### ISSUE TITLE
[REVIEW]: metricsgraphics: An R htmlwidget interface to the MetricsGraphics.js D3-based visualization library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#10]
**Submitting author:** @hrbrmstr (<a href="http://orcid.org/0000-0001-5670-2640">Bob Rudis</a>)
**Repository:** <a href="https://github.com/hrbrmstr/metricsgraphics" target="_blank">https://github.com/hrbrmstr/metricsgraphics</a>
**Version:** v0.9.1
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.50373" target="_blank">10.5281/zenodo.50373</a>
**Editor:** @arfon 
**Reviewer:** @amoeba
## Status

[![status](http://joss.theoj.org/papers/1677676c38bd118db5fe363a6eb3f88f/status.svg)](http://joss.theoj.org/papers/1677676c38bd118db5fe363a6eb3f88f)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/1677676c38bd118db5fe363a6eb3f88f"><img src="http://joss.theoj.org/papers/1677676c38bd118db5fe363a6eb3f88f/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/1677676c38bd118db5fe363a6eb3f88f/status.svg)]http://joss.theoj.org/papers/1677676c38bd118db5fe363a6eb3f88f
```
### General checks
- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/hrbrmstr/metricsgraphics">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v0.9.1)?
- [x] **Archive:** Does the <a target="_blank" href="10.5281/zenodo.50373">software archive</a> resolve?
### Functionality
- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have the performance claims of the software been confirmed?
### Documentation
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
### Software paper
- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hi @hrbrmstr. Many thanks for submitting to JOSS! 

The next step is to look for a couple of reviewers - if you have any suggestions please add them here. :rocket: 

@karthik - this do you have any suggestions?

**Comment by hrbrmstr** [comment]
@timelyportfolio &  @ramnathv come quickly to mind. I'll get some others.
Also, once I get the hang of this, Oliver & I will submit `iptools` as well.

**Comment by whedon** [comment]
Compiled paper PDF: [paper.pdf](https://github.com/openjournals/joss-reviews/files/249512/paper.pdf)

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers anyone interested in reviewing this?

**Comment by ramnathv** [comment]
@arfon What is expected in the review process?

**Comment by arfon** [comment]
@ramnathv we basically need the reviewer to work through the checklist at the [top of this issue](https://github.com/openjournals/joss-reviews/issues/10#issue-153024367).

There are also reviewer guidelines here: http://joss.theoj.org/about#reviewer_guidelines

If you're willing to review I'll add you to the `@openjournals/joss-reviewers` GitHub team which will give you permissions to edit the checklist.

> What are the timelines involved?

As soon as you're able :smile:

**Comment by amoeba** [comment]
Hey @hrbrmstr, great package. This is the first I've sat down with the Metrics library and it's great to have an htmlwidgets interface for it. Some notes:

- License: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?

    No. LICENSE file indicates @hrbrmstr is the sole copyright holder. Recommend adopting one of the OSI-approved LICENSES

- Version: Does the release version given match the GitHub release (v0.9.1)?

    No. The version that is installed when I run `install_packages('metricsgraphics')` is 0.9.0. Requesting guidance from @arfon on this and @hrbrmstr for comment on whether 0.9.1 has been submitted to CRAN or what its status is. I'm indifferent to this discrepancy.

- Archive: Does the software archive resolve?

    Mostly Yes: The link in this Issue doesn't work but the URL included a DOI, which I followed, which resolved to the [Zenodo page for the 0.9.1 release](http://zenodo.org/record/50373). Main README file also has the right link. Checking it off for now.

- Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

    (1,2,3) No. Recommend editing README.md to make clear. 
    As an aside, repository contains a CoC (CONDUCT.MD) which I think is fantastic.

- Paper

    See this section from http://joss.theoj.org/about#reviewer_guidelines:

    > Note the paper should not include software documentation such as API (Application Programming Interface) functionality, as this should be outlined in the software documentation.

    The paper contains a light amount of software documentation. The Summary section of the paper is fine but the Core Functionality section breaks with the above recommendation. I think the Core Functionality paragraph can be removed as it is redundant with the core software documentation.

- Tests

    The test suite exists but is minimal. This is a hard package to test because it relies on a the Metrics Graphics JS library which has its own test suite. I think what the author has done is good enough.

This is a solid submission with only minor revisions needed. The code is well-written, works as advertised, has plenty of useful examples, and contains complete and helpful documentation. The paper is concise and to the point. The software has a clear research application in that it increases the accessibility of a popular JavaScript charting library by integrating it directly into R.

Grade: (2) Minor Revisions

**Comment by wrathematics** [comment]
Hope it's ok if I chime in here.  Regarding the license, their package is actually licensed MIT.  You can confirm this by checking the License line in the DESCRIPTION file.  The reason the LICENSE file contains only a few snippets is per CRAN repository rules; the idea is that you need only fill out the missing lines in the "template" [here](https://www.r-project.org/Licenses/MIT).   The rules are explained in detail [here](https://cran.r-project.org/doc/manuals/R-exts.html#Licensing).

I do think the reviewer comment makes perfect sense.  In my opinion, CRAN's rule on this is bizarre and confusing, and I happen to think it actually violates the license (though I am not a lawyer so my opinion on this doesn't matter much).  CRAN is very picky about this, however, so it's not super obvious to me how best to conform R packages to the JOSS rules.  One can distribute full licenses in `inst/`, but then someone would have to know to look for them.  One could have the full license in an additional file named COPYING, and this could be added to .Rbuildignore to avoid issues with CRAN.  But then that's not really any less confusing.

I'm thinking of submitting a few R packages myself to JOSS, so I'm very curious to see how this is ultimately resolved.

**Comment by amoeba** [comment]
Okay by me and thanks a ton for the information, @wrathematics. I'm new to R packaging and wasn't aware of any of that. Eager to see what others have to say.

From `DESCRIPTION`: License: MIT + file LICENSE

That's super confusing since 'file LICENSE' would seem to disagree with MIT (given my near-zero knowledge of copyright law). I'll have to read up on the CRAN rules. Thanks again.

**Comment by hrbrmstr** [comment]
This. Is. *Awesome*.

I'm semi-AFK for the main part of the weekend but I'll try to get on the
edits tomorrow night.

#ty to all who are carving out cycles to make JOSS work. Pls feel free to
tap me as a reviewer for other submissions. I'll be glad to chip in.

-Bob

**Comment by arfon** [comment]
> This. Is. *Awesome*.

Yes @amoeba and @wrathematics many thanks for such a rapid and excellent review :zap:

> I'm thinking of submitting a few R packages myself to JOSS, so I'm very curious to see how this is ultimately resolved.

On the licensing issue - I would rather see a `LICENSE` file also included in the repository if possible as I think that's both more discoverable and explicit about the licensing terms.

> I'm semi-AFK for the main part of the weekend but I'll try to get on the edits tomorrow night.

@hrbrmstr - please just leave a message on this thread to let us know when you've made the updates.

> #ty to all who are carving out cycles to make JOSS work. Pls feel free to
> tap me as a reviewer for other submissions. I'll be glad to chip in.

If you're interested then perhaps you'd like to join the `@openjournals/joss-reviewers` team on GitHub. That way if any review opportunities arise then you'll be notified of them?

**Comment by arfon** [comment]
*Bump* @hrbrmstr - have you had a change to look at these suggested modifications?

**Comment by arfon** [comment]
> Bump @hrbrmstr - have you had a change to look at these suggested modifications?

👋 @hrbrmstr - are you still interested in making these edits so we can accept this submission?

**Comment by arfon** [comment]
@whedon assign @amoeba as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @amoeba

**Comment by arfon** [comment]
🎏 flagging this as stale 🎏 

If there's no update here by @hrbrmstr in the next month I'll assume they want this paper withdrawn.

**Comment by arfon** [comment]
> If there's no update here by @hrbrmstr in the next month I'll assume they want this paper withdrawn.

This paper is now withdrawn from JOSS.
