### ISSUE TITLE
[PRE REVIEW]: STEDY - Software for TEnsegrity DYnamics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1000]
**Submitting author:** @vaishnavtv (<a href="http://orcid.org/0000-0001-9897-0600">Venkata Vaishnav Tadiparthi</a>)
**Repository:** <a href="https://github.com/uqLab/stedy" target ="_blank">https://github.com/uqLab/stedy</a>
**Version:** v0.1.0
**Editor:** @labarba
**Reviewers:** @Kevin-Mattheus-Moerman, @ctdegroot

**Author instructions**

Thanks for submitting your paper to JOSS @vaishnavtv. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@vaishnavtv if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1000 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01000/joss.01000/10.21105.joss.01000.pdf)

**Comment by vaishnavtv** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by vaishnavtv** [comment]
In my submission, I suggested that @labarba be assigned as an editor, due to her experience with fluid dynamics. Was there a problem with that?

**Comment by arfon** [comment]
> In my submission, I suggested that @labarba be assigned as an editor, due to her experience with fluid dynamics. Was there a problem with that?

No, that should be OK I think. @labarba - would you be able to handle this submission for JOSS?

**Comment by labarba** [comment]
I'm a little worried that this software lists as a dependency the Matlab Optimization Toolbox, which is an additional thousand bucks over Matlab. How am I going to find reviewers for such a thing?

**Comment by ctdegroot** [comment]
I have access to academic licenses for Matlab and the Optimization Toolbox. I would be able to do the review.

**Comment by vaishnavtv** [comment]
Perfect! Thank you!

**Comment by moorepants** [comment]
I'm sorry I do not have access to Matlab. If it runs in Octave I can review.

**Comment by vaishnavtv** [comment]
Would one reviewer be sufficient? @labarba

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@ctdegroot : Are you still willing to be one of the reviewers for this submission? I will be looking for a second reviewer to help out.

**Comment by labarba** [comment]
@vaishnavtv : Your only reference in the paper is a manuscript that has been submitted but is not available without contacting the authors. Would you consider depositing your manuscript in a pre-print server? You can use arXiv, [engrXiv](https://engrxiv.org), or other. A majority of [journals accept preprints](https://en.wikipedia.org/wiki/List_of_academic_journals_by_preprint_policy) these days.

**Comment by labarba** [comment]
@Kevin-Mattheus-Moerman : Would you be able to review this submission for JOSS? It uses the Matlab Optimization Toolbox.

**Comment by Kevin-Mattheus-Moerman** [comment]
@labarba sure thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
Perhaps folks at https://github.com/NASA-Tensegrity-Robotics-Toolkit e.g. @apsabelhaus (who contributed to https://github.com/apsabelhaus/tInvKin) would be interested in reviewing this?

**Comment by Kevin-Mattheus-Moerman** [comment]
My colleague at MIT might be interested in this too. @cybanical fancy testing some code to study dynamics of tensegrity structures? (also I recommend that you upgrade your github profile with an ORCID link, your real name, and some affiliation information etc).

**Comment by labarba** [comment]
@whedon assign @Kevin-Mattheus-Moerman as reviewer

**Comment by labarba** [comment]
Thank you, @Kevin-Mattheus-Moerman ! 
Let's wait and see if one of the folks you recommend can volunteer the second review, and then we can get it started.

**Comment by ctdegroot** [comment]
@labarba Yes, I am still able to review it

**Comment by labarba** [comment]
@whedon add @ctdegroot as reviewer

**Comment by labarba** [comment]
@arfon : Can you tell why our dear bot `@whedon` is ignoring my commands?

**Comment by whedon** [comment]
OK, the reviewer is @Kevin-Mattheus-Moerman

**Comment by whedon** [comment]
OK, @ctdegroot is now a reviewer

**Comment by labarba** [comment]
So ... I guess `@whedon` was sleeping. Now we're set!

**Comment by labarba** [comment]
@whedon start review

**Comment by apsabelhaus** [comment]
Dear all - very nice to meet you!

I'm happy to be a reviewer, though I'm not sure what this entails, I'm new to JOSS. I have the MATLAB Optimization Toolbox.

On a different note, the field of dynamics derivations for tensegrity structures is actually very extensive, and it would be very good to include many other knowledgeable experts in the area. There are well-known expressions for the dynamics of these structures that could be verified against the authors' code. In fact, the authors have a colleague at Texas A&M who is a forerunner in the area - Robert Skelton - who can refer good reviewers for this code. Other significant authors in the field include Cornel Sultan, Josep Mirats-Tur, and their students.

Of particular note would be other contributors to NTRTsim (https://github.com/NASA-Tensegrity-Robotics-Toolkit) such as Brian Mirletz @brtietz and the current maintainer Jonathan Bruce @JEB12345. Also, Jeffrey Friesen at @Jfriesen222 has already derived the dynamics for a large set of tensegrity robots. 

Please let me know how you might like from me.

**Comment by apsabelhaus** [comment]
Another good reviewer would be Mauricio de Oliviera at UC San Diego.

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1042. Feel free to close this issue now!

**Comment by Kevin-Mattheus-Moerman** [comment]
@apsabelhaus thanks for those suggestions!

**Comment by cybanical** [comment]
@Kevin-Mattheus-Moerman <https://github.com/Kevin-Mattheus-Moerman> This
looks super interesting, but it looks like I'm too slammed right now. I've
got two other papers to review right now for ICRA.
*_____________________________________*
*MATTHEW CARNEY | Research Assistant and PhD Candidate **| *Mechatronics
Design Engineer
MIT Media Lab | Biomechatronics
75 Amherst St. | E14-274G | Cambridge, MA 02142 USA
biomech.media.mit.edu
<https://www.media.mit.edu/groups/biomechatronics/overview/> |
matthematic.com | IG:@matt.thematic
<https://www.instagram.com/matt.thematic/>

**Comment by addyhsu** [comment]
@labarba The software has been archived on Zenodo. DOI: 10.5281/zenodo.2527084

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.2527084 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2527084" target="_blank">10.5281/zenodo.2527084</a> is the archive.

**Comment by labarba** [comment]
Wrong issue. We should be at https://github.com/openjournals/joss-reviews/issues/1042
