### ISSUE TITLE
[REVIEW]: TensorFlow.jl: An Idiomatic Julia Front End for TensorFlow

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1002]
**Submitting author:** @malmaud (<a href="http://orcid.org/0000-0002-5352-2086">Jonathan Matthew Malmaud</a>)
**Repository:** <a href="https://github.com/malmaud/TensorFlow.jl" target ="_blank">https://github.com/malmaud/TensorFlow.jl</a>
**Version:** v0.10.1
**Editor:** @arokem
**Reviewer:** @jekbradbury
**Archive:** <a href="https://doi.org/10.5281/zenodo.1476107" target="_blank">10.5281/zenodo.1476107</a>

## Status

[![status](http://joss.theoj.org/papers/64507095a9c1ba68bd548f6670ea5db6/status.svg)](http://joss.theoj.org/papers/64507095a9c1ba68bd548f6670ea5db6)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/64507095a9c1ba68bd548f6670ea5db6"><img src="http://joss.theoj.org/papers/64507095a9c1ba68bd548f6670ea5db6/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/64507095a9c1ba68bd548f6670ea5db6/status.svg)](http://joss.theoj.org/papers/64507095a9c1ba68bd548f6670ea5db6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/malmaud/TensorFlow.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jekbradbury, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/malmaud/TensorFlow.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.10.1)?
- [x] **Authorship:** Has the submitting author (@malmaud) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jekbradbury it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01002/joss.01002/10.21105.joss.01002.pdf)

**Comment by jekbradbury** [comment]
Accept.

Looks good to me. A couple quibbles (that don't block acceptance):
- The paper has a minor formatting issue where the table at the bottom of the first page overlaps with margin elements.
- I think this sentence should be dropped or reworded: "For example, it allows Julia code to operate on TPUs by virtue of using the same TensorFlow graph syntax as Python's TensorFlow client, even though there is no native Julia TPU compiler." This is because I don't believe anyone has actually demonstrated TensorFlow.jl code running on a TPU (and I believe significant external work would be needed to do this, because the TPU API is more than just TensorFlow graphs; you also have to use infeed/outfeed and explicitly invoke XLA compilation etc.)...and also because the last clause in the sentence may not be true for much longer :slightly_smiling_face:.

**Comment by malmaud** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01002/joss.01002/10.21105.joss.01002.pdf)

**Comment by malmaud** [comment]
Thanks @jekbradbury, I agree with all your points. I've removed the TPU clause and fixed the table formatting.

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by arokem** [comment]
@jekbradbury : looks like most/all the issues have been addressed? Is this paper ready to be accepted from your point of view?

@malmaud: comments from me: 

- [ ] In the third paragraph of the summary section, you have a sentence: "This * can correspond to ...". I believe this should be "Thus, * can correspond...". Do I understand correctly? 
- [ ] The first sentence in the fourth paragraph might be missing a word. Maybe "TensorFlow.jl aims to..."
- [ ] The word "indices" is mis-spelled as "indicies" in the bottom of page 2
- [ ] The word "paramterized" is mis-spelled as "paramatrised"
- [ ] In the first paragraph of the "Challenges" section, you have the fragment: "... and does not include many conveients for the definition of training of graphs". How about replacing that with: "... and does not include interfaces for conveniently defining the training of graphs".  Is that statement true, by the way? Seems unlikely. 
- [ ] The second paragraph of this section includes a couple of typos: "Graidnet" and "ptimizers". 
- I still see a statement about TPUs in the manuscript currently on `master` in the last paragraph. I think this statement should at least be qualified (or better, removed).

**Comment by malmaud** [comment]
Thanks for these comments!

* I fixed the typos you pointed out.
* The intent of the 'challenges' section is that TensorFlow's C API exposes minimal low-level functionality, with most of the complexity of building and training a neural net implemented in Python on top of the C API. I clarified the wording.
* I removed all references to TPUs. While I do think it would be pretty easy to get TensorFlow.jl to run on TPUs, it isn't implemented yet so I agree that removal makes sense.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01002/joss.01002/10.21105.joss.01002.pdf)

**Comment by jekbradbury** [comment]
@arokem: Yes, the paper's ready to be accepted from my POV.

**Comment by arokem** [comment]
@jekbradbury : thank you for the review! 👏 

@malmaud : the paper is ready to be accepted! To go ahead with the archiving of the paper, please create a DOI for the software (e.g., by tagging a release and uploading it to zenodo.org). Once you have a DOI, we can go ahead with the rest of the process.

**Comment by malmaud** [comment]
OK, I have a DOI: 10.5281/zenodo.1476107. Thanks @jekbradbury and @arokem for handling the review.

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.1476107 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1476107" target="_blank">10.5281/zenodo.1476107</a> is the archive.

**Comment by arokem** [comment]
@arfon : I believe this article is ready to go!

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1002 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    17    0    17    0     0    251      0 --:--:-- --:--:-- --:--:--   253
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/42

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/42, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/43
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01002](https://doi.org/10.21105/joss.01002)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@jekbradbury - many thanks for your review here and to @arokem for editing this submission ✨ 

@malmaud - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.01002 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01002/status.svg)](https://doi.org/10.21105/joss.01002)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01002">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01002/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01002/status.svg
   :target: https://doi.org/10.21105/joss.01002
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01002/status.svg)](https://doi.org/10.21105/joss.01002)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by oxinabox** [comment]
Cool, nice.
I am only finding put about thus now, as I guess the JOSS script doesn't tag coauthors.

**Comment by oxinabox** [comment]
@arokem  I  was sharing a link around to the released paper,
and some errors were pointed out to me.
 
 - the citation for the MLandPL paper broke and so it didn't end up in the reference list.
 - the cited article for the Julia language is the 2014 preprint, rather than the final 2017 article
 - and a couple of typos slipped through.

What should we do?
Does the JOSS process allow us to submit an updated version?

**Comment by arfon** [comment]
@oxinabox - feel free to update your paper in `master` on https://github.com/malmaud/TensorFlow.jl and check that it's fixed by typing `@whedon generate pdf` here.

Once you're happy with the changes, I can update the final accepted version.

**Comment by oxinabox** [comment]
Excellent.

**Comment by malmaud** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by malmaud** [comment]
Done

**Comment by arfon** [comment]
Paper compilation is failing for some reason right now. I've compiled locally: 
[10.21105.joss.01002.pdf](https://github.com/openjournals/joss-reviews/files/2549836/10.21105.joss.01002.pdf)

**Comment by oxinabox** [comment]
@Whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by oxinabox** [comment]
@malmaud @arfon  was the new version pushed out to the public?

**Comment by arfon** [comment]
@oxinabox does it look correct here? https://doi.org/10.21105/joss.01002

**Comment by oxinabox** [comment]
It seems it does not quiet have the last fixes in 
https://github.com/malmaud/TensorFlow.jl/pull/469/

**Comment by arfon** [comment]
> It seems it does not quiet have the last fixes in malmaud/TensorFlow.jl#469

OK, I've just regenerated (and updated) the live paper.

**Comment by oxinabox** [comment]
Awesome, thanks.
