### ISSUE TITLE
[REVIEW]: SeqTools: A python package for easy transformation, combination and evaluation of large datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1006]
**Submitting author:** @nlgranger (<a href="http://orcid.org/0000-0003-2943-9888">Nicolas Granger</a>)
**Repository:** <a href="https://github.com/nlgranger/SeqTools" target ="_blank">https://github.com/nlgranger/SeqTools</a>
**Version:** v0.9.0
**Editor:** @pjotrp
**Reviewer:** @Benjamin-Lee
**Archive:** <a href="https://doi.org/10.5281/zenodo.1472094" target="_blank">10.5281/zenodo.1472094</a>

## Status

[![status](http://joss.theoj.org/papers/527a3c6e78ef0b31f93bbd29235d5a0b/status.svg)](http://joss.theoj.org/papers/527a3c6e78ef0b31f93bbd29235d5a0b)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/527a3c6e78ef0b31f93bbd29235d5a0b"><img src="http://joss.theoj.org/papers/527a3c6e78ef0b31f93bbd29235d5a0b/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/527a3c6e78ef0b31f93bbd29235d5a0b/status.svg)](http://joss.theoj.org/papers/527a3c6e78ef0b31f93bbd29235d5a0b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/nlgranger/SeqTools" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Benjamin-Lee, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @pjotrp know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nlgranger/SeqTools">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.9.0)?
- [x] **Authorship:** Has the submitting author (@nlgranger) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Benjamin-Lee it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1006 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01006/joss.01006/10.21105.joss.01006.pdf)

**Comment by pjotrp** [comment]
@nlgranger to expedite the review process do you mind going through above list of check boxes and make sure they can be ticked (you can't tick them). Also check the PDF output carefully. Ping us here when you are done.

**Comment by pjotrp** [comment]
Thanks! You can bump before final publishing. 

@Benjamin-Lee you can start review. Please read the reviewer guidelines above

**Comment by Benjamin-Lee** [comment]
All checks have passed!

**Comment by pjotrp** [comment]
The review process is now complete. To finalize your submission and accept your paper in JOSS, we need two things. First, can you confirm that all references in your bibliography have a DOI (if one exists). 

Second, we need you to deposit a copy of your software repository (including any revisions made during the JOSS review process) with a data-archiving service. To do so:

 1. Create [a GitHub release](https://help.github.com/articles/creating-releases/) of the current version of your software repository
 2. Deposit that release with [Zenodo](https://zenodo.org/), [figshare](https://figshare.com/), or a similar DOI issuer.
 3. Post a comment here with the DOI for the release.

**Comment by nlgranger** [comment]
Hi, thank you all for the review.
The bibliography items do not have a DOI (one is a white-paper, the other a workshop paper).
The doi is: https://doi.org/10.5281/zenodo.1472094

**Comment by pjotrp** [comment]
@whedon set  10.5281/zenodo.1472094 as active

**Comment by pjotrp** [comment]
@whedon set  10.5281/zenodo.1472094 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1472094" target="_blank">10.5281/zenodo.1472094</a> is the archive.

**Comment by pjotrp** [comment]
@arfon we are ready to R&R

**Comment by arfon** [comment]
> Letting you know, @arfon is currently OOO until Monday, October 29th 2018. ❤️

This is not actually true. I'm here!

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/36

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/36, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/37
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01006](https://doi.org/10.21105/joss.01006)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@Benjamin-Lee - many thanks for your review here and to @pjotrp for editing this submission ✨ 

@nlgranger - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.01006 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01006/status.svg)](https://doi.org/10.21105/joss.01006)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01006">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01006/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01006/status.svg
   :target: https://doi.org/10.21105/joss.01006
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01006/status.svg)](https://doi.org/10.21105/joss.01006)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by nlgranger** [comment]
@Benjamin-Lee @pjotrp @arfon Thank you very much!
