### ISSUE TITLE
[REVIEW]: idpflex: Analysis of Intrinsically Disordered Proteins by Comparing Simulations to Small Angle Scattering Experiments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1007]
**Submitting author:** @jmborr (<a href="http://orcid.org/0000-0002-0866-8158">Jose M. Borreguero</a>)
**Repository:** <a href="https://github.com/jmborr/idpflex.git" target ="_blank">https://github.com/jmborr/idpflex.git</a>
**Version:** 0.1.7
**Editor:** @brainstorm
**Reviewer:** @gjeuken
**Archive:** <a href="https://doi.org/10.5281/zenodo.2179293" target="_blank">10.5281/zenodo.2179293</a>

## Status

[![status](http://joss.theoj.org/papers/f55f6e3726e1d794979469fd1d1b1557/status.svg)](http://joss.theoj.org/papers/f55f6e3726e1d794979469fd1d1b1557)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f55f6e3726e1d794979469fd1d1b1557"><img src="http://joss.theoj.org/papers/f55f6e3726e1d794979469fd1d1b1557/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f55f6e3726e1d794979469fd1d1b1557/status.svg)](http://joss.theoj.org/papers/f55f6e3726e1d794979469fd1d1b1557)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jmborr/idpflex.git" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@gjeuken, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @brainstorm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jmborr/idpflex.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.5)?
- [x] **Authorship:** Has the submitting author (@jmborr) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @gjeuken it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01007/joss.01007/10.21105.joss.01007.pdf)

**Comment by gjeuken** [comment]
@brainstorm 
Hi Roman,
I have some comments and questions.

First of all, everything seems to be in good order, according to the checklist. I would like to see some more formalism in the method description, as it is quite general, but I'm not sure it's in the scope of the Journal. (Am I wrong here?)

* Their version number is 0.1.6 and not 0.1.5 as it is stated above.
* For the **statement of need** they do a good job on the paper but it is absent in the documentation.
* I was unable to run their example notebooks, most likely due to a path mixup, although I didn't check enough to be sure. The error I get is:
`FileNotFoundError: [Errno 2] No such file or directory: 'crysol': 'crysol'`
But they do have unit tests and they work ok.

Lastly, I'm not sure how deep I should go investigating the functionality of the software. If you could make this more clear to me I would be very grateful.

But as I said before, overall it looks very good.

**Comment by brainstorm** [comment]
@jmborr, can you fix the issues @gjeuken encountered?

@arfon, as I see it, @gjeuken has very good points regarding more scope/expectations on the reviewing task itself, a good one to discuss with the editorial board perhaps? Thanks @gjeuken for rising the issue!

**Comment by jmborr** [comment]
@brainstorm Sorry, it was my intention to start working on these issues today but had not the time. I will address them tomorrow.

**Comment by jmborr** [comment]
@brainstorm @gjeuken Regarding the insertion of an **statement of need** in the documentation, I though of inserting the Summary paper I submitted here in JOSS. Is this admissible?

**Comment by jmborr** [comment]
@gjeuken [crysol](https://www.embl-hamburg.de/biosaxs/crysol.html) is a third-party software to generate  X-ray patterns, given an arrangement of atomic positions. It is assumed to be installed under any of the directories of `PATH`.
What I can do is to include the output of crysol in helper repository [idpflex_data](https://github.com/jmborr/idpflex_data). The example notebook would then check for an installation of crysol in the user's computer and if a `Not-Found` error is raised, then the notebook will fetch the crysol output from the helper repository. How does that sound?

**Comment by brainstorm** [comment]
@jmborr What Gustavo meant is that you should include the statement of need in the documentation **as well**, it's good where it is already, but would be better to have it in **both** places.

**Comment by gjeuken** [comment]
@jmborr 
In the case of CRYSOL I think just a link to the software would suffice.
Your suggestion is of course better, but that's up to you.

**Comment by jmborr** [comment]
This PR dealt with the statement of need:
https://github.com/jmborr/idpflex/pull/74

Unfortunately, the documentation build in [readthedocs](https://readthedocs.org/projects/idpflex/builds/) is failing because of a known problem for one of the dependency packages ([mdtraj](https://github.com/mdtraj/mdtraj/issues/1119)) when building the documentation in a virtual environment. I am going to try building the documentation in readthedocs [with conda](https://docs.readthedocs.io/en/latest/conda.html), instead of virtualenv.

**Comment by jmborr** [comment]
@gjeuken @brainstorm This [PR](https://github.com/jmborr/idpflex/pull/76) dealt with building correctly the [documentation in readthedocs](https://idpflex.readthedocs.io/en/latest/). Now the statement-of-need is public :smiley:

**Comment by gjeuken** [comment]
@brainstorm 
Everything seems in good order, but I did not check the functionality box as I do not yet know the scope of the functionality review.

**Comment by brainstorm** [comment]
@gjeuken According to https://joss.readthedocs.io/en/latest/review_criteria.html#functionality, you should check the core functionality, in other words whether the software generates the expected outputs given some inputs... with your proteomics knowledge, can you verify that the outputs match what the software claims to achieve?

**Comment by jmborr** [comment]
@gjeuken I suggest:
1. running the unit tests in your machine. After all, automatic testing with Travis only covers a few configurations.
2. running the two jupyter notebooks. These cover almost all of the software functionality. Currently, some of the input is generated by third party software ([CRYSOL](https://www.embl-hamburg.de/biosaxs/crysol.html), [DSSP](http://www.cmbi.ru.nl/xssp/)). I can modify the notebooks to make sure that the notebooks will fetch the required input from the data repository in case you don't have this third party software installed.

Does this sound good?

**Comment by gjeuken** [comment]
@brainstorm 
Sorry for being confusing, but my question is whether or not I should evaluate the "correctness" of the output in some way, or how much I should go down that path. That would require me to evaluate the methods themselves and for such, I would need a better description of them and it would resemble a more traditional article review.
An alternative is just to check if the input and output are in the correct format.

@jmborr 
I've run the unit test and they all passed.
Regarding point 2, I think you already did some of those changes, but I could be wrong. I'm still having problems running the notebooks past the CRYSOL input, but I'm positive I could solve them with some effort if this is the direction the review should go.

Again, I'm sorry if I am confusing and dragging this too much, but this is a different review system than what I'm used to in general.

**Comment by jmborr** [comment]
@gjeuken I will solve the issue regarding DSSP much in the same way as I did with CRYSOL. Notebook `hiAPP_clustering.ipynb` is a system test in itself because the task is to find the combination of clusters that provide the best fit to the experimental X-Ray profile. In the notebook, the experimental X-Ray profile is actually composed of three particular clusters, so the mail goal of the notebook is to show that the fitting procedure that scans the clustering tree is able to recover those three clusters. The rest of the notebook is a showcase of what properties one can calculate on the identified clusters for better characterization of the protein ensemble of structures.

**Comment by jmborr** [comment]
This [PR](https://github.com/jmborr/idpflex/pull/79) dealt with checking for DSSP. If not found, the notebook fetches the output files from the data repository.

**Comment by brainstorm** [comment]
@jmborr Please do you have a moment to review @gjeuken input and so we can submit and archive the DOI for your JOSS submission? :) Great work so far, thanks everyone 👍

**Comment by jmborr** [comment]
@brainstorm sorry, I had some deadline at work. I'm looking into this now...

**Comment by jmborr** [comment]
@brainstorm @gjeuken I have split the summary paper into several paragraphs, adding more details. Please let me know how it looks now (https://idpflex.readthedocs.io/en/latest/)

**Comment by brainstorm** [comment]
@jmborr Muchas gracias! ;)

@gjeuken To be clear, there's no need for you to fix the issues, but reporting them is a must... can you run the notebook successfully now?

**Comment by gjeuken** [comment]
Hi all, sorry about the delay.
I still haven't manage to run the entire Notebook. the specific error I get is the following:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-12-8bed65896dd2> in <module>
----> 1 [profile.to_ascii(name) for profile, name in zip(profiles, crysol_names)]
      2 propagator_size_weighted_sum(profiles, cl.tree)

NameError: name 'profiles' is not defined
```

Which happens because the profile object is created in else clause that is never executed.

But just to be clear, my main question regarding this review was how much in detail should I look at the methods, and that is because I am used to reviewing papers for scientific magazines, where the mathematical method is the crucial in the article.
To answer my question I took the liberty of looking at other accepted articles here and it seams like this paper is not lacking in content in that respect. So I am sorry for causing this unecessary delay.

**Comment by Fahima-Islam** [comment]
@gjeuken No need to be sorry, I'm very grateful you found a bug in the notebook! I have just pushed the fix to master.
Again, thanks for running the notebook :smiley:

**Comment by jmborr** [comment]
@gjeuken ooops, I posted through the github page that the other collaborator had left open in my browser hahaha.

**Comment by gjeuken** [comment]
@jmborr 
Perfect!
On the hiAPP_clustering_with_properties notebook you need to 
`from distutils.spawn import find_executable`
And both of them work perfectly.

@brainstorm 
With the notebooks now running, I was able to verify the complete functionality of the software, and I believe that was the only thing still remaining. :)

To both, again, sorry if I caused any delay in the process due to my confusion about the methods.

**Comment by jmborr** [comment]
@gjeuken oops, that was sloppy from my part, sorry :blush: 
I just pushed the fix to master.

**Comment by brainstorm** [comment]
Thanks again for your dedication @gjeuken and @jmborr, nothing to be sorry about, good job!

@jmborr Can you let me know when you have a release ready with all the (known) bugs fixed?

**Comment by jmborr** [comment]
I have uploaded the new version 0.1.7 with all the corrections to [pipy](https://pypi.org/project/idpflex/), and the [corrected documentation](https://idpflex.readthedocs.io/en/stable/)

**Comment by brainstorm** [comment]
That's great, thanks @jmborr, can you deposit a release tarball on zenodo and share the DOI here?

**Comment by jmborr** [comment]
@brainstorm never uploaded to *zenodo*, I am confused. Here's a screenshot for uploading the tarball. I assume the *Upload type* is **software** but I'm confused regarding the DOI. Should I click the *Reserve DOI* button?
![zenodo](https://user-images.githubusercontent.com/1136006/49738234-df661480-fc5c-11e8-940f-bef063010285.PNG)

**Comment by brainstorm** [comment]
Yes, have a look at the other closed review issues in this repo, i.e: https://github.com/openjournals/joss-reviews/issues/1102#issuecomment-442090116, reserving a zenodo DOI is part of the process.

**Comment by jmborr** [comment]
@brainstorm very good.
[10.5281/zenodo.2179293](https://zenodo.org/record/2179293#.XA73UctKjBs)

**Comment by brainstorm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01007/joss.01007/10.21105.joss.01007.pdf)

**Comment by brainstorm** [comment]
@whedon set 10.5281/zenodo.2179293 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2179293" target="_blank">10.5281/zenodo.2179293</a> is the archive.

**Comment by brainstorm** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/113

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/113, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by brainstorm** [comment]
@jmborr After reviewing the paper a bit more closely, it seems that there's a fair bit of repetition between the abstract and the actual paper.md, is that intentional?

**Comment by jmborr** [comment]
@brainstorm nope, I just pushed to master the removal of the duplicated paragraph

**Comment by brainstorm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by jmborr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by jmborr** [comment]
@brainstorm we submitted the command at the same time :smile:

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01007/joss.01007/10.21105.joss.01007.pdf)

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01007/joss.01007/10.21105.joss.01007.pdf)

**Comment by jmborr** [comment]
@brainstorm got to fix the references

**Comment by jmborr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01007/joss.01007/10.21105.joss.01007.pdf)

**Comment by jmborr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01007/joss.01007/10.21105.joss.01007.pdf)

**Comment by jmborr** [comment]
@brainstorm OK, now the proof looks very much correct. Are following steps:
- issue `@whedon accept`
- Check the final proof
- issue `@whedon accept deposit=true`
??

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/116
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01007](https://doi.org/10.21105/joss.01007)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@gjeuken - many thanks for your review here and to @brainstorm for editing this submission ✨ 

@jmborr - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01007/status.svg)](https://doi.org/10.21105/joss.01007)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01007">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01007/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01007/status.svg
   :target: https://doi.org/10.21105/joss.01007
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01007/status.svg)](https://doi.org/10.21105/joss.01007)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by jmborr** [comment]
@arfon @brainstorm @gjeuken Thanks a million for giving me a chance to publish in JOSS and for the effort to carry out this review!  💃

**Comment by gjeuken** [comment]
Great to be a part of this, and congrats @jmborr for the excellent work! :)
And again, sorry for any delays due to confusion on my part.
