### ISSUE TITLE
[PRE REVIEW]: wolfexplorer: a tool for visualization and exploration of complex multi-year multi-specimen datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1009]
**Submitting author:** @zkuralt (<a href="http://orcid.org/0000-0001-7201-4282">Žan Kuralt</a>)
**Repository:** <a href="https://github.com/romunov/wolfexplorer" target ="_blank">https://github.com/romunov/wolfexplorer</a>
**Version:** v0.9
**Editor:** @trallard
**Reviewers:** @amoeba

**Author instructions**

Thanks for submitting your paper to JOSS @zkuralt. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@zkuralt if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @trallard it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1009 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: tags, authors, affiliations, date, bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @trallard - would you be willing to edit this submission for JOSS?

**Comment by trallard** [comment]
Sure @arfon

**Comment by arfon** [comment]
> @whedon assign @trallard as editor

@whedon needs commands to be issues in separate comments currently sorry.

**Comment by arfon** [comment]
@zkuralt - please take at look at the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) in our submission requirements and format the YAML header of your paper the same way. Also, please note that YAML is white-space sensitive when making these changes.

Once you've made your changes you can ask @whedon to recompile your paper with the command `@whedon generate pdf`

**Comment by trallard** [comment]
👋🏼 Hi @zkuralt I am happy to serve as the editor for this submission. As Arfon pointed out it seems that the `title` header is not properly indented.

Also, do you have any reviewers in mind? You can see the list of reviewers using the command `@whedon list reviewers`

**Comment by zkuralt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01009/joss.01009/10.21105.joss.01009.pdf)

**Comment by zkuralt** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by zkuralt** [comment]
@trallard I checked the list of reviewers and the ones listed below fit the area of wolfexplorer.

amoeba
jsta
pboesu
jhollist
ethanwhite

**Comment by trallard** [comment]
Hello :wave: @amoeba @jsta @pboesu @jhollist @ethanwhite  would any of you be interested in reviewing this submission? 
We'd ideally like to have two editors looking at this

**Comment by amoeba** [comment]
Hi @trallard 	I could probably commit to getting a review on by November 15th if that works for you. Please let me know and I can plan on it.

**Comment by trallard** [comment]
Hi @amoeba, thanks for offering 🎉. This would work perfectly, that would give us time to find a second reviewer

**Comment by ethanwhite** [comment]
I can't right now. Sorry

**Comment by trallard** [comment]
@whedon  assign @amoeba as reviewer

**Comment by trallard** [comment]
No worries @ethanwhite 

@jsta @pboesu @jhollist would any of you have a chance to help with this review?

**Comment by jhollist** [comment]
Sorry for not responding sooner.

Unfortunately I am going to have to pass as well.

**Comment by jsta** [comment]
Likewise, my review queue is full. Best of luck!

**Comment by trallard** [comment]
@whedon assign @amoeba as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @amoeba

**Comment by trallard** [comment]
I am going to open the review issue for this submission for now since we have @amoeba  confirmed for mid-November

I will try and find a second reviewer in the meantime 🤞

**Comment by trallard** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1064. Feel free to close this issue now!

**Comment by zkuralt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01009/joss.01009/10.21105.joss.01009.pdf)

**Comment by zkuralt** [comment]
I suspect that whedon generates PDF from master branch. We will generate it again after merging joss_review branch to master.

**Comment by trallard** [comment]
Yes by default it uses master

I can see the paper correctly unless you have been working on an alternate branch for corrections and stuff @zkuralt

**Comment by trallard** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

```

**Comment by trallard** [comment]
@whedon generate pdf from branch joss_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1009 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    304      0 --:--:-- --:--:-- --:--:--   306
Error reading bibliography ./paper.bib (line 121, column 5):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF
