### ISSUE TITLE
[PRE REVIEW]: ReproZip

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#101]
**Submitting author:** @remram44 (<a href="http://orcid.org/0000-0002-0524-2282">Rémi Rampin</a>)
**Repository:** <a href="https://github.com/ViDA-NYU/reprozip" target ="_blank">https://github.com/ViDA-NYU/reprozip</a>
**Version:** 1.0.8
**Editor:** @acabunoc
**Reviewer:** @stain

**What this issue is for**

Thanks for submitting your paper to JOSS @remram44. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @acabunoc it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by arfon** [comment]
👋  @acabunoc - would you be able to edit this for us? It looks like `@jsta` might be a good reviewer for this one: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv#L22

**Comment by remram44** [comment]
Review is for [version 1.0.8](https://github.com/ViDA-NYU/reprozip/tree/1.0.8), [10.5281/zenodo.159604](https://doi.org/10.5281/zenodo.159604). Required paper.md is [in branch `joss-paper`](https://github.com/ViDA-NYU/reprozip/tree/joss-paper/paper).

**Comment by acabunoc** [comment]
Hey @jsta, would you be up for reviewing this?

**Comment by stain** [comment]
I can review it if @jsta doesn't have time.

**Comment by jsta** [comment]
Go head @stain.  This looks very interesting but I don't have time currently. I would be interested in hearing whether this tool might be easier for novices to use than Docker.

**Comment by acabunoc** [comment]
Thanks so much @stain & @jsta! I'll add you as a review @stain 😄

**Comment by acabunoc** [comment]
@whedon assign @stain as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @stain

**Comment by acabunoc** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by acabunoc** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/107. Feel free to close this issue now!

**Comment by vchuravy** [comment]
:warning: [An error happened when generating the pdf](https://github.com/JuliaCon/proceedings-papers/actions/runs/3387796496?check_suite_focus=true).
