### ISSUE TITLE
[PRE REVIEW]: TipToft: detecting plasmids contained in uncorrected long read sequencing data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1010]
**Submitting author:** @andrewjpage (<a href="http://orcid.org/0000-0001-6919-6062">Andrew Page</a>)
**Repository:** <a href="https://github.com/andrewjpage/tiptoft" target ="_blank">https://github.com/andrewjpage/tiptoft</a>
**Version:** v0.1.4
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @ctb, @kapsakcj, @azneto

**Author instructions**

Thanks for submitting your paper to JOSS @andrewjpage. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@andrewjpage if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1010 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dbdd2bfb2d31/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@mgymrek - would you be willing to edit this submission for JOSS?

**Comment by arfon** [comment]
@andrewjpage - please take at look at the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) in our submission requirements and format the YAML header of your paper the same way. Also, please note that YAML is white-space sensitive when making these changes.

Once you've made your changes you can ask @whedon to recompile your paper with the command `@whedon generate pdf`

**Comment by andrewjpage** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01010/joss.01010/10.21105.joss.01010.pdf)

**Comment by andrewjpage** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01010/joss.01010/10.21105.joss.01010.pdf)

**Comment by andrewjpage** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01010/joss.01010/10.21105.joss.01010.pdf)

**Comment by andrewjpage** [comment]
I would like to propose the following reviewers:
@kapsakcj
@ctb
@azneto

**Comment by kapsakcj** [comment]
I'd also be happy to review. Thanks for nominating me to review @andrewjpage !  I will say though, that this would be my first time formally reviewing a manuscript and first time reviewing open-source software, so any advice or instructions would be welcomed. I have found the JOSS reviewer guidelines [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) to get me started. If you'd like to choose a more experienced reviewer, that would be fine with me.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @ctb as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ctb

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @kapsakcj as reviewer

**Comment by whedon** [comment]
OK, @kapsakcj is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@kapsakcj thanks for your comments. I am here to guide you all through the review process. Let me know if you have any questions. We will be recruiting multiple reviewers. I hope this first review experience will be a good one. Thanks! :robot: :rocket:

**Comment by ctb** [comment]
(I've reviewed a few JOSS papers, and had a few reviewed; never seen more than one reviewer, much less three. Is this a new policy?)

**Comment by danielskatz** [comment]
We've frequently moved to two

**Comment by ctb** [comment]
(a third is being solicited for this 'un)

**Comment by danielskatz** [comment]
For me, the number depends on my expertise on the topic

**Comment by Kevin-Mattheus-Moerman** [comment]
@ctb I tend to aim for at least two reviewers. Since this submission is off topic for me I intend to recruit at least one more. I think, unless it delays the review process, the more the merrier.

**Comment by azneto** [comment]
I'd be happy to do it, though it's my first time reviewing a submission for JOSS. Feel free to choose a more experienced reviewer.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @azneto as reviewer

**Comment by whedon** [comment]
OK, @azneto is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @azneto that is fine. prior experience with JOSS is not a requirement. I'm here to guide you through the process.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1021. Feel free to close this issue now!

**Comment by fmaguire** [comment]
@Kevin-Mattheus-Moerman Sorry about the slow reply, I've been away on holiday and only just got back.  Looks like you are sorted for this one but I'd be happy to review other submission in future.
