### ISSUE TITLE
[PRE REVIEW]: Ising_OPV v4.0: Experimental Tomography Data Import, Interpretation, and Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1011]
**Submitting author:** @MikeHeiber (<a href="http://orcid.org/0000-0002-1567-5663">Michael Heiber</a>)
**Repository:** <a href="https://github.com/MikeHeiber/Ising_OPV" target ="_blank">https://github.com/MikeHeiber/Ising_OPV</a>
**Version:** v4.0.0-rc.2
**Editor:** @katyhuff
**Reviewers:** @myousefi2016, @stuartcampbell, @mdoucet

**Author instructions**

Thanks for submitting your paper to JOSS @MikeHeiber. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@MikeHeiber if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @labarba - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
PDF failed to compile for issue #1011 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    167      0 --:--:-- --:--:-- --:--:--   168
pandoc-citeproc: reference pfannmoeller2013ees not found
pandoc-citeproc: reference vanbavel2009nl not found
pandoc-citeproc: reference pfannmoeller2013ees not found
pandoc-citeproc: reference proudian2018arXiv not found
pandoc-citeproc: reference heiber2018ising4 not found
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.265 ...{Acknowledgments}\label{acknowledgments}}

Looks like we failed to compile the PDF

**Comment by MikeHeiber** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by MikeHeiber** [comment]
I would suggest @stuartcampbell as a potential reviewer that is knowledgeable about C++ and materials science.

**Comment by MikeHeiber** [comment]
@whedon generate pdf from branch joss-edits

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-edits. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1011 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    180      0 --:--:-- --:--:-- --:--:--   180
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.266 ...{Acknowledgments}\label{acknowledgments}}

Looks like we failed to compile the PDF

**Comment by MikeHeiber** [comment]
@whedon generate pdf from branch joss-edits

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-edits. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1011 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    139      0 --:--:-- --:--:-- --:--:--   140
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.279 

Looks like we failed to compile the PDF

**Comment by MikeHeiber** [comment]
@whedon generate pdf from branch joss-edits

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-edits. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1011 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     90      0 --:--:-- --:--:-- --:--:--    90
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.280 

Looks like we failed to compile the PDF

**Comment by MikeHeiber** [comment]
@arfon @labarba Any idea why the PDF is not compiling? I am not using any math in the document, so I can't figure out why latex is complaining.

**Comment by arfon** [comment]
I think the issue is actually with the underscore in the title. This pull
request should fix the paper: https://github.com/MikeHeiber/Ising_OPV/pull/8

**Comment by MikeHeiber** [comment]
I tried that as well, and it didn't seem to fix the problem.  See the joss-edits branch for my latest edited version.

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-edits

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-edits. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1011 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    127      0 --:--:-- --:--:-- --:--:--   127
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.280 

Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@MikeHeiber - I'm not sure what's going on here. I can compile your paper fine with the edits in your `joss-edits` branch: [10.21105.joss.01011.pdf](https://github.com/openjournals/joss-reviews/files/2473426/10.21105.joss.01011.pdf)

**Comment by MikeHeiber** [comment]
@arfon Hmm... Well thanks for providing the compiled PDF.  Based on how that compiled, I've made a few more minor corrections/modifications to the joss-edits branch.

**Comment by MikeHeiber** [comment]
@whedon generate pdf from branch joss-edits

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-edits. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1011 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    189      0 --:--:-- --:--:-- --:--:--   189
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.279 

Looks like we failed to compile the PDF

**Comment by arfon** [comment]
Compiled again locally [10.21105.joss.01011.pdf](https://github.com/openjournals/joss-reviews/files/2474390/10.21105.joss.01011.pdf)

**Comment by MikeHeiber** [comment]
The proof looks good to me!

**Comment by MikeHeiber** [comment]
@labarba @arfon Just wondering when reviewer(s) will be assigned so that we can move forward. Please let me know if you are waiting on me for anything. Thanks!

**Comment by labarba** [comment]
You should expect at least a period of two weeks for finding reviewers. Sometimes more. Editors and reviewers are volunteers and most often have latency before new tasks enter our queue. Right now, for example, I'm starting a trip, with two talks to give, and last week, another trip and another talk.

**Comment by MikeHeiber** [comment]
@arfon @labarba It's now been 4 weeks since submission.  I understand that sometime things are busy, but   it should not take so long to start assigning reviewers.  Is there possibly another editor available that has time to handle this submission?

**Comment by arfon** [comment]
:wave: @katyhuff - would you be willing to edit this for JOSS?

**Comment by MikeHeiber** [comment]
@arfon Thank you for trying to move this along.  With the traditional publishers that I submit to, most of the time is spent waiting for the reviewers to assess the technical aspects of the work and not on waiting for the editors to make initial editorial decisions and sending the manuscript out for review.  I am happy to put in some more work to comb over the reviewer list again and suggest reviewers if it helps get things going.  I could even suggest new JOSS reviewers that work in my field and are active Github users, if it would help.

**Comment by katyhuff** [comment]
@MikeHeiber This level of materials science is slightly beyond my wheelhouse, so I spent a few hours on the plane looking over your submission to understand the purpose. At this point, I think I grok it, and I'm certainly happy to help out in finding reviewers unless @labarba has an objection ( @labarba I know you're on travel and juggling more papers than most, but if you object to changing editors I'm happy to return this to your capable hands ).

**Comment by katyhuff** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by katyhuff** [comment]
Now, @MikeHeiber ,  let's ping a few fitting reviewers, with materials science, physics, and c or c++ expertise. We can start the review once two or three of them accept the request to review.

----

Dear reviewers,

- @stuartcampbell as suggested: Stuart, are you able to and interested in taking on this review?
- @mdoucet  Mathieu, are you able to and interested in taking on this review?
- @jochym : Pawel, are you able to and interested in taking on this review?
- @trallard : Tania, are you able to and interested in taking on this review?
- @myousefi2016 : Mehrdad, are you able to and interested in taking on this review?


**Title:** Ising_OPV v4.0: Experimental Tomography Data Import, Interpretation, and Analysis
**Summary:** A C++ software tool for generating and analyzing model bulk heterojunction morphologies in a parallel computing environment
**Topic:** Computational Materials Science
**Article Proof:** https://github.com/openjournals/joss-reviews/files/2474390/10.21105.joss.01011.pdf
**Submitting author:** @MikeHeiber (Michael Heiber)
**Repository:** https://github.com/MikeHeiber/Ising_OPV
**Version:** v4.0.0-rc.2

**Comment by myousefi2016** [comment]
Hi, I’m interested to review this software.

**Comment by katyhuff** [comment]
@myousefi2016 Excellent! Thank you for the prompt response. We'll get started as soon as a couple of folks volunteer.

**Comment by stuartcampbell** [comment]
@katyhuff yes I'm happy to help

**Comment by katyhuff** [comment]
Fabulous, thanks @stuartcampbell ! I'll give the other reviewers another few hours to volunteer if they're interested before we start the review. Three is always slightly better than two if folks are interested!

**Comment by katyhuff** [comment]
@whedon assign @myousefi2016 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @myousefi2016

**Comment by katyhuff** [comment]
@whedon add @stuartcampbell as reviewer

**Comment by whedon** [comment]
OK, @stuartcampbell is now a reviewer

**Comment by katyhuff** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by mdoucet** [comment]
@katyhuff I’m happy to help

**Comment by katyhuff** [comment]
Thank you @mdoucet !

**Comment by katyhuff** [comment]
@whedon add @mdoucet as reviewer

**Comment by whedon** [comment]
OK, @mdoucet is now a reviewer

**Comment by katyhuff** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1072. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Hi Folks, We'll conduct the review over in #1072 !
