### ISSUE TITLE
[REVIEW]: imager: an R package for image processing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1012]
**Submitting author:** @dahtah (<a href="http://orcid.org/0000-0003-0174-5058">Simon BARTHELME</a>)
**Repository:** <a href="https://github.com/dahtah/imager" target ="_blank">https://github.com/dahtah/imager</a>
**Version:** 0.42
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @jeroen
**Archive:** <a href="https://doi.org/10.5281/zenodo.3235256" target="_blank">10.5281/zenodo.3235256</a>

## Status

[![status](http://joss.theoj.org/papers/489ba37ed9daff3376bbf3dcd06ca4cd/status.svg)](http://joss.theoj.org/papers/489ba37ed9daff3376bbf3dcd06ca4cd)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/489ba37ed9daff3376bbf3dcd06ca4cd"><img src="http://joss.theoj.org/papers/489ba37ed9daff3376bbf3dcd06ca4cd/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/489ba37ed9daff3376bbf3dcd06ca4cd/status.svg)](http://joss.theoj.org/papers/489ba37ed9daff3376bbf3dcd06ca4cd)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dahtah/imager" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jeroen, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dahtah/imager">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.42
- [x] **Authorship:** Has the submitting author (@dahtah) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jeroen, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01012/joss.01012/10.21105.joss.01012.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@jeroen, @NikEfth can you update me on when you plan to work on this review? Thanks. :rocket: :robot:

**Comment by jeroen** [comment]
@dahtah in the brief overview of imaging libraries available in R, could you compare `imager` to the `magick` package? This package interfaces to ImageMagick library and is the most comprehensive imaging toolkit in R currently available.

**Comment by NikEfth** [comment]
@jeroen @dahtah I would need a bit of support to get this started. I am using arch linux and I cannot find the dependency ibfftw3-dev. Any help?

**Comment by dahtah** [comment]
@NikEfth I don't know much about arch linux, but I guess [this](https://www.archlinux.org/packages/extra/x86_64/fftw/) should be the right package, assuming the include files are in there. Could you please confirm?

**Comment by Kevin-Mattheus-Moerman** [comment]
@dahtah, @jeroen, @NikEfth can you give an update as to where we are on the review process?

**Comment by Kevin-Mattheus-Moerman** [comment]
@dahtah can you clarify the license for this work and where it can be found? Thanks.

**Comment by dahtah** [comment]
@Kevin-Mattheus-Moerman The license can be found in the DESCRIPTION file of the R package, as per recommend practice. Do you mean clarify the license in the manuscript?

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for the clarification. You do not need to mention the license in the paper. But here are some steps I think you should take: 

- [ ] The DESCRIPTION file simply reads: `License: LGPL`, however this license type has [three variations i.e. LGPL-2.0, LGPL-2.1 and LGPL-3.0](https://opensource.org/licenses/lgpl-license), which one does your project carry?  

- [ ] Can you also add an actual LICENSE file to your project? If you choose LGPL-3.0 you'd paste [this text](https://opensource.org/licenses/LGPL-3.0) in there. This way it is clear what the license is. Also this way GitHub will render a little statement on the top right on your project front page clarifying the license, like this: 
![screenshot from 2018-11-21 09-04-24](https://user-images.githubusercontent.com/8392709/48830493-a24ce780-ed6c-11e8-927c-5b33ce7a88d0.png)

- [ ] Perhaps consider also rendering a license badge at the top of your readme and have it link to your LICENSE file, e.g. : ![License](https://img.shields.io/badge/License-GNU_LGPL_3.0-orange.svg)

**Comment by dahtah** [comment]
@Kevin-Mattheus-Moerman Thank you for your suggestions. They are implemented in the current master.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon this repository is currently on the release 0.20 but the version label here and on CRAN is 0.41.1. Is this okay or should we suggest that the repo release carries the same version number as the CRAN number?

**Comment by Kevin-Mattheus-Moerman** [comment]
@NikEfth have you resolved the linux arch issue you had? Are you still able to help with this review? Let me know if you cannot. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jeroen I see you have two unticked boxes remaining. The version number will be fixed once the submission is accepted. In terms of the license this has now been clarified to be an OSI approved license (LGPL-3.0). Are you able to tick the last boxes and perhaps formulate a recommendation (e.g. accept or not). Thanks!

**Comment by arfon** [comment]
> @arfon this repository is currently on the release 0.20 but the version label here and on CRAN is 0.41.1. Is this okay or should we suggest that the repo release carries the same version number as the CRAN number?

I think we want to be clear about which version we've reviewed here. Is GitHub version `0.20` the same as CRAN version `0.41.1`?

**Comment by dahtah** [comment]
@arfon It's my fault, I haven't consistently tagged releases on github to coincide with CRAN. If you'd like to know which version you have installed, run:
```packageVersion('imager')```
I'll try to pay more attention to tags in the future.

**Comment by Kevin-Mattheus-Moerman** [comment]
@NikEfth any luck resuming the review process? Let me know if you are still able to review this work or not. Thanks.

**Comment by NikEfth** [comment]
Hi @Kevin-Mattheus-Moerman this slipped under my radar. Sorry. 
I will give it a try the coming week and let you know soon. 
Cheers,

**Comment by Kevin-Mattheus-Moerman** [comment]
Great, thanks @NikEfth

**Comment by Kevin-Mattheus-Moerman** [comment]
@jeroen I see you have 3 unticked boxes remaining. The version number will be fixed once the submission is accepted. In terms of the license this has now been clarified to be an OSI approved license (LGPL-3.0). Are you able to tick the last boxes and perhaps formulate a recommendation (e.g. accept or not). Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@NikEfth can you give an update on your review? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@jeroen see my comments :point_up:, do you think you are able to tick the last boxes? Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@jeroen :wave: do you think you can tick those last boxes at this point? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@NikEfth are you still able to help with this review? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@NikEfth can you please complete the review at your earliest convenience to avoid further delays with this submission? Thanks.

**Comment by jeroen** [comment]
OK accept. 

PS: I don't understand why I have to check for ` Version: Does the release version given match the GitHub release (0.41.1)?` and then you say `
The version number will be fixed once the submission is accepted`. .

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @jeroen you are correct. In fact for future review issue we've removed the version check as we tend to update this anyway at the point of acceptance. Feel free to tick that last box. Thanks again for your review efforts!

**Comment by Kevin-Mattheus-Moerman** [comment]
@NikEfth can  you please finalize your side of the review at your earliest convenience? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon remove @NikEfth as reviewer

**Comment by whedon** [comment]
OK, @NikEfth is no longer a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01012/joss.01012/10.21105.joss.01012.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon do you know why the references are not listed for this paper?

**Comment by arfon** [comment]
I *think* because it's missing this section: https://github.com/dahtah/imager/pull/91

**Comment by labarba** [comment]
👋 Folks, it looks like this has been accepted but some issues remain with the paper. Can @dahtah and @Kevin-Mattheus-Moerman make a final push on this?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01012/joss.01012/10.21105.joss.01012.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@dahtah can you add the following sections/headings to your paper: 

- [ ] Acknowledgements

- [ ] References

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01012/joss.01012/10.21105.joss.01012.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@dahtah thanks for making those changes. at this point can you:

- [ ] Please archive a copy of the reviewed software on [Zenodo](http://about.zenodo.org/) (some find the steps defining [this](https://guides.github.com/activities/citable-code/) automated process useful). Once you've done that can you provide us with the DOI of the archived version? 
- [ ] Can you please list the final version label for the reviewed software?

**Comment by Kevin-Mattheus-Moerman** [comment]
@dahtah :wave: :point_up:

**Comment by dahtah** [comment]
Sorry for the delay, and thanks for reviewing this. Zenodo gave me the following DOI: 10.5281/zenodo.3235256. The archived version is 0.42

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 10.5281/zenodo.3235256 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3235256" target="_blank">10.5281/zenodo.3235256</a> is the archive.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 0.42 as version

**Comment by whedon** [comment]
OK. 0.42 is the version.

**Comment by Kevin-Mattheus-Moerman** [comment]
@dahtah can you do the following: 

- [ ] Can you change the Zenodo archive title from _"dahtah/imager: JOSS release"_ to match that of this submission _"imager: an R package for image processing"_

- [ ] Can you update the author list on Zenodo so it matches the paper?

**Comment by Kevin-Mattheus-Moerman** [comment]
@dahtah :wave: can you work on the above? Thanks

**Comment by dahtah** [comment]
@Kevin-Mattheus-Moerman Done!

**Comment by Kevin-Mattheus-Moerman** [comment]
@dahtah did you create a new Zenodo archive? It does not seem updated yet on this link: https://zenodo.org/record/3235256

**Comment by dahtah** [comment]
@Kevin-Mattheus-Moerman Is it good now? I had saved but hadn't clicked the publish button

**Comment by Kevin-Mattheus-Moerman** [comment]
@dahtah yep looks good

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/joss-eics this submission is ready to be accepted :tada:

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/747

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/747, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1138513397585195008) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/748
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01012](https://doi.org/10.21105/joss.01012)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01012/status.svg)](https://doi.org/10.21105/joss.01012)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01012">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01012/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01012/status.svg
   :target: https://doi.org/10.21105/joss.01012
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01012/status.svg)](https://doi.org/10.21105/joss.01012)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
