### ISSUE TITLE
[REVIEW]: Embeddings.jl: easy access to pretrained word embeddings from julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1013]
**Submitting author:** @oxinabox (<a href="http://orcid.org/0000-0003-1386-1646">Lyndon White</a>)
**Repository:** <a href="https://github.com/JuliaText/Embeddings.jl/" target ="_blank">https://github.com/JuliaText/Embeddings.jl/</a>
**Version:** 0.3.1
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @aviks
**Archive:** <a href="https://doi.org/10.5281/zenodo.2633789" target="_blank">10.5281/zenodo.2633789</a>

## Status

[![status](http://joss.theoj.org/papers/fed0b7d1db22a7fe0d5933a7b6b81e81/status.svg)](http://joss.theoj.org/papers/fed0b7d1db22a7fe0d5933a7b6b81e81)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/fed0b7d1db22a7fe0d5933a7b6b81e81"><img src="http://joss.theoj.org/papers/fed0b7d1db22a7fe0d5933a7b6b81e81/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/fed0b7d1db22a7fe0d5933a7b6b81e81/status.svg)](http://joss.theoj.org/papers/fed0b7d1db22a7fe0d5933a7b6b81e81)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/JuliaText/Embeddings.jl/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@aviks, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JuliaText/Embeddings.jl/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.3.1
- [x] **Authorship:** Has the submitting author (@oxinabox) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @aviks it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01013/joss.01013/10.21105.joss.01013.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@aviks thanks again for being a reviewer for this submission. How are you getting on? Let me know if you have questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@aviks can you give an update as to how you are getting on with the review process? Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@aviks we'd like to move on with this submission. If you are still able to review this work please do so at your earliest convenience. If you are no longer able to do so please let us know. Thanks.

**Comment by oxinabox** [comment]
I'm honestly happy to wait. I am in no hurry for this one. @aviks  is a pretty ideal reviewer.

**Comment by Kevin-Mattheus-Moerman** [comment]
@oxinabox thanks for letting us know. We can of course be flexible regarding timing.

**Comment by labarba** [comment]
I have just sent a follow-up message via email to the reviewer to ask if they still plan on doing this (copied @Kevin-Mattheus-Moerman).

**Comment by aviks** [comment]
Sorry for delaying this folks. I will get on this now.

**Comment by aviks** [comment]
Everything looks good apart from a couple of documentation nits that I've raised on the repo.

**Comment by Kevin-Mattheus-Moerman** [comment]
@oxinabox I see you have a short contributing section in your readme. Would you be okay with expanding your community guidelines (last unticked box above) a bit, e.g. using the steps/info below? 

- [ ] Please add [community guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines) i.e. in the form of a `CONTRIBUTING.md` file (see also here https://help.github.com/articles/github-community-guidelines/) and a [code of conduct](https://opensource.guide/code-of-conduct/) (`COC.md`) document (good templates are available here: https://www.contributor-covenant.org/). 

- [ ] I recommend that you link to the CONTRIBUTING and COC files in the README file.

**Comment by Kevin-Mattheus-Moerman** [comment]
The other unticked box is installation instructions. 
@oxinabox can you also expand your installation instructions. @aviks if you have more feedback on this to point @oxinabox in the right direction (i.e. what you feel is missing) that would be great. Thanks again for your review work.

**Comment by oxinabox** [comment]
I added an Installation section the other day. https://github.com/JuliaText/Embeddings.jl/blob/master/README.md#installation
I do not think there are more instructions I can give.


I have further expanded the Contributing section, and added reference to the Julia Community Standards.
I'm not sure if moving this section of the document to a CONTRIBUTING.md would make it more, or less likely to be read.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.21105/joss.00602 is OK

MISSING DOIs

- https://doi.org/10.1137/141000671 may be missing for title: Julia: A Fresh Approach to Numerical Computing
- https://doi.org/10.1108/09504121211251880 may be missing for title: DataDeps.jl: Repeatable Data Setup for Replicable Data Science
- https://doi.org/10.1162/tacl_a_00051 may be missing for title: Enriching Word Vectors with Subword Information
- https://doi.org/10.1162/tacl_a_00051 may be missing for title: Learning Word Vectors for 157 Languages
- https://doi.org/10.2172/1209543 may be missing for title: Efficient estimation of word representations in vector space
- https://doi.org/10.3115/v1/d14-1162 may be missing for title: GloVe: Global Vectors for Word Representation

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@oxinabox can you check those DOI's?

**Comment by oxinabox** [comment]
- **correct:** `https://doi.org/10.1137/141000671 may be missing for title: Julia: A Fresh Approach to Numerical Computing`
- **Incorrect:** `https://doi.org/10.1108/09504121211251880 may be missing for title: DataDeps.jl: Repeatable Data Setup for Replicable Data Science`
    - this paper has been stuck in some review hole for almost a year, so the citation is for the preprint. idk where this DOI is from.
- **correct:** `https://doi.org/10.1162/tacl_a_00051 may be missing for title: Enriching Word Vectors with Subword Information`
- **Incorrect:** `https://doi.org/10.1162/tacl_a_00051 may be missing for title: Learning Word Vectors for 157 Languages`
    - This is the same DOI as above so it can't be for this paper too.
- **Incorrect:** `https://doi.org/10.2172/1209543 may be missing for title: Efficient estimation of word representations in vector space`
- **correct:** `https://doi.org/10.3115/v1/d14-1162 may be missing for title: GloVe: Global Vectors for Word Representation`

I should update the bibliography to use these DOIs that are correct?

**Comment by labarba** [comment]
Please update your bibliography, yes.

**Comment by Kevin-Mattheus-Moerman** [comment]
@oxinabox any luck updaring the .bib file? Let me know if you need help or have questions.

**Comment by oxinabox** [comment]
No, sorry i've been away. Will send to it soon

**Comment by oxinabox** [comment]
Done

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1013 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    14    0    14    0     0    176      0 --:--:-- --:--:-- --:--:--   177
Error reading bibliography ./paper.bib (line 40, column 3):
unexpected "d"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by Kevin-Mattheus-Moerman** [comment]
@oxinabox can you trouble shoot the above a bit? Feel free to call `@whedon generate pdf` yourself here to attempt to recreate the paper.

**Comment by oxinabox** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01013/joss.01013/10.21105.joss.01013.pdf)

**Comment by oxinabox** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1013 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    14    0    14    0     0    161      0 --:--:-- --:--:-- --:--:--   162

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01013/joss.01013/10.21105.joss.01013.pdf)

**Comment by oxinabox** [comment]
LGTM

**Comment by oxinabox** [comment]
LGTM

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1162/tacl_a_00051 is OK
- 10.3115/v1/d14-1162 is OK
- 10.21105/joss.00602 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
Some minor comments on the paper:

- [ ] Can you define the acronyms NLP, LSTM 

- [ ] Either introduce NLP and use it consistently or remove it and say natural language processing throughout (it appears natural language processing is spelled out later in the text). 

- [ ] Can you use the same form in the bullet list? By form I mean that the word embeddings follows after the bracketed references e.g.:
- Bla bla ProjectSoftWareName (REFERENCES) embeddings bla bla

- [ ] The 3rd bullet point contains two grouped reference sets, should these be merged?:  (Grave, Bojanowski, Gupta, Joulin, & Mikolov, 2018), (Bojanowski, Grave, Joulin, & Mikolov, 2017)

- [ ] Could you make sure the reference to "DataDeps.jl: Repeatable
Data Setup for Replicable Data Science" will also show up with a "Retrieved from" link? I believe it is https://arxiv.org/pdf/1808.01091.pdf.

**Comment by oxinabox** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01013/joss.01013/10.21105.joss.01013.pdf)

**Comment by oxinabox** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01013/joss.01013/10.21105.joss.01013.pdf)

**Comment by oxinabox** [comment]
Done

**Comment by oxinabox** [comment]
@Kevin-Mattheus-Moerman  his this good to go now?
I am submitting my final corrected version of my thesis soon, and it would be nice to be able to switch this from "Under Review"  to "Published".

**Comment by Kevin-Mattheus-Moerman** [comment]
@oxinabox apologies for the delay. I'll get to this now.

**Comment by Kevin-Mattheus-Moerman** [comment]
@oxinabox looks good. 

One minor thing. Currently it says "an long", this should be "a long". Also, since now you do not reuse the acronym LSTM, consider removing it all together, or if the acronym is used more often than the spelled out form use:  "LSTM (long short term memory)" rather than "long short term memory (LSTM)".

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1162/tacl_a_00051 is OK
- 10.3115/v1/d14-1162 is OK
- 10.21105/joss.00602 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01013/joss.01013/10.21105.joss.01013.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
Great. Thanks @oxinabox. At this point can you provide a DOI to an archived version of the final reviewed software through a service like [ZENODO](https://zenodo.org/) (some find [these steps](https://guides.github.com/activities/citable-code/) useful)? Once you've done that can you provide the version tag of the final version of the reviewed software?

**Comment by oxinabox** [comment]
Thanks:
DOI:  10.5281/zenodo.2633789 
Version: 0.3.1

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 10.5281/zenodo.2633789 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2633789" target="_blank">10.5281/zenodo.2633789</a> is the archive.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 0.3.1 as version

**Comment by whedon** [comment]
OK. 0.3.1 is the version.

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/joss-eics I recommend this work is accepted in JOSS

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1162/tacl_a_00051 is OK
- 10.3115/v1/d14-1162 is OK
- 10.21105/joss.00602 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/615

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/615, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/616
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01013](https://doi.org/10.21105/joss.01013)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @oxinabox, your JOSS paper is published!

Big thanks to our editor: @Kevin-Mattheus-Moerman, and the reviewer: @aviks — Merci, danke, gracias 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01013/status.svg)](https://doi.org/10.21105/joss.01013)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01013">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01013/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01013/status.svg
   :target: https://doi.org/10.21105/joss.01013
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01013/status.svg)](https://doi.org/10.21105/joss.01013)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
