### ISSUE TITLE
[PRE REVIEW]: gtk-fortran: a GTK+ binding to build Graphical User Interfaces in Fortran

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1014]
**Submitting author:** @vmagnin (<a href="http://orcid.org/0000-0002-9016-9955">Vincent MAGNIN</a>)
**Repository:** <a href="https://github.com/jerryd/gtk-fortran" target ="_blank">https://github.com/jerryd/gtk-fortran</a>
**Version:** v17.10
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @johnsamuelwrites, @devonrex, @sundmanbo

**Author instructions**

Thanks for submitting your paper to JOSS @vmagnin. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@vmagnin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Kevin-Mattheus-Moerman it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1014 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-7ea7c17cf2a1/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-7ea7c17cf2a1/lib/whedon.rb:91:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-7ea7c17cf2a1/lib/whedon.rb:91:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-7ea7c17cf2a1/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-7ea7c17cf2a1/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-7ea7c17cf2a1/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-7ea7c17cf2a1/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-7ea7c17cf2a1/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-7ea7c17cf2a1/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-7ea7c17cf2a1/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @Kevin-Mattheus-Moerman - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@vmagnin - this pull request should fix the paper compilation: https://github.com/jerryd/gtk-fortran/pull/124

**Comment by vmagnin** [comment]
> @vmagnin - this pull request should fix the paper compilation: [jerryd/gtk-fortran#124](https://github.com/jerryd/gtk-fortran/pull/124)
@arfon - I have merged your pull request. Effectively, one of the author has no ORCID.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01014/joss.01014/10.21105.joss.01014.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@daviddoria is this submission of interest to you and would you be able to help review it?

**Comment by vmagnin** [comment]
> [ point_right Check article proof page_facing_up point_left ](https://github.com/openjournals/joss-papers/blob/joss.01014/joss.01014/10.21105.joss.01014.pdf)

In the proof, there is a problem with two citations: in the .bib m**a**tcalfe2011 should be replaced by m**e**tcalfe2011. Should I push the correction on the repository of the project ?
Concerning the softwares references, I guess "n.d." means "no date" ?  And when the author is a community, how should the reference appear in the .bib ?
Thanks

**Comment by vmagnin** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by Kevin-Mattheus-Moerman** [comment]
Yes do implement the changes in your own repo. You can call `@whedon generate pdf` yourself here whenever you want to re-render the pdf. 

@arfon can you help answer the question about citing a software package when the author is a community, what should be changed in this: 
```latex
@misc{plplot,
author = {The Plplot developer community},
title = {PLplot - The ultimate in cross-platform plotting},
howpublished = {\url{http://plplot.sourceforge.net/}}
}
```
to avoid it being rendered as: 
`community, T. P. developer. (n.d.). PLplot - the ultimate in cross-platform plotting.
http://plplot.sourceforge.net/.`

**Comment by alexlarsson** [comment]
Sorry, I don't have any time to review this.

**Comment by vmagnin** [comment]
@whedon generate pdf

* Corrected metcalf2011 reference
* Corrected author J. De Lisle affiliation
* improved reference to Tincher2017 paper
* added date to DISLIN reference

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01014/joss.01014/10.21105.joss.01014.pdf)

**Comment by vmagnin** [comment]
@Kevin-Mattheus-Moerman
@arfon

Browsing a lot of JOSS papers, I found one citing the R software using:
```
@Manual{R2018,
	title = {R: A Language and Environment for Statistical Computing},
	author = R Core Team,
	organization = {R Foundation for Statistical Computing},
	address = {Vienna, Austria},
	year = {2018},
	url = {https://www.R-project.org/},
}
```
The result is:
_suppdata is an R (R Core Team 2018) package to provide easy,_

**Comment by vmagnin** [comment]
@whedon generate pdf

* Tried to improve references

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1014 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    127      0 --:--:-- --:--:-- --:--:--   128
Error reading bibliography ./paper.bib (line 66, column 1):
unexpected "@"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by vmagnin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01014/joss.01014/10.21105.joss.01014.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@molines @bjonkman @szaghi @komatits would you be interested in reviewing this work for the [Journal of Open Source Software (JOSS)](http://joss.theoj.org/)? The [review process](http://joss.theoj.org/about#reviewer_guidelines) focuses on [the software](https://github.com/jerryd/gtk-fortran) and [a short paper](https://github.com/openjournals/joss-papers/blob/joss.01014/joss.01014/10.21105.joss.01014.pdf). 
Let me know if you have questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@vmagnin would you be able to help suggest reviewers?

**Comment by bjonkman** [comment]
Sorry, but I don't have time to review this.

**Comment by vmagnin** [comment]
> @vmagnin would you be able to help suggest reviewers?

@Kevin-Mattheus-Moerman 
If it's OK for you I can try to contact some forkers or followers of the project on GitHub.

**Comment by Kevin-Mattheus-Moerman** [comment]
@vmagnin yes please do. Feel free to ping them in this issue.

**Comment by Kevin-Mattheus-Moerman** [comment]
@chirayubatra @jlokimlin would you be interested in reviewing this work for the [Journal of Open Source Software (JOSS)](http://joss.theoj.org/)? The [review process](http://joss.theoj.org/about#reviewer_guidelines) focuses on [the software](https://github.com/jerryd/gtk-fortran) and [a short paper](https://github.com/openjournals/joss-papers/blob/joss.01014/joss.01014/10.21105.joss.01014.pdf). 
Let me know if you have questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@vmagnin I'll still looking for reviewers. Let me know if you have any in mind.

**Comment by Kevin-Mattheus-Moerman** [comment]
@vmagnin I am unable to access your website URL shown at the top of your project http://gtk+fortran, is it broken?

**Comment by Kevin-Mattheus-Moerman** [comment]
@chirayubatra @jlokimlin @molines @szaghi @komatits @mitotic would you be interested in reviewing [this work](https://github.com/jerryd/gtk-fortran/wiki) for the [Journal of Open Source Software (JOSS)](http://joss.theoj.org/)? 

This submission, gtk-fortran, offers _"scientists programming in Fortran a cross-platform library to build Graphical User Interfaces"_. 

The JOSS [review process](http://joss.theoj.org/about#reviewer_guidelines) takes place on GitHub and focuses on [the software](https://github.com/jerryd/gtk-fortran) and [a short paper](https://github.com/openjournals/joss-papers/blob/joss.01014/joss.01014/10.21105.joss.01014.pdf). 
Let me know if you have questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @johnsamuelwrites as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @johnsamuelwrites

**Comment by Kevin-Mattheus-Moerman** [comment]
@johnsamuelwrites (https://orcid.org/0000-0001-8721-7007) thanks for joining as a reviewer! This is a pre-review issue where we gather reviewers. The review process will be initiated later and takes place on a dedicated review issue. In the meantime you can familiarize yourself with the [review guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#). Let me know if you have questions.

**Comment by johnsamuelwrites** [comment]
Thank you @Kevin-Mattheus-Moerman for the invitation. I will finish the review in the upcoming days.

**Comment by vmagnin** [comment]
> @vmagnin I'll still looking for reviewers. Let me know if you have any in mind.

Dear @Kevin-Mattheus-Moerman ,
I have found two persons who agree to be reviewers: @devonrex and @sundmanbo

**Comment by vmagnin** [comment]
> @vmagnin I am unable to access your website URL shown at the top of your project http://gtk+fortran, is it broken?

@Kevin-Mattheus-Moerman 
The URL http://gtk+fortran is probably an error in the settings of the project, dating back to the origin of the project... There is no other site than https://github.com/jerryd/gtk-fortran (or its wiki page https://github.com/jerryd/gtk-fortran/wiki).
I will ask @jerryd, who originally created that repository, to delete that URL.


https://github.com/jerryd/gtk-fortran

**Comment by Kevin-Mattheus-Moerman** [comment]
@vmagnin currently your paper contains this sentence: `A Graphical User Interface (GUI) can be useful in a research software to visualize results in real time during a computation, to plot results or to interact with the user, especially if the software is used by other people or distributed outside the laboratory.` 
Can you please expand your paper a in terms of describing the application of this work to scientific research? Perhaps give some specific examples of how this work is relevant in particular research applications (sketch a picture that helps the reader understand how this work might be important enough to some scientific research that researchers will feel the need to cite it in their paper).

**Comment by Kevin-Mattheus-Moerman** [comment]
@vmagnin can you reply to my comment above please. Thanks.

**Comment by vmagnin** [comment]
> @vmagnin can you reply to my comment above please. Thanks.

Dear @Kevin-Mattheus-Moerman 
sorry for the delay, of course I have read your request and I have begun thinking about the arguments to add in the paper. But I was busy with other things these last weeks.
I will work on it this week.

**Comment by vmagnin** [comment]
@Kevin-Mattheus-Moerman 
I have modified the paper:
* The introduction paragraph has been expanded, and splitted in two. A reference was added.
* Added the following sentences in the (now) third paragraph : 
	* _"The gtkf-sketcher tool even makes easier the design of a complex GTK+3 GUI by automatically generating the Fortran code from the XML files created by the user interface designer software Glade [glade]."_
	* _"They can for example implement visual management of tree-like data structures for handling of complex data projects."_

@whedon generate pdf

P.S. I hope the "@" mentions will work in this message, because today the github editor does not seem to recognize them...

**Comment by vmagnin** [comment]
@Kevin-Mattheus-Moerman 
Please read my last message. Github seems now to work properly !
@whedon generate pdf

**Comment by vmagnin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01014/joss.01014/10.21105.joss.01014.pdf)

**Comment by sundmanbo** [comment]
@Kevin-Mattheus-Moerman Hi, I have started the review and managed to install the software with minor problems.

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1109. Feel free to close this issue now!

**Comment by Kevin-Mattheus-Moerman** [comment]
@vmagnin thanks for providing the additional clarifications in your paper. I will suggest further edits to the paper (saw some language/spelling issues) but have started the review process.
