### ISSUE TITLE
[PRE REVIEW]: pylbm: A Flexible Python Package for Lattice Boltzmann Method

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1016]
**Submitting author:** @gouarin (<a href="http://orcid.org/0000-0003-4761-9989">Loic Gouarin</a>)
**Repository:** <a href="https://github.com/pylbm/pylbm" target ="_blank">https://github.com/pylbm/pylbm</a>
**Version:** 0.3.2
**Editor:** @kyleniemeyer
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @gouarin. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@gouarin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@gouarin - please take a look at the errors from @whedon's attempt to compile the paper above. Once you have pushed some fixes, you can ask Whedon to compile again with `@whedon generate pdf`

**Comment by gouarin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01016/joss.01016/10.21105.joss.01016.pdf)

**Comment by kyleniemeyer** [comment]
Hi @gouarin, do you have any suggested reviewers for this submission? I will try to identify at least one from the JOSS reviewer pool, but I would also like at least one reviewer who is an expert on the topic.

**Comment by danielskatz** [comment]
And just as a general comment, it would be good to say something about why one would want to run LB simulations in the readme and the docs - for example, in what science/engineering disciplines and for what problems is the LB method a good choice?

**Comment by gouarin** [comment]
@kyleniemeyer I will try to give you a name soon.

@danielskatz it's difficult to answer to that question. It's like to answer what science/engineering disciplines and for what problems is the finite element, finite difference or finite volume methods a good choice. LB method can be used in computational fluid dynamics and for a lot of problems.

cc @bgraille

**Comment by kyleniemeyer** [comment]
@gouarin @danielskatz I do think including some example problems is important for the paper. Also, I notice that right now about half the paper is decided to *future* extensions/features; I don't really think that is appropriate, as most of the paper should be motivating and describing the *current* software. I'd encourage you to check out some of the recent published articles, and work on revising the paper at this stage.

**Comment by danielskatz** [comment]
As @kyleniemeyer said, I don't think there needs to be an exhaustive list of problems for which this is used, but some examples would really help.

**Comment by gouarin** [comment]
@kyleniemeyer , @danielskatz thanks for your comments. We will modify the article and give various examples. We didn't do it to have a short article. With examples, the article will give more information about what we can do with pylbm and probably more interesting.

**Comment by danielskatz** [comment]
The examples can be really brief (under a paragraph overall), and probably should be in the readme and docs, not just the article.  Once the review starts, it's likely the reviewers will ask for this too ...

**Comment by danielskatz** [comment]
I'm not sure those graphics really explain what's going on - at least labeling the axes/colors would help

**Comment by labarba** [comment]
Hi @kyleniemeyer — I could recommend some reviewer(s) for this submission.

What we're missing, though, is a clear _Statement of Need_, and some statements in the paper to illustrate how this software has been or can be used in research.

The [Lattice Boltzmann Method](https://en.wikipedia.org/wiki/Lattice_Boltzmann_methods) is like a whole branch of CFD, with [thousands](https://scholar.google.com/scholar?as_ylo=2018&q=%22lattice+boltzmann+method%22&hl=en&as_sdt=0,9) of papers published on the topic every year.

Several open-source software packages implementing LBM are already available, big and small. For example:

- OpenLB, https://www.openlb.net C++, parallel https://en.wikipedia.org/wiki/OpenLB
- Palabos, an OS LB solver http://www.palabos.org 
- CudneLB - the templated version, https://github.com/CFD-GO/TCLB 
- waLBerla - A Massively Parallel Framework http://walberla.net

Therefore, even if we find reviewers and start the review, they (and the editor) will be asking you, @gouarin, to write in the paper how your software sits in the field, what special or different feature it offers, and—for sure—to cite other software in the field.

**Comment by labarba** [comment]
Sure! Just ping us all here when you're ready.

**Comment by labarba** [comment]
👋 @gouarin — We'll add this label here 👇 and pause the review. Ping us back when you feel the review can restart.

**Comment by danielskatz** [comment]
👋 @gouarin - Given that this review hasn't started, I plan to withdraw the paper, with the idea that it can be submitted when the modifications have been made and it is ready to be reviewed.  Please let me know if you disagree.

**Comment by gouarin** [comment]
@danielskatz I agree. Sorry for the delay.

We will do better next time !

**Comment by danielskatz** [comment]
Thanks - we look forward to your future submission!
