### ISSUE TITLE
[PRE REVIEW]: The Another Assimilation System for WRF-Chem (AAS4WRF): a new mass-conserving emissions preprocessor for WRF-Chem regional modelling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1017]
**Submitting author:** @alvv1986 (<a href="http://orcid.org/0000-0002-4972-4486">Angel Vara Vela</a>)
**Repository:** <a href="https://github.com/alvv1986/AAS4WRF" target ="_blank">https://github.com/alvv1986/AAS4WRF</a>
**Version:** v1.4.0
**Editor:** @kthyng
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @alvv1986. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@alvv1986 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kthyng it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1017 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     81      0 --:--:-- --:--:-- --:--:--    81
Error reading bibliography ./paper.bib (line 101, column 3):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @kthyng - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@alvv1986 - it looks like there's an issue with the bibtex associated with this submission. Please push fixes to your repository and then ask Whedon to recompile the paper with `@whedon generate pdf`

**Comment by alvv1986** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1017 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    301      0 --:--:-- --:--:-- --:--:--   306
[WARNING] Could not convert image '/tmp/tex2pdf.211/6c3ae40bf6fd8dc37ade6f51beb00839cced3929.shtml': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : 
  
  
  
  
  
  
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA not enough bytes
[WARNING] Could not convert image '/tmp/tex2pdf.211/0db7704bfd610123fc558b7817f0bc9aee2455dd.shtml': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : 
  
  
  
  
  
  
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA not enough bytes
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.211/6c3ae40bf6f
d8dc37ade6f51beb00839cced3929.shtml (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.515 ...0bf6fd8dc37ade6f51beb00839cced3929.shtml}

Looks like we failed to compile the PDF

**Comment by alvv1986** [comment]
H

**Comment by alvv1986** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01017/joss.01017/10.21105.joss.01017.pdf)

**Comment by alvv1986** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by alvv1986** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by kthyng** [comment]
@alvv1986, thanks for your submission. The editorial board has determined that your submission does not meet our submission requirements. In particular, this submission falls under the 'Minor utility package' category; you can see more information under JOSS [Submission Requirements](https://joss.readthedocs.io/en/latest/submitting.html?#submission-requirements).

Please don't hesitate to reach out for further clarification on the submission requirements.
