### ISSUE TITLE
[REVIEW]: SWEpy: A Python Library for Quick and Easy Access and Manipulation of MEaSUREs CETB files for SWE analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1018]
**Submitting author:** @wino6687 (<a href="http://orcid.org/0000-0002-6772-9600">will norris</a>)
**Repository:** <a href="https://github.com/wino6687/SWEpy" target ="_blank">https://github.com/wino6687/SWEpy</a>
**Version:** v1.1.7
**Editor:** @arfon
**Reviewer:** @usethedata
**Archive:** <a href="https://doi.org/10.5281/zenodo.1849824" target="_blank">10.5281/zenodo.1849824</a>

## Status

[![status](http://joss.theoj.org/papers/9d64f87cdcc80b9d9a01bb1103142c7f/status.svg)](http://joss.theoj.org/papers/9d64f87cdcc80b9d9a01bb1103142c7f)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/9d64f87cdcc80b9d9a01bb1103142c7f"><img src="http://joss.theoj.org/papers/9d64f87cdcc80b9d9a01bb1103142c7f/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/9d64f87cdcc80b9d9a01bb1103142c7f/status.svg)](http://joss.theoj.org/papers/9d64f87cdcc80b9d9a01bb1103142c7f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/wino6687/SWEpy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@usethedata, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [X] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [X] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [X] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/wino6687/SWEpy">repository url</a>?
- [X] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [X] **Version:** Does the release version given match the GitHub release (v1.1.5)?
- [X] **Authorship:** Has the submitting author (@wino6687) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [X] **Installation:** Does installation proceed as outlined in the documentation?
- [X] **Functionality:** Have the functional claims of the software been confirmed?
- [X] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [X] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [X] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [X] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [X] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [X] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [X] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [X] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [X] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [X] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @usethedata it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01018/joss.01018/10.21105.joss.01018.pdf)

**Comment by arfon** [comment]
@wino6687 - it looks like your paper doesn't have any references, or if they are, they're not being compiled in. You can read how to cite works in Pandoc [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)

**Comment by usethedata** [comment]
@arfon What's the correct way to document what I don't see as a COI so that it's out there?  In terms of the stated COI policy, we're fine.  I've never been a collaborator with either of the authors, nor have I ever collaborated directly with the Earth Lab at UC Boulder.   People who report to me are collaborators with the National Snow and Ice Data Center (NSIDC) at UC-B, which is the source of the data referenced by this software.  But nobody that works for me is a collaborator (or has been a collaborator) with UC-B Earth Lab in the past 4+ years.  I'm the PI for one of the NASA DAACs (ORNL DAAC), and part of NSDIC funding is a separate contract from NASA, but under the same program.

**Comment by arfon** [comment]
> @arfon What's the correct way to document what I don't see as a COI so that it's out there?

I think you've just done it 😁. Thanks for disclosing this - and please proceed with the review.

**Comment by wino6687** [comment]
@arfon, thanks for pointing that out! I do reference the NSIDC database that is used, I will get that fixed now.

**Comment by wino6687** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01018/joss.01018/10.21105.joss.01018.pdf)

**Comment by wino6687** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01018/joss.01018/10.21105.joss.01018.pdf)

**Comment by wino6687** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01018/joss.01018/10.21105.joss.01018.pdf)

**Comment by wino6687** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01018/joss.01018/10.21105.joss.01018.pdf)

**Comment by wino6687** [comment]
Alright, the citation is fixed, sorry it took so many iterations!

**Comment by wino6687** [comment]
Hi @arfon, I updated the current git release over the last couple weeks to v1.1.7. Is there a way to update the JOSS review to v1.1.7?

**Comment by arfon** [comment]
> Hi @arfon, I updated the current git release over the last couple weeks to v1.1.7. Is there a way to update the JOSS review to v1.1.7?

Done.

**Comment by arfon** [comment]
How are you getting along with your review @usethedata ?

**Comment by usethedata** [comment]
Review completed.

**Comment by kyleniemeyer** [comment]
@usethedata thanks for your review!

@wino6687 if you have completed making any changes, can you archive the software and report the DOI back here?

**Comment by wino6687** [comment]
@whedon set 10.5281/zenodo.1849824 as archive

**Comment by whedon** [comment]
I'm sorry @wino6687, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by wino6687** [comment]
Looks like I can't do that! Thank you @usethedata for the review, and @kyleniemeyer, the archive is 10.5281/zenodo.1849824


Thank you!!

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.1849824 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1849824" target="_blank">10.5281/zenodo.1849824</a> is the archive.

**Comment by wino6687** [comment]
Hi @kyleniemeyer and @arfon, is there anything else I should be doing right now to help with the process? Thanks!

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by arfon** [comment]
> Hi @kyleniemeyer and @arfon, is there anything else I should be doing right now to help with the process? Thanks!

Thanks for the bump. This got lost in the handoff between editors.

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/107

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/107, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/108
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01018](https://doi.org/10.21105/joss.01018)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01018/status.svg)](https://doi.org/10.21105/joss.01018)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01018">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01018/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01018/status.svg
   :target: https://doi.org/10.21105/joss.01018
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01018/status.svg)](https://doi.org/10.21105/joss.01018)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by arfon** [comment]
@usethedata - many thanks for your review ✨ 

@wino6687 - your paper is now accepted into JOSS :zap::rocket::boom:
