### ISSUE TITLE
[REVIEW]: acronym: An Automatic Reduction Pipeline for Astronomical Images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#102]
**Submitting author:** @kweis (<a href="http://orcid.org/0000-0002-4639-1436">Kolby Weisenburger</a>)
**Repository:** <a href="https://github.com/kweis/acronym" target ="_blank">https://github.com/kweis/acronym</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** @xuanxu
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.570881" target="_blank">10.5281/zenodo.570881</a>

## Status

[![status](http://joss.theoj.org/papers/a3d09040637afbcff0a01e0d77c563cf/status.svg)](http://joss.theoj.org/papers/a3d09040637afbcff0a01e0d77c563cf)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/a3d09040637afbcff0a01e0d77c563cf"><img src="http://joss.theoj.org/papers/a3d09040637afbcff0a01e0d77c563cf/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/a3d09040637afbcff0a01e0d77c563cf/status.svg)](http://joss.theoj.org/papers/a3d09040637afbcff0a01e0d77c563cf)
```

**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/kweis/acronym" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)
### Conflict of interest
- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).
### General checks
- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kweis/acronym">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@kweis) made major contributions to the software?
### Functionality
- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?
### Documentation
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
### Software paper
- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@xuanxu :wave:. Many thanks for agreeing to review this submission. Please follow the reviewer guidelines (http://joss.theoj.org/about#reviewer_guidelines) and update the issue checklist at the top of this issue as you go.

**Comment by migueldvb** [comment]
I am happy to review this submission if additional reviewers are needed.

**Comment by arfon** [comment]
> I am happy to review this submission if additional reviewers are needed.

That sounds great @migueldvb. Please feel free to review this too.

**Comment by migueldvb** [comment]
As a general comment it seems that this CCD reduction could be done with
existing open source software such as astropy's ccdproc package (implemented in
python) or FITSH using some helper functions from acronymn (as ARCTIC data have
some FITS keywords READAMPS, DSEC11 that are not part of the FITS standard
such as TRIMSEC and BIASSEC).  However I may have missed something.  It would be
useful to say in the documentation what is different in this code from other
reduction software and give a reference to other packages that have
the same functionality.

Another issue that should be fixed is that currently there is no automated test
functions that will verify that the reduction of the test data in he repository
provides the expected result.

There are a few additional minor issues in the acronym github repository (some of them may have already been fixed).

- https://github.com/kweis/acronym/issues/5
- https://github.com/kweis/acronym/issues/6
- https://github.com/kweis/acronym/issues/6
- https://github.com/kweis/acronym/issues/7
- https://github.com/kweis/acronym/issues/8
- https://github.com/kweis/acronym/issues/9
- https://github.com/kweis/acronym/issues/10
- https://github.com/kweis/acronym/issues/11
 
So far I haven't got any other comments. If I find any other issues I will open a new ticket.

**Comment by arfon** [comment]
@kweis - the `paper.md` won't compile as there aren't any references? Given you mention Astropy in your readme perhaps you should consider (at least) citing this package?

**Comment by arfon** [comment]
> @kweis - the paper.md won't compile as there aren't any references? Given you mention Astropy in your readme perhaps you should consider (at least) citing this package?

Friendly bump @kweis.

**Comment by arfon** [comment]
> Friendly bump @kweis.

👋  @kweis

**Comment by arfon** [comment]
> 👋 @kweis

Hi @kweis - taking a look at the list of issues that @migueldvb opened on your project it appears that you closed these with no comment:

- https://github.com/kweis/acronym/issues/5
- https://github.com/kweis/acronym/issues/6
- https://github.com/kweis/acronym/issues/7
- https://github.com/kweis/acronym/issues/8
- https://github.com/kweis/acronym/issues/9
- https://github.com/kweis/acronym/issues/10
- https://github.com/kweis/acronym/issues/11

It's not clear if you have addressed @migueldvb's feedback on these issues or aren't planning to. If it's the latter then I'm going to assume that you aren't interested in having your paper published in JOSS any longer.

Please respond here to let us know what you'd like to do at this stage but if there's no response within the next couple of weeks I'll reject this submission.

**Comment by sagetrey** [comment]
unsubscribe

**Comment by arfon** [comment]
@sagetrey - please take a look at the instructions here to unsubscribe from JOSS reviews: https://github.com/openjournals/joss-reviews/issues/166#issuecomment-273498829

**Comment by kweis** [comment]
I've resolved all opened issues and moved the large binary files to a zipped file in the release docs. I released an updated [package](https://github.com/kweis/acronym/releases/latest) that highlights how I've addressed @migueldvb's feedback. 

With respect to the general comment regarding the CCD reduction -- the reason for writing in-house procedures (rather than astropy's ccdproc, for instance) is for clarity and transparency when handling ARCTIC's peculiarities. ARCTIC has specialized readout modes that result in variable image sizes. How we handle this is most obvious in the trim_image function and while this could be enveloped into a helper function in tandem with astropy's ccdproc, we wished to maintain a package that was curated specifically for the ARCTIC instrument and that did not rely on preexisting reduction packages. We are currently comparing our results to results from using ccdproc and will update the repository with a test function this week.

**Comment by arfon** [comment]
> We are currently comparing our results to results from using ccdproc and will update the repository with a test function this week.

👋 @kweis - how are you getting on with this update?

**Comment by kweis** [comment]
Apologies for the delay, I should have an update here quite soon

**Comment by migueldvb** [comment]
Thanks @kweis I have updated the issue checklist at the top of the review with the current status of the package. I will be glad to review the updated version when it is ready.

**Comment by kweis** [comment]
Hi there, 
I've addressed the outstanding checklist items as follows:
1. Installation instructions are in the README and I've added a requirements.txt file to install/update the required dependencies. Since there are only three nonstandard libraries, I believe the requirements.txt file handles the dependencies most succinctly. 
2. Documentation was added to the major functions and clarifying comments were added throughout the code.
3. I've included appropriate references in the README and in the paper.md file.

**Comment by migueldvb** [comment]
Thank you for the revised version. I will send you any further comments by the end of the week, if I have any.

**Comment by migueldvb** [comment]
I have a couple of comments on the latest version.  The README file refers to  "/example/rawdata zipfile (example.zip in release docs)". However there is no such file in the `docs` directory and I could not figure out how to download the test data from the description in the README. Since the package depends on astropy already I'd suggest using `astropy.utils.data` tor download the test data but this could be done in a number of other ways.  There is another reference in the README to the "use the test.py script (see below)" but this script cannot be found in the repo. It may have been just an oversight in not adding this file. Finally the suggested use of os.path for path manipulation is included in https://github.com/kweis/acronym/pull/13 that is currently open.

Apart from those issues the requirements for acceptance are met now and I think it is almost ready.

**Comment by arfon** [comment]
Hi @kweis @migueldvb - how are we doing here?

**Comment by kweis** [comment]
I cleaned up the README to address the most recent comments from @migueldvb -- the raw data is still in the release notes to keep it out of the main repository, but I linked to it so it's much easier to find.

I think I'd already addressed the os.path.join issue, but forgot to close it. closed now!

**Comment by migueldvb** [comment]
That sounds great. I recommend this paper for acceptance in JOSS.

**Comment by arfon** [comment]
> That sounds great. I recommend this paper for acceptance in JOSS.

Great!

@kweis - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by kweis** [comment]
The DOI is https://doi.org/10.5281/zenodo.570881

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.570881 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.570881" target="_blank">10.5281/zenodo.570881</a> is the archive.

**Comment by arfon** [comment]
@kweis - Could you move the references you currently have in the `paper.md` file into a `paper.bib` file and cite them directly please? (You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html))

**Comment by kweis** [comment]
Okay, moved it to the paper.bib file and cited using @ in the paper.md. Is that the citation you were referring to?

**Comment by arfon** [comment]
> Okay, moved it to the paper.bib file and cited using @ in the paper.md. Is that the citation you were referring to?

Yep. That looks good. 

@migueldvb - many thanks for your review here ✨ 

@kweis - your submission is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00102 ⚡️ 🚀 💥

**Comment by kweis** [comment]
Sounds great! Thanks for your insight and patience, @migueldvb @arfon!!
