### ISSUE TITLE
test_free_diffusion2D: error

### ISSUE THREAD

**Issue by mwacaan** [openjournals/joss-reviews#1020]
MATLAB R2014a on linux

>> test_free_diffusion2D
Error using  ./ 
Matrix dimensions must agree.

Error in rwalkfree (line 27)
    v = (v./sqrt(dot(v,v,3))) * ss;

Error in rwalk (line 36)
    X = rwalkfree(p, ns, ss);

Error in test_free_diffusion2D (line 24)
X = rwalk(p, ns, ssize);
 

### :warning: Please do not open issues on this repository :warning:

This repository is _exclusively_ for JOSS pre-review and review issues. These are generated as part of our submission process.

If you have a question about JOSS then please open an issue on the main JOSS repository: https://github.com/openjournals/joss

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1020 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@mwacaan - please do not open new issues on this repository. If you would like to open an issue for you review of https://github.com/openjournals/joss-reviews/issues/966 then please do so on the source repository here: https://github.com/davidnsousa/mcsd
