### ISSUE TITLE
[REVIEW]: Overlapping: a R package for Estimating Overlapping in Empirical Distributions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1023]
**Submitting author:** @masspastore (<a href="http://orcid.org/0000-0002-7922-6365">MASSIMILIANO PASTORE</a>)
**Repository:** <a href="https://github.com/masspastore/overlapping" target ="_blank">https://github.com/masspastore/overlapping</a>
**Version:** v1.5.0
**Editor:** @arfon
**Reviewer:** @soodoku, @russellpierce
**Archive:** <a href="https://doi.org/10.5281/zenodo.1920397" target="_blank">10.5281/zenodo.1920397</a>

## Status

[![status](http://joss.theoj.org/papers/05da34b6ecffbbb8f8be61362989a757/status.svg)](http://joss.theoj.org/papers/05da34b6ecffbbb8f8be61362989a757)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/05da34b6ecffbbb8f8be61362989a757"><img src="http://joss.theoj.org/papers/05da34b6ecffbbb8f8be61362989a757/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/05da34b6ecffbbb8f8be61362989a757/status.svg)](http://joss.theoj.org/papers/05da34b6ecffbbb8f8be61362989a757)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/masspastore/overlapping" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@soodoku & @russellpierce, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/masspastore/overlapping">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.5.0)?
- [x] **Authorship:** Has the submitting author (@https://github.com/masspastore) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/masspastore/overlapping">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.5.0)?
- [x] **Authorship:** Has the submitting author (@https://github.com/masspastore) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @soodoku, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01023/joss.01023/10.21105.joss.01023.pdf)

**Comment by arfon** [comment]
@soodoku, @russellpierce - please carry out your reviews in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by russellpierce** [comment]
Is it typical that the Statement of Need, Example, etc would be just in the paper and not in the README.md of the repo?

**Comment by russellpierce** [comment]
@masspator Nice to meet you.  I've added several issues to your repo to cover items that I believe are in this checklist.  Rather than giving you a lot of extra feedback at this time, I'll pause there and wait to see if that feedback seems useful. :)

**Comment by masspastore** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by masspastore** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1023 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1023/paper/paper.md): control characters are not allowed at line 1 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by masspastore** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1023 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/author.rb:23:in `strip_footnotes': undefined method `[]' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/author.rb:13:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:109:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:109:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:106:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:106:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@masspastore - please update your paper YAML header to _exactly_ match the format of this example: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

Please note that YAML is whitespace sensitive.

**Comment by masspastore** [comment]
Thanks @arfon 

I unfortunately added a new reference in the bib file without checking it. 
I updated the bib and the paper files, now I think it is correct.

**Comment by masspastore** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1023 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/author.rb:23:in `strip_footnotes': undefined method `[]' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/author.rb:13:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:109:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:109:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:106:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:106:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by masspastore** [comment]
@whedon  generate pdf

**Comment by masspastore** [comment]
Thanks @arfon 

I updated the YAML header as of your suggestion. 
I checked it in my computer and it works, I hope now it's fine.

**Comment by arfon** [comment]
@masspastore - please merge this PR too: https://github.com/masspastore/overlapping/pull/9

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01023/joss.01023/10.21105.joss.01023.pdf)

**Comment by russellpierce** [comment]
Oh darn, @soodoku I might have checked items off your list when I meant to be checking off mine.  My apologies!

**Comment by soodoku** [comment]
No worries.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01023/joss.01023/10.21105.joss.01023.pdf)

**Comment by arfon** [comment]
@soodoku, @russellpierce - it looks like you're both making good progress with your reviews here. Do you think you might be able to complete them in the next week?

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by masspastore** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01023/joss.01023/10.21105.joss.01023.pdf)

**Comment by russellpierce** [comment]
@arfon my son was born on Saturday, so my bandwidth is a little limited at the moment (and 10 days passed since you asked). I'll try to review late this week and see if any more feedback is needed.

**Comment by russellpierce** [comment]
@masspastore I added one more grammar correction under a git blame. Otherwise I think things are looking good.  cc: @arfon

**Comment by arfon** [comment]
@soodoku - it looks like there are a few checkboxes un-checked for your review. Is there still work to be done by the author or are you happy to accept here?

**Comment by soodoku** [comment]
@arfon: need to check a couple of things. i plan to get to it over the weekend. i will be in touch soonish.

**Comment by russellpierce** [comment]
@soodoku thanks for giving it a thorough look. I'll admit that I've been through it enough at this point where I don't have as clear as view on the end result as I might have at the start. So, it is entirely possible I'm missing something. :) I.e. don't take my signoff as a need for less rigour.

**Comment by soodoku** [comment]
hey @arfon: go for it.

**Comment by arfon** [comment]
@masspastore - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by masspastore** [comment]
Thanks @arfon - Sure, just done; here is the link: https://zenodo.org/record/1920397#.XAZeVeLTU2x. Doi for Zenodo is 10.5281/zenodo.1920397

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1920397.svg)](https://doi.org/10.5281/zenodo.1920397)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1920397 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1920397" target="_blank">10.5281/zenodo.1920397</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1023 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0    170      0 --:--:-- --:--:-- --:--:--   171
/app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c44264c87f39/lib/whedon/bibtex.rb:43:in `make_citation': undefined method `has_field?' for #<BibTeX::Comment x-kbibtex-personnameformatting=<%l><, %f>> (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c44264c87f39/lib/whedon/bibtex.rb:30:in `block in generate_citations'
	from /app/vendor/bundle/ruby/2.4.0/gems/bibtex-ruby-4.4.7/lib/bibtex/bibliography.rb:150:in `each'
	from /app/vendor/bundle/ruby/2.4.0/gems/bibtex-ruby-4.4.7/lib/bibtex/bibliography.rb:150:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c44264c87f39/lib/whedon/bibtex.rb:29:in `generate_citations'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c44264c87f39/lib/whedon/processor.rb:214:in `generate_crossref'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c44264c87f39/lib/whedon/processor.rb:91:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c44264c87f39/bin/whedon:76:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c44264c87f39/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon accept

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/100

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/100, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by masspastore** [comment]
Hi @arfon, I updated the bib file with all avaliable DOIs  

Thanks

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/105

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/105, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/106
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01023](https://doi.org/10.21105/joss.01023)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@soodoku, @russellpierce - many thanks for your reviews here ✨ 

@masspastore - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01023/status.svg)](https://doi.org/10.21105/joss.01023)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01023">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01023/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01023/status.svg
   :target: https://doi.org/10.21105/joss.01023
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01023/status.svg)](https://doi.org/10.21105/joss.01023)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
