### ISSUE TITLE
[PRE REVIEW]: Altair: Interactive Statistical Visualizations for Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1024]
**Submitting author:** @domoritz (<a href="http://orcid.org/0000-0002-3110-1053">ROBYN DOMINIK MORITZ</a>)
**Repository:** <a href="https://github.com/altair-viz/altair" target ="_blank">https://github.com/altair-viz/altair</a>
**Version:** v2
**Editor:** @jedbrown
**Reviewers:** @jedbrown, @dnszafir, @terrytangyan, @kellieotto

**Author instructions**

Thanks for submitting your paper to JOSS @domoritz. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@domoritz if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01024/joss.01024/10.21105.joss.01024.pdf)

**Comment by domoritz** [comment]
@arfon Done in https://github.com/altair-viz/altair/pull/1167.

I don't remember who said it but we had an editor volunteer to review the Altair submission. I hope that they see it and speak up. (https://github.com/altair-viz/altair/pull/394#issuecomment-429906564)

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01024/joss.01024/10.21105.joss.01024.pdf)

**Comment by arfon** [comment]
> @arfon Done in altair-viz/altair#1167.

Great. Can we get that merged in?

**Comment by domoritz** [comment]
That's a very odd citation style.

<img width="619" alt="screen shot 2018-10-16 at 16 16 52" src="https://user-images.githubusercontent.com/589034/47022981-f0177400-d15e-11e8-8b8a-df52182137f7.png">

<img width="658" alt="screen shot 2018-10-16 at 16 16 45" src="https://user-images.githubusercontent.com/589034/47022984-f279ce00-d15e-11e8-830f-f592095bfb36.png">

**Comment by arfonsmith** [comment]
Yes, I saw that. I was wondering what was going on myself... I suggest we
investigate as we make progress on this submission.

>

**Comment by ellisonbg** [comment]
Merged the altair PR.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01024/joss.01024/10.21105.joss.01024.pdf)

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01024/joss.01024/10.21105.joss.01024.pdf)

**Comment by arfon** [comment]
> That's a very odd citation style.

I think it's because the `author` string is in the format author AND author and author (e.g. https://github.com/altair-viz/altair/blob/master/paper/paper.bib#L19) rather than Lastname, Firstname and Lastname, Firstname and Lastname, Firstname

**Comment by domoritz** [comment]
I'll fix it.

**Comment by domoritz** [comment]
I fixed the author format in https://github.com/altair-viz/altair/pull/1169

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01024/joss.01024/10.21105.joss.01024.pdf)

**Comment by jedbrown** [comment]
It's somewhat outside my usual wheelhouse, but I have some potential reviewers in mind and would be happy to edit this submission if no other editor emerges to claim it.

**Comment by domoritz** [comment]
Hmm, the references still look funny. Do you have any suggestions? 

<img width="685" alt="screen shot 2018-10-18 at 09 14 33" src="https://user-images.githubusercontent.com/589034/47137222-49de8200-d2b6-11e8-962f-cec4391ab455.png">

**Comment by arfon** [comment]
This PR seems to fix the formatting @domoritz : https://github.com/altair-viz/altair/pull/1171

Check out this version I compiled locally based on these changes: 
[10.21105.joss.01024.pdf](https://github.com/openjournals/joss-reviews/files/2491965/10.21105.joss.01024.pdf)

**Comment by domoritz** [comment]
Excellent. May I ask how you compile the paper locally?

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01024/joss.01024/10.21105.joss.01024.pdf)

**Comment by jedbrown** [comment]
Looks good apart from capitalization in the CHI reference.

You can do a basic compile directly using pandoc, but if you want complete decoration you'd install https://github.com/openjournals/whedon/ (which has a lot of Ruby dependencies and ultimately calls pandoc with many arguments).
`pandoc -o paper.pdf --filter pandoc-citeproc --csl /path/to/apa.csl paper.md`

**Comment by domoritz** [comment]
I fixed the capitalization of CHI in https://github.com/altair-viz/altair/pull/1174.

**Comment by domoritz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01024/joss.01024/10.21105.joss.01024.pdf)

**Comment by domoritz** [comment]
@jedbrown @arfon Thank you for the pre-review. How do we find an editor/reviewer?

**Comment by jedbrown** [comment]
@whedon assign @jedbrown as reviewer

**Comment by jedbrown** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by jedbrown** [comment]
@terrytangyuan @kellieotto @adavidzh :wave: Would any of you be available to review this submission?

**Comment by terrytangyuan** [comment]
Yes I can review.

**Comment by adavidzh** [comment]
> @terrytangyuan @kellieotto @adavidzh 👋 Would any of you be available to review this submission?

I can review.

**Comment by kellieotto** [comment]
I can review as well.

**Comment by jedbrown** [comment]
@whedon add @dnszafir as reviewer

**Comment by whedon** [comment]
OK, @dnszafir is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @terrytangyan as reviewer

**Comment by whedon** [comment]
OK, @terrytangyan is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @kellieotto as reviewer

**Comment by whedon** [comment]
OK, @kellieotto is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1057. Feel free to close this issue now!

**Comment by adavidzh** [comment]
So I don’t get to help out this time? 🥺

**Comment by jedbrown** [comment]
@adavidzh If you put it that way, I'm happy to include you. I figured we had sufficient diversity of reviewers and this way we wouldn't feel bad about pinging you in the event of a subsequent submission relevant to your interests in the next coming months.

**Comment by adavidzh** [comment]
@jedbrown I'm happy to stay fresh for something else. It's just that the follow-up was not clear to me and I was perhaps over-eager for my first time. Thanks!

**Comment by jedbrown** [comment]
@adavidzh Thanks and sorry about my miscommunication.
