### ISSUE TITLE
[PRE REVIEW]: GPUE: Graphics Processing Unit Gross-Pitaevskii Equation solver

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1025]
**Submitting author:** @leios (<a href="http://orcid.org/0000-0002-3243-8918">James Schloss</a>)
**Repository:** <a href="https://github.com/GPUE-group/GPUE" target ="_blank">https://github.com/GPUE-group/GPUE</a>
**Version:** v1.0
**Editor:** @labarba
**Reviewers:** @mgalloy, @markbasham

**Author instructions**

Thanks for submitting your paper to JOSS @leios. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@leios if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by jmbr** [comment]
I'm not available for refereeing for the next 2-3 weeks. Feel free to notify me after that if necessary.

**Comment by arghdos** [comment]
Unfortunately I'm in the same boat as @jmbr -- finishing up my PhD here, and won't be available for at least a few weeks.

**Comment by labarba** [comment]
Thank you, @mgalloy -- I will assign you now, but am looking for a second reviewer before starting the review. Stay tuned.

**Comment by labarba** [comment]
@whedon assign @mgalloy as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mgalloy

**Comment by labarba** [comment]
@whedon add @markbasham as reviewer

**Comment by whedon** [comment]
OK, @markbasham is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1037. Feel free to close this issue now!
