### ISSUE TITLE
[PRE REVIEW]: PyMS: Python for Mycorrhizal Symbiosis data analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1029]
**Submitting author:** @jschnab (<a href="http://orcid.org/0000-0002-9515-332X">Jonathan Schnabel</a>)
**Repository:** <a href="https://github.com/jschnab/pyms" target ="_blank">https://github.com/jschnab/pyms</a>
**Version:** 0.8.1
**Editor:** @arfon
**Reviewers:** @aokad, @johnlees

**Author instructions**

Thanks for submitting your paper to JOSS @jschnab. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jschnab if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01029/joss.01029/10.21105.joss.01029.pdf)

**Comment by jschnab** [comment]
Hi, I suggest the following reviewers, in not particular order:
conradstack
tacaswell
krother
kellietto
Chilipp
aokad
nagoue

**Comment by jschnab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01029/joss.01029/10.21105.joss.01029.pdf)

**Comment by arfon** [comment]
@jschnab - could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by jschnab** [comment]
@arfon - I suggest the following reviewers, in no particular order:
conradstack
tacaswell
krother
kellietto
Chilipp
aokad
nagoue

**Comment by arfon** [comment]
Hi @aokad and @nagoue - would you both be willing to review this submission from @jschnab? You can see the paper [here](https://github.com/openjournals/joss-papers/blob/joss.01029/joss.01029/10.21105.joss.01029.pdf). 

I believe you have both reviewed for us in the past, but incase you don't recall, this is an overview of the JOSS review process: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by nagoue** [comment]
Hi,

Not for me this time.

Cheers,

Le 11/11/2018 à 01:43, Arfon Smith a écrit :

**Comment by aokad** [comment]
Yes, I'd be willing to review this submission. 
This would be my first time reviewing for JOSS, so I'd appreciate some guidance.

**Comment by arfon** [comment]
@nagoue - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by jschnab** [comment]
@arfon - Hi, nagoue already commented she's not available to review my submission.

**Comment by arfon** [comment]
> @arfon - Hi, nagoue already commented she's not available to review my submission.

My apologies @nagoue.

**Comment by arfon** [comment]
@martlj - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by martlj** [comment]
Hi,

sorry, I can’t help this time.

Cheers,
Martin

**Comment by jschnab** [comment]
@arfon - Hi, could I suggest a referee who is not on the list provided?

**Comment by arfon** [comment]
> @arfon - Hi, could I suggest a referee who is not on the list provided?

Definitely!

**Comment by jschnab** [comment]
@arfon - Hi, @johnlees agreed to review my submission.

**Comment by arfon** [comment]
@whedon add @johnlees as reviewer

**Comment by whedon** [comment]
OK, @johnlees is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1125. Feel free to close this issue now!

**Comment by arfon** [comment]
@aokad, @johnlees - many thanks for agreeing to review this submission. Please head over to #1125 where the actual review will take place.
