### ISSUE TITLE
[PRE REVIEW]: scarplet: A Python package for topographic template matching and diffusion dating

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1031]
**Submitting author:** @rmsare (<a href="http://orcid.org/0000-0003-3711-6771">Robert Sare</a>)
**Repository:** <a href="https://github.com/rmsare/scarplet" target ="_blank">https://github.com/rmsare/scarplet</a>
**Version:** 0.1.0
**Editor:** @kthyng
**Reviewers:** @fclubb, @mcflugen

**Author instructions**

Thanks for submitting your paper to JOSS @rmsare. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@rmsare if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kthyng it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @kthyng - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01031/joss.01031/10.21105.joss.01031.pdf)

**Comment by rmsare** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by rmsare** [comment]
kbarnhart, leouieda, kbevers or sgrieve all seems like good potential reviewers if any of them are interested.

**Comment by kthyng** [comment]
Hi @rmsare! Thanks for the suggestions. 

@leouieda and @kbevers are you willing and able to review this submission? We ask that reviews are in within about 2 weeks, and you can more information about the process [here](https://joss.readthedocs.io/en/latest/review_criteria.html).

**Comment by kbevers** [comment]
@kthyng Unfortunately I won't have the time to do a review of this within the next two weeks. I hope you can find someone else to take a look at it.

**Comment by kthyng** [comment]
@kbevers Thanks so much for letting me know!

@jkmacc-LANL You look like you might be a good reviewer for this submission. Are you willing and able to review this submission? We ask that reviews are in within about 2 weeks, and you can find more information about the process [here](https://joss.readthedocs.io/en/latest/review_criteria.html).

**Comment by rmsare** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01031/joss.01031/10.21105.joss.01031.pdf)

**Comment by kthyng** [comment]
Hi @jkmacc-LANL — any interest in reviewing this submission to JOSS?

**Comment by kthyng** [comment]
Hey @leouieda — are you available for reviewing this JOSS submission?

**Comment by kthyng** [comment]
@kbarnhart I'm trying to avoid asking you to do another review so soon after you doing one recently. However, this package does sound complementary to your and your group's work. Can you suggest someone else to review this who is involved with LandLab? Thanks for any help.

**Comment by kbarnhart** [comment]
@SiccarPoint or @gregtucker would be good Landlab people to ask.

**Comment by kthyng** [comment]
Hi @SiccarPoint! Are you willing and able to review this submission? We ask that reviews are in within about 2 weeks, and you can more information about the process [here](https://joss.readthedocs.io/en/latest/review_criteria.html).

**Comment by kthyng** [comment]
And thanks @kbarnhart!

**Comment by sgrieve** [comment]
Hi @kthyng unfortunately I am swamped at the moment and wouldn't be able to turn the review around until the start of next month. However, I have spoken to @fclubb and she is willing to review.

**Comment by fclubb** [comment]
Yep, I can review

**Comment by kthyng** [comment]
Thanks @fclubb, for being willing to review and @SiccarPoint and @sgrieve for letting me know.

@gregtucker Are you willing and able to review this submission? We ask that reviews are in within about 2 weeks, and you can more information about the process [here](https://joss.readthedocs.io/en/latest/review_criteria.html).

**Comment by kbarnhart** [comment]
I spoke with @gregtucker yesterday and learned that he won't be able to do this on the necessary timeline. I'm in a similar boat (can't take on a review until December).

Other Landlab folks to consider are: 
@nicgaspar @margauxmouchene and @nathanlyons

**Comment by kthyng** [comment]
Hi @nicgaspar @margauxmouchene and @nathanlyons! Any chance one of you can review this submission in the next two weeks?

Thanks again @kbarnhart.

**Comment by nathanlyons** [comment]
Hi @kthyng. I am committed elsewhere the remainder of the calendar year. Please feel free to contact me in the future for other reviews.

**Comment by nicgaspar** [comment]
Hi @kthyng. I’m sorry but I am traveling the next two weeks and I have two reviews already that I need to finish. You could also try @mcflugen. Please ask me again in the future.

**Comment by margauxmouchene** [comment]
Hi @kthyng. I tried installing everything before saying yes to reviewing it. Turns out I'm having major issues with the dependencies (pyfftw and GDAL - on OSX). As I understand you are on a tight schedule, I have to decline this review request. Please contact me again for other reviews.

**Comment by kthyng** [comment]
It's definitely a tough time of year! Everybody is booked!

@mcflugen — any chance you can review this submission in the next two weeks? Thanks for your consideration.

**Comment by rmsare** [comment]
@margauxmouchene Thank you for bringing this up. If you have a minute, would you mind pasting your install issues into a github issue or email (robertmsare@gmail.com)? Something as simple as the brew/pip errors and your system specs (OS X version) would be useful, no need for a full report. It would be helpful for me to document as I am not an OS X user.

And @kthyng and everyone - in hindsight, I'm sorry I submitted this so close to conference season for many people. Thank you all for bearing with me and fielding the review requests.

**Comment by kthyng** [comment]
@nathanlyons, @nicgaspar, and @margauxmouchene — The way we track potential reviewers is through a list, which you can sign up for: http://joss.theoj.org/reviewer-signup.html

**Comment by mcflugen** [comment]
@kthyng I could have a look at it this week but, if I'm not able to finish it by Friday, I probably wouldn't be able to get back to it until December, which is also pretty booked.

@margauxmouchene, @rmsare I also wasn't able to install things with *pip* but I was able to *conda*-install everything without problem (and run the tests - which, of course, all passed :tada:).

**Comment by rmsare** [comment]
@mcflugen Thanks for letting me know! I'll look into what's up with pip.

**Comment by kthyng** [comment]
Ok awesome everyone! I'd like to go ahead with our two reviewers @fclubb and @mcflugen. @mcflugen please do as much as you can before Friday and we'll figure it out from there if needed.

**Comment by kthyng** [comment]
@whedon assign @fclubb as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @fclubb

**Comment by kthyng** [comment]
@whedon add @mcflugen as reviewer

**Comment by whedon** [comment]
OK, @mcflugen is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1066. Feel free to close this issue now!
