### ISSUE TITLE
[PRE REVIEW]: dml: Distance Metric Learning in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1032]
**Submitting author:** @terrytangyuan (<a href="http://orcid.org/0000-0001-5243-233X">Yuan Tang</a>)
**Repository:** <a href="https://github.com/terrytangyuan/dml" target ="_blank">https://github.com/terrytangyuan/dml</a>
**Version:** v1.1.0
**Editor:** @arfon
**Reviewers:** @joethorley

**Author instructions**

Thanks for submitting your paper to JOSS @terrytangyuan. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@terrytangyuan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01032/joss.01032/10.21105.joss.01032.pdf)

**Comment by terrytangyuan** [comment]
Potential reviewers: @nhejazi @strengejacke @joethorley. Please let us know if you are willing to review this. Thanks!

**Comment by joethorley** [comment]
I'm willing

**Comment by terrytangyuan** [comment]
@arfon Could you be the editor?

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @joethorley as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @joethorley

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1036. Feel free to close this issue now!

**Comment by arfon** [comment]
@joethorley - thanks for agreeing to review this package! See you and @terrytangyuan over in #1036 for the actual review.
