### ISSUE TITLE
[PRE REVIEW]: polyCub: An R package for Integration over Polygons

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1033]
**Submitting author:** @bastistician (<a href="http://orcid.org/0000-0002-1791-9449">Sebastian Meyer</a>)
**Repository:** <a href="https://github.com/bastistician/polyCub" target ="_blank">https://github.com/bastistician/polyCub</a>
**Version:** 0.7.0
**Editor:** @karthik
**Reviewers:** @wrathematics

**Author instructions**

Thanks for submitting your paper to JOSS @bastistician. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bastistician if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @karthik - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01033/joss.01033/10.21105.joss.01033.pdf)

**Comment by bastistician** [comment]
Scanning through https://bit.ly/joss-reviewers, I found @nuest and @wrathematics to be potentially suitable reviewers for the R package **polyCub**.

**Comment by karthik** [comment]
👋  @nuest and @wrathematics, will either of you be able to review this submission?

**Comment by wrathematics** [comment]
Sorry for the delay. I keep messing up my email filters for JOSS, so I haven't been seeing the pings...

I believe I can review this package.

**Comment by karthik** [comment]
@whedon assign @wrathematics as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @wrathematics

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1056. Feel free to close this issue now!

**Comment by karthik** [comment]
Thanks Drew! 🙏 
Please carry out the review in the new thread and ping with any questions.
