### ISSUE TITLE
[PRE REVIEW]: resampy: efficient sample rate conversion in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#104]
**Submitting author:** bmcfee (<a href="http://orcid.org/0000-0001-6261-9747">Brian McFee</a>)
**Repository:** <a href="https://github.com/bmcfee/resampy" target ="_blank">https://github.com/bmcfee/resampy</a>
**Version:** 0.1.4
**Editor:** @arfon
**Reviewer:** @arokem

**What this issue is for**

Thanks for submitting your paper to JOSS bmcfee. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @tracykteal it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @tracykteal - would you be able to edit this one for us?

**Comment by arokem** [comment]
:hand: I can review this

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @arokem as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arokem

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/125. Feel free to close this issue now!
