### ISSUE TITLE
[REVIEW]: STEDY - Software for TEnsegrity DYnamics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1042]
**Submitting author:** @vaishnavtv (<a href="http://orcid.org/0000-0001-9897-0600">Venkata Vaishnav Tadiparthi</a>)
**Repository:** <a href="https://github.com/uqLab/stedy" target ="_blank">https://github.com/uqLab/stedy</a>
**Version:** v0.1.0
**Editor:** @labarba
**Reviewer:** @Kevin-Mattheus-Moerman, @ctdegroot, @apsabelhaus
**Archive:** <a href="https://doi.org/10.5281/zenodo.2527084" target="_blank">10.5281/zenodo.2527084</a>

## Status

[![status](http://joss.theoj.org/papers/932cce456c4dd1514e6c4e46d2088ad7/status.svg)](http://joss.theoj.org/papers/932cce456c4dd1514e6c4e46d2088ad7)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/932cce456c4dd1514e6c4e46d2088ad7"><img src="http://joss.theoj.org/papers/932cce456c4dd1514e6c4e46d2088ad7/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/932cce456c4dd1514e6c4e46d2088ad7/status.svg)](http://joss.theoj.org/papers/932cce456c4dd1514e6c4e46d2088ad7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/uqLab/stedy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Kevin-Mattheus-Moerman & @ctdegroot, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @labarba know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/uqLab/stedy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@vaishnavtv) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/uqLab/stedy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@vaishnavtv) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/uqLab/stedy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@vaishnavtv) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Kevin-Mattheus-Moerman, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01042/joss.01042/10.21105.joss.01042.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@labarba over at https://github.com/openjournals/joss-reviews/issues/1000# @apsabelhaus agreed to be reviewer, perhaps you could add him here.

**Comment by Kevin-Mattheus-Moerman** [comment]
@apsabelhaus let me introduce you to JOSS and reviewing for JOSS. [JOSS](http://joss.theoj.org/) is a free, open access, and open source journal. Reviews take place here, i.e. in Github issues. As you can see the top of this issue has checklists for the reviewers which will guide them through the review process. A set of checklists will be created for you if you join as reviewer. As described in our [review guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) the review focuses on [the software](https://github.com/uqLab/stedy) and a [short paper](https://github.com/openjournals/joss-papers/blob/joss.01042/joss.01042/10.21105.joss.01042.pdf). Reviewers can comment on this work here in this issue and are encouraged to created dedicated issues on the software repository, and link to them here, for larger items. Let me know if you have more questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@labarba so far @vaishnavtv has worked on has, and resolved, these issues which I've posted on the software repository:

- [ ] https://github.com/uqLab/stedy/issues/1 README issues
- [ ] https://github.com/uqLab/stedy/issues/2 Example TemplateForUser_DBar.m does not exist
- [ ] https://github.com/uqLab/stedy/issues/3 Comments about / errors in example: Template_DBar

**Comment by labarba** [comment]
I manually added the header comment to add @apsabelhaus as reviewer — thank you, all.

**Comment by labarba** [comment]
@Kevin-Mattheus-Moerman : I forgot how to give @apsabelhaus the permissions to edit the reviewer checklist or send him the appropriate invitation. Do you remember? I went to the Teams section of the `open journals` org, and couldn't immediately identify a team to add him. Help…

**Comment by Kevin-Mattheus-Moerman** [comment]
The first step is this: 
'@whedon add @apsabelhaus as reviewer'

**Comment by Kevin-Mattheus-Moerman** [comment]
Then this invitation should be accepted: https://github.com/openjournals/joss-reviews/invitations

**Comment by labarba** [comment]
The `@whedon add` commands sets things up _only_ if used in the Pre-Review issue, _before_ starting the review. Once we're here, adding a reviewer is a manual process.

**Comment by vaishnavtv** [comment]
You can find the pre-print of the cited reference [here](https://www.researchgate.net/publication/328676032_A_Lagrangian_Formulation_for_Constrained_Multibody_Dynamics_in_Tensegrity_Systems).

I hope the review is going smoothly. Please let us know if anything else is required.

**Comment by vaishnavtv** [comment]
Any issues with the review? It has been almost two weeks since the last update. Kindly let us know if there are problems with the software.

**Comment by ctdegroot** [comment]
@vaishnavtv Please have patience. As you know peer review takes time and reviewers cannot drop everything immediately to tend to a review. I will review within the next two weeks.

**Comment by labarba** [comment]
@vaishnavtv I kindly ask you that you be patient, and allow the review to proceed at a pace that reflects the fact that everyone here is a volunteer.

**Comment by ctdegroot** [comment]
@vaishnavtv The paper contains insufficient references and the one reference that is included is not formatted properly (it appears twice). Please include at least a couple more references. For example, you mention some similar software called "Simscape Multibody". You should reference that.  The first paragraph needs a reference or two also.

**Comment by ctdegroot** [comment]
@vaishnavtv Where can I find your automated tests?

**Comment by vaishnavtv** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1042 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    252      0 --:--:-- --:--:-- --:--:--   254
Error reading bibliography ./JOSSpaper.bib (line 6, column 3):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by vaishnavtv** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01042/joss.01042/10.21105.joss.01042.pdf)

**Comment by vaishnavtv** [comment]
@ctdegroot I have made the recommended changes to the paper - affiliations and references have been added. We were under the impression that our manuscript submitted for publication would suffice as it exhaustively covers all information pertinent to this submission as well. Thank you for the clarification. 

For the automated tests, would the files provided in the Examples folder be sufficient?

**Comment by ctdegroot** [comment]
@vaishnavtv The paper looks good now.

I don't think that the files in the Examples folder are sufficient as test cases because they do not assert what result is expected. Let's imagine that I am a user that makes some changes/extensions to the code. How to I check that I haven't broken anything that already existed?

From the JOSS review criteria:

Good: An automated test suite hooked up to an external service such as Travis-CI or similar
OK: Documented manual steps that can be followed to check the expected functionality of the software (e.g. a sample input file to assert behaviour)
Bad (not acceptable): No way for you the reviewer to check whether the software works

To get the tests into the 'OK' category you will need to provide some reference results that can be checked (preferably automatically) with the code outputs.

One other note, is that you should remove all of the ".DS_Store" files that are in some of the example folders. Normally you can put this in your .gitignore file to prevent them from being tracked in the future.

**Comment by vaishnavtv** [comment]
@ctdegroot 
As recommended, I have added a Tests folder to the repository. The user can simply run TestPendulum.m to check the results of their changes to the code. I have also modified the Contributing Guidelines document to reflect this update. 

I have removed all the .DS_Store files as well.

**Comment by ctdegroot** [comment]
@labarba I'm satisfied with the changes so far. Still need to finish checking on the functionality of the code; hopefully soon.

**Comment by Kevin-Mattheus-Moerman** [comment]
@vaishnavtv can you please work on adding basic community guidelines? See this issue:
- [ ] [Community Guidelines](https://github.com/uqLab/stedy/issues/6)

**Comment by Kevin-Mattheus-Moerman** [comment]
@labarba thanks for the reminder. Only one box now remains unticked and it relates to community guidelines. I've opened an issue on this an am awaiting feedback from the author.

**Comment by labarba** [comment]
We have recommendations to accept from @Kevin-Mattheus-Moerman and @ctdegroot, but we never heard back from @apsabelhaus.

👋 @apsabelhaus — did this escape your radar? If you're not available now to volunteer a review, we can proceed without you, and perhaps count on you at some other time. You can [sign up](http://joss.theoj.org/reviewer-signup.html) online to be listed as a potential reviewer.

**Comment by apsabelhaus** [comment]
@labarba yes, this did indeed fall under my radar! My apologies to the review team and the authors. I'll perform the review today.

**Comment by apsabelhaus** [comment]
@Kevin-Mattheus-Moerman it doesn't seem like I'm able to fill out the checklist. Following the link to https://github.com/openjournals/joss-reviews/invitations seems to imply I haven't been formally sent an invitation. Could you do so / am I missing something? I'll proceed with evaluating the software in the meantime! Thanks again for everyone's patience, I'm more used to traditional academic peer-review deadlines.

**Comment by labarba** [comment]
@arfon Can you help us? I added @apsabelhaus as reviewer manually here, after the review started, so we don't have the benefit of our bot `whedon` setting the permissions right. I don't remember how to give the permissions to the reviewer, in this case. I looked at the teams in the org, but it's not clear to me: a `joss-reviewers` team exists, but it has only two members.

**Comment by arfon** [comment]
@labarba - I've added @apsabelhaus as an external collaborator to this repository which will will allow them to update the checklist.  @apsabelhaus - the invite is available here: https://github.com/openjournals/joss-reviews/invitations

**Comment by apsabelhaus** [comment]
Thank you @arfon and @labarba ! Started checking off the list.

My initial review is that this is a very nice piece of software, with a well-defined use case, filling a gap that the community needs. With some minor changes and clarifications, I would be ready to recommend for publication. @vaishnavtv , I've opened a handful of issues, mostly about documentation or technical questions. I've currently left the following boxes unticked for these reasons:

1) Functionality: one minor potential bug about the video.
2) Functionality documentation: some confusion about the API and technical assumptions.
4) References: just a bit more explanation needed about certain technical parts that weren't referred to in the JOSS paper or your preprint. I've provided some examples to refer to.

Thanks to the authors for a great contribution to the tensegrity systems community!

**Comment by ctdegroot** [comment]
@vaishnavtv You need to revise your installation instructions. It is not clear that steps 3b and 3c are only required if there is an error. I had to read several times to make sense of it.

**Comment by ctdegroot** [comment]
@vaishnavtv In the test that you've added, please do not make the user interactively enter data. If I'm trying to test the code as a new user, I don't know what I should enter. Is one test enough to verify the full functioning of the code?

**Comment by ctdegroot** [comment]
@vaishnavtv Regarding the item "Performance: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)": You have stated in your paper that "We have demonstrated superiority of the method in terms of accuracy over the commercially avail- able dynamics simulator, Simscape Multibody". There is a performance claim made. How do I confirm it?

**Comment by labarba** [comment]
Thank you all for your careful work! 
@ctdegroot We don't _require_ test coverage or unit tests vs. regression tests.

The JOSS Review [criteria on tests](https://joss.readthedocs.io/en/latest/review_criteria.html?highlight=test#tests) are: 

> Authors are strongly encouraged to include an automated test suite covering the core functionality of their software.
> Good: An automated test suite hooked up to an external service such as Travis-CI or similar
> OK: Documented manual steps that can be followed to check the expected functionality of the software (e.g. a sample input file to assert behaviour)
> Bad (not acceptable): No way for you the reviewer to check whether the software works

**Comment by ctdegroot** [comment]
@labarba Thank you for the clarification. In this case I still think it falls into the not acceptable category. I ran the one test that was provided and based on the output I don't know if the code is working or not. It runs and shows some plots, but is it working correctly? Not sure.

**Comment by vaishnavtv** [comment]
@ctdegroot, when you run the test case, you should see the results of 3 checks (bar length, energy constraints and motion errors) in the command window. Let me know if that’s not being displayed.

**Comment by vaishnavtv** [comment]
@ctdegroot , about the performance claim issue, we demonstrated superiority in terms of accuracy over Simscape multibody and attached plots in the [preprint]. Would you like us to attach the relevant files to the repository?
[preprint]: https://www.researchgate.net/publication/328676032_A_Lagrangian_Formulation_for_Constrained_Multibody_Dynamics_in_Tensegrity_Systems

**Comment by ctdegroot** [comment]
@vaishnavtv The preprint is reference in the paper right? That is good enough for me to verify the performance claim. For the test, what are you comparing to for a reference? Is it an exact solution? It is not clear to me from inspecting the code or running the case. There are no comments in "Pendulum_MinRealODE.m" so I don't know what it does.

**Comment by vaishnavtv** [comment]
The test compares the results of our simulation with that of the commonly accepted ground truth for the same structure, i.e., a simulation performed using minimum coordinates. I will add comments to the corresponding files with a proper description. Would that be sufficient?

**Comment by ctdegroot** [comment]
@vaishnavtv If you are content with doing the absolute minimum possible amount of testing then I suppose, since the other reviewers have accepted your tests, that I can check the item off.

**Comment by vaishnavtv** [comment]
@ctdegroot, as recommended I have added another test case to the repository. I'm amending the contributing guidelines to reflect this change.

**Comment by ctdegroot** [comment]
@vaishnavtv Thanks for fixing these up. I've ticked the box for tests now, since there is enough to check the code to a reasonable degree.

**Comment by ctdegroot** [comment]
My review is concluded. I'm satisfied with the changes.

**Comment by labarba** [comment]
@vaishnavtv : I read over your revised paper and I only have one suggestion, and that is to delete the sentence: “The scientific computing community’s familiarity with MATLAB makes it a favored choice for performing simulations of this nature.”  (Unsubstantiated assessment.)

We now only await the recommendation to accept from @apsabelhaus.

Unofficially, I was surprised that you chose to deposit your preprint on ResearchGate, rather than arXiv, or [engrXiv](https://engrxiv.org). I encourage you to consider these options in the future.

**Comment by vaishnavtv** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01042/joss.01042/10.21105.joss.01042.pdf)

**Comment by vaishnavtv** [comment]
@labarba statement deleted. 
Could you help explain to me why one should choose arXiv or any of the other OSF journals over ResearchGate to publish preprints? Is there a visibility advantage?

**Comment by labarba** [comment]
👋  @apsabelhaus — We're waiting for you to finish the checklist. Are you still working on your review? Or are you ready to make a recommendation?

**Comment by apsabelhaus** [comment]
Hi all, thanks again for your patience, the semester just finished up here, so I'm going to work on this now.

**Comment by apsabelhaus** [comment]
All boxes checked from me. I recommend publication.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by labarba** [comment]
Oops. Forgot one thing ... @vaishnavtv: Could you now make a deposit in an archive, such as Zenodo, and give us the DOI here?

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.2527084 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2527084" target="_blank">10.5281/zenodo.2527084</a> is the archive.

**Comment by labarba** [comment]
👋 @vaishnavtv — Could you edit the metadata over at Zenodo, so that the title and list of authors match this submission?

**Comment by labarba** [comment]
Hi there, @vaishnavtv — As soon as you correct the metadata of the Zenodo entry, I can get you paper published here in JOSS. Let me know!

**Comment by vaishnavtv** [comment]
Happy new year! 
@labarba, it’s done. 
Is there anything else we need to add?

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/419

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/419, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/420
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01042](https://doi.org/10.21105/joss.01042)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
https://twitter.com/JOSS_TheOJ/status/1080093912616837120

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01042/status.svg)](https://doi.org/10.21105/joss.01042)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01042">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01042/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01042/status.svg
   :target: https://doi.org/10.21105/joss.01042
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01042/status.svg)](https://doi.org/10.21105/joss.01042)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by vaishnavtv** [comment]
Thank you @labarba and to all the reviewers, for your helpful inputs in the review process!
