### ISSUE TITLE
[REVIEW]: Reasons: A digital argument mapping library for modern browsers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1044]
**Submitting author:** @davekinkead (<a href="http://orcid.org/0000-0001-5396-8099">David Kinkead</a>)
**Repository:** <a href="https://github.com/davekinkead/reasons" target ="_blank">https://github.com/davekinkead/reasons</a>
**Version:** v1.0.1
**Editor:** @yochannah
**Reviewer:** @yochannah, @andytwoods
**Archive:** <a href="https://doi.org/10.5281/zenodo.2766003" target="_blank">10.5281/zenodo.2766003</a>

## Status

[![status](http://joss.theoj.org/papers/cdf89c5289d83c0e8f8af99929382324/status.svg)](http://joss.theoj.org/papers/cdf89c5289d83c0e8f8af99929382324)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/cdf89c5289d83c0e8f8af99929382324"><img src="http://joss.theoj.org/papers/cdf89c5289d83c0e8f8af99929382324/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/cdf89c5289d83c0e8f8af99929382324/status.svg)](http://joss.theoj.org/papers/cdf89c5289d83c0e8f8af99929382324)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/davekinkead/reasons" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@yochannah & @andytwoods, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @yochannah know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/davekinkead/reasons">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.1
- [x] **Authorship:** Has the submitting author (@davekinkead) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/davekinkead/reasons">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.1
- [x] **Authorship:** Has the submitting author (@davekinkead) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mbod, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01044/joss.01044/10.21105.joss.01044.pdf)

**Comment by yochannah** [comment]
Quick status check - is there anything I can do to help progress this? 👍

**Comment by davekinkead** [comment]
Thanks Yo - I’ve just got back from conference season and am working on an issue raised by the reviewer.

Dave

**Comment by yochannah** [comment]
fantastic - feel free to ask any questions on this issue if needed!

**Comment by yochannah** [comment]
Quick status check - let me know when we're ready to move forward or if you have any issues :)

**Comment by labarba** [comment]
👋  @mbod, @andytwoods — hi there, I'm one of the Associate Editors-in-chief, and am doing an audit of stalled submissions. We haven't heard from y'all in a while. Can you check in with us to get an idea of timelines for the review to progress? Thanks!

**Comment by labarba** [comment]
I have just followed up by email with @mbod, who has not shown signs of life here (cc. @yochannah).

**Comment by yochannah** [comment]
thanks @labarba! I think @davekinkead is also working on the issues raised by @andytwoods and will let us know when he is ready to revisit.

**Comment by davekinkead** [comment]
Hi all - I’m overseas at the moment but will be back on campus next week to action anything outstanding.

Dave

**Comment by davekinkead** [comment]
All fixed now & good to go. Sorry for the delay.

**Comment by labarba** [comment]
👋  @andytwoods — looks like we're ready for you to take a second look. Thanks!

**Comment by labarba** [comment]
Hi @mbod — we're hoping to hear from you here: can we still expect a review from you?

**Comment by yochannah** [comment]
@mbod,  @andytwoods, do you think you might be able to revisit this? Thanks!!!

**Comment by andytwoods** [comment]
congrats! All in order 
    /@
    \ \
  ___> \
 (__O)  \
(____@)  \
(____@)   \
 (__o)_    \
       \    \

**Comment by labarba** [comment]
@yochannah : we have one complete review now, and a second reviewer who has gone MIA. Could you make an assessment at this point about whether we can move forward with acceptance on the basis of the one review we have?

**Comment by davekinkead** [comment]
Hi @labarba any news?

**Comment by yochannah** [comment]
Okay, I've run through the review steps myself. @davekinkead I'll be happy to accept this, one this issue is fixed with the demo code in the repo:

https://github.com/davekinkead/reasons/issues/5 

I'll also give the paper a quick once-over again now.

**Comment by yochannah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01044/joss.01044/10.21105.joss.01044.pdf)

**Comment by yochannah** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.14742/ajet.1154 may be missing for title: Improving critical thinking using web based argument mapping exercises with automated feedback
- https://doi.org/10.1007/s10734-009-9226-9 may be missing for title: Computer-assisted argument mapping: a rationale approach
- https://doi.org/10.1007/s11409-012-9092-1 may be missing for title: An evaluation of argument mapping as a method of enhancing critical thinking performance in e-learning environments
- https://doi.org/10.4324/9780203393543 may be missing for title: Thinking critically about critical thinking
- https://doi.org/10.5840/teachphil200427213 may be missing for title: Argument maps improve critical thinking
- https://doi.org/10.2307/1275020 may be missing for title: The principles of judicial proof: as given by logic, psychology, and general experience, and illustrated in judicial trials

INVALID DOIs

- None
```

**Comment by yochannah** [comment]
@davekinkead Could you please add DOIs to the above publications? Thanks!

**Comment by davekinkead** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.7208/chicago/9780226028576.001.0001 is OK
- https://doi.org/10.14742/ajet.1154 is OK
- https://doi.org/10.1007/s10734-009-9226-9 is OK
- https://doi.org/10.1007/s11409-012-9092-1 is OK
- https://doi.org/10.1111/j.1467-9973.1992.tb00551.x is OK
- https://doi.org/10.1111/j.1469-5812.2010.00673.x is OK
- 10.1017/cbo9780511840005.005 is OK
- 10.5840/teachphil200427213 is OK
- https://doi.org/10.2307/1275020 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by davekinkead** [comment]
Hi @yochannah - https://github.com/davekinkead/reasons/issues/5 has been actioned & DOIs added

Thanks

**Comment by yochannah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01044/joss.01044/10.21105.joss.01044.pdf)

**Comment by yochannah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01044/joss.01044/10.21105.joss.01044.pdf)

**Comment by yochannah** [comment]
Hmm, so whedon can see that the references are there since it passes the check references step, but it's not generating links in the paper itself for some reason. @openjournals/joss-eics do we need to do anything to fix this?

**Comment by yochannah** [comment]
@davekinkead Thanks, the bug is fixed and looking good! 

One small extra thing I've noticed in the references: 

> Toulmin, S. E. (1958). The uses of argument. Cambridge university press. 

I suspect that Cambridge University Press should be capitalised. It's probably worth giving the manuscript a final proofread if you feel you need to, as well. 👍

Once the references thing above is all ironed out I'll ask you to make an archive on Zenodo or similar, but let's wait until we're sure we don't need to make any changes first.

**Comment by labarba** [comment]
@davekinkead — Try putting _just_ the DOI, i.e., the alphanumeric identifier, not the full URL, into the `doi` field of the `.bib` file.

**Comment by davekinkead** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01044/joss.01044/10.21105.joss.01044.pdf)

**Comment by labarba** [comment]
Just before the references, you have a link to the code repository. We include a link to the repo on the margin decorators (first page), so we ask that you don't add an additional link in the text or references. Can you edit that?

**Comment by davekinkead** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by labarba** [comment]
For your last reference, the DOI points to the book review. Did you mean this?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01044/joss.01044/10.21105.joss.01044.pdf)

**Comment by labarba** [comment]
You're missing the year for Toulmin, S. (2003).

**Comment by davekinkead** [comment]
@whedon  generate pdf

**Comment by davekinkead** [comment]
@labarba all the DOIs at crossref for the original 1913 article point to that review.  Should I drop the DOI?

**Comment by davekinkead** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01044/joss.01044/10.21105.joss.01044.pdf)

**Comment by labarba** [comment]
Regarding Wigmore (1913): you are citing the book, not the review of the book, so that DOI is not correct. However, I did find that the book is now in the public domain and you can find an online archive at https://archive.org/details/principlesofjudi00wigm/ — maybe you could add that URL.

**Comment by davekinkead** [comment]
Perfect @labarba!

@whedon generate pdf

**Comment by davekinkead** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01044/joss.01044/10.21105.joss.01044.pdf)

**Comment by davekinkead** [comment]
Comments 

https://github.com/openjournals/joss-reviews/issues/1044#issuecomment-491593171
https://github.com/openjournals/joss-reviews/issues/1044#issuecomment-491593290
https://github.com/openjournals/joss-reviews/issues/1044#issuecomment-491593585
https://github.com/openjournals/joss-reviews/issues/1044#issuecomment-491595545
https://github.com/openjournals/joss-reviews/issues/1044#issuecomment-491595939
https://github.com/openjournals/joss-reviews/issues/1044#issuecomment-491596274
https://github.com/openjournals/joss-reviews/issues/1044#issuecomment-491597090

have now been actioned. Thanks for your patience @yochannah @labarba

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by labarba** [comment]
Oops. Please now make a tagged release, and report the version number here, then make a deposit of your full repository on an archive service like Zenodo, and report the DOI here.

**Comment by labarba** [comment]
@yochannah — Did you tick off the checklist items for @mbod's list? If you, you should edit the comment and put your username there.

**Comment by davekinkead** [comment]
Hi @labarba 

Tagged release https://github.com/davekinkead/reasons/releases/tag/v1.0.1
Zendo https://zenodo.org/record/2766003

**Comment by labarba** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.2766003 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2766003" target="_blank">10.5281/zenodo.2766003</a> is the archive.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.7208/chicago/9780226028576.001.0001 is OK
- 10.14742/ajet.1154 is OK
- 10.1007/s10734-009-9226-9 is OK
- 10.1007/s11409-012-9092-1 is OK
- 10.1111/j.1467-9973.1992.tb00551.x is OK
- 10.1111/j.1469-5812.2010.00673.x is OK
- 10.1017/cbo9780511840005.005 is OK
- 10.5840/teachphil200427213 is OK
- 10.3200/ctch.53.1.41-48 is OK

MISSING DOIs

- https://doi.org/10.2307/1275020 may be missing for title: The principles of judicial proof: as given by logic, psychology, and general experience, and illustrated in judicial trials

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/682

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/682, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/683
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01044](https://doi.org/10.21105/joss.01044)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
I have now made this edit to the top post: https://github.com/openjournals/joss-reviews/issues/1044#issuecomment-491600234

**Comment by labarba** [comment]
Congratulations, @davekinkead, your JOSS paper is now published!

Many thanks to @yochannah, @andytwoods for their work on this submission 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01044/status.svg)](https://doi.org/10.21105/joss.01044)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01044">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01044/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01044/status.svg
   :target: https://doi.org/10.21105/joss.01044
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01044/status.svg)](https://doi.org/10.21105/joss.01044)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
