### ISSUE TITLE
[PRE REVIEW]: ReinforcementLearning: A Package to Perform Model-Free Reinforcement Learning in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1045]
**Submitting author:** @nproellochs (<a href="http://orcid.org/0000-0002-1835-7302">Nicolas Proellochs</a>)
**Repository:** <a href="https://github.com/nproellochs/ReinforcementLearning" target ="_blank">https://github.com/nproellochs/ReinforcementLearning</a>
**Version:** v1.0.2
**Editor:** @arfon
**Reviewers:** @terrytangyuan, @kbenoit

**Author instructions**

Thanks for submitting your paper to JOSS @nproellochs. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@nproellochs if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @leeper it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1045 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     87      0 --:--:-- --:--:-- --:--:--    87
Could not find bibliography file: proellochs-feuerriegel.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @leeper - the submitting author suggested you as the handling editor.

**Comment by nproellochs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1045 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     50      0 --:--:-- --:--:-- --:--:--    51
Error producing PDF.
! Misplaced alignment tab character &.
\f@nch@olf ->\footnotesize {\sffamily Pr&
                                         ouml;llochs et al., (2018). Reinfor...
l.282 

Looks like we failed to compile the PDF

**Comment by nproellochs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01045/joss.01045/10.21105.joss.01045.pdf)

**Comment by arfon** [comment]
@nproellochs - could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by nproellochs** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by nproellochs** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by nproellochs** [comment]
Potential reviewers are @kbenoit and @terrytangyuan

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by terrytangyuan** [comment]
@arfon Are you commenting in the wrong issue or is this on purpose? @nproellochs has suggested two potential reviewers (including myself) that are totally different than the ones you listed. I'd be happy to review though.

**Comment by kbenoit** [comment]
Happy to help if need, @arfon just let me know.

**Comment by arfon** [comment]
> @arfon Are you commenting in the wrong issue or is this on purpose? @nproellochs has suggested two potential reviewers (including myself) that are totally different than the ones you listed. I'd be happy to review though.

> Happy to help if need, @arfon just let me know.

Thanks folks! I was trying to not overload you both with reviews but if you're happy to help with this submission I'd love to have your reviews!

**Comment by terrytangyuan** [comment]
Thanks! Yes, happy to review this.

**Comment by arfon** [comment]
@whedon add @terrytangyuan as reviewer

**Comment by whedon** [comment]
OK, @terrytangyuan is now a reviewer

**Comment by arfon** [comment]
@whedon add @kbenoit as reviewer

**Comment by whedon** [comment]
OK, @kbenoit is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1087. Feel free to close this issue now!

**Comment by arfon** [comment]
OK thanks @terrytangyuan & @kbenoit - thanks for agreeing to review this submission! See you both over in #1087 for the actual review.
