### ISSUE TITLE
[PRE REVIEW]: ElGateau: A Library for Using the Elgato Stream Deck for Experimental Psychology Research

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1046]
**Submitting author:** @cMadan (<a href="http://orcid.org/0000-0003-3228-6501">Christopher R Madan</a>)
**Repository:** <a href="https://github.com/cMadan/ElGateau" target ="_blank">https://github.com/cMadan/ElGateau</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @JonathanReardon

**Author instructions**

Thanks for submitting your paper to JOSS @cMadan. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@cMadan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Kevin-Mattheus-Moerman it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @Kevin-Mattheus-Moerman - the submitting author suggested you as the handling editor :-)

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01046/joss.01046/10.21105.joss.01046.pdf)

**Comment by cMadan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01046/joss.01046/10.21105.joss.01046.pdf)

**Comment by cMadan** [comment]
For a reviewer, I'd like to suggest @JonathanReardon.

**Comment by Kevin-Mattheus-Moerman** [comment]
@JonathanReardon would you be able to review this submission for [JOSS](http://joss.theoj.org/)? The [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub and focuses on [the software](https://github.com/cMadan/ElGateau) and a [short paper](https://github.com/openjournals/joss-papers/blob/joss.01046/joss.01046/10.21105.joss.01046.pdf). Let me know if you have questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@cMadan thanks for this submission. Since this submission features a software to interact with a specific type of hardware device, can you say a couple of words about: 

1. What aspects of this work can be evaluated/reviewed without the device? 
2. Is the device needed to properly review this work? 
3. If so, are you able to lend the device to a reviewer (we have made such arrangements for other works in the past)? 
4. Have you programmed a virtual version of the hardware device i.e. a simulation environment so some of the functionality of the software can be tested in the absence of the device?

**Comment by DavidBrainard** [comment]
I'm sorry but I am swamped and won't be able to help with this review.

**Comment by Kevin-Mattheus-Moerman** [comment]
> I'm sorry but I am swamped and won't be able to help with this review.

@DavidBrainard thanks for you quick reply. Do you have any colleagues that you think could help here? Thanks.

**Comment by whedon** [comment]
OK, the reviewer is @JonathanReardon

**Comment by cMadan** [comment]
Thanks for getting things started, @Kevin-Mattheus-Moerman!

> What aspects of this work can be evaluated/reviewed without the device?

The toolbox includes a developer mode that simulates the device i/o, that functions within Jupyter Notebook. 

> Is the device needed to properly review this work? If so, are you able to lend the device to a reviewer (we have made such arrangements for other works in the past)?

The device isn't needed, since there is the developer mode. I also could demonstrate the device remotely (e.g., over Skype), doing a live demo of the device interaction on the device itself.

> Have you programmed a virtual version of the hardware device i.e. a simulation environment so some of the functionality of the software can be tested in the absence of the device?

Yes, there is a simulation mode built-in the code.

**Comment by cMadan** [comment]
@Kevin-Mattheus-Moerman, are we good to start the review issue, or is there anything else to get sorted first?

**Comment by Kevin-Mattheus-Moerman** [comment]
I was hoping to find another reviewer but no luck as of yet. I'll start the review process so we can get going.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1070. Feel free to close this issue now!

**Comment by cMadan** [comment]
Fyi., @Kevin-Mattheus-Moerman, the magic-word isn't needed anymore. `@whedon start review` is sufficient.
