### ISSUE TITLE
[PRE REVIEW]: TextWiller: collection of text mining utilities, specially devoted to the Italian language

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1048]
**Submitting author:** @scan2001 (<a href="http://orcid.org/0000-0001-5621-5463">andrea sciandra</a>)
**Repository:** <a href="https://github.com/livioivil/TextWiller" target ="_blank">https://github.com/livioivil/TextWiller</a>
**Version:** 2.0
**Editor:** @mgymrek
**Reviewers:** @timClicks

**Author instructions**

Thanks for submitting your paper to JOSS @scan2001. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@scan2001 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #1048 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:91:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:91:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by scan2001** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01048/joss.01048/10.21105.joss.01048.pdf)

**Comment by scan2001** [comment]
I'd like to suggest @lmullen as a potential reviewer

**Comment by lmullen** [comment]
Sorry, I'm not available to review at this time.

**Comment by arfon** [comment]
:wave: @mgymrek - would you be able to edit this submission for JOSS?

**Comment by scan2001** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01048/joss.01048/10.21105.joss.01048.pdf)

**Comment by scan2001** [comment]
@labarba : thank you for your advice. I edited the paper with some sentences about the the research application of the software and the targeted audience.

**Comment by danielskatz** [comment]
👋 @mgymrek - would you be able to edit this submission for JOSS? (reposting)

**Comment by danielskatz** [comment]
👋 @mgymrek - ping...

**Comment by mgymrek** [comment]
@whedon assign @mgymrek as editor

**Comment by whedon** [comment]
OK, the editor is @mgymrek

**Comment by mgymrek** [comment]
@zfurnas @masalmon @benmarwick
would any of you be able to review this submission?

**Comment by mgymrek** [comment]
@linuxscout @timClicks @lmullen would any of you be able to review this submission?

**Comment by mgymrek** [comment]
@linuxscout @timClicks @lmullen @zfurnas @masalmon @benmarwick pinging again to see if any of you would be able to review this one

**Comment by timClicks** [comment]
@mgymrek Hi Melissa! Sorry, I missed the first notification. I'll be happy to review.

**Comment by timClicks** [comment]
Hi @scan2001, thanks for the paper submission. I'm not officially an assigned reviewer, but I've taken a quick look at the paper. 

Let me start by saying that it's excellent to see NLP contributions to non-English languages.

**Prior art**

However, there are many text mining packages available, even sticking within the R community. I wonder if you should cite some of the other open source NLP packages and explain that they do not offer Italian stemming/normalisation?

From the review guidelines:

> Submissions that implement solutions already solved in other software packages are accepted into JOSS provided that they meet the criteria listed above **and cite prior similar work**. [emphasis added]


**Authorship**

I believe that it's up to your team to decide on authorship, but the three authors don't match the authors listed in the [DESCRIPTION](https://github.com/livioivil/TextWiller/blob/master/DESCRIPTION) file or the [TextWiller-package.R](https://github.com/livioivil/TextWiller/blob/master/R/TextWiller-package.R#L13) file.

Also, from the [contribution list](https://github.com/livioivil/TextWiller/graphs/contributors), it's unclear what level of contribution that your first author has made? (I assume that some of the commit history has been lost)  

Here is the relevant guidance from the review guidelines:

> As part of the review process, you are asked to check whether the submitting author has made a ‘substantial contribution’ to the submitted software (as determined by the commit history) and to check that ‘the full list of paper authors seems appropriate and complete?’ 


**Documentation**

[TextWiller's API documentation](https://github.com/livioivil/TextWiller/tree/master/man) is in Italian. However, it looks comprehensive.

(Deferring to @mgymrek for an opinion about whether this is allowed) 



**Tests**

TextWiller doesn't appear to have a comprehensive test suite.

**Comment by livioivil** [comment]
> **Authorship**

> I believe that it's up to your team to decide on authorship, but the three authors don't match the authors listed in the [DESCRIPTION](https://github.com/livioivil/TextWiller/blob/master/DESCRIPTION) file or the [TextWiller-package.R](https://github.com/livioivil/TextWiller/blob/master/R/TextWiller-package.R#L13) file.

> Also, from the [contribution list](https://github.com/livioivil/TextWiller/graphs/contributors), it's unclear what level of contribution that your first author has made? (I assume that some of the commit history has been lost)

Hi, I'm the host of the package. I confirm that I have done a large part of the submissions. However, @scan2001 in most of the cases scripted the first version of the code. So, I think, he deserves the merit of the first authorship.
I hope this helps.

**Comment by mgymrek** [comment]
thanks @timClicks! I am going to move this over to a review thread

**Comment by mgymrek** [comment]
@whedon assign @timClicks as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @timClicks

**Comment by mgymrek** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1256. Feel free to close this issue now!
