### ISSUE TITLE
[PRE REVIEW]: Read, Tidy, and Display Data from Microtiter Plates in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#105]
**Submitting author:** @seaaan (<a href="http://orcid.org/0000-0002-9409-9405">Sean Hughes</a>)
**Repository:** <a href="https://github.com/ropenscilabs/plater" target ="_blank">https://github.com/ropenscilabs/plater</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** @arfon

**What this issue is for**

Thanks for submitting your paper to JOSS @seaaan. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@karthik @noamross - has this submission already been accepted into rOpenSci?

**Comment by noamross** [comment]
This submission has been accepted to rOpenSci. The review thread can be
found here: https://github.com/ropensci/onboarding/issues/60

**Comment by arfon** [comment]
> This submission has been accepted to rOpenSci. The review thread can be
found here: ropensci/onboarding#60

👍 thanks.

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/106. Feel free to close this issue now!
