### ISSUE TITLE
@davidnsousa below are some minor issues with the paper. Please work on these and regenerate the paper here by calling `@whedon generate pdf`.

### ISSUE THREAD

**Issue by davidnsousa** [openjournals/joss-reviews#1050]
- [x] Typo in: `....and any measures the user may want to defined, as well as....`, here `defined` should be `define`. 
- [x] Please add DOI's or hyperlinks where possible for all references.

_Originally posted by @Kevin-Mattheus-Moerman in https://github.com/openjournals/joss-reviews/issues/966#issuecomment-433008208_

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1050 with the following error: 

 Can't find any papers to compile :-(
