### ISSUE TITLE
[PRE REVIEW]: morphMan: Automated manipulation of vascular geometries

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1051]
**Submitting author:** @aslakbergersen (<a href="http://orcid.org/0000-0001-5063-3680">Aslak Bergersen</a>)
**Repository:** <a href="https://github.com/KVSlab/morphMan" target ="_blank">https://github.com/KVSlab/morphMan</a>
**Version:** v0.1
**Editor:** @trallard
**Reviewers:** @brainstorm, @rlizzo

**Author instructions**

Thanks for submitting your paper to JOSS @aslakbergersen. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@aslakbergersen if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @trallard it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01051/joss.01051/10.21105.joss.01051.pdf)

**Comment by arfon** [comment]
:wave: @trallard - the submitting author suggested you as the handling editor.

**Comment by hkjeldsberg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01051/joss.01051/10.21105.joss.01051.pdf)

**Comment by hkjeldsberg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01051/joss.01051/10.21105.joss.01051.pdf)

**Comment by hkjeldsberg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01051/joss.01051/10.21105.joss.01051.pdf)

**Comment by hkjeldsberg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01051/joss.01051/10.21105.joss.01051.pdf)

**Comment by hkjeldsberg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01051/joss.01051/10.21105.joss.01051.pdf)

**Comment by hkjeldsberg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01051/joss.01051/10.21105.joss.01051.pdf)

**Comment by hkjeldsberg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01051/joss.01051/10.21105.joss.01051.pdf)

**Comment by aslakbergersen** [comment]
@rlizzo if you have the time, I think you would be a very good reviewer for this paper since this is a VTK/VMTK application.

**Comment by rlizzo** [comment]
Thanks for the note @aslakbergersen. Count me in. From a quick look this seems like an interesting project/paper.

**Comment by rlizzo** [comment]
As a matter of disclosure to the editor @trallard. I am one of the lead developers of [VMTK](www.github.com/vmtk/vmtk), which this project uses extensively; in addition I was an author of VMTK's [accepted JOSS paper](http://joss.theoj.org/papers/10.21105/joss.00745#), which was for the version of the VMTK library this project requires. 

However, as I do not have any prior relationship (professional or personal) with the listed authors or their employer - Simula Research Laboratory - I do not believe this to be a [conflict of interest](https://github.com/openjournals/joss/blob/master/COI.md). However, it should be publicly noted for the integrity of the open review process.

**Comment by trallard** [comment]
@whedon add @rlizzo as reviewer

**Comment by whedon** [comment]
OK, @rlizzo is now a reviewer

**Comment by aslakbergersen** [comment]
Hey @trallard, @brainstorm is a potential reviewer with a perfect background for giving a good review on this project. He reviewed the vmtk paper in JOSS.

**Comment by trallard** [comment]
Hi @brainstorm 👋  would you be able to review this submission?

**Comment by brainstorm** [comment]
@whedon assign @brainstorm as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @brainstorm

**Comment by brainstorm** [comment]
Sure @trallard, happy to review along... didn't want to substitute @rlizzo, I thought whedon added on co-reviewers by default, sorry about that :-S

**Comment by arfon** [comment]
@whedon add @rlizzo as reviewer

**Comment by whedon** [comment]
OK, @rlizzo is now a reviewer

**Comment by arfon** [comment]
@brainstorm `assign` clobbers all existing assignments. Sorry the commands aren't a little clearer...

**Comment by trallard** [comment]
@wehdon start review

**Comment by trallard** [comment]
@whedon  start review

**Comment by trallard** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1065. Feel free to close this issue now!

**Comment by trallard** [comment]
We can now migrate to the [review issue](https://github.com/openjournals/joss-reviews/issues/1065) !!!
