### ISSUE TITLE
[PRE REVIEW]: CITapp - a free reaction time-based Concealed Information Test application

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1052]
**Submitting author:** @gasparl (<a href="http://orcid.org/0000-0001-9401-4830">Gáspár Lukács</a>)
**Repository:** <a href="https://github.com/gasparl/citapp_pc" target ="_blank">https://github.com/gasparl/citapp_pc</a>
**Version:** v1.0.0
**Editor:** @yochannah
**Reviewers:** @vsoch, @andytwoods

**Author instructions**

Thanks for submitting your paper to JOSS @gasparl. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@gasparl if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1052 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1052/paper/paper.md): invalid trailing UTF-8 octet at line 1 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@gasparl - @whedon can't compile this paper as the `paper.md` and `paper.bib` don't seem to be valid UTF-8 . Could you try saving them as UTF-8 encoded and updating your repository?

**Comment by gasparl** [comment]
Sure - I converted to UTF-8 and updated. Hope it's fine now.

**Comment by arfon** [comment]
@whedon compile pdf

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01052/joss.01052/10.21105.joss.01052.pdf)

**Comment by gasparl** [comment]
There were some small syntax mistakes in the paper.bib; I now corrected.

**Comment by gasparl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01052/joss.01052/10.21105.joss.01052.pdf)

**Comment by yochannah** [comment]
@whedon assign @yochannah as editor

**Comment by whedon** [comment]
OK, the editor is @yochannah

**Comment by yochannah** [comment]
:wave: Hey @gasparl! I'll be editing this paper. Thanks for the list of suggested reviewers. While we're settling who will review the paper, it might be a good idea to look through [another review issue in this repo](https://github.com/openjournals/joss-reviews/labels/review) to get an idea of the things reviewers will be looking for. I'd recommend starting by adding a README.md to your bitbucket repo to provide basic guidelines for anyone visiting the repo.

**Comment by andytwoods** [comment]
Kind of wish there was a readme and not just the pdf. And can't access the pdf on my fone as I'd need to download whole project! Happy to review if they add a readme.

**Comment by gasparl** [comment]
Thanks very much @yochannah and @andytwoods! I now renamed the documentation md file to README.md - if these should be two separate texts (e.g., shorter README.md), do let me know.

I checked a couple of previous reviews already, but I will do another round very soon.

**Comment by RichardLitt** [comment]
I unfortunately do not have time at the moment. Good luck.

**Comment by gasparl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01052/joss.01052/10.21105.joss.01052.pdf)

**Comment by gasparl** [comment]
I went through the Review checklist once more, and I think everything should be fine. I now added a more thoroughly explained example usage, two example output files, and also an automatic testing function. I correspondingly updated the manual with the related information.
I also made some very small final corrections in the paper.

**Comment by yochannah** [comment]
Sorry, still on the hunt for suitable reviewers. @vsoch, @xirdneh - is this a paper you'd be interested in reviewing?

**Comment by yochannah** [comment]
I've reached out to some more possible reviewers - hopefully it'll be easier to find someone now that the holidays are over!

**Comment by yochannah** [comment]
Quick update: I've had a couple more polite declines unfortuantely, mostly due to people being busy. I have another few leads to try though. Thank you for your patience!

**Comment by gasparl** [comment]
No problem, thank you for the efforts.

**Comment by gasparl** [comment]
Thanks @vsoch!
@yochannah: should I move it to Github? It's totally fine by me.

**Comment by yochannah** [comment]
@gasparl I'd be reluctant to force you to, but if you really don't mind then go ahead! I can edit the issue to the URL at the top of this once you're ready.

@vsoch Yay, thank you! 🥑

**Comment by vsoch** [comment]
I highly encourage moving to Github :) At quick glance I see something that I would really enjoy (after review) adding static Github pages preview / containers with continuous integration, and (it's probably doable on bitbucket) but I like Github much better. At least every time I've tried bitbucket I can't ever find what I'm looking for, lol.

**Comment by gasparl** [comment]
It's really no problem, I've been planning to gradually move my all code to Github anyway.
Here is the new repository: https://github.com/gasparl/citapp_pc
I think it should be all there and fine - but if there is anything else I should do, let me know.

**Comment by yochannah** [comment]
Okay, thanks for migrating this @gasparl! :) I've edited the new url in so I'll kick off the review process now  🎉

**Comment by yochannah** [comment]
@whedon assign @vsoch as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @vsoch

**Comment by yochannah** [comment]
@whedon add @andytwoods as reviewer

**Comment by whedon** [comment]
OK, @andytwoods is now a reviewer

**Comment by yochannah** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1179. Feel free to close this issue now!

**Comment by yochannah** [comment]
Okay all - hop over to #1179 and let's get reviewing! 

@andytwoods I know it was some time ago when you agreed to review - if your availability has changed that is fine - just let me know.

**Comment by vsoch** [comment]
@arfon it looks like there is a bug that when the repo was transferred, the old repo (bitbucket) was used and not the edited github one here! I'll update the repo to Github in the review, and maybe want to look into why this happened.
