### ISSUE TITLE
[PRE REVIEW]: Rule-based Integration -- An extensive system of symbolic integration rules

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1054]
**Submitting author:** @halirutan (<a href="http://orcid.org/0000-0003-0361-9063">Patrick Scheibe</a>)
**Repository:** <a href="https://github.com/RuleBasedIntegration/JOSS-Publication" target ="_blank">https://github.com/RuleBasedIntegration/JOSS-Publication</a>
**Version:** 4.16.0.4
**Editor:** @danielskatz
**Reviewers:** @acolum, @rljacobson

**Author instructions**

Thanks for submitting your paper to JOSS @halirutan. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@halirutan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @danielskatz it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01054/joss.01054/10.21105.joss.01054.pdf)

**Comment by arfon** [comment]
:wave: @danielskatz - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by halirutan** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by halirutan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01054/joss.01054/10.21105.joss.01054.pdf)

**Comment by halirutan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01054/joss.01054/10.21105.joss.01054.pdf)

**Comment by danielskatz** [comment]
Sorry for the delay - I missed this earlier.

@halirutan - what is the specific software you are submitting (which repository/repositories)?

Also, if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Comment by halirutan** [comment]
@danielskatz Thanks for your response. The specific OSS we want to submit for publishing is the Mathematica implementation for the Rubi integrator which lives here

https://github.com/RuleBasedIntegration/Rubi

However, since this is a larger endeavor we have created a GitHub organization where all repositories live under [github.com/RuleBasedIntegration](https://github.com/RuleBasedIntegration). That was the logical decision as we provide the large database of over 70000 test-integrals for several languages and e.g. the 6600+ integration rules as PDF as well and we wanted a better separation from the implementation. We have provided links to the website and all important repositories in the manuscript.

As reviewers, someone with knowledge of Mathematica and a an understanding of symbolic integration would be good. This narrows down the list pretty much and I suggest

rljacobson
wspr
acolum

If rljacobson is who I think he is, then I do know him from some discussions if that matters. If this is a criterion for exclusion, then I hope he can be at least the 2nd reviewer. He is an expert in both Mathematica and mathematics and I am certain that his suggestions will help to improve the publication.

**Comment by danielskatz** [comment]
@rljacobson, @wspr, @acolum - Would you be willing to review this submission?

**Comment by acolum** [comment]
Yes, I'd be willing to review this submission. This would be my first time reviewing for JOSS, so I'd appreciate some guidance.

**Comment by rljacobson** [comment]
I am happy to review this submission. Like @acolum, this would be my first time reviewing for JOSS, but I fully support its mission and look forward to participating!

For the record, I am [Robert Jacobson, Assistant Professor of Mathematics at Roger Williams University](https://www.rwu.edu/academics/schools-and-colleges/fssns/faculty/robert-jacobson). I hold a PhD in mathematics and have a significant background in computer science. Having used Mathematica professionally for many years and even built compiler tools for the Mathematica programming language, I think it is fair to call me an expert in Mathematica.

**Comment by halirutan** [comment]
@danielskatz It seems we have found two reviewers. How do we go from here? Do they need your final Go?

@whedon generate pdf

**Comment by danielskatz** [comment]
Thanks @acolum and @rljacobson  - I'll start the review now in a new issue

**Comment by danielskatz** [comment]
@whedon assign @acolum as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @acolum

**Comment by danielskatz** [comment]
@whedon add @rljacobson as reviewer

**Comment by whedon** [comment]
OK, @rljacobson is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1073. Feel free to close this issue now!
