### ISSUE TITLE
[PRE REVIEW]: QComms QKD Software Toolkit

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1055]
**Submitting author:** @richardcollins (<a href="http://orcid.org/0000-0002-6238-990X">Richard Collins</a>)
**Repository:** <a href="https://gitlab.com/QComms/cqptoolkit" target ="_blank">https://gitlab.com/QComms/cqptoolkit</a>
**Version:** 0.3
**Editor:** @brainstorm
**Reviewers:** @ejdanderson

**Author instructions**

Thanks for submitting your paper to JOSS @richardcollins. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@richardcollins if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @brainstorm it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1055 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    115      0 --:--:-- --:--:-- --:--:--   115
[WARNING] Could not convert image '/tmp/tex2pdf.419/cf2a65fef76d0435350459a434ca66a263cebdd8.svg': check that rsvg2pdf is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.419/cf2a65fef76
d0435350459a434ca66a263cebdd8.svg (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.239 ...65fef76d0435350459a434ca66a263cebdd8.svg}

Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @brainstorm - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1055 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    190      0 --:--:-- --:--:-- --:--:--   192
[WARNING] Could not convert image '/tmp/tex2pdf.509/cf2a65fef76d0435350459a434ca66a263cebdd8.svg': check that rsvg2pdf is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.509/cf2a65fef76
d0435350459a434ca66a263cebdd8.svg (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.239 ...65fef76d0435350459a434ca66a263cebdd8.svg}

Looks like we failed to compile the PDF

**Comment by richardcollins** [comment]
I've changed the image to eps instead of svg - does that fix the error?

On Wed, 2018-10-31 at 12:24 -0700, whedon wrote:

Attempting PDF compilation. Reticulating splines etc...

**Comment by arfon** [comment]
> I've changed the image to eps instead of svg - does that fix the error?

Let's find out...

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01055/joss.01055/10.21105.joss.01055.pdf)

**Comment by brainstorm** [comment]
Reaching out to other reviewers, hard to find former colleagues and acquaintances with **quantum** expertise within my circles :-S

**Comment by brainstorm** [comment]
@ejdanderson I've found [your paper about QKD](https://github.com/ejdanderson/paper-quantum-key-distribution/blob/master/paper.pdf) interesting. The context of why I'm writing you today is that JOSS publishes articles about open source research software and as an editor I think that you could be a valuable reviewer for this submission.

If you would like to collaborate with JOSS as a reviewer, you'll find [the process fairly straightforward and well documented](https://joss.readthedocs.io/en/latest/review_criteria.html#review-items). Please let me know if that sounds interesting to you and so we can proceed having you as a reviewer for this JOSS submission?

**Comment by ejdanderson** [comment]
@brainstorm Sorry for the delay, I'd be happy to review.

**Comment by brainstorm** [comment]
@whedon assign @ejdanderson as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ejdanderson

**Comment by brainstorm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1119. Feel free to close this issue now!

**Comment by brainstorm** [comment]
That's fantastic @ejdanderson, let's go into it through issue #1119 then, thanks for your time! :)
