### ISSUE TITLE
[REVIEW]: polyCub: An R package for Integration over Polygons

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1056]
**Submitting author:** @bastistician (<a href="http://orcid.org/0000-0002-1791-9449">Sebastian Meyer</a>)
**Repository:** <a href="https://github.com/bastistician/polyCub" target ="_blank">https://github.com/bastistician/polyCub</a>
**Version:** 0.7.0
**Editor:** @karthik
**Reviewer:** @wrathematics
**Archive:** <a href="https://doi.org/10.5281/zenodo.2559486" target="_blank">10.5281/zenodo.2559486</a>

## Status

[![status](http://joss.theoj.org/papers/5b55a804b26dab315d532b283d10283a/status.svg)](http://joss.theoj.org/papers/5b55a804b26dab315d532b283d10283a)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/5b55a804b26dab315d532b283d10283a"><img src="http://joss.theoj.org/papers/5b55a804b26dab315d532b283d10283a/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/5b55a804b26dab315d532b283d10283a/status.svg)](http://joss.theoj.org/papers/5b55a804b26dab315d532b283d10283a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bastistician/polyCub" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@wrathematics, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @karthik know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bastistician/polyCub">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.7.0)?
- [x] **Authorship:** Has the submitting author (@bastistician) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @wrathematics it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01056/joss.01056/10.21105.joss.01056.pdf)

**Comment by wrathematics** [comment]
Sorry this took me so long. I think everything basically looks good. A few very minor comments:

* The README.md file describes how to contribute, report problems, and seek support. But I think it's somewhat popular to have a CONTRIBUTING.md file. Personally I prefer having that information in a README, but you might consider creating one.
* I found one minor compiler warning. I submitted an issue on your repo, but as I say, it's quite minor so you may close the issue if you wish to ignore.
* Your README.md is quite thorough. You might consider turning it into a package vignette.
* I would personally like to see some benchmarks (perhaps in a future vignette). Even if you just compared the performance/accuracy tradeoffs that you outline in the paper, I think it would be very helpful.

As far as the JOSS review is concerned, I don't consider any of these issues blockers.

**Comment by karthik** [comment]
Thanks very much @wrathematics!
@bastistician Please let me know if you want to address these optional fixes before acceptance.

**Comment by bastistician** [comment]
Thanks a lot for the review, @wrathematics! (BTW: I wouldn't judge two weeks as a long review period.)
I really like your suggestion of turning the README into a package vignette as well as including some benchmarks therein. Let me do that before acceptance (@karthik).

**Comment by labarba** [comment]
:wave @bastistician — We haven't heard from you in a while. What's your status? Are you able to work on this revision soon?

**Comment by bastistician** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01056/joss.01056/10.21105.joss.01056.pdf)

**Comment by bastistician** [comment]
I have
* implemented the suggested improvements and increased the package version to 0.7.1
* not yet tagged that release nor submitted to CRAN
* made minor modifications in the paper (referencing the new vignette), see the updated article proof

@wrathematics : May I include your name as a reviewer in the package [DESCRIPTION](https://github.com/bastistician/polyCub/blob/0323d96a0f7913571463995d2686f0b74341c6d9/DESCRIPTION) (with role="rev")?

@karthik : How do we proceed? Is there an intended release schedule at JOSS? I would like the package to be cited using this JOSS publication, so I have included a reference in the package [CITATION](https://github.com/bastistician/polyCub/blob/0323d96a0f7913571463995d2686f0b74341c6d9/inst/CITATION) file. However, the DOI will only be registered later, and the volume and issue number are probably not yet fixed (or can I assume "4(33)" as indicated in the footnote of the current proof?). Should I release the package on CRAN prior to or after JOSS acceptance and archiving on Zenodo?

**Comment by karthik** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01056/joss.01056/10.21105.joss.01056.pdf)

**Comment by karthik** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by karthik** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1214/14-AOAS743 is OK
- http://doi.org/10.1007/s10543-007-0131-2 is OK
- http://doi.org/10.1093/sysbio/syv057 is OK
- http://doi.org/10.18637/jss.v077.i11 is OK
- http://doi.org/10.18637/jss.v012.i06 is OK
- http://doi.org/10.1016/j.cpc.2005.01.010 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by karthik** [comment]
@bastistician Can you please deposit the latest version of your package on Zenodo and share the DOI with me here? 🙏

**Comment by bastistician** [comment]
@karthik Today, I have released the package on [CRAN](https://CRAN.R-project.org/package=polyCub) (version 0.7.1) and created a corresponding [GitHub release](https://github.com/bastistician/polyCub/releases/tag/v0.7.1), which has subsequently been pushed to Zenodo. Here is the DOI:

https://doi.org/10.5281/zenodo.2559486

**Comment by karthik** [comment]
@whedon set zenodo.2559486 as archive

**Comment by whedon** [comment]
zenodo.2559486 doesn't look like an archive DOI.

**Comment by karthik** [comment]
@whedon set 10.5281/zenodo.2559486 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2559486" target="_blank">10.5281/zenodo.2559486</a> is the archive.

**Comment by karthik** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1214/14-AOAS743 is OK
- http://doi.org/10.1007/s10543-007-0131-2 is OK
- http://doi.org/10.1093/sysbio/syv057 is OK
- http://doi.org/10.18637/jss.v077.i11 is OK
- http://doi.org/10.18637/jss.v012.i06 is OK
- http://doi.org/10.1016/j.cpc.2005.01.010 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/478

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/478, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by karthik** [comment]
LGTM. EICs, this is ready to accept.

**Comment by arfon** [comment]
> LGTM. EICs, this is ready to accept.

Thanks @karthik. In the future can you ping @openjournals/joss-eics?

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/485
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01056](https://doi.org/10.21105/joss.01056)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@wrathematics - many thanks for your review here and to @karthik for editing this submission ✨ 

@bastistician - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01056/status.svg)](https://doi.org/10.21105/joss.01056)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01056">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01056/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01056/status.svg
   :target: https://doi.org/10.21105/joss.01056
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01056/status.svg)](https://doi.org/10.21105/joss.01056)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
