### ISSUE TITLE
[REVIEW]: Altair: Interactive Statistical Visualizations for Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1057]
**Submitting author:** @domoritz (<a href="http://orcid.org/0000-0002-3110-1053">ROBYN DOMINIK MORITZ</a>)
**Repository:** <a href="https://github.com/altair-viz/altair" target ="_blank">https://github.com/altair-viz/altair</a>
**Version:** v2.3.0
**Editor:** @jedbrown
**Reviewer:** @dnszafir, @terrytangyuan, @kellieotto
**Archive:** <a href="https://doi.org/10.5281/zenodo.2030098" target="_blank">10.5281/zenodo.2030098</a>

## Status

[![status](http://joss.theoj.org/papers/cd11f880b3f81bf5b5a225007212dc8b/status.svg)](http://joss.theoj.org/papers/cd11f880b3f81bf5b5a225007212dc8b)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/cd11f880b3f81bf5b5a225007212dc8b"><img src="http://joss.theoj.org/papers/cd11f880b3f81bf5b5a225007212dc8b/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/cd11f880b3f81bf5b5a225007212dc8b/status.svg)](http://joss.theoj.org/papers/cd11f880b3f81bf5b5a225007212dc8b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/altair-viz/altair" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dnszafir & @terrytangyuan & @kellieotto, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @jedbrown know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/altair-viz/altair">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2)?
- [x] **Authorship:** Has the submitting author (@domoritz) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/altair-viz/altair">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2)?
- [x] **Authorship:** Has the submitting author (@domoritz) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/altair-viz/altair">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2)?
- [x] **Authorship:** Has the submitting author (@domoritz) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jedbrown, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01057/joss.01057/10.21105.joss.01057.pdf)

**Comment by jedbrown** [comment]
@dnszafir @terrytangyuan @kellieotto :wave: Welcome! The comments from whedon above outline the review process. I'll be watching this thread if you have any questions. Thanks!

**Comment by terrytangyuan** [comment]
Great software and nice summarization of the background in the paper. A couple of questions and suggestions:

* You provided a section [here](https://github.com/altair-viz/altair#feedback-and-contribution) in `README.md` that mentions how to give feedback and contribute. Could you put it in a `CONTRIBUTING.md` file?
* Just want to double check with the other authors: has @domoritz (the submitting author) made significant contributions to this software? It doesn't look like so from the commit history [here](https://github.com/altair-viz/altair/commits?author=domoritz) since most of the commits are only related to this particular paper. However, @domoritz might have contributed significantly offline during the collaboration with the UW Interactive Data Lab (I noticed that he's part of the lab). Maybe @jakevdp and @ellisonbg can chime in and confirm?
* Does any of the references have DOI? If so, would you please add them?

**Comment by domoritz** [comment]
Thank you for the review @terrytangyuan!

I'm the co-author of Vega-Lite, created the schema that Altair is generated from, and maintain the Vega-Lite integration in Jupyter Notebooks and Jupyterlab. I created the submission because I did the last push of the paper in https://github.com/altair-viz/altair/pull/394.

I'll send PRs for the other two improvements.

**Comment by domoritz** [comment]
@whedon regenerate

**Comment by domoritz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01057/joss.01057/10.21105.joss.01057.pdf)

**Comment by dnszafir** [comment]
Agreed on acceptance, @jedbrown. Overall, Altair looks like a fantastic and well-documented resource. I ran into a minor challenge with the installation that may be worth addressing given the broad target audience. 

I followed the installation instructions as detailed in the repo (which were clear, simple, and well-articulated). Once installed, I ran into a few issues that turned out to be a stale version of Anaconda (specifically: https://github.com/conda-forge/pandas-feedstock/issues/51). It may be worth noting on the Troubleshooting guide to check for a sufficiently up-to-date version of Anaconda. 

After resolving this issue, the plot did not render, but the Troubleshooting guide was partially helpful in resolving the issue. Given the broad target audience, it is worth mentioning that iPython may need to be explicitly updated under "JupyterLab: Textual Chart Representation" as the documented 'Change Kernel' solution did not work in this case. Keep in mind my configuration was probably more out-of-date than the target user as I am not a regular notebook user, but a brief clarification may help others encountering these issues. 

As a future thought given the target audience: a growing number of people (both formal students and self-taught) are learning programming and data science through Python. Given the target goals of the package, it might be useful to call out examples that are especially helpful for learning and/or illustrating foundational data science concepts.

**Comment by domoritz** [comment]
Thank you for the feedback @dnszafir!

@jakevdp will appreciate the feedback on the getting started guide. The troubleshooting guide could suggest updating the Python installation as a possible step to resolve issues.

Altair is definitely designed with (novice) data scientists in mind. @jakevdp gave a tutorial at PyCon and all the materials are at https://github.com/altair-viz/altair-tutorial. There is also a case study that mirrors the Vega-Lite tutorial on exploring weather data at https://altair-viz.github.io/case_studies/exploring-weather.html. Is that something you had in mind?

**Comment by jedbrown** [comment]
Thanks, @kellieotto and @dnszafir!

@domoritz I have a couple minor (mostly bib) edits here: https://github.com/altair-viz/altair/pull/1195
Also, is it intended that the `notebooks/*.ipynb` work? They look unclean (was last executed out of order) and I see some errors. For example,
```python
import altair.vegalite.v2 as vl
vl.vegalite(...)
```
fails because `vl.vegalite` does not exist. Can you look at these?

**Comment by domoritz** [comment]
Good catch. I'm fixing the notebooks in https://github.com/altair-viz/altair/pull/1196. The property is called `VegaLite`.

**Comment by domoritz** [comment]
The notebooks aren't crucial and shouldn't affect the submission.

**Comment by domoritz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01057/joss.01057/10.21105.joss.01057.pdf)

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01057/joss.01057/10.21105.joss.01057.pdf)

**Comment by jedbrown** [comment]
Looks good to me now. @domoritz Go ahead and create an archive on Zenodo or similar.

**Comment by domoritz** [comment]
I uploaded the current version to Zenodo at https://zenodo.org/record/1489327

**Comment by jedbrown** [comment]
Sorry to not be more explicit, @domoritz. We normally ask for the Zenodo archive to be a tagged version of the software (the interface encourages that IIRC) and the author list of the archive should match the author list of the paper. Can you do that?

**Comment by domoritz** [comment]
Here is the new version: https://zenodo.org/record/1489372

**Comment by jedbrown** [comment]
@arfon This is basically ready to accept, but the archived version (v2.2.2) does not include the paper (it's the most recent release and there are no important changes since). My understanding is that we want a new version (v2.2.3 for example) to be tagged and archived. Can you confirm?

**Comment by domoritz** [comment]
@jakevdp Could you tag a new version?

**Comment by jedbrown** [comment]
@jakevdp Can you comment on this? Other papers I have edited archive a tagged version that contains the post-review repo/paper.

**Comment by domoritz** [comment]
2.3 is out.

**Comment by domoritz** [comment]
@jedbrown Here is the archived version of 2.3: https://zenodo.org/record/2030098.

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01057/joss.01057/10.21105.joss.01057.pdf)

**Comment by jedbrown** [comment]
Thanks! In double-checking, I noticed one more messed up citation (comma should be a semicolon). @arfon Is it possible to possible to include this trivial patch in the paper of record without requiring a new tag/archive?

```
diff --git i/paper/paper.md w/paper/paper.md
index 96dc1b4..bc99c65 100644
--- i/paper/paper.md
+++ w/paper/paper.md
@@ -70,7 +70,7 @@ JSON data, which is then rendered in a user-interface such as the Jupyter Notebo
 specification [@2016-reactive-vega-architecture], which is then parsed and executed using a reactive runtime that
 internally makes use of D3.js [@2011-d3]. 
 
-The declarative nature of the Vega-Lite visualization grammar [@2005-grammar, @2017-vega-lite], and its encoding in a
+The declarative nature of the Vega-Lite visualization grammar [@2005-grammar; @2017-vega-lite], and its encoding in a
 formal JSON schema, provide Altair with a number of benefits. First, much of the Altair Python code and tests are
 generated from the Vega-Lite JSON schema, ensuring strict conformance with the Vega-Lite specification. Second, the JSON
 data produced by Altair and consumed by Vega-Lite provides a natural serialization and file format for statistical
```

**Comment by arfon** [comment]
> Thanks! In double-checking, I noticed one more messed up citation (comma should be a semicolon). @arfon Is it possible to possible to include this trivial patch in the paper of record without requiring a new tag/archive?

Yes, feel free to just update `master` with the fix.

**Comment by jedbrown** [comment]
Thanks. @domoritz Can you apply that trivial fix in the repository?

**Comment by domoritz** [comment]
@jakevdp can you apply the patch?

**Comment by domoritz** [comment]
@jakevdp Can you merge https://github.com/altair-viz/altair/pull/1258?

**Comment by domoritz** [comment]
Merged.

@whedon generate pdf

**Comment by domoritz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01057/joss.01057/10.21105.joss.01057.pdf)

**Comment by dnszafir** [comment]
> Thank you for the feedback @dnszafir!
> 
> @jakevdp will appreciate the feedback on the getting started guide. The troubleshooting guide could suggest updating the Python installation as a possible step to resolve issues.
> 
> Altair is definitely designed with (novice) data scientists in mind. @jakevdp gave a tutorial at PyCon and all the materials are at https://github.com/altair-viz/altair-tutorial. There is also a case study that mirrors the Vega-Lite tutorial on exploring weather data at https://altair-viz.github.io/case_studies/exploring-weather.html. Is that something you had in mind?

Sorry for dropping the ball on this! Yes, this kind of thing seems quite relevant. I could imagine that coupling this kind of breakdown with a description of the statistical and analytical goals unveiled with each chart being super useful. Again, just a thought for future work given the target audience.

**Comment by jedbrown** [comment]
:tada:  Many thanks to @terrytangyuan, @kellieotto, and @dnszafir for your reviews. Over to you, @arfon.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/109

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/109, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/110
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01057](https://doi.org/10.21105/joss.01057)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@dnszafir, @terrytangyuan, @kellieotto - many thanks for your reviews here and to @jedbrown for editing this submission ✨ 

@domoritz @jakevdp - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01057/status.svg)](https://doi.org/10.21105/joss.01057)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01057">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01057/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01057/status.svg
   :target: https://doi.org/10.21105/joss.01057
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01057/status.svg)](https://doi.org/10.21105/joss.01057)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
