### ISSUE TITLE
[REVIEW]: Read, Tidy, and Display Data from Microtiter Plates in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#106]
**Submitting author:** @seaaan (<a href="http://orcid.org/0000-0002-9409-9405">Sean Hughes</a>)
**Repository:** <a href="https://github.com/ropenscilabs/plater" target ="_blank">https://github.com/ropenscilabs/plater</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** @arfon
**Archive:** <a href="https://dx.doi.org/10.5281/zenodo.163543" target="_blank">https://dx.doi.org/10.5281/zenodo.163543</a>

## Status

[![status](http://joss.theoj.org/papers/f9a1ce601307ed0cc536ac48e6be3ce5/status.svg)](http://joss.theoj.org/papers/f9a1ce601307ed0cc536ac48e6be3ce5)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f9a1ce601307ed0cc536ac48e6be3ce5"><img src="http://joss.theoj.org/papers/f9a1ce601307ed0cc536ac48e6be3ce5/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f9a1ce601307ed0cc536ac48e6be3ce5/status.svg)](http://joss.theoj.org/papers/f9a1ce601307ed0cc536ac48e6be3ce5)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ropenscilabs/plater" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ropenscilabs/plater">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@seaaan) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
rOpenSci review here: ropensci/onboarding#60

**Comment by arfon** [comment]
Thanks for your submission to JOSS @seaaan. Your paper is now accepted into JOSS, the DOI is http://dx.doi.org/10.21105/joss.00106 🎉 🚀 💥

**Comment by seaaan** [comment]
Wow, that was so easy! Thank you so much for having such a smooth process.
