### ISSUE TITLE
[PRE REVIEW]: Artery.FE: An implementation of the 1D blood flow equations in FEniCS

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1060]
**Submitting author:** @akdiem (<a href="http://orcid.org/0000-0003-1719-1942">Alexandra Diem</a>)
**Repository:** <a href="https://github.com/KVSlab/bloodflow" target ="_blank">https://github.com/KVSlab/bloodflow</a>
**Version:** v1.0
**Editor:** @trallard
**Reviewers:** @dlagrava, @jhill1

**Author instructions**

Thanks for submitting your paper to JOSS @akdiem. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@akdiem if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @trallard it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1060 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8e8528b72684/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @trallard - the submitting author suggested you as the handling editor.

**Comment by trallard** [comment]
Hi @akdiem I will be the editor for your submission 👋 
It seems there are some problems with the paper, you might want to check the `yaml` header and try and regenerate the paper.

Also, have you got any potential reviewers in mind? If not you can check our list [of registered reviewers](https://bit.ly/joss-reviewers)

**Comment by akdiem** [comment]
Hi @trallard Thank you for being the editor for my submission and apologies for the delayed response (I was away). I have fixed the issue according to the error message and pushed the changes to my repository. How do I regenerate the paper?

I have checked the list of reviewers and could suggest @abhishekbajpayee and @dlagrava

**Comment by akdiem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1060 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    102      0 --:--:-- --:--:-- --:--:--   103
Error reading bibliography ./paper.bib (line 30, column 16):
unexpected "}"
expecting white space or ","
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by akdiem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01060/joss.01060/10.21105.joss.01060.pdf)

**Comment by trallard** [comment]
Hello 👋  @abhishekbajpayee and @dlagrava would you be interested in reviewing this submission?

**Comment by dlagrava** [comment]
Hello @trallard, sorry for the late response. I could try to do the review, but lately I have been busier than normal, so it may take longer. If that is OK with you then I will start.

**Comment by trallard** [comment]
Hi @dlagrava no worries that would be perfect, we ideally want reviews to be conducted within a couple of weeks but taking longer than that should not be an issue, we can always accommodate and work around reviewer's availability. Does this sound reasonable?

**Comment by dlagrava** [comment]
Hello @trallard that sounds great. Let's move on!

**Comment by trallard** [comment]
@whedon assign @dlagrava as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dlagrava

**Comment by trallard** [comment]
@akdiem  let's ping a few fitting reviewers, with Python and computational fluid dynamics expertise. We already have @dlagrava acceptance to review but ideally, we'd want one extra reviewer.


Dear reviewers,

@kyleniemeyer  Kyle, are you able to and interested in taking on this review?
@abhishekbajpayee Abishek, are you able to and interested in taking on this review?
@ctdegroot Christopher, are you able to and interested in taking on this review?

---

**Title:** Artery.FE: An implementation of the 1D blood flow equations in FEniCS
**Summary:** This package implements the 1D blood flow equations using the finite element framework FEniCS. The package provides tools for modelling blood flow through a network of arteries by solving a 1D approximation of the cross-sectional area and flow rate of each artery.
**Topic:** Computational Fluid Dynamics
**Article Proof:** [https://github.com/openjournals/joss-papers/blob/joss.01060/joss.01060/10.21105.joss.01060.pdf](https://github.com/openjournals/joss-papers/blob/joss.01060/joss.01060/10.21105.joss.01060.pdf)
Submitting author: @akdiem 
**Repository:** [https://github.com/KVSlab/bloodflow](https://github.com/KVSlab/bloodflow)

**Comment by ctdegroot** [comment]
@trallard I am interested, but I have two other JOSS reviews on the go right now. I am willing to do it, but with the understanding that it might take me a few weeks to start my review.

**Comment by trallard** [comment]
Hi @ctdegroot, thanks a lot for offering, but given the fact that you have two simultaneous reviews at the moment I might proceed to review with @dlagrava. 

We very much appreciate your time and contribution to JOSS and we would certainly not have you burn out 😄

**Comment by trallard** [comment]
@whedon add @jhill1as reviewer

**Comment by trallard** [comment]
@whedon add @jhill1 as reviewer

**Comment by whedon** [comment]
OK, @jhill1 is now a reviewer

**Comment by trallard** [comment]
@dlagrava @jhill1 @akdiem  this is now ready to move to the review process so I will be closing this issue now

**Comment by trallard** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1107. Feel free to close this issue now!
