### ISSUE TITLE
[PRE REVIEW]: ssdtools: An R package to fit Species Sensitivity Distributions (SSDs)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1061]
**Submitting author:** @joethorley (<a href="http://orcid.org/0000-0002-7683-4592">Joseph Thorley</a>)
**Repository:** <a href="https://github.com/bcgov/ssdtools" target ="_blank">https://github.com/bcgov/ssdtools</a>
**Version:** v0.0.3
**Editor:** @arfon
**Reviewers:** @ibarraespinosa, @nanhung

**Author instructions**

Thanks for submitting your paper to JOSS @joethorley. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@joethorley if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01061/joss.01061/10.21105.joss.01061.pdf)

**Comment by nanhung** [comment]
Looks great! I can review this paper.

**Comment by ibarraespinosa** [comment]
Hi, thanks for suggesting me. Interesting work. If your paper passes to the review stage, I would review it.

**Comment by joethorley** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@ibarraespinosa @nanhung - many thanks for agreeing to review this submission! I'll go ahead now and set you up as reviewers and start the review process.

**Comment by arfon** [comment]
@whedon add @ibarraespinosa as reviewer

**Comment by whedon** [comment]
OK, @ibarraespinosa is now a reviewer

**Comment by arfon** [comment]
@whedon add @nanhung as reviewer

**Comment by whedon** [comment]
OK, @nanhung is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1082. Feel free to close this issue now!

**Comment by arfon** [comment]
@ibarraespinosa, @nanhung, @joethorley - please head over to #1082 for the main review thread.

**Comment by nanhung** [comment]
Overall, the package and paper look great. Just a few couples of questions and suggestions:

- For the title, I suggest removing the abbreviation SSDs. 
- Does Carl Schwarz make any significant contributions to this paper or software? 
- I find that there're only `ssdfit_dist` and `ssdfit_dists` rather than `ssdfit` in your package. Why not combine these two functions to one and named it ssdfit?
- I try to use `ggplot` with `geom_xribbon` and `geom_hcintercept` that you mentioned in summary. However, I don't know how to use `geom_xribbon`. Perhaps you can provide an example in the reference manual.     
- Is it possible to use lower case "g" for `ggplot2` in reference?
- Does any of the references have doi? If so, please provide them?
- I can only find one reference in the reference manual. Is there some reference that you can add?
