### ISSUE TITLE
[PRE REVIEW]: idvf: Iterative Inversion of Deformation Vector Field with Adaptive Bi-residual Feedback Control

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1062]
**Submitting author:** @ailiop (<a href="http://orcid.org/0000-0002-1959-9792">Alexandros-Stavros Iliopoulos</a>)
**Repository:** <a href="https://github.com/ailiop/idvf" target ="_blank">https://github.com/ailiop/idvf</a>
**Version:** v1.0.0
**Editor:** @arokem
**Reviewers:** @Kevin-Mattheus-Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @ailiop. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ailiop if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
👋 @arokem - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01062/joss.01062/10.21105.joss.01062.pdf)

**Comment by ailiop** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by ailiop** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01062/joss.01062/10.21105.joss.01062.pdf)

**Comment by ailiop** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01062/joss.01062/10.21105.joss.01062.pdf)

**Comment by arokem** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by arokem** [comment]
@ailiop : any ideas for potential reviewers?

**Comment by ailiop** [comment]
Hi @arokem. I have one in mind but do not know his GitHub handle. I have asked him via e-mail and will report here once I hear back.
I do not suppose it is an issue to suggest a reviewer not on the JOSS list, right?

**Comment by ailiop** [comment]
@arokem : I have not heard back from the person I had in mind yet. I went over the list of reviewers and I think @ThomasA or @Kevin-Mattheus-Moerman would be suitable reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
Yep I think can help review this. Sounds interesting.

**Comment by ailiop** [comment]
@arokem : I have pushed a new release (v1.0.1) to fix a couple of bugs I just found. Is it possible to update the review issue to target v1.0.1 instead of v1.0.0?

**Comment by arokem** [comment]
@whedon assign @Kevin-Mattheus-Moerman as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @Kevin-Mattheus-Moerman

**Comment by arokem** [comment]
Thanks @Kevin-Mattheus-Moerman! 👏 

@ailiop: I wouldn't worry about the version number. The reviewer will look at the most recent version of the software, and we'll probably want you to make another release at the end of the review to incorporate any changes due to the review anyway.

**Comment by ailiop** [comment]
@arokem : Great, that makes sense. Thank you.

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1076. Feel free to close this issue now!

**Comment by arokem** [comment]
I am closing this issue. @Kevin-Mattheus-Moerman : please head over to #1076 for the review. Feel free to tag me on issues that you raise on the repo, so that I can follow along.
