### ISSUE TITLE
[REVIEW]: 3D ultrasound file reading and coordinate transformations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1063]
**Submitting author:** @plooney (<a href="http://orcid.org/0000-0002-0764-5413">Padraig Looney</a>)
**Repository:** <a href="https://github.com/plooney/kretz" target ="_blank">https://github.com/plooney/kretz</a>
**Version:** v1.1
**Editor:** @cMadan
**Reviewer:** @thewtex
**Archive:** <a href="https://doi.org/10.5281/zenodo.2537876" target="_blank">10.5281/zenodo.2537876</a>

## Status

[![status](http://joss.theoj.org/papers/7a2fedfa7961977f015743ad287542b6/status.svg)](http://joss.theoj.org/papers/7a2fedfa7961977f015743ad287542b6)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/7a2fedfa7961977f015743ad287542b6"><img src="http://joss.theoj.org/papers/7a2fedfa7961977f015743ad287542b6/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/7a2fedfa7961977f015743ad287542b6/status.svg)](http://joss.theoj.org/papers/7a2fedfa7961977f015743ad287542b6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/plooney/kretz" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@thewtex, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @cMadan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/plooney/kretz">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.1
- [x] **Authorship:** Has the submitting author (@plooney) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @thewtex it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01063/joss.01063/10.21105.joss.01063.pdf)

**Comment by thewtex** [comment]
>  License: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?

https://github.com/plooney/kretz/issues/1 created to clarify / standardize the license file.

**Comment by thewtex** [comment]
> Version: Does the release version given match the GitHub release (0.01)?

https://github.com/plooney/kretz/issues/2 created to create a GitHub release. It may be desirable to address other review items before creating this release.

**Comment by thewtex** [comment]
>  Installation: Does installation proceed as outlined in the documentation?

Generally, yes, but a few minor issues identified:

- https://github.com/plooney/kretz/issues/4
- https://github.com/plooney/kretz/issues/5

**Comment by thewtex** [comment]
> Functionality: Have the functional claims of the software been confirmed?

https://github.com/plooney/kretz/issues/8 created to enable use as a library.

**Comment by thewtex** [comment]
>  Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

There is Doxygen documentation and the naming of classes and methods are information.

A few items to improve with the command line programs:

- https://github.com/plooney/kretz/issues/6
- https://github.com/plooney/kretz/issues/7

**Comment by thewtex** [comment]
>  References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

- Minor correction required: https://github.com/plooney/kretz/issues/10

**Comment by thewtex** [comment]
@cMadan @plooney review complete.

I apologize again for the tardiness of the review.

@plooney the code looks outstanding, and this is a valuable contribution for ultrasound research. Thank you for sharing this work.

**Comment by cMadan** [comment]
@thewtex, thank you for the thorough review!

@plooney, please let us know after you have have revised the project based on the reviewer feedback.

**Comment by plooney** [comment]
@cMadan 

Thanks for the comments @thewtex. I have tried to address all the points, I struggled to get the two of the issues resolved fully; ITK Module and CI.

**Comment by thewtex** [comment]
@plooney looking good.

Please review and fix up this PR as required:

  https://github.com/plooney/kretz/pulls

which should how to format as an ITK Module to use as a library and adds CI configuration.

One other item is to tag the repository.

**Comment by thewtex** [comment]
@cMadan I believe all review items are now complete!

**Comment by cMadan** [comment]
@thewtex, great, thank you for all your work in reviewing this!

@plooney, I will do a final proof to make sure everything looks good and comment again shortly.

**Comment by plooney** [comment]
@cMadan I have deposited it on Zenodo. The DOI is 

DOI: 10.5281/zenodo.2537876

**Comment by plooney** [comment]
I changed the tag to v1.1 to include the latest commit with all the responses to the review.

**Comment by cMadan** [comment]
@whedon set v1.1 as version

**Comment by whedon** [comment]
OK. v1.1 is the version.

**Comment by cMadan** [comment]
@whedon set 10.5281/zenodo.2537876 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2537876" target="_blank">10.5281/zenodo.2537876</a> is the archive.

**Comment by cMadan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/429

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/429, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by cMadan** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
I'm sorry @cMadan, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by cMadan** [comment]
@arfon @danielskatz, we're all set to accept here!

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/430
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01063](https://doi.org/10.21105/joss.01063)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@thewtex - many thanks for your review here and to @cMadan for editing this submission ✨ 

@plooney - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01063/status.svg)](https://doi.org/10.21105/joss.01063)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01063">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01063/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01063/status.svg
   :target: https://doi.org/10.21105/joss.01063
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01063/status.svg)](https://doi.org/10.21105/joss.01063)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
