### ISSUE TITLE
[REVIEW]: scarplet: A Python package for topographic template matching and diffusion dating

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1066]
**Submitting author:** @rmsare (<a href="http://orcid.org/0000-0003-3711-6771">Robert Sare</a>)
**Repository:** <a href="https://github.com/rmsare/scarplet" target ="_blank">https://github.com/rmsare/scarplet</a>
**Version:** 0.1.0
**Editor:** @kthyng
**Reviewer:** @fclubb, @mcflugen
**Archive:** <a href="https://doi.org/10.5281/zenodo.1492786" target="_blank">10.5281/zenodo.1492786</a>

## Status

[![status](http://joss.theoj.org/papers/2a23987d6f629b4be281de912f66db69/status.svg)](http://joss.theoj.org/papers/2a23987d6f629b4be281de912f66db69)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/2a23987d6f629b4be281de912f66db69"><img src="http://joss.theoj.org/papers/2a23987d6f629b4be281de912f66db69/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/2a23987d6f629b4be281de912f66db69/status.svg)](http://joss.theoj.org/papers/2a23987d6f629b4be281de912f66db69)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/rmsare/scarplet" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@fclubb & @mcflugen, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @kthyng know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rmsare/scarplet">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.0)?
- [x] **Authorship:** Has the submitting author (@rmsare) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rmsare/scarplet">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.0)?
- [x] **Authorship:** Has the submitting author (@rmsare) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @fclubb, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01066/joss.01066/10.21105.joss.01066.pdf)

**Comment by rmsare** [comment]
@kthyng and reviewers - thanks for this! I am tagging co-author @gehilley in case he would like to follow the review.

**Comment by mcflugen** [comment]
@rmsare Nice work 👍I think this is great.

I submitted a couple issues to your repository that address most of the items on our checklist. There are only a couple of other things.

Things to do:
* [ ] Fix installation issues (rmsare/scarplet#59)
* [ ] Fix examples (rmsare/scarplet#60)
* [ ] Add Statement of Need to the documentation
* [ ] Add DOIs to the references in `paper.md`

I think that's it for now.

**Comment by rmsare** [comment]
@mcflugen Thank you for the thorough review and your work on the conda recipe! I will dig into this and hope to address your comments and implement changes by Monday.

**Comment by fclubb** [comment]
Hi @rmsare, thanks for submitting this, the package looks really useful. Here are some notes/comments, which I think are mostly similar those that @mcflugen mentioned.

### Installation and functionality
- Installation worked for me with `pip` but I couldn't get the code to run due to issues with gdal (rmsare/scarplet#62).  I think it would be better to have an environment file so that the gdal install is already taken care of, or do a conda package as was already suggested.
- Examples: it wasn't immediately clear to me that the example data was included within the GitHub repository, as I had just done a `pip` install. I have added a comment to the issue that @mcflugen opened.
- The data for the channel network example is not provided within the GitHub repo so I couldn't test this example. Would need to test this to check all of the functionality of the software.

### Software paper
- I think the software paper needs to include DOIs with the references.

### Documentation
- Readme file could contain a clearer statement of need.

**Comment by rmsare** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01066/joss.01066/10.21105.joss.01066.pdf)

**Comment by rmsare** [comment]
Thanks for your comments @fclubb and @mcflugen.

The example issues have been addressed in some of the PRs above. I've also clarified the statement of need in the README and added DOIs to the paper.

A conda recipe has been submitted that should take care of install problems.

It seems like the best course of action is cutting a new version after your reviews are completed, and I will release, re-package, and increment the paper version then.

**Comment by rmsare** [comment]
@kthyng Thanks for the follow up.

I believe I have addressed the points raised so far by both reviewers. The following changes have been made:

- [x] Add DOIs to paper
- [x] Add statement of need to README
- [x] Refactor example data access
- [x] Clarify how to run examples and access sample data in both README and docs
- [x] Change call to a GDAL binary based on @mcflugen's code review
- [ ] Submit package to conda-forge (review pending)

The remaining issues should be solved once the conda package is accepted. At that point I think @fclubb will be able to install without GDAL problems and verify functionality.

Unfortunately that package review is blocking for now. Please let me know if there's anything I can do in the meantime.

**Comment by rmsare** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by fclubb** [comment]
Hi @rmsare, I have checked the changes that you made and I am happy with submission - I have checked off all the points in my checklist. Nice work!

**Comment by mcflugen** [comment]
@rmsare Yep, looks good to me too! 🎉

**Comment by rmsare** [comment]
Thanks to you both for your help and reviews. This submission was a good learning experience for me.

**Comment by rmsare** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01066/joss.01066/10.21105.joss.01066.pdf)

**Comment by rmsare** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01066/joss.01066/10.21105.joss.01066.pdf)

**Comment by arfon** [comment]
> I'm not sure what the problem is here, as the author lists are all in the same style in paper.bib and use "and" to separate authors. @kthyng (or @arfon), is this a known issue with whedon?

I think you need to separate authors with commas from memory.

**Comment by arfon** [comment]
Feel free to try tweaking the bibtex and compiling here.

**Comment by rmsare** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01066/joss.01066/10.21105.joss.01066.pdf)

**Comment by rmsare** [comment]
@whendon generate pdf

**Comment by rmsare** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01066/joss.01066/10.21105.joss.01066.pdf)

**Comment by rmsare** [comment]
I'm happy with the formatting as is. 

This comes up in other JOSS papers, too, like [10.21105/joss.00979](http://joss.theoj.org/papers/10.21105/joss.00979).

**Comment by arfon** [comment]
> The Zenodo archive of the latest release is 10.5281/zenodo.1492786

@kthyng - are we ready to accept this submission?

**Comment by kthyng** [comment]
One more thing:
@rmsare it looks like you have no co-author on your zenodo archive, but you have one on this JOSS submission. Presumably they should match, in which case can you edit the metadata for the zenodo entry?

**Comment by kthyng** [comment]
Great! We're ready to move forward then @arfon.

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.1492786 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1492786" target="_blank">10.5281/zenodo.1492786</a> is the archive.

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/85
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01066](https://doi.org/10.21105/joss.01066)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@fclubb, @mcflugen - many thanks for your reviews here and to @kthyng for editing this submission ✨ 

@rmsare - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01066/status.svg)](https://doi.org/10.21105/joss.01066)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01066">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01066/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01066/status.svg
   :target: https://doi.org/10.21105/joss.01066
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01066/status.svg)](https://doi.org/10.21105/joss.01066)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
