### ISSUE TITLE
[PRE REVIEW]: hotsub - Command line tool to run batch jobs with ETL framework concurrently on cloud services

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1067]
**Submitting author:** @otiai10 (<a href="http://orcid.org/0000-0001-6636-856X">Hiromu Ochiai</a>)
**Repository:** <a href="https://github.com/otiai10/hotsub" target ="_blank">https://github.com/otiai10/hotsub</a>
**Version:** v0.10.0
**Editor:** @brainstorm
**Reviewers:** @reisingerf

**Author instructions**

Thanks for submitting your paper to JOSS @otiai10. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@otiai10 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @brainstorm it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1067 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    247      0 --:--:-- --:--:-- --:--:--   250
Error reading bibliography ./paper.bib (line 2, column 13):
unexpected "B"
expecting space or ","
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
👋 @brainstorm - the submitting author suggested you as the handling editor.

**Comment by brainstorm** [comment]
Fantastic! 👍 

May I suggest a suitable reviewer? @reisingerf, would you like to review this tool for JOSS?

**Comment by brainstorm** [comment]
@whedon assign @reisingerf as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @reisingerf

**Comment by brainstorm** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1069. Feel free to close this issue now!
