### ISSUE TITLE
[PRE REVIEW]: Shenfun: High Performance Computing Platform for the Spectral Galerkin method

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1068]
**Submitting author:** @mikaem (<a href="http://orcid.org/0000-0002-3293-7573">Mikael Mortensen</a>)
**Repository:** <a href="https://github.com/spectralDNS/shenfun" target ="_blank">https://github.com/spectralDNS/shenfun</a>
**Version:** 1.2.0
**Editor:** @katyhuff
**Reviewers:** @lucydot, @lindsayad

**Author instructions**

Thanks for submitting your paper to JOSS @mikaem. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mikaem if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@katyhuff - would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01068/joss.01068/10.21105.joss.01068.pdf)

**Comment by mikaem** [comment]
Great:-) I see a lot of people on the list of reviewers with topic areas high performance computing, Python and MPI. Shouldn't be too hard to find reviewers. Want me to pick from the top of the list? I have no one in particular in mind.

**Comment by katyhuff** [comment]
@mikaem, your suggestions would be great. 

Meanwhile -- perhaps @lucydot or @lindsayad would be interested. @lucydot, @lindsayad, would either of you be willing to be reviewers for this JOSS submission?

**Comment by lucydot** [comment]
@katyhuff @mikaem I’d be very happy to review.

**Comment by lindsayad** [comment]
I can review if another reviewer is still needed

**Comment by katyhuff** [comment]
Two will be perfect! Thanks @lucydot @lindsayad !

**Comment by katyhuff** [comment]
@whedon assign @lucydot as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @lucydot

**Comment by katyhuff** [comment]
@whedon add @lindsayad as reviewer

**Comment by whedon** [comment]
OK, @lindsayad is now a reviewer

**Comment by katyhuff** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1071. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Ok! @mikaem , @lucydot , @lindsayad : We'll close this issue and continue the review over in #1071.
