### ISSUE TITLE
[REVIEW]: hotsub - Command line tool to run batch jobs with ETL framework concurrently on cloud services

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1069]
**Submitting author:** @otiai10 (<a href="http://orcid.org/0000-0001-6636-856X">Hiromu Ochiai</a>)
**Repository:** <a href="https://github.com/otiai10/hotsub" target ="_blank">https://github.com/otiai10/hotsub</a>
**Version:** v0.10.0
**Editor:** @brainstorm
**Reviewer:** @reisingerf
**Archive:** <a href="https://doi.org/10.5281/zenodo.1482983" target="_blank">10.5281/zenodo.1482983</a>

## Status

[![status](http://joss.theoj.org/papers/f1e4470e4831caa4252427cec8c009a8/status.svg)](http://joss.theoj.org/papers/f1e4470e4831caa4252427cec8c009a8)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f1e4470e4831caa4252427cec8c009a8"><img src="http://joss.theoj.org/papers/f1e4470e4831caa4252427cec8c009a8/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f1e4470e4831caa4252427cec8c009a8/status.svg)](http://joss.theoj.org/papers/f1e4470e4831caa4252427cec8c009a8)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/otiai10/hotsub" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@reisingerf, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @brainstorm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/otiai10/hotsub">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.10.0)?
- [x] **Authorship:** Has the submitting author (@otiai10) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @reisingerf it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1069 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    209      0 --:--:-- --:--:-- --:--:--   207
Error reading bibliography ./paper.bib (line 2, column 13):
unexpected "B"
expecting space or ","
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by brainstorm** [comment]
@otiai10, could you please correct your `paper.bib`? See error above. Also, in the statement of need, I think that https://github.com/base2genomics/batchit should be pointed out perhaps?

**Comment by otiai10** [comment]
@brainstorm 
Thank you. I will

- [ ] Fix `bib` format
- [ ] Update `README.md` and `paper.md` to specify the statement of need more clearly
- [ ] Write available functionalities on `README.md` more clearly
- [ ] Add `CONTRIBUTING.md`

**Comment by reisingerf** [comment]
@otiai10 could you please also put the output of `hotsub run --help` in the `README.md`? 
It shows a lot of options and default values that are mentioned nowhere in the documentation.

**Comment by otiai10** [comment]
Thank you very much for taking time for review. I've patched some updates (mentioned above) to `bib` and `md`.
https://github.com/otiai10/hotsub

**Comment by otiai10** [comment]
@brainstorm Thanks for everything.

https://zenodo.org/record/1482983#.W-j3m3ozbdQ
Does it work?

**Comment by brainstorm** [comment]
@whedon set 10.5281/zenodo.1482983 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1482983" target="_blank">10.5281/zenodo.1482983</a> is the archive.

**Comment by brainstorm** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/63

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/63, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by brainstorm** [comment]
@reisingerf @otiai10 Thanks much everyone!

@arfon LGTM, shall I deposit?

**Comment by arfon** [comment]
@brainstorm - before we accept this, can we update the references to be actual citations in the text?

@otiai10 - Could you move the references you currently have in the `paper.md` file into a `paper.bib` file and cite them directly please? (You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html))

Also, it looks like we need to add a date to the `paper.md` file.

**Comment by otiai10** [comment]
Thank you,

- I think all the references on `paper.md` are [listed on `paper.md`](https://github.com/otiai10/hotsub/tree/master/paper). Could you please specify what I should actually do more than this?
- Should I add `date` to the `paper.md` as the date it put on [`Zenodo`](https://zenodo.org/record/1482983#.W-myZXozbOR)? : November 12, 2018

**Comment by arfon** [comment]
> - I think all the references on paper.md are listed on paper.md. Could you please specify what I should actually do more than this?

Yes, you need to remove all of the content underneath the [references section here](https://github.com/otiai10/hotsub/blob/master/paper/paper.md#references) and instead, cite the entries in your `paper.bib` inline in your paper body. When we compile the paper, the references will be compiled automatically.

> -  Should I add date to the paper.md as the date it put on Zenodo? : November 12, 2018

That should be fine yes.

**Comment by brainstorm** [comment]
Sorry about that @arfon, will look more closely next time before pre-accepting :-S

**Comment by arfon** [comment]
OK, final step now @otiai10 is to actually cite the references in your paper text. For example, [this citation](https://github.com/otiai10/hotsub/blob/master/paper/paper.bib#L9-L14) for Azure needs to be something like:

```
Azure Batch by Microsoft [@AzureBatch] ...
```

This `[@AzureBatch]` syntax is the bibtex entry key and will be used by Pandoc to compile the references section. This section is now currently blank as you're not actually citing any of the bibtex entries in the body of your paper.

**Comment by otiai10** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01069/joss.01069/10.21105.joss.01069.pdf)

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/64

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/64, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/65
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01069](https://doi.org/10.21105/joss.01069)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@reisingerf - many thanks for your review here and to @brainstorm for editing this submission.

@otiai10 - your paper is now accepted into JOSS! :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01069/status.svg)](https://doi.org/10.21105/joss.01069)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01069">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01069/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01069/status.svg
   :target: https://doi.org/10.21105/joss.01069
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01069/status.svg)](https://doi.org/10.21105/joss.01069)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by otiai10** [comment]
-------

@arfon 
CC @friend1ws

Thank you for everything.

I'd like to ask if it's possible to add **co-authors** and **acknowledgements**, and update the paper.

[This change](https://github.com/otiai10/hotsub/pull/119/files) is already merged to master and ready to generate pdf.

Thank you.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
> I'd like to ask if it's possible to add co-authors and acknowledgements, and update the paper.

Sure thing. The paper is now updated.

**Comment by otiai10** [comment]
Thank you very much! 😄
