### ISSUE TITLE
[PRE REVIEW]: A MATLAB toolbox to detect and analyze marine heatwaves

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1074]
**Submitting author:** @ZijieZhaoMMHW (<a href="http://orcid.org/0000-0003-3403-878X">Zijie Zhao</a>)
**Repository:** <a href="https://github.com/ZijieZhaoMMHW/m_mhw1.0" target ="_blank">https://github.com/ZijieZhaoMMHW/m_mhw1.0</a>
**Version:** v1.0
**Editor:** @kthyng
**Reviewers:** @mvdh7

**Author instructions**

Thanks for submitting your paper to JOSS @ZijieZhaoMMHW. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ZijieZhaoMMHW if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01074/joss.01074/10.21105.joss.01074.pdf)

**Comment by ZijieZhaoMMHW** [comment]
Hi,

I suggest @fgnievinski to be the reviewer.

**Comment by ZijieZhaoMMHW** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by ZijieZhaoMMHW** [comment]
Hi,

I suggest @fgnievinski to be the reviewer.

**Comment by ZijieZhaoMMHW** [comment]
Potential reviewers are @fgnievinski  and @JesperDramsch if they are ok.

**Comment by ZijieZhaoMMHW** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01074/joss.01074/10.21105.joss.01074.pdf)

**Comment by ZijieZhaoMMHW** [comment]
@arfon  Sorry to bother. Just notice that it seems that this issue has not been assigned to anyone.... Should I do anything?

**Comment by arfon** [comment]
Hi @ZijieZhaoMMHW - I'm currently waiting on an editor to pick up this submission. I'm hoping that one of our MATLAB specialists will be able to handle this submission but they're currently handling a lot of submissions.

Basically, it may take another couple of weeks before this submission will move forward.

**Comment by JesperDramsch** [comment]
Hey folks, I'm not sure I'm up for reviewing this one. I'd like to move away from Matlab as I don't even have the current version installed anymore, or know how package management works. Any way I can adjust my record reflecting this?

**Comment by arfon** [comment]
No problem @JesperDramsch - I've removed Matlab from your listed languages here: https://bit.ly/joss-reviewers

**Comment by kthyng** [comment]
Hi @arfon! I don't use Matlab anymore, but I do oceanography. I can edit this if you want.

**Comment by arfon** [comment]
> Hi @arfon! I don't use Matlab anymore, but I do oceanography. I can edit this if you want.

✨ that would be great. Thanks @kthyng!

**Comment by arfon** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
Hi @fgnievinski and @mvdh7: are you willing and able to review this JOSS submission? You can read more about the process [here](https://joss.readthedocs.io/en/latest/review_criteria.html). We normally ask for reviews in about 2 weeks but given there is a holiday in the US next week, I would like reviews in the next 3 weeks.

**Comment by ZijieZhaoMMHW** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01074/joss.01074/10.21105.joss.01074.pdf)

**Comment by ZijieZhaoMMHW** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01074/joss.01074/10.21105.joss.01074.pdf)

**Comment by kthyng** [comment]
Hey @chadagreene! Are you able and willing to review this submission in this next two weeks? I think you'd be a good fit. You can get more info on reviewing [here](https://joss.readthedocs.io/en/latest/review_criteria.html).

**Comment by mvdh7** [comment]
Hey, happy to give it a go. Sorry, I haven't had any notifications when you @ me, so I've only just seen this now (thanks to Twitter).

**Comment by chadagreene** [comment]
The toolbox looks interesting and nicely documented, but I'm afraid I'm in over my head this month with deadlines, so I must decline. Feel free to ask again in the future.

**Comment by kthyng** [comment]
Ok thanks everyone for their responses, let's go ahead with @mvdh7 as reviewer. I'll set things up to move forward!

**Comment by kthyng** [comment]
@whedon assign @mvdh7 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mvdh7

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1124. Feel free to close this issue now!
