### ISSUE TITLE
[REVIEW]: Yellowbrick: Visualizing the Scikit-Learn Model Selection Process

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1075]
**Submitting author:** @bbengfort (<a href="http://orcid.org/0000-0003-0660-7682">Benjamin Bengfort</a>)
**Repository:** <a href="https://github.com/DistrictDataLabs/yellowbrick" target ="_blank">https://github.com/DistrictDataLabs/yellowbrick</a>
**Version:** v0.8
**Editor:** @arfon
**Reviewer:** @mnarayan
**Archive:** <a href="https://doi.org/10.5281/zenodo.1206239" target="_blank">10.5281/zenodo.1206239</a>

## Status

[![status](http://joss.theoj.org/papers/fa85e63caee1eead35a990c1755b55b6/status.svg)](http://joss.theoj.org/papers/fa85e63caee1eead35a990c1755b55b6)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/fa85e63caee1eead35a990c1755b55b6"><img src="http://joss.theoj.org/papers/fa85e63caee1eead35a990c1755b55b6/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/fa85e63caee1eead35a990c1755b55b6/status.svg)](http://joss.theoj.org/papers/fa85e63caee1eead35a990c1755b55b6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/DistrictDataLabs/yellowbrick" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mnarayan, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/DistrictDataLabs/yellowbrick">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.8)?
- [x] **Authorship:** Has the submitting author (@bbengfort) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mnarayan it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01075/joss.01075/10.21105.joss.01075.pdf)

**Comment by arfon** [comment]
@mnarayan - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know!

**Comment by arfon** [comment]
:wave: @mnarayan - please try and get to this review soon.

**Comment by arfon** [comment]
_bump_ please review this submission soon.

**Comment by arfon** [comment]
:wave: @mnarayan - it looks like you're part-way through your review. Do you think you might be able to complete it in the next week?

**Comment by arfon** [comment]
:wave: @mnarayan - please leave an update on this review issue when you can.

**Comment by arfon** [comment]
I've just emailed @mnarayan to ask them to complete their review in the next week or two.

**Comment by mnarayan** [comment]
Sorry for the delay, will finish my comments this week.

**Comment by arfon** [comment]
:wave: @mnarayan - did you manage to complete your review?

**Comment by arfon** [comment]
:wave: @mnarayan - please update us on your progress when you get a chance.

**Comment by mnarayan** [comment]
I am finished with my review.  I can't find anything more that needs to be done for publication. This package is beautiful.

**Comment by arfon** [comment]
> I am finished with my review. I can't find anything more that needs to be done for publication. This package is beautiful.

Great, thanks @mnarayan.

@bbengfort - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01075/joss.01075/10.21105.joss.01075.pdf)

**Comment by arfon** [comment]
One quick question @bbengfort - I notice there are a lot of contributors to this package, and your paper mentions a number of core contributors yet I only see two of you listed as authors on the JOSS paper. Is this correct?

**Comment by bbengfort** [comment]
@mnarayan thank you so much for the review and the compliment! 

@arfon we're really excited about this publication! The DOI of the official Yellowbrick archive (with all versions) is [10.5281/zenodo.1488364](https://zenodo.org/record/1488364). As for your question about the authors - @rebeccabilbro and I are the primary authors of Yellowbrick and the maintainers. After discussing with our other core contributors we feel that the easiest and most equitable thing for everyone is if it's just the two of us listed as authors on the paper and our core contributors are mentioned in the acknowledgements. We are proud of the number of contributors we've had to the package, and on every release we list everyone who contributed as recognition. 

Thanks again for all your hard work on JOSS!

**Comment by rebeccabilbro** [comment]
Thank you so much @mnarayan for your review &mdash; we are excited to get the word out about visual diagnostics for model selection via JOSS!! Sincere thanks also to @arfon for shepherding our paper through the process; we are deeply grateful to you both for volunteering your time and energies to this important work!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1488364 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1488364" target="_blank">10.5281/zenodo.1488364</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1075 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1075 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:73:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.1206239 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1016/j.visinf.2017.01.006 is OK
- 10.1002/sam.11271 is OK

MISSING DOIs

- https://doi.org/10.1145/1753326.1753529 may be missing for title: Interactive optimization for steering machine classification

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1075 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1075 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:73:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@bbengfort @rebeccabilbro - could you see if that DOI suggested by Whedon is the correct one for your references? If so, please add it to the bibtex.

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.1206239 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1016/j.visinf.2017.01.006 is OK
- 10.1002/sam.11271 is OK

MISSING DOIs

- https://doi.org/10.1145/1753326.1753529 may be missing for title: Interactive optimization for steering machine classification

INVALID DOIs

- None
```

**Comment by bbengfort** [comment]
@arfon could we update our archive DOI to 10.5281/zenodo.1206239 please? This will resolve to the latest version of Yellowbrick, whereas the DOI I supplied before will only resolve to v0.9. 

The DOI for the Interactive Optimization paper is correct, I'm updating the bibtex now!

**Comment by bbengfort** [comment]
@arfon the bibtex has been updated in the Yellowbrick repo.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1206239 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1206239" target="_blank">10.5281/zenodo.1206239</a> is the archive.

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.1206239 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1145/2935694.2935698 is OK
- 10.1016/j.visinf.2017.01.006 is OK
- 10.1002/sam.11271 is OK
- 10.1145/1753326.1753529 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01075/joss.01075/10.21105.joss.01075.pdf)

**Comment by arfon** [comment]
@mnarayan - many thanks for your review here ✨ 

@bbengfort @rebeccabilbro - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01075/status.svg)](https://doi.org/10.21105/joss.01075)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01075">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01075/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01075/status.svg
   :target: https://doi.org/10.21105/joss.01075
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01075/status.svg)](https://doi.org/10.21105/joss.01075)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
