### ISSUE TITLE
[PRE REVIEW]: IDTxl: The Information Dynamics Toolkit xl: a Python package for the efficient analysis of multivariate information dynamics in networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1078]
**Submitting author:** @pwollstadt (<a href="http://orcid.org/0000-0002-7105-5207">Patricia Wollstadt</a>)
**Repository:** <a href="https://github.com/pwollstadt/IDTxl" target ="_blank">https://github.com/pwollstadt/IDTxl</a>
**Version:** v.0.4.0
**Editor:** @cMadan
**Reviewers:** @danielemarinazzo, @Autoplectic

**Author instructions**

Thanks for submitting your paper to JOSS @pwollstadt. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@pwollstadt if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by jlizier** [comment]
Hi -- some reviewer suggestions from @pwollstadt and I are as follows:
1. Daniele Marinazzo @danielemarinazzo who is familiar with the inference algorithms and underlying information theory measures here.
2. Ryan James @Autoplectic who is familiar with the underlying information theory measures and has published with JOSS in the past.
3. Luca Faes (can't find a github account though), whose expertise here is similar to Marinazzo

**Comment by danielemarinazzo** [comment]
good, hit me. If you preprint I can do an open review too.
I won't be able to review the code though, you might want someone expert in
that.

Luca Faes has no github account indeed afaik.

cheers

**Comment by pwollstadt** [comment]
Hi all! 

@cMadan, we have reviewed the pdf and have found a problem with multiple citations. I fixed that and uploaded the corrected version (https://github.com/pwollstadt/IDTxl/commit/b9316494054e82cff8342e54bc5189a05f677fb4). There was another error in a reference, I also got rid of. Is there any action required on my part to recompile the pdf?

Thanks @jlizier for adding our suggested reviewers and thanks already to @danielemarinazzo for the quick reply!

**Comment by jlizier** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01078/joss.01078/10.21105.joss.01078.pdf)

**Comment by jlizier** [comment]
The 2nd generated PDF proof is fine.

(@cMadan I hope I'm not out of line here by adding:) @danielemarinazzo I don't think JOSS is too worried about code level review, more a check of required features such as documentation, tests, etc -- see https://joss.readthedocs.io/en/latest/reviewer_guidelines.html and see the checklist for the reviewer in issue #1075 for example (a similar checklist would be added here once reviewers are formally assigned). Thanks for the quick reply!

**Comment by Autoplectic** [comment]
I'm happy to review this work.

**Comment by cMadan** [comment]
@jlizier, no problem about revising the PDF. I wouldn't quite agree that we're not worried about code-level review. It's definitely not line-by-line, but this is a software journal and part of evaluating the functionality is agreeing that the code as a whole does what it says it's supposed to do.

@danielemarinazzo, it would be great to have you as a reviewer for this. Evaluate what you think you can, and let me know what aspects you feel unsure to judge--and then we'll figure things from there.

@Autoplectic, great, thanks for volunteering!

**Comment by cMadan** [comment]
@whedon add @danielemarinazzo as reviewer

**Comment by whedon** [comment]
OK, @danielemarinazzo is now a reviewer

**Comment by cMadan** [comment]
@whedon add @Autoplectic as reviewer

**Comment by whedon** [comment]
OK, @Autoplectic is now a reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1081. Feel free to close this issue now!
