### ISSUE TITLE
[PRE REVIEW]: Hickle: A HDF5-based Python pickle replacement

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1080]
**Submitting author:** @telegraphic (<a href="http://orcid.org/0000-0003-2783-1608">Danny Price</a>)
**Repository:** <a href="https://github.com/telegraphic/hickle" target ="_blank">https://github.com/telegraphic/hickle</a>
**Version:** v3.2.2
**Editor:** @arfon
**Reviewers:** @betteridiot

**Author instructions**

Thanks for submitting your paper to JOSS @telegraphic. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@telegraphic if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1080 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
:wave: @telegraphic, thanks for your submission to JOSS. Our robot @whedon is somewhat fussy about filenames so could you please rename your `PAPER.md` to `paper.md` and update the paper to point to your bibliography (it's currently pointing to `paper.bib` but your bibtex appears to be in `references.bib`)

**Comment by telegraphic** [comment]
Thanks @arfon, no worries, just pushed the new names.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1080 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1080/paper.md): mapping values are not allowed in this context at line 17 column 10 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-b79e4e9c8e4d/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-b79e4e9c8e4d/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-b79e4e9c8e4d/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-b79e4e9c8e4d/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-b79e4e9c8e4d/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@telegraphic - I made some small fixes to your paper here: https://github.com/telegraphic/hickle/pull/78

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01080/joss.01080/10.21105.joss.01080.pdf)

**Comment by telegraphic** [comment]
Looks like the list at the end did not convert from markdown `*`s into bullets?

**Comment by telegraphic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01080/joss.01080/10.21105.joss.01080.pdf)

**Comment by telegraphic** [comment]
An extra break seems to have done the trick, the proof looks great

**Comment by arfon** [comment]
@telegraphic - could you take a look at [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few candidates that might be able to give this package a good review. Also, please start from somewhere near the bottom of the spreadsheet where some of the more recent JOSS review volunteers are listed.

**Comment by telegraphic** [comment]
How about @mgckind @adammichaelwood  or @betteridiot?

**Comment by arfon** [comment]
:wave: @adammichaelwood @betteridiot would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by betteridiot** [comment]
Let me give a quick glance. I will get back to you by 12:00 PM November 14th (lunch today).

**Comment by betteridiot** [comment]
I would be more than happy to review this package

**Comment by arfon** [comment]
Great, thanks @betteridiot. I'll go ahead and set you up as a reviewer but there won't be anything to actually do until I've identified a second reviewer and we've created the main review thread.

**Comment by arfon** [comment]
@whedon add @betteridiot as reviewer

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@tupi @tianxzhu - would either of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by betteridiot** [comment]
How is this going? Should I start reviewing?

**Comment by arfon** [comment]
@betteridiot - I had hoped to find a second reviewer but am struggling. Let's move forward with just yourself - I'll be along for the ride too if you need my assistance :-)

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1115. Feel free to close this issue now!

**Comment by arfon** [comment]
@betteridiot @telegraphic see you both over in #1115 where the actual JOSS review takes place.
