### ISSUE TITLE
[REVIEW]: IDTxl: The Information Dynamics Toolkit xl: a Python package for the efficient analysis of multivariate information dynamics in networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1081]
**Submitting author:** @pwollstadt (<a href="http://orcid.org/0000-0002-7105-5207">Patricia Wollstadt</a>)
**Repository:** <a href="https://github.com/pwollstadt/IDTxl" target ="_blank">https://github.com/pwollstadt/IDTxl</a>
**Version:** 1.0
**Editor:** @cMadan
**Reviewer:** @danielemarinazzo, @Autoplectic
**Archive:** <a href="https://doi.org/10.5281/zenodo.2554339" target="_blank">10.5281/zenodo.2554339</a>

## Status

[![status](http://joss.theoj.org/papers/121584f956839529d509ecbf1bce1376/status.svg)](http://joss.theoj.org/papers/121584f956839529d509ecbf1bce1376)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/121584f956839529d509ecbf1bce1376"><img src="http://joss.theoj.org/papers/121584f956839529d509ecbf1bce1376/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/121584f956839529d509ecbf1bce1376/status.svg)](http://joss.theoj.org/papers/121584f956839529d509ecbf1bce1376)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pwollstadt/IDTxl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@danielemarinazzo & @Autoplectic, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @cMadan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pwollstadt/IDTxl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.0
- [x] **Authorship:** Has the submitting author (@pwollstadt) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pwollstadt/IDTxl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.0
- [x] **Authorship:** Has the submitting author (@pwollstadt) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @danielemarinazzo, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01081/joss.01081/10.21105.joss.01081.pdf)

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01081/joss.01081/10.21105.joss.01081.pdf)

**Comment by pwollstadt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01081/joss.01081/10.21105.joss.01081.pdf)

**Comment by danielemarinazzo** [comment]
I have completed the checklist. Unless I have missed, and I apologize in advance, the license file seems to be missing.

Suggestions: 

1. it would be convenient to add some running time indicators for different possible scenarios (number of time series, length of time series, etc).
2. you call "multivariate" and "bivariate" the cases with more or two time series respectively. In other contexts "multivariate" refers to the case in which the driver, or the target, or both, are comprised of many time series. On the other hand the case in which you want to distinguish among direct and mediated influences is called "conditioned" as opposed to "pairwise".  I understand that this is solely a matter of nomenclature, still a note of disambiguation could be useful.
3. In the examples you refer to "MuTE network" or "generate.mute.example".  If MuTE is  a general acronym for multivariate transfer entropy, no problem. If on the other hand it refers to the examples implemented in our toolbox (https://github.com/montaltoalessandro/MuTE), I would just like to stress the benchmark model with 5 time series is not ours but is taken by other toolboxes, such as the MVGC by Barnett and Seth, and before that the work by Baccala and Sameshima.

Congratultions and thanks for this nice upgrade.

d.

**Comment by cMadan** [comment]
It looks like the license is in `COPYING.txt`. Is there a particular reason that this is the filename, rather than `LICENSE.txt`?

**Comment by jlizier** [comment]
From memory that was to follow the [GNU recommendation](http://www.gnu.org/licenses/gpl-howto.html) - is the use of LICENSE mandatory for JOSS or other options ok so long as it's following some convention such as GNU?

@danielemarinazzo thanks for the comments - all are clear, we'll get back to you on those

**Comment by cMadan** [comment]
JOSS doesn't have any rules about the license filename, but my impression is that `LICENSE` is more common of a filename than `COPYING`, even for GNU GPL licensed projects. The main idea is that the license should be easily found. I recommend you change the filename here, but I am not going to require it.

**Comment by pwollstadt** [comment]
Hi @cMadan, I changed the file name to `LICENSE` in https://github.com/pwollstadt/IDTxl/commit/1d617372cca66449dd36139b3301c17391e193f7.

Thanks @danielemarinazzo for the quick review. I will look into the relevant references for the MuTE example, thanks for pointing that out.

**Comment by Autoplectic** [comment]
Everything checklist-wise looks good to me.

A few minor suggestions:

You implement and document both [multiinformation](https://github.com/pwollstadt/IDTxl/wiki/Variable-names-used-in-IDTxl) as well as [multivariate mutual information](http://pwollstadt.github.io/IDTxl/html/idtxl_network_inference.html#multivariate-mutual-information-mmi). It would be best to utilize a single name, and to list alternative names (this quantity is often also called the total correlation, for example). Further, it would be good to explicitly state that which multivariate mutual informations it is *not* (co-information/integration, dual total correlation/binding information, [CAEKL mutual information](https://ieeexplore.ieee.org/document/7270410?reload=true&arnumber=7270410&filter%3DAND(p_IS_Number:7270357))).

To check my sanity, the SydneyPID estimator estimates the BROJA PID, not the recent PID of Lizier and Finn, yes?

**Comment by pwollstadt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01081/joss.01081/10.21105.joss.01081.pdf)

**Comment by pwollstadt** [comment]
Hi all, thanks to @danielemarinazzo and @Autoplectic for the review and the suggestions, we have addressed the remaining issues: 

@danielemarinazzo, we have added the original reference for the example network used in the MuTE paper. Also, theoretical and some practical results for runtimes have been added as a [wiki page](https://github.com/pwollstadt/IDTxl/wiki/Runtimes-and-Benchmarking). I also added a sentence to the [theoretical introduction](https://github.com/pwollstadt/IDTxl/wiki/Theoretical-Introduction#idtxls-greedy-algorithm-for-mte-estimation) pointing our that what we call multivariate TE, is sometimes also termed "conditioned" TE. The major issue regarding the license file was already fixed earlier (see https://github.com/openjournals/joss-reviews/issues/1081#issuecomment-441458997).

@Autoplectic, we do not yet implement a measure for multiinformation, only multivariate mutual information. We apologise for the confusion. We have added a note to the [variable list](https://github.com/pwollstadt/IDTxl/wiki/Variable-names-used-in-IDTxl#idtxl-variable-and-function-names)  that it contains `multiinformation` for future reference and is not yet implemented. We hope, this will clear up misunderstandings about the implementation.

> To check my sanity, the SydneyPID estimator estimates the BROJA PID, not the recent PID of Lizier and Finn, yes?

Yes, The Sydney PID estimator estimates the BROJA PID. I added this information to the classes' docstring.

@editor, the commits also contain a fix for an issue raised independently of the JOSS review process ([#20](https://github.com/pwollstadt/IDTxl/issues/20)). I hope this is alright with everyone. 

Thanks again to everyone for your suggestions so far!

**Comment by Autoplectic** [comment]
@pwollstadt what exactly do you mean by multivariate mutual information? There are several quantities which have been called that, and so adding a definition or utilizing a more specific name would be very helpful.

**Comment by pwollstadt** [comment]
@Autoplectic, we have added a description of our multivariate mutual information implementation to the [Wiki](https://github.com/pwollstadt/IDTxl/wiki/Theoretical-Introduction#further-network-inference-algorithms-implemented-in-idtxl). Thank you for your suggestion, we hope this clears up any misunderstanding about what is meant here.

**Comment by danielemarinazzo** [comment]
That's very good for me, I have no further comments.
Congratulations on a useful paper and piece of software.

**Comment by cMadan** [comment]
@Autoplectic, do you have any additional questions, or are the definitions of the terms clear now? Thank you!

**Comment by Autoplectic** [comment]
I have no further questions. With the multitude of multivariate information measures out there, it is important to have definitions as the same term is used to refer to different quantities rather often.

**Comment by cMadan** [comment]
@Autoplectic, of course, that completely makes sense.

@pwollstadt, it looks like we're all set to accept! Can you mint a new release that includes all of the changes from the review process, and provide a doi associated with an archived version on Zenodo or figshare?

**Comment by pwollstadt** [comment]
@cMadan, I prepared a [final release](https://github.com/pwollstadt/IDTxl/releases/tag/v1.0) containing all requested changes and linked it to Zenodo. Here is the DOI: [10.5281/zenodo.2554339](https://doi.org/10.5281/zenodo.2554339). Let me know if there is anything more you need from us for the publication. Thanks again to @Autoplectic and @danielemarinazzo and everyone else for your input!

**Comment by cMadan** [comment]
@whedon set 1.0 as version

**Comment by whedon** [comment]
OK. 1.0 is the version.

**Comment by cMadan** [comment]
@whedon set 10.5281/zenodo.2554339 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2554339" target="_blank">10.5281/zenodo.2554339</a> is the archive.

**Comment by cMadan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/488

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/488, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by pwollstadt** [comment]
Thanks a lot! We found a minor error in the final proof, which I fixed in the repo's master (https://github.com/pwollstadt/IDTxl/commit/84e8469545402740ec5f89dc1b9dd925f955210). Is there a way to generate the final PDF from that?

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1081 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    255      0 --:--:-- --:--:-- --:--:--   258

**Comment by arfon** [comment]
@pwollstadt - the `paper.md` metadata is currently broken. Please make this fix: https://github.com/pwollstadt/IDTxl/pull/31

**Comment by pwollstadt** [comment]
Sorry about that. Thanks, I merged the fix into master (
https://github.com/pwollstadt/IDTxl/commit/a949f07857379727ddfab98c35074b0e8f580171).

**Comment by jlizier** [comment]
@whedon accept

**Comment by whedon** [comment]
I'm sorry @jlizier, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by jlizier** [comment]
Ah ok, I was trying to regenerate the proof / dry run after the merge, so we can verify it then give the deposit=true line. Could you do that pls @arfon ?

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1081 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1081 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:73:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1103/PhysRevE.83.051112 is OK
- http://doi.org/10.1103/PhysRevE.69.066138 is OK
- http://doi.org/10.1371/journal.pone.0109462 is OK
- http://doi.org/10.1103/PhysRevLett.85.461 is OK
- http://doi.org/10.1007/s10827-010-0262-3 is OK
- http://doi.org/10.1371/journal.pone.0055809 is OK
- http://doi.org/10.1002/j.1538-7305.1948.tb00917.x is OK
- http://doi.org/10.1007/s12064-011-0145-9 is OK
- http://doi.org/10.1016/j.ins.2012.04.016 is OK
- http://doi.org/10.3390/e16042161 is OK
- http://doi.org/10.3390/e20040271 is OK
- http://doi.org/10.3389/frobt.2014.00011 is OK
- http://doi.org/10.1186/1471-2202-12-119 is OK
- http://doi.org/10.2307/1912791 is OK

MISSING DOIs

- https://doi.org/10.1186/1471-2202-14-s1-p337 may be missing for title: Multivariate construction of effective computational networks from observational data

INVALID DOIs

- http://doi.org/http://arxiv.org/abs/1004.2515 is INVALID
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1103/PhysRevE.83.051112 is OK
- http://doi.org/10.1103/PhysRevE.69.066138 is OK
- http://doi.org/10.1371/journal.pone.0109462 is OK
- http://doi.org/10.1103/PhysRevLett.85.461 is OK
- http://doi.org/10.1007/s10827-010-0262-3 is OK
- http://doi.org/10.1371/journal.pone.0055809 is OK
- http://doi.org/10.1002/j.1538-7305.1948.tb00917.x is OK
- http://doi.org/10.1007/s12064-011-0145-9 is OK
- http://doi.org/10.1016/j.ins.2012.04.016 is OK
- http://doi.org/10.3390/e16042161 is OK
- http://doi.org/10.3390/e20040271 is OK
- http://doi.org/10.3389/frobt.2014.00011 is OK
- http://doi.org/10.1186/1471-2202-12-119 is OK
- http://doi.org/10.2307/1912791 is OK

MISSING DOIs

- https://doi.org/10.1186/1471-2202-14-s1-p337 may be missing for title: Multivariate construction of effective computational networks from observational data

INVALID DOIs

- http://doi.org/http://arxiv.org/abs/1004.2515 is INVALID
```

**Comment by arfon** [comment]
@pwollstadt - please remove `http://arxiv.org/abs/1004.2515` from the DOI field in your bibtex. Something like this should work as an entry instead.

```
@misc{1004.2515,
Author = {Paul L. Williams and Randall D. Beer},
Title = {Nonnegative Decomposition of Multivariate Information},
Year = {2010},
Eprint = {arXiv:1004.2515},
}
```

Also, ignore the DOI suggestion here. Whedon does its best to suggest possible missing DOIs but sometimes it's wrong :-)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1103/PhysRevE.83.051112 is OK
- http://doi.org/10.1103/PhysRevE.69.066138 is OK
- http://doi.org/10.1371/journal.pone.0109462 is OK
- http://doi.org/10.1103/PhysRevLett.85.461 is OK
- http://doi.org/10.1007/s10827-010-0262-3 is OK
- http://doi.org/10.1371/journal.pone.0055809 is OK
- http://doi.org/10.1002/j.1538-7305.1948.tb00917.x is OK
- http://doi.org/10.1007/s12064-011-0145-9 is OK
- http://doi.org/10.1016/j.ins.2012.04.016 is OK
- http://doi.org/10.3390/e16042161 is OK
- http://doi.org/10.3390/e20040271 is OK
- http://doi.org/10.3389/frobt.2014.00011 is OK
- http://doi.org/10.1186/1471-2202-12-119 is OK
- http://doi.org/10.2307/1912791 is OK

MISSING DOIs

- https://doi.org/10.1186/1471-2202-14-s1-p337 may be missing for title: Multivariate construction of effective computational networks from observational data

INVALID DOIs

- http://doi.org/http://arxiv.org/abs/1004.2515 is INVALID
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1103/PhysRevE.83.051112 is OK
- http://doi.org/10.1103/PhysRevE.69.066138 is OK
- http://doi.org/10.1371/journal.pone.0109462 is OK
- http://doi.org/10.1103/PhysRevLett.85.461 is OK
- http://doi.org/10.1007/s10827-010-0262-3 is OK
- http://doi.org/10.1371/journal.pone.0055809 is OK
- http://doi.org/10.1002/j.1538-7305.1948.tb00917.x is OK
- http://doi.org/10.1007/s12064-011-0145-9 is OK
- http://doi.org/10.1016/j.ins.2012.04.016 is OK
- http://doi.org/10.3390/e16042161 is OK
- http://doi.org/10.3390/e20040271 is OK
- http://doi.org/10.3389/frobt.2014.00011 is OK
- http://doi.org/10.1186/1471-2202-12-119 is OK
- http://doi.org/10.2307/1912791 is OK

MISSING DOIs

- https://doi.org/10.1186/1471-2202-14-s1-p337 may be missing for title: Multivariate construction of effective computational networks from observational data

INVALID DOIs

- http://doi.org/http://arxiv.org/abs/1004.2515 is INVALID
```

**Comment by pwollstadt** [comment]
Thanks! :) I fixed the arxiv reference and left everything else as is in  
https://github.com/pwollstadt/IDTxl/commit/de4ed33770311ba566c74d2f88fcafbecefcd6f5

**Comment by cMadan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1103/PhysRevE.83.051112 is OK
- http://doi.org/10.1103/PhysRevE.69.066138 is OK
- http://doi.org/10.1371/journal.pone.0109462 is OK
- http://doi.org/10.1103/PhysRevLett.85.461 is OK
- http://doi.org/10.1007/s10827-010-0262-3 is OK
- http://doi.org/10.1371/journal.pone.0055809 is OK
- http://doi.org/10.1002/j.1538-7305.1948.tb00917.x is OK
- http://doi.org/10.1007/s12064-011-0145-9 is OK
- http://doi.org/10.1016/j.ins.2012.04.016 is OK
- http://doi.org/10.3390/e16042161 is OK
- http://doi.org/10.3390/e20040271 is OK
- http://doi.org/10.3389/frobt.2014.00011 is OK
- http://doi.org/10.1186/1471-2202-12-119 is OK
- http://doi.org/10.2307/1912791 is OK

MISSING DOIs

- https://doi.org/10.1186/1471-2202-14-s1-p337 may be missing for title: Multivariate construction of effective computational networks from observational data

INVALID DOIs

- None
```

**Comment by jlizier** [comment]
The suggested missing DOI is for a preprint without a DOI, so I think we can proceed

**Comment by cMadan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1103/PhysRevE.83.051112 is OK
- http://doi.org/10.1103/PhysRevE.69.066138 is OK
- http://doi.org/10.1371/journal.pone.0109462 is OK
- http://doi.org/10.1103/PhysRevLett.85.461 is OK
- http://doi.org/10.1007/s10827-010-0262-3 is OK
- http://doi.org/10.1371/journal.pone.0055809 is OK
- http://doi.org/10.1002/j.1538-7305.1948.tb00917.x is OK
- http://doi.org/10.1007/s12064-011-0145-9 is OK
- http://doi.org/10.1016/j.ins.2012.04.016 is OK
- http://doi.org/10.3390/e16042161 is OK
- http://doi.org/10.3390/e20040271 is OK
- http://doi.org/10.3389/frobt.2014.00011 is OK
- http://doi.org/10.1186/1471-2202-12-119 is OK
- http://doi.org/10.2307/1912791 is OK

MISSING DOIs

- https://doi.org/10.1186/1471-2202-14-s1-p337 may be missing for title: Multivariate construction of effective computational networks from observational data

INVALID DOIs

- None
```

**Comment by cMadan** [comment]
@arfon, it looks like whedon isn't giving the link to the final proof here...? Otherwise I think we're set to accept.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1103/PhysRevE.83.051112 is OK
- http://doi.org/10.1103/PhysRevE.69.066138 is OK
- http://doi.org/10.1371/journal.pone.0109462 is OK
- http://doi.org/10.1103/PhysRevLett.85.461 is OK
- http://doi.org/10.1007/s10827-010-0262-3 is OK
- http://doi.org/10.1371/journal.pone.0055809 is OK
- http://doi.org/10.1002/j.1538-7305.1948.tb00917.x is OK
- http://doi.org/10.1007/s12064-011-0145-9 is OK
- http://doi.org/10.1016/j.ins.2012.04.016 is OK
- http://doi.org/10.3390/e16042161 is OK
- http://doi.org/10.3390/e20040271 is OK
- http://doi.org/10.3389/frobt.2014.00011 is OK
- http://doi.org/10.1186/1471-2202-12-119 is OK
- http://doi.org/10.2307/1912791 is OK

MISSING DOIs

- https://doi.org/10.1186/1471-2202-14-s1-p337 may be missing for title: Multivariate construction of effective computational networks from observational data

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
> @arfon, it looks like whedon isn't giving the link to the final proof here...? Otherwise I think we're set to accept.

Not sure what's going on here. Will debug.

**Comment by whedon** [comment]
PDF failed to compile for issue #1081 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1081 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:73:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/505

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/505, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/506

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/506, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1103/PhysRevE.83.051112 is OK
- http://doi.org/10.1103/PhysRevE.69.066138 is OK
- http://doi.org/10.1371/journal.pone.0109462 is OK
- http://doi.org/10.1103/PhysRevLett.85.461 is OK
- http://doi.org/10.1007/s10827-010-0262-3 is OK
- http://doi.org/10.1371/journal.pone.0055809 is OK
- http://doi.org/10.1002/j.1538-7305.1948.tb00917.x is OK
- http://doi.org/10.1007/s12064-011-0145-9 is OK
- http://doi.org/10.1016/j.ins.2012.04.016 is OK
- http://doi.org/10.3390/e16042161 is OK
- http://doi.org/10.3390/e20040271 is OK
- http://doi.org/10.3389/frobt.2014.00011 is OK
- http://doi.org/10.1186/1471-2202-12-119 is OK
- http://doi.org/10.2307/1912791 is OK

MISSING DOIs

- https://doi.org/10.1186/1471-2202-14-s1-p337 may be missing for title: Multivariate construction of effective computational networks from observational data

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/507
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01081](https://doi.org/10.21105/joss.01081)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@danielemarinazzo, @Autoplectic - many thanks for your reviews here and to @cMadan for editing this one ✨ 

@pwollstadt - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01081/status.svg)](https://doi.org/10.21105/joss.01081)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01081">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01081/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01081/status.svg
   :target: https://doi.org/10.21105/joss.01081
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01081/status.svg)](https://doi.org/10.21105/joss.01081)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by jlizier** [comment]
Awesome - thank you very much @arfon @cMadan and @danielemarinazzo @Autoplectic for your work!
