### ISSUE TITLE
[REVIEW]: GFAKluge: A C++ library and command line utilities for the Graphical Fragment Assembly formats

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1083]
**Submitting author:** @edawson (<a href="http://orcid.org/0000-0001-5448-1653">Eric Dawson</a>)
**Repository:** <a href="https://github.com/edawson/gfakluge" target ="_blank">https://github.com/edawson/gfakluge</a>
**Version:** 1.1.2
**Editor:** @mgymrek
**Reviewer:** @sjackman
**Archive:** <a href="https://doi.org/10.5281/zenodo.2546721" target="_blank">10.5281/zenodo.2546721</a>

## Status

[![status](http://joss.theoj.org/papers/d731f6dfc6b77013caaccfd8333c684a/status.svg)](http://joss.theoj.org/papers/d731f6dfc6b77013caaccfd8333c684a)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d731f6dfc6b77013caaccfd8333c684a"><img src="http://joss.theoj.org/papers/d731f6dfc6b77013caaccfd8333c684a/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d731f6dfc6b77013caaccfd8333c684a/status.svg)](http://joss.theoj.org/papers/d731f6dfc6b77013caaccfd8333c684a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/edawson/gfakluge" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sjackman, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @mgymrek know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/edawson/gfakluge">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.1.2
- [x] **Authorship:** Has the submitting author (@edawson) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @sjackman it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01083/joss.01083/10.21105.joss.01083.pdf)

**Comment by sjackman** [comment]
> Installation: Does installation proceed as outlined in the documentation?

> You can build libgfakluge and the command line gfak utilities by typing `make` in the repo.

On macOS with Apple `clang`, `make` fails with `error: 'omp.h' file not found`, because `gfakluge` requires OpenMP, and Apple `clang` does not provide OpenMP. Please add OpenMP to the list of dependencies. Please include instructions in `README.md` for building from source on macOS.

```sh
brew install gcc@8
make CXX=g++-8
```

**Comment by sjackman** [comment]
> GFAKluge [@GFAKluge] is a set of command line utilities

> ```bibtex
@online{GFAKluge,
  author = {Eric T. Dawson and Richard Durbin},
  title = {GFAKluge},
  year = 2018,
  url = {https://github.com/edawson/gfakluge}
}
```

I don't believe it's typical to cite the software repository from the paper.

@mgymrek Opinion?

**Comment by sjackman** [comment]
Please mention the homepage and license in the Summary. For example

**Homepage**: <https://github.com/edawson/gfakluge> 
**License**: MIT

**Comment by sjackman** [comment]
> GFAKluge facilitates interprogram exchange by providing a high-level C++ API for developers

> To use GFAKluge in your program, you'll need to add a few lines to your code. First, add the necessary include line to your C++ code: `#include "gfakluge.hpp"`
Next, make sure that the library is on the proper system paths and compile line:

GFAKluge would be more easily used as a library if

1. it were a header-only library (so it does not require compilation and `-L… -l…`)
2. `make install` and the Brew package installed that header

To make `gfakluge` a header-only library, merge `gfakluge.hpp` and `gfakluge.cpp` into a single file and remove `gfakluge.cpp`. Make every method an inline method by either defining it within `class GFAKluge` or decorating the definition with `static inline` if it's defined outside the class.

Header-only libraries are much easier to use in practice than libraries that require linking.

**Comment by sjackman** [comment]
Please add a `make install` target to `Makefile`.

```makefile
prefix=/usr/local

install:
	install gfak $(DESTDIR)$(prefix)/bin/
```

**Comment by sjackman** [comment]
> and converting between legacy GFA formats.

Please be more specific. I suggest `and converting between GFA versions 1 and 2.`

**Comment by sjackman** [comment]
> To our knowledge, GFAKluge is the only publically-available software package that can consume and produce both GFA1 and GFA2

GfaPy is able to consume and produce both GFA1 and GFA2.
https://doi.org/10.1093/bioinformatics/btx398

RGFA handles only GFA1 (I believe). I suggest citing it.
https://doi.org/10.7717/peerj.2681

`abyss-todot` included with ABySS 2 produces both GFA1 and GFA2 (with the command line options `--gfa1` and `--gfa2`), and consumes both with some format limitations (it does not handle all record types).
https://doi.org/10.1101/gr.214346.116

See https://github.com/GFA-spec/GFA-spec#implementations

**Comment by sjackman** [comment]
> the gfak convert tool

I'd suggest typesetting this as…

the `gfak convert` tool

**Comment by sjackman** [comment]
Ditto `vg msga`

**Comment by sjackman** [comment]
> We see the command line utilities as being useful to the development community in the short term.

The need for file conversion will likely never go away. Older tools that support only GFA1 may never be updated to support GFA2. Newer tools may support producing only GFA2 and not GFA1. To make these tools interoperate, a conversion tool is needed. That need is likely not temporary.

**Comment by sjackman** [comment]
> Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

Please list in the manuscript the currently available commands.

```
   convert: Convert between GFA 0.1 <-> 1.0 <-> 2.0
   diff:    Determine whether two GFA files have identical graphs
   extract: Convert the S lines of a GFA file to FASTA format.
   fillseq: Add sequences from a FASTA file to S lines.
   ids:     Coordinate the ID spaces of multiple GFA graphs.
   concat:  Merge GFA graphs (without ID collisions).
   sort:    Print a GFA file in HSLP / HSEFGUO order.
   stats:   Get assembly statistics (e.g. N50) for a GFA file.
   subset:  Extract the subgraph between two IDs in a graph.
   trim:    Remove elements from a GFA graph.
```

Please give three or more real world examples of their use.

**Comment by sjackman** [comment]
> Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

Is the API documented? If not, please document the API using Doxygen or a similar tool. A one-line summary of the purpose of each public method is sufficient. Please post the rendered HTML API documentation online using GitHub Pages or similar.

**Comment by sjackman** [comment]
>  Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?

Please include a `make check` rule in the Makefile that runs the automated tests.

**Comment by sjackman** [comment]
> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I've ticked this off as complete, since I think it's self evident how to use GitHub to submit issues and pull requests. You could if you liked add `Reporting bugs` and `Contributing` to the README.md or CONTRIBUTING.md.

**Comment by sjackman** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by sjackman** [comment]
My review is complete.

**Comment by mgymrek** [comment]
Thanks for these helpful comments @sjackman.

To summarize for @edawson:

- Please address the comments regarding installation and documentation.
- I agree no need to cite the software repository in the paper.
- There is no need to include extensive documents of the different commands in the manuscript itself. However please be sure these are well documented e.g. in the readme or manual.
- For completeness it would be helpful to add a CONTRIBUTING.md file.

**Comment by edawson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01083/joss.01083/10.21105.joss.01083.pdf)

**Comment by edawson** [comment]
@mgymrek I believe I've just addressed the last of these. I've included my checklist, which I pulled out from @sjackman 's comments.

- [X] Fix install instructions
- [X] Remove citation to repo in summary
- [X] Mention the homepage and license in the summary
- [X] Make GFAKluge a header-only library
- [X] Add a make install target to makefile
- [X] Change the wording of "legacy GFA formats"
- [X] Reference GFApy and RGFA and ABYSS, all of which are other programs which can convert GFA 1 -> 2
- [X] Fix typesetting of convert
- [X] Fix typesetting of vg msga
- [X] Change wording to reflect that GFA2 and GFA1 interconversion needs are not temporary
- [X] List the currently available commands in the manuscript.
- [X] Give command line examples of three or more commands
- [X] Mention the API documentation in the manuscript
- [X] Add a make test target in the makefile that runs automated tests
- [X] Add a contributing section to the Readme

**Comment by sjackman** [comment]
For the authors of the reference "Gene Myers, Jason Chin, & Durbin, R. (2015)", I suggest adding Shaun Jackman (myself), Heng Li, and Giorgio Gonnella based on this text:

> Jason Chin, Richard Durbin, and myself (Gene Myers) found ourselves together at a workshop meeting in Dagstuhl Germany and hammered out an initial proposal for an assembly format. We started with GFA 1 and proceeded to build a more comprehensive design around it. After extensive revision and discussion on Github with the GFA group including Shaun Jackman, Heng Li, and Giorgio Gonnella, we arrived at GFA 2.0.

https://github.com/gfa-spec/gfa-spec/#gfa-20-graphical-fragment-assembly-gfa2-format-specification-20

**Comment by sjackman** [comment]
> convert: Convert between GFA 0.1 <-> 1.0 <-> 2.0

What is GFA 0.1, and how does it differ from GFA 1.0?

**Comment by sjackman** [comment]
> available in the interface.md file file.

There's a typo here: file ~~file~~.

**Comment by mgymrek** [comment]
Thanks @sjackman, if all the items have been completed could you just update the checklist above?

**Comment by edawson** [comment]
@sjackman I've addressed your remaining comments. We consider the original GFA proposal by Heng Li to be "GFA 0.1," and it's supported as a legacy format that predates any real specification. Thanks for your review!

@whedon generate pdf

**Comment by sjackman** [comment]
> We consider the original GFA proposal by Heng Li to be "GFA 0.1," and it's supported as a legacy format that predates any real specification.

Are there any tangible technical differences between Heng's proposal GFA 0.1 and GFA 1.0?

**Comment by edawson** [comment]
Off the top of my head, the only things that come to mind are the `x` and `a` lines sometimes seen in early minimap2 runs and the `W` walk line used in place of the `P` path line syntax.

**Comment by sjackman** [comment]
> Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?

```console
$ make check
prove test/gfa_test.t
test/gfa_test.t .. test/gfa_test.t: line 5: ./bash-tap/bash-tap-bootstrap: No such file or directory
test/gfa_test.t: line 7: plan: command not found
test/gfa_test.t: line 10: is: command not found
test/gfa_test.t: line 14: is: command not found
test/gfa_test.t: line 17: is: command not found
test/gfa_test.t: line 20: is: command not found
test/gfa_test.t: line 23: is: command not found
test/gfa_test.t: line 26: is: command not found
Processed 1 graphs...
Done.
test/gfa_test.t: line 29: is: command not found
Merging 2 graphs...
test/gfa_test.t: line 32: is: command not found
test/gfa_test.t .. Dubious, test returned 127 (wstat 32512, 0x7f00)
No subtests run 

Test Summary Report
-------------------
test/gfa_test.t (Wstat: 32512 Tests: 0 Failed: 0)
  Non-zero exit status: 127
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  1 wallclock secs ( 0.04 usr  0.01 sys +  0.06 cusr  0.06 csys =  0.17 CPU)
Result: FAIL
make: *** [Makefile:40: check] Error 1
```

Should the file `bash-tap/bash-tap-bootstrap` be included in the source code, or are further instructions needed for the automated tests?

**Comment by sjackman** [comment]
You may want to consider using Autotools (`autoconf` and `automake`) if you're interested. Not a requirement though.

**Comment by sjackman** [comment]
`make install` installs `gfakluge.hpp`, which depends on `tinyfa.hpp` and `pliib.hpp`, but those files are not installed by `make install`.

**Comment by sjackman** [comment]
`make check` fails on macOS with `md5sum: command not found`.
```console
$ make check
Last 15 lines from /Users/sjackman/Library/Logs/Homebrew/gfakluge/02.make:
test/gfa_test.t: line 32: md5sum: command not found
Merging 2 graphs...
test/gfa_test.t: line 32: is: command not found
test/gfa_test.t .. 
Dubious, test returned 127 (wstat 32512, 0x7f00)
```

**Comment by edawson** [comment]
- [X] make examples.md a link to that file  
- [X] set the GitHub website link to the appropriate documentation (now links to README / GitHub Pages)  
- [X] make interface.md a link to that file  
- [X] bash-tap/bash-tap-bootstrap be included in the source code (made bash-tap) a git submodule, meaning it's now downloaded with `git clone --recursive`  
- [X] You may want to consider using Autotools (I'm going to run through some tutorials and see if I can incorporate this - thanks for the suggestion!)
- [X] `make` install installs `pliib.hpp` and `tinyfa.hpp`

> I've updated brewsci/bio/gfakluge to 1.1.0.  

Awesome! I was trying to do this before but struggling. I'd definitely appreciate the help learning how to bump a version and cut a fresh release on homebrew.

**Comment by sjackman** [comment]
> Awesome! I was trying to do this before but struggling. I'd definitely appreciate the help learning how to bump a version and cut a fresh release on homebrew.

Open an issue or PR next time over at Brewsci/bio, and if you run into any trouble, I'll be happy to walk you through it.

**Comment by sjackman** [comment]
> Thanks @sjackman, if all the items have been completed could you just update the checklist above?

@mgymrek All checked off, Melissa! ✅

**Comment by mgymrek** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01083/joss.01083/10.21105.joss.01083.pdf)

**Comment by mgymrek** [comment]
Thanks @sjackman!

@edawson could you (1) create a Zenodo archive and report the DOI in this thread and (2) check over the proof that was just generated by whedon?

**Comment by edawson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01083/joss.01083/10.21105.joss.01083.pdf)

**Comment by edawson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01083/joss.01083/10.21105.joss.01083.pdf)

**Comment by edawson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01083/joss.01083/10.21105.joss.01083.pdf)

**Comment by edawson** [comment]
@mgymrek I had to make a few changes to the bibliography that I missed earlier, but the latest proof is now good. The DOI is: 10.5281/zenodo.2546721 . Thanks (and thanks again @sjackman )!

**Comment by mgymrek** [comment]
@whedon set 10.5281/zenodo.2546721 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2546721" target="_blank">10.5281/zenodo.2546721</a> is the archive.

**Comment by mgymrek** [comment]
@whedon set 1.1.2 as version

**Comment by whedon** [comment]
OK. 1.1.2 is the version.

**Comment by mgymrek** [comment]
thanks, congrats @edawson! and thanks @sjackman for the helpful review

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/449

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/449, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/450
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01083](https://doi.org/10.21105/joss.01083)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@sjackman - many thanks for your review here and to @mgymrek for editing this submission ✨ 

@edawson - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01083/status.svg)](https://doi.org/10.21105/joss.01083)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01083">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01083/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01083/status.svg
   :target: https://doi.org/10.21105/joss.01083
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01083/status.svg)](https://doi.org/10.21105/joss.01083)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by sjackman** [comment]
I've added the citation to the Brewsci/bio package. https://github.com/brewsci/homebrew-bio/commit/311543ab3629b3fd029fdd16be59c2040867607b

**Comment by sjackman** [comment]
The URL https://doi.org/10.21105/joss.01083 resolves to JOSS, but doi.org does not yet have a Bibtex entry. I imagine it will soon enough.
```console
$ curl -sLH "Accept: text/bibliography; style=bibtex" "https://doi.org/10.21105/joss.01083"
Resource not found.
```

**Comment by arfon** [comment]
> The URL https://doi.org/10.21105/joss.01083 resolves to JOSS, but doi.org does not yet have a Bibtex entry. I imagine it will soon enough.

Yeah, it can take a few hours for the DOI metadata to propagate properly.
