### ISSUE TITLE
[PRE REVIEW]: ggvoronoi: Voronoi Diagrams and Heatmaps with ggplot2

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1086]
**Submitting author:** @garretrc (<a href="http://orcid.org/0000-0002-1434-6630">Robert Garrett</a>)
**Repository:** <a href="https://github.com/garretrc/ggvoronoi" target ="_blank">https://github.com/garretrc/ggvoronoi</a>
**Version:** v0.8.2
**Editor:** @yochannah
**Reviewers:** @trinker, @corybrunson

**Author instructions**

Thanks for submitting your paper to JOSS @garretrc. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@garretrc if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01086/joss.01086/10.21105.joss.01086.pdf)

**Comment by arfon** [comment]
:wave: @trinker - would you be willing to review this submission for JOSS?

**Comment by garretrc** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by garretrc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01086/joss.01086/10.21105.joss.01086.pdf)

**Comment by trinker** [comment]
>  @trinker - would you be willing to review this submission for JOSS?

@arfon Yes

**Comment by yochannah** [comment]
@whedon assign @yochannah as editor

**Comment by whedon** [comment]
OK, the editor is @yochannah

**Comment by yochannah** [comment]
Hey @garretrc, thanks for submitting this paper for review! I'll be editing this for JOSS. 

@trinker thanks for being willing to review!

The next step is to find a second reviewer before we kick off the official review. @trinker @garretrc - any suggestions for reviewer number 2 by any chance, perhaps from the [reviewer spreadsheet](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing)? No worries if not!

**Comment by garretrc** [comment]
Maybe @nuest or @jhollist ? Based on folks who listed R and spatial in the spreadsheet

**Comment by jhollist** [comment]
Not a firm no.  I have some possible work changes coming up that would limit my ability to do a review.  I should know more in 10-12 days.  If you can get someone else that'd be best, but I'll keep y'all updated on my status.

**Comment by garretrc** [comment]
Looking at people who listed R and data viz I see @corybrunson and @tweed1e if either of you would be willing to review!

**Comment by corybrunson** [comment]
Probably—i hope to finish a review for a paper journal today or tomorrow; if i succeed, then i'll be glad to take this on and finish within a week. Will update within a day.

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1096. Feel free to close this issue now!

**Comment by yochannah** [comment]
⚡️  @trinker, @corybrunson thanks for volunteering to review this package! Let's head over to #1096 and work with @garretrc to complete the review 👍
