### ISSUE TITLE
[PRE REVIEW]: GAMA: Genetic Automated Machine learning Assistant

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1088]
**Submitting author:** @PGijsbers (<a href="http://orcid.org/0000-0001-7346-8075">Pieter Gijsbers</a>)
**Repository:** <a href="https://github.com/PGijsbers/GAMA" target ="_blank">https://github.com/PGijsbers/GAMA</a>
**Version:** v0.1.0
**Editor:** @arokem
**Reviewers:** @jsgalan

**Author instructions**

Thanks for submitting your paper to JOSS @PGijsbers. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@PGijsbers if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01088/joss.01088/10.21105.joss.01088.pdf)

**Comment by labarba** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by labarba** [comment]
@arokem : This is an obvious submission for you to handle, and it should be easy to find reviewers. For example, @rhiever 👋  …would be ideal to review this, if available & willing. If not, he may be able to help us identify a couple of reviewers.

**Comment by rhiever** [comment]
I'd love to, but I haven't had much extra time for reviewing lately. Maybe @mfeurer? @ledell or someone on the H2O dev team? @weixuanfu?

**Comment by weixuanfu** [comment]
I think it is a very interesting tool and I believe @PGijsbers did very good jobs related to autoML, but I didn't have much time for reviewing neither.

**Comment by arokem** [comment]
Yep. Thanks for assigning me. Will take a look.

**Comment by arokem** [comment]
@fmohr : would you like to review this article for [The Journal of Open Source Software](http://joss.theoj.org/)?

**Comment by mfeurer** [comment]
Thanks for suggesting me @rhiever, but I don't feel comfortable reviewing a paper of a collaborator.

**Comment by fmohr** [comment]
Hey, thanks for asking. In general, I am open to review for JOSS. In this particular case, however, I'm afraid I can't help out; I'm a Java guy and not at all an expert for Python. I don't know to which degree this is a problem, but Pieter mentions this as one of two criterions, so probably speaking Python should be a criterion.

**Comment by PGijsbers** [comment]
I have to admit I'm not intimately familiar with the level of code inspection that is done in the JOSS review process. I listed Python as required since the package is written entirely in Python, I figured it would make sense to look for people who are familiar so as to save time in the review process. That said, I would probably feel the same reviewing a package written in Java.

**Comment by arokem** [comment]
Yes. That all makes sense. Thanks for your candor, @fmohr. 

Let's keep looking for a reviewer that speaks Python...

**Comment by arokem** [comment]
Hey @krother, @nilesh-patil : would either or both of you be willing to review this article for JOSS?

**Comment by jsgalan** [comment]
Hi all,

Yes, i will have time to review it. Please assign it to me :)

Best

**Comment by arokem** [comment]
@whedon assign @jsgalan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jsgalan

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1132. Feel free to close this issue now!

**Comment by arokem** [comment]
Thanks for taking this on @jsgalan ! Please head over to #1132 for the review checklist. I am closing this one.
