### ISSUE TITLE
[PRE REVIEW]: rcites: An R package to access the CITES Speciesplus database

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1090]
**Submitting author:** @JonasGeschke (<a href="http://orcid.org/0000-0002-5654-9313">Jonas Geschke</a>)
**Repository:** <a href="https://github.com/ropensci/rcites" target ="_blank">https://github.com/ropensci/rcites</a>
**Version:** 1.0.0
**Editor:** @karthik
**Reviewers:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @JonasGeschke. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@JonasGeschke if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01090/joss.01090/10.21105.joss.01090.pdf)

**Comment by arfon** [comment]
Many thanks @JonasGeschke. Can you check the [article proof](https://github.com/openjournals/joss-papers/blob/joss.01090/joss.01090/10.21105.joss.01090.pdf) and let me know if this looks good to accept?

**Comment by JonasGeschke** [comment]
Thanks @arfon. We made some minor changes in the affiliations, so could you please update the article proof?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01090/joss.01090/10.21105.joss.01090.pdf)

**Comment by JonasGeschke** [comment]
Great, thank you @arfon! Looking good now.

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1091. Feel free to close this issue now!
