### ISSUE TITLE
[PRE REVIEW]: pyam: a Python Package for the Analysis and Visualization of Assessment Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1092]
**Submitting author:** @gidden (<a href="http://orcid.org/0000-0003-0687-414X">Matthew Gidden</a>)
**Repository:** <a href="https://github.com/IAMconsortium/pyam" target ="_blank">https://github.com/IAMconsortium/pyam</a>
**Version:** v0.1.2
**Editor:** @lheagy
**Reviewers:** @jtmiclat, @Chilipp

**Author instructions**

Thanks for submitting your paper to JOSS @gidden. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@gidden if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@lheagy) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1092 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1092/paper/paper.md): mapping values are not allowed in this context at line 5 column 18 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-b79e4e9c8e4d/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-b79e4e9c8e4d/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-b79e4e9c8e4d/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-b79e4e9c8e4d/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-b79e4e9c8e4d/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @lheagy - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
:wave: @gidden: this PR fixes the YAML of your paper: https://github.com/IAMconsortium/pyam/pull/144

**Comment by gidden** [comment]
Thanks again @arfon, PR is merge. This is my first submission to JOSS, will @whedon automatically rerender pdfs upon updates to `master` or do we need to explicitly ask it to do so?

**Comment by arfon** [comment]
> we need to explicitly ask it to do so?

You'll need to request another build. You can do this with `@whedon generate pdf`

**Comment by gidden** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01092/joss.01092/10.21105.joss.01092.pdf)

**Comment by gidden** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01092/joss.01092/10.21105.joss.01092.pdf)

**Comment by gidden** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01092/joss.01092/10.21105.joss.01092.pdf)

**Comment by lheagy** [comment]
Hi @gidden: Thanks for your submission! 

One quick think that I suggest is that you might consider including reference to "Climate science" in your title (the term "models" is very general, and from the title, it is not necessarily clear which domain of science the software is relevant to)

**Comment by jtmiclat** [comment]
Hello @lheagy, I am willing to review this but I am only able to start on weekend. Hope that is alright!

**Comment by lheagy** [comment]
Excellent, thanks @jtmiclat! Yes, starting on the weekend is fine

**Comment by Chilipp** [comment]
Hello @lheagy! Yes, I am willing to review it, too

**Comment by lheagy** [comment]
Thanks @Chilipp!!

**Comment by lheagy** [comment]
@whedon assign @jtmiclat as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jtmiclat

**Comment by lheagy** [comment]
@whedon add @Chilipp as reviewer

**Comment by whedon** [comment]
OK, @Chilipp is now a reviewer

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1095. Feel free to close this issue now!
