### ISSUE TITLE
[PRE REVIEW]: portalr: an R package for summarizing and using the Portal Project Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1093]
**Submitting author:** @emchristensen (<a href="http://orcid.org/0000-0002-5635-2502">Erica Christensen</a>)
**Repository:** <a href="https://github.com/weecology/portalr" target ="_blank">https://github.com/weecology/portalr</a>
**Version:** v0.1.4
**Editor:** @karthik
**Reviewers:** @Pakillo

**Author instructions**

Thanks for submitting your paper to JOSS @emchristensen. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@emchristensen if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@karthik) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1093 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
:wave: @emchristensen - could you please rename your `paper.Rmd` file to `paper.md` please?

**Comment by arfon** [comment]
@karthik - the submitting author suggested you as the handling editor.

**Comment by emchristensen** [comment]
oops, ok it's renamed now

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01093/joss.01093/10.21105.joss.01093.pdf)

**Comment by emchristensen** [comment]
I just removed a bit of code leftover when it was a .Rmd, otherwise looks good.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01093/joss.01093/10.21105.joss.01093.pdf)

**Comment by emchristensen** [comment]
looks good

**Comment by karthik** [comment]
@whedon assign @Pakillo as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @Pakillo

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1098. Feel free to close this issue now!
