### ISSUE TITLE
[REVIEW]: pyam: a Python Package for the Analysis and Visualization of Assessment Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1095]
**Submitting author:** @gidden (<a href="http://orcid.org/0000-0003-0687-414X">Matthew Gidden</a>)
**Repository:** <a href="https://github.com/IAMconsortium/pyam" target ="_blank">https://github.com/IAMconsortium/pyam</a>
**Version:** v0.1.2
**Editor:** @lheagy
**Reviewer:** @jtmiclat, @Chilipp
**Archive:** <a href="https://doi.org/10.5281/zenodo.1491662" target="_blank">10.5281/zenodo.1491662</a>

## Status

[![status](http://joss.theoj.org/papers/356bc013105642ec4e94a3b951836cfe/status.svg)](http://joss.theoj.org/papers/356bc013105642ec4e94a3b951836cfe)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/356bc013105642ec4e94a3b951836cfe"><img src="http://joss.theoj.org/papers/356bc013105642ec4e94a3b951836cfe/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/356bc013105642ec4e94a3b951836cfe/status.svg)](http://joss.theoj.org/papers/356bc013105642ec4e94a3b951836cfe)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/IAMconsortium/pyam" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jtmiclat & @Chilipp, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lheagy know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/IAMconsortium/pyam">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.2)?
- [x] **Authorship:** Has the submitting author (@gidden) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/IAMconsortium/pyam">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.2)?
- [x] **Authorship:** Has the submitting author (@gidden) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jtmiclat, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01095/joss.01095/10.21105.joss.01095.pdf)

**Comment by gidden** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01095/joss.01095/10.21105.joss.01095.pdf)

**Comment by gidden** [comment]
Hi @lheagy, per your suggestion, I have updated the title to more accurately reflect the scientific domains in which `pyam` is or is envisioned being used. Looking forward to the reviews of @jtmiclat and @Chilipp.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01095/joss.01095/10.21105.joss.01095.pdf)

**Comment by Chilipp** [comment]
Dear @gidden and @danielhuppmann . I reviewed your software today and I very much appreciate your work. I find this as a very useful and nicely documented piece of software and I very much appreciated the review. There are only minor revisions that I can present

- [ ] **Installation instructions**
  > Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

  The list of dependencies is missing in the [install instructions](http://software.ene.iiasa.ac.at/pyam/install.html). From your setup.py I get, that pyam is built on 

  - numpy
  - pandas >=0.21.0
  - matplotlib
  - seaborn

  They should at least be listed in the requirements, together with the necessary citations as specified on the webpages (e.g. for matplotlib it requires a link to https://matplotlib.org/ and a citation such as 

  Hunter, J. D., Matplotlib: A 2D Graphics Environment, Computing in Science Engineering, 2007, 9, 90-95
  (see https://matplotlib.org/citing.html)
- [ ] **Automated tests** 
  > Are there automated tests or manual steps described so that the function of the software can be verified?

  I highly recommend to include coverage tests into your software, e.g. by installing pytest-cov (pip install pytest-cov) on you CI services and then using some free services, such as [codecov.io (https://codecov.io/) or [coveralls.io](https://coveralls.io/). When I run your tests with coverage tests, I get

  <details>
  <summary>pytest -v --mpl tests --cov=pyam</summary>
  
  ```
  Name                  Stmts   Miss  Cover
  -----------------------------------------
  pyam/__init__.py         18      0   100%
  pyam/_version.py        277    152    45%
  pyam/core.py            538     64    88%
  pyam/iiasa.py            92      3    97%
  pyam/logger.py            8      0   100%
  pyam/plotting.py        378    194    49%
  pyam/run_control.py      62     19    69%
  pyam/statistics.py      151     23    85%
  pyam/timeseries.py       53      2    96%
  pyam/utils.py           152     23    85%
  -----------------------------------------
  TOTAL                  1729    480    72%
  ```
  </details>

  Overall, your package seems to be very well covered, but there are clearly some modules underrepresented in your tests (`pyam/plotting.py` and `pyam/_version.py`). However, JOSS does not formally require a report on your test coverage, so this is just a recommendation from my side.
- [ ] **Community guidelines:** 
  > Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

  These are missing (see https://help.github.com/articles/setting-guidelines-for-repository-contributors/ for guidance)

Additionally there are some minor things that I added as issues and PRs to your project
- [ ] https://github.com/IAMconsortium/pyam/pull/147
- [ ] https://github.com/IAMconsortium/pyam/pull/148
- [ ] https://github.com/IAMconsortium/pyam/issues/149
- [ ] https://github.com/IAMconsortium/pyam/issues/150

Once all these items are checked off, I recommend to publish your paper.

**Comment by lheagy** [comment]
:wave: hi @gidden, please keep us posted on your progress and post here when you are done with your revisions.

**Comment by gidden** [comment]
Hello all. First of all, thank you very much to @Chilipp and @jtmiclat for their very useful reviews. We have striven to implement all suggestions both of you made.

Notably these include:

- adding contributor/community guidance ([pr](https://github.com/IAMconsortium/pyam/pull/161), [site](https://software.ene.iiasa.ac.at/pyam/index.html#interested-in-contributing-welcome-to-the-team))
- adding coveralls support ([pr](https://github.com/IAMconsortium/pyam/pull/158), [site](https://coveralls.io/github/IAMconsortium/pyam))
- adding explicit required dependencies outside of `setup.py`/`pip` ([pr](https://github.com/IAMconsortium/pyam/pull/161), [site](https://software.ene.iiasa.ac.at/pyam/install.html#depedencies))

From our view, we believe the article is now ready for publication. Please let us know if we should do anything further.

**Comment by Chilipp** [comment]
I am okay with accepting his software for publication @lheagy. Thank you very much @gidden and @danielhuppmann for your work on this! 🎉 🎉

**Comment by Chilipp** [comment]
> were those just missed?

Yes, my apologies

**Comment by lheagy** [comment]
Many thanks @Chilipp and @jtmiclat for taking the time to review! 🎉 

Congratulations @gidden on your submission! To finalize the acceptance, please archive your software on [zenodo](http://zenodo.org) or similar and post the doi here.

**Comment by danielhuppmann** [comment]
thanks @lheagy, @Chilipp and @jtmiclat for the useful feedback and positive reviews.

@gidden is on an extended Christmas break and I'd rather wait for his return with making a new release and generating the doi. We'll get back to you mid-January at the latest.

**Comment by danielhuppmann** [comment]
@lheagy, the stable doi for the project on zenodo is 
[10.5281/zenodo.1470400](https://doi.org/10.5281/zenodo.1470400), the doi for the latest release is [10.5281/zenodo.1491662](https://doi.org/10.5281/zenodo.1491662).

There are a few minor updates since release 0.1.2 (also thanks to issues raised and comments by @Chilipp), but nothing critical, so we'll probably hold off on the next release until we get a few more features implemented.

**Comment by lheagy** [comment]
@whedon set 10.5281/zenodo.1491662 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1491662" target="_blank">10.5281/zenodo.1491662</a> is the archive.

**Comment by lheagy** [comment]
Many thanks @Chilipp and @jtmiclat for your review! and congratulations @danielhuppmann on your submission 🎉 

@arfon: this is ready to be published :tada:

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/427

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/427, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/428
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01095](https://doi.org/10.21105/joss.01095)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@jtmiclat, @Chilipp - many thanks for your reviews here and to @lheagy for editing this submission ✨ 

@gidden - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01095/status.svg)](https://doi.org/10.21105/joss.01095)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01095">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01095/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01095/status.svg
   :target: https://doi.org/10.21105/joss.01095
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01095/status.svg)](https://doi.org/10.21105/joss.01095)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by gidden** [comment]
Thank you all!!
