### ISSUE TITLE
[PRE REVIEW]: finreportr - Financial Data from U.S. Securities and Exchange Commission

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#110]
**Submitting author:** @sewardlee337 (<a href="http://orcid.org/0000-0001-5583-035X">Seward Lee</a>)
**Repository:** <a href="https://github.com/sewardlee337/finreportr" target ="_blank">https://github.com/sewardlee337/finreportr</a>
**Version:** v1.0.1
**Editor:** @arfon
**Reviewer:** @jsta

**What this issue is for**

Thanks for submitting your paper to JOSS sewardlee337. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @sewardlee337, thanks for submitting this package to JOSS. Before we get started finding an editor and reviewer could you confirm that this software has a research application? In particular, our submission guidelines state:

> - Should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler)

What is the research challenge that this software is designed to address?

**Comment by sewardlee337** [comment]
@arfon thank you for prepping my package for review!

My package contributes to research in empirical finance by automating the download of data relating to financial health and transactions of publicly-listed companies, thus speeding-up and simplifying the financial research workflow. 

My paper summary has been updated accordingly.

**Comment by arfon** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current JOSS editors:

```
@acabunoc
@arfon
@biorelated
@cMadan
@danielskatz
@jakevdp
@karthik
@katyhuff
@Kevin-Mattheus-Moerman
@kyleniemeyer
@labarba
@mgymrek
@pjotrp
@tracykteal
```

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by arfon** [comment]
:wave: @jsta - do you think you'd be able to review this submission? It's in R and looks to be some kind of API client library.

**Comment by jsta** [comment]
Yes, I can review this.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @jsta as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jsta

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/119. Feel free to close this issue now!
