### ISSUE TITLE
[PRE REVIEW]: sierra-local: A lightweight standalone application for drug resistance prediction

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1100]
**Submitting author:** @ArtPoon (<a href="http://orcid.org/0000-0003-3779-154X">Art Poon</a>)
**Repository:** <a href="https://github.com/PoonLab/sierra-local" target ="_blank">https://github.com/PoonLab/sierra-local</a>
**Version:** v0.1.2
**Editor:** @pjotrp
**Reviewers:** @azneto 

**Author instructions**

Thanks for submitting your paper to JOSS @ArtPoon. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ArtPoon if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @george-githinji it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@george-githinji) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @george-githinji - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01100/joss.01100/10.21105.joss.01100.pdf)

**Comment by ArtPoon** [comment]
* The table exceeds page margins and some entries are running together.  I've added some `<br/>` tags in the table to try to improve this formatting.
* Journal titles are inconsistently abbreviated, and there was no automatic adjustment of capitalization.  I have manually edited the title entries to make this consistent throughout the reference list.

**Comment by ArtPoon** [comment]
Edits in commit https://github.com/PoonLab/sierra-local/commit/f30e5603a2e8ae310790062091cd877cbd6e31cc

**Comment by ArtPoon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01100/joss.01100/10.21105.joss.01100.pdf)

**Comment by ArtPoon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01100/joss.01100/10.21105.joss.01100.pdf)

**Comment by kyleniemeyer** [comment]
@george-githinji can you edit this submission? Thanks!

**Comment by george-githinji** [comment]
Thank you @azneto @betteridiot.
 @pjotrp would you mind taking this on as an editor?

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
Thanks @ArtPoon, this is an interesing submission. @azneto do you mind being the primary reviewer? No rush.

**Comment by azneto** [comment]
Sure, @pjotrp. I've just started reviewing it.

**Comment by pjotrp** [comment]
@whedon assign @azneto  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @azneto

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1186. Feel free to close this issue now!
