### ISSUE TITLE
[PRE REVIEW]: estez: Create and Query a Local Copy of GenBank in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1101]
**Submitting author:** @dombennett (<a href="http://orcid.org/0000-0003-2722-1359">Dominic Bennett</a>)
**Repository:** <a href="https://github.com/ropensci/restez" target ="_blank">https://github.com/ropensci/restez</a>
**Version:** v1.0.0
**Editor:** @karthik
**Reviewers:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @dombennett. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dombennett if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@karthik) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01101/joss.01101/10.21105.joss.01101.pdf)

**Comment by arfon** [comment]
@DomBennett - could you link to the rOpenSci onboarding thread here please?

Also, please take a look a the preview PDF - I think there needs to be a space between the `#` and your headers.

**Comment by DomBennett** [comment]
Hi @arfon,

I've updated the headers and I've switched the image insertion from html to markdown (there was no figure in the pdf proof).

ROpenSci onboarding thread: https://github.com/ropensci/onboarding/issues/232

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01101/joss.01101/10.21105.joss.01101.pdf)

**Comment by arfon** [comment]
@DomBennett does this look OK? ☝️

**Comment by DomBennett** [comment]
@arfon better! But I didn't realise the figure caption was generated from the image caption. I've updated the paper to reflect this. I've also changed the code snippets for R syntax highlighting.

Can I ask whedon to re-compile?

@whedon generate pdf

**Comment by DomBennett** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01101/joss.01101/10.21105.joss.01101.pdf)

**Comment by DomBennett** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01101/joss.01101/10.21105.joss.01101.pdf)

**Comment by DomBennett** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01101/joss.01101/10.21105.joss.01101.pdf)

**Comment by DomBennett** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01101/joss.01101/10.21105.joss.01101.pdf)

**Comment by DomBennett** [comment]
@arfon sorry, my error! Had to do a bit of wrangling of the markdown to get the figure placement correct.

I'm now happy with it. Thanks!

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1102. Feel free to close this issue now!
