### ISSUE TITLE
[PRE REVIEW]: The SuiteSparse Matrix Collection Website Interface

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1105]
**Submitting author:** @ScottKolo (<a href="http://orcid.org/0000-0001-8340-0824">Scott Kolodziej</a>)
**Repository:** <a href="https://github.com/ScottKolo/suitesparse-matrix-collection-website" target ="_blank">https://github.com/ScottKolo/suitesparse-matrix-collection-website</a>
**Version:** JOSS-1.0.0
**Editor:** @jedbrown
**Reviewers:** @dblarremore, @tkonolige

**Author instructions**

Thanks for submitting your paper to JOSS @ScottKolo. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ScottKolo if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jedbrown it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@jedbrown) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01105/joss.01105/10.21105.joss.01105.pdf)

**Comment by ScottKolo** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

```

**Comment by ScottKolo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01105/joss.01105/10.21105.joss.01105.pdf)

**Comment by ScottKolo** [comment]
Hello, I just made a few tweaks to the paper bibliography to fix some formatting issues and had the PDF regenerated to reflect the changes.

Can I ask about the status of our submission? Do you need anything further on our end? I know the holidays kind of slow things down, I just wanted to see if we are still in pre-review.

Thank you!

**Comment by jedbrown** [comment]
I'm waiting to hear back from potential reviewers. This submission is a bit unusual for JOSS in that the code is not itself research (though it represents significant effort and is important for facilitating research), but I think it's still fair to review according to the usual criteria. Feel free to make suggestions for potential reviewers.

**Comment by jedbrown** [comment]
@whedon add @dblarremore as reviewer

**Comment by whedon** [comment]
OK, @dblarremore is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @tkonolige as reviewer

**Comment by whedon** [comment]
OK, @tkonolige is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1244. Feel free to close this issue now!
