### ISSUE TITLE
[REVIEW]: AnyPyTools: A Python package for reproducible research with the AnyBody Modeling System.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1108]
**Submitting author:** @melund (<a href="http://orcid.org/0000-0001-9920-4051">Morten Enemark Lund</a>)
**Repository:** <a href="https://github.com/AnyBody-Research-Group/AnyPyTools" target ="_blank">https://github.com/AnyBody-Research-Group/AnyPyTools</a>
**Version:** 1.0.0
**Editor:** @trallard
**Reviewer:** @tonygon, @acolum
**Archive:** <a href="https://doi.org/10.5281/zenodo.2450121" target="_blank">10.5281/zenodo.2450121</a>

## Status

[![status](http://joss.theoj.org/papers/03757b9d4a0d730af5d712006c762719/status.svg)](http://joss.theoj.org/papers/03757b9d4a0d730af5d712006c762719)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/03757b9d4a0d730af5d712006c762719"><img src="http://joss.theoj.org/papers/03757b9d4a0d730af5d712006c762719/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/03757b9d4a0d730af5d712006c762719/status.svg)](http://joss.theoj.org/papers/03757b9d4a0d730af5d712006c762719)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/AnyBody-Research-Group/AnyPyTools" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@tonygon & @marcopus & @acolum, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @trallard know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/AnyBody-Research-Group/AnyPyTools">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0.0)?
- [x] **Authorship:** Has the submitting author (@melund) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/AnyBody-Research-Group/AnyPyTools">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0.0)?
- [x] **Authorship:** Has the submitting author (@melund) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @tonygon, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01108/joss.01108/10.21105.joss.01108.pdf)

**Comment by trallard** [comment]
Hi reviewers and @melund! This is the issue we will be using to conduct the review. 
@tonygon, @marcopus, @acolum each of you have a checklist to guide you through the review process.

If any of you encounters any issues / need any guidance during the review process feel free to ping me here 👩🏻‍💻

**Comment by melund** [comment]
Thanks, @trallard. I am really looking forward to the review process here :)

**Comment by acolum** [comment]
Just completed my review!
The paper, documentation, and code were all excellent, and I was glad to check off all of the requirements above.

**Comment by trallard** [comment]
Great, thanks for that speedy review @acolum. I will just wait for  @tonygon and @marcopus 's reviews

**Comment by melund** [comment]
@trallard. I just browsed the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and I think one of the reviewers I suggested could cause a problem. I knew one of my supervisors (Michael Skipper Andersen @msna) had worked with @marcopus in the past but didn't realize that the also recently (2017) co-authored a paper. 

I am sorry about that. But I think that disqualifies @marcopus as a reviewer.

**Comment by trallard** [comment]
hey @melund  thanks for double checking. I am going to then remove @marcopus  (apologies). Is @tonygon still a suitable reviewer?

**Comment by tonygon** [comment]
> hey @melund thanks for double checking. I am going to then remove @marcopus (apologies). Is @tonygon still a suitable reviewer?

@trallard My apologies for the delay. As I mentioned to Morten before agreeing, I'm able to do the review, I work with AnyPython tools and AnyBody, I used both regularly for a project.
But, I'm in the transition between jobs, so time is a bit limited ;)
Since we have holidays by the end of the week I will finish the review then.
I already know/did most of all AnyPython tools part, I just need to seat down and finish the formal procedure from the JOSS side.

I hope there is still time.
Cheers!

**Comment by tonygon** [comment]
@trallard 
Just finished checking the JOSS requirements)
Thanks for the patience!
And continue the great work @melund!!

Cheers!

**Comment by trallard** [comment]
@tonygon thanks for your review and hope you had a nice holiday season 

---
@melund now that the reviews are completed and the paper has been recommended for acceptance, we need you to complete the following actions:

- [ ]  make a new release of the package (unless the latest release is up to date with the recent modifications)

- [ ]  upload the revised software to your DOI-granting data/software repository, and post the DOI here

- [ ] double check the submission paper to ensure it is up-to-date 

Once these tasks are completed I can finalise the editorial tasks

**Comment by melund** [comment]
Thanks a lot @trallard. I have finished the remaining tasks. 

> - [x] make a new release of the package (unless the latest release is up to date with the recent modifications)
>
> - [x] upload the revised software to your DOI-granting data/software repository, and post the DOI here
>
> - [x] double check the submission paper to ensure it is up-to-date

The library is achived with Zenodo and the DOI for version 1.0.1 is: 

**10.5281/zenodo.2450121**

**Comment by trallard** [comment]
@whedon commands

**Comment by trallard** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01108/joss.01108/10.21105.joss.01108.pdf)

**Comment by trallard** [comment]
@whedon set 10.5281/zenodo.2450121 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2450121" target="_blank">10.5281/zenodo.2450121</a> is the archive.

**Comment by melund** [comment]
@trallard PDF looks good :)

**Comment by trallard** [comment]
@melund all looks good to me so I will proceed with the acceptance recommendation

@arfon: this submission is accepted and ready to be published 🎉👾

@tonygon @acolum  thank you very much for your time and valuable contribution to JOSS as reviewers for this submission 🙌🏻

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/425

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/425, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/426
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01108](https://doi.org/10.21105/joss.01108)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by melund** [comment]
Woohoo... Awesome, it is online. Thanks a lot everyone...

**Comment by arfon** [comment]
@tonygon, @acolum - many thanks for your reviews and to @trallard for editing this submission ✨ 

@melund - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01108/status.svg)](https://doi.org/10.21105/joss.01108)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01108">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01108/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01108/status.svg
   :target: https://doi.org/10.21105/joss.01108
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01108/status.svg)](https://doi.org/10.21105/joss.01108)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
