### ISSUE TITLE
[REVIEW]: gtk-fortran: a GTK+ binding to build Graphical User Interfaces in Fortran

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1109]
**Submitting author:** @vmagnin (<a href="http://orcid.org/0000-0002-9016-9955">Vincent MAGNIN</a>)
**Repository:** <a href="https://github.com/jerryd/gtk-fortran" target ="_blank">https://github.com/jerryd/gtk-fortran</a>
**Version:** v17.10
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @johnsamuelwrites, @sundmanbo
**Archive:** <a href="https://doi.org/10.5281/zenodo.2544192" target="_blank">10.5281/zenodo.2544192</a>

## Status

[![status](http://joss.theoj.org/papers/33eda34ec9fd549844fb43ca28dd879a/status.svg)](http://joss.theoj.org/papers/33eda34ec9fd549844fb43ca28dd879a)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/33eda34ec9fd549844fb43ca28dd879a"><img src="http://joss.theoj.org/papers/33eda34ec9fd549844fb43ca28dd879a/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/33eda34ec9fd549844fb43ca28dd879a/status.svg)](http://joss.theoj.org/papers/33eda34ec9fd549844fb43ca28dd879a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jerryd/gtk-fortran" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@johnsamuelwrites & @sundmanbo, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jerryd/gtk-fortran">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v17.10)?
- [x] **Authorship:** Has the submitting author (@vmagnin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jerryd/gtk-fortran">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v17.10)?
- [x] **Authorship:** Has the submitting author (@vmagnin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @johnsamuelwrites, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01109/joss.01109/10.21105.joss.01109.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@johnsamuelwrites, @devonrex, @sundmanbo this is where the review takes place. There are tick boxes at the top if this issue to guide you through the process. Please let me know if you have any questions. Thanks! :robot: :rocket:

**Comment by sundmanbo** [comment]
Hi Kevin

I am not sure this is the right way to conatct you
but I am very unhappy about whedon/JOSS sending me a lot of emails about
the reviewing of papers I am not involved in.
How do I stop that?

Bo Sundman



Den tors 29 nov. 2018 kl 10:32 skrev Kevin Mattheus Moerman <
notifications@github.com>:

**Comment by Kevin-Mattheus-Moerman** [comment]
@sundmando yes that is annoying. The to of this issue contains instructions to avoid this. I.e. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews. Let me know if you need more help.

**Comment by sundmanbo** [comment]
Yes I need more help.  Where do I find a "No watching" button?


Den lör 1 dec. 2018 kl 11:41 skrev Kevin Mattheus Moerman <
notifications@github.com>:

**Comment by arfon** [comment]
> Yes I need more help.  Where do I find a "No watching" button?

@sundmanbo - if you might want to change your settings in your GitHub profile [here](https://github.com/settings/notifications) to stop emails being sent:

![](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)

**Comment by johnsamuelwrites** [comment]
@Kevin-Mattheus-Moerman @vmagnin v17.10 is the specified version for the journal. gtk-fortran follows a different versioning scheme, making use of the gtk version as well. For example: https://github.com/jerryd/gtk-fortran/releases shows v17.10.gtk3.22.25 and v17.10.gtk2.24.31. Is it possible to specify these two versions?

**Comment by vmagnin** [comment]
> @Kevin-Mattheus-Moerman @vmagnin v17.10 is the specified version for the journal. gtk-fortran follows a different versioning scheme, making use of the gtk version as well. For example: https://github.com/jerryd/gtk-fortran/releases shows v17.10.gtk3.22.25 and v17.10.gtk2.24.31. Is it possible to specify these two versions?

Each version of gtk-fortran is numbered using the Ubuntu version used to build it, for example 17.10: but each release comprises a GTK+ 2 version and a GTK+3 version. And 3.22.25 and 2.24.31 are the precise GTK+ versions used to build gtk-fortran.

**Comment by Kevin-Mattheus-Moerman** [comment]
Happy New Year to all!

**Comment by Kevin-Mattheus-Moerman** [comment]
@johnsamuelwrites, @devonrex, @sundmanbo can you provide an update on the review process? Let me know if I can help with anything. Thanks.

**Comment by sundmanbo** [comment]
Hi Kevin

I have finished my review and accept the software.  But I had big problems
receiving a lot of messages from reviews of other papers and had to turn
off some obscure feedback buttons inside GITHUB not be be overloaded by
emails.  So maybe I did not finish the review properly.

Best wishes

Bo Sundman


Den fre 4 jan. 2019 kl 11:31 skrev Kevin Mattheus Moerman <
notifications@github.com>:

**Comment by Kevin-Mattheus-Moerman** [comment]
@vmagnin can you work on / formulate a reply to @johnsamuelwrites 's comments? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@devonrex are you able to review this software soon? Thanks

**Comment by vmagnin** [comment]
@Kevin-Mattheus-Moerman 

Thank you @johnsamuelwrites for that review. Concerning your three final comments:

1. I clicked on the link 'How to use GTK-Fortran with Code::Blocks IDE' on two different PCs today and it works fine. Perhaps there was a server problem the day you try it ?

2. A quick start tutorial is a good idea and I can work on it during the next months.

3. Fully automating the test run could be a long term project. I guess there is applications to test softwares with GUI, but I have no experience of that kind of software.  If you have some idea on how it could be done, I am interested.

Finally, I can say that such a review process is very interesting because users generally only post bug reports or questions on how to do something with the soft, but there is very rarely comments or critics or even requests concerning the documentation of the soft.

**Comment by johnsamuelwrites** [comment]
@Kevin-Mattheus-Moerman @vmagnin Thanks for the response. I verified the link (review comment 1) and it's working now. Regarding review comment 3 on full automation, I am aware that it may be little difficult and may not be the immediate focus of gtk-fortran. As I mentioned in the review, the manual tests are fine, especially considering that this is a GUI building tool and some users may wish to run through all the tests manually.

**Comment by Kevin-Mattheus-Moerman** [comment]
@devonrex thanks for letting us know. I'll remove you as reviewer. For future reference the review entails downloading (e.g. the zip file for the repository if you like without using GIT) and testing the software. Then boxes are ticked at the top of this review issue. Editors are also here to help with the process. Thanks for your time.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon remove @devonrex as reviewer

**Comment by whedon** [comment]
OK, @devonrex is no longer a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01109/joss.01109/10.21105.joss.01109.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@vmagnin since both reviewers are happy with your submission I will recommend that this work is accepted in JOSS. 

At this point can you do the following: 

- [ ] Create a new release of the reviewed software and archive a version of it e.g. in a service like Zenodo (some find it convenient to use these steps: https://guides.github.com/activities/citable-code/). Once archived please list the DOI of the archived version here. 

- [ ] Please inform us on the version tag for the archived release.

**Comment by vmagnin** [comment]
Thank you @Kevin-Mattheus-Moerman 

- [X] I have created a new release (v17.10.gtk3.22.25_1).
- [ ] Concerning the DOI, I need some time to contact my coauthor @jerryd  who is the owner of the repository. It seems he is the only one who can give Zenodo the access to the repository.

**Comment by vmagnin** [comment]
@whedon generate PDF

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01109/joss.01109/10.21105.joss.01109.pdf)

**Comment by vmagnin** [comment]
Dear @Kevin-Mattheus-Moerman

I finally succeeded obtaining a DOI:
- I have asked my coauthor jerryd to transfer to me the ownership of the repository. So the new URL of gtk-fortran is https://github.com/vmagnin/gtk-fortran (instead of https://github.com/jerryd/gtk-fortran, which now redirects toward the new URL).
- I have updated that URL in the paper and have regenerated the PDF.
- I have created a new release: v17.10.gtk3.22.25_2
- And have obtained its DOI: 10.5281/zenodo.2544192

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1016/S0167-2991(08)80304-7 is OK
- http://doi.org/http://dx.doi.org/10.1016/j.apradiso.2015.12.003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon @danielskatz @kyleniemeyer @labarba I recommend we accept this work in JOSS. The new version tag and DOI are: 

> * I have created a new release: v17.10.gtk3.22.25_2
> * And have obtained its DOI: 10.5281/zenodo.2544192

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.2544192 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2544192" target="_blank">10.5281/zenodo.2544192</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1109 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@vmagnin have you removed the `paper.md` file from your repository? @whedon doesn't seem to be able to find it any longer.

**Comment by vmagnin** [comment]
@arfon The paper.md, paper.bib and paper.png files are still in the master branch of the gtk-fortran repository. But some days ago I have changed the default branch of the repository from master (gtk2) to gtk3. Perhaps @whedon is searching in the default branch. 
=> So, I have just copied and pushed the three `paper.*` files in the gtk3 branch. I hope it will solve the problem.

Another reason could be the ownership transfer one month ago from https://github.com/jerryd/gtk-fortran to https://github.com/vmagnin/gtk-fortran, but theoretically everything is automatically redirected from the old URL to the new.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01109/joss.01109/10.21105.joss.01109.pdf)

**Comment by arfon** [comment]
> @arfon The paper.md, paper.bib and paper.png files are still in the master branch of the gtk-fortran repository. But some days ago I have changed the default branch of the repository from master (gtk2) to gtk3. Perhaps @whedon is searching in the default branch.

Ah yes. @whedon only picks up files in the default branch.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1016/S0167-2991(08)80304-7 is OK
- http://doi.org/http://dx.doi.org/10.1016/j.apradiso.2015.12.003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/486

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/486, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/487
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01109](https://doi.org/10.21105/joss.01109)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@johnsamuelwrites, @sundmanbo - many thanks for your reviews and to @Kevin-Mattheus-Moerman for editing this submission ✨ 

@vmagnin - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01109/status.svg)](https://doi.org/10.21105/joss.01109)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01109">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01109/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01109/status.svg
   :target: https://doi.org/10.21105/joss.01109
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01109/status.svg)](https://doi.org/10.21105/joss.01109)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1016/S0167-2991(08)80304-7 is OK
- http://doi.org/http://dx.doi.org/10.1016/j.apradiso.2015.12.003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```
