### ISSUE TITLE
[PRE REVIEW]: CEGO: C++11 Evolutionary Global Optimization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1110]
**Submitting author:** @ianhbell (<a href="http://orcid.org/0000-0003-1091-9080">Ian Bell</a>)
**Repository:** <a href="https://github.com/usnistgov/CEGO" target ="_blank">https://github.com/usnistgov/CEGO</a>
**Version:** v1.0.0
**Editor:** @jedbrown
**Reviewers:** @sarats, @sjvrijn, @mmenickelly

**Author instructions**

Thanks for submitting your paper to JOSS @ianhbell. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ianhbell if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jedbrown it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@jedbrown) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01110/joss.01110/10.21105.joss.01110.pdf)

**Comment by arfon** [comment]
:wave: @jedbrown - the submitting author suggested you as the handling editor.

**Comment by jedbrown** [comment]
@sarats @sjvrijn :wave:  Would you be available to review this submission?

**Comment by sarats** [comment]
@jedbrown Sure, would be happy to.

**Comment by jedbrown** [comment]
@whedon add @sarats as reviewer

**Comment by whedon** [comment]
OK, @sarats is now a reviewer

**Comment by jedbrown** [comment]
Thanks, @sarats. I'll wait to hear back from another potential reviewer before starting the review issue.

**Comment by sjvrijn** [comment]
@jedbrown Yep, I'm available

**Comment by jedbrown** [comment]
@whedon add @sjvrijn as reviewer

**Comment by whedon** [comment]
OK, @sjvrijn is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @mmenickelly as reviewer

**Comment by whedon** [comment]
OK, @mmenickelly is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1147. Feel free to close this issue now!
