### ISSUE TITLE
[PRE REVIEW]: PsychroLib: a library of psychrometric functions to calculate thermodynamic properties of air

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1113]
**Submitting author:** @dmey (<a href="http://orcid.org/0000-0002-7071-7547">D. Meyer</a>)
**Repository:** <a href="https://github.com/psychrometrics/psychrolib" target ="_blank">https://github.com/psychrometrics/psychrolib</a>
**Version:** 2.0.0
**Editor:** @kyleniemeyer
**Reviewers:** @bryanwweber, @puncan

**Author instructions**

Thanks for submitting your paper to JOSS @dmey. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dmey if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1113 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    295      0 --:--:-- --:--:-- --:--:--   296
[WARNING] Could not convert image '/tmp/tex2pdf.280/94796596a57b8d2d015572f76f2a94f3213dec0a.svg': check that rsvg2pdf is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.280/94796596a57
b8d2d015572f76f2a94f3213dec0a.svg (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.249 ...6596a57b8d2d015572f76f2a94f3213dec0a.svg}

Looks like we failed to compile the PDF

**Comment by kyleniemeyer** [comment]
Hi @dmey, could you try submitting with a non-SVG figure? Perhaps PDF or PNG?

**Comment by dmey** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01113/joss.01113/10.21105.joss.01113.pdf)

**Comment by dmey** [comment]
Add padding to paper fig + fix paper refs
@whedon generate pdf

**Comment by dmey** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01113/joss.01113/10.21105.joss.01113.pdf)

**Comment by dmey** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01113/joss.01113/10.21105.joss.01113.pdf)

**Comment by dmey** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01113/joss.01113/10.21105.joss.01113.pdf)

**Comment by dmey** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01113/joss.01113/10.21105.joss.01113.pdf)

**Comment by dmey** [comment]
Hi @kyleniemeyer, thank you for pointing this out. I have changed the format to PDF but I am having issues with its placement -- see my last proof. The image ends up on page 2 even though there is enough space to position it on page 1.

Also, a couple of other things that I have noticed that may be worth addressing in the documentation (https://joss.readthedocs.io/en/latest/submitting.html):

- Add a supported media-formats section.
- Explain how to resize figures (if at all possible)
- Explain how to force figure placement in text (if at all possible) a bit like in this case -- the `H` option in LaTeX.

Beside this, I have only received a notification of this issues when you mentioned me but none when `@whedon` open the issue. Is this the expected behaviour?

If you want, I can move any of the above to a separate issue if you think that's necessary/easier for you to handle. Thanks.

**Comment by danielskatz** [comment]
👋 @kyleniemeyer - I think you might be the closest editor for this topic - are you willing to handle it?

**Comment by kyleniemeyer** [comment]
Yes, I can handle this one.

**Comment by kyleniemeyer** [comment]
@whedon set @kyleniemeyer as editor

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
@bryanwweber do you have the bandwidth to review this? Looks similar to stuff you've worked on (and teach 😄 )

**Comment by bryanwweber** [comment]
@kyleniemeyer Sure, would be happy to!

**Comment by kyleniemeyer** [comment]
@whedon add @bryanwweber as reviewer

**Comment by whedon** [comment]
OK, @bryanwweber is now a reviewer

**Comment by kyleniemeyer** [comment]
@dmey I am going to find a second reviewer; any suggestions are welcome, though I have a few colleagues I will ask.

**Comment by dmey** [comment]
Thank you both, @kyleniemeyer and @bryanwweber.
@kyleniemeyer, looking at the list of JOSS reviewers, `andreas-h`/`katyhuff`/`wholmgren` looked like they may be appropriate but if you had other colleagues in mind or you can ask that's really good too! Thanks for asking!

**Comment by dmey** [comment]
Is everyone OK if I move the figure placement issue -- i.e. force the position of a figure so that it does not end up in between the reference section -- to https://github.com/openjournals/joss/issues?

**Comment by bryanwweber** [comment]
@dmey Rather than using `H` to force the figure placement on the first page, you could consider moving the image up the page, to before the first paragraph and see what happens.

**Comment by dmey** [comment]
@whedon generate pdf from dmey/paper

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01113/joss.01113/10.21105.joss.01113.pdf)

**Comment by dmey** [comment]
@bryanwweber even when the figure is placed at the top of the page, the figure still ends up between the refs. I'll open an issue then.

**Comment by dmey** [comment]
@whedon generate pdf from dmey/paper

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01113/joss.01113/10.21105.joss.01113.pdf)

**Comment by dmey** [comment]
@whedon generate pdf from dmey/paper

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01113/joss.01113/10.21105.joss.01113.pdf)

**Comment by arfon** [comment]
@dmey - the command to compile from a different branch doesn't seem to be working.

**Comment by dmey** [comment]
@arfon I was just getting back to you in the issue about this. I think there are two issues here then. One with the `generate from` command to use for testing and the other with the actual figure placement.

**Comment by dmey** [comment]
@arfon can you manually set the branch to `dmey/paper` so that we can use it to sort out these draft and during review? For the `generate from` command issue, I noticed that there is already openjournals/joss#471 open. Thanks.

**Comment by arfon** [comment]
Sure, I can compile locally. Here's the current output of `dmey/paper`: [10.21105.joss.01113.pdf](https://github.com/openjournals/joss-reviews/files/2654212/10.21105.joss.01113.pdf)

**Comment by dmey** [comment]
@arfon sorry but I meant if you can set `@whedon` to track `dmey/paper` as the default branch instead of `master` for now on so that we can carry out the review there and we would also not have to rely on the `generate from` command which is currently not working -- I would like to keep `master` tidy.

**Comment by arfon** [comment]
Whedon can’t do that sorry.

**Comment by dmey** [comment]
@whedon generate pdf from "dmey/paper"

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01113/joss.01113/10.21105.joss.01113.pdf)

**Comment by dmey** [comment]
@whedon generate pdf from branch dmey/paper

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01113/joss.01113/10.21105.joss.01113.pdf)

**Comment by dmey** [comment]
@whedon generate pdf from branch dmey/paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch dmey/paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01113/joss.01113/10.21105.joss.01113.pdf)

**Comment by dmey** [comment]
@whedon generate pdf from branch dmey/paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch dmey/paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01113/joss.01113/10.21105.joss.01113.pdf)

**Comment by dmey** [comment]
@whedon generate pdf from branch dmey/paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch dmey/paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01113/joss.01113/10.21105.joss.01113.pdf)

**Comment by dmey** [comment]
@arfon the branch issue doesn't appear to be an issue after all -- silly me, I was using `generate pdf from <branch_name>` instead of `generate pdf from branch <branch_name>`... 😬. For reference though it may still be good to handle invalid commands in whedon.

I'd say that the latest formatting is now acceptable to review -- perhaps there may be other changes that can be addressed during the review process. If there are no issues with anyone, I would therefore keep the latest version of the paper under the `dmey/paper` branch.

**Comment by dmey** [comment]
Hi @kyleniemeyer, just wondering if you've heard anything back from any of the reviewers you had in mind. Thanks.

**Comment by kyleniemeyer** [comment]
@whedon add @puncan as reviewer

**Comment by whedon** [comment]
OK, @puncan is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1137. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
ok @dmey @bryanwweber @puncan we are done with this pre-review issue, and we'll move over to #1137 for the actual review.
