### ISSUE TITLE
[PRE REVIEW]: rdbsp: An Open Source Rock Dynamic Behavior Simulation Program

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1114]
**Submitting author:** @zhangning737 (<a href="http://orcid.org/0000-0003-3597-0691">Zhang Ning</a>)
**Repository:** <a href="https://github.com/zhangning737/rdbsp.git" target ="_blank">https://github.com/zhangning737/rdbsp.git</a>
**Version:** v1.0.0
**Editor:** @lheagy
**Reviewers:** @dvalters

**Author instructions**

Thanks for submitting your paper to JOSS @zhangning737. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@zhangning737 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01114/joss.01114/10.21105.joss.01114.pdf)

**Comment by danielskatz** [comment]
@whedon set https://github.com/zhangning737/rdbsp as repository

**Comment by danielskatz** [comment]
👋  @zhangning737 - there is going to need to be quite a bit more information in the README.  For example, I was going to use that to assign an editor, which I can't do without having some idea what this software does.  Some of the content from the paper probably needs to be copied into the README.  You also might want to look at the [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html) (see documentation) to see what else you should be adding.

**Comment by danielskatz** [comment]
👋 @lheagy - I think you are the best-suited editor for this submission - can you handle it?

**Comment by lheagy** [comment]
Thanks @danielskatz: I don't have much experience with C / C++ , but I would be happy to be the editor on this submission

**Comment by lheagy** [comment]
@whedon assign @lheagy as editor

**Comment by whedon** [comment]
OK, the editor is @lheagy

**Comment by lheagy** [comment]
👋 Hi @zhangning737, thanks for your submission to JOSS. Before we send this out for review, please have a look at the [JOSS review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html). Specifically,
- [ ] an [OSI approved license](https://opensource.org/licenses/alphabetical) needs to be included in the repository 
- [ ] documentation for the software should be provided. This should include
    - [ ] a statement of need
    - [ ] installation instructions
    - [ ] example usage
    - [ ] API documentation
    - [ ] community guidelines
    - [ ] functionality
    - [ ] tests
- [ ] the README should include a high level overview of the documentation that includes

Please have a look as some of the other accepted JOSS submissions, e.g.:
- [Ising_OPV v4.0: Experimental Tomography Data Import, Interpretation, and Analysis](http://joss.theoj.org/papers/0b6b9d572386a1520d3c6eff4563d22c)
- [Lithology: A Landlab submodule for spatially variable rock properties](http://joss.theoj.org/papers/74487c5a6820fb2fe2898960ad6d2ea0)

For now, I will tag this submission as pending enhancements. Please keep me posted on your progress and once these items are addressed, we can work on finding reviewers.

**Comment by lheagy** [comment]
👋 Hi @zhangning737, just checking in. Do you intend to make the changes suggested above? If so, I will leave this issue open. If not, I will close this and you can always re-open the issue and re-start the submission when these items are addressed

**Comment by lheagy** [comment]
:wave: Hi again @zhangning737, just checking in after the holidays. Do you plan to make the suggested changes as listed above? Thank you!

**Comment by lheagy** [comment]
👋 Hi @zhangning737, checking in again. Are you planning to make the changes as suggested above? If so, please leave a comment here to let me know.

**Comment by zhangning737** [comment]
@lheagy thank you for you message. I will prepare it now.

**Comment by zhangning737** [comment]
@lheagy update the repo with documentation and READ.md. pls check it. I will those qualified. Any else needed?

**Comment by lheagy** [comment]
Thanks @zhangning737, I will take a look in the next couple of days.

**Comment by lheagy** [comment]
Thanks for your updates @zhangning737, there are still a few things that I did not see:
- [ ]  an explanation of how to run an example
- [ ] an explanation of how to run the tests. Note that the tests need to be distinct from the example usage. Tests should provide some objective way to make sure that the code is functioning as expected. 
- [ ] a statement of need should be included in the README (the intro of your paper contains good motivation, so this can essentially be used 
- [ ] community guidelines (e.g. along the lines of https://github.com/MikeHeiber/Ising_OPV/blob/master/CONTRIBUTING.md) 

Please let me know when you have had a chance to address these

**Comment by zhangning737** [comment]
@lheagy OK, I'll check and revise the docs.

**Comment by lheagy** [comment]
Thanks @zhangning737, please ping here when you have made the changes.

**Comment by zhangning737** [comment]
@lheagy taken days for reediting tests and examples, fixed.

I have submited new tests and example and add to documentation, also updated README and CONTRIBUTING. pls check it.

Thx. 

Wish docs completed this time.

**Comment by lheagy** [comment]
👋 Hi @dvalters, @trallard, would you be willing to review this submission for JOSS?

**Comment by dvalters** [comment]
Hi @lheagy :wave:, sure, I can review this.

**Comment by lheagy** [comment]
@whedon assign @dvalters as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dvalters

**Comment by lheagy** [comment]
Many thanks @dvalters! I will wait to hear back from @trallard before starting the review.

**Comment by trallard** [comment]
Hi @lheagy I am sorry but I have other two reviews in process and I do not have the time now to take up on a third one

**Comment by lheagy** [comment]
Hi @trallard, no problem. Thanks for getting back to me. Best of luck with your other reviews!

**Comment by lheagy** [comment]
:wave: Hi @harpolea, would you be willing to review this submission for JOSS?

**Comment by harpolea** [comment]
Hi @lheagy, I'm afraid I'm going to be busy travelling this month, so do not think I'd have the necessary time to review this properly (especially as I only have limited access to machines with the Intel compilers required). I also do not have much experience with finite element codes or solid mechanics, so do not think I'd be the best person to look at this.

**Comment by lheagy** [comment]
Thanks for getting back to me @harpolea. Safe travels!

**Comment by lheagy** [comment]
👋 Hi @nnadeau, would you be willing to review this submission for JOSS?

**Comment by nnadeau** [comment]
hi @lheagy, unfortunately i'm not available at this time

**Comment by dvalters** [comment]
Is this something @sgrieve might be available to review?

**Comment by sgrieve** [comment]
I'm afraid I don't have time at present, I'm about to do a block of field teaching. If you can't find anyone else give me a shout in 2 weeks and I'll see what I can do.

**Comment by lheagy** [comment]
Thanks @sgrieve, I will start the review process now with @dvalters as the reviewer so he can get started. If I can't find someone else in the next two weeks, I will check in with you again.

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1328. Feel free to close this issue now!
