### ISSUE TITLE
[PRE REVIEW]: swsc: A sitewise UCE partitioner

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1116]
**Submitting author:** @RHagenson (<a href="http://orcid.org/0000-0001-9750-1925">Ryan Hagenson</a>)
**Repository:** <a href="https://bitbucket.org/RHagenson/swsc/" target ="_blank">https://bitbucket.org/RHagenson/swsc/</a>
**Version:** v6.0.1
**Editor:** @pjotrp
**Reviewers:** @urbanslug

**Author instructions**

Thanks for submitting your paper to JOSS @RHagenson. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@RHagenson if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @pjotrp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@pjotrp) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
👋 @pjotrp - the submitting author suggested you as the handling editor.

**Comment by RHagenson** [comment]
I placed the `paper.md` and `paper.bib` under a directory called `paper/`, if that is a problem I can easily move it to the root of the repo. Used an accepted paper as reference for how to layout the source.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01116/joss.01116/10.21105.joss.01116.pdf)

**Comment by RHagenson** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

```

**Comment by RHagenson** [comment]
May I request updating the version under review to v6.1.0? A collaborator of mine found that in large datasets the PartitionFinder2 output can have overlapping flanks between UCEs. This error is fixed in v6.1.0.

**Comment by pjotrp** [comment]
Sure thing. I am still trying to find a reviewer.

**Comment by RHagenson** [comment]
Thank you. Happy holidays!

**Comment by pjotrp** [comment]
@whedon assign @urbanslug as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @urbanslug

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1146. Feel free to close this issue now!
