### ISSUE TITLE
[PRE REVIEW]: Cadabra2: computer algebra for field theory revisited

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1117]
**Submitting author:** @kpeeters (<a href="http://orcid.org/0000-0002-3077-8193">Kasper Peeters</a>)
**Repository:** <a href="https://github.com/kpeeters/cadabra2" target ="_blank">https://github.com/kpeeters/cadabra2</a>
**Version:** 2.2.2
**Editor:** @danielskatz
**Reviewers:** @StewMH, @henrik227

**Author instructions**

Thanks for submitting your paper to JOSS @kpeeters. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@kpeeters if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1117 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@kpeeters - you should put the paper contents (md, bib) in a paper directory, then add a new comment here with the line 
```@whedon generate pdf```
to build it

**Comment by kpeeters** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01117/joss.01117/10.21105.joss.01117.pdf)

**Comment by danielskatz** [comment]
It looks like there might be some reference issue that you can clean up, but we should also start getting reviewers.  Do you have any suggestions for potential reviewers? [This list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable.

**Comment by kpeeters** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01117/joss.01117/10.21105.joss.01117.pdf)

**Comment by kpeeters** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kpeeters** [comment]
Am fixing the refs (is there a recommended tool to generate pdf locally?).

Will have a scan through that list, will get back to you asap.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01117/joss.01117/10.21105.joss.01117.pdf)

**Comment by danielskatz** [comment]
https://github.com/openjournals/joss/issues/379 might be helpful for understanding the paper generation process

👋 @arfon - maybe we need to move some of this into our docs, rather than leaving it as an issue?

**Comment by kpeeters** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01117/joss.01117/10.21105.joss.01117.pdf)

**Comment by kpeeters** [comment]
@arfon @danielskatz Definitely put that in your docs please.

**Comment by kpeeters** [comment]
As for reviewer suggestions: andrewfowlie, StewMH, rljacobson, moorepants, henrik227.

**Comment by danielskatz** [comment]
👋 @andrewfowlie, @StewMH, @moorepants, @henrik227

Would any of you be willing to review this JOSS submission?

**Comment by danielskatz** [comment]
@kpeeters - do all the references that have DOIs lists them in the bib?

**Comment by StewMH** [comment]
Hi @danielskatz,

I'd be happy to review this - my first time as a reviewer.

Cheers,
Stewart

**Comment by kpeeters** [comment]
@danielskatz Will check all entries to see if any DOIs can be added (not a very common way to cite in my field).

**Comment by andrewfowlie** [comment]
Hi @danielskatz,

my partner and I have just had a baby so I'm afraid I can't help. I recommend my colleague Peter Athron -  http://inspirehep.net/author/profile/P.Athron.1, github user name pathron

best,

Andrew

**Comment by henrik227** [comment]
Hi @danielskatz,

I can review this too.

Henrik

**Comment by danielskatz** [comment]
Thanks @StewMH and @henrik227 - I'll add you and start the review

**Comment by danielskatz** [comment]
@whedon assign @StewMH as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @StewMH

**Comment by danielskatz** [comment]
@whedon add @henrik227 as reviewer

**Comment by whedon** [comment]
OK, @henrik227 is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1118. Feel free to close this issue now!
