### ISSUE TITLE
[PRE REVIEW]: Multilocus sequence typing by blast from de novo assemblies against PubMLST

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#112]
**Submitting author:** @andrewjpage (<a href="http://orcid.org/0000-0001-6919-6062">Andrew Page</a>)
**Repository:** <a href="https://github.com/sanger-pathogens/mlst_check" target ="_blank">https://github.com/sanger-pathogens/mlst_check</a>
**Version:** v2.1.1630910
**Editor:** @pjotrp
**Reviewer:** @harmn

**What this issue is for**

Thanks for submitting your paper to JOSS @andrewjpage. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @pjotrp. Would you be willing to edit this submission?

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by andrewjpage** [comment]
Hi,
I would like to suggest @happykhan as a reviewer. He is a software developer who works for Mark Achtman (who created MLST) and he has substantial experience in large scale MLST pipelines such as http://enterobase.warwick.ac.uk/

Andrew

**Comment by pjotrp** [comment]
@whedon assign @harmn as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @harmn

**Comment by pjotrp** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/118. Feel free to close this issue now!

**Comment by pjotrp** [comment]
@happykhan: feel free to pitch in with review
