### ISSUE TITLE
[PRE REVIEW]: scikit-posthocs: Pairwise multiple comparison tests in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1120]
**Submitting author:** @maximtrp (<a href="http://orcid.org/0000-0003-2586-4633">Maksim Terpilowski</a>)
**Repository:** <a href="https://github.com/maximtrp/scikit-posthocs" target ="_blank">https://github.com/maximtrp/scikit-posthocs</a>
**Version:** 0.4.0
**Editor:** @katyhuff
**Reviewers:** mnarayan, @djmitche

**Author instructions**

Thanks for submitting your paper to JOSS @maximtrp. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@maximtrp if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01120/joss.01120/10.21105.joss.01120.pdf)

**Comment by maximtrp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01120/joss.01120/10.21105.joss.01120.pdf)

**Comment by arfon** [comment]
:wave: @katyhuff - would you be willing to edit this submission for JOSS?

**Comment by danielskatz** [comment]
👋 @katyhuff - ping...

**Comment by katyhuff** [comment]
I'm afraid I'm not able to contribute until January 1.

**Comment by danielskatz** [comment]
@katyhuff - that's fine - I'll go ahead and assign this to you, and assume that you'll start it in the new year.

**Comment by danielskatz** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by katyhuff** [comment]
Hi @maximtrp thanks for this submission. I'm sorry for the delay. I'm back in action now. Now, @maximtrp , let's ping a few fitting reviewers, with computational statistics and python expertise. We can start the review once two or three of them accept the request to review.

----

Dear potential reviewers (@djmitche @kellieotto @mnarayan @acolum ),

Based on your expertise in computational statistics and python, I would like to ask if you can help us out with a submission to JOSS (The Journal of Open Source Software), where I’m an editor. 

Title: Scikit-posthocs
Summary: scikit-posthocs provides statistical post-hoc tests for pairwise multiple comparisons and outliers detection algorithms. https://scikit-posthocs.readthedocs.io/
Topic: Computational Statistics, automated comparison plotting, scikit ecosystem, etc. 
Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01120/joss.01120/10.21105.joss.01120.pdf
Submitting author: @maxheld83 (Maksim Terpilowski)
Repository: https://github.com/maximtrp/scikit-posthocs
Version: v0.4.0

@djmitche : Dustin, are you able to and interested in taking on this review?
@kellieotto : Kellie, are you able to and interested in taking on this review?
@mnarayan : Manjari, are you able to and interested in taking on this review?
@acolum : Alyssa, are you able to and interested in taking on this review?

Your prompt response is appreciated. Please see https://joss.readthedocs.io/en/latest/reviewer_guidelines.html for more information about reviewer criteria and the process if it is new to you.

**Comment by maximtrp** [comment]
Thank you, @katyhuff. Please correct the username of submitting author (it should be @maximtrp, not @maxheld83).

**Comment by katyhuff** [comment]
Sorry -- Tab completion error! Fixed.

**Comment by mnarayan** [comment]
I am happy to review this.

**Comment by katyhuff** [comment]
@whedon assign mnarayan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is mnarayan

**Comment by djmitche** [comment]
I can review too.

**Comment by katyhuff** [comment]
@whedon add @djmitche as reviewer

**Comment by whedon** [comment]
OK, @djmitche is now a reviewer

**Comment by katyhuff** [comment]
Ok - that should be enough reviewers for this paper. @kellieotto @acolum , you're off the hook!

**Comment by katyhuff** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1169. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Thanks so much for volunteering to review @djmitche and @mnarayan ! Let's go over to #1169 for the review.
