### ISSUE TITLE
[PRE REVIEW]: UWGeodynamics: A teaching an research tool for numerical geodynamic modelling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1121]
**Submitting author:** @rbeucher (<a href="http://orcid.org/0000-0003-3891-5444">Romain Beucher</a>)
**Repository:** <a href="https://github.com/underworldcode/UWGeodynamics" target ="_blank">https://github.com/underworldcode/UWGeodynamics</a>
**Version:** v1.0.0
**Editor:** @lheagy
**Reviewers:** @techas, @tth030

**Author instructions**

Thanks for submitting your paper to JOSS @rbeucher. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@rbeucher if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@lheagy) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @lheagy - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
PDF failed to compile for issue #1121 with the following error: 

 Can't find any papers to compile :-(

**Comment by lheagy** [comment]
Hi @arfon, I am happy to be an editor on this!

It looks like the paper is in a directory called `joss` - can this be communicated to whedon? or does the paper need to be in root or a `paper` directory

**Comment by lheagy** [comment]
@whedon assign @lheagy as editor

**Comment by whedon** [comment]
OK, the editor is @lheagy

**Comment by rbeucher** [comment]
Hi @lheagy, thanks for accepting to be the editor on this. Just received the list of potential reviewers. Im having a look right now.

**Comment by rbeucher** [comment]
Hi @lheagy. 

Here are some reviewer suggestions:

Sergio Zlotnik from the University of Barcelona,
Jolante van Wijk from New Mexico Tech Earth and Environmental Science
Thorsten Beker from The University of Texas at Austin
Thomas Theunissen from the University of Bergen, Norway

I have found Sergio on github, his pseudo is techas


--

**Comment by lheagy** [comment]
👋 @arfon: can the paper be in a folder called "joss" or does it need to be in root or "paper"

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1121 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1121/joss/paper.md): could not find expected ':' while scanning a simple key at line 19 column 4 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@lheagy the location is fine. The only issue I can see is L19: `orcid:0000-0003-3891-5444` <- this needs a space between `orcid:` and the value.

**Comment by rbeucher** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01121/joss.01121/10.21105.joss.01121.pdf)

**Comment by lheagy** [comment]
👋 Hi @rbeucher, just a quick update for you, I have heard back from Sergio and he is willing to review. I am just looking for one more reviewer and then we can get the review process started.

**Comment by rbeucher** [comment]
Great! Thanks @lheagy

**Comment by lheagy** [comment]
@whedon assign @techas as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @techas

**Comment by tth030** [comment]
Hei @lheagy!
I accept to review this submission. Now you know my github account by the way.
Thomas Th.

**Comment by lheagy** [comment]
@whedon add @tth030 as reviewer

**Comment by whedon** [comment]
OK, @tth030 is now a reviewer

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1136. Feel free to close this issue now!
