### ISSUE TITLE
[REVIEW]: A MATLAB toolbox to detect and analyze marine heatwaves

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1124]
**Submitting author:** @ZijieZhaoMMHW (<a href="http://orcid.org/0000-0003-3403-878X">Zijie Zhao</a>)
**Repository:** <a href="https://github.com/ZijieZhaoMMHW/m_mhw1.0" target ="_blank">https://github.com/ZijieZhaoMMHW/m_mhw1.0</a>
**Version:** v1.0
**Editor:** @kthyng
**Reviewer:** @mvdh7
**Archive:** <a href="https://doi.org/10.5281/zenodo.2545437" target="_blank">10.5281/zenodo.2545437</a>

## Status

[![status](http://joss.theoj.org/papers/088c8391f6c863e4a48ecf2530c5f13f/status.svg)](http://joss.theoj.org/papers/088c8391f6c863e4a48ecf2530c5f13f)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/088c8391f6c863e4a48ecf2530c5f13f"><img src="http://joss.theoj.org/papers/088c8391f6c863e4a48ecf2530c5f13f/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/088c8391f6c863e4a48ecf2530c5f13f/status.svg)](http://joss.theoj.org/papers/088c8391f6c863e4a48ecf2530c5f13f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ZijieZhaoMMHW/m_mhw1.0" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mvdh7, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @kthyng know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ZijieZhaoMMHW/m_mhw1.0">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@ZijieZhaoMMHW) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mvdh7 it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01124/joss.01124/10.21105.joss.01124.pdf)

**Comment by ZijieZhaoMMHW** [comment]
@whedon  commands

**Comment by ZijieZhaoMMHW** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01124/joss.01124/10.21105.joss.01124.pdf)

**Comment by kthyng** [comment]
Hi @mvdh7! How are things going on your end with this review? Pinged you on twitter too in case you still aren't getting notifications here.

**Comment by mvdh7** [comment]
Sorry for delay. Do I just post comments here?

**Comment by kthyng** [comment]
@mvdh7 Please use the checklist and information in the first comment on this issue up above. The checklist will help guide you through, checking off as things are found to be ok. We ask that you open new github issues for anything more than a comment, and link them to this review. Putting an overview comment in here is helpful to summarize and say if you are satisfied or what the current state is. Let me know if you have other questions!

**Comment by mvdh7** [comment]
Thanks @kthyng. @ZijieZhaoMMHW & co have done a great job in making this analysis available on MATLAB, and I'm sure this will be a very useful tool in the future. But there are a few issues that I think need to be resolved before publication in JOSS. I have ticked all the review boxes that I think I can at this point, & added all the corresponding issues.

**Comment by kthyng** [comment]
Great, thanks so much @mvdh7.

@ZijieZhaoMMHW please start addressing these issues as soon as you can. Thanks.

**Comment by ZijieZhaoMMHW** [comment]
Sorry for late reply, I was on flight yesterday and just back to work today. @mvdh7  Thanks for your careful review and pointed issues, I would try to address all issues this week and get back to you. @kthyng

**Comment by ZijieZhaoMMHW** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1124 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    266      0 --:--:-- --:--:-- --:--:--   271
Error reading bibliography ./paper.bib (line 10, column 3):
unexpected "u"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by ZijieZhaoMMHW** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1124 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    173      0 --:--:-- --:--:-- --:--:--   173
Error reading bibliography ./paper.bib (line 10, column 3):
unexpected "u"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by ZijieZhaoMMHW** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01124/joss.01124/10.21105.joss.01124.pdf)

**Comment by ZijieZhaoMMHW** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01124/joss.01124/10.21105.joss.01124.pdf)

**Comment by ZijieZhaoMMHW** [comment]
Hi @mvdh7  I have responded all issues. Please see if you are ok with it.

**Comment by kthyng** [comment]
Hi @mvdh7 and @ZijieZhaoMMHW, I'm hoping to finish up this submission in the next week or so. I've marked myself as being out of office starting next Wednesday, but it is dependent on forces outside my control; I'll try to finish this before being out. If that ends up not happening, @lheagy will take over.

**Comment by mvdh7** [comment]
Okay @kthyng. Will try my best to get things wrapped up before then

**Comment by ZijieZhaoMMHW** [comment]
https://doi.org/10.5281/zenodo.2545360

**Comment by arfon** [comment]
@ZijieZhaoMMHW - could you please rename your `LICENCE.txt` to `LICENSE.txt` and move it to the root (top level) of your repository please?

**Comment by ZijieZhaoMMHW** [comment]
@arfon Done. Sorry for that.

**Comment by arfon** [comment]
Thanks @ZijieZhaoMMHW. Could you update the Zenodo archive with this change too please?

**Comment by arfon** [comment]
@mvdh7 - many thanks for your review here and to @kthyng for editing this submission ✨ 

@ZijieZhaoMMHW - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01124/status.svg)](https://doi.org/10.21105/joss.01124)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01124">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01124/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01124/status.svg
   :target: https://doi.org/10.21105/joss.01124
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01124/status.svg)](https://doi.org/10.21105/joss.01124)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
