### ISSUE TITLE
[PRE REVIEW]: arcesetc: ARC Echelle Spectroscopic Exposure Time Calculator

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1126]
**Submitting author:** @bmorris3 (<a href="http://orcid.org/0000-0003-2528-3409">Brett Morris</a>)
**Repository:** <a href="https://github.com/bmorris3/arcesetc" target ="_blank">https://github.com/bmorris3/arcesetc</a>
**Version:** 0.1
**Editor:** @arfon
**Reviewers:** @wtgee

**Author instructions**

Thanks for submitting your paper to JOSS @bmorris3. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bmorris3 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@arfon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1126 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0     93      0 --:--:-- --:--:-- --:--:--    93
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.01126.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by bmorris3** [comment]
May I recommend @nespinoza or @wtgee as reviewers? Thanks to each for considering.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01126/joss.01126/10.21105.joss.01126.pdf)

**Comment by arfon** [comment]
> May I recommend @nespinoza or @wtgee as reviewers? Thanks to each for considering.

Great suggestions. @nespinoza or @wtgee - would you be interested in reviewing this submission for JOSS?

Also, @bmorris3 - can you updated your citation to the published version of the Astropy 2.0 paper? http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=2018arXiv180102634T&data_type=BIBTEX&db_key=PRE&nocookieset=1

**Comment by bmorris3** [comment]
Got it, thanks for the tip @arfon.

**Comment by bmorris3** [comment]
@wtgee That's perfect thank you! Also, we should totally meet up while you're in Seattle, I'd love to meet you in person 😄

**Comment by wtgee** [comment]
Sounds good! @arfon go ahead and put me down. (I was thinking there was an `@whedon accept` but it looks like not)

**Comment by arfon** [comment]
@whedon add @wtgee as reviewer

**Comment by whedon** [comment]
OK, @wtgee is now a reviewer

**Comment by arfon** [comment]
> Sounds good! @arfon go ahead and put me down. (I was thinking there was an `@whedon accept` but it looks like not)

There is, but that comes later in the process :-)

Thanks for agreeing to review this submission @wtgee - I'll go ahead and set up the review now.

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1130. Feel free to close this issue now!

**Comment by nespinoza** [comment]
> @wtgee That's perfect thank you! Also, we should totally meet up while you're in Seattle, I'd love to meet you in person 😄

Got late to the party but glad to see @wtgee will review this! Good luck with the submission @bmorris3!
