### ISSUE TITLE
[PRE REVIEW]: A News Verification Browser for the Detection of Clickbait, Satire, and Falsified News

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1127]
**Submitting author:** @VictoriaRubin (<a href="http://orcid.org/0000-0003-3610-9967">Victoria Rubin</a>)
**Repository:** <a href="https://github.com/litrl/litrl_code" target ="_blank">https://github.com/litrl/litrl_code</a>
**Version:** v0.12.0.0
**Editor:** @danielskatz
**Reviewers:** @lrasmus, @CBenghi

**Author instructions**

Thanks for submitting your paper to JOSS @VictoriaRubin. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@VictoriaRubin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1127 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1127 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1127/paper.md): mapping values are not allowed in this context at line 11 column 44 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by brogly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1127 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    289      0 --:--:-- --:--:-- --:--:--   290
Error reading bibliography ./paper.bib (line 115, column 9):
unexpected "l"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by brogly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01127/joss.01127/10.21105.joss.01127.pdf)

**Comment by brogly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01127/joss.01127/10.21105.joss.01127.pdf)

**Comment by arfon** [comment]
@jasonclark - would you be willing to edit this submission for JOSS?

**Comment by brogly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01127/joss.01127/10.21105.joss.01127.pdf)

**Comment by brogly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01127/joss.01127/10.21105.joss.01127.pdf)

**Comment by brogly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01127/joss.01127/10.21105.joss.01127.pdf)

**Comment by brogly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01127/joss.01127/10.21105.joss.01127.pdf)

**Comment by brogly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01127/joss.01127/10.21105.joss.01127.pdf)

**Comment by brogly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01127/joss.01127/10.21105.joss.01127.pdf)

**Comment by brogly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01127/joss.01127/10.21105.joss.01127.pdf)

**Comment by brogly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01127/joss.01127/10.21105.joss.01127.pdf)

**Comment by danielskatz** [comment]
👋 @jasonclark - ping... (re: editing request, see https://github.com/openjournals/joss-reviews/issues/1127#issuecomment-449369691)

**Comment by brogly** [comment]
Hi, maybe ejolly, shivam11, or arokem could review if Jason is busy? Although I'm guessing he is just on vacation or AFK given the holidays. Thanks!

**Comment by brogly** [comment]
@danielskatz - Hi Daniel, can I send the requests to the other potential reviewers? (only asking because I'm not sure if we need to wait or not)

**Comment by danielskatz** [comment]
Hi @brogly - we need an editor before we can assign reviewers...

**Comment by VictoriaRubin** [comment]
@arfon @danielskatz  @labarba @kyleniemeyer Request to Explain further procedures
Dear Editor-In-Chief, Associate and Associate Editors,
Could someone please explain to us how your peer-review process works?

My RA @brogly has been trying to get this simple 2 page manuscript into your peer-review pipeline for the past month, but in exactly a month nothing seems to have happened. Obviously the Holiday season is partly to blame, but there seems to be no clear path to what we are supposed to be doing next. 

@danielskatz seems to imply that we need to find a editor. How do you exactly envision this? We've requested reviewers that we thought might be interested. 

Is there a communication break down here? Or is our paper not conforming with any requirements to get someone to look at it please?

As much as we like the bot-enabled chat commands, I would very much appreciate some clarity from a human.

vrubin@uwo.ca
Dr. Victoria L. Rubin, Associate Professor, Faculty of Information & Media Studies (FIMS)
Director, Language & Information Technology Research Lab (LiT.RL)
FNB 4046, Western University, London, Ontario, Canada N6A 5B7
Tel: (519) 661-2111 x 88479, Fax: (519) 661-3506

**Comment by danielskatz** [comment]
I apologize on behalf on JOSS - this has been a problem on our side, not your side.  The process is that a submission can request a specific editor, who then works with the author to find reviewers and carry out the review process.  If a submission does not request an editor, we are supposed to assign one.

In this case, our process broke: the editor who we suggested has not responded, and to some extent, blaming the holiday break, we didn't follow-up.  I will go ahead and assign myself as editor, and start the process.

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @ejolly, @shivam11 - would one (or ideally both) of you be willing to review this for JOSS?

**Comment by danielskatz** [comment]
@brogly - can you suggest any other potential reviewers from the wider community?

**Comment by VictoriaRubin** [comment]
@danielskatz - Thanks for clarifying. Re outside reviewers: perhaps, Martin Potthast, who ran the CLickbait Challenge (https://webis.de/data/webis-clickbait-17.html)? Or anyone from his team or the other dataset group? 
@brogly  Chris, please stay on this, to make sure no further glitches occur. You had Martin Potthast's e-mail somewhere when we asked for permissions to use his set, right? Just in case @danielskatz asks for it Thanks again to both of you!

See 2 references below from our GitHub:
[CLICKBAIT DATASET 1] Abhijnan Chakraborty, Bhargavi Paranjape, Sourya Kakarla, and Niloy Ganguly. "Stop Clickbait: Detecting and Preventing Clickbaits in Online News Media”. In Proceedings of the 2016 IEEE/ACM International Conference on Advances in Social Networks Analysis and Mining (ASONAM), San Fransisco, US, August 2016. (URL: https://github.com/bhargaviparanjape/clickbait)

[CLICKBAIT DATASET 2] Martin Potthast, Tim Gollub, Kristof Komlossy, Sebastian Schuster, Matti Wiegmann, Erika Patricia Garces Fernandez, Matthias Hagen, and Benno Stein. Crowdsourcing a Large Corpus of Clickbait on Twitter. In Proceedings of the 27th International Conference on Computational Linguistics (COLING 2018), pages 1498–1507, August 2018. The COLING 2018 Organizing Committee.

**Comment by danielskatz** [comment]
👋 @potthast - would you be willing to review this submission for JOSS?  Or perhaps you can suggest someone from your group/team?  (See the [JOSS review guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) in case you are not familiar with how JOSS works)

**Comment by ejolly** [comment]
> 👋 @ejolly, @shivam11 - would one (or ideally both) of you be willing to review this for JOSS?

Unfortunately, I don't have easy access to a Windows computer (OSX and Linux only), so I'm not sure I'll be able to review this submission. Looks really interesting though!

**Comment by danielskatz** [comment]
👋 @lrasmus - you said in email you are willing to review this - please confirm here.

**Comment by lrasmus** [comment]
> 👋 @lrasmus - you said in email you are willing to review this - please confirm here.

I am willing and happy to review.  Thank you!

**Comment by danielskatz** [comment]
Thanks - I want to get one more reviewer, then we will start the review

**Comment by danielskatz** [comment]
@whedon assign @lrasmus as reviewer

but note that we are not starting the review yet...

**Comment by whedon** [comment]
OK, the reviewer is @lrasmus

**Comment by danielskatz** [comment]
👋 @CBenghi, @xirdneh, @nmullins, @dredamonsta1 - would one of you be interested in being the second reviewer for this submission on JOSS?

**Comment by danielskatz** [comment]
👋 @bmst, @johanneskiesel, @kleinfreund, @phoerious - would one you be willing to review this submission for JOSS? Or perhaps you can suggest someone from your group/team? (See the [JOSS review guidelines](
https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) in case you are not familiar with how JOSS works)

**Comment by potthast** [comment]
Thanks for the invitation.

Apart from me, only @bmst has been doing research on clickbait detection lately. Unfortunately, at present, we are both overwhelmed with other commitments, so that we will have to pass.

Sorry for the inconvenience!

**Comment by danielskatz** [comment]
👋 @felixhenninger or @jaynanavati - would you be willing to review this for JOSS?

**Comment by danielskatz** [comment]
👋 @theBrianCui or @rahulkapoor90 - would one of you be willing to review this for JOSS?  (See the [JOSS review guidelines](
https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) in case you are not familiar with how JOSS works)

**Comment by theBrianCui** [comment]
👋 Hi - what is this? I've never heard of JOSS before. How can I help?

**Comment by brogly** [comment]
@lrasmus - Thanks for agreeing to review.
@theBrianCui - We are looking for a second reviewer for the Litrl Browser software and associated paper for submission to JOSS. Links to these are above and @danielskatz (Editor) posted review guidelines right above your reply if you are interested.
@danielskatz - The following reviewers may also be interested, chkoar, sirsharpest, rljacobson, lindemann09, adammichaelwood (omitting the @ as I'm not sure how many people I'm supposed to ask all at once...)

**Comment by danielskatz** [comment]
Hi @theBrianCui - sorry for my delay in responding.  JOSS is an open journal for short articles that also contain open source research software.  Review is of both the article and the software.  Once a submission is reviewed successfully (which means the reviewers point out problems and the authors fix them), the submission is published and the authors can then use this publication for academic credit (by asking users to cite the publication).  [Here](
https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) are the review guidelines.

Are you willing to review this submission? (this issue overall, and [this article draft](
https://github.com/openjournals/joss-papers/blob/joss.01127/joss.01127/10.21105.joss.01127.pdf) in particular)?

**Comment by brogly** [comment]
@chkoar, @sirsharpest, @rljacobson, @lindemann09, @adammichaelwood would you be interested in reviewing this submission? We are looking for a second reviewer.

**Comment by CBenghi** [comment]
@danielskatz, @brogly,
apologies for the delay, I have only just noticed the thread, as I have had to ignore github for a while.
I'm happy to help with the review if still needed.

**Comment by danielskatz** [comment]
Yes, thanks very much @CBenghi - I'll go ahead and start the review now with you as one of the reviewers.

**Comment by danielskatz** [comment]
@whedon add @CBenghi as reviewer

**Comment by whedon** [comment]
OK, @CBenghi is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1208. Feel free to close this issue now!
