### ISSUE TITLE
[PRE REVIEW]: WrightTools: a Python package for multidimensional spectroscopy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1131]
**Submitting author:** @untzag (<a href="http://orcid.org/0000-0002-3845-824X">Blaise Thompson</a>)
**Repository:** <a href="https://github.com/wright-group/WrightTools" target ="_blank">https://github.com/wright-group/WrightTools</a>
**Version:** 3.2.0
**Editor:** @yochannah
**Reviewers:** @daissi, @ivergara

**Author instructions**

Thanks for submitting your paper to JOSS @untzag. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@untzag if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @yochannah it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@yochannah) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01131/joss.01131/10.21105.joss.01131.pdf)

**Comment by danielskatz** [comment]
👋 @yochannah - you've been suggested as the editor for this one.

**Comment by untzag** [comment]
@yochannah I suggest @ivergara and @jwuttke as potential reviewers because they both mention "spectroscopy"

I also suggest @ygrange and @Dybian for their interest in "workflow development"

all of these reviewers have indicated familiarity with Python

unfortunately, I'm not aware of anyone who has interest in both OSS and multidimensional spectroscopy---so I don't have any recommendations with exact domain knowledge

hope these humble suggestions are helpful in some way :smile:

**Comment by ygrange** [comment]
Short note to say I won’t have time. Good luck! 

--
Y. Grange

> Op 18 dec. 2018 om 02:50 heeft Blaise Thompson
<notifications@github.com> het volgende geschreven:
> 
> @yochannah I suggest @ivergara and @jwuttke as potential reviewers
because they both mention "spectroscopy"
> 
> I also suggest @ygrange and @Dybian for their interest in "workflow
development"
> 
> all of these reviewers have indicated familiarity with Python
> 
> unfortunately, I'm not aware of anyone who has interest in both OSS
and multidimensional spectroscopy---so I don't have any recommendations
with exact domain knowledge

**Comment by yochannah** [comment]
Sure, I can edit this. 

Thanks @ygrange for letting us know you won't have time. 

Looks like @dybian may have changed their github username. @daissi was that you? (and might you be interested to review?)

**Comment by daissi** [comment]
@yochannah indeed, I have changed my github username. Could you update it in the reviewers list?

Spectroscopy is not my field but I accept to review WrightTools for the workflow part.

**Comment by yochannah** [comment]
Thanks @daissi ! We need to find a second reviewer, then we can kick the official review issue off.

**Comment by ivergara** [comment]
@yochannah hi! Sorry for the late reply. I'm currently on vacation thus at the time unable to do the reviewing. From the quick check I did on the documentation I think I could do a review. Unfortunately, I could start working on it in any serious capacity only from the 3rd of January. If that's acceptable, or no alternative can be found until then, I'd gladly do the review.

**Comment by yochannah** [comment]
@ivergara I suspect most other reviewers won't be expecting to review over the holiday period, so starting 3rd Jan seems totally reasonable. Thanks! I'll kick off the review process, and don't worry about not getting to in until the new year. Have a great holiday period all! 🎄 🕎

**Comment by yochannah** [comment]
@whedon assign @daissi as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @daissi

**Comment by yochannah** [comment]
@whedon add @ivergara as reviewer

**Comment by whedon** [comment]
OK, @ivergara is now a reviewer

**Comment by yochannah** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1141. Feel free to close this issue now!

**Comment by yochannah** [comment]
Okay all - let's hop over to #1141 to get reviewing. Please remember to be a little more patient over the holiday period as things may take a little longer than normal, while people are eating too much turkey and the like 🎁
