### ISSUE TITLE
[PRE REVIEW]: RSeqAn: Headers and wrappers for the SeqAn library in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1133]
**Submitting author:** @aguang (<a href="http://orcid.org/0000-0003-4974-1873">August Guang</a>)
**Repository:** <a href="https://github.com/compbiocore/RSeqAn" target ="_blank">https://github.com/compbiocore/RSeqAn</a>
**Version:** v1.0
**Editor:** @brainstorm
**Reviewers:** @pdiakumis

**Author instructions**

Thanks for submitting your paper to JOSS @aguang. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@aguang if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by danielskatz** [comment]
👋 @mgymrek - are you able to edit this submission?

**Comment by brainstorm** [comment]
Happy to either review or edit this submission, your call @danielskatz and @mgymrek 👍

**Comment by danielskatz** [comment]
I would suggest you edit if you don't mind

**Comment by brainstorm** [comment]
@whedon assign brainstorm as editor

**Comment by whedon** [comment]
OK, the editor is brainstorm

**Comment by brainstorm** [comment]
@vladsaveliev, would you like to help JOSS review this software? Shouldn't take long to evaluate, I'll help you out as editor ;)

**Comment by brainstorm** [comment]
@whedon assign @pdiakumis as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @pdiakumis

**Comment by brainstorm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1160. Feel free to close this issue now!
