### ISSUE TITLE
[PRE REVIEW]: PyWavelets: A Python package for wavelet analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1134]
**Submitting author:** @grlee77 (<a href="http://orcid.org/0000-0001-8895-2740">Gregory Lee</a>)
**Repository:** <a href="https://github.com/PyWavelets/pywt" target ="_blank">https://github.com/PyWavelets/pywt</a>
**Version:** v1.0.1
**Editor:** @jedbrown
**Reviewers:** @rafat, @souopgui

**Author instructions**

Thanks for submitting your paper to JOSS @grlee77. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@grlee77 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by labarba** [comment]
I wonder if @rafat would be willing to help us with this review?

👋 @rafat —Are you familiar with the Journal of Open Source Software (JOSS)? JOSS is a free, open-source, community driven and developer-friendly online journal. It aims to bridge the gap of research software receiving citation credit. JOSS reviews involve downloading and installing the software, and inspecting the repository for key elements. Have a look at the JOSS [Review Process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

**Comment by rafat** [comment]
Yeah, I will gladly review the software.

Rafat

**Comment by jedbrown** [comment]
Thanks @labarba for catching this stall and thanks @rafat for being available to review.

@grlee77 There appears to be a missing reference ("manuscript by Stephan Mallat (???)") in your paper. Also, JOSS papers will include a Zenodo archive of the repository (post-review), so no need to cite an existing archive in the text.  Additionally, would it be appropriate to mention related work such as [Kymatio](https://github.com/kymatio/kymatio)?

**Comment by jedbrown** [comment]
@whedon add @rafat as reviewer

**Comment by whedon** [comment]
OK, @rafat is now a reviewer

**Comment by grlee77** [comment]
Apologies for missing the notification above regarding the reference.  It should be fixed now.

> Additionally, would it be appropriate to mention related work such as [Kymatio](https://github.com/kymatio/kymatio)?

Yeah, I saw this library recently and can add a mention to the manuscript.  Kymatio implements a scattering transform that I haven't studied in detail, but appears to be useful for things like classification. I believe the underlying wavelets involved are implemented in the Fourier domain whereas everything in PyWavelets is done via convolution with FIR filters.  PyWavelets has a wide range of classical wavelet transforms with a well defined inverse transform while I think it may be possible to invert a scattering transform, but it is not so straightforward.

**Comment by grlee77** [comment]
Do you need help identifying additional reviewers? I can suggest a couple potential ones from the provided list, but don't have anyone specific in mind.

**Comment by grlee77** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01134/joss.01134/10.21105.joss.01134.pdf)

**Comment by jedbrown** [comment]
@whedon add @souopgui as reviewer

**Comment by whedon** [comment]
OK, @souopgui is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1237. Feel free to close this issue now!
