### ISSUE TITLE
[PRE REVIEW]: pycontour: A Python package for contour representation and functionality

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1135]
**Submitting author:** @PingjunChen (<a href="http://orcid.org/0000-0003-0528-1713">Pingjun Chen</a>)
**Repository:** <a href="https://github.com/PingjunChen/pycontour" target ="_blank">https://github.com/PingjunChen/pycontour</a>
**Version:** v1.0.0
**Editor:** @arokem
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @PingjunChen. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@PingjunChen if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01135/joss.01135/10.21105.joss.01135.pdf)

**Comment by PingjunChen** [comment]
I would like to suggest @grlee77, @thomakra, @rlizzo, and @hooman650 to serve as the reviewers, considering their expertise in Python and image analysis.

**Comment by PingjunChen** [comment]
Hi @arokem, I don't want to push you. But I do hope this to be reviewed asap.  

Thanks for your time and effort!

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01135/joss.01135/10.21105.joss.01135.pdf)

**Comment by arokem** [comment]
Dear @PingjunChen. After review of your submission, the editorial board has determined that your submission does not meet our [submission requirements](http://joss.theoj.org/about#submission_requirements). In particular, while the software seems very useful, and the package seems well-documented and well-executed, this submission falls under the 'Minor utility package' category, and so it is our decision not to publish it in JOSS. I am sorry that I don't have better news. Best wishes, Ariel

**Comment by PingjunChen** [comment]
@arokem Thanks for your feedback. I agree the 'minor utility package' decision. I submit because I believe this package would be useful for python developers. I will add more functionalities to this repo to make it feature extensive.

Would it be fine to submit this repo in the future?
