### ISSUE TITLE
[PRE REVIEW]: tissueloc: Whole slide pathology image tissue localization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1138]
**Submitting author:** @PingjunChen (<a href="http://orcid.org/0000-0003-0528-1713">Pingjun Chen</a>)
**Repository:** <a href="https://github.com/PingjunChen/tissueloc" target ="_blank">https://github.com/PingjunChen/tissueloc</a>
**Version:** v1.0.0
**Editor:** @pjotrp
**Reviewers:** @Arafatk

**Author instructions**

Thanks for submitting your paper to JOSS @PingjunChen. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@PingjunChen if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @pjotrp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@pjotrp) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @pjotrp - the submitting author suggested you as the handling editor.

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by PingjunChen** [comment]
PDF cannot be generated. I have checked reference and image insertion, which should be conformed to format. I wonder if I can ask help on the pdf generation. @pjotrp @arfon

**Comment by PingjunChen** [comment]
Thanks @arfon ! Glad you generate pdf for me! I tried using "whedon generate pdf", only "Attempting PDF compilation..." shown above, no pdf link generated. I thought it could be format issue, but could not find any, thus asking for help.

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@PingjunChen do you mind regenerating the paper without the image? I have included an image in other papers, take a look http://joss.theoj.org/papers/10.21105/joss.00025. 

Also there are some English grammar problems - do you mind having a native speaker check (I am not one!) before we start review. Finally, it took me some time to figure out what the paper actually is about. Can you make the introduction somewhat clearer? Say what the goal is of the software and how it helps its users. Next have a section on state-of-the-art and how your tool differs. I know you cover it somewhat, but make it extremely clear. It will help noobs like me ;)

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1138 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    213      0 --:--:-- --:--:-- --:--:--   216
pandoc: paper.md: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #1138 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1138 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:47:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01138/joss.01138/10.21105.joss.01138.pdf)

**Comment by arfon** [comment]
> @PingjunChen & @Arafatk, we will go into review soon. First I would like to have the pdf generation fixed. We'll await @arfon.

@whedon had managed to get into a weird state. I've fixed this now.

**Comment by pjotrp** [comment]
Thank you @arfon! @PingjunChen do you want to reintroduce the figure again?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01138/joss.01138/10.21105.joss.01138.pdf)

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01138/joss.01138/10.21105.joss.01138.pdf)

**Comment by PingjunChen** [comment]
Hi @pjotrp, I have added the schematic diagram to paper.md and the pdf generation works now! Thanks. One small issue is that the figure caption is overlapped with the footnote. Any suggestions to fix that?

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01138/joss.01138/10.21105.joss.01138.pdf)

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01138/joss.01138/10.21105.joss.01138.pdf)

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01138/joss.01138/10.21105.joss.01138.pdf)

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01138/joss.01138/10.21105.joss.01138.pdf)

**Comment by pjotrp** [comment]
The figure caption outside the page is probably a LaTeX problem. Making the figure smaller will fix it. Or have the caption as text so it goes on the next page... @arfon, we probably don't have a way to constrain the figure in a vertical box?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01138/joss.01138/10.21105.joss.01138.pdf)

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01138/joss.01138/10.21105.joss.01138.pdf)
