### ISSUE TITLE
[PRE REVIEW]: open_iA: A tool for processing and visual analysis of industrial computed tomography datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1139]
**Submitting author:** @codeling (<a href="http://orcid.org/0000-0003-1271-0838">Bernhard Fröhler</a>)
**Repository:** <a href="https://github.com/3dct/open_iA" target ="_blank">https://github.com/3dct/open_iA</a>
**Version:** 2018.12
**Editor:** @katyhuff
**Reviewers:** @trallard, @behollister

**Author instructions**

Thanks for submitting your paper to JOSS @codeling. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@codeling if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @katyhuff it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@katyhuff) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @katyhuff - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01139/joss.01139/10.21105.joss.01139.pdf)

**Comment by katyhuff** [comment]
Hi @codeling, thanks for this submission. I'm sorry for the delay. I'm back in action now. Now, @codeling , let's ping a few fitting reviewers, with C++ and Python expertise as well as some background in image analysis and/or computed tomography. We can start the review once two or three of them accept the request to review.

Dear potential reviewers (@krischer @rrrlw @camillescott  ),

Based on your expertise in C++ and Python, image analysis, and/or computed tomography, I would like to ask if you can help us out with a submission to JOSS (The Journal of Open Source Software), where I’m an editor.

Title: open_iA: A tool for processing and visual analysis of industrial computed tomography datasets 
Summary: Visual analysis and processing of volumetric datasets, with a focus on industrial computed tomography
Wiki: https://github.com/3dct/open_ia/wiki
Topic: Data visualization, signal processing, imaging
Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01139/joss.01139/10.21105.joss.01139.pdf
Submitting author: @codeling (Bernhard Fröhler)
Repository: https://github.com/3dct/open_iA
Version: 2018.12

@krischer : Lion, are you able to and interested in taking on this review?
@rrrlw : Raoul, are you able to and interested in taking on this review?
@camillescott : Camille, are you able to and interested in taking on this review?

Your prompt response is appreciated. Please see https://joss.readthedocs.io/en/latest/reviewer_guidelines.html for more information about reviewer criteria and the process if it is new to you.

**Comment by rrrlw** [comment]
Hello, although open_iA looks phenomenal, I do not have the expertise necessary to review it. :(

My apologies; best of luck with the submission!

**Comment by katyhuff** [comment]
Thank you for letting us know, @rrrlw .

@codeling : Can you suggest any reviewers? It would be helpful to me if you can think of anyone. The folks on [this list](https://bit.ly/joss-reviewers) are already reviewers for JOSS. If there is someone else that you would like to suggest, please let me know. Though they will need to be free of any conflict of interest, you may be aware of individuals in your community who would be good reviewers for this submission.

**Comment by codeling** [comment]
From the list, I could imagine @jochym and @trallard might also be a good fit!

**Comment by katyhuff** [comment]
Both would be excellent if they have the time, indeed.

Pawel (@jochym) and Tania (@trallard), based on your expertise, I would like to ask if you can help us out by volunteering to review this submission to JOSS.

Title: open_iA: A tool for processing and visual analysis of industrial computed tomography datasets
Summary: Visual analysis and processing of volumetric datasets, with a focus on industrial computed tomography
Wiki: https://github.com/3dct/open_ia/wiki
Topic: Data visualization, signal processing, imaging
Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01139/joss.01139/10.21105.joss.01139.pdf
Submitting author: @codeling (Bernhard Fröhler)
Repository: https://github.com/3dct/open_iA
Version: 2018.12

**Comment by katyhuff** [comment]
@whedon assign @trallard as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @trallard

**Comment by katyhuff** [comment]
@behollister and @ngoldbaum , would either of you be available to and interested in reviewing this JOSS submission? I agree that you like have the expertise. Do you have the time? We'd like at least two reviewers. @trallard has thankfully already agreed, so we're looking for one or two more.

Title: open_iA: A tool for processing and visual analysis of industrial computed tomography datasets
Summary: Visual analysis and processing of volumetric datasets, with a focus on industrial computed tomography
Wiki: https://github.com/3dct/open_ia/wiki
Topic: Data visualization, signal processing, imaging
Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01139/joss.01139/10.21105.joss.01139.pdf
Submitting author: @codeling (Bernhard Fröhler)
Repository: https://github.com/3dct/open_iA
Version: 2018.12

**Comment by behollister** [comment]
Hi,


Yes, I can review the submission. When is the deadline?


Regards,

Brad


Brad E. Hollister, Ph.D.

Department of Computer Science
Californian State University Dominguez Hills
Office: NSM B218
Phone: 864-395-5560
________________________________

**Comment by katyhuff** [comment]
Thaknks @behollister ! We aim to complete the review process quickly, so I typically expect a reviewer to get started with their review during the week following assignment, complete their initial review within a week or so thereafter, and remain active with the back-and-forth until the paper is accepted (can be as quick as a week, but is often 3 weeks, and occasionally longer.) If a deadline is helpful to you, I can certainly assign one, though I typically do not. 


Please see https://joss.readthedocs.io/en/latest/reviewer_guidelines.html for more information about reviewer criteria and the process.

**Comment by katyhuff** [comment]
@whedon add @behollister as reviewer

**Comment by whedon** [comment]
OK, @behollister is now a reviewer

**Comment by katyhuff** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1185. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Thanks for volunteering, both. Two reviewers will likely be sufficient for this review, I'll contribute a bit to the review as well. Let's get started over in #1185 .
