### ISSUE TITLE
[PRE REVIEW]: FRIEDA: Flexible Robust Intelligent Elastic Data Management Framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#114]
**Submitting author:** dghoshal-lbl (<a href="http://orcid.org/0000-0002-6819-6949">Devarshi Ghoshal</a>)
**Repository:** <a href="https://bitbucket.org/dghoshal/frieda" target ="_blank">https://bitbucket.org/dghoshal/frieda</a>
**Version:** v0.3.0
**Editor:** @acabunoc
**Reviewer:** @krother

**What this issue is for**

Thanks for submitting your paper to JOSS dghoshal-lbl. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @acabunoc and @tracykteal. Would either of you be willing to edit this submission for JOSS?

**Comment by dghoshal-lbl** [comment]
Is there any update on the review process?

**Comment by arfon** [comment]
@whedon assign @acabunoc as editor

**Comment by whedon** [comment]
OK, the editor is @acabunoc

**Comment by arfon** [comment]
> Is there any update on the review process?

Apologies for the slow progress here. @acabunoc has agreed to edit this submission - her next task is to find a reviewer for this submission.

**Comment by dghoshal-lbl** [comment]
Any update/suggestion/concerns regarding our submission? How long is the review process?

**Comment by arfon** [comment]
Friendly bump on this @acabunoc :grin:

**Comment by acabunoc** [comment]
I'm on it! Sorry for the delay. Will take a look and reach out to reviewers tomorrow at the latest.

**Comment by acabunoc** [comment]
Hi 👋  @krother & @jsta! Would either of you be interested (& have time) to review this?

Also, @dghoshal-lbl, let me know you have anyone to suggest as a reviewer. It's usually good to have multiple reviewers, closer to the domain.

**Comment by krother** [comment]
Yes, I'm in. Will take me 4-5 days though.

**Comment by acabunoc** [comment]
Excellent! Thanks @krother 😄

**Comment by acabunoc** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by acabunoc** [comment]
@whedon assign @krother as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @krother

**Comment by acabunoc** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by acabunoc** [comment]
@whedon start review magic-word=bananas 🍌

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by acabunoc** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/164. Feel free to close this issue now!
