### ISSUE TITLE
[PRE REVIEW]: dlmmc: Dynamical linear model regression for atmospheric time-series analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1140]
**Submitting author:** @justinalsing (<a href="http://orcid.org/0000-0003-4618-3546">Justin Alsing</a>)
**Repository:** <a href="https://github.com/justinalsing/dlmmc" target ="_blank">https://github.com/justinalsing/dlmmc</a>
**Version:** v1.0.0
**Editor:** @danielskatz
**Reviewers:** @Chilipp, @taqtiqa-mark

**Author instructions**

Thanks for submitting your paper to JOSS @justinalsing. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@justinalsing if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1140 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/author.rb:58:in `block in build_affiliation_string': Problem with affiliations for Justin Alsing, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/author.rb:57:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/author.rb:57:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:109:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:109:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:106:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:106:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-443822f01563/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01140/joss.01140/10.21105.joss.01140.pdf)

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @justinalsing - I note that you don't have DOIs in the references for papers - you can add them to the bib file, then rebuild the PDF by adding a comment here that just says
```
@whedon generate pdf
```

Also, do you have suggestions for reviewers?  In particular, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission, though if you have suggestions outside the list, that's great too.

**Comment by danielskatz** [comment]
Also, as we get this started, please be aware of the [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html) that will be used, and make any other changes needed to make the review easier.

**Comment by justinalsing** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01140/joss.01140/10.21105.joss.01140.pdf)

**Comment by justinalsing** [comment]
Other possible suitable reviewers (expertise in python and climate science)

jtmiclat
Chilipp
sarats

**Comment by justinalsing** [comment]
I was also recommended mathause (not on the list of JOSS reviewers) by a colleague as probably well placed to review this code

**Comment by danielskatz** [comment]
👋 @ejolly & @ghammad - would one or both of you be willing to review this JOSS submission?  I'm looking for a total of 2 reviewers

**Comment by danielskatz** [comment]
👋 @taqtiqa-mark & @lindemann09 - would one or both of you be willing to review this JOSS submission? I'm looking for a total of 2 reviewers

**Comment by danielskatz** [comment]
👋 @jtmiclat & @Chilipp - would one or both of you be willing to review this JOSS submission? I'm looking for a total of 2 reviewers

**Comment by danielskatz** [comment]
👋 @sarats & @mathause - would one or both of you be willing to review this JOSS submission? I'm looking for a total of 2 reviewers

**Comment by Chilipp** [comment]
looks interesting @danielskatz. I would be willing to review it but I won't be available before January 16th.

**Comment by taqtiqa-mark** [comment]
@danielskatz, sure I'm able to review this.

**Comment by danielskatz** [comment]
Thanks @taqtiqa-mark.  I would like to find two reviewers, and as you can see, a couple of other people are willing to review but not for a couple of weeks.  If I can find one more person willing to review soon, we'll start; otherwise, we'll start in a day or two with the expectation that the second review will be a bit later than yours.  So hold on for a day or two...

**Comment by mathause** [comment]
I could also only start to review mid/ end of January. So I suppose others are able to do it earlier than me.

**Comment by danielskatz** [comment]
I'm going to wait one more day to see if anyone I've mentioned can start a review immediately, and if not, we'll start anyhow with the expectation that one reviewer won't start until mid January.

**Comment by ejolly** [comment]
Sorry for the delayed response @danielskatz I've been traveling with limited access to email. Unfortunately, I too won't be able to start a review until the end of this month. Happy to do it then if that timeline works/makes sense.

**Comment by danielskatz** [comment]
Ok, let's go ahead with @taqtiqa-mark and @Chilipp, recognizing that  @Chilipp won't be able to start for another week.

**Comment by danielskatz** [comment]
@whedon assign @taqtiqa-mark as reviewer

**Comment by danielskatz** [comment]
@whedon add @Chilipp as reviewer

**Comment by whedon** [comment]
OK, @Chilipp is now a reviewer

**Comment by danielskatz** [comment]
@whedon add @taqtiqa-mark as reviewer

**Comment by whedon** [comment]
OK, @taqtiqa-mark is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1157. Feel free to close this issue now!
