### ISSUE TITLE
[REVIEW]: vcftoolz: a Python package for comparing and evaluating Variant Call Format files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1144]
**Submitting author:** @stevendavis (<a href="http://orcid.org/0000-0002-5581-1922">Steve Davis</a>)
**Repository:** <a href="https://github.com/CFSAN-Biostatistics/vcftoolz" target ="_blank">https://github.com/CFSAN-Biostatistics/vcftoolz</a>
**Version:** v1.1.0
**Editor:** @mgymrek
**Reviewer:** @richyanicky
**Archive:** <a href="https://doi.org/10.5281/zenodo.2583998" target="_blank">10.5281/zenodo.2583998</a>

## Status

[![status](http://joss.theoj.org/papers/8f99ee5890ba7e9e3a69d8f49d677037/status.svg)](http://joss.theoj.org/papers/8f99ee5890ba7e9e3a69d8f49d677037)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/8f99ee5890ba7e9e3a69d8f49d677037"><img src="http://joss.theoj.org/papers/8f99ee5890ba7e9e3a69d8f49d677037/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/8f99ee5890ba7e9e3a69d8f49d677037/status.svg)](http://joss.theoj.org/papers/8f99ee5890ba7e9e3a69d8f49d677037)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/CFSAN-Biostatistics/vcftoolz" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@richyanicky, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @mgymrek know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/CFSAN-Biostatistics/vcftoolz">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.1.0
- [x] **Authorship:** Has the submitting author (@stevendavis) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by richyanicky** [comment]
The software functioned as stated. It ran without error within the bounds of the description provided.
There are some issues that I came across that would be a benefit to our use.
1) Read gz format directly. I could not read our gz vcf files.
2) Files > 1M bp are too large to process and often caused our server to run out of memory.
3) The Venn diagrams are great, however it used the long file names and they could not be read in the output. A option would be to provide plot labels.

**Comment by mgymrek** [comment]
Thanks @richyanicky for the review.

@stevendavis, could you respond to the reviewer comments, and in particular comment on the size of files and the compute requirements? Is this meant to process genome-wide VCFs? In which case it would be important to handle gzipped files. On the other hand if it is meant to handle only small files it is worth making that clear.

**Comment by stevendavis** [comment]
@richyanicky I'm back to work after the government shutdown.  Thank you for the review comments.  
1. Supporting .gz files is a good idea. 
2. We use the software to process bacterial variants. In our work, we usually have dozens of samples in a multi-VCF file with 10,000 or fewer variant positions and our VCF files include only the variant positions.  Could you clarify, in your testing, do you have more than 1 million variant positions?  How many samples per VCF file?
3. An option to provide plot labels is a good idea.

@mgymrek Do these issues preclude publishing the manuscript, or would it be acceptable to address the issues in a future software release?

**Comment by mgymrek** [comment]
@stevendavis: The changes are not strictly necessary, however I do have the following comments about @richyanicky's points

1. It looks like the package uses PyVCF to parse VCFs. I believe reading gzipped vcfs should be supported (e.g. something like `vcf.Reader(open('file.vcf.gz', 'rb'))` has worked for me)

2. Can you clarify in the paper the data sizes you are targeting. I know it mentions pathogens, but it would be helpful for a user to know it is meant for smaller variant files (vs. say human whole genome) by explicitly saying it is for on the order of thousands of variants.

3. Not necessary, but would be nice.

Also in the paper should the sentence: "The artifacts produced by vcftools are not available from other tools." say `vcftoolz` instead of `vcftools`?

**Comment by stevendavis** [comment]
@mgymrek The vcftoolz software is now updated to support reading gzipped vcf files.  Thanks for the tip.  I've bumped the version number to 1.1.0.  I have not yet pushed the release to PyPi, but will do so soon.

The manuscript is also updated to clarify the expected number of variants, and fixed the typo.  Good catch!

Do I need to do anything to trigger PDF file creation?

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01144/joss.01144/10.21105.joss.01144.pdf)

**Comment by mgymrek** [comment]
@stevendavis this looks good. Can you add DOIs for the two paper references?

**Comment by stevendavis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01144/joss.01144/10.21105.joss.01144.pdf)

**Comment by stevendavis** [comment]
@mgmrek Thank you for the feedback.  The DOIs are added for the two paper references.  Let me know if any other changes are needed.

**Comment by mgymrek** [comment]
Thanks @stevendavis. Could you make a Zenodo archive and report the DOI here?

**Comment by stevendavis** [comment]
The Zenodo DOI for the vcftoolz software is:
10.5281/zenodo.2583998

The version is:
v1.1.0

**Comment by mgymrek** [comment]
@whedon set doi 10.5281/zenodo.2583998

**Comment by mgymrek** [comment]
@whedon set v1.1.0 as version

**Comment by whedon** [comment]
OK. v1.1.0 is the version.

**Comment by stevendavis** [comment]
@whedon set doi 10.5281/zenodo.2583998

**Comment by stevendavis** [comment]
@whedon set 10.5281/zenodo.2583998 as archive

**Comment by whedon** [comment]
I'm sorry @stevendavis, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by stevendavis** [comment]
@mgymrek May I ask you to set the archive DOI?

**Comment by mgymrek** [comment]
@whedon set 10.5281/zenodo.2583998 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2583998" target="_blank">10.5281/zenodo.2583998</a> is the archive.

**Comment by stevendavis** [comment]
For some reason, the paper is still tagged "DOI pending".  What am I doing wrong?

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/577

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/577, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1101/023754 is OK
- 10.1093/bioinformatics/btr330 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/578
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01144](https://doi.org/10.21105/joss.01144)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@richyanicky - many thanks for your review and to @mgymrek for editing this submission ✨ 

@stevendavis - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01144/status.svg)](https://doi.org/10.21105/joss.01144)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01144">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01144/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01144/status.svg
   :target: https://doi.org/10.21105/joss.01144
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01144/status.svg)](https://doi.org/10.21105/joss.01144)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by stevendavis** [comment]
@richyanicky @mgymrek @arfon Awesome! Thank you everyone for the comments and suggestions and for keeping my first JOSS submission running along smoothly.
