### ISSUE TITLE
[REVIEW]: strandCheckR: An R package for quantifying and removing double strand sequences for strand-specific RNA-seq

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1145]
**Submitting author:** @tothuhien (<a href="http://orcid.org/0000-0003-2902-3655">Thu-Hien To</a>)
**Repository:** <a href="https://github.com/UofABioinformaticsHub/strandCheckR" target ="_blank">https://github.com/UofABioinformaticsHub/strandCheckR</a>
**Version:** v1.1.2
**Editor:** @mgymrek
**Reviewer:** @rmflight
**Archive:** <a href="https://doi.org/10.5281/zenodo.2555032" target="_blank">10.5281/zenodo.2555032</a>

## Status

[![status](http://joss.theoj.org/papers/526e5d062277f5e46154b00f7e6e1587/status.svg)](http://joss.theoj.org/papers/526e5d062277f5e46154b00f7e6e1587)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/526e5d062277f5e46154b00f7e6e1587"><img src="http://joss.theoj.org/papers/526e5d062277f5e46154b00f7e6e1587/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/526e5d062277f5e46154b00f7e6e1587/status.svg)](http://joss.theoj.org/papers/526e5d062277f5e46154b00f7e6e1587)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/UofABioinformaticsHub/strandCheckR" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@rmflight, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @mgymrek know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/UofABioinformaticsHub/strandCheckR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
  - No [license](https://github.com/UofABioinformaticsHub/strandCheckR/issues/2) file. It is licensed according to CRAN and Bioconductor standards, but not commonly accepted OSS project standards.
  - This was resolved by [this commit](https://github.com/UofABioinformaticsHub/strandCheckR/commit/1340208624961bf0a5ee142cb539b3d5099c08a9)
- [x] **Version:** v1.1.2
- [x] **Authorship:** Has the submitting author (@tothuhien) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
  - Yes, based on the git contributions, it seems the authors list is appropriate and complete.

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
  - Yes, installation proceeds without problems. As noted in [this issue](https://github.com/UofABioinformaticsHub/strandCheckR/issues/6), I do suggest removing the list of required packages from the README, as Bioconductor installs the dependencies without difficulty.
- [x] **Functionality:** Have the functional claims of the software been confirmed?
  - Yes, I have confirmed that I can run the code provided in the vignette, and that it behaves as outlined in the vignette and paper.
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)
  - The paper has a performance claim that is not verified. See [this issue](https://github.com/UofABioinformaticsHub/strandCheckR/issues/8).

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
  - This is stated in the paper, and in the package documentation, but not in the README. Copying over the statement from the DESCRIPTION should be sufficient. See [this issue](https://github.com/UofABioinformaticsHub/strandCheckR/issues/4).
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
  - Dependencies are handled just fine by the Bioconductor installer.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
  - There is no example of usage in the README, but the included vignette does provide a fully worked example. I think including the commands listed in the package level documentation into the README would be sufficient. See [this issue](https://github.com/UofABioinformaticsHub/strandCheckR/issues/5).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
  - The core functionality is documented, in that there are descriptions for each function and their arguments.
  - However, some of the documentation lacks examples, and there are places where I believe the documentation could be improved, as outlined in [this pull request](https://github.com/UofABioinformaticsHub/strandCheckR/pull/3) and [this issue](https://github.com/UofABioinformaticsHub/strandCheckR/issues/9).
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
  - There are automated tests.
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
  - No Contributing file or description provided. See [this issue](https://github.com/UofABioinformaticsHub/strandCheckR/issues/7)

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by rmflight** [comment]
I think I've completed my initial review.

**Comment by mgymrek** [comment]
@rmflight great. can you paste as a comment and recommended changes especially regarding items from the checklist you did not find satisfactory?

**Comment by rmflight** [comment]
Hi @mgymrek . I actually created issues for all of this in [the repo](https://github.com/UofABioinformaticsHub/strandCheckR/issues?q=is%3Aissue+author%3Armflight), and have been checking items from the main review above as they have been addressed. I can put all the comments on here, but didn't think that was necessary.

**Comment by mgymrek** [comment]
@rmflight that's fine. Can you update this comment thread when all of those issues have been addressed?

**Comment by mgymrek** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01145/joss.01145/10.21105.joss.01145.pdf)

**Comment by mgymrek** [comment]
Thanks @rmflight for the helpful review!
@tothuhien can you make a Zenodo archive and report the DOI here?

**Comment by steveped** [comment]
Hi @mgymrek,

I've just created a release with the DOI & added the badge to the README. It's 10.5281/zenodo.2555032. Hopefully I got the process right for a first timer. :)

**Comment by mgymrek** [comment]
@whedon set 10.5281/zenodo.2555032 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2555032" target="_blank">10.5281/zenodo.2555032</a> is the archive.

**Comment by mgymrek** [comment]
@wedon set v1.1.2 as version

**Comment by mgymrek** [comment]
@whedon set v1.1.2 as version

**Comment by whedon** [comment]
OK. v1.1.2 is the version.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/499

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/499, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1371/journal.pcbi.1003118 is OK
- http://doi.org/10.1101/pdb.prot5652 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/500
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01145](https://doi.org/10.21105/joss.01145)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@rmflight - many thanks for your review here and to @mgymrek for editing this submission ✨

@tothuhien - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01145/status.svg)](https://doi.org/10.21105/joss.01145)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01145">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01145/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01145/status.svg
   :target: https://doi.org/10.21105/joss.01145
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01145/status.svg)](https://doi.org/10.21105/joss.01145)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by arfon** [comment]
@mgymrek - in the future, please ping `@openjournals/joss-eics` when you're ready to accept a paper. This will then notify the managing editor on rotation.
