### ISSUE TITLE
[REVIEW]: tissueloc: Whole slide pathology image tissue localization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1148]
**Submitting author:** @PingjunChen (<a href="http://orcid.org/0000-0003-0528-1713">Pingjun Chen</a>)
**Repository:** <a href="https://github.com/PingjunChen/tissueloc" target ="_blank">https://github.com/PingjunChen/tissueloc</a>
**Version:** v1.0.0
**Editor:** @pjotrp
**Reviewer:** @Arafatk
**Archive:** <a href="https://doi.org/10.5281/zenodo.2529982" target="_blank">10.5281/zenodo.2529982</a>

## Status

[![status](http://joss.theoj.org/papers/04e06b619d03f936a2c58e047f66b6c3/status.svg)](http://joss.theoj.org/papers/04e06b619d03f936a2c58e047f66b6c3)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/04e06b619d03f936a2c58e047f66b6c3"><img src="http://joss.theoj.org/papers/04e06b619d03f936a2c58e047f66b6c3/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/04e06b619d03f936a2c58e047f66b6c3/status.svg)](http://joss.theoj.org/papers/04e06b619d03f936a2c58e047f66b6c3)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/PingjunChen/tissueloc" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Arafatk, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @pjotrp know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/PingjunChen/tissueloc">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@PingjunChen) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01148/joss.01148/10.21105.joss.01148.pdf)

**Comment by pjotrp** [comment]
@PingjunChen we are starting review in this issue tracker. To expedite the review process do you mind going through above list of check boxes and make sure they can be ticked (you can't tick them). Also check the PDF output carefully. Ping us here when you are done.

**Comment by PingjunChen** [comment]
Hi @pjotrp and @Arafatk, all listed boxes can be ticked except "Automated tests". Because of the gigabyte size of whole slide image (WSI), we think uploading testing WSIs to github repo is not good practice. But tests are conducted extensively in local repo.

**Comment by pjotrp** [comment]
@PingjunChen I agree that storing the data in github is not a good idea. What I do is provide data that is readily available for download in some way. A web server or figshare or something would do. But, to be honest, since this is a tool using standard libraries - so I am OK to skip it. If you decide to develop it further I would certainly recommend adding tests. You could also consider including some smaller images - just to make sure it won't regress.

**Comment by pjotrp** [comment]
@Arafatk you can start review. Please read the reviewer guidelines above.

**Comment by PingjunChen** [comment]
Thanks for your suggestions! @pjotrp I have add a few low level slide images, which is much smaller, for testing tissue localization. They are located in "$project_dir/test/data". With these testing images, now automated test using travis is added and passed.

**Comment by Arafatk** [comment]
@pjotrp I am on it.

**Comment by Arafatk** [comment]
@PingjunChen     
1.  The installation worked fine but I had to install python-tk separately to run the software.  For a sanity check for installation generally I go to Codeanywhere.io and spawn small virtual machines to try out my installation and see if it works on a fresh instances.  
2. I see this on the generated PDF 
![image](https://user-images.githubusercontent.com/11155207/50567851-d2c27100-0d6f-11e9-9721-218e3e2ff4e4.png)
Can you please resize the image size to make this look cleaner?       
3. Can you please elaborate a little bit on the community guidelines?  
Maybe use some other software as a reference point -> https://github.com/SciRuby/scirub/blob/master/CONTRIBUTING.md      
4. I think paper.md must also have references just like the generated pdf but maybe I am wrong. -> https://github.com/PingjunChen/tissueloc/blob/master/paper/paper.md

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01148/joss.01148/10.21105.joss.01148.pdf)

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01148/joss.01148/10.21105.joss.01148.pdf)

**Comment by PingjunChen** [comment]
@Arafatk @pjotrp  By the way, I now upgrade the ``tissueloc`` version to 1.4.0.

**Comment by pjotrp** [comment]
Thank you @Arafatk! @PingjunChen can you also discuss the boxes that have not been checked on the check list? Mostly these are minor additions to the README file. They are important for people who want to try the software. Almost there!

**Comment by PingjunChen** [comment]
1. For the installation, I have updated the instructions in README.md and remove "import matplotlib" in the repo. I have tried the installation on both my Ubuntu and Mac machine.
2. I use the "travis" and "pytest" for automated test. The status is "passing". 
3. I have updated the "Contributing" part. I would like to refer the reference point @Arafatk suggested. Sadly, the link cannot be opened. 

Thanks @pjotrp and @Arafatk !

**Comment by Arafatk** [comment]
@PingjunChen Thanks for the work. All the suggestions that I made have been taken care off. 

By the way, this is the link that I had suggested ->  https://github.com/SciRuby/sciruby/blob/master/CONTRIBUTING.md 


Also, this is a very trivial issues but perhaps Contribution part could be phrased a bit differently just for clarity. So  

![image](https://user-images.githubusercontent.com/11155207/50572302-0e4a5300-0de3-11e9-953a-353dc54c5473.png)

Might also be written as         

We would like to test this package on more diversified digital slides. Slides (low level images would be better) and their corresponding results are also very welcome as [Pull Requests](https://github.com/PingjunChen/tissueloc/pulls).

**Comment by PingjunChen** [comment]
@Arafatk Thanks for your feedback. I revised the last paragraph in "Contributing" as you suggested. Also Thanks for the link you provide.

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01148/joss.01148/10.21105.joss.01148.pdf)

**Comment by pjotrp** [comment]
Thank you @Arafatk and @PingjunChen. Great job. 

The review process is now complete. To finalize your submission and accept your paper in JOSS, we need two things. First, can you confirm that all references in your bibliography have a DOI (if one exists).

Second, we need you to deposit a copy of your software repository (including any revisions made during the JOSS review process) with a data-archiving service. To do so:

 1. Create [a GitHub release](https://help.github.com/articles/creating-releases/) of the current version of your software repository
 2. Deposit that release with [Zenodo](https://zenodo.org/), [figshare](https://figshare.com/), or a similar DOI issuer.
 3. Post a comment here with the DOI for the release.

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01148/joss.01148/10.21105.joss.01148.pdf)

**Comment by PingjunChen** [comment]
0. I just reviewed the repo and tagged the repo v1.5.0 as the final version for JOSS.
1. After checking, now I confirm all references in the bibliography have DOI.
2. DOI for the release is 10.5281/zenodo.2529982, with badge shown as
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.2529982.svg)](https://doi.org/10.5281/zenodo.2529982)

Thanks! @pjotrp and @Arafatk !

**Comment by pjotrp** [comment]
You need to add the doi for each reference as in https://github.com/genenetwork/genenetwork2/blob/testing/doc/joss/2016/paper.bib so it shows in the paper.

**Comment by PingjunChen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by PingjunChen** [comment]
@pjotrp 
I misunderstood what you mean. Now DOIs are added to each referenced paper.
By the way, shall I release a new version to Zenodo again because of this update?

**Comment by pjotrp** [comment]
No worries. It is fine like this. @arfon I believe we are good to go!

**Comment by pjotrp** [comment]
@whedon set 10.5281/zenodo.2529982 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2529982" target="_blank">10.5281/zenodo.2529982</a> is the archive.

**Comment by pjotrp** [comment]
@PingjunChen and @Arafatk thank you. We'll publish soon - and great turn around times!

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/421

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/421, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/422
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01148](https://doi.org/10.21105/joss.01148)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@Arafatk - many thanks for your review here and to @pjotrp for editing this submission ✨ 

@PingjunChen - your paper is now accepted into JOSS :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01148/status.svg)](https://doi.org/10.21105/joss.01148)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01148">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01148/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01148/status.svg
   :target: https://doi.org/10.21105/joss.01148
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01148/status.svg)](https://doi.org/10.21105/joss.01148)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
