### ISSUE TITLE
[PRE REVIEW]: RAILS and Cobbler: Scaffolding and automated finishing of draft genomes using long sequences

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#115]
**Submitting author:** @warrenlr (<a href="http://orcid.org/0000-0002-9890-2293">Rene L. Warren</a>)
**Repository:** <a href="https://github.com/warrenlr/RAILS" target ="_blank">https://github.com/warrenlr/RAILS</a>
**Version:** v1.1
**Editor:** @biorelated
**Reviewer:** @andrewjpage

**What this issue is for**

Thanks for submitting your paper to JOSS @warrenlr. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @biorelated - would you be willing to edit this submission for JOSS?

**Comment by biorelated** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by biorelated** [comment]
@arfon I am happy to edit  :)

**Comment by biorelated** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by biorelated** [comment]
@andrewjpage @pjotrp would you be in a position to suggest potential reviewers for this submission? I can then followup with them? Thank you.

**Comment by andrewjpage** [comment]
I would be willing to review this.

**Comment by biorelated** [comment]
@whedon assign @andrewjpage as reviewer

**Comment by whedon** [comment]
I'm sorry @biorelated, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by biorelated** [comment]
Many thanks @andrewjpage! . @arfon let us assign @andrewjpage as a reviewer for this.

**Comment by arfon** [comment]
@whedon assign @biorelated as editor

**Comment by whedon** [comment]
OK, the editor is @biorelated

**Comment by arfon** [comment]
> Many thanks @andrewjpage! . @arfon let us assign @andrewjpage as a reviewer for this.

@biorelated looks like I broken something in Whedon. Would you be able to try this again now? We should need the following two commands:

```
@whedon assign @andrewjpage as reviewer
@whedon start review magic-word=bananas
```

**Comment by biorelated** [comment]
@whedon assign @andrewjpage as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @andrewjpage

**Comment by biorelated** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/116. Feel free to close this issue now!
