### ISSUE TITLE
[PRE REVIEW]: locBLAST: An enhanced PHP web interface to standalone NCBI BLAST+ program

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1150]
**Submitting author:** @AshokHub (<a href="http://orcid.org/0000-0003-2862-028X">Dr. T. Ashok Kumar</a>)
**Repository:** <a href="https://github.com/AshokHub/locBLAST" target ="_blank">https://github.com/AshokHub/locBLAST</a>
**Version:** v2.0
**Editor:** @pjotrp
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @AshokHub. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@AshokHub if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1150 with the following error: 

 Can't find any papers to compile :-(

**Comment by AshokHub** [comment]
Paper (.md) and Bibliography (.bib) has been uploaded to GitHub in 'papers' directory.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01150/joss.01150/10.21105.joss.01150.pdf)

**Comment by AshokHub** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01150/joss.01150/10.21105.joss.01150.pdf)

**Comment by AshokHub** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01150/joss.01150/10.21105.joss.01150.pdf)

**Comment by AshokHub** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@Kevin-Mattheus-Moerman
@arfon
@arokem
@brainstorm
@cMadan
@danielskatz
@jasonclark
@jedbrown
@karthik
@katyhuff
@kthyng
@kyleniemeyer
@labarba
@lheagy
@mgymrek
@pjotrp
@trallard
@yochannah
```

**Comment by AshokHub** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
:wave: @pjotrp - would you be willing to edit this submission for JOSS?

**Comment by AshokHub** [comment]
@pjotrp I am waiting for review.

**Comment by pjotrp** [comment]
@whedon asssing @pjotrp as editor

**Comment by pjotrp** [comment]
@whedon assing @pjotrp as editor

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp
