### ISSUE TITLE
[PRE REVIEW]: dolfin-adjoint 2018.1: automated adjoints for FEniCS and Firedrake

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1151]
**Submitting author:** @sebastkm (<a href="http://orcid.org/0000-0002-8888-6568">Sebastian Mitusch</a>)
**Repository:** <a href="https://bitbucket.org/dolfin-adjoint/pyadjoint" target ="_blank">https://bitbucket.org/dolfin-adjoint/pyadjoint</a>
**Version:** 2018.1
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @chrisrichardson

**Author instructions**

Thanks for submitting your paper to JOSS @sebastkm. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@sebastkm if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1151 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:91:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:91:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by sebastkm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01151/joss.01151/10.21105.joss.01151.pdf)

**Comment by sebastkm** [comment]
We suggest @Kevin-Mattheus-Moerman as editor for this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @chrisrichardson as reviewer

**Comment by whedon** [comment]
OK, @chrisrichardson is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @chrisrichardson for agreeing to review this work. This is a pre-review issue. Once I find more reviewers I'll open the formal review issue where the review will take place.

**Comment by Kevin-Mattheus-Moerman** [comment]
@garth-wells is this something you could review for the Journal of Open Source Software? Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@sebastkm let me know if you have any potential reviewers in mind that you think we should contact

**Comment by sebastkm** [comment]
We suggest @IgorBaratta @msiebenborn

**Comment by Kevin-Mattheus-Moerman** [comment]
@IgorBaratta @msiebenborn would you be interested in reviewing this work for the [Journal of Open Source Software (JOSS)](http://joss.theoj.org/about). The [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) focuses on [the software](https://bitbucket.org/dolfin-adjoint/pyadjoint) and a [short paper](https://github.com/openjournals/joss-papers/blob/joss.01151/joss.01151/10.21105.joss.01151.pdf). Let me know if you have any questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
To avoid further delay we will now start the review process. However, additional reviewers are still welcomed and can easily be added at a later point as well.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1292. Feel free to close this issue now!

**Comment by Kevin-Mattheus-Moerman** [comment]
@IgorBaratta I just noticed you :+1: the request to review this work? Can you confirm I can formally add you as a reviewer? Thanks!

**Comment by IgorBaratta** [comment]
> @IgorBaratta I just noticed you  the request to review this work? Can you confirm I can formally add you as a reviewer? Thanks!

@Kevin-Mattheus-Moerman , Yes! You can confirm me as a reviewer.
