### ISSUE TITLE
[PRE REVIEW]: NodeLab: A MATLAB package for meshfree node-generation and adaptive refinement

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1152]
**Submitting author:** @pankajkmishra (<a href="http://orcid.org/0000-0003-4907-4724">Pankaj K Mishra</a>)
**Repository:** <a href="https://github.com/pankajkmishra/NodeLab" target ="_blank">https://github.com/pankajkmishra/NodeLab</a>
**Version:** v1.0
**Editor:** @kyleniemeyer
**Reviewers:** @Kevin-Mattheus-Moerman, @vijaysm

**Author instructions**

Thanks for submitting your paper to JOSS @pankajkmishra. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@pankajkmishra if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@kyleniemeyer) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01152/joss.01152/10.21105.joss.01152.pdf)

**Comment by arfon** [comment]
:wave: @kyleniemeyer - the submitting author suggested you as the handling editor.

**Comment by pankajkmishra** [comment]
Hi @kyleniemeyer - I think @Kevin-Mattheus-Moerman ( already in the JOSS list) could be a potential reviewer.

**Comment by Kevin-Mattheus-Moerman** [comment]
I can review this, looks interesting.

**Comment by kyleniemeyer** [comment]
Thanks @Kevin-Mattheus-Moerman!

**Comment by kyleniemeyer** [comment]
@whedon add @Kevin-Mattheus-Moerman as reviewer

**Comment by whedon** [comment]
OK, @Kevin-Mattheus-Moerman is now a reviewer

**Comment by kyleniemeyer** [comment]
@IgorBaratta @CELavecchia @vijaysm would any of you be interested/available to review this as well?

**Comment by vijaysm** [comment]
Sorry just getting to this. I can review it.

**Comment by kyleniemeyer** [comment]
@whedon add @vijaysm as reviewer

**Comment by whedon** [comment]
OK, @vijaysm is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1173. Feel free to close this issue now!
