### ISSUE TITLE
[PRE REVIEW]: QMRTools: a mathematica toolbox for quantitative MRI analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1154]
**Submitting author:** @mfroeling (<a href="http://orcid.org/0000-0003-3841-0497">Martijn Froeling</a>)
**Repository:** <a href="https://github.com/mfroeling/QMRITools" target ="_blank">https://github.com/mfroeling/QMRITools</a>
**Version:** v2.0
**Editor:** @cMadan
**Reviewers:** @grlee77, @JoshKarpel

**Author instructions**

Thanks for submitting your paper to JOSS @mfroeling. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mfroeling if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1154 with the following error: 

 Can't find any papers to compile :-(

**Comment by mfroeling** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

```

**Comment by mfroeling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1154 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by mfroeling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #1154 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    145      0 --:--:-- --:--:-- --:--:--   147
[WARNING] Could not convert image '/tmp/tex2pdf.118/e4c024bc84d042324fc3253cdcf0eab2cad60748.shtml': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : 
  
  
  
  
  
  
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA not enough bytes
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.118/e4c024bc84d
042324fc3253cdcf0eab2cad60748.shtml (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.260 ...bc84d042324fc3253cdcf0eab2cad60748.shtml}

Looks like we failed to compile the PDF

**Comment by mfroeling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1154 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by mfroeling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1154 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by mfroeling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01154/joss.01154/10.21105.joss.01154.pdf)

**Comment by mfroeling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01154/joss.01154/10.21105.joss.01154.pdf)

**Comment by danielskatz** [comment]
👋 @cMadan - are you willing to edit this submission?

**Comment by cMadan** [comment]
@danielskatz - sure, would be happy to

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by mfroeling** [comment]
@cMadan other prefered mathematica language reviewers are taqtiqa-mark, rljacobson, acolum, chlalanne, JoshKarpel, wspr

**Comment by Kevin-Mattheus-Moerman** [comment]
@cmadan these also seem suitable reviewers (people I contacted for https://github.com/openjournals/joss-reviews/issues/889) nnadeau, davidnsousa, markus-nilsson, JianCheng

**Comment by mfroeling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01154/joss.01154/10.21105.joss.01154.pdf)

**Comment by cMadan** [comment]
@nnadeau @markus-nilsson @acolum @JoshKarpel, would you be interested and available to review this submission? Thank you for your consideration!

@Kevin-Mattheus-Moerman, thanks for the additional suggestions!

**Comment by JoshKarpel** [comment]
@cMadan Would be happy to, although I don't know anything about MRI/QMR so I won't be able to address any related technical concerns.

**Comment by nnadeau** [comment]
@cMadan, unfortunately I am not available at this time.

**Comment by acolum** [comment]
@cMadan Thank you for tagging me, but I'm also not available at this time.

**Comment by cMadan** [comment]
@JoshKarpel, thanks for letting me know! I might still include you as a reviewer, depending who else we get (e.g., someone who knows MRI well but not Mathematica).

@nnadeau @acolum, no problem, thank you for considering!

**Comment by markus-nilsson** [comment]
Thanks for asking -- unfortunately not available at the moment

**Comment by mfroeling** [comment]
@JianCheng are you available to review my submission since you have expertise in diffusion processing.

@grlee77 are you available to review my submission since you are one of the few reviewers in the list with MRI expertise.

@rljacobson are you available to review my submission as a Mathematica programmer

**Comment by rljacobson** [comment]
@mfroeling I am definitely qualified to review Mathematica code and general computer vision applications, though I do not have specific expertise with MRI imaging. I do not have any expertise in medicine, but I am quite familiar with the mathematical underpinnings of MRI if that helps. Because I start teaching quite soon, my available time is limited. If you willing to wait ~3 weeks for a completed review, I am willing to review it for you. (The guidelines suggest 2 weeks is more typical.)

**Comment by rljacobson** [comment]
@mfroeling Unfortunately, my computer vision expert had to decline. I'll try to be expedient.

**Comment by cMadan** [comment]
@grlee77 @JoshKarpel @rljacobson, I think between the three of you, there is sufficient expertise to review this submission. Let me know if you're good with this plan and I'll start the review.

**Comment by JoshKarpel** [comment]
@cMadan sounds good to me!

**Comment by grlee77** [comment]
sounds good to me as well

**Comment by cMadan** [comment]
@whedon add @grlee77 as reviewer

**Comment by whedon** [comment]
OK, @grlee77 is now a reviewer

**Comment by cMadan** [comment]
@whedon add @JoshKarpel as reviewer

**Comment by whedon** [comment]
OK, @JoshKarpel is now a reviewer

**Comment by cMadan** [comment]
@rljacobson and others tagged earlier, if you're still interested in reviewing this submission, please let me know. This work is at the intersection of a topic and programming language that don't often overlap, so adequate reviewing will likely include people who cover only part of the project's content--though I also wouldn't want there to be too many reviewers.

I'm going to start the actual review now, but can still add an additional reviewer if someone has time and interest, and would lead to a better project when it gets accepted.

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1204. Feel free to close this issue now!

**Comment by rljacobson** [comment]
@cMadan I'm sorry, I missed this notification. Yes, I am happy to review this submission. You are welcome to add me to #1204 if you wish.

**Comment by cMadan** [comment]
@rljacobson, no worries, thank you! I'll go ahead and add you as a reviewer :)
