### ISSUE TITLE
[PRE REVIEW]: LightTwinSVM: A Simple and Fast Implementation of Standard Twin Support Vector Machine Classifier

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1155]
**Submitting author:** @mir-am (<a href="http://orcid.org/0000-0002-9818-7752">A. Mir</a>)
**Repository:** <a href="https://github.com/mir-am/LightTwinSVM" target ="_blank">https://github.com/mir-am/LightTwinSVM</a>
**Version:** v0.5.0
**Editor:** @cMadan
**Reviewers:** @stefanv

**Author instructions**

Thanks for submitting your paper to JOSS @mir-am. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mir-am if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01155/joss.01155/10.21105.joss.01155.pdf)

**Comment by mir-am** [comment]
Hello
First, we are very grateful for the consideration of our paper.
Before starting the review process, we need to make some minor revisions to our paper to solve problems like an undefined reference.
However, we need an editor to be assigned. (We have suggested @arfon, Mr. Smith)

Regards,
Mir

**Comment by arfon** [comment]
:wave: @mir-am - thanks for your submission to JOSS. Please go ahead and make the changes you need to for your paper and ask @whedon to recompile your paper here with the command `whedon generate pdf`.

> However, we need an editor to be assigned. (We have suggested @arfon, Mr. Smith)

I probably won't edit this submission - it may take another few days for an editor to be assigned.

**Comment by mir-am** [comment]
@arfon - Thanks for replying.
We carefully revised our paper and would like to assign an editor for consideration of the paper

**Comment by mir-am** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01155/joss.01155/10.21105.joss.01155.pdf)

**Comment by cMadan** [comment]
@whedon assign @cmadan as editor

**Comment by cMadan** [comment]
@mir-am, thank you for your submission. Do you have any suggestions for reviewers? (See first comment in this issue for more information.)

**Comment by cMadan** [comment]
@arfon, it seems that whedon updated the first comment with me as editor, but didn't 'acknowledge' the command or assign me to the issue in Github. Has anything changed with how it's supposed to do that...?

**Comment by mir-am** [comment]
> @whedon assign @cMadan as editor

We thank you for the consideration of our paper.
@cMadan - @arfon - How can we add a caption to a table in our paper?

**Comment by mir-am** [comment]
> @mir-am, thank you for your submission. Do you have any suggestions for reviewers? (See first comment in this issue for more information.)
We suggest @glemaitre for reviewing our research work.

**Comment by cMadan** [comment]
@mir-am, this should do it:
https://pandoc.org/MANUAL.html#tables

**Comment by mir-am** [comment]
> @mir-am, this should do it:
> https://pandoc.org/MANUAL.html#tables

Thanks. 
We revised our paper.
We would like to start the review process.

**Comment by mir-am** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01155/joss.01155/10.21105.joss.01155.pdf)

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@arfon, not sure what happened earlier, but didn't seem like `@whedon` acted properly earlier. This time it worked though.

**Comment by arfon** [comment]
> @arfon, not sure what happened earlier, but didn't seem like @whedon acted properly earlier. This time it worked though.

Weird. Not sure. Seems like a minor hiccup...

**Comment by cMadan** [comment]
@glemaitre, would you be interested and available to review this submission? Thank you for your consideration!

**Comment by glemaitre** [comment]
@cMadan I'm sorry but I will not be able to review right now. I am lacking personal time to make the review and I don't want to be the latent factor.

**Comment by mir-am** [comment]
Hi
We would like to suggest @rougier for reviewing our research work.
We also welcome reviewer suggestions from the editor.

**Comment by cMadan** [comment]
@mir-am, I am asking around for additional reviewers and hopefully someone will volunteer.

I was looking at the figures in the paper, are the SVM and TwinSVM illustrations based on the same data?

**Comment by mir-am** [comment]
> @mir-am, I am asking around for additional reviewers and hopefully someone will volunteer.
> 
> I was looking at the figures in the paper, are the SVM and TwinSVM illustrations based on the same data?

Thanks.
The dataset for both illustrations is nearly the same. Data points are randomly selected from an artificial dataset. However, we can add new illustrations based on the exact same dataset.

**Comment by rougier** [comment]
I can review but it'll take me some time (3/4 weeks) because I'm a bit busy right now.

**Comment by cMadan** [comment]
@mir-am, I think it would be better if they are the exact same, thanks!

@rougier, that sounds fine to me. I won't start the review yet in case someone else is also able/interested to review, but if you could comment here when your free, I'll start the review even if no one else has volunteered.

**Comment by mir-am** [comment]
> PDF failed to compile for issue #1155 with the following error:
> 
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 
> 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
> 100 15 0 15 0 0 234 0 --:--:-- --:--:-- --:--:-- 238
> Error producing PDF.
> ! Undefined control sequence.
> \SQSPL@scan ->\futurelet \SQSPL@next
> \SQSPL@scani
> l.388 \texttt{Scikit-learn}'s SVM\label{tab:1}}
> 
> Looks like we failed to compile the PDF

@arfon @cMadan 
The paper successfully compiled on my machine using Pandoc. However, whedon cannot compile the paper and produced above error.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01155/joss.01155/10.21105.joss.01155.pdf)

**Comment by mir-am** [comment]
@arfon Thanks for fixing the error.

We would like to start the review process if possible.

**Comment by arfon** [comment]
> We would like to start the review process if possible.

@mir-am - @cMadan is still looking for reviewers here I think.

**Comment by cMadan** [comment]
@mir-am, yes, I still need to find someone to review the submission.

**Comment by cMadan** [comment]
@raamana, would you be interested and available to review this submission?

@arokem, do you have any suggestions for others who may be suitable reviewers here?

**Comment by raamana** [comment]
Thanks Chris, happy to review, this is an interesting and useful tool. However, due to prior commitments etc, I may take 4-8 weeks.

**Comment by cMadan** [comment]
@raamana, thanks! I'll see if @arokem has any suggestions, otherwise will ping you here in a few weeks and see when you're ready to start.

**Comment by raamana** [comment]
Sounds good. I'm unsubscribing for now. Please mention me so I get pinged.

**Comment by labarba** [comment]
👋 @rougier In your comment here 28 days ago you said you might be able to review this submission for JOSS? It's still waiting for reviewer assignment. Can you help us?

**Comment by labarba** [comment]
I wonder if @stefanv could help here ... Stefan: are you able to review this submission for JOSS?

**Comment by stefanv** [comment]
I'd be happy to!

**Comment by labarba** [comment]
@whedon assign @stefanv as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @stefanv

**Comment by labarba** [comment]
Let's wait a bit before starting the reviews, to get a reply from @rougier about being a second reviewer.

**Comment by cMadan** [comment]
Thanks for your help here, @labarba!

**Comment by stefanv** [comment]
OK, I'm proceeding with the review.

**Comment by stefanv** [comment]
@labarba What is JOSS policy on content recommendations?  E.g., I have some recommended language edits, as well as experiment suggestion (since there is a benchmark included in the paper).

Here's the language diffs for the authors' consideration.  I tried not to touch your sentences other than to correct grammar.

```diff
--- lighttwinsvm.md	2019-02-14 10:40:40.417605199 -0800
+++ lighttwinsvm-sjw.md	2019-02-14 10:58:44.144803880 -0800
@@ -21,25 +21,25 @@
 ---
 
 # Abstract
-This paper presents the `LightTwinSVM` program and its features. It is a simple and fast implementation of the twin support vector machine algorithm (TwinSVM). Numerical experiments on benchmark datasets shows the effectiveness of the `LightTwinSVM` program in terms of accuracy. This program can be used by researchers, students, and practitioners to solve classifications tasks.
+This paper presents the `LightTwinSVM` program and its features. It is a simple and fast implementation of twin support vector machine  algorithm (TwinSVM). Numerical experiments on benchmark datasets show the effectiveness of `LightTwinSVM` in terms of accuracy. This program can be used by researchers, students, and practitioners to solve classifications tasks.
 
 # Introduction
 
-Classification is a widely-used learning method in machine learning. The task of classification consists of training samples for which the class labels are available. On the basis of such training samples, a classifier learns a rule for predicting an unseen sample [@shalev2014]. To do a classification task, many algorithms have been proposed in machine learning literature such as Artificial Neural Network (ANN), Support Vector Machine (SVM), K-nearest neighbors (KNN), and Decision Trees. Among these classification algorithms, SVM classifier has relatively better prediction accuracy and generalization [@kotsiantis2007]. The main idea of SVM is to find the optimal separating hyperplane with the largest margin between the two classes. Figure \ref{fig:1} shows the geometric illustration of SVM classifier.
+Classification is a widely-used learning method in machine learning. The task of classification consists of training samples for which the class labels are available. On the basis of such training samples, a classifier learns a rule for predicting the label of an unseen sample [@shalev2014]. To do a classification task, many algorithms have been proposed in machine learning literature such as Artificial Neural Network (ANN), Support Vector Machine (SVM), K-nearest neighbors (KNN), and Decision Trees. Among these classification algorithms, SVM classifiers have relatively better prediction accuracy and generalization [@kotsiantis2007]. The main idea of SVM is to find the optimal separating hyperplane with the largest margin between the two classes. Figure \ref{fig:1} shows the geometric illustration of SVM classifier.
 
 ![Geometric illustration of SVM classifier.\label{fig:1}](figs/SVM.png)
 
-Over the past decade, researchers have proposed new classifiers based on the SVM [@nayak2015]. Of these extensions of SVM, twin support vector machine (TwinSVM) [@jayadeva2007] has received more attention from scholars in the field of SVM research. This may be due to the novel idea of TwinSVM which is doing classification using two non-parallel hyperplanes. Each of which is as close as possible to samples of its own class and far from samples of the other class. To show the central idea of TwinSVM graphically, Figure \ref{fig:2} shows the geometric illustration of TwinSVM classifier.
+Over the past decade, researchers have proposed new classifiers based on the SVM [@nayak2015]. Of these extensions of SVM, the twin support vector machine (TwinSVM) [@jayadeva2007] has received more attention from scholars in the field of SVM research. This may be due to the novel idea of TwinSVM which is doing classification using two non-parallel hyperplanes. Each of which is as close as possible to samples of its own class and far from samples of the other class. To show the central idea of TwinSVM graphically, Figure \ref{fig:2} shows the geometric illustration of TwinSVM classifier.
 
 ![Geometric illustration of TwinSVM classifier.\label{fig:2}](figs/TwinSVM.png)
 
-SVM has several stable software packages and implementations such as `LIBSVM` [@chang2011libsvm] and `LIBLINEAR` [@fan2008liblinear]. These packages were used to implement SVM in `Scikit-learn` [@pedregosa2011scikit] which is a widely-used machine learning package for Python programming language. To solve a classification problem with the SVM algorithm, one can use `Scikit-learn` with several lines of code in Python.
+For SVMs, there exist several stable software packages and implementations such as `LIBSVM` [@chang2011libsvm] and `LIBLINEAR` [@fan2008liblinear]. These packages were used to implement SVMs in `scikit-learn` [@pedregosa2011scikit] which is a widely-used machine learning package for Python programming language. To solve a classification problem with the SVM algorithm, one can use `scikit-learn` with only a few lines of code in Python.
 
-Even though TwinSVM is a popular classification algorithm in the field of SVM research, to best of our knowledge, it has not a free and reliable implementation with user guide on the internet. This motivated us to develop `LightTwinSVM` program to help researchers, practitioners, and students build their own classifier on the basis of `LightTwinSVM`. Moreover, this program can be used to solve classification problems. In the next section, we present `LightTwinSVM`, its features, and compare it with `Scikit-learn`'s SVM. 
+Even though TwinSVM is a popular classification algorithm in the field of SVM research, to the best of our knowledge, there exists no free and reliable implementation with a user guide on the internet. This motivated us to develop `LightTwinSVM` to help researchers, practitioners, and students build their own TwinSVM classifiers. Moreover, this program can be used to solve classification problems. In the next section, we present `LightTwinSVM`, its features, and compare it with `scikit-learn`'s SVM. 
 
 # LightTwinSVM
 
-`LightTwinSVM` program is a simple and fast implementation of TwinSVM classifier. It is mostly written in Python and its main design goals are simplicity and speed. Also, this program is free, open source, and licensed under the terms of GNU GPL v3^[https://opensource.org/licenses/GPL-3.0]. `LightTwinSVM` is built on top of `NumPy` [@walt2011], `Scikit-learn` [@pedregosa2011scikit], and `pandas` [@mckinney2011pandas].
+The `LightTwinSVM` program is a simple and fast implementation of the TwinSVM classifier. It is mostly written in Python and its main design goals are simplicity and speed. Also, this program is free, open source, and licensed under the terms of GNU GPL v3^[https://opensource.org/licenses/GPL-3.0]. `LightTwinSVM` is built on top of `NumPy` [@walt2011], `scikit-learn` [@pedregosa2011scikit], and `pandas` [@mckinney2011pandas].
 
 `LightTwinSVM` program can be used by both researchers in the field of SVM research and by students in courses on pattern recognition and machine learning. Moreover, this software can be applied to a wide variety of research applications such as text classification, image or video recognition, medical diagnosis, and bioinformatics. For example, `LightTwinSVM` was used for the numerical experiments in our previous research paper [@mir2018]. 
 
@@ -49,18 +49,18 @@
 - Since speed is one of the design goals, the **clipDCD optimization algorithm** [@peng2014] is employed which is a simple and fast external optimizer. It was improved and implemented in C++.
 - In order to solve linear or non-linear classification problems, both **linear** and **RBF kernels** are supported.
 - Multi-class classification problems can be solved using either **One-vs-One** or **One-vs-All** scheme.
-- The One-vs-One classifier is **Scikit-learn compatible**. Therefore, `Scikit-learn` tools such as GridSearchCV and cross_val_score can be employed.
+- The One-vs-One classifier is **scikit-learn compatible**. Therefore, `scikit-learn` tools such as `GridSearchCV` and `cross_val_score` can be employed.
 - To evaluate the performance of the classifier, **K-fold cross-validation** and **train/test split** are supported.
 - The optimal values of hyper-parameters can be found with **grid search**.
 - **CSV** and **LIBSVM** formats are supported for importing datasets.
 - Detailed classification results are saved in a spreadsheet file so that results can be analyzed and interpreted.
 
-In order to show the efficiency of `LightTwinSVM` program, we conducted experiments and compared it with the implementation of SVM in `Scikit-learn` on UCI^[http://archive.ics.uci.edu/ml/datasets.html] benchmark datasets. Table \ref{tab:1} shows the accuracy comparison between `LightTwinSVM` and `Scikit-learn`'s SVM.
+In order to show the efficiency of `LightTwinSVM`, we conducted experiments and compared it with the implementation of SVM in `scikit-learn` on the UCI^[http://archive.ics.uci.edu/ml/datasets.html] benchmark datasets. Table \ref{tab:1} shows the accuracy comparison between `LightTwinSVM` and `scikit-learn`'s SVM.
 
 
-Table: The accuracy comparison between `LightTwinSVM` and `Scikit-learn`'s SVM\label{tab:1}
+Table: The accuracy comparison between `LightTwinSVM` and `scikit-learn`'s SVM\label{tab:1}
 
-       Datasets                    LightTwinSVM              Scikit-learn's SVM        Difference in Accuracy   
+       Datasets                    LightTwinSVM              scikit-learn's SVM        Difference in Accuracy   
 --------------------------  --------------------------  --------------------------  -------------------------- 
       Pima-Indian                    **78.91**                    78.26                        0.65 
       Australian                     **87.25**                    86.81                        0.44 
@@ -74,7 +74,7 @@
       Titanic                        **82.04**                    81.71                        0.33 
       Mean                           **83.44**                    81.90                        1.53 
 
-From the Table \ref{tab:1}, it can be seen that `LightTwinSVM` outperforms `Scikit-learn`'s SVM on most datasets. For instance, the accuracy difference in Sonar dataset is as high as 10.74% which is a significant result. However, one may notice that the difference in accuracy between the two classifiers is not very large. To show whether a significant difference exists, statistical tests are often used in research papers on classification [@demsar2006]. Due to the limited space, comprehensive experiments with statistical tests are skipped in this paper. In summary, the experiment indicates that the `LightTwinSVM` program can be used for classification tasks and it may produce a better prediction accuracy.
+From the Table \ref{tab:1}, it can be seen that `LightTwinSVM` outperforms `scikit-learn`'s SVM on most datasets. For instance, the accuracy difference in Sonar dataset is as high as 10.74% which is a significant result. However, one may notice that the difference in accuracy between the two classifiers is not very large. To show whether a significant difference exists, statistical tests are often used in research papers on classification [@demsar2006]. Due to the limited space, comprehensive experiments with statistical tests are skipped in this paper. In summary, the experiment indicates that the `LightTwinSVM` program can be used for classification tasks and it may produce a better prediction accuracy.
 
 The source code of `LightTwinSVM`, its installation guide and usage example can be found at [https://github.com/mir-am/LightTwinSVM](https://github.com/mir-am/LightTwinSVM).
```

**Comment by stefanv** [comment]
## Reviewer questions

### General checks

- [x] **Repository:** Is the source code for this software available at the repository url?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?

Yes, but I wanted to verify whether this license also applies to the included optimizer.

Potential license breach through publication of datasets without attribution:

https://archive.ics.uci.edu/ml/citation_policy.html

- [x] **Version:** Does the release version given match the GitHub release (v0.5.0)?
- [ ] **Archive:** Does the <a target="_blank" href="http://dx.doi.org/10.5281/zenodo.13750">software archive</a> resolve?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?

No.  The installation process is non-standard for a Python library.  On my (Debian) system, the shell script (which I was hesitant to run, as I imagine many users will be), did not correctly detect Python 3 and and then asked for sudo access (at which point I aborted).

Please provide clear steps for installing manually from source.

- [ ] **Functionality:** Have the functional claims of the software been confirmed?

I will proceed with these items as soon as I am able to install.

- [ ] **Performance:** Have the performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the functionality of the software documented to a satisfactory level (e.g. API method documentation)?

I could not locate the API documentation.

- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?

Yes, but will verify once installation is completed.

- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

None that I could find.

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

Editor: is this a requirement of the `.bib` file?  Not entirely sure what is meant by "archival reference".  No DOIs are provided, as far as I can tell.

**Comment by stefanv** [comment]
First round of review completed; awaiting feedback from editors, and then updates from authors.

**Comment by mir-am** [comment]
Hi

We thank the reviewer for his valuable comments and suggestions. 
We will carefully revise the paper and LightTwinSVM program according to the reviewer's comments.

We share our responses to the comments as soon as all the reviewer's comments are addressed.

Regards,
Mir

**Comment by labarba** [comment]
Folks, this is the Pre-Review issue. We need to move to the Review issue for these conversations. I didn't hear back from @rougier, so let's rely on the expert review by @stefanv, and let me start the Review now.

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1252. Feel free to close this issue now!

**Comment by rougier** [comment]
@labarba @stefanv Sorry for the delay but I was waiting for the actual review thread to be opened. Did I miss something ? (for me we were still in the pre-review stage)

**Comment by labarba** [comment]
Yes, you are right. But I needed an affirmation from you to be added as reviewer. If I add you in the Pre-Review issue, then `whedon` automatically adds a review checklist for you in the Review issue, and adds permissions for you to edit (if you don't have them already).
