### ISSUE TITLE
[PRE REVIEW]: instrbuilder: a Python package for control of electrical instruments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1156]
**Submitting author:** @lucask07 (<a href="http://orcid.org/0000-0002-7236-7202">Lucas J. Koerner</a>)
**Repository:** <a href="https://github.com/lucask07/instrbuilder" target ="_blank">https://github.com/lucask07/instrbuilder</a>
**Version:** 0.1.0
**Editor:** @arokem
**Reviewers:** @brainstorm

**Author instructions**

Thanks for submitting your paper to JOSS @lucask07. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@lucask07 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@arokem) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01156/joss.01156/10.21105.joss.01156.pdf)

**Comment by arfon** [comment]
:wave: @arokem, the submitting author suggested you as the handling editor.

**Comment by arokem** [comment]
@whedon assign arokem as editor

**Comment by whedon** [comment]
OK, the editor is arokem

**Comment by arokem** [comment]
@lucask07 : do you have any suggestions for reviewers of this submission? Potentially someone from NSLS-II, if that is not a conflict.

**Comment by lucask07** [comment]
@arokem I suggest @casteer (Christopher Steer) who lists software for instrumentation as an interest. It would be best if the reviewer has access to a function generator, oscilloscope or similar to exercise the package.

**Comment by arokem** [comment]
Yes. I noticed that too. We'll have chances to do more proof-reading towards the end of the process as well.

**Comment by arokem** [comment]
@casteer: would you be willing to review this paper for JOSS?

**Comment by casteer** [comment]
Hi, sure looks interesting, we don't have the precise make of oscilloscope mention in the docs but they should be SCPI or VISA, so am happy to accept. The JOSS reviewer's guidelines mentions a checklist of essential features and details, if there is one, please could you post a link? (no worries, if there isn't one, I'm happy to review without it too) Kind regards, Chris.

**Comment by brainstorm** [comment]
@arokem Count me in if you need a co-reviewer, I've recently acquired a SCPI/LXI compatible oscilloscope, so perfect timing ;)

**Comment by arokem** [comment]
Thanks @brainstorm and @casteer!

**Comment by arokem** [comment]
@whedon assign casteer as reviewer

**Comment by whedon** [comment]
OK, the reviewer is casteer

**Comment by arokem** [comment]
@whedon assign @brainstorm as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @brainstorm

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1172. Feel free to close this issue now!

**Comment by arokem** [comment]
OK. I am going to close this issue now. Please head over to #1172 for more instructions and for the reviewer check-lists.
