### ISSUE TITLE
[PRE REVIEW]: Multiblock PLS: Block dependent prediction modeling for Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1158]
**Submitting author:** @lvermue (<a href="http://orcid.org/0000-0002-3403-7624">Laurent Vermue</a>)
**Repository:** <a href="https://github.com/DTUComputeStatisticsAndDataAnalysis/MBPLS" target ="_blank">https://github.com/DTUComputeStatisticsAndDataAnalysis/MBPLS</a>
**Version:** v1.0.0
**Editor:** @brainstorm
**Reviewers:** arokem

**Author instructions**

Thanks for submitting your paper to JOSS @lvermue. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@lvermue if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @brainstorm it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@brainstorm) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01158/joss.01158/10.21105.joss.01158.pdf)

**Comment by danielskatz** [comment]
👋 @brainstorm - note that the authors requested you as the editor

**Comment by brainstorm** [comment]
Thanks for the heads up @danielskatz! @khinsen, would you like to review this submission?

**Comment by brainstorm** [comment]
👋 @betatim, would you like to review this submission?

**Comment by brainstorm** [comment]
@whedon assign arokem as reviewer

**Comment by whedon** [comment]
OK, the reviewer is arokem

**Comment by brainstorm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1190. Feel free to close this issue now!
