### ISSUE TITLE
[REVIEW]: RAILS and Cobbler: Scaffolding and automated finishing of draft genomes using long sequences

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#116]
**Submitting author:** @warrenlr (<a href="http://orcid.org/0000-0002-9890-2293">Rene L. Warren</a>)
**Repository:** <a href="https://github.com/warrenlr/RAILS" target ="_blank">https://github.com/warrenlr/RAILS</a>
**Version:** v1.1
**Editor:** @biorelated
**Reviewer:** @andrewjpage
**Archive:** <a href="https://dx.doi.org/10.5281/zenodo.167092" target="_blank">https://dx.doi.org/10.5281/zenodo.167092</a>

## Status

[![status](http://joss.theoj.org/papers/0d20e540649867a13af66f5d90483433/status.svg)](http://joss.theoj.org/papers/0d20e540649867a13af66f5d90483433)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/0d20e540649867a13af66f5d90483433"><img src="http://joss.theoj.org/papers/0d20e540649867a13af66f5d90483433/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0d20e540649867a13af66f5d90483433/status.svg)](http://joss.theoj.org/papers/0d20e540649867a13af66f5d90483433)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/warrenlr/RAILS" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/warrenlr/RAILS">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.1)?
- [x] **Authorship:** Has the submitting author (@warrenlr) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by andrewjpage** [comment]
Good work @warrenlr and thanks for making all the changes I suggested.

**Comment by arfon** [comment]
Thanks for completing the review @andrewjpage. I've reopened the issue as I haven't finished all of the editorial tasks yet for this paper.

@warrenlr - one small suggestion - would you mind renaming the `gpl-3.0.md` file to `LICENSE` - this is a more 'standard' way to include a license file in a repository.

**Comment by warrenlr** [comment]
ok -- done

**Comment by arfon** [comment]
Thanks @warrenlr. At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by warrenlr** [comment]
Thank you @arfon for editing this submission.
The reviewed software is now archived, with DOI: 10.5281/zenodo.167092

Thanks,
Rene

**Comment by biorelated** [comment]
Thank you @andrewjpage for reviewing the work. @arfon over to you for acceptance.

**Comment by arfon** [comment]
@biorelated - many thanks for editing this submission. @andrewjpage - thanks for the review!

@warrenlr - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00116 🎉 🚀 💥

**Comment by warrenlr** [comment]
This is great!
@arfon, @andrewjpage, @biorelated : many thanks for the swift review and the pleasant experience!

**Comment by vchuravy** [comment]
:warning: [An error happened when generating the pdf](https://github.com/JuliaCon/proceedings-papers/actions/runs/3387758458?check_suite_focus=true).
