### ISSUE TITLE
[REVIEW]: RSeqAn: Headers and wrappers for the SeqAn library in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1160]
**Submitting author:** @aguang (<a href="http://orcid.org/0000-0003-4974-1873">August Guang</a>)
**Repository:** <a href="https://github.com/compbiocore/RSeqAn" target ="_blank">https://github.com/compbiocore/RSeqAn</a>
**Version:** v1.3.1
**Editor:** @brainstorm
**Reviewer:** @pdiakumis
**Archive:** <a href="https://doi.org/10.5281/zenodo.2558617" target="_blank">10.5281/zenodo.2558617</a>

## Status

[![status](http://joss.theoj.org/papers/d51a775d4ba4e4f256efdbfd62ac9799/status.svg)](http://joss.theoj.org/papers/d51a775d4ba4e4f256efdbfd62ac9799)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d51a775d4ba4e4f256efdbfd62ac9799"><img src="http://joss.theoj.org/papers/d51a775d4ba4e4f256efdbfd62ac9799/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d51a775d4ba4e4f256efdbfd62ac9799/status.svg)](http://joss.theoj.org/papers/d51a775d4ba4e4f256efdbfd62ac9799)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/compbiocore/RSeqAn" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@pdiakumis, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @brainstorm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/compbiocore/RSeqAn">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.3.1)?
- [x] **Authorship:** Has the submitting author (@aguang) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @pdiakumis it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01160/joss.01160/10.21105.joss.01160.pdf)

**Comment by brainstorm** [comment]
@aguang, could you please fix the table in the paper so that it displays properly? Thanks @pdiakumis for pointing it out!

**Comment by pdiakumis** [comment]
@aguang, I also believe the release version (v1.0 above) needs to match the one in your GitHub repo (v1.3.1 in the [DESCRIPTION](https://github.com/compbiocore/RSeqAn/blob/deae809018536e4f51e4bb496e605586e004756b/DESCRIPTION#L4) file (?)) - thanks!

**Comment by aguang** [comment]
@brainstorm @pdiakumis I think I've fixed the table. As for the version, I may have submitted the wrong version number, it should be v1.3.1. Is there a way for me to change that in my submission?

**Comment by brainstorm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1160 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: date, bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by brainstorm** [comment]
@aguang, could you please add the missing expected fields in the paper.md? Namely `date`/`bibliography` as stated above in the whedon output? Thanks!

**Comment by pdiakumis** [comment]
Hi @aguang,

First of all, thank you so much for submitting to JOSS!

It was my very first review, and my Rcpp/C++/SeqAn knowledge was non-existent, so apologies for the delay. On the bright side, I learnt how to use them over the afternoon and I've been blown away by the magic.

Here are a couple of comments:

* Maybe a quick note under [Usage](https://github.com/compbiocore/RSeqAn#usage) with e.g. "for a quick test/example, use `Rcpp::sourceCpp("RSeqAn_example1.cpp")`" would be great for people like myself, who might be experienced with R but not Rcpp/C++. That `Sys.setenv` note was also very helpful.

* The version issue seems to have been addressed.
* I think the only outstanding issue is with the PDF compilation, so for that see the error output above. If that gets solved, then I believe we're good to go @brainstorm (?).

Kind Regards,
Peter

**Comment by aguang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1160 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: date, bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by aguang** [comment]
@wehdon generate pdf

**Comment by aguang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1160 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: date, bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by aguang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1160 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon/author.rb:58:in `block in build_affiliation_string': Problem with affiliations for August Guang, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon/author.rb:57:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon/author.rb:57:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon.rb:109:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon.rb:109:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon.rb:106:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon.rb:106:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by aguang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01160/joss.01160/10.21105.joss.01160.pdf)

**Comment by aguang** [comment]
@pdiakumis I'm glad you found RSeqAn useful! Thanks for your comments, I've added a note under Usage with a link to the vignette as well as the C++ code from it as its own example file that can be loaded. I also updated the Installation in the README and created a tagged release for 1.3.1 which hopefully should clear up what version the JOSS paper is referring to. And it looks like the pdf is compiled now.

**Comment by brainstorm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1186/1471-2105-9-11 is OK
- http://doi.org/10.1080/00031305.2017.1375990 is OK
- http://doi.org/10.1093/bioinformatics/btp450 is OK
- http://doi.org/10.1016/j.jbiotec.2017.07.017 is OK
- http://doi.org/10.1093/bioinformatics/btp120 is OK

MISSING DOIs

- https://doi.org/10.1038/nmeth.3252 may be missing for title: Orchestrating high-throughput genomic analysis with Bioconductor

INVALID DOIs

- http://doi.org/10.1038/nmeth.1923.Fast is INVALID
```

**Comment by brainstorm** [comment]
@aguang Can you please fix the above issues with the DOIs?

**Comment by aguang** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1186/1471-2105-9-11 is OK
- http://doi.org/10.1080/00031305.2017.1375990 is OK
- http://doi.org/10.1038/nmeth.3252 is OK
- http://doi.org/10.1038/nmeth.1923 is OK
- http://doi.org/10.1093/bioinformatics/btp450 is OK
- http://doi.org/10.1016/j.jbiotec.2017.07.017 is OK
- http://doi.org/10.1093/bioinformatics/btp120 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by aguang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01160/joss.01160/10.21105.joss.01160.pdf)

**Comment by aguang** [comment]
@brainstorm Should be good now.

**Comment by brainstorm** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by brainstorm** [comment]
Great! @aguang can you please deposit the release tarball on Zenodo and come back with the resulting DOI?

**Comment by aguang** [comment]
@brainstorm 10.5281/zenodo.2558603 should be it if I did it right

**Comment by aguang** [comment]
actually there appears to already have been a Zenodo doi made for me when I made a release tag on Github: 10.5281/zenodo.2558617. Not sure which one would be better to use.

**Comment by brainstorm** [comment]
@whedon set 10.5281/zenodo.2558617 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2558617" target="_blank">10.5281/zenodo.2558617</a> is the archive.

**Comment by brainstorm** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1160 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1160 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/bin/whedon:70:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1186/1471-2105-9-11 is OK
- http://doi.org/10.1080/00031305.2017.1375990 is OK
- http://doi.org/10.1038/nmeth.3252 is OK
- http://doi.org/10.1038/nmeth.1923 is OK
- http://doi.org/10.1093/bioinformatics/btp450 is OK
- http://doi.org/10.1016/j.jbiotec.2017.07.017 is OK
- http://doi.org/10.1093/bioinformatics/btp120 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01160/joss.01160/10.21105.joss.01160.pdf)

**Comment by kyleniemeyer** [comment]
Hello @aguang, before we accept and publish your submission, could you please make some small edits to the paper? In particular, the article could use some revision at the very beginning, to satisfy these requirements:
- A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience
- A clear statement of need that illustrates the purpose of the software

(What you have now isn't too far off, but I admit as someone whose field is far from that relevant to the software, I don't quite understand what this software—or SeqAn, really—is used for. Some general description or examples of use cases in that paragraph would also help.) 

Thanks!

**Comment by aguang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01160/joss.01160/10.21105.joss.01160.pdf)

**Comment by aguang** [comment]
@kyleniemeyer is it clearer now?

**Comment by aguang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01160/joss.01160/10.21105.joss.01160.pdf)

**Comment by brainstorm** [comment]
Looks good now, thanks for the extra pair of editorial eyes, @kyleniemeyer. Should be good to accept/deposit now.

**Comment by brainstorm** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1186/1471-2105-9-11 is OK
- http://doi.org/10.1080/00031305.2017.1375990 is OK
- http://doi.org/10.1038/nmeth.3252 is OK
- http://doi.org/10.1038/nmeth.1923 is OK
- http://doi.org/10.1093/bioinformatics/btp450 is OK
- http://doi.org/10.1016/j.jbiotec.2017.07.017 is OK
- http://doi.org/10.14778/2735471.2735478 is OK
- http://doi.org/10.1093/bioinformatics/btp120 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/481

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/481, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by brainstorm** [comment]
@arfon, I think we are done and ready to accept here :)

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/484
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01160](https://doi.org/10.21105/joss.01160)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@brainstorm - please ping @openjournals/joss-eics in the future when handing off the submissions. We now have one of us on a rotation.

**Comment by arfon** [comment]
@pdiakumis - many thanks for your review here and to @brainstorm for editing this submission ✨ 

@aguang - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01160/status.svg)](https://doi.org/10.21105/joss.01160)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01160">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01160/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01160/status.svg
   :target: https://doi.org/10.21105/joss.01160
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01160/status.svg)](https://doi.org/10.21105/joss.01160)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by aguang** [comment]
Thanks! Very appreciative of the review process here and will definitely be volunteering to review with y'all in the future.
