### ISSUE TITLE
[PRE REVIEW]: KMC_Lattice v2.0: An Object-Oriented C++ Library for Custom Kinetic Monte Carlo Simulations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1161]
**Submitting author:** @MikeHeiber (<a href="http://orcid.org/0000-0002-1567-5663">Michael Heiber</a>)
**Repository:** <a href="https://github.com/MikeHeiber/KMC_Lattice" target ="_blank">https://github.com/MikeHeiber/KMC_Lattice</a>
**Version:** v2.0.0-rc.2
**Editor:** @katyhuff
**Reviewers:** @myousefi2016, @mdoucet

**Author instructions**

Thanks for submitting your paper to JOSS @MikeHeiber. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@MikeHeiber if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @katyhuff it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@katyhuff) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1161 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    115      0 --:--:-- --:--:-- --:--:--   116
Error reading bibliography ./paper.bib (line 47, column 1):
unexpected "t"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @katyhuff - the submitting author suggested you as the handling editor.

**Comment by MikeHeiber** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

```

**Comment by MikeHeiber** [comment]
@whedon generate pdf from branch joss-edits

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-edits. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1161 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    261      0 --:--:-- --:--:-- --:--:--   263
Error reading bibliography ./paper.bib (line 123, column 1):
unexpected "a"
expecting space or ","
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by MikeHeiber** [comment]
@whedon generate pdf from branch joss-edits

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-edits. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1161 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     95      0 --:--:-- --:--:-- --:--:--    96
Error reading bibliography ./paper.bib (line 159, column 1):
unexpected "v"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by MikeHeiber** [comment]
@whedon generate pdf from branch joss-edits

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-edits. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01161/joss.01161/10.21105.joss.01161.pdf)

**Comment by MikeHeiber** [comment]
@whedon generate pdf from branch joss-edits

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-edits. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01161/joss.01161/10.21105.joss.01161.pdf)

**Comment by MikeHeiber** [comment]
I have made some minor corrections to the paper, but everything is now compiled correctly and ready for review.  The joss-edits branch contains the latest version of repository.
@katyhuff Here are some suggested reviewers that I found from the list:
@arghdos 
@myousefi2016 
@jeffhammond
@jwuttke

**Comment by katyhuff** [comment]
Thanks for suggesting reviewers @MikeHeiber. 

Now, @MikeHeiber , let's ping a few fitting reviewers, with computational physics, materials science, and c++ expertise. We can start the review once two or three of them accept the request to review.

Dear reviewers,

@myousefi2016 as suggested: Thank you for volunteering, Mehrdad!
@jeffhammond as suggested: Thanks for your quick response. I appreciate your candor. No need to review this one. 
@mdoucet Mathieu, are you able to and interested in taking on this review?
@jwuttke : Joachim,  are you able to and interested in taking on this review?
@jochym : Pawel, are you able to and interested in taking on this review?

- Title: KMC_Lattice v2.0: An Object-Oriented C++ Library for Custom Kinetic Monte Carlo Simulations
- Summary: A lightweight, object-oriented C++ library that contains a general framework for creating custom kinetic Monte Carlo simulation software tools. (e.g. for simulating organic semiconductors)
- Topic: Computational Physics for Materials Science 
- Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01161/joss.01161/10.21105.joss.01161.pdf
- Submitting author: @MikeHeiber (Michael Heiber)
- Repository: https://github.com/MikeHeiber/KMC_Lattice
- Version: v2.0.0-rc.2

**Comment by katyhuff** [comment]
@whedon assign @myousefi2016 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @myousefi2016

**Comment by mdoucet** [comment]
@katyhuff I'd be available to review this submission.

**Comment by arfon** [comment]
> @whedon generate pdf from branch joss-edits

@MikeHeiber - this @whedon feature has been a little buggy in the past - did this work for you (compiling from a named branch)?

**Comment by MikeHeiber** [comment]
@arfon Also, for my last submission a few months ago, you had to compile the paper locally to get it to work, but this time everything worked as expected on my end.

**Comment by katyhuff** [comment]
@whedon add @mdoucet as reviewer

**Comment by whedon** [comment]
OK, @mdoucet is now a reviewer

**Comment by katyhuff** [comment]
Two reviewers should be sufficient. Thank you @mdoucet and @myousefi2016 for volunteering. Let's get started!

**Comment by katyhuff** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1168. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Ok team, let's head over to #1168 .
