### ISSUE TITLE
[PRE REVIEW]: pyscses - a python space charge site explicit solver

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1163]
**Submitting author:** @georgiewellock (<a href="http://orcid.org/0000-0002-1068-5889">Georgina Wellock</a>)
**Repository:** <a href="https://github.com/bjmorgan/pyscses" target ="_blank">https://github.com/bjmorgan/pyscses</a>
**Version:** v 0.9.3.2
**Editor:** @labarba
**Reviewers:** @ncclementi, @vyasr

**Author instructions**

Thanks for submitting your paper to JOSS @georgiewellock. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@georgiewellock if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by labarba** [comment]
@ncclementi — Would you be willing to volunteer a review for this submission to JOSS? You've experienced the review process as an author, so you'll know what is entailed, but have a look at the [documentation](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) to imagine what it's like from the other side. 
Let me know!

**Comment by ncclementi** [comment]
@labarba Sure, I'll be happy to do it.

**Comment by labarba** [comment]
@whedon assign @ncclementi as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ncclementi

**Comment by labarba** [comment]
:wave @vyasr — Have you reviewed for JOSS? You've published with us, I remember (quaternions!). Would you be able to help us out as second reviewer for this submission?

**Comment by labarba** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1002/bbpc.198400007 is OK
- http://doi.org/10.1016/0022-3697(85)90172-6 is OK
- http://doi.org/10.1016/S0167-2738(98)00502-5 is OK
- http://doi.org/10.1016/0167-2738(96)00316-5 is OK
- http://doi.org/10.1016/S0167-2738(02)00229-1 is OK
- http://doi.org/10.1149/1.1507597 is OK
- http://doi.org/10.1016/j.ssi.2011.07.001 is OK
- http://doi.org/10.1002/fuce.201200071 is OK
- http://doi.org/10.1016/j.ssi.2016.10.010 is OK
- http://doi.org/10.1063/1.3681169 is OK
- http://doi.org/10.1002/0470020229.ch1 is OK
- http://doi.org/10.1039/B300170A is OK
- http://doi.org/10.1023/A:1009998114205 is OK
- http://doi.org/10.1039/C6CP02177H is OK

MISSING DOIs

- https://doi.org/10.32607/20758251-2018-10-1-24-33 may be missing for title: The Surface Motion of Particles in Crystals and the Natural Roughness of Crystalline Faces
- https://doi.org/10.1063/1.117366 may be missing for title: Defect and transport properties of nanocrystalline CeO_2-x
- https://doi.org/10.1016/0079-6786(95)00004-e may be missing for title: Ionic Conduction in Space Charge Regions
- https://doi.org/10.1557/proc-492-377 may be missing for title: Combined atomistic and continuum modelling of space charge formation at the CeO_2 (111) grain boundary.

INVALID DOIs

- None
```

**Comment by labarba** [comment]
👋  @georgiewellock — have a look at your references list and check on `@whedon`'s suggestions ☝️

**Comment by labarba** [comment]
@whedon add @vyasr as reviewer

**Comment by whedon** [comment]
OK, @vyasr is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1209. Feel free to close this issue now!
