### ISSUE TITLE
[PRE REVIEW]: HODLRlib: A Library for Hierarchical Matrices

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1165]
**Submitting author:** @sivaramambikasaran (<a href="http://orcid.org/0000-0003-2978-6281">Sivaram Ambikasaran</a>)
**Repository:** <a href="https://github.com/sivaramambikasaran/HODLR" target ="_blank">https://github.com/sivaramambikasaran/HODLR</a>
**Version:** 3.1415
**Editor:** @jedbrown
**Reviewers:** @poulson

**Author instructions**

Thanks for submitting your paper to JOSS @sivaramambikasaran. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@sivaramambikasaran if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: @jedbrown - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01165/joss.01165/10.21105.joss.01165.pdf)

**Comment by jedbrown** [comment]
@whedon assign @poulson as editor

**Comment by jedbrown** [comment]
This is firmly in @poulson's wheelhouse. Opportune timing as he joins the editorial board. :tada:

**Comment by poulson** [comment]
@sivaramambikasaran I am starting to take a look and should start having feedback in the coming days.

**Comment by sivaramambikasaran** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

```

**Comment by sivaramambikasaran** [comment]
@whedon @poulson : Possible reviewers

1. @poulson
2. @klho
3. @gchavez2
4. @dfm
5. @michael-hartmann

**Comment by sivaramambikasaran** [comment]
And of course if you want the reviewers from the existing list.

1. @labarba 
2. @jedbrown 
3. @ChrisRackauckas
4. @jeffhammond
5. @wrathematics

**Comment by labarba** [comment]
Perhaps for this submission, I could edit and @poulson could review? He can also observe the editing process to learn the ropes.

**Comment by jedbrown** [comment]
@wheden assign @jedbrown as editor

**Comment by jedbrown** [comment]
@whedon add @poulson as reviewer

**Comment by whedon** [comment]
OK, @poulson is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1167. Feel free to close this issue now!

**Comment by jedbrown** [comment]
Sorry about the chaos. We'll move to #1167 for the review now.
