### ISSUE TITLE
[REVIEW]: scikit-posthocs: Pairwise multiple comparison tests in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1169]
**Submitting author:** @maximtrp (<a href="http://orcid.org/0000-0003-2586-4633">Maksim Terpilowski</a>)
**Repository:** <a href="https://github.com/maximtrp/scikit-posthocs" target ="_blank">https://github.com/maximtrp/scikit-posthocs</a>
**Version:** v0.5.1
**Editor:** @katyhuff
**Reviewer:** @mnarayan, @djmitche
**Archive:** <a href="https://doi.org/10.5281/zenodo.2639732" target="_blank">10.5281/zenodo.2639732</a>

## Status

[![status](http://joss.theoj.org/papers/c10b7f55a5206105c66428bd0e40a167/status.svg)](http://joss.theoj.org/papers/c10b7f55a5206105c66428bd0e40a167)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/c10b7f55a5206105c66428bd0e40a167"><img src="http://joss.theoj.org/papers/c10b7f55a5206105c66428bd0e40a167/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/c10b7f55a5206105c66428bd0e40a167/status.svg)](http://joss.theoj.org/papers/c10b7f55a5206105c66428bd0e40a167)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/maximtrp/scikit-posthocs" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mnarayan & @djmitche, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @katyhuff know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/maximtrp/scikit-posthocs">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.5.1
- [x] **Authorship:** Has the submitting author (@maximtrp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/maximtrp/scikit-posthocs">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.5.1
- [x] **Authorship:** Has the submitting author (@maximtrp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mnarayan, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01169/joss.01169/10.21105.joss.01169.pdf)

**Comment by djmitche** [comment]
In

> Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

I'm unfamiliar with what "should have a DOI" means.  But I don't see any DOI's in the references.  @mnarayan is that something you're familar with and could look at more deeply?

**Comment by djmitche** [comment]
I'm not aware of any further changes yet -- @maximtrp please let me know if there's something I should look at to check off another box..

**Comment by katyhuff** [comment]
@maximtrp : How is this going? I don't mean to pester, but wanted to make sure that you'd like this review to continue. One option, if you need substantial time, is to withdraw the submission (close this issue) and resubmit when you're at a new code version that will satisfy the key features that the review has uncovered.

**Comment by maximtrp** [comment]
@katyhuff Sorry for a long delay. I will finish in a few days.

**Comment by mnarayan** [comment]
@maximtrp I can see a lot of code improvements, you are almost there!
My only sticking points are related to clarifying the functionality and description of what this package offers. Even the PMCMRplus package that is the inspiration for yours is a bit opaque. This shouldn't take you too long however.

**Comment by mnarayan** [comment]
The scikit-posthocs package implements several statistical testing procedures to conduct pairwise multiple comparisons after the global null in an ANOVA has been rejected. It fills a clear gap in the python ecosystem and has been created as an analog to the `PMCMRplus` package in R. 

@maximtrp has addressed all my issues and the package implementation meets all the requirements for JOSS.

**Comment by djmitche** [comment]
@mnarayan there are a few more check-boxes in your section of the review.

@whedon commands

**Comment by djmitche** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01169/joss.01169/10.21105.joss.01169.pdf)

**Comment by djmitche** [comment]
Looks good to me!

**Comment by maximtrp** [comment]
@djmitche @mnarayan Thank you for reviews! Your comments were _very_ helpful.

**Comment by djmitche** [comment]
@katyhuff what is the status here?  I see this is still assigned to me - is there anything further required?

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by katyhuff** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1169 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    400      0 --:--:-- --:--:-- --:--:--   410
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.01169.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01169/joss.01169/10.21105.joss.01169.pdf)

**Comment by katyhuff** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by katyhuff** [comment]
Thanks so much for the ping @djmitche for the ping! It's a hectic end of the semester and I missed the notification that the comments had been handled. 

Thanks @mnarayan and @djmitche for your excellent reviews. The care you took and attention to detail that you supplied is what makes JOSS possible.

**Comment by katyhuff** [comment]
Thank you @maximtrp for a strong submission and for engaging actively in the review process! I have looked over the paper and have conducted a high level review of the code itself. Everything looks ship-shape to me and we are nearly ready to move forward with acceptance. That said, if you have a moment, I would like to see all existing references contain a DOI where possible. Some of the citations you've chosen are a bit older, and so they don't have DOIs. This is reasonable, though Pandas and SciPy both have options for newer citations if you are so inclined to use those instead. This is optional, in my opinion, since you seem to have used the preferred citations for all packages (which happen to not contain DOIs). 

At this point, it'll be good for you as well to to double check the paper, review any lingering details in your code/readme/etc., and then make an archive of the reviewed software in Zenodo/figshare/other service. Please be sure that your created DOI metadata (title, authors, etc.) matches this JOSS submission. Once that's complete, please update this thread with the DOI of the archive, and I'll move forward with accepting the submission! Until then, now is your moment for final touchups!

**Comment by maximtrp** [comment]
@katyhuff I would like to keep these references as they are indeed the preferred ones. I have created a release of *scikit-posthocs* on Zenodo. Here is the DOI: [10.5281/zenodo.2639732](https://zenodo.org/record/2639732). Everything else is okay. Thank you!

**Comment by katyhuff** [comment]
@whedon set 10.5281/zenodo.2639732 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2639732" target="_blank">10.5281/zenodo.2639732</a> is the archive.

**Comment by katyhuff** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/625

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/625, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by katyhuff** [comment]
Thanks @maximtrp for your submission, patience, and cooperation with the process!

Thank you again @mnarayan and @djmitche for your detailed reviews!

This paper should be ready to accept @openjournals/joss-eics - over to you! (Please note the discussion about DOIs, above.)

**Comment by labarba** [comment]
@whedon set v0.5.1 as version

**Comment by whedon** [comment]
OK. v0.5.1 is the version.

**Comment by labarba** [comment]
@maximtrp — I noticed the version on your Zenodo archive didn't match what we had here, went to your repo, and see your version tag as v0.5.1 ... so I updated the version. Please confirm that is what we want.

**Comment by maximtrp** [comment]
@labarba That's right. It should be v0.5.1. Thank you!

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/626
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01169](https://doi.org/10.21105/joss.01169)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @maximtrp, your JOSS paper is published! 🚀 

Big thanks to our editor: @katyhuff, and the reviewers: @mnarayan, @djmitche — your contribution to JOSS is invaluable! 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01169/status.svg)](https://doi.org/10.21105/joss.01169)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01169">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01169/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01169/status.svg
   :target: https://doi.org/10.21105/joss.01169
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01169/status.svg)](https://doi.org/10.21105/joss.01169)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
