### ISSUE TITLE
[PRE REVIEW]: Kactus2: A graphical EDA tool built on the IP-XACT standard

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#117]
**Submitting author:** @TermosPullo (<a href="http://orcid.org/0000-0003-2254-3332">Janne Virtanen</a>)
**Repository:** <a href="https://sourceforge.net/p/kactus2/code/HEAD/tree/trunk/" target ="_blank">https://sourceforge.net/p/kactus2/code/HEAD/tree/trunk/</a>
**Version:** 3.2.173
**Editor:** @labarba
**Reviewer:** @jflorence

**What this issue is for**

Thanks for submitting your paper to JOSS @TermosPullo. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
Thanks for submitting this @TermosPullo. It's not clear from your submission or the documentation whether it meets our submission guidelines. In particular we require that (quoting from http://joss.theoj.org/about#author_guidelines):

> - Your software should have a research application
> -Should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler)

Could you confirm that this submission meets these criteria? In particular, what research problem is does this software solve?

**Comment by TermosPullo** [comment]
Kactus2 is a very large software suite for Model Driven Architecture (MDA) paradigm. The background was UML2.0-based HW/SW co-design, but we switched from UML2.0 to IP-XACT standard in 2009. Still the same principles apply, and the tool enables the development of system models at varying abstractions and modeling languages. The final goal is to fully automate the system design process starting from very high abstraction, the tool and its plugins performing automated transforms and finally producing executables and binaries for both HW and SW implementation.

**Comment by arfon** [comment]
> Kactus2 is a very large software suite for Model Driven Architecture (MDA) paradigm. The background was UML2.0-based HW/SW co-design, but we switched from UML2.0 to IP-XACT standard in 2009. Still the same principles apply, and the tool enables the development of system models at varying abstractions and modeling languages.

Thanks for the background @TermosPullo. Apologies for restating my original question (this is very probably my ignorance here) but is MDA a topic of academic research?

**Comment by TermosPullo** [comment]
MDA is the term used by omg.org that is a standardization organization. However, there is active research community that feeds their results to the standardization. The same applies to IP-XACT, standardized by IEEE. Our role is to propose new features and extension to the standards, as well as carry out independent research that might never end up in a standard. Despite MDA is a reserved word, the fundamental idea is system modeling and refining the models by series of transformations until it can be realized. The benefit is that the system can be specified independent of the implementation platform that can change over time or its capabilities change.

**Comment by labarba** [comment]
I have been in contact with the following people to help review or suggest reviewers:

Marilyn Wolf, School of ECE, Georgia Institute of Technology
http://www.ece.gatech.edu/research/labs/esl/wolf.html

Yung-Hsiang Lu, Associate Professor, ECE Purdue University
http://engineering.purdue.edu/HELPS/

In both cases, I have explained by email how JOSS works, and have provided links to previous review threads, as examples. I await for their commitment or suggestions for alternate reviewers. Will update here.

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@whedon assign @jflorence as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jflorence

**Comment by labarba** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/151. Feel free to close this issue now!
