### ISSUE TITLE
[PRE REVIEW]: AxoPy: A Python Library for Implementing Human-Computer Interface Experiments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1170]
**Submitting author:** @ixjlyons (<a href="http://orcid.org/0000-0002-9143-8459">Kenneth Lyons</a>)
**Repository:** <a href="https://github.com/axopy/axopy" target ="_blank">https://github.com/axopy/axopy</a>
**Version:** v0.2.1
**Editor:** @trallard
**Reviewers:** @lucask07, @peircej

**Author instructions**

Thanks for submitting your paper to JOSS @ixjlyons. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ixjlyons if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @trallard it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@trallard) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1170 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     80      0 --:--:-- --:--:-- --:--:--    80
Error reading bibliography ./references.bib (line 14, column 5):
unexpected "t"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @trallard - the submitting author suggested you as the handling editor.

@ixjlyons - looks like there is a problem compiling your paper. Please take a look and make your fixes in `master`. Whedon can then be asked to recompile the paper with `@whedon generate pdf`

**Comment by ixjlyons** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01170/joss.01170/10.21105.joss.01170.pdf)

**Comment by ixjlyons** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01170/joss.01170/10.21105.joss.01170.pdf)

**Comment by trallard** [comment]
Hello @ixjlyons 👋 apologies for the delay in starting the review. Let's start by pinging a few fitting reviewers, with Python expertise as well as some background in signal processing, experimental design, or biomedical related data. We can start the review once two or three of them accept the request to review.

---

Dear potential reviewers (@lucask07, @ThomasA , @hooman650, @kczimm  ),

Based on your expertise I would like to ask if you can help us out with a submission to JOSS ([The Journal of Open Source Software](http://joss.theoj.org/)), where I’m an editor. The details of the submission are:


**Title**: AxoPy: A Python Library for Implementing Human-Computer Interface Experiments
**Summary:** Axo-Pythonic synapses are those in which an axon synapses upon a Python program. AxoPy aims to facilitate such connections between electrophysiolgical signals and machines by making it easy for researchers to develop human-computer interface experiments. 
**Documentation**: [https://axopy.readthedocs.io/en/latest/index.html](https://axopy.readthedocs.io/en/latest/index.html)
**Article Proof**: [https://github.com/openjournals/joss-papers/blob/joss.01170/joss.01170/10.21105.joss.01170.pdf](https://github.com/openjournals/joss-papers/blob/joss.01170/joss.01170/10.21105.joss.01170.pdf)
**Submitting author:** @ixjlyons Kenneth Lyons
**Repository:** https://github.com/3dct/open_iA
**Version**: v0.2.1

@lucask07 : Lucas, are you able to and interested in taking on this review?
@ThomasA: Thomas, are you able to and interested in taking on this review?
@hooman650: Hooman, are you able to and interested in taking on this review?
@kczimm: Kendal, , are you able to and interested in taking on this review?

Your prompt response is appreciated. Please see [https://joss.readthedocs.io/en/latest/reviewer_guidelines.html](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) for more information about reviewer criteria and the process if it is new to you.

**Comment by ixjlyons** [comment]
@trallard: I noticed that @peircej is in the spreadsheet of reviewers --- he's the author of PsychoPy, which is a fairly closely related experiment-building framework. I imagine he'd be a good reviewer for AxoPy if he has the time.

Also, the link to the repository should be: https://github.com/axopy/axopy.

**Comment by trallard** [comment]
thanks @lucask07 

@peterjc would you be able and interested in reviewing this submission for JOSS?

**Comment by trallard** [comment]
@whedon add @lucask07 as reviewer

**Comment by whedon** [comment]
OK, @lucask07 is now a reviewer

**Comment by peircej** [comment]
I'd be happy to review if still needed

**Comment by kczimm** [comment]
I’m sorry I can’t review at this time for recent family reasons.

**Comment by peterjc** [comment]
This sounds quite outside my area of expertise to review, so no.

**Comment by ThomasA** [comment]
I'm sorry, but human-computer interfaces are not my area.

**Comment by trallard** [comment]
@whedon add @peircej as reviewer

**Comment by whedon** [comment]
OK, @peircej is now a reviewer

**Comment by trallard** [comment]
Thanks everyone for replying to the reviewer request.

@ixjlyons @lucask07 @peircej we are ready to start the review so I am going to create the review issue and close this one

**Comment by trallard** [comment]
@whedon start review
