### ISSUE TITLE
[REVIEW]: COSplay: Contrast Optimized Stimulation Player

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1171]
**Submitting author:** @TheChymera (<a href="http://orcid.org/0000-0001-7037-2449">Horea-Ioan Ioanas</a>)
**Repository:** <a href="https://github.com/IBT-FMI/COSplay/" target ="_blank">https://github.com/IBT-FMI/COSplay/</a>
**Version:** 1.1.1
**Editor:** @arokem
**Reviewers:** @effigies, @tanselbaran
**Archive:** <a href="https://doi.org/10.5281/zenodo.3338391" target="_blank">10.5281/zenodo.3338391</a>

## Status

[![status](http://joss.theoj.org/papers/3ee7ef4edc7b537e19f89225d1d96139/status.svg)](http://joss.theoj.org/papers/3ee7ef4edc7b537e19f89225d1d96139)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/3ee7ef4edc7b537e19f89225d1d96139"><img src="http://joss.theoj.org/papers/3ee7ef4edc7b537e19f89225d1d96139/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/3ee7ef4edc7b537e19f89225d1d96139/status.svg)](http://joss.theoj.org/papers/3ee7ef4edc7b537e19f89225d1d96139)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/IBT-FMI/COSplay/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@damaggu & @effigies, please carry out your reviews in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/IBT-FMI/COSplay/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.1.1)?
- [x] **Authorship:** Has the submitting author (@TheChymera) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/IBT-FMI/COSplay/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.1.1)?
- [x] **Authorship:** Has the submitting author (@TheChymera) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @damaggu it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01171/joss.01171/10.21105.joss.01171.pdf)

**Comment by arokem** [comment]
Hey @effigies/@damaggu: have you had a chance to take a look?

**Comment by effigies** [comment]
Ah, no. Thanks for the reminder. I'll make time this week.

**Comment by effigies** [comment]
RE conflicts of interest, I've met @TheChymera in person within the last 4 years (Scipy 2017), and we've collaborated (mostly in the form of PR review) separately on [Nipype](https://github.com/nipy/nipype/).

Also, this week piled up on me, and there's no chance I'll have a proper review today. I will aim for next Wednesday.

**Comment by arokem** [comment]
Hi @effigies: the in-person meeting does not constitute a COI, in my opinion.

I am not sure whether the software collaboration constitutes COI, though. Let's check with the EIC. @arfon : the author of this paper and the reviewer have collaborated in code review on another software package (nipype, mentioned above). Does this constitute a COI that should disqualify @effigies from reviewing this paper? It is "work that is funded or published" only in the sense that that software project receives funding and is publicly available, but I believe that the two have not been paid from the same source of funding or been co-authors on any publication resulting from that software (but may in the future be). Should I find another reviewer for this?

**Comment by danielskatz** [comment]
Neither of these are a COI.

**Comment by damaggu** [comment]
@arokem, @danielskatz  Sorry, I'll make some time this week as well. Regarding COI: I'm actually collaborating with @TheChymera on other projects, but haven't been involved in the development of COSplay. Does this constitute a problem? Regards

**Comment by danielskatz** [comment]
> @arokem, @danielskatz Sorry, I'll make some time this week as well. Regarding COI: I'm actually collaborating with @TheChymera on other projects, but haven't been involved in the development of COSplay. Does this constitute a problem? Regards

Yes, @arokem should try to find another reviewer in this case.

**Comment by damaggu** [comment]
@danielskatz Just wanted to point out that, @TheChymera is not the first author. I haven't interacted with the first outer, in case that makes a difference regarding COI.

**Comment by danielskatz** [comment]
But he's the submitting author.  In my opinion, this is enough of a conflict with the submission that you shouldn't be asked to review it.

**Comment by effigies** [comment]
This is going to be a hard thing to get a complete review for, then. The reason we have two reviewers is that we need one with access to the hardware.

**Comment by danielskatz** [comment]
JOSS allows recording of the COI and waiving it if that's the best case for the submission.  If @arokem thinks that how the review should proceed, it can.

**Comment by arokem** [comment]
Yes. This submission is hard enough to review as it is, and the number of potential reviewers so small, that I think that we should go ahead with that in mind. Considering the review is open, it will be straightforward to see that the review is being done in earnest, despite COI.

**Comment by damaggu** [comment]
@arokem @danielskatz I've found actually another potential reviewer on campus @tanselbaran, that would fulfil both the proximity and the COI requirement. Therefore I'd propose him as reviewer. Would that work?

**Comment by danielskatz** [comment]
I defer to @arokem

**Comment by arokem** [comment]
Thanks for finding an alternate reviewer! @tanselbaran: would you be willing to review this paper for JOSS? If you are, we can excuse @damaggu and move on with this with you as the reviewer. I'll have to figure out how to add you here.

**Comment by tanselbaran** [comment]
Sure, I would be willing to review this paper.

**Comment by arokem** [comment]
@whedon remove @damaggu as reviewer

**Comment by whedon** [comment]
OK, @damaggu is no longer a reviewer

**Comment by arokem** [comment]
@whedon add @tanselbaran as reviewer

**Comment by whedon** [comment]
OK, @tanselbaran is now a reviewer

**Comment by arokem** [comment]
It looks like I managed to switch you two off as reviewers, but this doesn't seem to change the names in the checklists at the top of the review.

@tanselbaran : please use @damaggu's section at the top of the page to mark progress on the review. 

Thanks everyone!

**Comment by arokem** [comment]
Aha - found out how to do that. You now have your own section, @tanselbaran! Sorry for all the comments 😄

**Comment by labarba** [comment]
👋  @effigies, @tanselbaran — Can you give us a status update? We see a few items are checked off, but looks like @tanselbaran has not started yet. How are things looking?

**Comment by tanselbaran** [comment]
Sorry for the delay, I was away at a winter school last week. I am currently working on it, and will be done as soon as possible (i.e. by Friday the latest)

**Comment by effigies** [comment]
Ah, I'm sorry. I'm currently in the middle of a couple very busy weeks, so I will try to finish after April 9.

**Comment by tanselbaran** [comment]
By the way, I am a PhD student in the same university and department as the authors, but in different institutes and fields of research. I have never met any of them in person nor collaborated with them on any project. So there are no issues for me to review this work, right?

**Comment by arokem** [comment]
No problem, @tanselbaran

**Comment by arokem** [comment]
Hey @effigies, @tanselbaran : have either of you had a chance to take a look?

**Comment by tanselbaran** [comment]
@arokem  Sorry for the delay. Yes, I have been looking into it further. I think this would be a useful package, but I currently have some concerns regarding the items that I didn't check off on the list. I am not familiar with the level of detail that is expected from the authors for the documentation and the example tests, but I couldn't really see any example usage or a simple test provided by the authors either in the repository or on the readthedocs page. There is a standalone test provided for the hardware and a very nice video provided on how to assemble the hardware, but the main scope of this publication is the software package, is that correct? 

There is also quite a detailed documentation of individual functions that are part of the package. However, as someone who is completely unfamiliar with this package, I am quite lost on a higher level as to how I can get started with doing anything with this package, if that makes any sense. Maybe it would be more helpful for the future users if the authors could an example case of, for instance, how to generate a simple pulse train by using the COSplay package. That's why I refrain from checking off the items "Example usage" and "Automated Tests" at the moment. Since I couldn't get to test the function of the package, I am also refraining from checking off the "Functionality" item for now. I checked off the "Functionality documentation" item since the authors seems to have done a satisfactory job for documenting the functions included in the package. 

As for the "Community guidelines", I couldn't really see any clear guidelines for future developers anywhere on the repository or the documentation page, but that might be just me not finding it. @effigies , did you see anything along those lines? 

@arokem, please let me know if you have any questions or need further comments on any of the issues I have mentioned.

**Comment by arokem** [comment]
@tanselbaran : thank you for your comments. These are all well within the scope of this review and should be addressed in a revision.

**Comment by effigies** [comment]
Hi all, sorry about the delay as well. I've left the Functionality section of the review to @tanselbaran as discussed above. My concerns remain mostly with the documentation. In addition to the below, the documentation does not appear to be hosted, and I built it myself. I don't know if web-accessible documentation is a requirement for JOSS, so I'm just noting that.

> ### Documentation
> 
>  **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?

This is present in the paper but not the documentation.

> **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

I see that dependencies are not listed in `setup.py`. Is there a principled reason not to do this? Also, as a Python package, people may expect it to be pip installable from PyPI. (I did install with `pip install .`, but being able to say `pip install COSplay==1.1.1` would be easier.)

> **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

I didn't see anything that really looked like this.

> **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?

There are tests of the client/server connection. The documentation has what appears to be a reasonable level of detail, but without a board, any gaps will not be evident to me. I'm checking this, with the understanding that the @tanselbaran's functionality checks will verify these.

> **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

These seem to be missing.

**Comment by TheChymera** [comment]
@tanselbaran @effigies thank you for your comments. Could you please open issues ont he package so that I know exactly what I should add, and we can keep better track of when this has been resolved?

Regarding hosted docs, I do not thing this is required by JOSS, but they do exist:

https://cosplay.readthedocs.io/en/latest/?badge=latest

**Comment by TheChymera** [comment]
Regarding the other issues of contributing guidelines and dependencies, these have now been resolved. If there is anything else left, please create an issue.

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01171/joss.01171/10.21105.joss.01171.pdf)

**Comment by arokem** [comment]
@TheChymera : thank you for the quick turnaround! 

@tanselbaran , @effigies : when you get a chance, could you please take another look?

**Comment by effigies** [comment]
@arokem My two outstanding issues, corresponding to **A statement of need** and **Example usage**: https://github.com/IBT-FMI/COSplay/issues/37

For **Functionality**, **Performance** and **Automated tests**, I'm deferring to @tanselbaran's assessment of these and leaving them unchecked until he checks them off.

**Comment by arokem** [comment]
@tanselbaran : where do you stand on testing the functionality of the software?

**Comment by tanselbaran** [comment]
I was on vacation last week, but I can take a look this week. I opened an issue for the missing example usage and tests--I think I would need to have those available to test functionality.

**Comment by arokem** [comment]
Hi @tanselbaran : were you able to take another look at this?

**Comment by arokem** [comment]
Checkin in about this again: @tanselbaran -- any progress on your review?

**Comment by danielskatz** [comment]
👋 @tanselbaran - just a ping...  & @arokem, if there's no response soon, please try email

**Comment by tanselbaran** [comment]
Dear all,

My apologies for the long delay. I just got around to testing the hardware, as things have been quite busy with my project. 

After following the steps that are provided by the authors in the documentation of the repository, I verify that the device performs the test stimulus from all output channels with the specified frequencies and pulse widths. Thus, I am checking the functionality, performance and automated test items. 

Two minor improvements to be made in the automated test description: 
-The actual folder name in the device is named "sequence_library" rather than "sequences" as mentioned in the readme. Fixing that would remove any confusions from the user side. 
-It wasn't very clear to me what the "amplitude" mentioned in the sequence.tsv files was. I am not sure what the 0.6 and 0.5 in rows 6 and 7 are referring to in the table.  According to SI units as mentioned by the readme file, they should be referring to values in Volts, but I believe that's not the case. As I could measure, the amplitude of the output pulse was 2 V for Channel 5 and 1.5 V for Channel 6.

Please let me know if there are any questions.

**Comment by arokem** [comment]
Hello @TheChymera : looks like just a few small comments to address from @tanselbaran, in addition to previous comments from @effigies (described in https://github.com/openjournals/joss-reviews/issues/1171#issuecomment-488434380). Please let me know when you've had a chance to address these.

**Comment by danielskatz** [comment]
👋 @TheChymera - How are you doing on the changes?

**Comment by TheChymera** [comment]
@danielskatz @arokem sorry for the long delay, I too have been sidetracked by my thesis.

Addressing @effigies ' open concerns: https://github.com/IBT-FMI/COSplay/commit/ba9406744637701d1d586a28551e653960d4041b

Addressing @tanselbaran 's concerns: https://github.com/IBT-FMI/COSplay/commit/413c49149282bbbd39e5ea322fed492ac7aed724
Regarding the question about the amplitude: it is clarified [in the first two paragraphs, here](https://github.com/IBT-FMI/COSplay/blob/master/documentation/pyboard.rst#circuit). This section was now also linked to in the README overview: https://github.com/IBT-FMI/COSplay/commit/799f50d180375c8de17abac804e5dc866f60e328

**Comment by effigies** [comment]
My concerns were satisfied, and I'm checking off the boxes that I deferred to @tanselbaran's judgment, as he has checked those.

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arokem** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01171/joss.01171/10.21105.joss.01171.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/sdata.2016.44 is OK
- 10.5281/zenodo.1044033 is OK
- 10.5281/zenodo.573368 is OK
- 10.6084/m9.figshare.7227626.v1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arokem** [comment]
@tanselbaran : just to confirm -- are your comments all addressed?

**Comment by tanselbaran** [comment]
Yes, everything looks good to me.

**Comment by arokem** [comment]
Great. I think that we ready to proceed with this. 

@TheChymera : could you please create an archive of the software, as it is currently, or of a new release (e.g., on https://zenodo.org) and post the DOI here?

**Comment by TheChymera** [comment]
@arokem thank you!

10.5281/zenodo.3338391
https://zenodo.org/record/3338391#.XS3-FqSxWw4

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.3338391 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3338391" target="_blank">10.5281/zenodo.3338391</a> is the archive.

**Comment by arokem** [comment]
@openjournals/joss-eics : I believe this paper is ready for your final review.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/836

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/836, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@TheChymera  - can you accept https://github.com/IBT-FMI/COSplay/pull/39 please to fix an incorrect ; and slightly make the sentence that contains it more clear?

**Comment by TheChymera** [comment]
@danielskatz merged. Do I need to update the archive now on zenodo?

**Comment by TheChymera** [comment]
@danielskatz merged. Do I need to update the archive now on zenodo?

**Comment by danielskatz** [comment]
no, we're concerned with the software and not the paper source in the archive

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01171/joss.01171/10.21105.joss.01171.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/837

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/837, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1151180986987765760) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/838
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01171](https://doi.org/10.21105/joss.01171)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @effigies & @tanselbaran for reviewing and @arokem for editing!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01171/status.svg)](https://doi.org/10.21105/joss.01171)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01171">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01171/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01171/status.svg
   :target: https://doi.org/10.21105/joss.01171
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01171/status.svg)](https://doi.org/10.21105/joss.01171)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
