### ISSUE TITLE
[PRE REVIEW]: BoltzMM: an R package for maximum pseudolikelihood estimation of fully-visible   Boltzmann machines

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1174]
**Submitting author:** @andrewthomasjones (<a href="http://orcid.org/0000-0003-1324-703X">Andrew Jones</a>)
**Repository:** <a href="https://github.com/andrewthomasjones/BoltzMM" target ="_blank">https://github.com/andrewthomasjones/BoltzMM</a>
**Version:** 0.1.3
**Editor:** @yochannah
**Reviewers:** @ja-thomas, @schalkdaniel

**Author instructions**

Thanks for submitting your paper to JOSS @andrewthomasjones. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@andrewthomasjones if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @yochannah it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@yochannah) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01174/joss.01174/10.21105.joss.01174.pdf)

**Comment by arfon** [comment]
:wave: @yochannah - the submitting author suggested you as the handling editor.

**Comment by yochannah** [comment]
Sounds good! @andrewthomasjones - do you have anyone you'd like to suggest for review? No worries if not!

**Comment by andrewthomasjones** [comment]
I don't really have anyone to suggest sorry.

**Comment by yochannah** [comment]
@andrewthomasjones No worries - thankfully our reviewer volunteer list does have a lot of Machine learning + R users so hopefully it won't be too hard to find someone (famous last words, I know! 😆 )

@ja-thomas @schalkdaniel - can we interest you in reviewing this paper by any chance?

**Comment by ja-thomas** [comment]
happy to do it. I guess @schalkdaniel might be suited a bit better, due to his RCPP experience, but if he declines I can do it as well :)

**Comment by schalkdaniel** [comment]
Hi, sorry for not responding till now. I can do the review. :)

**Comment by yochannah** [comment]
@schalkdaniel thank you both for agreeing to review! 

@ja-thomas I would like to proceed with two reviewers so I'll take up your offer too. Thank you!

**Comment by yochannah** [comment]
@whedon assign @ja-thomas as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ja-thomas

**Comment by yochannah** [comment]
@whedon add @schalkdaniel as reviewer

**Comment by yochannah** [comment]
@whedon start review

**Comment by yochannah** [comment]
Alright - @andrewthomasjones @ja-thomas @schalkdaniel let's hop over to #1193 to start the review!
