### ISSUE TITLE
[PRE REVIEW]: plfMA: a Graphical User Interface for various Graphs of the Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1176]
**Submitting author:** @DHAMMAPALB (<a href="http://orcid.org/0000-0001-6729-1699">DHAMMAPAL BHARNE</a>)
**Repository:** <a href="https://github.com/DHAMMAPALB/plfMA" target ="_blank">https://github.com/DHAMMAPALB/plfMA</a>
**Version:** 1.0.4
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @DHAMMAPALB. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@DHAMMAPALB if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1176 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
Thanks for your submission to JOSS @DHAMMAPALB. Unfortunately this submission is not acceptable to JOSS as it falls into the 'minor utility' category:

> - The software should be feature complete (no half-baked solutions) and designed for maintainable extension (not one-off modifications). Minor ‘utility’ packages, including ‘thin’ API clients, are not acceptable.
