### ISSUE TITLE
[PRE REVIEW]: BladeX: Python Blade Morphing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1178]
**Submitting author:** @mtezzele (<a href="http://orcid.org/0000-0001-9747-6328">Marco Tezzele</a>)
**Repository:** <a href="https://github.com/mathLab/BladeX" target ="_blank">https://github.com/mathLab/BladeX</a>
**Version:** v0.1
**Editor:** @labarba
**Reviewers:** @benoitpaillard, @Juanlu001

**Author instructions**

Thanks for submitting your paper to JOSS @mtezzele. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mtezzele if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1178 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    257      0 --:--:-- --:--:-- --:--:--   254
100    15    0    15    0     0    256      0 --:--:-- --:--:-- --:--:--   254
Error reading bibliography ./paper.bib (line 22, column 9):
unexpected "J"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by mtezzele** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01178/joss.01178/10.21105.joss.01178.pdf)

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@mtezzele — I wonder if you'd rather use the word "morphing" instead of "deformation" in the title. When I read "deformation" I think of the elastic or plastic deformation of engineered objects under stress.

**Comment by labarba** [comment]
Also, it would help a lot if you were able to suggest some names as potential reviewers. Your submission is in an area that we don't see a lot of open-source software, as it's mainly design engineering. If you know of any other software in this field, please give us the lead (and you might think of citing them in the paper).

**Comment by mtezzele** [comment]
@labarba thank you very much for your suggestions. I will do the modifications and ask few people if they are available as potential reviewers. I will let you know ASAP.

**Comment by mtezzele** [comment]
We have the first potential reviewer: @benoitpaillard

**Comment by mtezzele** [comment]
Found also the second reviewer: @spiani

**Comment by labarba** [comment]
Thank you, @mtezzele — that helps a lot. 

👋  @benoitpaillard, @spiani — would you be willing to sign-up as reviewers for JOSS? 
http://joss.theoj.org/reviewer-signup.html
That will give me more information about your areas of expertise (but also leaves you open for future review invitations! ... which you can always decline, of course).
If not, you could email me with your real name and a few words about your expertise. Thanks! 🙏 
Do take a look at the [JOSS Review Process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

**Comment by benoitpaillard** [comment]
Hi, I just signed up to JOSS but got no email back. Let me know if that is normal.

**Comment by labarba** [comment]
@whedon assign @benoitpaillard as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @benoitpaillard

**Comment by spiani** [comment]
I have registered on JOSS, but I also have received no feedback. Could you please add me as a reviewer? Thank you

**Comment by arfon** [comment]
> I have registered on JOSS, but I also have received no feedback. Could you please add me as a reviewer? Thank you

We have you as a potential reviewer in our spreadsheet now (although I note you didn't specify what are your areas if interest/specialist topics). I'm not sure if @labarba is planning on asking for your help reviewing this submission - @labarba?

**Comment by labarba** [comment]
@spiani — Could you send me an email with your real name and links or info about your background? At the moment, I have little to go on (just the author's mention) to make the assignment. Thank you!

**Comment by Juanlu001** [comment]
:wave: Hi! @labarba told me about this submission on Twitter and I'd like to review it. I already signed up as a reviewer.

**Comment by labarba** [comment]
@whedon add @Juanlu001 as reviewer

**Comment by whedon** [comment]
OK, @Juanlu001 is now a reviewer

**Comment by spiani** [comment]
@labarba For sure. Where can I send you a brief description of my background?

**Comment by labarba** [comment]
I'm going to start this review with the two reviewers already assigned—thanks for being willing to contribute, @spiani, but I didn't hear from you and I'd like to move things along.

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1203. Feel free to close this issue now!

**Comment by spiani** [comment]
@labarba Sorry for the delayed answers, but I have been quite busy in the last few days. I am happy that you have found anyway some reviewers for your project and I hope I can be of some help next time!
