### ISSUE TITLE
[PRE REVIEW]: stats19: A package for working with open road crash data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1180]
**Submitting author:** @robinlovelace (<a href="http://orcid.org/0000-0001-5679-6536">Robin Lovelace</a>)
**Repository:** <a href="https://github.com/ropensci/stats19" target ="_blank">https://github.com/ropensci/stats19</a>
**Version:** 0.1.1
**Editor:** @arfon
**Reviewers:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @robinlovelace. The JOSS editor @karthik, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@robinlovelace if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@karthik) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01180/joss.01180/10.21105.joss.01180.pdf)

**Comment by arfon** [comment]
@Robinlovelace - could you link to the rOpenSci onboarding issue here please?

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1181. Feel free to close this issue now!
