### ISSUE TITLE
[REVIEW]: VIVO: a system for research discovery

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1182]
**Submitting author:** @mconlon17 (<a href="http://orcid.org/0000-0002-1304-8447">Michael Conlon</a>)
**Repository:** <a href="https://github.com/vivo-project/VIVO" target ="_blank">https://github.com/vivo-project/VIVO</a>
**Version:** v1.10.0
**Editor:** @jasonclark
**Reviewer:** @sonal-raj
**Archive:** <a href="https://doi.org/10.5281/zenodo.2639714" target="_blank">10.5281/zenodo.2639714</a>

## Status

[![status](http://joss.theoj.org/papers/d08957ac44d38d23c10f073872c8c5b4/status.svg)](http://joss.theoj.org/papers/d08957ac44d38d23c10f073872c8c5b4)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d08957ac44d38d23c10f073872c8c5b4"><img src="http://joss.theoj.org/papers/d08957ac44d38d23c10f073872c8c5b4/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d08957ac44d38d23c10f073872c8c5b4/status.svg)](http://joss.theoj.org/papers/d08957ac44d38d23c10f073872c8c5b4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/vivo-project/VIVO" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sonal-raj, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @jasonclark know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/vivo-project/VIVO">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.10.0)?
- [x] **Authorship:** Has the submitting author (@mconlon17) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @sonal-raj it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01182/joss.01182/10.21105.joss.01182.pdf)

**Comment by jasonclark** [comment]
@sonal-raj Thanks for making time for this review later this month. I/We appreciate it. Checklist and instructions are above. Let me know if schedules change. Hope the conference goes well.  cc @mconlon17

**Comment by labarba** [comment]
👋 @sonal-raj — I see from a [comment](https://github.com/openjournals/joss-reviews/issues/943#issuecomment-454131124) in the Pre-review issue that you agreed to get to this review by the end of January. We have a few items ticked off on your review checklist, so it looks like you did get started! Do you have an idea when you might get finished, though?

**Comment by sonal-raj** [comment]
@labarba - I am done with most of the review. I will update it by this weekend. Apologies for the delay, been drowning in work of late!

**Comment by sonal-raj** [comment]
The VIVO software has been reviewed against all the recommended criteria in the checklist. The installation, functionality and documentation are sound and the current version is operational without issues. I recommend the acceptance of this submission.

**Comment by labarba** [comment]
@jasonclark — this one is ready for your final checks.

**Comment by jasonclark** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01182/joss.01182/10.21105.joss.01182.pdf)

**Comment by jasonclark** [comment]
Hi, @mconlon17. We are close to finishing this paper. There is a final step where you make an archive of the software in [Zenodo](https://zenodo.org/) and report the DOI. Can you do that and let me know the DOI here?

**Comment by mconlon17** [comment]
Very good to hear. Will do.

**Comment by mconlon17** [comment]
Here is the DOI:  https://doi.org/10.5281/zenodo.2639713

**Comment by arfon** [comment]
@mconlon17 - there are a couple of issues with your paper. One of the grant numbers looks to be a placeholder (`xxxxxxx`) - could you please address that.

Also, none of the references are included in the body text which means they won't be compiled into the paper pdf. You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)

**Comment by danielskatz** [comment]
👋 @mconlon17 - Please note we are waiting for your changes to the paper, as requested by @arfon about 5 weeks ago.

**Comment by arfon** [comment]
I should have updated here to say I emailed the author last night about this and he replied immediately. I would expect an update shortly.

**Comment by labarba** [comment]
👋  @mconlon17 — Can you give us an update? If you're not close to done, please let me know of a time period to set a reminder for you.

**Comment by arfon** [comment]
I've just sent @mconlon17 another reminder over email.

**Comment by kyleniemeyer** [comment]
Hi @mconlon17, just checking in about your updates to the paper.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01182/joss.01182/10.21105.joss.01182.pdf)

**Comment by hauschke** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1182 with the following error: 

 Error reading bibliography ./paper.bib (line 33, column 9):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1182 with the following error: 

 Error reading bibliography ./paper.bib (line 33, column 9):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@mconlon17 - this PR should allow your paper to compile: https://github.com/vivo-project/VIVO/pull/134

**Comment by danielskatz** [comment]
👋 @hauschke - please note the comment above...

**Comment by hauschke** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01182/joss.01182/10.21105.joss.01182.pdf)

**Comment by mconlon17** [comment]
I have reviewed the proof.  All good.  Thanks to @hauschke for addressing comments.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01182/joss.01182/10.21105.joss.01182.pdf)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.2639714 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2639714" target="_blank">10.5281/zenodo.2639714</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1182 with the following error: 

 sh: 57: Syntax error: newline unexpected
Looks like we failed to compile the Crossref XML

**Comment by arfon** [comment]
@sonal-raj - many thanks for your review here and to @jasonclark for editing this submission ✨ 

@mconlon17 - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01182/status.svg)](https://doi.org/10.21105/joss.01182)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01182">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01182/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01182/status.svg
   :target: https://doi.org/10.21105/joss.01182
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01182/status.svg)](https://doi.org/10.21105/joss.01182)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
