### ISSUE TITLE
[PRE REVIEW]: Qiskit VSCode: a tool to enhance the quantum computing programming experience

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1183]
**Submitting author:** @cbjuan (<a href="http://orcid.org/0000-0003-2045-8329">Juan Cruz-Benito</a>)
**Repository:** <a href="https://github.com/Qiskit/qiskit-vscode/" target ="_blank">https://github.com/Qiskit/qiskit-vscode/</a>
**Version:** v0.4.1
**Editor:** @danielskatz
**Reviewers:** @malmaud, @naberek

**Author instructions**

Thanks for submitting your paper to JOSS @cbjuan. The JOSS editor @danielskatz, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@cbjuan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @danielskatz it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@danielskatz) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1183 with the following error: 

 ORCID looks to be the wrong length
/app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:91:in `block in check_orcids': Problem with ORCID (000-0003-2045-8329) for Juan Cruz-Benito (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @danielskatz - the submitting author suggested you as the handling editor.

**Comment by danielskatz** [comment]
👋 @cbjuan - if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

Also, your ORCID in paper.md is missing a leading zero.  Please fix this, then in a new comment here, enter ```@whedon generate pdf```

**Comment by cbjuan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01183/joss.01183/10.21105.joss.01183.pdf)

**Comment by cbjuan** [comment]
👋 @danielskatz! Thanks for your comments. I fixed the ORCID, and now @whedon can compile the PDF.


About the article proof, maybe we need to fix some titles in the references to meet some formal considerations. For example, the reference:
```
Research, I. (2018b). The ibm quantum experience. https://www.research.ibm.com/
ibm-q/.
```
should be (note the fixes in the author and the capitalization in the title):
```
IBM Research (2018b). The IBM Quantum Experience. https://www.research.ibm.com/
ibm-q/.
```
If possible, I would like to know how to fix these minor issues considering how PDF compiler handles that.



As prospective reviewers (I got them from the list) I would like to point out: @krischer, @mamrehn, and @malmaud. They have been selected mainly regarding their declared knowledge on Typescript and Python.

**Comment by danielskatz** [comment]
typically in bibtex files, you add {}s around anything you want to stay in the same case, for example:

  title={The {IBM Q} experience and {QISKit} open-source quantum computing software}

**Comment by danielskatz** [comment]
👋 @krischer, @mamrehn, and @malmaud - would a couple of you be willing to review this JOSS submission?

**Comment by cbjuan** [comment]
Ok, @danielskatz. I was not sure about it. We will fix it.

**Comment by malmaud** [comment]
Yes, I'm happy to review this. Full disclosure though,  I have worked at IBM research although not in this field and I do not know any of the authors.

**Comment by cbjuan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01183/joss.01183/10.21105.joss.01183.pdf)

**Comment by danielskatz** [comment]
@malmaud - Given what you've said, I don't see your previous work at IBM as an issue, though it's good to note.  I'll assign you as a reviewer, but we won't start the review until we get a second reviewer.  @cbjuan - if you have other suggestions outside the JOSS volunteer reviewer community, we're always willing to bring in more people.

**Comment by danielskatz** [comment]
@whedon assign @malmaud as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @malmaud

**Comment by danielskatz** [comment]
@cbjuan - Can you make any other suggestions about possible reviewers, from inside or outside the JOSS volunteer reviewer community?  We need one more to get going...

**Comment by cbjuan** [comment]
Sure, sorry for the delay. From outside JOSS reviewers, I would like to recommend @victorvicpal. And from JOSS reviewers (if needed) I point out to @pragyansmita

**Comment by danielskatz** [comment]
Another reviewer volunteered in response to a tweet - thanks @naberek
So we will start the review now.

**Comment by danielskatz** [comment]
@whedon add @naberek as reviewer

**Comment by whedon** [comment]
OK, @naberek is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1188. Feel free to close this issue now!
