### ISSUE TITLE
[PRE REVIEW]: areal: An R package for areal weighted interpolation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1187]
**Submitting author:** @chris-prener (<a href="http://orcid.org/0000-0002-4310-9888">Christopher Prener</a>)
**Repository:** <a href="https://github.com/slu-openGIS/areal" target ="_blank">https://github.com/slu-openGIS/areal</a>
**Version:** v0.1.3
**Editor:** @lheagy
**Reviewers:** @sjsrey, @edzer

**Author instructions**

Thanks for submitting your paper to JOSS @chris-prener. The JOSS editor @lheagy, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@chris-prener if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@lheagy) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @lheagy - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
PDF failed to compile for issue #1187 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    122      0 --:--:-- --:--:-- --:--:--   122
Error producing PDF.
! Undefined control sequence.
\SQSPL@scan ->\futurelet \SQSPL@next 
                                     \SQSPL@scani 
l.335 ...l R package}}\label{the-areal-r-package}}

Looks like we failed to compile the PDF

**Comment by chris-prener** [comment]
> Looks like we failed to compile the PDF

I'm wondering if this failed because of [the use of backticks in the heading](https://github.com/slu-openGIS/areal/blob/master/paper/paper.md#the-areal-r-package)? If so, I can remove and re-push...

**Comment by arfon** [comment]
This failure is due to a bug we recently introduced into our LaTeX template. I'll fix this shortly and let you know when it's updated.

**Comment by chris-prener** [comment]
OK, thanks for letting me know @arfon!

**Comment by lheagy** [comment]
👋 Hi @chris-prener, thanks for your submission! Do you have any recommendations for reviewers?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1187 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    181      0 --:--:-- --:--:-- --:--:--   182
Error producing PDF.
! Undefined control sequence.
\SQSPL@scan ->\futurelet \SQSPL@next 
                                     \SQSPL@scani 
l.345 ...l R package}}\label{the-areal-r-package}}

Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01187/joss.01187/10.21105.joss.01187.pdf)

**Comment by chris-prener** [comment]
>👋 Hi @chris-prener, thanks for your submission! Do you have any recommendations for reviewers?

Hi @lheagy - the following three people from google doc all list GIS and R as areas/languages of interest: nuest, jsta, sjsrey.

**Comment by lheagy** [comment]
👋 Hi @nuest, @sjsrey, would you be willing to review this submission for JOSS?

**Comment by sjsrey** [comment]
Hi Lindsey,

I would be happy to help - with the one caveat that I can't start on this
for another two weeks as I have several other reviews in my queue that I am
committed to.

s.
Sergio (Serge) Rey
Founding Director, Center for Geospatial Sciences
Professor, School of Public Policy
University of California, Riverside
sergio.rey@ucr.edu

**Comment by lheagy** [comment]
Thanks @sjsrey, that timeline is fine. Best of luck with the other reviews on your list.

**Comment by lheagy** [comment]
@whedon assign @sjsrey as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sjsrey

**Comment by lheagy** [comment]
Thanks for your reply @nuest. 

:wave: Hi @edzer, would you be willing to review this submission for JOSS?

**Comment by edzer** [comment]
Sure. Could you please point me to the guidelines for reviewers?

**Comment by lheagy** [comment]
Excellent, thank you @edzer! The guidelines for the review process are here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Shortly, I will close this issues and open another that contains a checklist that will help guide the review process. Please let me know if you have any questions or if I can provide further clarification.

**Comment by lheagy** [comment]
@whedon add @edzer as reviewer

**Comment by whedon** [comment]
OK, @edzer is now a reviewer

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1221. Feel free to close this issue now!
