### ISSUE TITLE
[REVIEW]: The Biddy BDD package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1189]
**Submitting author:** @meolic (<a href="http://orcid.org/0000-0003-3395-1227">Robert Meolic</a>)
**Repository:** <a href="https://github.com/meolic/biddy" target ="_blank">https://github.com/meolic/biddy</a>
**Version:** v1.8.2
**Editor:** @brainstorm
**Reviewer:** @HaoZeke
**Archive:** <a href="https://doi.org/10.5281/zenodo.2561641" target="_blank">10.5281/zenodo.2561641</a>

## Status

[![status](http://joss.theoj.org/papers/fc7f571e455ef955d1e5dd271343723f/status.svg)](http://joss.theoj.org/papers/fc7f571e455ef955d1e5dd271343723f)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/fc7f571e455ef955d1e5dd271343723f"><img src="http://joss.theoj.org/papers/fc7f571e455ef955d1e5dd271343723f/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/fc7f571e455ef955d1e5dd271343723f/status.svg)](http://joss.theoj.org/papers/fc7f571e455ef955d1e5dd271343723f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/meolic/biddy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@HaoZeke, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @brainstorm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/meolic/biddy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.8.2)?
- [x] **Authorship:** Has the submitting author (@meolic) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by meolic** [comment]
I have improved the first example in the documentation to make the usage of the package more clear. Sorry for these last-minute changes.

**Comment by HaoZeke** [comment]
@brainstorm, you're welcome.. I hope to have this finished in a few days.
@meolic, no problem, there may be some more changes, I will open pull requests and link to them as and when required, or discuss them with you here.


Right off the bat, could you please modify the `paper.md` so as to adhere to the following:

- [ ] Remove the historical review of package changes
- [ ] Remove or reword segments like `exciting features` and `wicked if not used carefully`

Beyond that, I would prefer a clearer statment (headings, boldface text etc) detailing the *need* for the software and *the features*.

As a style guide, perhaps [this JOSS paper](https://www.theoj.org/joss-papers/joss.01015/10.21105.joss.01015.pdf) would be useful.

Additionally, for changes to `paper.md` I would not like to open pull requests, so it might be better if I could highlight aspects which need editing, say for example if it is on [hackmd.io](https://hackmd.io/)

**Comment by meolic** [comment]
@HaoZeke I have made the requested changes. Please check https://hackmd.io/Ii3fJIJmS3iplOQHSCTjHA  (i do not know how to use hackmd.io correctly).

**Comment by meolic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01189/joss.01189/10.21105.joss.01189.pdf)

**Comment by meolic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01189/joss.01189/10.21105.joss.01189.pdf)

**Comment by meolic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01189/joss.01189/10.21105.joss.01189.pdf)

**Comment by meolic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01189/joss.01189/10.21105.joss.01189.pdf)

**Comment by meolic** [comment]
@HaoZeke I have updated paper.md. Many thanks for your suggestions, especially for the hint about writing math formulas in the markdown format. I am ready for your comments about the source code and the supplemented documentation (for the instalation it should be enough to read README.md, the complete API is documented in User manual available from biddy.meolic.com).

**Comment by brainstorm** [comment]
@HaoZeke Do the updates address some of the issues?

**Comment by meolic** [comment]
I have tried to address all of them.

**Comment by HaoZeke** [comment]
@brainstorm, I have completed my review. It is compliant with the instructions, and the code is very well documented (along with its usage). There are perhaps more edge cases (on exotic machines) however, even those are easily handled.

I believe the repository and BIDDY adheres to the JOSS guidelines and also that the claims in `paper.md` are well substantiated.

@meolic thank you for the prompt resolution of all my queries, and for open-sourcing this really well documented and useful software!

I am very sorry for the long delay.

**Comment by brainstorm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1109/TC.1986.1676819 is OK
- http://doi.org/10.1007/978-3-319-10575-8_8 is OK
- http://doi.org/10.1587/transinf.E96.D.1419 is OK
- http://doi.org/10.4304/jsw.7.6.1358-1366 is OK
- http://doi.org/10.23919/FMCAD.2017.8102248 is OK
- http://doi.org/10.14743/apem2018.4.297 is OK

MISSING DOIs

- https://doi.org/10.1145/1388240.1388245 may be missing for title: The Art of Computer Programming, Volume 4, Fascicle 1: Bitwise Tricks and Techniques; Binary Decision Diagrams. Addison-Wesley Professional, 2009
- https://doi.org/10.4304/jsw.7.6.1358-1366 may be missing for title: Implementation aspects of a BDD package supporting general decision diagrams. University of Maribor, Tech. rep., 2016

INVALID DOIs

- None
```

**Comment by brainstorm** [comment]
@meolic Can you please fix the DOI issues?

**Comment by meolic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01189/joss.01189/10.21105.joss.01189.pdf)

**Comment by meolic** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1109/TC.1986.1676819 is OK
- http://doi.org/10.1007/978-3-319-10575-8_8 is OK
- http://doi.org/10.1587/transinf.E96.D.1419 is OK
- http://doi.org/10.4304/jsw.7.6.1358-1366 is OK
- http://doi.org/10.23919/FMCAD.2017.8102248 is OK
- http://doi.org/10.14743/apem2018.4.297 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by meolic** [comment]
@brainstorm Thank you for this remark. Now, references should be OK.

**Comment by brainstorm** [comment]
Fantastic, I think we are all set to accept over here, @kyleniemeyer :)

**Comment by brainstorm** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by brainstorm** [comment]
@meolic Can you please generate a Zenodo DOI I can set as archive?

**Comment by meolic** [comment]
Done.

**Comment by meolic** [comment]
Done.

[![DOI](https://zenodo.org/badge/44801799.svg)](https://zenodo.org/badge/latestdoi/44801799)

**Comment by brainstorm** [comment]
@whedon set http://doi.org/10.5281/zenodo.2561641 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2561641" target="_blank">10.5281/zenodo.2561641</a> is the archive.

**Comment by brainstorm** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1109/TC.1986.1676819 is OK
- http://doi.org/10.1007/978-3-319-10575-8_8 is OK
- http://doi.org/10.1587/transinf.E96.D.1419 is OK
- http://doi.org/10.4304/jsw.7.6.1358-1366 is OK
- http://doi.org/10.23919/FMCAD.2017.8102248 is OK
- http://doi.org/10.14743/apem2018.4.297 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by brainstorm** [comment]
@arfon I think we are ready to deposit here ;)

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/482

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/482, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/483
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01189](https://doi.org/10.21105/joss.01189)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@HaoZeke - many thanks for your review and to @brainstorm for editing this submission ✨ 

@meolic - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01189/status.svg)](https://doi.org/10.21105/joss.01189)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01189">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01189/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01189/status.svg
   :target: https://doi.org/10.21105/joss.01189
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01189/status.svg)](https://doi.org/10.21105/joss.01189)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
