### ISSUE TITLE
[PRE REVIEW]: causalweight: An R Package for Causal Inference and Mediation Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1194]
**Submitting author:** @hbodory (<a href="http://orcid.org/0000-0002-3645-1204">Hugo Bodory</a>)
**Repository:** <a href="https://github.com/hbodory/causalweight" target ="_blank">https://github.com/hbodory/causalweight</a>
**Version:** 0.1.2
**Editor:** @karthik
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @hbodory. The JOSS editor @karthik, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@hbodory if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@karthik) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by arfon** [comment]
:wave: @karthik - the submitting author suggested you as the handling editor.

**Comment by labarba** [comment]
:wave @karthik It looks like we're waiting for you to assign reviewers here. Can you have a look?

**Comment by karthik** [comment]
Thanks Lorena (I was traveling). 

@hbodory Thanks for this submission. Unfortunately this is not a R package. You have a collection of R function in a R folder but no R package structure, documentation (the manual.pdf does not count as acceptable package documentation), tests, or any metadata. I would recommend reading about creating R packages here (free resource: http://r-pkgs.had.co.nz/) and creating a new submission when you have a complete package.

@joss-eics Can you close this submission?

**Comment by hbodory** [comment]
@karthik Thank you for your reply. Just to make sure that I understand your concerns about the R package correctly. The R package causalweight is available on CRAN since 2018, currently version 0.1.2 is running on CRAN, see [causalweight](https://CRAN.R-project.org/package=causalweight).  Do you want me to submit a new package to CRAN?

**Comment by karthik** [comment]
@hbodory For JOSS you need to point us to the source code of the package that includes everything. I see causalweight on CRAN and the source there includes most things I have asked for. But the repo you link to in this submission just has a `R/` folder with the functions and nothing more. Where is your package source?

**Comment by karthik** [comment]
In looking at your repo, I see that you gitignored all the package files: https://github.com/hbodory/causalweight/commit/32eb7f5844160bec7d92b3ca7f8384cc0edc03e4#diff-a084b794bc0759e7a6b77810e01874f2

which is the problem.

**Comment by hbodory** [comment]
I have uploaded the package source in the folder causalweight_0.1.2.tar.gz on [GitHub_causalweight](https://github.com/hbodory/causalweight).

**Comment by karthik** [comment]
@hbodory Your GitHub repo has to be the full package repository that includes all the files. The built package source is not helpful. Here is an example of an R package on GitHub: https://github.com/ropensci/drake

**Comment by hbodory** [comment]
@karthik  The files are on GitHub available now.

**Comment by karthik** [comment]
Thanks @hbodory We still need to see tests before going further. See here for [help](http://r-pkgs.had.co.nz/tests.html) setting up testing.

**Comment by karthik** [comment]
@hbodory Can you please update the thread when you have added some tests?

**Comment by hbodory** [comment]
@karthik Thank you for your reminder. I am out of office at the moment but I will upload some tests as soon as possible.

**Comment by hbodory** [comment]
Dear Lorena,

I apologize for the late reply, I am not in the office at the moment.

I will run the required tests as soon as possible in June so that the review process can go on.

Thanks in advance for your support.

Best regards,

Hugo

**Comment by danielskatz** [comment]
@whedon remind @hbodory in 2 weeks

**Comment by whedon** [comment]
Sorry, I can't set reminders on PRE-REVIEW issues.

**Comment by danielskatz** [comment]
👋 @hbodory - Any update on this?

**Comment by arfon** [comment]
At this point I think we should close this pre-review issue. @hbodory - we'd welcome a resubmission at some point in the future when you've managed to address the feedback here.
