### ISSUE TITLE
[PRE REVIEW]: pyclustering

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1195]
**Submitting author:** @annoviko (<a href="http://orcid.org/0000-0002-9666-9141">Andrei Novikov</a>)
**Repository:** <a href="https://github.com/annoviko/pyclustering" target ="_blank">https://github.com/annoviko/pyclustering</a>
**Version:** 0.8.2
**Editor:** @poulson
**Reviewers:** @adavidzh

**Author instructions**

Thanks for submitting your paper to JOSS @annoviko. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@annoviko if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1195 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    184      0 --:--:-- --:--:-- --:--:--   185
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.01195.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01195/joss.01195/10.21105.joss.01195.pdf)

**Comment by annoviko** [comment]
Hello, @arfon,
I have checked the list and found out that **adavidzh**, **dvysardana**, **pragyansmita** are suitable persons for review in line with the description (C/C++, Python, Cluster Analysis, Data Mining).

**Comment by arfon** [comment]
> I have checked the list and found out that adavidzh, dvysardana, pragyansmita are suitable persons for review in line with the description (C/C++, Python, Cluster Analysis, Data Mining).

Thanks @annoviko. Before we decide upon reviewers, we need to have an editor assigned - this shouldn't take more than a week.

> The article devoted to 0.8.2 version that is on stable release branch '0.8.2.rel' (link: https://github.com/annoviko/pyclustering/tree/0.8.2.rel). DOI is already assigned for this release (link: https://zenodo.org/record/1491324#.XEgztVUzaUk) and it can be used by JOSS if it does not contradict the rules. Master branch already contains changes related to the new version of the library.

Is the paper (https://github.com/openjournals/joss-reviews/issues/1195#issuecomment-456493099) above not correct then? We can ask @whedon to compile a paper from a different branch in your repository.

Also, regarding the DOI & archive you already have - this might be OK, if your code is modified because of the review here we would ask you to make a new archive before publication.

**Comment by annoviko** [comment]
@arfon, thanks for the clarification. The paper is totally correct, no need to rebuild it, I have just provided some extra information about the repository.

**Comment by danielskatz** [comment]
👋 @arfon - is this ready to go to an editor in your opinion?  If so, can you suggest one?  If not, what else do you think is needed?

**Comment by danielskatz** [comment]
👋 @poulson - Are you able to edit this submission?

**Comment by danielskatz** [comment]
👋 @poulson - ping... Are you able to edit this submission?

**Comment by poulson** [comment]
@arfon @danielskatz Yes, I would be happy to edit this submission and apologize, none of my pings had been going through. I promise I was not actively ignoring this!

**Comment by poulson** [comment]
@lmcinnes Would you be able to review this submission?

**Comment by poulson** [comment]
@adavidzh Would you be able to review this submission?

**Comment by adavidzh** [comment]
> @adavidzh Would you be able to review this submission?

I just looked through the different materials and can do.

**Comment by danielskatz** [comment]
@whedon assign @poulson as editor

by the way @poulson - you perform this command too...

**Comment by whedon** [comment]
OK, the editor is @poulson

**Comment by poulson** [comment]
@whedon assign @adavidzh as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @adavidzh

**Comment by poulson** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by poulson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1230. Feel free to close this issue now!
