### ISSUE TITLE
[PRE REVIEW]: eddy: Extracting Protoplanetary Disk Dynamics with Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1197]
**Submitting author:** @richteague (<a href="http://orcid.org/0000-0003-1534-5186">Richard Teague</a>)
**Repository:** <a href="https://github.com/richteague/eddy" target ="_blank">https://github.com/richteague/eddy</a>
**Version:** v1.1
**Editor:** @arfon
**Reviewers:** @kevin-flaherty

**Author instructions**

Thanks for submitting your paper to JOSS @richteague. The JOSS editor @arfon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@richteague if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@arfon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1197 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    283      0 --:--:-- --:--:-- --:--:--   288
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.01197.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01197/joss.01197/10.21105.joss.01197.pdf)

**Comment by arfon** [comment]
:wave: @richteague - many thanks for your submission to JOSS. Next up we need to find a reviewer or two for this submission. Could you take a look at [this list of potential reviewers](https://bit.ly/joss-reviewers) and suggest a few here that might be suitable? Alternatively, you can suggest names of people not on this list that I can contact.

**Comment by arfon** [comment]
:wave: @adam-m-jcbs - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by adam-m-jcbs** [comment]
:wave: @arfon, @richteague - I am willing and feel competent to review the submission.  However, I am currently quite subscribed through February.  I cannot guarantee I'll be able to make time in my schedule to complete the review until my plate is clearer in March.  I've agreed to do a review I didn't have room for in the past and am trying to not repeat that mistake.  Were I to be selected as the reviewer, I wouldn't be able to promise completion of the review until March 15.  I will attempt to complete it sooner, but am not comfortable promising to have it done sooner than that.

If this constraint is something y'all are both comfortable with and would still like me to do the review, please let me know.  Looks like an interesting project I'd like to learn more about!

**Comment by richteague** [comment]
@arfon - What's the best practice when it comes to further development of the code? I wanted to submit a JOSS paper for it already as there's been quite a bit of work based on the software so far (published and in prep.), but there's definitely some additional features which I'd be interested in implementing. Would I have to wait for the review (i.e. after 15th March) to begin on this, or is it possible to review this version?

**Comment by arfon** [comment]
> @arfon - What's the best practice when it comes to further development of the code? I wanted to submit a JOSS paper for it already as there's been quite a bit of work based on the software so far (published and in prep.), but there's definitely some additional features which I'd be interested in implementing. Would I have to wait for the review (i.e. after 15th March) to begin on this, or is it possible to review this version?

I think it's helpful if the reviewer doesn't have a moving target here. That said, we don't have a reviewer assigned yet you're welcome to make changes _right now_ and let us know about them once a reviewer is ready to go.

**Comment by arfon** [comment]
@whedon add @kevin-flaherty as reviewer

**Comment by whedon** [comment]
OK, @kevin-flaherty is now a reviewer

**Comment by arfon** [comment]
:wave: @richteague - @kevin-flaherty has kindly volunteered to review this submission for us. Are you still planning on making some changes to this package soon? If not, we are ready to move forward to the actual review.

**Comment by richteague** [comment]
@arfon - Sounds great to me! No more changes need to be made. Thanks!

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1220. Feel free to close this issue now!

**Comment by arfon** [comment]
@richteague @kevin-flaherty - see you over in #1220 for the actual review.
