### ISSUE TITLE
[PRE REVIEW]: Compare Expression Profiles for Pre-defined Gene Groups with C-REx

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1198]
**Submitting author:** @edifice1989 (<a href="http://orcid.org/0000-0002-8164-2480">Mingze He</a>)
**Repository:** <a href="https://cloud.docker.com/u/edifice1989/repository/docker/edifice1989/c-rex" target ="_blank">https://cloud.docker.com/u/edifice1989/repository/docker/edifice1989/c-rex</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @edifice1989. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@edifice1989 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1198 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1198 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:47:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @edifice1989 - could you please link to the software repository for this submission rather than a Docker container image?

**Comment by edifice1989** [comment]
Hi Arfon,

    Here is the link to the software repository:
https://github.com/edifice1989/rocker-c-rex

    Please kindly instruct me how to change it! Thank you very much!

Best,
Ming

**Comment by danielskatz** [comment]
It appears this was resubmitted as source in https://github.com/openjournals/joss-reviews/issues/1215, so I am going to close this one.
@edifice1989 - if this is incorrect, please feel free to reopen this issue; otherwise, future discussion will take place in https://github.com/openjournals/joss-reviews/issues/1215
