### ISSUE TITLE
[PRE REVIEW]: straditize: Digitizing stratigraphic diagrams

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1199]
**Submitting author:** @Chilipp (<a href="http://orcid.org/0000-0001-6171-7716">Philipp S. Sommer</a>)
**Repository:** <a href="https://github.com/Chilipp/straditize" target ="_blank">https://github.com/Chilipp/straditize</a>
**Version:** v0.1.0
**Editor:** @yochannah
**Reviewers:** @ixjlyons, @sgrieve

**Author instructions**

Thanks for submitting your paper to JOSS @Chilipp. The JOSS editor @yochannah, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Chilipp if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @yochannah it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@yochannah) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @yochannah - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01199/joss.01199/10.21105.joss.01199.pdf)

**Comment by yochannah** [comment]
Okay, looks good! 

@Chilipp Thanks for submitting this! Do you have any suggestions for possible reviewers by any chance? (No worries if not!)

One possible reviewer occurs to me - @sgrieve might this interest you?

**Comment by Chilipp** [comment]
I'd say ideally someone with a background in GUI development and/or digitisation. Maybe @ixjlyons or @sauln?

**Comment by sauln** [comment]
I'd love to help, but don't have any experience in digitization.

**Comment by ixjlyons** [comment]
I'm also not very knowledgable in this area, but my understanding of the review process leads me to believe I'm qualified to do the review and I'd be happy to do it. @yochannah what level of familiarity with the field do you expect a reviewer to have?

**Comment by sgrieve** [comment]
@yochannah I'd be delighted to review. This looks really cool!

**Comment by yochannah** [comment]
Thanks @sauln and no worries! 👍 

@ixjlyons looking at your profile, you look like you're quite comfortable with python and open source - we'd be happy to have you review! 

@sgrieve Thanks! 

@ixjlyons and @sgrieve - I'll set you two as reviewers and kick off the review issue.

**Comment by yochannah** [comment]
@whedon assign @ixjlyons as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ixjlyons

**Comment by yochannah** [comment]
@whedon add @sgrieve as reviewer

**Comment by whedon** [comment]
OK, @sgrieve is now a reviewer

**Comment by yochannah** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1216. Feel free to close this issue now!

**Comment by yochannah** [comment]
Okay, @ixjlyons, @sgrieve and @Chilipp  - let's pop over to #1216 to conduct the review process. All the details you need should be there but let me know if there are any Qs!
