### ISSUE TITLE
[PRE REVIEW]: batchtools: Tools for R to work on batch systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#120]
**Submitting author:** @mllg (<a href="http://orcid.org/0000-0001-9754-0393">Michel Lang</a>)
**Repository:** <a href="https://github.com/mllg/batchtools" target ="_blank">https://github.com/mllg/batchtools</a>
**Version:** v0.9.0
**Editor:** @arfon
**Reviewer:** @masalmon

**What this issue is for**

Thanks for submitting your paper to JOSS @mllg. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by arfon** [comment]
👋  @pragyansmita - would you be willing to review this submission for us?

**Comment by arfon** [comment]
@masalmon - would you be willing to review this submissions for JOSS?

**Comment by masalmon** [comment]
@arfon Yes! I'll do that next week.

**Comment by arfon** [comment]
@whedon assign @masalmon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @masalmon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/135. Feel free to close this issue now!
