### ISSUE TITLE
[PRE REVIEW]: Model dispersion with PRISM; an alternative to MCMC for rapid analysis of models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1200]
**Submitting author:** @1313e (<a href="http://orcid.org/0000-0002-1559-9832">Ellert van der Velden</a>)
**Repository:** <a href="https://github.com/1313e/PRISM" target ="_blank">https://github.com/1313e/PRISM</a>
**Version:** v1.0.0
**Editor:** @arokem
**Reviewers:** fonnesbeck

**Author instructions**

Thanks for submitting your paper to JOSS @1313e. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@1313e if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by danielskatz** [comment]
👋 @Kevin-Mattheus-Moerman - would you be willing to edit this submission?

**Comment by Kevin-Mattheus-Moerman** [comment]
I'm a bit swamped until the end of February. If you cannot find an alternative editor I can take this but perhaps try to find somebody else first.

**Comment by 1313e** [comment]
I have been looking through the list of potential reviewers, but given the large number that are in there, I could not really pick one or a few that I would like to suggest.
I know that that is not much of a help, but that list is really long (which is a good thing in my opinion).

**Comment by danielskatz** [comment]
👋 @arokem - Is this something you can take on as editor?

**Comment by danielskatz** [comment]
👋 @arokem - ping... Is this something you can take on as editor?

**Comment by arokem** [comment]
Sorry for the delay. I can do this.

**Comment by arokem** [comment]
@whedon assign arokem as editor

**Comment by whedon** [comment]
OK, the editor is arokem

**Comment by arokem** [comment]
@fonnesbeck : would you be willing to review this article for [JOSS](http://joss.theoj.org/)?

**Comment by fonnesbeck** [comment]
@arokem yes, I can do it.

**Comment by arokem** [comment]
Thanks!

**Comment by arokem** [comment]
@whedon assign fonnesbeck as reviewer

**Comment by whedon** [comment]
OK, the reviewer is fonnesbeck

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1229. Feel free to close this issue now!

**Comment by arokem** [comment]
Thanks a lot for taking this on! Please head over to #1229 for the reviewer checklist. I'm closing this one.
