### ISSUE TITLE
[REVIEW]: TraitDB: Web application database of phenotypic trait data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1201]
**Submitting author:** @dleehr (<a href="http://orcid.org/0000-0003-3221-9579">Dan Leehr</a>)
**Repository:** <a href="https://github.com/NESCent/TraitDB" target ="_blank">https://github.com/NESCent/TraitDB</a>
**Version:** v1.0.1
**Editor:** @pjotrp
**Reviewer:** @amoeba
**Archive:** <a href="https://doi.org/10.5281/zenodo.2609163" target="_blank">10.5281/zenodo.2609163</a>

## Status

[![status](http://joss.theoj.org/papers/94404e364d0cc8e5b7a025743133212c/status.svg)](http://joss.theoj.org/papers/94404e364d0cc8e5b7a025743133212c)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/94404e364d0cc8e5b7a025743133212c"><img src="http://joss.theoj.org/papers/94404e364d0cc8e5b7a025743133212c/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/94404e364d0cc8e5b7a025743133212c/status.svg)](http://joss.theoj.org/papers/94404e364d0cc8e5b7a025743133212c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/NESCent/TraitDB" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@amoeba, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @pjotrp know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/NESCent/TraitDB">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** v1.0.1
- [x] **Authorship:** Has the submitting author (@dleehr) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @amoeba it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01201/joss.01201/10.21105.joss.01201.pdf)

**Comment by dleehr** [comment]
Thanks @pjotrp ! I need to get the tests and installation in order. I'll reply again when that's done.

**Comment by dleehr** [comment]
OK, ready for the next steps and the PDF looks good to me.

**Comment by pjotrp** [comment]
Thanks @dleehr. @amoeba you can start review.

**Comment by amoeba** [comment]
Hi @pjotrp I started my review but encountered some issues I didn't expect (documented on https://github.com/NESCent/TraitDB/issues/222) so I'll need some more time for my review.

**Comment by pjotrp** [comment]
No worries.

**Comment by pjotrp** [comment]
@dleehr is this really a blocker?

**Comment by amoeba** [comment]
Hi @pjotrp, @dleehr has addresses all of my outstanding issues with the review over on https://github.com/NESCent/TraitDB/issues/222 and I've updated the checklist above to reflect that. Everything is in order for your final stamp except

> Version: Does the release version given match the GitHub release (v0.9.1)?

which should be updated to 1.0.0 (See: https://github.com/NESCent/TraitDB/releases/tag/v1.0.0).

My review is: Accept (conditional upon the above)

**Comment by pjotrp** [comment]
Thank you @amoeba! @dleehr to finalize your submission and accept your paper in JOSS, we need two things. First, can you confirm that all references in your bibliography have a DOI in the bibliography (if one exists).

Second, we need you to deposit a copy of your software repository (including any revisions made during the JOSS review process) with a data-archiving service.

To do so:

1. Create [a GitHub release](https://help.github.com/articles/creating-releases/) of the current version of your software repository
2. Deposit that release with [Zenodo](https://zenodo.org/), [figshare](https://figshare.com/), or a similar DOI issuer.
3. Post a comment here with the DOI for the release.

**Comment by dleehr** [comment]
Thanks @pjotrp 

> First, can you confirm that all references in your bibliography have a DOI in the bibliography 

Yes

> Second, we need you to deposit a copy of your software repository (including any revisions made during the JOSS review process) with a data-archiving service.

https://doi.org/10.5281/zenodo.2583988

**Comment by pjotrp** [comment]
@whedon set 10.5281/zenodo.2583988 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2583988" target="_blank">10.5281/zenodo.2583988</a> is the archive.

**Comment by pjotrp** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1038/sdata.2014.15 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by pjotrp** [comment]
ping eic @openjournals/joss-eics

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/546

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/546, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
Hi @dleehr — Please edit the metadata of the Zenodo deposit (note: no need for a new DOI or version) so the title and author list match the paper.

The paper proof has a References section, but no references listed. Can you check that?

Editorial suggestions/fixes:
- you could merge your first four mini-paragraphs into one paragraph.
- "While these software are technically proficient can facilitate robust operations…" >> something is wrong with this phrase
- "TraitDB aids the ingest of datasets">> grammar? if "ingest" is a verb, why the article?

To be honest, after reading the paper, it's hard to visualize wha the software does. I remind you that the JOSS paper should be understandable to non-specialists. Can you try to improve the readability, overall, and state more clearly what the software _does_?

**Comment by pjotrp** [comment]
@labarba some valid comment. Except for the last one. I checked the paper for having a topical introduction for laymen. It says that it stores data from different formats using templates.  What else do you want to add?

**Comment by labarba** [comment]
Since the author is requested to make some edits, seems like a final effort to make it read easier is not too much to ask.

**Comment by pjotrp** [comment]
@dleehr feel free to share your thoughts.

**Comment by dleehr** [comment]
Appreciate the feedback. I'll take another pass at the paper and make the requested specific changes. Thank you all for your time.

**Comment by pjotrp** [comment]
@dleehr are you OK?

**Comment by dleehr** [comment]
Yes. In the middle of an edit today. Will be updating tomorrow.

**Comment by dleehr** [comment]
Hey @pjotrp, I revised the intro paragraph to move some information up and state the case more clearly to a general audience.

I registered a new DOI at Zenodo: 10.5281/zenodo.2609163, since the auto-generated github submission did not allow any edits (e.g. to correct the author list)

**Comment by pjotrp** [comment]
@labarba happy?

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01201/joss.01201/10.21105.joss.01201.pdf)

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.2609163 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2609163" target="_blank">10.5281/zenodo.2609163</a> is the archive.

**Comment by labarba** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by labarba** [comment]
@dleehr — Please check your proof, and if you are happy with it, we can proceed to publish your paper. Cheers!

**Comment by dleehr** [comment]
Looks good to me, thanks!

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1038/sdata.2014.15 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/581

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/581, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
The XML deposit includes one citation, whereas the paper has no references.

@arfon : Why does `whedon` find a citation when there are none? Is it picking it up from a `.bib` file? In that case, should the `.bib` file be deleted? Is the citation included in the XML going to cause a false citation entry with Crossref?

**Comment by arfon** [comment]
> @arfon : Why does whedon find a citation when there are none? Is it picking it up from a .bib file? In that case, should the .bib file be deleted? Is the citation included in the XML going to cause a false citation entry with Crossref?

Yes please remove the entry from the bibtex file (but don't delete it).

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1038/sdata.2014.15 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/596

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/596, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/597
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01201](https://doi.org/10.21105/joss.01201)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@amoeba - many thanks for your review here and to @pjotrp for editing this submission ✨

@dleehr - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01201/status.svg)](https://doi.org/10.21105/joss.01201)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01201">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01201/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01201/status.svg
   :target: https://doi.org/10.21105/joss.01201
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01201/status.svg)](https://doi.org/10.21105/joss.01201)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
