### ISSUE TITLE
[PRE REVIEW]: surfinpy: A Surface Phase Diagram Generator

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1202]
**Submitting author:** @symmy596 (<a href="http://orcid.org/0000-0001-6059-497X">Adam Symington</a>)
**Repository:** <a href="https://github.com/symmy596/SurfinPy" target ="_blank">https://github.com/symmy596/SurfinPy</a>
**Version:** 0.8
**Editor:** @labarba
**Reviewers:** @bocklund, @mkhorton

**Author instructions**

Thanks for submitting your paper to JOSS @symmy596. The JOSS editor @labarba, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@symmy596 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@labarba) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @labarba - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
PDF failed to compile for issue #1202 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    208      0 --:--:-- --:--:-- --:--:--   208
100    15    0    15    0     0    206      0 --:--:-- --:--:-- --:--:--   205
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.01202.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01202/joss.01202/10.21105.joss.01202.pdf)

**Comment by labarba** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1021/acs.chemmater.8b00649 may be missing for title: Particle Morphology and Lithium Segregation to Surfaces of the Li7La3Zr2O12 Solid Electrolyte
- https://doi.org/10.1021/jp300576b may be missing for title: Water Adsorption and Its Effect on the Stability of Low Index Stoichiometric and Reduced Surfaces of Ceria
- https://doi.org/10.1021/acs.jpcc.6b10986 may be missing for title: Water Adsorption on AnO2 111, 110, and 100 Surfaces (An = U and Pu): A Density Functional Theory + U Study
- https://doi.org/10.1103/physrevlett.90.046103 may be missing for title: First-Principles Atomistic Thermodynamics for Oxidation Catalysis: Surface Phase Diagrams and Catalytically Interesting Regions
- https://doi.org/10.1103/physrevb.69.115409 may be missing for title: Ab initio morphology and surface thermodynamics of \ensuremathα\ensuremath-\mathrmAl_2\mathrmO_3

INVALID DOIs

- None
```

**Comment by labarba** [comment]
👋  @@symmy596 — Doing the pre-checks on your paper, we've found that your references list is missing a bunch of DOIs. Check on the helpful suggestions of our bot ☝️ 
Can you update your BibTeX entries to include the DOIs?
Also, I request that you don't use double { } around the titles to override the capitalization style of the bibliography. Only use them in acronyms or other individual names that need to be capitalized. Thanks!

**Comment by labarba** [comment]
@bjmorgan — Maybe you would like to contribute a review for JOSS on this one?

**Comment by labarba** [comment]
@whedon assign @bocklund as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @bocklund

**Comment by bjmorgan** [comment]
@labarba I'd be happy to review, but want to flag a possible [conflict of interest](https://github.com/openjournals/joss/blob/master/COI.md). I'm in the same department as three of the authors on this paper, and have an active collaboration with two of the authors.

**Comment by labarba** [comment]
Ah, thanks, @bjmorgan — I guess I'm on the right track for selecting reviewers 😁 

At this point, I'd like to ask @symmy596 if the authors could suggest some names for a possible second reviewer?

**Comment by bocklund** [comment]
If I may suggest: @mkhorton is on the reviewer list and might be interested.

**Comment by bjmorgan** [comment]
@utf is not on the reviewer list, but has published in JOSS and has the right background.

**Comment by mkhorton** [comment]
I’d be happy to review, I also know @utf and can vouch he’d also be a good
reviewer / appropriate for this.

**Comment by labarba** [comment]
Thanks, @mkhorton! We'll add you to this one. 

👋  @utf — Would you like to contribute as a JOSS reviewer? Go over to our [online form](
http://joss.theoj.org/reviewer-signup.html) and sign up!

**Comment by labarba** [comment]
@whedon add @mkhorton as reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1210. Feel free to close this issue now!
