### ISSUE TITLE
[REVIEW]: BladeX: Python Blade Deformation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1203]
**Submitting author:** @mtezzele (<a href="http://orcid.org/0000-0001-9747-6328">Marco Tezzele</a>)
**Repository:** <a href="https://github.com/mathLab/BladeX" target ="_blank">https://github.com/mathLab/BladeX</a>
**Version:** v0.1
**Editor:** @labarba
**Reviewer:** @benoitpaillard, @Juanlu001
**Archive:** <a href="https://doi.org/10.5281/zenodo.2556690" target="_blank">10.5281/zenodo.2556690</a>

## Status

[![status](http://joss.theoj.org/papers/5b0ef70a351c1a51daf3a9354cd7b3fa/status.svg)](http://joss.theoj.org/papers/5b0ef70a351c1a51daf3a9354cd7b3fa)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/5b0ef70a351c1a51daf3a9354cd7b3fa"><img src="http://joss.theoj.org/papers/5b0ef70a351c1a51daf3a9354cd7b3fa/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/5b0ef70a351c1a51daf3a9354cd7b3fa/status.svg)](http://joss.theoj.org/papers/5b0ef70a351c1a51daf3a9354cd7b3fa)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mathLab/BladeX" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@benoitpaillard & @Juanlu001, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @labarba know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mathLab/BladeX">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1)?
- [x] **Authorship:** Has the submitting author (@mtezzele) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mathLab/BladeX">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1)?
- [x] **Authorship:** Has the submitting author (@mtezzele) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @benoitpaillard, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01203/joss.01203/10.21105.joss.01203.pdf)

**Comment by labarba** [comment]
@benoitpaillard, @Juanlu001 — this is where the action happens. You can read about the [JOSS Review Process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) in our docs. Each of you has a review checklist at the top of this issue 👆 and you should feel free to ask questions here, and open issues in the submission repository as needed.

**Comment by labarba** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@mtezzele — I notice that you cited the software repository in your paper. The paper format will have a link to the repository (and software archive, made after review is complete) on the front page, so it's not necessary to add it to the References list. You also cite a _submitted_ paper: would you be able to post a pre-print of the manuscript, for example in [engrXiv](https://engrxiv.org) or a similar service? (Then you can add the DOI or pre-print identifier in your References list.)

**Comment by Juanlu001** [comment]
I did a first pass on the repository and left two minor suggestions, https://github.com/mathLab/BladeX/issues/42 and https://github.com/mathLab/BladeX/issues/43 (none of them a blocker). I will finish my review during the coming days.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01203/joss.01203/10.21105.joss.01203.pdf)

**Comment by mtezzele** [comment]
@labarba I added the Preprint record to the bibitem but it does not appear in the pdf (https://github.com/mathLab/BladeX/pull/45). Can you please tell me how to do it?

**Comment by Juanlu001** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by Juanlu001** [comment]
I find the software very well written and its documentation excellent, it was a pleasing surprise to see an engineering tool with such up to date coding practices. Congratulations @mtezzele and @mahgadalla!

@labarba is there anything else I have to do apart from crossing off all the elements of the list?

**Comment by labarba** [comment]
@Juanlu001 — If you have checked off all the review items, and the authors have made any improvements to  your satisfaction, all I need is a statement from you here that you recommend publication.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01203/joss.01203/10.21105.joss.01203.pdf)

**Comment by labarba** [comment]
@mtezzele — I believe you should use the `note` field to provide the URL to the preprint. Also, the entry type should probably be `@unpublished` or `@misc`.

**Comment by Juanlu001** [comment]
I hereby recommend publication of this paper.

**Comment by mtezzele** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01203/joss.01203/10.21105.joss.01203.pdf)

**Comment by mtezzele** [comment]
@labarba unfortunately with note neither unpublished nor misc work.

**Comment by labarba** [comment]
Dang! Try with the `howpublished` field in `@misc`.

**Comment by mtezzele** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01203/joss.01203/10.21105.joss.01203.pdf)

**Comment by mtezzele** [comment]
@labarba Finally we did it! Thank you very much!

**Comment by benoitpaillard** [comment]
Hi all, sorry for the late completion.

The really only issue I'd mention is the dependency to pythonocc which is still a mess to compile, but don't get me wrong, I'm using it in my projects as well ! I just wish it could be compiled more easily.

Appart from that, finally a code that does 3D blades, but also robust naca and general airfoil generators !! Congrats guys, great tool.

**Comment by labarba** [comment]
@mtezzele — Some final editorial comments:

¶1.
obtain designs which allow >> that allow
prototipation environment >> prototyping environment
By a practical standpoint, the propeller blade >> From a practical standpoint, a propeller blade
the shape of a certain number of sectional profile shapes >> the shape of a certain number of sectional profiles
a morphing tool that expand >> expands
In particular we followed >> In particular, we followed [add comma]

¶2.
In the BladeX Python package we implemented >> package, we… [add comma]
simulation driven design >> simulation-driven design [add hyphen]

¶3.
naval propulsion”, >>naval propulsion,”  [comma inside quote]
can be found in (Tezzele, Demo, Mola, & Rozza, 2018) >> this is an in-text citation (meaning, the citation is part of the sentence), so you need to suppress the parenthesis; see [Citation Syntax](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)

¶4.
the resulted iges and stl  le formats >> the resulting
(same in caption of Figure 1)

**Comment by mahgadalla** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01203/joss.01203/10.21105.joss.01203.pdf)

**Comment by mahgadalla** [comment]
@labarba thanks a lot! the editorial comments are now fixed. Please let us know if the in-text citation looks ok now, also if the first citation should be regarded as in-text as well?

**Comment by labarba** [comment]
Yes, I missed that one. Whenever the citation is part of the sentence, treat as in-text.

**Comment by mahgadalla** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01203/joss.01203/10.21105.joss.01203.pdf)

**Comment by mahgadalla** [comment]
@labarba ok done!
Are there any further comments to consider?

**Comment by labarba** [comment]
At this point, we ask you that you make a full archive of the repository in Zenodo or a similar service, and post the archive DOI on this thread. Thanks!

**Comment by mahgadalla** [comment]
@labarba here's the Zenodo archive DOI:
[10.5281/zenodo.2556690](http://doi.org/10.5281/zenodo.2556690)

**Comment by labarba** [comment]
Could you edit the title on Zenodo to match the paper?

**Comment by mahgadalla** [comment]
Sure! Edited now. (Y)

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.2556690 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2556690" target="_blank">10.5281/zenodo.2556690</a> is the archive.

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/475
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01203](https://doi.org/10.21105/joss.01203)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by mtezzele** [comment]
@labarba @Juanlu001 @benoitpaillard thank you all for your time and effort in this review. 
It has been a pleasure.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01203/status.svg)](https://doi.org/10.21105/joss.01203)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01203">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01203/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01203/status.svg
   :target: https://doi.org/10.21105/joss.01203
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01203/status.svg)](https://doi.org/10.21105/joss.01203)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by labarba** [comment]
My sincere thanks to our reviewers, @benoitpaillard, @Juanlu001 — this adventure in new-wave publishing would not be possible without you.
