### ISSUE TITLE
[PRE REVIEW]: HCP: A Matlab package to create beautiful heatmaps with richly annotated covariates

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1206]
**Submitting author:** @ManuelaS (<a href="http://orcid.org/0000-0001-9941-4307"></a>)
**Repository:** <a href="https://bitbucket.org/manuela_s/hcp/" target ="_blank">https://bitbucket.org/manuela_s/hcp/</a>
**Version:** v0.1
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @trallard, @piermorel

**Author instructions**

Thanks for submitting your paper to JOSS @ManuelaS. The JOSS editor @Kevin-Mattheus-Moerman, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ManuelaS if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by ManuelaS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1206 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    139      0 --:--:-- --:--:-- --:--:--   140

**Comment by ManuelaS** [comment]
I would like to suggest as potential reviewers @piermorel, @trallard and @cMadan given their experience with Matlab and data visualization. Note that @piermorel is not included in the list of existing reviewers, but he is the author of Gramm, another Matlab visualization package published in JOSS.

**Comment by arfon** [comment]
The automated paper compilation is timing out because of the very large images in the paper. Here's a copy of the PDF: [10.21105.joss.01206.pdf](https://github.com/openjournals/joss-reviews/files/2800191/10.21105.joss.01206.pdf)

**Comment by trallard** [comment]
Hi @ManuelaS and @Kevin-Mattheus-Moerman  I would gladly accept to review the paper but I would only have capacity to do so after the 16th of February

Also, I agree that @piermorel would be a great reviewer (I conducted the review for gramm last year and it was  a great package 🎉)

**Comment by Kevin-Mattheus-Moerman** [comment]
I can edit this one. Thanks @trallard for your willingness to act as a reviewer. I'll add you and we'll eagerly await your review contribution.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @trallard as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @trallard

**Comment by piermorel** [comment]
Hi everyone. I would also accept to review the paper if you still need additional reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @piermorel as reviewer

**Comment by whedon** [comment]
OK, @piermorel is now a reviewer

**Comment by ManuelaS** [comment]
Thanks all!

**Comment by piermorel** [comment]
Hello, shouldn't we get a review thread for HCP ? I haven't found one yet.

**Comment by danielskatz** [comment]
@Kevin-Mattheus-Moerman are you ready to start the review?

**Comment by Kevin-Mattheus-Moerman** [comment]
Apologies for the delay I will now initiate the review process.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1291. Feel free to close this issue now!
