### ISSUE TITLE
[REVIEW]: cartoee: Publication quality maps using Earth Engine

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1207]
**Submitting author:** @kmarkert (<a href="http://orcid.org/0000-0002-7557-0425">Kel Markert</a>)
**Repository:** <a href="https://github.com/kmarkert/cartoee" target ="_blank">https://github.com/kmarkert/cartoee</a>
**Version:** 0.0.5
**Editor:** @lheagy
**Reviewer:** @Fil
**Archive:** <a href="https://doi.org/10.5281/zenodo.2552811" target="_blank">10.5281/zenodo.2552811</a>

## Status

[![status](http://joss.theoj.org/papers/2eea2105f42bbab1e49cf26d935837c8/status.svg)](http://joss.theoj.org/papers/2eea2105f42bbab1e49cf26d935837c8)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/2eea2105f42bbab1e49cf26d935837c8"><img src="http://joss.theoj.org/papers/2eea2105f42bbab1e49cf26d935837c8/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/2eea2105f42bbab1e49cf26d935837c8/status.svg)](http://joss.theoj.org/papers/2eea2105f42bbab1e49cf26d935837c8)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/kmarkert/cartoee" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Fil, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lheagy know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kmarkert/cartoee">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.0.5
- [x] **Authorship:** Has the submitting author (@kmarkert) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by Fil** [comment]
I don't believe that there is COI in this case, but just to make sure, let me state that I have been working on a similar tool, written in Javascript and WebGL, on and off for the last few years. You can see an (older) instance of this tool at [URL](https://www.davidrumsey.com/luna/servlet/detail/RUMSEY~8~1~308989~90078901:Urbano-Monte-World-Map-Reprojection?sort=Pub_List_No_InitialSort%2CPub_Date%2CPub_List_No%2CSeries_No&qvq=q:visionscarto.net;sort:Pub_List_No_InitialSort%2CPub_Date%2CPub_List_No%2CSeries_No;lc:RUMSEY~8~1&mi=0&trs=1).

@lheagy @KMarkert feel free to revoke me if this sounds (even slightly) annoying. For my part I see this rather as a good way to learn and maybe cooperate in the future.

**Comment by Fil** [comment]
@whedon help

**Comment by Fil** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by Fil** [comment]
@lheagy all checked! 

@KMarkert congratulations 🎉

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1109/MCSE.2007.55 is OK
- http://doi.org/10.5281/zenodo.2542609 is OK
- http://doi.org/https://doi.org/10.1016/j.rse.2017.06.031 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lheagy** [comment]
Many thanks @Fil for the speedy review!!

@KMarkert, could you please make a new release and ensure that the title of the zenodo archive is the same as your paper "cartoee: Publication quality maps using Earth Engine" and post the doi here? From there, we can proceed with publication 🎉

**Comment by KMarkert** [comment]
@Fil Thank you very much for the reviews and helping make the package of higher quality.

@lheagy I have edited the name of the zenodo archive to reflect the name of the paper. Can you please confirm that I did this correctly? Here is the doi: https://dx.doi.org/10.5281/zenodo.2552811

**Comment by lheagy** [comment]
@whedon set 10.5281/zenodo.2552811 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2552811" target="_blank">10.5281/zenodo.2552811</a> is the archive.

**Comment by lheagy** [comment]
@whedon set 0.0.5 as version

**Comment by whedon** [comment]
OK. 0.0.5 is the version.

**Comment by lheagy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01207/joss.01207/10.21105.joss.01207.pdf)

**Comment by lheagy** [comment]
👋 Hi @arfon, this submission is ready for publication! Congrats @KMarkert 🎉

**Comment by danielskatz** [comment]
Hi @lheagy - We've moved to rotating editors-in-chief, and this week it's me.  For the future, please notify @joss-eics when there's a paper ready to go, or to otherwise get the person on-duty...

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/462

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/462, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1109/MCSE.2007.55 is OK
- http://doi.org/10.5281/zenodo.2542609 is OK
- http://doi.org/https://doi.org/10.1016/j.rse.2017.06.031 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by danielskatz** [comment]
Thanks for reviewing @Fil and editing @lheagy !

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/463
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01207](https://doi.org/10.21105/joss.01207)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
👋 @arfon - I don't see the paper itself, which should be at https://www.theoj.org/joss-papers/joss.01207/10.21105.joss.01207.pdf
Can you see what might have gone wrong?

**Comment by arfon** [comment]
> Can you see what might have gone wrong?

The paper seems to be there now. Sometimes GitHub pages (where the PDFs are served from) takes longer than a few seconds to update.
