### ISSUE TITLE
[REVIEW]: A News Verification Browser for the Detection of Clickbait, Satire, and Falsified News

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1208]
**Submitting author:** @VictoriaRubin (<a href="http://orcid.org/0000-0003-3610-9967">Victoria Rubin</a>)
**Repository:** <a href="https://github.com/litrl/litrl_code" target ="_blank">https://github.com/litrl/litrl_code</a>
**Version:** v0.14.0.0
**Editor:** @arfon
**Reviewer:** @lrasmus, @CBenghi
**Archive:** <a href="https://doi.org/10.5281/zenodo.2588566" target="_blank">10.5281/zenodo.2588566</a>

## Status

[![status](http://joss.theoj.org/papers/7151f505800a4de5ee91ab5aadabf4f7/status.svg)](http://joss.theoj.org/papers/7151f505800a4de5ee91ab5aadabf4f7)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/7151f505800a4de5ee91ab5aadabf4f7"><img src="http://joss.theoj.org/papers/7151f505800a4de5ee91ab5aadabf4f7/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/7151f505800a4de5ee91ab5aadabf4f7/status.svg)](http://joss.theoj.org/papers/7151f505800a4de5ee91ab5aadabf4f7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/litrl/litrl_code" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@lrasmus & @CBenghi, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/litrl/litrl_code">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.14.0.0
- [x] **Authorship:** Has the submitting author (@VictoriaRubin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/litrl/litrl_code">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.14.0.0
- [x] **Authorship:** Has the submitting author (@VictoriaRubin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lrasmus, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01208/joss.01208/10.21105.joss.01208.pdf)

**Comment by brogly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by danielskatz** [comment]
👋 @lrasmus @CBenghi - Can I get an update from you on this review?

**Comment by lrasmus** [comment]
> 👋 @lrasmus @CBenghi - Can I get an update from you on this review?

@danielskatz I have started with the basic checklist items, sorry it was a little slow start on my end.  I am planning to complete by the end of this week.  Thank you @brogly for updates in manuscript and instructions.

**Comment by lrasmus** [comment]
@danielskatz - clarification question.  The authors have appropriately tagged and marked for release v0.12.0.0 of the software.  Should we review just what is in the repository as of that tag, or include recent commits?  Not trying to be a stickler, just wondering if recommended practice is for authors to re-tag software updates that we then review, or if software gets versioned and tagged following completion of JOSS review.  Thanks!

**Comment by danielskatz** [comment]
You should review changes, particularly those made in response to review issues.

>software gets versioned and tagged following completion of JOSS review

yes, this is what happens

**Comment by brogly** [comment]
@lrasmus @CBenghi - you may need to clone the repository again. Thanks!

**Comment by brogly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01208/joss.01208/10.21105.joss.01208.pdf)

**Comment by brogly** [comment]
@lrasmus @CBenghi minor change to PDF references to clarify that Asubiaro & Rubin and Brogly & Rubin are both unpublished articles

**Comment by danielskatz** [comment]
👋 @lrasmus & @CBenghi - can I get an update from you on where you are in your reviews, in response to @brogly's changes?

**Comment by lrasmus** [comment]
@danielskatz - making progress.  @CBenghi is rocking it reporting technical issues/considerations (https://github.com/litrl/litrl_code/issues).  I am finding some documentation gaps that I am opening issues for in the repo as well.

**Comment by brogly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01208/joss.01208/10.21105.joss.01208.pdf)

**Comment by brogly** [comment]
@CBenghi @lrasmus - Added a newly assigned DOI for one of the references

**Comment by brogly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01208/joss.01208/10.21105.joss.01208.pdf)

**Comment by brogly** [comment]
@lrasmus @CBenghi - Updated document to clarify detector scores as requested by @lrasmus

**Comment by lrasmus** [comment]
@danielskatz , @brogly, @CBenghi - I've completed my review and feel this meets the JOSS review guidelines.

**Comment by danielskatz** [comment]
@CBenghi - how do things look to you at this point?

**Comment by CBenghi** [comment]
@danielskatz,

I've given it another look yesterday and I've seen a lot of progress.
I was waiting for @brogly to complete https://github.com/litrl/litrl_code/issues/21 as he last stated a few days ago to give another look.

@danielskatz, perhaps you can also help clear a doubt that I've expressed at https://github.com/litrl/litrl_code/issues/19, the issue is around the long term reliability of the software as the version of python that it uses reaches end of life in less than a year. I'm not sure what is the policy that Joss adopts around this.

**Comment by danielskatz** [comment]
Thanks.

> @danielskatz, perhaps you can also help clear a doubt that I've expressed at [litrl/litrl_code#19](https://github.com/litrl/litrl_code/issues/19), the issue is around the long term reliability of the software as the version of python that it uses reaches end of life in less than a year. I'm not sure what is the policy that Joss adopts around this.

In this case, given the statement in https://github.com/litrl/litrl_code/issues/19 that this will be fixed before it is an issue, I don't think it should block acceptance of this version of the software.

**Comment by lrasmus** [comment]
I should echo that I think @CBenghi raised some really good issues.  This was my first JOSS review, and I wasn't sure if any of those would be blockers for acceptance or not.

**Comment by brogly** [comment]
@danielskatz - Thanks - we are happy to upgrade the software to Python 3 before 2020 but basically the problem is doing it *right now* - we will have more time for that fix later in the year.

@lrasmus - Thanks for the excellent feedback throughout.

@CBenghi - Still working on the DPI issue and hope to get that fixed today.

**Comment by CBenghi** [comment]
@whedon set v0.14.0.0 as version

**Comment by whedon** [comment]
I'm sorry @CBenghi, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by CBenghi** [comment]
Hi All,
I've been able to spend a bit more time and I feel we are almost there, but I have a couple of minor issues.
  
@danielskatz version of the software should be updated to v0.14.0.0, @whedon rejected my command there.

@brogly, two outstanding aspects to look at for me:
1) I'm uncertain on the benefit or referencing unpublished work (lacking DOI as per checklist above), I would probably remove them at this stage.
2) I've also opened an issue at: https://github.com/litrl/litrl_code/issues/27, I've provided two easy courses of action there, in one of them you'd need to setup a test harness, which I would be happy to help with.

Once these are closed I'm happy to accept.

Best,
Claudio

**Comment by danielskatz** [comment]
@whedon set v0.14.0.0 as version

**Comment by whedon** [comment]
OK. v0.14.0.0 is the version.

**Comment by danielskatz** [comment]
@CBenghi - referencing unpublished work is ok - the checkbox just says that for every reference that has a DOI, the DOI should be listed.  If a reference doesn't have a DOI, that's fine.

**Comment by danielskatz** [comment]
Also, I'm going to be on vacation for 2 1/2 weeks, so I'm shifting the editor of this submission to be @arfon, during that period - thanks @arfon

**Comment by danielskatz** [comment]
@whedon assign @arfon as editor

**Comment by brogly** [comment]
@danielskatz - OK & Thanks! I will leave the unpublished documents then.

@CBenghi - I understand the new issue and will start work on that shortly.

**Comment by CBenghi** [comment]
Dear @arfon,

I'm glad to let you know that @brogly has addressed all the issues. 
I agree with @lrasmus that the repository passes all requirements for the review and I've flagged them all above.

Well done @brogly, I'm tempted to start using this myself in normal web browsing :-)

Best,
Claudio

**Comment by arfon** [comment]
> I agree with @lrasmus that the repository passes all requirements for the review and I've flagged them all above.

Great!

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1208 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2016628 is OK
- 10.1002/pra2.2018.14505501100 is OK
- 10.1002/pra2.2015.145052010081 is OK
- 10.1145/2823465.2823467 is OK
- 10.1002/pra2.2015.145052010083 is OK
- 10.18653/v1/W16-0802 is OK
- 10.5210/fm.v17i3.3933 is OK

MISSING DOIs

- https://doi.org/10.1002/pra2.2018.14505501100 may be missing for title: Falsified News Detection Methodology
- https://doi.org/10.1145/2823465.2823467 may be missing for title: Detecting Clickbait: Here’s how to Do it
- https://doi.org/10.1353/ils.0.0000 may be missing for title: News Verification Suite: Towards System Design to Supplement Reporters’ and Editors’ Judgements

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01208/joss.01208/10.21105.joss.01208.pdf)

**Comment by arfon** [comment]
@VictoriaRubin - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by VictoriaRubin** [comment]
@arfon - The DOI is 10.5281/zenodo.2588566. @danielskatz + @CBenghi @lrasmus - Thank you very much for your review!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.2588566 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2588566" target="_blank">10.5281/zenodo.2588566</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/541

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/541, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2016628 is OK
- 10.1002/pra2.2018.14505501100 is OK
- 10.1002/pra2.2015.145052010081 is OK
- 10.1145/2823465.2823467 is OK
- 10.1002/pra2.2015.145052010083 is OK
- 10.18653/v1/W16-0802 is OK
- 10.5210/fm.v17i3.3933 is OK

MISSING DOIs

- https://doi.org/10.1002/pra2.2018.14505501100 may be missing for title: Falsified News Detection Methodology
- https://doi.org/10.1145/2823465.2823467 may be missing for title: Detecting Clickbait: Here’s how to Do it
- https://doi.org/10.1353/ils.0.0000 may be missing for title: News Verification Suite: Towards System Design to Supplement Reporters’ and Editors’ Judgements

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/542
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01208](https://doi.org/10.21105/joss.01208)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@lrasmus, @CBenghi - many thanks for your reviews here and to @danielskatz for editing this submission ✨ 

@VictoriaRubin - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01208/status.svg)](https://doi.org/10.21105/joss.01208)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01208">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01208/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01208/status.svg
   :target: https://doi.org/10.21105/joss.01208
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01208/status.svg)](https://doi.org/10.21105/joss.01208)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by danielskatz** [comment]
Thanks everyone, I’m glad to see this complete!

**Comment by brogly** [comment]
Thanks everyone!!!
