### ISSUE TITLE
[PRE REVIEW]: vbvs.concurrent: Fitting Methods for the Functional Linear Concurrent Model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#121]
**Submitting author:** @jeff-goldsmith (<a href="http://orcid.org/0000-0002-6150-8997">Jeff Goldsmith</a>)
**Repository:** <a href="https://github.com/jeff-goldsmith/vbvs.concurrent" target ="_blank">https://github.com/jeff-goldsmith/vbvs.concurrent</a>
**Version:** v0.1
**Editor:** @cMadan
**Reviewer:** @fabian-s

**What this issue is for**

Thanks for submitting your paper to JOSS @jeff-goldsmith. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by cMadan** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@jeff-goldsmith - I'm looking for a reviewer via Twitter, but any suggestions would be appreciated!

**Comment by jeff-goldsmith** [comment]
Here are some folks who would be able to review the code and have expertise in the statistical area the package targets:
@fabian-s, @huangracer, @jgellar, @swihart, @Jfortin1, @mandymejia, @emsweene, @sbrockhaus.

Full disclosure -- I've worked with several of these people on other projects, especially those who have contributed to the [refund](https://github.com/refunders/refund) package. If nothing else this might give you something to go on. Thanks!

**Comment by arfon** [comment]
Friendly bump @cMadan 😄 .

**Comment by cMadan** [comment]
@fabian-s, @huangracer, @jgellar, @swihart, @Jfortin1, @mandymejia, @emsweene, @sbrockhaus - would any of you be interested in reviewing this package? It's fine if you've collaborated with @jeff-goldsmith, we just need to make sure the code is sufficiently described, documented, and functional (see http://joss.theoj.org/about#reviewer_guidelines)

**Comment by fabian-s** [comment]
I'd be willing to review it, but won't be able to make it before January. Is that acceptable?

**Comment by cMadan** [comment]
@fabian-s - that's fine with me, thanks for volunteering!

**Comment by cMadan** [comment]
@whedon assign @fabian-s as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @fabian-s

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by cMadan** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/141. Feel free to close this issue now!
