### ISSUE TITLE
[PRE REVIEW]: Social Media Exploratory Data Analytics in Excel

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1213]
**Submitting author:** @professorf (<a href="http://orcid.org/0000-0002-5162-9277">Nick Flor</a>)
**Repository:** <a href="https://github.com/professorf/smeda" target ="_blank">https://github.com/professorf/smeda</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @professorf. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@professorf if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1213 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon.rb:82:in `check_fields': undefined method `keys' for "Nick V. Flor University of New Mexico 27 January 2018":String (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @jasonclark - Can you edit this submission?

**Comment by danielskatz** [comment]
👋 @jasonclark - ping... Can you edit this submission?

**Comment by professorf** [comment]
Please let me know if you have any questions. Thanks - Nick

**Comment by labarba** [comment]
I don't think this submission is ready to be assigned an editor and begin review. 

First, @arfon, should JOSS consider an analysis pipeline using Excel as "open source software"? Is it even "software"?

Second, the repository contains a `paper.md` file, but it does not conform to the JOSS requirements. The author needs to read and follow the [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html) to prepare a `paper.md` with the needed metadata.

**Comment by arfon** [comment]
@professorf - many thanks for your submission to JOSS. The editors of JOSS have had an offline discussion about this submission and we've decided that Excel submissions are not allowable in JOSS. 

There are a number of challenges with Excel submissions for JOSS:

- 'Source code' is captured in a binary file.
- Excel isn't really software:
  - It's extremely hard (impossible?) to cleanly separate the code components from the data being executed on.
  - Testing of these macros in any formal way is very challenging.
  - Very hard to develop something for [maintainable extension](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).
