### ISSUE TITLE
[PRE REVIEW]: FSharpGephiStreamer: An idiomatic bridge between F# and network visualization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1214]
**Submitting author:** @muehlhaus (<a href="http://orcid.org/0000-0003-3925-6778">Timo Mühlhaus</a>)
**Repository:** <a href="https://github.com/CSBiology/FSharpGephiStreamer" target ="_blank">https://github.com/CSBiology/FSharpGephiStreamer</a>
**Version:** v1.1.0
**Editor:** @danielskatz
**Reviewers:** @cgravill, @PrashantVaidyanathan

**Author instructions**

Thanks for submitting your paper to JOSS @muehlhaus. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@muehlhaus if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1214 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1214/paper/paper.md): invalid leading UTF-8 octet at line 1 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @arfon - can you help with this one?

**Comment by danielskatz** [comment]
👋 @yochannah - would you be willing to edit this?
(Note that there's a pdf problem that I'm hoping @arfon will help us solve as well)

**Comment by yochannah** [comment]
@danielskatz Sure! 

@muehlhaus we don't seem to have any F# reviewers on our list so it could take a little while longer to find someone. Do you have any suggestions? No worries if not.

**Comment by danielskatz** [comment]
@whedon assign @yochannah as editor

**Comment by whedon** [comment]
OK, the editor is @yochannah

**Comment by arfon** [comment]
This looks to be a bug in our LaTeX template at the `#` in the title. I've been trying to fix this for the last hour and haven't found an easy fix yet sorry.

**Comment by muehlhaus** [comment]
@yochannah - I am afraid that people I would recommend with the necessary expertise might not be completely free regarding conflicts of interest. I am very sorry.

**Comment by yochannah** [comment]
@swoodhouse 👋 I wonder if you might be interested in reviewing this paper by any chance?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01214/joss.01214/10.21105.joss.01214.pdf)

**Comment by muehlhaus** [comment]
The article proof looks fine. Thank you for fixing the pdf generator that it can cope with our article.

**Comment by yochannah** [comment]
Hi @tpetricek - I know you're busy reviewing another item on JOSS at the minute so I won't ask you to look at another (unless you want to!) - but I was wondering if you could recommend any F#-ers who might be interested in reviewing this?

**Comment by tpetricek** [comment]
This looks like a nice project! I'd try asking @cgravill or maybe @sylvanc.

**Comment by yochannah** [comment]
Thanks @tpetricek!

@cgravill, @sylvanc, are either or both of you interested in reviewing this paper by any chance?

**Comment by yochannah** [comment]
Still looking for a reviewer on this at the minute - most of the people I've managed to find through searches so far either have no research experience or have collaborated with the current authors 😆 I did find another name to try, though - @gbaydin, is this something we could interested you in reviewing?

**Comment by kMutagene** [comment]
Hi @yochannah,
Thank you for your continued efforts in finding a reviewer for our paper. I guess a factor why it is so hard finding people for this may be that all the fsharpers go straight to industry, which in my opinion is a pity as we see F# as a language suited very well for research in bioinformatics (and for all kinds of data analysis).

**Comment by cgravill** [comment]
I’m also more on the industry side. Still, it seems like you’re having a challenge engaging an ideal reviewer, so I’d be willing to assist if that helps.

**Comment by yochannah** [comment]
@cgravill I would be very happy to take you up on this one. Ideally I'd like a second reviewer as well - any chance you know anyone who might be interested?

**Comment by cgravill** [comment]
I'd tag @tpetricek but I fear we'd have a cycle going then! :-) I'll try asking around.

**Comment by labarba** [comment]
@yochannah 👋  — how are you getting on searching for reviewers for this submission?

**Comment by cgravill** [comment]
@PrashantVaidyanathan may also be able to help

**Comment by labarba** [comment]
Hi folks! @yochannah will be stepping down from the JOSS board, due to other obligations making it hard for her to volunteer time currently. I would like to reassign this submission to another editor.

@danielskatz — given current loads, could you take over on this one?

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @PrashantVaidyanathan  - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
👋 @cgravill - thanks for agreeing to review - once I get one more reviewer, we'll start the review

**Comment by danielskatz** [comment]
@whedon assign @cgravill as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @cgravill

**Comment by danielskatz** [comment]
👋 @TahaHachana, @dsyme, @jackfoxy, @tpetricek - would one of you be willing be the 2nd reviewer for this JOSS submission?  (See our [reviewer guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) if needed)

**Comment by jackfoxy** [comment]
@danielskatz  thanks for the invitation. I'm going to have to beg out...too many other commitments, and I'm probably the least qualified for this topic.

**Comment by PrashantVaidyanathan** [comment]
@danielskatz I'm happy to help. I'm travelling this week so the earliest I can send in my reviews is 20th May if that's alright?

**Comment by danielskatz** [comment]
@PrashantVaidyanathan - Thanks! You will see as we start the review that a JOSS review is not a one-time read, but a set of suggestions and requests to the author, and an iterative process with the author to improve the submission (both the paper and the software)

**Comment by danielskatz** [comment]
@whedon add @PrashantVaidyanathan as reviewer

**Comment by whedon** [comment]
OK, @PrashantVaidyanathan is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1445. Feel free to close this issue now!
