### ISSUE TITLE
[PRE REVIEW]: Compare Expression Profiles for Pre-defined Gene Groups with C-REx

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1215]
**Submitting author:** @edifice1989 (<a href="http://orcid.org/0000-0002-8164-2480">Mingze He</a>)
**Repository:** <a href="https://github.com/edifice1989/rocker-c-rex" target ="_blank">https://github.com/edifice1989/rocker-c-rex</a>
**Version:** v1.0
**Editor:** @mgymrek
**Reviewers:** @byandell

**Author instructions**

Thanks for submitting your paper to JOSS @edifice1989. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@edifice1989 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01215/joss.01215/10.21105.joss.01215.pdf)

**Comment by danielskatz** [comment]
Hi @edifice1989 - I note that your PDF does not have any references that are built.  It looks like you manually added references in your .md file, rather than using the `@` notation as in the [sample paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography).  Please fix this, and once you have done so, enter a new comment here with ```@whedon generate pdf``` to restart the PDF processing.

**Comment by edifice1989** [comment]
@whedon generate pdf

**Comment by danielskatz** [comment]
This might be an instance when replying to an email doesn't work, and you actually need to type the command in as a new comment in GitHub.

(@arfon - do you know if this is correct?)

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
> This might be an instance when replying to an email doesn't work, and you actually need to type the command in as a new comment in GitHub.

> (@arfon - do you know if this is correct?)

I think that's right. You need to actually type the command here.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01215/joss.01215/10.21105.joss.01215.pdf)

**Comment by pjotrp** [comment]
Nice contribution. I'll look for an editor.

**Comment by danielskatz** [comment]
I'll mark it as you for now, so that it's not on my list of papers awaiting an editor, and when you determine who you think should edit it, you can change the assignment to them.

**Comment by danielskatz** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@danielskatz please do not do that.

**Comment by danielskatz** [comment]
sorry - let me see if I can undo it

**Comment by pjotrp** [comment]
@whedon assign @mgymrek as editor

**Comment by whedon** [comment]
OK, the editor is @mgymrek

**Comment by mgymrek** [comment]
@byandell would you be able to review this one? Or do you have any suggestions?

**Comment by edifice1989** [comment]
should we find another editor? thanks!

Ming

**Comment by pjotrp** [comment]
@edifice1989 I presume you mean say reviewer?

**Comment by edifice1989** [comment]
yes. I mean reviewer. Thanks!!

**Comment by mgymrek** [comment]
@whedon assign @byandell as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @byandell

**Comment by mgymrek** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1255. Feel free to close this issue now!
