### ISSUE TITLE
[PRE REVIEW]: dfitspy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1217]
**Submitting author:** @astrom-tom (<a href="http://orcid.org/0000-0001-8385-3276">Romain Thomas</a>)
**Repository:** <a href="https://github.com/astrom-tom/dfitspy" target ="_blank">https://github.com/astrom-tom/dfitspy</a>
**Version:** v19.1.5
**Editor:** @arfon
**Reviewers:** @taldcroft

**Author instructions**

Thanks for submitting your paper to JOSS @astrom-tom. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@astrom-tom if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1217 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
@astrom-tom - I don't see any .bib file in your repo, and your reference is written manually, rather than being compiled.  Please refer to https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography for an example.  Once you've made changes in your repository, enter ```@whedon generate pdf``` as a new comment here to attempt to rebuild the pdf from the md and bib files.

**Comment by danielskatz** [comment]
You also need some real content in the readme, including the purpose of the software, what problems it can solve, a pointer to how it can be installed and tested, how others can contribute, etc.

See https://joss.readthedocs.io/en/latest/review_criteria.html, which states: 
> A high-level overview of this documentation should be included in a README file (or equivalent).

**Comment by danielskatz** [comment]
Also, I see a bunch of temporary files inside the repository that you might want to remove - those that end with `~`

**Comment by danielskatz** [comment]
Once these changes are made, let me know and we'll move forward to assigning an editor

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1217 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01217/joss.01217/10.21105.joss.01217.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01217/joss.01217/10.21105.joss.01217.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01217/joss.01217/10.21105.joss.01217.pdf)

**Comment by danielskatz** [comment]
> Thank you for dealing with my submission. For the readme, there is only one link that goes to github pages (full documentation made with sphinx). Is that enough?

No, it's not.  This is what I wrote in https://github.com/openjournals/joss-reviews/issues/1217#issuecomment-458549216

**Comment by astrom-tom** [comment]
A high-level overview of this documentation should be included in a README file (or equivalent).  

What means 'or equivalent'?
In any case, I updated the readme and pointed also to the real online documentation.

**Comment by danielskatz** [comment]
Equivalent is in case the software is not on github and in some other system where the initial file has some other name.

**Comment by danielskatz** [comment]
👋 @arfon - can you edit this submission?

**Comment by danielskatz** [comment]
@astrom-tom Regarding the readme, thanks for your updates, and, can you try to generalize it a bit? Think about how it will look to non-astronomers - will they have any idea what the software does? Or who might want to use it, and for what kind of research problems?

**Comment by astrom-tom** [comment]
dear @danielskatz,

I updated the readme to briefly present the FITS file format and give a bit more details of what is dfitspy doing.
Let me know if this is ok.

Thank you!

**Comment by arfon** [comment]
> 👋 @arfon - Can I pass this to you to edit? It also probably needs a check regarding the JOSS criteria about utility packages.

Yep, I may give this to our new editor. Regardless, I can take it from here.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @astrom-tom - thanks for submitting this package to JOSS. Could you say a little more about how this submission meets the following [submission criteria](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements)?

> - The software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler)

For this, it's not clear to me that this functionality isn't available elsewhere (e.g. in https://github.com/esheldon/fitsio or astropy).

Additionally:

> - The software should be feature complete (no half-baked solutions) and designed for maintainable extension (not one-off modifications).

Have you considered contributing this to a larger community package such as `astropy.io.fits`? This feels like a more natural home for functionality like this than a small standalone package.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by astrom-tom** [comment]
Dear @arfon, 

Thank you for being the editor for my code. 
To answer your questions:
- This package have been partially developed at the Very Large Telescope to ease the search and the display of fitsfiles metadata among large number of files. dfistpy primarily aims at being included in scripts where large number of fitsfiles have to be reviewed in an fast and efficient way (without looking at the data), which is the case at the telescope but also for programs that have a lot of data. Additionally, it can be used directly in the terminal as a stand-alone package for simple display in the terminal (a-la dfits+fitsort). It is worth noting that my supervisor allowed me to submit this package and the package will remain in active development.

-dfitspy is designed to do one thing only and has been optimized for it. Of course, with some work you can rewrite this for your own code (which is the case for, I guess, a lot of codes). I used fitsio and numpy modules as building blocks. I also tried using astropy but it seems that using fitsio was much faster when I tested with thousands of files (using the cfitsio wrapper directly included in the fitsio python module). I do not believe that including this in the astropy.io.fits is a good option.

Hope this answers your questions and do not prevent the review of this module.

Best,

R.

**Comment by arfon** [comment]
> Hope this answers your questions and do not prevent the review of this module.

I think this is sufficient. Thanks for the additional background.

@taldcroft - would you be interested in reviewing this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by taldcroft** [comment]
@arfon - what's  the time scale for review?  Next 2-3 of weeks are tough, but after that I'd be happy to review this submission.

**Comment by arfon** [comment]
> @arfon - what's the time scale for review? Next 2-3 of weeks are tough, but after that I'd be happy to review this submission.

Do you think you could complete your initial review by the 12th March?

**Comment by taldcroft** [comment]
@arfon - no problem by 12th March.

**Comment by arfon** [comment]
@whedon assign @taldcroft as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @taldcroft

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1249. Feel free to close this issue now!

**Comment by arfon** [comment]
> @arfon - no problem by 12th March.

Great. Thanks @taldcroft - please head over to #1249 to carry out the actual review.
