### ISSUE TITLE
[PRE REVIEW]: crystal-torture: A crystal tortuosity module

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1218]
**Submitting author:** @connorourke (<a href="http://orcid.org/0000-0002-0703-8234">Conn O&#39;Rourke</a>)
**Repository:** <a href="https://github.com/connorourke/crystal_torture" target ="_blank">https://github.com/connorourke/crystal_torture</a>
**Version:** v1.0.3
**Editor:** @katyhuff
**Reviewers:** @vahtras, @mkhorton

**Author instructions**

Thanks for submitting your paper to JOSS @connorourke. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@connorourke if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01218/joss.01218/10.21105.joss.01218.pdf)

**Comment by danielskatz** [comment]
👋 @katyhuff - Would you be willing to edit this submission?

**Comment by katyhuff** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by katyhuff** [comment]
Sorry -- that darn close and comment button is the worst UI in the universe.

**Comment by katyhuff** [comment]
@connorourke and @bjmorgan : Thank you for your submission! 

I'm going to be looking for reviewers and could use your help. If you see anyone in [this list](https://bit.ly/joss-reviewers) who would be appropriate, I would be grateful if you could point them out. I'll look closely as well, but frequently the authors have insight on the appropriateness of reviewers that an editor cannot have. It's important that reviewers have domain knowledge in the field of the submission (computational physics/chemistry/materials)  as well as familiarity with the systems and languages involved (python, fortran, openMP). 

Before I assign anyone,  I am going to do a little pre-review. You may see some issues pop up in your repo.

**Comment by katyhuff** [comment]
FYI: these are the reviewers that stand out to me from our reviewer pool, with regard to this submission. I am not "@" including them until I've completed some basic checks. 

- jochym
- ledius
- jwuttke
- stuartcampbell
- diegoenry
- vahtras
- goerz

**Comment by bjmorgan** [comment]
@katyhuff: Other suggested potential reviewers:

* yxqd
* mkhorton
* bocklund
* mdoucet

**Comment by katyhuff** [comment]
@bjmorgan I'm sorry for taking so long to handle this submission. I usually don't let these sit for more than a couple of days before requesting reviewers. Your submission slipped through the cracks. I apologize for the delay. Anyway, I'll be requesting reviewers now.

**Comment by katyhuff** [comment]
Dear reviewers,
This submission is in need of expertise in computational physics/chemistry/materials as well as familiarity with the systems and languages involved (python, fortran, openMP).

@goerz : Michael, are you able to and interested in taking on this review?
@jwuttke : Joachim, are you able to and interested in taking on this review?
@jochym : Pawel, are you able to and interested in taking on this review?
@vahtras: Olav, are you able to and interested in taking on this review?

- Title: crystal-torture: A crystal tortuosity module
- Summary: crystal_torture is a Python, Fortran and OpenMP crystal structure analysis module. The module contains a set of classes that enable: a crystal structure to be converted into a graph for network analysis, connected clusters of crystal sites (nodes) to be retrieved and output, periodicity of connected clusters of crystal sites to be determined, and relative path tortuosity to traverse a crystal within a connected cluster to be calculated for each site.
- Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01218/joss.01218/10.21105.joss.01218.pdf
- Submitting author: @bjmorgan (Benjamin Morgan)
- Repository: https://github.com/connorourke/crystal_torture
- Version: v1.0.3

A very nice jupyter notebook example is found here: https://nbviewer.jupyter.org/github/connorourke/crystal_torture/blob/master/examples/crystal_torture_examples.ipynb

**Comment by vahtras** [comment]
Yes I can

**Comment by katyhuff** [comment]
@whedon assign @vahtras as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @vahtras

**Comment by goerz** [comment]
I'm traveling the next two weeks, so I wouldn't be available to look at this until after March 17.

**Comment by katyhuff** [comment]
Thanks @goerz , for letting me know . I'll see if we can get a second reviewer signed up who is more available.

**Comment by katyhuff** [comment]
Hi Folks,

@jwuttke : Joachim, are you able to and interested in taking on this review?
@jochym : Pawel, are you able to and interested in taking on this review?
@yxqd : Jiao, are you able to and interested in taking on this review?
@mkhorton : Matthew, are you able to and interested in taking on this review?


- Title: crystal-torture: A crystal tortuosity module
- Summary: crystal_torture is a Python, Fortran and OpenMP crystal structure analysis module. The module contains a set of classes that enable: a crystal structure to be converted into a graph for network analysis, connected clusters of crystal sites (nodes) to be retrieved and output, periodicity of connected clusters of crystal sites to be determined, and relative path tortuosity to traverse a crystal within a connected cluster to be calculated for each site.
- Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01218/joss.01218/10.21105.joss.01218.pdf
- Submitting author: @bjmorgan (Benjamin Morgan)
- Repository: https://github.com/connorourke/crystal_torture
- Version: v1.0.3

**Comment by mkhorton** [comment]
Hi @katyhuff, I'd be interested in this one!

**Comment by katyhuff** [comment]
Fantastic! Thanks @mkhorton !

**Comment by katyhuff** [comment]
@whedon add @mkhorton as reviewer

**Comment by whedon** [comment]
OK, @mkhorton is now a reviewer

**Comment by katyhuff** [comment]
Two should do it. Let's get the review started.

**Comment by katyhuff** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1306. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Ok, @vahtras, @mkhorton, @connorourke, @bjmorgan , let's move over to #1306!
