### ISSUE TITLE
[PRE REVIEW]: getTBinR: an R package for accessing and summarising the World Health Organisation Tuberculosis data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1219]
**Submitting author:** @seabbs (<a href="http://orcid.org/0000-0001-8057-8037">Sam Abbott</a>)
**Repository:** <a href="https://github.com/seabbs/getTBinR" target ="_blank">https://github.com/seabbs/getTBinR</a>
**Version:** v0.5.7
**Editor:** @trallard
**Reviewers:** @rrrlw, @strengejacke

**Author instructions**

Thanks for submitting your paper to JOSS @seabbs. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@seabbs if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by danielskatz** [comment]
@seabbs - once you've made changes (as in 
https://github.com/seabbs/getTBinR/pull/52), type ```@whedon generate pdf``` as a new comment here to retry the compilation

**Comment by seabbs** [comment]
@whedon generate pdf

**Comment by danielskatz** [comment]
I'm not sure why that didn't work - let's try again (and notify @arfon as well)

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1219 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1219/inst/paper/paper.md): mapping values are not allowed in this context at line 16 column 34 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by seabbs** [comment]
Looks like I had a : that was causing issues. Hopefully fixed now

@whedon generate pdf

**Comment by danielskatz** [comment]
you definitely need to make the command the first thing in a comment - can you try again?

**Comment by seabbs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by danielskatz** [comment]
good - not sure why the command didn't work for you the other time. Maybe whedon was misbehaving...

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01219/joss.01219/10.21105.joss.01219.pdf)

**Comment by danielskatz** [comment]
👋 @trallard - would you be willing to edit this submission?

**Comment by trallard** [comment]
sure thing @danielskatz

**Comment by danielskatz** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by seabbs** [comment]
Is there anything I can do to help move this along?

**Comment by trallard** [comment]
🙋🏻‍♀️ Hi @seabbs (sorry for the delayed action) I will be performing the editorial duties for this submission. If you have any questions over the review process please feel free to @ me.

The first step is to find suitable reviewers for this submission. Have you got any suitable people in mind? Otherwise, you can check the list of reviewers we have and suggest a few here.

**Comment by trallard** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by seabbs** [comment]
Hi @trallard  - no problem. 

No external people in mind. Looking at the list (from bottom to top) here are a few that looked relevant (in no particular order): 

* stulacy (R + epidemiology)
* rrrlw (R + Data visualisation + Epidemiology)
* strengejacke (R + Epidemiology + Data visualisation)
* aj2duncan (R + Epidemiology)
* patatefritte (R + Epidemiology)
* ellessenne (R + Epidemiology)
* ibontama (R + Epidemiology)
* rosap (R + Epidemiology
* simonthelwall (R + Epidemiology + Infectious disease)*
* darokun (R + Epidemiology + Public Health)*
* petermacp (R + Epidemiology + Infectious disease)*
* noamross (R + Epidemiology) 
* masalmon (R + Epidemiology) * 

`*` indicate people that look like they have R experience, are generally active in epidemiology, and have done work on infectious disease.

Hope that helps - let me know if you need anything more.

**Comment by seabbs** [comment]
@trallard 

I was wondering if It was okay to do development work whilst awaiting/under review? I have the next version [changes prepped](https://github.com/seabbs/getTBinR/projects/2) and just waiting on this to implement (some time has come up whilst I avoid writing my thesis :)).

Thanks!

**Comment by trallard** [comment]
Dear reviewers,

@stulacy Stuart are you able and willing to take this review?
@rrrlw Raul are you able and willing to take this review?
@strengejacke Daniel are you able and willing to take this review?
@noamross Noam are you able and willing to take this review?
@maelle MaëlleMaëlle are you able and willing to take this review?
@darokun Daloha are you able and willing to take this review?


**Title:** Get TB Data in R
**Summary:** Quickly and easily import analysis ready TB burden data, from the World Health Organisation (WHO), into R. The aim of the package is to speed up access to high quality TB burden data, using a simple R interface. Generic plotting functions are provided to allow for rapid graphical exploration of the WHO TB data.
**Article Proof:** [https://github.com/openjournals/joss-papers/blob/joss.01219/joss.01219/10.21105.joss.01219.pdf](https://github.com/openjournals/joss-papers/blob/joss.01219/joss.01219/10.21105.joss.01219.pdf)
Submitting author: @seabbs 
**Repository:** [https://github.com/seabbs/getTBinR](https://github.com/seabbs/getTBinR)

**Comment by trallard** [comment]
@seabbs yes that is perfectly fine, we will just update the version after those improvements and the review 

Once two or more reviewers have agreed to help out we can proceed with the review process

**Comment by rrrlw** [comment]
I would be happy to review this submission.

**Comment by trallard** [comment]
thanks @rrrlw

**Comment by trallard** [comment]
@whedon set @rrrlw as reviewer

**Comment by strengejacke** [comment]
I also have time and could review this submission!

**Comment by arfon** [comment]
> @whedon set @rrrlw as reviewer

@trallard - you want `@whedon add @rrrlw as reviewer` <- (or assign rather than add)

**Comment by trallard** [comment]
@whedon assign @rrrlw as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rrrlw

**Comment by trallard** [comment]
@whedon add @strengejacke as reviewer

**Comment by whedon** [comment]
OK, @strengejacke is now a reviewer

**Comment by trallard** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1260. Feel free to close this issue now!

**Comment by trallard** [comment]
Thanks, @arfon 🤦🏻‍♀️ I sometimes get the commands mixed up 

---
Now that we have two reviewers we are ready to proceed with the formal review so let's move over to the review issue!
