### ISSUE TITLE
[PRE REVIEW]: shmlast: An improved implementation of Conditional Reciprocal Best Hits with LAST and Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#122]
**Submitting author:** @camillescott (<a href="http://orcid.org/0000-0001-8822-8779">Camille Scott</a>)
**Repository:** <a href="https://github.com/camillescott/shmlast" target ="_blank">https://github.com/camillescott/shmlast</a>
**Version:** v1.0.2
**Editor:** @biorelated
**Reviewer:** @genomematt

**What this issue is for**

Thanks for submitting your paper to JOSS @camillescott. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current JOSS editors:

```
@acabunoc
@arfon
@biorelated
@cMadan
@danielskatz
@jakevdp
@karthik
@katyhuff
@Kevin-Mattheus-Moerman
@kyleniemeyer
@labarba
@mgymrek
@pjotrp
@tracykteal
```

**Comment by arfon** [comment]
@biorelated - would you be willing to edit this submission for JOSS?

**Comment by biorelated** [comment]
@arfon yes I will. 👍

**Comment by biorelated** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by arfon** [comment]
@whedon set @biorelated as editor

**Comment by arfon** [comment]
@whedon assign @biorelated as editor

**Comment by whedon** [comment]
OK, the editor is @biorelated

**Comment by biorelated** [comment]
@Genomematt would you be  happy to review this work please?

**Comment by genomematt** [comment]
@whedon assign @genomematt as reviewer

**Comment by whedon** [comment]
I'm sorry @genomematt, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by genomematt** [comment]
:hand: I will review @biorelated  ( @whedon is clearly too ethical to let me self assign )

**Comment by arfon** [comment]
> ✋ I will review @biorelated ( @whedon is clearly too ethical to let me self assign )

Lol. Yes, something like that.

**Comment by arfon** [comment]
(I'll let @biorelated do the honors here but thanks in advance @genomematt)

**Comment by biorelated** [comment]
@whedon assign @genomematt as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @genomematt

**Comment by biorelated** [comment]
Sorry @genomematt  for the delay i assigning the review task. I was away from Github the last 2 days. Glad you can review this!

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/142. Feel free to close this issue now!

**Comment by arfon** [comment]
@biorelated @genomematt - the actual review issue is over in #142
