### ISSUE TITLE
[REVIEW]: areal: An R package for areal weighted interpolation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1221]
**Submitting author:** @chris-prener (<a href="http://orcid.org/0000-0002-4310-9888">Christopher Prener</a>)
**Repository:** <a href="https://github.com/slu-openGIS/areal" target ="_blank">https://github.com/slu-openGIS/areal</a>
**Version:** v0.1.4.3
**Editor:** @lheagy
**Reviewer:** @sjsrey, @edzer
**Archive:** <a href="https://doi.org/10.5281/zenodo.2667289" target="_blank">10.5281/zenodo.2667289</a>

## Status

[![status](http://joss.theoj.org/papers/3adac04a327078b3ae62f3232830ffb1/status.svg)](http://joss.theoj.org/papers/3adac04a327078b3ae62f3232830ffb1)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/3adac04a327078b3ae62f3232830ffb1"><img src="http://joss.theoj.org/papers/3adac04a327078b3ae62f3232830ffb1/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/3adac04a327078b3ae62f3232830ffb1/status.svg)](http://joss.theoj.org/papers/3adac04a327078b3ae62f3232830ffb1)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/slu-openGIS/areal" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sjsrey & @edzer, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lheagy know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/slu-openGIS/areal">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.1.4.3
- [x] **Authorship:** Has the submitting author (@chris-prener) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/slu-openGIS/areal">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.1.4.3
- [x] **Authorship:** Has the submitting author (@chris-prener) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @sjsrey, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by lheagy** [comment]
:wave: Many thanks @sjsrey, @edzer for being willing to review! In the main thread above, there is a checklist for you both to help guide the review. If you haven't previously reviewed for JOSS, please be sure to accept the invite: https://github.com/openjournals/joss-reviews/invitations. This will allow you to check off the items in the checklist. If possible, we would appreciate receiving your review within the next 2 weeks. 

Please let me know if you have any questions or if I can provide clarification on anything.

**Comment by chris-prener** [comment]
Thanks @sjsrey and @edzer for volunteering to review - we're looking forward to your feedback!

**Comment by sjsrey** [comment]
@chris-prener when installing via 
```
> install.packages("areal")
```
 I'm getting:
```
ERROR: dependencies ‘lwgeom’, ‘sf’ are not available for package ‘areal’
  * removing ‘/home/serge/anaconda3/lib/R/library/areal’

The downloaded source packages are in
        ‘/tmp/RtmpBEpBpJ/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages("areal") :
  installation of package ‘units’ had non-zero exit status
2: In install.packages("areal") :
  installation of package ‘sf’ had non-zero exit status
3: In install.packages("areal") :
  installation of package ‘lwgeom’ had non-zero exit status
4: In install.packages("areal") :
  installation of package ‘areal’ had non-zero exit status
> library(areal)
Error in library(areal) : there is no package called ‘areal’
>
```

I realize this might be due to using R installed via conda. But on Ubuntu 18.04 I'm getting the same error(s) on a clean install of R from the official repositories:
```
* DONE (dplyr)
ERROR: dependencies ‘lwgeom’, ‘sf’ are not available for package ‘areal’
* removing ‘/home/serge/R/x86_64-pc-linux-gnu-library/3.4/areal’

The downloaded source packages are in
        ‘/tmp/Rtmpb2kPO5/downloaded_packages’
Warning messages:
1: In install.packages("areal") :
  installation of package ‘units’ had non-zero exit status
2: In install.packages("areal") :
  installation of package ‘sf’ had non-zero exit status
3: In install.packages("areal") :
  installation of package ‘lwgeom’ had non-zero exit status
4: In install.packages("areal") :
  installation of package ‘areal’ had non-zero exit status
> library(areal)
Error in library(areal) : there is no package called ‘areal’
```

**Comment by edzer** [comment]
This is a nice package that provides relatively limited functionality over `sf::st_interpolate_aw` (which I wrote), but that explains and illustrates the whole areal interpolation process very well. Since JOSS does not demand new functionality, it is a nice addition to the existing package ecosystem around `sf`. I recommend that the authors address the following issues:

* The pdf of the paper shows R code on page 2, but this code is hidden where it runs off the page at the side.
* The manuscript claims it provides functions that "validate data suitability for areal interpolation", but does not explain what this validation does. What does it do?
* given that the package does little more than `sf::st_interpolate_aw`, and given that that function was available first, the added value of the packages would become more clear when it would 
     * mention the name of that _function_ (rather than refer to "the existing functionality in `sf`"),
     * show in a side-by-side comparison that `areal::aw_interpolate` and `sf::st_interpolate_aw` give identical results for an intensive an an extensive variable
     * give an example where `areal::aw_interpolate` does something different when there is a difference in areas, and show how large the effect of doing this is
* the correct reference for _Pebesma, E. (2018)_ is found [here](https://journal.r-project.org/archive/2018/RJ-2018-009/index.html)
* change the wording of "black box", as this is not a black box. Closed source software is a black box
* the `areal-weighted-interpolation` vignette mentions "Spatially intensive operations are used when the data to be interpolated are a ratio." I'm afraid it is not this simple: a counter example is is CO2 emissions measured in tons/year: an extensive variable when interpolated spatially.

**Comment by chris-prener** [comment]
Thanks so much for the feedback @edzer - we can make these changes!

**Comment by sjsrey** [comment]
Well designed and documented package that extends important functionality for areal interpolation. A couple of points the authors may want to consider - these are not show stoppers by any means just food for thought and perhaps future extensions:

* Scaling: the current examples are well crafted and illustrate the core functionality. At the same time `n` is fairly modest here and one wonders if these methods were going to be used for larger `n` problems, or applied iteratively over [many cities ](https://spatial.ucr.edu/project_neighborhood.html), would there be any bottlenecks users should be aware of?
* The distinction between extensive and intensive variables is handled nicely. One case that might also be considered is the choice between interpolation of an intensive variable directly versus deriving the intensive estimates as a ratio of two extensive variables that have been estimated: `pct_black = black/total`, for example could be based on first estimating `black`, and `total`, or it could be treated as an intensive variable that is estimated in one step.. Related to this is that there are inherent constraints that are likely violated when treating the intensive and extensive variables independently in certain cases. For example, in a simple world where where 'total = black + white`, this implies `pct_black + pct_white =1`. If the intensive and extensive variables involved are estimated independently, this constraint is likely to be violated.
*  The `weight` argument names are a bit confusing. `sum`, to me, would seem to a better name for the case where intersection  between the target areas and a source area do not exhaust the source area. In other words, use the sum of the intersection area over the source area to form the weight. `total`, to me, seems to imply one would want to allocate the total value of the source area over the target areas.

**Comment by chris-prener** [comment]
Thanks @sjsrey - I appreciate your feedback. We can absolutely address your last point to clarify `sum` and `total`. We can also clarify point two a bit in the documentation. 

Re: your first bullet - I imagine there would be speed issues with a large `n`... a benchmark where we interpolate from state to counties might possibly illustrate speed constraints?

In any event - we can address these points in an updated draft. Will post here when the paper manuscript and associated documentation for the package has been updated. @lheagy - aside from addressing reviewer concerns, are there any other steps we need to take at this stage?

**Comment by lheagy** [comment]
Thanks for getting in touch @chris-prener, addressing reviewer comments is the only thing that needs to be done at this stage. Please ping again when you feel they have all been addressed and we can proceed from there. 

Many thanks @edzer and @sjsrey for your feedback!

**Comment by labarba** [comment]
👋 @chris-prener — How are you getting along? It looks like we're waiting here for you to respond to the reviewer comments. Can you give us a status update?

**Comment by chris-prener** [comment]
Hi @labarba and @lheagy - good - should have revisions wrapped up this week. I'll check in on Saturday at the latest.

**Comment by chris-prener** [comment]
We would like to thank both @edzer and @sjsrey as well as @lheagy for the feedback and the opportunity to revise both the software and the manuscript. We believe that the manuscript has been greatly strengthened as a result of your collective feedback and are excited to resubmit it for your review. @lheagy, if there is a better way to embed tables and to handle the appendix file we've created (available [here](https://github.com/slu-openGIS/areal/blob/master/paper/appendix.md)), please let us know - we're happy to adapt both to any style that *JOSS* prefers.

## Reviewer 1 - @edzer
* The pdf of the paper shows R code on page 2, but this code is hidden where it runs off the page at the side.
    * The example has been changed to return a tibble object rather than an `sf` object. A new line was added below the example that clarifies the `sf` functionality as well.

* The manuscript claims it provides functions that "validate data suitability for areal interpolation", but does not explain what this validation does. What does it do?
    * A description of the validation process has been added to the manuscript in the section titled **The `areal` R package**.

* given that the package does little more than sf::st_interpolate_aw, and given that that function was available first, the added value of the packages would become more clear when it would mention the name of that function (rather than refer to "the existing functionality in sf"),
    * A direct reference to `sf::st_interpolate_aw` in the first paragraph of the section titled **The `areal` R package**.

* show in a side-by-side comparison that areal::aw_interpolate and sf::st_interpolate_aw give identical results for an intensive an extensive variable
    * This is included in the new **A Quick Comparison with sf** section with two figures, one for extensive interpolations and one for intensive interpolations.

* give an example where areal::aw_interpolate does something different when there is a difference in areas, and show how large the effect of doing this is
    * This is included in the new **A Quick Comparison with sf** section with a figure and a description of the difference as well as why one approach may be preferable over the other.

* the correct reference for Pebesma, E. (2018) is found here
    * This has been corrected

* change the wording of "black box", as this is not a black box. Closed source software is a black box
    * This has been changed to:

    > "for users who need to unpack the interpolation workflow"

* the areal-weighted-interpolation vignette mentions "Spatially intensive operations are used when the data to be interpolated are a ratio." I'm afraid it is not this simple: a counter example is is CO2 emissions measured in tons/year: an extensive variable when interpolated spatially.
    * This has been changed to:

    > "Spatially *intensive* operations are used when the data to be interpolated are, for example, a percentage or density value."

* Additionally, @edzer provided [feedback](https://github.com/slu-openGIS/areal/issues/18) about two packages listed as dependencies that may not be necessary.
    * Both `lwgeom` and `tibble` have been removed as dependencies

## Reviewer 2 - @sjsrey

* Scaling: the current examples are well crafted and illustrate the core functionality. At the same time n is fairly modest here and one wonders if these methods were going to be used for larger n problems, or applied iteratively over many cities , would there be any bottlenecks users should be aware of?
    * We have added benchmarks to the end a new section titled **Performance Notes** as well as a discussion of a special case that `areal` handles, which is when geometry collections are returned by `sf::st_intersection()`. The process for handling this special case is more resource intensive and results in longer processing times.

* The distinction between extensive and intensive variables is handled nicely. One case that might also be considered is the choice between interpolation of an intensive variable directly versus deriving the intensive estimates as a ratio of two extensive variables that have been estimated
    * Mindful of the short length of JOSS manuscripts, we have included a discussion of this in the vignette on areal weighted interpolation in the section entitled **Mixed Interpolations**.

* The weight argument names are a bit confusing.
    * Since the package is already on CRAN, we are reluctant to change the argument. In the paper, however, we have made two clarifications to address this. The first was to explicitly link the names for both weights to their descriptions in the second to last paragraph of the section **The areal R package**. They now read:

    > "...we offer a formula that matches the existing functionality in `sf`, which is based on the total area of the original source feature (specified with `weight = "total"`)."

    > "This uses a sum of the source feature areas remaining after the data are intersected as part of the spatial weight calculation process (specified with `weight = "sum"`)."

    We also have added a section titled **A Quick Comparison with sf** that illustrates the difference between these two approaches, and includes a brief discussion of the selection process between both in the second and third full paragraphs. It includes the following language:

    > "If we expect that our source and target data should overlap completely (but perhaps do not because of data quality issues), the `"sum"` approach will allocate all individuals into target features whereas `"total"`will not, instead allocating only a proportion of individuals relative to the overlap between the source and target features. In the example data provided in the `areal` package, this is the case - the Census tracts do not perfectly map onto the extent of the wards, and so the `"total"` approach is inappropriate."

**Comment by lheagy** [comment]
Many thanks for your thorough response @chris-prener! 

@edzer, @sjsrey would you be willing to take a look through @chris-prener's response? Please check off items in the checklist that have been adequately addressed, and if there are any remaining items that you think should be changed before acceptance, please leave comments here. Thank you both!

**Comment by lheagy** [comment]
Many thanks @chris-prener for your thorough response!

:wave: Hi @edzer, @sjsrey: it looks like most of the items on your checklist are checked-off. Do you have any remaining comments before we proceed with accepting the submission?

**Comment by sjsrey** [comment]
I think the author has responded to the points I raised, and I have no further comments. Looking forward to seeing it published.

**Comment by lheagy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01221/joss.01221/10.21105.joss.01221.pdf)

**Comment by lheagy** [comment]
@whedon check referenced

**Comment by lheagy** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.32614/RJ-2018-009 is OK

MISSING DOIs

- https://doi.org/10.1016/j.compenvurbsys.2005.07.005 may be missing for title: Rapid facilitation of dasymetric-based population interpolation by means of raster pixel maps
- https://doi.org/10.1080/00182494.1973.10112670 may be missing for title: The linkage of data describing overlapping geographical units
- https://doi.org/10.2747/1548-1603.49.5.644 may be missing for title: The development of an areal interpolation ArcGIS extension and a comparative study

INVALID DOIs

- None
```

**Comment by lheagy** [comment]
@chris-prener: I left a few comments for grammar in the paper in slu-openGIS/areal#20, and it looks like there are a few missing doi's in the references. Would you please take a look at these and ping here when you are done? Thanks!

**Comment by lheagy** [comment]
:wave: Hi @chris-prener just checking in - have you had a chance to take a look at the suggestions in slu-openGIS/areal#20?

**Comment by chris-prener** [comment]
hey @lheagy - thanks for your patience! just made all of those suggested changes and added the DOI numbers. I also found an additional DOI that whedon did not, and added the package's DOI as well.

**Comment by lheagy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01221/joss.01221/10.21105.joss.01221.pdf)

**Comment by lheagy** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1559/152304083783914958 is OK
- 10.1016/j.compenvurbsys.2005.07.005 is OK
- 10.1080/00182494.1973.10112670 is OK
- 10.32614/RJ-2018-009 is OK
- 10.5281/zenodo.2603540 is OK
- 10.2747/1548-1603.49.5.644 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lheagy** [comment]
many thanks @chris-prener. Please have another look at the compiled pdf above and double-check that all looks good (nothing jumped out at me). If it is fine, then please create a new release and archive the software on [zenodo](https://zenodo.org/). The title and author list on the zenodo archive should match the paper. Once you have done this, please post the version number and doi here and we can proceed with publishing 🎉

**Comment by chris-prener** [comment]
hi @lheagy - I corrected a few additional typos and added a citation for the `microbenchmark` package. The most recent paper has been pushed to the repo and released. The zendo repository has been updated with a `.zenodo.json` file to make sure it is formatted the way you described above.

**Comment by chris-prener** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01221/joss.01221/10.21105.joss.01221.pdf)

**Comment by chris-prener** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1559/152304083783914958 is OK
- 10.1016/j.compenvurbsys.2005.07.005 is OK
- 10.1080/00182494.1973.10112670 is OK
- 10.32614/RJ-2018-009 is OK
- 10.5281/zenodo.2603540 is OK
- 10.2747/1548-1603.49.5.644 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by chris-prener** [comment]
@lheagy - everything looks good. Is there a way to force the sample `R` code onto the next page so it isn't broken up by the page break?

**Comment by lheagy** [comment]
Thanks @chris-prener. 

@arfon: is there an easy way to keep a code-block together in the paper? (see code split over page 2-3 here: https://github.com/openjournals/joss-papers/blob/joss.01221/joss.01221/10.21105.joss.01221.pdf)

**Comment by arfon** [comment]
> @arfon: is there an easy way to keep a code-block together in the paper? (see code split over page 2-3 here: https://github.com/openjournals/joss-papers/blob/joss.01221/joss.01221/10.21105.joss.01221.pdf)

Perhaps a `\newpage` would help here? I _think_ this works with Pandoc/Markdown.

**Comment by chris-prener** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01221/joss.01221/10.21105.joss.01221.pdf)

**Comment by chris-prener** [comment]
worked perfectly - thanks @arfon!

**Comment by chris-prener** [comment]
@lheagy - just tagged a new released on GitHub/Zenodo.

**Comment by lheagy** [comment]
excellent, thanks @chris-prener! Can you please post the zenodo doi here?

**Comment by chris-prener** [comment]
the zenodo doi for the latest release is `10.5281/zenodo.2667289`; the master doi that always resolves to the latest version is `10.5281/zenodo.2433868`.

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.2667289 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2667289" target="_blank">10.5281/zenodo.2667289</a> is the archive.

**Comment by kyleniemeyer** [comment]
@chris-prener we do want to use the specific DOI for the accepted release, since you could theoretically submit a later JOSS paper for a future version

**Comment by lheagy** [comment]
@whedon set v0.1.4.3 as version

**Comment by whedon** [comment]
OK. v0.1.4.3 is the version.

**Comment by lheagy** [comment]
:wave: @openjournals/joss-eics: this submission is ready to be accepted 🎉

**Comment by chris-prener** [comment]
thanks for the update @lheagy!

**Comment by chris-prener** [comment]
and thanks for the clarity @kyleniemeyer

**Comment by chris-prener** [comment]
@lheagy - any updates on when the acceptance process will be complete? Thanks!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01221/joss.01221/10.21105.joss.01221.pdf)

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1559/152304083783914958 is OK
- 10.1016/j.compenvurbsys.2005.07.005 is OK
- 10.1080/00182494.1973.10112670 is OK
- 10.32614/RJ-2018-009 is OK
- 10.5281/zenodo.2603540 is OK
- 10.2747/1548-1603.49.5.644 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@chris-prener some minor edits for the paper:
- could you add full affiliation details (i.e., location) for the authors?
- the first paragraph ends in a comma

**Comment by chris-prener** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01221/joss.01221/10.21105.joss.01221.pdf)

**Comment by chris-prener** [comment]
@kyleniemeyer and @lheagy - made the two changes Kyle requested, and tagged a new released with the updated paper manuscript. The Zenodo DOI for the newest release is - 10.5281/zenodo.2857598

**Comment by kyleniemeyer** [comment]
@chris-prener sorry, looks like Zenodo is having some database issues right now, so I'm going to hold off moving forward until we can confirm the archive. Should be resolved within the day, I hope.

**Comment by chris-prener** [comment]
@kyleniemeyer and @lheagy - looks like everything is back up on the Zenodo end. the DOI is resolving correctly and Zenodo has the correct version of the updated software.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1559/152304083783914958 is OK
- 10.1016/j.compenvurbsys.2005.07.005 is OK
- 10.1080/00182494.1973.10112670 is OK
- 10.32614/RJ-2018-009 is OK
- 10.5281/zenodo.2603540 is OK
- 10.2747/1548-1603.49.5.644 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/704

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/704, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
Posted to the Twitters: https://twitter.com/JOSS_TheOJ/status/1130248728525385728

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/705
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01221](https://doi.org/10.21105/joss.01221)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@sjsrey, @edzer - many thanks for your reviews here and to @lheagy for editing this submission ✨ 

@chris-prener - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01221/status.svg)](https://doi.org/10.21105/joss.01221)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01221">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01221/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01221/status.svg
   :target: https://doi.org/10.21105/joss.01221
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01221/status.svg)](https://doi.org/10.21105/joss.01221)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by chris-prener** [comment]
@lheagy or @arfon - one follow-up question - does Google Scholar index JOSS publications right now? Googled around but didn't seem to find a clear answer...

**Comment by arfon** [comment]
> @lheagy or @arfon - one follow-up question - does Google Scholar index JOSS publications right now? Googled around but didn't seem to find a clear answer...

Yes, but based on historical performance, it can take a month or two for them to show up.

**Comment by chris-prener** [comment]
Thanks @arfon!
