### ISSUE TITLE
[PRE REVIEW]: A Julia package for bilevel optimization problems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1222]
**Submitting author:** @matbesancon (<a href="http://orcid.org/0000-0002-6284-3033">Mathieu Besançon</a>)
**Repository:** <a href="https://github.com/matbesancon/BilevelOptimization.jl" target ="_blank">https://github.com/matbesancon/BilevelOptimization.jl</a>
**Version:** v0.1.0
**Editor:** @poulson
**Reviewers:** @HaoZeke, @vissarion

**Author instructions**

Thanks for submitting your paper to JOSS @matbesancon. The JOSS editor @poulson, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@matbesancon if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @poulson it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@poulson) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1222 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     62      0 --:--:-- --:--:-- --:--:--    62
Error producing PDF.
! Extra }, or forgotten $.
l.398 ...x_i - By_i) = 0 \forall i \in \{1..m_l\}}

Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
👋 @poulson - note that you were proposed by the authors as the editor

**Comment by danielskatz** [comment]
@matbesancon
It looks like there's an extra } in paper.md in the line:
```\lambda_i \cdot (b_i - Ax_i - By_i) = 0 \forall i \in \{1..m_l\}}.$$```

After you fix it, you can try recompiling by typing ```@whedon generate pdf``` as a new comment in this issue.

**Comment by matbesancon** [comment]
thanks @danielskatz

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01222/joss.01222/10.21105.joss.01222.pdf)

**Comment by danielskatz** [comment]
note that the URL for Dempe seems to have some spaces that should be removed as well

**Comment by danielskatz** [comment]
👋 @VivianePons - Are you able to edit this submission?

**Comment by danielskatz** [comment]
Sorrry @VivianePons - please ignore my previous comment, this is already set to be edited by @poulson

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01222/joss.01222/10.21105.joss.01222.pdf)

**Comment by matbesancon** [comment]
reviewers suggestions:
```
stsievert
andim
ChrisRackauckas
jakobbossek
sarats
sjvrijn
chkoar
vissarion
malmaud
HaoZeke
taqtiqa-mark
```
(those who seem to be comfortable with optimization and/or Julia packages)
I didn't tag them all because it seemed excessive, I'll let the editors see what seems appropriate

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01222/joss.01222/10.21105.joss.01222.pdf)

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01222/joss.01222/10.21105.joss.01222.pdf)

**Comment by matbesancon** [comment]
sorry for stressing the bot, multiline equations are a bit of a bother

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01222/joss.01222/10.21105.joss.01222.pdf)

**Comment by matbesancon** [comment]
ok it's even worse, if someone has a tip for that I'd be glad

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by matbesancon** [comment]
ok now special characters don't appear, this is really not ideal. My kingdom for `\begin{align}`

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01222/joss.01222/10.21105.joss.01222.pdf)

**Comment by poulson** [comment]
@danielskatz I am happy to edit this paper! Still getting used to finding the notifications for this!

**Comment by poulson** [comment]
@stsievert Would you be willing to review this paper?

**Comment by poulson** [comment]
@jakobbossek Would you be willing to review this paper?

**Comment by stsievert** [comment]
@poulson I don't think so – I have my plate full with other tasks. Sorry.

**Comment by jakobbossek** [comment]
@stsievert Sorry, covered with many other task. Moreover, I am not familiar with the Julia language.

**Comment by poulson** [comment]
@andim Would you be willing to review this paper?

**Comment by poulson** [comment]
@ChrisRackauckas would you be willing to review this paper?

**Comment by ChrisRackauckas** [comment]
Sorry, I'm booked. If it comes late March and no one has picked it up then ping me again.

**Comment by poulson** [comment]
@sarats do you have time to help review this paper?

**Comment by sarats** [comment]
Leaving on travel shortly. I can get to this at the end of the month if that's okay.

**Comment by poulson** [comment]
Thank you for your extreme patience on this, @matbesancon. We need to get two or three reviewers to accept before the review can start.

@sjvrijn: Sander, would you be willing to spend your time reviewing this paper?
@chkoar: Christos, your profile says you are busy, but please let me know if you have the interest and capacity to review this paper.
@vissarion: Vissarion, please let me know if you have the time and interest to help review this paper.
@malmaud: Jon, please let me know if you are able to spend the time to review this paper.
@HaoZeke: Rohit, thank you for your recent review, so I hate to overload you (especially given your profile says you are out sick), but please let me know if you would be able and willing to serve as a review on this paper as well.
@taqtiqa-mark: Mark, please let me know if you would be willing and able to serve as a reviewer on this paper.

Title: A Julia package for bilevel optimization problems.
Summary: This package is a Julia toolbox based on JuMP.jl for solving bilevel optimization problems. These are encountered in various applications, including power grids, security games, market equilibria or chemical reaction optimization.
Topic: Mathematical Optimization
Article Proof: https://github.com/matbesancon/BilevelOptimization.jl
Submitting Author: Mathieu Besancon @matbesancon

**Comment by poulson** [comment]
@sarats Thank you for the offer, Sarat, and please let me know if now is sufficiently late in the month for you to come back to reviewing this paper. It would be much appreciated!

**Comment by malmaud** [comment]
Sorry Jack, I don't have time to take on this review at the moment.

**Comment by poulson** [comment]
@malmaud Thank you for the fast response, Jon!

**Comment by chkoar** [comment]
@poulson Jack I am really sorry but I won't be able to act as a reviewer  this time

**Comment by poulson** [comment]
@chkoar Thank you for letting me know, Christos!

**Comment by vissarion** [comment]
@poulson I could help with the review although I have no experience with `Julia`. Is there a deadline?

**Comment by HaoZeke** [comment]
@poulson you're welcome, I am much better now, thanks, I would be willing and able to review this package. Julia is one of my favourite languages and optimization problems are also right up my alley.

**Comment by sjvrijn** [comment]
@poulson I'm busy at the moment, but would be available in two weeks if needed

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01222/joss.01222/10.21105.joss.01222.pdf)

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01222/joss.01222/10.21105.joss.01222.pdf)

**Comment by poulson** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by poulson** [comment]
@vissarion Thank you for agreeing to help review this, Vissarion. I think that, given @HaoZeke's Julia expertise, between the two of you, the expertise should be covered. As for a deadline, the soft deadline is typically two weeks.

@HaoZeke I'm glad to hear that you're feeling better, and thank you for your enthusiasm in agreeing to review this paper!

@sjvrijn Hi Sander, it seems that we have this paper covered now, but thank you for the offer to serve as a backup!

@whedon add @HaoZeke as reviewer
@whedon add @vissarion as reviewer

**Comment by poulson** [comment]
@whedon add @HaoZeke as reviewer

**Comment by whedon** [comment]
OK, @HaoZeke is now a reviewer

**Comment by poulson** [comment]
@whedon add @vissarion as reviewer

**Comment by whedon** [comment]
OK, @vissarion is now a reviewer

**Comment by poulson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1278. Feel free to close this issue now!
