### ISSUE TITLE
[REVIEW]: DmpBbo: A versatile Python/C++ library for Function Approximation, Dynamical Movement Primitives, and Black-Box Optimization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1225]
**Submitting author:** @graiola (<a href="http://orcid.org/0000-0003-1481-1106">Gennaro Raiola</a>)
**Repository:** <a href="https://github.com/stulp/dmpbbo" target ="_blank">https://github.com/stulp/dmpbbo</a>
**Version:** 1.0.0
**Editor:** @danielskatz
**Reviewer:** @studywolf, @jenskober
**Archive:** <a href="https://doi.org/10.5281/zenodo.2669652" target="_blank">10.5281/zenodo.2669652</a>

## Status

[![status](http://joss.theoj.org/papers/49a8abac3e6207a0bc1b4127cfbce6e5/status.svg)](http://joss.theoj.org/papers/49a8abac3e6207a0bc1b4127cfbce6e5)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/49a8abac3e6207a0bc1b4127cfbce6e5"><img src="http://joss.theoj.org/papers/49a8abac3e6207a0bc1b4127cfbce6e5/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/49a8abac3e6207a0bc1b4127cfbce6e5/status.svg)](http://joss.theoj.org/papers/49a8abac3e6207a0bc1b4127cfbce6e5)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/stulp/dmpbbo" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@studywolf & @jenskober, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/stulp/dmpbbo">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.0.0
- [x] **Authorship:** Has the submitting author (@graiola) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/stulp/dmpbbo">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.0.0
- [x] **Authorship:** Has the submitting author (@graiola) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @studywolf, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01225/joss.01225/10.21105.joss.01225.pdf)

**Comment by danielskatz** [comment]
👋 @studywolf & @jenskober - thanks for agreeing to review.

I'll note here that we expect a couple of weeks delay until this gets started.

When you are ready to start, please see the comment above - your job is basically to review the paper and software according to your checklists, checking off items as they are deemed ok, and making either short comments or more detailed comments in the code repository as you find problems that need to be addressed by the author.

**Comment by danielskatz** [comment]
👋 @studywolf & @jenskober - Please go ahead and start this review when you are able to do so

**Comment by studywolf** [comment]
I'm still a couple weeks from being able to start reviewing.

**Comment by danielskatz** [comment]
@jenskober - How are you doing with your review?

**Comment by jenskober** [comment]
I got started a little bit, but am now busy with conference deadlines till this weekend

**Comment by danielskatz** [comment]
Hi - I'm going to be on vacation for 2 1/2 weeks, so I'm shifting the editor of this submission to be @arfon, during that period - thanks @arfon

**Comment by danielskatz** [comment]
@whedon assign @arfon as editor

**Comment by studywolf** [comment]
regarding the authorship checkbox, Gennaro Raiola has contributed about 1k vs 120k lines of code from Freek Stulp according to the commit history. I'm not sure exactly what the requirements for 'major contribution' are, but the authorship on the paper reflects Freek Stulp as primary author so I'm checking this box as complete.

**Comment by studywolf** [comment]
didn't see what versions are python are supported. leaving Installation unchecked until stulp/dmpbbo#28 resolved

**Comment by graiola** [comment]
@studywolf, the issue stulp/dmpbbo#28 should be fixed now.

**Comment by jenskober** [comment]
@graiola 
missing DOIs in paper
https://doi.org/10.1109/ROBOT.2002.1014739
https://doi.org/10.1109/IROS.2012.6385818

**Comment by jenskober** [comment]
and a few little issues with the demos and tests
stulp/dmpbbo#31

**Comment by graiola** [comment]
@jenskober I fixed the missing DOIs, thanks.

**Comment by jenskober** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01225/joss.01225/10.21105.joss.01225.pdf)

**Comment by stulp** [comment]
> and a few little issues with the demos and tests
> [stulp/dmpbbo#31](https://github.com/stulp/dmpbbo/issues/31)

I've taken the liberty of splitting your issue [stulp/dmpbbo#31](https://github.com/stulp/dmpbbo/issues/31) into smaller ones 32-40, so that we can assign & conquer. As the other ones are now open, I've closed [stulp/dmpbbo#31](https://github.com/stulp/dmpbbo/issues/31).

**Comment by stulp** [comment]
Here is a small update. Based on the feedback from the reviewers, following larger modifications have been made (apart from smaller bugfixes). These modifications are related to the demos and tests in the C++ version, not the core library.

- The executables and Python wrappers were in different directories which was confusing. They are now installed in the demos/ directory so that they are together.

- Demos are now documented in README.md files in the subdirectories of the demos/ directory. Again, this is to have everything in one place, and allow users to understand and run demos without calling doxygen (doxygen documentation is now only for the API of the libraries in the src/ directory)  

- When running the demos, the data is no longer stored in /tmp, but in the demos/ directory itself. This ensures that everything is in one place, makes it more transparent that data is being written, and allows the user to have a look at the generated data on the spot.

- Tests in dmpbbo are not unit test but programs used for development. They are no longer installed in bin_test to avoid confusion about this.

- INSTALL.txt has been rewritten and improved into INSTALL.md

**Comment by jenskober** [comment]
@stulp Thanks for all the updates, looks great now from my side.

@graiola One last thing about the paper itself: if you check the article proof above, on the second page in applications you have "(Stulp,2012,Stulp et al. (2013),stulp14simultaneous,Stulp & Sigaud (2015))" "stulp14simultaneous" is missing in the references, the first one "Stulp,2012" looks strange as well, and a few spaces after the commas (also first page "(A. J. Ijspeert, Nakanishi, & Schaal, 2002,A. Ijspeert, Nakanishi, Pastor, Hoffmann, & Schaal (2013))") would be nice...

**Comment by graiola** [comment]
Thanks @jenskober , I will look into it now.

**Comment by graiola** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1225 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:58:in `block in build_affiliation_string': Problem with affiliations for Freek Stulp, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:57:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:57:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:109:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:109:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:106:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:106:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by graiola** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01225/joss.01225/10.21105.joss.01225.pdf)

**Comment by jenskober** [comment]
@arfon @studywolf I'm done with my review.

**Comment by arfon** [comment]
> @arfon @studywolf I'm done with my review.

Great! It looks like there's a number of checkboxes that aren't ticked - could you please take another look at them and tick what you can given you review?

**Comment by jenskober** [comment]
Hmm, as far as I can see all mine are checked. @studywolf still has some that are not checked.

**Comment by arfon** [comment]
> Hmm, as far as I can see all mine are checked. @studywolf still has some that are not checked.

You're right. Apologies. @studywolf - how are you getting along with your review?

**Comment by studywolf** [comment]
Sorry about the delay, I didn't get these notification reminders for some reason. Things have been hectic! I will try to finish the review tonight / tomorrow though.

**Comment by studywolf** [comment]
a few issues submitted to the repo as i was going through the examples. I haven't fully confirmed the functionality or look at the functionality documentation. 

There are no unit tests for checking off the 'automated tests' box, I see it was mentioned above but didn't see it specifically addressed. What's the resolution on this?

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by danielskatz** [comment]
thanks for the help while I was out @arfon

**Comment by danielskatz** [comment]
> There are no unit tests for checking off the 'automated tests' box, I see it was mentioned above but didn't see it specifically addressed. What's the resolution on this?

The test do not need need to be automated, but there do need to be some tests.  If there are tests, please check it off.  If there are no tests at all, some need to be added

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by studywolf** [comment]
Check it off if there are any tests at all? Or are we looking for some amount of functionality coverage?

**Comment by danielskatz** [comment]
I would say minimal functionality tests - something that verifies the basic functionality

**Comment by danielskatz** [comment]
👋 @studywolf - How is the review going?  What's currently blocking you?

**Comment by studywolf** [comment]
Was able to check off a few more, mostly available time is blocking me. I had one remaining issue on the repo (and just raised another), should I not be waiting for them to be resolved before checking off the corresponding box?

**Comment by studywolf** [comment]
@danielskatz i've completed the review, and with the contributing documentation added it looks good aside from the documentation for one part of the code. This is currently an open issue on the github, so deferring to you on this. If you think it's fine to not have this resolved before approving then :+1:

**Comment by danielskatz** [comment]
Let's go ahead at this point.

**Comment by danielskatz** [comment]
👋 @graiola - what is the current version number?

And please make sure there is an archive of the current version, and let me know the DOI for it as well.

**Comment by danielskatz** [comment]
Thanks very much, @studywolf and @jenskober for your reviews!

**Comment by stulp** [comment]
It would be nice if I could close issue 44 (which was opened by @studywolf) before assigning the next version number. That is the version I would like the DOI to be assigned with.

Fixing 44 is quite a bit of work (involving an overhaul of the serialization functions), but I should be done within a week or so. Would it be possible to wait with the acceptance until I have fixed it?

**Comment by danielskatz** [comment]
If it's that close to done, then yes, let's wait.  My suggestion to go ahead was based on an assumption it would take longer.

**Comment by danielskatz** [comment]
When you make the new version, please make the changes clear so one of us can quickly review them as well.

**Comment by danielskatz** [comment]
👋 @stulp - just checking on your progress...

**Comment by stulp** [comment]
@danielskatz - I've just merged the branches in which I was addressing the remaining issues.

My main change has been to completely rewrite the code in demos/dmp_bbo_robot (and renaming it to demo_robot/). The directory https://github.com/stulp/dmpbbo/blob/master/demo_robot has been the result of that, and the programs/scripts/README in that directory have not been reviewed yet. I think this should fix the remaining issue #44 raised by @studywolf 

Along the way, I made several other fixes:
* Fixing boost:serialization issues.
* Fixed all doxygen warnings (by documenting all functions and adding namespaces)
* Nicer plotting here and there (to make nice plots for demo_robot/)
These fixes/tweaks, I would say, do not require a review.

I will make a new release with a new version number and an archive tomorrow.

**Comment by danielskatz** [comment]
👋 @studywolf - I know you thought you were done, but I would greatly appreciate your confirmation that the submission, with these changes, is still acceptable (and ideally has improved).

**Comment by stulp** [comment]
The new release is here: https://github.com/stulp/dmpbbo/releases/tag/v1.0.0

Archives of the repository are downloadable at the end of that release.

**Comment by studywolf** [comment]
I should be able to look into this on Sunday :+1:

**Comment by studywolf** [comment]
i will have comments / gone through the code by wednesday night

**Comment by danielskatz** [comment]
@studywolf - Assuming you meant Wednesday 2 days ago, I'm just checking... :)

**Comment by studywolf** [comment]
Hello! Yes you are correct, sorry about that. I've run through the demo_robot files and just made a typo correction issue in the README. This all LGTM :+1:

**Comment by danielskatz** [comment]
Thanks! We can’t quite accept yet due to some system issues, but we can start the process

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by danielskatz** [comment]
Ok. I jumped the gun. 

@stulp - please deposit the current version in an archival repository, eg zenodo, figshare, etc and let me know the DOI. And let me know the version number that goes with the archived software.

**Comment by graiola** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01225/joss.01225/10.21105.joss.01225.pdf)

**Comment by graiola** [comment]
@danielskatz this is the DOI 10.5281/zenodo.2669652
The version is v1.0.0

Thanks!

**Comment by danielskatz** [comment]
whedon set 1.0.0 as version

**Comment by danielskatz** [comment]
@whedon set 1.0.0 as version

**Comment by whedon** [comment]
OK. 1.0.0 is the version.

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.2669652 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2669652" target="_blank">10.5281/zenodo.2669652</a> is the archive.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1177/0278364911402527 is OK
- https://doi.org/10.1162/neco_a_00393 is OK
- https://doi.org/10.1109/ROBOT.2002.1014739 is OK
- https://doi.org/10.1109/tro.2011.2163863 is OK
- https://doi.org/10.1016/j.neunet.2011.02.004 is OK
- https://doi.org/10.1109/IROS.2012.6385818 is OK
- 10.1109/IROS.2014.6942741 is OK
- 10.1109/HUMANOIDS.2013.7030008 is OK
- https://doi.org/10.1016/j.neunet.2015.05.005 is OK
- https://doi.org/10.2478/pjbr-2013-0003 is OK

MISSING DOIs

- https://doi.org/10.1109/iros.2011.6095096 may be missing for title: Learning force control policies for compliant manipulation

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1225 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    468      0 --:--:-- --:--:-- --:--:--   483
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.01225.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
👋 @graiola - I no longer see the paper.md and paper.bib files in the repo - what am I missing?

**Comment by arfon** [comment]
@danielskatz - they're still there (e.g. `https://github.com/stulp/dmpbbo/blob/master/docs/paper/paper.md`). Whedon just sometimes fails to clone the repositories properly (a long-standing bug).

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/664

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/664, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1177/0278364911402527 is OK
- https://doi.org/10.1162/neco_a_00393 is OK
- https://doi.org/10.1109/ROBOT.2002.1014739 is OK
- https://doi.org/10.1109/tro.2011.2163863 is OK
- https://doi.org/10.1016/j.neunet.2011.02.004 is OK
- https://doi.org/10.1109/IROS.2012.6385818 is OK
- 10.1109/IROS.2014.6942741 is OK
- 10.1109/HUMANOIDS.2013.7030008 is OK
- https://doi.org/10.1016/j.neunet.2015.05.005 is OK
- https://doi.org/10.2478/pjbr-2013-0003 is OK

MISSING DOIs

- https://doi.org/10.1109/iros.2011.6095096 may be missing for title: Learning force control policies for compliant manipulation

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@graiola - Some of the references have some issues - please see https://github.com/stulp/dmpbbo/pull/49

**Comment by graiola** [comment]
PR merged!

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1177/0278364911402527 is OK
- 10.1162/neco_a_00393 is OK
- 10.1109/ROBOT.2002.1014739 is OK
- 10.1109/tro.2011.2163863 is OK
- 10.1016/j.neunet.2011.02.004 is OK
- 10.1109/IROS.2012.6385818 is OK
- 10.1109/IROS.2014.6942741 is OK
- 10.1109/HUMANOIDS.2013.7030008 is OK
- 10.1016/j.neunet.2015.05.005 is OK
- 10.2478/pjbr-2013-0003 is OK

MISSING DOIs

- https://doi.org/10.1109/iros.2011.6095096 may be missing for title: Learning force control policies for compliant manipulation

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/666

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/666, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/667
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01225](https://doi.org/10.21105/joss.01225)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
now we wait for the DOI to work, then I'll complete the process

**Comment by danielskatz** [comment]
Also, thanks very much to @studywolf & @jenskober for the reviewing work!

**Comment by arfon** [comment]
> now we wait for the DOI to work, then I'll complete the process

@danielskatz - the DOI is now resolving.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01225/status.svg)](https://doi.org/10.21105/joss.01225)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01225">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01225/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01225/status.svg
   :target: https://doi.org/10.21105/joss.01225
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01225/status.svg)](https://doi.org/10.21105/joss.01225)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by graiola** [comment]
Thanks @arfon and @danielskatz, and thanks to our reviewers @studywolf and @jenskober

**Comment by stulp** [comment]
Thank you @studywolf and @jenskober for your thorough reviews, and thank you @arfon and @danielskatz for supervising the review process. I think the reviewing process has certainly contributed to improving the code, especially in terms of documentation, and making the code easier to navigate for newcomers. So thanks again for the time and effort you have all invested.

**Comment by jenskober** [comment]
Yes, it felt more like helping to improve the code rather than typical academic reviews. I really enjoyed the process, especially as @graiola and @stulp were extremely quick to react and went beyond what we were suggesting.
