### ISSUE TITLE
[PRE REVIEW]: A Hyperbolic "Crystal Ball"

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1226]
**Submitting author:** @benjaminwilson (<a href="http://orcid.org/0000-0002-3708-0361">Benjamin Wilson</a>)
**Repository:** <a href="https://github.com/lateral/crystal-ball" target ="_blank">https://github.com/lateral/crystal-ball</a>
**Version:** v1.0.1
**Editor:** @poulson
**Reviewers:** @HaoZeke

**Author instructions**

Thanks for submitting your paper to JOSS @benjaminwilson. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@benjaminwilson if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01226/joss.01226/10.21105.joss.01226.pdf)

**Comment by arfon** [comment]
:wave: @benjaminwilson thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](http://joss.theoj.org/about#submission_requirements). In particular, this item:

> - Your software should have an obvious research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)? The section [_'what should my paper contain'_](http://joss.theoj.org/about#paper_structure) has some guidance for the sort of content we're looking to be present in the `paper.md`.

Many thanks!

**Comment by benjaminwilson** [comment]
Hi @arfon pleased to meet you.  The submission is in the category of "supports the functioning of research instruments or the execution of research experiments" (from the guidelines), rather than being research itself.  The core purpose is the inspection of hyperbolic embeddings resulting from machine learning pipelines, such as those cited in `paper.md` (the Leimeiser & Wilson paper is our own work).  I've tried to clarify this in the `paper.md`.

**Comment by benjaminwilson** [comment]
Looking at the list of reviewers, I found the following which may be good candidates:

+ HaoZeke - geometry and JavaScript
+ Danbo3004 - ML and JavaScript
+ neurons - ML and JavaScript
+ zfrenchee - ML and JavaScript

**Comment by poulson** [comment]
Exploring large point clouds of embeddings is a standard step in research pipelines (especially if the embeddings can have a string associated with them). If this tool can visualize large amounts of points (e.g., at least thousands) in this manner, I can vouch that I would have used it in my last research job.

**Comment by benjaminwilson** [comment]
Thanks @poulson . Indeed, the situation is compounded by the negative curvature of hyperbolic space, for which visualisations in the Euclidean plane, regardless of how they are derived (t-SNE, PCA, etc.) drastically distort the distances.

I could perhaps add some functionality for using custom labels - I'll add that to the list.

In terms of scale, I can report that I've tested in with 1.2k nodes and as many edges (the mammals graph from Nickel & Kiela, 2017).

**Comment by poulson** [comment]
@whedon assign @poulson as editor

**Comment by whedon** [comment]
OK, the editor is @poulson

**Comment by poulson** [comment]
@HaoZeke would you be willing to review this paper?

**Comment by poulson** [comment]
@Danbo3004 would you be willing to review this paper?

**Comment by HaoZeke** [comment]
@poulson I am a little backed up with another review but I would be glad to look this over next week if it is still relevant..

**Comment by poulson** [comment]
Thank you for the quick comments @HaoZeke. I will wait to hear back from @Danbo3004 and, if they don't get back, I think by next week would be fine. It seems like you've already done some legwork.

**Comment by HaoZeke** [comment]
@poulson, I have completed my pending review, so I am free to look this over now.

**Comment by poulson** [comment]
@whedon assign @haozeke as the reviewer

**Comment by poulson** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by poulson** [comment]
@whedon assign @HaoZeke as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @HaoZeke

**Comment by poulson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1240. Feel free to close this issue now!
