### ISSUE TITLE
[PRE REVIEW]: pyuvsim: a comprehensive simulation package for radio interferometers in python.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1227]
**Submitting author:** @aelanman (<a href="http://orcid.org/0000-0003-2116-3573">Adam Lanman</a>)
**Repository:** <a href="https://github.com/RadioAstronomySoftwareGroup/pyuvsim/" target ="_blank">https://github.com/RadioAstronomySoftwareGroup/pyuvsim/</a>
**Version:** v0.2.1
**Editor:** @arfon
**Reviewers:** @ygrange

**Author instructions**

Thanks for submitting your paper to JOSS @aelanman. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@aelanman if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1227 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    200      0 --:--:-- --:--:-- --:--:--   202
Error reading bibliography ./paper.bib (line 91, column 3):
unexpected "u"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by aelanman** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by aelanman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01227/joss.01227/10.21105.joss.01227.pdf)

**Comment by danielskatz** [comment]
👋 @arfon - are you able to edit this?

**Comment by ygrange** [comment]
That's a remarkably on-topic tool actually! I'll do it.

**Comment by arfon** [comment]
@whedon assign @ygrange as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ygrange

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1234. Feel free to close this issue now!

**Comment by arfon** [comment]
@ygrange please head over to #1234 for the actual review.
