### ISSUE TITLE
[PRE REVIEW]: data.adapt.multi.test: Data-Adaptive Statistics for High-Dimensional Testing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#123]
**Submitting author:** @wilsoncai1992 (<a href="http://orcid.org/0000-0003-2680-3066">Weixin Cai</a>)
**Repository:** <a href="https://github.com/wilsoncai1992/data.adapt.multi.test" target ="_blank">https://github.com/wilsoncai1992/data.adapt.multi.test</a>
**Version:** 0.2.0
**Editor:** @karthik
**Reviewer:** @gavinsimpson

**What this issue is for**

Thanks for submitting your paper to JOSS @wilsoncai1992. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@karthik - would you be able to edit this submission for JOSS?

**Comment by karthik** [comment]
@arfon I've pinged a few reviewers and will update as soon as I have someone lined up.

**Comment by karthik** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by karthik** [comment]
@whedon assign @gavinsimpson as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @gavinsimpson

**Comment by arfon** [comment]
@whedon start-review magic-word=bananas

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/161. Feel free to close this issue now!
