### ISSUE TITLE
[PRE REVIEW]: pycoQC, interactive quality control for Oxford Nanopore Sequencing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1232]
**Submitting author:** @a-slide (<a href="http://orcid.org/0000-0001-8772-6776">Adrien Leger</a>)
**Repository:** <a href="https://github.com/a-slide/pycoQC" target ="_blank">https://github.com/a-slide/pycoQC</a>
**Version:** v2.2.0
**Editor:** @pjotrp
**Reviewers:** @george-githinji

**Author instructions**

Thanks for submitting your paper to JOSS @a-slide. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@a-slide if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1232 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
@arfon whedon is having trouble finding the paper, though at https://github.com/a-slide/pycoQC I see it at `paper/paper.md`.

@brainstorm @mgymrek @pjotrp @yochannah do one of you have the bandwidth to edit this submission? It looks bioinformatics-y to my untrained eyes... :)

**Comment by a-slide** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by pjotrp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01232/joss.01232/10.21105.joss.01232.pdf)

**Comment by pjotrp** [comment]
Great contribution @a-slide! I'll look for a reviewer.

**Comment by a-slide** [comment]
Hi @pjotrp,
I would suggest @trallard 
Alternatively, I would said @luizirber or @serine
Thanks

**Comment by pjotrp** [comment]
@whedon assign @george-githinji as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @george-githinji

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1236. Feel free to close this issue now!
