### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by sjsrey** [openjournals/joss-reviews#1233]
Moving this to an issue to remove subsequent discussion outside review thread

@chris-prener when installing via 
```
> install.packages("areal")
```
 I'm getting:
```
ERROR: dependencies ‘lwgeom’, ‘sf’ are not available for package ‘areal’
  * removing ‘/home/serge/anaconda3/lib/R/library/areal’

The downloaded source packages are in
        ‘/tmp/RtmpBEpBpJ/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages("areal") :
  installation of package ‘units’ had non-zero exit status
2: In install.packages("areal") :
  installation of package ‘sf’ had non-zero exit status
3: In install.packages("areal") :
  installation of package ‘lwgeom’ had non-zero exit status
4: In install.packages("areal") :
  installation of package ‘areal’ had non-zero exit status
> library(areal)
Error in library(areal) : there is no package called ‘areal’
>
```

I realize this might be due to using R installed via conda. But on Ubuntu 18.04 I'm getting the same error(s) on a clean install of R from the official repositories:
```
* DONE (dplyr)
ERROR: dependencies ‘lwgeom’, ‘sf’ are not available for package ‘areal’
* removing ‘/home/serge/R/x86_64-pc-linux-gnu-library/3.4/areal’

The downloaded source packages are in
        ‘/tmp/Rtmpb2kPO5/downloaded_packages’
Warning messages:
1: In install.packages("areal") :
  installation of package ‘units’ had non-zero exit status
2: In install.packages("areal") :
  installation of package ‘sf’ had non-zero exit status
3: In install.packages("areal") :
  installation of package ‘lwgeom’ had non-zero exit status
4: In install.packages("areal") :
  installation of package ‘areal’ had non-zero exit status
> library(areal)
Error in library(areal) : there is no package called ‘areal’
```

_Originally posted by @sjsrey in https://github.com/openjournals/joss-reviews/issues/1221#issuecomment-460396285_

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1233 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
Hi @sjsrey, can you please move this to the issues for the [joss repo](https://github.com/openjournals/joss)? This repo is only for reviewing submissions to the journal.

**Comment by kyleniemeyer** [comment]
@sjsrey oh, I just noticed this issue is actually for the software associated with a submission, and that you opened it here: https://github.com/slu-openGIS/areal/issues/17
