### ISSUE TITLE
[PRE REVIEW]: AtlasReader: A Python package to generate coordinate tables, region labels, and informative figures from statistical MRI images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1235]
**Submitting author:** @miykael (<a href="http://orcid.org/0000-0002-5866-047X">Michael Philipp Notter</a>)
**Repository:** <a href="https://github.com/miykael/atlasreader" target ="_blank">https://github.com/miykael/atlasreader</a>
**Version:** v0.0.3
**Editor:** @cMadan
**Reviewers:** @andrewheusser

**Author instructions**

Thanks for submitting your paper to JOSS @miykael. The JOSS editor @arokem, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@miykael if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01235/joss.01235/10.21105.joss.01235.pdf)

**Comment by miykael** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01235/joss.01235/10.21105.joss.01235.pdf)

**Comment by danielskatz** [comment]
👋 @arokem - Note that this submission requested you as editor

**Comment by miykael** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01235/joss.01235/10.21105.joss.01235.pdf)

**Comment by arokem** [comment]
Hey @cMadan : would you mind taking this one? 

There are a couple of reasons: 

1. I am swamped with other reviews right now. 
2. My grant is acknowledged in the paper, so though I am not strictly speaking a collaborator on this work, there may at least be the appearance of a conflict of interest.

**Comment by arokem** [comment]
Just to be clear, @cMadan : could you be the *editor* for this submission?

**Comment by cMadan** [comment]
@arokem, sure I can be the editor for this one.

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@andrewheusser, would you be available/interested in reviewing this submission?

**Comment by andrewheusser** [comment]
I think so, what's the timeline?

**Comment by cMadan** [comment]
@andrewheusser, sooner is good, but it's also flexible. In all likelihood, you'll have some comments that will take the authors time to work on for a week or two, and then will need to look again and see if sufficiently revised. That back-and-forth can go on for just a week or two, or sometimes is more intermittent over a few months, it all depends how responsive both the authors and reviewer are.

**Comment by andrewheusser** [comment]
Sounds good - I'll start it Tuesday morning and hopefully have it done within a few days after that.  Is there a guide/checklist I should follow?

**Comment by miykael** [comment]
Hi @andrewheusser - thank you for reviewing this. And thank you for starting it so quickly. I will respond to your review and comments as quickly as possible.

@cMadan might know of some additional guide/checklist, but I think the main one from JOSS is here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by cMadan** [comment]
@andrewheusser, great! I'll start the actual review process then

**Comment by cMadan** [comment]
@whedon assign @andrewheusser as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @andrewheusser

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1257. Feel free to close this issue now!
