### ISSUE TITLE
[REVIEW]: pycoQC, interactive quality control for Oxford Nanopore Sequencing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1236]
**Submitting author:** @a-slide (<a href="http://orcid.org/0000-0001-8772-6776">Adrien Leger</a>)
**Repository:** <a href="https://github.com/a-slide/pycoQC" target ="_blank">https://github.com/a-slide/pycoQC</a>
**Version:** v2.2.0
**Editor:** @pjotrp
**Reviewer:** @george-githinji
**Archive:** <a href="https://doi.org/10.5281/zenodo.2578275" target="_blank">10.5281/zenodo.2578275</a>

## Status

[![status](http://joss.theoj.org/papers/ea8e08dc950622bdd5d16a65649954aa/status.svg)](http://joss.theoj.org/papers/ea8e08dc950622bdd5d16a65649954aa)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/ea8e08dc950622bdd5d16a65649954aa"><img src="http://joss.theoj.org/papers/ea8e08dc950622bdd5d16a65649954aa/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/ea8e08dc950622bdd5d16a65649954aa/status.svg)](http://joss.theoj.org/papers/ea8e08dc950622bdd5d16a65649954aa)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/a-slide/pycoQC" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@george-githinji, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @pjotrp know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/a-slide/pycoQC">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2.2.0)?
- [x] **Authorship:** Has the submitting author (@a-slide) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @george-githinji it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by pjotrp** [comment]
Dear @a-slide, we are starting review in this issue tracker. To expedite the review process do you mind going through above list of check boxes and make sure they can be ticked (you can't tick them). Also check the PDF output carefully. Ping us here when you are done.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01236/joss.01236/10.21105.joss.01236.pdf)

**Comment by a-slide** [comment]
Hi @pjotrp and @george-githinji,

I confirm that I can tick all the boxes, except **automated tests**. Indeed, there is no straightforward way to do it as the outputs of pycoQC methods are dynamic plots. One possibility is to inspect visually the outputs and compare it with other software which I have done. Reports generated from the same datasets with pycoQC, Nanoplot and MinIONQC are available online at https://www.ebi.ac.uk/~aleg/data/pycoQC_test/comparison/. Although the 3 programs have different implementation, the results are similar for all 3 summary files tested. If this is an acceptable solution to you, I am happy to upload the datasets on Zenodo to get a DOI.

In addition, I made a dew minor changes in pycoQC and updated the software version to 2.2.1.

Thanks

**Comment by pjotrp** [comment]
Thanks. I am fine with not having automated tests for visualisations. One improvement is to create regresssion tests (where you just compare the outputs). But I think that is for more complex systems. 

@george-githinji you can start review.

**Comment by a-slide** [comment]
Hi @george-githinji
Let me know if there is anything I can do to help or if you need any extra test files.
Thanks

**Comment by george-githinji** [comment]
I am currently going through the package and the the paper submission. Should get back to you in 2 days. Thanks!

**Comment by george-githinji** [comment]
The authors provide a tool for summarizing nanopore sequence data based on the sequence summary file generated by the base callers. They make use of third-party tools to provide summary statistics and plots. The tool is well documented and provides clear and standard methods for installation under open source license. They compare the tool with similar functionality and make argument for extra features. It would be great if the tool provided raw summary data used in each visualization/plot to the users so as to  allow alternative visualization methods or environments.  The dynamic plots would be great for real-time analysis during a nanopore run and might want to consider such a feature in the future. I would recommend publication to JOSS.

**Comment by pjotrp** [comment]
Thank you @george-githinji!

**Comment by pjotrp** [comment]
@a-slide The review process is now complete. To finalize your submission and accept your paper in JOSS, we need two things. First, can you confirm that all references in your bibliography have a DOI in the bibliography (if one exists).

Second, we need you to deposit a copy of your software repository (including any revisions made during the JOSS review process) with a data-archiving service.

To do so:

1. Create [a GitHub release](https://help.github.com/articles/creating-releases/) of the current version of your software repository
2. Deposit that release with [Zenodo](https://zenodo.org/), [figshare](https://figshare.com/), or a similar DOI issuer.
3. Post a comment here with the DOI for the release.

     * Get a new proof with the @whedon generate pdf command.
     * Download the proof, check all references have DOIs, follow the
       links and check the references.
     * Give the paper a proof-read and ask authors to fix typos.
     * Ask the author to make a Zenodo archive, and report the DOI in the
       Review thread.
     * Check the Zenodo deposit has the correct metadata (title and author
       list), and request the author edit it if it doesnt match the
       paper.
     * Run @whedon set <doi> as archive.
     * Run @wedon set <v1.x.x> as version if the version was updated.
     * Add the accepted label.

**Comment by arfon** [comment]
> @a-slide The review process is now complete. To finalize your submission and accept your paper in JOSS, we need two things. First, can you confirm that all references in your bibliography have a DOI in the bibliography (if one exists).

`@whedon` can help with this by typing `@whedon check references`

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1186/s13059-016-1103-0 is OK
- http://doi.org/10.1038/nbt.3423 is OK
- http://doi.org/10.1093/bioinformatics/bty654 is OK
- http://doi.org/10.1093/bioinformatics/bty149 is OK
- http://doi.org/10.1038/nmeth.4577 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by pjotrp** [comment]
@arfon very cool :)

**Comment by pjotrp** [comment]
@a-slide next step is for you to confirm.

**Comment by a-slide** [comment]
Dear all,

Sorry for the late reply and many thanks for accepting our paper.

@george-githinji, We would like to thank you for your time and for the fair review. 
Regarding your remark on raw data, although it is not documented all the pycoQC functions actually returns the plots in JSON format. If you don't plot it with plotly iplot function the raw data can easily be extracted from the object returned.

@arfon and @pjotrp we published a new version of pycoQC on the master branch with minor changes related to the documentation ([see relevant pull request](https://github.com/a-slide/pycoQC/commit/bedf3e308864140d15816e77d1767e58a02eaf12) ). The last version number is **[2.2.2](https://github.com/a-slide/pycoQC/tree/v2.2.2)** with DOI **[10.5281/zenodo.2578275](https://zenodo.org/record/2578275)**. The pre-compiled version hosted on pypi was also updated.
As for references, some don't have a DOI as I cited several unpublished tools or github repositories. 
 
We hope this answers your questions and look forward for the final version of the paper.

Best

**Comment by pjotrp** [comment]
@whedon set  10.5281/zenodo.2578275 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2578275" target="_blank">10.5281/zenodo.2578275</a> is the archive.

**Comment by pjotrp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01236/joss.01236/10.21105.joss.01236.pdf)

**Comment by pjotrp** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1186/s13059-016-1103-0 is OK
- http://doi.org/10.1038/nbt.3423 is OK
- http://doi.org/10.1093/bioinformatics/bty654 is OK
- http://doi.org/10.1093/bioinformatics/bty149 is OK
- http://doi.org/10.1038/nmeth.4577 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/533

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/533, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by pjotrp** [comment]
@arfon we are ready to R&R

**Comment by danielskatz** [comment]
Hi @pjotrp - the new practices, now that we have AEiCs and Arfon doesn't have to do this all himself, is to notify @openjournals/joss-eics when a paper is ready to go.  That's me this week, and I'll go ahead and do this now.

**Comment by pjotrp** [comment]
Alright. Hard to get rid of old habits...

**Comment by danielskatz** [comment]
@a-slide - Can I ask for some small updates to the paper?  All related to cases...  I've suggested them via https://github.com/a-slide/pycoQC/pull/55

**Comment by a-slide** [comment]
Hi @danielskatz,
Sure thanks. Should I also update the package version number ?

**Comment by danielskatz** [comment]
I don't think it's needed for such a small text-only change in the paper

**Comment by tleonardi** [comment]
I've also added a pull request for a problem with the @ in my affiliation

**Comment by a-slide** [comment]
I think I merged everything to master

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/534

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/534, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1186/s13059-016-1103-0 is OK
- http://doi.org/10.1038/nbt.3423 is OK
- http://doi.org/10.1093/bioinformatics/bty654 is OK
- http://doi.org/10.1093/bioinformatics/bty149 is OK
- http://doi.org/10.1038/nmeth.4577 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/535
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01236](https://doi.org/10.21105/joss.01236)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks:
@a-slide for submitting
@george-githinji for reviewing
@pjotrp for editing

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01236/status.svg)](https://doi.org/10.21105/joss.01236)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01236">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01236/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01236/status.svg
   :target: https://doi.org/10.21105/joss.01236
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01236/status.svg)](https://doi.org/10.21105/joss.01236)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by a-slide** [comment]
Thanks everyone !
JOSS is awesome

**Comment by danielskatz** [comment]
We are aware there is a problem with the paper on the JOSS site - hopefully to be resolved soon.

**Comment by arfon** [comment]
> We are aware there is a problem with the paper on the JOSS site - hopefully to be resolved soon.

Things are now fixed.
