### ISSUE TITLE
[PRE REVIEW]: Ocellaris: an exactly incompressible DG FEM solver for free surface flows

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1238]
**Submitting author:** @TormodLandet (<a href="http://orcid.org/0000-0001-5070-8056">Tormod Landet</a>)
**Repository:** <a href="https://bitbucket.org/ocellarisproject/ocellaris" target ="_blank">https://bitbucket.org/ocellarisproject/ocellaris</a>
**Version:** 2019.0.1
**Editor:** @labarba
**Reviewers:** @inducer, @piyueh

**Author instructions**

Thanks for submitting your paper to JOSS @TormodLandet. The JOSS editor @labarba, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@TormodLandet if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@labarba) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01238/joss.01238/10.21105.joss.01238.pdf)

**Comment by danielskatz** [comment]
👋 @labarba - the author requested you edit this submission

**Comment by labarba** [comment]
I would like to invite Andreas Klöckner (@inducer) to review this — Andreas: would you be willing to contribute a review for JOSS? Title: **Ocellaris: an exactly incompressible DG FEM solver for free surface flows** (uses Python, C++, Fenics and PETSc).
Have a look at the [JOSS Review Process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html), and let me know!

**Comment by labarba** [comment]
(Now sent invitation to Andreas via email.)

**Comment by inducer** [comment]
@labarba I would in principle be willing to review. An important data point for me would be the time horizon you have in mind. The guidelines say, "rapid", but that can mean many things. Could you clarify? To be more precise, it's early-semester-and-pre-CSE crunch time in my group, so "early March" is easier to accommodate than "next week".

**Comment by labarba** [comment]
I see — we certainly don't expect reviewers to deliver in a week (although some JOSS papers do get reviews and published in a matter of days), but our target is around three weeks. More common is >1 month. Would you be able to get to it right after SIAM CSE? Obviously you are ideal for this one!

**Comment by inducer** [comment]
Right after CSE is doable. Count me in.

**Comment by labarba** [comment]
@whedon assign @inducer as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @inducer

**Comment by labarba** [comment]
@whedon add @piyueh as reviewer

**Comment by whedon** [comment]
OK, @piyueh is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1239. Feel free to close this issue now!
