### ISSUE TITLE
[REVIEW]: A Hyperbolic "Crystal Ball"

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1240]
**Submitting author:** @benjaminwilson (<a href="http://orcid.org/0000-0002-3708-0361">Benjamin Wilson</a>)
**Repository:** <a href="https://github.com/lateral/crystal-ball" target ="_blank">https://github.com/lateral/crystal-ball</a>
**Version:** v1.0.1
**Editor:** @poulson
**Reviewer:** @HaoZeke
**Archive:** <a href="https://doi.org/10.5281/zenodo.2573958" target="_blank">10.5281/zenodo.2573958</a>

## Status

[![status](http://joss.theoj.org/papers/033b265ce2f8562dc1148b534a09275c/status.svg)](http://joss.theoj.org/papers/033b265ce2f8562dc1148b534a09275c)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/033b265ce2f8562dc1148b534a09275c"><img src="http://joss.theoj.org/papers/033b265ce2f8562dc1148b534a09275c/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/033b265ce2f8562dc1148b534a09275c/status.svg)](http://joss.theoj.org/papers/033b265ce2f8562dc1148b534a09275c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/lateral/crystal-ball" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@HaoZeke, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @poulson know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lateral/crystal-ball">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.1
- [x] **Authorship:** Has the submitting author (@benjaminwilson) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @HaoZeke it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01240/joss.01240/10.21105.joss.01240.pdf)

**Comment by benjaminwilson** [comment]
@HaoZeke thanks for your initial feedback over on the [other issue](https://github.com/openjournals/joss-reviews/issues/1226#issuecomment-460364318).  I'll address that today!

**Comment by benjaminwilson** [comment]
Hi @HaoZeke , I've added a section that gives a high-level view of the algorithms for computing the updates to the point configurations to `paper.md`, and added a small note about the performance to `README.md`. 

I think this addresses the bulk of your points from previously - but not all of them - I'm afraid I'll have to leave those until Monday.

Thanks already for the comments to date!

**Comment by HaoZeke** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01240/joss.01240/10.21105.joss.01240.pdf)

**Comment by HaoZeke** [comment]
@benjaminwilson, thank you for the extensions, I will check when your additions are completed. In general, for the review process I will be opening issues on the project tracker, or where the solution is unambiguous, I shall be opening pull requests. Again, this is just the general outline, in this case I don't see much scope for either. Good work!

**Comment by HaoZeke** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.2172/1209543 may be missing for title: Neural Embeddings of Graphs in Hyperbolic Space
- https://doi.org/10.2172/963444 may be missing for title: Hyperbolic Neural Networks

INVALID DOIs

- None
```

**Comment by benjaminwilson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01240/joss.01240/10.21105.joss.01240.pdf)

**Comment by benjaminwilson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1039/c5cc90276b may be missing for title: Neural Embeddings of Graphs in Hyperbolic Space
- https://doi.org/10.1016/0893-6080(88)90120-7 may be missing for title: Hyperbolic Neural Networks

INVALID DOIs

- None
```

**Comment by benjaminwilson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by benjaminwilson** [comment]
@HaoZeke thanks for your patience!  I think I've now addressed all issues raised in the pre-review.

**Comment by HaoZeke** [comment]
Excellent work, I believe this is ready for submission now. @poulson

**Comment by poulson** [comment]
@benjaminwilson It seems that the DOIs were removed rather than fixed. Would you mind making sure that each of the references has a DOI?

**Comment by benjaminwilson** [comment]
Hi @poulson, I've indeed removed some entries from the `.bib` file that I wasn't using.  For all but one of the remainder, I am afraid that I am really stumped on getting DOIs for any of them.  I was surprised that I couldn't find either on the paper itself or in published BibTeX or on crossref.org.  I don't know if this is because they are all either arXiv (1) or conference proceedings (rest).  Do you know of somewhere else I can look?

**Comment by poulson** [comment]
@benjaminwilson Hi Benjamin, I am still relatively new to `whedon`'s `check references`, but you might try mirroring the DOI formatting of a recently completed review, such as https://github.com/sivaramambikasaran/HODLR/blob/master/docs/paper/paper.bib.

The DOI links are surrounded by curly braces and only contain the latter part of the address. Could you try this approach to see if the DOI's are picked up?

**Comment by benjaminwilson** [comment]
Hi! The problem is rather that I can't find the DOIs for those articles anywhere.

**Comment by benjaminwilson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.4414/saez.2013.01498 may be missing for title: Skip-gram word embeddings in hyperbolic space

INVALID DOIs

- None
```

**Comment by benjaminwilson** [comment]
whedon sure does come up with some crazy suggestions for what the missing DOI might be!

**Comment by poulson** [comment]
whedon generate pdf

**Comment by poulson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01240/joss.01240/10.21105.joss.01240.pdf)

**Comment by poulson** [comment]
Thanks @benjaminwilson; I proofread and everything looks great. Would you mind creating a Zenodo archive and reporting the DOI here?

**Comment by benjaminwilson** [comment]
Hi @poulson , I think I've got that done now: DOI: 10.5281/zenodo.2573958

**Comment by poulson** [comment]
@whedon set 10.5281/zenodo.2573958 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2573958" target="_blank">10.5281/zenodo.2573958</a> is the archive.

**Comment by poulson** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by poulson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01240/joss.01240/10.21105.joss.01240.pdf)

**Comment by poulson** [comment]
@benjaminwilson Thank you for your contribution!

@HaoZeke Thank you for providing your time and expertise for this review!

@arfon This paper should be ready for submission; I am forwarding it over to you (please excuse me, I think there is a rotating editorial board but am not sure who that lands on right now).

**Comment by benjaminwilson** [comment]
Thanks very much both @poulson and @HaoZeke for your comments and your patience!

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.4414/saez.2013.01498 may be missing for title: Skip-gram word embeddings in hyperbolic space

INVALID DOIs

- None
```

**Comment by arfon** [comment]
> @arfon This paper should be ready for submission; I am forwarding it over to you (please excuse me, I think there is a rotating editorial board but am not sure who that lands on right now).

@poulson - yep it's me this week. In the future you can ping @openjournals/joss-eics to get the editor on rotation.

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/512
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01240](https://doi.org/10.21105/joss.01240)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@HaoZeke - many thanks for your review here and to @poulson for editing this submission ✨ 

@benjaminwilson - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01240/status.svg)](https://doi.org/10.21105/joss.01240)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01240">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01240/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01240/status.svg
   :target: https://doi.org/10.21105/joss.01240
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01240/status.svg)](https://doi.org/10.21105/joss.01240)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by arfon** [comment]
P.S. Congratulations to @poulson for editing his first JOSS paper ⚡️
