### ISSUE TITLE
[PRE REVIEW]: Optimising Light Source Positioning for Even and Flux-Efficient Illumination 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1241]
**Submitting author:** @adrena-lab (<a href="http://orcid.org/0000-0002-4413-5527">Stefan  Guldin</a>)
**Repository:** <a href="https://github.com/adrena-lab/Optimising-Light-Source-Positioning" target ="_blank">https://github.com/adrena-lab/Optimising-Light-Source-Positioning</a>
**Version:** 1.0
**Editor:** @trallard
**Reviewers:** @cmccomb, @nicoguaro

**Author instructions**

Thanks for submitting your paper to JOSS @adrena-lab. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@adrena-lab if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1241 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1241 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/bin/whedon:47:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-dc9ad3c41cc6/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1241 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@adrena-lab - please rename your paper to `paper.md`. In addition, I don't see a bibtex file in this repository.

**Comment by arfon** [comment]
I've emailed the submitting author directly to point out that we're waiting on them at this point.

**Comment by danielskatz** [comment]
I'm going to mark this as paused at this point - @adrena-lab please ping us when we are ready to resume the process.

**Comment by adrena-lab** [comment]
Dear Arfon and Daniel,

My apologies, there was a misunderstanding on our end.  We have renamed out paper to paper.md and have added paper.bib to the repository.  We will follow this thread to ensure there are no further delays.

Thank you,

Niamh

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1241 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    109      0 --:--:-- --:--:-- --:--:--   108
Could not find bibliography file: LED_paper.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
As you probably can tell, there are some other files missing, such as a .bib file and a figure.  Feel free to add files, and when you have done so, enter a comment here that is ```@whedon generate pdf``` to try the PDF compilation process again.  Let me know when you are done or stuck.

**Comment by adrena-lab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01241/joss.01241/10.21105.joss.01241.pdf)

**Comment by danielskatz** [comment]
It would be good to explain the research application of this software - what kinds of researchers will use this software, and for what types of research?

**Comment by danielskatz** [comment]
Similarly, the README will need some work - it should talk about the research application(s) of the software, plus a bit more.  See https://joss.readthedocs.io/en/latest/review_criteria.html under "Documentation" and "A statement of need".

**Comment by adrena-lab** [comment]
Thank you Daniel,  I will make these changes

**Comment by danielskatz** [comment]
Thanks - once you do, we can move to finding an editor

**Comment by adrena-lab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01241/joss.01241/10.21105.joss.01241.pdf)

**Comment by adrena-lab** [comment]
Dear Daniel,

I have adjusted the paper to include the research applications and target audience and provided significant modifications to the ReadMe file.  I hope this is sufficient.

Thank you,

Niamh

**Comment by danielskatz** [comment]
thanks - this looks nice to me.

**Comment by danielskatz** [comment]
👋 @trallard - would you be willing to edit this submission?

**Comment by trallard** [comment]
Hi @danielskatz 👋 I would be happy to take this up on

**Comment by danielskatz** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by trallard** [comment]
Hi @adrena-lab I will be the editor do you have any reviewers in mind? You can also check the list fo reviewers [here](https://bit.ly/joss-reviewers)

**Comment by adrena-lab** [comment]
Dear trallard,

After looking through the list of reviewers, I think aquilesC and cmccomb would be most suited.  

Please let me know if you would like me to provide further suggestions.

Thank you!

Niamh

**Comment by trallard** [comment]
Hey, @adrena-lab  let's find a couple more options in case some folks can not take the submission. Ideally, we'd want 2 reviewers. Let me know if you cannot find any more suitable reviewers on out list.

**Comment by adrena-lab** [comment]
Dear @trallard ,

I think that Kevin-Mattheus-Moerman, nicoguaro, JoshKarpel, martlj, or PhilipVinc could also be suitable reviewers. 

Thank you,

Niamh

**Comment by adrena-lab** [comment]
Hi @trallard ,

would you have any update on our manuscript draft? Looking forward to hearing from you. 

Thanks, 
Stefan

**Comment by trallard** [comment]
hi @adrena-lab  sorry for the long wait, I am now back and in full swing so let's get things moving

Dear potential reviewers (@aquilesC @cmccomb @nicoguaro @martlj @PhilipVinc),

It seems that you all have valuable expertise to review this submission, so I was wondering if you had the time and bandwidth to take upon as reviewers?

**Title**: open_iA: Optimising light source positioning for even and flux-efficient illumination

**Summary**: Visual analysis and processing of volumetric datasets, with a focus on industrial computed tomography


Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01139/joss.01139/10.21105.joss.01139.pdf

Submitting author: @adrena-lab 

Repository: [https://github.com/adrena-lab/Optimising-Light-Source-Positioning](https://github.com/adrena-lab/Optimising-Light-Source-Positioning)

Version: 1.0

**Comment by nicoguaro** [comment]
@trallard, I think I can review it but it will take me a little bit longer than usual.

@adrena-lab, the software seems to be written in MATLAB. Is it mandatory, or can it run in Octave? If it cannot run in Octave, which version of MATLAB is needed?

**Comment by martlj** [comment]
@trallard, I am away from the office until 29th April, but if that's not too long I'd be happy to review it as soon as possible after then.

**Comment by cmccomb** [comment]
@trallard I should be able to make time for the review in the next few weeks!

**Comment by adrena-lab** [comment]
Dear All, 

I believe the link to the article proof above is incorrect (from a different contribution, not authored by us). Should be this one: 

https://github.com/openjournals/joss-papers/blob/joss.01241/joss.01241/10.21105.joss.01241.pdf

Thanks, 
Stefan

**Comment by trallard** [comment]
I might have changed the url when writing the comment fixed now @adrena-lab also can you please let us know if this can be run in Octave as per @nicoguaro question?

Thanks a lot @cmccomb I will add you as a reviewer straight away!

@martlj not a problem we can start the review with Chris and get yours in when you are back

**Comment by trallard** [comment]
@whedon add @cmccomb as reviewer

**Comment by whedon** [comment]
OK, @cmccomb is now a reviewer

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01241/joss.01241/10.21105.joss.01241.pdf)

**Comment by adrena-lab** [comment]
Article proof looks fine.

**Comment by adrena-lab** [comment]
@nicoguaro The software was written and tested using Matlab 2018a. It may indeed run using Octave as the code does not rely upon Matlab proprietary toolboxes, however this hasn't been tested by us.

**Comment by nicoguaro** [comment]
@trallard, I will take it then.

**Comment by trallard** [comment]
@whedon add @nicoguaro as reviewer

**Comment by whedon** [comment]
OK, @nicoguaro is now a reviewer

**Comment by trallard** [comment]
Great we now have two reviewers so I am going to move forward with the process 🎊

**Comment by trallard** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1392. Feel free to close this issue now!
