### ISSUE TITLE
[PRE REVIEW]: Rclean: A Tool for Writing Cleaner, More Transparent Code

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1242]
**Submitting author:** @MKLau (<a href="http://orcid.org/0000-0003-3758-2406">Matthew Lau</a>)
**Repository:** <a href="https://github.com/provtools/rclean" target ="_blank">https://github.com/provtools/rclean</a>
**Version:** v1.0.1
**Editor:** @labarba
**Reviewers:** @cboettig, @benmarwick

**Author instructions**

Thanks for submitting your paper to JOSS @MKLau. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@MKLau if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1242 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@MKLau - please rename your paper to `paper.md`. In addition, I don't see any software associated with this submission - the paper should be contained _within_ the software repository that we review.

**Comment by MKLau** [comment]
Ah OK, thanks. I didn’t fully understand that from the submission example. I thought that the reference to the software was contained in the paper.

Thanks, will do ASAP,

Matt


On Feb 8, 2019, at 8:19 AM, Arfon Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


@MKLau<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MKLau&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=yYM9bdhQa7fj0pqtCBPxMvjOe6gKXC-k_OhnGcaB0ZI&m=t8h8F793uLUMsXpW5DQhaefLm0jJUzRX6zrUvesyJ4o&s=qNc7-eI_CYx_Uj_Qz7LB95GCm6wwUFk_7bCHmycfE0U&e=> - please rename your paper to paper.md. In addition, I don't see any software associated with this submission - the paper should be contained within the software repository that we review.

**Comment by MKLau** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by MKLau** [comment]
@arfon OK, now in github.com/provtools/rclean/joss (master branch). I don't see a way to update the repo URL though. How should I proceed?

**Comment by arfon** [comment]
> @arfon OK, now in github.com/provtools/rclean/joss (master branch). I don't see a way to update the repo URL though. How should I proceed?

I've updated the address manually.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1242 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    257      0 --:--:-- --:--:-- --:--:--   262
Could not find bibliography file: rclean.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@MKLau - it looks like your `paper.md` file is referencing a bibtex file that doesn't exist.

**Comment by MKLau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1242 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    196      0 --:--:-- --:--:-- --:--:--   197
Could not find bibliography file: rclean.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by MKLau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01242/joss.01242/10.21105.joss.01242.pdf)

**Comment by MKLau** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1038/542139a is OK
- http://doi.org/10.1126/science.1213847 is OK
- http://doi.org/10.1038/532306a is OK
- http://doi.org/10.1038/sdata.2016.18 is OK
- http://doi.org/10.1073/pnas.1708290115 is OK
- http://doi.org/10.1016/j.ecoinf.2007.07.006 is OK
- http://doi.org/10.1021/acs.jpclett.5b00285 is OK
- http://doi.org/10.1038/s41567-018-0342-2 is OK
- http://doi.org/10.1109/MCSE.2018.042781334 is OK
- http://doi.org/10.1016/j.ecoinf.2015.06.010 is OK
- http://doi.org/10.1145/2602649.2602651 is OK
- http://doi.org/10.1016/j.ecoinf.2007.07.006 is OK
- http://doi.org/10.1038/530027a is OK
- http://doi.org/10.1038/535355b is OK
- http://doi.org/10.7717/peerj.175 is OK
- http://doi.org/10.1038/541269a is OK
- http://doi.org/10.1186/s12864-016-2466-z is OK
- http://doi.org/10.1002/fee.1222 is OK
- http://doi.org/10.1016/j.tree.2016.07.002 is OK
- http://doi.org/10.1038/sdata.2017.114 is OK
- http://doi.org/10.1371/journal.pcbi.1004140 is OK
- http://doi.org/10.1111/j.1740-9713.2015.00827.x is OK

MISSING DOIs

- https://doi.org/10.1890/09-0032.1 may be missing for title: Repeatability and transparency in ecological research
- https://doi.org/10.1126/science.aad7048 may be missing for title: INSIGHTS PERSPECTIVES
- https://doi.org/10.1890/11-0009.1 may be missing for title: Modeling range dynamics in heterogeneous landscapes: invasion of the hemlock woolly adelgid in eastern North America
- https://doi.org/10.1038/533452a may be missing for title: 1,500 scientists lift the lid on reproducibility
- https://doi.org/10.1029/96jd00557 may be missing for title: Seasonal variation of the ozone production efficiency per unit NOx at Harvard Forest, Massachusetts

INVALID DOIs

- None
```

**Comment by MKLau** [comment]
@whedon generate pdf
@whedon check references

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01242/joss.01242/10.21105.joss.01242.pdf)

**Comment by MKLau** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1145/2602649.2602651 is OK
- http://doi.org/10.1038/533452a is OK
- http://doi.org/10.1126/science.1213847 is OK
- http://doi.org/10.1038/s41567-018-0342-2 is OK
- http://doi.org/10.1371/journal.pcbi.1004140 is OK
- http://doi.org/10.1109/MCSE.2018.042781334 is OK
- http://doi.org/10.1073/pnas.1708290115 is OK
- http://doi.org/10.1038/sdata.2017.114 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by MKLau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01242/joss.01242/10.21105.joss.01242.pdf)

**Comment by MKLau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01242/joss.01242/10.21105.joss.01242.pdf)

**Comment by MKLau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01242/joss.01242/10.21105.joss.01242.pdf)

**Comment by MKLau** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@Kevin-Mattheus-Moerman
@VivianePons
@arfon
@arokem
@brainstorm
@cMadan
@danielskatz
@eramirem
@gkthiruvathukal
@jasonclark
@jedbrown
@karthik
@katyhuff
@kthyng
@kyleniemeyer
@labarba
@lheagy
@mgymrek
@pjotrp
@poulson
@trallard
@yochannah
```

**Comment by MKLau** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by MKLau** [comment]
@arfon Hi Afron, OK just finished proofing and fixing some citation issues. Looks good to go now.

**Comment by arfon** [comment]
> @arfon Hi Afron, OK just finished proofing and fixing some citation issues. Looks good to go now.

Got it. Thanks.

**Comment by labarba** [comment]
@whedon set @labarba as editor

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@cboettig — Would you be willing to contribute a review for JOSS on this submission? The software (Rclean) is one of the tools used for code curation in the workflow manager `encapsulator`, which you reviewed for _CiSE_ last year (same group of authors). Your expertise would be ideal here!

**Comment by cboettig** [comment]
@labarba Sure thing

**Comment by labarba** [comment]
Thanks, @cboettig ! I will look for a second reviewer, and get this started.

**Comment by labarba** [comment]
👋  @benmarwick — Would you be willing to contribute a review for this JOSS submission? I have a feeling it's right up your alley: **Rclean: A Tool for Writing Cleaner, More Transparent Code**

**Comment by benmarwick** [comment]
Yes, I can do this. Sorry that I missed your mention here from so long ago!

**Comment by benmarwick** [comment]
Has there been any discussion about whether this pkg might be suitable for @ropensci [onboarding](https://github.com/ropensci/software-review)? Perhaps @noamross or @maelle could advise if this pkg is suitable? It it passes that, then it's auto-submitted here, if I understand correctly.

**Comment by labarba** [comment]
@whedon assign @cboettig as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @cboettig

**Comment by labarba** [comment]
@whedon add @benmarwick as reviewer

**Comment by whedon** [comment]
OK, @benmarwick is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1312. Feel free to close this issue now!
