### ISSUE TITLE
[PRE REVIEW]: iced: fast and memory efficient normalization of contact maps

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1243]
**Submitting author:** @NelleV (<a href="http://orcid.org/0000-0002-8748-6546">Nelle varoquaux</a>)
**Repository:** <a href="https://github.com/hiclib/joss_paper" target ="_blank">https://github.com/hiclib/joss_paper</a>
**Version:** v0.5.1
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @NelleV. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@NelleV if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1243 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    373      0 --:--:-- --:--:-- --:--:--   372
Could not find bibliography file: paper.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by arfon** [comment]
@NelleV - I don't see any software associated with this submission - the paper should be contained _within_ the software repository that we review.

**Comment by NelleV** [comment]
@arfon I had not understood this from the documentation. Should I reopen a submission?

(also ping @stefanv as I believe he's about to do the same thing)

**Comment by NelleV** [comment]
Also, does the paper have to be in the root of the repository?

**Comment by stefanv** [comment]
Ah, that's a bit awkward; are we expected to host a `paper.md` file in perpetuity at the root of our software repository?

**Comment by arfon** [comment]
@stefanv - no, you can remove it after the submission is accepted. Also, it can be anywhere in the repository.

**Comment by arfon** [comment]
> @arfon I had not understood this from the documentation. Should I reopen a submission?

Yes, it might be easier to resubmit. Let me know if this is what you'd like to do.

**Comment by stefanv** [comment]
Thanks for clarifying, @arfon!  Elsewhere in the package works great, we could host it inside our docs, e.g..

**Comment by NelleV** [comment]
Let's close this submission, and I'll resubmit from the main package. Is this just a matter of closing the PR?
