### ISSUE TITLE
[PRE REVIEW]: SkyPortal: An Astronomical Data Platform

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1245]
**Submitting author:** @stefanv (<a href="http://orcid.org/0000-0001-9276-1891">Stéfan van der Walt</a>)
**Repository:** <a href="https://github.com/skyportal/skyportal" target ="_blank">https://github.com/skyportal/skyportal</a>
**Version:** 1.0
**Editor:** @arfon
**Reviewers:** @gnarayan

**Author instructions**

Thanks for submitting your paper to JOSS @stefanv. The JOSS editor @arfon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@stefanv if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@arfon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01245/joss.01245/10.21105.joss.01245.pdf)

**Comment by arfon** [comment]
:wave: @gnarayan would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by stefanv** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01245/joss.01245/10.21105.joss.01245.pdf)

**Comment by stefanv** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01245/joss.01245/10.21105.joss.01245.pdf)

**Comment by gnarayan** [comment]
@arfon - sure. It's quite short so should finish it on today's flight.

**Comment by arfon** [comment]
@whedon add @gnarayan as reviewer

**Comment by whedon** [comment]
OK, @gnarayan is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1247. Feel free to close this issue now!

**Comment by arfon** [comment]
@gnarayan - please head over to #1247 for the actual review.
