### ISSUE TITLE
[PRE REVIEW]: LGP: A robust Linear Genetic Programming implementation on the JVM using Kotlin.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1246]
**Submitting author:** @JedS6391 (<a href="http://orcid.org/0000-0002-5028-9987">Jed Simson</a>)
**Repository:** <a href="https://github.com/JedS6391/LGP" target ="_blank">https://github.com/JedS6391/LGP</a>
**Version:** 4.2
**Editor:** @gkthiruvathukal
**Reviewers:** @homonecloco

**Author instructions**

Thanks for submitting your paper to JOSS @JedS6391. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@JedS6391 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01246/joss.01246/10.21105.joss.01246.pdf)

**Comment by JedS6391** [comment]
Hi there, just wondering if there's anything I can do to help this pre-review get started?

**Comment by labarba** [comment]
👋  @gkthiruvathukal — This JOSS submission looks like something you could handle as editor, no? I will assign you, but let me know if I can help you in any way!

**Comment by labarba** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
@labarba Yes, I will be happy to handle this submission, being one of the Java people on the board.

**Comment by gkthiruvathukal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by gkthiruvathukal** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
:wave: @gkthiruvathukal - how are you getting along identifying reviewers? @JedS6391 - if you get a chance, identifying a few potential reviewer names from the list (https://bit.ly/joss-reviewers) would help out too.

**Comment by gkthiruvathukal** [comment]
@arfon I'm getting the ball rolling now. Thanks for everyone's patience as I begin my tenure with JOSS.

@JedS6391 Can you let me know if you have any preferred reviewers? We do have reviewers with Kotlin expertise. As I wish to get the review processing moving as soon as possible, if I do not hear any preferences, I will make the assignment within 24-48 hours of this posting.

**Comment by JedS6391** [comment]
Hi @gkthiruvathukal, I don't have any real preference for a reviewer. Maybe paragkulkarni11 or arcuri82 (GitHub is not allowing me to mention them directly) would be interested as it seems they have Kotlin experience?

Otherwise, I trust your judgement to pick a suitable reviewer.

**Comment by gkthiruvathukal** [comment]
@paragkulkarni11 Would you be willing to contribute a review for JOSS on this submission? This submission seems closely related to your areas of expertise and interest.

**Comment by gkthiruvathukal** [comment]
@arcuri82 Would you be willing to contribute a review for JOSS on this submission? This submission seems closely related to your areas of expertise and interest. I have not seen a follow-up communication from @paragkulkarni11 yet. If either or both of you respond, we can begin the review process.

**Comment by gkthiruvathukal** [comment]
@homonecloco Would you be willing to contribute a review to this JOSS submission? I see you have Java and Genetics listed. I realize that genetic programming is not the same thing as genetics, but your expertise would be helpful for this submission.

**Comment by homonecloco** [comment]
Sure, I'll be happy to review this submission. How do I proceed?

**Comment by gkthiruvathukal** [comment]
@homonecloco I will assign you as a reviewer and start the review.

**Comment by gkthiruvathukal** [comment]
@whedon assign @homonecloco

**Comment by gkthiruvathukal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by gkthiruvathukal** [comment]
@whedon assign @homonecloco as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @homonecloco

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1337. Feel free to close this issue now!

**Comment by arcuri82** [comment]
hi. sorry for late reply (very busy week). if you still need a reviewer, I can do it

**Comment by gkthiruvathukal** [comment]
@arcuri82 Thanks for your offer. I have started the review now. I will keep you in mind for a future submission.
