### ISSUE TITLE
[REVIEW]: SkyPortal: An Astronomical Data Platform

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1247]
**Submitting author:** @stefanv (<a href="http://orcid.org/0000-0001-9276-1891">Stéfan van der Walt</a>)
**Repository:** <a href="https://github.com/skyportal/skyportal" target ="_blank">https://github.com/skyportal/skyportal</a>
**Version:** 1.0
**Editor:** @arfon
**Reviewer:** @gnarayan
**Archive:** <a href="https://doi.org/10.5281/zenodo.2742377" target="_blank">10.5281/zenodo.2742377</a>

## Status

[![status](http://joss.theoj.org/papers/28a83ab43ff3ca23cdd831e82877365a/status.svg)](http://joss.theoj.org/papers/28a83ab43ff3ca23cdd831e82877365a)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/28a83ab43ff3ca23cdd831e82877365a"><img src="http://joss.theoj.org/papers/28a83ab43ff3ca23cdd831e82877365a/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/28a83ab43ff3ca23cdd831e82877365a/status.svg)](http://joss.theoj.org/papers/28a83ab43ff3ca23cdd831e82877365a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/skyportal/skyportal" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@gnarayan, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/skyportal/skyportal">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0)?
- [x] **Authorship:** Has the submitting author (@stefanv) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @gnarayan it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01247/joss.01247/10.21105.joss.01247.pdf)

**Comment by arfon** [comment]
@gnarayan - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by stefanv** [comment]
Thank you for reviewing, @gnarayan—much appreciated!

**Comment by arfon** [comment]
:wave: @gnarayan - how are you getting along here?

**Comment by gnarayan** [comment]
Had issues with the installation that it took STScI IT to help resolve, so got stuck at that point on checklist above. That's been worked through, and I've made notes on the draft, so will send something out either late tonight or tomorrow. I will say that I am at Berekely and got to meet with @stefanv and see the system being demoed, and that has been valuable.

**Comment by gnarayan** [comment]
I've included a PDF with the review detailing the major issues to address, together with logfiles with the output from stdout and stderr on running `make test` and from `make monitor` followed by status. 

The issues are not with the paper, or the software itself (which I thank @stefanv for demonstrating live - that always involves some risk). Rather they arise because the default installation does not demonstrate functionality (either because of a bug or because it was never designed to) and the because the current documentation isn't adequate. I hope the authors will address these, as the system as demonstrated looked very promising.

[skyportal.pdf](https://github.com/openjournals/joss-reviews/files/2913507/skyportal.pdf)
[test.log](https://github.com/openjournals/joss-reviews/files/2913509/test.log)
[monitor.log](https://github.com/openjournals/joss-reviews/files/2913510/monitor.log)

**Comment by stefanv** [comment]
Thanks for the review, @gnarayan!  I will address the issues you mentioned and report back here.

**Comment by stefanv** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01247/joss.01247/10.21105.joss.01247.pdf)

**Comment by stefanv** [comment]
@gnarayan @arfon We believe we have now addressed all of the issues identified in the first round of review.  Please see https://github.com/skyportal/skyportal/issues/127.  Specifically, we hope that the improved logging, installation instructions, and working Docker images will aid in evaluating the paper.  Feel free to let us know if there are any other issues we should address.

**Comment by arfon** [comment]
OK thanks @stefanv. @gnarayan - when you get a chance, please take a look at these changes.

**Comment by gnarayan** [comment]
The authors have addressed all my comments more than satisfactorily. They have met all the requirements laid out by JOSS. 

I've found one issue that occurs intermittently:
```
tornado.application - ERROR - Exception in callback (<socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 63500)>, <function wrap.<locals>.null_wrapper at 0x102893048>)
Traceback (most recent call last):
  File "/Users/gnarayan/work/skyportal/skyportal_env/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Users/gnarayan/work/skyportal/skyportal_env/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/gnarayan/work/skyportal/skyportal_env/lib/python3.6/site-packages/tornado/netutil.py", line 264, in accept_handler
    connection, address = sock.accept()
  File "/Users/gnarayan/anaconda3/envs/skyportal/lib/python3.6/socket.py", line 205, in accept
    fd, addr = self._accept()
OSError: [Errno 24] Too many open files
```
Restarting the server seems to address the issue, at least for a time. I think this is best dealt with as a github issue for skyportal, and I will raise it there. This does not count as an impediment for publication - no software is ever just "done." 

My compliments to the authors on this valuable contribution to the time-domain science ecosystem.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01247/joss.01247/10.21105.joss.01247.pdf)

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by arfon** [comment]
@stefanv - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by stefanv** [comment]
@arfon I've tagged v0.9 of the software and published it as http://doi.org/10.5281/zenodo.2742377

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.2742377 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2742377" target="_blank">10.5281/zenodo.2742377</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.25080/Majora-629e541a-004 is OK
- 10.1016/j.ascom.2014.09.001 is OK
- 10.1086/648598 is OK

MISSING DOIs

- https://doi.org/10.1038/s41550-017-0321-z may be missing for title: A recurrent neural network for classification of unevenly sampled variable stars

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/679

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/679, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/680
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01247](https://doi.org/10.21105/joss.01247)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@gnarayan - many thanks for your review here ✨ 

@stefanv - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01247/status.svg)](https://doi.org/10.21105/joss.01247)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01247">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01247/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01247/status.svg
   :target: https://doi.org/10.21105/joss.01247
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01247/status.svg)](https://doi.org/10.21105/joss.01247)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by gnarayan** [comment]
A very different way of doing reviews, and I really love the use of whedon to manage the process. Thanks for asking me to do this, @arfon!

**Comment by arfon** [comment]
> A very different way of doing reviews, and I really love the use of whedon to manage the process. Thanks for asking me to do this, @arfon!

😻 thanks for the kind words @gnarayan and for your review!

**Comment by stefanv** [comment]
@gnarayan Thank you very much for your detailed review; the software & documentation is in a much better state because of it.

@arfon Thank you for handling this submission, and for guiding us through the JOSS review process.
