### ISSUE TITLE
[PRE REVIEW]: iced: fast and memory efficient normalization of contact maps

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1248]
**Submitting author:** @NelleV (<a href="http://orcid.org/0000-0002-8748-6546">Nelle varoquaux</a>)
**Repository:** <a href="https://github.com/hiclib/iced" target ="_blank">https://github.com/hiclib/iced</a>
**Version:** v0.5.1
**Editor:** @pjotrp
**Reviewers:** @robinweide

**Author instructions**

Thanks for submitting your paper to JOSS @NelleV. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@NelleV if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01248/joss.01248/10.21105.joss.01248.pdf)

**Comment by arfon** [comment]
@pjotrp - are you able to identify an editor for this submission?

**Comment by pjotrp** [comment]
On it.

**Comment by NelleV** [comment]
The labels from whedon are not quite accurate: this is primarly a Python library.

**Comment by pjotrp** [comment]
I think they are ticked automatically. Fixed.

**Comment by pjotrp** [comment]
@robinweide can you review or suggest a reviewer? @NelleV do you know anyone in this small field who could review - you can suggest users of your tools who also write software themselves?

**Comment by danielskatz** [comment]
Ping - just noting that this has been sitting for almost 2 weeks now.

**Comment by robinweide** [comment]
> @robinweide can you review or suggest a reviewer? @NelleV do you know anyone in this small field who could review - you can suggest users of your tools who also write software themselves?

I can look at it next week.

**Comment by NelleV** [comment]
Hi. So sorry, I missed the first notification.
Do you need one or two reviewers? I can probably compile a list of people from the Hi-C community, but they might not be python developers.

**Comment by NelleV** [comment]
Actually, Jacob Schrieber would also be a good fit (https://homes.cs.washington.edu/~jmschr/)

**Comment by pjotrp** [comment]
@whedon assign @robinweide as reviewer

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@whedon assign @robinweide as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @robinweide

**Comment by pjotrp** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1286. Feel free to close this issue now!

**Comment by pjotrp** [comment]
We may add a reviewer later.
