### ISSUE TITLE
[REVIEW]: dfitspy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1249]
**Submitting author:** @astrom-tom (<a href="http://orcid.org/0000-0001-8385-3276">Romain Thomas</a>)
**Repository:** <a href="https://github.com/astrom-tom/dfitspy" target ="_blank">https://github.com/astrom-tom/dfitspy</a>
**Version:** v19.3.3
**Editor:** @arfon
**Reviewer:** @taldcroft
**Archive:** <a href="https://doi.org/10.5281/zenodo.2592698" target="_blank">10.5281/zenodo.2592698</a>

## Status

[![status](http://joss.theoj.org/papers/6a3d39d2fcb6c44965e203527f276c8a/status.svg)](http://joss.theoj.org/papers/6a3d39d2fcb6c44965e203527f276c8a)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/6a3d39d2fcb6c44965e203527f276c8a"><img src="http://joss.theoj.org/papers/6a3d39d2fcb6c44965e203527f276c8a/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/6a3d39d2fcb6c44965e203527f276c8a/status.svg)](http://joss.theoj.org/papers/6a3d39d2fcb6c44965e203527f276c8a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/astrom-tom/dfitspy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@taldcroft, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/astrom-tom/dfitspy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v19.3.3
- [x] **Authorship:** Has the submitting author (@astrom-tom) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @taldcroft it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by arfon** [comment]
@taldcroft - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by arfon** [comment]
:wave: @taldcroft - a friendly reminder that you said you thought you'd be able to complete your review by the 12th March :smile:

**Comment by taldcroft** [comment]
Yup, it's on my calendar!

**Comment by taldcroft** [comment]
Minor comments on the article proof:
- `fits` is an acronym and should always be capitalized as `FITS`.
- `usefull` => `useful`.
- `used natively inside a another program` (extra `a`)
- `strenghth` => `strength`
- Not sure of JOSS standards, but I believe `Python` should always be capitalized.
- `Therefore fits file can` => `Therefore FITS files can` (plural `files`)
- There is a space in the URL for the `www.eso.org/...` link.  Note also that this link goes to a page that provides man page links for the original `dfits` and `fitsort` standalone tools, but both those links are broken.  Can you dig up any working links for the `difts` and `fitsort` man pages?

**Comment by taldcroft** [comment]
@arfon @astrom-tom - Review completed.  

I opened a number of issues that I think should be addressed (by fixing or discussion).  These issues  are the source of unchecked boxes in the review checklist.

- https://github.com/astrom-tom/dfitspy/issues/3
- https://github.com/astrom-tom/dfitspy/issues/4
- https://github.com/astrom-tom/dfitspy/issues/5
- https://github.com/astrom-tom/dfitspy/issues/6
- https://github.com/astrom-tom/dfitspy/issues/7
- https://github.com/astrom-tom/dfitspy/issues/8
- https://github.com/astrom-tom/dfitspy/issues/9
- https://github.com/astrom-tom/dfitspy/issues/10
- https://github.com/astrom-tom/dfitspy/issues/11

Overall I see the utility in this package as a standalone package, separate from `astropy` or `fitsio`.  (For astropy there is a GPL / BSD license problem anyway).  When we've ironed the issues I opened then I'll be happy to recommend inclusion to JOSS.  :smile:

**Comment by arfon** [comment]
👍 thanks @taldcroft. Over to you @astrom-tom

**Comment by astrom-tom** [comment]
Thanks you very much @taldcroft! I will be working on a revision in the next few days and get back to you with a revised version!

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
Dear @arfon ,

What is the process to resubmit the code?

Thanks!

**Comment by taldcroft** [comment]
@astrom-tom - still 3 open issues that you should address prior to resubmitting.  None of them are difficult.  :smile:

**Comment by arfon** [comment]
> What is the process to resubmit the code?

Please just let me know here once you've updated your code based on @taldcroft's feedback. There's no need to resubmit - you simply have to update this issue letting us know you've made the changes.

**Comment by astrom-tom** [comment]
@taldcroft, @arfon  The remaining issues have been adresses and the code have been updated and move to the main pypi repository. The new version is 19.3.3.

**Comment by taldcroft** [comment]
All good now, I've reviewed and closed the outstanding issues and have now checked off the remaining review boxes.

From my perspective I'm pleased to recommend to @arfon and the editors that `dfitspy` be accepted to JOSS.  

:tada:

**Comment by arfon** [comment]
@whedon set v19.3.3 as version

**Comment by whedon** [comment]
OK. v19.3.3 is the version.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by arfon** [comment]
Thanks @taldcroft!

@astrom-tom - your paper is currently very short. Do you think it would be possible to add a little more detail for example discussing the need for this software and some examples of usage? https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

**Comment by astrom-tom** [comment]
Thanks so much @taldcroft & @arfon !

@arfon I will try to add some more in the paper today and I will let you know when I think it is ready.

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1249 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    189      0 --:--:-- --:--:-- --:--:--   189
Error producing PDF.
! LaTeX Error: Lonely \item--perhaps a missing list environment.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.325 

Looks like we failed to compile the PDF

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1249 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0    153      0 --:--:-- --:--:-- --:--:--   154
Error producing PDF.
! LaTeX Error: Lonely \item--perhaps a missing list environment.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.325 

Looks like we failed to compile the PDF

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
Dear @arfon 

First of all, sorry for the mess with all the pdf compilations. I reworked on the paper and included more information and gave simple examples.

**Comment by arfon** [comment]
@astrom-tom - I've made a small correction here: https://github.com/astrom-tom/dfitspy/pull/12

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
Thanks @arfon !

**Comment by arfon** [comment]
@astrom-tom - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by astrom-tom** [comment]
Here it is: DOI: 10.5281/zenodo.2592698
One question, can I put dfitspy in ASCL?

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by astrom-tom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01249/joss.01249/10.21105.joss.01249.pdf)

**Comment by arfon** [comment]
> @arfon Here it is: DOI: 10.5281/zenodo.2592698
👍 

@astrom-tom - before I proceed with accepting this paper can you confirm you've finished iterating on the paper? 

> One question, can I put dfitspy in ASCL?

Definitely, although you probably want to make sure you're filling in the 'preferred citation' field to make sure that authors are citing the thing you want to be cited (presumably this paper). See for example Astropy's entry: http://ascl.net/1304.002

**Comment by astrom-tom** [comment]
@arfon Yes, the paper is ok for me and I will not modify it.
As for ASCL I will wait that this paper is ready on ADS.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.2592698 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2592698" target="_blank">10.5281/zenodo.2592698</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1249 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1051/0004-6361:20010923 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/554

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/554, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1051/0004-6361:20010923 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/555
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01249](https://doi.org/10.21105/joss.01249)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@taldcroft - many thanks for your review here ✨ 

@astrom-tom - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01249/status.svg)](https://doi.org/10.21105/joss.01249)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01249">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01249/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01249/status.svg
   :target: https://doi.org/10.21105/joss.01249
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01249/status.svg)](https://doi.org/10.21105/joss.01249)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by astrom-tom** [comment]
Thank you so much for your work @arfon and @taldcroft. It is really awesome! 
(I just signed up for being a reviewer :D ).

@arfon One very last question, when will it be available in ADS? Is there any timeline?

**Comment by arfon** [comment]
> (I just signed up for being a reviewer :D ).

Thanks!

> @arfon One very last question, when will it be available in ADS? Is there any timeline?

I think ADS typically index us every few weeks. It's not immediate.

**Comment by astrom-tom** [comment]
@arfon Thanks a lot!
For the future version, should I resubmit them or can I just cite the paper for the version that was just accepted?

**Comment by arfon** [comment]
> For the future version, should I resubmit them or can I just cite the paper for the version that was just accepted?

Future versions of this package? If there have been major updates then it's possible to resubmit and publish another JOSS paper but this has only happened for a couple of packages in the past and the changes were very large. Basically unless you feel like you need to publish a new paper, I'd encourage people to cite this paper.

**Comment by astrom-tom** [comment]
@arfon Perfect! Thanks again for all this work!
