### ISSUE TITLE
[REVIEW]: resampy: efficient sample rate conversion in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#125]
**Submitting author:** @bmcfee (<a href="http://orcid.org/0000-0001-6261-9747">Brian McFee</a>)
**Repository:** <a href="https://github.com/bmcfee/resampy" target ="_blank">https://github.com/bmcfee/resampy</a>
**Version:** 0.1.4
**Editor:** @arfon
**Reviewer:** @arokem
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.192679" target="_blank">10.5281/zenodo.192679</a>

## Status

[![status](http://joss.theoj.org/papers/5edc41d8387010ad062c29a6a313f740/status.svg)](http://joss.theoj.org/papers/5edc41d8387010ad062c29a6a313f740)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/5edc41d8387010ad062c29a6a313f740"><img src="http://joss.theoj.org/papers/5edc41d8387010ad062c29a6a313f740/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/5edc41d8387010ad062c29a6a313f740/status.svg)](http://joss.theoj.org/papers/5edc41d8387010ad062c29a6a313f740)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bmcfee/resampy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bmcfee/resampy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.4)?
- [x] **Authorship:** Has the submitting author (bmcfee) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @arokem - many thanks for agreeing to review this. This is the main review issue - please work through the checklist as you progress and let me know if you run into any difficulties.

**Comment by arokem** [comment]
👍 from me for publication. 

See: 

https://github.com/bmcfee/resampy/issues/37
https://github.com/bmcfee/resampy/issues/38
https://github.com/bmcfee/resampy/issues/39
https://github.com/bmcfee/resampy/issues/40
https://github.com/bmcfee/resampy/issues/41

**Comment by arfon** [comment]
> 👍 from me for publication.

⚡️ many thanks @arokem.

@bmcfee - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by bmcfee** [comment]
@arfon here it is: https://zenodo.org/record/192679

Thanks!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.192679 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.192679" target="_blank">10.5281/zenodo.192679</a> is the archive.

**Comment by arfon** [comment]
@arokem many thanks for the review here!

@bmcfee - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00125 🚀 🎉 💥

**Comment by bmcfee** [comment]
:shipit:

Thanks again, @arfon and @arokem (and you too, @whedon :robot:)!
