### ISSUE TITLE
[PRE REVIEW]: NeuroDSP: A package for neural digital signal processing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1250]
**Submitting author:** @voytek (<a href="http://orcid.org/0000-0003-1640-2525">Bradley Voytek</a>)
**Repository:** <a href="https://github.com/neurodsp-tools/neurodsp" target ="_blank">https://github.com/neurodsp-tools/neurodsp</a>
**Version:** v1.0.0
**Editor:** @arokem
**Reviewers:** @TomDLT

**Author instructions**

Thanks for submitting your paper to JOSS @voytek. The JOSS editor @arokem, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@voytek if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@arokem) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1250 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:58:in `block in build_affiliation_string': Problem with affiliations for Bradley Voytek, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:57:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:57:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:109:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:109:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:106:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:106:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @arokem - the submitting author suggested you as the handling editor.

**Comment by voytek** [comment]
Fixed affiliation quoting issue

**Comment by arokem** [comment]
Yep. I can take this one! 

@voytek : do you have any ideas for potential reviewers?

**Comment by voytek** [comment]
> @voytek : do you have any ideas for potential reviewers?

The most obvious would be Alexandre Gramfort (alexandre.gramfort@inria.fr), who is the first author on MNE, and Denis Engemann (denis.engemann@googlemail.com) who is also an MNE dev. Both have significant electrophysiology and Python experience.

**Comment by arokem** [comment]
Hey @agramfort: would you be willing to review this paper for [JOSS](http://joss.theoj.org)? Thanks!

**Comment by agramfort** [comment]
I could but I would suggest to ask @TomDLT who certainly has more time to take a close look. Otherwise when would you need a review? For when? Should the review be posted here? What are the guidelines for reviewers?

**Comment by arokem** [comment]
Thanks for the quick response. The guidelines for reviewers are [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). Generally: public/open review on GitHub, focused on a checklist of items that we would like the software to comply with, before publishing the paper. We'd like to have a review in two weeks, if possible. Can you take this on?

**Comment by arokem** [comment]
@TomDLT: @agramfort suggested you would be a good reviewer for this article in [JOSS](http://joss.theoj.org). Would you be available to review this in addition or instead of him? Thanks!

**Comment by TomDLT** [comment]
I can do that !

**Comment by agramfort** [comment]
thanks @TomDLT 

let me know if you need also feedback from me @arokem

**Comment by arokem** [comment]
OK. Let's start with @TomDLT and see whether we need more input down the line. Thanks!

**Comment by arokem** [comment]
@whedon assign @TomDLT as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @TomDLT

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1272. Feel free to close this issue now!

**Comment by arokem** [comment]
@TomDLT please head over to #1272 for your reviewer checklist. I am closing this issue now.
