### ISSUE TITLE
[PRE REVIEW]: pyro: a framework for hydrodynamics explorations and prototyping

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1253]
**Submitting author:** @harpolea (<a href="http://orcid.org/0000-0002-1530-781X">Alice Harpole</a>)
**Repository:** <a href="https://github.com/python-hydro/pyro2" target ="_blank">https://github.com/python-hydro/pyro2</a>
**Version:** 3.0
**Editor:** @labarba
**Reviewers:** @mikaem, @ngoldbaum

**Author instructions**

Thanks for submitting your paper to JOSS @harpolea. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@harpolea if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1253 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1253 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    206      0 --:--:-- --:--:-- --:--:--   207
Error producing PDF.
! Missing { inserted.
<to be read again> 
                   \let 
l.335 ...hod-of-lines piecewise linear solver\(^\\

Looks like we failed to compile the PDF

**Comment by labarba** [comment]
It looks like something is failing with the embedded LaTeX symbol in this line:
 > method-of-lines piecewise linear solver$^\star$

Can you investigate, @harpolea? You could try `\ast` instead?

You can then recompile the paper yourself with the command `@whedon generate pdf` in a comment here.

**Comment by arfon** [comment]
@harpolea - this PR should fix the paper compilation https://github.com/python-hydro/pyro2/pull/72

**Comment by IanHawke** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01253/joss.01253/10.21105.joss.01253.pdf)

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@harpolea, @IanHawke, @zingale, @taataam — If you have any reviewer suggestions, feel free to post them here. The link to our volunteer databas is in the header of this thread.

**Comment by labarba** [comment]
👋  @gforsyth — I wonder if you would be willing/able to contribute a review for JOSS on this submission? *"pyro: a framework for hydrodynamics explorations and prototyping"*

**Comment by IanHawke** [comment]
Based on the list of reviewers my first thought would be @ngoldbaum ; however, I'm not sure if eg @zingale may have a conflict there through yt?

**Comment by harpolea** [comment]
From looking at people in the list who mention CFD, I'd also suggest @mikaem or @highlando

**Comment by mikaem** [comment]
Looks interesting. I'll be happy to do it:-)

**Comment by ngoldbaum** [comment]
If there’s no problem with me and @zingale being yt developers I’d be happy to review this.

**Comment by labarba** [comment]
@ngoldbaum Thank you! According to our policy, we simply ask for disclosure (as you've done here) of any association with the authors, and for an assessment on your part that the circumstance does not make you "unable to make an impartial scientific judgment or evaluation." If you assert that you can be impartial in your review, then we're good!

**Comment by labarba** [comment]
Thanks for agreeing to review, @mikaem! I will assign you now, and add @ngoldbaum in a moment—just waiting for confirmation from him.

**Comment by labarba** [comment]
@whedon assign @mikaem as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mikaem

**Comment by ngoldbaum** [comment]
I assert that my association with Mike doesn't make me unable to make an impartial scientific judgement or evaluation.

**Comment by gforsyth** [comment]
> I wonder if you would be willing/able to contribute a review for JOSS on this submission? _"pyro: a framework for hydrodynamics explorations and prototyping"_

Happy to help -- currently slammed with SciPy stuff, but if you need another reviewer I can take a look next week

**Comment by labarba** [comment]
@whedon add @ngoldbaum as reviewer

**Comment by whedon** [comment]
OK, @ngoldbaum is now a reviewer

**Comment by labarba** [comment]
Thanks for being willing to contribute a review for JOSS, @gforsyth! I will take you up on it another time, as we now have two reviewers for this submission and you're on SciPy duty.
