### ISSUE TITLE
[PRE REVIEW]: Phobos: A tool for creating complex robot models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1254]
**Submitting author:** @Amudtogal (<a href="http://orcid.org/0000-0002-0190-9780">Simon Reichel</a>)
**Repository:** <a href="https://github.com/dfki-ric/phobos" target ="_blank">https://github.com/dfki-ric/phobos</a>
**Version:** 1.0.0 &quot;Capricious Choutengan&quot;
**Editor:** @gkthiruvathukal
**Reviewers:** @CameronDevine, @trallard

**Author instructions**

Thanks for submitting your paper to JOSS @Amudtogal. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Amudtogal if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1254 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1254 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
👋  @Amudtogal — You will need to rename your paper file as `paper.md` for out bot to find it!

**Comment by Amudtogal** [comment]
@wedon commands

On 15.02.19 11:03, whedon wrote:
> Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.
> 
> For a list of things I can do to help you, just type:
> 
> ```
> @whedon commands
> ```
> 
> **What happens now?**
> 
> This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:
> 
> You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/openjournals/joss-reviews/issues/1254#issuecomment-464162404

-- 
Simon V Reichel
MPhil Student
Department of Zoology
University of Cambridge

**Comment by arfon** [comment]
@Amudtogal - please rename `phobos_joss.md` to `paper.md`

**Comment by danielskatz** [comment]
@Amudtogal - Sorry for the delay, I was just looking here to see if you had responded, but then also thought to look at the repo, where I see that you have moved the file.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1254 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0     68      0 --:--:-- --:--:-- --:--:--    68
Error producing PDF.
! Argument of \caption@ydblarg has an extra }.
<inserted text> 
                \par 
l.314 Robots UR5} within \texttt{Phobos}}

Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
👋 @arfon - Can you help me see what's wrong with this?  The figure line in [paper.md](https://github.com/dfki-ric/phobos/blob/master/paper.md) looks ok.  Is there a problem with having a link in a caption?  Or the formatting?

**Comment by Amudtogal** [comment]
Actually, my mistake, I didn't respond to your mail directly!

Thank you for the revision, feel free to contact me for any questions!

Best,
Simon

**Comment by danielskatz** [comment]
ping @arfon ...

**Comment by arfon** [comment]
@danielskatz - looks like we don't support links in captions. That said, anything that looks like a URL us auto-linked in the PDF output anyway. 

Fix for the build here: https://github.com/dfki-ric/phobos/pull/178

**Comment by danielskatz** [comment]
👋 @gkthiruvathukal - while this paper is not quite ready yet, would you be willing to be the editor for the submission?

**Comment by Amudtogal** [comment]
@wedon generate pdf

**Comment by arfon** [comment]
> @wedon generate pdf

@Amudtogal - you're missing the `h` in @whedon

**Comment by Amudtogal** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01254/joss.01254/10.21105.joss.01254.pdf)

**Comment by kyleniemeyer** [comment]
@gkthiruvathukal now that the paper is compiling, can you edit this submission?

**Comment by gkthiruvathukal** [comment]
@kyleniemeyer Yes, I'm getting on the case now. Thanks for the gentle prod. I am getting a good sense of the workflow now.

**Comment by labarba** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
@danielskatz Sorry for not seeing your earlier request. I am usually willing, so the answer is yes. It took me a bit of time to get ramped up as an editor but things are going well now.

@kyleniemeyer Yes, I am on the case.

@Amudtogal Do you have any suggested reviewers from https://bit.ly/joss-reviewers? I plan to make an assignment from the list if I do not hear from you within 24 hours.

**Comment by Amudtogal** [comment]
In terms of reviewers it would be great to have someone from a simulation & robotics background. The best choice might be **carlojoseRG** with background knowledge in ROS & robotics, however Python is not included in his languages.

Other people having useful knowledge for the review are:
**mosteo** (robotics background, Python)
**trallard** (robotics background, Python)
**hugoledoux** (3D, modelling background, Python)
**CELavecchia** (robotics background, Python)
**traversaro** (simulation & robotics background)
**CameronDevine** (robotics background, Python)
**nnadeau** (robotics & mechanics background, Python)
**jizecn** (robotics background, Python)

I hope this helps making a good choice!

**Comment by gkthiruvathukal** [comment]
@Amudtogal Thanks for the quick follow up.

**Comment by gkthiruvathukal** [comment]
@trallard Would you be willing to contribute a review for JOSS on this submission? This submission seems closely related to your areas of expertise and interest.

**Comment by trallard** [comment]
@gkthiruvathukal I would be happy to take this up as a reviewer. I will be OOO until the 1st of April so can only start the review then though

**Comment by gkthiruvathukal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by gkthiruvathukal** [comment]
@trallard Thank you for agreeing and letting me know your plans. I will start the review shortly. I'm still deciding whether I need an additional reviewer.

**Comment by gkthiruvathukal** [comment]
@hugoledoux and @CameronDevine:  As you can see above, I have asked @trallard but she will be away from the office until April 1st. Is there any chance either or both of you would be available to contribute a review this submission?

**Comment by CameronDevine** [comment]
@gkthiruvathukal I would love to contribute a review.

**Comment by gkthiruvathukal** [comment]
Thanks for the quick response, @CameronDevine. If I don't hear from @hugoledoux within 24 hours or so, I'm inclined to go with one reviewer (you) on this one.

**Comment by hugoledoux** [comment]
Sorry, I don't have time to do this in the coming month (holidays).

**Comment by Amudtogal** [comment]
Thank you very much for your efforts! If you need any assistance with the tool, I am ready to help!

**Comment by gkthiruvathukal** [comment]
@whedon assign @CameronDevine as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @CameronDevine

**Comment by gkthiruvathukal** [comment]
@whedon add @trallard as reviewer

**Comment by whedon** [comment]
OK, @trallard is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1326. Feel free to close this issue now!
