### ISSUE TITLE
[REVIEW]: Compare Expression Profiles for Pre-defined Gene Groups with C-REx

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1255]
**Submitting author:** @edifice1989 (<a href="http://orcid.org/0000-0002-8164-2480">Mingze He</a>)
**Repository:** <a href="https://github.com/edifice1989/rocker-c-rex" target ="_blank">https://github.com/edifice1989/rocker-c-rex</a>
**Version:** v1.0
**Editor:** @mgymrek
**Reviewer:** @byandell
**Archive:** <a href="https://doi.org/10.5281/zenodo.2651751" target="_blank">10.5281/zenodo.2651751</a>

## Status

[![status](http://joss.theoj.org/papers/650c8eea1668b7cfe0c4c4702ad146e4/status.svg)](http://joss.theoj.org/papers/650c8eea1668b7cfe0c4c4702ad146e4)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/650c8eea1668b7cfe0c4c4702ad146e4"><img src="http://joss.theoj.org/papers/650c8eea1668b7cfe0c4c4702ad146e4/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/650c8eea1668b7cfe0c4c4702ad146e4/status.svg)](http://joss.theoj.org/papers/650c8eea1668b7cfe0c4c4702ad146e4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/edifice1989/rocker-c-rex" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@byandell, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @mgymrek know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/edifice1989/rocker-c-rex">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@edifice1989) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @byandell it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01255/joss.01255/10.21105.joss.01255.pdf)

**Comment by mgymrek** [comment]
quoting from @byandell: "It is a nice application, but I think these methods are fairly standard. It allows comparison of two pre-determined groups, but often this is the start of much more intense investigation, and I don't see how to use the Shiny app beyond doing t-tests. The Shiny app appears quite polished in many ways, although I got an error with Wilcoxon test for between sample comparison, and it took awhile to initially load the data on the server."

**Comment by edifice1989** [comment]
Thanks for the feedback from @byandell !

To  @byandell <https://github.com/byandell>:

Could you tell me a little bit more about which test data you used for
Wilcoxon test for between sample comparison?

Thank you very much!!

Ming

**Comment by edifice1989** [comment]
Hi Melissa,

    I just found a typo in the paper.md. I made changes to that. Is that
enough to fix this typo to be reflected in the final version? What else
should I do?

   Thanks!!

Best,
Ming

**Comment by mgymrek** [comment]
Hi @byandell would you be able to fill out the checklist at the top of the review?

**Comment by edifice1989** [comment]
Hi Melissa,

Is there any feedback from reviewer? Thank you very much!!

Ming

**Comment by mgymrek** [comment]
@byandell would you be able to fill out the checklist?

@edifice1989 I will also try to contact @byandell directly

**Comment by edifice1989** [comment]
Hi Melissa,

   Is there any updates from the reviewer?

  I am still waiting patiently: )

Thanks,
Ming

**Comment by byandell** [comment]
I filled out the checklist. Sorry, did not realize there was more to do. What else?
Brian

Brian S. Yandell brian.yandell@wisc.edu<mailto:brian.yandell@wisc.edu>
Professor of Biometry, Statistics & Horticulture
University of Wisconsin-Madison
http://www.stat.wisc.edu/~yandell

**Comment by edifice1989** [comment]
@byandell thank you very much!
@mgymrek <https://github.com/mgymrek> please kindly advise what are next
steps. thanks!!

Best,
Ming

**Comment by edifice1989** [comment]
Hi Melissa,

    Please advise if there is any other issues need to be fixed!

    Thanks a lot!!

Best,
Ming

**Comment by mgymrek** [comment]
Thanks @byandell for the review.

@edifice1989 I just have minor comments that should be addressed:
* The README.md file should be more informative, with at the very least a description of what the software does, install instructions (which are there already), and basic usage.
* For the paper, we require a statement of need. Could you add a brief description of how this fulfills a need not met by existing tools, and add some references to those?

**Comment by edifice1989** [comment]
@whedon <https://github.com/whedon> generate pdf

**Comment by edifice1989** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01255/joss.01255/10.21105.joss.01255.pdf)

**Comment by edifice1989** [comment]
@mgymrek <https://github.com/mgymrek> thanks for your kind and helpful
comments!

I have updated README.md to include table of contents, more information
about the purpose of C-REx and 3 more example usages

Also, I added a section of statement of need  in paper.md with references
(updated paper.bib) to explain how C-REx is different than other
approaches, especially where enrichment analysis fails instead C-REx could
be helpful

Please let me know if there is anything else need to be addressed!

Thank you very much!!

Ming

**Comment by edifice1989** [comment]
Hi @mgymrek <https://github.com/mgymrek>,

   Could you please take a look of my updated README.md and paper.me with
statement of need? I am looking forward for your feedback!

   Thank you very much!

Best,
Ming

**Comment by labarba** [comment]
👋  @mgymrek — It looks like this submission is ready for you to take action on the author's response to your final comments. Ping us by mentioning `@openjournals/joss-eics` when ready to publish.

**Comment by byandell** [comment]
Who is “you” in the message? Brian

Brian S. Yandell
Professor, Statistics & Horticulture
Director, Biometry Program
University of Wisconsin—Madison
http://www.stat.wisc.edu/~Yandell
________________________________

**Comment by labarba** [comment]
From the review thread, it looks like @mgymrek requested some changes 19 days ago: https://github.com/openjournals/joss-reviews/issues/1255#issuecomment-476261001

The author reports having addressed these.

**Comment by edifice1989** [comment]
Hi @labarba <http://lorenabarba.com/>,

   Thanks for your inquiry! Have you heard anything back from @mgymrek
<https://github.com/mgymrek> ?

   It is almost a month since I addressed her comments.

  Thank you very much!!

**Comment by labarba** [comment]
@openjournals/joss-eic — This review needs your attention. It looks like we need @mgymrek to come back to it.

**Comment by danielskatz** [comment]
👋 @mgymrek - Please take a look at this review again, since there are changes based on your previous feedback.

**Comment by mgymrek** [comment]
I apologize for the delay. Thank you for addressing the comments, this looks good. Can you now make a Zenodo archive and report the DOI in this thread?

**Comment by edifice1989** [comment]
Here is the DOI from Zenodo: 10.5281/zenodo.2651751

Thanks!!

**Comment by edifice1989** [comment]
Hi @mgymrek <https://github.com/mgymrek> Does the Zenodo archive and DOI
look good? Is there anything else I need to do? thank you very much!

**Comment by kyleniemeyer** [comment]
@whedon set  10.5281/zenodo.2651751 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2651751" target="_blank">10.5281/zenodo.2651751</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01255/joss.01255/10.21105.joss.01255.pdf)

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.cpb.2017.12.003 is OK
- 10.1371/journal.pgen.1004915 is OK
- 10.1186/gb-2010-11-3-r25 is OK
- 10.1186/1471-2105-12-323 is OK
- 10.1186/gb-2010-11-10-r106 is OK
- 10.1038/nprot.2012.016 is OK
- 10.1093/bioinformatics/btm051 is OK
- 10.1186/s13059-016-0881-8 is OK
- 10.1093/bioinformatics/btv122 is OK
- 10.1093/bioinformatics/bts034 is OK
- 10.1038/nprot.2011.457 is OK
- 10.1093/bioinformatics/bti267 is OK
- 10.1093/nar/gkg115 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @edifice1989, I submitted a minor PR for the paper that fixed some of the references: https://github.com/edifice1989/rocker-c-rex/pull/2

Please merge that, and we can move forward with the final acceptance.

**Comment by edifice1989** [comment]
Hi Kyle,

     I have merged your request.

    Thank you very much for your help!!

Best,
Ming

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01255/joss.01255/10.21105.joss.01255.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/651

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/651, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.cpb.2017.12.003 is OK
- 10.1371/journal.pgen.1004915 is OK
- 10.1186/gb-2010-11-3-r25 is OK
- 10.1186/1471-2105-12-323 is OK
- 10.1186/gb-2010-11-10-r106 is OK
- 10.1038/nprot.2012.016 is OK
- 10.1093/bioinformatics/btm051 is OK
- 10.1186/s13059-016-0881-8 is OK
- 10.1093/bioinformatics/btv122 is OK
- 10.1093/bioinformatics/bts034 is OK
- 10.1038/nprot.2011.457 is OK
- 10.1093/bioinformatics/bti267 is OK
- 10.1093/nar/gkg115 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/652
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01255](https://doi.org/10.21105/joss.01255)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
@edifice1989 congrats on your paper's acceptance in JOSS! Thanks to @byandell for reviewing and @mgymrek for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01255/status.svg)](https://doi.org/10.21105/joss.01255)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01255">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01255/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01255/status.svg
   :target: https://doi.org/10.21105/joss.01255
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01255/status.svg)](https://doi.org/10.21105/joss.01255)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
