### ISSUE TITLE
[REVIEW]: TextWiller: collection of text mining utilities, specially devoted to the Italian language

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1256]
**Submitting author:** @scan2001 (<a href="http://orcid.org/0000-0001-5621-5463">andrea sciandra</a>)
**Repository:** <a href="https://github.com/livioivil/TextWiller" target ="_blank">https://github.com/livioivil/TextWiller</a>
**Version:** v1.0
**Editor:** @mgymrek
**Reviewer:** @timClicks
**Archive:** <a href="https://doi.org/10.5281/zenodo.3381523" target="_blank">10.5281/zenodo.3381523</a>

## Status

[![status](http://joss.theoj.org/papers/631dac1f05dcf07a36a5add954a31f90/status.svg)](http://joss.theoj.org/papers/631dac1f05dcf07a36a5add954a31f90)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/631dac1f05dcf07a36a5add954a31f90"><img src="http://joss.theoj.org/papers/631dac1f05dcf07a36a5add954a31f90/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/631dac1f05dcf07a36a5add954a31f90/status.svg)](http://joss.theoj.org/papers/631dac1f05dcf07a36a5add954a31f90)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/livioivil/TextWiller" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@timClicks, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @mgymrek know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/livioivil/TextWiller">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0
- [x] **Authorship:** Has the submitting author (@scan2001) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @timClicks it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01256/joss.01256/10.21105.joss.01256.pdf)

**Comment by mgymrek** [comment]
Copying from the pre-review thread from @timClicks :

Hi @scan2001, thanks for the paper submission. I'm not officially an assigned reviewer, but I've taken a quick look at the paper. 

Let me start by saying that it's excellent to see NLP contributions to non-English languages.

**Prior art**

However, there are many text mining packages available, even sticking within the R community. I wonder if you should cite some of the other open source NLP packages and explain that they do not offer Italian stemming/normalisation?

From the review guidelines:

> Submissions that implement solutions already solved in other software packages are accepted into JOSS provided that they meet the criteria listed above **and cite prior similar work**. [emphasis added]


**Authorship**

I believe that it's up to your team to decide on authorship, but the three authors don't match the authors listed in the [DESCRIPTION](https://github.com/livioivil/TextWiller/blob/master/DESCRIPTION) file or the [TextWiller-package.R](https://github.com/livioivil/TextWiller/blob/master/R/TextWiller-package.R#L13) file.

Also, from the [contribution list](https://github.com/livioivil/TextWiller/graphs/contributors), it's unclear what level of contribution that your first author has made? (I assume that some of the commit history has been lost)  

Here is the relevant guidance from the review guidelines:

> As part of the review process, you are asked to check whether the submitting author has made a ‘substantial contribution’ to the submitted software (as determined by the commit history) and to check that ‘the full list of paper authors seems appropriate and complete?’ 


**Documentation**

[TextWiller's API documentation](https://github.com/livioivil/TextWiller/tree/master/man) is in Italian. However, it looks comprehensive.

(Deferring to @mgymrek for an opinion about whether this is allowed) 



**Tests**

TextWiller doesn't appear to have a comprehensive test suite.

**Comment by mgymrek** [comment]
@timClicks thanks for starting the review! would you also be able to fill out the checklist here?

**Comment by mgymrek** [comment]
Hi @timClicks I just wanted to check in on this

**Comment by timClicks** [comment]
@mgymrek Apologies on the delay. Will make my way through installation this week.

**Comment by mgymrek** [comment]
hi @timClicks I just wanted to ping you about the review. I see you've started the checklist.

**Comment by labarba** [comment]
👋  @timClicks — can you update us on your status with this review?

**Comment by mgymrek** [comment]
@timClicks can you give us an update if you will be able to complete this review?

**Comment by danielskatz** [comment]
👋 @timClicks - we haven't heard from you in about 10 weeks now - are you still planning to perform this review?

**Comment by danielskatz** [comment]
Note twitter discussion thread: https://twitter.com/LorenaABarba/status/1131222830794903552

**Comment by timClicks** [comment]
Statement of need from paper.md, l 32

> The main quality of this software is to be one of the few text mining R packages in Italian language. Moreover, TextWiller can help social media researchers with some specific functions for the data extracted from Twitter via APIs.

**Comment by timClicks** [comment]
Installation was very easy, `TextWiller`'s dependencies were fully satisfied by installing the `devtools` library as recommended in the instructions.

**Comment by timClicks** [comment]
**Functionality documentation** provided by `TextWiller` is comprehensive with examples. All public functions appear to be documented in RMarkdown in the `/man` directory, as is conventional for R projects.

**Comment by timClicks** [comment]
**References** do not include any archival resources, so I have marked this as a pass.

**Comment by timClicks** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by timClicks** [comment]
@mgymrek I believe that there are no community guidelines in the repository or any tests, either automated or manual.

I believe that the paper and the project meet the other criteria.

**Comment by mgymrek** [comment]
Thanks @timClicks.

@scan2001. I agree with these comments. Including tests and community guidelines is a JOSS requirement. Are you able to add tests for TextWiller functionality, and also to expand the README with guidelines for community members to contribute or get support?

You may look at other JOSS submissions for examples. e.g. https://github.com/ropensci/citesdb

**Comment by scan2001** [comment]
Thanks @mgymrek and @timClicks.
We will add tests for TextWiller functionality and the guidelines for community members to contribute or get support.

**Comment by kyleniemeyer** [comment]
Hi @scan2001, just wanted to check on your progress. Can you give us an expected date when you think you'll be able to complete that work?

**Comment by scan2001** [comment]
Hi @kyleniemeyer, sorry for the delay. We have already included the guidelines for community members and we will run the tests probably next week, with maximum expected date no later than July 14th.

**Comment by kyleniemeyer** [comment]
@whedon remind @scan2001 in 2.5 weeks

**Comment by whedon** [comment]
I don't recognize this description of time '2.5' 'weeks'.

**Comment by kyleniemeyer** [comment]
@whedon remind @scan2001 in 3 weeks

**Comment by whedon** [comment]
Reminder set for @scan2001 in 3 weeks

**Comment by scan2001** [comment]
@mgymrek @kyleniemeyer
we have completed the tests and added community guidelines (updating README and creating a code of conduct file)

**Comment by mgymrek** [comment]
Thanks for the updates. Comments:

* Please add to the README how to run the tests. This wasn't clear.

For the paper:

* The paper should mention in the first sentence the focus on Italian language.
* The paper should have a clear statement of need: are there any other existing packages that do something similar? How does your tool compare to those?
* The text could be slighltly expanded so non-experts can better interpret what the tool is doing. For example, you might have bullet points or small paragraph about several of the major functions, where could you describe and define the goal (e.g. what does it mean to normalize) and the inputs and outputs of the tool.

**Comment by whedon** [comment]
:wave: @scan2001, please update us on how things are progressing here.

**Comment by scan2001** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01256/joss.01256/10.21105.joss.01256.pdf)

**Comment by scan2001** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01256/joss.01256/10.21105.joss.01256.pdf)

**Comment by scan2001** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01256/joss.01256/10.21105.joss.01256.pdf)

**Comment by scan2001** [comment]
@mgymrek we modified the paper and the README to meet your requests

**Comment by mgymrek** [comment]
Great, thanks for the changes. This looks good.

To prepare for publication can you:

* Fix the following minor typos:
"few text mining R packages in Italian language" -> "few text mining R packages in the Italian language"
"main differences ... is... " -> "main differences ...are..."
"extract users communication pattern" -> "extract users' communication patterns" 

* Please add DOIs to all references

* Create an archive (e.g. Zenodo) and post the archive DOI in the review issue

**Comment by scan2001** [comment]
@whedon generate pdf

**Comment by scan2001** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.3115/1220575.1220619 is OK
- 10.1007/978-88-470-5532-2 is OK
- 10.1016/c2010-0-66188-8 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by scan2001** [comment]
@whedon set 10.5281/zenodo.3381523 as archive

**Comment by whedon** [comment]
I'm sorry @scan2001, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by scan2001** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01256/joss.01256/10.21105.joss.01256.pdf)

**Comment by scan2001** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01256/joss.01256/10.21105.joss.01256.pdf)

**Comment by scan2001** [comment]
Thanks @mgymrek
We fixed the typos, added DOIs to all references (except the last two: a book and a thesis, as they haven't a DOI) and created an archive in Zenodo. 
This is the archive DOI: 10.5281/zenodo.3381523

**Comment by mgymrek** [comment]
Thanks @scan2001. Can you please ensure the Zenodo release has the same title and author list as the JOSS paper for consistency? Then we should be ready to go.

**Comment by scan2001** [comment]
Thanks @mgymrek. We set Zenodo release title and authors so that they are the same as those in the paper

**Comment by mgymrek** [comment]
@whedon set 10.5281/zenodo.3381523 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3381523" target="_blank">10.5281/zenodo.3381523</a> is the archive.

**Comment by mgymrek** [comment]
Thanks @scan2001. I noticed the version on this thread is listed as 2.0 but on Zenodo it says v1.0. Could you clarify which version number the final release is, and make sure that matches with what is listed on Zenodo?

**Comment by scan2001** [comment]
Thanks @mgymrek. We named the release v1.0 because it's the first release we did specifically for the Zenodo archive, while version 2.0 doesn't concern the release, it was only written by one collaborator in the description without any particular reason, actually we don't have 2 version of this software.

**Comment by mgymrek** [comment]
@whedon set v1.0 as version

**Comment by whedon** [comment]
OK. v1.0 is the version.

**Comment by mgymrek** [comment]
ok, Thanks @scan2001.
@openjournals/joss-eics we are ready to accept this submission.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/956

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/956, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1170821178140823553) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/957
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01256](https://doi.org/10.21105/joss.01256)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@timClicks - many thanks for your review here and to @mgymrek for editing this submission ✨ 

@scan2001 - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01256/status.svg)](https://doi.org/10.21105/joss.01256)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01256">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01256/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01256/status.svg
   :target: https://doi.org/10.21105/joss.01256
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01256/status.svg)](https://doi.org/10.21105/joss.01256)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
