### ISSUE TITLE
[REVIEW]: AtlasReader: A Python package to generate coordinate tables, region labels, and informative figures from statistical MRI images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1257]
**Submitting author:** @miykael (<a href="http://orcid.org/0000-0002-5866-047X">Michael Philipp Notter</a>)
**Repository:** <a href="https://github.com/miykael/atlasreader" target ="_blank">https://github.com/miykael/atlasreader</a>
**Version:** v0.1.0
**Editor:** @cMadan
**Reviewer:** @andrewheusser
**Archive:** <a href="https://doi.org/10.5281/zenodo.2575731" target="_blank">10.5281/zenodo.2575731</a>

## Status

[![status](http://joss.theoj.org/papers/c5edcaeab94610f7bad4b631642b896b/status.svg)](http://joss.theoj.org/papers/c5edcaeab94610f7bad4b631642b896b)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/c5edcaeab94610f7bad4b631642b896b"><img src="http://joss.theoj.org/papers/c5edcaeab94610f7bad4b631642b896b/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/c5edcaeab94610f7bad4b631642b896b/status.svg)](http://joss.theoj.org/papers/c5edcaeab94610f7bad4b631642b896b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/miykael/atlasreader" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@andrewheusser, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @cMadan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/miykael/atlasreader">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.1.0
- [x] **Authorship:** Has the submitting author (@miykael) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @andrewheusser it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01257/joss.01257/10.21105.joss.01257.pdf)

**Comment by andrewheusser** [comment]
hey @cMadan - I finished the review and the author sufficiently addressed all of my concerns (see [here](https://github.com/miykael/atlasreader/issues?q=is%3Aissue+author%3Aandrewheusser+is%3Aclosed).  The author implemented the changes on a branch, but they are not yet merged.  What are the next steps?

**Comment by cMadan** [comment]
@andrewheusser, thank you for the prompt and thorough review! It looks like you're all done.

For @miykael, the next steps are to merge these changes and confirm that you think it's ready to be accepted. Then I'll look everything over and check that I agree. If that's the case, I'll then ask for the DOI of an archived copy of the code and what version of the software corresponds to the code after the revisions related to the review--and then we're all set!

**Comment by miykael** [comment]
Thank you @andrewheusser for the very nice and helpful feedback! Your comments were much appreciated and helped to improve the toolbox.

@cMadan - I've merged the changes created a new GitHub release and a new PyPi release. So, the current version number is now v0.1.0. In my opinion (and this of the co-authors), the toolbox is ready to be accepted. Can I update the version number in the JOSS publication or is that up to you? Is there anything else that I can help with?

**Comment by miykael** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01257/joss.01257/10.21105.joss.01257.pdf)

**Comment by miykael** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01257/joss.01257/10.21105.joss.01257.pdf)

**Comment by miykael** [comment]
I apologize for the repeated `@whedon` commands, but I try to get the paper output to the right format. But the next "PDF generation" should be the last.

**Comment by miykael** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01257/joss.01257/10.21105.joss.01257.pdf)

**Comment by miykael** [comment]
Sorry, found a small typo in the references. But otherwise, everything is good to go.

**Comment by miykael** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01257/joss.01257/10.21105.joss.01257.pdf)

**Comment by andrewheusser** [comment]
my pleasure, nice job on the package!

**Comment by cMadan** [comment]
@whedon set v0.1.0 as version

**Comment by whedon** [comment]
OK. v0.1.0 is the version.

**Comment by cMadan** [comment]
@whedon set 10.5281/zenodo.2575731 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2575731" target="_blank">10.5281/zenodo.2575731</a> is the archive.

**Comment by cMadan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/518

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/518, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1109/MCSE.2007.55 is OK
- http://doi.org/10.1016/j.neuroimage.2010.07.033 is OK
- http://doi.org/10.5281/zenodo.1287921 is OK
- http://doi.org/10.3389/fninf.2014.00014 is OK
- http://doi.org/10.1109/MCSE.2007.58 is OK
- http://doi.org/10.7717/peerj.453 is OK

MISSING DOIs

- https://doi.org/10.1017/cbo9781139871754.008 may be missing for title: SciPy: Open source scientific tools for Python
- https://doi.org/10.3389/fninf.2014.00014 may be missing for title: Scikit-learn: Machine learning in Python

INVALID DOIs

- None
```

**Comment by cMadan** [comment]
I think those missing DOIs aren't correct here, they are related but more tutorial to the packages than for the packages per se. As discussed in the review (https://github.com/miykael/atlasreader/issues/105), I think there aren't DOIs for those references.

@miykael, you're all set congratulations! @andrewheusser, thank you again for the thorough review.

@arfon, can you do the honors?

**Comment by arfon** [comment]
> @arfon, can you do the honors?

Done. The proof I generated locally ended up doing a slightly better job with figure layout so I processed the paper manually.

@andrewheusser - many thanks for your review here and to @cMadan for editing this submission ✨ 

@miykael - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01257/status.svg)](https://doi.org/10.21105/joss.01257)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01257">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01257/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01257/status.svg
   :target: https://doi.org/10.21105/joss.01257
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01257/status.svg)](https://doi.org/10.21105/joss.01257)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by miykael** [comment]
@andrewheusser - thank you again for your great review!

@cMadan - thank you for your work and accepting the paper.

@arfon - thank you for changing the figure layout. It's now exactly how I wanted it.

**Comment by andrewheusser** [comment]
👍 my pleasure
