### ISSUE TITLE
[PRE REVIEW]: `tqdm`: A Fast, Extensible Progress Meter for Python and CLI

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1258]
**Submitting author:** @casperdcl (<a href="http://orcid.org/0000-0002-7211-1557">da Costa-Luis, Casper O.</a>)
**Repository:** <a href="https://github.com/tqdm/tqdm" target ="_blank">https://github.com/tqdm/tqdm</a>
**Version:** v4.31.1
**Editor:** @cMadan
**Reviewers:** @GregaVrbancic, @Benjamin-Lee

**Author instructions**

Thanks for submitting your paper to JOSS @casperdcl. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@casperdcl if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1258 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: affiliations, bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@casperdcl — The `paper.md` file does not conform to the JOSS requirements. Please re-read and follow the [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html) to prepare a `paper.md` with the needed metadata (the bibliography needs to go in a .bib file).

Very cool project… but for the purposes of a JOSS review, we will need your paper to address the research application of the software. We call this a "Statement of Need,"

> The authors should clearly state what problems the software is designed to solve and who the target audience is. 

From the [Submission Requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements):

> The software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler)

**Comment by casperdcl** [comment]
@labarba thanks for your comments. I did indeed read the submission guidelines thoroughly and expected a discussion.

1. Does `paper.md` and/or `paper.bib` have to be located in the root of the repository? I am very hesitant to clutter the root (which is why I put the bib in-place. The guidelines did not explicitly forbid this). Ideally I can put all materials in a `paper` subfolder. Even better, I'd prefer to place them in a different repository (e.g. the documentation repo)
2. Does the `affiliations` filed have to be filled in? This work was not supported by any institution and thus there are no applicable affiliations. If this is required, perhaps "Independent" or "Non-affiliated" would suffice?
3. Browsing other accepted papers, I noticed a "statement of need" was not always explicitly given, but rather inferred from the summary. If you believe this paper needs it, I am happy to add one - do let me know.
4. If @whedon needs to be able to auto-complie this paper, could you provide details as to how I can replicate the paper build environment locally for testing? Alternatively I can provide my own build instructions.

**Comment by labarba** [comment]
1. A folder is fine. A branch is fine. A different repo, no. (But you can delete after archive and publication.)
2. Need to put something in affiliation. Up to you what.
3. Statement of Need is not a required _heading_, but the content is. Your paper lacks the content.
4. The auto-build by `whedon` here is a requisite for publication. JOSS is able to be free thanks to many volunteers and extensive automation. You can attempt to build after pushing changes with the command `@whedon generate pdf` in a comment here.

**Comment by casperdcl** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by casperdcl** [comment]
@whedon generate pdf from branch devel

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch devel. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1258 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by casperdcl** [comment]
@whedon generate pdf from branch devel

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch devel. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01258/joss.01258/10.21105.joss.01258.pdf)

**Comment by casperdcl** [comment]
@whedon generate pdf from branch devel

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch devel. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01258/joss.01258/10.21105.joss.01258.pdf)

**Comment by casperdcl** [comment]
- [x] affilitiations
- [ ] statement of need
- [x] fix generate issues

**Comment by casperdcl** [comment]
@whedon generate pdf from branch devel

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch devel. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01258/joss.01258/10.21105.joss.01258.pdf)

**Comment by casperdcl** [comment]
@labarba thanks I think it's ready now

**Comment by casperdcl** [comment]
@whedon generate pdf from branch devel

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch devel. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01258/joss.01258/10.21105.joss.01258.pdf)

**Comment by casperdcl** [comment]
@whedon generate pdf from branch devel

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch devel. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01258/joss.01258/10.21105.joss.01258.pdf)

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@casperdcl, thank you for submitting tdqm for publication in JOSS. I have used tdqm myself and recommended it to others and think it's a great package. That said, I'm not convinced that it's within the scope for publication in JOSS, but perhaps you can make the relevance more clear.

From the submission requirements (https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements):
> JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or the execution of research experiments; extracts knowledge from large data sets; offers a mathematical library, or similar.

I am unsure if tdqm fits this criteria. It's definitely a useful utility in developing research software, but do you think it fits this criteria? For instance, do you think others will cite their use of tdqm in research papers?

**Comment by casperdcl** [comment]
Thanks @cMadan - it's on the first page out of >100k packages on https://libraries.io/search?languages=Python&order=desc&sort=rank, and as per JOSS requirements I've listed some peer-reviewed publications which explicitly list `tqdm` (see the *Popularity* section in the paper). It can be invaluable when debugging, say, learning rates of a machine learning framework. At 5M downloads per month (see below) I don't know how it compares to other JOSS software.

[![Libraries-Rank](https://img.shields.io/librariesio/sourcerank/pypi/tqdm.svg?logo=koding&logoColor=white)](https://libraries.io/pypi/tqdm) [![PyPI-Downloads](https://img.shields.io/pypi/dm/tqdm.svg?label=pypi%20downloads&logo=python&logoColor=white)](https://pypi.org/project/tqdm) [![OpenHub-Status](https://www.openhub.net/p/tqdm/widgets/project_thin_badge?format=gif)](https://www.openhub.net/p/tqdm?ref=Thin+badge) [![README-Hits](https://caspersci.uk.to/cgi-bin/hits.cgi?q=tqdm&style=social&r=https://github.com/tqdm/tqdm&l=https://caspersci.uk.to/images/tqdm.png&f=https://raw.githubusercontent.com/tqdm/tqdm/master/images/logo.gif)](https://caspersci.uk.to/cgi-bin/hits.cgi?q=tqdm&a=plot&r=https://github.com/tqdm/tqdm&l=https://caspersci.uk.to/images/tqdm.png&f=https://raw.githubusercontent.com/tqdm/tqdm/master/images/logo.gif&style=social)

**Comment by cMadan** [comment]
Thanks for your response, @casperdcl! I looked through some other JOSS submissions and there are other instances of software that is more intended towards developers than a specific application/group of users, so I agree that it is sufficiently within-scope.

Do you have any suggestions for reviewers?

**Comment by casperdcl** [comment]
Well since it's so widely applicable as you've noted, I don't have any reviewer preference. Just someone who uses python regularly!

**Comment by cMadan** [comment]
@sealhuang @lindemann09 @GregaVrbancic, would any of you be interested/available to review this submission?

**Comment by GregaVrbancic** [comment]
Hi @cMadan!

If it is acceptable, I could review this submission in the next few days.

**Comment by cMadan** [comment]
@GregaVrbancic, that would be great! I'll wait to see if someone else volunteers to be an additional reviewer, but will start the review shortly.

**Comment by cMadan** [comment]
@whedon add @GregaVrbancic as reviewer

**Comment by whedon** [comment]
OK, @GregaVrbancic is now a reviewer

**Comment by Benjamin-Lee** [comment]
I'm glad to review as well!

**Comment by cMadan** [comment]
Thanks for volunteering, @Benjamin-Lee! I'll add you as a reviewer and go ahead and start the review.

**Comment by cMadan** [comment]
@whedon add @Benjamin-Lee as reviewer

**Comment by whedon** [comment]
OK, @Benjamin-Lee is now a reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1277. Feel free to close this issue now!
