### ISSUE TITLE
[PRE REVIEW]: mitolina: MITOchondrial LINeage Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1259]
**Submitting author:** @mikldk (<a href="http://orcid.org/0000-0002-0234-0266">Mikkel Meyer Andersen</a>)
**Repository:** <a href="https://github.com/mikldk/mitolina" target ="_blank">https://github.com/mikldk/mitolina</a>
**Version:** v0.0.1
**Editor:** @lpantano
**Reviewers:** @jdeligt

**Author instructions**

Thanks for submitting your paper to JOSS @mikldk. The JOSS editor @mgymrek, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mikldk if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mgymrek it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@mgymrek) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1259 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
Hi @mikldk - you need to put a paper in the repository before a review can start - see https://joss.readthedocs.io/en/latest/submitting.html

**Comment by mikldk** [comment]
I totally agree. I forgot to change `.gitignore` (mikldk/mitolina@eccc17e3ada22fda0e920732523beb63d39c1ec9)

**Comment by mikldk** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01259/joss.01259/10.21105.joss.01259.pdf)

**Comment by mikldk** [comment]
Now fixed (mikldk/mitolina@eccc17e3ada22fda0e920732523beb63d39c1ec9 + mikldk/mitolina@4b24a010b6b175e45a1f639029da68e1603ac205). Thanks, @danielskatz.

**Comment by danielskatz** [comment]
👋 @mgymrek - note that the authors suggested you as the editor, and this is now assigned to you

**Comment by pjotrp** [comment]
We should not assign editors without agreement. Lorena has agreed to edit this one.

**Comment by pjotrp** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by pjotrp** [comment]
@danielskatz thank you for helping out! @mikldk we'll look for a reviewer. If you know someone in your field who can review, you can recommend.

**Comment by mikldk** [comment]
Thanks, @pjotrp. I give it a thought. Although not in the centre of my field, @afrubin and @ajank have previously reviewed related software (#684); maybe they are ready again?

**Comment by ajank** [comment]
Hi @mikldk, thanks for asking! Unfortunately I cannot commit myself to review anything in the coming few weeks. If you were still looking for a reviewer in 2-3 weeks from now, do not hesitate to contact me again.

**Comment by mikldk** [comment]
Hi @ajank ; thank's for letting us know. @pjotrp and I will try to find someone else.

**Comment by lpantano** [comment]
@whedon assign @jdeligt as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jdeligt

**Comment by lpantano** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1266. Feel free to close this issue now!

**Comment by danielskatz** [comment]
FWIW, @lpantano, you shouldn't need to use the "magic-word" - just ```@whedon start review``` should work
