### ISSUE TITLE
[PRE REVIEW]: riskclustr: Functions to Study Etiologic Heterogeneity

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1263]
**Submitting author:** @zabore (<a href="http://orcid.org/0000-0002-1402-4498">Emily Zabor</a>)
**Repository:** <a href="https://github.com/zabore/riskclustr" target ="_blank">https://github.com/zabore/riskclustr</a>
**Version:** 0.1.0
**Editor:** @pjotrp
**Reviewers:** @avhoeck

**Author instructions**

Thanks for submitting your paper to JOSS @zabore. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@zabore if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01263/joss.01263/10.21105.joss.01263.pdf)

**Comment by arfon** [comment]
:wave: @pjotrp - do you think you could suggest a handling editor for this submission?

**Comment by pjotrp** [comment]
Very cool paper :)

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@whedon assign @avhoeck as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @avhoeck

**Comment by pjotrp** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1269. Feel free to close this issue now!
