### ISSUE TITLE
[REVIEW]: mitolina: MITOchondrial LINeage Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1266]
**Submitting author:** @mikldk (<a href="http://orcid.org/0000-0002-0234-0266">Mikkel Meyer Andersen</a>)
**Repository:** <a href="https://github.com/mikldk/mitolina" target ="_blank">https://github.com/mikldk/mitolina</a>
**Version:** v0.0.1
**Editor:** @lpantano
**Reviewer:** @jdeligt
**Archive:** <a href="https://doi.org/10.5281/zenodo.2574400" target="_blank">10.5281/zenodo.2574400</a>

## Status

[![status](http://joss.theoj.org/papers/1819fd2f15585545474c1c82bf97f213/status.svg)](http://joss.theoj.org/papers/1819fd2f15585545474c1c82bf97f213)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/1819fd2f15585545474c1c82bf97f213"><img src="http://joss.theoj.org/papers/1819fd2f15585545474c1c82bf97f213/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/1819fd2f15585545474c1c82bf97f213/status.svg)](http://joss.theoj.org/papers/1819fd2f15585545474c1c82bf97f213)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mikldk/mitolina" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jdeligt, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mikldk/mitolina">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.0.1)?
- [x] **Authorship:** Has the submitting author (@mikldk) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jdeligt it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01266/joss.01266/10.21105.joss.01266.pdf)

**Comment by lpantano** [comment]
Hi @mikldk, 

We are starting the review process in this issue tracker. 

To expedite the review process do you mind going through the above list of checkboxes and make sure they can be ticked (you can't tick them). Also, check the PDF output carefully. 

Please, Ping us here when you are done.

Cheers

Lorena

**Comment by mikldk** [comment]
Hi @lpantano. Ping: I went though the list and I seem to have addressed all.

**Comment by jdeligt** [comment]
Hi @mikldk I just raised a minor issue on not having a release in the repo. Could you please look into this while I continue with the rest of the review. 
https://github.com/mikldk/mitolina/issues/2

**Comment by jdeligt** [comment]
Now hit a bigger issue: https://github.com/mikldk/mitolina/issues/3.
I have to manually install dependencies upon which relies on a 'non standard library': libudunits2.so

**Comment by jdeligt** [comment]
@mikldk please let me know when you've looked at this so I can check the last steps. Apart from the software side of things I would like to hear your take on the Biparental inheritance published in November: https://doi.org/10.1073/pnas.1810946115 and how your software deals with this. I think its an important thing to note for potential users especially if you're targeting forensics where edge cases matter a lot.

**Comment by mikldk** [comment]
@jdeligt:
Thanks for all your inputs!

1) Regarding a release (mikldk/mitolina#2): I thought I should wait until after potential acceptance. But I now made one [here](https://github.com/mikldk/mitolina/releases).
2) Vignette not loading (mikldk/mitolina#3): I have now updated `README.md` to compile these by default (`remotes::install_github("mikldk/mitolina", build_opts = c("--no-resave-data", "--no-manual"))`). Thanks.
3) Dependencies: I have now adapted the vignette so that it checks whether the suggested `ggraph` is installed. This ought to remove the "'non standard library': libudunits2.so" warning. Thanks.
4) Regarding [10.1073/pnas.1810946115](https://doi.org/10.1073/pnas.1810946115): There is still very much debate about this. See e.g. [10.1073/pnas.1820533116](https://doi.org/10.1073/pnas.1820533116). Still, the general belief is that mtDNA is maternally inherited.

Please let me know if I can assist further.

**Comment by jdeligt** [comment]
@mikldk thanks fro the quick response and resolving the issues. As far as the software/paper is concerned I'm happy to accept this and move it forward. I would personally add a (small) disclaimer about the fact that this software operates under the maternal only model, just so that users are aware of it.
@lpantano please move this paper forward.

**Comment by pjotrp** [comment]
Haha, don't close just yet :)

**Comment by lpantano** [comment]
Thanks so much for the review @jdeligt!

@mikldk, do you think you could add a note as @jdeligt mentioned? I think is a good point.

I will move this forward after that.

Thanks!

**Comment by mikldk** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01266/joss.01266/10.21105.joss.01266.pdf)

**Comment by lpantano** [comment]
Hey @mikldk, 

did you add the note as @jdeligt mentioned? if you so, can you comment with the commit here, so I can follow up?

Thanks!

**Comment by mikldk** [comment]
Thanks, @jdeligt, @pjotrp and @lpantano. I have now added the note "This software operates under the maternal inheritance only model, i.e. that mtDNA is only passed on by mothers to children." in both `README.md` and `paper.md`. I have also deleted the old release and made a new: <https://github.com/mikldk/mitolina/releases>. I have also added Zenodo, and this new release has DOI: <https://doi.org/10.5281/zenodo.2574140>.

**Comment by mikldk** [comment]
@lpantano , yes indeed. I just wanted to check the proof before I wrote you :-). The note was added in mikldk/mitolina@ae28a61f9c137fe1574ba0d59f320b6ff6414069.

**Comment by lpantano** [comment]
Thanks so much! I will proceed with the acceptance in 1 hour.

**Comment by pjotrp** [comment]
One of the fastest reviews ever :+1:

**Comment by mikldk** [comment]
Indeed! Thanks for the splendid service!

**Comment by lpantano** [comment]
@whedon set https://doi.org/10.5281/zenodo.2574140 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2574140" target="_blank">10.5281/zenodo.2574140</a> is the archive.

**Comment by lpantano** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1371/journal.pgen.1007028 is OK
- http://doi.org/10.1371/journal.pgen.1007774 is OK
- http://doi.org/10.1016/j.fsigen.2012.11.004 is OK
- http://doi.org/10.1016/j.jtbi.2013.03.009 is OK
- http://doi.org/10.7287/peerj.preprints.3188v1 is OK
- http://doi.org/10.1016/j.ajhg.2009.05.001 is OK
- http://doi.org/10.1093/molbev/msu222 is OK
- http://doi.org/10.1038/s41598-017-05673-7 is OK
- http://doi.org/10.21105/joss.00684 is OK
- http://doi.org/10.1016/j.fsigen.2014.09.021 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/513

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/513, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by lpantano** [comment]
Hi @pjotrp, 

all is good, should you do the deposit, or I do?

Thanks!

**Comment by labarba** [comment]
(We don't remove the "review" label.)

**Comment by labarba** [comment]
:wave @mikldk — Could you edit the metadata of your Zenodo archive so it matches the title of the JOSS paper? Thanks.

**Comment by labarba** [comment]
You may also want to add case protection with `{}` to the bibtex entry for Butler (2009), so you get _DNA_ instead of _dna_.

**Comment by lpantano** [comment]
@labarba, is the metadata to change the one that is saying now: `mikldk/mitolina: v0.0.1`? (just to learn for the next time) and (sorry about the label).

**Comment by labarba** [comment]
Yes: the title of the Zenodo archive matching the title of the JOSS paper.

**Comment by labarba** [comment]
(Authors often need to be manually edited, too, as Zenodo automatically lists everyone who has a commit.)

**Comment by mikldk** [comment]
@lpantano @labarba I'll look at Zenodo metadata. And the reference. And recompile paper. I guess I should then delete Github release and make a new afterwards?

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01266/joss.01266/10.21105.joss.01266.pdf)

**Comment by mikldk** [comment]
@lpantano @labarba : I have updated `paper.bib`, deleted the old release and created a new. The new DOI at Zenodo is [10.5281/zenodo.2574400](https://doi.org/10.5281/zenodo.2574400). I have changed the Zenodo title at <https://zenodo.org/record/2574400>. I hope I have done everything right?

**Comment by labarba** [comment]
ah! No need to get a new DOI at Zenodo, but alright!

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.2574400 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2574400" target="_blank">10.5281/zenodo.2574400</a> is the archive.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1371/journal.pgen.1007028 is OK
- http://doi.org/10.1371/journal.pgen.1007774 is OK
- http://doi.org/10.1016/j.fsigen.2012.11.004 is OK
- http://doi.org/10.1016/j.jtbi.2013.03.009 is OK
- http://doi.org/10.7287/peerj.preprints.3188v1 is OK
- http://doi.org/10.1016/j.ajhg.2009.05.001 is OK
- http://doi.org/10.1093/molbev/msu222 is OK
- http://doi.org/10.1038/s41598-017-05673-7 is OK
- http://doi.org/10.21105/joss.00684 is OK
- http://doi.org/10.1016/j.fsigen.2014.09.021 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/514

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/514, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/515
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01266](https://doi.org/10.21105/joss.01266)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @mikldk, your paper is published!

Big thanks to the handling editor, @lpantano, and the reviewer, @jdeligt 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01266/status.svg)](https://doi.org/10.21105/joss.01266)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01266">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01266/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01266/status.svg
   :target: https://doi.org/10.21105/joss.01266
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01266/status.svg)](https://doi.org/10.21105/joss.01266)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by mikldk** [comment]
Thank you all!
