### ISSUE TITLE
[PRE REVIEW]: NiBetaSeries: task related correlations in fMRI

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1267]
**Submitting author:** @jdkent (<a href="http://orcid.org/0000-0002-4892-2659">James Kent</a>)
**Repository:** <a href="https://github.com/HBClab/NiBetaSeries" target ="_blank">https://github.com/HBClab/NiBetaSeries</a>
**Version:** v0.2.3
**Editor:** @arokem
**Reviewers:** snastase

**Author instructions**

Thanks for submitting your paper to JOSS @jdkent. The JOSS editor @arokem, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jdkent if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@arokem) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @arokem - the submitting author suggested you as the handling editor and this looks like a pretty good fit I think?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01267/joss.01267/10.21105.joss.01267.pdf)

**Comment by arokem** [comment]
Sure. I can take this one. 

@jdkent: do you have any ideas for good reviewers for this paper?

**Comment by jdkent** [comment]
Thanks @arokem!
Here are a few (in no particular order):
mnarayan
snastase
effigies

**Comment by arokem** [comment]
Hey @snastase : would you be willing to review this paper for JOSS?

**Comment by snastase** [comment]
@arokem Sure—will do. Hopefully will be able to get to it next week.

**Comment by arokem** [comment]
@whedon assign snastase as reviewer

**Comment by whedon** [comment]
OK, the reviewer is snastase

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1295. Feel free to close this issue now!

**Comment by arokem** [comment]
Thanks @snastase! Head on over to #1295 for the review checklist. I'll close this one now.

**Comment by jdkent** [comment]
Thank you @aroekm and @snastase!
