### ISSUE TITLE
[PRE REVIEW]: uJVM: Lightweight Java Virtual Machine for embedded systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1268]
**Submitting author:** @omoliavko (<a href="http://orcid.org/0000-0003-3167-983X">Oleksandr Moliavko</a>)
**Repository:** <a href="https://github.com/Samsung/uJVM/" target ="_blank">https://github.com/Samsung/uJVM/</a>
**Version:** v0.1
**Editor:** @gkthiruvathukal
**Reviewers:** @morganericsson, @hainesr

**Author instructions**

Thanks for submitting your paper to JOSS @omoliavko. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@omoliavko if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1268 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    171      0 --:--:-- --:--:-- --:--:--   173
Could not find bibliography file: 
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @omoliavko - please review the submission guidelines on how to prepare your JOSS paper. In particular, your paper doesn't seem to have an associated bibtex file: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by omoliavko** [comment]
Hello, as of now we don't have any publications regarding uJVM; therefore, we can't provide any bibtex file. Is it strictly necessary for publication? If yes, can we provide empty bibtex file?

**Comment by arfon** [comment]
You don't need to cite publications, you should move what you currently have in this section into the bibtex file and cite accordingly: https://github.com/Samsung/uJVM/blob/master/docs/joss/paper.md#references

Also, any related work should be cited too.

**Comment by omoliavko** [comment]
Thank you for quick answer; we'll prepare related works list and add bibtex file with citations ASAP

**Comment by omoliavko** [comment]
Hello, I've created a separate paper.bib file with references to materials we've used during uJVM development and updated paper.md file accordingly.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1268 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    104      0 --:--:-- --:--:-- --:--:--   105
Could not find bibliography file: 
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@omoliavko - please merge this PR: https://github.com/Samsung/uJVM/pull/63

Also, you need to cite the entries in your bibtex directly please. (You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html))

**Comment by omoliavko** [comment]
Merge done; also, I've updated reference marks in paper.md

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01268/joss.01268/10.21105.joss.01268.pdf)

**Comment by arfon** [comment]
Great, thanks for your work getting the paper to compile. Reading this paper, it's not immediately clear to me what the research challenge is that you're addressing here. 

Quoting from our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements):

> - The software should have an obvious research application
> - You should be a major contributor to the software you are submitting
> - The software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler)
> - The software should be feature complete (no half-baked solutions) and designed for maintainable extension (not one-off modifications). Minor ‘utility’ packages, including ‘thin’ API clients, are not acceptable.

Could you say a little more in your paper about what sort of research challenges this software is designed to address.

Also, I'm cc-ing @gkthiruvathukal who I think would be a good editor for this submission.

**Comment by omoliavko** [comment]
Many thanks for your patience in explaining how to make paper valid. I've updated the text to explain potential research application in a bit more detail.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01268/joss.01268/10.21105.joss.01268.pdf)

**Comment by arfon** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by omoliavko** [comment]
Is there something I need to do for paper review to actually start or I should just wait for assigned reviewer?

**Comment by gkthiruvathukal** [comment]
@omoliavko  In looking more closely at the review criteria at https://joss.readthedocs.io/en/latest/review_criteria.html, I was wondering whether you either comment on or reviews your paper to include how your contribution addresses "any ongoing research projects using the software or recent scholarly publications enabled by it."

**Comment by omoliavko** [comment]
@gkthiruvathukal I've rewritten the part of article regarding potential research applications of uJVM. Could you please take another look at it?

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01268/joss.01268/10.21105.joss.01268.pdf)

**Comment by gkthiruvathukal** [comment]
@omoliavko Thanks for responding and addressing my issue. Do you have any suggestions for reviewers from this list? https://bit.ly/joss-reviewers

**Comment by omoliavko** [comment]
Based on data from the list, I think the following could be reviewers for paper: hainesr, jizecn, adavidzh, dvysardana.
I've updated the paper text by extending list of supported H/W and RTOSes, but it should not have significant effect on research-related aspects.

**Comment by gkthiruvathukal** [comment]
@hainesr Would you be willing to contribute a review for JOSS on this submission? This submission seems closely related to your areas of expertise and interest.

**Comment by omoliavko** [comment]
@hainesr If you have any questions or if I can assist you in some way regarding my submission, please do not hesitate to contact me.

**Comment by gkthiruvathukal** [comment]
@jizecn and @adavidzh: Would either or both of you be willing to contribute a review for JOSS on this submission? I haven't heard back from @hainesr yet. Please let me know so we can begin review of this submission.

**Comment by adavidzh** [comment]
@gkthiruvathukal: thanks for thinking of me. I'll have to pass as I have two ongoing reviews and JVM is not my specialty.

**Comment by gkthiruvathukal** [comment]
@dvysardana, would you be willing to contribute a review to this JOSS submission? @jizecn, we can use two reviewers, so please let me know if you are willing, too.

**Comment by gkthiruvathukal** [comment]
@jmkim and @morganericsson, would either or both of you be willing to contribute a review to this JOSS submission? As you can see in this issue thread, I have asked others who are either not available or have not responded. Both of you have Java listed and systems/software engineering interests, so I think this submission would be of interest to you.

**Comment by morganericsson** [comment]
Yes, I can do that.

**Comment by hainesr** [comment]
Apologies @gkthiruvathukal, I've been on leave and am only just catching up. Do you still need my input on this?

**Comment by gkthiruvathukal** [comment]
@hainesr Hope you had a great/productive leave. I definitely need your help. Upon hearing from you, I will assign you and @morganericsson as reviewers and start review.

**Comment by hainesr** [comment]
OK, I'm now at a workshop through until Friday but I'll try and have a look at this ASAP to see if I am capable of reviewing it.

**Comment by gkthiruvathukal** [comment]
Thanks, @hainesr. I will make the assignments and start review. We always work with the reviewers and their schedules, so your timeframe is fine. Thanks for agreeing to contribute a review. I will assign you and @morganericsson and start review.

**Comment by gkthiruvathukal** [comment]
@whedon assign @morganericsson as reviewer
@whedon add @hainesr as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @morganericsson

**Comment by gkthiruvathukal** [comment]
@whedon add @hainesr as reviewer

**Comment by whedon** [comment]
OK, @hainesr is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by gkthiruvathukal** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1338. Feel free to close this issue now!
