### ISSUE TITLE
[PRE REVIEW]: tsfeaturex: An R Package for Automating Time Series Feature Extraction

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1270]
**Submitting author:** @nelsonroque (<a href="http://orcid.org/0000-0003-1184-202X">Nelson Roque</a>)
**Repository:** <a href="https://github.com/nelsonroque/tsfeaturex" target ="_blank">https://github.com/nelsonroque/tsfeaturex</a>
**Version:** v.0.3.6
**Editor:** @xuanxu
**Reviewers:** @acolum, @aj2duncan

**Author instructions**

Thanks for submitting your paper to JOSS @nelsonroque. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@nelsonroque if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01270/joss.01270/10.21105.joss.01270.pdf)

**Comment by arfon** [comment]
:wave: @xuanxu - would you be willing to edit this submission for JOSS?

**Comment by xuanxu** [comment]
@arfon sure!

**Comment by arfon** [comment]
Great! Next you need to type `@whedon assign @xuanxu as editor`, then look for some reviewers...

**Comment by xuanxu** [comment]
@whedon assign @xuanxu as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by xuanxu** [comment]
👋  @acolum, @aj2duncan: Would you be willing to review this paper? I think your expertise in R and math makes both of you a great fit for this submission. 
I think one reviewer is enough to get this started, but it would be great to have the two of you reviewing it.

**Comment by acolum** [comment]
Hi @xuanxu, thank you, and I'm willing to review this paper.

**Comment by xuanxu** [comment]
Thanks @acolum! I will assign you now. 
I'll give some more time for a response from @aj2duncan to have a second reviewer and then start the review issue soon.

**Comment by xuanxu** [comment]
@whedon assign @acolum as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @acolum

**Comment by aj2duncan** [comment]
Hi @xuanxu, happy to review this too.

**Comment by xuanxu** [comment]
@whedon add @aj2duncan as reviewer

**Comment by whedon** [comment]
OK, @aj2duncan is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1279. Feel free to close this issue now!

**Comment by xuanxu** [comment]
@acolum, @aj2duncan, please head over to #1279 for the actual review
