### ISSUE TITLE
[PRE REVIEW]: JuliaCall: an R package for seamless integration between R and Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1271]
**Submitting author:** @Non-Contradiction (<a href="http://orcid.org/0000-0001-7022-0947">Changcheng Li</a>)
**Repository:** <a href="https://github.com/Non-Contradiction/JuliaCall" target ="_blank">https://github.com/Non-Contradiction/JuliaCall</a>
**Version:** v0.16.4
**Editor:** @leouieda
**Reviewers:** @matbesancon, @aguang

**Author instructions**

Thanks for submitting your paper to JOSS @Non-Contradiction. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Non-Contradiction if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01271/joss.01271/10.21105.joss.01271.pdf)

**Comment by arfon** [comment]
:wave: @leouieda - would you be willing to edit this submission for JOSS?

**Comment by leouieda** [comment]
@arfon sure, I'd be happy to do it :+1: 

I'll look through the reviewer list to see if anyone has R and Julia experience. @Non-Contradiction let me know if you have any suggestions for reviewers. There is [a list of potential reviewers here](https://bit.ly/joss-reviewers).

**Comment by danielskatz** [comment]
@whedon assign @leouieda as editor

**Comment by whedon** [comment]
OK, the editor is @leouieda

**Comment by leouieda** [comment]
:wave: Hi @ChrisRackauckas @Aguang @matbesancon @r-barnes @nhejazi @dmbates would any of you be interested in reviewing this submission for JOSS?

**Comment by matbesancon** [comment]
Yes I can review this submission

**Comment by ChrisRackauckas** [comment]
I won't be able to review until sometime in April.

**Comment by aguang** [comment]
I can also review

**Comment by dmbates** [comment]
I can also review.

**Comment by leouieda** [comment]
@matbesancon @aguang @dmbates thank you for agreeing to review! :tada: @ChrisRackauckas no worries since we have 3 reviewers already.

**Comment by leouieda** [comment]
@dmbates initially we only need 2 reviewers so I'll go with the order of response. Thank you for volunteering and I'll keep you in mind if we need a third reviewer (if that's ok with you).

**Comment by leouieda** [comment]
@whedon assign @matbesancon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @matbesancon

**Comment by leouieda** [comment]
@whedon add @aguang as reviewer

**Comment by whedon** [comment]
OK, @aguang is now a reviewer

**Comment by dmbates** [comment]
> @dmbates initially we only need 2 reviewers so I'll go with the order of response. Thank you for volunteering and I'll keep you in mind if we need a third reviewer (if that's ok with you).

Certainly.  Thanks for letting me know.

**Comment by leouieda** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1284. Feel free to close this issue now!

**Comment by leouieda** [comment]
@matbesancon @aguang  @Non-Contradiction the review will take place in #1284. Please feel free to ping me at any time if you have questions. 

@matbesancon @aguang there are instructions in the issue and a link to our review guidelines. When you open issues and/or pull requests in the software repo, please link back to the review issue so we can keep track of progress by including `openjournals/joss-reviews#1284` in the text.
