### ISSUE TITLE
[REVIEW]: The Climate Equity Reference Calculator

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1273]
**Submitting author:** @krueschan (<a href="http://orcid.org/0000-0003-0722-1044">Christian Holz</a>)
**Repository:** <a href="https://github.com/climateequityreferenceproject/cerc-web" target ="_blank">https://github.com/climateequityreferenceproject/cerc-web</a>
**Version:** v3.2.2
**Editor:** @jedbrown
**Reviewer:** @mtobis
**Archive:** <a href="https://doi.org/10.5281/zenodo.2592644" target="_blank">10.5281/zenodo.2592644</a>

## Status

[![status](http://joss.theoj.org/papers/3a39361da648816fccf17af893b2b440/status.svg)](http://joss.theoj.org/papers/3a39361da648816fccf17af893b2b440)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/3a39361da648816fccf17af893b2b440"><img src="http://joss.theoj.org/papers/3a39361da648816fccf17af893b2b440/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/3a39361da648816fccf17af893b2b440/status.svg)](http://joss.theoj.org/papers/3a39361da648816fccf17af893b2b440)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/climateequityreferenceproject/cerc-web" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mtobis, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @jedbrown know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/climateequityreferenceproject/cerc-web">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v3.2.2
- [x] **Authorship:** Has the submitting author (@krueschan) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mtobis it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01273/joss.01273/10.21105.joss.01273.pdf)

**Comment by jedbrown** [comment]
@mtobis :wave: Welcome and thanks for agreeing to review! The comments from @whedon above outline the review process, which takes place in this thread (possibly with issues filed in the project repository). I'll be watching this thread if you have any questions.

I ran the docker image locally via
```
$ docker pull climateequityreferenceproject/cerc-web
$ docker run -it --rm -p 8080:80 climateequityreferenceproject/cerc-web bash
root@c941332d432f:/var/www/cerc-web/public_html# dumb-init /start.sh
```
and pointing my browser to `localhost:8080`, which I think is sufficient to demonstrate that this system (or a derivative thereof) can indeed by hosted by external researchers.

**Comment by krueschan** [comment]
@whedon set v3.2.1 as version

**Comment by whedon** [comment]
I'm sorry @krueschan, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by krueschan** [comment]
That's ok @whendon, I'll ask one of the humans to do it. @jedbrown or @mtobis, can you please `@whedon set v3.2.1 as version`? Thanks.

**Comment by krueschan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01273/joss.01273/10.21105.joss.01273.pdf)

**Comment by mtobis** [comment]
I think the "installation" question is ambiguous in the present case. The end user is not expected to be able to run the code on their own machine, but only to interact with the system through a web interface. Thus I am treating "installation" as meaning "ability to attain functionality", rather than "ability to replicate the service". I think the latter may present some difficulties.

(My attempt to do "docker run" per Jed's message did not work. A server was instantiated but it did not respond.)

I think it would have been better to make clear that the code is in php in the html directory. I spent some time trying to figure out where in my docker image it was and how to get it out!

**Comment by mtobis** [comment]
Is this the full paper? 

https://github.com/openjournals/joss-papers/blob/joss.01273/joss.01273/10.21105.joss.01273.pdf

I see only a summary and a reference section.

**Comment by jedbrown** [comment]
Thanks, @mtobis.

This is a typical length for a JOSS "paper"; it is not meant to duplicate project documentation, which should be sufficiently complete to enable research using the software.

I'm okay with the present state of installation; having reproduced it locally, I think someone who wishes to run/extend the software (e.g., with new data or alternate analysis methods) would be able to get it working. I'm sure the technical issue you experienced with the docker container is resolvable in principle and won't ask you to spend further time on it.

**Comment by mtobis** [comment]
This work is essentially a web wrapper around https://sourceforge.net/p/gdrs/code/HEAD/tree/gdrsclib/

Let me state categorically that this is very important work and it should be available and documented.

I am not sure whether that sourceforge tree is considered part of the review. I gather it is not.

I believe my job here is to validate the suitability of this submission for JOSS, not its importance to the world, so unfortunately I hit some snags.

* Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

- I defer to Jed on this, so it's okay.

*  Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

- There is fairly extensive online documentation, but it can't obviously be accessed until some parameters are chosen. It would be better if the help page were the landing page. To my initial exploration no use case examples are provided. This could definitely be improved with modest effort.

*  Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

- Yes, if 1) sourceforge link is considered and 2) the theoretical basis for the calculations is considered sufficient (The actual algorithmic basis is straightforward.)

*  Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?

- Assuming this is a review only of the wrapper and not of the underlying calculations, the testing presumably is a rather trivial comparison between a few use cases. This could be automated in principle, but I'd be quite confident in this case with manual tests.

  Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

- As a one-off wrapper around a specific code base, scope for contribution is very limited so this is moot. I did not notice a way to report issues or seek support, but again I rather doubt that such issues would arise regarding the wrapper code.

All but one of these issues are not really consequential for the intended uses of the code. I have checked off everything except "example usage". 

I strongly recommend altering the code so that a first time user can see the documentation without plunging into parameter choices, and that the online documentation be extended with use cases and user stories.

**Comment by mtobis** [comment]
Oh, sorry markdown mangled my bullets. Apologies. The above bulleted items were intended to come in pairs with two bullet styles: alternating between the requirement and my comment.

**Comment by krueschan** [comment]
Thanks very much for the review, @mtobis. Below are responses/further questions:

> I am not sure whether that sourceforge tree is considered part of the review. I gather it is not.

Correct, that is the intention.

> * Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems). 
>   * There is fairly extensive online documentation, but it can't obviously be accessed until some parameters are chosen. It would be better if the help page were the landing page. To my initial exploration no use case examples are provided. This could definitely be improved with modest effort.

The current design, where the "equity splash screen" is shown first that shows the most salient parameters and a sub-set of parameters for them was the result of feedback from end-users who felt overwhelmed if presented with the full complement of settings on first loading the calculator. The settings on the splash screen are documented through extensive glossary entries (I hope the links to glossary entries are identifiable as links, e.g. that clicking "Historical Responsibility" brings up a substantial glossary entry explaining the concept as used here?). So even upon first loading the calculator, the user has access to the documentation of the specific parameter choices presented to them at that stage, which feels perhaps sufficient to me - what else would you expect at this stage?

As far as use cases are concerned, we considered the literature that is references in the manuscript (Adow, Ware, & Viita, 2018; CSO Equity Review, 2015, 2016, 2017, 2018; Holz
et al., 2018; Kartha, Holz, & Athanaisou, 2018; Metcalfe, 2015; Richards, Wollenberg, &
van Vuuren, 2018) 

> * Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?
>   * Assuming this is a review only of the wrapper and not of the underlying calculations, the testing presumably is a rather trivial comparison between a few use cases. This could be automated in principle, but I'd be quite confident in this case with manual tests.

Happy to provide manual test cases but I have no idea how I would go about them. Can you point me to an example repository that does that? Or some other relevant documentation?

> * Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
>   * As a one-off wrapper around a specific code base, scope for contribution is very limited so this is moot. I did not notice a way to report issues or seek support, but again I rather doubt that such issues would arise regarding the wrapper code.

The repository has a CONTRIBUTING.md file and the calculator itself has a "Please send feedback" link at the bottom of each page.

> I strongly recommend altering the code so that a first time user can see the documentation without plunging into parameter choices, and that the online documentation be extended with use cases and user stories.

Thanks for the suggestion and see my comments above. I am thinking of adding a line of text on top of the "equity splash screen" that points the first time user to a general introduction of our approach, i.e. this page: https://climateequityreference.org/about-the-climate-equity-reference-project-effort-sharing-approach/ 
This could look like this:
![splash screen with intro](https://climateequityreference.org/files/splash_screen_intro.png)
Do you think that would sufficiently address your concerns?

**Comment by mtobis** [comment]
yes that would be an adequate and easy fix

**Comment by krueschan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1273 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    105      0 --:--:-- --:--:-- --:--:--   105
Error reading bibliography ./paper.bib (line 116, column 2):
unexpected "@"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by krueschan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01273/joss.01273/10.21105.joss.01273.pdf)

**Comment by krueschan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01273/joss.01273/10.21105.joss.01273.pdf)

**Comment by krueschan** [comment]
> yes that would be an adequate and easy fix

Ok. @mtobis - I have done this now.

**Comment by krueschan** [comment]
> > yes that would be an adequate and easy fix
> 
> Ok. @mtobis - I have done this now.

P.S. the textbox is displayed in collapsed state if the user has a 'db' cookie set, which identifies them to not be first time users, so delete this cookie to get the full first time user experience.

**Comment by krueschan** [comment]
@mtobis , just checking if, as far as you're concerned, your comments regarding
> Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems). 

are now resolved with the recent changes as described above? If so, I think the review process probably expects you to tick the appropriate check box in the checklist on the top of the page, if not, that would be good to know so I can figure out what else to do.

**Comment by mtobis** [comment]
Yes. I have signed off on all checkboxes. Again I think this is important work. Thanks for doing it and my apologies for slow response as I am traveling,

**Comment by jedbrown** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by jedbrown** [comment]
Thanks, @mtobis.

@krueschan It looks like all but the first "missing DOI" is buggy. (This experimental whedon feature needs work.) Can you check that first one?  Can you also check capitalization in references? I think `{Paris Agreement}` needs to be protected in multiple cases.

**Comment by krueschan** [comment]
Thanks @jedbrown. That first one is wrong too. Just a book chapter by the same name (and from the same authors) as the book that I am citing, so my citation is fine as is. I have protected the `{Paris Agreement}` as suggested and checked for other examples of capitalization and found a few more. Thanks. Looks like the whedon doi guessing experimental feature is at least as buggy as Mendeley's, though much less intrusive. 

Can you also please `@whedon set v3.2.2 as version`, please?

**Comment by krueschan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01273/joss.01273/10.21105.joss.01273.pdf)

**Comment by krueschan** [comment]
found and fixed another minor issue with the bibliography.

@whedon generate pdf

**Comment by krueschan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01273/joss.01273/10.21105.joss.01273.pdf)

**Comment by jedbrown** [comment]
@whedon set v3.2.2 as version

**Comment by whedon** [comment]
OK. v3.2.2 is the version.

**Comment by jedbrown** [comment]
@krueschan Can you confirm that Sivan Kartha meets the authorship guidelines with respect to this software? https://joss.readthedocs.io/en/latest/submitting.html#authorship  (I ask because there are no commits authored by him.)

After confirmation, please archive the software at Zenodo or similar and report the DOI here.

**Comment by krueschan** [comment]
Yes, I confirm that Sivan absolutely meets the authorship guidelines. 
The Zenodo archive DOI is 10.5281/zenodo.2592644

**Comment by jedbrown** [comment]
@whedon set 10.5281/zenodo.2592644 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2592644" target="_blank">10.5281/zenodo.2592644</a> is the archive.

**Comment by jedbrown** [comment]
@openjournals/joss-eics Over to you.

**Comment by labarba** [comment]
Small editorial fix in the last paragraph:

“In research by the authors and others, most recently in (Adow … ) among other pieces” >> when you use the citation as part of speech in a sentence, you need to use in-text citation; see:  https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.htm#citation_syntax

Also, comma after “e.g.” in parenthetical a bit later.

**Comment by krueschan** [comment]
Ok, good points, thanks.
I fixed it, though using a different approach than you suggested, by joining putting parts of the sentence into the parenthesis with the citations. Also, the comma after e.g.

**Comment by krueschan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01273/joss.01273/10.21105.joss.01273.pdf)

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/556

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/556, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/s10784-017-9371-z is OK
- 10.1002/wcc.201 is OK
- 10.5281/zenodo.1748847 is OK
- 10.1038/nclimate2826 is OK
- 10.1038/nclimate3186 is OK
- 10.1016/j.envsci.2017.04.020 is OK
- 10.7910/DVN/O3H22Z is OK
- 10.7910/DVN/RIBJXF is OK
- 10.6084/m9.figshare.5917399 is OK
- 10.6084/m9.figshare.5917402 is OK
- 10.6084/m9.figshare.5917408 is OK
- 10.6084/m9.figshare.7637669 is OK
- 10.1080/14693062.2018.1430018 is OK
- 10.5281/zenodo.2590636 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-531-92258-4_12 may be missing for title: The Greenhouse Development Rights Framework. The Right to Development in a Climate Constrained World, Second Edition
- https://doi.org/10.2139/ssrn.3279932 may be missing for title: The Greenhouse Development Rights and Climate Equity Reference Calculator Engine
- https://doi.org/10.1007/978-3-319-69772-7 may be missing for title: Norway’s Fair Share of Meeting the Paris Agreement
- https://doi.org/10.4324/9781315103358-12 may be missing for title: Climate Inequality in the Commonwealth: A Call for Urgent Action
- https://doi.org/10.4135/9781483351384.n48 may be missing for title: Special Report on the Impacts of Global Warming of 1.5°C Above Pre-Industrial Levels and Related Global Greenhouse Gas Emission Pathways, in the Context of Strengthening the Global Response to the Threat of Climate Change, Sustainable Development, and Efforts to Eradicate Poverty
- https://doi.org/10.1007/978-1-4302-0172-4_1 may be missing for title: SQLite (Version 3)
- https://doi.org/10.4135/9781473975101 may be missing for title: Paris Agreement
- https://doi.org/10.2139/ssrn.3286257 may be missing for title: Synthesis Report on the Aggregate Effect of the Intended Nationally Determined Contributions
- https://doi.org/10.1007/springerreference_29771 may be missing for title: The Emissions Gap Report 2015
- https://doi.org/10.1186/s12939-017-0700-1 may be missing for title: Fast, Fair Climate Action Crucial for Health and Equity

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/557
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01273](https://doi.org/10.21105/joss.01273)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @krueschan, your JOSS paper is published!

Big thanks to the editor: @jedbrown, and reviewer: @mtobis 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01273/status.svg)](https://doi.org/10.21105/joss.01273)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01273">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01273/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01273/status.svg
   :target: https://doi.org/10.21105/joss.01273
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01273/status.svg)](https://doi.org/10.21105/joss.01273)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by krueschan** [comment]
Thanks very much, @jedbrown @mtobis @labarba and of course @whedon for this smooth review experience.

**Comment by arfon** [comment]
@editorialbot reaccept

**Comment by arfon** [comment]
@editorialbot reaccept

**Comment by mtobis** [comment]
No idea what this is all about. Please leave me off the distribution, at
least until you get it sorted.

mt

**Comment by jedbrown** [comment]
@mtobis Sorry about this -- we'll figure out a better workflow for the future. I can't remove you from the issue, but you can click unsubscribe in the right margin.

![image](https://github.com/openjournals/joss-reviews/assets/3303/eda6377e-be39-4239-951c-d4f0b8fe3c68)
