### ISSUE TITLE
[PRE REVIEW]: Ecological Metadata as Linked Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1274]
**Submitting author:** @cboettig (<a href="http://orcid.org/0000-0002-1642-628X">Carl Boettiger</a>)
**Repository:** <a href="https://github.com/ropensci/emld" target ="_blank">https://github.com/ropensci/emld</a>
**Version:** 0.2.0
**Editor:** @usethedata
**Reviewers:** @usthedata

**Author instructions**

Thanks for submitting your paper to JOSS @cboettig. **Currently, there isn't an JOSS editor assigned** to your paper.

@cboettig if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01274/joss.01274/10.21105.joss.01274.pdf)

**Comment by arfon** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by arfon** [comment]
Cross-linking with rOpenSci here: https://github.com/ropensci/software-review/issues/269

**Comment by usethedata** [comment]
@whedon assign @usthedata as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @usthedata

**Comment by usethedata** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1276. Feel free to close this issue now!

**Comment by usethedata** [comment]
Closing issue with review started
