### ISSUE TITLE
[PRE REVIEW]: PoreSpy: A Python Toolkit for Quantitative Analysis of Porous Media Images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1275]
**Submitting author:** @jgostick (<a href="http://orcid.org/0000-0001-7736-7124">Jeff Gostick</a>)
**Repository:** <a href="https://github.com/PMEAL/porespy" target ="_blank">https://github.com/PMEAL/porespy</a>
**Version:** V1.0.0
**Editor:** @usethedata
**Reviewers:** @yxqd, @cr458

**Author instructions**

Thanks for submitting your paper to JOSS @jgostick. **Currently, there isn't an JOSS editor assigned** to your paper.

@jgostick if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #1275 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
:wave: @jgostick - thanks for your submission to JOSS. There are a few issues that need fixing before we can proceed to assign a handling editor:

1. Please add an open source license to this repository
2. Please write a paper to accompany your submission. [This section](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) of our docs should help.

**Comment by jgostick** [comment]
I'm sorry, I thought I'd done this.  I added all this to the Master branch, but the default branch on github was the dev branch, so perhaps that was the issues?  Anyway, I have changed the default to master and updated the version number to V1.0.1.  Do I need to tell the system to look at this new tag?  If so, how?

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1275 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1275/paper.md): did not find expected key while parsing a block mapping at line 32 column 4 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
There is some extra space before the name associated with affil 2.  Please remove it.  You can also regenerate the pdf yourself by entering ```@whedon generate pdf``` as a new comment here.

**Comment by jgostick** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01275/joss.01275/10.21105.joss.01275.pdf)

**Comment by danielskatz** [comment]
The third-to-last reference could use some work on the author names.

**Comment by danielskatz** [comment]
👋 @usethedata - would you be willing to act as editor for this submission?

**Comment by jgostick** [comment]
@danielskatz I already caught that problem in the references and have re-pushed.  Will regenerate now.  Thanks for your help.

**Comment by jgostick** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01275/joss.01275/10.21105.joss.01275.pdf)

**Comment by jgostick** [comment]
From looking at the list, PingjunChen and Alanocallaghan look like the only fully qualified reviewers.

**Comment by usethedata** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by usethedata** [comment]
👋 @yxqd and @cr458 would you be willing to review this paper?

**Comment by cr458** [comment]
@usethedata yup would be happy to!

**Comment by yxqd** [comment]
@usethedata yes I can help

**Comment by usethedata** [comment]
@whedon assign @yxqd as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @yxqd

**Comment by usethedata** [comment]
@whedon add @cr458 as reviewer

**Comment by whedon** [comment]
OK, @cr458 is now a reviewer

**Comment by usethedata** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1296. Feel free to close this issue now!

**Comment by usethedata** [comment]
Closing pre-review issue with review started.
