### ISSUE TITLE
[PRE REVIEW]: tacmagic: PET Analysis in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1280]
**Submitting author:** @eebrown (<a href="http://orcid.org/0000-0002-1575-2606">Eric E. Brown</a>)
**Repository:** <a href="https://github.com/ropensci/tacmagic" target ="_blank">https://github.com/ropensci/tacmagic</a>
**Version:** v0.2.0
**Editor:** @danielskatz
**Reviewers:** @danielskatz

**Author instructions**

Thanks for submitting your paper to JOSS @eebrown. **Currently, there isn't an JOSS editor assigned** to your paper.

@eebrown if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by danielskatz** [comment]
👋 @arokem - the author suggested you as the editor for this submission.  Are you willing to take it on?

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01280/joss.01280/10.21105.joss.01280.pdf)

**Comment by danielskatz** [comment]
@eebrown - you need to add a LICENSE to the repository - If needed, see https://choosealicense.com

**Comment by eebrown** [comment]
Hello, thanks for processing this JOSS submission. @danielskatz it is licenced under GPL-3. I can add a LICENCE file.

 I was told to note:

This submission has been accepted to rOpenSci. The review thread can be found at https://github.com/ropensci/software-review/issues/280

**Comment by danielskatz** [comment]
Thanks - that will make this a fast process.

**Comment by eebrown** [comment]
I have added a LICENSE file to the repository.

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @danielskatz

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1281. Feel free to close this issue now!
