### ISSUE TITLE
[PRE REVIEW]: ChiRP: Chinese Restaurant Process Mixtures for Regression and Clustering

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1283]
**Submitting author:** @stablemarkets (<a href="http://orcid.org/0000-0002-0437-4611">Arman Oganisian</a>)
**Repository:** <a href="https://github.com/stablemarkets/ChiRP" target ="_blank">https://github.com/stablemarkets/ChiRP</a>
**Version:** 1.0.0
**Editor:** @pjotrp
**Reviewers:** @agisga

**Author instructions**

Thanks for submitting your paper to JOSS @stablemarkets. **Currently, there isn't an JOSS editor assigned** to your paper.

@stablemarkets if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by danielskatz** [comment]
👋 @eramirem - the authors requested you as the editor of this submission.  Are you willing to do so?

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1283 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    201      0 --:--:-- --:--:-- --:--:--   202
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.01283.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
@arfon - I'm unsure what's happening here with the paper - Can you check?

**Comment by stablemarkets** [comment]
Hi Daniel. I forgot to include a .png file that was called in paper.md. Maybe that was causing a compilation error? I fixed it now so that my paper.md, paper.bib, and the figure are all in the paper/ subdirectory of my GitHub repo. Maybe it will work now.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01283/joss.01283/10.21105.joss.01283.pdf)

**Comment by danielskatz** [comment]
thanks

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01283/joss.01283/10.21105.joss.01283.pdf)

**Comment by danielskatz** [comment]
@pjotrp - Do you think your group can edit this?

**Comment by pjotrp** [comment]
Yes. @agisga, this looks like something of interest to you. Can you take a look at above paper and see if you can review it?

**Comment by agisga** [comment]
@pjotrp Yes, I would be happy to do the review. Please let me know if there any specific instructions for referees that I need to follow.

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@whedon assign @agisga as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @agisga

**Comment by pjotrp** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1287. Feel free to close this issue now!
