### ISSUE TITLE
[REVIEW]: JuliaCall: an R package for seamless integration between R and Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1284]
**Submitting author:** @Non-Contradiction (<a href="http://orcid.org/0000-0001-7022-0947">Changcheng Li</a>)
**Repository:** <a href="https://github.com/Non-Contradiction/JuliaCall" target ="_blank">https://github.com/Non-Contradiction/JuliaCall</a>
**Version:** v0.16.5
**Editor:** @leouieda
**Reviewer:** @matbesancon, @aguang
**Archive:** <a href="https://doi.org/10.5281/zenodo.2591769" target="_blank">10.5281/zenodo.2591769</a>

## Status

[![status](http://joss.theoj.org/papers/67ba02e58e33a8a5b2295ec741a3260c/status.svg)](http://joss.theoj.org/papers/67ba02e58e33a8a5b2295ec741a3260c)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/67ba02e58e33a8a5b2295ec741a3260c"><img src="http://joss.theoj.org/papers/67ba02e58e33a8a5b2295ec741a3260c/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/67ba02e58e33a8a5b2295ec741a3260c/status.svg)](http://joss.theoj.org/papers/67ba02e58e33a8a5b2295ec741a3260c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Non-Contradiction/JuliaCall" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@matbesancon & @aguang, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leouieda know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Non-Contradiction/JuliaCall">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.16.5
- [x] **Authorship:** Has the submitting author (@Non-Contradiction) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Non-Contradiction/JuliaCall">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.16.5
- [x] **Authorship:** Has the submitting author (@Non-Contradiction) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @matbesancon, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01284/joss.01284/10.21105.joss.01284.pdf)

**Comment by matbesancon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1137/141000671 is OK
- http://doi.org/10.18637/jss.v040.i08 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by matbesancon** [comment]
@aguang I'm almost finished reviewing the software part and going to start the paper itself soon

**Comment by leouieda** [comment]
Thanks for the update @matbesancon :+1: 

If you have feedback or require changes to the software/docs, please open issues or PRs in the software repo and link them here by mentioning `openjournals/joss-reviews#1284`.

**Comment by matbesancon** [comment]
Closed:
https://github.com/Non-Contradiction/JuliaCall/issues/85
https://github.com/Non-Contradiction/JuliaCall/issues/89

Still open:
https://github.com/Non-Contradiction/JuliaCall/issues/87
https://github.com/Non-Contradiction/JuliaCall/issues/86

**Comment by aguang** [comment]
I've tested the code and read through the paper and most of it looks good to me. The package is very easy to use and even though I knew how much faster Julia was compared to R I was blown away by how much faster the Mandlebrot code was with JuliaCall. Very cool.

That said I've raised a few issues; 2 are to do with documentation and 1 is some code functionality.

Non-Contradiction/JuliaCall#91
Non-Contradiction/JuliaCall#92
Non-Contradiction/JuliaCall#93

**Comment by leouieda** [comment]
@aguang thank you for your comments :100: 

@Non-Contradiction please reply to the issues that @matbesancon and @aguang have raised. If any changes need to be made, please let us know when you're done so we can have a second round of reviews. Please also look at the checklist items at the top of this issue to see which items are still missing.

**Comment by aguang** [comment]
I closed the issues that were for functionality documentation and would recommend this paper for acceptance.

Quick question: There are 4 dois in the paper but whedon only checked 2. I checked the others and they are all OK but is this a bug? The other 2 are books that can be read in eBook form.

**Comment by leouieda** [comment]
@aguang thank you conducting the review! :tada: I don't think there is a problem with the DOIs if you checked that they work manually. We can wait and see if Whedon will complain. 

@matbesancon please let us know as soon as the remaining issues are resolved.

**Comment by Non-Contradiction** [comment]
@aguang thank you very much for the review! The suggestions in the issues are very constructive.

**Comment by matbesancon** [comment]
Closed most issues related to the software, one more regarding the paper:
https://github.com/Non-Contradiction/JuliaCall/issues/95

**Comment by matbesancon** [comment]
All issues relevant are now closed, I recommend the paper for submission :)

**Comment by leouieda** [comment]
Thank you @matbesancon and @aguang for all your work on the reviews! :1st_place_medal: 

:tada: Congratulations @Non-Contradiction! :tada: Following the positive recommendation of the reviewers, I'm happy to accept your paper for publication in JOSS. We just need a couple of things from you now:

1. Double check the author list and affiliations
2. Make a new release of the software with latest changes after review and the updated JOSS paper text (this will be the official version published in JOSS)
3. Archive this new release on [Zenodo](https://zenodo.org/) or similar and post the DOI for the archive here

Please don't hesitate to ask if you need any help.

**Comment by Non-Contradiction** [comment]
Thank you @matbesancon @aguang @leouieda for detailed reviews and constructive suggestions!

I checked the author list, make a new release on Github, and archive the release on Zenodo.
The DOI for the archive is DOI: 10.5281/zenodo.2591769

**Comment by leouieda** [comment]
@whedon set 10.5281/zenodo.2591769 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2591769" target="_blank">10.5281/zenodo.2591769</a> is the archive.

**Comment by leouieda** [comment]
@whedon set v0.16.5 as version

**Comment by whedon** [comment]
OK. v0.16.5 is the version.

**Comment by leouieda** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01284/joss.01284/10.21105.joss.01284.pdf)

**Comment by leouieda** [comment]
Thank you, @Non-Contradiction. I've run some last checks on the article proof and everything looks good to me.

@openjournals/joss-eics this submission is ready to be published.

**Comment by labarba** [comment]
Hi @Non-Contradiction — I'm going to ask you to edit the metadata of the Zenodo deposit (no need to get new version or new DOI) so the title and author list match the JOSS paper.

**Comment by labarba** [comment]
A few more editorial suggestions/requests:

- high-performance technique computing >> technique? 
- Section 2.77 in (Xie, Allaire, & Grolemund, 2018) >>When the citation is part of the sentence, then use: Author (year). The citation should appear in parenthesis when it is not part of the sentence, e.g. “We take inspiration from Smith et al. (2006) to … The code implements Theory X (Jones, 2012) to obtain … “  For the syntax to obtain brackets in the right places, see: https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html
- There are R packages which wrap Julia packages >> remove syntactic expletive: "Some R packages wrap Julia packages…" Elsewhere in the paper, look for "there are" and see if you can remove it by rephrasing.
- The package XRJulia follows the extending R interface implemented by the XR package >> something missing? Check grammar.
- has a signi cant speed advantage >> suggest not to use "significant" unless you mean "statistically significant"

**Comment by Non-Contradiction** [comment]
Thank @labarba for the suggestions. They are of great help! 
I have made the following changes accordingly.

* The wording of "high-performance technique computing" is from some introduction material of Julia by the Julia creators. I change it to high-performance scientific computing with similar meaning since it is easier to understand.
* I removed the brackets around the citation of xie2018r, from the link it seems to be the right syntax to give in-text citations. Previously I don't know these syntaxes. Thank you for the link.
* "there are" has been replaced.
* Extending R is an interface (or a framework of interfaces) connecting R to other languages, and the `XR` package implements the interface. `XRJulia` is an interface especially for Julia based on the `XR` package. Since this information of the `XRJulia` package can be easily found in the reference and not directly related to this paper, I removed the part and changed the sentence to "The package `XRJulia` connects to `Julia` from `R`."
* By "significant" I mean statistically significant. And I still removed the word since it is ambiguous. 

Thank you for the suggestions again and hope these modifications make the paper more concise and clear.

**Comment by labarba** [comment]
> Hi @Non-Contradiction — I'm going to ask you to edit the metadata of the Zenodo deposit (no need to get new version or new DOI) so the title and author list match the JOSS paper.

Looks like this is still pending?

**Comment by Non-Contradiction** [comment]
I have questions in changing the metadata of the Zenodo deposit. 
I used Zenodo's webhook to generate the deposit automatically from the release.
On the Zenodo website, it says creating a file with the name `.zenodo.json` can change the metadata.
But after creating the file, I found that the metadata didn't change automatically.
It seems that I have to create a new release to let Zenodo aware of the change?

**Comment by Non-Contradiction** [comment]
I have changed the metadata of the Zenodo deposit.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1201/9781315381305 is OK
- 10.1201/9781138359444 is OK
- 10.18637/jss.v040.i08 is OK

MISSING DOIs

- https://doi.org/10.31274/rtd-180813-10057 may be missing for title: R: A Language and Environment for Statistical Computing
- https://doi.org/10.7287/peerj.preprints.27221v1/supp-9 may be missing for title: autodiffr: Automatic Differentiation in R through ’Julia’
- https://doi.org/10.1007/0-387-30528-9_7 may be missing for title: convexjlr: Disciplined Convex Programming in R using ’Convex.jl’
- https://doi.org/10.1063/1.4912317 may be missing for title: diffeqr: Solving Differential Equations (ODEs, SDEs, DDEs, DAEs)
- https://doi.org/10.1109/ultsym.2008.0011/mm4 may be missing for title: FixedEffectjlr: A package for fast Fixed Effect Models in R
- https://doi.org/10.15514/ispras-2015-27(6)-2 may be missing for title: V8: Embedded JavaScript Engine for R
- https://doi.org/10.17504/protocols.io.jh7cj9n may be missing for title: rjulia: Integrating R and Julia – Calling Julia from R

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/549

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/549, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/551
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01284](https://doi.org/10.21105/joss.01284)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @Non-Contradiction, your JOSS paper is published!

Sincere thanks to the editor: @leouieda, and the reviewers: @matbesancon, @aguang 🙏

**Comment by matbesancon** [comment]
thanks @labarba for this last sprint on this!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01284/status.svg)](https://doi.org/10.21105/joss.01284)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01284">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01284/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01284/status.svg
   :target: https://doi.org/10.21105/joss.01284
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01284/status.svg)](https://doi.org/10.21105/joss.01284)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by labarba** [comment]
https://twitter.com/JOSS_TheOJ/status/1105918693400371206

**Comment by leouieda** [comment]
Congratulations @Non-Contradiction :tada: :tada:  Thank you @matbesancon and @aguang for the reviews and @labarba for the edits. I'll add those to my checklist for the future :smiley:
