### ISSUE TITLE
[REVIEW]: iced: fast and memory efficient normalization of contact maps

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1286]
**Submitting author:** @NelleV (<a href="http://orcid.org/0000-0002-8748-6546">Nelle varoquaux</a>)
**Repository:** <a href="https://github.com/hiclib/iced" target ="_blank">https://github.com/hiclib/iced</a>
**Version:** v0.5.1
**Editor:** @pjotrp
**Reviewer:** @robinweide
**Archive:** <a href="https://doi.org/10.5281/zenodo.2622857" target="_blank">10.5281/zenodo.2622857</a>

## Status

[![status](http://joss.theoj.org/papers/403431316ea4efc3dc57aa598064cb47/status.svg)](http://joss.theoj.org/papers/403431316ea4efc3dc57aa598064cb47)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/403431316ea4efc3dc57aa598064cb47"><img src="http://joss.theoj.org/papers/403431316ea4efc3dc57aa598064cb47/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/403431316ea4efc3dc57aa598064cb47/status.svg)](http://joss.theoj.org/papers/403431316ea4efc3dc57aa598064cb47)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/hiclib/iced" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@robinweide, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @pjotrp know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/hiclib/iced">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.5.1)?
- [x] **Authorship:** Has the submitting author (@NelleV) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @robinweide it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01286/joss.01286/10.21105.joss.01286.pdf)

**Comment by pjotrp** [comment]
@NelleV, we are starting review in this issue tracker. To expedite the review process do you mind going through above list of check boxes and make sure they can be ticked (you can't tick them). Also check the PDF output carefully. Ping us here when you are done.

**Comment by NelleV** [comment]
### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/hiclib/iced">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.5.1)?
- [x] **Authorship:** Has the submitting author (@NelleV) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.) 

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by NelleV** [comment]
The proofs look fine. I can tick everything, except Performance (I don't think it si applicaable) and Community guidelines (I'm not sure what is expected there--I've got a brief statement in the first page of the documentation that I am happy to extend if it is not detailed enough: http://projects.cbio.mines-paristech.fr/iced/index.html)

**Comment by pjotrp** [comment]
Thank you @NelleV. @robinweide you can start review.

**Comment by robinweide** [comment]
Hi @NelleV, @pjotrp,

I think it lookes quite good. The documentation is expansive and all code is clear and commented where applicable.

Minor ssues I have:

- [LICENSE-file missing](https://github.com/hiclib/iced/issues/61)
-  @NelleV you can tick off **performance** if you cite Servant et al. (2015) for the iced-benchmarks
- [community guidelines links to pastis-issue tracker](https://github.com/hiclib/iced/issues/62)
- I cannot find the DOI's in the references.

**Comment by pjotrp** [comment]
Thank you @robinweide! @NelleV please check.

**Comment by NelleV** [comment]
Thanks @robinweide for the review!

I've fixed all items be the number 3 (community guidelines). Unless I'm looking at the wrong link in the documentation, it's already pointing to the issue tracker.

**Comment by pjotrp** [comment]
@robinweide are you happy with the fixes?

**Comment by NelleV** [comment]
For information, point n3 is now also fixed. The link was pointing to the wrong bug tracker…

I hope this is now good to go. Let me know if I need to do anything else!

**Comment by robinweide** [comment]
> @robinweide are you happy with the fixes?

@pjotrp yes. However, since I'm already a user of HiC-pro -and thus iced- for a long time, I do strongly urge you to find a second reviewer. He/she could verify if all (installation/basic operation) is clear for a novice (Hi-C)user.

**Comment by pjotrp** [comment]
@robinweide thanks for the review. I think it is fine as is. The fact that you use this software is convincing enough to me.

**Comment by pjotrp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01286/joss.01286/10.21105.joss.01286.pdf)

**Comment by pjotrp** [comment]
Dear @NelleV, do you mind starting the paper with a short laypersons introduction of HiC and what your code does? Just paragraph will do to help the casual reader.

**Comment by NelleV** [comment]
Yes, no problem. Can I consider the article accepted with minor revisions? I have a job talk tomorrow.

**Comment by NelleV** [comment]
Can I re-trigger whedon's pdf generation?

**Comment by danielskatz** [comment]
just put ```@whedon generate pdf``` in as a new comment

**Comment by NelleV** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01286/joss.01286/10.21105.joss.01286.pdf)

**Comment by pjotrp** [comment]
> Yes, no problem. Can I consider the article accepted with minor revisions? I have a job talk tomorrow.

Yes

**Comment by NelleV** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1286 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    289      0 --:--:-- --:--:-- --:--:--   290
Can't compile the PDF, the bibtex file has 5 extraneous references: `@cournac:normalization, @imakaev:iterative, @li:hi-corrector, @varoquaux:iced_osf, @servant:hicpro`

**Comment by NelleV** [comment]
I'm not sure why the pdf is not compiling anymore: I changed the affiliation of my co-author Nicolas (INSERM is now INSERM U900). Any help would be appreciated.

**Comment by pjotrp** [comment]
@arfon I think we need some help here.

**Comment by pjotrp** [comment]
Oh, I see it now. @NelleV you need to remove the references in the bibtex file that you do not use in the paper. This is a recent check added to @whedon

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01286/joss.01286/10.21105.joss.01286.pdf)

**Comment by NelleV** [comment]
Thanks! The affiliation has been updated fine, and I added the introductory paragraph as well as a figure to show the data.

**Comment by pjotrp** [comment]
@NelleV excellent. We are close to completion. To finalize your submission and accept your paper in JOSS, we need two things. First, can you confirm that all references in your bibliography have a DOI in the bibliography (if one exists).

Second, we need you to deposit a copy of your software repository (including any revisions made during the JOSS review process) with a data-archiving service.

To do so:

1. Create [a GitHub release](https://help.github.com/articles/creating-releases/) of the current version of your software repository
2. Deposit that release with [Zenodo](https://zenodo.org/), [figshare](https://figshare.com/), or a similar DOI issuer.
3. Post a comment here with the DOI for the release.

**Comment by NelleV** [comment]
I've deposited the code in OSF already. Is that a suitable DOI issuer?
The DOI is 10.17605/OSF.IO/N6WHX

**Comment by NelleV** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01286/joss.01286/10.21105.joss.01286.pdf)

**Comment by NelleV** [comment]
I've added the DOI for all of the references.

**Comment by pjotrp** [comment]
@whedon set 10.17605/OSF.IO/N6WHX as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.17605/OSF.IO/N6WHX" target="_blank">10.17605/OSF.IO/N6WHX</a> is the archive.

**Comment by pjotrp** [comment]
Whedon accepts the DOI. Maybe the EIC team wants to have a look.

ping eic @openjournals/joss-eics

**Comment by kyleniemeyer** [comment]
Hi @NelleV, just a few final suggestions/corrections for the article:

- I think "As any genomics experiments" is missing a word.
- You don't need to cite the software in the paper, since there is already a link to the archive, and this paper serves as a reference for the software. (If you really want to keep it, it does need some fixing—th names aren't showing up correct, and it should have 2019 for the year.)
- The first sentence is great, but the second sentence mentions Hi-C which isn't explained—for nonexperts it might be nice to give a few words explaining what this is, since the rest of this paragraph is generally understandable.

Otherwise, looks great!

**Comment by NelleV** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01286/joss.01286/10.21105.joss.01286.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/600

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/600, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1186/1471-2164-13-436 is OK
- 10.1038/nmeth.2148 is OK
- 10.1093/bioinformatics/btu747 is OK
- 10.17605/OSF.IO/N6WHX is OK
- 10.1186/s13059-015-0831-x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@NelleV sorry to come back with another question, but I'm a little confused about the OSF DOI—from what I can tell, OSF is not actually archiving the accepted version of the software, but really linking to the GitHub repo, which can change. For our purposes, we really want an archived snapshot of the accepted version that could be downloaded, and usually people use Zenodo or Figshare for this purpose.

(I don't think @whedon does any checking of the archive DOI, other than that it's legit. @arfon perhaps you could comment?)

**Comment by NelleV** [comment]
You are correct. I can upload the code to zenodo.

**Comment by NelleV** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01286/joss.01286/10.21105.joss.01286.pdf)

**Comment by NelleV** [comment]
I've created a zenodo archive (/http://doi.org/10.5281/zenodo.2622857). I think everything is fine now, but the archive link on the article proof is not working.

**Comment by arfon** [comment]
> (I don't think @whedon does any checking of the archive DOI, other than that it's legit. @arfon perhaps you could comment?)

That's correct.

> I think everything is fine now, but the archive link on the article proof is not working.

This is only 'linked up' in the final proofs.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.2622857 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2622857" target="_blank">10.5281/zenodo.2622857</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1186/1471-2164-13-436 is OK
- 10.1038/nmeth.2148 is OK
- 10.1093/bioinformatics/btu747 is OK
- 10.5281/zenodo.2622857 is OK
- 10.1186/s13059-015-0831-x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/603

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/603, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/604
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01286](https://doi.org/10.21105/joss.01286)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @NelleV on your article published in JOSS!  Thanks @robinweide for reviewing and @pjotrp for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01286/status.svg)](https://doi.org/10.21105/joss.01286)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01286">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01286/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01286/status.svg
   :target: https://doi.org/10.21105/joss.01286
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01286/status.svg)](https://doi.org/10.21105/joss.01286)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
