### ISSUE TITLE
[PRE REVIEW]: PyBIDS: Python tools for BIDS datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1289]
**Submitting author:** @tyarkoni (<a href="http://orcid.org/0000-0002-6558-5113">Tal Yarkoni</a>)
**Repository:** <a href="https://github.com/bids-standard/pybids" target ="_blank">https://github.com/bids-standard/pybids</a>
**Version:** 0.8.0
**Editor:** @cMadan
**Reviewers:** @grlee77

**Author instructions**

Thanks for submitting your paper to JOSS @tyarkoni. **Currently, there isn't an JOSS editor assigned** to your paper.

@tyarkoni if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1289 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @cMadan - the submitting author requested you as the editor - is this ok?

**Comment by danielskatz** [comment]
👋 @tyarkoni - your paper.md authors and affiliations aren't formatted right - see https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography for an example of how this needs to be.

**Comment by tyarkoni** [comment]
Re: editor, I would have requested @arokem because of his Python expertise, but he's a contributor to the repository, so it seemed like a conflict of interest.

There's a PR that I *think* fixes the issues. Let's see...

@whedon generate pdf from branch joss

**Comment by danielskatz** [comment]
Whedon commands need to be new comments

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01289/joss.01289/10.21105.joss.01289.pdf)

**Comment by danielskatz** [comment]
ok, looks good

**Comment by grlee77** [comment]
I am interested in volunteering as a reviewer for this submission. I have MRI neuroimaging and python expertise.
I do not have any conflicts to report (I have contributed to one of the project's dependencies, NiBabel, but have not had any involvement with BIDS or pyBIDS).

**Comment by danielskatz** [comment]
Thanks @grlee77 - reviewer decisions will be made by the editor, hopefully @cMadan once he accepts

**Comment by cMadan** [comment]
@danielskatz @tyarkoni, sure, I'm happy to serve as editor for this submission.

@grlee77, thank you for volunteering to be a reviewer here.

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@whedon add @grlee77 as reviewer

**Comment by whedon** [comment]
OK, @grlee77 is now a reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1294. Feel free to close this issue now!
