### ISSUE TITLE
[PRE REVIEW]: pyuvdata: an interface for astronomical interferometeric datasets in python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#129]
**Submitting author:** bhazelton (<a href="http://orcid.org/0000-0001-7532-645X">Bryna J. Hazelton</a>)
**Repository:** <a href="https://github.com/HERA-Team/pyuvdata" target ="_blank">https://github.com/HERA-Team/pyuvdata</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewer:** @astrofrog

**What this issue is for**

Thanks for submitting your paper to JOSS bhazelton. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
👋  @astrofrog - would you be willing to review this submission for JOSS?

**Comment by astrofrog** [comment]
@arfon - very sorry for the delay, I'm happy to review this. I should have it done by the end of the week.

**Comment by arfon** [comment]
@whedon assign @astrofrog as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @astrofrog

**Comment by arfon** [comment]
> @arfon - very sorry for the delay, I'm happy to review this. I should have it done by the end of the week.

⚡️ thanks @astrofrog. I'll ping you on the actual review thread shortly.

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/140. Feel free to close this issue now!
