### ISSUE TITLE
[PRE REVIEW]: Badread: simulation of error-prone long reads

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1293]
**Submitting author:** @rrwick (<a href="http://orcid.org/0000-0001-8349-0778">Ryan Wick</a>)
**Repository:** <a href="https://github.com/rrwick/Badread" target ="_blank">https://github.com/rrwick/Badread</a>
**Version:** v0.1.3
**Editor:** @brainstorm
**Reviewers:** @betteridiot

**Author instructions**

Thanks for submitting your paper to JOSS @rrwick. **Currently, there isn't an JOSS editor assigned** to your paper.

@rrwick if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by danielskatz** [comment]
@pjotrp - I think this is another for your group to edit

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01293/joss.01293/10.21105.joss.01293.pdf)

**Comment by pjotrp** [comment]
Yes, I'll ask.

**Comment by brainstorm** [comment]
@whedon assign @brainstorm as editor

**Comment by whedon** [comment]
OK, the editor is @brainstorm

**Comment by dredamonsta1** [comment]
@Whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by brainstorm** [comment]
👋 @betteridiot, would you like to assist me reviewing this paper? Thanks in advance!

**Comment by betteridiot** [comment]
@brainstorm this is definitely up my alley. I would be more than happy to review this.

**Comment by brainstorm** [comment]
@whedon assign @betteridiot as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @betteridiot

**Comment by brainstorm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1316. Feel free to close this issue now!

**Comment by brainstorm** [comment]
Alright, thanks @betteridiot, off we go! ;)
