### ISSUE TITLE
[REVIEW]: PoreSpy: A Python Toolkit for Quantitative Analysis of Porous Media Images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1296]
**Submitting author:** @jgostick (<a href="http://orcid.org/0000-0001-7736-7124">Jeff Gostick</a>)
**Repository:** <a href="https://github.com/PMEAL/porespy" target ="_blank">https://github.com/PMEAL/porespy</a>
**Version:** V1.1.2
**Editor:** @usethedata
**Reviewer:** @yxqd, @cr458
**Archive:** <a href="https://doi.org/10.5281/zenodo.2642818" target="_blank">10.5281/zenodo.2642818</a>

## Status

[![status](http://joss.theoj.org/papers/cdf32608cb4a4fc253f8c8b51a8661cd/status.svg)](http://joss.theoj.org/papers/cdf32608cb4a4fc253f8c8b51a8661cd)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/cdf32608cb4a4fc253f8c8b51a8661cd"><img src="http://joss.theoj.org/papers/cdf32608cb4a4fc253f8c8b51a8661cd/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/cdf32608cb4a4fc253f8c8b51a8661cd/status.svg)](http://joss.theoj.org/papers/cdf32608cb4a4fc253f8c8b51a8661cd)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/PMEAL/porespy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@yxqd & @cr458, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @usethedata know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/PMEAL/porespy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** V1.1.2
- [x] **Authorship:** Has the submitting author (@jgostick) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/PMEAL/porespy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** V1.1.2
- [x] **Authorship:** Has the submitting author (@jgostick) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @yxqd, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01296/joss.01296/10.21105.joss.01296.pdf)

**Comment by jgostick** [comment]
Not sure if it's ok to interject in the review process, but this seems relevant to the review process:

Sometime between submitting to JOSS and now, Numpy (1.16) made a change that breaks Skimage (0.14.1)  The Skimage team has already fixed this in 0.14.2, but this version is NOT currently the default on the Conda distribution.  So, if a user were to install Conda, they get a version of Numpy and Skimage that do not work together.  The latest version of Skimage is available on the conda-forge channel, but not sure how long it will be until it reaches the default Conda channel.  

In our package we try not to specify hard version numbers, to avoid users needing to make virtualenvs for each package they want to use, so at this time the install may not work, depending the version of conda is being used.

**Comment by yxqd** [comment]
Hi @jgostick. I was able to install porespy with conda and will test its functionality tomorrow. Here are some questions regarding the paper itself:

* Should [Matthew Lam](https://github.com/mattrlam) be a co-author? Looking at commits only, he seems to contribute similarly to Matthew Kok and Mohammadamin Sadeghi.
* Could you please add more references to the first sentence of the paper? For example, https://doi.org/10.2138/rmg.2015.80.04 may be a good one
* There is one reference for your paper missing DOI

**Comment by jgostick** [comment]
HI @yxqd 
I'm glad you were able to get it installed...but if you haven't tried importing it you might run into the above mentioned problem.  You can upgrade skimage with ``conda install scikit-image -c conda-forge``

Regarding your questions:
* Matt Lam was an undergrad student that worked on a random walk algorithm.  We since removed this and put it into a separate package called [PyTrax](https://github.com/PMEAL/pytrax).  We submitted a paper to SoftwareX with his name on it, so he's getting his due credit.
* Will add some new citations and update the doi asap.  

Thanks for your input!

**Comment by yxqd** [comment]
@jgostick Thanks! The importing and testing following the instructions in README went well.

This is a software that has a clear-defined audience and lower the barrier for research concerning porosity analysis. Great job! Overall I am impressed with the quality of the software and documentation, and would recommend it for publication pending some issues below. Most of the issues are minor and are only suggestions, but I would really appreciate the authors to address the issue on improving the tests.

* PMEAL/porespy#153
* PMEAL/porespy#154
* PMEAL/porespy#155

**Comment by yxqd** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01296/joss.01296/10.21105.joss.01296.pdf)

**Comment by yxqd** [comment]
@jgostick BTW, it would be really nice to have the binder examples working: https://github.com/PMEAL/porespy-examples. This is just a suggestion though and not a road-blocker.

**Comment by jgostick** [comment]
Binder does not seem to work for us.  We got it going at first, but now it wont' render our files.  I think we may have an example that asks for too much resources?  Or maybe we broke the configuration by accident.

**Comment by cr458** [comment]
@jgostick sorry for the delay in getting back. 

1) Are you expecting contributions to this package from external users in the future? If so it may be useful to include instructions for developers too: i.e to install test requirements, and how to run the tests. I see that you include instructions to install the package in editable mode, which is nice. 

2) Since in your README you recommend: 

> PoreSpy depends heavily on the Scipy Stack. The best way to get a fully functional environment is the Anaconda distribution. 

Could you include your recommended way of installing it using conda?

3) Also could you please put:
>Be sure to get the Python 3.6+ version.

in bold/capitals/both, I somehow managed to miss it the first time around and have a default version of 3.5 for some reason (rare case but can happen!)


Will be getting round to digging into the code and playing around with it soon, looks good so far!

**Comment by cr458** [comment]
@jgostick I've noticed quite a few missing tests. Would you like me to open separate issues for each one, or one big issue for all of them?

**Comment by jgostick** [comment]
@cr458 One issue is fine.  The code coverage is ~90%

**Comment by usethedata** [comment]
Checking in on status.  I'm reading that there are a couple of issues opened that are being worked.  Anything in particular that needs help to move this forward? @jgostick @cr458 @yxqd

**Comment by jgostick** [comment]
@cr458 will make a list of missing unit tests, but otherwise I think we addressed all of @yxqd's comments.

**Comment by cr458** [comment]
Going through and making  a list of missing lists, documentation and issues I'm encountering when using the data, should be done fairly soon!

**Comment by cr458** [comment]
@jgostick have left some issues on the repo. If most of them seem nitpickiy it's because it's a very nice package and I found no major issues :).

- PMEAL/porespy#164
- PMEAL/porespy#163
- PMEAL/porespy#162
- PMEAL/porespy#161
- PMEAL/porespy#160
- PMEAL/porespy#159

**Comment by jgostick** [comment]
Loving it, many thanks.  I will address asap, then merge dev into master, upgrade version number to 1.1 and deploy to PyPI.   I would like that version to be the official JOSS version.  How does that work?

**Comment by usethedata** [comment]
@jgostick I've double checked, and the answer to your question is that when we're ready, you make a deposit of the desired version (such as with Zenodo).  Put the DOI for that archive here in this thread, and I'll use that to set the archive version associated with the paper.

**Comment by jgostick** [comment]
Hello all:  I have now merged everything onto master, bumped the version number to V1.1.0, and pushed official release to PyPI.  I have also enabled Zenodo, and received the following DOI for this release:  10.5281/zenodo.2633285

**Comment by jgostick** [comment]
Hold the presses...there is a failing test that I thought we'd fixed, but stupidly forgot about.  Very sorry.  I will get back to you tomorrow with the truly corrected information.

**Comment by jgostick** [comment]
I have fixed my release debacle, and now version 1.1.1 of PoreSpy is available on Github.  It now has a DOI of 10.5281/zenodo.2635591 for V1.1.1.

**Comment by usethedata** [comment]
@whedon set 10.5281/zenodo.2635591 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2635591" target="_blank">10.5281/zenodo.2635591</a> is the archive.

**Comment by usethedata** [comment]
@whedon set V1.1.1 as version

**Comment by whedon** [comment]
OK. V1.1.1 is the version.

**Comment by usethedata** [comment]
@yxqd and @cr458 are you able to complete your reviews with this update?

**Comment by yxqd** [comment]
@usethedata looks good to me now.

**Comment by TomTranter** [comment]
Hey guys, I saw my name was wrong on the paper so updated it. Not sure if I need to do anything else

**Comment by jgostick** [comment]
Sorry about that @TomTranter.  There is also another issue:  The Tag on github is 1.1.1, and this has been archived with a DOI...but the __version__ number is still at 1.1.0  👎   I really need to learn how to do githooks to prevent this, because I do it too often.  So how to proceed?  Should I add a new tag and have a new doi issued?

**Comment by usethedata** [comment]
@jgostick Yes.

**Comment by cr458** [comment]
@usethedata After the tag issue, looks good to me. Anything else I need to do to officially approve the PR?

**Comment by jgostick** [comment]
Great!  I have not 'pulled the trigger' on this new doi/tag/version yet due to mistakes made previously.  The dev branch is all set to go.  Now that both reviewers have reported back positively, I suppose I can:

1. Merge dev onto master
2. Tag master as V1.1.2 (Will be the official version of record in JOSS, also I can assure you that __version__ will now be set to 1.1.2 as well!)
3.  This tagging will generate a new DOI, which I will paste back into here when I get it.  

Is this correct?

**Comment by usethedata** [comment]
@cr458 If you'll mark off the rest of your checklist, that would be good.
@jgostick Yes.  I'll change the version here and I'll update the DOI when you've got that.

**Comment by usethedata** [comment]
@whedon set V1.1.2 as version

**Comment by whedon** [comment]
OK. V1.1.2 is the version.

**Comment by jgostick** [comment]
This DOI is offered on Zenodo as the 'one to rule them all', which will always resolve to the latest release.  I feel like this is the best one to use as future versions won't render it obsolete...

10.5281/zenodo.2633284

**Comment by jgostick** [comment]
Hi All, what's the situation here?  I think everything is done on our end.  I would like be able to 'announce' this paper at the upcoming interpore conference in Valencai, which is May 6-10...assuming our submission is acceptable, will it be possible to make a decision by this date?

**Comment by usethedata** [comment]
@whedon set 10.5281/zenodo.2642818 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2642818" target="_blank">10.5281/zenodo.2642818</a> is the archive.

**Comment by usethedata** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by usethedata** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.coelec.2017.08.018 is OK
- 10.2118/89343-PA is OK
- 10.2138/rmg.2015.80.04 is OK
- 10.1103/PhysRevE.96.023307 is OK
- 10.1016/j.compchemeng.2018.12.025 is OK
- 10.1038/nature09419 is OK
- 10.1016/j.ijheatmasstransfer.2015.02.073 is OK
- 10.1111/jmi.12389 is OK
- 10.1016/j.ijheatmasstransfer.2018.07.030 is OK
- 10.1016/j.ces.2018.10.049 is OK
- 10.1002/smll.201703616 is OK
- 10.2138/am-2001-8-917 is OK
- 10.1016/S0920-4105(97)00035-1 is OK
- 10.1002/ente.201800338 is OK
- 10.1016/j.electacta.2018.09.089 is OK
- 10.1186/s40679-016-0031-0 is OK
- 10.7717/peerj.453 is OK
- 10.1109/MCSE.2016.49 is OK

MISSING DOIs

- https://doi.org/10.1115/1.1483342 may be missing for title: Random Heterogeneous Materials: Microstructure and Macroscopic Properties

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1296 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    144      0 --:--:-- --:--:-- --:--:--   144
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.01296.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by usethedata** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01296/joss.01296/10.21105.joss.01296.pdf)

**Comment by usethedata** [comment]
@jgostick My apologies for the delay.  Some elder care issues have needed my attention.

@openjournals/joss-eics I believe this is ready to go.

**Comment by usethedata** [comment]
@jgostick If you want to give the PDF one final review to make sure you don't see any mistakes (author list, etc), that would be good.  It's a pain to fix once the article has been published.

**Comment by jgostick** [comment]
Everything looks good!

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.coelec.2017.08.018 is OK
- 10.2118/89343-PA is OK
- 10.2138/rmg.2015.80.04 is OK
- 10.1103/PhysRevE.96.023307 is OK
- 10.1016/j.compchemeng.2018.12.025 is OK
- 10.1038/nature09419 is OK
- 10.1016/j.ijheatmasstransfer.2015.02.073 is OK
- 10.1111/jmi.12389 is OK
- 10.1016/j.ijheatmasstransfer.2018.07.030 is OK
- 10.1016/j.ces.2018.10.049 is OK
- 10.1002/smll.201703616 is OK
- 10.2138/am-2001-8-917 is OK
- 10.1016/S0920-4105(97)00035-1 is OK
- 10.1002/ente.201800338 is OK
- 10.1016/j.electacta.2018.09.089 is OK
- 10.1186/s40679-016-0031-0 is OK
- 10.7717/peerj.453 is OK
- 10.1109/MCSE.2016.49 is OK

MISSING DOIs

- https://doi.org/10.1115/1.1483342 may be missing for title: Random Heterogeneous Materials: Microstructure and Macroscopic Properties

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/650

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/650, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
Hi @jgostick, before I do the final accept, could you edit the metadata for the Zenodo archive so that the authors match the paper? And also add full names/ORCID rather than just GitHub handles.

**Comment by jgostick** [comment]
I think it's done now...hopefully I edited the right places

**Comment by kyleniemeyer** [comment]
@jgostick this is what I'm seeing:
<img width="802" alt="Screen Shot 2019-04-30 at 8 59 31 PM" src="https://user-images.githubusercontent.com/190432/57005222-ea2d3180-6b8a-11e9-8c3c-9c0a5d558e01.png">

In addition to the GitHub handles instead of names, I also see names on Zenodo that aren't on the paper, and vice versa.

On the other hand, for version 1.1.1 in Zenodo, I see this:
<img width="811" alt="Screen Shot 2019-04-30 at 9 01 18 PM" src="https://user-images.githubusercontent.com/190432/57005239-29f41900-6b8b-11e9-87ca-487dd24aba3c.png">

So perhaps you edited the names for the wrong version?

**Comment by jgostick** [comment]
ahhh, I clicked save, but not publish, because I thought it already was published.  

Names, affiliation and orcid should be ok now, but I'm a bit confused which DOI to use...

The DOI for V1.1.2 is 10.5281/zenodo.2642818, but zenodo offers one for "all versions" which seems more useful since a new doi is issued for every minor version bump.  The one for all versions is 10.5281/zenodo.2633284, which is the one I gave to @usethedata in the above thread.

**Comment by kyleniemeyer** [comment]
In this case, we should use the specific DOI associated with the version published—we don't want the archived software referenced in the paper to point to a future version, if you update the archive later.

The paper also points to the software repo, so it will direct to the latest version in that way.

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.2642818 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2642818" target="_blank">10.5281/zenodo.2642818</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.coelec.2017.08.018 is OK
- 10.2118/89343-PA is OK
- 10.2138/rmg.2015.80.04 is OK
- 10.1103/PhysRevE.96.023307 is OK
- 10.1016/j.compchemeng.2018.12.025 is OK
- 10.1038/nature09419 is OK
- 10.1016/j.ijheatmasstransfer.2015.02.073 is OK
- 10.1111/jmi.12389 is OK
- 10.1016/j.ijheatmasstransfer.2018.07.030 is OK
- 10.1016/j.ces.2018.10.049 is OK
- 10.1002/smll.201703616 is OK
- 10.2138/am-2001-8-917 is OK
- 10.1016/S0920-4105(97)00035-1 is OK
- 10.1002/ente.201800338 is OK
- 10.1016/j.electacta.2018.09.089 is OK
- 10.1186/s40679-016-0031-0 is OK
- 10.7717/peerj.453 is OK
- 10.1109/MCSE.2016.49 is OK

MISSING DOIs

- https://doi.org/10.1115/1.1483342 may be missing for title: Random Heterogeneous Materials: Microstructure and Macroscopic Properties

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/653

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/653, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/654
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01296](https://doi.org/10.21105/joss.01296)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @jgostick on your paper's acceptance in JOSS! Thanks to @yxqd and @cr458 for reviewing, and @usethedata for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01296/status.svg)](https://doi.org/10.21105/joss.01296)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01296">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01296/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01296/status.svg
   :target: https://doi.org/10.21105/joss.01296
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01296/status.svg)](https://doi.org/10.21105/joss.01296)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
