### ISSUE TITLE
[PRE REVIEW]: ggparliament: A ggplot2 extension for parliament plots in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1297]
**Submitting author:** @zmeers (<a href="http://orcid.org/0000-0001-8045-6531">Zoe Meers</a>)
**Repository:** <a href="https://github.com/RobWHickman/ggparliament/" target ="_blank">https://github.com/RobWHickman/ggparliament/</a>
**Version:** v2.0.1
**Editor:** @cMadan
**Reviewers:** @andrewheiss

**Author instructions**

Thanks for submitting your paper to JOSS @zmeers. **Currently, there isn't an JOSS editor assigned** to your paper.

@zmeers if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1297 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
:wave: @zmeers - please review the JOSS submission guidelines and draft a paper to support your submission: https://joss.readthedocs.io/en/latest/submitting.html#submitting-your-paper

I'm going to pause this submission until we've heard back from you that you've done this.

**Comment by zmeers** [comment]
@arfon -- sorry about that. The paper is actually in the dev branch. Can I submit the paper from the dev branch or does it need to be in the master branch for compilation? I was planning to push the paper to the master branch, once accepted.

**Comment by arfon** [comment]
@whedon generate pdf from branch dev

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch dev. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01297/joss.01297/10.21105.joss.01297.pdf)

**Comment by zmeers** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by zmeers** [comment]
@whedon generate pdf from branch dev

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch dev. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01297/joss.01297/10.21105.joss.01297.pdf)

**Comment by zmeers** [comment]
Some minor issues with the BibTex... 
@whedon generate pdf from branch dev

**Comment by zmeers** [comment]
@whedon generate pdf from branch dev

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch dev. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01297/joss.01297/10.21105.joss.01297.pdf)

**Comment by zmeers** [comment]
The foot note did not compile. I will change it and recompile the paper.

**Comment by zmeers** [comment]
@whedon generate pdf from branch dev

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch dev. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01297/joss.01297/10.21105.joss.01297.pdf)

**Comment by zmeers** [comment]
@arfon Perhaps @andrewheiss or @rdrr1990 would be interested in reviewing this paper? They both list political science or politics as an area they are comfortable reviewing.

**Comment by andrewheiss** [comment]
🙋‍♂️Sure, I'd be happy to

**Comment by kyleniemeyer** [comment]
@zmeers please hold tight while we find an editor to manage your submission

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@whedon add @andrewheiss as reviewer

**Comment by whedon** [comment]
OK, @andrewheiss is now a reviewer

**Comment by cMadan** [comment]
I think we're all set to start the review here--so I'll start the review issue and close this one.

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1313. Feel free to close this issue now!
