### ISSUE TITLE
[REVIEW]: healpy: equal area pixelization and spherical harmonics transforms for data on the sphere in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1298]
**Submitting author:** @zonca (<a href="http://orcid.org/0000-0001-6841-1058">Andrea Zonca</a>)
**Repository:** <a href="https://github.com/healpy/healpy" target ="_blank">https://github.com/healpy/healpy</a>
**Version:** v1.12.9
**Editor:** @xuanxu
**Reviewer:** @harpolea
**Archive:** <a href="https://doi.org/10.5281/zenodo.2605426" target="_blank">10.5281/zenodo.2605426</a>

## Status

[![status](http://joss.theoj.org/papers/82b2a7bbe1e269c6f88af66b7a662085/status.svg)](http://joss.theoj.org/papers/82b2a7bbe1e269c6f88af66b7a662085)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/82b2a7bbe1e269c6f88af66b7a662085"><img src="http://joss.theoj.org/papers/82b2a7bbe1e269c6f88af66b7a662085/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/82b2a7bbe1e269c6f88af66b7a662085/status.svg)](http://joss.theoj.org/papers/82b2a7bbe1e269c6f88af66b7a662085)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/healpy/healpy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@harpolea, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @xuanxu know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/healpy/healpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.12.9
- [x] **Authorship:** Has the submitting author (@zonca) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @harpolea it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01298/joss.01298/10.21105.joss.01298.pdf)

**Comment by harpolea** [comment]
Hi all,
Overall, this package looks great and I've ticked off all the items in the review checklist. However I have a few additional points/suggestions:

- I worked through the tutorial and found a couple of bugs. I filed these as issues (healpy/healpy#538 and healpy/healpy#539)
- I checked the test coverage and it is a little low for some modules (< 60%) - it would be great if this could be improved
- A minor point: it would be nice to have a description/overview of the project in the documentation (i.e. not just in the README)
- Checking the contributors to the project, there are a few people who appear to have made substantial contributions (> 500 additions) but who are not listed in the author list. The criteria for who is listed as an author or is considered as a 'core developer' is not given, so I was wondering how this was determined?

**Comment by zonca** [comment]
thanks @harpolea !
the tutorial definitely needs some love, @daniellenz would you like to work on that? I think at some point we lost the script to download the high resolution WMAP maps, I recovered it from an ancient healpy version, see https://github.com/healpy/healpy/blob/master/healpy/test/data/get_wmap_maps.sh
We should tell people to run that before running the tutorial so they have some real data, or just rework the tutorial at lower resolution, whatever you think is best.

**Comment by DanielLenz** [comment]
Thanks @harpolea  for the review, these are all great comments!

Thanks @zonca for adding the wmap download script back to the repo. I'd be happy to update the tutorial, and I think the higher resolution data are important to have (e.g. Cl estimation doesn't really make sense on nside=32 data).

**Comment by zonca** [comment]
@harpolea current status:

* [ ] **tutorial**, @DanielLenz working on it
* [ ] **coverage**, have pull request ready (https://github.com/healpy/healpy/pull/541) to bring coverage over 80% for all the computational functions. I would prefer not to add more test on the modules related to visualization
* [x] **intro in docs**, I discovered our webhook was not working anymore and the docs were 2 months old, fixed now: https://healpy.readthedocs.io/en/latest/
* [ ] **contributors** authors are the core devs, (+ the HEALPix team as they maintain the upstream package and coordinate joint releases) and the core devs are people who monitor and answer the support tickets, anyone can become a core dev just asking me or another core dev. @DanielLenz is the most recent core dev and has relatively few commits compared to other more random contributors, but he is now the person spending more time on the project and this is probably going to increase in the future.

**Comment by zonca** [comment]
Hi @harpolea, we just merged a fix for the issue on the tutorial

**Comment by harpolea** [comment]
Great! I reran the tutorial and everything looks good to me. 

One small thing: I did try installing from conda on a different machine when I ran it and it didn't install the most recent version (e.g. it didn't include the new script to download the high res data), so I think that needs to be updated?

**Comment by zonca** [comment]
Yes, now that we are done with the fixes I'll make a new release and reply
back. Thank you.

**Comment by zonca** [comment]
ok @harpolea I have released 1.12.9, I renamed the downloader script to `healpy_get_wmap_maps.sh` and install it in the package so it's in the path.

Also, I moved the tutorial to a Jupyter Notebook and now we have a mybinder, see the badge in https://github.com/healpy/healpy

how do I change the version which is attached to the release?

**Comment by harpolea** [comment]
Great! Everything looks good to me @zonca. 

@xuanxu - I have ticked off all the checkboxes and I recommend this for publication!

**Comment by xuanxu** [comment]
Great! Thanks @harpolea! 
@zonca: I will set the version to 1.12.9. Can you create an archive in [zenodo](https://zenodo.org)/[figshare](https://figshare.com/)/other and report an DOI here?

**Comment by xuanxu** [comment]
@whedon set v1.12.9 as version

**Comment by whedon** [comment]
OK. v1.12.9 is the version.

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01298/joss.01298/10.21105.joss.01298.pdf)

**Comment by zonca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01298/joss.01298/10.21105.joss.01298.pdf)

**Comment by zonca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01298/joss.01298/10.21105.joss.01298.pdf)

**Comment by zonca** [comment]
thanks @harpolea and @xuanxu, see http://doi.org/10.5281/zenodo.2605426

**Comment by zonca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01298/joss.01298/10.21105.joss.01298.pdf)

**Comment by zonca** [comment]
ok, added some last minute feedback

**Comment by xuanxu** [comment]
@zonca: Could you edit the metadata of the Zenodo deposit so it matches the title and author list of the JOSS paper? Thanks!

**Comment by zonca** [comment]
ok @xuanxu , fixed

**Comment by xuanxu** [comment]
Thanks @zonca!

**Comment by xuanxu** [comment]
@whedon set 10.5281/zenodo.2605426 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2605426" target="_blank">10.5281/zenodo.2605426</a> is the archive.

**Comment by xuanxu** [comment]
This is ready now for publication. 
Pinging EIC for final acceptance: @openjournals/joss-eics

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/579

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/579, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.3847/0067-0049/226/1/10 is OK
- 10.1086/427976 is OK
- 10.22323/1.301.0766 is OK
- 10.1088/0067-0049/208/2/20 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by danielskatz** [comment]
Thanks to @xuanxu for editing and @harpolea for reviewing!

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/580
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01298](https://doi.org/10.21105/joss.01298)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
@zonca - please say hello to K. Gorski for me, since I used to work with him a bit a long time ago...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01298/status.svg)](https://doi.org/10.21105/joss.01298)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01298">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01298/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01298/status.svg
   :target: https://doi.org/10.21105/joss.01298
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01298/status.svg)](https://doi.org/10.21105/joss.01298)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by zonca** [comment]
Thanks @harpolea, @xuanxu, @danielskatz, it was a great experience publishing with JOSS!
