### ISSUE TITLE
[REVIEW]: MicrobiomeR:  An R Package for Simplified and Standardized Microbiome Analysis Workflows

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1299]
**Submitting author:** @grabear (<a href="http://orcid.org/0000-0001-8096-0180">Robert Gilmore</a>)
**Repository:** <a href="https://github.com/vallenderlab/MicrobiomeR" target ="_blank">https://github.com/vallenderlab/MicrobiomeR</a>
**Version:** 0.6.0
**Editor:** @lpantano
**Reviewer:** @CosteaPaul 
**Archive:** <a href="https://doi.org/10.5281/zenodo.2600432" target="_blank">10.5281/zenodo.2600432</a>

## Status

[![status](http://joss.theoj.org/papers/b6b22ad1249f52b2caf2b2b615080d9d/status.svg)](http://joss.theoj.org/papers/b6b22ad1249f52b2caf2b2b615080d9d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/b6b22ad1249f52b2caf2b2b615080d9d"><img src="http://joss.theoj.org/papers/b6b22ad1249f52b2caf2b2b615080d9d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/b6b22ad1249f52b2caf2b2b615080d9d/status.svg)](http://joss.theoj.org/papers/b6b22ad1249f52b2caf2b2b615080d9d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/vallenderlab/MicrobiomeR" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@CosteaPaul , please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/vallenderlab/MicrobiomeR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.6.0
- [x] **Authorship:** Has the submitting author (@grabear) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @CosteaPaul it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01299/joss.01299/10.21105.joss.01299.pdf)

**Comment by lpantano** [comment]
@grabear, can you render the other branch. As well, make sure to go over the list and see whether all the item can be checked to make the work easier @CosteaPaul.

Thanks!

**Comment by grabear** [comment]
Ok!  I will soon!

**Comment by grabear** [comment]
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01299/joss.01299/10.21105.joss.01299.pdf)

**Comment by CosteaPaul** [comment]
Slightly confused about where exactly i'm supposed to comment on this, so i'll just do it here and i'm sure i'll be told off if i did it wrong.

Running into trouble installing this package:
`install_github("vallenderlab/MicrobiomeR") `
returns:

Error: (converted from warning) unable to access index for repository /src/contrib:
  cannot open URL '/src/contrib/PACKAGES'

devtools 2.0.1
Issue in R 3.5.1, both on Windows and Unbuntu.

**Comment by lpantano** [comment]
Thanks @CosteaPaul,

This is a good place to comment or the other issue @grabear opened in his repository.

**Comment by grabear** [comment]
@CosteaPaul This isn't necessarily an issue with our package.  

Try using:
`install_github("ropensci/taxa")`
and see if it gives you the same error.

What version of the `remotes` package are you using?  Try upgrading to the latest version if you haven't already.

**Comment by CosteaPaul** [comment]
@grabear , ropensci/taxa installs just fine.
Using remotes 2.0.1

**Comment by grabear** [comment]
@CosteaPaul Please see the issue that I've created with the remotes repository.  It's linked above. :point_up: 

The "solution" was found here https://github.com/r-lib/remotes/issues/251, which links to this:
https://community.rstudio.com/t/travis-build-error-cannot-open-url-src-contrib-packages/18088

If you just do the following:
```r
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = "true")
remotes::install_github("vallenderlab/MicrobiomeR")
```

**Comment by grabear** [comment]
Sorry for the issues, we can update our README to reflect this weird workaround.  Once we put our package on CRAN this issue should not be a problem.

**Comment by CosteaPaul** [comment]
@grabear, the little hack seems to solve the install problem. 

Ran all from scratch on a docker starting with xubu 18 and the latest R (3.5.3). Installing this takes a while, but runs though. Hefty list of dependencies. Would say overall i spent >2 hours getting this running. (Packages like curl and openssl fail because of lib dependencies that then need to be installed separately). 

But now i can start playing with it. 

Would actually really appreciate a docker repo that i could just pull and get started directly. Think this is something that would make sense having?

**Comment by grabear** [comment]
> Would actually really appreciate a docker repo that I could just pull and get started directly. Think this is something that would make sense having?

I think this would be really nifty!  @CosteaPaul 

Unfortunately, our institution has a policy that doesn't permit us to use docker containers on their servers.  I can definitely try to look into it on my personal machine if you think it would be helpful.

**Comment by CosteaPaul** [comment]
@grabear it's not something i think is needed, but would be nice to have.
Maybe a singularity container then? (that way you don't have to upset your security ppl).

Anyway, i've ticked all the boxes so as far as i'm concerned this is good to go. Am i supposed to do something else now?

**Comment by grabear** [comment]
@lpantano What happens next?

**Comment by lpantano** [comment]
Thanks both!, I will take a final look and tell you something tomorrow morning!

**Comment by lpantano** [comment]
Hi,

I think all is good. One minor detail in the references is that some of them have initials for the authors and others F. Lastname. Can you normalize the references to have the latter(F Lastname)?

After that, generate another proof, check references, and create a zenodo archive DOI. The metadata needs to be correct, like the title of the version in zenodo should be the title of the paper and author list.

After that, I can start the acceptance process and ping the joss-eics team to have a final look and finalize the acceptance.

Thanks!

**Comment by grabear** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01299/joss.01299/10.21105.joss.01299.pdf)

**Comment by grabear** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01299/joss.01299/10.21105.joss.01299.pdf)

**Comment by grabear** [comment]
@lpantano @CosteaPaul @sdhutchins https://zenodo.org/record/2598670

**Comment by lpantano** [comment]
Thank you, @grabear. 

I think there is some misunderstanding, sorry about that. 

The Zenodo has to be from your repository, here you have an example of an accepted paper: https://zenodo.org/record/2574400#.XJE3_akpBp8

Cheers

**Comment by grabear** [comment]
Ahhh!  SMH....  @lpantano one second.

**Comment by grabear** [comment]
Unfortunately, I have to wait for Zenodo to get back to me.  I used the DOI in that first link that I sent.  In order to change the files, associated with that DOI I had to fill out a form and make a request.  

More to come...

**Comment by lpantano** [comment]
sorry about the issue. Normally I sync Zenodo with my repos and then everytime I make a release a new version in Zenodo is created. If that is easy, go ahead, we can add whatever new Zenodo link to the final reviewed version.

**Comment by grabear** [comment]
@sdhutchins made a release or two today.  Here is the link to the zenodo for that:
https://zenodo.org/account/settings/github/repository/vallenderlab/MicrobiomeR#

I also used this DOI in the "zenodo mistake" I made earlier.  So we made need to be issued another DOI.
@lpantano

**Comment by lpantano** [comment]
Hi,

Thanks for working on this. I found this one: https://zenodo.org/record/2600432#.XJLLXaQpCEc  what seems correct.

But we need to match the title of the zenodo release with the paper (as you did for the mistake). Can you remove the mistake zenodo or change the title and update this one with the paper title.

Probably we need to add more documentation on this matter.

Let me know if you need more help trying to match the title to the paper.

Thanks! almost there.

**Comment by grabear** [comment]
Sorry about that!  I've been doing the zenodo in a hurry, and I'm kicking myself for it.  I'm working to complete this properly now.

**Comment by grabear** [comment]
Ok so here is the Zenodo link for the paper.  The title should be correct.  I published it as well, so hopefully that solved some other issues.  https://zenodo.org/record/2600432

**Comment by lpantano** [comment]
@weldom set 10.5281/zenodo.2600432 as archive

**Comment by lpantano** [comment]
@weldom set 0.6.0 as version

**Comment by lpantano** [comment]
@whedon set 0.6.0 as version

**Comment by whedon** [comment]
OK. 0.6.0 is the version.

**Comment by lpantano** [comment]
@whedon set 10.5281/zenodo.2600432 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2600432" target="_blank">10.5281/zenodo.2600432</a> is the archive.

**Comment by lpantano** [comment]
Hi @openjournals/joss-eics,

This paper has been accepted. Let us know if we missed something.

Thanks!

**Comment by sdhutchins** [comment]
@lpantano just an fyi, we added an additional reference to the paper in the `.bib` file in `v0.60`

**Comment by grabear** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01299/joss.01299/10.21105.joss.01299.pdf)

**Comment by lpantano** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0061217 is OK
- 10.1371/journal.pcbi.1005404 is OK
- 10.12688/f1000research.14013.2 is OK
- 10.1038/nmeth.f.303 is OK
- 10.1093/nar/gks1219 is OK
- 10.1093/nar/gkt1209 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by grabear** [comment]
:smile:

**Comment by lpantano** [comment]
Just pinging again @openjournals/jose-editors and @arfon in case this was missed. The paper is accepted.

**Comment by arfon** [comment]
Hi @lpantano - looks like we missed the ping last week, my apologies.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/593

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/593, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0061217 is OK
- 10.1371/journal.pcbi.1005404 is OK
- 10.12688/f1000research.14013.2 is OK
- 10.1038/nmeth.f.303 is OK
- 10.1093/nar/gks1219 is OK
- 10.1093/nar/gkt1209 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/594
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01299](https://doi.org/10.21105/joss.01299)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@CosteaPaul - many thanks for your review here and to @lpantano for editing this submission ✨ 

@grabear - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01299/status.svg)](https://doi.org/10.21105/joss.01299)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01299">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01299/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01299/status.svg
   :target: https://doi.org/10.21105/joss.01299
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01299/status.svg)](https://doi.org/10.21105/joss.01299)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by grabear** [comment]
Thanks, @whedon @lpantano @CosteaPaul @sdhutchins for working through this!

Cheers!!
@grabear
