### ISSUE TITLE
Title bar clipped on Firefox on Mac OS X

### ISSUE THREAD

**Issue by gvwilson** [openjournals/joss-reviews#13]
Firefox 46.0.1 on Mac OS X 10.10.5, top of 'about' page is clipped:
![screen shot 2016-05-05 at 1 01 08 pm](https://cloud.githubusercontent.com/assets/911566/15050400/8f5b1076-12c1-11e6-8f1e-c5ba583f8f5d.png)

**Comment by arfon** [comment]
Thanks for spotting this @gvwilson! Fixed in https://github.com/openjournals/joss/commit/5e192f4613da43fc2ddfaa1dee7139ce91b2910a
