### ISSUE TITLE
Unopened review for submission.

### ISSUE THREAD

**Issue by johnb30** [openjournals/joss-reviews#130]
First off, my apologies if this is the incorrect venue; please feel free to close the issue and point me towards a better avenue for discussion. 

We submitted a paper to JOSS about a month ago, but still haven't seen it hit the review process. The submission is [here](http://joss.theoj.org/papers/78d3cb025a049782e7ea63a0c8ee79f6). Please let me know if any other details or information is needed from our end.

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
> We submitted a paper to JOSS about a month ago, but still haven't seen it hit the review process. The submission is here. Please let me know if any other details or information is needed from our end.

@johnb30 - my apologies. This one slipped through the net. I've started the process over here https://github.com/openjournals/joss-reviews/issues/131
