### ISSUE TITLE
[PRE REVIEW]: rrcf: Implementation of the Robust Random Cut Forest algorithm for anomaly detection on streams

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1301]
**Submitting author:** @mdbartos (<a href="http://orcid.org/0000-0001-6421-222X">Matthew Bartos</a>)
**Repository:** <a href="https://github.com/kLabUM/rrcf" target ="_blank">https://github.com/kLabUM/rrcf</a>
**Version:** v0.2
**Editor:** @VivianePons
**Reviewers:** @vc1492a, @justinshenk

**Author instructions**

Thanks for submitting your paper to JOSS @mdbartos. **Currently, there isn't an JOSS editor assigned** to your paper.

@mdbartos if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01301/joss.01301/10.21105.joss.01301.pdf)

**Comment by mdbartos** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01301/joss.01301/10.21105.joss.01301.pdf)

**Comment by kyleniemeyer** [comment]
@eramirem @arokem could one of you edit this submission?

**Comment by mdbartos** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01301/joss.01301/10.21105.joss.01301.pdf)

**Comment by mdbartos** [comment]
Hi @kyleniemeyer, just checking in to see if you've found an editor.

Thanks,
MDB

**Comment by kyleniemeyer** [comment]
@eramirem @arokem ping- could one of you take this?

**Comment by labarba** [comment]
👋 @VivianePons — Taking into account editor workloads at the moment, I'd like to assign this submission to you for handling. Can you take it on?

**Comment by labarba** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by VivianePons** [comment]
I have just emails to @vc1492a and @justinshenk to ask for a review

**Comment by vc1492a** [comment]
@VivianePons Thanks, will gladly provide a review of this work. Will read the original paper and review the code, and will comment here (within a few weeks time) with my comments.

**Comment by VivianePons** [comment]
@whedon assign @vc1492a as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @vc1492a

**Comment by VivianePons** [comment]
Perfect! I will create a review issue with some checkpoints as soon as I have a second confirmed reviewer. Don't hesitate to comment here in the meantime

**Comment by VivianePons** [comment]
@whedon add @justinshenk as reviewer

**Comment by whedon** [comment]
OK, @justinshenk is now a reviewer

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1336. Feel free to close this issue now!
