### ISSUE TITLE
[PRE REVIEW]: ACHR.cu: GPU sampling of metabolic networks.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1302]
**Submitting author:** @marouenbg (<a href="http://orcid.org/0000-0001-5934-966X">Marouen Ben Guebila</a>)
**Repository:** <a href="https://github.com/marouenbg/ACHR.cu" target ="_blank">https://github.com/marouenbg/ACHR.cu</a>
**Version:** v0.1
**Editor:** @lpantano
**Reviewers:** @wmegchel, @prasunanand

**Author instructions**

Thanks for submitting your paper to JOSS @marouenbg. **Currently, there isn't an JOSS editor assigned** to your paper.

@marouenbg if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1302 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1302 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01302/joss.01302/10.21105.joss.01302.pdf)

**Comment by marouenbg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1302 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    232      0 --:--:-- --:--:-- --:--:--   236
Error producing PDF.
! Undefined control sequence.
l.376 Model\Cores

Looks like we failed to compile the PDF

**Comment by marouenbg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01302/joss.01302/10.21105.joss.01302.pdf)

**Comment by kyleniemeyer** [comment]
@brainstorm @mgymrek @pjotrp not sure exactly if this one fits in your area, but if so would one of you be able to edit? (or recommend someone else... this is a bit far outside my area of expertise to make a good call)

**Comment by pjotrp** [comment]
One of our team will take it.

**Comment by kyleniemeyer** [comment]
thanks @pjotrp!

**Comment by lpantano** [comment]
Hi @marouenbg,

I will lead the review process of this tool. Thank you for submitting. I am looking for possible reviewers, meanwhile, could you add the DOI links to the reference, please? It has to end up something like this: https://github.com/openjournals/joss-papers/blob/joss.01299/joss.01299/10.21105.joss.01299.pdf

Thanks!

**Comment by kyleniemeyer** [comment]
@whedon assign @lpantano as editor

**Comment by marouenbg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01302/joss.01302/10.21105.joss.01302.pdf)

**Comment by lpantano** [comment]
Hi @marouenbg,

I am still trying to find a reviewer for this, I will try one more time and see what happens. If not, I will talk to the editor board to get some help.

Sorry for the delay.

**Comment by marouenbg** [comment]
Thanks @lpantano for the update. Let me know how it goes.

**Comment by arfon** [comment]
:wave: how are you getting along finding a reviewer @lpantano?

**Comment by lpantano** [comment]
Hi Arfon,

I was still trying to find somebody. People in metabolomics I contacted
found this challenging because they don't have a mathematical background to
understand enough the tool.
And we have an internal meeting tomorrow to solve this issue some who.
Thanks for proposing a reviewer.

Cheers

**Comment by lpantano** [comment]
@whedon assign ﻿﻿﻿@wmegchel as reviewer

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, the reviewer is ﻿﻿﻿@wmegchel

**Comment by lpantano** [comment]
@whedon start review

**Comment by lpantano** [comment]
@whedon add @prasunanand as reviewer

**Comment by whedon** [comment]
OK, @prasunanand is now a reviewer

**Comment by lpantano** [comment]
@arfon, whedon is not starting the review, anything else I have to trigger to move this to review?

**Comment by arfon** [comment]
@whedon start review

**Comment by arfon** [comment]
@whedon assign @wmegchel as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @wmegchel

**Comment by arfon** [comment]
@whedon add @prasunanand as reviewer

**Comment by whedon** [comment]
OK, @prasunanand is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1363. Feel free to close this issue now!

**Comment by arfon** [comment]
> @arfon, whedon is not starting the review, anything else I have to trigger to move this to review?

Not sure what was going on with Whedon. Re-assigning the reviewers seemed to help here.
