### ISSUE TITLE
[PRE REVIEW]: mpi4py-fft - Parallel Fast Fourier Transforms with MPI for Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1303]
**Submitting author:** @mikaem (<a href="http://orcid.org/0000-0002-3293-7573">Mikael Mortensen</a>)
**Repository:** <a href="https://bitbucket.org/mpi4py/mpi4py-fft" target ="_blank">https://bitbucket.org/mpi4py/mpi4py-fft</a>
**Version:** v2.0.0
**Editor:** @VivianePons
**Reviewers:** @iljah, @rainwoodman

**Author instructions**

Thanks for submitting your paper to JOSS @mikaem. **Currently, there isn't an JOSS editor assigned** to your paper.

@mikaem if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01303/joss.01303/10.21105.joss.01303.pdf)

**Comment by mikaem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01303/joss.01303/10.21105.joss.01303.pdf)

**Comment by kyleniemeyer** [comment]
@VivianePons are you interested/willing to edit this submission?

**Comment by kyleniemeyer** [comment]
@eramirem this one might also be up your alley to edit

**Comment by VivianePons** [comment]
I can take it, I will look at it next week.

**Comment by kyleniemeyer** [comment]
@VivianePons thanks!

**Comment by kyleniemeyer** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by iljah** [comment]
I've accepted editor's request to review.

**Comment by mikaem** [comment]
Do you want me to suggest other reviewers @VivianePons?

**Comment by VivianePons** [comment]
@whedon assign @iljah as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @iljah

**Comment by VivianePons** [comment]
@mikaem I have asked a second reviewer and I am waiting for their answers. I will let you know.

**Comment by VivianePons** [comment]
@iljah I am waiting for a confirmed second reviewer to officially start the "review issue" but feel free to voice your comments here in the meantime.

**Comment by VivianePons** [comment]
I am not hearing back from my second reviewer. @mikaem do you have any suggestion for a reviewer?

**Comment by mikaem** [comment]
Dear Yu Feng @rainwoodman
Would you be interested in reviewing this submission to JOSS?

**Comment by rainwoodman** [comment]
Sure -- I'll need to see the review guidelines, and a deadline.

**Comment by VivianePons** [comment]
@whedon add @rainwoodman as reviewer

**Comment by whedon** [comment]
OK, @rainwoodman is now a reviewer

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1340. Feel free to close this issue now!
