### ISSUE TITLE
[PRE REVIEW]: lifelines: survival analysis in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1305]
**Submitting author:** @CamDavidsonPilon (<a href="http://orcid.org/0000-0003-1794-9143">Cameron Davidson-Pilon</a>)
**Repository:** <a href="https://github.com/camdavidsonpilon/lifelines" target ="_blank">https://github.com/camdavidsonpilon/lifelines</a>
**Version:** 0.20.0
**Editor:** @trallard
**Reviewers:** @becarioprecario, @sunhwan

**Author instructions**

Thanks for submitting your paper to JOSS @CamDavidsonPilon. **Currently, there isn't an JOSS editor assigned** to your paper.

@CamDavidsonPilon if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1305 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by CamDavidsonPilon** [comment]
@becarioprecario @sunhwan

**Comment by CamDavidsonPilon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by CamDavidsonPilon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1305 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:117:in `parse_affiliations': undefined method `each' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:103:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by CamDavidsonPilon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1305 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    235      0 --:--:-- --:--:-- --:--:--   236
Error reading bibliography ./paper.bib (line 9, column 10):
unexpected ","
expecting white space
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by CamDavidsonPilon** [comment]
SORRY ABOUT THE NOISE 🔈 

I think I got it.

**Comment by CamDavidsonPilon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1305 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    115      0 --:--:-- --:--:-- --:--:--   116
Error reading bibliography ./paper.bib (line 51, column 44):
unexpected "\\"
expecting white space or ","
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by CamDavidsonPilon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01305/joss.01305/10.21105.joss.01305.pdf)

**Comment by CamDavidsonPilon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1305 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    124      0 --:--:-- --:--:-- --:--:--   125
Error reading bibliography ./paper.bib (line 24, column 1):
unexpected "@"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by CamDavidsonPilon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01305/joss.01305/10.21105.joss.01305.pdf)

**Comment by kyleniemeyer** [comment]
@Cameron Davidson-Pilon before we get this review started and work on reviewers, we first need to assign an editor to handle it—hang tight.

**Comment by kyleniemeyer** [comment]
@trallard would you be able/interested to edit this submission?

**Comment by CamDavidsonPilon** [comment]
Whoops, I got confused by the OP I guess. Thanks @kyleniemeyer

**Comment by trallard** [comment]
Hi @kyleniemeyer yes I would be happy to edit this submission

**Comment by kyleniemeyer** [comment]
@trallard thanks!

**Comment by kyleniemeyer** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by trallard** [comment]
Hi @CamDavidsonPilon  I will be editing this paper let's ping the reviewers. Once we have found 2 reviewers we can proceed to the review of the software

---

Dear potential reviewers, 

Based on your expertise I would like to ask if you can help out with this JOSS submission.

**Title**: lifelines: survival analysis in Python

**Summary**: lifelines is a pure Python implementation of the best parts of survival analysis. We'd love to hear if you are using lifelines, please leave an Issue and let us know your thoughts on the library. 

**Article proof**: [https://github.com/openjournals/joss-papers/blob/joss.01305/joss.01305/10.21105.joss.01305.pdf](https://github.com/openjournals/joss-papers/blob/joss.01305/joss.01305/10.21105.joss.01305.pdf)

**Submitting author**: @CamDavidsonPilon (Cameron Davidson-Pilon)

**Version:** 0.20.0

**Repository**: [https://github.com/CamDavidsonPilon/lifelines](https://github.com/CamDavidsonPilon/lifelines)

---

@becarioprecario: Virgilio, are you able to and interested in taking this review?
@sunhwan: Sunhwan, are you able to and interested in taking this review?

**Comment by becarioprecario** [comment]
Hi,

Yes. I will be happy to review this paper. Please, do you have a link with the instructions on how to make reviews.
Best,
Virgilio

**Comment by trallard** [comment]
Thanks @becarioprecario 
Let's wait and see if @sunhwan is willing to act as a reviewer too

**Comment by trallard** [comment]
@whedon assign @becarioprecario as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @becarioprecario

**Comment by sunhwan** [comment]
@trallard I will be happy to review this paper.

**Comment by trallard** [comment]
fab thanks @sunhwan! I will then start the review issue and close this one

**Comment by trallard** [comment]
@whedon add @sunhwan as reviewer

**Comment by whedon** [comment]
OK, @sunhwan is now a reviewer

**Comment by trallard** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1317. Feel free to close this issue now!
