### ISSUE TITLE
[PRE REVIEW]: rGUIDANCE – alignment confidence score computation in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1307]
**Submitting author:** @FranzKrah (<a href="http://orcid.org/0000-0001-7866-7508">Franz-Sebastian Krah</a>)
**Repository:** <a href="https://github.com/FranzKrah/rGUIDANCE" target ="_blank">https://github.com/FranzKrah/rGUIDANCE</a>
**Version:** 1.0
**Editor:** @karthik
**Reviewers:** @shaunpwilkinson 

**Author instructions**

Thanks for submitting your paper to JOSS @FranzKrah. **Currently, there isn't an JOSS editor assigned** to your paper.

@FranzKrah if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01307/joss.01307/10.21105.joss.01307.pdf)

**Comment by kyleniemeyer** [comment]
@karthik this submission looks like it might be up your alley—can you edit it?

**Comment by karthik** [comment]
Sure thing.

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by karthik** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1111/j.1461-0248.2009.01314.x is OK
- 10.1186/1471-2105-7-471 is OK
- 10.1371/journal.pone.0018093 is OK
- 10.1093/sysbio/syv033 is OK
- 10.1016/j.patrec.2005.10.010 is OK
- 10.1093/bioinformatics/bti623 is OK

MISSING DOIs

- https://doi.org/10.1055/a-0805-3526 may be missing for title: The popularity of data analysis software
- https://doi.org/10.1093/bioinformatics/btu033 may be missing for title: RAxML version 8: a tool for phylogenetic analysis and post-analysis of large phylogenies
- https://doi.org/10.1093/molbev/msq066 may be missing for title: An alignment confidence score capturing robustness to guide tree uncertainty
- https://doi.org/10.1093/nar/gkv318 may be missing for title: GUIDANCE2: accurate detection of unreliable alignment regions accounting for the uncertainty of multiple parameters
- https://doi.org/10.1142/9789812776136_0003 may be missing for title: Local reliability measures from sets of co-optimal multiple sequence alignments.
- https://doi.org/10.1186/s12862-018-1229-7 may be missing for title: Evolutionary dynamics of host specialization in wood-decay fungi

INVALID DOIs

- None
```

**Comment by FranzKrah** [comment]
List of potential reviewers:
- emmanuel.paradis@ird.fr
- juancamilovillada@gmail.com
- me@nanx.me
- shaunpwilkinson@gmail.com
- frederick.boehm@gmail.com
- mdsherman@betteridiot.tech


and should I add the missing DOIs?

**Comment by FranzKrah** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by FranzKrah** [comment]
Hi, I could need some assistance here! Is there anything I should do now? 
Cheers Franz

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1111/j.1461-0248.2009.01314.x is OK
- 10.1186/1471-2105-7-471 is OK
- 10.1371/journal.pone.0018093 is OK
- 10.1093/sysbio/syv033 is OK
- 10.1016/j.patrec.2005.10.010 is OK
- 10.1093/bioinformatics/bti623 is OK

MISSING DOIs

- https://doi.org/10.1093/bioinformatics/btu033 may be missing for title: RAxML version 8: a tool for phylogenetic analysis and post-analysis of large phylogenies
- https://doi.org/10.1093/molbev/msq066 may be missing for title: An alignment confidence score capturing robustness to guide tree uncertainty
- https://doi.org/10.1093/nar/gkv318 may be missing for title: GUIDANCE2: accurate detection of unreliable alignment regions accounting for the uncertainty of multiple parameters
- https://doi.org/10.1142/9789812776136_0003 may be missing for title: Local reliability measures from sets of co-optimal multiple sequence alignments.

INVALID DOIs

- None
```

**Comment by arfon** [comment]
> and should I add the missing DOIs?

@FranzKrah - yes please. The list of DOIs above ☝️should be considered as suggestions, please check them before adding them.

> Hi, I could need some assistance here! Is there anything I should do now?

I think the next steps are on @karthik here to take your reviewer suggestions and invite the reviewers to participate.

**Comment by FranzKrah** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1111/j.1461-0248.2009.01314.x is OK
- 10.1186/1471-2105-7-471 is OK
- 10.1371/journal.pone.0018093 is OK
- 10.1093/sysbio/syv033 is OK
- 10.1093/bioinformatics/btu033 is OK
- 10.1093/molbev/msq066 is OK
- 10.1093/nar/gkv318 is OK
- 10.1142/9789812776136_0003 is OK
- 10.1186/s12862-018-1229-7 is OK
- 10.1016/j.patrec.2005.10.010 is OK
- 10.1093/bioinformatics/bti623 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by karthik** [comment]
👋 @nanxstats would you be able to review this submission for us? 🙏

**Comment by nanxstats** [comment]
Hi @karthik -thanks for the invitation, but to be honest, I'm not really familiar with phylogenetics or evolution biology, so probably not the best candidate for this review. Sorry!

**Comment by karthik** [comment]
No worries @nanxstats and thanks for the fast response.

**Comment by karthik** [comment]
@shaunpwilkinson Would you be able to review this submission for us? 🙏

**Comment by shaunpwilkinson** [comment]
Hi @karthik sure, I'd be happy to review, but I may take a couple of weeks before I can to get to it. If you're happy with a slight delay then sign me up!

**Comment by karthik** [comment]
Fantastic! Thank you @shaunpwilkinson 

The additional time is fine. I'll start the review (which will create a new issue with a checklist and close this one).

**Comment by karthik** [comment]
@whedon assign @@shaunpwilkinson  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @@shaunpwilkinson

**Comment by karthik** [comment]
@whedon assign @shaunpwilkinson  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @shaunpwilkinson

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1350. Feel free to close this issue now!
