### ISSUE TITLE
[PRE REVIEW]: webweb: a tool for creating lightweight network visualizations in the browser

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1308]
**Submitting author:** @hneutr (<a href="http://orcid.org/0000-0003-2518-841X">Kenneth Hunter Wapman</a>)
**Repository:** <a href="https://github.com/dblarremore/webweb" target ="_blank">https://github.com/dblarremore/webweb</a>
**Version:** 0.0.29
**Editor:** @cMadan
**Reviewers:** @vc1492a, @jg-you

**Author instructions**

Thanks for submitting your paper to JOSS @hneutr. **Currently, there isn't an JOSS editor assigned** to your paper.

@hneutr if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01308/joss.01308/10.21105.joss.01308.pdf)

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@hneutr, do you have any suggestions for potential reviewers?

**Comment by hneutr** [comment]
Hey @cMadan! Thanks for taking the time to do this —  I (along with @dblarremore) really appreciate it. For reviewers, I think the tool follows pretty closely along the interests of:
- Yo Yehudi

And less closely along: 
- Leonardo Uieda
- Ariel Rokem
- Karthik Ram

I'm happy to @ any reviewers to engage them, but didn't want to without knowing what the process is.

- Hunter

**Comment by cMadan** [comment]
@jg-you @count0 @antoineallard--Hi, would you be interested/available to review this project for publication in JOSS? Thank you for considering!

**Comment by jg-you** [comment]
I've never done software reviews before, and I am busy with a few other reviews ATM, so I will probably be slow.

If these are not serious issues, then sure I'll be happy to review `webweb`!
Otherwise, I'll have to pass.

**Comment by antoineallard** [comment]
Never done software reviews before either. I may be able to look at the code in a few weeks. One of the coauthors is a friend. Is that an issue?

**Comment by count0** [comment]
I have too much on my plate at the moment, and I will have to decline.

**Comment by cMadan** [comment]
@jg-you @antoineallard, will get back to you soon. I want to try and get someone who's done a software review also on board and then perhaps have one of you as an additional reviewer.

@count0, no problem, thank you for considering!

@hneutr, can you take a look at the JOSS reviewer list (linked in the first comment in this issue), and see if anyone there might be a good fit? It would be preferable to have one person that has done a software review and has a been through the process here at JOSS before.

**Comment by hneutr** [comment]
Hey @cMadan — took a look at the list and, prioritizing for web-involved people with experience in Javascript and python, found three that seemed to me reasonably aligned with the project: krischer, wtgee, and Danbo3004. More than a few others would probably work, too, but these three were the ones that caught!

**Comment by cMadan** [comment]
@krischer @danbo3004 @wtgee, would you be interested/available to review this project for publication in JOSS? Thank you for considering!

**Comment by cMadan** [comment]
@vc1492a @danlurie @raamana, would you be interested/available to review this project for publication in JOSS? Thank you for considering!

**Comment by vc1492a** [comment]
@cMadan Thanks for considering - I'd be happy to provide a review, but it will be a few weeks until I sit down to get started due to a few other commitments and another JOSS review I am currently progressing through (referenced above). Looking at the repository, it looks like I won't be able to review the Matlab functionality, but would be able to review the Python functionality. Let me know how this sounds (either way)!

**Comment by raamana** [comment]
Thanks Chris for the invite. As much as I love to review this (I myself worked towards making such tools - look at [draw3dnx in graynet](https://github.com/raamana/graynet/blob/master/graynet/vis_network.py) which uses plotly also ) and contribute to JOSS, I am unfortunately very busy in the next few months (oversubscribed already). Late June or July is better time for me, but I hope the authors don't have to wait so long.

**Comment by cMadan** [comment]
@vc1492a, that sounds good to me. In that case, I'll assign you as reviewer and you can start (and let me know) when you're ready.

@raamana, no worries, thank you for considering! 

@jg-you, I'd like to also assign you as reviewer, if you're still interested. I think reviewing alongside another reviewer here would also be helpful in seeing how we do software reviews at JOSS. Let me know if that works for you!

@antoineallard, because of the conflict (co-author as friend), I won't assign you as a reviewer here. Please do look into how reviews work here, and it would be great to have you as a reviewer in the future!  You can sign-up to be on the reviewer list here: http://joss.theoj.org/reviewer-signup.html (@jg-you, please also feel free to add yourself!)

**Comment by cMadan** [comment]
@whedon add @vc1492a as reviewer

**Comment by whedon** [comment]
OK, @vc1492a is now a reviewer

**Comment by danlurie** [comment]
Thanks for inviting me, @cMadan. `webweb` looks like a really net and useful tool!

Unfortunately, like @raamana, I'm pretty much booked solid from now until early July. Hopefully you're not still looking for reviewers then, but if you are feel free to ping me again.

**Comment by cMadan** [comment]
@danlurie, no worries, thanks for considering!

**Comment by jg-you** [comment]
Sure I'll do it. I plan to have some time in early June.

**Comment by cMadan** [comment]
@jg-you, thank you for disclosing this, that's fine with me--but it is good to have that noted here in the pre-review.

I'll add you as a reviewer and start the review process.

**Comment by cMadan** [comment]
@whedon add @jg-you as reviewer

**Comment by whedon** [comment]
OK, @jg-you is now a reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1458. Feel free to close this issue now!
