### ISSUE TITLE
[PRE REVIEW]: AutoClassWrapper: a Python wrapper for AutoClass C classification

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1309]
**Submitting author:** @pierrepo (<a href="http://orcid.org/0000-0003-4177-3619">Pierre Poulain</a>)
**Repository:** <a href="https://github.com/pierrepo/autoclasswrapper" target ="_blank">https://github.com/pierrepo/autoclasswrapper</a>
**Version:** v1.4.1
**Editor:** @trallard
**Reviewers:** @rpetit3, @lowandrew

**Author instructions**

Thanks for submitting your paper to JOSS @pierrepo. **Currently, there isn't an JOSS editor assigned** to your paper.

@pierrepo if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1309 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1309/paper/paper.md): did not find expected key while parsing a block mapping at line 17 column 3 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@pierrepo - this pull request should fix your paper: https://github.com/pierrepo/autoclasswrapper/pull/11

**Comment by pierrepo** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by pierrepo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01309/joss.01309/10.21105.joss.01309.pdf)

**Comment by pierrepo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01309/joss.01309/10.21105.joss.01309.pdf)

**Comment by pierrepo** [comment]
The proof is OK for me.

**Comment by pierrepo** [comment]
Following @whedon recommendations, here is a list of potential reviewers (taken from this [list](https://bit.ly/joss-reviewers)):

- @rpetit3
- @jdeligt
- @a-slide
- @lowandrew
- @afrendeiro

**Comment by kyleniemeyer** [comment]
Hi @pierrepo, we need to assign an editor to handle your submission before reviewers—hang tight!

**Comment by kyleniemeyer** [comment]
@trallard could you edit this submission?

**Comment by trallard** [comment]
Sure @kyleniemeyer

**Comment by kyleniemeyer** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by kyleniemeyer** [comment]
Thanks @trallard!

**Comment by labarba** [comment]
👋 @trallard — it looks like this submission is waiting for you to assign reviewers, now that your back from `ooo`, yes?

**Comment by trallard** [comment]
Hi Pierre @pierrepo apologies for the long wait, let's get things moving now for you 😄 

Dear potential reviewers (@rpetit3 @jdeligt @a-slide @lowandrew @afrendeiro)

You all seem to have valuable expertise that could be used in this review, I am wondering if you have the time and bandwidth to help os review this submission?

**Title**: AutoClassWrapper: a Python wrapper for AutoClass C classification
**Repo**: [https://github.com/pierrepo/autoclasswrapper](https://github.com/pierrepo/autoclasswrapper)

**Summary**: AutoClass is an unsupervised Bayesian classification system.
AutoClass C is an implementation of the AutoClass algorithm made by the NASA.
AutoClassWrapper is a Python wrapper to ease the use of Autoclass C.

Submitting author: @pierrepo Pierren Poulain
Version: 1.4.1

**Comment by rpetit3** [comment]
Hi @trallard! 

I would be glad to help reviewing @pierrepo's manuscript/software.

Full disclosure, this will be my first time formally reviewing a manuscript/software. To help get started I have read through the [Review Checklist](https://joss.readthedocs.io/en/latest/review_checklist.html), but I still might stumble over some things (I'll do my best not to!). So, any advice, feedback, and/or instructions would be very much welcomed.

Depending on reviewer turn out, I will definitely understand if you'd like to choose a more experienced reviewer.

Thank you!
Robert

**Comment by lowandrew** [comment]
Hi @trallard!

I'm in very much the same boat as @rpetit3 with respect to software/review experience, but I'd be happy to review.

Thanks,
Andrew

**Comment by trallard** [comment]
Hi @rpetit3  and @lowandrew  this is great! Do not worry at all, the review process for JOSS is very comprehensive and I will monitor the review regularly to make sure you need as much guidance/support as needed 😄 

I am going to assign you as reviewers and see if any of the other folks are interested in reviewing before starting the process

**Comment by trallard** [comment]
@whedon  add @rpetit3 as reviewer

**Comment by trallard** [comment]
@whedon  add @lowandrew as reviewer

**Comment by trallard** [comment]
@whedon add @rpetit3 as reviewer

**Comment by whedon** [comment]
OK, @rpetit3 is now a reviewer

**Comment by trallard** [comment]
@whedon add @lowandrew as reviewer

**Comment by whedon** [comment]
OK, @lowandrew is now a reviewer

**Comment by jdeligt** [comment]
Hi Tania,

Thanks for considering me, but unfortunately I'm currently in the middle of
immigrating so won't have the time to handle this appropriately. Better
luck next time.

Best, Joep

**Comment by trallard** [comment]
No worries @jdeligt 

Ok let's us move to the formal review process

**Comment by trallard** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1390. Feel free to close this issue now!
