### ISSUE TITLE
[PRE REVIEW]: UralicNLP: An NLP library for Uralic Languages

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1310]
**Submitting author:** @mikahama (<a href="http://orcid.org/0000-0001-9315-1278">Mika K Hämäläinen</a>)
**Repository:** <a href="https://github.com/mikahama/uralicNLP" target ="_blank">https://github.com/mikahama/uralicNLP</a>
**Version:** v1.1.0
**Editor:** @gkthiruvathukal
**Reviewers:** @gweissman

**Author instructions**

Thanks for submitting your paper to JOSS @mikahama. **Currently, there isn't an JOSS editor assigned** to your paper.

@mikahama if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01310/joss.01310/10.21105.joss.01310.pdf)

**Comment by kyleniemeyer** [comment]
@gkthiruvathukal  would you be able to edit this submission?

**Comment by gkthiruvathukal** [comment]
@kyleniemeyer Yes.

**Comment by kyleniemeyer** [comment]
Thanks @gkthiruvathukal!

**Comment by kyleniemeyer** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
@Gweissman and @mbod, Would either or both of you be willing to contribute a review to this JOSS submission? This is a Python NLP project and would closely match your areas of interest.

**Comment by gweissman** [comment]
@gkthiruvathukal Thank you for thinking of me for the review. I could comment on things like documentation, ease of install, readability of software, and other user experience domains. However, I am completely unfamiliar with Uralic languages so could not comment on the accuracy of usefulness of the tool. Neither am I a computer scientist nor a linguist, so others may have more relevant expertise here. With the above caveats in mind, I'm happy to go ahead with a review if it would be helpful. Simultaneously, I'd be supportive of finding someone else with more relevant expertise who could offer substantive feedback.

**Comment by gkthiruvathukal** [comment]
Thanks, @gweissman. I don't see too much expertise in Uralic languages on the board, so we're all kind of in the same boat. I am mainly interested in evaluating the aspects you mentioned. I'm hoping we will get one other reviewer (@mbod). I will assign you and wait a bit longer to see if we can get a second reviewer.  Then we'll start review.

**Comment by gweissman** [comment]
Ok, sounds good.

**Comment by gkthiruvathukal** [comment]
@gweissman I think I will just assign you as the sole reviewer for now. It seems like you can handle this paper, unless you have to start speaking an Uralic language. (I don't speak one either.)  I will be available to help, should any questions arise during review.

**Comment by gkthiruvathukal** [comment]
@whedon assign @gweissman

**Comment by gkthiruvathukal** [comment]
@whedon assign @gweissman as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @gweissman

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1345. Feel free to close this issue now!
