### ISSUE TITLE
[PRE REVIEW]: MPIFiles.jl: A Julia Package for Magnetic Particle Imaging Files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1311]
**Submitting author:** @tknopp (<a href="http://orcid.org/0000-0002-1589-8517">Tobias Knopp</a>)
**Repository:** <a href="https://github.com/MagneticParticleImaging/MPIFiles.jl" target ="_blank">https://github.com/MagneticParticleImaging/MPIFiles.jl</a>
**Version:** v0.5.0
**Editor:** @brainstorm
**Reviewers:** @IgorBaratta

**Author instructions**

Thanks for submitting your paper to JOSS @tknopp. **Currently, there isn't an JOSS editor assigned** to your paper.

@tknopp if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01311/joss.01311/10.21105.joss.01311.pdf)

**Comment by tknopp** [comment]
Hi, I am very excited about JOSS and this is my first submission. Getting a domain expert for review will be somewhat challenging. I have found one reviewer with expertise in magnetic resonance imaging, which would be close enough. But maybe its more important that there is Julia expertise. In the end, my package is basically a file loading / storing library.

**Comment by arfon** [comment]
:wave: @arokem - do you think you could edit this submission for us?

**Comment by tknopp** [comment]
I have not seen him on the list of potential reviewers but @timholy would certainly be an excellent reviewer if he finds the time. Not a Julia expert but @MandyA could cover very well the MPI related part of the review (she is Python expert).

**Comment by labarba** [comment]
@brainstorm — Taking into account editor workloads at the moment, I'd like to assign this submission to you for handling. Can you take it on?

**Comment by brainstorm** [comment]
Sure! While I'm here I would like to ask for guidance on my QKD quantum
paper... The reviewer seems to have ghosted us mid-review, what's the best
course of action here?

Den sön 17 mars 2019 08:22Lorena A. Barba <notifications@github.com> skrev:

**Comment by labarba** [comment]
@whedon assign @brainstorm as editor

**Comment by whedon** [comment]
OK, the editor is @brainstorm

**Comment by brainstorm** [comment]
👋 @IgorBaratta, would you like to assist us reviewing this paper?

**Comment by IgorBaratta** [comment]
Sure.
But I'm already reviewing another JOSS paper, and I'll only be available from next week.

**Comment by brainstorm** [comment]
No worries @IgorBaratta, your expertise in this specific field is much appreciated for the review, we can start next week then!

**Comment by brainstorm** [comment]
@whedon assign @IgorBaratta as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @IgorBaratta

**Comment by brainstorm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1331. Feel free to close this issue now!
