### ISSUE TITLE
[REVIEW]: Kepler Mapper: A flexible Python implementation of the Mapper algorithm.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1315]
**Submitting author:** @sauln (<a href="http://orcid.org/0000-0002-8549-9810">Nathaniel Saul</a>)
**Repository:** <a href="https://github.com/scikit-tda/kepler-mapper" target ="_blank">https://github.com/scikit-tda/kepler-mapper</a>
**Version:** 1.3.3
**Editor:** @leouieda
**Reviewer:** @ixjlyons, @lmcinnes
**Archive:** <a href="https://doi.org/10.5281/zenodo.3485851" target="_blank">10.5281/zenodo.3485851</a>

## Status

[![status](http://joss.theoj.org/papers/f765cd0fe0c0eb7f071075f762d4f09d/status.svg)](http://joss.theoj.org/papers/f765cd0fe0c0eb7f071075f762d4f09d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f765cd0fe0c0eb7f071075f762d4f09d"><img src="http://joss.theoj.org/papers/f765cd0fe0c0eb7f071075f762d4f09d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f765cd0fe0c0eb7f071075f762d4f09d/status.svg)](http://joss.theoj.org/papers/f765cd0fe0c0eb7f071075f762d4f09d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/scikit-tda/kepler-mapper" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ixjlyons & @lmcinnes, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leouieda know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/scikit-tda/kepler-mapper">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.3.3
- [x] **Authorship:** Has the submitting author (@sauln) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/scikit-tda/kepler-mapper">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.3.3
- [x] **Authorship:** Has the submitting author (@sauln) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ixjlyons, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1315 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:58:in `block in build_affiliation_string': Problem with affiliations for Sam Mangham, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:57:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:57:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:109:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:109:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:106:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:106:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by leouieda** [comment]
@lmcinnes and @ixjlyons please read the reviewer guidelines (if you haven't already) and fill out the review checklist. If you open any issues or PRs in the software repository, please add `openjournals/joss-reviews#1315` to the description so we can keep track of the process. 

Please feel free to ping me at any time :bellhop_bell:

**Comment by leouieda** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1315 with the following error: 

 ORCID looks to be the wrong length
/app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:91:in `block in check_orcids': Problem with ORCID (XXXX-XXXX-XXXX-XXX) for Hendrik Jacob van Veen (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by leouieda** [comment]
Sorry, didn't see the paper on the master branch.

**Comment by sauln** [comment]
That's great, I didn't know Whedon could generate from a branch. 👯‍♂️

**Comment by leouieda** [comment]
Whedon is getting better and better :robot:

**Comment by leouieda** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01315/joss.01315/10.21105.joss.01315.pdf)

**Comment by leouieda** [comment]
@sauln one more fix to the paper formatting and we should be good to go (scikit-tda/kepler-mapper#155)

**Comment by leouieda** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1315 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    130      0 --:--:-- --:--:-- --:--:--   131
Error producing PDF.
! Argument of \caption@ydblarg has an extra }.
<inserted text> 
                \par 
l.327 Breast Cancer Dataset}}

Looks like we failed to compile the PDF

**Comment by sauln** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01315/joss.01315/10.21105.joss.01315.pdf)

**Comment by leouieda** [comment]
:wave: @ixjlyons @lmcinnes just a gentle reminder in case this fell through the cracks. Please let me know when you have a chance to start going through this submission.

**Comment by lmcinnes** [comment]
I can start working on it next week once I have SciPy2019 commitments out of the way.

**Comment by ixjlyons** [comment]
@leouieda Apologies, I hadn't forgotten about this but it got pushed around a bit. I started my review and I'll allocate some time this weekend to finish up the first pass.

**Comment by ixjlyons** [comment]
My review:

The purpose of Kepler Mapper is clear from the docs and paper, and it appears to me to fulfill that purpose. I appreciate the background page of the docs as well as the applications page. The tutorials take the documentation above and beyond a reference for library usage and look nice overall. The code seems to be structured sensibly and it looks like the library is quite flexible/extensible. The paper is clear and concise.

I think the examples page could use a little work. As it is now, there isn't really any information about the examples and there isn't really a connection to the source code. Something like [sphinx-gallery](https://sphinx-gallery.github.io/) would work well, especially if you could serve and link to the interactive HTML interface. Some information about the examples themselves would also be helpful, such as a description of the dataset and maybe some insight Mapper provides. 

There are [mutable default arguments](https://docs.python-guide.org/writing/gotchas/) in a handful of places. I didn't check thoroughly, but it appears to me that those objects are used in such a way that there shouldn't be a problem, and it may be totally intentional. I just wanted to bring it up to make sure the potential pitfalls were considered and avoided. 

Some minor things I noticed that didn't seem to warrant their own issues: 

- Typo in the paper, second paragraph: "We also an provide extensive..." -> "We also provide an extensive..."
- I think there may be some missing DOIs in the references.
- I'd consider hiding `SimplicialNerve` until it's implemented.
- The last example in the `KeplerMapper.project()` docstring should probably be moved/copied to the `fit_transform()` docstring.

Overall, Kepler Mapper appears to be in great shape. I recommend accepting.

**Comment by leouieda** [comment]
@ixjlyons thank you for your review and suggestions :clap: 

@sauln I see you've opened issues for the points raised by @ixjlyons (thank you for doing that). Please try to address these points, in particular the use of mutable defaults. This is a dangerous pitfall in Python that lead to extremely hard to catch bugs (I speak from experience).

**Comment by sauln** [comment]
@leouieda, will do. It'll probably take a week or two to finish up everything. I'll ping you once the changes have been made.

**Comment by leouieda** [comment]
:wave: Hi @lmcinnes, sorry to bug you again but please let us know when you have some time for the review/

**Comment by lmcinnes** [comment]
Sorry for being so slow. Once I got the time this went very quickly because everything was mostly very well laid out and easy to test and check. I agree with @ixjlyons that a sphinx-gallery style approach to the examples might be nice (and hopefully not that hard to set up).

You can also add DOIs for a few of the references. Carlssons paper is hDOI: 10.1090/S0273-0979-09-01249-X, and Edelsbrunner is DOI: 10.1007/978-3-540-33259-6_7.

Other than that it all meets the requirements and looks good to me.

**Comment by leouieda** [comment]
@lmcinnes thank you for your feedback!

 @sauln both reviews are very positive and there only a few minor things that need to be implemented. Please let us know when you've had time to implement the suggestions of both reviewers. To make it easier to track, here is a checklist (feel free to tick things off as you go):

- [ ] More contextual information for the examples
- [ ] Add missing DOIs
- [ ] Replace mutable default arguments
- [ ] Hide SimplicialNerve until it's implemented
- [ ] last example in the KeplerMapper.project() docstring should probably be moved/copied to the fit_transform() docstring
- [ ] Use sphinx-gallery for the documentation (optional but nice to have)

Take your time with these and please let us know if you want any clarifications or further input.

**Comment by sauln** [comment]
Thank you @leouieda, @lmcinnes, and @ixjlyons for taking the time to edit and review.  The feedback is encouraging and we are working on each of the changes that have been suggested. 

@leouieda, the past few weeks have been crazy for me, but I am working on the examples and mutable defaults currently. I hope to finish up within the next 2 weeks.  

I've created the checklist here, as github won't let me check your boxes.

- [ ] More contextual information for the examples
- [x] Add missing DOIs
- [ ] Replace mutable default arguments
- [x] Hide SimplicialNerve until it's implemented
- [x]  last example in the KeplerMapper.project() docstring should probably be moved/copied to the fit_transform() docstring
- [ ]   Use sphinx-gallery for the documentation (optional but nice to have)

**Comment by leouieda** [comment]
Hi @sauln no problem, take your time. I'll ask whedon to remind you in two weeks for an update just to keep us in the loop.

**Comment by leouieda** [comment]
@whedon remind @sauln in 2 weeks

**Comment by whedon** [comment]
Reminder set for @sauln in 2 weeks

**Comment by whedon** [comment]
:wave: @sauln, please update us on how things are progressing here.

**Comment by leouieda** [comment]
Hi @sauln let me know if you need more time. I can set another reminder.

**Comment by sauln** [comment]
At least another week. I have a [draft of the sphinx-gallery](https://kepler-mapper.scikit-tda.org/generated/gallery/index.html) working but it needs a little more work before completion.  

I've been convinced about the mutable defaults.  I think the best way will be to go with `cover=None` and then add the default rather than choosing a set of strings.

**Comment by leouieda** [comment]
@sauln no problem, take your time. I'll set a reminder just so we don't forget to check in.

**Comment by leouieda** [comment]
@whedon remind @sauln in 10 days

**Comment by whedon** [comment]
Reminder set for @sauln in 10 days

**Comment by whedon** [comment]
:wave: @sauln, please update us on how things are progressing here.

**Comment by leouieda** [comment]
@whedon remind @sauln in 10 days

**Comment by whedon** [comment]
Reminder set for @sauln in 10 days

**Comment by whedon** [comment]
:wave: @sauln, please update us on how things are progressing here.

**Comment by leouieda** [comment]
Hi @sauln, any updates on you progress? Please let me know if you need some more time or have any questions/concerns.

**Comment by leouieda** [comment]
@whedon remind @sauln in 10 days

**Comment by whedon** [comment]
Reminder set for @sauln in 10 days

**Comment by whedon** [comment]
:wave: @sauln, please update us on how things are progressing here.

**Comment by sauln** [comment]
woah! sorry for stringing you along all this time, but it's done @leouieda! The mutable default arguments are now removed and we have a basic gallery set up to showcase examples.

**Comment by leouieda** [comment]
Hi @sauln no problem, this has been a crazy month for me as well. I'll have a final look at the submission as soon as I get back from travel next week.

**Comment by labarba** [comment]
Hi everybody! What's the status of this review? I see no progress in the last month. Could you give us all a status update?

**Comment by leouieda** [comment]
Hi @labarba, I had a final look at the paper and everything seems good to go on my part. The author has addressed all of the major concerns of the reviewers. 

@sauln I'm happy to move on with acceptance of your paper :tada: Here are the steps you need to take now:

- Double check authors and affiliations (including ORCIDs)
- Make a release with the latest changes from the review and post the version number here.
- Archive the release on Zenodo/figshare and post the DOI here (make sure the title and author list matches the JOSS paper, if possible).

**Comment by sauln** [comment]
I'll have some time finish off these last 3 things next week.

@deargle, @mlwave, and @smangham, could you please all confirm your affiliations and orcids?

- [ ] Double check authors and affiliations (including ORCIDs)
- [ ] Make a release with the latest changes from the review and post the version number here.
- [ ] Archive the release on Zenodo/figshare and post the DOI here (make sure the title and author list matches the JOSS paper, if possible).

**Comment by deargle** [comment]
I confirm my orcid and affiliation. Thanks for heading this, @sauln.

**Comment by smangham** [comment]
I can confirm my name and affiliation, my ORCID is 0000-0001-7511-5652. Apologies for the delay and thanks for handling this @sauln!

**Comment by leouieda** [comment]
:wave: hi @sauln any progress updates on these tasks? Let me know when you're done so we can move on to publication.

**Comment by deargle** [comment]
Hi @leouieda, we published [an updated JOSS release to zenodo](https://zenodo.org/record/3485851), doi 10.5281/zenodo.3485851. Version number is 1.3.3 (took a few iterations to get the .zenodo.json formatting right)

Anything else you need from us?

**Comment by leouieda** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/srep01236 is OK
- 10.2312/SPBG/SPBG07/091-100 is OK
- 10.1007/978-3-540-33259-6_7 is OK
- 10.1090/S0273-0979-09-01249-X is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by leouieda** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01315/joss.01315/10.21105.joss.01315.pdf)

**Comment by leouieda** [comment]
@deargle looks good to me! I'm happy to pass this on for final acceptance into JOSS :tada:

**Comment by leouieda** [comment]
@whedon set 10.5281/zenodo.3485851 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3485851" target="_blank">10.5281/zenodo.3485851</a> is the archive.

**Comment by leouieda** [comment]
@whedon set 1.3.3 as version

**Comment by whedon** [comment]
OK. 1.3.3 is the version.

**Comment by leouieda** [comment]
@openjournals/joss-eics this submission is ready for acceptance and publication :confetti_ball:

**Comment by sauln** [comment]
Yay!! Thank you @ixjlyons and @lmcinnes for your reviews, @leouieda for your patience, @deargle for your help pushing it through the finish line!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/srep01236 is OK
- 10.2312/SPBG/SPBG07/091-100 is OK
- 10.1007/978-3-540-33259-6_7 is OK
- 10.1090/S0273-0979-09-01249-X is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@sauln here are some minor points in relation to your paper. 
- [ ] In "...data topoloigcal structures." fix the typo and consider rephrasing to "In "... topological data structures.""
- [ ] In "We leverage Scikit-Learn API-compatible cluster and scaling algorithms to construct network graphs in a flexible and user-friendly way.". Should you use "Scikit-Learn's" here? 
- [ ] If works like matplotlib (which currently have hyperlinks) have a reference for a citation, please use/add them. 
- [ ] I suggest the removal of the "Source code" section this the paper will contain a link to the repository already and the repository/readme should in term link to the documentation. 

- [ ] The references `[@edelsbrunner2010computational], [@carlsson2009topology].` are comma separated, can you amend the paper.md file so this is a grouped citation? I.e. like this: [@edelsbrunner2010computational; @carlsson2009topology]

**Comment by Kevin-Mattheus-Moerman** [comment]
@labarba can you help check the citation syntax for this paper? Are we happy about the use of `&` and `et al.` here?

**Comment by labarba** [comment]
In-text citations are not properly used.

When the citation is part of the sentence, it renders: Author (year). If the citation is not part of the sentence, then it should appear in parenthesis. E.g. “We take inspiration from Smith et al. (2006) to blah “ and “The code implements Theory 1 (Jones, 2012) and Theory 2 (Roberts, 2014) to obtain blah “  For the syntax to obtain brackets in the right places, see https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax

**Comment by deargle** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/srep01236 is OK
- 10.2312/SPBG/SPBG07/091-100 is OK
- 10.1007/978-3-540-33259-6_7 is OK
- 10.1090/S0273-0979-09-01249-X is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by deargle** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01315/joss.01315/10.21105.joss.01315.pdf)

**Comment by deargle** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01315/joss.01315/10.21105.joss.01315.pdf)

**Comment by deargle** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01315/joss.01315/10.21105.joss.01315.pdf)

**Comment by deargle** [comment]
@Kevin-Mattheus-Moerman I think I got everything from https://github.com/openjournals/joss-reviews/issues/1315#issuecomment-542142232. For point two, I changed the hyphenation to "Scikit-Learn-API-compatible ..."

@labarba I fixed the citation formatting.

Thinks look good to y'all?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/srep01236 is OK
- 10.2312/SPBG/SPBG07/091-100 is OK
- 10.1007/978-3-540-33259-6_7 is OK
- 10.1090/S0273-0979-09-01249-X is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1027

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1027, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by deargle** [comment]
Would you want me to make a new release with those bibliography fixes?

**Comment by Kevin-Mattheus-Moerman** [comment]
No that is okay. The main purpose is to archive the software. The paper can have minor changes.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1184923785033666561) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1028
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01315](https://doi.org/10.21105/joss.01315)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by Kevin-Mattheus-Moerman** [comment]
Congratulations @sauln! :tada: 
Thanks @ixjlyons, @lmcinnes for reviewing this work!!! :clap: 
Also thank you @leouieda for editing this submission.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01315/status.svg)](https://doi.org/10.21105/joss.01315)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01315">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01315/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01315/status.svg
   :target: https://doi.org/10.21105/joss.01315
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01315/status.svg)](https://doi.org/10.21105/joss.01315)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by deargle** [comment]
Thanks all! 

Not a huge deal, but I noted that the suggested citation on JOSS has an extra period in it after the title. Fixable?

![image](https://user-images.githubusercontent.com/1174653/67045968-8ffa3b80-f0ec-11e9-8c5e-e7c98f8dbcfe.png)

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev :point_up: can this be fixed?
