### ISSUE TITLE
[PRE REVIEW]: RAFF: Robust Algebraic Fitting Function in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1318]
**Submitting author:** @fsobral (<a href="http://orcid.org/0000-0003-4963-0946">Francisco Nogueira Calmon Sobral</a>)
**Repository:** <a href="https://github.com/fsobral/RAFF.jl" target ="_blank">https://github.com/fsobral/RAFF.jl</a>
**Version:** v0.4.1
**Editor:** @poulson
**Reviewers:** @abelsiqueira, @matbesancon

**Author instructions**

Thanks for submitting your paper to JOSS @fsobral. **Currently, there isn't an JOSS editor assigned** to your paper.

@fsobral if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1318 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1318 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@openjournals/joss-eics - the submitting author had suggested @poulson as the handling editor.

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1318 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:91:in `block in check_orcids': Problem with ORCID (0000-0000-0000-0000) for Ronaldo Lopes (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
👋 @fsobral - please see the error above from @whedon. The ORCID for one of your authors is invalid (you can simply remove this field if the author doesn't have one).

**Comment by labarba** [comment]
@poulson Could you edit this submission?

**Comment by fsobral** [comment]
Hello, @arfon . Sorry for this mistake. I have removed the invalid ORCID.

**Comment by fsobral** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01318/joss.01318/10.21105.joss.01318.pdf)

**Comment by labarba** [comment]
@whedon assign @poulson as editor

**Comment by whedon** [comment]
OK, the editor is @poulson

**Comment by poulson** [comment]
Thank you for moving forward with the assignment: I am travelling this week and am very happy to handle this submission!

**Comment by fsobral** [comment]
Thanks, this is excellent news. If you need a suggestion for a referee, I have already talked to @abelsiqueira, who was interesting in reviewing the algorithm.

**Comment by poulson** [comment]
Hi Abel (@abelsiqueira), would you be interested in reviewing this submission?

**Comment by abelsiqueira** [comment]
Yes, count me in.

**Comment by poulson** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by poulson** [comment]
@whedon add @abelsiqueira as reviewer

**Comment by whedon** [comment]
OK, @abelsiqueira is now a reviewer

**Comment by poulson** [comment]
Hi Jon (@malmaud): given your familiarity with Julia, would you be willing to serve as an additional reviewer on this submission?

Hi Scott (@stsievert): Would you be interested and able in serving as an additional reviewer on this submission?

Hi Jakob (@jakobbossek): Would you be interested and able in serving as an additional reviewer on this submission?

**Comment by stsievert** [comment]
I can provide a review, but it'll have to be after May. My plate will be full until then.

**Comment by jakobbossek** [comment]
I can assist in the reviewing process even though I have no experience with Julia (so far). However, I can start to review at the earliest in mid-april.

**Comment by malmaud** [comment]
I can't commit to a full review at this time. If, however, one of the other reviewers has a specific Julia-related technical question they encounter in the course of their review, I'd be happy to answer.

**Comment by poulson** [comment]
Thank you for your responses, Scott (@stsievert), Jakob (@jakobbossek), and Jon (@malmaud). Jakob, I will try to move forward with finding other reviewers and get back to you if for some reason they cannot be found in the next two weeks.

**Comment by poulson** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by poulson** [comment]
Hi Christopher (@ChrisRackauckas) -- you are one of the few reviewers listing both Julia and optimization in your expertise. Would you be able to help with this submission?

Hi Rowan (@rowanc1) -- you have listed both optimization and Julia in your expertise and I was hoping that you would be interesting and able to serve as a reviewer for this submission. Would you be willing to review this submission?

Hi Matheiu (@matbesancon -- I apologize for repeatedly requesting you to review, but you are one of the few reviewers explicitly listing both Julia and optimization in your expertise. Would you be willing and able to review this submission?

Hi Oscar (@oesteban) -- would you be interested and able to review this submission? I believe that your expertise in optimization would be of help, even though you list Python and not Julia in your core language expertise. 

Hi Andreas (@andim) -- would you be interested and able to review this submission? With your optimization, python, and C expertise, I believe you could be of help here.

**Comment by oesteban** [comment]
I'm swamped right now, sorry about that.

**Comment by matbesancon** [comment]
@poulson yes I'd be glad to review this paper

**Comment by ChrisRackauckas** [comment]
Sorry I will not be available right now.

**Comment by labarba** [comment]
@whedon add @matbesancon as reviewer

**Comment by whedon** [comment]
OK, @matbesancon is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1385. Feel free to close this issue now!
