### ISSUE TITLE
[PRE REVIEW]: UTDEventData: An R package to access political event data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1319]
**Submitting author:** @KateHyoung (<a href="http://orcid.org/0000-0002-0744-5884">Hyoungah Kim</a>)
**Repository:** <a href="https://github.com/KateHyoung/UTDEventData" target ="_blank">https://github.com/KateHyoung/UTDEventData</a>
**Version:** v1.0.0
**Editor:** @alexhanna
**Reviewers:** @briatte, @andrewheiss

**Author instructions**

Thanks for submitting your paper to JOSS @KateHyoung. **Currently, there isn't an JOSS editor assigned** to your paper.

@KateHyoung if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1319 with the following error: 

 ORCID looks to be the wrong length
/app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:91:in `block in check_orcids': Problem with ORCID (000-0002-9300-1576) for Latifur Khan (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
👋 @KateHyoung  - it looks like one of the ORCIDs is missing a `0` here?

**Comment by arfon** [comment]
@openjournals/joss-eics - the submitting author suggested @arokem as the handling editor.

**Comment by KateHyoung** [comment]
Thank you, @arfon, I have fixed it.

**Comment by KateHyoung** [comment]
As following @whedon recommendations, here is a list of potential reviewers

- @earino
- @andrewheiss
- @alexhanna
- @briatte

**Comment by briatte** [comment]
@KateHyoung Would be happy to review (and learn how reviewing for JOSS works in practice, by the same occasion)!

**Comment by andrewheiss** [comment]
I'm also fine reviewing!

**Comment by alexhanna** [comment]
Happy to see this in submission!

**Comment by labarba** [comment]
Since we already have two volunteers willing to contribute a review, I'll assign @alexhanna to handle as editor. Thanks everybody!

**Comment by labarba** [comment]
@whedon assign @alexhanna as editor

**Comment by whedon** [comment]
OK, the editor is @alexhanna

**Comment by labarba** [comment]
@whedon assign @briatte as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @briatte

**Comment by labarba** [comment]
@whedon add @andrewheiss as reviewer

**Comment by whedon** [comment]
OK, @andrewheiss is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1322. Feel free to close this issue now!
