### ISSUE TITLE
[PRE REVIEW]: Ramble: Higher-Order Functions for Parsing in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#132]
**Submitting author:** @chappers (<a href="http://orcid.org/0000-0002-2089-3796">Chapman Siu</a>)
**Repository:** <a href="https://github.com/chappers/Ramble/tree/master/joss-paper" target ="_blank">https://github.com/chappers/Ramble/tree/master/joss-paper</a>
**Version:** v0.1.1
**Editor:** @arfon
**Reviewer:** @pjotrp

**What this issue is for**

Thanks for submitting your paper to JOSS @chappers. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by arfon** [comment]
:wave: @wrathematics - would you be willing to review this submission for JOSS?

**Comment by arfon** [comment]
@noamross - would this also be a good candidate for rOpenSci?

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
Dear @chappers, before I look for a reviewer I would like to ask you why you think your project is relevant for science and do you have any applications in that area? Why is it not a proper R package with a vignette? I would like to read your PDF on slideshare, but to download it I need to register, something I will not do. Finally you'll need to make this FOSS with a proper license. Thanks.

**Comment by chappers** [comment]
Hi @pjotrp the details of the package and license can probably be easier viewed from the [CRAN link](https://cran.r-project.org/web/packages/Ramble/index.html), the software is already in a package form with license and [vignette](https://cran.r-project.org/web/packages/Ramble/vignettes/Higher-Order_Functions_for_Parsing_in_R.html). The slideshare file is irrelevant to the review. 

The key application of this package is allow a user to write a parser in R which is capable of handling context-free grammars. Besides this package there does not appear to be any way to write a parser within R. 

The applications could be in the data mining area when you have semi-structured data and are required to build a bespoke tool to parse strings into a data structure. It could also be used as a starting point for a compiler.

**Comment by pjotrp** [comment]
OK, my questions arise from reading the paper and the source tree. It will need to be clarified. All this information should be in either.

Do you know someone who could review your paper? Sorry for the delay, I was on a trip.

**Comment by pjotrp** [comment]
@chappers: can you suggest a reviewer?

**Comment by arfon** [comment]
> @chappers: can you suggest a reviewer?

@pjotrp - any luck finding a reviewer for this submission?

**Comment by pjotrp** [comment]
I guess @chappers did not find a reviewer. This is going to be relatively hard, but we can start. Sorry about the delay.

**Comment by noamross** [comment]
I can ping the rOpenSci crowd to see if someone is interested in reviewing this.

**Comment by pjotrp** [comment]
Thanks @noamross. Please do.

**Comment by pjotrp** [comment]
@arfon I am still trying for this one. If we don't find a reviewer could I become the reviewer (and you or someone the editor?)

**Comment by arfon** [comment]
> @arfon I am still trying for this one. If we don't find a reviewer could I become the reviewer (and you or someone the editor?)

That works for me. Shall we do it?

**Comment by pjotrp** [comment]
I have sent out one more request, let's wait until tomorrow.

**Comment by pjotrp** [comment]
@karthik do you think you can recommend someone to review this paper. The subject of parsing is somewhat off-tangent for the regular R-crowd, but I think the project is a worthwhile addition.

**Comment by pjotrp** [comment]
@arfon Since we are getting no pickup on this paper and I know something about R and parsers I'll take up review. I believe this is an exceptional situation.

**Comment by arfon** [comment]
@whedon assign @pjotrp as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @pjotrp

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/209. Feel free to close this issue now!

**Comment by arfon** [comment]
👍 many thanks in advance @pjotrp
