### ISSUE TITLE
[PRE REVIEW]: Meteo Browser South Tyrol: A Shiny App to download the meteorological time series from the Open Data Catalogue of the Province of Bolzano/Bozen - Italy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1320]
**Submitting author:** @GiulioGenova (<a href="http://orcid.org/0000-0001-9412-8651">Giulio Genova</a>)
**Repository:** <a href="https://github.com/GiulioGenova/MeteoBrowser" target ="_blank">https://github.com/GiulioGenova/MeteoBrowser</a>
**Version:** v1.0.1
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @GiulioGenova. **Currently, there isn't an JOSS editor assigned** to your paper.

@GiulioGenova if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01320/joss.01320/10.21105.joss.01320.pdf)

**Comment by arfon** [comment]
@openjournals/joss-eics the submitting author suggested @yochannah as the handling editor.

**Comment by labarba** [comment]
Hi  @GiulioGenova —thank you for your submission to JOSS. After pre-screening and consulting with other editors, we find the submission out of scope, falling in the 'minor utility' category. Please see our eligibility criteria at: https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements

Thanks for your interest in publishing with JOSS.
