### ISSUE TITLE
[REVIEW]: biotools: a package for optimization cluster analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1321]
**Submitting author:** @arsilva87 (<a href="http://orcid.org/0000-0003-2518-542X">Anderson da Silva</a>)
**Repository:** <a href="https://github.com/arsilva87/biotools" target ="_blank">https://github.com/arsilva87/biotools</a>
**Version:** 3.1
**Editor:** @karthik
**Reviewer:** @diyadas
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/2c266b2b63f172bc1b52ce4b89859a4e/status.svg)](http://joss.theoj.org/papers/2c266b2b63f172bc1b52ce4b89859a4e)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/2c266b2b63f172bc1b52ce4b89859a4e"><img src="http://joss.theoj.org/papers/2c266b2b63f172bc1b52ce4b89859a4e/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/2c266b2b63f172bc1b52ce4b89859a4e/status.svg)](http://joss.theoj.org/papers/2c266b2b63f172bc1b52ce4b89859a4e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/arsilva87/biotools" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@diyadas, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @karthik know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/arsilva87/biotools">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (3.1)?
- [x] **Authorship:** Has the submitting author (@arsilva87) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @diyadas it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01321/joss.01321/10.21105.joss.01321.pdf)

**Comment by karthik** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1093/bioinformatics/bts322 is OK
- 10.4155/bfs.13.5 is OK
- 10.1590/S0100-204X2013000600003 is OK
- 10.5897/AJAR2013.7588 is OK
- 10.1590/S0100-204X2007001000008 is OK

MISSING DOIs

- https://doi.org/10.1002/ajpa.1330120224 may be missing for title: Advanced statistical methods in biometric research
- https://doi.org/10.1002/9781118313718.part2 may be missing for title: The relative importance of characters affecting genetic divergence
- https://doi.org/10.3329/bjb.v43i3.21600 may be missing for title: Genetic diversity of chilli (Capsicum annuum L.) genotypes of India based on morpho-chemical traits

INVALID DOIs

- None
```

**Comment by karthik** [comment]
@arsilva87 Can you please remove `biotools_5.0.tar.gz` from the repo?

**Comment by arsilva87** [comment]
@karthik It was removed.

**Comment by karthik** [comment]
@arsilva87 Following up from the issue I raised in your repo, the reviewers and I are unable to install your software with reasonable effort. It's because of your dependency on rpanel, which requires a dated Tcltk widget called `BWidget`. Can you please articulate why you need these dependencies, how you are using them and why you are unable to refactor with modern alternatives? I'm pausing the review until we are able to resolve this.

**Comment by arsilva87** [comment]
@karthik The problem was solved by removing the dependencies with none or minimal losses, only for a single functionality of the package.

**Comment by arsilva87** [comment]
@whedon

**Comment by diyadas** [comment]
The README still directs users to install from CRAN, which I gather has not been updated. Installation proceeds with `devtools::install_github` - please update the README.

**Comment by arsilva87** [comment]
@diyadas README file updated.

**Comment by labarba** [comment]
@karthik — It looks like the author is asking for this review to be re-started. Can you get back in? I'm removing the "paused" label now.

**Comment by labarba** [comment]
@diyadas — Could you check on the author improvements, continue with your checklist, and report back to us with anything missing? Thank you!

**Comment by karthik** [comment]
@diyadas Do you need help continuing the review?

**Comment by diyadas** [comment]
Thanks for your patience. I've opened issues in your repo @arsilva87. I'll be happy to take a look again after they're addressed.

**Comment by labarba** [comment]
👋  @arsilva87 — Can you give us an update? If you're not close to done, please let me know of a time period to set a reminder for you.

**Comment by arsilva87** [comment]
@labarba I have updated the repository and worked on the issued pointed out by @diyadas. Thanks.

**Comment by labarba** [comment]
@karthik — please have a look at the progress here

**Comment by arsilva87** [comment]
@karthik How is the reviewing progress?

**Comment by arfon** [comment]
@diyadas & @karthik, many thanks for your efforts thus far. As I have outlined in my email to @arsilva87, this submission still falls well below what is expected of a JOSS submission. As such I am rejecting this submission and invite the author to resubmit if they are able to bring the submission up to standard.
