### ISSUE TITLE
[PRE REVIEW]: Native PDF Reader Library in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1323]
**Submitting author:** @sambitdash (<a href="http://orcid.org/0000-0003-4856-7244">Sambit Kumar Dash</a>)
**Repository:** <a href="https://github.com/sambitdash/PDFIO.jl" target ="_blank">https://github.com/sambitdash/PDFIO.jl</a>
**Version:** v0.1.1
**Editor:** @alexhanna
**Reviewers:** @jameshclrk, @malmaud

**Author instructions**

Thanks for submitting your paper to JOSS @sambitdash. **Currently, there isn't an JOSS editor assigned** to your paper.

@sambitdash if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1323 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@sambitdash - :wave: thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](http://joss.theoj.org/about#submission_requirements). In particular, this item:

> - Your software should have an obvious research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)? The section [_'what should my paper contain'_](http://joss.theoj.org/about#paper_structure) has some guidance for the sort of content we're looking to be present in the `paper.md`.

Many thanks!

**Comment by sambitdash** [comment]
From the said site I gather JOSS is interested in the following areas:

> JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or the execution of research experiments; **extracts knowledge from large data sets**; offers a mathematical library, or similar.

There is no in-built native tool in Julia to read PDF files and extract text from documents. This tool enables you to achieve that. I guess from that perspective, it fits into the area of interest JOSS has defined for itself. Implementation of PDF Library from scratch is a fairly non-trivial task which has been achieved in this exercise using a new programming language.

**Comment by sambitdash** [comment]
@arfon Sorry I may have misunderstood. Are you suggesting, I provide a detailed description as `paper.md` template? Should I check it in the PDFIO.jl repositiory?

**Comment by arfon** [comment]
> @arfon Sorry I may have misunderstood. Are you suggesting, I provide a detailed description as paper.md template? Should I check it in the PDFIO.jl repositiory?

Yes please. Please review the submission guidelines here: https://joss.readthedocs.io/en/latest/submitting.html#submitting-a-paper-to-joss

**Comment by danielskatz** [comment]
I'm going to mark this as paused until we hear back from @sambitdash

**Comment by sambitdash** [comment]
@danielskatz Thanks for the update. I will take a few more days to complete the paper submission.

**Comment by danielskatz** [comment]
👋 @sambitdash - any news?  We could just remove this paper for now, and let you resubmit when you are ready...  Or if you are close to having a paper written and in your repo, and want to proceed soon, let us know.

**Comment by sambitdash** [comment]
@danielskatz Sorry for the delay on my part. I will be able to submit the paper by the end of this week. If that's not too late will request to keep this request active for now.

**Comment by sambitdash** [comment]
@danielskatz submitted the paper in the Github folder. Kindly, review the submission and provide your feedback.

**Comment by danielskatz** [comment]
You can also issue the command I'm going to give next, by putting the same text in a new comment, in case the paper isn't quite right in your opinion, or if anything fails in the build.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01323/joss.01323/10.21105.joss.01323.pdf)

**Comment by danielskatz** [comment]
@sambitdash - note there are some issues with your reference that you can fix - otherwise, thanks, this looks fine to proceed, which we will do

**Comment by danielskatz** [comment]
👋 @yochannah - would you be willing to edit this submission?

**Comment by sambitdash** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01323/joss.01323/10.21105.joss.01323.pdf)

**Comment by sambitdash** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by sambitdash** [comment]
@whedon generate pdf from branch debug

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch debug. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01323/joss.01323/10.21105.joss.01323.pdf)

**Comment by sambitdash** [comment]
Looks like @@whendon is picking up the older files still. I did some modification to the files I am hopeful that should fix the issues as such.

**Comment by sambitdash** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01323/joss.01323/10.21105.joss.01323.pdf)

**Comment by sambitdash** [comment]
Looks like @@whendon is picking up the older files still. I did some modification to the files I am hopeful that should fix the issues as such.

**Comment by sambitdash** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01323/joss.01323/10.21105.joss.01323.pdf)

**Comment by sambitdash** [comment]
@whedon  generate pdf

**Comment by sambitdash** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01323/joss.01323/10.21105.joss.01323.pdf)

**Comment by sambitdash** [comment]
The reference issue is now addressed.

**Comment by danielskatz** [comment]
👋 @yochannah - ping...

**Comment by danielskatz** [comment]
👋 @alexhanna - would you be willing to edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon assign @alexhanna as editor

**Comment by whedon** [comment]
OK, the editor is @alexhanna

**Comment by alexhanna** [comment]
Hi @sambitdash, can you suggest some reviewers for this? You can also get some suggestions on list of potential reviewers mentioned in the first message of this issue.

**Comment by sambitdash** [comment]
malmaud, jameshclrk, ChrisRackauckas can be comfortable with the Julia Language I guess.

**Comment by alexhanna** [comment]
@malmaud, @jameshclrk, @ChrisRackauckas -- are any of you available to edit this submission?

**Comment by arfon** [comment]
> @malmaud, @jameshclrk, @ChrisRackauckas -- are any of you available to edit this submission?

By edit, you mean _review_ right 😃

**Comment by alexhanna** [comment]
YES. Sorry. It's still before 8 AM here. :P

**Comment by jameshclrk** [comment]
I'm happy to review this at the weekend, hope that's ok!

**Comment by alexhanna** [comment]
@whedon assign @jameshclrk as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jameshclrk

**Comment by alexhanna** [comment]
Wonderful, thanks! @malmaud or @ChrisRackauckas, do you have any interest in joining on?

**Comment by ChrisRackauckas** [comment]
Sorry I will not have the time

**Comment by malmaud** [comment]
Ya I can review this weekend.

**Comment by alexhanna** [comment]
Excellent.

**Comment by alexhanna** [comment]
@whedon add @malmaud as reviewer

**Comment by whedon** [comment]
OK, @malmaud is now a reviewer

**Comment by alexhanna** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1453. Feel free to close this issue now!
