### ISSUE TITLE
[PRE REVIEW]: Stripy: A Python module for (constrained) triangulation in Cartesian coordinates and on a sphere

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1324]
**Submitting author:** @lmoresi (<a href="http://orcid.org/0000-0003-3685-174X">Louis Moresi</a>)
**Repository:** <a href="https://github.com/underworldcode/stripy" target ="_blank">https://github.com/underworldcode/stripy</a>
**Version:** 0.7.0
**Editor:** @VivianePons
**Reviewers:** @santisoler

**Author instructions**

Thanks for submitting your paper to JOSS @lmoresi. **Currently, there isn't an JOSS editor assigned** to your paper.

@lmoresi if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1324 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1324 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1324 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    145      0 --:--:-- --:--:-- --:--:--   144
Error reading bibliography ./paper.bib (line 8, column 1):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@lmoresi - please take a look at the errors above with your bibtex file. If you make fixes in your `paper` branch you can recompile with `@whedon generate pdf from branch paper`

**Comment by arfon** [comment]
@openjournals/joss-eics - the submitting author suggested `@lheagy` as the handling editor.

**Comment by lmoresi** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01324/joss.01324/10.21105.joss.01324.pdf)

**Comment by lmoresi** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01324/joss.01324/10.21105.joss.01324.pdf)

**Comment by lmoresi** [comment]
I fixed a couple of (unimportant) bugs in the paper that were obvious once I looked at the pdf ... not sure if whedon is listening to me any more though.

**Comment by lmoresi** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01324/joss.01324/10.21105.joss.01324.pdf)

**Comment by labarba** [comment]
👋 @VivianePons — Taking into account editor workloads at the moment, I'd like to assign this submission to you for handling. Can you take it on?

**Comment by labarba** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by VivianePons** [comment]
I have just emails to ask @margauxmouchene and @kmarkert for reviews

**Comment by VivianePons** [comment]
@lmoresi I have trouble finding available reviewers, do you have any suggestions?

**Comment by lmoresi** [comment]
> @lmoresi I have trouble finding available reviewers, do you have any suggestions?

We're discussing the possible choices. A queston of joss etiquette - is it appropriate to name people here in the open forum ?

**Comment by VivianePons** [comment]
We usually do it that way but if you'd rather send me an email about it, please do so.

**Comment by lmoresi** [comment]
It's fine. I just wanted to make sure there were no privacy issues. We have the following suggestions that are mainly from the Earth Science side as we think that is the primary audience for stripy and maybe that will help. We also suggest contacting professor Renka whose original code we wrapped as the starting point for the package (email details below)

  - Paul Wessel (U. Hawaii) - pwessel_at_hawaii.edu - PaulWessel on github
  - Simon Williams (Northwest University, Xi’an, China) - contact details TBA
  - Thorsten Becker (UT Austin) -  twb_at_ig.utexas.edu  - thwbecker on github
  - Robert Renka (U. North Texas ) - robert.renka_at_unt.edu

**Comment by lmoresi** [comment]
@VivianePons - did you have any luck with those suggestions or would you like us to extend the list ? (also, fyi, @brmather)

**Comment by VivianePons** [comment]
I have asked 10 people so far, and I got either no response or too busy. At the moment, I'm waiting for an answer from Robert Renka and another person who was suggested by busy people.

**Comment by VivianePons** [comment]
@whedon assign @santisoler as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @santisoler

**Comment by VivianePons** [comment]
Good news! We have one confirmed reviewer. I would still feel more comfortable with a second one. Anyway, this has been taking quite some time already so I will create the review issue right now and add the second reviewer when I find someone.

**Comment by VivianePons** [comment]
@whedon create review

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1410. Feel free to close this issue now!
