### ISSUE TITLE
[PRE REVIEW]: Manif: A micro Lie theory library for state-estimation in robotics applications

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1325]
**Submitting author:** @artivis (<a href="http://orcid.org/0000-0001-5279-8251">Jeremie Deray</a>)
**Repository:** <a href="https://github.com/artivis/manif" target ="_blank">https://github.com/artivis/manif</a>
**Version:** branch: joss
**Editor:** @poulson
**Reviewers:** @jordigh, @drvinceknight, @alex-konovalov

**Author instructions**

Thanks for submitting your paper to JOSS @artivis. **Currently, there isn't an JOSS editor assigned** to your paper.

@artivis if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1325 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1325 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0     91      0 --:--:-- --:--:-- --:--:--    92
Error reading bibliography ./paper.bib (line 38, column 3):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@openjournals/joss-eics - the submitting author suggested @poulson as the handling editor.

**Comment by arfon** [comment]
@artivis - thanks for your submission to JOSS. Please fix the errors in your bibtex and check the fixes work with the command `@whedon generate pdf from branch joss`

**Comment by artivis** [comment]
@arfon thank you for the prompt notification.

@whedon generate pdf from branch joss

**Comment by artivis** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01325/joss.01325/10.21105.joss.01325.pdf)

**Comment by artivis** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01325/joss.01325/10.21105.joss.01325.pdf)

**Comment by labarba** [comment]
Hi @poulson — Can you edit this submission? It depends en the [Eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page) library. Maybe you can get someone on their team to review?

@artivis — Please help us by recommending some reviewers. Find a link to folks who have signed up to review for JOSS in the welcome post by `@whedon`, above.

**Comment by artivis** [comment]
@labarba That's a fairly long list, I will browse it fully later today. In the meantime I already spotted @vissarion & @kpeeters as potential reviewers.

**Comment by artivis** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01325/joss.01325/10.21105.joss.01325.pdf)

**Comment by artivis** [comment]
Is there a way to properly generate the pdf locally (on my machine) so that I can fix the small formatting issue here and there before pushing and bothering whedon ?? ^^

**Comment by artivis** [comment]
Potential reviewers : @vissarion, @kpeeters, @vijaysm, @jizecn, @nnadeau, @traversaro, @carlosjoseRG

**Comment by labarba** [comment]
@whedon assign @poulson as editor

**Comment by whedon** [comment]
OK, the editor is @poulson

**Comment by poulson** [comment]
Thank you for moving forward with the assignment: I am travelling this week and am very happy to handle this submission!

@labarba, I happen to be working on contributing code to Eigen this last week, so I think I could definitely reach out!

**Comment by vissarion** [comment]
@artivis @poulson I am reviewing another paper at the moment so I have not time for this, sorry. But if you do not find reviewers after two weeks or so please ping me again.

**Comment by nnadeau** [comment]
unfortunately, I am not available to review at this time.

**Comment by vijaysm** [comment]
@poulson I expect to go on paternity leave for couple of weeks soon and so will be unavailable to review. However, I will keep an eye out on the JOSS issues page if I do find time.

**Comment by poulson** [comment]
Hi @jordigh -- Given your expertise in mathematics and numerical analysis, would you be willing and able to serve as a reviewer for this submission? (Please excuse me not using your name -- it is not listed on your GitHub profile.)

Hi Alexander (@alex-konovalov) -- Given your mathematics expertise, would you be willing and able to serve as a reviewer for this submission?

Hi Scott (@stsievert) -- I know that I just contacted you about reviewing another submission, but, given your mathematics expertise, would you be willing to review this submission?

Hi Vince (@drvinceknight) -- Given your mathematics expertise, would you be willing and able to review this submission?

**Comment by stsievert** [comment]
I'm still swamped. I can provide a review after May.

I'm not too familiar with C++, but have glanced at the repo and think I would encourage @artivis to look at the [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html).

**Comment by artivis** [comment]
Hi @stsievert, thanks for feedback. I did have a look at the [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html), can I ask you to be more specific ?

**Comment by stsievert** [comment]
> can I ask you to be more specific ?

* When I looked at the documentation (https://codedocs.xyz/artivis/manif/), the splash screen for me loaded with a blank screen. Same with the wiki.
* The review mentions "a clear statement of need". I know there's a short statement of need on the README: "manif is a header-only c++11 Lie theory library for state-estimation targeted at robotics applications". I don't think that's clear. I think this definition would be clear if most words could be expanded into a paragraph. Why should I care about "header-only c++11", "Lie theory", "state estimation" or "robotics application"?

**Comment by artivis** [comment]
Thanks for the precision.  
- It seems that there is indeed an issue with the splash screen of the online documentation, I'll fix that. The wiki's one is yet to be done.
- I guess I can beef up the statement a little :+1:

**Comment by alex-konovalov** [comment]
Hi @poulson - thanks for the suggestion, I can try to evaluate its usability and mathematical functionality, but I am not experienced in C++ and will not be able to comment on that. If you can counterbalance this by appropriate C++ skills of another reviewer, then I will be happy to do this.

**Comment by drvinceknight** [comment]
Hi @poulson, I'm very happy to act as a review however, much like @alex-konovalov my C++ expertise is limited.

**Comment by jordigh** [comment]
I can be a reviewer. I know C++ and Lie algebras/groups.

**Comment by poulson** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by poulson** [comment]
@whedon add @jordigh as reviewer

**Comment by whedon** [comment]
OK, @jordigh is now a reviewer

**Comment by poulson** [comment]
@whedon add @drvinceknight as reviewer

**Comment by whedon** [comment]
OK, @drvinceknight is now a reviewer

**Comment by poulson** [comment]
@whedon add @alex-konovalov as reviewer

**Comment by whedon** [comment]
OK, @alex-konovalov is now a reviewer

**Comment by poulson** [comment]
Thank you for your informative responses, Alex (@alex-konovalov), Vince (@drvinceknight), and @jordigh! Between the three of you, we should have our bases covered!

**Comment by poulson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1371. Feel free to close this issue now!
