### ISSUE TITLE
[REVIEW]: rdbsp: An Open Source Rock Dynamic Behavior Simulation Program

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1328]
**Submitting author:** @zhangning737 (<a href="http://orcid.org/0000-0003-3597-0691">Zhang Ning</a>)
**Repository:** <a href="https://github.com/zhangning737/rdbsp.git" target ="_blank">https://github.com/zhangning737/rdbsp.git</a>
**Version:** v1.0.0
**Editor:** @lheagy
**Reviewers:** @dvalters, @srmnitc
**Archive:** <a href="https://doi.org/10.5281/zenodo.3335406" target="_blank">10.5281/zenodo.3335406</a>

## Status

[![status](http://joss.theoj.org/papers/5199f1a2669daae8f9932d7982a34d4c/status.svg)](http://joss.theoj.org/papers/5199f1a2669daae8f9932d7982a34d4c)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/5199f1a2669daae8f9932d7982a34d4c"><img src="http://joss.theoj.org/papers/5199f1a2669daae8f9932d7982a34d4c/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/5199f1a2669daae8f9932d7982a34d4c/status.svg)](http://joss.theoj.org/papers/5199f1a2669daae8f9932d7982a34d4c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/zhangning737/rdbsp.git" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dvalters, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lheagy know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/zhangning737/rdbsp.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@zhangning737) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/zhangning737/rdbsp.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@zhangning737) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dvalters it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01328/joss.01328/10.21105.joss.01328.pdf)

**Comment by lheagy** [comment]
@dvalters, many thanks for being willing to review! Above there is a checklist to help guide your review. Please let me know if you have any questions or if I can provide any clarification.

**Comment by lheagy** [comment]
👋 Hi @dvalters, just checking in this review. Please let me know if you have any questions.

**Comment by lheagy** [comment]
👋 Hi @dvalters, checking in on this - when do you think you will have time to start your review? Thanks!

**Comment by dvalters** [comment]
Oh sorry @lheagy - totally slipped my mind. Will start tonight 👍

Apologies!

**Comment by lheagy** [comment]
Many thanks @dvalters, please let me know if you have any questions along the way

**Comment by dvalters** [comment]
Apologies for the delay to my review @lheagy, @zhaozhang, this has been due to difficulty in obtaining access to the proprietary Intel compiler required for the installation process. 

Can I ask @lheagy, would this requirement be a barrier to acceptance in JOSS? 

@zhaozhang , is there a way to compile this with an open-source compiler (i.e. gcc) ?

**Comment by danielskatz** [comment]
👋 @dvalters - you've written to @zhaozhang above, but the software is by @zhangning737

**Comment by dvalters** [comment]
Apolgies @zhangning737, my question was if there is a way to compile with an open source compiler, or plans to include this functionality in the near future?

**Comment by lheagy** [comment]
Thanks @dvalters! I have started issue zhangning737/rdbsp#1 to discuss compiler options. @zhangning737: could you please provide some pointers on where to access compilers for the code? It would be preferable if this could be achieved with an open source compiler. If this is not possible, I will check with the editorial board on any concerns for acceptance.

**Comment by zhangning737** [comment]
@lheagy @dvalters Actually[ Intel compiler ](https://software.intel.com/en-us/parallel-studio-xe/choose-download)provide free license to open source contributors. I think just refer this repo could get a free license. Here chooses intel compiler since this software using a mkl subroutine. Of cource it could be compiled with gcc and vc community after minor changes. But I think Intel complier provides long term supports for open source community.

**Comment by lheagy** [comment]
Thanks @zhangning737. @dvalters: can you give it a try with the link that @zhangning737 provided? If you run into any issues, one option we have is to try installing on [mybinder.org](http://mybinder.org)

**Comment by lheagy** [comment]
:wave: Just checking in @dvalters: were you able to get up and running? or would it be beneficial for @zhangning737 to set up a binder-demo?

**Comment by lheagy** [comment]
Hi @dvalters, would you be willing to take another look at this submission? If so, do you have a time-estimate of when you can get to it? If not, please let me know. Thanks!

**Comment by lheagy** [comment]
And just a note @zhangning737: if we don't hear back by early next week, I will begin looking for another reviewer to jump in. Thanks for your patience

**Comment by zhangning737** [comment]
@lheagy no problem...

**Comment by lheagy** [comment]
:wave: Hi @jordigh, would you be willing to jump in on this review for JOSS?

**Comment by lheagy** [comment]
:wave: Hi @danehkar and @srmnitc would you be willing to review this submission for JOSS? The review is already in progress thanks to the help of @dvalters, but we are in need of reviewers to help on the next revision. If you are not able to but have suggestions of other possible reviewers, I would be grateful. Thanks!

**Comment by srmnitc** [comment]
Hi @lheagy , I think I can help with the review process.

**Comment by lheagy** [comment]
@whedon add @srmnitc as reviewer

**Comment by whedon** [comment]
OK, @srmnitc is now a reviewer

**Comment by lheagy** [comment]
:wave: @srmnitc, just checking here. Do you think you will have time in the next week to take a look at this submission? Thanks!

**Comment by srmnitc** [comment]
@lheagy yes definitely. I am currently travelling, but I will definitely be able to take a look in the next few days.

**Comment by lheagy** [comment]
Many thanks @srmnitc! Safe travels

**Comment by srmnitc** [comment]
@zhangning737 @lheagy I was finally able to try compiling the code, but I was not successful. I am not sure if its a specific issue with my setup, but in any case, I am of the opinion that there should be more detailed instructions to compile successfully. I have created an [issue on the repo](https://github.com/zhangning737/rdbsp/issues/2#issue-462378692)

**Comment by srmnitc** [comment]
@zhangning737 I have also raised an issue with citations and generally citations of books. @lheagy I am reviewing for the first time, so, do I have to take into account typos and other issues in the paper text?

**Comment by lheagy** [comment]
@srmnitc: If you are willing to point out typos as you spot them (or create a pull request to fix them), that would be much appreciated!

**Comment by srmnitc** [comment]
@lheagy thanks! Fixed some typos and created a pull request now.

**Comment by zhangning737** [comment]
@srmnitc compiling error might relate to the newly update of intel compiler, I'll check it with the newest version. Thanks.

**Comment by zhangning737** [comment]
@lheagy Already pull the request. @srmnitc Please check the configuration model of Intel Compiler. I think I should add that to documentation.

**Comment by lheagy** [comment]
Thanks @zhangning737. @srmnitc, would you be willing to take a look at the updates?

**Comment by srmnitc** [comment]
@lheagy just finished looking at it. Most issues are now fixed - installation and tests work perfectly except for some minor changes which I have kept open as an issue. The DOIs on the paper are incomplete, so I have kept the issue open.

**Comment by srmnitc** [comment]
@lheagy @zhangning737 I still think a better documentation is required - the existing one is complete, but inaccessible from a non specialist perspective. A detailed documentation with example usage would be a recommendation for the future.

**Comment by srmnitc** [comment]
@lheagy @zhangning737 There are only two issues holding back my review - 1) the DOIs of references are not complete 2) There is no release version of github

**Comment by zhangning737** [comment]
@srmnitc Thanks for your advice, the documentation will be improved with more detailed information. @lheagy @srmnitc The DOIs have been added, and removed the debug option and added a tag for release...

**Comment by srmnitc** [comment]
@lheagy @zhangning737  I think all the points in the checklist are okay now. So, I have finished my review. Thanks for all the quick updates  @zhangning737!

**Comment by lheagy** [comment]
Excellent, many thanks for your review @srmnitc!

**Comment by lheagy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01328/joss.01328/10.21105.joss.01328.pdf)

**Comment by lheagy** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1201/9781315391304 is OK
- 10.1016/j.tust.2015.06.006 is OK
- 10.1007/s002110050020 is OK
- 10.1016/B978-0-08-044606-6.X5000-0 is OK
- 10.1016/C2009-0-24909-9 is OK
- 10.1002/nme.1620170504 is OK
- 10.1016/0749-6419(90)90007-2 is OK
- 10.1002/eqe.4290160314 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lheagy** [comment]
👋 Hi @zhangning737, I started pr zhangning737/rdbsp#6 with a few minor grammatical updates to the paper. Please take a look when you have a chance.

**Comment by zhangning737** [comment]
@lheagy Thank you for your revisions. Looks better now... Already pulled...

**Comment by lheagy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01328/joss.01328/10.21105.joss.01328.pdf)

**Comment by lheagy** [comment]
Excellent, thanks @zhangning737, can you please take a  look at the article proof and make sure everything is in order? Once you are happy with it, please generate a new software release and archive it on [zenodo](http://zenodo.org) or similar and set the title and author of the archive to be the same as that in your paper. After that, please post the doi here and we can proceed with publication.

**Comment by lheagy** [comment]
👋 Hi @zhangning737, just checking in. Whenever you have a chance to create a new release and archive your software, please post the doi here. Thanks!

**Comment by zhangning737** [comment]
@lheagy Just changed 3 words in the last paragraph of paper.

Already upload to ``` zenodo ``` and the DOI is:

```10.5281/zenodo.3335406```

Is the DOI alright? seems a little bit odd...
If there anything else need to be done, please let me know. Thanks...

**Comment by lheagy** [comment]
Thanks @zhangning737! And sorry for my delay, I just returned from a conference.  The archive looks good!

**Comment by lheagy** [comment]
@whedon set 10.5281/zenodo.3335406 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3335406" target="_blank">10.5281/zenodo.3335406</a> is the archive.

**Comment by lheagy** [comment]
:wave: @openjournals/jose-eics, this submission is ready to be published! One reviewer did not fully complete the review, so please let me know if you need me to jump in and explicitly check off those items as a third reviewer. Thanks!

**Comment by lheagy** [comment]
👋 @openjournals/joss-eics, this submission is ready to be published! One reviewer did not fully complete the review, so please let me know if you need me to jump in and explicitly check off those items as a third reviewer. Thanks!

**Comment by kyleniemeyer** [comment]
Hi @zhangning737, it looks like you deleted the JOSS paper file in your latest commit (https://github.com/zhangning737/rdbsp/commit/52742007231dba84846a82a38bf398f9dafa75f7). Can you add that back?

**Comment by zhangning737** [comment]
@kyleniemeyer my fault, mis remove it when due with some conflict... added it back now...

**Comment by kyleniemeyer** [comment]
Thanks @zhangning737. Could you next merge the pull request I just submitted, which made a few minor edits to the paper? https://github.com/zhangning737/rdbsp/pull/7

**Comment by zhangning737** [comment]
@kyleniemeyer thanks for the revisions, already pulled...

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01328/joss.01328/10.21105.joss.01328.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/858

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/858, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by BarryDeCicco** [comment]
I do not want to be involved with JOSS any more.  I would really appreciate it if somebody would remove me from this.  I've running at a rate of 50 e-mails this morning alone.
Barry

    On Thursday, July 25, 2019, 12:20:10 PM EDT, whedon <notifications@github.com> wrote:  
 
 
Check final proof 👉 openjournals/joss-papers#858

If the paper PDF and Crossref deposit XML look good in openjournals/joss-papers#858, then you can now move forward with accepting the submission by compiling again with the flag deposit=true e.g.
@whedon accept deposit=true

**Comment by kyleniemeyer** [comment]
Hi @BarryDeCicco, you are likely subscribed to all notifications from the `joss-reviews` repo, which happens by default when you are added as a reviewer. (And would lead to quite a lot of unnecessary notifications.) You can fix this by going to the "Watch" dropdown at the top of the page, and changing to "not watching": 


![](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1154430479480819713) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/859
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01328](https://doi.org/10.21105/joss.01328)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @zhangning737 on your paper's publication in JOSS! Thanks to @dvalters and @srmnitc for reviewing, and @lheagy for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01328/status.svg)](https://doi.org/10.21105/joss.01328)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01328">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01328/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01328/status.svg
   :target: https://doi.org/10.21105/joss.01328
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01328/status.svg)](https://doi.org/10.21105/joss.01328)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by BarryDeCicco** [comment]
Thank you, Kyle!  I’ve set myself to ‘ignoring’.
Barry
    On Thursday, July 25, 2019, 12:36:04 PM EDT, Kyle Niemeyer <notifications@github.com> wrote:  
 
 
Hi @BarryDeCicco, you are likely subscribed to all notifications from the joss-reviews repo, which happens by default when you are added as a reviewer. (And would lead to quite a lot of unnecessary notifications.) You can fix this by going to the "Watch" dropdown at the top of the page, and changing to "not watching":
