### ISSUE TITLE
[PRE REVIEW]: corporaexplorer: an R package for dynamic exploration of text collections

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1329]
**Submitting author:** @kgjerde (<a href="http://orcid.org/0000-0001-8291-6837">Kristian Lundby Gjerde</a>)
**Repository:** <a href="https://github.com/kgjerde/corporaexplorer" target ="_blank">https://github.com/kgjerde/corporaexplorer</a>
**Version:** v0.4.0
**Editor:** @leouieda
**Reviewers:** @kbenoit, @trinker

**Author instructions**

Thanks for submitting your paper to JOSS @kgjerde. **Currently, there isn't an JOSS editor assigned** to your paper.

@kgjerde if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01329/joss.01329/10.21105.joss.01329.pdf)

**Comment by arfon** [comment]
:wave: @leouieda - would you be willing to edit this submission for JOSS?

**Comment by leouieda** [comment]
@arfon sure thing :+1:

**Comment by leouieda** [comment]
@whedon assign @leouieda as editor

**Comment by whedon** [comment]
OK, the editor is @leouieda

**Comment by leouieda** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1080/19312458.2017.1387238 is OK
- 10.1126/science.1167742 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by leouieda** [comment]
:wave: Hi @kgjerde, I'll be handling your submission and will start looking for reviewers so we can get this started.

**Comment by kgjerde** [comment]
@leouieda: Great – thanks!

As per whedon's instructions: I think @andrewheiss, @kbenoit, and @trinker are all very suitable potential reviewers.

**Comment by kbenoit** [comment]
Looks very cool, I'd be happy to contribute a review.

**Comment by trinker** [comment]
I'd be happy to review as well.

**Comment by kgjerde** [comment]
@leouieda, @kbenoit, @trinker: Thanks a lot to all of you for such quick responses.

Also: I just added a link to one more example corpus in the readme file, but will leave the Github repo alone now.

**Comment by leouieda** [comment]
@whedon assign @kbenoit as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kbenoit

**Comment by leouieda** [comment]
@whedon add @trinker as reviewer

**Comment by whedon** [comment]
OK, @trinker is now a reviewer

**Comment by leouieda** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1342. Feel free to close this issue now!

**Comment by leouieda** [comment]
:wave: @kbenoit @trinker thank you for agreeing to review :tada: Please head over to #1342 for the review. There are checklists of criteria for both of you. You can also leave comments on the issue with your review or ask any questions. Also feel free to open issues and make pull requests on the software repository. If you do so, please link back to the review issue by mentioning `openjournals/joss-reviews#1342`.

@kgjerde thank you for recommending reviewers :+1: Please do your best to respond to the reviewers comments and suggestions. And don't hesitate to ask if you have any questions or concerns.

**Comment by kgjerde** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01329/joss.01329/10.21105.joss.01329.pdf)

**Comment by kgjerde** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01329/joss.01329/10.21105.joss.01329.pdf)

**Comment by kgjerde** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01329/joss.01329/10.21105.joss.01329.pdf)
