### ISSUE TITLE
[REVIEW]: PETRARCH2: Another Event Coding Program

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#133]
**Submitting author:** @johnb30 (<a href="http://orcid.org/0000-0001-7811-4399">John Beieler</a>)
**Repository:** <a href="https://github.com/openeventdata/petrarch2" target ="_blank">https://github.com/openeventdata/petrarch2</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** @RichardLitt
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.224637" target="_blank">10.5281/zenodo.224637</a>

## Status

[![status](http://joss.theoj.org/papers/78d3cb025a049782e7ea63a0c8ee79f6/status.svg)](http://joss.theoj.org/papers/78d3cb025a049782e7ea63a0c8ee79f6)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/78d3cb025a049782e7ea63a0c8ee79f6"><img src="http://joss.theoj.org/papers/78d3cb025a049782e7ea63a0c8ee79f6/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/78d3cb025a049782e7ea63a0c8ee79f6/status.svg)](http://joss.theoj.org/papers/78d3cb025a049782e7ea63a0c8ee79f6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/openeventdata/petrarch2" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/openeventdata/petrarch2">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@johnb30) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00133.pdf](https://github.com/openjournals/joss-reviews/files/637116/10.21105.joss.00133.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @RichardLitt - this is where the review actually happens. Please work through the checklist in the issue above (you should be able to check off items as you go).

Holler if you have any problems/questions.

**Comment by RichardLitt** [comment]
I believe that the software and possibly also the test dataset need DOIs. That, and the issues above, are blocking this. Not major blockers, just some small reworking needed.

**Comment by RichardLitt** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by RichardLitt** [comment]
Not sure how to say I consider my first pass done; given the linked issues above, this can be closed. Throwing this back into the author's camp for now.

**Comment by johnb30** [comment]
Hi @RichardLitt, thanks a ton for the review! We'll work over the next few days to update things and will drop a note in this issue when things are updated.

**Comment by RichardLitt** [comment]
Sounds good. 

General comments: This is well done. On a note that isn't technically needed but would be great - I'd like the answer to "Do the authors clearly state what problems the software is designed to solve and who the target audience is?" to be clearer in the document. Yes, you cover this, but I think the audience could be explicitly stated. I understand where the work is coming from, but some readers won't. 

Otherwise, LGTM.

**Comment by johnb30** [comment]
@RichardLitt as you saw I updated things in those two issues. I also added more into the paper body itself about the target audience and use cases. We greatly appreciate all of your feedback and input.

The only thing I wasn't sure about was the DOIs. If it's just the DOI for the paper I think that gets generated when the paper is accepted. Maybe @arfon can chime in?

**Comment by RichardLitt** [comment]
Your changes also look good to me. @arfon can you clarify about the DOIs?

**Comment by arfon** [comment]
> The only thing I wasn't sure about was the DOIs. If it's just the DOI for the paper I think that gets generated when the paper is accepted. Maybe @arfon can chime in?

@johnb30 - we need you to create an archive of the repository with Zenodo or figshare - see [this guide](https://guides.github.com/activities/citable-code/) for example. When you have done this, please let us know the archive DOI here.

We will then issue a DOI for the JOSS paper separately.

**Comment by johnb30** [comment]
I just minted a DOI. The number is (I think...) `10.5281/zenodo.224637` and the archive is at https://zenodo.org/record/224637#.WGXGQ7YrJE4. Let me know if anything else is needed from my end.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.224637 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.224637" target="_blank">10.5281/zenodo.224637</a> is the archive.

**Comment by arfon** [comment]
@RichardLitt - many thanks for reviewing this submission ✨ !

@johnb30 - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00133 ⚡️ 🚀 💥
