### ISSUE TITLE
[REVIEW]: Python Sorted Containers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1330]
**Submitting author:** @grantjenks (<a href="http://orcid.org/0000-0001-5010-405X">Grant Jenks</a>)
**Repository:** <a href="https://github.com/grantjenks/python-sortedcontainers" target ="_blank">https://github.com/grantjenks/python-sortedcontainers</a>
**Version:** v2.1.0
**Editor:** @jasonclark
**Reviewer:** @djmitche
**Archive:** <a href="https://doi.org/10.5281/zenodo.2584337" target="_blank">10.5281/zenodo.2584337</a>

## Status

[![status](http://joss.theoj.org/papers/e8b71872eaf49e7dead39eefee7c5a21/status.svg)](http://joss.theoj.org/papers/e8b71872eaf49e7dead39eefee7c5a21)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/e8b71872eaf49e7dead39eefee7c5a21"><img src="http://joss.theoj.org/papers/e8b71872eaf49e7dead39eefee7c5a21/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/e8b71872eaf49e7dead39eefee7c5a21/status.svg)](http://joss.theoj.org/papers/e8b71872eaf49e7dead39eefee7c5a21)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/grantjenks/python-sortedcontainers" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@djmitche, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @jasonclark know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/grantjenks/python-sortedcontainers">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2.1.0)?
- [x] **Authorship:** Has the submitting author (@grantjenks) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @djmitche it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01330/joss.01330/10.21105.joss.01330.pdf)

**Comment by djmitche** [comment]
@grantjenks:

> Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I don't see these bits in the repository.  Have I missed them?

Typically (1) is handled with `CONTRIBUTORS.md` or a section in the README, and (2) and (3) are handled with GitHub issue templates.

**Comment by grantjenks** [comment]
There's a page for that at http://www.grantjenks.com/docs/sortedcontainers/development.html It's the second-to-last link under the User Guide section of the README. I think it covers 1-3.

**Comment by djmitche** [comment]
Indeed, I did miss that.  That definitely covers (1), but not so much (2) and (3).  It's probably a tiny thing, but just an indication that both support requests and bug reports are welcome on the github repo would be enough.

**Comment by djmitche** [comment]
(that's the last bit before I can check all the boxes..)

**Comment by grantjenks** [comment]
@djmitche I have updated the docs at [Development and Support](http://www.grantjenks.com/docs/sortedcontainers/development.html) to cover (2) and (3).

There's two new sections at the top of the page: "Reporting Issues" and "Support". I've also tried to make it a bit more discoverable by updating the README's Documentation section with a Community Guide heading that links to "Development and Support". For now, I'd prefer not to use GitHub issue templates. I think the documentation provides sufficient guidelines for (2) and (3).

Thanks for the feedback and review!

**Comment by djmitche** [comment]
That's fantastic :)

**Comment by djmitche** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by djmitche** [comment]
@jasonclark review is complete.  I think the next step is up to you?

**Comment by jasonclark** [comment]
@djmitche Yep. Thanks for your review.

**Comment by jasonclark** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01330/joss.01330/10.21105.joss.01330.pdf)

**Comment by jasonclark** [comment]
Hi, @grantjenks. We are close to finishing this paper. There is a final step where you make an archive of the software in Zenodo and report the DOI. Can you do that and let me know the DOI here?

**Comment by grantjenks** [comment]
I think that's done. I believe the DOI is: 10.5281/zenodo.2584337
Here's the Zenodo link: https://zenodo.org/record/2584337
And the DOI link: https://doi.org/10.5281/zenodo.2584337

**Comment by djmitche** [comment]
@jasonclark is this ready to wrap up?

**Comment by grantjenks** [comment]
@jasonclark let me know if I can help close this out.

**Comment by djmitche** [comment]
@jasonclark hey, so this keeps showing up in my "assigned" queue despite there being no action required on my part.  And @whedon seems to want it that way.  Can we wrap this up?

**Comment by arfon** [comment]
> @jasonclark hey, so this keeps showing up in my "assigned" queue despite there being no action required on my part. And @whedon seems to want it that way. Can we wrap this up?

Sorry @djmitche - Whedon periodically tries to fix assignments on review issues but it looks like it's been a little over-keen here.

@grantjenks - I've just emailed Jason a reminder. If we don't hear back from him in the next day or so then I'll finish up this submission for him.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.2584337 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2584337" target="_blank">10.5281/zenodo.2584337</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.5281/zenodo.2584337 is OK

MISSING DOIs

- https://doi.org/10.1109/sp.2016.17 may be missing for title: SoK: (State of) The Art of War: Offensive Techniques in Binary Analysis
- https://doi.org/10.25080/majora-7b98e3ed-013 may be missing for title: Dask: Parallel Computation with Blocked algorithms and Task Scheduling

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/708

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/708, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
:wave: @grantjenks - a couple of final changes to the paper:

- Could you remove the last sentence about the Zenodo archive? We link to the archive directly from the paper already so this is superfluous.
- When you're mentioning projects (e.g. Astropy, Dask etc.) could you cite those packages in the paper? You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html). Also, note the Dask paper needs a DOI added to it.

**Comment by grantjenks** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01330/joss.01330/10.21105.joss.01330.pdf)

**Comment by grantjenks** [comment]
@arfon Update:

1. I removed the last sentence and verified the article proof still includes the DOI.
2. I found the Dask Distributed DOI and included it.
3. I cited the projects in the paper based on your reference. I wasn't sure how the text would be rendered. Looks like it included just the year. I think that's OK but let me know if there's a better rendering.
4. Everyone in the bibliography now has a reference from the paper except astropy:2013. Should I remove that entry from paper.bib?

I'm excited to wrap this up today, if possible.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01330/joss.01330/10.21105.joss.01330.pdf)

**Comment by arfon** [comment]
:+1: thanks. This looks good @grantjenks

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.25080/Majora-7b98e3ed-013 is OK
- 10.5281/zenodo.2584337 is OK

MISSING DOIs

- https://doi.org/10.1109/sp.2016.17 may be missing for title: SoK: (State of) The Art of War: Offensive Techniques in Binary Analysis

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/732

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/732, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1135565978203492352) 👈 🐦🐦🐦

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01330/status.svg)](https://doi.org/10.21105/joss.01330)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01330">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01330/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01330/status.svg
   :target: https://doi.org/10.21105/joss.01330
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01330/status.svg)](https://doi.org/10.21105/joss.01330)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
