### ISSUE TITLE
[REVIEW]: MPIFiles.jl: A Julia Package for Magnetic Particle Imaging Files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1331]
**Submitting author:** @tknopp (<a href="http://orcid.org/0000-0002-1589-8517">Tobias Knopp</a>)
**Repository:** <a href="https://github.com/MagneticParticleImaging/MPIFiles.jl" target ="_blank">https://github.com/MagneticParticleImaging/MPIFiles.jl</a>
**Version:** v0.5.3
**Editor:** @brainstorm
**Reviewer:** @IgorBaratta
**Archive:** <a href="https://doi.org/10.5281/zenodo.3242352" target="_blank">10.5281/zenodo.3242352</a>

## Status

[![status](http://joss.theoj.org/papers/0e06aa80b90b3aaee0cf3a9da52f3760/status.svg)](http://joss.theoj.org/papers/0e06aa80b90b3aaee0cf3a9da52f3760)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/0e06aa80b90b3aaee0cf3a9da52f3760"><img src="http://joss.theoj.org/papers/0e06aa80b90b3aaee0cf3a9da52f3760/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0e06aa80b90b3aaee0cf3a9da52f3760/status.svg)](http://joss.theoj.org/papers/0e06aa80b90b3aaee0cf3a9da52f3760)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/MagneticParticleImaging/MPIFiles.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@IgorBaratta, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @brainstorm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MagneticParticleImaging/MPIFiles.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.5.3
- [x] **Authorship:** Has the submitting author (@tknopp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @IgorBaratta it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01331/joss.01331/10.21105.joss.01331.pdf)

**Comment by labarba** [comment]
👋  @IgorBaratta — Can you give us a quick update on your review?

**Comment by tknopp** [comment]
@labarba: If there is anything I can do, please let me know. I have a depending paper under review and would of course like to reference the software being used. I could ask in the Julia forum for potential reviewers if @IgorBaratta has no time. Or maybe you have other reviewers in mind. Thanks!

**Comment by labarba** [comment]
I sent an email to @IgorBaratta, and he replied on May 14, saying he would work on this review and deliver by the end of the week.

**Comment by tknopp** [comment]
Thanks for the update! Did not want to be pushy, just eager to get my first JOSS review :-)

**Comment by IgorBaratta** [comment]
Hi @tknopp, @labarba,  sorry for not addressing this review sooner!

I found the package quite practical, primarily because of the possibility of reading different file formats in a common interface. I've tested the package functionality with MDF data-sets available in the OpenMPIData repository and the Bruker MPI data-sets used in the tests. 

Everything worked out smoothly.  Though it took some hours for downloading and testing the big data-sets, as expected.

However, I'd suggest some improvements before recommending acceptance.

**Software Paper:**

- The pdf file has lost its formatting. Please check the 3rd paragraph.
- I would also recommend checking the structure of the 2nd paragraph to improve readability.

**Documentation:**

- Example usage -  I didn't find any clear example in the documentation. I used the data-sets mentioned above to verify the core functionality of the package, but they are not documented. I'd suggest include at least one example with an actual (small) data-set, maybe in the Getting Started section.

- Community guidelines – Although there is a clear indication of the issue tracker (to report issues and seek support), I was not able to find any guidelines for contributing to the package. 

I hope this review would help improve the package.

**Comment by tknopp** [comment]
Thank you @IgorBaratta! These are all very good points that definitely need to be addressed. I will work on this and ping you when its ready.

**Comment by tknopp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01331/joss.01331/10.21105.joss.01331.pdf)

**Comment by tknopp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01331/joss.01331/10.21105.joss.01331.pdf)

**Comment by tknopp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1331 with the following error: 

 Error reading bibliography ./paper.bib (line 47, column 4):
unexpected "e"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by tknopp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01331/joss.01331/10.21105.joss.01331.pdf)

**Comment by tknopp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1331 with the following error: 

 Error reading bibliography ./paper.bib (line 33, column 3):
unexpected "p"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by tknopp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01331/joss.01331/10.21105.joss.01331.pdf)

**Comment by tknopp** [comment]
@IgorBaratta: I have worked on all of your points. Regarding this
> Example usage - I didn't find any clear example in the documentation. I used the data-sets mentioned above to verify the core functionality of the package, but they are not documented. I'd suggest include at least one example with an actual (small) data-set, maybe in the Getting Started section.

I was not 100% sure how this was meant. The dataset used in "getting started" was actually downloaded when performing running the test suite but I have not mentioned it in the documentation. Now I explicitly download the data:
    https://magneticparticleimaging.github.io/MPIFiles.jl/dev/gettingStarted.html
Then the user can directly try out all the exampled on that page.

**Comment by labarba** [comment]
Hi all — are we waiting here for the reviewer to complete their tasks? or the author to do some revisions? Or both? Give us an update!

**Comment by IgorBaratta** [comment]
> @IgorBaratta: I have worked on all of your points. Regarding this
> 
> > Example usage - I didn't find any clear example in the documentation. I used the data-sets mentioned above to verify the core functionality of the package, but they are not documented. I'd suggest include at least one example with an actual (small) data-set, maybe in the Getting Started section.
> 
> I was not 100% sure how this was meant. The dataset used in "getting started" was actually downloaded when performing running the test suite but I have not mentioned it in the documentation. Now I explicitly download the data:
> https://magneticparticleimaging.github.io/MPIFiles.jl/dev/gettingStarted.html
> Then the user can directly try out all the exampled on that page.
 Great, thanks @tknopp .
Yes. That's what I meant.

All points have been addressed and the boxes thicked.

**Comment by IgorBaratta** [comment]
The author has addressed all points. 
To me this paper is ready for acceptance.


> Hi all — are we waiting here for the reviewer to complete their tasks? or the author to do some revisions? Or both? Give us an update!

**Comment by brainstorm** [comment]
I see a couple of points unchecked in the checklist: example usage and community guidelines?

**Comment by brainstorm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/nature03808 is OK
- 10.1038/s41467-019-09704-x is OK
- 10.1088/1361-6560/aa6c99 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by brainstorm** [comment]
Other than those, @tknopp, feel free to register a zenodo DOI so we can archive and accept. Thanks everyone!

**Comment by IgorBaratta** [comment]
> I see a couple of points unchecked in the checklist: example usage and community guidelines?
My mistake. I guess now they are all checked.

**Comment by tknopp** [comment]
@brainstorm: I am not sure what you mean by "register a zenodo DOI", could you elaborate? Should I register a DOI for one of the references or for the article itself? Would be great to get some help.

**Comment by labarba** [comment]
Hi @tknopp — The JOSS publication process requires that after all revisions to the software and paper are complete and the reviewers and editor recommend publication, you do the following:

- make a tagged release of your software, and report the version number here so we can update the metadata
- make a full deposit of your software in an archive that provides persistence and a global identifier such as a DOI (Zenodo is the most popular, but other archives with similar services exist and are permitted); report the DOI of the software archive here, so we can update the metadata.

You may find this helpful: https://guides.github.com/activities/citable-code/

HTH

**Comment by labarba** [comment]
I've read the paper and made some editorial suggestions via this PR
https://github.com/MagneticParticleImaging/MPIFiles.jl/pull/14

**Comment by labarba** [comment]
Note: after making the Zenodo deposit, be sure to check that it has the correct metadata, and edit as necessary. This includes the title (should match the paper title) and author list (make sure the list is correct and people like me who only fixed some bits of the paper, are not on it). You may also want to add the ORCID of all authors in the Zenodo metadata.

**Comment by tknopp** [comment]
Thanks @labarba, I have merged your changes and initiated a release of the package:

https://github.com/JuliaRegistries/General/pull/1295

Note that this is a two-step procedure in the Julia universe and the github release is done in the second step. I thus need to wait until the upper PR is merged. Then I will create the zenodo DOI.

**Comment by tknopp** [comment]
@labarba: I hope I got this right:
- Here is the Zenodo release: https://zenodo.org/record/3242352#.XP4-Uy2BrLE
- The DOI is: 10.5281/zenodo.3242352
- MPIFiles has now Version 0.5.3

**Comment by labarba** [comment]
@whedon set v0.5.3 as archive

**Comment by whedon** [comment]
v0.5.3 doesn't look like an archive DOI.

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.3242352 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3242352" target="_blank">10.5281/zenodo.3242352</a> is the archive.

**Comment by labarba** [comment]
@whedon set v0.5.3 as version

**Comment by whedon** [comment]
OK. v0.5.3 is the version.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/nature03808 is OK
- 10.1038/s41467-019-09704-x is OK
- 10.1088/1361-6560/aa6c99 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/743

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/743, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1138051197498200065) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/744
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01331](https://doi.org/10.21105/joss.01331)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @tknopp, your JOSS paper is published! 🚀 

Big thanks to our editor: @brainstorm and reviewer: @IgorBaratta 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01331/status.svg)](https://doi.org/10.21105/joss.01331)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01331">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01331/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01331/status.svg
   :target: https://doi.org/10.21105/joss.01331
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01331/status.svg)](https://doi.org/10.21105/joss.01331)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by tknopp** [comment]
Awesome, thank you very much @labarba, @brainstorm and @IgorBaratta. Will celebrate my first JOSS paper now!
