### ISSUE TITLE
[PRE REVIEW]: treex: a Python package for manipulating rooted trees

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1332]
**Submitting author:** @RomainAzais (<a href="http://orcid.org/0000-0002-5234-1822">Romain Azais</a>)
**Repository:** <a href="https://gitlab.inria.fr/azais/treex" target ="_blank">https://gitlab.inria.fr/azais/treex</a>
**Version:** v1.1.3
**Editor:** @VivianePons
**Reviewers:** @dvalters, @VivianePons

**Author instructions**

Thanks for submitting your paper to JOSS @RomainAzais. **Currently, there isn't an JOSS editor assigned** to your paper.

@RomainAzais if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1332 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    135      0 --:--:-- --:--:-- --:--:--   135
Error producing PDF.
! Misplaced alignment tab character &.
<argument> ...estore \footnotesize {\sffamily Aza&
                                                  iuml;s et al., (2019). tre...
l.357 

Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @VivianePons - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@Azais - for some reason Whedon doesn't like the HTML-escaped characters in the footer. Can you update your paper to look like this? https://gist.github.com/arfon/6b1092c47917335272158679e3d2a6ec

**Comment by RomainAzais** [comment]
The issue was due to accented characters. I removed them from the file paper.md.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01332/joss.01332/10.21105.joss.01332.pdf)

**Comment by VivianePons** [comment]
Yes, I'am taking this one! Trees are my favorite thing ;)

**Comment by Azais** [comment]
You have the wrong Azais, sorry ! I therefore cannot update the paper.

Good luck to my distant relative, 

Another Azais

**Comment by VivianePons** [comment]
I have fixed the Azais issue in the comment section as I understand @RomainAzais is the author! Sorry @Azais for the confusion. I am not sure how to stop github sending you updates on this thread now that you're in it. But in any case, this is just the pre-review issue. It will be closed as soon as I find reviewers.

@Arfon : I am going to find a reviewer, I am also wondering if I can add myself as a second reviewer if I am the editor?

**Comment by VivianePons** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by RomainAzais** [comment]
> [ 👉 Check article proof 📄 👈 ](https://github.com/openjournals/joss-papers/blob/joss.01332/joss.01332/10.21105.joss.01332.pdf)

I didn't answer last week but the article proof is correct.

**Comment by dvberkel** [comment]
@VivianePons You have sent me an email in which you requested a review of the article. I am willing and able to review the paper.

I will start with reading the article.

**Comment by VivianePons** [comment]
@whedon assign @dvalters as reviewer

**Comment by dvberkel** [comment]
@whedon commands

**Comment by whedon** [comment]
OK, the reviewer is @dvalters

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by VivianePons** [comment]
@whedon add @VivianePons as reviewer

**Comment by whedon** [comment]
OK, @VivianePons is now a reviewer

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1351. Feel free to close this issue now!
