### ISSUE TITLE
[PRE REVIEW]: scikit-finite-diff, a new tool for PDE solving

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1333]
**Submitting author:** @celliern (<a href="http://orcid.org/0000-0002-3759-3546">Nicolas Cellier</a>)
**Repository:** <a href="https://gitlab.com/celliern/scikit-fdiff/" target ="_blank">https://gitlab.com/celliern/scikit-fdiff/</a>
**Version:** v0.6.0rc1
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @mrava87, @poulson

**Author instructions**

Thanks for submitting your paper to JOSS @celliern. 

@celliern if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1333 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @poulson - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
:wave: @celliern - please update your paper structure to exactly match this one: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by celliern** [comment]
This should be done. Do I need to redo the submission to retrigger the paper compilation?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01333/joss.01333/10.21105.joss.01333.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@chrisrichardson, @IgorBaratta, @sebastkm would you be interested in reviewing this work for JOSS? Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@maroba as developer of [findiff](https://github.com/maroba/findiff) you might be interested in this submission to [JOSS](http://joss.theoj.org/). I'm wondering if you'd be a suitable reviewer. If you are interested in reviewing this, please can you tell me about your professional background or provide a link to a professional page e.g. your university or an ORCID profile (apologies I cannot tell from your current GitHub profile).

**Comment by Kevin-Mattheus-Moerman** [comment]
@lheagy would you be interested in reviewing this work or do you know any suitable potential reviewers? Thanks.

**Comment by lheagy** [comment]
Hi @Kevin-Mattheus-Moerman, this looks like an interesting submission! My edit que is keeping me pretty busy at the moment, so it would be several weeks before I could get to this, so if you can't find another reviewer, feel free to ping. Otherwise, I would suggest: @prisae, @thast or there may be some folks from the [Fenics](https://fenicsproject.org/) project who would be willing to take a look

**Comment by prisae** [comment]
Not sure if I am up for this task. (Time-wise definitely not within the next 10 days, give me a shout if you're still looking for reviewers in two weeks.)

However, topic-wise I would suggest to ask @mrava87. He is definitely better suited topic-wise, and might be very interested in it indeed.

**Comment by mrava87** [comment]
Hi, I am happy to review this. Let me know if it’s ok and I can do it over the weekend :) As I never reviewed this journal before, the manuscript is the one you access at the ‘check proof’ link above? And comments should also be focused on the software itself, right?

**Comment by Kevin-Mattheus-Moerman** [comment]
@mrava87 thanks for your interest, I assume this is you: https://scholar.google.com/citations?user=2fON_zgAAAAJ&hl=en (I recommend you add your affiliation and perhaps a link to a professional profile like ORCID to your GitHub profile too). I'll add you as a reviewer and will help you through the process. This is a pre-review issue, the review will take place in a separate issue. Thanks for helping!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @mrava87 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mrava87

**Comment by Kevin-Mattheus-Moerman** [comment]
@wesselb @willtebbutt @ketch @twhughes @ianwilliamson @ohinai @rc would you be interested in reviewing this [JOSS](http://joss.theoj.org/) submission on Finite Differences using Python? The review process will focus on [the software](https://gitlab.com/celliern/scikit-fdiff/) and a [short paper](https://github.com/openjournals/joss-papers/blob/joss.01333/joss.01333/10.21105.joss.01333.pdf). 

This is a pre-review issue. The review takes place in a separate review issue where tickboxes guide the reviewers. Here is an example of a completed review process: https://github.com/openjournals/joss-reviews/issues/1203 (see our [review guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)).

**Comment by mrava87** [comment]
> @mrava87 thanks for your interest, I assume this is you: https://scholar.google.com/citations?user=2fON_zgAAAAJ&hl=en (I recommend you add your affiliation and perhaps a link to a professional profile like ORCID to your GitHub profile too). I'll add you as a reviewer and will help you through the process. This is a pre-review issue, the review will take place in a separate issue. Thanks for helping!

Added my organization and link to scholar to my github account :)

**Comment by mrava87** [comment]
> @wesselb @willtebbutt @ketch @twhughes @ianwilliamson @ohinai @rc would you be interested in reviewing this [JOSS](http://joss.theoj.org/) submission on Finite Differences using Python? The review process will focus on [the software](https://gitlab.com/celliern/scikit-fdiff/) and a [short paper](https://github.com/openjournals/joss-papers/blob/joss.01333/joss.01333/10.21105.joss.01333.pdf).
> 
> This is a pre-review issue. The review takes place in a separate review issue where tickboxes guide the reviewers. Here is an example of a completed review process: #1203 (see our [review guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)).

Sounds good. So we wait until you create the review issue and then we can start commenting there, right?

**Comment by ianwilliamson** [comment]
> @wesselb @willtebbutt @ketch @twhughes @ianwilliamson @ohinai @rc would you be interested in reviewing this [JOSS](http://joss.theoj.org/) submission on Finite Differences using Python? 

Hi, this is a neat concept for reviewing! This package looks very interesting but unfortunately I don't have time to review this right now.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mrava87 
> Sounds good. So we wait until you create the review issue and then we can start commenting there, right?

Yes

**Comment by Kevin-Mattheus-Moerman** [comment]
@ianwilliamson thanks for your reply. Let me know if you know if any other suitable reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
@celliern are there any reviewers you wish to suggest at this point?

**Comment by celliern** [comment]
I may suggest Antonino Ingargiola (@tritemio), if not too busy to make that review.

**Comment by poulson** [comment]
@arfon I am sorry to have been too slow to respond to this. It looks like a very interesting submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@poulson I am willing to step down as editor if you want to take this one. Just let me know. Alternatively would you like to review this work?

**Comment by poulson** [comment]
@Kevin-Mattheus-Moerman I am happy to serve as either a reviewer or an editor. By no means did I mean to imply that I was hoping to supplant you, simply that I regret being too slow due to international travel. You list finite element analysis as one of your core expertise, so I believe I should defer here!

**Comment by celliern** [comment]
I'm happy to see that the software interest you. If we still lack of reviewer, I could ask to the scipy user / dev mailing list if someone is interested to help in the review process?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @poulson as reviewer

**Comment by whedon** [comment]
OK, @poulson is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@celliern I'll start the review process now but if you find more potential reviewers via the scipy list let me know and I can still add them later.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1356. Feel free to close this issue now!
