### ISSUE TITLE
[PRE REVIEW]: GUESSmyLT: Software to guess the RNA-Seq library type of paired and single end read files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1334]
**Submitting author:** @Juke34 (<a href="http://orcid.org/0000-0002-6629-0173">Jacques Dainat</a>)
**Repository:** <a href="https://github.com/NBISweden/GUESSmyLT" target ="_blank">https://github.com/NBISweden/GUESSmyLT</a>
**Version:** v1.0
**Editor:** @lpantano
**Reviewers:** @mistrm82

**Author instructions**

Thanks for submitting your paper to JOSS @Juke34. Currently, there isn't an JOSS editor assigned to your paper.

@Juke34 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mgymrek it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@mgymrek) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1334 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1334/paper.md): did not find expected alphabetic or numeric character while scanning an alias at line 21 column 11 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @pjotrp @mgymrek @brainstorm @lpantano - would one of you be able to edit this submission?

**Comment by lpantano** [comment]
I can do that if @pjotrp is ok and the others.

**Comment by arfon** [comment]
@Juke34 - what you're trying to do with the `*` affiliation won't work sorry. The affiliation indexes need to be numerical.

**Comment by Juke34** [comment]
Is there any advised way to pinpoint equal contribution ?

**Comment by pjotrp** [comment]
I would add it as a footnote. You can even point to the github contributions graph.

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
Hi @Juke34,

Thanks for submitting your work here. Let me know when you get the PDF generated correctly, and I can start moving things forward.

Thanks!

**Comment by Juke34** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01334/joss.01334/10.21105.joss.01334.pdf)

**Comment by Juke34** [comment]
I had apparently forgot a sentence. I also fixed a typo and added a figure. I'm not sure having proceeding properly with the figure. Let's see the new pdf.
@whedon generate pdf

**Comment by lpantano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01334/joss.01334/10.21105.joss.01334.pdf)

**Comment by lpantano** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1093/bioinformatics/bts356 is OK
- 10.1038/nmeth.4197 is OK
- 10.1038/nmeth.1923 is OK
- doi: 10.1093/molbev/msx319  is OK
- 10.1038/nbt.1883 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lpantano** [comment]
@whedon assign @mistrm82 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mistrm82

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1344. Feel free to close this issue now!
