### ISSUE TITLE
[PRE REVIEW]: Capytaine: a Python-based linear potential flow solver

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1335]
**Submitting author:** @mancellin (<a href="http://orcid.org/0000-0002-0316-3230">Matthieu Ancellin</a>)
**Repository:** <a href="https://github.com/mancellin/capytaine" target ="_blank">https://github.com/mancellin/capytaine</a>
**Version:** v1.0
**Editor:** @leouieda
**Reviewers:** @mikaem, @harpolea

**Author instructions**

Thanks for submitting your paper to JOSS @mancellin. **Currently, there isn't an JOSS editor assigned** to your paper.

@mancellin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @leouieda - would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01335/joss.01335/10.21105.joss.01335.pdf)

**Comment by leouieda** [comment]
@arfon I'd be happy to :+1:

**Comment by arfon** [comment]
@whedon assign @leouieda as editor

**Comment by whedon** [comment]
OK, the editor is @leouieda

**Comment by leouieda** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by leouieda** [comment]
:wave: Hi @mancellin I made a few editorial suggestions for the JOSS paper (mancellin/capytaine#6) and will start looking for reviewers now. Please let me know if you have any questions or suggestions for reviewers.

**Comment by leouieda** [comment]
:wave: @harpolea @mikaem would you be interested in reviewing this submission for JOSS?

**Comment by mikaem** [comment]
Hi. Looks interesting, I can do it.

**Comment by harpolea** [comment]
Sure, I'd be happy to review it

**Comment by leouieda** [comment]
@whedon assign @mikaem as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mikaem

**Comment by leouieda** [comment]
@whedon add @harpolea as reviewer

**Comment by whedon** [comment]
OK, @harpolea is now a reviewer

**Comment by leouieda** [comment]
@mikaem @harpolea thank you for agreeing to review :tada: :1st_place_medal:

**Comment by leouieda** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by leouieda** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01335/joss.01335/10.21105.joss.01335.pdf)

**Comment by leouieda** [comment]
@mancellin please add these missing DOIs to your BibTex:

* https://doi.org/10.1115/OMAE2018-77924
* https://doi.org/10.1016/j.apor.2018.10.007

**Comment by mancellin** [comment]
Done.

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5802/smai-jcm.36 is OK
- 10.1115/OMAE2018-77924 is OK
- 10.1504/IJCSE.2009.029165 is OK
- 10.5334/jors.148 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1016/j.apor.2018.10.007 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5802/smai-jcm.36 is OK
- 10.1115/OMAE2018-77924 is OK
- 10.1504/IJCSE.2009.029165 is OK
- 10.5334/jors.148 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1016/j.apor.2018.10.007 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by leouieda** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1341. Feel free to close this issue now!

**Comment by leouieda** [comment]
@mikaem @harpolea Thank you for agreeing to review. Please head over to #1341 for the review. Feel free to ping me (`@leouieda`) in the review issue or elsewhere if you need any help or have questions.
