### ISSUE TITLE
[REVIEW]: LGP: A robust Linear Genetic Programming implementation on the JVM using Kotlin.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1337]
**Submitting author:** @JedS6391 (<a href="http://orcid.org/0000-0002-5028-9987">Jed Simson</a>)
**Repository:** <a href="https://github.com/JedS6391/LGP" target ="_blank">https://github.com/JedS6391/LGP</a>
**Version:** 5.1
**Editor:** @gkthiruvathukal
**Reviewer:** @homonecloco
**Archive:** <a href="https://doi.org/10.5281/zenodo.3519400" target="_blank">10.5281/zenodo.3519400</a>

## Status

[![status](http://joss.theoj.org/papers/a3f8ca9f3d7c7a7c1b02dc04c49154c2/status.svg)](http://joss.theoj.org/papers/a3f8ca9f3d7c7a7c1b02dc04c49154c2)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/a3f8ca9f3d7c7a7c1b02dc04c49154c2"><img src="http://joss.theoj.org/papers/a3f8ca9f3d7c7a7c1b02dc04c49154c2/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/a3f8ca9f3d7c7a7c1b02dc04c49154c2/status.svg)](http://joss.theoj.org/papers/a3f8ca9f3d7c7a7c1b02dc04c49154c2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/JedS6391/LGP" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@homonecloco, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @gkthiruvathukal know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JedS6391/LGP">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 5.1
- [x] **Authorship:** Has the submitting author (@JedS6391) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @homonecloco it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01337/joss.01337/10.21105.joss.01337.pdf)

**Comment by arfon** [comment]
:wave: @homonecloco - how are you getting along with your review?

**Comment by homonecloco** [comment]
Hi, 
I'm still figuring out how to do the reviews in here.

**Comment by homonecloco** [comment]
The documentation is extensive and detailed. However, the links to the API are broken. Reported as an issue in JedS6391/LGP#55

**Comment by homonecloco** [comment]
There is a link to the Thesis of the author, http://www.jedsimson.co.nz/static/assets/thesis/Open-Source%20Linear%20Genetic%20Programming.pdf Would it be appropriate to also include the supervisor as author?

**Comment by homonecloco** [comment]
I had issues running the program, as stated JedS6391/LGP#56 . I'll continue the review once this issue is resolved.

**Comment by homonecloco** [comment]
The installation consists on downloading the jars. There is also an option to do it from Maven.

**Comment by gkthiruvathukal** [comment]
@JedS6391 I'm not sure whether you saw the issues that have been reported by @homonecloco. Can you please follow up when you get a chance? Thanks.

**Comment by JedS6391** [comment]
Hi @gkthiruvathukal, [JedS6391/LGP#55](https://github.com/JedS6391/LGP/issues/55) and [JedS6391/LGP#56](https://github.com/JedS6391/LGP/issues/56) have been addressed. I am currently working on [JedS6391/LGP#7](https://github.com/JedS6391/LGP/issues/57), but it is taking a little while to write the unit tests before the issue can be closed.

**Comment by gkthiruvathukal** [comment]
Thanks, @JedS6391. Please let us know when you've had a chance to add unit tests.

**Comment by gkthiruvathukal** [comment]
Just a nudge here, @JedS6391. Any update on unit tests?

**Comment by gkthiruvathukal** [comment]
@JedS6391 Please provide an update on when you will be able to address unit tests.

**Comment by JedS6391** [comment]
Hi @gkthiruvathukal, apologies for the lack of updates. Unfortunately I have not had time recently to dedicate to the LGP project, and as such I am happy for this review to be cancelled and postponed until I can satisfy the requirements.

**Comment by gkthiruvathukal** [comment]
@JedS6391  I don't want you to withdraw the submission. You have been good about addressing 2/3 issues. Can you give me an idea of when you might be able to do it? I will work with your schedule and nudge you accordingly.

**Comment by JedS6391** [comment]
Much appreciated! I will able to start working on the remaining issues over the next few weekends.

**Comment by JedS6391** [comment]
Hi @gkthiruvathukal -- just wanted to give you a brief progress update. 

I have implemented unit tests for a subset of the functionality in [this PR](https://github.com/JedS6391/LGP/pull/58). I hope to finish the remaining tests over the weekend.

I will let you know once all unit tests have been completed.

**Comment by gkthiruvathukal** [comment]
@JedS6391 Perfect. Let me know when you have a few more tests in place. I don't need 100% test coverage to proceed.  I just did a quick look and it seems like something is failing, so I will wait until you get it sorted out. Thanks for moving on this!

**Comment by JedS6391** [comment]
Hi @gkthiruvathukal, the latest [commit](https://github.com/JedS6391/LGP/commits/develop) against the develop branch has a green build and has a subset of the tests.

At the moment, the coverage is 20% but I intended to increase this going forward. If you are interested to see a breakdown of the areas covered, then that can be viewed [here](https://codecov.io/gh/JedS6391/LGP/tree/8249ba28013930c7ca9b1328a715e64d83960d4f/src/main/kotlin/nz/co/jedsimson/lgp/core).

I will continue to add more tests and eventually close the initial issue.

**Comment by gkthiruvathukal** [comment]
@JedS6391 I find your efforts satisfactory as there is now a basis for doing further testing in future work. If our reviewer, @homonecloco, agrees, I would like to move toward accepting your submission. Once we hear from @homonecloco, you will need to create a Zenodo archive.

**Comment by gkthiruvathukal** [comment]
@homonecloco When you get a chance, can you let us know if your issues are all addressed so I can proceed with the next steps (acceptance).

**Comment by homonecloco** [comment]
Hi, I haven't got a chance, I'd been travelling the last week. I'll aim to review before the end of this week.

**Comment by gkthiruvathukal** [comment]
@homonecloco No problem! Thanks for your quick response. End of week is fine.

**Comment by gkthiruvathukal** [comment]
@homonecloco Any chance you can let us know whether your remaining issues have been addressed so I can proceed with acceptance?

**Comment by gkthiruvathukal** [comment]
@homonecloco Just a nudge to the above comment. Can you let me know if you have any further issues with this submission. I believe we are ready to accept.

**Comment by homonecloco** [comment]
Hi, 
Sorry for not finishing the review earlier. I ended up having a couple of complex weeks. The unit tests where added and they run. They seem to be ok. There is also an extra repository with actual examples, that may be good to have included in the main page of the project. There is one example that is missing to run, so I aded an issue on the corresponding repository: 
JedS6391/LGP-examples#1 and I would like a bit more clarification as stated in JedS6391/LGP-examples#2 
But other than that, I'm happy with the state of the project. 
Best,
Ricardo.

**Comment by Kevin-Mattheus-Moerman** [comment]
@gkthiruvathukal can you pick this up? It seems all boxes are ticked now. Thanks

**Comment by gkthiruvathukal** [comment]
Thanks for the nudge, @Kevin-Mattheus-Moerman.
 
@openjournals/joss-eics  I am ready to recommend acceptance of the submission. @JedS6391 has done a great job of addressing all reviewer feedback during this process.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01337/joss.01337/10.21105.joss.01337.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1147/rd.21.0002 is OK
- 10.5281/zenodo.2561124 is OK
- 10.5281/zenodo.2561130 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
Here are some additional points in relation to your paper: 

- [ ] We will shortly process the acceptance of this work in JOSS. Please double check your work (including the author list, affiliations, and acknowledgements) and make any final edits now. 
- [ ] Please check your reference syntax throughout and make sure it is in line with these guidelines: 
https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax
e.g. you use `[@friedberg1958] experimented with...` in your paper.md, but this should be `@friedberg1958 experimented with...` if used in this way. 
- [ ] The final paper will contain a link to the archived software. I therefore suggest removal of this sentence and the links to the Zenodo archives "The source code for LGP and LGP-lib have been archived to Zenodo with the linked DOIs: • LGP core: (Simson, 2019a) • LGP library: (Simson, 2019b)". If both the core and the library are important (and were reviewed), does it make sense to place them both in a single archive? 
- [ ] Once you've made the above changes please archive a copy of the reviewed software on Zenodo and report the DOI here. 
- [ ] Can you confirm what the latest version tag is of the reviewed software? Is it still 4.2 or was the version tag altered during review? 

Thanks.

**Comment by JedS6391** [comment]
Hi @Kevin-Mattheus-Moerman, thanks for the notes. I will make the request changes and update this thread once all changes are completed.

Regarding your last question -- the version tag was altered during review to resolve some issues that were encountered. The latest version tag (and reviewed version) is [5.1](https://github.com/JedS6391/LGP/tree/5.1). This will be the version that I archive on Zenodo.

Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 5.1 as version

**Comment by whedon** [comment]
OK. 5.1 is the version.

**Comment by JedS6391** [comment]
Hi @Kevin-Mattheus-Moerman, I have made the requested changes to the paper. The DOI is 10.5281/zenodo.3402305 (the archive can be found [here](https://zenodo.org/record/3402305)).

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01337/joss.01337/10.21105.joss.01337.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@JedS6391 can you modify the archived version on Zenodo so that the title (and author list) match the paper?

**Comment by Kevin-Mattheus-Moerman** [comment]
@JedS6391 I cannot see the changes yet (see boxes left  unticked, the references style is still the same and the section referring to the source is still there/unaltered)? Has the paper.md file been updated? Is the above pdf accurate?

**Comment by Kevin-Mattheus-Moerman** [comment]
@JedS6391 :wave: :point_up:

**Comment by JedS6391** [comment]
Hi @Kevin-Mattheus-Moerman, I think something went wrong with the automatic upload to Zenodo from GitHub so I created the archive manually (see [here](https://zenodo.org/record/3519400)). I have also updated the archive title + author list to be correct. 

The new DOI is 10.5281/zenodo.3519400.

Apologies for the delay in getting this sorted.

**Comment by JedS6391** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01337/joss.01337/10.21105.joss.01337.pdf)

**Comment by JedS6391** [comment]
I believe I need to change the DOI to the new one to get the paper to reflect the changes made?

**Comment by Kevin-Mattheus-Moerman** [comment]
@JedS6391 no you need to make the changes in your paper.md file (https://github.com/JedS6391/LGP/blob/develop/paper.md) and run '@whedon generate pdf'. Note the two changes I proposed above. Let me know if you have questions.

**Comment by JedS6391** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01337/joss.01337/10.21105.joss.01337.pdf)

**Comment by JedS6391** [comment]
Hi @Kevin-Mattheus-Moerman, the generated PDF now has the reflected changes (I didn't realise whedon read from the `develop` branch). Please note that the correct DOI is as stated yesterday: 10.5281/zenodo.3519400.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 10.5281/zenodo.3519400 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3519400" target="_blank">10.5281/zenodo.3519400</a> is the archive.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1147/rd.21.0002 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1057

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1057, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1188362835795025920) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1058
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01337](https://doi.org/10.21105/joss.01337)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01337/status.svg)](https://doi.org/10.21105/joss.01337)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01337">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01337/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01337/status.svg
   :target: https://doi.org/10.21105/joss.01337
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01337/status.svg)](https://doi.org/10.21105/joss.01337)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
