### ISSUE TITLE
[PRE REVIEW]: prysm: A Python optics module

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1339]
**Submitting author:** @brandondube (<a href="http://orcid.org/0000-0002-3837-605X">Brandon Dube</a>)
**Repository:** <a href="https://github.com/brandondube/prysm" target ="_blank">https://github.com/brandondube/prysm</a>
**Version:** v0.15.1
**Editor:** @xuanxu
**Reviewers:** @aquilesC

**Author instructions**

Thanks for submitting your paper to JOSS @brandondube. **Currently, there isn't an JOSS editor assigned** to your paper.

@brandondube if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1339 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    114      0 --:--:-- --:--:-- --:--:--   115
Could not find bibliography file: paper.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@brandondube - please either rename `references.bib` to be `paper.bib` or change the entry in your `paper.md` to point to `references.bib`

**Comment by brandondube** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by brandondube** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01339/joss.01339/10.21105.joss.01339.pdf)

**Comment by brandondube** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01339/joss.01339/10.21105.joss.01339.pdf)

**Comment by danielskatz** [comment]
👋 @xuanxu - Would you be willing to edit this submission?

**Comment by xuanxu** [comment]
@whedon assign @xuanxu as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by xuanxu** [comment]
:wave: @aquilesC: Would you be willing to review this paper? I think your expertise in Python and Optics makes you a great fit for this submission.

**Comment by aquilesC** [comment]
@xuanxu , sure!

**Comment by xuanxu** [comment]
Great! Thanks @aquilesC!
I'll assign you now and start the review issue

**Comment by xuanxu** [comment]
@whedon assign @aquilesC as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @aquilesC

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1352. Feel free to close this issue now!

**Comment by xuanxu** [comment]
@aquilesC, please head over to #1352 for the actual review
