### ISSUE TITLE
[PRE REVIEW]: Optlang: A Python interface to common mathematical optimization solvers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#134]
**Submitting author:** @KristianJensen (<a href="http://orcid.org/0000-0002-2796-805X">Kristian Jensen</a>)
**Repository:** <a href="https://github.com/biosustain/optlang" target ="_blank">https://github.com/biosustain/optlang</a>
**Version:** v1.0.0
**Editor:** @kyleniemeyer
**Reviewer:** @moorepants

**What this issue is for**

Thanks for submitting your paper to JOSS KristianJensen. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@kyleniemeyer @labarba would either of you be wiling to edit this submission for JOSS?

**Comment by kyleniemeyer** [comment]
I can handle this one, unless @labarba prefers to.

**Comment by arfon** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by kyleniemeyer** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by kyleniemeyer** [comment]
Hi @jordigh @jkahn would either of you be interested in helping review this?

I don't see any current reviewers with explicit expertise in optimization, so I sent out a request on Twitter: https://twitter.com/kyleniemeyer/status/808837158714806272

@KristianJensen any suggestions you have on possible domain-expert reviewers would be appreciated as well; I try to get two people, including one area expert, to take a look.

**Comment by moorepants** [comment]
@kyleniemeyer I'd be interested in reviewing this. Can anyone review?

**Comment by kyleniemeyer** [comment]
@moorepants absolutely! I was hoping to get someone familiar with SymPy, since this package relies on it. Please take a look at the [reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines), and add yourself as a reviewer via a PR to the [reviewer csv file](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv).

**Comment by kyleniemeyer** [comment]
@whedon assign @moorepants as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @moorepants

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/139. Feel free to close this issue now!
