### ISSUE TITLE
[PRE REVIEW]: Container Tree: Software to Model Container Filesystems, Packages, and Inheritance

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1343]
**Submitting author:** @vsoch (<a href="http://orcid.org/0000-0002-4387-3819">Vanessa Sochat</a>)
**Repository:** <a href="https://www.github.com/singularityhub/container-tree" target ="_blank">https://www.github.com/singularityhub/container-tree</a>
**Version:** 0.0.48
**Editor:** @brainstorm
**Reviewers:** @luizirber

**Author instructions**

Thanks for submitting your paper to JOSS @vsoch. **Currently, there isn't an JOSS editor assigned** to your paper.

@vsoch if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1343 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01343/joss.01343/10.21105.joss.01343.pdf)

**Comment by arfon** [comment]
:wave: @trallard - would you be able to edit this submission?

**Comment by vsoch** [comment]
A new robot! :heart:

**Comment by arfon** [comment]
> A new robot! ❤️

Yes! This one [isn't ours though](https://github.com/swinton/probot-ooo). @vsoch - would you be willing to wait until `@trallard` is back before moving this forward?

**Comment by vsoch** [comment]
Sure, if there isn't anyone else suitable to review, this is okay with me.

**Comment by vsoch** [comment]
Oup, @trallard has an :avocado: in her name, I'm definitely okay to wait!

**Comment by arfon** [comment]
> Sure, if there isn't anyone else suitable to review, this is okay with me.

Thanks. This is mostly because lots of our editors are very busy with submissions right now.

**Comment by vsoch** [comment]
Understood! If you ever need another hand, I'm always here to offer :)

**Comment by labarba** [comment]
@trallard — Looks like we're waiting to hear from you. We'd like to assign this submission to you for editing. Let us know!

**Comment by vsoch** [comment]
Thanks @labarba. Let me know if I can help in any way - we are 25 days in and I hope that we can get underway soon!

**Comment by trallard** [comment]
Hi @labarba  I would be happy to take up on the editorial duties for this submission 😄

**Comment by labarba** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by luizirber** [comment]
Hi,

@brainstorm contacted me some time ago to check if I was interested in reviewing this, but I was busy. I have time available now, if you're still looking for a reviewer =]

**Comment by vsoch** [comment]
@luizirber this would be great! @trallard @labarba do we need a reviewer? It would be great to get this underway soon :)

And thanks @brainstorm you (continue to be) awesome!

**Comment by vsoch** [comment]
Hey guys are we ready to move forward?

**Comment by brainstorm** [comment]
@whedon assign @brainstorm as editor

**Comment by whedon** [comment]
OK, the editor is @brainstorm

**Comment by brainstorm** [comment]
@whedon assign @luizirber as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @luizirber

**Comment by brainstorm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1418. Feel free to close this issue now!

**Comment by brainstorm** [comment]
Let's do it! :)
