### ISSUE TITLE
[REVIEW]: GUESSmyLT: Software to guess the RNA-Seq library type of paired and single end read files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1344]
**Submitting author:** @Juke34 (<a href="http://orcid.org/0000-0002-6629-0173">Jacques Dainat</a>)
**Repository:** <a href="https://github.com/NBISweden/GUESSmyLT" target ="_blank">https://github.com/NBISweden/GUESSmyLT</a>
**Version:** v1.0
**Editor:** @lpantano
**Reviewer:** @mistrm82
**Archive:** <a href="https://doi.org/10.5281/zenodo.3268394" target="_blank">10.5281/zenodo.3268394</a>

## Status

[![status](http://joss.theoj.org/papers/48dd8e1d72e65ce23f3a0216d0b035e7/status.svg)](http://joss.theoj.org/papers/48dd8e1d72e65ce23f3a0216d0b035e7)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/48dd8e1d72e65ce23f3a0216d0b035e7"><img src="http://joss.theoj.org/papers/48dd8e1d72e65ce23f3a0216d0b035e7/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/48dd8e1d72e65ce23f3a0216d0b035e7/status.svg)](http://joss.theoj.org/papers/48dd8e1d72e65ce23f3a0216d0b035e7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/NBISweden/GUESSmyLT" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mistrm82, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/NBISweden/GUESSmyLT">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0
- [x] **Authorship:** Has the submitting author (@Juke34) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mistrm82 it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01344/joss.01344/10.21105.joss.01344.pdf)

**Comment by lpantano** [comment]
Thanks @mistrm82 to take time to review this paper!

@Juke34, please, go over the items that the reviewer will need to check and make sure all are good to go. 

I think @mistrm82 will start reviewing the paper around Next Thursday. 

Cheers

**Comment by Juke34** [comment]
Everything sounds ok except we didn't have any Community guidelines. Now is done. I have re-flagged this last version as v1.0. I took the opportunity to add acknowledgements in the paper too, and move all the paper related files into the paper dedicated folder. So, I guess we should compile the pdf again...

**Comment by lpantano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01344/joss.01344/10.21105.joss.01344.pdf)

**Comment by mistrm82** [comment]
Apologies for the delay, I should have this complete by tomorrow

**Comment by mistrm82** [comment]
@Juke34 I am having some problems installing (created an issue) so I have not been able to assess the "Functionality" section

**Comment by mistrm82** [comment]
I think this is a great tool with functionality that meets a need for researchers doing NGS analysis. The problems I encountered is that installation is quite involved. I created a conda environment with the prerequisites (biopython, pysam, bcbio-gff) which was not too much of an issue. However, when trying to run some commands I encountered errors due to the lack of other required programs (i.e busco, trinity). Working on a cluster environment, the installation of these tools is not always straightforward. Is there any way to have these extra programs be installed as dependencies when you run the setup.py install? This would make it easier. Since I couldn't do these installations I was unable to fully test out functionality.

**Comment by lpantano** [comment]
Hi @Juke34, Do you think you can address @mistrm82 comment to get a better way to get the tool installed?

**Comment by Juke34** [comment]
Yes I think we can make a bioconda package.

**Comment by labarba** [comment]
👋 @Juke34  — How are you getting along? Can you give us a status update on this submission?

**Comment by Juke34** [comment]
I started to work on it but I have to do some test before to release it. I'm currently busy by teachings. I hope it could be done by the end of may.

**Comment by labarba** [comment]
Hi @Juke34 — Can you give us an update? If you're not close to done, please let me know of a time period to set a reminder for you.

**Comment by Juke34** [comment]
Thank you for your patience. Here are the updates: We have slightly modified the installation. We have created a PyPi package (https://pypi.org/project/guessmylt/), allowing installation using pip.  So, using `pip install GUESSmyLT` will install most of the dependencies. Still Bowtie2, BUSCO and Trinity (depending of the user need Trinity is not mandatory) has to be installed aside.

Working on conda to package the whole, I have seen differences in the BUSCO results between osx and linux, and Trinity does not work on osx. So I have created a Bioconda recipe that should be compiled on linux (https://github.com/bioconda/bioconda-recipes/pull/15786). Each package added to Bioconda also has a corresponding Docker BioContainer automatically created and uploaded to Quay.io. Once the container available, the reproducibility problem (different result between mac and linux) would be solved. The thing is, my Bioconda package is currently stuck at the check step because the bioconda-utils is encountered some issues (https://github.com/bioconda/bioconda-utils/pull/567) that have to be resolved first.

May the simplification with `pip install GUESSmyLT` enough for publication?

**Comment by labarba** [comment]
@mistrm82 — Let us know your assessment and response to the author's reply, above.

**Comment by mistrm82** [comment]
HI @Juke34 and @labarba  I will take a look over the next few days and will respond to the new updates. thanks!

**Comment by epruesse** [comment]
@Juke34 The problem with your package is not related to the bioconda-utils PR mentioned. 

- You are currently installing files to `site-packages/example_run` which should go to `site-packages/GUESSmlLT` or be omitted from distributed package.
- The package currently fails in testing. If you look at the build logs, you will find at the bottom during the tests in an isolated minimal container an exception raised by gitpython indicating that `git` is missing. It's likely due to a missing run dependency on `git` itself.

**Comment by lpantano** [comment]
I have added the right tag to get this merged, if not I could ping the bioconda team. Thanks for the effort.

**Comment by mistrm82** [comment]
Thanks @Juke34  for both the PyPi package (https://pypi.org/project/guessmylt/) and the bioconda recipe. The problem I had previously was the inability to get Busco and so I think I will hold off on testing the PyPi  package and wait for the PR merge from bioconda

**Comment by Juke34** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01344/joss.01344/10.21105.joss.01344.pdf)

**Comment by lpantano** [comment]
@mistrm82, the package should be able through bioconda today, so feel free to test it from tomorrow. Let us know if you find any issue. Thanks!

**Comment by mistrm82** [comment]
Sorry for the delay. I was successfully able to install via bioconda and use the tool. Thanks @Juke34 everything looks great to me

**Comment by lpantano** [comment]
@whedon  generate pdf

**Comment by lpantano** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1093/bioinformatics/bts356 is OK
- 10.1038/nmeth.4197 is OK
- 10.1038/nmeth.1923 is OK
- doi: 10.1093/molbev/msx319  is OK
- 10.1038/nbt.1883 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lpantano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01344/joss.01344/10.21105.joss.01344.pdf)

**Comment by lpantano** [comment]
@Juke34, We are almost there. Can you generate a Zenodo archive pointing to your github current version and making sure title and authors match the Zenodo link? Thanks

**Comment by lpantano** [comment]
@whedon set v1.0 as version

**Comment by whedon** [comment]
OK. v1.0 is the version.

**Comment by Juke34** [comment]
Here is the dog: 10.5281/zenodo.3268394

**Comment by lpantano** [comment]
@whedon set  10.5281/zenodo.3268394 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3268394" target="_blank">10.5281/zenodo.3268394</a> is the archive.

**Comment by lpantano** [comment]
Thanks for the hard work to the authors and reviewers. @openjournals/joss-eics this is accepted now.

**Comment by labarba** [comment]
I'm confused by the author list: are commas missing, or something? It looks like some authors have a single-letter last name. Are first and last names being displayed in the wrong order?

**Comment by Juke34** [comment]
My mistake sorry. It should be now fixed.

**Comment by Juke34** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01344/joss.01344/10.21105.joss.01344.pdf)

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1093/bioinformatics/bts356 is OK
- 10.1038/nmeth.4197 is OK
- 10.1038/nmeth.1923 is OK
- doi: 10.1093/molbev/msx319  is OK
- 10.1038/nbt.1883 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/820

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/820, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1147897712316170240) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/821
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01344](https://doi.org/10.21105/joss.01344)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @Juke34, your JOSS paper is published! 🚀 

Big thanks to our editor: @lpantano, and the reviewer: @mistrm82 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01344/status.svg)](https://doi.org/10.21105/joss.01344)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01344">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01344/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01344/status.svg
   :target: https://doi.org/10.21105/joss.01344
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01344/status.svg)](https://doi.org/10.21105/joss.01344)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
