### ISSUE TITLE
[PRE REVIEW]: AMReX: a framework for block-structured adaptive mesh refinement

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1347]
**Submitting author:** @asalmgren (<a href="http://orcid.org/0000-0003-2103-312X">Ann Almgren</a>)
**Repository:** <a href="https://github.com/AMReX-Codes/amrex" target ="_blank">https://github.com/AMReX-Codes/amrex</a>
**Version:** current master branch on github
**Editor:** @kyleniemeyer
**Reviewers:** @MatthewTurk, @RemiLehe , @cmsquared

**Author instructions**

Thanks for submitting your paper to JOSS @asalmgren. **Currently, there isn't an JOSS editor assigned** to your paper.

@asalmgren if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1347 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @kyleniemeyer - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
PDF failed to compile for issue #1347 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:91:in `block in check_orcids': Problem with ORCID (0000-0002-1752-1631) for Brian Friesen (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@asalmgren - `0000-0002-1752-1631` looks to be an invalid ORCID. Please check.

**Comment by asalmgren** [comment]
@arfon The ORCID for Brian Friesen has been fixed.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01347/joss.01347/10.21105.joss.01347.pdf)

**Comment by asalmgren** [comment]
I have checked the proof.

**Comment by asalmgren** [comment]
@whedon I approve the proof

**Comment by danielskatz** [comment]
👋 @kyleniemeyer - the submitting author suggested you as the handling editor.

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
Hi @asalmgren, thanks for your submission! I will try to find a reviewer from the JOSS pool to assign, but I generally prefer two or three reviewers for submissions. Do you have any suggestions for potential reviewers with domain-specific expertise? I will then reach out to them.

**Comment by asalmgren** [comment]
I'm not sure if you allow users of the software to be reviewers?

If so, then I recommend

Brandon Runnels, Univ of Colorado, Colorado Springs:   brunnels@uccs.edu

Jordan Musser, NETL Jordan.Musser@netl.doe.gov <grote1@llnl.gov>

Remi Lehe, LBNL  rlehe@lbl.gov

If you want reviewers who aren't using AMReX (or AMReX-based application
codes), then perhaps

Chris Malone, LANL cmalone@lanl.gov

Matt Turk  mjturk@illinois.edu <mjturk@illinois.edu>

**Comment by kyleniemeyer** [comment]
@asalmgren thanks! I've reached out to a few potential reviewers.

**Comment by kyleniemeyer** [comment]
@whedon add @MatthewTurk as reviewer

**Comment by whedon** [comment]
OK, @MatthewTurk is now a reviewer

**Comment by kyleniemeyer** [comment]
@RemiLehe has agreed to serve as a second reviewer, after disclosing a potential conflict of interest due to collaboration on another project (https://github.com/ECP-WarpX/WarpX)

**Comment by kyleniemeyer** [comment]
@whedon add @RemiLehe  as reviewer

**Comment by whedon** [comment]
OK, @RemiLehe  is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon add @cmsquared as reviewer

**Comment by whedon** [comment]
OK, @cmsquared is now a reviewer

**Comment by kyleniemeyer** [comment]
OK @asalmgren we now have three reviewers, so I'll start the actual review process in a new issue.

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1370. Feel free to close this issue now!
