### ISSUE TITLE
[REVIEW]: prysm: A Python optics module

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1352]
**Submitting author:** @brandondube (<a href="http://orcid.org/0000-0002-3837-605X">Brandon Dube</a>)
**Repository:** <a href="https://github.com/brandondube/prysm" target ="_blank">https://github.com/brandondube/prysm</a>
**Version:** v0.16
**Editor:** @xuanxu
**Reviewer:** @aquilesC
**Archive:** <a href="https://doi.org/10.5281/zenodo.2672954" target="_blank">10.5281/zenodo.2672954</a>

## Status

[![status](http://joss.theoj.org/papers/2348fba6a2c53cc06b892365ba72fb42/status.svg)](http://joss.theoj.org/papers/2348fba6a2c53cc06b892365ba72fb42)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/2348fba6a2c53cc06b892365ba72fb42"><img src="http://joss.theoj.org/papers/2348fba6a2c53cc06b892365ba72fb42/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/2348fba6a2c53cc06b892365ba72fb42/status.svg)](http://joss.theoj.org/papers/2348fba6a2c53cc06b892365ba72fb42)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/brandondube/prysm" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@aquilesC, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @xuanxu know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/brandondube/prysm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.16
- [x] **Authorship:** Has the submitting author (@brandondube) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @aquilesC it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01352/joss.01352/10.21105.joss.01352.pdf)

**Comment by xuanxu** [comment]
:wave: @aquilesC What's your status with the continued review of this submission?

**Comment by brandondube** [comment]
Are there any updates or changes I need to make to the repository or the manuscript?

**Comment by aquilesC** [comment]
I will update it soon!
I was overwhelmed by some other tasks, but this week is going to be easier
for me. Overall is OK, I have some comments regarding the documentation. As
soon as I can seat down on my PC, I'll update you.

**Comment by aquilesC** [comment]
I have finished reviewing Prysm. It is a very nice package and I think it fulfills all the criteria to be published in JOSS. I have two small suggestions to improve the repository for the future: 

- Contributing guidelines could be expanded. Perhaps adding an extra file in the docs, like [Pandas](https://pandas-docs.github.io/pandas-docs-travis/development/contributing.html) or [Numpy](https://www.numpy.org/devdocs/dev/index.html) did. It can be useful to create issues for missing features and linking them to the project's roadmap (the capabilities of the project board on Github are quite limited, without room for discussion, assigning people, etc.) It is also important to explain how to contribute in practical *Github* matters. For example, pull requests should be of squashed commits or should they contain the entire history? 

- The API documentation appears only in the *latest* version on Readthedocs but not on the *stable* version. 

The suggestions above, however, do not change the code. Therefore, @brandondube can upload the program to Zenodo and get the doi. If I'm not mistaken, after this stage, things are back in the hands of @xuanxu ?

**Comment by xuanxu** [comment]
Thanks @aquilesC!

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01352/joss.01352/10.21105.joss.01352.pdf)

**Comment by xuanxu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1109/MCSE.2007.55 is OK
- 10.5281/zenodo.2558175 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by xuanxu** [comment]
@brandondube I just found a minor typo in the article proof: `propgations` -> `propagations`. Other than that everything looks good for publication.

Once you fix the typo, please create an archive in zenodo/figshare/other and report the DOI here (if needed edit the deposit metadata so it matches the title and author name of [the JOSS paper](https://github.com/openjournals/joss-papers/blob/joss.01352/joss.01352/10.21105.joss.01352.pdf))

**Comment by brandondube** [comment]
@xuanxu Thanks for the catch!  I fixed the typo in the paper.  For Zenodo/etc, do I upload prysm@v0.15.1, 0.15.1 patched with the paper typo fix, or latest?  And is the convention to zip up the entire contents of the root directory, less .git?  Or just the minimum artifacts for the software to install?

**Comment by xuanxu** [comment]
@brandondube usually you would release a new version with all the changes made during the review process, once you do that I'll update the version here and that would be the version you need to upload to Zenodo.

The convention is to upload the zip that GitHub provides in the release page (example: [link to zip here in the 'Assets' section](https://github.com/brandondube/prysm/releases/tag/v0.15.1)). That will include the root directory you see in GitHub (no .git dir) at the moment that specific version was released.

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01352/joss.01352/10.21105.joss.01352.pdf)

**Comment by brandondube** [comment]
@xuanxu thanks.  The change was pushed, but to dev.  It is on master now, along with about 90 commits of other changes :)

I'm within spitting distance (a week or so) of releasing v0.16 -- would it be alright to save the finalization here until then?

**Comment by brandondube** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01352/joss.01352/10.21105.joss.01352.pdf)

**Comment by xuanxu** [comment]
@brandondube I'm ok with waiting for a week for the new release. Please tell us here once you are ready for the v0.16 and I'll ping aquilesC then for a quick re-review so we are sure everything is still fine. Is that ok with you @aquilesC ?

**Comment by aquilesC** [comment]
It is fine with me! Let me know when the new version is out!

**Comment by brandondube** [comment]
@aquilesC v0.16 will have a final check-over tomorrow and assuming I find nothing derailing, a release monday.  If you would like to begin your check-over, you can see the changes (summarized with git):

```bash
cd prysm
git checkout master
git pull
git diff HEAD v0.15.1 --stat
```

They are also summarized in the release notes,
https://prysm.readthedocs.io/en/latest/releases/v0.16.html
You might have to clear your cache for this to render fully up-to-date, and wait about an hour for the RTD build to complete.

I also opened several issues on the repo with some features, bugs, etc, for future releases and adding a contributing guide to the docs.

Cheers,
- Brandon

**Comment by aquilesC** [comment]
@brandondube , everything is looking fine! 
The issues and the contributing guidelines make a much clearer entry point for new contributors. 
I've run the tests and the examples, and everything looks OK. 

Let me know when you publish to PyPI so I test the entire install cycle, and I guess that would be it.

**Comment by brandondube** [comment]
The release is up on PyPI!  Once you've given the OK, I'll package it on Zenodo for the submission 🚀

**Comment by brandondube** [comment]
@xuanxu I uploaded to Zenodo -- https://zenodo.org/record/2672954

DOI 10.5281/zenodo.2672954 🍾

**Comment by xuanxu** [comment]
@brandondube Great, thanks!

**Comment by xuanxu** [comment]
@whedon set v0.16 as version

**Comment by whedon** [comment]
OK. v0.16 is the version.

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01352/joss.01352/10.21105.joss.01352.pdf)

**Comment by xuanxu** [comment]
@whedon set 10.5281/zenodo.2672954 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2672954" target="_blank">10.5281/zenodo.2672954</a> is the archive.

**Comment by xuanxu** [comment]
OK, everything ready for publication. Thanks for the review @aquilesC!

Pinging @openjournals/joss-eics for final acceptance

**Comment by labarba** [comment]
@brandondube — I'm not sure if this matters, but it looks like you pushed v0.16 as a tag, without creating the release. You can see that the "Latest release" flag is not shown next to it:
https://github.com/brandondube/prysm/releases

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1109/MCSE.2007.55 is OK
- 10.5281/zenodo.2558175 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/675

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/675, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by brandondube** [comment]
👋 @labarba not sure if it matters either (I uploaded the release on PyPi) - but I went ahead and turned the tag into a release on GH as well.

RTD seems to be having some widespread issues w/ conda right now, so unfortunately the docs won't be updated until those are resolved.

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/678
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01352](https://doi.org/10.21105/joss.01352)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @brandondube, your JOSS paper is now published? 🎉 

Sincere thanks to our editor: @xuanxu, and the reviewer: @aquilesC — your contribution to JOSS is invaluable 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01352/status.svg)](https://doi.org/10.21105/joss.01352)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01352">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01352/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01352/status.svg
   :target: https://doi.org/10.21105/joss.01352
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01352/status.svg)](https://doi.org/10.21105/joss.01352)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by farrukhazfar** [comment]
Hi Folks, wondering if this is the appropriate place to post a question - apologies if it isn't : In Wavefront.from_amp_and_phase(aperture, opd, wvl, dx) is the "aperture" neccesarily supposed to be a mask ? If it can be numbers then can it must be a "scalar" ( as in scalar diffraction theory) field and not an intensity - yes ? kind regards and thanks, Farrukh Azfar

**Comment by kyleniemeyer** [comment]
@farrukhazfar the appropriate place to ask questions about the software would be in its repository: https://github.com/brandondube/prysm

**Comment by kyleniemeyer** [comment]
@farrukhazfar the issues tab in the actual repository for the software would be appropriate (https://github.com/brandondube/prysm/issues) - you've posted this in a closed, six-year old review issue for the journal article about the software.
