### ISSUE TITLE
[PRE REVIEW]: WGS2NCBI - Toolkit for preparing genomes for submission to NCBI

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1353]
**Submitting author:** @rvosa (<a href="http://orcid.org/0000-0001-9254-7318">Rutger Vos</a>)
**Repository:** <a href="https://github.com/naturalis/wgs2ncbi" target ="_blank">https://github.com/naturalis/wgs2ncbi</a>
**Version:** v1.0.0
**Editor:** @lpantano
**Reviewers:** @druvus

**Author instructions**

Thanks for submitting your paper to JOSS @rvosa. **Currently, there isn't an JOSS editor assigned** to your paper.

@rvosa if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1353 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5469df74be0c/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5469df74be0c/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5469df74be0c/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5469df74be0c/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5469df74be0c/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5469df74be0c/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
@rvosa, please check your paper source, using https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography as an example/template.  When you've made changes, enter ```@whedon generate pdf``` as a new comment here, and iterate until you are happy with the paper.  Then we'll start the pre-review process by assigning an editor.

**Comment by danielskatz** [comment]
👋 bioinformatics editing team (@pjotrp @mgymrek @brainstorm @lpantano) - can one of you take on this submission as editor?

**Comment by rvosa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01353/joss.01353/10.21105.joss.01353.pdf)

**Comment by pjotrp** [comment]
> wave bioinformatics editing team (@pjotrp @mgymrek @brainstorm @lpantano) - can one of you take on this submission as editor?

We'll take it on. Thanks @rvosa for submitting this interesting tool!

**Comment by danielskatz** [comment]
👋 @pjotrp @mgymrek @brainstorm @lpantano - it would be great if whichever of you is willing to edit this would assign it your self as editor :)

**Comment by lpantano** [comment]
@whedon  assign @lpantano as editor

**Comment by lpantano** [comment]
@danielskatz  @arfon I think whedon doesn't like me anymore ..... it doesn't assign me as editor, maybe I lost permissions :/

**Comment by kyleniemeyer** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by kyleniemeyer** [comment]
@lpantano weird! I had also been noticing some delays with whedon, maybe that was the issue.

**Comment by arfon** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@Kevin-Mattheus-Moerman
@VivianePons
@alexhanna
@arfon
@arokem
@brainstorm
@cMadan
@danielskatz
@eramirem
@gkthiruvathukal
@jasonclark
@jedbrown
@karthik
@katyhuff
@kthyng
@kyleniemeyer
@labarba
@leouieda
@lheagy
@lpantano
@mgymrek
@pjotrp
@poulson
@trallard
@usethedata
@xuanxu
@yochannah
```

**Comment by arfon** [comment]
> @danielskatz @arfon I think whedon doesn't like me anymore ..... it doesn't assign me as editor, maybe I lost permissions :/

Hrm, not sure what's up here.

**Comment by lpantano** [comment]
@whedon assign @druvus as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @druvus

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1364. Feel free to close this issue now!
