### ISSUE TITLE
[PRE REVIEW]: SMACT: Semiconducting Materials by Analogy and Chemical Theory

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1354]
**Submitting author:** @dandavies99 (<a href="http://orcid.org/0000-0003-4094-5992">D. W. Davies</a>)
**Repository:** <a href="https://github.com/WMD-group/SMACT/" target ="_blank">https://github.com/WMD-group/SMACT/</a>
**Version:** v2.0.2
**Editor:** @usethedata
**Reviewers:** @symmy596, @utf

**Author instructions**

Thanks for submitting your paper to JOSS @dandavies99. **Currently, there isn't an JOSS editor assigned** to your paper.

@dandavies99 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01354/joss.01354/10.21105.joss.01354.pdf)

**Comment by danielskatz** [comment]
👋 @usethedata - the submitters suggested you as the editor. Are you able to accept?

**Comment by dandavies99** [comment]
Suggested potential reviewers: @utf, @symmy596, @kjappelbaum.

**Comment by usethedata** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by usethedata** [comment]
@whedon assign @symmy596 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @symmy596

**Comment by usethedata** [comment]
@whedon add @utf as reviewer

**Comment by whedon** [comment]
OK, @utf is now a reviewer

**Comment by usethedata** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.chempr.2016.09.010 is OK
- https://doi.org/10.1016/0022-3697(64)90176-3 is OK
- https://doi.org/10.1016/0022-3697(58)90050-7 is OK
- 10.1021/cm400893e is OK
- 10.1021/ja204670s is OK
- 10.1039/C8FD00032H is OK
- 10.1039/TF9292500253 is OK
- 10.1103/PhysRevLett.33.1088 is OK
- https://doi.org/10.1016/j.commatsci.2018.05.018 is OK
- https://doi.org/10.1016/j.commatsci.2012.10.028 is OK
- 10.1038/s41586-018-0337-2 is OK
- 10.1186/1758-2946-3-33 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by usethedata** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1361. Feel free to close this issue now!
