### ISSUE TITLE
[PRE REVIEW]: OrpailleCC: a Library for Data Stream Analysis on Embedded Systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1357]
**Submitting author:** @Azazel7 (<a href="http://orcid.org/0000-0003-2129-5517">Martin Khannouz</a>)
**Repository:** <a href="https://github.com/big-data-lab-team/OrpailleCC" target ="_blank">https://github.com/big-data-lab-team/OrpailleCC</a>
**Version:** V1.0
**Editor:** @gkthiruvathukal
**Reviewers:** @sepandhaghighi

**Author instructions**

Thanks for submitting your paper to JOSS @Azazel7. **Currently, there isn't an JOSS editor assigned** to your paper.

@Azazel7 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1357 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon/author.rb:58:in `block in build_affiliation_string': Problem with affiliations for Martin Khannouz, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon/author.rb:57:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon/author.rb:57:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon.rb:109:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon.rb:109:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon.rb:106:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon.rb:106:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @azazel7 - there's a problem with your paper, as seen from the whedon comment above.  Please make changes, following the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography), and then enter ```@whedon generate pdf``` as a new comment here to recompile the paper, and repeat until you are happy with it.

**Comment by danielskatz** [comment]
In this case, the affiliations in the author block need to be simple integers that refer to the affiliations block, not complete affiliations in the author block.  Again, see the example.

**Comment by danielskatz** [comment]
👋 @eramirem - would you be able to edit this submission?

**Comment by azazel7** [comment]
@danielskatz Thanks. I made the modifications.

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01357/joss.01357/10.21105.joss.01357.pdf)

**Comment by labarba** [comment]
@azazel7 — We're missing in your paper a brief description of how the software is used or can be used in research settings. Could you expand that? Please also comment on any extant software that targets the same (or similar) application or functionality.

**Comment by danielskatz** [comment]
I'm going to mark this as paused for now - please let us know when you have added to the paper as requested by @labarba and are ready to proceed.

**Comment by azazel7** [comment]
A paragraph has been refactored to add the required information. The goal of OrpailleCC is to provide a consistent environment to study data stream algorithms for embedded systems. I will use this library for my own research as well.
@whedon generate pdf

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01357/joss.01357/10.21105.joss.01357.pdf)

**Comment by danielskatz** [comment]
@azazel7 - At some point, you will need to add DOIs to references that have them.  Once you have done so, you can regenerate the PDF by adding a new comment here that is ```@whedon generate pdf``` (not as part of another comment, but as a new comment)

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1109/bigdata.2018.8621946 may be missing for title: A multi-dimensional extension of the Lightweight Temporal Compression method
- https://doi.org/10.1145/362686.362692 may be missing for title: Space/Time Trade-offs in Hash Coding with Allowable Errors
- https://doi.org/10.3390/a10030080 may be missing for title: A hybrid algorithm for optimal wireless sensor network deployment with the minimum number of sensor nodes
- https://doi.org/10.1109/bigdata.2018.8621946 may be missing for title: A multi-dimensional extension of the Lightweight Temporal Compression method
- https://doi.org/10.2307/2685209 may be missing for title: An introduction to kernel and nearest-neighbor nonparametric regression
- https://doi.org/10.1109/hicss.2000.926982 may be missing for title: Energy-efficient communication protocol for wireless microsensor networks
- https://doi.org/10.1109/glocom.2002.1188034 may be missing for title: Analysis of energy consumption and lifetime of heterogeneous wireless sensor networks
- https://doi.org/10.1109/35.925682 may be missing for title: Maximum battery life routing to support ubiquitous mobile computing in wireless ad hoc networks

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
see the above for suggestions, but be aware, it is not always completely correct, so take it with a grain of salt...

**Comment by danielskatz** [comment]
👋 @gkthiruvathukal - would you be willing to edit this submission?

**Comment by gkthiruvathukal** [comment]
@danielskatz Yes.

**Comment by danielskatz** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by azazel7** [comment]
@danielskatz Ok.

**Comment by azazel7** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.14778/2824032.2824132 is OK
- 10.1109/lcn.2004.72 is OK
- 10.1109/bigdata.2018.8621946 is OK
- 10.1145/2674005.2674994 is OK
- 10.1016/j.future.2017.03.026 is OK
- 10.1145/3147.3165 is OK
- 10.1145/362686.362692 is OK
- 10.3390/a10030080 is OK
- 10.2307/2685209 is OK
- 10.1109/hicss.2000.926982 is OK
- 10.1109/glocom.2002.1188034 is OK
- 10.1109/35.925682 is OK
- 10.1145/1656274.1656278 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01357/joss.01357/10.21105.joss.01357.pdf)

**Comment by azazel7** [comment]
@danielskatz I found most of the DOIs of the references in the paper, except for two of them.

**Comment by danielskatz** [comment]
Great - for the couple of the conference proceedings where the cases are incorrect, you might add another {} around the text where you want to preserve the case in the .bib file.

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01357/joss.01357/10.21105.joss.01357.pdf)

**Comment by azazel7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01357/joss.01357/10.21105.joss.01357.pdf)

**Comment by azazel7** [comment]
I think it's fixed.

**Comment by gkthiruvathukal** [comment]
@azazel7 Can you take a look at https://bit.ly/joss-reviewers and suggest any reviewers?

**Comment by azazel7** [comment]
@gkthiruvathukal : I had a look at the list and I would suggest the following names:
- federeghe
- sepandhaghighi
- aaronyd
- gcdeshpande
- conradsnicta
- adavidzh
- lisitsyn

I made sure that all have a background in C++ as well as knowledge on embedded systems and machine learning. None of them are known by me or any author of OrpailleCC.

**Comment by gkthiruvathukal** [comment]
@azazel7 Thanks for your suggestions from our list. I was a bit busy grading finals so there was a bit of a delay in getting started. Stay tuned.

**Comment by gkthiruvathukal** [comment]
@federeghe Would you be willing to contribute a review for this JOSS submission?

**Comment by gkthiruvathukal** [comment]
@sepandhaghighi Would you also be willing to contribute a review for this JOSS submission?

**Comment by federeghe** [comment]
@gkthiruvathukal Yes I would, but probably I cannot begin the review before June 1.

**Comment by sepandhaghighi** [comment]
@gkthiruvathukal Hi
Yes, I'm available.

**Comment by gkthiruvathukal** [comment]
@whedon assign @sepandhaghighi as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sepandhaghighi

**Comment by gkthiruvathukal** [comment]
@whedon list

**Comment by gkthiruvathukal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1485. Feel free to close this issue now!
