### ISSUE TITLE
[REVIEW]: The MTPy software package for magnetotelluric data analysis and visualisation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1358]
**Submitting author:** @alkirkby (<a href="http://orcid.org/0000-0003-1361-440X">Alison Kirkby</a>)
**Repository:** <a href="https://github.com/MTgeophysics/mtpy" target ="_blank">https://github.com/MTgeophysics/mtpy</a>
**Version:** v1.0
**Editor:** @lheagy
**Reviewer:** @JKutt
**Archive:** <a href="https://doi.org/10.5281/zenodo.2698634" target="_blank">10.5281/zenodo.2698634</a>

## Status

[![status](http://joss.theoj.org/papers/ccb44c5f422e8f52c244665ae4794f76/status.svg)](http://joss.theoj.org/papers/ccb44c5f422e8f52c244665ae4794f76)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/ccb44c5f422e8f52c244665ae4794f76"><img src="http://joss.theoj.org/papers/ccb44c5f422e8f52c244665ae4794f76/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/ccb44c5f422e8f52c244665ae4794f76/status.svg)](http://joss.theoj.org/papers/ccb44c5f422e8f52c244665ae4794f76)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/MTgeophysics/mtpy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@JKutt, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lheagy know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MTgeophysics/mtpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0
- [x] **Authorship:** Has the submitting author (@alkirkby) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @JKutt it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1358 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by lheagy** [comment]
:wave: Many thanks @JKutt for being willing to review! Above there is a checklist to help guide your review. Please feel free to open issues on the [target repository](https://github.com/MTgeophysics/mtpy) with comments or suggestions for improvement in the submission and link them here by mentioning openjournals/joss-reviews#1358 in the issue text. 

The author @alkirkby mentioned that she will fix the images in the paper on monday. 

Please let me know if you have any questions!

**Comment by alkirkby** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1358 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-96d847bd9060/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by alkirkby** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01358/joss.01358/10.21105.joss.01358.pdf)

**Comment by alkirkby** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01358/joss.01358/10.21105.joss.01358.pdf)

**Comment by JKutt** [comment]
Hi @lheagy, I managed to complete my review! I had a bit of a stumble at first getting things running but after following the Linux install more thoroughly I managed to get it going. Once up and running everything went quite smooth! A lot of good stuff in here. I found a few things and created an issue for one but the others already exist (e.g. error with print statements due to python 2 vs. 3).

**Comment by alkirkby** [comment]
Hey @JKutt, thanks for the review! We're glad you managed to install MTPy in the end, but we are tidying up some of the issues at the moment to make it easier for users.
I was wondering if you could let me know the issue numbers for the issues you mentioned above? I can't find anything in the issues page about print statements with python 2 vs 3, for example. I need to go through the issues page as some of the issues were resolved but never closed.

**Comment by lheagy** [comment]
Many thanks for your speedy review @JKutt! @alkirkby: it looks they are issues 
- MTgeophysics/mtpy#77
- MTgeophysics/mtpy#78

**Comment by alkirkby** [comment]
Great thanks @lheagy. I've checked both those issues - #78 has been addressed and I have now addressed #77.

**Comment by JKutt** [comment]
Hi @alkirkby the "print" statements issue was brought up in MTgeophysics/mtpy#63

**Comment by alkirkby** [comment]
Hi @JKutt, Fei tells me that the print statements issue was resolved, are you able to specify where in MTPy you're encountering these issues?

**Comment by JKutt** [comment]
> Hi @JKutt, Fei tells me that the print statements issue was resolved, are you able to specify where in MTPy you're encountering these issues?

@alkirkby sorry for the late reply, missed this one. I can't quite remember off the top of my head but it was in places where "print" is used instead of "print()"

**Comment by zhang01GA** [comment]
Hi  @JKutt and @alkirkby:
Two weeks ago, I did fix one new print issue in mtpy/imaging/plotstrike.py 
 https://github.com/MTgeophysics/mtpy/commit/c4b6f3d8ffac3636a9bb60e7fc072bffcf312f73

Today, I applied 2to3 to every *.py script in mtpy.  But had not found any print statement issue.
All active print statement has been changed to print() in the refactoring long time ago.
(some py2 prints may exist in commented out # lines. But they are not active).

Please let me know. Thanks

**Comment by lheagy** [comment]
Thanks @zhang01GA! @JKutt, would you mind taking another look when you have a chance?

**Comment by JKutt** [comment]
> Thanks @zhang01GA! @JKutt, would you mind taking another look when you have a chance?

All seems good now! No issues second time around.

**Comment by lheagy** [comment]
👋 @JKutt: it looks like the box for `automated-tests` is still un-checked. Do you have any other comments wrt testing? or can this be ticked off? Thanks!

**Comment by JKutt** [comment]
> 👋 @JKutt: it looks like the box for automated-tests is still un-checked. Do you have any other comments wrt testing? or can this be ticked off? Thanks!

@lheagy darn, I missed that one! Apologies. No concern on the testing, simply missed ticking it off. Should be good now!

**Comment by lheagy** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1111/j.1365-246X.2004.02281.x is OK
- 10.1111/j.1365-246X.2004.02203.x is OK
- 10.1029/JB092iB01p00633 is OK
- 10.1190/1.1442813 is OK
- 10.1111/j.1365-246X.2011.05347.x is OK
- 10.1016/j.cageo.2014.01.010 is OK
- 10.1016/J.CAGEO.2014.07.013 is OK
- 10.1190/1.1438799 is OK
- 10.1111/j.1365-246X.1962.tb02992.x is OK

MISSING DOIs

- https://doi.org/10.1111/j.1365-246x.2005.02779.x may be missing for title: Determinable and non-determinable parameters of galvanic distortion in magnetotellurics

INVALID DOIs

- None
```

**Comment by lheagy** [comment]
Many thanks @JKutt for your review!! 

@alkirkby, It looks like there is one missing DOI in the paper:
```
https://doi.org/10.1111/j.1365-246x.2005.02779.x may be missing for title: Determinable and non-determinable parameters of galvanic distortion in magnetotellurics
```

Also, I posted an issue about the documentation website - currently, it looks like the auto-documentation isn't functioning as expected (MTgeophysics/mtpy#80). Please take a look when you have a chance.

**Comment by alkirkby** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1111/j.1365-246x.2005.02779.x is OK
- 10.1111/j.1365-246X.2004.02281.x is OK
- 10.1111/j.1365-246X.2004.02203.x is OK
- 10.1029/JB092iB01p00633 is OK
- 10.1190/1.1442813 is OK
- 10.1111/j.1365-246X.2011.05347.x is OK
- 10.1016/j.cageo.2014.01.010 is OK
- 10.1016/J.CAGEO.2014.07.013 is OK
- 10.1190/1.1438799 is OK
- 10.1111/j.1365-246X.1962.tb02992.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by alkirkby** [comment]
Hi @lheagy, okay great!

@zhang01GA is looking into the documentation issue and will link the user guide from the main page. I've just fixed the doi issue. Nearly there!

**Comment by alkirkby** [comment]
Hi @lheagy, @zhang01GA has now fixed the documentation issue and has added a link to the user guide to the front page.

**Comment by lheagy** [comment]
Excellent, thanks @alkirkby!

Please take a look at the pdf proof below. If everything looks good, then please make a new release and archive the software on [zenodo](http://zenodo.org) or similar and ensure that the title and author list match those in the paper. Then, please post the new version number and doi here.

**Comment by lheagy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01358/joss.01358/10.21105.joss.01358.pdf)

**Comment by alkirkby** [comment]
Great thanks @lheagy,
I've just created a release and archived the software: DOI: 10.5281/zenodo.2698634
We are now just awaiting final sign-off of the proof. We'll let you know when it's ready to go!

**Comment by alkirkby** [comment]
Hi @lheagy,
We have just obtained final approval of the proof so are ready to go ahead with the next stage of the process!

**Comment by alkirkby** [comment]
version number is 1.0

**Comment by lheagy** [comment]
@whedon set 10.5281/zenodo.2698634 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2698634" target="_blank">10.5281/zenodo.2698634</a> is the archive.

**Comment by lheagy** [comment]
@whedon set 1.0 as version

**Comment by whedon** [comment]
OK. 1.0 is the version.

**Comment by lheagy** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1111/j.1365-246x.2005.02779.x is OK
- 10.1111/j.1365-246X.2004.02281.x is OK
- 10.1111/j.1365-246X.2004.02203.x is OK
- 10.1029/JB092iB01p00633 is OK
- 10.1190/1.1442813 is OK
- 10.1111/j.1365-246X.2011.05347.x is OK
- 10.1016/j.cageo.2014.01.010 is OK
- 10.1016/J.CAGEO.2014.07.013 is OK
- 10.1190/1.1438799 is OK
- 10.1111/j.1365-246X.1962.tb02992.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lheagy** [comment]
@whedon set v1.0 as version

**Comment by whedon** [comment]
OK. v1.0 is the version.

**Comment by lheagy** [comment]
:wave: @alkirkby, excellent! Would you mind updating the title in the zenodo archive to match the title of the paper: "The MTPy software package for magnetotelluric data analysis and visualisation". After that, we are good to go!

**Comment by alkirkby** [comment]
@lheagy, ok no worries, done.

**Comment by lheagy** [comment]
Many thanks @JKutt for your speedy review! and congratulations @alkirkby and team on your submission 🎉 

👋 @openjournals/joss-eics, this submission is ready to be accepted!

**Comment by danielskatz** [comment]
Thanks to @JKutt for reviewing and @lheagy for editing!

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1111/j.1365-246x.2005.02779.x is OK
- 10.1111/j.1365-246X.2004.02281.x is OK
- 10.1111/j.1365-246X.2004.02203.x is OK
- 10.1029/JB092iB01p00633 is OK
- 10.1190/1.1442813 is OK
- 10.1111/j.1365-246X.2011.05347.x is OK
- 10.1016/j.cageo.2014.01.010 is OK
- 10.1016/J.CAGEO.2014.07.013 is OK
- 10.1190/1.1438799 is OK
- 10.1111/j.1365-246X.1962.tb02992.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/709

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/709, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@alkirkby - I see a couple of reference problems that I've tried to fix via https://github.com/MTgeophysics/mtpy/pull/82

One is opening quotes that were backwards, and the other is an underscore that caused a URL to not work right.  I'm sure my fix will work for the quotes, but I'm not sure it will work for the URL. Can you accept the PR, and see if paper will compile?  If not, we can try to fix the underscore in the URL another way.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by alkirkby** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1358 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1358 with the following error: 

 sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.01358.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01358/joss.01358/10.21105.joss.01358.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01358/joss.01358/10.21105.joss.01358.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1111/j.1365-246x.2005.02779.x is OK
- 10.1111/j.1365-246X.2004.02281.x is OK
- 10.1111/j.1365-246X.2004.02203.x is OK
- 10.1029/JB092iB01p00633 is OK
- 10.1190/1.1442813 is OK
- 10.1111/j.1365-246X.2011.05347.x is OK
- 10.1016/j.cageo.2014.01.010 is OK
- 10.1016/J.CAGEO.2014.07.013 is OK
- 10.1190/1.1438799 is OK
- 10.1111/j.1365-246X.1962.tb02992.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/710

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/710, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1131333735734022149) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/711
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01358](https://doi.org/10.21105/joss.01358)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by alkirkby** [comment]
Hi @danielskatz just wondering if the DOI issue should have resolved by now? It's still failing to load the document for me.

**Comment by alkirkby** [comment]
It's working now, sorry I was just impatient :)

**Comment by danielskatz** [comment]
Yes, that’s why the review is still open. Let’s see if it resolves a little later; that’s usually the case.

**Comment by danielskatz** [comment]
Actually, it’s now working for me, though it might be cached for you.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01358/status.svg)](https://doi.org/10.21105/joss.01358)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01358">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01358/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01358/status.svg
   :target: https://doi.org/10.21105/joss.01358
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01358/status.svg)](https://doi.org/10.21105/joss.01358)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by alkirkby** [comment]
Thanks @danielskatz, yep it's working now, I was just a bit impatient. And thanks @lheagy and @JKutt for editing and reviewing!
