### ISSUE TITLE
Genralize language to include if use on a Mac is working correctly #1385

### ISSUE THREAD

**Issue by JKutt** [openjournals/joss-reviews#1362]
Windows and Linux use is stated but nothing about use on a Mac. Suggesting the mention if only to be used explicitly on Windows or Linux.

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1362 with the following error: 

 Can't find any papers to compile :-(
