### ISSUE TITLE
[REVIEW]: ACHR.cu: GPU sampling of metabolic networks.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1363]
**Submitting author:** @marouenbg (<a href="http://orcid.org/0000-0001-5934-966X">Marouen Ben Guebila</a>)
**Repository:** <a href="https://github.com/marouenbg/ACHR.cu" target ="_blank">https://github.com/marouenbg/ACHR.cu</a>
**Version:** v0.2
**Editor:** @lpantano
**Reviewer:** @wmegchel, @prasunanand
**Archive:** <a href="https://doi.org/10.5281/zenodo.3233085" target="_blank">10.5281/zenodo.3233085</a>

## Status

[![status](http://joss.theoj.org/papers/536aea75c0eadd41db178b1ca9604067/status.svg)](http://joss.theoj.org/papers/536aea75c0eadd41db178b1ca9604067)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/536aea75c0eadd41db178b1ca9604067"><img src="http://joss.theoj.org/papers/536aea75c0eadd41db178b1ca9604067/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/536aea75c0eadd41db178b1ca9604067/status.svg)](http://joss.theoj.org/papers/536aea75c0eadd41db178b1ca9604067)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/marouenbg/ACHR.cu" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@wmegchel & @prasunanand, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/marouenbg/ACHR.cu">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.2
- [x] **Authorship:** Has the submitting author (@marouenbg) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/marouenbg/ACHR.cu">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.2
- [x] **Authorship:** Has the submitting author (@marouenbg) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @wmegchel, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01363/joss.01363/10.21105.joss.01363.pdf)

**Comment by marouenbg** [comment]
@lpantano @wmegchel  @prasunanand
I thought that it can be cumbersome to go through all the dependencies with potentially no access to NVIDIA GPU, below I provide a code ocean capsule which is a container with all the dependencies cached. You can also have reproducible runs of an example.
https://codeocean.com/capsule/4395814/tree
I have that helps your assessment.

**Comment by lpantano** [comment]
Thanks for this. 

@wmegchel and @prasunanand, it is possible to give an update on the reviewing process? 

Thanks so much!

**Comment by prasunanand** [comment]
@marouenbg  I am unable to download 
Dependencies
IBM CPLEX v12.6 (free for academics)

**Comment by marouenbg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01363/joss.01363/10.21105.joss.01363.pdf)

**Comment by marouenbg** [comment]
@prasunanand Thanks for the feedback. I fixed the missing doi in the summary. Which error did you get when you could not download CPLEX? 
Otherwise, you can skip the installation part and check an installed version at code ocean https://codeocean.com/capsule/4395814/tree

**Comment by prasunanand** [comment]
Review done!

**Comment by lpantano** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0086587 is OK
- 10.1101/440701 is OK
- 10.1145/1365490.1365500 is OK
- 10.1287/opre.46.1.84 is OK
- 10.1109/hpcsim.2014.6903792 is OK
- 10.1038/s41596-018-0098-2 is OK
- 10.1016/j.cell.2015.05.019 is OK
- 10.1016/j.ymben.2003.09.002 is OK
- 10.1109/99.660313 is OK
- 10.1007/bf02989823 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lpantano** [comment]
Thank @prasunanand  and @wmegchel  for the nice review. I will proceed with acceptance.

@marouenbg could you create a Zenodo archive for your repository and pass me the DOI link? Make sure the author and title match the paper information. Congrats!

**Comment by marouenbg** [comment]
Awesome! Thanks @prasunanand for the review. @lpantano I need a couple of day to review the text and the we can proceed with the final version. Thank you!

**Comment by marouenbg** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0086587 is OK
- 10.1101/440701 is OK
- 10.1145/1365490.1365500 is OK
- 10.1287/opre.46.1.84 is OK
- 10.1109/hpcsim.2014.6903792 is OK
- 10.1038/s41596-018-0098-2 is OK
- 10.1016/j.cell.2015.05.019 is OK
- 10.1016/j.ymben.2003.09.002 is OK
- 10.1109/99.660313 is OK
- 10.1007/bf02989823 is OK
- 10.1038/nbt.2488 is OK
- 10.1128/ecosalplus.10.2.1 is OK
- 10.1186/1752-0509-2-79 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-642-22194-1_4 may be missing for title: A GPU-based parallel algorithm for large scale linear programming problem
- https://doi.org/10.1145/3297663.3310308 may be missing for title: Simultaneous solving of batched linear programs on a GPU
- https://doi.org/10.1016/j.jpdc.2019.01.001 may be missing for title: Two-dimensional batch linear programming on the GPU

INVALID DOIs

- None
```

**Comment by marouenbg** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0086587 is OK
- 10.1101/440701 is OK
- 10.1145/1365490.1365500 is OK
- 10.1287/opre.46.1.84 is OK
- 10.1109/hpcsim.2014.6903792 is OK
- 10.1038/s41596-018-0098-2 is OK
- 10.1016/j.cell.2015.05.019 is OK
- 10.1016/j.ymben.2003.09.002 is OK
- 10.1109/99.660313 is OK
- 10.1007/bf02989823 is OK
- 10.1038/nbt.2488 is OK
- 10.1128/ecosalplus.10.2.1 is OK
- 10.1186/1752-0509-2-79 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-642-22194-1_4 may be missing for title: A GPU-based parallel algorithm for large scale linear programming problem
- https://doi.org/10.1145/3297663.3310308 may be missing for title: Simultaneous solving of batched linear programs on a GPU
- https://doi.org/10.1016/j.jpdc.2019.01.001 may be missing for title: Two-dimensional batch linear programming on the GPU

INVALID DOIs

- None
```

**Comment by marouenbg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01363/joss.01363/10.21105.joss.01363.pdf)

**Comment by marouenbg** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0086587 is OK
- 10.1101/440701 is OK
- 10.1145/1365490.1365500 is OK
- 10.1287/opre.46.1.84 is OK
- 10.1109/hpcsim.2014.6903792 is OK
- 10.1038/s41596-018-0098-2 is OK
- 10.1016/j.cell.2015.05.019 is OK
- 10.1016/j.ymben.2003.09.002 is OK
- 10.1109/99.660313 is OK
- 10.1007/bf02989823 is OK
- 10.1038/nbt.2488 is OK
- 10.1128/ecosalplus.10.2.1 is OK
- 10.1186/1752-0509-2-79 is OK
- 10.1007/978-3-642-22194-1_4 is OK
- 10.1145/3297663.3310308 is OK
- 10.1016/j.jpdc.2019.01.001 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by marouenbg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01363/joss.01363/10.21105.joss.01363.pdf)

**Comment by marouenbg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01363/joss.01363/10.21105.joss.01363.pdf)

**Comment by marouenbg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01363/joss.01363/10.21105.joss.01363.pdf)

**Comment by marouenbg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01363/joss.01363/10.21105.joss.01363.pdf)

**Comment by marouenbg** [comment]
Hi @lpantano I am all set. A math symbol did not compile in the final text, but it is working now. Thanks to all involved!

**Comment by marouenbg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01363/joss.01363/10.21105.joss.01363.pdf)

**Comment by marouenbg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01363/joss.01363/10.21105.joss.01363.pdf)

**Comment by marouenbg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01363/joss.01363/10.21105.joss.01363.pdf)

**Comment by marouenbg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01363/joss.01363/10.21105.joss.01363.pdf)

**Comment by marouenbg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01363/joss.01363/10.21105.joss.01363.pdf)

**Comment by lpantano** [comment]
@whedon set  0.2 as version

**Comment by whedon** [comment]
OK.  0.2 is the version.

**Comment by lpantano** [comment]
@whedon set v0.2 as version

**Comment by whedon** [comment]
OK. v0.2 is the version.

**Comment by lpantano** [comment]
hi @marouenbg ,

thanks for the changes. Can you create now a zenodo archive and give me the DOI, after that we can proceed with the aceptance. Remember that the title and authors should match the paper information.

Thanks!

**Comment by marouenbg** [comment]
Hi @lpantano ,
here is the zenodo archive https://zenodo.org/record/3233085#.XO02GNNKii4
DOI/10.5281/zenodo.3233085

**Comment by lpantano** [comment]
@whedon set 10.5281/zenodo.3233085 as archive

**Comment by lpantano** [comment]
Hi @openjournals/joss-eics, 

I think this is complete!

**Comment by kyleniemeyer** [comment]
Hi @marouenbg, I just submitted two minor PRs for the paper and references; could you merge those and then we can rebuild the PDF?

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by marouenbg** [comment]
Done! Thanks @kyleniemeyer for spotting them out.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01363/joss.01363/10.21105.joss.01363.pdf)

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0086587 is OK
- 10.1101/440701 is OK
- 10.1145/1365490.1365500 is OK
- 10.1287/opre.46.1.84 is OK
- 10.1109/hpcsim.2014.6903792 is OK
- 10.1038/s41596-018-0098-2 is OK
- 10.1016/j.cell.2015.05.019 is OK
- 10.1016/j.ymben.2003.09.002 is OK
- 10.1109/99.660313 is OK
- 10.1007/bf02989823 is OK
- 10.1038/nbt.2488 is OK
- 10.1128/ecosalplus.10.2.1 is OK
- 10.1186/1752-0509-2-79 is OK
- 10.1007/978-3-642-22194-1_4 is OK
- 10.1145/3297663.3310308 is OK
- 10.1016/j.jpdc.2019.01.001 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0086587 is OK
- 10.1101/440701 is OK
- 10.1145/1365490.1365500 is OK
- 10.1287/opre.46.1.84 is OK
- 10.1109/hpcsim.2014.6903792 is OK
- 10.1038/s41596-018-0098-2 is OK
- 10.1016/j.cell.2015.05.019 is OK
- 10.1016/j.ymben.2003.09.002 is OK
- 10.1109/99.660313 is OK
- 10.1007/bf02989823 is OK
- 10.1038/nbt.2488 is OK
- 10.1128/ecosalplus.10.2.1 is OK
- 10.1186/1752-0509-2-79 is OK
- 10.1007/978-3-642-22194-1_4 is OK
- 10.1145/3297663.3310308 is OK
- 10.1016/j.jpdc.2019.01.001 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/719

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/719, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by lpantano** [comment]
Do the last changes change the Zenode DOI or/and version?

**Comment by kyleniemeyer** [comment]
@lpantano they were only minor changes to the paper, which we archive, so I wasn't worried about updating the Zenodo record

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1133460389818183681) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/720
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01363](https://doi.org/10.21105/joss.01363)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @marouenbg on your paper's publication in JOSS! Thanks also to @wmegchel and @prasunanand for reviewing, and @lpantano for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01363/status.svg)](https://doi.org/10.21105/joss.01363)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01363">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01363/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01363/status.svg
   :target: https://doi.org/10.21105/joss.01363
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01363/status.svg)](https://doi.org/10.21105/joss.01363)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by marouenbg** [comment]
@kyleniemeyer @arfon I just realized I had small typo in the title. First, a dash is missing in `gpu accelerated`. Second the title line ends with a full stop, which gives me references with two full stops. Is it possible to amend the title? Otherwise it is fine like it is.

**Comment by arfon** [comment]
@marouenbg - can you make your changes to the `paper.md` file and I can then update the paper.

**Comment by marouenbg** [comment]
@arfon I just corrected the title in `paper.md`. Thanks!

**Comment by arfon** [comment]
OK that's now updated. The changes might take a few hours to update as there's caching in place on the JOSS site.
