### ISSUE TITLE
[PRE REVIEW]: Tradestatistics: Open Trade Statistics API Wrapper and Utility Program

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1366]
**Submitting author:** @pachamaltese (<a href="http://orcid.org/0000-0003-1017-7574">Mauricio Vargas</a>)
**Repository:** <a href="https://github.com/ropensci/tradestatistics" target ="_blank">https://github.com/ropensci/tradestatistics</a>
**Version:** 0.1
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @pachamaltese. **Currently, there isn't an JOSS editor assigned** to your paper.

@pachamaltese if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kyleniemeyer** [comment]
@karthik looks like this is an rOpenSci-related submission. Can you edit?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01366/joss.01366/10.21105.joss.01366.pdf)

**Comment by arfon** [comment]
@pachamaltese - could you please add a little more detail to your paper explaining what people might use this for, including any links to associated research? We have some guidelines in our documentation here: https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

**Comment by pachamaltese** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by pachamaltese** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01366/joss.01366/10.21105.joss.01366.pdf)

**Comment by pachamaltese** [comment]
Dear @arfon 
I added more descriptive text. It is my intention to write a short article for the R package and another article for the API/data curation methodology. What do you think?

**Comment by labarba** [comment]
Hi @pachamaltese — After a pre-review of your submission, and an assessment by the editorial board at large, we find that this submission does not quite meet our [submission requirements](http://joss.theoj.org/about#submission_requirements). In particular, while the software seems very useful, it falls under the 'Minor utility' category, and we therefore decided not to put it through review. 

Thank you for considering JOSS as a venue for your software, and I hope you'll submit other software with research application in the future.

**Comment by pachamaltese** [comment]
@labarba Hi. I totally undestand, but what do you think about a larger (much larger) article about tradestatistics.io? it's a project that opens data from the UN that otherwise is not accesible for universities  without specific subscriptions.

**Comment by labarba** [comment]
I'm not sure what you mean by a larger article. JOSS doesn't publish long-form articles, but short articles _about research software_ (and the review is mostly about the software).
