### ISSUE TITLE
[PRE REVIEW]: Drifter-ML: Testing Machine Learning Algorithms

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1368]
**Submitting author:** @EricSchles (<a href="http://orcid.org/0000-0003-1160-366X">Eric Schles</a>)
**Repository:** <a href="https://github.com/EricSchles/drifter_ml" target ="_blank">https://github.com/EricSchles/drifter_ml</a>
**Version:** 0.18
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @EricSchles. **Currently, there isn't an JOSS editor assigned** to your paper.

@EricSchles if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1368 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
Hi @EricSchles, before we proceed, we need a paper associated with the submission. Please review our author guidelines: https://joss.readthedocs.io/en/latest/submitting.html

**Comment by danielskatz** [comment]
I'm going to mark this as paused for now - please let us know when you have created a paper and are ready to proceed.

**Comment by EricSchles** [comment]
Hi Daniel,

Sounds good - I should be able to start things up in a few days.

Eric

**Comment by danielskatz** [comment]
👋 @EricSchles - any update?

**Comment by EricSchles** [comment]
Sorry for the delay, i’m working on it.  I tend to write pretty slow
unfortunately.

Thanks for checking in!

**Comment by danielskatz** [comment]
👋 @EricSchles - just checking in again...

**Comment by danielskatz** [comment]
👋 @EricSchles - given that we're now approaching 2 months since the initial partial submission, I suggest we withdraw this, and when you are ready for us to review your paper and software, you resubmit to JOSS at that time.

**Comment by danielskatz** [comment]
👋 @EricSchles - having not heard anything, and having this submission in an early state, I am going to mark it as withdrawn, but please, when you are ready for us to review your paper and software, resubmit it to JOSS at that time.
