### ISSUE TITLE
[REVIEW]: Pyret: A Python package for analysis of neurophysiology data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#137]
**Submitting author:** @nirum (<a href="http://orcid.org/0000-0002-3946-4705">Niru Maheswaranathan</a>)
**Repository:** <a href="https://github.com/baccuslab/pyret" target ="_blank">https://github.com/baccuslab/pyret</a>
**Version:** v0.5.0
**Editor:** @arokem
**Reviewer:** @kdesimone
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.232521" target="_blank">10.5281/zenodo.232521</a>

## Status

[![status](http://joss.theoj.org/papers/73e486788290a6386e90a21c7e71bbe0/status.svg)](http://joss.theoj.org/papers/73e486788290a6386e90a21c7e71bbe0)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/73e486788290a6386e90a21c7e71bbe0"><img src="http://joss.theoj.org/papers/73e486788290a6386e90a21c7e71bbe0/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/73e486788290a6386e90a21c7e71bbe0/status.svg)](http://joss.theoj.org/papers/73e486788290a6386e90a21c7e71bbe0)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/baccuslab/pyret" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/baccuslab/pyret">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.5.0)?
- [x] **Authorship:** Has the submitting author (@nirum) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arokem** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arokem** [comment]
@whedon assign @kdesimone as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kdesimone

**Comment by kdesimone** [comment]
The authors have satisfactorily addressed (and closed) all the issues, which I've linked below.

https://github.com/baccuslab/pyret/issues/88
https://github.com/baccuslab/pyret/issues/86
https://github.com/baccuslab/pyret/issues/85
https://github.com/baccuslab/pyret/issues/83

**Comment by arokem** [comment]
@arfon: what's the next step here? 

IIUC, @nirum and colleagues need to create a DOI for the package that incorporates the fixes from the review. Is that correct?

**Comment by arfon** [comment]
> IIUC, @nirum and colleagues need to create a DOI for the package that incorporates the fixes from the review. Is that correct?

Yes, that's correct. @nirum - please create the archive and update this thread with the DOI so we can accept this submission.

**Comment by nirum** [comment]
Thanks @kdesimone and @arokem!

I've uploaded the package using zenodo, here is the DOI:
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.232521.svg)](https://doi.org/10.5281/zenodo.232521)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.232521 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.232521" target="_blank">10.5281/zenodo.232521</a> is the archive.

**Comment by arfon** [comment]
@arokem thanks for editing this one and for your review @kdesimone :zap:

@nirum - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00137 ⚡️ 🚀 💥
