### ISSUE TITLE
[REVIEW]: AMReX: a framework for block-structured adaptive mesh refinement

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1370]
**Submitting author:** @asalmgren (<a href="http://orcid.org/0000-0003-2103-312X">Ann Almgren</a>)
**Repository:** <a href="https://github.com/AMReX-Codes/amrex" target ="_blank">https://github.com/AMReX-Codes/amrex</a>
**Version:** current master branch on github
**Editor:** @kyleniemeyer
**Reviewer:** @MatthewTurk, @RemiLehe , @cmsquared
**Archive:** <a href="https://doi.org/10.5281/zenodo.2754709" target="_blank">10.5281/zenodo.2754709</a>

## Status

[![status](http://joss.theoj.org/papers/8549074fbc29175a9823c1aca2f26d24/status.svg)](http://joss.theoj.org/papers/8549074fbc29175a9823c1aca2f26d24)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/8549074fbc29175a9823c1aca2f26d24"><img src="http://joss.theoj.org/papers/8549074fbc29175a9823c1aca2f26d24/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/8549074fbc29175a9823c1aca2f26d24/status.svg)](http://joss.theoj.org/papers/8549074fbc29175a9823c1aca2f26d24)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/AMReX-Codes/amrex" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@MatthewTurk & @RemiLehe  & @cmsquared, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @kyleniemeyer know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/AMReX-Codes/amrex">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (current master branch on github)?
- [x] **Authorship:** Has the submitting author (@asalmgren) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/AMReX-Codes/amrex">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (current master branch on github)?
- [x] **Authorship:** Has the submitting author (@asalmgren) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/AMReX-Codes/amrex">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (current master branch on github)?
- [x] **Authorship:** Has the submitting author (@asalmgren) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @MatthewTurk, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kyleniemeyer** [comment]
👋 @asalmgren @MatthewTurk @RemiLehe  @cmsquared 

The actual review will take place in this issue; you can find the individual reviewer checklists above. Thanks!

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01370/joss.01370/10.21105.joss.01370.pdf)

**Comment by asalmgren** [comment]
Looks good.

**Comment by cmsquared** [comment]
Just to disclose a possible perceived COI:  In the last 4 years, I have been on published papers or meeting abstracts with Zhang, Almgren, Beckner, Bell, Friesen, Katz, Nonaka, and Zingale from the author list.  Most of this was for work we had done together either on astrophysics or utilizing/writing tools that were based on the predecessor of AMReX: BoxLib.  I do not feel this is an *actual* COI given that I have not worked on AMReX, nor any of the updated modifications to codes that once used BoxLib and now use AMReX.

**Comment by cmsquared** [comment]
The team has addressed the points outlined in the Issue raised above via a series of commits.  I am happy to recommend this article for publication.

**Comment by kyleniemeyer** [comment]
Thanks @cmsquared!

@RemiLehe @MatthewTurk just wanted to check in on the status of your reviews

**Comment by RemiLehe** [comment]
Thanks for the reminder! I'll try to send my review comments today.

**Comment by RemiLehe** [comment]
I have completed the review ; here are a few comments regarding the checklist itself:

- Regarding possible perceived COI: As mentioned off-line to @kyleniemeyer, I am currently working and collaborating with the AMReX team for the [WarpX project](https://github.com/ECP-WarpX/WarpX.git). I am not developing the AMReX source code, though.

- Regarding the license: AMReX uses a modified 3-clause BSD license, which has been adapted for UC Berkeley/LBNL. (Open-source software from LBNL usually use this license.) Strictly speaking, it is not in the [OSI approved list](https://opensource.org/licenses/alphabetical). (or I missed it)

**Comment by MatthewTurk** [comment]
Hi @kyleniemeyer, working on mine now.  Apologies, hope to have it done within 24 hours.

**Comment by MatthewTurk** [comment]
I have completed my review, and here are my comments:

 * `LICENSE` is not in the repository, but it is in the `README.md` file and a `license.txt` file, which seems fine to me.
 * I did have to dig around for the tests, but not to the point that I felt even raising an issue was warranted on the original repository.

I recommend this paper be accepted.

**Comment by RemiLehe** [comment]
The reviewers have addressed my comment (in the issues of the AMReX repository).
I also recommend that the paper be accepted.

**Comment by kyleniemeyer** [comment]
Thanks for your reviews @MatthewTurk @RemiLehe @cmsquared !

@asalmgren it looks like the only remaining issue is the license. JOSS requires that software submissions use standard OSI-approved licenses, and it looks like your submission is using a modified version of the BSD 3-clause license. 

The editorial board is in agreement that AMReX needs to adopt an (unmodified, standard) OSI-approved license for JOSS to accept it. If possible, this could be as simple as moving to the standard BSD 3-clause license. However, if you need the indemnification protections in your modified license, there is an OSI-approved NASA license that includes such language. 

Bruce Wilson (@usethedata) has dealt with some of these issues at ORNL and has volunteered to chat about this if needed. Also, @jedbrown pointed out that AMReX is part of the xSDK collaboration, which states:
> The xSDK collaboration has a strong preference for packages to use an OSI-approved, permissive open-source license (e.g., MIT or BSD 3-Clause). All new packages will be required to use such a license.

**Comment by asalmgren** [comment]
Kyle et al --

We understand and are trying to figure out how we can meet the
requirement.   Is there a way to find out if there are codes currently
published in JOSS that have been released from LBNL?

Thanks

**Comment by jedbrown** [comment]
Note that SuperLU_DIST, for example, is standard 3-clause BSD. https://github.com/xiaoyeli/superlu_dist/blob/master/License.txt
JOSS #830 has a normal 3-clause BSD license.

**Comment by asalmgren** [comment]
We have replaced the license.txt with the modified BSD license by LICENSE
containing the standard 3-clause BSD license.

For the record however - I think that both JOSS and xSKD should re-consider
their policy regarding the modified license -- if you read the text you
will notice that it is in fact more "permissive" and in the spirit of open
source than the standard 3-clause license, and as such should be
acceptable, both in spirit and in reality.

**Comment by jedbrown** [comment]
@asalmgren Although the intent may be to ensure [inbound=outbound](http://ebb.org/bkuhn/blog/2011/07/07/harmony-harmful.html) (see "Inbound=Outbound Is All You Need"), it applies to those who may make modifications in a fork (not just contributors to upstream) or as a component of a different project, and thus may require one-off legal consult for potential users as well as possible conflict with more restrictive licenses such as GPL. IMO, clarity regarding inbound=outbound (e.g., Developer's Certification of Origin) belongs in contributing documentation and not in a license. I'm not aware of any OSI approved licenses with such terms.

**Comment by arfon** [comment]
> We have replaced the license.txt with the modified BSD license by LICENSE
> containing the standard 3-clause BSD license.

Many thanks @asalmgren.

> For the record however - I think that both JOSS and xSKD should re-consider
> their policy regarding the modified license -- if you read the text you
> will notice that it is in fact more "permissive" and in the spirit of open
> source than the standard 3-clause license, and as such should be
> acceptable, both in spirit and in reality.

The challenge here is that with the modification, without consulting a lawyer, we don't know _what_ this license is. Any modification to an existing license is effectively a new license, hence defeating the purpose of having a shared set of common licenses where the terms are understood from a legal perspective.

If you and your colleagues strongly believe in this modified license, then I'd encourage you to petition the Open Source Initiative with this modified license. If a project uses a license in [this list](https://opensource.org/licenses/alphabetical) then JOSS can accept a submission.

**Comment by asalmgren** [comment]
Arfon et al,

Thank you for the discussion.     We'll look into petitioning OSI to accept
this modification.

In the meantime, however, I'm glad that the new AMReX license (standard
3-clause BSD) is acceptable.

Thanks,
Ann

**Comment by kyleniemeyer** [comment]
Thanks @asalmgren!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01370/joss.01370/10.21105.joss.01370.pdf)

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1088/1742-6596/1031/1/012024 is OK
- 10.1137/15M102616X is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @asalmgren, the software aspect of the review is done, but I just have a few comments on the paper before we wrap things up:
- This is minor, but could you add more detail to the author affiliations, matching what you'd typically see in an article? (E.g., city, country)
- Would it be appropriate to add a few references in the first paragraph pointing interested readers to general work on AMR? And potentially later in the introduction to other techniques that are mentioned?
- Similarly, the mentions of SUNDIALS, PETSc, and hypre might be appropriate places for references.
- I just submitted a PR with some typographic edits: AMReX-Codes/amrex#478

Once you've made these changes, please archive your submission's source files and provide back the DOI (using Zenodo, for example).

**Comment by asalmgren** [comment]
@kyleniemeyer --

We have

1) added detail to the affiliations
2) added references re AMR
3) added references for SUNDIALS, PETSc, hypre, Conduit, SENSEI, Visit, yt,
Paraview
4) merged your PR

The current version is http://doi.org/10.5281/zenodo.2754709
The DOI of all versions is https://doi.org/10.5281/zenodo.2555438

Thanks,

Ann

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01370/joss.01370/10.21105.joss.01370.pdf)

**Comment by kyleniemeyer** [comment]
Hi @asalmgren, looks good! I just made some minor fixes in two PRs; apologies for my pickiness on this.

**Comment by asalmgren** [comment]
Corrections merged and much appreciated!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01370/joss.01370/10.21105.joss.01370.pdf)

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1088/1742-6596/1031/1/012024 is OK
- 10.1016/0021-9991(84)90073-1 is OK
- 10.1016/0021-9991(89)90035-1 is OK
- 10.1137/0915008 is OK
- 10.1137/0915008 is OK
- 10.1080/00102209808915770 is OK
- 10.1088/1364-7830/4/4/309 is OK
- 10.1137/15M102616X is OK
- 10.1145/1089014.1089020 is OK
- 10.1088/0067-0049/192/1/9 is OK
- 10.1137/1.9780898719505 is OK

MISSING DOIs

- https://doi.org/10.1016/b978-012387582-2/50038-1 may be missing for title: ParaView: An End-User Tool for Large Data Visualization

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@asalmgren sorry, one last missing DOI that I missed, and then I will accept & publish the paper

**Comment by WeiqunZhang** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1088/1742-6596/1031/1/012024 is OK
- 10.1016/0021-9991(84)90073-1 is OK
- 10.1016/0021-9991(89)90035-1 is OK
- 10.1137/0915008 is OK
- 10.1137/0915008 is OK
- 10.1080/00102209808915770 is OK
- 10.1088/1364-7830/4/4/309 is OK
- 10.1137/15M102616X is OK
- 10.1145/1089014.1089020 is OK
- 10.1016/B978-012387582-2/50038-1 is OK
- 10.1088/0067-0049/192/1/9 is OK
- 10.1137/1.9780898719505 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by WeiqunZhang** [comment]
One of the references has a valid but incorrect DOI.  I will fix it.

**Comment by WeiqunZhang** [comment]
DOI `10.1137/0915008` appeared in two different references.  This has been fixed in AMReX repo.  I have also manually clicked and checked the DOI links in generated pdf file.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01370/joss.01370/10.21105.joss.01370.pdf)

**Comment by kyleniemeyer** [comment]
Thanks @WeiqunZhang and @asalmgren! Looks good to move forward now.

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.2754709 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2754709" target="_blank">10.5281/zenodo.2754709</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1088/1742-6596/1031/1/012024 is OK
- 10.1016/0021-9991(84)90073-1 is OK
- 10.1016/0021-9991(89)90035-1 is OK
- 10.1137/0915008 is OK
- 10.1006/jcph.1998.5890 is OK
- 10.1080/00102209808915770 is OK
- 10.1088/1364-7830/4/4/309 is OK
- 10.1137/15M102616X is OK
- 10.1145/1089014.1089020 is OK
- 10.1016/B978-012387582-2/50038-1 is OK
- 10.1088/0067-0049/192/1/9 is OK
- 10.1137/1.9780898719505 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/685

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/685, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/686
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01370](https://doi.org/10.21105/joss.01370)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Hey @arfon, looks like the paper PDF isn't showing up at http://joss.theoj.org/papers/10.21105/joss.01370 even though the PDF was generated fine at https://github.com/openjournals/joss-papers/blob/49965f4a1df4246a547c458c1f29feada6b6aa8e/joss.01370/10.21105.joss.01370.pdf 

Any ideas? Just wait a bit longer?

**Comment by arfon** [comment]
> Any ideas? Just wait a bit longer?

Sometimes GitHub pages can take a couple of minutes to build. I can see the paper fine now at https://doi.org/10.21105/joss.01370 👍 

<img width="1081" alt="Screen Shot 2019-05-12 at 4 54 52 PM" src="https://user-images.githubusercontent.com/4483/57587680-c648e480-74d6-11e9-9a45-b24ed86be7d4.png">

**Comment by kyleniemeyer** [comment]
Works for me too now, thanks!

Congrats @asalmgren et al. on your paper being published in JOSS! Thanks to @MatthewTurk, @RemiLehe , and @cmsquared for reviewing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01370/status.svg)](https://doi.org/10.21105/joss.01370)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01370">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01370/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01370/status.svg
   :target: https://doi.org/10.21105/joss.01370
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01370/status.svg)](https://doi.org/10.21105/joss.01370)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
