### ISSUE TITLE
[PRE REVIEW]: xml2jupyter: Mapping parameters between XML and Jupyter widgets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1372]
**Submitting author:** @rheiland (<a href="http://orcid.org/0000-0002-7440-2905">Randy Heiland</a>)
**Repository:** <a href="https://github.com/rheiland/xml2jupyter" target ="_blank">https://github.com/rheiland/xml2jupyter</a>
**Version:** v1.0.0
**Editor:** @lheagy
**Reviewers:** @choldgraf

**Author instructions**

Thanks for submitting your paper to JOSS @rheiland. **Currently, there isn't an JOSS editor assigned** to your paper.

@rheiland if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01372/joss.01372/10.21105.joss.01372.pdf)

**Comment by labarba** [comment]
@lheagy — the author suggested you as editor, and this indeed looks in your interest sphere. I will assign you now, but let me know if you're disinclined for any reason ...

**Comment by labarba** [comment]
@whedon assign @lheagy as editor

**Comment by whedon** [comment]
OK, the editor is @lheagy

**Comment by rheiland** [comment]
> [ 👉 Check article proof 📄 👈 ](https://github.com/openjournals/joss-papers/blob/joss.01372/joss.01372/10.21105.joss.01372.pdf)

As a first-time JOSS submitter, I'm not exactly sure how this review thread works, but if I'm supposed to reply to this "check article proof", I would just say that it looks acceptable to me. It's just slightly strange with a line break on a quoted <user_parameters> (p. 2).

**Comment by rheiland** [comment]
Regarding suggestions for possible reviewers, I'd probably prefer to use your list of potential reviewers. When I visit that list and look for relevant subject interests, I would probably suggest 
@Chilipp, @dangunter, @louietaylor, @pgadige, @vsoch, or @wtgee , to name a few (not sure why some of these names seem not to be valid github usernames).

**Comment by MathCancer** [comment]
Thanks, everyone. Michael Hucka (https://github.com/mhucka), Herbert Sauro (https://github.com/hsauro), and Jacob Scott (https://github.com/cancerconnector) might also be appropriate reviewers, given their work in mathematical biology and interfacing computational models.

**Comment by lheagy** [comment]
Happy to @labarba!

**Comment by rheiland** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by rheiland** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01372/joss.01372/10.21105.joss.01372.pdf)

**Comment by rheiland** [comment]
Looks good - just made a minimal change: "shown below" -> "shown in Figure 3" (because the figure wasn't *below*).

**Comment by lheagy** [comment]
:wave: Hi @mhucka, would you be willing to review this submission for the Journal of Open Source Software (JOSS)? 

JOSS is a free, open-source, community driven and developer-friendly online journal. The review process is open, and conversation between the authors, reviewers and editors are encouraged. JOSS reviews involve downloading and installing the software, and inspecting the repository
and submitted paper for key elements. See https://joss.readthedocs.io/en/latest/review_criteria.html

Editors and reviewers post comments on the Review issue, and authors respond to the comments
and improve their submission until acceptance (or withdrawal, if they feel unable to
satisfy the review).

If you are unable to review at this time, any suggestions you have for alternate reviewers would be appreciated. 

Thanks for your consideration!

**Comment by choldgraf** [comment]
Hey all - I'd be happy to give this one a review if it's still needed.

**Comment by lheagy** [comment]
@whedon assign @choldgraf as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @choldgraf

**Comment by lheagy** [comment]
:wave: Hi @fbergmann, would you be willing to review this submission for the Journal of Open Source Software (JOSS)?

JOSS is a free, open-source, community driven and developer-friendly online journal. The review process is open, and conversation between the authors, reviewers and editors are encouraged. JOSS reviews involve downloading and installing the software, and inspecting the repository
and submitted paper for key elements. See https://joss.readthedocs.io/en/latest/review_criteria.html

Editors and reviewers post comments on the Review issue, and authors respond to the comments
and improve their submission until acceptance (or withdrawal, if they feel unable to
satisfy the review).

If you are unable to review at this time, any suggestions you have for alternate reviewers would be appreciated.

Thanks for your consideration!

**Comment by lheagy** [comment]
👋 Hi @dangunter, would you be willing to review this submission for JOSS?

**Comment by lheagy** [comment]
I am still on the look-out for another reviewer, but I will start the review so that @choldgraf can get started in the mean-time

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1408. Feel free to close this issue now!
