### ISSUE TITLE
[PRE REVIEW]: WatchMe: Software for Reproducible Monitoring and Data Collection

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1373]
**Submitting author:** @vsoch (<a href="http://orcid.org/0000-0002-4387-3819">Vanessa Sochat</a>)
**Repository:** <a href="https://www.github.com/vsoch/watchme" target ="_blank">https://www.github.com/vsoch/watchme</a>
**Version:** 0.0.13
**Editor:** @brainstorm
**Reviewers:** @andreysmelter and @crew102

**Author instructions**

Thanks for submitting your paper to JOSS @vsoch. **Currently, there isn't an JOSS editor assigned** to your paper.

@vsoch if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01373/joss.01373/10.21105.joss.01373.pdf)

**Comment by labarba** [comment]
👋  @brainstorm — The author suggested you as handling editor, and it looks like this work is in your sphere of interests. I'll assign you now, but let me know if you're disinclined for any reason.

**Comment by labarba** [comment]
@whedon assign @brainstorm as editor

**Comment by whedon** [comment]
OK, the editor is @brainstorm

**Comment by vsoch** [comment]
Thanks @whedon, @labarba, and @brainstorm! 

Suggestions for reviewers: @petar, @mdmurbach, @andreysmelter, @crew102

**Comment by brainstorm** [comment]
Yeah, @labarba, happy to edit, @vsoch's software is usually delicious :)

**Comment by andreysmelter** [comment]
> Thanks @whedon, @labarba, and @brainstorm!
> 
> Suggestions for reviewers: @petar, @mdmurbach, @andreysmelter, @crew102

Hi all, I will be happy to review @vsoch software paper!

**Comment by crew102** [comment]
I’m down for a review as well

**Comment by brainstorm** [comment]
Sweet, let's have you two onboard then.

**Comment by brainstorm** [comment]
@whedon assign @crew102 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @crew102

**Comment by brainstorm** [comment]
@whedon assign @andreysmelter as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @andreysmelter

**Comment by brainstorm** [comment]
@whedon assign @andreysmelter and @crew102 as reviewers

**Comment by whedon** [comment]
OK, the reviewer is @andreysmelter and @crew102

**Comment by brainstorm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1388. Feel free to close this issue now!

**Comment by vsoch** [comment]
Thanks @brainstorm @whedon ! Looking forward to it.

**Comment by arfon** [comment]
> @whedon assign @andreysmelter and @crew102 as reviewers

@brainstorm Whedon didn't do quite what you expected here, we need to assign one at a time. I'll go ahead and fix up the review issue...

**Comment by vsoch** [comment]
Thanks @arfon, I'll keep an eye out for this in the future too. :)
