### ISSUE TITLE
[PRE REVIEW]: labjack-controller: Fast Realtime Data Collection with Labjack T-Series DAQs in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1376]
**Submitting author:** @nyctanthous (<a href="http://orcid.org/0000-0002-1240-5385">Benjamin Montgomery</a>)
**Repository:** <a href="https://github.com/university-of-southern-maine-physics/labjack-controller" target ="_blank">https://github.com/university-of-southern-maine-physics/labjack-controller</a>
**Version:** 0.3
**Editor:** @usethedata
**Reviewers:** @lucask07, @ixjlyons

**Author instructions**

Thanks for submitting your paper to JOSS @nyctanthous. **Currently, there isn't an JOSS editor assigned** to your paper.

@nyctanthous if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1376 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1376/paper.md): found a tab character that violate intendation while scanning a plain scalar at line 10 column 11 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@Nyctanthous — have a look at the tabs on the metadata section of your paper. Looks like some weird characters are messing up the paper compilations.

**Comment by labarba** [comment]
Also, after a quick look at your paper, I'd say it doesn't quite meet [our expectations](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). In particular, see if you can address these better:
- A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience
- A clear statement of need that illustrates the purpose of the software for research (this should include mention of other software that may address the same need, in a different way, for example)

**Comment by labarba** [comment]
@usethedata — from the looks of it, you could help us with this submission. Have a look ... I'm going to assign you now, but do let me know if you are disinclined for any reason. Thanks!

**Comment by labarba** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by Nyctanthous** [comment]
@labarba Thanks for the heads-up, I'll have the paper revised in the next 24 hours.

**Comment by Nyctanthous** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1376 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1376/paper.md): mapping values are not allowed in this context at line 11 column 14 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Nyctanthous** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1376 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Nyctanthous** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1376 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    138      0 --:--:-- --:--:-- --:--:--   136
100    13    0    13    0     0    136      0 --:--:-- --:--:-- --:--:--   135
Error reading bibliography ./paper.bib (line 13, column 1):
unexpected "@"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by Nyctanthous** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01376/joss.01376/10.21105.joss.01376.pdf)

**Comment by Nyctanthous** [comment]
Fourth time's the charm, apparently. Everything should be in a fully reviewable state.

**Comment by usethedata** [comment]
@Nyctanthous In your document, I see "n.d." Is that for "no DOI"?  Sorry to be slow in responding -- some challenges in the day job.

**Comment by Nyctanthous** [comment]
@usethedata No problem. I expect n.d. indicates "no date" recorded for authorship; I'm using the `misc` entry in the bibliography because, at this time, all references are websites.

I am not aware of any papers on the libraries that are similar/related to this one. ([minimal-modbus][0], [nidaqmx-python][1], [openDAQ][2], [Lawson Lab's 301/302 library][3], as some popular examples). If are any, however, it would be great to add them.

[0]: https://minimalmodbus.readthedocs.io/en/master/
[1]: https://nidaqmx-python.readthedocs.io/en/latest/
[2]: https://github.com/openDAQ/python-opendaq
[3]: http://www.lawsonlabs.com/specExternal301_Developer.html

**Comment by labarba** [comment]
@usethedata 👋  — Looks like this submission is waiting for you to assign reviewers. 

@Nyctanthous — You can help us by seeing if you can suggest any reviewers form the JOSS list. Follow the link above, https://github.com/openjournals/joss-reviews/issues/1376#issuecomment-482981062

**Comment by Nyctanthous** [comment]
It looks like @ixjlyons would be a good fit, given their preference for data acquisition and assorted electronic systems experience.
@lucask07 also looks like they should have a significant experience in this field, as this library is all about interacting with instruments, usually sensors, and experimental data acquisition.

**Comment by labarba** [comment]
@ixjlyons, @lucask07 👋 — would either (or both) of you be willing to contribute a review for this JOSS submission? Title: "labjack-controller: Fast Realtime Data Collection with Labjack T-Series DAQs in Python" ... Let us know!

**Comment by lucask07** [comment]
Hi @labarba 
Sure, I have a labjack and so this is definitely a good fit.

**Comment by labarba** [comment]
@whedon assign @lucask07 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @lucask07

**Comment by labarba** [comment]
We'll try to get a second reviewer and then start the review. Thanks, @lucask07 !

**Comment by ixjlyons** [comment]
I don't have a LabJack device, but I have experience with data acquisition so I could do some code review and the usual checklist items (and I'm willing to do the review if that's sufficient). Alternatively, I know @moorepants is on the reviewer list and has LabJack hardware, though I don't know if he has one of the T series devices or bandwidth to do a review.

**Comment by labarba** [comment]
Thank you, @ixjlyons! Since we have one other reviewer, your code review as described is sufficient. I'll add you and start the review now.

**Comment by labarba** [comment]
@whedon add @ixjlyons as reviewer

**Comment by whedon** [comment]
OK, @ixjlyons is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1448. Feel free to close this issue now!
