### ISSUE TITLE
[PRE REVIEW]: Fruitbat: A Python Package for Estimating Redshifts of Fast Radio Bursts

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1377]
**Submitting author:** @abatten (<a href="http://orcid.org/0000-0001-7599-6488">Adam Batten</a>)
**Repository:** <a href="https://github.com/abatten/fruitbat" target ="_blank">https://github.com/abatten/fruitbat</a>
**Version:** v1.0.0
**Editor:** @xuanxu
**Reviewers:** @zingale

**Author instructions**

Thanks for submitting your paper to JOSS @abatten. **Currently, there isn't an JOSS editor assigned** to your paper.

@abatten if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1377 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:91:in `block in check_orcids': Problem with ORCID (0000-0001-7559-6488) for Adam J. Batten (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@abatten 👋 — could there be a typo in your ORCID?

**Comment by labarba** [comment]
@xuanxu — The submitting author suggested you as handling editor, and it does look like your cup of tea. I'll assign you now, but let me know if you're disinclined for any reason.

**Comment by labarba** [comment]
@whedon assign @xuanxu as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by abatten** [comment]
The ORCID number seems to be correct. It might have failed because my ORCID account didn't have my middle initial. I've changed it now so hopefully it works.

**Comment by abatten** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1377 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:91:in `block in check_orcids': Problem with ORCID (0000-0001-7559-6488) for Adam J. Batten (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by abatten** [comment]
Hmmm. Actually I did miss a number. Trying again.

@whedon generate pdf

**Comment by abatten** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by xuanxu** [comment]
> @xuanxu — The submitting author suggested you as handling editor, and it does look like your cup of tea. I'll assign you now, but let me know if you're disinclined for any reason.

👍

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
I'm not sure why Whedon is struggling here. I've compiled the PDF locally: [10.21105.joss.01377.pdf](https://github.com/openjournals/joss-reviews/files/3081403/10.21105.joss.01377.pdf)

**Comment by abatten** [comment]
Thanks @arfon. Looks like parts of the document didn't render as I'd expect them to. e.g missing citations, listing dot points and figure captions. I'll fix those up.

**Comment by abatten** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
I'm wondering if Whedon is struggling because of the size of the logo: https://github.com/abatten/fruitbat/blob/master/logo/fruitbat_logo.png

**Comment by abatten** [comment]
It could be. The logo isn't super important to the paper, just thought it would be nice. I'll remove it and see.

**Comment by arfon** [comment]
Anyway, here's an update proof: [10.21105.joss.01377.pdf](https://github.com/openjournals/joss-reviews/files/3087480/10.21105.joss.01377.pdf)

**Comment by arfon** [comment]
> It could be. The logo isn't super important to the paper, just thought it would be nice. I'll remove it and see.

Or just resize it? If you want to try out the change, you can push a modification to a branch and then ask Whedon to compile the paper from that branch for testing (e.g. `@whedon generate pdf from branch testing`)

**Comment by abatten** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by abatten** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by abatten** [comment]
It still seems to be struggling even without the logo. It could be the other figure, but it isn't that big. I'm not sure what the issue is.

**Comment by abatten** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by abatten** [comment]
@arfon Any more ideas why it's failing?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
It looks like the very long author lists on the Planck papers is blowing up the memory usage on the Heroku PDF worker:

```
2019-04-18T11:20:05.697913+00:00 heroku[router]: at=info method=POST path="/dispatch" host=whedon.herokuapp.com request_id=c5739468-eeda-43e3-bf27-38b7cab4f6dc fwd="140.82.115.12" dyno=web.1 connect=0ms service=2747ms status=200 bytes=253 protocol=https
2019-04-18T11:20:05.711888+00:00 app[worker.1]: 4 TID-1bkjao PDFWorker JID-21ab8dd21ac0cd55cb66681a INFO: start
2019-04-18T11:20:07.406918+00:00 heroku[router]: at=info method=POST path="/dispatch" host=whedon.herokuapp.com request_id=e499a364-b79b-4670-89e4-cc8f7d9e07e2 fwd="140.82.115.5" dyno=web.1 connect=0ms service=2002ms status=200 bytes=228 protocol=https
2019-04-18T11:20:48.119861+00:00 heroku[worker.1]: Process running mem=737M(142.2%)
2019-04-18T11:20:48.121062+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2019-04-18T11:21:06.931745+00:00 heroku[worker.1]: Process running mem=728M(142.2%)
2019-04-18T11:21:06.931745+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2019-04-18T11:21:28.033900+00:00 heroku[worker.1]: Process running mem=728M(142.2%)
2019-04-18T11:21:28.033981+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2019-04-18T11:21:46.996705+00:00 heroku[worker.1]: Process running mem=853M(166.6%)
2019-04-18T11:21:46.996784+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2019-04-18T11:22:07.247549+00:00 heroku[worker.1]: Process running mem=861M(168.2%)
2019-04-18T11:22:07.247659+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2019-04-18T11:22:27.579594+00:00 heroku[worker.1]: Process running mem=1020M(199.3%)
2019-04-18T11:22:27.579731+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2019-04-18T11:22:47.066625+00:00 heroku[worker.1]: Process running mem=1020M(199.3%)
2019-04-18T11:22:47.066721+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2019-04-18T11:23:06.512981+00:00 heroku[worker.1]: Process running mem=1021M(199.3%)
2019-04-18T11:23:06.513116+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2019-04-18T11:23:26.883818+00:00 heroku[worker.1]: Process running mem=1020M(199.3%)
2019-04-18T11:23:26.883865+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2019-04-18T11:23:46.561362+00:00 heroku[worker.1]: Process running mem=1020M(199.3%)
2019-04-18T11:23:46.561420+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2019-04-18T11:24:06.626757+00:00 heroku[worker.1]: Process running mem=1020M(199.3%)
2019-04-18T11:24:06.626922+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2019-04-18T11:24:27.698419+00:00 heroku[worker.1]: Process running mem=1020M(199.3%)
2019-04-18T11:24:27.698526+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2019-04-18T11:24:47.311199+00:00 heroku[worker.1]: Process running mem=1279M(249.9%)
```

I'm not sure there's much we can do to easily fix this unless you can truncate that author list (they won't all render in the paper anyway)?

**Comment by abatten** [comment]
Well that should be an easy fix!

**Comment by abatten** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01377/joss.01377/10.21105.joss.01377.pdf)

**Comment by abatten** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by abatten** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01377/joss.01377/10.21105.joss.01377.pdf)

**Comment by arfon** [comment]
That's looking better. Feel free to add back in the logo now as I don't think this was the source of the problem.

**Comment by abatten** [comment]
Actually it was also an issue. I tried with the logo and it couldn't generate the PDF for 14 minutes, so I have re-scaled the image to see if that now works.

**Comment by abatten** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01377/joss.01377/10.21105.joss.01377.pdf)

**Comment by abatten** [comment]
Alright! Looking good, I'll merge to paper development branch into master.

**Comment by abatten** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01377/joss.01377/10.21105.joss.01377.pdf)

**Comment by xuanxu** [comment]
:wave: @zingale: Would you be willing to review this paper? I think your expertise in Python and Astrophysics makes you a great fit for this submission.

**Comment by zingale** [comment]
yes, I can review this.

**Comment by xuanxu** [comment]
@zingale Great, thanks! I'll assign you and start the review issue now

**Comment by xuanxu** [comment]
@whedon assign @zingale as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @zingale

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1399. Feel free to close this issue now!

**Comment by xuanxu** [comment]
@zingale, please head over to #1399 for the actual review
