### ISSUE TITLE
[PRE REVIEW]: View eXtract aNnotate (ViXeN) media files: a multimedia project manager

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1378]
**Submitting author:** @prabhuramachandran (<a href="http://orcid.org/0000-0001-6337-1720">Prabhu Ramachandran</a>)
**Repository:** <a href="https://github.com/vixen-project/vixen" target ="_blank">https://github.com/vixen-project/vixen</a>
**Version:** 1.0rc2
**Editor:** @xuanxu
**Reviewers:** @deniederhut, @amoeba

**Author instructions**

Thanks for submitting your paper to JOSS @prabhuramachandran. **Currently, there isn't an JOSS editor assigned** to your paper.

@prabhuramachandran if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1378 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1378/paper/paper.md): found a tab character that violate intendation while scanning a plain scalar at line 13 column 11 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
👋 @prabhuramachandran — have a look at the tabs on the metadata section of your paper. Looks like some weird characters are messing up the paper compilation.

**Comment by labarba** [comment]
@jasonclark — this submission looks to be in your areas of expertise and interest. I'm hoping you can handle it. I'll assign you now, but do let me know if you're disinclined for any reason.

**Comment by labarba** [comment]
@whedon assign @jasonclark as editor

**Comment by whedon** [comment]
OK, the editor is @jasonclark

**Comment by prabhuramachandran** [comment]
@labarba -- thanks for the heads up, I've fixed the tabs in the `paper.md`.
@whedon generate pdf

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01378/joss.01378/10.21105.joss.01378.pdf)

**Comment by labarba** [comment]
@jasonclark — Looks like this submission is waiting for you to assign reviewers.

@prabhuramachandran — You can help us by seeing if you can find some names to suggest from the JOSS list; see the link above, https://github.com/openjournals/joss-reviews/issues/1378#issuecomment-482989183

**Comment by kadambarid** [comment]
Thank you for your patience. 
We would like to suggest @ethanwhite and @deniederhut from the reviewer list.

**Comment by ethanwhite** [comment]
Cool idea - unfortunately I'm not available to review in the near future.

**Comment by deniederhut** [comment]
I'm down. What's the turnaround time?

**Comment by kyleniemeyer** [comment]
@deniederhut great! We don't have a specific deadline for reviews, but generally we like to get reviews within two or three weeks—but longer can be ok.

**Comment by kyleniemeyer** [comment]
@whedon assign @deniederhut as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @deniederhut

**Comment by deniederhut** [comment]
Okay, good to know. We're in the middle of the review period for SciPy, so it be a few weeks before I can take a look.

**Comment by arfon** [comment]
@whedon assign @xuanxu as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by arfon** [comment]
Just a heads up @prabhuramachandran - @xuanxu is going to be taking over as the editor of this submission. He'll start the review once he's found a second reviewer for the submission.

**Comment by prabhuramachandran** [comment]
@arfon -- thank you for the heads up!  Perhaps one of @amoeba or @jsta could be a possible second reviewer?

**Comment by amoeba** [comment]
Hey @prabhuramachandran, I'm available and willing.

**Comment by arfon** [comment]
@whedon add @amoeba as reviewer

**Comment by whedon** [comment]
OK, @amoeba is now a reviewer

**Comment by arfon** [comment]
> Hey @prabhuramachandran, I'm available and willing.

⚡️ thanks @amoeba! @xuanxu - as this submission has been waiting for some time, I'm going to move this forward to review and hopefully you can pick it up from there?

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1501. Feel free to close this issue now!

**Comment by arfon** [comment]
@deniederhut, @amoeba - please head over to #1501 where the review will take place.
