### ISSUE TITLE
[PRE REVIEW]: Lexicon-Mono-Seq, DOM Text Based Async MSA Viewer

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1379]
**Submitting author:** @IbrahimTanyalcin (<a href="http://orcid.org/0000-0003-0327-5096">Ibrahim  Tanyalcin</a>)
**Repository:** <a href="https://github.com/IbrahimTanyalcin/lexicon-mono-seq" target ="_blank">https://github.com/IbrahimTanyalcin/lexicon-mono-seq</a>
**Version:** v0.15.12
**Editor:** @csoneson
**Reviewers:** @hrhotz, @jkanche, @imallona

**Author instructions**

Thanks for submitting your paper to JOSS @IbrahimTanyalcin. **Currently, there isn't an JOSS editor assigned** to your paper.

@IbrahimTanyalcin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1379 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1379 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1379 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1379 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@IbrahimTanyalcin —You've given us a link to your project webpage, not the repository: it should be https://github.com/IbrahimTanyalcin/lexicon-mono-seq
Let's see if I can change that manually.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01379/joss.01379/10.21105.joss.01379.pdf)

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by labarba** [comment]
@IbrahimTanyalcin — Before we can start with assigning an editor and reviewers, you'll have to do a bit more work on the paper to meet [our expectations](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). Right now the article itself is very brief and doesn't contain much substance; while we don't expect a full article here, it should be 250–1000 words and should include:

- A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience
- A clear statement of need that illustrates the purpose of the software, and comments on other extant software with similar function

Your article should be improved with a brief description of how the software works, and some examples use cases.

**Comment by IbrahimTanyalcin** [comment]
@labarba , I'll beef up the paper.md a bit, the examples are embedded inside the readme, I've got 6 already, 2 more on the way. I'll let you know when I'm done, probably in a few hours.

**Comment by IbrahimTanyalcin** [comment]
@labarba, Could you take a quick glance at the paper.md, does it fit better? https://github.com/IbrahimTanyalcin/lexicon-mono-seq/blob/master/paper/paper.md

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01379/joss.01379/10.21105.joss.01379.pdf)

**Comment by arfon** [comment]
@IbrahimTanyalcin - this looks pretty good. It looks like you've not cited any of the entries in your `paper.bib` file which means they're not being compiled into the PDF proof. Could you make sure cite these? You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)

**Comment by arfon** [comment]
:wave: @csoneson - would you be willing to edit this submission for JOSS?

**Comment by IbrahimTanyalcin** [comment]
@arfon ,I'll fix the citations. I've added 2 more examples meanwhile.

**Comment by IbrahimTanyalcin** [comment]
@arfon, I've added the refs, though I'm not sure if it'll compile properly.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01379/joss.01379/10.21105.joss.01379.pdf)

**Comment by IbrahimTanyalcin** [comment]
Hmmm strange, any leads why the 4 other references does not appear on the references?

**Comment by arfon** [comment]
I could 6 citations in the `paper.md`, 6 references in `paper.bib` and 6 rendered references in the output PDF. That seems correct?

**Comment by IbrahimTanyalcin** [comment]
@arfon, pardon me I did not see the second page :((( Yes, indeed it is all in order. Thank you.

**Comment by danielskatz** [comment]
👋 @csoneson - ping... would you be willing to edit this submission for JOSS?

**Comment by csoneson** [comment]
@danielskatz Yes, I can do that. Sorry, I completely missed the previous post.

**Comment by danielskatz** [comment]
no worries

**Comment by danielskatz** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋 @IbrahimTanyalcin -thanks for your submission, I am in the process of reaching out to possible reviewers. I just had a quick look at your repository, and I could not find a valid license file (see https://joss.readthedocs.io/en/latest/review_criteria.html#software-license) - could you check that?

**Comment by IbrahimTanyalcin** [comment]
Added MIT, thanks for reminding, long forgotten.

**Comment by csoneson** [comment]
@whedon assign @hrhotz as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @hrhotz

**Comment by csoneson** [comment]
Hi @jkanche - would you be interested in reviewing this submission for JOSS? Looks like a nice fit for your expertise!

**Comment by jkanche** [comment]
Hi @csoneson, Yes, I'm interested in reviewing this. This would be my first review for JOSS, I was wondering what the official process is ?

**Comment by csoneson** [comment]
@jkanche Awesome! You can find reviewer guidelines here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Basically, in a few minutes I will assign you as one of the reviewers of the submission, and open the 'actual' review issue (there will be a link posted here). The review will take place in that issue - there will be a checklist for you to go through and evaluate the submission against. Comments and suggestions are also to be posted in that issue.

**Comment by csoneson** [comment]
@whedon add @jkanche as reviewer

**Comment by whedon** [comment]
OK, @jkanche is now a reviewer

**Comment by csoneson** [comment]
@whedon add @imallona as reviewer

**Comment by whedon** [comment]
OK, @imallona is now a reviewer

**Comment by csoneson** [comment]
Ok, we have a great set of reviewers ready - thanks @hrhotz, @jkanche and @imallona!

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1407. Feel free to close this issue now!

**Comment by csoneson** [comment]
Reviewers - please head over to #1407 for the actual review!
