### ISSUE TITLE
[PRE REVIEW]: MODISSnow: Download MODIS Snow Cover Data with R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#138]
**Submitting author:** @jmsigner (<a href="http://orcid.org/0000-0002-1771-7775">Johannes Signer</a>)
**Repository:** <a href="https://github.com/jmsigner/MODISSnow" target ="_blank">https://github.com/jmsigner/MODISSnow</a>
**Version:** v0.1
**Editor:** Pending
**Reviewer:** Pending

**What this issue is for**

Thanks for submitting your paper to JOSS jmsigner. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by noamross** [comment]
Hello @jmsigner.  This package looks like it would be a great match for rOpenSci, which specializes in data-access packages like this and has a joint submittal process with JOSS.  If you are interested in this approach, you can find more info here: https://github.com/ropensci/onboarding

@arfon let me know if I'm stepping out of line poaching like this ;)

**Comment by arfon** [comment]
> @arfon let me know if I'm stepping out of line poaching like this ;)

@noamross - nope. Fine with me :-)

@jmsigner - let us know what you'd like to do here. If this package was accepted into rOpenSci then this paper would effectively be automatically accepted into JOSS.

**Comment by jmsigner** [comment]
@noamross  thanks for suggesting rOpenSci. @arfon I will aim for the rOpenSci route.

**Comment by arfon** [comment]
> @noamross thanks for suggesting rOpenSci. @arfon I will aim for the rOpenSci route.

👍  OK great. We'll pause this for now. Please comment on this thread when you've finished up the rOpenSci process and we can accept the paper here too.

**Comment by arfon** [comment]
@jmsigner - was this ever accepted into rOpenSci?
