### ISSUE TITLE
[PRE REVIEW]: coronagraph: Telescope Noise Modeling for Exoplanets in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1380]
**Submitting author:** @jlustigy (<a href="http://orcid.org/0000-0002-0746-1980">Jacob Lustig-Yaeger</a>)
**Repository:** <a href="https://github.com/jlustigy/coronagraph" target ="_blank">https://github.com/jlustigy/coronagraph</a>
**Version:** v0.1
**Editor:** @arfon
**Reviewers:** @lpueyo

**Author instructions**

Thanks for submitting your paper to JOSS @jlustigy. **Currently, there isn't an JOSS editor assigned** to your paper.

@jlustigy if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01380/joss.01380/10.21105.joss.01380.pdf)

**Comment by labarba** [comment]
@arfon, I think this submission is right up your alley. Do you want to take it as handling editor?

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @lpueyo - would you be willing to review this submission for JOSS?

**Comment by arfon** [comment]
@whedon assign @lpueyo as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @lpueyo

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1387. Feel free to close this issue now!
