### ISSUE TITLE
[PRE REVIEW]: “Blaster” – a graphical user interface for common sequences analysis tools

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1381]
**Submitting author:** @snowformatics (<a href="http://orcid.org/0000-0003-0536-835X">Stefanie Lueck</a>)
**Repository:** <a href="https://github.com/snowformatics/BlasterQt" target ="_blank">https://github.com/snowformatics/BlasterQt</a>
**Version:** v.1.2.4
**Editor:** @lpantano
**Reviewers:** @vbarrera

**Author instructions**

Thanks for submitting your paper to JOSS @snowformatics. **Currently, there isn't an JOSS editor assigned** to your paper.

@snowformatics if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01381/joss.01381/10.21105.joss.01381.pdf)

**Comment by danielskatz** [comment]
👋 bioinformatics editing team (@pjotrp @mgymrek @brainstorm @lpantano) - can one of you take on this submission as editor?

**Comment by lpantano** [comment]
Hi, we will take, we need to decide some logistics. Thanks!

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
@whedon assign @vbarrera as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @vbarrera

**Comment by lpantano** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1016/S0022-2836(05)80360-2 is OK
- 10.1186/gb-2009-10-3-r25 is OK
- 10.1007/978-1-4020-6754-9_3188 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1411. Feel free to close this issue now!
