### ISSUE TITLE
[PRE REVIEW]: ECabc: A feature tuning program focused on Artificial Neural Network hyperparameters

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1383]
**Submitting author:** @sanskriti-s (<a href="http://orcid.org/0000-0002-9884-7351">Sanskriti Sharma</a>)
**Repository:** <a href="https://github.com/ECRL/ecabc" target ="_blank">https://github.com/ECRL/ecabc</a>
**Version:** v2.2.2
**Editor:** @arokem
**Reviewers:** @annoviko

**Author instructions**

Thanks for submitting your paper to JOSS @sanskriti-s. **Currently, there isn't an JOSS editor assigned** to your paper.

@sanskriti-s if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1383 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1383/paper/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@sanskriti-s — Please check the formatting of the metadata section of your paper, and adjust according to the example in the [Author Guide](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography).

**Comment by sanskriti-s** [comment]
Hi,

I fixed it. 

Thank you,
Sanskriti

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1383 with the following error: 

 ORCID looks malformed
/app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:91:in `block in check_orcids': Problem with ORCID (N/A) for Hernan Gelaf-Romer (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@sanskriti-s — We do need an ORCID for every author. If your co-author doesn't have one, they will have to create one …

**Comment by arfon** [comment]
> @sanskriti-s — We do need an ORCID for every author. If your co-author doesn't have one, they will have to create one …

Actually we don't need ORCIDs for authors, it's just the current value's of `N/A` aren't valid :-) . I've fixed this here: https://github.com/ECRL/ecabc/pull/44

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1383 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    141      0 --:--:-- --:--:-- --:--:--   142
pandoc: /images/state.png: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
👋 @sanskriti-s - in your code to include the image, you have a leading slash that shouldn't be there.  I think https://github.com/ECRL/ecabc/pull/45 should fix this.  Once you've merged it, or made the same change, you can enter ```@whedon generate pdf``` here in a new comment to try the processing again.

**Comment by sanskriti-s** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01383/joss.01383/10.21105.joss.01383.pdf)

**Comment by danielskatz** [comment]
👋 @arokem - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
👋 @arokem - ping...

**Comment by arokem** [comment]
@whedon assign arokem as editor

**Comment by whedon** [comment]
OK, the editor is arokem

**Comment by arokem** [comment]
@sanskriti-s : do you have any suggestions for reviewers?

**Comment by sanskriti-s** [comment]
@desilinguist Would you be open to reviewing?

**Comment by arokem** [comment]
Let me see if we can find someone other than me. 

@annoviko: would you be willing to review this JOSS submission?

**Comment by annoviko** [comment]
Hello, @arocem,I am little bit surprised to be suggested as a reviewer for this submission, because I am not even in the reviewer list. But anyway I have read the paper and have looked through the repository, so if there are no any other candidates, I can review it.1:39, 30 апреля 2019 г., Ariel Rokem <notifications@github.com>:Let me see if we can find someone other than me.
@annoviko: would you be willing to review this JOSS submission?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

Best regards, Andrei

**Comment by arokem** [comment]
Thank you! I identified you as a potential reviewer based on your own recent JOSS paper.

**Comment by arokem** [comment]
@whedon assign @annoviko as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @annoviko

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1420. Feel free to close this issue now!

**Comment by arokem** [comment]
Head on over to #1420 for the review. I will close this issue now.
