### ISSUE TITLE
[PRE REVIEW]: PVGeo: an open-source Python package for geoscientific visualization in VTK and ParaView

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1384]
**Submitting author:** @banesullivan (<a href="http://orcid.org/0000-0001-8628-4566">C. Bane Sullivan</a>)
**Repository:** <a href="https://github.com/OpenGeoVis/PVGeo" target ="_blank">https://github.com/OpenGeoVis/PVGeo</a>
**Version:** 2.0.0
**Editor:** @leouieda
**Reviewers:** @gassmoeller, @leguark

**Author instructions**

Thanks for submitting your paper to JOSS @banesullivan. **Currently, there isn't an JOSS editor assigned** to your paper.

@banesullivan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1384 with the following error: 

 Can't find any papers to compile :-(

**Comment by banesullivan** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by banesullivan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by labarba** [comment]
👋 @leouieda — it looks like this is a companion package to the submission I assigned you earlier today. It makes sense for you to edit both?

**Comment by whedon** [comment]
PDF failed to compile for issue #1384 with the following error: 

 Can't find any papers to compile :-(

**Comment by banesullivan** [comment]
Whoops, forgot to merge the paper into the `master` branch... on it.

**Comment by banesullivan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01384/joss.01384/10.21105.joss.01384.pdf)

**Comment by labarba** [comment]
@leouieda — I will assign you as editor on this one, but do let me know if you have any qualms.

**Comment by labarba** [comment]
@whedon assign @leouieda as editor

**Comment by whedon** [comment]
OK, the editor is @leouieda

**Comment by banesullivan** [comment]
Please note that there is a citation for `vtki` in this paper: #1382

**Comment by banesullivan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1384 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    278      0 --:--:-- --:--:-- --:--:--   282
Error producing PDF.
! Argument of \caption@ydblarg has an extra }.
<inserted text> 
                \par 
l.367 ...dary, and interpreted faulting surfaces.}

Looks like we failed to compile the PDF

**Comment by banesullivan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01384/joss.01384/10.21105.joss.01384.pdf)

**Comment by banesullivan** [comment]
How would I go about making sure Figure 2 isn't forced onto its own page? Ideally, I'd like it to be at the top of that page and then have the `Mentions` section start right under it.

I'm not familiar with the markdown to LaTeX converter used here and how I might implement a fix for this.

**Comment by leouieda** [comment]
Hi @banesullivan, just an update: I'm trying to find reviewers for your two submissions but I'm having a hard time tracking down people with the right balance of skills. I'm still waiting on a few replies but I'm hoping to get this started soon.

I'm also not too familiar with the manuscript building pipeline. Try moving the figure higher up in the document. You can ask Whedon to compile the PDF from a branch so you don't have to make broken commits to *master*: `@whedon generate pdf from branch custom-branch-name`

**Comment by banesullivan** [comment]
Thank you for the update, @leouieda!

I'll experiment on another branch with the figure layouts - thanks for the tip!

**Comment by leouieda** [comment]
:wave: Hi @ngoldbaum @rowanc1 would you be interested in reviewing this submission for JOSS?

**Comment by ngoldbaum** [comment]
I can't, I'm sorry.

**Comment by leouieda** [comment]
@ngoldbaum thanks for the quick reply :tada: No worries.

**Comment by leouieda** [comment]
@whedon assign @gassmoeller as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @gassmoeller

**Comment by leouieda** [comment]
@gassmoeller thank you agreeing to review :tada: I just wanted to add a disclaimer that @gassmoeller @banesullivan and I have recently been part on the same conference session proposals. However, this does not constitute a conflict of interest [according to our policies](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy).

**Comment by gassmoeller** [comment]
I am looking forward to review this @leouieda. Do I need to do anything to create the actual review issue or will you do that?

**Comment by leouieda** [comment]
Hi @gassmoeller happy to have you on board! I'll create the review. We're just waiting on a second reviewer. I'm having a hard time finding someone with the right skills and time. Do you have any suggestions?

**Comment by banesullivan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01384/joss.01384/10.21105.joss.01384.pdf)

**Comment by leouieda** [comment]
@whedon add @leguark as reviewer

**Comment by whedon** [comment]
OK, @leguark is now a reviewer

**Comment by leouieda** [comment]
@banesullivan let us know when things are stable after the rename of vtki/pyvista so we can start this review.

**Comment by banesullivan** [comment]
@leouieda All is stable and PVGeo is released on version `2.0.0` which is the version I'd like to submit for review (not `1.2.3` mentioned above)

**Comment by leouieda** [comment]
OK, I'll let whedon do its magic and start the review :+1:

**Comment by leouieda** [comment]
@whedon set 2.0.0 as version

**Comment by whedon** [comment]
OK. 2.0.0 is the version.

**Comment by leouieda** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01384/joss.01384/10.21105.joss.01384.pdf)

**Comment by leouieda** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1451. Feel free to close this issue now!

**Comment by leouieda** [comment]
:wave: @banesullivan @gassmoeller @Leguark please head on over to #1451 for the review. Please don't hesitate to ask if you have any questions about the review process. We encourage reviewers to open issues/PRs in the software repo as well as leave comments on the review thread. As a reminder, if you create any issues/PRs please include `openjournals/joss-reviews#1451` in the description so that it will link back to the review. This helps me keep track of what is happening.

**Comment by alexgarciac** [comment]
hi. as this is python and a py package there should be some sample data so that anyone could test that the package and all the assertions being made in the paper do really work. I read the paper and there is a lot about a lot but there is no sample data to test the package.

**Comment by leouieda** [comment]
Hi @alexgarciac, the JOSS paper [should not contain documentation or data](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). These are expect to be included in the software documentation, which the submission does. For example: https://pvgeo.org/examples/filters-general/voxelize-points.html
