### ISSUE TITLE
[REVIEW]: RAFF: Robust Algebraic Fitting Function in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1385]
**Submitting author:** @fsobral (<a href="http://orcid.org/0000-0003-4963-0946">Francisco Nogueira Calmon Sobral</a>)
**Repository:** <a href="https://github.com/fsobral/RAFF.jl" target ="_blank">https://github.com/fsobral/RAFF.jl</a>
**Version:** v0.4.1
**Editor:** @poulson
**Reviewer:** @abelsiqueira, @matbesancon
**Archive:** <a href="https://doi.org/10.5281/zenodo.3265300" target="_blank">10.5281/zenodo.3265300</a>

## Status

[![status](http://joss.theoj.org/papers/51cd6b32d9c05c58a539a415c263d773/status.svg)](http://joss.theoj.org/papers/51cd6b32d9c05c58a539a415c263d773)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/51cd6b32d9c05c58a539a415c263d773"><img src="http://joss.theoj.org/papers/51cd6b32d9c05c58a539a415c263d773/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/51cd6b32d9c05c58a539a415c263d773/status.svg)](http://joss.theoj.org/papers/51cd6b32d9c05c58a539a415c263d773)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/fsobral/RAFF.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@abelsiqueira & @matbesancon, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @poulson know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fsobral/RAFF.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v0.4.1)?
- [x] **Authorship:** Has the submitting author (@fsobral) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fsobral/RAFF.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.4.1)?
- [x] **Authorship:** Has the submitting author (@fsobral) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @abelsiqueira, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1385 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
👋  @abelsiqueira, @matbesancon — Thank you for agreeing to review this submission for JOSS! This is where the action happens. You each have a review checklist at the top of this issue thread. Feel free to enter your comments here, and to open new issues on the submission repository, as needed. Godspeed!

**Comment by matbesancon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by fsobral** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by matbesancon** [comment]
@abelsiqueira I did a first review of the paper at https://github.com/fsobral/RAFF.jl/issues/18 if you want to add some comments directly to it

**Comment by abelsiqueira** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1385 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    481      0 --:--:-- --:--:-- --:--:--   481
Error reading bibliography ./paper.bib (line 37, column 1):
unexpected "p"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by abelsiqueira** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by fsobral** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by evcastelani** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by fsobral** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by evcastelani** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by fsobral** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by evcastelani** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by evcastelani** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by evcastelani** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by matbesancon** [comment]
@labarba @poulson my review is done, after the revisions made to the package and paper I recommend its acceptance for JOSS. It's a great package and the paper explains it well

**Comment by evcastelani** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by abelsiqueira** [comment]
@labarba @poulson my review is also done, and I also recommend acceptance. The version number above, v0.4.1, has changed to v0.6.0. Otherwise, I'm good to go. Nice paper, @evcastelani and @fsobral.

**Comment by fsobral** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by fsobral** [comment]
Thanks @abelsiqueira and @matbesancon for the careful reading of the manuscript and for the suggestions to the software! It was greatly improved.

Regarding the version, I don't know how to change it...

**Comment by evcastelani** [comment]
@abelsiqueira and @matbesancon, we appreciate the effort and time spent by you to help us improve this work. Sincerely, thank you very much for the corrections and suggestions.

**Comment by poulson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1385 with the following error: 

 Can't find any papers to compile :-(

**Comment by poulson** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by poulson** [comment]
:wave: @fsobral. Thank you for your patience for my response; my apologies for the delay!

I have a few comments on the manuscript:

* Given that the point of the package is learning a model for a black-box function, unqualified usage of the term "optimal" in the opening paragraphs seems a bit aggressive given that unregularized two-norm objective functions are not typically the most competitive in terms of generalization. It would be good to add some sort of qualifier there.

* In terms of demonstrating non-differentiability of the LOVO problem, it seems to me that one can easily show this with m=2 and p=1, given F1(theta) = theta and F2(theta) = -theta in the neighborhood of theta=0. Is there a need to spend half a page showing this?

* As a nit, I would recommend adding a comma at the position "is a continuous function but assuming that" to become "is a continuous function, but assuming that".

Also, would you mind creating a DOI for the submission on Zenodo and posting it here?

**Comment by evcastelani** [comment]
>  @fsobral. Thank you for your patience for my response; my apologies for the delay!
> 
> I have a few comments on the manuscript:
> 
> * Given that the point of the package is learning a model for a black-box function, unqualified usage of the term "optimal" in the opening paragraphs seems a bit aggressive given that unregularized two-norm objective functions are not typically the most competitive in terms of generalization. It would be good to add some sort of qualifier there.

We have removed the term from the phrase. Our use for "optimal" is in the optimization sense, i.e., the parameters come from the solution of an optimization problem. However, we are only able to achieve stationary points, so there is no point in calling them "optimal" if it may cause confusion.

> * In terms of demonstrating non-differentiability of the LOVO problem, it seems to me that one can easily show this with m=2 and p=1, given F1(theta) = theta and F2(theta) = -theta in the neighborhood of theta=0. Is there a need to spend half a page showing this?

You're right, your example is enough to show the non-differentiability, but our example is used to show the whole structure of LOVO problem in context of fitting functions, not just differentiability. Our example was motivated by the discussion in https://github.com/fsobral/RAFF.jl/issues/18. 

> * As a nit, I would recommend adding a comma at the position "is a continuous function but assuming that" to become "is a continuous function, but assuming that".

Done.

> 
> Also, would you mind creating a DOI for the submission on Zenodo and posting it here?

Ok, we are waiting for Zenodo's DOI for our github project.

**Comment by fsobral** [comment]
@poulson We have successfully created a DOI for the package: 10.5281/zenodo.3242619

**Comment by fsobral** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by matbesancon** [comment]
@whedon set v0.6.1 as version

**Comment by whedon** [comment]
I'm sorry @matbesancon, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by evcastelani** [comment]
Dear @poulson, Is there any additional information, clarification on the text or on the current package that we can provide to help the evaluation of the submitted paper? In addition, as highlighted by @fsobral we don't know how change the version of package in JOSS system, can you help us?

**Comment by poulson** [comment]
Dear @evcastelani: please excuse the delay and thank you for taking the time to respond to the suggestions! I am happy to recommend the paper for publication now (@arfon).

**Comment by poulson** [comment]
@whedon set 10.5281/zenodo.3242619 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3242619" target="_blank">10.5281/zenodo.3242619</a> is the archive.

**Comment by poulson** [comment]
(pinging @openjournals/joss-eics instead of Arfon)

**Comment by kyleniemeyer** [comment]
Hi @fsobral and @evcastelani, I just made some minor edits to the paper in https://github.com/fsobral/RAFF.jl/pull/20, could you merge that? Also, there are a few final things:

- One of the expectations for JOSS papers is to contain
> A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience
Can you add this?
- Can you merge the `joss` branch into `master`, and then update the Zenodo archive with the updated version? Also, the metadata on the Zenodo archive needs to be cleaned up a bit, as the author names are not formatted properly (they should match the paper).

Thanks!

**Comment by evcastelani** [comment]
Dear @kyleniemeyer 

Thank you for your corrections in the paper.

> * One of the expectations for JOSS papers is to contain
> 
> > A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience
> > Can you add this?

Done

> * Can you merge the `joss` branch into `master`, and then update the Zenodo archive with the updated version? Also, the metadata on the Zenodo archive needs to be cleaned up a bit, as the author names are not formatted properly (they should match the paper).

We have merged the `joss` branch into `master`. Since our project is a registered Julia package, we are waiting for it to be added. When the process finishes, a new release will be automatically generated and the DOI will also be automatically generated. We will ping you with the new DOI as soon as it is generated.

**Comment by kyleniemeyer** [comment]
@evcastelani ok, thanks. Please ping us here when the DOI is ready.

**Comment by fsobral** [comment]
Dear @kyleniemeyer , here's the new DOI: `10.5281/zenodo.3265300`.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.3265300 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3265300" target="_blank">10.5281/zenodo.3265300</a> is the archive.

**Comment by kyleniemeyer** [comment]
@fsobral ok, everything looks good to go now.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/s10898-008-9280-3 is OK
- 10.1007/s001860400410 is OK
- 10.1186/1471-2105-7-123 is OK
- 10.1007/978-3-540-79246-8_29 is OK
- 10.15345/iojes.2018.03.013 is OK
- 10.1007/BFb0067700 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1007/s1175001001691 is INVALID
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/812

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/812, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
Hi @fsobral, there was an incorrect DOI, that I've corrected in https://github.com/fsobral/RAFF.jl/pull/21

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01385/joss.01385/10.21105.joss.01385.pdf)

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/s10898-008-9280-3 is OK
- 10.1007/s001860400410 is OK
- 10.1007/s11750-010-0169-1 is OK
- 10.1186/1471-2105-7-123 is OK
- 10.1007/978-3-540-79246-8_29 is OK
- 10.15345/iojes.2018.03.013 is OK
- 10.1007/BFb0067700 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/s10898-008-9280-3 is OK
- 10.1007/s001860400410 is OK
- 10.1007/s11750-010-0169-1 is OK
- 10.1186/1471-2105-7-123 is OK
- 10.1007/978-3-540-79246-8_29 is OK
- 10.15345/iojes.2018.03.013 is OK
- 10.1007/BFb0067700 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/813

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/813, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1146100967508779008) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/814
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01385](https://doi.org/10.21105/joss.01385)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats to @fsobral and @evcastelani on your submission's publication in JOSS! And thanks very much to @abelsiqueira and @matbesancon for reviewing, and @poulson for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01385/status.svg)](https://doi.org/10.21105/joss.01385)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01385">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01385/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01385/status.svg
   :target: https://doi.org/10.21105/joss.01385
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01385/status.svg)](https://doi.org/10.21105/joss.01385)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by evcastelani** [comment]
@kyleniemeyer thank you for accepting our article and providing important improvements. It was the first time we published on JOSS and it was a great experience. Thanks again to the reviewers @matbesancon 
 and @abelsiqueira for all suggestions and the editor @poulson for the support.

**Comment by fsobral** [comment]
Dear @kyleniemeyer , we forgot to mention the funding agency of our project in the paper. This is very important for us, since we might have to refund them or even be unable to apply again for funding. Is it possible to add such information and edit the paper? I'm really sorry for this trouble.

**Comment by kyleniemeyer** [comment]
@fsobral please add the necessary section to the paper on your repo, and let us know.

@arfon once they do that, can you manually update the PDF?

**Comment by arfon** [comment]
> Dear @kyleniemeyer , we forgot to mention the funding agency of our project in the paper. This is very important for us, since we might have to refund them or even be unable to apply again for funding. Is it possible to add such information and edit the paper? I'm really sorry for this trouble.

Please update your `paper.md` and I can update the paper.

**Comment by fsobral** [comment]
Thank you @arfon and @kyleniemeyer for the quick answer. The file `paper.md` has been updated in the master branch.

**Comment by arfon** [comment]
OK, the paper is now updated but it might take a while for your browser to pick up the updated PDF as there's caching on the JOSS site.

**Comment by fsobral** [comment]
Thank you @arfon !
