### ISSUE TITLE
[REVIEW]: WatchMe: Software for Reproducible Monitoring and Data Collection

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1388]
**Submitting author:** @vsoch (<a href="http://orcid.org/0000-0002-4387-3819">Vanessa Sochat</a>)
**Repository:** <a href="https://www.github.com/vsoch/watchme" target ="_blank">https://www.github.com/vsoch/watchme</a>
**Version:** 0.0.13
**Editor:** @brainstorm
**Reviewer:** @andreysmelter, @crew102
**Archive:** <a href="https://doi.org/10.5281/zenodo.2633142" target="_blank">10.5281/zenodo.2633142</a>

## Status

[![status](http://joss.theoj.org/papers/672fca0d93b6210f3d9d171e42b5a119/status.svg)](http://joss.theoj.org/papers/672fca0d93b6210f3d9d171e42b5a119)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/672fca0d93b6210f3d9d171e42b5a119"><img src="http://joss.theoj.org/papers/672fca0d93b6210f3d9d171e42b5a119/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/672fca0d93b6210f3d9d171e42b5a119/status.svg)](http://joss.theoj.org/papers/672fca0d93b6210f3d9d171e42b5a119)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://www.github.com/vsoch/watchme" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@andreysmelter and @crew102, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @brainstorm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://www.github.com/vsoch/watchme">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.0.13)?
- [x] **Authorship:** Has the submitting author (@vsoch) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://www.github.com/vsoch/watchme">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.0.13)?
- [x] **Authorship:** Has the submitting author (@vsoch) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @andreysmelter it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01388/joss.01388/10.21105.joss.01388.pdf)

**Comment by vsoch** [comment]
Thanks @andreysmelter and @crew102 for offering to review, and @brainstorm for being grandmaster editor! This isn't in the paper (as it's an extra thing) but if/when you are interested, I used this tool with git hooks to show an example of how to (automatically update) some simple plots for a watcher repo -> https://vsoch.github.io/2019/watchme-git-hook/

It will make more sense after you play around a bit :)

**Comment by crew102** [comment]
@brainstorm, is it OK for reviewers to make contributions to the repo they're reviewing or would that amount to some kind of conflict of interest? For example, if I see some spelling mistake in the documentation/paper, can I open a PR to fix it as part of my review?

**Comment by vsoch** [comment]
Why would that be a conflict of interest? I'm definitely okay with it!

**Comment by crew102** [comment]
Just wanted to make sure

**Comment by arfon** [comment]
> @brainstorm, is it OK for reviewers to make contributions to the repo they're reviewing or would that amount to some kind of conflict of interest? For example, if I see some spelling mistake in the documentation/paper, can I open a PR to fix it as part of my review?

This is completely fine 👍

**Comment by crew102** [comment]
@brainstorm , LGTM. Approved from my point of view.

**Comment by andreysmelter** [comment]
Hi @brainstorm @vsoch 
I just have a quick question if I have a minor revisions/comments where do I write them? Trying to finalize review over this weekend.

Thank you.

**Comment by vsoch** [comment]
hey @andreysmelter this is great news!

For specific questions or edits that need to be made, what I've typically done is open up an issue for each. It might seem like overkill, but it's easier for both author and reviewer to keep track of what has been fixed, and what not. What I would likely do is reference each issue in one or more PRs to address them.

**Comment by andreysmelter** [comment]
Sounds great, @vsoch 

Thank you!

**Comment by andreysmelter** [comment]
Hi @brainstorm @vsoch 
I have completed my review and raised several issues that I have found against the watchme repo. They have already been fixed and merged. Everything else looks excellent to me and ready to go to the next step (acceptance/publishing?).

Thank you.

**Comment by brainstorm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by vsoch** [comment]
ping @brainstorm

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01388/joss.01388/10.21105.joss.01388.pdf)

**Comment by brainstorm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by brainstorm** [comment]
Doh, there are no DOIs in this paper... and after reading through this final version, looks good to me. Can you deposit the zip on Zenodo? Thx!

**Comment by vsoch** [comment]
- [Released via Zenodo](https://zenodo.org/record/2667656#.XM7-j3VKjoo)
 - [Released on PyPi](https://pypi.org/project/watchme/)

**Comment by brainstorm** [comment]
@whedon set 10.5281/zenodo.2633142 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2633142" target="_blank">10.5281/zenodo.2633142</a> is the archive.

**Comment by brainstorm** [comment]
@kyleniemeyer @arfon I think we are done here, ready to accept imho :+1:

**Comment by labarba** [comment]
@vsoch — Could you edit the metadata of the Zenodo deposit so the title and author match the paper? Thanks!

**Comment by vsoch** [comment]
All set!

https://zenodo.org/record/2667656#.XNQjEnVKjoo

I also added the orcid id, and license.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/673

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/673, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/674
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01388](https://doi.org/10.21105/joss.01388)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @vsoch, your JOSS paper is published! 🚀 

Tremendous thanks to our editor: @brainstorm, and to the reviewers: @andreysmelter, @crew102 — we appreciate all that you do 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01388/status.svg)](https://doi.org/10.21105/joss.01388)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01388">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01388/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01388/status.svg
   :target: https://doi.org/10.21105/joss.01388
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01388/status.svg)](https://doi.org/10.21105/joss.01388)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by vsoch** [comment]
Thank you @brainstorm @andreysmelter @arfon @crew102 and @labarba !
