### ISSUE TITLE
[REVIEW]: Optlang: A Python interface to common mathematical optimization solvers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#139]
**Submitting author:** @KristianJensen (<a href="http://orcid.org/0000-0002-2796-805X">Kristian Jensen</a>)
**Repository:** <a href="https://github.com/biosustain/optlang" target ="_blank">https://github.com/biosustain/optlang</a>
**Version:** v1.0.0
**Editor:** @kyleniemeyer
**Reviewer:** @moorepants
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.228165" target="_blank">10.5281/zenodo.228165</a>

## Status

[![status](http://joss.theoj.org/papers/cd848071a664d696e214a3950c840e15/status.svg)](http://joss.theoj.org/papers/cd848071a664d696e214a3950c840e15)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/cd848071a664d696e214a3950c840e15"><img src="http://joss.theoj.org/papers/cd848071a664d696e214a3950c840e15/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/cd848071a664d696e214a3950c840e15/status.svg)](http://joss.theoj.org/papers/cd848071a664d696e214a3950c840e15)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/biosustain/optlang" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/biosustain/optlang">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (KristianJensen) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @moorepants it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by moorepants** [comment]
Some initial notes:

- The installation was a bit fuzzy on the dependencies. I think that at least scipy and swiglpk should be pulled in automatically with install, see https://github.com/biosustain/optlang/issues/54 for more.
- It seems the JOSS submission author, @KristianJensen, is more of a [minor contributor of the software](https://github.com/biosustain/optlang/graphs/contributors). It seems the largest contribution is by far by @phantomas1234. Is there are reason they are not the primary author?

**Comment by KristianJensen** [comment]
@moorepants Thanks for your comments so far. Regarding the contributions:
Due to a mistake on my part (forgetting to set my email in git) that was recently corrected, the majority of my commits are not linked to my github user. Doing `git log | grep 'Author: Kristian' | wc` in the current master branch returns 115 commits authored by me.

The project was originally initiated by @phantomas1234 who also drafted several of the solver interfaces and core functionality. I have contributed by adding several major features (e.g. QP support, scipy_interface, JSON-storage) and by shaping up the code from a "working draft" to "ready for submission". This has included many refactorings and bug fixes, unifying API and behaviour across solvers and setting up a common unittest suite for all the supported solvers.
Based on this we decided that I would be the submitting author, and the other authors agree that my contributions are well within the definition of "major".

**Comment by phantomas1234** [comment]
I copy all of that. Thank you for your review and your valuable comments @moorepants. We could fix the commit history for github to report @KristianJensen's contributions accurately but that would be fairly destructive and we would like to avoid that.

**Comment by moorepants** [comment]
Thanks for the clarification on the contributions. That's acceptable to me. No need to fix the git history. I assume that JOSS somehow includes all contributors as authors. So it should be fine.

**Comment by kyleniemeyer** [comment]
@moorepants @phantomas1234 @KristianJensen I'll jump in here and state that JOSS does not require the lead/submitting author to be the person who has made the majority of commits/contributions to the original code.

**Comment by moorepants** [comment]
My comments on contribution arise based on this checkbox: "Authorship: Has the submitting author (KristianJensen) made major contributions to the software?". When i looked at the Github contributors graph and commit list, it wasn't clear to me that this was satisfied. Can JOSS be more clear on what "major contributions" means?

Also @kyleniemeyer, can you clarify who JOSS assigns as authors to the "paper"?

**Comment by moorepants** [comment]
Additional items to address:

- [ ] State who the target audience is in the documentation statement of need.
- [ ] I recommend adding a CONTRIBUTING file that mirrors and maybe enhances this statement: http://optlang.readthedocs.io/en/latest/developers.html#contribute. You could be a little more explicit on where to seek support.
- [ ] Also in paper.md "who the target audience is".

**Comment by moorepants** [comment]
I finished going through the initial look. I've tested the software (automated and examples). It's super cool. I think this is an excellent use of SymPy and very useful for solving many problems. Great work!

If you can address those concerns above, I'm happy to approve this.

**Comment by kyleniemeyer** [comment]
@moorepants fair point. We don't really have an explicit definition of "major contribution"; it's mainly there to ensure we don't have someone submitting that isn't a contributor at all (and in any event the major contributors should certainly make up the author list). In this particular case, your question was certainly fine, but it seems the situation is fine as far as we're concerned.

We leave it up to the project contributors to decide who are the paper authors, but from my perspective the contributor list and author list should mostly match. @arfon do you have anything to add here?

**Comment by arfon** [comment]
> We leave it up to the project contributors to decide who are the paper authors, but from my perspective the contributor list and author list should mostly match. @arfon do you have anything to add here?

That's correct, we don't have any hard and fast rules here. I too would expect these to mostly match but I'm sure there are scenarios where they won't.

**Comment by andim** [comment]
Regarding the point "statement of need" I have two suggestions:
- Point out more prominently in the documentation/README that optlang is a modeling language for optimization problems (as opposed to a package providing solvers)
- Feature the range of optimization problems supported (seems to be LP/QP/MILP currently) more prominently e.g. this info is missing in the README
- Discuss benefits/drawbacks relative to the more standard `scipy.optimize`, which not only provides a range of solvers but also a generic interface to them (`scipy.optimize.minimize`)

**Comment by KristianJensen** [comment]
@moorepants We have now clarified who the target audience is, both in the paper and documentation and added a CONTRIBUTING.md file.

Furthermore as per the suggestions above (thanks @andim !) we have made it more clear that optlang is a modeling language (including a new paper title) and added currently supported solver capabilities to the readme. However we would prefer not to have lengthy comparisons of optlang and other available software in the documentation, although with the clarified description of optlang as a modeling language, it should be more clear what distinguishes it from e.g. `scipy.optimize.minimize`.

**Comment by moorepants** [comment]
Thanks. All looks good to me now. I recommend for acceptance.

**Comment by kyleniemeyer** [comment]
Thanks for the review @moorepants! 

@KristianJensen I just made a few minor edits to the paper in https://github.com/biosustain/optlang/pull/57, please take a look and then merge those. After that, I think we will be good to go for acceptance in JOSS—you can then archive the software, and please provide the associated DOI here.

**Comment by kyleniemeyer** [comment]
Hi @KristianJensen, just wanted to ping you on this.

**Comment by KristianJensen** [comment]
Hi @kyleniemeyer 

Everything is now merged, released and archived on zenodo at https://doi.org/10.5281/zenodo.228165

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.228165 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.228165" target="_blank">10.5281/zenodo.228165</a> is the archive.

**Comment by arfon** [comment]
@kyleniemeyer - is this good to accept now?

**Comment by kyleniemeyer** [comment]
@arfon good to go!

**Comment by arfon** [comment]
@moorepants - many thanks for your review and thanks to @kyleniemeyer for editing this submission.

@KristianJensen - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00139 ⚡️ 🚀 💥
