### ISSUE TITLE
[PRE REVIEW]: stingray: A modern Python library for spectral timing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1391]
**Submitting author:** @dhuppenkothen (<a href="http://orcid.org/0000-0002-1169-7486">Daniela Huppenkothen</a>)
**Repository:** <a href="https://github.com/StingraySoftware/stingray" target ="_blank">https://github.com/StingraySoftware/stingray</a>
**Version:** v0.1
**Editor:** @arfon
**Reviewers:** @Cadair

**Author instructions**

Thanks for submitting your paper to JOSS @dhuppenkothen. The JOSS editor @arfon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dhuppenkothen if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@arfon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1391 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1391/joss/paper.md): found character that cannot start any token while scanning for the next token at line 12 column 3 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @dhuppenkothen - this PR should fix the paper compilation issues: https://github.com/StingraySoftware/stingray/pull/394

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01391/joss.01391/10.21105.joss.01391.pdf)

**Comment by arfon** [comment]
Thanks for this submission @dhuppenkothen - do you have any suggestions for people who might be good reviewers for this submission?

**Comment by dhuppenkothen** [comment]
Do you want the answer to that question in real names or GitHub user names? :)

**Comment by arfon** [comment]
Ideally both, but feel free to quote GitHub names e.g. `@arfon` to stop people being pinged accidentally.

**Comment by dhuppenkothen** [comment]
Ah, I was wondering how to stop them from being pinged! 

I think Stuart Mumford (`@Cadair`) might be a good reviewer. Also, Nestor Espinoza `@nespinoza` and Matt Pitkin (`@mattpitkin`). Those are the ones from the list of reviewers whose names stand out, but anyone at the intersection of astronomy and Python would be great, I suspect.

**Comment by arfon** [comment]
:wave: @Cadair - would you be willing to review this submission for JOSS?

**Comment by Cadair** [comment]
Yeah I would be happy to :smile:

**Comment by arfon** [comment]
@whedon assign @Cadair as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @Cadair

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1393. Feel free to close this issue now!

**Comment by arfon** [comment]
Thanks for agreeing to review this submission @Cadair - see you over in #1393 for the actual review.
