### ISSUE TITLE
[REVIEW]: Optimising Light Source Positioning for Even and Flux-Efficient Illumination 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1392]
**Submitting author:** @adrena-lab (<a href="http://orcid.org/0000-0002-4413-5527">Stefan  Guldin</a>)
**Repository:** <a href="https://github.com/adrena-lab/Optimising-Light-Source-Positioning" target ="_blank">https://github.com/adrena-lab/Optimising-Light-Source-Positioning</a>
**Version:** 1.0.1
**Editor:** @trallard
**Reviewer:** @cmccomb, @nicoguaro
**Archive:** <a href="https://doi.org/10.5281/zenodo.2847905" target="_blank">10.5281/zenodo.2847905</a>

## Status

[![status](http://joss.theoj.org/papers/2f4e9f01dd901fcf5a14caeeff4938ff/status.svg)](http://joss.theoj.org/papers/2f4e9f01dd901fcf5a14caeeff4938ff)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/2f4e9f01dd901fcf5a14caeeff4938ff"><img src="http://joss.theoj.org/papers/2f4e9f01dd901fcf5a14caeeff4938ff/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/2f4e9f01dd901fcf5a14caeeff4938ff/status.svg)](http://joss.theoj.org/papers/2f4e9f01dd901fcf5a14caeeff4938ff)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/adrena-lab/Optimising-Light-Source-Positioning?files=1" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@cmccomb & @nicoguaro, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @trallard know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/adrena-lab/Optimising-Light-Source-Positioning?files=1">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.0.1
- [x] **Authorship:** Has the submitting author (@adrena-lab) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/adrena-lab/Optimising-Light-Source-Positioning?files=1">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.0.1
- [x] **Authorship:** Has the submitting author (@adrena-lab) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @cmccomb, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1392 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1392 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by trallard** [comment]
@nicoguaro @cmccomb thanks for agreeing to review this submission. 

You will find a checklist for each of you, please tick the items as you go over them. Use this issue to keep the updates and discussions in a central place. However, if there are longer issues or improvements that need to be requested, please make an issue on the software repo and reference it here 😄 

If you encounter any issues or have any questions about the review process feel free to ping me here

**Comment by cmccomb** [comment]
@adrena-lab This is a great repository! Here's what I think should be updated/revised: 

1. General Checks, Version: You should make a release with version 1.0.
2. Documentation, Installation instructions: Please state the dependencies. For MATLAB, this probably just means to indicate which versions it should run on. If you want to make claims for Octave (recommended!) please provide version information for that too. It would be helpful to provide a short description fo what each file does, as well as a description of what the .mat file is used for.
3. Documentation, Automated Tests: There is not way to check the functionality of the software. Maybe the authors could provide an expected optimum value for the example that users could compare against?
4. Documentation, Example Usage: Will the authors please provide some more description of the example case in the README file? This would be helpful for the reader. The content can be borrowed from the software paper.
5. Documentation, Community Guidelines: Community guidelines should be added. In addition, the zip file should not be used in the repository in order to make it easier for others to contribute. Include the .m and .mat files directly.

**Comment by nicoguaro** [comment]
@adrena-lab, I downloaded the repository and ran the main file using Octave 5.1 under Windows 10. I agree with the comments added by @cmccomb. 

I will test the software in MATLAB later, in the mean time I add the errors I obtained using Octave.

The first error was 
```
error: 'fullfact' undefined near line 44 column 16
error: called from
    Create_Variable_Combinations at line 44 column 14
    Optimising_Light_Source_Positioning at line 62 column 16
```

This was fixed doing the following in the command prompt.

    pkg load statistics

Similarly, I obtained the following error

```
error: 'std2' undefined near line 171 column 28
error: called from
    Illumination_Calculations at line 171 column 26
    Optimising_Light_Source_Positioning at line 158 column 21
```

That was fixed with

    pkg load image

There is also the following error:

```
error: 'newline' undefined near line 176 column 13
error: called from
    Convhull_Option_Reduction at line 176 column 5
    Optimising_Light_Source_Positioning at line 189 column 29
```

**Comment by adrena-lab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1392 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1392 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by adrena-lab** [comment]
Dear @trallard, @cmccomb and @nicoguaro

thank you for handling the manuscript and for the very constructive feedback to our work. We have in the meantime uploaded a revised submission on github. We restructured the organisation of the files in the repository and made major changes to the file readme.md:

1) We expanded the installation instructions to include a description of what each file does.
2) We have added a section on dependencies. 
3) We have added/expanded the Example Usage Section to include a description of the example case and how it is carried out. Further, we note that the software is automatically set up to run this example to act as an automated test. Anyone who runs the code as provided will get the same results as shown in the example. 
4) We have also added some notes on the community guidelines.
5) We have made a release version v1.0 to package the software

Please note that 
1) We received an error message from whedon about the pdf file compilation. Whedon was able to compile the pdf previously and since then, we did not change anything to the relevant file paper.md. Would you be able to resolve this issue?
2) Please note that we have no previous experience in the use of Octave. Based on the comments of @nicoguaro, it seems to be relatively straight forward to run our files, but we feel unable to facilitate this and would prefer to leave the adaptation to other platforms to the user.

We hope to have fully addressed all points raised by the reviewers and look forward to your response. 
Thank you and best wishes, 
@adrena-lab

**Comment by cmccomb** [comment]
@adrena-lab Thank you for the detailed response and revisions! I have updated my review checklist and have no further recommendations.

**Comment by nicoguaro** [comment]
I tested the software using MATLAB 2019a and obtained the results presented in the example. Nevertheless, I obtained the following warning message:

```matlab
Warning: Polynomial is badly conditioned. Add points with distinct X values, reduce the degree of the polynomial, or try centering
and scaling as described in HELP POLYFIT. 
> In polyfit (line 79)
  In Convhull_Option_Reduction (line 91)
  In Optimising_Light_Source_Positioning (line 188) 
Warning: Polynomial is badly conditioned. Add points with distinct X values, reduce the degree of the polynomial, or try centering
and scaling as described in HELP POLYFIT. 
> In polyfit (line 79)
  In Convhull_Option_Reduction (line 91)
  In Optimising_Light_Source_Positioning (line 188) 
```

## Comments

- Regarding the *Statement of need* it is present in the first paragraph of the README file, but it might be clearer if it is presented separated.
- The README present details that are too specific. It would be a good idea to move them to documentation files and leave the instructions for installation and execution of the example provided.
- The functions have plenty of comments but it lacks a [help block](https://www.mathworks.com/help/matlab/matlab_prog/add-help-for-your-program.html), especially, defining input and output parameters.
- There are lines of code (and comments) that are too long.

**Comment by adrena-lab** [comment]
Dear @trallard, @cmccomb and @nicoguaro 
thanks for the feedback we received on our recent revision, in particular the comments by @nicoguaro. We have now further revised our contribution as follows: 
	•	We fixed a Minor bug in Convhull_Option_Reduction.m to remove warning message 
	•	We fixed a minor bug in Plot_Save_Results.m to ensure the rectangle denoting the illuminated area and circles that represent the positions of the light sources are fully visible and not obstructed by the surface plot. 
	•	We added a statement of need section to README.md for clarity 
	•	We reformatted README.md file to separate installation instructions from the description of each .m & .mat file 
	•	We added help block to each function file with information defining the input and output parameters 
	•	We edited the code to ensure all lines of code and comments are not too long 
	•	Created new release (v1.0.1) to cover addition of help blocks and aforementioned bug fixes 
Our repository on Github is updated accordingly. 
Again, we are extremely grateful for the time spent on reviewing and testing our JOSS submission and for the constructive feedback that we received during the revision process. We hope that the contribution is now suitable for publication in JOSS. 
Best wishes, 
Niamh, Alaric and Stefan from @adrenlab

**Comment by nicoguaro** [comment]
I would recommend the paper for publication now.

**Comment by trallard** [comment]
Hey  @adrena-lab it seems all is now good for publication, can you please go over this list of actions before I move onto the process:

1. Create a new release on GitHub
2. Publish the package in Zenodo and share the DOI here (the general one pointing to the code and all the versions, not the one corresponding to the latest release)
3. Check the paper for: links, authors and DOIs and call `@whedon generate pdf`

Once this is completed please ping me directly

**Comment by adrena-lab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1392 with the following error: 

 Can't find any papers to compile :-(

**Comment by adrena-lab** [comment]
Dear @trallard,

We created a new release on github (v1.0.1) to encompass the latest revisions. We have published the package on Zenodo and obtained the following DOI:10.5281/zenodo.2847906.  Unfortunately, there appear to be some issues with compiling the .pdf and I am unsure how to proceed.  I would appreaciate any advice.

Thank you,

Niamh

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1392 with the following error: 

 [WARNING] Could not convert image '/tmp/tex2pdf.597/279c0eb56ba260c2eb47e84a0963ff2ed937ca37.shtml': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : 
  
  
  
  
  
  
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA Invalid bit depth (104)
[WARNING] Could not convert image '/tmp/tex2pdf.597/4c92490c05e42464422b1211c0dcf578b5cba966.shtml': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : 
  
  
  
  
  
  
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA Invalid bit depth (104)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.597/279c0eb56ba
260c2eb47e84a0963ff2ed937ca37.shtml (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.322 ...b56ba260c2eb47e84a0963ff2ed937ca37.shtml}

Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@adrena-lab - please update the URLs for images in your `paper.md` to link to GitHub RAW URLs e.g. `https://raw.githubusercontent.com/adrena-lab/Optimising-Light-Source-Positioning/Code/Figures/Figure1.png`

**Comment by adrena-lab** [comment]
Dear @arfon 

Thank you very much.  I will try that now.

Niamh

**Comment by adrena-lab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1392 with the following error:

**Comment by adrena-lab** [comment]
Dear @arfon,

I made those changes but am still encountering an error but it I cannot see what the error is.  Again, any advice would be appreciated.

Thank you,

Niamh

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01392/joss.01392/10.21105.joss.01392.pdf)

**Comment by adrena-lab** [comment]
Thank you!

**Comment by adrena-lab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01392/joss.01392/10.21105.joss.01392.pdf)

**Comment by adrena-lab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01392/joss.01392/10.21105.joss.01392.pdf)

**Comment by adrena-lab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01392/joss.01392/10.21105.joss.01392.pdf)

**Comment by adrena-lab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01392/joss.01392/10.21105.joss.01392.pdf)

**Comment by adrena-lab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1392 with the following error: 

 Error reading bibliography ./paper.bib (line 20, column 1):
unexpected "n"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by adrena-lab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01392/joss.01392/10.21105.joss.01392.pdf)

**Comment by adrena-lab** [comment]
> Hey @adrena-lab it seems all is now good for publication, can you please go over this list of actions before I move onto the process:
> 
> 1. Create a new release on GitHub
> 2. Publish the package in Zenodo and share the DOI here (the general one pointing to the code and all the versions, not the one corresponding to the latest release)
> 3. Check the paper for: links, authors and DOIs and call `@whedon generate pdf`
> 
> Once this is completed please ping me directly

Hi @trallard, 

we are done with all of the above. Only issue is that the link to the archive is not working. We had shared the details of Zenodo submission in our thread (DOI:10.5281/zenodo.2847906; https://zenodo.org/record/2847906#.XN1OA9NKhdA). 

Can this be resolved? If so, I believe we should be ready to publish. 

Thanks, 
Stefan and Niamh

**Comment by adrena-lab** [comment]
Hi @trallard,

I was wondering whether there is an update on our paper as it seems we have addressed all outstanding issues (besides the minor comment that the link to the archive is not working). It would be great to see this work published. 

Thank you and kind regards, 
Stefan

**Comment by adrena-lab** [comment]
Hi @trallard,

sorry to bother but I am wondering about the status of our manuscript. Please see above. I have an ERC interview coming up and it would be very helpful to provide evidence of this work. 

Many thanks and best wishes, 
Stefan

**Comment by trallard** [comment]
Thanks for your patience @adrena-lab  everything seems to be ok now so I will proceed with the last actions for approval and publication

**Comment by trallard** [comment]
@whedon set https://doi.org/10.5281/zenodo.2847905 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2847905" target="_blank">10.5281/zenodo.2847905</a> is the archive.

**Comment by trallard** [comment]
@whedon  check references

**Comment by trallard** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by trallard** [comment]
@whedon set 1.0.1 as version

**Comment by whedon** [comment]
OK. 1.0.1 is the version.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01392/joss.01392/10.21105.joss.01392.pdf)

**Comment by trallard** [comment]
@adrena-lab  all looks good to me so I am going to proceed for acceptance 🙋🏻‍♀️

@cmccomb  and @nicoguaro  thanks a lot for your time and valuable contribution to JOSS as reviewers for this submission 🙌🏻

@openjournals/joss-eics this submission has been accepted and is ready to be published 🎉🙌✨

**Comment by adrena-lab** [comment]
Thanks all, @cmccomb @nicoguaro and @trallard - we sincerely appreciate your service to the community. Niamh, Alaric and Stefan from @adrena-lab

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- 10.1017/9781108552493 is INVALID
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/716

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/716, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1131596666056957953) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/717
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01392](https://doi.org/10.21105/joss.01392)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
The DOI does not yet resolve for me - once it does, I will close this and the paper will be finalized.

**Comment by arfon** [comment]
Looks like it's resolving now...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01392/status.svg)](https://doi.org/10.21105/joss.01392)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01392">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01392/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01392/status.svg
   :target: https://doi.org/10.21105/joss.01392
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01392/status.svg)](https://doi.org/10.21105/joss.01392)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
