### ISSUE TITLE
[PRE REVIEW]: SCONE: Open Source Software for Predictive Simulation of Biological Motion

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1394]
**Submitting author:** @tgeijten (<a href="http://orcid.org/0000-0001-8352-8107">Thomas Geijtenbeek</a>)
**Repository:** <a href="https://github.com/opensim-org/SCONE" target ="_blank">https://github.com/opensim-org/SCONE</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @modenaxe, @demotu

**Author instructions**

Thanks for submitting your paper to JOSS @tgeijten. **Currently, there isn't an JOSS editor assigned** to your paper.

@tgeijten if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1394 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1394 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
👋 @Kevin-Mattheus-Moerman - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01394/joss.01394/10.21105.joss.01394.pdf)

**Comment by tgeijten** [comment]
Thanks! The bullets points (*) don't show up correctly. Are they supported?

**Comment by arfon** [comment]
The Markdown parser is a little fussy and needs there to be whitespace before the first bullet. This PR should fix the rendering: https://github.com/opensim-org/SCONE/pull/47

**Comment by tgeijten** [comment]
Great, thanks! I merged the PR.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01394/joss.01394/10.21105.joss.01394.pdf)

**Comment by danielskatz** [comment]
👋 @Kevin-Mattheus-Moerman - ping...  the submitting author suggested you as the handling editor.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@modenaxe @chrisdembia @moorepants @trallard @demotu @nicoguaro would you be interested in reviewing this work for JOSS?

**Comment by nicoguaro** [comment]
@Kevin-Mattheus-Moerman, currently I am reviewing another work for JOSS. So, I will decline this one.

**Comment by demotu** [comment]
yes, I can review it

@demotu <https://github.com/demotu>
-
Marcos Duarte
http://demotu.org/

**Comment by moorepants** [comment]
I am not currently available to review.

**Comment by trallard** [comment]
I am sorry @Kevin-Mattheus-Moerman  but I have some other reviews down the line that I really need to get going so I am going to pass on this one

**Comment by modenaxe** [comment]
I can review it. Also, I have tried the alpha version of SCONE few months ago - just disclosing this in case it constitutes a problem -.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @modenaxe as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @modenaxe

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @demotu as reviewer

**Comment by whedon** [comment]
OK, @demotu is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@tgeijten let me know if you'd like to recommend and reviewers

**Comment by tgeijten** [comment]
Friedl de Groote, Seungmoon Song. Perhaps @chrisdembia knows anyone else?

**Comment by tgeijten** [comment]
@Kevin-Mattheus-Moerman how many reviewers are needed?

**Comment by kyleniemeyer** [comment]
@tgeijten Generally JOSS likes to have at least two reviewers, though we can also have one if the editor serves as a second reviewer.

**Comment by Kevin-Mattheus-Moerman** [comment]
@tgeijten I usually aim for at least 2, which we already have, but I wanted to give you the chance to add some recommended reviewers. To avoid further delay we'll start the review process now.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1421. Feel free to close this issue now!
