### ISSUE TITLE
[PRE REVIEW]: Javapriori: a java tool to get frequent items and association rules using the apriori algorithm.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1395]
**Submitting author:** @jos101 (<a href="http://orcid.org/0000-0003-0299-2659">Jose Bolaño</a>)
**Repository:** <a href="https://github.com/jos101/javapriori" target ="_blank">https://github.com/jos101/javapriori</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @jos101. **Currently, there isn't an JOSS editor assigned** to your paper.

@jos101 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01395/joss.01395/10.21105.joss.01395.pdf)

**Comment by jos101** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01395/joss.01395/10.21105.joss.01395.pdf)

**Comment by jos101** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01395/joss.01395/10.21105.joss.01395.pdf)

**Comment by jos101** [comment]
@whedon

**Comment by jos101** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by jos101** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/170036.170072 is OK
- 10.1145/1133905.1133907 is OK
- 10.1023/B:DAMI.0000005258.31418.83 is OK
- 10.1177/0149206312466147 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
👋@jos101, many thanks for your submission to JOSS. Unfortunately this software is not considered in scope for JOSS as it appears to both be a minor utility package and it's not clear that it's research software https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements
