### ISSUE TITLE
[PRE REVIEW]: ppiclF: A Parallel Particle-In-Cell Library in Fortran

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1396]
**Submitting author:** @dpzwick (<a href="http://orcid.org/0000-0001-5329-6341">David Zwick</a>)
**Repository:** <a href="https://github.com/dpzwick/ppiclF/" target ="_blank">https://github.com/dpzwick/ppiclF/</a>
**Version:** v1.0
**Editor:** @jedbrown
**Reviewers:** @iljah, @markadams

**Author instructions**

Thanks for submitting your paper to JOSS @dpzwick. **Currently, there isn't an JOSS editor assigned** to your paper.

@dpzwick if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @jedbrown - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01396/joss.01396/10.21105.joss.01396.pdf)

**Comment by dpzwick** [comment]
Potential reviewers:

@dvalters 
@Chilipp 
@iljah
@jedbrown

**Comment by jedbrown** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by jedbrown** [comment]
@dpzwick Thanks for your submission. The paper is on the short side for JOSS and I think would benefit from including comparison with related method/software (some of which may be applications rather than libraries) and perhaps something on performance (if that is meant to be a distinguishing feature). The paper is intended to give a prospective user the information needed to make choices that match their research needs. Reviewers will also ask about [community guidelines ](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines) so you can get a jump on it by adding that while we assemble reviewers.

**Comment by jedbrown** [comment]
@dvalters @Chilipp @iljah Would any of you be available to review?

**Comment by Chilipp** [comment]
Hey @jedbrown and @dpzwick! This looks very interesting and I would like to review it. But unfortunately my workload for the next weeks is too high so I won't be available for a review, sorry.

**Comment by iljah** [comment]
I can review within a week or so.

**Comment by dpzwick** [comment]
Thanks for the suggestions @jedbrown. I updated the paper.

**Comment by dpzwick** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01396/joss.01396/10.21105.joss.01396.pdf)

**Comment by jedbrown** [comment]
@whedon add @iljah as reviewer

**Comment by whedon** [comment]
OK, @iljah is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @markadams as reviewer

**Comment by whedon** [comment]
OK, @markadams is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1400. Feel free to close this issue now!
