### ISSUE TITLE
[PRE REVIEW]: anesthetic: nested sampling visualisation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1398]
**Submitting author:** @williamjameshandley (<a href="http://orcid.org/0000-0002-5866-0445">Will Handley</a>)
**Repository:** <a href="https://github.com/williamjameshandley/anesthetic" target ="_blank">https://github.com/williamjameshandley/anesthetic</a>
**Version:** 1.0.0
**Editor:** @xuanxu
**Reviewers:** @tacaswell

**Author instructions**

Thanks for submitting your paper to JOSS @williamjameshandley. The JOSS editor @xuanxu, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@williamjameshandley if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @xuanxu it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@xuanxu) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01398/joss.01398/10.21105.joss.01398.pdf)

**Comment by danielskatz** [comment]
👋 @xuanxu - note that the submitter requested you as the editor - please confirm this is ok, and if this is a problem, please let me know

**Comment by danielskatz** [comment]
👋  @williamjameshandley  - I see a couple of references that are missing - perhaps the cite in the paper.md doesn't quite match the key in the .bib file?  Feel free to make changes, and enter ```@whedon generate pdf``` here as a new comment to rebuild and check.

**Comment by xuanxu** [comment]
@danielskatz :+1: I can edit this

**Comment by xuanxu** [comment]
:wave: @tacaswell: Would you be willing to review this paper? I think your expertise in matplotlib and Python visualization tools makes you a great fit for this submission.

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01398/joss.01398/10.21105.joss.01398.pdf)

**Comment by danielskatz** [comment]
@whedon assign @xuanxu as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1398 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    168      0 --:--:-- --:--:-- --:--:--   171
Error reading bibliography ./paper.bib (line 117, column 6):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01398/joss.01398/10.21105.joss.01398.pdf)

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01398/joss.01398/10.21105.joss.01398.pdf)

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01398/joss.01398/10.21105.joss.01398.pdf)

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01398/joss.01398/10.21105.joss.01398.pdf)

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01398/joss.01398/10.21105.joss.01398.pdf)

**Comment by williamjameshandley** [comment]
@danielskatz many thanks for your prompt response on this submission. I've fixed the citations. Let me know if there's anything else I can do (I don't currently see anything if I click the "list of potential reviewers").

**Comment by danielskatz** [comment]
As the assigned editor, @xuanxu will work with you on the reviewers.

From the first comment on this issue, [this list of people](https://bit.ly/joss-reviewers) works for me.

It looks like the link that is generated in the second comment in this issue ([this list of potential reviewers]([])) is broken, however.

Let's see if we can get the code that generated that fixed, by pointing it out to the author :)

**Comment by danielskatz** [comment]
👋 @arfon - see the comment above and the broken link that was generated in the second comment in this issue...  Can you fix the underlying code that generated it?

**Comment by xuanxu** [comment]
@danielskatz / @williamjameshandley I have already ask @tacaswell, we are waiting for his response :)

**Comment by williamjameshandley** [comment]
@FaustinCarter may be interested in reviewing this, as he maintains a package with some overlap in functionality [pygtc](https://pygtc.readthedocs.io/en/latest/)

**Comment by tacaswell** [comment]
Yes, I can review.

**Comment by xuanxu** [comment]
@tacaswell :sparkles: thanks! I'll assign you and start the review issue now

**Comment by xuanxu** [comment]
@whedon assign @tacaswell as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @tacaswell

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1414. Feel free to close this issue now!

**Comment by xuanxu** [comment]
@tacaswell, please head over to #1414 for the actual review
