### ISSUE TITLE
[REVIEW]: Fruitbat: A Python Package for Estimating Redshifts of Fast Radio Bursts

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1399]
**Submitting author:** @abatten (<a href="http://orcid.org/0000-0001-7599-6488">Adam Batten</a>)
**Repository:** <a href="https://github.com/abatten/fruitbat" target ="_blank">https://github.com/abatten/fruitbat</a>
**Version:** v1.0.1
**Editor:** @xuanxu
**Reviewer:** @zingale
**Archive:** <a href="https://doi.org/10.5281/zenodo.2667596" target="_blank">10.5281/zenodo.2667596</a>

## Status

[![status](http://joss.theoj.org/papers/634bb69f2445c7457bea5dbc0b83e650/status.svg)](http://joss.theoj.org/papers/634bb69f2445c7457bea5dbc0b83e650)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/634bb69f2445c7457bea5dbc0b83e650"><img src="http://joss.theoj.org/papers/634bb69f2445c7457bea5dbc0b83e650/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/634bb69f2445c7457bea5dbc0b83e650/status.svg)](http://joss.theoj.org/papers/634bb69f2445c7457bea5dbc0b83e650)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/abatten/fruitbat" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@zingale, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @xuanxu know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/abatten/fruitbat">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.1
- [x] **Authorship:** Has the submitting author (@abatten) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @zingale it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01399/joss.01399/10.21105.joss.01399.pdf)

**Comment by zingale** [comment]
added an issue about installing: https://github.com/abatten/fruitbat/issues/27

**Comment by zingale** [comment]
adding an issue about reproducing the simple example: https://github.com/abatten/fruitbat/issues/29

**Comment by zingale** [comment]
There are two more issues to be resolved:

https://github.com/abatten/fruitbat/issues/32
https://github.com/abatten/fruitbat/issues/31

otherwise, it looks good.

**Comment by abatten** [comment]
I have fixed all the issues that you mentioned it the last couple of pull requests.

**Comment by abatten** [comment]
Whilst we are here, do you know if it is possible to get the TeX files that produce the JOSS paper? This would be required if I want to submit the paper to the ArXiv. I just tested it with the PDF created by Whedon and it was rejected, requesting for all the TeX files instead of a PDF.

**Comment by zingale** [comment]
@xuanxu all of my issues have been address and I've completed the checklist and accept this for publication.

**Comment by kyleniemeyer** [comment]
@abatten regarding the TeX files, unfortunately the conversion using Pandoc happens automatically with our whedon bot, so it isn't *super* easy to get those files. You may be able to do the conversion yourself manually based on the LaTeX template here: https://github.com/openjournals/whedon/tree/master/resources

**Comment by xuanxu** [comment]
Thanks @zingale!

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01399/joss.01399/10.21105.joss.01399.pdf)

**Comment by xuanxu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1126/science.1147532 is OK
- 10.1126/science.1236789 is OK
- 10.1093/mnras/stv1953 is OK
- 10.1038/s41586-018-0867-7 is OK
- 10.1017/pasa.2016.35 is OK
- 10.3847/1538-4357/aa7d57 is OK
- 10.3847/2041-8213/834/2/L7 is OK
- 10.1086/380598 is OK
- 10.1111/j.1365-2966.2004.07359.x is OK
- 10.3847/2041-8213/aae8e3 is OK
- 10.1088/0067-0049/180/2/330 is OK
- 10.1088/0067-0049/192/2/18 is OK
- 10.1088/0067-0049/208/2/19 is OK
- 10.1051/0004-6361/201321591 is OK
- 10.1051/0004-6361/201525830 is OK
- 10.3847/1538-4357/835/1/29 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by xuanxu** [comment]
@abatten Could you please release a new version with all the recent changes?
Once you do that I need you to create an archive of that version in zenodo/figshare/other and report the DOI here.

**Comment by abatten** [comment]
I made a new release: 1.0.1 so this will have to be updated in the paper.
Archive version: 10.5281/zenodo.2667568

**Comment by xuanxu** [comment]
@abatten I can't find the release listed in GitHub: https://github.com/abatten/fruitbat/releases

**Comment by abatten** [comment]
Ah I fixed that. There should be the new release 1.0.1.

Also, I messed up the files in the Zenodo archive so I had to make a new zenodo doi: 10.5281/zenodo.2667596

**Comment by xuanxu** [comment]
Great, thanks @abatten!

**Comment by xuanxu** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01399/joss.01399/10.21105.joss.01399.pdf)

**Comment by xuanxu** [comment]
@whedon set 10.5281/zenodo.2667596 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2667596" target="_blank">10.5281/zenodo.2667596</a> is the archive.

**Comment by xuanxu** [comment]
This is ready now for publication.
Pinging EIC for final acceptance: @openjournals/joss-eics

**Comment by kyleniemeyer** [comment]
Thanks @xuanxu. CrossRef is having some issues right now, so we are going to pause on publishing accepted articles until those issues are resolved.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1126/science.1147532 is OK
- 10.1126/science.1236789 is OK
- 10.1093/mnras/stv1953 is OK
- 10.1038/s41586-018-0867-7 is OK
- 10.1017/pasa.2016.35 is OK
- 10.3847/1538-4357/aa7d57 is OK
- 10.3847/2041-8213/834/2/L7 is OK
- 10.1086/380598 is OK
- 10.1111/j.1365-2966.2004.07359.x is OK
- 10.3847/2041-8213/aae8e3 is OK
- 10.1088/0067-0049/180/2/330 is OK
- 10.1088/0067-0049/192/2/18 is OK
- 10.1088/0067-0049/208/2/19 is OK
- 10.1051/0004-6361/201321591 is OK
- 10.1051/0004-6361/201525830 is OK
- 10.3847/1538-4357/835/1/29 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/671

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/671, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/672
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01399](https://doi.org/10.21105/joss.01399)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @abatten, your JOSS paper is now published! 🎉 

With huge thanks to our editor: @xuanxu, and the reviewer: @zingale — we couldn't do this without you! 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01399/status.svg)](https://doi.org/10.21105/joss.01399)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01399">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01399/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01399/status.svg
   :target: https://doi.org/10.21105/joss.01399
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01399/status.svg)](https://doi.org/10.21105/joss.01399)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
