### ISSUE TITLE
Markdown not rendered in paper status summaries on home page

### ISSUE THREAD

**Issue by gvwilson** [openjournals/joss-reviews#14]
Firefox 46.0.1 on Mac OS X 10.10.5, Markdown summaries on home page are not rendered properly:
![screen shot 2016-05-05 at 1 02 51 pm](https://cloud.githubusercontent.com/assets/911566/15050431/cdd18902-12c1-11e6-9d6c-22f46a26ae6d.png)

**Comment by arfon** [comment]
Thanks for reporting this @gvwilson. Would you mind opening this issue on https://github.com/openjournals/joss?
