### ISSUE TITLE
[REVIEW]: pyuvdata: an interface for astronomical interferometeric datasets in python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#140]
**Submitting author:** @bhazelton (<a href="http://orcid.org/0000-0001-7532-645X">Bryna J. Hazelton</a>)
**Repository:** <a href="https://github.com/HERA-Team/pyuvdata" target ="_blank">https://github.com/HERA-Team/pyuvdata</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewer:** @astrofrog
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.297348" target="_blank">10.5281/zenodo.297348</a>

## Status

[![status](http://joss.theoj.org/papers/65cdb0663de92c9559cc95fa63800fff/status.svg)](http://joss.theoj.org/papers/65cdb0663de92c9559cc95fa63800fff)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/65cdb0663de92c9559cc95fa63800fff"><img src="http://joss.theoj.org/papers/65cdb0663de92c9559cc95fa63800fff/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/65cdb0663de92c9559cc95fa63800fff/status.svg)](http://joss.theoj.org/papers/65cdb0663de92c9559cc95fa63800fff)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/HERA-Team/pyuvdata" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/HERA-Team/pyuvdata">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (bhazelton) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @astrofrog it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋  @astrofrog - please do your review here updating the checklist as you go...

**Comment by arfon** [comment]
> 👋 @astrofrog - please do your review here updating the checklist as you go...

Friendly reminder @astrofrog 😁

**Comment by astrofrog** [comment]
@arfon - sorry for the delay, will review this now!

**Comment by astrofrog** [comment]
I've opened a few issues in the target repository and have linked to here for the critical ones (there are four, above). Once these are addressed, I think all the requirements will be met.

**Comment by astrofrog** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
> I've opened a few issues in the target repository and have linked to here for the critical ones (there are four, above). Once these are addressed, I think all the requirements will be met.

👍  thanks. @bhazelton - let us know when you've been able to address @astrofrog's review feedback.

**Comment by arfon** [comment]
Friendly reminder on this @bhazelton.

**Comment by bhazelton** [comment]
Thank you for the reminder. We are working on addressing the issues (we've
closed several of them), but we are a distributed team of scientists with
fairly busy research schedules so it may take a little bit longer. We
really appreciate the issues that were raised and we think they will make
the project better, so we want to address them fully and properly.

**Comment by bhazelton** [comment]
@arfon @astrofrog I think we have now fixed all the issues that were raised, both critical and non-critical.

**Comment by astrofrog** [comment]
This looks good to me now, so as far as I'm concerned this can be accepted!

cc @arfon @whedon

**Comment by arfon** [comment]
> This looks good to me now, so as far as I'm concerned this can be accepted!

🎉 thanks @astrofrog.

@bhazelton - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by bhazelton** [comment]
@arfon Here's the Zenodo badge: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.297348.svg)](https://doi.org/10.5281/zenodo.297348)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.297348 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.297348" target="_blank">10.5281/zenodo.297348</a> is the archive.

**Comment by arfon** [comment]
@astrofrog many thanks for the review here ✨ 

@bhazelton - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00140 :zap: 🚀 💥
