### ISSUE TITLE
[REVIEW]: ppiclF: A Parallel Particle-In-Cell Library in Fortran

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1400]
**Submitting author:** @dpzwick (<a href="http://orcid.org/0000-0001-5329-6341">David Zwick</a>)
**Repository:** <a href="https://github.com/dpzwick/ppiclF/" target ="_blank">https://github.com/dpzwick/ppiclF/</a>
**Version:** v1.0.0
**Editor:** @jedbrown
**Reviewer:** @iljah, @markadams
**Archive:** <a href="https://doi.org/10.5281/zenodo.2667285" target="_blank">10.5281/zenodo.2667285</a>

## Status

[![status](http://joss.theoj.org/papers/af8a524242ba0c072ef4c42f816b76df/status.svg)](http://joss.theoj.org/papers/af8a524242ba0c072ef4c42f816b76df)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/af8a524242ba0c072ef4c42f816b76df"><img src="http://joss.theoj.org/papers/af8a524242ba0c072ef4c42f816b76df/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/af8a524242ba0c072ef4c42f816b76df/status.svg)](http://joss.theoj.org/papers/af8a524242ba0c072ef4c42f816b76df)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dpzwick/ppiclF/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@iljah & @markadams, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @jedbrown know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dpzwick/ppiclF/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.0
- [x] **Authorship:** Has the submitting author (@dpzwick) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dpzwick/ppiclF/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.0
- [x] **Authorship:** Has the submitting author (@dpzwick) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @iljah, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01400/joss.01400/10.21105.joss.01400.pdf)

**Comment by jedbrown** [comment]
@iljah @markadams :wave:  Welcome and thanks for agreeing to review! The comments from @whedon above outline the review process, which takes place in this thread (possibly with issues filed in the [ppiclF repository](https://github.com/dpzwick/ppiclF/). I'll be watching this thread if you have any questions.

**Comment by markadams** [comment]
I think having the data lurk in common blocks will limit the extensibility of this project. I would suggest a more object oriented approach like provide a particle list object and iterators of some sort, and methods that operate on these lists. For instance, using multiple species of particles does not look feasible now. I don't know what the long term goal of this project is but it is young and I am suggesting a major refactoring -- the longer you wait the harder it will be to do.

**Comment by dpzwick** [comment]
Thank you, that is a good suggestion. Indeed I think we may head that direction in the future. Either by upgrading to Fortran 90 or possibly even a while C++ overhaul. 

While this would be helpful, it shouldn't hinder the current capabilities of ppiclF. Multiple species can be done already since the user can solve whichever equations they want and also store arbitrary numbers of properties in their simulation.

I will keep this in mind for future versions though.

**Comment by iljah** [comment]
Documentation (README.md as far as I can tell) could use a bit longer statement of need and is missing installation instructions and community guidelines.

**Comment by iljah** [comment]
According to my instructions there should be API documentation but I don't see any in the repository. Where can I learn e.g. how `ppiclc_solve_InitBoxFilter` works?

**Comment by iljah** [comment]
Readme also doesn't say anything about testing the library.

**Comment by iljah** [comment]
Added some installation issues to library repo:
 - https://github.com/dpzwick/ppiclF/issues/25
 - https://github.com/dpzwick/ppiclF/issues/26
 - https://github.com/dpzwick/ppiclF/issues/27

**Comment by iljah** [comment]
One more: https://github.com/dpzwick/ppiclF/issues/28

**Comment by dpzwick** [comment]
Thank you for the feedback @iljah. I think issues dpzwick/ppiclF#25, dpzwick/ppiclF#26, and dpzwick/ppiclF#28 are a simple misunderstanding of not being able to see the documentation website. 

While the link to the website was in the compiled JOSS pdf, I made it more clear in the README.md file along with your previous suggestions to that file (see [this commit](https://github.com/dpzwick/ppiclF/commit/ecf2aa00fffe62100f66631959353c94195489f4)).

As for issue dpzwick/ppiclF#27, I agree. It was confusing that even when a different compiler is specified gslib would compile with a hard-coded mpicc. I updated the source so gslib will use the same compiler as the main ppiclF Makefile. Although I also note that the only supported compilers currently are mpicc, mpif77 and mpif90.

**Comment by dpzwick** [comment]
Also, to address your question above about where to find information about items such as: ppiclc_solve_InitBoxFilter, there is extensive information on the documentation website [here](https://dpzwick.github.io/ppiclF-doc/user/external.html).

**Comment by iljah** [comment]
Documentation on external website should be ok now that there's also a link to it in readme but it's also missing a statement of need or at least the target audience.

About performance: is there are particular reason why ghost particle send doesn't seem to scale past 1000 ranks, or at all? Also how many particles / s does ppiclF process on one core?

A link to vulcan page at LLNL in performance section would be nice.

**Comment by dpzwick** [comment]
Thank you for the feedback. I updated the readme to include a target audience in [this commit](https://github.com/dpzwick/ppiclF/commit/db29738bc62cc4ae659a27a4ed240f668a736f97) and [this commit](https://github.com/dpzwick/ppiclF/commit/0f154f3cd1c2b5ee8f28e0cde1ad4f45b3921b8a).

Regarding the ghost particles, the reason for this is the underlying all-to-all communication. At best all-to-all communication can be log_2 (R) where R is number of MPI ranks unless some very specific refactoring of communication patterns is done. In the weak scaling, the particles per rank is fixed so it is expected to see this log scaling.

Regarding the number of particles on a single core, the number is only limited by the available memory per core. In the performance section it was varied between 256 - 24,576 when the strong scaling was done, although it could have been higher if needed.

I also added a link to Vulcan on the website in [this commit](https://github.com/dpzwick/ppiclF-doc/commit/e3f8d29173c14ee3fb0702b4303c9ceaa1e72ab7) so it is updated now.

**Comment by iljah** [comment]
Thanks, I was asking about solved particles per second per core not number of particles. 

What fraction of CPU time was used by the fluid solver and was that included in timings provided in performance section? I can imagine with only 300 particles per process the fluid solution would take much more time than particles which would improve particle scaling since time spent transferring particle data would be masked by fluid computation.

**Comment by dpzwick** [comment]
In the scaling cases the fluid was not timed. Since Nek5000 was used, the times for the fluid solver are highly dependent on problem set setup since the fluid solver will iterate on a pressure poisson system. For this reason, the times on the scaling plots are only for ppiclF and not for any part of the fluid solver that it was coupled to.

**Comment by iljah** [comment]
So there was no ppiclF communication going on while fluid solver was running?

In any case I think all checklist items have been addressed so @jedbrown to me this looks good to go. Thanks!

**Comment by dpzwick** [comment]
There were barriers set so that just the timings for ppiclF could be tested. In real applications there may be some overlap of communication with computation though. 

Thanks for your insight and suggestions @iljah and @markadams!

**Comment by jedbrown** [comment]
@dpzwick Some minor tweaks to the paper:
1. No need to cite the repository for this software; it appears in the margin.
2. Please check `[-@` and `@` syntax for your references. https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax
3. The displayed equation is completely general, but presumably one would not use this when `Y` is exclusively mesh-based field data, for example. A couple sentences about what particle-in-cell methods are and how ppiclF interfaces with field-based solvers would be useful. This could cite traditional publications that would be relevant to a user interested in further details or applications.
4. It would be useful to mention some other PIC software and how ppiclF compares to them. Note that some (e.g., [geodynamics](http://www.underworldcode.org/)) use only a handful of particles per cell while others (like plasma applications) use many thousands of particles per cell. A library might be better in one regime than another. [Underworld](http://www.underworldcode.org/) and [XGC1](https://epsi.pppl.gov/computing/xgc-1) are familiar to me, and [there](https://picksc.idre.ucla.edu/software/software-production-codes/) [are](https://fbpic.github.io/) [others](http://warp.lbl.gov/) likely to turn up if a prospective user searches.

**Comment by dpzwick** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by dpzwick** [comment]
Thanks for the feedback @jedbrown .

I updated the PDF based on your suggestions.

**Comment by jedbrown** [comment]
Thanks. The ICPP `booktitle` field needs case protection. For the Nek5000 and CMT-nek references, I would use "in-text" style, `... Navier-Stokes solver Nek5000 [-@nek5000] ...`.

**Comment by dpzwick** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01400/joss.01400/10.21105.joss.01400.pdf)

**Comment by dpzwick** [comment]
The references are update now. Although it doesn't seem like the [-@nek5000] has an effect.

**Comment by jedbrown** [comment]
Ah, that formatting is because the bib entries don't have an `author` field. Surely there are some people, or "Nek5000 Development Team", that make sense to list as authors.

**Comment by dpzwick** [comment]
I can probably find some people but that is the recommended citation style
on their website. What do you think?

**Comment by jedbrown** [comment]
Oh, I see what you mean. That's unfortunate. I don't think there's a way to format the link optimally, so would type it manually `Nek5000 (2019)` and drop in the `nocite`. If that looks right, we'll be ready to tag and archive.

**Comment by dpzwick** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01400/joss.01400/10.21105.joss.01400.pdf)

**Comment by dpzwick** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01400/joss.01400/10.21105.joss.01400.pdf)

**Comment by dpzwick** [comment]
The paper has been updated. Thanks!

**Comment by jedbrown** [comment]
Looks good to me. Please tag a release and archive on Zenodo or similar. We would prefer that both your source and documentation repository be archived together at the same DOI. I believe you can do that by directly uploading the files (instead of using the GitHub integration) from both repositories, then adding your metadata. Let me know if you have questions about that process, and please report the DOI back here when done.

**Comment by dpzwick** [comment]
I uploaded to Zenodo with the source and documentation. The DOI is: 10.5281/zenodo.2667285.

**Comment by jedbrown** [comment]
@whedon set 10.5281/zenodo.2667285 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2667285" target="_blank">10.5281/zenodo.2667285</a> is the archive.

**Comment by jedbrown** [comment]
@whedon set v1.0.0 as version

**Comment by whedon** [comment]
OK. v1.0.0 is the version.

**Comment by jedbrown** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1109/IPPS.1996.508039 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jedbrown** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/659

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/659, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1109/IPPS.1996.508039 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jedbrown** [comment]
@openjournals/joss-eics :wave: over to you.

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/660
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01400](https://doi.org/10.21105/joss.01400)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
This DOI doesn't yet resolve for me - once it does, I will close this issue, and the publication process will be complete

**Comment by danielskatz** [comment]
@arfon - does this DOI work for you?  It doesn't for me, 5-6 hours after it should have been created ...

**Comment by kyleniemeyer** [comment]
This one does not work for me either, just now.

**Comment by arfon** [comment]
@kyleniemeyer @danielskatz - looks like the Crossref deposit API is down (http://status.crossref.org/incidents/psyzb7txpwbq) - suggest not accepting any papers until this is resolved.

**Comment by kyleniemeyer** [comment]
@arfon it looks as though that issue was only temporary; can we try depositing again? I imagine this would have be done manually.

**Comment by arfon** [comment]
> @arfon it looks as though that issue was only temporary; can we try depositing again? I imagine this would have be done manually.

I tried already. Unfortunately Crossref are *actually* having major issues with their deposit API, they just don't seem to have posted publicly about it. Perhaps no-body is on call over the weekend :-\ ?

**Comment by arfon** [comment]
Looks like the DOI is resolving now.

**Comment by danielskatz** [comment]
Thanks @iljah & @markadams for reviewing and @jedbrown for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01400/status.svg)](https://doi.org/10.21105/joss.01400)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01400">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01400/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01400/status.svg
   :target: https://doi.org/10.21105/joss.01400
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01400/status.svg)](https://doi.org/10.21105/joss.01400)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
