### ISSUE TITLE
[PRE REVIEW]: pymcmcstat: A Python Package for Bayesian Inference Using Delayed Rejection Adaptive Metropolis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1401]
**Submitting author:** @prmiles (<a href="http://orcid.org/0000-0002-7501-5114">Paul Miles</a>)
**Repository:** <a href="https://github.com/prmiles/pymcmcstat" target ="_blank">https://github.com/prmiles/pymcmcstat</a>
**Version:** v1.7.0
**Editor:** @katyhuff
**Reviewers:** @djmitche, @jarvist

**Author instructions**

Thanks for submitting your paper to JOSS @prmiles. **Currently, there isn't an JOSS editor assigned** to your paper.

@prmiles if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01401/joss.01401/10.21105.joss.01401.pdf)

**Comment by danielskatz** [comment]
👋 @katyhuff - the submitter requested you as the editor - are you willing to accept?

**Comment by katyhuff** [comment]
yes!

**Comment by katyhuff** [comment]
@whedon set @katyhuff as editor

**Comment by katyhuff** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by katyhuff** [comment]
Thank you for your submission @prmiles .  I'll now identify appropriate reviewers and request their assistance with this review.

**Comment by katyhuff** [comment]
I've found some great folks. Now @prmiles , let's ping a few fitting reviewers, with python, statistics (ideally bayesian), and some computational physics expertise. We can start the review once two or three of them accept the request to review.

**Comment by katyhuff** [comment]
Dear @jarvist : 

I have identified you as a fitting reviewer for this paper, which will require experts with python, statistics (ideally bayesian), and some computational physics expertise. Are you able to and interested in taking on this JOSS review?

Title: pymcmcstat: A Python Package for Bayesian Inference Using Delayed Rejection Adaptive Metropolis
Summary:  A Python program for running Markov Chain Monte Carlo (MCMC) simulations.  Included in this package is the ability to use different Metropolis based sampling techniques including Metropolis-Hastings, Adaptive-Metropolis, Delayed-Rejection, and Delayed Rejection Adaptive Metropolis. This Python package is an adaptation of the MATLAB toolbox mcmcstat.  
Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01401/joss.01401/10.21105.joss.01401.pdf
Submitting author: @prmiles (Paul Miles)
Repository: https://github.com/prmiles/pymcmcstat
Version: v1.7.0

**Comment by katyhuff** [comment]
Dear @ivergara : 

I have identified you as a fitting reviewer for this paper, which will require experts with python, statistics (ideally bayesian), and some computational physics expertise. Are you able to and interested in taking on this JOSS review?


Title: pymcmcstat: A Python Package for Bayesian Inference Using Delayed Rejection Adaptive Metropolis
Summary:  A Python program for running Markov Chain Monte Carlo (MCMC) simulations.  Included in this package is the ability to use different Metropolis based sampling techniques including Metropolis-Hastings, Adaptive-Metropolis, Delayed-Rejection, and Delayed Rejection Adaptive Metropolis. This Python package is an adaptation of the MATLAB toolbox mcmcstat.  
Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01401/joss.01401/10.21105.joss.01401.pdf
Submitting author: @prmiles (Paul Miles)
Repository: https://github.com/prmiles/pymcmcstat
Version: v1.7.0

**Comment by katyhuff** [comment]
Dear @djmitche:

I have identified you as a fitting reviewer for this paper, which will require experts with python, statistics (ideally bayesian), and some computational physics expertise. Are you able to and interested in taking on this JOSS review?


Title: pymcmcstat: A Python Package for Bayesian Inference Using Delayed Rejection Adaptive Metropolis
Summary:  A Python program for running Markov Chain Monte Carlo (MCMC) simulations.  Included in this package is the ability to use different Metropolis based sampling techniques including Metropolis-Hastings, Adaptive-Metropolis, Delayed-Rejection, and Delayed Rejection Adaptive Metropolis. This Python package is an adaptation of the MATLAB toolbox mcmcstat.  
Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01401/joss.01401/10.21105.joss.01401.pdf
Submitting author: @prmiles (Paul Miles)
Repository: https://github.com/prmiles/pymcmcstat
Version: v1.7.0

**Comment by katyhuff** [comment]
Dear @malmaud:

I have identified you as a fitting reviewer for this paper, which will require experts with python, statistics (ideally bayesian), and some computational physics expertise. Are you able to and interested in taking on this JOSS review?


Title: pymcmcstat: A Python Package for Bayesian Inference Using Delayed Rejection Adaptive Metropolis
Summary:  A Python program for running Markov Chain Monte Carlo (MCMC) simulations.  Included in this package is the ability to use different Metropolis based sampling techniques including Metropolis-Hastings, Adaptive-Metropolis, Delayed-Rejection, and Delayed Rejection Adaptive Metropolis. This Python package is an adaptation of the MATLAB toolbox mcmcstat.  
Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01401/joss.01401/10.21105.joss.01401.pdf
Submitting author: @prmiles (Paul Miles)
Repository: https://github.com/prmiles/pymcmcstat
Version: v1.7.0

**Comment by katyhuff** [comment]
Dear @betatim:
I have identified you as a fitting reviewer for this paper, which will require experts with python, statistics (ideally bayesian), and some computational physics expertise. Are you able to and interested in taking on this JOSS review?


Title: pymcmcstat: A Python Package for Bayesian Inference Using Delayed Rejection Adaptive Metropolis
Summary:  A Python program for running Markov Chain Monte Carlo (MCMC) simulations.  Included in this package is the ability to use different Metropolis based sampling techniques including Metropolis-Hastings, Adaptive-Metropolis, Delayed-Rejection, and Delayed Rejection Adaptive Metropolis. This Python package is an adaptation of the MATLAB toolbox mcmcstat.  
Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01401/joss.01401/10.21105.joss.01401.pdf
Submitting author: @prmiles (Paul Miles)
Repository: https://github.com/prmiles/pymcmcstat
Version: v1.7.0

**Comment by katyhuff** [comment]
Dear @ejolly:

I have identified you as a fitting reviewer for this paper, which will require experts with python, statistics (ideally bayesian), and some computational physics expertise. Are you able to and interested in taking on this JOSS review?


Title: pymcmcstat: A Python Package for Bayesian Inference Using Delayed Rejection Adaptive Metropolis
Summary:  A Python program for running Markov Chain Monte Carlo (MCMC) simulations.  Included in this package is the ability to use different Metropolis based sampling techniques including Metropolis-Hastings, Adaptive-Metropolis, Delayed-Rejection, and Delayed Rejection Adaptive Metropolis. This Python package is an adaptation of the MATLAB toolbox mcmcstat.  
Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01401/joss.01401/10.21105.joss.01401.pdf
Submitting author: @prmiles (Paul Miles)
Repository: https://github.com/prmiles/pymcmcstat
Version: v1.7.0

**Comment by djmitche** [comment]
I have good experience in Python and minimal statistical experience.  On that basis, I'm happy to help.

**Comment by katyhuff** [comment]
@djmitche : Thank you! I particularly hoped that you could contribute with regard to reviewing the testing coverage!

**Comment by katyhuff** [comment]
@whedon assign @djmitche as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @djmitche

**Comment by jarvist** [comment]
This software package has good overlap with my expertise, and I am happy to review. As the package is quite extensive in features and size of code-base, review may take a while.

**Comment by katyhuff** [comment]
@jarvist  : Thank you! I appreciate your engagement. If good software-development practices have been employed, I've found that even large code bases become much more straightforward to review. It is my hope this is the case with this submission. We'll start the review as soon as we have one more reviewer.

**Comment by katyhuff** [comment]
@whedon add @jarvist as reviewer

**Comment by whedon** [comment]
OK, @jarvist is now a reviewer

**Comment by ivergara** [comment]
@katyhuff unfortunately I cannot take this review, Bayesian statistics falls (at the moment) too far from my knowledge corpus to be able to provide a good feedback on how the package works.

**Comment by katyhuff** [comment]
Thank you for letting me know @ivergara .

**Comment by katyhuff** [comment]
@malmaud @ejolly @betatim Are any of you available to conduct this review? It would be great to have a 3rd reviewer. Thank you!


Title: pymcmcstat: A Python Package for Bayesian Inference Using Delayed Rejection Adaptive Metropolis
Summary: A Python program for running Markov Chain Monte Carlo (MCMC) simulations. Included in this package is the ability to use different Metropolis based sampling techniques including Metropolis-Hastings, Adaptive-Metropolis, Delayed-Rejection, and Delayed Rejection Adaptive Metropolis. This Python package is an adaptation of the MATLAB toolbox mcmcstat.
Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01401/joss.01401/10.21105.joss.01401.pdf
Submitting author: @prmiles (Paul Miles)
Repository: https://github.com/prmiles/pymcmcstat
Version: v1.7.0

**Comment by ejolly** [comment]
@katyhuff This package looks really great and I would be happy to help review however this week and for the next 3 weeks I'll be traveling so I likely won't be able to assist reviewing for about a month. If that timeline works I'm happy to conduct the review then. Otherwise, I'd suggest finding someone else who can review on a shorter timeline. Apologies!

**Comment by katyhuff** [comment]
Ok -- it looks like folks are pretty busy -- we'll move forward with two reviewers on this one. Thanks for letting me know, @betatim @ejolly !

**Comment by katyhuff** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1417. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Ok @prmiles @djmitche @jarvist , let's move to #1417 and start the review over there!
