### ISSUE TITLE
[PRE REVIEW]: hdme: High-Dimensional Regression with Measurement Error

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1402]
**Submitting author:** @osorensen (<a href="http://orcid.org/0000-0003-0724-3542">Øystein Sørensen</a>)
**Repository:** <a href="https://github.com/osorensen/hdme" target ="_blank">https://github.com/osorensen/hdme</a>
**Version:** v0.2.3
**Editor:** @csoneson
**Reviewers:** @dirmeier, @dmbates

**Author instructions**

Thanks for submitting your paper to JOSS @osorensen. **Currently, there isn't an JOSS editor assigned** to your paper.

@osorensen if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01402/joss.01402/10.21105.joss.01402.pdf)

**Comment by danielskatz** [comment]
👋 @csoneson - the submitter requested you as the editor - are you willing to edit this submission?

**Comment by csoneson** [comment]
@danielskatz yes, I'd be happy to.

**Comment by danielskatz** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋Hi @dirmeier, @dmbates, @fabian-s - would you be interested in reviewing this submission for JOSS? It looks like a nice fit to your expertise!

**Comment by dirmeier** [comment]
Hey, sure thing! I'd be happy to review.

**Comment by csoneson** [comment]
@dirmeier Fantastic, thanks! I'll try to get one more reviewer on board before opening the actual review issue.

**Comment by csoneson** [comment]
@whedon assign @dirmeier as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dirmeier

**Comment by dmbates** [comment]
I am also happy to review.

**Comment by csoneson** [comment]
@dmbates Excellent, thank you!

**Comment by csoneson** [comment]
@whedon add @dmbates as reviewer

**Comment by whedon** [comment]
OK, @dmbates is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1404. Feel free to close this issue now!

**Comment by csoneson** [comment]
Ok - the review is started in #1404 - I'll close this issue, and we'll continue over there! Thanks again for agreeing to review.
