### ISSUE TITLE
[PRE REVIEW]: DEEPaaS API: a REST API for Machine Learning and Deep Learning models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1403]
**Submitting author:** @alvarolopez (<a href="http://orcid.org/0000-0002-0013-4602">Álvaro López García</a>)
**Repository:** <a href="https://github.com/indigo-dc/DEEPaaS" target ="_blank">https://github.com/indigo-dc/DEEPaaS</a>
**Version:** 0.3.0
**Editor:** @trallard
**Reviewers:** @dangunter, @krother, @rougier

**Author instructions**

Thanks for submitting your paper to JOSS @alvarolopez. **Currently, there isn't an JOSS editor assigned** to your paper.

@alvarolopez if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01403/joss.01403/10.21105.joss.01403.pdf)

**Comment by danielskatz** [comment]
👋 @trallard - this submission requests you as the editor - are you willing to do so?

**Comment by alvarolopez** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01403/joss.01403/10.21105.joss.01403.pdf)

**Comment by alvarolopez** [comment]
I see that my name is wrong in the proofs. We Spaniards have 2 surnames (López García), but only my last surname is being considered as such (García). Is there an easy way to indicate that "López García" are two surnames, rather than joining them with a hyphen?

**Comment by danielskatz** [comment]
👋 @arfon - How do we do this?

**Comment by arfon** [comment]
> 👋 @arfon - How do we do this?

This is something we have to fix manually I'm afraid. We generally do this at the point of accepting the submission.

**Comment by danielskatz** [comment]
Thanks @arfon  - So @alvarolopez, please be sure we fix this manually at the end of review/acceptance, and don't worry about it for now.

**Comment by alvarolopez** [comment]
@danielskatz @arfon cool, thanks for the info.

**Comment by trallard** [comment]
Hi @danielskatz  I would be happy to take this review as the editor

**Comment by danielskatz** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by trallard** [comment]
Hi @alvarolopez 

Have you got any reviewers in mind for this submission? You can check the list of registered reviewers ➡️ https://bit.ly/joss-reviewers](https://bit.ly/joss-reviewers) and suggest a couple of suitable ones

**Comment by alvarolopez** [comment]
Hi @trallard 
Although the list is dauning, I think that @dangunter or @jsta could make a review for this.

Cheers.

**Comment by dangunter** [comment]
Hi, I can comment on the general idea  but as I don't really do ML etc. in practice I can't comment on the value proposition of such a tool -- if that is even a desired outcome of the review.

**Comment by dangunter** [comment]
Hi @trallard I could review this but not sure what to do next

**Comment by trallard** [comment]
Thanks @dangunter I will add you now

**Comment by trallard** [comment]
@whedon add @dangunter as reviewer

**Comment by whedon** [comment]
OK, @dangunter is now a reviewer

**Comment by trallard** [comment]
Hi @jsta would you be willing to and able to take this review?

**Comment by jsta** [comment]
Unfortunately I cannot, as my reviewing queue is full.

**Comment by trallard** [comment]
Thanks for your patience @alvarolopez let's try and find you another reviewer to move this forward

Hi @nilesh-patil are you willing and able to take on this review?
Hi @rasbst are you willing and able to take on this review?
Hi @ssomani are you willing and able to take on this review?
Hi @GregaVrbancic are you willing and able to take on this review?
 
**Title**: DEEPaaS
**Description**: DEEP as a Service (DEEPaaS) is a REST API that is focused on providing access to machine learning models. By using DEEPaaS users can easily run a REST API in front of their model, thus accessing its functionality via HTTP calls.
**Repo**: [https://github.com/indigo-dc/DEEPaaS](https://github.com/indigo-dc/DEEPaaS)

**Comment by trallard** [comment]
👋🏼@rougier @krother @nirum @kellieotto would any of you be interested and willing to review this submission?

**Comment by kellieotto** [comment]
@trallard thanks for checking but I currently don't have time to review this.

**Comment by krother** [comment]
@trallard I would be happy to review this submission

**Comment by rougier** [comment]
@trallard I'm a bit busy right now but after June, 30 I'll more time.

**Comment by trallard** [comment]
Thanks @krother  and @rougier  I will assign you both to the review process and take it from there. 

@rougier  feel free to jump into as and when you can

**Comment by trallard** [comment]
@whedon  set @krother as reviewer

**Comment by trallard** [comment]
@whedon set @rougier as reviewer

**Comment by trallard** [comment]
@whedon add @krother as reviewer

**Comment by whedon** [comment]
OK, @krother is now a reviewer

**Comment by trallard** [comment]
@whedon  add @rougier as reviewer

**Comment by trallard** [comment]
@whedon add @rougier as reviewer

**Comment by whedon** [comment]
OK, @rougier is now a reviewer

**Comment by trallard** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1517. Feel free to close this issue now!

**Comment by trallard** [comment]
@whedon start review
