### ISSUE TITLE
[REVIEW]: hdme: High-Dimensional Regression with Measurement Error

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1404]
**Submitting author:** @osorensen (<a href="http://orcid.org/0000-0003-0724-3542">Øystein Sørensen</a>)
**Repository:** <a href="https://github.com/osorensen/hdme" target ="_blank">https://github.com/osorensen/hdme</a>
**Version:** 0.3.0
**Editor:** @csoneson
**Reviewer:** @dirmeier, @dmbates
**Archive:** <a href="https://doi.org/10.5281/zenodo.2939896" target="_blank">10.5281/zenodo.2939896</a>

## Status

[![status](http://joss.theoj.org/papers/cd3ffee6f58a8d5034ec516d3d329b76/status.svg)](http://joss.theoj.org/papers/cd3ffee6f58a8d5034ec516d3d329b76)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/cd3ffee6f58a8d5034ec516d3d329b76"><img src="http://joss.theoj.org/papers/cd3ffee6f58a8d5034ec516d3d329b76/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/cd3ffee6f58a8d5034ec516d3d329b76/status.svg)](http://joss.theoj.org/papers/cd3ffee6f58a8d5034ec516d3d329b76)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/osorensen/hdme" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dirmeier & @dmbates, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/osorensen/hdme">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.3.0
- [x] **Authorship:** Has the submitting author (@osorensen) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/osorensen/hdme">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.3.0
- [x] **Authorship:** Has the submitting author (@osorensen) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dirmeier, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01404/joss.01404/10.21105.joss.01404.pdf)

**Comment by csoneson** [comment]
@dirmeier, @dmbates - please perform your review in this issue, by updating your checklist above and posting comments. If you have any questions, don't hesitate to ping me.

**Comment by osorensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1404 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1404/paper.md): invalid leading UTF-8 octet at line 1 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by osorensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01404/joss.01404/10.21105.joss.01404.pdf)

**Comment by osorensen** [comment]
Thanks to @dirmeier and @dmbates for agreeing to review. Just a note; I added doi to all references in paper.bib and recompiled the article. The content in paper.md is unchanged.

**Comment by dmbates** [comment]
It appears that the last release in the repository is 0.2.2, not 0.2.3

**Comment by osorensen** [comment]
Thanks for pointing this out, @dmbates. I have now tagged the appropriate commit in the repository to version 0.2.3, which is the one currently on CRAN. Note that there have been some small commits to the development version since the release.

https://github.com/osorensen/hdme/releases

**Comment by dmbates** [comment]
Not the fault of this package but my initial installation attempt on a clean R install failed because the Rglpk package failed to install.  It has an external dependency on an executable that I needed to track down and get installed before I could install this package.

**Comment by dmbates** [comment]
There do not appear to be print methods for many of the model types in the examples that I tried.  If you are going to assign an S3 class to the fitted model then it would be common to provide methods for print and for various extractors like coef.

Also the fitting functions typically take the name of the model type without prepending "fit_" or a similar phrase.  So an "lm" object is created by "lm", not "fit_lm", etc.

**Comment by dmbates** [comment]
The tests seem rather perfunctory - for the most part checking dimensions.  A more systematic testing approach would be welcome.

**Comment by dirmeier** [comment]
See here for the manuscript's revision itself: https://github.com/osorensen/hdme/issues/26

**Comment by osorensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01404/joss.01404/10.21105.joss.01404.pdf)

**Comment by osorensen** [comment]
Thanks to both reviewers for the very useful feedback and @csoneson for the summary. 

I have now added doi for Sorensen et al. (2015) and written a note about the GLPK dependency in the repository README.

I will work on adding print functions and standardizing names of the fitting functions during the next week.

**Comment by osorensen** [comment]
Dear @csoneson, @dmbates and @dirmeier 

The master branch of the GitHub repository is now updated with development version 0.2.3.9001 of hdme. The following are the most important updates:

- All main methods have been renamed according to the suggestion from @dmbates, i.e., the function names are now `gmus()`, `gmu_lasso()`, .etc., rather than `fit_gmus()`, `fit_gmu_lasso()?, etc.
- print() and coef() methods have been added for all S3 classes, as suggested by @dmbates. Their use is illustrated for the `gmus()` function in [this issue](https://github.com/osorensen/hdme/issues/29), and the examples in the documentation have also been updated to show their use.
- The unit tests have been throughly updated. In addition to testing dimensions and classes, they are now also testing for exact values of estimated coefficients for each of the methods. The test coverage is now 99 % according to the [code coverage report](https://codecov.io/gh/osorensen/hdme?branch=master).
- I have also updated the manuscript according to the comments of @dirmeier in [this issue](https://github.com/osorensen/hdme/issues/26).

**Comment by dirmeier** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01404/joss.01404/10.21105.joss.01404.pdf)

**Comment by dirmeier** [comment]
Hello, I think the `fit_gmus` and `fit_corrected_lasso` need to be updated to `gmus` and ` corrected_lasso` in the manuscript. Other than that, I think we are done with the review from my side. Great package!

**Comment by osorensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01404/joss.01404/10.21105.joss.01404.pdf)

**Comment by osorensen** [comment]
Thanks @dirmeier, `fit_gmus` and `fit_corrected_lasso` are now updated.

**Comment by csoneson** [comment]
@osorensen - thanks for updating the package, and @dirmeier - thanks for letting us know that you are happy with the submission! Although @dmbates has already checked all the boxes in the checklist, I would like to get a confirmation that he is also satisfied with the additions prompted by his comments above, before we move on to the next stage.

**Comment by dmbates** [comment]
The modified version has addressed my concerns.

**Comment by csoneson** [comment]
Thank you @dmbates!

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01404/joss.01404/10.21105.joss.01404.pdf)

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1214/12-AOS1018 is OK
- 10.1111/j.2517-6161.1996.tb02080.x is OK
- 10.1007/978-3-642-20192-9 is OK
- 10.1214/009053606000001523 is OK
- 10.1093/biomet/asp013 is OK
- 10.1214/10-AOS793 is OK
- 10.1080/10618600.2018.1425626 is OK
- 10.1016/j.csda.2013.02.005 is OK
- 10.1038/nrc3721 is OK
- 10.5705/ss.2013.180 is OK
- 10.1177/0962280217734241 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@osorensen - I had another look through your paper, and there are a few small things that should be fixed before acceptance:
* A typo in the first paragraph: satisifaction -> satisfaction
* The Eddelbuettel & Sanderson reference is missing the journal name
* For both Sørensen et al papers, there is no first name initial for the first author
* I would suggest being consistent with the use of journal abbreviations (either for all references, or for none of them)

In addition, please tag a release in your GitHub repository, generate a corresponding Zenodo archive, and report the Zenodo DOI back here. The title and authors of the Zenodo archive should match those of the paper.

**Comment by osorensen** [comment]
@csoneson - I have now fixed the points above. For the fourth point, I chose to consistently use full journal names. I have generated a release, with version number 0.3.0, and it has Zenodo DOI  10.5281/zenodo.2939896.

**Comment by osorensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01404/joss.01404/10.21105.joss.01404.pdf)

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1214/12-AOS1018 is OK
- 10.1111/j.2517-6161.1996.tb02080.x is OK
- 10.1007/978-3-642-20192-9 is OK
- 10.1214/009053606000001523 is OK
- 10.1093/biomet/asp013 is OK
- 10.1214/10-AOS793 is OK
- 10.1080/10618600.2018.1425626 is OK
- 10.1016/j.csda.2013.02.005 is OK
- 10.1038/nrc3721 is OK
- 10.5705/ss.2013.180 is OK
- 10.1177/0962280217734241 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@whedon set 10.5281/zenodo.2939896 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2939896" target="_blank">10.5281/zenodo.2939896</a> is the archive.

**Comment by csoneson** [comment]
@whedon set 0.3.0 as version

**Comment by whedon** [comment]
OK. 0.3.0 is the version.

**Comment by csoneson** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1214/12-AOS1018 is OK
- 10.1111/j.2517-6161.1996.tb02080.x is OK
- 10.1007/978-3-642-20192-9 is OK
- 10.1214/009053606000001523 is OK
- 10.1093/biomet/asp013 is OK
- 10.1214/10-AOS793 is OK
- 10.1080/10618600.2018.1425626 is OK
- 10.1016/j.csda.2013.02.005 is OK
- 10.1038/nrc3721 is OK
- 10.5705/ss.2013.180 is OK
- 10.1177/0962280217734241 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/697

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/697, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by csoneson** [comment]
@openjournals/joss-eics - I think we are done here! @dirmeier, @dmbates - thanks a lot for reviewing!

**Comment by labarba** [comment]
@osorensen — quick suggestion: you may want to add your ORCID to the Zenodo archive metadata.

**Comment by osorensen** [comment]
@labarba - thanks, my ORCID is now added.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1214/12-AOS1018 is OK
- 10.1111/j.2517-6161.1996.tb02080.x is OK
- 10.1007/978-3-642-20192-9 is OK
- 10.1214/009053606000001523 is OK
- 10.1093/biomet/asp013 is OK
- 10.1214/10-AOS793 is OK
- 10.1080/10618600.2018.1425626 is OK
- 10.1016/j.csda.2013.02.005 is OK
- 10.1038/nrc3721 is OK
- 10.5705/ss.2013.180 is OK
- 10.1177/0962280217734241 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/698

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/698, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
Posted to the Twitters: https://twitter.com/JOSS_TheOJ/status/1130203379832172553

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/699
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01404](https://doi.org/10.21105/joss.01404)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@dirmeier, @dmbates -  many thanks for your reviews here and to @csoneson for editing this submission ✨ 

@osorensen - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01404/status.svg)](https://doi.org/10.21105/joss.01404)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01404">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01404/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01404/status.svg
   :target: https://doi.org/10.21105/joss.01404
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01404/status.svg)](https://doi.org/10.21105/joss.01404)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
