### ISSUE TITLE
[PRE REVIEW]: insight: Easy Access to Model Information for Various Model Objects

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1405]
**Submitting author:** @strengejacke (<a href="http://orcid.org/0000-0002-8895-3206">Daniel Lüdecke</a>)
**Repository:** <a href="https://github.com/easystats/insight" target ="_blank">https://github.com/easystats/insight</a>
**Version:** 0.2.1
**Editor:** @karthik
**Reviewers:** @alexpghayes

**Author instructions**

Thanks for submitting your paper to JOSS @strengejacke. The JOSS editor @alexhanna, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@strengejacke if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @alexhanna it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@alexhanna) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1405 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @alexhanna - this submission suggested you as the editor - is this ok with you?

**Comment by danielskatz** [comment]
@strengejacke - I don't see a paper.bib file in your repo - please see https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography for an example of how the paper.md and paper.bib work together

**Comment by strengejacke** [comment]
Thanks @danielskatz for starting the pre-review. Actually, the package is more "technical" and does not implement methods proposed in (statistical) papers... That's why we haven't included a bibliography. If it's required, we could at least cite the R-software, if this is OK for you?

**Comment by danielskatz** [comment]
yes, please do - it seems that we expect something ...

**Comment by strengejacke** [comment]
Ok, bibliography added.
Suggested reviewers, with no preferred order:

@amoeba 
@cschwem2er
@Ohlsen
@jsta 
@corybrunson

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01405/joss.01405/10.21105.joss.01405.pdf)

**Comment by danielskatz** [comment]
Ok, it looks like you don't actually have to cite anything, but you do need a paper.bib file.
If you want to cite R, you will need to put a reference to it in the paper.md file - see the example for how to do this.  If not, I guess it's fine, but it's a bit odd to have a paper about research software that has no citations of previous work.  The reviewers can discuss this issue...
(If you do make changes, you can regenerate the PDF by adding a new comment here containing ```@whedon generate pdf```)

**Comment by strengejacke** [comment]
I have cited R in the appropriate place, but indeed I forgot a _References_ heading at the end...

**Comment by strengejacke** [comment]
@whedon genrate pdf

I will also discuss with the co-authors if and where it makes sense to add references.

**Comment by strengejacke** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01405/joss.01405/10.21105.joss.01405.pdf)

**Comment by alexhanna** [comment]
@danielskatz -- I'm not sure I'm the best editor for this, but will handle it if there's no better fit.

**Comment by karthik** [comment]
Sure I can.

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by karthik** [comment]
@whedon assign @alexpghayes as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @alexpghayes

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1412. Feel free to close this issue now!
