### ISSUE TITLE
[PRE REVIEW]: fmcmc: A friendly MCMC framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1406]
**Submitting author:** @gvegayon (<a href="http://orcid.org/0000-0002-3171-0844">George Vega Yon</a>)
**Repository:** <a href="https://github.com/USCbiostats/fmcmc" target ="_blank">https://github.com/USCbiostats/fmcmc</a>
**Version:** 0.1-0
**Editor:** @arokem
**Reviewers:** fabian-s

**Author instructions**

Thanks for submitting your paper to JOSS @gvegayon. **Currently, there isn't an JOSS editor assigned** to your paper.

@gvegayon if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01406/joss.01406/10.21105.joss.01406.pdf)

**Comment by danielskatz** [comment]
👋 @arokem - would you be able to edit this submission?

**Comment by danielskatz** [comment]
👋 @arokem - ping...

**Comment by arokem** [comment]
@whedon assign arokem as editor

**Comment by whedon** [comment]
OK, the editor is arokem

**Comment by arokem** [comment]
@gvegayon : do you have any suggestion for potential reviewers?

**Comment by gvegayon** [comment]
:wave: @arokem and @danielskatz ! I do have a couple in mind. Will check with my coauthor (@pmarjora) and get back to you today/tomorrow. Thanks!

**Comment by gvegayon** [comment]
Hey, we think @pboesu and @fabian-s would be great reviewers :)

**Comment by arokem** [comment]
👋 @pboesu : would you be willing to review this article for [JOSS](http://joss.theoj.org/)?

**Comment by arokem** [comment]
👋 @fabian-s: would you be willing to review this article for [JOSS](http://joss.theoj.org)?

**Comment by fabian-s** [comment]
yes

**Comment by arokem** [comment]
@whedon assign fabian-s as reviewer

**Comment by whedon** [comment]
OK, the reviewer is fabian-s

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1427. Feel free to close this issue now!

**Comment by arokem** [comment]
Super! Thanks for pitching in. I will close this issue now. Please head over to #1427 for your reviewer checklist.
