### ISSUE TITLE
[REVIEW]: vbvs.concurrent: Fitting Methods for the Functional Linear Concurrent Model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#141]
**Submitting author:** @jeff-goldsmith (<a href="http://orcid.org/0000-0002-6150-8997">Jeff Goldsmith</a>)
**Repository:** <a href="https://github.com/jeff-goldsmith/vbvs.concurrent" target ="_blank">https://github.com/jeff-goldsmith/vbvs.concurrent</a>
**Version:** v0.1
**Editor:** @cMadan
**Reviewer:** @fabian-s
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.209506" target="_blank">10.5281/zenodo.209506</a>

## Status

[![status](http://joss.theoj.org/papers/a3884174f17dbb9a695f7b8658887eff/status.svg)](http://joss.theoj.org/papers/a3884174f17dbb9a695f7b8658887eff)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/a3884174f17dbb9a695f7b8658887eff"><img src="http://joss.theoj.org/papers/a3884174f17dbb9a695f7b8658887eff/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/a3884174f17dbb9a695f7b8658887eff/status.svg)](http://joss.theoj.org/papers/a3884174f17dbb9a695f7b8658887eff)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jeff-goldsmith/vbvs.concurrent" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jeff-goldsmith/vbvs.concurrent">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1)?
- [x] **Authorship:** Has the submitting author (@jeff-goldsmith) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by cMadan** [comment]
@fabian-s - The reviewer guidelines are here: http://joss.theoj.org/about#reviewer_guidelines

For the most part you need to see if the statements above in the first post are true and check things off accordingly. If something isn't the case, or you otherwise have a suggestion, either post a comment to @jeff-goldsmith here (or ask me) or make an issue in the project's repository (https://github.com/jeff-goldsmith/vbvs.concurrent) and we'll sort things out until the submission meets JOSS' guidelines.

**Comment by fabian-s** [comment]
@jeff-goldsmith:

- In paper.md:
    - typo: line 20: "subjct"
    - please add author and affiliation
    - please add DOI for Wrobel, Park, Staicu, Goldsmith (2016)
- the shiny app does not show CIs for the estimated coefficient functions -- please correct the description of the plot given by `plot_shiny`.

**Comment by jeff-goldsmith** [comment]
@fabian-s: thanks for the quick review!

> - In paper.md:
>   - typo: line 20: "subjct"
>   - please add author and affiliation
>   - please add DOI for Wrobel, Park, Staicu, Goldsmith (2016)

the first and third of these are addressed in jeff-goldsmith/vbvs.concurrent@d550ab78ab1aa0f8ca4fea1f9951984bbd3f33ab. 

the second seems to be an issue with the default latex template in rstudio, which may not support the header requested by JOSS; perhaps @cMadan can comment?

> - the shiny app does not show CIs for the estimated coefficient functions -- please correct the description of the plot given by `plot_shiny`.

great catch! this is addressed in refunders/refund.shiny@e147d70c88fc4f4f061bbc77d891ce31562021c8.

**Comment by cMadan** [comment]
@jeff-goldsmith - I looked at the paper.md (https://raw.githubusercontent.com/jeff-goldsmith/vbvs.concurrent/master/paper.md) and I think you're okay. A few other recent accepted submissions similarly didn't have separate author/affiliation sections in the header, so it should compile fine.

**Comment by cMadan** [comment]
@fabian-s - it looks like the submission is all set?

@jeff-goldsmith - if everything is all set, the last thing we'll need is for the repo to be archived in figshare or zenodo (and the DOI for the archive)

**Comment by fabian-s** [comment]
@cMadan @jeff-goldsmith  : yup, seems fine. merry christmas y'all :santa:

**Comment by cMadan** [comment]
@fabian-s - you're all done, but I still need the DOI for the archive from @jeff-goldsmith

**Comment by jeff-goldsmith** [comment]
@cMadan - DOI for the archive is doi.org/10.5281/zenodo.209506

thanks for an easy review process!

**Comment by cMadan** [comment]
@whedon set 10.5281/zenodo.209506 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.209506" target="_blank">10.5281/zenodo.209506</a> is the archive.

**Comment by cMadan** [comment]
@jeff-goldsmith - thank YOU for the great submission! :)

@arfon - I think we're all set to accept here :)

**Comment by arfon** [comment]
@fabian-s many thanks for the review here :zap: and thanks to @cMadan for editing this one! ✨ 

@jeff-goldsmith - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00141 ⚡️ 🚀 💥
