### ISSUE TITLE
[REVIEW]: “Blaster” – a graphical user interface for common sequences analysis tools

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1411]
**Submitting author:** @snowformatics (<a href="http://orcid.org/0000-0003-0536-835X">Stefanie Lueck</a>)
**Repository:** <a href="https://github.com/snowformatics/BlasterQt" target ="_blank">https://github.com/snowformatics/BlasterQt</a>
**Version:** v.1.2.4
**Editor:** @lpantano
**Reviewer:** @vbarrera
**Archive:** <a href="https://doi.org/10.5281/zenodo.3576574" target="_blank">10.5281/zenodo.3576574</a>

## Status

[![status](http://joss.theoj.org/papers/433b8bfbc78479593962f8d5bddf5af7/status.svg)](http://joss.theoj.org/papers/433b8bfbc78479593962f8d5bddf5af7)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/433b8bfbc78479593962f8d5bddf5af7"><img src="http://joss.theoj.org/papers/433b8bfbc78479593962f8d5bddf5af7/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/433b8bfbc78479593962f8d5bddf5af7/status.svg)](http://joss.theoj.org/papers/433b8bfbc78479593962f8d5bddf5af7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/snowformatics/BlasterQt" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@vbarrera, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/snowformatics/BlasterQt">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v.1.2.4)?
- [x] **Authorship:** Has the submitting author (@snowformatics) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @vbarrera it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01411/joss.01411/10.21105.joss.01411.pdf)

**Comment by kyleniemeyer** [comment]
Hello @vbarrera, just wanted to check on your review.

**Comment by vbarrera** [comment]
Hi @kyleniemeyer.
Sorry for the radio silence.
I've been having some issues with some parts of the app. I'll be adding my notes this week.

**Comment by vbarrera** [comment]
Initial submitted issues:
https://github.com/snowformatics/BlasterQt/issues/12
https://github.com/snowformatics/BlasterQt/issues/11
https://github.com/snowformatics/BlasterQt/issues/10
https://github.com/snowformatics/BlasterQt/issues/9
https://github.com/snowformatics/BlasterQt/issues/4

**Comment by lpantano** [comment]
Hi @snowformatics, just wondering if you have seen the reviewer's comment and you have any question on your side.

**Comment by snowformatics** [comment]
Hi Lorena,

I apologize for my silence and I thank Victor for his very constructive and
helpful review, I think all points could be addressed and fixed. I have a
question, what is the deadline for fixing the bugs? I am currently moving
with baby and it's a bit complicated. Of course I will try ASAP to submit a
new version but I am not done yet.

Thanks for your understanding
Stefanie




Lorena Pantano <notifications@github.com> schrieb am Do., 20. Juni 2019,
17:32:

**Comment by lpantano** [comment]
No worries, whenever you have time, we just need to know you are aware :)

**Comment by labarba** [comment]
@snowformatics — Could we have a status update on your revisions? I see you were moving back in June, but hopefully things have settled for you. If not, and you will need extended time to work on your submission, it would help if you let us know and we can add the "paused" label here.

**Comment by snowformatics** [comment]
Dear Lorena,

I apologize for my silence. I am working on the revision but the movement
took much longer then expected.  Since yesterday we are settled and now I
am going to work more often on the software.  A paused label would be very
helpful,  I put myself a deadline for end of August.

Thanks for your understanding and tolerance

Stefanie

Am So., 4. Aug. 2019, 13:04 hat Lorena A. Barba <notifications@github.com>
geschrieben:

**Comment by labarba** [comment]
@whedon remind @snowformatics in 26 days

**Comment by whedon** [comment]
Reminder set for @snowformatics in 26 days

**Comment by snowformatics** [comment]
Dear reviewers,

I fixed and closed all issues except of two (snowformatics/BlasterQt#12
<https://github.com/snowformatics/BlasterQt/issues/12> and
snowformatics/BlasterQt#4
<https://github.com/snowformatics/BlasterQt/issues/4>) because I can not
reproduce the bugs.

@vbarrera <https://github.com/vbarrera>  would it be possible to sent me
the sequences which causes the problems?

Thank you very much in advance and again sorry for the late reply

Cheers

Am Mo., 5. Aug. 2019 um 19:27 Uhr schrieb whedon <notifications@github.com>:

**Comment by whedon** [comment]
:wave: @snowformatics, please update us on how things are progressing here.

**Comment by vbarrera** [comment]
@snowformatics Is the binary updated? I wanted to try the new features and confirm the other issues with the most updated one. Thanks.

Also @labarba and @lpantano, I'll be away for 3 weeks starting next week. Should be paused the review?

**Comment by snowformatics** [comment]
The binary is not updated yet, I will do it next week.

I have no problem with pausing the review.



Am Mi., 4. Sep. 2019, 00:45 hat Victor Barrera <notifications@github.com>
geschrieben:

**Comment by lpantano** [comment]
@vbarrera , @snowformatics , it is ok to unpause this and continue with the review?

**Comment by snowformatics** [comment]
I am fine with unpausing, should I create a new binary nevertheless of 2
open issues?

Am Fr., 18. Okt. 2019, 13:45 hat Lorena Pantano <notifications@github.com>
geschrieben:

**Comment by vbarrera** [comment]
Hi.
I'm good with unpausing too. 

@snowformatics It would be helpful if you create the new binary with the updated version. 
I'll reevaluate all issues and close them if they're no longer happening.
Thank you.

**Comment by snowformatics** [comment]
Hi,

I created a new binary:

https://sourceforge.net/projects/blasterqt/files/BlasterQtv1.3.exe/download

Best regards
Stefanie

**Comment by vbarrera** [comment]
Hi,
Thank you very much for creating the new binary.

I've been testing the new version and I've found the following issues:
- Added a comment to the DB database management:
https://github.com/snowformatics/BlasterQt/issues/10#issuecomment-549142471
- Comment on Documentation:
https://github.com/snowformatics/BlasterQt/issues/11#issuecomment-549154709
- https://github.com/snowformatics/BlasterQt/issues/13
- https://github.com/snowformatics/BlasterQt/issues/14
-  https://github.com/snowformatics/BlasterQt/issues/15
- https://github.com/snowformatics/BlasterQt/issues/16
- https://github.com/snowformatics/BlasterQt/issues/17
- https://github.com/snowformatics/BlasterQt/issues/18
- https://github.com/snowformatics/BlasterQt/issues/19

Best regards

**Comment by snowformatics** [comment]
Hi,

thank you very much for extensively testing, reporting bugs and improvements. 
I created an new binary of Version 1.4 :
https://sourceforge.net/projects/blasterqt/files/BlasterQtv1.4.exe/download

Best regards
Stefanie

**Comment by danielskatz** [comment]
👋 @lpantano - just checking in on this review, where I can't quite tell what's blocking progress...

**Comment by lpantano** [comment]
Hi @danielskatz , the reviewer is finishing the last round.Thanks.

**Comment by vbarrera** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by vbarrera** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by vbarrera** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1016/S0022-2836(05)80360-2 is OK
- 10.1186/gb-2009-10-3-r25 is OK
- 10.1007/978-1-4020-6754-9_3188 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01411/joss.01411/10.21105.joss.01411.pdf)

**Comment by vbarrera** [comment]
@snowformatics 
Thanks for solving all the issues.
Software is working properly and all issues have been addressed.

Please, for the final approval, update documents to describe the latest version:
- testing_guidelines (i.e: FASTQ to FASTA is described and it's no longer a functionality of the software).
- update README to include those changes.
- update manual to include changes. Also, non English word detected (i.e: Inhaltsverzeichnis). (minor edit).
- All texts/links make reference to v.1.2.4 
- Although references are included in the text, they don't appear in the reference section of the paper (minor edit).

Best regards,

**Comment by snowformatics** [comment]
@vbarrera 

Thank you very much for reviewing the manuscript and your patience, I think the software got major improvements.
I updated the documents and fixed the reference issue. 

Best regards
Stefanie

**Comment by lpantano** [comment]
@vbarrera can you confirm all is good now?

**Comment by vbarrera** [comment]
Yes. All good.

**Comment by lpantano** [comment]
Thank you! @snowformatics could you make a Zenodo archive from the current github version. The tittle and authors should match the paper exactly. Let me know if you have any question.

**Comment by snowformatics** [comment]
Hi Lorena,

I have created an archive with DOI at our institute repository system, is
this ok for you? Otherwise I could create a Zenodo archive, no problem.

http://dx.doi.org/10.5447/IPK/2019/23

Am So., 15. Dez. 2019 um 17:09 Uhr schrieb Lorena Pantano <
notifications@github.com>:

**Comment by snowformatics** [comment]
I just realized that's not the same title, so I will create a  Zenodo archive.

**Comment by snowformatics** [comment]
Zenodo archive:
https://zenodo.org/record/3576466#.XfaAvehKhPY

**Comment by lpantano** [comment]
Thanks for the quick reply. Sadly, the zenodo needs to contains all the code in this repo. You can link zenodo with the GitHub code, and every time you do a release it would create an archive version. When you do the link you need to modify the title an author but that's all. Or you can repeat what you did here, but it needs to be the full repository. I hope this is ok with you. Sorry to not have explained better before.

**Comment by snowformatics** [comment]
Oh  I am sorry, here we go:

https://zenodo.org/record/3576574#.XfaUfOhKhPY

Hope that's ok now.

**Comment by lpantano** [comment]
@whedon set 10.5281/zenodo.3576574 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3576574" target="_blank">10.5281/zenodo.3576574</a> is the archive.

**Comment by lpantano** [comment]
@openjournals/joss-eics, I think this is ready for you.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1016/S0022-2836(05)80360-2 is OK
- 10.1186/gb-2009-10-3-r25 is OK
- 10.1007/978-1-4020-6754-9_3188 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1184

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1184, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1207322197527797763) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1185
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01411](https://doi.org/10.21105/joss.01411)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@vbarrera - many thanks for your review and to @lpantano for editing this submission ✨ 

@snowformatics - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by arfon** [comment]
I'm going to leave this issue open until the PDF is rendering properly on the JOSS site (this looks to be a GitHub pages issue)

**Comment by snowformatics** [comment]
Thanks to everyone and merry Christmas!

**Comment by arfon** [comment]
> I'm going to leave this issue open until the PDF is rendering properly on the JOSS site (this looks to be a GitHub pages issue)

Looks like this is working now.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01411/status.svg)](https://doi.org/10.21105/joss.01411)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01411">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01411/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01411/status.svg
   :target: https://doi.org/10.21105/joss.01411
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01411/status.svg)](https://doi.org/10.21105/joss.01411)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
