### ISSUE TITLE
[REVIEW]: anesthetic: nested sampling visualisation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1414]
**Submitting author:** @williamjameshandley (<a href="http://orcid.org/0000-0002-5866-0445">Will Handley</a>)
**Repository:** <a href="https://github.com/williamjameshandley/anesthetic" target ="_blank">https://github.com/williamjameshandley/anesthetic</a>
**Version:** 1.0.2
**Editor:** @xuanxu
**Reviewer:** @tacaswell
**Archive:** <a href="https://doi.org/10.5281/zenodo.2762773" target="_blank">10.5281/zenodo.2762773</a>

## Status

[![status](http://joss.theoj.org/papers/8c51bffda75d122cf4a8b991e18d3e45/status.svg)](http://joss.theoj.org/papers/8c51bffda75d122cf4a8b991e18d3e45)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/8c51bffda75d122cf4a8b991e18d3e45"><img src="http://joss.theoj.org/papers/8c51bffda75d122cf4a8b991e18d3e45/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/8c51bffda75d122cf4a8b991e18d3e45/status.svg)](http://joss.theoj.org/papers/8c51bffda75d122cf4a8b991e18d3e45)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/williamjameshandley/anesthetic" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@tacaswell, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @xuanxu know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/williamjameshandley/anesthetic">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.0.2
- [x] **Authorship:** Has the submitting author (@williamjameshandley) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @tacaswell it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01414/joss.01414/10.21105.joss.01414.pdf)

**Comment by tacaswell** [comment]
- version: there is a 1.0.0 on pypi and a 1.0.0 tag, however there is also a 1.0.1 on pypi, no corosponding tag and ~15 commits on master past the tag. 
(https://github.com/williamjameshandley/anesthetic/compare/1.0.0...master).  It looks like there is 1 bug fix and the rest are do
 - Installation: discovered that `fastkde` did not declare it's setup dependencies correctly, opened an issue on their side (https://bitbucket.org/lbl-cascade/fastkde/issues/7/use-setup_requires-and-install_requires-in)
 - the 1D plots don't have yaxis ticks / label.  Is that expected?  (I am concerned that that is actually a Matplotlib bug...)

I recommend publication provisional on the 1.0.0 vs 1.0.1 issue being addressed and confirmation that there should be no y-labels on some of the plots.

**Comment by williamjameshandley** [comment]
Many thanks @tacaswell 

> version: there is a 1.0.0 on pypi and a 1.0.0 tag, however there is also a 1.0.1 on pypi, no corosponding tag and ~15 commits on master past the tag.
(williamjameshandley/anesthetic@1.0.0...master). It looks like there is 1 bug fix and the rest are documentation.
Indeed. I spotted a minor error in the anesthetic script, and updated the documentation.

>Installation: discovered that fastkde did not declare it's setup dependencies correctly, opened an issue on their side (https://bitbucket.org/lbl-cascade/fastkde/issues/7/use-setup_requires-and-install_requires-in)
Great, thank you very much for this.

> the 1D plots don't have yaxis ticks / label. Is that expected? (I am concerned that that is actually a Matplotlib bug...)
This is an anesthetic feature rather than a  matplotlib bug, since the 1D posterior plots are normalised to have peaks at the same height (as is the usual convention for these kind of triangle plots)

**Comment by tacaswell** [comment]
I recommend acceptance

@￼xuanxu what is the next step here?

**Comment by xuanxu** [comment]
Thanks @tacaswell, I'll take it from here!

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01414/joss.01414/10.21105.joss.01414.pdf)

**Comment by xuanxu** [comment]
@whedon set 1.0.1 as version

**Comment by whedon** [comment]
OK. 1.0.1 is the version.

**Comment by xuanxu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1214/06-BA127 is OK
- 10.1080/00107510802066753 is OK
- 10.1111/j.1365-2966.2009.14548.x is OK
- 10.1093/mnrasl/slv047 is OK
- 10.1093/mnras/stv1911 is OK
- 10.21105/joss.00965 is OK
- 10.5281/zenodo.2648394 is OK
- 10.21105/joss.00046 is OK
- 10.21105/joss.00024 is OK
- 10.1214/aoms/1177729694 is OK
- 10.1016/j.ascom.2015.05.005 is OK
- 10.1103/PhysRevD.66.103511 is OK
- https://doi.org/10.1016/j.csda.2016.02.014 is OK
- 10.25080/Majora-4af1f417-011 is OK

MISSING DOIs

- https://doi.org/10.2307/2334940 may be missing for title: Monte Carlo Sampling Methods Using Markov Chains and Their Applications
- https://doi.org/10.18637/jss.v086.i07 may be missing for title: DNest4: Diffusive Nested Sampling in C++ and Python
- https://doi.org/10.1016/j.dark.2018.100260 may be missing for title: MontePython 3: boosted MCMC sampler and other features
- https://doi.org/10.1140/epjc/s10052-017-5274-y may be missing for title: Comparison of statistical sampling methods with ScannerBit, the GAMBIT scanning module

INVALID DOIs

- None
```

**Comment by xuanxu** [comment]
@williamjameshandley:
- There are some references without DOI, could you add the missing DOIs (see [prev comment](https://github.com/openjournals/joss-reviews/issues/1414#issuecomment-491255323)) to the `paper.bib` file?

- The paper mentions version 1.0.0, I've updated the version for the submission to 1.0.1, and created a PR in your repo to update that.

Once you do these minor changes I'll need you to create a Zenodo archive, and report the DOI here, please.

**Comment by williamjameshandley** [comment]
@xuanxu I've merged in your changes to the paper, and added the DOIs that exist. Unfortunately there aren't any for the DNest 4 or MontePython papers, as they're only arXiv articles

**Comment by williamjameshandley** [comment]
> Once you do these minor changes I'll need you to report the new Zenodo archive's DOI here, please.

Version 1.0.1 10.5281/zenodo.2668761

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1414 with the following error: 

 Error reading bibliography ./paper.bib (line 131, column 2):
unexpected "v"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by xuanxu** [comment]
Thanks @williamjameshandley!

There is a typo in the bib file preventing the paper to compile: a missing comma, I've issued a PR in your repo fixing it. 

> Unfortunately there aren't any for the DNest 4 or MontePython papers, as they're only arXiv articles

So the DOIs [suggested by whedon](https://github.com/openjournals/joss-reviews/issues/1414#issuecomment-491255323) for them are not the right ones?

> ```
> MISSING DOIs
> 
> - https://doi.org/10.18637/jss.v086.i07 may be missing for title: DNest4: Diffusive Nested Sampling in C++ and Python
> - https://doi.org/10.1016/j.dark.2018.100260 may be missing for title: MontePython 3: boosted MCMC sampler and other features
> ```

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01414/joss.01414/10.21105.joss.01414.pdf)

**Comment by williamjameshandley** [comment]
> So the DOIs suggested by whedon for them are not the right ones?

Ah -- that's very clever, I missed the autosuggestions. I've added in the full bibtex associated with those doi links.

**Comment by xuanxu** [comment]
@williamjameshandley great!

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01414/joss.01414/10.21105.joss.01414.pdf)

**Comment by xuanxu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1214/06-BA127 is OK
- 10.1080/00107510802066753 is OK
- 10.1111/j.1365-2966.2009.14548.x is OK
- 10.1093/mnrasl/slv047 is OK
- 10.1093/mnras/stv1911 is OK
- 10.2307/2334940 is OK
- 10.18637/jss.v086.i07 is OK
- 10.1140/epjc/s10052-017-5274-y is OK
- 10.21105/joss.00965 is OK
- 10.5281/zenodo.2668761 is OK
- 10.21105/joss.00046 is OK
- 10.21105/joss.00024 is OK
- 10.1214/aoms/1177729694 is OK
- 10.1016/j.ascom.2015.05.005 is OK
- https://doi.org/10.1016/j.dark.2018.100260 is OK
- 10.1103/PhysRevD.66.103511 is OK
- https://doi.org/10.1016/j.csda.2016.02.014 is OK
- 10.25080/Majora-4af1f417-011 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by xuanxu** [comment]
@williamjameshandley Do you mind to create a new zenodo archive (and update the reference in the bib file )? 
As it is is ok because there's no changes in the code, but I'd love the reference to point to a deposit that includes the correct files for the final joss paper. WDYT?

**Comment by williamjameshandley** [comment]
Sure. 

What is the correct way to do this? I'm struggling to see how I could have a bib file with the correct doi archived in the corresponding zenodo doi, unless I use the 'all versions' doi 10.5281/zenodo.2614017

**Comment by xuanxu** [comment]
You are right. I think it's ok to have the link in the paper using the 'all versions' doi. It will redirect readers to the more recent version.
Report here the DOI of the latest version and I'll use that here in the JOSS submission.

**Comment by xuanxu** [comment]
The other option is to create a deposit and then change the bib file to point to it. That way the diference between the final paper and the deposit is minimal.
Whatever option you prefer is OK.

**Comment by williamjameshandley** [comment]
I've gone with the first option, as it works better with GitHub's syncing between releases and zenodo archives. I updated the version number to 1.0.2 in the README, paper and bib file, pushed a new pypi version, and created a new github release. The 'all versions' DOI is:

10.5281/zenodo.2614017

Many thanks @xuanxu

**Comment by xuanxu** [comment]
@williamjameshandley 👌

**Comment by xuanxu** [comment]
@whedon set 1.0.2 as version

**Comment by whedon** [comment]
OK. 1.0.2 is the version.

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01414/joss.01414/10.21105.joss.01414.pdf)

**Comment by xuanxu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1214/06-BA127 is OK
- 10.1080/00107510802066753 is OK
- 10.1111/j.1365-2966.2009.14548.x is OK
- 10.1093/mnrasl/slv047 is OK
- 10.1093/mnras/stv1911 is OK
- 10.2307/2334940 is OK
- 10.18637/jss.v086.i07 is OK
- 10.1140/epjc/s10052-017-5274-y is OK
- 10.21105/joss.00965 is OK
- 10.5281/zenodo.2614017 is OK
- 10.21105/joss.00046 is OK
- 10.21105/joss.00024 is OK
- 10.1214/aoms/1177729694 is OK
- 10.1016/j.ascom.2015.05.005 is OK
- https://doi.org/10.1016/j.dark.2018.100260 is OK
- 10.1103/PhysRevD.66.103511 is OK
- https://doi.org/10.1016/j.csda.2016.02.014 is OK
- 10.25080/Majora-4af1f417-011 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by xuanxu** [comment]
@whedon set 10.5281/zenodo.2762773 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2762773" target="_blank">10.5281/zenodo.2762773</a> is the archive.

**Comment by xuanxu** [comment]
This is ready now for publication.
Pinging EIC for final acceptance: @openjournals/joss-eics

**Comment by labarba** [comment]
@williamjameshandley — Could you edit the Zenodo archive metadata, so the title and author list matches the paper? You may also add your ORCID.

**Comment by williamjameshandley** [comment]
@labarba I believe this is now done.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1214/06-BA127 is OK
- 10.1080/00107510802066753 is OK
- 10.1111/j.1365-2966.2009.14548.x is OK
- 10.1093/mnrasl/slv047 is OK
- 10.1093/mnras/stv1911 is OK
- 10.2307/2334940 is OK
- 10.18637/jss.v086.i07 is OK
- 10.1140/epjc/s10052-017-5274-y is OK
- 10.21105/joss.00965 is OK
- 10.5281/zenodo.2614017 is OK
- 10.21105/joss.00046 is OK
- 10.21105/joss.00024 is OK
- 10.1214/aoms/1177729694 is OK
- 10.1016/j.ascom.2015.05.005 is OK
- https://doi.org/10.1016/j.dark.2018.100260 is OK
- 10.1103/PhysRevD.66.103511 is OK
- https://doi.org/10.1016/j.csda.2016.02.014 is OK
- 10.25080/Majora-4af1f417-011 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/681

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/681, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
- Use the common capitalization of: Python, NumPy, SciPy, and Matplotlib (pandas is usually not capitalized).
- Check your [citation syntax](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax). If citing two works at once, separate by semicolon to get them in the same parenthesis group.
- "Currently public available implementations" >> awkward. Maybe "Currently available public implementations"?
- "all which have been incorporated" >> all _of_ which
- on page 2, you're missing a space before citations, so the parenthesis touches the previous word
- "one and two-dimensional" >> add hyphen after "one"
- "A subset of computations from item 1 are provided" >> _is_ provided
- "the effect of adjust dynamically adjusting " >> typo

Just before the Acknowledgements, you have a link to the code repository. We include a link to the repo on the margin decorators (first page), so we ask that you don't add an additional link in the text or references. The Zenodo archive will also be linked on the first page. Can you edit those out?

The notebook is not "hosted" on Binder ... it is hosted on GitHub but Binder can build an image on request. Please reword.

**Comment by labarba** [comment]
You should add caps protection on `{mcmc}` here: https://github.com/williamjameshandley/anesthetic/blob/11ce6b382c5a528e60117adba32d71de8c993efa/paper/paper.bib#L324

**Comment by labarba** [comment]
This DOI is not resolving:
https://github.com/williamjameshandley/anesthetic/blob/11ce6b382c5a528e60117adba32d71de8c993efa/paper/paper.bib#L330

Try putting _just_ the DOI, i.e., the alphanumeric identifier, not the full URL, into the `doi` field of the `.bib` file.

**Comment by labarba** [comment]
Also, don't include the Zenodo archive in the references, as it will be provided on the margin of the first page.

**Comment by labarba** [comment]
Handley, W., & Speagle, J. (2019) — do not cite items that are not publicly available. Either upload a preprint to arXiv, or remove the citation (it is OK to mention in the text that you have some work in progress, but not to cite it).

**Comment by labarba** [comment]
We need caps protection on "Carlo" and "Markov" in this title: 
https://github.com/williamjameshandley/anesthetic/blob/11ce6b382c5a528e60117adba32d71de8c993efa/paper/paper.bib#L129

**Comment by labarba** [comment]
Did you want to preserve the capitalization on the second appearance of "PolyChord" here?
https://github.com/williamjameshandley/anesthetic/blob/11ce6b382c5a528e60117adba32d71de8c993efa/paper/paper.bib#L186

**Comment by labarba** [comment]
This DOI link is also broken:
https://github.com/williamjameshandley/anesthetic/blob/11ce6b382c5a528e60117adba32d71de8c993efa/paper/paper.bib#L360

**Comment by labarba** [comment]
Caps protection on "Bayes"
https://github.com/williamjameshandley/anesthetic/blob/11ce6b382c5a528e60117adba32d71de8c993efa/paper/paper.bib#L41

**Comment by labarba** [comment]
Let me know when all ☝️ is done.

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01414/joss.01414/10.21105.joss.01414.pdf)

**Comment by williamjameshandley** [comment]
Many thanks @labarba, I believe I've implemented all those corrections.

**Comment by williamjameshandley** [comment]
> This DOI link is also broken:
> https://github.com/williamjameshandley/anesthetic/blob/11ce6b382c5a528e60117adba32d71de8c993efa/paper/paper.bib#L360

Apologies, I missed this one. Latest push has this fixed as well.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1214/06-BA127 is OK
- 10.1080/00107510802066753 is OK
- 10.1111/j.1365-2966.2009.14548.x is OK
- 10.1093/mnrasl/slv047 is OK
- 10.1093/mnras/stv1911 is OK
- 10.2307/2334940 is OK
- 10.18637/jss.v086.i07 is OK
- 10.1140/epjc/s10052-017-5274-y is OK
- 10.21105/joss.00965 is OK
- 10.21105/joss.00046 is OK
- 10.21105/joss.00024 is OK
- 10.1214/aoms/1177729694 is OK
- 10.1016/j.ascom.2015.05.005 is OK
- 10.1016/j.dark.2018.100260 is OK
- 10.1103/PhysRevD.66.103511 is OK
- https://doi.org/10.1016/j.csda.2016.02.014 is OK
- 10.25080/Majora-4af1f417-011 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/684

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/684, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
Please accept my small edits, via PR. Note that the PDF generated above still shows one broken DOI link, but when I open the `.bib` file it looks correct. Unsure what's up.

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01414/joss.01414/10.21105.joss.01414.pdf)

**Comment by williamjameshandley** [comment]
> Please accept my small edits, via PR. Note that the PDF generated above still shows one broken DOI link, but when I open the `.bib` file it looks correct. Unsure what's up.

I'm not exactly sure which one you're referring to, but I noticed that there was an errant ``&`` in the fastKDE journal name. I changed it to ``\&`` and it seems to be resolving better, and the DOI no longer has http in front of it.

**Comment by williamjameshandley** [comment]
(Edits merged)

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1214/06-BA127 is OK
- 10.1080/00107510802066753 is OK
- 10.1111/j.1365-2966.2009.14548.x is OK
- 10.1093/mnrasl/slv047 is OK
- 10.1093/mnras/stv1911 is OK
- 10.2307/2334940 is OK
- 10.18637/jss.v086.i07 is OK
- 10.1140/epjc/s10052-017-5274-y is OK
- 10.21105/joss.00965 is OK
- 10.21105/joss.00046 is OK
- 10.21105/joss.00024 is OK
- 10.1214/aoms/1177729694 is OK
- 10.1016/j.ascom.2015.05.005 is OK
- 10.1016/j.dark.2018.100260 is OK
- 10.1103/PhysRevD.66.103511 is OK
- 10.1016/j.csda.2016.02.014 is OK
- 10.25080/Majora-4af1f417-011 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/687

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/687, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/688
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01414](https://doi.org/10.21105/joss.01414)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @williamjameshandley, your JOSS paper is published 🚀 

Huge thanks to our editor: @xuanxu, and reviewer: @tacaswell — we couldn't do this without you 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01414/status.svg)](https://doi.org/10.21105/joss.01414)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01414">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01414/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01414/status.svg
   :target: https://doi.org/10.21105/joss.01414
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01414/status.svg)](https://doi.org/10.21105/joss.01414)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by williamjameshandley** [comment]
Many thanks for all your efforts @labarba, @xuanxu and @tacaswell: I remain very impressed by the quality, efficiency and usefulness of the JOSS review process.
