### ISSUE TITLE
[PRE REVIEW]: tcherry: Learning the structure of tcherry trees

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1415]
**Submitting author:** @katrinekirkeby (<a href="http://orcid.org/0000-0001-6065-1583">Katrine Kirkeby</a>)
**Repository:** <a href="https://github.com/nvihrs14/tcherry" target ="_blank">https://github.com/nvihrs14/tcherry</a>
**Version:** 0.1.1
**Editor:** @jasonclark
**Reviewers:** @kellieotto

**Author instructions**

Thanks for submitting your paper to JOSS @katrinekirkeby. **Currently, there isn't an JOSS editor assigned** to your paper.

@katrinekirkeby if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01415/joss.01415/10.21105.joss.01415.pdf)

**Comment by danielskatz** [comment]
👋 @jasonclark - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whendon generate pdf

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01415/joss.01415/10.21105.joss.01415.pdf)

**Comment by katrinekirkeby** [comment]
Am I allowed to change the Version, if i found some small errors in the code?

**Comment by danielskatz** [comment]
of course, but you can also wait until the end of the review process in case additional changes are needed based on the reviews

**Comment by katrinekirkeby** [comment]
Okay, thanks for the quick response

**Comment by kyleniemeyer** [comment]
@whedon assign @jasonclark as editor

**Comment by whedon** [comment]
OK, the editor is @jasonclark

**Comment by jasonclark** [comment]
Hi, @katrinekirkeby. Things look in order. I'm going to look for an editor and copy you. Thanks for the submission!

**Comment by jasonclark** [comment]
Hi, @kellieotto. Would you be able to review the [tcherry](https://github.com/nvihrs14/tcherry) software in the next couple of weeks? Let me know when you have the chance. Thanks so much for considering. 

cc @katrinekirkeby

**Comment by jasonclark** [comment]
> Hi, @katrinekirkeby. Things look in order. I'm going to look for a reviewer and copy you. Thanks for the submission!

@katrinekirkeby I did see that the description, topics, and website are empty. Could you add some info there? Topics will help with searching/discoverability. An abridged description from the README will help introduce the software. If you don't have a website, no worries. The other two bits of info will provide the context as someone lands on the repo homepage. Thanks!

**Comment by kellieotto** [comment]
@jasonclark yes, I'd be happy to review.

**Comment by jasonclark** [comment]
@kellieotto Thanks for your willingness to review. I'll assign you and set up the review thread.

**Comment by jasonclark** [comment]
@whedon assign @kellieotto as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kellieotto

**Comment by jasonclark** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1480. Feel free to close this issue now!

**Comment by jasonclark** [comment]
@kellieotto The review is open at https://github.com/openjournals/joss-reviews/issues/1480. The checklist there gives you a framework to follow. If you have any questions, let me know. Thanks again for your time and expertise.

**Comment by jasonclark** [comment]
@katrinekirkeby I'm going to keep this issue open for a bit. I need you to add a description, some topics, and website information to the repo landing page. Once that is complete, I will close this pre-review issue. Thanks!

**Comment by kyleniemeyer** [comment]
@jasonclark can you try to find a second reviewer for the submission? We prefer to have at least two (even though JOSS hasn't consistently applied that expectation up until now). If it is very challenging to find another reviewer, then it's ok for the editor to serve as the second reviewer. Thanks!

**Comment by jasonclark** [comment]
Hi, @dhhagan. Would you be able to review the tcherry software in the next couple of weeks? Let me know when you have the chance. Thanks so much for considering.

cc @katrinekirkeby @labarba

**Comment by jasonclark** [comment]
Hi, @dhhagan. Are you available to review the tcherry software? Let me know when you have the chance. Thanks so much for considering.

cc @katrinekirkeby @labarba

**Comment by katrinekirkeby** [comment]
> > Hi, @katrinekirkeby. Things look in order. I'm going to look for a reviewer and copy you. Thanks for the submission!
> 
> @katrinekirkeby I did see that the description, topics, and website are empty on the repo landing page. Could you add some info there? Topics will help with searching/discoverability. An abridged description from the README will help introduce the software. If you don't have a website, no worries. The other two bits of info will provide the context as someone lands on the repo homepage. Thanks!

Hi, @jasonclark. We have now added a description and topics to the repo landing page.

**Comment by dhhagan** [comment]
@jasonclark Sorry about the delay - yup, can do it sometime this week.

**Comment by arfon** [comment]
> @jasonclark Sorry about the delay - yup, can do it sometime this week.

@dhhagan - I've added a checklist to the review over in #1480 for you.

@jasonclark - can this pre-review issue be closed now?
