### ISSUE TITLE
[PRE REVIEW]: qtl2pleio: Testing pleiotropy vs. separate QTL in multiparental populations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1416]
**Submitting author:** @fboehm (<a href="http://orcid.org/0000-0002-1644-5931">Frederick Boehm</a>)
**Repository:** <a href="https://github.com/fboehm/qtl2pleio" target ="_blank">https://github.com/fboehm/qtl2pleio</a>
**Version:** v0.1.3
**Editor:** @csoneson
**Reviewers:** @vjcitn, @rcorty

**Author instructions**

Thanks for submitting your paper to JOSS @fboehm. **Currently, there isn't an JOSS editor assigned** to your paper.

@fboehm if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01416/joss.01416/10.21105.joss.01416.pdf)

**Comment by danielskatz** [comment]
👋 bioinformatics editing team (@pjotrp @mgymrek @brainstorm @lpantano) - can one of you take on this submission as editor?

**Comment by lpantano** [comment]
Hi @danielskatz , it makes sense. we'll try to find the best one for this.

Thanks!

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
Thanks for your submission @fboehm. I will have a first look at your repository and identify suitable reviewers - please let me know if you have suggestions for people that might be good reviewers!

**Comment by fboehm** [comment]
Thanks for your assistance, @csoneson! I think that @pjotrp attended a talk that I gave about the project related to this software. I'm sure that he would be a great reviewer.

**Comment by csoneson** [comment]
👋@sirsharpest - would you be interested in reviewing this submission for JOSS? Looks like a great fit to your expertise.

**Comment by csoneson** [comment]
@fboehm - thanks for your suggestion. I noticed that @pjotrp has relatively recently published together with one of the authors of this submission, which would not be compatible with the JOSS conflict of interest statement. I have invited a couple of other great people - let's see if they are available!

**Comment by fboehm** [comment]
Ah, good point, @csoneson. Thanks for your assistance with this!

**Comment by csoneson** [comment]
@whedon assign @vjcitn as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @vjcitn

**Comment by csoneson** [comment]
Ok @fboehm, we have our first reviewer! I'd like to have one more before officially starting the review.

**Comment by fboehm** [comment]
Thanks so much, @csoneson and @vjcitn! @csoneson, is there a list of people who are certified to serve as reviewers? One person who might be willing to review is Robert Corty of U. North Carolina. I don't know if he has reviewed for JOSS yet.

**Comment by csoneson** [comment]
Thanks @fboehm - please have a look in the first post in this issue, there is a link to a list of people who have agreed to review for JOSS.

**Comment by fboehm** [comment]
Thanks for the reminder, @csoneson. In looking at the list of reviewers, it seems that @nhejazi, @rmflight, @skummerf and @dpolychr all have expertise that would be useful when reviewing my submission. Is there a way to reach out to them?

**Comment by csoneson** [comment]
@fboehm they should get a notification by being mentioned in this issue. @nhejazi, @rmflight, @skummerf, @dpolychr (and ping @SirSharpest, @rcorty) - would any of you be available and interested in reviewing this submission for JOSS?

**Comment by rmflight** [comment]
QTL testing is definitely outside my area of expertise, so I'm going to have to decline.

Good luck!

**Comment by dpolychr** [comment]
Thanks for the invitation but QTL testing is not my expertise either. Good luck with the submission and I would be happy to help out with requests that fall within my area of expertise

**Comment by rcorty** [comment]
I’d like to consider reviewing, but I can’t see the pdf on mobile.  It says the file is corrupted?

**Comment by csoneson** [comment]
Thanks @rcorty - I just checked and it works fine for me, both on the laptop and on the mobile (if I choose 'Desktop version' for GitHub on the mobile). I just pulled down the paper and sent it to you by email, if that's helpful to have a first look.

**Comment by rcorty** [comment]
Thank you — I’ll be happy to review.

**Comment by csoneson** [comment]
Excellent!

**Comment by csoneson** [comment]
@whedon add @rcorty as reviewer

**Comment by whedon** [comment]
OK, @rcorty is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1435. Feel free to close this issue now!

**Comment by csoneson** [comment]
@vjcitn, @rcorty - thanks for agreeing to review this JOSS submission! Please head over to issue #1435 for the actual review.
