### ISSUE TITLE
[REVIEW]: pymcmcstat: A Python Package for Bayesian Inference Using Delayed Rejection Adaptive Metropolis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1417]
**Submitting author:** @prmiles (<a href="http://orcid.org/0000-0002-7501-5114">Paul Miles</a>)
**Repository:** <a href="https://github.com/prmiles/pymcmcstat" target ="_blank">https://github.com/prmiles/pymcmcstat</a>
**Version:** v1.7.1
**Editor:** @katyhuff
**Reviewers:** @djmitche, @katyhuff
**Archive:** <a href="https://doi.org/10.5281/zenodo.2660145" target="_blank">10.5281/zenodo.2660145</a>

## Status

[![status](http://joss.theoj.org/papers/5ac18236dc3f11e9f46977fc43f61991/status.svg)](http://joss.theoj.org/papers/5ac18236dc3f11e9f46977fc43f61991)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/5ac18236dc3f11e9f46977fc43f61991"><img src="http://joss.theoj.org/papers/5ac18236dc3f11e9f46977fc43f61991/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/5ac18236dc3f11e9f46977fc43f61991/status.svg)](http://joss.theoj.org/papers/5ac18236dc3f11e9f46977fc43f61991)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/prmiles/pymcmcstat" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@djmitche & @jarvist, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @katyhuff know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/prmiles/pymcmcstat">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.7.1
- [x] **Authorship:** Has the submitting author (@prmiles) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/prmiles/pymcmcstat">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** v1.7.1
- [ ] **Authorship:** Has the submitting author (@prmiles) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @djmitche, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01417/joss.01417/10.21105.joss.01417.pdf)

**Comment by djmitche** [comment]
I'm happy aside from the above-referenced two issues.

While this does not have a very "pythonic" interface, that's justified in the documentation as an effort to match the MATLAB functionality, and I think will match the expectations of users of this sort of application nicely.  In particular, I'd highlight that many methods "display" data by printing to stdout rather than return it, and that running the simulation modifies the MCMC object itself, from which results must be fetched, rather than leaving the object unchanged and returning the simulation results.    It seems that the displayed results are also available programmatically if necessary (e.g., ModelSettings), so this would not be an impediment to using the library as a component of a larger application.

**Comment by katyhuff** [comment]
Thank you @djmitche for your prompt review! You've made some very good points that perhaps @prmiles could consider as improvements to the package!

**Comment by prmiles** [comment]
Thank you @djmitche for your comments regarding the pymcmcstat package.  I have resolved the two issues you reported.

**Comment by djmitche** [comment]
Indeed!  All boxes checked..

**Comment by djmitche** [comment]
@jarvist ping!

**Comment by katyhuff** [comment]
@jarvist : Do you still intend to complete this review?

**Comment by katyhuff** [comment]
Sorry for the delay here @prmiles. I've  to the prompt and thorough review by @djmitche Without the review  from @jarvist, I'll move forward with this review  on my own, as I have previously installed and checked the software myself. I'll review all the checks today and we can move forward.


## Review checklist for @jarvist
### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/prmiles/pymcmcstat">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v1.7.0)?
- [ ] **Authorship:** Has the submitting author (@prmiles) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01417/joss.01417/10.21105.joss.01417.pdf)

**Comment by katyhuff** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/s11222-008-9110-y is OK
- 10.1007/s11222-006-9438-0 is OK
- 10.1198/jcgs.2009.06134 is OK
- 10.5281/zenodo.2630882 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by katyhuff** [comment]
Thank you @djmitche for your review -- we couldn't do this without you.

Thank you @prmiles for a strong submission and for engaging actively in the review process! I have looked over the paper, double checked all the DOI links, and have conducted a high level review of the code itself. Everything looks ship-shape to me. At this point, please double check the paper yourself, review any lingering details in your code/readme/etc. that you intend to make, and then make an archive of the reviewed software in Zenodo/figshare/other service. Please be sure that the DOI metadata (title, authors, etc.) matches this JOSS submission. You may update the version to reflect these changes as necessary. If you do need to update the version please let me know the new version number. Once that's complete, please update this thread with the DOI of the archive, and I'll move forward with accepting the submission! Until then, now is your moment for final touchups!

**Comment by katyhuff** [comment]
@whedon remove @jarvist as reviewer

**Comment by whedon** [comment]
OK, @jarvist is no longer a reviewer

**Comment by katyhuff** [comment]
@whedon add @katyhuff as reviewer

**Comment by whedon** [comment]
OK, @katyhuff is now a reviewer

**Comment by prmiles** [comment]
The updated DOI is [10.5281/zenodo.2660145](http://doi.org/10.5281/zenodo.2660145).  This corresponds to version 1.7.1, which includes the corrections requested by @djmitche 

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.2660145.svg)](https://doi.org/10.5281/zenodo.2660145)

I fixed several items in the paper and I am completing my final touch-ups.  I'll let you know as soon as they are complete.  Thank you!

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01417/joss.01417/10.21105.joss.01417.pdf)

**Comment by prmiles** [comment]
I have completed my final touchups.  However, I noticed in the article proof that the "Archive" link under "Software" does not appear to be working.  The "Review" and "Repository" links appear to be working, so I figured I would ask.  Thanks!

**Comment by katyhuff** [comment]
That's part of the following steps.
Never fear.

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01417/joss.01417/10.21105.joss.01417.pdf)

**Comment by katyhuff** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/s11222-008-9110-y is OK
- 10.1007/s11222-006-9438-0 is OK
- 10.1198/jcgs.2009.06134 is OK
- 10.5281/zenodo.2660145 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by katyhuff** [comment]
@whedon set v1.7.1 as version

**Comment by whedon** [comment]
OK. v1.7.1 is the version.

**Comment by katyhuff** [comment]
@whedon set 10.5281/zenodo.2660145 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2660145" target="_blank">10.5281/zenodo.2660145</a> is the archive.

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01417/joss.01417/10.21105.joss.01417.pdf)

**Comment by katyhuff** [comment]
@openjournals/joss-eics I believe this paper is ready for acceptance!

**Comment by labarba** [comment]
@prmiles — Could you edit the Zenodo archive metadata, so the title matches the paper? You may want to add your ORCID, also.

**Comment by katyhuff** [comment]
Whoops! Sorry I missed this @labarba. Thank you for catching it.

**Comment by prmiles** [comment]
I have updated the Zenodo archive metadata title such that it matches the paper.

Regarding the ORCID, I have linked it to my Zenodo account.  Is that what you are requesting?  The ORCiD is in the markdown file for the paper as well.  I believe I formatted it correctly.

Thank you!

**Comment by prmiles** [comment]
I added my ORCiD as part of the Zenodo metadata.  Sorry for my confusion!

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/s11222-008-9110-y is OK
- 10.1007/s11222-006-9438-0 is OK
- 10.1198/jcgs.2009.06134 is OK
- 10.5281/zenodo.2660145 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/734

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/734, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
Folks, I read the paper and I find it awfully hard ... I mean, it really is full of jargon and acronyms. Nobody commented on that during the review? JOSS does say in the Author guidelines that the article should be written aimed at a non-specialist technical audience. Do you want to give this a new look?

**Comment by prmiles** [comment]
I apologize for the confusion regarding the intended audience.  I am happy to update the paper to communicate with a non-specialist technical audience, but I will need a few days to do this effectively.  Assuming the other reviewers are in agreement, I will begin updating the paper and hopefully have it ready by Monday.  Thank you for the feedback.

**Comment by labarba** [comment]
The [relevant section](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) of our documentation says:

> JOSS welcomes submissions from broadly diverse research areas. For this reason, we require that authors include in the paper some sentences that would explain the software functionality and domain of use to a non-specialist reader. 

I really appreciate your willingness to give this another pass. It benefits JOSS and all our community if we try to communicate better about the software we're publishing. (And it's hard work to write about technical topics without jargon.)

**Comment by katyhuff** [comment]
@labarba Thanks for this feedback. I did find it readable, but likely because I am quite familiar with this area of application. I'll be more careful about this jargon-blindness in the future.

@prmiles Thank you for being willing to make these changes. In addition to a reduction of acronyms, perhaps moving the 4th paragraph closer to the beginning of the paper would help to provide a softer onramp for the reader.

**Comment by prmiles** [comment]
@katyhuff Thank you for the suggestion regarding the 4th paragraph!  I'm grateful the issue was brought up, and thank you for your patience as I make the updates.

**Comment by djmitche** [comment]
I'll look more closely at that in future reviews.  I did have to do a bit of background reading to understand the purpose of the package.

**Comment by prmiles** [comment]
I have modified the paper to accommodate a more general technical audience.  The first couple paragraphs provide a broad perspective of why the software is useful and where it can be used in scientific research (hopefully!).   My hope is that the first part of the paper gives the reader the big picture and enough information to know whether or not they could use the software.

The latter part of the paper still contains fairly technical content.  I added some discussion regarding Metropolis algorithms, and I believe the references provide a reasonable set of resources if someone wants to learn more about MCMC methods.

Ideally, the first part of the paper makes the technical content less overwhelming, but I am happy to continue iterating.  Thank you again for the feedback regarding the paper!

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01417/joss.01417/10.21105.joss.01417.pdf)

**Comment by labarba** [comment]
Please delete the last sentence before the acknowledgements, and the citation to the Zenodo deposit. We ask that you don't include this as a citation, because the archive will be highlighted in the margin decorators on the first page of the paper (and the DOIs will be linked in the metadata of the paper).

**Comment by prmiles** [comment]
I have removed the final sentence, including the citation to the Zenodo deposit.  I also removed the Zenodo information from the .bib file.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/s11222-008-9110-y is OK
- 10.1007/s11222-006-9438-0 is OK
- 10.1198/jcgs.2009.06134 is OK
- 10.5281/zenodo.2660145 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/738

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/738, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
Hmm. Did you forget to push the change? I still see the sentence and citation in the PDF created with the `accept` command above.

**Comment by prmiles** [comment]
The paper looks correct in the master version of my GitHub repository... I'm not entirely sure how the compiling process works with whedon.  Does whedon pull the latest version from the repository when you use the accept command?  Or only when you generate the pdf?

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01417/joss.01417/10.21105.joss.01417.pdf)

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/s11222-008-9110-y is OK
- 10.1007/s11222-006-9438-0 is OK
- 10.1198/jcgs.2009.06134 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/739

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/739, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1136716204918411264) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/740
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01417](https://doi.org/10.21105/joss.01417)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congrats, @prmiles, your paper is published!
Huge thanks to our Rditor: @katyhuff, and reviewers: @djmitche, @katyhuff

**Comment by labarba** [comment]
(Published from my phone at an airport)

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01417/status.svg)](https://doi.org/10.21105/joss.01417)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01417">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01417/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01417/status.svg
   :target: https://doi.org/10.21105/joss.01417
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01417/status.svg)](https://doi.org/10.21105/joss.01417)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by prmiles** [comment]
Thank you again for all the feedback on the paper and software!
