### ISSUE TITLE
[REVIEW]: Container Tree: Software to Model Container Filesystems, Packages, and Inheritance

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1418]
**Submitting author:** @vsoch (<a href="http://orcid.org/0000-0002-4387-3819">Vanessa Sochat</a>)
**Repository:** <a href="https://www.github.com/singularityhub/container-tree" target ="_blank">https://www.github.com/singularityhub/container-tree</a>
**Version:** 0.0.48
**Editor:** @brainstorm
**Reviewer:** @luizirber
**Archive:** <a href="https://doi.org/10.5281/zenodo.2853983" target="_blank">10.5281/zenodo.2853983</a>

## Status

[![status](http://joss.theoj.org/papers/f7b46a7f922b468e535adabc2337b330/status.svg)](http://joss.theoj.org/papers/f7b46a7f922b468e535adabc2337b330)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f7b46a7f922b468e535adabc2337b330"><img src="http://joss.theoj.org/papers/f7b46a7f922b468e535adabc2337b330/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f7b46a7f922b468e535adabc2337b330/status.svg)](http://joss.theoj.org/papers/f7b46a7f922b468e535adabc2337b330)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://www.github.com/singularityhub/container-tree" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@luizirber, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @brainstorm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://www.github.com/singularityhub/container-tree">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.0.48)?
- [x] **Authorship:** Has the submitting author (@vsoch) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @luizirber it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01418/joss.01418/10.21105.joss.01418.pdf)

**Comment by vsoch** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by vsoch** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01418/joss.01418/10.21105.joss.01418.pdf)

**Comment by vsoch** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01418/joss.01418/10.21105.joss.01418.pdf)

**Comment by vsoch** [comment]
okay, looks good! Thanks @whedon. I had some "n.d" dates that I wanted to fix up. The manuscript should be ready now. Thanks for reviewing @luizirber and overseeing @brainstorm.

**Comment by brainstorm** [comment]
@luizirber There seem to be some unchecked boxes on the review, do you reckon this review is complete/done?

**Comment by luizirber** [comment]
Not ready yet, pycon happened along the way... will finish tomorrow

On May 5, 2019 9:55:58 PM UTC, Roman Valls Guimera <notifications@github.com> wrote:
>@luizirber There seem to be some unchecked boxes on the review, do you
>reckon this review is complete/done?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/openjournals/joss-reviews/issues/1418#issuecomment-489466799

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brainstorm** [comment]
Hey, no rush, enjoy PyCon, I'm just getting through my email backlog after
the break ;)

**Comment by vsoch** [comment]
Yeah @luizirber that sounds awesome!! When you come back, let us know how it was, and where PyCon 2020 will be! I found [the site](https://us.pycon.org/2019/about/) and I didn't realize it was closer to my neck of the woods than say, San Francisco. I totally want to go one of these years, so fingers crossed it's close by again!

**Comment by vsoch** [comment]
omg it's in Pittsburgh! https://pycon.blogspot.com/2019/02/pycon-2020-2021-location.html woo!

**Comment by luizirber** [comment]
Finally back on track, sorry for the delay.

I sent some PRs for small doc fixes in the original repo, so the main items missing in the checklist are:

## Automated tests

While CircleCI is set up, I didn't find any tests in the codebase. The examples are very nice, but are not automated/ran on every PR. But it seems they would be very amenable to testing, perhaps with smaller data inputs?

## References

At least the PLOS ref has a DOI. Not sure about the others.

**Comment by vsoch** [comment]
Thanks @luizirber ! I'll get you some tests (likely tomorrow, or day after). I just responded to the PR (thank you!) and I'll see if I can update references with DOIs.

**Comment by vsoch** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01418/joss.01418/10.21105.joss.01418.pdf)

**Comment by vsoch** [comment]
@whedon generate pdf again!

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01418/joss.01418/10.21105.joss.01418.pdf)

**Comment by brainstorm** [comment]
@vsoch LGTM, archive to Zenodo #FTW?

**Comment by vsoch** [comment]
hey @brainstorm ! I’m still finishing up some final tests, and I should have it ready to go in a couple of days at the most. Will keep you posted!

**Comment by vsoch** [comment]
@luizirber I'm so glad you noticed this, because I had added the circle config to build containers without finishing the actual tests for the trees and client! I'm happy to report that I now have tests for container trees, collection trees, package trees, data export, and the command line client! All just under 1K lines of code, tested and merged: https://github.com/singularityhub/container-tree/pull/44

@brainstorm I've drafted a new release for the updated version, v0.0.49, and the archive should be processing --> available via zenodo asap https://zenodo.org/account/settings/github/repository/singularityhub/container-tree#

Holy crap, I'm tired... going for a run! :running_man:

**Comment by luizirber** [comment]
Great job, @vsoch! And enjoy the run =]

@brainstorm all checked on my side, ready to go!

**Comment by brainstorm** [comment]
Cool cool, thanks everybody! @vsoch need the zenodo DOI thingie and should be Archivable, I cannot login/hack your zenodo account ;)

**Comment by vsoch** [comment]
This one?

https://doi.org/10.5281/zenodo.2853983

**Comment by vsoch** [comment]
And latest release https://github.com/singularityhub/container-tree/releases/tag/v0.0.49

**Comment by brainstorm** [comment]
@whedon set https://doi.org/10.5281/zenodo.2853983 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2853983" target="_blank">10.5281/zenodo.2853983</a> is the archive.

**Comment by brainstorm** [comment]
All set here too, @labarba, ready to accept/deposit 👍

**Comment by labarba** [comment]
I'm not on duty this week.

Ping @openjournals/joss-eics

**Comment by labarba** [comment]
@vsoch — Please edit the metadata of the Zenodo deposit (no need to get new version or new DOI) so the title and author list match the JOSS paper. You may also want to add your ORCID in the metadata.

**Comment by vsoch** [comment]
Ah thanks for the reminder - all fixed!

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2602127 is OK
- https://doi.org/10.1371/journal.pone.0188511 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/700

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/700, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
Posted to the Twitters: https://twitter.com/JOSS_TheOJ/status/1130209744663318528

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/701
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01418](https://doi.org/10.21105/joss.01418)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by vsoch** [comment]
It looks like the pdf is 404, do we need to wait longer? https://www.theoj.org/joss-papers/joss.01418/10.21105.joss.01418.pdf

**Comment by vsoch** [comment]
Oh you know what, it's probably just github pages (this happens to me a lot!) I'll check in a few minutes.

**Comment by arfon** [comment]
> Oh you know what, it's probably just github pages (this happens to me a lot!) I'll check in a few minutes.

I've just cleared the Cloudflare cache and it's showing up for me OK. Sometimes GitHub pages is just a little slow.

**Comment by vsoch** [comment]
Showing up for me too! Thanks @arfon. And huge +1, GitHub pages is slow these days. Thanks to everyone for your help with this paper! :fireworks:

**Comment by vsoch** [comment]
Thanks @whedon, I think we are good and I'm ready to go party, err... keep working on other stuff, run up a hill a few times, and eat dinner :) Enjoy the rest of your robot Sunday! @arfon I can't close the issue (should I be able to?) but please feel free to do so.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01418/status.svg)](https://doi.org/10.21105/joss.01418)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01418">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01418/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01418/status.svg
   :target: https://doi.org/10.21105/joss.01418
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01418/status.svg)](https://doi.org/10.21105/joss.01418)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
