### ISSUE TITLE
[PRE REVIEW]: sslf: A simple spectral line finder

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1419]
**Submitting author:** @cjordan (<a href="http://orcid.org/0000-0002-1220-2940">Christopher H. Jordan</a>)
**Repository:** <a href="https://gitlab.com/chjordan/sslf" target ="_blank">https://gitlab.com/chjordan/sslf</a>
**Version:** v0.1.9
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @cjordan. **Currently, there isn't an JOSS editor assigned** to your paper.

@cjordan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01419/joss.01419/10.21105.joss.01419.pdf)

**Comment by kyleniemeyer** [comment]
Hi @cjordan, the JOSS editors discussed your submission, and decided that—while useful—we classify it more as a minor utility than what we consider research software.

However, some folks did find is useful, and suggested that the novel elements of this code would be a good addition to existing community software packages such as https://github.com/astropy/specutils

**Comment by cjordan** [comment]
Thank you for your correspondence @kyleniemeyer.
