### ISSUE TITLE
[REVIEW]: shmlast: An improved implementation of Conditional Reciprocal Best Hits with LAST and Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#142]
**Submitting author:** @camillescott (<a href="http://orcid.org/0000-0001-8822-8779">Camille Scott</a>)
**Repository:** <a href="https://github.com/camillescott/shmlast" target ="_blank">https://github.com/camillescott/shmlast</a>
**Version:** v1.1
**Editor:** @biorelated
**Reviewer:** @genomematt
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.260437" target="_blank">10.5281/zenodo.260437</a>

## Status

[![status](http://joss.theoj.org/papers/3cde54de7dfbcada7c0fc04f569b36c7/status.svg)](http://joss.theoj.org/papers/3cde54de7dfbcada7c0fc04f569b36c7)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/3cde54de7dfbcada7c0fc04f569b36c7"><img src="http://joss.theoj.org/papers/3cde54de7dfbcada7c0fc04f569b36c7/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/3cde54de7dfbcada7c0fc04f569b36c7/status.svg)](http://joss.theoj.org/papers/3cde54de7dfbcada7c0fc04f569b36c7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/camillescott/shmlast" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/camillescott/shmlast">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.2)?
- [x] **Authorship:** Has the submitting author (@camillescott) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @genomematt it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by biorelated** [comment]
@genomematt Where are we at with this review? Please let us know.

**Comment by genomematt** [comment]
I am still working my way through this, but some initial comments @camillescott.

I think that you need a more from first principles statement of need that outlines the sequence matching problem that CRBH is addressing (remembering that this is a generalist scientific computing journal) so that readers don't need to chase a reference to get a basic idea of what the software does.

You need contribution, bug report and support guidelines - check out some other JOSS articles for what this should look like.

A real world (ish) worked example, ideally as a jupyter notebook or doctest file would greatly enhance, and would help with explaining the statement of need.

Very pleased to see coverage as part of your testing.  Your exclusions all look very sensible on first pass.  You may wish to add `#pragma no cover` directives marking the code you don't test.  This makes it easier to track in your code and makes full coverage 100%. (suggestion not a requirement)

As you make a claim of improved performance (speed) it would be good to quantify that improvement.

I had an install issue but I am pretty sure it was related to a prior install not yours.  I will redo on a clean VM to confirm.

**Comment by camillescott** [comment]
Thanks @genomematt. I'll add a section to the paper describing the approach in a bit more detail. I can easily add a figure with performance comps as well.

**Comment by camillescott** [comment]
Update: I have added a performance comparison figure, a section describing the method in a bit more detail, and contribution guidelines.

**Comment by genomematt** [comment]
Ok @camillescott the added bits are good.  My install issue was a conda problem and all was fine on a clean vm.

Given that there are multiple dependencies I think there should be a test step at the end of your install procedure.  This would not need to be comprehensive testing of code, just a 'if you have installed it correctly this input will give this output.'

I am giving you a scraping pass on the real world application documentation, but an additional notebook  that does not hide the actual running in a script like the performance notebook, showing real transcripts against a real db and then interpreting the csv to answer the biological question would enhance.
As it stands the documentation is good for anyone who has done this sort of procedure before, and not as easy for someone who has a set of transcripts and is asking 'what is the best way to match these to the most closely related model organism'

Neither of those would stop me recommending accepting, but the complete lack of community guidelines does.
```Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support```

**Comment by camillescott** [comment]
What is expected for guidelines? I did add a CONTRIBUTING.md: https://github.com/camillescott/shmlast/blob/master/CONTRIBUTING.md

I followed the example of several other accepted projects on that -- should I add more?

**Comment by genomematt** [comment]
Sorry @camillescott I missed the CONTRIBUTING.md.  I suspect a lot of other people especially those with bugs or support questions would as well.  At least link it from the readme, and personally I would be inclined to put such a short section just in the readme.

**Comment by genomematt** [comment]
Ok @biorelated I consider this ready to accept.

**Comment by camillescott** [comment]
Copy that @genomematt -- added it to the readme :)

**Comment by biorelated** [comment]
Many thanks @genomematt.

**Comment by biorelated** [comment]
@arfon can we prepare this work for publication please?

**Comment by arfon** [comment]
@camillescott - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by camillescott** [comment]
@arfon: I've archived on Zenodo; here is the DOI: http://doi.org/10.5281/zenodo.260437

note that the final published version after the requested changes is v1.1, not v1.0.2 as in Whedon's first post in this issue

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.260437 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.260437" target="_blank">10.5281/zenodo.260437</a> is the archive.

**Comment by arfon** [comment]
Many thanks for your review @genomematt and thanks for editing this one @biorelated ✨ 

@camillescott - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00142 ⚡️ 🚀 💥
