### ISSUE TITLE
[REVIEW]: ECabc: A feature tuning program focused on Artificial Neural Network hyperparameters

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1420]
**Submitting author:** @sanskriti-s (<a href="http://orcid.org/0000-0002-9884-7351">Sanskriti Sharma</a>)
**Repository:** <a href="https://github.com/ECRL/ecabc" target ="_blank">https://github.com/ECRL/ecabc</a>
**Version:** v2.2.2
**Editor:** @arokem
**Reviewer:** @annoviko
**Archive:** <a href="https://doi.org/10.5281/zenodo.3256403" target="_blank">10.5281/zenodo.3256403</a>

## Status

[![status](http://joss.theoj.org/papers/4bb4db31cd486cf8017e2055621956ad/status.svg)](http://joss.theoj.org/papers/4bb4db31cd486cf8017e2055621956ad)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/4bb4db31cd486cf8017e2055621956ad"><img src="http://joss.theoj.org/papers/4bb4db31cd486cf8017e2055621956ad/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/4bb4db31cd486cf8017e2055621956ad/status.svg)](http://joss.theoj.org/papers/4bb4db31cd486cf8017e2055621956ad)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ECRL/ecabc" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@annoviko, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ECRL/ecabc">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2.2.2)?
- [x] **Authorship:** Has the submitting author (@sanskriti-s) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @annoviko it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01420/joss.01420/10.21105.joss.01420.pdf)

**Comment by annoviko** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/s0925-2312(00)00302-7 is OK
- 10.1109/sami.2015.7061899 is OK
- 10.21105/joss.00401 is OK
- 10.1016/j.fuel.2017.06.015 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by annoviko** [comment]
Hello, @sanskriti-s
There are several remarks:
1. Example contains mistakes in README.md (at least it doesn't work for v2.2.2):
- Incorrect import, I think `from ecabc import *` should be instead of `from eabc import *`, otherwise following exception is obtained:
```
ImportError: No module named 'eabc'
```
- ABC is not defined:
```python
    abc = ABC(fitness_fxn=idealDayTest,
            value_ranges=values
            )
```
```
NameError: name 'ABC' is not defined
```

2. Several references does not contains DOI. Could you please add DOI for these references?
```
@online{ecabc_github,
author = {Sanskriti Sharma},
title = {ECabc: A feature tuning program focused on Artificial Neural Network hyperparameters},
year = {2019},
url = {https://github.com/ECRL/ECabc},
urldate = {2019-04-12}
}

@online{ecabc_pypi,
author = {Sanskriti Sharma, Hernan Gelaf-Romer},
title = {ecabc 2.2.2},
year = {2019},
url = {https://pypi.python.org/pypi/ecabc/},
urldate = {2019-04-12}
}

@online{uml_ecrl,
author = {John Hunter Mack},
title = {Energy and Combustion Research Laboratory},
year = {2019},
url = {http://faculty.uml.edu/Hunter_Mack/},
urldate = {2019-04-12}
}

@book{Hassoun_2009,
Author = {{Hassoun}, M.},
Booktitle = {Fundamentals of Artificial Neural Networks, by Hassoun, Mohamad H.~ISBN 9788120313569 (HB).~Published by PHI Learning, Delhi, India, 2009.},
Publisher = {PHI Learning},
Title = {{Fundamentals of Artificial Neural Networks}},
Year = 2009
}
```

**Comment by sanskriti-s** [comment]
Hi @annoviko. Sorry for the late response, I had finals. So I fixed the README, but I have a question about the DOIs. To the best of my knowledge online sources don't have DOIs and while books do, I can't find one for the book I have cited. So what should I do about them?

**Comment by arokem** [comment]
Hi @sanskriti-s : you are correct that the websites you refer do not have a DOI, and you do not need to specify one for these. I believe that the Hassoun book does not have a DOI either. So, no need for DOIs for these.

**Comment by sanskriti-s** [comment]
Hi @arokem, Ok thanks

**Comment by arokem** [comment]
@annoviko : any other comments? I see that several of the boxes have not been checked yet.

**Comment by annoviko** [comment]
Hello, @arokem,
Sorry for delay, I have returned from business trip recently. I will finish review during this week.

**Comment by annoviko** [comment]
Hello, @sanskriti-s ,
There is only one unclear moment that is related to testing. I haven't found any tests in the repository and there is no instruction how to verify software. Could you please provide any comments?

**Comment by sanskriti-s** [comment]
Hi @annoviko . The tests are available in the examples directory

**Comment by annoviko** [comment]
Hello, @sanskriti-s ,

I think it should be reflected in the README in line with JOSS's requirements:
> Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?
Could you please add this information (how to verify software functionality) to README?

**Comment by sanskriti-s** [comment]
Hello @annoviko. I have made the changes you requested.

**Comment by annoviko** [comment]
@sanskriti-s , thanks, now everything looks ok.
@arokem, let's move to the next steps.

**Comment by arokem** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01420/joss.01420/10.21105.joss.01420.pdf)

**Comment by arokem** [comment]
@sanskriti-s : just one request on my end: the caption of Figure one is currently not particularly informative. Would you mind rewriting this caption? Even just "Figure 1: the stages of the algorithm (see text)" or similar would be sufficient. 

After that's done, we can proceed with the next steps in accepting the article.

**Comment by sanskriti-s** [comment]
@arokem: Done!

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01420/joss.01420/10.21105.joss.01420.pdf)

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01420/joss.01420/10.21105.joss.01420.pdf)

**Comment by arokem** [comment]
@sanskriti-s : next, I will need you to create an archive of the current state of your software and deposit this into zenodo (https://zenodo.org). This will be the version of the code that will be associated with your paper.

**Comment by sanskriti-s** [comment]
@arokem : done!

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.3256403 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3256403" target="_blank">10.5281/zenodo.3256403</a> is the archive.

**Comment by arokem** [comment]
Great. I think this is ready for your approval @openjournals/joss-eics

**Comment by kyleniemeyer** [comment]
Hi @sanskriti-s, please clean up the Zenodo archive's metadata—the author list should match that of the paper, and right now it includes "KOLANICH; Daniel S. Katz; Ariel Rokem; Arfon Smith" and is missing Hunter Mack.

**Comment by kyleniemeyer** [comment]
@sanskriti-s there are a few other changes needed in the paper:

- Please add more-complete affiliation information, matching what you'd see in any journal article (department, institution, city, state, country)
- In the first paragraph, please fix the citations using the appropriate commands:
```
- `@author:2001`  ->  "Author et al. (2001)"
- `[@author:2001]` -> "(Author et al., 2001)"
- `[@author1:2001; @author2:2001]` -> "(Author1 et al., 2001; Author2 et al., 2002)"
```
In particular, I would change `research by Z. Cam et al [@Cam_2015]` to `research by @Cam_2015`.
- In the third paragraph, please add a comma after `i.e.`
- Please revise the last sentence of the third paragraph, it seems incomplete. `Alternatively, a number of iterations can be and for each iteration...`, "a number of iterations" can be what?
- Please fix the `Cam_2015` reference info, it looks malformed. The `author` field should include all of the author names.
- Actually, it looks like many of the references only include the first author and "et al.". Please add the full author lists for each citation, and remove all instances of "et al."
- The Mack reference is not appropriate (you're citing a research group page); either remove the citation and just mention the group in the text, or add citations to actual publications that have used the software.

**Comment by sanskriti-s** [comment]
@kyleniemeyer : Fixed zenodo metadata

**Comment by sanskriti-s** [comment]
@kyleniemeyer : Fixed paper and bibliography

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01420/joss.01420/10.21105.joss.01420.pdf)

**Comment by kyleniemeyer** [comment]
@sanskriti-s I fixed a number of the remaining issues with the paper and references in https://github.com/ECRL/ecabc/pull/47 and https://github.com/ECRL/ecabc/pull/48

When I was asking for affiliation information, I meant your affiliation given in the paper header, not to add institution to each of the references—which is not necessary (or even used).

Also, it looked like you actually removed the citation commands, rather than correcting them as I asked; I fixed those.

Finally, in BibTeX references, author names in `author` need to be separated by `and` rather than commas.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01420/joss.01420/10.21105.joss.01420.pdf)

**Comment by kyleniemeyer** [comment]
@sanskriti-s sorry, I missed one reference in the text

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01420/joss.01420/10.21105.joss.01420.pdf)

**Comment by kyleniemeyer** [comment]
@sanskriti-s ok, I think we're good to go here!

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1420 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/openjournals/joss-reviews-testing/issues/1420: 404 - Not Found // See: https://developer.github.com/v3/issues/#get-a-single-issue (Octokit::NotFound)
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/response.rb:9:in `block in call'
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/response.rb:61:in `on_complete'
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
	from /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/connection.rb:138:in `get'
	from /app/vendor/bundle/ruby/2.4.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/connection.rb:156:in `request'
	from /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/connection.rb:19:in `get'
	from /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/client/issues.rb:114:in `issue'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/review.rb:21:in `issue_body'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:71:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by sanskriti-s** [comment]
@kyleniemeyer : Thank you so much for your revisions

**Comment by whedon** [comment]
Downloading of the repository (to check the bibtex) failed for issue #1420 failed with the following error: 

 /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/openjournals/joss-reviews-testing/issues/1420: 404 - Not Found // See: https://developer.github.com/v3/issues/#get-a-single-issue (Octokit::NotFound)
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/response.rb:9:in `block in call'
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/response.rb:61:in `on_complete'
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
	from /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/connection.rb:138:in `get'
	from /app/vendor/bundle/ruby/2.4.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/connection.rb:156:in `request'
	from /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/connection.rb:19:in `get'
	from /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/client/issues.rb:114:in `issue'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/review.rb:21:in `issue_body'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:291:in `review_issue'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:301:in `download'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:38:in `download'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/s0925-2312(00)00302-7 is OK
- 10.1109/sami.2015.7061899 is OK
- 10.21105/joss.00401 is OK
- 10.1016/j.fuel.2017.06.015 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/834

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/834, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1149442269071728645) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/835
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01420](https://doi.org/10.21105/joss.01420)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
@sanskriti-s congrats on your submission's publication in JOSS! Thanks to @annoviko for reviewing and @arokem for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01420/status.svg)](https://doi.org/10.21105/joss.01420)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01420">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01420/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01420/status.svg
   :target: https://doi.org/10.21105/joss.01420
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01420/status.svg)](https://doi.org/10.21105/joss.01420)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
