### ISSUE TITLE
[PRE REVIEW]: Fireworks: Reproducible Machine Learning with PyTorch

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1422]
**Submitting author:** @smk508 (<a href="http://orcid.org/0000-0003-4686-4923">Saad Khan</a>)
**Repository:** <a href="https://github.com/kellylab/Fireworks" target ="_blank">https://github.com/kellylab/Fireworks</a>
**Version:** 0.3.0
**Editor:** @arokem
**Reviewers:** dirmeier

**Author instructions**

Thanks for submitting your paper to JOSS @smk508. **Currently, there isn't an JOSS editor assigned** to your paper.

@smk508 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1422 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/author.rb:58:in `block in build_affiliation_string': Problem with affiliations for Saad Khan, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/author.rb:57:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/author.rb:57:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:109:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:109:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:106:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:106:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by smk508** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by smk508** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01422/joss.01422/10.21105.joss.01422.pdf)

**Comment by kyleniemeyer** [comment]
@smk508 I am looking for a JOSS editor to handle the submission; once someone is assigned, they will work to assign reviewers.

**Comment by smk508** [comment]
Ok thanks!

**Comment by arokem** [comment]
I can handle this one.

**Comment by arokem** [comment]
@whedon assign arokem as editor

**Comment by whedon** [comment]
OK, the editor is arokem

**Comment by arokem** [comment]
@smk508 : do you have any suggestions for reviewers? You can also look [here](https://bit.ly/joss-reviewers)

**Comment by smk508** [comment]
Hi @arokem . Thanks so much! I looked through the spreadsheet for people who are experts in machine learning, big data, and/or bioinformatics. There's a lot of people, so I'm not sure who makes the most sense, but I just picked out some names. I think if there's someone who has experience designing or contributing to machine learning / big data frameworks such a TensorFlow / PyTorch / Spark, that person would probably have good insight to give since this library is a framework meant to facilitate machine learning. 

Here are some names as I skimmed the spreadsheet:

Simon Dirmier
Niranjan Padmanabhan (username: neurons)
Divya Sardanda

**Comment by arokem** [comment]
👋 @dvysardana: would you be willing to review this paper for JOSS? It seems right up your alley!

**Comment by arokem** [comment]
I'll give @dvysardana a few more days to reply here, but if I don't hear back I'll ping other potential reviewers next week.

**Comment by smk508** [comment]
Ok thanks

**Comment by smk508** [comment]
Hi @arokem , what's the status on the paper review?

**Comment by arokem** [comment]
Sorry - I have been traveling and away from this pre-review.

**Comment by arokem** [comment]
👋 @dirmeier : would you be willing to review this paper for JOSS?

**Comment by dirmeier** [comment]
Hey, so sorry for the late reply. I totally forgot answering. Yes, I'd be happy to review!

**Comment by smk508** [comment]
Hi @dirmeier thanks for reviewing my submission! What are the next steps @arokem ?

**Comment by arokem** [comment]
@whedon assign dirmeier as reviewer

**Comment by whedon** [comment]
OK, the reviewer is dirmeier

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1478. Feel free to close this issue now!

**Comment by arokem** [comment]
@dirmeier : thanks for taking this on! Please head over to #1478 for the review. I'll close this issue now.
