### ISSUE TITLE
[REVIEW]: CRED: a rapid peak caller for Chem-seq data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1423]
**Submitting author:** @jlincbio (<a href="http://orcid.org/0000-0002-8086-3185">Jason Lin</a>)
**Repository:** <a href="https://github.com/jlincbio/cred" target ="_blank">https://github.com/jlincbio/cred</a>
**Version:** 0.1
**Editor:** @lpantano
**Reviewer:** @darogan
**Archive:** <a href="https://doi.org/10.5281/zenodo.2667613" target="_blank">10.5281/zenodo.2667613</a>

## Status

[![status](http://joss.theoj.org/papers/f9d17ffdcd6b02ef2f2a5eaa3638c294/status.svg)](http://joss.theoj.org/papers/f9d17ffdcd6b02ef2f2a5eaa3638c294)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f9d17ffdcd6b02ef2f2a5eaa3638c294"><img src="http://joss.theoj.org/papers/f9d17ffdcd6b02ef2f2a5eaa3638c294/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f9d17ffdcd6b02ef2f2a5eaa3638c294/status.svg)](http://joss.theoj.org/papers/f9d17ffdcd6b02ef2f2a5eaa3638c294)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jlincbio/cred" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@darogan, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jlincbio/cred">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1)?
- [x] **Authorship:** Has the submitting author (@jlincbio) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @darogan it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01423/joss.01423/10.21105.joss.01423.pdf)

**Comment by darogan** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by darogan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1186/gb-2008-9-9-r137 is OK
- 10.1371/journal.pone.0065598 is OK
- 10.1371/journal.pone.0165581 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.1137/1.9781611970586 is OK

MISSING DOIs

- https://doi.org/10.2307/2346797 may be missing for title: Algorithm AS 63: The Incomplete Beta Integral

INVALID DOIs

- None
```

**Comment by darogan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01423/joss.01423/10.21105.joss.01423.pdf)

**Comment by darogan** [comment]
@jlincbio The references don't appear in the article proof - is this some thing you can fix? 

Also, would it be appropriate to cite your recent PLoS One (10.1371/journal.pone.0215247) paper as I can imagine both tools being used during a project

**Comment by jlincbio** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01423/joss.01423/10.21105.joss.01423.pdf)

**Comment by jlincbio** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01423/joss.01423/10.21105.joss.01423.pdf)

**Comment by jlincbio** [comment]
@darogan thanks for reviewing CRED, Dr. Hamilton. I apologize for the delay.

I am trying to figure out why the references are not showing up - I suspected that it is the bibTex entries but paper.bib seemed to pass the BibTex quality checker (https://biblatex-linter.herokuapp.com/validate); I will continue to try to fix it.

Re: your comment about the recent PLoS ONE publication -  I did not explicitly refer to it in the manuscript and because that publication dealt more with microarray data rather than sequencing data, I decided to leave it as is. Nevertheless I will take up your suggestion and see if it's worth adding a remark in the paper and including this citation.

**Comment by jlincbio** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01423/joss.01423/10.21105.joss.01423.pdf)

**Comment by jlincbio** [comment]
@lpantano Thanks for setting the review process up :)

**Comment by jlincbio** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01423/joss.01423/10.21105.joss.01423.pdf)

**Comment by jlincbio** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01423/joss.01423/10.21105.joss.01423.pdf)

**Comment by jlincbio** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01423/joss.01423/10.21105.joss.01423.pdf)

**Comment by jlincbio** [comment]
@darogan sorry about the delay. It turned out that I didn't properly set the reference property names properly and was not calling them in the manuscript. This latest version seemed to have fixed it: 

> 
> 
> [ 👉 Check article proof 📄 👈 ](https://github.com/openjournals/joss-papers/blob/joss.01423/joss.01423/10.21105.joss.01423.pdf)

**Comment by darogan** [comment]
@jlincbio Thanks for fixing it, PDF looks great, all references OK.

@lpantano I'm happy with the software/paper - shall I close the issue to complete the review?

**Comment by lpantano** [comment]
Thanks! i will take a final look today and proceed with the acceptance.

**Comment by lpantano** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1186/gb-2008-9-9-r137 is OK
- 10.1371/journal.pone.0065598 is OK
- 10.1371/journal.pone.0165581 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.2307/2346797 is OK
- 10.1137/1.9781611970586 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lpantano** [comment]
@jlincbio , we are almost there. Can you create a zenodo doi (https://zenodo.org/) pointed to the current version of the repository? The title of that archive should match paper title and the authors should match as well. Here is an example of another paper:

https://zenodo.org/record/2645762#.XMyf2akpCpc

https://github.com/openjournals/joss-reviews/issues/1364

Cheers

**Comment by jlincbio** [comment]
@lpantano do you mean a link like this:
https://doi.org/10.5281/zenodo.2663855

Or is it this one:
https://zenodo.org/record/2663855#.XMystqRS_D4

Thanks.

**Comment by lpantano** [comment]
@whedon set https://zenodo.org/record/2663855 as archive

**Comment by whedon** [comment]
https://zenodo.org/record/2663855 doesn't look like an archive DOI.

**Comment by lpantano** [comment]
@whedon set 10.5281/zenodo.2663855 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2663855" target="_blank">10.5281/zenodo.2663855</a> is the archive.

**Comment by lpantano** [comment]
Hi @openjournals/joss-eics, I think we are good to go!

**Comment by kyleniemeyer** [comment]
Hi @jlincbio, overall looks good, but before we fully accept I have two comments on the paper. Could you please:
[ ] Add to the background section a bit more helping describe the high-level functionality and purpose of the software for a *diverse, non-specialist audience*? This is part of our expectations for articles, since the JOSS audience is quite broad.
[ ] Add some metadata to the first reference (Durbin 1973)? It looks like it may be a textbook, but if so is missing some info in the reference.

**Comment by jlincbio** [comment]
@kyleniemeyer thanks for the comments, I'll try to get right onto it. Re: point 1, should some general description on what a peak caller does be sufficient?

Also, do I need to submit a new release and get a new zenodo DOI?

**Comment by jlincbio** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01423/joss.01423/10.21105.joss.01423.pdf)

**Comment by jlincbio** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by jlincbio** [comment]
@whedon set 10.5281/zenodo.2667425 as archive

**Comment by whedon** [comment]
I'm sorry @jlincbio, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by jlincbio** [comment]
> [ 👉 Check article proof 📄 👈 ](https://github.com/openjournals/joss-papers/blob/joss.01423/joss.01423/10.21105.joss.01423.pdf)

@kyleniemeyer would the above changes be sufficient to satisfy the journal requirements?

Also if a new Zenodo archive DOI is necessary I think this is it:
10.5281/zenodo.2667425

**Comment by jlincbio** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01423/joss.01423/10.21105.joss.01423.pdf)

**Comment by jlincbio** [comment]
@kyleniemeyer sorry, this is the new Zenodo DOI: 10.5281/zenodo.2667428

**Comment by kyleniemeyer** [comment]
Hi @jlincbio, sorry the Durbin ref was still not showing up correctly; I just submitted a [PR](https://github.com/jlincbio/cred/pull/1) to fix it.

**Comment by jlincbio** [comment]
@kyleniemeyer thanks for the help. I merged the fix on my mobile phone and re-released it under the same version tag of v0.1...hopefully I did not do something stupid to mess it up.

The DOI seems to be the same as before at 10.5281/zenodo.2667428 (the same commit, ddef12d).

Thanks - it's my first time with Zenodo.

**Comment by jlincbio** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01423/joss.01423/10.21105.joss.01423.pdf)

**Comment by jlincbio** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01423/joss.01423/10.21105.joss.01423.pdf)

**Comment by jlincbio** [comment]
So sorry with all these edits...I'm doing this on a mobile and keep making mistakes.
New DOI: 10.5281/zenodo.2667613

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.2667613 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2667613" target="_blank">10.5281/zenodo.2667613</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/S0959-440X(03)00081-2 is OK
- 10.1021/cb500724t is OK
- 10.1186/gb-2008-9-9-r137 is OK
- 10.1371/journal.pone.0065598 is OK
- 10.1371/journal.pone.0165581 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.2307/2346797 is OK
- 10.1038/ncomms7706 is OK
- 10.1137/1.9781611970586 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/661

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/661, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@jlincbio ok, you are all set. Unfortunately, we have to pause the final publishing step until CrossRef resolves some issues they are dealing with at the moment. Hopefully those are resolved by tomorrow.

**Comment by jlincbio** [comment]
@kyleniemeyer thanks, so is there anything I need to do on my part?

I'd also like to take this time to thank @lpantano and @darogan for their time and attention over the course of the review and apologize for all the incessant editing throughout the process. This is my first time submitting manuscripts for review using GitHub, and hopefully I have not caused anyone too much trouble.

**Comment by jlincbio** [comment]
I noticed a small typo (extra "an" in "...BioPerl library made it an undesireable") and modified `paper.md` by the way; hopefully this isn't too late.

**Comment by kyleniemeyer** [comment]
@jlincbio nope, until we formally publish the paper it isn't too late.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01423/joss.01423/10.21105.joss.01423.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/665

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/665, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/S0959-440X(03)00081-2 is OK
- 10.1021/cb500724t is OK
- 10.1186/gb-2008-9-9-r137 is OK
- 10.1371/journal.pone.0065598 is OK
- 10.1371/journal.pone.0165581 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.2307/2346797 is OK
- 10.1038/ncomms7706 is OK
- 10.1137/1.9781611970586 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jlincbio** [comment]
@kyleniemeyer thanks for the help...the PDF looks fine. Hopefully this didn't wake you up in the middle of the night.

**Comment by jlincbio** [comment]
@kyleniemeyer sorry to bother you again, but do you know when the issue with CrossRef will be resolved and the paper can officially go on-line?

**Comment by kyleniemeyer** [comment]
@jlincbio congrats on your paper's publication in JOSS! thanks to @darogan for reviewing and @lpantano for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01423/status.svg)](https://doi.org/10.21105/joss.01423)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01423">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01423/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01423/status.svg
   :target: https://doi.org/10.21105/joss.01423
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01423/status.svg)](https://doi.org/10.21105/joss.01423)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by kyleniemeyer** [comment]
@jlincbio congrats on your paper's publication in JOSS! Thanks to @darogan for reviewing and @lpantano for editing!

**Comment by lpantano** [comment]
Congrats! you did great!

**Comment by darogan** [comment]
Congratulations, was a pleasure to review

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/670
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01423](https://doi.org/10.21105/joss.01423)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by jlincbio** [comment]
@lpantano @darogan @kyleniemeyer thanks again for the help along the way and I do apologize for all the inconvenience I've caused. Looking forward to the next chance working with the wonderful people at JOSS in the future.
