### ISSUE TITLE
[PRE REVIEW]: sluRm: A lightweight wrapper for HPC with Slurm

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1428]
**Submitting author:** @gvegayon (<a href="http://orcid.org/0000-0002-3171-0844">George Vega Yon</a>)
**Repository:** <a href="https://github.com/USCbiostats/sluRm" target ="_blank">https://github.com/USCbiostats/sluRm</a>
**Version:** 0.1-0
**Editor:** @karthik
**Reviewers:** @mschubert, @mllg

**Author instructions**

Thanks for submitting your paper to JOSS @gvegayon. **Currently, there isn't an JOSS editor assigned** to your paper.

@gvegayon if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01428/joss.01428/10.21105.joss.01428.pdf)

**Comment by kyleniemeyer** [comment]
@karthik could you handle this submission? Looks up your alley.

**Comment by kyleniemeyer** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by karthik** [comment]
Currently ooo till May 15

**Comment by kyleniemeyer** [comment]
@karthik hmm OOO bot didn't seem to catch that. But thanks, no problem.

**Comment by karthik** [comment]
Hello @wrathematics Any chance you have time to review this submission?

**Comment by karthik** [comment]
👋 @HenrikBengtsson Would you also be open to reviewing this for us?

**Comment by karthik** [comment]
Pinged Henrik directly on 5/28

**Comment by HenrikBengtsson** [comment]
Sorry, I won't have the time to review this one any time soon, especially since I don't have access to a Slurm environment.  I think whoever reviews this should be able to test it and play with it using Slurm.  On a related note (request to the community), a Linux container with R and Slurm pre-configured would be useful (I would be interested in that outside of this submission).

My suggestion for alternative reviewers are:

 * Michel Lang (@mllg), author of [batchtools](https://cran.r-project.org/package=batchtools)
 * Michael Schubert (@mschubert), author of [clustermq](https://cran.r-project.org/package=clustermq)
 * Will Landau (@wlandau-lilly), author of [drake](https://github.com/ropensci/drake) and who I think have mentioned he got access to a Slurm environment

PS. Does "[PRE REVIEW]" in the subject mean "looking for reviewers" whereas "[REVIEW]" means "under review"?

**Comment by mschubert** [comment]
I'd be happy to review this.<sup>1</sup>

However, could the editors please confirm that the advantages listed in the article (fewer dependencies, slightly different API) are sufficient as per JOSS guidelines?

> The software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler)

<sup>1</sup> COI: author of package with similar functionality

**Comment by wlandau** [comment]
I am willing to stay in the loop as a backup, but I am about to travel to a conference, so I would not be able to begin until next week. Also, the Slurm installation Henrik mentioned was experimental. It was all emulated on my local machine (including the one and only compute node) and I no longer currently have it.

**Comment by mllg** [comment]
I can also review this and test the package on multiple slurm systems.

**Comment by karthik** [comment]
> PS. Does "[PRE REVIEW]" in the subject mean "looking for reviewers" whereas "[REVIEW]" means "under review"?

Yes, that's right.

**Comment by karthik** [comment]
Thanks Henrik for the reviewer suggestions and the helpful comments. 

> However, could the editors please confirm that the advantages listed in the article (fewer dependencies, slightly different API) are sufficient as per JOSS guidelines?

@mschubert Good point.  @gvegayon: Can you please tell us a bit more about how your package is a significant improvement over existing tools?

**Comment by gvegayon** [comment]
Thanks all (@mschubert @mllg @wlandau @HenrikBengtsson) for all the comments/suggestions! @karthik, besides of it be lightweight (actually, dependency free), the other important contributions are:

* Tailored for Slurm workflow (no need to use template files to set up a job, this is done on the fly).

* Accessing bash commands directly from within R (cancel jobs, query jobs, see details on the job account, submitting jobs, etc.)

```r
# Canceling a previously created job
scancel(job)

# Canceling all my jobs in the cluster
scancel(user = "vegayon")

# Canceling a given job id
scancel(9291231)
```

* smoothly resubmitting jobs, or parts of it (which is something some of my colleagues value a lot), e.g.:
```r
library(sluRm)

# A simple expr evaluation, WhoAmI() gives some info about the node
x <- Slurm_EvalQ(sluRm::WhoAmI(), njobs = 20, plan = "wait")

# Suppose jobs 1, 2, and 15-20 failed, then we can do the following
sbatch(x, array = "1,2,15-20")

# And, if status OK, then collect safely the entire array
ans <- Slurm_collect(x)
```

This last point is critical (I see partial failure all the time, and is very common in heterogeneous clusters). And I'm not sure how easy/complicated is to resubmit parts of jobs in the other frameworks, or how easy/complicated is to add these features to the other frameworks. 

I tried to work out a comparison table with some of the tools mentioned [here](https://github.com/USCbiostats/sluRm/#vs) (tried to fill it to the best of my understanding, would happily receive comments/complains/suggestions from any of you :) ).

LMK what are your thoughts 

cc my co-author @pmarjora

**Comment by karthik** [comment]
Thank you @gvegayon for addressing this issue.  This meets JOSS' criteria and I'm happy to send this out for review. Thanks @mschubert and @mllg for volunteering. I'll assign you shortly.

**Comment by karthik** [comment]
@whedon add @mschubert as reviewer

**Comment by whedon** [comment]
OK, @mschubert is now a reviewer

**Comment by karthik** [comment]
@whedon add @mllg as reviewer

**Comment by whedon** [comment]
OK, @mllg is now a reviewer

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1493. Feel free to close this issue now!
