### ISSUE TITLE
[PRE REVIEW]: phylosmith: an R-package for reproducible and efficient microbiome analysis with phyloseq-objects

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1429]
**Submitting author:** @schuyler-smith (<a href="http://orcid.org/0000-0001-5720-5611">Schuyler Smith</a>)
**Repository:** <a href="https://github.com/schuyler-smith/phylosmith/" target ="_blank">https://github.com/schuyler-smith/phylosmith/</a>
**Version:** 0.99.0
**Editor:** @karthik
**Reviewers:** @joey711

**Author instructions**

Thanks for submitting your paper to JOSS @schuyler-smith. **Currently, there isn't an JOSS editor assigned** to your paper.

@schuyler-smith if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1429 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
Hi @schuyler-smith, your paper file needs to be named `paper.md` and `paper.bib` for our system to detect it in your repo; could you fix that?

**Comment by kyleniemeyer** [comment]
@karthik sorry for the double tap, but this one also looks to fall in your realm...

**Comment by kyleniemeyer** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by schuyler-smith** [comment]
> Hi @schuyler-smith, your paper file needs to be named `paper.md` and `paper.bib` for our system to detect it in your repo; could you fix that?

@karthik 

Sorry for the late response! For some reason the notifications of the messages were not pushing to me. Here I was wondering why I hadn't heard from anyone, and it was on my end!

I renamed the files. Was the fail because of the travis build? I have openmp in my c++ code and so I had messed up my configure file for the flags when dealing with native MacOS that doesn't support it. It should be fixed, and able to compile on all systems now!

**Comment by schuyler-smith** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by schuyler-smith** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01429/joss.01429/10.21105.joss.01429.pdf)

**Comment by schuyler-smith** [comment]
@kyleniemeyer @karthik 
Thank you! I was able to generate the paper. Please let me know if I missed anything else, I tried my best to be diligent in the submission checklist.

**Comment by karthik** [comment]
Im on heavy travel at the moment but have pinged a few reviewers. I'll update this thread when I hear back. Stay tuned!

**Comment by karthik** [comment]
@whedon assign @joey711 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @joey711

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1442. Feel free to close this issue now!
