### ISSUE TITLE
[PRE REVIEW]: survPen: an R package for hazard and excess hazard modelling with multidimensional penalized splines

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1430]
**Submitting author:** @fauvernierma (<a href="http://orcid.org/0000-0002-3809-8248">Mathieu Fauvernier</a>)
**Repository:** <a href="https://github.com/fauvernierma/survPen" target ="_blank">https://github.com/fauvernierma/survPen</a>
**Version:** v1.1.0
**Editor:** @csoneson
**Reviewers:** @corybrunson, @seabbs

**Author instructions**

Thanks for submitting your paper to JOSS @fauvernierma. The JOSS editor @csoneson, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@fauvernierma if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @csoneson it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@csoneson) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01430/joss.01430/10.21105.joss.01430.pdf)

**Comment by kyleniemeyer** [comment]
@csoneson would you be able to edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by fauvernierma** [comment]
Hello everyone,

As they are both experts in R and survival analysis, I think that @becarioprecario and @adibender would make appropriate reviewers for the survPen package.

Do you agree ?

**Comment by csoneson** [comment]
@kyleniemeyer Yes, I can edit this one.

**Comment by csoneson** [comment]
@fauvernierma - thanks for these suggestions. I agree that they would fit very well as reviewers. @becarioprecario, @adibender, would you be willing to review this JOSS submission?

**Comment by csoneson** [comment]
@fauvernierma - I had a first quick look at your repository and the paper, and I have a couple of small comments that would be good if you could fix already before we start the review:
- Please add a plain text LICENSE file (you can add it to `.Rbuildignore` to ignore it when building the package
- Please check the references in the paper. Some of them look a bit weird (e.g. the Uhry _et al_ paper have authors "Group, G.E.W" and "the, C.W.S.G.", and not all words are properly capitalized). Also make sure that a DOI is indicated for all references that have one.

**Comment by becarioprecario** [comment]
Hi,

I am afraid that I cannot commit to make a review of this right now. I am already very late with another JOS review.

Sorry.

Virgilio

**Comment by csoneson** [comment]
@becarioprecario No problem, thanks for the quick reply!

**Comment by csoneson** [comment]
@corybrunson, @seabbs - would you be interested in reviewing this submission for JOSS?

**Comment by fauvernierma** [comment]
I have added a LICENSE file and all references should be in order now

Thank you

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01430/joss.01430/10.21105.joss.01430.pdf)

**Comment by corybrunson** [comment]
@csoneson i would be glad to review. I would expect to finish after one week. (I have only introductory training in survival analysis but the topic interests me.)

**Comment by csoneson** [comment]
@corybrunson excellent, thank you! 
As soon as we find one more reviewer I will open the actual review issue, where you can leave your comments etc.

**Comment by seabbs** [comment]
@csonesn I would also be happy to review. 

Not an expert in survival analysis but I have used `mgcv` fairly regularly (according to vignettes it has a comparable framework).

**Comment by csoneson** [comment]
@seabbs perfect. I will add you both as reviewers and open the review issue.

**Comment by csoneson** [comment]
@whedon assign @corybrunson as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @corybrunson

**Comment by csoneson** [comment]
@whedon add @seabbs as reviewer

**Comment by whedon** [comment]
OK, @seabbs is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by adibender** [comment]
Hello, sorry for late reply, happy to review if still necessary.

**Comment by arfon** [comment]
@whedon start review

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1434. Feel free to close this issue now!

**Comment by csoneson** [comment]
Hi @adibender - thanks for volunteering! I think we are set here - I hope I can come back to you for another paper in the future!

**Comment by csoneson** [comment]
@corybrunson, @seabbs - let's head over to #1434 for the review!
