### ISSUE TITLE
[PRE REVIEW]: emg3d: A multigrid solver for 3D electromagnetic diffusion.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1431]
**Submitting author:** @prisae (<a href="http://orcid.org/0000-0002-8575-2484">Dieter Werthmüller</a>)
**Repository:** <a href="https://github.com/empymod/emg3d" target ="_blank">https://github.com/empymod/emg3d</a>
**Version:** v0.5.0
**Editor:** @jedbrown
**Reviewers:** @akelbert, @emersodb, @lukeolson

**Author instructions**

Thanks for submitting your paper to JOSS @prisae. The JOSS editor @lheagy, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@prisae if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@lheagy) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01431/joss.01431/10.21105.joss.01431.pdf)

**Comment by kyleniemeyer** [comment]
@whedon remove @lheagy as editor

**Comment by kyleniemeyer** [comment]
Sorry, did not get this one started correctly.

**Comment by kyleniemeyer** [comment]
@poulson @jedbrown would either of you be willing to edit this submission? (@lheagy you are welcome to as well, just trying to ensure a relatively even editing load...)

**Comment by jedbrown** [comment]
I'm happy to

**Comment by prisae** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by prisae** [comment]
Re reviewer: Anyone into geophysics and python; electromagnetics would be a plus, I guess.

Some people from your list which fit the description: @rowanc1, @leouieda, @WalBytes , @vidalgp, @kbevers, @jkmacc-LANL, @whimian, @rbeucher, @d-chambers.

**Comment by prisae** [comment]
I saw one typo and some of the reference-bracketing in the compiled version did not turn out as I intended. Is there a way to edit them now or shall I wait for the reviews first?

**Comment by lheagy** [comment]
Thanks @jedbrown and @kyleniemeyer! I know @prisae and am excited to see that he submitted this project 😄. I will definitely be checking out the software, but am happy to let someone else lead the editorial process here.

**Comment by poulson** [comment]
> I'm happy to

I'm glad to see this is getting the proper attention!

**Comment by kyleniemeyer** [comment]
@whedon set @jedbrown as editor

**Comment by kyleniemeyer** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by prisae** [comment]
Hi @jedbrown. Do I have to do anything at the moment in this regard?

**Comment by jedbrown** [comment]
No, sorry about the silence. I re-upped some of my reviewer invitations.

**Comment by prisae** [comment]
No problem at all. I was just not sure if it is stalled because I haven't done something I was supposed to do.

**Comment by jedbrown** [comment]
@whedon add @akelbert as reviewer

**Comment by whedon** [comment]
OK, @akelbert is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @emersodb as reviewer

**Comment by whedon** [comment]
OK, @emersodb is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @lukeolson as reviewer

**Comment by whedon** [comment]
OK, @lukeolson is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1463. Feel free to close this issue now!
