### ISSUE TITLE
[PRE REVIEW]: MoFEM: An open source, parallel finite element library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1432]
**Submitting author:** @likask (<a href="http://orcid.org/0000-0002-8468-5435">Lukasz Kaczmarczyk</a>)
**Repository:** <a href="https://bitbucket.org/likask/mofem-cephas/src" target ="_blank">https://bitbucket.org/likask/mofem-cephas/src</a>
**Version:** v0.8.22
**Editor:** @jedbrown
**Reviewers:** @tjhei, @chrisrichardson, @Kevin-Mattheus-Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @likask. **Currently, there isn't an JOSS editor assigned** to your paper.

@likask if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1432 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by kyleniemeyer** [comment]
@jedbrown, could you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by likask** [comment]
1) Source files and the license file is in `mofem` subdirectory. 
2) JOSS paper.md is in `media` directory
3) Documentation http://mofem.eng.gla.ac.uk

**Comment by likask** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by likask** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1432 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    11    0    11    0     0    144      0 --:--:-- --:--:-- --:--:--   144
Error producing PDF.
! Argument of \caption@ydblarg has an extra }.
<inserted text> 
                \par 
l.580 ...for more details.\label{fig:convergence}}

Looks like we failed to compile the PDF

**Comment by likask** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01432/joss.01432/10.21105.joss.01432.pdf)

**Comment by likask** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.789521 is OK

MISSING DOIs

- https://doi.org/10.2172/970174 may be missing for title: MOAB: A Mesh-Oriented Database
- https://doi.org/10.1002/nme.847 may be missing for title: Hierarchic finite element bases on unstructured tetrahedral meshes
- https://doi.org/10.1137/11082539x may be missing for title: Bernstein-Bézier finite elements of arbitrary order and optimal assembly procedures
- https://doi.org/10.1016/j.camwa.2015.04.027 may be missing for title: Orientation embedded high order shape functions for the exact sequence elements of all shapes
- https://doi.org/10.1016/j.cma.2017.06.001 may be missing for title: Energy consistent framework for continuously evolving 3D crack propagation
- https://doi.org/10.1093/imanum/drq047 may be missing for title: A second elasticity element using the matrix bubble

INVALID DOIs

- None
```

**Comment by likask** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.2172/970174 is OK
- https://doi.org/10.1002/nme.847 is OK
- https://doi.org/10.1137/11082539x is OK
- https://doi.org/10.1016/j.camwa.2015.04.027 is OK
- https://doi.org/10.1016/j.cma.2017.06.001 is OK
- 10.5281/zenodo.789521 is OK
- https://doi.org/10.1093/imanum/drq047 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by likask** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01432/joss.01432/10.21105.joss.01432.pdf)

**Comment by likask** [comment]
> Failed to discover a valid open source license.

That is fixed; Reference is moved to root repository directory.

**Comment by likask** [comment]
Fix letter in my name 
@whedon generate pdf from branch joss

**Comment by likask** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01432/joss.01432/10.21105.joss.01432.pdf)

**Comment by likask** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01432/joss.01432/10.21105.joss.01432.pdf)

**Comment by likask** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by likask** [comment]
Suggested revieweres @IgorBaratta @mikaem

I've pick-up reviewers based on C++ and finite element method. It could be cool to have MoFEM reviewed by someone from the FEniCS community. 

BTW I don't know how JOSS pick reviewers. Should I do it? Or I crossing some red lines now :)

**Comment by jedbrown** [comment]
Thanks for suggesting reviewers. @IgorBaratta @mikaem, :wave: please let us know if you're available. I reached out yesterday to a couple other potential reviewers.

**Comment by likask** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01432/joss.01432/10.21105.joss.01432.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@jedbrown I've been using other open source finite element packages (https://febio.org/), and am the developer of GIBBON (https://www.gibboncode.org). I will test this package in the coming weeks. You can add me as a reviewer. However since I am not well versed in C++ I can only comment on the high level components like functionality and documentation. I therefore recommend you do recruit several other reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
Perhaps @belgiansteve (the developer for the C++ FEA package FEBio https://febio.org/) and @siboles would be interested in reviewing this work too?

**Comment by jedbrown** [comment]
@whedon add @tjhei as reviewer

**Comment by whedon** [comment]
OK, @tjhei is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @chrisrichardson as reviewer

**Comment by whedon** [comment]
OK, @chrisrichardson is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @Kevin-Mattheus-Moerman as reviewer

**Comment by whedon** [comment]
OK, @Kevin-Mattheus-Moerman is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1441. Feel free to close this issue now!

**Comment by vijaysm** [comment]
@jedbrown I would be happy to review the paper as well if you are still looking for reviewers.

**Comment by jedbrown** [comment]
Thanks, @vijaysm. I'd be happy to have your review; there's now a checklist for you in #1441.
