### ISSUE TITLE
[PRE REVIEW]: mTower: Trusted Execution Environment for MCU-based devices

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1436]
**Submitting author:** @omoliavko (<a href="http://orcid.org/0000-0003-3167-983X">Oleksandr Moliavko</a>)
**Repository:** <a href="https://github.com/Samsung/mTower.git" target ="_blank">https://github.com/Samsung/mTower.git</a>
**Version:** v0.1
**Editor:** @gkthiruvathukal
**Reviewers:** @gradvohl

**Author instructions**

Thanks for submitting your paper to JOSS @omoliavko. **Currently, there isn't an JOSS editor assigned** to your paper.

@omoliavko if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01436/joss.01436/10.21105.joss.01436.pdf)

**Comment by labarba** [comment]
@omoliavko — Thank you for your submission to JOSS. From a quick inspection of the paper, it's not clear that it meets our [submission criteria](http://joss.theoj.org/about#submission_requirements). In particular:

> - Your software should have an obvious research application

You have a section header on "Research application" but the content is unconvincing—bear in mind we ask that the paper be written for a technical non-specialist. As such, it's unclear how security assessment of IoT devices is a research question. Can you clarify?

**Comment by omoliavko** [comment]
@labarba - thank you for comment. I've rewritten "Research application" part of article. Could you please take a look at it once more? If specific measurement results are needed, I suppose these can be obtained, but conditions under which the measurements will be performed will be artificial in any case.

**Comment by labarba** [comment]
@omoliavko — Thanks for the update on your paper. The editors have discussed this submission on our email list, and remain hesitant about whether it is in-scope for JOSS. We say in our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) that

> The software should have an obvious research application

The goal is to publish articles that allow **citation** of these software works, when used by other researchers. Although you explain _your_ plans to use the software in some research, can you articulate how it may be used by _others_ in pursuit of answering a research question?

**Comment by omoliavko** [comment]
@labarba - I apologize for not explaining potential research applications for mTower in more detail. I've updated the relevant part of paper once more to emphasize that mTower can be used by any developer interested in evaluating performance of TrustZone-based security mechanisms in embedded systems. If necessary, I can provide examples of potential usage scenarios of mTower (descriptions of test cases and  and measurement procedures), but these would be our own tests, not ones developed by third-party researchers.

**Comment by labarba** [comment]
👋 @danielskatz — Could you handle this submission as editor?

**Comment by danielskatz** [comment]
@gkthiruvathukal might be better, but if he doesn't want to, I will

**Comment by gkthiruvathukal** [comment]
@danielskatz and @labarba, I am willing to handle this submission.

**Comment by danielskatz** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
@omoliavko Can you please take a look at the list of reviewers at https://bit.ly/joss-reviewers and suggest a few who may have the relevant expertise to contribute a review for your submission?

**Comment by omoliavko** [comment]
From the list, it looks like gradvohl and federeghe have the relevant expertise.

**Comment by gkthiruvathukal** [comment]
@gradvohl, Would you be willing to contribute a review for this JOSS submission?

**Comment by gkthiruvathukal** [comment]
@federeghe, Would you be willing to contribute a review for this JOSS submission?

**Comment by federeghe** [comment]
@gkthiruvathukal yes, I can review this.

**Comment by gradvohl** [comment]
> 
> 
> @gradvohl, Would you be willing to contribute a review for this JOSS submission?

Yes. I am happy to review it.

**Comment by gkthiruvathukal** [comment]
@whedon assign @federeghe as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @federeghe

**Comment by gkthiruvathukal** [comment]
@whedon assign @gradvohl as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @gradvohl

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1494. Feel free to close this issue now!
