### ISSUE TITLE
[PRE REVIEW]: OnToCode: Template-based code-generation from ontologies

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1437]
**Submitting author:** @fiveop (<a href="http://orcid.org/0000-0003-3931-6670">Philipp Matthias Schäfer</a>)
**Repository:** <a href="https://gitlab.com/dlr-dw/ontocode" target ="_blank">https://gitlab.com/dlr-dw/ontocode</a>
**Version:** 1.0.0
**Editor:** @usethedata
**Reviewers:** @jimmccusker

**Author instructions**

Thanks for submitting your paper to JOSS @fiveop. **Currently, there isn't an JOSS editor assigned** to your paper.

@fiveop if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01437/joss.01437/10.21105.joss.01437.pdf)

**Comment by labarba** [comment]
@fiveop — Thank you for your submission to JOSS. From a quick inspection of the paper, it's not clear that it meets our [submission criteria](http://joss.theoj.org/about#submission_requirements). In particular:

> - Your software should have an obvious research application

The paper says the software was “developed in support of a research project on the merits of automatic transfer of spacecraft part data from suppliers to integrators,” but it’s unclear how this targets a research question (supply chain manufacturing?). Bear in mind we ask that the paper be written for a technical non-specialist. Can you clarify here and expand in the paper?

**Comment by danielskatz** [comment]
👋 @fiveop - I'm going to pause this submission until we get a response to the request above.

**Comment by fiveop** [comment]
@labarba Thank you for your quick inspection and sorry that it took me so long to answer (Now, I have reenabled e-mail notifications).

To address your comment, I have reformulated my text, in particular the quoted paragraph. I hope this clarifies what we use the library for and why it is useful to our (undeniably applied) research. I don't explain it any further in this comment, because eventually the text will stand by itself.

Unsure about the proper process, I have so far only pushed the changes to a separate branch of our repository (see https://gitlab.com/dlr-dw/ontocode/blob/rephrase_application_section/joss/paper.md).

**Comment by danielskatz** [comment]
Thanks - I think we can go ahead with the review.  You will need to put the paper in the master branch at some point, and if you are willing to do it now, it will make the review process easier.

**Comment by danielskatz** [comment]
@whedon generate pdf from branch rephrase_application_section

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch rephrase_application_section. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01437/joss.01437/10.21105.joss.01437.pdf)

**Comment by danielskatz** [comment]
👋 @usethedata - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@fiveop - I hope you are ok with waiting 10 days until @usethedata returns.  If he is not willing/able to edit, I will do it.

**Comment by fiveop** [comment]
@danielskatz Thank you, there's no rush.

**Comment by kyleniemeyer** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by usethedata** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01437/joss.01437/10.21105.joss.01437.pdf)

**Comment by usethedata** [comment]
@fiveop Sorry for the delays on my part.  I've got a couple of requests out for reviewers, but this is in an area where I'm not seeing a lot of reviewers with directly relevant expertise.  If you have suggestions, that could be useful.  You can send me suggestions here or via email wilsonbe [at] ornl [dot] gov.

**Comment by usethedata** [comment]
@whedon assign @jimmccusker as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jimmccusker

**Comment by usethedata** [comment]
I'm still working to find a second reviewer.  However, in the interests of moving forward, I'm going to open up the review issue and I will manually add the second reviewer in the review issue when the person is identified.

**Comment by usethedata** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1513. Feel free to close this issue now!

**Comment by nicholascar** [comment]
I am happy to be an additional reviewer.

**Comment by usethedata** [comment]
@nicholascar -- thanks.  You've been added as a reviewer and have a checklist over on https://github.com/openjournals/joss-reviews/issues/1513
