### ISSUE TITLE
[PRE REVIEW]: DynaMo: Dynamic Body Shape and Motion Capture with Intel RealSense Cameras

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1438]
**Submitting author:** @abhishektha (<a href="http://orcid.org/0000-0003-4260-0488">Abhishektha Boppana</a>)
**Repository:** <a href="https://github.com/anderson-cu-bioastronautics/dynamo_realsense-capture" target ="_blank">https://github.com/anderson-cu-bioastronautics/dynamo_realsense-capture</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewers:** @melund, @ixjlyons

**Author instructions**

Thanks for submitting your paper to JOSS @abhishektha. **Currently, there isn't an JOSS editor assigned** to your paper.

@abhishektha if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1438 with the following error: 

 /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-77e1ffbd3fc0/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-77e1ffbd3fc0/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-77e1ffbd3fc0/lib/whedon/processor.rb:34:in `new'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-77e1ffbd3fc0/lib/whedon/processor.rb:34:in `set_paper'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-77e1ffbd3fc0/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-77e1ffbd3fc0/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.5.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.5.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@abhishektha — Please see the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) in the documentation, and fix your paper—it's missing the bibliography entry in the metadata.

Also, I know that you suggested @Kevin-Mattheus-Moerman as handling editor, and this is in his area of interest, but he has a high editorial load right now. Unless he pops in here and says he's willing to handle one more paper, I'll look for another editor.

**Comment by abhishektha** [comment]
@labarba, I've updated the paper and uploaded it to the main branch of the repository. Does this need to be tagged as a release to be recompiled?

And thank you for searching for another editor!

**Comment by labarba** [comment]
You can tag a release after the reviews, so it includes any improvements. Stay tuned!

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1438 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    11    0    11    0     0     85      0 --:--:-- --:--:-- --:--:--    84
Error reading bibliography ./paper.bib (line 17, column 1):
unexpected "a"
expecting space or ","
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by labarba** [comment]
You're missing a comma after `@article{Windolf:2008`

**Comment by abhishektha** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01438/joss.01438/10.21105.joss.01438.pdf)

**Comment by abhishektha** [comment]
@labarba looks like I finally got the pdf compiled, thank you for your help so far!

**Comment by labarba** [comment]
@moorepants — Do you think you could contribute a review for this JOSS submission? Title: "DynaMo: Dynamic Body Shape and Motion Capture with Intel RealSense Cameras"
Let me know!

**Comment by labarba** [comment]
@melund — Might you be able to contribute a review of this submission for JOSS? Title: "DynaMo: Dynamic Body Shape and Motion Capture with Intel RealSense Cameras"

**Comment by melund** [comment]
@labarba Yes. I would like that. But I don't have access to the cameras, so there is certain parts I won't be able to review in detail. If that is ok then I am in :)

**Comment by labarba** [comment]
Thanks, @melund — We appreciate your best-effort review, given no access to the hardware.

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@whedon assign @melund as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @melund

**Comment by moorepants** [comment]
@labarba I'm sorry but I do not have time to review at this time.

**Comment by labarba** [comment]
👋  @ixjlyons — would you be willing to contribute a review for JOSS on this submission? "DynaMo: Dynamic Body Shape and Motion Capture with Intel RealSense Cameras"

**Comment by ixjlyons** [comment]
Yes I can review this. It might take a couple weeks for me to get to it.

**Comment by labarba** [comment]
@whedon add @ixjlyons as reviewer

**Comment by whedon** [comment]
OK, @ixjlyons is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1466. Feel free to close this issue now!
