### ISSUE TITLE
[PRE REVIEW]: modelDown: automated website generator with interpretable documentation for predictive machine learning models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1439]
**Submitting author:** @matiszak (<a href="http://orcid.org/0000-0001-6335-3434">Mateusz Urbański</a>)
**Repository:** <a href="https://github.com/MI2DataLab/modelDown" target ="_blank">https://github.com/MI2DataLab/modelDown</a>
**Version:** 1.0.0
**Editor:** @alexhanna
**Reviewers:** @terrytangyuan, @pdwaggoner

**Author instructions**

Thanks for submitting your paper to JOSS @matiszak. **Currently, there isn't an JOSS editor assigned** to your paper.

@matiszak if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01439/joss.01439/10.21105.joss.01439.pdf)

**Comment by labarba** [comment]
👋  @alexhanna — Could you handle this submission as editor? Looks like it fits within your sphere of interests. Let me know!

**Comment by alexhanna** [comment]
Sure, I could edit this.

**Comment by alexhanna** [comment]
@whedon set @alexhanna as editor

**Comment by alexhanna** [comment]
@whedon assign @alexhanna as editor

**Comment by whedon** [comment]
OK, the editor is @alexhanna

**Comment by alexhanna** [comment]
@Matiszak could you recommend some editors for this from the list noted above?

**Comment by Matiszak** [comment]
From what I can see in joss_reviewers list these reviewers seem closest to the topic (there would be many more but that could be too much of a choice) :)
@sctyner @pdwaggoner @kellieotto @terrytangyuan @corybrunson @jkarreth @hiendn @strengejacke @kdpeterson51

**Comment by terrytangyuan** [comment]
Happy to review this. Feel free to assign.

**Comment by pdwaggoner** [comment]
Hi - I’d also be happy to review if needed!

**Comment by alexhanna** [comment]
Excellent, thanks @terrytangyuan and @pdwaggoner

**Comment by alexhanna** [comment]
@whedon assign @terrytangyuan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @terrytangyuan

**Comment by alexhanna** [comment]
@whedon add @pdwaggoner as reviewer

**Comment by whedon** [comment]
OK, @pdwaggoner is now a reviewer

**Comment by alexhanna** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1444. Feel free to close this issue now!
