### ISSUE TITLE
[PRE REVIEW]: SlicerITKUltrasound: A 3D Slicer extension for ultrasound image formation, processing, and analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#144]
**Submitting author:** @thewtex (<a href="http://orcid.org/0000-0001-9475-3756">Matthew McCormick</a>)
**Repository:** <a href="https://github.com/KitwareMedical/SlicerITKUltrasound" target ="_blank">https://github.com/KitwareMedical/SlicerITKUltrasound</a>
**Version:** v0.2.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @lassoan

**What this issue is for**

Thanks for submitting your paper to JOSS @thewtex. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@arokem - would you be willing to edit this submission for JOSS?

**Comment by arfon** [comment]
> @arokem - would you be willing to edit this submission for JOSS?

Friendly new year reminder @arokem 😁  - this looks closest to your editorial topic areas.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@thewtex I've started to chase down potential reviewers. Let me know if want to suggest any reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jcfr @aylward if you are not involved in this project, are you able to review (or suggest reviewers for) this submission for http://joss.theoj.org/?

**Comment by Kevin-Mattheus-Moerman** [comment]
@ungi @lassoan if you are not involved in this project, are you able to review (or suggest reviewers for) this submission for http://joss.theoj.org/?

**Comment by thewtex** [comment]
@Kevin-Mattheus-Moerman thanks for your help. @ungi @lassoan or @fedorov may be good reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
.@thewtex Great. @ungi @lassoan @fedorov please let me know if you are able to review this submission.

**Comment by fedorov** [comment]
@Kevin-Mattheus-Moerman can you please point me to your reviewer guidelines? I could not quickly locate them on http://joss.theoj.org/.

**Comment by lassoan** [comment]
I would be happy to review, but not sure what or how. I only see a repository with some code and doc. Is there a rendered document somewhere? Should I review and/or test the code?

**Comment by Kevin-Mattheus-Moerman** [comment]
@fedorov @lassoan the reviewer guidelines are found here http://joss.theoj.org/about#reviewer_guidelines

The review process focuses largely on the claims about the software and the software itself. The paper is a very short document since our view is that properly documented software forms the more important part of the software publication. 

A paper PDF is  generated based on the paper.md file which for this project is found here: 
https://github.com/KitwareMedical/SlicerITKUltrasound/blob/master/paper.md

The paper text is also rendered here: 
http://joss.theoj.org/papers/746880f9243feff57502fae59abce923

This is an example of an accepted paper: 
http://joss.theoj.org/papers/73fcd8f3fcc262db670ec8fccfdad706

You can view the review process that occurred for that paper here:
https://github.com/openjournals/joss-reviews/issues/43

As you can see, once a reviewer is assigned a check list appears which forms the basis of the review process. 

Let me know if you have any other questions. 

Kevin

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @lassoan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @lassoan

**Comment by Kevin-Mattheus-Moerman** [comment]
@fedorov our quasi-automated system can currently handle 1 reviewer which is currently set to @lassoan. Nevertheless I'd like you @fedorov to act as the second reviewer. You can leave comments here for the authors to act on and also follow the checklist that will appear here shortly.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by fedorov** [comment]
it's super confusing that I receive github comments by email that do not show up in this issue

![image](https://cloud.githubusercontent.com/assets/313942/21723218/a0094a70-d3fd-11e6-80e3-f3d95a4d96af.png)

**Comment by lassoan** [comment]
The submission fulfills the JOSS requirements.

My only concern is that the software's scope (as described in the title) is "ultrasound image formation, processing, and analysis", but now it only addresses a small task in ultrasound image formation (scan conversion). Many more modules will be needed to make the software fulfill its promise.

**Comment by Kevin-Mattheus-Moerman** [comment]
@fedorov Apologies. I was having some trouble with our system and deleted those messages to avoid clogging this thread.

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/153. Feel free to close this issue now!

**Comment by arfon** [comment]
@Kevin-Mattheus-Moerman - #153 is the main review issue so we should move the conversation over there.
