### ISSUE TITLE
[PRE REVIEW]: iRODS Bash Completer

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1440]
**Submitting author:** @billyfish (<a href="http://orcid.org/0000-0002-7789-6875">Simon Tyrrell</a>)
**Repository:** <a href="https://github.com/TGAC/irods_bash_completer" target ="_blank">https://github.com/TGAC/irods_bash_completer</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @billyfish. **Currently, there isn't an JOSS editor assigned** to your paper.

@billyfish if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01440/joss.01440/10.21105.joss.01440.pdf)

**Comment by labarba** [comment]
@billyfish — After a pre-review of your submission, and an assessment by the editorial board at large (on our email list), we find that this submission does not quite meet our [submission requirements](http://joss.theoj.org/about#submission_requirements). In particular, while the software seems useful, it falls under the 'Minor utility' category, and we therefore decided not to put it through review. 

Thank you for considering JOSS as a venue for your software, and I hope you'll submit other software with research application in the future.

**Comment by billyfish** [comment]
Hi

Looking at the list of reviewers, it looks llike the following people might
be a good match:

gflofst
gradvohl
gonsie


cheers

Simon

**Comment by labarba** [comment]
Please re-read my previous post. We have decided not to put your submission through review, as is it out of scope.

**Comment by billyfish** [comment]
Ah, sorry I didn't see your previous comment. Thanks anyway.
