### ISSUE TITLE
[REVIEW]: phylosmith: an R-package for reproducible and efficient microbiome analysis with phyloseq-objects

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1442]
**Submitting author:** @schuyler-smith (<a href="http://orcid.org/0000-0001-5720-5611">Schuyler Smith</a>)
**Repository:** <a href="https://github.com/schuyler-smith/phylosmith/" target ="_blank">https://github.com/schuyler-smith/phylosmith/</a>
**Version:** 0.99.0
**Editor:** @karthik
**Reviewer:** @joey711
**Archive:** <a href="https://doi.org/10.5281/zenodo.3251024" target="_blank">10.5281/zenodo.3251024</a>

## Status

[![status](http://joss.theoj.org/papers/4d4780ab16c487764ebe108fa6bcdc2c/status.svg)](http://joss.theoj.org/papers/4d4780ab16c487764ebe108fa6bcdc2c)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/4d4780ab16c487764ebe108fa6bcdc2c"><img src="http://joss.theoj.org/papers/4d4780ab16c487764ebe108fa6bcdc2c/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/4d4780ab16c487764ebe108fa6bcdc2c/status.svg)](http://joss.theoj.org/papers/4d4780ab16c487764ebe108fa6bcdc2c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/schuyler-smith/phylosmith/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@joey711, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @karthik know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/schuyler-smith/phylosmith/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.99.0)?
- [x] **Authorship:** Has the submitting author (@schuyler-smith) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @joey711 it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01442/joss.01442/10.21105.joss.01442.pdf)

**Comment by karthik** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0061217 is OK

MISSING DOIs

- https://doi.org/10.1371/journal.pcbi.1005871 may be missing for title: Ten simple rules for biologists learning to program
- https://doi.org/10.1038/nature11234 may be missing for title: Structure, function and diversity of the healthy human microbiome

INVALID DOIs

- None
```

**Comment by schuyler-smith** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0061217 is OK
- 10.1371/journal.pcbi.1005871 is OK
- 10.1038/nature11234 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by schuyler-smith** [comment]
@karthik I just want to check to make sure that everything is set for this on my end, or if there is anything that I can/need to do. Thank you!

**Comment by karthik** [comment]
@schuyler-smith All good at your end. We're just waiting for the review to come in.

**Comment by karthik** [comment]
Pinged reviewer over email on 06/05

**Comment by joey711** [comment]
Functionality confirmed.
![image](https://user-images.githubusercontent.com/841437/59557774-6fcc3b80-8f97-11e9-9fcc-8e018c1c4941.png)

**Comment by joey711** [comment]
Also tested the `co_occurrence` function, which was re-implemented with Rcpp for performance. Can confirm the performance. I did not test accuracy. 

Speaking of accuracy, that function in particular could use some unit tests to establish a baseline of analytical accuracy. A few other functional unit tests wouldn't hurt.

**Comment by joey711** [comment]
Main deficiencies to address:

- (1) Installation. The documented installation code is insufficient. The phyloseq package is released through bioconductor, and is not installed automatically as a dependency through the indicated `devtools::install_github("phylosmith")` command. More importantly, there are other deeply-implied dependencies related to the Rcpp compilation. I was able to resolve this with the following `Dockerfile` code, starting with an official bioconductor release image (see below).
- (2) Unit tests. There are none.

Dockerfile code:

```
FROM bioconductor/release_core2

# Install phyloseq 
RUN Rscript -e 'if(!requireNamespace("BiocManager", quietly = TRUE)){install.packages("BiocManager")}; BiocManager::install("phyloseq")'

RUN Rscript -e 'install.packages("devtools")'

RUN apt-get update && apt-get install -y --no-install-recommends libudunits2-dev
RUN Rscript -e 'install.packages("units")'

RUN Rscript -e 'install.packages("RcppEigen")'
RUN Rscript -e 'install.packages("RcppParallel")'
RUN Rscript -e 'install.packages("Rtsne")'

# ggforce
RUN apt-get install -y --no-install-recommends libgdal-dev
RUN Rscript -e 'install.packages("ggforce")'

# Install phylosmith
RUN Rscript -e 'devtools::install_github("schuyler-smith/phylosmith")'

# To run R from the command line:
# docker run -ti --user bioc bioconductor/release_core2 R
# docker run -e PASSWORD=rstudio1 -p 8787:8787 phylosmith
```

**Comment by joey711** [comment]
Otherwise looks good. @karthik I'm not sure what to do next? I think author will find it is in their own best interest to address these two minor issues. Afterward, it seems to meet all the criteria and I'm happy to get out of the way.

**Comment by schuyler-smith** [comment]
@joey711 Thank you for the review!
I was aware of the installation dependencies, from dealing with travis-ci, but wasn't sure how convoluted I should make the instructions vs let the user install dependencies on a need-to-need basis. I updated the instructions to include all the dependencies I included in the travis file, and the ones you listed for your installation. Hopefully it's clear and complete!

The unit tests I was admittedly not sure how to include, but had thought about. I am sure I have wasted a lot of my own time by not adding them sooner. I will look into including them!

**Comment by schuyler-smith** [comment]
@karthik I addressed the installation documentation issues, hopefully to a satisfactory level. I will hope to add the unit tests in the near future. If they are needed, please let me know and I will make it a priority.

Is there anything I need to do for the next steps?

**Comment by schuyler-smith** [comment]
@karthik also curious of what the next steps actually are, namely when doi's get assigned so that my labmate can cite. Thanks again for all the help!

**Comment by karthik** [comment]
Thanks @joey711 for this review! @schuyler-smith I'm just returning from a trip so I'll need a day to look over the changes and recommend next steps. I'll update this thread shortly.

**Comment by karthik** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01442/joss.01442/10.21105.joss.01442.pdf)

**Comment by karthik** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0061217 is OK
- 10.1371/journal.pcbi.1005871 is OK
- 10.1038/nature11234 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by karthik** [comment]
@schuyler-smith In preparation for accepting your package, can you archive your software on Zenodo and post a DOI here?

**Comment by karthik** [comment]
@joey711 Thank you! Can you check off the item on automated tests or raise any concerns you have there?

**Comment by schuyler-smith** [comment]
@karthik 10.5281/zenodo.3251024

**Comment by karthik** [comment]
Thanks! Let me get the final sign off from @joey711 and I will proceed.

**Comment by joey711** [comment]
Confirmed. Signed off.

**Comment by karthik** [comment]
@whedon set 10.5281/zenodo.3251024 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3251024" target="_blank">10.5281/zenodo.3251024</a> is the archive.

**Comment by karthik** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0061217 is OK
- 10.1371/journal.pcbi.1005871 is OK
- 10.1038/nature11234 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/782

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/782, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by karthik** [comment]
Over to you, @joss-eics

**Comment by schuyler-smith** [comment]
@karthik @joey711 Thank you both for your help and efforts in this!

**Comment by danielskatz** [comment]
Thanks @joey711 for reviewing and @karthik for editing!

**Comment by danielskatz** [comment]
@arfon - can you provide any comment/fix on the name that is broken across lines 2 and 3 of the PDF?

**Comment by danielskatz** [comment]
@schuyler-smith - Here are  bunch of corrections to the paper:

- "Presented here is phylosmith" could be "This paper presents phylosmith"  (and perhaps this will also fix the breaking phylosmith at the end of line 2 and the start of line 3)
- "Functions that will either return a transformed version of the input phyloseq object, a subset version, or extracted data from it on set parameters" is not a complete sentence.
- "which can suffers" should be "which can suffer"
- "from convergence getting stuck in local minima" could be "from converging to local minima"
- "As of this announcement," could be "As of publication of this paper,"
- "the age of big-data that biologists" could be "the age of big-data, biologists"
- "that their should" should be "that there should"
- "there has developed a formulaic approach to analysis" could be "a formulaic approach to analysis has developed"
- "i.e. incorrect" should be "e.g., incorrect"
- "and medium, users" should be "and intermediate users"
- "a barrier as they" should be "a barrier, as they"
- "the package data.table" could be "the data.table package"
- "on answering biological." needs another word at the end, perhaps "questions"

**Comment by danielskatz** [comment]
@schuyler-smith - also, please update the title of the Zenodo archive to match the title of the paper: "phylosmith: an R-package for reproducible and efficient microbiome analysis with phyloseq-objects"

**Comment by schuyler-smith** [comment]
@danielskatz thank you! This process has certainly opened my eyes to my inability to proofread my own work!

I addressed all the corrections you listed, and edited the Zenodo release title.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0061217 is OK
- 10.1371/journal.pcbi.1005871 is OK
- 10.1038/nature11234 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/783

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/783, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01442/joss.01442/10.21105.joss.01442.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0061217 is OK
- 10.1371/journal.pcbi.1005871 is OK
- 10.1038/nature11234 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/784

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/784, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@schuyler-smith - I also noticed some bib issues - suggested fixes in https://github.com/schuyler-smith/phylosmith/pull/4

In addition, some of the R & R package citations seem a little off - can you check the citations in the bib part of the pdf and make sure these look correct and complete?

**Comment by schuyler-smith** [comment]
@danielskatz I merged your bib fixes. The data.table package was not officially published, that I can find. Matt Dowel just has extensive online presence for it, but I wanted to cite it. Maybe there is a better way?
ggplot2 appears to be cited most through Hadley Wickham's book, that I used for citation, so it doesn't have a DOI or anything of the sort. Any suggestion on that is welcome too.

Are these what you were referring too?

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01442/joss.01442/10.21105.joss.01442.pdf)

**Comment by schuyler-smith** [comment]
@danielskatz I see a couple corrections to make, sorry.

**Comment by schuyler-smith** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1442 with the following error: 

 Error reading bibliography ./paper.bib (line 15, column 9):
unexpected ","
expecting white space
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
The first ref should have DOI https://doi.org/10.1038/nature09944 added
The fourth ref should have DOI http://dx.doi.org/10.18637/jss.v040.i08 added

there could also be more...

**Comment by schuyler-smith** [comment]
@danielskatz you are correct, I found a couple other DOIs. I think i blindly trusted the google scholar bib citations. Hopefully it looks better.

**Comment by schuyler-smith** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01442/joss.01442/10.21105.joss.01442.pdf)

**Comment by danielskatz** [comment]
ok, looks good now  - thanks

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0061217 is OK
- 10.18637/jss.v040.i08 is OK
- 10.1371/journal.pcbi.1005871 is OK
- 10.1038/nature11234 is OK
- 10.1038/nature07540 is OK
- 10.1038/nature09944 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/785

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/785, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1141795064085196800) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/786
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01442](https://doi.org/10.21105/joss.01442)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01442/status.svg)](https://doi.org/10.21105/joss.01442)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01442">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01442/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01442/status.svg
   :target: https://doi.org/10.21105/joss.01442
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01442/status.svg)](https://doi.org/10.21105/joss.01442)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
