### ISSUE TITLE
[PRE REVIEW]: FRIDGe: Fast Reactor Input Generator

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1443]
**Submitting author:** @ryanstwrt (<a href="http://orcid.org/0000-0003-4867-6555">Ryan Stewart</a>)
**Repository:** <a href="https://github.com/ryanstwrt/FRIDGe" target ="_blank">https://github.com/ryanstwrt/FRIDGe</a>
**Version:** v1.0.0
**Editor:** @katyhuff
**Reviewers:** @kellyrowland, @pshriwise

**Author instructions**

Thanks for submitting your paper to JOSS @ryanstwrt. The JOSS editor @katyhuff, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ryanstwrt if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @katyhuff it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@katyhuff) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01443/joss.01443/10.21105.joss.01443.pdf)

**Comment by labarba** [comment]
👋 @katyhuff — The author suggested you as editor, and the submission is clearly in your sphere of interests, so I went ahead and assigned you. Let me know if you have any issues.

**Comment by katyhuff** [comment]
@ryanstwrt I'm terribly sorry for the delay. I somehow missed this notification! I apologize. I expect to be able to find reviewers today. (related -- have you heard of PyNE? I think you could be an excellent contributor, if you aren't already).

Initially, I know that @kellyrowland would be an exceptional reviewer for this work, if she is available. @kellyrowland :  

* @kellyrowland: Dr. Rowland, are you able to and interested in taking on this review?
* This submission is in need of expertise in nuclear engineering as well as familiarity with the systems and languages involved ([tools]). 
* Title: 
* Summary: FRIDGe: Fast Reactor Input Generator
* Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01443/joss.01443/10.21105.joss.01443.pdf
* Submitting author: @ryanstwrt
* Repository: https://github.com/ryanstwrt/FRIDGe
* Version: v1.0.0

**Comment by ryanstwrt** [comment]
@katyhuff No problem! I have heard of PyNE, part of my inspiration for creating FRIDGe was the work everyone with PyNE did to help make NE research more available. I'll look into areas of PyNE where I might be able to contribute, thanks for the info.

**Comment by kellyrowland** [comment]
@katyhuff I'm interested and able to take on this review; thanks for reaching out to me.

**Comment by katyhuff** [comment]
Thanks @kellyrowland! 

@pshriwise I think you would be an excellent reviewer for this JOSS submission. Some more information about reviewing for JOSS can be found here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

@pshriwise: Dr. Shriwise, are you able to and interested in taking on this review for the Journal of Open Source Software?
This submission is in need of expertise in nuclear engineering as well as familiarity with the systems and languages involved (MCNP, Python, yaml, LaTeX).
Title: FRIDGe: Fast Reactor Input Generator
Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01443/joss.01443/10.21105.joss.01443.pdf
Submitting author: @ryanstwrt
Repository: https://github.com/ryanstwrt/FRIDGe
Version: v1.0.0

**Comment by katyhuff** [comment]
@whedon assign @kellyrowland as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kellyrowland

**Comment by pshriwise** [comment]
@katyhuff @whedon I'd be happy to look it over. Thanks for thinking of me!

**Comment by katyhuff** [comment]
Thanks @pshriwise ! 

Dear both (@kellyrowland @pshriwise ): A key requirement of JOSS submissions is that a submission should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler).  Minor ‘utility’ packages, including ‘thin’ API clients, are not acceptable.

I want to let you know that I contemplated whether this package is a minor utility, and I determined it to be somewhat on the boundary of these two. It certainly will make research faster and easier for folks who use it. So - as I tend to be generous with this type of "novelty" and "significance" assessment - I am approving it to move forward into the review. However, it's possible that this package overlaps somewhat with the python features of new MCNP Tools python package (first distributed in MCNP 6.2... https://laws.lanl.gov/vhosts/mcnp.lanl.gov/pdf_files/la-ur-17-21779.pdf). I hope you'll consider this question completely, but generously, when reviewing the statement of need.

**Comment by katyhuff** [comment]
@whedon add @pshriwise as reviewer

**Comment by whedon** [comment]
OK, @pshriwise is now a reviewer

**Comment by katyhuff** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1486. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Ok @ryanstwrt , @kellyrowland , and @pshriwise let's head over to #1486 .
