### ISSUE TITLE
[REVIEW]: modelDown: automated website generator with interpretable documentation for predictive machine learning models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1444]
**Submitting author:** @matiszak (<a href="http://orcid.org/0000-0001-6335-3434">Mateusz Urbański</a>)
**Repository:** <a href="https://github.com/MI2DataLab/modelDown" target ="_blank">https://github.com/MI2DataLab/modelDown</a>
**Version:** v1.0.1
**Editor:** @alexhanna
**Reviewer:** @terrytangyuan, @pdwaggoner
**Archive:** <a href="https://doi.org/10.5281/zenodo.3247303" target="_blank">10.5281/zenodo.3247303</a>

## Status

[![status](http://joss.theoj.org/papers/d8c6609e293913021f03e2bb0ef759a1/status.svg)](http://joss.theoj.org/papers/d8c6609e293913021f03e2bb0ef759a1)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d8c6609e293913021f03e2bb0ef759a1"><img src="http://joss.theoj.org/papers/d8c6609e293913021f03e2bb0ef759a1/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d8c6609e293913021f03e2bb0ef759a1/status.svg)](http://joss.theoj.org/papers/d8c6609e293913021f03e2bb0ef759a1)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/MI2DataLab/modelDown" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@terrytangyuan & @pdwaggoner, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @alexhanna know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MI2DataLab/modelDown">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.1
- [x] **Authorship:** Has the submitting author (@matiszak) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MI2DataLab/modelDown">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.1
- [x] **Authorship:** Has the submitting author (@matiszak) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @terrytangyuan, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01444/joss.01444/10.21105.joss.01444.pdf)

**Comment by pdwaggoner** [comment]
@whedon check DOIs

**Comment by pdwaggoner** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.18637/jss.v082.i11 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by pdwaggoner** [comment]
Hi - Sorry for the delay. Overall, this looks really good! Here are a few comments for things I think should be addressed/fixed:

1. The license on the main repo (Apache 2.0) doesn't match the license at the pkgdown "documentation" site (GPL-3 -- https://mi2datalab.github.io/modelDown/). Both are acceptable by OSI, but I would clarify and fix.

2. Installation instructions are included in the vignette, but I would like to see something a little more clear and up front on the repo README landing (e.g., `Installation for Dev Version: xxx // Installation for Stable Version: xxx`). Something simple and straightforward for the user would be a useful place to start interaction with the package.

3. Typo on page 1 in the paragraph starting with "The modelDown package is designed..." in the sentence, "In THE case of pkgdown... while in THE case of modelDown..."

4. Typo on page 2, in the paragraph starting with "The 'Model performance'..." -- the word "lab" should be "tab". There are many other small grammatical errors/typos throughout. I would recommend a closer second (or third) read-through of the paper to root these out and correct them. Should be a simple fix.

5. I don't think the first sentence of the Summary section (which is slightly grammatically incorrect) is too useful. 

6. I am not sure if the authors were intending to include a sample screenshot or figure in the two places with hyphens (e.g., "-Example model performance tab."), but if not, I would highly recommend including a screenshot to give the user/reader an idea of what the output looks like. If so, then perhaps the authors forgot to include this in the manuscript. I would include some demo figures either way.

7. An example/demo of the code would be a helpful addition to the paper. Perhaps just before the explanation of all of the tabs produced in the output. It would be nice just to see the code/package in action within the JOSS paper, even though examples are included in the package vignette.

8. I would also include a note on how people can contribute (if you want them to), via issue tickets, PRs, or whatever this might look like.

Other than these things, the paper and software all looks great! The authors did a good job here and I think the package will be widely accepted and used. Great work!

**Comment by Matiszak** [comment]
Thank you very much for your review and sorry for the delay. I hope I took care of all the points, your input was very helpful. Could you see if there is anything else worth changing ?

@whedon generate pdf

**Comment by Matiszak** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01444/joss.01444/10.21105.joss.01444.pdf)

**Comment by pdwaggoner** [comment]
This all looks really great to me! Thanks for making the changes. I would say its good to go from my perspective. @alexhanna back over to you. Thanks!

**Comment by terrytangyuan** [comment]
Just went over the paper and the checklist. The paper looks great to me. Great job @Matiszak!

**Comment by alexhanna** [comment]
Thank you for your reviews, @pdwaggoner and @terrytangyuan! And for making the edits, @Matiszak.

**Comment by alexhanna** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by alexhanna** [comment]
@Matiszak do you have an archive DOI for the repository? We need that for acceptance.

**Comment by arfon** [comment]
> @Matiszak do you have an archive DOI for the repository? We need that for acceptance.

Also, @Matiszak - please make sure that you make new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive. For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

**Comment by Matiszak** [comment]
The 1.0.1 version including the changes that have resulted from this review has been archived at 10.5281/zenodo.3247303
Also it set as official release on https://github.com/MI2DataLab/modelDown and also published to CRAN: https://cran.r-project.org/web/packages/modelDown/index.html

Thank you very much for your work, please let me know if there is anything else to do.

**Comment by alexhanna** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by alexhanna** [comment]
@whedon set 10.5281/zenodo.3247303 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3247303" target="_blank">10.5281/zenodo.3247303</a> is the archive.

**Comment by alexhanna** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.18637/jss.v082.i11 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/781

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/781, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by alexhanna** [comment]
@openjournals/joss-eics this looks ready for acceptance.

**Comment by danielskatz** [comment]
I've suggested a bunch of text changes for the paper in https://github.com/MI2DataLab/modelDown/pull/72

**Comment by Matiszak** [comment]
@danielskatz Thank you, the PR is merged.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01444/joss.01444/10.21105.joss.01444.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.18637/jss.v082.i11 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/794

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/794, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
👋 @Matiszak - please also merge https://github.com/MI2DataLab/modelDown/pull/74, which has fixes for the cases of words in the bibtex. Then ping @openjournals/joss-eics for the final acceptance

**Comment by Matiszak** [comment]
@whendon generate pdf

**Comment by Matiszak** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01444/joss.01444/10.21105.joss.01444.pdf)

**Comment by Matiszak** [comment]
@openjournal/joss-eics Merged :+1:

**Comment by Matiszak** [comment]
@openjournals/joss-eics Merged :+1:

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/797

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/797, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.18637/jss.v082.i11 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1144129095669862405) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/798
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01444](https://doi.org/10.21105/joss.01444)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01444/status.svg)](https://doi.org/10.21105/joss.01444)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01444">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01444/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01444/status.svg
   :target: https://doi.org/10.21105/joss.01444
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01444/status.svg)](https://doi.org/10.21105/joss.01444)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
