### ISSUE TITLE
[REVIEW]: FSharpGephiStreamer: An idiomatic bridge between F# and network visualization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1445]
**Submitting author:** @muehlhaus (<a href="http://orcid.org/0000-0003-3925-6778">Timo Mühlhaus</a>)
**Repository:** <a href="https://github.com/CSBiology/FSharpGephiStreamer" target ="_blank">https://github.com/CSBiology/FSharpGephiStreamer</a>
**Version:** 1.1.6
**Editor:** @danielskatz
**Reviewer:** @cgravill, @PrashantVaidyanathan
**Archive:** <a href="https://doi.org/10.5281/zenodo.3246352" target="_blank">10.5281/zenodo.3246352</a>

## Status

[![status](http://joss.theoj.org/papers/353e97af96ed27c448d32501fda34aed/status.svg)](http://joss.theoj.org/papers/353e97af96ed27c448d32501fda34aed)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/353e97af96ed27c448d32501fda34aed"><img src="http://joss.theoj.org/papers/353e97af96ed27c448d32501fda34aed/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/353e97af96ed27c448d32501fda34aed/status.svg)](http://joss.theoj.org/papers/353e97af96ed27c448d32501fda34aed)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/CSBiology/FSharpGephiStreamer" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@cgravill & @PrashantVaidyanathan, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/CSBiology/FSharpGephiStreamer">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.1.6
- [x] **Authorship:** Has the submitting author (@muehlhaus) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/CSBiology/FSharpGephiStreamer">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.1.6
- [x] **Authorship:** Has the submitting author (@muehlhaus) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @cgravill, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01445/joss.01445/10.21105.joss.01445.pdf)

**Comment by danielskatz** [comment]
👋 @cgravill & @PrashantVaidyanathan - thanks for agreeing to review.

Please carry out your review in this issue by updating your checklist above. The checklist gives me some insight into the review process and any blocking issues, as well as being the full set of items that once passed will lead us to accept the submission.

And please fully read the the top 2 comments in this issue.  If you have any problems or questions, please feel free to let me know.

**Comment by danielskatz** [comment]
👋 @cgravill & @PrashantVaidyanathan - Is there anything I can do to help with your reviews?

If you can at least check your "Conflict of interest" and "Code of Conduct" boxes when you feel ready, that would help me know that the processes are working and that you are starting :)

(And @PrashantVaidyanathan, yes, I do remember that you will not be working on this 'till next week due to travel)

**Comment by cgravill** [comment]
Sure, completed those steps @danielskatz 

How precisely should these requirements be taken? For example, they have a plain text license but it includes a .txt extension. Is that OK?

**Comment by danielskatz** [comment]
You could ask that this be changed to have no extension, since the JOSS criteria says "Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?" and since the GitHub guidance for this is for it to either have no extension or be .md.  You could open an issue in the software repo to request this, and put in a comment here pointing to that issue.

**Comment by cgravill** [comment]
I'm not aware it's a conflict of interest but for full transparency:
- @PrashantVaidyanathan and I are both employed in a group at the same institution: Microsoft Research
- I'm also a contributor to https://github.com/Microsoft/automatic-graph-layout an alternative network library to Gephi, and tools to connect to it from F#

**Comment by danielskatz** [comment]
> @PrashantVaidyanathan and I are both employed in a group at the same institution: Microsoft Research

Are you both employed in the same group? Do you work together on the same projects?

> I'm also a contributor to https://github.com/Microsoft/automatic-graph-layout an alternative network library to Gephi, and tools to connect to it from F#

Expertise in the subject is good.

With both factors in mind, do you feel that you can provide a fair and unbiased review and advise?

**Comment by cgravill** [comment]
Yes, we're both employed in this group https://www.microsoft.com/en-us/research/group/biological-computation/ and have overlap in projects.

We've not discussed the contents of this work.

I feel I'm able to give a fair and unbiased review.

**Comment by danielskatz** [comment]
Thanks for providing this info, @cgravill

Given the particular circumstances of this software and this conflict, we (the associate editors-in-chief) have decided that we will note it and waive it for this review.  So please continue the review.

**Comment by danielskatz** [comment]
👋 @PrashantVaidyanathan - have you had a chance to start looking at this yet?

**Comment by PrashantVaidyanathan** [comment]
@danielskatz Apologies for the delay. I had spotty net connection over the last few days while travelling. I've started reviewing the submission now.

**Comment by danielskatz** [comment]
It looks like there are some issues being worked through, which is good - @muehlhaus and @cgravill and @PrashantVaidyanathan, please let me know if anything seems to get stuck

**Comment by danielskatz** [comment]
👋 @muehlhaus and @cgravill and @PrashantVaidyanathan - Can I get an update from you on this?

**Comment by PrashantVaidyanathan** [comment]
@danielskatz We identified some bugs Specifically https://github.com/CSBiology/FSharpGephiStreamer/issues/15 and https://github.com/CSBiology/FSharpGephiStreamer/issues/16
And it looks like these have been fixed. The authors also added an enhancement (for the documentation)

I'm close to finishing my review.

**Comment by cgravill** [comment]
There were some issues, that sound like they've now been resolved. Some of it is on a pull request https://github.com/CSBiology/FSharpGephiStreamer/pull/23 but I'm planning to try out the test release, hopefully this week.

**Comment by muehlhaus** [comment]
@danielskatz I think this review process is very useful and helps us a lot to improve the quality of the FSharpGephiStreamer. Thank you all for that. We resolved the issues and will close all after successful testing within the next few days.

**Comment by PrashantVaidyanathan** [comment]
I've completed my review (and the checklist)
@danielskatz and @muehlhaus 
For the point: Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified? 
I believe that while there isn't an explicit test in the documentation, the simple example: https://csbiology.github.io/FSharpGephiStreamer/SimpleNetwork.html serves as a manual step to ensure that the FSharpGephiStreamer works as intended. 

For all other points, I think this project is well documented and the software works as intended and is very useful.

**Comment by danielskatz** [comment]
Thanks @PrashantVaidyanathan

**Comment by cgravill** [comment]
I'm satisfied with the changes that it's now clearer how to install and operate the tool.

Everything is checked off and it looks like it's ready to proceed @danielskatz

**Comment by danielskatz** [comment]
@muehlhaus - Can you make a deposit of the current repo into an archive (e.g. zenodo via https://guides.github.com/activities/citable-code/) and tell me the DOI? If you also need to update the version number, let me know that as well.

**Comment by danielskatz** [comment]
Thanks @cgravill

**Comment by muehlhaus** [comment]
@danielskatz - Great. I just enabled Zenodo for our repository. The DOI is: 10.5281/zenodo.3246352
Thank you.

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3246352.svg)](https://doi.org/10.5281/zenodo.3246352)

**Comment by danielskatz** [comment]
Is the version still 1.1.0?

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3246352 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3246352" target="_blank">10.5281/zenodo.3246352</a> is the archive.

**Comment by muehlhaus** [comment]
@danielskatz The latest version is 1.1.6

**Comment by danielskatz** [comment]
@whedon set 1.1.6 as version

**Comment by whedon** [comment]
OK. 1.1.6 is the version.

**Comment by muehlhaus** [comment]
@cgravill and @PrashantVaidyanathan . Again, thank you so much for your work. It was a really constructive review process.

**Comment by danielskatz** [comment]
:wave: @arfon can you take this from here?

**Comment by kMutagene** [comment]
> @cgravill and @PrashantVaidyanathan . Again, thank you so much for your work. It was a really constructive review process.

I second that. Thank you for the constructive comments and the patience while resolving the issues!

**Comment by cgravill** [comment]
Thanks for sharing your library and responding so quickly to issues. Also looking forward there being more F# in biology coming out https://github.com/CSBiology

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/1159876.1159884 is OK
- 10.1145/2429376.2429378 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/762

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/762, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1139615583866163200) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/763
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01445](https://doi.org/10.21105/joss.01445)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01445/status.svg)](https://doi.org/10.21105/joss.01445)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01445">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01445/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01445/status.svg
   :target: https://doi.org/10.21105/joss.01445
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01445/status.svg)](https://doi.org/10.21105/joss.01445)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
