### ISSUE TITLE
[PRE REVIEW]: cppduals: a nestable vectorized templated dual number library for C++11

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1446]
**Submitting author:** @tesch1 (<a href="http://orcid.org/0000-0003-4096-1562">Michael Tesch</a>)
**Repository:** <a href="https://gitlab.com/tesch1/cppduals" target ="_blank">https://gitlab.com/tesch1/cppduals</a>
**Version:** v0.1.0
**Editor:** @danielskatz
**Reviewers:** @StewMH, @mdavezac

**Author instructions**

Thanks for submitting your paper to JOSS @tesch1. **Currently, there isn't an JOSS editor assigned** to your paper.

@tesch1 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01446/joss.01446/10.21105.joss.01446.pdf)

**Comment by arfon** [comment]
:wave: @tesch1 - thanks for your submission to JOSS.

After giving your paper a quick read, I think it would be good to expand a little on this bullet from our [paper requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain):

> A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience

We also have this requirement for our papers: 

> Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it.

Are there ongoing research projects that make use of this software?

**Comment by tesch1** [comment]
Thanks for the quick reply.

I've recalibrated the summary a bit, is there anything more specific about
what kind of diverse non-specialist audience is intended?  Academics with
some math, at least?

Yes, there are ongoing research projects using the software, indeed one of
them is mentioned, though there are no citations at this time.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01446/joss.01446/10.21105.joss.01446.pdf)

**Comment by arfon** [comment]
> I've recalibrated the summary a bit, is there anything more specific about what kind of diverse non-specialist audience is intended?  

Thanks, I think that addition to the introduction helps.

Could you take a look at this [list of potential reviewers](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing) and identify any good candidates to review this submission?

**Comment by arfon** [comment]
@danielskatz - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @tesch1 - I repeat Arfon's request: 

Could you take a look at this [list of potential reviewers](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing) and identify any good candidates to review this submission?

**Comment by tesch1** [comment]
Yes, I will have a look.

**Comment by danielskatz** [comment]
👋 @tesch1 - Any suggestions?

**Comment by tesch1** [comment]
Perhaps @leios, @vyasr, @mlxd, or @StewMH would be good?

**Comment by danielskatz** [comment]
👋  @leios, @vyasr, @mlxd, or @StewMH - would a couple of you be willing to review this for JOSS?  Or if not, would you have suggestions for others who might be good fits?

**Comment by StewMH** [comment]
Hi Dan, Michael,

I'd be happy to review it.

Cheers,
Stewart

**Comment by danielskatz** [comment]
Thanks @StewMH - as soon as we get one more reviewer, we will start the actual review.

**Comment by danielskatz** [comment]
@whedon assign @StewMH as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @StewMH

**Comment by mlxd** [comment]
Sorry @tesch1 @danielskatz , don't think that I will have time for the coming 3 weeks.
If things haven't moved forward by then, I'll be happy to jump in.

**Comment by danielskatz** [comment]
Thanks @mlxd - let's see if we can find someone else in this case

**Comment by danielskatz** [comment]
👋 @poulson and @VivianePons - can you help with suggestions for a second reviewer for this submission?

**Comment by danielskatz** [comment]
👋 @mdavezac - you've been suggested as the perfect reviewer for this.  Would you be willing to do this?  (see [JOSS reviewer guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html))

**Comment by vyasr** [comment]
Sorry I haven't been more responsive, I unfortunately won't be available to review this paper.

**Comment by mdavezac** [comment]
I'd be happy to review it.

**Comment by danielskatz** [comment]
Great, thanks - we'll start the review now then

**Comment by danielskatz** [comment]
@whedon add @mdavezac as reviewer

**Comment by whedon** [comment]
OK, @mdavezac is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1487. Feel free to close this issue now!
