### ISSUE TITLE
[PRE REVIEW]: Phy2HTML: A simple method for displaying phylogenies in webpages

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1447]
**Submitting author:** @msrosenberg (<a href="http://orcid.org/0000-0001-7882-2467">Michael S. Rosenberg</a>)
**Repository:** <a href="https://github.com/msrosenberg/Phy2HTML" target ="_blank">https://github.com/msrosenberg/Phy2HTML</a>
**Version:** 1.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @drmsrosenberg. **Currently, there isn't an JOSS editor assigned** to your paper.

@drmsrosenberg if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1447 with the following error: 

 /app/vendor/ruby-2.5.3/lib/ruby/2.5.0/psych.rb:402:in `parse': (tmp/1447/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.5.3/lib/ruby/2.5.0/psych.rb:402:in `parse_stream'
	from /app/vendor/ruby-2.5.3/lib/ruby/2.5.0/psych.rb:350:in `parse'
	from /app/vendor/ruby-2.5.3/lib/ruby/2.5.0/psych.rb:263:in `load'
	from /app/vendor/ruby-2.5.3/lib/ruby/2.5.0/psych.rb:498:in `block in load_file'
	from /app/vendor/ruby-2.5.3/lib/ruby/2.5.0/psych.rb:497:in `open'
	from /app/vendor/ruby-2.5.3/lib/ruby/2.5.0/psych.rb:497:in `load_file'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-fc4c5c749ca9/lib/whedon.rb:95:in `load_yaml'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-fc4c5c749ca9/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-fc4c5c749ca9/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-fc4c5c749ca9/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-fc4c5c749ca9/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-fc4c5c749ca9/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.5.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.5.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @msrosenberg - many thanks for your submission to JOSS. 

Unfortunately this submission isn't allowed in JOSS as it falls into our ['minor utility'](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) category.
