### ISSUE TITLE
[PRE REVIEW]: WRF-CMake: integrating CMake support into the Advanced Research WRF (ARW) modelling system

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1449]
**Submitting author:** @letmaik (<a href="http://orcid.org/0000-0003-3299-1382">Maik Riechert</a>)
**Repository:** <a href="https://github.com/WRF-CMake/WRF" target ="_blank">https://github.com/WRF-CMake/WRF</a>
**Version:** 4
**Editor:** @arfon
**Reviewers:** @zbeekman, @andreas-h

**Author instructions**

Thanks for submitting your paper to JOSS @letmaik. The JOSS editor @arfon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@letmaik if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@arfon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1449 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
Downloading of the repository (to analyze the language) for issue #1449 failed with the following error: 

 Cloning into 'tmp/1449'...

**Comment by arfon** [comment]
:wave: @letmaik - many thanks for your submission to JOSS. Please review our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) and prepare a `paper.md` file (and references in a bibtex file) and add them to the repository.

**Comment by letmaik** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1449 with the following error: 

 /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-fc4c5c749ca9/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-fc4c5c749ca9/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-fc4c5c749ca9/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-fc4c5c749ca9/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-fc4c5c749ca9/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-fc4c5c749ca9/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.5.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.5.0/bin/whedon:23:in `<main>'

**Comment by letmaik** [comment]
@arfon Is it possible to submit papers to JOSS without affiliation?

**Comment by arfon** [comment]
@letmaik - it is, but it's kind of a hack:

```
---
title: 'WRF-CMake: integrating CMake support into the Advanced Research WRF (ARW) modelling system'
tags:
  - cmake
  - fortran
  - meteorology
  - weather
  - modelling
  - nwp
  - wrf
authors:
  - name: M. Riechert
    orcid: 0000-0003-3299-1382
    affiliation: 1
  - name: D. Meyer
    orcid: 0000-0002-7071-7547
    affiliation: 1
affiliations:
  - name: None
    index: 1
date: 14 May 2019
bibliography: paper.bib
---
```

**Comment by letmaik** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01449/joss.01449/10.21105.joss.01449.pdf)

**Comment by letmaik** [comment]
@whedon generate pdf from branch joss-paper

@arfon We changed layout slightly and also replaced affiliation by "Independent scholar" which makes more sense than "None", see also https://journals.ametsoc.org/doi/full/10.1175/BAMS-D-12-00171.1 where they've done the same.

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper
. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1449 with the following error: 

 error: pathspec 'joss-paper?' did not match any file(s) known to git.
Can't find any papers to compile :-(

**Comment by letmaik** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01449/joss.01449/10.21105.joss.01449.pdf)

**Comment by dmey** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01449/joss.01449/10.21105.joss.01449.pdf)

**Comment by dmey** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01449/joss.01449/10.21105.joss.01449.pdf)

**Comment by dmey** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01449/joss.01449/10.21105.joss.01449.pdf)

**Comment by dmey** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01449/joss.01449/10.21105.joss.01449.pdf)

**Comment by dmey** [comment]
@letmaik There is still a minor issue with the last paragraph on page 2 (it needs to be moved _after_ Figure 1 on page 3) but I would suggest leaving this for now given that we may need to make changes to the summary at review time.

**Comment by letmaik** [comment]
@dmey Yes, I agree.

@arfon We're ready, what's next?

**Comment by arfon** [comment]
@letmaik @dmey - could you suggest some potential reviewers for this submission? Either community members you know or by [looking at this list of volunteers](https://bit.ly/joss-reviewers).

**Comment by letmaik** [comment]
This is the list of reviewers we think would be relevant for our paper (in order):
https://github.com/zbeekman 
https://github.com/dvalters 
https://github.com/hainesr 
https://github.com/johnrobertlawson 
https://github.com/andreas-h 
https://github.com/bjarketol 
https://github.com/rowanc1 
https://github.com/tomchor 
https://github.com/schoenemeyer

**Comment by arfon** [comment]
@zbeekman @dvalters - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The software under consideration is here: https://github.com/WRF-CMake/WRF and you can learn more about the project in this [short overview paper](https://github.com/openjournals/joss-papers/blob/joss.01449/joss.01449/10.21105.joss.01449.pdf).

**Comment by zbeekman** [comment]
@afron: I'd be happy to review this submission!

**Comment by arfon** [comment]
@whedon add @zbeekman as reviewer

**Comment by whedon** [comment]
OK, @zbeekman is now a reviewer

**Comment by arfon** [comment]
> @afron: I'd be happy to review this submission!

Excellent, thanks @zbeekman! I'd like to find at least two reviewers for this submission so for now please sit tight while I find another reviewer.

**Comment by zbeekman** [comment]
Sure! Just ping me with next steps once you’re ready. This will be my first
JOSS review. I’ve read through most of the docs so far. I’ve taken a
cursory look at the repository and will read through the paper.

**Comment by arfon** [comment]
@andreas-h @bjarketol - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The software under consideration is here: https://github.com/WRF-CMake/WRF and you can learn more about the project in this [short overview paper](https://github.com/openjournals/joss-papers/blob/joss.01449/joss.01449/10.21105.joss.01449.pdf)

**Comment by andreas-h** [comment]
Yes, I'd be happy to review this.

Tue May 21 13:08:56 GMT+02:00 2019 Arfon Smith <notifications@github.com>:

**Comment by arfon** [comment]
@whedon add @andreas-h as reviewer

**Comment by whedon** [comment]
OK, @andreas-h is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1468. Feel free to close this issue now!

**Comment by arfon** [comment]
@zbeekman, @andreas-h - many thanks for agreeing to review this submission. See you over in #1468 where the full review will take place.
