### ISSUE TITLE
[PRE REVIEW]: eLabFTW - a free and open source electronic lab notebook

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#145]
**Submitting author:** @NicolasCARPi (<a href="http://orcid.org/0000-0002-7494-5555">Nicolas CARPI</a>)
**Repository:** <a href="https://github.com/elabftw/elabftw" target ="_blank">https://github.com/elabftw/elabftw</a>
**Version:** 1.4.0
**Editor:** @cMadan
**Reviewer:** @raamana

**What this issue is for**

Thanks for submitting your paper to JOSS @NicolasCARPi. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by raamana** [comment]
@whedon assign me as a reviewer!

**Comment by cMadan** [comment]
@whedon assign @raamana as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @raamana

**Comment by cMadan** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/146. Feel free to close this issue now!

**Comment by cMadan** [comment]
For anyone coming across this pre-review issue from Twitter or otherwise, feel free to make suggestions in the review thread (https://github.com/openjournals/joss-reviews/issues/146) or as issues in the project's repository (https://github.com/elabftw/elabftw). While we don't need more reviewers, more constructive feedback to the authors is always good! :)
