### ISSUE TITLE
sample data

### ISSUE THREAD

**Issue by alexgarciac** [openjournals/joss-reviews#1452]
hi. as this is python and a py package there should be some sample data so that anyone could test that the package and all the assertions being made in the paper do really work. I read the paper and there is a lot about a lot but there is no sample data to test the package.

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1452 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
Hi @alexgarciac - please don’t open issues on this repository - the only issues in this repository should be reviews for JOSS papers. 

If you’re reviewing a JOSS submission, please open issues on that repository.
