### ISSUE TITLE
[PRE REVIEW]: rtweet: Collecting and analyzing Twitter data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1454]
**Submitting author:** @mkearney (<a href="http://orcid.org/0000-0002-0730-4694">Michael Wayne Kearney</a>)
**Repository:** <a href="https://github.com/mkearney/rtweet" target ="_blank">https://github.com/mkearney/rtweet</a>
**Version:** v0.6.9
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @mkearney. **Currently, there isn't an JOSS editor assigned** to your paper.

@mkearney if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1454 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01454/joss.01454/10.21105.joss.01454.pdf)

**Comment by mkearney** [comment]
Oops. I just committed some minor edits to the paper before I saw the creation of this thread. Perhaps this will work to create an updated version: @whedon generate pdf

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01454/joss.01454/10.21105.joss.01454.pdf)

**Comment by mkearney** [comment]
possible reviewers: @maelle @andrewheiss @pachamaltese @leeper @maelle @briatte

**Comment by maelle** [comment]
No rOpenSci submission then? 😢 https://github.com/ropensci/software-review/issues/193

**Comment by andrewheiss** [comment]
I've got a Twitter developer account already, so I can test this out and review it

**Comment by mkearney** [comment]
@maelle I learned the JOSS entry is more immediately desirable for purpose of tenure, but I actually forgot about the JOSS/Ropensci fast-track announcement. Regardless, I would still plan to submit to Ropensci!

**Comment by mkearney** [comment]
Apologies for the ropensci oversight!

@maelle I'm thinking maybe I should withdraw this JOSS submission and submit to ropensci (with the JOSS auto/fast-track publish option). Do you agree? 

@andrewheiss Would you still be willing to review for/over on @ropensci?

**Comment by arfon** [comment]
> @maelle I'm thinking maybe I should withdraw this JOSS submission and submit to ropensci (with the JOSS auto/fast-track publish option). Do you agree?

If you're interested in submitting to rOpenSci then I definitely think we should close this and we can fast-track you through the JOSS process once you've been accepted there. Sound ok?

**Comment by mkearney** [comment]
Yes, that closes this. I've withdrawn this JOSS submission and have instead [submitted](https://github.com/ropensci/software-review/issues/302) to @ropensci.

**Comment by pachamaltese** [comment]
@maelle sure! I have a developer account I have used this package before.
I'm in

**Comment by andrewheiss** [comment]
Yep, I'm find doing it for @ropensci

**Comment by briatte** [comment]
@mkearney I have never reviewed for @ropensci before, but would happily review the package there if you need a second review (I have also used the package in the past).

**Comment by pachamaltese** [comment]
I also want to review the package!
