### ISSUE TITLE
[PRE REVIEW]: multimatch_gaze: The MultiMatch algorithm for gaze path comparison in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1456]
**Submitting author:** @adswa (<a href="http://orcid.org/0000-0003-2917-3450">Adina Wagner</a>)
**Repository:** <a href="https://github.com/adswa/multimatch_gaze" target ="_blank">https://github.com/adswa/multimatch_gaze</a>
**Version:** v0.1.1
**Editor:** @kyleniemeyer
**Reviewers:** @FelixHenninger, @JonathanReardon

**Author instructions**

Thanks for submitting your paper to JOSS @AdinaWagner. **Currently, there isn't an JOSS editor assigned** to your paper.

@AdinaWagner if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01456/joss.01456/10.21105.joss.01456.pdf)

**Comment by arfon** [comment]
:wave: @adswa, thanks for your submission to JOSS. While I identify the right editor for this submission, could you take a look at [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few individuals that might be able to review this submission?

**Comment by adswa** [comment]
Hi @arfon, absolutely, many thanks for the list!
@felixhenninger 's entry in the document sounds like he is knowledgeable with regard to eye-tracking -- maybe he has time? Alternatively, maybe @oesteban or @vsoch? Thanks a lot for everyone's time!

**Comment by arfon** [comment]
:wave: @kyleniemeyer - would you be able to edit this submission for us?

**Comment by kyleniemeyer** [comment]
@arfon sure thing, I'll handle it

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
Hi @FelixHenninger, @oesteban, and @vsoch : are you interested and available to review this submission for JOSS?

**Comment by vsoch** [comment]
I would default to @FelixHenninger first- he bought his own timing equipment and published on it! I’ve built infrastructure for deploying experiments, but that’s different from critiquing timing itself. @FelixHenninger do you have the bandwidth?

**Comment by FelixHenninger** [comment]
Hi y'all, thanks so much for considering me!

Somehow, I missed the GitHub pings; thanks, @kyleniemeyer, for writing directly! I would be thrilled to take a closer look at this, though I'll be out of office until the end of next week, if it's ok that I complete the review in the week of the 24th, I'd be more than happy to -- the project looks fantastic! If any of you get around to it faster, of course, I totally understand. Kind regards, and sorry for the delay,

-Felix

**Comment by kyleniemeyer** [comment]
@whedon assign @FelixHenninger as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @FelixHenninger

**Comment by kyleniemeyer** [comment]
Thanks  @FelixHenninger! I am actively looking for a second reviewer (have a few more emails out), so hopefully we will be able to start the official review thread soon.

**Comment by vsoch** [comment]
@FelixHenninger thank you! You are definitely a good fit for the job :)

**Comment by kyleniemeyer** [comment]
Just a quick update: I am still working to find a second reviewer. I sent out a handful of emails without any success so far.

**Comment by kyleniemeyer** [comment]
@peircej @JonathanReardon @lindemann09 would any of you be willing to review this submission?

**Comment by adswa** [comment]
Thanks @kyleniemeyer for keeping us up to date - this transparency and communication is highly appreciated!

**Comment by JonathanReardon** [comment]
Hi! Yes, I'd be happy to review this, it looks really nice! Thanks for the heads up

**Comment by kyleniemeyer** [comment]
Thanks @JonathanReardon!

**Comment by kyleniemeyer** [comment]
@whedon add @JonathanReardon as reviewer

**Comment by whedon** [comment]
OK, @JonathanReardon is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1525. Feel free to close this issue now!
