### ISSUE TITLE
[PRE REVIEW]: A reproducible Snakemake pipeline to analyse Illumina paired-end data from ChiP-Seq experiments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1457]
**Submitting author:** @mgalland (<a href="http://orcid.org/0000-0003-2161-8689">marc galland</a>)
**Repository:** <a href="https://github.com/KoesGroup/Snakemake_ChIPseq_PE" target ="_blank">https://github.com/KoesGroup/Snakemake_ChIPseq_PE</a>
**Version:** v1.2.0
**Editor:** @brainstorm
**Reviewers:** @vladsaveliev

**Author instructions**

Thanks for submitting your paper to JOSS @mgalland. **Currently, there isn't an JOSS editor assigned** to your paper.

@mgalland if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1457 with the following error: 

 Error reading bibliography ./bibliography.bib (line 118, column 19):
unexpected "S"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @mgalland - it looks like your BibTeX file is missing a comma. Could you please fix the file and ask Whedon to compile the paper again with `@whedon generate pdf`

**Comment by arfon** [comment]
@mgymrek - would you be able to edit this submission for JOSS?

**Comment by mgalland** [comment]
Yes, no problem, just added the comma. Always funny to trigger a robot in a peer-review process!
@whedon generate pdf.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1457 with the following error: 

 Error reading bibliography ./bibliography.bib (line 118, column 19):
unexpected "S"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@mgalland looks like L118 needs changing to `title = {Anaconda Software Distribution},`

Also, when I compile locally, Pandoc complains about the following issues with your citations:

```
pandoc-citeproc: reference Gruning:2018 not found
pandoc-citeproc: reference Ramiez:2016 not found
pandoc-citeproc: reference Buels:2016 not found
```

**Comment by mgalland** [comment]
All right, sorry for that. Silly mistakes...
@whedon generate pdf

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01457/joss.01457/10.21105.joss.01457.pdf)

**Comment by danielskatz** [comment]
👋 bioinformatics editing team (@mgymrek @brainstorm @lpantano @csoneson) - can one of you take on this submission as editor?

**Comment by lpantano** [comment]
@danielskatz, it seems a good fit, we'll do it. 

@mgallan, can you try to fix the figures. They are not centered. We'll find the editor that could handle this meanwhile.

**Comment by brainstorm** [comment]
👋  @vladsaveliev, would you like to review this pipeline for JOSS?

**Comment by brainstorm** [comment]
And/or @pdiakumis if @vladsaveliev keeps ignoring me ;)

**Comment by vladsaveliev** [comment]
Sorry, didn't have a chance to look at it to understand how much work it will require

**Comment by brainstorm** [comment]
@vladsaveliev Usually the reviewer checklist is fairly straightforward, the total time spent on the actual review, in my personal experience, is quite short (20-30min of codebase/tests/docs review), since you know your way through Snakemake, that could potentially be even less.

**Comment by brainstorm** [comment]
@vladsaveliev https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by vladsaveliev** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @vladsaveliev, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by vladsaveliev** [comment]
I can try to review

**Comment by brainstorm** [comment]
@whedon assign @vladsaveliev as reviewer

**Comment by brainstorm** [comment]
@whedon assign @brainstorm as editor

**Comment by whedon** [comment]
OK, the editor is @brainstorm

**Comment by brainstorm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1465. Feel free to close this issue now!
