### ISSUE TITLE
[REVIEW]: CSaransh: Software Suite to Study Molecular Dynamics Simulations of Collision Cascades

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1461]
**Submitting author:** @haptork (<a href="http://orcid.org/0000-0002-1100-6059">Utkarsh Bhardwaj</a>)
**Repository:** <a href="https://github.com/haptork/csaransh" target ="_blank">https://github.com/haptork/csaransh</a>
**Version:** v0.3.2
**Editor:** @katyhuff
**Reviewer:** @jmborr, @arose
**Archive:** <a href="https://doi.org/10.5281/zenodo.3434635" target="_blank">10.5281/zenodo.3434635</a>

## Status

[![status](http://joss.theoj.org/papers/72f2ddde2112497826753319956ea8ab/status.svg)](http://joss.theoj.org/papers/72f2ddde2112497826753319956ea8ab)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/72f2ddde2112497826753319956ea8ab"><img src="http://joss.theoj.org/papers/72f2ddde2112497826753319956ea8ab/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/72f2ddde2112497826753319956ea8ab/status.svg)](http://joss.theoj.org/papers/72f2ddde2112497826753319956ea8ab)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/haptork/csaransh" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jmborr & @arose, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @katyhuff know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/haptork/csaransh">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** v0.3.2
- [x] **Authorship:** Has the submitting author (@haptork) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/haptork/csaransh">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.3.2
- [x] **Authorship:** Has the submitting author (@haptork) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jmborr, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01461/joss.01461/10.21105.joss.01461.pdf)

**Comment by katyhuff** [comment]
@arose and @jmborr  Thank you for beginning your reviews. I hope all is going well. Please don't hesitate to comment if questions arise. Some authors are also very responsive to issues in the source code repository.

**Comment by danielskatz** [comment]
👋 @arose and @jmborr - this is just a ping/reminder, since it's not clear what's happened on these reviews in the last couple of weeks

**Comment by haptork** [comment]
@katyhuff There seems to be no progress on this?

P.S. [here](https://haptork.github.io/csaransh/presentation/index.html) is a talk recently given on one of the analysis that is included in csaransh. The html presentation also uses the react components from csaransh web interface.

**Comment by katyhuff** [comment]
I'm sorry @haptork . I am sorry to say that our reviewers seem to be quite paused and I'm looking for new ones. Summer travel schedules seem to be keeping many people from committing. 

@arose I know you have begun your review. If you intend to complete it, please respond today.

**Comment by labarba** [comment]
@katyhuff — have you had any success looking for alternate reviewers?

**Comment by jmborr** [comment]
I am running the instructions in [README.md](https://github.com/haptork/csaransh/blob/master/README.md) in a Ubuntu 16.04 box. This I was able to do:
- [x] build the C++ post-processor and run the after-build tests
- [x] run `csaransh_pp` and `pp.py` on `data/lammps` to produce `cascades-data.js`
- [x] run the interface as a web application with node server. Here _instructions should state_ to `npm install csaransh-server` prior to `npm start`.

The duplication of this widget within section "View and Compare Cascade Info" is by design?
<img src="https://user-images.githubusercontent.com/1136006/62650322-9ae26400-b924-11e9-9cff-0748b872d918.png" width="400"/>

**Comment by haptork** [comment]
> I am running the instructions in [README.md](https://github.com/haptork/csaransh/blob/master/README.md) in a Ubuntu 16.04 box. This I was able to do:
> 
> * [x]  build the C++ post-processor and run the after-build tests
> * [x]  run `csaransh_pp` and `pp.py` on `data/lammps` to produce `cascades-data.js`
> * [x]  run the interface as a web application with node server. Here _instructions should state_ to `npm install csaransh-server` prior to `npm start`.
> 
> The duplication of this widget within section "View and Compare Cascade Info" is by design?
> <img alt="" width="400" src="https://user-images.githubusercontent.com/1136006/62650322-9ae26400-b924-11e9-9cff-0748b872d918.png">

Thank you for taking this up. :)

Yes, the duplication is meant for comparison. The widget has a lock on top left. With lock open, it will show the stats for currently viewing cascade while once locked the stats get fixed on the current one selected. Thus, one cascade can be fixed on one of the widget and its stats can be compared with others as one views different cascades on the other widget with open lock. By default, the left widget is locked on some arbitrary cascade and right one would change as one selects the cascade from the main table. May be in future we can introduce some better interface to compare figures of two cascades but for now this does the job.

Please let me know of any other clarification if needed :)

**Comment by arose** [comment]
> Installation: Does installation proceed as outlined in the documentation?

The installation went smoothly. I agree with @jmborr that `npm install csaransh-server` should be added to the instructions.

> References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

There are a few dois missing.

**Comment by arose** [comment]
The IAEA challenge shows a need for visualization and analysis tools for collisional cascade molecular dynamics simulation data. Are the results of the challenge available somewhere? I could not find it on their website?

**Comment by katyhuff** [comment]
Thanks @arose for your review!

Thank you @jmborr for your review efforts so far. Perhaps the remainder of your review could be revisited at this point (checkboxes at the top of the page).

@haptork, can you please respond (with changes to the code, install instructions, etc.) to the requests by the reviewers so far (i.e. the comment regarding adding the npm install command to the instructions, the comment from @rose regarding the dois and the results of the iaea challenge).

**Comment by haptork** [comment]
Thank you @arose for reviewing.

> > Installation: Does installation proceed as outlined in the documentation?
> 
> The installation went smoothly. I agree with @jmborr that `npm install csaransh-server` should be added to the instructions.

Added to the instructions with latest commit (6114548d4da347d386cefa20da28d8db67bea651)


> The IAEA challenge shows a need for visualization and analysis tools for collisional cascade molecular dynamics simulation data. Are the results of the challenge available somewhere? I could not find it on their website?

The results were e-mailed to the participants. The results and the software tools of the participants are planned to be put up on the https://cascadesdb.org/ website which is a work in progress as of now. 

The database that the contest uses and the one which is shown by default in csaransh does have an indirect reference. The database page of the contest is https://www-amdis.iaea.org/CDB/challenge/, for each data point it has a webpage (https://www-amdis.iaea.org/CDB/challenge/data/001.html), which shows the DOI of the publication for the datapoint. The reference publication for the data is http://doi.org/10.1038/s41467-018-03415-5 which we have added as a reference in paper.bib.

I don’t think there is any other reference for it now. We can share the mail notifying the results. Also, MoD-PMI presentation participation mentioned in paper, now has a link in the MoD-PMI web page ( http://dpc.nifs.ac.jp/dkato/MoD-PMI2019/ ) .

Let me know if anything needs to be done from our side to get the references checked.

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01461/joss.01461/10.21105.joss.01461.pdf)

**Comment by katyhuff** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1103/PhysRevB.85.024105 is OK
- https://doi.org/10.1016/S0022-3115(99)00171-3 is OK
- https://doi.org/10.1016/S0022-3115(97)00244-4 is OK
- https://doi.org/10.1016/S0022-3115(99)00170-1 is OK
- https://doi.org/10.1016/j.jnucmat.2006.02.022 is OK

MISSING DOIs

- https://doi.org/10.1016/b978-0-08-056033-5.00027-6 may be missing for title: Primary Radiation Damage Formation
- https://doi.org/10.1007/978-3-642-37456-2_14 may be missing for title: Density-Based Clustering Based on Hierarchical Density Estimates
- https://doi.org/10.1209/0295-5075/103/46003 may be missing for title: High-energy collision cascades in tungsten: Dislocation loops structure and clustering scaling laws
- https://doi.org/10.1038/s41467-018-03415-5 may be missing for title: Improving atomic displacement and replacement calculations with physically realistic damage models

INVALID DOIs

- None
```

**Comment by haptork** [comment]
@katyhuff  
Added missing DOIs (commit b6d057ab6d21a7bed34e90737d10d7b98e170402)
Added missing refs (commit c1300cf3547740809255e08250c6a0d9e3862436)
Updated screenshot captions, removed extra line between image and caption(commit 2f6b6a8626fe128cf55a27002bc24b44d4713d1e)

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01461/joss.01461/10.21105.joss.01461.pdf)

**Comment by katyhuff** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1016/b978-0-08-056033-5.00027-6 is OK
- 10.1103/PhysRevB.85.024105 is OK
- https://doi.org/10.1016/S0022-3115(99)00171-3 is OK
- https://doi.org/10.1016/S0022-3115(97)00244-4 is OK
- https://doi.org/10.1016/S0022-3115(99)00170-1 is OK
- https://doi.org/10.1016/j.jnucmat.2006.02.022 is OK
- https://doi.org/10.1007/978-3-642-37456-2_14 is OK
- https://doi.org/10.1209/0295-5075/103/46003 is OK
- https://doi.org/10.1038/s41467-018-03415-5 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by haptork** [comment]
Updated a few formatting issues in the latest commit (putting captions as image placeholders).

**Comment by katyhuff** [comment]
@haptork Thanks for engaging actively in the review process. I've made some suggestions on the pdf itself (from before your most recent commit). Can you please consider the suggestions marked in this pdf, and let me know as soon as you feel these suggested changes have been handled?

[csaransh.pdf](https://github.com/openjournals/joss-reviews/files/3598409/csaransh.pdf)

**Comment by katyhuff** [comment]
Excellent, thank you.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01461/joss.01461/10.21105.joss.01461.pdf)

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1016/b978-0-08-056033-5.00027-6 is OK
- 10.1103/PhysRevB.85.024105 is OK
- https://doi.org/10.1016/S0022-3115(99)00171-3 is OK
- https://doi.org/10.1016/S0022-3115(97)00244-4 is OK
- https://doi.org/10.1016/S0022-3115(99)00170-1 is OK
- https://doi.org/10.1016/j.jnucmat.2006.02.022 is OK
- https://doi.org/10.1007/978-3-642-37456-2_14 is OK
- https://doi.org/10.1209/0295-5075/103/46003 is OK
- https://doi.org/10.1038/s41467-018-03415-5 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by katyhuff** [comment]
Thank you @arose and @jmborr for your reviews -- we couldn't do this without you.
Thank you @haptork for a strong submission and for engaging actively in the review process! I have looked over the paper, double-checked all the DOI links, and have conducted a high-level review of the code itself. Everything looks ship-shape to me. At this point, please double-check the paper yourself, review any lingering details in your code/readme/etc., and then make an archive of the reviewed software in Zenodo/figshare/other service. 

**Please be sure that the DOI metadata (title, authors, etc.) matches this JOSS submission.** 
Please also let me know if the release version needs to be updated in this JOSS submission. Once that's complete, please update this thread with the DOI of the archive, and I'll move forward with accepting the submission. Until then, now is your moment for final touchups!

**Comment by jmborr** [comment]
@katyhuff thanks for your hard work. I feel I have to apologize here because I was very very slow with my review. I was caught at a time where my organization is under pressure to finish a ton of work before some hard deadlines. It was difficult to set aside time for the review :disappointed:

**Comment by katyhuff** [comment]
@whedon set v0.3.2 as version

**Comment by whedon** [comment]
OK. v0.3.2 is the version.

**Comment by katyhuff** [comment]
@whedon set 10.5281/zenodo.3406703 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3406703" target="_blank">10.5281/zenodo.3406703</a> is the archive.

**Comment by katyhuff** [comment]
@openjournals/joss-eics : I believe this is ready for your review

**Comment by arfon** [comment]
@openjournals/joss-eics : I believe this is ready for your review

/ cc @kthyng

**Comment by kthyng** [comment]
Hi @haptork! A few items to wrap up your submission:

- [ ] The tagged version in the github repo is v0.3.4, the release version is v0.3.3, and the version just mentioned in this conversation (and listed at the top) is v0.3.2. Can you confirm the version and make these consistent?

Edits for paper:
 - [ ] pg. 2 paragraph 2: should "materials for fusion, 2018" be capitalized? 
 - [ ] pg. 2 paragraph 2: "in arXiv preprint paper (Bhardwaj, Sand, & Warrier, 2018)" should be "in *the*..." and is it important to specify that it is a preprint? Was it never published in a peer-reviewed journal?
 - [ ] pg.2 paragraph 3: "CascadesDB database(Hill, 2018)" needs a space
 - [ ] "etc" is used repeatedly throughout the paper — please remove these except when strictly necessary.
 - [ ] Figure 2: "Section to chose and compare similar clusters" should be "Section to choose and compare similar clusters"
 - [ ] Figure 2: "The right side shows top five clusters" should be "The right side shows the top five clusters"
 - [ ] Figure 3: "A high energy cascade can be composed of different sub-cascades or frangments." has a typo "fragments"

**Comment by katyhuff** [comment]
Wow @kthyng sorry I missed all of these things (especially the version -- it's in my checklist, so I'm not at all sure how I missed it!) Thanks for your sharp eyes!

**Comment by haptork** [comment]
> Hi @haptork! A few items to wrap up your submission:
> 
> * [ ]  The tagged version in the github repo is v0.3.4, the release version is v0.3.3, and the version just mentioned in this conversation (and listed at the top) is v0.3.2. Can you confirm the version and make these consistent?

The zenodo archive version for the DOI I mentioned is 0.3.2 (in its metadata) which corresponds to: https://github.com/haptork/csaransh/releases/tag/v0.3.2. Please ignore the later two versions in the GitHub repo. Sorry for the confusion.

> Edits for paper:
> 
> * [ ]  pg. 2 paragraph 2: should "materials for fusion, 2018" be capitalized?

Thank you. Corrected.

> * [ ]  pg. 2 paragraph 2: "in arXiv preprint paper (Bhardwaj, Sand, & Warrier, 2018)" should be "in _the_..." and is it important to specify that it is a preprint? Was it never published in a peer-reviewed journal?

Thank you. Added _the_ and removed preprint from the sentence. The paper is in communication in a peer reviewed journal.

> * [ ]  pg.2 paragraph 3: "CascadesDB database(Hill, 2018)" needs a space

Thanks. Corrected.

> * [ ]  "etc" is used repeatedly throughout the paper — please remove these except when strictly necessary.

Corrected. Thanks.

> * [ ]  Figure 2: "Section to chose and compare similar clusters" should be "Section to choose and compare similar clusters"

Thanks. It had already been corrected before archiving.

> * [ ]  Figure 2: "The right side shows top five clusters" should be "The right side shows the top five clusters"

Thanks. Corrected

> * [ ]  Figure 3: "A high energy cascade can be composed of different sub-cascades or frangments." has a typo "fragments"

Thanks. It had already been corrected before archiving.

commit for the corrections: d9d3cb9f6e84b737ba22dfd5064d8a545cbb5cc7
zenodo archive after the corrections (if required): 10.5281/zenodo.3434635

Please let me know if anything is to be done.

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.3434635 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3434635" target="_blank">10.5281/zenodo.3434635</a> is the archive.

**Comment by kthyng** [comment]
Great! Thanks @haptork for addressing those items.

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/970

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/970, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1174775682045489152) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/971
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01461](https://doi.org/10.21105/joss.01461)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats to @haptork on your newly published paper!!! Thanks so much to @jmborr, @arose — your review was integral to this publication!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01461/status.svg)](https://doi.org/10.21105/joss.01461)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01461">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01461/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01461/status.svg
   :target: https://doi.org/10.21105/joss.01461
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01461/status.svg)](https://doi.org/10.21105/joss.01461)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by haptork** [comment]
Thanks @katyhuff @kthyng @arose @jmborr. :)
