### ISSUE TITLE
[REVIEW]: tidyqwi: A Tidy Approach to Accessing The US Census Bureau's Quarterly Workforce Indicators

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1462]
**Submitting author:** @medewitt (<a href="http://orcid.org/0000-0001-8940-1967">Michael DeWitt</a>)
**Repository:** <a href="https://github.com/medewitt/tidyqwi" target ="_blank">https://github.com/medewitt/tidyqwi</a>
**Version:** v0.1.0
**Editor:** @alexhanna
**Reviewer:** @tweed1e
**Archive:** <a href="https://doi.org/10.5281/zenodo.3247760" target="_blank">10.5281/zenodo.3247760</a>

## Status

[![status](http://joss.theoj.org/papers/96bac49d6912cea4d191abff922d7c2e/status.svg)](http://joss.theoj.org/papers/96bac49d6912cea4d191abff922d7c2e)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/96bac49d6912cea4d191abff922d7c2e"><img src="http://joss.theoj.org/papers/96bac49d6912cea4d191abff922d7c2e/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/96bac49d6912cea4d191abff922d7c2e/status.svg)](http://joss.theoj.org/papers/96bac49d6912cea4d191abff922d7c2e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/medewitt/tidyqwi/tree/master/inst" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@tweed1e, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @alexhanna know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/medewitt/tidyqwi/tree/master/inst">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@medewitt) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @tweed1e it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1462 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1462 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-fc4c5c749ca9/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-fc4c5c749ca9/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-fc4c5c749ca9/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by medewitt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1462 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1462 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by tweed1e** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by tweed1e** [comment]
Hi, sorry for the delay, I've completed my review—I opened a few issues which the author has dealt with, and now I'm satisfied that it passes all requirements. 👍👍. 

(The author guidelines say leaving this comment is sufficient, so I'm guessing I shouldn't "Close and comment".)

**Comment by alexhanna** [comment]
Thanks for the review, @tweed1e, and for addressing the issues @medewitt.

**Comment by alexhanna** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1462 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1462 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by alexhanna** [comment]
@medewitt we need the documentation to be located in a `paper.md` file for submission. We need a doc in the format described on the [submission guidelines site](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain).

**Comment by medewitt** [comment]
Hi @alexhanna thank you for your work in this and thank you @tweed1e for the review.

 I think everything is in compliance to the guidelines at https://github.com/medewitt/tidyqwi/tree/master/inst

**Comment by medewitt** [comment]
Do you think it is the double quotes in the title vs single quotes that is causing the error, @alexhanna?

**Comment by alexhanna** [comment]
I don't think so, although you could try to change that and recheck the PDF. @arfon, is there a particular location in the repository that the `paper.md` must be located?

**Comment by arfon** [comment]
I don't think Whedon can find the paper as the repository address won't clone (`https://github.com/medewitt/tidyqwi/tree/master/inst`). I've changed the URL at the top of the thread to be `https://github.com/medewitt/tidyqwi`

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01462/joss.01462/10.21105.joss.01462.pdf)

**Comment by alexhanna** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1257/aer.102.3.589 may be missing for title: Did the Housing Price Bubble Clobber Local Labor Market Job and Worker Flows When It Burst?
- https://doi.org/10.1162/rest_a_00680 may be missing for title: Who Loses under Cap-and-Trade Programs? The Labor Market Effects of the Nox Budget Trading Program
- https://doi.org/10.1086/685449 may be missing for title: Minimum Wage Shocks, Employment flows, and Labor Market Frictions

INVALID DOIs

- None
```

**Comment by alexhanna** [comment]
@medewitt looks like a few references are missing DOIs. Could you check on those?

**Comment by medewitt** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1257/aer.102.3.589 may be missing for title: Did the Housing Price Bubble Clobber Local Labor Market Job and Worker Flows When It Burst?
- https://doi.org/10.1162/rest_a_00680 may be missing for title: Who Loses under Cap-and-Trade Programs? The Labor Market Effects of the Nox Budget Trading Program
- https://doi.org/10.1086/685449 may be missing for title: Minimum Wage Shocks, Employment flows, and Labor Market Frictions

INVALID DOIs

- None
```

**Comment by medewitt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01462/joss.01462/10.21105.joss.01462.pdf)

**Comment by medewitt** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1257/aer.102.3.589 is OK
- 10.1162/REST_a_00680 is OK
- 10.1086/685449 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by medewitt** [comment]
Done...sorry about that

**Comment by alexhanna** [comment]
No worries. This looks ready to go then. The last thing we need is for you to create an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive. For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

**Comment by medewitt** [comment]
Okey dokey. DOI: 10.5281/zenodo.3247760

**Comment by alexhanna** [comment]
No worries.

**Comment by alexhanna** [comment]
@whedon set 10.5281/zenodo.3247760 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3247760" target="_blank">10.5281/zenodo.3247760</a> is the archive.

**Comment by alexhanna** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/768

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/768, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1257/aer.102.3.589 is OK
- 10.1162/REST_a_00680 is OK
- 10.1086/685449 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by alexhanna** [comment]
@openjournals/joss-eics this submission is ready to be accepted.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/769

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/769, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1257/aer.102.3.589 is OK
- 10.1162/REST_a_00680 is OK
- 10.1086/685449 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @arfon - note that there's a problem on line 40 of the [xml](https://github.com/openjournals/joss-papers/pull/769/commits/4876bc02ec4ea60d6be941ded63ef85d057df952) - your thoughts on how to proceed?

**Comment by arfon** [comment]
@medewitt - could you change your name entry to `name: Michael E DeWitt Jr` (i.e. remove the comma)?

**Comment by arfon** [comment]
This will allow Whedon to parse the name field properly.

**Comment by medewitt** [comment]
Change my name!!! Just kidding. No problem, done.

**Comment by arfon** [comment]
> Change my name!!! Just kidding. No problem, done.

😆

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/772

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/772, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1257/aer.102.3.589 is OK
- 10.1162/REST_a_00680 is OK
- 10.1086/685449 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/773

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/773, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1257/aer.102.3.589 is OK
- 10.1162/REST_a_00680 is OK
- 10.1086/685449 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@danielskatz - this looks better to me ☝️

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1140748455666733066) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/775
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01462](https://doi.org/10.21105/joss.01462)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks @tweed1e for reviewing and @alexhanna for editing

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01462/status.svg)](https://doi.org/10.21105/joss.01462)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01462">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01462/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01462/status.svg
   :target: https://doi.org/10.21105/joss.01462
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01462/status.svg)](https://doi.org/10.21105/joss.01462)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
