### ISSUE TITLE
[PRE REVIEW]: swisslandstats-geopy: Python tools for the land statistics datasets from the Swiss Federal Statistical Office

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1464]
**Submitting author:** @martibosch (<a href="http://orcid.org/0000-0001-8735-9144">Martí Bosch</a>)
**Repository:** <a href="https://github.com/martibosch/swisslandstats-geopy" target ="_blank">https://github.com/martibosch/swisslandstats-geopy</a>
**Version:** v0.6.1
**Editor:** @leouieda
**Reviewers:** @weikang9009, @darribas

**Author instructions**

Thanks for submitting your paper to JOSS @martibosch. The JOSS editor @leouieda, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@martibosch if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @leouieda it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@leouieda) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1464 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1464/paper/paper.md): mapping values are not allowed in this context at line 2 column 28 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-fc4c5c749ca9/lib/whedon.rb:95:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-fc4c5c749ca9/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-fc4c5c749ca9/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-fc4c5c749ca9/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-fc4c5c749ca9/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-fc4c5c749ca9/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @leouieda - note that the submitter requested you as editor and I went ahead and assigned you based on the fit - if you have any concerns, please let me know and I will find another editor

**Comment by danielskatz** [comment]
👋 @martibosch - you need to add single quotes `'` around the title in your paper.md

Once you have done so, you can enter ```@whedon generate pdf``` as a new comment here to see if that fixes the build problem

**Comment by martibosch** [comment]
Hello @danielskatz - my apologies. I have already added the single quotes around the title and pushed the commit to the master branch.

Thank you

**Comment by danielskatz** [comment]
> Once you have done so, you can enter @whedon generate pdf as a new comment here to see if that fixes the build problem

**Comment by danielskatz** [comment]
I'll do it this time...

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01464/joss.01464/10.21105.joss.01464.pdf)

**Comment by danielskatz** [comment]
looks good - over to @leouieda to edit...  (or to say that someone else should)

**Comment by leouieda** [comment]
@danielskatz I'd be happy to edit this submission :+1: 

@martibosch I'll look over your submission shortly and start searching for appropriate reviewers. Let me know if you have any questions :slightly_smiling_face:

**Comment by martibosch** [comment]
Thank you very much @leouieda 

A small update: a preprint which shows how the library might be used in real studies is already available (https://doi.org/10.1101/645549), and so is the repository with the materials required to reproduce the results (https://github.com/martibosch/swiss-urbanization). Should we add this to the manuscript? 

On the other hand, the library has also been used in a manuscript submitted to the "Landscape Ecology"  (Springer) journal, which is currently undergoing major modifications. Although we have not published any preprint, the code to reproduce our results (using this library) is also available at a dedicated repository (https://github.com/martibosch/carbon-sequestration-vaud).

Martí

**Comment by leouieda** [comment]
@martibosch you could add a link to these repositories as examples of the software package. But they don't need to be on the paper (maybe just as a citation to the preprint). The JOSS papers are usually very minimal and most of your efforts should go into the software documentation instead.

**Comment by leouieda** [comment]
:wave: Hi @martibosch, I wanted to give you an update on the process. I'm searching for reviewers and have sent invitations through email. I hope to have the reviewers assigned within the next week so we can start the review process. Thanks for your patience.

**Comment by leouieda** [comment]
@whedon assign @weikang9009 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @weikang9009

**Comment by leouieda** [comment]
@whedon add @darribas as reviewer

**Comment by whedon** [comment]
OK, @darribas is now a reviewer

**Comment by leouieda** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01464/joss.01464/10.21105.joss.01464.pdf)

**Comment by leouieda** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1511. Feel free to close this issue now!
