### ISSUE TITLE
[REVIEW]: A reproducible Snakemake pipeline to analyse Illumina paired-end data from ChiP-Seq experiments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1465]
**Submitting author:** @mgalland (<a href="http://orcid.org/0000-0003-2161-8689">marc galland</a>)
**Repository:** <a href="https://github.com/KoesGroup/Snakemake_ChIPseq_PE" target ="_blank">https://github.com/KoesGroup/Snakemake_ChIPseq_PE</a>
**Version:** v1.2.0
**Editor:** @brainstorm
**Reviewer:** @vladsaveliev
**Archive:** <a href="https://doi.org/10.5281/zenodo.3240026" target="_blank">10.5281/zenodo.3240026</a>

## Status

[![status](http://joss.theoj.org/papers/6fcc9acc993e02b90a1b9028429b36c7/status.svg)](http://joss.theoj.org/papers/6fcc9acc993e02b90a1b9028429b36c7)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/6fcc9acc993e02b90a1b9028429b36c7"><img src="http://joss.theoj.org/papers/6fcc9acc993e02b90a1b9028429b36c7/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/6fcc9acc993e02b90a1b9028429b36c7/status.svg)](http://joss.theoj.org/papers/6fcc9acc993e02b90a1b9028429b36c7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/KoesGroup/Snakemake_ChIPseq_PE" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@vladsaveliev, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @brainstorm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/KoesGroup/Snakemake_ChIPseq_PE">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.2.0)?
- [x] **Authorship:** Has the submitting author (@mgalland) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @vladsaveliev it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01465/joss.01465/10.21105.joss.01465.pdf)

**Comment by vladsaveliev** [comment]
**Review**

Snakemake_ChIPseq_PE is a solid Snakemake workflow, designed very much in Snakemake spirit, and makes use of its main features like conda or signularity-based runs. Self-contained assuming you have conda executable installed. Python code is clean, follows PEP guidelines an thus easy to read.

The tool is well documented, pretty clear instructions how to install and test it. One small suggestion is to remove ~/ in this command so it would work assuming a user cloned the repo and changed into it:

```
conda env create --name chipseq --file ~/envs/global_env.yaml
```

Feature-wise, one suggestion is the ability to start from BAM files as well. Often you either have an external pre-aligned BAMs, or want to do the heavy lifting with another software and use the workflow just for reporting.

Tests complete without any issues and the output corresponds to the description. 

All good from my side.

**Comment by brainstorm** [comment]
Vlad, Thanks a ton for this! @mgalland, could you please apply the fixes/suggestions and generate a preliminary DOI via Zenodo?

**Comment by brainstorm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2025836 is OK
- 10.1093/bioinformatics/bts480 is OK
- 10.1093/bioinformatics/bty560 is OK
- 10.1038/nmeth.1923 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.1038/s41592-018-0046-7 is OK
- 10.1093/nar/gkw257 is OK
- 10.1093/bioinformatics/btu170 is OK
- 10.1186/gb-2008-9-9-r137 is OK
- 10.1016/j.cels.2018.03.014 is OK
- 10.1186/s13059-016-0924-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by brainstorm** [comment]
@mgalland, before you put it on Zenodo, please make sure that:

1) The paper figures render well, they seem a bit off.
2) There's better spacing on the enumerations, paragraphs and overall text structure.

Other than that, LGTM.

**Comment by vladsaveliev** [comment]
Have to clarify that I don't think that running from BAMs is a requirement to accept the article. Just a suggestion. Can go as is.

Agree about the figure rendering though, images look cropped by the right edge, especially the DAG plot.

**Comment by mgalland** [comment]
Yes, running from BAMs would be nice but, in practice, I don't really know how to implement this...
Do you think the figures are cropped because their size is too big? Jihed will look into that tonight (Amsterdam time!).

**Comment by vladsaveliev** [comment]
@mgalland Snakemake is just a Python extension, so you can use `if`-`else` statements whenever you want, e.g. like that:
https://github.com/umccr/10x/blob/master/ema/Snakefile#L49-L75
https://github.com/vladsaveliev/vcf_stuff/blob/master/vcf_stuff/eval_vcf/vcf.smk#L137-L156
Hope this is helpful

**Comment by mgalland** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01465/joss.01465/10.21105.joss.01465.pdf)

**Comment by mgalland** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01465/joss.01465/10.21105.joss.01465.pdf)

**Comment by mgalland** [comment]
@brainstorm Figures seem fine now. Could you be more specific regarding the text formatting? Where would you like to see modifications? Thanks.

**Comment by brainstorm** [comment]
Thanks @mgalland, looks better now. I was referring to the enumeration after "The outputs delivered with the pipeline are:"... an few extra newlines specifically there and better separation of paragraphs could improve readability. It is now a bit too compact imho.

After this is addressed, feel free to deposit on Zenodo. Cheers!

**Comment by mgalland** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01465/joss.01465/10.21105.joss.01465.pdf)

**Comment by mgalland** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01465/joss.01465/10.21105.joss.01465.pdf)

**Comment by mgalland** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01465/joss.01465/10.21105.joss.01465.pdf)

**Comment by mgalland** [comment]
@brainstorm I'm very sorry but after several tries, it seems that I cannot add any extra lines to the `paper.md` file somehow. I don't understand why to be honest. Is that something you'd know about?

**Comment by brainstorm** [comment]
@mgalland I see, my point was that spacing were similar to the GH-rendered markdown version https://github.com/KoesGroup/Snakemake_ChIPseq_PE/blob/master/paper.md, but there might be other tricks to display it well on @arfon's JOSS renderer.

Nevermind, looks good anyway, it was just a minor spacing detail. Looks good to me, could you generate a Zenodo DOI so that it can be archived?

Thanks everyone!

**Comment by mgalland** [comment]
@brainstorm Thanks! Done! I've made a Zenodo record just know. Thanks to all reviewers and contributors. Here is the link: https://zenodo.org/record/3240026

**Comment by brainstorm** [comment]
@whedon set https://zenodo.org/record/3240026 as archive

**Comment by whedon** [comment]
https://zenodo.org/record/3240026 doesn't look like an archive DOI.

**Comment by brainstorm** [comment]
@whedon set 10.5281/zenodo.3240026 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3240026" target="_blank">10.5281/zenodo.3240026</a> is the archive.

**Comment by brainstorm** [comment]
All camera ready, @arfon ;)

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2025836 is OK
- 10.1093/bioinformatics/bts480 is OK
- 10.1093/bioinformatics/bty560 is OK
- 10.1038/nmeth.1923 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.1038/s41592-018-0046-7 is OK
- 10.1093/nar/gkw257 is OK
- 10.1093/bioinformatics/btu170 is OK
- 10.1186/gb-2008-9-9-r137 is OK
- 10.1016/j.cels.2018.03.014 is OK
- 10.1186/s13059-016-0924-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/735

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/735, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1136645879358795776) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/736
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01465](https://doi.org/10.21105/joss.01465)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@vladsaveliev - many thanks for your review and to @brainstorm for editing this submission ✨ 

@mgalland - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01465/status.svg)](https://doi.org/10.21105/joss.01465)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01465">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01465/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01465/status.svg
   :target: https://doi.org/10.21105/joss.01465
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01465/status.svg)](https://doi.org/10.21105/joss.01465)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
