### ISSUE TITLE
[PRE REVIEW]: mLEARn: An Implementation of Multi-layer Perceptron in C++

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1467]
**Submitting author:** @kalu-o (<a href="http://orcid.org/0000-0002-8152-4863">Kalu U. Ogbureke</a>)
**Repository:** <a href="https://github.com/kalu-o/mLEARn" target ="_blank">https://github.com/kalu-o/mLEARn</a>
**Version:** v1.0.1
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @kalu-o. **Currently, there isn't an JOSS editor assigned** to your paper.

@kalu-o if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01467/joss.01467/10.21105.joss.01467.pdf)

**Comment by danielskatz** [comment]
👋 @kalu-o - your affiliation shows up as IEEE - Is this the institution where you work/study or where you worked/studied while the work was done?

**Comment by kalu-o** [comment]
Hi Daniel,
I did not work/study in IEEE, but a member. The work was done at Rovira i Virgili University, Tarragona Spain.  It is a research software; I briefly looked at JOSE and think it might be better suited there.

**Comment by danielskatz** [comment]
Can I suggest that you withdraw it from JOSS (which I can do with your permission) and resubmit to JOSE instead?  That does seem like a better fit.

**Comment by kalu-o** [comment]
Yes please.
