### ISSUE TITLE
[PRE REVIEW]: AdMit: Adaptive mixture of Student-t distributions in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#147]
**Submitting author:** @ArdiaD (<a href="http://orcid.org/0000-0003-2823-782X">David Ardia</a>)
**Repository:** <a href="https://github.com/ArdiaD/AdMit" target ="_blank">https://github.com/ArdiaD/AdMit</a>
**Version:** 2.0.2
**Editor:** Pending
**Reviewer:** Pending

**What this issue is for**

Thanks for submitting your paper to JOSS ArdiaD. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @pboesu - would you be willing to review this submission for JOSS? This is by the same author as https://github.com/openjournals/joss-reviews/issues/148 so I think it would be OK to prioritize one over the other.

**Comment by pboesu** [comment]
Hi @arfon, @ArdiaD,
a full description of this R package appears to have been published already in the Journal of Statistical Software by the same authors: http://dx.doi.org/10.18637/jss.v029.i03

Can you provide a justification for submitting this to JOSS now, @ArdiaD?

**Comment by ArdiaD** [comment]
Hi @pboesu,
Regarding your comments:
1. AdMit article appeared in JSS and R journal. These are package descriptions and different applications. Was no issue publishing in both journals. NB: both papers are cited in the JOSS abstract. 
2. bayesGARCH appeared in R journal. Again description of the package. NB: the paper is cited in the JOSS abstract.

In both cases, the DOI is associated to the papers, not the the software (unless I am wrong). So I thought JOSS goals was to provide a DOI for the package. My goal is not to have another publication, but get a DOI for the package, as it is used but not cited in publications.

If this is in contradiction with JOSS standard, please remove my submissions and accept my apologizes for the time wasted.

**Comment by arfon** [comment]
Closing following conversation in #148
