### ISSUE TITLE
[PRE REVIEW]: SimonGrataGen: The Simon Grammar Task Experiment Generator

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1470]
**Submitting author:** @DrMichaelLindner (<a href="http://orcid.org/0000-0002-8289-6845">Michael Lindner</a>)
**Repository:** <a href="https://github.com/DrMichaelLindner/SimonGrataGen" target ="_blank">https://github.com/DrMichaelLindner/SimonGrataGen</a>
**Version:** v1.0
**Editor:** @cMadan
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @DrMichaelLindner. The JOSS editor @cMadan, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@DrMichaelLindner if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @cMadan it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@cMadan) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01470/joss.01470/10.21105.joss.01470.pdf)

**Comment by danielskatz** [comment]
👋 @cMadan - the author requested you as the editor - I hope this is ok - let me know if it isn't

**Comment by cMadan** [comment]
@danielskatz, sure, I have no problem being editor here.

@DrMichaelLindner, I've looked over your submission but currently view it as too specialised for a JOSS publication. Can you provide a bit of justification of why you think this software is sufficient for a standalone publication?

**Comment by labarba** [comment]
Hi @DrMichaelLindner — Could you clarify here how your submission meets the [JOSS requirements](shttps://joss.readthedocs.io/en/latest/submitting.html#submission-requirements)?

**Comment by kyleniemeyer** [comment]
Hi @DrMichaelLindner, could you please respond to the above request? Otherwise, we will withdraw the submission.

**Comment by cMadan** [comment]
@DrMichaelLindner, I just sent you an email. If I don't hear back from you by the end of the week, I will withdraw this submission.

**Comment by cMadan** [comment]
Since this still hasn't been responded to, I am going to withdraw the submission.
