### ISSUE TITLE
[REVIEW]: cde - R package to retrieve data from the Environment Agency Catchment Data Explorer site

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1473]
**Submitting author:** @robbriers (<a href="http://orcid.org/0000-0003-0341-1203">Robert Briers</a>)
**Repository:** <a href="https://github.com/ropensci/cde" target ="_blank">https://github.com/ropensci/cde</a>
**Version:** v0.4.1
**Editor:** @karthik
**Reviewer:** @jhollist
**Archive:** <a href="https://doi.org/10.5281/zenodo.2577178" target="_blank">10.5281/zenodo.2577178</a>

## Status

[![status](http://joss.theoj.org/papers/0d35f75e861fcf47556d70571e226589/status.svg)](http://joss.theoj.org/papers/0d35f75e861fcf47556d70571e226589)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/0d35f75e861fcf47556d70571e226589"><img src="http://joss.theoj.org/papers/0d35f75e861fcf47556d70571e226589/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0d35f75e861fcf47556d70571e226589/status.svg)](http://joss.theoj.org/papers/0d35f75e861fcf47556d70571e226589)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ropensci/cde" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jhollist, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @karthik know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).
                                                                          
### General checks                        

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ropensci/cde">repository url</a>?

- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
  
- [x] **Version:** v0.4.1

- [x] **Authorship:** Has the submitting author (@robbriers) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
            
### Functionality
  
- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jhollist it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by karthik** [comment]
Jeff: Thank you! Noting here that you'll complete the review by early July.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01473/joss.01473/10.21105.joss.01473.pdf)

**Comment by labarba** [comment]
@whedon remind @@jhollist in 3 weeks

**Comment by whedon** [comment]
@@jhollist doesn't seem to be a reviewer or author for this submission.

**Comment by labarba** [comment]
@whedon remind @jhollist in 3 weeks

**Comment by whedon** [comment]
Reminder set for @jhollist in 3 weeks

**Comment by jhollist** [comment]
Thanks all for giving me the extra time to get this review done!  And kudos to @robbriers for a nicely done package.  

I have updated the checklist above.  For each of the items I did not check I have a few things that I feel should be addressed prior to signing off on those.  I have outlined those in an issue on the package repository.    See those at https://github.com/ropensci/cde/issues/23

Any questions, please let me know.

**Comment by karthik** [comment]
Thanks Jeff! 
@robbriers Please review these comments and post your responses. 🙏

**Comment by karthik** [comment]
I added a few more comments in Jeff's issue above.

**Comment by robbriers** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01473/joss.01473/10.21105.joss.01473.pdf)

**Comment by robbriers** [comment]
Updated pdf above and addressed points raised in [https://github.com/ropensci/cde/issues/23](https://github.com/ropensci/cde/issues/23).
Let me know if anything else needs attention

**Comment by robbriers** [comment]
[https://github.com/ropensci/cde/issues/23#issuecomment-506983904](https://github.com/ropensci/cde/issues/23#issuecomment-506983904)

**Comment by whedon** [comment]
:wave: @jhollist, please update us on how your review is going.

**Comment by karthik** [comment]
Thanks for the updates @robbriers. @jhollist When you get a chance, can you check out the statement of need?

**Comment by karthik** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by karthik** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01473/joss.01473/10.21105.joss.01473.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/J.SCITOTENV.2016.09.228 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jhollist** [comment]
> Thanks for the updates @robbriers. @jhollist When you get a chance, can you check out the statement of need?

Just took a look at the new proof and statement of need looks good.  Going to check on the other things but anticipate signing off on these momentarily.

**Comment by jhollist** [comment]
Looks good to me!  Just signed off on the last remaining items in the checklist.  👍 👍

**Comment by karthik** [comment]
Thanks Jeff, you rock! 💯

**Comment by karthik** [comment]
whedon generate pdf

**Comment by karthik** [comment]
@robbriers Can you please archive on Zenodo and post a DOI here 🙏

**Comment by robbriers** [comment]
https://doi.org/10.5281/zenodo.2577178

**Comment by karthik** [comment]
@whedon set 10.5281/zenodo.2577178 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2577178" target="_blank">10.5281/zenodo.2577178</a> is the archive.

**Comment by karthik** [comment]
Over you to @openjournals/joss-eics

**Comment by labarba** [comment]
👋  @robbriers — Please check that the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.

**Comment by labarba** [comment]
@whedon set v0.4.1 as version

**Comment by whedon** [comment]
OK. v0.4.1 is the version.

**Comment by robbriers** [comment]
@labarba fixed zenodo metadata as requested

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/815

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/815, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/J.SCITOTENV.2016.09.228 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
Paper paragraph 1: malformed citation: `[@WWAPUnitedNationsWorldWaterAssessmentProgramme/UN-Water2018]`

**Comment by labarba** [comment]
While you are there, add a comma after "e.g." on page 2.

**Comment by robbriers** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01473/joss.01473/10.21105.joss.01473.pdf)

**Comment by robbriers** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01473/joss.01473/10.21105.joss.01473.pdf)

**Comment by robbriers** [comment]
@labarba think that has fixed the problem

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/J.SCITOTENV.2016.09.228 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/816

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/816, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1146723059765796866) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/817
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01473](https://doi.org/10.21105/joss.01473)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congrats @robbriers! Your JOSS paper is accepted.

Big thanks to our editor: @karthik and reviewer: @jhollist

**Comment by labarba** [comment]
(Just published this from my airplane seat before doors close for a long-haul. Cool.)

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01473/status.svg)](https://doi.org/10.21105/joss.01473)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01473">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01473/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01473/status.svg
   :target: https://doi.org/10.21105/joss.01473
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01473/status.svg)](https://doi.org/10.21105/joss.01473)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by robbriers** [comment]
:) great - many thanks @labarba @karthik @jhollist
