### ISSUE TITLE
[PRE REVIEW]: Eyestream: An open WebSocket-based middleware for serializing and streaming eye tracker event data from Gazepoint GP3 HD research hardware

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1476]
**Submitting author:** @MLHale (<a href="http://orcid.org/0000-0002-8433-2744">Matthew Hale</a>)
**Repository:** <a href="https://github.com/MLHale/eyestream" target ="_blank">https://github.com/MLHale/eyestream</a>
**Version:** 1.0.2
**Editor:** @cMadan
**Reviewers:** @RingoHHuang, @adswa

**Author instructions**

Thanks for submitting your paper to JOSS @MLHale. **Currently, there isn't an JOSS editor assigned** to your paper.

@MLHale if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01476/joss.01476/10.21105.joss.01476.pdf)

**Comment by danielskatz** [comment]
👋 @MLHale - some of the references have case problems - you might want to enclose anything that should stay upper case in {}s - when you have made changes, to test them, enter a new comment here with ```@whedon generate pdf```

**Comment by danielskatz** [comment]
👋 @cMadan - would you be willing to edit this submission?

**Comment by MLHale** [comment]
@danielskatz I'll fix the case issues, thanks for pointing that out.

**Comment by MLHale** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01476/joss.01476/10.21105.joss.01476.pdf)

**Comment by cMadan** [comment]
@danielskatz, sure, I can edit this. Will need to see how easily I can find a reviewer that has the requisite hardware though.

@MLHale, do you have any suggestions for reviewers, in particular those who would have the necessary hardware?

**Comment by danielskatz** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by MLHale** [comment]
@cMadan - I don't know of anyone specifically on GitHub except for @esdalmaijer - who created [PyOpenGaze](https://github.com/esdalmaijer/PyOpenGaze), which is one of the dependencies used in this project.

In the broader academic community - there are many authors who've written manuscripts involving gazepoint devices.

A few include:
Pujitha Mannaru - Department of Electrical and Computer Engineering University of Connecticut Storrs USA

Balakumar Balasingam - Department of Electrical and Computer Engineering University of Connecticut Storrs USA

Krishna Pattipati - Warfighter Human Systems Integration Lab Naval Research Laboratory Washington DC USA

Joseph T. Coyne - Warfighter Human Systems Integration Lab Naval Research Laboratory Washington DC USA

Ciara Sibley - Warfighter Human Systems Integration Lab Naval Research Laboratory Washington DC USA

Gregory Funke - Air Force Research Laboratory, Wright-Patterson AFB, OH

Eric - Greenlee - Texas Tech University, Lubbock, TX

Martha Carter - Miami University, Oxford, OH

Allen Dukes - Air Force Research Laboratory, Wright-Patterson AFB, OH

Julie Iskander - Institute for Intelligent Systems Research and Innovation (IISRI), Deakin University, Australia

**Comment by cMadan** [comment]
@esdalmaijer @TobiasRoeddiger @EmotionCognitionLab @RingoHHuang @pollen-robotics @nu-childlab, would you be interested and available in reviewing this software paper for publication at JOSS?

**Comment by cMadan** [comment]
@MLHale, just to update you, I've been emailing potential reviewers for your submission but that's still in-progress.

**Comment by cMadan** [comment]
@MLHale, how much of your submission *requires* access to the Gazepoint hardware? I'm having trouble finding researchers who have the hardware and are interested in reviewing.

**Comment by MLHale** [comment]
@cMadan - Well the library sits on-top of the hardware-level libraries and does require the library to stream data. 

That said, the program could probably be tested without the hardware - it just won't do anything, since there will be no hardware/hardware libraries to read data from.

Perhaps someone could do a code review or other means of review on the paper/library without testing it in practice? Or possibly I could conduct tests at the behest of the reviewers and post screenshots / videos of the requested tests?

**Comment by cMadan** [comment]
@adswa, would you be available and interested in reviewing this submission? I understand that you don't have the hardware for this submission, but a code review would be much appreciated and I should have another reviewer who does have access to the hardware to test the functionality.

@RingoHHuang, thanks for agreeing to review this submission!

**Comment by cMadan** [comment]
@whedon add @RingoHHuang as reviewer

**Comment by whedon** [comment]
OK, @RingoHHuang is now a reviewer

**Comment by adswa** [comment]
Hey @cMadan, sure, I will do what I can.

**Comment by cMadan** [comment]
@whedon add @adswa as reviewer

**Comment by whedon** [comment]
OK, @adswa is now a reviewer

**Comment by cMadan** [comment]
@adswa, great, I will add you and start the review then! :)

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1620. Feel free to close this issue now!
