### ISSUE TITLE
[PRE REVIEW]: An Optimized Tool for Learning Embeddings of Words and Entities from Wikipedia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1477]
**Submitting author:** @ikuyamada (<a href="http://orcid.org/0000-0002-7980-7661">Ikuya Yamada</a>)
**Repository:** <a href="https://github.com/wikipedia2vec/wikipedia2vec" target ="_blank">https://github.com/wikipedia2vec/wikipedia2vec</a>
**Version:** v1.0.3
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @ikuyamada. **Currently, there isn't an JOSS editor assigned** to your paper.

@ikuyamada if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1477 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon.rb:123:in `block in check_orcids': Problem with ORCID (0000-0000-0000-0000) for Akari Asai (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon.rb:121:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon.rb:121:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon.rb:81:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋  @ikuyamada - The ORCID for Akari Asai is not correct.  Either update this to the correct ORCID, or remove this line from the paper.  Then in a new comment here, enter ```@whedon generate pdf``` to regenerate the pdf.

**Comment by ikuyamada** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01477/joss.01477/10.21105.joss.01477.pdf)

**Comment by ikuyamada** [comment]
@danielskatz Thanks. I removed the line and regenerated the paper!

**Comment by ikuyamada** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01477/joss.01477/10.21105.joss.01477.pdf)

**Comment by ikuyamada** [comment]
I fixed several formatting issues and regenerated the PDF.

**Comment by danielskatz** [comment]
👋 @usethedata - would you also be willing to edit this submission?

**Comment by danielskatz** [comment]
👋 @ikuyamada - Did you also withdraw the paper and then submit a new version?

**Comment by danielskatz** [comment]
note that this version has been withdrawn - see #1479 instead
