### ISSUE TITLE
[REVIEW]: Fireworks: Reproducible Machine Learning with PyTorch

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1478]
**Submitting author:** @smk508 (<a href="http://orcid.org/0000-0003-4686-4923">Saad Khan</a>)
**Repository:** <a href="https://github.com/kellylab/Fireworks" target ="_blank">https://github.com/kellylab/Fireworks</a>
**Version:** 0.3.2
**Editor:** @arokem
**Reviewer:** @dirmeier
**Archive:** <a href="https://doi.org/10.5281/zenodo.3339548" target="_blank">10.5281/zenodo.3339548</a>

## Status

[![status](http://joss.theoj.org/papers/6156356281b38760548fdb14505d9ba1/status.svg)](http://joss.theoj.org/papers/6156356281b38760548fdb14505d9ba1)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/6156356281b38760548fdb14505d9ba1"><img src="http://joss.theoj.org/papers/6156356281b38760548fdb14505d9ba1/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/6156356281b38760548fdb14505d9ba1/status.svg)](http://joss.theoj.org/papers/6156356281b38760548fdb14505d9ba1)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/kellylab/Fireworks" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dirmeier, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kellylab/Fireworks">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.3.2
- [x] **Authorship:** Has the submitting author (@smk508) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dirmeier it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01478/joss.01478/10.21105.joss.01478.pdf)

**Comment by smk508** [comment]
Hi @dirmeier . Do you have any updates on this review or any questions?

**Comment by arokem** [comment]
Hello @dirmeier! Have you had a chance to take a look?

**Comment by dirmeier** [comment]
Yeah, the review is in the repo's issue tracker..

**Comment by smk508** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by smk508** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1478 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:123:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:123:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:121:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:121:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:81:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by dirmeier** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1478 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:123:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:123:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:121:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:121:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:81:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by dirmeier** [comment]
Hey @arokem ,
I think once we fix the error above we are done with the review. I am not sure what is failing here, the `md` file seems fine.

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1478 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:123:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:123:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:121:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:121:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:81:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arokem** [comment]
@openjournals/joss-eics : does anyone know what this error means? I am failing to debug this just by looking at the markdown.

**Comment by kyleniemeyer** [comment]
I would try removing the empty `orcid:` field for the second author, I think whedon gets confused by that

**Comment by danielskatz** [comment]
something is wrong with an orcid

**Comment by arokem** [comment]
@smk508 : I implemented @kyleniemeyer's suggestion here: https://github.com/kellylab/Fireworks/pull/75. If you merge that, we can take a look and see what remains to complete the review of this paper.

**Comment by smk508** [comment]
Hi @arokem ,

Sorry I was on vacation for the weekend so I didn't see this. I've merged the PR.

**Comment by smk508** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1478 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/author.rb:58:in `block in build_affiliation_string': Problem with affiliations for Saad Khan, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/author.rb:57:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/author.rb:57:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:141:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:141:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:138:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:138:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:84:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
Ah, it looks like the `affiliations` block is not right. Can you change
```affiliations:
    - name: Systems & Computational Biology, Albert Einstein College of Medicine
```
to 
```
affiliations:
    - name: Systems & Computational Biology, Albert Einstein College of Medicine
      index: 1
```

**Comment by smk508** [comment]
Ok let's see if that worked. @whedon generate pdf

**Comment by smk508** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01478/joss.01478/10.21105.joss.01478.pdf)

**Comment by smk508** [comment]
ok it builds now

**Comment by arokem** [comment]
Sorry for the slowness here. One more comment: the figure caption contains the words "Figure 1". Please remove these, so that you don't get a duplication of these words in the PDF. 

Also, the reference to the Paszke paper seems partial. Is there more information?

**Comment by smk508** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01478/joss.01478/10.21105.joss.01478.pdf)

**Comment by smk508** [comment]
Ok I've updated the figure caption. The Paszke reference was meant to be a reference to the Pytorch library itself and its built-in data processing modules when I was comparing them to Fireworks.

**Comment by arokem** [comment]
Gotcha. Looks like it's missing a couple of words, though. 

See: https://github.com/pytorch/pytorch/blob/master/CITATION

**Comment by smk508** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01478/joss.01478/10.21105.joss.01478.pdf)

**Comment by smk508** [comment]
Oh sorry. I misunderstood what you were saying before! I fixed the typo in the citations now.

**Comment by arokem** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/2934664 is OK
- 10.1093/bib/bbw068 is OK
- 10.1145/2934664 is OK
- 10.1007/s13218-015-0381-0 is OK
- 10.1007/bf00140399 is OK
- 10.1038/nature14539 is OK

MISSING DOIs

- https://doi.org/10.1163/1574-9347_bnp_e612900 may be missing for title: Keras

INVALID DOIs

- None
```

**Comment by arokem** [comment]
I think that Whedon is checking all the references in your bib file. I believe everything is in order here.

**Comment by arokem** [comment]
@smk508 : could you please create an archive of the software (e.g., using https://zenodo.org) and post the link + DOI here? 

I apologize in advance for the additional delay, but I am heading out on vacation and will be back heree next week to move this ahead.

**Comment by smk508** [comment]
Ok that sounds good. I've made an archive on zenodo by following thir instructions and added a badge to the README.
DOI: 10.5281/zenodo.3339548
URL: https://zenodo.org/badge/latestdoi/135873580

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.3339548 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3339548" target="_blank">10.5281/zenodo.3339548</a> is the archive.

**Comment by arokem** [comment]
@openjournals/joss-eics : I believe this paper is ready for your final review

**Comment by danielskatz** [comment]
Is version 0.3.0 correct? It seems like perhaps this should be 0.3.2?

**Comment by danielskatz** [comment]
Also, I don't think Kubeflow is a journal, so in paper.bib:
@misc{kubeflow_2019, title={Kubeflow}, howpublished={https://www.kubeflow.org/}, journal={Kubeflow}, year={2019}, month={Jan}
}
should probably be:
@misc{kubeflow_2019, title={Kubeflow}, howpublished={https://www.kubeflow.org/}, year={2019}, month={Jan}
}

**Comment by smk508** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01478/joss.01478/10.21105.joss.01478.pdf)

**Comment by smk508** [comment]
Ok I've updated the kubeflow citation in paper.bib. The current version is 0.3.2, yes. I don't know how to change the top post in this thread to say 0.3.2.

**Comment by danielskatz** [comment]
@whedon set 0.3.2 as version

**Comment by whedon** [comment]
OK. 0.3.2 is the version.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/849

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/849, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
sorry, I see a few more small things in the bib - can we try with https://github.com/kellylab/Fireworks/pull/76 ?

**Comment by smk508** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by smk508** [comment]
Ok I merged the PR

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01478/joss.01478/10.21105.joss.01478.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/850

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/850, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1152950113117134849) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/851
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01478](https://doi.org/10.21105/joss.01478)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by smk508** [comment]
Thanks!

**Comment by danielskatz** [comment]
Thanks to @dirmeier for reviewing and @arokem for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01478/status.svg)](https://doi.org/10.21105/joss.01478)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01478">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01478/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01478/status.svg
   :target: https://doi.org/10.21105/joss.01478
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01478/status.svg)](https://doi.org/10.21105/joss.01478)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
