### ISSUE TITLE
[PRE REVIEW]: Wikipedia2Vec: An Optimized Tool for Learning Embeddings of Words and Entities from Wikipedia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1479]
**Submitting author:** @ikuyamada (<a href="http://orcid.org/0000-0002-7980-7661">Ikuya Yamada</a>)
**Repository:** <a href="https://github.com/wikipedia2vec/wikipedia2vec" target ="_blank">https://github.com/wikipedia2vec/wikipedia2vec</a>
**Version:** v1.0.3
**Editor:** @usethedata
**Reviewers:** @ionlights

**Author instructions**

Thanks for submitting your paper to JOSS @ikuyamada. **Currently, there isn't an JOSS editor assigned** to your paper.

@ikuyamada if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1479 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1479 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01479/joss.01479/10.21105.joss.01479.pdf)

**Comment by danielskatz** [comment]
👋  @ikuyamada - what's going on between https://github.com/openjournals/joss-reviews/issues/1477 and this submission?

**Comment by ikuyamada** [comment]
@danielskatz Thank you for your comments and I am sorry to bother you. I mistakenly withdrew the previous paper. It would be appreciated if we can proceed based on this submission.

**Comment by danielskatz** [comment]
👋 @usethedata - would you also be willing to edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by usethedata** [comment]
Working on finding reviewers.  Sorry for my delay.

**Comment by usethedata** [comment]
Two declines and a deferral on reviewers.  Going back to look for additional options.  Suggestions welcomed.

**Comment by usethedata** [comment]
@ikuyamada Still working on finding reviewers, but having some challenges.  Any suggestions you have will be appreciated.

**Comment by ikuyamada** [comment]
@usethedata Thank you for working on finding reviewers of my article! However, I don't understand what kind of suggestions that are needed here. Are there a list of any reviewer candidates of this journal or can I recommend any researchers that are capable of reviewing this paper?

**Comment by usethedata** [comment]
@ikuyamada What I'm looking for is if you know someone, who does not have a conflict of interest with you (see our [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy) and who would be qualified to review the work.  We have a list of [people who've volunteered as reviewers](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822), but I've already been working through that lists, looking for people with NLP and Python expertise.

**Comment by ikuyamada** [comment]
@usethedata I am sorry but I do not come up with any suitable reviewers.

**Comment by usethedata** [comment]
@ikuyamada Understood.  Thanks for checking. Let me dig further.

**Comment by usethedata** [comment]
👋  @jkahn @linuxscout @alexhanna @ionlights We're looking for a couple of reviewers for a JOSS paper "Wikipedia2Vec: An Optimized Tool for Learning Embeddings of Words and Entities from Wikipedia".  Would any of you be willing to take this on?  Thanks much for considering.

**Comment by ionlights** [comment]
@usethedata hey, sorry for the late reply. i'll give this a look in a few hours and get back to you. 👍

**Comment by usethedata** [comment]
👋 @ionlights Thoughts?

**Comment by ionlights** [comment]
> 👋 @ionlights Thoughts?

@usethedata i think i can give this a review. it's my first review with JOSS. 😅i've given the following a look-over, as that all i need to know – aside from domain-specific knowledge?
- https://joss.readthedocs.io/en/latest/
- https://joss.readthedocs.io/en/latest/review_criteria.html
- https://joss.readthedocs.io/en/latest/review_checklist.html

i'll most likely be able to give this a look during my flights later this week, so if someone else chimes in, just let me know.

**Comment by usethedata** [comment]
@ionlights Thanks much.  I am looking for a second reviewer (and have a couple of options).  If I can get one in the next couple of days, I'll open up the review issue then.  If I'm still looking by Wednesday evening, I'll open the review issue with just one reviewer and add the second one manually.  When I open the review issue, you'll see a checklist there for you, and that's where there would be any discussion about the review.

**Comment by usethedata** [comment]
@whedon set @ionlights as reviewer

**Comment by usethedata** [comment]
@whedon assign @ionlights as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ionlights

**Comment by usethedata** [comment]
I'm still working on getting a second reviewer. But in the interests of letting the review move forward, I'm opening the review issue and will manually add a second reviewer after we find one.

**Comment by usethedata** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1558. Feel free to close this issue now!
