### ISSUE TITLE
[REVIEW]: tcherry: Learning the structure of tcherry trees

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1480]
**Submitting author:** @katrinekirkeby (<a href="http://orcid.org/0000-0001-6065-1583">Katrine Kirkeby</a>)
**Repository:** <a href="https://github.com/nvihrs14/tcherry" target ="_blank">https://github.com/nvihrs14/tcherry</a>
**Version:** 0.1.1
**Editor:** @jasonclark
**Reviewer:** @kellieotto, @dhhagan 
**Archive:** <a href="https://doi.org/10.5281/zenodo.3340382" target="_blank">10.5281/zenodo.3340382</a>

## Status

[![status](http://joss.theoj.org/papers/b8118cb7ec7b0fd7bf93ae41dbcc65ea/status.svg)](http://joss.theoj.org/papers/b8118cb7ec7b0fd7bf93ae41dbcc65ea)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/b8118cb7ec7b0fd7bf93ae41dbcc65ea"><img src="http://joss.theoj.org/papers/b8118cb7ec7b0fd7bf93ae41dbcc65ea/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/b8118cb7ec7b0fd7bf93ae41dbcc65ea/status.svg)](http://joss.theoj.org/papers/b8118cb7ec7b0fd7bf93ae41dbcc65ea)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/nvihrs14/tcherry" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kellieotto, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @jasonclark know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nvihrs14/tcherry">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.1)?
- [x] **Authorship:** Has the submitting author (@katrinekirkeby) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nvihrs14/tcherry">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.1)?
- [x] **Authorship:** Has the submitting author (@katrinekirkeby) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kellieotto it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01480/joss.01480/10.21105.joss.01480.pdf)

**Comment by jasonclark** [comment]
@kellieotto Can you carry out the review this week? Thanks!

**Comment by kellieotto** [comment]
Yes, thank you for the reminder!

**Comment by kellieotto** [comment]
@jasonclark @katrinekirkeby The package looks good on the whole but needs minor revisions. I've detailed them in the issues referenced above. Please tag me when they're done and I will take another look.

**Comment by katrinekirkeby** [comment]
@kellieotto Thank you for reviewing this packages.  We have now tried to solved the missing issues, but regarding the issue about gramma we are not quite sure what you mean since we are not native english speakers, could you please clarify what the issues are

**Comment by kellieotto** [comment]
Thanks for making those changes so quickly @katrinekirkeby. Everything looks good now. I made some very minor grammar edits to the paper in the issue here: https://github.com/nvihrs14/tcherry/issues/4

**Comment by katrinekirkeby** [comment]
@kellieotto I have now fixed the grammar edits

**Comment by kellieotto** [comment]
Looks good! @jasonclark I recommend this package for acceptance.

**Comment by arfon** [comment]
:wave: @dhhagan - please complete your review when you get a chance.

**Comment by dhhagan** [comment]
Hey @arfon I'm trying to complete the review now, but it appears the invite to the repository/issue didn't work and I can't seem to update the checkboxes above. Is there something I'm missing..?

**Comment by arfon** [comment]
@dhhagan - you'll need to accept this invite (shown at the top of this page) https://github.com/openjournals/joss-reviews/invitations

**Comment by dhhagan** [comment]
@arfon For some reason, it keeps saying that it can't find the invitation and won't let me accept.

<img width="1429" alt="Screen Shot 2019-06-25 at 12 58 12 PM" src="https://user-images.githubusercontent.com/4370504/60117856-fe377e80-9748-11e9-86e9-15a31a33cabc.png">

**Comment by arfon** [comment]
> @arfon For some reason, it keeps saying that it can't find the invitation and won't let me accept.

Hrm. Can you try again now?

**Comment by dhhagan** [comment]
@arfon That worked! Should have the review done within 24h.

**Comment by dhhagan** [comment]
Hey @arfon Sorry to bother you again, but for some reason when I logged on this morning,  I no longer had access - not sure what's going on with GitHub...

**Comment by arfon** [comment]
@dhhagan - I'm so sorry for the trouble we've caused you here. You've actually helped me uncover a bug in our infrastructure. This should be fixed in https://github.com/openjournals/joss/commit/16230e01a4fdafc7a9df4f894b8f4a0dc46909b7 but you will have to accept the invite (hopefully for the last time!) again.

**Comment by dhhagan** [comment]
Hey @arfon and @katrinekirkeby I have completed most of the review - I opened up a couple of issues on the github repository - if you can address those, I will approve ASAP!

**Comment by arfon** [comment]
> Hey @arfon and @katrinekirkeby I have completed most of the review - I opened up a couple of issues on the github repository - if you can address those, I will approve ASAP!

Excellent, thanks @dhhagan. @katrinekirkeby - please take a look at these issues and let us know when you have done so.

**Comment by katrinekirkeby** [comment]
> Hey @arfon and @katrinekirkeby I have completed most of the review - I opened up a couple of issues on the github repository - if you can address those, I will approve ASAP!

Hello @dhhagan regarding the issue about the names, it is a choice we made because we think the name should say what the function is made for. Regarding the issue about contributions we have stated in the readme that the packages is a part of our Masters thesis, and because of that we don’t will be adding further functions, but we will answer questions over mail

**Comment by dhhagan** [comment]
Okay then - I think it's done. I've checked off the last box.

**Comment by arfon** [comment]
@katrinekirkeby - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by arfon** [comment]
I've just emailed the submitting author to ask them to return to this submission soon.

**Comment by katrinekirkeby** [comment]
> I've just emailed the submitting author to ask them to return to this submission soon.

Sorry for the late answer, somehow the emails ended up in my spam box. I'm not quite sure how to make an archive of the software in Zenodo/figshare/other service, but I have baked a new release of the software and made a new release on GitHub where this number is under the tags version: e472a7a

**Comment by mikldk** [comment]
@katrinekirkeby See e.g. <https://genr.eu/wp/cite/> (or some other guide) on how to do that. It is only a few steps.

**Comment by katrinekirkeby** [comment]
> @katrinekirkeby - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:
> 
> * The title of the archive is the same as the JOSS paper title
> * That the authors of the archive are the same as the JOSS paper authors
> 
> I can then move forward with accepting the submission.

The DOI of the zenodo archive is: 10.5281/zenodo.3340382

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3340382" target="_blank">10.5281/zenodo.3340382</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/845

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/845, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1151839432309399552) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/846
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01480](https://doi.org/10.21105/joss.01480)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@kellieotto, @dhhagan - many thanks for your reviews here and to @jasonclark for editing this submission.

@katrinekirkeby - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01480/status.svg)](https://doi.org/10.21105/joss.01480)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01480">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01480/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01480/status.svg
   :target: https://doi.org/10.21105/joss.01480
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01480/status.svg)](https://doi.org/10.21105/joss.01480)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
