### ISSUE TITLE
[PRE REVIEW]: Delira: A High-Level Framework for Deep Learning in Medical Image Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1484]
**Submitting author:** @haarburger (<a href="http://orcid.org/0000-0002-2405-640X">Christoph Haarburger</a>)
**Repository:** <a href="https://github.com/justusschock/delira" target ="_blank">https://github.com/justusschock/delira</a>
**Version:** v0.3.2
**Editor:** @mbobra
**Reviewers:** @PingjunChen, @acolum

**Author instructions**

Thanks for submitting your paper to JOSS @haarburger. **Currently, there isn't an JOSS editor assigned** to your paper.

@haarburger if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1484 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
Hi @haarburger, our build system can't find your paper (neither can I). Did you prepare a paper according to [our author guidelines](https://joss.readthedocs.io/en/latest/submitting.html)?

**Comment by haarburger** [comment]
The paper was still in a non-master branch. I'll report back here after it is merged to master.

**Comment by haarburger** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by haarburger** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1484 with the following error: 

 Could not find bibliography file: paper.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by haarburger** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01484/joss.01484/10.21105.joss.01484.pdf)

**Comment by kyleniemeyer** [comment]
Great, thanks @haarburger! We'll proceed now.

**Comment by kyleniemeyer** [comment]
@whedon assign @mbobra as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by mbobra** [comment]
@haarburger Would you like to suggest any reviewers from [this list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822)?

**Comment by haarburger** [comment]
I suggest @PingjunChen, @sealhuang and @fernandoandreotti (in random order) from the list.

**Comment by mbobra** [comment]
@sealhuang and @fernandoandreotti Are you available to review this submission for JOSS?

**Comment by mbobra** [comment]
@haarburger Just an update: I'm working on finding additional reviewers!

**Comment by fernandoandreotti** [comment]
Sorry guys, it seems interesting but unfortunately I've been quite busy.

**Comment by mbobra** [comment]
@whedon assign @PingjunChen as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @PingjunChen

**Comment by mbobra** [comment]
@whedon add @acolum as reviewer

**Comment by whedon** [comment]
OK, @acolum is now a reviewer

**Comment by mbobra** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1488. Feel free to close this issue now!
