### ISSUE TITLE
[REVIEW]: FRIDGe: Fast Reactor Input Generator

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1486]
**Submitting author:** @ryanstwrt (<a href="http://orcid.org/0000-0003-4867-6555">Ryan Stewart</a>)
**Repository:** <a href="https://github.com/ryanstwrt/FRIDGe" target ="_blank">https://github.com/ryanstwrt/FRIDGe</a>
**Version:** v1.0.1
**Editor:** @katyhuff
**Reviewer:** @kellyrowland, @pshriwise
**Archive:** <a href="https://doi.org/10.5281/zenodo.3361822" target="_blank">10.5281/zenodo.3361822</a>

## Status

[![status](http://joss.theoj.org/papers/adf3c528083f563d4ac04163315ff90c/status.svg)](http://joss.theoj.org/papers/adf3c528083f563d4ac04163315ff90c)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/adf3c528083f563d4ac04163315ff90c"><img src="http://joss.theoj.org/papers/adf3c528083f563d4ac04163315ff90c/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/adf3c528083f563d4ac04163315ff90c/status.svg)](http://joss.theoj.org/papers/adf3c528083f563d4ac04163315ff90c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ryanstwrt/FRIDGe" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kellyrowland & @pshriwise, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @katyhuff know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ryanstwrt/FRIDGe">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.1
- [x] **Authorship:** Has the submitting author (@ryanstwrt) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ryanstwrt/FRIDGe">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.1
- [x] **Authorship:** Has the submitting author (@ryanstwrt) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kellyrowland, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01486/joss.01486/10.21105.joss.01486.pdf)

**Comment by katyhuff** [comment]
@ryanstwrt The first thing I'd like to note is the image in your paper -- it is too large. Please reduce its width.

**Comment by ryanstwrt** [comment]
@katyhuff Yup, I noticed this when I first uploaded my paper but I wasn't sure if I should update it before it went to you. After I update my document, does it automatically update the article proof so I can check my changes?

**Comment by pshriwise** [comment]
@ryanstwrt during install I got the following error:

`error: package directory 'frdige/driver' does not exist`

Just a typo it seems. Please find a relevant PR in your repo.

**Comment by ryanstwrt** [comment]
@pshriwise Thanks for the catch! I've merged the changes into the master branch.

**Comment by kellyrowland** [comment]
@ryanstwrt Please see issue #2 in your code repository for a request regarding clearer installation instructions.

**Comment by kellyrowland** [comment]
@pshriwise are you able to test that the `EBRII_Driver.i` input file generated with the instructions in the README functions correctly as MCNP6 input?

**Comment by pshriwise** [comment]
@kellyrowland I had some trouble too and found that it only worked if I imported the module from the repository rather than from the installed location. I think this is because the required data isn't being installed with the package...

@ryanstwrt I saw that you include package data in the `setup.py` but I think the preferred method these days is to use a `MANIFEST.in` file to make sure that data gets included in the package install. More info on that [here](https://python-packaging.readthedocs.io/en/latest/non-code-files.html)

The following `MANIFEST.in` file did the trick for me: 

```
include fridge/data/CotN/*.yaml
include fridge/data/assembly/*.yaml
include fridge/data/materials/*.yaml
include fridge/data/core/*.yaml
include fridge/fridge_input_file/*.yaml
include fridge/mcnp_input_files/*.i
```

**Comment by kellyrowland** [comment]
Good catch, thanks! I had only tried the import statement in the top repository directory.

**Comment by ryanstwrt** [comment]
@pshriwise I've added the `MANIFEST.in` file and left  `include_package_data=True`. I've also removed the `package_data={...}` from the `setup.py` file. I believe this should address the problem @kellyrowland was experiencing. Thank you for the information on the preferred methodology for including package data. Let me know if the problem persists, and I can take some more time to investigate.

**Comment by pshriwise** [comment]
A few minor edits/suggestions to the paper:

  - "in small scales" &rightarrow; "at reduced scale"
  - "Building simple geometries is **a** relatively..."
  - "inputes" &rightarrow; "inputs"
  - "(fuel, clad, coolant..." &rightarrow; "(fuel, cladding, coolant..."

**Comment by ryanstwrt** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by ryanstwrt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01486/joss.01486/10.21105.joss.01486.pdf)

**Comment by ryanstwrt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01486/joss.01486/10.21105.joss.01486.pdf)

**Comment by ryanstwrt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01486/joss.01486/10.21105.joss.01486.pdf)

**Comment by kellyrowland** [comment]
@ryanstwrt I don't see the MCNP DOI in the latest article proof - it looks like the `.bib` file was updated with the DOI but the `.md` file still has the previous reference.

**Comment by kellyrowland** [comment]
The report by Lum et al. has a DOI at https://doi.org/10.2172/1415120 which should be included as well.

**Comment by ryanstwrt** [comment]
@kellyrowland I see the reference mistake for MCNP, and I've adjusted it to reference the updated source. I'll upload it here shortly. As for the report by Lem et al., the DOI you're referencing was a report that was sent to DOE, not the final paper that was included in the IRPhEP handbook. From what I can tell the handbook does not have a DOI.

**Comment by ryanstwrt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01486/joss.01486/10.21105.joss.01486.pdf)

**Comment by kellyrowland** [comment]
Noted, thanks. Looks good to me!

**Comment by kellyrowland** [comment]
Hi @katyhuff - it looks like we're all set on the review here. What are the next steps?

**Comment by katyhuff** [comment]
Thanks for your patience, I've been on travel. I'll do a few final checks.

**Comment by katyhuff** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.13182/NT11-135 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by katyhuff** [comment]
@ryanstwrt thanks for your submission. I'm going through some final checks and a few things popped up.


- [ ] Are there any individuals who have made substantive contributions to this work who are not included in the author list? Some roles in a project warrant co-authorship, and some do not. Really, only the community around the project can decide this. I often consider people who satisfy the roles delineated by this credit project (https://www.casrai.org/credit.html). For example, perhaps Prof. Palmer has served a conceptualilzation or support role. Whether that rises to the level of co-authorship is up to you, but I wanted to bring it up just in case.
- [ ] The citation regarding GenIV goals may be more robust if you include a URL, or if you refer to the technical report. I think the appropriate URL is https://www.gen-4.org/gif/jcms/c_9502/generation-iv-goals . Meanwhile, the appropriate technical report is probably this one... https://www.gen-4.org/gif/jcms/c_60729/technology-roadmap-update-2013 . To include the URL, you might try adding it to your bibfile entry as "url=" or "extra=". For the report, consider:

```bibtex
@techreport{behar_technology_2014,
	type = {Generation {IV} {International} {Forum}},
	title = {Technology {Roadmap} {Update} for {Generation} {IV} {Nuclear} {Energy} {Systems}},
	shorttitle = {{GIF} {Technology} {Roadmap}},
	url = {https://www.gen-4.org/gif/upload/docs/application/pdf/2014-03/gif-tru2014.pdf},
	language = {en},
	number = {January 2014 Update},
	institution = {OECD Nuclear Energy Agency},
	author = {Behar, Christophe},
	month = jan,
	year = {2014},
	note = {https://www.gen-4.org/gif/upload/docs/application/pdf/2014-03/gif-tru2014.pdf},
	pages = {66}
```
- [ ] I think the YAML citation could also be stronger, particularly with the information available at https://yaml.org/spec/1.2/spec.html and here https://yaml.org/spec/cvs/spec.pdf . The authors are copyrighted for each version in this package, so it's reasonable to include them as authors in the citation, and to cite the (very stable) version 1.2. 
- [ ] It is appropriate to summarize the state of the field, albeit briefly, just to express clearly how your tool expands on the existing capabilities in the literature. There are python packages with similar capabilities. For example, MCNP has come out with an MCNPTools package giving MCNP a python API (https://mcnp.lanl.gov/pdf_files/la-ur-17-21779.pdf) and PyNE has some, but certainly not all, of these capabilities. I think it's clear your tool is for a particular custom application, but you should make it clear how it goes beyond what exists.

**Comment by ryanstwrt** [comment]
@katyhuff Thanks for the comments. I've updated both the YAML and Gen IV citation to be more specific and provide a better reference for those who are interested. Along with this, I have added a few sentence presenting some work that has already been with MCNP and differentiating FRIDGe from these resources. I did take a look at CRediT and while Dr. Palmer has been instrumental in helping as a grad student, I am not sure if it is appropriate for me to put him on this paper as he has not been involved in the development of it. Hopefully I addressed all of your concerns. If not, please feel free to let me know and I will update accordingly.

**Comment by ryanstwrt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1486 with the following error: 

 Error reading bibliography ./paper.bib (line 49, column 1):
unexpected "@"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by ryanstwrt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1486 with the following error: 

 Error reading bibliography ./paper.bib (line 49, column 12):
unexpected "("
expecting letter, white space or "{"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by ryanstwrt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01486/joss.01486/10.21105.joss.01486.pdf)

**Comment by ryanstwrt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01486/joss.01486/10.21105.joss.01486.pdf)

**Comment by labarba** [comment]
@katyhuff — it looks like both reviewers have completed their checklists here. What's the status of this submission?

**Comment by katyhuff** [comment]
@labarba Thank you for the ping.

@pshriwise and @kellyrowland Thank you for your reviews -- we couldn't do this without you.

@ryanstwrt Thank you for your submission and for engaging actively in the review process! I have looked over the paper, double-checked all the DOI links, and have conducted a high-level review of the code itself. Thank you for handling my remaining comments. 

Everything looks ship-shape to me. At this point, please double-check the paper yourself, review any lingering details in your code/readme/etc., and then make an archive of the reviewed software in Zenodo/figshare/other service. Please be sure that the DOI metadata (title, authors, etc.) matches this JOSS submission. Once that's complete, please update this thread with the DOI of the archive, and I'll move forward with accepting the submission. Until then, now is your moment for final touchups!

**Comment by labarba** [comment]
Before the archive, we will need a new tagged release with all the changes during this review
https://github.com/ryanstwrt/FRIDGe/releases

**Comment by ryanstwrt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01486/joss.01486/10.21105.joss.01486.pdf)

**Comment by ryanstwrt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01486/joss.01486/10.21105.joss.01486.pdf)

**Comment by ryanstwrt** [comment]
I have released a new version of FRIDGe and archived it via Zenodo. 
Here is the DOI for the archive: 10.21105/joss.01486
Feel free to let me know if you need anything else.

**Comment by arfon** [comment]
@ryanstwrt - please don't use `10.21105/joss.01486` as the DOI for the archive. This is the DOI that we will use for the JOSS paper.

Please use a Zenodo-issued DOI.

**Comment by ryanstwrt** [comment]
I apologize, I misunderstood. Here is the new DOI: 10.5281/zenodo.3361822

**Comment by katyhuff** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by katyhuff** [comment]
@whedon set 10.5281/zenodo.3361822 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3361822" target="_blank">10.5281/zenodo.3361822</a> is the archive.

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01486/joss.01486/10.21105.joss.01486.pdf)

**Comment by katyhuff** [comment]
Thanks again to @ryanstwrt for your submission, and thanks very much to @pshriwise @kellyrowland for your reviews. I think this is ready to accept @openjournals/joss-eics !

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/888

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/888, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1159049736361353216) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/889
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01486](https://doi.org/10.21105/joss.01486)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@kellyrowland, @pshriwise - many thank for your reviews here and to @katyhuff for editing this submission ✨ 

@ryanstwrt - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01486/status.svg)](https://doi.org/10.21105/joss.01486)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01486">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01486/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01486/status.svg
   :target: https://doi.org/10.21105/joss.01486
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01486/status.svg)](https://doi.org/10.21105/joss.01486)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
