### ISSUE TITLE
[REVIEW]: Delira: A High-Level Framework for Deep Learning in Medical Image Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1488]
**Submitting author:** @haarburger (<a href="http://orcid.org/0000-0002-2405-640X">Christoph Haarburger</a>)
**Repository:** <a href="https://github.com/justusschock/delira" target ="_blank">https://github.com/justusschock/delira</a>
**Version:** v0.3.2
**Editor:** @mbobra
**Reviewer:** @PingjunChen, @acolum
**Archive:** <a href="https://doi.org/10.5281/zenodo.3247307" target="_blank">10.5281/zenodo.3247307</a>

## Status

[![status](http://joss.theoj.org/papers/744634c556aa17cdc2f41f6387b1975d/status.svg)](http://joss.theoj.org/papers/744634c556aa17cdc2f41f6387b1975d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/744634c556aa17cdc2f41f6387b1975d"><img src="http://joss.theoj.org/papers/744634c556aa17cdc2f41f6387b1975d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/744634c556aa17cdc2f41f6387b1975d/status.svg)](http://joss.theoj.org/papers/744634c556aa17cdc2f41f6387b1975d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/justusschock/delira" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@PingjunChen & @acolum, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mbobra know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/justusschock/delira">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.3.2)?
- [x] **Authorship:** Has the submitting author (@haarburger) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/justusschock/delira">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.3.2)?
- [x] **Authorship:** Has the submitting author (@haarburger) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @PingjunChen, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01488/joss.01488/10.21105.joss.01488.pdf)

**Comment by mbobra** [comment]
Sorry about Whedon's comment, @acolum! You are a reviewer, too :sunny:

**Comment by PingjunChen** [comment]
@haarburger please add DOI to references if exist. Also, the current reference format looks not standard.

**Comment by haarburger** [comment]
whedon commands

**Comment by haarburger** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by haarburger** [comment]
@whedon generate pdf from branch reformat-paper-refs

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch reformat-paper-refs. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01488/joss.01488/10.21105.joss.01488.pdf)

**Comment by haarburger** [comment]
@PingjunChen, unfortunately none of the references has a DOI. Please let me know if you have further suggestions on how to improve the reference format.

**Comment by PingjunChen** [comment]
@haarburger Thanks, now the reference format should be fine.  

I have some difficulty to understand the installation on the backend. Take tensorflow as an example,  does ```pip install delira[tf]``` mean ```pip install delira tf```? But in PyPI, `tf` is not `tensorflow` . Please give more explicit installation instructions. 

Because of the complexity of this framework, I need more time to check the functionalities and tests.

**Comment by haarburger** [comment]
@PingjunChen the pip command is supposed to be used exactly as stated in our readme. Maybe [this](https://stackoverflow.com/questions/46775346/what-do-square-brackets-mean-in-pip-install) explanation about the syntax is helpful. It means that we want to install the `tensorflow`/`pytorch` backend as an extra.

**Comment by PingjunChen** [comment]
@haarburger The link you provide helps me understand the usage of the square bracket. Although for deep learning people,  `tf` defaults to `tensorflow`, and you also give `tensorflow` link to `tf`. Nevertheless, I still suggest changing `tf` to `tensorflow`, at least in the `Installation` part. The main reason is to avoid ambiguity, as [`tf`](https://pypi.org/project/tf/) is already used by https://pypi.org/project/tf in PyPI.

**Comment by acolum** [comment]
I'm finished with my review and am recommending this for publication. @haarburger I just wanted to commend you and your team for a job well done writing and documenting this package. This is one of the best JOSS submissions I've reviewed.

**Comment by PingjunChen** [comment]
@mbobra Just a reminder that we have finished the review. Overall, this package has rich features for deep learning model training, data preparation, visualization, etc. In addition, the documentation is well-written with iPython notebook examples for classification, segmentation, and GAN applications. I recommend accepting for publication.

**Comment by haarburger** [comment]
Thank you @PingjunChen and @acolum for your quick reviews 👍

**Comment by mbobra** [comment]
@openjournals/joss-eics This submission is ready to be accepted! :rocket:

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01488/joss.01488/10.21105.joss.01488.pdf)

**Comment by arfon** [comment]
@haarburger - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? Please make sure that the title of the Zenodo archive and authors match the authors of the paper here.

Once you've done this, I can then move forward with accepting the submission.

**Comment by labarba** [comment]
I think the software also needs a new tagged release with the latest changes?

**Comment by arfon** [comment]
> I think the software also needs a new tagged release with the latest changes?

Oh yes. Please do that too when making the Zenodo archive!

**Comment by haarburger** [comment]
We'd like to add a few bugfixes and minor improvements to the new tag. I'll let you know when these changes are merged and tagged and the Zenodo archive is created.

**Comment by haarburger** [comment]
@labarba, @arfon we've finally tagged our repository and uploaded v0.4.0 to Zenodo at `10.5281/zenodo.3247307`

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3247307 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3247307" target="_blank">10.5281/zenodo.3247307</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/764

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/764, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1140576092580909056) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/765
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01488](https://doi.org/10.21105/joss.01488)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@PingjunChen, @acolum - many thanks for your reviews and to @mbobra for editing this submission ✨ 

@haarburger - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01488/status.svg)](https://doi.org/10.21105/joss.01488)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01488">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01488/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01488/status.svg
   :target: https://doi.org/10.21105/joss.01488
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01488/status.svg)](https://doi.org/10.21105/joss.01488)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
