### ISSUE TITLE
[PRE REVIEW]: BCAW: Automated tool for codon usage bias analysis for molecular evolution

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1489]
**Submitting author:** @AliYoussef96 (<a href="http://orcid.org/0000-0002-5201-387X">Ali Youssef</a>)
**Repository:** <a href="https://github.com/AliYoussef96/BCAW-Tool" target ="_blank">https://github.com/AliYoussef96/BCAW-Tool</a>
**Version:** v1.0.0
**Editor:** @mgymrek
**Reviewers:** @Benjamin-Lee

**Author instructions**

Thanks for submitting your paper to JOSS @AliYoussef96. **Currently, there isn't an JOSS editor assigned** to your paper.

@AliYoussef96 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1489 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
👋 @AliYoussef96 — You need to put your references into a `.bib` file, and add this to the metadata of the paper, as shown in the [Author Guide](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography).

Also, on a first look at your paper, I want to point out that Summary section throws the reader into the deep end with technical background and lots of jargon. Please give this another pass: we would like the paper to give a reader an idea of what the software does and what research context it is used for. Take note of this advice from the [Author Guide](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain):

> JOSS welcomes submissions from broadly diverse research areas. For this reason, we require that authors include in the paper some sentences that would explain the software functionality and domain of use to a non-specialist reader.

**Comment by labarba** [comment]
Folks — the author suggested @csoneson as editor, but given her focus on R (this is a Python package), maybe another editor can best handle this? Could either @lpantano or @mgymrek take this submission? Let me know!

**Comment by AliYoussef96** [comment]
> Folks — the author suggested @csoneson as editor, but given her focus on R (this is a Python package), maybe another editor can best handle this? Could either @lpantano or @mgymrek take this submission? Let me know!

I would also suggest @benjamin-lee. Thank You.

**Comment by Benjamin-Lee** [comment]
I'm happy to do it!

**Comment by AliYoussef96** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by labarba** [comment]
Thanks for agreeing to review this JOSS submission, @Benjamin-Lee! I will assign you now, but hold your horses, as we haven't assigned the handling editor yet (and they'll want a second reviewer).

I'm waiting for either @lpantano or @mgymrek to agree to edit.

**Comment by labarba** [comment]
@whedon assign @Benjamin-Lee as reviewer

**Comment by AliYoussef96** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1489 with the following error: 

 Error reading bibliography ./paper.bib (line 1, column 16):
unexpected "a"
expecting space or ","
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by AliYoussef96** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01489/joss.01489/10.21105.joss.01489.pdf)

**Comment by labarba** [comment]
I have sent an email to @mgymrek asking to edit this submission.

**Comment by mgymrek** [comment]
@whedon assign @mgymrek as editor

**Comment by whedon** [comment]
OK, the editor is @mgymrek

**Comment by mgymrek** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1500. Feel free to close this issue now!

**Comment by mgymrek** [comment]
@Benjamin-Lee thanks for agreeing to review! You can now head over to the review issue #1500 to complete the review.
