### ISSUE TITLE
[PRE REVIEW]: hmds: An R Package for Heuristic High and Multi Dimensional Scaling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#149]
**Submitting author:** @jirotubuyaki (<a href="http://orcid.org/0000-0001-6871-7727">Masashi Okada</a>)
**Repository:** <a href="https://github.com/jirotubuyaki/hmds" target ="_blank">https://github.com/jirotubuyaki/hmds</a>
**Version:** version 1.0
**Editor:** @karthik
**Reviewer:** @kevinushey

**What this issue is for**

Thanks for submitting your paper to JOSS @jirotubuyaki. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@noamross - is this a good candidate for rOpenSci?

**Comment by noamross** [comment]
Thanks for checking.  We don't do statistical methods packages; our [**scope**](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) is limited to data access, extraction, manipulation and facilitating reproducible workflows. 

I watch the full feed of package submissions, and will chime in if I see candidates for dual-submission.

**Comment by arfon** [comment]
> I watch the full feed of package submissions, and will chime in if I see candidates for dual-submission.

👍  OK thanks @noamross. Apologies for the noise 😄

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by arfon** [comment]
:wave: @nuest - would you be willing to review this submission for JOSS?

**Comment by arfon** [comment]
Hi @jirotubuyaki  - I'm struggling a little for find a reviewer for this submission. Is there anyone you could recommend from your research area that might be a good candidate?

**Comment by jirotubuyaki** [comment]
@arfon 
Thank you for sending a message to me. This package is made by Rcpp(R & C++).
I do not have a good candidate. Would you chose a reviewer for me.

**Comment by arfon** [comment]
@karthik - any chance you could help us find a reviewer for this submission?

**Comment by arfon** [comment]
:wave: @pragyansmita - would you be willing to review this submission for JOSS?

**Comment by karthik** [comment]
@arfon Just getting caught up. Sure, I'm happy to handle if you haven't found a reviewer.

**Comment by arfon** [comment]
@karthik - would you be willing to review this one?

**Comment by karthik** [comment]
@arfon sure

**Comment by karthik** [comment]
Pinged @kevinushey as a potential reviewer

**Comment by kevinushey** [comment]
@karthik I'd be happy to review this package.

**Comment by karthik** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by karthik** [comment]
@whedon assign @kevinushey as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kevinushey

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by karthik** [comment]
@whedon assign @kevinushey as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kevinushey

**Comment by karthik** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by karthik** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/214. Feel free to close this issue now!
