### ISSUE TITLE
[PRE REVIEW]: phasespace: $n$-body phase space generation in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1490]
**Submitting author:** @apuignav (<a href="http://orcid.org/0000-0001-8868-2947">Albert Puig Navarro</a>)
**Repository:** <a href="https://github.com/zfit/phasespace/" target ="_blank">https://github.com/zfit/phasespace/</a>
**Version:** 1.0.2
**Editor:** @poulson
**Reviewers:** @mdoucet, @stuartcampbell, @vyasr

**Author instructions**

Thanks for submitting your paper to JOSS @apuignav. **Currently, there isn't an JOSS editor assigned** to your paper.

@apuignav if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1490 with the following error: 

 Error reading bibliography ./paper.bib (line 13, column 7):
unexpected "S"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by labarba** [comment]
@apuignav Please check your `.bib` file... I think you're missing a comma in line 12.

**Comment by labarba** [comment]
👋  @poulson Could you handle this submission as editor? Have a look!

**Comment by apuignav** [comment]
> @apuignav Please check your `.bib` file... I think you're missing a comma in line 12.

Yup, sorry, done!

**Comment by apuignav** [comment]
Maybe @betatim, even though he's at the top of the list?

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01490/joss.01490/10.21105.joss.01490.pdf)

**Comment by mayou36** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01490/joss.01490/10.21105.joss.01490.pdf)

**Comment by apuignav** [comment]
Latest proof looks good to me!

**Comment by labarba** [comment]
I have sent an email to @poulson asking to edit this submission.

**Comment by poulson** [comment]
Hi @labarba! I would be happy to take this on. Thank you for your patience and follow up!

**Comment by labarba** [comment]
@whedon assign @poulson as editor

**Comment by whedon** [comment]
OK, the editor is @poulson

**Comment by poulson** [comment]
:wave: Tim (@betatim), it seems that your expertise in physics and python would be helpful for reviewing this submission. Would you be willing and able to do so?

:wave: Pawel (@jochym), given your expertise in theoretical physics and python, your help reviewing this submission would be greatly appreciated. Are you available and interested?

:wave: Mathieu (@mdoucet), given your expertise in neutron scattering and python, your thoughts on this submission would be immensely helpful. Are you interested and available?

**Comment by mdoucet** [comment]
@poulson Yes I can help.

**Comment by poulson** [comment]
Thank you, Mathieu (@mdoucet)!

**Comment by poulson** [comment]
@whedon add @mdoucet as reviewer

**Comment by whedon** [comment]
OK, @mdoucet is now a reviewer

**Comment by poulson** [comment]
:wave: Stuart (@stuartcampbell): given your expertise in particle physics and Python, you would be a great referee for this submission. Would you be willing and able to help handle this paper?
 
:wave: Lee (@mlxd): similarly, given your physics and python expertise, having you as a reviewer would be perfect. Do you have the time and interest to help handle this submission?

**Comment by mlxd** [comment]
Hi @poulson , I won't have the time in the coming month for this. If things haven't moved forward by end of July I should have some time by then.

**Comment by stuartcampbell** [comment]
Hi Jack, (@poulson),  I don't really know anything about particle physics, my background is in condensed matter physics and neutron/x-ray scattering.  But if you still want me to, I am willing to have a look.

**Comment by poulson** [comment]
@mlxd and @stuartcampbell: thank you for the helpful responses! I apologize for misreading the short descriptions of your expertise! I will reach out to others first.

Hi (@vyasr): Given your listed expertise in python and "particle simulation", would you be willing and able to review this submission?

Hi (@betatim): Would you reconsider reviewing this submission?

**Comment by poulson** [comment]
:wave: @betatim -- any thoughts on reviewing this submission?
:wave: @vyasr -- any thoughts on reviewing this submission?

**Comment by poulson** [comment]
Hi @stuartcampbell, would you mind stepping in as a reviewer on this despite your expertise being in condensed matter physics? Assuming you would feel comfortable?

**Comment by vyasr** [comment]
Apologies for not responding sooner. This package is unfortunately outside my realm of expertise, the particle simulations that I am familiar with are typically in soft condensed matter so I don't really know particle physics. I'm happy to provide code review, but if you'd like me to review I think it would be good to have a second reviewer who has some expertise in the field

**Comment by stuartcampbell** [comment]
I'd be happy to do it , but I would assume that the answers it gives are correct.

**Comment by apuignav** [comment]
Hey, just to point out that the tests check the physics answers against the accepted standard in particle physics, [TGenPhaseSpace](https://root.cern.ch/doc/master/classTGenPhaseSpace.html), and the [RapidSim](https://github.com/gcowan/RapidSim) software (extensively used in peer-reviewed publications), which makes use of TGenPhaseSpace for complex decay chains.

**Comment by stuartcampbell** [comment]
> Hey, just to point out that the tests check the physics answers against the accepted standard in particle physics, [TGenPhaseSpace](https://root.cern.ch/doc/master/classTGenPhaseSpace.html), and the [RapidSim](https://github.com/gcowan/RapidSim) software (extensively used in peer-reviewed publications), which makes use of TGenPhaseSpace for complex decay chains.

Thank you, yes I saw that it had a physics test in the code base and presumed it was testing against an accepted standard.

**Comment by poulson** [comment]
Thank you, Stuart (@stuartcampbell) and @vyasr! It seems adding you both as reviewers, with a focus on code and an understanding that there are unit tests in place, should lead to the most productive review process.

**Comment by poulson** [comment]
@whedon add @stuartcampbell as reviewer

**Comment by whedon** [comment]
OK, @stuartcampbell is now a reviewer

**Comment by poulson** [comment]
@whedon add @vyasr as reviewer

**Comment by whedon** [comment]
OK, @vyasr is now a reviewer

**Comment by poulson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1570. Feel free to close this issue now!
