### ISSUE TITLE
[PRE REVIEW]: STUMPY: A Powerful and Scalable Python Library for Time Series Data Mining

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1492]
**Submitting author:** @seanmylaw (<a href="http://orcid.org/0000-0003-2594-1969">Sean Law</a>)
**Repository:** <a href="https://github.com/TDAmeritrade/stumpy" target ="_blank">https://github.com/TDAmeritrade/stumpy</a>
**Version:** v1.0
**Editor:** @mbobra
**Reviewers:** @ejolly, @hooman650

**Author instructions**

Thanks for submitting your paper to JOSS @seanmylaw. **Currently, there isn't an JOSS editor assigned** to your paper.

@seanmylaw if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01492/joss.01492/10.21105.joss.01492.pdf)

**Comment by seanlaw** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by seanlaw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01492/joss.01492/10.21105.joss.01492.pdf)

**Comment by labarba** [comment]
@seanlaw — I'm going to send this back to you for some more work, because the paper itself does not quite meet [our expectations](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). Right now, the article is very brief and doesn't communicate a lot about the software, and its need or uses in research. While we don't expect a full article, it should be 250–1000 words (currently you have ~130 words). These items need to be improved:

- the summary describing high-level functionality and purpose of the software for a diverse, non-specialist audience;
- a clear statement of need that illustrates the research application of the software (including references to other software meeting similar needs).

In essence, the article needs to be improved with more description of how the software works, some examples, and use cases.

**Comment by seanlaw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01492/joss.01492/10.21105.joss.01492.pdf)

**Comment by seanlaw** [comment]
@labarba thank you for the feedback. I've added a summary that hopefully motivates the need for this software and I've, hopefully, clarified what the core competency (the efficient calculation of the matrix profile - which is the most computationally intensive part of motif (i.e., pattern) and discord (i.e., novelty/anomaly) discovery). 

Let me know if or where I can be more clear. Perhaps, you can direct me to some reasonably good examples that I can learn from.

**Comment by danielskatz** [comment]
Thanks @seanlaw - this looks good to go forward.  While I find an editor, you might want to fix the references - issues where letters are incorrectly in lower case can be fixed by putting {}s around letters of strings that should not be converted to lower case by bibtex.

**Comment by danielskatz** [comment]
👋 @VivianePons - would you be willing to edit this submission?

**Comment by VivianePons** [comment]
Hi Daniel, I will be on maternity leave starting Friday, so I cannot take new submissions. I haven't put myself "unavailable" yet because I'm finishing the edition of 2 papers

**Comment by labarba** [comment]
@VivianePons — Please set your `ooo` status even if you are finishing up two papers. Thanks! …and good luck with what is coming 👶

**Comment by labarba** [comment]
Perhaps @mbobra could be handling editor for this one?

**Comment by seanlaw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01492/joss.01492/10.21105.joss.01492.pdf)

**Comment by seanlaw** [comment]
> Thanks @seanlaw - this looks good to go forward. While I find an editor, you might want to fix the references - issues where letters are incorrectly in lower case can be fixed by putting {}s around letters of strings that should not be converted to lower case by bibtex.

@danielskatz Thanks for the pro tip! It should be fixed now.

@VivianePons Best of luck but I'm sure you'll do great!

**Comment by mbobra** [comment]
@labarba Sure, I'm happy to edit!

**Comment by labarba** [comment]
@whedon assign @mbobra as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by mbobra** [comment]
@whedon assign @ejolly as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ejolly

**Comment by mbobra** [comment]
@whedon add @hooman650 as reviewer

**Comment by whedon** [comment]
OK, @hooman650 is now a reviewer

**Comment by mbobra** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1504. Feel free to close this issue now!
