### ISSUE TITLE
[PRE REVIEW]: SmartEDA: An R Package for Automated Exploratory Data Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1495]
**Submitting author:** @sayanddude (<a href="http://orcid.org/0000-0002-6477-0376">Sayan Putatunda</a>)
**Repository:** <a href="https://github.com/daya6489/SmartEDA" target ="_blank">https://github.com/daya6489/SmartEDA</a>
**Version:** v0.3.1
**Editor:** @mgymrek
**Reviewers:** @nhejazi, @terrytangyuan 

**Author instructions**

Thanks for submitting your paper to JOSS @sayanddude. The JOSS editor @jasonclark, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@sayanddude if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jasonclark it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@jasonclark) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1495 with the following error: 

 Error producing PDF.
! Undefined control sequence.
l.444 the ISLR package \citep

Looks like we failed to compile the PDF

**Comment by labarba** [comment]
Hi @jasonclark — the author suggested you as editor, and I clicked on the wrong button which assigned you automatically. Please ignore. I'm looking for another editor and will swap that out ASAP.

**Comment by sayanddude** [comment]
@wheadon please compile the pdf again. I have corrected the issue.

**Comment by sayanddude** [comment]
> PDF failed to compile for issue #1495 with the following error:
> 
> Error producing PDF.
> ! Undefined control sequence.
> l.444 the ISLR package \citep
> 
> Looks like we failed to compile the PDF

please compile the pdf again. I have corrected the issue.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01495/joss.01495/10.21105.joss.01495.pdf)

**Comment by labarba** [comment]
@mgymrek 👋  — On the basis of topic and current editor loads, I'd like to assign this submission for you to edit. Can you take it?

**Comment by mgymrek** [comment]
@whedon assign @mgymrek as editor

**Comment by whedon** [comment]
OK, the editor is @mgymrek

**Comment by mgymrek** [comment]
@amoeba @masalmon @cdcrabtree @nhejazi @kellieotto Would you be willing to review this submission?

**Comment by nhejazi** [comment]
Happy to provide a review.

**Comment by mgymrek** [comment]
@whedon assign @nhejazi as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nhejazi

**Comment by mgymrek** [comment]
Thanks @nhejazi!
We are still looking for a second reviewer for this submission.
@corybrunson @terrytangyuan @strengejacke would either of you be willing to review this submission?

**Comment by terrytangyuan** [comment]
Yes

**Comment by mgymrek** [comment]
Thanks @terrytangyuan!

**Comment by mgymrek** [comment]
@whedon add @terrytangyuan  as reviewer

**Comment by whedon** [comment]
OK, @terrytangyuan  is now a reviewer

**Comment by mgymrek** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1509. Feel free to close this issue now!

**Comment by mgymrek** [comment]
Thanks @terrytangyuan and @nhejazi for agreeing to review. You may now head over to the review issue #1509 to complete the review. Let me know if you have any questions about the process.
