### ISSUE TITLE
[PRE REVIEW]: CGIMP: Real-time exploration and covariate projection for self-organizing map datasets'

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1496]
**Submitting author:** @adadiehl (<a href="http://orcid.org/0000-0002-0915-4570">Adam Diehl</a>)
**Repository:** <a href="https://github.com/Boyle-Lab/CGIMP" target ="_blank">https://github.com/Boyle-Lab/CGIMP</a>
**Version:** 1.0.0
**Editor:** @lpantano
**Reviewers:** @adriancbondia,  @arunhpatil

**Author instructions**

Thanks for submitting your paper to JOSS @adadiehl. **Currently, there isn't an JOSS editor assigned** to your paper.

@adadiehl if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1496 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
@adadiehl — You will need to rename the file here as `paper.md`
https://github.com/Boyle-Lab/CGIMP/tree/master/paper

**Comment by labarba** [comment]
👋  @lpantano — Based on topic and current editor loads, I'd like to assign you this submission. Can you take it? Let me know!

**Comment by lpantano** [comment]
Hi. yes, I will take it. thanks

**Comment by labarba** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by adadiehl** [comment]
I have renamed the manuscript as paper.md. Thank you!

-Adam

**Comment by lpantano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1496 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1496/paper/paper.md): mapping values are not allowed in this context at line 12 column 11 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:95:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by lpantano** [comment]
@adadiehl, it is possible you have a typo in the header for autors instead of authors?

**Comment by adadiehl** [comment]
You were correct. I've corrected it.

**Comment by lpantano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1496 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1496/paper/paper.md): mapping values are not allowed in this context at line 12 column 11 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:95:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by lpantano** [comment]
can you make sure: name, orcid and affiliation have the same indentation please?

**Comment by adadiehl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1496 with the following error: 

 Error reading bibliography ./CGIMP_manuscript.bib (line 9, column 9):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by adadiehl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01496/joss.01496/10.21105.joss.01496.pdf)

**Comment by adadiehl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01496/joss.01496/10.21105.joss.01496.pdf)

**Comment by adadiehl** [comment]
All appears to be well with the proof now.

**Comment by adadiehl** [comment]
@whedon generate pdf

>

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01496/joss.01496/10.21105.joss.01496.pdf)

**Comment by adadiehl** [comment]
@whedon <https://github.com/whedon> generate pdf

**Comment by adadiehl** [comment]
It looks like pdf generation may have stalled with the most recent version,
which corrects a problem with the author affiliations for AP Boyle. As far
as I know, this should be the last correction that needs to be made.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01496/joss.01496/10.21105.joss.01496.pdf)

**Comment by adadiehl** [comment]
Thank you. Everything looks good with the pdf.

**Comment by lpantano** [comment]
👋   @skummerf and @mnarayan, would you be interested in reviewing this tool? thanks!

**Comment by mnarayan** [comment]
Unfortunately, I am not available to review the next 4 weeks.

**Comment by lpantano** [comment]
@whedon assign @arunhpatil as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arunhpatil

**Comment by lpantano** [comment]
@whedon assign @adriancbondia as reviewr

**Comment by lpantano** [comment]
@whedon assign @adriancbondia as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @adriancbondia

**Comment by lpantano** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/j.cell.2013.09.043 may be missing for title: Dynamic trans-acting factor colocalization in human cells.
- https://doi.org/10.1093/bioinformatics/btq033 may be missing for title: BEDTools: a flexible suite of utilities for comparing genomic features.
- https://doi.org/10.1093/nar/gky018 may be missing for title: Conserved and species-specific transcription factor co-binding patterns drive divergent gene regulation in human and mouse

INVALID DOIs

- None
```

**Comment by lpantano** [comment]
@adadiehl can you check the references and add the DIO to them as shown here: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

Thanks

**Comment by adadiehl** [comment]
I’ve fixed DOIs for all references that I can. One does not appear to have a DOI. How do I handle that reference?


"The wind of heaven is that which flows between a horse's ears."

**Comment by lpantano** [comment]
I will ask about that, but probably we can start the review process. Thanks

**Comment by lpantano** [comment]
@whedon add  @arunhpatil as reviewer

**Comment by whedon** [comment]
OK,  @arunhpatil is now a reviewer

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1520. Feel free to close this issue now!
