### ISSUE TITLE
[PRE REVIEW]: AirMathOSS: A open source script-based tool for electronic aeronautical calculations 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1497]
**Submitting author:** @lucaspompeun (<a href="http://orcid.org/0000-0001-9625-4985">Lucas Neves</a>)
**Repository:** <a href="https://github.com/lucaspompeun/AirMathOSS" target ="_blank">https://github.com/lucaspompeun/AirMathOSS</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @lucaspompeun. **Currently, there isn't an JOSS editor assigned** to your paper.

@lucaspompeun if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1497 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/lib/whedon.rb:123:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/lib/whedon.rb:123:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/lib/whedon.rb:121:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/lib/whedon.rb:121:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/lib/whedon.rb:81:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
Hi @lucaspompeun — Could you clarify here how your submission meets the [JOSS requirements](shttps://joss.readthedocs.io/en/latest/submitting.html#submission-requirements)? In particular,

> The software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler)

**Comment by lucaspompeun** [comment]
Hi @labarba.
Mathematical modeling has become increasingly complex and potentialized with the use of computational routines and structures, becoming an object of fundamental study in engineering. Areas such as aeronautics and aerodesign require a large volume of calculations and analyze and are increasingly used as computational options in their structures since the reduction of errors and false-positive results are remarkable (Seider, 2012). In addition, with a greater application of computational models by engineers, it is necessary the development and publication of a script capable of calculating and meeting the demands of definitions of electronic elements in microelectronic model airplanes. This script, in open-source model, is fundamental for future research, its ability to malleability and implementation of new mathematical resources.

**Comment by labarba** [comment]
He @lucaspompeun — After a pre-review of your submission, and an assessment by the editorial board at large, we find that this submission does not quite meet our [submission requirements](http://joss.theoj.org/about#submission_requirements). In particular, while the software seems useful, it falls under the 'Minor utility' category, and we therefore decided not to put it through review. 

Thank you for considering JOSS as a venue for your software, and I hope you'll submit other software with research application in the future.
