### ISSUE TITLE
Icons beside paper titles not rendering

### ISSUE THREAD

**Issue by gvwilson** [openjournals/joss-reviews#15]
Firefox 46.0.1 on Mac OS X 10.10.5: small character icons (?) beside titles are showing up as unrenderable.
![screen shot 2016-05-06 at 1 11 38 pm](https://cloud.githubusercontent.com/assets/911566/15080474/6200ce38-138c-11e6-9961-8dd16b37ee14.png)

**Comment by arfon** [comment]
Thanks for reporting this @gvwilson. Would you mind opening this issue on https://github.com/openjournals/joss? (Also, I realize it would be awesome if you could move issues between repos on GitHub)
