### ISSUE TITLE
[PRE REVIEW]: KraljicMatrix: An R package for implementing the Kraljic Matrix to strategically analyze a firm’s purchasing portfolio

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#150]
**Submitting author:** @bradleyboehmke (<a href="http://orcid.org/0000-0002-3611-8516">Bradley Boehmke</a>)
**Repository:** <a href="https://github.com/bradleyboehmke/KraljicMatrix" target ="_blank">https://github.com/bradleyboehmke/KraljicMatrix</a>
**Version:** v0.1.0
**Editor:** @arfon
**Reviewer:** @cmsaie

**What this issue is for**

Thanks for submitting your paper to JOSS @bradleyboehmke. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@noamross - is this a good candidate for rOpenSci?

**Comment by noamross** [comment]
Thanks for checking.  We don't do statistical methods packages; our [**scope**](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) is limited to data access, extraction, manipulation and facilitating reproducible workflows.

**Comment by arfon** [comment]
👋  @bradleyboehmke - many thanks for this submission. Could you confirm that this software has a research application? Please see the 'requirements for submission' under the [author guidelines](http://joss.theoj.org/about#author_guidelines).

**Comment by bradleyboehmke** [comment]
@arfon 

The most established supply chain purchasing portfolio model in academic literature and practice is Kraljic’s model ([Kraljic, 1983](https://hbr.org/1983/09/purchasing-must-become-supply-management)), now known as the Kraljic Portfolio Matrix (KPM). However, one of the primary weaknesses of the KPM has been the qualitative nature of the model, which results in a subjective method for weighting and positioning suppliers or commodities in the quadrants of the KPM. Furthermore, there are no tools that assist/automate the analytic process for analysts performing supply chain purchasing portfolio analyses.  

The `KraljicMatrix` package provides a quantitative framework to objectively position purchases in the KPM matrix along with identifying which products and services to begin strategic sourcing efforts with.  This quantitative framework was based on a recent [paper](https://www.dropbox.com/s/5w7xh8ldrvodfvn/Manuscript.pdf?dl=1) I co-authored and is currently finishing its review process for publication at the Journal of Purchasing & Supply Management.  Moreover, the `KraljicMatrix` package was recently published on [CRAN](https://CRAN.R-project.org/package=KraljicMatrix) and is being implemented in the Air Force organization that performs contracting and purchasing analysis on over $10B worth of goods and services.  We are also actively advancing more perspectives of the KPM process both for academic literature and organizational practice and plan to expand the `KraljicMatrix` package’s capabilities as our science around supply chain purchasing analysis advances. 

Hopefully this clarifies the research application.

v/r,
Brad

**Comment by arfon** [comment]
Excellent, many thanks for the clarification here @bradleyboehmke. It's not clear that we have any reviewers suitable for this submission right now - are there any people in your research field who you would recommend as potential reviewers?

**Comment by bradleyboehmke** [comment]
@arfon 

I talked to Trevor Bihl <trevor.bihl@gmail.com> and he is willing to review.  I've got a emails out to a few others that could be potential reviewers as well.

**Comment by bradleyboehmke** [comment]
@arfon 

Cade Saie <cade.saie@gmail.com> is also willing to review the code.

**Comment by bradleyboehmke** [comment]
@arfon , just wanted to follow up to see if either of the two reviewers I suggested worked out or if I need to ask a few others.  I've got a few more in my back pocket if necessary.  Thx.

**Comment by arfon** [comment]
Trevor didn't get back to me so I just emailed Cade.

**Comment by cmsaie** [comment]
@arfon  I am willing to review

**Comment by arfon** [comment]
> @arfon I am willing to review

✨ thanks @cmsaie

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
@whedon assign @cmsaie as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @cmsaie

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/170. Feel free to close this issue now!

**Comment by arfon** [comment]
@cmsaie - please head over to #170 to actually carry out the review.

**Comment by TJBihl** [comment]
I need a little more than 4 days notice if I'm travelling.
