### ISSUE TITLE
[PRE REVIEW]: fitODBOD: An R Package to Model Binomial Outcome Data using Binomial Mixture and Alternate Binomial Distributions.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1503]
**Submitting author:** @Amalan-ConStat (<a href="http://orcid.org/0000-0002-0643-9052">Amalan Mahendran</a>)
**Repository:** <a href="https://github.com/Amalan-ConStat/R-fitODBOD" target ="_blank">https://github.com/Amalan-ConStat/R-fitODBOD</a>
**Version:** v1.4.0
**Editor:** @csoneson
**Reviewers:** @osorensen, @jjharden

**Author instructions**

Thanks for submitting your paper to JOSS @Amalan-ConStat. **Currently, there isn't an JOSS editor assigned** to your paper.

@Amalan-ConStat if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01503/joss.01503/10.21105.joss.01503.pdf)

**Comment by arfon** [comment]
:wave: @csoneson - the submitting author suggested you as the handling editor. Is this a paper you could edit for JOSS?

**Comment by csoneson** [comment]
@arfon Yes!

**Comment by arfon** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by arfon** [comment]
> @arfon Yes!

Great, thanks!

**Comment by csoneson** [comment]
👋@Amalan-ConStat - I'm taking a first look at your submission. If you have suggestions for suitable reviewers, please let me know!

**Comment by Amalan-ConStat** [comment]
Hello @arfon and @csoneson , Thank you for assigning an editor as swiftly as possible. I hope to be at your disposal when suggestions arise regarding my paper. My apologies but I have no suggestions for suitable reviewers for my R package submission.

**Comment by csoneson** [comment]
👋@osorensen, @nhejazi, @jjharden - would you be interested in reviewing this submission for JOSS?

**Comment by csoneson** [comment]
@Amalan-ConStat - while we wait for the invited reviewers to respond, there are a couple of things we can fix:
- I made a pull request to your repository with some suggestions regarding grammar and wording. Please have a look and merge if you agree
- Your paper is a bit on the long side for JOSS standards. In particular, the example code describing how to use the package would fit better in the documentation
- Please remove titles (Prof.) from the author list
- Please check the references - in a few cases you need case protection (forcing capitalization by enclosing text in {}). Also please add a DOI to Grassia (1977), and remove "Retrieved from" before the DOIs of the references where it appears, for consistency.

**Comment by csoneson** [comment]
@Amalan-ConStat It also looks like your continuous integration tests are failing, seemingly because of a timeout - could you look into this?

**Comment by osorensen** [comment]
@csoneson yes, I am interested in reviewing.

**Comment by csoneson** [comment]
@osorensen - great, thank you! We'll wait for one more reviewer accepting before opening the review issue.

**Comment by csoneson** [comment]
@whedon assign @osorensen as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @osorensen

**Comment by jjharden** [comment]
I can review this submission.

**Comment by csoneson** [comment]
@jjharden - awesome, thank you! Since we have our two reviewers, I'll go ahead and open the review issue now.

**Comment by csoneson** [comment]
@whedon add @jjharden as reviewer

**Comment by whedon** [comment]
OK, @jjharden is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1505. Feel free to close this issue now!

**Comment by csoneson** [comment]
@jjharden, @osorensen - please head over to #1505 for the review!
