### ISSUE TITLE
[REVIEW]: fitODBOD: An R Package to Model Binomial Outcome Data using Binomial Mixture and Alternate Binomial Distributions.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1505]
**Submitting author:** @Amalan-ConStat (<a href="http://orcid.org/0000-0002-0643-9052">Amalan Mahendran</a>)
**Repository:** <a href="https://github.com/Amalan-ConStat/R-fitODBOD" target ="_blank">https://github.com/Amalan-ConStat/R-fitODBOD</a>
**Version:** v1.4.1
**Editor:** @csoneson
**Reviewer:** @osorensen, @jjharden
**Archive:** <a href="https://doi.org/10.5281/zenodo.3265356" target="_blank">10.5281/zenodo.3265356</a>

## Status

[![status](http://joss.theoj.org/papers/388fc2f4d7c1e0ae83cf0de13ac038a4/status.svg)](http://joss.theoj.org/papers/388fc2f4d7c1e0ae83cf0de13ac038a4)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/388fc2f4d7c1e0ae83cf0de13ac038a4"><img src="http://joss.theoj.org/papers/388fc2f4d7c1e0ae83cf0de13ac038a4/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/388fc2f4d7c1e0ae83cf0de13ac038a4/status.svg)](http://joss.theoj.org/papers/388fc2f4d7c1e0ae83cf0de13ac038a4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Amalan-ConStat/R-fitODBOD" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@osorensen & @jjharden, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Amalan-ConStat/R-fitODBOD">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.4.1
- [x] **Authorship:** Has the submitting author (@Amalan-ConStat) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Amalan-ConStat/R-fitODBOD">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.4.1
- [x] **Authorship:** Has the submitting author (@Amalan-ConStat) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @osorensen, @jjharden it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01505/joss.01505/10.21105.joss.01505.pdf)

**Comment by csoneson** [comment]
@osorensen, @jjharden, please see reviewer instructions above - don't hesitate to ping me if you have any questions!

**Comment by csoneson** [comment]
@Amalan-ConStat - I've copied my comments from the PRE-REVIEW issue here. Please also have a look at the reviewer checklists above to see what the reviewers will be looking at. 

- I made a pull request to your repository with some suggestions regarding grammar and wording. Please have a look and merge if you agree
- Your paper is a bit on the long side for JOSS standards. In particular, the example code describing how to use the package would fit better in the documentation
- Please remove titles (Prof.) from the author list
- Please check the references - in a few cases you need case protection (forcing capitalization by enclosing text in {}). Also please add a DOI to Grassia (1977), and remove "Retrieved from" before the DOIs of the references where it appears, for consistency.
It also looks like your continuous integration tests are failing, seemingly because of a timeout.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01505/joss.01505/10.21105.joss.01505.pdf)

**Comment by Amalan-ConStat** [comment]
Hello reviewers, Thank you for the support. As requested I have made necessary changes for the article and merged it as well. Further there is no issue in continuous integration as there will not be a timeout.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01505/joss.01505/10.21105.joss.01505.pdf)

**Comment by Amalan-ConStat** [comment]
Thank you, it looks completely fine. That is all.

**Comment by jjharden** [comment]
I have reviewed the software and paper. Here are the issues that I see.

1. Installation instructions: I did not see a list of dependencies.
2. Example usage: There are plenty of examples, in the documentation. However, the example given on GitHub (“Just an example”) seems much simpler than what is described in the section titled “Modelling” in the paper. It would be helpful to see an example that describes demonstrates more of the software’s capabilities.
3. Automated tests: I did not see any description of automated tests or manual steps to verify the functions in the software.
3. References: Not all references have DOIs listed. Also, some have JSTOR and Google book links, which I would not recommend using.

**Comment by osorensen** [comment]
I cannot find a release in the GitHub repository. Please create a release [here](https://github.com/Amalan-ConStat/R-fitODBOD/releases) corresponding to v1.4.0.

**Comment by csoneson** [comment]
@osorensen, @jjharden - thanks for your reviews! @Amalan-ConStat - please address the reviewer comments above and the issues opened in your repository, and comment back here when you are ready or if you have questions!

**Comment by Amalan-ConStat** [comment]
I have resolved all issues regarding to the repository as requested in my repository, further I have addressed all comments too.  Thank you for reminding.

**Comment by osorensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01505/joss.01505/10.21105.joss.01505.pdf)

**Comment by Amalan-ConStat** [comment]
I have checked the article proof, seems fine. Thank you for going through the changes swiftly.

**Comment by osorensen** [comment]
@csoneson The updates to the software and the paper address all my concerns. I have close the issues I opened in the source repository. The software is well documented and easy to use, and implements important models which are well described in the statistical literature. Happy to accept it now.

**Comment by Amalan-ConStat** [comment]
Thank you very much for immediate responses and clear clarification requests for the issues in the R package. How may i proceed now ?

**Comment by csoneson** [comment]
@osorensen Thanks for your review!
@Amalan-ConStat Could you briefly summarize how you addressed @jjharden's comments above, to make it easier for him to have a second look? Regarding his point 3, it looks like most of the current unit tests are checking that the functions fail if given invalid input - could you also add some tests that confirm that they produce the correct output for given inputs?

**Comment by Amalan-ConStat** [comment]
As requested I was now added a few more but clear tests focusing on the outputs for the functions pxxxBin,
EstMLExxx and NegLLxxx. Most of these tests are for checking if produce exact values and if their outputs of necessary classes.

**Comment by Amalan-ConStat** [comment]
@osorensen  Regarding how i addressed issues pointed out by @jjharden , 
1. I added a dependencies section in the article. Which specifies why the dependency packages are used and what they are.
2. Just an example has been changed to a title called "Modelling", which explains the steps from 1 to 5 in the article more clearly. Where a final conclusion has been reached of which distribution fits the Alcohol data of Week 1. 
3. Using the testthat package I have updated the tests which will check if errors are produced, and functions do create necessary outputs as they should.
4. All references have been checked, except two (one article and book) all the others have dois.

In the article highlighted issues have been resolved
1. Binomial to binomial is done everywhere, except when abbreviations are used.
2. has to have is completed in occasions which are necessary.
3.  EstTriBin to EstMLETriBin is completed, which was a spelling miss by me.
4. spaces added as requested in two separate occasions between words.
5. One reference which had a capitalized title has been changed.

**Comment by osorensen** [comment]
@Amalan-ConStat , I think your last comment should be addressed to @csoneson rather than me.

**Comment by Amalan-ConStat** [comment]
Thank you for pointing that out, I have changed it now. and sorry for the inconvenience.

**Comment by csoneson** [comment]
Thanks @Amalan-ConStat. @jjharden - could you take a look at the revised submission and let us know whether the changes listed above addresses your concerns? Thanks!

**Comment by jjharden** [comment]
Everything looks good to me. My comments have been addressed.

**Comment by csoneson** [comment]
Thank you @jjharden - could you please also tick the empty boxes in the checklist above? 
@Amalan-ConStat - I will take another look at the submission and get back to you shortly to move on with the acceptance procedure.

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/pst.100 is OK
- 10.1111/j.1467-842X.1988.tb00844.x is OK
- 10.1093/biomet/70.1.269 is OK
- 10.2307/2342822 is OK
- 10.1007/978-94-010-1842-5_4 is OK
- 10.15288/jsa.1988.49.131 is OK
- 10.5539/ijsp.v2n2p24 is OK
- 10.1111/j.1467-9876.2007.00564.x is OK
- 10.1007/978-0-8176-4626-4_2 is OK
- 10.2307/2529589 is OK
- 10.2991/jsta.2013.12.1.8 is OK
- 10.1016/j.spl.2014.01.019 is OK
- 10.1080/03610928508828990 is OK
- 10.1111/j.1467-842X.1977.tb01277.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01505/joss.01505/10.21105.joss.01505.pdf)

**Comment by Amalan-ConStat** [comment]
I have gone through the article properly and it includes all the corrections without any issues.

**Comment by csoneson** [comment]
@Amalan-ConStat I have sent a pull request fixing some issues with a couple of the references. If this looks fine to you, please merge it. 
The next step is to create a Zenodo archive. Please make sure that the package version number is consistent everywhere, and that the Zenodo archive has exactly the same name and authors as the paper. Then, post the DOI from Zenodo in this thread.

**Comment by Amalan-ConStat** [comment]
I have completed the merge and it is done. package version number is set to 1.4.1 everywhere, which makes it consistent and accurate. Further, Zenodo archive has exactly the same name and authors as the paper. 

http://doi.org/10.5281/zenodo.3265356

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/pst.100 is OK
- 10.1111/j.1467-842X.1988.tb00844.x is OK
- 10.1093/biomet/70.1.269 is OK
- 10.2307/2342822 is OK
- 10.1007/978-94-010-1842-5_4 is OK
- 10.15288/jsa.1988.49.131 is OK
- 10.5539/ijsp.v2n2p24 is OK
- 10.1111/j.1467-9876.2007.00564.x is OK
- 10.1007/978-0-8176-4626-4_2 is OK
- 10.2307/2529589 is OK
- 10.2991/jsta.2013.12.1.8 is OK
- 10.1016/j.spl.2014.01.019 is OK
- 10.1080/03610928508828990 is OK
- 10.1111/j.1467-842X.1977.tb01277.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01505/joss.01505/10.21105.joss.01505.pdf)

**Comment by csoneson** [comment]
Hi @Amalan-ConStat - the Zenodo archive in the link above does not have the same title and authors as the paper - the title of the Zenodo archive is "Amalan-ConStat/R-fitODBOD: All issues addressed", and I have been included among the authors.

**Comment by Amalan-ConStat** [comment]
Very sorry, I have corrected them now in the zenodo archive. Hope now it is correct. Further article proof is correct. 

http://doi.org/10.5281/zenodo.3265356

**Comment by csoneson** [comment]
The title is correct now. However, the author names are given in different formats, and consequently the citations of the two records would be different (Mahendran et al. for paper, Amalan et al. for Zenodo archive).

**Comment by Amalan-ConStat** [comment]
Apologies again, I have corrected it now. http://doi.org/10.5281/zenodo.3265356

**Comment by csoneson** [comment]
@whedon set 10.5281/zenodo.3265356 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3265356" target="_blank">10.5281/zenodo.3265356</a> is the archive.

**Comment by csoneson** [comment]
@whedon set v1.4.1 as version

**Comment by whedon** [comment]
OK. v1.4.1 is the version.

**Comment by csoneson** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/pst.100 is OK
- 10.1111/j.1467-842X.1988.tb00844.x is OK
- 10.1093/biomet/70.1.269 is OK
- 10.2307/2342822 is OK
- 10.1007/978-94-010-1842-5_4 is OK
- 10.15288/jsa.1988.49.131 is OK
- 10.5539/ijsp.v2n2p24 is OK
- 10.1111/j.1467-9876.2007.00564.x is OK
- 10.1007/978-0-8176-4626-4_2 is OK
- 10.2307/2529589 is OK
- 10.2991/jsta.2013.12.1.8 is OK
- 10.1016/j.spl.2014.01.019 is OK
- 10.1080/03610928508828990 is OK
- 10.1111/j.1467-842X.1977.tb01277.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/810

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/810, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by csoneson** [comment]
@openjournals/joss-eics - I think we are ready for acceptance here! Thanks.

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1146004033120985089) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/811
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01505](https://doi.org/10.21105/joss.01505)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @Amalan-ConStat, your JOSS paper is published! 🚀 

Big thanks to our editor: @csoneson, and the reviewers: @osorensen, @jjharden — JOSS is thriving thanks to your contributions!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01505/status.svg)](https://doi.org/10.21105/joss.01505)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01505">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01505/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01505/status.svg
   :target: https://doi.org/10.21105/joss.01505
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01505/status.svg)](https://doi.org/10.21105/joss.01505)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by Amalan-ConStat** [comment]
Thank you for the unconditional support.
