### ISSUE TITLE
[REVIEW]: `hopit`: An R Package for Analysis of Reporting Behavior Using Generalized Ordered Probit Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1508]
**Submitting author:** @MaciejDanko (<a href="http://orcid.org/0000-0002-7924-9022">Maciej J. Dańko</a>)
**Repository:** <a href="https://github.com/MaciejDanko/hopit" target ="_blank">https://github.com/MaciejDanko/hopit</a>
**Version:** v0.10.1.9000
**Editor:** @alexhanna
**Reviewer:** @soodoku, @mkearney
**Archive:** <a href="https://doi.org/10.5281/zenodo.3530634" target="_blank">10.5281/zenodo.3530634</a>

## Status

[![status](http://joss.theoj.org/papers/73b926670df79a6cfa48cffa7d4775a6/status.svg)](http://joss.theoj.org/papers/73b926670df79a6cfa48cffa7d4775a6)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/73b926670df79a6cfa48cffa7d4775a6"><img src="http://joss.theoj.org/papers/73b926670df79a6cfa48cffa7d4775a6/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/73b926670df79a6cfa48cffa7d4775a6/status.svg)](http://joss.theoj.org/papers/73b926670df79a6cfa48cffa7d4775a6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/MaciejDanko/hopit" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@soodoku & @mkearney, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @alexhanna know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MaciejDanko/hopit">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.10.1.9000
- [x] **Authorship:** Has the submitting author (@MaciejDanko) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MaciejDanko/hopit">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.10.1.9000
- [x] **Authorship:** Has the submitting author (@MaciejDanko) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @soodoku, @mkearney it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01508/joss.01508/10.21105.joss.01508.pdf)

**Comment by MaciejDanko** [comment]
@soodoku, I noticed that you haven't checked "functionality" in the functionality checklist.

I decided to improved the functionality of the package by adding generic functions (_print_, _summary_, _plot_) to _latentIndex_, _standardizeCoef_, _getLevels_, and _getCutPoints_. I also improved the code so the functions are easier to run (less 'initial' parameters) for a user. The vignette and readme were slightly modified to follow the code update.

The community guidelines are now both in the readme and the contributing files

I also put DOI everywhere where it was passible.

**Comment by soodoku** [comment]
thanks @MaciejDanko. cool improvements. hope to test it out v. soon and update the checklist!

**Comment by soodoku** [comment]
@MaciejDanko: went through the package and the health example to check functionality. things seem to pan out. my only rec. would be = to prove to yourself that you are doing the right thing computationally, use either an off-the-shelf package or a toy example that you can reason through. otherwise, god speed!

**Comment by labarba** [comment]
@alexhanna — reviewer @mkearney seems to have gone MIA: could you try reaching out via email to get a status update? The other reviewer has completed his checklist.

**Comment by MaciejDanko** [comment]
@soodoku thank you very much for the review. I have already checked the package by the replicating the results of Jurges (2007, doi: 10.1002/hec.1134) model. While the data and the model slightly differed I got almost identical results.

**Comment by alexhanna** [comment]
Messaged @mkearney to check if he was able to still serve as a reviewer on the package.

**Comment by alexhanna** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01508/joss.01508/10.21105.joss.01508.pdf)

**Comment by alexhanna** [comment]
The paper draft looks good to me. Just a reminder to update the ??? parts of the paper.md file once the review is completed. I'll give @mkearney two weeks to reply to the review.

@openjournals/jose-eics if the reviewer doesn't respond, should we try to find another review for this package before continuing on it?

**Comment by arfon** [comment]
> @openjournals/jose-eics if the reviewer doesn't respond, should we try to find another review for this package before continuing on it?

@alexhanna - there are a couple of options here:

- Find another reviewer.
- If you're comfortable, you could do a quick review yourself.

**Comment by mkearney** [comment]
My apologies for the delay. The end of summer/beginning of Fall got away from me!

I got the package installed, working, and everything looks good, @MaciejDanko and @alexhanna !!

A few minor notes:

1. I would agree with @soodoku that it'd be nice to see/compare similar estimates from libraries.
1. Overall test coverage is solid, but I would point out there are no tests for functions in [R/boot.R](https://github.com/MaciejDanko/hopit/blob/master/R/boot.R). The main functionality seems to be supported with automated tests.
1. The installation was a bit picky on a linux and a mac to me. I had to temporarily rename my `.Rprofile` to get it installed properly. SO this was 100% user error, but I don't usually have to rename my `.Rprofile` to get packages working properly.
1. The vignette(s) are only in the form of PDFs. Can source code be supplied? Or a script-only version of the README (which I found to be useful)?

**Comment by MaciejDanko** [comment]
@mkearney, thank you for your review!

1. @mkearney and @soodoku, here is the mentioned "off-the-shelf-package-example" using a very simple model. I use the ``vglm`` function of the VGAM package. The ``vglm()`` and the ``hopit()`` fit different models, but for this particular (simple) example (and data ?) one can compare (at least) the fit of the health variable coefficients.

``library(VGAM)``
``library(hopit)``

``# Let us define a very simple model such that both packages can easily run it; i.e. ``
``# no interactions between threshold and health variables, ``
``# no survey design, no fitting of sigma, etc.``

``latent.formula <- health ~ hypertension + high_cholesterol +``
``    heart_attack_or_stroke + poor_mobility + very_poor_grip +``
``    depression + respiratory_problems +``
``    IADL_problems + obese + diabetes + other_diseases``

``thresh.formula <- ~ sex + ageclass + country``

``# Fit the hopit model``
``model1.hopit <- hopit(latent.formula = latent.formula,``
``                thresh.formula = thresh.formula,``
``                decreasing.levels = TRUE,``
``                data = healthsurvey)``

``# Fit the vglm model``
``healthsurvey$health <- ordered(healthsurvey$health)``
``thresh.right <- deparse(thresh.formula[[2]])``
``big.formula <- update.formula(latent.formula,paste('. ~ . +',thresh.right))``
``parallel.formula <- formula(paste('FALSE ~', thresh.right))``

``model1.vglm<-vglm(big.formula, data = healthsurvey,``
``            family = cumulative(parallel = parallel.formula, link = 'probit'))``

``# Can compare only health variables; thresholds are fitted differently``
``round(cbind(VGAM= - coef(model1.vglm)[5:15],``
``      hopit=coef(model1.hopit,aslist=TRUE)$latent.params),4)``

2. The bootstrapping (``boot_hopit``) is not present in automated test, because running it takes some time. The ``boot_hopit`` is also quite simple function, which is not so prone to errors or changes in the main algorithm. Nonetheless, all examples of the ``boot_hopit`` and vignette were tested and work fine.
 
3. The hopit package (installation, auto-tests, examples, etc.) was tested on Travis (Linux) and AppVeyor (Windows). It was also checked during submission to CRAN. I will try to figure out the issue with ``.Rprofile``, but so far I cannot replicate it. I cannot even guess why it could happen.
 
4. The script version of README can be seen on GitHub (click raw option or use this link [README](https://raw.githubusercontent.com/MaciejDanko/hopit/master/README.md)).  I am not sure if it is a common practice to supply a code for vignette on GitHub. Anyway, I am attaching the most recent version of the code here [hopit_vignette.zip](https://github.com/openjournals/joss-reviews/files/3573793/hopit_vignette.zip). I hope it will be helpful :).

**Comment by MaciejDanko** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01508/joss.01508/10.21105.joss.01508.pdf)

**Comment by MaciejDanko** [comment]
@alexhanna, the issue with ??? is resolved now.

**Comment by MaciejDanko** [comment]
@mkearney, 
I noticed emoji under my reply, but you haven't ticked "performance" on the functionality checklist off.
Please let me known if you have any questions. I would be happy to help

**Comment by alexhanna** [comment]
👋 hi @mkearney can you check the performance button?

**Comment by alexhanna** [comment]
:wave: @mkearney it's been two weeks. Can you look at this?

**Comment by MaciejDanko** [comment]
Actually it is almost six weeks since @mkearney replied :-/

**Comment by mkearney** [comment]
> @mkearney,
> I noticed emoji under my reply, but you haven't ticked "performance" on the functionality checklist off.
> Please let me known if you have any questions. I would be happy to help

I thought I fixed this two different times. That'll teach me to do Github things on my phone... 😅

**Comment by MaciejDanko** [comment]
Hi @alexhanna, the performance box has been ticked, could we proceed further? :)

**Comment by alexhanna** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01508/joss.01508/10.21105.joss.01508.pdf)

**Comment by alexhanna** [comment]
This is looking good to me. Thanks for all your work on this, @mkearney and @soodoku.

**Comment by alexhanna** [comment]
👋 @MaciejDanko - the last step we need you to do is get a DOI number from Zenodo and post it here. We can then assign the repository a DOI and pass it off to the EIC for acceptance.

**Comment by alexhanna** [comment]
👋 👋 @MaciejDanko - let's publish this thing!

**Comment by MaciejDanko** [comment]
@alexhanna - there is a DOI in article proof (10.21105/joss.01508) shall I use this one when uploading the package to Zenodo?

**Comment by MaciejDanko** [comment]
Hi @alexhanna,
here is the DOI:
10.5281/zenodo.3530634

**Comment by MaciejDanko** [comment]
![image](https://user-images.githubusercontent.com/20182356/68831560-f607bd80-06ae-11ea-9ad9-13913094dce6.png) @alexhanna - let's do it asap, next week I am out of office. :-)

**Comment by alexhanna** [comment]
@whedon set 10.5281/zenodo.3530634 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3530634" target="_blank">10.5281/zenodo.3530634</a> is the archive.

**Comment by alexhanna** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01508/joss.01508/10.21105.joss.01508.pdf)

**Comment by alexhanna** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.18637/jss.v009.i08 is OK
- 10.1016/j.socscimed.2009.05.013 is OK
- 10.1080/03610928508828893 is OK
- 10.1007/s11205-013-0542-1 is OK
- 10.1111/joes.12002 is OK
- 10.1080/0022250X.1975.9989847 is OK
- 10.1017/S000305540400108X is OK
- 10.1002/hec.1134 is OK
- 10.1007/s10182-006-0228-y is OK
- 10.1007/s10902-004-1753-6 is OK
- 10.1093/ije/dyt088 is OK
- 10.1016/j.socscimed.2019.03.002 is OK
- 10.18637/jss.v052.i05 is OK
- 10.7287/peerj.preprints.3188v1 is OK
- 10.18637/jss.v040.i08 is OK

MISSING DOIs

- https://doi.org/10.1201/b15166 may be missing for title: Dynamic Documents with R and knitr

INVALID DOIs

- None
```

**Comment by alexhanna** [comment]
Hi @MaciejDanko, I made a small PR for a missing DOI (https://github.com/MaciejDanko/hopit/pull/12). Once you accept this, we should be good to go.

**Comment by MaciejDanko** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.18637/jss.v009.i08 is OK
- 10.1016/j.socscimed.2009.05.013 is OK
- 10.1080/03610928508828893 is OK
- 10.1007/s11205-013-0542-1 is OK
- 10.1111/joes.12002 is OK
- 10.1080/0022250X.1975.9989847 is OK
- 10.1017/S000305540400108X is OK
- 10.1002/hec.1134 is OK
- 10.1007/s10182-006-0228-y is OK
- 10.1007/s10902-004-1753-6 is OK
- 10.1093/ije/dyt088 is OK
- 10.1016/j.socscimed.2019.03.002 is OK
- 10.18637/jss.v052.i05 is OK
- 10.7287/peerj.preprints.3188v1 is OK
- 10.18637/jss.v040.i08 is OK

MISSING DOIs

- https://doi.org/10.1201/b15166 may be missing for title: Dynamic Documents with R and knitr

INVALID DOIs

- None
```

**Comment by alexhanna** [comment]
@MaciejDanko -- hrm, it looks like it didn't update. if you're not citing the book, you could also choose to remove it.

**Comment by MaciejDanko** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by MaciejDanko** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01508/joss.01508/10.21105.joss.01508.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.18637/jss.v009.i08 is OK
- 10.1016/j.socscimed.2009.05.013 is OK
- 10.1080/03610928508828893 is OK
- 10.1007/s11205-013-0542-1 is OK
- 10.1111/joes.12002 is OK
- 10.1080/0022250X.1975.9989847 is OK
- 10.1017/S000305540400108X is OK
- 10.1002/hec.1134 is OK
- 10.1007/s10182-006-0228-y is OK
- 10.1007/s10902-004-1753-6 is OK
- 10.1093/ije/dyt088 is OK
- 10.1016/j.socscimed.2019.03.002 is OK
- 10.18637/jss.v052.i05 is OK
- 10.7287/peerj.preprints.3188v1 is OK
- 10.18637/jss.v040.i08 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by MaciejDanko** [comment]
Hi @alexhanna ,  it works now, thanks!

**Comment by alexhanna** [comment]
Excellent. @openjournals/joss-eics, this one is also ready to go.

**Comment by labarba** [comment]
Hi @MaciejDanko — I found no [releases](https://github.com/MaciejDanko/hopit/releases) in the repo. Please make a tagged release with the reviewed version of the software and post the version number here to update the metadata.

**Comment by MaciejDanko** [comment]
Hi @labarba - I made a release tagged v0.10.1.9000

**Comment by labarba** [comment]
@whedon set v0.10.1.9000 as version

**Comment by whedon** [comment]
OK. v0.10.1.9000 is the version.

**Comment by labarba** [comment]
Could you merge my small fix in the `.bib`?

**Comment by MaciejDanko** [comment]
Hi @labarba - small fix was merged, thank you.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.18637/jss.v009.i08 is OK
- 10.1016/j.socscimed.2009.05.013 is OK
- 10.1080/03610928508828893 is OK
- 10.1007/s11205-013-0542-1 is OK
- 10.1111/joes.12002 is OK
- 10.1080/0022250X.1975.9989847 is OK
- 10.1017/S000305540400108X is OK
- 10.1002/hec.1134 is OK
- 10.1007/s10182-006-0228-y is OK
- 10.1007/s10902-004-1753-6 is OK
- 10.1093/ije/dyt088 is OK
- 10.1016/j.socscimed.2019.03.002 is OK
- 10.18637/jss.v052.i05 is OK
- 10.7287/peerj.preprints.3188v1 is OK
- 10.18637/jss.v040.i08 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1103

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1103, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1196131446341226496) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1104
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01508](https://doi.org/10.21105/joss.01508)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @MaciejDanko, your JOSS paper is published! 🚀 

Sincere thanks to our editor: @alexhanna, and the reviewers: @soodoku, @mkearney — we couldn't do this without you 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01508/status.svg)](https://doi.org/10.21105/joss.01508)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01508">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01508/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01508/status.svg
   :target: https://doi.org/10.21105/joss.01508
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01508/status.svg)](https://doi.org/10.21105/joss.01508)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
