### ISSUE TITLE
[REVIEW]: SmartEDA: An R Package for Automated Exploratory Data Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1509]
**Submitting author:** @sayanddude (<a href="http://orcid.org/0000-0002-6477-0376">Sayan Putatunda</a>)
**Repository:** <a href="https://github.com/daya6489/SmartEDA" target ="_blank">https://github.com/daya6489/SmartEDA</a>
**Version:** 0.3.2
**Editor:** @mgymrek
**Reviewer:** @nhejazi, @terrytangyuan 
**Archive:** <a href="https://doi.org/10.5281/zenodo.3383824" target="_blank">10.5281/zenodo.3383824</a>

## Status

[![status](http://joss.theoj.org/papers/e56dad3d192cfeddd10fcc1550505ceb/status.svg)](http://joss.theoj.org/papers/e56dad3d192cfeddd10fcc1550505ceb)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/e56dad3d192cfeddd10fcc1550505ceb"><img src="http://joss.theoj.org/papers/e56dad3d192cfeddd10fcc1550505ceb/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/e56dad3d192cfeddd10fcc1550505ceb/status.svg)](http://joss.theoj.org/papers/e56dad3d192cfeddd10fcc1550505ceb)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/daya6489/SmartEDA" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@nhejazi & @terrytangyuan , please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mgymrek know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/daya6489/SmartEDA">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.3.2
- [x] **Authorship:** Has the submitting author (@sayanddude) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/daya6489/SmartEDA">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.3.2
- [x] **Authorship:** Has the submitting author (@sayanddude) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @nhejazi, @terrytangyuan  it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01509/joss.01509/10.21105.joss.01509.pdf)

**Comment by terrytangyuan** [comment]
I saw that you submitted for review to JSS already https://arxiv.org/pdf/1903.04754.pdf. Is this submission to JOSS still necessary?

**Comment by sayanddude** [comment]
@terrytangyuan Hi! We initially submitted the paper (given that it's a CRAN package) to JSS a couple of months back but it didn't work out there. We assure you that currently the paper is not under consideration for submission at any journal or conference. We are hoping that this paper goes through the rigorous review and gets published at JOSS!

**Comment by terrytangyuan** [comment]
@sayanddude I see. There are many other tools for exploratory data analysis in R. What makes this package useful/different?

**Comment by sayanddude** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01509/joss.01509/10.21105.joss.01509.pdf)

**Comment by sayanddude** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01509/joss.01509/10.21105.joss.01509.pdf)

**Comment by sayanddude** [comment]
> @sayanddude I see. There are many other tools for (automated) exploratory data analysis in R. What makes this package useful/different?

@terrytangyuan Hi! We have added a new section “Comparison with other R Packages” in the updated version of the paper pdf generated above. In this section we have given a snapshot of various capabilities of SmartEDA vs. some of the competing R packages (such as dlookr, explorer, DataExplorer, etc.) and have highlighted its advantages. Figure 9 in the paper gives a snapshot of the comparison and shows how it’s better than most of the available R packages for automated exploratory data analysis (Please find attached the figure below).

<img width="772" alt="Fig9" src="https://user-images.githubusercontent.com/7638057/61121279-77aacd00-a4bc-11e9-862e-b7a352b0f5ce.png">


To summarize, some of the key benefits of SmartEDA are:
•	No need remember the different R package names as SmartEDA has most of the exploratory function and dependencies
•	No need to write lengthy R scripts. SmartEDA does the exploratory in one line R script
•	It cuts down time for exploratory data analysis
•	SmartEDA has the extension of data.table to build customized summary statistics and cross tables
•	SmartEDA function can generate 100’s of ggplot (like scatter, bar, stacked bar, boxplot, density, qqplot, co-ordinate plots) at a time with customized theme using ggthemes package options
 
Also, SmartEDA finds mention in the study conducted by Staniak and Biecek (2018) where they reviewed the landscape of R packages for automated Exploratory analysis. Some of the distinguishing features of SmartEDA pointed out by the authors when comparing it with other R packages are:
•	The SmartEDA package  reports skewness and displays QQ plots against normal distribution 
•	SmartEDA package provides a method of visualizing multivariate relationships - parallel coordinate plot. 
•	SmartEDA give a reasonable insight into variables distributions and simple relationships.
•	Parallel Co-ordinates Plots (PCP) in SmartEDA is unique and is very well done. 
This paper by Staniak and Biecek (2019)  is available in ArXiv- https://arxiv.org/pdf/1904.02101.pdf 

Reference:
Mateusz Staniak and  Przemyslaw Biecek (2019), “The Landscape of R Packages for Automated Exploratory Data Analysis”, arXiv:1904.02101 [stat.CO]

**Comment by sayanddude** [comment]
> 👉 Check article proof 📄 👈

@nhejazi @terrytangyuan Requesting the reviewers to kindly consider the latest version of the pdf. We have added a section on “Comparison with other R Packages” and corrected some formatting issues in the earlier version.

**Comment by terrytangyuan** [comment]
@sayanddude Thanks. The table looks great. Some feedback:
* I see lots of long functions with >150 lines of code and the code style is not consistent (I suggest running a `lintr` check). Similarly, in the `roxygen` docs, the style is not consistent. I see both `##'` and `#'`. The indentation levels and the `roxygen` syntax are sometimes incorrect. Please double check. 
* There are no tests.
* Have you tried running this package on large datasets?
* Please make the paper more concise - I see many pages where each page only has one giant picture.

**Comment by sayanddude** [comment]
@terrytangyuan Thanks for the feedback! I will work on your comments and will get back to you with the updated paper and required code changes as soon as possible.

**Comment by labarba** [comment]
@sayanddude — can you give us a status update? If you will need considerable more time, it would help if you let us know and we can add a "paused" label here.

**Comment by sayanddude** [comment]
@labarba - Hi! We are almost done addressing all the comments of the reviewer. We are now at the final stages of creating the unit test for the package. Please give us a couple of more days, we will update the code repository along with the updated paper by Tuesday (6th Aug, 2019) end of the day. Thanks!

**Comment by sayanddude** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01509/joss.01509/10.21105.joss.01509.pdf)

**Comment by sayanddude** [comment]
@terrytangyuan  We have worked on addressing all of your comments. Please find below our response to each action items:

•	_I see lots of long functions with >150 lines of code and the code style is not consistent (I suggest running a lintr check). Similarly, in the roxygen docs, the style is not consistent. I see both ##' and #'. The indentation levels and the roxygen syntax are sometimes incorrect. Please double check._
-	Thanks for your comment! We have updated the Github repository and we have ensured the length of almost all the functions are below 150 lines of code. We have also run a lintr check and have corrected all the issues related to style inconsistencies, indentation issues and incorrect syntaxes.

•	_There isn't any unit test for the package._
-	Thanks a lot for the comment! We have now implemented the unit test of the package (available at https://github.com/daya6489/SmartEDA).

•	_Have you tried running this package on large datasets?._
-	Yes, the package works well on large datasets. Recently, we applied the SmartEDA package on the Microsoft malware prediction data in Kaggel (available at- https://www.kaggle.com/ajithvallabai/microsoft-malware-prediction/data ). This dataset was considerably large i.e. it had 8900000 rows and 82 columns. The SmartEDA package worked seamlessly on this dataset.

•	_Please make the paper more concise - I see many pages where each page only has one giant picture._
-	Thanks for the comment! We have considerably reduced the size of the paper (please refer to the updated version of the paper i.e. **10.21105.joss.01509.pdf** ) by removing a few verbose content and also by consolidating most of the images into a single figure i.e. Figure 2.

Thanks and Regards,
Sayan

**Comment by sayanddude** [comment]
@labarba Hi! As discussed, we have completed working on the comments and have updated the Github code repository along with the paper.

**Comment by labarba** [comment]
The handling editor, @mgymrek, will take it from here.

**Comment by mgymrek** [comment]
@sayanddude thanks for making these changes

@nhejazi, @terrytangyuan can you now go over the revision? If your comments have been sufficiently addressed please finish filling out the checklist

**Comment by nhejazi** [comment]
Weighing in with a few points that I think ought to be addressed as we continue the review for the `SmartEDA` package.

* Major (cannot be checked off yet)
  * __References__: I believe some of the references are missing DOIs. As an example, the paper "Exploratory data analysis of a clinical study group: Development of a procedure for exploring multidimensional data" has a DOI ( https://doi.org/10.1371/journal.pone.0201950
), available at https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0201950. Please double-check all references for DOIs and add them where missing.
  * __Community Guidelines__: While the package repository contains a `CODE_OF_CONDUCT.md` file, a "Contributions" section ought to be added to the package `README.md` (and would translate to the `pkgdown` site). It can be something simple that points to the existing `CODE_OF_CONDUCT.md` document (e.g., from a package I wrote https://github.com/nhejazi/biotmle#contributions). Similarly, a statement in the `README.md` about issues would be a welcome addition https://github.com/nhejazi/biotmle#issues.

* Minor (things that will not hold up the review):
  * __Unit tests__: it looks like you've added a number of unit tests --- thank you for addressing this concern brought up by another reviewer. From a quick look at some of these tests, they seems as though they could be better tightened. For example, there's a unit test of a plotting function that simply checks whether the produced object is, in fact, a `ggplot` object. While Visualizations can be particularly difficult to test, there are also some tests that check only that a returned summary statistic matches the values produced by a call to the corresponding base function (e.g., a call to `mean`). Over time, and as your package attracts more users, I would encourage you to write more tests.
  * __JOSS paper__: From a quick read, there are some notational/grammatical/stylistic improvements that could be made. A few examples: (1) In the first paragraph, there are two sentences where an inline reference to Tukey is intended but not used ("was coined by (J.W. Tukey)"; "was done by (J.W. Tukey)"). Note that the correct markdown syntax for such citations would simply be "@eda:1" (rather than the currently used "[@eda:1]"). (2) At the end of the introduction, you refer to R as a statistical computing package, whereas it might better be called a programming environment or language; moreover, you cite Venables & Ripley where you should cite the R core development team. (3) There are some grammatical mistakes in the paper, please re-read it to catch these --- it would be best if they were absent from the final version that gets published.

**Comment by sayanddude** [comment]
@nhejazi Thanks for the feedback! I will work on your comments and will soon get back to you with the updated paper and other required changes (hopefully, by end of next week!).

**Comment by sayanddude** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1509 with the following error: 

 Error producing PDF.
! Undefined control sequence.
l.371 environment such as R (\proglang

Looks like we failed to compile the PDF

**Comment by sayanddude** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01509/joss.01509/10.21105.joss.01509.pdf)

**Comment by sayanddude** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01509/joss.01509/10.21105.joss.01509.pdf)

**Comment by sayanddude** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01509/joss.01509/10.21105.joss.01509.pdf)

**Comment by sayanddude** [comment]
@nhejazi We have worked on addressing all of your comments. Please find below our response to each action items:

**Major (cannot be checked off yet)**

- **_References: I believe some of the references are missing DOIs. As ..........._**
Thanks for your comment! We have added the DOI for almost all the articles for which DOIs are available in the updated version of the paper. Only for the cited R packages and for the Exploratory Data Analysis book by Tukey (1977), there's no DOI available.

- **_Community Guidelines: While the package repository contains a CODE_OF_CONDUCT.md file, a "Contributions" section .........................._**
Thanks for pointing it out! We have added an "Issues" section and a "Contributions" section in the README.md file of the package (please refer to https://github.com/openjournals/joss-reviews/issues/1509). We have also added a "Contribution Guidelines" as suggested by you.

**Minor (things that will not hold up the review):**

- _**Unit tests: it looks like  .............**_
Thanks for your valuable comment! Yes, we agree that more tests can be written for testing the summary statistics. And yes, as more users start using our package we will keep writing more unit tests. In fact, we plan to write some more unit test in the next release version of the package.

- **_JOSS paper: From a quick read, there are some ................._**
Thanks for your comment! We have corrected the required markdown syntax (i.e. @eda:1). We have also cited the R core development team for "R" and have called R as a "programming environment" in text (pg. 1, paragraph 3, Introduction section) instead of "a statistical computing package" that was mentioned in the earlier version of the paper. We have also corrected some of the grammatical mistakes in the paper and have also tools such as "Grammarly" to run a check of the entire manuscript for any grammatical errors.

**Comment by sayanddude** [comment]
@mgymrek @terrytangyuan @nhejazi Hi! We have addressed all the comments mentioned above and have also made the required changes to the code repository. Kindly let us know if there's any pending action items from our end.

Thanks and Regards,
Sayan

**Comment by nhejazi** [comment]
@sayanddude Thank you for quickly addressing our concerns, including the addition of the DOIs to all references (where possible). I've gone ahead and completed the reviewer checklist available to me and am ready to recommend the software paper for acceptance into JOSS. There may yet be other concerns to address but I do think the paper and R package are close.

**Comment by sayanddude** [comment]
@nhejazi Thank you so much!

**Comment by mgymrek** [comment]
Thanks!

@sayanddude see next steps below.

Some minor comments on the paper:
* "EDA can be categorized into Descriptive statistical techniques and graphical techniques": uncapitalize descriptive
* You can reference just Figure 2 rather than spelling out (a) through (f)
* There is a reference to a Figure 9 that I believe should be to Figure 3 instead

After fixing those typos, can you please make a zenodo archive, being sure the title and author list match those on the paper, and report the DOI here?

**Comment by terrytangyuan** [comment]
@sayanddude Thanks for addressing the comments. The paper looks good to me now and I recommend for publication.

**Comment by sayanddude** [comment]
@terrytangyuan Thank you so much!

**Comment by sayanddude** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01509/joss.01509/10.21105.joss.01509.pdf)

**Comment by sayanddude** [comment]
> Thanks!
> 
> @sayanddude see next steps below.
> 
> Some minor comments on the paper:
> 
> * "EDA can be categorized into Descriptive statistical techniques and graphical techniques": uncapitalize descriptive
> * You can reference just Figure 2 rather than spelling out (a) through (f)
> * There is a reference to a Figure 9 that I believe should be to Figure 3 instead
> 
> After fixing those typos, can you please make a zenodo archive, being sure the title and author list match those on the paper, and report the DOI here?

@mgymrek Thanks for the feedback! I have corrected all the required typos in the updated version of the pdf.
Also, I have created the zenodo archive for the SmartEDA package (version 0.3.2) with DOI: 10.5281/zenodo.3383824 and the URL is: https://doi.org/10.5281/zenodo.3383824.

I have ensured that the title and the author names are same as the ones mentioned in the paper. Please let me know if I have missed out on anything. Thank you so much!

**Comment by sayanddude** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01509/joss.01509/10.21105.joss.01509.pdf)

**Comment by mgymrek** [comment]
@whedon set 10.5281/zenodo.3383824 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3383824" target="_blank">10.5281/zenodo.3383824</a> is the archive.

**Comment by mgymrek** [comment]
@whedon set 0.3.2 as version

**Comment by whedon** [comment]
OK. 0.3.2 is the version.

**Comment by mgymrek** [comment]
Thanks @sayanddude!
@openjournals/joss-eics this paper is ready to be accepted!

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/946

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/946, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1169276181427961856) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/947
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01509](https://doi.org/10.21105/joss.01509)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by sayanddude** [comment]
Thank you @mgymrek , @nhejazi and @terrytangyuan for guidance, support, and patience! It is much appreciated!

**Comment by terrytangyuan** [comment]
@arfon Should we close this issue now that the paper has been deposited?

**Comment by danielskatz** [comment]
Yes

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01509/status.svg)](https://doi.org/10.21105/joss.01509)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01509">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01509/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01509/status.svg
   :target: https://doi.org/10.21105/joss.01509
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01509/status.svg)](https://doi.org/10.21105/joss.01509)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
