### ISSUE TITLE
[PRE REVIEW]: Translational Informatics Management System (TIMS): Towards OMICS based clinical data management for long term curation of clinical studies

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1512]
**Submitting author:** @absd@bii.a-star.edu.sg (<a href="http://orcid.org/0000-0003-1247-6279">Wing-Cheong Wong</a>)
**Repository:** <a href="https://github.com/bii-absd/tims" target ="_blank">https://github.com/bii-absd/tims</a>
**Version:** v1.0
**Editor:** @csoneson
**Reviewers:** @rabdill, @andreysmelter

**Author instructions**

Thanks for submitting your paper to JOSS @absd@bii.a-star.edu.sg. The JOSS editor @lpantano, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@absd@bii.a-star.edu.sg if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lpantano it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@lpantano) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1512 with the following error: 

 Error reading bibliography ./TIMSpaper.bib (line 10, column 20):
unexpected "("
expecting letter, digit, white space, "#", "," or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
👋 @lpantano - The author suggested you as the editor - Are you able to do this?  Or can someone else from the bioinformatics team (@mgymrek, @brainstorm, @csoneson)?

**Comment by danielskatz** [comment]
👋 @absd@bii.a-star.edu.sg - there's a problem with your .bib file
line 10, now ```volume = 36(4):336-353,``` should be
```
volume = {36},
number={4},
pages={336--353},
```

you will need to make similar changes for other entries.

Once you have made these changes, enter ```@whedon generate pdf``` as a new comment in this issue, and whedon will try to generate the pdf again.

**Comment by bii-absd** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1512 with the following error: 

 Error reading bibliography ./TIMSpaper.bib (line 28, column 9):
unexpected "p"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by bii-absd** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01512/joss.01512/10.21105.joss.01512.pdf)

**Comment by bii-absd** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01512/joss.01512/10.21105.joss.01512.pdf)

**Comment by bii-absd** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01512/joss.01512/10.21105.joss.01512.pdf)

**Comment by bii-absd** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01512/joss.01512/10.21105.joss.01512.pdf)

**Comment by bii-absd** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01512/joss.01512/10.21105.joss.01512.pdf)

**Comment by bii-absd** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01512/joss.01512/10.21105.joss.01512.pdf)

**Comment by bii-absd** [comment]
Dear Editor,
The pdf article seems alright in general except for the missing captions from the figure. I have referred to the pandoc references and made several attempts to fix it but to no avail. Can you kindly advise? Many thanks

**Comment by danielskatz** [comment]
I've made a bunch of suggested edits, including attempts to fix the caption issue, in https://github.com/bii-absd/tims/pull/1

**Comment by lpantano** [comment]
sorry, I don't think I can take this one right now.

**Comment by danielskatz** [comment]
👋 bioinformatics editors (@mgymrek, @brainstorm, @csoneson) - Can someone else besides @lpantano edit this submission?

**Comment by danielskatz** [comment]
@whedon unset editor

**Comment by danielskatz** [comment]
@arfon - I feel like this should have worked, but don't think it did ...
Maybe an addition for @whedon?

**Comment by arfon** [comment]
> @arfon - I feel like this should have worked, but don't think it did ...

Yeah, Whedon doesn't know how to do this. It can only replace an editor with another one...

**Comment by danielskatz** [comment]
Can we teach Whedon this new trick?

**Comment by bii-absd** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01512/joss.01512/10.21105.joss.01512.pdf)

**Comment by bii-absd** [comment]
@danielskatz -  Greatly appreciate your fixes. The generated pdf looks good.

**Comment by danielskatz** [comment]
@bii-absd - there are clearly still some problems with the fact that the figure numbers are automatically generated, and the text references to them do not match, but this should be easy for you to fix by changing the text mentions to match the autogenerated names/numbers.

**Comment by danielskatz** [comment]
👋 bioinformatics editors (@mgymrek, @brainstorm, @csoneson) - Can someone else besides @lpantano edit this submission?

**Comment by bii-absd** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01512/joss.01512/10.21105.joss.01512.pdf)

**Comment by bii-absd** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01512/joss.01512/10.21105.joss.01512.pdf)

**Comment by bii-absd** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01512/joss.01512/10.21105.joss.01512.pdf)

**Comment by csoneson** [comment]
> 👋 bioinformatics editors (@mgymrek, @brainstorm, @csoneson) - Can someone else besides @lpantano edit this submission?
I can do it.

**Comment by bii-absd** [comment]
@danielskatz and @csoneson - Thank you.

**Comment by danielskatz** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋 @absd@bii.a-star.edu.sg - do you have suggestions for suitable reviewers for your submission (e.g. from the list linked in the first comment above)?

**Comment by bii-absd** [comment]
@csoneson - (rabdill, andreysmelter) seems suitable.

**Comment by csoneson** [comment]
👋@rabdill, @andreysmelter - would you be willing to review this submission for JOSS?

**Comment by rabdill** [comment]
@csoneson I'd be happy to.

**Comment by bii-absd** [comment]
@csoneson and @rabdill - thank you.

**Comment by andreysmelter** [comment]
Hi all!
@csoneson I am up for review as well

**Comment by bii-absd** [comment]
@andreysmelter - thank you.

**Comment by csoneson** [comment]
@whedon assign @rabdill as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rabdill

**Comment by csoneson** [comment]
@whedon add @andreysmelter as reviewer

**Comment by whedon** [comment]
OK, @andreysmelter is now a reviewer

**Comment by csoneson** [comment]
@rabdill and @andreysmelter - thank you for accepting to review this submission! I will open the review issue now.

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1533. Feel free to close this issue now!

**Comment by bii-absd** [comment]
I believe someone hit an error while trying to export data to cBioPortal 
on TIMS (we received the error email).

This error is caused by the firewall not being open for local connection 
to port 3306 (mysql) when IT open the system for public access.

The issue is resolved now, and sorry for the inconvenience caused.

**Comment by csoneson** [comment]
@bii-absd - thanks for your notice. Please post any comments in the review issue (#1533) - this pre-review issue is closed and no longer in use.
