### ISSUE TITLE
[PRE REVIEW]: traffic: a toolbox for processing and analysing air traffic data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1514]
**Submitting author:** @xoolive (<a href="http://orcid.org/0000-0002-2335-5774">Xavier Olive</a>)
**Repository:** <a href="https://github.com/xoolive/traffic" target ="_blank">https://github.com/xoolive/traffic</a>
**Version:** v2.0
**Editor:** @danielskatz
**Reviewers:** @junzis, @espinielli

**Author instructions**

Thanks for submitting your paper to JOSS @xoolive. The JOSS editor @danielskatz, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@xoolive if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @danielskatz it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@danielskatz) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01514/joss.01514/10.21105.joss.01514.pdf)

**Comment by danielskatz** [comment]
@xoolive - please review and update the bib entries - as you can see in the pdf, there are some issues.  You can wrap words or letters in {}s to preserve their case, for example. And the third reference is incomplete.  Once you have made changes in the .bib file, you can regenerate the pdf by adding a new comment in this issue with ```@whedon generate pdf```

**Comment by danielskatz** [comment]
Also, as stated above, You can help me by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by xoolive** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01514/joss.01514/10.21105.joss.01514.pdf)

**Comment by xoolive** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01514/joss.01514/10.21105.joss.01514.pdf)

**Comment by xoolive** [comment]
Thank you @danielskatz for your feedback. I identified in the list @dvysardana, @Zac-HD, @johnsamuelwrites and @sara-02 who may be interested in reviewing the submission. @junzis and @espinielli are not in the list but very likely to provide helpful insights.

**Comment by danielskatz** [comment]
👋  @junzis & @espinielli - would one of you be willing to review this submission for [JOSS](http://joss.theoj.org/about#about)?  A JOSS review involves examining the short paper and the software repository against [18 criteria](https://joss.readthedocs.io/en/latest/review_checklist.html), and explaining problems to the editor and to the author, who makes improvements in an iterative process until the submission is acceptable.

**Comment by danielskatz** [comment]
👋  @dvysardana, @Zac-HD, @johnsamuelwrites & @sara-02 - Would one or two of you also be willing to review this submission?

**Comment by junzis** [comment]
>  @junzis & @espinielli - would one of you be willing to review this submission for [JOSS](http://joss.theoj.org/about#about)? A JOSS review involves examining the short paper and the software repository against [18 criteria](https://joss.readthedocs.io/en/latest/review_checklist.html), and explaining problems to the editor and to the author, who makes improvements in an iterative process until the submission is acceptable.

@danielskatz - certainly, I would be happy to review this paper.

**Comment by danielskatz** [comment]
Thanks @junzis - I'll assign you, and once I get a second reviewer, I'll start the review.

**Comment by danielskatz** [comment]
@whedon assign @junzis as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @junzis

**Comment by espinielli** [comment]
> 
> 
> 👋 @junzis & @espinielli - would one of you be willing to review this submission for [JOSS](http://joss.theoj.org/about#about)? A JOSS review involves examining the short paper and the software repository against [18 criteria](https://joss.readthedocs.io/en/latest/review_checklist.html), and explaining problems to the editor and to the author, who makes improvements in an iterative process until the submission is acceptable.

I would be happy. What's the deadline? (leaving sooooon for a week...)

**Comment by danielskatz** [comment]
Thanks @espinielli - we try to get reviews done in a couple of weeks, so your timing should be fine

**Comment by danielskatz** [comment]
@whedon add @espinielli as reviewer

**Comment by whedon** [comment]
OK, @espinielli is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1518. Feel free to close this issue now!

**Comment by johnsamuelwrites** [comment]
I can review, if the review is still open.

> Thank you @danielskatz for your feedback. I identified in the list @dvysardana, @Zac-HD, @johnsamuelwrites and @sara-02 who may be interested in reviewing the submission. @junzis and @espinielli are not in the list but very likely to provide helpful insights.

**Comment by danielskatz** [comment]
Thanks @johnsamuelwrites but we have enough reviewers and started the review.
