### ISSUE TITLE
[PRE REVIEW]: modeLLtest: An R Package for Unbiased Model Comparison using Cross Validation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1515]
**Submitting author:** @ShanaScogin (<a href="http://orcid.org/0000-0002-7801-853X">Shana Scogin</a>)
**Repository:** <a href="https://github.com/ShanaScogin/modeLLtest" target ="_blank">https://github.com/ShanaScogin/modeLLtest</a>
**Version:** v1.0.0
**Editor:** @usethedata
**Reviewers:** @monogan, @andrewheiss

**Author instructions**

Thanks for submitting your paper to JOSS @ShanaScogin. **Currently, there isn't an JOSS editor assigned** to your paper.

@ShanaScogin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01515/joss.01515/10.21105.joss.01515.pdf)

**Comment by danielskatz** [comment]
@ShanaScogin - you might want to change your subsection headings to ```##```s. If you do this, or make other changes, you can add a new comment in this issue containing ```@whedon generate pdf``` to see how it works out

**Comment by ShanaScogin** [comment]
@danielskatz  great - will do and thanks for the help! 
@whedon generate pdf

**Comment by ShanaScogin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01515/joss.01515/10.21105.joss.01515.pdf)

**Comment by danielskatz** [comment]
👋 @usethedata - Can you edit this submission?

**Comment by usethedata** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by usethedata** [comment]
@ShanaScogin Looks interesting.  Do post back (or have volunteers post back) if you have suggestions for reviewers.

**Comment by ShanaScogin** [comment]
@usethedata Great - I have a couple emails out. I will post back when I receive responses. Thanks for editing!

**Comment by ShanaScogin** [comment]
@usethedata - @andrewheiss seems like a great fit. Would you like to check him out and assign him as a reviewer?

**Comment by usethedata** [comment]
What say you @andrewheiss are you willing and able to review this paper for JOSS?  Thanks.

**Comment by usethedata** [comment]
Also, @wrathematics @soodoku @lebebr01 @jacobsoj @mkearney -- would any of you be willing to review this paper for JOSS?  Thanks much.

**Comment by ShanaScogin** [comment]
@monogan - perhaps you'd be willing to review? Thanks for the help!

**Comment by andrewheiss** [comment]
Yep, I’d be happy to review!

**Comment by monogan** [comment]
I can review this. @usethedata, if you choose me, do I understand correctly that you'll provide me with a checklist to do the review?

**Comment by usethedata** [comment]
@whedon assign @monogan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @monogan

**Comment by usethedata** [comment]
@whedon add @andrewheiss as reviewer

**Comment by whedon** [comment]
OK, @andrewheiss is now a reviewer

**Comment by usethedata** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1542. Feel free to close this issue now!

**Comment by usethedata** [comment]
@ShanaScogin Thanks for the assistance in finding reviewers.  
@andrewheiss @monogan Thanks for agreeing to review.  There is a checklist for each of you over in the review issue ( #1542 ).  Please let me know if you have questions, either by tagging me in a post on that issue or reaching out to me directly.
