### ISSUE TITLE
[PRE REVIEW]: KinESim: Pre-equilibrium kinetic simulation of electrochemical reactions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1516]
**Submitting author:** @dap-biospec (<a href="http://orcid.org/0000-0003-4625-0323">Denis Proshlyakov</a>)
**Repository:** <a href="https://github.com/dap-biospec/KinESim" target ="_blank">https://github.com/dap-biospec/KinESim</a>
**Version:** v1.6.8g
**Editor:** @kyleniemeyer
**Reviewers:** @usethedata, @faustincarter, @cfneese

**Author instructions**

Thanks for submitting your paper to JOSS @dap-biospec. **Currently, there isn't an JOSS editor assigned** to your paper.

@dap-biospec if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1516 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: tags, date (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @kyleniemeyer - the author suggested you as the editor - ok?

**Comment by danielskatz** [comment]
👋 @dap-biospec - your paper is missing the tags and date elements - see our [sample paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography)

Once you've made changes, enter a new comment in this issue with ```@whedon generate pdf``` to rebuild the paper

**Comment by dap-biospec** [comment]
@whedon generate pdf 
paper.md has been updated with missing fields

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1516 with the following error: 

 Could not find bibliography file: KinESim.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by dap-biospec** [comment]
@whedon generate pdf
bibliography file reference corrected

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01516/joss.01516/10.21105.joss.01516.pdf)

**Comment by kyleniemeyer** [comment]
@danielskatz yes, I can handle this.

However, I noticed a few major issues immediately—for one, rather than a software package, this submission seems a set of "procedures" for the proprietary software environment [Igor Pro](https://www.wavemetrics.com). Thus, it will be challenging for us to find reviewers; I'm also not totally sure if this is in scope. 

There are also no tests, and the documentation is provided as a PDF & Word doc, with little commenting or in-code documentation.

**Comment by dap-biospec** [comment]
@kyleniemeyer
Dear Kyle,

I am new to JOSS (OSS in general) and still learning the ropes. I would be happy to provide additional documentation as needed.

As for Igor Pro, it is routinely used, along with Origin and more so than Matlab, by a sizeable proportion of scientific community in chemistry, biochemistry and related disciplines. End users in those disciplines is the primary target for the software. Our submission is a complete package that can perform simulations, processing, and reporting per user needs. It allows for an extensive customization with minimal programming skills. I am write in several languages (including C++, javascript, PHP/web) and I believe that in this case this packaged form will promote open source use and development.

We submitted demo packaged Igor experiment that can used for testing. Please let me know if there is another form of testing that is preferred. Demo also illustrates adaptation for a specific type of experimental technique or conditions.

I am looking forward to working with you to make submission compliant with the accepted standards.

Best,
Denis

**Comment by danielskatz** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
@whedon add @usethedata as editor

**Comment by kyleniemeyer** [comment]
Hi @dap-biospec, we are going to proceed with the review, since @usethedata has agreed to review the submission. Do you have any suggestions for other potential reviewers, particularly those who may be comfortable working with Igor?

**Comment by kyleniemeyer** [comment]
@whedon add @usethedata as reviewer

**Comment by whedon** [comment]
OK, @usethedata is now a reviewer

**Comment by dap-biospec** [comment]
@kyleniemeyer let me look around. I have much stronger connections in chemistry than in the software development, but I will try give you a couple of names.

**Comment by kyleniemeyer** [comment]
@dap-biospec one or two potential reviewers from your domain would be very helpful—they don't have to be software developers

**Comment by dap-biospec** [comment]
@kyleniemeyer I am working on it. Hopefully, it will expand JOSS Igor reviewers database too.

**Comment by kyleniemeyer** [comment]
@whedon add @faustincarter as reviewer

**Comment by whedon** [comment]
OK, @faustincarter is now a reviewer

**Comment by kyleniemeyer** [comment]
@dap-biospec we now have two reviewers, but I would really like to get at least one person with domain-specific knowledge, if you can suggest one or two. If you just have names/email addresses, I can reach out.

**Comment by dap-biospec** [comment]
@kyleniemeyer here are several names of potential reviewers in the scientific fields related to our manuscript.  I am not affiliated with any of them.

1) Christopher Neese: physical chemistry, chemical physics, https://electroscience.osu.edu/people/neese.6

2) Tim Causgrove:  chemistry, protein kinetics and thermodynamics http://faculty.tamucc.edu/tcausgrove/Causgrove_Home.html

3) Tony Withers: geochemistry; equilibrium and dynamics; spectroscopy; - http://www.bgi.uni-bayreuth.de/?page=4&lng=en&mode=s&id=337

**Comment by dap-biospec** [comment]
@kyleniemeyer An additional question about supplementary materials for this submission: "conventional" journals have a mechanism of submitting "for review only" materials, such as related manuscripts that did not appear in print yet. We have two submitted manuscripts that illustrate application. I think they will be valuable for reviewers to see, but cannot be uploaded to an open depository on GitHub.  I am happy to email them to you or to reviewers, or to use another mechanism if you can suggest one.

**Comment by kyleniemeyer** [comment]
@dap-biospec we do not really have a mechanism to provide review-only materials that are not publicly available, since the entire review process happens in a GitHub issue like this (once the reviewers are finalized, this issue will be closed and the review issue will be created).

Instead, I recommend that you make your submitted manuscripts available openly via a preprint server like arXiv, ChemRxiv, PeerJ Preprints, or similar.

**Comment by dap-biospec** [comment]
@kyleniemeyer - got it, thank you. Let me clear this with editors of submitted manuscripts.

**Comment by kyleniemeyer** [comment]
Update: Christopher Neese agreed to review via email. I will add him and get the review itself started shortly.

**Comment by kyleniemeyer** [comment]
@whedon add @cfneese as reviewer

**Comment by whedon** [comment]
OK, @cfneese is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1532. Feel free to close this issue now!
