### ISSUE TITLE
[REVIEW]: traffic: a toolbox for processing and analysing air traffic data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1518]
**Submitting author:** @xoolive (<a href="http://orcid.org/0000-0002-2335-5774">Xavier Olive</a>)
**Repository:** <a href="https://github.com/xoolive/traffic" target ="_blank">https://github.com/xoolive/traffic</a>
**Version:** v2.0
**Editor:** @danielskatz
**Reviewer:** @junzis, @espinielli
**Archive:** <a href="https://doi.org/10.5281/zenodo.3269812" target="_blank">10.5281/zenodo.3269812</a>

## Status

[![status](http://joss.theoj.org/papers/605f1a926656b575a6a50cc8dededb7f/status.svg)](http://joss.theoj.org/papers/605f1a926656b575a6a50cc8dededb7f)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/605f1a926656b575a6a50cc8dededb7f"><img src="http://joss.theoj.org/papers/605f1a926656b575a6a50cc8dededb7f/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/605f1a926656b575a6a50cc8dededb7f/status.svg)](http://joss.theoj.org/papers/605f1a926656b575a6a50cc8dededb7f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/xoolive/traffic" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@junzis & @espinielli, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/xoolive/traffic">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2.0)?
- [x] **Authorship:** Has the submitting author (@xoolive) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/xoolive/traffic">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2.0)?
- [x] **Authorship:** Has the submitting author (@xoolive) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @junzis, @espinielli it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01518/joss.01518/10.21105.joss.01518.pdf)

**Comment by danielskatz** [comment]
Thanks for agreeing to review @junzis & @espinielli - instructions are above, which are basically to work through your checklists.  I'lll also note here that @espinelli will be out for about a week soon.

If you have any questions, please ask.

**Comment by xoolive** [comment]
Thank you for agreeing to review @junzis and @espinielli

**Comment by espinielli** [comment]
I, too, am writing (and presenting at [UseR!2019](http://www.user2019.fr): "R in the Air") an R package for flight trajectories 😇

**Comment by junzis** [comment]
@danielskatz - Do items from the checklist "Document" section also need to be included in the paper? Thanks!

**Comment by danielskatz** [comment]
The documentation criteria is:
> There should be sufficient documentation for you, the reviewer to understand the core functionality of the software under review. A high-level overview of this documentation should be included in a README file (or equivalent). 

The paper needs are shown at the top of https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by junzis** [comment]
@xoolive - The paper, library, and document all look great! Here are my minor comments: 

1) It will be great if you can emphasize "the statement of need" in the paper. Perhaps from the perspective of ATM researcher point of view.

2) Is there already an archive version of the library on Zenodo, Figshare, or similar?  The "Archive" link in the PDF seems not working.

**Comment by xoolive** [comment]
Thank you @junzis for the feedback.

1. I will emphasize this statement of need and let you know here when ready.
2. It looks like it's all [there](https://joss.readthedocs.io/en/latest/whedon.html?highlight=zenodo#setting-the-software-archive)!
3. I am not sure it is a good idea: pyarrow and fastparquet are optional dependencies for pandas for a reason. Both have strengths and weaknesses and the decision can/should be let to the end user (Parquet format is not a must-go for the typical user of this library). From the top of my head, I think the HDF5 engine also requires optional dependencies which are useless for users like myself who almost never use the HDF5 format.
  Error messages of pandas for optional dependencies are rather explicit. It seems to me that questioning their dependency choices is out of the scope of this library.

**Comment by junzis** [comment]
@xoolive - Thanks for your clarifications. In this case, my last two comments can be ignored.

**Comment by danielskatz** [comment]
The archive link is not needed yet - we will add that at the end once any needed changes are made.  (We're discussing changing this review criteria, but haven't settled on exactly how to yet.)

**Comment by danielskatz** [comment]
👋 @espinielli - have you had a chance to start your review?

**Comment by xoolive** [comment]
@junzis Latest commit addresses your comment about the statement of need.
https://github.com/xoolive/traffic/commit/4ac5d962f4b8978cc704a7f57ca9b53910654cc9

**Comment by xoolive** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01518/joss.01518/10.21105.joss.01518.pdf)

**Comment by junzis** [comment]
@danielskatz - I have completed all the checkboxes for the review process. Finally, the paper is good and documentation is complete from my point of view. I think it can be accepted.

**Comment by danielskatz** [comment]
Thanks @junzis!

**Comment by espinielli** [comment]
> 
> 
> 👋 @espinielli - have you had a chance to start your review?

I will start, this afternoon

**Comment by espinielli** [comment]
@xoolive I am trying to install as per https://traffic-viz.github.io/installation.html
Specifically:
1. clone of the repo
1. `python setup.py install`

Last failed: I am on a Mac where python is still 2.7.0, ok, so I installed "latest" `python` (`brew install python`)
and run `python3 setup.py install` which fails with

```
...
    exec(code, globals, locals)
  File "/var/folders/bw/cfz6xpw10cs4l_1jkhyyywpw0000gn/T/easy_install-hl3fy6pw/Cartopy-0.17.0/setup.py", line 42, in <module>
    file.relative_to(sample_dir).as_posix()
ImportError: Cython 0.15.1+ is required to install cartopy.
```

(I assume Python 3 is the norm these days, hence why you did not mentioned it in the documentstion)

**Comment by espinielli** [comment]
Small suggestion for rewording in https://github.com/xoolive/traffic/issues/28
Small suggestion for reordering of text https://github.com/xoolive/traffic/issues/29

**Comment by xoolive** [comment]
Nothing stupid @espinielli, just regular Python mess 😄 

Python 3 is indeed the norm these days, and the dependency is stated [here](https://github.com/xoolive/traffic/blob/master/setup.py#L51). The installation process should fail if you have python<3.6.

There are specific non-Python dependencies for two Python libraries, namely `cartopy` and `shapely`. For Mac OS, brew is an option but you need to pay extra attention to the cross dependencies between the versions of the C libraries and of the Python libraries. Then `Cython` is indeed required to build `cartopy` but not to execute it.

If you already have a working `cartopy` and `shapely`, then installation is direct. Otherwise, as recommended [here](https://traffic-viz.github.io/installation.html), it may be better to use an anaconda distribution which installs the C libraries and the Python libraries, and also does the dependency mess for you!

**Comment by xoolive** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01518/joss.01518/10.21105.joss.01518.pdf)

**Comment by espinielli** [comment]
I have finished my review. The package and the paper are excellent.
I have filed 2 minor suggestion on the documentation which @xoolive is addressing faster than 
light speed 👍 https://github.com/xoolive/traffic/issues/30 and https://github.com/xoolive/traffic/issues/31.

IMHO they are not to be blocking issues for the paper to be accepted.

**Comment by xoolive** [comment]
Thank you @espinielli for the extensive feedback!

**Comment by danielskatz** [comment]
Thanks to @junzis & @espinielli for reviewing!

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01518/joss.01518/10.21105.joss.01518.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by danielskatz** [comment]
@xoolive - we now need you to archive the software in an archival repository, such as zenodo (see https://guides.github.com/activities/citable-code/) or elsewhere that provides a DOI - then let me know the DOI of the archive.  Also, is 2.0 still the correct version number?  If not, let me know what is.

**Comment by xoolive** [comment]
Thank you @danielskatz 

Here is the link to the DOI: https://doi.org/10.5281/zenodo.3269812 
2.0 is the correct version number

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3269812 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3269812" target="_blank">10.5281/zenodo.3269812</a> is the archive.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.ast.2018.11.031 is OK
- 10.1109/TITS.2019.2914770 is OK
- 10.21105/joss.01057 is OK
- 10.5281/zenodo.1490296 is OK

MISSING DOIs

- https://doi.org/10.1109/ipsn.2014.6846743 may be missing for title: Bringing up OpenSky: A large-scale ADS-B sensor network for research

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/818

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/818, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@xoolive - please merge https://github.com/xoolive/traffic/pull/32

**Comment by xoolive** [comment]
@danielskatz done, I am not sure now about the whedon command to type in order to generate a new final proof

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01518/joss.01518/10.21105.joss.01518.pdf)

**Comment by danielskatz** [comment]
sorry, my fix didn't quite work for the cases - let's try again - please change the line in the bib file to:
booktitle = {Proceedings of the 13th {I}nternational {S}ymposium on {I}nformation {P}rocessing in {S}ensor {N}etworks},

**Comment by xoolive** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01518/joss.01518/10.21105.joss.01518.pdf)

**Comment by xoolive** [comment]
@danielskatz this one looks good to me 😃

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1147257992385048581) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/819
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01518](https://doi.org/10.21105/joss.01518)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01518/status.svg)](https://doi.org/10.21105/joss.01518)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01518">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01518/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01518/status.svg
   :target: https://doi.org/10.21105/joss.01518
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01518/status.svg)](https://doi.org/10.21105/joss.01518)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by xoolive** [comment]
@danielskatz @espinielli @junzis 
Thank you for contributing to a smooth reviewing process. It was a nice experience to go through this process together.
