### ISSUE TITLE
[PRE REVIEW]: Tools for Prototyping with 3D Ultrasonics in ROS

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1519]
**Submitting author:** @adi3 (<a href="http://orcid.org/0000-0002-6382-8441">Adi Singh</a>)
**Repository:** <a href="https://gitlab.com/toposens/public/ros-packages" target ="_blank">https://gitlab.com/toposens/public/ros-packages</a>
**Version:** v1.1.0
**Editor:** @gkthiruvathukal
**Reviewers:** @dvberkel

**Author instructions**

Thanks for submitting your paper to JOSS @adi3. **Currently, there isn't an JOSS editor assigned** to your paper.

@adi3 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #1519 with the following error: 

 sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.01519.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
@adi3 - I don't see the software that you want to submit - it seems  like you have just submitted a paper repo.  Can I suggest that you withdraw this, and then submit the software repository, which should contain a paper.md file in a directory in that repository?  Take a look at the repositories in some of the accepted papers in http://joss.theoj.org ...

**Comment by ts-adi** [comment]
@danielskatz - Sorry, this was an oversight on my part. This is the code repository: https://gitlab.com/toposens/public/ros-packages/

I don't mind withdrawing and resubmitting the paper, but we'd like to keep the contents of the ROS code repo limited to what's relevant to the ROS framework. In doing so, we are following the precedent set by ros_control, which has been published in JOSS; they too separate their code repo (https://github.com/ros-controls/ros2_control) and their paper repo (https://github.com/ros-controls/joss_paper).

So can I resubmit the way it is currently structured?

**Comment by danielskatz** [comment]
👋 @arfon, can you help here?

**Comment by arfon** [comment]
> 👋 @arfon, can you help here?

@ts-adi - could you add the paper to a branch of the `https://gitlab.com/toposens/public/ros-packages` repository. We don't need this branch to ever be merged to `master` but it's much more convenient for the paper to be present _somewhere_ in the repository. Once the JOSS review is complete, you can simply delete that branch.

**Comment by ts-adi** [comment]
@arfon Thanks, that is a suitable solution. I've created a branch `joss_paper` in the software repository `https://gitlab.com/toposens/public/ros-packages/tree/joss_paper`.

Should I still withdraw and resubmit?

**Comment by arfon** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01519/joss.01519/10.21105.joss.01519.pdf)

**Comment by arfon** [comment]
> Should I still withdraw and resubmit?

No, I think we're OK with how it is now. @danielskatz - we'll need to compile the papers from the `joss_paper` branch.

**Comment by danielskatz** [comment]
@gkthiruvathukal - Would you be willing to edit this submission?

**Comment by gkthiruvathukal** [comment]
Yes, @danielskatz.

**Comment by danielskatz** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by danielskatz** [comment]
Note that you have to use ```@whedon generate pdf from branch joss_paper``` to generate the paper in this case...

**Comment by ts-adi** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01519/joss.01519/10.21105.joss.01519.pdf)

**Comment by ts-chris** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1519 with the following error: 

 Error producing PDF.
! LaTeX Error: File `float.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.255 \floatplacement

Looks like we failed to compile the PDF

**Comment by ts-chris** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01519/joss.01519/10.21105.joss.01519.pdf)

**Comment by ts-chris** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01519/joss.01519/10.21105.joss.01519.pdf)

**Comment by gkthiruvathukal** [comment]
@adi3 Can you help suggest a a few reviewers from [this list of people](https://bit.ly/joss-reviewers)? We now require 2 reviewers for all JOSS submissions.

**Comment by ts-adi** [comment]
@gkthiruvathukal Here are my suggestions: @trallard @carlosjoseRG @mosteo @CELavecchia @traversaro @CameronDevine @nnadeau @jizecn @Scivision @suyashkumar

Looks like not all the usernames are active or accessible, so hopefully a few from that list get a notification.

**Comment by nnadeau** [comment]
@gkthiruvathukal @ts-adi i accept :)

**Comment by gkthiruvathukal** [comment]
@whedon assign @nnadeau as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nnadeau

**Comment by dvberkel** [comment]
@gkthiruvathukal I am no robotics expert, or ultrasonic expert, but I am could review the paper

**Comment by gkthiruvathukal** [comment]
Thanks, @dvberkel. I will add you and get this review rolling.

**Comment by gkthiruvathukal** [comment]
@whedon assign @dvberkel as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dvberkel

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1531. Feel free to close this issue now!
