### ISSUE TITLE
[PRE REVIEW]: AncesTrim - a tool for trimming complex pedigrees

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#152]
**Submitting author:** @JNisk (<a href="http://orcid.org/0000-0002-2871-6890">Julia Niskanen</a>)
**Repository:** <a href="https://github.com/JNisk/AncesTrim" target ="_blank">https://github.com/JNisk/AncesTrim</a>
**Version:** v1.0
**Editor:** @mgymrek
**Reviewer:** @jyuan1322

**What this issue is for**

Thanks for submitting your paper to JOSS JNisk. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by mgymrek** [comment]
I can take this one.

**Comment by mgymrek** [comment]
@whedon assign @mgymrek as editor

**Comment by whedon** [comment]
OK, the editor is @mgymrek

**Comment by JNisk** [comment]
Dear editor,
is this review process still ongoing? It has been a while since the last activity in this topic.

Yours sincerely,
JNisk

**Comment by arfon** [comment]
:wave: @mgymrek - how are you getting on finding a reviewer for this submission?

**Comment by mgymrek** [comment]
@whedon assign @jyuan1322 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jyuan1322

**Comment by mgymrek** [comment]
Found one! Jie (@jyuan1322) has agreed to review.

**Comment by mgymrek** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by mgymrek** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/179. Feel free to close this issue now!
