### ISSUE TITLE
[PRE REVIEW]: PyCurious: A Python module for computing the Curie depth from the magnetic anomaly.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1521]
**Submitting author:** @brmather (<a href="http://orcid.org/0000-0003-3566-1557">Ben Mather</a>)
**Repository:** <a href="https://github.com/brmather/pycurious" target ="_blank">https://github.com/brmather/pycurious</a>
**Version:** 0.4
**Editor:** @lheagy
**Reviewers:** @santisoler

**Author instructions**

Thanks for submitting your paper to JOSS @brmather. **Currently, there isn't an JOSS editor assigned** to your paper.

@brmather if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1521 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:123:in `block in check_orcids': Problem with ORCID (0000-0000-0000-0000) for Robert Delhaye (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:121:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:121:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:81:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
Hi @lheagy, the author suggested you to edit this submission; can you handle this one?

**Comment by kyleniemeyer** [comment]
Hi @brmather, thanks for your submission. We will get this assigned to an editor, who will use this pre-review issue for reviewer assignment.

For your paper, if your coauthor does not have an ORCID, then please just remove that field (rather than use `0000-0000-0000-0000`.

**Comment by brmather** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by brmather** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1029/2009JB006494 is OK
- 10.1016/S0040-1951(99)00072-4 is OK
- 10.7289/V5H70CVX is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by brmather** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01521/joss.01521/10.21105.joss.01521.pdf)

**Comment by brmather** [comment]
@kyleniemeyer thank you for handling the submission. I have removed @rdelhaye ORCID and the PDF has been successfully generated.

I recommend the following two reviewers for our submission:

- Santiago Soler (github:santisoler)
- Claire Bouligand Claire.Bouligand@univ-grenoble-alpes.fr 

Please let me know if you would like more suggestions.

Kind regards,
Ben

**Comment by lheagy** [comment]
Happy to @kyleniemeyer!

**Comment by lheagy** [comment]
@whedon assign @lheagy as editor

**Comment by whedon** [comment]
OK, the editor is @lheagy

**Comment by lheagy** [comment]
:wave: @fourndo, @santisoler, would you be willing to review this submission for JOSS (Journal of Open Source Software)? With both of your experience in Magnetic methods, I would very much appreciate your input! 

If you haven't reviewed with JOSS before, the review process is a bit different. We focus on the software, and provide a checklist to help guide the review (more info in the [reviewer guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)). 

If you don't have the time at the moment, I would appreciate any recommendations you have. Thanks!

**Comment by santisoler** [comment]
Hi @lheagy and @brmather! I'll be glad to review `pycurious`.
I'll try to start opening issues for the end of next week. Please be patient while I read through the submitted paper and explore the repository.

**Comment by lheagy** [comment]
Excellent, thanks @santisoler!!

**Comment by lheagy** [comment]
@whedon assign @santisoler as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @santisoler

**Comment by lheagy** [comment]
Just a quick update on a second reviewer: I have sent an email to Claire and am waiting to hear back. I will keep you posted. @santisoler: if you would like to get going on the checklist right away, please let me know and I can start the review. Otherwise I will hopefully find a second reviewer and we can start the process then.

**Comment by santisoler** [comment]
@lheagy I'm not planning to get into the review until the end of next week, so there's no rush to start it. But if you want to make my checklist available right away so you don't have to remember to do it in the future, go ahead.

**Comment by lheagy** [comment]
I will start the review and keep looking for a second reviewer so that you can start at your convenience @santisoler

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1544. Feel free to close this issue now!

**Comment by lheagy** [comment]
:wave: @jessepisel, would you be willing to review this submission for JOSS? 

If you haven't reviewed with JOSS before, the review process is a bit different. We focus on the software, and provide a checklist to help guide the review (more info in the reviewer guidelines).

If you don't have the time at the moment, I would appreciate any recommendations you have. Thanks!

**Comment by jessepisel** [comment]
Howdy @lheagy I would be happy to review this submission for JOSS. I haven't reviewed with JOSS yet so I will go through the reviewer guidelines and checklist and get started in the next couple of days.

**Comment by lheagy** [comment]
Excellent, many thanks @jessepisel! The review issue is started over in #1544. I will add a checklist for you there. In order to be able to check off items, please accept the invitation to JOSS: https://github.com/openjournals/joss-reviews/invitations. Note that you will likely want to "unwatch" the repo so that you don't get swamped with all of the review activity!
