### ISSUE TITLE
[PRE REVIEW]: Singularity Compose: Orchestration for Singularity Instances

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1522]
**Submitting author:** @vsoch (<a href="http://orcid.org/0000-0002-4387-3819">Vanessa Sochat</a>)
**Repository:** <a href="https://github.com/singularityhub/singularity-compose" target ="_blank">https://github.com/singularityhub/singularity-compose</a>
**Version:** 0.0.15
**Editor:** @gkthiruvathukal
**Reviewers:** @daissi

**Author instructions**

Thanks for submitting your paper to JOSS @vsoch. **Currently, there isn't an JOSS editor assigned** to your paper.

@vsoch if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01522/joss.01522/10.21105.joss.01522.pdf)

**Comment by kyleniemeyer** [comment]
Hi @vsoch, thanks for your submission. At first glance, while this looks like valuable software, I don't see anything that indicates that it is *research* software—nothing in the README or paper seems to connect it to research. Could you clarify how it has an obvious research application?

**Comment by vsoch** [comment]
Think of any kind of research application that involves a database (mongodb, postgres, etc.) along with an application to interact with it. For example, Singularity Compose is going to fit in nicely with being used on our SLURM cluster to start a database on a node for a researcher's (containerized) scripts to interact with. A second example is with respect to interactive applications. I'm not a huge fan, but jupyter notebooks (and similar) and becoming more popular, and tools like OnDemand (Ohio Supercomputing Center) now allow for running rstudio/jupyter via a Singularity container.  An integration with Singularity compose would allow for a user to do similar, but with the interactive applications and services that are relevant for their work.

The use cases are strong with this one, and there is no tool that can provide what I outlined above. It is niche as it's for Singularity containers, however they are the unit of reproducible operability on HPC. You are correct that it's a general purpose tool, and not something like a package for a specific scientific domain. But the reasons that I outlined above, and what can be developed for research with such a tool, are exactly what makes it so exciting. I've been waiting years (since 2016) to develop this, and the base unit (Singularity) is finally ready to support it.

**Comment by vsoch** [comment]
And of course reproducibility of all of the above - given that I run my specific database service + application, by placing the singularity-compose.yml alongside the version controlled code and container recipes, this ensures not just reproducibility of the container build, but also deployment of the services to do some analysis. I believe I stated this in the paper. :)

**Comment by vsoch** [comment]
@kyleniemeyer please let me know if you have other questions, or if you'd like me to suggest reviewers (those with experience with reproducibility and/or container technologies would be well suited!)

**Comment by vsoch** [comment]
oh that's so cool! @whedon extracts labels now! You're the best robot, @whedon  <3

**Comment by kyleniemeyer** [comment]
@vsoch great, thank you for the information. I do think that both the README and JOSS paper need to emphasize the research application a bit more, so it's clear, but that can happen through the review process.

**Comment by kyleniemeyer** [comment]
@gkthiruvathukal can you take on this submission? otherwise, @danielskatz also looks like a good fit.

**Comment by gkthiruvathukal** [comment]
@kyleniemeyer I think I can.  I have a few reviews nearing completion so I should be fine with it.

**Comment by kyleniemeyer** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
@vsoch Can you help suggest a a few reviewers from [this list of people](https://bit.ly/joss-reviewers)? We now require 2 reviewers for all JOSS submissions.

**Comment by vsoch** [comment]
Sure thing! It looks like @nuest is the only other one that lists containers, so he might be familiar with Docker Compose (Singularity Compose's counterpart). The next tag that might imply container experience would be reproducibility, and from that I can suggest @cole-brokamp and @daissi.

**Comment by gkthiruvathukal** [comment]
@nuest, @cole-brokamp, @daissi: Would you be willing to contribute a review for this JOSS submission? I need two reviewers to begin review.

**Comment by cole-brokamp** [comment]
I am out traveling for the next three weeks, but would be glad to take a look when I get back.

**Comment by gkthiruvathukal** [comment]
@cole-brokamp this works for me. Could you wrap up your review a week or two after travel?

**Comment by vsoch** [comment]
Works for me too! Safe travels @cole-brokamp :airplane:

**Comment by cole-brokamp** [comment]
Sure, sounds good!

**Comment by daissi** [comment]
Unfortunately, I will not be available to do it before September. It should be better to find someone else, but if nobody appears until September, I will be happy to review this one.

**Comment by gkthiruvathukal** [comment]
@daissi I'm going to go ahead and add you for now so I can get started. Given that this is summer and many people are busy, I'm noticing that many reviews are taking longer. You'l be the second reviewer with @cole-brokamp, who is also on some travel.

**Comment by gkthiruvathukal** [comment]
@whedon assign @cole-brokamp as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @cole-brokamp

**Comment by gkthiruvathukal** [comment]
@whedon assign @daissi as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @daissi

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1578. Feel free to close this issue now!
