### ISSUE TITLE
[PRE REVIEW]: Agents.jl: agent-based modeling framework in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1527]
**Submitting author:** @kavir1698 (<a href="http://orcid.org/0000-0003-0895-1495">Ali Rezaee Vahdati</a>)
**Repository:** <a href="https://github.com/kavir1698/Agents.jl" target ="_blank">https://github.com/kavir1698/Agents.jl</a>
**Version:** v1.1.2
**Editor:** @jedbrown
**Reviewers:** @Datseris

**Author instructions**

Thanks for submitting your paper to JOSS @kavir1698. **Currently, there isn't an JOSS editor assigned** to your paper.

@kavir1698 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01527/joss.01527/10.21105.joss.01527.pdf)

**Comment by kyleniemeyer** [comment]
Hi @Kevin-Mattheus-Moerman or @jedbrown, could one of you edit this submission?

**Comment by kavir1698** [comment]
Hi,
From the provided list of potential reviewers, I suggest the following reviewers:

* ajgates42@gmail.com
* erahulkulkarni@gmail.com
* amin.sadeghi@mail.mcgill.ca

**Comment by kyleniemeyer** [comment]
Hi @jedbrown, based on editor load and area I'm going to assign this one to you. Thanks!

**Comment by kyleniemeyer** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by jedbrown** [comment]
@kavir1698 Thanks for your submission. I see a few things that should be corrected before starting the review.
1. There are some syntactic issues with the references in the paper, e.g., `@[key]` should be `[@key]`. There is no need to cite your own repository; it already appears in the margin decoration.
2. The paper is very short and would benefit from some greater explanation of features, perhaps a performance comparison or brief example to help a prospective user determine whether Agents.jl will meet their needs.
3. It looks like Travis-CI is used only to build documentation. Can you make it run the automated test suite? In any case, please document how to run the test suite.
4. Please add CONTRIBUTING.md and address [Community Guidelines](https://joss.readthedocs.io/en/latest/review_checklist.html).
5. This software claims performance as a feature so the docs should define a comparison and enable users to replicate it. In most cases, the paper should summarize such results.

**Comment by kavir1698** [comment]
Thank you, @jedbrown, for your suggestions. I have now addressed your comments. How should I resubmit?

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01527/joss.01527/10.21105.joss.01527.pdf)

**Comment by jedbrown** [comment]
@fdroessler @Nick-gauthier @Adrianzo @Datseris :wave: This submission looks like it may be relevant to your interests; would you be available to review?

**Comment by Datseris** [comment]
Hi, yes I'd be happy to review @jedbrown . This seems very interesting for me, and I didn't know if its existence before now.

**Comment by Datseris** [comment]
@jedbrown I am currently on vacation and I have some free spare time. Is it possible for me to start the review process now, or in the next couple of days? Because after my vacation I will not be able to do the review (too busy with PhD defense).

**Comment by Datseris** [comment]
@jedbrown I want to be sure there isn't any conflict of interest here. @kavir1698 has agreed to join us in JuliaDynamics, a GitHub organization that I am part of. In this process I will do some contributions to the repo under review here. But, since the rules of JOSS state that I can't review a repo that I contribute to, I will do this _after_ the current review process is done. 

is this okay?

**Comment by jedbrown** [comment]
@Datseris Yes, I can start the review now. (I've been working to track down another reviewer, but can add them later since you're ready to get started.) Thanks for disclosing this potential CoI -- I don't consider plans to collaborate to be problematic for the review.

**Comment by jedbrown** [comment]
@whedon add @Datseris as reviewer

**Comment by whedon** [comment]
OK, @Datseris is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1611. Feel free to close this issue now!
