### ISSUE TITLE
[PRE REVIEW]: RETS-Manager: A platform for fetching and syncing real estate data and images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1528]
**Submitting author:** @issamhammad (<a href="http://orcid.org/0000-0002-1895-3438">Issam Hammad</a>)
**Repository:** <a href="https://github.com/issamhammad/RETS-Manager" target ="_blank">https://github.com/issamhammad/RETS-Manager</a>
**Version:** V1.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @issamhammad. **Currently, there isn't an JOSS editor assigned** to your paper.

@issamhammad if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01528/joss.01528/10.21105.joss.01528.pdf)

**Comment by kyleniemeyer** [comment]
Hello @issamhammad, thank you for your interest in JOSS. The editorial board discussed your submission, and as currently framed we do not consider this submission research software and thus does not fall within our scope. We recognize it may be useful, and possibly for research, but it isn't currently framed that way. If you can demonstrate the research utility—possibly by connecting it to current or published research projects/papers—and write documentation more targeted at researchers, then we may consider a resubmission in the future.
