### ISSUE TITLE
[PRE REVIEW]: phymcmc: A wrapper for emcee providing convenient functions and scripts

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1529]
**Submitting author:** @cbeauc (<a href="http://orcid.org/0000-0003-0599-0069">Catherine Beauchemin</a>)
**Repository:** <a href="https://github.com/cbeauc/phymcmc" target ="_blank">https://github.com/cbeauc/phymcmc</a>
**Version:** v0.4
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @cbeauc. **Currently, there isn't an JOSS editor assigned** to your paper.

@cbeauc if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01529/joss.01529/10.21105.joss.01529.pdf)

**Comment by cbeauc** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by cbeauc** [comment]
Possible reviewers: @tacaswell @dfm @glemaitre @nnadeau @Jgoldfar @a-slide @lowandrew @tleonardi @gavinmdouglas

**Comment by gavinmdouglas** [comment]
This looks like a very useful software, but sorry I have to decline being a reviewer since I don't have the expertise to evaluate it.

**Comment by tacaswell** [comment]
I can do this, but likely not until after scipy (late July).

**Comment by kyleniemeyer** [comment]
Hello @cbeauc, thank you for your interest in JOSS. The editorial board discussed your submission, and in our view, your submission appears to be more of a wrapper/minor utility rather than research software in its own right. Thus, while it may be useful, it would not be within scope for JOSS. The relevant qualification for us is:
> The software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better.
