### ISSUE TITLE
[REVIEW]: bioLEC: A Python package to measure Landscape Elevational Connectivity

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1530]
**Submitting author:** @tristan-salles (<a href="http://orcid.org/0000-0001-6095-7689">Tristan Salles</a>)
**Repository:** <a href="https://github.com/Geodels/bioLEC" target ="_blank">https://github.com/Geodels/bioLEC</a>
**Version:** 1.0.0
**Editor:** @kthyng
**Reviewer:** @kbarnhart, @hugoledoux 
**Archive:** <a href="https://doi.org/10.5281/zenodo.3348340" target="_blank">10.5281/zenodo.3348340</a>

## Status

[![status](http://joss.theoj.org/papers/c0f33df56ab66222b389d4eb85bc60a7/status.svg)](http://joss.theoj.org/papers/c0f33df56ab66222b389d4eb85bc60a7)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/c0f33df56ab66222b389d4eb85bc60a7"><img src="http://joss.theoj.org/papers/c0f33df56ab66222b389d4eb85bc60a7/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/c0f33df56ab66222b389d4eb85bc60a7/status.svg)](http://joss.theoj.org/papers/c0f33df56ab66222b389d4eb85bc60a7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Geodels/bioLEC" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kbarnhart & @hugoledoux , please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Geodels/bioLEC">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** 1.0.0
- [x] **Authorship:** Has the submitting author (@tristan-salles) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Geodels/bioLEC">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.0.0
- [x] **Authorship:** Has the submitting author (@tristan-salles) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kbarnhart, @hugoledoux  it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01530/joss.01530/10.21105.joss.01530.pdf)

**Comment by tristan-salles** [comment]
Checked!

**Comment by kbarnhart** [comment]
Reviewer update:

I've done a full pass at a review and was very pleased with the package. I think that bioLEC is a great contribution to topographic analysis and an appropriate contribution to JOSS. 

I've made all of my comments as Issues. The three unchecked boxes in my checklist all correspond to items identified in issues. I will check them off as they are addressed. 

I have only tested the developer and pip installs. I will not be able to test the Docker install or run the code on an HPCC. I was not 100% successful at running the notebooks locally or on Binder (both cases due to issues with `lavavu` indicated in the Issues made in the main repository.

**Comment by tristan-salles** [comment]
Thanks, @kbarnhart for the really useful review, I have been updating the code and documentation to account for the comments and improvements that were proposed.

**Comment by kthyng** [comment]
thanks @kbarnhart!

@hugoledoux Just a friendly reminder about your JOSS review.

**Comment by kbarnhart** [comment]
@tristan-salles glad the review was helpful. 

@kthyng I've completed my review and am happy to indicate that I think the contribution should be published in JOSS. I have left only one checkbox un-checked (related to versioning). As @tristan-salles indicated in [bioLEC Issue 1](https://github.com/Geodels/bioLEC/issues/1) the version will be tagged at the end of the JOSS review process.

**Comment by tristan-salles** [comment]
Thanks again @kbarnhart !

**Comment by kthyng** [comment]
@hugoledoux Want to check in again. If you know when you can work on this review, I will wait to ping you again until after that time. Thanks!

**Comment by hugoledoux** [comment]
I can do this this week.

**Comment by hugoledoux** [comment]
I clicked above what is working, and left some blanks, these are linked to the comments below.

## version
the github page doesn't have an official release (nor tags!).

## installation
the first install returned an error because I didn't have numpy installed, I needed to install it myself. You should install it as a dependencies (other packages were installed automatically). I see now it's in the `requirements.txt` file...hmmmm... Python packaging is messy, not sure why this happened.

## unit tests
Is it all in file `/src/tests/testInstall.py`? This works and all tests are fine, but is it enough?

## examples?
Perhaps putting a folder with a few terrains and one example file would be a good idea?

**Comment by tristan-salles** [comment]
Thanks for the review @hugoledoux !!! 

## version

I was waiting for the end of the JOSS review process before creating the **bioLEC** version. This is now done and its tagged as [ **v1.0.0**](https://github.com/Geodels/bioLEC/releases/tag/v1.0.0) to match the Python package version.


## installation

Hum.. this is weird, I did try a clean install and it worked fine but I have seen a few posts on google suggesting to put the complete version number such as `numpy>=1.15.0` instead of only `numpy>=1.15` and to make sure that the version number between `requirements.txt` and `setup.py` were matching... I have modified both files accordingly, just in case it clears the dependency issue you've experienced...

## unit tests

the `testInstall.py` is where the unit test is done. I agree this is a simple test but it actually: 
1. returns any library installation problem,  
2. runs all the functions via the `test flag` in the `LEC.py` file and 
3. checks the obtained results for a given topography against the expected ones. 

## examples?

First it is worth mentioning that the third jupyter notebook `bioLEC3-MeshGen` explains how to generate terrains from standard ARCGIS like format and `bioLEC1-genericCase` shows how to use 2D numpy arrays as input for `bioLEC`. But I agree with @hugoledoux, additional examples are a good idea and I have added 2 additional terrains to test for the user :
+ `dataset/pyrenees.csv`
+ `dataset/afghan.csv`

I have updated the `bioLEC2-Kosciuszko` jupyter notebook to add the link to these new topographic files. I think we need to make sure the package size is not too big in size and I believe having 3 different terrains might be enough.

**Comment by hugoledoux** [comment]
All is good, I've clicked them all above 👍🏽

Two small caveats:
1. I wouldn't use "ArcGIS formats", mostly because that's a for-profit company and this is not accurate (unless you support only ArcGIS...). Your third jupyter book speaks of "GeoTIFF", which I much prefer personally!
2. The main link to the mybinder.org only has links to only 2 notebooks, but one can see it in the `notebooks`.

**Comment by tristan-salles** [comment]
Thanks, I have updated the binder notebook links

**Comment by kthyng** [comment]
Awesome looks like everything is wrapped up! I have a few steps to do on my end now.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01530/joss.01530/10.21105.joss.01530.pdf)

**Comment by kthyng** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1073/pnas.1518922113 is OK
- 10.1098/rstb.2011.0065 is OK
- 10.5194/esurf-5-369-2017 is OK
- 10.1038/nclimate2656 is OK
- 10.1007/s40823-016-0006-9 is OK
- 10.1038/ngeo1742 is OK
- 10.1126/science.aaf2201 is OK
- 10.1371/journal.pone.0195557 is OK
- 10.7717/peerj.453 is OK
- 10.1111/j.1096-3642.1860.tb00090.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
Ok @tristan-salles now's the time to make a Zenodo archive, and report the DOI in the review thread.

**Comment by tristan-salles** [comment]
Here it comes!

[![DOI](https://zenodo.org/badge/185154268.svg)](https://zenodo.org/badge/latestdoi/185154268)

Thanks...

**Comment by kthyng** [comment]
Great! Please go to your Zenodo deposit and correct the metadata (check both title and author list).

**Comment by tristan-salles** [comment]
sorry didn't check it... I've updated it now.

[![DOI](https://zenodo.org/badge/185154268.svg)](https://zenodo.org/badge/latestdoi/185154268)

**Comment by kthyng** [comment]
Great! No problem.

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.3348340 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3348340" target="_blank">10.5281/zenodo.3348340</a> is the archive.

**Comment by kthyng** [comment]
@whedon set 1.0.0 as version

**Comment by whedon** [comment]
OK. 1.0.0 is the version.

**Comment by kthyng** [comment]
@openjournals/joss-eics This paper is ready to be taken over! Should be all ready for you!

congrats @tristan-salles and thanks @kbarnhart and @hugoledoux!!

**Comment by tristan-salles** [comment]
Thanks all !!!

**Comment by kyleniemeyer** [comment]
Hi @tristan-salles, please merge the PRs I just submitted that fix a few things in the paper: https://github.com/Geodels/bioLEC/pull/11 and https://github.com/Geodels/bioLEC/pull/10, then we'll be good to go.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01530/joss.01530/10.21105.joss.01530.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/856

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/856, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by tristan-salles** [comment]
checked!

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1154241969310380032) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/857
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01530](https://doi.org/10.21105/joss.01530)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats on your submission's publication in JOSS @tristan-salles!

Many thanks to @kbarnhart and @hugoledoux for reviewing, and @kthyng for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01530/status.svg)](https://doi.org/10.21105/joss.01530)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01530">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01530/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01530/status.svg
   :target: https://doi.org/10.21105/joss.01530
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01530/status.svg)](https://doi.org/10.21105/joss.01530)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
