### ISSUE TITLE
[PRE REVIEW]: Blimpy: Breakthrough Listen I/O Methods for Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1534]
**Submitting author:** @telegraphic (<a href="http://orcid.org/0000-0003-2783-1608">Danny Price</a>)
**Repository:** <a href="https://github.com/UCBerkeleySETI/blimpy" target ="_blank">https://github.com/UCBerkeleySETI/blimpy</a>
**Version:** 1.3.6
**Editor:** @xuanxu
**Reviewers:** @garrettj403, @zhampel

**Author instructions**

Thanks for submitting your paper to JOSS @telegraphic. **Currently, there isn't an JOSS editor assigned** to your paper.

@telegraphic if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1534 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
Hi @xuanxu, this submission looks right up your alley. Can you edit?

**Comment by kyleniemeyer** [comment]
Hey @arfon, I see `paper.md` and `paper.bib` right at the top level of the repo, any idea why whedon doesn't see those?

**Comment by kyleniemeyer** [comment]
Hi @telegraphic, thanks for your submission. While we get things initiated here, I noticed that your article is quite short; although we don't publish full-length papers here, we do expect 250-1000 words (one or two pages in PDF format is typical). Can you expand on your software a bit more, for example talking about features, infrastructure, etc., or even giving one or two examples?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01534/joss.01534/10.21105.joss.01534.pdf)

**Comment by xuanxu** [comment]
> Hi @xuanxu, this submission looks right up your alley. Can you edit?

@kyleniemeyer yes, I can edit this

**Comment by xuanxu** [comment]
@whedon assign @xuanxu as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by telegraphic** [comment]
Hi @kyleniemeyer -- happy to expand on the software, will add a few paragraphs

**Comment by xuanxu** [comment]
:wave: @garrettj403 and @dhuppenkothen: Would you be willing to review this paper? I think your expertise in Python and Jupyter notebooks and your background on Astronomy/Radioastronomy makes both of you a great fit for this submission.

**Comment by dhuppenkothen** [comment]
@xuanxu Unfortunately I'm going to be travelling/teaching/organizing at a school for the next few weeks, so I don't think I can do this on a timescale earlier than about a month from now. I'm really sorry!

**Comment by garrettj403** [comment]
Hi @xuanxu, I'm happy to review this repo. I'm not very familiar with SETI or the Breakthrough Listen program, but it looks like an interesting project!

**Comment by xuanxu** [comment]
Thanks for agreeing to review @garrettj403, I will assign you now.
I'll start the review issue once I find the second reviewer. Stay tuned.

**Comment by xuanxu** [comment]
@whedon assign @garrettj403 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @garrettj403

**Comment by xuanxu** [comment]
:wave: @benjaminrose — would you be willing to contribute a review for JOSS on this submission?

**Comment by garrettj403** [comment]
Hi @telegraphic - In case you didn't know this, ApJ has an agreement with JOSS where you can submit two papers in parallel: one to JOSS and one to ApJ. You can find more info here: [https://iopscience.iop.org/article/10.3847/1538-4357/aaf876](url)

**Comment by telegraphic** [comment]
Thanks @garrettj403 for bringing that to my attention!

**Comment by xuanxu** [comment]
:wave: @zhampel — would you be willing to contribute a review for JOSS on this submission?

**Comment by zhampel** [comment]
@xuanxu Yes I can provide a review for this submission.

**Comment by xuanxu** [comment]
Great, thanks @zhampel
I'm going to move this forward to review

**Comment by xuanxu** [comment]
@whedon add @zhampel as reviewer

**Comment by whedon** [comment]
OK, @zhampel is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1554. Feel free to close this issue now!

**Comment by xuanxu** [comment]
@garrettj403, @zhampel - please head over to #1554 where the review will take place.
