### ISSUE TITLE
[PRE REVIEW]: Sourcepredict: Prediction of metagenomic sample sources using dimension reduction followed by machine learning classification

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1535]
**Submitting author:** @maxibor (<a href="http://orcid.org/0000-0001-9140-7559">Maxime Borry</a>)
**Repository:** <a href="https://github.com/maxibor/sourcepredict" target ="_blank">https://github.com/maxibor/sourcepredict</a>
**Version:** v0.33
**Editor:** @lpantano
**Reviewers:** @gavinmdouglas, @giraola

**Author instructions**

Thanks for submitting your paper to JOSS @maxibor. **Currently, there isn't an JOSS editor assigned** to your paper.

@maxibor if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01535/joss.01535/10.21105.joss.01535.pdf)

**Comment by kyleniemeyer** [comment]
Hi @mgymrek or @lpantano, can one of you edit this submission?

**Comment by lpantano** [comment]
I can take this one. Thanks

**Comment by maxibor** [comment]
Maybe @gavinmdouglas or @giraola could be good reviewers for this article ?

**Comment by kyleniemeyer** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by gavinmdouglas** [comment]
I'm interested in reviewing this article.

**Comment by lpantano** [comment]
@gavinmdouglas, thank you!

**Comment by lpantano** [comment]
@whedon assign @gavinmdouglas as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @gavinmdouglas

**Comment by lpantano** [comment]
that would be awesome @giraola

**Comment by lpantano** [comment]
@whedon add @giraola as reviewer

**Comment by whedon** [comment]
OK, @giraola is now a reviewer

**Comment by lpantano** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1186/gb-2014-15-3-r46 is OK
- 10.7717/peerj.4600 is OK
- 10.1038/455481a is OK
- 10.1093/molbev/msw046 is OK
- 10.1128/AEM.01996-06 is OK
- 10.1038/nmeth.1650 is OK
- 10.2307/1942268 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1540. Feel free to close this issue now!
