### ISSUE TITLE
[PRE REVIEW]: SeleDiff: A fast and scalable tool for estimating and testing selection differences between populations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1536]
**Submitting author:** @xin-huang (<a href="http://orcid.org/0000-0002-9918-9602">Xin Huang</a>)
**Repository:** <a href="https://github.com/xin-huang/SeleDiff" target ="_blank">https://github.com/xin-huang/SeleDiff</a>
**Version:** v.1.0.0
**Editor:** @lpantano
**Reviewers:** @stulacy, @suresh-lab

**Author instructions**

Thanks for submitting your paper to JOSS @xin-huang. **Currently, there isn't an JOSS editor assigned** to your paper.

@xin-huang if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1536 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
Hi @mgymrek and @lpantano, can one of you take this? (Perhaps one of you can take this submission and the other can take #1535...)

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1536 with the following error: 

 Error reading bibliography ./paper.bib (line 5, column 5):
unexpected "Y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by xin-huang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1536 with the following error: 

 Error producing PDF.
! Missing delimiter (. inserted).
<to be read again> 
                   {
l.373 \[\text{median}\left{

Looks like we failed to compile the PDF

**Comment by xin-huang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01536/joss.01536/10.21105.joss.01536.pdf)

**Comment by xin-huang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by xin-huang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01536/joss.01536/10.21105.joss.01536.pdf)

**Comment by xin-huang** [comment]
Potential reviewers could be @stulacy and @Suresh-lab

**Comment by suresh-lab** [comment]
Happy help!

**Comment by stulacy** [comment]
Also happy to review!

**Comment by kyleniemeyer** [comment]
Great, thanks to you both @stulacy and @suresh-lab! I will add you as reviewers, but we are still waiting to get an editor assigned to handle the submission and start the review.

**Comment by kyleniemeyer** [comment]
@whedon add @stulacy as reviewer

**Comment by kyleniemeyer** [comment]
@whedon add @suresh-lab as reviewer

**Comment by kyleniemeyer** [comment]
Hi @mgymrek, just another ping about handling this submission—we already have two reviewers ready to go!

**Comment by xin-huang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01536/joss.01536/10.21105.joss.01536.pdf)

**Comment by lpantano** [comment]
well, I can do it  as well if there is already two reviewers :)

**Comment by kyleniemeyer** [comment]
@lpantano sounds good, thanks! 😀

**Comment by danielskatz** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by danielskatz** [comment]
👋 @lpantano - btw, you can assign yourself as editor too (via whedon), once you volunteer :)

**Comment by lpantano** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/ece3.1261 is OK
- 10.1073/pnas.1019276108 is OK
- 10.1093/molbev/msw211 is OK
- 10.1101/gr.192336.115 is OK
- 10.1093/molbev/msu211 is OK
- 10.1111/mec.13559 is OK
- 10.1146/annurev-genet-111212-133526 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1545. Feel free to close this issue now!
