### ISSUE TITLE
[PRE REVIEW]: bayestestR: Describing Effects and their Uncertainty, Existence and Significance within the Bayesian Framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1537]
**Submitting author:** @DominiqueMakowski (<a href="http://orcid.org/0000-0001-5375-9967">Dominique Makowski</a>)
**Repository:** <a href="https://github.com/easystats/bayestestR" target ="_blank">https://github.com/easystats/bayestestR</a>
**Version:** v0.2.3
**Editor:** @cMadan
**Reviewers:** @paul-buerkner, @tjmahr

**Author instructions**

Thanks for submitting your paper to JOSS @DominiqueMakowski. **Currently, there isn't an JOSS editor assigned** to your paper.

@DominiqueMakowski if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1537 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
Hi @karthik, can you take this submission?

**Comment by karthik** [comment]
@kyleniemeyer Unfortunately I'm taking a much needed hiatus on handling new submissions till September.

**Comment by kyleniemeyer** [comment]
@karthik got it!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01537/joss.01537/10.21105.joss.01537.pdf)

**Comment by kyleniemeyer** [comment]
Hi @cMadan, can you handle this submission? I see quite a few psychology-related references/applications here.

**Comment by DominiqueMakowski** [comment]
Potential reviewers that could be interested include @paul-buerkner and @tjmahr ☺️

**Comment by tjmahr** [comment]
I can review it. (I have done one review in the past for ROpenSci.)

**Comment by paul-buerkner** [comment]
It is a rather short article, right? I think I should be able to review it. Are there any reviewing guidelines?

**Comment by strengejacke** [comment]
@paul-buerkner 

Guidelines are described here: https://joss.readthedocs.io/en/latest/review_criteria.html
The review will be in a GitHub repo, where reviewers have this checklist:
https://joss.readthedocs.io/en/latest/review_checklist.html

You can glance at the compiled PDF here:
https://github.com/openjournals/joss-papers/blob/joss.01537/joss.01537/10.21105.joss.01537.pdf

But it's not only the review of the paper, but also of the GitHub-repository, as you have a checklist for both the paper and the repo.

**Comment by paul-buerkner** [comment]
Great, thanks! I am happy to review this paper then.

**Comment by kyleniemeyer** [comment]
Thanks to both of @paul-buerkner and @tjmahr for volunteering so quickly! I'll assign you now, but we are still waiting to get an editor assigned to handle the submission, who will actually start the review.

**Comment by kyleniemeyer** [comment]
@whedon add @paul-buerkner as reviewer

**Comment by kyleniemeyer** [comment]
@whedon add @tjmahr as reviewer

**Comment by cMadan** [comment]
@kyleniemeyer @DominiqueMakowski, sure I can serve as editor here.

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1541. Feel free to close this issue now!
