### ISSUE TITLE
[PRE REVIEW]: bíogo: a simple high-performance bioinformatics toolkit for the Go language

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#154]
**Submitting author:** @kortschak (<a href="http://orcid.org/0000-0001-8295-2301">Robert Daniel Kortschak</a>)
**Repository:** <a href="https://github.com/biogo/biogo" target ="_blank">https://github.com/biogo/biogo</a>
**Version:** v1.0.0
**Editor:** @pjotrp
**Reviewer:** @brentp

**What this issue is for**

Thanks for submitting your paper to JOSS kortschak. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: @pjotrp - would you be willing to edit this submission for JOSS?

**Comment by arfon** [comment]
> 👋 @pjotrp - would you be willing to edit this submission for JOSS?

Friendly reminder on this @pjotrp 😁

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
Dear Robert,

Thank you for submitting and sorry for the delay in review. I'll look for a reviewer. Meanwhile, can you look at some of the accepted papers to put in some more information - like proper citations? http://joss.theoj.org/papers/popular. Also a note on relevance, performance and explaining what SAM/BAM/CRAM is would be helpful to readers. Not asking you to do a lot of work, but take a cue from other papers.

Pjotr

**Comment by pjotrp** [comment]
@brentp would you be willing to review this paper?

**Comment by brentp** [comment]
I am, but I am a (small) contributor to this repo. Does that preclude me?

**Comment by pjotrp** [comment]
@whedon assign @brentp as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @brentp

**Comment by pjotrp** [comment]
@brentp - the better :)

**Comment by brentp** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @brentp, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by arfon** [comment]
@pjotrp - looks like we're good to open up the review issue at this point? If so then you'll need this command to create the review issue (with checklist etc):

```
> @whedon start review magic-word=bananas
```

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/167. Feel free to close this issue now!
