### ISSUE TITLE
[REVIEW]: Sourcepredict: Prediction of metagenomic sample sources using dimension reduction followed by machine learning classification

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1540]
**Submitting author:** @maxibor (<a href="http://orcid.org/0000-0001-9140-7559">Maxime Borry</a>)
**Repository:** <a href="https://github.com/maxibor/sourcepredict" target ="_blank">https://github.com/maxibor/sourcepredict</a>
**Version:** v0.34
**Editor:** @lpantano
**Reviewers:** @gavinmdouglas, @giraola, @will-rowe 
**Archive:** <a href="https://doi.org/10.5281/zenodo.3379604" target="_blank">10.5281/zenodo.3379604</a>

## Status

[![status](http://joss.theoj.org/papers/f33385c6b7f2c176ae076bb1c4ad50ba/status.svg)](http://joss.theoj.org/papers/f33385c6b7f2c176ae076bb1c4ad50ba)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f33385c6b7f2c176ae076bb1c4ad50ba"><img src="http://joss.theoj.org/papers/f33385c6b7f2c176ae076bb1c4ad50ba/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f33385c6b7f2c176ae076bb1c4ad50ba/status.svg)](http://joss.theoj.org/papers/f33385c6b7f2c176ae076bb1c4ad50ba)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/maxibor/sourcepredict" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@gavinmdouglas & @giraola, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/maxibor/sourcepredict">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.34
- [x] **Authorship:** Has the submitting author (@maxibor) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/maxibor/sourcepredict">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.34
- [x] **Authorship:** Has the submitting author (@maxibor) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @gavinmdouglas, @giraola it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01540/joss.01540/10.21105.joss.01540.pdf)

**Comment by lpantano** [comment]
Hi @gavinmdouglas  and @giraola, just to check on how the reviewing is going and if you need anything from me. Thanks!

**Comment by gavinmdouglas** [comment]
Thanks @lpantano - I made comments (see: https://github.com/maxibor/sourcepredict/issues/3), which I believe are still being addressed by the author. I'll post here when that issue is resolved.

**Comment by maxibor** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by maxibor** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01540/joss.01540/10.21105.joss.01540.pdf)

**Comment by gavinmdouglas** [comment]
Hey @lpantano - There a small number of minor changes to the documentation that I think should be made, but all of my major comments have been addressed. Note that DOIs are not available for two of the references apparently.

**Comment by lpantano** [comment]
Thank you, @gavinmdouglas, for all the work. @maxibor, are you willing to make the changes to the documentation as the reviewer suggest?

**Comment by lpantano** [comment]
@whedone remove @giraola as reviewer

**Comment by lpantano** [comment]
@whedon remove @giraola as reviewer

**Comment by whedon** [comment]
OK, @giraola is no longer a reviewer

**Comment by lpantano** [comment]
@whedon add @giraola as reviewer

**Comment by whedon** [comment]
OK, @giraola is now a reviewer

**Comment by maxibor** [comment]
Changes were and are being made @lpantano

**Comment by maxibor** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01540/joss.01540/10.21105.joss.01540.pdf)

**Comment by gavinmdouglas** [comment]
Hey @lpantano  - quick note that all of my remaining minor comments have been addressed.

**Comment by lpantano** [comment]
Thanks a lot!, I’ll wait for the other reviewer.

**Comment by lpantano** [comment]
👋 @giraola, any update in the review? Thanks!

**Comment by lpantano** [comment]
Hi @maxibor, I am trying to find another reviewer since it seems @giraola is super busy right now. Sorry about the dealy. If you know other possible reviewer let me know.

**Comment by maxibor** [comment]
Hi @lpantano, @will-rowe could also be a good match for this

**Comment by will-rowe** [comment]
Happy to review if needed.

**Comment by lpantano** [comment]
@whedon add @will-rowe  as reviewer

**Comment by whedon** [comment]
OK, @will-rowe  is now a reviewer

**Comment by lpantano** [comment]
@whedon remove @giraola  as reviewer

**Comment by whedon** [comment]
OK, @giraola  is no longer a reviewer

**Comment by will-rowe** [comment]
Hi all. I've made a few minor comments over at the [sourcepredict issue tracker](https://github.com/maxibor/sourcepredict/issues/4). Nothing major - it's a nice contribution!

**Comment by maxibor** [comment]
@whedon generate pdf

**Comment by will-rowe** [comment]
@lpantano - My comments have been addressed and I'm happy. Thanks @maxibor

**Comment by maxibor** [comment]
@whedon commands

**Comment by maxibor** [comment]
@lpantano I created the Zenodo archive and added DOI badge in the README.
The version is now 0.34 (following all the modifications after this review).
The rest should be fine 😃

**Comment by maxibor** [comment]
Done

**Comment by labarba** [comment]
Some editorial fixes/requests:

- Remove the URL to the GitHub repository from the first line. The JOSS article template includes the repo as part of the margin decorators on the front page.
- Add comma after "i.e." and don't italicize
- [p.1] "Second it predicts" --> add comma
- [p.2] heading "Prediction of unknown sources proportion" --> Prediction of the proportion of unknown sources
- "Let S_i ... be a sample ... be an organism" --> pls fix verb repeat
- "of each of the ... organism" --> organisms (plural), or remove "of the"
- "is added to each U_k^S samples --> here, it's "sample" in singular: each sample
- independantly --> independently
- "Prediction of known source proportion" --> Prediction of the proportion of known sources
- [p.3] "Combining unknown and source proportion" --> proportions (plural)
- "Then for each" --> delete "Then" (you've started a new section); appears twice
- Acknowledgements --> add a \ after "Dr." to suppress the double white space (default in LaTeX for end of sentence)
- Bibliography: add case protection in titles with `{}` to keep the capitalization, where appropriate; for example, in "Southern Wisconsin"
- Use camel case for journal titles
- DOI for Maaten & Hinton 2008 (and caps protection)
- DOI for Patt et al. 1999?

You seem to have written the sections on p,2 as a sequence of orphan sentences. Can you group into paragraphs?

You mention `scikit-bio`: is there a reference you can cite for this library? What about `scikit-learn`?

**Comment by maxibor** [comment]
Thanks for the editorial check and comments !

> Remove the URL to the GitHub repository from the first line. The JOSS article template includes the repo as part of the margin decorators on the front page.

Done

> Add comma after "i.e." and don't italicize

Done

> [p.1] "Second it predicts" --> add comma

Done

> [p.2] heading "Prediction of unknown sources proportion" --> Prediction of the proportion of unknown sources

Done

> "Let S_i ... be a sample ... be an organism" --> pls fix verb repeat

Done

> "of each of the ... organism" --> organisms (plural), or remove "of the"

Done

> "is added to each U_k^S samples --> here, it's "sample" in singular: each sample

Done

> independantly --> independently

Done

> "Prediction of known source proportion" --> Prediction of the proportion of known sources

Done

> [p.3] "Combining unknown and source proportion" --> proportions (plural)

Done

> "Then for each" --> delete "Then" (you've started a new section); appears twice

Done

> Acknowledgements --> add a \ after "Dr." to suppress the double white space (default in LaTeX for end of sentence)

Done

> Bibliography: add case protection in titles with `{}`to keep the capitalization, where appropriate; for example, in "Southern Wisconsin"

Done

> Use camel case for journal titles

Done

> DOI for Maaten & Hinton 2008 (and caps protection)

> DOI for Patt et al. 1999?

As far as I could search, there is no DOI available for these articles (I couldn't find any DOI for the Journal of Machine Learning research)

> You seem to have written the sections on p,2 as a sequence of orphan sentences. Can you group into paragraphs?

Done

> You mention `scikit-bio`: is there a reference you can cite for this library?

Added a reference

> What about `scikit-learn`?

Added a reference

**Comment by maxibor** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01540/joss.01540/10.21105.joss.01540.pdf)

**Comment by maxibor** [comment]
Do you need any more input from my side @lpantano and @labarba ?

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/944

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/944, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1169207333764947969) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/945
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01540](https://doi.org/10.21105/joss.01540)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @maxibor, your JOSS paper is published! 🚀 

Big thanks to our editor: @lpantano, and reviewers: @gavinmdouglas, @will-rowe — we appreciate your contributions to JOSS! 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01540/status.svg)](https://doi.org/10.21105/joss.01540)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01540">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01540/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01540/status.svg
   :target: https://doi.org/10.21105/joss.01540
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01540/status.svg)](https://doi.org/10.21105/joss.01540)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by labarba** [comment]
@arfon —could you keep an eye on this paper? The DOI is not resolving yet.

**Comment by arfon** [comment]
Looks like the DOI is resolving now.

**Comment by maxibor** [comment]
Thanks @lpantano and @labarba for the editing !
Thanks a lot @gavinmdouglas and @will-rowe for the review and really helpful comments and suggestions !
First paper of my PhD, and great publishing experience with JOSS !

**Comment by arfon** [comment]
> First paper of my PhD, and great publishing experience with JOSS !

🎉 congrats!
