### ISSUE TITLE
[REVIEW]: PyCurious: A Python module for computing the Curie depth from the magnetic anomaly.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1544]
**Submitting author:** @brmather (<a href="http://orcid.org/0000-0003-3566-1557">Ben Mather</a>)
**Repository:** <a href="https://github.com/brmather/pycurious" target ="_blank">https://github.com/brmather/pycurious</a>
**Version:** 1.0.2
**Editor:** @lheagy
**Reviewers:** @santisoler, @jessepisel
**Archive:** <a href="https://doi.org/10.5281/zenodo.3349511" target="_blank">10.5281/zenodo.3349511</a>

## Status

[![status](http://joss.theoj.org/papers/7d3a0f7af69f8624092a0958860f2e38/status.svg)](http://joss.theoj.org/papers/7d3a0f7af69f8624092a0958860f2e38)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/7d3a0f7af69f8624092a0958860f2e38"><img src="http://joss.theoj.org/papers/7d3a0f7af69f8624092a0958860f2e38/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/7d3a0f7af69f8624092a0958860f2e38/status.svg)](http://joss.theoj.org/papers/7d3a0f7af69f8624092a0958860f2e38)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/brmather/pycurious" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@santisoler, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lheagy know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/brmather/pycurious">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.0.2
- [x] **Authorship:** Has the submitting author (@brmather) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/brmather/pycurious">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.0.2
- [x] **Authorship:** Has the submitting author (@brmather) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @santisoler it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01544/joss.01544/10.21105.joss.01544.pdf)

**Comment by lheagy** [comment]
@whedon add @jessepisel as reviewer

**Comment by whedon** [comment]
OK, @jessepisel is now a reviewer

**Comment by lheagy** [comment]
Thanks for your review @jessepisel! I see pr brmather/pycurious#12 is active and am linking it here so we can keep track of the progress

**Comment by jessepisel** [comment]
@lheagy perfect, thank you for linking it!

**Comment by brmather** [comment]
Thanks for your review @jessepisel - I have merged your pull request into the master branch and addressed your comments in brmather/pycurious#12. If you notice anything else that requires attention, please feel free to open an issue ticket.

**Comment by santisoler** [comment]
Hi @brmather! Sorry for the delay. I'll start opening some issues on `pycurious`' repository. We can discuss them over there.

**Comment by santisoler** [comment]
@brmather I think `pycurious` it's a great asset for geoscientists. Curie Point Depth is a widely used tool, but there aren't well maintained and documented open source libraries to calculate it. I'm glad to review it.

I've opened some issues, although I haven't found big problems with `pycurious`. I need to finish reviewing it, but feel free to answer them and even open PRs while I'm still doing it. Sorry for my brevity, I wanted to compensate my delay, so I opened the issues very quickly.

**Comment by santisoler** [comment]
@lheagy I have checked off all my boxes, so I consider `pycurious` to be ready for publication.

Thanks for letting me review it, and thanks to the authors @brmather and @rdelhaye for the quick response to every issue I opened. I enjoy the open review system because it offers a great opportunity to learn from each other and help improving ourselves.

**Comment by lheagy** [comment]
Excellent, many thanks @santisoler and @jessepisel for taking time to review!! 🎉 

@brmather, I have started a pull request with a few small corrections to the paper. I would also request that in the first paragraph, you give make a few more connections as to why the Curie depth is of interest when interpreting magnetic data. For example in or after the second sentence: would you mind adding some description as to why the Curie depth is used in the interpretation of magnetic data (e.g. it provides information on subsurface temperature, etc). I know you mention this, but it could be a bit more explicit for a non-domain expert. I left a few other comments in the pull request. Please let me know once you have had a chance to take a look.

**Comment by brmather** [comment]
Many thanks to @santisoler and @jessepisel for their extremely helpful reviews of `pycurious`. I have found JOSS' interactive review process very useful in improving software so that it is useful to as many people as possible. I have learnt a lot and will apply these practises to the other projects I'm actively working on. I thank the reviewers for the time they have spent on providing advice and submitting pull requests - it is very much appreciated!

Here is a summary of improvements to `pycurious` from the JOSS review:

- Updated contributions guide to encourage development on priority areas
- Anaconda installation support (and fixes for Cython build issues)
- Checking if windows that exceed the extent of the domain
- Correct propagation of errors with Tanaka *et al.* 1999 approach
- Refactor code to compute the radial power spectrum
- Updated Docstrings and Jupyter notebooks
- Updated test suite (using `pytest`) to test for expected functionality of core routines
- PEP8 compliant code

@lheagy thank you for coordinating the review process. I have responded to your pull request with number of additions I think broaden the appeal of the software package.

**Comment by brmather** [comment]
@whedon generate pdf from branch lheagy-patch-1

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch lheagy-patch-1. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01544/joss.01544/10.21105.joss.01544.pdf)

**Comment by brmather** [comment]
@whedon generate pdf from branch lheagy-patch-1

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch lheagy-patch-1. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01544/joss.01544/10.21105.joss.01544.pdf)

**Comment by brmather** [comment]
@whedon generate pdf from branch lheagy-patch-1

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch lheagy-patch-1. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01544/joss.01544/10.21105.joss.01544.pdf)

**Comment by lheagy** [comment]
:wave: @brmather, if you are happy with the edits to the paper, please merge in the changes and generate a new release of the software. From there, please create an archive on [zenodo](https://zenodo.org/) or similar with the title and author list being the same as the paper and then post the version number and doi here. Thanks!

**Comment by brmather** [comment]
Thanks @lheagy 

I have released version 1.0.2. Some unknown error foiled the 1.0 release on Zenodo, so I had to bump the version to 1.0.2. The Docker image is on Docker Hub, the release is on PyPI, and the Zenodo doi is 10.5281/zenodo.3349511.

**Comment by lheagy** [comment]
@whedon set 1.0.2 as version

**Comment by whedon** [comment]
OK. 1.0.2 is the version.

**Comment by lheagy** [comment]
@whedon set 10.5281/zenodo.3349511 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3349511" target="_blank">10.5281/zenodo.3349511</a> is the archive.

**Comment by lheagy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01544/joss.01544/10.21105.joss.01544.pdf)

**Comment by lheagy** [comment]
Thanks @brmather! Would you mind updating the title on the zenodo record to match the paper? e.g. "PyCurious: A Python module for computing the Curie depth from the magnetic anomaly" . Please also take a look at the proof above and give a :+1: if you are happy with it. From there, we can proceed with publishing 🎉

**Comment by brmather** [comment]
I keep getting an internal server error on Zenodo preventing me from updating the title and author fields. Aside from that, the proof looks good.

![Screenshot_2019-07-25 Zenodo](https://user-images.githubusercontent.com/15915881/61835580-bcbcff00-aebf-11e9-9c33-2101789571ac.png)

**Comment by lheagy** [comment]
Hmm... Is it possible you have it open in multiple tabs? (I am seeing the banner at the top that says "There us a new version of the upload being edited here")

**Comment by brmather** [comment]
Ha - that fixed it! Thanks @lheagy it's properly updated now.

**Comment by lheagy** [comment]
@openjournals/joss-eics, this submission is ready to be published! Congrats @brmather 🎉

**Comment by kyleniemeyer** [comment]
Hi @brmather, please merge the small PR I just submitted with some fixes in the paper: https://github.com/brmather/pycurious/pull/33

**Comment by brmather** [comment]
No problem. Merged to `master` branch.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01544/joss.01544/10.21105.joss.01544.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/867

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/867, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1154787023422705664) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/868
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01544](https://doi.org/10.21105/joss.01544)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
@brmather congrats on your article's publication in JOSS!

Thanks to  @santisoler and @jessepisel for reviewing, and to @lheagy for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01544/status.svg)](https://doi.org/10.21105/joss.01544)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01544">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01544/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01544/status.svg
   :target: https://doi.org/10.21105/joss.01544
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01544/status.svg)](https://doi.org/10.21105/joss.01544)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
