### ISSUE TITLE
[REVIEW]: SeleDiff: A fast and scalable tool for estimating and testing selection differences between populations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1545]
**Submitting author:** @xin-huang (<a href="http://orcid.org/0000-0002-9918-9602">Xin Huang</a>)
**Repository:** <a href="https://github.com/xin-huang/SeleDiff" target ="_blank">https://github.com/xin-huang/SeleDiff</a>
**Version:** v1.1
**Editor:** @lpantano
**Reviewer:** @stulacy, @suresh-lab
**Archive:** <a href="https://doi.org/10.5281/zenodo.3323833" target="_blank">10.5281/zenodo.3323833</a>

## Status

[![status](http://joss.theoj.org/papers/93d0bb9fea95827696628d97d9825dca/status.svg)](http://joss.theoj.org/papers/93d0bb9fea95827696628d97d9825dca)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/93d0bb9fea95827696628d97d9825dca"><img src="http://joss.theoj.org/papers/93d0bb9fea95827696628d97d9825dca/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/93d0bb9fea95827696628d97d9825dca/status.svg)](http://joss.theoj.org/papers/93d0bb9fea95827696628d97d9825dca)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/xin-huang/SeleDiff" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@stulacy & @suresh-lab, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/xin-huang/SeleDiff">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.1
- [x] **Authorship:** Has the submitting author (@xin-huang) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/xin-huang/SeleDiff">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.1
- [x] **Authorship:** Has the submitting author (@xin-huang) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @stulacy, @suresh-lab it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01545/joss.01545/10.21105.joss.01545.pdf)

**Comment by xin-huang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1545 with the following error:

**Comment by suresh-lab** [comment]
Hi, Am I able to provide written comments for the review in addition to the checklist? Do I attach it as a file here on this thread?

**Comment by stulacy** [comment]
Can you please add the DOI for Haldane (1924)?

**Comment by xin-huang** [comment]
Hi @stulacy 
Yes, I have added the doi for this reprint https://link.springer.com/article/10.1007/BF02459574

**Comment by lpantano** [comment]
Hi @suresh-lab,  for sure you can provide comments. if it will be a long thread you can create an issue in the repository and mention this one.  I think is better to write the comments on the issue so they are more accessible.  Let me know if that would work. Thanks!

**Comment by xin-huang** [comment]
Hi @suresh-lab 
I have revised the community guidelines in README:

"If you are interested in contributing to SeleDiff, please feel free to clone and modify it. You should include unit tests for your modified codes. Besides, you can edit build.gradle to include new dependencies. After your modification, please send a GitHub Pull Request with a clear list of what you've done."

Please let me know whether it is appropriate.

**Comment by suresh-lab** [comment]
thank you, that's perfect.

**Comment by lpantano** [comment]
It seems reviewers are done, let me know otherwise. I will start the final step to mark this as accepted.

**Comment by lpantano** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/ece3.1261 is OK
- 10.1073/pnas.1019276108 is OK
- 10.1007/BF02459574 is OK
- 10.1093/molbev/msw211 is OK
- 10.1101/gr.192336.115 is OK
- 10.1093/molbev/msu211 is OK
- 10.1111/mec.13559 is OK
- 10.1146/annurev-genet-111212-133526 is OK

MISSING DOIs

- https://doi.org/10.2307/1529706 may be missing for title: An Introduction to Population Genetics Theory

INVALID DOIs

- None
```

**Comment by lpantano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01545/joss.01545/10.21105.joss.01545.pdf)

**Comment by lpantano** [comment]
@xin-huang, it seems there is another DOI missing:

- https://doi.org/10.2307/1529706 may be missing for title: An Introduction to Population Genetics Theory

can you fix it?

And after that, can you make a zenodo archive and give me the DOI? you need to make sure the title and authors there match your paper.

thanks!

**Comment by lpantano** [comment]
@whedon set v1.1 as version

**Comment by whedon** [comment]
OK. v1.1 is the version.

**Comment by xin-huang** [comment]
Hi @lpantano 

I think this https://doi.org/10.2307/1529706 is a book review for the book I cited.  The book, An Introduction to Population Genetics Theory, is a old book published in 1970s (https://www.amazon.com/Introduction-Population-Genetics-Theory/dp/1932846123), I cannot find a doi related to this book.

The DOI for the zenodo archive is 10.5281/zenodo.3323833

Thank you very much.

**Comment by lpantano** [comment]
@whedon  set 10.5281/zenodo.3323833 as archive

**Comment by lpantano** [comment]
@whedon set 10.5281/zenodo.3323833 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3323833" target="_blank">10.5281/zenodo.3323833</a> is the archive.

**Comment by lpantano** [comment]
Hi @openjournals/joss-eics, this is accepted. The only thing is that reference that doesn't have a DOI because it is too old. I don't know if there is a specific way to deal with that. Thanks!

**Comment by danielskatz** [comment]
Thanks - I'll do the processing tonight or tomorrow

Don't worry about the DOI, whedon provides guidance but is not always right, and everything doesn't have to have a DOI; we just want to make sure that for things that do have a DOI, the DOI is part of the reference.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01545/joss.01545/10.21105.joss.01545.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/840

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/840, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@xin-huang - please merge https://github.com/xin-huang/SeleDiff/pull/6 to make a couple of small changes in wording.

**Comment by xin-huang** [comment]
Hi @danielskatz 

I have merged it into the main branch. Thank you very much.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01545/joss.01545/10.21105.joss.01545.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/841

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/841, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1151831781672402945) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/844
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01545](https://doi.org/10.21105/joss.01545)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @stulacy and @suresh-lab for reviewing and to @lpantano for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01545/status.svg)](https://doi.org/10.21105/joss.01545)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01545">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01545/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01545/status.svg
   :target: https://doi.org/10.21105/joss.01545
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01545/status.svg)](https://doi.org/10.21105/joss.01545)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
