### ISSUE TITLE
[PRE REVIEW]: SODAR Core

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1547]
**Submitting author:** @mikkonie (<a href="http://orcid.org/0000-0002-4180-8810">Mikko Nieminen</a>)
**Repository:** <a href="https://github.com/bihealth/sodar_core" target ="_blank">https://github.com/bihealth/sodar_core</a>
**Version:** v0.6.2
**Editor:** @lpantano
**Reviewers:** @rbatorsky, @olgabot

**Author instructions**

Thanks for submitting your paper to JOSS @mikkonie. **Currently, there isn't an JOSS editor assigned** to your paper.

@mikkonie if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1547 with the following error: 

 Could not find bibliography file: paper.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by labarba** [comment]
👋 @mikkonie — your paper is failing to compile because we need the bibliography in a `.bib` file. Please see the section on [https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) in the documentation.

**Comment by labarba** [comment]
@lpantano — Would you handle this submission as editor? Thanks!

**Comment by lpantano** [comment]
Hi, sure.

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
Hi @mikkonie , can you add as well a link with the documentation. I don't know if the idea is to be compatible with readthedocs or similar, but to have formatted documentation is important. Thanks!

**Comment by holtgrewe** [comment]
Hi @lpantano 👋 

(I'm a coauthor of @mikkonie) on this article.

We have a readthedocs documentation linked as "build passing" badge copied from the readthedocs generated markup, would something else be more appropriate?

- https://sodar-core.readthedocs.io/en/latest/?badge=latest

I'll look into the `.bib` file and failing build ASAP.

**Comment by lpantano** [comment]
Thanks @holtgrewe , can you add the link to the line `See docs for detailed documentation on use, integration and development.` I didn't see the badget was clickable and I was wondering where the link was. Thank you.

**Comment by holtgrewe** [comment]
@lpantano OK adjusted the `README.rst` and split out the bibliography into `.bib`.

**Comment by lpantano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01547/joss.01547/10.21105.joss.01547.pdf)

**Comment by lpantano** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.7287/peerj.preprints.27717v2 is OK
- 10.1038/sdata.2016.18 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lpantano** [comment]
@holtgrewe, do you have a suggested reviewer in mind?

**Comment by holtgrewe** [comment]
@lpantano Hm, I don't know anyone using Django for life science databases, sadly. Maybe @johanneskoester could recommend someone?

**Comment by lpantano** [comment]
@whedon assign @rbatorsky as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rbatorsky

**Comment by rbatorsky** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @rbatorsky, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by rbatorsky** [comment]
ok, I thought that might happen! @lpantano please start the review when you can.

**Comment by lpantano** [comment]
@whedon as @olgabot as reviewer

**Comment by lpantano** [comment]
@whedon add @olgabot as reviewer

**Comment by whedon** [comment]
OK, @olgabot is now a reviewer

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1584. Feel free to close this issue now!
