### ISSUE TITLE
[PRE REVIEW]: FEST-3D: Finite-volume Explicit STructured 3-Dimensional solver

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1549]
**Submitting author:** @jayten (<a href="http://orcid.org/0000-0002-1546-3855">Jatinder Pal Singh Sandhu</a>)
**Repository:** <a href="https://github.com/FEST3D/FEST-3D" target ="_blank">https://github.com/FEST3D/FEST-3D</a>
**Version:** v1.0
**Editor:** @labarba
**Reviewers:** @hariradh

**Author instructions**

Thanks for submitting your paper to JOSS @jayten. **Currently, there isn't an JOSS editor assigned** to your paper.

@jayten if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01549/joss.01549/10.21105.joss.01549.pdf)

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@rouson — Would you be willing to contribute another review for JOSS? This one seems right up your alley! (Fortran, CFD). Let me know!

**Comment by rouson** [comment]
@labarba Yes, I'll be glad to review this.  Please point me to the reviewer instructions.

**Comment by labarba** [comment]
Thank you, @rouson!! You can find the [Reviewer Guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) on our dedicated documentation site.

Do you know anyone who could be a good second reviewer?

**Comment by rouson** [comment]
I recommend Hari Radhakrishnan (GitHub user name @hariradh) and/or Izaak Beekman (GitHub user name @zbeekman).  Do they need to be added as collaborators on this repository or something for tagging them with "@username" to work?

**Comment by labarba** [comment]
👋  @hariradh, @zbeekman — Would either of you be willing to provide a review for a submission to the Journal of Open Source Software?
*FEST-3D: Finite-volume Explicit STructured 3-Dimensional solver*
software: https://github.com/FEST3D/FEST-3D
paper tmp link: https://github.com/openjournals/joss-papers/blob/joss.01549/joss.01549/10.21105.joss.01549.pdf

[Reviewer Guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) on our dedicated documentation site 🚀

**Comment by hariradh** [comment]
Dear Lorena,

I am willing to review the submission. Please send me any additional information needed for the review. 

Regards,
Hari

**Comment by labarba** [comment]
That's great @hariradh — Thank you. I will add you and start the review now. This will open a new GitHub issue, with a review checklist for you. JOSS reviews happen in the open, with reviewer comments posted on the review issue, and you can also open issues on the software repository. I'm here to answer any questions!

**Comment by labarba** [comment]
@whedon add @hariradh as reviewer

**Comment by whedon** [comment]
OK, @hariradh is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1555. Feel free to close this issue now!
