### ISSUE TITLE
[PRE REVIEW]: ODES: a high level interface to ODE and DAE solvers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#155]
**Submitting author:** @bmcage (<a href="http://orcid.org/0000-0001-8383-8068">Benny Malengier</a>)
**Repository:** <a href="https://github.com/bmcage/odes/" target ="_blank">https://github.com/bmcage/odes/</a>
**Version:** v2.3.0
**Editor:** @kyleniemeyer
**Reviewer:** @arghdos

**What this issue is for**

Thanks for submitting your paper to JOSS @bmcage. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @kyleniemeyer - would you be willing to edit this submission for JOSS?

**Comment by kyleniemeyer** [comment]
@arfon sure this definitely looks quite relevant!

**Comment by kyleniemeyer** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by bmcage** [comment]
feel free to direct any questions at me if needed

**Comment by kyleniemeyer** [comment]
Thanks @bmcage!

**Comment by kyleniemeyer** [comment]
@arghdos would you be willing to review this submission?

**Comment by arghdos** [comment]
@kyleniemeyer Yes, I am willing to review this

**Comment by kyleniemeyer** [comment]
Great! Please take a look at the reviewer guidelines: http://joss.theoj.org/about#reviewer_guidelines

@whedon assign @arghdos as reviewer

**Comment by kyleniemeyer** [comment]
@whedon assign @arghdos as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arghdos

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/165. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
OK @arghdos the actual review will take place over in #165, so I'm going to close this issue.
