### ISSUE TITLE
[PRE REVIEW]: bbsAssistant: An R package for downloading and handling data and information from the North American Breeding Bird Survey.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1550]
**Submitting author:** @trashbirdecology (<a href="http://orcid.org/0000-0002-0896-5099">Jessica Burnett</a>)
**Repository:** <a href="https://github.com/TrashBirdEcology/bbsAssistant/" target ="_blank">github.com/trashbirdecology/bbsassistant</a>
**Version:** 0.0.1
**Editor:** @kthyng
**Reviewers:** @ethanwhite , @jsta 

**Author instructions**

Thanks for submitting your paper to JOSS @trashbirdecology. **Currently, there isn't an JOSS editor assigned** to your paper.

@trashbirdecology if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1550 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
👋  @TrashBirdEcology — the GitHub repo URL you provided with the submission is giving a 404. Can you post here the correct URL?

**Comment by TrashBirdEcology** [comment]
Oh no - so sorry about that!

https://github.com/TrashBirdEcology/bbsAssistant/

________________________________________________________________

Jessica L. Burnett, M.Sc.
Ph.D. Candidate
School of Natural Resources
University of Nebraska-Lincoln
+1.352.792.5425

GitHub <http://github.com/trashbirdecology>
CV/Resume
<https://github.com/TrashBirdEcology/cv/blob/master/burnett_extendedCV.pdf>
Nebraska Cooperative Fish & Wildlife Research Unit
<http://snr.unl.edu/necoopunit/>
ORC ID: 0000-0002-0896-5099 <https://orcid.org/0000-0002-0896-5099>
________________________________________________________________



<http://snr.unl.edu/necoopunit/>

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01550/joss.01550/10.21105.joss.01550.pdf)

**Comment by labarba** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
hi @TrashBirdEcology! I'll be your editor. I have a few comments and questions to start.

Please look through your paper and edit it so that your links look correct. I suspect you have a space between the [] and the () so they aren't rendering correctly.

Also please look through your readme — your "manual" link doesn't work, I think there is an image that isn't coming through ("coverage status") and I saw a typo on "speices". 

Finally, have a look through our [list of reviewers](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing) and select out a handful that you think could be good choices. I'll contact them to get two total. If you know other people who would be good reviewers (but aren't involved with the project), feel free to list them too. Thanks!

**Comment by TrashBirdEcology** [comment]
@kthyng Thank you for this quick feedback. 

I have addressed the issues you mentioned in man and readme. 

I recommend @ethanwhite and @jhollist as potential reviewers. 
Please note that I have a mild conflict of interest with potential reviewer @ha0ye

Thanks!

**Comment by TrashBirdEcology** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01550/joss.01550/10.21105.joss.01550.pdf)

**Comment by kthyng** [comment]
@TrashBirdEcology Great!

I see that @jhollist has recently done a review for us, so I will try to find someone else.

@ethanwhite and @r-barnes are you interested and available to do a review on this JOSS submission? We ask for reviews within about 3 weeks, and you can get more information [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

**Comment by ethanwhite** [comment]
I'd be happy to review this. Not sure I can guarantee 3 weeks as I have some travel coming up, but 4 should be doable.

**Comment by kthyng** [comment]
@ethanwhite Thanks! I'll get the review underway as soon as I find a second reviewer.

@TrashBirdEcology can you find anyone else on the reviewer list to try? I couldn't get ahold of r-barnes. If needed I will ask jhollist but would prefer to try another person first.

**Comment by TrashBirdEcology** [comment]
@kthyng, perhaps @dombennett, @jabobsoj or @ha0ye

**Comment by kthyng** [comment]
@dombennett are you interested and available to do a review on this JOSS submission? We ask for reviews within about 3 weeks, and you can get more information [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

**Comment by r-barnes** [comment]
I'm afraid I'm overloaded at the moment. If you don't find someone in a few weeks, please ping me again. I'm sorry I can't be of more help :-(

**Comment by kthyng** [comment]
@r-barnes Understandable, thanks!

@TrashBirdEcology sorry for the delay as I work to find reviewers! 

@jacobsoj, @jhollist, or @ha0ye are you interested and available to do a review on this JOSS submission? We ask for reviews within about 3 weeks, and you can get more information here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html .  
We need one more reviewer to move forward!

**Comment by ha0ye** [comment]
I don't think I'll be able to do 3 weeks, since I have upcoming travel all the way through Sept. 9. If you still need someone after that point, I'll be able to help out.

Some other options might be @mstrimas, @SaraVarela, or @sebpardo who each have rOpenSci packages for bird data.

**Comment by jhollist** [comment]
I'm in the same boat as @ha0ye.  Got a crazy schedule until mid September.  I can commit to a review by Sep 20th.  Hopefully, I'll be the last resort and you get a review quicker than that.

Sorry!

**Comment by kthyng** [comment]
Ok still looking for a second reviewer. People have lots of travel at this time of year — I'm traveling too!

**Comment by kthyng** [comment]
@mstrimas, @SaraVarela, or @sebpardo are you interested and available to do a review on this JOSS submission? We ask for reviews within about 3 weeks, and you can get more information here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html .
We need one more reviewer to move forward!

**Comment by TrashBirdEcology** [comment]
@kthyng  I am OK with the wait as the FTP server on which some of these functions relies just underwent a major overhaul without warning.  I will need to update two of the functions, which I plan to do within ~10 days.

**Comment by kthyng** [comment]
Ok @TrashBirdEcology, I will put this on pause for now, please ping me when you are ready to move forward. Thank!

**Comment by TrashBirdEcology** [comment]
@kthyng We are ready to resume review. Thanks for your patience. 

@whedon generate pdf

**Comment by TrashBirdEcology** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01550/joss.01550/10.21105.joss.01550.pdf)

**Comment by kthyng** [comment]
Great! We're ready to continue then! Maybe we'll have better luck with reviewers' schedules now too...

@ethanwhite and @jhollist Would you be able to review this submission now that it is ready to go? As before, we'd ask for reviews in about the next 3 weeks or so.

**Comment by jhollist** [comment]
Unfortunately, I am now on the hook for another JOSS review by end of Sep.  Sorry!!!

**Comment by kthyng** [comment]
ha, ok thanks @jhollist.

@ha0ye would you be able to review this submission? I asked you previously but now time has passed so maybe you are available.

**Comment by ha0ye** [comment]
I think I can find the time over the next 3-4 weeks.

As a heads up though, I'm in the same lab as @ethanwhite, and we have our own project that includes a component that processes data (including BBS). Also, I know @TrashBirdEcology personally, and we have collaborated on work in the past.

I don't think those are substantial obstacles to my providing a constructive review; the overlap with @ethanwhite might be the most challenging in terms of finding a diverse set of reviewers, but I can understand the difficulties in wrangling sufficient reviewers to begin with!

**Comment by kthyng** [comment]
Thanks @ha0ye, makes sense that just you or @ethanwhite would be reviewers. Hopefully we can hear about @ethanwhite about his availability.

@mstrimas, @SaraVarela, or @sebpardo are you interested and available to do a review on this JOSS submission? We ask for reviews within about 3 weeks, and you can get more information here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html .

**Comment by ethanwhite** [comment]
I can still review, but things have gotten a lot busier since my semester has started so I need to ask for an extra week to complete the review.

**Comment by kthyng** [comment]
@ethanwhite totally understand that! Thanks for agreeing to review. I need to find another reviewer before we can proceed.

**Comment by TrashBirdEcology** [comment]
@kthyng I have posted on rstats twitter to see if we can't find someone (who isn't yet a JOSS reviewer)!

**Comment by kthyng** [comment]
ooo nice idea. I'm reaching out outside github too. Sign those people up as reviewers!! :)

**Comment by TrashBirdEcology** [comment]
Indeed..

**Comment by mstrimas** [comment]
Apologies for the slow response, I'm already hugely overcommitted this fall, so I definitely don't have time for a full code review. Looking at the review checklist, it doesn't seem like a code review is required though, mostly just some quick checks to make sure everything is working. Am I missing something here, do these usually go fairly quickly?

**Comment by kthyng** [comment]
@mstrimas We would prefer a code review actually. Maybe you can review for JOSS another time. Thanks!

**Comment by kthyng** [comment]
Hi @jsta! Are you interested and available to do a review on this JOSS submission? We ask for reviews within about 3 weeks, and you can get more information here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html .
We need one more reviewer to move forward!

**Comment by jsta** [comment]
Hi @kthyng I am interested and can review. :+1:

**Comment by sebpardo** [comment]
Hi @kthyng , unfortunately I have a very busy month ahead of me and won't be able to take on this review. Hopefully I can be of help with future reviews down the line.

**Comment by kthyng** [comment]
Thanks for the note @sebpardo!

**Comment by kthyng** [comment]
Woohoo! We have two reviewers!! @ethanwhite  and @jsta!!

**Comment by kthyng** [comment]
@whedon assign @ethanwhite  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ethanwhite

**Comment by kthyng** [comment]
@whedon add @jsta  as reviewer

**Comment by whedon** [comment]
OK, @jsta  is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1768. Feel free to close this issue now!

**Comment by kthyng** [comment]
Thanks all! We'll head on over to #1768 for the review itself.
