### ISSUE TITLE
[PRE REVIEW]: neurone_loader: A Python module for loading EEG data recorded with Bittium NeurOne

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1552]
**Submitting author:** @heilerich (<a href="http://orcid.org/0000-0002-9068-2679">Felix Heilmeyer</a>)
**Repository:** <a href="https://github.com/heilerich/neurone_loader" target ="_blank">https://github.com/heilerich/neurone_loader</a>
**Version:** v1.1.0
**Editor:** @brainstorm
**Reviewers:** @rougier, @satra

**Author instructions**

Thanks for submitting your paper to JOSS @heilerich. **Currently, there isn't an JOSS editor assigned** to your paper.

@heilerich if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1552 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
👋 @heilerich — your paper is not compiling. Please add the required bibliography field, according to the [documentation](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography).

**Comment by heilerich** [comment]
my bad 🙏🏻 I added the field.
@whedon generate pdf

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01552/joss.01552/10.21105.joss.01552.pdf)

**Comment by labarba** [comment]
@cMadan — Would you add another paper to your editing load? This one seems closest to your areas of domain knowledge.

**Comment by labarba** [comment]
👋 @brainstorm — Would you be able to edit this submission?

**Comment by brainstorm** [comment]
@satra, would you help me out reviewing this submission for JOSS? :)

**Comment by arfon** [comment]
> @satra, would you help me out reviewing this submission for JOSS? :)

Thanks @brainstorm. Just a reminder that we've moved to having a minimum of two reviewers these days incase you were planning on proceeding with just the one 😸

**Comment by brainstorm** [comment]
Argh, true, forgot about that... perhaps @chrisgorgo can be our second reviewer for JOSS? 👋

**Comment by satra** [comment]
@brainstorm - happy to do a review.

**Comment by brainstorm** [comment]
@whedon assign @satra as reviewer

**Comment by brainstorm** [comment]
Thanks Satra! :)

**Comment by labarba** [comment]
@whedon assign @brainstorm as editor

**Comment by whedon** [comment]
OK, the editor is @brainstorm

**Comment by brainstorm** [comment]
@rougier Would you like to assist reviewing this paper?

**Comment by rougier** [comment]
I'm already late with another JOSS review but I can try do to this one by end of July if it is ok.

**Comment by brainstorm** [comment]
Thanks @rougier! It's fine for me unless @heilerich is in a rush to get this review done?

**Comment by heilerich** [comment]
Fine for me! Take your time.

**Comment by brainstorm** [comment]
@whedon assign @rougier as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rougier

**Comment by brainstorm** [comment]
@whedon add @satra as reviewer

**Comment by whedon** [comment]
OK, @satra is now a reviewer

**Comment by brainstorm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1626. Feel free to close this issue now!
