### ISSUE TITLE
[REVIEW]: pyMannKendall: a python package for non parametric Mann Kendall family of trend tests.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1556]
**Submitting author:** @mmhs013 (<a href="http://orcid.org/0000-0002-5361-0633">Md. Manjurul Hussain</a>)
**Repository:** <a href="https://github.com/mmhs013/pyMannKendall" target ="_blank">https://github.com/mmhs013/pyMannKendall</a>
**Version:** 1.1
**Editor:** @mbobra
**Reviewer:** @dhhagan, @rreinecke
**Archive:** <a href="https://doi.org/10.5281/zenodo.3347253" target="_blank">10.5281/zenodo.3347253</a>

## Status

[![status](http://joss.theoj.org/papers/14903dbd55343be89105112e585d262a/status.svg)](http://joss.theoj.org/papers/14903dbd55343be89105112e585d262a)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/14903dbd55343be89105112e585d262a"><img src="http://joss.theoj.org/papers/14903dbd55343be89105112e585d262a/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/14903dbd55343be89105112e585d262a/status.svg)](http://joss.theoj.org/papers/14903dbd55343be89105112e585d262a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mmhs013/pyMannKendall" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dhhagan & @rreinecke, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mbobra know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mmhs013/pyMannKendall">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.1
- [x] **Authorship:** Has the submitting author (@mmhs013) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mmhs013/pyMannKendall">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.1
- [x] **Authorship:** Has the submitting author (@mmhs013) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dhhagan, @rreinecke it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01556/joss.01556/10.21105.joss.01556.pdf)

**Comment by mbobra** [comment]
👋 @dhhagan @rreinecke Thanks for agreeing to review this submission! Whedon generated a checklist for you above. Feel free to ask me any questions -- I'm always happy to help.

**Comment by rreinecke** [comment]
@mmhs013 I did not have the time to take a closer look at your code but here are already some comments on the overall documentation that you could improve:

-  mmhs013/pyMannKendall#1 
-  mmhs013/pyMannKendall#2
-  mmhs013/pyMannKendall#3
-  mmhs013/pyMannKendall#4
-  mmhs013/pyMannKendall#5
-  mmhs013/pyMannKendall#6

**Comment by rreinecke** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by rreinecke** [comment]
@mmhs013 I had a look at your code now and I think it is nicely documented but without robust unit tests and an thoroughly explained example problem it is not possible for me to judge if the code actually provides the promised functionality. See also mmhs013/pyMannKendall#5 Let me know if you need further input. I will continue my review when this is implemented.

**Comment by rreinecke** [comment]
@mbobra @mmhs013 FYI I'm not available from 13th till the 20th. I will continue the review after my return. See also my notes for @mmhs013 above.
Cheers

**Comment by mmhs013** [comment]
@rreinecke *thanks for your comments*. According to your comments, I am already updated readme file with Installation Instructions, list of dependencies (mmhs013/pyMannKendall#1), project description (mmhs013/pyMannKendall#2) and added new details example ipython notebook file with some plots (mmhs013/pyMannKendall#3) and added DOI in paper bib file (mmhs013/pyMannKendall#6).

The input and output parameters of functions are almost the same, which are described in **Function details** section in the readme file. I think, the new updates of readme file and example also describe more clearly about functions (mmhs013/pyMannKendall#4).

I write this unit test using pytest for my own purpose because when I update/modify my code, this test compares those functions with some known results. If I unintentionally make some mistakes, which produce the wrong result, This will warn me. I think this is fine for me (mmhs013/pyMannKendall#5).

I don't use the unit test previously. So I am not an expert in this section. I don't clearly understand how can I improve my unit test. Do you have any suggestions for me?

Please check my updates. If you are satisfied with my updates, then close relevant issues. I am waiting for your respond.

**Comment by rreinecke** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by rreinecke** [comment]
@mbobra I'm done. I think the submission substantially improved throughout the review and is ready to be accepted after @dhhagan concerns have been addressed.

@mmhs013 I would suggest to you to go through the README and code files with a spellchecker there are still a couple typos and grammar mistakes. ;)

Cheers
Robert

**Comment by mmhs013** [comment]
Thanks a lot, @rreinecke . My English is poor. :( I will update my README and other with a professional writer.

**Comment by dhhagan** [comment]
@mbobra Just finished up the review - It looks like after the paper is regenerated and the DOI's appear, it is good to go! I agree with @rreinecke that the english could be improved a bit - @mmhs013 Let me know if you would like any help with this and I could probably run through the ReadMe real quick, though I don't want to step on any toes.

**Comment by mbobra** [comment]
@rreinecke and @dhhagan Thank you so much for reviewing! We really appreciate your time and effort ☀️

@mmhs013 We're almost there! I have a couple comments:
* Do you have access to someone who can read over the docs and give some feedback on improving the English? If not, let me know and we can help you.
* Can you please [archive your release on Zenodo](https://guides.github.com/activities/citable-code/) to obtain a DOI and then put that in your README.md file? 

After these two items I think we're done 🎉

**Comment by mmhs013** [comment]
@rreinecke, @dhhagan and @mbobra thanks a lot for reviewing my project.

@mbobra, I already checked the README.md file and others with my friend. I think it's been better than before. I also archive my package on Zenodo and add Zenodo DOI in my README.md file.

**Comment by mbobra** [comment]
@whedon set 10.5281/zenodo.3347253 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3347253" target="_blank">10.5281/zenodo.3347253</a> is the archive.

**Comment by mbobra** [comment]
@whedon set 1.1 as version

**Comment by whedon** [comment]
OK. 1.1 is the version.

**Comment by mbobra** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by mbobra** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by mbobra** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1556 with the following error: 

 Error reading bibliography ./paper.bib (line 15, column 3):
unexpected "d"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by mbobra** [comment]
@mmhs013 It looks like there is a small error in paper.bib. Could you add a comma at the end of line 14?

**Comment by mmhs013** [comment]
@mbobra, I already fix this error. Please check it again.

**Comment by mbobra** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01556/joss.01556/10.21105.joss.01556.pdf)

**Comment by mbobra** [comment]
@openjournals/joss-eics This paper is ready for acceptance! (I could not get Whedon to check the references but it looks fine in the pdf). Nice work @mmhs013 🎉

**Comment by mmhs013** [comment]
@mbobra, all references are not visible in pdf!

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.2307/1907187 is OK
- 10.1016/j.atmosres.2016.02.008 is OK
- 10.1029/WR018i001p00107 is OK
- 10.1016/S0022-1694(97)00125-X is OK
- 10.2307/2333424 is OK
- 10.1023/B:WARM.0000043140.61082.60 is OK
- 10.1029/2001WR000861 is OK
- 10.1002/hyp.1095 is OK
- 10.1021/es051650b is OK
- 10.1002/env.507 is OK
- 10.1080/01621459.1968.10480934 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mmhs013** [comment]
@mbobra, when I update my paper for improving English, I accidentally remove some of my reference from paper. So those are not shown in pdf. I am sorry for that. I already fix it. Can you regenerate pdf?

**Comment by mbobra** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01556/joss.01556/10.21105.joss.01556.pdf)

**Comment by mmhs013** [comment]
Now, it looks good. Thanks a lot @mbobra for accept my paper. :D

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.2307/1907187 is OK
- 10.1016/j.atmosres.2016.02.008 is OK
- 10.1029/WR018i001p00107 is OK
- 10.1016/S0022-1694(97)00125-X is OK
- 10.2307/2333424 is OK
- 10.1023/B:WARM.0000043140.61082.60 is OK
- 10.1029/2001WR000861 is OK
- 10.1002/hyp.1095 is OK
- 10.1021/es051650b is OK
- 10.1002/env.507 is OK
- 10.1080/01621459.1968.10480934 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.2307/1907187 is OK
- 10.1016/j.atmosres.2016.02.008 is OK
- 10.1029/WR018i001p00107 is OK
- 10.1016/S0022-1694(97)00125-X is OK
- 10.2307/2333424 is OK
- 10.1023/B:WARM.0000043140.61082.60 is OK
- 10.1029/2001WR000861 is OK
- 10.1002/hyp.1095 is OK
- 10.1021/es051650b is OK
- 10.1002/env.507 is OK
- 10.1080/01621459.1968.10480934 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @mmhs013, one final thing: could you edit the Zenodo archive to make the title match the paper title?

**Comment by kyleniemeyer** [comment]
Also, @mmhs013 please merge the two pull requests I just submitted, which fix a few things in the paper and references: https://github.com/mmhs013/pyMannKendall/pull/9 and https://github.com/mmhs013/pyMannKendall/pull/10

**Comment by mmhs013** [comment]
@kyleniemeyer, I already update Zenodo title and also merge you two pull requests. Thanks for you help.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01556/joss.01556/10.21105.joss.01556.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/860

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/860, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1154436602413944839) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/861
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01556](https://doi.org/10.21105/joss.01556)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @mmhs013 on your paper's publication in JOSS! Thanks to  @dhhagan and @rreinecke for reviewing, and @mbobra for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01556/status.svg)](https://doi.org/10.21105/joss.01556)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01556">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01556/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01556/status.svg
   :target: https://doi.org/10.21105/joss.01556
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01556/status.svg)](https://doi.org/10.21105/joss.01556)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by SSSCharmCity** [comment]
It does not appear that the code implements the full partial MannKendall methods described in Libiseller& Grimvall for one or more covariates WITH SEASONALITY.  I.e L&G describe data for d- variables, p-seasons, and n-years.   This code appears to only address data from 2-variables for n-years.   The utility of this helpful code would be significantly increased if the seasonal form of the partial MK test was coded, allowing the user to specify d=2 and p=1 (currently implemented) as a special case.

**Comment by mmhs013** [comment]
@SSSCharmCity, thanks for your recommendation. I will try to implement this in future updates.
