### ISSUE TITLE
[REVIEW]: Wikipedia2Vec: An Optimized Tool for Learning Embeddings of Words and Entities from Wikipedia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1558]
**Submitting author:** @ikuyamada (<a href="http://orcid.org/0000-0002-7980-7661">Ikuya Yamada</a>)
**Repository:** <a href="https://github.com/wikipedia2vec/wikipedia2vec" target ="_blank">https://github.com/wikipedia2vec/wikipedia2vec</a>
**Version:** v1.0.3
**Editor:** @arfon
**Reviewer:** @ionlights
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/6f8f184e6350b2fe9381d26c9a6249e3/status.svg)](http://joss.theoj.org/papers/6f8f184e6350b2fe9381d26c9a6249e3)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/6f8f184e6350b2fe9381d26c9a6249e3"><img src="http://joss.theoj.org/papers/6f8f184e6350b2fe9381d26c9a6249e3/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/6f8f184e6350b2fe9381d26c9a6249e3/status.svg)](http://joss.theoj.org/papers/6f8f184e6350b2fe9381d26c9a6249e3)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/wikipedia2vec/wikipedia2vec" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ionlights, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @usethedata know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/wikipedia2vec/wikipedia2vec">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.3)?
- [ ] **Authorship:** Has the submitting author (@ikuyamada) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ionlights it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01558/joss.01558/10.21105.joss.01558.pdf)

**Comment by ionlights** [comment]
hey, @ikuyamda, @usethedata 

sorry i've been silent. i'm nearly done. i've done all of the checklist save for the functionality (validating performance, etc.)

all the other, un-marked sections have comments which i've been preparing. i'm hoping to have this done this weekend, though i'm not sure about the performance validation.

@usethedata are you looking for me to reproduce their results, in terms of analytical performance (accuracies, scores, etc.) as well as training time? (latter is kinda up to whatever hardware user's have, so that's a bit harder to validate.)

**Comment by usethedata** [comment]
@ionlights Sorry to have been out of communication, and I really thought I'd responded to your question.  Don't worry about training time in any absolute sense.  Anything you can do in a reasonable amount of time that checks for qualitative agreement with their claims is appreciated.

**Comment by arfon** [comment]
@ionlights - could you give me an update on the status of this review? For @ikuyamada's sake, I would really like to wrap up this submission ASAP.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by arfon** [comment]
@usethedata - I'll take this one from here.

**Comment by arfon** [comment]
@ionlights @usethedata - I've been in touch with the author (@ikuyamada) and they have decided to withdraw this paper from JOSS. Thanks for your efforts on this, and I'm sorry this paper didn't make it to accept/publish.

**Comment by arfon** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
