### ISSUE TITLE
[PRE REVIEW]: drms: A Python package for accessing HMI and AIA data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1559]
**Submitting author:** @kbg (<a href="http://orcid.org/0000-0002-1361-5712">Kolja Glogowski</a>)
**Repository:** <a href="https://github.com/sunpy/drms" target ="_blank">https://github.com/sunpy/drms</a>
**Version:** v0.5.6
**Editor:** @xuanxu
**Reviewers:** @mgckind, @aureliocarnero

**Author instructions**

Thanks for submitting your paper to JOSS @kbg. **Currently, there isn't an JOSS editor assigned** to your paper.

@kbg if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1559 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
:wave: @xuanxu - would you be willing to edit this submission for JOSS?

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1559 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:123:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:123:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:121:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:121:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:81:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@kbg this PR should fix your paper: https://github.com/sunpy/drms/pull/29

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01559/joss.01559/10.21105.joss.01559.pdf)

**Comment by kbg** [comment]
@arfon Thanks. I forgot to add the ORCID for one of the authors. I also spotted a missing hyphen in one of the affiliations. Both should be fixed now.

**Comment by xuanxu** [comment]
@whedon assign @xuanxu as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by xuanxu** [comment]
👋 @mgckind and @astrom-tom: Would you be willing to be the reviews of this paper? I think your expertise in Python and astrophysics data management makes both of you a great fit for this submission.

**Comment by mgckind** [comment]
@xuanxu, thanks for the ping, I'm still on vacation I might be able to give you a realistic answer early next week.

**Comment by mbobra** [comment]
Hi! The SunPy Project plans to submit [a paper about our v1.0 release](https://github.com/sunpy/sunpy-1.0-paper) and we'd like to cite this paper on `drms` since it is a SunPy affiliated package. Do you know approximately how long it would take to complete this review so we can synchronize our submission?

**Comment by xuanxu** [comment]
Hi @mbobra! I'm waiting responses from @mgckind, @astrom-tom and another posible reviewer I contacted via email. Hopefully the review can start some day this week.

**Comment by mgckind** [comment]
Sorry I dropped the ball on this request , please assign me as reviewer @xuanxu I'll start as soon as possible (I'm at Pearc19 this week)

**Comment by xuanxu** [comment]
Thanks @mgckind! I'll assign you now. I'll then start the review once we have the second reviewer. Stay tuned!

**Comment by xuanxu** [comment]
@whedon assign @mgckind as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mgckind

**Comment by xuanxu** [comment]
@whedon add @aureliocarnero as reviewer

**Comment by whedon** [comment]
OK, @aureliocarnero is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1614. Feel free to close this issue now!

**Comment by xuanxu** [comment]
@mgckind, @aureliocarnero - please head over to #1614 where the review will take place.

**Comment by astrom-tom** [comment]
Dear all,

Sorry for the late answer I was unavailable for more than a month. I would be happy to be a reviewer as well if there is still time.

let me know!
Cheers,

R

**Comment by xuanxu** [comment]
Hey @astrom-tom! Thanks! Right now the review is almost complete by one of the reviewers and halfway there by the other. If you don't mind I prefer to have you first in queue for the next astro-submission we receive.
