### ISSUE TITLE
[PRE REVIEW]: biotmle: Targeted Learning for Biomarker Discovery

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#156]
**Submitting author:** @nhejazi (<a href="http://orcid.org/0000-0002-7127-2789">Nima Hejazi</a>)
**Repository:** <a href="https://github.com/nhejazi/biotmle" target ="_blank">https://github.com/nhejazi/biotmle</a>
**Version:** v0.1.0
**Editor:** @karthik
**Reviewer:** @NelleV

**What this issue is for**

Thanks for submitting your paper to JOSS @nhejazi. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @mgymrek @biorelated - would either of you be willing to edit this submission for JOSS?

**Comment by mgymrek** [comment]
A little outside my area but I have some potential reviewers in mind that I'll reach out to.

**Comment by arfon** [comment]
@whedon assign @mgymrek as editor

**Comment by whedon** [comment]
OK, the editor is @mgymrek

**Comment by arfon** [comment]
> A little outside my area but I have some potential reviewers in mind that I'll reach out to.

:wave: @mgymrek - how are you getting on finding a reviewer for this submission?

**Comment by nhejazi** [comment]
Just wanted to add a few updates from the development end of the `biotmle` R package:

* There are a number of minor revisions (no changes to the core functionality) currently in process, for submission of the package to the [Bioconductor project](http://www.bioconductor.org/). See [this issue](https://github.com/nhejazi/biotmle/issues/15) for a list.

* All functionality of the package is intact -- perhaps see the R package vignette [here](http://nimahejazi.org/biotmle/articles/exposureBiomarkers.html).

* My understanding of the review process is that JOSS is meant to ensure that the software works as advertised, so I would think that deep knowledge of the statistical approach would be unnecessary (there is, of course, a separate methods manuscript being prepared for submission, but that should not be necessary to use the R package).

**Comment by nhejazi** [comment]
@arfon @mgymrek -- The R package has now been fully revised and accepted by Bioconductor (please see the relevant issue [here](https://github.com/Bioconductor/Contributions/issues/254)). Since Bioconductor's review system is quite similar to that of JOSS, the software and paper should now be fully JOSS-compliant.

**Comment by arfon** [comment]
> Since Bioconductor's review system is quite similar to that of JOSS, the software and paper should now be fully JOSS-compliant. 

@nhejazi - we don't have any formal agreement with Bioconductor about this. @karthik - could you advise?

**Comment by nhejazi** [comment]
@arfon -- I didn't mean anything about a formal agreement: I mentioned that because my previous comment (from 13 March) indicated that the software was being altered, which I assumed would hold up the review. I point out that the software has gone through Bioconductor's entirely separate vetting process for the eventual reviewer (scanning the issue would give them a sense of exactly what standards the software does and does not conform to). My apologies for any confusion!

**Comment by arfon** [comment]
>  I point out that the software has gone through Bioconductor's entirely separate vetting process for the eventual reviewer (scanning the issue would give them a sense of exactly what standards the software does and does not conform to). My apologies for any confusion.

👍 yep, no problem. I just wanted to make sure that you understood that being accepted into Bioconductor doesn't have an _formal_ meaning here (although I agree it's a very good sign 😁). 

BTW, we _do_ have an agreement with the [ROpenSci](https://github.com/ropensci) folks that packages that have been accepted there can be automatically accepted here.

**Comment by karthik** [comment]
@arfon @nhejazi I'm aware of the bioconductor review system but don't know details of their process. But I like the idea of exploring how similar it is to rOpenSci and fast track those submissions if appropriate.  For now let's proceed with this as a regular submission but evaluate before the next bioconductor one comes through.

**Comment by arfon** [comment]
Ping @mgymrek - are you still able to edit this submission?

**Comment by nhejazi** [comment]
Would it be possible to inquire whether there might be other JOSS editors that might be less busy than the individual assigned? Nothing at all against @mgymrek, just that we haven't heard anything from them at all on this thread since 10 January.

**Comment by karthik** [comment]
Sorry @nhejazi

I will take this over and assign a reviewer by early next week.

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by arfon** [comment]
> I will take this over and assign a reviewer by early next week.

👍 thanks @karthik

**Comment by nhejazi** [comment]
Thanks very much, @karthik!

**Comment by karthik** [comment]
@whedon assign @NelleV as reviewer

**Comment by karthik** [comment]
@NelleV Thank you so much for agreeing to review this submission 🙏. I realize you are busy this week, so if you able to review in the next two weeks, we would be super grateful. Please start your review in the issue below and I will close this (pre-review request) out.

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by karthik** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/295. Feel free to close this issue now!

**Comment by nhejazi** [comment]
@karthik and @NelleV, many thanks for the help in starting the review!
