### ISSUE TITLE
[PRE REVIEW]: ccostr: An R package for estimating mean costs with censored data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1560]
**Submitting author:** @LarsHernandez (<a href="http://orcid.org/0000-0002-3715-8528">Lars Nielsen</a>)
**Repository:** <a href="https://github.com/HaemAalborg/ccostr" target ="_blank">https://github.com/HaemAalborg/ccostr</a>
**Version:** 0.1.0
**Editor:** @csoneson
**Reviewers:** @BarryDeCicco, @joethorley

**Author instructions**

Thanks for submitting your paper to JOSS @LarsHernandez. **Currently, there isn't an JOSS editor assigned** to your paper.

@LarsHernandez if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1560 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1560/paper.md): invalid leading UTF-8 octet at line 1 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:95:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @csoneson - would you be willing to edit this submission for JOSS?

**Comment by arfon** [comment]
@LarsHernandez - this PR should fix your paper compilation: https://github.com/HaemAalborg/ccostr/pull/8

**Comment by csoneson** [comment]
> 👋 @csoneson - would you be willing to edit this submission for JOSS?

Yes, I can do that!

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
@LarsHernandez - please let me know if you have suggestions for suitable reviewers (e.g. from the list in the first post above)!

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1560 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by csoneson** [comment]
👋 @LarsHernandez - it looks like whedon is not happy with the missing date field in your yaml header, could you add that? I compiled it locally to have a first look and it looks almost all good; could you just add case protection for {SAS} in the Zhao and Wang (2010) reference? Also, the word "naïve" doesn't show up properly in my locally compiled paper - whedon might have the same problem. Once you have pushed a new version to your GitHub repo, you can ask whedon to rebuild the pdf using the command above (@whedon generate pdf).

**Comment by LarsHernandez** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01560/joss.01560/10.21105.joss.01560.pdf)

**Comment by LarsHernandez** [comment]
@csoneson Thanks for the corrections, I think it generated correctly now. I don't really have any other suggestions for reviewers, we checked the list and you seemed the most apt.

**Comment by csoneson** [comment]
Thanks @LarsHernandez, yes, now it renders correctly. For the reviewers - I think you checked the list of JOSS editors. In the first post in this issue there is a link to a list of people who have signed up as potential reviewers. Could you have a look at that one? I will do the same, and we'll find some good reviewers for your submission!

**Comment by csoneson** [comment]
👋@BarryDeCicco, @joethorley - would you be interested in reviewing this submission for JOSS?

**Comment by BarryDeCicco** [comment]
Yes - this will be my first review.

    On Wednesday, July 24, 2019, 7:06:13 AM EDT, Charlotte Soneson <notifications@github.com> wrote:  
 
 
👋@BarryDeCicco, @joethorley - would you be interested in reviewing this submission for JOSS?

**Comment by joethorley** [comment]
> 👋@BarryDeCicco, @joethorley - would you be interested in reviewing this submission for JOSS?

I'm happy to review.

**Comment by csoneson** [comment]
@whedon assign @BarryDeCicco as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @BarryDeCicco

**Comment by csoneson** [comment]
@whedon add @joethorley as reviewer

**Comment by whedon** [comment]
OK, @joethorley is now a reviewer

**Comment by csoneson** [comment]
@BarryDeCicco, @joethorley - thanks a lot! I will close this pre-review issue now and open the main review issue, where the review will take place.

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1593. Feel free to close this issue now!
