### ISSUE TITLE
[PRE REVIEW]: X.509 Compliant Hybrid Certificates for the Post-Quantum Transition

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1561]
**Submitting author:** @j-braun (<a href="http://orcid.org/0000-0001-6491-2250">Johannes Braun</a>)
**Repository:** <a href="https://github.com/CROSSINGTUD/bc-hybrid-certificates" target ="_blank">https://github.com/CROSSINGTUD/bc-hybrid-certificates</a>
**Version:** v1.0.0
**Editor:** @danielskatz
**Reviewers:** @jbasney, @jteheran

**Author instructions**

Thanks for submitting your paper to JOSS @j-braun. **Currently, there isn't an JOSS editor assigned** to your paper.

@j-braun if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01561/joss.01561/10.21105.joss.01561.pdf)

**Comment by arfon** [comment]
:wave: thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). In particular, this item:

> - Your software should have an obvious research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)? The section [_'what should my paper contain'_](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) has some guidance for the sort of content we're looking to be present in the `paper.md`.

Many thanks!

**Comment by danielskatz** [comment]
👋 @j-braun - note that we are waiting for your reply here...

**Comment by j-braun** [comment]
@arfon @danielskatz - I am sorry for the delayed answer. I was busy the past days and did not have the possibility to track the issue all the time. So here is the answer to your question in regard to research applictions:
Our software was designed to be used by (post-quantum) cryptography researchers and IT security practitioners. It’s goal is to enable researchers to extensively test their newly designed schemes in real world environments and to demonstrate their practicality. This is a very important aspect on that field of research as it allows insights and gives valuable hints in regard to optimization and parameter setting. A prior mock-up implementation was for example used  for the following publication, which we also reference in the paper:
“N. Bindel, U. Herath, M. McKague, and D. Stebila. Transitioning to a quantum resistant public key infrastructure. In T. Lange and T. Takagi, editors, Post-Quantum Cryptography, pages 384{405, Cham, 2017. Springer International Publishing.”
The mock up implementation was used to do a first evaluation of the hybrid certificate approach in conjunction with the Q-TESLA scheme designed by Bindel at al. Our software now allows a more thorough evaluation of such schemes.

Should we explicitly add this to the paper?

**Comment by j-braun** [comment]
@whedon - potential reviewers could be: 
- gcdeshpande 
- trp07

**Comment by j-braun** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by j-braun** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01561/joss.01561/10.21105.joss.01561.pdf)

**Comment by danielskatz** [comment]
@j-braun - we have rotating associate editors-in-chief, which is why two of us have asked about this, and this week, we'll let a third (@kyleniemeyer) reply and follow-up...

**Comment by kyleniemeyer** [comment]
Hi @j-braun, thanks for your explanation. Yes, please do add some description of the research applications of the software to your paper; this may be most helpful near the beginning.

**Comment by kyleniemeyer** [comment]
@danielskatz can you serve as editor for this submission?

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @gcdeshpande & @trp07 - would you be willing to review this JOSS submission?

**Comment by danielskatz** [comment]
👋 @jbasney - would you be willing to review this JOSS submission?  Or perhaps suggest others who would be well-suited.  See the [paper above](https://github.com/openjournals/joss-papers/blob/joss.01561/joss.01561/10.21105.joss.01561.pdf) and [info on JOSS reviewing](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)

**Comment by jbasney** [comment]
Yes I can do the review this weekend. -Jim

**Comment by danielskatz** [comment]
Thanks Jim - I'll assign you as a reviewer, but we won't start the review until I also get another reviewer assigned.

**Comment by danielskatz** [comment]
@whedon @assign @jbasney as reviewer

**Comment by danielskatz** [comment]
@whedon assign @jbasney as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jbasney

**Comment by j-braun** [comment]
Hi @danielskatz  , just added some text regarding research applications to the paper as @kyleniemeyer  requested.

**Comment by danielskatz** [comment]
@jbasney - do you have any thoughts on another reviewer?

**Comment by jbasney** [comment]
> @jbasney - do you have any thoughts on another reviewer?

Yes, I think @msalle @DrDaveD @jteheran @zsshah & @djw8605 would all be good reviewers if they are available.

**Comment by danielskatz** [comment]
👋  @msalle @DrDaveD @jteheran @zsshah & @djw8605 - would one of you be willing to review this submission for JOSS?  See the [paper above](https://github.com/openjournals/joss-papers/blob/joss.01561/joss.01561/10.21105.joss.01561.pdf) and [info on JOSS reviewing](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)

**Comment by jteheran** [comment]
I can review it. Is there a deadline?

**Comment by danielskatz** [comment]
Thanks @jteheran - it's an open interactive process, so there's not exactly a deadline,  but we like to have reviewers provide initial feedback in a couple of weeks, if possible

**Comment by danielskatz** [comment]
@whedon add @jteheran as reviewer

**Comment by whedon** [comment]
OK, @jteheran is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1606. Feel free to close this issue now!
