### ISSUE TITLE
[PRE REVIEW]: ClustForOpt: Time-series aggregation for optimization in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1562]
**Submitting author:** @holgerteichgraeber (<a href="http://orcid.org/0000-0002-4061-2226">Holger Teichgraeber</a>)
**Repository:** <a href="https://github.com/holgerteichgraeber/ClustForOpt.jl" target ="_blank">https://github.com/holgerteichgraeber/ClustForOpt.jl</a>
**Version:** v0.4.2
**Editor:** @danielskatz
**Reviewers:** @jgoldfar, @ahwillia

**Author instructions**

Thanks for submitting your paper to JOSS @holgerteichgraeber. **Currently, there isn't an JOSS editor assigned** to your paper.

@holgerteichgraeber if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1562 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01562/joss.01562/10.21105.joss.01562.pdf)

**Comment by holgerteichgraeber** [comment]
> You can help the editor by looking at this list of potential reviewers to identify individuals who might be able to review your submission (please start at the bottom of the list).

Just went through the list. Some ideas for potential reviewers:
- Jgoldfar
- matbesancon
- ChrisRackauckas
- ahwillia

**Comment by arfon** [comment]
:wave: @danielskatz - would you be willing to edit this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @jgoldfar & ChrisRackauckas & @ahwillia - Would two of you be willing to review this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01562/joss.01562/10.21105.joss.01562.pdf)

**Comment by jgoldfar** [comment]
@danielskatz I would be happy to review; this would be my first time doing so but I've long been interested in JOSS.

**Comment by danielskatz** [comment]
Thanks @jgoldfar  - I'll put you in the system, but we won't start the review until I get one more reviewer as well.

**Comment by danielskatz** [comment]
@whedon assign @jgoldfar as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jgoldfar

**Comment by ahwillia** [comment]
I'm traveling for the next few weeks. I can do it in a pinch in ~3 weeks
time. Perhaps wait and see if there's a quicker response from someone
else...

**Comment by danielskatz** [comment]
Thanks @ahwillia - let's see if @ChrisRackauckas (who I didn't tag correctly above - sorry) is willing to review this.

**Comment by danielskatz** [comment]
👋 @ChrisRackauckas  - Would you be willing to review this submission for JOSS?

**Comment by ChrisRackauckas** [comment]
Not right now. If it gets to September and it still needs a review then give me a ping.

**Comment by danielskatz** [comment]
👋 @ahwillia - Given that you've said you can do this in a pinch, I will ask you to do so, recognizing that it won't happen quickly.

**Comment by danielskatz** [comment]
@whedon add @ahwillia as reviewer

**Comment by whedon** [comment]
OK, @ahwillia is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1573. Feel free to close this issue now!
