### ISSUE TITLE
[PRE REVIEW]: MemCNN: a Framework for Developing Memory Efficient Invertible Neural Networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1563]
**Submitting author:** @silvandeleemput (<a href="http://orcid.org/0000-0001-6047-3051">Sil C. van de Leemput</a>)
**Repository:** <a href="https://github.com/silvandeleemput/memcnn" target ="_blank">https://github.com/silvandeleemput/memcnn</a>
**Version:** 0.3.3
**Editor:** @terrytangyuan
**Reviewers:** @GregaVrbancic, @sepandhaghighi

**Author instructions**

Thanks for submitting your paper to JOSS @silvandeleemput. **Currently, there isn't an JOSS editor assigned** to your paper.

@silvandeleemput if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01563/joss.01563/10.21105.joss.01563.pdf)

**Comment by silvandeleemput** [comment]
> @silvandeleemput if you have any suggestions for potential reviewers then please mention them here in this thread.

Going through the list, I would suggest the following reviewers (having a deep learning background and a preference for Python): 

arokem
nilesh-patil
paragkulkarni11
rasbt
sssomani
mamrehn
GregaVrbancic

**Comment by arfon** [comment]
:wave: @terrytangyuan - would you be willing to edit this submission for JOSS?

**Comment by terrytangyuan** [comment]
@whedon assign @terrytangyuan as editor

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by terrytangyuan** [comment]
Thanks @silvandeleemput. Hi, if you are willing to review for this submission, please let us know here! 
@arokem @nilesh-patil @paragkulkarni11 @rasbt @sssomani @mamrehn @GregaVrbancic

**Comment by GregaVrbancic** [comment]
Hi @terrytangyuan, I would be glad to review the submitted paper.

**Comment by terrytangyuan** [comment]
@whedon add @GregaVrbancic as reviewer

**Comment by whedon** [comment]
OK, @GregaVrbancic is now a reviewer

**Comment by terrytangyuan** [comment]
We need another reviewer. 👋 Would any of you be interested? @arokem @nilesh-patil @paragkulkarni11 @rasbt @sssomani @mamrehn

**Comment by arokem** [comment]
Sorry: I am too busy with other papers right now.

**Comment by rasbt** [comment]
Sorry I am currently traveling and won’t be available until mid August

**Comment by terrytangyuan** [comment]
Pulling another set of potential reviewers. Would any of you be interested in reviewing this paper? @paragkulkarni11 @Danbo3004 @sepandhaghighi @EduPH @DanielLenz

**Comment by sepandhaghighi** [comment]
@terrytangyuan 

Hi

I'm available.

**Comment by EduPH** [comment]
Hi,
It depends on how fast you want an answer. I think I could send it back along first week of August.

**Comment by terrytangyuan** [comment]
Thanks! @EduPH I'll keep you in mind for future reviews. 😄

**Comment by terrytangyuan** [comment]
@whedon add @sepandhaghighi as reviewer

**Comment by whedon** [comment]
OK, @sepandhaghighi is now a reviewer

**Comment by terrytangyuan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1576. Feel free to close this issue now!

**Comment by terrytangyuan** [comment]
👋 @sepandhaghighi and @GregaVrbancic, please head over to #1576 to start the review!
