### ISSUE TITLE
[PRE REVIEW]: labor_planner: A Python package for planning and visualizing staff labor allocation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1564]
**Submitting author:** @crvernon (<a href="http://orcid.org/0000-0002-3406-6214">Chris Vernon</a>)
**Repository:** <a href="https://github.com/crvernon/labor_planner" target ="_blank">https://github.com/crvernon/labor_planner</a>
**Version:** v.1.1.1
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @crvernon. **Currently, there isn't an JOSS editor assigned** to your paper.

@crvernon if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01564/joss.01564/10.21105.joss.01564.pdf)

**Comment by arfon** [comment]
@crvernon :wave: thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). In particular, this item:

> - Your software should have an obvious research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)? The section [_'what should my paper contain'_](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) has some guidance for the sort of content we're looking to be present in the `paper.md`.

Many thanks!

**Comment by crvernon** [comment]
@arfon thanks for the lightning fast response!  This software is definitely not the normal "research" software that I am used to creating.  I did think that the `labor_planner` software may be beneficial to the scientific community in terms of ensuring that 1) staff were able to maintain funding throughout the year with out having major fluxes in their hours, and 2) staff were able to maintain a positive work-life balance to be most productive and generally happy.  

I absolutely see you point about having an "obvious research application" and respect your decision regarding the fit of this software in JOSS.  Please let me know if you feel that `labor_planner` would not appeal to JOSS readers and I will kindly withdrawal.

This journal is fantastic and I am excited to publish here in the future!  Thanks and have a great day!

**Comment by arfon** [comment]
Hi @crvernon - thanks for the response. Even though this looks like very useful (and well written) software, unfortunately this submission is out of scope for JOSS.

We'd welcome future submissions that meet our [submission criteria](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).

**Comment by crvernon** [comment]
@arfon thanks for the consideration.  Do I need to do anything to withdraw my submission?  Or do you simply close the issue?  Thanks!

**Comment by arfon** [comment]
> @arfon thanks for the consideration. Do I need to do anything to withdraw my submission? Or do you simply close the issue? Thanks!

No, I can do this for you.
