### ISSUE TITLE
[PRE REVIEW]: kdensity: An R package for kernel density estimation with parametric starts and asymmetric kernels

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1565]
**Submitting author:** @JonasMoss (<a href="http://orcid.org/0000-0002-6876-6964">Jonas Moss</a>)
**Repository:** <a href="https://github.com/JonasMoss/kdensity" target ="_blank">https://github.com/JonasMoss/kdensity</a>
**Version:** v1.0.1
**Editor:** @terrytangyuan
**Reviewers:** @gvegayon

**Author instructions**

Thanks for submitting your paper to JOSS @JonasMoss. **Currently, there isn't an JOSS editor assigned** to your paper.

@JonasMoss if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1565 with the following error: 

 Error producing PDF.
! Undefined control sequence.
l.370 The following example uses the \code

Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @terrytangyuan - would you be willing to edit this submission for JOSS?

**Comment by arfon** [comment]
@JonasMoss - I don't think Pandoc supports `\code`. Can you use back-ticks instead?

**Comment by terrytangyuan** [comment]
@arfon Yes definitely. 

@whedon assign @terrytangyuan as editor

@JonasMoss if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, this list of people have already agreed to review for JOSS and may be suitable for this submission.

**Comment by terrytangyuan** [comment]
@whedon assign @terrytangyuan as editor

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by JonasMoss** [comment]
Changed \code to backticks. I suggest @TrashBirdEcology for reviewing.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01565/joss.01565/10.21105.joss.01565.pdf)

**Comment by TrashBirdEcology** [comment]
@JonasMoss @terrytangyuan Unfortunately I am slammed for the next two weeks. If you OK with waiting for a review I am happy to begin it near or after 01 August.

**Comment by terrytangyuan** [comment]
@TrashBirdEcology Thanks for letting us know. @JonasMoss Could you try finding more reviewers from the list and see if others might have better availability?

**Comment by JonasMoss** [comment]
@TrashBirdEcology thanks! I suggest @gvegayon.

**Comment by terrytangyuan** [comment]
Thanks. Hi @gvegayon, would you be able to review for this paper?

**Comment by gvegayon** [comment]
:wave: @terrytangyuan @JonasMoss, sure, I can help :). My only problem is that I'm on a conference next week, so I can start with the review process on the 22nd. LMK

**Comment by TrashBirdEcology** [comment]
If anything changes please email me (jessicaleighburnett.at.gmail), I am muting this thread, now. Thanks!

**Comment by JonasMoss** [comment]
@gvegayon @terrytangyuan Sounds great to me! Thanks =)

**Comment by terrytangyuan** [comment]
@whedon assign @gvegayon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @gvegayon

**Comment by terrytangyuan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1566. Feel free to close this issue now!

**Comment by terrytangyuan** [comment]
Thanks everyone! @gvegayon Please head over to #1566 for review when you get back.
