### ISSUE TITLE
[REVIEW]: kdensity: An R package for kernel density estimation with parametric starts and asymmetric kernels

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1566]
**Submitting author:** @JonasMoss (<a href="http://orcid.org/0000-0002-6876-6964">Jonas Moss</a>)
**Repository:** <a href="https://github.com/JonasMoss/kdensity" target ="_blank">https://github.com/JonasMoss/kdensity</a>
**Version:** 1.1.0
**Editor:** @terrytangyuan
**Reviewer:** @gvegayon, @TrashBirdEcology
**Archive:** <a href="https://doi.org/10.5281/zenodo.3466547" target="_blank">10.5281/zenodo.3466547</a>

## Status

[![status](http://joss.theoj.org/papers/28cef1f13a184adc6260fc513139c7ef/status.svg)](http://joss.theoj.org/papers/28cef1f13a184adc6260fc513139c7ef)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/28cef1f13a184adc6260fc513139c7ef"><img src="http://joss.theoj.org/papers/28cef1f13a184adc6260fc513139c7ef/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/28cef1f13a184adc6260fc513139c7ef/status.svg)](http://joss.theoj.org/papers/28cef1f13a184adc6260fc513139c7ef)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/JonasMoss/kdensity" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@gvegayon, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @terrytangyuan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JonasMoss/kdensity">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.1.0
- [x] **Authorship:** Has the submitting author (@JonasMoss) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JonasMoss/kdensity">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.1.0
- [x] **Authorship:** Has the submitting author (@JonasMoss) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @gvegayon it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01566/joss.01566/10.21105.joss.01566.pdf)

**Comment by terrytangyuan** [comment]
@TrashBirdEcology I also added you as the reviewer since JOSS now requires at least two reviewers. Feel free to review this paper when you get back. Thanks.

**Comment by terrytangyuan** [comment]
👋 @gvegayon You mentioned that you would be able to start the review on 22nd. Feel free to start the review while @TrashBirdEcology is still traveling.

**Comment by gvegayon** [comment]
OK @JonasMoss @terrytangyuan, I've finished my first round. Overall, everything looks good (very nice job @JonasMoss!), and there are only a few issues that I would like the authors to address. The most important is regarding related R packages.

**Comment by terrytangyuan** [comment]
Thanks @gvegayon! @JonasMoss Could you address those issues pointed out?

**Comment by JonasMoss** [comment]
@terrytangyuan Sure! Thanks a lot @gvegayon

**Comment by JonasMoss** [comment]
@gvegayon Okay! I've addressed the issues. Details are on the Github issues pages.

**Comment by terrytangyuan** [comment]
@gvegayon Please take another look when you get a chance. Also ping @TrashBirdEcology for review when you are back from traveling.

**Comment by TrashBirdEcology** [comment]
Added dependency issue, [issue #56](https://github.com/JonasMoss/kdensity/issues/56)

**Comment by JonasMoss** [comment]
Thanks a lot @TrashBirdEcology ! I've addressed your issues with details on the repository's issues page.

**Comment by terrytangyuan** [comment]
👋  @gvegayon @TrashBirdEcology I think this is ready for another round of review whenever you get a chance. Thanks!

**Comment by gvegayon** [comment]
OK @JonasMoss, the changes look good. Only one minor issue regarding a broken link. Thanks.

**Comment by JonasMoss** [comment]
@gvegayon Great! Fixed it now. =)

**Comment by terrytangyuan** [comment]
@gvegayon @TrashBirdEcology It looks like some items in the review list are not checked yet. Could you take a look? If everything looks good, we can move forward with this submission soon. Thanks.

**Comment by TrashBirdEcology** [comment]
@terrytangyuan done

**Comment by gvegayon** [comment]
Same here @terrytangyuan

**Comment by terrytangyuan** [comment]
Thanks everyone!

@JonasMoss At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

The title of the archive is the same as the JOSS paper title
That the authors of the archive are the same as the JOSS paper authors
I can then move forward with accepting the submission.

**Comment by JonasMoss** [comment]
Thanks! Here's the doi of the Zenodo archive.
10.5281/zenodo.3466547
https://zenodo.org/record/3466547

**Comment by terrytangyuan** [comment]
@whedon set 1.1.0 as version

**Comment by whedon** [comment]
OK. 1.1.0 is the version.

**Comment by terrytangyuan** [comment]
@whedon set 10.5281/zenodo.3466547 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3466547" target="_blank">10.5281/zenodo.3466547</a> is the archive.

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1566 with the following error: 

 pandoc-citeproc: Cannot decode byte '\x20': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by terrytangyuan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1566 with the following error: 

 pandoc-citeproc: Cannot decode byte '\x20': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by terrytangyuan** [comment]
@JonasMoss Could you take a look at your recent changes to see what caused the above compilation failure?

**Comment by JonasMoss** [comment]
I changed the encoding from ANSI to UTF-8 at the Github repo now. 

@whedon generate pdf

**Comment by terrytangyuan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01566/joss.01566/10.21105.joss.01566.pdf)

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- doi:10.1214/aos/1176324627 is OK
- doi:10.1093/biomet/asm068 is OK
- doi:10.1023/A:1004165218295 is OK
- doi:10.1016/S0167-9473(99)00010-9 is OK
- doi:10.1201/9781315140919 is OK
- 10.18637/jss.v084.i05 is OK
- 10.21105/joss.00870 is OK

MISSING DOIs

- None

INVALID DOIs

- doi:10.2307/2346189 is INVALID
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1000

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1000, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by terrytangyuan** [comment]
@JonasMoss Could you fix the invalid DOI shown above?

**Comment by JonasMoss** [comment]
@terrytangyuan Fixed.

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- doi:10.1214/aos/1176324627 is OK
- doi:10.1093/biomet/asm068 is OK
- doi:10.1023/A:1004165218295 is OK
- doi:10.1016/S0167-9473(99)00010-9 is OK
- doi:10.1201/9781315140919 is OK
- 10.18637/jss.v084.i05 is OK
- 10.21105/joss.00870 is OK

MISSING DOIs

- None

INVALID DOIs

- doi:10.2307/2346189 is INVALID
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1001

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1001, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by terrytangyuan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- doi:10.1214/aos/1176324627 is OK
- doi:10.1093/biomet/asm068 is OK
- doi:10.1023/A:1004165218295 is OK
- doi:10.1016/S0167-9473(99)00010-9 is OK
- doi:10.1201/9781315140919 is OK
- 10.18637/jss.v084.i05 is OK
- 10.21105/joss.00870 is OK

MISSING DOIs

- None

INVALID DOIs

- doi:10.2307/2346189 is INVALID
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- doi:10.1214/aos/1176324627 is OK
- doi:10.1093/biomet/asm068 is OK
- doi:10.1023/A:1004165218295 is OK
- doi:10.1016/S0167-9473(99)00010-9 is OK
- doi:10.1201/9781315140919 is OK
- 10.18637/jss.v084.i05 is OK
- 10.21105/joss.00870 is OK

MISSING DOIs

- None

INVALID DOIs

- doi:10.2307/2346189 is INVALID
```

**Comment by terrytangyuan** [comment]
@openjournals/joss-eics Could you take from here? The paper looks good to me. I manually verified that the DOI has been fixed.

**Comment by kyleniemeyer** [comment]
Hi @JonasMoss, not sure if this is causing the whedon error (and if so, why it's only showing up for one of them), but if you look in the list of references, a number of them have repeated "doi:" in the DOIs.

Please remove the extra `doi:` from these references: Chen 1999, Chen 2000, Hjort 1995, Jones 2007, Marron 1994, Silverman 2018 (and any others, if I missed any)

(in other words, change `doi = {doi:10.1214/aos/1176324627}` to just `doi = {10.1214/aos/1176324627}` (e.g.) in the references where applicable.)

**Comment by JonasMoss** [comment]
@kyleniemeyer OK, done it.

The doi 10.2307/2346189 was in fact invalid acccording to doi.org though. I replaced it with the correct doi.

The string "10.2307/2346189" isn't in the paper.bib on the Github repo (i.e. search finds nothing), so it looks like whedon isn't looking at the right place. Perhaps the document must be compiled again?

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01566/joss.01566/10.21105.joss.01566.pdf)

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1214/aos/1176324627 is OK
- 10.1093/biomet/asm068 is OK
- 10.1023/A:1004165218295 is OK
- 10.1016/S0167-9473(99)00010-9 is OK
- 10.1201/9781315140919 is OK
- 10.1111/j.2517-6161.1994.tb02006.x is OK
- 10.18637/jss.v084.i05 is OK
- 10.21105/joss.00870 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@JonasMoss looks to be resolved now!

**Comment by kyleniemeyer** [comment]
@JonasMoss nearly there! I just have one final paper edit: could you add a sentence or two at the beginning of the paper to satisfy this requirement:
> A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.

(from our list of things that JOSS papers [should contain](https://openjournals.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain))

**Comment by JonasMoss** [comment]
@kyleniemeyer OK! We added two sentences to the beginning of the paper now.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01566/joss.01566/10.21105.joss.01566.pdf)

**Comment by kyleniemeyer** [comment]
@JonasMoss thanks! just one minor correction: I think you are missing "R" at near the beginning of the second sentence: "This (R Core Team, 2019) package..." -> "This R (R Core Team, 2019) package..."

**Comment by JonasMoss** [comment]
@kyleniemeyer Thanks. Fixed.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01566/joss.01566/10.21105.joss.01566.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1214/aos/1176324627 is OK
- 10.1093/biomet/asm068 is OK
- 10.1023/A:1004165218295 is OK
- 10.1016/S0167-9473(99)00010-9 is OK
- 10.1201/9781315140919 is OK
- 10.1111/j.2517-6161.1994.tb02006.x is OK
- 10.18637/jss.v084.i05 is OK
- 10.21105/joss.00870 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1004

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1004, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1179821104917028864) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1005
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01566](https://doi.org/10.21105/joss.01566)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @JonasMoss on your article's publication in JOSS!

Many thanks to @gvegayon & @TrashBirdEcology for reviewing, and @terrytangyuan for editing, this submission.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01566/status.svg)](https://doi.org/10.21105/joss.01566)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01566">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01566/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01566/status.svg
   :target: https://doi.org/10.21105/joss.01566
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01566/status.svg)](https://doi.org/10.21105/joss.01566)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by TrashBirdEcology** [comment]
Congrats @JonasMoss !
