### ISSUE TITLE
[PRE REVIEW]: lfda: Local Fisher Discriminant Analysis in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1567]
**Submitting author:** @terrytangyuan (<a href="http://orcid.org/0000-0001-5243-233X">Yuan Tang</a>)
**Repository:** <a href="https://github.com/terrytangyuan/lfda/" target ="_blank">https://github.com/terrytangyuan/lfda/</a>
**Version:** v1.1.2
**Editor:** @arfon
**Reviewers:** @sctyner, @strengejacke

**Author instructions**

Thanks for submitting your paper to JOSS @terrytangyuan. The JOSS editor @arfon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@terrytangyuan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@arfon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01567/joss.01567/10.21105.joss.01567.pdf)

**Comment by arfon** [comment]
:wave: @terrytangyuan - can you suggest some potential reviewers from [this list](https://bit.ly/joss-reviewers)?

**Comment by terrytangyuan** [comment]
Hi, if you’d like to review this submission, please let us know here! @joethorley @corybrunson @sctyner @jacobsoj @strengejacke @hiendn

**Comment by hiendn** [comment]
@terrytangyuan I can review it, but not in the next two weeks. So put me in reserve if no one else can. :)

**Comment by strengejacke** [comment]
I'm on vacation and can start with the review at the beginning of August. If this is ok, I'm happy to review it.

**Comment by corybrunson** [comment]
I would like to complete an ongoing review first. I will check back here when i'm done, though, because i'd certainly be interested in reviewing this one. : )

**Comment by sctyner** [comment]
Looks like you don't need me, but just in case, I'm happy to review.

**Comment by terrytangyuan** [comment]
Looks like @sctyner is the only one who didn't mention any availability so I guess she should be able to review this quicker than anyone else. @corybrunson reviewed for my `autoplotly` JOSS paper before so he should be familiar with some of the related content in this paper. But I'll leave this to our editor @arfon to decide on the reviewers. 👋

**Comment by arfon** [comment]
@whedon add @sctyner as reviewer

**Comment by whedon** [comment]
OK, @sctyner is now a reviewer

**Comment by arfon** [comment]
@whedon add @strengejacke as reviewer

**Comment by whedon** [comment]
OK, @strengejacke is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1572. Feel free to close this issue now!

**Comment by arfon** [comment]
Thanks for all of the quick responses. @sctyner & @strengejacke, see you over in #1572 for the actual review.
