### ISSUE TITLE
[PRE REVIEW]: G3F: Global, Multidimensional Spectral Regression Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1568]
**Submitting author:** @dap-biospec (<a href="http://orcid.org/0000-0003-4625-0323">Denis Proshlyakov</a>)
**Repository:** <a href="https://github.com/dap-biospec/G3F" target ="_blank">https://github.com/dap-biospec/G3F</a>
**Version:** v1.0a4
**Editor:** @kyleniemeyer
**Reviewers:** @tcausgrove, @FaustinCarter

**Author instructions**

Thanks for submitting your paper to JOSS @dap-biospec. **Currently, there isn't an JOSS editor assigned** to your paper.

@dap-biospec if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1568 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1568/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:95:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @dap-biospec - this PR should fix your paper compilation: https://github.com/dap-biospec/G3F/pull/1

**Comment by arfon** [comment]
:wave: @kyleniemeyer - would you be willing to edit this submission for JOSS?

**Comment by dap-biospec** [comment]
@arfon @kyleniemeyer Thank you for patching up the paper!

Below are three suggested reviewers. I have no affiliation with any of them. 

Christopher Neese: physical chemistry, chemical physics, https://electroscience.osu.edu/people/neese.6

Tim Causgrove: chemistry, protein kinetics and thermodynamics http://faculty.tamucc.edu/tcausgrove/Causgrove_Home.html

Tony Withers: geochemistry; equilibrium and dynamics; spectroscopy; - http://www.bgi.uni-bayreuth.de/?page=4&lng=en&mode=s&id=337

**Comment by kyleniemeyer** [comment]
@arfon yep, I'll take this one

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
@dap-biospec could you merge @arfon's PR for your paper fix, so that we can compile it here?

**Comment by dap-biospec** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1568 with the following error: 

 Error reading bibliography ./paper.bib (line 25, column 9):
unexpected "a"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by dap-biospec** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01568/joss.01568/10.21105.joss.01568.pdf)

**Comment by dap-biospec** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01568/joss.01568/10.21105.joss.01568.pdf)

**Comment by dap-biospec** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01568/joss.01568/10.21105.joss.01568.pdf)

**Comment by dap-biospec** [comment]
@kyleniemeyer patch and compilation are done.

**Comment by kyleniemeyer** [comment]
@whedon add @tcausgrove as reviewer

**Comment by whedon** [comment]
OK, @tcausgrove is now a reviewer

**Comment by dap-biospec** [comment]
@tcausgrove, @kyleniemeyer - Documentation has been updated to keep repo transparent. Additional examples are provided in the demo experiment to better illustrate capabilities in three scenarios. A separate performance testing experiment is provided along with the description of testing process and the expected results.

**Comment by kyleniemeyer** [comment]
Hi @FaustinCarter, I realize the submission #1532 is still in progress, but would you also be willing to review this one?

**Comment by FaustinCarter** [comment]
In theory, yes. In practice, it depends on whether I can get IgorPro 8 to give me another trial period. I have an older license, but this code does not appear to be backwards compatible. Give me a couple days and I'll have a definite. If you find a different reviewer in the meantime, that is also fine.

**Comment by dap-biospec** [comment]
@FaustinCarter - I would greatly appreciate it. Please let me know if we can help you with IgorPro 8 in any way. For example, we can set up a remote desktop to one of our computers with IgorPro running site license. I can also reach out to Wavemetrics if you would like.

**Comment by FaustinCarter** [comment]
Either one of those sound like reasonable options to me. If you can make
one of them work I'm on board.

**Comment by dap-biospec** [comment]
@FaustinCarter  I am asking our IT staff to set up a limited time VPN access for you (I have control of my group our workstations). What email address would you like to use? It would be better if it is more official than GMail (not for me, for administration). If you do not want to post it here, email me directly at dapro@chemistry.msu.edu. 

Thanks for understanding!

**Comment by kyleniemeyer** [comment]
Great, thanks @FaustinCarter and @dap-biospec for working something out! I'll go ahead and add you as a reviewer and we can get the formal review started.

**Comment by kyleniemeyer** [comment]
@whedon add @FaustinCarter as reviewer

**Comment by whedon** [comment]
OK, @FaustinCarter is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1629. Feel free to close this issue now!
