### ISSUE TITLE
[PRE REVIEW]: SG-t-SNE-Π: Swift Neighbor Embedding of Sparse Stochastic Graphs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1569]
**Submitting author:** @pitsianis (<a href="http://orcid.org/0000-0002-7353-3524">Nikos Pitsianis</a>)
**Repository:** <a href="https://github.com/fcdimitr/sgtsnepi" target ="_blank">https://github.com/fcdimitr/sgtsnepi</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewers:** @tingyu66, @rioyokota

**Author instructions**

Thanks for submitting your paper to JOSS @pitsianis. **Currently, there isn't an JOSS editor assigned** to your paper.

@pitsianis if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1569 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @labarba - would you be able to edit this submission for JOSS?

**Comment by arfon** [comment]
:wave: @pitsianis  - this PR should fix your paper compilation: https://github.com/fcdimitr/sgtsnepi/pull/1

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01569/joss.01569/10.21105.joss.01569.pdf)

**Comment by labarba** [comment]
> 👋 @labarba - would you be able to edit this submission for JOSS?

I could try, although I am not familiar with graph analysis. This looks like heavy duty computer science, and I might have a hard time finding reviewers. Could @jedbrown or @poulson pitch in here, to see if they would be in a better to edit?

**Comment by labarba** [comment]
@pitsianis — Could you take a stab at improving the paper's readability for a non-specialist? Note that our [documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) requests that you include: 

- a summary describing high-level functionality and purpose of the software for a diverse, non-specialist audience;
- a clear statement of need that illustrates the research application of the software (including references to other software meeting similar needs).

**Comment by pitsianis** [comment]
Hello there,

Thank you @afron for fixing the pdf generation.

Dear @labarba, I would like to propose Rio Yokota (rioyokota@gsic.titech.ac.jp) as a reviewer. He is very familiar with the methodologies and prior art in this field (N-body, Barnes Hut method) and he will appreciate our improvements.

**Comment by pitsianis** [comment]
> @pitsianis — Could you take a stab at improving the paper's readability for a non-specialist? 

Thank you @labarba for the quick feedback. We have rewritten the summary accordingly. Your comments are greatly appreciated.

**Comment by pitsianis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01569/joss.01569/10.21105.joss.01569.pdf)

**Comment by pitsianis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01569/joss.01569/10.21105.joss.01569.pdf)

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@whedon assign @tingyu66 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @tingyu66

**Comment by labarba** [comment]
👋 @tingyu66 — Thank you for agreeing to review this submission for JOSS. You can start the review, but please wait for me to find another reviewer and start the review issue before posting your comments. Stay tuned!

**Comment by labarba** [comment]
@whedon add @rioyokota as reviewer

**Comment by whedon** [comment]
OK, @rioyokota is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1577. Feel free to close this issue now!
