### ISSUE TITLE
[PRE REVIEW]: bíogo/hts: high throughput sequence handling for the Go language

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#157]
**Submitting author:** @kortschak (<a href="http://orcid.org/0000-0001-8295-2301">Robert Daniel Kortschak</a>)
**Repository:** <a href="https://github.com/biogo/hts" target ="_blank">https://github.com/biogo/hts</a>
**Version:** v1.0.0
**Editor:** @pjotrp
**Reviewer:** @sb10

**What this issue is for**

Thanks for submitting your paper to JOSS kortschak. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @pjotrp - would you be willing to edit this submission for JOSS too? It's from the same authors as #154

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
Dear Robert,

Thank you for submitting and sorry for the delay in review. I'll look for a reviewer. Meanwhile, can you look at some of the accepted papers to put in some more information - like proper citations? http://joss.theoj.org/papers/popular. Also a note on relevance, performance and explaining what SAM/BAM/CRAM is would be helpful to readers. Not asking you to do a lot of work, but take a cue from other papers.

Pjotr

**Comment by kortschak** [comment]
@pjotrp, thank you.

I am sort of at a loss to know how to address that. The SAM specification has no proper citation (no DOI as far as I know). Part of the issue here is that there are not good metrics to cover what we are aiming for here - reviewability of code without significant performance loss. Also note that we don't cover CRAM at this stage.

@brentp do you have any input on performance numbers? I know you've been making significant improvments there. So can you make comparisons under your workloads with samtools or other?

Dan

**Comment by pjotrp** [comment]
@kortschak I would check the samtools and sambamba papers - both bind to htslib

@brentp Brad has suggested you as a reviewer - would you be willing to take that on?

**Comment by pjotrp** [comment]
@kortschak I would check the samtools and sambamba papers - both bind to htslib

**Comment by pjotrp** [comment]
@sb10 would you be willing to review this paper?

**Comment by sb10** [comment]
Yes, I can review it. Do I do the "whedon assign @username as reviewer" command, or do you?

**Comment by brentp** [comment]
re performance (and utility) I just now wrote, in 30 minutes a simple program using biogo/hts to replicate the functionality in samtools flagstat:
https://gist.github.com/brentp/731895435be04f7d69ec69a6c2fcd008

On my machine, samtools flagstat takes 10.3 seconds.

the biogo/hts program takes 13.1 seconds. If I change (a single character) to allow it to use 2 cpus, then it take 8.4 seconds.

**Comment by pjotrp** [comment]
whedon assign @sb10 as reviewer

**Comment by pjotrp** [comment]
@whedon assign @sb10 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sb10

**Comment by kortschak** [comment]
@brentp If you would send a PR of that code to add it to biogo/hts/paper/examples or similar that would be good. Thanks.

**Comment by arfon** [comment]
@pjotrp - looks like we're good to open up the review issue at this point? If so then you'll need this command to create the review issue (with checklist etc):

```
> @whedon start review magic-word=bananas
```

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/168. Feel free to close this issue now!
