### ISSUE TITLE
[REVIEW]: phasespace: $n$-body phase space generation in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1570]
**Submitting author:** @apuignav (<a href="http://orcid.org/0000-0001-8868-2947">Albert Puig Navarro</a>)
**Repository:** <a href="https://github.com/zfit/phasespace/" target ="_blank">https://github.com/zfit/phasespace/</a>
**Version:** 1.0.2
**Editor:** @poulson
**Reviewer:** @mdoucet, @stuartcampbell, @vyasr
**Archive:** <a href="https://doi.org/10.5281/zenodo.2591993" target="_blank">10.5281/zenodo.2591993</a>

## Status

[![status](http://joss.theoj.org/papers/8d627191394fa68c607459480e0b4b6f/status.svg)](http://joss.theoj.org/papers/8d627191394fa68c607459480e0b4b6f)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/8d627191394fa68c607459480e0b4b6f"><img src="http://joss.theoj.org/papers/8d627191394fa68c607459480e0b4b6f/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/8d627191394fa68c607459480e0b4b6f/status.svg)](http://joss.theoj.org/papers/8d627191394fa68c607459480e0b4b6f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/zfit/phasespace/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mdoucet & @stuartcampbell & @vyasr, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @poulson know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/zfit/phasespace/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0.2)?
- [x] **Authorship:** Has the submitting author (@apuignav) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/zfit/phasespace/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0.2)?
- [x] **Authorship:** Has the submitting author (@apuignav) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/zfit/phasespace/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0.2)?
- [x] **Authorship:** Has the submitting author (@apuignav) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mdoucet, @stuartcampbell, @vyasr it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01570/joss.01570/10.21105.joss.01570.pdf)

**Comment by apuignav** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01570/joss.01570/10.21105.joss.01570.pdf)

**Comment by apuignav** [comment]
Fixed a couple of typography issues, now it's good to go!

**Comment by vyasr** [comment]
Additional notes relating to my review:
* I don't think most of the elements added to setup_requires are actually necessary for users (e.g. sphinx, bumpversion, wheel, twine, etc). I would remove those that the user shouldn't actually need. Developers can install those as needed.
* A few tests currently fail because they're referring to nonexistent files. Based on your documentation, these tests (in `test_physics.py`) are the ones that are meant to test against external codes. If the outputs are being stored as artifacts directly on your testing servers or something similar, I would suggest using e.g. `pytest.mark.skip` if not on CI to avoid users seeing a failure.
* Although they are internal methods, they're doing the bulk of the work it seems like, so I would like to see some documentation of the `_generate` and `_recursive_generate` functions for the sake of future developers.

Once these requests are addressed, I can review the actual paper as well.

**Comment by mdoucet** [comment]
I'm done with my review. The code does what it says it does. I could run the code, generate decays and check that the 4-momentum vectors and invariant mass of the results made sense. I only wish that functionality to deal with decay widths, along the lines of the helper code in `tests/helpers/decays.py`, would be part of the main code.

**Comment by mayou36** [comment]
> * I don't think most of the elements added to setup_requires are actually necessary for users (e.g. sphinx, bumpversion, wheel, twine, etc). I would remove those that the user shouldn't actually need. Developers can install those as needed.

I agree, removed

> * A few tests currently fail because they're referring to nonexistent files. Based on your documentation, these tests (in `test_physics.py`) are the ones that are meant to test against external codes. If the outputs are being stored as artifacts directly on your testing servers or something similar, I would suggest using e.g. `pytest.mark.skip` if not on CI to avoid users seeing a failure.
> * Although they are internal methods, they're doing the bulk of the work it seems like, so I would like to see some documentation of the `_generate` and `_recursive_generate` functions for the sake of future developers.

Fixed the CI (there was a problem with uploading the large files to the CI)

**Comment by mayou36** [comment]
> I'm done with my review.

Thanks a lot for that!

> I only wish that functionality to deal with decay widths, along the lines of the helper code in `tests/helpers/decays.py`, would be part of the main code.

This is intentionally not part of the package. phasespace aims to only provide the decay mechanics and leaves other things to other libraries, since there are enough around that are quite suitable for that. E.g. using `tensorflow_probability` with it's distributions and the `particle`-package for the particles characteristics works already well. And there is an example also provided in the docs that can be copy-pasted basically.

So from our point of view, the additional maintenance and design effort is simply not worth it.

**Comment by poulson** [comment]
Hi @vyasr: How do you feel your requests are progressing?

**Comment by apuignav** [comment]
@vyasr I think it makes sense, although the documentation is mainly included in the "parent" methods. We'll add docs to clarify better so it's more developer-friendly.

**Comment by apuignav** [comment]
@vyasr Docs have been updated!

**Comment by vyasr** [comment]
Looks good! I'm all set with my review now.

One minor tip, the docstrings are pretty inconsistent with using `tensor`, `Tensor`, and `tf.Tensor`. If you consistently refer to `tensorflow.Tensor` using the fully qualified name (it might be possible to use aliases, I haven't tried) you can take advantage of [Intersphinx](http://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) to get links to show up in your documentation.

**Comment by poulson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01570/joss.01570/10.21105.joss.01570.pdf)

**Comment by poulson** [comment]
The preprint looks good!

**Comment by poulson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/S0168-9002(97)00048-X is OK
- 10.1016/j.cpc.2017.01.029 is OK
- 10.5281/zenodo.2602043 is OK
- 10.5281/zenodo.2591993 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by poulson** [comment]
@whedon set 10.5281/zenodo.2591993 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2591993" target="_blank">10.5281/zenodo.2591993</a> is the archive.

**Comment by poulson** [comment]
:wave: @openjournals/joss-eics, this submission looks ready to be accepted.

**Comment by labarba** [comment]
Before continuing, @apuignav, please edit the metadata of the Zenodo archive so the author list and title matches the JOSS paper.

**Comment by apuignav** [comment]
Should be done. I don't know why zenodo deletes all the info whenever a new release happens :-(

**Comment by apuignav** [comment]
Hey! Is there anything missing from our side? I have not been following closely lately.

**Comment by danielskatz** [comment]
👋 @apuignav - sorry for the delay - I think you hit a shift change of Associated-Editor-in-Chiefs.

**Comment by danielskatz** [comment]
Can you merge some minor changes in the paper: https://github.com/zfit/phasespace/pull/32 ?

**Comment by apuignav** [comment]
Done! Thanks for the fixes!

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/S0168-9002(97)00048-X is OK
- 10.1016/j.cpc.2017.01.029 is OK
- 10.5281/zenodo.2602043 is OK
- 10.5281/zenodo.2591993 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1059

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1059, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
👋 @arfon - note that we have a problem with the title in the xml, due to the greek character, I assume. Your thoughts?

**Comment by arfon** [comment]
Hrm, looks like Whedon is stripping this out. Feel free to accept here and I'll update the Crossref metadata manually after you accept.

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1189146263603818497) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1060
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01570](https://doi.org/10.21105/joss.01570)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
@arfon - please do your crossref-latex magic :)  And then please close this when everything seems to be right

**Comment by danielskatz** [comment]
Thanks to @mdoucet, @stuartcampbell, @vyasr for reviewing!
And to @poulson for editing!

**Comment by arfon** [comment]
> @arfon - please do your crossref-latex magic :) And then please close this issue when everything seems to be right

OK, fixed up the metadata and opened https://github.com/openjournals/whedon/issues/59 to track this.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01570/status.svg)](https://doi.org/10.21105/joss.01570)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01570">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01570/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01570/status.svg
   :target: https://doi.org/10.21105/joss.01570
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01570/status.svg)](https://doi.org/10.21105/joss.01570)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by apuignav** [comment]
Thank you very much to everybody for the review!
