### ISSUE TITLE
[PRE REVIEW]: cspy: A Python package with a collection of algorithms for the (Resource) Constrained Shortest Path problem

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1571]
**Submitting author:** @torressa (<a href="http://orcid.org/0000-0002-2894-9432">David Torres Sanchez</a>)
**Repository:** <a href="https://github.com/torressa/cspy" target ="_blank">https://github.com/torressa/cspy</a>
**Version:** v0.0.8
**Editor:** @poulson
**Reviewers:** @hausen, @oesteban, @stsievert

**Author instructions**

Thanks for submitting your paper to JOSS @torressa. **Currently, there isn't an JOSS editor assigned** to your paper.

@torressa if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1571 with the following error: 

 Error reading bibliography ./paper.bib (line 13, column 3):
unexpected "a"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
👋 @poulson - you've been requested as the editor - are you willing to serve as such?

**Comment by danielskatz** [comment]
👋 @torressa - I think https://github.com/torressa/cspy/pull/12 will fix the build error.  Please merge it and then in a new comment here, enter ```@whedon generate pdf``` Please iterate until the paper builds :)

**Comment by torressa** [comment]
Thanks @danielskatz :)

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01571/joss.01571/10.21105.joss.01571.pdf)

**Comment by torressa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01571/joss.01571/10.21105.joss.01571.pdf)

**Comment by danielskatz** [comment]
👋 @poulson - you've been requested as the editor - are you willing to serve as such?

**Comment by poulson** [comment]
Hi @danielskatz -- I am able to serve as an editor and apologize for the delay.

**Comment by poulson** [comment]
@whedon assign @poulson as editor

**Comment by whedon** [comment]
OK, the editor is @poulson

**Comment by poulson** [comment]
Hi Camille (@camillescott) -- Given your expertise in C++ and Cython, as well as graphs, complex networks, and workflows, I think you would be an ideal reviewer for this submission. Would you have the time and interest in doing so?

Hi Rodrigo (@hausen) -- Given your expertise in C++, combinatorics, and graph theory, I believe you would be of great help in reviewing the C++ and graph analysis sides of this submission. Do you happen to have the time and interest to serve in this review process?

Hi Valentino (@vc1492a) -- Given your python expertise, as well as your background in graph analysis and complex networks, I believe you would be a perfect complement to Rodrigo's potential C++ focus. Would you have the time and bandwidth to serve in this process?

Hi @gabrielspadon -- You listed very similar expertise as Valentino, and I believe you would similarly be a perfect complement to the C++ expertise of Rodrigo in this review. Do you have the time and interest to help with the review?

**Comment by hausen** [comment]
@poulson , I'll be glad to help!

**Comment by poulson** [comment]
@whedon add @hausen as reviewer

**Comment by whedon** [comment]
OK, @hausen is now a reviewer

**Comment by poulson** [comment]
Sorry for the spam. Editing from my phone is dangerous!

**Comment by vc1492a** [comment]
@poulson thanks for the consideration! Unfortunately I don't really have the bandwidth to perform any reviews at this time. Best of luck, I took a peek at the package and it looks like it would have made for an interesting review.

**Comment by poulson** [comment]
Hi Camille (@camillescott) -- Given your expertise in C++ and Cython, as well as graphs, complex networks, and workflows, I think you would be an ideal reviewer for this submission. Would you have the time and interest in doing so?

Hi @gabrielspadon -- You listed very similar expertise as Valentino, and I believe you would similarly be a perfect complement to the C++ expertise of Rodrigo in this review. Do you have the time and interest to help with the review?

**Comment by torressa** [comment]
Based on the expertise listed in the database, I would suggest the following reviewers:
@stsievert 
@oesteban
@sarats 
@andim 
@sjvrijn

**Comment by poulson** [comment]
Hi Scott (@stsievert): I apologize if I've asked you to review too many times, but you were recommended as a relevant reviewer for this paper. Would you have the time and interest in doing so?

Hi Oscar (@oesteban): David recommended you as a reviewer for this paper; would you be interested and confident in serving as a reviewer?

Hi Sarat (@sarats): You were recommended as an expert reviewer for this paper on Constrained Shortest Path problems: do you have the time and interest to serve as a reviewer?

This corresponding repository is available here:
https://github.com/torressa/cspy

**Comment by oesteban** [comment]
Hi @poulson, I'd love to review this submission, but I'm currently swamped and also 2 days away from a break period. Sorry I have to decline. Good luck with this submission @torressa !

**Comment by stsievert** [comment]
I can review this. I have moderate interest, but no experience in shortest path algorithms. I can reserve some time for this.

**Comment by poulson** [comment]
Thank you Oscar (@oesteban) and Scott (@stsievert). I will go ahead and add you two and start the review. Moderate interest is...an interesting way to put it...but I don't want to delay the review any further.

**Comment by poulson** [comment]
@whedon add @oesteban as reviewer

**Comment by whedon** [comment]
OK, @oesteban is now a reviewer

**Comment by poulson** [comment]
@whedon add @stsievert as reviewer

**Comment by whedon** [comment]
OK, @stsievert is now a reviewer

**Comment by poulson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1655. Feel free to close this issue now!
