### ISSUE TITLE
[REVIEW]: lfda: Local Fisher Discriminant Analysis in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1572]
**Submitting author:** @terrytangyuan (<a href="http://orcid.org/0000-0001-5243-233X">Yuan Tang</a>)
**Repository:** <a href="https://github.com/terrytangyuan/lfda/" target ="_blank">https://github.com/terrytangyuan/lfda/</a>
**Version:** v1.1.2
**Editor:** @arfon
**Reviewer:** @sctyner, @strengejacke
**Archive:** <a href="https://doi.org/10.5281/zenodo.3352038" target="_blank">10.5281/zenodo.3352038</a>

## Status

[![status](http://joss.theoj.org/papers/f18fd3cf5e04fb6f25e26323e048a651/status.svg)](http://joss.theoj.org/papers/f18fd3cf5e04fb6f25e26323e048a651)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f18fd3cf5e04fb6f25e26323e048a651"><img src="http://joss.theoj.org/papers/f18fd3cf5e04fb6f25e26323e048a651/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f18fd3cf5e04fb6f25e26323e048a651/status.svg)](http://joss.theoj.org/papers/f18fd3cf5e04fb6f25e26323e048a651)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/terrytangyuan/lfda/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sctyner & @strengejacke, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/terrytangyuan/lfda/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.1.2)?
- [x] **Authorship:** Has the submitting author (@terrytangyuan) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/terrytangyuan/lfda/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.1.2)?
- [x] **Authorship:** Has the submitting author (@terrytangyuan) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @sctyner, @strengejacke it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01572/joss.01572/10.21105.joss.01572.pdf)

**Comment by arfon** [comment]
Note for myself here that @strengejacke won't be able to start this review until early August.

**Comment by sctyner** [comment]
The repository does not pass the License and Version general checks. Issue [here](https://github.com/terrytangyuan/lfda/issues/22).

**Comment by sctyner** [comment]
@arfon I have a question about authorship. The DESCRIPTION file of the R package list the Authors as, "Yuan Tang. Contributions from Wenxuan Li, Nan Xiao and Zachary Deane-Mayer." However, only Yuan Tang and Wenxuan Li are listed as authors in the [paper.md](https://github.com/terrytangyuan/lfda/blob/master/paper/paper.md) file. Does one or both of these need to change in order to be acceptable? Based on my reading of the submission requirements and checklist above, it seems that the authors on the paper should include all four names given in the description file. What is correct? Thanks in advance for your guidance.

**Comment by terrytangyuan** [comment]
@sctyner I've fixed the issue with the license. Regarding the other issue with the version, I was hoping to release v1.1.3 on Github and on CRAN after the paper got accepted so I could include the full version of the paper as part of the release. @arfon Could you double check to see if this is the right process?

Regarding the author names, I asked Nan before and he preferred not to be included since he did not contribute much. Zachary helped with the CI but never heard of him afterwards (I sent an email earlier to express my willingness to include him as co-author but he hasn't responded for years).

**Comment by sctyner** [comment]
There are six empty tests. Issue [here](https://github.com/terrytangyuan/lfda/issues/23)

**Comment by terrytangyuan** [comment]
@sctyner Could you elaborate on what you meant by “empty tests”? Those are testing the exposed core functions from the package, e.g. lfda(), klfda(), etc.

**Comment by terrytangyuan** [comment]
@sctyner Thanks. Just saw your reply on the issue. BTW, I changed the version back to v1.1.2 in DESCRIPTION so this should no longer be an issue.

**Comment by sctyner** [comment]
Ok, I am pretty much done. The automated tests and hearing from @arfon about the versioning are the only unresolved things.

**Comment by terrytangyuan** [comment]
@sctyner Just fixed the issue with tests. Regarding the versioning, I fixed the version number in `DESCRIPTION` file so I think it should be fine now. Please let me know if there's anything else I should resolve. Thank you!

**Comment by sctyner** [comment]
My review is complete.

**Comment by strengejacke** [comment]
I have opened several issues (https://github.com/terrytangyuan/lfda/issues) that need to be addressed, some of them are required to complete my review.

I think the submission is well prepared, so I would consider the issues as minor changes.

**Comment by terrytangyuan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01572/joss.01572/10.21105.joss.01572.pdf)

**Comment by terrytangyuan** [comment]
@strengejacke Thanks for your review! I have addressed all the issues. Please let me know if there's anything else I need to resolve.

**Comment by strengejacke** [comment]
Thanks, all my raised issues have been addressed satisfactorily.

@arfon I recommend publication.

**Comment by sctyner** [comment]
@arfon I also recommend publication.

**Comment by arfon** [comment]
> Thanks, all my raised issues have been addressed satisfactorily.

> @arfon I also recommend publication.

Wonderful, thanks @strengejacke and @sctyner. Apologies for being absent over the last few days - I've been taking a few days vacation but it looks like things have been progressing nicely here :grin:

**Comment by arfon** [comment]
@terrytangyuan - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by terrytangyuan** [comment]
Thanks @strengejacke and @sctyner for your review! 

@arfon Here’s the DOI: 10.5281/zenodo.3352038

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3352038 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3352038" target="_blank">10.5281/zenodo.3352038</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/870

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/870, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1156105341597376512) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/871
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01572](https://doi.org/10.21105/joss.01572)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@sctyner, @strengejacke - many thanks for your reviews here ✨ 

@terrytangyuan - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01572/status.svg)](https://doi.org/10.21105/joss.01572)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01572">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01572/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01572/status.svg
   :target: https://doi.org/10.21105/joss.01572
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01572/status.svg)](https://doi.org/10.21105/joss.01572)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by terrytangyuan** [comment]
🎉 Thanks @arfon for editing and @sctyner @strengejacke for the review!
