### ISSUE TITLE
[REVIEW]: TimeSeriesClustering: An extensible framework in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1573]
**Submitting author:** @holgerteichgraeber (<a href="http://orcid.org/0000-0002-4061-2226">Holger Teichgraeber</a>)
**Repository:** <a href="https://github.com/holgerteichgraeber/TimeSeriesClustering.jl" target ="_blank">https://github.com/holgerteichgraeber/TimeSeriesClustering.jl</a>
**Version:** v0.5.2
**Editor:** @danielskatz
**Reviewer:** @jgoldfar, @ahwillia
**Archive:** <a href="https://doi.org/10.5281/zenodo.3385349" target="_blank">10.5281/zenodo.3385349</a>

## Status

[![status](http://joss.theoj.org/papers/e3975d642975a19f5e2d7e43e3752066/status.svg)](http://joss.theoj.org/papers/e3975d642975a19f5e2d7e43e3752066)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/e3975d642975a19f5e2d7e43e3752066"><img src="http://joss.theoj.org/papers/e3975d642975a19f5e2d7e43e3752066/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/e3975d642975a19f5e2d7e43e3752066/status.svg)](http://joss.theoj.org/papers/e3975d642975a19f5e2d7e43e3752066)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/holgerteichgraeber/ClustForOpt.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jgoldfar & @ahwillia, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/holgerteichgraeber/ClustForOpt.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.5.2
- [x] **Authorship:** Has the submitting author (@holgerteichgraeber) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/holgerteichgraeber/ClustForOpt.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.5.2
- [x] **Authorship:** Has the submitting author (@holgerteichgraeber) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jgoldfar, @ahwillia it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01573/joss.01573/10.21105.joss.01573.pdf)

**Comment by danielskatz** [comment]
Note: @ahwillia is traveling for the next few weeks. It will be about 3 weeks until he can work on this review.

**Comment by danielskatz** [comment]
👋 @jgoldfar, @ahwillia - We'll do the review here - please read the comments above, and get started when you can.  If you have any questions, please ask.

**Comment by holgerteichgraeber** [comment]
> 👋 @jgoldfar, @ahwillia - We'll do the review here - please read the comments above, and get started when you can. If you have any questions, please ask.

👋Thank you all for offering to review, I look forward to your comments. 
Tagging along co-authors @YoungFaithful and @arbrandt for reference.

**Comment by danielskatz** [comment]
👋 @jgoldfar - have you had a chance to get started?

**Comment by jgoldfar** [comment]
Yes; I will post my review within a few days

**Comment by danielskatz** [comment]
@whedon remind @ahwillia in 7 days

**Comment by whedon** [comment]
Reminder set for @ahwillia in 7 days

**Comment by danielskatz** [comment]
> Yes; I will post my review within a few days

@jgoldfar - any update on this?

**Comment by ahwillia** [comment]
Looking through this now. I'm generally very impressed and think we should be able to approve this in short order. I am confirming that I can install and execute the package now.

My biggest piece of feedback is that the README and description of the package should emphasize even more applications. I think this package will be **broadly** useful to many fields! For example, the first sentence of the README might lead users to think the package is for a very specialized purpose I would recommend editing to something like...

**Current:** "ClustForOpt is a julia implementation of unsupervised machine learning methods for finding representative periods for energy systems optimization problems."

**Revised:** "ClustForOpt is a julia implementation of unsupervised machine learning methods for *detecting motifs, clustering, and quantifying similarity between time series datasets*."

Likewise, in the subsequent paragraphs, I recommend adding some more example applications with citations. Segmentation and clustering of audio datasets should be an easy one to find.

It is of course okay to say something like *"this package was **originally** developed for energy systems optimization"* but I think emphasizing the generality of the package and the methods as much as possible will increase the impact of this work.

Full disclosure, I've worked on using very simple time warping methods for neural data (https://www.biorxiv.org/content/10.1101/661165v1), though those data show very different statistics and call for different modeling approaches. But I'm quite enthusiastic about this area of research.

**Comment by ahwillia** [comment]
One final thought, I don't insist on changing the name of the repo, but something like "TimeSeriesClustering.jl" would seem to better capture the function of the package. The name ClustForOpt doesn't make it super clear what the package does...

Also can the authors comment on the differences between this package and other time series packages in julia (e.g `TimeSeries.jl`) in the paper / README? It would be nice to give users more guidance on the broader tools available in Julia for these kinds of modeling problems.

**Comment by whedon** [comment]
:wave: @ahwillia, please update us on how your review is going.

**Comment by holgerteichgraeber** [comment]
Thank you for your feedback, these are great ideas! I am out for the weekend, and will get back to this next week.

**Comment by holgerteichgraeber** [comment]
In case that there are any papers that you can recommend to read in the suggested application areas, suggestions are greatly appreciated.

**Comment by danielskatz** [comment]
👋 @jgoldfar, @ahwillia - can you please use your checklists above to indicate what you think is ok, and what needs to be done, in addition to the comments @ahwillia has posted in this thread, and what I expect @jgoldfar to post soon.

**Comment by ahwillia** [comment]
Checked my boxes...

> @holgerteichgraeber 
>In case that there are any papers that you can recommend to read in the suggested application areas, suggestions are greatly appreciated.

Eamonn Keogh has a variety of methods and application papers to check out (e.g. https://www.cs.ucr.edu/~eamonn/MatrixProfile.html). I'm sure many other research groups have relevant papers as well. Please don't worry about being comprehensive, but the more references you can find the better.

**Comment by danielskatz** [comment]
👋 @jgoldfar

> Yes; I will post my review within a few days

Can you please go ahead and do this? (and check the boxes for items that are complete)

**Comment by holgerteichgraeber** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01573/joss.01573/10.21105.joss.01573.pdf)

**Comment by holgerteichgraeber** [comment]
> 
> 
> @whedon generate pdf from branch paper

Ok, that seems not to have worked. Will push to master branch and revisit. 

I will be updating the package to reflect its more general applicability and rename to TimeSeriesClustering.jl. I will update here once complete.

**Comment by holgerteichgraeber** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1573 with the following error: 

 Error reading bibliography ./paper.bib (line 344, column 1):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by holgerteichgraeber** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1573 with the following error: 

 Error reading bibliography ./paper.bib (line 344, column 1):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by holgerteichgraeber** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01573/joss.01573/10.21105.joss.01573.pdf)

**Comment by holgerteichgraeber** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01573/joss.01573/10.21105.joss.01573.pdf)

**Comment by holgerteichgraeber** [comment]
I am in the process of renaming the package. There is no documentation on how to do that with the new package registry in julia, so I opened an issue in the general registry. Will update here as soon as `TimeSeriesClustering.jl` is officially registered. 

@danielskatz would the name of this issue and the repository name at the top need to be updated?

**Comment by danielskatz** [comment]
Sorry for the delay - I'm on vacation and just scanning things, and missed this.

But the answer is that we can do what's needed - I'm fairly sure that we will need to change the repo URL in this issue, and we will probably change the name of the issue as well.

**Comment by danielskatz** [comment]
👋 @jgoldfar

> Yes; I will post my review within a few days

Can you please go ahead and do this? (and check the boxes for items that are complete)

**Comment by danielskatz** [comment]
@arfon - note that this has been renamed - do we need to do anything to tell whedon this, or in an internal database?

**Comment by danielskatz** [comment]
👋 @jgoldfar, @ahwillia - can you confirm that you are happy with this now?

**Comment by arfon** [comment]
> @arfon - note that this has been renamed - do we need to do anything to tell whedon this, or in an internal database?

The repository has been renamed or the paper, or both?

**Comment by holgerteichgraeber** [comment]
> 
> 
> > @arfon - note that this has been renamed - do we need to do anything to tell whedon this, or in an internal database?
> 
> The repository has been renamed or the paper, or both?

Both the paper and the repository (and thus also the link to the repository: https://github.com/holgerteichgraeber/TimeSeriesClustering.jl )

**Comment by arfon** [comment]
Got it, thanks. I've updated the links in the JOSS database.

**Comment by ahwillia** [comment]
> 👋 @jgoldfar, @ahwillia - can you confirm that you are happy with this now?

Yes this looks good to me!

**Comment by danielskatz** [comment]
I've suggested some minor grammar changes in https://github.com/holgerteichgraeber/TimeSeriesClustering.jl/pull/118

**Comment by danielskatz** [comment]
Also, please make an archive of the repo in an archival repository (e.g., zenodo), and let me know the DOI of the archive, as well as the current version number

**Comment by jgoldfar** [comment]
Looks good to me as well.

**Comment by holgerteichgraeber** [comment]
The current version number is `v0.5.2` and the zenodo DOI is `10.5281/zenodo.3385349` .

**Comment by holgerteichgraeber** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01573/joss.01573/10.21105.joss.01573.pdf)

**Comment by holgerteichgraeber** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01573/joss.01573/10.21105.joss.01573.pdf)

**Comment by holgerteichgraeber** [comment]
> 
> 
> The current version number is `v0.5.2` and the zenodo DOI is `10.5281/zenodo.3385349` (https://doi.org/10.5281/zenodo.3385349).

@danielskatz just following up, this may have gotten lost among the other messages.

**Comment by danielskatz** [comment]
thanks - sorry I missed that

**Comment by danielskatz** [comment]
@whedon set v0.5.2 as version

**Comment by whedon** [comment]
OK. v0.5.2 is the version.

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3385349 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3385349" target="_blank">10.5281/zenodo.3385349</a> is the archive.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/950

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/950, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.apenergy.2019.02.012 is OK
- 10.21105/joss.01230 is OK
- 10.18637/jss.v062.i01 is OK
- 10.18637/jss.v031.i07 is OK
- 10.21105/joss.01504 is OK
- 10.5281/zenodo.2547683 is OK
- 10.21105/joss.00825 is OK
- 10.1016/j.energy.2017.09.087 is OK
- 10.1016/j.energy.2017.11.059 is OK
- 10.1016/j.energy.2017.06.082 is OK
- 10.1016/j.renene.2017.10.017 is OK
- 10.1016/j.energy.2016.06.081 is OK
- 10.1016/j.apenergy.2017.03.051 is OK
- 10.1109/IEVC.2012.6183283 is OK
- 10.1016/j.compchemeng.2009.10.009 is OK
- 10.1137/15M1020575 is OK
- 10.1137/141000671 is OK
- 10.1016/j.is.2015.04.007 is OK
- 10.1016/j.patcog.2005.01.025 is OK
- 10.1016/j.engappai.2010.09.007 is OK
- 10.1137/1.9781611972795.41 is OK
- 10.1186/1471-2105-8-S7-S21 is OK
- 10.1002/widm.1119 is OK
- 10.1016/j.knosys.2014.04.035 is OK
- 10.1016/j.dsp.2010.07.003 is OK
- 10.1145/1281192.1281282 is OK
- 10.4018/ijban.2014100104 is OK

MISSING DOIs

- https://doi.org/10.1137/1.9781611972801.73 may be missing for title: Multiresolution motif discovery in time series
- https://doi.org/10.1109/asru.2017.8269008 may be missing for title: An embedded segmental k-means model for unsupervised segmentation and clustering of speech

INVALID DOIs

- 10.1.1.19.6629 is INVALID
```

**Comment by danielskatz** [comment]
👋 @holgerteichgraeber - It looks like the two missing DOIs found above are correct - please add them.  And the invalid DOI is indeed invalid - either replace it with the right one or remove it.

Then please regenerate the pdf.

**Comment by holgerteichgraeber** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01573/joss.01573/10.21105.joss.01573.pdf)

**Comment by holgerteichgraeber** [comment]
> 
> 
> 👋 @holgerteichgraeber - It looks like the two missing DOIs found above are correct - please add them. And the invalid DOI is indeed invalid - either replace it with the right one or remove it.
> 
> Then please regenerate the pdf.

@danielskatz Thank you, I updated the two DOIs and removed the third.

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.apenergy.2019.02.012 is OK
- 10.21105/joss.01230 is OK
- 10.18637/jss.v062.i01 is OK
- 10.18637/jss.v031.i07 is OK
- 10.21105/joss.01504 is OK
- 10.5281/zenodo.2547683 is OK
- 10.21105/joss.00825 is OK
- 10.1016/j.energy.2017.09.087 is OK
- 10.1016/j.energy.2017.11.059 is OK
- 10.1016/j.energy.2017.06.082 is OK
- 10.1016/j.renene.2017.10.017 is OK
- 10.1016/j.energy.2016.06.081 is OK
- 10.1016/j.apenergy.2017.03.051 is OK
- 10.1109/IEVC.2012.6183283 is OK
- 10.1016/j.compchemeng.2009.10.009 is OK
- 10.1137/15M1020575 is OK
- 10.1137/141000671 is OK
- 10.1016/j.is.2015.04.007 is OK
- 10.1016/j.patcog.2005.01.025 is OK
- 10.1016/j.engappai.2010.09.007 is OK
- 10.1137/1.9781611972795.41 is OK
- 10.1186/1471-2105-8-S7-S21 is OK
- 10.1002/widm.1119 is OK
- https://doi.org/10.1137/1.9781611972801.73 is OK
- 10.1016/j.knosys.2014.04.035 is OK
- https://doi.org/10.1109/asru.2017.8269008 is OK
- 10.1016/j.dsp.2010.07.003 is OK
- 10.1145/1281192.1281282 is OK
- 10.4018/ijban.2014100104 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1170683168430731264) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/951
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01573](https://doi.org/10.21105/joss.01573)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @jgoldfar & @ahwillia for reviewing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01573/status.svg)](https://doi.org/10.21105/joss.01573)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01573">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01573/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01573/status.svg
   :target: https://doi.org/10.21105/joss.01573
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01573/status.svg)](https://doi.org/10.21105/joss.01573)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by holgerteichgraeber** [comment]
Thank you @danielskatz @ahwillia @jgoldfar for editing and reviewing! I very much appreciate that you took the time to review, your comments were extremely helpful!
