### ISSUE TITLE
[PRE REVIEW]: Pannellum: a lightweight web-based panorama viewer

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1574]
**Submitting author:** @mpetroff (<a href="http://orcid.org/0000-0002-4436-4215">Matthew Petroff</a>)
**Repository:** <a href="https://github.com/mpetroff/pannellum" target ="_blank">https://github.com/mpetroff/pannellum</a>
**Version:** v2.5.2
**Editor:** @leouieda
**Reviewers:** @vsoch, @Fil

**Author instructions**

Thanks for submitting your paper to JOSS @mpetroff. **Currently, there isn't an JOSS editor assigned** to your paper.

@mpetroff if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1574 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01574/joss.01574/10.21105.joss.01574.pdf)

**Comment by danielskatz** [comment]
👋 @leouieda - Would you be willing to edit this submission?

**Comment by leouieda** [comment]
@danielskatz sure, no problem

**Comment by leouieda** [comment]
:wave: Hi @ethan-nelson @vsoch would you be interested in reviewing this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon assign @leouieda as editor

**Comment by whedon** [comment]
OK, the editor is @leouieda

**Comment by danielskatz** [comment]
@leouieda note that you can do this too, you don’t need to wait for an AEiC to do it

**Comment by leouieda** [comment]
Thanks, @danielskatz. I wasn't sure I could do that :)

**Comment by vsoch** [comment]
hey @leouieda ! Yes I'd be happy to review this. If I don't have time soon I definitely will in the coming week!

**Comment by leouieda** [comment]
@whedon assign @vsoch as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @vsoch

**Comment by leouieda** [comment]
@vsoch thank you! :tada:

**Comment by leouieda** [comment]
:wave: Hi @fil would you be interested in reviewing this submission for JOSS?

**Comment by Fil** [comment]
yes — I already know the software so it will be easy

**Comment by leouieda** [comment]
@whedon add @Fil as reviewer

**Comment by whedon** [comment]
OK, @Fil is now a reviewer

**Comment by leouieda** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1628. Feel free to close this issue now!
