### ISSUE TITLE
[REVIEW]: SG-t-SNE-Π: Swift Neighbor Embedding of Sparse Stochastic Graphs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1577]
**Submitting author:** @pitsianis (<a href="http://orcid.org/0000-0002-7353-3524">Nikos Pitsianis</a>)
**Repository:** <a href="https://github.com/fcdimitr/sgtsnepi" target ="_blank">https://github.com/fcdimitr/sgtsnepi</a>
**Version:** v1.0.1
**Editor:** @labarba
**Reviewer:** @tingyu66, @rioyokota
**Archive:** <a href="https://doi.org/10.5281/zenodo.3355679" target="_blank">10.5281/zenodo.3355679</a>

## Status

[![status](http://joss.theoj.org/papers/57356ccae93210da491a09042c4cc592/status.svg)](http://joss.theoj.org/papers/57356ccae93210da491a09042c4cc592)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/57356ccae93210da491a09042c4cc592"><img src="http://joss.theoj.org/papers/57356ccae93210da491a09042c4cc592/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/57356ccae93210da491a09042c4cc592/status.svg)](http://joss.theoj.org/papers/57356ccae93210da491a09042c4cc592)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/fcdimitr/sgtsnepi" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@tingyu66 & @rioyokota, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @labarba know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fcdimitr/sgtsnepi">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.1
- [x] **Authorship:** Has the submitting author (@pitsianis) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fcdimitr/sgtsnepi">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.1
- [x] **Authorship:** Has the submitting author (@pitsianis) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @tingyu66, @rioyokota it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01577/joss.01577/10.21105.joss.01577.pdf)

**Comment by labarba** [comment]
👋  @tingyu66, @rioyokota — Thank you for agreeing to review this JOSS submission! This is where the action happens. You both have a review checklist to work your way through. Feel free to ask any questions here. You can post your reviewer comments on this thread and open issues in the software repository as needed (add a cross-link to those here). Godspeed!

**Comment by rioyokota** [comment]
The submitting author has not made any contribution to the repo.

**Comment by rioyokota** [comment]
The installation instructions require sudo access.

**Comment by labarba** [comment]
👋 @pitsianis — Our reviewers are asked to check the following item:

> Authorship: Has the submitting author (@pitsianis) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

We realize that commits are not necessarily a full representation of contributions to a software project, but they do provide a visible signal for them. Therefore, if absent, we request that authors confirm that they are aware of the JOSS [authorship](https://joss.readthedocs.io/en/latest/submitting.html#authorship) policy, and conform to it.

**Comment by pitsianis** [comment]
Yes, I confirm that all authors in the JOSS paper submission have contributed to the design, analysis and the implementation of the associated software release in substantial ways. All co-authors agree to be listed as such, agree to be accountable for all aspects of the work, and to notify JOSS if any retraction or correction of mistakes is needed after publication.

Do you need such a declaration from each co-author separately, or in a special form?

**Comment by rioyokota** [comment]
paper.md does not contain list of authors.

**Comment by rioyokota** [comment]
paper.md does not have references. README.md does but with no DOI for any of the references.

**Comment by danielskatz** [comment]
Hi @rioyokota - re your last two comments, please see the pdf generated from the md and bib files, a few comments up (https://github.com/openjournals/joss-papers/blob/joss.01577/joss.01577/10.21105.joss.01577.pdf)

**Comment by rioyokota** [comment]
Yes, the authors, references, and DOI are available in the generated pdf.

**Comment by rioyokota** [comment]
My checklist is completed.

**Comment by pitsianis** [comment]
Thank you all for the effort, you are inspiring me to volunteer as a reviewer as well.

We have discovered an embarrassing typo and a couple of minor ones on the file paper.md. Shall we push an update or better wait for the review process to be completed?

**Comment by labarba** [comment]
Please go ahead with the fix, push the change and then run `@whedon generate pdf` in a comment here to get a new proof.

**Comment by labarba** [comment]
@rioyokota — does this comment require action, in your view?

> The installation instructions require sudo access.

**Comment by rioyokota** [comment]
What has been the stance of JOSS in the past? Many people working on shared systems (supercomputers) will not be able to install this software because they cannot simply ask the admin to install the dependencies. If there were instructions on how to install these dependencies locally, that would cover a much broader audience.

**Comment by labarba** [comment]
JOSS has no express stance on this. I see a recently published [paper](https://doi.org/10.21105/joss.01531) that also uses a `sudo` installation, but the use context there is different. It perhaps depends on how the software will likely be used. If this software will most likely be used in shared HPC scenarios, it could make sense to suggest a different installation process. Or the authors could see to provide a Singularity container image?

**Comment by pitsianis** [comment]
We do state that our primary target is the personal computer and laptop.

This issue is really with the packages we depend upon and their support for user space builds (and their dependencies).

The container solution is a clean way to deal with this issue, especially if we can provide a script to put together the image.

**Comment by pitsianis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01577/joss.01577/10.21105.joss.01577.pdf)

**Comment by tingyu66** [comment]
I had a linking error when trying to compile on macOS and opened an issue here: https://github.com/fcdimitr/sgtsnepi/issues/2.

**Comment by tingyu66** [comment]
I finished my review checklist.

**Comment by labarba** [comment]
@tingyu66, @rioyokota — Thank you both for completing your review checklist. To move forward with accepting this submission, could we have a statement from you here summarizing your assessment of the software, and giving your recommendation to publish?

**Comment by rioyokota** [comment]
The software is easy to use and highly relevant for the field of machine learning. I recommend publication without further modification.

**Comment by tingyu66** [comment]
The documentation is easy to follow and the examples (in both the code and the supplementary material) clearly demonstrate some suitable embedding applications. I recommend this paper for publication.

**Comment by labarba** [comment]
@pitsianis — you have a handful of in-text citations, meaning that the citation is a part of the sentence, with extra parens: "see (Smith 2000)" or "shown in (Jones 2001)." In these cases, you need to use the correct [citation syntax](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax) to get rid of the parens.

**Comment by labarba** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/s41592-018-0308-4 is OK
- 10.1006/jpdc.1996.0107 is OK
- 10.1145/1583991.1584053 is OK
- 10.1007/s10115-013-0693-z is OK
- 10.1038/s41467-019-09177-y is OK
- 10.5281/zenodo.3334873 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
Could you add a link to the arXiv preprint for this reference?
https://arxiv.org/abs/1906.05582

**Comment by pitsianis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01577/joss.01577/10.21105.joss.01577.pdf)

**Comment by pitsianis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01577/joss.01577/10.21105.joss.01577.pdf)

**Comment by pitsianis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01577/joss.01577/10.21105.joss.01577.pdf)

**Comment by pitsianis** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/s41592-018-0308-4 is OK
- 10.1006/jpdc.1996.0107 is OK
- 10.1145/1583991.1584053 is OK
- 10.1007/s10115-013-0693-z is OK
- 10.1038/s41467-019-09177-y is OK
- 10.5281/zenodo.3334873 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by pitsianis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01577/joss.01577/10.21105.joss.01577.pdf)

**Comment by labarba** [comment]
Looking good! When you're ready, the next steps are:

- [ ] Make a new release of your software, and list the version tag of the archived version here. 
- [ ] Archive the reviewed software in Zenodo 
- [ ] Check the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID to the metadata.
- [ ] Please list the Zenodo DOI of the archived version here.

**Comment by pitsianis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01577/joss.01577/10.21105.joss.01577.pdf)

**Comment by pitsianis** [comment]
@labarba Thank you for your help and the timely and gentle nudges to get all our ducks in a row.

A new release is made (v1.0.1). 
The Zenodo DOI with this release archived is 10.5281/zenodo.3355679

**Comment by pitsianis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01577/joss.01577/10.21105.joss.01577.pdf)

**Comment by labarba** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.3355679 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3355679" target="_blank">10.5281/zenodo.3355679</a> is the archive.

**Comment by labarba** [comment]
Could you make the title of the Zenodo deposit match the title for this JOSS submission? This can be done editing the metadata (no need for a new DOI version).

**Comment by pitsianis** [comment]
@labarba -- We corrected the title of the Zenodo deposit to match the title for this JOSS submission.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/874

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/874, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1156455449799122944) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/875
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01577](https://doi.org/10.21105/joss.01577)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @pitsianis, your JOSS paper is published! 🚀 

Huge thanks to  @tingyu66, @rioyokota for reviewing this submission—JOSS is grateful for your contribution 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01577/status.svg)](https://doi.org/10.21105/joss.01577)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01577">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01577/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01577/status.svg
   :target: https://doi.org/10.21105/joss.01577
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01577/status.svg)](https://doi.org/10.21105/joss.01577)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
