### ISSUE TITLE
[PRE REVIEW]: Simple-Web-Server: a fast and flexible HTTP/1.1 C++ client and server library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1579]
**Submitting author:** @eidheim (<a href="http://orcid.org/0000-0001-5355-6326">Ole Christian Eidheim</a>)
**Repository:** <a href="https://gitlab.com/eidheim/Simple-Web-Server" target ="_blank">https://gitlab.com/eidheim/Simple-Web-Server</a>
**Version:** v3.0
**Editor:** @gkthiruvathukal
**Reviewers:** @ts-adi

**Author instructions**

Thanks for submitting your paper to JOSS @eidheim. **Currently, there isn't an JOSS editor assigned** to your paper.

@eidheim if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01579/joss.01579/10.21105.joss.01579.pdf)

**Comment by danielskatz** [comment]
@gkthiruvathukal - would you be willing to edit this submission?

**Comment by gkthiruvathukal** [comment]
@danielskatz Yes, I will edit this one.

**Comment by danielskatz** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by danielskatz** [comment]
@gkthiruvathukal - in case you didn't know, you can do this (assign yourself as editor) too...

**Comment by gkthiruvathukal** [comment]
Thanks for letting me know! I will do that next time, @danielskatz.

**Comment by gkthiruvathukal** [comment]
@danielskatz Any idea why this submission did not move to review state after you assigned me? On my dashboard, it shows as review_pending.

**Comment by gkthiruvathukal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by gkthiruvathukal** [comment]
@eidheim if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission. Thanks!

**Comment by gkthiruvathukal** [comment]
@eidhelm Can you also comment on two things:
- Why is Simple-Web-Server research software and/or how does it aid in developing research software?
- Does this provide support for HTTPS?

The first question is important from a JOSS standpoint. 
The second is important in general and is not mentioned anywhere in the paper. If HTTPS is not supported, this can present a great deal of frustration to users.

**Comment by eidheim** [comment]
@gkthiruvathukal First of all, thank you for accepting to be editor for this submission.

> @eidheim if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, this list of people have already agreed to review for JOSS and may be suitable for this submission. Thanks!

I see there are several potential reviewers with C++ as one of their preferred programming languages. The ones that stood out to me as having relevant background was: gradvohl, aaronyd, hainesr, jaynanavati, nmullins, HaoZeke, Danbo3004, gcdeshpande and adi3.


> Why is Simple-Web-Server research software and/or how does it aid in developing research software?

Simple-Web-Server can be helpful for any research software written in C++ that needs to communicate with remote endpoints through HTTP or HTTPS. It is a general purpose library that might aid software development in several research fields. An example another paper accepted by JOSS describing a general purpose library can be found here: https://github.com/openjournals/joss-papers/blob/ceab2f713f640fcb4602a05206fbdbb8d04261a0/joss.01109/10.21105.joss.01109.pdf


> Does this provide support for HTTPS?

Yes, Simple-Web-Server supports HTTPS. This is mentioned in the first paragraph of the summery in the paper: "Simple-Web-Server is a library that can be utilized in C++ applications to
implement web-resources or perform HTTP(S) requests in a simple manner across OS
platforms compared to using a networking library directly.". "HTTP(S)" could however be changed to "HTTP or HTTPS".

**Comment by gkthiruvathukal** [comment]
@eidheim Thanks for your responses. This is all I needed to proceed with assigning reviewers. I would like see a clear mention of how this helps research software (the language you provided being just about all we need) and to split HTTP and HTTPS. I even failed to notice the regex-like syntax at first.

**Comment by gkthiruvathukal** [comment]
@gradvohl, @aaronyd, @hainesr, @jaynanavati, @nmullins, @HaoZeke, @Danbo3004, @gcdeshpande and @adi3: Would you be willing to contribute a review for this JOSS submission? I need two reviewers. I plan to assign on an FCFS basis. I know a couple of you have helped me on recent submissions but would be grateful to have your help again.

**Comment by HaoZeke** [comment]
@gkthiruvathukal I would be willing but there need to be significant rewrites. As far as I can tell there are no indications as to how this benefits researchers. It seems like a nice project though..

**Comment by HaoZeke** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1007/978-1-4419-7719-9_6 may be missing for title: Boost C++ Libraries

INVALID DOIs

- None
```

**Comment by gkthiruvathukal** [comment]
@HaoZeke If you take a look, I asked @eidheim about how it's research software and will be helpful to it.  I believe he gave a satisfactory response and we can iterate with him on this during review. I'm going to assign you as you already have provided some good feedback.

**Comment by gkthiruvathukal** [comment]
@whedon assign @HaoZeke as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @HaoZeke

**Comment by gkthiruvathukal** [comment]
Awaiting one more reviewer!

**Comment by HaoZeke** [comment]
@gkthiruvathukal, sure, thanks. I am certain that working with @eidheim will definitely make this a valued contribution. Will continue once the review starts.

**Comment by ts-adi** [comment]
@gkthiruvathukal I can take this on. The library is probably useful and I think @eidheim will just need to elucidate his response more specifically
> It is a general purpose library that might aid software development in several research fields.

By the way, the code itself should have comments and documentation beyond a readme. This is especially important for a library where a doxygen-built API would help users. Not sure if that is part of the review process though.

**Comment by HaoZeke** [comment]
@ts-adi it will be.

**Comment by gkthiruvathukal** [comment]
@ts-adi I'm grateful that you are willing to be a reviewer. Let me assign you and get the ball rolling. All of these comments will be helpful for the actual review.

**Comment by gkthiruvathukal** [comment]
@whedon assign @ts-adi as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ts-adi

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1592. Feel free to close this issue now!

**Comment by gcdeshpande** [comment]
Happy to take up.. if still available

Thanks and Regards
Gajendra C. Deshpande
Assistant Professor, CSE@KLS.GIT
Belgaum - 590008
Karnataka, INDIA

Blog: http://gajendramoksha.wordpress.com
Website: http://sites.google.com/a/git.edu/gcd
Facebook: https://www.facebook.com/gcdeshpande


[http://csta.acm.org/Membership/sub/badge.jpg]


________________________________

**Comment by gkthiruvathukal** [comment]
@gcdeshpande I will keep you in mind for another submission. Thanks for responding!
