### ISSUE TITLE
[PRE REVIEW]: remBoot: An R package for Random Encounter Modelling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#158]
**Submitting author:** @arcaravaggi (<a href="http://orcid.org/0000-0002-1763-8970">Anthony Caravaggi</a>)
**Repository:** <a href="https://github.com/arcaravaggi/remBoot" target ="_blank">https://github.com/arcaravaggi/remBoot</a>
**Version:** 0.0.0.9000
**Editor:** @karthik
**Reviewer:** @amoeba

**What this issue is for**

Thanks for submitting your paper to JOSS @arcaravaggi. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @karthik - would you be willing to edit this submission for JOSS?

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by karthik** [comment]
@arfon Sure, np.

**Comment by arcaravaggi** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by arcaravaggi** [comment]
@karthik - Perhaps @jsta and/or @amoeba would be appropriate reviewers? Both list ecology as a topic of interest.

**Comment by arcaravaggi** [comment]
Dear editor (@karthik),
It has been some time since there was any activity on this issue. Could you please advise as to whether the review process is still ongoing.
Many thanks,
arcaravaggi

**Comment by amoeba** [comment]
Hey @arcaravaggi, sorry I didn't catch your first mention. Unless @jsta is eager to review this one, I can do this before Monday. I'm not familiar with Random Encounter Modeling but I can probably wrap my head around it.

At a first (quick) glance, I expect I'm going to have comments about:

- The readme looks to be missing sections
- The paper looks to have too much info but I'm not sure and it may be totally fine
- The package is missing automated tests but I'm not sure the package is complex to warrant much in the way of tests

A more thorough review to come when I get a chance this weekend.

**Comment by arcaravaggi** [comment]
Hi @amoeba, thanks for agreeing to review the package. I appreciate your time and feedback.

**Comment by arfon** [comment]
@whedon assign @amoeba as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @amoeba

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/176. Feel free to close this issue now!

**Comment by arfon** [comment]
> Hey @arcaravaggi, sorry I didn't catch your first mention. Unless @jsta is eager to review this one, I can do this before Monday. I'm not familiar with Random Encounter Modeling but I can probably wrap my head around it.

Awesome, thanks @amoeba. Please head over to #176 for the actual review issue (with checklist etc).
