### ISSUE TITLE
[PRE REVIEW]: DOENOVA: Simple DOE and ANOVA package for Python 3

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1580]
**Submitting author:** @fblavoie (<a href="http://orcid.org/0000-0003-4574-1315">Francis B Lavoie</a>)
**Repository:** <a href="https://github.com/fblavoie/doenova" target ="_blank">https://github.com/fblavoie/doenova</a>
**Version:** 0.1.3
**Editor:** @usethedata
**Reviewers:** @klmedeiros

**Author instructions**

Thanks for submitting your paper to JOSS @fblavoie. **Currently, there isn't an JOSS editor assigned** to your paper.

@fblavoie if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1580 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@fblavoie - please change manuscript.md to paper.md to whedon can find it

**Comment by danielskatz** [comment]
@mgymrek - would you be willing to edit this submission?

**Comment by kyleniemeyer** [comment]
Hi @mgymrek, just another ping—we'd like to assign this submission to you.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1580 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/author.rb:58:in `block in build_affiliation_string': Problem with affiliations for Francis Lavoie, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/author.rb:57:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/author.rb:57:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:141:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:141:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:138:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:138:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:84:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
Hi @fblavoie, please merge the PR I submitted that attempts to fix some things in your paper: https://github.com/fblavoie/doenova/pull/1

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01580/joss.01580/10.21105.joss.01580.pdf)

**Comment by labarba** [comment]
👋  @fblavoie — I'm the Associate Editor in Chief this week, and I will be continuing to search for an editor to assign to your submission. But first, I need to ask you to add to the top of your paper:

> A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.

(From our [Documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain).)

As it is, I (a non-specialist) cannot quite parse what your software does, and that makes it hard for me to identify the right editor. Thanks!

**Comment by fblavoie** [comment]
Thanks for the follow-up.
I just added the summary to the paper.
If it can help to find an editor... an important part of the software features perform "basic under-grad" mathematics. People working in mathematics/statistics should be able to understand what the software does.

**Comment by labarba** [comment]
@whedon assign @usethedata as editor

**Comment by arfon** [comment]
@whedon assign @usethedata as editor

**Comment by arfon** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata
