### ISSUE TITLE
[PRE REVIEW]: datacleanbot: an automated data cleaning tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1581]
**Submitting author:** @Ji-Zhang (<a href="http://orcid.org/0000-0002-4913-518X">Ji Zhang</a>)
**Repository:** <a href="https://github.com/Ji-Zhang/datacleanbot" target ="_blank">https://github.com/Ji-Zhang/datacleanbot</a>
**Version:** v0.4
**Editor:** @usethedata
**Reviewers:** @kellieotto 

**Author instructions**

Thanks for submitting your paper to JOSS @Ji-Zhang. **Currently, there isn't an JOSS editor assigned** to your paper.

@Ji-Zhang if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1581 with the following error: 

 sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.01581.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01581/joss.01581/10.21105.joss.01581.pdf)

**Comment by danielskatz** [comment]
@usethedata - would you be willing to edit this submission?

**Comment by Ji-Zhang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01581/joss.01581/10.21105.joss.01581.pdf)

**Comment by usethedata** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by usethedata** [comment]
@Ji-Zhang Thanks for your submission.  In reading through it, one thing I notice is that there's no contributor information.  Part of the expectation is under the heading of community guidelines: 

    There should be clear guidelines for third-parties wishing to:

    * Contribute to the software
    * Report issues or problems with the software
    * Seek support

I'm not seeing information about contributions (a very simple contributing.md file can be done, explaining how you want to receive code or documentation contributions.  Reporting issues and seeking support might go well in your documentation.  It doesn't need to be long or elaborate.  

Finally, do you have any suggested reviewers?  Thanks

**Comment by Ji-Zhang** [comment]
@usethedata Thank you for reminding that. I just added the contributing.md file. 

Regarding the reviewers, I am wondering if @rgmyr or @kellieotto is willing to be the reviewer. The tool is written in Python,  any reviewer familiar with machine learning, data science or data visualization is welcomed.

**Comment by kellieotto** [comment]
I can review this package.

**Comment by Ji-Zhang** [comment]
> I can review this package.

That would be great. Thanks a lot.

**Comment by usethedata** [comment]
@kellieotto Thanks for agreeing to review.  In the interests of keeping this moving forward, I'm going to go ahead and open up the review issue.  We do need to find a second reviewer, and I'll add that person to the review issue.

**Comment by usethedata** [comment]
@whedon assign @kellieotto  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kellieotto

**Comment by usethedata** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1608. Feel free to close this issue now!
