### ISSUE TITLE
[PRE REVIEW]: rtdpy: A python package for residence time distributions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1582]
**Submitting author:** @MatthewFlamm (<a href="http://orcid.org/0000-0002-2040-5481">Matthew Flamm</a>)
**Repository:** <a href="https://github.com/Merck/rtdpy" target ="_blank">https://github.com/Merck/rtdpy</a>
**Version:** v0.5
**Editor:** @xuanxu
**Reviewers:** @ctdegroot, @dandavies99

**Author instructions**

Thanks for submitting your paper to JOSS @MatthewFlamm. **Currently, there isn't an JOSS editor assigned** to your paper.

@MatthewFlamm if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01582/joss.01582/10.21105.joss.01582.pdf)

**Comment by danielskatz** [comment]
👋 @xuanxu - would you be willing to edit this submission?

**Comment by xuanxu** [comment]
@danielskatz I’m going to be ooo for a couple of weeks, so I think it’d be better to have another person editing this (but feel free to assign it to me if you can’t find anyone else).

**Comment by danielskatz** [comment]
@xuanxu - if it's just 2 weeks, I think given the balance of submissions and editors, I would prefer for you to handle this one.

**Comment by MatthewFlamm** [comment]
I've looked through the reviewer list.  Only as suggestions: both @ctdegroot and @arosen93 have chemical engineering, which would be the main applicable area for this package, listed under Domains/Topics and Python listed under Preferred Programming Language.

Look forward to the process.

**Comment by ctdegroot** [comment]
Yep, this is in my area. I’d be happy to review it.

**Comment by arosen93** [comment]
Unfortunately a fair bit out of my comfort zone, so I will have to decline, but thanks for the suggestion. Best of luck with the submission.

**Comment by danielskatz** [comment]
@whedon assign @xuanxu as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by danielskatz** [comment]
@ctdegroot - sorry for delay, but we will wait until @xuanxu is available (a couple of weeks before starting the review)

**Comment by xuanxu** [comment]
Thanks @ctdegroot! I'll assign you now. 
I'll start the review issue once I find the second reviewer, stay tuned!

**Comment by xuanxu** [comment]
@whedon assign @ctdegroot as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ctdegroot

**Comment by xuanxu** [comment]
:wave: @khinsen: would you be willing to review this paper? I think your knowledge of Python and computational chemistry makes you a good fit for this submission.

**Comment by xuanxu** [comment]
:wave: @dandavies99 — would you be willing to contribute a review for JOSS on this submission?

**Comment by dandavies99** [comment]
Hi @xuanxu, sure I'd be happy to.

**Comment by xuanxu** [comment]
great @dandavies99, thanks! I'll assign you now and start the review

**Comment by xuanxu** [comment]
@whedon add @dandavies99 as reviewer

**Comment by whedon** [comment]
OK, @dandavies99 is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1621. Feel free to close this issue now!

**Comment by xuanxu** [comment]
@ctdegroot, @dandavies99 - please head over to #1621 where the review will take place.
