### ISSUE TITLE
[PRE REVIEW]: ivis: dimensionality reduction in very large datasets using Siamese Networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1583]
**Submitting author:** @beringresearch (<a href="http://orcid.org/0000-0001-6727-4688">Ignat Drozdov</a>)
**Repository:** <a href="https://github.com/beringresearch/ivis" target ="_blank">https://github.com/beringresearch/ivis</a>
**Version:** v1.2.3
**Editor:** @lpantano
**Reviewers:** @SaskiaFreytag, @kevinrue

**Author instructions**

Thanks for submitting your paper to JOSS @beringresearch. **Currently, there isn't an JOSS editor assigned** to your paper.

@beringresearch if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01583/joss.01583/10.21105.joss.01583.pdf)

**Comment by danielskatz** [comment]
👋 @lpantano - you've been suggested as the editor - are you willing to do so?

**Comment by lpantano** [comment]
Sure.

**Comment by danielskatz** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
@SaskiaFreytag, will you be interested in reviewing this tool?

**Comment by SaskiaFreytag** [comment]
Sure. How do I go about reviewing it?

**Comment by lpantano** [comment]
Thank you, @SaskiaFreytag, I will add you as a reviewer, then I need to find another one (if you know somebody would like to do it, let me know). At that moment, I will start another issue where the review happens (mainly a list of items to check, like https://github.com/openjournals/joss-reviews/issues/1584.

**Comment by lpantano** [comment]
@whedon add @SaskiaFreytag as reviewer

**Comment by whedon** [comment]
OK, @SaskiaFreytag is now a reviewer

**Comment by lpantano** [comment]
@whedon add @kevinrue as reviewer

**Comment by whedon** [comment]
OK, @kevinrue is now a reviewer

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1596. Feel free to close this issue now!
