### ISSUE TITLE
[PRE REVIEW]: ORIS: An interactive software tool for prediction of replication origin in prokaryotic genomes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1585]
**Submitting author:** @urmi-21 (<a href="http://orcid.org/0000-0003-3703-0820">Urminder Singh</a>)
**Repository:** <a href="https://github.com/urmi-21/ORIS" target ="_blank">https://github.com/urmi-21/ORIS</a>
**Version:** v1.0
**Editor:** @csoneson
**Reviewers:** @jdeligt, @holtgrewe

**Author instructions**

Thanks for submitting your paper to JOSS @urmi-21. **Currently, there isn't an JOSS editor assigned** to your paper.

@urmi-21 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1585 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1585 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1585/paper/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:95:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @csoneson - you've been requested as the editor - are you willing to edit this submission?

**Comment by danielskatz** [comment]
👋 @urmi-21 - A fix for the paper compilation issues might be in https://github.com/urmi-21/ORIS/pull/2  Please merge this and see if it fixes the problem, by adding a comment here that says ```@whedon generate pdf``` - feel free to iterate

**Comment by urmi-21** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01585/joss.01585/10.21105.joss.01585.pdf)

**Comment by urmi-21** [comment]
@danielskatz Thanks for the suggesting the fix in paper.md. The compiled pdf looks good to me.

**Comment by danielskatz** [comment]
While we are in the process of assigning an editor, you might suggestion some possible reviewers, either from [this list](https://bit.ly/joss-reviewers) (please start at the bottom of the list) or elsewhere, who might be able to review your submission. Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by urmi-21** [comment]
I would like to suggest the following reviewers: @holtgrewe @jdeligt
I hope my submission is appropriate for them to review.

**Comment by csoneson** [comment]
Yes, I can take on this one. 
> 👋 @csoneson - you've been requested as the editor - are you willing to edit this submission?

**Comment by csoneson** [comment]
@holtgrewe, @jdeligt - would you be interested in reviewing this submission for JOSS?

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by jdeligt** [comment]
Count me in.

**Comment by csoneson** [comment]
Great @jdeligt - thank you!

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1101/cshperspect.a010108 may be missing for title: Principles and concepts of DNA replication in bacteria, archaea, and eukarya
- https://doi.org/10.1111/j.1365-2958.2005.04622.x may be missing for title: MicroReview: Divided genomes: negotiating the cell cycle in prokaryotes with multiple chromosomes
- https://doi.org/10.1093/bioinformatics/16.6.560 may be missing for title: Oriloc: prediction of replication boundaries in unannotated bacterial chromosomes
- https://doi.org/10.1186/1471-2105-9-79 may be missing for title: Ori-Finder: a web-based system for finding oriC s in unannotated bacterial genomes
- https://doi.org/10.1016/j.biosystems.2011.09.003 may be missing for title: Nucleotide correlation based measure for identifying origin of replication in genomic sequences
- https://doi.org/10.1016/j.biosystems.2011.11.006 may be missing for title: On the origin of three base periodicity in genomes
- https://doi.org/10.1073/pnas.95.7.3720 may be missing for title: Strand compositional asymmetry in bacterial and large viral genomes
- https://doi.org/10.1126/science.272.5262.745 may be missing for title: Origin of replication of Mycoplasma genitalium
- https://doi.org/10.1093/nar/26.10.2286 may be missing for title: Analyzing genomes with cumulative skew diagrams
- https://doi.org/10.1007/s00792-004-0385-4 may be missing for title: Identification of replication origins in the genome of the methanogenic archaeon, Methanocaldococcus jannaschii
- https://doi.org/10.1155/2005/509646 may be missing for title: Identification of replication origins in archaeal genomes based on the Z-curve method
- https://doi.org/10.3389/fmicb.2014.00482 may be missing for title: Ori-Finder 2, an integrated tool to predict replication origins in the archaeal genomes
- https://doi.org/10.1002/j.1460-2075.1995.tb07169.x may be missing for title: Sequence-dependent bending propensity of DNA as revealed by DNase I: parameters for trinucleotides.
- https://doi.org/10.1093/nar/27.23.4636 may be missing for title: Improved microbial gene identification with GLIMMER
- https://doi.org/10.1093/nar/gks990 may be missing for title: DoriC 5.0: an updated database of oriC regions in both bacterial and archaeal genomes
- https://doi.org/10.1111/febs.14150 may be missing for title: Identification and characterization of ARS-like sequences as putative origin (s) of replication in human malaria parasite Plasmodium falciparum

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@urmi-21 - while we are recruiting a second reviewer, could you please add DOIs to the references in your paper?

**Comment by urmi-21** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1101/cshperspect.a010108 may be missing for title: Principles and concepts of DNA replication in bacteria, archaea, and eukarya
- https://doi.org/10.1111/j.1365-2958.2005.04622.x may be missing for title: MicroReview: Divided genomes: negotiating the cell cycle in prokaryotes with multiple chromosomes
- https://doi.org/10.1093/bioinformatics/16.6.560 may be missing for title: Oriloc: prediction of replication boundaries in unannotated bacterial chromosomes
- https://doi.org/10.1186/1471-2105-9-79 may be missing for title: Ori-Finder: a web-based system for finding oriC s in unannotated bacterial genomes
- https://doi.org/10.1016/j.biosystems.2011.09.003 may be missing for title: Nucleotide correlation based measure for identifying origin of replication in genomic sequences
- https://doi.org/10.1016/j.biosystems.2011.11.006 may be missing for title: On the origin of three base periodicity in genomes
- https://doi.org/10.1073/pnas.95.7.3720 may be missing for title: Strand compositional asymmetry in bacterial and large viral genomes
- https://doi.org/10.1126/science.272.5262.745 may be missing for title: Origin of replication of Mycoplasma genitalium
- https://doi.org/10.1093/nar/26.10.2286 may be missing for title: Analyzing genomes with cumulative skew diagrams
- https://doi.org/10.1007/s00792-004-0385-4 may be missing for title: Identification of replication origins in the genome of the methanogenic archaeon, Methanocaldococcus jannaschii
- https://doi.org/10.1155/2005/509646 may be missing for title: Identification of replication origins in archaeal genomes based on the Z-curve method
- https://doi.org/10.3389/fmicb.2014.00482 may be missing for title: Ori-Finder 2, an integrated tool to predict replication origins in the archaeal genomes
- https://doi.org/10.1002/j.1460-2075.1995.tb07169.x may be missing for title: Sequence-dependent bending propensity of DNA as revealed by DNase I: parameters for trinucleotides.
- https://doi.org/10.1093/nar/27.23.4636 may be missing for title: Improved microbial gene identification with GLIMMER
- https://doi.org/10.1093/nar/gks990 may be missing for title: DoriC 5.0: an updated database of oriC regions in both bacterial and archaeal genomes
- https://doi.org/10.1111/febs.14150 may be missing for title: Identification and characterization of ARS-like sequences as putative origin (s) of replication in human malaria parasite Plasmodium falciparum

INVALID DOIs

- None
```

**Comment by urmi-21** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01585/joss.01585/10.21105.joss.01585.pdf)

**Comment by urmi-21** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1201/9781315815015 is OK
- 10.1101/cshperspect.a010108 is OK
- 10.1111/j.1365-2958.2005.04622.x is OK
- 10.1093/bioinformatics/16.6.560 is OK
- 10.1186/1471-2105-9-79 is OK
- 10.1016/j.biosystems.2011.09.003 is OK
- 10.1016/j.biosystems.2011.11.006 is OK
- 10.1111/febs.14150 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by urmi-21** [comment]
@csoneson Hi, I've added the DOIs to the references. Thanks.

**Comment by holtgrewe** [comment]
@csoneson sure can do ;)

**Comment by csoneson** [comment]
@holtgrewe great, thanks! I'm going to open the review issue, and then we'll head over there for the actual review

**Comment by csoneson** [comment]
@whedon assign @jdeligt as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jdeligt

**Comment by csoneson** [comment]
@whedon add @holtgrewe as reviewer

**Comment by whedon** [comment]
OK, @holtgrewe is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1589. Feel free to close this issue now!
