### ISSUE TITLE
[PRE REVIEW]: Spruceup: fast and flexible identification, visualization, and removal of outliers from large multiple sequence alignments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1586]
**Submitting author:** @marekborowiec (<a href="http://orcid.org/0000-0001-7510-4064">Marek Borowiec</a>)
**Repository:** <a href="https://github.com/marekborowiec/spruceup-ms" target ="_blank">https://github.com/marekborowiec/spruceup-ms</a>
**Version:** v2019.1.1
**Editor:** @csoneson
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @marekborowiec. The JOSS editor @csoneson, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@marekborowiec if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @csoneson it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@csoneson) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01586/joss.01586/10.21105.joss.01586.pdf)

**Comment by danielskatz** [comment]
👋 @csoneson - you were requested to edit this, and I failed to unset you when I started this metareview - sorry - I hope you can take on this one too - Please let me know if not.

**Comment by danielskatz** [comment]
👋 @marekborowiec - your submission doesn't actually have any software to be reviewed.  A normal JOSS submission is a repository that contains software and a paper.  Please look at some of the other accepted and under review submissions.  I've marked this as paused for the time being until there's content to review.  If you would prefer to withdraw this and submit again with a different repository, please let us know.

**Comment by csoneson** [comment]
That's ok, I can take it
> 👋 @csoneson - you were requested to edit this, and I failed to unset you when I started this metareview - sorry - I hope you can take on this one too - Please let me know if not.

**Comment by marekborowiec** [comment]
I see. Sorry for the confusion. I was under the impression that code and paper should exist in separate repositories. The md file contains link to the software repo. Would uploading a zipped version of the software repo into this repository work? This would be the easiest solution for me because I’m traveling and without access to a laptop and/or internet at times for the week. Otherwise I won’t be able to resubmit until August. Thank you for understanding.

**Comment by danielskatz** [comment]
The best thing is probably to withdraw this version, and when you are back and ready in August, add the paper to the software repo and then resubmit - I'm going to go ahead and mark this as withdrawn, but please do resubmit when you are able to.
