### ISSUE TITLE
[REVIEW]: studentlife: Tidy Handling and Navigation of a Valuable Mobile-Health Dataset

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1587]
**Submitting author:** @frycast (<a href="http://orcid.org/0000-0001-6032-0522">Daniel Fryer</a>)
**Repository:** <a href="https://github.com/frycast/studentlife" target ="_blank">https://github.com/frycast/studentlife</a>
**Version:** v1.0.0
**Editor:** @arokem
**Reviewers:** @klmedeiros, @jminnier
**Archive:** <a href="https://doi.org/10.5281/zenodo.3371922" target="_blank">10.5281/zenodo.3371922</a>

## Status

[![status](http://joss.theoj.org/papers/4a61d044aefabdb7c57520a0715e41ed/status.svg)](http://joss.theoj.org/papers/4a61d044aefabdb7c57520a0715e41ed)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/4a61d044aefabdb7c57520a0715e41ed"><img src="http://joss.theoj.org/papers/4a61d044aefabdb7c57520a0715e41ed/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/4a61d044aefabdb7c57520a0715e41ed/status.svg)](http://joss.theoj.org/papers/4a61d044aefabdb7c57520a0715e41ed)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="github.com/frycast/studentlife" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@klmedeiros, @jminnier : please carry out your review in this issue by updating your checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="github.com/frycast/studentlife">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@frycast) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="github.com/frycast/studentlife">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@frycast) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @klmedeiros it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1587 with the following error: 

 Can't find any papers to compile :-(

**Comment by arokem** [comment]
@whedon add @jminnier as reviewer

**Comment by whedon** [comment]
OK, @jminnier is now a reviewer

**Comment by hiendn** [comment]
> **Submitting author:** @frycast ([Daniel Fryer](http://orcid.org/0000-0001-6032-0522))
> **Repository:** [github.com/frycast/studentlife](github.com/frycast/studentlife)
> **Version:** v1.0.0
> **Editor:** @arokem
> **Reviewers:** @klmedeiros, @jminnier
> **Archive:** Pending
> 
> ## Status
> [![status](https://camo.githubusercontent.com/cee88cbf149132c3f25c18f7c74e1e4db7b29829/687474703a2f2f6a6f73732e7468656f6a2e6f72672f7061706572732f34613631643034346165666162646237633537353230613037313565343165642f7374617475732e737667)](http://joss.theoj.org/papers/4a61d044aefabdb7c57520a0715e41ed)
> 
> Status badge code:
> 
> ```
> HTML: <a href="http://joss.theoj.org/papers/4a61d044aefabdb7c57520a0715e41ed"><img src="http://joss.theoj.org/papers/4a61d044aefabdb7c57520a0715e41ed/status.svg"></a>
> Markdown: [![status](http://joss.theoj.org/papers/4a61d044aefabdb7c57520a0715e41ed/status.svg)](http://joss.theoj.org/papers/4a61d044aefabdb7c57520a0715e41ed)
> ```
> 
> **Reviewers and authors**:
> 
> Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the [target repository](github.com/frycast/studentlife) and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)
> 
> ## Reviewer instructions & questions
> @klmedeiros, @jminnier : please carry out your review in this issue by updating your checklist below. If you cannot edit the checklist please:
> 
> 1. Make sure you're logged in to your GitHub account
> 2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations
> 
> The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arokem know.
> 
> ✨ **Please try and complete your review in the next two weeks** ✨
> 
> ## Review checklist for @klmedeiros
> ### Conflict of interest
> * [ ]  As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.
> 
> ### Code of Conduct
> * [ ]  I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).
> 
> ### General checks
> * [ ]  **Repository:** Is the source code for this software available at the [repository url](github.com/frycast/studentlife)?
> * [ ]  **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
> * [ ]  **Version:** Does the release version given match the GitHub release (v1.0.0)?
> * [ ]  **Authorship:** Has the submitting author (@frycast) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
> 
> ### Functionality
> * [ ]  **Installation:** Does installation proceed as outlined in the documentation?
> * [ ]  **Functionality:** Have the functional claims of the software been confirmed?
> * [ ]  **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)
> 
> ### Documentation
> * [ ]  **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
> * [ ]  **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
> * [ ]  **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
> * [ ]  **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
> * [ ]  **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
> * [ ]  **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
> 
> ### Software paper
> * [ ]  **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
> * [ ]  **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
> * [ ]  **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
> 
> ## Review checklist for @jminnier
> ### Conflict of interest
> * [ ]  As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.
> 
> ### Code of Conduct
> * [ ]  I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).
> 
> ### General checks
> * [ ]  **Repository:** Is the source code for this software available at the [repository url](github.com/frycast/studentlife)?
> * [ ]  **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
> * [ ]  **Version:** Does the release version given match the GitHub release (v1.0.0)?
> * [ ]  **Authorship:** Has the submitting author (@frycast) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
> 
> ### Functionality
> * [ ]  **Installation:** Does installation proceed as outlined in the documentation?
> * [ ]  **Functionality:** Have the functional claims of the software been confirmed?
> * [ ]  **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)
> 
> ### Documentation
> * [ ]  **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
> * [ ]  **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
> * [ ]  **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
> * [ ]  **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
> * [ ]  **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
> * [ ]  **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
> 
> ### Software paper
> * [ ]  **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
> * [ ]  **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
> * [ ]  **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

@arokem @frycast --- The URL at the top of the page leads to a 404 error when clicked. Is this a potential reason why the paper is not compiling by `@weldon generate pdf`?

**Comment by frycast** [comment]
@arokem @klmedeiros --- Is there a way that I can change the URL at the top of the page? Perhaps I should resubmit?

**Comment by frycast** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by frycast** [comment]
@whedon generate pdf from branch master

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch master. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1587 with the following error: 

 fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Can't find any papers to compile :-(

**Comment by frycast** [comment]
@whedon generate pdf from https://github.com/frycast/studentlife

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1587 with the following error: 

 Can't find any papers to compile :-(

**Comment by hiendn** [comment]
@whedon generate pdf from https://github.com/frycast/studentlife/tree/master/paper

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1587 with the following error: 

 Can't find any papers to compile :-(

**Comment by hiendn** [comment]
@whedon generate pdf from https://github.com/frycast/studentlife/blob/master/paper/paper.md

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1587 with the following error: 

 Can't find any papers to compile :-(

**Comment by hiendn** [comment]
@arokem can you look into what is wrong with this submission, that makes it unable to render a PDF? Do you think it is worth it to simply resubmit the paper in a hope of resolving the issues?

**Comment by arokem** [comment]
I just edited the URL in the first comment on this issue. Let's see if that works.

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01587/joss.01587/10.21105.joss.01587.pdf)

**Comment by frycast** [comment]
Thanks @arokem ! On another note, we just noticed a typo in the address of author Pierre Orban (saying "Monstreal" instead of "Montreal"). Should I update that on the repo now and recompile?

**Comment by frycast** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01587/joss.01587/10.21105.joss.01587.pdf)

**Comment by frycast** [comment]
Hi @arokem  @jminner @klmedeiros. I've updated the typo in the author's affiliation and recompiled the pdf. How is it looking now?

**Comment by jminnier** [comment]
This software looks great and the addition of visualizations makes this data accessing package really nice and extra useful.

I just had minor questions:
https://github.com/frycast/studentlife/issues/7 (a couple typos, I think)
https://github.com/frycast/studentlife/issues/8 (contribution info missing as far as I can tell)

Thanks for making this package @frycast!

**Comment by arokem** [comment]
Thanks for taking a look @jminnier ! 

@klmedeiros : have you had a chance to look into this?

**Comment by frycast** [comment]
Thanks for the useful comments @jminnier . I've fixed both typos and appended community guidelines to the README . Thanks @arokem .

**Comment by jminnier** [comment]
Looks great @frycast, thanks!

**Comment by frycast** [comment]
@klmedeiros : sorry for the delay in getting the pdf to compile in the beginning. Do you still have time to review this?

**Comment by klmedeiros** [comment]
@frycast Yes my sincerest apologies for the delay on my end. I will wrap this up today/tomorrow.

**Comment by klmedeiros** [comment]
@frycast This looks great! I found the documentation on the README very helpful, and was happy to provide a review for this.

**Comment by arokem** [comment]
@klmedeiros : there is still one item that is not checked off ("performance"). Are there any performance claims that you would like to test? Otherwise, is this paper ready to be accepted from your point of view?

**Comment by arokem** [comment]
@jminnier : just to confirm: is this paper ready to be accepted from your point of view?

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01587/joss.01587/10.21105.joss.01587.pdf)

**Comment by jminnier** [comment]
@arokem Indeed, I believe this paper is ready to be accepted.

**Comment by klmedeiros** [comment]
@arokem My apologies, I did test the package out a bit (differences between downloading full dataset or a sample) and found it good, and forgot to check that off. I have now, and I believe the paper is ready to be accepted.

**Comment by arokem** [comment]
Thanks both!

**Comment by arokem** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/npp.2016.7 is OK
- 10.1145/2632048.2632054 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arokem** [comment]
@frycast : everything looks good! 

At this point, could you please make a new release of this software that includes the changes that have resulted from the review? Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive. For the archive version, please make sure that:

- The title of the archive is the same as the JOSS paper title
- The authors of the archive are the same as the JOSS paper authors

**Comment by frycast** [comment]
Thanks @arokem . I've made the new release and an archive on Zenodo with DOI: 10.5281/zenodo.3371922

**Comment by arokem** [comment]
This looks good to me 

@openjournals/joss-eics : I believe that this paper is ready for your review.

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.3371922 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3371922" target="_blank">10.5281/zenodo.3371922</a> is the archive.

**Comment by kyleniemeyer** [comment]
Hi @frycast, I made some minor copy edits in two PRs, if you could merge those: https://github.com/frycast/studentlife/pull/9 and https://github.com/frycast/studentlife/pull/10

**Comment by frycast** [comment]
Thanks @kyleniemeyer . I've merged them both.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01587/joss.01587/10.21105.joss.01587.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/917

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/917, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1164204204317138945) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/918
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01587](https://doi.org/10.21105/joss.01587)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @frycast on your article's publication in JOSS! Many thanks to @arokem for editing, and @klmedeiros and @jminnier for reviewing this submission.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01587/status.svg)](https://doi.org/10.21105/joss.01587)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01587">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01587/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01587/status.svg
   :target: https://doi.org/10.21105/joss.01587
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01587/status.svg)](https://doi.org/10.21105/joss.01587)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by frycast** [comment]
Great news. Thank you @kyleniemeyer and @arokem ! And many thanks to @klmedeiros and @jminnier for your reviews and helpful comments.

**Comment by frycast** [comment]
@kyleniemeyer the software [repository link here](https://joss.theoj.org/papers/4a61d044aefabdb7c57520a0715e41ed) still leads to 404 Not Found page. It's because I originally specified the link as "github.com/frycast/studentlife" and it needs to be changed to have the prefix "https://". Are you able to make that change?

**Comment by kyleniemeyer** [comment]
> @kyleniemeyer the software [repository link here](https://joss.theoj.org/papers/4a61d044aefabdb7c57520a0715e41ed) still leads to 404 Not Found page. It's because I originally specified the link as "github.com/frycast/studentlife" and it needs to be changed to have the prefix "https://". Are you able to make that change?

@arfon can you help with this one?

**Comment by arfon** [comment]
> @arfon can you help with this one?

Fixed.
