### ISSUE TITLE
[PRE REVIEW]: IRXCT: Iterative Reconstruction and visualization application for X-ray Computed Tomography

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1588]
**Submitting author:** @dntrinca (<a href="http://orcid.org/0000-0002-0464-9443">D Narcis Trinca</a>)
**Repository:** <a href="https://github.com/dntrinca/IRXCT" target ="_blank">https://github.com/dntrinca/IRXCT</a>
**Version:** 1.0
**Editor:** @usethedata
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @dntrinca. **Currently, there isn't an JOSS editor assigned** to your paper.

@dntrinca if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1588 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@dntrinca - this submission has some problems - the source code being in a zip file is one.  We expect to see the software in a version control repository (eg github) but in a way that the software can be updated via pull requests and changes - a zip file doesn't really work for that.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1588 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
Also, please follow the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) to use affiliations correctly - they need to be marked as integer indexes in the authors section, then these indexes need to be used in the affiliations section.

Once you have made changes, please feel free to enter ```@whedon generate pdf``` her as a new comment in this issue to try to build the paper again.

**Comment by dntrinca** [comment]
Dear Daniel Skatz,

  I just made the necessary corrections you have mentioned.

  Best,
  D Narcis

**Comment by dntrinca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1588 with the following error: 

 Error reading bibliography ./paper.bib (line 24, column 3):
unexpected "j"
expecting space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by dntrinca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1588 with the following error: 

 Error reading bibliography ./paper.bib (line 29, column 1):
unexpected "@"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by dntrinca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01588/joss.01588/10.21105.joss.01588.pdf)

**Comment by dntrinca** [comment]
Dear Daniel S Katz,

  Sorry for mispelling your name in a previous reply.

  Best,
  D Narcis

**Comment by danielskatz** [comment]
Please carefully proofread your submission, and add DOIs to the bib entries for papers that have DOIs, again following the example in the JOSS documentation.

**Comment by danielskatz** [comment]
👋 @usethedata - would you be willing to edit this submission?

**Comment by dntrinca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01588/joss.01588/10.21105.joss.01588.pdf)

**Comment by dntrinca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01588/joss.01588/10.21105.joss.01588.pdf)

**Comment by dntrinca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01588/joss.01588/10.21105.joss.01588.pdf)

**Comment by usethedata** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by usethedata** [comment]
@dntrinca This is interesting work and thanks for your submission.  However, we need to get a few more things take care of before this is ready to be reviewed.  The biggest is that the readme should be more extensive.  This is the key thing.  There should also be guidelines for people wanting to contribute to the effort and for those who are looking for support.  Please see the review criteria (https://joss.readthedocs.io/en/latest/review_criteria.html) for what we ask the reviewers to evaluate.

**Comment by dntrinca** [comment]
Dear Bruce Wilson, I will prepare this and reply to you soon. Best, D Narcis

**Comment by dntrinca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01588/joss.01588/10.21105.joss.01588.pdf)

**Comment by dntrinca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01588/joss.01588/10.21105.joss.01588.pdf)

**Comment by dntrinca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01588/joss.01588/10.21105.joss.01588.pdf)

**Comment by dntrinca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01588/joss.01588/10.21105.joss.01588.pdf)

**Comment by dntrinca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1588 with the following error: 

 Error reading bibliography ./paper.bib (line 62, column 1):
unexpected end of input
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by dntrinca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01588/joss.01588/10.21105.joss.01588.pdf)

**Comment by dntrinca** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01588/joss.01588/10.21105.joss.01588.pdf)

**Comment by dntrinca** [comment]
@usethedata , I just finished the necessary additions; let me know if this is OK..Best, D Narcis

**Comment by usethedata** [comment]
@dntrinca My apologies for being less responsive than I should.  It's been a crazy week. I'll go over things and start working on getting reviewers.

**Comment by dntrinca** [comment]
@usethedata Dear Bruce, That is very good, I am looking forward to hear from you soon. Best, D Narcis

**Comment by dntrinca** [comment]
@usethedata Dear Bruce, Did you find any reviewers ? I know it might be hard to find, as most of the scientific codes are in Matlab in general..But myself I wrote in Visual C++ to do a real Windows application, professionally written, and which does not require anything to be installed on a Windows system..

  Given the situation, do you think it is a priority to review the code ? The submission has a step-by step manual that shows all the functionalities if it is followed properly..

  Best, and let me know when you have some news..
  D Narcis

**Comment by martlj** [comment]
Hi, apologies for the slow reply. Medical CT is a bit outside of my usual domain and I don't use Windows either so I'm not best placed to give a thorough review of this I'm afraid.

**Comment by dntrinca** [comment]
@abhishekbajpayee @rlizzo @casperdcl Hello, is any of you willing to review this submission concerning a Windows program for tomography reconstruction? Best Regards, D Narcis

**Comment by dntrinca** [comment]
@usethedata @danielskatz  Hello, with this message I want to tell you that I withdraw my work from this journal..

**Comment by danielskatz** [comment]
I'm sorry to hear this, and that we didn't do a better job with this review.

**Comment by casperdcl** [comment]
yes sorry I work more in PET and PET-MRI, and also prefer avoiding windows and avoiding matlab.
