### ISSUE TITLE
[PRE REVIEW]: RiskPortfolios

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#159]
**Submitting author:** @ArdiaD (<a href="http://orcid.org/0000-0003-2823-782X">David Ardia</a>)
**Repository:** <a href="https://github.com/ArdiaD/RiskPortfolios" target ="_blank">https://github.com/ArdiaD/RiskPortfolios</a>
**Version:** 2.00.11
**Editor:** @arfon
**Reviewer:** @braverock

**What this issue is for**

Thanks for submitting your paper to JOSS @ArdiaD. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by arfon** [comment]
@ArdiaD - I'm not sure we have any obvious reviewers for this package. Are there people in your research field you'd be able to recommend as potential candidates?

**Comment by ArdiaD** [comment]
@arfon I think Enrico could do it, if time permits: enricoschumann on GitHub

**Comment by ArdiaD** [comment]
@arfon Also, MatthieuStigler on GitHub would be able to review, if he has enough time at disposal.

**Comment by arfon** [comment]
@enricoschumann @MatthieuStigler would either of you be willing to review this submission for JOSS? You can see an overview of our review process here: http://joss.theoj.org/about#reviewer_guidelines

**Comment by ArdiaD** [comment]
@arfon I think that @joshuaulrich would also be a good reviewer.

**Comment by MatthieuStigler** [comment]
Oh thanks David @ArdiaD ! I am afraid however this is a topic I am not familiar enough with to be able to review!

**Comment by arfon** [comment]
👋  @joshuaulrich  - would you be willing to review this submission for JOSS?

**Comment by joshuaulrich** [comment]
Thank you very much for the consideration, but I have to decline because I will be very short on time for the next few weeks.  I'm working to finish a project with a deadline looming in mid-February.  Please do consider me for other finance-related submissions though.

**Comment by ArdiaD** [comment]
Thanks @MatthieuStigler and @joshuaulrich for your feedback. @arfon what should we do then? Do you want me to try to provide additional references?

**Comment by arfon** [comment]
> Thanks @MatthieuStigler and @joshuaulrich for your feedback. @arfon what should we do then? Do you want me to try to provide additional references?

Yes please 🙏

**Comment by ArdiaD** [comment]
Ok, then I can imagine @braverock or @peterccarl, or @bpfaff. Also, @enricoschumann will still be willing to review. I know all of them, and I am convinced they will make the right comments to improve the package.

**Comment by arfon** [comment]
Thanks @ArdiaD. 

> Ok, then I can imagine @braverock or @peterccarl, or @bpfaff. Also, @enricoschumann is OK to review. I know all of them, and I am convinced they will make the right comments to improve the package.

👋  all. Would any of you be willing to review this submission for JOSS? You can read more about the reviewer process here: http://joss.theoj.org/about#reviewer_guidelines

**Comment by braverock** [comment]
@arfon, @ArdiaD I'd be happy to take a look at the submission.

It isn't clear to me from your reviewer guidelines where my feedback should go.

**Comment by arfon** [comment]
@whedon assign @braverock as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @braverock

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/171. Feel free to close this issue now!

**Comment by arfon** [comment]
> It isn't clear to me from your reviewer guidelines where my feedback should go.

Many thanks for agreeing to review this submission @braverock! This (pre review) issue is used to find a reviewer, the actual review thread with the checklist for you to work through is in #171. 

Please let me know if you have any questions as you make progress.
