### ISSUE TITLE
[REVIEW]: PyMarket

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1591]
**Submitting author:** @gus0k (<a href="http://orcid.org/0000-0001-8041-9685">Diego</a>)
**Repository:** <a href="https://github.com/gus0k/pymarket" target ="_blank">https://github.com/gus0k/pymarket</a>
**Version:** v0.7.8
**Editor:** @alexhanna
**Reviewer:** @igarizio, @taqtiqa-mark
**Archive:** <a href="https://doi.org/10.5281/zenodo.3665175" target="_blank">10.5281/zenodo.3665175</a>

## Status

[![status](http://joss.theoj.org/papers/2851d3edebf001a6784de629d3330532/status.svg)](http://joss.theoj.org/papers/2851d3edebf001a6784de629d3330532)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/2851d3edebf001a6784de629d3330532"><img src="http://joss.theoj.org/papers/2851d3edebf001a6784de629d3330532/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/2851d3edebf001a6784de629d3330532/status.svg)](http://joss.theoj.org/papers/2851d3edebf001a6784de629d3330532)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/gus0k/pymarket" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@igarizio & @taqtiqa-mark, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @alexhanna know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/gus0k/pymarket">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.7.8
- [x] **Authorship:** Has the submitting author (@gus0k) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
    -  ~gus0k/pymarket/issues/13~
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/gus0k/pymarket">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.7.8
    -  gus0k/pymarket/issues/4
- [x] **Authorship:** Has the submitting author (@gus0k) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
    - ~gus0k/pymarket/issues/3~
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
    - gus0k/pymarket/issues/5
    - gus0k/pymarket/issues/7
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
    - ~gus0k/pymarket/issues/3~
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?  
    -  ~gus0k/pymarket/issues/2~

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @igarizio, @taqtiqa-mark it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01591/joss.01591/10.21105.joss.01591.pdf)

**Comment by gus0k** [comment]
Hello,

Do you have anything so far that you would like me to fix or clarify?

Best regards,
K

**Comment by igarizio** [comment]
Hello @gus0k 👋,
Great work on PyMarket! It is really well written and nicely documented. Also, the idea behind it seems really useful.

Here are some of my comments:

- Software version: This may be silly, but I prefer to ask. The review states v0.7.4 but your last version is v0.7.5, I suppose you want to publish the last version, right? (@alexhanna if that is the case, is it possible to just change the version stated in this issue?)

- Authorship: Just wanted to check, but you own both @gus0k and @ellguso, right? (context: I was looking at the [contributors](https://github.com/gus0k/pymarket/graphs/contributors) part of your repo)

- Paper acknowledgement: Here I may be wrong, but I think the title "acknowledgement" may not be correct. What I generally see in the acknowledgement part is words of appreciation to other researchers, funding entities, etc. (@taqtiqa-mark, @alexhanna please let me know what you think).

- List of mechanisms: I think it would help people reading your paper if you added a list of the mechanisms implemented in the library (maybe you can even add this list to your README).

- Paper references: If you decide to add the list of mechanisms implemented, I think it would be appropriate to cite where those mechanisms come from (I think you already have those references inside huang_auction.py, muda_auction.py, etc.)

- Small detail: On the second page of the paper, it says "Figure 1: png".

I will continue to review the other items in the checklist and will post if necessary. Please let me know if you have any questions. 😃

**Comment by gus0k** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01591/joss.01591/10.21105.joss.01591.pdf)

**Comment by gus0k** [comment]
@whedon set v0.7.5 as version

**Comment by whedon** [comment]
I'm sorry @gus0k, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by gus0k** [comment]
@igarizio @taqtiqa-mark Thank you both so far for your input. I have updated the paper to list the implemented algorithms and their references.

@alexhanna  Would it be possible to update the version number to 0.7.5?

Regarding the acknowledgements, Telecom ParisTech is paying for my PhD. In that sense, I feel it plays the same role as funding entities. 

Best regards,
K

**Comment by gus0k** [comment]
@igarizio  @taqtiqa-mark , can I help you in any way to advance in your reviews?
 Best regards,
k

**Comment by alexhanna** [comment]
👋  @igarizio and @taqtiqa-mark, are you able to continue your reviews of this package?

**Comment by alexhanna** [comment]
@whedon set v0.7.5 as version

**Comment by whedon** [comment]
OK. v0.7.5 is the version.

**Comment by alexhanna** [comment]
@gus0k the version has been updated.

**Comment by gus0k** [comment]
Thank you.

**Comment by gus0k** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01591/joss.01591/10.21105.joss.01591.pdf)

**Comment by gus0k** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01591/joss.01591/10.21105.joss.01591.pdf)

**Comment by danielskatz** [comment]
👋 @alexhanna, it looks like reviewers still need to continue their reviews?

**Comment by alexhanna** [comment]
Hi @taqtiqa-mark, are you able to continue reviewing this?

👋 @igarizio, it looks like the last thing you need to check on the review is the functionality?

**Comment by igarizio** [comment]
👋 @alexhanna Yes, I am almost done.

**Comment by alexhanna** [comment]
Hi @taqtiqa-mark, checking in again. Can you confirm that the issues noted above have been adequately addressed?

**Comment by taqtiqa-mark** [comment]
No. I've opened gus0k/pymarket/issues/11 as an example of issues 5/7, and I've made a pull request  providing reproducible example.  I'll settle for just Ubuntu 16.04 instructions that work.

**Comment by gus0k** [comment]
@taqtiqa-mark Sorry for the dealy, it was a busy week. I have already addressed the issue. I think there was a problem with the python version you were using. I uploaded a working Docker with ubuntu 16.04

@igarizio Fixed the problem with too many bidders.

**Comment by gus0k** [comment]
@igarizio , it looks like you have finished. Is that ok?

**Comment by alexhanna** [comment]
Hi @taqtiqa-mark can you ensure that these issues have been addressed and check off the relevant boxes in your review?

**Comment by taqtiqa-mark** [comment]
@alexhanna As best I can tell the install instructions are not tested.  
@gus0k previously waved his hands that things work on Linux, but has now qualified that to a couple of distributions.  The install instructions have been updated to add some missing step. So we are making progress (painfully).
 
I've made another pull request, showing the install instructions will break the users pip installation on their computer - a big no-no.

Given the package is currently so small and has limited use cases, I have suggested to @gus0k that simply providing a link to a working Docker Container, and removing references to claims to work on Linux is the fastest path forward.

**Comment by labarba** [comment]
@gus0k — Could we have a status update of your work on responding to reviewer comments? Let me know if you want us to set a reminder for you.

**Comment by gus0k** [comment]
Hello,

I think I managed to fix the problem: provide working installation instructions and specify for which platforms does it work.
I just addressed @taqtiqa-mark last comment.

Best regards,
Diego

**Comment by alexhanna** [comment]
:wave: @taqtiqa-mark -- have you been able to have a look at these changes?

**Comment by taqtiqa-mark** [comment]
The install instructions now appear to work.  I haven't had time to check the remaning items.  Expect to this weekend.

**Comment by alexhanna** [comment]
👋 @taqtiqa-mark - have you been able to check the remaining items?

**Comment by taqtiqa-mark** [comment]
Apologies.  One of my parents has just died and am dealing with that - likely two weeks.

**Comment by gus0k** [comment]
@taqtiqa-mark I am very sorry to hear this. Please, take all the time you need.

**Comment by alexhanna** [comment]
Sorry to hear this, @taqtiqa-mark. Yes, please take your time.

**Comment by Kevin-Mattheus-Moerman** [comment]
@taqtiqa-mark we are sorry to hear about your loss. Let @alexhanna know whenever you are ready to resume this review. Thanks again for your help!

**Comment by taqtiqa-mark** [comment]
My apologies . I clean forgot about this.

**Comment by danielskatz** [comment]
Sorry for the delay here - it now looks like this is ready to publish, which I will proceed with the steps for.  If there's anything that's missing, either of the reviewers (@taqtiqa-mark or @igarizio) or the editor (@alexhanna) should speak up soon

**Comment by danielskatz** [comment]
👋 @gus0k - At this point could you:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g. figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.  As part of this, I will also be doing a careful proof read of the paper.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01591/joss.01591/10.21105.joss.01591.pdf)

**Comment by danielskatz** [comment]
some suggested changes for the paper are in https://github.com/gus0k/pymarket/pull/18 and for the bib are in https://github.com/gus0k/pymarket/pull/19

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/EEM.2017.7981938 is OK
- 10.1109/SmartGridComm.2017.8340728 is OK
- 10.1111/1467-8640.t01-1-00206 is OK
- 10.1088/1469-7688/2/5/303 is OK
- 10.1088/1469-7688/1/2/307 is OK

MISSING DOIs

- https://doi.org/10.1109/isgt.2019.8791585 may be missing for title: Strategy-proof local energy market with sequential stochastic decision process for battery control
- https://doi.org/10.1111/1467-937x.00171 may be missing for title: A decentralized market with common values uncertainty: Non-steady states

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
Also, please add the 2 missing DOIs above to the .bib file

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/EEM.2017.7981938 is OK
- 10.1109/SmartGridComm.2017.8340728 is OK
- 10.1109/ISGT.2019.8791585 is OK
- 10.1111/1467-937X.00171 is OK
- 10.1111/1467-8640.t01-1-00206 is OK
- 10.1088/1469-7688/2/5/303 is OK
- 10.1088/1469-7688/1/2/307 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01591/joss.01591/10.21105.joss.01591.pdf)

**Comment by danielskatz** [comment]
sorry, missed one in the bib - please merge https://github.com/gus0k/pymarket/pull/20 as well

**Comment by danielskatz** [comment]
also, be aware that you can do ```@whedon generate pdf``` to check the PDF when you choose to

**Comment by gus0k** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01591/joss.01591/10.21105.joss.01591.pdf)

**Comment by gus0k** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01591/joss.01591/10.21105.joss.01591.pdf)

**Comment by gus0k** [comment]
@danielskatz 
Created the tagged version (0.78) and uploaded it to zenodo:

10.5281/zenodo.3665175

**Comment by danielskatz** [comment]
@whedon set v0.7.8 as version

**Comment by whedon** [comment]
OK. v0.7.8 is the version.

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3665175 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3665175" target="_blank">10.5281/zenodo.3665175</a> is the archive.

**Comment by danielskatz** [comment]
Please change the metadata in the zenodo repository so that the title is the same as the title of the paper

**Comment by gus0k** [comment]
Done

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/EEM.2017.7981938 is OK
- 10.1109/SmartGridComm.2017.8340728 is OK
- 10.1109/ISGT.2019.8791585 is OK
- 10.1111/1467-937X.00171 is OK
- 10.1111/1467-8640.t01-1-00206 is OK
- 10.1088/1469-7688/2/5/303 is OK
- 10.1088/1469-7688/1/2/307 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1299

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1299, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1227604385645068288) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1300
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01591](https://doi.org/10.21105/joss.01591)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @igarizio & @taqtiqa-mark for reviewing!
And to @alexhanna for editing!

Congratulations to @gus0k and co-authors!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01591/status.svg)](https://doi.org/10.21105/joss.01591)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01591">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01591/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01591/status.svg
   :target: https://doi.org/10.21105/joss.01591
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01591/status.svg)](https://doi.org/10.21105/joss.01591)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by gus0k** [comment]
Thank you all!
