### ISSUE TITLE
[REVIEW]: ivis: dimensionality reduction in very large datasets using Siamese Networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1596]
**Submitting author:** @beringresearch (<a href="http://orcid.org/0000-0001-6727-4688">Ignat Drozdov</a>)
**Repository:** <a href="https://github.com/beringresearch/ivis" target ="_blank">https://github.com/beringresearch/ivis</a>
**Version:** v1.2.4
**Editor:** @lpantano
**Reviewer:** @SaskiaFreytag, @kevinrue
**Archive:** <a href="https://doi.org/10.5281/zenodo.3360634" target="_blank">10.5281/zenodo.3360634</a>

## Status

[![status](http://joss.theoj.org/papers/b498439c2585ddc954d80a89427b96e2/status.svg)](http://joss.theoj.org/papers/b498439c2585ddc954d80a89427b96e2)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/b498439c2585ddc954d80a89427b96e2"><img src="http://joss.theoj.org/papers/b498439c2585ddc954d80a89427b96e2/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/b498439c2585ddc954d80a89427b96e2/status.svg)](http://joss.theoj.org/papers/b498439c2585ddc954d80a89427b96e2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/beringresearch/ivis" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@SaskiaFreytag & @kevinrue, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/beringresearch/ivis">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.2.4
- [x] **Authorship:** Has the submitting author (@beringresearch) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/beringresearch/ivis">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.2.4
- [x] **Authorship:** Has the submitting author (@beringresearch) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @SaskiaFreytag, @kevinrue it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01596/joss.01596/10.21105.joss.01596.pdf)

**Comment by kevinrue** [comment]
# General checks
For the record, the submitting author (@beringresearch) is an institutional account representative of the affiliation of the authors who made major contributions to the software.
This is frequent practice and absolutely fine.

**Comment by SaskiaFreytag** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by SaskiaFreytag** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/s41598-019-45301-0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kevinrue** [comment]
@lpantano Both reviewers have ticked all our respective boxes. Let us know if you need anything else from us!

**Comment by lpantano** [comment]
Thank you so much, @kevinrue and @SaskiaFreytag!, I’ll move to final steps then.

**Comment by lpantano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01596/joss.01596/10.21105.joss.01596.pdf)

**Comment by lpantano** [comment]
Hi @beringresearch, can you create a Zenodo archive from your github and make sure it matches the title and authors of the paper?, thanks

**Comment by idroz** [comment]
Hi @lpantano , Zenodo archive should have already been created - https://zenodo.org/record/3268357#.XUguXi2ZPOQ

**Comment by lpantano** [comment]
@whedon set 10.5281/zenodo.3360569 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3360569" target="_blank">10.5281/zenodo.3360569</a> is the archive.

**Comment by lpantano** [comment]
@openjournals/joss-eics, reviewers are done, please, let us know if this is ready to go. Thanks everybody!

**Comment by kevinrue** [comment]
Argh, @lpantano was too fast for me. Here is what I was just typing:

As flattered as I am to be listed as a co-author on the citation in ZENODO 
> Cite as:
> Ignat Drozdov, Benjamin Szubert, beringresearch, & Kevin Rue-Albrecht. (2019, August 5). beringresearch/ivis 1.2.3-joss (Version 1.2.3-joss). Zenodo. http://doi.org/10.5281/zenodo.3360569

I think what Lorena needs (if it's possible) would be to only have " Ignat Drozdov & Benjamin Szubert" as authors.
Also, "beringresearch" is an affiliation rather than an author.

With regards to my contributions to the R package during the review process, I think the fairest approach would be to add this to the R package DESCRIPTION file:
```
c(person("Kevin", "Rue-Albrecht", role = "ctb", email = "kevin.rue-albrecht@kennedy.ox.ac.uk", comment = c(ORCID = "0000-0003-3899-3872"))
```
It declares that I contributed to, rather than authored, the package.
See http://r-pkgs.had.co.nz/description.html#author

**Comment by lpantano** [comment]
Good catch, I checked the previous version. @idroz, if you could update the metadata, please? or if you create a new version let me know, I can update both references. Thanks

**Comment by idroz** [comment]
Still getting to know my way around Zenodo! Author list should now be fixed. I have also modified R package DESCRIPTION file to acknowledge @kevinrue contribution. Thanks again!

**Comment by lpantano** [comment]
Thank you @idroz, but you may need to bump the version and get another zenodo. Right now DESCRIPTION in master has @kevinrue  as author, but not the zenodo archive file. It would be possible to create a v 1.2.4 to make sure we point to the final version and the zenodo points to the final version? Thanks!

**Comment by idroz** [comment]
v 1.2.4 released and author details synced across zenodo and GitHub.

**Comment by lpantano** [comment]
@whedon set v1.2.4 as version

**Comment by whedon** [comment]
OK. v1.2.4 is the version.

**Comment by lpantano** [comment]
Thanks, version looks good, and zenode as well, just need to update the title of the zenodo archive. The title should match the title of your paper (ivis: dimensionality reduction in very large datasets using Siamese Networks). thanks.

**Comment by idroz** [comment]
Done.

**Comment by lpantano** [comment]
@whedon set 10.5281/zenodo.3360634 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3360634" target="_blank">10.5281/zenodo.3360634</a> is the archive.

**Comment by lpantano** [comment]
thanks!

ok, @openjournals/joss-eics , this time for real. I think all makes sense now. Sorry about the noise.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/886

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/886, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1158544893356257280) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/887
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01596](https://doi.org/10.21105/joss.01596)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@SaskiaFreytag, @kevinrue - many thanks for your reviews here and to @lpantano for editing this submission ✨ 

@beringresearch - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01596/status.svg)](https://doi.org/10.21105/joss.01596)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01596">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01596/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01596/status.svg
   :target: https://doi.org/10.21105/joss.01596
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01596/status.svg)](https://doi.org/10.21105/joss.01596)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
