### ISSUE TITLE
[PRE REVIEW]: AltamISA: a Python API for ISA-Tab files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1597]
**Submitting author:** @holtgrewe (<a href="http://orcid.org/0000-0002-3051-1763">Manuel Holtgrewe</a>)
**Repository:** <a href="https://github.com/bihealth/altamisa" target ="_blank">https://github.com/bihealth/altamisa</a>
**Version:** v0.2.0
**Editor:** @lpantano
**Reviewers:** @tleonardi, @dsurujon, @dmnfarrell

**Author instructions**

Thanks for submitting your paper to JOSS @holtgrewe. **Currently, there isn't an JOSS editor assigned** to your paper.

@holtgrewe if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01597/joss.01597/10.21105.joss.01597.pdf)

**Comment by kyleniemeyer** [comment]
Hi @brainstorm, can you edit this submission?

**Comment by holtgrewe** [comment]
@dmnfarrel @tleonardi and @dsurujon would be three suitable candidates recently added to the list of volunteers that have specified both Python and bioinformatics as areas of expertise.

**Comment by tleonardi** [comment]
This seems a very interesting tool, I'd be happy to review the submission.

**Comment by dmnfarrell** [comment]
Yes I'd be willing to review this submission.

**Comment by dsurujon** [comment]
This looks very interesting! I'm happy to review the submission.

**Comment by kyleniemeyer** [comment]
Thanks @tleonardi @dmnfarrell and @dsurujon for responding so quickly! I am still waiting to get an editor assigned to manage the submission, but I will definitely take you all up on the offer to review.

**Comment by kyleniemeyer** [comment]
@whedon add @tleonardi as reviewer

**Comment by labarba** [comment]
👋 @holtgrewe — I am the Associate Editor-in-Chief on rotation this week, and will continue working to identify an editor to handle your submission.  But first, I need to ask you to add to the top of your paper:

> A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.

(From our [Documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain).)

Currently, you have an Introduction section that is laden with jargon. As it is, I (a non-specialist) will find it hard for to identify the right editor. Thanks!

**Comment by holtgrewe** [comment]
@labarba 👋 Thanks for raising this point. Would the following be sufficient and appropriately terse?

"AltamISA is a Python library for reading, validating, representing, and writing the ISA-Tab file format. ISA-Tab is an open, TSV-based file format for modeling and sharing life science experiments that is in use by various life science databases such as MetaboLights."

**Comment by labarba** [comment]
That's a start. How can a file format be used for _modeling_, though?

**Comment by holtgrewe** [comment]
Of course, you're right. I'd propose to adjust the introduction section to the following. It contains all information of the current version but the first paragraph should be understandable by a broad audience.

> AltamISA is a Python library for reading, validating, representing, and writing the ISA-Tab file format.
> ISA-Tab is an open, TSV (tab separated values)-based file format for representing the ISA (investigation study assay) tools data model [@Sansone:2012].
> The ISA tools data model allows for representing life science experiments and annotating the modeled objects and steps with arbitrary meta data.
> The ISA tools data model and TSV format are used by various life science databases, including MetaboLights [@Haug:2013].
>
> Shortly, the experimental process from sample extraction from a source (e.g., a donor individual) through processing of the samples to creating read-outs in one or more assays can be represented through DAGs (directed acyclic graphs) consisting of extensively annotatable so-called *material* and *process* nodes.
> Together, the ISA tools data model and ISA-Tab allow for representing most conceivable experiments in life science and to store them into machine-readable files for exchanging information about such experiments.
> This greatly facilitates the development of data management applications following the FAIR (findable, accessible, interoperable, and reusable, cf. @Wilkinson:2016) guidelines.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01597/joss.01597/10.21105.joss.01597.pdf)

**Comment by labarba** [comment]
That's much better!

I want to say that "shortly" is used in English to mean "in a little while" or "soon," so I think your word choice is not working at the start of paragraph 2.

**Comment by labarba** [comment]
👋 @lpantano — I believe this submission is within your domains of knowledge. Could you handle as editor?

It is a Python library for reading, validating, representing, and writing the ISA-Tab file format, used in life science experiments.

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
@whedon add @dsurujon as reviewer

**Comment by whedon** [comment]
OK, @dsurujon is now a reviewer

**Comment by lpantano** [comment]
@whedon add @dmnfarrell as reviewer

**Comment by whedon** [comment]
OK, @dmnfarrell is now a reviewer

**Comment by lpantano** [comment]
@tleonardi @dmnfarrell and @dsurujon, thank you to be a reviewer, if any of you don't have time anymore, let me know. We have three reviewers so it is fine if one cannot do it.Thanks!

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1610. Feel free to close this issue now!
