### ISSUE TITLE
[PRE REVIEW]: greta: simple and scalable statistical modelling in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1599]
**Submitting author:** @goldingn (<a href="http://orcid.org/0000-0001-8916-5570">Nick Golding</a>)
**Repository:** <a href="https://github.com/greta-dev/greta" target ="_blank">https://github.com/greta-dev/greta</a>
**Version:** 0.3.0
**Editor:** @terrytangyuan
**Reviewers:** @lionel68 @joethorley

**Author instructions**

Thanks for submitting your paper to JOSS @goldingn. **Currently, there isn't an JOSS editor assigned** to your paper.

@goldingn if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01599/joss.01599/10.21105.joss.01599.pdf)

**Comment by kyleniemeyer** [comment]
Hi @usethedata, do you have the bandwidth to edit this submission?

**Comment by goldingn** [comment]
Here's a list of potential reviewers from the reviewer list:
- becarioprecario
- mdogucu
- Volkerschmid
- lionel68
- joethorley
- fabian-s

**Comment by goldingn** [comment]
The paper is deliberately a bit longer than most JOSS manuscripts - including a code example over two pages. I thought I might as well make it an interesting read. Happy to discuss cutting it down if that's an issue.

**Comment by goldingn** [comment]
I suggested @usethedata for his statistical background. @terrytangyuan might also be interested in editing, given the TensorFlow angle.

**Comment by terrytangyuan** [comment]
Yes, I would definitely be interested in editing this if @usethedata is not available.

**Comment by kyleniemeyer** [comment]
@terrytangyuan it's all yours!

**Comment by kyleniemeyer** [comment]
@whedon assign @terrytangyuan as editor

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by kyleniemeyer** [comment]
@goldingn regarding the length, I don't think it is an issue. We don't publish articles with research reasults, but longer articles that describe the software and provide examples are fine (just not required).

**Comment by goldingn** [comment]
@kyleniemeyer ah that's great, thanks!

**Comment by terrytangyuan** [comment]
👋 @becarioprecario @mdogucu @Volkerschmid @lionel68 @joethorley @fabian-s If you are interested in reviewing this submission, please let us know here!

**Comment by joethorley** [comment]
@terrytangyuan I would like to review

**Comment by lionel68** [comment]
@terrytangyuan same here, would also be happy to review this manuscript.

**Comment by terrytangyuan** [comment]
@whedon assign @lionel68 @joethorley as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @lionel68 @joethorley

**Comment by terrytangyuan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1601. Feel free to close this issue now!

**Comment by terrytangyuan** [comment]
Thanks everyone! Let’s head over to https://github.com/openjournals/joss-reviews/issues/1601 for review.
