### ISSUE TITLE
Submission: R3D2: Relativistic Reactive Riemann problem solver for Deflagrations and Detonations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#16]
**Submitting author:** @harpolea (<a href="http://orcid.org/0000-0002-1530-781X">Alice Harpole</a>)
**Repository:** <a href="https://github.com/harpolea/r3d2" target ="_blank">https://github.com/harpolea/r3d2</a>
**Version:** v1.0
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.51096" target ="_blank">http://dx.doi.org/10.5281/zenodo.51096</a>

## Status

[![status](http://joss.theoj.org/papers/99f57be50022ae8b2eecdd1d28b05766/status.svg)](http://joss.theoj.org/papers/99f57be50022ae8b2eecdd1d28b05766)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/99f57be50022ae8b2eecdd1d28b05766"><img src="http://joss.theoj.org/papers/99f57be50022ae8b2eecdd1d28b05766/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/99f57be50022ae8b2eecdd1d28b05766/status.svg)]http://joss.theoj.org/papers/99f57be50022ae8b2eecdd1d28b05766
```

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/harpolea/r3d2">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Archive:** Does the <a target="_blank" href="http://dx.doi.org/10.5281/zenodo.51096">software archive</a> resolve?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have the performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Compiled paper PDF: [10.21105.joss.00016.pdf](https://github.com/openjournals/joss-reviews/files/286440/10.21105.joss.00016.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by gravypod** [comment]
I'll give it a look tomorrow if no one else has a chance. One just got to
take a quick few final exams today.

**Comment by kyleniemeyer** [comment]
This one is the first that probably falls under my area, so I should take a look.

**Comment by arfon** [comment]
OK @kyleniemeyer - thanks! @gravypod - looks like you're off the hook.

**Comment by kyleniemeyer** [comment]
Haven't forgotten about this, just been busy... plan to review this in the next day or so.

**Comment by kyleniemeyer** [comment]
OK, finally performed my review (sorry for the delay!). Here are my comments:

* No performance claims (other than in one place stating performance is poor), so technically this is question is satisfied.

* Typo in Usage section of the README (also first page of the docs): `eos = eos_defn.eos_gamma_law(5.0/3.0)` should be `eos = eos_defns.eos_gamma_law(5.0/3.0)`. In addition, that section could be improved with a bit more detail about what can be done with the `rp` object once the Riemann Problem has been solved. I can see quite nice detailed examples in the documentation, but something to complete that usage section (what to do with that result, for example) might be good.

* The code itself is not documented, and the online documentation (e.g., "Indices and Tables" section it empty/leads to broken pages).

* Regarding the statement of need, the paper (and software README) give fairly technical descriptions, and could both use a higher-level description of need/intended audience that would be more easily understood by a general reader. For example, many technical readers may not immediately know what the Riemann problem is, so a gentler introduction would help.

(I'll add that the detailed examples given in the [documentation on readthedocs](http://r3d2.readthedocs.io/) are great!)

**Comment by kyleniemeyer** [comment]
In fact, I went ahead and corrected the typo in the docs directly via harpolea/r3d2#2

**Comment by kyleniemeyer** [comment]
Of course, any other eyes on this (e.g., @gravypod) can only help.

**Comment by harpolea** [comment]
Thanks @kyleniemeyer - we've improved the documentation (adding docstrings to functions and removing the redundant 'Indices and Tables' section from the online docs) and the statement of need: harpolea/r3d2#3, harpolea/r3d2#4, harpolea/r3d2#5

**Comment by kyleniemeyer** [comment]
@harpolea those changes look good—did you update the paper with the new statement of need?

@arfon: where would an updated paper show up?

**Comment by arfon** [comment]
> @arfon: where would an updated paper show up?

I updated the paper in the original review issue.

**Comment by harpolea** [comment]
@kyleniemeyer Yes, we updated the paper to include more background information on the Riemann problem and its uses

**Comment by kyleniemeyer** [comment]
OK, at this point I think all the review criteria are satisfied.

@arfon recommend accepting now! (meta ?: should I let you add the "accepted" label, or do that myself?)

**Comment by arfon** [comment]
> @arfon recommend accepting now! (meta ?: should I let you add the "accepted" label, or do that myself?)

:boom: 🎉

**Comment by arfon** [comment]
@harpolea: http://dx.doi.org/10.21105/joss.00016 :zap: :boom: :rocket:
