### ISSUE TITLE
Mute this repo for all but review(s) to which one is assigned?

### ISSUE THREAD

**Issue by gavinsimpson** [openjournals/joss-reviews#160]
I've just agreed to provide a review for a JOSS submission but crikey that's a whole lot of email I'm now getting for the entire joss-reviews repo. Is there a way to mute the issues (reviews) I'm not involved in?

(Yes, I know I can filter the email into a folder, but I still need to parse the messages to see if any of them pertain to the one thing I involved with.)

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
> I've just agreed to provide a review for a JOSS submission but crikey that's a whole lot of email I'm now getting for the entire joss-reviews repo. Is there a way to mute the issues (reviews) I'm not involved in?

Yep, this is kind of a known issue. Apologies for the noise. There are some instructions on the review issue for your paper here that describe how to get rid of most of these notifications:

https://github.com/openjournals/joss-reviews/issues/161#issuecomment-271902496
