### ISSUE TITLE
[REVIEW]: greta: simple and scalable statistical modelling in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1601]
**Submitting author:** @goldingn (<a href="http://orcid.org/0000-0001-8916-5570">Nick Golding</a>)
**Repository:** <a href="https://github.com/greta-dev/greta" target ="_blank">https://github.com/greta-dev/greta</a>
**Version:** 0.3.1
**Editor:** @terrytangyuan
**Reviewers:** @lionel68, @joethorley, @lionel68
**Archive:** <a href="https://doi.org/10.5281/zenodo.819476" target="_blank">10.5281/zenodo.819476</a>

## Status

[![status](http://joss.theoj.org/papers/62e62338d8ba44ff9e5dc295cf631477/status.svg)](http://joss.theoj.org/papers/62e62338d8ba44ff9e5dc295cf631477)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/62e62338d8ba44ff9e5dc295cf631477"><img src="http://joss.theoj.org/papers/62e62338d8ba44ff9e5dc295cf631477/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/62e62338d8ba44ff9e5dc295cf631477/status.svg)](http://joss.theoj.org/papers/62e62338d8ba44ff9e5dc295cf631477)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/greta-dev/greta" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@lionel68 @joethorley, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @terrytangyuan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/greta-dev/greta">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.3.1
- [x] **Authorship:** Has the submitting author (@goldingn) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/greta-dev/greta">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.3.1
- [x] **Authorship:** Has the submitting author (@goldingn) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lionel68 @joethorley it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01601/joss.01601/10.21105.joss.01601.pdf)

**Comment by joethorley** [comment]
@goldingn greta is a fantastic piece of software. I just have three minor issues that need to be addressed

https://github.com/greta-dev/greta/issues/295
https://github.com/greta-dev/greta/issues/296
https://github.com/greta-dev/greta/issues/297

**Comment by goldingn** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01601/joss.01601/10.21105.joss.01601.pdf)

**Comment by goldingn** [comment]
Thanks @joethorley!

Resolved two of those issues now. The last formatting issue (#297) doesn't seem to be present in the article proof, but I may have misunderstood.

**Comment by terrytangyuan** [comment]
Nice job @goldingn and thanks @joethorley for the review!
👋 @lionel68 Have you got a chance to review this paper yet?

**Comment by lionel68** [comment]
On my agenda for this friday :) @terrytangyuan

**Comment by goldingn** [comment]
Thanks for the review @joethorley! There's one item (references) still unchecked in your review list. I think that's resolved now.

**Comment by lionel68** [comment]
@whedon @terrytangyuan I am starting the review but I can't seem to be able to update the review checklist above. Am I missing something?

**Comment by terrytangyuan** [comment]
It looks like you are not a collaborator of this repo, @kyleniemeyer could you help take a look?

**Comment by lionel68** [comment]
greta is a very promising software and is likely to become a very handy tool in the data scientist toolbox.

I opened three issues:

greta-dev/greta#299 (example R code not running on my laptop)
greta-dev/greta#300 (python warnings when running greta::model)
greta-dev/greta#301 (minor textual comments)

Looking forward to using the capacities of greta.

**Comment by kyleniemeyer** [comment]
@whedon add @lionel68 as reviewer

**Comment by whedon** [comment]
OK, @lionel68 is now a reviewer

**Comment by kyleniemeyer** [comment]
@lionel68 can you edit the checklist now?

**Comment by lionel68** [comment]
Yes it works thanks @whedon and @kyleniemeyer , I'll finish filling the checklist early on next week!

**Comment by goldingn** [comment]
Hi @terrytangyuan, how does the JOSS review process deal with changing version numbers, and things like CRAN submission?

There's a version 0.3.0 of greta on CRAN (and in the GitHub commit history), and a development version currently at 0.3.0.9008 on GitHub. On submission I stated that review is for 0.3.0, and @lionel68 reviewed that version exactly. He hit an issue which I'm pretty sure is fixed in the dev version.

I'd like to wrap that and any other fixes that come from this review into a 0.3.1 release candidate and push that to CRAN. I'd like all non-dev versions to be released on CRAN.

How does the following procedure sound:

1. complete review of the paper and software on the dev version of greta
2. submit that to CRAN as 0.3.1
3. on acceptance to CRAN, update both the greta master branch and the JOSS version of record to 0.3.1
4. hit the publish button on JOSS

I'm sure this is something that has come up before for the journal, so let me know if I'm overthinking it.

---

P.S. I'd also love to have the JOSS citation in the next CRAN release, but that might be a bit circular!

**Comment by terrytangyuan** [comment]
@goldingn Yes, we can update the version number here through a `@whedon` command prior to JOSS paper publication/acceptance. So your outlined procedure looks fine to me. Before step 4, you'll need to create an archive on services like Zenondo (I'll provide more details on the requirements once accepted).

**Comment by goldingn** [comment]
Great, thanks @terrytangyuan. I'll do that and leave off on the citation then.

**Comment by lionel68** [comment]
The issue I had with the example code were resolved by installing the dev version of greta from Github. I now checked all review items in the list above.

**Comment by goldingn** [comment]
The new release is running the gauntlet at CRAN...

**Comment by goldingn** [comment]
OK, accepted on CRAN and updated on Github master.

@terrytangyuan, could you please change the version of record to 0.3.1?

I think all of the reviewers' comments have been addressed now too.

**Comment by joethorley** [comment]
I am happy

**Comment by terrytangyuan** [comment]
@whedon set 0.3.1 as version

**Comment by whedon** [comment]
OK. 0.3.1 is the version.

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by terrytangyuan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1080/10618600.2016.1172487 is OK
- 10.18637/jss.v076.i01 is OK
- 10.7717/peerj-cs.55 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by terrytangyuan** [comment]
Thank you!

@goldingn - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

* The title of the archive is the same as the JOSS paper title
* That the authors of the archive are the same as the JOSS paper authors
I can then move forward with accepting the submission.

**Comment by goldingn** [comment]
This version of the software is now released on GitHub and on CRAN. Here's a figshare archive of this version of the software:
https://doi.org/10.6084/m9.figshare.9461447.v1
Title and authors are the same as this paper.

**Comment by terrytangyuan** [comment]
@whedon set 10.5281/zenodo.819476 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.819476" target="_blank">10.5281/zenodo.819476</a> is the archive.

**Comment by terrytangyuan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01601/joss.01601/10.21105.joss.01601.pdf)

**Comment by terrytangyuan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1080/10618600.2016.1172487 is OK
- 10.18637/jss.v076.i01 is OK
- 10.7717/peerj-cs.55 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/892

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/892, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by terrytangyuan** [comment]
The paper looks good to me. I am handing this over to our editors-in-chief now. @openjournals/joss-eics

**Comment by goldingn** [comment]
Thanks @terrytangyuan!

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1160897306348179456) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/895
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01601](https://doi.org/10.21105/joss.01601)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@lionel68, @joethorley, @lionel68 -  many thanks for your reviews and to @terrytangyuan for editing this submission.

@goldingn - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01601/status.svg)](https://doi.org/10.21105/joss.01601)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01601">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01601/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01601/status.svg
   :target: https://doi.org/10.21105/joss.01601
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01601/status.svg)](https://doi.org/10.21105/joss.01601)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
