### ISSUE TITLE
[REVIEW]: containerit: Generating Dockerfiles for reproducible research with R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1603]
**Submitting author:** @nuest (<a href="http://orcid.org/0000-0002-0024-5046">Daniel Nüst</a>)
**Repository:** <a href="https://github.com/o2r-project/containerit/" target ="_blank">https://github.com/o2r-project/containerit/</a>
**Version:** 0.6.0
**Editor:** @terrytangyuan
**Reviewer:** @vsoch, @cole-brokamp
**Archive:** <a href="https://doi.org/10.5281/zenodo.3373289" target="_blank">10.5281/zenodo.3373289</a>

## Status

[![status](http://joss.theoj.org/papers/6f3b6a7cca0fa133966f13f260f0360d/status.svg)](http://joss.theoj.org/papers/6f3b6a7cca0fa133966f13f260f0360d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/6f3b6a7cca0fa133966f13f260f0360d"><img src="http://joss.theoj.org/papers/6f3b6a7cca0fa133966f13f260f0360d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/6f3b6a7cca0fa133966f13f260f0360d/status.svg)](http://joss.theoj.org/papers/6f3b6a7cca0fa133966f13f260f0360d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/o2r-project/containerit/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@vsoch & @cole-brokamp, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @terrytangyuan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/o2r-project/containerit/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x]  **Version:** 0.6.0
- [x] **Authorship:** Has the submitting author (@nuest) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/o2r-project/containerit/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.6.0
- [x] **Authorship:** Has the submitting author (@nuest) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @vsoch it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01603/joss.01603/10.21105.joss.01603.pdf)

**Comment by vsoch** [comment]
hey everyone! I'll be able to start my review tomorrow. Looking forward to it.

**Comment by vsoch** [comment]
## Review issues:
 - [ ] [Request for Proofreader](https://github.com/o2r-project/containerit/issues/153) the paper needs a native English speaker to read over first, there are many mistakes with grammar and sentence structure. I'll start my review after this. Thanks everyone!

**Comment by nuest** [comment]
I'll organise a proofreading and will update both https://github.com/o2r-project/containerit/issues/153 and here.

**Comment by nuest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01603/joss.01603/10.21105.joss.01603.pdf)

**Comment by terrytangyuan** [comment]
👋 @vsoch @cole-brokamp Looks like the paper has been revised. Would you be able to start the review soon?

**Comment by vsoch** [comment]
I already started the review, per the linked issue that is open (linked above) and the authors are reviewing.  I’ll continue my review when they update that issue.

**Comment by vsoch** [comment]
And actually I forgot to link this one – sorry about that! https://github.com/o2r-project/containerit/issues/156

**Comment by cole-brokamp** [comment]
Also just added some of my own issues and comments as a part of my review over here: https://github.com/o2r-project/containerit/issues/159

**Comment by nuest** [comment]
I've collected my updates based on reviewer feedback in this PR: https://github.com/o2r-project/containerit/pull/160 (Tests also work again).

I suggest to merge that PR and update the tag as soon as the reviewers confirm everything mention so far is addressed.

@cole-brokamp The only open thread AFAICS is the problem that the printing did not work properly during your tests: https://github.com/o2r-project/containerit/issues/159#issuecomment-521924165 It would be great if you could try again.

**Comment by vsoch** [comment]
@nuest now that testing is fixed and you've made good changes to the docs and paper, when the pull request is merged (and I've checked the version) I can finish up the review. Thanks for your hard work on this!

**Comment by cole-brokamp** [comment]
Everything looking good to me.  I'm all checked off.  Thanks!

**Comment by nuest** [comment]
:tada: Thank you @vsoch and @cole-brokamp for the great review experience and the useful feedback, especially on improving the manuscript and increasing accessibility for newcomers and potential contributors.

https://github.com/o2r-project/containerit/pull/160 is merged.

**Comment by nuest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01603/joss.01603/10.21105.joss.01603.pdf)

**Comment by nuest** [comment]
I also updated the tag: https://github.com/o2r-project/containerit/releases/tag/v0.5.0

_Is it time now to create the release on Zenodo?_

**Comment by nuest** [comment]
I also updated the tag: https://github.com/o2r-project/containerit/releases/tag/v0.5.0

_Is it time now to create the release on Zenodo_ @terrytangyuan _?_

**Comment by nuest** [comment]
FYI: I'm currently fixing some small glitches since an online resource used in the tests is not available right now. Hardening the tests should do it.

**Comment by nuest** [comment]
Everything's in order now (https://github.com/o2r-project/containerit/releases/tag/v0.5.0). Also fixed a DOI URL, so...

@whedon generate pdf

**Comment by nuest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01603/joss.01603/10.21105.joss.01603.pdf)

**Comment by vsoch** [comment]
@nuest has addressed all of my issues! Here are the first two that I forgot to link:

 - https://github.com/o2r-project/containerit/issues/153
 - https://github.com/o2r-project/containerit/issues/156

The last little bit would be to bump the version, in the case that the software was tweaked for review? That's my last bullet, so when we've verified the version, and released on Zenodo, I recommend this software for publication in JoSS. Great job addressing all of the concerns @nuest!

**Comment by terrytangyuan** [comment]
Thanks everyone! @nuest does v0.5.0 contain all the fixes you want or do you still need to release another one?

**Comment by vsoch** [comment]
Version 0.5.0 was the original that was submit, so I think given the changes probably another release is needed?

**Comment by terrytangyuan** [comment]
Yes, @nuest please release another version and then I’ll update the version number here.

**Comment by nuest** [comment]
Version `0.6.0` is released on GitHub: https://github.com/o2r-project/containerit/releases/tag/v0.6.0

May I release to Zenodo?

**Comment by terrytangyuan** [comment]
@whedon set 0.6.0 as version

**Comment by whedon** [comment]
OK. 0.6.0 is the version.

**Comment by terrytangyuan** [comment]
Yes @nuest. Please make sure the authors field and version in Zenondo match with the paper.

**Comment by vsoch** [comment]
Whomever checked my version box, thanks! I was just checking it now :)

**Comment by nuest** [comment]
Zenodo repository: https://zenodo.org/record/3373289

DOI: `10.5281/zenodo.3373289`

**Comment by terrytangyuan** [comment]
@whedon set 10.5281/zenodo.3373289 as doi

**Comment by terrytangyuan** [comment]
@whedon set 10.5281/zenodo.3373289 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3373289" target="_blank">10.5281/zenodo.3373289</a> is the archive.

**Comment by terrytangyuan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/nbt.3780 is OK
- 10.1186/s13742-015-0087-0 is OK
- 10.1145/2723872.2723882 is OK
- 10.32614/RJ-2017-065 is OK
- 10.1145/2882903.2899401 is OK
- 10.1145/2889160.2891057 is OK
- 10.2218/ijdc.v12i2.509 is OK
- 10.1198/106186007X178663 is OK
- 10.1093/bioinformatics/btw120 is OK
- 10.5063/schema/codemeta-2.0 is OK
- 10.1007/978-3-319-96418-8_34 is OK
- 10.1101/116962 is OK
- 10.3390/rs9030290 is OK
- 10.1371/journal.pone.0177459 is OK
- 10.1007/s10816-015-9272-9 is OK
- 10.1016/j.ascom.2018.08.003 is OK
- 10.5281/zenodo.2203844 is OK
- 10.1045/january2017-nuest is OK
- 10.25080/Majora-4af1f417-011 is OK
- 10.11588/heibooks.285.377 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/916

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/916, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by terrytangyuan** [comment]
This paper looks good to me now. I am handing this over to our editors-in-chief now. @openjournals/joss-eics

**Comment by kyleniemeyer** [comment]
Hi @nuest—I did some minor final copyediting, if you could merge these PRs: https://github.com/o2r-project/containerit/pull/166 and https://github.com/o2r-project/containerit/pull/167

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by nuest** [comment]
Merged! Would you like me to update the Zenodo deposit (and get a new DOI) ?

**Comment by kyleniemeyer** [comment]
@nuest that isn't necessary, since JOSS archives the final version of the paper itself

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01603/joss.01603/10.21105.joss.01603.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/919

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/919, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1164223667196321795) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/920
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01603](https://doi.org/10.21105/joss.01603)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by vsoch** [comment]
Congrats @nuest !

**Comment by kyleniemeyer** [comment]
Congrats @nuest on your article's publication in JOSS! Many thanks to @terrytangyuan for editing, and @vsoch and @cole-brokamp for reviewing this submission.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01603/status.svg)](https://doi.org/10.21105/joss.01603)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01603">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01603/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01603/status.svg
   :target: https://doi.org/10.21105/joss.01603
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01603/status.svg)](https://doi.org/10.21105/joss.01603)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by nuest** [comment]
**Thank you all!** :clap: :heart: This review was a real fun thing to do!
