### ISSUE TITLE
[PRE REVIEW]: Graph Transliterator: a graph-based transliteration tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1604]
**Submitting author:** @seanpue (<a href="http://orcid.org/0000-0001-8463-8578">A. Sean Pue</a>)
**Repository:** <a href="https://github.com/seanpue/graphtransliterator" target ="_blank">https://github.com/seanpue/graphtransliterator</a>
**Version:** v0.2.7
**Editor:** @gkthiruvathukal
**Reviewers:** @rlskoeser, @vc1492a

**Author instructions**

Thanks for submitting your paper to JOSS @seanpue. **Currently, there isn't an JOSS editor assigned** to your paper.

@seanpue if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01604/joss.01604/10.21105.joss.01604.pdf)

**Comment by kyleniemeyer** [comment]
Hi @gkthiruvathukal, the author of this submission suggested you as editor. Do you have the bandwidth to handle this one?

**Comment by gkthiruvathukal** [comment]
@kyleniemeyer I'm pretty sure I can handle it. Most of my assignments are moving toward a conclusion, so I am willing. After this, I might need to pause until late August as I will be on vacation starting August 10th with classes resuming on the 26th. Please go ahead and assign me.

**Comment by kyleniemeyer** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by kyleniemeyer** [comment]
@gkthiruvathukal thanks! and sounds good, just email the AEiCs to let us know your plans and we can avoid assigning anything to you.

**Comment by gkthiruvathukal** [comment]
@kyleniemeyer Thanks! I will get moving on this review now.

**Comment by gkthiruvathukal** [comment]
@seanpue, if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Comment by gkthiruvathukal** [comment]
@seanpue, did you see my follow-up? Please respond and let me know any potential reviewers. Please also let me know if you still want your submission reviewed. As you have not responded to my query in 24 days, I am concerned you will not be responsive once review actually starts. I will only commence review once I receive a response. It would be greatly helpful if you can suggest reviewers from the list as previously requested.

**Comment by seanpue** [comment]
Hi @gkthiruvathukal Sorry for the delay. As an academic, I do not normally recommend reviewers. I also don't know many people on that list. I would suggest at least one reviewer with good Python, someone with some CS or basic graph theory background (particularly to check my descriptions), and also NLP, computational linguistics, or digital humanities. So quickly skimming that list, I would suggest desilinguist, mbod, rlskoeser, jkhan,richardlitt, linuxscout, alexhanna, or adammichaelwood. I will respond quickly to any further message. Thanks!

**Comment by gkthiruvathukal** [comment]
Hi @seanpue, thanks for the response! I'm an academic here, too, but we use a slightly different model here at JOSS, especially since the review takes place in the open.  As reviewers start woring on your submission, they'll raise comments and issues, and you'll be able to respond to them.  Thanks for responding. I will see who is willing to review, and we'll go from there!

**Comment by gkthiruvathukal** [comment]
@desilinguist, @mbod, @rlskoeser, @jkhan,richardlitt, @linuxscout, @alexhanna, or @adammichaelwood: I need two reviewers to help contribute a review for this submission. Please let me know if you are willing and able to help. I will probably go with first come, first served scheduling to make the two assignments.  Thank you for your consideration!

**Comment by rlskoeser** [comment]
@gkthiruvathukal I'm willing to review.

**Comment by seanpue** [comment]
Hey @gkthiruvathukal Since @rlskoeser has the digital humanities, text-analysis, and nlp covered, perhaps you could ask people who do more general graphs and/or algorithms. From that list: hausen, gabrielspadon, juliohm, sonal-raj, vc1492a (also NLP, missed earlier), camillescott, szhorvat, amritagos.  Cheers.

**Comment by gkthiruvathukal** [comment]
Thanks, @seanpue 

@hausen, @gabrielspadon, @juliohm, @sonal-raj, @vc1492a, @camillescott, @szhorvat, @amritagos, are any of you willing to act as an additional reviewer for this submission, focused on the graph/algorithmic aspects? Once I have a second reviewer, I can commence review of @seanpue's submission.

**Comment by vc1492a** [comment]
@gkthiruvathukal Thanks for the consideration, willing and happy to review this. Bandwidth has been a little tight as of late but this project is very interesting to me and I would enjoy the opportunity to perform and provide a review. You may want to add a third reviewer for NLP - I have some experience in this area but my experience is far from extensive.

**Comment by gkthiruvathukal** [comment]
So grateful @rlskoeser and @vc1492a. I will assign both of you and get the review started.

**Comment by gkthiruvathukal** [comment]
@whedon assign @rlskoeser as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rlskoeser

**Comment by gkthiruvathukal** [comment]
@whedon add @vc1492a as reviewer

**Comment by whedon** [comment]
OK, @vc1492a is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1717. Feel free to close this issue now!
