### ISSUE TITLE
[PRE REVIEW]: anytime: Anything to Datetime or Date Converter

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1605]
**Submitting author:** @eddelbuettel (<a href="http://orcid.org/0000-0001-6419-907X">Dirk Eddelbuettel</a>)
**Repository:** <a href="https://github.com/eddelbuettel/anytime" target ="_blank">https://github.com/eddelbuettel/anytime</a>
**Version:** v0.3.5
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @eddelbuettel. **Currently, there isn't an JOSS editor assigned** to your paper.

@eddelbuettel if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01605/joss.01605/10.21105.joss.01605.pdf)

**Comment by kyleniemeyer** [comment]
Hi @eddelbuettel, thanks for your interest in JOSS.  From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). In particular, these items:

> - Your software should have an obvious research application
> - The software should be feature complete (no half-baked solutions) and designed for maintainable extension (not one-off modifications). Minor ‘utility’ packages, including ‘thin’ API clients, are not acceptable.

Could you confirm here that there _is_ a research application for this software (and explain what that application is)? I'm also a little concerned that, while useful, the software is more of a utility than research software; the spirit of the criteria is that the software contributes to obtaining results in a scientific analysis.

Thanks!

**Comment by eddelbuettel** [comment]
@kyleniemeyer thanks for the prompt follow-up!  The core contribution of `anytime` is a faithful, performant and easier-than-alternatives conversion of _any_ input. This may frequently be a text format variable that may often be in a not-quite-standard form, but can also be numeric or another variant.  `anytime` converts from a large variety of text formats, as well from 'other' numeric forms to the desired and trusted Date or Datetime format, and does it fast (using underlying C++ code) and without additional user input,  

This enables any research relying on time-stamped data input that is not yet in proper time forma to (more) easily convert the input data for subsequent research use, and forms part of a any data processiing pipeline involving date or datetime inputs.

**Comment by labarba** [comment]
@eddelbuettel —
After a pre-review of your submission, and an assessment by the editorial board at large, we find that this submission does not quite meet our [submission requirements](http://joss.theoj.org/about#submission_requirements). In particular, while the software seems very useful, it falls under the 'Minor utility' category, and we therefore decided not to put it through review. 

Thank you for considering JOSS as a venue for your software, and I hope you'll submit other software with research application in the future.
