### ISSUE TITLE
[REVIEW]: X.509 Compliant Hybrid Certificates for the Post-Quantum Transition

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1606]
**Submitting author:** @j-braun (<a href="http://orcid.org/0000-0001-6491-2250">Johannes Braun</a>)
**Repository:** <a href="https://github.com/CROSSINGTUD/bc-hybrid-certificates" target ="_blank">https://github.com/CROSSINGTUD/bc-hybrid-certificates</a>
**Version:** 1.0.1
**Editor:** @danielskatz
**Reviewer:** @jbasney, @jteheran
**Archive:** <a href="https://doi.org/10.5281/zenodo.3365786" target="_blank">10.5281/zenodo.3365786</a>

## Status

[![status](http://joss.theoj.org/papers/04d39dd271866597b0f7f9bcc4434968/status.svg)](http://joss.theoj.org/papers/04d39dd271866597b0f7f9bcc4434968)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/04d39dd271866597b0f7f9bcc4434968"><img src="http://joss.theoj.org/papers/04d39dd271866597b0f7f9bcc4434968/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/04d39dd271866597b0f7f9bcc4434968/status.svg)](http://joss.theoj.org/papers/04d39dd271866597b0f7f9bcc4434968)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/CROSSINGTUD/bc-hybrid-certificates" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jbasney & @jteheran, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/CROSSINGTUD/bc-hybrid-certificates">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.0.1
- [x] **Authorship:** Has the submitting author (@j-braun) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/CROSSINGTUD/bc-hybrid-certificates">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.0.1
- [x] **Authorship:** Has the submitting author (@j-braun) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jbasney, @jteheran it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01606/joss.01606/10.21105.joss.01606.pdf)

**Comment by danielskatz** [comment]
👋 @jbasney, @jteheran - Here's where we do the review - please read the comments in this issue for instructions, but basically, your job is to either check off your items in the first comment or explain why you can't - either briefly here, or by opening issues in the source repo and mentioning this issue in them to create a link from here to there.

Thanks for being willing to do this, and if you have any questions, please ask me

**Comment by danielskatz** [comment]
👋 @j-braun - note that there are a couple of issues waiting for your response

**Comment by j-braun** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01606/joss.01606/10.21105.joss.01606.pdf)

**Comment by j-braun** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01606/joss.01606/10.21105.joss.01606.pdf)

**Comment by j-braun** [comment]
@danielskatz  - we took care of the issues and fixed them

**Comment by danielskatz** [comment]
👋 @jbasney, @jteheran - please check and see what else needs to be done, if anything

**Comment by jbasney** [comment]
looks good to me

**Comment by jteheran** [comment]
looks good to me too

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01606/joss.01606/10.21105.joss.01606.pdf)

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/978-3-319-59879-6_22 is OK
- 10.5281/zenodo.3364471 is OK
- 10.1109/SFCS.1994.365700 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@j-braun - please merge https://github.com/CROSSINGTUD/bc-hybrid-certificates/pull/4 or let me know any changes you don't agree with.

**Comment by danielskatz** [comment]
After that, please make a Zenodo archive of the software, and report the DOI here.  If the version number has changed, please report that here as well.

**Comment by j-braun** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01606/joss.01606/10.21105.joss.01606.pdf)

**Comment by j-braun** [comment]
@danielskatz I agreed to your changes, and only fixed one last typo.
Version is now v1.0.1
DOI: 10.5281/zenodo.3365225 

@danielskatz, @jbasney, @jteheran -  thank you very much for your quick review and support

**Comment by danielskatz** [comment]
@whedon set 1.0.1 as version

**Comment by whedon** [comment]
OK. 1.0.1 is the version.

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3365225 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3365225" target="_blank">10.5281/zenodo.3365225</a> is the archive.

**Comment by danielskatz** [comment]
@j-braun - Can you change the title of the zenodo archive to match the paper title?

**Comment by j-braun** [comment]
@danielskatz - Updating the title in Zenodo was not possible. Instead Icreated a new release matching the paper title. This triggered a new archive, but also created a new DOI.
DOI: 10.5281/zenodo.3365786 
hope this is ok.

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3365786 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3365786" target="_blank">10.5281/zenodo.3365786</a> is the archive.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1160812495495471104) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/894
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01606](https://doi.org/10.21105/joss.01606)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
@jbasney, @jteheran - thanks very much for reviewing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01606/status.svg)](https://doi.org/10.21105/joss.01606)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01606">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01606/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01606/status.svg
   :target: https://doi.org/10.21105/joss.01606
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01606/status.svg)](https://doi.org/10.21105/joss.01606)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
