### ISSUE TITLE
[PRE REVIEW]: Ryacas: A computer algebra system in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1607]
**Submitting author:** @mikldk (<a href="http://orcid.org/0000-0002-0234-0266">Mikkel Meyer Andersen</a>)
**Repository:** <a href="https://github.com/mikldk/ryacas" target ="_blank">https://github.com/mikldk/ryacas</a>
**Version:** v1.0.0
**Editor:** @drvinceknight
**Reviewers:** @MikeLydeamore, @EduPH

**Author instructions**

Thanks for submitting your paper to JOSS @mikldk. **Currently, there isn't an JOSS editor assigned** to your paper.

@mikldk if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01607/joss.01607/10.21105.joss.01607.pdf)

**Comment by labarba** [comment]
@mikldk —
After a pre-review of your submission, and an assessment by the editorial board at large, we find that this submission does not quite meet our [submission requirements](http://joss.theoj.org/about#submission_requirements). In particular, while the software seems very useful, it falls under the 'minor utility/thin wrapper' category, and we therefore decided not to put it through review. 

Thank you for considering JOSS as a venue for your software, and I hope you'll submit other software with research application in the future.

**Comment by mikldk** [comment]
@labarba Thank you very much for considering our submission. We acknowledge your judgement of the submission we made. At the time of submission we had already been working on an extension package for a while that integrated `R` and `yacas` much more closely, e.g. using `yacas` matrices as `R` matrices (with `[` subsetting, finding inverses via `solve()` etc.). The idea was to release it separately afterwards, but based on your judgement we have spent the last week on finishing it and have now fully integrated the functionality into `Ryacas` ([PR#30](https://github.com/mikldk/ryacas/pull/30) and following commit(s)).

May I highlight the updated [README](http://mikldk.github.io/ryacas/index.html) and vignette ["Getting started"](http://mikldk.github.io/ryacas/articles/getting-started.html) as well as the new the vignettes ["The high-level (symbol) interface"](http://mikldk.github.io/ryacas/articles/high-level.html) and ["Arbitrary-precision arithmetic"](http://mikldk.github.io/ryacas/articles/arbitrary-precision.html).

We now believe that the package is much more complete and that it adds much more to `R` than "just" being a thin way to call `yacas` commands. We therefore kindly ask you to reconsider our submission with these additions.

**Comment by mikldk** [comment]
Here is a blog post demonstrating usage of the package: <https://mikl.dk/post/2019-pizza-frozen-yogurt/> (mainly under the "Finding the optimal consumption" section).

**Comment by labarba** [comment]
@openjournals/joss-eics : The author of this rejected submission requests that we have a second look.

**Comment by kthyng** [comment]
Hi @drvinceknight! How about another submission? It looks like you are more in the Python community, but as long as you can find reviewers that are comfortable with R, you should be fine.

**Comment by drvinceknight** [comment]
Yup :) @kthyng :+1:

**Comment by drvinceknight** [comment]
@whedon assign @drvinceknight as editor

**Comment by whedon** [comment]
OK, the editor is @drvinceknight

**Comment by drvinceknight** [comment]
@arfon, sorry for the ping but this paper does not appear in my dashboard: have I done something incorrectly?

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1607 with the following error: 

 Can't find any papers to compile :-(

**Comment by drvinceknight** [comment]
@mikldk the pdf fails to compile (see error above), looking at your repo it does not look like there's a `paper.md` file present.

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01607/joss.01607/10.21105.joss.01607.pdf)

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01607/joss.01607/10.21105.joss.01607.pdf)

**Comment by mikldk** [comment]
@drvinceknight sorry about that. Now it's there.

**Comment by arfon** [comment]
@whedon assign @drvinceknight as editor

**Comment by whedon** [comment]
OK, the editor is @drvinceknight

**Comment by arfon** [comment]
> @arfon, sorry for the ping but this paper does not appear in my dashboard: have I done something incorrectly?

Should be showing up now. We just found an edge-case (bug) in the system :-)

**Comment by drvinceknight** [comment]
> @drvinceknight sorry about that. Now it's there.

Thanks @mikldk, I will proceed to identify reviewers.


> Should be showing up now. We just found an edge-case (bug) in the system :-)

Thanks @arfon, all working for me now. :+1:

**Comment by mikldk** [comment]
@drvinceknight : Thanks. Suggestions include: @wrathematics @ajank @drvinceknight @acolum

**Comment by drvinceknight** [comment]
> Suggestions include: @drvinceknight 

I've heard of him, he sounds great! (Joking: that's me :+1: :))

**Comment by drvinceknight** [comment]
Hi @matloff, @wrathematics, @ajank and @acolum would you be interested in reviewing this paper for JOSS? It is presenting a piece of software that interfaces to the `yacas` computer algebra system.

If you have not reviewed for JOSS before here is some documentation describing the process: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html and I'd be very happy to answer any questions you have.

Once two reviewers have agreed I will open a separate review issue where the review process can take place.

**Comment by matloff** [comment]
Sorry, way too busy.

Norm

**Comment by ajank** [comment]
Sorry, I have too many other obligations at the moment for a timely review.

**Comment by drvinceknight** [comment]
No problem, thanks for the response both :+1:

**Comment by acolum** [comment]
Sorry, I have too many other commitments going on at the moment.

**Comment by mikldk** [comment]
A few suggestions more from the reviewer list: @mdavezac , @EduPH , @MikeLydeamore .

**Comment by MikeLydeamore** [comment]
I can take on this one.

**Comment by drvinceknight** [comment]
Thank you @MikeLydeamore!

**Comment by drvinceknight** [comment]
@whedon assign @MikeLydeamore as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @MikeLydeamore

**Comment by EduPH** [comment]
I can review if needed.

**Comment by drvinceknight** [comment]
Fantastic, thank you @EduPH. I will now open a review issue.

**Comment by drvinceknight** [comment]
@when add @EduPH as reviewer

**Comment by drvinceknight** [comment]
@whedon add @EduPH as reviewer

**Comment by whedon** [comment]
OK, @EduPH is now a reviewer

**Comment by drvinceknight** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1763. Feel free to close this issue now!
