### ISSUE TITLE
[REVIEW]: AltamISA: a Python API for ISA-Tab files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1610]
**Submitting author:** @holtgrewe (<a href="http://orcid.org/0000-0002-3051-1763">Manuel Holtgrewe</a>)
**Repository:** <a href="https://github.com/bihealth/altamisa" target ="_blank">https://github.com/bihealth/altamisa</a>
**Version:** v0.2.2
**Editor:** @lpantano
**Reviewer:** @tleonardi, @dsurujon, @dmnfarrell
**Archive:** <a href="https://doi.org/10.5281/zenodo.3370902" target="_blank">10.5281/zenodo.3370902</a>

## Status

[![status](http://joss.theoj.org/papers/a0b124b1c1e05f57cd80336863f669b6/status.svg)](http://joss.theoj.org/papers/a0b124b1c1e05f57cd80336863f669b6)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/a0b124b1c1e05f57cd80336863f669b6"><img src="http://joss.theoj.org/papers/a0b124b1c1e05f57cd80336863f669b6/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/a0b124b1c1e05f57cd80336863f669b6/status.svg)](http://joss.theoj.org/papers/a0b124b1c1e05f57cd80336863f669b6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bihealth/altamisa" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@tleonardi & @dsurujon & @dmnfarrell, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bihealth/altamisa">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.2.2
- [x] **Authorship:** Has the submitting author (@holtgrewe) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bihealth/altamisa">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.2.2
- [x] **Authorship:** Has the submitting author (@holtgrewe) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bihealth/altamisa">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.2.2
- [x] **Authorship:** Has the submitting author (@holtgrewe) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @tleonardi, @dsurujon, @dmnfarrell it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01610/joss.01610/10.21105.joss.01610.pdf)

**Comment by tleonardi** [comment]
Hi @holtgrewe, I'm in the process of reviewing the submission and still have to test its functionality.
In the meantime I have a couple of comments.

I've noticed that the paper lists "Mathias Kuhring, Mikko Nieminen, Jennifer Kirwan, Dieter Beule and Manuel Holtgrewe" as authors. However, `AUTHORS.rst` and the Credits section of the docs only report Kuhring, Nieminen and Holtgrewe (with commits only by Kuhring and Holtgrewe). Can you confirm that all co-authors have actively contributed to AlamISA development in line with JOSS [authorship guidelines](https://joss.readthedocs.io/en/latest/submitting.html#authorship)?

On a separate note, can you add a DOI to the references in the bibliography?

**Comment by holtgrewe** [comment]
@tleonardi Thanks for finding this. Yes, while Beule and Kirwan have contributed no lines of code, they have contributed a lot in terms of software design and domain-specific knowledge, without this, the code would not be where it is now. Also, Nieminen is sitting next to Kuhring in the office and has worked (accumulated certainly hours) with Kuhring in pair programming, discussion, and consulting.

I thus see all authors on the paper fit for inclusion as authors and all have contributed to the content of the package and have made a contribution far beyond just supervision and funding.

**Comment by holtgrewe** [comment]
@tleonardi And of course, I can add DOIs (just added to `master`).

@whedon generate pdf

**Comment by holtgrewe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01610/joss.01610/10.21105.joss.01610.pdf)

**Comment by tleonardi** [comment]
@holtgrewe thanks for the clarification about authorship, I think this is perfectly in line with the journal's policy.

**Comment by tleonardi** [comment]
@lpantano could you advise on JOSS policy about citing manuscripts _in preparation_? The authors are citing their _SODAR_ manuscript as _Nieminen, Holtgrewe and Beule, 2020_. Is this ok?

**Comment by lpantano** [comment]
Thanks @tleonardi, I will check that.

**Comment by lpantano** [comment]
Hi @tleonardi  and @holtgrewe, the board of editors recommends to deposit that paper into biorxiv if you really want to cite it. If that is not possible, sadly it needs to be removed from the reference and mentioned in the paper that it is under preparation or working on that. I hope that works.

**Comment by holtgrewe** [comment]
@lpantano Sounds very well in line with the spirit of JOSS. We'll be happy to remove it as we don't have much to show for it right now.

**Comment by holtgrewe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01610/joss.01610/10.21105.joss.01610.pdf)

**Comment by tleonardi** [comment]
@lpantano I have now completed my review of this submission. AltamISA is a useful research software that facilitates the systematic annotation of experimental procedure in line with the FAIR (Findable, Accessible, Interoperable, and Reusable) guidelines. The paper is clear and well written - as is the code, which is also well documented and thoroughly tested.
In my review I have only found some minor issues ([#58](https://github.com/bihealth/altamisa/issues/58), [#59](https://github.com/bihealth/altamisa/issues/59), [#60](https://github.com/bihealth/altamisa/issues/60), [#61](https://github.com/bihealth/altamisa/issues/61)) which the authors have now fixed/addressed.
I'm happy to reccommend the paper for publication in JOSS.

**Comment by dsurujon** [comment]
I have gone through the manuscript, documentation and examples for AltamISA. I think this is a very nice and convenient package, and I'd like to thank the authors for introducing me to the ISA framework - I will try to incorporate ISA and AltamISA into my work in the future!     
I spotted a couple of typos in the documentation, and have one suggestion. @holtgrewe could you please address those issues I listed in this issue (bihealth/altamisa/issues/64)

Moreover, I have 2 small issues regarding the manuscript: 
* Under the section "License and Availability" it says the current version is "0.2.0", however after addressing @tleonardi 's comments the version number is now 0.2.1
* Towards the end of the "Aims and Features" section, the authors note that they excluded JSON and RFD file formats from this project because they are not widely adapted. I would argue that at least for JSON, it is a very well-accepted and ubiquitously used file format. It is possible taht the authors mean specifically within applications that use the ISA framework, these formats are more rare than the ISA-Tab format. If this is the case, I would suggest rephrasing this statement to clarify this point.  
       
Once these issues are addressed I would be more than happy to recommend this paper for publication. Thank you @holtgrewe and colleagues for generating this nice package!

**Comment by dmnfarrell** [comment]
I have reviewed this software and find the paper clear and well written. The software installs via pip with no issues. I have no experience with the ISA-tab format but the code examples I tested worked and the API documentation look well prepared. Some of the issues I noticed have already been addressed by the other reviewers. The only other comments I have are as follows:
* it is not clear how the tests are to be run from the documentation, if this is possible
* issue bihealth/altamisa/issues/60 is yet to be addressed in terms of the import statements in the docs

Otherwise I am happy to recommend for publication.

**Comment by mkuhring** [comment]
@lpantano, @tleonardi, @dsurujon, @dmnfarrell, @holtgrewe 
Thanks to all reviewers for your constructive criticism. We updated our documentation with respect to your remaining issues: https://github.com/bihealth/altamisa/issues/60, https://github.com/bihealth/altamisa/issues/64. We will tag a new release soon. Feel free to open additional issues if you see need for additional improvements.

**Comment by mkuhring** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01610/joss.01610/10.21105.joss.01610.pdf)

**Comment by lpantano** [comment]
Thank you, @mkuhring ! 

can you confirm the new version is v0.2.2? or let me know when you have the latest version that addressed the reviewers' comments.

Cheers

**Comment by mkuhring** [comment]
Yes, v0.2.2 is the new version.

Lorena Pantano <notifications@github.com> schrieb am Do., 15. Aug. 2019,
20:51:

**Comment by lpantano** [comment]
@whedon set v0.2.2 as version

**Comment by whedon** [comment]
OK. v0.2.2 is the version.

**Comment by lpantano** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/ng.1054 is OK
- 10.1038/sdata.2016.18 is OK
- 10.1002/0471250953.bi1413s53 is OK
- 10.1109/32.221135 is OK
- 10.1186/1471-2105-15-S14-S4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lpantano** [comment]
Thank you @mkuhring , could you create a zenodo archive with this version and where the title and the authors match what the paper shows? I would need the DOI from zenodo. Thanks!

**Comment by holtgrewe** [comment]
@lpantano 

- 10.5281/zenodo.3370902
- https://zenodo.org/record/3370902

**Comment by lpantano** [comment]
@whedon set 10.5281/zenodo.3370902 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3370902" target="_blank">10.5281/zenodo.3370902</a> is the archive.

**Comment by lpantano** [comment]
Hey @dmnfarrell, I see you didn't check the "automated tests" but others have done it, is this a mistake or there is an issue with this?

**Comment by dmnfarrell** [comment]
Yes it's a mistake. I've checked that now.

**Comment by lpantano** [comment]
Hey @openjournals/joss-eics this paper has been accepted. Thanks all!

**Comment by kyleniemeyer** [comment]
Hi @holtgrewe, I just made some minor fixes to the paper bib file, if you could merge these: https://github.com/bihealth/altamisa/pull/67

**Comment by holtgrewe** [comment]
@kyleniemeyer Sure, done. :white_check_mark:

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1610 with the following error: 

 Error reading bibliography ./paper.bib (line 37, column 5):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by holtgrewe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01610/joss.01610/10.21105.joss.01610.pdf)

**Comment by kyleniemeyer** [comment]
Thanks @holtgrewe, looks like I dropped a comma in my edits...

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by holtgrewe** [comment]
:)

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/909

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/909, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1163827343397466112) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/910
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01610](https://doi.org/10.21105/joss.01610)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @holtgrewe on your article's publication in JOSS! Thanks to @tleonardi, @dsurujon, and @dmnfarrell for reviewing, and @lpantano for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01610/status.svg)](https://doi.org/10.21105/joss.01610)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01610">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01610/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01610/status.svg
   :target: https://doi.org/10.21105/joss.01610
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01610/status.svg)](https://doi.org/10.21105/joss.01610)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
