### ISSUE TITLE
[REVIEW]: AutoGAMESS: A Python package for automation of GAMESS(us) Raman calculations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1612]
**Submitting author:** @Cavenfish (<a href="http://orcid.org/0000-0002-7416-8629">Brian Ferrari</a>)
**Repository:** <a href="https://github.com/Cavenfish/autogamess" target ="_blank">https://github.com/Cavenfish/autogamess</a>
**Version:** v1.1.1
**Editor:** @jedbrown
**Reviewer:** @arosen93, @shivupa, @colleeneb
**Archive:** <a href="https://doi.org/10.5281/zenodo.3385236" target="_blank">10.5281/zenodo.3385236</a>

## Status

[![status](http://joss.theoj.org/papers/794a5294c44ee66fb210760db10353f9/status.svg)](http://joss.theoj.org/papers/794a5294c44ee66fb210760db10353f9)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/794a5294c44ee66fb210760db10353f9"><img src="http://joss.theoj.org/papers/794a5294c44ee66fb210760db10353f9/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/794a5294c44ee66fb210760db10353f9/status.svg)](http://joss.theoj.org/papers/794a5294c44ee66fb210760db10353f9)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Cavenfish/autogamess" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@arosen93 & @shivupa & @colleeneb, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @jedbrown know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Cavenfish/autogamess">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.1.1
- [x] **Authorship:** Has the submitting author (@Cavenfish) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Cavenfish/autogamess">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.1.1
- [x] **Authorship:** Has the submitting author (@Cavenfish) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Cavenfish/autogamess">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.1.1
- [x] **Authorship:** Has the submitting author (@Cavenfish) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arosen93, @shivupa, @colleeneb it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01612/joss.01612/10.21105.joss.01612.pdf)

**Comment by jedbrown** [comment]
@arosen93, @shivupa, and @colleeneb :wave: Welcome and thanks for agreeing to review! The comments from @whedon above outline the review process, which takes place in this thread (possibly with issues filed in the [AutoGAMESS repository](https://github.com/Cavenfish/autogamess)). I'll be watching this thread if you have any questions.

**Comment by shivupa** [comment]
Hi the version has  progressed to 1.0.33. Is it possible to update the submission to reflect this?

**Comment by jedbrown** [comment]
@shivupa We can set the version at acceptance. It's common for the review to result in a new release.

**Comment by jedbrown** [comment]
@whedon set 1.0.33 as version

**Comment by whedon** [comment]
OK. 1.0.33 is the version.

**Comment by shivupa** [comment]
Yeah that makes sense, and also thanks! (Thanks @whedon)

**Comment by Cavenfish** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01612/joss.01612/10.21105.joss.01612.pdf)

**Comment by Cavenfish** [comment]
An issue with AutoGAMESS angle calculations has recently been pointed out to me. I should have this fixed in less than a day, the changes will be reflected in the paper as well. 
I apologize for not catching this sooner.

**Comment by arosen93** [comment]
@Cavenfish Good to know. Just FYI, I plan to get to this review over the weekend (by Monday at the latest).

**Comment by Cavenfish** [comment]
Okay, I have committed the edits to the code and paper.

**Comment by Cavenfish** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01612/joss.01612/10.21105.joss.01612.pdf)

**Comment by Cavenfish** [comment]
@arosen93  Your comments on the paper were greatly appreciated! I have made revisions to the paper taking your comments into account, and I believe it has strengthened the paper. 

I look forward to hearing more comments from you all.

**Comment by Cavenfish** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01612/joss.01612/10.21105.joss.01612.pdf)

**Comment by Cavenfish** [comment]
@shivupa @colleeneb @arosen93 

Hey, If there is anything I can do to make this review process easier for you three please let me know.

**Comment by Cavenfish** [comment]
Thank you for the comments on my paper @shivupa! I have made changes to the paper taking into consideration your comments and I believe it looks much better now.

**Comment by Cavenfish** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01612/joss.01612/10.21105.joss.01612.pdf)

**Comment by colleeneb** [comment]
Just commenting to say that I've checked off all the boxes in the checklist, and that the code functions as expected for the cases I tested.

**Comment by colleeneb** [comment]
@Cavenfish This is outside of the scope of the review, but I wanted to mention that if you are interested in making changes/improvements to GAMESS itself, you can follow the instructions [here](https://www.msg.chem.iastate.edu/gamess/developers.html), and email to request access to the GAMESS private repo on github.

**Comment by shivupa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01612/joss.01612/10.21105.joss.01612.pdf)

**Comment by jedbrown** [comment]
@Cavenfish Did you mean to cite cclib in the paper? I see it in paper.bib, but not cited in the paper.

**Comment by Cavenfish** [comment]
@jedbrown  Yes, i did. It must have gotten dropped by accident during one of my edits to the paper. I'll add it back in now. I also want to mention before the publication I'd like to make a final version change, to 1.1.0 to make the version changes from publication onward easier to spot for users. I'm waiting for @arosen93  to finish with his review before making the version change though.

**Comment by arosen93** [comment]
@Cavenfish I'm very sorry about the delay. I promise to finish the review by the end of the day. Stay tuned. Thanks for your patience. I'm nearly done testing it.

**Comment by Cavenfish** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01612/joss.01612/10.21105.joss.01612.pdf)

**Comment by arosen93** [comment]
Hi @Cavenfish. I've complete the testing of the code. Generally, it works as expected, especially as a result of the useful additions made over the course of the review process. I really like the improved examples as well.

@jedbrown: Once the pytest is fixed (https://github.com/Cavenfish/autogamess/issues/15), my review will be complete.

**Comment by jedbrown** [comment]
Thanks, all.

@Cavenfish, I would like to relay a concern and suggestion raised in private discussion. There was some concern that the software as written will be thought of more as a utility that some users may not feel compelled to cite. It was proposed that adding the ability to plot results would aid reproducibility. For example, I understand that it's common to use GUI software such as MacMolPlt to make line plots of frequency versus infrared or Raman intensities. What do you think of teaching AutoGAMESS to create such plots (suitably named/labeled/annotated)?

Further (and perhaps out of scope at this time), is anyone here aware of an API or bulk download option for [CCCBDB](https://cccbdb.nist.gov/) or other repository of experimental data, such that software like AutoGAMESS could automate comparison to experiments?

**Comment by Cavenfish** [comment]
Hey @jedbrown 

In terms of AutoGAMESS being cited, I understand the concerns but I have spoken with other researchers at my University and they consider AutoGAMESS to be worth citing (and they plan on doing so when able). Of course, this is special circumstance and is not to be expected for all users of AutoGAMESS. If you think adding plots will increase the chance of citation then I will add the plotting feature to AutoGAMESS, I have considered adding something like that before but figured users would prefer to simply generate their own plots instead.

In terms of the CCCBDB comparison to experiments, this was actually something I tried to do at first and even found this [package](https://github.com/marcelo-mason/cccbdb-calculation-parser). However, it was not exactly what I was looking for, so I dropped it. I would be very interested in something that works better so that I could add a feature for comparing results as well as generating scaling factors.

**Comment by jedbrown** [comment]
I think plotting would add significant value and improve workflow reproducibility. Thanks for your willingness to add this feature.

What was the deficiency in that CCBDB retriever/parser relative to what you were looking for? Are any reviewers aware of better tools for this?

**Comment by Cavenfish** [comment]
The parser seems to only pull calculated data not experimental data from what I could tell. What I would like is the experimental data, which i considered leaving a feature request for but the code has not been changed in 2 years so I figured its no longer maintained.

**Comment by jedbrown** [comment]
Okay, boo. That package is tiny (so it may be easy to build the feature), but quite rough and is "failing" for unspecified reason when I try to run the example.

**Comment by Cavenfish** [comment]
My thoughts were to just remake the package entirely from scratch.

**Comment by Cavenfish** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01612/joss.01612/10.21105.joss.01612.pdf)

**Comment by Cavenfish** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01612/joss.01612/10.21105.joss.01612.pdf)

**Comment by Cavenfish** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01612/joss.01612/10.21105.joss.01612.pdf)

**Comment by Cavenfish** [comment]
I apologize for the whedon spam, the figure gave me some trouble.

@jedbrown  I have added the plotting feature to AutoGAMESS, an example is now included in both the README and paper. 

If any of you have any feedback about the plots please let me know.

**Comment by shivupa** [comment]
I have some points that I think would strengthen this submission. These are open to discussion There has been mention that the scope is somewhat limited. I think adopting some of the points below would help broaden the scope and increase adoption in the target audience.

Short term:

1. Presenting the examples as Jupyter notebook is helpful, but adding Binder hosting would really help. Some of the users could be experimentalists who aren't used to the command line which may limit adoption otherwise. The notebook currently in examples would need to have the bash cells commented out as the binder instances would not have GAMESS in them.

2. I think the addition of plotting was very necessary. Something I would like to see (aka would make me use this over just making the plot myself) is line broadening for visual assistance with choices for line shapes (Gaussian/Lorentzian) and other associated parameters.

3. Integration with cclib would be nice. Short term, I would like to see at least the initial molecule being read with cclib and then being fed into the new project function. Clearly the parsing of the necessary data isn't being done yet in cclib, but either implementing this upstream or opening issues for these would allow you to support many codes.

4. I'd really like to see the addition of the generation of scaling factors. For now instead of interfacing with a database, I would like to see some representation of an experimental spectrum being read in and being matched to calculated intensities.

General point / Long term:

5. I think this should be called Autovib or AutoRAMAN because it automates these types of calculations rather than the full spectrum of calculations that GAMESS is capable of. Rebranding it as such would allow for (future work) adding other software packages such as Orca, PYSCF, etc.

Let me know what you think.

**Comment by Cavenfish** [comment]
Hey @shivupa you make some great points,

1) I will need to learn more about Binder before attempting to implement it. This is the same with Sphinx which has also been suggested.

2) I can have that feature added right away (it is also something my adivsor recommended), my thought is to have the line broadening choices be over-plotted with a different line-style (dotted or dashed)  so that the vertical lines remain but you also have the broadened lines in the plot as well. What do you think, is that too much for one plot?

3) I can replace the default initial molecule library with a cclib interface. I just don't see how to make that happen, does cclib have a pre-optimization molecule coordinate dictionary or some way of getting me the point group symmetry and initial atom coordinates? If so, can you please help me find it.

4) I can make a function that has users give experimental data in list form and it then generates the scaling factors (as well as the scaled frequencies) from there. 

5) Re-branding it as AutoRaman seems like it may be an inconvenience but I do see merit in that suggestion. I will consider it.

**Comment by arosen93** [comment]
Hey @Cavenfish. I think these are some good ideas. With regards to #2, I think what you said would be a great choice. You could also have an optional flag to hide the vertical lines if desired, but I think what you suggested would be a good default. Lots of visualization programs have a similar thing (I personally like ChemCraft's -- that might be a good reference). With regards to #5, I had the same thought as @shivupa, although didn't bring it up. I do think the name "AutoGAMESS" is a bit misleading, given the specific nature of the program, but I also understand that it may be inconvenient to "re-brand".

**Comment by Cavenfish** [comment]
@shivupa @arosen93 I have added the line broadening feature, an example is in the README. I also added a spectral line plot which is the sum of the fits.

**Comment by shivupa** [comment]
I opened an issue which shows how to address 3. I realized the library you would want to use is openbabel not cclib. I included an example of how to do this. It seems like code for 4 is added once we can review that and see an example I would say this address all of the issues that I think are essential (1 and 5 are long term and optional).

**Comment by Cavenfish** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01612/joss.01612/10.21105.joss.01612.pdf)

**Comment by Cavenfish** [comment]
I have finished both the plotting function and scaling factor generation function. I have added documentation and examples for them in the README and put more in the paper about these two new capabilities.

**Comment by Cavenfish** [comment]
i just pushed a commit that gets rid of the straggler phrase at the end of the paper's capabilities section.

**Comment by Cavenfish** [comment]
@jedbrown @shivupa @arosen93 @colleeneb 

I believe all the new features should be fully functional and reflected properly in the README and JOSS paper. I await feedback from you all, thanks again for the time and effort.

**Comment by arosen93** [comment]
@jedbrown, @Cavenfish This is an excellent update to AutoGAMESS that I think really strengthens the use-cases for the code. I also like the ability to generate the scaling factors. The only remaining suggestion I have is to add a formal test case that generates an example IR and/or Raman plot (just like you have in the README) to confirm that this part of the code doesn't break. As long as the code doesn't crash when it makes the figure, I think that's a suitable test (it's easy for a `matplotlib` update to change something unexpected in one's code). Otherwise, I do not have any additional comments at this time.

**Comment by colleeneb** [comment]
I also think this strengthens the use-cases for AutoGAMESS. It was a lot of nice work!  I have no additional comments either.

**Comment by shivupa** [comment]
I also agree! @Cavenfish has addressed all of the short-term comments I raised! The plotting test is a good idea.

**Comment by Cavenfish** [comment]
@jedbrown @shivupa @arosen93 @colleeneb

I added the test for `make_plot` function to the package tests. I have also updated and released version 1.1.0 of AutoGAMESS, which includes all the new features.

**Comment by Cavenfish** [comment]
Hey @jedbrown is there anything more I should be doing now, or just wait for further comments?

**Comment by jedbrown** [comment]
@Cavenfish Thanks for your great additions. I just returned from travel and the semester is about to start, but I'll handle this within the coming days. Sorry for the delay.

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01612/joss.01612/10.21105.joss.01612.pdf)

**Comment by jedbrown** [comment]
@Cavenfish Thanks for your patience. In addition to the PR, please consider whether your use of packages such as [SciPy](https://www.scipy.org/citing.html) and [Matplotlib](https://matplotlib.org/3.1.1/citing.html) (and others) warrant citation. Most likely yes.

The PyPI link (https://pypi.org/project/autogamess/) says
> The author of this package has not provided a project description

If you intend for that page to be the landing page for those who wish to install AutoGAMESS, then you'll want to curate its content. I would recommend cutting that link, such that a prospective user arrives at your GitHub and/or just installs via `pip`, typically without visiting the PyPI site. Also note that the repository is always linked from the sidebar in the typeset version so you don't need to link it again.

The wording in the section "Use of AutoGAMESS" is rough, but why rule out managing an ensemble using only Python (versus shell scripts calling user-written Python scripts calling AutoGAMESS)? Perhaps just say that you provide examples of incorporating AutoGAMESS into workflows based on shell scripts?

**Comment by Cavenfish** [comment]
@jedbrown Hey, I merged your commits and made the changes you suggested above. Some of the package citations I wasn't able to find DOI's for, is this an issue?

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by jedbrown** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01612/joss.01612/10.21105.joss.01612.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/jcc.540141112 is OK
- 10.1016/B978-044451719-7/50084-6 is OK
- 10.1016/j.theochem.2004.06.013 is OK
- 10.1002/jcc.23415 is OK
- 10.1051/0004-6361:20052658 is OK
- 10.1088/0004-637x/782/2/63 is OK
- 10.1023/A:1008193805436 is OK
- 10.1016/S1093-3263(99)00002-9 is OK
- 10.1002/jcc.21600 is OK
- 10.1016/j.tcb.2005.05.001 is OK
- 10.1002/jcc.20823 is OK
- 10.1002/(SICI)1096-987X(199610)17:13<1571::AID-JCC9>3.0.CO;2-P is OK
- 10.1021/ci600510j is OK
- 10.1021/acs.jpca.7b07361 is OK
- 10.1016/j.commatsci.2017.07.030 is OK
- 10.1088/1361-648x/aa680e is OK
- 10.1016/j.cpc.2015.08.012 is OK
- 10.1021/jp960976r is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jedbrown** [comment]
Another small PR, then I think we'll be ready. We only need DOIs for references that have them.

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01612/joss.01612/10.21105.joss.01612.pdf)

**Comment by jedbrown** [comment]
Thanks! Looks good to me now, so please tag a release ([annotated tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging#_annotated_tags) preferred). Presumably this will be v1.1.1, but it's your choice. Then please archive on Zenodo or a similar service and report the DOI back in this thread.

**Comment by Cavenfish** [comment]
v1.1.1 sounds good to me! I made the tag and here is the DOI:  10.5281/zenodo.3385177.

**Comment by jedbrown** [comment]
@Cavenfish Can you please push your tag?

**Comment by Cavenfish** [comment]
@jedbrown sorry about that, just pushed it.

**Comment by jedbrown** [comment]
@whedon set v1.1.1 as version

**Comment by whedon** [comment]
OK. v1.1.1 is the version.

**Comment by jedbrown** [comment]
Thanks.

Sorry, my instructions may have been unclear: You should archive your _repository_ with Zenodo, not the paper. JOSS handles the paper DOI, with reference to the DOI for your repository.

**Comment by Cavenfish** [comment]
@jedbrown  
Oh, that makes more sense. I apologize for the inconvenience. 

Do you by any chance know how to go about removing the previous upload or should i just leave it be and simply archive the repository?

**Comment by jedbrown** [comment]
DOI are intended to be permanent so either leave it or add a new version (https://help.zenodo.org/#versioning).

**Comment by Cavenfish** [comment]
I left alone for now, here is the new repository DOI:  10.5281/zenodo.3385236.

**Comment by jedbrown** [comment]
@whedon set 10.5281/zenodo.3385236 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3385236" target="_blank">10.5281/zenodo.3385236</a> is the archive.

**Comment by jedbrown** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/942

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/942, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by jedbrown** [comment]
@openjournals/joss-eics This paper is accepted; over to you.

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1169041994355748864) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/943
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01612](https://doi.org/10.21105/joss.01612)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@arosen93, @shivupa, @colleeneb - many thanks for your reviews here and to @jedbrown for editing this submission ✨ 

@Cavenfish - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01612/status.svg)](https://doi.org/10.21105/joss.01612)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01612">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01612/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01612/status.svg
   :target: https://doi.org/10.21105/joss.01612
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01612/status.svg)](https://doi.org/10.21105/joss.01612)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
