### ISSUE TITLE
[REVIEW]: drms: A Python package for accessing HMI and AIA data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1614]
**Submitting author:** @kbg (<a href="http://orcid.org/0000-0002-1361-5712">Kolja Glogowski</a>)
**Repository:** <a href="https://github.com/sunpy/drms" target ="_blank">https://github.com/sunpy/drms</a>
**Version:** v0.5.7
**Editor:** @xuanxu
**Reviewer:** @mgckind, @aureliocarnero
**Archive:** <a href="https://doi.org/10.5281/zenodo.3369966" target="_blank">10.5281/zenodo.3369966</a>

## Status

[![status](http://joss.theoj.org/papers/310a0fa5052bdaf3d398bf1fefa32b6e/status.svg)](http://joss.theoj.org/papers/310a0fa5052bdaf3d398bf1fefa32b6e)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/310a0fa5052bdaf3d398bf1fefa32b6e"><img src="http://joss.theoj.org/papers/310a0fa5052bdaf3d398bf1fefa32b6e/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/310a0fa5052bdaf3d398bf1fefa32b6e/status.svg)](http://joss.theoj.org/papers/310a0fa5052bdaf3d398bf1fefa32b6e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/sunpy/drms" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mgckind & @aureliocarnero, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @xuanxu know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sunpy/drms">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.5.7
- [x] **Authorship:** Has the submitting author (@kbg) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sunpy/drms">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.5.7
- [x] **Authorship:** Has the submitting author (@kbg) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mgckind, @aureliocarnero it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1614 with the following error: 

 Can't find any papers to compile :-(

**Comment by xuanxu** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01614/joss.01614/10.21105.joss.01614.pdf)

**Comment by mgckind** [comment]
There is one author that contributed to the repo and appears in the Authors.txt (Nabil Freij) which is not on the paper, is that intentionally? just wondering about not missing anybody. Thanks

**Comment by mgckind** [comment]
@xuanxu , @kbg. I'm done with the review, 
I installed it, looked at the documentation, the paper, I ran a few examples and others and everything seems in order. After addressing the following points this is ready to go:
- I made a comment about the authors above
- I created 3 issues related to the paper, tests and community guidelines, sunpy/drms#30, sunpy/drms#31 and sunpy/drms#32
- I think adding more examples would be useful, as it wasn't very clear how to filter by date or make an end-to-end plot like the one from the paper 

Let me know if you have questions and congrats for this complete and useful package

**Comment by mbobra** [comment]
> There is one author that contributed to the repo and appears in the Authors.txt (Nabil Freij) which is not on the paper, is that intentionally? just wondering about not missing anybody. Thanks

@kbg invited all contributors to coauthor (see [this issue](https://github.com/sunpy/drms/issues/27)) and Nabil declined.

**Comment by mgckind** [comment]
> > There is one author that contributed to the repo and appears in the Authors.txt (Nabil Freij) which is not on the paper, is that intentionally? just wondering about not missing anybody. Thanks
> 
> @kbg invited all contributors to coauthor (see [this issue](https://github.com/sunpy/drms/issues/27)) and Nabil declined.

oh I see, yes this is good. Thanks!

**Comment by kbg** [comment]
@mgckind : Thanks for the feedback. I'm currently going through the issues you opened. I will leave a comment there, when I think that I have resolved them.

About adding more examples to the online documentation: Have you had a look at the [Tutorial](https://drms.readthedocs.io/en/latest/tutorial.html)? It contains quite some information about how to use the `drms` module.

**Comment by mgckind** [comment]
> @mgckind : Thanks for the feedback. I'm currently going through the issues you opened. I will leave a comment there, when I think that I have resolved them.
> 
> About adding more examples to the online documentation: Have you had a look at the [Tutorial](https://drms.readthedocs.io/en/latest/tutorial.html)? It contains quite some information about how to use the `drms` module.

Yes, I went through the tutorial and through the example pages, I made a comment on showing for example how to reproduce Figures from the paper, I think with that it should be enough.

**Comment by aureliocarnero** [comment]
I have checked all the checklist and in my opinion, it is ready to go.
You have adressed all the issues open by @mgckind and correct the example used to create the publication figure.
Congrats!

**Comment by xuanxu** [comment]
Thanks @aureliocarnero!

**Comment by xuanxu** [comment]
@mgckind: There's a couple items still unmarked in your checklist (test + community guidelines) that seems to be addressed,. Can you confirm you completed the review/recommend publication?

**Comment by kbg** [comment]
Thanks. I'm also going to add a link to the figure example into the paper. I think that all issues will be resolved after this.

Also, in case the repository branch of the paper source code would show up somewhere in the publication: I will merge the `joss-paper` branch into `master`, after it got accepted.

**Comment by mgckind** [comment]
I closed the issues and did a final review, this is good to go. @xuanxu , @kbg . I checked off the pending items. Congratulations

**Comment by xuanxu** [comment]
@mgckind thanks!

**Comment by xuanxu** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper
. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1614 with the following error: 

 error: pathspec 'joss-paper
' did not match any file(s) known to git.
Can't find any papers to compile :-(

**Comment by xuanxu** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01614/joss.01614/10.21105.joss.01614.pdf)

**Comment by xuanxu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2572850 is OK
- 10.1088/1749-4699/8/1/014009 is OK
- 10.1007/s11207-011-9842-2 is OK
- 10.1007/s11207-011-9776-8 is OK
- 10.1007/s11207-014-0529-3 is OK
- 10.1007/BF00733429 is OK
- 10.1007/s11207-014-0485-y is OK
- 10.1007/s11207-011-9841-3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by xuanxu** [comment]
Everything looks good @kbg, here are the next steps:
- please merge the joss-paper branch into master, 
- then you should make a new tagged release that includes all changes made during this review 
- Archive that release in Zenodo 
- Check the Zenodo deposit has the correct metadata: title and author list should match the paper's; you may also add the authors' ORCID.

Once you do that please report here the version number, and the Zenodo DOI.

**Comment by kbg** [comment]
Thanks, this is great.

About the author list: Do the author lists (GitHub/Zenodo vs. JOSS paper) really need to be identical? At the moment the GitHub contributors do not match completely with the authors of the paper. We have two GitHub contributors who decided not to be on the author list (see https://github.com/sunpy/drms/issues/27). On the other hand, we also have a paper author who did not directly contribute any code to the GitHub repository, but who is still involved in the project (he is one of the JSOC/DRMS developers).

Please let me know, how I should handle this. I cannot just remove contributors from the Zenodo author list, nor can I put people on the paper author list, without having their consent.

**Comment by xuanxu** [comment]
@kbg: The author list of the specific version archived in Zenodo for the paper should match the author list of the paper. No need for any of those to match the Github contributors list, so you should edit just the Zenodo site.

**Comment by kbg** [comment]
Ok, thanks. I'll try to create an additional Zenodo archive for the paper then (in addition to the one that is automatically created by the GitHub hook).

**Comment by xuanxu** [comment]
@kbg OK (if you want to use the automatically created by the hook is ok too, the metadata of any Zenodo archive is editable and that includes the author list)

**Comment by mbobra** [comment]
Hi @xuanxu, I'm writing for @kbg since he is on vacation now. I'm a co-author on the paper and @kbg and I talked about this beforehand -- hopefully this is okay, but if not please let me know.

We are not sure what to do about matching the co-author list on the paper to the author list on the Zenodo release. On one hand, we cannot force people to be authors on a paper if they do not want to. On the other hand, it seems wrong to go into the Zenodo metadata and remove contributors names from the release when they have in fact contributed to the codebase. Therefore, we think it makes sense for the Zenodo release and the paper to have a different list of authors. Please let us know if this is possible.

**Comment by xuanxu** [comment]
@mbobra/@kbg: Yes, as long as all the people listed in the paper are also in the Zenodo archive, it is posible to have those different author lists.

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01614/joss.01614/10.21105.joss.01614.pdf)

**Comment by xuanxu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2572850 is OK
- 10.1088/1749-4699/8/1/014009 is OK
- 10.1007/s11207-011-9842-2 is OK
- 10.1007/s11207-011-9776-8 is OK
- 10.1007/s11207-014-0529-3 is OK
- 10.1007/BF00733429 is OK
- 10.1007/s11207-014-0485-y is OK
- 10.1007/s11207-011-9841-3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mbobra** [comment]
Thanks, @xuanxu! 

- We merged the JOSS paper into the [master branch of the repo](https://github.com/sunpy/drms/tree/master)
- We released a new version of `drms` three days ago, [v0.5.7](https://github.com/sunpy/drms/releases/tag/v0.5.7)
- We archived this release in Zenodo with the DOI [10.5281/zenodo.3369966](https://zenodo.org/record/3369966)
- All the paper authors are also listed in the Zenodo release

**Comment by xuanxu** [comment]
Great, @mbobra!

**Comment by xuanxu** [comment]
@whedon set v0.5.7 as version

**Comment by whedon** [comment]
OK. v0.5.7 is the version.

**Comment by xuanxu** [comment]
@whedon set 10.5281/zenodo.3369966 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3369966" target="_blank">10.5281/zenodo.3369966</a> is the archive.

**Comment by xuanxu** [comment]
@mbobra could you edit the title of the Zenodo archive to:
`drms: A Python package for accessing HMI and AIA data` so it has the same title as the paper?

**Comment by kbg** [comment]
I just updated the title on Zenodo (I could not find a way to give @mbobra write access to the Zenodo record).

**Comment by xuanxu** [comment]
Yay! :tada:
This is now ready por publication. Pinging @openjournals/joss-eics for final acceptance.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01614/joss.01614/10.21105.joss.01614.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/911

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/911, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1163879625967230976) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/912
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01614](https://doi.org/10.21105/joss.01614)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @kbg on your article's publication in JOSS! Many thanks to @xuanxu for editing,
and @mgckind and @aureliocarnero for reviewing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01614/status.svg)](https://doi.org/10.21105/joss.01614)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01614">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01614/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01614/status.svg
   :target: https://doi.org/10.21105/joss.01614
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01614/status.svg)](https://doi.org/10.21105/joss.01614)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by kbg** [comment]
Thanks for accepting the paper, and also many thanks to everybody for the work they put into editing and reviewing it.

_(I was on vacation, so I'm a bit late to the party :o))._
