### ISSUE TITLE
[PRE REVIEW]: Rudi: Lightweight image converter and dataset augmentor

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1615]
**Submitting author:** @liashchynskyi (<a href="http://orcid.org/0000-0002-3920-6239">Petro Liashchynskyi</a>)
**Repository:** <a href="https://github.com/liashchynskyi/rudi" target ="_blank">https://github.com/liashchynskyi/rudi</a>
**Version:** 1.0
**Editor:** @arfon
**Reviewers:** @casperdcl, @nnadeau

**Author instructions**

Thanks for submitting your paper to JOSS @liashchynskyi. **Currently, there isn't an JOSS editor assigned** to your paper.

@liashchynskyi if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01615/joss.01615/10.21105.joss.01615.pdf)

**Comment by labarba** [comment]
@liashchynskyi — I am the Associate-Editor-in-Chief on rotation, and will be looking for a handling editor for your submission.

After reading your paper, though, it seems like a bit of a slog to have to read a whole page of background before getting to a statement about what the software does. Could you look into placing a few sentences about the software right at the top of your summary? The reader wants to know at the start: _Who is this software for? What does it do?_

You will also have to work on the figure placements. Once you make changes, you can run the command `@whedon generate pdf` right here in a comment to get a new proof.

**Comment by labarba** [comment]
Our [Documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) requests:

> A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.

**Comment by liashchynskyi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01615/joss.01615/10.21105.joss.01615.pdf)

**Comment by liashchynskyi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01615/joss.01615/10.21105.joss.01615.pdf)

**Comment by liashchynskyi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01615/joss.01615/10.21105.joss.01615.pdf)

**Comment by liashchynskyi** [comment]
@labarba check, plaese 😄

**Comment by liashchynskyi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01615/joss.01615/10.21105.joss.01615.pdf)

**Comment by liashchynskyi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01615/joss.01615/10.21105.joss.01615.pdf)

**Comment by liashchynskyi** [comment]
@labarba check, please 🐱

**Comment by liashchynskyi** [comment]
latest @whedon generate pdf

**Comment by liashchynskyi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01615/joss.01615/10.21105.joss.01615.pdf)

**Comment by labarba** [comment]
👋  @mbobra — Could you handle this new JOSS submission as editor? 

**Rudi: Lightweight image converter and dataset augmentor**
https://github.com/liashchynskyi/rudi
[ Article proof :page_facing_up: ](https://github.com/openjournals/joss-papers/blob/joss.01615/joss.01615/10.21105.joss.01615.pdf)

**Comment by liashchynskyi** [comment]
@terrytangyuan Would you be an editor? 😄

**Comment by liashchynskyi** [comment]
come on, people 🐱

**Comment by terrytangyuan** [comment]
I am a little bit overloaded recently. Let's see if @mbobra is available first.

**Comment by labarba** [comment]
Thank you, @terrytangyuan—feel free to unsubscribe from this issue...  @mbobra won't be handling this one (feel free to unsubscribe, also!).

@liashchynskyi — Please bear with us as we identify a handling editor for your submission.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@liashchynskyi - thanks for your submission. Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by liashchynskyi** [comment]
@arfon maybe these 5 - desilinguist, 12 - rougier, 596 - soroushj

i don't know 😹

**Comment by arfon** [comment]
@shivam11 @soroushj @casperdcl would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by casperdcl** [comment]
@arfon sure, can do

**Comment by arfon** [comment]
> @arfon sure, can do

Great, thanks! I'll go ahead and add you as a reviewer, but we won't start the actual review until I've identified a second reviewer.

**Comment by arfon** [comment]
@whedon add @casperdcl as reviewer

**Comment by whedon** [comment]
OK, @casperdcl is now a reviewer

**Comment by liashchynskyi** [comment]
@arfon no one answered for a long time.
maybe we can find other people?

**Comment by arfon** [comment]
:wave: @sbrugman - would you be willing to review this submission for JOSS?  We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by arfon** [comment]
@clemaitre58 @nnadeau - would either of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by nnadeau** [comment]
@arfon i can review 👍

**Comment by clemaitre58** [comment]
@arfon I can also review it.

**Comment by arfon** [comment]
@whedon add @nnadeau as reviewer

**Comment by whedon** [comment]
OK, @nnadeau is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1664. Feel free to close this issue now!

**Comment by arfon** [comment]
> @arfon I can also review it.

I've already secured two reviewers now so I'll move forward with them. Thanks for volunteering though!

@casperdcl, @nnadeau, @liashchynskyi - see you over in #1664 for the actual review
