### ISSUE TITLE
[PRE REVIEW]: SleepPy: A python package for sleep analysis from accelerometer data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1617]
**Submitting author:** @elyiorgos (<a href="http://orcid.org/0000-0003-3371-8935">Yiorgos Christakis</a>)
**Repository:** <a href="https://github.com/elyiorgos/sleeppy" target ="_blank">https://github.com/elyiorgos/sleeppy</a>
**Version:** 0.12
**Editor:** @lheagy
**Reviewers:** @eskofier, @ikarosilva

**Author instructions**

Thanks for submitting your paper to JOSS @elyiorgos. **Currently, there isn't an JOSS editor assigned** to your paper.

@elyiorgos if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1617 with the following error: 

 Error reading bibliography ./paper.bib (line 20, column 81):
unexpected "a"
expecting space or ","
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by labarba** [comment]
@elyiorgos  — Please merge this fix
https://github.com/elyiorgos/sleeppy/pull/1

**Comment by elyiorgos** [comment]
@labarba Should be all set, thank you!

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1617 with the following error: 

 Error reading bibliography ./paper.bib (line 49, column 10):
unexpected "{"
expecting letter, digit, white space or "="
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by labarba** [comment]
Please merge this fix
https://github.com/elyiorgos/sleeppy/pull/2

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01617/joss.01617/10.21105.joss.01617.pdf)

**Comment by elyiorgos** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01617/joss.01617/10.21105.joss.01617.pdf)

**Comment by elyiorgos** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01617/joss.01617/10.21105.joss.01617.pdf)

**Comment by elyiorgos** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01617/joss.01617/10.21105.joss.01617.pdf)

**Comment by labarba** [comment]
👋  @lheagy — Could you handle this JOSS submission as editor? (You might get @fperez to review it: I know he was capturing data from his sleep at one point!)

**SleepPy: A python package for sleep analysis from accelerometer data**
https://github.com/elyiorgos/sleeppy
[ Article proof :page_facing_up:](https://github.com/openjournals/joss-papers/blob/joss.01617/joss.01617/10.21105.joss.01617.pdf)

**Comment by lheagy** [comment]
Happy to @labarba!

**Comment by lheagy** [comment]
👋 Hi @elyiorgos, do you have any recommendations for reviewers?

**Comment by labarba** [comment]
@whedon assign @lheagy as editor

**Comment by whedon** [comment]
OK, the editor is @lheagy

**Comment by elyiorgos** [comment]
Hello! @lheagy, I don't have anyone in particular in mind, though from the available list of reviewers  provided @jminnier, or others with knowledge of python and backgrounds in health, medicine, or a clinical environment would be good choices.

**Comment by elyiorgos** [comment]
I found others as well but for some reason was unable to @ them, @nirum for instance, I'm not sure why that is.

**Comment by lheagy** [comment]
Thanks @elyiorgos. Before assigning reviewers, there are a few things that I wasn't able to find in the repository that are a part of the [review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html). If you would be willing to address the following before we start the review process, this should help streamline the review:

- [ ] [Community guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines) for other communities interested in contributing to the project
- [ ] [Tests](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines): is there a test-suite that covers the core functionality of the software? (Ideally automated). 

Also, for documentation, you might consider hosting the API documentation on [ReadTheDocs](https://readthedocs.org/) or similar. This is not required but a suggestion. 

For reference, here is an accepted JOSS paper that is particularly well-done: https://joss.theoj.org/papers/10.21105/joss.00957

**Comment by elyiorgos** [comment]
Hi @lheagy, I just added community guidelines today after looking at the example you sent, and a few other accepted joss examples, I appreciate the guidance :)

As a way to test the function of the package, there is a demo file and demo run script provided in the sleeppy folder. Essentially what this does is take an acceptable input data file, and run the full package on it, and produce all intermediate data as well as several visualizations to confirm things are functioning properly. As a way to check that the outputs are appropriate outputs, the expected visual results are also stored in the demo folder. Running the test/demo is outlined in the readme and the documentation on pip, but I'm also happy to answer any questions.

I wanted to ask, is it customary to bring reviewers from an external network with a JOSS submission? We have several contacts at various institutions/companies in our network that work in wearable technologies and/or would be potential users of the package, so we could suggest them as reviewers if that's acceptable or desirable. Let me know and I'm happy to suggest extra reviewers!

Thanks very much for all the help!

Best, 
Yiorgos

**Comment by lheagy** [comment]
Thanks @elyiorgos! 

One note on testing, we do expect that there is at least some testing that objectively checks the code (e.g. a sample input and `assert` statements or similar that numerically verify the results). Tests that require a visual check aren't enough to meet [those criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#tests)

As for reviewers, yes - it is acceptable to bring in external reviewers. We do expect that reviewers have some experience developing software so that they can provide input from a developer's on the software package. If you do have people in mind who you would be interested in getting feedback from or making a connection with, this is a great opportunity, so feel free to share their names! 

All the best,
Lindsey

**Comment by elyiorgos** [comment]
Thanks @lheagy!

The existing demo produces a visual report that includes calculated
endpoints(their numerical values), which could be compared with the
expected endpoints manually, but based on your response and for ease of use
I added an automated check for that process today. That should serve as a
more robust validation of the output.

To help identify external reviewers I'm going to include my colleague
@shyamalpatel on this thread, we should have a list of potential reviewers
ready soon (hopefully today). We'll share that as soon as we get in touch
with them. Thanks again!

Best,
Yiorgos

**Comment by shyamalpatel** [comment]
We would like to nominate Prof. Bjoern Eskofier (@eskofier) as a reviewer. Dr. Eskofier is a professor in the Department of Computer Science at University of Erlangen (https://www.fau.eu/) and leads a research group focused on wearable computing and machine learning.

Best,
Shyamal

**Comment by lheagy** [comment]
:wave: Hi @eskofier, @jminnier would you be willing to review this submission [JOSS](Joss.theoj.org/about)? JOSS is a 'developer friendly' journal. That is, we focus on the software as a scientific contribution. If the submitting authors have followed best practices (have documentation, tests, continuous integration, and a license) then their review should be straight-forward. There are more details on reviewing with JOSS here: http://joss.theoj.org/about#reviewer_guidelines 

I would greatly appreciate your input! If you are unable to take this on at the moment, any recommendations for alternate reviewers would be much appreciated.

**Comment by eskofier** [comment]
Dear Lindsay,

I can take this.

Best regards,
Bjoern Eskofier
-- 
Prof. Bjoern Eskofier, Ph.D.

FAU Sandbox: find out more about our newest FAU student startup & innovation program at www.sandbox.fau.de 

Heisenberg professorship of the DFG
Digital Sports and Health Group
Machine Learning and Data Analytics Lab
Department of Computer Science
Faculty of Engineering
Friedrich-Alexander University Erlangen-Nuernberg (FAU)
Carl-Thiersch-Strasse 2b, 91052 Erlangen, Germany

Adjunct Member, Faculty of Medicine
Speaker, Central Institute of Healthcare Engineering
Friedrich-Alexander University Erlangen-Nuernberg (FAU)
Henkestraße 91, 91052 Erlangen

I-net: http://www.mad.cs.fau.de
Phone: +49 9131 85-27297
Email: bjoern.eskofier@fau.de

**Comment by shyamalpatel** [comment]
@lheagy [Dr. Ikaro Silva](https://www.linkedin.com/in/ikaro-silva-5642239/) (@ikarosilva) would be able to review this if you are looking for additional reviewers. Dr. Silva is a senior research scientist at Philips Research North America and has a strong background in biomedical applications of signal processing and machine learning.

Best,
Shyamal

**Comment by lheagy** [comment]
Excellent, many thanks @eskofier! I will continue looking for one more reviewer before we get started.

**Comment by lheagy** [comment]
@whedon assign @eskofier as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @eskofier

**Comment by jminnier** [comment]
Sorry @lheagy I don't have time for the next few weeks to review this one, though this package looks really neat! Hope you are able to find another reviewer.

**Comment by lheagy** [comment]
Thanks for getting back to me @jminnier!

**Comment by lheagy** [comment]
:wave: @jkahn, @ikarosilva, would you be willing to review this submission [JOSS](Joss.theoj.org/about)? JOSS is a 'developer friendly' journal. That is, we focus on the software as a scientific contribution. If the submitting authors have followed best practices (have documentation, tests, continuous integration, and a license) then their review should be straight-forward. There are more details on reviewing with JOSS here: http://joss.theoj.org/about#reviewer_guidelines 

I would greatly appreciate your input! If you are unable to take this on at the moment, any recommendations for alternate reviewers would be much appreciated.

**Comment by ikarosilva** [comment]
@lheagy Happy to review this ! Please let me know the timeframe that we are working with so that I can plan accordingly.

Thank you,

-Ikaro

**Comment by lheagy** [comment]
Many thanks @ikarosilva! I will start the review issue. In it, there will be a checklist to help guide your review. If possible, we would appreciate getting your review within the next two weeks.

**Comment by lheagy** [comment]
@whedon add @ikarosilva as reviewer

**Comment by whedon** [comment]
OK, @ikarosilva is now a reviewer

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1663. Feel free to close this issue now!
