### ISSUE TITLE
[PRE REVIEW]: Pakman: a modular, efficient and portable tool for approximate Bayesian inference

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1618]
**Submitting author:** @ThomasPak (<a href="http://orcid.org/0000-0002-7198-7688">Thomas Pak</a>)
**Repository:** <a href="https://github.com/ThomasPak/pakman" target ="_blank">https://github.com/ThomasPak/pakman</a>
**Version:** v1.0.0
**Editor:** @jedbrown
**Reviewers:** @jmlarson1, @gonsie

**Author instructions**

Thanks for submitting your paper to JOSS @ThomasPak. **Currently, there isn't an JOSS editor assigned** to your paper.

@ThomasPak if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01618/joss.01618/10.21105.joss.01618.pdf)

**Comment by labarba** [comment]
@jedbrown — the author suggested you as handling editor. Do you think you could take this one?

**Comment by jedbrown** [comment]
@whedon assign @jedbrown as editor

**Comment by jedbrown** [comment]
@ThomasPak Could you please address [Community Guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines)?

In your paper, this naming would result in `PacMan` (which of course is impossible to search for). Using your last name makes it distinguishable, but I think it's worth thinking about what that looks like to potential contributors if building a community is one of your goals (it need not be for JOSS, but many JOSS authors wish to).
![Screenshot_20190801_113522](https://user-images.githubusercontent.com/3303/62314666-c5c64700-b450-11e9-94ee-b5778dc3c518.png)

**Comment by ThomasPak** [comment]
@jedbrown Hi Jed, thanks for your comment.

I designed Pakman so that it is easy to extend with additional ABC algorithms. This is mentioned in the [code documentation](https://codedocs.xyz/ThomasPak/pakman/index.html). In addition, I  wrote a page that goes into practical detail on how to do this (see [Implementing a Controller subclass](https://codedocs.xyz/ThomasPak/pakman/controller.html)).

I would want and expect that people contribute to this project, and I do not claim sole ownership of Pakman. The name was merely the result of a brainstorming session where I tried to find a name that is memorable and, as you said, makes it distinguishable.

I have to admit though that I did not give too much thought to how the name would be perceived by potential contributors. Would you suggest adding more emphasis on community building in the documentation or finding a new name altogether?

**Comment by jedbrown** [comment]
I think the documentation on extensibility is nice, but it would help to add a [CONTRIBUTING.md](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors) and explain how you would like for issues and questions to be raised. It's common to ask for pull requests and issues to be created on GitHub, but you might want something different or might want to provide further guidelines. There are many facets to creating a welcoming community, but expressing that contributions are encouraged and will be recognized, plus adopting a [code of conduct](https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project) are best practices.
Regarding the name, that's a big change, but it's easier to do now than later. It's entirely your choice, but I think it's worth thinking about how it will be perceived by a community. Linux is successful, but I can't think of many community projects named after an initial author that have thrived.

**Comment by arfon** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by ThomasPak** [comment]
@jedbrown Thanks for the resources on writing contributing guidelines. I have now added a [CONTRIBUTING.md](https://github.com/ThomasPak/pakman/blob/master/CONTRIBUTING.md), as well as a [CODE_OF_CONDUCT.md](https://github.com/ThomasPak/pakman/blob/master/CODE_OF_CONDUCT.md). Apologies for the delay, this is my first open source project so it is all a bit new to me.

After discussing the naming matter with my co-authors, we ultimately decided against changing the name.

**Comment by ThomasPak** [comment]
Dear @jedbrown, I would like to suggest the following reviewers:

- fabian-s
- becarioprecario
- mattpitkin
- Volkerschmid
- gweodoo
- gonsie
- mikaem

I selected these reviewers based on their topic areas including either Bayesian statistics or MPI, as well as their knowledge of C++.

In addition, darrenjw is not on the suggested list of reviewers, but I believe he would be a suitable reviewer for this paper as well.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01618/joss.01618/10.21105.joss.01618.pdf)

**Comment by jedbrown** [comment]
@Volkerschmid @gweodoo @gonsie :wave: Would you be available to review this submission for JOSS?

**Comment by gonsie** [comment]
Yes, I can review.

**Comment by jedbrown** [comment]
@whedon add @jmlarson1 as reviewer

**Comment by whedon** [comment]
OK, @jmlarson1 is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @gonsie as reviewer

**Comment by whedon** [comment]
OK, @gonsie is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1716. Feel free to close this issue now!
