### ISSUE TITLE
[PRE REVIEW]: Porpoise tracker

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1619]
**Submitting author:** @henrikmidtiby (<a href="http://orcid.org/0000-0002-3310-5680">Henrik Skov Midtiby</a>)
**Repository:** <a href="https://github.com/henrikmidtiby/PorpoiseTrackerJOSSPaper/" target ="_blank">https://github.com/henrikmidtiby/PorpoiseTrackerJOSSPaper/</a>
**Version:** v1.0.0
**Editor:** @kthyng
**Reviewers:** @abhishekbajpayee, @jizecn

**Author instructions**

Thanks for submitting your paper to JOSS @henrikmidtiby. **Currently, there isn't an JOSS editor assigned** to your paper.

@henrikmidtiby if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1619 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:123:in `block in check_orcids': Problem with ORCID (0000-0000-0000-0000) for Henrik Dyrberg Egemose (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:121:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:121:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:81:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by labarba** [comment]
@henrikmidtiby — You have a placeholder there instead of your real ORCID number. Please fix.

Also, JOSS expects the `paper.md` and `paper.bib` file to reside in the software repository, and for you to link that repository to this submission, i.e., 
https://github.com/henrikmidtiby/PorpoiseTracker

**Comment by henrikmidtiby** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by henrikmidtiby** [comment]
@labarba Thanks for the comments. They raise two questions.

* One of the authors don't have a orcid yet, is that required to submit to JOSS?
* Is it possible to change the repository of this submission, or should I just create a new submission with the proper repository?

**Comment by labarba** [comment]
I *think* if you leave the ORCID field blank, the compilation will work. Let's try it.

If you move your paper to the software repository, I can update the repository URL by editing the comment above.

**Comment by labarba** [comment]
👋 @kthyng — Could you handle this submission as editor?

PorpoiseTracker: a tool to measure the size and track porpoises or other marine animals from  UAV recordings
https://github.com/henrikmidtiby/PorpoiseTracker

**Comment by kthyng** [comment]
Yep! I'll assign myself.

**Comment by kthyng** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
Hi @henrikmidtiby! Please look through this list of volunteers and provide some suggestions for people to review your submission: https://bit.ly/joss-reviewers
We'll need two reviewers to proceed, so we'll most likely need more than two suggestions. I've noticed a lot of people are traveling right now, too, and are unavailable.

**Comment by henrikmidtiby** [comment]
@labarba 
The JOSS paper was added to the repository in this commit
https://github.com/henrikmidtiby/PorpoiseTracker/commit/4e079085983324f23651395fdaf9691ab85dc2db

@kthyng 
I would suggest the following reviewers based on their descriptions on the list and I have also mentioned why I thinkt they are applicable.
nicoguaro, due to physics and math background
krother, due to biology background
sealhuang, due to experience with machine vision
stsievert, due to image processing
oesteban, due to image processing
abhishekbajpayee, due to image processing
ThomasA, due to image processing
Scivision, due to gis and imaging
jizecn, due to computer vision and navigation

**Comment by kthyng** [comment]
I’m going to mark myself out of office bc I’m traveling but I’ll still be checking in every couple days.

**Comment by kthyng** [comment]
Ill check back in tonight or tomorrow to follow up on reviewers!

**Comment by kthyng** [comment]
Thanks for your suggestions @henrikmidtiby!

@Scivision and @jizecn Are you interested in reviewing this JOSS submission? We ask for reviews within about 3 weeks, and you can find more information about this process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by kthyng** [comment]
Having a hard time getting in contact with people. 

@oesteban, @sealhuang, @abhishekbajpayee Are you interested in reviewing this JOSS submission? We ask for reviews within about 3 weeks, and you can find more information about this process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Looking for two reviewers total, thanks all!

**Comment by abhishekbajpayee** [comment]
@kthyng I should be able to review.

**Comment by kthyng** [comment]
@abhishekbajpayee awesome! Just need one more...

**Comment by oesteban** [comment]
@henrikmidtiby  @kthyng sorry for my slow response - I am having to decline reviews because I can't timely perform them. Thanks for your understanding and good luck with this submission!

**Comment by kthyng** [comment]
Thanks for letting me know, @oesteban!

**Comment by kthyng** [comment]
Ok we have two reviewers, @abhishekbajpayee and @jizecn! Let's get this review started!

**Comment by kthyng** [comment]
@whedon assign @abhishekbajpayee as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @abhishekbajpayee

**Comment by kthyng** [comment]
@whedon add @jizecn as reviewer

**Comment by whedon** [comment]
OK, @jizecn is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1654. Feel free to close this issue now!
