### ISSUE TITLE
[PRE REVIEW]: The UCSCXenaTools R package: a toolkit for accessing genomics data from UCSC Xena platform, from cancer multi-omics to single-cell RNA-seq

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1622]
**Submitting author:** @ShixiangWang (<a href="http://orcid.org/0000-0001-9855-7357">Wang Shixiang</a>)
**Repository:** <a href="https://github.com/ropensci/UCSCXenaTools/" target ="_blank">https://github.com/ropensci/UCSCXenaTools/</a>
**Version:** v1.2.5
**Editor:** @arfon
**Reviewers:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @ShixiangWang. **Currently, there isn't an JOSS editor assigned** to your paper.

@ShixiangWang if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1622 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1622 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-07bb23bf8f0b/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-07bb23bf8f0b/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-07bb23bf8f0b/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
👋 @ShixiangWang — You provided the archive DOI instead of the repository URL, and our bot cannot build your paper. 

Please confirm that this is the correct submission repository:
https://github.com/ropensci/UCSCXenaTools/

**Comment by ShixiangWang** [comment]
@labarba Yes, this is the package repository. I followed the instruction from https://github.com/ropensci/software-review/issues/315#issuecomment-515795175 to submit a Zenodo DOI instead of GitHub repository. I am sorry if this operation was wrong.

**Comment by labarba** [comment]
@arfon — I'm confused. The author was told to "Submit to JOSS using the Zenodo DOI" after acceptance of his software on rOpenSci. We need the software repo URL, so I think there's some confusion here.

**Comment by ShixiangWang** [comment]
@labarba Maybe rOpenSci should update the approval comment template.

Could you help me correct the repository URL?

I still see the Zenodo DOI, but I cannot edit it.

![image](https://user-images.githubusercontent.com/25057508/62433587-94f35400-b767-11e9-9331-29c6f9e7bd5c.png)

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01622/joss.01622/10.21105.joss.01622.pdf)

**Comment by ShixiangWang** [comment]
Amazing!

**Comment by arfon** [comment]
> The author was told to "Submit to JOSS using the Zenodo DOI" after acceptance of his software on rOpenSci. We need the software repo URL, so I think there's some confusion here.

Yes, that's not correct. @ShixiangWang - could you point me to the documentation from rOpenSci that asks for this?

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1627. Feel free to close this issue now!

**Comment by ShixiangWang** [comment]
@arfon It's from to do list at here https://github.com/ropensci/software-review/issues/315#issuecomment-515795175

**Comment by noamross** [comment]
Thanks for pointing this out, @ShixiangWang.  @arfon, we'll fix this in our templates.  Has the submission form changed? I seem to remember that one previously had to put the Zenodo DOI into the form (in addition to the repo URL).

**Comment by arfon** [comment]
> Has the submission form changed?

Nope, it's the same as it's always been. 😁
