### ISSUE TITLE
[PRE REVIEW]: GoFish: Fishing for Line Observations in Protoplanetary Disks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1623]
**Submitting author:** @richteague (<a href="http://orcid.org/0000-0003-1534-5186">Richard Teague</a>)
**Repository:** <a href="https://github.com/richteague/gofish" target ="_blank">https://github.com/richteague/gofish</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewers:** @zhampel, @nespinoza

**Author instructions**

Thanks for submitting your paper to JOSS @richteague. **Currently, there isn't an JOSS editor assigned** to your paper.

@richteague if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1623 with the following error: 

 Error reading bibliography ./paper.bib (line 53, column 98):
unexpected "E"
expecting space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by labarba** [comment]
please merge this fix
https://github.com/richteague/gofish/pull/2

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01623/joss.01623/10.21105.joss.01623.pdf)

**Comment by labarba** [comment]
@arfon — the submitting author suggested you as handling editor. Could you take it?

**GoFish: Fishing for Line Observations in Protoplanetary Disks**
https://github.com/richteague/gofish
[ Article proof :page_facing_up: ](https://github.com/openjournals/joss-papers/blob/joss.01623/joss.01623/10.21105.joss.01623.pdf)

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @richteague, thanks for your submission to JOSS! A couple of quick questions:

- Is this paper accompanying a submission in a AAS publication?
- Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by richteague** [comment]
Hi @arfon! 

No, this paper should be a stand alone, although the methods have previously been described in various AAS articles.

For reviewers, I could suggest ygrange, nespinoza or zhampel, although I'd be happy with any reviewer that's familiar with astronomy.

**Comment by arfon** [comment]
> No, this paper should be a stand alone, although the methods have previously been described in various AAS articles.

👍understood. Thanks.

:wave: @zhampel & @nespinoza - would you be willing to review this submission for JOSS?

**Comment by zhampel** [comment]
@arfon Yes, I'm willing to review this submission.

**Comment by arfon** [comment]
@whedon add @zhampel as reviewer

**Comment by whedon** [comment]
OK, @zhampel is now a reviewer

**Comment by arfon** [comment]
> @arfon Yes, I'm willing to review this submission.

Excellent thanks! I won't start the actual review until I have a second reviewer but thanks in advance for your help here.

**Comment by nespinoza** [comment]
Hi all! Thanks for inviting me to review this exciting piece of software, @arfon. Sadly I will have to decline this time as I am swamped during the next few weeks, and wouldn't want to slow down the process. If there are still no reviewers in two weeks from now, please consider me again!

**Comment by richteague** [comment]
So I'm actually on vacation for the next two and a bit weeks so maybe this would work? I'll be back in the office early September so from my side there's no rush.

**Comment by nespinoza** [comment]
If that's the case then yes, I could start reviewing this the first days of September :-). Does this sound good @arfon?

**Comment by arfon** [comment]
> If that's the case then yes, I could start reviewing this the first days of September :-). Does this sound good @arfon?

Sounds great to me!

**Comment by arfon** [comment]
@whedon add @nespinoza as reviewer

**Comment by whedon** [comment]
OK, @nespinoza is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1632. Feel free to close this issue now!

**Comment by arfon** [comment]
Thanks folks, see you over in #1632 for the actual review.
