### ISSUE TITLE
[PRE REVIEW]: ENZO: An Adaptive Mesh Refinement Code for Astrophysics (Version 2.6)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1624]
**Submitting author:** @bwoshea (<a href="http://orcid.org/0000-0002-2786-0348">Brian O&#39;Shea</a>)
**Repository:** <a href="https://github.com/enzo-project/enzo-dev" target ="_blank">https://github.com/enzo-project/enzo-dev</a>
**Version:** v2.6
**Editor:** @danielskatz
**Reviewers:** @zingale, @rtfisher

**Author instructions**

Thanks for submitting your paper to JOSS @bwoshea. **Currently, there isn't an JOSS editor assigned** to your paper.

@bwoshea if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1624 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1624/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-07bb23bf8f0b/lib/whedon.rb:95:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-07bb23bf8f0b/lib/whedon.rb:78:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-07bb23bf8f0b/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-07bb23bf8f0b/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-07bb23bf8f0b/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-07bb23bf8f0b/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
👋 @bwoshea — something is not quite right with `paper.md`…not sure what. I do notice that the indentation of the tags doesn't quite match the other blocks. Could this be it?

Also, JOSS papers usually reside in the software repository (a different branch is OK), but here you've created a separate repo for just the paper. Is this the software repo?
https://github.com/enzo-project/enzo-dev

Note that in the JOSS workflow the software repository gets added to the decorators on the first-page margin of the published paper, so it kind of breaks things if you put the paper in another repo.

**Comment by labarba** [comment]
@xuanxu — the submitting author suggested you as handling editor. Could you take this one?

**ENZO: An Adaptive Mesh Refinement Code for Astrophysics**
https://github.com/enzo-project/enzo-dev

**Comment by labarba** [comment]
@bwoshea — if you make changes to the paper, you can run `@whedon generate pdf` right here to get our bot to attempt compilation.

**Comment by xuanxu** [comment]
@labarba I can’t take this right now, sorry. I’ll be mostly offline next week. I’d prefer you find another editor for this one.

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
Hi @bwoshea - suggestions for potential reviewers are very welcome. Please consider people on [this list](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Comment by danielskatz** [comment]
@bwoshea - part of the problem with the paper compiling is (or will be) blank ORCIDs - for authors without ORCIDS, remove the blank ORCID line from the .md file

**Comment by labarba** [comment]
Perhaps @zingale might be willing to contribute a review for this submission…
—@zingale: ENZO has been submitted to JOSS: could you review?

**Comment by zingale** [comment]
yes, I can do this, but as it is quite a big code, it would be useful to have additional reviewer(s).

**Comment by labarba** [comment]
Oh, yes, absolutely! We've defaulted to a minimum of two reviewers in JOSS now. But maybe here we need three? Do you know anyone you might recommend?

**Comment by labarba** [comment]
@whedon assign @zingale as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @zingale

**Comment by danielskatz** [comment]
Hey @labarba - do you want to take over editing this one?

**Comment by labarba** [comment]
👋  @bwoshea — to stave off any confusion: I am the Associate-Editor-in-Chief on rotation this week, and generally pushing things along for new submissions (or stuck ones). @danielskatz volunteered to be your handling editor, and will take this into review.

**Comment by labarba** [comment]
@danielskatz — here's a lead for you for another potential reviewer 
https://github.com/r-j-arnold 
https://software.ac.uk/about/fellows/becky-arnold

**Comment by zingale** [comment]
Maybe @rtfisher would be interested in reviewing.

**Comment by danielskatz** [comment]
👋 @r-j-arnold - please let me know if you would be willing to review this for JOSS

**Comment by danielskatz** [comment]
@zingale - thanks - you were actually suggested to me by some else as well, so it's great to have you on board.  We'll need to wait for some changes to the paper so that it compiles, and a second reviewer, then we'll start the reviews

**Comment by rtfisher** [comment]
I'm happy to pitch in the reviewing.

**Comment by r-j-arnold** [comment]
Hi @danielskatz I'm afraid I'm submitting my thesis and moving to america in the next few weeks so I wouldn't be able to do this in a timely fashion. Since Robert and Michael have now said yes, it may be best to proceed with them.

**Comment by danielskatz** [comment]
Thanks @rtfisher, and no worries, @r-j-arnold 
We'll start the reviews once @bwoshea makes the needed changes in the paper

**Comment by danielskatz** [comment]
@whedon add @rtfisher as reviewer

**Comment by whedon** [comment]
OK, @rtfisher is now a reviewer

**Comment by bwoshea** [comment]
@labarba thank you for all of the information!  I just made some updates to the repository and will test it momentarily.

Regarding repositories, would it be fine if we moved the paper to a subdirectory called 'method-paper-JOSS-2019' within our code repository?  It's a bit unclear from the JOSS submission instructions.  I can do that essentially immediately.

**Comment by bwoshea** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1624 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1624/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-3a9b13a3fd39/lib/whedon.rb:106:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-3a9b13a3fd39/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-3a9b13a3fd39/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-3a9b13a3fd39/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-3a9b13a3fd39/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-3a9b13a3fd39/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by bwoshea** [comment]
@danielskatz  Thank you!  @rtfisher and @zingale would be great reviewers.

**Comment by bwoshea** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01624/joss.01624/10.21105.joss.01624.pdf)

**Comment by labarba** [comment]
> would it be fine if we moved the paper to a subdirectory called 'method-paper-JOSS-2019' within our code repository?

You could do that. Our bot [`@whedon`](https://joss.readthedocs.io/en/latest/whedon.html) knows how to look into folders for the paper source. You can also put the paper in a branch, in which case the command to compile will be `@whedon generate pdf from branch <branch-name>`. In any case, we will have to change the repository listed here by editing the top comment. Let us know the URL here.

**Comment by labarba** [comment]
@arfon — have a look at this compiled [article proof](https://github.com/openjournals/joss-papers/blob/joss.01624/joss.01624/10.21105.joss.01624.pdf). With a very long author list, the margin decorators get pushed to the bottom of the page, colliding with the footer. This may require some change to the paper template.

**Comment by bwoshea** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01624/joss.01624/10.21105.joss.01624.pdf)

**Comment by bwoshea** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01624/joss.01624/10.21105.joss.01624.pdf)

**Comment by bwoshea** [comment]
@labarba @arfon I've made a few updates to the repo to fix a few formatting issues, but the link @labarba shared a few minutes ago seems to point to the correct PDF.  Thanks to all for the suggestions about how to sort out the compilation issue!

**Comment by bwoshea** [comment]
> > would it be fine if we moved the paper to a subdirectory called 'method-paper-JOSS-2019' within our code repository?
> 
> You could do that. Our bot [`@whedon`](https://joss.readthedocs.io/en/latest/whedon.html) knows how to look into folders for the paper source. You can also put the paper in a branch, in which case the command to compile will be `@whedon generate pdf from branch <branch-name>`. In any case, we will have to change the repository listed here by editing the top comment. Let us know the URL here.

Understood.  Let me check with the other Enzo developers regarding how they wish to do that.  Would it be OK to proceed with the review using the current repository for the moment?

**Comment by labarba** [comment]
> Would it be OK to proceed with the review using the current repository for the moment?

I believe so. 
@arfon — does manually editing the URL to the software repository on the top comment of the Review issue update the link on the paper's front page in subsequent compilations?

**Comment by arfon** [comment]
> @arfon — does manually editing the URL to the software repository on the top comment of the Review issue update the link on the paper's front page in subsequent compilations?

It does not but I can fix up the JOSS site so that it will.

**Comment by bwoshea** [comment]
> > @arfon — does manually editing the URL to the software repository on the top comment of the Review issue update the link on the paper's front page in subsequent compilations?
> 
> It does not but I can fix up the JOSS site so that it will.

Excellent, thanks!  I just messaged all of the Enzo developers, and we'll move on the repository issue pretty quickly as soon as we reach consensus (meaning on the 2-3 day time frame, given the number of developers).

**Comment by arfon** [comment]
> @arfon — have a look at this compiled article proof. With a very long author list, the margin decorators get pushed to the bottom of the page, colliding with the footer. This may require some change to the paper template.

Thanks for spotting this. This is something we'll have to fix at the end of the review as I'll have to manually override the margin formatting for this paper.

**Comment by danielskatz** [comment]
> Excellent, thanks! I just messaged all of the Enzo developers, and we'll move on the repository issue pretty quickly as soon as we reach consensus (meaning on the 2-3 day time frame, given the number of developers).

@bwoshea - any news on this?

**Comment by bwoshea** [comment]
@danielskatz - yes, I'm moving it over to the enzo-dev repository right now.  As soon as the PR is approved you will be able to find it in the master branch of github.com/enzo-project/enzo-dev in the subdirectory "method-paper-joss-2019".  I'm working to get our required number of approvals right now, and expect that will happen pretty soon.

**Comment by danielskatz** [comment]
Thanks - please be sure to let us know when this is done so that we can start the review

**Comment by bwoshea** [comment]
@danielskatz - the PR is now merged, and you can find the paper in the Enzo code repository (specifically, in https://github.com/enzo-project/enzo-dev/tree/master/method-paper-joss-2019) .  Do you need anything else to start the review?

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01624/joss.01624/10.21105.joss.01624.pdf)

**Comment by labarba** [comment]
I changed the repository URL on the top comment of this issue, then compiled with `whedon`, and it's all good!

**Comment by danielskatz** [comment]
Ok, let's try it and see how the review issue looks

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1636. Feel free to close this issue now!
