### ISSUE TITLE
[PRE REVIEW]: SMBLtoODEpy: A software program for converting SBML models into ODE models in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1625]
**Submitting author:** @ashleefv (<a href="http://orcid.org/0000-0001-9059-5703">Ashlee N. Ford Versypt</a>)
**Repository:** <a href="https://github.com/SMRuggiero/sbmltoodepy" target ="_blank">https://github.com/SMRuggiero/sbmltoodepy</a>
**Version:** v.1.0.2
**Editor:** @mgymrek
**Reviewers:** @SirSharpest, @marouenbg

**Author instructions**

Thanks for submitting your paper to JOSS @ashleefv. **Currently, there isn't an JOSS editor assigned** to your paper.

@ashleefv if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1625 with the following error: 

 Error reading bibliography ./paper.bib (line 14, column 5):
unexpected "t"
expecting space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by ashleefv** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01625/joss.01625/10.21105.joss.01625.pdf)

**Comment by ashleefv** [comment]
I approve of the proof.

**Comment by ashleefv** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by labarba** [comment]
👋  @mgymrek — the submitting author suggested you as handling editor. Could you take this one?

**SMBLtoODEpy: A software program for converting SBML models into ODE models in Python**
https://github.com/SMRuggiero/sbmltoodepy
[ Article proof :page_facing_up: ](https://github.com/openjournals/joss-papers/blob/joss.01625/joss.01625/10.21105.joss.01625.pdf)

**Comment by mgymrek** [comment]
@labarba Sure I can take this one.

**Comment by mgymrek** [comment]
@whedon assign @mgymrek as editor

**Comment by whedon** [comment]
OK, the editor is @mgymrek

**Comment by mgymrek** [comment]
@marouenbg @sirsharpest @dsurujon @sdelandtsheer would either of you be willing to review this submission?

**Comment by marouenbg** [comment]
Hi @mgymrek, I´d be happy to.

**Comment by SirSharpest** [comment]
@mgymrek I'd be happy to also (otherwise, if you just want one, I'm happy to bow out)

**Comment by mgymrek** [comment]
Great, thanks @marouenbg and @SirSharpest!

**Comment by mgymrek** [comment]
@whedon assign @SirSharpest as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @SirSharpest

**Comment by mgymrek** [comment]
@whedon add @marouenbg as reviewer

**Comment by whedon** [comment]
OK, @marouenbg is now a reviewer

**Comment by mgymrek** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1643. Feel free to close this issue now!

**Comment by mgymrek** [comment]
Please head over to #1643 to perform the review. If you are new to reviewing for JOSS, please let me know if you have any questions.
