### ISSUE TITLE
[REVIEW]: neurone_loader: A Python module for loading EEG data recorded with Bittium NeurOne

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1626]
**Submitting author:** @heilerich (<a href="http://orcid.org/0000-0002-9068-2679">Felix Heilmeyer</a>)
**Repository:** <a href="https://github.com/heilerich/neurone_loader" target ="_blank">https://github.com/heilerich/neurone_loader</a>
**Version:** v1.1.0
**Editor:** @brainstorm
**Reviewer:** @rougier, @satra
**Archive:** <a href="https://doi.org/10.5281/zenodo.3468534" target="_blank">10.5281/zenodo.3468534</a>

## Status

[![status](http://joss.theoj.org/papers/c71df4f24b732eabc11b3195a9a8c94d/status.svg)](http://joss.theoj.org/papers/c71df4f24b732eabc11b3195a9a8c94d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/c71df4f24b732eabc11b3195a9a8c94d"><img src="http://joss.theoj.org/papers/c71df4f24b732eabc11b3195a9a8c94d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/c71df4f24b732eabc11b3195a9a8c94d/status.svg)](http://joss.theoj.org/papers/c71df4f24b732eabc11b3195a9a8c94d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/heilerich/neurone_loader" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@rougier & @satra, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @brainstorm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/heilerich/neurone_loader">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.1.0)?
- [x] **Authorship:** Has the submitting author (@heilerich) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/heilerich/neurone_loader">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.1.0)?
- [x] **Authorship:** Has the submitting author (@heilerich) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @rougier, @satra it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01626/joss.01626/10.21105.joss.01626.pdf)

**Comment by brainstorm** [comment]
@rougier @satra Let me know if you have any kind of doubts/issues while conducting this review ;)

**Comment by rougier** [comment]
Sorry, I'm late because I'm on vacation but I will do it next week.

**Comment by satra** [comment]
@brainstorm - i have completed the checklist

**Comment by brainstorm** [comment]
Thanks @satra! I noticed that you didn't check the versioning box... is it because it does not follow [semver](https://semver.org)? (has a `v` as a prefix). If so, @heilerich, could you stick to the [semver](https://semver.org) spec on your releases?

**Comment by brainstorm** [comment]
@rougier no worries, see you next week!

@satra Do you reckon that the "statement of need" is not clear/complete?

**Comment by satra** [comment]
@brainstorm 

- the latest release has not been tagged or pushed to github. pypi says 1.1.0, but github still has 1.0.1
- statement of need is in the pdf of the paper but not in the documentation itself. target audience is in neither and could be made more explicit.

**Comment by brainstorm** [comment]
Thanks Satra, good points. @heilerich, could you please address the points raised please?

**Comment by rougier** [comment]
I'm now reviewing the paper and software. I managed to install the software but I get trouble testing it because I can't get download the data (I opened an issue).  Who is the second author (I cannot find any commit by him)? I also noticed the discrepancy between the GitHub release version (1.0.1) and the release given here (1.1.0).

**Comment by rougier** [comment]
Problem solved.  But tests are failing: 41 failed, 12 passed, 21 error in 3.13 seconds
Test dependencies: zodbpickle, braindecode, mne

Example error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rougier/tmp/neurone_loader/test/test_data/ses1_1_events.npy'
```
test search in `test_data` while it seems to be  in data are in `test/data/NeuroneTestdata`. I ran the get_test_data.sh from inside the test drectory, maybe this is the reason.

Also, it would be good to warn the user (in the README) that the test data is very large (> 2.75 Go).

**Comment by heilerich** [comment]
Thanks for your feedback everyone!

**Release Tag**
@brainstorm @rougier  I have tagged the release on github and also removed the v prefix to comply with semver.

**Statement of Need and Audience**
@satra I added a short statement regarding the purpose of the library to the documentation introduction (see the [review branch](https://github.com/heilerich/neurone_loader/tree/review)). I could add more of the paper contents to the docs but I would prefer to keep it short. Would you be satisfied with the changes I made?
Regarding the target audience I must admit I a little unsure as to how make it more explicit. It is simply anyone working with python and NeurOne equipment. That could include but is not limited to neuroscientists, other researchers, doctors, clinical staff ... Do you think it is necessary to explicitly state that in the documentation?

**Testing**
@rougier The test data should indeed be in the `test/test_data` folder. I added a note to the README that the scripts should be run from the main directory. I also added a note regarding the size of the test data (see the [review branch](https://github.com/heilerich/neurone_loader/tree/review)).
Were you able to run the tests in the meantime?

**Authors**
@rougier The second author is my supervisor. He provided the equipment and the data used in the development. He also provided some (unpublished) reference implementations for loading and converting the data. Some data converted with these implementations are used in the tests as a reference to validate the loading results.

**Comment by rougier** [comment]
Tests are now working. I get 6 failed, 68 passed in 695.95 seconds. Difficult to say where it failed because the output is quite verbose. Last failed test was:
```
___________________________________ TestAgainstBBCI.test_length ____________________________________

self = <test.test_mne_export.TestAgainstBBCI testMethod=test_length>

    def test_length(self):
>       self.assertEqual(self.bbci_cnt.last_samp, self.raw_cnt.last_samp)
E       AssertionError: 33462 != 31198
```
Apart from that I think the submission is now ok for me.

**Comment by heilerich** [comment]
Thanks for testing. I ran the tests again on my machines and everything passed. A [CI Build](https://travis-ci.org/heilerich/neurone_loader/builds/580714188) of the most recent commit is also still passing. I suspect there is some kind of incompatibility regarding the environment. In any case, it seems you might have encountered an actual bug and I would really appreciate your help in resolving this.
Maybe you could open another issue in the [repository](https://github.com/heilerich/neurone_loader/) and provide me with some details including your OS, python version, installed packages (e.g. output of `pip freeze`) and the complete output of the tests (you might consider placing that in a separate gist for the sake of readability). Thanks again and have a nice day 👋🏻

**Comment by brainstorm** [comment]
@satra Does it tick the remaining boxes for you according to https://github.com/openjournals/joss-reviews/issues/1626#issuecomment-524649967?

**Comment by brainstorm** [comment]
Looks all good to ship @arfon.

**Comment by arfon** [comment]
@heilerich - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by heilerich** [comment]
@arfon I have seen your message! Thanks for the reminder. I'm really sorry for the delay, I'm terribly busy at the moment. I will try to fit this in tomorrow.

**Comment by arfon** [comment]
Got it, thanks for the update!

**Comment by heilerich** [comment]
@arfon Okay, released, tagged, deployed, archived ;)
I hope everything works now. The DOI of the zenodo archive is `10.5281/zenodo.3468534`

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3468534 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3468534" target="_blank">10.5281/zenodo.3468534</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.neuroimage.2013.10.027 is OK
- 10.3389/fnins.2013.00267 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1002

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1002, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1179181367290208256) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1003
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01626](https://doi.org/10.21105/joss.01626)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@rougier, @satra - many thanks for your reviews here, and to @brainstorm for editing this one ✨ 

@heilerich - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01626/status.svg)](https://doi.org/10.21105/joss.01626)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01626">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01626/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01626/status.svg
   :target: https://doi.org/10.21105/joss.01626
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01626/status.svg)](https://doi.org/10.21105/joss.01626)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
