### ISSUE TITLE
[REVIEW]: Pannellum: a lightweight web-based panorama viewer

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1628]
**Submitting author:** @mpetroff (<a href="http://orcid.org/0000-0002-4436-4215">Matthew Petroff</a>)
**Repository:** <a href="https://github.com/mpetroff/pannellum" target ="_blank">https://github.com/mpetroff/pannellum</a>
**Version:** v2.5.3
**Editor:** @leouieda
**Reviewer:** @vsoch, @Fil
**Archive:** <a href="https://doi.org/10.5281/zenodo.3373725" target="_blank">10.5281/zenodo.3373725</a>

## Status

[![status](http://joss.theoj.org/papers/91c079a4f6a341b560cea877cc4e2aed/status.svg)](http://joss.theoj.org/papers/91c079a4f6a341b560cea877cc4e2aed)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/91c079a4f6a341b560cea877cc4e2aed"><img src="http://joss.theoj.org/papers/91c079a4f6a341b560cea877cc4e2aed/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/91c079a4f6a341b560cea877cc4e2aed/status.svg)](http://joss.theoj.org/papers/91c079a4f6a341b560cea877cc4e2aed)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mpetroff/pannellum" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@vsoch & @Fil, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @leouieda know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mpetroff/pannellum">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license? **The repository contains a COPYING file, which is detected by GitHub as a license, and follows suit of other GNU software (so I approve)**
- [x] **Version:** v2.5.3
- [x] **Authorship:** Has the submitting author (@mpetroff) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mpetroff/pannellum">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v2.5.3
- [x] **Authorship:** Has the submitting author (@mpetroff) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @vsoch, @Fil it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01628/joss.01628/10.21105.joss.01628.pdf)

**Comment by vsoch** [comment]
Thanks @whedon! I'll be able to get started on this soon.

**Comment by leouieda** [comment]
:wave: @vsoch @Fil thank you for agreeing to review! Please feel free to post your comments on this thread and/or open issues or pull-requests on the software repository. If opening issues or PRs, please remember to mention `openjournals/joss-reviews#1628` so that they are linked back to this thread. This makes it easier for me to monitor the review progress.

@vsoch @Fil @mpetroff please feel free to ask if you have any questions about the review process.

**Comment by mpetroff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01628/joss.01628/10.21105.joss.01628.pdf)

**Comment by Fil** [comment]
Done reviewing, and it's a 💡

**Comment by vsoch** [comment]
My review is complete! @mpetroff has addressed all of my issues (linked above), and specifically:
 - the paper is well written, clearly communicates a need, walks the reader through some background and how it works, and finishes by directing to the documentation
 - the repository now has a clean set of examples, one of which is driven by a Dockerfile to lower the barrier to entry
 - testing is automated 
 - community guidelines are clear

Great work on this @mpetroff! I definitely approve this software for publication in JoSS.

**Comment by mpetroff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01628/joss.01628/10.21105.joss.01628.pdf)

**Comment by mpetroff** [comment]
@leouieda The review was completed a week and a half ago. I just released v2.5.3 with the changes made as a result of the review (mostly documentation / testing improvements) and a few unrelated bug fixes.

**Comment by leouieda** [comment]
Sorry, I just moved this week and forgot to set my away reminder. Will have
a look at the paper tonight and move on with acceptance.

**Comment by leouieda** [comment]
@vsoch @Fil thank you for your reviews :confetti_ball: 

@mpetroff I had a final look through the paper and since both reviewers approve I'm happy to move forward with acceptance of your paper :tada: Here are the steps you need to take now:

- Double check authors and affiliations (including ORCIDs)
- Make a release with the latest changes from the review and post the version number here.
- Archive the release on [Zenodo](https://zenodo.org/) and post the DOI here (make sure the title and author list matches the JOSS paper, if possible).

Let me know if you need help with any of these steps.

**Comment by mpetroff** [comment]
> * Double check authors and affiliations (including ORCIDs)

Done.

> * Make a release with the latest changes from the review and post the version number here.

v2.5.3

> * Archive the release on [Zenodo](https://zenodo.org/) and post the DOI here (make sure the title and author list matches the JOSS paper, if possible).

[10.5281/zenodo.3373725](https://doi.org/10.5281/zenodo.3373725)

**Comment by mpetroff** [comment]
The concept DOI is [10.5281/zenodo.3334433](https://doi.org/10.5281/zenodo.3334433); I don't know which is preferred for JOSS.

**Comment by leouieda** [comment]
@mpetroff thanks! We prefer the DOI for the specific version.

**Comment by leouieda** [comment]
@whedon set version as v2.5.3

**Comment by leouieda** [comment]
@whedon set v2.5.3 as version

**Comment by whedon** [comment]
OK. v2.5.3 is the version.

**Comment by leouieda** [comment]
@whedon set 10.5281/zenodo.3373725 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3373725" target="_blank">10.5281/zenodo.3373725</a> is the archive.

**Comment by leouieda** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01628/joss.01628/10.21105.joss.01628.pdf)

**Comment by leouieda** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/218380.218395 is OK
- 10.23925/1980-7651.2018v21;p71-83 is OK
- 10.1186/s40561-018-0074-x is OK
- 10.1007/978-3-030-04028-4_71 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by leouieda** [comment]
@openjournals/joss-eics this submission is ready for publication :tada:

**Comment by labarba** [comment]
@mpetroff — Could you edit the metadata of the Zenodo archive so the title matches the JOSS paper?

**Comment by labarba** [comment]
Also, you've got three new commits since v2.5.3. Do you need to up the patch version for the accepted software?

**Comment by mpetroff** [comment]
I updated the Zenodo title. The three most recent commits are unrelated to the review and are intended for v2.6.0.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/935

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/935, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1628 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure (OpenSSL::SSL::SSLError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/http.rb:948:in `connect'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/net/http.rb:876:in `start'
	from /app/vendor/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
	from /app/vendor/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
	from /app/vendor/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
	from /app/vendor/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient.rb:67:in `get'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/compilers.rb:291:in `jats_from_markdown'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/compilers.rb:28:in `generate_jats'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:96:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:79:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
Yikes! Something has gone awry. @arfon — help!

**Comment by vsoch** [comment]
help us, @arfon! You're our only hope...

![giphy](https://user-images.githubusercontent.com/814322/64069397-bb959500-cc16-11e9-9d6e-a40f2ba996a7.gif)

**Comment by danielskatz** [comment]
I would just try again. Some faults are transient

**Comment by vsoch** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
I'm sorry @vsoch, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by vsoch** [comment]
Denied! :P

**Comment by vsoch** [comment]
And @whedon is channeling Hal... is the predicted future from the movie coming true? Things just got real! :scream: 

Happy Saturday everyone :)

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1167921146546667520) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/936
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01628](https://doi.org/10.21105/joss.01628)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by vsoch** [comment]
Woohoo congrats @mpetroff !

**Comment by labarba** [comment]
It worked. Congratulations, @mpetroff, your JOSS paper is published! 🚀 

Big thanks to our editor: @leouieda, and the reviewers: @vsoch, @Fil — thank you for your contributions to JOSS 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01628/status.svg)](https://doi.org/10.21105/joss.01628)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01628">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01628/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01628/status.svg
   :target: https://doi.org/10.21105/joss.01628
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01628/status.svg)](https://doi.org/10.21105/joss.01628)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by mpetroff** [comment]
Thank you @vsoch and @Fil for the prompt and detailed comments, and thank you @leouieda and @labarba for editorial support!
