### ISSUE TITLE
[PRE REVIEW]: nse: Computation of Numerical Standard Errors in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#163]
**Submitting author:** @ArdiaD (<a href="http://orcid.org/0000-0003-2823-782X">David Ardia</a>)
**Repository:** <a href="https://github.com/keblu/nse" target ="_blank">https://github.com/keblu/nse</a>
**Version:** v1-00.16
**Editor:** @arfon
**Reviewer:** @braverock

**What this issue is for**

Thanks for submitting your paper to JOSS @ArdiaD. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by ArdiaD** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by ArdiaD** [comment]
@arfon We have released version v1-00.16, and the version we asked for the review was v1-00.15. How can we ensure that the review will be on the current version number, v1-00.16?

**Comment by arfon** [comment]
> @arfon We have released version v1-00.16, and the version we asked for the review was v1-00.15. How can we ensure that the review will be on the current version number, v1-00.16?

Thanks for the heads up - I've updated the version at the top of this thread to track this.

**Comment by ArdiaD** [comment]
Thanks for this @arfon !

**Comment by ArdiaD** [comment]
Btw @arfon, maybe @braverock would also be willing to review this package.

**Comment by braverock** [comment]
@arfon I agree, I am familiar with this work, and have published similar work in other places. I am willing to review the NSE package.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @braverock as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @braverock

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/172. Feel free to close this issue now!

**Comment by arfon** [comment]
> @arfon I agree, I am familiar with this work, and have published similar work in other places. I am willing to review the NSE package.

@braverock - many thanks. Please head over to #172 where the review should take place.
