### ISSUE TITLE
[REVIEW]: GoFish: Fishing for Line Observations in Protoplanetary Disks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1632]
**Submitting author:** @richteague (<a href="http://orcid.org/0000-0003-1534-5186">Richard Teague</a>)
**Repository:** <a href="https://github.com/richteague/gofish" target ="_blank">https://github.com/richteague/gofish</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** @zhampel, @nespinoza
**Archive:** <a href="https://doi.org/10.5281/zenodo.3403894" target="_blank">10.5281/zenodo.3403894</a>

## Status

[![status](http://joss.theoj.org/papers/f2808d0c1cc0ffb51aa60466c896ed06/status.svg)](http://joss.theoj.org/papers/f2808d0c1cc0ffb51aa60466c896ed06)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f2808d0c1cc0ffb51aa60466c896ed06"><img src="http://joss.theoj.org/papers/f2808d0c1cc0ffb51aa60466c896ed06/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f2808d0c1cc0ffb51aa60466c896ed06/status.svg)](http://joss.theoj.org/papers/f2808d0c1cc0ffb51aa60466c896ed06)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/richteague/gofish" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@zhampel & @nespinoza, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/richteague/gofish">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@richteague) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/richteague/gofish">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@richteague) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @zhampel, @nespinoza it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01632/joss.01632/10.21105.joss.01632.pdf)

**Comment by arfon** [comment]
Re-stating here that @nespinoza won't be able to start his review until early September.

**Comment by zhampel** [comment]
@richteague

*Paper*
Corrections/Clarifications:
- requirer -> require
- which is assumed to random -? which is assumed to be random / which is assumed random
- Can you please specify what is meant by random, i.e. type or distribution?
- Does 'correcting' need to be in quotes? It is a correction operation itself, no?
- mass of the mass of the central star -> mass of the central star


*Documentation*

- I recommend you provide a clearly labelled section on your GitHub README that provides some basic form of documentation & usage. Preferably also a clear link in this section that directs to your doc page. The little icon below the molecular fishing image is a bit small and easily bypassed.
- Your readthedocs page is nice & thorough.
- The Harvard Dataverse link directs to a page claiming that the service is unavailable. Is this a bad link or an intermittent issue?

Once access is permitted to the example data from Harvard Dataverse, I will continue my review of the codebase operability/functionality.

**Comment by labarba** [comment]
@whedon remind @nespinoza in three days

**Comment by whedon** [comment]
Reminder set for @nespinoza in three days

**Comment by whedon** [comment]
:wave: @nespinoza, please update us on how your review is going.

**Comment by richteague** [comment]
@zhampel 

Thanks for the initial comments!

I've corrected the manuscript draft following your suggestions. I've also updated the README to include a brief example usage and another link to the documentation. Please let me know if you feel as if there should be more here.

Regarding the data files, these should be persistent and are likely an intermittent issue. I have checked the downloads and had others verify that they're able to download the data cube so hopefully everything is good to go.

**Comment by nespinoza** [comment]
Hi everyone!

First of all, congrats @richteague on this very useful piece of software! I tested the whole code and all worked for me (in particular, the TWHya dataset worked for me). I have gone over the documentation and paper, and have a few minor comments I would like to cover, and one moderate comment at the end:

**Regarding the paper**:

- For some reason the references are not compiling correctly --- I think this has to do with the fact that the `paper.md` file in the repository is performing the citations using commas between each citation, i.e., you are doing `'[@citation]'` instead of simply doing `[@citation]`.

**Regarding the code & documentation**:

- In the documentation, I had trouble viewing line [10] of the notebook (Fishing Basics --- "Extracing a Disk Averaged Spectrum") in my computer (I had to go to the actual notebook to run/see this line in my own system). This might be because the line is too long --- perhaps you could consider breaking the line in two with `\`. 
- A bit of a technical question: in line [12] and [13] of the notebook of the same section, you play with resampling the data. However, the errorbars go _up_ when you bin the data in velocity-space where they should intuitively go _down_ (you have more data on each bin, hence, errors on the flux density should go down as ~`1/sqrt(n)` where `n` is the number of samples in the bin). I checked the code and it seems this goes back to `eddy`, which in turn calls `scipy.stats.binned_statistics`. Turns out that when you ask for `std` in `scipy.stats.binned_statistics` this returns the _sample_ standard deviation on each bin, whereas what you really want, I believe, is the _error on the flux density_ for the given bin. Assuming independent and identically distributed data, a good measure of this is the standard error on the mean, which is given by the sample standard deviation divided by the square-root of `n`. I believe it is important this is reported in the documentation, because some people (like me) would perhaps be expecting the error on the flux densities to be reported and not the sample standard deviation of the bin, which are different statistics.

**Comment by richteague** [comment]
Hi @nespinoza!

Thanks for the comments!

I've corrected the citation style, hopefully this works now.

I've included a line break in line 10 of the Fishing Basics notebook and appears to render OK.

I've added a small community guidelines section pointing towards the (albeit brief) contributing guide on the main repo. If you think this require more info I can update this.

Regarding the technical question, you're absolutely right. I made the choice in `eddy` to use just the standard deviation because the spectra will have some small levels of correlation (both spatially and spectrally). However, I've included a new argument, `assume_correlated` which, if set to `False` (the default is `True`), it estimates the error following the poisson statistics you described above. I've included both a note in the function docstrings to highlight this and included another cell in the notebook demonstrating this.

**Comment by nespinoza** [comment]
Thanks for the quick response to the comments @richteague! I'm all set then --- ready to accept the paper to JOSS (as soon as the code has a release version in Github, so I can mark the "version" part above)!

**Comment by richteague** [comment]
Great, thanks a lot! I'll wait to see if @zhampel has any other issues with it, then I'll update the release version on GitHub.

**Comment by zhampel** [comment]
@richteague 

Thanks for your changes, and after having been able to download the dataset, I see that the functionality is as advertised. BTW the documentation is very thorough and appreciated!

However, I have a request regarding the installation which can have an impact on those wishing to contribute (e.g. if users fork the repo and wish to make PRs). I recommend that you add an `__init__.py` file in the gofish with the following lines:

# __init__.py

from .gofish import *

This would allow a user to (instead of running `pip install gofish`) clone the repo, setup a virtualenv and run `python setup.py install`. Then the user would have an easier time testing and contributing to your codebase. After such a change is made, I will check off the installation & contributing boxes, as this will facilitate user contributions. Then I think you can update the version. Is that acceptable?

One other thing: have you considered adding an emcee search to the advanced fishing example?

**Comment by richteague** [comment]
@zhampel - Thanks a lot for the report! I've added the `__init__.py` file to the main repo. I've thought about adding an emcee search to the documentation and this is something I want to to, however I'm working with a collaborator to get some real data that would be more appropriate for such an example. As it might take a little while to get the data, I didn't want that to delay the publication of the software.

I've also updated the version to v1.0 in GitHub (@nespinoza).

Thanks again to you both for your quick reviews!

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01632/joss.01632/10.21105.joss.01632.pdf)

**Comment by arfon** [comment]
@richteague - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by richteague** [comment]
@arfon - Here's the Zenodo DOI: https://doi.org/10.5281/zenodo.3403894

**Comment by arfon** [comment]
@richteague - minor point, could you remove Lorena's name from the authors of the Zenodo archive?

Also, could you update the title of your submission to match the paper, i.e. change it to `GoFish: Fishing for Line Observations in Protoplanetary Disks`

**Comment by richteague** [comment]
@arfon - No problem, I've made those changes!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3403894 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3403894" target="_blank">10.5281/zenodo.3403894</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/960

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/960, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1171483676799946753) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/961
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01632](https://doi.org/10.21105/joss.01632)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@zhampel, @nespinoza - many thanks for your reviews here ✨ 

@richteague - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01632/status.svg)](https://doi.org/10.21105/joss.01632)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01632">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01632/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01632/status.svg
   :target: https://doi.org/10.21105/joss.01632
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01632/status.svg)](https://doi.org/10.21105/joss.01632)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon this paper lacks a **References** heading. Should one be added?

**Comment by arfon** [comment]
> @arfon this paper lacks a References heading. Should one be added?

Good catch @Kevin-Mattheus-Moerman.

@richteague - could you please merge this small change to your paper? https://github.com/richteague/gofish/compare/master...arfon:patch-1
