### ISSUE TITLE
[PRE REVIEW]: PressureDrop.jl: Pressure traverses for oil & gas wells

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1633]
**Submitting author:** @jnoynaert (<a href="http://orcid.org/0000-0002-2986-0376">Jared Noynaert</a>)
**Repository:** <a href="https://github.com/jnoynaert/PressureDrop.jl" target ="_blank">https://github.com/jnoynaert/PressureDrop.jl</a>
**Version:** v1.0.1
**Editor:** @oliviaguest
**Reviewers:** @wkearn, @mancellin

**Author instructions**

Thanks for submitting your paper to JOSS @jnoynaert. **Currently, there isn't an JOSS editor assigned** to your paper.

@jnoynaert if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01633/joss.01633/10.21105.joss.01633.pdf)

**Comment by arfon** [comment]
Thanks for your submission to JOSS @jnoynaert. Please could you remove the backticks around the citations you have in your `paper.md` so Pandoc can pick them up?

**Comment by jnoynaert** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01633/joss.01633/10.21105.joss.01633.pdf)

**Comment by jnoynaert** [comment]
Maybe @wkearn would be a good reviewer?

**Comment by wkearn** [comment]
I would be happy to review this submission!

**Comment by arfon** [comment]
:wave: @oliviaguest - would you be willing to edit this submission for JOSS?

**Comment by oliviaguest** [comment]
@arfon yes, I am more than happy to edit this! 😄 

@whedon assign @oliviaguest as editor

**Comment by oliviaguest** [comment]
@whedon add @wkearn as reviewer

**Comment by oliviaguest** [comment]
@mancellin are you interested and able to review *[PressureDrop.jl: Pressure traverses for oil & gas wells](https://github.com/jnoynaert/PressureDrop.jl)* for [JOSS](https://joss.theoj.org)?

**Comment by arfon** [comment]
> @arfon yes, I am more than happy to edit this! 😄

BTW, you need to issue commands to @whedon on their own (i.e. not after some other comment).

**Comment by arfon** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by arfon** [comment]
@whedon add @wkearn as reviewer

**Comment by whedon** [comment]
OK, @wkearn is now a reviewer

**Comment by oliviaguest** [comment]
@arfon ah, thanks!

**Comment by mancellin** [comment]
Hello everybody. I'm on holidays until next week. If you don't mind waiting a bit, I'd be happy to do the review.

**Comment by oliviaguest** [comment]
@mancellin of course, fantastic!

**Comment by oliviaguest** [comment]
@whedon add @mancellin as reviewer

**Comment by whedon** [comment]
OK, @mancellin is now a reviewer

**Comment by oliviaguest** [comment]
@labarba do I now just start the review with whedon? :blush:

**Comment by danielskatz** [comment]
yes, ```@whedon start review```

**Comment by labarba** [comment]
And once you start the review, close this issue, and go to the Review issue to post a welcoming message to get a ping out to the reviewers. I use something like:

> 👋 <rev1> <rev2> — This is where the action happens. You both have a review checklist to work your way through. Feel free to post questions here and open review issues in the submission repository (with a link to this issue).

**Comment by oliviaguest** [comment]
@danielskatz thank you — I was wondering what more there is before I issue that in case anything else needs to happen. 😅 

@labarba ah, thanks! Will whedon link us from here to the new issue it opens?

**Comment by labarba** [comment]
Yep. Try it!

**Comment by danielskatz** [comment]
You may want to browse https://joss.readthedocs.io/en/latest/editing.html as well.

And if you want to ask something of the associate editor in chief on duty, please ping ```@openjournals/joss-eics``` rather than a specific person

**Comment by labarba** [comment]
@danielskatz — I'm @oliviaguest's onboarding buddy.

**Comment by danielskatz** [comment]
> @danielskatz — I'm @oliviaguest's onboarding buddy.

Ok, that makes sense

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1642. Feel free to close this issue now!
