### ISSUE TITLE
[REVIEW]: Spruceup: fast and flexible identification, visualization, and removal of outliers from large multiple sequence alignments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1635]
**Submitting author:** @marekborowiec (<a href="http://orcid.org/0000-0001-7510-4064">Marek Borowiec</a>)
**Repository:** <a href="https://github.com/marekborowiec/spruceup" target ="_blank">https://github.com/marekborowiec/spruceup</a>
**Version:** v2019.2.3
**Editor:** @csoneson
**Reviewer:** @iimog, @gavinmdouglas
**Archive:** <a href="https://doi.org/10.5281/zenodo.3476875" target="_blank">10.5281/zenodo.3476875</a>

## Status

[![status](https://joss.theoj.org/papers/841347d12b4da595f6751339fac8f29c/status.svg)](https://joss.theoj.org/papers/841347d12b4da595f6751339fac8f29c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/841347d12b4da595f6751339fac8f29c"><img src="https://joss.theoj.org/papers/841347d12b4da595f6751339fac8f29c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/841347d12b4da595f6751339fac8f29c/status.svg)](https://joss.theoj.org/papers/841347d12b4da595f6751339fac8f29c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/marekborowiec/spruceup" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@iimog & @gavinmdouglas, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/marekborowiec/spruceup">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v2019.2.3
- [x] **Authorship:** Has the submitting author (@marekborowiec) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/marekborowiec/spruceup">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v2019.2.3
- [x] **Authorship:** Has the submitting author (@marekborowiec) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @iimog, @gavinmdouglas it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01635/joss.01635/10.21105.joss.01635.pdf)

**Comment by csoneson** [comment]
@iimog, @gavinmdouglas - please perform your review in this issue (see instructions in the first comment above). If you have any questions, don't hesitate to ping me.

 @marekborowiec - please have a look at the review criteria in the checklists above and check that your repository contains all the required items. Otherwise, you can add them already now to simplify the review process!

**Comment by csoneson** [comment]
Hi all - I just wanted to check in on this submission and the progress of the review process. @marekborowiec - there seems to be a couple of issues open in your repository, do you think you will be able to address them? Don't hesitate to ping me if anything is unclear!

**Comment by marekborowiec** [comment]
Hello all,

Thank you for checking in, @csoneson; I'm working on it!
@iimog and @gavinmdouglas: thank you both for constructive reviews! Your suggestions will help me improve the tool. Please bear with me as I'm slowly getting through them; I might be asking some clarification questions along the way!

**Comment by csoneson** [comment]
Just checking in again - @marekborowiec, could you give us an update on the progress with the revision?

**Comment by marekborowiec** [comment]
Thanks for checking in @csoneson. Still working on it. I'm almost done with the long laundry list of problems in Issue #5. My schedule becomes better at the end of this week and I hope I'll be able to address all the remaining issues next week.

**Comment by gavinmdouglas** [comment]
All of my points have been addressed in https://github.com/marekborowiec/spruceup/issues/5 and I have nothing else to add.

**Comment by iimog** [comment]
Same applies to me. All my points have been addressed to my satisfaction. Nothing to add.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01635/joss.01635/10.21105.joss.01635.pdf)

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.ympev.2016.05.030 is OK
- 10.1186/s12864-015-2146-4 is OK
- 10.1093/sysbio/syw101 is OK
- 10.1093/bioinformatics/btp348 is OK
- 10.1186/1471-2148-10-210 is OK
- 10.1186/s12862-019-1350-2 is OK
- 10.1186/1748-7188-3-7 is OK
- 10.1016/j.ympev.2015.10.027 is OK
- 10.1093/sysbio/sys004 is OK
- 10.1186/1742-9994-7-10 is OK
- 10.1186/s12864-018-4620-2 is OK
- 10.1080/10635150500541730 is OK
- 10.1093/nar/gkq443 is OK
- 10.5852/ejt.2017.283 is OK
- 10.1038/s41559-017-0126 is OK
- 10.1080/14772000.2017.1401016 is OK
- 10.1080/10635150701472164 is OK
- 10.1093/sysbio/syy043 is OK
- 10.1093/bioinformatics/bty448 is OK
- 10.1371/journal.pone.0030288 is OK
- 10.1093/molbev/msu245 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@iimog, @gavinmdouglas - thanks a lot for your thorough reviews!

@marekborowiec - I have sent a PR with a couple of small fixes to a few bib items. I'll get back to you shortly to finalize the acceptance.

**Comment by marekborowiec** [comment]
Thank you, @csoneson!

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01635/joss.01635/10.21105.joss.01635.pdf)

**Comment by csoneson** [comment]
@marekborowiec - paper looks good. Here are the next steps:
- [ ] Check that the software version is consistently reported
- [ ] Create a tagged release of the current version of the software and report the version tag here
- [ ] Archive the software in Zenodo. Make sure that the title and authors of the archive are the same as those of the paper (you can also add ORCID)
- [ ] Report back the doi of the Zenodo archive here

**Comment by marekborowiec** [comment]
The pdf looks great! One minor remark: the current release is 2019.2.2, not 2019.1.1 as indicated at the top of this page.

**Comment by csoneson** [comment]
That's fine - we'll set the release version when the Zenodo archive is done. That will be the final version reported with the publication.

**Comment by marekborowiec** [comment]
> * [X]  Check that the software version is consistently reported
> * [X]  Create a tagged release of the current version of the software and report the version tag here

https://github.com/marekborowiec/spruceup/tree/v2019.2.2

> * [X]  Archive the software in Zenodo. Make sure that the title and authors of the archive are the same as those of the paper (you can also add ORCID)
> * [X]  Report back the doi of the Zenodo archive here

@csoneson 
https://doi.org/10.5281/zenodo.3476720

**Comment by marekborowiec** [comment]
> * [X]  Check that the software version is consistently reported
> * [X]  Create a tagged release of the current version of the software and report the version tag here


> * [ ]  Archive the software in Zenodo. Make sure that the title and authors of the archive are the same as those of the paper (you can also add ORCID)
> * [ ]  Report back the doi of the Zenodo archive here

**Comment by csoneson** [comment]
@whedon set v2019.2.3 as version

**Comment by whedon** [comment]
OK. v2019.2.3 is the version.

**Comment by csoneson** [comment]
@whedon set 10.5281/zenodo.3476875 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3476875" target="_blank">10.5281/zenodo.3476875</a> is the archive.

**Comment by csoneson** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.ympev.2016.05.030 is OK
- 10.1186/s12864-015-2146-4 is OK
- 10.1093/sysbio/syw101 is OK
- 10.1093/bioinformatics/btp348 is OK
- 10.1186/1471-2148-10-210 is OK
- 10.1186/s12862-019-1350-2 is OK
- 10.1186/1748-7188-3-7 is OK
- 10.1016/j.ympev.2015.10.027 is OK
- 10.1093/sysbio/sys004 is OK
- 10.1186/1742-9994-7-10 is OK
- 10.1186/s12864-018-4620-2 is OK
- 10.1080/10635150500541730 is OK
- 10.1093/nar/gkq443 is OK
- 10.5852/ejt.2017.283 is OK
- 10.1038/s41559-017-0126 is OK
- 10.1080/14772000.2017.1401016 is OK
- 10.1080/10635150701472164 is OK
- 10.1093/sysbio/syy043 is OK
- 10.1093/bioinformatics/bty448 is OK
- 10.1371/journal.pone.0030288 is OK
- 10.1093/molbev/msu245 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1009

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1009, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by csoneson** [comment]
@openjournals/joss-eics - we're ready for you to take over!

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1181694542984155136) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1013
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01635](https://doi.org/10.21105/joss.01635)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @marekborowiec, your JOSS paper is now published! 🚀 

Big thanks to our editor: @csoneson, and the reviewers: @iimog, @gavinmdouglas — your contribution to JOSS is greatly appreciated 🙏

**Comment by marekborowiec** [comment]
Thank you @labarba, @csoneson, @iimog and @gavinmdouglas!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01635/status.svg)](https://doi.org/10.21105/joss.01635)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01635">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01635/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01635/status.svg
   :target: https://doi.org/10.21105/joss.01635
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01635/status.svg)](https://doi.org/10.21105/joss.01635)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
