### ISSUE TITLE
[REVIEW]: ENZO: An Adaptive Mesh Refinement Code for Astrophysics (Version 2.6)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1636]
**Submitting author:** @bwoshea (<a href="http://orcid.org/0000-0002-2786-0348">Brian O&#39;Shea</a>)
**Repository:** <a href="https://github.com/enzo-project/enzo-dev" target ="_blank">https://github.com/enzo-project/enzo-dev</a>
**Version:** v2.6.1
**Editor:** @danielskatz
**Reviewer:** @zingale, @rtfisher
**Archive:** <a href="https://doi.org/10.5281/zenodo.3469922" target="_blank">10.5281/zenodo.3469922</a>

## Status

[![status](https://joss.theoj.org/papers/ee73bb825d396e5ddf95b96d9300f295/status.svg)](https://joss.theoj.org/papers/ee73bb825d396e5ddf95b96d9300f295)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ee73bb825d396e5ddf95b96d9300f295"><img src="https://joss.theoj.org/papers/ee73bb825d396e5ddf95b96d9300f295/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ee73bb825d396e5ddf95b96d9300f295/status.svg)](https://joss.theoj.org/papers/ee73bb825d396e5ddf95b96d9300f295)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/enzo-project/enzo-method-paper-JOSS-2019" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@zingale & @rtfisher, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/enzo-project/enzo-method-paper-JOSS-2019">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v2.6.1
- [x] **Authorship:** Has the submitting author (@bwoshea) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/enzo-project/enzo-method-paper-JOSS-2019">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v2.6.1
- [x] **Authorship:** Has the submitting author (@bwoshea) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @zingale, @rtfisher it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01636/joss.01636/10.21105.joss.01636.pdf)

**Comment by danielskatz** [comment]
I had to update the repository URL on the top comment of this issue. (note to @arfon -  whedon didn't use the URL in the pre-report issue, and this may also lead to a problem when we do the final acceptance.)

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01636/joss.01636/10.21105.joss.01636.pdf)

**Comment by danielskatz** [comment]
@bwoshea - merging https://github.com/enzo-project/enzo-dev/pull/93 will fix 2 small bib entries

**Comment by danielskatz** [comment]
👋 @zingale, @rtfisher - we are ready for you to review this now.  Please read the first 2 comments in this issue carefully.  Your job now is to go through the paper (the latest "check article proof" in this issue) and the repository, and check off items in your checklist until you are done, and if you find problems, either report them here or create an issue in the repo and mention this issue in that one.

If you have any questions or problems, please let me know.

**Comment by rtfisher** [comment]
I am just beginning the review process. I find the documentation link (https://enzo-project.org/docs/2.6/) under https://github.com/enzo-project/enzo-dev returns a 404.

**Comment by danielskatz** [comment]
> @bwoshea - merging [enzo-project/enzo-dev#93](https://github.com/enzo-project/enzo-dev/pull/93) will fix 2 small bib entries

Now that this has been done, I will recompile - @bwoshea, you can do this too, just the way I am, with an instruction in whedon in a new comment (letting you know in case more changes are needed)

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01636/joss.01636/10.21105.joss.01636.pdf)

**Comment by zingale** [comment]
regarding 

> References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)

There are 2 references to Enzo itself, referring to github.  Should these be changed to an archived version of the code with a DOI?

**Comment by zingale** [comment]
The license is UI/NCSA until 2000 and UC BSD until 2008, both are on the OSI list.  Should we assume the last license remains in effect since 2008?

**Comment by zingale** [comment]
https://github.com/enzo-project/enzo-dev/issues/94

**Comment by zingale** [comment]
https://github.com/enzo-project/enzo-dev/issues/95

**Comment by zingale** [comment]
https://github.com/enzo-project/enzo-dev/issues/96

**Comment by zingale** [comment]
https://github.com/enzo-project/enzo-dev/issues/97

**Comment by zingale** [comment]
https://github.com/enzo-project/enzo-dev/issues/98

**Comment by zingale** [comment]
https://github.com/enzo-project/enzo-dev/issues/99

**Comment by zingale** [comment]
https://github.com/enzo-project/enzo-dev/issues/100

**Comment by zingale** [comment]
https://github.com/enzo-project/enzo-dev/issues/106

**Comment by zingale** [comment]
I'm done with my pass through the docs and have filed a number of issues, some which I would like to see addressed for the review (marked with `[JOSS REVIEW]`) and others that are suggestions to take into consideration.

I will try running some standard test problems next.

**Comment by danielskatz** [comment]
@zingale  - thanks for all your comments so far. If possible, when you open an issue in https://github.com/enzo-project/enzo-dev, just mention this review thread (https://github.com/openjournals/joss-reviews/issues/1636) in that issue rather than posted that issue in this thread.  This will insert a note here that will show if the issue is open or closed.

**Comment by zingale** [comment]
oh, I see, I did it backwards.  I'll fix that.

**Comment by danielskatz** [comment]
👋 @bwoshea - note that we're waiting for you to respond to a bunch of open issues - listed above...

**Comment by rtfisher** [comment]
Just to clarify, I am still in the process of completing my review. @bwoshea indicates that the ENZO team is awaiting this completion prior to starting their responses.

**Comment by danielskatz** [comment]
That's ok, but JOSS reviews typically are more interactive.  Maybe with a complex team like this, it makes sense to wait.

**Comment by bwoshea** [comment]
@danielskatz  Sorry about that.  Given the vigor of @zingale 's review and the distributed nature of the Enzo team, we would prefer to wait until the reviews are completed (or at least the first wave of feedback) until we proceed.  If you insist on doing it otherwise I'm sure we can make that happen, though.

**Comment by danielskatz** [comment]
It’s fine to wait, as I said previously

**Comment by rtfisher** [comment]
Ok, I've completed my initial review. It looks like I also identified some of the same issues as @zingale, though our final assessments of the JOSS requirements differ slightly.

**Comment by danielskatz** [comment]
Thanks @rtfisher! Now over to @bwoshea and the Enzo team...

**Comment by bwoshea** [comment]
@danielskatz We're on it!  @rtfisher and @zingale , thank you for all of your feedback!

**Comment by bwoshea** [comment]
@zingale @rtfisher just to give you a heads-up, we've addressed all of the issues you have raised but one, and that should be done in the next day or so.  We've left all off the PRs open so that you can see what has been changed, and all PRs and issues are cross-referenced.  We're ready for your feedback whenever you are available.

**Comment by zingale** [comment]
It looks like all of my issues have been addressed via PRs.  Once those PRs are merged, I am happy with accepting.

**Comment by rtfisher** [comment]
I am fine with accepting after merger as well.

**Comment by bwoshea** [comment]
@zingale @rtfisher thanks!  

@rtfisher to clarify, there are two open issues that you raised (https://github.com/enzo-project/enzo-dev/issues/108 and https://github.com/enzo-project/enzo-dev/issues/109 ) - would you mind making a quick note saying you're OK with what we've done for those?

**Comment by rtfisher** [comment]
Thank you, @bwoshea. Sorry for the delayed response -- I was serving on a panel today.

I concur that the issues are now resolved, and have closed both.

**Comment by danielskatz** [comment]
The next steps will be
1. The authors (@bwoshea) to make any remaining changes (sorry, I can't easily tell if there's more to do or if you've already done this because the PRs didn't reference this review thread) and saying that they are done here.
1. The reviewers (@zingale and @rtfisher) to confirm that they are satisfied by checking off the remaining items in their review checklists above and by saying so in this thread.

**Comment by bwoshea** [comment]
@danielskatz  we have made the remaining changes!

**Comment by danielskatz** [comment]
👋 @zingale and @rtfisher: please confirm that you are satisfied by checking off the remaining items in your review checklists above and by saying so in this thread.  If not, please say what you think any current issues are.

**Comment by zingale** [comment]
I'm happy to accept.  I've check all my boxes.  Nice job @bwoshea and the Enzo team.

**Comment by rtfisher** [comment]
I accept as well, and second Michael's congratulations to @bwoshea and all of the many Enzo developers!

**Comment by danielskatz** [comment]
Great - thanks @zingale and @rtfisher!

**Comment by danielskatz** [comment]
👋 @bwoshea - to finish up now, I need you to 

1. deposit the repository in an archive (e.g. zenodo) and to report the DOI here
1. tell me the latest version number here
1. confirm that the paper text and references are final

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01636/joss.01636/10.21105.joss.01636.pdf)

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1088/0067-0049/211/2/19 is OK
- 10.1038/s41586-019-0873-4 is OK
- 10.1093/mnras/stv1509 is OK
- 10.1088/2041-8205/807/1/L12 is OK
- 10.3847/1538-4357/ab0654 is OK
- 10.3847/1538-4357/aa6fb1 is OK
- 10.1093/mnras/stv2641 is OK
- 10.3847/1538-4357/aa88c1 is OK
- 10.1103/PhysRevE.95.033206 is OK
- 10.1103/PhysRevLett.121.021104 is OK
- 10.3847/2041-8213/834/1/L1 is OK
- 10.1126/science.1173540 is OK
- 10.1093/mnras/sty2984 is OK
- 10.3847/1538-4357/aae30b is OK
- 10.1093/mnras/stw3291 is OK
- 10.1093/mnras/stt2121 is OK
- 10.1088/0004-637X/809/1/69 is OK
- 10.3847/1538-4357/aa799f is OK
- 10.1103/PhysRevD.99.063509 is OK
- 10.1051/0004-6361:200809967 is OK
- 10.1093/mnras/sty1289 is OK
- 10.3847/1538-4357/aa7263 is OK
- 10.3847/0004-637X/827/1/28 is OK
- 10.1093/mnras/stw1461 is OK
- 10.3847/1538-4357/aab7f2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @bwoshea - to finish up now, I need you to

deposit the repository in an archive (e.g. zenodo) and report the DOI here
tell me the latest version number here
confirm that the paper text and references are final

**Comment by danielskatz** [comment]
👋 @bwoshea - to finish up now, I need you to

1. deposit the repository in an archive (e.g. zenodo) and report the DOI here
1. tell me the latest version number here
1. confirm that the paper text and references are final

**Comment by bwoshea** [comment]
@danielskatz sorry for the delay.  We now have a DOI:  10.5281/zenodo.3468822:

 <a href="https://zenodo.org/badge/latestdoi/178911062"><img src="https://zenodo.org/badge/178911062.svg" alt="DOI"></a>

The lates version number is Enzo v2.6.1.

We are verifying the paper text and references right now.  The one issue I can see with the paper is the overlapping text in the bottom-left corner of the first page, where the 'LICENSE' block overlaps the footer:

![JOSS_paper_issue](https://user-images.githubusercontent.com/7969676/66050071-81abfd00-e4fa-11e9-87ed-3fad5d01ef1f.jpeg)

I anticipate that I will get back to you by no later than tomorrow finalizing the paper text and references.

**Comment by arfon** [comment]
> We are verifying the paper text and references right now. The one issue I can see with the paper is the overlapping text in the bottom-left corner of the first page, where the 'LICENSE' block overlaps the footer:

@bwoshea @danielskatz - this is an issue with our LaTeX template not handling long author lists very well. @danielskatz - feel free to accept this paper with Whedon here but I'll need to manually update the PDF afterwards to fix the layout issues.

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3469922 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3469922" target="_blank">10.5281/zenodo.3469922</a> is the archive.

**Comment by danielskatz** [comment]
@whedon set v2.6.1 as version

**Comment by whedon** [comment]
OK. v2.6.1 is the version.

**Comment by bwoshea** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01636/joss.01636/10.21105.joss.01636.pdf)

**Comment by bwoshea** [comment]
@danielskatz We've proofread the paper and pushed a small change.  The revised PDF looks good to me.  I think we're good to go!

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1088/0067-0049/211/2/19 is OK
- 10.1038/s41586-019-0873-4 is OK
- 10.1093/mnras/stv1509 is OK
- 10.1088/2041-8205/807/1/L12 is OK
- 10.3847/1538-4357/ab0654 is OK
- 10.3847/1538-4357/aa6fb1 is OK
- 10.1093/mnras/stv2641 is OK
- 10.3847/1538-4357/aa88c1 is OK
- 10.1103/PhysRevE.95.033206 is OK
- 10.1103/PhysRevLett.121.021104 is OK
- 10.3847/2041-8213/834/1/L1 is OK
- 10.1126/science.1173540 is OK
- 10.1093/mnras/sty2984 is OK
- 10.3847/1538-4357/aae30b is OK
- 10.1093/mnras/stw3291 is OK
- 10.1093/mnras/stt2121 is OK
- 10.1088/0004-637X/809/1/69 is OK
- 10.3847/1538-4357/aa799f is OK
- 10.1103/PhysRevD.99.063509 is OK
- 10.1051/0004-6361:200809967 is OK
- 10.1093/mnras/sty1289 is OK
- 10.3847/1538-4357/aa7263 is OK
- 10.3847/0004-637X/827/1/28 is OK
- 10.1093/mnras/stw1461 is OK
- 10.3847/1538-4357/aab7f2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1636 with the following error: 

 sh: 158: Syntax error: newline unexpected
Looks like we failed to compile the Crossref XML

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1088/0067-0049/211/2/19 is OK
- 10.1038/s41586-019-0873-4 is OK
- 10.1093/mnras/stv1509 is OK
- 10.1088/2041-8205/807/1/L12 is OK
- 10.3847/1538-4357/ab0654 is OK
- 10.3847/1538-4357/aa6fb1 is OK
- 10.1093/mnras/stv2641 is OK
- 10.3847/1538-4357/aa88c1 is OK
- 10.1103/PhysRevE.95.033206 is OK
- 10.1103/PhysRevLett.121.021104 is OK
- 10.3847/2041-8213/834/1/L1 is OK
- 10.1126/science.1173540 is OK
- 10.1093/mnras/sty2984 is OK
- 10.3847/1538-4357/aae30b is OK
- 10.1093/mnras/stw3291 is OK
- 10.1093/mnras/stt2121 is OK
- 10.1088/0004-637X/809/1/69 is OK
- 10.3847/1538-4357/aa799f is OK
- 10.1103/PhysRevD.99.063509 is OK
- 10.1051/0004-6361:200809967 is OK
- 10.1093/mnras/sty1289 is OK
- 10.3847/1538-4357/aa7263 is OK
- 10.3847/0004-637X/827/1/28 is OK
- 10.1093/mnras/stw1461 is OK
- 10.3847/1538-4357/aab7f2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1636 with the following error: 

 sh: 158: Syntax error: newline unexpected
Looks like we failed to compile the Crossref XML

**Comment by danielskatz** [comment]
👋 @arfon - can you debug this?

**Comment by danielskatz** [comment]
Actually, if you want to take over given that you have to generate the PDF manually for the spacing issue, please go ahead - this is fully ready to publish

**Comment by arfon** [comment]
@zingale, @rtfisher - many thanks for your reviews here and to @danielskatz for editing this submission ✨ 

@bwoshea - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01636/status.svg)](https://doi.org/10.21105/joss.01636)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01636">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01636/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01636/status.svg
   :target: https://doi.org/10.21105/joss.01636
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01636/status.svg)](https://doi.org/10.21105/joss.01636)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by danielskatz** [comment]
@arfon - can you generate a tweet for this?

**Comment by arfon** [comment]
Sure thing: https://twitter.com/JOSS_TheOJ/status/1179768071877214208?s=20
