### ISSUE TITLE
[PRE REVIEW]: BioVirusHost is a simple Python interface to query information from Virus-Host database.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1639]
**Submitting author:** @AliYoussef96 (<a href="http://orcid.org/0000-0002-5201-387X">Ali Youssef</a>)
**Repository:** <a href="https://github.com/AliYoussef96/BioVirusHost" target ="_blank">https://github.com/AliYoussef96/BioVirusHost</a>
**Version:** v1.0.1
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @AliYoussef96. **Currently, there isn't an JOSS editor assigned** to your paper.

@AliYoussef96 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01639/joss.01639/10.21105.joss.01639.pdf)

**Comment by arfon** [comment]
:wave: @brainstorm - the submitting author suggested you as the handling editor. Would you be able to take this one?

**Comment by danielskatz** [comment]
👋 @csoneson - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
👋  @AliYoussef96 - As we examine this submission in preparation for reviewing it, we've determined that it is not appropriate for JOSS.  As stated in https://joss.readthedocs.io/en/latest/submitting.html, 
> minor ‘utility’ packages, including ‘thin’ API clients, are not acceptable.
