### ISSUE TITLE
[REVIEW]: FRIEDA: Flexible Robust Intelligent Elastic Data Management Framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#164]
**Submitting author:** dghoshal-lbl (<a href="http://orcid.org/0000-0002-6819-6949">Devarshi Ghoshal</a>)
**Repository:** <a href="https://bitbucket.org/dghoshal/frieda" target ="_blank">https://bitbucket.org/dghoshal/frieda</a>
**Version:** v0.3.0
**Editor:** @acabunoc
**Reviewer:** @krother
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.290299" target="_blank">10.5281/zenodo.290299</a>

## Status

[![status](http://joss.theoj.org/papers/f68f92a740c6e42365025be9a9efed1b/status.svg)](http://joss.theoj.org/papers/f68f92a740c6e42365025be9a9efed1b)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f68f92a740c6e42365025be9a9efed1b"><img src="http://joss.theoj.org/papers/f68f92a740c6e42365025be9a9efed1b/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f68f92a740c6e42365025be9a9efed1b/status.svg)](http://joss.theoj.org/papers/f68f92a740c6e42365025be9a9efed1b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://bitbucket.org/dghoshal/frieda" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/dghoshal/frieda">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.3.0)?
- [x] **Authorship:** Has the submitting author (dghoshal-lbl) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @krother it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by krother** [comment]
I'm writing comments here, because I cannot create issues in the target repository (bitbucket).

**Comment by krother** [comment]
The LICENSE looks like a MIT License, but I am not sure. It would be great to reference the name of the license in the README, so that it is clear that it is an OSI-approved license.

**Comment by krother** [comment]
The Summary lists at least two kinds of categories (4 stages in the lifecycle, 2 planes and the data coordinator). What is the relationship between them? Are these orthogonal dimensions or contained in each other? A bit more specific info would help me understand what the things described mean practically for me as a user.

**Comment by krother** [comment]
What order of magnitude do you have in mind with "data management"? How much data is FRIEDA built for? Is FRIEDA useful if I have a human genome (4 GB) or if I have data from the CERN particle collider (100 petabytes)?

**Comment by krother** [comment]
In the Overview, the line breaks in some terminal sessions are distorted on my machine (Ubuntu/Firefox). Please check the sections: "Install the following dependencies", "euca - export", "$ ssh <NERSC username>" and "Amazon EC2"

**Comment by krother** [comment]
Installation: works fine on Python 2.7, great! Had to install a few packages manually. It would be great to have the 'requirements.txt' file commonly used with Python (create it with 'pip freeze > requirements.txt')

**Comment by krother** [comment]
Test: There are no instructions how to run the tests (it is not 'python setup.py test', and executing 'test/test_runner.py' just gives a list of expected arguments.)

**Comment by krother** [comment]
Documentation: It seems to refer to an older version of the software (refers to SVN repository instead of Github and to 'frieda_wrapper.py', a file that I am unable to find). I cannot assess how much of the documentation needs to be updated.

**Comment by dghoshal-lbl** [comment]
Thanks for the review comments. I have added the comments as issues to the repo. You can also add to the issues now.

**Comment by dghoshal-lbl** [comment]
Hi, I have incorporated the changes as suggested by the reviewer. Please find the answers under issues in the software repository (https://bitbucket.org/dghoshal/frieda/issues/1/joss-review-comments).

Please let me know if there are other concerns or comments.

**Comment by arfon** [comment]
@krother - would you be able to take another look at this submission again and let us know what you think?

**Comment by dghoshal-lbl** [comment]
So @krother has already provided additional reviews in the source repo. I am in the process of incorporating the changes and will let you know once done; mostly by Monday next week.

**Comment by dghoshal-lbl** [comment]
@krother - I have added the suggested changes. Please let me know if you need further modifications to the release.

**Comment by krother** [comment]
@arfon Everything fine, the authors took care of everything. I suggest to move forward with publishing the article.

**Comment by dghoshal-lbl** [comment]
@arfon Can you please let me know the DOI once the article is published?

**Comment by arfon** [comment]
@dghoshal-lbl - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by dghoshal-lbl** [comment]
@arfon Thanks. I archived the reviewed software in zenodo. The DOI is 10.5281/zenodo.290299

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.290299 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.290299" target="_blank">10.5281/zenodo.290299</a> is the archive.

**Comment by arfon** [comment]
@dghoshal-lbl - there are a couple of issues with your paper that I need you to fix before accepting here:

1. The metadata in the paper header isn't formatted correctly. See [this PR](https://bitbucket.org/arfons/frieda/pull-requests/1/updating-paper-metadata-to-be-compatible/diff#comment-None) for a fix
2. You don't appear to cite any of the references in `paper.bib` so they're not pulled into the compiled paper. I'm assuming this _isn't_ what you want 😄

**Comment by dghoshal-lbl** [comment]
@arfon : I have merged in your suggested changes and also updated the markdown version to include the references. Do I need to update the zenodo archive as well?

**Comment by arfon** [comment]
> @arfon : I have merged in your suggested changes and also updated the markdown version to include the references. Do I need to update the zenodo archive as well?

:+1: The archive is most important for the software so I'm happy to leave this _as is_ if you are.

**Comment by dghoshal-lbl** [comment]
@arfon : Sounds good. Let me know if everything else looks okay.

**Comment by arfon** [comment]
@krother many thanks for the review here and @acabunoc for editing ✨ 

@dghoshal-lbl - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00164 ⚡️ 🚀 💥

**Comment by danielskatz** [comment]
Note: It was discovered after the review and publication of this paper that the [software archive associated with this paper](
http://dx.doi.org/10.5281/zenodo.290299) contains a license that is not OSI-compliant, which should have been caught during the review and publication process, but unfortunately was not.

To address this oversight, the authors have changed the license for the software going forward to one that is OSI-compliant, as can be seen in the [active software repository](https://bitbucket.org/dghoshal/frieda).

**Comment by arfon** [comment]
@dghoshal-lbl - if possible, I'd like to update the archived version of the software associated with this submission so that it has the updated license. Have there been substantial updates to this package since it was reviewed (and accepted) here?

**Comment by arfon** [comment]
> @arfon None, except the license as far as I remember.

OK great. Would you be able to update the software archive for this repository and post the new DOI here?

**Comment by dghoshal-lbl** [comment]
@arfon You mean the archive on zenodo? I just checked and it seems I cannot remove/replace the old file from the archive. How was the archive created and how can it be updated?

**Comment by dghoshal-lbl** [comment]
@arfon Ok, I see I created that archive. So do you want me to upgrade it to versioned record and then update the archive?

**Comment by dghoshal-lbl** [comment]
@arfon The new DOI is: [10.5281/zenodo.1345764](https://zenodo.org/record/1345764#.W3R_mpNKjOQ)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1345764 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1345764" target="_blank">10.5281/zenodo.1345764</a> is the archive.

**Comment by arfon** [comment]
> @arfon The new DOI is: 10.5281/zenodo.1345764

Thanks @dghoshal-lbl.

**Comment by dghoshal-lbl** [comment]
@arfon As I click on the link above (https://doi.org/10.5281/zenodo.1345764), it shows up as a broken link. Will it take some time to show up?

**Comment by arfon** [comment]
>@arfon As I click on the link above (https://doi.org/10.5281/zenodo.1345764), it shows up as a broken link. Will it take some time to show up?

I think it can take a few hours before the Zenodo DOIs are registered with Datacite.
