### ISSUE TITLE
[PRE REVIEW]: pySRURGS - a python package for symbolic regression by uniform random global search

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1640]
**Submitting author:** @pySRURGS (<a href="http://orcid.org/0000-0002-3050-8943">Sohrab Towfighi</a>)
**Repository:** <a href="https://github.com/pySRURGS/pySRURGS" target ="_blank">https://github.com/pySRURGS/pySRURGS</a>
**Version:** 0.1
**Editor:** @mbobra
**Reviewers:** @henrik227, @SirSharpest

**Author instructions**

Thanks for submitting your paper to JOSS @pySRURGS. **Currently, there isn't an JOSS editor assigned** to your paper.

@pySRURGS if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @mbobra - would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01640/joss.01640/10.21105.joss.01640.pdf)

**Comment by pySRURGS** [comment]
Can also consider @hausen, @krother, @benjamin-lee, @stulacy, @r-barnes, @jmadera

**Comment by pySRURGS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01640/joss.01640/10.21105.joss.01640.pdf)

**Comment by stulacy** [comment]
Sorry, I don't have any time to review this at the moment.

**Comment by danielskatz** [comment]
👋 @mbobra - would you be willing to edit this submission for JOSS?

**Comment by mbobra** [comment]
@danielskatz Yes, please assign me!

**Comment by danielskatz** [comment]
You can assign yourself :)

**Comment by danielskatz** [comment]
@whedon assign @mbobra as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by mbobra** [comment]
@whedon assign @henrik227 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @henrik227

**Comment by mbobra** [comment]
@whedon add @SirSharpest as reviewer

**Comment by whedon** [comment]
OK, @SirSharpest is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1675. Feel free to close this issue now!
