### ISSUE TITLE
[PRE REVIEW]: thurstonianIRT: Thurstonian IRT Models in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1641]
**Submitting author:** @paul-buerkner (<a href="http://orcid.org/0000-0001-5765-8995">Paul-Christian Bürkner</a>)
**Repository:** <a href="https://github.com/paul-buerkner/thurstonianIRT" target ="_blank">https://github.com/paul-buerkner/thurstonianIRT</a>
**Version:** 0.9.0
**Editor:** @cMadan
**Reviewers:** @tomfaulkenberry, @russellpierce

**Author instructions**

Thanks for submitting your paper to JOSS @paul-buerkner. **Currently, there isn't an JOSS editor assigned** to your paper.

@paul-buerkner if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01641/joss.01641/10.21105.joss.01641.pdf)

**Comment by danielskatz** [comment]
@paul-buerkner - while I find an editor, I've also suggested a number of text changes in https://github.com/paul-buerkner/thurstonianIRT/pull/2 - if you merge this, please regenerate the pdf by entering ```@whedon generate pdf``` as a new comment in this thread.

**Comment by danielskatz** [comment]
👋 @trallard - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
👋 @brainstorm - would you be willing to edit this submission?

**Comment by paul-buerkner** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01641/joss.01641/10.21105.joss.01641.pdf)

**Comment by paul-buerkner** [comment]
@bgoodri may be able to review this submission as he is responsible for the rstan interface to Stan on which thurstonianIRT (partially) relies on.

**Comment by danielskatz** [comment]
Thanks - we will need to find at least 2 reviewers, so more suggestions are also welcome.

**Comment by paul-buerkner** [comment]
I will think of some more and come back to you.

**Comment by paul-buerkner** [comment]
@yrosseel may be able to review this submission as he is responsible for the lavaan package on which thurstonianIRT (partially) relies on.

**Comment by danielskatz** [comment]
👋 @cMadan - would you be willing to edit this submission?

**Comment by cMadan** [comment]
@danielskatz, sure, I can edit this one

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@TomDonoghue @DominiqueMakowski @russellpierce @tomfaulkenberry, would you be interested and available to review this submission?

**Comment by tomfaulkenberry** [comment]
sure...I'll be happy to do a review!

**Comment by cMadan** [comment]
@tomfaulkenberry, great! I'll start the review after finding a second reviewer.

**Comment by cMadan** [comment]
@whedon add @tomfaulkenberry as reviewer

**Comment by whedon** [comment]
OK, @tomfaulkenberry is now a reviewer

**Comment by TomDonoghue** [comment]
I would if I could, but I don't think I'm right for this one - I only know minimal R, and I'm not particularly familiar with the stats they implement. I'm going to have to pass on this one - I'm sure someone else could do a much better job!

**Comment by cMadan** [comment]
@TomDonoghue, no problem, thanks for considering!

**Comment by DominiqueMakowski** [comment]
Same for me, IRT is not really within my comfort zone... will have to pass! Authors of IRT-related packages might also be interested (e.g. [1](https://github.com/xluo11/xxIRT), [2](https://github.com/philchalmers/mirt), [3](https://github.com/RobertMyles/IRT), [4](https://github.com/tminka/ItemResponse)) ☺️

**Comment by russellpierce** [comment]
Same as Dominique. If you're in a pinch I'd be glad to, but outside of my specialization.

**Comment by cMadan** [comment]
@DominiqueMakowski, no problem, thanks!

@russellpierce, thanks--I'm going to assign you as a reviewer here, as I think I'll have trouble finding someone who's a better fit.

**Comment by cMadan** [comment]
@whedon add @russellpierce as reviewer

**Comment by whedon** [comment]
OK, @russellpierce is now a reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1662. Feel free to close this issue now!
