### ISSUE TITLE
[REVIEW]: PressureDrop.jl: Pressure traverses for oil & gas wells

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1642]
**Submitting author:** @jnoynaert (<a href="http://orcid.org/0000-0002-2986-0376">Jared Noynaert</a>)
**Repository:** <a href="https://github.com/jnoynaert/PressureDrop.jl" target ="_blank">https://github.com/jnoynaert/PressureDrop.jl</a>
**Version:** v1.0.1
**Editor:** @oliviaguest
**Reviewer:** @wkearn, @mancellin
**Archive:** <a href="https://doi.org/10.5281/zenodo.3529746" target="_blank">10.5281/zenodo.3529746</a>

## Status

[![status](https://joss.theoj.org/papers/06b3959e7319a94468e572edac33e0f4/status.svg)](https://joss.theoj.org/papers/06b3959e7319a94468e572edac33e0f4)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/06b3959e7319a94468e572edac33e0f4"><img src="https://joss.theoj.org/papers/06b3959e7319a94468e572edac33e0f4/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/06b3959e7319a94468e572edac33e0f4/status.svg)](https://joss.theoj.org/papers/06b3959e7319a94468e572edac33e0f4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jnoynaert/PressureDrop.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@wkearn & @mancellin, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @oliviaguest know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jnoynaert/PressureDrop.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.1)?
- [x] **Authorship:** Has the submitting author (@jnoynaert) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jnoynaert/PressureDrop.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.1)?
- [x] **Authorship:** Has the submitting author (@jnoynaert) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @wkearn, @mancellin it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01642/joss.01642/10.21105.joss.01642.pdf)

**Comment by oliviaguest** [comment]
👋@wkearn, @mancellin — This is where the action happens. You both have a review checklist to work your way through. Feel free to post questions here and open review issues in [the submission repository](https://github.com/openjournals/joss-reviews/issues/1633): https://github.com/openjournals/joss-reviews/issues/1633

**Comment by labarba** [comment]
Hi everybody! If you open a new issue in the [submission repository](https://github.com/jnoynaert/PressureDrop.jl), it's nice if you link to this very issue thread here, so we get a cross-link from GitHub.

**Comment by oliviaguest** [comment]
[ @labarba thanks for all the help so far ]

**Comment by jnoynaert** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01642/joss.01642/10.21105.joss.01642.pdf)

**Comment by jnoynaert** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01642/joss.01642/10.21105.joss.01642.pdf)

**Comment by mancellin** [comment]
PressureDrop.jl is a specialized tool to model the pressure profile in oil and gas wells.
The code can be installed and tested easily using Julia package manager. It is well documented and the code behaved as documented when I tried it.

Some comments and suggestions have been discussed there: https://github.com/jnoynaert/PressureDrop.jl/issues/3.

Overall, I can recommend the paper for publication.

**Comment by oliviaguest** [comment]
@mancellin thank you so much!

@wkearn could you give us a status update for your review?

**Comment by wkearn** [comment]
@oliviaguest Sorry for the delay, I plan to finish my review this afternoon.

**Comment by oliviaguest** [comment]
@wkearn Fantastic and thank you. 😊

**Comment by wkearn** [comment]
Sorry, again, for taking so long with my review.

This package looks great! It is definitely designed with a specialized audience in mind, but the code is very clearly documented, and someone with experience using these kinds of models will, I think, have no problem running the models and analyzing the output. 

I have a few minor suggestions that I will add to jnoynaert/PressureDrop.jl/issues/3 but otherwise I am happy to recommend this paper for publication.

**Comment by oliviaguest** [comment]
@labarba what is the next step, please? 😊 Do we wait for the suggestions (see comment just above mine) to be discussed because doing anything else at the moment?

**Comment by labarba** [comment]
@wkearn You said "otherwise" you're happy to recommend publication. Thus, we wait for you to confirm that your minor suggestion is addressed, and you are satisfied.

**Comment by oliviaguest** [comment]
@wkearn just a quick reminder to report back if/when you can — thanks. 😄

**Comment by jnoynaert** [comment]
Sorry, I haven't had a chance to get back and make those documentation changes yet. I should have some spare time this week to finish them.

**Comment by oliviaguest** [comment]
@jnoynaert any updates? :+1:

**Comment by jnoynaert** [comment]
@oliviaguest finally pushed this and tagged Will in the [original issue](https://github.com/jnoynaert/PressureDrop.jl/issues/3)

**Comment by danielskatz** [comment]
👋 @jnoynaert & @oliviaguest - what's the status of this now?

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01642/joss.01642/10.21105.joss.01642.pdf)

**Comment by oliviaguest** [comment]
@jnoynaert is it looking good?

**Comment by wkearn** [comment]
@oliviaguest Sorry for the delay on this, but @jnoynaert's updates look really good, and I can fully recommend publication.

**Comment by jnoynaert** [comment]
@oliviaguest I just looked at the last article proof and it looks good to me. Thanks for your patience on this one!

**Comment by oliviaguest** [comment]
Great! 😄

@jnoynaert can you create an archive for the code (on Zenodo, figshare, or other) and post the archive DOI here, please?

**Comment by jnoynaert** [comment]
@oliviaguest https://zenodo.org/record/3529593

**Comment by oliviaguest** [comment]
@whedon set 10.5281/zenodo.3529593 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3529593" target="_blank">10.5281/zenodo.3529593</a> is the archive.

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01642/joss.01642/10.21105.joss.01642.pdf)

**Comment by oliviaguest** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1115/1.3227845 may be missing for title: Predicting temperatures in flowing oil wells

INVALID DOIs

- 10.5281/zenodo.3337394 is INVALID
```

**Comment by oliviaguest** [comment]
@jnoynaert does this all look good?

**Comment by jnoynaert** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by jnoynaert** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1115/1.3227845 may be missing for title: Predicting temperatures in flowing oil wells

INVALID DOIs

- 10.5281/zenodo.3337394 is INVALID
```

**Comment by jnoynaert** [comment]
@whedon set 10.5281/zenodo.3529746 as archive

**Comment by whedon** [comment]
I'm sorry @jnoynaert, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by jnoynaert** [comment]
@oliviaguest I noticed a few DOIs needed fixing, but the check references command for whedon is referencing an older version of the paper than what's on the master branch right now. 

What do we need to do to sync up to the latest version for the reference checks? I'm wondering if it's stuck on the release archived on Zenodo

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01642/joss.01642/10.21105.joss.01642.pdf)

**Comment by oliviaguest** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1115/1.3227845 is OK
- 10.5281/zenodo.593105 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by oliviaguest** [comment]
@whedon accept

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1115/1.3227845 is OK
- 10.5281/zenodo.593105 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1092

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1092, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by oliviaguest** [comment]
@jnoynaert I think it's fine now — I think you needed to recompile before checking. Does it look good to you?

**Comment by jnoynaert** [comment]
@oliviaguest looks great, thank you!

**Comment by oliviaguest** [comment]
@labarba where do I check who can run: `@whedon accept deposit=true` for us?

**Comment by labarba** [comment]
Ping eics for that

**Comment by oliviaguest** [comment]
Ah, yes! Thanks! @openjournals/joss-eics :wave:

**Comment by kyleniemeyer** [comment]
Hi @jnoynaert, just a few things before I finalize acceptance:

1. In the newest Zenodo record (10.5281/zenodo.3529746, I believe), can you fix the title to match that of the paper?

2. One of our [paper requirements](https://openjournals.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) is 
> A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.

Can you edit the introduction to make it a bit more accessible to a more general audience?

3. Also, a number of the older references are missing information:
- Payne:1979 reference: missing `doi={10.2118/6874-PA}`, `volume=31`, `number=9`
- Ramey:1962 reference: missing `doi={10.2118/96-PA}`, `volume=14`, `number=4`
- Griffith:1961 reference: missing `doi={10.1115/1.3682268}, `volume=83`, `number=3`, `pages={307--318}`
- Beggs:1973 reference: missing `doi={10.2118/4007-PA}`, `volume=25`, `number=5`

**Comment by jnoynaert** [comment]
@whedon generate pdf

**Comment by jnoynaert** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by jnoynaert** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1642 with the following error: 

 Error reading bibliography ./paper.bib (line 18, column 3):
unexpected "d"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by jnoynaert** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01642/joss.01642/10.21105.joss.01642.pdf)

**Comment by jnoynaert** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1115/1.3682268 is OK
- 10.2118/4007-PA is OK
- 10.2118/6874-PA is OK
- 10.2118/96-PA is OK
- 10.1115/1.3227845 is OK
- 10.5281/zenodo.593105 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.3529746 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3529746" target="_blank">10.5281/zenodo.3529746</a> is the archive.

**Comment by jnoynaert** [comment]
@kyleniemeyer 
- updated title @ [doi.org/10.5281/zenodo.3529746](url))
- added references and verified the last DOI-less citation does not have one available (at least a reasonably discoverable one, at any rate)
- added two introductory paragraphs to clarify a bit for people not working in that field

**Comment by kyleniemeyer** [comment]
@jnoynaert ok, looks good! The introduction is much better.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1115/1.3682268 is OK
- 10.2118/4007-PA is OK
- 10.2118/6874-PA is OK
- 10.2118/96-PA is OK
- 10.1115/1.3227845 is OK
- 10.5281/zenodo.593105 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1095

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1095, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1192878385145364480) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1096
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01642](https://doi.org/10.21105/joss.01642)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @jnoynaert on your article's publication in JOSS! 

Many thanks to @wkearn and @mancellin for reviewing, and @oliviaguest for editing this submission.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01642/status.svg)](https://doi.org/10.21105/joss.01642)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01642">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01642/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01642/status.svg
   :target: https://doi.org/10.21105/joss.01642
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01642/status.svg)](https://doi.org/10.21105/joss.01642)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
