### ISSUE TITLE
[REVIEW]: SMBLtoODEpy: A software program for converting SBML models into ODE models in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1643]
**Submitting author:** @ashleefv (<a href="http://orcid.org/0000-0001-9059-5703">Ashlee N. Ford Versypt</a>)
**Repository:** <a href="https://github.com/SMRuggiero/sbmltoodepy" target ="_blank">https://github.com/SMRuggiero/sbmltoodepy</a>
**Version:** v1.0.3
**Editor:** @mgymrek
**Reviewer:** @SirSharpest, @marouenbg
**Archive:** <a href="https://doi.org/10.5281/zenodo.3441677" target="_blank">10.5281/zenodo.3441677</a>

## Status

[![status](https://joss.theoj.org/papers/7180dfddc52a8b3bbf13b58eaa0e6d45/status.svg)](https://joss.theoj.org/papers/7180dfddc52a8b3bbf13b58eaa0e6d45)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7180dfddc52a8b3bbf13b58eaa0e6d45"><img src="https://joss.theoj.org/papers/7180dfddc52a8b3bbf13b58eaa0e6d45/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7180dfddc52a8b3bbf13b58eaa0e6d45/status.svg)](https://joss.theoj.org/papers/7180dfddc52a8b3bbf13b58eaa0e6d45)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/SMRuggiero/sbmltoodepy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@SirSharpest & @marouenbg, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mgymrek know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SMRuggiero/sbmltoodepy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.3
- [x] **Authorship:** Has the submitting author (@ashleefv) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SMRuggiero/sbmltoodepy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.3
- [x] **Authorship:** Has the submitting author (@ashleefv) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @SirSharpest, @marouenbg it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01643/joss.01643/10.21105.joss.01643.pdf)

**Comment by SirSharpest** [comment]
@ashleefv I have made my comments as a new issue on the relevant github page: [https://github.com/SMRuggiero/sbmltoodepy/issues/1](https://github.com/SMRuggiero/sbmltoodepy/issues/1) 

Most are minor, and possibly non-issues. Though, I feel that the clarifications I mentioned for the manuscript would be important to readers. As would being explicit in which python versions are supported. Finally, I feel strongly about unit-testing being done to software engineering standards, but I understand that this has at least been addressed using their own method.

@mgymrek if there is anything else, prior to author response, please let me know and I'll promptly proceed with.

**Comment by mgymrek** [comment]
Thanks @SirSharpest and @marouenbg. These comments look reasonable. 
@ashleefv please review the comments from the reviewers and post responses to their comments here.

**Comment by ashleefv** [comment]
Alright. We've been posting responses on the github repository issues. We'll also consolidate them and post here when they are completed (should be later this week).

Ashlee N. Ford Versypt, Ph.D.
Assistant Professor, School of Chemical Engineering, Oklahoma State University
Member, Harold Hamm Diabetes Center, University of Oklahoma Health Sciences Center
420 Engineering North, OSU, Stillwater, OK 74078
Ph: 405-744-5280
ashleefv@okstate.edu<mailto:ashleefv@okstate.edu>
Ford Versypt Lab Website<https://sites.google.com/site/ashleefordversypt/>




On Sun, Sep 1, 2019 at 11:54 AM Melissa Gymrek <notifications@github.com<mailto:notifications@github.com>> wrote:
**External Email - Please verify sender email address before responding.**
**External Email - Please verify sender email address before responding.**

Thanks @SirSharpest<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSirSharpest&data=02%7C01%7Cashleefv%40okstate.edu%7Cc7fd0a4b6fb84a59701908d72efd0de6%7C2a69c91de8494e34a230cdf8b27e1964%7C0%7C0%7C637029536707290708&sdata=mcuLcFShtmQe9IqbVrfs3saXZ5xxpb0OZVExFAfQ%2Bv4%3D&reserved=0> and @marouenbg<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarouenbg&data=02%7C01%7Cashleefv%40okstate.edu%7Cc7fd0a4b6fb84a59701908d72efd0de6%7C2a69c91de8494e34a230cdf8b27e1964%7C0%7C0%7C637029536707300702&sdata=AyYQFRGIJ4oLeGFKnuijIvRxdXvertrCNIpalEHLyXk%3D&reserved=0>. These comments look reasonable.
@ashleefv<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fashleefv&data=02%7C01%7Cashleefv%40okstate.edu%7Cc7fd0a4b6fb84a59701908d72efd0de6%7C2a69c91de8494e34a230cdf8b27e1964%7C0%7C0%7C637029536707300702&sdata=XwbE8raSs%2B0iDcPygTQohMyMHQCU%2BPZEMJxKnZbI5%2Fk%3D&reserved=0> please review the comments from the reviewers and post responses to their comments here.

**Comment by ashleefv** [comment]
# Responses to Reviewer 1's comments (Issue 1):

### General Comments
We now specify that the supported versions of python are 3.5, 3.6, and 3.7.

Added comment to README.md about installing from source.

### Testing

PyTest could be a good fit for our project, but we expect to include if we have a major update in the future.

### Software checked on:
We now specify that the supported versions of python are 3.5, 3.6, and 3.7.  

### Software style
Removed all of the "import *" statements. While the updated code on this github repo has been updated, we plan on updating the package on PyPI once all reviewer comments have been addressed.

### Running the provided Tutorial.md
We addressed the comments by 

- clarifying the case when cloning the repo and pip install make sense together (use on google colab)
- fixing pip install command
- hosting a copy of SBMLtoODEpy.ipynb in the repo  
###  Community guidelines

We do not see the scope of the project for others' to make pull requests or suggest features. 
### Paper Clarifications
In our paper, we compare our work to two other pieces of software.

COPASI- The comparison was intended simply to validate the results of the models generated by SBMLtoODEpy. COPASI uses ODEPACK for its Time Course calculations, which is the same library that scipy's odeint function uses. If the calculations agree, then that suggests SBMLtoODEpy has generated the correct equations. Furthermore, the targeted niche for SBMLtoODEpy is not the same as COPASI.

Systems Biology Format Converter (SBFC)- SBFC is a better software to compare SBMLtoODEpy to. SBFC converts SBML models into various programming and modeling languages, but notably excludes Python. This gap SBFC's functionality is specifically the target niche of SBMLtoODEpy. Additionally, SBMLtoODEpy is designed to generate code that can be incorporated into other python projects. The Octave/MATLAB scripts generated by SBFC implement the model that neither accept arguments nor return any values. SBMLtoODEpy generates code that implements the model as a class with most methods and members intended to be accessible to other code.

The paper has been updated to better convey the scope and intent of the comparisons.

**Comment by ashleefv** [comment]
# Responses to Reviewer 2's comments 
## Comment 1 (Issue 2) 
Since we expect users to take and modify or use the code generated by SBMLtoODEpy in ways we can't predict, the burden of applying SED-ML or KiSAO will have to be on the user. Additionally most SBML components are stored as entries in dictionaries that are members of the class implementing the model. Currently rules and initial assignments are not implemented this way and annotations stored in the SBML model are not retained. We plan to address these in a future update.

We updated the paper to expand on the comparison to COPASI. My comment to reviewer #1 addresses the comparison to COPASI and Systems Biology Format Converter in more depth.

## Comment 2 (Issue 3) 

We looked into the suggestion and are currently not interested in using Travis-CI. Travis-CI does not play well with PyPI accounts with non-alphanumeric characters in its password. Additionally, any updates to SBMLtoODEpy will change the code generated by it and may require different interfacing with user code. Because of this, we want only want a new version of our code pushed when we are absolutely certain its ready for public use. Building and pushing a new version of our code to PyPI is already a simple process with setuptools and twine.

We did set up a code ocean capsule and tested our code on Ubuntu 16.04 and 18.04. We're not planning on publishing the capsule as we do not believe it to be a good fit to publish this project on code ocean. However, we are glad the reviewer provided this suggestion because it may be a good fit for some of our other projects that involve simulation experiments.

## Comment 3 (Issue 4) 
We have added in both the readme and tutorial to our documentation page. While we see the value in a troubleshooting section of the documentation, we think we need user feedback before creating it. We plan on adding a changelog section to the documentation as part of finishing addressing reviewer feedback, if future edits are made.

**Comment by ashleefv** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01643/joss.01643/10.21105.joss.01643.pdf)

**Comment by ashleefv** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01643/joss.01643/10.21105.joss.01643.pdf)

**Comment by ashleefv** [comment]
Approved the new article proof. We have concluded our responses to the reviewers' comments.

**Comment by mgymrek** [comment]
Thanks @ashleefv for addressing these comments.
 @SirSharpest, @marouenbg, could you review these edits and update the checklists above accordingly?

Also, I noticed you mentioned you mentioned for community guidelines that you do not envision contributions from others to the project. However this is an important aspect of open source projects. Even if you do not envision new features, it's possible a user could find a bug and want to contribute a fix for example. To address this point you could simply add a blurb to the readme suggesting users to contact you or submit a pull request if they would like to contribute a change.

**Comment by ashleefv** [comment]
That's a good suggestion. I've edited the readme accordingly.

Ashlee N. Ford Versypt, Ph.D.
Assistant Professor, School of Chemical Engineering, Oklahoma State University
Member, Harold Hamm Diabetes Center, University of Oklahoma Health Sciences Center
420 Engineering North, OSU, Stillwater, OK 74078
Ph: 405-744-5280
ashleefv@okstate.edu<mailto:ashleefv@okstate.edu>
Ford Versypt Lab Website<https://sites.google.com/site/ashleefordversypt/>




On Sun, Sep 8, 2019 at 4:30 PM Melissa Gymrek <notifications@github.com<mailto:notifications@github.com>> wrote:
**External Email - Please verify sender email address before responding.**
**External Email - Please verify sender email address before responding.**

Thanks @ashleefv<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fashleefv&data=02%7C01%7Cashleefv%40okstate.edu%7Cbc27e1764ae0415dd45808d734a3b08e%7C2a69c91de8494e34a230cdf8b27e1964%7C0%7C0%7C637035749976906292&sdata=CfgqLiIMgCsH%2Bhha9SYWtvmk7yBsrqitMt5Ae1%2Fr%2BRo%3D&reserved=0> for addressing these comments.
@SirSharpest<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSirSharpest&data=02%7C01%7Cashleefv%40okstate.edu%7Cbc27e1764ae0415dd45808d734a3b08e%7C2a69c91de8494e34a230cdf8b27e1964%7C0%7C0%7C637035749976916285&sdata=Wzy25mE3zPIRxyTw1Ni7WnRhG6c44K85YVrcqLq%2By2Q%3D&reserved=0>, @marouenbg<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarouenbg&data=02%7C01%7Cashleefv%40okstate.edu%7Cbc27e1764ae0415dd45808d734a3b08e%7C2a69c91de8494e34a230cdf8b27e1964%7C0%7C0%7C637035749976916285&sdata=l%2FiMTA4VSwQYRnKk2q2n71FcGaa1Cy8fGhyv8ES2Eg4%3D&reserved=0>, could you review these edits and update the checklists above accordingly?

Also, I noticed you mentioned you mentioned for community guidelines that you do not envision contributions from others to the project. However this is an important aspect of open source projects. Even if you do not envision new features, it's possible a user could find a bug and want to contribute a fix for example. To address this point you could simply add a blurb to the readme suggesting users to contact you or submit a pull request if they would like to contribute a change.

**Comment by marouenbg** [comment]
I just checked all the boxes on my side. The authors did address the comments either through new commits and/or provided reasonable explanations for sticking to their initial choices. Great job!

**Comment by mgymrek** [comment]
Perfect, thanks @marouenbg and @SirSharpest for the reviews!

**Comment by mgymrek** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01643/joss.01643/10.21105.joss.01643.pdf)

**Comment by ashleefv** [comment]
I approve of the proof.

Ashlee N. Ford Versypt, Ph.D.
Assistant Professor, School of Chemical Engineering, Oklahoma State University
Member, Harold Hamm Diabetes Center, University of Oklahoma Health Sciences Center
420 Engineering North, OSU, Stillwater, OK 74078
Ph: 405-744-5280
ashleefv@okstate.edu<mailto:ashleefv@okstate.edu>
Ford Versypt Lab Website<https://sites.google.com/site/ashleefordversypt/>




On Tue, Sep 10, 2019 at 10:44 AM whedon <notifications@github.com<mailto:notifications@github.com>> wrote:
**External Email - Please verify sender email address before responding.**
**External Email - Please verify sender email address before responding.**

👉 Check article proof 📄 👈 <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopenjournals%2Fjoss-papers%2Fblob%2Fjoss.01643%2Fjoss.01643%2F10.21105.joss.01643.pdf&data=02%7C01%7Cashleefv%40okstate.edu%7C1a9134394c574cfb828d08d73605c065%7C2a69c91de8494e34a230cdf8b27e1964%7C0%7C1%7C637037270637206273&sdata=5ctUPlU%2F%2FSx76D8t1ytYy6cuUjTBxLoH3mymu9lVKMs%3D&reserved=0>

**Comment by ashleefv** [comment]
@mgymrek What is the next step?

**Comment by mgymrek** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btg015 is OK
- 10.1093/nar/gku1181 is OK
- 10.1042/bst0311472 is OK
- 10.1093/nar/gkx1023 is OK
- 10.1093/bioinformatics/btn051 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/MCSE.2007.58 is OK
- 10.1186/s12859-016-1000-2 is OK
- 10.1038/msb.2009.19 is OK
- 10.1146/annurev.ph.34.030172.000305 is OK
- 10.1371/journal.pcbi.1003371 is OK
- 10.1111/iep.12062 is OK
- 10.1007/s11538-005-9022-3 is OK
- 10.1038/msb.2011.22 is OK
- 10.1093/bioinformatics/btl485 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mgymrek** [comment]
@ashleefv We are almost there, just a couple more steps. I have gone over the proof and have the following minor comments:

* "models that not easy" -> "models that are not easy"
* The Hindmarsh et al. reference I don't see a DOI in the proof

After fixing these, please make a Zenodo archive, ensuring the title + author list match that in the paper and that the version number is correct.

**Comment by mgymrek** [comment]
Hi @ashleefv sorry for the delayed response, yes that is fine. You can now proceed with making the Zenodo archive. Thanks!

**Comment by ashleefv** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01643/joss.01643/10.21105.joss.01643.pdf)

**Comment by ashleefv** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btg015 is OK
- 10.1093/nar/gku1181 is OK
- 10.1042/bst0311472 is OK
- 10.1093/nar/gkx1023 is OK
- 10.1093/bioinformatics/btn051 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/MCSE.2007.58 is OK
- 10.1186/s12859-016-1000-2 is OK
- 10.1038/msb.2009.19 is OK
- 10.1146/annurev.ph.34.030172.000305 is OK
- 10.1371/journal.pcbi.1003371 is OK
- 10.1111/iep.12062 is OK
- 10.1007/s11538-005-9022-3 is OK
- 10.1038/msb.2011.22 is OK
- 10.1093/bioinformatics/btl485 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by ashleefv** [comment]
@mgymrek We have updated the Hindmarsh url, fixed the noted typo, finalized the revised pypi release, and created a new zenodo doi for this updated release: https://zenodo.org/record/3441677#.XYLMoyhKjZs

**Comment by mgymrek** [comment]
@whedon set v1.0.3 as version

**Comment by whedon** [comment]
OK. v1.0.3 is the version.

**Comment by mgymrek** [comment]
@whedon set 10.5281/zenodo.3441677 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3441677" target="_blank">10.5281/zenodo.3441677</a> is the archive.

**Comment by mgymrek** [comment]
@openjournals/joss-eics We are ready to accept this submission!

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/974

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/974, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1175186394127503362) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/975
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01643](https://doi.org/10.21105/joss.01643)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Woohoo!! Congrats @ashleefv on your publication and thank you to reviewers @SirSharpest and @marouenbg!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01643/status.svg)](https://doi.org/10.21105/joss.01643)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01643">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01643/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01643/status.svg
   :target: https://doi.org/10.21105/joss.01643
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01643/status.svg)](https://doi.org/10.21105/joss.01643)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by ashleefv** [comment]
I recently got the feedback that our acronym in the first word of the title reversed the B & M. It should be SBMLtoODEpy. Additionally this accidental reversal of the letters appeared one other time int he document. Can this be corrected?

**Comment by ashleefv** [comment]
@mgymrek We aren't sure if our title issue and internal typo can be updated. We accidentally switched the letters B&M in the title of our paper and in one other place (I'm fine if that internal typo is not corrected, but the title would be best to fix.). I never caught the error because it blended together for me visually. Someone just commented on our github repository pointing out the issue.

**Comment by arfon** [comment]
@ashleefv - please make the necessary changes to your `paper.md` file and let me know when you've done this. I can then update the paper.

**Comment by ashleefv** [comment]
@arfon I have updated paper.md in the repository: https://github.com/SMRuggiero/sbmltoodepy

**Comment by arfon** [comment]
@ashleefv - this was fixed in https://github.com/openjournals/joss-papers/commit/5f08ae368b4f81d8c7783bd4be821829cb0a3335 although the paper might take a few hours to show as updated on the JOSS website as there's caching in place.
