### ISSUE TITLE
[PRE REVIEW]: bio-go: A flexible tools Bioinformatics library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1645]
**Submitting author:** @RHagenson (<a href="http://orcid.org/0000-0001-9750-1925">Ryan Hagenson</a>)
**Repository:** <a href="https://github.com/bio-ext/bio-go" target ="_blank">https://github.com/bio-ext/bio-go</a>
**Version:** v1.0.0
**Editor:** @lpantano
**Reviewers:** @kortschak, @will-rowe

**Author instructions**

Thanks for submitting your paper to JOSS @RHagenson. **Currently, there isn't an JOSS editor assigned** to your paper.

@RHagenson if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01645/joss.01645/10.21105.joss.01645.pdf)

**Comment by danielskatz** [comment]
👋 @RHagenson  - please add to your paper an explantation of what research problems your software can help with (which is another way of saying who will cite your software).  Perhaps add a little about how they would use your software.  When you have done so, please enter ```@whedon generate pdf``` as a new comment here to regenerate the pdf.

**Comment by RHagenson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01645/joss.01645/10.21105.joss.01645.pdf)

**Comment by danielskatz** [comment]
👋 @lpantano - would you be willing to edit this?

**Comment by lpantano** [comment]
@whedon set @lpantano as editor

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
Hi @RHagenson, thanks for submitting to JOSS. I look around but I couldn't find any documentation of the tool. One of the mandatory requirement is to have full documentation with examples. If it is already done, can you put the link in the readme of the repo?

Cheers

**Comment by RHagenson** [comment]
@lpantano Documentation can be built through `godoc`, for online access to documentation visit: https://godoc.org/github.com/bio-ext/bio-go/bio

I have been using property tests to serve as both tests and examples. These can be run and seen from the repo root through `go test` via `go test -v ./...` (I have also just now added the `-v` flag to produce this output in TravisCI). In my opinion, code that is not automatically validated with each push to `master` is less useful than strict properties that can be expected from the library. The intent of the property tests (perhaps not as well as I had hoped) is to show potential users what properties they can expect from an implementation. All this said, I agree that explicit examples have value so I will add an `examples/` directory alongside `bio/` at the root. The separate directory would allow running everything all at once in CI and let potential users clearly see where examples are housed without all the property-testing framework around them.

I will add all the above directive information on viewing documentation and running tests to the README later today.

In your opinion, are there other additions I need to make?

**Comment by lpantano** [comment]
Thank you for the detailed explanation, I think that would help a lot to show potential users how they can use your tool, and then the goDoc can get into details. 

Thanks for making the changes.

**Comment by RHagenson** [comment]
@lpantano I added the documentation and testing sections to the README. However, due to my immediate schedule I will not be able to add `examples/` quite yet. I will tag you again in this thread when I have `examples/` added. If there are any other additions/changes I need to make, let me know.

**Comment by lpantano** [comment]
@adavidzh, would you be interested in reviewing this tool?

**Comment by adavidzh** [comment]
> @adavidzh, would you be interested in reviewing this tool?

Hi @lpantano. I'm afraid I'm tight for time these coming weeks and the topic is a little too far away from my comfort zone.

**Comment by RHagenson** [comment]
@lpantano Not done with the examples (they are being developed on `examples` branch), but I wanted to update you that I will be doing two types of examples: 
1. Individual documentation example, i.e. examples that will display in the documentation built with `godoc` that show usage of individual elements
2. Aggregate examples, i.e. examples that use multiple elements together

**Comment by lpantano** [comment]
@krother, do you think you would have time to review this new tool? Thanks

**Comment by lpantano** [comment]
@mskwark, would you be interested in reviewing this tool?

**Comment by peterjc** [comment]
I was asked (by email) to review, but declined:

Sadly I know nothing about Go, and the project's current state of documentation leaves too steep a learning curve for me or any other bioinformatician curious to try it.

It needs a quick start, I would think even a trivial example like loading a given DNA sequence (be it with IUPAC ambiguity codes or just A, C, G, T bases) from a FASTA file, translating it into an amino acid sequence, and then writing out this protein sequence as a new FASTA file would be useful. Looking at the module names I think this functionality would be covered already.

**Comment by RHagenson** [comment]
@peterjc Thank you for the advice on a helpful and explanatory aggregate example of usage reading in a given DNA FASTA, translating it to protein, and writing it out as a new FASTA. In your opinion, are there any other rough edges about the project in its current state that need smoothing?

**Comment by peterjc** [comment]
@RHagenson the beginner documentation was the main thing lacking - beyond that it was hard to say more, sorry.

**Comment by RHagenson** [comment]
@peterjc Thank you for the help you provided. I will add more documentation at the beginner level.

**Comment by kortschak** [comment]
Sure.

**Comment by will-rowe** [comment]
Happy to review this too if needed

**Comment by lpantano** [comment]
Thank you both to agree on reviewing this tool. I will wait until docs are updated to start the review.

**Comment by RHagenson** [comment]
@lpantano, I finished writing the beginner documentation (available at https://bio-ext.github.io/bio-go/) and the updated version number is [v1.1.3](https://github.com/bio-ext/bio-go/tree/v1.1.3).

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1741. Feel free to close this issue now!
