### ISSUE TITLE
[PRE REVIEW]: deepCR: Cosmic Ray Rejection with Deep Learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1647]
**Submitting author:** @kmzzhang (<a href="http://orcid.org/0000-0002-9870-5695">Keming Zhang</a>)
**Repository:** <a href="https://github.com/profjsb/deepCR" target ="_blank">https://github.com/profjsb/deepCR</a>
**Version:** 0.1.5
**Editor:** @terrytangyuan
**Reviewers:** @shreyasbapat, @DanielLenz

**Author instructions**

Thanks for submitting your paper to JOSS @kmzzhang. **Currently, there isn't an JOSS editor assigned** to your paper.

@kmzzhang if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1647 with the following error: 

 Could not find bibliography file: paper.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
@kmzzhang - There doesn't seem to be a paper.bib file in your repo

**Comment by kmzzhang** [comment]
Hello,

I have just included paper.bib in the repo.

Thanks,
Keming

On Aug 13, 2019, at 6:54 PM, Daniel S. Katz <notifications@github.com<mailto:notifications@github.com>> wrote:


@kmzzhang<https://github.com/kmzzhang> - There doesn't seem to be a paper.bib file in your repo

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01647/joss.01647/10.21105.joss.01647.pdf)

**Comment by danielskatz** [comment]
There's a misspelled `robust` near the end of the paper...  Please fix it, and then add a new comment here containing ```@whedon generate pdf``` to rebuild the paper

**Comment by danielskatz** [comment]
👋 @terrytangyuan - would you be willing to review this submission?

**Comment by terrytangyuan** [comment]
@whedon assign @terrytangyuan as editor

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by terrytangyuan** [comment]
Sure, @kmzzhang do you have a list of potentials reviewers in mind? If so, please mention them here.

**Comment by kmzzhang** [comment]
@terrytangyuan, may I suggest nilesh-patil, DanielLenz, shreyasbapat as potential reviewers? They have listed both deep learning and astronomy as their expertise. Additionally, I don’t see the figure in the generated paper proof. Is the figure format wrong? Thanks.

On Aug 14, 2019, at 5:39 AM, Yuan Tang <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure, @kmzzhang<https://github.com/kmzzhang> do you have a list of potentials reviewers in mind? If so, please mention them here.

**Comment by danielskatz** [comment]
I wonder if the path to the image is a problem?  @arfon - can you help with this?  (since we can't see the generate pdf log to see any error msgs)

**Comment by terrytangyuan** [comment]
Hi @nilesh-patil @DanielLenz @shreyasbapat Would you be interested in reviewing this submission?

**Comment by shreyasbapat** [comment]
> Hi @nilesh-patil @DanielLenz @shreyasbapat Would you be interested in reviewing this submission?

Yes sure! I can :)

**Comment by DanielLenz** [comment]
I'd be happy to review in general. However, the work has already been described and published in [Zhang & Bloom (2019, submitted to AAS)](https://arxiv.org/abs/1907.09500), and will undergo peer review there as well.

**Comment by arfon** [comment]
> I wonder if the path to the image is a problem? @arfon - can you help with this? (since we can't see the generate pdf log to see any error msgs)

@kmzzhang - can you update the URL of the image to: `https://raw.githubusercontent.com/profjsb/deepCR/master/imgs/postage-sm.jpg` rather than using the relative path?

> I'd be happy to review in general. However, the work has already been described and published in Zhang & Bloom (2019, submitted to AAS), and will undergo peer review there as well.

Also, can you confirm @kmzzhang that this is a joint submission with AAS?

**Comment by kmzzhang** [comment]
@whedon<https://github.com/whedon> generate pdf

On Aug 14, 2019, at 5:24 PM, Arfon Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


I wonder if the path to the image is a problem? @arfon<https://github.com/arfon> - can you help with this? (since we can't see the generate pdf log to see any error msgs)

@kmzzhang<https://github.com/kmzzhang> - can you update the URL of the image to: https://raw.githubusercontent.com/profjsb/deepCR/master/imgs/postage-sm.jpg rather than using the relative path?

I'd be happy to review in general. However, the work has already been described and published in Zhang & Bloom (2019, submitted to AAS), and will undergo peer review there as well.

Also, can you confirm @kmzzhang<https://github.com/kmzzhang> that this is a joint submission with AAS?

**Comment by danielskatz** [comment]
you probably need to do this on github - doing it by email doesn't quite work

**Comment by kmzzhang** [comment]
Yes, this is a joint submission with AAS.

On Aug 14, 2019, at 5:24 PM, Arfon Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


I wonder if the path to the image is a problem? @arfon<https://github.com/arfon> - can you help with this? (since we can't see the generate pdf log to see any error msgs)

@kmzzhang<https://github.com/kmzzhang> - can you update the URL of the image to: https://raw.githubusercontent.com/profjsb/deepCR/master/imgs/postage-sm.jpg rather than using the relative path?

I'd be happy to review in general. However, the work has already been described and published in Zhang & Bloom (2019, submitted to AAS), and will undergo peer review there as well.

Also, can you confirm @kmzzhang<https://github.com/kmzzhang> that this is a joint submission with AAS?

**Comment by arfon** [comment]
> Yes, this is a joint submission with AAS.

👍 thanks for confirming.

/ cc @crawfordsm

**Comment by terrytangyuan** [comment]
@kmzzhang Please use Github instead of email for responding in the future since the responses from email is very verbose. Thank you. 

@whedon assign @shreyasbapat as reviewer
@whedon add @DanielLenz as reviewer

**Comment by terrytangyuan** [comment]
@whedon assign @shreyasbapat as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @shreyasbapat

**Comment by terrytangyuan** [comment]
@whedon add @DanielLenz as reviewer

**Comment by whedon** [comment]
OK, @DanielLenz is now a reviewer

**Comment by terrytangyuan** [comment]
@whedon start review

**Comment by kmzzhang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01647/joss.01647/10.21105.joss.01647.pdf)

**Comment by terrytangyuan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1651. Feel free to close this issue now!

**Comment by terrytangyuan** [comment]
@shreyasbapat @DanielLenz Thank you! Look forward to your review in #1651!
