### ISSUE TITLE
[PRE REVIEW]: 3D reconstruction toolbox for behavior tracked with multiple cameras

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1648]
**Submitting author:** @SwathiSheshadri (<a href="http://orcid.org/0000-0003-2850-107X">Swathi Sheshadri</a>)
**Repository:** <a href="https://github.com/SwathiSheshadri/pose3d" target ="_blank">https://github.com/SwathiSheshadri/pose3d</a>
**Version:** v1.0.0
**Editor:** @cMadan
**Reviewers:** @danasolav, @sreschechtko

**Author instructions**

Thanks for submitting your paper to JOSS @SwathiSheshadri. **Currently, there isn't an JOSS editor assigned** to your paper.

@SwathiSheshadri if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1648 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate paper

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01648/joss.01648/10.21105.joss.01648.pdf)

**Comment by danielskatz** [comment]
👋 @SwathiSheshadri - as you can see in the PDF, there are a few problems with the paper, such as references without a space before them, and a missing References header for the reference section.  Please feel free to make changes in the .md file, then put a comment ```@whedon generate pdf``` in this issue to regenerate the pdf

**Comment by danielskatz** [comment]
👋 @cMadan - you were requested by the submitter for this - are you willing to edit it?

**Comment by SwathiSheshadri** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01648/joss.01648/10.21105.joss.01648.pdf)

**Comment by SwathiSheshadri** [comment]
👋 I suggest @sreschechtko and @brittonsauerbrei as potential reviewers for this work.

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@SwathiSheshadri, it looks like the project is mainly a GUI utility that wraps around DeepLabCut and first-party Matlab functions. Do you think this is a fair assessment?

**Comment by SwathiSheshadri** [comment]
@cMadan, thank you for taking time to edit our submission.
I agree with your assessment in that the focus of our submission with pose3d is to provide a user-friendly 3D reconstruction interface targeted mainly towards DeepLabCut (DLC) users. However, pose3d is not limited to DLC users and can be easily used with any other 2D tracking software as described in one of our demo examples.
I would also like to add that pose3d extends Matlab’s existing triangulation function designed for use with only 2 cameras to ‘n’ cameras and includes a description of the same in the Appendix.pdf document of our paper folder.

**Comment by cMadan** [comment]
@SwathiSheshadri, do you have any suggestions for potential reviewers?

**Comment by SwathiSheshadri** [comment]
@cMadan, I suggest @sreschechtko (Sasha Reschechtko) and @brittonsauerbrei (Britton Sauerbrei) as potential reviewers. These two researchers are actively interested in behavior tracking and would be well suited to review pose3d. 
Additionally, I suggest the following reviewers from the JOSS list based on their programming language preference and area of expertise : @Kevin-Mattheus-Moerman, @fernandoandreotti

**Comment by Kevin-Mattheus-Moerman** [comment]
I suggest @danasolav as a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@cMadan are you able to invite some more reviewers? I think @danasolav would be ideal but perhaps we can find some more. Thanks.

**Comment by danasolav** [comment]
I can review this submission. Is it ready for reviewing?

**Comment by Kevin-Mattheus-Moerman** [comment]
@danasolav @cMadan will likely find a few more reviewers before the formal review starts. If you like you can start evaluating the software but you can also wait until the review issue is opened. There you'll have tickboxes to guide you through the process.

**Comment by cMadan** [comment]
@danasolav, great, thank you! As @Kevin-Mattheus-Moerman said, we do still need another reviewer before we formally begin, but feel free to start trying to install/test the software if you have time.

**Comment by cMadan** [comment]
@whedon add @danasolav as reviewer

**Comment by whedon** [comment]
OK, @danasolav is now a reviewer

**Comment by cMadan** [comment]
@SwathiSheshadri, do you have any additional suggestions about who might be a suitable reviewer for your submission?

**Comment by SwathiSheshadri** [comment]
Thank you all for your responses and for helping advance our submission towards review. 
@cMadan, I make the following additional reviewer suggestions.
Additional JOSS reviewer suggestions:
@thomakra 
@cpontonn
In addition, I request you to reconsider my earlier suggested reviewers @sreschechtko (Sasha Reschechtko) and @brittonsauerbrei (Britton Sauerbrei) as they would be best equipped to test our submission out. Please let me know if I have to contact them and request them to register as reviewers at JOSS.

**Comment by cMadan** [comment]
@SwathiSheshadri, since you've tagged them in the pre-review issue here, they are automatically notified via Github.

@thomakra @cpontonn @sreschechtko @brittonsauerbrei, would you be available and interested in reviewing this submission?

**Comment by sreschechtko** [comment]
I am available and able to review this submission.

**Comment by thomakra** [comment]
I'm sorry, I'm not able to review it at this time.

-Thomas-

**Comment by cMadan** [comment]
@sreschechtko, great! I'll add you as a reviewer and start the review process.

@thomakra, no problem, thanks for letting me know.

**Comment by cMadan** [comment]
@whedon add @sreschechtko as reviewer

**Comment by whedon** [comment]
OK, @sreschechtko is now a reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1849. Feel free to close this issue now!
