### ISSUE TITLE
[PRE REVIEW]: feign: a Python package to estimate geometric efficiency in passive gamma spectroscopy measurements of nuclear fuel

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1649]
**Submitting author:** @ezsolti (<a href="http://orcid.org/0000-0003-2339-4340">Zsolt Elter</a>)
**Repository:** <a href="https://github.com/ezsolti/feign/" target ="_blank">https://github.com/ezsolti/feign/</a>
**Version:** v1.0.0
**Editor:** @katyhuff
**Reviewers:** @kellyrowland, @sskutnik

**Author instructions**

Thanks for submitting your paper to JOSS @ezsolti. The JOSS editor @katyhuff, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ezsolti if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @katyhuff it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@katyhuff) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1649 with the following error: 

 Error reading bibliography ./paper.bib (line 17, column 1):
unexpected "t"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
👋 @katyhuff - this submission requested you as the editor, and this seemed like such a good fit that I just left it that way - please let me know if this is not ok.

**Comment by danielskatz** [comment]
👋 @ezsolti - please merge https://github.com/ezsolti/feign/pull/6 and then enter a new comment here: ```@whedon generate pdf``` - if there are additional problems, please make changes to the source and regenerate the pdf until you are happy with it.

**Comment by katyhuff** [comment]
I can definitely take this one. Thanks @danielskatz .

@ezsolti : We can begin requesting reviewers when ezsolti/feign#6 is merged and when you are happy with the PDF that builds from `@whedon generate pdf` . I have some reviewers in mind, though your suggestions are certainly welcome.  If you have any suggestions for potential reviewers then please mention them here in this thread. [This list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Comment by ezsolti** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01649/joss.01649/10.21105.joss.01649.pdf)

**Comment by ezsolti** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01649/joss.01649/10.21105.joss.01649.pdf)

**Comment by ezsolti** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01649/joss.01649/10.21105.joss.01649.pdf)

**Comment by ezsolti** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01649/joss.01649/10.21105.joss.01649.pdf)

**Comment by ezsolti** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01649/joss.01649/10.21105.joss.01649.pdf)

**Comment by ezsolti** [comment]
@katyhuff : Hello! Thank you for taking care of the paper. I reached a pdf what I'm more or less satisfied with (besides that a cite to a conference paper doesn't want to render correctly, what ever I do).
I have reviewers in mind only from the safeguards side, so maybe it is better to go with your suggestions.

**Comment by katyhuff** [comment]
@ezsolti : 

Ok --  I'll start asking for reviewers. (nonproliferation and safeguards suggestions are just as welcome as anyone else). 

How would you like the citation to render?

**Comment by katyhuff** [comment]
* @kellyrowland: Dr. Rowland, are you able to and interested in taking on this review?
* This submission is in need of expertise in nuclear engineering, particularly gamma spectroscopy and ray tracing, as well as familiarity with the systems and languages involved (python). 
* Title: feign: a Python package to estimate geometric efficiency in passive gamma spectroscopy measurements of nuclear fuel 
* Summary: feign is a python package for estimating the geometric efficiency in passive gamma spectroscopy measurements of spent nuclear fuel assemblies. It implements a 2D point-kernel method without build-up factors (ie. an "uncollided F5 tally" as known by MCNP users). The name feign implies that the program pretends to be a transport code, however it is rather a ray-tracing code. It is intended for nuclear safeguards specialists and nuclear engineers who want to get a quick estimate on the geometric efficiency in their passive gamma setup. It might be also useful to people working with passive gamma emission tomography of spent fuel. The feign API allows the user to define the geometry of a rectangular fuel assembly, which is built of pins (nested annular material regions). The user also defines the composition of materials present in the simulation, the detector points where the efficiency needs to be evaluated, and optionally collimators and absorber elements.
* Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01649/joss.01649/10.21105.joss.01649.pdf
* Submitting author: @ezsolti (Zsolt Elter)
* Repository: https://github.com/ezsolti/feign
* Version: v1.0.0

**Comment by ezsolti** [comment]
@katyhuff : In that case Stefano Vaccaro (author of one of the cited papers: https://www.sciencedirect.com/science/article/pii/S0168900216307707) might be a good candidate.

For the 'Partial defect identification in PWR spent fuel using Passive Gamma Spectroscopy' paper the Proceedings doesn't want to appear, also when referenced all surnames appear instead of (Elter et al., 2018).

**Comment by kellyrowland** [comment]
Hi @katyhuff , thanks for reaching out - I am interested in and able to take on this review.

**Comment by katyhuff** [comment]
* @sskutnik: Prof. Skutnik, are you able to and interested in taking on this review? The Journal of Open Source Software is a developer friendly, open access journal for research software packages. A JOSS review primarily involves checking submissions against a checklist of essential software features and details in the submitted paper and code. I am the handling editor for a submission that could use your expertise. More information about the review process can be found in [our reviewer documentation](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). If you are willing and able to review this submission for JOSS, please let me know in this github thread and fill out your information at this signup form: https://joss.theoj.org/reviewer-signup.html . If not, please just let me know in this thread.
* This submission is in need of expertise in nuclear engineering, particularly gamma spectroscopy and ray tracing, as well as familiarity with the systems and languages involved (python). 
* Title: feign: a Python package to estimate geometric efficiency in passive gamma spectroscopy measurements of nuclear fuel 
* Summary: feign is a python package for estimating the geometric efficiency in passive gamma spectroscopy measurements of spent nuclear fuel assemblies. It implements a 2D point-kernel method without build-up factors (ie. an "uncollided F5 tally" as known by MCNP users). The name feign implies that the program pretends to be a transport code, however it is rather a ray-tracing code. It is intended for nuclear safeguards specialists and nuclear engineers who want to get a quick estimate on the geometric efficiency in their passive gamma setup. It might be also useful to people working with passive gamma emission tomography of spent fuel. The feign API allows the user to define the geometry of a rectangular fuel assembly, which is built of pins (nested annular material regions). The user also defines the composition of materials present in the simulation, the detector points where the efficiency needs to be evaluated, and optionally collimators and absorber elements.
* Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01649/joss.01649/10.21105.joss.01649.pdf
* Submitting author: @ezsolti (Zsolt Elter)
* Repository: https://github.com/ezsolti/feign
* Version: v1.0.0

**Comment by katyhuff** [comment]
@whedon assign @kellyrowland as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kellyrowland

**Comment by katyhuff** [comment]
Thank you @kellyrowland! I'll ping you when we have enough reviewers to begin the review.

Thank you @ezsolti : Thank you for your suggestion, I'll look into including Stefano Vaccaro as a reviewer.

**Comment by sskutnik** [comment]
Hi @katyhuff I'd be happy to serve as a reviewer.

**Comment by katyhuff** [comment]
Fantastic @sskutnik , thank you.

**Comment by katyhuff** [comment]
@whedon add @sskutnik as reviewer

**Comment by whedon** [comment]
OK, @sskutnik is now a reviewer

**Comment by katyhuff** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1650. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Ok, folks, let's move over to #1650 to conduct the review. In that issue, each of you have a checklist. Please make sure that you have notifications turned on in issue #1650 and that you have at some point completed the reviewer signup form. https://joss.theoj.org/reviewer-signup.html
