### ISSUE TITLE
[REVIEW]: deepCR: Cosmic Ray Rejection with Deep Learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1651]
**Submitting author:** @kmzzhang (<a href="http://orcid.org/0000-0002-9870-5695">Keming Zhang</a>)
**Repository:** <a href="https://github.com/profjsb/deepCR" target ="_blank">https://github.com/profjsb/deepCR</a>
**Version:** v0.2.0
**Editor:** @terrytangyuan
**Reviewer:** @shreyasbapat, @DanielLenz
**Archive:** <a href="https://doi.org/10.5281/zenodo.3383309" target="_blank">10.5281/zenodo.3383309</a>

## Status

[![status](https://joss.theoj.org/papers/631cf287644112b79ae936229491f9ab/status.svg)](https://joss.theoj.org/papers/631cf287644112b79ae936229491f9ab)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/631cf287644112b79ae936229491f9ab"><img src="https://joss.theoj.org/papers/631cf287644112b79ae936229491f9ab/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/631cf287644112b79ae936229491f9ab/status.svg)](https://joss.theoj.org/papers/631cf287644112b79ae936229491f9ab)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/profjsb/deepCR" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@shreyasbapat & @DanielLenz, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @terrytangyuan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/profjsb/deepCR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.2.0
- [x] **Authorship:** Has the submitting author (@kmzzhang) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/profjsb/deepCR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.2.0
- [x] **Authorship:** Has the submitting author (@kmzzhang) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @shreyasbapat, @DanielLenz it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01651/joss.01651/10.21105.joss.01651.pdf)

**Comment by DanielLenz** [comment]
I really enjoyed the package and the paper, thanks for providing that! I'll wrap up the review shortly. 

In the meantime, could you add the software acknowledgements that you have included in our AAS submission here as well?

**Comment by shreyasbapat** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01651/joss.01651/10.21105.joss.01651.pdf)

**Comment by kmzzhang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01651/joss.01651/10.21105.joss.01651.pdf)

**Comment by kmzzhang** [comment]
@DanielLenz I have included the software acknowledgements.

**Comment by shreyasbapat** [comment]
Can the network architecture diagram be also included in the paper? Or maybe in the README as  it is in the https://arxiv.org/pdf/1907.09500.pdf ?

**Comment by shreyasbapat** [comment]
Though, it's really amazing! I loved reviewing the submission. The paper is awesome, and the package is definitely awesome :D

**Comment by terrytangyuan** [comment]
@kmzzhang Could you take a look at @shreyasbapat's suggestion? We should be ready to move on after that.

**Comment by kmzzhang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01651/joss.01651/10.21105.joss.01651.pdf)

**Comment by kmzzhang** [comment]
@shreyasbapat I've added the network architecture figure in the paper. I also added both figure caption to the main text because they're not showing up as figure captions. Please let me know if this is the optimal way to do it. Thanks!

**Comment by DanielLenz** [comment]
Thanks for adding the figures! I'm sure there a more optimal way to adjust the alignment/spacing and the caption; do you have any pointers, @terrytangyuan ?

**Comment by terrytangyuan** [comment]
cc @openjournals/joss-eics who might have a better idea on how to fix it.

**Comment by kyleniemeyer** [comment]
@kmzzhang if you put the figures on their own lines, the positioning should be better; you can also add captions:
```markdown
``deepCR`` is a Python package ...
... at left) is concatenated with the original image as the input.

![Figure 1](https://raw.githubusercontent.com/profjsb/deepCR/master/imgs/network.png)

Since ``deepCR`` ... 
...pixels replaced with deepCR predictions  (last row).

![Figure 2](https://raw.githubusercontent.com/profjsb/deepCR/master/imgs/postage-sm.jpg)
 
In the paper accompanying ``deepCR`` [@deepcr], the authors showed that ...
```

**Comment by kmzzhang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01651/joss.01651/10.21105.joss.01651.pdf)

**Comment by shreyasbapat** [comment]
Hi @kmzzhang , 

Thanks for including the figure, but can we change the caption to both the figures and make the alignment a little better?

**Comment by shreyasbapat** [comment]
> I also added both figure caption to the main text because they're not showing up as figure captions

Oh I see :/

**Comment by kmzzhang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kmzzhang** [comment]
Hi @shreyasbapat, I'm still working on the format. This version should work

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01651/joss.01651/10.21105.joss.01651.pdf)

**Comment by shreyasbapat** [comment]
> Hi @shreyasbapat, I'm still working on the format. This version should work

Right! Thanks a lot for the changes! GTG!

**Comment by DanielLenz** [comment]
Excellent, thanks for fixing this so quickly.

Last quick comment: Could you separate the software acknowledgements with a delimiter (semicolon, comma)?

Other than that, I'm happy to say that I recommend this for publication!

**Comment by kmzzhang** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01651/joss.01651/10.21105.joss.01651.pdf)

**Comment by kmzzhang** [comment]
Hi @DanielLenz, this is fixed!

**Comment by DanielLenz** [comment]
@terrytangyuan, I think both @shreyasbapat and myself approve the manuscript and the code base.

What's the next step for the submission?

**Comment by kmzzhang** [comment]
Hi @terrytangyuan, could you please let us know the next steps? Thanks.

**Comment by crawfordsm** [comment]
For reference, the corresponding paper has been accepted at the AAS and the AAS DOI for the paper is 10.3847/1538-3881/ab3c53

**Comment by arfon** [comment]
> Hi @terrytangyuan, could you please let us know the next steps? Thanks.

@kmzzhang - can you tell me what AAS journal you submitted the other paper to? There’s a small amount of metadata we need you to add to the `paper.md` file before accepting the JOSS paper (this links the two papers).

**Comment by kmzzhang** [comment]
@arfon It is accepted to ApJ

**Comment by arfon** [comment]
@kmzzhang - can you merge this PR please? https://github.com/profjsb/deepCR/pull/10

**Comment by kmzzhang** [comment]
@arfon done

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01651/joss.01651/10.21105.joss.01651.pdf)

**Comment by arfon** [comment]
@terrytangyuan - this looks to be ready for you to accept I think?

**Comment by terrytangyuan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1086/323894 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.5281/zenodo.1482019 is OK
- 10.7717/peerj.453 is OK
- 10.3847/1538-3881/aabc4f is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by terrytangyuan** [comment]
@kmzzhang Thanks! 

At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

* The title of the archive is the same as the JOSS paper title
* That the authors of the archive are the same as the JOSS paper authors
I can then move forward with accepting the submission.

**Comment by kmzzhang** [comment]
@terrytangyuan DOI: 10.5281/zenodo.3383309. Thanks!

**Comment by terrytangyuan** [comment]
@whedon set v0.2.0 as version

**Comment by whedon** [comment]
OK. v0.2.0 is the version.

**Comment by terrytangyuan** [comment]
@whedon set 10.5281/zenodo.3383309 as doi

**Comment by terrytangyuan** [comment]
@whedon set 10.5281/zenodo.3383309 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3383309" target="_blank">10.5281/zenodo.3383309</a> is the archive.

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/940

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/940, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by terrytangyuan** [comment]
Looks good to me. @arfon Could you handle the next steps?

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1168519263751221254) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/941
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01651](https://doi.org/10.21105/joss.01651)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@shreyasbapat, @DanielLenz - many thanks for your reviews here and to @terrytangyuan for editing this submission ✨ 

@kmzzhang - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01651/status.svg)](https://doi.org/10.21105/joss.01651)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01651">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01651/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01651/status.svg
   :target: https://doi.org/10.21105/joss.01651
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01651/status.svg)](https://doi.org/10.21105/joss.01651)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by kmzzhang** [comment]
@arfon I just realized that the title in the paper is incorrect. It should be “deepCR: Cosmic Ray Rejection with Deep Learning,” while the published paper has the word “Ray" missing. I may have omitted it in the paper source file — the title in the paper submission metadata is correct. Is there a way to fix this error?

**Comment by kmzzhang** [comment]
@arfon I just realized that the title in the paper is incorrect. It should be “deepCR: Cosmic Ray Rejection with Deep Learning,” while the published paper has the word “Ray" missing. I may have omitted it in the paper source file — the title in the paper submission metadata is correct. Is there a way to fix this error?

**Comment by arfon** [comment]
@kmzzhang - I can fix this for you.

**Comment by arfon** [comment]
OK that should be fixed now. It might take a few hours for the updated paper to show up online as there's caching in place for the PDFs.
