### ISSUE TITLE
[PRE REVIEW]: molic: An R package for multivariate outlier detection in contingency tables

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1653]
**Submitting author:** @mlindsk (<a href="http://orcid.org/0000-0002-1033-697X">Mads Lindskou</a>)
**Repository:** <a href="https://github.com/mlindsk/molic" target ="_blank">https://github.com/mlindsk/molic</a>
**Version:** v0.5.0
**Editor:** @csoneson
**Reviewers:** @jdeligt, @jkanche

**Author instructions**

Thanks for submitting your paper to JOSS @mlindsk. **Currently, there isn't an JOSS editor assigned** to your paper.

@mlindsk if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1653 with the following error: 

 Error producing PDF.
! LaTeX Error: File `algorithm.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.255 \usepackage

Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
@mlindsk - it looks like a file is missing.  Please enter ```@whedon generate pdf``` as a new comment in this issue to instruct whedon to try again, and iterate until the paper compiles.

**Comment by mlindsk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1653 with the following error: 

 Error producing PDF.
! LaTeX Error: File `algorithm.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.255 \usepackage

Looks like we failed to compile the PDF

**Comment by mlindsk** [comment]
I have looked for information on the use of  external latex packages in paper.md but failed. Is it not possible to include such packages as the latex algorithm package?

**Comment by danielskatz** [comment]
👋 @arfon?

**Comment by arfon** [comment]
> @danielskatz I have looked for information on the use of external latex packages in paper.md but failed. Is it not possible to include such packages as the latex algorithm package?

We generally don't support custom packages with the paper build. Can you tell me what you're trying to achieve here, and could it be accomplished with regular (LaTeX) maths syntax?

**Comment by mlindsk** [comment]
I am trying to display a pseudo algorithm in the algorithmics environment which cannot be done in regular latex. If it's a hassle I can certainly find other ways to achieve something similar. I just like the format.

**Comment by danielskatz** [comment]
Can you go ahead and do this in another way?

**Comment by mlindsk** [comment]
Yes sure. I will try to make a standalone tex file for the algorithm and convert to png.

**Comment by mlindsk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1653 with the following error: 

 Error producing PDF.
! LaTeX Error: File `algorithm.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.255 \usepackage

Looks like we failed to compile the PDF

**Comment by mlindsk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1653 with the following error: 

 Error producing PDF.
! Undefined control sequence.
l.298 \algrenewcommand

Looks like we failed to compile the PDF

**Comment by mlindsk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01653/joss.01653/10.21105.joss.01653.pdf)

**Comment by mlindsk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01653/joss.01653/10.21105.joss.01653.pdf)

**Comment by mlindsk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01653/joss.01653/10.21105.joss.01653.pdf)

**Comment by mlindsk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01653/joss.01653/10.21105.joss.01653.pdf)

**Comment by mlindsk** [comment]
@danielskatz Hi Daniel. It finally worked; a hassle to get the spacing right.

**Comment by danielskatz** [comment]
Thanks - can you now add something about what types of research this enables?  And how such research will use it?

**Comment by danielskatz** [comment]
👋 @csoneson - would you be willing to edit this submission?

**Comment by mlindsk** [comment]
Sure. I'll look into this Monday morning (afternoon here in Denmark).

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋mlindsk - I will handle your submission. Do you have suggestions for suitable reviewers (e.g. from the list linked in the first comment above)?

A couple of initial comments, in addition to @danielskatz's above:
- [ ] Please only include the references that you are citing in the .bib file
- [ ] It looks like there are no actual tests in the `testthat/` folder - could you add that?
- [ ] Check the capitalization of "Proceedings of the seventeenth conference..."

**Comment by mlindsk** [comment]
@csoneson That is great. I will look through the list and propose someone as reviewer. And I will handle @danielskatz and your comments first thing tomorrow morning.

**Comment by mlindsk** [comment]
Hi,

Would any of you be willing to review the molic package ?

@VivekTodur
@jkanche

**Comment by mlindsk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01653/joss.01653/10.21105.joss.01653.pdf)

**Comment by mlindsk** [comment]
> wavemlindsk - I will handle your submission. Do you have suggestions for suitable reviewers (e.g. from the list linked in the first comment above)?
> 
> A couple of initial comments, in addition to @danielskatz's above:
> 
>     * [ x ]  Please only include the references that you are citing in the .bib file
> 
>     * [ x ]  It looks like there are no actual tests in the `testthat/` folder - could you add that?
> 
>     * [ x ]  Check the capitalization of "Proceedings of the seventeenth conference..."

:wave: @csoneson Updates according to your comments.

**Comment by mlindsk** [comment]
Hi,

I am a suggesting a few more potential reviewers. I suggest reviewers based on **R**, **C++** and possibly **genomics/genetics**.

@jdeligt
@jkanche

**Comment by csoneson** [comment]
@mlindsk - great, thanks. While we are waiting to see whether @VivekTodur, @jdeligt or @jkanche would be available and interested in reviewing the submission, a couple of more things for the paper that can just as well be fixed now:
- please add DOIs to all your references wherever possible
- could you fix the "Consortium, 1. G. P. & others" in the reference list? 
- when a citation is part of a sentence, please give it without the enclosing square brackets in the markdown file (e.g. in the first sentence of the second paragraph of the use case, but there are also other instances). 
- I still think that "Proceedings of the seventeenth..." should have some words capitalized (e.g. according to https://dl.acm.org/citation.cfm?id=647235&picked=prox)

**Comment by mlindsk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01653/joss.01653/10.21105.joss.01653.pdf)

**Comment by mlindsk** [comment]
@csoneson Goodmorning.

>     * please add DOIs to all your references wherever possible
 - check 
>     * could you fix the "Consortium, 1. G. P. & others" in the reference list?
 - It renders fine when i'm running pandoc locally - i dont have control over the JOSS config. At least I wouldn't know how to change this. Any advice would be helpful.
>     * when a citation is part of a sentence, please give it without the enclosing square brackets in the markdown file (e.g. in the first sentence of the second paragraph of the use case, but there are also other instances).
 - Thanks - I was not aware that I could simply remove the brackets.
>     * I still think that "Proceedings of the seventeenth..." should have some words capitalized (e.g. according to https://dl.acm.org/citation.cfm?id=647235&picked=prox)
 - I have capitalized exactly the same words as in the reference. Again, it is something the JOSS pandoc config does.

**Comment by csoneson** [comment]
I think both of these issues can be solved by an extra pair of curly brackets. I just sent a PR.

**Comment by jdeligt** [comment]
Count me in

**Comment by mlindsk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01653/joss.01653/10.21105.joss.01653.pdf)

**Comment by mlindsk** [comment]
@csoneson 
> I think both of these issues can be solved by an extra pair of curly brackets. I just sent a PR.

Fantastic to learn new things in bibfiles. Seems corrected now.

@jdeligt 
> Count me in

Fantastic!

**Comment by jkanche** [comment]
I can review this package as well!

**Comment by mlindsk** [comment]
@jkanche Fantastic!

**Comment by csoneson** [comment]
@jdeligt, @jkanche - thanks a lot! I'll assign you as reviewers and start the review issue.

**Comment by csoneson** [comment]
@whedon assign @jdeligt as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jdeligt

**Comment by csoneson** [comment]
@whedon add @jkanche as reviewer

**Comment by whedon** [comment]
OK, @jkanche is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1665. Feel free to close this issue now!
