### ISSUE TITLE
[REVIEW]: cspy: A Python package with a collection of algorithms for the (Resource) Constrained Shortest Path problem

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1655]
**Submitting author:** @torressa (<a href="http://orcid.org/0000-0002-2894-9432">David Torres Sanchez</a>)
**Repository:** <a href="https://github.com/torressa/cspy" target ="_blank">https://github.com/torressa/cspy</a>
**Version:** v0.1.0
**Editor:** @poulson
**Reviewers:** @hausen, @stsievert
**Archive:** <a href="https://doi.org/10.5281/zenodo.3837663" target="_blank">10.5281/zenodo.3837663</a>

## Status

[![status](https://joss.theoj.org/papers/25eda55801a528b982d03a6a61f7730d/status.svg)](https://joss.theoj.org/papers/25eda55801a528b982d03a6a61f7730d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/25eda55801a528b982d03a6a61f7730d"><img src="https://joss.theoj.org/papers/25eda55801a528b982d03a6a61f7730d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/25eda55801a528b982d03a6a61f7730d/status.svg)](https://joss.theoj.org/papers/25eda55801a528b982d03a6a61f7730d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/torressa/cspy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@hausen & @stsievert, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @poulson know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/torressa/cspy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.1.0
- [x] **Authorship:** Has the submitting author (@torressa) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/torressa/cspy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.1.0
- [x] **Authorship:** Has the submitting author (@torressa) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
    * see https://github.com/torressa/cspy/issues/14
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
    * see https://github.com/torressa/cspy/issues/15
    * (in-depth example provided on GitHub; as of 2020-01-08 simple example on documentation not provided)
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
    * see https://github.com/torressa/cspy/issues/16

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @hausen, @oesteban, @stsievert it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01655/joss.01655/10.21105.joss.01655.pdf)

**Comment by stsievert** [comment]
Thanks for the submission @torressa! This package looks pretty good.

The biggest improvements I see are documentation, specifically with the statement of need and a use of the software.

* I think the "statement of need" could use work, in the paper and especially in the documentation. I don't see any motivating reasons on why I, a grad student studying optimization (but not an expert on shortest path problems) should pick up cspy.
    * Possibly relevant questions: When is the constrained shortest path problem relevant? What concrete problems can it be applied to? What features does cspy provide, and why is it unique?
    * The provided statement of need is a lot clearer in paper than the documentation.
* I'd also like to more in-depth use of this software. Right now, I can only see some toy examples in the docstrings. Ideally, I think this would be best with an example with real data.
    * One question I have: how are constraints from real problems coded in cspy? I know cspy can be used in the vehicle routing problem with time windows (desaulniers2008tabu), but don't know how to code the time constraints in cspy. 

I can point to some examples of other projects with good motivation/statement of needs if you'd like.

I feel these points would increase my inclination to use or recommend this software (though I am not a member of the target audience, the operational research community).

Some other comments: 

* Could you add a point on how to contribute code? There are some good instructions in README.md for issues, but it's a little slim on "contributing to the software" and "seeking support".
* @poulson should books have DOIs? They list the book "Computers and Intractability; A Guide to the Theory of NP-Completeness" as a reference without a DOI.

I might have some more comments in the future.

**Comment by torressa** [comment]
Thanks @stsievert for the comments and your prompt review :)
Really appreciate the comments. I'll raise them as separate issues and work on them in the coming days.

**Comment by stsievert** [comment]
Thanks for opening those issues @torressa – that's useful. They provide a channel for more detailed feedback and any questions you have.

**Comment by poulson** [comment]
Hi :wave: @hausen and @oesteban: it looks like it's been a couple of weeks and @stsievert is getting to a midway point in their review, but neither of you has checked any boxes or made any comments. It is pretty common for reviews to fall between the cracks, so I am hoping to raise this towards the top of your river of emails. :smile:

**Comment by oesteban** [comment]
@poulson Sorry, I thought I wasn't assigned this one (https://github.com/openjournals/joss-reviews/issues/1571#issuecomment-520653198). I'm still pretty swamped so I can't take this for review - I will for sure hold it up for long.

**Comment by poulson** [comment]
@whedon remove @oesteban as reviewer

**Comment by whedon** [comment]
OK, @oesteban is no longer a reviewer

**Comment by stsievert** [comment]
@torressa I've updated https://github.com/openjournals/joss-reviews/issues/1655#issuecomment-523107985 to include a note of the API documentation.

**Comment by danielskatz** [comment]
👋 I'm just checking in on this as the associate-editor-in-chief on duty this week ... What's the status here?

**Comment by stsievert** [comment]
:+1: Thanks for checking in @danielskatz! I've been waiting until some points in https://github.com/openjournals/joss-reviews/issues/1655#issuecomment-523107985 and issues I've filed to be resolved.

I have filed some issues on the source repository (https://github.com/torressa/cspy/issues/14, https://github.com/torressa/cspy/issues/15, https://github.com/torressa/cspy/issues/16). I'm don't think this paper can be accepted until some of these issues are resolved.

**Comment by torressa** [comment]
Sorry, was on holiday then swamped with new job. Will get going over the next weekends.
Thanks @stsievert  for your feedback!

**Comment by torressa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01655/joss.01655/10.21105.joss.01655.pdf)

**Comment by torressa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01655/joss.01655/10.21105.joss.01655.pdf)

**Comment by poulson** [comment]
Thank you, @stsievert -- it looks like the rest of the review depends upon you!

@torressa -- am I understanding that you are expecting to need one more weekend to respond to @stsievert's issues?

**Comment by torressa** [comment]
@poulson That's right! 
I made some changes in the paper but docs and actual functioning example need to be updated.

**Comment by danielskatz** [comment]
👋 @poulson - just checking in on the status of this submission...

**Comment by torressa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01655/joss.01655/10.21105.joss.01655.pdf)

**Comment by poulson** [comment]
Hi @torressa and @stsievert -- in our previous discussion a few weeks ago it looked like @torressa just needed to finalize some changes requested by @stsievert.

@torressa: How are those changes coming along?

@stsievert: Are you happy with the changes so far?

**Comment by torressa** [comment]
Hi @poulson! Thanks for the follow up.
I have made a few changes to accommodate for the comments.
I might still add some additional examples and update the docs.

**Comment by poulson** [comment]
Thank you, @torressa!

:wave: @stsievert -- Do you have have any lingering concerns given David's updates?

It looks like you might still be concerned about: functionality, performance, examles, statement of need, and community guidelines.

**Comment by stsievert** [comment]
I think most of my concerns have been resolved (but will need to look more carefully). I'd still like to see a simple use case on the documentation, alongside a clear description of the features of a CSP problem.

**Comment by poulson** [comment]
Hi @hausen :wave: -- please let me know if you think you will be able to make progress on your review in the next few days. @stsievert has been nearly done with theirs for a few weeks and it would be good for us to promptly respond to the authors.

**Comment by hausen** [comment]
@poulson Sorry for the extremely long delay. I'll send you my comments by Friday.

**Comment by hausen** [comment]
@torressa @poulson I only found a couple of small issues:

1. **Installation instructions:** `pip install cspy` does not automatically install the dependencies (tried on a clean pyenv)

2. **Example usage:** a couple of the examples in the API docs have errors.
  * [BiDirectional](https://cspy.readthedocs.io/en/latest/api/cspy.BiDirectional.html#example): replace `import cspy` with `from cspy import BiDirectional`
  * [GreedyElim](https://cspy.readthedocs.io/en/latest/api/cspy.GreedyElim.html#example): add `from networkx import DiGraph` line, replace `G = nx.DiGraph(directed=True, n_res=2)` with `G = DiGraph(directed=True, n_res=2)`
  * [PSOLGENT](https://cspy.readthedocs.io/en/latest/api/cspy.PSOLGENT.html#example): replace `n_nodes = len(self.J.nodes())` with `n_nodes = len(G.nodes())`
  * [cgar/requirements.txt](https://github.com/torressa/cspy/blob/master/examples/cgar/requirements.txt): replace `cspy>=0.8` with `cspy>=0.0.8`. Unfortunately, I couldn't test it because it requires a proprietary package, `gurobipy`. @torressa is it possible to eliminate that requirement, or provide another real-world example that doesn't need that package?

3. **README.md**: `Inrich and Desaulniers (2005)` should link to https://www.researchgate.net/publication/227142556_Shortest_Path_Problems_with_Resource_Constraints .

**Comment by torressa** [comment]
Thanks @hausen for the comments.
Will sort them out in the weekend.

**Comment by torressa** [comment]
Sorted! 
1. Updated the pypi package (bumped to 0.0.10) so that it would automatically install dependencies.
2. Corrected mistakes in doc examples. Also translated airport example to use PuLP instead of gurobipy.
3. Fixed! (Together with all the other links that weren't working)

**Comment by labarba** [comment]
👋  @poulson — Looks like the author posted some updates that need your attention. Can you pop in here an check?

**Comment by poulson** [comment]
Hi @hausen -- it looks like you haven't checked any of the review boxes despite some responses from the author to your suggestions. Are there further fixes needed, or are you happy with their response?

**Comment by hausen** [comment]
@poulson yeah, everything seems to be good with the submission. For some reason, I can't check any of the boxes above, but if I could I'd check all of them.

**Comment by arfon** [comment]
@hausen - can you try accepting the invite at this page which should allow you to update the checklist https://github.com/openjournals/joss-reviews/invitations

**Comment by hausen** [comment]
@arfon @poulson done

**Comment by poulson** [comment]
Thank you, Rodrigo (@hausen)!

Hi Scott (@stsievert) :wave: -- it seems you still have four boxes unchecked:
 - Statement of need
 - Example Usage
 - Functionality Documentation
 - References

Do you have any lingering concerns on any of these four?

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by stsievert** [comment]
> Do you have any lingering concerns on any of these four?

- Problem statement: no. I've checked the box.
- [ ] Example usage: yes. The link to "examples" is broken on the docs (on *[Using cspy]*), and I'd like to see a simple example as expressed in https://github.com/torressa/cspy/issues/15#issuecomment-566115714
- [ ] Functionality Documentation: one small concerns. The `n_res` parameter on the algorithms page is not defined (e.g, [GRASP]). It is explained on *[Using cspy]*, but confusing when I first see an algorithm. Perhaps if I were a domain expert I would realize.
- References: no.

I've checked the boxes above.

[Using cspy]:https://cspy.readthedocs.io/en/latest/how_to.html
[GRASP]:https://cspy.readthedocs.io/en/latest/api/cspy.GRASP.html

**Comment by torressa** [comment]
Hi @stsievert !
Sorted.
I've added the simple example that used to be in the paper as a jupyter notebook.
I've explained the `n_res` parameter explicitly in the [Using cspy](https://cspy.readthedocs.io/en/latest/how_to.html) part of the docs and it I think it's pretty clear from the API examples what it is.
Hope that's ok

**Comment by stsievert** [comment]
Thanks for the improvements @torressa! The docs are looking better. Thanks for adding the simple example.

Could you add the simple example to the main documentation page? I think that'd help provide some more clarify.

**Comment by torressa** [comment]
Done! Thanks @stsievert for the suggestions.
By the way, more examples coming! 
I'm collaborating with someone to implements some vehicle routing variants using cspy!!

**Comment by arfon** [comment]
:wave: just a friendly check-in to see how things are going with this review? @stsievert - I note that there are a few un-checked items on your review list?

**Comment by torressa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01655/joss.01655/10.21105.joss.01655.pdf)

**Comment by torressa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01655/joss.01655/10.21105.joss.01655.pdf)

**Comment by torressa** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01655/joss.01655/10.21105.joss.01655.pdf)

**Comment by torressa** [comment]
Just updated the paper with a list of linked examples.
Sorry for the bombarding, couldn't get the bullets to work

**Comment by stsievert** [comment]
I've checked off all my boxes. The simple example at https://cspy.readthedocs.io/en/latest/how_to.html#simple-example has greatly helped improve the usability of this software.

I have unchecked the software versioning box. I would have not accepted v0.0.8; however I would be willing to accept the current release v0.1.0 (perhaps in part due to https://github.com/torressa/cspy/issues/14, https://github.com/torressa/cspy/issues/15 and https://github.com/torressa/cspy/issues/16). How should that be managed?

**Comment by torressa** [comment]
Just updated the docs. 

Versioning-wise, do you mean that the points need updating to match the current version (v0.1.0)?

Since the start of the submission there has a fair amount of bug fixes (around 6 major ones), a few new features and some other changes stemming from the development of the vehicle routing application [vrpy](https://github.com/Kuifje02/vrpy/). Taking the version to v0.0.14.

After the exact algorithm is actually providing known optimal solutions to the vehicle routing problem I decided to bump from v0.0.14 to v0.1.0.

**Comment by stsievert** [comment]
>> I would have not accepted v0.0.8; however I would be willing to accept the current release v0.1.0 (perhaps in part due to torressa/cspy#14, torressa/cspy#15 and torressa/cspy#16). How should that be managed?
>
> Versioning-wise, do you mean that the points need updating to match the current version (v0.1.0)? Since the start of the submission there has a fair amount of bug fixes

Whoops, thanks. I meant to ask @poulson or @afron that question.

**Comment by arfon** [comment]
I think we can simply update the version associated with the review here (to `v0.1.0`) and declare that the version associated with the review.

Would that be acceptable @hausen & @stsievert?

**Comment by hausen** [comment]
fine by me @arfon !

**Comment by stsievert** [comment]
That works for me too @arfon.

**Comment by arfon** [comment]
@poulson - I think this is pretty close to being ready to accept now.

**Comment by arfon** [comment]
@whedon check references

**Comment by arfon** [comment]
@whedon set v0.1.0 as version

**Comment by whedon** [comment]
OK. v0.1.0 is the version.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.disopt.2006.05.007 is OK
- 10.1016/j.ejor.2009.10.002 is OK
- 10.1109/TITS.2015.2477350 is OK
- 10.1007/s00291-007-0083-6 is OK
- 10.1016/j.orl.2004.11.011 is OK
- 10.1287/ijoc.1040.0117 is OK
- 10.1016/j.ejor.2016.06.058 is OK
- 10.1016/j.ejor.2014.04.004 is OK
- 10.1016/j.ejor.2017.03.017 is OK
- 10.1016/j.ejor.2017.09.035 is OK
- 10.1002/net.20212 is OK
- 10.1080/03155986.1988.11732063 is OK
- 10.1007/0-387-25486-2_2 is OK
- 10.1080/10556788.2018.1548015 is OK
- 10.1016/j.ejor.2017.03.031 is OK
- 10.1287/trsc.1070.0223 is OK
- 10.1002/net.20033 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01655/joss.01655/10.21105.joss.01655.pdf)

**Comment by arfon** [comment]
@torressa - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by torressa** [comment]
Hey @arfon, thanks for the follow up. 
All done, here's the DOI: 10.5281/zenodo.3837663

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3837663 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3837663" target="_blank">10.5281/zenodo.3837663</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.disopt.2006.05.007 is OK
- 10.1016/j.ejor.2009.10.002 is OK
- 10.1109/TITS.2015.2477350 is OK
- 10.1007/s00291-007-0083-6 is OK
- 10.1016/j.orl.2004.11.011 is OK
- 10.1287/ijoc.1040.0117 is OK
- 10.1016/j.ejor.2016.06.058 is OK
- 10.1016/j.ejor.2014.04.004 is OK
- 10.1016/j.ejor.2017.03.017 is OK
- 10.1016/j.ejor.2017.09.035 is OK
- 10.1002/net.20212 is OK
- 10.1080/03155986.1988.11732063 is OK
- 10.1007/0-387-25486-2_2 is OK
- 10.1080/10556788.2018.1548015 is OK
- 10.1016/j.ejor.2017.03.031 is OK
- 10.1287/trsc.1070.0223 is OK
- 10.1002/net.20033 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1456

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1456, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1263506113623986178) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1457
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01655](https://doi.org/10.21105/joss.01655)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@hausen, @stsievert - many thanks for your reviews here and to @poulson for editing this submission ✨ 

@torressa - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01655/status.svg)](https://doi.org/10.21105/joss.01655)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01655">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01655/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01655/status.svg
   :target: https://doi.org/10.21105/joss.01655
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01655/status.svg)](https://doi.org/10.21105/joss.01655)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
