### ISSUE TITLE
[PRE REVIEW]: Torsional Axisymmetric Core Oscillations Visualiser (TACO-VIS): A python module for animating torsional wave data for fluid planetary cores.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1657]
**Submitting author:** @sam-greenwood (<a href="http://orcid.org/0000-0001-9303-6229">Sam Greenwood</a>)
**Repository:** <a href="https://github.com/sam-greenwood/taco_vis" target ="_blank">https://github.com/sam-greenwood/taco_vis</a>
**Version:** v1.0
**Editor:** @leouieda
**Reviewers:** @malmans2, @banesullivan

**Author instructions**

Thanks for submitting your paper to JOSS @sam-greenwood. The JOSS editor @leouieda, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@sam-greenwood if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @leouieda it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@leouieda) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1657 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1657/paper/paper.md): mapping values are not allowed in this context at line 2 column 70 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:115:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @leouieda - the submitter suggested you as reviewer, and I incorrectly assigned it to you without asking.  I apologize and hope this is ok - let me know if it is not.

**Comment by danielskatz** [comment]
@sam-greenwood - you will need to change bibliography.bibtex to paper.bib

**Comment by danielskatz** [comment]
👋 @sam-greenwood - I think merging https://github.com/sam-greenwood/taco_vis/pull/1 should allow the paper to compile - please enter ```@whedon generate pdf``` here as a new comment in this issue to try.

**Comment by sam-greenwood** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1657 with the following error: 

 pandoc-citeproc: reference cox2014forward not found
pandoc-citeproc: reference cox2014forward not found
Error producing PDF.
! Text line contains an invalid character.
l.407 ...strong magnetic field within the earth^^V

Looks like we failed to compile the PDF

**Comment by sam-greenwood** [comment]
Fixed the citations and reference

@whedon generate pdf

**Comment by sam-greenwood** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1657 with the following error: 

 Error producing PDF.
! Text line contains an invalid character.
l.423 convection and jets in earth^^V

Looks like we failed to compile the PDF

**Comment by sam-greenwood** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01657/joss.01657/10.21105.joss.01657.pdf)

**Comment by sam-greenwood** [comment]
> 👉 Check article proof 📄 👈

Almost, just need to fix the figures

**Comment by sam-greenwood** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01657/joss.01657/10.21105.joss.01657.pdf)

**Comment by leouieda** [comment]
@danielskatz no problem, I'd be happy to edit this submission!

**Comment by danielskatz** [comment]
@whedon assign @leouieda as editor

**Comment by whedon** [comment]
OK, the editor is @leouieda

**Comment by leouieda** [comment]
:wave: Hi @banesullivan @malmans2 would you be interested in reviewing this submission for JOSS?

**Comment by malmans2** [comment]
Hi @leouieda, sorry for the late reply, I was traveling. Yes, I would be happy to review this!

**Comment by banesullivan** [comment]
Hi @leouieda and @sam-greenwood, I’d also be happy to review this submission! It looks like a cool visualization tool and I’d be happy to this project grow

Sorry for the delayed reply as well... things are a bit hectic right now but I’d love to circle back to this next week and get started where I can!


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leouieda** [comment]
@malmans2 @banesullivan no worries about the delay. I really appreciate you taking the time to review! :rocket:

**Comment by leouieda** [comment]
@whedon assign @malmans2 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @malmans2

**Comment by leouieda** [comment]
@whedon add @banesullivan as reviewer

**Comment by whedon** [comment]
OK, @banesullivan is now a reviewer

**Comment by leouieda** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1720. Feel free to close this issue now!
