### ISSUE TITLE
[PRE REVIEW]: LISC: A Python Package for Scientific Literature Collection and Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1658]
**Submitting author:** @TomDonoghue (<a href="http://orcid.org/0000-0001-5911-0472">Thomas Donoghue</a>)
**Repository:** <a href="https://github.com/lisc-tools/lisc" target ="_blank">https://github.com/lisc-tools/lisc</a>
**Version:** v0.1.0
**Editor:** @danielskatz
**Reviewers:** @timClicks, @linuxscout

**Author instructions**

Thanks for submitting your paper to JOSS @TomDonoghue. **Currently, there isn't an JOSS editor assigned** to your paper.

@TomDonoghue if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01658/joss.01658/10.21105.joss.01658.pdf)

**Comment by danielskatz** [comment]
👋 @TomDonoghue - thanks for this submission.  I'm going to assign myself as editor, and while I'll be slower than normal to respond over the next 2 weeks, I think we'll be able to make progress.

For your part, please look at this [list of potential reviewers](https://bit.ly/joss-reviewers) and identify individuals who might be able to review your submission (please start at the bottom of the list). Also, please suggest individuals who are not on this list by mentioning their GitHub handles here.  I also have some ideas for reviewers...

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @pgroth - would you be willing to review this submission for JOSS?  (If you haven't done this before, which I think is the case, you might want to take a look at the [JOSS review guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) and specifically [JOSS review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html))

**Comment by TomDonoghue** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01658/joss.01658/10.21105.joss.01658.pdf)

**Comment by TomDonoghue** [comment]
Hey @danielskatz - thanks for editing this submission!

I re-generated the PDF to fix some bullet lists that I hadn't quite formatted right. 

In terms of reviewers, from the list of JOSS reviewers, the most relevant listings seem to me to be:
- Petar Maric (https://bitbucket.org/petar/)
- @\bagheria
- @\adammichaelwood
- @\linuxscout
- @\timClicks
- @\crew102

These aren't people I know personally, just the ones on the list for Python, who seemed to have the most related topic interests.

**Comment by danielskatz** [comment]
Hi - I'm on vacation, so this will happen a little slower than normal (but still faster than a traditional journal), and thanks in advance for your patience

**Comment by danielskatz** [comment]
👋 @bagheria, @adammichaelwood, @linuxscout, @timClicks, @crew102 - Would a couple of you be willing to review this submission for JOSS?

**Comment by timClicks** [comment]
Sure :)

**Comment by danielskatz** [comment]
Thanks @timClicks - I'll add you, but we won't start the review until we get another reviewer as well.

**Comment by danielskatz** [comment]
@whedon assign @timClicks as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @timClicks

**Comment by danielskatz** [comment]
👋 @dgarijo - would you be willing to review this submission for JOSS?  (If you haven't done this before, which I think is the case, you might want to take a look at the [JOSS review guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) and specifically [JOSS review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html))

**Comment by dgarijo** [comment]
Hi @danielskatz,
unfortunately my review pipeline is full at the moment. Sorry.
Thanks for considering me!

**Comment by linuxscout** [comment]
Salam,
I can review it.

**Comment by danielskatz** [comment]
Thanks @linuxscout - I'll add you, and we'll get started in the review issue that will be created shortly

**Comment by danielskatz** [comment]
@whedon add @linuxscout as reviewer

**Comment by whedon** [comment]
OK, @linuxscout is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1674. Feel free to close this issue now!

**Comment by crew102** [comment]
Hi @danielskatz , I could review if you guys need/want another.

**Comment by danielskatz** [comment]
I think we're set with 2 reviewers, but thanks.  If you want to anyhow, I can add you.

**Comment by crew102** [comment]
K, I'll sit this one out then.
