### ISSUE TITLE
[PRE REVIEW]: Open-Unmix - A Reference Implementation for Music Source Separation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1659]
**Submitting author:** @faroit (<a href="http://orcid.org/0000-0002-2534-1165">Fabian-Robert Stöter</a>)
**Repository:** <a href="https://github.com/sigsep/open-unmix-paper-joss" target ="_blank">https://github.com/sigsep/open-unmix-paper-joss</a>
**Version:** v1.0.0
**Editor:** @arokem
**Reviewers:** @bmcfee, hagenw

**Author instructions**

Thanks for submitting your paper to JOSS @faroit. **Currently, there isn't an JOSS editor assigned** to your paper.

@faroit if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #1659 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:143:in `block in check_orcids': Problem with ORCID (0000-0000-0000-0000) for Stefan Uhlich (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:141:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:141:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:88:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
Please merge https://github.com/sigsep/open-unmix-paper-joss/pull/1 and see if that enables the paper to build by entering ```@whedon generate pdf``` as a new comment here.  (also note that I suggested a number of language changes as well in the PR - these are all optional...

**Comment by danielskatz** [comment]
👋 @arokem - would you be willing to edit this submission?

**Comment by faroit** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01659/joss.01659/10.21105.joss.01659.pdf)

**Comment by faroit** [comment]
@danielskatz regarding the use of submodules, please note my questions I asked earlier in [JOSS#565](https://github.com/openjournals/joss/issues/565).

**Comment by danielskatz** [comment]
Thanks for pointing that out - please also mention it in the review thread that will be created once there are an editor and reviewers assigned.

**Comment by danielskatz** [comment]
Also, while we wait for that, you might want to make some fixes in the bib part of the paper - anything in a title or booktitle that should be in Upper Case needs to be protected with {}s, for example
booktitle={Proc. {IEEE} Intl. Conf. on Acoustics, Speech and Signal Processing (ICASSP)},
could be 
booktitle={{Proc. IEEE Intl. Conf. on Acoustics, Speech and Signal Processing (ICASSP)}},
to preserve all cases, or you could manually select parts to preserve, noting that the "." triggers automatic capitalization of the following word...

Another example is
  title        = {MUSDB18-HQ - an uncompressed version of MUSDB18},
which could be
  title        = {{MUSDB18-HQ} - an uncompressed version of {MUSDB18}},
or
  title        = {{MUSDB18-HQ - an uncompressed version of MUSDB18}},

**Comment by faroit** [comment]
> Also, while we wait for that, you might want to make some fixes in the bib part of the paper 

sure, will do.

Another question: can you please point me JOSSs pre-print policy? E.g. can I simultaneously submit to arxiv?

**Comment by danielskatz** [comment]
This is fine, although it's a little unusual - JOSS papers are usually short and focus on the software itself, while authors often write longer papers about the use of the software, for journals or conferences, and those longer papers are the ones that are usually submitted as pre-prints.

**Comment by faroit** [comment]
> This is fine, although it's a little unusual - JOSS papers are usually short and focus on the software itself, while authors often write longer papers about the use of the software, for journals or conferences, and those longer papers are the ones that are usually submitted as pre-prints.

maybe our contribution is a bit unusual here, indeed. We actually wrote the paper to be significanlty  longer, describing the technical details of the model (see [arxiv branch](https://github.com/sigsep/open-unmix-paper-joss/tree/arxiv)) and then shortened it to <2000 words to comply with the JOSS policy.
Since there are not many scientific contributions being made – the model is basically the distillation of multiple former methods, we therefore, really would like to stick to a JOSS-only contribution for now and will probably write a longer journal later this year, that include larger scale experiments, hence a more rigor scientific contribution. 

Now, we still want to offer a DOI for the community as quickly as possible, because we expect them to cite this paper very soon with the upcoming deadlines of the major conferences in our field.

**Comment by danielskatz** [comment]
Ok, thanks

**Comment by arokem** [comment]
Yes. I can edit this one!

**Comment by arokem** [comment]
@whedon assign arokem as editor

**Comment by whedon** [comment]
OK, the editor is arokem

**Comment by arokem** [comment]
@faroit : do you have any suggestions for reviewers?

**Comment by arokem** [comment]
👋 @bmcfee : would you be willing to review this paper for the [Journal of Open Source Software](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)?

**Comment by faroit** [comment]
Researchers close to field (audio+ML) with open-source software experience: @bmcfee  @justinsalamon @hagenw @danstowell @drscotthawley @keunwoochoi @jordipons

**Comment by bmcfee** [comment]
@arokem sure!

**Comment by arokem** [comment]
Awesome. Thanks!

**Comment by arokem** [comment]
@whedon assign @bmcfee as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @bmcfee

**Comment by arokem** [comment]
👋 @justinsalamon : would you be willing to review this paper for the [Journal of Open Source Software](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)?

**Comment by arokem** [comment]
To facilitate a quick start for the review, let's try the shotgun approach: 

@hagenw @danstowell @drscotthawley @keunwoochoi @jordipons (and @justinsalamon, in case you are interested):

Would one of you be willing to review this paper for the [Journal of Open Source Software](https://joss.theoj.org/)?

**Comment by hagenw** [comment]
I would be willing

**Comment by arokem** [comment]
Thanks @hagenw !

**Comment by arokem** [comment]
@whedon add hagenw as reviewer

**Comment by whedon** [comment]
OK, hagenw is now a reviewer

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1667. Feel free to close this issue now!

**Comment by arokem** [comment]
OK, @bmcfee and @hagenw : please head over to #1667 for your review checklists. I'll close this issue now.

**Comment by justinsalamon** [comment]
@arokem sorry, just seeing this now (I was on vacation). Let me know if you still require additional reviews.

**Comment by drscotthawley** [comment]
@arokem & @faroit Just to chime in late: I'm honored to be listed in such distinguished company! Right now I'm doing two other reviews and have a full plate otherwise, but consider me again in the future.
