### ISSUE TITLE
[PRE REVIEW]: Airbase - An airfoil files database to search, compare and plot

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1660]
**Submitting author:** @lucaspompeun (<a href="http://orcid.org/0000-0001-9625-4985">Lucas Neves</a>)
**Repository:** <a href="https://github.com/lucaspompeun/airbase" target ="_blank">https://github.com/lucaspompeun/airbase</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @lucaspompeun. **Currently, there isn't an JOSS editor assigned** to your paper.

@lucaspompeun if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1660 with the following error: 

 Error reading bibliography ./paper.bib (line 2, column 9):
unexpected "."
expecting letter, digit, white space, "#", "," or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
👋 @lucaspompeun - JOSS is a journal for research software, but this submission does not appear to be research software; it instead appears to be a database and data.  Given this, I don't think it's suitable for JOSS and suggest it be withdrawn, but if you have a different opinion and want to argue how it is suitable for JOSS, please do.

**Comment by lucaspompeun** [comment]
Hi @danielskatz - Nowadays, with the increasing of data science, databases are becoming to play a central role to some scientific areas, such as bioinformatics with [NCBI](https://www.ncbi.nlm.nih.gov/), [PDB](http://www.rcsb.org/) and others, with this increasing in mind, the airbase have the purpose of offer scientists the oportunity to acess a wide variety of dat seligs relevant data to provide a precision in new researchs at aerodesign area. I hope you understand the scientific purpose of this work :)

**Comment by danielskatz** [comment]
My concern is not the scientific value, but that JOSS is a **software** journal, and this doesn't appear to be software.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01660/joss.01660/10.21105.joss.01660.pdf)

**Comment by lucaspompeun** [comment]
I see your point. The idea was to produce the database with a web interface, to easyer the acess for scientists, since our target are physicists and engineers. The database can be used in a offline way, but I don't signalized this on README.md, it's just download the repository and open the "index.html" file. We have a future idea to update the offline repository with an API, since the current update must be manual, downloading the folder "dat".

**Comment by danielskatz** [comment]
I'm going to mark this as withdrawn for now - if you can turn it into software, please feel free to resubmit at that time.
