### ISSUE TITLE
[REVIEW]: virtualNicheR: generating virtual fundamental and realised niches for use in virtual ecology experiments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1661]
**Submitting author:** @tretherington (<a href="http://orcid.org/0000-0002-3187-075X">Thomas R Etherington</a>)
**Repository:** <a href="https://github.com/manaakiwhenua/virtualNicheR" target ="_blank">https://github.com/manaakiwhenua/virtualNicheR</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewer:** @ViniciusBRodrigues, @lsw5077
**Archive:** <a href="https://doi.org/10.7931/cae9-bt94" target="_blank">10.7931/cae9-bt94</a>

## Status

[![status](https://joss.theoj.org/papers/50d817f68b43f5516015d3efb79f83c5/status.svg)](https://joss.theoj.org/papers/50d817f68b43f5516015d3efb79f83c5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/50d817f68b43f5516015d3efb79f83c5"><img src="https://joss.theoj.org/papers/50d817f68b43f5516015d3efb79f83c5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/50d817f68b43f5516015d3efb79f83c5/status.svg)](https://joss.theoj.org/papers/50d817f68b43f5516015d3efb79f83c5)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/manaakiwhenua/virtualNicheR" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ViniciusBRodrigues & @lsw5077, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/manaakiwhenua/virtualNicheR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@tretherington) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/manaakiwhenua/virtualNicheR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@tretherington) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ViniciusBRodrigues, @lsw5077 it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@ViniciusBRodrigues, @lsw5077 - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01661/joss.01661/10.21105.joss.01661.pdf)

**Comment by ViniciusBRodrigues** [comment]
Based on the review checklist, small modifications should be done. The **A statement of need** and **Community guidelines** could be improved. The use of the software could be very wide inside ecology, but you can specify (more clearly) the target audience. 

There is no clear information about how to contribute to the software, report issues or seek support. Despite the users can do that through GitHub, you should make it clear and inform options for non-GitHub users, I think. :grin:

**Comment by arfon** [comment]
:wave: @lsw5077 - how are you getting along with your review?

**Comment by arfon** [comment]
:wave: @tretherington - please let us know when you've had a chance to update your submission based on @ViniciusBRodrigues and @lsw5077's feedback.

**Comment by tretherington** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01661/joss.01661/10.21105.joss.01661.pdf)

**Comment by tretherington** [comment]
Many thanks @ViniciusBRodrigues and @lsw5077 for your comments 😃 !

I've updated things such that:

1. I have included a [Community guidelines](https://github.com/manaakiwhenua/virtualNicheR#community-guidelines) section in the README so folks know how best to report bugs, seek help, and suggest/make developments.  Apologies from me for neglecting to include that first time around 😞
2. I have reworded why the software is needed in the paper to try and make the need stronger and clearer.  You were both right that we had neglected to include that need in the README, so that has now been added there too.
3. I've also inserted what I think is the best easily accessed general reference to species-environment models in the paper so anyone interested to know more about their importance can look into things further.

@arfon I've also got the excellent whedon robot to regenerate the pdf, so hopefully everything should be up to date for you

**Comment by lsw5077** [comment]
The revisions look great! Nice work! I have no further comments.

**Comment by arfon** [comment]
> The revisions look great! Nice work! I have no further comments.

Thanks for the quick responses @tretherington & @lsw5077. @lsw5077 - if the criteria have been met, can you check off the final checkboxes for your review please?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01661/joss.01661/10.21105.joss.01661.pdf)

**Comment by arfon** [comment]
@tretherington - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by tretherington** [comment]
@arfon I've created a new release v1.0.1 and I have archived the software in my institution's data store here: [https://datastore.landcareresearch.co.nz/dataset/virtualnicher](https://datastore.landcareresearch.co.nz/dataset/virtualnicher) which the DOI of [10.7931/cae9-bt94](https://doi.org/10.7931/cae9-bt94)

Do let me know if you need anything else! 😃

**Comment by arfon** [comment]
@whedon set 10.7931/cae9-bt94 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.7931/cae9-bt94" target="_blank">10.7931/cae9-bt94</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/981

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/981, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1661 with the following error:

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by arfon** [comment]
Looks like Whedon's having a bad day... Apologies for all the noise on this thread.

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1176987029537722368) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/982
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01661](https://doi.org/10.21105/joss.01661)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@ViniciusBRodrigues, @lsw5077 - many thanks for your reviews here ✨ 

@tretherington - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01661/status.svg)](https://doi.org/10.21105/joss.01661)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01661">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01661/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01661/status.svg
   :target: https://doi.org/10.21105/joss.01661
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01661/status.svg)](https://doi.org/10.21105/joss.01661)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by tretherington** [comment]
Thanks @arfon @ViniciusBRodrigues @lsw5077 for an excellent and useful review process.

And I've just signed up as a reviewer in the hope this journal has a long life! 😄 🍾
