### ISSUE TITLE
[REVIEW]: thurstonianIRT: Thurstonian IRT Models in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1662]
**Submitting author:** @paul-buerkner (<a href="http://orcid.org/0000-0001-5765-8995">Paul-Christian Bürkner</a>)
**Repository:** <a href="https://github.com/paul-buerkner/thurstonianIRT" target ="_blank">https://github.com/paul-buerkner/thurstonianIRT</a>
**Version:** 0.10.0
**Editor:** @cMadan
**Reviewer:** @tomfaulkenberry, @russellpierce
**Archive:** <a href="https://doi.org/10.5281/zenodo.3515749" target="_blank">10.5281/zenodo.3515749</a>

## Status

[![status](https://joss.theoj.org/papers/d4724cba82df22008e8f1a58cd5faf96/status.svg)](https://joss.theoj.org/papers/d4724cba82df22008e8f1a58cd5faf96)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d4724cba82df22008e8f1a58cd5faf96"><img src="https://joss.theoj.org/papers/d4724cba82df22008e8f1a58cd5faf96/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d4724cba82df22008e8f1a58cd5faf96/status.svg)](https://joss.theoj.org/papers/d4724cba82df22008e8f1a58cd5faf96)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/paul-buerkner/thurstonianIRT" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@tomfaulkenberry & @russellpierce, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @cMadan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/paul-buerkner/thurstonianIRT">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.10.0
- [x] **Authorship:** Has the submitting author (@paul-buerkner) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/paul-buerkner/thurstonianIRT">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.10.0
- [x] **Authorship:** Has the submitting author (@paul-buerkner) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @tomfaulkenberry, @russellpierce it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01662/joss.01662/10.21105.joss.01662.pdf)

**Comment by russellpierce** [comment]
@tomfaulkenberry do you have a copy of Mplus that you can use to evaluate the functional claims of the authors? I do not, and have limited familiarity, so I'm prone to leave that entirely with you. Okay?

**Comment by paul-buerkner** [comment]
In the worst case I may also remove the Mplus part from the paper if it is
hard to get a copy of it. After all it is not open source or free to use.

Russell S. Pierce <notifications@github.com> schrieb am Do., 22. Aug. 2019,
05:08:

**Comment by tomfaulkenberry** [comment]
Sorry for my late addition here...no, I do not have Mplus either.  I do like Paul's idea of just removing the Mplus part, as it does go against the spirit of open source software.  

We just started our Fall term this week, so I am a bit behind on doing this full review.  I will have it done in the coming week, though.

**Comment by paul-buerkner** [comment]
I will remove the Mplus part from the paper in the next few days but feel free to review the rest already and just ignore the Mplus part.

**Comment by tomfaulkenberry** [comment]
I have completed my review of thurstonianIRT.  I find it to be a powerful, well-documented package that will likely be of great use to many researchers interested in IRT modeling on forced-choice questionnaires.  I am impressed by the simple interface, particularly as it calls Stan "under the hood" without the need for a beginner to get too deep into Stan coding.

Only one issue came up for me when testing the software.  I could not get the `fit_TIRT_lavaan` function to work (either for the CRAN version or the developer version).  I've logged this issue here: https://github.com/paul-buerkner/thurstonianIRT/issues/3#issue-488603450.  Please feel free to ask me more questions about setup, etc., and I'll be happy to send relevant details.

Once this issue is cleared up for me, I will be more than happy to endorse publication.

Tom

**Comment by paul-buerkner** [comment]
Thanks for the comments, @tomfaulkenberry! The issue you raised should be fixed now.

With regard to Mplus, I realize that I actually don't mention it in the paper already so
there may not be any need to change. Still, thurstonianIRT itself needs to support Mplus
for comparison and validation of former implementations which were all written in Mplus.
Since I don't make any claims about it in the paper, I hope it's fine that the reviewers cannot test the Mplus implementation of thurstonianIRT themselves.

**Comment by tomfaulkenberry** [comment]
Thanks Paul...I closed the issue referenced above.  All has checked out, and I am quite satisfied with everything.  My review is now complete!

**Comment by cMadan** [comment]
@russellpierce, how is your review progressing? 

@tomfaulkenberry, thank you for reviewing this submission!

**Comment by cMadan** [comment]
@russellpierce, any update? Thanks!

**Comment by russellpierce** [comment]
@cMadan Spinning up, hoping to do work on this today - which will be made manifest by me actually doing it.  Apologies to you and to Paul for the delay.

**Comment by russellpierce** [comment]
Pending the completion of https://github.com/paul-buerkner/thurstonianIRT/issues/9 and https://github.com/paul-buerkner/thurstonianIRT/issues/4  I too am now quite satisfied with everything. My review is now complete and I endorse publication!

**Comment by paul-buerkner** [comment]
Thank you @russellpierce for your very thorough and helpful review! I have incorporated all the requested changes and think the software and related paper are now ready.

**Comment by paul-buerkner** [comment]
With the reviews now done (I think?) what are the next steps in the submission process?

**Comment by cMadan** [comment]
@russellpierce, thank you for reviewing this submission!

@paul-buerkner, I have to do some final checks now, but we're almost done!

**Comment by cMadan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01662/joss.01662/10.21105.joss.01662.pdf)

**Comment by cMadan** [comment]
@paul-buerkner, can you look over your bib file? It looks like there are a few mistakes to fix (missing volume/pages, incorrect page numbers, missing capitalisation).

**Comment by paul-buerkner** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01662/joss.01662/10.21105.joss.01662.pdf)

**Comment by paul-buerkner** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01662/joss.01662/10.21105.joss.01662.pdf)

**Comment by paul-buerkner** [comment]
Thanks @cMadan! The bib file should be correct now.

**Comment by cMadan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1177/0013164410375112 is OK
- 10.1177/0013164419832063 is OK
- 10.18637/jss.v076.i01 is OK
- 10.18637/jss.v048.i02 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by cMadan** [comment]
@paul-buerkner, everything looks good to me!

To move forward with accepting your submission, there are a few last things to take care of:

- [ ] Make a tagged release of your software, and list the version tag of the archived version here. 
- [ ] Archive the reviewed software in Zenodo 
- [ ] Check the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] List the Zenodo DOI of the archived version here.

You may find this helpful: https://guides.github.com/activities/citable-code/

**Comment by paul-buerkner** [comment]
Thanks!

Tagged release is 0.10.0 and can be found at https://github.com/paul-buerkner/thurstonianIRT/releases/tag/v0.10.0

Zenodo link is: https://github.com/paul-buerkner/thurstonianIRT/releases/tag/v0.10.0

Zenodo DOI is 10.5281/zenodo.3515749

**Comment by cMadan** [comment]
@whedon set 0.10.0 as version

**Comment by whedon** [comment]
OK. 0.10.0 is the version.

**Comment by cMadan** [comment]
@whedon set 10.5281/zenodo.3515749 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3515749" target="_blank">10.5281/zenodo.3515749</a> is the archive.

**Comment by cMadan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1177/0013164410375112 is OK
- 10.1177/0013164419832063 is OK
- 10.18637/jss.v076.i01 is OK
- 10.18637/jss.v048.i02 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1041

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1041, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by cMadan** [comment]
@openjournals/joss-eics, I think we're all set to accept here!

**Comment by kthyng** [comment]
@cMadan thanks for your thorough finishing up! Made it easy for me :)

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1187041115700191232) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1044
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01662](https://doi.org/10.21105/joss.01662)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Congratulations to @paul-buerkner on your JOSS submission!!

Thank you to @tomfaulkenberry and @russellpierce for your time and expertise as reviewers, and thanks to @cMadan for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01662/status.svg)](https://doi.org/10.21105/joss.01662)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01662">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01662/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01662/status.svg
   :target: https://doi.org/10.21105/joss.01662
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01662/status.svg)](https://doi.org/10.21105/joss.01662)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by paul-buerkner** [comment]
Thank you so much for your thorough reviewing and editing!!!

whedon <notifications@github.com> schrieb am Mi., 23. Okt. 2019, 19:25:
