### ISSUE TITLE
[REVIEW]: Rudi: Lightweight image converter and dataset augmentor

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1664]
**Submitting author:** @liashchynskyi (<a href="http://orcid.org/0000-0002-3920-6239">Petro Liashchynskyi</a>)
**Repository:** <a href="https://github.com/liashchynskyi/rudi" target ="_blank">https://github.com/liashchynskyi/rudi</a>
**Version:** 1.0
**Editor:** @arfon
**Reviewer:** @casperdcl, @nnadeau
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/347e879c449b4346e53666693c3122fd/status.svg)](https://joss.theoj.org/papers/347e879c449b4346e53666693c3122fd)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/347e879c449b4346e53666693c3122fd"><img src="https://joss.theoj.org/papers/347e879c449b4346e53666693c3122fd/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/347e879c449b4346e53666693c3122fd/status.svg)](https://joss.theoj.org/papers/347e879c449b4346e53666693c3122fd)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/liashchynskyi/rudi" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@casperdcl & @nnadeau, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/liashchynskyi/rudi">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (1.0)?
- [x] **Authorship:** Has the submitting author (@liashchynskyi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/liashchynskyi/rudi">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (1.0)?
- [ ] **Authorship:** Has the submitting author (@liashchynskyi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @casperdcl, @nnadeau it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01664/joss.01664/10.21105.joss.01664.pdf)

**Comment by arfon** [comment]
@casperdcl, @nnadeau - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by casperdcl** [comment]
# Review

Thought I'd be über quick about this, considering how small the work is it was very easy to review.

## A statement of need

- https://github.com/liashchynskyi/rudi/blame/88b3ed52ef557cba9f2f4db9280c861caa0b86d1/paper/paper.md#L39-L566: Excessive repetition defining the concept of "data augmentation" and justifying its existence, which doesn't seem to a point which needs debate.
- The package (*Rudi*) lists *Augmentor* (https://github.com/mdbloice/Augmentor, http://augmentor.readthedocs.io/) as a requirement. It would appear that *Augmentor*'s statement of need is essentially identical to Rudi's. This, combined with the fact that *Rudi* is an extremely tiny wrapper package (115 lines of python code excluding `setup.py` and blanks, and only 76 if counting `augmentor.py` and `converter.py`) with a very short development history (~1 month) makes it seem far better placed to be a pull request on *Augmentor* rather than a stand-alone package.

## Installation instructions

- Dependencies are only listed in `setup.py`. Ideally they should also appear in `README.md` and/or `requirements.txt`.

## Functionality documentation

- Currently only provided by installing and running help on the executable.

## Automated tests

- There are no tests.

## Community guidelines

- There are no guidelines.

## Overall recommendation

- Convert into a small sub-package of https://github.com/mdbloice/Augmentor and open a PR there

**Comment by arfon** [comment]
Thanks for your review @casperdcl. It sounds like this package might fall foul of our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) that explicitly call out 'minor utilities' as not allowable in JOSS:

> - The software should be feature-complete (no half-baked solutions) and designed for maintainable extension (not one-off modifications). Minor ‘utility’ packages, including ‘thin’ API clients, are not acceptable.

In your opinion does this package fall into that category?

**Comment by casperdcl** [comment]
@arfon yes, while it may be a useful package it really does seem to be a thin API wrapper that could be present in *Augmentor*.

**Comment by arfon** [comment]
OK thanks @casperdcl. 

@nnadeau - could you give your opinion on [this question](https://github.com/openjournals/joss-reviews/issues/1664#issuecomment-523236126) too?

**Comment by liashchynskyi** [comment]
@casperdcl so what? No one can use dependencies, man? 😄 

@arfon close this issue

**Comment by casperdcl** [comment]
@liashchynskyi I don't have a problem with using dependencies (things like [nteract/papermill](https://github.com/nteract/papermill) even recommend you [extend them by only writing a minimal `setup.py` file and nothing else!](https://papermill.readthedocs.io/en/latest/extending-entry-points.html)), it's just as @arfon says not sure if it's appropriate for a JOSS publication.

**Comment by liashchynskyi** [comment]
ok, close the issue 😁 good luck, guys

Ср, 21 серп. 2019 16:06 користувач Casper da Costa-Luis <
notifications@github.com> пише:

**Comment by liashchynskyi** [comment]
oj, just close this issue 😀 good luck, guys

**Comment by arfon** [comment]
It sounds like you'd like to withdraw this submission @liashchynskyi? Can you confirm? If so, I'll go ahead and close this.

**Comment by nnadeau** [comment]
@arfon , I'm in agreement with @casperdcl. This repo is nothing more than a thin CLI wrapper.

**Comment by arfon** [comment]
OK thanks for your reviews here @casperdcl & @nnadeau 

@liashchynskyi - we'd welcome a resubmission in the future if this package were extended/made more comprehensive such that it met our [submission criteria](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).

**Comment by liashchynskyi** [comment]
ok, thanks you all, guys 😀
