### ISSUE TITLE
[REVIEW]: Open-Unmix - A Reference Implementation for Music Source Separation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1667]
**Submitting author:** @faroit (<a href="http://orcid.org/0000-0002-2534-1165">Fabian-Robert Stöter</a>)
**Repository:** <a href="https://github.com/sigsep/open-unmix-paper-joss" target ="_blank">https://github.com/sigsep/open-unmix-paper-joss</a>
**Version:** v1.0.0
**Editor:** @arokem
**Reviewer:** @bmcfee, @hagenw
**Archive:** <a href="https://doi.org/10.5281/zenodo.3402103" target="_blank">10.5281/zenodo.3402103</a>

## Status

[![status](https://joss.theoj.org/papers/571753bc54c5d6dd36382c3d801de41d/status.svg)](https://joss.theoj.org/papers/571753bc54c5d6dd36382c3d801de41d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/571753bc54c5d6dd36382c3d801de41d"><img src="https://joss.theoj.org/papers/571753bc54c5d6dd36382c3d801de41d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/571753bc54c5d6dd36382c3d801de41d/status.svg)](https://joss.theoj.org/papers/571753bc54c5d6dd36382c3d801de41d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/sigsep/open-unmix-paper-joss" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@bmcfee & @hagenw, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sigsep/open-unmix-paper-joss">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@faroit) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sigsep/open-unmix-paper-joss">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@faroit) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @bmcfee, @hagenw it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01667/joss.01667/10.21105.joss.01667.pdf)

**Comment by bmcfee** [comment]
@arokem just checking over the COI policy -- the main author has contributed to some software projects that i maintain (and have published on).  It's not totally obvious to me whether that constitutes a COI.  I don't think this would impede my ability to review, but full disclosure and all.

**Comment by arokem** [comment]
Just to clarify: has the main author been a co-author on any of the papers that you have published on your software?

**Comment by bmcfee** [comment]
> has the main author been a co-author on any of the papers that you have published on your software?

Nope.

**Comment by arokem** [comment]
In my reading, this does not constitute COI. If you feel at all uncomfortable, I'd be happy to look for another reviewer. Otherwise, I think that your statement that this association will not impede your ability to review the article is sufficient for you to check that box and move ahead.

**Comment by bmcfee** [comment]
Cool, we're in agreement then.  Thanks!

**Comment by bmcfee** [comment]
https://github.com/sigsep/open-unmix-paper-joss/issues/2 - on version numbers

**Comment by bmcfee** [comment]
https://github.com/sigsep/open-unmix-paper-joss/issues/3 - on including source code and a related issue with the docs

**Comment by bmcfee** [comment]
https://github.com/sigsep/open-unmix-paper-joss/issues/4 - on performance

**Comment by bmcfee** [comment]
https://github.com/sigsep/open-unmix-paper-joss/issues/5 - on documentation/API

**Comment by bmcfee** [comment]
https://github.com/sigsep/open-unmix-paper-joss/issues/6 - on community guidelines

**Comment by hagenw** [comment]
https://github.com/sigsep/open-unmix-paper-joss/issues/9 - on testing

**Comment by faroit** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01667/joss.01667/10.21105.joss.01667.pdf)

**Comment by faroit** [comment]
we would like to officially release the software next week. It would be great if we could provide a DOI soon so that researchers can use this as a baseline e.g. for the upcoming [ICASSP](https://2020.ieeeicassp.org/authors/important-dates/). 

@hagenw @bmcfee thank you again for your time and help. It would be great to know for us if could tell us when you find time to complete the review so we know if we might want to prepare a preprint.

**Comment by hagenw** [comment]
I think that should be possible. I'm done with the review of all the written parts and will install and test the software on Monday or Tuesday. If everything works fine then the review should be finished in time.

**Comment by hagenw** [comment]
https://github.com/sigsep/open-unmix-paper-joss/issues/11

**Comment by hagenw** [comment]
https://github.com/sigsep/open-unmix-paper-joss/issues/12

**Comment by bmcfee** [comment]
Everything looks good on my end, checkboxes completed.

**Comment by hagenw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01667/joss.01667/10.21105.joss.01667.pdf)

**Comment by hagenw** [comment]
All fine from my side, also all checkboxes completed.

**Comment by arokem** [comment]
@whedon on check references

**Comment by arokem** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1109/ICASSP.2011.5946809 is OK
- 10.5281/zenodo.3269749 is OK
- 10.1109/MSP.2018.2875349 is OK
- 10.5281/zenodo.3338373 is OK
- 10.5281/zenodo.3382104 is OK
- 10.5281/zenodo.3370486 is OK
- 10.5281/zenodo.3370489 is OK
- 10.5281/zenodo.3261102 is OK
- 10.5281/zenodo.3271451 is OK
- 10.1109/ICASSP.2019.8683251 is OK
- 10.1109/ICASSP.2019.8683555 is OK
- 10.1109/TASL.2011.2172425 is OK
- 10.1007/978-3-319-53547-0_25 is OK
- 10.1016/j.sigpro.2011.10.007 is OK
- 10.1007/978-3-642-28551-6_51 is OK
- 10.1109/MLSP.2013.6661988 is OK
- 10.1007/978-3-319-22482-4_45 is OK
- 10.1007/978-3-319-53547-0_31 is OK
- 10.1007/978-3-319-93764-9_28 is OK
- 10.5281/zenodo.1117372 is OK
- 10.1109/MSP.2018.2874719 is OK
- 10.1109/ICASSP.2017.7952158 is OK
- 10.1109/ICASSP.2015.7178348 is OK
- 10.1109/TASLP.2016.2580946 is OK
- 10.1109/ASRU.2015.7404834 is OK
- 10.1109/JSTSP.2019.2904183 is OK
- 10.21437/Interspeech.2018-1773 is OK
- 10.1109/MSP.2018.2875349 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by faroit** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01667/joss.01667/10.21105.joss.01667.pdf)

**Comment by faroit** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01667/joss.01667/10.21105.joss.01667.pdf)

**Comment by faroit** [comment]
@arokem I did some last little update on the bibliography and I think we are good here. Please tell me what the next steps are to proceed.

**Comment by arokem** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1109/ICASSP.2011.5946809 is OK
- 10.5281/zenodo.3386463 is OK
- 10.1109/MSP.2018.2875349 is OK
- 10.5281/zenodo.3338373 is OK
- 10.5281/zenodo.3382104 is OK
- 10.5281/zenodo.3370486 is OK
- 10.5281/zenodo.3370489 is OK
- 10.5281/zenodo.3261102 is OK
- 10.5281/zenodo.3271451 is OK
- 10.1109/ICASSP.2019.8683251 is OK
- 10.1109/ICASSP.2019.8683555 is OK
- 10.1109/TASL.2011.2172425 is OK
- 10.1007/978-3-319-53547-0_25 is OK
- 10.1016/j.sigpro.2011.10.007 is OK
- 10.1007/978-3-642-28551-6_51 is OK
- 10.1109/MLSP.2013.6661988 is OK
- 10.1007/978-3-319-22482-4_45 is OK
- 10.1007/978-3-319-53547-0_31 is OK
- 10.1007/978-3-319-93764-9_28 is OK
- 10.5281/zenodo.1117372 is OK
- 10.1109/MSP.2018.2874719 is OK
- 10.1109/ICASSP.2017.7952158 is OK
- 10.1109/ICASSP.2015.7178348 is OK
- 10.1109/TASLP.2016.2580946 is OK
- 10.1109/ASRU.2015.7404834 is OK
- 10.1109/JSTSP.2019.2904183 is OK
- 10.21437/Interspeech.2018-1773 is OK
- 10.1109/MSP.2018.2875349 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arokem** [comment]
@faroit : At this point, could you please make a new release of the main repo that includes all of the changes that have resulted from the review? Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive. For the archive version, please make sure that:

- The title of the archive is the same as the JOSS paper title
- The authors of the archive are the same as the JOSS paper authors

**Comment by faroit** [comment]
@arokem all done. Here is the DOI on zenodo: 10.5281/zenodo.3402103

**Comment by arokem** [comment]
@whdeon set 10.5281/zenodo.3402103 as archive

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.3402103 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3402103" target="_blank">10.5281/zenodo.3402103</a> is the archive.

**Comment by arokem** [comment]
@openjournals/joss-eics : I believe this is ready for your review

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/954

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/954, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1170736846327992320) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/955
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01667](https://doi.org/10.21105/joss.01667)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@bmcfee, @hagenw - many thanks for your reviews here and to @arokem for editing this submission ✨ 

@faroit - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01667/status.svg)](https://doi.org/10.21105/joss.01667)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01667">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01667/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01667/status.svg
   :target: https://doi.org/10.21105/joss.01667
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01667/status.svg)](https://doi.org/10.21105/joss.01667)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by bmcfee** [comment]
Congrats @faroit !

**Comment by faroit** [comment]
@arokem @bmcfee @hagenw Thanks all for your great input. The whole process is very well designed and to be honest, this was the first time I enjoyed submitting a paper. So I am definitely consider to help out and review.
