### ISSUE TITLE
[PRE REVIEW]: The Walrus: the fastest calculation of hafnians, Hermite polynomials and Gaussian boson sampling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1668]
**Submitting author:** @nquesada (<a href="http://orcid.org/0000-0002-0175-1688">Nicolás Quesada</a>)
**Repository:** <a href="https://github.com/xanaduAI/thewalrus" target ="_blank">https://github.com/xanaduAI/thewalrus</a>
**Version:** 0.7.0
**Editor:** @katyhuff
**Reviewers:** @PhilipVinc, @poulson

**Author instructions**

Thanks for submitting your paper to JOSS @nquesada. **Currently, there isn't an JOSS editor assigned** to your paper.

@nquesada if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kyleniemeyer** [comment]
Hi @VivianePons, can you edit this submission?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01668/joss.01668/10.21105.joss.01668.pdf)

**Comment by kyleniemeyer** [comment]
@poulson can you edit this submission?

**Comment by nquesada** [comment]
Hey @kyleniemeyer thanks for helping out in finding an editor for our submission!
I assume I can post here the people I can think could be helpful in reviewing, correct?

**Comment by kyleniemeyer** [comment]
@nquesada sure, suggestions for potential reviewers are always welcome!

**Comment by nquesada** [comment]
Great! From the list of potential reviewers JOSS has, I think either @goerz or @PhilipVinc would make good reviewers given their background in quantum optics.

**Comment by goerz** [comment]
I'm currently reviewing another paper, so unfortunately I can't take this on at the moment

**Comment by PhilipVinc** [comment]
I am available for reviewing the paper.

**Comment by kyleniemeyer** [comment]
Thanks @PhilipVinc!

**Comment by kyleniemeyer** [comment]
@whedon add @PhilipVinc as reviewer

**Comment by nquesada** [comment]
Thanks @PhilipVinc !

**Comment by labarba** [comment]
@whedon assign @poulson as editor

**Comment by whedon** [comment]
OK, the editor is @poulson

**Comment by poulson** [comment]
Oh my -- this is my kind of submission, and even local to Toronto! I apologize for the delay and -- reading through it -- am immediately curious about the interpretations of combining the halfnian generalization of the permanent with the immanantal generalization -- via characters of the symmetric group -- of permanents and determinants. I suppose one would just introduce an arbitrary character of the symmetric group rather than chi(sigma) == 1 in the case of the halfnian.

I will send out invitations to reviewers as soon as I finish reading the paper.

**Comment by nquesada** [comment]
Hey @poulson, thanks for agreeing to be editor of our paper; also, very happy to hear you find our paper interesting!

**Comment by poulson** [comment]
Hi Max Scheurer (https://github.com/maxscheurer): given your CPPE project (https://github.com/maxscheurer/cppe), which exposes a python interface for an Eigen-based C++ quantum chemistry simulation, it looks like your expertise would be helpful for reviewing this submission.

While the submission is more focused around combinatorial determinant calculations of structured matrices, my guess is that this isn't too much of a stretch for you.

Please let me know if you have the time and interest to review this submission, and would feel confident doing so.

**Comment by maxscheurer** [comment]
Hi, I think this is out of my field of expertise, so I don't feel capable to review the manuscript. Sorry...

**Comment by PhilipVinc** [comment]
@poulson, should you ask Whedon to start the review issue so that I can fill the checklist?

I have a few minor comments on this library, especially on the documentation, which otherwise seems a very fine piece of software. Normally I would leave those on the Review issue?

**Comment by katyhuff** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by katyhuff** [comment]
@whedon add @poulson as reviewer

**Comment by whedon** [comment]
OK, @poulson is now a reviewer

**Comment by katyhuff** [comment]
Hi Folks (@PhilipVinc @nquesada ), I am stepping in as editor because this content is fairly niche, but Jack (@paulson)and I believe he will be an excellent second reviewer for this work. It was a great idea on Jack's part, and I'm happy to take over handing this one. Now that we have two reviewers and one editor, let's get started on the review.

**Comment by katyhuff** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1705. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Ok folks, let's move over to #1705 , where @PhilipVinc and @poulson will conduct the review.
