### ISSUE TITLE
[REVIEW]: bíogo: a simple high-performance bioinformatics toolkit for the Go language

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#167]
**Submitting author:** kortschak (<a href="http://orcid.org/0000-0001-8295-2301">Robert Daniel Kortschak</a>)
**Repository:** <a href="https://github.com/biogo/biogo" target ="_blank">https://github.com/biogo/biogo</a>
**Version:** v1.0.0
**Editor:** @pjotrp
**Reviewer:** @brentp
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.292939" target="_blank">10.5281/zenodo.292939</a>

## Status

[![status](http://joss.theoj.org/papers/d6325420e7ab6ac2d7720606c504c0fd/status.svg)](http://joss.theoj.org/papers/d6325420e7ab6ac2d7720606c504c0fd)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d6325420e7ab6ac2d7720606c504c0fd"><img src="http://joss.theoj.org/papers/d6325420e7ab6ac2d7720606c504c0fd/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d6325420e7ab6ac2d7720606c504c0fd/status.svg)](http://joss.theoj.org/papers/d6325420e7ab6ac2d7720606c504c0fd)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/biogo/biogo" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/biogo/biogo">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (kortschak) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @brentp it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by brentp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by brentp** [comment]
This LGTM to me based on the criteria above and here: http://joss.theoj.org/about#reviewer_guidelines

I'm unclear what more I should do.

**Comment by pjotrp** [comment]
Thanks @brentp for your review! 

@kortschak the paper.md is short and concise, but I would suggest to add some references to similar projects (biopython, biojava, bioruby, biorust) as a clarification of what the software aims to do and give it some historic reference (it also helps people to find you!). You can also add particular strengths of this project (at this point in time) so as to advertise the work to new comers and (I dare say) some performance metrics to underwrite your claims. Also add references to documentation so that people who want to dig deeper have a single click.

Note that these are merely suggestions to strengthen the scientific side of the paper and make it easy on the reader to understand what you are doing. We can accept the paper *as is* - so if you want to leave it like this that is fine too.

**Comment by kortschak** [comment]
@pjotrp I can refer explicitly to the original bioRxiv paper as that more fully details the reasoning behind the project and refers to other projects. The link to that is http://biorxiv.org/content/early/2014/05/12/005033 Do you think that would be satisfactory?

**Comment by pjotrp** [comment]
Good idea. After that ping @arfon that we complete acceptance.

**Comment by dadelson** [comment]
@kortschak excellent.

**Comment by kortschak** [comment]
@arfon This is ready. Thank you.

**Comment by pjotrp** [comment]
I believe @arfon we can accept this paper.

**Comment by arfon** [comment]
> I believe @arfon we can accept this paper.

👍 

@kortschak - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by kortschak** [comment]
@arfon I would like to hold off until the release of the next version of the host compiler as there is an outstanding test suite failure with the current release candidate that should be fixed in that release. When Go1.8 is release I will update the test matrix and tag a minor version change, pinging @brentp and @pjotrp to ensure things have been done correctly. Is that OK with you?

**Comment by pjotrp** [comment]
No problem - just tell us when you are ready.

**Comment by kortschak** [comment]
@brentp @pjotrp The required changes have now been made.

 http://doi.org/10.5281/zenodo.292939

**Comment by pjotrp** [comment]
@arfon next stop

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.292939 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.292939" target="_blank">10.5281/zenodo.292939</a> is the archive.

**Comment by arfon** [comment]
@brentp & @pjotrp - many thanks for reviewing and editing this submission ✨ 

@kortschak - your paper is now accepted into JOSS. The DOI is http://dx.doi.org/10.21105/joss.00167 🚀 ⚡️ 💥
