### ISSUE TITLE
[PRE REVIEW]: qnm: A Python package for calculating Kerr quasinormal modes, separation constants, and spherical-spheroidal mixing coefficients

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1671]
**Submitting author:** @duetosymmetry (<a href="http://orcid.org/0000-0001-7559-9597">Leo C. Stein</a>)
**Repository:** <a href="https://github.com/duetosymmetry/qnm" target ="_blank">https://github.com/duetosymmetry/qnm</a>
**Version:** 0.3.0
**Editor:** @xuanxu
**Reviewers:** @mattpitkin, @duncanmmacleod

**Author instructions**

Thanks for submitting your paper to JOSS @duetosymmetry. **Currently, there isn't an JOSS editor assigned** to your paper.

@duetosymmetry if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kyleniemeyer** [comment]
Hi @xuanxu, can you edit this submission?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01671/joss.01671/10.21105.joss.01671.pdf)

**Comment by duetosymmetry** [comment]
I could suggest @mattpitkin as a domain expert for review.

**Comment by mattpitkin** [comment]
I'm happy to review this.

**Comment by xuanxu** [comment]
@whedon assign @xuanxu as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by xuanxu** [comment]
Thanks, @mattpitkin! I'll assign you now.
I'll start the review issue once I find the second reviewer, stay tuned!

**Comment by xuanxu** [comment]
@whedon assign @mattpitkin as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mattpitkin

**Comment by xuanxu** [comment]
:wave: @duncanmmacleod: would you be willing to review this paper? I think your knowledge of Python and gravitational waves makes you a great fit for this submission.

**Comment by xuanxu** [comment]
:wave: @zonca: would you be willing to review this paper? Your experience with Python and cosmology would come in handy here.

**Comment by duncanmmacleod** [comment]
> 👋 @duncanmmacleod: would you be willing to review this paper? I think your knowledge of Python and gravitational waves makes you a great fit for this submission.

Yes, I am happy to review, but will not able to read or contribute anything for at least two (2) weeks due to existing commitments. If you're happy to wait, I'm happy to get to it after September 9.

**Comment by xuanxu** [comment]
Thanks @duncanmmacleod! Yes, that is ok. I'll start the review issue now, and you can join later (I'll set a reminder for September 10th).

**Comment by xuanxu** [comment]
@whedon add @duncanmmacleod as reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by xuanxu** [comment]
@mattpitkin, @duncanmmacleod  - please head over to #1683 where the review will take place.
