### ISSUE TITLE
[PRE REVIEW]: BotSlayer: real-time detection of bot amplification on Twitter

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1672]
**Submitting author:** @yangkcatiu (<a href="http://orcid.org/0000-0003-4627-9273">Kai-Cheng Yang</a>)
**Repository:** <a href="https://github.com/IUNetSci/BotSlayer-CE" target ="_blank">https://github.com/IUNetSci/BotSlayer-CE</a>
**Version:** v1.0.0
**Editor:** @arokem
**Reviewers:** mkearney, nkratzke

**Author instructions**

Thanks for submitting your paper to JOSS @yangkcatiu. **Currently, there isn't an JOSS editor assigned** to your paper.

@yangkcatiu if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1672 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/author.rb:33:in `strip_footnotes': undefined method `[]' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/author.rb:13:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:191:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:191:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:188:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:188:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:91:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
Hi @alexhanna, do you have bandwidth to take on this submission?

**Comment by kyleniemeyer** [comment]
@yangkcatiu I think this PR should fix the paper compilation issue: https://github.com/IUNetSci/BotSlayer-CE/pull/11

**Comment by alexhanna** [comment]
I don't quite have the bandwidth for this right now.

**Comment by labarba** [comment]
👋  @yangkcatiu 
The README says:
> The "CE" version of BotSlayer is not meant for research
... which would imply this software is not in-scope for a JOSS publication. JOSS explicitly publishes research software.

**Comment by filmenczer** [comment]
We apologize for the misleading warning. We eliminated it and updated the paper to clarify that the software is indeed ready for research, but depending on the specific application domain, users may wish to plug in more appropriate (simpler or more sophisticated) bot detection algorithms.

We can also suggest a few potential reviewers: @mkearney, @jboynyc, @soodoku, @rmhogervorst, @Ohmaddi.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01672/joss.01672/10.21105.joss.01672.pdf)

**Comment by labarba** [comment]
👋 @arokem — Could you handle this submission as editor?
"BotSlayer: real-time detection of bot amplification on Twitter"
Repository: https://github.com/IUNetSci/BotSlayer-CE

**Comment by arokem** [comment]
Yeah. I can take this one.

**Comment by arokem** [comment]
@whedon assign arokem as editor

**Comment by whedon** [comment]
OK, the editor is arokem

**Comment by arokem** [comment]
👋 @mkearney : would you be willing to review this article for the [Journal of Open Source Software](https://joss.theoj.org/)?

**Comment by arokem** [comment]
👋 @nkratzke : would you be willing to review this article for the [Journal of Open Source Software](https://joss.theoj.org/)?

**Comment by nkratzke** [comment]
Yes, I can do this review. Let me know how to submit it to you.

**Comment by arokem** [comment]
@nkratzke : thanks! Once I have one more reviewer, I will start the review as a separate issue here. You will then have a list of items to check off. For more information, please take a look at the [reviewer guide](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)

**Comment by arokem** [comment]
👋 @jboynyc : would you be willing to review this article for the [Journal of Open Source Software](https://joss.theoj.org/)?

**Comment by mkearney** [comment]
I can review as well!

**Comment by arokem** [comment]
@whedon assign mkearney as reviewer

**Comment by whedon** [comment]
OK, the reviewer is mkearney

**Comment by arokem** [comment]
@whedon add nkratzke as reviewer

**Comment by whedon** [comment]
OK, nkratzke is now a reviewer

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1706. Feel free to close this issue now!

**Comment by arfon** [comment]
@arokem - looks like you forgot the `@` at the start of these reviewer handles. Ideally Whedon should be able to handle this more gracefully. I'll go ahead and fix this up for you.

**Comment by jboynyc** [comment]
> wave @jboynyc : would you be willing to review this article for the [Journal of Open Source Software](https://joss.theoj.org/)?

If you still need a review, I'll take a look.

**Comment by arokem** [comment]
@jboynyc : thanks for replying here! I think we're all set for now, but if things come up, I might call on you later. Thanks again!

**Comment by jboynyc** [comment]
cool. sure, happy to be of service in the future.
