### ISSUE TITLE
[PRE REVIEW]: EoN (Epidemics on Networks), software for simulation, analytic approximation, and analysis of epidemics on networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1673]
**Submitting author:** @joelmiller (<a href="http://orcid.org/0000-0003-4426-0405">Joel Miller</a>)
**Repository:** <a href="https://github.com/springer-math/Mathematics-of-Epidemics-on-Networks" target ="_blank">https://github.com/springer-math/Mathematics-of-Epidemics-on-Networks</a>
**Version:** v1.0.8
**Editor:** @lpantano
**Reviewers:** @acolum, @pholme

**Author instructions**

Thanks for submitting your paper to JOSS @joelmiller. **Currently, there isn't an JOSS editor assigned** to your paper.

@joelmiller if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1673 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1673/docs/paper/paper.md): mapping values are not allowed in this context at line 21 column 9 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:115:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
Hi @lpantano, could you edit this submission?

**Comment by kyleniemeyer** [comment]
@joelmiller this PR should fix the paper compilation issue: https://github.com/springer-math/Mathematics-of-Epidemics-on-Networks/pull/41

However, please also add more details to the affiliations, matching what you'd typically see in an article.

**Comment by lpantano** [comment]
Hi @kyleniemeyer, sadly I don't have any experience in this, and I don't know people on the field. If the author can find one reviewer, I can try to find another, but I don't think I can find two of them alone.

**Comment by lpantano** [comment]
@acolum, would you be able to review this tool?

**Comment by kyleniemeyer** [comment]
@joelmiller are you able to suggest one or two potential reviewers?

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01673/joss.01673/10.21105.joss.01673.pdf)

**Comment by acolum** [comment]
@lpantano Thanks for inviting me, and yes, I'm able to review this tool.

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
@whedon assign @acolumn as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @acolumn

**Comment by lpantano** [comment]
@whedon assign @acolum as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @acolum

**Comment by lpantano** [comment]
Thank you, @acolumn, really appreciate it. 

@stulacy, would you be interested in reviewing this tool?

**Comment by joelmiller** [comment]
I would suggest @count0 or @hagberg

**Comment by joelmiller** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01673/joss.01673/10.21105.joss.01673.pdf)

**Comment by stulacy** [comment]
Unfortunately this is quite outside of my area. Either of the suggestions
made by @joelmiller look more appropriate.

**Comment by lpantano** [comment]
Sorry, for the delay I am having issues to find the second reviewer. @acolum, do you know somebody else that could help? I will ask internally, if not. Cheers

**Comment by acolum** [comment]
Sorry, I don’t know anybody else who could help.

**Comment by lpantano** [comment]
Thank you @joelmiller, I contacted a couple of people as well, still no luck. I will keep trying.

**Comment by lpantano** [comment]
@whedon add @pholme as reviewer

**Comment by whedon** [comment]
OK, @pholme is now a reviewer

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1731. Feel free to close this issue now!
