### ISSUE TITLE
[REVIEW]: LISC: A Python Package for Scientific Literature Collection and Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1674]
**Submitting author:** @TomDonoghue (<a href="http://orcid.org/0000-0001-5911-0472">Thomas Donoghue</a>)
**Repository:** <a href="https://github.com/lisc-tools/lisc" target ="_blank">https://github.com/lisc-tools/lisc</a>
**Version:** v0.1.1
**Editor:** @danielskatz
**Reviewer:** @timClicks, @linuxscout
**Archive:** <a href="https://doi.org/10.5281/zenodo.3462035" target="_blank">10.5281/zenodo.3462035</a>

## Status

[![status](https://joss.theoj.org/papers/7be5e75ec454ef0946841b02a80cd947/status.svg)](https://joss.theoj.org/papers/7be5e75ec454ef0946841b02a80cd947)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7be5e75ec454ef0946841b02a80cd947"><img src="https://joss.theoj.org/papers/7be5e75ec454ef0946841b02a80cd947/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7be5e75ec454ef0946841b02a80cd947/status.svg)](https://joss.theoj.org/papers/7be5e75ec454ef0946841b02a80cd947)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/lisc-tools/lisc" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@timClicks & @linuxscout, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lisc-tools/lisc">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.1.1
- [x] **Authorship:** Has the submitting author (@TomDonoghue) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lisc-tools/lisc">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.1.1
- [x] **Authorship:** Has the submitting author (@TomDonoghue) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @timClicks, @linuxscout it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01674/joss.01674/10.21105.joss.01674.pdf)

**Comment by danielskatz** [comment]
👋 @timClicks, @linuxscout - your job as a reviewer is to examine the paper and software repo, and to check off items in your review list as possible.  When you have some issue where improvement is needed, either flag it here or with a new issue in the repository (mentioning this review issue).  If you have any questions or problems, please let me know. (FYI, I'm mostly on vacation this week and next and will be slower to respond than normal.)

**Comment by timClicks** [comment]
Thanks @danielskatz. I'm also away until the middle of next week. I will aim to have my review completed by next Friday.

**Comment by linuxscout** [comment]
## Review checklist for @linuxscout
### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lisc-tools/lisc">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@TomDonoghue) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by linuxscout** [comment]
I work on review

**Comment by danielskatz** [comment]
👋 @linuxscout - thanks for your work so far. Are there issues that are preventing you from checking the remaining boxes?  If so, please flag them here or with new issues in the repository (mentioning this review issue).

**Comment by danielskatz** [comment]
@whedon remind @timClicks in 6 days

**Comment by whedon** [comment]
Reminder set for @timClicks in 6 days

**Comment by linuxscout** [comment]
I work on testing the software.
For the automated tests, there is none in the repository.

**Comment by linuxscout** [comment]
No automated tests
https://github.com/lisc-tools/lisc/issues/22

**Comment by danielskatz** [comment]
As we say in the [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#tests)

>Authors are strongly encouraged to include an automated test suite covering the core functionality of their software.
>
> * Good: An automated test suite hooked up to an external service such as Travis-CI or similar
> * OK: Documented manual steps that can be followed to objectively check the expected functionality of the software (e.g. a sample input file to assert behavior)
> * Bad (not acceptable): No way for you the reviewer to objectively assess whether the software works

So we do not require automated tests (though we encourage them), but we do require some tests.  

In this case, if there are manual tests that you think are sufficient "to objectively check the expected functionality of the software (e.g. a sample input file to assert behavior)", that's enough for this criterion to be checked.

**Comment by linuxscout** [comment]
I think that tutorials are good as tests.

**Comment by TomDonoghue** [comment]
There are tests!

In the folder lisc/tests is a set of unit-tests. They are, I would say often smoke-tests, in that there is not always strong accuracy checking, but there are at least sanity check tests.

They are written with pytest. If you want to run them locally, then, with pytest installed, from inside the lisc code folder (so in `lisc/lisc`) run:
`pytest .`

I realize now it's not really documented anywhere how to run the tests. Is there a convention on how / where to note tests and how to run them?

Tests are also integrated with travis:
https://travis-ci.org/lisc-tools/lisc

**Comment by danielskatz** [comment]
You might add this info to the README, but certainly should add it to https://lisc-tools.github.io/lisc/, perhaps after installation (after you install, you test to make sure things are working...)

**Comment by linuxscout** [comment]
What I should do now?

**Comment by danielskatz** [comment]
> What I should do now?

Nothing - your part is done, and thanks!

We're now waiting for @timClicks to do his review, check off his items, bring up needed changes, etc.  He was away, but said he would have his review done around now.

I think we're also waiting for @TomDonoghue to add something about how to run the tests to the documentation.

**Comment by whedon** [comment]
:wave: @timClicks, please update us on how your review is going.

**Comment by timClicks** [comment]
@danielskatz My recommendation: accept, subject to the test amendments that have been mentioned already :)

I've worked through the tutorials, and think that this a very handy package.

In general, the API documentation is in an OK state, rather than a Good state (as per the [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html)). That reflects the relative immaturity of the project. lisc is in a much better state than other packages that are released at a 0.1 state.

As a side comment, the tests are written using a very common test framework for Python applications (pytest). However, this isn't included as a dependency in the requirements.txt file so installing the test framework manually is required.

@TomDonoghue thanks for taking the time to submit this to JOSS.

---

@danielskatz @linuxscout @TomDonoghue Sincerely apologise for delaying this process.

**Comment by danielskatz** [comment]
👋 @TomDonoghue - so it seem like the only remaining action for you is to add something about how to run the tests to the documentation.

**Comment by TomDonoghue** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01674/joss.01674/10.21105.joss.01674.pdf)

**Comment by TomDonoghue** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01674/joss.01674/10.21105.joss.01674.pdf)

**Comment by TomDonoghue** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01674/joss.01674/10.21105.joss.01674.pdf)

**Comment by TomDonoghue** [comment]
**Test Coverage**

In terms of noting the test coverage, what I have done is add a section to the README, which gets built as the homepage of the documentation page, which mentions the tests, and how to run them, and the test dependency of pytest. 

I'm actually not too sure what is considered convention / best practice for documenting tests & test coverage - so please let me know if this isn't the best answer! I haven't, for example, typically listed 'pytest' in the `requirements.txt` (it seems not necessarily standard to do so?). Would best practice be to list pytest in requirements, even if its not needed to use the package? Pytest is noted in setup.py. And/or, more generally, if anyone has any suggestions on additional or different ways to mention tests, please let me know!

**API Documentation**
I totally agree that the level of API documentation is middle ground, with it wanting for more examples with inputs / outputs, etc. That's definitely on the list of things to keep updating (https://github.com/lisc-tools/lisc/issues/20). 

**Paper Notes**
There weren't any specific comments on the paper itself. I did a last sweep through, with some very minor edits for wording, layout, and minor ref fixes. I rebuilt the paper above. I hope it's okay to do some last tweaks - just wanted to make nothing was weird there before it gets locked in. Let me know if there are any comments on the wording, etc - happy to tweak / fix up!

**Thanks!**

A huge thank you to @linuxscout & @timClicks for doing the review, and @danielskatz for managing! Please let me know if there is anything else I should do!

**Comment by danielskatz** [comment]
👋 @linuxscout & @timClicks - Please let me know your comments on the changes described above

**Comment by timClicks** [comment]
@danielskatz LGTM. I've reviewed the new paper and the new README. Both look fine.

**Comment by danielskatz** [comment]
👋 @linuxscout - Please let me know your comments on the changes described above

**Comment by danielskatz** [comment]
👋 @linuxscout - Please let me know your comments on the changes described above
(last chance, then I'll assume this is ok with you based on your previous comments and your checking of all the items on your list)

**Comment by linuxscout** [comment]
Hi,
I think it okay for updates.
Thanks.

**Comment by danielskatz** [comment]
👋 @TomDonoghue - to finish up now, I need you to 

1. deposit the repository in an archive (e.g. zenodo) and to report the DOI here
1. tell me the latest version number here
1. confirm that the paper text and references are final

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01674/joss.01674/10.21105.joss.01674.pdf)

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/2623330.2623667 is OK
- 10.1145/3097983.3098057 is OK
- 10.1016/j.jneumeth.2012.04.019 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @TomDonoghue - to finish up now, I need you to

deposit the repository in an archive (e.g. zenodo) and to report the DOI here
tell me the latest version number here
confirm that the paper text and references are final

**Comment by TomDonoghue** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01674/joss.01674/10.21105.joss.01674.pdf)

**Comment by TomDonoghue** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/2623330.2623667 is OK
- 10.1145/3097983.3098057 is OK
- 10.1016/j.jneumeth.2012.04.019 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by TomDonoghue** [comment]
@danielskatz - sorry for the delay, this time it's me away/travelling!

I have done a last check of the paper, and for the references, and other than a couple typos, the only thing I changed is the link to Meta (to be the tool link, not the page on Chan-Zuckerberg, which I think makes more sense). I also released a small version update of the tool, and tagged & released on GitHub / PYPI and made a release on Zenodo, to get a DOI. 

In terms of what you asked for:
Current Version: 0.1.1
DOI: 10.5281/zenodo.3462035
Paper: I confirm the text & references are final

Please let me know if you need anything else from me!

**Comment by danielskatz** [comment]
@whedon set v0.1.1 as version

**Comment by whedon** [comment]
OK. v0.1.1 is the version.

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3462035 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3462035" target="_blank">10.5281/zenodo.3462035</a> is the archive.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/2623330.2623667 is OK
- 10.1145/3097983.3098057 is OK
- 10.1016/j.jneumeth.2012.04.019 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/983

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/983, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@TomDonoghue - please see https://github.com/lisc-tools/lisc/pull/25

**Comment by TomDonoghue** [comment]
@danielskatz - thanks for wording updates / fixes! I have merged the PR.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01674/joss.01674/10.21105.joss.01674.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/2623330.2623667 is OK
- 10.1145/3097983.3098057 is OK
- 10.1016/j.jneumeth.2012.04.019 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/984

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/984, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1177284302360535040) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/985
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01674](https://doi.org/10.21105/joss.01674)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
@TomDonoghue - this seems to be taking a bit longer than normal to have the DOI work - It should work eventually...

**Comment by danielskatz** [comment]
@timClicks & @linuxscout - thanks for reviewing!

**Comment by danielskatz** [comment]
👋 @arfon - any insight on the DOI delay here?

**Comment by danielskatz** [comment]
never mind - now working...

**Comment by arfon** [comment]
> 👋 @arfon - any insight on the DOI delay here?

Looks like it's resolving now.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01674/status.svg)](https://doi.org/10.21105/joss.01674)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01674">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01674/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01674/status.svg
   :target: https://doi.org/10.21105/joss.01674
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01674/status.svg)](https://doi.org/10.21105/joss.01674)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by TomDonoghue** [comment]
Thank you @danielskatz for managing this submission!
