### ISSUE TITLE
[REVIEW]: pySRURGS - a python package for symbolic regression by uniform random global search

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1675]
**Submitting author:** @pySRURGS (<a href="http://orcid.org/0000-0002-3050-8943">Sohrab Towfighi</a>)
**Repository:** <a href="https://github.com/pySRURGS/pySRURGS" target ="_blank">https://github.com/pySRURGS/pySRURGS</a>
**Version:** 0.1
**Editor:** @mbobra
**Reviewer:** @henrik227, @SirSharpest
**Archive:** <a href="https://doi.org/10.5281/zenodo.3442594" target="_blank">10.5281/zenodo.3442594</a>

## Status

[![status](https://joss.theoj.org/papers/6c575a3b0604e5c5d4ca31f27d4d182d/status.svg)](https://joss.theoj.org/papers/6c575a3b0604e5c5d4ca31f27d4d182d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6c575a3b0604e5c5d4ca31f27d4d182d"><img src="https://joss.theoj.org/papers/6c575a3b0604e5c5d4ca31f27d4d182d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6c575a3b0604e5c5d4ca31f27d4d182d/status.svg)](https://joss.theoj.org/papers/6c575a3b0604e5c5d4ca31f27d4d182d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pySRURGS/pySRURGS" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@henrik227 & @SirSharpest, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mbobra know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pySRURGS/pySRURGS">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.1
- [x] **Authorship:** Has the submitting author (@pySRURGS) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pySRURGS/pySRURGS">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.1
- [x] **Authorship:** Has the submitting author (@pySRURGS) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @henrik227, @SirSharpest it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01675/joss.01675/10.21105.joss.01675.pdf)

**Comment by mbobra** [comment]
👋Thank you so much @henrik227 and @SirSharpest for agreeing to review this submission! The review checklist is above. Please let me know if there is anything else you need!

**Comment by sohrabtowfighi** [comment]
Hi, I have rewritten the test script `test.py` to better meet criteria described herein.

**Comment by sohrabtowfighi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01675/joss.01675/10.21105.joss.01675.pdf)

**Comment by henrik227** [comment]
@sohrabtowfighi Regarding the authorship: Are you also using the @pySRURGS account, or is this someone else?

**Comment by sohrabtowfighi** [comment]
@henrik227, I am also using the @pySRURGS account. There is no other author.

**Comment by sohrabtowfighi** [comment]
I have added an -exhaustive flag which performs brute-force exhaustive search instead of uniform random global search

**Comment by pySRURGS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01675/joss.01675/10.21105.joss.01675.pdf)

**Comment by SirSharpest** [comment]
I have added my inital comments [here](https://github.com/pySRURGS/pySRURGS/issues/6), though I am happy to elaborate if I have been unclear.

**Comment by pySRURGS** [comment]
I have added the `-deterministic` flag and made other changes to address @SirSharpest' comments.

**Comment by sohrabtowfighi** [comment]
After acknowledging Dr. Luther Tychonievich, I added a wayback machine archive link to the blog post where Dr. Tychonievich details the algorithm mapping integers to binary trees.

**Comment by sohrabtowfighi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by sohrabtowfighi** [comment]
I removed the word 'actually' from the paper.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01675/joss.01675/10.21105.joss.01675.pdf)

**Comment by mbobra** [comment]
@sohrabtowfighi We're almost there! Could you please go ahead and [create a new release](https://help.github.com/en/articles/creating-releases) that incorporates all of these fixes?  And can you please [archive your release on Zenodo](https://guides.github.com/activities/citable-code/) to obtain a DOI and then put the Zenodo badge in your README.md file? After that I think we're done 🎉

**Comment by mbobra** [comment]
Thank you for your review, @SirSharpest! We really appreciate it 👏

**Comment by pySRURGS** [comment]
Done. Thanks!
https://zenodo.org/badge/latestdoi/200314164

**Comment by mbobra** [comment]
@whedon set 10.5281/zenodo.3442594 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3442594" target="_blank">10.5281/zenodo.3442594</a> is the archive.

**Comment by mbobra** [comment]
@whedon set 0.1 as version

**Comment by whedon** [comment]
OK. 0.1 is the version.

**Comment by mbobra** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1186/s13040-018-0164-x is OK
- 10.1145/2464576.2482691 is OK

MISSING DOIs

- https://doi.org/10.1016/0303-2647(94)90062-0 may be missing for title: Genetic Programming: On the Programming of Computers by Means of Natural Selection
- https://doi.org/10.1016/0012-365x(71)90023-9 may be missing for title: Enumerating Trees
- https://doi.org/10.1287/moor.6.1.19 may be missing for title: Minimization by Random Search Techniques

INVALID DOIs

- None
```

**Comment by mbobra** [comment]
@pySRURGS Can you please make sure all the references in the paper.bib file include DOIs? Thanks!

**Comment by sohrabtowfighi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01675/joss.01675/10.21105.joss.01675.pdf)

**Comment by sohrabtowfighi** [comment]
@mbobra I have fixed references. The work of Tychonievich has no DOI.

**Comment by sohrabtowfighi** [comment]
Wait found issue and  need to regenerate pdf.

**Comment by sohrabtowfighi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01675/joss.01675/10.21105.joss.01675.pdf)

**Comment by sohrabtowfighi** [comment]
@mbobra ok done

**Comment by mbobra** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/BF00175355 is OK
- 10.1186/s13040-018-0164-x is OK
- 10.1145/2464576.2482691 is OK
- 10.1287/moor.6.1.19 is OK

MISSING DOIs

- https://doi.org/10.1016/0012-365x(71)90023-9 may be missing for title: Enumerating Trees

INVALID DOIs

- None
```

**Comment by mbobra** [comment]
@sohrabtowfighi Looks like one is still missing.

**Comment by pySRURGS** [comment]
@mbobra
That one has no doi

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/972

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/972, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
Oops, I forgot to first verify the zenodo archive.

@pySRURGS Please change the meta data on your zenodo archive so that the title and author match your paper exactly.

**Comment by pySRURGS** [comment]
@kthyng Done thanks!

**Comment by kthyng** [comment]
Great, thanks!

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1175054044286586892) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/973
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01675](https://doi.org/10.21105/joss.01675)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your publication @pySRURGS!!! Thanks so much to our reviewers, @henrik227 and @SirSharpest.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01675/status.svg)](https://doi.org/10.21105/joss.01675)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01675">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01675/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01675/status.svg
   :target: https://doi.org/10.21105/joss.01675
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01675/status.svg)](https://doi.org/10.21105/joss.01675)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
