### ISSUE TITLE
[PRE REVIEW]: SIHR: a MATLAB/GNU Octave toolbox for single image highlight removal

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1676]
**Submitting author:** @vitorsr (<a href="http://orcid.org/0000-0002-7583-5577">Vítor Saraiva Ramos</a>)
**Repository:** <a href="https://github.com/vitorsr/SIHR" target ="_blank">https://github.com/vitorsr/SIHR</a>
**Version:** v0.1
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @thomakra, @Atif-Anwer

**Author instructions**

Thanks for submitting your paper to JOSS @vitorsr. **Currently, there isn't an JOSS editor assigned** to your paper.

@vitorsr if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1676 with the following error: 

 Error producing PDF.
! Package graphics Error: Division by 0.

See the graphics package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.307 ...089d5f01186488ed275cfa889c48f63fd4f6.jpg}

Looks like we failed to compile the PDF

**Comment by kyleniemeyer** [comment]
Hi @Kevin-Mattheus-Moerman, this submission looks up your alley—can you edit it?

**Comment by vitorsr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1676 with the following error: 

 Error producing PDF.
! Package graphics Error: Division by 0.

See the graphics package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.307 ...089d5f01186488ed275cfa889c48f63fd4f6.jpg}

Looks like we failed to compile the PDF

**Comment by vitorsr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01676/joss.01676/10.21105.joss.01676.pdf)

**Comment by vitorsr** [comment]
Wait. Was I meant to do that? Sorry for the trouble, just wanted to make sure it compiled.

Thank you for your time.

**Comment by kyleniemeyer** [comment]
@vitorsr no worries, whedon has varying permissions—it's fine to regenerate the pdf yourself

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@danasolav is this something you'd be interested in reviewing? We'll get several reviewers (some of whom are experts in this field) so it is okay if this isn't exactly your expertise. You could test it for the removal of reflections from your some of your DIC data for instance.

**Comment by Kevin-Mattheus-Moerman** [comment]
@vitorsr I'm recruiting/searching for reviewers. If you have any reviewer suggestions please feel free to tag them here. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@wanrenjie @rui1996 @thatbrguy @sjtrny @ceciliavision would you be interested in reviewing this submission for the Journal of Open Source Software (JOSS)? This package implements (MATLAB/Octave) and compares several single image highlight removal methods. [The review process focuses](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) largely on [the software](https://github.com/vitorsr/SIHR) and also a [short paper](https://github.com/openjournals/joss-papers/blob/joss.01676/joss.01676/10.21105.joss.01676.pdf). Let me know if you have any questions.  
This is a _prereview_ issue. Once several reviewers have been found a review issue is opened.

**Comment by thatbrguy** [comment]
@Kevin-Mattheus-Moerman @vitorsr Thank you for reaching out! However, I would like to pass on this opportunity as I don't think I possess sufficient background knowledge to provide a proper review for this submission.

**Comment by vitorsr** [comment]
Greetings @Kevin-Mattheus-Moerman. There are a few changes to the repository that need to be made. Is it OK if I make some changes, publish a new release, and mint a new Zenodo DOI for that release while still in prereview? I'll update them accordingly. Thanks in advance.

**Comment by Kevin-Mattheus-Moerman** [comment]
Yes that is fine, we'll inform the reviewers about what version to focus on, and I can update the version tag here too.

**Comment by vitorsr** [comment]
@kczimm @thomakra can you review this submission for JOSS?

**Comment by sjtrny** [comment]
Hi thanks for the invitation to review. However right at this current moment I do not have the capacity to complete a review in a timely manner. I'm open to reviewing this (or any future work) once semester is over for me.

**Comment by Kevin-Mattheus-Moerman** [comment]
@wanrenjie @rui1996 @ceciliavision @kczimm @thomakra Would you be interested in reviewing this submission for the Journal of Open Source Software (JOSS)? This package implements (MATLAB/Octave) and compares several single image highlight removal methods. [The review process focuses](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) largely on [the software](https://github.com/vitorsr/SIHR) and also a [short paper](https://github.com/openjournals/joss-papers/blob/joss.01676/joss.01676/10.21105.joss.01676.pdf). Let me know if you have any questions.
This is a _prereview_ issue. Once several reviewers have been found a review issue is opened.

**Comment by thomakra** [comment]
Hi,

Apologies for the late reply.
I've been on vacation.
I should have time to have a look after Wednesday next week.
This would be my first time contributing, so I would appreciate a link to
any guidelines you have for what is expected from a review.

-Thomas-

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for your reply @thomakra. Could please specify (or update your GitHub profile to include links to) personal/professional profiles and affiliations?

**Comment by Kevin-Mattheus-Moerman** [comment]
@thomakra here is information about our review process:
https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Here is an example of an ongoing review process (I'll open a similar review issue once we have sufficient reviewers), as you can see tickboxes guide reviewers through the GitHub based review process: 
https://github.com/openjournals/joss-reviews/issues/1613

**Comment by Kevin-Mattheus-Moerman** [comment]
@thomakra :point_up:

> Thanks for your reply @thomakra. Could please specify (or update your GitHub profile to include links to) personal/professional profiles and affiliations? This is so we can verify exactly who potential reviewers are and what their background is. Thanks.

**Comment by thomakra** [comment]
Here is my profile page on the university website:
https://en.uit.no/om/enhet/ansatte/person?p_document_id=138601&p_dimension_id=88136

I have a Linkedin profile, but I haven't used it actively.
My background is a M.Sc. in pattern recognition, machine learning, image
processing and remote sensing.

-Thomas-

**Comment by kczimm** [comment]
Sorry, I'm unable to review this paper at this time.

**Comment by Kevin-Mattheus-Moerman** [comment]
@wanrenjie @rui1996 @ceciliavision Would you be interested in reviewing this submission for the Journal of Open Source Software (JOSS)? This package implements (MATLAB/Octave) and compares several single image highlight removal methods. [The review process focuses](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) largely on [the software](https://github.com/vitorsr/SIHR) and also a [short paper](https://github.com/openjournals/joss-papers/blob/joss.01676/joss.01676/10.21105.joss.01676.pdf). Let me know if you have any questions.
This is a _prereview_ issue. Once several reviewers have been found a review issue is opened.

**Comment by vitorsr** [comment]
@Kevin-Mattheus-Moerman, may I suggest @Atif-Anwer as a potential reviewer? He is a Ph.D. student at UT Petronas and is already familiar with the project. I have contacted him regarding reviewing for JOSS and he has agreed to do so.

**Comment by Kevin-Mattheus-Moerman** [comment]
@Atif-Anwer Would you be interested in reviewing this submission for the Journal of Open Source Software (JOSS)? This package implements (MATLAB/Octave) and compares several single image highlight removal methods. [The review process focuses](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) largely on [the software](https://github.com/vitorsr/SIHR) and also a [short paper](https://github.com/openjournals/joss-papers/blob/joss.01676/joss.01676/10.21105.joss.01676.pdf). Let me know if you have any questions.
This is a _prereview_ issue. Once several reviewers have been found a review issue is opened.

**Comment by Atif-Anwer** [comment]
Hi!
I would be glad to review the paper. It is quite inline with my current area of research also. 
What is the deadline for submitting the review (if any)? 
This would be my first time reviewing/contributing, and I have gone through the guidelines you linked above. But I'm confused as to where do reviewers submit their comments (or are they not visible to the public?)
Regards, 
Atif

> @Boyiliee @Atif-Anwer @DmitryUlyanov Would you be interested in reviewing this submission for the Journal of Open Source Software (JOSS)? This package implements (MATLAB/Octave) and compares several single image highlight removal methods. [The review process focuses](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) largely on [the software](https://github.com/vitorsr/SIHR) and also a [short paper](https://github.com/openjournals/joss-papers/blob/joss.01676/joss.01676/10.21105.joss.01676.pdf). Let me know if you have any questions.
> This is a _prereview_ issue. Once several reviewers have been found a review issue is opened.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @Atif-Anwer as reviewer

**Comment by whedon** [comment]
OK, @Atif-Anwer is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @Atif-Anwer. I aim to recruit one more reviewer and then we'll get started. In the mean time you can familiarize yourself with the [review guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1822. Feel free to close this issue now!
