### ISSUE TITLE
[PRE REVIEW]: Knuteon! - A capillary electrophoresis data extraction utility for Karat32 data files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1677]
**Submitting author:** @Schallaven (<a href="http://orcid.org/0000-0001-7423-4609">Sven Kochmann</a>)
**Repository:** <a href="https://github.com/Schallaven/Knuteon" target ="_blank">https://github.com/Schallaven/Knuteon</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @Schallaven. **Currently, there isn't an JOSS editor assigned** to your paper.

@Schallaven if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01677/joss.01677/10.21105.joss.01677.pdf)

**Comment by Schallaven** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01677/joss.01677/10.21105.joss.01677.pdf)

**Comment by kyleniemeyer** [comment]
Hi @Schallaven, thanks for your interest in JOSS.

After a pre-review of your submission, and an assessment by the editorial board at large, we find that this submission does not quite meet our submission requirements. In particular, while the software seems very useful, it falls under the "minor utility" category, and we therefore decided not to put it through review.

Thank you for considering JOSS as a venue for your software, and I hope you'll submit other software with research application in the future.
