### ISSUE TITLE
[PRE REVIEW]: pypulseq 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1678]
**Submitting author:** @imr-framework (<a href="http://orcid.org/0000-0002-3776-4114">Sairam Geethanath</a>)
**Repository:** <a href="https://github.com/imr-framework/pypulseq" target ="_blank">https://github.com/imr-framework/pypulseq</a>
**Version:** 1.2.2
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @grlee77, @mathieuboudreau

**Author instructions**

Thanks for submitting your paper to JOSS @imr-framework. **Currently, there isn't an JOSS editor assigned** to your paper.

@imr-framework if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kyleniemeyer** [comment]
Hi @Kevin-Mattheus-Moerman, another imaging-related submission—do you have the bandwidth to edit this one?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01678/joss.01678/10.21105.joss.01678.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by grlee77** [comment]
Hi @sravan953, I am interested in taking a look. I work in a Philips environment currently, but have also done sequence programming for GE and Siemens scanners in the past, so this is pretty relevant.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @grlee77 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @grlee77

**Comment by Kevin-Mattheus-Moerman** [comment]
@mwegrzyn are you interested in reviewing this work for JOSS?

**Comment by mwegrzyn** [comment]
Hello, 
thank you for the invitation. This sounds very interesting, but I'm afraid I don't have the necessary physics knowledge to adequately understand the code. Sorry, but I'll have to pass. 
Best regards, Martin Wegrzyn

**Comment by Kevin-Mattheus-Moerman** [comment]
@kelvinlayton @stefan-k would you be interested in reviewing this work for the Journal of Open Source Software (JOSS)? [The review](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) focuses largely on [the software](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) and a [very short paper](https://github.com/openjournals/joss-papers/blob/joss.01678/joss.01678/10.21105.joss.01678.pdf).

**Comment by stefan-k** [comment]
Thanks for the invitation!
I'm currently quite short on time, but I'll think about it and I'll let you know within the next couple of days. I should mention though that there may be a conflict of interest as I've collaborated with @imr-framework in the past and we've co-authored papers and conference contributions. I've also worked on a [similar project](https://github.com/pulseq/pypulseq) which was abandoned in favor of the software which is up for review. 

Maybe @m-a-x-i-m-z is interested in this too.

**Comment by sravan953** [comment]
@sairamgeethanath one reviewer still pending, am I right @Kevin-Mattheus-Moerman ?

**Comment by Kevin-Mattheus-Moerman** [comment]
@sravan953 yes we are still recruiting reviewers. Aiming for 3 hopefully.

**Comment by Kevin-Mattheus-Moerman** [comment]
@stefan-k thanks for your message and for clarifying the potential conflict of interest. Since we will have multiple reviewers without a conflict of interest, if you were to join decisions will not rest solely on your judgement/comments. Therefore, since it sounds like you could have valuable feedback, I'd still welcome your contribution as an additional reviewer. Let me know what you decide.

**Comment by stefan-k** [comment]
Unfortunately I have to decline as I won't have time. Maybe @jfnielsen or @magland, who have worked on similar software, are interested to help out.

**Comment by jfnielsen** [comment]
I'm happy to review but like stefan-k I'm collaborating with the authors on related topics which is technically a conflict. I'm certainly interested though.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @jfnielsen as reviewer

**Comment by whedon** [comment]
OK, @jfnielsen is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@jfnielsen thanks for pointing out the conflict of interest. I'll welcome you as an additional reviewer and will also recruit reviewers without a conflict of interest. Thanks for your help.

**Comment by Kevin-Mattheus-Moerman** [comment]
@spinicist would you be interested in reviewing this work for the [Journal of Open Source Software (JOSS)](https://joss.theoj.org)? [The review](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) focuses largely on [the software](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) and a [very short paper](https://github.com/openjournals/joss-papers/blob/joss.01678/joss.01678/10.21105.joss.01678.pdf).

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon remove @jfnielsen as reviewer

**Comment by whedon** [comment]
OK, @jfnielsen is no longer a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@jfnielsen After consulting with the editorial board it was decided to not include you due to the conflict of interest you referred to. My apologies for the confusion. Thanks again for offering to review for JOSS. I will consider you as a potential reviewer for other MRI related submissions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mfroeling are you or your co-workers interested in reviewing this work on MRI pulse sequence design in Python?

**Comment by Kevin-Mattheus-Moerman** [comment]
@nstikov, @vsoch, @mathieuboudreau would you be interested in reviewing this JOSS submission?

**Comment by mathieuboudreau** [comment]
Sure!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @mathieuboudreau as reviewer

**Comment by whedon** [comment]
OK, @mathieuboudreau is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1725. Feel free to close this issue now!

**Comment by Kevin-Mattheus-Moerman** [comment]
This pre-review issue will now be closed. People interested in helping to review should head over to #1725.
