### ISSUE TITLE
[PRE REVIEW]: Python KM: Kramers--Moyal coefficients for stochastic processes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1679]
**Submitting author:** @LRydin (<a href="http://orcid.org/0000-0001-5513-0580">Leonardo Rydin Gorjão</a>)
**Repository:** <a href="https://github.com/LRydin/KramersMoyal" target ="_blank">https://github.com/LRydin/KramersMoyal</a>
**Version:** v0.31
**Editor:** @kthyng
**Reviewers:** @dawbarton , @Shibabrat 

**Author instructions**

Thanks for submitting your paper to JOSS @LRydin. **Currently, there isn't an JOSS editor assigned** to your paper.

@LRydin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1679 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `initialize': No such file or directory @ rb_sysopen - tmp/1679/paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:113:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:63:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
Hi @xuanxu, this is a little outside your typical area, but could you edit this submission?

**Comment by kyleniemeyer** [comment]
@arfon not sure what's going on with the paper here—it builds fine for me locally. Could the presence of `paper.tex` and `paper.pdf` be causing an issue?

**Comment by xuanxu** [comment]
@kyleniemeyer I’m quite busy now, can you try to find another editor for this one?

**Comment by kyleniemeyer** [comment]
@xuanxu I'll give it a shot, but this is a math-heavy submission, and Viviane is out until October.

**Comment by kyleniemeyer** [comment]
@kthyng can you take this submission on?

**Comment by arfon** [comment]
> @arfon not sure what's going on with the paper here—it builds fine for me locally. Could the presence of paper.tex and paper.pdf be causing an issue?

Yeah, @LRydin - could you please remove the `paper.tex` file from your repository? It's confusing @whedon.

**Comment by LRydin** [comment]
Dear All,

@arfon certainly, I'll remove the .tex. Do understand that the paper.pdf is
generated from that TeX, since I am a novice with Markdown.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1679 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:143:in `block in check_orcids': Problem with ORCID (0000-0000-0000-0000) for Francisco Meirinhos (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:141:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:141:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:88:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@LRydin - this pull request should fix your paper: https://github.com/LRydin/KramersMoyal/pull/3 . I'm not sure if this author has an ORDIC but the placeholder one 0000-0000-0000-0000 is failing validation.

The Pandoc rendering engine goes from Markdown (`paper.md`) straight through to pdf. Having a file called `paper.tex` confuses our robot Whedon when compiling the paper :-)

**Comment by LRydin** [comment]
@Arfon He does not yet have an ORCID account, but I will talk with
Francisco to generate it.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01679/joss.01679/10.21105.joss.01679.pdf)

**Comment by kthyng** [comment]
Sure, I can be editor.

**Comment by kthyng** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
@LRydin Can you look at the list of reviewers (https://bit.ly/joss-reviewers) and select out at least 4 that look like good fits for your submission? Then I will ask them, in search of 2. People not from the list are fine, too.

**Comment by LRydin** [comment]
@kthyng <https://github.com/kthyng> Hey Kristen Thyng, I have found four
possible names:

pdebuyl
shibabrat
dawbarton
JoshKarpel

there is a possible other reviewer that has worked in the field and now is
a Professor at the Metropolitan University of Oslo: Pedro Lind,
Pedro.Lind@oslomet.no

Best,
Leonardo

**Comment by dawbarton** [comment]
Yes, I should be able to do that. I've strayed into this sort of area before, my knowledge is a bit rusty but should be fine.

**Comment by LRydin** [comment]
Dear Kristen Thyng,

I am but a PhD student, I don't think I possess at the time the required
knowledge to review papers, and the underlying python coding here, i.e.,
not the fundamental idea, but the improvement of the code, was performed by
Francisco Meirinhos (the second author). I feel he has the skills to review
computationally oriented papers. Maybe he would be a better bet?

I am thankful for the offer, but I don't believe I would have the required
knowledge for such.

Best,
Leonardo Rydin

**Comment by Shibabrat** [comment]
@kthyng I can take up the review for this submission. Sorry for the slow response.

**Comment by kthyng** [comment]
Great! We have two reviewers!

@dawbarton and @Shibabrat, I will start the review issue now.

**Comment by kthyng** [comment]
@whedon assign @dawbarton  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dawbarton

**Comment by kthyng** [comment]
@whedon add @Shibabrat  as reviewer

**Comment by whedon** [comment]
OK, @Shibabrat  is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1693. Feel free to close this issue now!
