### ISSUE TITLE
[PRE REVIEW]: tabulog: A Language-Agnostic Template System for Parsing Log Files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1680]
**Submitting author:** @austinnar (<a href="http://orcid.org/0000-0002-5319-9805">Austin Nar</a>)
**Repository:** <a href="https://github.com/AustinNar/tabulog" target ="_blank">https://github.com/AustinNar/tabulog</a>
**Version:** 0.1.1
**Editor:** @trallard
**Reviewers:** @alexanderfurnas, @trallard

**Author instructions**

Thanks for submitting your paper to JOSS @austinnar. **Currently, there isn't an JOSS editor assigned** to your paper.

@austinnar if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kyleniemeyer** [comment]
Hi @trallard, can you take this submission on?

**Comment by whedon** [comment]
PDF failed to compile for issue #1680 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1680 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:135:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
Hi @AustinNar, could you add an `affiliation` block to your paper's header, and also modify the author field to include this? It should look something like:
```yaml
authors:
  - name: Austin Nar
    orcid: 0000-0002-5319-9805
    affiliation: 1
affiliations:
 - name:  [department, institution, city, state, country]
   index: 1
```

**Comment by AustinNar** [comment]
Hi @kileniemeyer, I have pushed an update with affiliation, does that look correct?

**Comment by kyleniemeyer** [comment]
@AustinNar please remove the "Student" part, and add location information like city, state, and country

For example, my affiliation info would be:
> School of Mechanical, Industrial, and Manufacturing Engineering, Oregon State University, Corvallis, OR, USA

**Comment by AustinNar** [comment]
@kyleniemeyer Thank you, I've committed/pushed the updated paper.md

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01680/joss.01680/10.21105.joss.01680.pdf)

**Comment by trallard** [comment]
Sure @kyleniemeyer  I am happy to edit this submission

**Comment by kyleniemeyer** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by trallard** [comment]
Hi @AustinNar  apologies for the delay, the first thing we have to do is finding a couple of reviewers do you have someone in mind before moving forward?

If not you can check the list of reviewers at [https://bit.ly/joss-reviewers](https://bit.ly/joss-reviewers) 
and see if there is anyone that would be suitable

**Comment by AustinNar** [comment]
Hi @trallard no worries! Both @zfurnas and @mbod seem like good choices (background in R & Python and text analysis)

**Comment by trallard** [comment]
Excellent!


Dear potential reviewers (@alexanderfurnas and @mbod ),
Based on your expertise in R, Python and text analysis, I would like to ask if you can help us out with a submission to JOSS (The Journal of Open Source Software), where I’m an editor.
Title: tabulog: A Language-Agnostic Template System for Parsing Log Files

Summary: Tabulog is a flexible, powerful framework for parsing log files, specifically designed for web logs (such as the access.log files created by Apache), with the final output being in a tabular format.

Parsing logs with Tabulog requires two things: a template, and a list of "parser classes."

Article Proof: https://github.com/openjournals/joss-papers/blob/joss.01680/joss.01680/10.21105.joss.01680.pdf

Submitting author: @AustinNar  Austin NAr

Repository: https://github.com/AustinNar/tabulog

Version: 2018.12
@alexanderfurnas: Alexander, are you able to and interested in taking on this review?

@mbod : Monica, are you able to and interested in taking on this review?

Your prompt response is appreciated. Please see <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html> for more information about reviewer criteria and the process if it is new to you.

**Comment by alexanderfurnas** [comment]
I'm happy to be a reviewer. What is the expected turnaround times for the reviews? Thanks for the reviewer guidelines as well, everything is really well documented (which is not a surprised given the journal), but is a treat.

**Comment by trallard** [comment]
hey @alexanderfurnas  we expect the reviews to be dealt with within a couple of weeks, but if you have other commitments we can wait a bit longer.

**Comment by trallard** [comment]
@whedon assign @alexanderfurnas as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @alexanderfurnas

**Comment by trallard** [comment]
ping @alexanderfurnas just wanted to check if you had a timeline for this review?

**Comment by labarba** [comment]
@trallard — it looks like you need to find a second reviewer here to start the review?

**Comment by trallard** [comment]
HI yes @labarba I have tried finding other reviewers but have had no luck. Will make another recruiting effort this week.

**Comment by trallard** [comment]
@whedon remind @trallard in 3 days

**Comment by whedon** [comment]
Sorry, I can't set reminders on PRE-REVIEW issues.

**Comment by trallard** [comment]
I will be taking on as the second reviewer to move this forward

**Comment by trallard** [comment]
@whedon  add @trallard as reviewer

**Comment by trallard** [comment]
@whedon add @trallard as reviewer

**Comment by whedon** [comment]
OK, @trallard is now a reviewer

**Comment by trallard** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1917. Feel free to close this issue now!
