### ISSUE TITLE
[PRE REVIEW]: RHEOS - A Julia package for Rheology Data Analysis.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1681]
**Submitting author:** @akabla (<a href="http://orcid.org/0000-0002-0280-3531">Alexandre Kabla</a>)
**Repository:** <a href="https://github.com/JuliaRheology/RHEOS.jl" target ="_blank">https://github.com/JuliaRheology/RHEOS.jl</a>
**Version:** v0.9
**Editor:** @jedbrown
**Reviewers:** @adambeall, @gbruer15, @HaoZeke

**Author instructions**

Thanks for submitting your paper to JOSS @akabla. **Currently, there isn't an JOSS editor assigned** to your paper.

@akabla if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1681 with the following error: 

 Error reading bibliography ./paper.bib (line 161, column 3):
unexpected "v"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by kyleniemeyer** [comment]
Hi @jedbrown, could you edit this submission?

**Comment by kyleniemeyer** [comment]
@akabla this PR should fix the compilation issue (assuming there aren't others): https://github.com/JuliaRheology/RHEOS.jl/pull/34

**Comment by akabla** [comment]
Thanks Kyle, I just accepted the PR.

**Comment by akabla** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1681 with the following error: 

 [WARNING] Could not convert image '/tmp/tex2pdf.157/02ebd5134ef935743898e21f279b1f371ffbfaa1.svg': check that rsvg2pdf is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
[WARNING] Could not convert image '/tmp/tex2pdf.157/7a4a8d0b45104765db67392b19dbfe1d93d90bdc.svg': check that rsvg2pdf is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.157/02ebd5134ef
935743898e21f279b1f371ffbfaa1.svg (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.443 ...d5134ef935743898e21f279b1f371ffbfaa1.svg}

Looks like we failed to compile the PDF

**Comment by akabla** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01681/joss.01681/10.21105.joss.01681.pdf)

**Comment by jedbrown** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by akabla** [comment]
Thanks @jedbrown for accepting to edit the paper. We'll try to suggest reviewers asap.

**Comment by akabla** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by akabla** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01681/joss.01681/10.21105.joss.01681.pdf)

**Comment by HaoZeke** [comment]
Hey this seems like a neat project. Might I recommend myself as a reviewer? @akabla

**Comment by akabla** [comment]
Dear @HaoZeke, you would be more than welcome!
@jedbrown

**Comment by akabla** [comment]
Dear Jed,    @jedbrown 

please find below suggestions of reviewers for the paper.

@HaoZeke has most kindly offered to review.

Based on the list of JOSS reviewers, I would also suggest:

- myousefi
- wkearn
- mancellin

Many thanks

**Comment by moustachio-belvedere** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1101/543330 is OK
- 10.1016/j.mechmat.2013.09.017 is OK
- 10.1101/565614 is OK
- 10.1017/CBO9780511626722 is OK
- 10.1122/1.5025622 is OK
- 10.1122/1.5018715 is OK

MISSING DOIs

- https://doi.org/10.1115/1.3424077 may be missing for title: Creep and Relaxation of Nonlinear Viscoelastic Materials: With an Introduction to Linear Viscoelasticity

INVALID DOIs

- None
```

**Comment by moustachio-belvedere** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1101/543330 is OK
- 10.1016/j.mechmat.2013.09.017 is OK
- 10.1101/565614 is OK
- 10.1017/CBO9780511626722 is OK
- 10.1122/1.5025622 is OK
- 10.1122/1.5018715 is OK

MISSING DOIs

- https://doi.org/10.1115/1.3424077 may be missing for title: Creep and Relaxation of Nonlinear Viscoelastic Materials: With an Introduction to Linear Viscoelasticity

INVALID DOIs

- None
```

**Comment by moustachio-belvedere** [comment]
I have removed the Findley book DOI that `whedon` suggests as it a DOI for a book review of the actual book.

**Comment by moustachio-belvedere** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01681/joss.01681/10.21105.joss.01681.pdf)

**Comment by akabla** [comment]
Dear @jedbrown,

This is just to check if you are waiting for more information from us. 

Please let me know if there is anything else I should do in addition to the list of [suggested referees above](https://github.com/openjournals/joss-reviews/issues/1681#issuecomment-524829693).

Thanks!

**Comment by jedbrown** [comment]
@whedon add @adambeall as reviewer

**Comment by whedon** [comment]
OK, @adambeall is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @gbruer15 as reviewer

**Comment by whedon** [comment]
OK, @gbruer15 is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @HaoZeke as reviewer

**Comment by whedon** [comment]
OK, @HaoZeke is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1700. Feel free to close this issue now!
