### ISSUE TITLE
[PRE REVIEW]: kmeRs : K-Mers Similarity Score Matrix

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1687]
**Submitting author:** @RafalUrniaz (<a href="http://orcid.org/0000-0003-0192-2165">Rafal Urniaz</a>)
**Repository:** <a href="https://github.com/RafalUrniaz/kmeRs" target ="_blank">https://github.com/RafalUrniaz/kmeRs</a>
**Version:** 1.1.0
**Editor:** @csoneson
**Reviewers:** @jlincbio, @VivekTodur

**Author instructions**

Thanks for submitting your paper to JOSS @RafalUrniaz. **Currently, there isn't an JOSS editor assigned** to your paper.

@RafalUrniaz if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01687/joss.01687/10.21105.joss.01687.pdf)

**Comment by labarba** [comment]
👋 @RafalUrniaz — I am the Associate Editor-in-Chief on rotation this week. I'm going to send this back to you for some more work, because the paper does not meet [our expectations](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). The paper, as submitted, is too brief and doesn't describe the software or its need and uses in research. While we don't expect a full article, it should be 250–1000 words. These items need to be included:

- the summary describing high-level functionality and purpose of the software for a diverse, non-specialist audience;
- a clear statement of need that illustrates the research application of the software (including references to other software meeting similar needs).

TL;DR: the article needs to be improved with more description of how the software works, some examples, and use cases.

**Comment by RafalUrniaz** [comment]
Hi @labarba,

Thank you for your essential comments. I am happy to announce that the paper was revised and updated as you suggested above. Please, find the new one in the paper folder at kmeRs git. I am looking forward to you suggestions after revision. 

Best wishes,
Rafal.

**Comment by RafalUrniaz** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by RafalUrniaz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01687/joss.01687/10.21105.joss.01687.pdf)

**Comment by kthyng** [comment]
Now that those changes have been made, it looks like we can move forward.

@csoneson could you edit this submission?

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
@coughls, @VivekTodur, @jlincbio - would two of you be willing to review this submission for JOSS?

**Comment by jlincbio** [comment]
Sure, I'm in.

**Comment by VivekTodur** [comment]
Hello,

Yes, I would be interested.

Regards,
Vivek

**Comment by csoneson** [comment]
@jlincbio, @VivekTodur - thanks a lot! I'll get the review issue started.

**Comment by csoneson** [comment]
@whedon assign @jlincbio as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jlincbio

**Comment by csoneson** [comment]
@whedon add @VivekTodur as reviewer

**Comment by whedon** [comment]
OK, @VivekTodur is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1744. Feel free to close this issue now!
