### ISSUE TITLE
[PRE REVIEW]: Rescal-snow: A model for dunes and snow-waves

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1689]
**Submitting author:** @kellykochanski (<a href="http://orcid.org/0000-0003-0754-0184">Kelly Kochanski</a>)
**Repository:** <a href="https://github.com/kellykochanski/rescal-snow" target ="_blank">https://github.com/kellykochanski/rescal-snow</a>
**Version:** v1.1
**Editor:** @kthyng
**Reviewers:** @zbeekman

**Author instructions**

Thanks for submitting your paper to JOSS @kellykochanski. **Currently, there isn't an JOSS editor assigned** to your paper.

@kellykochanski if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1689 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1689 with the following error: 

 Error reading bibliography ./docs/paper.bib (line 43, column 3):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by labarba** [comment]
👋  @kellykochanski 
You're missing a comma on this line
https://github.com/kellykochanski/rescal-snow/blob/95b8ac00971f932e8ce2809df5e567b1be068976/docs/paper.bib#L42

Please fix, then run the command `@whedon generate pdf` in a comment below.

**Comment by kellykochanski** [comment]
Committing updates to new branch rescal-snow/kk/JOSS-fixes

@whedon generate pdf

**Comment by kellykochanski** [comment]
Possible reviewers from the list:  @gassmoeller (interested in geosciences and scientific computing), @zbeekman (interest in multi-physics codes, plus experience with cmake, legacy frameworks and HPC that could potentially improve this code), @rgmyr (interested in geoscience, some work on geomorphology and work in relevant languages)

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1689 with the following error: 

 Error reading bibliography ./docs/paper.bib (line 46, column 3):
unexpected "v"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by labarba** [comment]
@whedon generate pdf from branch kk/JOSS-fixes

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch kk/JOSS-fixes. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1689 with the following error: 

 Error reading bibliography ./docs/paper.bib (line 46, column 3):
unexpected "v"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by labarba** [comment]
@kellykochanski Please go over your bibliography for missing commas.

**Comment by labarba** [comment]
👋  @kthyng — Could you handle this submission as editor? 
"Rescal-snow: A model for dunes and snow-waves"

**Comment by kellykochanski** [comment]
@labarba Thanks for your help - I should be able to get this. Is there a way to test the pdf compilation outside this issue?

@whedon generate pdf from branch kk/JOSS-fixes

**Comment by zbeekman** [comment]
@labarba & @kellykochanski This looks very interesting. I'd be happy to review this with the caveat that I won't be able to start work on this until Sept. 9th.

**Comment by kthyng** [comment]
@labarba Yep I'll do it!

**Comment by kthyng** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
@zbeekman Awesome! That timing is fine, we like to have reviews within about 3 weeks. I'll search for another reviewer now before we start the review process.

**Comment by kthyng** [comment]
@rgmyr Are you interested in reviewing this submission for JOSS? You can check out reviewer guidelines here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html 
We ask for reviews within about 3 weeks.

**Comment by labarba** [comment]
@whedon generate pdf from branch kk/JOSS-fixes

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch kk/JOSS-fixes. Reticulating splines etc...
```

**Comment by labarba** [comment]
Note that `whedon` commands need to be issued alone in a comment (no other text included).

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01689/joss.01689/10.21105.joss.01689.pdf)

**Comment by kellykochanski** [comment]
Got it. @labarba one more technical question - the references are not included in the .pdf, even though @whedon was clearly reading them and didn't give me an error. What should I do to trouble shoot?

**Comment by labarba** [comment]
I don't know why the references are not rendering. @arfon?

Also, remove the section "Availability," as the JOSS article template includes links to the software repository (and permanent archive) on the margin decorators of the front page.

**Comment by kellykochanski** [comment]
@whedon generate pdf from branch kk/JOSS-fixes

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch kk/JOSS-fixes. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1689 with the following error: 

 Could not find bibliography file: docs/paper.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by kellykochanski** [comment]
@whedon generate pdf from branch kk/JOSS-fixes

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch kk/JOSS-fixes. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1689 with the following error: 

 Could not find bibliography file: paper/paper.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@kellykochanski - this PR should allow your paper to compile: https://github.com/kellykochanski/rescal-snow/pull/25

Also, please make sure the bibtex keys you're citing in your `paper.md` are _exactly_ the same as the ones in the bibtex. You currently have (for example) a citation to `@Kobayashi:1980` in your `paper.md` but the bibtex key in `paper.bib` is `Kobayashi1980`. So you either need to remove the `:` from the string in `paper.md` or change the key in `paper.bib` to `Kobayashi:1980`.

Hopefully that makes sense? It looks like a large number of your references have this issue.

**Comment by labarba** [comment]
@whedon generate pdf from branch kk/JOSS-fixes

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch kk/JOSS-fixes. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01689/joss.01689/10.21105.joss.01689.pdf)

**Comment by arfon** [comment]
Just an FYI, the author still needs to fix the citations to their bibtex keys before the references will show up properly.

**Comment by kellykochanski** [comment]
@whedon generate pdf from branch kk/JOSS-fixes

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch kk/JOSS-fixes. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01689/joss.01689/10.21105.joss.01689.pdf)

**Comment by kellykochanski** [comment]
@whedon generate pdf from branch kk/JOSS-fixes

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch kk/JOSS-fixes. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01689/joss.01689/10.21105.joss.01689.pdf)

**Comment by kellykochanski** [comment]
@whedon generate pdf from branch kk/JOSS-fixes

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch kk/JOSS-fixes. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1689 with the following error: 

 Error reading bibliography ./paper.bib (line 95, column 10):
unexpected ","
expecting white space
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by kellykochanski** [comment]
@whedon generate pdf from branch kk/JOSS-fixes

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch kk/JOSS-fixes. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01689/joss.01689/10.21105.joss.01689.pdf)

**Comment by kellykochanski** [comment]
This is now readable. There is still one issue that confuses me: the "Kochanski 2019" reference sometimes renders as "Kochanski, Anderson & Tucker 2019" and sometimes as "Kochanski et al. 2019". This seems slightly arbitrary but does not affect readability.

**Comment by kellykochanski** [comment]
@whedon generate pdf from branch kk/JOSS-fixes

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch kk/JOSS-fixes. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01689/joss.01689/10.21105.joss.01689.pdf)

**Comment by kellykochanski** [comment]
@whedon generate pdf from branch kk/JOSS-fixes

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch kk/JOSS-fixes. Reticulating splines etc...
```

**Comment by rgmyr** [comment]
@kthyng @kellykochanski Apologies for the delay. I also probably won't be able to start until at least the end of next week, but in any case I would be happy to review this!

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01689/joss.01689/10.21105.joss.01689.pdf)

**Comment by kellykochanski** [comment]
@whedon generate pdf from branch kk/JOSS-fixes

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch kk/JOSS-fixes. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01689/joss.01689/10.21105.joss.01689.pdf)

**Comment by kellykochanski** [comment]
@kthyng @rgmyr Thanks for agreeing to review - I look forward to your feedback.

**Comment by kellykochanski** [comment]
@whedon generate pdf from branch kk/JOSS-fixes

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch kk/JOSS-fixes. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01689/joss.01689/10.21105.joss.01689.pdf)

**Comment by kthyng** [comment]
great! We have two reviewers so we will proceed with the review issue.

**Comment by kthyng** [comment]
@whedon assign @zbeekman as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @zbeekman

**Comment by kthyng** [comment]
@whedon add @rgmyr as reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1699. Feel free to close this issue now!
