### ISSUE TITLE
[REVIEW]: Limarka: making possible Brazilian students writing dissertation and thesis with Markdown

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#169]
**Submitting author:** @edusantana (<a href="http://orcid.org/0000-0002-9165-9438">Eduardo Alexandre</a>)
**Repository:** <a href="https://github.com/abntex/limarka" target ="_blank">https://github.com/abntex/limarka</a>
**Version:** v0.6.6
**Editor:** @acabunoc
**Reviewer:** @alanlivio
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.256850" target="_blank">10.5281/zenodo.256850</a>

## Status

[![status](http://joss.theoj.org/papers/5aa10bb69bfbfc3faa0b799f9654e0c1/status.svg)](http://joss.theoj.org/papers/5aa10bb69bfbfc3faa0b799f9654e0c1)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/5aa10bb69bfbfc3faa0b799f9654e0c1"><img src="http://joss.theoj.org/papers/5aa10bb69bfbfc3faa0b799f9654e0c1/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/5aa10bb69bfbfc3faa0b799f9654e0c1/status.svg)](http://joss.theoj.org/papers/5aa10bb69bfbfc3faa0b799f9654e0c1)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/abntex/limarka" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/abntex/limarka">repository url</a>?
- [x] **Version:** Does the release version given match the GitHub release (v0.6.6)?
- [x] **Authorship:** Has the submitting author (@edusantana) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @alanlivio it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by acabunoc** [comment]
version updated to v0.6.6

**Comment by alanlivio** [comment]
Hello @acabunoc.
I finish the review. But I found a problem in the form.
I believe that the item " Version: Does the release version given match the GitHub release (v0.5.2)?" should be changed to v0.6.6, right?

**Comment by alanlivio** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by edusantana** [comment]
@whedon set 10.5281/zenodo.256850 as archive

**Comment by whedon** [comment]
I'm sorry @edusantana, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by alanlivio** [comment]
Hello @acabunoc.
I finish the review.
I only see the version problem.
How proceed to conclude the review.

**Comment by edusantana** [comment]
Hi @acabunoc Do you need any thing else? An other reviewer?

**Comment by acabunoc** [comment]
Thanks for the quick review @alanlivio!

The form is updated. I like how you have an Open Canvas in your docs 😄 .

Once I set the archive we should be good to go! Flagging @arfon 🎏

**Comment by acabunoc** [comment]
@whedon set 10.5281/zenodo.256850 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.256850" target="_blank">10.5281/zenodo.256850</a> is the archive.

**Comment by acabunoc** [comment]
Also, @arfon, I manually updated the version number. Not sure if this breaks something behind the scenes.

**Comment by edusantana** [comment]
@acabunoc about the open canvas, I enjoy doing it. Thank you for that. I discovered it looking at your repositories. But [this tip](https://blog.cwrichardkim.com/how-to-get-hundreds-of-stars-on-your-github-project-345b065e20a2#.k7ckcoxgt) was also good, for creating an animated gif.

**Comment by arfon** [comment]
Thanks for the review here @alanlivio and for editing this submission @acabunoc ✨ 

@edusantana - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00169 ⚡️ 🚀 💥
