### ISSUE TITLE
[PRE REVIEW]: Computing diffusion coeﬀicients in macromolecular simulations: the Diffusion Coeﬀicient Tool for VMD

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1692]
**Submitting author:** @tonigi (<a href="http://orcid.org/0000-0001-6449-0596">Toni Giorgino</a>)
**Repository:** <a href="https://github.com/giorginolab/vmd_diffusion_coefficient" target ="_blank">https://github.com/giorginolab/vmd_diffusion_coefficient</a>
**Version:** v1.1
**Editor:** @labarba
**Reviewers:** @jrperilla, @HaoZeke

**Author instructions**

Thanks for submitting your paper to JOSS @tonigi. **Currently, there isn't an JOSS editor assigned** to your paper.

@tonigi if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #1692 with the following error: 

 [WARNING] Could not convert image '/tmp/tex2pdf.962/12b5aeb93b39501746a99beed35229b93c87b40b.svg': check that rsvg2pdf is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.962/12b5aeb93b3
9501746a99beed35229b93c87b40b.svg (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.393 ...aeb93b39501746a99beed35229b93c87b40b.svg}

Looks like we failed to compile the PDF

**Comment by tonigi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01692/joss.01692/10.21105.joss.01692.pdf)

**Comment by tonigi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01692/joss.01692/10.21105.joss.01692.pdf)

**Comment by tonigi** [comment]
I may suggest @jhenin as a reviewer.

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@whedon assign @jrperilla as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jrperilla

**Comment by labarba** [comment]
👋 @jrperilla — Thanks for agreeing to review this JOSS submission! I'm on the lookout for a second reviewer, and once we add them, we can start the review issue. In the meantime, feel free to start checking out the software, and you can also open issues in their repository as needed.

**Comment by HaoZeke** [comment]
Ah, may I put myself forward to review this? @labarba

**Comment by labarba** [comment]
Of course! Thanks for volunteering—let's get this show on the road.

**Comment by labarba** [comment]
@whedon add @HaoZeke as reviewer

**Comment by whedon** [comment]
OK, @HaoZeke is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by labarba** [comment]
Hmm. We're experiencing a little hiccup. @arfon — our dearest bot is not responding to `start review` here. Any ideas?

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1698. Feel free to close this issue now!

**Comment by jrperilla** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01692/joss.01692/10.21105.joss.01692.pdf)

**Comment by labarba** [comment]
👋  @jrperilla — the review is happening here: https://github.com/openjournals/joss-reviews/issues/1698
