### ISSUE TITLE
[REVIEW]: Python KM: Kramers--Moyal coefficients for stochastic processes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1693]
**Submitting author:** @LRydin (<a href="http://orcid.org/0000-0001-5513-0580">Leonardo Rydin Gorjão</a>)
**Repository:** <a href="https://github.com/LRydin/KramersMoyal" target ="_blank">https://github.com/LRydin/KramersMoyal</a>
**Version:** v0.4
**Editor:** @kthyng
**Reviewer:** @dawbarton , @Shibabrat 
**Archive:** <a href="https://doi.org/10.21105/joss.01693" target="_blank">10.21105/joss.01693</a>

## Status

[![status](https://joss.theoj.org/papers/f8158e61d51e0a9822dcc69a4a3c1f4d/status.svg)](https://joss.theoj.org/papers/f8158e61d51e0a9822dcc69a4a3c1f4d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f8158e61d51e0a9822dcc69a4a3c1f4d"><img src="https://joss.theoj.org/papers/f8158e61d51e0a9822dcc69a4a3c1f4d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f8158e61d51e0a9822dcc69a4a3c1f4d/status.svg)](https://joss.theoj.org/papers/f8158e61d51e0a9822dcc69a4a3c1f4d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/LRydin/KramersMoyal" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dawbarton  & @Shibabrat , please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/LRydin/KramersMoyal">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@LRydin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/LRydin/KramersMoyal">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@LRydin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dawbarton , @Shibabrat  it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01693/joss.01693/10.21105.joss.01693.pdf)

**Comment by kthyng** [comment]
Hi @dawbarton , @Shibabrat, just a ping to do your review when you can. Thanks!

**Comment by dawbarton** [comment]
I've made comments for the authors in https://github.com/LRydin/KramersMoyal/issues/4 and https://github.com/LRydin/KramersMoyal/issues/5

**Comment by LRydin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01693/joss.01693/10.21105.joss.01693.pdf)

**Comment by LRydin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01693/joss.01693/10.21105.joss.01693.pdf)

**Comment by LRydin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01693/joss.01693/10.21105.joss.01693.pdf)

**Comment by kthyng** [comment]
@Shibabrat How is your review coming along?

**Comment by Shibabrat** [comment]
@kthyng It's going slowly since I'm also learning the theory behind the package to be sure my feedback is useful but I'll speed-up. Apologies for the delay.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01693/joss.01693/10.21105.joss.01693.pdf)

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01693/joss.01693/10.21105.joss.01693.pdf)

**Comment by kthyng** [comment]
Hi @Shibabrat will you be able to complete your review soon?

**Comment by Shibabrat** [comment]
@kthyng I've gone through the recent version of the software and it satisfies all the requirements, as far as I can access. The only remaining item is the community guidelines issue.

**Comment by kthyng** [comment]
Thanks for your review @Shibabrat! 

@LRydin looks to me like you have just a few last things to address.

**Comment by LRydin** [comment]
Dear @kthyng ,

great news :). I will once more go over the paper, bib, etc, and I will revised with my former and present supervisor which funding applies (I believe as is should be correct, but I want to double check). 

I still want to add some docs before the publication is out (as in readthedocs), if that is okay with you. If you feel the publication can be made available before, that is of course also possible.

I will attend to the community guidelines and return to you once it is sorted.

Best,
Leonardo Rydin
@fmeirinhos

**Comment by kthyng** [comment]
@LRydin sounds good to me! Let me know when you're ready to proceed.

**Comment by LRydin** [comment]
Dear @kthyng ,

I've commented on the open issue [#7](https://github.com/LRydin/KramersMoyal/issues/7), added a Conduct of Fairness, and address a bit more the Contributions. I don't know if this suffices thought.

In the meanwhile I have one (kind'a silly) question: We referred to this package so far as Python KM, but have used more extensively `KramersMoyal`. I was wondering if it would make sense to resolve this somewhat ambiguous mentioning and simply refer to is as `KramersMoyal` and remove entirely the Python KM?
(This would imply also altering the title of the paper to "KramersMoyal: Kramers–Moyal coefficients for stochastic processes in python")

I find KM a bit too short and ambiguous (km as in kilometers...). E.g, MC for Monte Carlo is fairly used, but KM for Kramers–Moyal is not...

Best regards,
Leonardo Rydin
@fmeirinhos

**Comment by kthyng** [comment]
@LRydin I've pinged @Shibabrat on your issue to look at your work.

You can change the name of your package if you would like, including in the title of the paper, etc. Just go ahead and make all the changes if you want to do so.

**Comment by LRydin** [comment]
Dear @kthyng,

wonderful, I'll make the changes then. I'm rereading the paper to ensure everything is okay. I'll commit the corrected version with the "new" name as soon as it is ready.

Best,
Leonardo Rydin
@fmeirinhos

**Comment by LRydin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01693/joss.01693/10.21105.joss.01693.pdf)

**Comment by LRydin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01693/joss.01693/10.21105.joss.01693.pdf)

**Comment by LRydin** [comment]
Dear @kthyng, @Shibabrat, and @dawbarton,

I have made all the changes I deemed necessary. I reread the paper and made the final corrections. In this manner, I have only two remarks:
 - I've added the explicit mention of what the kernel-based estimations is: The [Nadaraya–Watson kernel regression](https://en.wikipedia.org/wiki/Kernel_regression), and the two relevant references there from Nadaraya and Watson.
- I've resized the figures and altered the name to `kramersmoyal`, as is both the name of the package and the GitHub repository.

There is one last issue: the paper *Analysis and data-driven reconstruction of bivariate jump-diffusion processes* that is referenced as being in the ArXiv is now in production. It was accepted last week. I believe it would be positive to add the actual reference (once the journal assigns an issue and number). @kthyng How should we proceed in this regard? Await for the issue number or publish with the reference to the ArXiv?

I think that should be it. Thank you all for the corrections, reviews and suggestions.

Best,
Leonardo Rydin
@fmeirinhos

**Comment by kthyng** [comment]
@LRydin I think it makes sense to provide the most up to date information available when we're ready to finalize everything in your submission. Alternatively, if you prefer, we can wait for the full reference info on that paper and pause this in the meantime.

**Comment by kthyng** [comment]
@dawbarton Can you make a final check on this submission? I see a few boxes unchecked above.

**Comment by LRydin** [comment]
> @LRydin I think it makes sense to provide the most up to date information available when we're ready to finalize everything in your submission. Alternatively, if you prefer, we can wait for the full reference info on that paper and pause this in the meantime.

Dear @kthyng, I have reached out to the publisher to see if they already attributed an issue, but I have to wait for the publication procedure to advance a bit more. With luck next week there will be some more details, and then I could change the details in the JOSS paper. Else, I'd say, next week we finalise this, if all the boxes are ticked.

Best regards,
Leonardo Rydin
@fmeirinhos

**Comment by dawbarton** [comment]
@kthyng: boxes now checked! Looks good to me.

**Comment by LRydin** [comment]
Dear @kthyng,

I think we should proceed. I'll stick with the ArXiv version of the paper, as in the end the doi of the final publication is likely to also be linked to the same (ArXiv) doi. Should I alter the reference and include *in press* and the journal's name (Phys. Rev. E.)?

On another note, thank you @dawbarton and @Shibabrat for the reviews, the paper and the library are certainly looking better! I'm excited about my first JOSS publication.

Best,
Leonardo Rydin
@fmeirinhos

**Comment by kthyng** [comment]
@LRydin Yes that change sounds appropriate. Let me know when you're done and we can proceed.

**Comment by LRydin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01693/joss.01693/10.21105.joss.01693.pdf)

**Comment by LRydin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01693/joss.01693/10.21105.joss.01693.pdf)

**Comment by LRydin** [comment]
Dear @kthyng,

That's that. It is ready. The last thing to do is to get the figures out of the tables and simply utilise captions... which I have no idea how it's done... Do you do that on your side, in the processing for the publication?

Best regards,
Leonardo Rydin
@fmeirinhos

**Comment by kthyng** [comment]
@LRydin I have edited the figures in your paper in PR [#8](https://github.com/LRydin/KramersMoyal/pull/8). If you think the paper looks good with the changes, you can accept the PR.

**Comment by LRydin** [comment]
Dear @kthyng,

I've accepted the PR, but also added a left and right margin to the figures, to have them all in the same size. I've updated the repo. I think that should be that :).

Cheers,
Leonardo Rydin
@fmeirinhos

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01693/joss.01693/10.21105.joss.01693.pdf)

**Comment by kthyng** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1137/1114019 is OK
- 10.1088/1367-2630/aaf0d7 is OK
- 10.1038/srep35435 is OK
- 10.1016/j.physleta.2009.07.073 is OK
- 10.1063/1.5019320 is OK
- 10.1111/1540-6261.00489 is OK
- 10.5334/jors.123 is OK
- 10.1201/9781315140919 is OK
- 10.1007/978-3-030-18472-8 is OK
- 10.1007/978-3-642-61544-3 is OK
- 10.1137/1109020 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
I have made some correction for your paper in this PR: https://github.com/LRydin/KramersMoyal/pull/9

**Comment by kthyng** [comment]
We recommend making an official release for your submission. I see we have v0.31 marked. I want to find out 1. if that is still the correct version number and 2. if it is, are you interested in making a corresponding git release to match?

**Comment by kthyng** [comment]
The subsequent step is to make an archive of your work at a place like Zenodo, then report the DOI back here. Please make sure that the title and author list of your work in Zenodo exactly match your paper here.

**Comment by LRydin** [comment]
Dear @kthyng,

> We recommend making an official release for your submission. I see we have v0.31 marked. I want to find out 1. if that is still the correct version number and 2. if it is, are you interested in making a corresponding git release to match?

1. The current version is at 0.4
2. Zenodo: Done. Here is the link: https://zenodo.org/record/3581328#.XfkWPdnTWbd and the DOI is 10.21105/joss.01693

I have accepted the last PR and corrected the suggested spellings.

Cheers,
Leonardo
@fmeirinhos

**Comment by kthyng** [comment]
Are you interested in making a formal github release, such that it would show up here: https://github.com/LRydin/KramersMoyal/releases

You can get more info here: https://help.github.com/en/github/administering-a-repository/creating-releases

**Comment by LRydin** [comment]
Seems like a good idea @kthyng. Should I do so now?

**Comment by kthyng** [comment]
But I will still check in despite being out of office for travel.

**Comment by kthyng** [comment]
> Seems like a good idea @kthyng. Should I do so now?

Yes, please do.

**Comment by LRydin** [comment]
I'll get to it right away. I'll repost here in a bit.

**Comment by LRydin** [comment]
@kthyng Here it is: https://github.com/LRydin/KramersMoyal/releases/tag/v0.4

**Comment by kthyng** [comment]
@whedon set v0.4 as version

**Comment by whedon** [comment]
OK. v0.4 is the version.

**Comment by kthyng** [comment]
/ooo December 18, 2019 to January 7, 2020

**Comment by kthyng** [comment]
@whedon set 10.21105/joss.01693 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.21105/joss.01693" target="_blank">10.21105/joss.01693</a> is the archive.

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1137/1114019 is OK
- 10.1088/1367-2630/aaf0d7 is OK
- 10.1038/srep35435 is OK
- 10.1016/j.physleta.2009.07.073 is OK
- 10.1063/1.5019320 is OK
- 10.1111/1540-6261.00489 is OK
- 10.5334/jors.123 is OK
- 10.1201/9781315140919 is OK
- 10.1007/978-3-030-18472-8 is OK
- 10.1007/978-3-642-61544-3 is OK
- 10.1137/1109020 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1187

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1187, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1207750511849549828) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1188
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01693](https://doi.org/10.21105/joss.01693)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new paper @LRydin!!! Thanks to  reviewers @dawbarton and @Shibabrat — we couldn't have done this without your time and expertise.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01693/status.svg)](https://doi.org/10.21105/joss.01693)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01693">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01693/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01693/status.svg
   :target: https://doi.org/10.21105/joss.01693
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01693/status.svg)](https://doi.org/10.21105/joss.01693)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by LRydin** [comment]
Exciting! Thanks @kthyng, @dawbarton and @Shibabrat. I will proceed to do
> Party like you just published a paper! 

as expected :)

Thank you all again.
Cheers,
Leonardo Rydin
@fmeirinhos
