### ISSUE TITLE
[PRE REVIEW]: DEPP - Differential Evolution Parallel Program

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1694]
**Submitting author:** @gbertoldo (<a href="http://orcid.org/0000-0002-1888-9181">Guilherme Bertoldo</a>)
**Repository:** <a href="https://github.com/gbertoldo/DEPP" target ="_blank">https://github.com/gbertoldo/DEPP</a>
**Version:** v1.0.0
**Editor:** @meg-simula
**Reviewers:** @HaoZeke, @dham

**Author instructions**

Thanks for submitting your paper to JOSS @gbertoldo. **Currently, there isn't an JOSS editor assigned** to your paper.

@gbertoldo if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01694/joss.01694/10.21105.joss.01694.pdf)

**Comment by labarba** [comment]
@gbertoldo — I think you need to remove the backticks around the citations, so the references will get processed when compiling the paper. After you push the changes, you can run `@whedon generate pdf` alone in a comment here to compile the paper again.

**Comment by labarba** [comment]
👋  @meg-simula — Maybe this could be a good paper for you to edit? Have a look and let me know if you can lead this one. 
"DEPP - Differential Evolution Parallel Program" https://github.com/gbertoldo/DEPP

**Comment by gbertoldo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01694/joss.01694/10.21105.joss.01694.pdf)

**Comment by gbertoldo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01694/joss.01694/10.21105.joss.01694.pdf)

**Comment by gbertoldo** [comment]
I think it is good now. Thank you @labarba!

**Comment by meg-simula** [comment]
Sure @labarba. I'll just assign myself.

**Comment by meg-simula** [comment]
@whedon assign @meg-simula as editor

**Comment by whedon** [comment]
OK, the editor is @meg-simula

**Comment by HaoZeke** [comment]
Hi @meg-simula. May I put myself forward for this? I really like modern fortran :grin:

**Comment by meg-simula** [comment]
Hi @HaoZeke, thanks for volunteering! Sure, that would be great. I'll assign you.

**Comment by meg-simula** [comment]
@whedon assign @HaoZeke as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @HaoZeke

**Comment by meg-simula** [comment]
I've contacted David Ham (via email) to also review this paper, and he has agreed. I'll add him as an reviewer and let whedon start the review now.

**Comment by meg-simula** [comment]
@whedon add @dham as reviewer

**Comment by whedon** [comment]
OK, @dham is now a reviewer

**Comment by meg-simula** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1701. Feel free to close this issue now!
