### ISSUE TITLE
[PRE REVIEW]: RepnDecomp: A GAP package for decomposing linear representations of finite groups

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1695]
**Submitting author:** @kaashif (<a href="http://orcid.org/0000-0001-8581-5804">Kaashif Hymabaccus</a>)
**Repository:** <a href="https://gitlab.com/kaashif/decomp/" target ="_blank">https://gitlab.com/kaashif/decomp/</a>
**Version:** 0.1
**Editor:** @VivianePons
**Reviewers:** @alex-konovalov, @falque

**Author instructions**

Thanks for submitting your paper to JOSS @kaashif. **Currently, there isn't an JOSS editor assigned** to your paper.

@kaashif if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1695 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1695 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-80a4e9edb5a6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01695/joss.01695/10.21105.joss.01695.pdf)

**Comment by labarba** [comment]
👋 @VivianePons — the author suggested you as handling editor... are you back from leave? This is right up your alley.
"RepnDecomp: A GAP package for decomposing linear representations of finite groups"
https://gitlab.com/kaashif/decomp/

**Comment by labarba** [comment]
That answers my question! Will look for another editor.

**Comment by arfon** [comment]
:wave: @meg-simula - would you be willing to edit this submission for JOSS?

**Comment by meg-simula** [comment]
Thanks for asking - but this submission is quite outside my area of expertise, so I'm a bit reluctant to jump in.

**Comment by arfon** [comment]
> Thanks for asking - but this submission is quite outside my area of expertise, so I'm a bit reluctant to jump in.

OK thanks @meg-simula 

@kaashif - we have an editor that would be perfect for this submission but she's currently out on maternity leave for the next month. Would it be acceptable to you to wait for a month before moving the submission forward?

**Comment by kaashif** [comment]
That's fine, there's no rush for me.

**Comment by arfon** [comment]
> That's fine, there's no rush for me.

Great. I'll go ahead and assign the editor but also mark the submission as paused for now. Our editor should be back in the ~1 month!

**Comment by arfon** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by alex-konovalov** [comment]
@dimpase in which case we can ask if anyone outside is interested to review it, I will be happy to assist reviewers with checking regression tests. @kaashif could you please adjust the output of the default package test - see diffs in https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-devel/jobs/584474552

**Comment by labarba** [comment]
👋 I've removed the "paused" label on this, as @VivianePons should be back to editing now.

**Comment by VivianePons** [comment]
@alex-konovalov I would actually like to have you as a reviewer even if you work in the same department as @dimpase. As I know you personally, I trust your judgment! And I will look for a secondary reviewer anyway.

**Comment by alex-konovalov** [comment]
@VivianePons thanks, will be happy to review then - makes sense, since I run the package update system for GAP and have access to tools for automated checks. We need also to discuss with @dimpase and @kaashif plans for submitting this package for the redistribution with GAP, and perhaps align the two processes. In the meantime, it would be useful if you could fix tests at https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-devel, address some issues at https://gitlab.com/kaashif/decomp/, and think whether you may want to migrate to https://github.com/gap-packages or establish a proper website on GitLab by adapting https://github.com/gap-system/ReleaseTools and 
https://github.com/gap-system/GitHubPagesForGAP

**Comment by VivianePons** [comment]
@whedon assign @alex-konovalov as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @alex-konovalov

**Comment by kaashif** [comment]
Acknowledged, will work on fixing those tests and issues. I've just started a new job and been quite busy which is why I haven't gotten around to it yet, sorry about that.

**Comment by alex-konovalov** [comment]
@kaashif thanks. I've invited you to https://github.com/orgs/gap-packages/ and then you should be to migrate the repository. I suggest then to discuss technical details there.

**Comment by VivianePons** [comment]
@whedon add @falque as reviewer

**Comment by whedon** [comment]
OK, @falque is now a reviewer

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1835. Feel free to close this issue now!

**Comment by alex-konovalov** [comment]
Thanks @VivianePons. I've checked https://github.com/openjournals/joss/blob/master/COI.md - just to confirm with you as an editor, do we agree that I can tick the COI box in the review, since being involved with @dimpase in OpenDreamKit and CoDiMa projects, and being employed at the same institution (since recently) in not a CoI in this particular case?

**Comment by VivianePons** [comment]
Yes, it's ok, it's been "disclosed and waived"
