### ISSUE TITLE
[PRE REVIEW]: ndsplines: A Python Library for Tensor-Product B-Splines of Arbitrary Dimension

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1697]
**Submitting author:** @sixpearls (<a href="http://orcid.org/0000-0001-5602-1888">Benjamin Margolis</a>)
**Repository:** <a href="https://github.com/kb-press/ndsplines/" target ="_blank">https://github.com/kb-press/ndsplines/</a>
**Version:** v0.1.0
**Editor:** @mbobra
**Reviewers:** @amritagos, @sarats

**Author instructions**

Thanks for submitting your paper to JOSS @sixpearls. **Currently, there isn't an JOSS editor assigned** to your paper.

@sixpearls if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01697/joss.01697/10.21105.joss.01697.pdf)

**Comment by labarba** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.21105/joss.00396 may be missing for title: SimuPy: A Python framework for modeling and simulating dynamical systems.
- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation
- https://doi.org/10.1109/mcse.2010.118 may be missing for title: Cython: The best of both worlds
- https://doi.org/10.2514/6.2019-2901 may be missing for title: Developing an Entry Guidance and Control Design Capability Using Flaps for the Lifting Nano-ADEPT
- https://doi.org/10.2514/6.2002-4482 may be missing for title: Flight dynamic model exchange using XML

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@sixpearls — Please add DOIs to your references; our bot `whedon` has given you some tips above. Also, the reference label `@deboor` is not present in your `.bib` file, and thus you get `???` in the paper where you cited that.

**Comment by labarba** [comment]
👋  @mbobra — Could you handle this JOSS submission as editor?
"ndsplines: A Python Library for Tensor-Product B-Splines of Arbitrary Dimension"
repo: https://github.com/kb-press/ndsplines/

**Comment by sixpearls** [comment]
@labarba Thanks, I will correct the bibliography.

@whedon commands

**Comment by labarba** [comment]
`whedon` likes to get its commands as a single-line comment

**Comment by sixpearls** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01697/joss.01697/10.21105.joss.01697.pdf)

**Comment by sixpearls** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01697/joss.01697/10.21105.joss.01697.pdf)

**Comment by arfon** [comment]
I'm going to go ahead and assign @mbobra as the handling editor for this submission. @sixpearls - it's going to be another week or so before @mbobra is back to JOSS editorial activities - your patience is much appreciated :-)

**Comment by arfon** [comment]
@whedon assign @mbobra as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by sixpearls** [comment]
@mbobra: Great, thanks! Let me or my co-author @ixjlyons know if there is anything we can do to help.

**Comment by sixpearls** [comment]
Hi @mbobra, any updates on reviewers? Is there any way we can help? Thanks!

**Comment by kthyng** [comment]
Hi @sixpearls did you look through the list of volunteer reviewers to see if you could find any suggestions? [Here](https://bit.ly/joss-reviewers) is the list. Suggesting a handful is most helpful if possible since we need two and people aren't always available.

**Comment by sixpearls** [comment]
Hi @vissarion, @amritagos, @hugoledoux, @HaoZeke, @trp07, @sarats, would two of you be willing to act as reviewers for this JOSS submission on N-dimensional splines? The repository is https://github.com/kb-press/ndsplines/, if you would like to check it out

**Comment by amritagos** [comment]
Thanks for suggesting me. I'd be happy to review this.

**Comment by HaoZeke** [comment]
Sorry, I wouldn't be able to look this over this week, as I'm dealing with 
a bit of backlog. If it's still around next week I'd be happy to look it 
over then.

**Comment by sarats** [comment]
I can review this.

**Comment by mbobra** [comment]
Thank you for volunteering to review @amritagos and @sarats! We really appreciate it ☀️

**Comment by mbobra** [comment]
@whedon assign @amritagos as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @amritagos

**Comment by mbobra** [comment]
@whedon add @sarats as reviewer

**Comment by whedon** [comment]
OK, @sarats is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1745. Feel free to close this issue now!

**Comment by mbobra** [comment]
@amritagos @sarats You can complete your review over on [this thread](https://github.com/openjournals/joss-reviews/issues/1745)! Please let me know if you have any questions.
