### ISSUE TITLE
[REVIEW]: Computing diffusion coeﬀicients in macromolecular simulations: the Diffusion Coeﬀicient Tool for VMD

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1698]
**Submitting author:** @tonigi (<a href="http://orcid.org/0000-0001-6449-0596">Toni Giorgino</a>)
**Repository:** <a href="https://github.com/giorginolab/vmd_diffusion_coefficient" target ="_blank">https://github.com/giorginolab/vmd_diffusion_coefficient</a>
**Version:** v1.2
**Editor:** @labarba
**Reviewer:** @jrperilla, @HaoZeke
**Archive:** <a href="https://doi.org/10.5281/zenodo.3445530" target="_blank">10.5281/zenodo.3445530</a>

## Status

[![status](https://joss.theoj.org/papers/25d51faf73cc17ae3affb51b787bbe18/status.svg)](https://joss.theoj.org/papers/25d51faf73cc17ae3affb51b787bbe18)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/25d51faf73cc17ae3affb51b787bbe18"><img src="https://joss.theoj.org/papers/25d51faf73cc17ae3affb51b787bbe18/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/25d51faf73cc17ae3affb51b787bbe18/status.svg)](https://joss.theoj.org/papers/25d51faf73cc17ae3affb51b787bbe18)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/giorginolab/vmd_diffusion_coefficient" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jrperilla & @HaoZeke, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @labarba know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/giorginolab/vmd_diffusion_coefficient">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@tonigi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/giorginolab/vmd_diffusion_coefficient">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@tonigi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jrperilla, @HaoZeke it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01698/joss.01698/10.21105.joss.01698.pdf)

**Comment by labarba** [comment]
👋  @jrperilla, @HaoZeke — Thank you for agreeing to review this submission for JOSS. At the top of this Review issue, each of you has a review checklist: work your way through it, and post any questions or comments for the authors here. You can also open new issues in the submission repository, linking to this thread here for a cross-reference. Godspeed!

**Comment by HaoZeke** [comment]
Thanks @labarba. Right, so, off the bat, @tonigi, the `LICENSE` file has issues, essentially, it is currently not an [OSI approved license](https://opensource.org/licenses/alphabetical). I am opening an issue in the repo to discuss this further.

**Comment by tonigi** [comment]
Thanks for spotting! Updated LICENSE to the BSD-3 text.

**Comment by HaoZeke** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/0263-7855(96)00018-5 is OK
- 10.1042/BJ20130960 is OK
- 10.1038/srep19839 is OK
- 10.33011/livecoms.1.1.5068 is OK
- 10.1016/S0006-3495(02)73971-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by tonigi** [comment]
@HaoZeke made amendments according to suggestions. Also, regarding the "Functionality" point, added an explanation of the demo calculation and how the results compare with experimental ones. :)

**Comment by HaoZeke** [comment]
@tonigi Thanks for the very prompt resolution of all points raised. @labarba I am pleased to say that I have completed my review, and recommend this for publication.

**Comment by labarba** [comment]
@jrperilla — May I ask for an update on your review?

**Comment by jrperilla** [comment]
The Diffusion Coefficient Tool in VMD offers a simple and accessible method to glean diffusion coefficients from mean square displacement of a molecular species within a molecular dynamics trajectory. Given that diffusion coefficients computed from MD data can help to validate equilibration or otherwise detect the presence of bulk motions, this software is of particular interest to the computational chemistry community. To test the method appropriately, i.e., following guidelines stated by the author in the JOSS manuscript, an equilibrated system was chosen describing roughly 30,000 TIP3P waters over 4 microseconds. While the plugin functioned as intended and produced consistent results given different values of stride and lag intervals, from both command-line and GUI, several concerns regarding the structure and design of the tool were noted during testing. 


1. https://github.com/giorginolab/vmd_diffusion_coefficient/issues/4
2. https://github.com/giorginolab/vmd_diffusion_coefficient/issues/5
3. https://github.com/giorginolab/vmd_diffusion_coefficient/issues/6

Minor issues or feature requests:

1. https://github.com/giorginolab/vmd_diffusion_coefficient/issues/7
2. https://github.com/giorginolab/vmd_diffusion_coefficient/issues/8
3. https://github.com/giorginolab/vmd_diffusion_coefficient/issues/9
4. https://github.com/giorginolab/vmd_diffusion_coefficient/issues/10

**Comment by tonigi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01698/joss.01698/10.21105.joss.01698.pdf)

**Comment by tonigi** [comment]
@jrperilla Thanks for the suggestions! Each item is answered in the corresponding issue. In short, all the added functionality now constitutes release 1.2. The paper and docs are updated accordingly.

**Comment by jrperilla** [comment]
I think all my concerns were addressed and the paper is ready for publication.

**Comment by jrperilla** [comment]
I want to shout out to @abryer94 for helping with the testing of the code.

**Comment by labarba** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/0263-7855(96)00018-5 is OK
- 10.1042/BJ20130960 is OK
- 10.1038/srep19839 is OK
- 10.33011/livecoms.1.1.5068 is OK
- 10.1016/S0006-3495(02)73971-4 is OK
- 10.1093/bioinformatics/btu037 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@whedon set v1.2 as version

**Comment by whedon** [comment]
OK. v1.2 is the version.

**Comment by labarba** [comment]
@tonigi — We're now going to need you to make an archive deposit in Zenodo (or a similar service) get a DOI, and post the DOI here.

Please edit the archive metadata so the title and author list matches the JOSS paper.

**Comment by tonigi** [comment]
Hi @labarba , just tried with Zenodo's GitHub integration and got ... 

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3445530.svg)](https://doi.org/10.5281/zenodo.3445530)

10.5281/zenodo.3445530

**Comment by tonigi** [comment]
@HaoZeke , @jrperilla , @abryer94 -- thanks for the thorough reviews!

@labarba -- thanks for managing!

Sorry for the nitpicking - I just wanted to point out that non-ascii "ff" combined characters slipped in the title. I guess it's better to rename them to plain "ff" before submission lest we hit some "undocumented feature" in the next steps such as cross-ref indexing etc.

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.3445530 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3445530" target="_blank">10.5281/zenodo.3445530</a> is the archive.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/968

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/968, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1174651494609620992) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/969
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01698](https://doi.org/10.21105/joss.01698)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @tonigi, your JOSS paper is now published! 🚀 

Huge thanks to our reviewers: @jrperilla, @HaoZeke — your contribution to JOSS is very much appreciated! 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01698/status.svg)](https://doi.org/10.21105/joss.01698)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01698">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01698/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01698/status.svg
   :target: https://doi.org/10.21105/joss.01698
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01698/status.svg)](https://doi.org/10.21105/joss.01698)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
