### ISSUE TITLE
[REVIEW]: Rescal-snow: A model for dunes and snow-waves

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1699]
**Submitting author:** @kellykochanski (<a href="http://orcid.org/0000-0003-0754-0184">Kelly Kochanski</a>)
**Repository:** <a href="https://github.com/kellykochanski/rescal-snow" target ="_blank">https://github.com/kellykochanski/rescal-snow</a>
**Version:** v1.1.1
**Editor:** @kthyng
**Reviewers:** @zbeekman, @rgmyr
**Archive:** <a href="https://doi.org/10.5281/zenodo.3517217" target="_blank">10.5281/zenodo.3517217</a>

## Status

[![status](https://joss.theoj.org/papers/822d9380fa5ce6f89cbbdebf1605df14/status.svg)](https://joss.theoj.org/papers/822d9380fa5ce6f89cbbdebf1605df14)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/822d9380fa5ce6f89cbbdebf1605df14"><img src="https://joss.theoj.org/papers/822d9380fa5ce6f89cbbdebf1605df14/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/822d9380fa5ce6f89cbbdebf1605df14/status.svg)](https://joss.theoj.org/papers/822d9380fa5ce6f89cbbdebf1605df14)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/kellykochanski/rescal-snow" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@zbeekman & @rgmyr, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kellykochanski/rescal-snow">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@kellykochanski) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kellykochanski/rescal-snow">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@kellykochanski) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @zbeekman it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01699/joss.01699/10.21105.joss.01699.pdf)

**Comment by kthyng** [comment]
I just saw that I closed the pre-review issue before whedon had actually added the second reviewer. I have gone in and edited the first comment by hand to add @rgmyr. However, I see that he is not listed as an "Assignee" at the top right of the page, and I can't add him. @arfon is this important? Will @rgmyr have all necessary permissions the way I have added him?

**Comment by arfon** [comment]
@whedon add @rgmyr as reviewer

**Comment by whedon** [comment]
OK, @rgmyr is now a reviewer

**Comment by arfon** [comment]
> @whedon add @rgmyr as reviewer

@kthyng doing this ☝️makes Whedon give the reviewer the permission on the repository (although it doesn't make a new checklist). 

@rgmyr will need to accept the invite here: https://github.com/openjournals/joss-reviews/invitations

**Comment by kthyng** [comment]
Thanks @arfon! Looks like both reviewers are able to make edits now.

**Comment by rgmyr** [comment]
Minor issue on the paper affiliations list: the '2' for LLNL is in the wrong place (comes after instead of before). I think this is because in `paper.md`, that line should just be `index: 2` instead of `- index: 2`.

**Comment by rgmyr** [comment]
I've had a couple of (possibly related) installation issues, which I've created tickets for:

- [JOSS Review (@rgmyr): ZLIB not found by CMake](https://github.com/kellykochanski/rescal-snow/issues/26)
- [JOSS Review (@rgmyr): Release build fails](https://github.com/kellykochanski/rescal-snow/issues/27)

In the meantime, I now at least have the software running and will try to continue with the rest of the Functionality and Documentation points.

**Comment by kellykochanski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01699/joss.01699/10.21105.joss.01699.pdf)

**Comment by kellykochanski** [comment]
@rgmyr We've updated the build system and installation instructions to fix these issues. Zlib is now a dependency and is not explicitly linked within Rescal-snow.

**Comment by kellykochanski** [comment]
@zbeekman We're looking forward to your comments. Have you had any trouble with the repository?

**Comment by rgmyr** [comment]
My installation issues were fixed by the build update and additional dependency instructions.

My only other change request was regarding documentation and style consistency of the included Python utilities, which @kellykochanski promptly improved:
- [JOSS Review (@rgmyr): Python utilities documentation and style](https://github.com/kellykochanski/rescal-snow/issues/28)

I should note that I wasn't able to test the functionality related to parallel simulation runs, simply because I don't have access to any remote computing clusters at this time. With that said, it looks pretty straightforward and reasonable based on my previous experiences with `slurm`-scheduled systems.

That completes my review checklist, so I'm happy to recommend acceptance of this submission.

**Comment by zbeekman** [comment]
@kellykochanski I just wanted to update you on my progress. (I know you're busy responding to issues & coding so no need to respond.) So far I have:

- Built & tested on macOS w/ native & Homebrew tooling
  - Opened https://github.com/kellykochanski/rescal-snow/pull/42 to resolve building with brewed gccs
- Thoroughly reviewed documentation and submitted some PRs for broken links etc.
  - Very nice documentation documents & tutorial
- Thoroughly reviewed the paper
  - Again, very nice!

To conclude the review I will do the following (out of time today):

- Build and test on Linux with Intel compilers & gcc
- Perform the parallel parameter space study in the tutorial
- Verify (quick and dirty) performance numbers in the parallelism/performance document

Outstanding issues (so far) that I think need to be resolved, in order of severity:

- [ ] https://github.com/kellykochanski/rescal-snow/issues/41
- [ ] https://github.com/kellykochanski/rescal-snow/issues/35
- [ ] https://github.com/kellykochanski/rescal-snow/issues/37

Some CI testing and/or single test script to verify the tutorial works would have probably prevented https://github.com/kellykochanski/rescal-snow/issues/41 and would be really good to add. (You probably cannot do the last parametric parameter study example on a free CI solution, but a script for including this could be a good supplement to CI testing here.

So far things look really good! I think https://github.com/kellykochanski/rescal-snow/issues/41 definitely should be addressed/resolved before publication, but most of the other things are pretty minor.

**Comment by kellykochanski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01699/joss.01699/10.21105.joss.01699.pdf)

**Comment by kellykochanski** [comment]
@zbeekman I believe these issues have now been addressed; issues 35 and 37 are closed, and it would be great if you could confirm our work on [41](https://github.com/kellykochanski/rescal-snow/issues/41).

I'm curious to see your results for the performance test.

**Comment by kellykochanski** [comment]
@zbeekman Do you know when you will have time to look at this?

**Comment by zbeekman** [comment]
On the agenda for today! Thanks for the nudge.

**Comment by zbeekman** [comment]
I think I have more or less concluded my review. There are many great features of rescal-snow, and, in most circumstances, building it was straight forwards. I've tested it on:

- macOS with clang
- macOS with GCC 9
- HPC cluster with GCC 6
- HPC cluster with Intel 18

In general there is a fairly large quantity of usage documentation and tutorials. At times this has been a double edged sword because the documentation and tutorials are markdown documents which can become out of sync with the project and software. Overall, the software testing and processes relating to reproducibility and quality assurance do leave some room for improvement. Despite this, these areas have improved over the course of this review, which is encouraging.

*I am recommending publication with minor revisions*, discussed in https://github.com/kellykochanski/rescal-snow/issues/41 and https://github.com/kellykochanski/rescal-snow/issues/44. The *main* software package seems fairly robust and has some really interesting capabilities. Some of the supporting scripts and pre/post-processing tools do not appear to be as robust as I would like, and caused me to devote more time than I would have liked to troubleshooting. Nevertheless, I feel that the overall package meets the requirements for JOSS publication. The weakest points, in my opinion, are in the `Documentation` section, in particular, __Automated Tests__ and __Functionality Documentation__. The __Functionality Documentation__ issues were because following the examples did not produce the results they claimed to due to bugs, most of which are fixed.

While I do not believe the aforementioned issues preclude rescal-snow from being published--i.e., "major revisions",--I recommend that the authors take additional steps (now or after publication) to reduce the brittleness and manual nature of a lot of the testing and documentation:

1. Setup CI testing
   - test on linux
   - test on macOS
   - test scripts (Bash and Python) used in tutorials and user-documentation
   - setup unit tests for Python modules/code
2. Setup static analysis (you can do this during CI) of the shell scripts and python modules & scripts as part of your quality assurance process
   - [ShellCheck](https://github.com/koalaman/shellcheck#installing) is a great tool for shell scripts
3. Consider transitioning shell scripts to either Python with robust exception handling or CMake tasks via custom targets and/or ctest tests
   - Python with exception handling is more robust and portable
   - Relying on CMake rather than *nix tools and bash scripts make it more likely to run on all major OSes and the CMake code can be exercised during CI testing or by quickly typing `ctest`.
4. Restructure some or all of the documentation, most notably the tutorial, as a Jupyter Notebook.
   - Test the notebook(s) during CI to ensure code changes haven't broken the examples and tutorials
   - This was probably the greatest source of delay and frustration during the review. Automating ways to check the code in the documentation and keeping code with documentation will help ensure things do not get out of sync.

Great job with rescal-snow!

**Comment by kellykochanski** [comment]
@zbeekman Thank you for the time and attention you have dedicated to this review.

**Comment by kellykochanski** [comment]
@zbeekman If you're willing to put a little bit of time into that, I'd be delighted - I looked into CI when you first brought it up (and it does seem like a sensible solution to some of the back and forth we were having), but it's outside of my current expertise.

I'm trying to avoid relying on Jupyter notebooks, unfortunately - I do production runs in an hpc environment without access to IPython, and the tutorial is used by students learning to work in the same environment.

**Comment by kellykochanski** [comment]
@kthyng The issues [#41](https://github.com/kellykochanski/rescal-snow/issues/41) and [#44](https://github.com/kellykochanski/rescal-snow/issues/44) are now closed, and I believe both reviewers have recommended JOSS acceptance.

**Comment by kthyng** [comment]
Awesome! I will start the next process then.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01699/joss.01699/10.21105.joss.01699.pdf)

**Comment by kthyng** [comment]
@whedon check references

**Comment by kthyng** [comment]
Paper-related changes:

- [ ] in the last paragraph of the first page, you need a semicolon between these two references: [@Kobayashi1980, @Kochanski2019]
- [ ] I think your caption for Fig 2 needs an extra line before it to get the spacing correct
- [ ] Your Liston2007 reference should have {} around {SnowTran-3D} so the capitalization is preserved.
- [ ] Same with the items in Lehning2002 reference that should be properly capitalized in your references list.
- [ ] Same for Gallee2012. You can check after you make changes by looking through the references list to make sure everything is capitalized correctly.

@openjournals/joss-eics Can anyone tell why in this paper the Marsh et al paper doesn't shorten to "Marsh et al' when referenced but instead displays all the authors? This is not consistent with other bib entries with fewer or more number of authors. And same question for the Narteau reference which displays all author names inline.

**Comment by kthyng** [comment]
I think there are a few more bib-related errors actually; you can get more details for how to format your references [here](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography). 

For example, the top two lines of reference Filhol2015 should be as below to get the order of the initial correct in the references list.

@article{Filhol2015,
  author  = "Filhol, S. and Sturm, M.",


Honestly I'm having trouble keeping track, but generally you'll want to exactly follow the examples on that site so that your references show up exactly right. In the references list, the first author should be shown as "Last name, First initial/name", but any subsequent authors should be listed as "First inital/name Last Name".

**Comment by kthyng** [comment]
This reference (https://iopscience.iop.org/article/10.1088/1367-2630/14/9/093037) has two more authors that have not been listed.

**Comment by kthyng** [comment]
These two references have the same doi:

Narteau, C., Zhang, D., Rozier, O., & Claudin, P. (2009). Setting the length and time scales of a cellular automaton dune model from the analysis of superimposed bed forms. Journal of Geophysical Research: Earth Surface, 114(f3). doi:10.1002/esp.3479


Rozier, O., & Narteau, C. (2014). A real‐space cellular automaton laboratory. Earth Surface Processes and Landforms, 39(1), 98–109. doi:10.1002/esp.3479

**Comment by kellykochanski** [comment]
@kthyng Thank you for the careful review and comments.

**Comment by kellykochanski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1699 with the following error: 

 Error reading bibliography ./paper.bib (line 63, column 3):
unexpected "d"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by kellykochanski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01699/joss.01699/10.21105.joss.01699.pdf)

**Comment by kellykochanski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01699/joss.01699/10.21105.joss.01699.pdf)

**Comment by kellykochanski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1699 with the following error: 

 Error reading bibliography ./paper.bib (line 96, column 1):
unexpected "@"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by kellykochanski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01699/joss.01699/10.21105.joss.01699.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/esp.3479 is OK
- 10.1029/2008JF001127 is OK
- 10.3189/172756507782202865 is OK
- 10.1029/JC088iC09p05475 is OK
- 10.1016/S0165-232X(02)00072-1 is OK
- 10.1002/2015JF003529 is OK
- 10.1007/s10546-012-9764-z is OK
- 10.5194/tc-13-1267-2019 is OK
- 10.1088/1367-2630/14/9/093037 is OK
- 10.1016/j.cageo.2018.06.009 is OK
- 10.1029/2018GL077616 is OK
- 10.1016/S0165-232X(02)00073-3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kellykochanski** [comment]
@kthyng I've fixed the following:

- Figure 2 caption has its own line
- Missing semicolon added to bibliography
- Missing umlaut in "Lammel" name properly formatted
- Capitalizations in paper names {bracketed}
- DOIs checked

I have not been able to fix the expanded author list for Marsh et al., despite reformatting (from quotes "" to brackets {{}}) to match the example you sent. 

Currently, lists of 1-4 authors are shown in full, and the papers with 5+ authors are abbreviated to Firstauthor et al.

**Comment by kthyng** [comment]
Nice, thanks @kellykochanski. We can proceed.

**Comment by kthyng** [comment]
@whedon set <v1.1> as version

**Comment by whedon** [comment]
OK. <v1.1> is the version.

**Comment by kthyng** [comment]
@kellykochanski  Please create an archive (on Zenodo, figshare, or other) and post the archive DOI here. Make sure that the title and author list in Zenodo match what you have on your paper here exactly.

**Comment by kellykochanski** [comment]
@kthyng I've created a software arxiv on zenodo with doi 10.5281/zenodo.3517217 

dx.doi.org/10.5281/zenodo.3517217

**Comment by kthyng** [comment]
I need to update the version number and syntax.

**Comment by kthyng** [comment]
@whedon set v1.1.1 as version

**Comment by whedon** [comment]
OK. v1.1.1 is the version.

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.3517217 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3517217" target="_blank">10.5281/zenodo.3517217</a> is the archive.

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/esp.3479 is OK
- 10.1029/2008JF001127 is OK
- 10.3189/172756507782202865 is OK
- 10.1029/JC088iC09p05475 is OK
- 10.1016/S0165-232X(02)00072-1 is OK
- 10.1002/2015JF003529 is OK
- 10.1007/s10546-012-9764-z is OK
- 10.5194/tc-13-1267-2019 is OK
- 10.1088/1367-2630/14/9/093037 is OK
- 10.1016/j.cageo.2018.06.009 is OK
- 10.1029/2018GL077616 is OK
- 10.1016/S0165-232X(02)00073-3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1047

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1047, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1187430629576720384) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1048
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01699](https://doi.org/10.21105/joss.01699)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Woohoo congratulations on your submission @kellykochanski!! 🎉 

Huge thanks to @zbeekman and @rgmyr for your excellent reviews.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01699/status.svg)](https://doi.org/10.21105/joss.01699)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01699">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01699/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01699/status.svg
   :target: https://doi.org/10.21105/joss.01699
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01699/status.svg)](https://doi.org/10.21105/joss.01699)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
