### ISSUE TITLE
[REVIEW]: KraljicMatrix: An R package for implementing the Kraljic Matrix to strategically analyze a firm’s purchasing portfolio

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#170]
**Submitting author:** @bradleyboehmke (<a href="http://orcid.org/0000-0002-3611-8516">Bradley Boehmke</a>)
**Repository:** <a href="https://github.com/bradleyboehmke/KraljicMatrix" target ="_blank">https://github.com/bradleyboehmke/KraljicMatrix</a>
**Version:** v0.1.0
**Editor:** @arfon
**Reviewer:** @cmsaie
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.268587" target="_blank">10.5281/zenodo.268587</a>

## Status

[![status](http://joss.theoj.org/papers/eae6c93511e508027ae7f26ef7eff977/status.svg)](http://joss.theoj.org/papers/eae6c93511e508027ae7f26ef7eff977)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/eae6c93511e508027ae7f26ef7eff977"><img src="http://joss.theoj.org/papers/eae6c93511e508027ae7f26ef7eff977/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/eae6c93511e508027ae7f26ef7eff977/status.svg)](http://joss.theoj.org/papers/eae6c93511e508027ae7f26ef7eff977)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bradleyboehmke/KraljicMatrix" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bradleyboehmke/KraljicMatrix">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@bradleyboehmke) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @cmsaie it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by cmsaie** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
@cmsaie - looking at the checklist it looks like you've completed your review? Were there any issues that came up when reviewing this package and do you have any written feedback for @bradleyboehmke?

**Comment by cmsaie** [comment]
@arfon I only have one suggestion for @bradleyboehmke.  I think when you call SAVF_score it should automatically compute the optimal rho and use it, maintain the function to call it on its own as well.

**Comment by arfon** [comment]
OK many thanks @cmsaie.

@bradleyboehmke - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by bradleyboehmke** [comment]
No problem @arfon 

[![DOI](https://zenodo.org/badge/74397607.svg)](https://zenodo.org/badge/latestdoi/74397607)

Also, @cmsaie , I like your suggestion.  I'm going to change the default in the SAVF_score function so that the optimal rho value is automatically computed and used.  I'll also allow the user to override and supply a non-optimal rho value if, for some reason, they want to.  I think this will be a good improvement to the code; it helps to streamline its functionality for the user.  Great suggestion, thanks!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.268587 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.268587" target="_blank">10.5281/zenodo.268587</a> is the archive.

**Comment by arfon** [comment]
@cmsaie - many thanks for your review here ✨ 

@bradleyboehmke - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00170 ⚡️ 🚀 💥

**Comment by bradleyboehmke** [comment]
Fantastic!  Thanks @arfon!
