### ISSUE TITLE
[PRE REVIEW]: PYCV: a PLUMED 2 Module Enabling the Rapid Prototyping of Collective Variables in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1702]
**Submitting author:** @tonigi (<a href="http://orcid.org/0000-0001-6449-0596">Toni Giorgino</a>)
**Repository:** <a href="https://github.com/giorginolab/plumed2-pycv/" target ="_blank">https://github.com/giorginolab/plumed2-pycv/</a>
**Version:** v1.1
**Editor:** @arfon
**Reviewers:** @amritagos, @carlocamilloni

**Author instructions**

Thanks for submitting your paper to JOSS @tonigi. **Currently, there isn't an JOSS editor assigned** to your paper.

@tonigi if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1702 with the following error: 

 Can't find any papers to compile :-(

**Comment by tonigi** [comment]
@whedon generate pdf from branch joss-paper

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1702 with the following error: 

 fatal: Unable to create '/app/tmp/1702/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
Can't find any papers to compile :-(

**Comment by arfon** [comment]
😸you beat me to it @tonigi

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01702/joss.01702/10.21105.joss.01702.pdf)

**Comment by tonigi** [comment]
faster than whedon itself :)

**Comment by arfon** [comment]
@tonigi - thanks for this submission to JOSS. Could you please identify a few potential reviewers for this submission. In particular, if at all possible I'd like to have one of the PLUMED 2 core team involved in this review.

**Comment by tonigi** [comment]
Sure. Sending them by email to avoid mention spam.

**Comment by amritagos** [comment]
Hi, I have worked with PLUMED before and would like to put myself forward for this. I just signed up as a volunteer, hope this isn't impolite!

**Comment by arfon** [comment]
Thanks @amritagos! I'll go ahead and add you as a reviewer but I won't start the review until we have another reviewer or two for this submission.

**Comment by arfon** [comment]
@whedon add @amritagos as reviewer

**Comment by arfon** [comment]
@whedon add @arfon as editor

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by tonigi** [comment]
Perhaps @carlocamilloni could be so kind to give it an eye?

**Comment by carlocamilloni** [comment]
Yes this is a good time to me

**Comment by tonigi** [comment]
To summarize:
* Fork of Plumed 2.5 with the `pycv` module: https://github.com/giorginolab/plumed2-pycv/
* Web page: https://giorginolab.github.io/plumed2-pycv/
* Paper (auto-generated by the editorial bot) https://github.com/openjournals/joss-papers/blob/joss.01702/joss.01702/10.21105.joss.01702.pdf
* Info on the review process: https://joss.readthedocs.io/en/latest/review_criteria.html  (will take place in a future issue, as far as I know)

Thanks!

**Comment by arfon** [comment]
@whedon add @carlocamilloni as reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1773. Feel free to close this issue now!

**Comment by arfon** [comment]
@amritagos, @carlocamilloni, @tonigi - see you over in #1773 for the actual review.
