### ISSUE TITLE
[PRE REVIEW]: Underworld2: Python Geodynamics Modelling for Desktop, HPC and Cloud

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1703]
**Submitting author:** @jmansour (<a href="http://orcid.org/0000-0001-5865-1664">john mansour</a>)
**Repository:** <a href="https://github.com/underworldcode/underworld2" target ="_blank">https://github.com/underworldcode/underworld2</a>
**Version:** v2.8.1b
**Editor:** @leouieda
**Reviewers:** @gassmoeller, @gabersyd

**Author instructions**

Thanks for submitting your paper to JOSS @jmansour. **Currently, there isn't an JOSS editor assigned** to your paper.

@jmansour if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1703 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
:wave: @jmansour - Whedon doesn't seem to be able to find a paper in your repository. Please review our [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html) on how to prepare a paper.

**Comment by jmansour** [comment]
Hi @arfon.  The `paper.md` document isn't stored within the project repository, but is instead here:

https://github.com/underworldcode/joss/

It is unclear (unless I missed something) from the guidelines whether it was sufficient to have the document within a separate repo. I'd rather it remains in a separate repo, but it isn't a huge issue if you'd like it to be stored within the project repo.  If that is the case, will @whedon scan all branches? Or do you use the `version` to designate the branch?  

Thanks

**Comment by arfon** [comment]
Hi @jmansour, sorry this wasn't clear. If at all possible, we prefer the paper to be in the same repository as the submission software. Whedon can compile papers from branches other than the default one (usually `master`) so if you're able to place the paper in the https://github.com/underworldcode/underworld2 repo, that would be great.

BTW, I've slightly [tweaked our submission guidelines](https://github.com/openjournals/joss/commit/9e881a7606db2e1f3c84114ffafc2cfcbd670e5b) to hopefully make this more clear.

**Comment by jmansour** [comment]
Ok, thanks @arfon, I'll move it into the project repo. 

With regards to process, is it reasonable to create a branch to capture changes relating to the review, with a new project release created at the conclusion which can then be tied to the JOSS publication?

**Comment by arfon** [comment]
> With regards to process, is it reasonable to create a branch to capture changes relating to the review, with a new project release created at the conclusion which can then be tied to the JOSS publication?

Yes, that would be great.

**Comment by jmansour** [comment]
Ok, excellent. I'll add the document shortly.  

Possible reviewers include Gabriele Morra (@gabersyd) and Sergio Zlotnik (@techas), although I believe Sergio has some experience using Underworld2 already. From the JOSS list of reviewers, I think any of the following might be appropriate: lheagy, whimian, daniellivingston, vidalgp, leouieda.

**Comment by arfon** [comment]
:wave: @leouieda - would you be willing to edit this submission for JOSS?

**Comment by leouieda** [comment]
Hi @arfon, I'd be happy to edit this!

**Comment by leouieda** [comment]
@whedon assign @leouieda as editor

**Comment by whedon** [comment]
OK, the editor is @leouieda

**Comment by leouieda** [comment]
@jmansour thank you for the reviewer recommendations! They really help. I'll try to get someone with geodynamics experience and someone with Python/C FEM experience to balance things out.

**Comment by leouieda** [comment]
:wave: Hi @florian-wagner @gabersyd would you like to review this submission for JOSS? Please see  [our documentation](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) for more information on what a JOSS review is like.

**Comment by florian-wagner** [comment]
Hi @leouieda, thanks for consideration. Although I have been looking forward to a chance to contribute to JOSS, I am currently on job transition / moving and not available for reviews. Sorry.

**Comment by jmansour** [comment]
Thanks @arfon & @leouieda  & also @florian-wagner 

I'll create the new branch with the required submission paper today.

**Comment by gabersyd** [comment]
Hi, I have never interacted with JOSS so I am certainly curious and willing
to do my best to review it. I am very busy until Sep 19, but immediately
after that I can look at it and provide my feedback.

Gabriele

Gabriele Morra
<http://scholar.google.com/citations?sortby=pubdate&hl=en&user=DDuTppAAAAAJ&view_op=list_works>
, Department of Physics <http://physics.louisiana.edu>, School of
Geosciences <http://geos.louisiana.edu>, University of Louisiana at
Lafayette <http://www.louisiana.edu>

**Comment by jmansour** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1703 with the following error: 

 Can't find any papers to compile :-(

**Comment by jmansour** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by jmansour** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1703 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:143:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:143:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:141:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:141:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:88:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by jmansour** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01703/joss.01703/10.21105.joss.01703.pdf)

**Comment by leouieda** [comment]
@jmansour I'm still trying to find a second reviewer for this. Sorry for the delay. I will be out of office until Sep 29 but will try to get this started as soon as possible.

**Comment by jmansour** [comment]
That's fine @leouieda. Thanks.

**Comment by leouieda** [comment]
:wave: Hi @krischer would you be interested in reviewing this submission for JOSS? Here is a [link to the submitted paper](https://github.com/openjournals/joss-papers/blob/joss.01703/joss.01703/10.21105.joss.01703.pdf) and the [software repository](https://github.com/underworldcode/underworld2).

**Comment by krischer** [comment]
Hi @leouieda,

thanks for the consideration and while I could review the Python part I'm not familiar with geodynamic simulations at all so I don't feel qualified for this particular review.

I think @gassmoeller for example would be much more qualified here.

**Comment by leouieda** [comment]
@krischer thanks for the quick response!

**Comment by leouieda** [comment]
@gassmoeller would you like to review this submission for JOSS?

**Comment by gassmoeller** [comment]
Hi @leouieda,
I am happy to review this submission.

**Comment by jmansour** [comment]
Thanks @gassmoeller, and also @krischer.

**Comment by leouieda** [comment]
Thank you @gassmoeller 👍 much appreciated

**Comment by whedon** [comment]
OK, @gassmoeller is now a reviewer

**Comment by leouieda** [comment]
@whedon add @gabersyd as reviewer

**Comment by whedon** [comment]
OK, @gabersyd is now a reviewer

**Comment by leouieda** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1797. Feel free to close this issue now!
