### ISSUE TITLE
[REVIEW]: AXITOM: A Python package for reconstruction of axisymmetric tomograms acquired by a conical beam

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1704]
**Submitting author:** @PolymerGuy (<a href="http://orcid.org/0000-0002-9981-4041">Sindre Nordmark Olufsen</a>)
**Repository:** <a href="https://github.com/PolymerGuy/AXITOM" target ="_blank">https://github.com/PolymerGuy/AXITOM</a>
**Version:** V0.1.3
**Editor:** @katyhuff
**Reviewer:** @PingjunChen, @dgursoy
**Archive:** <a href="https://doi.org/10.5281/zenodo.3466426" target="_blank">10.5281/zenodo.3466426</a>

## Status

[![status](https://joss.theoj.org/papers/45e4cdd5f172a6e995434b3877aa09d6/status.svg)](https://joss.theoj.org/papers/45e4cdd5f172a6e995434b3877aa09d6)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/45e4cdd5f172a6e995434b3877aa09d6"><img src="https://joss.theoj.org/papers/45e4cdd5f172a6e995434b3877aa09d6/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/45e4cdd5f172a6e995434b3877aa09d6/status.svg)](https://joss.theoj.org/papers/45e4cdd5f172a6e995434b3877aa09d6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/PolymerGuy/AXITOM" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@PingjunChen & @dgursoy, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @katyhuff know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/PolymerGuy/AXITOM">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@PolymerGuy) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/PolymerGuy/AXITOM">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@PolymerGuy) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @PingjunChen, @dgursoy it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01704/joss.01704/10.21105.joss.01704.pdf)

**Comment by katyhuff** [comment]
@PingjunChen and @dgursoy : thank you for your engagement in this review process! Please see the checklists in the description of this issue, above, for guidance with your review. 

@PolymerGuy, I am hoping that Pingjun Chen will be able to start their review promptly, so you should soon have some comments from that review. I have requested the expert assistance of @dgursoy, as well. That review will begin when @dgursoy becomes available in mid-September. Thank you for your patience with these reviews, @PolymerGuy.

**Comment by katyhuff** [comment]
@whedon remind @dgursoy on September 15.

**Comment by katyhuff** [comment]
@whedon remind @dgursoy in 2 weeks

**Comment by whedon** [comment]
Reminder set for @dgursoy in 2 weeks

**Comment by PingjunChen** [comment]
@PolymerGuy Good documentation and tests in this repo. There are several minor issues I believe need to be corrected.
1. There is a RuntimeWarning when running tests, "utilities.py:34: RuntimeWarning: invalid value encountered in true_divide center_of_grav_x = np.average(np.sum(xs * covered_pixels, axis=1) / np.sum(covered_pixels, axis=1)) - m / 2." Better to get rid of it.
2. There are two copies of `example_data` in the repo, which is not the optimum solution.  Better to reconstruct `tests` and `examples` to use the same `example_data`.
3. In `README/Clone the repo` part, the usage of `You can now run an example:` can have path issue if not running the example under working directory `<path_to_axitom>/examples`. `os.path.abspath` and `os.path.dirname` can be used to solve this problem as well as the above two copies of data.  
4. The font size of `Reference` in the PDF file is not consistent with `Summary`. Leave a blank line before `Reference` in `paper.md`.

**Comment by PolymerGuy** [comment]
@PingjunChen Thank you for the feedback! 
The division warning is now gone and the routine itself is now a bit more robust.
The examples will now run when executed from the main folder. 

I have merged all changes into the  main branch

**Comment by PolymerGuy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01704/joss.01704/10.21105.joss.01704.pdf)

**Comment by PingjunChen** [comment]
@PolymerGuy Good improvements!
@katyhuff  This python package has useful axis-symmetric tomograms reconstruction functionality, as well as detailed documentation, tests, and examples.  I recommend accepting for publication.

**Comment by whedon** [comment]
:wave: @dgursoy, please update us on how your review is going.

**Comment by dgursoy** [comment]
Hi @whedon. I haven't started yet and plan to work it on next week.

**Comment by katyhuff** [comment]
Thank you @dgursoy !

**Comment by dgursoy** [comment]
@PolymerGuy great package! Thanks for working on this. I have few (most are optional) minor points:

- I had the same Runtime error that is mentioned above when installing from PyPI and running tests. I think this is because the changes are in the brach and the PyPI version hasn't been updated.
-  I had a hard time in finding the example config and data files. Also their names are different in docs and in the folder structure. It'd be nice to provide a better description of their location and names. 
- In the docs, you massage the data before processing (cropping and filtering). I think it would be better if you save the cropped and filtered image saved as an example file. This should increase the clarity of your documentation. 
- There is a typo in docs: "centre of rotation" should be "center of rotation".
- Config or setting object needs some documentation for others to appropriately set their parameters. These could be in the Class definition in ```config.py```. Few important ones are the units and coordinate definitions.
- I would add a short description of the module on top to guide future developers. 
- Maybe ```parse``` module can be merged into the ```utility``` module.
- Please check each of the function docstrings. There are some copy+paste typos, especially in axes definitions. Some are also missing the docs (e.g. ```fdk_axisym```). 
- You use ```projections`` and ```radiographs``` interchangeably. I believe both refers to the same thing, so I'd stick with one for clarity across the package.
- I'd use ```object``` or ```volume``` instead of ```data``` in ```forward_project```. Also in the same function use ```ratios``` instead of ```Ratios```?
- I'd automatically convert the input arrays to numpy arrays and give a warning if needed: ```backprojection.py", line 127, in fdk```. because this is in principle not an error, right?
- Some information about the test data can be provided. What is this image?

**Comment by PolymerGuy** [comment]
@dgursoy Thank you for the feedback! I will implement all the improvements suggested above and i will update the PyPi package as soon as possible. I hope to have all changes done within the next couple of days.

**Comment by PolymerGuy** [comment]
@dgursoy once again, thank you for the recommended changes. I have now implemented all of them and have in addition done a slight change to the Config class.

I also found a bug which made trouble when the projections did not have square dimensions.

The Config class now contains a smaller set of settings and also has a .with_param() method which returns a copy of the object with the new settings. If I could, I would make the config objects immutable, but as some of the internal parameters are calculated when the object is instantiated, I was not able to do this in a clean way.

The package is now updated on PyPi

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01704/joss.01704/10.21105.joss.01704.pdf)

**Comment by katyhuff** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1107/S1600577514013939 is OK
- 10.1107/S1600577516005658 is OK
- 10.1364/OE.24.025129 is OK
- 10.5281/ZENODO.47423 is OK
- 10.1364/JOSAA.1.000612 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.ultramic.2015.05.002 is INVALID because of 'https://doi.org/' prefix
```

**Comment by katyhuff** [comment]
@PolymerGuy One DOI (10.1016/j.ultramic.2015.05.002) will need to be fixed in your bibliography. Please remove the 'https://doi.org/' prefix from the DOI itself.

**Comment by PolymerGuy** [comment]
@katyhuff I have now removed the prefix from the DOI and pushed the changes to master.

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01704/joss.01704/10.21105.joss.01704.pdf)

**Comment by katyhuff** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1107/S1600577514013939 is OK
- 10.1107/S1600577516005658 is OK
- 10.1364/OE.24.025129 is OK
- 10.1016/j.ultramic.2015.05.002 is OK
- 10.5281/ZENODO.47423 is OK
- 10.1364/JOSAA.1.000612 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by katyhuff** [comment]
Thank you @PingjunChen and @dgursoy for your reviews -- we couldn't do this without you. Your comments seem to have been particularly valuable to the software package itself. That's wonderful, as it's very much the purpose of JOSS.

Thank you @PolymerGuy for a strong submission and for engaging actively in the review process! I have looked over the paper, double-checked all the DOI links, and have conducted a high-level review of the code itself. Everything now looks ship-shape to me. At this point, please double-check the paper yourself, review any lingering details in your code/readme/etc., and then make an archive of the reviewed software in Zenodo/figshare/other service. **Please be sure that the DOI metadata (title, authors, etc..) matches this JOSS submission.** Once that's complete, please update this thread with the DOI of the archive, and I'll move forward with accepting the submission. Until then, now is your moment for final touchups! If you bump up the version, please let me know the correct version to associate with this submission.

**Comment by PolymerGuy** [comment]
@katyhuff @PingjunChen @dgursoy Thank you all for your kind supervision and helpful advice on my first software submission! I have now archived the repo at Zenodo and got the following DOI: 
10.5281/zenodo.3466426

I kept the version as it was during the review.

**Comment by katyhuff** [comment]
@whedon set 10.5281/zenodo.3466426 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3466426" target="_blank">10.5281/zenodo.3466426</a> is the archive.

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01704/joss.01704/10.21105.joss.01704.pdf)

**Comment by katyhuff** [comment]
@openjournals/jose-eics  Hi there, I believe this one is ready for acceptance!

**Comment by labarba** [comment]
https://github.com/PolymerGuy/AXITOM/releases
... shows the version as V0.1.3, but here I see V0.1.2 — I will update the version here, but please let us know if that was not what you intended.

**Comment by labarba** [comment]
@whedon set V0.1.3 as version

**Comment by whedon** [comment]
OK. V0.1.3 is the version.

**Comment by labarba** [comment]
I suggested some copy edits via PR. The text was a bit cluttered and hard to read in places, so I attempted to remove some unnecessary words.

**Comment by PolymerGuy** [comment]
@labarba Thank you very much for the PR, and I really appreciate the proposed changes. I have now merged the PR.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1107/S1600577514013939 is OK
- 10.1107/S1600577516005658 is OK
- 10.1364/OE.24.025129 is OK
- 10.1016/j.ultramic.2015.05.002 is OK
- 10.5281/ZENODO.47423 is OK
- 10.1364/JOSAA.1.000612 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1017

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1017, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1181997723932864512) 👈 🐦🐦🐦

**Comment by labarba** [comment]
Congratulations, @PolymerGuy, your JOSS paper is now published! 🚀 

Huge thanks to our eeditor: @katyhuff, and the reviewers: @PingjunChen, @dgursoy — you're a part of our big adventure!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01704/status.svg)](https://doi.org/10.21105/joss.01704)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01704">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01704/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01704/status.svg
   :target: https://doi.org/10.21105/joss.01704
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01704/status.svg)](https://doi.org/10.21105/joss.01704)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
