### ISSUE TITLE
[REVIEW]: BotSlayer: real-time detection of bot amplification on Twitter

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1706]
**Submitting author:** @yangkcatiu (<a href="http://orcid.org/0000-0003-4627-9273">Kai-Cheng Yang</a>)
**Repository:** <a href="https://github.com/IUNetSci/BotSlayer-CE" target ="_blank">https://github.com/IUNetSci/BotSlayer-CE</a>
**Version:** v1.0
**Editor:** @arokem
**Reviewer:** @mkearney, @nkratzke
**Archive:** <a href="https://doi.org/10.5281/zenodo.3492278" target="_blank">10.5281/zenodo.3492278</a>

## Status

[![status](https://joss.theoj.org/papers/a741ef544d0e1161223581c1d0eb313c/status.svg)](https://joss.theoj.org/papers/a741ef544d0e1161223581c1d0eb313c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a741ef544d0e1161223581c1d0eb313c"><img src="https://joss.theoj.org/papers/a741ef544d0e1161223581c1d0eb313c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a741ef544d0e1161223581c1d0eb313c/status.svg)](https://joss.theoj.org/papers/a741ef544d0e1161223581c1d0eb313c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/IUNetSci/BotSlayer-CE" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mkearney & @nkratzke, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/IUNetSci/BotSlayer-CE">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@yangkcatiu) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/IUNetSci/BotSlayer-CE">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@yangkcatiu) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mkearney, @nkratzke it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01706/joss.01706/10.21105.joss.01706.pdf)

**Comment by nkratzke** [comment]
@arokem I have done my review. Generally speaking, the software was easy to install using Docker and worked the first time without hassle. It was easy to run an initial example case using the searchterm "Trump".

However, according to the JOSS checklist, there are open points from my point of view. These points are mainly documentation and automated testing points. I have addressed these points in separate tickets 

- https://github.com/IUNetSci/BotSlayer-CE/issues/13
- https://github.com/IUNetSci/BotSlayer-CE/issues/14
- https://github.com/IUNetSci/BotSlayer-CE/issues/15
- https://github.com/IUNetSci/BotSlayer-CE/issues/16
- https://github.com/IUNetSci/BotSlayer-CE/issues/17
- https://github.com/IUNetSci/BotSlayer-CE/issues/18

in the respective [repository](https://github.com/IUNetSci/BotSlayer-CE). The tickets cover mainly documentation points of the repository.

- Example usage
- Functionality documentation (missing API documentation)
- Automated tests (no automated tests found)
- Community guidelines (no guidelines found)

However, the JOSS paper is fine from my point of view.

**Comment by mkearney** [comment]
I've completed my review, @arokem. Following @nkratzke's lead, I also posted the following as a general remarks issue and created individual Github issues for bullet points #2-4.


Overall, I think the tool is absolutely fantastic! It's relatively easy to setup, but, more importantly, once it's up and running it's a breeze to use–e.g., in a maner of seconds, tracking the high frequency mentions of `@realDonaldTrump` generated 15+ pages of results that smoothly exported as a tidy CSV file.

With that said, I agree with the issues raised by @nkratzke and would like to add the following issues based on my review of BotSlayer:

* [x] Edit wording about tweepy functionality in README (update: [this has already been addressed](nkratzke))
* [ ] Given the real-time and interactive nature of *BotSlayer* and its relationship to public-opinion/affairs, **I think the intended audience (currently phrased as *'researchers'* or *'academic researchers'* in `paper.md` and `README.md`) should also include *'journalists'*–who not only have an interest in this topic but also have an [entire organization dedicated to computer-assisted reporting](https://www.ire.org/nicar)**.
* [ ] The tool exports `screen_name` as the user/account identifier, but screen names can be changed and are thus not stable identifiers. **The exported output should therefore include the user `id_str` value returned by Twitter's stream API**.
* [ ] The tool does not currently output a useful identifier of statuses. The exported output includes bot scores, screen names, status texts, timestamps, etc., but Twitter's stream and REST APIs [forcefully] return a lot more data than that. I don't think BotSlayer should include/return all of this information for the user, but it should at least return the sufficient information for researchers to lookup the rest via requests to the *lookup/statuses* endpoint of Twitter's REST API. **The exported output should therefore return the status `id_str` value**.

**Comment by arokem** [comment]
Thank you both for these reviews! 

@yangkcatiu : please address the comments made by the reviewers and let us know here when you are ready for the next round of review. Thanks!

**Comment by yangkcatiu** [comment]
Thank you all for the feedback, all the suggestions are very helpful! We are woking on addressing them.

**Comment by yangkcatiu** [comment]
👋@arokem @mkearney hi, we believe we have addressed the issue raised in last round of review, but haven't got any feedback for a while. We are wondering what's holding the reviewing process. Please let us know what we can do!

**Comment by arokem** [comment]
@mkearney, @nkratzke : could you please take a look when you get a chance? Were your previous comments addressed through these revisions?

**Comment by nkratzke** [comment]
@arokem My points have been addressed.

**Comment by nkratzke** [comment]
I am fine with the revisions.

**Comment by arokem** [comment]
@nkratzke : could you please check the boxes at the top of this issue?

**Comment by nkratzke** [comment]
@arokem OK, I did.

**Comment by arokem** [comment]
@mkearney : I see that there are still some check-boxes that you did not check. Do the authors need to address any of these before you can check these off? Or were these issues addressed in the previous round of reviews?

**Comment by yangkcatiu** [comment]
Hi @arokem , we haven't heard any feedback for a while now, we are wondering what would be the next steps. Thank you!

**Comment by arokem** [comment]
@mkearney : have you had a chance to take a look and see whether you are able to check off the remaining items?

**Comment by yangkcatiu** [comment]
Hi @arokem , we haven't heard anything feedback from the reviewer for almost a month now. We have addressed issues already, would it be possible for you to take a look and approve the changes? Thank you!

**Comment by arokem** [comment]
I apologize for how long this has languished. I've contacted @mkearney by email and he told me that he has some time set aside for this tonight, so I hope we can put this thing to rest tomorrow...

**Comment by yangkcatiu** [comment]
Really appreciate it!

**Comment by mkearney** [comment]
Sorry for the delay–you all were so fast with the revisions! The revisions look great!

**Comment by arokem** [comment]
OK - I see that you have checked all the boxes. I take it to assume that both reviewers are ready to recommend acceptance at this point. Thank you both for your reviews!

**Comment by arokem** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by yangkcatiu** [comment]
Thank you! @mkearney @arokem

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/3308560.3316486 is OK
- 10.1140/epjds/s13688-017-0111-y is OK
- 10.7717/peerj-cs.87 is OK

MISSING DOIs

- https://doi.org/10.1002/hbe2.115 may be missing for title: Arming the public with artificial intelligence to counter social bots
- https://doi.org/10.1145/3308560.3316495 may be missing for title: Disinformation warfare: Understanding state-sponsored trolls on Twitter and their influence on the Web
- https://doi.org/10.5210/fm.v22i8.8005 may be missing for title: Disinformation and Social Bot Operations in the Run Up to the 2017 French Presidential Election
- https://doi.org/10.1007/s13278-019-0578-6 may be missing for title: Characterizing the 2016 Russian IRA Influence Campaign
- https://doi.org/10.1073/pnas.1803470115 may be missing for title: Bots increase exposure to negative and inflammatory content in online social systems
- https://doi.org/10.1038/s41467-018-06930-7 may be missing for title: The spread of low-credibility content by social bots
- https://doi.org/10.2139/ssrn.2635800 may be missing for title: Political bots and the manipulation of public opinion in Venezuela

INVALID DOIs

- None
```

**Comment by arokem** [comment]
@yangkcatiu : see ☝️above for missing DOIs in references. Could you please add these for these references? I will also take another read through the PDF to make sure the everything is in the right place.

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01706/joss.01706/10.21105.joss.01706.pdf)

**Comment by yangkcatiu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by arokem** [comment]
I noticed that there is some inconsistent reference formatting. For example, sometimes "Clayton Allen Davis et al., 2016", sometimes "C A Davis et al. 2016" , and sometimes  "Davis et al. 2016". Could you please make sure that reference formats are consistent?

**Comment by yangkcatiu** [comment]
I have added the missing references; I also updated the references for two recently updated papers.

**Comment by yangkcatiu** [comment]
Sure!

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/3308560.3316486 is OK
- 10.1140/epjds/s13688-017-0111-y is OK
- 10.7717/peerj-cs.87 is OK

MISSING DOIs

- https://doi.org/10.1002/hbe2.115 may be missing for title: Arming the public with artificial intelligence to counter social bots
- https://doi.org/10.1145/3308560.3316495 may be missing for title: Disinformation warfare: Understanding state-sponsored trolls on Twitter and their influence on the Web
- https://doi.org/10.5210/fm.v22i8.8005 may be missing for title: Disinformation and Social Bot Operations in the Run Up to the 2017 French Presidential Election
- https://doi.org/10.1007/s13278-019-0578-6 may be missing for title: Characterizing the 2016 Russian IRA Influence Campaign
- https://doi.org/10.1073/pnas.1803470115 may be missing for title: Bots increase exposure to negative and inflammatory content in online social systems
- https://doi.org/10.1038/s41467-018-06930-7 may be missing for title: The spread of low-credibility content by social bots
- https://doi.org/10.2139/ssrn.2635800 may be missing for title: Political bots and the manipulation of public opinion in Venezuela

INVALID DOIs

- None
```

**Comment by yangkcatiu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by yangkcatiu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01706/joss.01706/10.21105.joss.01706.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/hbe2.115 is OK
- 10.1145/3308560.3316495 is OK
- 10.5210/fm.v22i8.8005 is OK
- 10.1007/s13278-019-0578-6 is OK
- 10.1145/3292522.3326016 is OK
- 10.1073/pnas.1803470115 is OK
- 10.1145/3308560.3316486 is OK
- 10.1038/s41467-018-06930-7 is OK
- 10.1140/epjds/s13688-017-0111-y is OK
- 10.7717/peerj-cs.87 is OK
- 10.7717/peerj-cs.87 is OK
- 10.2139/ssrn.2635800 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by yangkcatiu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01706/joss.01706/10.21105.joss.01706.pdf)

**Comment by arokem** [comment]
Looks like you got all the DOIs. Did you see my formatting PR? https://github.com/IUNetSci/BotSlayer-CE/pull/37

**Comment by yangkcatiu** [comment]
Yes, just merged, thank you!

**Comment by yangkcatiu** [comment]
I have re-formated the references.

**Comment by arokem** [comment]
@whedon  generate pdf

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01706/joss.01706/10.21105.joss.01706.pdf)

**Comment by arokem** [comment]
I had one more suggested wording change in https://github.com/IUNetSci/BotSlayer-CE/pull/38. If that looks OK, feel free to merge that. 

At this point, could you also please make a new release of the main repo that includes all of the changes that have resulted from the review? Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive. For the archive version, please make sure that:

- The title of the archive is the same as the JOSS paper title
- The authors of the archive are the same as the JOSS paper authors

Once we've registered the archive DOI, I believe that the paper will be ready for final approval by the EIC.

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3492278" target="_blank">10.5281/zenodo.3492278</a> is the archive.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set v1.0 as version

**Comment by whedon** [comment]
OK. v1.0 is the version.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01706/joss.01706/10.21105.joss.01706.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/hbe2.115 is OK
- 10.1145/3308560.3316495 is OK
- 10.5210/fm.v22i8.8005 is OK
- 10.1007/s13278-019-0578-6 is OK
- 10.1145/3292522.3326016 is OK
- 10.1073/pnas.1803470115 is OK
- 10.1145/3308560.3316486 is OK
- 10.1038/s41467-018-06930-7 is OK
- 10.1140/epjds/s13688-017-0111-y is OK
- 10.7717/peerj-cs.87 is OK
- 10.2139/ssrn.2635800 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@yangkcatiu Below are some comments and suggestions on the paper: 

- [ ] Instead of `First` and `Second`, I suggest `Firstly` and `Secondly`.
- [ ] Is it possible to increase the font in the table view of figure 1?
- [ ] Add `s` to make calculations plural in "All statistical and machine learning
calculation[s]..." 
- [ ] Please define the acronym AUC

**Comment by yangkcatiu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01706/joss.01706/10.21105.joss.01706.pdf)

**Comment by yangkcatiu** [comment]
@Kevin-Mattheus-Moerman  thank you for your comments! I have made the changes accordingly:

- [x] `First` -> `Firstly`; `Second` -> `Secondly`
- [x] Increase the font size in the table view of figure 1
- [x] Add `s` to `calculations`
- [x] Define AUC

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1031

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1031, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/hbe2.115 is OK
- 10.1145/3308560.3316495 is OK
- 10.5210/fm.v22i8.8005 is OK
- 10.1007/s13278-019-0578-6 is OK
- 10.1145/3292522.3326016 is OK
- 10.1073/pnas.1803470115 is OK
- 10.1145/3308560.3316486 is OK
- 10.1038/s41467-018-06930-7 is OK
- 10.1140/epjds/s13688-017-0111-y is OK
- 10.7717/peerj-cs.87 is OK
- 10.2139/ssrn.2635800 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1185287914353238017) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1032
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01706](https://doi.org/10.21105/joss.01706)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01706/status.svg)](https://doi.org/10.21105/joss.01706)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01706">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01706/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01706/status.svg
   :target: https://doi.org/10.21105/joss.01706
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01706/status.svg)](https://doi.org/10.21105/joss.01706)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by yangkcatiu** [comment]
Thank you all! We really appreciate your work and comments.
