### ISSUE TITLE
[PRE REVIEW]: MAESTROeX: A Massively Parallel Low Mach Number Astrophysical Solver

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1707]
**Submitting author:** @doreenfan (<a href="http://orcid.org/0000-0002-3246-4315">Duoming Fan</a>)
**Repository:** <a href="https://github.com/AMReX-Astro/MAESTROeX" target ="_blank">https://github.com/AMReX-Astro/MAESTROeX</a>
**Version:** 19.09
**Editor:** @arfon
**Reviewers:** @tukss, @pgrete

**Author instructions**

Thanks for submitting your paper to JOSS @doreenfan. **Currently, there isn't an JOSS editor assigned** to your paper.

@doreenfan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1707 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1707/paper/paper.md): found unexpected document indicator while scanning a quoted scalar at line 2 column 8 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:115:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@doreenfan - many thanks for your submission to JOSS. Please merge this pull request which should fix your paper compilation issues: https://github.com/AMReX-Astro/MAESTROeX/pull/96

Also, does this paper accompany a submission to a AAS journal?

**Comment by doreenfan** [comment]
Yes, we have also submitted a paper to ApJ. It's currently under review and
uploaded on Arxiv at https://arxiv.org/abs/1908.03634.
Thanks!

**Comment by arfon** [comment]
/ cc @crawfordsm

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01707/joss.01707/10.21105.joss.01707.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@mbobra @xuanxu could one of you edit this submission? Can you also help suggest some reviewers (even if you are not able to edit)? Thanks

**Comment by xuanxu** [comment]
hey @Kevin-Mattheus-Moerman, I can't take this one. I'm a little overloaded these days and both hydrodynamics and C++ are out of my areas of expertise.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mbobra :point_up: can you help here?

**Comment by jedbrown** [comment]
This is in my domain, but I should note possible CoI with authors before offering to edit:
1. I co-authored the jupyter4edu book with Michael last year (along with several other JOSS editors)
2. I have been funded by projects that included Ann (e.g., DOE FASTMath). I'm no longer directly funded by such projects, but I still collaborate with many members (though not directly with Ann).

**Comment by kthyng** [comment]
Thanks @jedbrown.   @mbobra could you edit this instead?

**Comment by arfon** [comment]
@kthyng - I'm happy to take this one if that's helpful.

**Comment by kthyng** [comment]
If you are happy to, then who am I to stop you? :)

**Comment by kthyng** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@doreenfan - do you have any suggested reviewers for this submission? Either mentioning them by their GitHub handle or name (that I can search online for).

**Comment by doreenfan** [comment]
I believe @zingale has some suggestions

**Comment by zingale** [comment]
potential suggestions (some mined from the 'stars' on one of our python hydro projects):

Philipp Edelmann (@tukss)
James Guilochon (@guillochon)
Claire Kopenhafer (@clairekope)

**Comment by arfon** [comment]
:wave: @tukss @guillochon @clairekope - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by tukss** [comment]
I would gladly be a reviewer. That would be my first JOSS review.

**Comment by arfon** [comment]
> I would gladly be a reviewer. That would be my first JOSS review.

🎉 excellent thanks!

I'll go ahead and add you as a reviewer but I won't actually start the main review (with associated checklist etc.) until I've found a second reviewer. So for now, please sit tight!

**Comment by arfon** [comment]
@whedon add @tukss as reviewer

**Comment by whedon** [comment]
OK, @tukss is now a reviewer

**Comment by clairekope** [comment]
Hi, thank you for the opportunity! Unfortunately I'm not currently in a good position to take this on.

**Comment by zingale** [comment]
Another suggestion of someone who works on astro hydro codes with C++,

Philipp Grete: @pgrete

**Comment by arfon** [comment]
@pgrete - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by pgrete** [comment]
Yes, I'm happy to conduct the review.

**Comment by arfon** [comment]
@whedon add @pgrete as reviewer

**Comment by whedon** [comment]
OK, @pgrete is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1757. Feel free to close this issue now!

**Comment by arfon** [comment]
@tukss, @pgrete, @doreenfan - see you all over in #1757 for the actual review.
