### ISSUE TITLE
[REVIEW]: Adeft: Acromine-based Disambiguation of Entities from Text with applications to the biomedical literature

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1708]
**Submitting author:** @johnbachman (<a href="http://orcid.org/0000-0001-6095-2466">John Bachman</a>)
**Repository:** <a href="https://github.com/indralab/adeft" target ="_blank">https://github.com/indralab/adeft</a>
**Version:** 0.5.3
**Editor:** @brainstorm
**Reviewer:** @GullyAPCBurns, @gbader
**Archive:** <a href="https://doi.org/10.5281/zenodo.3610528" target="_blank">10.5281/zenodo.3610528</a>

## Status

[![status](https://joss.theoj.org/papers/a7edba4e988abfc85b01b034d373a729/status.svg)](https://joss.theoj.org/papers/a7edba4e988abfc85b01b034d373a729)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a7edba4e988abfc85b01b034d373a729"><img src="https://joss.theoj.org/papers/a7edba4e988abfc85b01b034d373a729/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a7edba4e988abfc85b01b034d373a729/status.svg)](https://joss.theoj.org/papers/a7edba4e988abfc85b01b034d373a729)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/indralab/adeft" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@GullyAPCBurns & @gbader, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @brainstorm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/indralab/adeft">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@johnbachman) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/indralab/adeft">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@johnbachman) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @GullyAPCBurns, @gbader it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01708/joss.01708/10.21105.joss.01708.pdf)

**Comment by brainstorm** [comment]
@GullyAPCburns @gbader, please go ahead and review away ;)

https://joss.readthedocs.io/en/latest/review_checklist.html

**Comment by brainstorm** [comment]
@GullyAPCBurns @gbader, if you have doubts about how to proceed, please ask!

**Comment by gbader** [comment]
Hello. I completed the review. The paper and software look good.  My graduate student @JohnGiorgi helped review the software. We were able to get it to work and it successfully disambiguated “ER” (endoplasmic reticulum) in some test text.

**Comment by brainstorm** [comment]
Great, thanks @gbader!

I've noticed that you left out "State of the field" in your review, @johnbachman, could you please address that in the manuscript?

@GullyAPCBurns, let us know if you have any difficulties with the review process, I'm here to assist!

**Comment by johnbachman** [comment]
@brainstorm Will do!

**Comment by johnbachman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01708/joss.01708/10.21105.joss.01708.pdf)

**Comment by johnbachman** [comment]
@brainstorm @gbader We added a new paragraph to the manuscript briefly describing where Adeft fits in the context of word sense disambiguation more generally.

**Comment by brainstorm** [comment]
Thanks @johnbachman!  @GullyAPCBurns, please let me know if you have any doubts about the review process?

**Comment by danielskatz** [comment]
👋 @GullyAPCBurns, @gbader - How are your reviews coming?

**Comment by gbader** [comment]
The new paragraph looks great.  In my view, this paper should be accepted.

Sorry for the delay. I like the idea of this journal, but one issue with running peer review on github is that the emails all come from github, which I happen to have filtered due to the large number of automated emails I get from github.

**Comment by brainstorm** [comment]
Thanks @gbader for your input, we are still waiting for @GullyAPCBurns... shall we regard him as missing reviewer at this point as he's not replying?

**Comment by labarba** [comment]
@brainstorm — this submission has been silent for a while. It looks like you have an MIA reviewer. I suppose you did try to reach them by other means? (email, Twitter) It may be time to take some executive decision here on finding a replacement reviewer.

**Comment by johnbachman** [comment]
I contacted @GullyAPCBurns by email on Dec 13th, he said he would be able to review.

**Comment by GullyBurns** [comment]
Sincere apologies for having been unresponsive. I will recommit to completing this review as quickly as possible in the next two weeks.

**Comment by GullyAPCBurns** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by GullyAPCBurns** [comment]
@danielskatz, I can't seem to check any of the boxes on the above form. Am I missing something very obvious?

**Comment by danielskatz** [comment]
Please see the first comment - did you accept the invite as mentioned in step 2 there?

**Comment by GullyAPCBurns** [comment]
Got it. Confirmed and yet more apologies for the delay.

**Comment by GullyAPCBurns** [comment]
I was able to review the paper and software. The code looks great and the documentation is exemplary. I ran the available Jupyter notebooks and was able to disambiguate 'Gut Cancer (GC)' effectively. 

Again, I apologize for not having done this immediately. I'd recommend that you proceed with publication 'as is'.

**Comment by brainstorm** [comment]
Great, thanks @GullyAPCBurns!

**Comment by brainstorm** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btl534 is OK
- 10.1093/bioinformatics/btq129 is OK
- 10.15252/msb.20177651 is OK
- 10.1145/1459352.1459355 is OK

MISSING DOIs

- https://doi.org/10.1089/cmb.2005.12.554 may be missing for title: Word sense disambiguation in the biomedical domain: an overview
- https://doi.org/10.1016/j.jbi.2013.09.009 may be missing for title: Determining the difficulty of Word Sense Disambiguation
- https://doi.org/10.3115/1572364.1572374 may be missing for title: Disambiguation of Biomedical Abbreviations
- https://doi.org/10.1016/j.jbi.2010.08.009 may be missing for title: Disambiguation in the biomedical domain: the role of ambiguity type
- https://doi.org/10.18653/v1/p19-1569 may be missing for title: Language Modelling Makes Sense: Propagating Representations through WordNet for Full-Coverage Word Sense Disambiguation
- https://doi.org/10.18653/v1/p18-1230 may be missing for title: Incorporating Glosses into Neural Word Sense Disambiguation
- https://doi.org/10.1197/jamia.m1533 may be missing for title: A multi-aspect comparison study of supervised word sense disambiguation

INVALID DOIs

- None
```

**Comment by brainstorm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01708/joss.01708/10.21105.joss.01708.pdf)

**Comment by brainstorm** [comment]
Looks good to my too, @johnbachman, next step is for you to deposit it on Zenodo and we'll archive it in JOSS, let me know if you run into any problems with that. Pretty close to publication now ;)

**Comment by johnbachman** [comment]
Great, will do, thanks to all!

**Comment by johnbachman** [comment]
Hi @brainstorm, the release for the paper is up at Zenodo here: https://zenodo.org/record/3608205

The version is 0.5.2, DOI is 10.5281/zenodo.3608205.

Also, a question--should we add in DOIs for the 7 listed as "missing"?

**Comment by johnbachman** [comment]
@brainstorm Correction--the relevant version is 0.5.3 (fixed a minor issue in the release). Zenodo DOI reflects the update.

**Comment by brainstorm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01708/joss.01708/10.21105.joss.01708.pdf)

**Comment by johnbachman** [comment]
@brainstorm Sorry, updated the comment above with correct DOI information

**Comment by brainstorm** [comment]
@whedon set https://zenodo.org/record/3608243 as archive

**Comment by whedon** [comment]
https://zenodo.org/record/3608243 doesn't look like an archive DOI.

**Comment by brainstorm** [comment]
@whedon set  10.5281/zenodo.3608243 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3608243" target="_blank">10.5281/zenodo.3608243</a> is the archive.

**Comment by brainstorm** [comment]
No worries John, gotcha. @danielskatz LGTM, can you find any irregularity pre-publishing it for good?

**Comment by danielskatz** [comment]
👋 @openjournals/joss-eics - I think this may be ready for you

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btl534 is OK
- 10.1093/bioinformatics/btq129 is OK
- 10.15252/msb.20177651 is OK
- 10.1145/1459352.1459355 is OK

MISSING DOIs

- https://doi.org/10.1089/cmb.2005.12.554 may be missing for title: Word sense disambiguation in the biomedical domain: an overview
- https://doi.org/10.1016/j.jbi.2013.09.009 may be missing for title: Determining the difficulty of Word Sense Disambiguation
- https://doi.org/10.3115/1572364.1572374 may be missing for title: Disambiguation of Biomedical Abbreviations
- https://doi.org/10.1016/j.jbi.2010.08.009 may be missing for title: Disambiguation in the biomedical domain: the role of ambiguity type
- https://doi.org/10.18653/v1/p19-1569 may be missing for title: Language Modelling Makes Sense: Propagating Representations through WordNet for Full-Coverage Word Sense Disambiguation
- https://doi.org/10.18653/v1/p18-1230 may be missing for title: Incorporating Glosses into Neural Word Sense Disambiguation
- https://doi.org/10.1197/jamia.m1533 may be missing for title: A multi-aspect comparison study of supervised word sense disambiguation

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @johnbachman, can you update the Zenodo archive title to match the paper? Also, it looks like some of your references may be missing DOIs 👆, if you could add those (you may want to check that the suggestions are correct first).

**Comment by johnbachman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btl534 is OK
- 10.1093/bioinformatics/btq129 is OK
- 10.15252/msb.20177651 is OK
- 10.1145/1459352.1459355 is OK

MISSING DOIs

- https://doi.org/10.1089/cmb.2005.12.554 may be missing for title: Word sense disambiguation in the biomedical domain: an overview
- https://doi.org/10.1016/j.jbi.2013.09.009 may be missing for title: Determining the difficulty of Word Sense Disambiguation
- https://doi.org/10.3115/1572364.1572374 may be missing for title: Disambiguation of Biomedical Abbreviations
- https://doi.org/10.1016/j.jbi.2010.08.009 may be missing for title: Disambiguation in the biomedical domain: the role of ambiguity type
- https://doi.org/10.18653/v1/p19-1569 may be missing for title: Language Modelling Makes Sense: Propagating Representations through WordNet for Full-Coverage Word Sense Disambiguation
- https://doi.org/10.18653/v1/p18-1230 may be missing for title: Incorporating Glosses into Neural Word Sense Disambiguation
- https://doi.org/10.1197/jamia.m1533 may be missing for title: A multi-aspect comparison study of supervised word sense disambiguation

INVALID DOIs

- None
```

**Comment by johnbachman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btl534 is OK
- 10.1093/bioinformatics/btq129 is OK
- 10.15252/msb.20177651 is OK
- 10.1145/1459352.1459355 is OK

MISSING DOIs

- https://doi.org/10.1089/cmb.2005.12.554 may be missing for title: Word sense disambiguation in the biomedical domain: an overview
- https://doi.org/10.1016/j.jbi.2013.09.009 may be missing for title: Determining the difficulty of Word Sense Disambiguation
- https://doi.org/10.3115/1572364.1572374 may be missing for title: Disambiguation of Biomedical Abbreviations
- https://doi.org/10.1016/j.jbi.2010.08.009 may be missing for title: Disambiguation in the biomedical domain: the role of ambiguity type
- https://doi.org/10.18653/v1/p19-1569 may be missing for title: Language Modelling Makes Sense: Propagating Representations through WordNet for Full-Coverage Word Sense Disambiguation
- https://doi.org/10.18653/v1/p18-1230 may be missing for title: Incorporating Glosses into Neural Word Sense Disambiguation
- https://doi.org/10.1197/jamia.m1533 may be missing for title: A multi-aspect comparison study of supervised word sense disambiguation

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01708/joss.01708/10.21105.joss.01708.pdf)

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btl534 is OK
- 10.1093/bioinformatics/btq129 is OK
- 10.15252/msb.20177651 is OK
- 10.1145/1459352.1459355 is OK
- 10.1089/cmb.2005.12.554 is OK
- 10.1016/j.jbi.2013.09.009 is OK
- 10.3115/1572364.1572374 is OK
- 10.1016/j.jbi.2010.08.009 is OK
- 10.18653/v1/p19-1569 is OK
- 10.1197/jamia.m1533 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.18653/v1/p18-1230 is INVALID because of 'https://doi.org/' prefix
```

**Comment by kyleniemeyer** [comment]
@johnbachman your earlier requests to check the references didn't work because the PDF needed to be rebuilt first—thanks for adding those! 

Can you remove `https://doi.org/` from that one DOI causing an error? That should be the last edit needed.

**Comment by johnbachman** [comment]
Will do. After that's done, I will tag and release the latest version and update the Zenodo link.

**Comment by johnbachman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01708/joss.01708/10.21105.joss.01708.pdf)

**Comment by johnbachman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btl534 is OK
- 10.1093/bioinformatics/btq129 is OK
- 10.15252/msb.20177651 is OK
- 10.1145/1459352.1459355 is OK
- 10.1089/cmb.2005.12.554 is OK
- 10.1016/j.jbi.2013.09.009 is OK
- 10.3115/1572364.1572374 is OK
- 10.1016/j.jbi.2010.08.009 is OK
- 10.18653/v1/p19-1569 is OK
- 10.18653/v1/p18-1230 is OK
- 10.1197/jamia.m1533 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by johnbachman** [comment]
@whedon set 10.5281/zenodo.3610528 as archive

**Comment by whedon** [comment]
I'm sorry @johnbachman, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by johnbachman** [comment]
@brainstorm @kyleniemeyer The updated Zenodo archive (for Adeft version 5.5) is 10.5281/zenodo.3610528. Once that is updated we should be good to go.

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.3610528 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3610528" target="_blank">10.5281/zenodo.3610528</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btl534 is OK
- 10.1093/bioinformatics/btq129 is OK
- 10.15252/msb.20177651 is OK
- 10.1145/1459352.1459355 is OK
- 10.1089/cmb.2005.12.554 is OK
- 10.1016/j.jbi.2013.09.009 is OK
- 10.3115/1572364.1572374 is OK
- 10.1016/j.jbi.2010.08.009 is OK
- 10.18653/v1/p19-1569 is OK
- 10.18653/v1/p18-1230 is OK
- 10.1197/jamia.m1533 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1231

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1231, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1217882269190361090) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1232
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01708](https://doi.org/10.21105/joss.01708)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @johnbachman on your article's publication in JOSS!

Many thanks to @GullyAPCBurns and @gbader for reviewing, and @brainstorm for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01708/status.svg)](https://doi.org/10.21105/joss.01708)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01708">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01708/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01708/status.svg
   :target: https://doi.org/10.21105/joss.01708
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01708/status.svg)](https://doi.org/10.21105/joss.01708)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by johnbachman** [comment]
Thanks all!! @brainstorm @kyleniemeyer @gbader @GullyAPCBurns
