### ISSUE TITLE
[PRE REVIEW]: OnlineStats.jl: A Julia package for statistics on data streams

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1709]
**Submitting author:** @joshday (<a href="http://orcid.org/0000-0002-7490-6986">Josh Day</a>)
**Repository:** <a href="https://github.com/joshday/OnlineStats.jl" target ="_blank">https://github.com/joshday/OnlineStats.jl</a>
**Version:** v1.0.0
**Editor:** @karthik
**Reviewers:** @vchuravy, @ahwillia

**Author instructions**

Thanks for submitting your paper to JOSS @joshday. **Currently, there isn't an JOSS editor assigned** to your paper.

@joshday if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01709/joss.01709/10.21105.joss.01709.pdf)

**Comment by arfon** [comment]
:wave: @karthik - would you be willing to edit this submission for JOSS?

**Comment by karthik** [comment]
@arfon Unfortunately I'm not connected with the Julia community or use the language.

**Comment by karthik** [comment]
@@whedon assign @karthik as editor

**Comment by karthik** [comment]
@vchuravy @mlxd Can you consider reviewing this submission? 🙏

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by mlxd** [comment]
Hi, sorry but I don't have the time for this right now. If things haven't moved forward by the start of October feel free to let me know and I will try have a look then.

**Comment by karthik** [comment]
ok, thanks @mlxd 
If you can recommend other folks who might be suitable to review, I would welcome some names. :pray:

**Comment by vchuravy** [comment]
I have time to review this in about a week.

**Comment by karthik** [comment]
@vchuravy Can I assign you to this now?

**Comment by karthik** [comment]
@mlxd Would you also have time to review not that we're in October? :pray:

**Comment by mlxd** [comment]
> @mlxd Would you also have time to review not that we're in October? 🙏

Hi, my current timeline has changed and I will be unable to review this. I think @vchuravy may better offer a suggested reviewer than I.

**Comment by vchuravy** [comment]
Yes please do.

**Comment by karthik** [comment]
@whedon add @vchuravy as reviewer

**Comment by whedon** [comment]
OK, @vchuravy is now a reviewer

**Comment by karthik** [comment]
Hello @ahwillia would you be able and willing to serve as the second reviewer for this submission? 🙏

**Comment by ahwillia** [comment]
I'm unavailable until after Nov 1, but could review then.

**Comment by karthik** [comment]
ok no problem. I'll assign you as the second reviewer and you can complete in November.

**Comment by karthik** [comment]
ok no problem. I'll assign you as the second reviewer and you can complete in November.

**Comment by karthik** [comment]
@whedon add @ahwillia as reviewer

**Comment by whedon** [comment]
OK, @ahwillia is now a reviewer

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1816. Feel free to close this issue now!
