### ISSUE TITLE
[PRE REVIEW]: Mongiris: a package for manipulating IRIS

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1710]
**Submitting author:** @fduchatea (<a href="http://orcid.org/0000-0001-6803-917X">Fabien Duchateau</a>)
**Repository:** <a href="https://gitlab.liris.cnrs.fr/fduchate/mongiris" target ="_blank">https://gitlab.liris.cnrs.fr/fduchate/mongiris</a>
**Version:** 0.40
**Editor:** @gkthiruvathukal
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @fduchatea. **Currently, there isn't an JOSS editor assigned** to your paper.

@fduchatea if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1710 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
Whedon can't compile this paper as there's [~750Mb file](https://gitlab.liris.cnrs.fr/fduchate/mongiris/blob/master/mongiris/data/dump/dump-dbinsee.bin) in the repository 😱

**Comment by arfon** [comment]
Paper compiled locally: [10.21105.joss.01710.pdf](https://github.com/openjournals/joss-reviews/files/3581836/10.21105.joss.01710.pdf)

**Comment by arfon** [comment]
@gkthiruvathukal - would you be willing to edit this submission for JOSS?

**Comment by gkthiruvathukal** [comment]
@arfon Yes. On my way to Prague for a conference but will get started as soon as possible.

**Comment by arfon** [comment]
Excellent. Thanks @gkthiruvathukal!

**Comment by arfon** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by Kevin-Mattheus-Moerman** [comment]
@gkthiruvathukal :wave: are you able to find reviewers for this work? Thanks

**Comment by gkthiruvathukal** [comment]
@Kevin-Mattheus-Moerman I will be following up on this submission shortly. We discussed this submission on the editors list and decided that it falls under the utility/wrapper category. I will post the decision below.

**Comment by gkthiruvathukal** [comment]
Dear @fduchatea:

After a pre-review of your submission, and an assessment by the editorial board at large, we find that this submission does not quite meet our [submission requirements](http://joss.theoj.org/about#submission_requirements). In particular, while the software seems very useful, it falls under the 'Minor utility/Thin wrapper' category, and we therefore decided not to put it through review. 

Thank you for considering JOSS as a venue for your software, and I hope you'll submit other software with research application in the future.

Separately, I apologize for the delay in letting you know about our decision. The past few weeks have been a bit crazy at the office.
