### ISSUE TITLE
[PRE REVIEW]: ShinyCOPASI: a web-based exploratory interface for COPASI models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1711]
**Submitting author:** @pmendes (<a href="http://orcid.org/0000-0001-6507-9168">Pedro Mendes</a>)
**Repository:** <a href="https://github.com/copasi/shinyCOPASI" target ="_blank">https://github.com/copasi/shinyCOPASI</a>
**Version:** v.1.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @pmendes. **Currently, there isn't an JOSS editor assigned** to your paper.

@pmendes if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #1711 with the following error: 

 Error reading bibliography ./paper.bib (line 60, column 22):
unexpected ")"
expecting white space, "#", "," or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by abishakGupta** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01711/joss.01711/10.21105.joss.01711.pdf)

**Comment by arfon** [comment]
Hi @abishakGupta, thanks for your submission to JOSS. Unfortunately, after consulting with the JOSS editorial team, we've determined that this submission is out of scope for JOSS: https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements

Thanks again for your interest in JOSS.
