### ISSUE TITLE
[PRE REVIEW]: RDF-to-SemanticWiki: Creating ontology-based semantic wikis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1712]
**Submitting author:** @alvarosaurus (<a href="http://orcid.org/0000-0001-7620-1907">Alvaro Ortiz-Troncoso</a>)
**Repository:** <a href="https://gitlab.com/alvarosaurus/RDF-to-SemanticWiki" target ="_blank">https://gitlab.com/alvarosaurus/RDF-to-SemanticWiki</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @alvarosaurus. **Currently, there isn't an JOSS editor assigned** to your paper.

@alvarosaurus if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1712 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1712 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01712/joss.01712/10.21105.joss.01712.pdf)

**Comment by alvarosaurus** [comment]
@arfon. Many thanks for taking care of my submission. I noticed in the PDF proof that some referenced articles were not formatted correctly in the paper.bib file. I committed the changes to the master branch.

**Comment by alvarosaurus** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01712/joss.01712/10.21105.joss.01712.pdf)

**Comment by alvarosaurus** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01712/joss.01712/10.21105.joss.01712.pdf)

**Comment by alvarosaurus** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01712/joss.01712/10.21105.joss.01712.pdf)

**Comment by alvarosaurus** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01712/joss.01712/10.21105.joss.01712.pdf)

**Comment by alvarosaurus** [comment]
@arfon. Sorry but I don't get it. In the papaer.bib file have a reference that looks like this:
```
@misc{noy2001ontology,
  title={Ontology development 101: A guide to creating your first ontology},
  author={Noy, Natalya and McGuinness, Deborah},
  url={https://protege.stanford.edu/publications/ontology_development/ontology101.pdf},
  year={2001}
}
```
yet whedon is nor rendereing it at all. Any ideas?

**Comment by arfon** [comment]
You're missing the `@` in the `paper.md`. Currently the citations is `[noy2001ontology]` when it should be `[@noy2001ontology]`.

**Comment by alvarosaurus** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01712/joss.01712/10.21105.joss.01712.pdf)

**Comment by alvarosaurus** [comment]
@arfon: Great! Now the citations are correct.

Suggested reviewers:

@nuest: the application is provided as Docker containers, and reviewing those would be a plus. The application is used in the context of earth science, although the source code should be domain-neutral.

@fsteeg: the core of this appplication is to produce a semantically enhanced collaboration environment. I think this could be of interest to someone working in information science.

**Comment by alvarosaurus** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by arfon** [comment]
Hi @alvarosaurus, thanks again for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this submission does not meet our [submission criteria](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) in terms of scope. While this software looks useful, we believe it's more of a utility package rather than research software.

Thanks again for your interest in JOSS.
