### ISSUE TITLE
[PRE REVIEW]: GaitPy: An Open-Source Python Package for Gait Analysis Using an Accelerometer on the Lower Back

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1713]
**Submitting author:** @matt002 (<a href="http://orcid.org/0000-0001-9954-7003">Matthew Czech</a>)
**Repository:** <a href="https://github.com/matt002/GaitPy" target ="_blank">https://github.com/matt002/GaitPy</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewers:** @finsberg, @abhishektha

**Author instructions**

Thanks for submitting your paper to JOSS @mdc007. **Currently, there isn't an JOSS editor assigned** to your paper.

@mdc007 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1713 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1713/paper/paper.md): found character that cannot start any token while scanning for the next token at line 4 column 4 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:115:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @mdc007, many thanks for your submission to JOSS. Firstly, this pull request should fix your paper compilation: https://github.com/matt002/GaitPy/pull/1

Second, it's not immediately clear to me that your submission is currently up to standard for JOSS yet I'm afraid. In particular the fact that this is a written for Python 2.7 suggests to me that this package is close to deprecated and not ['designed for maintainable extension'](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).

Also, there don't currently appear to be any automated/unit tests which will be a problem during review.

**Comment by Matt-pfz** [comment]
Thank you for your edits and feedback. I will work to address these problems with the submission and update you when completed.

**Comment by Matt-pfz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01713/joss.01713/10.21105.joss.01713.pdf)

**Comment by Matt-pfz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01713/joss.01713/10.21105.joss.01713.pdf)

**Comment by kthyng** [comment]
Hi @trallard! I see you work in biomechanics. Could you edit this submission?

**Comment by danielskatz** [comment]
👋 @meg-simula - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
👋 @meg-simula - would you be willing to edit this submission? (just checking again...)

**Comment by meg-simula** [comment]
Thanks for checking @danielskatz - I have some open reviews and I would like to get those sorted before taking on more though.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by matt002** [comment]
@arfon - Sure: moorepants, nirum, melund, ixjlyons, could be good fits to review my submission. Apologies for the confusion, I would like the matt002 identity to be associated with this submission.

**Comment by arfon** [comment]
> @arfon - Sure: moorepants, nirum, melund, ixjlyons, could be good fits to review my submission. Apologies for the confusion, I would like the matt002 identity to be associated with this submission.

OK thanks. Many of those reviewers have been doing a lot for us recently so I'm going to look a little more broadly.

**Comment by arfon** [comment]
@finsberg @abhishektha - would you both be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by finsberg** [comment]
@arfon, I can review this submission.

**Comment by arfon** [comment]
> @arfon, I can review this submission.

Wonderful, thanks so much @finsberg. I'll add you as a reviewer now but will hold off starting the actual review thread until I've found a second reviewer.

**Comment by arfon** [comment]
@whedon add @finsberg as reviewer

**Comment by whedon** [comment]
OK, @finsberg is now a reviewer

**Comment by abhishektha** [comment]
@arfon, Sure! Would be glad to review!

**Comment by arfon** [comment]
@whedon add @abhishektha as reviewer

**Comment by whedon** [comment]
OK, @abhishektha is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1778. Feel free to close this issue now!

**Comment by arfon** [comment]
@finsberg, @abhishektha - many thanks for agreeing to review this submission. See you over in #1778 where the actual review will take place.
