### ISSUE TITLE
[PRE REVIEW]: BayesPostEst: An R Package to Generate Postestimation Quantities for Bayesian MCMC Estimation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1714]
**Submitting author:** @jkarreth (<a href="http://orcid.org/0000-0003-4586-7153">Johannes Karreth</a>)
**Repository:** <a href="https://github.com/ShanaScogin/BayesPostEst" target ="_blank">https://github.com/ShanaScogin/BayesPostEst</a>
**Version:** 0.1.0
**Editor:** @terrytangyuan
**Reviewers:** @svmiller, @TiagoVentura

**Author instructions**

Thanks for submitting your paper to JOSS @jkarreth. **Currently, there isn't an JOSS editor assigned** to your paper.

@jkarreth if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1714 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1714 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01714/joss.01714/10.21105.joss.01714.pdf)

**Comment by arfon** [comment]
:wave: @terrytangyuan - would you be willing to edit this submission for JOSS?

**Comment by jkarreth** [comment]
Thank you for getting this started! The following might be possible reviewers:

- @amoeba
- @andrewheiss
- @becarioprecario
- @benmarwick
- @bradweiner
- @caseyyoungflesh
- @cdcrabtree
- @earino
- @fabian-s
- @jacobsoj
- @jsta
- @lindemann09
- @mariacuellar
- @mdogucu
- @MikeLydeamore
- @pacoramon
- @paulgovan 
- @pboesu
- @rmhogervorst
- @soodoku
- @svmiller
- @tweed1e
- @vincentarelbundock
- @Volkerschmid

**Comment by terrytangyuan** [comment]
@whedon assign @terrytangyuan as editor

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by jkarreth** [comment]
@terrytangyuan , thank you for stepping up to edit this! Please let me know if I can help in any way by getting this on the radar of a few more potential reviewers. Thank you!

**Comment by terrytangyuan** [comment]
Looks like you've already tagged a lot people already so let's wait a couple more days. 

👋 Hi, if you would like to review this submission, please let us know here! 
@amoeba @andrewheiss @becarioprecario @benmarwick @bradweiner @caseyyoungflesh @cdcrabtree @earino @fabian-s @jacobsoj @jsta @lindemann09 @mariacuellar @mdogucu @MikeLydeamore @pacoramon @paulgovan @pboesu @RMHogervorst @soodoku @svmiller @tweed1e @vincentarelbundock @volkerschmid

**Comment by svmiller** [comment]
I'll review this submission if that's okay with the editorial team/authors.

**Comment by TiagoVentura** [comment]
I can review this submission as well. Thanks!

**Comment by terrytangyuan** [comment]
@whedon assign @svmiller as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @svmiller

**Comment by terrytangyuan** [comment]
@whedon add @TiagoVentura as reviewer

**Comment by whedon** [comment]
OK, @TiagoVentura is now a reviewer

**Comment by terrytangyuan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1722. Feel free to close this issue now!

**Comment by terrytangyuan** [comment]
@TiagoVentura @svmiller Thank you! Please head over to #1722 for the review.
