### ISSUE TITLE
[PRE REVIEW]: yenpathy: An R Package to Quickly Find K Shortest Paths Through a Weighted Graph

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1715]
**Submitting author:** @toph-allen (<a href="http://orcid.org/0000-0003-4580-091X">Toph Allen</a>)
**Repository:** <a href="https://github.com/ecohealthalliance/yenpathy" target ="_blank">https://github.com/ecohealthalliance/yenpathy</a>
**Version:** 1.0.0
**Editor:** @kyleniemeyer
**Reviewers:** @corybrunson, @szhorvat

**Author instructions**

Thanks for submitting your paper to JOSS @toph-allen. **Currently, there isn't an JOSS editor assigned** to your paper.

@toph-allen if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01715/joss.01715/10.21105.joss.01715.pdf)

**Comment by arfon** [comment]
:wave: @kyleniemeyer - would you be willing to edit this submission for JOSS?

**Comment by kyleniemeyer** [comment]
@arfon I don't know anything about R, but can cover this if needed

**Comment by toph-allen** [comment]
We suggest @michaellevy as a reviewer, who was an early user of `yenpathy` and filed an unsolicited issue.

**Comment by arfon** [comment]
> @arfon I don't know anything about R, but can cover this if needed

Yeah, sorry about this. I'm struggling with finding editors to cover submissions right now sorry.

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
Hi @michaellevy, are you interested in and available to review this submission?

**Comment by kyleniemeyer** [comment]
@toph-allen can you suggest any other potential reviewers? I will start looking myself, but other suggestions would be very helpful.

**Comment by kyleniemeyer** [comment]
Hi @corybrunson @vc1492a @camillescott @szhorvat, are any of you be interested and available to review this submission for JOSS?

**Comment by corybrunson** [comment]
@kyleniemeyer sure, i have some background both in graph theory and in R, and i'll be interested to see how the algorithm compares. I should be able to do a first full pass within 5 days.

**Comment by kyleniemeyer** [comment]
Thanks @corybrunson!

**Comment by kyleniemeyer** [comment]
@whedon add @corybrunson as reviewer

**Comment by whedon** [comment]
OK, @corybrunson is now a reviewer

**Comment by corybrunson** [comment]
@kyleniemeyer i'm sorry if i'm just confused, but i'm wondering why i was given access to `openjournals/joss-reviews`. I reflexively accepted it, thinking it was the review repo, and then started getting updates on reviews and pre-reviews from all of JOSS. I've unwatched the repo but i want to check whether i was supposed to have been granted access. Thanks!

P.S. I'm still down to review this submission!

**Comment by kyleniemeyer** [comment]
@corybrunson yes, you are given temporary access so that you can check off items in the review issue, when it is started—which will happen when I have a second reviewer assigned. Unwatching the repo is definitely what we recommend.

**Comment by vc1492a** [comment]
@kyleniemeyer thanks for reaching out about this work and the possibility to provide a review. Unfortunately I will need to pass on this one due to some recent time constraints.

**Comment by toph-allen** [comment]
> @toph-allen can you suggest any other potential reviewers? I will start looking myself, but other suggestions would be very helpful.

@kyleniemeyer I don’t have any suggestions that come to mind off the top of my head. I’ll think on it and let you know if someone comes to mind.

**Comment by szhorvat** [comment]
I can take a look but not right now. I would need about two weeks.

**Comment by kyleniemeyer** [comment]
@szhorvat thanks, that timeframe is perfectly fine—we generally ask reviewers to complete their reviews in 2-3 weeks (ideally) anyways! I will add you as the second reviewer and get the review issue started.

**Comment by kyleniemeyer** [comment]
@whedon add @szhorvat as reviewer

**Comment by whedon** [comment]
OK, @szhorvat is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1766. Feel free to close this issue now!
