### ISSUE TITLE
[PRE REVIEW]: oifits :  A Python Package to Analyse EHT Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1718]
**Submitting author:** @shreyasbapat (<a href="http://orcid.org/0000-0002-0870-4665">Shreyas Bapat</a>)
**Repository:** <a href="https://github.com/shreyasbapat/python-oifits" target ="_blank">https://github.com/shreyasbapat/python-oifits</a>
**Version:** v0.2.0
**Editor:** @arfon
**Reviewers:** @taldcroft, @mwcraig

**Author instructions**

Thanks for submitting your paper to JOSS @shreyasbapat. **Currently, there isn't an JOSS editor assigned** to your paper.

@shreyasbapat if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01718/joss.01718/10.21105.joss.01718.pdf)

**Comment by shreyasbapat** [comment]
I am not sure what tags to look for in this case, so I will go with Data Science. 
Here are my suggestions for potential reviewers: @jkahn @trallard 

cc @whedon @arfon :D

**Comment by arfon** [comment]
Thanks for this submission @shreyasbapat. While this looks like a useful piece of code, it feels like it would be much more useful contributed to an existing core package such as [`astropy.fits`](https://docs.astropy.org/en/stable/io/fits/). 

Have you considered trying to contribute to this package?

**Comment by shreyasbapat** [comment]
Hi @arfon 
I think astropy is kind of a general utility package while this is more specific. I can ask in the chatroom but I am very sure that the developers will deny for the same kind of reason .

**Comment by shreyasbapat** [comment]
Hi @afron I got the reply: 
`If it is not in the official FITS standards, it is not for astropy.io.fits, I am afraid.`
They have suggested to make it a affiliated package.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon, can you reply to @shreyasbapat

**Comment by shreyasbapat** [comment]
Thanks @Kevin-Mattheus-Moerman ! @arfon Are there any updates? :smile:

**Comment by arfon** [comment]
@shreyasbapat - are there any folks you would suggest as potential reviewers here? 

Also, before sending this out for review, it would be good if you could augment/extend the tests. The current automated tests look to be [very limited in scope](https://github.com/shreyasbapat/python-oifits/tree/master/src/oifits/tests).

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by shreyasbapat** [comment]
Definitely @arfon  I will do it in a day or two!

**Comment by shreyasbapat** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by shreyasbapat** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01718/joss.01718/10.21105.joss.01718.pdf)

**Comment by shreyasbapat** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01718/joss.01718/10.21105.joss.01718.pdf)

**Comment by shreyasbapat** [comment]
I added tests. 
And as I said earlier, 

I am not sure what tags to look for in this case, so I will go with Data Science.
Here are my suggestions for potential reviewers: @jkahn @trallard

Thanks @arfon

**Comment by arfon** [comment]
:wave: @mwcraig @taldcroft - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by taldcroft** [comment]
Yes, I would be happy to do the review.

**Comment by mwcraig** [comment]
Yes, I am also happy to review.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon add @taldcroft as reviewer

**Comment by whedon** [comment]
OK, @taldcroft is now a reviewer

**Comment by arfon** [comment]
@whedon add @mwcraig as reviewer

**Comment by whedon** [comment]
OK, @mwcraig is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1743. Feel free to close this issue now!

**Comment by arfon** [comment]
@taldcroft, @mwcraig, @shreyasbapat - see you over in #1743 where the actual review will take place.
