### ISSUE TITLE
[PRE REVIEW]: xrnet: Hierarchical Regularized Regression to Incorporate External Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1719]
**Submitting author:** @gmweaver (<a href="http://orcid.org/0000-0002-9918-8386">Garrett Weaver</a>)
**Repository:** <a href="https://github.com/USCbiostats/xrnet" target ="_blank">https://github.com/USCbiostats/xrnet</a>
**Version:** 0.0.0.9000
**Editor:** @mgymrek
**Reviewers:** @juanvillada, @jsgalan

**Author instructions**

Thanks for submitting your paper to JOSS @gmweaver. **Currently, there isn't an JOSS editor assigned** to your paper.

@gmweaver if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01719/joss.01719/10.21105.joss.01719.pdf)

**Comment by gmweaver** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01719/joss.01719/10.21105.joss.01719.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@Soneson @mgymrek @Guimera could one of you edit this submission? Would you be able to suggest some reviewers? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@soneson @mgymrek :point_up:

**Comment by mgymrek** [comment]
I can edit

**Comment by mgymrek** [comment]
@whedon assign @mgymrek as editor

**Comment by whedon** [comment]
OK, the editor is @mgymrek

**Comment by mgymrek** [comment]
@jsgalan @road2stat @nilesh-patil @vsoch would either of you be able to review this submission?

**Comment by vsoch** [comment]
I'm actually on a trip so I am not!

**Comment by mgymrek** [comment]
@jsgalan @road2stat @nilesh-patil @juanvillada @chlalanne would either of you be able to review?

**Comment by juanvillada** [comment]
Count me in! 👍🏼

**Comment by jsgalan** [comment]
Hi guys, I am currently out of office on a conference, I will be back by the end of the week, and can starting editing by next week.

Count me in!

Thanks

**Comment by mgymrek** [comment]
@whedon assign @juanvillada as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @juanvillada

**Comment by mgymrek** [comment]
@whedon add @jsgalan as reviewer

**Comment by whedon** [comment]
OK, @jsgalan is now a reviewer

**Comment by mgymrek** [comment]
Thanks @juanvillada and @jsgalan! I will now start a review thread, where you can complete the reviews. Please let me know if you have any questions on the process.

**Comment by mgymrek** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1761. Feel free to close this issue now!
