### ISSUE TITLE
[REVIEW]: nse: Computation of Numerical Standard Errors in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#172]
**Submitting author:** @ArdiaD (<a href="http://orcid.org/0000-0003-2823-782X">David Ardia</a>)
**Repository:** <a href="https://github.com/keblu/nse" target ="_blank">https://github.com/keblu/nse</a>
**Version:** v1-00.15
**Editor:** @arfon
**Reviewer:** @braverock
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.268594" target="_blank">10.5281/zenodo.268594</a>

## Status

[![status](http://joss.theoj.org/papers/9ad602c309d8cbd10ecdc546fdb25462/status.svg)](http://joss.theoj.org/papers/9ad602c309d8cbd10ecdc546fdb25462)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/9ad602c309d8cbd10ecdc546fdb25462"><img src="http://joss.theoj.org/papers/9ad602c309d8cbd10ecdc546fdb25462/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/9ad602c309d8cbd10ecdc546fdb25462/status.svg)](http://joss.theoj.org/papers/9ad602c309d8cbd10ecdc546fdb25462)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/keblu/nse" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/keblu/nse">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1-00.15)?
- [x] **Authorship:** Has the submitting author (ArdiaD) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @braverock it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@braverock - please take a look at the reviewer guidelines here (http://joss.theoj.org/about#reviewer_guidelines) and update the checklist as you proceed. Please let me know if you have any questions.

**Comment by ArdiaD** [comment]
@braverock thanks for your time. Look forward to receiving your feedback.

**Comment by braverock** [comment]
@arfon I've completed the checklist.  I was previously familiar with the NSE package, so most of what I had to do was to check that JOSS guidelines had been met.  @keblu and @ArdiaD have implemented multiple ways of computing standard errors of a given metric, many of which have not appeared in the R language previously.  It is a worthwhile contribution to the literature, and I recommend publication without reservations.

**Comment by ArdiaD** [comment]
Thanks @braverock for your review and your comments!

**Comment by arfon** [comment]
Many thanks for the review here @braverock.

@ArdiaD - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by ArdiaD** [comment]
@keblu can you create a Zenodo account and create a DOI for the current nse project; please follow these steps: https://guides.github.com/activities/citable-code/

**Comment by keblu** [comment]
Hi @arfon. Here you go: [![DOI](https://zenodo.org/badge/70136711.svg)](https://zenodo.org/badge/latestdoi/70136711). Thanks a lot!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.268594 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.268594" target="_blank">10.5281/zenodo.268594</a> is the archive.

**Comment by arfon** [comment]
@braverock - many thanks for your review here ✨ 

@ArdiaD & @keblu your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00172 ⚡️ 🚀 💥
