### ISSUE TITLE
[REVIEW]: Torsional Axisymmetric Core Oscillations Visualiser (TACO-VIS): A python module for animating torsional wave data for fluid planetary cores.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1720]
**Submitting author:** @sam-greenwood (<a href="http://orcid.org/0000-0001-9303-6229">Sam Greenwood</a>)
**Repository:** <a href="https://github.com/sam-greenwood/taco_vis" target ="_blank">https://github.com/sam-greenwood/taco_vis</a>
**Version:** v1.0
**Editor:** @leouieda
**Reviewer:** @malmans2, @banesullivan
**Archive:** <a href="https://doi.org/10.5281/zenodo.3902334" target="_blank">10.5281/zenodo.3902334</a>

## Status

[![status](https://joss.theoj.org/papers/e6b681b203f14a3ebaea2571f7519d3e/status.svg)](https://joss.theoj.org/papers/e6b681b203f14a3ebaea2571f7519d3e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e6b681b203f14a3ebaea2571f7519d3e"><img src="https://joss.theoj.org/papers/e6b681b203f14a3ebaea2571f7519d3e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e6b681b203f14a3ebaea2571f7519d3e/status.svg)](https://joss.theoj.org/papers/e6b681b203f14a3ebaea2571f7519d3e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/sam-greenwood/taco_vis" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@malmans2 & @banesullivan, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @leouieda know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sam-greenwood/taco_vis">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@sam-greenwood) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sam-greenwood/taco_vis">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@sam-greenwood) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @malmans2, @banesullivan it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01720/joss.01720/10.21105.joss.01720.pdf)

**Comment by leouieda** [comment]
:wave: @malmans2 @banesullivan @sam-greenwood this is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#1720` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me here (@leouieda) or email me privately if you have any questions/concerns.

**Comment by malmans2** [comment]
Hi @sam-greenwood. I just started the review and I'm going to work on it this week. Sorry about the delay!
While reading the paper I noticed a couple of minor issues:

- [ ] Figure 1 is never mentioned.
- [ ] All references are missing a doi. 

Other than that, I think it's well written and well structured.
I also have a suggestion about figure 2 and 3: Have you considered showing them in a single figure? They are based on the same data, so you could show them side-by-side and with just one colorbar.

**Comment by banesullivan** [comment]
Hi @sam-greenwood, apologies for taking a while to get around to this! As a first pass, I just opened up quite a few issues in the repo that we can work together to resolve for this review.

I'll try to review the paper soon here as well!

Overall (from my first pass) it looks like the library is in need of:

- [ ] clean up around the install script (`setup.py` and repo meta info)
- [ ] clear tests and to validate it is working on a CI service like Travis - I can help set up those build scripts as we move along! 
- [ ] a documentation website with examples and the full API docs should also be automatically generated - Read the Docs is great for this

**Comment by malmans2** [comment]
I agree with all bullet points by @banesullivan, especially on tests and documentation.
@sam-greenwood here are a few more:

- [ ] Follow the style guide for Python.
- [ ] Add community guidelines.
- [ ] Since your coauthors are not in the github contributors list, mention them in the documentation.

I haven't play much with the tools yet, I'm going to do it in the next couple of days!

**Comment by sam-greenwood** [comment]
Thanks both for the feedback, I'll get to work making the changes and address any issues I've got questions about (which I'm sure there will be as I'm somewhat new to this!)

**Comment by leouieda** [comment]
@banesullivan @malmans2 thank you for your reviews and opening issues on the project repo :+1: 

@sam-greenwood please keep us informed of the progress and don't hesitate to ask questions or reach out if you need any help/clarification implementing the requested changes.

**Comment by sam-greenwood** [comment]
> @banesullivan @malmans2 thank you for your reviews and opening issues on the project repo 👍
> 
> @sam-greenwood please keep us informed of the progress and don't hesitate to ask questions or reach out if you need any help/clarification implementing the requested changes.

Will do, I've just been away on a brief holiday so haven't had a chance to continue work on this just yet but will try to address the majority of the issues this weekend.

**Comment by danielskatz** [comment]
👋 @sam-greenwood - I'm just checking in on this as the associate-editor-in-chief on duty this week ...

**Comment by sam-greenwood** [comment]
> 👋 @sam-greenwood - I'm just checking in on this as the associate-editor-in-chief on duty this week ...

Good thanks. I asked a question about CI testing to which I did get a prompt answer but didn't get a notification for it, so was waiting around the last 2 weeks for a response I'd already had, my bad. Just seen it now so will work on that this weekend.

**Comment by banesullivan** [comment]
I finally got around to reviewing the paper! Overall I think it is well written and in line with most JOSS submissions, being a brief and high-level description of the software. I had the same concerns as @malmans2 in the [comment above](https://github.com/openjournals/joss-reviews/issues/1720#issuecomment-536698452) as well as a few other points:

- [ ] Figure 1 isn't mentioned (per @malmans2's comment), but also, was this figure made with the mentioned software? If not, you may consider removing it.

- [ ] Minor spelling/grammar: "python" should be "Python"

- It might be worth exploring combining figures 2, 3, and 4 as one figure with the three graphics in a single row (just a thought/suggestion)

- [ ] **State of the field requirement (per reviewer guidelines):** This part was a bit unclear to me from the paper. The following paragraph:

    > Although these torsional oscillations, described by the azimuthal component of velocity, uφ, can be visualised by static 2D (the cylindrical radius, s and time, t) plots (Cox, Livermore, & Mound, 2013; Gillet, Jault, Canet, & Fournier, 2010; Hide, Boggs, & Dickey, 2000; Teed, Jones, & Tobias, 2018), such diagrams do not communicate the geometry of the waves within the spherical core.

    appears to be addressing this, but it would be best to outline whether those references actually have software available or if they only describe the techniques to visualize these data. You then go on to mention that technique's limitations and how this software addresses those limitations, which is good, but I think it is worth mentioning any software out there that leverages those techniques.

- [ ] References. Make sure all have a DOI and:

    > In rapidly-rotating planets such as Earth, one important type of dynamical behaviour is longitudinal ‘torsional’ oscillations of concentric cylinders aligned with the rotation axis, each of which spans the height of the spherical core.

    This should be cited to point the reader to a paper/reference about this

**Comment by leouieda** [comment]
:wave: hi @sam-greenwood @banesullivan @malmans2 just checking on the review. What is the progress on @banesullivan and @malmans2 questions?

> You then go on to mention that technique's limitations and how this software addresses those limitations, which is good, but I think it is worth mentioning any software out there that leverages those techniques.

I agree with @banesullivan on this. It would be good to mention (and cite) any software that does something similar, if it exists. If not, then a statement about the lack of software would also make a compelling case.

**Comment by labarba** [comment]
Hi everyone — what are the next actions on this submission? It's been quiet for a while now ...

**Comment by sam-greenwood** [comment]
I think I have now addressed all of the issues. I have created the html documentation with sphinx and the comments by @banesullivan above:

1. Figure 1 is now cited at the end of the paragraph prior to it. The figure caption describes it as a cartoon if you feel this is sufficient?
2. Grammar issues changed
3. I have decided to combine 2 of the figure together but leave the last figure separate.
4. I have added in "To address this, we present the first visualisation tool specifically for these oscillations." to make this point clear.
5. All references now have a DOI

**Comment by malmans2** [comment]
Hi @sam-greenwood and Happy New Year!
I'll take a look at everything in the next few days.
In the meantime, could you please re-compile the paper?
Also, it looks like readthedocs is not able to build the documentation: https://readthedocs.org/projects/taco-vis
I'm I looking at the wrong link or are you still working on it?

**Comment by sam-greenwood** [comment]
> Hi @sam-greenwood and Happy New Year!
> I'll take a look at everything in the next few days.
> In the meantime, could you please re-compile the paper?
> Also, it looks like readthedocs is not able to build the documentation: https://readthedocs.org/projects/taco-vis
> Am I looking at the wrong link or are you still working on it?

Hi @malmans2, happy new year to you too. Thanks for spotting that, I've fixed that now, forgot to commit an earlier change I made. I'll recompile the paper now.

**Comment by sam-greenwood** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01720/joss.01720/10.21105.joss.01720.pdf)

**Comment by sam-greenwood** [comment]
With the paper, is there a way to control the figure sizes (at the moment it's just expanding them to fit the page width)?

**Comment by leouieda** [comment]
@sam-greenwood not really. What you can do for now is pad your figures with white space. Bear in mind that JOSS papers are not supposed to serve as documentation for the software. That's why we provide limited resources for styling and figures. Also note that the figure number is generated automatically, so you don't have to include "Figure 1" in your captions.

**Comment by leouieda** [comment]
As @banesullivan suggested:

> It might be worth exploring combining figures 2, 3, and 4 as one figure with the three graphics in a single row (just a thought/suggestion)

**Comment by leouieda** [comment]
:wave: Hi @banesullivan @malmans2 just checking on the status of this review after the holiday. I noticed that there are many unchecked items in the Functionality and Documentation sections. Have these been addressed, raised as issues, or not reviewed yet?

**Comment by sam-greenwood** [comment]
> @sam-greenwood not really. What you can do for now is pad your figures with white space. Bear in mind that JOSS papers are not supposed to serve as documentation for the software. That's why we provide limited resources for styling and figures. Also note that the figure number is generated automatically, so you don't have to include "Figure 1" in your captions.

Ok, fixed that @leouieda, thanks. I've also combined the figures onto one row.

**Comment by sam-greenwood** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01720/joss.01720/10.21105.joss.01720.pdf)

**Comment by malmans2** [comment]
@leouieda I've checked most of the items, and I opened two new issues about API and documentation fixes.

**Comment by sam-greenwood** [comment]
> @leouieda I've checked most of the items, and I opened two new issues about API and documentation fixes.

Happy to make the necessary changes for these, I'll get round to this next week.

**Comment by banesullivan** [comment]
@sam-greenwood, I have gone through your latest changes to the paper and it looks great to me! I have checked off most items in the review above, but I would still like to see the following issues addressed:

- https://github.com/sam-greenwood/taco_vis/issues/8
- https://github.com/sam-greenwood/taco_vis/issues/18
- https://github.com/sam-greenwood/taco_vis/pull/16

**Comment by leouieda** [comment]
@banesullivan @malmans2 thank you for the input! 

@sam-greenwood please let us know when these issues have been addressed so that the reviewers can update the checklist.

**Comment by sam-greenwood** [comment]
Hi @leouieda, @banesullivan @malmans2 , I've made the changes per the reviews suggestions (I apologise for the delay, writing up a thesis has kept me quite busy!). The one suggestion I didn't change is explained [here](https://github.com/sam-greenwood/taco_vis/issues/17).

**Comment by banesullivan** [comment]
@leouieda: To me (after the latest updates), this paper is ready for acceptance! 🎉 

Great work, @sam-greenwood!

**Comment by leouieda** [comment]
Thank for the update @sam-greenwood  and @banesullivan! @malmans2 please let me know as soon as can have a look at the latest revisions.

**Comment by malmans2** [comment]
@sam-greenwood  thanks for addressing my points. I only have two optional suggestions:
- I left a comment [here]( https://github.com/sam-greenwood/taco_vis/issues/18#issuecomment-590884472).
- I would add the documentation status badge, which I believe is the PR started by @banesullivan. 

@leouieda I also think the paper is good to go! Good job @sam-greenwood!

**Comment by malmans2** [comment]
@leouieda, my last comments have been addressed! All issues are closed and I checked all the items in the checklist.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by leouieda** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/gji/ggt414 is OK
- 10.1038/nature09010 is OK
- 10.1046/j.0956-540X.2000.01283.x is OK
- 10.1093/gji/ggy416 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by leouieda** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01720/joss.01720/10.21105.joss.01720.pdf)

**Comment by leouieda** [comment]
@sam-greenwood  I made a few editorial suggestions to the paper. After those are integrated please let me know. Tthere a couple of things that you'll need to do after that and before acceptance:

- Double check authors and affiliations (including ORCIDs)
- Make a release of the software with the latest changes from the review and **post the version number here**. This is the version that will be used in the JOSS paper.
- Archive the release on Zenodo/figshare/etc and **post the DOI here**.
- Make sure that the title and author list (including ORCIDs) in the archive match those in the JOSS paper.

**Comment by leouieda** [comment]
:wave: @sam-greenwood just wanted to check in to see how things are going. I know these are difficult times for everyone so there is no rush. Let me know if there anything I can do to help or if you need any further guidance on the tasks above.

**Comment by kyleniemeyer** [comment]
Hi @sam-greenwood, just wanted to follow up and see if you've been able to make progress on the final steps needed.

**Comment by Kevin-Mattheus-Moerman** [comment]
@sam-greenwood your paper is ready for processing and acceptance in JOSS. Please complete the steps outline above :point_up: let us know if you have any questions.

> @sam-greenwood I made a few editorial suggestions to the paper. After those are integrated please let me know. Tthere a couple of things that you'll need to do after that and before acceptance:
> 
>     * Double check authors and affiliations (including ORCIDs)
> 
>     * Make a release of the software with the latest changes from the review and **post the version number here**. This is the version that will be used in the JOSS paper.
> 
>     * Archive the release on Zenodo/figshare/etc and **post the DOI here**.
> 
>     * Make sure that the title and author list (including ORCIDs) in the archive match those in the JOSS paper.

**Comment by sam-greenwood** [comment]
Hi all, apologies about the long delay, it's been a difficult time recently. Hope all is well with everybody given the unique circumstances. @leouieda @Kevin-Mattheus-Moerman @kyleniemeyer  I've addressed those 4 points now:

* Double check authors and affiliations (including ORCIDs)
All double checked. One affiliation was updated. (I'll re-generate the pdf below such that it is updated)

* Make a release of the software with the latest changes from the review
Release of v1.1 has been created

* Archive the release on Zenodo/figshare/etc
DOI for Zenodo is: 10.5281/zenodo.3902334

* Make sure that the title and author list (including ORCIDs) in the archive match those in the JOSS paper.

The paper in the archive has the correct details.

**Comment by sam-greenwood** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01720/joss.01720/10.21105.joss.01720.pdf)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3902334 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3902334" target="_blank">10.5281/zenodo.3902334</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/gji/ggt414 is OK
- 10.1038/nature09010 is OK
- 10.1046/j.0956-540X.2000.01283.x is OK
- 10.1093/gji/ggy416 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1509

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1509, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1274834939847024640) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1510
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01720](https://doi.org/10.21105/joss.01720)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@malmans2, @banesullivan - many thanks for your reviews here and to @leouieda for editing this submission ✨ 

@sam-greenwood - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01720/status.svg)](https://doi.org/10.21105/joss.01720)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01720">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01720/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01720/status.svg
   :target: https://doi.org/10.21105/joss.01720
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01720/status.svg)](https://doi.org/10.21105/joss.01720)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
