### ISSUE TITLE
[REVIEW]: MiSTree: a Python package for constructing and analysing Minimum Spanning Trees

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1721]
**Submitting author:** @knaidoo29 (<a href="http://orcid.org/0000-0002-9182-1802">Krishna Naidoo</a>)
**Repository:** <a href="https://github.com/knaidoo29/mistree" target ="_blank">https://github.com/knaidoo29/mistree</a>
**Version:** v1.2
**Editor:** @xuanxu
**Reviewer:** @melissawm, @zonca
**Archive:** <a href="https://doi.org/10.5281/zenodo.3495008" target="_blank">10.5281/zenodo.3495008</a>

## Status

[![status](https://joss.theoj.org/papers/461d79e9e5faf21029c0a7b1c928be28/status.svg)](https://joss.theoj.org/papers/461d79e9e5faf21029c0a7b1c928be28)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/461d79e9e5faf21029c0a7b1c928be28"><img src="https://joss.theoj.org/papers/461d79e9e5faf21029c0a7b1c928be28/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/461d79e9e5faf21029c0a7b1c928be28/status.svg)](https://joss.theoj.org/papers/461d79e9e5faf21029c0a7b1c928be28)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/knaidoo29/mistree" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@melissawm & @zonca, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @xuanxu know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/knaidoo29/mistree">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@knaidoo29) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/knaidoo29/mistree">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@knaidoo29) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @melissawm, @zonca it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01721/joss.01721/10.21105.joss.01721.pdf)

**Comment by zonca** [comment]
## Installation

* missing requirement on `matplotlib` https://github.com/knaidoo29/mistree/issues/1
* package is not installable https://github.com/knaidoo29/mistree/issues/2

**Comment by zonca** [comment]
ok, @knaidoo29, anything related to software looks fine to me, now we'll focus on the paper: https://github.com/knaidoo29/mistree/issues/7

**Comment by knaidoo29** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01721/joss.01721/10.21105.joss.01721.pdf)

**Comment by melissawm** [comment]
Hello @knaidoo29 , I still haven't been able to install mistree, can you take a look at the two issues I just opened? Thanks!

**Comment by knaidoo29** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01721/joss.01721/10.21105.joss.01721.pdf)

**Comment by knaidoo29** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01721/joss.01721/10.21105.joss.01721.pdf)

**Comment by knaidoo29** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01721/joss.01721/10.21105.joss.01721.pdf)

**Comment by zonca** [comment]
@xuanxu Accept

**Comment by xuanxu** [comment]
@zonca: Thanks! (There's some unchecked items in your review list, I guess you consider them done)

**Comment by melissawm** [comment]
@xuanxu Accepted, thanks.

**Comment by xuanxu** [comment]
Great, thanks @melissawm!

**Comment by knaidoo29** [comment]
Great to see that it's been accepted! Really appreciate all the help from both @zonca and @melissawm. I think the code and the paper are now much stronger.

@xuanxu is there anything I need to do before publication?

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01721/joss.01721/10.21105.joss.01721.pdf)

**Comment by xuanxu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1086/311146 is OK
- 10.1002/j.1538-7305.1957.tb01515.x is OK
- 10.1088/1748-0221/12/02/P02009 is OK
- 10.1093/mnras/stt2136 is OK
- 10.1111/j.1365-2966.2009.14508.x is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- https://doi.org/10.1128/jcm.42.9.4230-4236.2004 may be missing for title: Use of the minimum spanning tree model for molecular epidemiological investigation of a nosocomial outbreak of hepatitis C virus infection
- https://doi.org/10.1504/ijcse.2009.029165 may be missing for title: F2PY: a tool for connecting Fortran and Python programs
- https://doi.org/10.2307/2033241 may be missing for title: On the shortest spanning subtree of a graph and the traveling salesman problem

INVALID DOIs

- None
```

**Comment by xuanxu** [comment]
@knaidoo29: Can you take a look at the list of DOIs missing info and add them if [the suggestions](#issuecomment-542829879) from whedon are corect?

**Comment by knaidoo29** [comment]
Hi @xuanxu, just checked these doi's and they are correct. I've uploaded them and added them to the bib file.

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01721/joss.01721/10.21105.joss.01721.pdf)

**Comment by xuanxu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1086/311146 is OK
- 10.1128/JCM.42.9.4230-4236.2004 is OK
- 10.1002/j.1538-7305.1957.tb01515.x is OK
- 10.1088/1748-0221/12/02/P02009 is OK
- 10.1093/mnras/stt2136 is OK
- 10.1111/j.1365-2966.2009.14508.x is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1504/IJCSE.2009.029165 is OK
- 10.2307/2033241 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by xuanxu** [comment]
OK @knaidoo29, everything looks good, here are the next steps:
- Please release a new version from the current master so it includes all the changes made during the review process
- Then archive that latest release in Zenodo
- Check the Zenodo deposit has the correct metadata: title and author name should match the paper; you may also add your ORCID.

Once you do that please report here the Zenodo DOI.

**Comment by knaidoo29** [comment]
Hi @xuanxu, possibly a dumb question but just to clarify does the title have to be the title of the paper or title of the code?

**Comment by xuanxu** [comment]
@knaidoo29 the title of the paper

**Comment by knaidoo29** [comment]
Okay @xuanxu I've created a new version (v1.2) which is archived on zenodo with the doi: 10.5281/zenodo.3495008 and has matching title to the paper, author and orcid.

**Comment by xuanxu** [comment]
@whedon set v1.2 as version

**Comment by whedon** [comment]
OK. v1.2 is the version.

**Comment by xuanxu** [comment]
@whedon set 10.5281/zenodo.3495008 as archive

**Comment by xuanxu** [comment]
Everything looks ready 🎉
Pinging @openjournals/joss-eics for final acceptance

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/jose-eics does anybody know why for [this paper](https://github.com/openjournals/joss-papers/blob/joss.01721/joss.01721/10.21105.joss.01721.pdf) the "matplotlib" project name is broken over 2 lines without a hyphen? is this because it is seen as a piece of code text? Since they use the `` `` `` symbols? i.e. the authors use 
```mardown
Dependencies for ``MiSTree`` include the ``Python`` modules ``numpy`` [@numpy], ``matplotlib`` [@Hunter:2007]
```
In the paper this is broken onto the next line like this: 
> Dependencies for MiSTree include the Python modules ``numpy`` (Oliphant, 2006), ``matplo``
> ``tlib`` (Hunter, 2007), ...

The authors have used code style formatting for all project names. If this is the issue then perhaps a simple quick fix is to use _italic_ fonts rather then `code` fonts for project names.

**Comment by kyleniemeyer** [comment]
@Kevin-Mattheus-Moerman yes, that's probably what's going on. I wonder if adding a line break (`\\`) before the word would help?

**Comment by knaidoo29** [comment]
@Kevin-Mattheus-Moerman I'm happy to change this to italic font instead if that is the cause of the issue.

**Comment by Kevin-Mattheus-Moerman** [comment]
@knaidoo29 sure. Can you make that change and run `@whedon generate pdf` once you are done? Thanks.

**Comment by knaidoo29** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01721/joss.01721/10.21105.joss.01721.pdf)

**Comment by knaidoo29** [comment]
Okay @Kevin-Mattheus-Moerman it looks like this has solved the issue.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1086/311146 is OK
- 10.1128/JCM.42.9.4230-4236.2004 is OK
- 10.1002/j.1538-7305.1957.tb01515.x is OK
- 10.1088/1748-0221/12/02/P02009 is OK
- 10.1093/mnras/stt2136 is OK
- 10.1111/j.1365-2966.2009.14508.x is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1504/IJCSE.2009.029165 is OK
- 10.2307/2033241 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1029

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1029, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1184933221101953025) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1030
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01721](https://doi.org/10.21105/joss.01721)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01721/status.svg)](https://doi.org/10.21105/joss.01721)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01721">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01721/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01721/status.svg
   :target: https://doi.org/10.21105/joss.01721
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01721/status.svg)](https://doi.org/10.21105/joss.01721)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by Kevin-Mattheus-Moerman** [comment]
Congratulations @knaidoo29 
Thanks @melissawm and @zonca for reviewing this work!!! :tada: 
Thank you @xuanxu for editing this.

**Comment by knaidoo29** [comment]
Hi @Kevin-Mattheus-Moerman just noticed that the footnote starts with `Naidoo, (3030).` shouldn't this be `Naidoo, (2019).` or `Naidoo, K. (2019).`?

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev :point_up: is this fixable
