### ISSUE TITLE
[REVIEW]: BayesPostEst: An R Package to Generate Postestimation Quantities for Bayesian MCMC Estimation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1722]
**Submitting author:** @jkarreth (<a href="http://orcid.org/0000-0003-4586-7153">Johannes Karreth</a>)
**Repository:** <a href="https://github.com/ShanaScogin/BayesPostEst" target ="_blank">https://github.com/ShanaScogin/BayesPostEst</a>
**Version:** v0.1.0
**Editor:** @terrytangyuan
**Reviewer:** @svmiller, @TiagoVentura
**Archive:** <a href="https://doi.org/10.5281/zenodo.3464224" target="_blank">10.5281/zenodo.3464224</a>

## Status

[![status](https://joss.theoj.org/papers/5748d7907454f341b547df4d278df219/status.svg)](https://joss.theoj.org/papers/5748d7907454f341b547df4d278df219)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5748d7907454f341b547df4d278df219"><img src="https://joss.theoj.org/papers/5748d7907454f341b547df4d278df219/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5748d7907454f341b547df4d278df219/status.svg)](https://joss.theoj.org/papers/5748d7907454f341b547df4d278df219)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ShanaScogin/BayesPostEst/tree/master" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@svmiller & @TiagoVentura, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @terrytangyuan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ShanaScogin/BayesPostEst/tree/master">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jkarreth) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ShanaScogin/BayesPostEst/tree/master">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jkarreth) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @svmiller, @TiagoVentura it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1722 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1722 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by terrytangyuan** [comment]
@openjournals/joss-eics Any idea on how to fix the compilation error?

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1722 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1722 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01722/joss.01722/10.21105.joss.01722.pdf)

**Comment by terrytangyuan** [comment]
Thank you!

**Comment by jkarreth** [comment]
Thank you @labarba for the quick diagnosis & fix, and I apologize getting this wrong in the submission!

**Comment by svmiller** [comment]
I'll caution here that I am kind of clumsy on Github, and this is the first review of its kind I've done, but I believe I've completed my review for this paper. I obviously recommend publication (which is the language I'm used to using for social science papers) and I should've checked all boxes in my review toward that end.

**Comment by TiagoVentura** [comment]
I checked all the boxes as well. The paper and the package are great, strongly recommend the publication. I just found on issue, that I append to this code. The function 'mcmcRocPrc' does not work as suggested in the Readme. I am providing an example here: 
`rm(list=ls(all=TRUE))
library("remotes")
install_github("ShanaScogin/BayesPostEst")

df <- carData::Cowles

df$female <- (as.numeric(df$sex) - 2) * (-1)
df$volunteer <- as.numeric(df$volunteer) - 1
df$extraversion <- (df$extraversion - mean(df$extraversion)) / (2 * sd(df$extraversion))
df$neuroticism <- (df$neuroticism - mean(df$neuroticism)) / (2 * sd(df$neuroticism))

dl <- as.list(df[, c("volunteer", "female", "neuroticism", "extraversion")])
dl$N <- nrow(df)

mod.jags <- paste("	
model {
for (i in 1:N){
  volunteer[i] ~ dbern(p[i])  
  logit(p[i]) <- mu[i]   
  mu[i] <- b[1] + b[2] * female[i] + b[3] * neuroticism[i] + b[4] * extraversion[i]
  }

for(j in 1:4){
  b[j] ~ dnorm(0, 0.1)
  }

}
")
writeLines(mod.jags, "mod.jags")

params.jags <- c("b")
inits1.jags <- list("b" = rep(0, 4))
inits.jags <- list(inits1.jags, inits1.jags, inits1.jags, inits1.jags)

library("R2jags")
set.seed(123)

fit.jags <- jags(data = dl, inits = inits.jags, 
                 parameters.to.save = params.jags, n.chains = 4, n.iter = 2000, 
                 n.burnin = 1000, model.file = "mod.jags")

mcmcmat.jags <- as.matrix(coda::as.mcmc(fit.jags))

mf <- model.frame(volunteer ~ female + neuroticism + extraversion, data = df)

fitstats <- mcmcRocPrc(modelmatrix = mm,
                       modelframe = mf,
                       mcmcout = mcmcmat.jags[, 1:ncol(mm)],
                       curves = TRUE,
                       link = "logit",
                       fullsims = FALSE)`

The error: 

> Error in mcmcRocPrc(modelmatrix = mm, modelframe = mf, mcmcout = mcmcmat.jags[,  : 
  unused arguments (modelmatrix = mm, modelframe = mf, mcmcout = mcmcmat.jags[, 1:ncol(mm)], link = "logit")

Let me know if it is something in my end.

**Comment by terrytangyuan** [comment]
@jkarreth Could you take a look at the above issue pointed out?

**Comment by jkarreth** [comment]
@TiagoVentura Thank you for pointing this out! The function is ahead of the Readme and vignette here, so I need to adjust the code in these documents. I'll update both documents and will post here again when that is done.

**Comment by TiagoVentura** [comment]
Yes! That was my intuition of what was happening @jkarreth . Thanks!

**Comment by jkarreth** [comment]
@TiagoVentura Thank you again for finding this issue! I updated the Readme to reflect the new arguments to `mcmcRocPrc`. The vignette should already be correct. Would you mind taking a quick look at the new code and see if you can reproduce it? The relevant part is:

```
fitstats <- mcmcRocPrc(object = fit.jags,
                       yname  = "volunteer",
                       xnames = c("female", "neuroticism", "extraversion"),
                       curves = TRUE,
                       fullsims = FALSE)
```

**Comment by TiagoVentura** [comment]
All good here. No more issues with the code. Thank you for the opportunity to review the paper, Looking forward to using the package!

**Comment by jkarreth** [comment]
Wonderful! Thank you very much @TiagoVentura and @svmiller for your time and efforts.

@terrytangyuan, I just made a small update to the paper.md (added explicit description of author contributions and changed an author affiliation). Is there anything else I should be doing now?

**Comment by terrytangyuan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01722/joss.01722/10.21105.joss.01722.pdf)

**Comment by jkarreth** [comment]
I just fixed a formatting issue in the paper and am recompiling - hope that's OK!

**Comment by jkarreth** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01722/joss.01722/10.21105.joss.01722.pdf)

**Comment by terrytangyuan** [comment]
Thanks everyone! 

@jkarreth At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

The title of the archive is the same as the JOSS paper title
That the authors of the archive are the same as the JOSS paper authors
I can then move forward with accepting the submission.

**Comment by ShanaScogin** [comment]
@terrytangyuan Here is the Zenodo doi associated with this release: http://doi.org/10.5281/zenodo.3464071 

How's that look? Do you need anything else from me? Everything should be up to date with was was linked here. (Also, thank you again everyone for the time and feedback!!!)

**Comment by terrytangyuan** [comment]
@whedon set v0.1.0 as version

**Comment by whedon** [comment]
OK. v0.1.0 is the version.

**Comment by terrytangyuan** [comment]
@whedon set 10.5281/zenodo.3464224  as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3464224" target="_blank">10.5281/zenodo.3464224</a> is the archive.

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.21105/joss.01541 is OK
- 10.18637/jss.v080.i01 is OK
- 10.18637/jss.v070.i09 is OK
- 10.1002/sim.3107 is OK
- 10.5281/zenodo.1308157 is OK
- 10.5281/zenodo.1284472 is OK
- 10.5281/zenodo.1308151 is OK
- 10.1177/2515245918771304 is OK
- 10.1111/j.2044-8309.1987.tb00769.x is OK
- 10.1111/j.1540-5907.2012.00602.x is OK
- 10.1080/03050629.2018.1389728 is OK
- 10.1037/a0029146 is OK

MISSING DOIs

- https://doi.org/10.3886/icpsr01255 may be missing for title: Making the Most of Statistical Analyses: Improving Interpretation and Presentation

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/988

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/988, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by terrytangyuan** [comment]
@ShanaScogin @jkarreth Could you fix the above missing DOI?

**Comment by jkarreth** [comment]
@terrytangyuan done, this is now added to paper.bib

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.21105/joss.01541 is OK
- 10.18637/jss.v080.i01 is OK
- 10.18637/jss.v070.i09 is OK
- 10.1002/sim.3107 is OK
- 10.5281/zenodo.1308157 is OK
- 10.5281/zenodo.1284472 is OK
- 10.5281/zenodo.1308151 is OK
- 10.1177/2515245918771304 is OK
- 10.1111/j.2044-8309.1987.tb00769.x is OK
- 10.1111/j.1540-5907.2012.00602.x is OK
- 10.1080/03050629.2018.1389728 is OK
- 10.1037/a0029146 is OK

MISSING DOIs

- https://doi.org/10.3886/icpsr01255 may be missing for title: Making the Most of Statistical Analyses: Improving Interpretation and Presentation

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/989

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/989, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by terrytangyuan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.21105/joss.01541 is OK
- 10.18637/jss.v080.i01 is OK
- 10.18637/jss.v070.i09 is OK
- 10.1002/sim.3107 is OK
- 10.5281/zenodo.1308157 is OK
- 10.5281/zenodo.1284472 is OK
- 10.5281/zenodo.1308151 is OK
- 10.1177/2515245918771304 is OK
- 10.1111/j.2044-8309.1987.tb00769.x is OK
- 10.1111/j.1540-5907.2012.00602.x is OK
- 10.1080/03050629.2018.1389728 is OK
- 10.1037/a0029146 is OK

MISSING DOIs

- https://doi.org/10.3886/icpsr01255 may be missing for title: Making the Most of Statistical Analyses: Improving Interpretation and Presentation

INVALID DOIs

- None
```

**Comment by jkarreth** [comment]
I'm not sure why this keeps happening, but if it's OK with you, @terrytangyuan, that DOI is not essential. It's attached to the replication data for the article we cite (and the article itself doesn't have a DOI since it's from 2000), so the citation should still be correct even without DOI.

**Comment by kyleniemeyer** [comment]
Whedon's DOI warnings are only meant to be warnings, so if you checked on one manually and it doesn't look like an actual issue, we can ignore

**Comment by terrytangyuan** [comment]
Thanks @kyleniemeyer. Since you are already here, could you take it from here? The paper looks good to me.

**Comment by kyleniemeyer** [comment]
Hi @jkarreth, 

We're nearly done, just a few typos/fixes for the paper:
- in your author list, some of the affiliations are missing states
- in your code snippet on page 2, some of the commented text is cut off; I would suggest rearranging and moving stuff to new (shorter) lines
- on page 5, "or observed 1s" seems to be a typo (or is otherwise not clear); should "1s" be "ones"?
- add commas after "e.g" throughout the document: "e.g." -> "e.g.,"
- in the Beger reference, the URL given should be removed and converted to a DOI (stripping out the "http://dx.doi.org/")
- in multiple references, words in titles need `{}` to protect capitalization ("Monte Carlo", "R", etc.)

**Comment by jkarreth** [comment]
Thank you for the close read and for finding these issues, @kyleniemeyer ! These should now all be fixed in https://github.com/ShanaScogin/BayesPostEst/tree/master/JOSSpaper:

- [x] in your author list, some of the affiliations are missing states
- [x] in your code snippet on page 2, some of the commented text is cut off; I would suggest rearranging and moving stuff to new (shorter) lines
- [x] on page 5, "or observed 1s" seems to be a typo (or is otherwise not clear); should "1s" be "ones"?
- [x] add commas after "e.g" throughout the document: "e.g." -> "e.g.,"
- [x] in the Beger reference, the URL given should be removed and converted to a DOI (stripping out the "http://dx.doi.org/")
- [x] in multiple references, words in titles need {} to protect capitalization ("Monte Carlo", "R", etc.)

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01722/joss.01722/10.21105.joss.01722.pdf)

**Comment by jkarreth** [comment]
Not sure how, but some of the references were lost in the latest .bib file. I just re-inserted them. Sorry about that!

**Comment by jkarreth** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01722/joss.01722/10.21105.joss.01722.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.21105/joss.01541 is OK
- 10.18637/jss.v080.i01 is OK
- 10.18637/jss.v070.i09 is OK
- 10.1002/sim.3107 is OK
- 10.5281/zenodo.1308157 is OK
- 10.5281/zenodo.1284472 is OK
- 10.5281/zenodo.1308151 is OK
- 10.1177/2515245918771304 is OK
- 10.2139/ssrn.2765419 is OK
- 10.1111/j.2044-8309.1987.tb00769.x is OK
- 10.1111/j.1540-5907.2012.00602.x is OK
- 10.1080/03050629.2018.1389728 is OK
- 10.1037/a0029146 is OK

MISSING DOIs

- https://doi.org/10.3886/icpsr01255 may be missing for title: Making the Most of Statistical Analyses: Improving Interpretation and Presentation

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/998

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/998, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1179085380873834509) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/999
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01722](https://doi.org/10.21105/joss.01722)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @jkarreth on your article's publication in JOSS!

Many thanks to @terrytangyuan for editing, and @svmiller & @TiagoVentura for reviewing, this submission.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01722/status.svg)](https://doi.org/10.21105/joss.01722)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01722">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01722/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01722/status.svg
   :target: https://doi.org/10.21105/joss.01722
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01722/status.svg)](https://doi.org/10.21105/joss.01722)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by terrytangyuan** [comment]
@whedon set 1.1.0 as version

**Comment by whedon** [comment]
OK. 1.1.0 is the version.

**Comment by jkarreth** [comment]
Thank you very much @svmiller and @TiagoVentura for your reviews, and @terrytangyuan and @kyleniemeyer for editing! I really appreciate it.
