### ISSUE TITLE
[PRE REVIEW]: Bedtoolsr: An R package for genomic data analysis and manipulation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1723]
**Submitting author:** @dphansti (<a href="http://orcid.org/0000-0003-2123-0051">Douglas Phanstiel</a>)
**Repository:** <a href="https://github.com/PhanstielLab/bedtoolsr.git" target ="_blank">https://github.com/PhanstielLab/bedtoolsr.git</a>
**Version:** v2.29.0
**Editor:** @mgymrek
**Reviewers:** @nhejazi , @mikmaksi 

**Author instructions**

Thanks for submitting your paper to JOSS @dphansti. The JOSS editor @mgymrek, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dphansti if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mgymrek it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@mgymrek) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01723/joss.01723/10.21105.joss.01723.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@dphansti thanks for submitting this work. 

Before we can consider your work for JOSS you need to address the following points: 
- [ ]  JOSS submission require an [OSI approved license](https://opensource.org/licenses). Please choose one and add a LICENSE file to your main folder. 
- [ ]  Have a look at our paper [formatting guidelines](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). Your paper looks like the classic Intro/methods/results/discussion format, at JOSS we have a different format and do not require these sections. Please study the guidelines and reformat your paper accordingly (you can leave the acknowledgements section). 
- [ ] Please remove the Source/Information/Contact links from the paper. Such links are added to the paper by default so do not need to appear in the text. 
- [ ] Please ensure all references with DOI's have them listed as well

I may have more points once I give your paper a more thorough read, but these are the points for the moment. Let me know if you have questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.32614/rj-2011-002 may be missing for title: testthat: Get Started with Testing
- https://doi.org/10.1038/517109a may be missing for title: Programming tools: Adventures with R
- https://doi.org/10.12688/f1000research.11997.1 may be missing for title: valr: Reproducible genome interval analysis in R
- https://doi.org/10.1093/bioinformatics/btq033 may be missing for title: BEDTools: a flexible suite of utilities for comparing genomic features
- https://doi.org/10.1371/journal.pcbi.1003118 may be missing for title: Software for computing and annotating genomic ranges
- https://doi.org/10.1093/bioinformatics/btr539 may be missing for title: Pybedtools: a flexible Python library for manipulating genomic datasets and annotations

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@mgymrek, @brainstorm, @karthik, @csoneson 
Could one of you serve as editor for this submission or suggest reviewers? 
@mgymrek you are assigned for now, please confirm if you can handle this submission. 
Thanks

**Comment by mgymrek** [comment]
@nhejazi @ajank @road2stat @mikmaksi would either of you be willing to review this submission?

**Comment by nhejazi** [comment]
Happy to review / co-review this package.

**Comment by mikmaksi** [comment]
Happy to review / co-review as well

**Comment by mgymrek** [comment]
@whedon assign @nhejazi  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nhejazi

**Comment by mgymrek** [comment]
@whedon add @mikmaksi  as reviewer

**Comment by whedon** [comment]
OK, @mikmaksi  is now a reviewer

**Comment by mgymrek** [comment]
Thanks @mikmaksi and @nhejazi! I will now start a review thread, where you can complete the review.

**Comment by mgymrek** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1742. Feel free to close this issue now!
