### ISSUE TITLE
[PRE REVIEW]: AliasFinder: A Python script to search for the true planetary frequency within radial velocity data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1724]
**Submitting author:** @StephanStock (<a href="http://orcid.org/0000-0002-1166-9338">Stephan Stock</a>)
**Repository:** <a href="https://github.com/JonasKemmer/AliasFinder" target ="_blank">https://github.com/JonasKemmer/AliasFinder</a>
**Version:** v1.0.0
**Editor:** @xuanxu
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @StephanStock. The JOSS editor @xuanxu, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@StephanStock if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @xuanxu it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@xuanxu) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1724 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:143:in `block in check_orcids': Problem with ORCID (0000-0000-0000-0000) for Jonas Kemmer (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:141:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:141:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:88:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon, does the paper need to be moved to a different location? Also that does not look like a real ORCID id.

**Comment by Kevin-Mattheus-Moerman** [comment]
@xuanxu can you help edit this one (I assigned you for now)? Alternatively, @mbobra could you edit this one? Could either of you also help suggest reviewers? Thanks

**Comment by xuanxu** [comment]
@Kevin-Mattheus-Moerman, yeah, I can edit this one.

**Comment by xuanxu** [comment]
@StephanStock please merge this PR: JonasKemmer/AliasFinder#1. It should fix the paper compilation error.

**Comment by StephanStock** [comment]
@xuanxu the pull request was merged by @JonasKemmer. As a potential reviewer we suggest @nespinoza

**Comment by arfon** [comment]
@xuanxu - `@nespinoza` has recently just finished a review. Perhaps we can find someone who hasn't reviewed for JOSS so recently?

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01724/joss.01724/10.21105.joss.01724.pdf)

**Comment by StephanStock** [comment]
Should we update our Orc-IDs in our Draft so that they represent our real Orc-IDs?

**Comment by StephanStock** [comment]
@xuanxu We did a new push with the corrected orcids of me and @JonasKemmer.

**Comment by xuanxu** [comment]
@StephanStock: great, thanks! I'll look for reviewers and start the review issue as soon as possible.

**Comment by StephanStock** [comment]
@xuanxu thanks for your patience

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01724/joss.01724/10.21105.joss.01724.pdf)

**Comment by xuanxu** [comment]
@Juanlu001: Thanks for flagging this.

**Comment by xuanxu** [comment]
Hi @JonasKemmer, 

After a pre-review of your submission, and an assessment by the editorial board at large, we find that this submission does not quite meet our submission requirements. In particular, while the code seems useful, as currently written this is a script for particular data analysis task, but it falls foul of the not being software 'designed for maintainable extension', and we therefore decided not to put it through review.

Thank you for considering JOSS as a venue for your software.
