### ISSUE TITLE
[REVIEW]: pypulseq: A Python Package for MRI Pulse Sequence Design 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1725]
**Submitting author:** @imr-framework (<a href="http://orcid.org/0000-0002-3776-4114">Sairam Geethanath</a>)
**Repository:** <a href="https://github.com/imr-framework/pypulseq" target ="_blank">https://github.com/imr-framework/pypulseq</a>
**Version:** 1.2.2r1
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @grlee77, @mathieuboudreau, @spinicist
**Archive:** <a href="https://doi.org/10.5281/zenodo.3479527" target="_blank">10.5281/zenodo.3479527</a>

## Status

[![status](https://joss.theoj.org/papers/fe83dd500d56a5f45db80def6ca6ed63/status.svg)](https://joss.theoj.org/papers/fe83dd500d56a5f45db80def6ca6ed63)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fe83dd500d56a5f45db80def6ca6ed63"><img src="https://joss.theoj.org/papers/fe83dd500d56a5f45db80def6ca6ed63/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fe83dd500d56a5f45db80def6ca6ed63/status.svg)](https://joss.theoj.org/papers/fe83dd500d56a5f45db80def6ca6ed63)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/imr-framework/pypulseq" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@grlee77, @mathieuboudreau, and @spinicist, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/imr-framework/pypulseq">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@imr-framework) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/imr-framework/pypulseq">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@imr-framework) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/imr-framework/pypulseq">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@imr-framework) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @grlee77, @mathieuboudreau it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01725/joss.01725/10.21105.joss.01725.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@imr-framework, @grlee77, @mathieuboudreau this is where the review takes place. The reviewers each have a set of tick boxes at the top of this issue to guide them through the process. Let me know if you have any questions. Let the reviewing begin!

**Comment by grlee77** [comment]
I have performed my initial review.

**Summary**

The Pypulseq software is a port of the Pulseq Matlab package to Python. This makes the Pulseq format for rapid sequence prototyping more readily available to sites without need for a commercial license. The authors also have used Python-based machine learning in combination with Pypulseq for novel sequence design. The overall goal is to have a tool for rapid sequence development without relying on complicated and proprietary vendor-specific pulse sequence development tools. The advantage of such an approach is greatly reduced development time for simple experiments and rapid prototyping.

I verified that Pulseq files are produced by running the examples. The generated files are plain text and appear to conform to the Pulseq specification. I currently work with Philips MR systems, which is not one of the supported vendors, so I did not attempt to verify proper execution of the Pulseq files on a physical MRI scanner.

The software appears to work as advertised. Its main weakness in relation to the JOSS criteria is the lack of automated testing and/or continuous integration to test across platforms. I opened imr-framework/pypulseq#16 regarding this.


**Comments regarding the text of the paper**

1.) A brief statement on the limitations of the types of sequences that can be designed with this simplified approach is warranted so as not to oversell the capabilities. For example, it seems that scans requiring features such as cardiac or respiratory gating, feedback from real-time image-based navigators, etc. are not going to be possible. I assume that it also presents difficulty for scans that require more complicated planning such as placement of saturation slabs and or localized shim boxes interactively prior to scan start.

2.) Similarly, is offline image reconstruction (i.e. not with the vendor-supplied reconstructor) always required when using this tool?

3.) I would add a reference to J. Nielsen's TOPPE publication as a closely related work (https://doi.org/10.1002/mrm.26990). (It seems that on the GE platform a Pulseq->TOPPE conversion is done to actually play out the sequences on the scanner?).

4.) For the puposes of the "state of the field" JOSS criteria, it should probably also be mentioned how this framework (and TOPPE) are fast and do not require compilation (as compared to C++ frameworks like ODIN or SequenceTree).

5.) Are there any areas that pypulseq currently offers additional functionality (or lacks functionality) relative to the Matlab implementation? This would be good to know for existing Matlab users thinking of making the switch to Python.

**Minor typos/suggested phrasing changes**

    1.) in the summary:
    "easy integrability with" -> "easy integration with"

    2.) under the "Statement of Need"
    "These are aimed at achieving" <- unclear what "these" is referring to

    3.) in the section on the Pulseq format:

    "A pulse sequence comprises of pulsed, magnetic field gradient, delay or ADC readout events" ->

    "A pulse sequence comprises of radiofrequency pulses, magnetic field gradient waveforms, delays or analog-to-digital converter (ADC) readout events"

    4.) Please include the meeting names (International Society for Magnetic Resonance in Medicine?) for the fourth reference and last reference.

**Comment by sravan953** [comment]
@grlee77 Thank you for your comments, will work on them and revert. Have a nice weekend!

**Comment by sravan953** [comment]
@grlee77 I have address your comments in the most recent commit. Please take a look!

More specifically regarding #5 in your comments: our future efforts involve incorporating SAR computation and real-time pulse sequence design.

**Comment by mathieuboudreau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01725/joss.01725/10.21105.joss.01725.pdf)

**Comment by mathieuboudreau** [comment]
>Contribution and authorship: Has the submitting author (@imr-framework) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

@imr-framework could you clarify what contribution(s) John Thomas Vaughan Jr. made to this project; I checked out the contributors to the source code  [here](https://github.com/imr-framework/pypulseq/graphs/contributors), and he doesn't appear on the list (whereas @tonggehua has made some commits and doesn't appear on the paper).

**Comment by mathieuboudreau** [comment]
@imr-framework does there exist some kind of validator tool to evaluate if a generated *.seq file is (1) properly formatted, and (2) doesn't exceed vendor-imposed hardware limits. I don't expect that this exists within your software, since *.seq files have been developed previously, I'm wondering if there's an external tool that already does this?

**Comment by sravan953** [comment]
@mathieuboudreau 
Regarding contributions-
John Thomas Vaughan Jr. has been principally involved in the design and review of this project, like for [Virtual Scanner](https://github.com/imr-framework/virtual-scanner/issues/22#issuecomment-520032559). We have been using PyPulseq internally, and the one commit from @tonggehua was regarding [documentation](https://github.com/imr-framework/pypulseq/commit/5cdf7a0802b764691cf1e5b7a6ae707edcb9a796). The authors list was finalised after internal deliberations.

Regarding the formatting-
We utilised a diffcheck tool to ensure that the *.seq files generated by PyPulseq match with Pulseq 1.2.0's files. We performed these checks for the demo scripts that have been bundled. The only difference between *.seq files generated by PyPulseq and Pulseq 1.2.0 is the comment on line 2 in every *.seq file which indicates which tool generated the file.

Regarding an external validator tool-
The `check_timing()` and `test_report()` methods can be leveraged to ensure that the designed pulse sequence is in accordance with the specified gradient raster time limits. Subsequently, a successfully generated *.seq file might or might not play on the scanner, depending on whether the hardware limits were violated or not.

**Comment by mathieuboudreau** [comment]
Ok great, thanks for all that additional information!

**Comment by grlee77** [comment]
> @grlee77 I have addressed your comments in the most recent commit. Please take a look!

Thanks, I have checked off the items related above that were addressed.

Regarding functionality, I had not checked the box because I did not verify on an actual scanner, but given that the Pulseq files look correctly formatted and the author has performed an offline comparison vs. the same demos in the Matlab package, I would trust that they work equivalently on actual hardware.

Re Automated testing: This has not been implemented, but the author has indicated future plans to do so in imr-framework/pypulseq#16. It is currently possible for users to manually test the basic functionality of the software by running the supplied examples.

**Comment by spinicist** [comment]
Hello,

I've gone through the review checklist.

The example in README.md does not appear to work. There is a typo - `slew_unit='mT/m/s'` should be `slew_unit='T/m/s'`, but after fixing that there is a division by zero error in `make_sinc_pulse`. The example EPI sequence works fine, as does the GRE sequence but it is very slow to plot.

Similarly to the other authors I did not go as far as testing the sequences on an actual scanner, as (for me) that would involve installation of TOPPE which would take considerable time and I consider beyond the scope of this review. On the same lines, I question the ultimate usefulness of tools such as PyPulseq and TOPPE because of their lack of interaction with vendor UI and safety limits (as mentioned by other reviewers). For instance all GE vendor sequences include extensive software SAR checks, which are not included in PyPulseq/TOPPE. I hence foresee conflicts with local safety and ethics policies if researchers want to use such sequences for scanning subjects.

I do not think the above is reason to reject this paper as PyPulseq itself is clearly useful for prototyping, and I have ticked the Functionality box because I think the functions that Py Pulseq claims to have, have been demonstrated. I only raise it because I think the realistic use-cases are fairly limited, and hence I think the claim "We also envisage PyPulseq to be utilized for repeatability and reproducibility studies ... (multi-site, multi-vendor)" is slightly strong.

**Comment by sravan953** [comment]
@spinicist Thanks for your comments, have made changes to the README based on your inputs.

Regarding conflicts with local safety and ethics policies-
We will soon incorporate SAR safety features into PyPulseq. @sairamgeethanath has a MATLAB version available at - https://github.com/imr-framework/sar4seq, which will soon get integrated into PyPulseq. We advocate leveraging PyPulseq as an open-source tool for prototyping pulse sequences, and do not advise subject scanning ([1](https://onlinelibrary.wiley.com/doi/abs/10.1002/mrm.26235), [2](https://www.sciencedirect.com/science/article/pii/S0730725X1830033X)). 

For repeatability and reproducibility-
[OMEGA](https://github.com/imr-framework/mrf) by @qianenlin focuses on the repeatability of MRF using NIST phantom ([Jiang et al., MRM 2014](https://onlinelibrary.wiley.com/doi/abs/10.1002/mrm.26509)). A MATLAB version exists as reported in [Qian et al., ISMRM 2019](https://index.mirasmart.com/ISMRM2019/PDFfiles/0817.html). We are now looking at developing a PyPulseq version. 

The [AMRI](https://github.com/imr-framework/amri/tree/amri) project leverages PyPulseq. Video recordings demonstrating PyPulseq’s functionality from AMRI are available on [YouTube](https://www.youtube.com/watch?v=F5cQZWIHnQU&t=45s).

**Comment by sairamgeethanath** [comment]
@sravan953 @spinicist The [AMRI phantom](https://www.youtube.com/watch?v=ZToRLwXQW1A) video illustrates the point better about using different acquisition parameters to generate different *.seq* files using pyPulseq and using them to scan phantoms, for example.

**Comment by sravan953** [comment]
@mathieuboudreau @grlee77 @spinicist We also have AMRI-Scanner as an Online Service (AMRI-SOS). AMRI-SOS lets you upload a sequence file to Google Drive and request a scan. On our end, we run an AMRI-SOS script that downloads the uploaded *.seq file and runs it on a Siemens Prisma 3T. This way we can prove functionality. Thanks @sairamgeethanath for the idea!

**Comment by sairamgeethanath** [comment]
@mathieuboudreau @grlee77 @spinicist Could you please let us know of action points to take this review forward?

**Comment by sairamgeethanath** [comment]
> @mathieuboudreau @grlee77 @spinicist We also have AMRI-Scanner as an Online Service (AMRI-SOS). AMRI-SOS lets you upload a sequence file to Google Drive and request a scan. On our end, we run an AMRI-SOS script that downloads the uploaded *.seq file and runs it on a Siemens Prisma 3T. This way we can prove functionality. Thanks @sairamgeethanath for the idea!

https://docs.google.com/forms/d/e/1FAIpQLSf3MIC6bcOpV20-yYrqmO_OhK4wNgsKZu3oBqRYe4CLbzIT8A/viewform?fbzx=3238199011716171808

**Comment by spinicist** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by spinicist** [comment]
I think my points have been sufficiently addressed. I have no further comments.

I'm not actually sure how to mark my review as complete?

**Comment by Kevin-Mattheus-Moerman** [comment]
@spinicist thanks for your help! :tada:

**Comment by grlee77** [comment]
I have checked off the remaining items as well and do not have any other remaining unaddressed comments.

Thanks for provided the additional AMRI info, @sravan953.

**Comment by mathieuboudreau** [comment]
I did the same earlier today - looks complete on my end !

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for your help @grlee77, @mathieuboudreau, @spinicist !!! :tada: :robot:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01725/joss.01725/10.21105.joss.01725.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1002/mrm.26235 may be missing for title: Pulseq: a rapid and hardware-independent pulse sequence prototyping framework
- https://doi.org/10.1016/j.mri.2018.03.008 may be missing for title: Pulseq-Graphical Programming Interface: Open source visual environment for prototyping pulse sequences and integrated magnetic resonance imaging algorithm development
- https://doi.org/10.1016/j.jmr.2004.05.021 may be missing for title: ODIN—object-oriented development interface for NMR
- https://doi.org/10.1002/mrm.25640 may be missing for title: Pulse sequence programming in a dynamic visual environment: SequenceTree
- https://doi.org/10.1002/mrm.26990 may be missing for title: TOPPE: A framework for rapid prototyping of MR pulse sequences

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@imr-framework here are some additional issues/comments in relation to your paper. Please make these required changes: 

- [ ] Check that you've added all possible DOI's to your references
- [ ] The hyper links `[TOPPE](toppe)`, `[Bruker](bruker)`,  `[PyPulseq-gpi](pypulseq-gpi-branch)`, and `[GPI](gpilab)` do not link to valid web content. Can you remove these links or fix them with proper URLs?
- [ ] You mention `We have leveraged this tool for several published research works`. Adding some key citations to those works here would be appropriate. 
- [ ] The statement of need section defines the acronym MRI again (`Magnetic Resonance Imaging (MRI)`), since it is already defined in the preceding section please simply use it here instead. 
- [ ] Since MR is not defined (I know it stands for Magnetic Resonance but still) I suggest you use MRI throughout instead. Or also define MR.
- [ ] In `Further, harmonizing acquisition across...` please replace `Further` with `Furthermore`. 
- [ ] Remove the `-` from `open-source` throughout
- [ ] I suggest adding a comma after Python in `...platforms in Python based on the Pulseq standard...`
- [ ] Please rephrase `The file format was designed keeping in mind design goals such as: human-readable, easily parsable, vendor independent, compact and low-level (Layton et al., 2017).`, to something like: `The file format was designed with the following design criteria in mind: human-readable, easily parsable, vendor independent, compact and low-level (Layton et al., 2017).`
- [ ] Please consider rephrasing: `It enables researchers and users to program pulse sequences in Python and export as a .seq file.` to: `It enables researchers and users to program pulse sequences in Python, and to export them as a .seq file.`
- [ ] the `About PyPulseq`section contains several sentences starting with `First,..`, `Second,...`, and `Third...`. Please change thes to `Firstly,...`, `Secondly,...`, and `Thirdly,...`. 
- [ ] In "`This allows PyPulseq to be integrated`...", It is unclear what `this` refers to? Please clarify. Perhaps saying `These advantages allow...` (if I understood this correctly) fixes the issue. 
- [ ] Please rephrase and remove the use of etc in "`...and related downstream reconstruction,
etc.`".
- [ ] Please add the and in the following sentence "`PyPulseq is aimed at MRI researchers focusing on pulse sequence design, image reconstruc-tion, [and] MR physics.`"
- [ ] Once all changes are implemented I'll recommend that your paper is accepted. At this point I ask you to double check the text yourself, in particular check that author list, the affiliations and also the acknowledgement section is accurate.

**Comment by sravan953** [comment]
@Kevin-Mattheus-Moerman Thanks for the comments! I believe I have addressed your inputs, and have pushed my commit. Please let me know.

**Comment by sravan953** [comment]
@Kevin-Mattheus-Moerman Thanks for the comments! I believe I have addressed your inputs, and have pushed my commit - 985516b7bd3b3905911a8fa826a98f79ef11aa9b. Please let me know.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01725/joss.01725/10.21105.joss.01725.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/mrm.26235 is OK
- 10.1016/j.mri.2018.03.008 is OK
- 10.1016/j.jmr.2004.05.021 is OK
- 10.1002/mrm.25640 is OK
- 10.1002/mrm.26990 is OK
- 10.1615/CritRevBiomedEng.2019029380 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@sravan953 thanks. One point is remaining, in the sentence containing"`...and export them a .seq file.`", you forgot to add either `to` or `as` i.e. use "`...and export them [to] a .seq file.`" or "`...and export them [as] a .seq file.`"

**Comment by Kevin-Mattheus-Moerman** [comment]
@sravan953, once you've made the above change, can you run `@whedon generate pdf` here? Also can you do the following: 

- [ ] Please archive the reviewed software on Zenodo and report the DOI here in this review thread. Make sure the Zenodo deposit has the correct metadata (same title and author list as the paper). 
- [ ] Can you confirm that the version of the reviewed (and archived) software is `1.2.2, or has the version tag moved on? Please provide the latest version tag for the reviewed software.

**Comment by sravan953** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by sravan953** [comment]
> @sravan953 thanks. One point is remaining, in the sentence containing"`...and export them a .seq file.`", you forgot to add either `to` or `as` i.e. use "`...and export them [to] a .seq file.`" or "`...and export them [as] a .seq file.`"

Apologies for overlooking this, this has been fixed.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01725/joss.01725/10.21105.joss.01725.pdf)

**Comment by sravan953** [comment]
> @sravan953, once you've made the above change, can you run `@whedon generate pdf` here? Also can you do the following:
> 
> * [ ]  Please archive the reviewed software on Zenodo and report the DOI here in this review thread. Make sure the Zenodo deposit has the correct metadata (same title and author list as the paper).
> * [ ]  Can you confirm that the version of the reviewed (and archived) software is `1.2.2`, or has the version tag moved on? Please provide the latest version tag for the reviewed software.

@Kevin-Mattheus-Moerman Oops, I now follow what you were saying. There have been some minor fixes since version 1.2.2. was submitted to JOSS for review. Would you recommend publishing a new release with the latest commit?

**Comment by sravan953** [comment]
@Kevin-Mattheus-Moerman -
1. DOI - 10.5281/zenodo.3479527
2. Latest release - 1.2.2r1 (published on Zenodo)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 1.2.2r1 as version

**Comment by whedon** [comment]
OK. 1.2.2r1 is the version.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 10.5281/zenodo.3479527 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3479527" target="_blank">10.5281/zenodo.3479527</a> is the archive.

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/joss-eics I recommend this paper for acceptance in JOSS. 

@sravan953 the editor in chief on call will take over now. They might have additional comments on your paper.

**Comment by Kevin-Mattheus-Moerman** [comment]
@sravan953 one last point from me. I would recommend that you update your paper title (and also the matched Zenodo archive title) to be a bit more descriptive, e.g.:
**PyPulseq: A Python Package for MRI Pulse Sequence Design**
Something like that would help make your paper more discoverable.

**Comment by arfon** [comment]
> @arfon is this something that we can change just in the PDF or do we need to propagate the title change anywhere else?

Just the `paper.md` should do it.

**Comment by sravan953** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01725/joss.01725/10.21105.joss.01725.pdf)

**Comment by sravan953** [comment]
@Kevin-Mattheus-Moerman @arfon Updated the title on the `README.md`, Zenodo archive and on `paper.md`.

**Comment by labarba** [comment]
I fixed in-text citation syntax and a terminology issue in https://github.com/imr-framework/pypulseq/pull/23

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/mrm.26235 is OK
- 10.1016/j.mri.2018.03.008 is OK
- 10.1016/j.jmr.2004.05.021 is OK
- 10.1002/mrm.25640 is OK
- 10.1002/mrm.26990 is OK
- 10.1615/CritRevBiomedEng.2019029380 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1023

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1023, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1182838451936342016) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1024
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01725](https://doi.org/10.21105/joss.01725)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @imr-framework, your JOSS paper is published! 🚀 

Huge thanks to our editor: @Kevin-Mattheus-Moerman, and the reviewers: @grlee77, @mathieuboudreau, @spinicist — your contributions to JOSS are greatly appreciated 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01725/status.svg)](https://doi.org/10.21105/joss.01725)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01725">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01725/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01725/status.svg
   :target: https://doi.org/10.21105/joss.01725
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01725/status.svg)](https://doi.org/10.21105/joss.01725)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by sairamgeethanath** [comment]
> Congratulations, @imr-framework, your JOSS paper is published! 🚀
> 
> Huge thanks to our editor: @Kevin-Mattheus-Moerman, and the reviewers: @grlee77, @mathieuboudreau, @spinicist — your contributions to JOSS are greatly appreciated 🙏

Many thanks to all the reviewers @mathieuboudreau @spinicist @grlee77, the editor @Kevin-Mattheus-Moerman and the associate editor in chief @labarba for the time and inputs to make our work better.
