### ISSUE TITLE
[PRE REVIEW]: mbend: An R package for bending non-positive-definite matrices to positive-definite

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1726]
**Submitting author:** @nilforooshan (<a href="http://orcid.org/0000-0003-0339-5442">Mohammad Ali Nilforooshan</a>)
**Repository:** <a href="https://github.com/nilforooshan/mbend" target ="_blank">https://github.com/nilforooshan/mbend</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @nilforooshan. **Currently, there isn't an JOSS editor assigned** to your paper.

@nilforooshan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1726 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:199:in `parse_affiliations': undefined method `each' for "Livestock Improvement Corporation, Hamilton, New Zealand":String (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:185:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:91:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@nilforooshan unfortunately the JOSS editorial board has determined this work, although useful, is not eligible for publication in JOSS as it is classified as a minor utility software (see [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements)).
We hope you consider JOSS for future more substantial research software.
