### ISSUE TITLE
[PRE REVIEW]: FAT Forensics: A Python Toolbox for Implementing and Deploying Fairness, Accountability and Transparency Algorithms in Predictive Systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1727]
**Submitting author:** @So-Cool (<a href="http://orcid.org/0000-0002-9869-5896">Kacper Sokol</a>)
**Repository:** <a href="https://github.com/fat-forensics/fat-forensics" target ="_blank">https://github.com/fat-forensics/fat-forensics</a>
**Version:** 0.0.1
**Editor:** @arokem
**Reviewers:** @bernease,  @osolari

**Author instructions**

Thanks for submitting your paper to JOSS @So-Cool. **Currently, there isn't an JOSS editor assigned** to your paper.

@So-Cool if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01727/joss.01727/10.21105.joss.01727.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@VivianePons @arokem @terrytangyuan could one of you edit this one?

**Comment by arokem** [comment]
Yeah - I can take this one.

**Comment by arokem** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by arokem** [comment]
@So-Cool : do you have any suggestions for potential reviewers?

**Comment by arokem** [comment]
👋 @ahurriyetoglu : would you be willing to review this submission for JOSS?

**Comment by arokem** [comment]
👋 @jkahn : would you be willing to review this submission for JOSS?

**Comment by arokem** [comment]
@whedon assign @bernease as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @bernease

**Comment by So-Cool** [comment]
Hi, from the provided list @sbrugman, @giodegas and @soroushj could be potential reviewers. More generally, anybody with a machine learning background and interest in algorithmic fairness, accountability and transparency will be a good fit.

**Comment by arokem** [comment]
@sbrugman : 👋 would you be willing to review this article for JOSS?

**Comment by arokem** [comment]
@giodegas: 👋 would you be willing to review this article for JOSS?

**Comment by arokem** [comment]
@soroushj: 👋 would you be willing to review this article for JOSS?

**Comment by sbrugman** [comment]
@arokem I have already committed to another review. I'm not having the time to do more at a time.

**Comment by arokem** [comment]
@giodegas or @soroushj: would either of you be able to review this article for JOSS?

**Comment by arokem** [comment]
👋 @zfurnas : would you be willing to review this article for JOSS?

**Comment by arokem** [comment]
👋 @ahurriyetoglu : would you be willing to review this article for JOSS?

**Comment by giodegas** [comment]
> 
> 
> @giodegas or @soroushj: would either of you be able to review this article for JOSS?

I would be happy to do it, but cannot allocate time at the moment.
Sorry.

**Comment by arokem** [comment]
@FreddieV4 : would you be willing to review this article for JOSS?

**Comment by arokem** [comment]
@tianxzhu : would you be willing to review this article for JOSS?

**Comment by arokem** [comment]
@So-Cool : I apologize for how long it is taking to find another reviewer. As an update: I am currently emailing some people off this issue, to see whether anyone has a good idea (or might be willing to do this themselves). I hope that we can find someone within a few days and get things kicked off here. Thank you for your patience.

**Comment by arokem** [comment]
👋 @adebayoj : would you be interested in reviewing this article for the [Journal of Open Source Software](https://joss.theoj.org/)? It is closely related to the work that you do, so your expertise will be 
 very helpful here. For more information about the journal and our process, you can refer to this webpage:  https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by arokem** [comment]
:wave: @linuxscout : would you be willing to review this paper for JOSS?

**Comment by arokem** [comment]
👋 osolari : would you be willing to review this paper for JOSS?

**Comment by arokem** [comment]
:wave: @professoralkmin: would you be willing to review this paper for JOSS?

**Comment by arokem** [comment]
👋@osolari : would you be willing to review this paper for JOSS?

**Comment by osolari** [comment]
Would be happy to! Would you please send me some guidelines? :-)

**Comment by arokem** [comment]
Thanks! The reviewer guidelines are [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

**Comment by arokem** [comment]
@whedon add  @osolari as reviewer

**Comment by whedon** [comment]
OK,  @osolari is now a reviewer

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1904. Feel free to close this issue now!

**Comment by arokem** [comment]
OK - thanks @bernease and @osolari for taking this on! Your reviewer checklists are on issue #1904. Please feel free to post issues related to the review on the software repository and to tag me in if you have any questions. I'll close this issue now.

**Comment by professoralkmin** [comment]
would be happy to do it! :)

Em qua, 20 de nov de 2019 3:56 PM, Ariel Rokem <notifications@github.com>
escreveu:

**Comment by arokem** [comment]
Thanks for the quick reply here, @professoralkmin : I think that we already have the requisite two reviewers, so you are off the hook. I'll call on you if we need another look. Thanks again.
