### ISSUE TITLE
[PRE REVIEW]: GKNAP: A Java and C++ package for solving the multidimensional knapsack problem

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1728]
**Submitting author:** @shah314 (<a href="http://orcid.org/0000-0002-3770-1391">Shalin S Shah</a>)
**Repository:** <a href="https://github.com/shah314/gamultiknapsack" target ="_blank">https://github.com/shah314/gamultiknapsack</a>
**Version:** v1.6
**Editor:** @arfon
**Reviewers:** @sjvrijn, @stulacy

**Author instructions**

Thanks for submitting your paper to JOSS @shah314. **Currently, there isn't an JOSS editor assigned** to your paper.

@shah314 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01728/joss.01728/10.21105.joss.01728.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@poulson could be the editor for this one?

**Comment by shah314** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01728/joss.01728/10.21105.joss.01728.pdf)

**Comment by shah314** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01728/joss.01728/10.21105.joss.01728.pdf)

**Comment by shah314** [comment]
@whedon @oesteban @hooman650 @sjvrijn could be reviewers (they have optimization, C++ and Java listed as their reviewer skills).

**Comment by kthyng** [comment]
Hi @usethedata! Could you edit this submission? It may not be your exact expertise, but it'd be great if you could take it on.

**Comment by arfon** [comment]
@kthyng - I can take this one.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @oesteban @hooman650 @sjvrijn - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by oesteban** [comment]
Sorry, I'm not familiar enough with the topic. Thanks for pinging me.

**Comment by sjvrijn** [comment]
@arfon Sure, I can help out with a review

**Comment by arfon** [comment]
@whedon add @sjvrijn as reviewer

**Comment by whedon** [comment]
OK, @sjvrijn is now a reviewer

**Comment by arfon** [comment]
Thanks @sjvrijn - I'll start the main review issue (the one with checklists) once I've found a second review. Thanks in advance for helping out!

**Comment by shah314** [comment]
@whedon @stulacy could also be a reviewer

**Comment by arfon** [comment]
> @stulacy could also be a reviewer

:wave: @stulacy - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by stulacy** [comment]
Happy to review!

**Comment by arfon** [comment]
@whedon add @stulacy as reviewer

**Comment by whedon** [comment]
OK, @stulacy is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1756. Feel free to close this issue now!

**Comment by arfon** [comment]
@sjvrijn, @stulacy, @shah314 - see you over in #1756 for the main review.
