### ISSUE TITLE
[PRE REVIEW]: Pybotics: Python Toolbox for Robotics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1729]
**Submitting author:** @nnadeau (<a href="http://orcid.org/0000-0003-1220-0889">Nicholas A. Nadeau</a>)
**Repository:** <a href="https://github.com/nnadeau/pybotics" target ="_blank">https://github.com/nnadeau/pybotics</a>
**Version:** 0.7.1
**Editor:** @kyleniemeyer
**Reviewers:** @adi3, @CameronDevine

**Author instructions**

Thanks for submitting your paper to JOSS @nnadeau. **Currently, there isn't an JOSS editor assigned** to your paper.

@nnadeau if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01729/joss.01729/10.21105.joss.01729.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@labarba @kyleniemeyer can one of you take this one? I could take this but I've a lot on my plate at the moment so I'm hoping one of you can help. I'll help suggest reviewers though.

**Comment by Kevin-Mattheus-Moerman** [comment]
Perhaps reviewers from these:
https://github.com/openjournals/joss-reviews/issues/489
https://github.com/openjournals/joss-reviews/issues/500
https://github.com/openjournals/joss-reviews/issues/456

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by nnadeau** [comment]
Hi @kyleniemeyer , thanks for being the editor. I recommend the following people as reviewers:
- @mosteo
- @trallard
- @carlosjoseRG
- @CELavecchia
- @CameronDevine
- @jizecn
- @adi3
- @giodegas
- @jcarpent

**Comment by ts-adi** [comment]
@kyleniemeyer I can take this up

**Comment by CameronDevine** [comment]
I would also be willing to review this.

**Comment by adi3** [comment]
> @kyleniemeyer I can take this up

Now commenting with the correct profile

**Comment by kyleniemeyer** [comment]
Great, thanks @adi3 and @CameronDevine!

**Comment by kyleniemeyer** [comment]
@whedon add @adi3 as reviewer

**Comment by whedon** [comment]
OK, @adi3 is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon add @CameronDevine as reviewer

**Comment by whedon** [comment]
OK, @CameronDevine is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1738. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
@nnadeau @adi3 @CameronDevine the review will take place over in #1738
