### ISSUE TITLE
[PRE REVIEW]: GSODR: Global Summary Daily Weather Data in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#173]
**Submitting author:** @adamhsparks (<a href="http://orcid.org/0000-0002-0061-8359">Adam H. Sparks</a>)
**Repository:** <a href="https://github.com/ropensci/GSODR" target ="_blank">https://github.com/ropensci/GSODR</a>
**Version:** 1.0.1 
**Editor:** @karthik
**Reviewer:** @arfon

**What this issue is for**

Thanks for submitting your paper to JOSS @adamhsparks. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@noamross @karthik - is this already accepted in rOpenSci?

**Comment by adamhsparks** [comment]
It's already accepted: https://github.com/ropensci/onboarding/issues/79

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/177. Feel free to close this issue now!

**Comment by arfon** [comment]
> It's already accepted: ropensci/onboarding#79

Thanks @adamhsparks. I'll process the submission over in #177
