### ISSUE TITLE
[PRE REVIEW]: Larq: An Open-Source Library for Training Binarized Neural Networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1734]
**Submitting author:** @lgeiger (<a href="http://orcid.org/0000-0002-8697-9920">Lukas Geiger</a>)
**Repository:** <a href="https://github.com/larq/larq" target ="_blank">https://github.com/larq/larq</a>
**Version:** v0.7.1
**Editor:** @terrytangyuan
**Reviewers:** @sbrugman, @casperdcl, @EduPH

**Author instructions**

Thanks for submitting your paper to JOSS @lgeiger. **Currently, there isn't an JOSS editor assigned** to your paper.

@lgeiger if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01734/joss.01734/10.21105.joss.01734.pdf)

**Comment by kthyng** [comment]
Hi @terrytangyuan can you edit this submission?

**Comment by terrytangyuan** [comment]
@whedon assign @terrytangyuan as editor

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by terrytangyuan** [comment]
@lgeiger if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Comment by lgeiger** [comment]
@terrytangyuan Thanks for being our editor.

Judging from the list of people, it seams like @EduPH, @shreyasbapat, @sbrugman, @soroushj or @casperdcl might be a good fit?

**Comment by sbrugman** [comment]
Thanks, I'm willing to review.

**Comment by EduPH** [comment]
I could if needed :)

**Comment by casperdcl** [comment]
can review too

**Comment by terrytangyuan** [comment]
@whedon assign @sbrugman as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sbrugman

**Comment by terrytangyuan** [comment]
@whedon add @casperdcl as reviewer

**Comment by whedon** [comment]
OK, @casperdcl is now a reviewer

**Comment by terrytangyuan** [comment]
@whedon add @EduPH as reviewer

**Comment by whedon** [comment]
OK, @EduPH is now a reviewer

**Comment by terrytangyuan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1746. Feel free to close this issue now!

**Comment by terrytangyuan** [comment]
Thank you! @sbrugman, @casperdcl, @EduPH Just assigned you as reviewers. Look forward to your review in #1746!
