### ISSUE TITLE
[PRE REVIEW]: Shop-Solver: A framework for solving and benchmarking shop scheduling problems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1735]
**Submitting author:** @KingZee (<a href="http://orcid.org/0000-0002-6478-3628">Abdelhakim Zakkari</a>)
**Repository:** <a href="https://github.com/KingZee/shop-solver" target ="_blank">https://github.com/KingZee/shop-solver</a>
**Version:** v1.2.0
**Editor:** @gkthiruvathukal
**Reviewers:** @nnadeau, @nthomasCUBE

**Author instructions**

Thanks for submitting your paper to JOSS @KingZee. **Currently, there isn't an JOSS editor assigned** to your paper.

@KingZee if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1735 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:143:in `block in check_orcids': Problem with ORCID (0000-0000-0000-0000) for Alami Semma (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:141:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:141:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:88:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kthyng** [comment]
Hi @poulson can you edit this submission?

**Comment by KingZee** [comment]
Hi! I think that problem would be on my side, I forgot to change the placeholder ORCID of my supervisor I kept while writing the article. I have updated it now, apologies for the issue.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01735/joss.01735/10.21105.joss.01735.pdf)

**Comment by KingZee** [comment]
Maybe I can suggest some reviewers? @PrashantVaidyanathan @soroushj @rljacobson @dvberkel seem like potential good fits.

**Comment by KingZee** [comment]
Maybe I can suggest some reviewers? 
@PrashantVaidyanathan
@soroushj
@rljacobson
@dvberkel
@louiseadennis
@nthomasCUBE
@nnadeau
@hainesr
@nkratzke
@nuest
all seem like potential good fits.

**Comment by kthyng** [comment]
Thanks @KingZee for the suggestions.

@gkthiruvathukal Would you be able to edit this submission?

**Comment by gkthiruvathukal** [comment]
Hi @kthyng, yes, I can handle it. I am just returning from a long period of travel and have some other assignments in front of this one, but I should be able to get rolling on it by the weekend.

**Comment by kthyng** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by kthyng** [comment]
Thanks @gkthiruvathukal!

**Comment by gkthiruvathukal** [comment]
@PrashantVaidyanathan @soroushj @rljacobson @dvberkel @louiseadennis @nthomasCUBE @nnadeau @hainesr  @nkratzke @nuest: Would any two of you be willing to contribute a review for this submission?

**Comment by nnadeau** [comment]
@gkthiruvathukal I’ll review

**Comment by nthomasCUBE** [comment]
@gkthiruvathukal <https://github.com/gkthiruvathukal> I’ll review also

Am Fr., 20. Sept. 2019 um 06:37 Uhr schrieb Nicholas Nadeau, P.Eng., AVS <
notifications@github.com>:

**Comment by gkthiruvathukal** [comment]
Thanks, @nnadeau and @nthomasCUBE. I'll get this going!

**Comment by gkthiruvathukal** [comment]
@whedon assign @nnadeau as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nnadeau

**Comment by gkthiruvathukal** [comment]
@whedon add @nthomasCUBE as reviewer

**Comment by whedon** [comment]
OK, @nthomasCUBE is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1752. Feel free to close this issue now!

**Comment by poulson** [comment]
Thank you for taking this over, @kthyng. I just got back from some overseas travel and forgot to put my OOO up.
