### ISSUE TITLE
[PRE REVIEW]: umami: A Python package for Earth surface dynamics objective function construction

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1736]
**Submitting author:** @kbarnhart (<a href="http://orcid.org/0000-0001-5682-455X">Katherine Barnhart</a>)
**Repository:** <a href="https://github.com/TerrainBento/umami" target ="_blank">https://github.com/TerrainBento/umami</a>
**Version:** v1.0.0
**Editor:** @meg-simula
**Reviewers:** @sgrieve, @tristan-salles

**Author instructions**

Thanks for submitting your paper to JOSS @kbarnhart. **Currently, there isn't an JOSS editor assigned** to your paper.

@kbarnhart if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1736 with the following error: 

 Could not find bibliography file: papers.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by kthyng** [comment]
Hi @leouieda can you edit this submission?

**Comment by kthyng** [comment]
Hi @meg-simula! Could you edit this submission?

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01736/joss.01736/10.21105.joss.01736.pdf)

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01736/joss.01736/10.21105.joss.01736.pdf)

**Comment by kbarnhart** [comment]
@kthyng thanks for working to find this an editor! 

Some recommended reviewers:
@lheagy
@leouieda
@sgrieve
@dvalters
@tristan-salles

**Comment by sgrieve** [comment]
Hey. I'm happy to review this, but won't get a chance till later next week as our teaching term has just started and things have got really busy.

**Comment by meg-simula** [comment]
@kthyng Sure, I'd be happy to. Assigning myself.

**Comment by meg-simula** [comment]
@whedon assign meg-simula as editor

**Comment by whedon** [comment]
OK, the editor is meg-simula

**Comment by meg-simula** [comment]
Thanks, @kbarnhart  for the submission! This looks very much ready for review. I'll reach out to reviewers, and get back to you.

**Comment by meg-simula** [comment]
Thanks @sgrieve for volunteering! Next week is absolutely fine.

**Comment by meg-simula** [comment]
@whedon assign @sgrieve as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sgrieve

**Comment by meg-simula** [comment]
@lheagy Would you be interested and availble for reviewing this submission?

**Comment by kbarnhart** [comment]
@meg-simula anything else you need from me to get another reviewer for this? Thanks for handling it!

**Comment by tristan-salles** [comment]
Hi @meg-simula & @kbarnhart do you still need an additional reviewer? I'm happy to make the review if needed.

**Comment by kbarnhart** [comment]
@tristan-salles thanks for being willing to review this. I don't think I get to make decisions about reviewers or can ask `@whedon` to do assign reviewers. I'll wait for @meg-simula to respond.

**Comment by meg-simula** [comment]
Hi @tristan-salles, yes, we do. Thanks! I'll assign you and start the review process.

**Comment by meg-simula** [comment]
@whedon add @tristan-salles as reviewer

**Comment by whedon** [comment]
OK, @tristan-salles is now a reviewer

**Comment by meg-simula** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1776. Feel free to close this issue now!
