### ISSUE TITLE
[PRE REVIEW]: ANCRTAdjust: An R package to adjust routine HIV testing data from antenatal care to reduce bias in estimating HIV prevalence trends

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1737]
**Submitting author:** @brittanyblouin (<a href="http://orcid.org/0000-0001-7447-7467">Brittany Blouin</a>)
**Repository:** <a href="https://github.com/brittanyblouin/ANCRTAdjust" target ="_blank">https://github.com/brittanyblouin/ANCRTAdjust</a>
**Version:** v0.1.0
**Editor:** @csoneson
**Reviewers:** @ellessenne, @seabbs

**Author instructions**

Thanks for submitting your paper to JOSS @brittanyblouin. **Currently, there isn't an JOSS editor assigned** to your paper.

@brittanyblouin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kthyng** [comment]
Hi @csoneson! Can you edit this submission?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01737/joss.01737/10.21105.joss.01737.pdf)

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
@alletsee, @dvanic, @ellessenne, @seabbs - would two of you be willing to review this submission for JOSS?

**Comment by ellessenne** [comment]
I am happy to review it!

**Comment by seabbs** [comment]
Happy to review

**Comment by csoneson** [comment]
Great - thanks @ellessenne and @seabbs for accepting! (@alletsee, @dvanic - I hope we can get back to you for another review in the future!)

**Comment by csoneson** [comment]
@whedon assign @ellessenne as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ellessenne

**Comment by csoneson** [comment]
@whedon add @seabbs as reviewer

**Comment by whedon** [comment]
OK, @seabbs is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1740. Feel free to close this issue now!
