### ISSUE TITLE
[REVIEW]: Pybotics: Python Toolbox for Robotics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1738]
**Submitting author:** @nnadeau (<a href="http://orcid.org/0000-0003-1220-0889">Nicholas A. Nadeau</a>)
**Repository:** <a href="https://github.com/nnadeau/pybotics" target ="_blank">https://github.com/nnadeau/pybotics</a>
**Version:** 0.7.1
**Editor:** @kyleniemeyer
**Reviewer:** @adi3, @CameronDevine
**Archive:** <a href="https://doi.org/10.5281/zenodo.3464685" target="_blank">10.5281/zenodo.3464685</a>

## Status

[![status](https://joss.theoj.org/papers/f5c479042b279f51a496efc9c4e79384/status.svg)](https://joss.theoj.org/papers/f5c479042b279f51a496efc9c4e79384)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f5c479042b279f51a496efc9c4e79384"><img src="https://joss.theoj.org/papers/f5c479042b279f51a496efc9c4e79384/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f5c479042b279f51a496efc9c4e79384/status.svg)](https://joss.theoj.org/papers/f5c479042b279f51a496efc9c4e79384)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/nnadeau/pybotics" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@adi3 & @CameronDevine, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kyleniemeyer know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nnadeau/pybotics">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@nnadeau) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nnadeau/pybotics">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@nnadeau) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @adi3, @CameronDevine it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01738/joss.01738/10.21105.joss.01738.pdf)

**Comment by kyleniemeyer** [comment]
👋 @nnadeau @adi3 @CameronDevine

**Comment by nnadeau** [comment]
Thanks for volunteering to review, @adi3 and @CameronDevine

**Comment by adi3** [comment]
@nnadeau Great work in the repo! I'm yet to test it out on my machine but I did a quick overview and I'm already a fan. Regarding the review, I'd like you to add a few things in the `Development` section of the readme.

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Step 3 of your development process should have the contributor run tests to make sure the changes have not broken anything. Please list out specific commands and outputs the contributor should expect before the feature is ready for PR.

In addition, please add a quick line and a link to the issues board of your repo so users know where they can get support.

**Comment by nnadeau** [comment]
@adi3 thanks for the review. The following changes have been made:

- Added issue templates: https://github.com/nnadeau/pybotics/commit/7d53e8f31756c316a0c84662a094a644bb376e3a
- As a [`CONTRIBUTING.md`](https://github.com/nnadeau/pybotics/blob/master/.github/CONTRIBUTING.md) already existed, I updated `README.md` with additional community info, direct links to the relevant docs/issues, and extended the testing how-to: https://github.com/nnadeau/pybotics/commit/2fe8b2127d560c676666c1a041d903716d3b18f8

**Comment by adi3** [comment]
@nnadeau Thanks for updating that.

With reference to this quote from your paper:
> It was designed to provide a simple, clear, and concise interface to quickly simulate and evaluate common robot concepts, such as kinematics, dynamics, trajectory generations, and calibration.

I see the how the library helps with kinematics and calibration easily; both your examples and the source code show it clearly. I'm less certain about the `dynamics` and `trajectory generations` part of it. Of course, the kinematics and calibration features are important for calculating solutions of  dynamics and trajectory, but to actually mention it as an advantage of your library, please implement either (1) an out-of-the-box feature relating to them, or (2) an example script showing how the existing features lead to dynamics and planning equations.

Ditto for the mention of `Machine learning` in the Readme.

**Comment by nnadeau** [comment]
@adi3 good catch! I've added additional examples (https://github.com/nnadeau/pybotics/pull/728). Specifically:

- https://github.com/nnadeau/pybotics/blob/master/examples/trajectory_generation.ipynb
- https://github.com/nnadeau/pybotics/blob/master/examples/machine_learning.ipynb
- https://github.com/nnadeau/pybotics/blob/master/examples/dynamics.ipynb

Example:

![image](https://user-images.githubusercontent.com/6395915/65566806-f04cf180-df21-11e9-9d1b-04b3eae55125.png)

**Comment by adi3** [comment]
@nnadeau Stellar work! I'm impressed by the utility of your library. I'll likely use it my work at some point.

I'm having some trouble running your tests. This is the error I get: `No such file or directory: 'black': 'black' `. I'm not conversant with `poetry` so some pointers here would be useful.

**Comment by adi3** [comment]
> @nnadeau Stellar work! I'm impressed by the utility of your library. I'll likely use it my work at some point.
> 
> I'm having some trouble running your tests. This is the error I get: `No such file or directory: 'black': 'black' `. I'm not conversant with `poetry` so some pointers here would be useful.

My bad. Running `poetry install` got all this fixed. Your tests run fine and at this point, I am satisfied with your submission. Pending a references check, I will be happy to recommend your paper for publication.

**Comment by adi3** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by adi3** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.3390/robotics8020033 may be missing for title: Impedance Control Self-Calibration of a Collaborative Robot Using Kinematic Coupling
- https://doi.org/10.1109/jra.1987.1087086 may be missing for title: Introduction to Robotics Mechanics and Control
- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation
- https://doi.org/10.1109/iros.2018.8593598 may be missing for title: Evolutionary motion control optimization in physical human-robot interaction

INVALID DOIs

- None
```

**Comment by adi3** [comment]
@nnadeau can you please update your .bib file to include the missing DOIs? See `whedon` output above.

**Comment by danielskatz** [comment]
Please be aware that ```whedon``` is not perfect at this, and sometimes gives wrong suggestions.

**Comment by nnadeau** [comment]
@adi3 @danielskatz DOIs updated: https://github.com/nnadeau/pybotics/pull/729

Missing DOIs:

- `Craig2005` (popular robotics textbook)
- `jones2001scipy` (recommended citation for library: https://www.scipy.org/citing.html#scipy-the-library)
- `pedregosa2011scikit` (recommended citation for library: https://scikit-learn.org/stable/about.html#citing-scikit-learn)

**Comment by nnadeau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01738/joss.01738/10.21105.joss.01738.pdf)

**Comment by nnadeau** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.3390/robotics8020033 is OK
- 10.1007/978-3-319-54413-7 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/IROS.2018.8593598 is OK

MISSING DOIs

- https://doi.org/10.1109/jra.1987.1087086 may be missing for title: Introduction to Robotics Mechanics and Control

INVALID DOIs

- None
```

**Comment by adi3** [comment]
@kyleniemeyer I am finished with my review and I recommend this paper for publication. Thank you for facilitating the process.

**Comment by nnadeau** [comment]
@CameronDevine, https://github.com/nnadeau/pybotics/issues/730 is fixed. Thanks for the idea.

**Comment by CameronDevine** [comment]
Once nnadeau/pybotics#731 is closed I will be ready to recommend this paper for publication.

**Comment by nnadeau** [comment]
@CameronDevine good to go! https://github.com/nnadeau/pybotics/issues/731 closed with https://github.com/nnadeau/pybotics/pull/732

**Comment by CameronDevine** [comment]
@kyleniemeyer, I recommend this paper for publication.

**Comment by kyleniemeyer** [comment]
Thanks @CameronDevine @adi3 ! I'll do my checks now.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01738/joss.01738/10.21105.joss.01738.pdf)

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.3390/robotics8020033 is OK
- 10.1007/978-3-319-54413-7 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/IROS.2018.8593598 is OK

MISSING DOIs

- https://doi.org/10.1109/jra.1987.1087086 may be missing for title: Introduction to Robotics Mechanics and Control

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @nnadeau, just a few minor edits needed for the paper, in the references:

- the title in the Corke reference doesn't look completely correct, please check.
- The SciPy reference should be
```
@Misc{,
  author =    {Eric Jones and Travis Oliphant and Pearu Peterson and others},
  title =     {{SciPy}: Open source scientific tools for {Python}},
  year =      {2001--},
  url = "http://www.scipy.org/",
  note = {[Online; accessed <today>]}
}
```
- in the Nadeau 2018 reference, please put `{ }` around words that should be capitalized, like IEEE, RSJ, and IROS (or just the whole conference name)

We can ignore the warning about the missing DOI from whedon, that looks to be a review of the book you cited.

**Comment by nnadeau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01738/joss.01738/10.21105.joss.01738.pdf)

**Comment by nnadeau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01738/joss.01738/10.21105.joss.01738.pdf)

**Comment by nnadeau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01738/joss.01738/10.21105.joss.01738.pdf)

**Comment by nnadeau** [comment]
@kyleniemeyer 

- updated Corke citation title to match recommended title on [the toolbox's website](http://petercorke.com/wordpress/toolboxes/robotics-toolbox) (https://github.com/nnadeau/pybotics/commit/fe145a340f4d178c46a6abae523618756f4eda85)
- escaped ampersand in Corke title (https://github.com/nnadeau/pybotics/commit/58a4533baf4bbb4b9c59c78b000a3dc385245744)
- fixed scipy citation (https://github.com/nnadeau/pybotics/commit/609da085f9481c55fad66d7f63b233e2a2b221c0)
- added `{}` to Nadeau citation (https://github.com/nnadeau/pybotics/commit/924dd59c8dcc039ac860d646fbae7ec981a78e64)

**Comment by nnadeau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01738/joss.01738/10.21105.joss.01738.pdf)

**Comment by nnadeau** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.3390/robotics8020033 is OK
- 10.1007/978-3-319-54413-7 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/IROS.2018.8593598 is OK

MISSING DOIs

- https://doi.org/10.1109/jra.1987.1087086 may be missing for title: Introduction to Robotics Mechanics and Control

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@nnadeau thanks! The SciPy citation is still not quite right, since our template doesn't play well with the recommended year format. Perhaps just change it to "2001" ?

**Comment by nnadeau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01738/joss.01738/10.21105.joss.01738.pdf)

**Comment by nnadeau** [comment]
@kyleniemeyer done

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by kyleniemeyer** [comment]
ah, whoops! @nnadeau, please archive your repo using a service such as Zenodo, and let me know what the associated DOI is.

**Comment by nnadeau** [comment]
@kyleniemeyer 

- Bumped release to [`0.7.2`](https://github.com/nnadeau/pybotics/releases/tag/0.7.2) (includes all changes from this review process)
- Fixed the the Zenodo integration (https://zenodo.org/record/3464672)
- Added DOI badge (https://github.com/nnadeau/pybotics/commit/43caa8de6bdb76e7aecc23e7d46e35e26f8f0834)
- DOI = `10.5281/zenodo.3464672 `

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.3464672 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3464672" target="_blank">10.5281/zenodo.3464672</a> is the archive.

**Comment by kyleniemeyer** [comment]
@nnadeau sorry to drag this out, but it looks like you released v0.7.3—should that be what we use?

**Comment by nnadeau** [comment]
@kyleniemeyer sure! that was outside the scope of this review process (i.e., travis CI update), but sure, go ahead!

DOI:
    10.5281/zenodo.3464685

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.3464685 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3464685" target="_blank">10.5281/zenodo.3464685</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.3390/robotics8020033 is OK
- 10.1007/978-3-319-54413-7 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/IROS.2018.8593598 is OK

MISSING DOIs

- https://doi.org/10.1109/jra.1987.1087086 may be missing for title: Introduction to Robotics Mechanics and Control

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/990

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/990, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by nnadeau** [comment]
@kyleniemeyer looks good! Thank you everyone for this review process.

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1178808463922778112) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/991
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01738](https://doi.org/10.21105/joss.01738)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @nnadeau on your article's publication in JOSS! Thanks to @adi3 and @CameronDevine for reviewing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01738/status.svg)](https://doi.org/10.21105/joss.01738)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01738">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01738/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01738/status.svg
   :target: https://doi.org/10.21105/joss.01738
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01738/status.svg)](https://doi.org/10.21105/joss.01738)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
