### ISSUE TITLE
[PRE REVIEW]: Economiccomplexity: Methods Used in the Economic Complexity Literature

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1739]
**Submitting author:** @pachamaltese (<a href="http://orcid.org/0000-0003-1017-7574">Mauricio Vargas</a>)
**Repository:** <a href="https://github.com/pachamaltese/economiccomplexity" target ="_blank">https://github.com/pachamaltese/economiccomplexity</a>
**Version:** 0.2.1
**Editor:** @oliviaguest
**Reviewers:** @rickecon, @JohnCoene

**Author instructions**

Thanks for submitting your paper to JOSS @pachamaltese. **Currently, there isn't an JOSS editor assigned** to your paper.

@pachamaltese if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01739/joss.01739/10.21105.joss.01739.pdf)

**Comment by kthyng** [comment]
Hi @pachamaltese! Can you explain a little bit more about the research application of your software? Please keep in mind in particular the [author guidelines](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). Thanks!

**Comment by pachamaltese** [comment]
Hi @kthyng! sure, this package is the only I've seen on CRAN, and amongst R packages, to explore bipartite relations used in Economic Complexity. This takes all the equations (i.e LaTeX equations) from The Atlas of Economic Complexity and related articles, to R functions that, in my opinion, are easy to use and may contribute to ease reproducibility in Social Sciences.
I've read that the functions from this packages are also used in Economic Geography and may be useful to explore different relations in Media Sociology such as twitter users and twitter contents.
I can say that this introduces in an easy+fast way the numerical methods from Economic Complexity into the R-world.

**Comment by pachamaltese** [comment]
fixing wrong bib entry from plos one
@whedon generate pdf

**Comment by pachamaltese** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01739/joss.01739/10.21105.joss.01739.pdf)

**Comment by kthyng** [comment]
Thanks @pachamaltese for the extra information.

@oliviaguest This is outside your main expertise, but would you be willing to edit this submission?

**Comment by oliviaguest** [comment]
@kthyng yes, no problem. 😊

**Comment by kthyng** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by kthyng** [comment]
Thanks @oliviaguest!

**Comment by oliviaguest** [comment]
@tweed1e would you be interested in reviewing this?

**Comment by oliviaguest** [comment]
also @koulvi would you also be interested in reviewing this?

**Comment by oliviaguest** [comment]
for some reason I am trying to tag https://github.com/vkoul and it's not letting me — so weird, will email instead!

**Comment by tweed1e** [comment]
Sorry @oliviaguest, I don't have time to review at the moment, looks cool tho

**Comment by oliviaguest** [comment]
👋 Hey @mdsumner — would you be interested in reviewing this submission for JOSS? 😸

**Comment by mdsumner** [comment]
No, sorry can't do this one

**Comment by oliviaguest** [comment]
Hey @zedtaha and @feddelegrand7 — would you be up for reviewing this submission? 😄

**Comment by oliviaguest** [comment]
@labarba I'm really struggling here to find somebody (sent off some emails too) — do you think it's possible for the authors to suggest at least one person?

**Comment by oliviaguest** [comment]
@economistgame — would you be interested in reviewing this submission for JOSS? :blush:

**Comment by labarba** [comment]
The header comment in this issue does request reviewer suggestions from the author.

> @pachamaltese if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Comment by pachamaltese** [comment]
> The header comment in this issue does request reviewer suggestions from the author.
> 
> > @pachamaltese if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

sure, based on networks/graphs/economy

* MatthewSmith430 (visualisation, international trade, network analysis)
* paulgovan
* JohnCoene
* Nick-gauthier

**Comment by oliviaguest** [comment]
@whedon add @rickecon as reviewer

**Comment by whedon** [comment]
OK, @rickecon is now a reviewer

**Comment by rickecon** [comment]
OK. Starting this review.

**Comment by oliviaguest** [comment]
@rickecon sadly, even though I have emailed a lot of people (about 10 up to now) we still need to wait till I find a 2nd reviewer before you can properly start. 

@pachamaltese I don't know if my emails to all these people are going to their spam folder or if they are too busy to reply, etc., but I will keep trying.

**Comment by oliviaguest** [comment]
👋 @MatthewSmith430, @paulgovan, @JohnCoene, @Nick-gauthier are any of you up for reviewing this? Sorry if I have also emailed you already, but please feel free to reply here instead of email if easier. Thanks! 😄

**Comment by JohnCoene** [comment]
@oliviaguest @pachamaltese I apologise for the belated reply, the notifications and emails totally escaped me. I'll be more than happy to review the package, it looks very interesting!

**Comment by rickecon** [comment]
@oliviaguest, I saw that @JohnCoene responded. In the future, try inviting the following two individuals to review JOSS economics manuscripts. Both are open source modelers and both would likely be interested in contributing to this community and to JOSS.

@jdebacker, Jason DeBacker, Associate Professor, Department of Economics, University of South Carolina ([https://www.jasondebacker.com/](https://www.aei.org/profile/matthew-h-jensen/))

@MattHJensen, Matt Jensen, Director of the Open Source Policy Center at the American Enterprise Institute ([https://www.aei.org/profile/matthew-h-jensen/](https://www.aei.org/profile/matthew-h-jensen/))

**Comment by oliviaguest** [comment]
@whedon add @JohnCoene as reviewer

**Comment by whedon** [comment]
OK, @JohnCoene is now a reviewer

**Comment by oliviaguest** [comment]
@rickecon perfect — thank you!

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1866. Feel free to close this issue now!

**Comment by oliviaguest** [comment]
@rickecon, @JohnCoene, @pachamaltese thank you all, please go to #1866 and/or open issues in the code repo itself, as appropriate!
