### ISSUE TITLE
[PRE REVIEW]: cleanEHR: The critical care EHR analysis tools

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#174]
**Submitting author:** @sinanshi (<a href="http://orcid.org/0000-0001-6935-0429">Sinan Shi</a>)
**Repository:** <a href="https://github.com/CC-HIC/cleanEHR" target ="_blank">https://github.com/CC-HIC/cleanEHR</a>
**Version:** v0.1.0
**Editor:** @arfon
**Reviewer:** @arfon

**What this issue is for**

Thanks for submitting your paper to JOSS @sinanshi. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@noamross - this looks to be a good candidate for rOpenSci, would you agree?

**Comment by ijstokes** [comment]
I was asked to put my name in as a reviewer.  I'd be happy to do that.  I have a background in computational biology and large scale distributed infrastructure for computational science.

**Comment by noamross** [comment]
Thanks, @arfon. Hello @jsinanshi . As Arfon noted, this package looks like it would be a great match for rOpenSci, which specializes in data-access R packages like this and has a joint submittal process with JOSS. If you are interested in this approach, you can find more info here: https://github.com/ropensci/onboarding. Let us know, otherwise we can continue with the submission just through JOSS.

**Comment by dpshelio** [comment]
@noamross  - just mentioning @sinanshi (typo) and @docsteveharris to include them in the decission.

**Comment by sinanshi** [comment]
@noamross We really like the idea of submitting our package to rOpenSci. Do we need to withdraw the current JOSS submission?

**Comment by sinanshi** [comment]
rOpenSci submission https://github.com/ropensci/onboarding/issues/102

**Comment by arfon** [comment]
> rOpenSci submission ropensci/onboarding#102

👍  we'll pause this for now then.

**Comment by sinanshi** [comment]
Could we restart the process the JOSS application as we received the approval from ropensci. We have the updated the DOI, see the readme file. https://github.com/ropensci/cleanEHR

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/513. Feel free to close this issue now!
