### ISSUE TITLE
[REVIEW]: ANCRTAdjust: An R package to adjust routine HIV testing data from antenatal care to reduce bias in estimating HIV prevalence trends

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1740]
**Submitting author:** @brittanyblouin (<a href="http://orcid.org/0000-0001-7447-7467">Brittany Blouin</a>)
**Repository:** <a href="https://github.com/brittanyblouin/ANCRTAdjust" target ="_blank">https://github.com/brittanyblouin/ANCRTAdjust</a>
**Version:** v0.1.0
**Editor:** @csoneson
**Reviewer:** @ellessenne, @seabbs
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/604f36e3c154da318ef64a4383c4d084/status.svg)](https://joss.theoj.org/papers/604f36e3c154da318ef64a4383c4d084)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/604f36e3c154da318ef64a4383c4d084"><img src="https://joss.theoj.org/papers/604f36e3c154da318ef64a4383c4d084/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/604f36e3c154da318ef64a4383c4d084/status.svg)](https://joss.theoj.org/papers/604f36e3c154da318ef64a4383c4d084)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/brittanyblouin/ANCRTAdjust" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ellessenne & @seabbs, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/brittanyblouin/ANCRTAdjust">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@brittanyblouin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/brittanyblouin/ANCRTAdjust">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@brittanyblouin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ellessenne, @seabbs it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01740/joss.01740/10.21105.joss.01740.pdf)

**Comment by csoneson** [comment]
@ellessenne, @seabbs - this is where the review happens! Instructions are provided in the post above - don't hesitate to ping me if you have questions.

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1097/01.aids.0000172871.80723.3e may be missing for title: New strategies for HIV surveillance in resource-constrained settings: An overview

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@brittanyblouin - please have a look at the checklists above and make sure that all requested items are available in your submission - if not, you can add the already now! Please also add DOIs to the references in your submission.

**Comment by brittanyblouin** [comment]
@csoneson - I have added the DOIs to the references.

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1097/01.aids.0000172871.80723.3e is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01740/joss.01740/10.21105.joss.01740.pdf)

**Comment by ellessenne** [comment]
Hi @brittanyblouin (cc @csoneson), 

First of all - well done with the package! I think you clearly describe the issue you aim to solve and the high-level functionality of ANCRTAdjust. The range of functions provided for end-users seems comprehensive (although I don't really work in the area, so hopefully I haven't missed anything obvious).
I have a few comments, some of which are quite specific and some more general ones.
You can find the former filed as issues in the ANCRTAdjust repository, and the more general comments follow here.

First, I think the documentation of the package could be improved: in particular, I think that the different arguments and options - albeit well described, strictly speaking - do not fully motivate their choice. What I am trying to say is, arguments are well described but they lack a bit of context and more methodological explanations: for instance, when using the `data_clean()` function it is not clear why one should choose an adjustment option over another. Another example is with the `mt_adjust()` function. I would suggest expanding the documentation a bit, and maybe including a vignette that describes the relevant methodology behind the functions implemented in this package.

Second, there are some tests in the 'test' folder - which is great! However, [`testthat`](https://testthat.r-lib.org) could be implemented to trigger automatic testing when running R CMD check.
More tests should be added to cover argument checks (and more argument checks should be implemented throughout the package as well).
The package *should* aim to pass R CMD check (I recommend running `devtools::check()` often) - do you aim to submit to CRAN eventually?

Third, there is no comparison with other software. Is there other software that can do something similar? If no, I would stress more the novelty of your work! If yes, a comparison needs to be included, focussing on strengths and weaknesses.

Fourth, I did not tick the "references" box yet: are the methods implemented in this package covered by the references included in the paper? Are they well established methods in the field? I feel I was not given enough information/details to assess this (and this somewhat connects with my first comment included above).

Overall, I like the package and the paper - the authors highlight the importance of standardised protocols and procedures to ensure consistency and reproducibility, and I share the same feeling.
However, I think the documentation of the package (and the paper, to a smaller extent) could be improved/expanded to describe methods in more detail and to be unambiguous to the end-user.

I hope this helps, and I look forward to discussing this in more detail!
Cheers,

Alessandro

**Comment by seabbs** [comment]
Hi @brittanyblouin (cc @csoneson) , 

Well done @brittanyblouin this is a nice package - we definitely need to see more of these kinds of tools for standardising data handling. 

Before I can recommend this package though I think there needs to be some more work tightening up - and expanding - the documentation. The rigour of the coding (i.e testing, function names, environment variable handling etc.) also needs some work. 

Looking forward to getting into  the details!

Very much seconding all of @ellessenne points in my review as their review was already pretty watertight (nice job 👍). Expanded on them in the review issues where I felt I had something to add.

**Comment by csoneson** [comment]
@ellessenne, @seabbs - thanks a lot for your comments!
@brittanyblouin - please go through the comments above and the issues that have been opened in your repository - don't hesitate to ping me and/or continue the discussion in the respective issue if you have any questions, and please report back here when you are ready for the reviewers to take another look!

**Comment by brittanyblouin** [comment]
Hi @ellessenne and @seabbs, Thank you so much for the comments and review of our package.  We will go over all comments and issues shortly and get back with an improved version.

**Comment by brittanyblouin** [comment]
Hi @csoneson - Can we add co-author @m-maheu-giroux as a corresponding author for this submission?

**Comment by csoneson** [comment]
> Hi @csoneson - Can we add co-author @m-maheu-giroux as a corresponding author for this submission?

@brittanyblouin Since @m-maheu-giroux is mentioned in this issue now, I believe he will be notified of all further activity here (which would also be achieved by clicking the "Subscribe" button above). Would that be a satisfactory solution? Or do you rather mean that you would like to hand over the "submitting author" status?

**Comment by m-maheu-giroux** [comment]
Yes, this is a satisfactory solution (thanks!).
Brittany Blouin shall remain "submitting author".

**Comment by m-maheu-giroux** [comment]
Hi @ellessenne and @seabbs,

First, thanks a lot for your thorough review. We have yet to publish many R packages and we really appreciate the time and efforts it took for you to revise our work (and to correct some of the omissions/blunder we made). 

We believe that we have addressed all your concerns and suggestions. I have not closed the issues you raised yet as I feel it is your prerogative to do so.

Do not hesitate to contact me if you have any further questions. Thanks again.

Best,
Mathieu MG

**Comment by seabbs** [comment]
Thanks for these changes @m-maheu-giroux - I think the package is looking really good! 

I've just gone through the review issues and added some more comments. I think the main work left to do is making sure unit test coverage is good enough, confirming package functionality, and making the need for the package very clear (nearly there on this).

**Comment by m-maheu-giroux** [comment]
Hi @ellessenne and @seabbs,

I will do my best to address your suggestions shortly. However, my co-author is on maternity leave and I am traveling extensively over the next month. I anticipate some delays in incorporating your suggestions.

Thank you for your understanding,
Mathieu MG

**Comment by ellessenne** [comment]
No worries @m-maheu-giroux, take your time - from my point of view, we're here to help so no need to worry about it!

**Comment by danielskatz** [comment]
I'm going to mark this as paused for now

**Comment by danielskatz** [comment]
It's now been 2 more months - is there any news on progress?

**Comment by m-maheu-giroux** [comment]
Apologies about the delay. The lead author on this is on maternity leave and it has been difficult to make rapid progress on this. Please let us know if pausing this causes you any issues.

**Comment by danielskatz** [comment]
Could we get a date when you think there will be progress?  (This just helps up know when to check on this again.)

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by csoneson** [comment]
@brittanyblouin, @m-maheu-giroux - do you think you will have the time to restart working on this submission within the next month or so? If not, in order to respect the reviewers' time and availability committment, I will propose to close (reject) this submission, and invite a resubmission at a later point in time.

**Comment by arfon** [comment]
@csoneson - I agree with your assessment here. Let's give this a couple more weeks but if we don't have a clear statement of intent from the authors by then we should close this submission.

**Comment by m-maheu-giroux** [comment]
Hi,

Thanks for your patience.
The intent was still to refine the submission by addressing the few outstanding comments by the reviewers. However, my co-authors and I are not in a position to do so within the next few weeks. We unfortunately have to agree with your proposition to close (reject) the submission.

Again, I would like to thank @ellessenne  and @seabbs  for their time reviewing the package. We highly appreciated your inputs.

Best,
Mathieu MG

**Comment by csoneson** [comment]
Thanks for letting us know @m-maheu-giroux - we will close this submission. Thanks a lot to @ellessenne and @seabbs for your time reviewing!

**Comment by ellessenne** [comment]
No worries! 
Happy to re-review this once it gets resubmitted! 😃

**Comment by arfon** [comment]
👍 ok thanks all. I'll go ahead and close this now but please do consider a re-submission again in the future.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
