### ISSUE TITLE
[REVIEW]: bio-go: A flexible tools Bioinformatics library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1741]
**Submitting author:** @RHagenson (<a href="http://orcid.org/0000-0001-9750-1925">Ryan Hagenson</a>)
**Repository:** <a href="https://github.com/bio-ext/bio-go" target ="_blank">https://github.com/bio-ext/bio-go</a>
**Version:** v1.0.0
**Editor:** @lpantano
**Reviewer:** @kortschak, @will-rowe
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/7217d1ef147e05e94f323aa080d10422/status.svg)](https://joss.theoj.org/papers/7217d1ef147e05e94f323aa080d10422)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7217d1ef147e05e94f323aa080d10422"><img src="https://joss.theoj.org/papers/7217d1ef147e05e94f323aa080d10422/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7217d1ef147e05e94f323aa080d10422/status.svg)](https://joss.theoj.org/papers/7217d1ef147e05e94f323aa080d10422)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bio-ext/bio-go" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kortschak & @will-rowe, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bio-ext/bio-go">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@RHagenson) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bio-ext/bio-go">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@RHagenson) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kortschak, @will-rowe it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01741/joss.01741/10.21105.joss.01741.pdf)

**Comment by RHagenson** [comment]
Note the version number under review should be [v1.1.3](https://github.com/bio-ext/bio-go/tree/v1.1.3) as v1.0.0 (as stated above) was prior to implementing pre-review comments.

**Comment by will-rowe** [comment]
Hi @RHagenson!

I've just done my review and have filed it as an issue over at the [repo](https://github.com/bio-ext/bio-go/issues/5). Please let me know if you need anything clarifying.

Cheers,

Will

**Comment by Kevin-Mattheus-Moerman** [comment]
@lpantano can you check with the authors where we stand with this submission?

**Comment by RHagenson** [comment]
@lpantano Work is still being done to address the concerns raised by reviewers. Unfortunately for me, I am the only author on the submission and have been pulled in other directions so progress stalled. I was able to knock out the "low-hanging fruit" concerns, but the more major ones -- which will take greater time to address -- remain.

**Comment by danielskatz** [comment]
@RHagenson  - I'm going to mark this as paused while you work through the major issues, as the associate-editor-in-chief on duty this week.  Please let us know when you are ready for the review to resume.

**Comment by RHagenson** [comment]
@danielskatz Pausing it is reasonable. I will continuing making the major changes then resume review once they are implemented. Thank you for your understanding.

**Comment by rhagenson** [comment]
@lpantano, I wanted to inform you that as part of the review process where both reviewers suggested a name change I have changed the organization and repo name. The code now resides at: https://github.com/sembio/go and the paper title has changed accordingly to "sembio/go: Semantic Bioinformatics for Go" -- I did not change significant portions of the code during this migration.

I still need to update the Zenodo archival process and make the other corrections as reviewers noted. Review should remain paused until I have made the full migration to the new code repo.

**Comment by lpantano** [comment]
Thanks for the update @rhagenson.

**Comment by danielskatz** [comment]
👋 @rhagenson - can you provide an update on your progress, and an expected date by which you think you will be done with your changes?

**Comment by rhagenson** [comment]
@danielskatz Thank you for bumping this to the top of my list.

Unfortunately, through this review process I have realized that `bio-go` (now `sembio/go`) is not the priority it should be for me to maintain a project of its scale in the longterm. I still believe `sembio/go`'s approach is valuable. However, I do not currently have the necessary bandwidth to maintain, extend, and improve `sembio/go`.

With this said, I wish to regretfully withdraw this submission in its current state. Thank you to all who have committed time to reviewing and managing this submission.

**Comment by danielskatz** [comment]
Thanks for letting us know - you can, of course, resubmit at a later time if your desires change

**Comment by danielskatz** [comment]
Thanks to @kortschak & @will-rowe for your reviewing work and @lpantano for your editing

**Comment by danielskatz** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
