### ISSUE TITLE
[REVIEW]: Bedtoolsr: An R package for genomic data analysis and manipulation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1742]
**Submitting author:** @dphansti (<a href="http://orcid.org/0000-0003-2123-0051">Douglas Phanstiel</a>)
**Repository:** <a href="https://github.com/PhanstielLab/bedtoolsr.git" target ="_blank">https://github.com/PhanstielLab/bedtoolsr.git</a>
**Version:** v2.29.0-3
**Editor:** @mgymrek
**Reviewer:** @nhejazi , @mikmaksi 
**Archive:** <a href="https://doi.org/10.5281/zenodo.3509513" target="_blank">10.5281/zenodo.3509513</a>

## Status

[![status](https://joss.theoj.org/papers/778551a735c85cf3d658035edd7dfbda/status.svg)](https://joss.theoj.org/papers/778551a735c85cf3d658035edd7dfbda)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/778551a735c85cf3d658035edd7dfbda"><img src="https://joss.theoj.org/papers/778551a735c85cf3d658035edd7dfbda/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/778551a735c85cf3d658035edd7dfbda/status.svg)](https://joss.theoj.org/papers/778551a735c85cf3d658035edd7dfbda)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/PhanstielLab/bedtoolsr.git" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@nhejazi  & @mikmaksi , please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mgymrek know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/PhanstielLab/bedtoolsr.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@dphansti) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/PhanstielLab/bedtoolsr.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@dphansti) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @nhejazi , @mikmaksi  it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01742/joss.01742/10.21105.joss.01742.pdf)

**Comment by mgymrek** [comment]
Friendly reminder to @nhejazi , @mikmaksi to post comments and go through the checklist on this review thread. Thanks!

**Comment by mikmaksi** [comment]
Here is my review. Checklist above is also marked. Everything looks good except I could not find a License file. I have one minor suggestion for the installation instructions and to expand on the usage example. Thank you!

### General checks
1. Repository: Is the source code for this software available at the repository url?
   - Yes.
2. License: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?
   - No. I could not find a license file in the repo.
3. Contribution and authorship: Has the submitting author (@dphansti) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
   - Yes. 

### Functionality
1. Installation: Does installation proceed as outlined in the documentation?
   - Yes. I have a minor suggestion about installation instructions. Would the authors consider adding a note about supported operating systems? A user may have R installed on their Windows machine and have bedtools installed on Windows Subsystem for Linux (WSL). bedtoolsr would not work in this case as far as I can tell since R wouldn't be able to call the bedtools binary. 
2. Functionality: Have the functional claims of the software been confirmed?
   - I tested bt.intersect, bt.igv, bt.links, bt.closest, bt.bamtobed, bt.coverage and bt.overlap on some sample data and encountered no issues.
3. Performance: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)
   - No performance claims to evaluate.

### Documentation
1. A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
   - Yes.
2. Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
   - Yes. See note under the Functionality section.
3. Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
   - The example provided in the README is somewhat basic. An example where multiple bedtools commands are chained together inside a single R script would go a long way to showcasing how bedtoolsr makes it easy to build a whole workflow using genome math in R.
4. Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
   - Yes. Usage instructions are provided for each function through built-in help docs.
5. Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?
   - Yes. testthat unit tests are implemented and Travis CI integration is set up.
6. Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support.
   - Yes.

### Software paper
1. Summary: Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
   - Yes.
2. A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
   - Yes. Authors make the case that bedtoolsr allows direct access to all functions in the bedtools package. Users already familiar with bedtools would have no learning curve associated with using bedtoolsr. Other main stregnths of bedtoolsr are ability to pass either file paths or R objects into bedtools functions.
3. State of the field: Do the authors describe how this software compares to other commonly-used packages?
   - Yes. Authors cite Riemondy (IRanges) and Lawrence et al. (valr). bedr package is not mentioned explicitly but is in the Lawrence et al. reference.
4. Quality of writing: Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
   - Yes.
5. References: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper citation syntax?
   - Citations are provided in correct format.

**Comment by nhejazi** [comment]
@dphansti et al., excellent work on this package, looks quite useful! After going through the review checklist, there's just a few items that require your attention before the few outstanding review items can be checked off. Please address the following when convenient:

* The package requires information about an open-source license, see https://github.com/PhanstielLab/bedtoolsr/issues/2
* The package requires contribution guidelines, see https://github.com/PhanstielLab/bedtoolsr/issues/3
* The JOSS paper looks good, but please add DOIs for each item in the bibliography for which this is possible, e.g., for the pybedtools paper in Bioinformatics, the DOI would be 10.1093/bioinformatics/btr539 and the DOI URL https://doi.org/10.1093/bioinformatics/btr539

**Comment by mgymrek** [comment]
Thanks @nhejazi and @mikmaksi for your helpful reviews.

@dphansti: Please address these comments here. I think they all look minor and addressable.

**Comment by dphansti** [comment]
Thank you so much for your quick and helpful reviews.  We believe we have addressed all of the comments and issues.


**Mikmaksi’s comments**

> General Comment 2: I could not find a license file in the repo.

We followed reviewer nhejazi’s instructions below to properly handle licensing for the R package and for the repository.

> Functionality Comment 1: I have a minor suggestion about installation instructions. Would the authors consider adding a note about supported operating systems? A user may have R installed on their Windows machine and have bedtools installed on Windows Subsystem for Linux (WSL). bedtoolsr would not work in this case as far as I can tell since R wouldn't be able to call the bedtools binary.

Great suggestion.  We have added the following text to README.md:
“bedtoolsr should work on any system with R and bedtools installed. It has been tested on macOS (version 10.14 "Mojave") and Linux (Ubuntu version 18.04). bedtools is not available for Windows; however, you can either use a virtual machine or Windows Subsystem for Linux. In either case, R from the Windows side would not be able to access bedtools running on the Linux side, so R and bedtoolsr would also have to be installed on the Linux side.”

> Documentation Comment 3: The example provided in the README is somewhat basic. An example where multiple bedtools commands are chained together inside a single R script would go a long way to showcasing how bedtoolsr makes it easy to build a whole workflow using genome math in R.

We have added a more complex and realistic example to the README.md file.


**nhejazi’s comments**

> The package requires information about an open-source license, see PhanstielLab/bedtoolsr#2

We have added a LICENSE file, referenced by the DESCRIPTION file, with the copyright year and holders, a LICENSE.md with the full license information, and closed the issue. We greatly appreciate the reviewer’s detailed instructions in this regard.

> The package requires contribution guidelines, see PhanstielLab/bedtoolsr#3

We have added this short contribution guidelines section to README.md and closed the issue:
“We welcome user feedback and contributions on this package. If you have a question or a problem, the best approach is to report it is through GitHub's issue tracker. If you want to propose a change to the source code, either to fix a bug or make an improvement, use a pull request.”

> please add DOIs for each item in the bibliography for which this is possible

We have added DOIs for all journal article citations.

**Comment by nhejazi** [comment]
Thanks for the quick work on this dphansti --- all looks good to me!

**Comment by mikmaksi** [comment]
Look good to me as well. Thank you @dphansti

**Comment by mgymrek** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01742/joss.01742/10.21105.joss.01742.pdf)

**Comment by mgymrek** [comment]
@mikmaksi if all looks good can you complete the checklist?

@dphansti this looks great. Can you just address these very minor comments on the proof?
"use to the genomic community" -> "use to the genomics community"
"breakthroughs in genetic research"-> "breakthroughs in genetics research"

After that, can you make a Zenodo archive, ensuring the title and author list match the paper, and report the DOI here? Also please ensure the version listed here (v2.29.0) is correct.

**Comment by mikmaksi** [comment]
@mgymrek of course. I checked the last box that was not check (license)

**Comment by dphansti** [comment]
Thanks @mgymrek. I think we have addressed all of the issues.

1) We made the suggested changes (e.g. genomic -> genomics) in the paper.md file
2) We made a Zenodo archive
3) DOI of the archive is 10.5281/zenodo.3509513
4) The version is v2.29.0-3 is the newest version that has the changes in 1-3 above.

Let me know if we need to do anything else.

**Comment by mgymrek** [comment]
@whedon set v2.29.0-3 as version

**Comment by whedon** [comment]
OK. v2.29.0-3 is the version.

**Comment by mgymrek** [comment]
Thanks @dphansti. Can you just ensure the Zenodo archive and the paper have the same title? It looks like the Zenodo archive is titled "PhanstielLab/bedtoolsr: bedtoolsr v2.29.0-3".

**Comment by dphansti** [comment]
@mgymrek I edited the Zenodo archive title to match the paper title. Let me know if it still doesn't look right.  Thanks.

**Comment by mgymrek** [comment]
@whedon set 10.5281/zenodo.3509513 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3509513" target="_blank">10.5281/zenodo.3509513</a> is the archive.

**Comment by mgymrek** [comment]
Thanks for the changes!

@openjournals/joss-eics we're ready to accept this article!

**Comment by dphansti** [comment]
Great.  Thank you all for your work on this.  @mgymrek what happens next? Do we need to take any action?

**Comment by mgymrek** [comment]
Pinging @openjournals/joss-eics again it looks like this might have been missed.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01742/joss.01742/10.21105.joss.01742.pdf)

**Comment by danielskatz** [comment]
please merge https://github.com/PhanstielLab/bedtoolsr/pull/4

**Comment by danielskatz** [comment]
also https://github.com/PhanstielLab/bedtoolsr/pull/5

**Comment by dphansti** [comment]
@danielskatz Both have been merged.  Thanks.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01742/joss.01742/10.21105.joss.01742.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.32614/RJ-2011-002 is OK
- 10.1038/517109a is OK
- 10.12688/f1000research.11997.1 is OK
- 10.1093/bioinformatics/btq033 is OK
- 10.1371/journal.pcbi.1003118 is OK
- 10.1093/bioinformatics/btr539 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1157

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1157, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1202817422375436289) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1158
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01742](https://doi.org/10.21105/joss.01742)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @nhejazi & @mikmaksi for reviewing, and @mgymrek for editing!
And congratulations to @dphansti and co-authors!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01742/status.svg)](https://doi.org/10.21105/joss.01742)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01742">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01742/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01742/status.svg
   :target: https://doi.org/10.21105/joss.01742
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01742/status.svg)](https://doi.org/10.21105/joss.01742)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
