### ISSUE TITLE
[REVIEW]: oifits :  A Python Package to Analyse EHT Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1743]
**Submitting author:** @shreyasbapat (<a href="http://orcid.org/0000-0002-0870-4665">Shreyas Bapat</a>)
**Repository:** <a href="https://github.com/shreyasbapat/python-oifits" target ="_blank">https://github.com/shreyasbapat/python-oifits</a>
**Version:** v0.2.0
**Editor:** @arfon
**Reviewer:** @taldcroft, @mwcraig
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/616d1441849c0da9fc6218441ea34513/status.svg)](https://joss.theoj.org/papers/616d1441849c0da9fc6218441ea34513)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/616d1441849c0da9fc6218441ea34513"><img src="https://joss.theoj.org/papers/616d1441849c0da9fc6218441ea34513/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/616d1441849c0da9fc6218441ea34513/status.svg)](https://joss.theoj.org/papers/616d1441849c0da9fc6218441ea34513)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/shreyasbapat/python-oifits" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@taldcroft & @mwcraig, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/shreyasbapat/python-oifits">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@shreyasbapat) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/shreyasbapat/python-oifits">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@shreyasbapat) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @taldcroft, @mwcraig it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01743/joss.01743/10.21105.joss.01743.pdf)

**Comment by arfon** [comment]
@taldcroft, @mwcraig - many thanks for agreeing to review this submission!

Please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by mwcraig** [comment]
@arfon my review of this submission is complete for the moment. 

I have not reviewed the paper itself in detail because of what is, I believe, a major issue with the code, described at https://github.com/shreyasbapat/python-oifits/issues/2

Because of that issue, my recommendation is that this submission needs major revision before it can be accepted.

The other issues I've opened in the code repo are relatively straightforward to address.

**Comment by shreyasbapat** [comment]
Working on it. Sorry for the inconvenience. I will need some time on this.

**Comment by shreyasbapat** [comment]
I am sorry for the mess @mwcraig . Thankyou for pointing this out. I had no idea of my mistake there. 
Sorry @arfon , I will revise the submission. It will take me some time (around 2-3 days) due to my ongoing exams. It was a wrong push, so I have the code ready which was **supposed** to go here. It will need some polishing and hence I will need some time. I request you to please halt this review for the moment. I am ashamed at this type of naive mistake, but I will ping you back as soon as I fix it.

**Comment by shreyasbapat** [comment]
@arfon I actually did a wrong push which led to this. I wish to stop the review process as I am feeling pathetic about it. I will restructure everything and make sure nothing of this sort happens at all again and will resubmit. I will remove this repository, and create a new one without the history of old faulty pushes. 
Can you stop the review at this point so that I can correct my mistakes?

**Comment by arfon** [comment]
Thanks for flagging these issues @mwcraig. As @shreyasbapat has requested, at this point I think it's best to have them withdraw this submission and potentially resubmit at some point in the future when these issues have been addressed.

> Can you stop the review at this point so that I can correct my mistakes?

Certainly. I'll close this issue now. 

Thanks for your efforts on this @mwcraig! @shreyasbapat - if you're able to resolve these issues to the satisfaction of @pboley and the reviewers here we'd welcome a submission at some point again in the future.

**Comment by taldcroft** [comment]
A bit late to the show, but I reviewed the discussion agree with the action to withdraw.
