### ISSUE TITLE
[REVIEW]: ndsplines: A Python Library for Tensor-Product B-Splines of Arbitrary Dimension

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1745]
**Submitting author:** @sixpearls (<a href="http://orcid.org/0000-0001-5602-1888">Benjamin Margolis</a>)
**Repository:** <a href="https://github.com/kb-press/ndsplines/" target ="_blank">https://github.com/kb-press/ndsplines/</a>
**Version:** 0.1.1
**Editor:** @mbobra
**Reviewer:** @amritagos, @sarats
**Archive:** <a href="https://doi.org/10.5281/zenodo.3516465" target="_blank">10.5281/zenodo.3516465</a>

## Status

[![status](https://joss.theoj.org/papers/2105c9d4cfe04cc994d56f389c273111/status.svg)](https://joss.theoj.org/papers/2105c9d4cfe04cc994d56f389c273111)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2105c9d4cfe04cc994d56f389c273111"><img src="https://joss.theoj.org/papers/2105c9d4cfe04cc994d56f389c273111/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2105c9d4cfe04cc994d56f389c273111/status.svg)](https://joss.theoj.org/papers/2105c9d4cfe04cc994d56f389c273111)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/kb-press/ndsplines/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@amritagos & @sarats, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mbobra know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kb-press/ndsplines/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@sixpearls) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kb-press/ndsplines/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@sixpearls) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @amritagos, @sarats it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01745/joss.01745/10.21105.joss.01745.pdf)

**Comment by amritagos** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.21105/joss.00396 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1109/mcse.2010.118 is OK
- 10.1002/zamm.19800600129 is OK
- 10.2514/6.2019-2901 is OK
- 10.2514/6.2002-4482 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by sixpearls** [comment]
Hi @amritagos, @sarats, how are the reviews going? Thanks for opening the issue about the license, @amritagos, will wait to bulk process the changes.

CC'ing my co-author, @ixjlyons

**Comment by amritagos** [comment]
Hi @sixpearls, I have completed my review and am waiting for the issue to be resolved for my closing comments. Great work!

**Comment by amritagos** [comment]
@mbobra, I have completed my review and am certain that the work presented by @sixpearls and @ixjlyons is well within the JOSS purview. The work is in accordance with the rules and standards of JOSS and I am glad to recommend this for acceptance and subsequent publication. Thanks!

**Comment by mbobra** [comment]
Thank you, @amritagos!

**Comment by mbobra** [comment]
@whedon remind @sarats in one hour

**Comment by whedon** [comment]
Reminder set for @sarats in one hour

**Comment by whedon** [comment]
:wave: @sarats, please update us on how your review is going.

**Comment by sixpearls** [comment]
Thank you @amritagos!

**Comment by mbobra** [comment]
Reminder set for @sarats in one hour

**Comment by mbobra** [comment]
@whedon remind @sarats in one hour

**Comment by whedon** [comment]
Reminder set for @sarats in one hour

**Comment by whedon** [comment]
:wave: @sarats, please update us on how your review is going.

**Comment by sarats** [comment]
Nice work, good to go.

**Comment by mbobra** [comment]
Thank you, @sarats! (And congratulations!)

**Comment by mbobra** [comment]
@sixpearls We're almost there! Can you please [archive your release on Zenodo](https://guides.github.com/activities/citable-code/) to obtain a DOI and then put that DOI in your `readme.rst` file? Please make sure that the title and author list on the Zenodo archive match the title and author list of the JOSS paper. After that I think we're done 🎉

**Comment by mbobra** [comment]
👋@sixpearls Let me know if you need any help archiving your release on Zenodo!

**Comment by ixjlyons** [comment]
I've released version 0.1.1 of ndsplines and created a Zenodo entry for it: https://doi.org/10.5281/zenodo.3516465

Thank you @amritagos and @sarats for reviewing and @mbobra for editing!

**Comment by mbobra** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01745/joss.01745/10.21105.joss.01745.pdf)

**Comment by mbobra** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.21105/joss.00396 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1109/mcse.2010.118 is OK
- 10.1002/zamm.19800600129 is OK
- 10.2514/6.2019-2901 is OK
- 10.2514/6.2002-4482 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mbobra** [comment]
@whedon set 10.5281/zenodo.3516465 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3516465" target="_blank">10.5281/zenodo.3516465</a> is the archive.

**Comment by mbobra** [comment]
@whedon set 0.1.1 as version

**Comment by whedon** [comment]
OK. 0.1.1 is the version.

**Comment by mbobra** [comment]
@openjournals/joss-eics This paper is ready for acceptance! Nice work @sixpearls @ixjlyons 🎉

**Comment by kthyng** [comment]
Hi @sixpearls! It looks like the citations in your paper aren't working when you have more than one because you are using commas to separate multiple references — please update to use semicolons. Also, please go through your references file and use {} around any words that need to stay capitalized, like MATLAB. The {} preserve capitalization.

**Comment by sixpearls** [comment]
@whedon generate pdf

**Comment by sixpearls** [comment]
Hi @kthyng, thank you for catching that. My co-author @ixjlyons has made those corrections and it looks correct now. Let us know if there are any other corrections.

**Comment by kthyng** [comment]
Great! Sorry I didn't realize to mention both @sixpearls and @ixjlyons.

The paper is looking good!

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.21105/joss.00396 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1109/mcse.2010.118 is OK
- 10.1002/zamm.19800600129 is OK
- 10.2514/6.2019-2901 is OK
- 10.2514/6.2002-4482 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1053

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1053, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1187764788287430667) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1054
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01745](https://doi.org/10.21105/joss.01745)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats @sixpearls and @ixjlyons on your new paper!!  🎉 🎉 

Thanks very much to @amritagos and @sarats for your time and expertise as reviewers, and thanks to @mbobra for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01745/status.svg)](https://doi.org/10.21105/joss.01745)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01745">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01745/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01745/status.svg
   :target: https://doi.org/10.21105/joss.01745
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01745/status.svg)](https://doi.org/10.21105/joss.01745)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
