### ISSUE TITLE
[PRE REVIEW]: pentapy: A Python toolbox for pentadiagonal linear systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1747]
**Submitting author:** @MuellerSeb (<a href="http://orcid.org/0000-0001-9060-4008">Sebastian Müller</a>)
**Repository:** <a href="https://github.com/GeoStat-Framework/pentapy" target ="_blank">https://github.com/GeoStat-Framework/pentapy</a>
**Version:** v1.0
**Editor:** @drvinceknight
**Reviewers:** @inakleinbottle, @virgesmith

**Author instructions**

Thanks for submitting your paper to JOSS @MuellerSeb. **Currently, there isn't an JOSS editor assigned** to your paper.

@MuellerSeb if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01747/joss.01747/10.21105.joss.01747.pdf)

**Comment by kthyng** [comment]
Hi @drvinceknight! How about editing this for your first submission?

**Comment by MuellerSeb** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by drvinceknight** [comment]
> Hi @drvinceknight! How about editing this for your first submission?

Fantastic! :D 

@whedon assign @drvinceknight

**Comment by drvinceknight** [comment]
@whedon assign @drvinceknight as editor

**Comment by whedon** [comment]
OK, the editor is @drvinceknight

**Comment by drvinceknight** [comment]
Hi @inakleinbottle, [nice to see you at PyCon UK!] how do you feel about possibly reviewing this paper? 

Hi @virgesmith @jaroslavhron would you be interested in reviewing this paper?

It is presenting an implementation of two algorithms for solutions of [a particular type of] sparse linear systems.

If anyone has any questions about reviewing for JOSS there is documentation here https://joss.readthedocs.io/en/latest/reviewer_guidelines.html and I would be more than happy to discuss.

**Comment by drvinceknight** [comment]
Hi @inakleinbottle, [nice to see you at PyCon UK!] how do you feel about possibly reviewing this paper for JOSS? 

Hi @virgesmith @jaroslavhron would you be interested in reviewing this paper?

It is presenting an implementation of two algorithms for solutions of [a particular type of] sparse linear systems.

If anyone has any questions about reviewing for JOSS there is documentation here

**Comment by MuellerSeb** [comment]
Hey everybody,
thanks for caring about this submission. @drvinceknight: thanks for editing!
Another reviewer suggestion from my side: @nschloe (https://github.com/nschloe)

I am looking forward to the reviewing process.
Sebastian

**Comment by drvinceknight** [comment]
> Another reviewer suggestion from my side: @nschloe (https://github.com/nschloe)

Thank you for the suggestion @MuellerSeb! @nschloe if you're able to take on the review that would be fantastic 👍

**Comment by inakleinbottle** [comment]
I am happy to provide a review for the article.

**Comment by drvinceknight** [comment]
Wonderful: thank you @inakleinbottle.

@whedon assign @inakleinbottle as reviewer

**Comment by drvinceknight** [comment]
@whedon assign @inakleinbottle as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @inakleinbottle

**Comment by inakleinbottle** [comment]
I have completed my review, and opened an [issue](https://github.com/GeoStat-Framework/pentapy/issues/1#issue-497003090) on the submission repository detailing some issues that need to be addressed.

(Do I need to open a Review issue using Whedon?)

**Comment by drvinceknight** [comment]
That's fantastic @inakleinbottle, thank you.

Regarding the way forward, once I've gotten a positive response from a second reviewer (I'm just waiting a few days) I'll open a review issue in which you'll be able to proceed but what you've done already is fantastic and should make the further steps straightforward. Thank you again! :+1:

**Comment by virgesmith** [comment]
hi, sorry I just assumed one reviewer (that has been my experience of JOSS) and @inakleinbottle  beat me to it. Happy to review, but very unlikely I could submit my report before the end of the month, if this is OK

**Comment by drvinceknight** [comment]
That's ok @virgesmith, thank you for agreeing. I'll open a review issue now!

**Comment by drvinceknight** [comment]
@whedon add @virgesmith as reviewer

**Comment by whedon** [comment]
OK, @virgesmith is now a reviewer

**Comment by drvinceknight** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1759. Feel free to close this issue now!

**Comment by drvinceknight** [comment]
@virgesmith @inakleinbottle I'm going to close this issue, please complete the review on #1759

**Comment by nschloe** [comment]
Sorry for coming to the party late. I'm a bit swamped these days, so I'd be glad if the review could be done by someone else this time. Will be happy to review @MuellerSeb's (typically great) work in the future though!

**Comment by drvinceknight** [comment]
No problem @nschloe, thanks for responding, we're all set on this occasion but perhaps next time :+1:
