### ISSUE TITLE
[PRE REVIEW]: widgyts: Custom Jupyter Widgets for Interactive Data Exploration with yt

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1748]
**Submitting author:** @munkm (<a href="http://orcid.org/0000-0003-0117-5366">Madicken Munk</a>)
**Repository:** <a href="https://github.com/data-exp-lab/widgyts" target ="_blank">https://github.com/data-exp-lab/widgyts</a>
**Version:** v0.3.1
**Editor:** @lpantano
**Reviewers:** @harpolea , @KayleighRutherford

**Author instructions**

Thanks for submitting your paper to JOSS @munkm. **Currently, there isn't an JOSS editor assigned** to your paper.

@munkm if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01748/joss.01748/10.21105.joss.01748.pdf)

**Comment by kthyng** [comment]
Hi @lpantano! Would you be willing to edit this data viz and exploration based submission?

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
@KayleighRutherford, would yo like to review this tool?

**Comment by lpantano** [comment]
@a-slide, would you like to review this tool?

**Comment by a-slide** [comment]
Hi @lpantano.
I had a quick look at the tool and although it looks great I don't feel competent enough to review it.

**Comment by lpantano** [comment]
@munkm , do you have suggested reviewers?

**Comment by munkm** [comment]
I think @harpolea would be a good fit to review this paper.

**Comment by munkm** [comment]
@lpantano How many suggestions would be helpful?

**Comment by harpolea** [comment]
Hi @munkm @lpantano, I'd be happy to review this!

**Comment by lpantano** [comment]
@whedon assign @munkm as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @munkm

**Comment by lpantano** [comment]
@whedon assign @harpolea  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @harpolea

**Comment by lpantano** [comment]
@whedon add @KayleighRutherford as reviewer

**Comment by whedon** [comment]
OK, @KayleighRutherford is now a reviewer

**Comment by munkm** [comment]
@lpantano am I supposed to be a reviewer on my own paper?

**Comment by lpantano** [comment]
It was an error, I fixed it. Sorry about that.


On September 30, 2019 at 10:18:16 AM, Madicken Munk (
notifications@github.com) wrote:

@lpantano <https://github.com/lpantano> am I supposed to be a reviewer on
my own paper?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjournals/joss-reviews/issues/1748?email_source=notifications&email_token=AAML6HG4SZ2CXEMOMCRWK5LQMIDCRA5CNFSM4IYPTHS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD75ZUAY#issuecomment-536582659>,
or mute the thread

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1774. Feel free to close this issue now!
