### ISSUE TITLE
[PRE REVIEW]: LIBSDNN: A Selective Desensitization Neural Network Library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1749]
**Submitting author:** @BIPL-HORIE (<a href="http://orcid.org/0000-0001-7320-5478">和正 堀江</a>)
**Repository:** <a href="https://github.com/BIPL-HORIE/LIBSDNN" target ="_blank">https://github.com/BIPL-HORIE/LIBSDNN</a>
**Version:** v1.0
**Editor:** @arokem
**Reviewers:** @HaoZeke, @dirmeier

**Author instructions**

Thanks for submitting your paper to JOSS @BIPL-HORIE. **Currently, there isn't an JOSS editor assigned** to your paper.

@BIPL-HORIE if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1749 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:143:in `block in check_orcids': Problem with ORCID (0000-0000-0000-0000) for Atsuo Suemitsu (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:141:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:141:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:88:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kthyng** [comment]
Hi @arokem could you edit this submission?

**Comment by kthyng** [comment]
@BIPL-HORIE I think the paper isn't compiling because some of the ORCIDs haven't been filled in for co-authors.

**Comment by arokem** [comment]
Yes. I can take this one.

**Comment by arokem** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by arokem** [comment]
👋 @hiendn : would you be willing to review this paper for JOSS?

**Comment by arokem** [comment]
👋 @dirmeier : would you be willing to review this paper for JOSS?

**Comment by arokem** [comment]
👋 @nsaunier : would you be willing to review this paper for JOSS?

**Comment by hiendn** [comment]
My apologies, @arokem, I am away on vacation at the moment and can not handle this review (no laptop!). Hope that it goes smoothly!

**Comment by nsaunier** [comment]
Sorry, @arokem, I am not enough of an expert in that field and have several reviews late.

**Comment by dirmeier** [comment]
Hey @arokem, I can certainly give it a try. But I think it would be good to have a second reviewer (and third) on this one. Also I don't have a windows PC and the tool doesn't seem to have a description for installing on Unix systems ([here](https://github.com/BIPL-HORIE/LIBSDNN/blob/master/doc/Command%20line%20tools%20usage.pdf))

**Comment by arokem** [comment]
OK @dirmeier : I will assign you and continue looking for more reviewers. 

@hiendn : any chance you could take this on?

**Comment by arokem** [comment]
@whedon assign @dirmeier as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dirmeier

**Comment by hiendn** [comment]
Apologies @arokem, I am on vacation until mid-October without a proper laptop. I am going to have to pass on this occasion.

**Comment by arokem** [comment]
@BIPL-HORIE : do you have ideas for appropriate reviewers for this submission?

**Comment by arokem** [comment]
@BIPL-HORIE : it's been hard to find a second reviewer for this. Do you have ideas for appropriate reviewers for this submission?

**Comment by HaoZeke** [comment]
Hi. I would be willing to review this submission. @BIPL-HORIE and @arokem

**Comment by arokem** [comment]
Thanks!

**Comment by arokem** [comment]
@whedon assign @HaoZeke as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @HaoZeke

**Comment by arokem** [comment]
@BIPL-HORIE : any thoughts on a second potential reviewer?

**Comment by arokem** [comment]
@HaoZeke : once I have two reviewers lined up for this, I will start the review process for this paper.

**Comment by HaoZeke** [comment]
Sure, thanks @arokem.

**Comment by dirmeier** [comment]
I can't follow. With @HaoZeke and me there are two reviewers?

**Comment by arokem** [comment]
Whoops. I lost track of my papers. We are on. Let me start the review for this!

**Comment by arokem** [comment]
@whedon add @dirmeier as reviewer

**Comment by whedon** [comment]
OK, @dirmeier is now a reviewer

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1785. Feel free to close this issue now!

**Comment by arokem** [comment]
I am closing this issue now. 

@HaoZeke  and @dirmeier : please head over to #1785 for the review.
