### ISSUE TITLE
[PRE REVIEW]: highlightHTML: CSS Formatting of R Markdown Documents

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#175]
**Submitting author:** @lebebr01 (<a href="http://orcid.org/0000-0002-1265-8761">Brandon LeBeau</a>)
**Repository:** <a href="https://github.com/lebebr01/highlightHTML" target ="_blank">https://github.com/lebebr01/highlightHTML</a>
**Version:** v 0.1.3
**Editor:** @acabunoc
**Reviewer:** @desilinguist

**What this issue is for**

Thanks for submitting your paper to JOSS @lebebr01. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋  @acabunoc - would you be willing to edit this submission for JOSS?

**Comment by acabunoc** [comment]
yup!

**Comment by acabunoc** [comment]
@whedon assign @acabunoc as editor

**Comment by arfon** [comment]
@acabunoc - Whedon was being a bit slow the other day... Not sure why he didn't respond here 😕

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
OK, the editor is @acabunoc

**Comment by acabunoc** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by acabunoc** [comment]
Hey @nuest & @desilinguist 👋 ! would either of you be interested in reviewing this paper? It looks like you both have CSS + R experience. 

Also, @lebebr01 do you have any potential reviewers you can suggest? It's nice to have multiple reviewers

Review guidelines can be found here: http://joss.theoj.org/about#reviewer_guidelines

**Comment by lebebr01** [comment]
These two are not on the reviewer list, but perhaps @daattali or @sckott would be interested and I think would be good reviewers.

**Comment by acabunoc** [comment]
Thanks @lebebr01!

@daattali & @sckott - would love to have you as reviewers! For an idea of what you'd do, reviewer guidelines: http://joss.theoj.org/about#reviewer_guidelines

**Comment by desilinguist** [comment]
Sure I'd be happy to review :)

**Comment by acabunoc** [comment]
Sweet, thanks @desilinguist! 🎉

**Comment by acabunoc** [comment]
@whedon assign @desilinguist as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @desilinguist

**Comment by acabunoc** [comment]
I'll start the review now!

@nuest, @daattali or @sckott if any of you are interested in also reviewing (multiple reviewers is good!) let us know here and I'll add you to the review

**Comment by acabunoc** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by acabunoc** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/185. Feel free to close this issue now!

**Comment by daattali** [comment]
Hello! This package looks interesting, it's such a commonly needed tool.
Thanks for building it! I have a bit too much on my plate right now so as
terrible as this is for my PR, I'm going to stay out of the review process
and just wait to see it on CRAN :) Good luck!

---
Founder & Lead Consultant
AttaliTech Ltd
http://deanattali.com/shiny
