### ISSUE TITLE
[REVIEW]: FluxCalR: a R package for calculating CO2 and CH4 fluxes from static chambers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1751]
**Submitting author:** @junbinzhao (<a href="http://orcid.org/0000-0001-5142-4901">Junbin Zhao</a>)
**Repository:** <a href="https://github.com/junbinzhao/FluxCalR/" target ="_blank">https://github.com/junbinzhao/FluxCalR/</a>
**Version:** 0.1.0.
**Editor:** @arfon
**Reviewer:** @jhollist, @ha0ye
**Archive:** <a href="https://doi.org/10.5281/zenodo.3549398" target="_blank">10.5281/zenodo.3549398</a>

## Status

[![status](https://joss.theoj.org/papers/2ed7dce0968c5ae0cf1d00c942502ff8/status.svg)](https://joss.theoj.org/papers/2ed7dce0968c5ae0cf1d00c942502ff8)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2ed7dce0968c5ae0cf1d00c942502ff8"><img src="https://joss.theoj.org/papers/2ed7dce0968c5ae0cf1d00c942502ff8/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2ed7dce0968c5ae0cf1d00c942502ff8/status.svg)](https://joss.theoj.org/papers/2ed7dce0968c5ae0cf1d00c942502ff8)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/junbinzhao/FluxCalR/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jhollist & @ha0ye, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/junbinzhao/FluxCalR/">repository url</a>?
- [X] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@junbinzhao) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/junbinzhao/FluxCalR/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@junbinzhao) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jhollist, @ha0ye it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01751/joss.01751/10.21105.joss.01751.pdf)

**Comment by arfon** [comment]
@jhollist, @ha0ye - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by arfon** [comment]
:wave: @jhollist, @ha0ye - how are you both getting along with your reviews?

**Comment by jhollist** [comment]
About half way there.  Should be completed by tomorrow.

**Comment by ha0ye** [comment]
I have this planned for second half of the week - currently dealing with end of month deadlines.

**Comment by arfon** [comment]
👍 thanks for the updates both!

**Comment by jhollist** [comment]
First, nice job on the package.  

Added my checklist to the original post in this thread and in the items I did not check, I provided details over at https://github.com/junbinzhao/FluxCalR/issues/2.

Any questions let me know!

**Comment by ha0ye** [comment]
Nice work on a useful tool. The post-calculation graph was nicely done.

There were some checklist items that @jhollist already covered, so I only added comments where I had additional thoughts or suggestions for improvements, over in junbinzhao/FluxCalR#3

**Comment by arfon** [comment]
@junbinzhao - looks like there's a bunch of reasonable amount of feedback here from @jhollist & @ha0ye for you to work through.

Could you let us know when you've had a chance to review and incorporate their suggestions?

**Comment by junbinzhao** [comment]
@arfon & @jhollist & @ha0ye , Thank you for looking at the package! I roughly went through the comments and they look very helpful. I will find time to revise it this month. But since my calendar is bit tight recently, I'll try to finish revising early next month (November). 

Thank you again!

Cheers,

Junbin

**Comment by arfon** [comment]
> @arfon & @jhollist & @ha0ye , Thank you for looking at the package! I roughly went through the comments and they look very helpful. I will find time to revise it this month. But since my calendar is bit tight recently, I'll try to finish revising early next month (November).

Sounds good. I'll set a reminder for us all.

**Comment by arfon** [comment]
@whedon remind @junbinzhao in 5 weeks

**Comment by whedon** [comment]
Reminder set for @junbinzhao in 5 weeks

**Comment by junbinzhao** [comment]
@arfon I have finished the revision and all the updates are done in the github now. but I don't know how to submit the point-to-point responses to the reviews. Do I attach the file here directly? Thank you!

**Comment by junbinzhao** [comment]
@arfon @jhollist @ha0ye Thank you so much for the reviews! They are indeed very helpful and practical! I have revised the package as well as the paper accordingly. I believe they are now much improved. I have added the point-to-point responses under [@jhollist review](https://github.com/junbinzhao/FluxCalR/issues/2) and [@ha0ye review](https://github.com/junbinzhao/FluxCalR/issues/3). Please let me know your further comments! 

Thank you very much again!! 

Junbin

**Comment by arfon** [comment]
> @arfon I have finished the revision and all the updates are done in the github now. but I don't know how to submit the point-to-point responses to the reviews. Do I attach the file here directly? Thank you!

Ideally it would be good to respond right here in this issue (e.g. by quoting the reviewer feedback as I am doing above ☝️) followed by your response. Does that make sense?

**Comment by junbinzhao** [comment]
@jhollist Thank you so much for your suggestions! Please see below my response to each of the points. 

> First, nice job on the package!
> 
> Second, my review comments are detailed below for the [JOSS Review](https://github.com/openjournals/joss-reviews/issues/1751%3E) My comments below should match closely with the review checklist and in cases where I didn't check an item taking care of the comments here will satisfy that item.
> 
> ### General Comments
> * Swap tidyverse imports with specific packages.  Tidyverse is big and will install many packages not needed by FluxCalR and (perhaps) not wanted by your users. The specific ones I saw on a quick scan of your code were: magrittr, dplyr, lubridate, and assertthat.  Just specify those specifically in Imports:

**Response:** “tidyverse” is now removed from the list and replaced with other specific packages.
> 
> ### Functionality
> * When using FluxCal I get following Warning message.
> 
> > Warning message:
> > In x11(14, 10) :
> > Calls like 'x11(w, h)' are unsafe and should be replaced by 'x11(width=w, height=h)'
> 
> Lines 82 and 218 seem to be the source of this message. Clean up the code to get rid of this warning message.
> 
**Response:** the width and height have been spelled out in the function. 

> ### Documentation
> note: Much of the documentation is included in the required R documentation. There is some of this also in the README. I am not sure what the JOSS requirements are for amount of info in the README vs language specific documentation.
> 
> * Statement of need:
>   
>   * Did not see a clear statement of need in either the README or the R Package documentation.  Why is this package needed?  Are there other standard ways to load and calculate fluxes?  If not, then there's the need but if so, why an R package specifically.  I don't doubt the need for this kind of package, but needs to be stated.

**Response:** a clear statement of need is added to the Readme file under the heading “Why is the package needed?”, including the reasoning and other available software. In the paper, this is further illustrated in the second and third paragraphs. 

> * Installation instructions:
>   
>   * switch install directions from devtools::install_github() to remotes::install_github()

**Response:** “devtools” has been changed with “remotes”. 

> * Example usage:
>   
>   * In function level doc, but not in README?  See note above on clarification from JOSS
> * Functionality documentation:
>   
**Response:** examples in the help files are updated. More examples are added to a vignettes file. In the Readme, one example is added with graphical illustrations. 

>   * Function level documentation is good enough and the examples worked, but additional details on what is going on would be better.  I think the package documentation would be improved by a vignette that deals with the flux calculations a little bit more, how to select the END times, etc.

**Response:** A vignette file is added with examples of how to use each function under different scenarios. 

> * Automated tests:
>   
>   * No clear tests were included in the package.  These need to be added.  A good first place to look for guidance on this is http://r-pkgs.had.co.nz/tests.html

**Response:** tests are added and they run automatically on the Travic CI. 

> * Community guidelines:
>   
>   * Community guidelines were included in the README.  Also including a CONTRIBUTING.md is nice as some may look for guidelines there.  An example of a good one is at https://github.com/ropensci/drake/blob/master/CONTRIBUTING.md.  Not required but suggested.
> 
**Response:** the “CONTRIBUTING.md” is added which contains community contribution guidelines. 

> ### Software Paper
> * State of the field: Didn't see much discussion of how these calculations are typically done.  A little bit more about other methods that researchers use or if those aren't standardized point that out as well.

**Response:** in the paragraph 1-3, more information on the background and calculation is added and I also highlighted the niche and unique features of the “FluxCalR” package compared to others. 

> * Quality of writing:  Just a few small typos/editorial things:
>   
>   * Paragraph 1, line 2: "chamber is" to "chambers are" or maybe "The static chamber"
>   * Paragraph 1, line 3: "approach" to "approaches"
>   * Paragraph 1, lines 7-11: This sentence is awkward.  Should probably be broken up into two sentences.
>   * Paragraph 1, line 11: "calculate" doesn't seem right here.  Maybe change to "transfrom"?
>   * Paragraph 2, line 1: change "with static" to "with the static"
>   * Paragraph 2, line 3: change "multiple flexible" to "multiple, flexible"
>   * Paragraph 2, line 3: change "of" to "for"
>   * Paragraph 2, line 7: superscript on R^2^?
>   * Paragraph 2, line 7: change "within defined" to "within the defined"
>   * Paragraph 3, line 1: replace "e.g.," with ", for example,"
>   * Paragraph 3, line 7-8: replace "the post-data-analysis with the ready-calculated
>     fluxes" with "data analysis with the ready calculated fluxes"

**Response:** all the wordings have been revised accordingly.

**Comment by junbinzhao** [comment]
@ha0ye Thank you so much for your suggestions! Please see below my response to each of the points. 

> Hi,
> 
> This seems like a very handy tool for resolving a tedious aspect of computing fluxes from raw sensor data.
> 
> Below are the detailed comments for my [JOSS review](https://github.com/openjournals/joss-reviews/issues/1751):
> 
> ## Functionality:
> * `Load_LGR()`
>   
>   * The description needs some more details about the data processing that is occurring - is there cleaning, transformation, etc. that is occurring?

**Response:** the function mainly converts the timestamps into the one R can read and also removes unused lines in the raw data file. This description has been added into the help file. 

>   * the `Time_format` argument only takes a few values. Preferred style for handling this is using `match.arg()`, but in this case, I'd recommend re-using the `orders` argument from `lubridate::parse_date_time()` and passing the argument through.

**Response:** I revised the code with match.arg() and parse_date_time() added as suggested. Thank you!

> * `Load_Other`
>   
>   * I was a bit confused about the `Date` argument, in that it represents a constant date on which the measurements were made, if such data were not present in the file. Mainly because most of the other arguments refer to columns of the input data file. Maybe you could use some other argument naming scheme to indicate such (and then add a similar additional argument for temperature, instead of reusing `Ta` in multiple ways)

**Response:** I changed the date argument to “date_ms” standing for date of measurement to distinguish it from other argument that takes column names. “Ta” is kept as it was here, since it takes the column name of air temperature which is in line with other argument (e.g., time, CO2 and CH4). For the “Ta” in the function `FluxCal()`, I have changed it to “df_Ta”, indicating it takes a data frame instead of number or column name. 

>   * same comment re: `Time_format` as for `Load_LGR()`

**Response:** revised accordingly.

> * `FluxCal`
>   
>   * In interactive mode, there are no instructions about advancing past the manual selection. I had to look up the help on `identify` to figure out that I needed to click a different mouse button. Unfortunately this didn't work on my laptop, and I had to plug in a mouse. There needs to be instruction for how to proceed, as well as a more accessible option.

**Response:** I have added a more detailed instruction in the interactive graph and included two steps and clarified that the user should end the operation by clicking the “Stop” button on the top-left corner of the window. 

>   * Depending on how I selected peaks and valleys in interactive mode for the LGR example data, I got an error and the next figure failed to draw:
>   
>   ```
>   Error in if (Slm$r.squared > R2.CO2[a, 1]) { : 
>   missing value where TRUE/FALSE needed
>   In addition: Warning message:
>   ‘mode(display)’ differs between new and previous
>      ==> NOT changing ‘display’ 
>   ```
>   

**Response:** the error is caused by selecting a point that results in a failure in the regression. This error message has been added to Line 217 in the `FluxCal()` function and tested to be working. 

>   
>   
>   * In terms of output format, I wasn't sure what the index and time values referred to? The middle of the range that had the best linear R^2 or the start? I'd suggest using start and end values that bracket the range (this makes it easier to reproduce the linear regressions or tweak if necessary). I think the output would be easier to manipulate if CO2 and CH4 results were not in wide format, but long (since the columns are identical.

**Response:** the output format has been modified to include both the start and end time that each flux is calculated and used the long format. The index is removed to avoid confusion. 

>   * For the option to take in timing cues, it'd be more convenient to supply this as a data argument rather than a file, as this enables processing or generating the timing cues in R. Also, in the example, it looks like there is additional metadata (the `Plot` and `Light.Dark` columns) associated with the timing cues that is ignored. It would be great to include this as part of the output, for easier analysis purposes (than having to later match the output with the metadata in the timing file).

**Response:** Agree! I have modified the input of the time cues to be data frame instead of a file. In addition, I added an argument “other” to take the column names in the time cue data that can passed to the output. 

>   * Is the precision sufficient on the molar mass constants? Maybe the output needs to be rounded to the corresponding significant digits. (Oh, these values are not later used?)

**Response:** all the unused constants are now removed. An argument “digits” has been added so that the users can define by themselves. 

>   * There's some duplicated code that could be avoided:
>     
>     * calculate ylim manually if not provided, then use the same plotting code
>     * calculations for CO2 and CH4 are basically identical

**Response:** these duplicated codes have been built into functions and called afterwards. 

>   * The function is long, and subtasks can be handled by separate functions (e.g. generating the initial timing cues, the calculations, and then re-plotting or generating the output). A single function to do the flux calculations could be re-used for both CO2 and CH4, for example.

**Response:** the time cue selecting procedure has now been separated from the original `FluxCal()` function and incorporated into an independent function `SelCue()`. The new `FluxCal()` function is now specified to calculate the fluxes. In the `FluxCal()` function, I added an argument `cal` for the users to choose which gas flux (or both) to calculate. 

>   * Are there default values for `vol` and `Area` that would work? It's a bit awkward to have them be required arguments, but not at the front of the list of arguments. Maybe a unitless calculation could work?

**Response:** these arguments are the unique dimensions of the chambers used for the measurements. Therefore, they are different from case to case and should be entered by the users themselves. I have moved these two arguments up to 3rd and 4th place.  

> * The software paper mention that the analysis is "reproducible" -- but if the peaks and valleys are manually chosen, this seems to be non-reproducible. Perhaps you can add an option for selecting peaks and valleys to be turned into a timing cues data structure and output file, to make the calculations reproducible, with the manual interaction only needing to happen once.

**Response:** agree! I have added an argument `save` to automatically export the selected cues as a file that can be re-used later. 

> * You might try running `goodpractice::gp()` to look for additional issues. Not all of them are relevant for JOSS, but it can identify some general ways to improve the package.

**Response:** codes have been revised according to the suggestions returned from goodpractice::gp(). 

> 
> ## Code Style:
> * the naming style for arguments and functions is a bit inconsistent: e.g. the data-loading functions use Snake_case, while the main computation function is CamelCase. Function arguments sometimes begin with a capital letter, and sometimes do not.

**Response:** I have carefully revised the name style and used small case letter for argument (except for CO2, CH4 and Ta, which are conventions) and the CamelCase for function names. 

> * There are several "magic numbers" - constants used in calculation (frequency as 60 / sampling interval, celsius to kelvin conversion using 273.2, and column indices).

**Response:** column indices are replaced with the column names. Other constants are defined at the beginning of the code and called by the names afterwards. 

> 
> ## Error checking:
> * Since several of the function arguments refer to column names, some error checking with informative messages would be good to add, when a user makes a typo.

**Response:** error messages are added which are triggered when wrong column names are detected. 

> 
> ## Documentation:
> * roxygen has functionality to create link to other topics (e.g. `\link{\code{}}`). There are a few spots where this would be useful in the docs.

**Response:** links have been added to the help whenever other functions are mentioned. 

> * I agree that a simple vignette showing usage of the functions, perhaps with screenshots for the interactive portion, would help understand the workflow, as well as the input and output data structures.

**Response:** a vignette file is added with examples of using the functions under different scenarios. Screenshots are included also to demonstrate the interactive cue selecting graph and the check-up graph. 

> 
> ## Software paper:
> * editing wise, the only additional note I have to [@jhollist's list](https://github.com/junbinzhao/FluxCalR/issues/2) is:
>   Paragraph 1, line 4: "for" -> "because of".

**Response:** changed accordingly.

> * I'm not sure what about the process of computing fluxes is considered "subjective" and "objective". Isn't the selection of peaks and valleys by hand (or inputting timing cues) also subjective? I think you may want to focus on how your tool makes it easier to select the windows for calculation, and that optimizing for R^2 gets the most consistent outputs.

**Response:** agree! I have added more background information in the first three paragraphs and clarified the “gap” that this package fills and also highlighted the features this package has that facilitate the flux calculation. 

> * To add to [@jhollist's comment](https://github.com/junbinzhao/FluxCalR/issues/2) about the Statement of need, the description contained details that were difficult to distinguish as being relevant or not to the core problem. It would be better to have a simple statement about the problem of selecting measurement windows from the raw data; and then to include additional details about how the package is able to make use of air temperature for computing fluxes. I would save the description of efficiency and benefits of the package for the third paragraph, so that you have a clear description of the functionality first.

**Response:** according the suggestion, I explicitly explained the challenge of selecting the valid data and added the formula of flux calculation. The features of the packages have been moved down to the 5th paragraph. 

> * Improved precision in wording is needed in some places. What do you mean by "processing the manually measured fluxes"? From the examples and description, it seems like the sensor is automated, and the final output are flux calculations.

**Response:** here I removed the word “manually” to avoid confusion. 

> * Is the method of selecting the window with the highest R^2 a commonly accepted method, or compared against other methods? A reference to a methods paper feels warranted here.

**Response:** The flux calculation is based on the assumption that the gas concentration change follows a straight line (i.e., the flux rate is constant during the measurement period). Therefore, R2 of the linear regression is usually used to identify the quality of the measurement. Two references are added to support the idea.

**Comment by junbinzhao** [comment]
> > @arfon I have finished the revision and all the updates are done in the github now. but I don't know how to submit the point-to-point responses to the reviews. Do I attach the file here directly? Thank you!
> 
> Ideally it would be good to respond right here in this issue (e.g. by quoting the reviewer feedback as I am doing above ☝️) followed by your response. Does that make sense?

@arfon Thanks! I have copied my replies to here. Hope they are sufficient!

**Comment by arfon** [comment]
@jhollist, @ha0ye - please let me know when you've had a chance to review @junbinzhao's responses.

**Comment by whedon** [comment]
:wave: @junbinzhao, please update us on how things are progressing here.

**Comment by jhollist** [comment]
@arfon I have gone over the responses and it all looks great to me!

I have completed my checklist above and am happy to give a 👍 

Nice job on this package, @junbinzhao.

**Comment by junbinzhao** [comment]
@jhollist thank you so much for your comments again! Cheers!

**Comment by ha0ye** [comment]
@junbinzhao - Great job! Thanks for your hard work in improving the package and responding to our reviews. I have a few minor suggestions to look into:
* increment the version number on the package :)
* as flagged by `goodpractice::gp()` replace `1:nrow(` with `seq_len(nrow(`. This helps avoid errors in the loop if the number of rows is 0.
* do a pass of `devtools::check()` to identify various filenames to cleanup, undocumented arguments, etc. There are some new files that probably should be included in `.Rbuildignore`.
* Upon further inspection, I see that my confusion with the interactive method of selecting timing cues is due to using `x11` on a Mac operating system. (This further gets flagged by `devtools::check()`.) It would be good to dig around examples and documentation for detecting operating system and an interface that is compatible with different user setups.
  - For reference, here is the screenshot from my machine - it doesn't have the stop button, and I had to dig into the documentation for `identify()` to find out how to exit correctly. This was the issue I originally had with trying to interact on my laptop, which doesn't have a secondary mouse button:
> For the usual X11 device the identification process is terminated by pressing any mouse button other than the first. For the quartz device the process is terminated by pressing either the pop-up menu equivalent (usually second mouse button or Ctrl-click) or the ESC key.

![Screen Shot 2019-11-19 at 10 59 15 AM](https://user-images.githubusercontent.com/5835366/69163146-b597ad80-0abb-11ea-94ca-16bc1687799e.png)

**Comment by junbinzhao** [comment]
@ha0ye Thank you very much for testing the package and giving the comments! Here are how I revised the package: 

1. I have changed the version to 0.2.0
2. `1:nrow()` are now all replaced by `seq_len(nrow())`
3. I did the `check` and incorporated all the suggestions. Now it has zero error, warning or notes.
4. I have changed `x()` to `dev.new()` according to the suggestion from the `check` report. Now it should be compatible with systems other than windows as well. Also, I added an additional instruction to the second step in the cue selecting graph "(Mac users press 'Esc')". 

Please let me know if you have other concerns or have found other problems. 

Thank you!

Junbin

**Comment by ha0ye** [comment]
@junbinzhao, @arfon Looks great to me! 🎉 👍

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01751/joss.01751/10.21105.joss.01751.pdf)

**Comment by arfon** [comment]
@junbinzhao - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by junbinzhao** [comment]
@ha0ye Thank you so much again! I really appreciate your practical suggestions and I learnt a lot!

**Comment by junbinzhao** [comment]
@arfon Thank you! I have now created a new release and archived the package in Zenodo (DOI: 10.5281/zenodo.3549398). I also went through the paper again and added some funding sources and made a few edits. Please let me know how I can proceed from here.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3549398 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3549398" target="_blank">10.5281/zenodo.3549398</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1016/j.agrformet.2003.12.001 is OK
- 10.1111/gcb.13119 is OK
- 10.1111/gcb.13621 is OK
- https://doi.org/10.1016/j.agrformet.2019.04.012 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1114

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1114, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@junbinzhao - I have made a couple of small stylistic changes here: https://github.com/junbinzhao/FluxCalR/pull/4

**Comment by junbinzhao** [comment]
@arfon Thanks. Looks good to me!

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1016/j.agrformet.2003.12.001 is OK
- 10.1111/gcb.13119 is OK
- 10.1111/gcb.13621 is OK
- https://doi.org/10.1016/j.agrformet.2019.04.012 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1115

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1115, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01751/joss.01751/10.21105.joss.01751.pdf)

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1016/j.agrformet.2003.12.001 is OK
- 10.1111/gcb.13119 is OK
- 10.1111/gcb.13621 is OK
- https://doi.org/10.1016/j.agrformet.2019.04.012 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1116

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1116, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1197464995367456768) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1117
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01751](https://doi.org/10.21105/joss.01751)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@jhollist, @ha0ye - many thanks for your reviews here ✨ 

@junbinzhao - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01751/status.svg)](https://doi.org/10.21105/joss.01751)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01751">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01751/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01751/status.svg
   :target: https://doi.org/10.21105/joss.01751
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01751/status.svg)](https://doi.org/10.21105/joss.01751)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by junbinzhao** [comment]
@arfon @jhollist @ha0ye Thank you all again! All the best!
