### ISSUE TITLE
[PRE REVIEW]: tabula: An R Package for Analysis, Seriation and Visualization of Archaeological Count Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1754]
**Submitting author:** @nfrerebeau (<a href="http://orcid.org/0000-0001-5759-4944">Nicolas Frerebeau</a>)
**Repository:** <a href="https://github.com/nfrerebeau/tabula" target ="_blank">https://github.com/nfrerebeau/tabula</a>
**Version:** v1.3.0
**Editor:** @oliviaguest
**Reviewers:** @izaromanowska, @soodoku

**Author instructions**

Thanks for submitting your paper to JOSS @nfrerebeau. **Currently, there isn't an JOSS editor assigned** to your paper.

@nfrerebeau if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kthyng** [comment]
Hi @oliviaguest! Could you edit this submission?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01754/joss.01754/10.21105.joss.01754.pdf)

**Comment by oliviaguest** [comment]
@kthyng I am very far from having expertise in this area and am currently editing 3 others — does it matter? If not, then, sure. 😊

**Comment by kthyng** [comment]
@oliviaguest generally you don't need too much specific expertise, and you're on the lower end of editor load, but I know I've asked you to take on submissions this week!  I can try another editor first though.

@karthik this submission looks to be more in your area of expertise. Would you edit this submission?

**Comment by karthik** [comment]
@kthyng Sorry I dont have bandwidth to handle.

**Comment by kthyng** [comment]
@oliviaguest Could you take this on then after all? I'd appreciate it if possible!

**Comment by oliviaguest** [comment]
Yes, @kthyng. I am starting a new job and moving house this week and next week. Is it OK to have a bit of a delay?

**Comment by danielskatz** [comment]
Yes, let's go ahead and do that - I'll assign it you but with the recognition that there will be a ~2-week delay.
 
Dan (newly on-duty as JOSS AEiC this week)

**Comment by danielskatz** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by oliviaguest** [comment]
@danielskatz thank you!

**Comment by oliviaguest** [comment]
Hi 👋 @soodoku would you be interested and available to review this?

**Comment by oliviaguest** [comment]
@whedon add @izaromanowska as reviewer

**Comment by whedon** [comment]
OK, @izaromanowska is now a reviewer

**Comment by oliviaguest** [comment]
@soodoku I missed the thumbs up, I assume that's a yes? excellent!

**Comment by soodoku** [comment]
yup

**Comment by oliviaguest** [comment]
@whedon add @soodoku as reviewer

**Comment by whedon** [comment]
OK, @soodoku is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1821. Feel free to close this issue now!

**Comment by oliviaguest** [comment]
@izaromanowska, @soodoku :wave:

Please head on to the actual review here: #1821
