### ISSUE TITLE
[REVIEW]: GKNAP: A Java and C++ package for solving the multidimensional knapsack problem

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1756]
**Submitting author:** @shah314 (<a href="http://orcid.org/0000-0002-3770-1391">Shalin S Shah</a>)
**Repository:** <a href="https://github.com/shah314/gamultiknapsack" target ="_blank">https://github.com/shah314/gamultiknapsack</a>
**Version:** v1.6
**Editor:** @arfon
**Reviewer:** @sjvrijn, @stulacy
**Archive:** <a href="https://doi.org/10.5281/zenodo.3507931" target="_blank">10.5281/zenodo.3507931</a>

## Status

[![status](https://joss.theoj.org/papers/ad81323fff206ff0e8c6d205f6d0bb1d/status.svg)](https://joss.theoj.org/papers/ad81323fff206ff0e8c6d205f6d0bb1d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ad81323fff206ff0e8c6d205f6d0bb1d"><img src="https://joss.theoj.org/papers/ad81323fff206ff0e8c6d205f6d0bb1d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ad81323fff206ff0e8c6d205f6d0bb1d/status.svg)](https://joss.theoj.org/papers/ad81323fff206ff0e8c6d205f6d0bb1d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/shah314/gamultiknapsack" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sjvrijn & @stulacy, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/shah314/gamultiknapsack">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@shah314) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/shah314/gamultiknapsack">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@shah314) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @sjvrijn, @stulacy it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01756/joss.01756/10.21105.joss.01756.pdf)

**Comment by arfon** [comment]
@sjvrijn, @stulacy - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by stulacy** [comment]
Can you please add more documentation on how to use the program?

For example, be explicit in that you need to be in the `java/classes` directory to run the `java GeneticAlgorithm` command in the first place (imo executables should be in a high-level folder clearly marked, it took me a minute to find these).
Mention how to format your data into the .dat format required.
How to interpret the output (i.e. is it just printed out to standard out or can it be obtained programmatically from the java function?)
Are there any arguments to this or do you only ever need to run this exact command with a correctly formatted dataset in the same directory? 

One functional change that would be very much appreciated is the ability to pass in the filename of the data file rather than having to rename the file each time you want to run a different problem.

There's no mention of testing - how do I know the program is working correctly? I assume the default dataset in the `classes` folder is `Weing1` as I get the same output as mentioned in the README but this isn't explicitly stated anywhere.

Also mention how to install it. Are you expecting users to just run the compiled Java code themselves? If so what version of Java do they need? Are there any other dependencies?
The C++ version wouldn't compile for me, a truncated log is below. 

```
(base) stuart@bishy ~/repos/gamultiknapsack $ g++ cmultiknapsack.cpp
cmultiknapsack.cpp: In function ‘void processDataORLIB()’:
cmultiknapsack.cpp:691:15: error: ‘strtok’ was not declared in this scope; did you mean ‘strtoq’?
  691 |  char * tok = strtok(line, " ");
      |               ^~~~~~
      |               strtoq
cmultiknapsack.cpp:719:7: error: ‘strcmp’ was not declared in this scope
  719 |    if(strcmp(tok, " ") == 0 || strcmp(tok, "\n") == 0)
      |       ^~~~~~
cmultiknapsack.cpp:35:1: note: ‘strcmp’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
   34 | #include <time.h>
  +++ |+#include <cstring>
   35 | 
cmultiknapsack.cpp:764:16: error: ‘strcmp’ was not declared in this scope
  764 |             if(strcmp(tok, " ") == 0 || strcmp(tok, "\n") == 0)
      |                ^~~~~~
cmultiknapsack.cpp:764:16: note: ‘strcmp’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
cmultiknapsack.cpp:803:13: error: ‘strcmp’ was not declared in this scope
  803 |          if(strcmp(tok, " ") == 0 || strcmp(tok, "\n") == 0)
      |             ^~~~~~
cmultiknapsack.cpp:803:13: note: ‘strcmp’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
```

**Comment by shah314** [comment]
@stulacy I think I have addressed all of your suggestions. The code has much more documentation in the README.md.

I am now passing in the file name and the format for both Java and C++ versions.

The java/classes directory is only for convenience, but the user should really compile the code on their own machine. C++ should also compile now (I tested it on g++ version 8). There were some headers missing, which was ok when using the Mac C++ compiler, but you may be using some other version of g++. 

I have added some test scripts in the tests directory which will be helpful in understanding how the code works. I have also described the format of the file that the code expects.

There is no installation. Just compile the code and run. There are also no dependencies. 

To get the output programmatically, the user can look at the main methods in both the Java and C++ code. 

The Java code was tested using JDK 1.8 and the C++ code was tested using g++ version 8. I have added this to the README.

Please do a git pull and verify and review the changes.

**Comment by stulacy** [comment]
Thank you @shah314 , I feel the changes help make the software more user friendly.
My only remaining comment is that I cannot see anywhere where the difference between Orlib and Weing data encoding is explicitly stated. Would it be useful to have this information displayed somewhere?

**Comment by shah314** [comment]
Thank you. I have added links to the page where all files are described. The bottom of the page also contains a link to all files: http://people.brunel.ac.uk/~mastjjb/jeb/orlib/mknapinfo.html

**Comment by stulacy** [comment]
Thanks for the clarification. I am happy that all the requirements have been met 🙂

**Comment by shah314** [comment]
Thank you for the review @stulacy :)

**Comment by sjvrijn** [comment]
I have some remarks and questions:

Community Guidelines:
- CONTRIBUTING.md mentions 'graph coloring code' instead of gamultiknapsack
- How should interested third parties seek support? 

Paper 
- Summary:
  - [line 2-3] "It is a strongly NP-hard problem, and [it] might be difficult to solve [it] using ..." the "it"s in square brackets can be removed.
- Mathematics:
  - [line 8] expect a colon ':' before this formula, a trailing comma
  - [line 9] 'Where' should be lowercase, missing 'and' after the comma

  - [line 12] "Our method [...] is described in (Shah, 2019)" This seems to conflict with [Summary line 14-15] "Our algorithm is *similar to* (Shah, 2019)". Is there a difference? If so, what is it? 
  - [paragraph 6] The difference between cases with and without domain knowledge is described, but I cannot determine which case your algorithm is catering to. Is it domain-knowledge informed? If so, what domain knowledge is needed? I can't find this in the README either.
  
Repo documentation README
- [Cited by] How can your paper from 2019 be cited by two papers from 2012? What is being cited by whom exactly? I also cannot find the first of the two referenced papers.

**Comment by shah314** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01756/joss.01756/10.21105.joss.01756.pdf)

**Comment by shah314** [comment]
@sjvrijn Thank you for the comments. I think I have made the changes you suggested.

About the (Shah, 2019) reference, the algorithm is similar (not the same). The cited paper solves the 0/1 knapsack problem while this paper solves the multidimensional knapsack problem. So, though similar, the two applications are entirely different. I changed the text in the paper.

About domain knowledge, what I meant was that a utility ratio is available, which might not be available in other problems.

About the citations, this code was written in a very basic form several years back. The code was cited by these papers and not the paper. I am also not able to find the first of the two papers. To make this more current, I have removed the "Cited By" section of the README.

**Comment by shah314** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01756/joss.01756/10.21105.joss.01756.pdf)

**Comment by sjvrijn** [comment]
@shah314 Thanks for the updates, the paper and additional documentation files seem fine to me now.

I encountered two problems when running some test files on the Java version, for which I have opened Issues in the repository: [program hangs on simple case](https://github.com/shah314/gamultiknapsack/issues/2) and [NumberFormatException on float-input](https://github.com/shah314/gamultiknapsack/issues/3)

Additionally, some of the documentation comments around the input files in both the C++ and Java version seem to be outdated:

- GeneticAlgorithm.java line 26 mentions `ORLIB_FILE` while in the `weing`-format test
- cmultiknapsack.cpp lines 1508 and 1515 are identical (but don't seem to really add anything anyway)

Furthermore, the Java version also sets `Constants.DIFF_TOLERANCE = 5000;` (line 31) only for the orlib-files, but I can't find that same change being made in the C++ version. Is this intended behavior?

**Comment by shah314** [comment]
@sjvrijn I replied to the issues on the git repository page. I think I have fixed both issues (the number format exception and the code hanging). Please do a git pull and review and verify. Thank you for the detailed review.

**Comment by shah314** [comment]
@sjvrijn About the Constants.DIFF_TOLERANCE, it is not really required. But the distribution of the values in weing and orlib formats are quite different. So, I noticed that a lower value of DIFF_TOLERANCE sometimes causes the calculation of lagrangian multipliers to take a very long time for orlib formatted files. But the C++ code runs fine without it. No harm in keeping it there though.

**Comment by sjvrijn** [comment]
@shah314 Thanks for the fixes. 
@arfon That completes the checklist for me too.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@shah314 - could you remove the following line from the end of the paper as the repository is linked in the left-hand column:

```
The Java and C++ code are available here: https://github.com/shah314/gamultiknapsack.
```

Once you've made that update, could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by shah314** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01756/joss.01756/10.21105.joss.01756.pdf)

**Comment by shah314** [comment]
@arfon I have made the changes. Thanks.

The Zenodo DOI is 10.5281/zenodo.3507931

https://zenodo.org/record/3507931#.Xanj7pNKiL8

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3507931 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3507931" target="_blank">10.5281/zenodo.3507931</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1145/324138.324430 may be missing for title: A Monte Carlo study of genetic algorithm initial population generation methods
- https://doi.org/10.1016/s0045-7825(01)00323-1 may be missing for title: Theoretical and numerical constraint-handling techniques used with evolutionary algorithms: a survey of the state of the art

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1033

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1033, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1185303975291215873) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1034
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01756](https://doi.org/10.21105/joss.01756)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@sjvrijn, @stulacy - many thanks for your reviews here ✨ 

@shah314 - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01756/status.svg)](https://doi.org/10.21105/joss.01756)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01756">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01756/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01756/status.svg
   :target: https://doi.org/10.21105/joss.01756
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01756/status.svg)](https://doi.org/10.21105/joss.01756)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by shah314** [comment]
Thank you very much @arfon @stulacy @sjvrijn
