### ISSUE TITLE
[REVIEW]: MAESTROeX: A Massively Parallel Low Mach Number Astrophysical Solver

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1757]
**Submitting author:** @doreenfan (<a href="http://orcid.org/0000-0002-3246-4315">Duoming Fan</a>)
**Repository:** <a href="https://github.com/AMReX-Astro/MAESTROeX" target ="_blank">https://github.com/AMReX-Astro/MAESTROeX</a>
**Version:** 19.09
**Editor:** @arfon
**Reviewer:** @tukss, @pgrete
**Archive:** <a href="https://doi.org/10.5281/zenodo.3549070" target="_blank">10.5281/zenodo.3549070</a>

## Status

[![status](https://joss.theoj.org/papers/cc6e46383ed1d2bd2886ab29ff3cd4e4/status.svg)](https://joss.theoj.org/papers/cc6e46383ed1d2bd2886ab29ff3cd4e4)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/cc6e46383ed1d2bd2886ab29ff3cd4e4"><img src="https://joss.theoj.org/papers/cc6e46383ed1d2bd2886ab29ff3cd4e4/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/cc6e46383ed1d2bd2886ab29ff3cd4e4/status.svg)](https://joss.theoj.org/papers/cc6e46383ed1d2bd2886ab29ff3cd4e4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/AMReX-Astro/MAESTROeX" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@tukss & @pgrete, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/AMReX-Astro/MAESTROeX">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@doreenfan) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/AMReX-Astro/MAESTROeX">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@doreenfan) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @tukss, @pgrete it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@tukss, @pgrete - thanks again for agreeing to review this submission. Please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01757/joss.01757/10.21105.joss.01757.pdf)

**Comment by tukss** [comment]
I finished my review. Once the two outstanding issues are resolved, I am happy to accept this paper.

**Comment by arfon** [comment]
> I finished my review. Once the two outstanding issues are resolved, I am happy to accept this paper.

Excellent, thanks @tukss! 

@pgrete - how are you getting long with your review?

**Comment by pgrete** [comment]
I've been on the road for the past weeks but back in the office now and reserved time next week to finish the review.

**Comment by arfon** [comment]
> I've been on the road for the past weeks but back in the office now and reserved time next week to finish the review.

Excellent, thanks for the update!

**Comment by crawfordsm** [comment]
Do we have the JOSS DOI for this yet?

**Comment by tukss** [comment]
The proof PDF contains 10.21105/joss.01757, but it doesn't work yet. @arfon, can you comment if the DOI will change after acceptance?

**Comment by arfon** [comment]
> 10.21105/joss.01757

@crawfordsm ☝️ this will be the DOI.

**Comment by pgrete** [comment]
I'm trying to understand the contribution of @XinlongSBU specifically this commit bbbc157984b9c2
Is the changeset that large because of the different parent or is this a significant contribution to the code (I'm asking as  @XinlongSBU is not listed as author on the paper as far as I can tell).

**Comment by XinlongSBU** [comment]
Hi,

This is the commit that I want to modify Exec/SCIENCE/wdconvect
<https://github.com/XinlongSBU/MAESTROeX/commit/bbbc157984b9c26254cb54b1e9f100d4fabc3bdf#diff-1ecb3a9669f1bc882c83705728af8ec6>.
Other changes are mistakes. I don't think this is merged into
AMReX-Astro/MAESTROeX <https://github.com/AMReX-Astro/MAESTROeX>.

Best,
Xinlong

Philipp Grete <notifications@github.com> 于2019年10月17日周四 上午11:46写道：

**Comment by pgrete** [comment]
I'm done with my first pass of the review and opened issues for all things I spotted.

**Comment by arfon** [comment]
Great, thanks @pgrete. @doreenfan - looks like you've got a collection of feedback here to work through. Please let us know here when you've had a chance to make your updates.

**Comment by zingale** [comment]
@pgrete I think we've addressed most of the issues.  Can you take a look?

**Comment by pgrete** [comment]
Looks good so far. Just testing the testing and GPU instructions.

@arfon what's your take on " State of the field: Do the authors describe how this software compares to other commonly-used packages?" with respect o referring to the MAESTROeX paper instead, see https://github.com/AMReX-Astro/MAESTROeX/issues/107 ?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01757/joss.01757/10.21105.joss.01757.pdf)

**Comment by arfon** [comment]
> @arfon what's your take on " State of the field: Do the authors describe how this software compares to other commonly-used packages?" with respect o referring to the MAESTROeX paper instead, see AMReX-Astro/MAESTROeX#107 ?

Do you mean resolve this item by simply citing the AAS paper?

**Comment by pgrete** [comment]
Yes, that' what I meant.

Apart from this and the pending verification of the GPU capabilities this looks good to me.

**Comment by pgrete** [comment]
GPU functionality has been confirmed. Once there's a decision on the software paper related item, I'm happy to approve @arfon

**Comment by arfon** [comment]
> Yes, that' what I meant.

👍 confirming this is OK from my perspective.

**Comment by zingale** [comment]
okay, just to make sure I understand.  Is the suggestion that we add a cite to the ApJ MAESTROeX paper in the JOSS paper.md?

**Comment by arfon** [comment]
> okay, just to make sure I understand. Is the suggestion that we add a cite to the ApJ MAESTROeX paper in the JOSS paper.md?

Yes.

**Comment by pgrete** [comment]
IIRC the reference is already there and my question was around whether this satisfies the "State of the field: Do the authors describe how this software compares to other commonly-used packages?" item in the reviewing checklist.

**Comment by zingale** [comment]
okay, so does Arfon's answer mean that we satisfy your point @pgrete ?

**Comment by pgrete** [comment]
Yes, my previous comment was meant as a clarification for why I raised the point (I just wanted to double check with the editor if this in line with the interpretation of the review instructions).

**Comment by tukss** [comment]
Just checked that all my raised points are fixed and they are. Great!

I noticed that the first line of the bibliography reads:
> {% bibliography –cited –file paper.bib %}
I guess that's a bug somewhere in the processing of the PDF.

**Comment by arfon** [comment]
> I guess that's a bug somewhere in the processing of the PDF.

It's in the `paper.md` - @doreenfan please merge this pull request: https://github.com/AMReX-Astro/MAESTROeX/pull/123

**Comment by zingale** [comment]
just checking in on this -- I think we are all in sync now, right?  Is there anything else we need to do?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01757/joss.01757/10.21105.joss.01757.pdf)

**Comment by arfon** [comment]
@doreenfan @zingale - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by zingale** [comment]
Here's the Zenodo link: https://zenodo.org/record/3549070
DOI: http://doi.org/10.5281/zenodo.3549070

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3549070 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3549070" target="_blank">10.5281/zenodo.3549070</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1088/0067-0049/188/2/358 is OK
- 10.21105/joss.01370 is OK
- 10.5281/zenodo.2656476 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1112

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1112, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1197408270069239808) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1113
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01757](https://doi.org/10.21105/joss.01757)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@tukss, @pgrete - many thanks for your reviews here ✨ 

@zingale - I forgot to ask for the AAS DOI before accepting this so while the JOSS paper is accepted and published we'll need to add the AAS metadata to the submission too when we have it.

@crawfordsm - is the AAS paper accepted yet? If so, do we know what the DOI is?

**Comment by doreenfan** [comment]
The AAS paper has been accepted, but I'm not sure what the DOI is.

**Comment by arfon** [comment]
@doreenfan - can you merge this PR for me please? https://github.com/AMReX-Astro/MAESTROeX/pull/128

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1088/0067-0049/188/2/358 is OK
- 10.21105/joss.01370 is OK
- 10.5281/zenodo.2656476 is OK

MISSING DOIs

- https://doi.org/10.21105/joss.01757 may be missing for title: MAESTROeX: A Massively Parallel Low Mach Number Astrophysical Solver

INVALID DOIs

- None
```

**Comment by arfon** [comment]
OK, the paper is now updated with the AAS DOI information. Thanks again @tukss & @pgrete !

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01757/status.svg)](https://doi.org/10.21105/joss.01757)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01757">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01757/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01757/status.svg
   :target: https://doi.org/10.21105/joss.01757
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01757/status.svg)](https://doi.org/10.21105/joss.01757)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
