### ISSUE TITLE
[PRE REVIEW]: Distant Viewing Toolkit: A Python Package for the Analysis of Visual Culture

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1758]
**Submitting author:** @statsmaths (<a href="http://orcid.org/0000-0003-0576-0669">Taylor Arnold</a>)
**Repository:** <a href="https://github.com/distant-viewing/dvt" target ="_blank">https://github.com/distant-viewing/dvt</a>
**Version:** v0.3.0
**Editor:** @arfon
**Reviewers:** @jgonggrijp, @elektrobohemian

**Author instructions**

Thanks for submitting your paper to JOSS @statsmaths. The JOSS editor @arfon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@statsmaths if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@arfon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01758/joss.01758/10.21105.joss.01758.pdf)

**Comment by arfon** [comment]
:wave: @statsmaths thanks for your submission to JOSS. 

Could you suggest a few potential reviewers for your submission? This can be people you know of in the community, elsewhere on GitHub, or from [this list of potential reviewers](https://bit.ly/joss-reviewers).

**Comment by statsmaths** [comment]
Of course. Here are some names:

- @duhaime **Douglas Duhaime**
- @adavidzh **André David**
- @SeguinBe **Benoit Seguin**
- @jgonggrijp **Julian Gonggrijp**
- @ZoeLeBlanc **Zoe LeBlanc**

**Comment by arfon** [comment]
:wave: @duhaime @adavidzh @SeguinBe @jgonggrijp @ZoeLeBlanc - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by adavidzh** [comment]
> 👋 @duhaime @adavidzh @SeguinBe @jgonggrijp @ZoeLeBlanc - would any of you be willing to review this submission for JOSS?

I'm afraid that I cannot help this time around.

**Comment by jgonggrijp** [comment]
@arfon I would be willing, but I could only start November 11th at the earliest.

@statsmaths Out of curiosity, how did you find/know about me?

**Comment by arfon** [comment]
> @arfon I would be willing, but I could only start November 11th at the earliest.

Thanks @jgonggrijp. Is that OK with you timing-wise?

**Comment by statsmaths** [comment]
Waiting until 11 November would be fine. Maybe we could just wait a day to see if @duhaime might be willing (he reacted to the initial listing but is on New York time and likely has not seen the follow-up request yet). 

@jgonggrijp Thanks! I found you through the UU DH Lab website. I work with several DH colleagues at Utrecht (e.g., Jasmijn van Gorp), know of the university's strength in visual DH, and was trying to find someone technical to review the work. When I saw that you have some repositories in Python and JavaScript, seemed like a good fit. Hopefully you don't mind!

**Comment by duhaime** [comment]
@statsmaths @afron Thanks for the heads up on this! I wish I could help out, as the DVT will be useful to many researchers in @YaleDHLab, but my cup overfloweth at the moment. I'm glad @jgonggrijp can tackle this one!

**Comment by statsmaths** [comment]
Not a problem @duhaime, just didn't want to misinterpret your reaction from earlier!

Okay, let's just go with @jgonggrijp if still willing. Thanks again to everyone!

**Comment by arfon** [comment]
@whedon add @jgonggrijp as reviewer

**Comment by whedon** [comment]
OK, @jgonggrijp is now a reviewer

**Comment by arfon** [comment]
:zap: thanks for agreeing to review @jgonggrijp. I won't actually start the review issue here until we've found a second reviewer.

@statsmaths - I'd like to find another reviewer for this submission. If you can think of any other names I'd be grateful - I'll also do some digging.

**Comment by SeguinBe** [comment]
Hello,

Sorry I am currently in holidays at the moment, so just seeing this
thread now, I will have a closer look at it around the 14th to see if
I could squeeze it in my agenda.

**Comment by arfon** [comment]
:wave: @elektrobohemian - you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by elektrobohemian** [comment]
@arfon I would be. starting around end of October/November would be great because I have to finish some Master theses before.

**Comment by arfon** [comment]
> @arfon I would be. starting around end of October/November would be great because I have to finish some Master theses before.

OK thanks. I think that timing works. I'll go ahead and set up the review now and set a reminder for the end of October.

**Comment by arfon** [comment]
@whedon start review
