### ISSUE TITLE
[REVIEW]: pentapy: A Python toolbox for pentadiagonal linear systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1759]
**Submitting author:** @MuellerSeb (<a href="http://orcid.org/0000-0001-9060-4008">Sebastian Müller</a>)
**Repository:** <a href="https://github.com/GeoStat-Framework/pentapy" target ="_blank">https://github.com/GeoStat-Framework/pentapy</a>
**Version:** v1.0.2
**Editor:** @drvinceknight
**Reviewer:** @inakleinbottle, @virgesmith
**Archive:** <a href="https://doi.org/10.5281/zenodo.3474843" target="_blank">10.5281/zenodo.3474843</a>

## Status

[![status](https://joss.theoj.org/papers/57c3bbdd7b7f3068dd1e669ccbcf107c/status.svg)](https://joss.theoj.org/papers/57c3bbdd7b7f3068dd1e669ccbcf107c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/57c3bbdd7b7f3068dd1e669ccbcf107c"><img src="https://joss.theoj.org/papers/57c3bbdd7b7f3068dd1e669ccbcf107c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/57c3bbdd7b7f3068dd1e669ccbcf107c/status.svg)](https://joss.theoj.org/papers/57c3bbdd7b7f3068dd1e669ccbcf107c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/GeoStat-Framework/pentapy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@inakleinbottle & @virgesmith, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @drvinceknight know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/GeoStat-Framework/pentapy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@MuellerSeb) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/GeoStat-Framework/pentapy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@MuellerSeb) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @inakleinbottle, @virgesmith it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01759/joss.01759/10.21105.joss.01759.pdf)

**Comment by MuellerSeb** [comment]
Thanks everybody for the level-up!
Thanks @inakleinbottle for your detailed review. I will try to elaborate all your points.
Thanks @virgesmith for volunteering as reviewer.

**Comment by MuellerSeb** [comment]
My response to @inakleinbottle can be found here: https://github.com/GeoStat-Framework/pentapy/issues/1#issuecomment-534624645

**Comment by inakleinbottle** [comment]
I have a query for the editor: copied from my review
* You might need to include references (at the end of the paper) to the packages mentioned in your paper: numpy, scipy, Cython, perfplot. This needs to be clarified by the JOSS editors.

What is the policy regarding citation of software packages in references? I should comment that these are clearly acknowledged in the paper, but are not included in the list of references.

**Comment by drvinceknight** [comment]
Hi @inakleinbottle, good question, I note that `scipy` has been referenced however I feel that on this occasion references for `cython` and `perfplot` would be helpful for the reader (for example reading the paper myself I was not familiar with `perfplot`). 

I do not feel strongly about including a reference for `numpy` in the context of the text of the paper but I would suggest that it could be nice to include it for completeness.

Does that sound ok to you @MuellerSeb ?

**Comment by MuellerSeb** [comment]
@drvinceknight : Thank you for working out a way to go. I will include a reference to the github repositories of numpy and perfplot (numpy has no "real" code-publication and perfplot is a rather small package without any publications). In case of Cython, a dedicated publication exists.

**Comment by MuellerSeb** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01759/joss.01759/10.21105.joss.01759.pdf)

**Comment by MuellerSeb** [comment]
My response to @virgesmith can be found here: https://github.com/GeoStat-Framework/pentapy/issues/2#issuecomment-537114042

**Comment by virgesmith** [comment]
@drvinceknight I am happy to recommend this package now, @MuellerSeb has addressed all the points I raised.

**Comment by inakleinbottle** [comment]
@drvinceknight I too am now happy to recommend this package.

**Comment by drvinceknight** [comment]
Wonderful! Thank you all for your efforts and congratulations @MuellerSeb. :+1:

**Comment by drvinceknight** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2587158 is OK
- 10.1155/2015/232456 is OK
- 10.1007/978-3-319-43409-4 is OK
- 10.1002/hyp.10064 is OK
- 10.1109/MCSE.2010.118 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by MuellerSeb** [comment]
@virgesmith and @inakleinbottle thank you for your detailed reviews. That really helped to further improve the package! @drvinceknight thank you for being such a nice editor!
Thanks everybody!

**Comment by drvinceknight** [comment]
@openjournals/joss-eics this paper is ready to be accepted (unless I've missed something - this is my first paper as editor so please let me know if I'm forgetting something).

**Comment by MuellerSeb** [comment]
I will make a release of pentapy 1.0.1 that includes all changes to get a proper DOI.
This is in line with the paper, since Version 1.0 is mentioned there, so I think a newer PATCH release is ok.
(Maybe it could be a good hint for further papers to use a pre-released release candidate for the review)

**Comment by labarba** [comment]
👋 @drvinceknight — The pre-publication steps to request authors are:

- [ ] Please make a tagged release of your software, and list the version tag of the archived version here. 
- [ ] Archive the reviewed software in Zenodo 
- [ ] Check the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] Please list the Zenodo DOI of the archived version here.

**Comment by MuellerSeb** [comment]
Zenodo fails to release the 1.0.1 version... uargh!
I created an Issue: https://github.com/zenodo/zenodo/issues/1878
BUT: the DOI in the paper references the "general" Zenodo publication, that means, it always directs to the latest version. Is that ok?

**Comment by MuellerSeb** [comment]
@labarba I see. So I have to wait for Zenodo to resolve that issue.

**Comment by labarba** [comment]
The JOSS paper should link to the DOI for the _specific version_ or the Zenodo archive that corresponds to the software _as reviewed and improved_ for the JOSS publication (not the general DOI for all versions). 

Also, note that the Zenodo archive DOI is displayed in the margin decorators of the first page, and we thus request that you do not add it in your list of references. (It will also be included in the metadata of the Crossref deposit for the paper.)

**Comment by labarba** [comment]
@whedon set v1.0.2 as version

**Comment by whedon** [comment]
OK. v1.0.2 is the version.

**Comment by MuellerSeb** [comment]
OK, I will remove it from the list of references. Now we have to wait until someone from zenodo fixes my failed release. v1.0.2 was just to trigger another zenodo release (which again failed), but I will leave it that way.

**Comment by MuellerSeb** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01759/joss.01759/10.21105.joss.01759.pdf)

**Comment by MuellerSeb** [comment]
The DOI from Zenodo was now successfully created:
10.5281/zenodo.3474843

**Comment by MuellerSeb** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by MuellerSeb** [comment]
@labarba : I think that I have done everything on your list. How to proceed?

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.3474843 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3474843" target="_blank">10.5281/zenodo.3474843</a> is the archive.

**Comment by labarba** [comment]
I made some minor copy edits in https://github.com/GeoStat-Framework/pentapy/pull/3
Note that the paper has links to the source repository and Zenodo archive on the margin decorators of the first page, and we don't need that mentioned in the body text.

I wasn't sure what the abbreviated word was here: 
> backward resp. forward substitution

And finally, you present a figure with a performance test: it would be nice if you said what hardware you used for the test!

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01759/joss.01759/10.21105.joss.01759.pdf)

**Comment by MuellerSeb** [comment]
@labarba I merged your edits, removed the abbreviation and added the sys specs.

**Comment by MuellerSeb** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01759/joss.01759/10.21105.joss.01759.pdf)

**Comment by MuellerSeb** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01759/joss.01759/10.21105.joss.01759.pdf)

**Comment by MuellerSeb** [comment]
@labarba merged!

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1155/2015/232456 is OK
- 10.1007/978-3-319-43409-4 is OK
- 10.1002/hyp.10064 is OK
- 10.1109/MCSE.2010.118 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1010

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1010, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01759/joss.01759/10.21105.joss.01759.pdf)

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1181687525003411456) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1011
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01759](https://doi.org/10.21105/joss.01759)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @MuellerSeb, your JOSS paper is published! 🚀 

Huge thanks to our editor: @drvinceknight, and the reviewers: @inakleinbottle, @virgesmith — we couldn't do this without you 🙏

**Comment by labarba** [comment]
I'm not seeing the PDF yet, but the DOI resolves. I'll leave this issue open for now...

**Comment by MuellerSeb** [comment]
YEAH! Thanks @drvinceknight, @inakleinbottle, @virgesmith and @labarba for this pleasant review!
I see the PDF ;-)
This was a very nice experience!

**Comment by labarba** [comment]
👋 @arfon —The PDF is not showing in the embedded frame for me, even though the file does exist ... see: https://joss.theoj.org/papers/10.21105/joss.01759

**Comment by kyleniemeyer** [comment]
@labarba @arfon just confirming that I can see the PDF

**Comment by labarba** [comment]
I see it now. Closing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01759/status.svg)](https://doi.org/10.21105/joss.01759)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01759">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01759/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01759/status.svg
   :target: https://doi.org/10.21105/joss.01759
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01759/status.svg)](https://doi.org/10.21105/joss.01759)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
