### ISSUE TITLE
[PRE REVIEW]: pymccrgb: Color- and curvature-based classification of multispectral point clouds in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1760]
**Submitting author:** @rmsare (<a href="http://orcid.org/0000-0003-3711-6771">Robert Sare</a>)
**Repository:** <a href="http://github.com/rmsare/pymccrgb" target ="_blank">http://github.com/rmsare/pymccrgb</a>
**Version:** v0.1.0
**Editor:** @kthyng
**Reviewers:** @martibosch, @daniellivingston

**Author instructions**

Thanks for submitting your paper to JOSS @rmsare. **Currently, there isn't an JOSS editor assigned** to your paper.

@rmsare if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1760 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@rmsare  - it looks like the repo you entered doesn't exist - but it's just that the http:// was missing - I've added it now
@arfon - does this need to be changed in an internal database as well?

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1760 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1760 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
@rmsare - can you accept https://github.com/rmsare/pymccrgb/pull/14 and then enter a new comment in this issue ```@whedon generate pdf``` to see if that fixes the problem

**Comment by rmsare** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01760/joss.01760/10.21105.joss.01760.pdf)

**Comment by rmsare** [comment]
Ack, thank you @danielskatz for fixing these issues.

I'd like to note that one of the references -- Pedregosa et al, 2011 -- does not have a DOI. The [original JMLR article](http://www.jmlr.org/papers/volume12/pedregosa11a/pedregosa11a.pdf) and [arxiv version](https://ui.adsabs.harvard.edu/abs/2012arXiv1201.0490P/abstract) do not have DOIs and the article isn't available in CrossRef as far as I can tell.

**Comment by rmsare** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by danielskatz** [comment]
that's fine - you may want to mention this on the review thread once we get an editor and reviewers and we start the review

**Comment by danielskatz** [comment]
👋 @kthyng - would you be willing to edit this submission?

**Comment by kthyng** [comment]
@danielskatz for sure!

**Comment by kthyng** [comment]
@whedon assign @kthyng  as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
Hi @rmsare! Can you suggest around 5 possible reviewers from this list of volunteers: https://bit.ly/joss-reviewers?

**Comment by rmsare** [comment]
Thanks, I think Katherine Barnhart (kbarnhart), Margaux Mochene (margauxmouchene), Marti Bosch (martibosch), Joseph Stachelek (jsta), Declan Valters (dvalters) could be potential reviewers.

**Comment by kthyng** [comment]
Thanks!

Hi @margauxmouchene and @martibosch! Are you interested and able to review this JOSS submission in about the next three weeks? You can find more details [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

**Comment by martibosch** [comment]
Hello @kthyng , I'd be happy to review this submission :v:

**Comment by rmsare** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01760/joss.01760/10.21105.joss.01760.pdf)

**Comment by kthyng** [comment]
@martibosch great! I'll add you as a reviewer, but we'll need to wait to start the actual review until we have a second reviewer.

**Comment by kthyng** [comment]
@whedon assign @martibosch as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @martibosch

**Comment by kthyng** [comment]
Hi @callumrollo, @daniellivingston, and @banesullivan! I need one more reviewer for this JOSS submission. Are any of you interested in reviewing? We ask for reviews within about 3 weeks and you can get more information about the process and details here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by daniellivingston** [comment]
Hi @kthyng , I would be more than happy to review this submission.

**Comment by kthyng** [comment]
@daniellivingston perfect! We can proceed with this review then.

**Comment by kthyng** [comment]
@whedon add @daniellivingston as reviewer

**Comment by whedon** [comment]
OK, @daniellivingston is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1777. Feel free to close this issue now!

**Comment by banesullivan** [comment]
Hi @kthyng - looks like @daniellivingston beat me here! This library looks really cool and I'd be happy to review if needed (although a bit busy lately). Thanks for thinking of me! I'll definitely be scoping out this package and maybe finding a way to couple [PyVista](https://docs.pyvista.org) with it

**Comment by kthyng** [comment]
@martibosch and @daniellivingston head on over to #1777 to do your reviews.

@banesullivan Thanks for being willing to help out! I'll keep you in mind for the next relevant submission.

**Comment by sdruskat** [comment]
> \<AT\>rmsare - it looks like the repo you entered doesn't exist - but it's just that the http:// was missing - I've added it now 
> @arfon - does this need to be changed in an internal database as well?

Hi @arfon and @danielskatz, sorry to revive this after 4 years. I stumbled over the [live JSON representation](https://joss.theoj.org/papers/10.21105/joss.01777.json) of the metadata missing the protocol prefix for the `software_repository` field. I can catch this in my retrieval code, but should this be fixed in the DB?

![grafik](https://github.com/openjournals/joss-reviews/assets/3007126/93530a48-9dd3-497f-bb27-df54e5a8b3df)

Thanks!
