### ISSUE TITLE
[REVIEW]: Ryacas: A computer algebra system in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1763]
**Submitting author:** @mikldk (<a href="http://orcid.org/0000-0002-0234-0266">Mikkel Meyer Andersen</a>)
**Repository:** <a href="https://github.com/mikldk/ryacas" target ="_blank">https://github.com/mikldk/ryacas</a>
**Version:** v1.1.0
**Editor:** @drvinceknight
**Reviewer:** @MikeLydeamore, @EduPH
**Archive:** <a href="https://doi.org/10.5281/zenodo.3476220" target="_blank">10.5281/zenodo.3476220</a>

## Status

[![status](https://joss.theoj.org/papers/69b3947f8900504a25aa36f65d14500b/status.svg)](https://joss.theoj.org/papers/69b3947f8900504a25aa36f65d14500b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/69b3947f8900504a25aa36f65d14500b"><img src="https://joss.theoj.org/papers/69b3947f8900504a25aa36f65d14500b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/69b3947f8900504a25aa36f65d14500b/status.svg)](https://joss.theoj.org/papers/69b3947f8900504a25aa36f65d14500b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mikldk/ryacas" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@MikeLydeamore & @EduPH, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @drvinceknight know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mikldk/ryacas">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mikldk) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mikldk/ryacas">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mikldk) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @MikeLydeamore, @EduPH it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01763/joss.01763/10.21105.joss.01763.pdf)

**Comment by MikeLydeamore** [comment]
Hi @drvinceknight, I have completed my review and have recommend minor revisions. I've created an issue in the source repository that lists these: https://github.com/mikldk/ryacas/issues/32

**Comment by drvinceknight** [comment]
Thank you @MikeLydeamore :+1:

**Comment by mikldk** [comment]
Thanks, @MikeLydeamore , for your review and for helping making the package better by catching these shortages. I hope that commit mikldk/ryacas@777cf33459d9b8349b1863149182c38652b4b23b have addressed your points.

**Comment by EduPH** [comment]
> **Contribution and authorship:** Has the submitting author (@mikldk) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

@mikldk, I can see that there are more authors cited at the README of the repository. Should they be added?

> **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

I see a lot of examples of the use of Ryacas in the documentation. However, I think they could be described a little bit more. Some of them have no description at all (http://mikldk.github.io/ryacas/articles/low-level.html#sums) 

> **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
The same as the previous point. I understand that is based on yacas, so you can use yacas documentation as solid ground. But some parts of documentation are too many lines of codes without explanations. 

Typo in the paper:
Hoever -> However

--
However, I think that the documentation is useful, and your work is great and useful. Apart from this, I have no other objections to the publication.

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01763/joss.01763/10.21105.joss.01763.pdf)

**Comment by mikldk** [comment]
@EduPH, thanks for good comments! I have tried making a few corrections in documentation ([diff](https://github.com/mikldk/ryacas/commit/c8e4af65bd4d57c9c907840d78daed37e3393c51#diff-c87dadc225fad3d4b5c2429f3261b341)) and in the paper ([diff](https://github.com/mikldk/ryacas/compare/459fe7f200b044cae5fa3bb0ff8589cf42773653..7190e22b4019e0127c6f980708450aa8e45aa5b1)) as suggested. I have also updated `solve()` so that it works in general now ([docs](http://mikldk.github.io/ryacas/articles/high-level.html#solving-equations)). The author list is accurate.

**Comment by mikldk** [comment]
@drvinceknight I see that I wrote version 1.0.0, but it actually should be version 1.1.0. Is that something that you can change? Sorry about this.

**Comment by drvinceknight** [comment]
@whedon set v1.1.0 as version

**Comment by whedon** [comment]
OK. v1.1.0 is the version.

**Comment by drvinceknight** [comment]
That's taken care of @mikldk :+1:

**Comment by drvinceknight** [comment]
@EduPH everything is ticked off on your list except "Functionality documentation" if you could let me know when you're happy with that side of things that'd be great :+1:

**Comment by EduPH** [comment]
@drvinceknight , yes, everything is fine for me :)

**Comment by mikldk** [comment]
@drvinceknight: I have made a [release of v1.1.0](https://github.com/mikldk/ryacas/releases/tag/1.1.0) (via [a small commit](https://github.com/mikldk/ryacas/commit/d60287363844ef75f4dc5e339abc7bc6e588c14a)). I have archived this on Zenodo: <https://doi.org/10.5281/zenodo.3475813>. Let me know if I need to do more.

@EduPH and @MikeLydeamore: Thanks a lot for your help with a fast and thorough review.

**Comment by mikldk** [comment]
@drvinceknight: I have made a release of v1.1.0. I have archived this on Zenodo: https://zenodo.org/record/3476220 (DOI: [10.5281/zenodo.3476220](https://doi.org/10.5281/zenodo.3476220)). Let me know if I need to do more.

I also updated the package at CRAN: <https://CRAN.R-project.org/package=Ryacas>.

@EduPH and @MikeLydeamore: Thanks a lot for your help with a fast and thorough review.

**Comment by drvinceknight** [comment]
Great thanks @mikldk

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01763/joss.01763/10.21105.joss.01763.pdf)

**Comment by drvinceknight** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.7287/peerj.preprints.3188v1 is OK
- 10.1007/3-540-45470-5_29 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by drvinceknight** [comment]
@openjournals/joss-eics this paper is ready to be accepted

**Comment by labarba** [comment]
The software archive is still pending:

- [ ] Archive the reviewed software in Zenodo or a similar service
- [ ] Check the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] Please list the Zenodo DOI of the archived version here so we can update the metadata.

**Comment by mikldk** [comment]
@drvinceknight / @labarba: It is already on Zenodo: https://zenodo.org/record/3476220 (DOI: [10.5281/zenodo.3476220](https://doi.org/10.5281/zenodo.3476220)).

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.3476220 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3476220" target="_blank">10.5281/zenodo.3476220</a> is the archive.

**Comment by labarba** [comment]
Please edit the Zenodo archive's metadata so the title and author list matches the JOSS paper.

**Comment by drvinceknight** [comment]
> The software archive is still pending:

I had checked that @labarba (based on the checklist you circulated on a previous review) but please let me know if I could have made that clearer. (Should I have asked Whedon to archive as you did?).

> Please edit the Zenodo archive's metadata so the title and author list matches the JOSS paper

I see that I missed that. Apologies.

**Comment by mikldk** [comment]
> Please edit the Zenodo archive's metadata so the title and author list matches the JOSS paper.

@labarba @drvinceknight : This has now been done: <https://zenodo.org/record/3476220>.

**Comment by labarba** [comment]
> Should I have asked Whedon to archive as you did?

Yes, the handling editor runs the command `@whedon set <doi> as archive` before handing it over to AEiCs.

**Comment by mikldk** [comment]
> Please edit the Zenodo archive's metadata so the title and author list matches the JOSS paper.

@labarba @drvinceknight : This has now been done: <https://zenodo.org/record/3476220>.

**Comment by drvinceknight** [comment]
> Yes, the handling editor runs the command `@whedon set <doi> as archive` before handing it over to AEiCs.

Thanks, I also see where I missed that in the docs. Apologies for the trouble :+1:

**Comment by mikldk** [comment]
@labarba @drvinceknight : This has now been done: https://zenodo.org/record/3476220.

**Comment by mikldk** [comment]
> Please edit the Zenodo archive's metadata so the title and author list matches the JOSS paper.

@labarba @drvinceknight : This has now been done: <https://zenodo.org/record/3476220>.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.7287/peerj.preprints.3188v1 is OK
- 10.1007/3-540-45470-5_29 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1015

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1015, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1181996068537606144) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1016
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01763](https://doi.org/10.21105/joss.01763)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @mikldk, your JOSS paper is now published! 🚀 

Huge thanks to our editor: @drvinceknight, and the reviewers: @MikeLydeamore, @EduPH — your contribution to JOSS is greatly appreciated!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01763/status.svg)](https://doi.org/10.21105/joss.01763)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01763">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01763/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01763/status.svg
   :target: https://doi.org/10.21105/joss.01763
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01763/status.svg)](https://doi.org/10.21105/joss.01763)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by mikldk** [comment]
I would repeat after @whedon: Huge thanks to our editor @drvinceknight and the reviewers @MikeLydeamore and @EduPH -- your effort is greatly appreciated!

**Comment by drvinceknight** [comment]
A personal thank you to the editors from me: this doesn't happen without you. Congratulations @mikldk and a further personal thanks to @labarba for your patience and guidance :+1:
