### ISSUE TITLE
[PRE REVIEW]: memochange: An R package for estimation procedures and tests for persistent time series

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1765]
**Submitting author:** @KaiWenger (<a href="http://orcid.org/0000-0002-6566-0427">Kai Wenger</a>)
**Repository:** <a href="https://github.com/KaiWenger/memochange" target ="_blank">https://github.com/KaiWenger/memochange</a>
**Version:** v1.0.1
**Editor:** @mbobra
**Reviewers:** @JonasMoss, @steffilazerte

**Author instructions**

Thanks for submitting your paper to JOSS @KaiWenger. **Currently, there isn't an JOSS editor assigned** to your paper.

@KaiWenger if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01765/joss.01765/10.21105.joss.01765.pdf)

**Comment by danielskatz** [comment]
👋 @mbobra - Would you be willing to edit this JOSS submission?

**Comment by danielskatz** [comment]
👋 @mbobra - Would you be willing to edit this JOSS submission?

**Comment by mbobra** [comment]
@whedon assign @mbobra as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by mbobra** [comment]
@KaiWenger I'm sorry for the delay on this; I'm still looking for reviewers and hope to start the review in the next couple of days.

**Comment by JonasMoss** [comment]
@KaiWenger @mbobra I'd be happy to review this package! I can start working on the review in about a week.

**Comment by mbobra** [comment]
Great, thanks @JonasMoss! I will assign you as a referee and the review process will begin once I find a second referee.

**Comment by mbobra** [comment]
@whedon assign @JonasMoss as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @JonasMoss

**Comment by mbobra** [comment]
@whedon add @steffilazerte as reviewer

**Comment by whedon** [comment]
OK, @steffilazerte is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1820. Feel free to close this issue now!
