### ISSUE TITLE
[REVIEW]: bbsAssistant: An R package for downloading and handling data and information from the North American Breeding Bird Survey.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1768]
**Submitting author:** @trashbirdecology (<a href="http://orcid.org/0000-0002-0896-5099">Jessica Burnett</a>)
**Repository:** <a href="https://github.com/TrashBirdEcology/bbsAssistant/" target ="_blank">https://github.com/TrashBirdEcology/bbsAssistant/</a>
**Version:** v1.0
**Editor:** @kthyng
**Reviewer:** @ethanwhite , @jsta 
**Archive:** <a href="https://doi.org/10.5066/P93W0EAW" target="_blank">10.5066/P93W0EAW</a>

## Status

[![status](https://joss.theoj.org/papers/4b445373a7a7806c92e17bdd194a8e69/status.svg)](https://joss.theoj.org/papers/4b445373a7a7806c92e17bdd194a8e69)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4b445373a7a7806c92e17bdd194a8e69"><img src="https://joss.theoj.org/papers/4b445373a7a7806c92e17bdd194a8e69/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4b445373a7a7806c92e17bdd194a8e69/status.svg)](https://joss.theoj.org/papers/4b445373a7a7806c92e17bdd194a8e69)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/TrashBirdEcology/bbsAssistant/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ethanwhite  & @jsta , please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/TrashBirdEcology/bbsAssistant/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@trashbirdecology) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/TrashBirdEcology/bbsAssistant/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@trashbirdecology) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ethanwhite , @jsta  it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01768/joss.01768/10.21105.joss.01768.pdf)

**Comment by kthyng** [comment]
@ethanwhite Will you be able to work on your review soon?

**Comment by ethanwhite** [comment]
Apologies for they delay. I have it on my high priority list for this week.

**Comment by kthyng** [comment]
@ethanwhite Just a friendly ping here.

**Comment by ethanwhite** [comment]
Thanks @kthyng and apologies again. Hoping to get this done very soon.

**Comment by ethanwhite** [comment]
I've completed my checklist level review. Below are sections related to fixes for boxes that I haven't checked yet:

## Automated tests

* Two tests are currently failing in my local build for `test-get_regions.R`, but they seem to be passing on Travis so maybe I have a missing dependency or something. Ubuntu 18.04, R 3.6.1.

## Community Guidelines

* Contributing and CoC links were broken. Fixed in https://github.com/TrashBirdEcology/bbsAssistant/pull/65  
* No clear description of how to "Report issues or problems with software" or "Seek support". There is some language related to reporting issues in
  `CONTRIBUTING.md`.
  
## State of the field

There are two additional packages that contain some of the functionality described here:

1. `rBBS` - This  package is acknowledged as a source of some code, but no comparison is made to it in the paper.
2. [`rdataretriever`](https://github.com/ropensci/rdataretriever) (software by my group) - which downloads BBS and loads it into R. This package works on the entire integrated BBS dataset, does not support data manipulation, and does not work with the BBS analyses, so there are definitely meaningful differences from this package and therefore no conflict with publishing this software paper. However, it does have some meaningful overlap and so may be worth mentioning here. It is potentially a useful alternative for users looking to work with a full integrated version of the BBS data.

## References

* The `rBBS` package should be cited.
* If `rdataretriever` is added then it and the associated `retriever` package (https://doi.org/10.21105/joss.00451)

I have some additional suggestions related to the functionality of the package and the API, but those are out of scope for the JOSS review checklist so I will open them as issues over in the `bbsAssistant` repository. (I will try to remember to tag this issue in case there is interest in considering them as part of this review).

**Comment by kthyng** [comment]
Hi @TrashBirdEcology! Just want to make sure you saw that @ethanwhite has some recommendations for you for moving forward.

**Comment by TrashBirdEcology** [comment]
Indeed! Have been travelling, need to hop on this! Thanks to both of you!


Jessica L. Burnett

GitHub <http://github.com/trashbirdecology>
CV/Resume
<https://github.com/TrashBirdEcology/cv/blob/master/burnett_extendedCV.pdf>
ORC ID: 0000-0002-0896-5099 <https://orcid.org/0000-0002-0896-5099>

**Comment by TrashBirdEcology** [comment]
@ethanwhite -- I was trying to work with rdataretriever but couldn't figure it out (zero Py experience here). 

To use rdataretriever it seems (please correct me if I am wrong) one must have (a) Python installed and (b) understand how to make R and Python talk. It seems the bbsAssistant package requires only knowledge of R, whereas rdataretriever requires Py & R. 

Although I still intend to point out the existence of relevant packages (yours, rbbs, bbsbayes), I am not sure there is too much overlap to go beyond mentioning the package?

Thanks!

**Comment by TrashBirdEcology** [comment]
@ethanwhite @jsta  - we have addressed the unchecked boxes in your reviews (in [branch joss-round1](https://github.com/TrashBirdEcology/bbsAssistant/blob/joss-round1/), see below). 

We have done some major re-writing of code in /R/, which I hope makes the top-level functioning more intuitive. This is outlined in the [quick overview vignette](https://github.com/TrashBirdEcology/bbsAssistant/blob/joss-round1/vignettes/quick-overview.Rmd). 

We have also addressed  the issues you opened in the repository, with the exception of adding mapping features (a feature request by @jsta).

## @ethanwhite 
- Community guidelines enhanced by adding a [contributions.md](https://github.com/TrashBirdEcology/bbsAssistant/blob/joss-round1/CONTRIBUTIONS.md) and [codeofconduct.md](https://github.com/TrashBirdEcology/bbsAssistant/blob/joss-round1/CODE_OF_CONDUCT.md).  Will be pushed to master upon resubmission.
-  [Tests](https://github.com/TrashBirdEcology/bbsAssistant/blob/joss-round1/tests/) were updated. Happy to receive suggestions for improving testing. 

## @ethanwhite  and @jsta 
- A section, State of the Field, and better reference to the relevant packages have been added to the [paper.md](https://github.com/TrashBirdEcology/bbsAssistant/blob/joss-round1/paper/paper.md), and will be regenerated. 


We appreciate the time you have already taken to provide critical feedback on this package -- it has been greatly improved.

**Comment by ethanwhite** [comment]
@TrashBirdEcology - apologies for the difficulties with `rdataretriever` (don't see them in this issue any more, but got a email notification about them). The `retriculate` package that we rely on for talking to Python has introduced a number of bugs and we're in the midst of trying to mitigate these issues through improved installation instructions until they get them fixed. You current mention of this and other associated packages is all that's needed here.

@TrashBirdEcology @kthyng - these changes all look great and I very much appreciate the productive engagement both on these issues and suggestions related to design! It's been a pleasure working with you both. I've completed the rest of the check boxes and consider this software paper ready for publication.

**Comment by TrashBirdEcology** [comment]
Thanks, @ethanwhite!


Jessica L. Burnett

GitHub <http://github.com/trashbirdecology>
CV/Resume
<https://github.com/TrashBirdEcology/cv/blob/master/burnett_extendedCV.pdf>
ORC ID: 0000-0002-0896-5099 <https://orcid.org/0000-0002-0896-5099>

**Comment by jsta** [comment]
Looks good to me. The issues I raised with the initial review have all been addressed. Only thing I see remaining is that the paper still mentions the `feather` file format even though this functionality has been removed?

**Comment by TrashBirdEcology** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by TrashBirdEcology** [comment]
Yikes -- I guess I didn't push that edit.

This has been resolved @jsta.


Jessica L. Burnett

GitHub <http://github.com/trashbirdecology>
CV/Resume
<https://github.com/TrashBirdEcology/cv/blob/master/burnett_extendedCV.pdf>
ORC ID: 0000-0002-0896-5099 <https://orcid.org/0000-0002-0896-5099>

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01768/joss.01768/10.21105.joss.01768.pdf)

**Comment by TrashBirdEcology** [comment]
@whedon  generate pdf

**Comment by TrashBirdEcology** [comment]
Sorry people and Whedon! 

Fixed a typo....
@whedon generate pdf

**Comment by kthyng** [comment]
Great! I see the go-ahead from @ethanwhite. 

@jsta can you confirm that the recent change has resolved your last concern?

**Comment by jsta** [comment]
Looks good. :+1:

**Comment by kthyng** [comment]
Great! We can begin the final acceptance process then.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01768/joss.01768/10.21105.joss.01768.pdf)

**Comment by kthyng** [comment]
I read through the paper and made a few small fixed in [this PR](https://github.com/TrashBirdEcology/bbsAssistant/pull/85) if you want to merge.

**Comment by kthyng** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1650/CONDOR-17-83.1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
Forgot to look through your references before I made that PR so here is another: https://github.com/TrashBirdEcology/bbsAssistant/pull/86

**Comment by kthyng** [comment]
@TrashBirdEcology Can you make a tagged release and archive, and report the version number and archive DOI in this review thread?

**Comment by kthyng** [comment]
Sorry I should have been more specific, by "archive" I mean to submit your JOSS submission to Zenodo or similar for a DOI.

**Comment by TrashBirdEcology** [comment]
@kthyng, yes, I will archive on USGS, but that might take a few days. I will ping you as soon as this is complete.

**Comment by kthyng** [comment]
When you archive with USGS will it be the code and paper like you would with Zenodo? And you get a DOI?

Also in case it was lost in the mix, please do make a tagged release and we'll set that as the new version. Your original version number is ok but it should match a tagged release in github.

**Comment by TrashBirdEcology** [comment]
Yes, similar to Zenodo, including a DOI.

Not sure what is meant by 'tagged' release, however?

Jessica L. Burnett

GitHub <http://github.com/trashbirdecology>
CV/Resume
<https://github.com/TrashBirdEcology/cv/blob/master/burnett_extendedCV.pdf>
ORC ID: 0000-0002-0896-5099 <https://orcid.org/0000-0002-0896-5099>

**Comment by kthyng** [comment]
@TrashBirdEcology I'm following editor guidelines here: https://joss.readthedocs.io/en/latest/editing.html#after-reviewers-recommend-acceptance

And here is some information about making releases in github: https://help.github.com/en/github/administering-a-repository/creating-releases

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01768/joss.01768/10.21105.joss.01768.pdf)

**Comment by kthyng** [comment]
@TrashBirdEcology Looks like the changes to the references haven't made it through?

**Comment by TrashBirdEcology** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01768/joss.01768/10.21105.joss.01768.pdf)

**Comment by TrashBirdEcology** [comment]
@kthyng  the 
__DOI__:  10.5066/P93W0EAW (will take a couple of hours to be public).  
__Version release__: https://github.com/TrashBirdEcology/bbsAssistant/releases/tag/v1.0

DOI: 10.5066/P93W0EAW

**Comment by kthyng** [comment]
@whedon set v1.0 as version

**Comment by whedon** [comment]
OK. v1.0 is the version.

**Comment by kthyng** [comment]
@whedon set 10.5066/P93W0EAW as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5066/P93W0EAW" target="_blank">10.5066/P93W0EAW</a> is the archive.

**Comment by kthyng** [comment]
@TrashBirdEcology I'm not familiar with this archive setup. Normally with Zenodo I would go to the website of your submission there and make sure the title and author list match your paper. Can you do that for your archive?

**Comment by TrashBirdEcology** [comment]
@kthyng I apologies for being a difficult customer here, but I am not sure what you mean by this?  The DOI archive (https://doi.org/10.5066/P93W0EAW) contains a .zip file of the V1.0 release instance of the package.

**Comment by kthyng** [comment]
@TrashBirdEcology You're not being difficult at all! I see at your archive link now that your title and author list is consistent with your JOSS submission. I wanted to check that since it isn't always true.

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1650/CONDOR-17-83.1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1152

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1152, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1202247629582872577) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1153
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01768](https://doi.org/10.21105/joss.01768)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by TrashBirdEcology** [comment]
Ahh yes I see you referred to the title and authorship discrepancies. Apologies!!

**Comment by kthyng** [comment]
Congratulations on your new paper @TrashBirdEcology!!! Many thanks to reviewers @ethanwhite and @jsta for your time and expertise.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01768/status.svg)](https://doi.org/10.21105/joss.01768)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01768">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01768/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01768/status.svg
   :target: https://doi.org/10.21105/joss.01768
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01768/status.svg)](https://doi.org/10.21105/joss.01768)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by TrashBirdEcology** [comment]
> Congratulations on your new paper @TrashBirdEcology!!! Many thanks to reviewers @ethanwhite and @jsta for your time and expertise.

thank you for handling @kthyng
