### ISSUE TITLE
[PRE REVIEW]: LinkSmart Border Gateway: A single entry point into an Internet of Things autonomous system

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1769]
**Submitting author:** @janniswarnat (<a href="http://orcid.org/0000-0002-8233-309X">Jannis Warnat</a>)
**Repository:** <a href="https://github.com/linksmart/border-gateway" target ="_blank">https://github.com/linksmart/border-gateway</a>
**Version:** v1.5.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @janniswarnat. **Currently, there isn't an JOSS editor assigned** to your paper.

@janniswarnat if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01769/joss.01769/10.21105.joss.01769.pdf)

**Comment by danielskatz** [comment]
👋 @janniswarnat - While this looks like nice software and is well-described, I don't see how it is research software that would be suitable for JOSS. See https://joss.readthedocs.io/en/latest/submitting.html, specifically "The software should have an **obvious** research application."  If you disagree, please explain how this is research software.

**Comment by janniswarnat** [comment]
@danielskatz My institute is part of the German Fraunhofer Society that focuses specifically on "applied research", in the case of my department on innovative applications of IoT technology funded by the European Union´s Horizon 2020 programme. E.g. currently there is a project running in which we deploy different sensors during large open-air events and process the data live in a cloud environment to improve the event´s security, visitors´ experience and noise management. Border Gateway is useful to provide basic protection for these kinds of experimental IoT deployments.

So from your submission page I think it fits "supports [...] the execution of research experiments". It is of course up to you to decide how broadly you want to interpret this definition.

**Comment by danielskatz** [comment]
@janniswarnat - In our opinion, this does not currently qualify as research software, as it is presented in the repo and the paper. Therefore, we are going to mark it as rejected.  If you want to recast it as solving a research problem, feel free to resubmit.
