### ISSUE TITLE
[REVIEW]: AliasFinder: A Python script to search for the true planetary frequency within radial velocity data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1771]
**Submitting author:** @StephanStock (<a href="http://orcid.org/0000-0002-1166-9338">Stephan Stock</a>)
**Repository:** <a href="https://github.com/JonasKemmer/AliasFinder" target ="_blank">https://github.com/JonasKemmer/AliasFinder</a>
**Version:** v1.0.0
**Editor:** @xuanxu
**Reviewer:** @Juanlu001, @wtgee
**Archive:** <a href="https://doi.org/10.5281/zenodo.3608898" target="_blank">10.5281/zenodo.3608898</a>

## Status

[![status](https://joss.theoj.org/papers/aafabd6b2c8558da7608930332f927e3/status.svg)](https://joss.theoj.org/papers/aafabd6b2c8558da7608930332f927e3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/aafabd6b2c8558da7608930332f927e3"><img src="https://joss.theoj.org/papers/aafabd6b2c8558da7608930332f927e3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/aafabd6b2c8558da7608930332f927e3/status.svg)](https://joss.theoj.org/papers/aafabd6b2c8558da7608930332f927e3)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/JonasKemmer/AliasFinder" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Juanlu001 & @wtgee, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @xuanxu know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JonasKemmer/AliasFinder">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@StephanStock) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JonasKemmer/AliasFinder">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@StephanStock) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Juanlu001, @wtgee it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01771/joss.01771/10.21105.joss.01771.pdf)

**Comment by wtgee** [comment]
Hi @xuanxu  I don't see any code contributions from the submitting author (@StephanStock) despite them also being listed as first author. Can you advise? Thanks!

**Comment by xuanxu** [comment]
@wtgee Yeah, this is the response from @JonasKemmer to that same question:

>It seems that the only contributor to the software is JonasKemmer.

>>This is not the case, @StephanStock is the main contributer to the code, he just asked me to maintain the code, which is why all commits are from me. Most of the code was written before I joined the project. I just converted it into a publishable form.

**Comment by wtgee** [comment]
Hi @xuanxu. Regarding the **Functionality documentation**, I can see that most of the methods have appropriate docstrings but there is nothing like a link out to readthedocs. Is the requirement just regarding docstrings?

**Comment by xuanxu** [comment]
@wtgee There should be sufficient documentation to understand the functionality of the software, including a high-level overview in the readme file (see https://joss.readthedocs.io/en/latest/review_criteria.html#documentation). If you feel the included documentation is not enough you can always suggest improvements to the author, I think a link to readthedocs or similar is always convenient.

**Comment by xuanxu** [comment]
@wtgee, @Juanlu001: Friendly ping, how is that review going?

**Comment by StephanStock** [comment]
@xuanxu @wtgee @Juanlu001 If there is anything you want us to do, please let us know

**Comment by Juanlu001** [comment]
Sorry for the long delay and thanks @StephanStock for your patience, I finished the review. Some comments:


* It would be nice to add a git tag to the repository, to clearly signal what's `v1.0.0`.
* Regarding "Contribution and authorship", I ticket off the box [because of this comment](https://github.com/openjournals/joss-reviews/issues/1724#issuecomment-530867688):

> @StephanStock is the main contributer to the code, he just asked me to maintain the code, which is why all commits are from me. Most of the code was written before I joined the project. I just converted it into a publishable form.

* Regarding "Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?" -- The software is meant to be used as a command line tool and the configuration options are properly described in the example file, so I ticket this item off too.
* The repository contains no automated tests.
  - Perhaps the authors could consider reusing the `Example/` data to create an automatic test using https://github.com/matplotlib/pytest-mpl (to check that the result image matches https://github.com/JonasKemmer/AliasFinder/blob/master/Example/GJ436_2.64d_1.00297d_alias_test.png.
  - To make this automatic (for example, to be checked in every commit), it would require some infrastructure, for example https://travis-ci.org/.
* There is no comparison with other similar software, which suggests that there is probably no other commonly used packages. If that's the case, having it stated somewhere could be perhaps beneficial. "To our knowledge, there are no..."
* The script uses several [Python dependencies](https://github.com/JonasKemmer/AliasFinder#requirements), it would be nice to add corresponding citations to this paper (at least I know that astropy, numpy, matplotlib and SciPy have papers or references that can be cited)

Other than that, the script worked flawlessly, and when instructed to do so it leveraged all 4 cores in my machine. Nice work @StephanStock @JonasKemmer!

**Comment by xuanxu** [comment]
@wtgee: How is your review going?

**Comment by xuanxu** [comment]
@StephanStock / @JonasKemmer: Did you have the opportunity to address the [feedback from @Juanlu001](https://github.com/openjournals/joss-reviews/issues/1771#issuecomment-546592112)?

**Comment by StephanStock** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01771/joss.01771/10.21105.joss.01771.pdf)

**Comment by StephanStock** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01771/joss.01771/10.21105.joss.01771.pdf)

**Comment by StephanStock** [comment]
@Juanlu001 thank you for the review and positive feedback.

@xuanxu we have taken the reviews into account and marked changes in bold in the new paper.md file. 


1. We will include a git tag when the paper is accepted and define version 1.0.0 
as the version which was accepted. 

2. Regarding the request for automated testing, we think that this is not feasible for our script 
for the moment. The provided example can be used as a manual test. We will include in the README, how the data can be downloaded when pip install is used. 

3. We included the following sentence as suggested by @Juanlu001:

"To our knowledge, there are no other public packages to perform alias testing based on this methodology."

Thanks to the referee for this suggestion!

4. We have added all the appropriate citations to for the packages which we use.

Thanks to @xuanxu  for keeping track of this. If there is anything else we should do, please let us know.

**Comment by StephanStock** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01771/joss.01771/10.21105.joss.01771.pdf)

**Comment by xuanxu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1051/0004-6361:200811296 is OK
- 10.1088/0004-637X/722/1/937 is OK
- 10.1051/0004-6361/201731442 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1051/0004-6361/201322068 is OK
- 10.21105/joss.01277 is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by StephanStock** [comment]
@xuanxu we are a bit worried that @wtgee did not respond to any message since September 30th.

How should we proceed?

**Comment by xuanxu** [comment]
@StephanStock 
>     1. We will include a git tag when the paper is accepted and define version 1.0.0
>        as the version which was accepted.

That's OK. I'll ask you for it when needed.

>     2. Regarding the request for automated testing, we think that this is not feasible for our script
>        for the moment. The provided example can be used as a manual test. We will include in the README, how the data can be downloaded when pip install is used.

OK, if automated tests are not in place, some form of manual procedure to test the functionality of the software should be included. Please document that (in the README is OK, in a separate file linked from the README is also OK).

> we are a bit worried that wtgee did not respond to any message since September 30th.

I've contacted him via email, I hope he'll provide an update soon.

**Comment by JonasKemmer** [comment]
Hello @xuanxu and @Juanlu001,
thanks for your comments. Instructions for manual testing are now included in the README.

**Comment by Juanlu001** [comment]
Looks good to me!

**Comment by xuanxu** [comment]
@wtgee Just a friendly ping here.

**Comment by wtgee** [comment]
Hi folks,

My sincere apologies for the ridiculous delay. Also thanks to @Juanlu001 for earlier reviews. The repository looks much improved from when I had first reviewed it before.  I agree that this is ready, just a few comments:

* Obviously I would like to see automated testing and encourage the authors to get in the future habit of developing tests as you develop software.
* There is a `contributing.md` but no reference on the main landing page about how to contribute or help, etc. Maybe just a small section at the bottom that links to the contributing doc and has some standard "If you want to help..." text.
* There are a number of spelling and grammatical mistakes in the JOSS paper still. I know I'm not supposed to do direct PRs, but it was just as easy to edit the document as to mark where the errors were: https://github.com/JonasKemmer/AliasFinder/pull/8

Other:
* The final plot now includes the Period as the secondary x-axis, which is helpful. Should update the plot on the github page to reflect that.
* The final plot might also be more informative with the residuals plotted. I'm not entirely sure what that would look like (maybe a 4th column with all the residuals from the row?) and don't think you need it for this version, but just a suggestion.

Other than that, things look great! Apologies again for the delay!

**Comment by JonasKemmer** [comment]
Hey @wtgee,
also thanks to you for your comments. Automated testing is for sure on our bucket list, however at this stage not feasible to implement. We added a reference to the `contributing.md` in the `README.md` as suggested and also included some of your spelling and grammar corrections, where we found it appropriate. Also we updated the example plot. Regarding your comment on the residual plot: we are currently investigating the possibility to include a metric to quantify the differences between data and simulation. For that we will sure make use of the residuals. All the best, Jonas and Stephan

**Comment by wtgee** [comment]
Great, thanks @JonasKemmer for the updates.  I realize automated testing wasn't going to make it in, just wanted to encourage you for the future.

@xuanxu I've checked off all my items. I see that @Juanlu001 still has a few checkboxes to fill but I think they had already given the signoff.  Everything looks good to me know as well.

Sorry again for the delay!

**Comment by Juanlu001** [comment]
I ticket off my remaining boxes :muscle:

**Comment by StephanStock** [comment]
Thank you @wtgee and @Juanlu001 for your feedback. It significantly helped to improve this software.

**Comment by StephanStock** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01771/joss.01771/10.21105.joss.01771.pdf)

**Comment by xuanxu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1051/0004-6361:200811296 is OK
- 10.1088/0004-637X/722/1/937 is OK
- 10.1051/0004-6361/201731442 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1051/0004-6361/201322068 is OK
- 10.21105/joss.01277 is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01771/joss.01771/10.21105.joss.01771.pdf)

**Comment by StephanStock** [comment]
There are still some textpassages in the paper in boldface, can we now make them normal?

**Comment by xuanxu** [comment]
> There are still some textpassages in the paper in boldface, can we now make them normal?

@StephanStock Yes, go ahead and please tell whedon to generate the pdf when ready

**Comment by JonasKemmer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01771/joss.01771/10.21105.joss.01771.pdf)

**Comment by xuanxu** [comment]
OK @JonasKemmer, everything looks good, here are the next steps:

- Please release a [tagged version](https://github.com/JonasKemmer/AliasFinder/releases) from the current master so it includes all the changes made during the review process
- Then archive that latest release in Zenodo
- Check the Zenodo deposit has the correct metadata: title and author name should match the paper; you may also add your ORCID.

Once you do that please report here the version number and archive DOI

**Comment by JonasKemmer** [comment]
Hey @xuanxu, we uploaded the release v1.0 to Zenodo, you can find it here: http://doi.org/10.5281/zenodo.3608898

**Comment by xuanxu** [comment]
@whedon set 10.5281/zenodo.3608898 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3608898" target="_blank">10.5281/zenodo.3608898</a> is the archive.

**Comment by xuanxu** [comment]
Everything is ready 🎉
@openjournals/joss-eics sending it your way for final acceptance! 🚀

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1051/0004-6361:200811296 is OK
- 10.1088/0004-637X/722/1/937 is OK
- 10.1051/0004-6361/201731442 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1051/0004-6361/201322068 is OK
- 10.21105/joss.01277 is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @StephanStock, I'm doing some final checks on the article before publication.

In the references, it looks like the journal/publication venue is missing for a few: both Astropy articles, Dawson, Trifonov, and Zechmeister. Can you check on that?

**Comment by kyleniemeyer** [comment]
Some other minor fixes:
- please add commas after "e.g." -> `e.g.,`
- In the second paragraph, change the Trifonov in-text reference to use the `@author:2001` formatting to remove the parentheses—it will appear like "Trifonov et al. (2018)"

**Comment by JonasKemmer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01771/joss.01771/10.21105.joss.01771.pdf)

**Comment by JonasKemmer** [comment]
@kyleniemeyer nice catch with the references, we updated the files. We also corrected the spelling errors in the paper. Thanks for letting us know.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1051/0004-6361:200811296 is OK
- 10.1088/0004-637X/722/1/937 is OK
- 10.1051/0004-6361/201731442 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1051/0004-6361/201322068 is OK
- 10.21105/joss.01277 is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1227

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1227, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1217850801676222464) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1228
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01771](https://doi.org/10.21105/joss.01771)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @StephanStock on your article's publication in JOSS! 

Thanks to @Juanlu001 and @wtgee for reviewing this, and @xuanxu for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01771/status.svg)](https://doi.org/10.21105/joss.01771)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01771">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01771/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01771/status.svg
   :target: https://doi.org/10.21105/joss.01771
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01771/status.svg)](https://doi.org/10.21105/joss.01771)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
