### ISSUE TITLE
[PRE REVIEW]: simode: R Package for Statistical Inference of Ordinary Differential Equations using Separable Integral-Matching

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1772]
**Submitting author:** @ramiyaari (<a href="http://orcid.org/0000-0002-8808-8937">Rami Yaari</a>)
**Repository:** <a href="https://github.com/ramiyaari/simode/" target ="_blank">https://github.com/ramiyaari/simode/</a>
**Version:** v1.1.6
**Editor:** @mjsottile
**Reviewers:** @cscherrer, @jgoldfar, @osorensen

**Author instructions**

Thanks for submitting your paper to JOSS @ramiyaari. **Currently, there isn't an JOSS editor assigned** to your paper.

@ramiyaari if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #1772 with the following error: 

 Could not find bibliography file: simode.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
@ramiyaari - I see some high-level issues here:

* no readme
* no license

Please see https://joss.readthedocs.io/en/latest/submitting.html#typical-paper-submission-flow

Also, in your paper, you say the bib is "bibliography: simode.bib" but it's actually "paper.bib" - please fix this, then enter ```@whedon generate pdf``` as a new comment in this issue to recompile.

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1772 with the following error: 

 Error producing PDF.
! LaTeX Error: Bad math environment delimiter.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.466 \begin{equation}

Looks like we failed to compile the PDF

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1772 with the following error: 

 Error producing PDF.
! Missing \endgroup inserted.
<inserted text> 
                \endgroup 
l.482 \begin{eqnarray}

Looks like we failed to compile the PDF

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@danielskatz thanks for your comments
I believe I fixed all these issues

**Comment by ramiyaari** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by ramiyaari** [comment]
Please update the software version to 1.1.6
Suggested Reviewers: Jgoldfar, trashbirdecology, MikeLydeamore, MaaniBeigy, llauriciu, matloff, ellessenne, osorensen, RomainAzais

**Comment by danielskatz** [comment]
@whedon set v1.1.6 as version

**Comment by whedon** [comment]
OK. v1.1.6 is the version.

**Comment by danielskatz** [comment]
I still don't see a readme or a license in the source repo.

**Comment by ramiyaari** [comment]
There is a README.txt and a LICENSE.txt file under inst/joss in the repo, together with paper.md

**Comment by ramiyaari** [comment]
@danielskatz: There is a README.txt and a LICENSE.txt file under inst/joss in the repo, together with paper.md

**Comment by danielskatz** [comment]
These need to be at the top level of the repo

**Comment by ramiyaari** [comment]
OK, fixed it

**Comment by labarba** [comment]
👋 @mjsottile — Could you handle this submission as editor?
**simode: R Package for Statistical Inference of Ordinary Differential Equations using Separable Integral-Matching**
Repository: https://github.com/ramiyaari/simode/

**Comment by mjsottile** [comment]
Yes, I can take this submission as editor.

**Comment by labarba** [comment]
@whedon assign @mjsottile as editor

**Comment by whedon** [comment]
OK, the editor is @mjsottile

**Comment by mjsottile** [comment]
👋@cscherrer would you be interested in reviewing this paper?

**Comment by mjsottile** [comment]
@whedon add @cscherrer as reviewer

**Comment by whedon** [comment]
OK, @cscherrer is now a reviewer

**Comment by mjsottile** [comment]
@whedon assign @cscherrer as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @cscherrer

**Comment by mjsottile** [comment]
Other possible reviewers from the spreadsheet: @jgoldfar - you appear to have knowledge of differential equations and R. @fabian-s - you appear to have knowledge of R and inference methods.  Interested in taking this on to help review?

**Comment by jgoldfar** [comment]
I would be able to take this on at the beginning of November; I'd be happy to help if there is still a need for review.

**Comment by mjsottile** [comment]
Thanks @jgoldfar.  That timeline should be fine in November.

**Comment by mjsottile** [comment]
@whedon add @jgoldfar as reviewer

**Comment by whedon** [comment]
OK, @jgoldfar is now a reviewer

**Comment by mjsottile** [comment]
Hi, @trashbirdecology, @MikeLydeamore, @MaaniBeigy, @llauriciu, @matloff, @ellessenne, @osorensen, @RomainAzais - you were suggested as potential reviewers for this JOSS submission.  Let me know if you're interested in reviewing this submission.  I am looking for at least one reviewer to add before I start the review process.

**Comment by osorensen** [comment]
Yes, I am interested.

**Comment by MaaniBeigy** [comment]
Yes, I am interested.

**Comment by MaaniBeigy** [comment]
Yes, I am interested

**Comment by mjsottile** [comment]
Thanks @osorensen - I'll add you.  @MaaniBeigy , I will hold off adding you unless we need an additional reviewer during the process.

**Comment by mjsottile** [comment]
@whedon add @osorensen as reviewer

**Comment by whedon** [comment]
OK, @osorensen is now a reviewer

**Comment by mjsottile** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1850. Feel free to close this issue now!

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)

**Comment by ramiyaari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01772/joss.01772/10.21105.joss.01772.pdf)
