### ISSUE TITLE
[REVIEW]: PYCV: a PLUMED 2 Module Enabling the Rapid Prototyping of Collective Variables in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1773]
**Submitting author:** @tonigi (<a href="http://orcid.org/0000-0001-6449-0596">Toni Giorgino</a>)
**Repository:** <a href="https://github.com/giorginolab/plumed2-pycv/" target ="_blank">https://github.com/giorginolab/plumed2-pycv/</a>
**Version:** v1.1
**Editor:** @arfon
**Reviewer:** @amritagos, @carlocamilloni
**Archive:** <a href="https://doi.org/10.5281/zenodo.3480171" target="_blank">10.5281/zenodo.3480171</a>

## Status

[![status](https://joss.theoj.org/papers/8fe944dca9a4c5c45dd778f8518b0251/status.svg)](https://joss.theoj.org/papers/8fe944dca9a4c5c45dd778f8518b0251)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8fe944dca9a4c5c45dd778f8518b0251"><img src="https://joss.theoj.org/papers/8fe944dca9a4c5c45dd778f8518b0251/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8fe944dca9a4c5c45dd778f8518b0251/status.svg)](https://joss.theoj.org/papers/8fe944dca9a4c5c45dd778f8518b0251)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/giorginolab/plumed2-pycv/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@amritagos & @carlocamilloni, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/giorginolab/plumed2-pycv/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@tonigi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/giorginolab/plumed2-pycv/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@tonigi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @amritagos, @carlocamilloni it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1773 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@amritagos, @carlocamilloni - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01773/joss.01773/10.21105.joss.01773.pdf)

**Comment by amritagos** [comment]
@whedon check references


On Tue, Oct 01, 2019 at 6:31am, whedon < notifications@github.com [notifications@github.com] > wrote:
Assigned #1773 [https://github.com/openjournals/joss-reviews/issues/1773] to @amritagos [https://github.com/amritagos] .

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by tonigi** [comment]
Perhaps stuck because the paper is not in the default branch. Re-committed there and retrying.

@whedon check references

**Comment by tonigi** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by arfon** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.cpc.2013.09.018 is OK
- 10.1038/s41592-019-0506-8 is OK
- 10.1016/j.cpc.2018.02.017 is OK
- 10.1073/pnas.202427399 is OK
- 10.1002/wcms.31 is OK
- 10.1063/1.2432340 is OK
- 10.1093/bioinformatics/btx529 is OK
- 10.1103/PhysRevLett.119.245701 is OK
- 10.1016/0021-9991(77)90121-8 is OK

MISSING DOIs

- None

INVALID DOIs

- http://dx.doi.org/DOI: 10.1016/0010-4655(95)00053-I is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.cpc.2013.09.018 is OK
- 10.1038/s41592-019-0506-8 is OK
- 10.1016/j.cpc.2018.02.017 is OK
- 10.1073/pnas.202427399 is OK
- 10.1002/wcms.31 is OK
- 10.1063/1.2432340 is OK
- 10.1093/bioinformatics/btx529 is OK
- 10.1103/PhysRevLett.119.245701 is OK
- 10.1016/0021-9991(77)90121-8 is OK

MISSING DOIs

- None

INVALID DOIs

- http://dx.doi.org/DOI: 10.1016/0010-4655(95)00053-I is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.cpc.2013.09.018 is OK
- 10.1038/s41592-019-0506-8 is OK
- 10.1016/j.cpc.2018.02.017 is OK
- 10.1073/pnas.202427399 is OK
- 10.1002/wcms.31 is OK
- 10.1063/1.2432340 is OK
- 10.1093/bioinformatics/btx529 is OK
- 10.1103/PhysRevLett.119.245701 is OK
- 10.1016/0021-9991(77)90121-8 is OK

MISSING DOIs

- None

INVALID DOIs

- http://dx.doi.org/DOI: 10.1016/0010-4655(95)00053-I is INVALID because of 'https://doi.org/' prefix
```

**Comment by tonigi** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.cpc.2013.09.018 is OK
- 10.1038/s41592-019-0506-8 is OK
- 10.1016/j.cpc.2018.02.017 is OK
- 10.1016/0010-4655(95)00053-I is OK
- 10.1073/pnas.202427399 is OK
- 10.1002/wcms.31 is OK
- 10.1063/1.2432340 is OK
- 10.1093/bioinformatics/btx529 is OK
- 10.1103/PhysRevLett.119.245701 is OK
- 10.1016/0021-9991(77)90121-8 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by tonigi** [comment]
@amritagos Regarding the missing checkboxes, do they mean that you would like them amended, or just not assessed yet? Thanks

**Comment by amritagos** [comment]
Sorry, have been dragging my feet on this a little. Will have my review completed today. Not assessed them fully yet, will have more detailed input (issues) if amendments are needed.

**Comment by amritagos** [comment]
@tonigi The commit style is not clear at all.
![image](https://user-images.githubusercontent.com/32496815/66310730-8faeb300-e92a-11e9-8b91-aa40bb3abb9c.png)
However it is too late to change that so do keep it in mind for future work. Once the issues have been resolved I will be happy to complete my review.

**Comment by tonigi** [comment]
Thanks! Should be amended. The development history could be rebased in the future.

**Comment by tonigi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01773/joss.01773/10.21105.joss.01773.pdf)

**Comment by tonigi** [comment]
What next? Should I send to Zenodo? Thanks

**Comment by carlocamilloni** [comment]
@arfon - @tonigi contribution is well coded and documented and provide a smart tool for prototyping new code for plumed. Python is definitely the way to go. The paper is self-contained and provides all what one needs to immediately use it.

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by tonigi** [comment]
moved to the default branch for simplicity

@whedon generate pdf

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1773 with the following error: 

 error: pathspec 'joss-paper' did not match any file(s) known to git.
error: pathspec 'joss-paper' did not match any file(s) known to git.
Could not find bibliography file: paper.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01773/joss.01773/10.21105.joss.01773.pdf)

**Comment by arfon** [comment]
@tonigi - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by tonigi** [comment]
Should be done - thanks!

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3480171.svg)](https://doi.org/10.5281/zenodo.3480171)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3480171 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3480171" target="_blank">10.5281/zenodo.3480171</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.cpc.2013.09.018 is OK
- 10.1038/s41592-019-0506-8 is OK
- 10.1016/j.cpc.2018.02.017 is OK
- 10.1016/0010-4655(95)00053-I is OK
- 10.1073/pnas.202427399 is OK
- 10.1002/wcms.31 is OK
- 10.1063/1.2432340 is OK
- 10.1093/bioinformatics/btx529 is OK
- 10.1103/PhysRevLett.119.245701 is OK
- 10.1016/0021-9991(77)90121-8 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1021

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1021, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1182612775312515073) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1022
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01773](https://doi.org/10.21105/joss.01773)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@amritagos, @carlocamilloni - many thanks for your reviews here ✨ 

@tonigi - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01773/status.svg)](https://doi.org/10.21105/joss.01773)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01773">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01773/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01773/status.svg
   :target: https://doi.org/10.21105/joss.01773
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01773/status.svg)](https://doi.org/10.21105/joss.01773)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
