### ISSUE TITLE
[REVIEW]: Hasasia: A Python package for Pulsar Timing Array Sensitivity Curves

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1775]
**Submitting author:** @Hazboun6 (<a href="http://orcid.org/0000-0003-2742-3321">Jeffrey Hazboun</a>)
**Repository:** <a href="https://github.com/Hazboun6/hasasia" target ="_blank">https://github.com/Hazboun6/hasasia</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** @cmbiwer, @matteobachetti
**Archive:** <a href="https://doi.org/10.5281/zenodo.3516463" target="_blank">10.5281/zenodo.3516463</a>

## Status

[![status](https://joss.theoj.org/papers/d99d7655bd5704ab951157a14df227af/status.svg)](https://joss.theoj.org/papers/d99d7655bd5704ab951157a14df227af)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d99d7655bd5704ab951157a14df227af"><img src="https://joss.theoj.org/papers/d99d7655bd5704ab951157a14df227af/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d99d7655bd5704ab951157a14df227af/status.svg)](https://joss.theoj.org/papers/d99d7655bd5704ab951157a14df227af)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Hazboun6/hasasia" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@cmbiwer & @matteobachetti, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Hazboun6/hasasia">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Hazboun6) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Hazboun6/hasasia">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Hazboun6) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @cmbiwer, @matteobachetti it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01775/joss.01775/10.21105.joss.01775.pdf)

**Comment by arfon** [comment]
@cmbiwer, @matteobachetti - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by matteobachetti** [comment]
Overall, a very useful software package, well documented. I'm not done with the review, but I can start putting down some thoughts as I go through the checklist.

- Re. the statement of need: I ticked it because I think it's pretty clear what the software does and who can benefit, even if the audience is not *explicitly* mentioned. 

- Tests are run on Travis. I'm verifying that they cover a significant amount of code.

- There are no community guidelines. In general, I think it's a good idea to have one.

- In the proof, there is one broken reference ( _on the formalism presented in (???)_ ). I would suggest to add two more references: 

  1. a review on pulsar timing arrays in the introduction

  2. the newest Astropy paper (https://www.astropy.org/acknowledging.html)

**Comment by matteobachetti** [comment]
<img width="566" alt="Screenshot 2019-10-01 at 18 03 48" src="https://user-images.githubusercontent.com/7190189/65979624-e2ddbd00-e475-11e9-835c-3c96c5ceb82a.png">
Coverage is not bad. There are quite a few seemingly important pieces of the code left untested in `sensitivity.py`, including many of the methods in the `Spectrum` and `Sensitivity` classes. Even though I wouldn't block the publication based on that, I recommend to cover at least the ones you think users will rely the most on :).

**Comment by matteobachetti** [comment]
Bottom line of my review: this is good code and deserves publication on JOSS. Before publication, I suggest to fix and improve the references as reported above (fix the broken one, add Astropy 2018 and a review on PTAs), and add some community/code of conduct guidelines to the repository.

As a further suggestion, it would be good to improve the test coverage, covering at least all important classes /methods that people will rely the most on.

**Comment by Hazboun6** [comment]
@matteobachetti thanks for the quick/thorough review! I really like the real time refereeing. I assume it's kosher for me to do some real time fixes? 

One question. For community guidelines, the docs have [this](https://hasasia.readthedocs.io/en/latest/contributing.html) standard template blurb about contributing. Is the issue that it's buried in the docs, i.e. that I should make it more front and center, or that I should expand on what's in there?

**Comment by matteobachetti** [comment]
Sorry for the confusion. The issue is not the contribution guideline, which you do have also in the `CONTRIBUTING.rst` file. I meant something like https://www.astropy.org/code_of_conduct.html, more about the quality of interaction in the community than how to technically do things. 
Some templates can also be found at https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project

**Comment by Hazboun6** [comment]
I see. Thanks for the explanation and links @matteobachetti . That was very easy and I'm excited to include a Code of Conduct in the documents. I also went through and added a number of test for the code. I'm up to 87% coverage now. I've also added a few references and changed the `astropy` ref.

**Comment by cmbiwer** [comment]
I will be able to take a thorough look after Friday afternoon, if that timeline is alright.

**Comment by cmbiwer** [comment]
A Python package for building sensitivity curves for PTAs is presented. Overall, I believe the submission is suitable for publication in JOSS with minor comments to address. Going through the documentation, I found it to be readable and the functionality promised is presented. I do not believe any of these should prevent publication but that addressing them would strengthen the submission.

I outline my notes below for the authors:
  * While trying the tutorials, on the "Getting Started" page, you use ``numpy`` in the code blocks but omit it from the imports at the top of the page. I would suggest you add ``import numpy as np`` at the top of this page with the other imports. You do it for the following tutorials but not this page.
  * There was a minor typo in the first tutorial on ``GWBSensitivity`` and ``DeterSensitivity``. You wrote "inclusing" which I believe it was intended to be "including."
  * While running ``python setup.py test`` I received a number of warnings due to the LaTeX in the docstrings, e.g. ``DeprecationWarning: invalid escape sequence``. Although, I did not test myself (see documentation comment below), maybe these could be avoided by making the docstring ``r'''``. However, the tests ran successfully which is the important part.
  * In the tutorial on real data analysis (https://hasasia.readthedocs.io/en/latest/real_data_tutorial.html) a link to Lam et al. is included but does not seem to work.
  * In the documentation of two classes, there is an attribute with a docstring ``Hubble constant must be in`` which seems incomplete.
  * There was no documentation on how to build the documentation (any packages beyond the standard Sphinx?) and the documentation asks users to write documentation (https://hasasia.readthedocs.io/en/latest/contributing.html#write-documentation). Therefore, perhaps instructions on building the documentation could be added to this page.
  * In the software paper it states "In fact a number of 'standard' PTA configurations are included as part of the package." Is this referring to the NanoGrav 11-year data? Which seems to be committed to the repo and is also part of the tutorial? If so, perhaps this should be explicitly mentioned or cited in the software paper.
  * The accompanying theory paper by the authors have a nice set of citations in the introduction. Maybe there is an appropriate citation to review PTA here?

**Comment by Hazboun6** [comment]
Thanks @cmbiwer for the detailed review! That `Deprecation error` appeared in the Python 3.6 and 3.7 builds on Travis, but I never saw them locally. The `r"""` did in fact fix things. I've fixed most of the points above. Regarding the last two points point, the newer version of the [manuscript](https://github.com/Hazboun6/hasasia/blob/master/paper/paper.md) mention the pickled NANOGrav sensitivity curve and includes two references to PTA reviews.

**Comment by Hazboun6** [comment]
@arfon What are the next steps at this point?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01775/joss.01775/10.21105.joss.01775.pdf)

**Comment by arfon** [comment]
@Hazboun6 - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by Hazboun6** [comment]
@arfon I'm just getting to this now. When you refer to the authors of the archive, do you mean the authors listed, for instance in an Authors.rst? Or am I missing something in Zenodo where one would list the authors?

**Comment by arfon** [comment]
@Hazboun6 - Zenodo will attempt to fill out the author list based on the Git commit history. This is often not accurate so we ask that you make sure the Zenodo archive authors are the same as the authors on the paper.

**Comment by Hazboun6** [comment]
Alright, I think we are all set. Here is the badge for Zenodo [![DOI](https://zenodo.org/badge/178294587.svg)](https://zenodo.org/badge/latestdoi/178294587). I added a `.zenodo.json` so that the metadata file would reflect the authors of this paper. Please let me know what else you'll need me to do. Thanks!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3516463 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3516463" target="_blank">10.5281/zenodo.3516463</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.3847/1538-3881/aabc4f is OK
- 10.1007/s00159-019-0115-7 is OK
- 10.1093/nsr/nwx126 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1042

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1042, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1186957102092357632) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1043
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01775](https://doi.org/10.21105/joss.01775)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
Looks like the DOI isn't resolving yet. I'll hold off closing this thread until that's working properly...

**Comment by arfon** [comment]
@cmbiwer, @matteobachetti - many thanks for your reviews here ✨ 

@Hazboun6 - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01775/status.svg)](https://doi.org/10.21105/joss.01775)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01775">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01775/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01775/status.svg
   :target: https://doi.org/10.21105/joss.01775
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01775/status.svg)](https://doi.org/10.21105/joss.01775)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
