### ISSUE TITLE
[REVIEW]: GaitPy: An Open-Source Python Package for Gait Analysis Using an Accelerometer on the Lower Back

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1778]
**Submitting author:** @matt002 (<a href="http://orcid.org/0000-0001-9954-7003">Matthew Czech</a>)
**Repository:** <a href="https://github.com/matt002/GaitPy" target ="_blank">https://github.com/matt002/GaitPy</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewer:** @finsberg, @abhishektha
**Archive:** <a href="https://doi.org/10.5281/zenodo.3528115" target="_blank">10.5281/zenodo.3528115</a>

## Status

[![status](https://joss.theoj.org/papers/a2233c9e27db0b6625dc56a3f7363875/status.svg)](https://joss.theoj.org/papers/a2233c9e27db0b6625dc56a3f7363875)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a2233c9e27db0b6625dc56a3f7363875"><img src="https://joss.theoj.org/papers/a2233c9e27db0b6625dc56a3f7363875/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a2233c9e27db0b6625dc56a3f7363875/status.svg)](https://joss.theoj.org/papers/a2233c9e27db0b6625dc56a3f7363875)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/matt002/GaitPy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@finsberg & @abhishektha, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/matt002/GaitPy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mdc007) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/matt002/GaitPy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mdc007) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @finsberg, @abhishektha it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01778/joss.01778/10.21105.joss.01778.pdf)

**Comment by arfon** [comment]
@finsberg, @abhishektha - it looks like you've both made good progress on your reviews. Could I ask whether you're close to making a recommendation to accept here?

**Comment by finsberg** [comment]
@arfon I am still not able to install this software using pip (see https://github.com/matt002/GaitPy/issues/9). When this issue is fixed I will recommend acceptance.

**Comment by abhishektha** [comment]
@arfon I just have a few more things to check off, will have it done this weekend!

**Comment by finsberg** [comment]
@arfon I am done with my review, and recommend GaitPy for publication in JOSS.

**Comment by arfon** [comment]
> @arfon I am done with my review, and can recommend GaitPy for publication in JOSS.

👍 many thanks @finsberg!

**Comment by abhishektha** [comment]
@arfon I am done with my review as well and can recommend GaitPy for publication. Its a very cool package, I was able to run some of my own IMU data through it and it did a great job predicting initial and final contact times. 

I did notice that one of the references was missing its DOI in the paper, I put a pull request in the repository to hopefully fit it: https://github.com/matt002/GaitPy/pull/18

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01778/joss.01778/10.21105.joss.01778.pdf)

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.gaitpost.2012.02.019 is OK
- 10.1016/S0966-6362(02)00190-X is OK
- 10.1109/TBME.2003.812189 is OK
- 10.1109/JBHI.2015.2419317 is OK
- 10.1016/j.gaitpost.2014.07.007 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1016/j.cll.2010.01.003.Lyme is INVALID
```

**Comment by arfon** [comment]
@mdc007 - I've also fixed a DOI in your paper here: https://github.com/matt002/GaitPy/pull/19

**Comment by arfon** [comment]
@finsberg, @abhishektha - many thanks for your reviews here!

@mdc007 - please let us know when you've had a chance to incorporate the updates from myself and @abhishektha.

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.gaitpost.2012.02.019 is OK
- 10.1016/S0966-6362(02)00190-X is OK
- 10.1016/j.gaitpost.2011.03.024 is OK
- 10.1109/TBME.2003.812189 is OK
- 10.1109/JBHI.2015.2419317 is OK
- 10.1023/A:1010933404324 is OK
- 10.1016/j.gaitpost.2014.07.007 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by matt002** [comment]
@arfon @finsberg @abhishektha I have incorporated the above mentioned updates. Thank you all very much for your review and edits. The paper and package are much improved following the review process.

**Comment by arfon** [comment]
@matt002 - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by matt002** [comment]
@arfon I made a new release (1.6.0) and archived the software in Zenodo with DOI: 10.5281/zenodo.3528115.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3528115 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3528115" target="_blank">10.5281/zenodo.3528115</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.gaitpost.2012.02.019 is OK
- 10.1016/S0966-6362(02)00190-X is OK
- 10.1016/j.gaitpost.2011.03.024 is OK
- 10.1109/TBME.2003.812189 is OK
- 10.1109/JBHI.2015.2419317 is OK
- 10.1023/A:1010933404324 is OK
- 10.1016/j.gaitpost.2014.07.007 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1085

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1085, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1191423366332403719) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1086
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01778](https://doi.org/10.21105/joss.01778)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@finsberg, @abhishektha - many thanks for your reviews here ✨ 

@matt002 - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01778/status.svg)](https://doi.org/10.21105/joss.01778)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01778">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01778/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01778/status.svg
   :target: https://doi.org/10.21105/joss.01778
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01778/status.svg)](https://doi.org/10.21105/joss.01778)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
