### ISSUE TITLE
[PRE REVIEW]: Telewavesim: Python software for teleseismic body wave modeling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1779]
**Submitting author:** @paudetseis (<a href="http://orcid.org/0000-0003-2364-9454">Pascal Audet</a>)
**Repository:** <a href="https://github.com/paudetseis/Telewavesim" target ="_blank">https://github.com/paudetseis/Telewavesim</a>
**Version:** v0.1.0
**Editor:** @kbarnhart
**Reviewers:** @andreww, @seisman, @brmather

**Author instructions**

Thanks for submitting your paper to JOSS @paudetseis. **Currently, there isn't an JOSS editor assigned** to your paper.

@paudetseis if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1779 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1779/paper/paper.md): mapping values are not allowed in this context at line 14 column 16 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon.rb:115:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by paudetseis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01779/joss.01779/10.21105.joss.01779.pdf)

**Comment by kyleniemeyer** [comment]
Hi @leouieda, can you edit this article?

**Comment by Kevin-Mattheus-Moerman** [comment]
@kyleniemeyer I can take this one

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@krischer @danielpeter @HongjianFang @seisman @NoisyLeon @andreww @shicks-seismo @martinvandriel would you be interested in reviewing this work for the [Journal of Open Source Software (JOSS)](https://joss.theoj.org)? 
[**Telewavesim: Software for teleseismic body wave modeling**](https://github.com/paudetseis/Telewavesim)
The streamlined [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub and focuses on the software and a [very short paper](https://github.com/openjournals/joss-papers/blob/joss.01779/joss.01779/10.21105.joss.01779.pdf). 

This here is a pre-review issue. Once I've attracted sufficient reviewers I'll open a dedicated review issue where check-boxes guide you through the review process.
Let me know if you have questions.

**Comment by andreww** [comment]
Yes - I'm happy to review this.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @andreww as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @andreww

**Comment by Kevin-Mattheus-Moerman** [comment]
@andreww great thanks! I aim to find 2 more reviewers before we start. I'll let you know when we are ready.

**Comment by seisman** [comment]
@Kevin-Mattheus-Moerman I'm glad to review it.

**Comment by danielpeter** [comment]
thanks for the invite, but too much stretched out at the moment...

**Comment by paudetseis** [comment]
Hi @Kevin-Mattheus-Moerman, @andreww and @seisman 
Thanks for handling the paper. I'd just like to point out that I just merged a PR from @trichter that improved the code significantly. You might want to do a git pull if you already cloned the repo.

**Comment by NoisyLeon** [comment]
Thanks for the invitation, but I do not really have time for this at the moment...

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @seisman as reviewer

**Comment by whedon** [comment]
OK, @seisman is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@krischer @HongjianFang @shicks-seismo @martinvandriel would you be interested in reviewing this work for the [Journal of Open Source Software (JOSS)](https://joss.theoj.org)? 
[**Telewavesim: Software for teleseismic body wave modeling**](https://github.com/paudetseis/Telewavesim)
The streamlined [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub and focuses on the software and a [very short paper](https://github.com/openjournals/joss-papers/blob/joss.01779/joss.01779/10.21105.joss.01779.pdf). 

This here is a pre-review issue. Once I've attracted sufficient reviewers I'll open a dedicated review issue where check-boxes guide you through the review process.
Let me know if you have questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@kbarnhart would you like to edit this one? (Or review it). Sounds like it might be your cup tea?

**Comment by kbarnhart** [comment]
@Kevin-Mattheus-Moerman I can edit it.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @kbarnhart as editor

**Comment by kbarnhart** [comment]
@paudetseis I'd like to find one more reviewer for your submission. If you have any recommendations, please mention them on this thread. The following is a [list of potential reviewers](https://bit.ly/joss-reviewers). You can also recommend people who are not on this list.

**Comment by paudetseis** [comment]
@kbarnhart I'd like to recommend @ThomasLecocq and perhaps @brmather, neither of which are on the list.

**Comment by kbarnhart** [comment]
@paudetseis thanks for that recommendation.

@ThomasLecocq and @brmather would you be interested in reviewing this work for the [Journal of Open Source Software (JOSS)](https://joss.theoj.org)? [**Telewavesim: Software for teleseismic body wave modeling**](https://github.com/paudetseis/Telewavesim)

The streamlined [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub and focuses on the software and a [very short paper](https://github.com/openjournals/joss-papers/blob/joss.01779/joss.01779/10.21105.joss.01779.pdf). 

This here is a pre-review issue. I would like one more reviewer and then I'll open a dedicated review issue where check-boxes guide you through the review process.

Let me know if you have questions.

**Comment by brmather** [comment]
Hi @kbarnhart and @paudetseis, I would be happy to review [Telewavesim](https://github.com/paudetseis/Telewavesim).for JOSS.

**Comment by kbarnhart** [comment]
@whedon add @brmather as reviewer

**Comment by whedon** [comment]
OK, @brmather is now a reviewer

**Comment by kbarnhart** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1818. Feel free to close this issue now!
