### ISSUE TITLE
[PRE REVIEW]: ComplexRegions.jl: A Julia package for regions in the complex plane

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1780]
**Submitting author:** @tobydriscoll (<a href="http://orcid.org/0000-0002-1490-2545">Tobin Driscoll</a>)
**Repository:** <a href="https://github.com/complexvariables/ComplexRegions.jl" target ="_blank">https://github.com/complexvariables/ComplexRegions.jl</a>
**Version:** v0.1.0
**Editor:** @drvinceknight
**Reviewers:** @dlfivefifty, @dpsanders

**Author instructions**

Thanks for submitting your paper to JOSS @tobydriscoll. **Currently, there isn't an JOSS editor assigned** to your paper.

@tobydriscoll if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1780 with the following error: 

 [WARNING] Could not convert image '/tmp/tex2pdf.242/3357d2f1f823ca2031ac9cc4fc4a70707debb275.svg': check that rsvg2pdf is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.242/3357d2f1f82
3ca2031ac9cc4fc4a70707debb275.svg (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.361 ...d2f1f823ca2031ac9cc4fc4a70707debb275.svg}

Looks like we failed to compile the PDF

**Comment by kyleniemeyer** [comment]
Hi @drvinceknight, how do you feel about taking on another submission as editor?

**Comment by kyleniemeyer** [comment]
@arfon can papers use SVG images, or does this need to be converted to (e.g.) PDF?

**Comment by arfon** [comment]
> @arfon can papers use SVG images, or does this need to be converted to (e.g.) PDF?

Unfortunately we don't currently support SVG. We can support PNG, PDF, JPEG, etc.

**Comment by kyleniemeyer** [comment]
@tobydriscoll could you replace the SVG image included in your article with a different format?

**Comment by drvinceknight** [comment]
> Hi @drvinceknight, how do you feel about taking on another submission as editor?

Yup no problem.

**Comment by drvinceknight** [comment]
@whedon assign @drvinceknight as editor

**Comment by whedon** [comment]
OK, the editor is @drvinceknight

**Comment by drvinceknight** [comment]
@tobydriscoll I'll aim to get to this next week but in the meantime if you had any suggestions for reviewers please let me know.

**Comment by tobydriscoll** [comment]
I've pushed a change of the figure to PDF.

Possible reviewers are dlfivefifty, ajt60gaibb, daanhb. nakatsukasayuji.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01780/joss.01780/10.21105.joss.01780.pdf)

**Comment by tobydriscoll** [comment]
Checked the proof and fixed typos in the references.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01780/joss.01780/10.21105.joss.01780.pdf)

**Comment by drvinceknight** [comment]
@dlfivefifty, @ajt60gaibb, @daanhb would you be able to review this paper for JOSS? It describes a Julia package for working with complex regions.

If you have not reviewed for JOSS before, there are instructions here https://joss.readthedocs.io/en/latest/index.html and I'd be happy to answer any questions you might have.

Once we have 2 reviewers I will open a second issue where the review itself will take place.

One particular thing I'd appreciate your opinions on is the statement of need which I don't feel is made as clear as it could be in the paper

**Comment by dlfivefifty** [comment]
What’s the expected timeline?

**Comment by drvinceknight** [comment]
A few weeks would be great but if that's not possible let me know what you could possibly manage. (In my experience reviewing for JOSS takes less time and is more enjoyable than traditional publications - just FYI in case you haven't reviewed for JOSS before.)

**Comment by dlfivefifty** [comment]
I’m a bit busy but could probably do it within 3 weeks

**Comment by drvinceknight** [comment]
That would be great, I'll add you as a reviewer now @dlfivefifty.

**Comment by drvinceknight** [comment]
@whedon assign @dlfivefifty as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dlfivefifty

**Comment by ajt60gaibb** [comment]
@drvinceknight, I am afraid that I have too many refereeing jobs right now. I wouldn't be able to do it in a reasonable time frame. This process looks interesting, though.

**Comment by drvinceknight** [comment]
No problem @ajt60gaibb thanks for responding. :+1:

**Comment by drvinceknight** [comment]
Hi @vchuravy I know this doesn't fit immediately within your area of expertise but would you be willing to review this paper for JOSS? 

@ChrisRackauckas, @Datseris would you be able to review this paper for JOSS?

**Comment by daanhb** [comment]
Hi @drvinceknight, if you're looking for more reviewers, I can still chime in - though I'll probably have a similar point of view as @dlfivefifty (being co-authors of the DomainSets.jl package)

**Comment by Datseris** [comment]
Hello, thank you for the invitation, but I have to kindly decline reviewing this, as I believe it does not fall into my area of expertise.

**Comment by ChrisRackauckas** [comment]
I am way oversubscribed until Spring. If you're still looking for reviews then, feel free to ping me.

**Comment by vchuravy** [comment]
@dpsanders might be a better fit than me.

**Comment by drvinceknight** [comment]
> Hello, thank you for the invitation, but I have to kindly decline reviewing this, as I believe it does not fall into my area of expertise.

> I am way oversubscribed until Spring. If you're still looking for reviews then, feel free to ping me.

I understand @ChrisRackauckas and @Datseris  , thank you for responding.

> @dpsanders might be a better fit than me.

Thank you @vchuravy, @dpsanders would you be able to review this paper please? 

> Hi @drvinceknight, if you're looking for more reviewers, I can still chime in - though I'll probably have a similar point of view as @dlfivefifty (being co-authors of the DomainSets.jl package)


Thank you @daanhb, I'm going to wait a day or so to see if @dpsanders responds positively to gain a bit more variety of review but if not and you're still able I would be very grateful!

**Comment by dpsanders** [comment]
Yes I am happy to review but have a bit of a backlog right now.

**Comment by drvinceknight** [comment]
Thanks @dpsanders I'll add you as a reviewer and if your backlog gets too much let me know.

**Comment by drvinceknight** [comment]
@whedon add @dpsanders as reviewer

**Comment by whedon** [comment]
OK, @dpsanders is now a reviewer

**Comment by drvinceknight** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1811. Feel free to close this issue now!

**Comment by drvinceknight** [comment]
@dpsanders and @dlfivefifty the review will take place on #1811, please let me know if you have any questions about the process and thank you again for agreeing to take this on. It's a vital part of the process.

@daanhb thank you very much for offering to review, it's truly appreciated and hopefully you won't mind me calling on you in the future.
