### ISSUE TITLE
[PRE REVIEW]: perccalc: An R package for estimating percentiles from categorical variables

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1781]
**Submitting author:** @cimentadaj (<a href="http://orcid.org/0000-0001-5594-1156">Jorge Cimentada</a>)
**Repository:** <a href="https://github.com/cimentadaj/perccalc/" target ="_blank">https://github.com/cimentadaj/perccalc/</a>
**Version:** v1.0.4
**Editor:** @majensen
**Reviewers:** @briatte, @amoeba

**Author instructions**

Thanks for submitting your paper to JOSS @cimentadaj. **Currently, there isn't an JOSS editor assigned** to your paper.

@cimentadaj if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1781 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
Hi @cimentadaj, thanks for your submission. Before we get started, can you please rename the article source file to `paper.md`? Our automated build system requires the article to be called that, though it can be located anywhere in the repo.

**Comment by kyleniemeyer** [comment]
@karthik can you edit this R submission?

**Comment by cimentadaj** [comment]
Thanks @kyleniemeyer, I renamed everything to `paper.*` so all should be set. From reviewing the list , I think @rmhogervorst, @lebebr01, @mkearney or @briatte could be reviewers.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by briatte** [comment]
Dear all,

I'd be happy to review the package, although let me admit that I'm biased, since I know @cimentadaj's excellent work on other survey-related packages :)

All the best,

François

**Comment by cimentadaj** [comment]
Yes, for full disclosure, @briatte has helped out on other packages.

**Comment by karthik** [comment]
@kyleniemeyer Unfortunately my editorial plate is too full to handle this. :/

**Comment by majensen** [comment]
@whedon assign @briatte as reviewer

**Comment by majensen** [comment]
@amoeba, would you be willing to review [this submission](https://github.com/openjournals/joss-papers/blob/joss.01781/joss.01781/10.21105.joss.01781.pdf) to JOSS? Thanks for considering!

**Comment by amoeba** [comment]
Hey @majensen, sure. I can have my review in by the end of next week, on October 18th. Sound good?

**Comment by majensen** [comment]
Awesome @amoeba, much appreciated!

**Comment by majensen** [comment]
@whedon add @amoeba as reviewer

**Comment by whedon** [comment]
OK, @amoeba is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1796. Feel free to close this issue now!

**Comment by majensen** [comment]
Closing prereview - please head on over to #1796
