### ISSUE TITLE
[PRE REVIEW]: OwlDE: making ODEs first-class `Owl` citizens

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1782]
**Submitting author:** @mseri (<a href="http://orcid.org/0000-0002-8563-5894">Marcello Seri</a>)
**Repository:** <a href="https://github.com/owlbarn/owl_ode/" target ="_blank">https://github.com/owlbarn/owl_ode/</a>
**Version:** v0.2.0
**Editor:** @mjsottile
**Reviewers:** @xoolive, @rljacobson, @dagit

**Author instructions**

Thanks for submitting your paper to JOSS @mseri. **Currently, there isn't an JOSS editor assigned** to your paper.

@mseri if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01782/joss.01782/10.21105.joss.01782.pdf)

**Comment by kyleniemeyer** [comment]
Hi @mjsottile, how do you feel about taking on this submission as your first editorial assignment?

**Comment by mjsottile** [comment]
I could do it - it sounded like it was possible to get a "buddy" to help me through the first one to make sure the process goes smoothly.  Is that possible?

**Comment by kyleniemeyer** [comment]
@mjsottile yes, absolutely—feel free to email any of the AEiCs for questions about the process, if @arfon didn't mention a specific person.

**Comment by kyleniemeyer** [comment]
@whedon assign @mjsottile as editor

**Comment by whedon** [comment]
OK, the editor is @mjsottile

**Comment by mseri** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01782/joss.01782/10.21105.joss.01782.pdf)

**Comment by tachukao** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01782/joss.01782/10.21105.joss.01782.pdf)

**Comment by mjsottile** [comment]
Some potential reviewers are @rljacobson, @xoolive, @ziotom78, and @ocramz.  Would any of you be interested in reviewing this paper?

**Comment by ziotom78** [comment]
Hi @mjsottile, the last time I used OCaml was almost ten years ago, so it would be better to hand this to somebody more knowledgeable of the language.

**Comment by xoolive** [comment]
Hello. I would be glad to review this paper/project.

**Comment by mjsottile** [comment]
@whedon assign @xoolive as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @xoolive

**Comment by mjsottile** [comment]
@xoolive thanks for agreeing to review.  I still need to find another reviewer or two to help out.

**Comment by xoolive** [comment]
Thank you, I will have a look at it all next week

**Comment by grayswandyr** [comment]
Thank you very much for the proposal but I feel I'm not versed enough in the field addressed by this piece of software to be able to provide with a relevant review.

**Comment by rljacobson** [comment]
@mjsottile This looks like a great project. I would love to review it. This project covers a lot of ground (multiple backends, etc.) and so might take a little longer than usual to complete.

**Comment by mjsottile** [comment]
@whedon add @rljacobson as reviewer

**Comment by whedon** [comment]
OK, @rljacobson is now a reviewer

**Comment by dagit** [comment]
@mjsottile I'd be happy to take a look at this. I'm not an Ocaml expert but I have experience in other functional languages.

**Comment by mjsottile** [comment]
@whedon add @dagit as reviewer

**Comment by whedon** [comment]
OK, @dagit is now a reviewer

**Comment by mjsottile** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1812. Feel free to close this issue now!
