### ISSUE TITLE
[REVIEW]: LIBSDNN: A Selective Desensitization Neural Network Library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1785]
**Submitting author:** @BIPL-HORIE (<a href="http://orcid.org/0000-0001-7320-5478">和正 堀江</a>)
**Repository:** <a href="https://github.com/BIPL-HORIE/LIBSDNN" target ="_blank">https://github.com/BIPL-HORIE/LIBSDNN</a>
**Version:** v1.0
**Editor:** @arokem
**Reviewer:** @HaoZeke, @dirmeier
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/6e2e2cbec72da96f91f2996aa1dfe5c0/status.svg)](https://joss.theoj.org/papers/6e2e2cbec72da96f91f2996aa1dfe5c0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6e2e2cbec72da96f91f2996aa1dfe5c0"><img src="https://joss.theoj.org/papers/6e2e2cbec72da96f91f2996aa1dfe5c0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6e2e2cbec72da96f91f2996aa1dfe5c0/status.svg)](https://joss.theoj.org/papers/6e2e2cbec72da96f91f2996aa1dfe5c0)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/BIPL-HORIE/LIBSDNN" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@HaoZeke & @dirmeier, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/BIPL-HORIE/LIBSDNN">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@BIPL-HORIE) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/BIPL-HORIE/LIBSDNN">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@BIPL-HORIE) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @HaoZeke, @dirmeier it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1785 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon.rb:143:in `block in check_orcids': Problem with ORCID (0000-0000-0000-0000) for Atsuo Suemitsu (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon.rb:141:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon.rb:141:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon.rb:88:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arokem** [comment]
@BIPL-HORIE : looks like the pdf  is still not building because of mismatches between the references in the paper.md and paper.bib files for example `Weston:2011` vs. `Weston:2000`. Could you please make sure that they match?

**Comment by BIPL-HORIE** [comment]
@arokem 
I am really sorry for my lack of confirmation.
I corrected the citation.

Thank you.

**Comment by dirmeier** [comment]
You can check if the pdf builds via: @whedon generate pdf

**Comment by dirmeier** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1785 with the following error: 

 Error producing PDF.
! Undefined control sequence.
l.435 the libsdnn\doc

Looks like we failed to compile the PDF

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01785/joss.01785/10.21105.joss.01785.pdf)

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1785 with the following error: 

 Error producing PDF.
! Undefined control sequence.
l.441 \frac{1+x}{2}sin^2(6\pixy

Looks like we failed to compile the PDF

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01785/joss.01785/10.21105.joss.01785.pdf)

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01785/joss.01785/10.21105.joss.01785.pdf)

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01785/joss.01785/10.21105.joss.01785.pdf)

**Comment by BIPL-HORIE** [comment]
@arokem
Thank you a lot for your supports.
I finally got the pdf version.

Please take a look.
Thank you.

**Comment by dirmeier** [comment]
Dear @BIPL-HORIE, the built manuscript is missing some Figures. Could you please check again?

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01785/joss.01785/10.21105.joss.01785.pdf)

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01785/joss.01785/10.21105.joss.01785.pdf)

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01785/joss.01785/10.21105.joss.01785.pdf)

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01785/joss.01785/10.21105.joss.01785.pdf)

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01785/joss.01785/10.21105.joss.01785.pdf)

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01785/joss.01785/10.21105.joss.01785.pdf)

**Comment by BIPL-HORIE** [comment]
@whedon  generate pdf

**Comment by BIPL-HORIE** [comment]
@whedon create pdf

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01785/joss.01785/10.21105.joss.01785.pdf)

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01785/joss.01785/10.21105.joss.01785.pdf)

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01785/joss.01785/10.21105.joss.01785.pdf)

**Comment by BIPL-HORIE** [comment]
Dear @dirmeier, sorry for late response.
All the pictures are now in the pdf file.

**Comment by arokem** [comment]
@dirmeier, @HaoZeke : have you had a chance to take a look at this paper/software?

**Comment by HaoZeke** [comment]
@arokem and @BIPL-HORIE, sorry for the delay, I had a bit of a sudden move two weeks ago. I will have this done over the weekend as it seems there have been quite a few modifications. Thanks for the reminder!

**Comment by dirmeier** [comment]
For some reason, I didn't receive notifications on this thread, sorry. I will do the review over the weekend.

**Comment by HaoZeke** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.7763/IJMLC.2015.V5.531 is OK
- 10.1002/scj.10477 is OK
- 10.2299/jsp.18.225 is OK
- 10.20965/jaciii.2015.p0825 is OK
- 10.1007/978-3-319-70136-3_55 is OK
- 10.1016/j.neunet.2007.12.036 is OK
- 10.2299/jsp.23.145 is OK
- 10.2299/jsp.23.145 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-642-17534-3_6 may be missing for title: Practical Surface EMG Pattern Classification by Using a Selective Desensitization Neural Network
- https://doi.org/10.1109/scis-isis.2014.7044714 may be missing for title: Q-learning in continuous state-action space with redundant dimensions by using a selective desensitization neural network

INVALID DOIs

- None
```

**Comment by HaoZeke** [comment]
@BIPL-HORIE just to keep you informed. I will be working on my review with issues opened in the repository which should link back to this thread as well. Please let me know if there are any questions.

**Comment by BIPL-HORIE** [comment]
@whedon  generate pdf

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01785/joss.01785/10.21105.joss.01785.pdf)

**Comment by BIPL-HORIE** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.7763/IJMLC.2015.V5.531 is OK
- 10.1002/scj.10477 is OK
- 10.2299/jsp.18.225 is OK
- 10.20965/jaciii.2015.p0825 is OK
- 10.1007/978-3-319-70136-3_55 is OK
- 10.1016/j.neunet.2007.12.036 is OK
- 10.2299/jsp.23.145 is OK
- 10.2299/jsp.23.145 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-642-17534-3_6 may be missing for title: Practical Surface EMG Pattern Classification by Using a Selective Desensitization Neural Network
- https://doi.org/10.1109/scis-isis.2014.7044714 may be missing for title: Q-learning in continuous state-action space with redundant dimensions by using a selective desensitization neural network

INVALID DOIs

- None
```

**Comment by BIPL-HORIE** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.7763/IJMLC.2015.V5.531 is OK
- 10.1002/scj.10477 is OK
- 10.2299/jsp.18.225 is OK
- 10.20965/jaciii.2015.p0825 is OK
- 10.1007/978-3-319-70136-3_55 is OK
- 10.1016/j.neunet.2007.12.036 is OK
- 10.2299/jsp.23.145 is OK
- 10.2299/jsp.23.145 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-642-17534-3_6 may be missing for title: Practical Surface EMG Pattern Classification by Using a Selective Desensitization Neural Network
- https://doi.org/10.1109/scis-isis.2014.7044714 may be missing for title: Q-learning in continuous state-action space with redundant dimensions by using a selective desensitization neural network

INVALID DOIs

- None
```

**Comment by BIPL-HORIE** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.7763/IJMLC.2015.V5.531 is OK
- 10.1002/scj.10477 is OK
- 10.2299/jsp.18.225 is OK
- 10.20965/jaciii.2015.p0825 is OK
- 10.1007/978-3-319-70136-3_55 is OK
- 10.1016/j.neunet.2007.12.036 is OK
- 10.2299/jsp.23.145 is OK
- 10.2299/jsp.23.145 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-642-17534-3_6 may be missing for title: Practical Surface EMG Pattern Classification by Using a Selective Desensitization Neural Network
- https://doi.org/10.1109/scis-isis.2014.7044714 may be missing for title: Q-learning in continuous state-action space with redundant dimensions by using a selective desensitization neural network

INVALID DOIs

- None
```

**Comment by BIPL-HORIE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01785/joss.01785/10.21105.joss.01785.pdf)

**Comment by BIPL-HORIE** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.7763/IJMLC.2015.V5.531 is OK
- 10.1002/scj.10477 is OK
- 10.1007/978-3-642-17534-3_6 is OK
- 10.2299/jsp.18.225 is OK
- 10.1109/scis-isis.2014.7044714 is OK
- 10.20965/jaciii.2015.p0825 is OK
- 10.1007/978-3-319-70136-3_55 is OK
- 10.1016/j.neunet.2007.12.036 is OK
- 10.2299/jsp.23.145 is OK
- 10.2299/jsp.23.145 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arokem** [comment]
@dirmeier, @HaoZeke : where do things currently stand? Have you had a chance to take a look?

**Comment by dirmeier** [comment]
I made my reviews a month ago or so ... haven't heard back so far

**Comment by HaoZeke** [comment]
Hi, I'm also waiting for the author to update the repository before continuing.

**Comment by arokem** [comment]
Thank you. 

@BIPL-HORIE : have you had a chance to take a look at the reviewers' comments?

**Comment by arokem** [comment]
@BIPL-HORIE : without your response, we cannot move ahead with this paper. Please get back to me ASAP confirming that you have received these comments.

**Comment by danielskatz** [comment]
👋 @BIPL-HORIE - we will be forced to reject this submission unless you respond this week

**Comment by danielskatz** [comment]
I have also emailed @BIPL-HORIE now

**Comment by arokem** [comment]
+1 for rejection. 

I emailed the author 8 days ago to ask when the revisions will be completed and received a response that this "will take time". 

When asked to post here for clarification and to notify the reviewers, the author did not respond, or clarify here.

**Comment by HaoZeke** [comment]
Do we have guidelines on rejection for delayed responses? To be totally fair I am well aware the reviews were not completed in the normal JOSS timeframe either..

**Comment by danielskatz** [comment]
No, we generally try to get all submissions to the acceptable point

**Comment by BIPL-HORIE** [comment]
Dear editor and reviewers,

I'm really sorry for my late response.
I regret submitting my paper even though I don't have enough time to revise.

Thank to the review, I found that my library does not have maintainability required as open source software. 
And, now I'm willing to revise my library according to the review.
However, It will be a hard job for me and it cannot be fixed right away, considering my skills.

I'm really sorry about that. Now, I think that my submission should be rejected in this time.
I don't want to bother the editors and reviewers any more.

I would appreciate it if I could submit again when I finished revising the library.

**Comment by danielskatz** [comment]
yes, we would be happy for this to be submitted in the future.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
