### ISSUE TITLE
[PRE REVIEW]: modelStudio: Interactive Studio with Explanations for ML Predictive Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1788]
**Submitting author:** @hbaniecki (<a href="http://orcid.org/0000-0001-6661-5364">Hubert Baniecki</a>)
**Repository:** <a href="https://github.com/ModelOriented/modelStudio" target ="_blank">https://github.com/ModelOriented/modelStudio</a>
**Version:** v0.1.8
**Editor:** @terrytangyuan
**Reviewers:** @acolum, @expectopatronum

**Author instructions**

Thanks for submitting your paper to JOSS @hbaniecki. **Currently, there isn't an JOSS editor assigned** to your paper.

@hbaniecki if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01788/joss.01788/10.21105.joss.01788.pdf)

**Comment by kyleniemeyer** [comment]
Hi @terrytangyuan, can you edit this submission?

**Comment by terrytangyuan** [comment]
@whedon assign @terrytangyuan as editor

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by hbaniecki** [comment]
Hi @terrytangyuan, just by looking at `Domains` in your document i can see that @expectopatronum has written `Interpretable machine learning` there, which is cool. 
I have also intersected all of your 723 reviewers with 481 stargazers of DALEX R package. This has led me to 7 people. Some of them list `R` as their language and `Machine Learning` as their domain: @mkearney, @alexpghayes, @acolum .

**Comment by terrytangyuan** [comment]
Hi 👋 @expectopatronum  @mkearney, @alexpghayes, @acolum, if you'd like to review this submission, please let us know here (we need at least two reviewers)!

**Comment by acolum** [comment]
Thanks for contacting me, and yes, I'd like to review this submission.

**Comment by expectopatronum** [comment]
I haven't worked with R for about a year now (switched jobs) but my main focus is interpretable machine learning. If you don't find anyone more suitable I'd gladly review this submission.
Off topic: Does anyone know where I can update my entry in this spreadsheet?

**Comment by alexpghayes** [comment]
I don't have the bandwidth to review at the moment, but this looks like a cool project!

**Comment by terrytangyuan** [comment]
@whedon assign @acolum as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @acolum

**Comment by terrytangyuan** [comment]
@whedon add @expectopatronum as reviewer

**Comment by whedon** [comment]
OK, @expectopatronum is now a reviewer

**Comment by terrytangyuan** [comment]
Thanks everyone! @expectopatronum assigned you as reviewer as we cannot find anyone else at this moment. Your input on this submission would be very helpful. Regarding the spreadsheet, I’ll ask the team to see if there’s any way to update that.

**Comment by terrytangyuan** [comment]
@expectopatronum You can direct any update request to the reviewers spreadsheet to @arfon.
