### ISSUE TITLE
[PRE REVIEW]: SunPy: A Python package for Solar Physics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1789]
**Submitting author:** @Cadair (<a href="http://orcid.org/0000-0003-4217-4642">Stuart Mumford</a>)
**Repository:** <a href="https://github.com/sunpy/sunpy" target ="_blank">https://github.com/sunpy/sunpy</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewers:** @mwcraig, @ceb8

**Author instructions**

Thanks for submitting your paper to JOSS @Cadair. The JOSS editor @arfon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Cadair if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@arfon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @Cadair - thanks for your submission to JOSS. Does this JOSS submission accompany a publication in a AAS journal?

**Comment by whedon** [comment]
PDF failed to compile for issue #1789 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01789/joss.01789/10.21105.joss.01789.pdf)

**Comment by arfon** [comment]
Also, @Cadair, could you identify potential reviewers for this submission? Given your epic author list (I'll fix the left-hand margin issue when this paper is published), I suspect finding reviewers might be tough... 😅

**Comment by ehsteve** [comment]
@arfon FYI, there is a companion paper that was submitted and accepted by ApJ.

**Comment by Cadair** [comment]
@arfon Is there a list of reviewers somewhere? People related to the astro ecosystem, i.e. astropy  or yt contributors would be at the top of the list I would think of.

**Comment by arfon** [comment]
> @arfon FYI, there is a companion paper that was submitted and accepted by ApJ. I am the corresponding author for that paper.

/ cc @crawfordsm

**Comment by arfon** [comment]
@Cadair [this list of people](https://bit.ly/joss-reviewers) posted at the top of this thread have volunteered but feel free to suggest people from outside of this list who you think could give a good review.

**Comment by arfon** [comment]
Also, given this is a joint submission with AAS Journals, could you add metadata like this to the YAML header of the `paper.md` file @Cadair?

```
aas-doi: DOI of AAS paper
aas-journal: Name of journal (e.g. Astronomical Journal)
```

**Comment by Cadair** [comment]
maybe (without mentioning them) mwcraig ceb8 or dhuppenkothen

I will add the aas metadata (although I don't know the DOI)

**Comment by Cadair** [comment]
Also ngoldbaum or drsophiemurray (who I am not 100% sure shouldn't be on the author list)

**Comment by arfon** [comment]
@ceb8 @dhuppenkothen - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by ehsteve** [comment]
@Cadair I'll ask for the DOI though we aren't published yet but accepted.

**Comment by ceb8** [comment]
@arfon Yes I can review. When do you need the review by?

**Comment by arfon** [comment]
> @arfon Yes I can review. When do you need the review by?

👍, ideally in the next 2-3 weeks?

**Comment by arfon** [comment]
:wave: @ngoldbaum - would you be willing to review this submission for JOSS?

**Comment by ngoldbaum** [comment]
Unfortunately I can't commit to reviewing this right now as I don't have the bandwidth. Good luck finding another reviewer.

**Comment by arfon** [comment]
> Unfortunately I can't commit to reviewing this right now as I don't have the bandwidth. Good luck finding another reviewer.

NP, thanks for the quick response.

**Comment by arfon** [comment]
:wave: @mwcraig - would you be willing to review this submission for JOSS?

**Comment by mwcraig** [comment]
@arfon -- I'd be delighted but fear I've got a conflict of interest here. Stuart and I are co-authors on the most recent astropy paper, but perhaps more importantly, have worked together on some of the pieces of Astropy that interface most directly with SunPy.

**Comment by mwcraig** [comment]
I think I could be unbiased (the JOSS review criteria are pretty straightforward) but felt obligated to make you aware of al the appearance of a conflict of interest.

**Comment by arfon** [comment]
OK thanks for letting me know @mwcraig. Let me ping @dhuppenkothen one more time to see if she's available, but I might come back to you later :-)

**Comment by arfon** [comment]
> I think I could be unbiased (the JOSS review criteria are pretty straightforward) but felt obligated to make you aware of al the appearance of a conflict of interest.

@mwcraig - Thanks again for the offer to help here. I'd like to take you up on your offer :-)

**Comment by arfon** [comment]
@whedon assign @mwcraig as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mwcraig

**Comment by arfon** [comment]
@whedon add @ceb8 as reviewer

**Comment by whedon** [comment]
OK, @ceb8 is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1832. Feel free to close this issue now!

**Comment by arfon** [comment]
@mwcraig, @ceb8 - many thanks for agreeing to review this submission. Please head over to #1832 where the actual review will take place.
