### ISSUE TITLE
[PRE REVIEW]: The ExoTETHyS package: Tools for Exoplanetary Transits around Host Stars

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1790]
**Submitting author:** @gmorello (<a href="http://orcid.org/0000-0002-4262-5661">Giuseppe Morello</a>)
**Repository:** <a href="https://github.com/ucl-exoplanets/ExoTETHyS" target ="_blank">https://github.com/ucl-exoplanets/ExoTETHyS</a>
**Version:** v1.0.1
**Editor:** @arfon
**Reviewers:** @steven-murray, @williamjameshandley

**Author instructions**

Thanks for submitting your paper to JOSS @gmorello. The JOSS editor @arfon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@gmorello if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@arfon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by arfon** [comment]
:wave: @gmorello, thanks for your submission to JOSS. A few questions/comments before we get started here:

- Is this a joint submission with a AAS publication?
- Please look at this [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) and format the YAML header _exactly_ the same way as it is done here. YAML is whitespace sensitive and your `paper.md` as it currently stands won't compile.
- Also, I don't see any tests/testing procedures included with this package. As such I don't think this is quite ready to send out to reviewers yet - if you would like to understand more about how your software will be reviewed, please take a look at our [reviewer guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html).

**Comment by gmorello** [comment]
Dear Arfon Smith,

thanks for your message.
I edited the paper.md file to be identical to the example.

In case it does not compile:

  *   Could they be caused by accented letters?
  *   Not all the contributors have an ORCID, so I have reported only mine.
  *   Could they be caused by the URL that I report?

About the tests, there are already 8 possible input files in the examples folder.
Some of them require the user to change the paths in order to work on their computers, but at least the sail_example2.txt, sail_example5.txt, sail_example6.txt and sail_example7.txt should now work without any edits.

Please let me know if there are still issues.

Best regards,
Giuseppe

________________________________

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1790 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1790/paper.md): control characters are not allowed at line 1 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon.rb:115:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by gmorello** [comment]
@whedon<https://github.com/whedon> generate pdf
________________________________

**Comment by arfon** [comment]
@gmorello - this pull request should fix your paper: https://github.com/ucl-exoplanets/ExoTETHyS/pull/2

Also, please create a `paper.bib` file and add the bibtex entry for the arXiv entry in your paper. You will need to cite the arXiv entry in the text: you can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)).

> About the tests, there are already 8 possible input files in the examples folder.

OK thanks. This may be acceptable to our reviewers but I suspect they will want something more robust than this.

Next step is to identify some potential reviewers for this submission. Could you take a look at [this list of people](https://bit.ly/joss-reviewers) and identify a few people that might be able to give this package a review?

**Comment by arfon** [comment]
> Is this a joint submission with a AAS publication?

Also, could you please answer this ☝️ question from earlier?

**Comment by gmorello** [comment]
It is associated with an AAS manuscript under review, the one cited from arXiv.

Solely based on the information they provide, I selected possibly suitable reviewers:

nespinoza*, nicoguaro, andreas-h, zingale, ziotom78, steven-murray, williamjameshandley, harpolea, astrom-tom, danehkar, dhuppenkothen, wtbarnes, gregbryan


*nespinoza developed a code with similar functionalities. I am not sure whether this can cause a conflict of interest.


I have tried hard but I do not understand why the compiler does not recognise the citation @2019arXiv190809599M.

Thanks,
Giuseppe

________________________________

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01790/joss.01790/10.21105.joss.01790.pdf)

**Comment by gmorello** [comment]
It looks fine, thank you.

Giuseppe
________________________________

**Comment by arfon** [comment]
:wave: @williamjameshandley - would you be willing to review this submission for JOSS?

**Comment by arfon** [comment]
:wave: @steven-murray - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by steven-murray** [comment]
@arfon yes I'd be happy to!

**Comment by whedon** [comment]
OK, @steven-murray is now a reviewer

**Comment by arfon** [comment]
@whedon add @williamjameshandley as reviewer

**Comment by whedon** [comment]
OK, @williamjameshandley is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1834. Feel free to close this issue now!

**Comment by arfon** [comment]
> @arfon I'm happy to review this.

Great, thanks for the quick response @williamjameshandley!

@steven-murray, @williamjameshandley, @gmorello - see you over in #1834 where the actual review will take place.
