### ISSUE TITLE
[PRE REVIEW]: GFFJ.jl: Optimization-based gap finding and filling in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1791]
**Submitting author:** @ZZP12 (<a href="http://orcid.org/0000-0002-9099-4357">Zhiping Zhang</a>)
**Repository:** <a href="https://github.com/varnerlab/GFFJ.git" target ="_blank">https://github.com/varnerlab/GFFJ.git</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @ZZP12. **Currently, there isn't an JOSS editor assigned** to your paper.

@ZZP12 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01791/joss.01791/10.21105.joss.01791.pdf)

**Comment by ZZP12** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1791 with the following error: 

 [WARNING] Could not convert image '/tmp/tex2pdf.1164/a453d977148ada08be2e80dd5041afebf370ea44.svg': check that rsvg2pdf is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
[WARNING] Could not convert image '/tmp/tex2pdf.1164/04cdb495b5652e551877e00b40294609dab10a02.svg': check that rsvg2pdf is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.1164/a453d97714
8ada08be2e80dd5041afebf370ea44.svg (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.345 ...d977148ada08be2e80dd5041afebf370ea44.svg}

Looks like we failed to compile the PDF

**Comment by ZZP12** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1791 with the following error: 

 [WARNING] Could not convert image '/tmp/tex2pdf.1200/04cdb495b5652e551877e00b40294609dab10a02.svg': check that rsvg2pdf is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error producing PDF.
! LaTeX Error: \begin{align*} on input line 343 ended by \end{align**}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.355 \end{align**}

Looks like we failed to compile the PDF

**Comment by ZZP12** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1791 with the following error: 

 Error producing PDF.
! LaTeX Error: \begin{align*} on input line 343 ended by \end{align**}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.356 \end{align**}

Looks like we failed to compile the PDF

**Comment by ZZP12** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1791 with the following error: 

 Error producing PDF.
! Package amsmath Error: Erroneous nesting of equation structures;
(amsmath)                trying to recover with `aligned'.

See the amsmath package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.356 \end{align*}

Looks like we failed to compile the PDF

**Comment by ZZP12** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01791/joss.01791/10.21105.joss.01791.pdf)

**Comment by ZZP12** [comment]
@vchuravy

**Comment by ZZP12** [comment]
@ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
Hey,
  I don't think I'll be able to commit adequate time for this until spring, but it looks like a great project. However, it should make sure that it satisfies the basics of a Julia package, for example changing the repo to a `.jl` and having a name that's not just an acronym. I would think it would be good for this to go through the package registration process before solidifying in paper form.

  If you don't find a reviewer by February, feel free to ping me.

**Comment by labarba** [comment]
@ZZP12 — After a pre-review of your submission, and an assessment by the editorial board at large, we find that this submission does not quite meet our [submission requirements](http://joss.theoj.org/about#submission_requirements). In particular, while the software seems useful, it falls under the 'Minor utility' category, and we therefore decided not to put it through review. 

Thank you for considering JOSS as a venue for your software, and I hope you'll submit other software with research application in the future.
