### ISSUE TITLE
[PRE REVIEW]: archetypal: A Python package for collecting, simulating, converting and analyzing building archetypes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1792]
**Submitting author:** @samuelduchesne (<a href="http://orcid.org/0000-0001-5790-878X">Samuel Letellier-Duchesne</a>)
**Repository:** <a href="https://github.com/samuelduchesne/archetypal" target ="_blank">https://github.com/samuelduchesne/archetypal</a>
**Version:** v1.3
**Editor:** @kyleniemeyer
**Reviewers:** @brynpickering, @ThibaultMarzullo

**Author instructions**

Thanks for submitting your paper to JOSS @samuelduchesne. **Currently, there isn't an JOSS editor assigned** to your paper.

@samuelduchesne if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01792/joss.01792/10.21105.joss.01792.pdf)

**Comment by labarba** [comment]
👋 @samuelduchesne — I am the Associate Editor-in-Chief on rotation this week, and will continue working to identify an editor to handle your submission.  But first, I need to ask you to add to the top of your paper:

> A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.

(From our [Documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain).)

Currently, the paper is using a lot of jargon. As it is, I (a non-specialist) will find it hard for to identify the right editor. Thanks!

**Comment by samuelduchesne** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by samuelduchesne** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.enbuild.2017.01.030 is OK
- 10.1016/j.buildenv.2015.12.001 is OK
- 10.2172/90674 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by samuelduchesne** [comment]
@whedon generate pdf from branch feature/clearer_summary

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature/clearer_summary. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01792/joss.01792/10.21105.joss.01792.pdf)

**Comment by samuelduchesne** [comment]
@whedon generate pdf from branch feature/clearer_summary

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature/clearer_summary. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01792/joss.01792/10.21105.joss.01792.pdf)

**Comment by samuelduchesne** [comment]
@whedon generate pdf from branch feature/clearer_summary

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature/clearer_summary. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01792/joss.01792/10.21105.joss.01792.pdf)

**Comment by samuelduchesne** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@Kevin-Mattheus-Moerman
@VivianePons
@alexhanna
@arfon
@arokem
@brainstorm
@cMadan
@csoneson
@danielskatz
@drvinceknight
@gkthiruvathukal
@jedbrown
@karthik
@katyhuff
@kthyng
@kyleniemeyer
@labarba
@leouieda
@lheagy
@lpantano
@majensen
@mbobra
@meg-simula
@mgymrek
@mjsottile
@oliviaguest
@poulson
@terrytangyuan
@trallard
@usethedata
@xuanxu
```

**Comment by samuelduchesne** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by labarba** [comment]
@brynpickering 👋  — Would you be interested in contributing a review for The Journal of Open Source Software (JOSS) on this submission:
**archetypal: A Python package for collecting, simulating, converting and analyzing building archetypes**
https://github.com/samuelduchesne/archetypal

**Comment by samuelduchesne** [comment]
🤓 Hi @labarba. Thanks for handling this review process. I looked at the list of reviewers and filtered it for python users and the keyword "energy" in their topic area (nothing for *building*). Only 9 hits! Most of them specialists in physics. May I suggest @katyhuff, @wholmgren or @EricaEgg? @brynpickering was also in the list.

**Comment by samuelduchesne** [comment]
@whedon generate pdf from branch develop

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch develop. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01792/joss.01792/10.21105.joss.01792.pdf)

**Comment by brynpickering** [comment]
@labarba happy to review 👍

**Comment by labarba** [comment]
Thank you, @brynpickering !

The area of application of this software is unusual for JOSS, so I think finding reviewers could be a bit of a challenge. Would you be able to recommend another person to review this?

**Comment by brynpickering** [comment]
Hmm, that's a tricky one - most people I know in the field are more accustomed to Matlab, so the Python element might prove to be a barrier. Nonetheless, @rmward61 might be interested (/ know others).

**Comment by labarba** [comment]
@whedon assign @brynpickering as reviewer

**Comment by labarba** [comment]
@katyhuff — Could you handle this submission as editor? We already have one reviewer and need a second.
archetypal: A Python package for collecting, simulating, converting and analyzing building archetypes
https://github.com/samuelduchesne/archetypal
(related to assessing energy performance of buildings in cities)

**Comment by Kevin-Mattheus-Moerman** [comment]
@katyhuff :wave: can you take this one? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@kyleniemeyer can you edit this one?

**Comment by kyleniemeyer** [comment]
@Kevin-Mattheus-Moerman sure, can do

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by ThibaultMarzullo** [comment]
Hi @Kevin-Mattheus-Moerman and @kyleniemeyer , I can review this

**Comment by Kevin-Mattheus-Moerman** [comment]
@kyleniemeyer, @ThibaultMarzullo is a colleague of mine at NUIG and works in this domain. 

@ThibaultMarzullo perhaps you can also update your GitHub profile to list your academic affiliation and perhaps even an ORCID profile or similar. Thank for your help here!

**Comment by kyleniemeyer** [comment]
Thanks @ThibaultMarzullo for volunteering and @Kevin-Mattheus-Moerman for the clarification!

**Comment by kyleniemeyer** [comment]
@whedon add @ThibaultMarzullo as reviewer

**Comment by whedon** [comment]
OK, @ThibaultMarzullo is now a reviewer

**Comment by kyleniemeyer** [comment]
OK, now that we have two reviewers assigned, I'm going to start the actual review, which will close this pre-review issue and open a new one.

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1833. Feel free to close this issue now!
