### ISSUE TITLE
[PRE REVIEW]: momepy: Urban Morphology Measuring Toolkit

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1793]
**Submitting author:** @martinfleis (<a href="http://orcid.org/0000-0003-3319-3366">Martin Fleischmann</a>)
**Repository:** <a href="https://github.com/martinfleis/momepy" target ="_blank">https://github.com/martinfleis/momepy</a>
**Version:** v0.1
**Editor:** @drvinceknight
**Reviewers:** @martibosch, @geraintpalmer

**Author instructions**

Thanks for submitting your paper to JOSS @martinfleis. **Currently, there isn't an JOSS editor assigned** to your paper.

@martinfleis if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1793 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1793/paper/paper.md): mapping values are not allowed in this context at line 2 column 15 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon.rb:115:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@labarba - you can mention @openjournals/dev for issues like this.

**Comment by martinfleis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by labarba** [comment]
Thanks! I'm not sure what Is going on here... 😕

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01793/joss.01793/10.21105.joss.01793.pdf)

**Comment by martinfleis** [comment]
@arfon @labarba That was my mistake, my markdown editor changed '' to ‘’.

**Comment by martinfleis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1793 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1793/paper/paper.md): mapping values are not allowed in this context at line 2 column 15 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon.rb:115:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by martinfleis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01793/joss.01793/10.21105.joss.01793.pdf)

**Comment by martinfleis** [comment]
Based on the list of potential reviewers, it seems that following are the closest match based on their research profile and Python as the preferred language. Hope this helps.
@sjsrey, @martibosch, @hertzsprung,  @kbevers, @Scivision

**Comment by labarba** [comment]
👋 @drvinceknight — We don't have any editors with field expertise related to architecture or urban planning, and I'm wondering if you could save the day here, given your multi-faceted disposition. Could you handle this as editor?
**momepy: Urban Morphology Measuring Toolkit**
https://github.com/martinfleis/momepy

**Comment by kbevers** [comment]
This is outside my area of expertise so I will not be reviewing this paper. Thanks for considering me as a potential reviewer.

**Comment by labarba** [comment]
@whedon assign @drvinceknight as editor

**Comment by whedon** [comment]
OK, the editor is @drvinceknight

**Comment by drvinceknight** [comment]
Thank you :+1:

**Comment by drvinceknight** [comment]
@geraintpalmer would you be able to review this paper for JOSS?

**Comment by drvinceknight** [comment]
@whedon assign @martibosch as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @martibosch

**Comment by drvinceknight** [comment]
@martibosch I don't know if you have reviewed for JOSS before but there is documentation on the process here https://joss.readthedocs.io/en/latest/index.html and I'm happy to answer any questions. Once I have sufficient reviewers I will open a new issue where the review will take place.

**Comment by martibosch** [comment]
this is the second time that I have been assigned to review a JOSS paper - the first was last week. Therefore, this will probably be my second JOSS paper as reviewer. I will follow the guidelines of the documentation and get back to you if I have any other question. Cheers!

**Comment by drvinceknight** [comment]
Ok fantastic, sorry for the slight overload with the request to review two papers at the same time. Your contribution is super appreciated.

**Comment by martibosch** [comment]
no worries - first of all I am happy to contribute to JOSS, and secondly, in this case I kindly offered because this library is really closely related to my PhD topic, so it is useful for me to be aware of the state of the art.

**Comment by geraintpalmer** [comment]
> @geraintpalmer would you be able to review this paper for JOSS?

Yes I'm happy to do this.

**Comment by drvinceknight** [comment]
Fantastic, thanks @geraintpalmer :+1:

**Comment by drvinceknight** [comment]
@whedon add @geraintpalmer as reviewer

**Comment by whedon** [comment]
OK, @geraintpalmer is now a reviewer

**Comment by drvinceknight** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1807. Feel free to close this issue now!

**Comment by drvinceknight** [comment]
@geraintpalmer @martibosch the review will take place on #1807 any questions about the process please don't hesitate to ping me.

**Comment by martinfleis** [comment]
@drvinceknight For some reason the review issue is duplicated in #1806 and #1807. The first one should be probably closed.

**Comment by drvinceknight** [comment]
Thanks @martinfleis, have taken care of it.
