### ISSUE TITLE
[REVIEW]: perccalc: An R package for estimating percentiles from categorical variables

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1796]
**Submitting author:** @cimentadaj (<a href="http://orcid.org/0000-0001-5594-1156">Jorge Cimentada</a>)
**Repository:** <a href="https://github.com/cimentadaj/perccalc/" target ="_blank">https://github.com/cimentadaj/perccalc/</a>
**Version:** v1.0.5
**Editor:** @majensen
**Reviewer:** @briatte, @amoeba
**Archive:** <a href="https://doi.org/10.5281/zenodo.3559855" target="_blank">10.5281/zenodo.3559855</a>

## Status

[![status](https://joss.theoj.org/papers/6aa957144bec59d3c1b02aa945ed9468/status.svg)](https://joss.theoj.org/papers/6aa957144bec59d3c1b02aa945ed9468)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6aa957144bec59d3c1b02aa945ed9468"><img src="https://joss.theoj.org/papers/6aa957144bec59d3c1b02aa945ed9468/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6aa957144bec59d3c1b02aa945ed9468/status.svg)](https://joss.theoj.org/papers/6aa957144bec59d3c1b02aa945ed9468)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/cimentadaj/perccalc/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@briatte & @amoeba, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @majensen know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cimentadaj/perccalc/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@cimentadaj) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cimentadaj/perccalc/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@cimentadaj) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @briatte, @amoeba it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01796/joss.01796/10.21105.joss.01796.pdf)

**Comment by majensen** [comment]
BTW, @briatte, thanks for volunteering to review! (I took you at your word...)

**Comment by briatte** [comment]
@majensen No problem. I'm planning to review the package next week, probably Thursday or Friday.

**Comment by amoeba** [comment]
Hey @majensen, @cimentadaj, I've conducted my first pass at the review checklist and things look very good overall. I have some items I'd like @cimentadaj to address so at this point my review is a conditional accept. See: https://github.com/cimentadaj/perccalc/issues/2.

**Comment by briatte** [comment]
Hi @majensen, @cimentadaj and @amoeba 

I'm also done with [my review](https://github.com/cimentadaj/perccalc/issues/2#issuecomment-544239961): conditional accept with very minor revisions (some of which are nitpicky to the point that @cimentadaj might reasonably decide to ignore them entirely).

**Comment by cimentadaj** [comment]
Hi everyone

Thanks for the reviews. I'm probably gonna check them out first week of November and finish them at that time. Is that good?

**Comment by majensen** [comment]
@cimentadaj sounds good to me. That accords with my schedule too :D 
Thanks all very much!

**Comment by cimentadaj** [comment]
I've answered to all comments from both reviewers [here](https://github.com/cimentadaj/perccalc/issues/2). As I outlined there, I'm happy to review some points if they feel like their points weren't addressed. 

Thank you both for reviewing the paper/package, the comments have been very helpful to ship the next version to CRAN flawlessly!

**Comment by majensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01796/joss.01796/10.21105.joss.01796.pdf)

**Comment by majensen** [comment]
@briatte, @amoeba -- based on @cimentadaj comments at [issue 2](https://github.com/cimentadaj/perccalc/issues/2), are you guys prepared to check off the remaining boxes? 
Assuming so, @cimentadaj, would you like to merge your review branch into master?

**Comment by cimentadaj** [comment]
@majensen, we're almost there. Still elucidating whether we keep/remove the example section. I think we'll have this figured out by the end of the week.

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1177/2332858416657343 may be missing for title: Recent trends in income, racial, and ethnic school readiness gaps at kindergarten entry
- https://doi.org/10.1177/2332858416649593 may be missing for title: Patterns of cross-national variation in the association between income and academic achievement
- https://doi.org/10.1007/springerreference_205246 may be missing for title: Categorical data analysis
- https://doi.org/10.2307/589632 may be missing for title: Intergenerational class mobility in three Western European societies: England, France and Sweden

INVALID DOIs

- None
```

**Comment by amoeba** [comment]
@majensen my review is now an _Accept_ after @cimentadaj 's recent change to the paper, removing the examples, as per https://github.com/cimentadaj/perccalc/issues/2#issuecomment-558031545.

**Comment by briatte** [comment]
Same here, I'm also Accept at that stage.

**Comment by majensen** [comment]
@amoeba and @briatte thanks very much; and thanks @cimentadaj for your hard work and responsiveness. 
@briatte, can you review your checklist and make sure everything is checked off; there are a couple of ticks necessary and I don't want to assume. 

I will perform my final proofreading tasks - might lead to a PR - and then will make the formal recommendation.

**Comment by majensen** [comment]
(right after @cimentadaj merges the review branch...)

**Comment by majensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01796/joss.01796/10.21105.joss.01796.pdf)

**Comment by majensen** [comment]
@cimentadaj : created https://github.com/cimentadaj/perccalc/pull/7 with some minor edits

**Comment by majensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01796/joss.01796/10.21105.joss.01796.pdf)

**Comment by majensen** [comment]
@cimentadaj - Here are the final steps. Can I get you to create a tag for the latest master, and then archive that tag with [Zenodo](https://zenodo.org/) or similar? Then please provide the DOI from the archive in this thread. I will push the recommendation from there to the editors-in-chief.
Thanks!!

**Comment by majensen** [comment]
(BTW, here's an overview for Zenodo, if you haven't used it before: https://github.com/openjournals/joss-reviews/issues/1839#issuecomment-560048729)

**Comment by cimentadaj** [comment]
Thanks, the DOI is 10.5281/zenodo.3559855 and can be found [here](https://zenodo.org/record/3559855).

**Comment by majensen** [comment]
@openjournals/joss-eics, I recommend this paper for publication and ask that you begin the final steps. Thanks!

**Comment by danielskatz** [comment]
Thanks - will do shortly

**Comment by danielskatz** [comment]
@majensen - if you can tell whedon the archive and version, that helps the AEiC...  (See https://joss.readthedocs.io/en/latest/editing.html#after-reviewers-recommend-acceptance)

**Comment by majensen** [comment]
Thanks @danielskatz will do

**Comment by majensen** [comment]
@whedon set 10.5281/zenodo.3559855 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3559855" target="_blank">10.5281/zenodo.3559855</a> is the archive.

**Comment by majensen** [comment]
@whedon set v1.0.5 as version

**Comment by whedon** [comment]
OK. v1.0.5 is the version.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01796/joss.01796/10.21105.joss.01796.pdf)

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1177/2332858416657343 is OK
- https://doi.org/10.1177/2332858416653924 is OK
- https://doi.org/10.1177/2332858416649593 is OK
- https://doi.org/10.2307/589632 is OK

MISSING DOIs

- https://doi.org/10.1007/springerreference_205246 may be missing for title: Categorical data analysis
- https://doi.org/10.18637/jss.v045.i03 may be missing for title: mice: Multivariate Imputation by Chained Equations in R

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @cimentadaj - please add the DOI (https://doi.org/10.18637/jss.v045.i03) for the van Buuren paper to you bib file.  Also, should there be some link for the reference to Ordinal?

**Comment by cimentadaj** [comment]
Thanks @danielskatz, should be fixed now for the van Buuren paper and the Agresti book.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01796/joss.01796/10.21105.joss.01796.pdf)

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1177/2332858416657343 is OK
- https://doi.org/10.1177/2332858416653924 is OK
- https://doi.org/10.1177/2332858416649593 is OK
- 10.1002/0470114754 is OK
- https://doi.org/10.2307/589632 is OK
- https://doi.org/10.18637/jss.v045.i03 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
There are a number of other small changes, which I've suggested fixes for in https://github.com/cimentadaj/perccalc/pull/8 - please merge, or let me know which you disagree with.

**Comment by danielskatz** [comment]
👋 @briatte - There are a number of checkboxes that you didn't check.  Can you check them please, or explain why they can't yet be checked?

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01796/joss.01796/10.21105.joss.01796.pdf)

**Comment by majensen** [comment]
Hey @briatte, sorry, we need you to check off the rest of the boxes on your review - thanks

**Comment by majensen** [comment]
@danielskatz : My guess is @briatte is OOO, since he is usu. very responsive. In view of comment from @briatte 's comment at https://github.com/openjournals/joss-reviews/issues/1796#issuecomment-558501728 and previous, I would recommend moving forward with the publication.

**Comment by danielskatz** [comment]
If you are sure this is ok, please check the missing box for @briatte, then let me know, and I will do the further processing in the next 24 hours.

**Comment by majensen** [comment]
@danielskatz boxes checked  thanks

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1177/2332858416657343 is OK
- https://doi.org/10.1177/2332858416653924 is OK
- https://doi.org/10.1177/2332858416649593 is OK
- 10.1002/0470114754 is OK
- https://doi.org/10.2307/589632 is OK
- https://doi.org/10.18637/jss.v045.i03 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1164

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1164, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1203648300047650816) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1165
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01796](https://doi.org/10.21105/joss.01796)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @briatte and @amoeba for reviewing and @majensen for editing!
And congratulations to @cimentadaj!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01796/status.svg)](https://doi.org/10.21105/joss.01796)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01796">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01796/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01796/status.svg
   :target: https://doi.org/10.21105/joss.01796
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01796/status.svg)](https://doi.org/10.21105/joss.01796)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by cimentadaj** [comment]
Thanks to everyone for the great review!
