### ISSUE TITLE
[REVIEW]: modelStudio: Interactive Studio with Explanations for ML Predictive Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1798]
**Submitting author:** @hbaniecki (<a href="http://orcid.org/0000-0001-6661-5364">Hubert Baniecki</a>)
**Repository:** <a href="https://github.com/ModelOriented/modelStudio" target ="_blank">https://github.com/ModelOriented/modelStudio</a>
**Version:** v0.1.9
**Editor:** @terrytangyuan
**Reviewer:** @acolum, @expectopatronum
**Archive:** <a href="https://doi.org/10.5281/zenodo.3527770" target="_blank">10.5281/zenodo.3527770</a>

## Status

[![status](https://joss.theoj.org/papers/9eec8c9d1969fbd44b3ea438a74af911/status.svg)](https://joss.theoj.org/papers/9eec8c9d1969fbd44b3ea438a74af911)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/9eec8c9d1969fbd44b3ea438a74af911"><img src="https://joss.theoj.org/papers/9eec8c9d1969fbd44b3ea438a74af911/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/9eec8c9d1969fbd44b3ea438a74af911/status.svg)](https://joss.theoj.org/papers/9eec8c9d1969fbd44b3ea438a74af911)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ModelOriented/modelStudio" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@acolum & @expectopatronum, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @terrytangyuan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ModelOriented/modelStudio">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@hbaniecki) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ModelOriented/modelStudio">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@hbaniecki) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @acolum, @expectopatronum it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01798/joss.01798/10.21105.joss.01798.pdf)

**Comment by hbaniecki** [comment]
Great! I am aware that i need to fix paper.bib file to properly code references. I will probably shorten the example. Then Figure 1 should fit one page earlier (same with Figure 2).

**Comment by hbaniecki** [comment]
@expectopatronum

**Comment by acolum** [comment]
Everything in the software and documentation looks good, but in the paper, there's some spelling, grammar, and citation errors.

**Comment by hbaniecki** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01798/joss.01798/10.21105.joss.01798.pdf)

**Comment by hbaniecki** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01798/joss.01798/10.21105.joss.01798.pdf)

**Comment by acolum** [comment]
The references and citations look great, but I'm still noticing a few spelling errors in the first paragraph under "Introduction" and the paragraph under "Conclusions."

**Comment by expectopatronum** [comment]
Yes, I also found several typos / missing articles. I marked them in the PDF: [10.21105.joss.01798_typos.pdf](https://github.com/openjournals/joss-reviews/files/3749652/10.21105.joss.01798_typos.pdf)

**Comment by hbaniecki** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01798/joss.01798/10.21105.joss.01798.pdf)

**Comment by hbaniecki** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01798/joss.01798/10.21105.joss.01798.pdf)

**Comment by hbaniecki** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01798/joss.01798/10.21105.joss.01798.pdf)

**Comment by hbaniecki** [comment]
Hopefully it is clean now.

**Comment by hbaniecki** [comment]
Hi! I would like to answer any further questions or resolve remarks to finish the review process (hopefully, by the end of the week) . 🔜 🔚 @acolum @expectopatronum

**Comment by acolum** [comment]
@hbaniecki Everything looks great, but there's still a few typos in the paper. In the second sentence under "Introduction," can you correct the spelling of "beeing" to "being" and "lead" to "leads"? After these are fixed, I'd be happy to approve everything for publication.

**Comment by expectopatronum** [comment]
Same here, after the typos are fixed, I can accept the paper.

**Comment by hbaniecki** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01798/joss.01798/10.21105.joss.01798.pdf)

**Comment by acolum** [comment]
Looks great to me! I'm finished with my review and can now recommend this package and paper for publication.

**Comment by expectopatronum** [comment]
Same here!

**Comment by hbaniecki** [comment]
@terrytangyuan

**Comment by terrytangyuan** [comment]
Thanks everyone! 

At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

The title of the archive is the same as the JOSS paper title
That the authors of the archive are the same as the JOSS paper authors
I can then move forward with accepting the submission.

**Comment by hbaniecki** [comment]
Hi @terrytangyuan !
I am sorry, that it took so long but I had to wait for the finalized new version. 
It will be v0.1.9 and here is the link: https://zenodo.org/record/3527770.

**Comment by hbaniecki** [comment]
@whedon set v0.1.9 as version

**Comment by whedon** [comment]
I'm sorry @hbaniecki, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by hbaniecki** [comment]
well, it will be `v0.1.9` and `10.5281/zenodo.3527770`

**Comment by terrytangyuan** [comment]
@whedon set v0.1.9 as version

**Comment by whedon** [comment]
OK. v0.1.9 is the version.

**Comment by terrytangyuan** [comment]
@whedon set 10.5281/zenodo.3527770 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3527770" target="_blank">10.5281/zenodo.3527770</a> is the archive.

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1083

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1083, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.21105/joss.01444 is OK

MISSING DOIs

- https://doi.org/10.18653/v1/n16-3020 may be missing for title: "Why Should I Trust You?": Explaining the Predictions of Any Classifier
- https://doi.org/10.32614/rj-2018-072 may be missing for title: Explanations of model predictions with live and breakDown packages
- https://doi.org/10.21105/joss.00786 may be missing for title: iml: An R package for Interpretable Machine Learning
- https://doi.org/10.32614/rj-2017-016 may be missing for title: pdp: An R Package for Constructing Partial Dependence Plots

INVALID DOIs

- None
```

**Comment by terrytangyuan** [comment]
@hbaniecki Could you fix the missing DOIs listed above?

**Comment by hbaniecki** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01798/joss.01798/10.21105.joss.01798.pdf)

**Comment by hbaniecki** [comment]
@terrytangyuan I have added missing DOIs to the .bib file.

**Comment by terrytangyuan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.18653/v1/n16-3020 is OK
- 10.32614/rj-2018-072 is OK
- 10.21105/joss.01444 is OK
- 10.21105/joss.00786 is OK
- 10.32614/rj-2017-016 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.18653/v1/n16-3020 is OK
- 10.32614/rj-2018-072 is OK
- 10.21105/joss.01444 is OK
- 10.21105/joss.00786 is OK
- 10.32614/rj-2017-016 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1084

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1084, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by terrytangyuan** [comment]
This paper looks good to me now! Handing over to @openjournals/joss-eics!

**Comment by kyleniemeyer** [comment]
Hi @hbaniecki, I made a few edits to the paper and references, if you could merge these:
https://github.com/ModelOriented/modelStudio/pull/31 and https://github.com/ModelOriented/modelStudio/pull/32

**Comment by hbaniecki** [comment]
Hi @kyleniemeyer, I merged your PR.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01798/joss.01798/10.21105.joss.01798.pdf)

**Comment by kyleniemeyer** [comment]
@hbaniecki sorry, one last fix I noticed when reviewing: https://github.com/ModelOriented/modelStudio/pull/33

**Comment by hbaniecki** [comment]
@kyleniemeyer np. I merged.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01798/joss.01798/10.21105.joss.01798.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.18653/v1/n16-3020 is OK
- 10.32614/RJ-2018-072 is OK
- 10.21105/joss.01444 is OK
- 10.21105/joss.00786 is OK
- 10.32614/rj-2017-016 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1090

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1090, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1191783422257172480) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1091
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01798](https://doi.org/10.21105/joss.01798)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @hbaniecki on your article's publication in JOSS! Many thanks to @acolum and  @expectopatronum for reviewing this, and @terrytangyuan for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01798/status.svg)](https://doi.org/10.21105/joss.01798)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01798">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01798/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01798/status.svg
   :target: https://doi.org/10.21105/joss.01798
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01798/status.svg)](https://doi.org/10.21105/joss.01798)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by hbaniecki** [comment]
wow even after so many reviews i can see a typo. @kyleniemeyer is it possible to fix the paper after the publication?

**Comment by kyleniemeyer** [comment]
Oh no! Um, I think so. Can you fix the source file and let us know? (@arfon?)

**Comment by hbaniecki** [comment]
I feel ashamed but hope that it can be updated. Fixed `paper.md`.

**Comment by arfon** [comment]
> Oh no! Um, I think so. Can you fix the source file and let us know? (@arfon?)

No problem. Paper updated based on the latest `paper.md` in `master`. FWIW, the new PDF might not show up for a few hours as there's caching in place for the PDFs on the JOSS site.
