### ISSUE TITLE
[PRE REVIEW]: Cine: A solar-pumped fluorescence model for cometary atmospheres

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#180]
**Submitting author:** @migueldvb (<a href="http://orcid.org/0000-0002-0455-9384">Miguel de Val-Borro</a>)
**Repository:** <a href="https://github.com/migueldvb/cine" target ="_blank">https://github.com/migueldvb/cine</a>
**Version:** v0.2
**Editor:** @arfon
**Reviewer:** @eteq

**What this issue is for**

Thanks for submitting your paper to JOSS @migueldvb. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: @eteq - would you be willing to review this submission for JOSS? You can learn more about what that entails here: http://joss.theoj.org/about#reviewer_guidelines

**Comment by eteq** [comment]
@arfon - can do, although probably not until late this week/early next... If that's ok, then I'm in.

**Comment by arfon** [comment]
> @arfon - can do, although probably not until late this week/early next... If that's ok, then I'm in.

👍 that would be great.

**Comment by arfon** [comment]
@whedon assign @eteq as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @eteq

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/182. Feel free to close this issue now!

**Comment by arfon** [comment]
@eteq the actual review issue is over in #182 - please head over there to carry out your review and give feedback as required.
