### ISSUE TITLE
[REVIEW]: Distant Viewing Toolkit: A Python Package for the Analysis of Visual Culture

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1800]
**Submitting author:** @statsmaths (<a href="http://orcid.org/0000-0003-0576-0669">Taylor Arnold</a>)
**Repository:** <a href="https://github.com/distant-viewing/dvt" target ="_blank">https://github.com/distant-viewing/dvt</a>
**Version:** v0.3.0
**Editor:** @arfon
**Reviewer:** @jgonggrijp, @elektrobohemian
**Archive:** <a href="https://doi.org/10.5281/zenodo.3614034" target="_blank">10.5281/zenodo.3614034</a>

## Status

[![status](https://joss.theoj.org/papers/a12e31a189dd7a10e28e6437f5a98ad7/status.svg)](https://joss.theoj.org/papers/a12e31a189dd7a10e28e6437f5a98ad7)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a12e31a189dd7a10e28e6437f5a98ad7"><img src="https://joss.theoj.org/papers/a12e31a189dd7a10e28e6437f5a98ad7/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a12e31a189dd7a10e28e6437f5a98ad7/status.svg)](https://joss.theoj.org/papers/a12e31a189dd7a10e28e6437f5a98ad7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/distant-viewing/dvt" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jgonggrijp & @elektrobohemian, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/distant-viewing/dvt">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@statsmaths) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/distant-viewing/dvt">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@statsmaths) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by arfon** [comment]
@jgonggrijp, @elektrobohemian - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by arfon** [comment]
@jgonggrijp, @elektrobohemian - it doesn't look like you've made any progress on your reviews here. Do you think you could complete them in the next two weeks?

**Comment by jgonggrijp** [comment]
@arfon In my case, that was to be expected. As I mentioned [in the pre-review](https://github.com/openjournals/joss-reviews/issues/1758#issuecomment-536972108), I wouldn't be able to start before yesterday in any case.

I'll try to do the review within the next two weeks.

**Comment by arfon** [comment]
> @arfon In my case, that was to be expected. As I mentioned in the pre-review, I wouldn't be able to start before yesterday in any case.

Apologies @jgonggrijp - I failed to read back up the issue to see this.

> I'll try to do the review within the next two weeks.

Perfect, thanks!

**Comment by arfon** [comment]
@elektrobohemian - could you give us an ETA on your review?

**Comment by jgonggrijp** [comment]
@arfon I'm a bit delayed. I'm trying to finish upcoming Friday, 29. November.

**Comment by arfon** [comment]
> @elektrobohemian - could you give us an ETA on your review?

I just emailed @elektrobohemian to ask them to give us an update on their review.

**Comment by statsmaths** [comment]
Hi everyone. I know things get slowed down around the winter holidays, but wanted to check in now that things are starting to pick up again. I answered some issues that @jgonggrijp opened in the dvt repository, but had not seen anything since then.

If there are any issues people are running into, please let us know. If additional reviewers are needed I can try to recommend someone. Thanks again for everyone's help!

**Comment by arfon** [comment]
Thanks for the update @statsmaths. I've also heard back over email from @elektrobohemian that they should be starting their review imminently.

**Comment by jgonggrijp** [comment]
@statsmaths @arfon Just letting you know that this is still on my agenda. I hope to continue (and preferably finish) this Friday.

**Comment by jgonggrijp** [comment]
@statsmaths @arfon I completed my review. I just opened three new issues (referenced right above this post), one of which is acceptance-blocking in my opinion (https://github.com/distant-viewing/dvt/issues/17) and one of which I'm not sure whether it should be acceptance-blocking or not (https://github.com/distant-viewing/dvt/issues/16). The latter might or might not be due to “limited options” being an euphemism for “no options”.

The third issue (https://github.com/distant-viewing/dvt/issues/15) is definitely non-blocking as far as I'm concerned. The package can be accepted with this issue still open.

**Comment by statsmaths** [comment]
@jgonggrijp Thanks for all of the really helpful comments. I pushed three commits that should
resolve the three issues that you opened.

**Comment by statsmaths** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01800/joss.01800/10.21105.joss.01800.pdf)

**Comment by jgonggrijp** [comment]
@statsmaths Welcome. dvt is a very interesting and well-documented package.
@arfon I see no blockers after the above fixes by @statsmaths.

**Comment by elektrobohemian** [comment]
I really like the software and the documented installation process as it is very mature. This is why I tried to install the software without relying on my background language. Hence, all opened issues are non-blocking as far as I am concerned.
I took a basic Ubuntu 18.04.3 LTS installation and tried to solve all issues by copy-and-pasting all occuring issues. Under Mac OS, I tried to run everything in a zsh environment.

Besides the issues discussed in the dvt project, I would suggest to extend the paper a little. As the paper als addresses layperson users, you would like to be a little more informative regarding the local web server section. I guess that not all DH researches might be familiar with the Java script-related security policies of all browsers.

I strongly recommend the dvt package for publication. My minor issues could be resolved after publication.

**Comment by elektrobohemian** [comment]
for the sake of completeness, the Mac OS values:

data  data_left  data_right
0 -1108      -1113       -1103
1 -1546      -1552       -1539
2 -1123      -1121       -1125
3 -1007      -1008       -1006
4 -1258      -1262       -1253
And
   frame_start  frame_end          rms
0            0         50   917.916747
1           50        200  1208.046528
2          200        220   997.259411

**Comment by arfon** [comment]
@elektrobohemian - many thanks for your feedback here! As you work through the checklist could you please be sure to tick the checkboxes at the top of the issue?

**Comment by elektrobohemian** [comment]
done.

**Comment by arfon** [comment]
@statsmaths - looks like this is getting pretty close to being accepted here 😄. Can you confirm that you've made all of the changes you planned to based on the feedback from @jgonggrijp & @elektrobohemian

**Comment by statsmaths** [comment]
Thanks @elektrobohemian for all of the helpful feedback. I just pushed responses that
resolve three of the four issues you opened. The only one still open is the issue with the
web application on macOS, as I cannot replicate it on my mac (it currently runs on Firefox,
Safari and Chrome for me). Not sure if that's blocking for the publication or not. 

@arfon, other than a potential fix to the web server issue all of the changes have been 
made at this point.

**Comment by elektrobohemian** [comment]
regarding the web server: no, it's not as @jgonggrijp couldn't replicate it neither. at least in my opinion.

regarding the Ubuntu/virtualenv issue I wouldn't consider this blocking either as it would only happen to layperson users which might also not rely on a Ubuntu LTS. a layperson would prefer Anaconda IMHO. As said above, I was only checking these scenarios as everything else worked so fine.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by arfon** [comment]
@statsmaths - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by statsmaths** [comment]
```
@whedon generate pdf
```

**Comment by statsmaths** [comment]
@arfon Great. Here is the DOI of the updated package. Thanks again to everyone!

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3614034.svg)](https://doi.org/10.5281/zenodo.3614034)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3614034 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3614034" target="_blank">10.5281/zenodo.3614034</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/digitalsh/fqz013 is OK
- 10.22148/16.043 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-319-54226-3_5 may be missing for title: Task-driven programming pedagogy in the digital humanities
- https://doi.org/10.1109/fg.2018.00020 may be missing for title: Vggface2: A dataset for recognising faces across pose and age
- https://doi.org/10.1007/3-540-45103-x_50 may be missing for title: Two-frame motion estimation based on polynomial expansion
- https://doi.org/10.5749/movingimage.18.1.0080 may be missing for title: Building a Crowdsourcing Platform for the Analysis of Film Colors
- https://doi.org/10.1109/fg.2017.82 may be missing for title: Face detection with the faster R-CNN
- https://doi.org/10.1109/tsp.2015.7296366 may be missing for title: Color image (dis) similarity assessment and grouping based on dominant colors
- https://doi.org/10.1007/978-3-030-04212-7_44 may be missing for title: Recurrent RetinaNet: A Video Object Detection Model Based on Focal Loss
- https://doi.org/10.1109/cvpr.2015.7298682 may be missing for title: Facenet: A unified embedding for face recognition and clustering
- https://doi.org/10.1109/saner.2017.7884606 may be missing for title: Code of conduct in open source projects
- https://doi.org/10.1093/llc/fqy085 may be missing for title: The visual digital turn: Using neural networks to study historical images

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1238

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1238, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@statsmaths - could you check if any of the DOIs that Whedon has found are correct? If they are, please go ahead and add them to your bibtex file (without the `https://doi.org/` preamble).

**Comment by arfon** [comment]
@statsmaths - I think this PR is correct too: https://github.com/distant-viewing/dvt/pull/22

**Comment by statsmaths** [comment]
Okay, merged PR and put all the DOIs into the bibles file.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1800 with the following error: 

 W, [2020-01-20 21:37:53#804]  WARN -- : Lexer: unbalanced braces at 403; brace level 0; mode :literal.
/app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/bibtex_parser.rb:45:in `block in generate_citations': undefined method `key' for #<BibTeX::Error:0x0000000007811d28> (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/gems/bibtex-ruby-5.0.1/lib/bibtex/bibliography.rb:149:in `each'
	from /app/vendor/bundle/ruby/2.4.0/gems/bibtex-ruby-5.0.1/lib/bibtex/bibliography.rb:149:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/bibtex_parser.rb:41:in `generate_citations'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/compilers.rb:245:in `crossref_from_markdown'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/compilers.rb:21:in `generate_crossref'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:95:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:79:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@statsmaths - think this unmatched `}` is causing things to blow up: https://github.com/distant-viewing/dvt/blob/master/paper/paper.bib#L4

**Comment by statsmaths** [comment]
Yes, your right (for some reason my pandoc compiled anyway). Fixed in 5f880da.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/digitalsh/fqz013 is OK
- 10.22148/16.043 is OK
- 10.1007/978-3-319-54226-3_5 is OK
- 10.1109/fg.2018.00020 is OK
- 10.1007/3-540-45103-x_50 is OK
- 10.5749/movingimage.18.1.0080 is OK
- 10.1109/fg.2017.82 is OK
- 10.1109/tsp.2015.7296366 is OK
- 10.1007/978-3-030-04212-7_44 is OK
- 10.1109/cvpr.2015.7298682 is OK
- 10.1109/saner.2017.7884606 is OK
- 10.1093/llc/fqy085 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1239

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1239, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1219381803892559872) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1240
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01800](https://doi.org/10.21105/joss.01800)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@jgonggrijp, @elektrobohemian - many thanks for your reviews here ✨ 

@statsmaths - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01800/status.svg)](https://doi.org/10.21105/joss.01800)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01800">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01800/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01800/status.svg
   :target: https://doi.org/10.21105/joss.01800
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01800/status.svg)](https://doi.org/10.21105/joss.01800)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/digitalsh/fqz013 is OK
- 10.22148/16.043 is OK
- 10.1007/978-3-319-54226-3_5 is OK
- 10.1109/fg.2018.00020 is OK
- 10.1007/3-540-45103-x_50 is OK
- 10.5749/movingimage.18.1.0080 is OK
- 10.1109/fg.2017.82 is OK
- 10.1109/tsp.2015.7296366 is OK
- 10.1007/978-3-030-04212-7_44 is OK
- 10.1109/cvpr.2015.7298682 is OK
- 10.1109/saner.2017.7884606 is OK
- 10.1093/llc/fqy085 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```
