### ISSUE TITLE
[PRE REVIEW]: MDL Suite: A language, generator and compiler for describing mazes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1802]
**Submitting author:** @Akash-Nag (<a href="http://orcid.org/0000-0003-0363-2698">Akash Nag</a>)
**Repository:** <a href="https://github.com/Akash-Nag/MDL-Suite" target ="_blank">https://github.com/Akash-Nag/MDL-Suite</a>
**Version:** 1.0
**Editor:** @drvinceknight
**Reviewers:** @rreinecke, @gradvohl

**Author instructions**

Thanks for submitting your paper to JOSS @Akash-Nag. **Currently, there isn't an JOSS editor assigned** to your paper.

@Akash-Nag if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01802/joss.01802/10.21105.joss.01802.pdf)

**Comment by labarba** [comment]
@Akash-Nag — thanks for your submission to JOSS. From a quick inspection of the submission it's not obvious that it meets our [submission criteria](http://joss.theoj.org/about#submission_requirements). In particular, this item:

> Your software should have an obvious research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)? The section [_'what should my paper contain'_](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) has some guidance for the sort of content we're looking to be present in the `paper.md`.

**Comment by Akash-Nag** [comment]
I am writing to resolve your query regarding the research application
of our proposed software / paper titled "MDL Suite: A language,
generator and compiler for describing mazes".

Consider a research paper which aims to propose a new maze solving
algorithm [1][2][3][4][5][6][7][8][9][10]. Writing such a paper
typically involves the following steps:

1. Develop the method/algorithm and write a program for it
2. Test the program against hundreds of random mazes and collect the results
3. Analyze the results to judge the performance of the algorithm
4. Generate some images of some typical mazes, and show the paths
taken by the solver which makes it more efficient than its competitors
5. Combine the algorithm, results, examples (images) into the paper

Our proposed MDL Suite contains 2 programs: a maze generator and a
maze compiler. The maze generator can be utilized in helping with
step-2 (above) and the compiler can be used to generate the maze
images (step-4). Therefore, the software has an obvious research
application. In absence of the software, researchers face many
problems as outlined in the submitted paper.

Now, let us consider a typical paper published in JOSS: e.g. Ravi et
al. (2019) [11] which discusses a file-format (similar to our proposed
MDL format) as well as a Python package which helps in MRI pulse
design (analogous to our MDL generator) and then exports the design
into a .seq formatted file (similar to ours), which can then be used
by a MRI machine. Researchers would typically design test-cases to run
on the MRI machine and then analyze the results obtained (similar to
Step-2 above). If we could discount the fact that the application of
our software is something as trivial as a maze whereas some other
papers apply to more serious domains of medicine or astrophysics, it
will be apparent that our proposed software has a similar application
to research as other software already accepted by your journal.

I hope that I have addressed your concerns but should you have any
further queries, please feel free to revert back to me.

REFERENCES
------------------------
[1]	Wyard-Scott, L., and Q-HM Meng. "A potential maze solving
algorithm for a micromouse robot." IEEE Pacific Rim Conference on
Communications, Computers, and Signal Processing. Proceedings. IEEE,
1995.

[2]	Mishra, Swati, and Pankaj Bande. "Maze solving algorithms for
micro mouse." 2008 IEEE International Conference on Signal Image
Technology and Internet Based Systems. IEEE, 2008.

[3]	Dang, Hongshe, Jinguo Song, and Qin Guo. "An efficient algorithm
for robot maze-solving." 2010 Second International Conference on
Intelligent Human-Machine Systems and Cybernetics. Vol. 2. IEEE, 2010.

[4]	Cai, Jianping, et al. "An algorithm of micromouse maze solving."
2010 10th IEEE International Conference on Computer and Information
Technology. IEEE, 2010.

[5]	Zhang, Ya Juan, Zi Li Zhang, and Yong Deng. "An improved maze
solving algorithm based on an amoeboid organism." 2011 Chinese Control
and Decision Conference (CCDC). IEEE, 2011.

[6]	Elshamarka, Ibrahim, and Abu Bakar Sayuti Saman. "Design and
implementation of a robot for maze-solving using flood-fill
algorithm." International Journal of Computer Applications 56.5
(2012).

[7]	Willardson, David M. "Analysis of micromouse maze solving
algorithm." Learning from Data (2001).

[8]	He, Shao-Bo, and Ke-Hui Sun. "Design and optimization of
micro-mouse solving the maze algorithm based on central method."
Jisuanji Xitong Yingyong- Computer Systems and Applications 21.9
(2012): 79-82.

[9]	Saman, Abu Bakar Sayuti, and Issa Abdramane. "Solving a
reconfigurable maze using hybrid wall follower algorithm." (2013).

[10]	Babula, Michał. "Simulated maze solving algorithms through
unknown mazes." Organizing and Program Committee 13 (2009).

[11]	Ravi et al., (2019). PyPulseq: A Python Package for MRI Pulse
Sequence Design. Journal of Open Source Software, 4(42), 1725,
https://doi.org/10.21105/joss.01725


Thanks & Regards
Akash Nag
Department of Computer Science
M.U.C. Women's College,
Burdwan 713104, West Bengal, India
Mobile: (+91) 98322-58023
E-mail: nag.akash.cs@gmail.com

**Comment by labarba** [comment]
Thanks for the explanation. 

This PR should solve your broken citations: https://github.com/Akash-Nag/MDL-Suite/pull/1

**Comment by labarba** [comment]
@drvinceknight 👋  — Could you handle this submission as editor?
**MDL Suite: A language, generator and compiler for describing mazes**
https://github.com/Akash-Nag/MDL-Suite
See the author's explanation of research uses: https://github.com/openjournals/joss-reviews/issues/1802#issuecomment-541418372

**Comment by drvinceknight** [comment]
> Could you handle this submission as editor?

Yup, no problem.

**Comment by drvinceknight** [comment]
@whedon assign @drvinceknight as editor

**Comment by whedon** [comment]
OK, the editor is @drvinceknight

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01802/joss.01802/10.21105.joss.01802.pdf)

**Comment by drvinceknight** [comment]
@Akash-Nag would you have any suggestions for reviewers of this paper?

**Comment by Akash-Nag** [comment]
No, I do not have any preferences/suggestions regarding the choice of
reviewers.

Thanks & Regards,

**Comment by drvinceknight** [comment]
@hausen, @pragyansmita, @gradvohl, @rreinecke, @BasTesterink would you be interested in reviewing this paper on maze generation for JOSS? I don't think it fits immediately within your areas of expertise but it is somewhat related and you all have knowledge of java.

If you have not reviewed for JOSS before, in my experience it takes less time than reviewing for a traditional journal and there is documentation here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html I'd also be very happy to answer any questions you might have.

**Comment by drvinceknight** [comment]
Fantastic thanks @rreinecke, once we have a second reviewer I'll open another issue where the review itself will take place.

**Comment by drvinceknight** [comment]
@whedon assign @rreinecke as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rreinecke

**Comment by gradvohl** [comment]
Hello @drvinceknight. I can review the paper if JOSS still needs a reviewer for it.
Best.

**Comment by drvinceknight** [comment]
Fantastic, thank you @gradvohl!

**Comment by drvinceknight** [comment]
@whedon add @gradvohl as reviewer

**Comment by whedon** [comment]
OK, @gradvohl is now a reviewer

**Comment by drvinceknight** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1815. Feel free to close this issue now!

**Comment by drvinceknight** [comment]
@gradvohl @rreinecke the review now takes place on #1815, if you have any questions don't hesitate to get in touch.
