### ISSUE TITLE
[PRE REVIEW]: CoralP: Flexible visualization of the human phosphatome

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1803]
**Submitting author:** @dphansti (<a href="http://orcid.org/0000-0003-2123-0051">Douglas Phanstiel</a>)
**Repository:** <a href="https://github.com/PhanstielLab/coralp" target ="_blank">https://github.com/PhanstielLab/coralp</a>
**Version:** v1.0.0
**Editor:** @majensen
**Reviewers:** @daissi, @stulacy

**Author instructions**

Thanks for submitting your paper to JOSS @dphansti. **Currently, there isn't an JOSS editor assigned** to your paper.

@dphansti if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01803/joss.01803/10.21105.joss.01803.pdf)

**Comment by labarba** [comment]
👋  @majensen — The authors suggested you as the handling editor for this submission. If you can take it on, please assign yourself with the command `@whedon assign @majensen as editor`.

**Comment by majensen** [comment]
@labarba can do
@whedon assign @majensen as editor

**Comment by majensen** [comment]
@whedon assign @majensen as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by majensen** [comment]
I've reached out to a couple of colleagues via email who may not be familiar with JOSS -- but I will @ -ping them here as well: @seandavi and @dcgenomics.

**Comment by majensen** [comment]
Not getting many bites from my local pool, will go to https://bit.ly/joss-reviewers list next.

**Comment by majensen** [comment]
Hello @kellieotto @daissi @stulacy -- would any of you be able to review this JOSS submission?
I appreciate the consideration - thanks!
--

**Comment by daissi** [comment]
@majensen Yes, I will review this submission.

**Comment by stulacy** [comment]
I'm not familiar with the application area but I could review it from a
technical perspective if you need it
Stuart

**Comment by majensen** [comment]
@daissi @stulacy thanks very much. @stulacy a tech review is very welcome.

**Comment by majensen** [comment]
@whedon assign @daissi as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @daissi

**Comment by majensen** [comment]
@whedon add @stulacy as reviewer

**Comment by whedon** [comment]
OK, @stulacy is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1837. Feel free to close this issue now!

**Comment by majensen** [comment]
Thanks all!
