### ISSUE TITLE
[PRE REVIEW]: mwarp1d: Manual one-dimensional data warping in Python and PyQt

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1804]
**Submitting author:** @0todd0000 (<a href="http://orcid.org/0000-0002-8292-7189">Todd Pataky</a>)
**Repository:** <a href="https://github.com/0todd0000/mwarp1d" target ="_blank">https://github.com/0todd0000/mwarp1d</a>
**Version:** 0.1.0
**Editor:** @trallard
**Reviewers:** @melund, @demotu

**Author instructions**

Thanks for submitting your paper to JOSS @0todd0000. **Currently, there isn't an JOSS editor assigned** to your paper.

@0todd0000 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01804/joss.01804/10.21105.joss.01804.pdf)

**Comment by labarba** [comment]
@trallard 👋  — Could you handle this submission as the editor? 
**mwarp1d: Manual one-dimensional data warping in Python and PyQt**
https://github.com/0todd0000/mwarp1d
(The author suggested @Kevin-Mattheus-Moerman, but he has a high load of submissions right now.)

**Comment by 0todd0000** [comment]
**Suggested reviewers** (from the list):

- melund
- ixjlyons
- CELavecchia
- alcantarar
- abhishektha

**Suggested reviewers** (from GitHub):

- PouyanMehryar
- ivoflipse
- demotu
- cedricmorio

**Comment by 0todd0000** [comment]
Comment re: article proof:

Figure problem:  the figure was not visible in the proof (using HTML tags) so I've updated paper.md in the repository using Markdown image syntax according to JOSS instructions.

Apologies for my mistake!

I have also corrected two other minor errors in the proof. 

Please re-compile the article proof at your convenience.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01804/joss.01804/10.21105.joss.01804.pdf)

**Comment by 0todd0000** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01804/joss.01804/10.21105.joss.01804.pdf)

**Comment by 0todd0000** [comment]
The proof looks OK now.

**Comment by Kevin-Mattheus-Moerman** [comment]
@trallard can you handle this submission?

**Comment by trallard** [comment]
Sure assing it to me @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by trallard** [comment]
Hi @0todd0000  the first thing we have to do to move this review forward is finding a pair of suitable reviewers. Have you got someone in mind already?

You can start by finding some reviewers looking at our list of registered reviewers here <https://bit.ly/joss-reviewers>

**Comment by 0todd0000** [comment]
Hello @trallard, yes I do have a few reviewers in mind. Please see my "Suggested reviewers" message above (sixth message in this thread, sent 10 days ago).

**Comment by 0todd0000** [comment]
Hello, it has been two weeks since our last communication.  Please provide a status update if possible. Do you require additional reviewer suggestions?

**Comment by trallard** [comment]
Thanks for the ping @0todd0000 

---
Dear potential reviewers, 

I am looking for a couple of folks willing and able to review the following JOSS submission:

**Title**: mwarp1d: Manual one-dimensional data warping in Python and PyQt
**description**: Manual one-dimensional data warping and nonlinear registration in Python and PyQt
**repository**: https://github.com/0todd0000/mwarp1d
**documentation**: http://www.spm1d.org/mwarp1d/index.html
**JOSS paper**: <https://github.com/openjournals/joss-papers/blob/joss.01804/joss.01804/10.21105.joss.01804.pdf>

@melund, Morten are you willing and able to take upon this review?
@CELAvecchia, Carolina are you willing and able to take upon this review?
@alcantarar, Ryan are you willing and able to take upon this review?
@abhishektha, Abhishekta are you willing and able to take upon this review?
@ ivoflipse Ivo, are you willing and able to take upon this review?
@ demotu Marcos, are you willing and able to take upon this review?

We are looking for at least two reviewers. The reviewing guidelines for JOSS can be found at <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>

**Comment by demotu** [comment]
Yes, I can review it.

**Comment by melund** [comment]
I can review as well.

**Comment by trallard** [comment]
Excellent, thanks both!

**Comment by trallard** [comment]
@whedon add @melund as reviewer

**Comment by whedon** [comment]
OK, @melund is now a reviewer

**Comment by trallard** [comment]
@whedon add @demotu as reviewer

**Comment by whedon** [comment]
OK, @demotu is now a reviewer

**Comment by trallard** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1870. Feel free to close this issue now!
