### ISSUE TITLE
[PRE REVIEW]: SHGYield

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#181]
**Submitting author:** @roguephysicist (<a href="http://orcid.org/0000-0002-4809-921X">Sean M. Anderson</a>)
**Repository:** <a href="https://github.com/roguephysicist/SHGYield" target ="_blank">https://github.com/roguephysicist/SHGYield</a>
**Version:** v1.0.1
**Editor:** @kyleniemeyer
**Reviewer:** @nicoguaro

**What this issue is for**

Thanks for submitting your paper to JOSS roguephysicist. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @kyleniemeyer - would you be willing to edit this submission for JOSS?

**Comment by kyleniemeyer** [comment]
@arfon 👍 can do.

**Comment by kyleniemeyer** [comment]
@whedon set editor as @kyleniemeyer

**Comment by kyleniemeyer** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by arfon** [comment]
👋 @kyleniemeyer - any luck finding a reviewer for this submission?

**Comment by kyleniemeyer** [comment]
@arfon thanks for the reminder... lost track of this one.

**Comment by kyleniemeyer** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by kyleniemeyer** [comment]
Hi @roguephysicist, do you have any suggestions for domain reviewers? If possible I would like to have at least one person familiar with the subject material take a look.

**Comment by kyleniemeyer** [comment]
Hi @tacaswell @betatim would one or both of you be able to review this submission?

**Comment by roguephysicist** [comment]
Hi @kyleniemeyer, I think that both of them seem like good candidates. Perhaps also @nicoguaro?

Thanks.

**Comment by nicoguaro** [comment]
@kyleniemeyer, I think I can review it. I like the plots in the repo ... so we have a nice beginning.

**Comment by kyleniemeyer** [comment]
@nicoguaro thanks! @tacaswell and @betatim, I do usually prefer to have a second review, so if you are interested & available, please chime in. I will get the review issue formally started, though.

**Comment by kyleniemeyer** [comment]
@whedon assign @nicoguaro as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nicoguaro

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/242. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
Alrighty, @nicoguaro (and possibly @tacaswell & @betatim) we'll head over to #242 for the actual review.
