### ISSUE TITLE
[PRE REVIEW]: MatSurv: Survival analysis and visualization in MATLAB

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1810]
**Submitting author:** @jhcreed (<a href="http://orcid.org/0000-0002-8302-2648">Jordan Creed</a>)
**Repository:** <a href="https://github.com/aebergl/MatSurv" target ="_blank">https://github.com/aebergl/MatSurv</a>
**Version:** v1.0.0
**Editor:** @cMadan
**Reviewers:** @dsurujon, @ManuelaS

**Author instructions**

Thanks for submitting your paper to JOSS @jhcreed. The JOSS editor @cMadan, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jhcreed if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @cMadan it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@cMadan) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1810 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon.rb:135:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-1e4ee47b240d/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@cMadan can you take this one?

**Comment by cMadan** [comment]
@Kevin-Mattheus-Moerman, sure!

@jhcreed, can you take a look at the list of potential reviewers, or others you think may be suitable, and suggest a few potential reviewers? Thanks!

**Comment by jhcreed** [comment]
Potential reviewers would be: acolum, marouenbg, ManuelaS, and dsurujon

**Comment by cMadan** [comment]
@acolum @marouenbg @ManuelaS @dsurujon, would you be available and interested in reviewing this submission?

**Comment by acolum** [comment]
Thank you for contacting me, but I'm not available to review this submission at this time.

**Comment by dsurujon** [comment]
I'd be willing to review this submission

**Comment by cMadan** [comment]
@dsurujon, that would be much appreciated, thank you!

@acolum, no problem, thanks for the prompt response.

@jhcreed, we usually have two reviewers for each submission, so we still need one more.

**Comment by cMadan** [comment]
@whedon add @dsurujon as reviewer

**Comment by whedon** [comment]
OK, @dsurujon is now a reviewer

**Comment by ManuelaS** [comment]
Hi, I could review this submission if you still need another reviewer

**Comment by cMadan** [comment]
@ManuelaS, that would be great, thank you!

@jhcreed @dsurujon @ManuelaS, I am going to start the review process. This will be done in a new GitHub issue--the link will appear below. This will have the reviewer checklists and should be used for the discussing the review process. (More detailed instructions will be included in the review issue.)

**Comment by cMadan** [comment]
@whedon add @ManuelaS as reviewer

**Comment by whedon** [comment]
OK, @ManuelaS is now a reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1830. Feel free to close this issue now!
