### ISSUE TITLE
[REVIEW]: ComplexRegions.jl: A Julia package for regions in the complex plane

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1811]
**Submitting author:** @tobydriscoll (<a href="http://orcid.org/0000-0002-1490-2545">Tobin Driscoll</a>)
**Repository:** <a href="https://github.com/complexvariables/ComplexRegions.jl" target ="_blank">https://github.com/complexvariables/ComplexRegions.jl</a>
**Version:** v0.1.1
**Editor:** @drvinceknight
**Reviewer:** @dlfivefifty, @dpsanders
**Archive:** <a href="https://doi.org/10.5281/zenodo.3548866" target="_blank">10.5281/zenodo.3548866</a>

## Status

[![status](https://joss.theoj.org/papers/73e8c56985d88c36b918c58cc1346d7a/status.svg)](https://joss.theoj.org/papers/73e8c56985d88c36b918c58cc1346d7a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/73e8c56985d88c36b918c58cc1346d7a"><img src="https://joss.theoj.org/papers/73e8c56985d88c36b918c58cc1346d7a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/73e8c56985d88c36b918c58cc1346d7a/status.svg)](https://joss.theoj.org/papers/73e8c56985d88c36b918c58cc1346d7a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/complexvariables/ComplexRegions.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dlfivefifty & @dpsanders, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @drvinceknight know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/complexvariables/ComplexRegions.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@tobydriscoll) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/complexvariables/ComplexRegions.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@tobydriscoll) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dlfivefifty, @dpsanders it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01811/joss.01811/10.21105.joss.01811.pdf)

**Comment by dlfivefifty** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by dlfivefifty** [comment]
I think my review is essentially done. The main thing is referencing related work of IntervalSets.jl and DomainSets.jl, see

https://github.com/complexvariables/ComplexRegions.jl/issues/1

**Comment by drvinceknight** [comment]
Thank you @dlfivefifty :+1: 💪

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01811/joss.01811/10.21105.joss.01811.pdf)

**Comment by dpsanders** [comment]
My main review is now complete.

There is basically nothing written down about how to contribute to the package, but I think it's understood this is done initially via issues, which seems fine to me.

I opened a couple of issues in the repo with suggestions for improvements.

**Comment by drvinceknight** [comment]
Thank @dpsanders and @dlfivefifty, @tobydriscoll if you could confirm when you've addressed the comments that would be great.

**Comment by tobydriscoll** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01811/joss.01811/10.21105.joss.01811.pdf)

**Comment by dpsanders** [comment]
There seems to be a problem with unicode characters in the Julia source code. @drvinceknight what can be done about that?

**Comment by tobydriscoll** [comment]
I'm not married to using unicode for this submission. I've pushed a change that avoids it.

**Comment by tobydriscoll** [comment]
@drvinceknight I think I have addressed the reviewers' comments. Both were quite helpful.

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01811/joss.01811/10.21105.joss.01811.pdf)

**Comment by drvinceknight** [comment]
@dpsanders and @dlfivefifty could you confirm you're happy with the requested modifications? (Thanks again for your time :+1:)

**Comment by dpsanders** [comment]
Good for me, thanks.

**Comment by dpsanders** [comment]
The `References` heading in the PDF didn't come out right.

**Comment by tobydriscoll** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01811/joss.01811/10.21105.joss.01811.pdf)

**Comment by tobydriscoll** [comment]
@dpsanders I needed to put in a blank line. References header is ok now.

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01811/joss.01811/10.21105.joss.01811.pdf)

**Comment by drvinceknight** [comment]
@dlfivefifty could you confirm you're now happy with the paper? 

> Good for me, thanks.

@dpsanders I've taken the liberty to tick the two remaining boxes on your check list ("Community guidelines", "State of the field" and "Reference").

**Comment by dlfivefifty** [comment]
Two comments: 

1. The citation for IntervalSets.jl gives Huybrechs and myself (Olver) too much credit: we’ve made contributions but it was created by @mronian, with many contributions by @timholy
2. The use of “.jl” in package names should be consistent between “ComplexRegions” and “IntervalSets.jl and DomainSets.jl”.

**Comment by tobydriscoll** [comment]
Updates:

1. I have avoided trying to summarize credit for IntervalSets. The paper links to it, where the full history is easy to see. 

2. I have decided to go without `.jl` on all the package names. It's an editorial choice, but seeing it over and over is really clunky.

**Comment by tobydriscoll** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01811/joss.01811/10.21105.joss.01811.pdf)

**Comment by dlfivefifty** [comment]
Ok one last comment: add references for DomainSets and IntervalSets as otherwise it’s not clear how to find them. This could just be links to the github pages

**Comment by tobydriscoll** [comment]
My mistake. I thought adding them as markdown links would get through. I put them in the Refs section instead.

@whedon generate pdf

**Comment by tobydriscoll** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01811/joss.01811/10.21105.joss.01811.pdf)

**Comment by tobydriscoll** [comment]
*sigh* Forgot to brace my capital Js. Trying again.

**Comment by tobydriscoll** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01811/joss.01811/10.21105.joss.01811.pdf)

**Comment by drvinceknight** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10/gf9fzf is OK
- 10.1109/tmi.2004.831226 is OK
- 10.1137/060659119 is OK
- 10.1093/imamat/hxw028 is OK

MISSING DOIs

- https://doi.org/10.2514/3.9819 may be missing for title: Wind-tunnel wall corrections on a two-dimensional plate by conformal mapping
- https://doi.org/10.1006/jcph.1993.1175 may be missing for title: Numerical Conformal Mapping Methods for Exterior Regions with Corners
- https://doi.org/10.1016/0022-247x(79)90086-6 may be missing for title: Capacitance and the conformal module of quadrilaterals
- https://doi.org/10.21236/ada198706 may be missing for title: Potential flow in channels
- https://doi.org/10.1007/bf01418327 may be missing for title: An integral equation method for the numerical conformal mapping of interior, exterior, and doubly-connected domains
- https://doi.org/10.1016/0377-0427(86)90133-0 may be missing for title: Numerical conformal mapping via the Szegő kernel
- https://doi.org/10.1109/22.156612 may be missing for title: Conformal mapping analyses of microstrips with circular and elliptic cross-sections
- https://doi.org/10.1137/0910031 may be missing for title: A Fast Algorithm for the Numerical Evaluation of Conformal Mappings
- https://doi.org/10.1016/0377-0427(86)90141-x may be missing for title: Conformal mapping solution of Laplace’s equation on a polygon with oblique derivative boundary conditions
- https://doi.org/10.1063/1.331373 may be missing for title: The geometric correction factor for a rectangular Hall plate

INVALID DOIs

- None
```

**Comment by drvinceknight** [comment]
@tobydriscoll it looks like a number of DOIs are missing, would you be able to add those please?

@dlfivefifty I believe the references you asked for are included now (but if you could confirm you're happy for this to be accepted that would be great :+1:)

**Comment by dlfivefifty** [comment]
id Suggest adding “.jl” to the references, even if it’s not used in the paper itself: this seems more consistent with how things are cited, particularly with packages whose names otherwise might be confusing (DifferentialEquations.jl). 

But I’ll leave it to the author/editor whether to incorporate this suggestion.

**Comment by tobydriscoll** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10/dnvcn7 is OK
- 10.2514/3.9819 is OK
- 10.1006/jcph.1993.1175 is OK
- 10.1016/0022-247X(79)90086-6 is OK
- 10/gf9fzf is OK
- 10.1137/0911035 is OK
- 10.1007/bf01418327 is OK
- 10.1016/0377-0427(86)90133-0 is OK
- 10.1109/22.156612 is OK
- 10.1137/0910031 is OK
- 10.1016/0377-0427(86)90141-x is OK
- 10.1063/1.331373 is OK
- 10.1109/tmi.2004.831226 is OK
- 10.1137/060659119 is OK
- 10.1093/imamat/hxw028 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by tobydriscoll** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01811/joss.01811/10.21105.joss.01811.pdf)

**Comment by tobydriscoll** [comment]
DOIs fixed and package names updated in the references.

**Comment by drvinceknight** [comment]
Great, thanks.

It's all looking good to me now.

Could you make a tagged release and archive, and report the version number and archive DOI here (note that the archive title should match the paper title: `ComplexRegions.jl: A Julia package for regions in the complex plane`).

**Comment by tobydriscoll** [comment]
It's v0.1.1, DOI is 10.5281/zenodo.3548866.

I hope it's all in order. Thanks!

**Comment by drvinceknight** [comment]
@when set 10.5281/zenodo.3548866 as archive

**Comment by drvinceknight** [comment]
@whedon set 10.5281/zenodo.3548866 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3548866" target="_blank">10.5281/zenodo.3548866</a> is the archive.

**Comment by drvinceknight** [comment]
@whedon set v0.1.1 as version

**Comment by whedon** [comment]
OK. v0.1.1 is the version.

**Comment by drvinceknight** [comment]
@openjournals/joss-eics this paper is ready to be accepted :)

Thanks @dpsanders and @dlfivefifty again for your work reviewing the paper.

**Comment by kthyng** [comment]
@tobydriscoll Hi! I am taking over from here. I made a few changes to your paper so there are not parentheses around references if they are meant to be inline instead. The PR is [here](https://github.com/complexvariables/ComplexRegions.jl/pull/5) and if you agree with it please merge.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01811/joss.01811/10.21105.joss.01811.pdf)

**Comment by kthyng** [comment]
Also a [PR](https://github.com/complexvariables/ComplexRegions.jl/pull/6) for spacing I missed before.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01811/joss.01811/10.21105.joss.01811.pdf)

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10/dnvcn7 is OK
- 10.2514/3.9819 is OK
- 10.1006/jcph.1993.1175 is OK
- 10.1016/0022-247X(79)90086-6 is OK
- 10/gf9fzf is OK
- 10.1137/0911035 is OK
- 10.1007/bf01418327 is OK
- 10.1016/0377-0427(86)90133-0 is OK
- 10.1109/22.156612 is OK
- 10.1137/0910031 is OK
- 10.1016/0377-0427(86)90141-x is OK
- 10.1063/1.331373 is OK
- 10.1109/tmi.2004.831226 is OK
- 10.1137/060659119 is OK
- 10.1093/imamat/hxw028 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1811 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e13363a737a/lib/whedon/bibtex_parser.rb:74:in `doi_citation': undefined method `encode' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e13363a737a/lib/whedon/bibtex_parser.rb:61:in `make_citation'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e13363a737a/lib/whedon/bibtex_parser.rb:47:in `block in generate_citations'
	from /app/vendor/bundle/ruby/2.4.0/gems/bibtex-ruby-5.0.0/lib/bibtex/bibliography.rb:149:in `each'
	from /app/vendor/bundle/ruby/2.4.0/gems/bibtex-ruby-5.0.0/lib/bibtex/bibliography.rb:149:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e13363a737a/lib/whedon/bibtex_parser.rb:41:in `generate_citations'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e13363a737a/lib/whedon/compilers.rb:245:in `crossref_from_markdown'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e13363a737a/lib/whedon/compilers.rb:21:in `generate_crossref'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e13363a737a/lib/whedon/processor.rb:95:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e13363a737a/bin/whedon:79:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e13363a737a/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kthyng** [comment]
hmm, almost done but need to see what the problem is here. @arfon can you help here?

**Comment by arfon** [comment]
@kthyng - there are a couple of DOIs that are non-standard in format. There look to be alternative (standard-form) DOIs for the same records and I've updated them in https://github.com/complexvariables/ComplexRegions.jl/pull/7

**Comment by kthyng** [comment]
@tobydriscoll Can you merge the PR from @arfon?

@arfon why are those errors only picked up when trying to accept instead of when generating the pdf?

**Comment by arfon** [comment]
> @arfon why are those errors only picked up when trying to accept instead of when generating the pdf?

They're been generated when we create the Crossref metadata (which we don't do until towards the end of the process).

**Comment by kthyng** [comment]
@arfon got it, makes sense. I know better what to look for when this happens in the future.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01811/joss.01811/10.21105.joss.01811.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@kthyng did you want to finish processing this one?

**Comment by Kevin-Mattheus-Moerman** [comment]
I checked the archive on Zenodo and the paper and all looks good.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1811 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/bibtex_parser.rb:74:in `doi_citation': undefined method `encode' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/bibtex_parser.rb:61:in `make_citation'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/bibtex_parser.rb:47:in `block in generate_citations'
	from /app/vendor/bundle/ruby/2.4.0/gems/bibtex-ruby-5.0.1/lib/bibtex/bibliography.rb:149:in `each'
	from /app/vendor/bundle/ruby/2.4.0/gems/bibtex-ruby-5.0.1/lib/bibtex/bibliography.rb:149:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/bibtex_parser.rb:41:in `generate_citations'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/compilers.rb:245:in `crossref_from_markdown'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/compilers.rb:21:in `generate_crossref'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/processor.rb:95:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/bin/whedon:79:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10/dnvcn7 is OK
- 10.2514/3.9819 is OK
- 10.1006/jcph.1993.1175 is OK
- 10.1016/0022-247X(79)90086-6 is OK
- 10/gf9fzf is OK
- 10.1137/0911035 is OK
- 10.1007/bf01418327 is OK
- 10.1016/0377-0427(86)90133-0 is OK
- 10.1109/22.156612 is OK
- 10.1137/0910031 is OK
- 10.1016/0377-0427(86)90141-x is OK
- 10.1063/1.331373 is OK
- 10.1109/tmi.2004.831226 is OK
- 10.1137/060659119 is OK
- 10.1093/imamat/hxw028 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@tobydriscoll it looks like you still need to merge this PR https://github.com/complexvariables/ComplexRegions.jl/pull/7. Let me know when you are ready to proceed.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1137/0908003 is OK
- 10.2514/3.9819 is OK
- 10.1006/jcph.1993.1175 is OK
- 10.1016/0022-247X(79)90086-6 is OK
- 10.1137/19M125947X is OK
- 10.1137/0911035 is OK
- 10.1007/bf01418327 is OK
- 10.1016/0377-0427(86)90133-0 is OK
- 10.1109/22.156612 is OK
- 10.1137/0910031 is OK
- 10.1016/0377-0427(86)90141-x is OK
- 10.1063/1.331373 is OK
- 10.1109/tmi.2004.831226 is OK
- 10.1137/060659119 is OK
- 10.1093/imamat/hxw028 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1140

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1140, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1201509158400471047) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1143
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01811](https://doi.org/10.21105/joss.01811)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01811/status.svg)](https://doi.org/10.21105/joss.01811)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01811">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01811/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01811/status.svg
   :target: https://doi.org/10.21105/joss.01811
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01811/status.svg)](https://doi.org/10.21105/joss.01811)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
