### ISSUE TITLE
[PRE REVIEW]: GAIM: A C++ library for Genetic Algorithms and Island Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1813]
**Submitting author:** @gdetor (<a href="http://orcid.org/0000-0001-5891-1702">Georgios Detorakis</a>)
**Repository:** <a href="https://gitlab.com/gdetor/genetic_alg" target ="_blank">https://gitlab.com/gdetor/genetic_alg</a>
**Version:** v1.0.0
**Editor:** @majensen
**Reviewers:** @sjvrijn, @sarats

**Author instructions**

Thanks for submitting your paper to JOSS @gdetor. The JOSS editor @mgymrek, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@gdetor if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mgymrek it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@mgymrek) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01813/joss.01813/10.21105.joss.01813.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@mgymrek can you  take this one? Alternatively, @brainstorm @majensen @csoneson can one of you take this one? Thanks

**Comment by mgymrek** [comment]
this is not really in my arena.  @brainstorm @majensen @csoneson @lpantano would either of you be able to take this one?

**Comment by csoneson** [comment]
This is also pretty far from my expertise I'm afraid.

**Comment by lpantano** [comment]
I know very little. I will give another day to see if actually any of the others know more, if not, i can take it and ask for help to the authors to find reviewers.

**Comment by majensen** [comment]
I'm comfortable taking this one

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @majensen as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by majensen** [comment]
@gdetor thanks for your submission. Would you be willing to have a look at this list https://bit.ly/joss-reviewers and see if you have any reviewers you may want to recommend? The topic is quite interesting and maybe a little outside the main work of some of us, as you can see.

**Comment by gdetor** [comment]
@majensen Two potential reviewers can be @sjvrijn and @sarats 
Thank you

**Comment by majensen** [comment]
Thanks @gdetor  - @sjvrijn @sarats , would either or both of you be willing to review this submission? (I will also ping via email/LinkedIn)

**Comment by sjvrijn** [comment]
@majensen I can review this submission

**Comment by majensen** [comment]
Thanks @sjvrijn

**Comment by sarats** [comment]
@majensen I'm happy to review this.

**Comment by majensen** [comment]
@sarats thanks so much. I will start the review; look for the link that will appear below.

**Comment by majensen** [comment]
@whedon assign @sjvrijn as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sjvrijn

**Comment by majensen** [comment]
@whedon add @sarats as reviewer

**Comment by whedon** [comment]
OK, @sarats is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1839. Feel free to close this issue now!

**Comment by majensen** [comment]
Thanks to all- the review will take place in issue #1839 
cheers
