### ISSUE TITLE
[PRE REVIEW]: MOAFS: A Massive Online Analysis library for featureselection in data streams

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1814]
**Submitting author:** @mbdemoraes (<a href="http://orcid.org/0000-0002-9485-0334">Matheus Bernardelli de Moraes</a>)
**Repository:** <a href="https://github.com/mbdemoraes/moafs" target ="_blank">https://github.com/mbdemoraes/moafs</a>
**Version:** v1.0.0
**Editor:** @VivianePons
**Reviewers:** @sptennak

**Author instructions**

Thanks for submitting your paper to JOSS @mbdemoraes. The JOSS editor @melissawm, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mbdemoraes if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @melissawm it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@melissawm) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01814/joss.01814/10.21105.joss.01814.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@melissawm @VivianePons @drvinceknight could one of you be editor for this one? (I've assigned Melissa as editor for now)

**Comment by VivianePons** [comment]
I can take this one

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon remove @melissawm as editor

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by VivianePons** [comment]
@mbdemoraes there seems to be a broken ref at the end of the paper, could you fix it? Thanks

**Comment by mbdemoraes** [comment]
Viviane,

Reference fixed! Thanks for the warning.

Att,

Matheus

Em sex, 18 de out de 2019 às 05:59, Viviane Pons <notifications@github.com>
escreveu:

**Comment by danielskatz** [comment]
👋 @VivianePons - What's the status of this submission?

**Comment by VivianePons** [comment]
@whedon assign @sptennak as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sptennak

**Comment by VivianePons** [comment]
I am still looking for a second reviewer, @mbdemoraes any suggestion?

**Comment by mbdemoraes** [comment]
Sure! From the joss reviewers list, I suggest:

   - jmadera
   - soroushj
   - xirdneh
   - dvysardana
   - nkratzke


Em seg., 4 de nov. de 2019 às 05:45, Viviane Pons <notifications@github.com>
escreveu:

**Comment by VivianePons** [comment]
Update: I am still looking for a second reviewer,

**Comment by mbdemoraes** [comment]
@VivianePons , given the trouble to find a suitable reviewer for this paper, I would like to check a possibility. There is someone, Andrés Bueno Barajas, who has a master's degree in Technology, focused on data streams and concept drift. He is experienced with the Massive Online Analysis framework. I have not suggested Andrés before because I've read JOSS Conflict of Interest and Andres has one published paper with André Gradvohl, a co-author of this paper. I would like to ask Andrés if he can give an impartial assessment of our work, but before I talk to him, I would like to know your opinion about it.

**Comment by VivianePons** [comment]
That sounds like a good idea. I am ok with it if the reviewer himself feels he can do it. The JOSS policy does not forbid that, it only states that the conflict should be acknowledged so that the editor can decide. In this case, I think it is find especially as we also have a second reviewer.

**Comment by danielskatz** [comment]
As a JOSS Associate-Editor-in-Chief, I think this depends on the details of the co-authored paper. For example: When was it published, and when was the work done? How many authors were there? Did they work closely together? Do they still work together?

**Comment by mbdemoraes** [comment]
@danielskatz, the paper was published at the beginning of this year (2019) on a Brazilian journal, "Revista Brasileira de Computação Aplicada", but it refers to a work completed at the end of 2017. Andrés is a former student of University Campinas (not related to André Gradvohl), who helped a former André Gradvohl's thesis student, Luis F. Grim (the main author of the referred paper), in the practical approach of experiments, such as working with MATLAB, parallel libraries, and GPU. On the other hand, André Gradvohl, as an advisor of Luis F. Grim, helped him with theoretical aspects such as defining and validating the experiments, paper structuring, organization, and writing. Therefore, as far as I'm concerned, there was no direct collaboration between André Gradvohl and Andrés Barajas. And if they still work together, the answer is no, since André is a professor at the School of Technology at the University of Campinas and Andrés has concluded his master's degree in 2018 and is not at the university anymore.

**Comment by danielskatz** [comment]
@mbdemoraes - thanks - this indeed seems like a conflict that could be waived

**Comment by gradvohl** [comment]
@danielskatz - Thank you for understanding. If you need more information, I am available to clarify and make the process as transparent as possible.

**Comment by VivianePons** [comment]
@gradvohl Where are we on this, did you ask this potential reviewer?

**Comment by gradvohl** [comment]
Hello @VivianePons! Yes, we're trying to reach him by e-mail, but we haven't yet. We'll try one last time.

**Comment by mbdemoraes** [comment]
Guys, we talked to Andrés and unfortunately he isn't available to review.
Other professionals we know have a strong conflict of interest and are not
suitable for this process. So we'll need your assistance with this task.

Em qua., 27 de nov. de 2019 às 12:23, André Leon S. Gradvohl <
notifications@github.com> escreveu:

**Comment by VivianePons** [comment]
No problem, I'll keep looking. My problem so far is that most people just NEVER answered me. This is what is causing the delay, I don't get negative answers, I get no answer at all...

**Comment by VivianePons** [comment]
Hey :wave: @xirdneh would you be willing to review this submission?. I tried to send you an email but it seems like your address at u texas does dot work...

**Comment by gradvohl** [comment]
Hello @VivianePons. Do you have any news about the reviewers for the paper?

**Comment by VivianePons** [comment]
I still have only one reviewer: most people I asked never answered and the one who did said no. I am going to start the review with the reviewer we have. If we find another one, that's better but we will have to work with only one!

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1970. Feel free to close this issue now!

**Comment by gradvohl** [comment]
Thank you very much, @VivianePons .
