### ISSUE TITLE
[REVIEW]: OnlineStats.jl: A Julia package for statistics on data streams

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1816]
**Submitting author:** @joshday (<a href="http://orcid.org/0000-0002-7490-6986">Josh Day</a>)
**Repository:** <a href="https://github.com/joshday/OnlineStats.jl" target ="_blank">https://github.com/joshday/OnlineStats.jl</a>
**Version:** v1.0.3
**Editor:** @karthik
**Reviewers:** @pkofod, @ahwillia
**Archive:** <a href="https://doi.org/10.5281/zenodo.3659245" target="_blank">10.5281/zenodo.3659245</a>

## Status

[![status](https://joss.theoj.org/papers/306085f555d2f0015aa1a131e41c491c/status.svg)](https://joss.theoj.org/papers/306085f555d2f0015aa1a131e41c491c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/306085f555d2f0015aa1a131e41c491c"><img src="https://joss.theoj.org/papers/306085f555d2f0015aa1a131e41c491c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/306085f555d2f0015aa1a131e41c491c/status.svg)](https://joss.theoj.org/papers/306085f555d2f0015aa1a131e41c491c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/joshday/OnlineStats.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@pkofod & @ahwillia, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @karthik know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/joshday/OnlineStats.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@joshday) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/joshday/OnlineStats.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@joshday) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @vchuravy, @ahwillia it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by karthik** [comment]
Editor note: @ahwillia will start review in November.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01816/joss.01816/10.21105.joss.01816.pdf)

**Comment by ahwillia** [comment]
This looks good to me -- I went ahead and checked all my boxes. The documentation is really nice, and the functionality of the package is clear.

My only feedback is that it would be nice to show more full-fledged examples or tutorials, since the operations performed by this particular package are nice building blocks for more complex models/applications. Are there any examples of other repos using `OnlineStats.jl` to do impressive things? Can these be mentioned in the documentation or the README?

Other than this suggestion, I am happy to see this accepted and published as is.

**Comment by ahwillia** [comment]
Also one area the documentation could use more work is the `StatLearn` object (e.g. for online fitting of GLMs). An example showing how to take multiple passes over the same dataset (i.e. multiple epochs) could be useful.

**Comment by karthik** [comment]
@vchuravy Quick ping to check in. Can you give us a sense for when you might complete this review? :pray:

**Comment by karthik** [comment]
@vchuravy Another ping to check in. Can you give us a sense for when you might complete this review?

**Comment by karthik** [comment]
@vchuravy Pinging one more time.  Are you still able to complete the review?

**Comment by karthik** [comment]
@joshday  Apologies for the delays with this submission. I'm still trying to get a response from reviewer 2. I'll look for a reviewer in the new year. I'll be out of office for the next few weeks.

**Comment by karthik** [comment]
/ooo December 22 2019 until January 10 2020

**Comment by karthik** [comment]
@joshday I am still looking for reviewers without much success. Are you able to recommend anyone that can review without any conflict of interest?

**Comment by pkofod** [comment]
@karthik I can review but I do have to disclose that we are both employed by Julia Computing. Though, we do live 7000km from each other, and have never worked on projects together. I have never used OnlineStats.jl either, although I'm aware of it's existence.

**Comment by karthik** [comment]
@pkofod  That's totally fine! In fact I've tried to get a few people from Julia Computing to review. Thanks so much for stepping in, assigning you now.

**Comment by karthik** [comment]
@@whedon assign @pkofod as reviewer

**Comment by karthik** [comment]
@whedon remove @vchuravy as reviewer

**Comment by whedon** [comment]
OK, @vchuravy is no longer a reviewer

**Comment by karthik** [comment]
@whedon assign @pkofod as reviewer

**Comment by whedon** [comment]
OK, @pkofod is now a reviewer

**Comment by karthik** [comment]
@pkofod I have updated the checklist above with your name. Please work through that list. Reviewer guidelines are here: http://joss.theoj.org/about#reviewer_guidelines

**Comment by pkofod** [comment]
I have looked at the repo for the first part and everything looks fine. It's structured like a typical Julia package, and has docs, CI, a proper readme with examples and a clear indication that contributions are welcome but Josh has strong preference for the design choices. I will try to find time to read the actual paper tomorrow or the day after.

**Comment by pkofod** [comment]
Everything looks pretty good. There is one thing missing IMO, but it might be a matter of focus and/or intent. Either OnlineStats.jl is mainly seen as a platform for developing online algorithms, and in that case the example is fine: it shows how to implement an algorithm using the structure provided by the package. However, if the goal (as I understood it at least) is mainly to provide implementations, then I think a simple example of using the *existing* package functionality would be nice. This could/would also show the Plots.jl integration. Just something like the following from the docs would suffice:
```
o = Partition(Mean())
o2 = Partition(Extrema())

s = Series(o, o2)

fit!(s, y)

plot(s, layout = 1, xlab = "Nobs")
```
Other than that, lgtm

**Comment by karthik** [comment]
Thanks @pkofod 
@joshday: Can you respond to the comment above:

> Either OnlineStats.jl is mainly seen as a platform for developing online algorithms, and in that case the example is fine: it shows how to implement an algorithm using the structure provided by the package. However, if the goal (as I understood it at least) is mainly to provide implementations, then I think a simple example of using the existing package functionality would be nice.

**Comment by karthik** [comment]
@whedon check references

**Comment by karthik** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1137/141000671 may be missing for title: Julia: A fresh approach to numerical computing
- https://doi.org/10.1198/0003130042836 may be missing for title: A Tutorial on MM Algorithms

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01816/joss.01816/10.21105.joss.01816.pdf)

**Comment by joshday** [comment]
In response @ahwillia suggestion, I have added a section to the README about packages that use OnlineStats.

In response to @pkofod:

> Either OnlineStats.jl is mainly seen as a platform for developing online algorithms, and in that case the example is fine: it shows how to implement an algorithm using the structure provided by the package. However, if the goal (as I understood it at least) is mainly to provide implementations, then I think a simple example of using the existing package functionality would be nice.

The paper is meant for a more technical audience (the "developing online algorithms" crowd) whereas the documentation is meant for general users.  I'm happy to add a higher level example, but I think most people will check the documentation first.

**Comment by pkofod** [comment]
That makes sense. I'm fine with the current state, just wanted to be sure what the intention was. So looks good to me.

**Comment by karthik** [comment]
@joshday Can you please check the references and make sure it is parsing correctly?

**Comment by joshday** [comment]
@karthik I've fixed the reference issues!

**Comment by karthik** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/141000671 is OK

MISSING DOIs

- https://doi.org/10.1007/978-1-4842-3579-9_6 may be missing for title: Spark Streaming

INVALID DOIs

- https://doi.org/10.1137/141000671 is INVALID because of 'https://doi.org/' prefix
```

**Comment by joshday** [comment]
I've fixed the invalid DOI.  

The "missing" DOI I believe is in error, as I'm citing the actual software.  The above DOI is for a book chapter in "Beginning Apache Spark 2", which is not what I'm citing.

**Comment by karthik** [comment]
If the software doesn't have a DOI, I think we can skip it but I'll tag @arfon in case he can help.

**Comment by arfon** [comment]
> If the software doesn't have a DOI, I think we can skip it but I'll tag @arfon in case he can help.

This sounds fine. The DOI search/recommender is just using the Crossref API looking for similar titles.

**Comment by karthik** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01816/joss.01816/10.21105.joss.01816.pdf)

**Comment by karthik** [comment]
LGTM

**Comment by karthik** [comment]
Ready to accept. Over you to @openjournals/joss-eics

**Comment by kthyng** [comment]
@joshday Hi! I'll take over from here. 

What version number do you want associated with this publication?

Also, can you create an archive of your code at, for example, Zenodo, and report the doi back here? Please be sure that the title and author list match your paper exactly, which might requires editing the metadata.

**Comment by karthik** [comment]
@kthyng Yikes, sorry I forget about Zenodo and versions. doh.

**Comment by joshday** [comment]
@kthyng The version I'd like to use is is v1.0.3 and the DOI is `10.5281/zenodo.3659245`.  Let me know if there's anything else I can do to help!  

A big thank you to @ahwillia and @pkofod for reviewing and @karthik for keeping this thing moving along!

**Comment by kthyng** [comment]
@whedon set v1.0.3 as version

**Comment by whedon** [comment]
OK. v1.0.3 is the version.

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.3659245 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3659245" target="_blank">10.5281/zenodo.3659245</a> is the archive.

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/141000671 is OK

MISSING DOIs

- https://doi.org/10.1007/978-1-4842-3579-9_6 may be missing for title: Spark Streaming

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1292

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1292, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1226893189933654017) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1293
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01816](https://doi.org/10.21105/joss.01816)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Congratulations on your new publication to @joshday!! Thank to editor @karthik and to reviewers @pkofod and @ahwillia — without your time and expertise we couldn't have done this!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01816/status.svg)](https://doi.org/10.21105/joss.01816)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01816">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01816/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01816/status.svg
   :target: https://doi.org/10.21105/joss.01816
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01816/status.svg)](https://doi.org/10.21105/joss.01816)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by joshday** [comment]
My apologies for missing this in the proof, but a unicode character (μ) fails to render in the example at the end of the paper.  Is it possible to revise the paper?  I can simply change the problem character to ASCII.

**Comment by danielskatz** [comment]
Please make the change in the .md or .bib file, than let us know - @arfon will have to manually propagate the change it at this point

**Comment by joshday** [comment]
Thanks @danielskatz, I've made the change.

**Comment by danielskatz** [comment]
👋 @arfon - over to you...

**Comment by arfon** [comment]
> 👋 @arfon - over to you...

OK this should be updated now. The PDF might take a few hours to show up as modified as there's caching in place for the papers.

**Comment by joshday** [comment]
Much appreciated!  Thank you!

**Comment by kthyng** [comment]
@editorialbot reaccept

**Comment by kthyng** [comment]
Oh editorialbot maybe doesn't even work because this is so old!

@openjournals/dev I think we need a manual intervention for this one?
