### ISSUE TITLE
[PRE REVIEW]: pyscal : A python module for structural analysis of atomic environments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1817]
**Submitting author:** @srmnitc (<a href="http://orcid.org/0000-0002-6776-1213">Sarath Menon</a>)
**Repository:** <a href="https://github.com/srmnitc/pyscal" target ="_blank">https://github.com/srmnitc/pyscal</a>
**Version:** 2.0.0
**Editor:** @melissawm
**Reviewers:** @lucydot, @bocklund

**Author instructions**

Thanks for submitting your paper to JOSS @srmnitc. **Currently, there isn't an JOSS editor assigned** to your paper.

@srmnitc if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by Kevin-Mattheus-Moerman** [comment]
@melissawm @VivianePons @meg-simula @xuanxu is one of you able to handle this submission? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@will-rowe this looks like its your cup of :tea:, would you like to edit this one?

**Comment by melissawm** [comment]
I can edit it, just let me know in case @will-rowe prefers to do it.

**Comment by will-rowe** [comment]
Thanks @melissawm - as this is outside my area of expertise and also my first editing offer, I would prefer if you could this time.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @melissawm as editor

**Comment by whedon** [comment]
OK, the editor is @melissawm

**Comment by srmnitc** [comment]
@melissawm thanks for agreeing to be the editor! Would you like me to recommend some reviewers?

**Comment by melissawm** [comment]
Yes @srmnitc, that would be very helpful. Thanks!

**Comment by srmnitc** [comment]
@melissawm  by going through their github profiles and contribution, I think all of them might be a good fit - bjmorgan, bocklund, mkhorton, lucydot, utf, kjappelbaum and lucydot.

**Comment by melissawm** [comment]
Thanks @srmnitc! 

@bjmorgan, @lucydot would you be available and interested in reviewing this submission?

**Comment by lucydot** [comment]
Hi @melissawm and @srmnitc - I’d be happy to review

**Comment by srmnitc** [comment]
thanks @melissawm  and @lucydot.

**Comment by melissawm** [comment]
@whedon assign @lucydot as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @lucydot

**Comment by melissawm** [comment]
@bocklund would you be willing to review this paper for JOSS? Thanks!

**Comment by bocklund** [comment]
Sure, I can review this!

**Comment by melissawm** [comment]
@whedon add @bocklund as reviewer

**Comment by whedon** [comment]
OK, @bocklund is now a reviewer

**Comment by melissawm** [comment]
Great, thanks! I'll move this to a review issue then.

**Comment by melissawm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1824. Feel free to close this issue now!
