### ISSUE TITLE
[REVIEW]: Telewavesim: Python software for teleseismic body wave modeling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1818]
**Submitting author:** @paudetseis (<a href="http://orcid.org/0000-0003-2364-9454">Pascal Audet</a>)
**Repository:** <a href="https://github.com/paudetseis/Telewavesim" target ="_blank">https://github.com/paudetseis/Telewavesim</a>
**Version:** v0.2.0
**Editor:** @kbarnhart
**Reviewer:** @andreww, @seisman, @brmather
**Archive:** <a href="https://doi.org/10.5281/zenodo.3551258" target="_blank">10.5281/zenodo.3551258</a>

## Status

[![status](https://joss.theoj.org/papers/dd49a1b3a0b51840e30996d5a3ffdb43/status.svg)](https://joss.theoj.org/papers/dd49a1b3a0b51840e30996d5a3ffdb43)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/dd49a1b3a0b51840e30996d5a3ffdb43"><img src="https://joss.theoj.org/papers/dd49a1b3a0b51840e30996d5a3ffdb43/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/dd49a1b3a0b51840e30996d5a3ffdb43/status.svg)](https://joss.theoj.org/papers/dd49a1b3a0b51840e30996d5a3ffdb43)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/paudetseis/Telewavesim" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@andreww & @seisman & @brmather, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kbarnhart know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/paudetseis/Telewavesim">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@paudetseis) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/paudetseis/Telewavesim">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@paudetseis) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/paudetseis/Telewavesim">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@paudetseis) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @andreww, @seisman, @brmather it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01818/joss.01818/10.21105.joss.01818.pdf)

**Comment by kbarnhart** [comment]
@whedon remind @andreww in one week
@whedon remind  @seisman in one week
@whedon remind @brmather in one week

**Comment by whedon** [comment]
Reminder set for @andreww in one week

**Comment by kbarnhart** [comment]
@whedon remind  @seisman in one week

**Comment by whedon** [comment]
Reminder set for  @seisman in one week

**Comment by kbarnhart** [comment]
@whedon remind @brmather in one week

**Comment by whedon** [comment]
Reminder set for @brmather in one week

**Comment by danielskatz** [comment]
@kbarnhart - FYI, @whedon only takes one command at a time, and it has to be the first content in the comment

**Comment by kbarnhart** [comment]
@danielskatz thanks for the the @whedon info! 👍 I've edited the comment to split up the reminders.

**Comment by paudetseis** [comment]
Question to @kbarnhart and reviewers: I see new issues on the GH repo from @seisman and making corrections as they come. Should I push them now or wait for potentially more comments from reviewers?

**Comment by kbarnhart** [comment]
@paudetseis - it’s up to you if you want to wait for all the reviews, or start addressing the issues as they arrive. 

It’s definitely good to do as @seisman has done and make sure to to link the reviews in the repository. That way the substantive review comments can be in the in-repository issues, but this issue can have a record of the the status.

**Comment by andreww** [comment]
Ok - my review is done. Comments are all added as issues in the telewavesim repository and reference this issue. As I see things, the blockers would be paudetseis/Telewavesim#21 (functionality) and paudetseis/Telewavesim#18 (community guidelines).

**Comment by paudetseis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01818/joss.01818/10.21105.joss.01818.pdf)

**Comment by paudetseis** [comment]
Thanks to @seisman and @andreww for their comments. Most of them have been addressed in new commits and comments in the corresponding issues. Issues #19 and #21 have been left open if there are other useful and specific suggestions for the documentation.

**Comment by seisman** [comment]
I've finished my review and the authors has addressed my issues. The submission now looks good to me.

**Comment by whedon** [comment]
:wave: @andreww, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @brmather, please update us on how your review is going.

**Comment by kbarnhart** [comment]
Thanks @andreww and @seisman for completing your reviews. 

@andreww it looks like there are a couple of check-boxes remaining unchecked. Please post here if anything remains for @paudetseis to do for you to check them. 

@brmather, please let me know if you have any questions as you undertake your review.

**Comment by brmather** [comment]
Thanks @kbarnhart - I've had a lot of deadlines in the last couple of weeks, but I'll submit my review soon. Hope that's OK. Cheers!

**Comment by andreww** [comment]
Yes - I'm happy that the changes address my concerns. I've added comments to one closed issue (https://github.com/paudetseis/Telewavesim/issues/15) but I don't think this needs to be addressed to allow publication here.

**Comment by kbarnhart** [comment]
@brmather Thanks for the update. I appreciate your being willing to do a review 👍 🎉 .

**Comment by kbarnhart** [comment]
I wanted to check in regarding this review.

**Comment by brmather** [comment]
Hi all, I have progressed through the checklist and I find all the checklist items have been met. Aside from some installation issues, that have been rectified, I did not have any additional issues to raise because they were addressed by other reviewers. The API documentation is particularly rich :clap: As it stands, I consider `Telewavesim` to be a valuable tool for the community and ready for publication.

Thanks for the opportunity to provide a review and congrats to the authors :+1:

**Comment by paudetseis** [comment]
Thanks @brmather !

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kbarnhart** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1093/gji/ggw111 is OK
- 10.1785/0120110162 is OK
- 10.1002/2017TC004625 is OK
- 10.1111/j.1365-246X.1984.tb05056.x is OK
- 10.1046/j.1365-246x.2000.00090.x is OK
- 10.1088/1749-4699/8/1/014003 is OK
- 10.1130/L126.1 is OK
- 10.1016/S0031-9201(97)00033-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01818/joss.01818/10.21105.joss.01818.pdf)

**Comment by kbarnhart** [comment]
@seisman @brmather @andreww thank you all for your reviews. As part of the JOSS review process, can you please confirm your recommendation to accept the submission.

**Comment by seisman** [comment]
@kbarnhart I recommend to accept this submission.

**Comment by brmather** [comment]
@kbarnhart I recommend to accept this submission.

**Comment by andreww** [comment]
Noting that I've not looked at any changes that may have been made in the last 27 days, my recommendation is that this manuscript should be accepted by JOSS.

**Comment by kbarnhart** [comment]
Thank you @seisman @brmather @andreww 

@paudetseis at this point could you:
- [ ] Edit the paper to clarify affiliation 3. It looks like two affiliations.
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a  similar service. 
- [ ] Verify that the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] Please list the Zenodo DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by paudetseis** [comment]
@kbarnhart @seisman @brmather @andreww 

Thank you all very much for taking time to review and improve Telewavesim! This was a great learning experience for me and I appreciate the valuable comments and suggestions.

I have completed the tasks listed above. 

- I edited the paper and fixed affiliation 3
- The version tag of the archived version is 0.2.0
- The package on PyPi was also updated to 0.2.0
- I edited the software details on Zenodo.
- The Zenodo deposit does have the correct metadata (title + author list).
- The Zenodo DOI is 10.5281/zenodo.3551250 (also shown as badge on the README page in the telewavesim repo). 

I haven't recompiled the PDF and will leave that to @kbarnhart once these details are verified and confirmed.

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01818/joss.01818/10.21105.joss.01818.pdf)

**Comment by kbarnhart** [comment]
@whedon set v0.2.0 as version

**Comment by whedon** [comment]
OK. v0.2.0 is the version.

**Comment by kbarnhart** [comment]
@paudetseis I found that the DOI you mentioned here is not resolved (https://doi.org/10.5281/zenodo.203551250). 

Following the link on the readme I find: http://doi.org/10.5281/zenodo.3551258

Can you confirm the DOI?

**Comment by paudetseis** [comment]
@kbarnhart I am confused about the DOI that you cite (https://doi.org/10.5281/zenodo.203551250), as I have not mentioned that DOI previously nor can I find any reference to it on this page, in the repo, README or API. The one mentioned above is the correct one (10.5281/zenodo.3551250),which is the same that appears on the README. 

Perhaps I misunderstood your final check box about the zenodo DOI: "Please list the Zenodo DOI of the archived version here." Can you please clarify where you found reference to the unresolved DOI for Telewavesim and how I can fix this?

**Comment by kbarnhart** [comment]
@paudetseis My apologies. I had meant to type https://doi.org/10.5281/zenodo.3551250
instead of https://doi.org/10.5281/zenodo.203551250. I mistyped and added a "20". 

However, I do not find the DO https://doi.org/10.5281/zenodo.3551250 as resolved. 

When I try to go to it I get the following screen. 

<img width="200" alt="Screen Shot 2019-11-24 at 9 02 21 PM" src="https://user-images.githubusercontent.com/6589339/69491735-eafa2c00-0efd-11ea-9127-d19e5a76b5aa.png">

I then went to the Telewavesim repository and the badge there lists:
10.5281/zenodo.3551258

<img width="600" alt="Screen Shot 2019-11-24 at 8 58 00 PM" src="https://user-images.githubusercontent.com/6589339/69491739-f0577680-0efd-11ea-9faf-6125e7d16500.png">

So I wanted to verify the correct DOI. I suspect it should be 10.5281/zenodo.3551258

(FYI - I'll be away from internet for 4 days starting mid-day Monday Nov 25th in GMT+12)

**Comment by paudetseis** [comment]
@kbarnhart My apologies too - the DOI that I typed here previously (https://doi.org/10.5281/zenodo.3551250) had a typo in the last digit. It should be https://doi.org/10.5281/zenodo.3551258. Sorry for the confusion.

**Comment by kbarnhart** [comment]
@whedon set 10.5281/zenodo.3551258 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3551258" target="_blank">10.5281/zenodo.3551258</a> is the archive.

**Comment by kbarnhart** [comment]
@openjournals/joss-eics this is ready for final processing.

**Comment by Kevin-Mattheus-Moerman** [comment]
@paudetseis can you please work on the following: 

- [ ] Can you amend the meta data for the archive on Zenodo such that the title and authors match the JOSS paper? 
- [ ] The paper contains two instances of `allows`, I suggest using `allows the` instead. 
- [ ] The acronym OBS is defined in the text but never used. Perhaps you can omit the use of the acronym altogether. 
- [ ] In the following: `...from core-refracted teleseismic shear waves (i.e., SKS, SKKS), etc.`, please consider removing `, etc.`, at the end of the sentence. Since the sentence contains `such as`, it is already clear that what follows is a subset of non-exhaustive examples.

**Comment by paudetseis** [comment]
@Kevin-Mattheus-Moerman Thank you for the suggestions.

- I edited the title and authors on Zenodo to match the JOSS paper.
- The two instances of `allows` are not followed by `the`  but rather by a noun and a gerund, respectively, which I believe is correct grammar.
- I removed the acronym OBS.
- I amended the sentence and removed `, etc.` at the end of the sentence.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01818/joss.01818/10.21105.joss.01818.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1093/gji/ggw111 is OK
- 10.1785/0120110162 is OK
- 10.1002/2017TC004625 is OK
- 10.1111/j.1365-246X.1984.tb05056.x is OK
- 10.1046/j.1365-246x.2000.00090.x is OK
- 10.1088/1749-4699/8/1/014003 is OK
- 10.1130/L126.1 is OK
- 10.1016/S0031-9201(97)00033-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1138

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1138, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1201475049473167360) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1139
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01818](https://doi.org/10.21105/joss.01818)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01818/status.svg)](https://doi.org/10.21105/joss.01818)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01818">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01818/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01818/status.svg
   :target: https://doi.org/10.21105/joss.01818
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01818/status.svg)](https://doi.org/10.21105/joss.01818)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
