### ISSUE TITLE
[PRE REVIEW]: Special relativity in R: the lorentz package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1819]
**Submitting author:** @RobinHankin (<a href="http://orcid.org/0000-0001-5982-0415">Robin Hankin</a>)
**Repository:** <a href="https://github.com/RobinHankin/lorentz" target ="_blank">https://github.com/RobinHankin/lorentz</a>
**Version:** 1.0-3
**Editor:** @arfon
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @RobinHankin. **Currently, there isn't an JOSS editor assigned** to your paper.

@RobinHankin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01819/joss.01819/10.21105.joss.01819.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@xuanxu @mbobra @meg-simula can one edit this one?

**Comment by xuanxu** [comment]
Relativity + R is a mix out of my area of expertise, I’ll have to pass on this one

**Comment by arfon** [comment]
I suspect this paper is going to be tough for any of our editors to be honest. I'll take it.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@RobinHankin - thanks for your submission to JOSS.

I've had a quick read of the paper associated with this submission and I think it could do with a little work. In particular [we ask](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) that your paper contains:

> - A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.
> - A clear Statement of Need that illustrates the research purpose of the software.

While there is some useful background here, it's not immediately clear what current research applications this software has.

In addition, can you clarify that this package is being used actively in research and has not simply been written as a learning exercise? In such situations, we have the [Journal of Open Source Education](http://jose.theoj.org) for these types of papers.

**Comment by RobinHankin** [comment]
thanks for this Arfon

I'll rewrite the submission as you suggest.  The research purpose of the
package is, as stated, to search for a generalization of the classical
distributive law; and this is ongoing work.  But, even though I've searched
a very large space for a possible distributive law, I didn't find one.
Does this matter?

<hankin.robin@gmail.com>
hankin.robin@gmail.com

<hankin.robin@gmail.com>

<hankin.robin@gmail.com>

**Comment by RobinHankin** [comment]
Arfon, can I press you for some advice on my submission please?

**Comment by arfon** [comment]
> I'll rewrite the submission as you suggest.  The research purpose of the
> package is, as stated, to search for a generalization of the classical
> distributive law; and this is ongoing work.  But, even though I've searched
> a very large space for a possible distributive law, I didn't find one.

Sorry, please do go ahead and redraft. I'm afraid I still don't quite understand what the research goal of this work is but I'm hoping that your reworked paper will help explain this to me (and potential readers).

**Comment by RobinHankin** [comment]
thank you Arfon, I appreciate your advice.  I will rework the submission as
you suggest.  I was not aware of JOSE; I checked it out but feel that the
lorentz work is more appropriate for JOSS.

With best wishes

Robin

<hankin.robin@gmail.com>
hankin.robin@gmail.com

<hankin.robin@gmail.com>

<hankin.robin@gmail.com>

**Comment by RobinHankin** [comment]
Arfon, I've redrafted `paper.md` in the repo, and I was just about to click the 'withdraw paper' button at

https://joss.theoj.org/papers/1d90c3a705d7106477e7071c350f8025

but I hesitated because it is not a withdrawal, it is more of a redraft (although I have done a little bit of work on the software as well).  Can you advise?

**Comment by arfon** [comment]
There's no need to withdraw. We can keep working with this submission here.

**Comment by RobinHankin** [comment]
OK thanks Arfon.  Can I check that there are no actions on me?

**Comment by arfon** [comment]
> OK thanks Arfon. Can I check that there are no actions on me?

Yep, it's on me to get back to you on this. I'm currently  a little swamped with other submissions.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01819/joss.01819/10.21105.joss.01819.pdf)

**Comment by arfon** [comment]
Hi @RobinHankin - firstly my apologies for taking so long to get to this. I've consulted with the JOSS editorial team and we've concluded that this submission is not in scope for JOSS as it falls into our 'minor utility' category. 

Thanks again for your interest in JOSS.

**Comment by RobinHankin** [comment]
OK Arfon, thanks for this.

I'm not trying to be difficult here, and I'm not querying the decision,
but  can I have some feedback on this please?    The package is an
efficient, coherent and documented numerical environment for working with
the Lorentz transform that has research applications over a wide range of
physical and mathematical applications.  JOSS publishes similar R packages
for physical problems such as FluxCalR . . . How come my work isn't in
scope for JOSS?  It just doesn't seem fair.

Can you advise?


<hankin.robin@gmail.com>
hankin.robin@gmail.com

<hankin.robin@gmail.com>

<hankin.robin@gmail.com>

**Comment by arfon** [comment]
Sure thing. I'll work with the other editors to get you a more formal response in the next couple of days.

**Comment by arfon** [comment]
After consulting with two experts in the field of relativity, this software was deemed minor (i.e. it carries out relatively simply matrix-vector multiplication) and fell short of another [criteria we use for JOSS submissions](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements), related to being a 'significant contribution to the available open source software' in this area:

> The software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler).

The Lorentz transform in special relativity is really just a matrix-vector multiplication with the matrix elements given by a simple formula, eg this one (B(v)): https://en.wikipedia.org/wiki/Lorentz_transform#Proper_transformations Going from three to four velocity and back amounts to solving a quadratic equation.

While this looks like a nicely put together piece of software, we believe that existing tools such as cadabra (https://cadabra.science) or SageManifolds (https://sagemanifolds.obspm.fr) are both well-established, and likely preferable software for addressing these research challenges.

We also have doubts about how popular R is for practitioners in the field (ie physicists) who generally use Python for numerical calculations or Mathematica, Maple, SymPy, or similar for symbolic manipulations (which this code does not appear to offer).
