### ISSUE TITLE
[REVIEW]: Cine: A solar-pumped fluorescence model for cometary atmospheres

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#182]
**Submitting author:** @migueldvb (<a href="http://orcid.org/0000-0002-0455-9384">Miguel de Val-Borro</a>)
**Repository:** <a href="https://github.com/migueldvb/cine" target ="_blank">https://github.com/migueldvb/cine</a>
**Version:** v0.2.1 
**Editor:** @arfon
**Reviewer:** @eteq
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.345982" target="_blank">10.5281/zenodo.345982</a>

## Status

[![status](http://joss.theoj.org/papers/64becd25ed50bbec874fe4b614a3bd29/status.svg)](http://joss.theoj.org/papers/64becd25ed50bbec874fe4b614a3bd29)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/64becd25ed50bbec874fe4b614a3bd29"><img src="http://joss.theoj.org/papers/64becd25ed50bbec874fe4b614a3bd29/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/64becd25ed50bbec874fe4b614a3bd29/status.svg)](http://joss.theoj.org/papers/64becd25ed50bbec874fe4b614a3bd29)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/migueldvb/cine" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/migueldvb/cine">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.2)?
- [x] **Authorship:** Has the submitting author (@migueldvb) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @eteq it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by eteq** [comment]
Process question (maybe for @arfon, maybe for @whedon?) - should there be a PDF of the paper in the author's repo, or just the ``.md`` and ``.bib`` files (which are there already)?

**Comment by arfon** [comment]
> Process question (maybe for @arfon, maybe for @whedon?) - should there be a PDF of the paper in the author's repo, or just the .md and .bib files (which are there already)?

`.md` and `.bib` files are fine. We generally compile these at the end into a PDF.

**Comment by eteq** [comment]
Alright, I've finished my initial review.  I've created migueldvb/cine#1,  migueldvb/cine#2, migueldvb/cine#4, migueldvb/cine#5 with detailed comments that need addressing.

One higher-level question (and the reason for the one un-checked item above) is the lack of API documentation.  I think this *might* be intentional (see migueldvb/cine#5), but if not, that needs to be rectified.


One other procedural question for @arfon: in the process of doing this review I created a PR that @migueldvb merged (it was easier just to do that).  Nominally I suppose that would now make me a co-author given that I have a commit in the repo.  But of course that would look like a weird conflict-of-interest.  Is there a policy for how this should work?  (I'm perfectly fine *not* being an author, as it's a very minor change...  But this is also sort of an academic curiosity.)

**Comment by arfon** [comment]
> One other procedural question for @arfon: in the process of doing this review I created a PR that @migueldvb merged (it was easier just to do that). Nominally I suppose that would now make me a co-author given that I have a commit in the repo. But of course that would look like a weird conflict-of-interest. Is there a policy for how this should work? (I'm perfectly fine not being an author, as it's a very minor change... But this is also sort of an academic curiosity.)

Great question @eteq. I'm in the same situation for many of the submissions as I make small edits to the `paper.md`files. Where I'm at on this:

- I think that minor contributions made during the process of review are OK but should not result in the reviewing becoming an author
- More major contributions which would likely warrant authorship are also OK but in this scenario then I think we'd want to find a second reviewer

Does that sound reasonable?

**Comment by eteq** [comment]
Yep, sounds good @arfon - in that case no issue here as the PR I sent definitely falls in the "minor" category.

**Comment by eteq** [comment]
@migueldvb - just to clarify in case you missed it above: migueldvb/cine#1 and migueldvb/cine#5 are currently awaiting response. Depending on the answer to migueldvb/cine#5, there *may* be additional documentation requirements, but once those issues are addressed, I think this is good to go.

**Comment by migueldvb** [comment]
@eteq thank you for the review.

I have clarified that the code is supposed to be run as a script in the README file. In the future it could be useful to be imported into python when defining the input model using python in the excitation code LIME is available. There is some work done in this direction but it has not yet been merged into LIME and this may take some time...

The missing orcid in the paper is because the co-author does not have an identifier yet although he is interested in getting one. I will leave the issue open as a reminder but perhaps we should not wait for this if all the other requirements are met.

**Comment by eteq** [comment]
Alright, great @migueldvb. 

@arfon, the author has addressed my concerns, so I think I can recommend this paper for acceptance.  There is one question remaining, though: as indicated in migueldvb/cine#1, one of the co-authors doesn't have an orcid yet, but @migueldvb thinks he might get one later.  Is it possible to update the author list after the facts and have whatever metadata is relevant be updated, or is the orcid a now-or-nothing thing?

**Comment by arfon** [comment]
> Is it possible to update the author list after the facts and have whatever metadata is relevant be updated, or is the orcid a now-or-nothing thing?

It's now or never I'm afraid. We only update paper metadata if there's been an error with a submission.

**Comment by migueldvb** [comment]
I was also wondering if the paper could be updated with the orcid
identifier later...

If the paper can be accepted as it is with a missing orcid for one author,
I would go ahead without it and close the issue in the repo.

On Sunday, March 5, 2017, Arfon Smith <notifications@github.com> wrote:
> Is it possible to update the author list after the facts and have
whatever metadata is relevant be updated, or is the orcid a now-or-nothing
thing?
>
> It's now or never I'm afraid. We only update paper metadata if there's
been an error with a submission.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/CwivyAIVv1vWdAPsktNn31pw6cxTEXBSTsoaa24ZtaV3L-H-lqtkU7tBSQni8Nx9qcjWphJ-iSBu-ieSH24UX7rwL_4Wl-Z-soveTTFIIVnXJYQVqTY4AYLJ5Sy4aTdlJWBIM7g2kgz3Ug8xDZrOMtDI-0gT3Q=s0-d-e1-ft#https://github.com/notifications/beacon/AApbZzyK4WRYpvkMIXKHQmu4BnLWyissks5ri1b0gaJpZM4L_x7e.gif>

**Comment by arfon** [comment]
> If the paper can be accepted as it is with a missing orcid for one author, I would go ahead without it and close the issue in the repo.

It can. 

@migueldvb - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by migueldvb** [comment]
@arfon I have made a DOI for the v0.2.1 release with Zenodo:
https://doi.org/10.5281/zenodo.345982

The title in the markdown paper file is changed to be more especific, 'Cine: line excitation by infrared fluorescence in cometary atmospheres', could you update it in the submission?

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.345982 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.345982" target="_blank">10.5281/zenodo.345982</a> is the archive.

**Comment by arfon** [comment]
Many thanks for the excellent review here @eteq ✨ 

@migueldvb - your paper is now accepted into JOSS and the DOI is http://dx.doi.org/10.21105/joss.00182 ⚡️ 🚀 💥
