### ISSUE TITLE
[REVIEW]: tabula: An R Package for Analysis, Seriation and Visualization of Archaeological Count Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1821]
**Submitting author:** @nfrerebeau (<a href="http://orcid.org/0000-0001-5759-4944">Nicolas Frerebeau</a>)
**Repository:** <a href="https://github.com/nfrerebeau/tabula" target ="_blank">https://github.com/nfrerebeau/tabula</a>
**Version:** v1.4.0
**Editor:** @oliviaguest
**Reviewer:** @izaromanowska, @soodoku
**Archive:** <a href="https://doi.org/10.5281/zenodo.3552904" target="_blank">10.5281/zenodo.3552904</a>

## Status

[![status](https://joss.theoj.org/papers/d4f9ee7bc85e4e6cb66bb12406570b73/status.svg)](https://joss.theoj.org/papers/d4f9ee7bc85e4e6cb66bb12406570b73)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d4f9ee7bc85e4e6cb66bb12406570b73"><img src="https://joss.theoj.org/papers/d4f9ee7bc85e4e6cb66bb12406570b73/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d4f9ee7bc85e4e6cb66bb12406570b73/status.svg)](https://joss.theoj.org/papers/d4f9ee7bc85e4e6cb66bb12406570b73)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/nfrerebeau/tabula" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@izaromanowska & @soodoku, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @oliviaguest know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nfrerebeau/tabula">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@nfrerebeau) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nfrerebeau/tabula">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@nfrerebeau) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @izaromanowska, @soodoku it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01821/joss.01821/10.21105.joss.01821.pdf)

**Comment by oliviaguest** [comment]
Hey @izaromanowska and @soodoku!

This is where the reviewing proper happens. You need to go through the checklist and feel free to post questions here and open review issues in the submission repository: https://github.com/nfrerebeau/tabula (If you do please link to them here to help keep track.)

**Comment by izaromanowska** [comment]
Hi @oliviaguest, I've done the review following the checklist. All works well as far as I can tell and is impressively well described. Do you need a written review as well?
One tiny suggestion is to mention in the readme that khroma needs to be installed and loaded. Probably unnecessary for most users but it's the only dependency that kicked off when checking examples on a freshly installed RStudio.

**Comment by oliviaguest** [comment]
@izaromanowska thank you!

> All works well as far as I can tell and is impressively well described. Do you need a written review as well?

It's up to you how much further feedback or ideas you want to share with the authors.

**Comment by oliviaguest** [comment]
@soodoku any chance you can get this within the next week?

**Comment by soodoku** [comment]
@oliviaguest --- plausibly. will work on the weekend on this, getting started sooner.

**Comment by oliviaguest** [comment]
@soodoku thanks! 
@nfrerebeau have you made any edits with respect to what @izaromanowska has given you feedback on?

**Comment by nfrerebeau** [comment]
As suggested by @izaromanowska, I have modified the README so that khroma is installed and loaded.

**Comment by oliviaguest** [comment]
@soodoku any luck finding time? I can set up an automated reminder for you if you want?

**Comment by soodoku** [comment]
not yet, @oliviaguest  but soon. on my agenda.

**Comment by soodoku** [comment]
I have created a few issues. None are blockers but would love to get @nfrerebeau's eyes on them. 

https://github.com/nfrerebeau/tabula/issues

once that's done, we can move fast.

**Comment by oliviaguest** [comment]
@soodoku thank you!

**Comment by nfrerebeau** [comment]
@soodoku thank you for all these constructive remarks. I will look in detail before the weekend and make the necessary changes.

**Comment by soodoku** [comment]
good to go from my end. thanks @nfrerebeau for bearing with me.

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01821/joss.01821/10.21105.joss.01821.pdf)

**Comment by oliviaguest** [comment]
@nfrerebeau please check the article and let me know if everything looks good to you. :smile:

**Comment by nfrerebeau** [comment]
@oliviaguest I fixed a small typo, everything else is OK!

**Comment by oliviaguest** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by oliviaguest** [comment]
@nfrerebeau oh, forgot to ask you to archive this using a DOI service you want, e.g., Zenodo, figshare, etc. Post the DOI back so I or you can run: 

```
@whedon set 10.0000/zenodo.00000 as archive

```

**Comment by nfrerebeau** [comment]
I don't know what number you need:

* DOI of version 1.4.0 (including changes made during the review): 10.5281/zenodo.3552904
* DOI for all versions: 10.5281/zenodo.1489944

**Comment by oliviaguest** [comment]
@nfrerebeau ah, I need the one of the software that is the most updated and with the edits you made during the review.

**Comment by nfrerebeau** [comment]
@oliviaguest this one: 10.5281/zenodo.3552904

**Comment by oliviaguest** [comment]
@whedon set 10.5281/zenodo.3552904 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3552904" target="_blank">10.5281/zenodo.3552904</a> is the archive.

**Comment by oliviaguest** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.jas.2011.06.031 is OK
- 10.18637/jss.v022.i04 is OK
- 10.2307/278341 is OK
- 10.1016/j.jas.2016.05.006 is OK
- 10.1007/3-540-28084-7_34 is OK
- 10.1371/journal.pone.0124942 is OK

MISSING DOIs

- https://doi.org/10.2307/501681 may be missing for title: A Quantitative Method for Deriving Cultural Chronology
- https://doi.org/10.2307/2843012 may be missing for title: Sequences in Prehistoric Remains

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1132

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1132, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by oliviaguest** [comment]
@nfrerebeau can you check the final proof and add any missing DOIs that apply, please? 😊

**Comment by nfrerebeau** [comment]
@oliviaguest only one of the two references had a DOI missing. I just added it!

**Comment by oliviaguest** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.jas.2011.06.031 is OK
- 10.18637/jss.v022.i04 is OK
- 10.2307/278341 is OK
- 10.1016/j.jas.2016.05.006 is OK
- 10.1007/3-540-28084-7_34 is OK
- 10.1371/journal.pone.0124942 is OK
- 10.2307/2843012 is OK

MISSING DOIs

- https://doi.org/10.2307/501681 may be missing for title: A Quantitative Method for Deriving Cultural Chronology

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1133

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1133, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by oliviaguest** [comment]
@openjournals/joss-eics can somebody please accept this? Thank you. :smile_cat:

**Comment by oliviaguest** [comment]
@nfrerebeau is that other missing one a false alarm?

**Comment by nfrerebeau** [comment]
@oliviaguest yes, the suggested DOI points to a review of the article and not the original publication. As far as I know, this reference does not have a DOI.

**Comment by oliviaguest** [comment]
@labarba :wave: I assumed tagging @openjournals/joss-eics above is enough to get this accepted... What am I missing?

**Comment by Kevin-Mattheus-Moerman** [comment]
@oliviaguest No further steps required. It is my turn this week. Apologies for the delay I'll get to it later this evening.

**Comment by oliviaguest** [comment]
@Kevin-Mattheus-Moerman ah, thanks! I tagged Lorena because she is helping me out. Sorry for the extra pressure (none intended) — was more worried I did something wrong. Thanks again!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set v1.4.0 as version

**Comment by whedon** [comment]
OK. v1.4.0 is the version.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01821/joss.01821/10.21105.joss.01821.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@nfrerebeau below are some suggested changes for your paper:

- [ ] The paper contains 1 instance of `...allowed the...` and 3 instances of `...allow the...`. Please consider adding `for`, i.e. so it reads `... allowed for the...`, and `... allow for the...` (or change to use `enabled`, `enables`). 
- [ ] In this sentence the referencing can be improved `It may use a priori information, e.g., absolute dates or stratigraphical constraints: Poblome & Groenen (2003), and allows the analysis of chronological patterns in a socio-economic or cultural perspective, e.g., Bellanger & Husi (2012), Lipo, Madsen, & Dunnell (2015).`, 
Consider reformatting to: 
`It may use a priori information, e.g., absolute dates or stratigraphical constraints (Poblome & Groenen 2003), and allows for the analysis of chronological patterns in a socio-economic or cultural perspective (e.g., (Bellanger & Husi 2012), (Lipo, Madsen, & Dunnell 2015)).`
- [ ] In `...count data, e.g., artifacts, faunal remains, etc.` consider rephrasing to `...count data, such as artifacts and faunal remains`, which reads better and avoids the use of `etc.` at the end of a sentence.
- [ ] In `...of diversity indices and implements seriation/ordination methods, but...`, since packages is plural this should have `implement` not `implements`. 
- [ ] Should the `[a]` be added here? `...Estimated dates can then be displayed as [a] tempo or activity plot...`
- [ ] If I understand the following correctly:  `...abundance plots, heatmaps, Ford (1962), and Bertin (1977) diagrams.` , perhaps it should read this instead: `...abundance plots, heatmaps, and Ford (1962) and Bertin (1977) diagrams.`
- [ ] In `All the contributors have made...`, I suggest: `The following contributors have made...`

**Comment by Kevin-Mattheus-Moerman** [comment]
@nfrerebeau 
- [ ] Please amend the meta data for the Zenodo archived version such that the title and the author set matches that of the paper. 
- [ ] The archived version lists version v1.4.0 (which I've updated here already), can you confirm this is correct (and that this is the version of the reviewed and archived software)?

**Comment by nfrerebeau** [comment]
@Kevin-Mattheus-Moerman I made the changes you suggested. Thank you for taking the time to improve my text.

I modified the title of the Zenodo archive. The author set in the meta data already matches that of the paper, or am I missing something?

I confirm that v1.4.0 is the version of the reviewed and archived software.

**Comment by oliviaguest** [comment]
@nfrerebeau if you can tick them off, that will help — thanks! :smile:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01821/joss.01821/10.21105.joss.01821.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@nfrerebeau nearly there. I left one box unchecked. You introduced `[a]` but I meant for you to introduce `a`, so please remove the square brackets. You can call `@whedon generate pdf` here when you are done. Thanks.

**Comment by nfrerebeau** [comment]
I was a little too fast on this one :sweat_smile:

**Comment by nfrerebeau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01821/joss.01821/10.21105.joss.01821.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.jas.2011.06.031 is OK
- 10.18637/jss.v022.i04 is OK
- 10.2307/278341 is OK
- 10.1016/j.jas.2016.05.006 is OK
- 10.1007/3-540-28084-7_34 is OK
- 10.1371/journal.pone.0124942 is OK
- 10.2307/2843012 is OK

MISSING DOIs

- https://doi.org/10.2307/501681 may be missing for title: A Quantitative Method for Deriving Cultural Chronology

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1141

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1141, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1201508283275776000) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1142
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01821](https://doi.org/10.21105/joss.01821)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01821/status.svg)](https://doi.org/10.21105/joss.01821)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01821">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01821/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01821/status.svg
   :target: https://doi.org/10.21105/joss.01821
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01821/status.svg)](https://doi.org/10.21105/joss.01821)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by nfrerebeau** [comment]
@izaromanowska, @soodoku, @oliviaguest and @Kevin-Mattheus-Moerman many thanks!!
