### ISSUE TITLE
[REVIEW]: pyscal : A python module for structural analysis of atomic environments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1824]
**Submitting author:** @srmnitc (<a href="http://orcid.org/0000-0002-6776-1213">Sarath Menon</a>)
**Repository:** <a href="https://github.com/srmnitc/pyscal" target ="_blank">https://github.com/srmnitc/pyscal</a>
**Version:** v2.0.1
**Editor:** @melissawm
**Reviewer:** @lucydot, @bocklund
**Archive:** <a href="https://doi.org/10.5281/zenodo.3522376" target="_blank">10.5281/zenodo.3522376</a>

## Status

[![status](https://joss.theoj.org/papers/168eca482155601dc517523899527a4e/status.svg)](https://joss.theoj.org/papers/168eca482155601dc517523899527a4e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/168eca482155601dc517523899527a4e"><img src="https://joss.theoj.org/papers/168eca482155601dc517523899527a4e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/168eca482155601dc517523899527a4e/status.svg)](https://joss.theoj.org/papers/168eca482155601dc517523899527a4e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/srmnitc/pyscal" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@lucydot & @bocklund, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @melissawm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/srmnitc/pyscal">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@srmnitc) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/srmnitc/pyscal">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@srmnitc) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lucydot, @bocklund it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01824/joss.01824/10.21105.joss.01824.pdf)

**Comment by bocklund** [comment]
I just finished my first pass on the review. I have a couple outstanding items to address:

**Installation:** Does installation proceed as outlined in the documentation? - I opened https://github.com/srmnitc/pyscal/issues/31. After this is closed, I can check this box.

**State of the field:** Do the authors describe how this software compares to other commonly-used packages - This is missing from the documentation and the JOSS paper.

**Comment by srmnitc** [comment]
@bocklund thanks a lot for the quick review. I will work on the issues soon. Just a quick clarification regarding the **State of the field** part. I know ideally it should be on the paper, but do you think adding it to documentation will suffice?

**Comment by lucydot** [comment]
Hi @srmnitc - I just finished my first look over. The documentation is really nice, and I like the use of binder for someone who wants to get a quick feel for the code.

**Installation:** I have the same issue as reported in srmnitc/pyscal#31 when installing through conda. I can confirm installation runs smoothly using `python setup.py install` in a conda environment as outlined in the documentation [here](https://pyscal.readthedocs.io/en/latest/gettingstarted.html#using-a-conda-environment).

**State of the field:** I don't want to call whether this is ok in the broader documentation, perhaps the editor @melissawm could clarify? It's listed under `Software paper` in the checklist, but I think it is a new addition to the checklist and there isn't explicit mention of it in the JOSS ReadTheDocs ([link](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)). It is stated that there should be `"A list of key references, including to other software addressing related needs"` - you reference Lechner 2016, though perhaps there is other software that could be referenced in addition to this. For me, it also links to the statement of need - what does your code enable that existing codes do not?

**Documentation:** I have a few suggestions regarding the documentation; these are just ideas that would not block paper acceptance. I've raised an issue in the repo: srmnitc/pyscal#34.

**Comment by srmnitc** [comment]
@lucydot thanks for the review and the comments. I think I can add few sentences in the paper about other codes. There are few other python modules, but none of them seems to be maintained/documented, and lacks all of the features this module has. Bigger tools like LAMMPS, for example, can also do this, but the target is different. We are looking at mostly post-processing of data. But I will add few sentences in the paper regarding this. Once again, thanks for the quick review.

**Comment by srmnitc** [comment]
@lucydot @bocklund I have added both numpy and matplotlib as dependencies. srmnitc/pyscal#31 has been closed.

**Comment by srmnitc** [comment]
@bocklund  @lucydot  @melissawm,  About **State of the field**, 661b6770c62dc2f5e91b066a28dcbb63f785cfbe has an updated version of paper that references another [python module](https://pyboo.readthedocs.io/en/latest/) has some overlapping functionality. This is the only one I could find with documentation and a doi. [LAMMPS](https://lammps.sandia.gov/) and [PLUMED](https://www.plumed.org/) can also calculate the basic version of Steinhardt parameters, but the primary focus is completely different, so I think they will not fall in the same category as this module.

**Comment by srmnitc** [comment]
@whedon  generate pdf

**Comment by lucydot** [comment]
@srmnitc  - fab, I can confirm that tests pass after install via conda. I'm also happy to tick off state of the field. I'd like another day or two to play around with the code (rather than just run through the examples given) before signing off - Lucy

**Comment by srmnitc** [comment]
@lucydot  thanks!

**Comment by bocklund** [comment]
With the latest changes, I'm recommending this submission for acceptance. Nice work, @srmnitc! @melissawm

**Comment by srmnitc** [comment]
@bocklund thanks for the review and suggestions!

**Comment by melissawm** [comment]
Thank you @lucydot and @bocklund for your review!

@srmnitc now you should create an archive (on Zenodo, figshare, or other) and post the archive DOI here in the REVIEW issue so we can generate the paper.  Thank you!

**Comment by srmnitc** [comment]
@melissawm I have created the archive. The DOI is 10.5281/zenodo.3522376

**Comment by lucydot** [comment]
@srmnitc good work, it was a pleasure to review and happy to recommend for acceptance

**Comment by melissawm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01824/joss.01824/10.21105.joss.01824.pdf)

**Comment by srmnitc** [comment]
@melissawm PDF looks to be correct. Thanks!

**Comment by melissawm** [comment]
@srmnitc A few points on the citations:
- In the citation of *Auer, S. & Frenkel, D. (2005)*, the correct citation from (https://link.springer.com/chapter/10.1007%2Fb99429#citeas)[Springer] reads: "Cite this chapter as: Auer S., Frenkel D. Numerical Simulation of Crystal Nucleation in Colloids. In: Dr. Holm C., Prof. Dr. Kremer K. (eds) Advanced Computer Simulation. Advances in Polymer Science, vol 173. Springer, Berlin, Heidelberg"
- Just to make sure, when you cite pybind11 you cite it as *Jakob, W., Rhinelander, J., & Moldovan, D. (2016)*, but there are several other contributors listed on that project. Is that information something the authors recommend for citing?
- For the citation "Kresse, G., & Furthmüller, J. (1996a). Efficiency of ab-initio total energy calculations for
metals and semiconductors using a plane-wave basis set. Computational Materials Science, 6, 15.", please check the Volume, Issue and Pages number (I believe it should read Volume 6, Issue 1, Pages 15-50)
- In the citation to VORO++, I believe it should read "Chaos: An Interdisciplinary Journal of Nonlinear Science, 19, 041111"
- Please check the Volume and Number information for the citation to "Stukowski, A (2012)" (I believe from the website it should be Volume 20, Number 4)

**Comment by srmnitc** [comment]
@melissawm I have not included the number for any of the citations. Should I include the number too?

**Comment by melissawm** [comment]
@srmnitc If it's consistent I believe it's not necessary.

**Comment by srmnitc** [comment]
@melissawm  thanks. I am checking the other corrections you pointed out.

**Comment by srmnitc** [comment]
@melissawm  I have corrected most of the issues. I have not included number/issue in any of the citations. For pybind11, I have used the proposed way of citation by the developers. Also for page numbers, I have only used the first page number. Once again, thanks for the suggestions!

**Comment by melissawm** [comment]
@whedon set 10.5281/zenodo.3522376 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3522376" target="_blank">10.5281/zenodo.3522376</a> is the archive.

**Comment by melissawm** [comment]
@openjournals/joss-eics I believe this is ready for final acceptance.

Thanks, @srmnitc !

**Comment by srmnitc** [comment]
Thanks @melissawm !

**Comment by danielskatz** [comment]
@srmnitc - is the version still v2.0.0?

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01824/joss.01824/10.21105.joss.01824.pdf)

**Comment by srmnitc** [comment]
@danielskatz its 2.0.1 now. Thanks!

**Comment by danielskatz** [comment]
@whedon set v2.0.1 as version

**Comment by whedon** [comment]
OK. v2.0.1 is the version.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/b99429 is OK
- 10.1016/0927-0256(96)00008-0 is OK
- 10.1103/PhysRevB.54.11169 is OK
- 10.1103/PhysRevB.47.558 is OK
- 10.1063/1.2977970 is OK
- 10.1063/1.4774084 is OK
- 10.1006/jcph.1995.1039 is OK
- 10.1063/1.3215722 is OK
- 10.1103/PhysRevB.28.784 is OK
- 10.1088/0965-0393/20/4/045021 is OK
- 10.1063/1.4729313 is OK
- 10.5281/zenodo.1066568 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1079

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1079, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@srmnitc - can you remove the space before the colon in the paper.md and the zenodo repository title?  This should be "pyscal: A ..."

**Comment by srmnitc** [comment]
@danielskatz made the changes. thanks!

**Comment by danielskatz** [comment]
Can you also merge https://github.com/srmnitc/pyscal/pull/38 ?

**Comment by srmnitc** [comment]
@danielskatz merged

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01824/joss.01824/10.21105.joss.01824.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/b99429 is OK
- 10.1016/0927-0256(96)00008-0 is OK
- 10.1103/PhysRevB.54.11169 is OK
- 10.1103/PhysRevB.47.558 is OK
- 10.1063/1.2977970 is OK
- 10.1063/1.4774084 is OK
- 10.1006/jcph.1995.1039 is OK
- 10.1063/1.3215722 is OK
- 10.1103/PhysRevB.28.784 is OK
- 10.1088/0965-0393/20/4/045021 is OK
- 10.1063/1.4729313 is OK
- 10.5281/zenodo.1066568 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1080

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1080, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
sorry, I didn't check the bib entries at the same time - can you also merge https://github.com/srmnitc/pyscal/pull/39 ?

**Comment by srmnitc** [comment]
@danielskatz merged. thanks!

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01824/joss.01824/10.21105.joss.01824.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/b99429 is OK
- 10.1016/0927-0256(96)00008-0 is OK
- 10.1103/PhysRevB.54.11169 is OK
- 10.1103/PhysRevB.47.558 is OK
- 10.1063/1.2977970 is OK
- 10.1063/1.4774084 is OK
- 10.1006/jcph.1995.1039 is OK
- 10.1063/1.3215722 is OK
- 10.1103/PhysRevB.28.784 is OK
- 10.1088/0965-0393/20/4/045021 is OK
- 10.1063/1.4729313 is OK
- 10.5281/zenodo.1066568 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1081

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1081, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1190368521433296896) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1082
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01824](https://doi.org/10.21105/joss.01824)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @lucydot & @bocklund for reviewing and @melissawm for editing!
And to @srmnitc for putting up with up with a bunch of little last minute changes!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01824/status.svg)](https://doi.org/10.21105/joss.01824)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01824">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01824/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01824/status.svg
   :target: https://doi.org/10.21105/joss.01824
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01824/status.svg)](https://doi.org/10.21105/joss.01824)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by srmnitc** [comment]
@danielskatz thanks a lot !

**Comment by srmnitc** [comment]
@arfon Hi Arfon, I am the author of the package in this review, which is now published. I had a quick question. We would like to change the license of the package from GNU GPL to BSD. It still remains open source, but it is for integration into a larger project. Is this okay from the perspective of JOSS? Sorry about the trouble!

**Comment by arfon** [comment]
@srmnitc - this is fine with us. Thanks for checking!
