### ISSUE TITLE
[PRE REVIEW]: rtweet: Collecting and analyzing Twitter data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1826]
**Submitting author:** @mkearney (<a href="http://orcid.org/0000-0002-0730-4694">Michael Wayne Kearney</a>)
**Repository:** <a href="https://github.com/ropensci/rtweet" target ="_blank">https://github.com/ropensci/rtweet</a>
**Version:** v0.7.0
**Editor:** @kthyng
**Reviewers:** @kthyng

**Author instructions**

Thanks for submitting your paper to JOSS @mkearney. **Currently, there isn't an JOSS editor assigned** to your paper.

@mkearney if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01826/joss.01826/10.21105.joss.01826.pdf)

**Comment by kthyng** [comment]
Hi @arokem! Would you be willing to edit this submission? Thanks in advance.

**Comment by mkearney** [comment]
This package has been reviewed by rOpenSci: https://github.com/ropensci/software-review/issues/302, @ropensci/editors

**Comment by mkearney** [comment]
@whedon set 10.5281/zenodo.3515425 as archive

**Comment by whedon** [comment]
I'm sorry @mkearney, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by mkearney** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1177/1461444818822813 is OK
- 10.1177/2055207618821521 is OK
- 10.1007/s11036-018-1055-6 is OK

MISSING DOIs

- https://doi.org/10.5210/fm.v23i12.9540 may be missing for title: A Simulated Cyberattack on Twitter: Assessing Partisan Vulnerability to Spear Phishing and Disinformation ahead of the 2018 US Midterm Elections
- https://doi.org/10.3389/fphy.2019.00098 may be missing for title: Sentiment-based prediction of alternative cryptocurrency price fluctuations using gradient boosting tree model

INVALID DOIs

- https://doi.org/10.5281/zenodo.2528481 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1080/14459795.2019.1606927 is INVALID because of 'https://doi.org/' prefix
- 10.5281/zenodo.1188429. is INVALID
- https://doi.org/10.1016/j.jairtraman.2019.01.010 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.jvacx.2019.100019 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1177/F1461444818809392 is INVALID because of 'https://doi.org/' prefix
- https://dx.doi.org/10.1038/s41746-018-0017-5 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.tele.2017.09.015 is INVALID because of 'https://doi.org/' prefix
```

**Comment by mkearney** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01826/joss.01826/10.21105.joss.01826.pdf)

**Comment by mkearney** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by mkearney** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2528481 is OK
- 10.5210/fm.v23i12.9540 is OK
- 10.1080/14459795.2019.1606927 is OK
- 10.1016/j.jairtraman.2019.01.010 is OK
- 10.1177/1461444818822813 is OK
- 10.3389/fphy.2019.00098 is OK
- 10.1177/2055207618821521 is OK
- 10.1016/j.jvacx.2019.100019 is OK
- 10.1016/j.tele.2017.09.015 is OK
- 10.1007/s11036-018-1055-6 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.5281/zenodo.1188429. is INVALID
- 10.1177/F1461444818809392 is INVALID
- https://dx.doi.org/10.1038/s41746-018-0017-5 is INVALID because of 'https://doi.org/' prefix
```

**Comment by mkearney** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01826/joss.01826/10.21105.joss.01826.pdf)

**Comment by mkearney** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2528481 is OK
- 10.5210/fm.v23i12.9540 is OK
- 10.1080/14459795.2019.1606927 is OK
- 10.5281/zenodo.1188429 is OK
- 10.1016/j.jairtraman.2019.01.010 is OK
- 10.1177/1461444818822813 is OK
- 10.3389/fphy.2019.00098 is OK
- 10.1177/2055207618821521 is OK
- 10.1016/j.jvacx.2019.100019 is OK
- 10.1177/1461444818809392 is OK
- 10.1038/s41746-018-0017-5 is OK
- 10.1016/j.tele.2017.09.015 is OK
- 10.1007/s11036-018-1055-6 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
> Hi @arokem! Would you be willing to edit this submission? Thanks in advance.

Just kidding, I will edit it since it is from rOpenSci.

**Comment by kthyng** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
@whedon assign @kthyng as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kthyng

**Comment by kthyng** [comment]
Hi @mkearney! Thanks for your submission. I am not familiar with rOpenSci, but in looking at your review there, I see that it is still open. Does that mean that it has not been completed yet?

**Comment by mkearney** [comment]
@kthyng The review of my submission has been completed, but they may consider the joss paper as part of the process? I know @ropensci has a history and documented workflow for submitting the accompanied paper.md, but I cannot speak to the nature or extent of the relationship between the two–for that hopefully @sckott can chime in!

**Comment by mkearney** [comment]
Nevermind, the issue has actually been closed!

**Comment by sckott** [comment]
the ropensci review is done ✅

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1829. Feel free to close this issue now!
