### ISSUE TITLE
[PRE REVIEW]: BioSimSpace: An interoperable Python framework for biomolecular simulation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1827]
**Submitting author:** @lohedges (<a href="http://orcid.org/0000-0002-5624-0500">Lester Hedges</a>)
**Repository:** <a href="https://github.com/michellab/BioSimSpace" target ="_blank">https://github.com/michellab/BioSimSpace</a>
**Version:** 2019.2.0
**Editor:** @will-rowe
**Reviewers:** @amritagos, @richardjgowers

**Author instructions**

Thanks for submitting your paper to JOSS @lohedges. The JOSS editor @will-rowe, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@lohedges if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @trallard it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@trallard) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1827 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
Sorry I forgot to unassign suggested editor @trallard when I started this issue.

**Comment by kthyng** [comment]
@will-rowe Would you be interested in trying this for your first JOSS submission as editor?

**Comment by kthyng** [comment]
@lohedges Is this pointing to the incorrect github repo or branch currently? Can you clarify the difference in the branches and which is correct to use for your JOSS submission?

**Comment by lohedges** [comment]
Hi @kthyng. Our paper is currently in the `feature-paper` branch of our repository (within a `paper` directory at the top level). Our plan was to merge this into our development branch, `devel`, when ready for publication, then into `master` for our next release. If you need the paper to be accessible from the main branch then I can merge across into `devel` now. Let me know what is preferable. (The `feature-paper` branch is fully up-to-date with `devel` so has all of the latest features.)

(I had mentioned this in our "paper description" section during the submission, but hadn't thought about the paper being processes by a bot :-) )

**Comment by will-rowe** [comment]
Sure @kthyng - thanks for the invite!

**Comment by will-rowe** [comment]
@whedon assign @will-rowe as editor

**Comment by whedon** [comment]
OK, the editor is @will-rowe

**Comment by will-rowe** [comment]
Hi @richardjgowers , @fdroessler, @MDebasish - would you be able to review this paper?

**Comment by richardjgowers** [comment]
@will-rowe yep

**Comment by lohedges** [comment]
@whedon generate pdf from branch feature-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01827/joss.01827/10.21105.joss.01827.pdf)

**Comment by lohedges** [comment]
@whedon generate pdf from branch feature-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01827/joss.01827/10.21105.joss.01827.pdf)

**Comment by lohedges** [comment]
@whedon generate pdf from branch feature-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01827/joss.01827/10.21105.joss.01827.pdf)

**Comment by lohedges** [comment]
Apologies for all the PDF renderings. Figured out how to compile from a custom branch. Just ironing out some minor formatting issues.

Does anyone know how to force a page break? It would be nice to make sure that the code snippets aren't split across multiple pages. (Obviously this could all change following any edits anyway.)

**Comment by lohedges** [comment]
@whedon generate pdf from branch feature-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01827/joss.01827/10.21105.joss.01827.pdf)

**Comment by kthyng** [comment]
> Hi @kthyng. Our paper is currently in the `feature-paper` branch of our repository (within a `paper` directory at the top level). Our plan was to merge this into our development branch, `devel`, when ready for publication, then into `master` for our next release. If you need the paper to be accessible from the main branch then I can merge across into `devel` now. Let me know what is preferable. (The `feature-paper` branch is fully up-to-date with `devel` so has all of the latest features.)
> 
> (I had mentioned this in our "paper description" section during the submission, but hadn't thought about the paper being processes by a bot :-) )

Actually I did click the button myself (not a bot) and I saw your note but wasn't careful enough and am not sure where to find that information now that I clicked the button to start the issue :) That's how I knew to ask anyway.

As you found, you can generate the pdf from a branch. From my understanding, the reviewers will review the code in the github repo listed on this review issue, but the paper is located in the `feature-paper` branch of this repo. Is that accurate?

**Comment by kthyng** [comment]
@lohedges Can you go through your paper and work on how to cite your references inline?  You can see details here: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography
I'm looking especially at the first paragraph under Molecular dynamics on the first page.

**Comment by kthyng** [comment]
@lohedges Re: forcing page break:
I am not sure but this will work in Markdown generally so I think it should work here (found [here](https://stackoverflow.com/questions/22601053/pagebreak-in-markdown-while-creating-pdf)): 

`<div style="page-break-after: always;"></div>`

**Comment by lohedges** [comment]
@kthyng 

> Actually I did click the button myself (not a bot) and I saw your note but wasn't careful enough and am not sure where to find that information now that I clicked the button to start the issue :) That's how I knew to ask anyway.

Apologies for confusing you with a bot :-) You are indeed a _bot master_, wheddon caters to _your_ whims, not vice versa.

> From my understanding, the reviewers will review the code in the github repo listed on this review issue, but the paper is located in the feature-paper branch of this repo. Is that accurate?

Yes, the repository is located at the link given at the top of this thread, i.e. [https://github.com/michellab/BioSimSpace](https://github.com/michellab/BioSimSpace). This points to the default branch of our repo, which is `devel`, which is what should be used for review purposes. However, the paper is currently located on the `feature-paper` branch, so reviewers will currently need to use that branch when generating a PDF. (The branch is fully up to date with `devel`, so there is no issue with reviewing the code from either branch, but ultimately the repository link that accompaines the paper should be the one listed above.) As mentioned, the plan is to merge `feature-paper` into `devel` when the paper is ready for publication, then `devel` will be merged into `master` at the time of our next release.

> Can you go through your paper and work on how to cite your references inline? You can see details here: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

This is now fixed. I'm not quite sure how that happened, since I followed the guide you linked to when writing the paper. Originally they were hyperlinks to the websites of the different molecular dynamics engines, so I must have forgotten to delete the first set of square brackets.

> I am not sure but this will work in Markdown generally so I think it should work here (found here):

Thanks, I've tested locally and this seems to work fine. I'll leave as is for now since things will likely jump around a bit if edits are needed. I'll make sure to tidy up the layout as much as possible at the proof stage.

Thanks for your help, much appreciated.

**Comment by lohedges** [comment]
@whedon generate pdf from branch feature-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01827/joss.01827/10.21105.joss.01827.pdf)

**Comment by lohedges** [comment]
@whedon generate pdf from branch feature-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01827/joss.01827/10.21105.joss.01827.pdf)

**Comment by will-rowe** [comment]
Thanks @richardjgowers - will let you know when we are ready to start the review.

**Comment by will-rowe** [comment]
Hi @amritagos - would you be able to review this submission?

**Comment by will-rowe** [comment]
@whedon assign @richardjgowers as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @richardjgowers

**Comment by will-rowe** [comment]
@whedon assign @richardjgowers as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @richardjgowers

**Comment by amritagos** [comment]
Sure, I'd be happy to @will-rowe.

**Comment by will-rowe** [comment]
Excellent - thank you @amritagos !

**Comment by will-rowe** [comment]
@whedon assign @amritagos as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @amritagos

**Comment by will-rowe** [comment]
@whedon add @richardjgowers as reviewer

**Comment by whedon** [comment]
OK, @richardjgowers is now a reviewer

**Comment by will-rowe** [comment]
sorry for the re-assigns, I'm still getting use to the system!

I think we have all we need now. Are you happy for the review process to start @lohedges ?

**Comment by lohedges** [comment]
Thanks, @will-rowe. I'm happy for the review process to start.

Let me know if you, or the reviewers, have any questions about the repository layout that I discussed in reply to @kthyng above. I understand that this is possibly non-standard, but hopefully it doesn't cause issue with the review process.

Cheers!

**Comment by will-rowe** [comment]
No worries @lohedges - I'll copy over your instructions re. branch info so that they are in the review issue for reference

@whedon start review

**Comment by will-rowe** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1831. Feel free to close this issue now!
