### ISSUE TITLE
[REVIEW]: rtweet: Collecting and analyzing Twitter data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1829]
**Submitting author:** @mkearney (<a href="http://orcid.org/0000-0002-0730-4694">Michael Wayne Kearney</a>)
**Repository:** <a href="https://github.com/ropensci/rtweet" target ="_blank">https://github.com/ropensci/rtweet</a>
**Version:** v0.7.0
**Editor:** @kthyng
**Reviewer:** @kthyng
**Archive:** <a href="https://doi.org/10.5281/zenodo.3515425" target="_blank">10.5281/zenodo.3515425</a>

## Status

[![status](https://joss.theoj.org/papers/5ec648d979e162cfc1d85e35cb0e3202/status.svg)](https://joss.theoj.org/papers/5ec648d979e162cfc1d85e35cb0e3202)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5ec648d979e162cfc1d85e35cb0e3202"><img src="https://joss.theoj.org/papers/5ec648d979e162cfc1d85e35cb0e3202/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5ec648d979e162cfc1d85e35cb0e3202/status.svg)](https://joss.theoj.org/papers/5ec648d979e162cfc1d85e35cb0e3202)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ropensci/rtweet" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kthyng, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ropensci/rtweet">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mkearney) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kthyng it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01829/joss.01829/10.21105.joss.01829.pdf)

**Comment by kthyng** [comment]
This submission was already [reviewed](https://github.com/ropensci/software-review/issues/302) as part of rOpenSci.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01829/joss.01829/10.21105.joss.01829.pdf)

**Comment by kthyng** [comment]
@mkearney There is a reference that's not coming through in your paper — can you check on that?

Also I will be needing your Zenodo archive.

**Comment by mkearney** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01829/joss.01829/10.21105.joss.01829.pdf)

**Comment by mkearney** [comment]
@kthyng I believe I fixed the missing reference issue. And is this what you need for the zenodo doi/archive: http://doi.org/10.5281/zenodo.3515425?

**Comment by kthyng** [comment]
@mkearney Yes the reference issue looks resolved now.

Yes, that zenodo archive is what I need, though can you change the title so that it matches your paper?

**Comment by mkearney** [comment]
Done!

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.3515425 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3515425" target="_blank">10.5281/zenodo.3515425</a> is the archive.

**Comment by kthyng** [comment]
Ok I think I have everything now! I can go through the acceptance process now.

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2528481 is OK
- 10.5210/fm.v23i12.9540 is OK
- 10.1080/14459795.2019.1606927 is OK
- 10.5281/zenodo.1188429 is OK
- 10.1016/j.jairtraman.2019.01.010 is OK
- 10.1177/1461444818822813 is OK
- 10.3389/fphy.2019.00098 is OK
- 10.1177/2055207618821521 is OK
- 10.1016/j.jvacx.2019.100019 is OK
- 10.1177/1461444818809392 is OK
- 10.1038/s41746-018-0017-5 is OK
- 10.1016/j.tele.2017.09.015 is OK
- 10.1007/s11036-018-1055-6 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1049

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1049, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1187440427714207744) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1050
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01829](https://doi.org/10.21105/joss.01829)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Congratulations @mkearney on your new paper!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01829/status.svg)](https://doi.org/10.21105/joss.01829)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01829">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01829/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01829/status.svg
   :target: https://doi.org/10.21105/joss.01829
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01829/status.svg)](https://doi.org/10.21105/joss.01829)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
