### ISSUE TITLE
[PRE REVIEW]: plotrr: Functions for making visual exploratory data analysis with nested data easier. Edit

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#183]
**Submitting author:** @cdcrabtree (<a href="http://orcid.org/0000-0001-5144-8671">Charles Crabtree</a>)
**Repository:** <a href="https://github.com/cdcrabtree/plotrr" target ="_blank">https://github.com/cdcrabtree/plotrr</a>
**Version:** v0.2.0
**Editor:** @pjotrp
**Reviewer:** @kbroman

**What this issue is for**

Thanks for submitting your paper to JOSS @cdcrabtree. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:Wave @noamross - this package looks like a potential good candidate for rOpenSci because of the focus on data visualization.

**Comment by pjotrp** [comment]
@arfon I can edit this one if you like.

**Comment by noamross** [comment]
@arfon Thanks. This doesn't meet the threshold for us as an extension beyond base or ggplot graphics.

**Comment by arfon** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by arfon** [comment]
> @arfon I can edit this one if you like.

Thanks @pjotrp.

**Comment by pjotrp** [comment]
I am asking around for reviewers.

**Comment by pjotrp** [comment]
@whedon assign @kbroman as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kbroman

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/190. Feel free to close this issue now!

**Comment by pjotrp** [comment]
All set. Use the link above.
