### ISSUE TITLE
[REVIEW]: RepnDecomp: A GAP package for decomposing linear representations of finite groups

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1835]
**Submitting author:** @kaashif (<a href="http://orcid.org/0000-0001-8581-5804">Kaashif Hymabaccus</a>)
**Repository:** <a href="https://github.com/gap-packages/RepnDecomp/" target ="_blank">https://github.com/gap-packages/RepnDecomp</a>
**Version:** 1.0.1
**Editor:** @VivianePons
**Reviewer:** @alex-konovalov, @falque
**Archive:** <a href="https://doi.org/10.5281/zenodo.3884306" target="_blank">10.5281/zenodo.3884306</a>

## Status

[![status](https://joss.theoj.org/papers/f260c31c9befafe72f990ced039c092a/status.svg)](https://joss.theoj.org/papers/f260c31c9befafe72f990ced039c092a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f260c31c9befafe72f990ced039c092a"><img src="https://joss.theoj.org/papers/f260c31c9befafe72f990ced039c092a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f260c31c9befafe72f990ced039c092a/status.svg)](https://joss.theoj.org/papers/f260c31c9befafe72f990ced039c092a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://gitlab.com/kaashif/decomp/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@alex-konovalov & @falque, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @VivianePons know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/kaashif/decomp/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@kaashif) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/kaashif/decomp/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@kaashif) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @alex-konovalov, @falque it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01835/joss.01835/10.21105.joss.01835.pdf)

**Comment by falque** [comment]
Hello there :)

I have started to review the submission, and since I am new to this whole reviewing process I am very very sorry if I miss some obvious elements, ask stupid questions, or such things...

The check list I have to fill has a section called Software paper, I assume it to be this: https://github.com/openjournals/joss-papers/blob/joss.01835/joss.01835/10.21105.joss.01835.pdf.
And I also assume that the items I need to check are directly related to this paper, but I have only found the information dwelled on by the State of the field item in the README file, so maybe it should be moved or copied to the paper ?
As for the authors, two names appear in the paper, but only one in the documentation, I guess it is because the other one will not be maintaining the code. Even though, in PackageInfo.g, Dmitrii Pasechnik is indicated as neither maintaining nor authoring, is that normal ?

Now, again, I assume the Documentation section of the checklist is about the documentation, which I reckon is that hosted at https://kaashif.gitlab.io/decomp/chap1.html#X789233A47A277072. Maybe I missed something, but I do not find there the Installation Instructions (second item of the list). I did find the list of dependencies in PackageInfo.g but maybe something explicit is expected in the documentation itself ?

These are of course details and I have not taken a deep look yet but for now it looks very nice !

**Comment by alex-konovalov** [comment]
@falque 
> Even though, in PackageInfo.g, Dmitrii Pasechnik is indicated as neither maintaining nor authoring, is that normal ?
Yes, one could now to this in PackageInfo.g in GAP, to give credit to those contributors who are neither authors nor maintainers.

**Comment by VivianePons** [comment]
Hi there,

Thank you @falque for your remarks, @kaashif did you have time to think about her questions?

**Comment by kaashif** [comment]
@falque Very sorry for the delay in reply, I was on holiday for the last 10 days.

> Hello there :)
> 
> I have started to review the submission, and since I am new to this whole reviewing process I am very very sorry if I miss some obvious elements, ask stupid questions, or such things...

I am also new to this process, there is no way your questions could be more stupid than mine :)

> The check list I have to fill has a section called Software paper, I assume it to be this: https://github.com/openjournals/joss-papers/blob/joss.01835/joss.01835/10.21105.joss.01835.pdf.
> And I also assume that the items I need to check are directly related to this paper, but I have only found the information dwelled on by the State of the field item in the README file, so maybe it should be moved or copied to the paper ?

Yes, I suppose this is useful context which belongs in the paper.

> Now, again, I assume the Documentation section of the checklist is about the documentation, which I reckon is that hosted at https://kaashif.gitlab.io/decomp/chap1.html#X789233A47A277072. Maybe I missed something, but I do not find there the Installation Instructions (second item of the list). I did find the list of dependencies in PackageInfo.g but maybe something explicit is expected in the documentation itself ?

Yes, I forgot installation instructions, I will add these.

> These are of course details and I have not taken a deep look yet but for now it looks very nice !

Thanks. I have a problem though, my employer still needs to approve any publications or contributions to software I make (this is a one-time thing). This should be a formality since this software is obviously (at least to me) unrelated to my work and not even in the same language, but these kinds of reviews are low priority and it takes a while for those responsible to actually do them.

I will chase some people on Monday and hopefully I'll make your suggested changes then.

**Comment by kaashif** [comment]
A quick update: I contacted the correct people and they will get around to reviewing my request eventually. I hope I'm not being too cautious, but people do get fired over this kind of thing sometimes, especially when working on sensitive financial software. Sorry I can't move this along a bit more promptly.

**Comment by kaashif** [comment]
The massive corporate bureacracy has churned and I have been told there are no IP concerns in this project! I'll make the changes and push them on the weekend. By that I mean the test fixes @alex-konovalov pointed out I need and the missing/jumbled docs @falque pointed out.

From now on, any delay is my fault :)

**Comment by VivianePons** [comment]
Good to know :) Glad that we are back on track!

**Comment by kaashif** [comment]
Changes I have made due to comments by @falque:

* Copied the comment about the state of the field to the paper.md. The comment is just that no open source software exists to do this but methods are well-known, so it's quite short.

* Added installation instructions to README and a link to the README in the first section of the documentation

From comments by @alex-konovalov:

* Fixed tests. The error he reported [here](https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-devel/jobs/584474552) was just a difference in how vector spaces were printed, before it was "0 generators" now it's "dimension 0". They do pass now on the newest GAP.

From really old comments by @dimpase:

* It was unclear what "representation" meant in terms of GAP (you need a finite group, coefficients in Cyclotomics (NOT finite fields)) and in some places I just use "rho" without even mentioning that it's a representation. I added a paragraph about this in the first manual section.

All changes have been pushed [here](https://gitlab.com/kaashif/decomp/).

**Comment by alex-konovalov** [comment]
@kaashif @dimpase is there a plan to submit this package for the redistribution with GAP?

**Comment by dimpase** [comment]
@alex-konovalov - will we make the coming GAP 4.11 release if we do it this week?

**Comment by alex-konovalov** [comment]
If it will satisfy the requirements and pass integration tests, then yes. To go ahead, please suggest depositing the package by email to GAP Support, and submit a PR to https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/currentPackageInfoURLList adding its PackageInfo.g URL.

**Comment by alex-konovalov** [comment]
@dimpase however, you need to establish a proper package webpage and releases process first - at the moment, https://gitlab.com/kaashif/decomp/blob/master/PackageInfo.g just points to the GitLab repository, and the link to package archive will not work. Maybe you want to migrate to https://github.com/gap-packages first, and then use ReleaseTools and GitHubPagesForGAP to set them up using our standard tools? (I think I have suggested that to you elsewhere, but can't see in the discussion above).

**Comment by kaashif** [comment]
Yeah I think migrating to https://github.com/gap-packages is a good idea, I've started doing that now. I'll also do the ReleaseTools stuff, change all of the URLs etc. I will also change the URL in the paper.md.

**Comment by kaashif** [comment]
@VivianePons Is there a way for me to change the source repository URL in the JOSS paper to point to https://github.com/gap-packages/RepnDecomp, since this is the place where proper GAP packages live?

**Comment by VivianePons** [comment]
I have updated the github issue. @openjournals/dev can you make the requied change wherever it is needed? Thanks!

**Comment by arfon** [comment]
> I have updated the github issue. @openjournals/dev can you make the requied change wherever it is needed? Thanks!

Done.

**Comment by VivianePons** [comment]
Dear all,

where are we on this? I see @kaashif has made some changes following the reviewers remarks, @alex-konovalov and @falque can you have a look and let me know where you stand in terms of acceptance (and check the boxes in the issue description accordingly).

**Comment by alex-konovalov** [comment]
Thanks for the reminder @VivianePons - I still have to evaluate the new version and check how this is aligned with getting the package redistributed with GAP. I shall find time for this in February.

**Comment by kaashif** [comment]
I'll have some time to work on this project this weekend. I think I can have all of the issues closed in a few days, I just didn't have much time over Christmas and New Year.

**Comment by danielskatz** [comment]
👋 @kaashif  - any news?

**Comment by alex-konovalov** [comment]
@danielskatz @VivianePons the package has been submitted for the redistribution with GAP, testing outcomes were reported at https://github.com/gap-system/gap-distribution/pull/101. We are waiting now for the next release of the package to be published, then I will check its compatibility with GAP and other packages, and hopefully it will be suitable for the redisribituion with GAP. This will allow me to complete the review.

**Comment by kaashif** [comment]
Oh, sorry, I made the changes but didn't publish a new version, doing that now

**Comment by kaashif** [comment]
Done, the manual examples, new non-flaky tests, and some changes from @alex-konovalov and @dimpase are now published in version 1.1.0: https://gap-packages.github.io/RepnDecomp/. Let me know what you think.

**Comment by VivianePons** [comment]
Perfect!
@alex-konovalov let me know when you can complete the review
@falque where are you on this? Could you have a look and let me know?

**Comment by falque** [comment]
@VivianePons Sorry, I kind of lost the thread, I'm going to take a look (probably tomorrow) and come back to you. Sorry again !

**Comment by falque** [comment]
As far as I am concerned, everything is okay (installation, tests, documentation, well, you can see the checklist) ! As a tiny remark, in the Testing section of the README file, I would add at the beginning that this is all supposed to take place in the previously unzipped ~/.gap/pkg/RepnDecomp . To be sure, it is highly guessable, but it took me a short while to understand so I think it could only be an improvement, especially for non-experts.

**Comment by VivianePons** [comment]
Thank you @falque and thanks for the suggestion, I agree with you that the clearer the better.

Now I'm only waiting for @alex-konovalov , where are we in terms of GAP realeases and package testing?

**Comment by kaashif** [comment]
> 
> 
> As far as I am concerned, everything is okay (installation, tests, documentation, well, you can see the checklist) ! As a tiny remark, in the Testing section of the README file, I would add at the beginning that this is all supposed to take place in the previously unzipped ~/.gap/pkg/RepnDecomp . To be sure, it is highly guessable, but it took me a short while to understand so I think it could only be an improvement, especially for non-experts.

Thanks for the suggestion, I'll change that now.

**Comment by alex-konovalov** [comment]
@VivianePons some progress - RepnDecomp will be definitely included in GAP 4.11.0, which will be publicly announced shortly. I will finish the review after that. Hope we can get it out in March!

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arfon** [comment]
:wave: @alex-konovalov, just a friendly check-in to see how things are going with your review?

**Comment by alex-konovalov** [comment]
@arfon thanks for the reminder. We published GAP 4.11.0 which includes RepnDecomp (https://www.gap-system.org/Releases/4.11.0.html), I will try to complete the review shortly.

**Comment by alex-konovalov** [comment]
@arfon @kaashif It all looks good to me - some minor remarks:

- the package has been migrated to https://github.com/gap-packages/RepnDecomp so I did not tick the first box which refers to the old repository. The link in the paper needs to be updated.

- installation instructions at https://github.com/gap-packages/RepnDecomp/blob/master/README.md describe how to install a development version of the package from its repository, in `./gap/pkg` directory where users can keep their customisations. First, you now have a proper versioning, so I would be suggesting to download latest official release from https://gap-packages.github.io/RepnDecomp/ (unless the user wants the development version). Second, since the package is now redistributed with GAP, you can mention that users having GAP 4.11.0 or newer will not have to install the package, since it is already included in the GAP distribution). 

- some wording in the paper needs to be improved, for example

```
When studying problems in algebra and combinatorics, it is
often useful to pass to a representation to more easily understand the
structure of the problem. 
```
to pass what? Also, "more easily" -> "easier" or "better"

```
This is also useful for computation, since
we can use representations to transform our algebraic problems into
linear algebra. 
```
"into linear algebra" does not sound right to me.

```
finding a basis which block diagonalises the matrices of the
representation optimally, 
```
Perhaps"which finds an optimal block diagonal form"...

```
* Decompose a representation into irreducibles
```
"into irreducible representations" ?

```
Our methods are not specific to cyclotomic numbers, but the GAP
algebra system ...
```
Either just "the GAP system" or "the GAP computational algebra system".
In fact, this is the first time GAP mentioned here. It would be useful to
add a reference ([see how](https://www.gap-system.org/Contacts/cite.html)).

**Comment by kaashif** [comment]
Thanks for the feedback, I agree some of the phrasing is a bit awkward and I'll address your comments shortly. Also thanks for reminding me about the new installation instructions now that there are real releases and versions.

One comment:

> "into linear algebra" does not sound right to me.

It sounds fine to me from a linguistic perspective, but maybe this isn't how mathematicians really speak. Maybe I should say "representations allow us to use tools from linear algebra to solve problems in group theory" or something along those lines.

**Comment by alex-konovalov** [comment]
@kaashif your new formulation sounds perfect to me, thanks! I think, saying "into linear algebra" is acceptable informally, but not in a paper.

**Comment by dimpase** [comment]
Thanks a lot for looking into this. 

Just one remark - I think "irredicubles" is an acceptable domain terminology - the rest I agree with.

**Comment by alex-konovalov** [comment]
Informally, it's fine, and it's clear from the context whether one means irreducible polynomials, or characters, or representations - but in the paper, I'd still prefer to avoid using adjectives as nouns.

**Comment by dimpase** [comment]
y8

**Comment by kaashif** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01835/joss.01835/10.21105.joss.01835.pdf)

**Comment by kaashif** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01835/joss.01835/10.21105.joss.01835.pdf)

**Comment by dimpase** [comment]
URL for GAP is off, and also there should be abn URL for the package itself

**Comment by dimpase** [comment]
text says "we produced a package for GAP" - the package should be named (and perhaps hyperlinked to its URL)

**Comment by kaashif** [comment]
Suggestions from @alex-konovalov:

>     * the package has been migrated to https://github.com/gap-packages/RepnDecomp so I did not tick the first box which refers to the old repository. The link in the paper needs to be updated.

The latest PDF which I have generated contains a correct link to the repository at 
https://github.com/gap-packages/RepnDecomp.

>     * installation instructions at https://github.com/gap-packages/RepnDecomp/blob/master/README.md describe how to install a development version of the package from its repository, in `./gap/pkg` directory where users can keep their customisations. First, you now have a proper versioning, so I would suggest to a user to download the latest official release from https://gap-packages.github.io/RepnDecomp/ (unless the user wants the development version). Second, since the package is now redistributed with GAP, you can mention that users having GAP 4.11.0 or newer will not have to install the package, since it is already included in the GAP distribution.

I improved the installation instructions in [the README](https://github.com/gap-packages/RepnDecomp#installation).

>     * some wording in the paper needs to be improved, for example
> 
> 
> ```
> When studying problems in algebra and combinatorics, it is
> often useful to pass to a representation to more easily understand the
> structure of the problem. 
> ```
> 
> to pass what? Also, "more easily" -> "easier" or "better"

I changed this to "When studying problems in algebra and combinatorics, it is often useful to also study associated representations to better understand the structure of the problem."

> ```
> This is also useful for computation, since
> we can use representations to transform our algebraic problems into
> linear algebra. 
> ```
> 
> "into linear algebra" does not sound right to me.

I changed this to "This is also useful for computation, since representations allow us to use tools from linear algebra to solve problems in group theory."

> ```
> finding a basis which block diagonalises the matrices of the
> representation optimally, 
> ```
> 
> Perhaps"which finds an optimal block diagonal form"...

I changed this to "finding a basis which produces an optimal block diagonal form of the representation". I think it is important to make it clear that the package is mainly for finding the basis. Finding an optimal block diagonal form is easy, involving only some character theory and use of off-the-shelf GAP functions, finding the basis is the tricky part.

> ```
> * Decompose a representation into irreducibles
> ```
> 
> "into irreducible representations" ?

I changed this to "Decompose a representation into a direct sum of irreducible representations".

> ```
> Our methods are not specific to cyclotomic numbers, but the GAP
> algebra system ...
> ```
> 
> Either just "the GAP system" or "the GAP computational algebra system".
> In fact, this is the first time GAP mentioned here. It would be useful to
> add a reference ([see how](https://www.gap-system.org/Contacts/cite.html)).

I changed this to "the GAP system" and I also added a citation for GAP before the bullet points.

From @dimpase:

I added a link to the package in the text of the paper, just before the bullet points. Also I fixed the URLs :)

From me:

I noticed that the unicode theta (as in Lovasz theta number) was not rendering in the PDFs, so I changed it to the TeX `\vartheta`, it looks right now.

**Comment by kaashif** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01835/joss.01835/10.21105.joss.01835.pdf)

**Comment by dimpase** [comment]
OK, few more things:

- add a reference to Kaashif's MSc thesis (the implementation of the package was a part of KH's MSc thesis)
- add an acknowledgement to CODIMA (K.H. thanks Collaborative Computational Project (CCP) in the area of Computational Discrete Mathematics, supported by the EPSRC (EP/M022641/1) for supporting his participation in a GAP workshop) 
- add an acknowledgement of OpenDreamKit (D.P. is partly funded by the OpenDreamKit Horizon 2020 European Research Infrastructures project (#676541))

**Comment by kaashif** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01835/joss.01835/10.21105.joss.01835.pdf)

**Comment by kaashif** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01835/joss.01835/10.21105.joss.01835.pdf)

**Comment by dimpase** [comment]
Looks good to go. Thanks a lot!

**Comment by dimpase** [comment]
Is now back with reviewers? Just wondering.

**Comment by VivianePons** [comment]
@alex-konovalov and @falque can you check that everything is in order and that you're happy now to move to the next step (acceptance!)?

**Comment by alex-konovalov** [comment]
@VivianePons thanks - looks good to me now, happy to go to the next phase. @falque what do you think?

**Comment by kyleniemeyer** [comment]
Hi @VivianePons, it looks like this submission may be ready to finalize.

@kaashif can you archive the software repository (e.g., on Zenodo) and provide the DOI here?

**Comment by kaashif** [comment]
Sure. I made a new release and put it on Zenodo here: https://doi.org/10.5281/zenodo.3884306

**Comment by VivianePons** [comment]
Thank you @kyleniemeyer for the reminder! I will take it from here

**Comment by VivianePons** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s10107-006-0039-7 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by VivianePons** [comment]
@kaashif could you update the archive so that the metadata match the paper (title and authors). Thanks

**Comment by kaashif** [comment]
Sure, should be done now. Sorry, this is my first time putting something on Zenodo :)

**Comment by VivianePons** [comment]
@whedon set 10.5281/zenodo.3884306 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3884306" target="_blank">10.5281/zenodo.3884306</a> is the archive.

**Comment by VivianePons** [comment]
@whedon set 1.0.1 as version

**Comment by whedon** [comment]
OK. 1.0.1 is the version.

**Comment by VivianePons** [comment]
Congratulations! I am putting the paper up for acceptance.

Thank you @kaashif and @dimpase for the work and @alex-konovalov and @falque for the reviews and useful comments :)

**Comment by VivianePons** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s10107-006-0039-7 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1478

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1478, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
Hello @kaashif, in my final review of the article I noticed there were some DOIs missing (though our checker didn't catch them). I just submitted a small PR that adds these, can you merge it? https://github.com/gap-packages/RepnDecomp/pull/8

**Comment by kaashif** [comment]
Thanks, I merged your PR.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s10107-006-0039-7 is OK
- 10.1023/A:1015366416311 is OK
- 10.2307/2004848 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1481

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1481, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1270426506922274816) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1482
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01835](https://doi.org/10.21105/joss.01835)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @kaashif on your article's publication in JOSS!

Many thanks to @alex-konovalov and @falque for reviewing this submission, and to @VivianePons for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01835/status.svg)](https://doi.org/10.21105/joss.01835)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01835">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01835/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01835/status.svg
   :target: https://doi.org/10.21105/joss.01835
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01835/status.svg)](https://doi.org/10.21105/joss.01835)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
