### ISSUE TITLE
[PRE REVIEW]: libRL: A Python library for the characterization of microwave absorption

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1836]
**Submitting author:** @1mikegrn (<a href="http://orcid.org/0000-0002-2525-1274">Michael Green</a>)
**Repository:** <a href="https://github.com/1mikegrn/libRL-package" target ="_blank">https://github.com/1mikegrn/libRL-package</a>
**Version:** v1.0.0
**Editor:** @dfm
**Reviewers:** @kjappelbaum, @mdoucet

**Author instructions**

Thanks for submitting your paper to JOSS @1mikegrn. **Currently, there isn't an JOSS editor assigned** to your paper.

@1mikegrn if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01836/joss.01836/10.21105.joss.01836.pdf)

**Comment by kthyng** [comment]
Hi @dfm! What do you think about editing this submission?

**Comment by dfm** [comment]
@kthyng: sure thing!

@GreenScarz: Please feel free to make suggestions for reviewers! You can find a list of potential reviewers [here](https://bit.ly/joss-reviewers) Otherwise, I'll start looking shortly.

@whedon assign @dfm as editor

**Comment by dfm** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
I'm sorry @dfm, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by dfm** [comment]
Whoops! Looks like the robot doesn't know me yet. @arfon: is there something else I need besides being a member of joss-editors?

**Comment by GreenScarz** [comment]
Hi @dfm and @kthyng , Thanks for taking the time to chat :) all of the analytical tools included therein are tools which I've used to publish materials research before; the biggest change has just been repackaging everything for general use. So really, anyone who has a knack for being hypercritical about documentation and then trying to break things will suffice as a reviewer. In the test folder is example data which they can use when poking around at the library and reviewing all the software.

**Comment by GreenScarz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01836/joss.01836/10.21105.joss.01836.pdf)

**Comment by GreenScarz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01836/joss.01836/10.21105.joss.01836.pdf)

**Comment by GreenScarz** [comment]
Sorry I really don't want to be spamming this compilation command, but one last time...

**Comment by GreenScarz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01836/joss.01836/10.21105.joss.01836.pdf)

**Comment by arfon** [comment]
@dfm can you retry the assignment now?

**Comment by arfon** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@Kevin-Mattheus-Moerman
@VivianePons
@alexhanna
@arfon
@arokem
@brainstorm
@cMadan
@csoneson
@danielskatz
@dfm
@drvinceknight
@gkthiruvathukal
@jedbrown
@karthik
@katyhuff
@kbarnhart
@kthyng
@kyleniemeyer
@labarba
@leouieda
@lheagy
@lpantano
@majensen
@mbobra
@meg-simula
@melissawm
@mgymrek
@mjsottile
@oliviaguest
@poulson
@terrytangyuan
@trallard
@usethedata
@will-rowe
@xuanxu
```

**Comment by dfm** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by GreenScarz** [comment]
Hey does anyone here know if changing your GitHub username will negatively effect this review/publication process? Obviously I made this account before I realized that it would be used for professional functions haha, probably shouldn't be tethered to my gamertag.

**Comment by dfm** [comment]
@GreenScarz: It shouldn't be a problem to change your username - just let me know!

**Comment by 1mikegrn** [comment]
so new username is @1mikegrn , the @GreenScarz links are discontinued and I've updated the docs in the libRL library to contain the new pip installation instructions.

**Comment by 1mikegrn** [comment]
just curious

@whedon generate pdf

**Comment by 1mikegrn** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01836/joss.01836/10.21105.joss.01836.pdf)

**Comment by dfm** [comment]
:wave: @kjappelbaum @lucydot @utf: are any of you available to review this submission?

**Comment by lucydot** [comment]
Hi @dfm I'm currently in the middle of another JOSS review, I'd rather not commit to two.

**Comment by kjappelbaum** [comment]
Hi @dfm, I'm available.

**Comment by dfm** [comment]
@lucydot: sorry about that - I should have checked!

@kjappelbaum: Excellent - thanks. Just need one more!

**Comment by dfm** [comment]
@whedon assign @kjappelbaum as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kjappelbaum

**Comment by dfm** [comment]
:wave: @bjmorgan @jochym @mkhorton @yxqd: Would any of you be available to review this submission? I'd love to get one or two more reviewers. Thanks!

**Comment by dfm** [comment]
@1mikegrn: it's taking a while to get a second reviewer, but we'll get there. Thanks for your patience!

In the meantime, a quick suggestion: can you make sure that you're not committing autogenerated files to the repo (e.g. the `.c` and `.pyd` files and `build` directory in `libRL`).

**Comment by mkhorton** [comment]
Sorry, I don't think I'd be a suitable reviewer for this one!

**Comment by 1mikegrn** [comment]
No worries @dfm, I understand review process takes time. Looked into your comment a bit, glad you pointed that out because I was previously oblivious to OS dependencies for compiled cython files - implemented a patch which should clear everything up and mitigate OS dependencies from cython.

**Comment by dfm** [comment]
:wave: @garrettj403: Any chance you'd be available to review this submission?

**Comment by garrettj403** [comment]
Hi @dfm - I'm sorry, but I just started a new position and I don't have the time right now.

**Comment by dfm** [comment]
@garrettj403: No worries. Good luck with it!

**Comment by dfm** [comment]
:wave: @mdoucet: Any chance you're available to review this submission?

**Comment by mdoucet** [comment]
Yes. I can help!

**Comment by dfm** [comment]
@mdoucet: great - thank you! I'll add you as a reviewer and we'll get started.

**Comment by dfm** [comment]
@whedon add @mdoucet as reviewer

**Comment by whedon** [comment]
OK, @mdoucet is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1868. Feel free to close this issue now!

**Comment by dfm** [comment]
@1mikegrn, @kjappelbaum, @mdoucet: You can head over to #1868 to get started on the review. Thanks all!
