### ISSUE TITLE
[PRE REVIEW]: splot: visual analytics for spatial statistics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1838]
**Submitting author:** @slumnitz (<a href="http://orcid.org/0000-0002-7007-5812">Stefanie Lumnitz</a>)
**Repository:** <a href="https://github.com/pysal/splot" target ="_blank">https://github.com/pysal/splot</a>
**Version:** v1.1.1
**Editor:** @leouieda
**Reviewers:** @ResidentMario, @martinfleis

**Author instructions**

Thanks for submitting your paper to JOSS @slumnitz. **Currently, there isn't an JOSS editor assigned** to your paper.

@slumnitz if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01838/joss.01838/10.21105.joss.01838.pdf)

**Comment by danielskatz** [comment]
👋 @leouieda - would you be willing to edit this submission?

**Comment by slumnitz** [comment]
Suggestions for potential reviewers:
* [jorisvandenbossche](https://github.com/jorisvandenbossche) - geopandas
* [gboeing](https://github.com/gboeing) - osmnx
* [ResidentMario](https://github.com/ResidentMario) - geoplot

**Comment by leouieda** [comment]
Hi @danielskatz, sure thing :+1:

**Comment by leouieda** [comment]
@whedon assign @leouieda as editor

**Comment by whedon** [comment]
OK, the editor is @leouieda

**Comment by leouieda** [comment]
Hi @slumnitz thank you for the reviewer suggestions! I just opened a PR to fix a citation formatting issue on the paper. Once that is merged, we can ask @whedon to rebuild the PDF.

**Comment by leouieda** [comment]
:wave: Hi @jorisvandenbossche @gboeing would you like to review this submission for JOSS? "splot: visual analytics for spatial statistics" by @slumnitz (Stefanie Lumnitz) *et al*. Here are links to the [submitted paper](https://github.com/openjournals/joss-papers/blob/joss.01838/joss.01838/10.21105.joss.01838.pdf) and [software repository](https://github.com/pysal/splot). Please see [our documentation](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) for more information on what a JOSS review is like and feel free to ask any questions you may have (either here or privately by email).

**Comment by jorisvandenbossche** [comment]
@leouieda I am happy to review this submission. 

To disclose a potential conflict of interest: I acted as co-mentor during Stefanie's GSOC in 2018 while she worked on `splot` (as geopandas maintainer, to give feedback on the usage of geopandas in splot). However, I would describe my role as very limited (I was not involved in the direction or design of the package, but just gave some code feedback, and I also have no commit to the package), and so see myself able to do an impartial review. But let the final decision to you.

**Comment by danielskatz** [comment]
@leouieda - If you can find an alternate reviewer for @jorisvandenbossche given this conflict, please do.  If not, we can waive this conflict given the relationship, but it would be cleaned not to have to.

**Comment by leouieda** [comment]
@jorisvandenbossche thank you for the disclosure, it's much appreciated! I'll follow Dan's suggestion and try to find someone else for the time being so we can avoid the conflict. If I can't find anyone suitable, I'll contact you again to see if you're still available/willing.

**Comment by leouieda** [comment]
:wave: Hi @ResidentMario would you like to review this submission for JOSS? "splot: visual analytics for spatial statistics" by @slumnitz (Stefanie Lumnitz) et al. Please see the comments above for more details.

**Comment by gboeing** [comment]
I would normally be happy to assist with this, but I don't think I have the capacity to take it on right now. Best of luck -- I saw splot recently and it looks like a cool project!

**Comment by ResidentMario** [comment]
Sure, I can review it. I'm a bit busy this week, but should have the time to take a look next week.

**Comment by leouieda** [comment]
@gboeing thank you for letting me know :slightly_smiling_face:

**Comment by leouieda** [comment]
@ResidentMario thank you for agreeing to review :tada: I'm searching for a second reviewer and we'll start the actual review as soon as I find one.

**Comment by leouieda** [comment]
:wave: @kbevers would you like to review this submission for JOSS? "splot: visual analytics for spatial statistics" by @slumnitz (Stefanie Lumnitz) et al. Please see the comments above for more details.

**Comment by leouieda** [comment]
@whedon assign @ResidentMario as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ResidentMario

**Comment by kbevers** [comment]
@leouieda Sorry, I haven't got the necessary time to do this at the moment. Looks like a cool software package though, I'll keep it in mind for later plotting :-)

**Comment by martinfleis** [comment]
@leouieda If you're still looking for a reviewer, I'd be happy to do it. I've already used PySAL and splot in my own research, so this is very close to my interests. I guess I'll spend time exploring the capabilities of splot anyway.

**Comment by leouieda** [comment]
@martinfleis thank you volunteering :clap: I was still looking and it seems like you'd be a great fit.

**Comment by leouieda** [comment]
@whedon add @martinfleis as reviewer

**Comment by whedon** [comment]
OK, @martinfleis is now a reviewer

**Comment by leouieda** [comment]
@whedon star review

**Comment by leouieda** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1882. Feel free to close this issue now!
