### ISSUE TITLE
[PRE REVIEW]: YoungTab

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#184]
**Submitting author:** @luk87 (<a href="http://orcid.org/0000-0001-9033-1345">Luca Romano</a>)
**Repository:** <a href="https://github.com/luk87/YoungTab" target ="_blank">https://github.com/luk87/YoungTab</a>
**Version:** v1.0
**Editor:** @danielskatz
**Reviewer:** @jmichel7

**What this issue is for**

Thanks for submitting your paper to JOSS @luk87. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by luk87** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by luk87** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by luk87** [comment]
@whedon assign @jordigh as reviewer

**Comment by whedon** [comment]
I'm sorry @luk87, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by luk87** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current JOSS editors:

```
@acabunoc
@arfon
@arokem
@biorelated
@cMadan
@danielskatz
@jakevdp
@karthik
@katyhuff
@Kevin-Mattheus-Moerman
@kyleniemeyer
@labarba
@mgymrek
@pjotrp
@tracykteal
```

**Comment by luk87** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @luk87, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by arfon** [comment]
:wave: @luk87. Could you take a look at the editor list and see which editor might be closest to your research domain? http://joss.theoj.org/about#editorial_board

Once we have an editor assigned we can start looking for a reviewer.

**Comment by luk87** [comment]
Dear @arfon I think the editor closest to my research domain could be Jake Vanderplas . 
Thank you

**Comment by arfon** [comment]
> Dear @arfon I think the editor closest to my research domain could be Jake Vanderplas.

OK thanks. @jakevdp - any chance you could edit this submission for us?

**Comment by jakevdp** [comment]
Hi all – this is pretty far from my area of expertise, and I wouldn't even know where to begin in finding good reviewers for this (I haven't thought about Lie algebras since my second year of graduate school). I'd be happy to serve as editor, but @luk87 do you have any recommendations for appropriate people to review this? Thanks.

**Comment by danielskatz** [comment]
I can probably find a reviewer for this - if so, I would be happy to try to edit it.

**Comment by luk87** [comment]
Dear @jakevdp thank you for the answer, I do not know anyone who could be an appropriate reviewer.  Dear @danielskatz thank you, I would appreciate it.

**Comment by danielskatz** [comment]
@luk87. As I've talked to a couple of people in this area and browsed the code itself, it seems to me that this is not really research software, but is more a GUI around a somewhat simple code, with the intent that this is mostly used for education.  But I may be completely wrong, as this is not my technical area at all.

Can you help me understand the research usage of this software?

**Comment by luk87** [comment]
Dear @danielskatz in several areas, as higher spin physics, supergravity, double filed theory or General relativity as an example it is common to deal with tensors carrying indices in one of the classical Lie algebras.  Although  it is trivial to compute the dimension of irreps for the algebra A_{n} it is not completely trivial to impose irreducible conditions on tensors when one is dealing with the other algebras.  In these cases with the code one could immediately get the dimension of the representation codified in the tensor since it is trivial to translate tensorial indices in Young tableaux.

**Comment by danielskatz** [comment]
thanks - you might want to include this (or some version of it) in the documents/text about the software

**Comment by luk87** [comment]
Yes, thank you

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@whedon assign @jmichel7 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jmichel7

**Comment by danielskatz** [comment]
@whedon start review
no bananas - let's see if it works

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/221. Feel free to close this issue now!

**Comment by arfon** [comment]
> no bananas - let's see if it works

😞 sorry, I've still not fixed that yet @danielskatz
