### ISSUE TITLE
[PRE REVIEW]: emcee v3: A Python ensemble sampling toolkit for affine-invariant MCMC

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1840]
**Submitting author:** @dfm (<a href="http://orcid.org/0000-0002-9328-5652">Daniel Foreman-Mackey</a>)
**Repository:** <a href="https://github.com/dfm/emcee" target ="_blank">https://github.com/dfm/emcee</a>
**Version:** v3.0.1
**Editor:** @xuanxu
**Reviewers:** @benjaminrose, @mattpitkin

**Author instructions**

Thanks for submitting your paper to JOSS @dfm. The JOSS editor @xuanxu, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dfm if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @xuanxu it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@xuanxu) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01840/joss.01840/10.21105.joss.01840.pdf)

**Comment by danielskatz** [comment]
👋 @xuanxu - you were suggested as the editor for this submission, and I accidentally left you assigned when I started the process, rather than asking you first. Are you willing to do this?

**Comment by xuanxu** [comment]
@danielskatz no problem, I take it 👍

**Comment by dfm** [comment]
@danielskatz @xuanxu: thanks!

A potential reviewer is: @mattpitkin

I'll take a closer look through the list when I'm not trying to do it on my phone later 😊

**Comment by xuanxu** [comment]
:wave: @mattpitkin: would you be willing to review this paper? the author of the submission has suggested you as a good candidate.

**Comment by xuanxu** [comment]
:wave: @dhuppenkothen: would you be willing to review this paper? I think your knowledge of astronomy, statistics and Python makes you a great fit for this submission.

**Comment by arfon** [comment]
@xuanxu - I recently asked `@dhuppenkothen` to review something and she declined due to current work commitments.

**Comment by dfm** [comment]
Another potential reviewer: @benjaminrose

**Comment by benjaminrose** [comment]
I can review this project.

**Comment by mattpitkin** [comment]
Sorry for the delayed response. I'm happy to review this

**Comment by xuanxu** [comment]
@benjaminrose, @mattpitkin thanks! I’ll start the review issue right away.

**Comment by xuanxu** [comment]
@whedon add @benjaminrose as reviewer

**Comment by whedon** [comment]
OK, @benjaminrose is now a reviewer

**Comment by xuanxu** [comment]
@whedon add @mattpitkin as reviewer

**Comment by whedon** [comment]
OK, @mattpitkin is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1864. Feel free to close this issue now!

**Comment by xuanxu** [comment]
@benjaminrose, @mattpitkin: please head over to #1864 where the review will take place.
