### ISSUE TITLE
[PRE REVIEW]: MyQueue: Task and workflow scheduling system

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1841]
**Submitting author:** @jjmortensen (<a href="http://orcid.org/0000-0001-5090-6706">Jens Jørgen Mortensen</a>)
**Repository:** <a href="https://gitlab.com/myqueue/myqueue" target ="_blank">https://gitlab.com/myqueue/myqueue</a>
**Version:** 19.10.1
**Editor:** @danielskatz
**Reviewers:** @gonsie, @marksantcroos

**Author instructions**

Thanks for submitting your paper to JOSS @jjmortensen. **Currently, there isn't an JOSS editor assigned** to your paper.

@jjmortensen if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01841/joss.01841/10.21105.joss.01841.pdf)

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @jjmortensen - I have some ideas for reviewers, but do you also have some you want to recommend?  Potentially from [this list of potential reviewers](https://bit.ly/joss-reviewers)

**Comment by danielskatz** [comment]
👋 @dthain - Would you or one of the members of your group be interested in reviewing this submission for JOSS?

**Comment by dthain** [comment]
Maybe -- What are the expected standards for papers published in JOSS re length, novelty, literature review, etc.?

**Comment by danielskatz** [comment]
> What are the expected standards for papers published in JOSS re length, novelty, literature review, etc.?

Overall, see our [reviewer guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#guiding-principles) and our [review criteria](https://joss.readthedocs.io/en/latest/review_checklist.html). Specifically:

- Re length: JOSS papers are typically 250-1000 words, but the review is of both the paper and the software.  See https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain for guidance about paper expectations.
- Re novelty and literature review: Novelty is not a criterion for JOSS submissions, since the goal of JOSS is to create a citable object for software that is likely to be used - Also see https://joss.readthedocs.io/en/latest/review_criteria.html#an-important-note-about-novel-software-and-citations-of-relevant-work

**Comment by dthain** [comment]
So, it seems like the view criteria mostly address the "maturity" of the software in terms of documentation, installation, examples, etc, and the paper submission is more of a "cover letter".  Am I getting that correctly?

**Comment by dthain** [comment]
the "review criteria"

**Comment by danielskatz** [comment]
Yes, a main purpose again is to create a placeholder that fits the paper citation system to help developers get credit for their work in the academic system. A second purpose is to improve the software and software practices through the open, collaborative, and iterative review process.

**Comment by jjmortensen** [comment]
@danielskatz That's a long list of "potential reviewers"!  From a very quick scan of the list, maybe these are a good fit: pragyansmita, Funnelfiasco, marksantcroos, gonsie, zbeekman?

**Comment by danielskatz** [comment]
Thanks @gonsie - I'll add you to the system, but will wait until we have one or two more reviews before we start the review process.

**Comment by danielskatz** [comment]
@whedon assign @gonsie as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @gonsie

**Comment by zbeekman** [comment]
I'm a bit swamped right now. If you're in a bind and can't find another reviewer I'll do it, but in the interest of a timely review let's see if anyone else bites.

**Comment by marksantcroos** [comment]
Hi @danielskatz, @jjmortensen, I can take it.

**Comment by danielskatz** [comment]
Thanks @marksantcroos - hope you are doing well :)
I'll add you as a reviewer.

**Comment by danielskatz** [comment]
@dthain - we'll go ahead without you, but feel free to follow-along in the review thread that will be created shortly, perhaps to familiarize yourself with the process for a future review opportunity.

**Comment by danielskatz** [comment]
@whedon add @marksantcroos as reviewer

**Comment by whedon** [comment]
OK, @marksantcroos is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1844. Feel free to close this issue now!
