### ISSUE TITLE
[PRE REVIEW]: Miet: an R package for region of interest analysis from magnetic reasonance images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1842]
**Submitting author:** @benoit-combes (<a href="http://orcid.org/0000-0003-4161-7093">Benoit Combès</a>)
**Repository:** <a href="https://gitlab.inria.fr/miet/miet" target ="_blank">https://gitlab.inria.fr/miet/miet</a>
**Version:** 0.1.0
**Editor:** @arokem
**Reviewers:** @janfreyberg, @neuroimaginador

**Author instructions**

Thanks for submitting your paper to JOSS @benoit-combes. **Currently, there isn't an JOSS editor assigned** to your paper.

@benoit-combes if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1842 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1842 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by danielskatz** [comment]
👋 @arfon - I'm a bit confused about what the error is here - is this related to the figure?  Perhaps you can help?  (and maybe open a whedon issue related to better error message?)

**Comment by arfon** [comment]
@danielskatz - I think this is because the URL at the top can't be cloned by Git. It needs changing to `https://gitlab.inria.fr/miet/miet`

**Comment by danielskatz** [comment]
👋 @benoit-combes - Please change the paper.md as @arfon suggests, then enter a new comment here with ```@whedon generate pdf``` to try recompiling

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@danielskatz - just to clarify, the URL for the repo needed editing at the top of the issue (I've done this).

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01842/joss.01842/10.21105.joss.01842.pdf)

**Comment by danielskatz** [comment]
ah, sorry, I thought you meant in the paper.md - How did this wrong URL get in? User error in the submission form?

**Comment by arfon** [comment]
> ah, sorry, I thought you meant in the paper.md - How did this wrong URL get in? User error in the submission form?

Yeah, it was an error in the submission form. I've opened an issue to track this (https://github.com/openjournals/whedon/issues/60)

**Comment by benoit-combes** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by benoit-combes** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@Kevin-Mattheus-Moerman
@VivianePons
@alexhanna
@arfon
@arokem
@brainstorm
@cMadan
@csoneson
@danielskatz
@dfm
@drvinceknight
@gkthiruvathukal
@jedbrown
@karthik
@katyhuff
@kbarnhart
@kthyng
@kyleniemeyer
@labarba
@leouieda
@lheagy
@lpantano
@majensen
@mbobra
@meg-simula
@melissawm
@mgymrek
@mjsottile
@oliviaguest
@poulson
@terrytangyuan
@trallard
@usethedata
@will-rowe
@xuanxu
```

**Comment by benoit-combes** [comment]
May I suggest @arokem as editor ?
In addition to @neuroimaginador that appears to gather expertise in R, data analysis and neuroimaging (that are relevant for the paper) for reviewer ?

**Comment by arokem** [comment]
Yes. I can edit this.

**Comment by arokem** [comment]
@whedon assign arokem as editor

**Comment by whedon** [comment]
OK, the editor is arokem

**Comment by arokem** [comment]
👋 @neuroimaginador : would you be willing to review this paper for JOSS?

**Comment by arfon** [comment]
@arokem @brechmos (who's here at STScI) might be a good additional reviewer.

**Comment by arokem** [comment]
@brechmos : would you be willing to review this paper for JOSS?

**Comment by arokem** [comment]
👋 @janfreyberg : would you be willing to review this paper for JOSS? You are one of the only people among our reviewer pool who are neuro-savvy and also R-literate, so it would be a great help.

**Comment by janfreyberg** [comment]
@arokem yes, of course!

**Comment by arokem** [comment]
Wonderful. Thank you! I will assign you first, and then stand by until I find another reviewer and kick off the review for this.

**Comment by arokem** [comment]
@whedon assign @janfreyberg as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @janfreyberg

**Comment by neuroimaginador** [comment]
Hello, I'd like to review this work!!

**Comment by arokem** [comment]
Thanks @neuroimaginador ! You are on!

**Comment by arokem** [comment]
@whedon add @neuroimaginador as reviewer

**Comment by whedon** [comment]
OK, @neuroimaginador is now a reviewer

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1862. Feel free to close this issue now!

**Comment by arokem** [comment]
Alright, @janfreyberg and @neuroimaginador, please head over to #1862 for your reviewer check-lists. Feel free to tag me into issues, if you have any questions, as you work through this. I'll close this now. Thanks again!
