### ISSUE TITLE
[REVIEW]: JCOL: A Java package for solving the graph coloring problem

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1843]
**Submitting author:** @shah314 (<a href="http://orcid.org/0000-0002-3770-1391">Shalin S Shah</a>)
**Repository:** <a href="https://github.com/shah314/graphcoloring" target ="_blank">https://github.com/shah314/graphcoloring</a>
**Version:** v1.1
**Editor:** @jedbrown
**Reviewers:** @HaoZeke, @ProbShin
**Archive:** <a href="https://doi.org/10.5281/zenodo.3709625" target="_blank">10.5281/zenodo.3709625</a>

## Status

[![status](https://joss.theoj.org/papers/07cf7b3c7dc9037ad19f0b2ae81cde14/status.svg)](https://joss.theoj.org/papers/07cf7b3c7dc9037ad19f0b2ae81cde14)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/07cf7b3c7dc9037ad19f0b2ae81cde14"><img src="https://joss.theoj.org/papers/07cf7b3c7dc9037ad19f0b2ae81cde14/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/07cf7b3c7dc9037ad19f0b2ae81cde14/status.svg)](https://joss.theoj.org/papers/07cf7b3c7dc9037ad19f0b2ae81cde14)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/shah314/graphcoloring" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@HaoZeke and @ProbShin, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @jedbrown know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/shah314/graphcoloring">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@shah314) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/shah314/graphcoloring">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@shah314) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @HaoZeke it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01843/joss.01843/10.21105.joss.01843.pdf)

**Comment by jedbrown** [comment]
👋🏼 @HaoZeke Welcome and thanks for agreeing to review! The comments from @whedon above outline the review process, which takes place in this thread (possibly with issues filed in the [GraphColoring repository](https://github.com/shah314/graphcoloring)). I'll be watching this thread if you have any questions.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `https://github.com/openjournals/joss-reviews/issues/1843` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@jedbrown) if you have any questions/concerns.

**Comment by jedbrown** [comment]
@whedon add ProbShin as reviewer

**Comment by whedon** [comment]
OK, ProbShin is now a reviewer

**Comment by jedbrown** [comment]
:wave: @ProbShin Welcome, and thanks for agreeing to review! Please have a look at the instructions above and let me know if you have questions.

**Comment by shah314** [comment]
@jedbrown Can I change the name of the paper?

**Comment by jedbrown** [comment]
Yes.On Nov 20, 2019 14:40, Shalin Shah <notifications@github.com> wrote:@jedbrown Can I change the name of the paper?

**Comment by shah314** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01843/joss.01843/10.21105.joss.01843.pdf)

**Comment by shah314** [comment]
@jedbrown I have changed the name in the paper to the following:

JCOL: A Java package for solving the graph coloring problem

**Comment by shah314** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by danielskatz** [comment]
👋 @jedbrown - just checking in on the status of this review...

**Comment by jedbrown** [comment]
@ProbShin @HaoZeke :wave: How is your review going? Is there anything we can do to assist?

**Comment by HaoZeke** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1145/359094.359101 may be missing for title: New methods to color the vertices of a graph
- https://doi.org/10.1111/j.1475-3995.2009.00696.x may be missing for title: A survey on vertex coloring problems

INVALID DOIs

- None
```

**Comment by HaoZeke** [comment]
@jedbrown sorry, been dragging my feet because of a recent move. Will finish ASAP.

**Comment by HaoZeke** [comment]
@shah314 just to keep you informed. I will be working on my review with issues opened in the repository which should link back to this thread as well. Please feel free to address the issues as when and when you can.

**Comment by shah314** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01843/joss.01843/10.21105.joss.01843.pdf)

**Comment by shah314** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/359094.359101 is OK
- 10.7939/R3M32NH6Q is OK
- 10.1111/j.1475-3995.2009.00696.x is OK
- 10.1145/2513109.2513110 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by shah314** [comment]
@HaoZeke I have fixed the DOIs. Thanks for agreeing to review.

**Comment by shah314** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01843/joss.01843/10.21105.joss.01843.pdf)

**Comment by shah314** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01843/joss.01843/10.21105.joss.01843.pdf)

**Comment by shah314** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01843/joss.01843/10.21105.joss.01843.pdf)

**Comment by shah314** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01843/joss.01843/10.21105.joss.01843.pdf)

**Comment by shah314** [comment]
@HaoZeke I have made the changes you requested.

@ProbShin Any thoughts or questions?

**Comment by shah314** [comment]
@HaoZeke I have made the changes you requested (I think). Any further thoughts?

**Comment by shah314** [comment]
@ProbShin I see you have worked with ColPack but this code is in Java. Any questions on the implementation or the programming language?

**Comment by HaoZeke** [comment]
@shah314 Thank you for making the changes. I have completed my review and am pleased to recommend this for publication in its current state in JOSS. @jedbrown

**Comment by shah314** [comment]
@HaoZeke Thank you very much for the review!

**Comment by shah314** [comment]
@jedbrown Can you please update the name on the JOSS website? It still shows the old name.

https://joss.theoj.org/papers/07cf7b3c7dc9037ad19f0b2ae81cde14

Thank you!

**Comment by jedbrown** [comment]
I think it'll be straightforward or automatic upon acceptance -- I can't change that item on the website, but our EiC can when we accept (if it isn't automatic).

@ProbShin How is your review coming? Is there anything we can do to facilitate?

**Comment by labarba** [comment]
👋  hi everybody! I see this review stalled for 23 days — could we have an update from reviewers and authors on the status?

**Comment by shah314** [comment]
@labarba I see that the second reviewer @probshin is completely silent and has not even accepted the review process. Maybe we need to find another second reviewer. The first reviewer @HaoZeke has approved the work for publication on JOSS.

**Comment by jedbrown** [comment]
I've made contact with @ProbShin by email and he promises to complete the review in the next two weeks.

**Comment by ProbShin** [comment]
@shah314 Sorry for the late, I had been trapped by some accidents before. I am working on the reviews recently. Here are some [comments](https://github.com/shah314/graphcoloring/issues/5#issue-578970792) about the experiment results.

**Comment by shah314** [comment]
@ProbShin No problem. I completely understand. Sorry for the impatience. I'll reply to your comments in the issue thread. Thank you.

**Comment by shah314** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01843/joss.01843/10.21105.joss.01843.pdf)

**Comment by shah314** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01843/joss.01843/10.21105.joss.01843.pdf)

**Comment by ProbShin** [comment]
@shah314  Thanks for your understanding. 

Here are some [comments](https://github.com/shah314/graphcoloring/issues/6#issue-579422802) about the code implementation. And I need to emphasize again that some modification is recommended, and some modification is only needed depending on the goal of the project.

**Comment by ProbShin** [comment]
@shah314 Thanks for the modification and update. 
@jedbrown I have put several comments on test results and code implementation and provide the basic explanations. The author and I had a brief discussion of the modifications and changes.  I have done my review and I am pleased to recommend this for publication.

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01843/joss.01843/10.21105.joss.01843.pdf)

**Comment by jedbrown** [comment]
@ProbShin Thanks for your review. Before we proceed, could you please you check off your checklist at [the top of this thread](https://github.com/openjournals/joss-reviews/issues/1843#issue-514116573)?

**Comment by ProbShin** [comment]
@jedbrown Sure, I tried, but I cannot edit the checklist. I noticed that the invitation link might be revoked. Is it possible to reinvite me somehow, I guess that might grant me access to the checklist.

**Comment by jedbrown** [comment]
@whedon re-invite @ProbShin as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@probshin please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by ProbShin** [comment]
Thanks, @jedbrown

**Comment by shah314** [comment]
@jedbrown @ProbShin @HaoZeke Thanks all for the reviews!

**Comment by shah314** [comment]
@jedbrown I have created a Zenodo archive release. Here is the DOI:

10.5281/zenodo.3709625

Thank you!

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by shah314** [comment]
@arfon @jedbrown Completely understandable. Let me know if you need any help.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01843/joss.01843/10.21105.joss.01843.pdf)

**Comment by arfon** [comment]
@shah314 - could you update the author list on your Zenodo record to match the paper please? It currently includes @jedbrown which I'm guessing is due to him making a few edits to the paper.

**Comment by shah314** [comment]
@arfon I have updated the Zenodo author list. Thanks.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3709625 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3709625" target="_blank">10.5281/zenodo.3709625</a> is the archive.

**Comment by arfon** [comment]
@shah314 - I made some minor changes to your paper in https://github.com/shah314/graphcoloring/pull/7 that improve the readability.

**Comment by shah314** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01843/joss.01843/10.21105.joss.01843.pdf)

**Comment by shah314** [comment]
@arfon I just merged the pull request. Thank you for the changes.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1145/359094.359101 is OK
- 10.7939/R3M32NH6Q is OK
- 10.1111/j.1475-3995.2009.00696.x is OK
- 10.1145/2513109.2513110 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1403

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1403, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1246057259009966081) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1404
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01843](https://doi.org/10.21105/joss.01843)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@HaoZeke, @ProbShin - many thanks for your reviews here and to @jedbrown for editing this submission ✨ 

@shah314 - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01843/status.svg)](https://doi.org/10.21105/joss.01843)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01843">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01843/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01843/status.svg
   :target: https://doi.org/10.21105/joss.01843
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01843/status.svg)](https://doi.org/10.21105/joss.01843)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by shah314** [comment]
@jedbrown @arfon @ProbShin @HaoZeke Thanks all!
