### ISSUE TITLE
[PRE REVIEW]: HRV: a Pythonic package for Heart Rate Variability Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1846]
**Submitting author:** @rhenanbartels (<a href="http://orcid.org/0000-0002-6088-2186">Rhenan Bartels</a>)
**Repository:** <a href="https://github.com/rhenanbartels/hrv" target ="_blank">https://github.com/rhenanbartels/hrv</a>
**Version:** 0.2.4
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @hooman650, @PGomes92, @paulvangentcom

**Author instructions**

Thanks for submitting your paper to JOSS @rhenanbartels. **Currently, there isn't an JOSS editor assigned** to your paper.

@rhenanbartels if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01846/joss.01846/10.21105.joss.01846.pdf)

**Comment by danielskatz** [comment]
👋 @gkthiruvathukal - would you be willing to edit this submission?

**Comment by gkthiruvathukal** [comment]
@Kevin-Mattheus-Moerman Would be great if you can take this one. I'll be happy to take new ones starting next week.  Going through a bit of a rough stretch with the continued teachers' strike in Chicago and trying to keep middle/high school kids entertained while staying on top of my own work. So I should be in the clear by next week (I hope).

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@hooman650 would you be interested in reviewing this work for JOSS?

**Comment by hooman650** [comment]
@Kevin-Mattheus-Moerman heals, I would be happy to.

**Comment by Kevin-Mattheus-Moerman** [comment]
@rhenanbartels I'll be looking for reviewers for your submission. Let me know if you can recommend any reviewers. Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @hooman650 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @hooman650

**Comment by Kevin-Mattheus-Moerman** [comment]
@paulvangentcom @J535D165 @DominiqueMakowski @ismorphism @PGomes92 would you be interested in reviewing this submission for [JOSS](https://joss.theoj.org/)? It concerns a Python package for Heart Rate Variability Analysis. 

This is a pre-review issue which we use to recruit reviewers. Once we have sufficient reviewers we open a dedicated review issue. The [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) focuses on [the software ](https://github.com/rhenanbartels/hrv) and a [short paper](https://github.com/openjournals/joss-papers/blob/joss.01846/joss.01846/10.21105.joss.01846.pdf). 
Here is an example of a review process where  you can see that checkboxes guide the reviewers through the review process: https://github.com/openjournals/joss-reviews/issues/1745

Let me know if you have questions.

**Comment by PGomes92** [comment]
Hi @Kevin-Mattheus-Moerman,

thanks for asking me!

I would be glad to provide some help in the review and to provide some feedback on this work. I will have a closer look at the review process during the next days and let you know as soon as I have some questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @PGomes92 as reviewer

**Comment by whedon** [comment]
OK, @PGomes92 is now a reviewer

**Comment by paulvangentcom** [comment]
Hi @Kevin-Mattheus-Moerman, thanks for reaching out.

Note me down, I'd be happy to have a look at the review process, package and paper.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @paulvangentcom as reviewer

**Comment by whedon** [comment]
OK, @paulvangentcom is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
Okay I will now initiate the review process. :rocket: :robot:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1867. Feel free to close this issue now!
