### ISSUE TITLE
[REVIEW]: 3D reconstruction toolbox for behavior tracked with multiple cameras

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1849]
**Submitting author:** @SwathiSheshadri (<a href="http://orcid.org/0000-0003-2850-107X">Swathi Sheshadri</a>)
**Repository:** <a href="https://github.com/SwathiSheshadri/pose3d" target ="_blank">https://github.com/SwathiSheshadri/pose3d</a>
**Version:** v2.2.1
**Editor:** @cMadan
**Reviewer:** @danasolav, @sreschechtko
**Archive:** <a href="https://doi.org/10.5281/zenodo.3589990" target="_blank">10.5281/zenodo.3589990</a>

## Status

[![status](https://joss.theoj.org/papers/8e825866efe9a51e8f095d20bf99fd60/status.svg)](https://joss.theoj.org/papers/8e825866efe9a51e8f095d20bf99fd60)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8e825866efe9a51e8f095d20bf99fd60"><img src="https://joss.theoj.org/papers/8e825866efe9a51e8f095d20bf99fd60/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8e825866efe9a51e8f095d20bf99fd60/status.svg)](https://joss.theoj.org/papers/8e825866efe9a51e8f095d20bf99fd60)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/SwathiSheshadri/pose3d" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@danasolav & @sreschechtko, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @cMadan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SwathiSheshadri/pose3d">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@SwathiSheshadri) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SwathiSheshadri/pose3d">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@SwathiSheshadri) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @danasolav, @sreschechtko it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01849/joss.01849/10.21105.joss.01849.pdf)

**Comment by SwathiSheshadri** [comment]
@danasolav, @sreschechtko thank you for taking time to review our submission.
@cMadan, please assign the latest release version v1.1.0 for review.

**Comment by cMadan** [comment]
@whedon set v1.1.0 as version

**Comment by whedon** [comment]
OK. v1.1.0 is the version.

**Comment by sreschechtko** [comment]
I was able to install the package and run the demo as well as my own data. I have raised some issues (#[1-6](https://github.com/SwathiSheshadri/pose3d/issues)) which I ran into during this process and which I would like to see addressed before recommending the publication of this package in JOSS.

**Comment by cMadan** [comment]
@sreschechtko, thank you for the update!

**Comment by SwathiSheshadri** [comment]
Thank you very much @sreschechtko for your time as well as for giving us detailed and very constructive review comments. We are very happy to hear that the code ran for you for the demo as well as for your own data. We will work on the issues you have raised at the repository and write back to you here.

**Comment by danasolav** [comment]
I have installed and ran the demo successfully. I would like to run my own data which was not acquired using DLC. Therefore I have raised an issue ([#7](https://github.com/SwathiSheshadri/pose3d/issues/7)) regarding the instructions for creating the csv file which is used as input.

**Comment by SwathiSheshadri** [comment]
@sreschechtko, please see our responses on the issues you raised at pose3d (#[1-6](https://github.com/SwathiSheshadri/pose3d/issues)). We have addressed the issues and have updated the repository to reflect the changes. Please use the latest release of pose3d v2.0.0 to see the changes done to pose3d as per your comments. We found your feedback and detailed comments very helpful for us in refining our repository for public use and we thank you very much again for your time and effort and look forward to hearing from you!

**Comment by SwathiSheshadri** [comment]
@danasolav, we developed pose3d using our 2D tracked data from DLC and we are very happy to hear that you have 2D tracked data outside of DLC framework as this will help us get your  perspective on our code for this particular use-case. In our latest release of pose3d (v2.0.0), we have updated the readme file (addressing issue [#7](https://github.com/SwathiSheshadri/pose3d/issues/7) to include details on preparing the .csv files required for pose3d when using a different software for 2D tracking. Looking forward to hearing more about your experience with pose3d!

**Comment by sreschechtko** [comment]
Thank you for responding to my review issues. I have closed the majority of issues because I think they are satisfactorily addressed, although I had a few minor comments on [5](https://github.com/SwathiSheshadri/pose3d/issues/5) and [7](https://github.com/SwathiSheshadri/pose3d/issues/7).

The only issue I raised which I am leaving open is [3](https://github.com/SwathiSheshadri/pose3d/issues/3) for plotting 2D data with the 3D reconstruction. I think pose3d should have the option to plot the 2d points (which it already has access to) on an un-annotated video since annotated video is not necessarily commonly saved output. I would also like to a see more descriptive error message in the plotter if the video is not available but the option to plot it has been selected.

**Comment by SwathiSheshadri** [comment]
Thank you for closing the issues @sreschechtko  
I have addressed the open issue #3 as well as the minor comments in the latest release of pose3d (v2.1.0).  
The plotting function has been updated to allow feature annotation along with plotting video frames/images used for 2D tracking recorded from primary camera. Alternatively, make_illustrative_movie.m helper function is now updated to allow users to flexibly select from any number of perspectives they want to visualize alongside 3D reconstructed results. Furthermore, error handling in the config file has been upgraded to deal with missing video/image path entries in the config file. I have also removed the requirement of user input for frame rate and duration of recording parameters in the config file to make editing the config file easier, thereby, less error prone.
I again thank you both (@danasolav and @sreschechtko) for your time and very helpful feedback and would be very happy to hear back from you.

**Comment by sreschechtko** [comment]
Hi All, I have closed all of the issues I opened on the main repository and am happy to recommend the package/article for publication in JOSS.

**Comment by SwathiSheshadri** [comment]
Thank you for closing all the issues @danasolav and @sreschechtko. Your feedback was immensely valuable towards making pose3d better for public use and we are very grateful to both of you for your time and effort! @cMadan, we are very thankful to you and the JOSS team for taking time to edit our submission. We request you to use the latest release of pose3d - version v2.2.0, for further processing at JOSS and look forward to hearing from you about the next steps to take for our submission!

**Comment by cMadan** [comment]
Thank you for the thorough reviews, @danasolav and @sreschechtko!

**Comment by cMadan** [comment]
@whedon set v2.2.1 as version

**Comment by whedon** [comment]
OK. v2.2.1 is the version.

**Comment by cMadan** [comment]
@whedon set 10.5281/zenodo.3589990 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3589990" target="_blank">10.5281/zenodo.3589990</a> is the archive.

**Comment by cMadan** [comment]
@SwathiSheshadri, please revise the archive name in Zenodo to match the name of your submission.

**Comment by cMadan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/s41593-018-0209-y is OK
- 10.1038/s41596-019-0176-0 is OK
- 10.1109/CVPR.2016.90 is OK
- 10.1109/CVPR.2009.5206848 is OK
- 10.5281/zenodo.3364758 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by cMadan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01849/joss.01849/10.21105.joss.01849.pdf)

**Comment by SwathiSheshadri** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01849/joss.01849/10.21105.joss.01849.pdf)

**Comment by SwathiSheshadri** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01849/joss.01849/10.21105.joss.01849.pdf)

**Comment by SwathiSheshadri** [comment]
@cMadan, thank you for your quick response! I have updated the archive name in Zenodo to match the name of our JOSS paper. Also, I have proofread the PDF file and have updated the paper.md file to have improved formatting for PDF. During the process, I noticed that the link in the paper PDF file to the archive is broken, please help with fixing the same.

**Comment by cMadan** [comment]
@SwathiSheshadri, I'm not sure why that isn't working, but will look into it.

@openjournals/joss-eics, it looks like the archive link in the compiled PDF isn't working. Any ideas why (or how we might otherwise resolve this)?

**Comment by Kevin-Mattheus-Moerman** [comment]
@cMadan 
> @openjournals/joss-eics, it looks like the archive link in the compiled PDF isn't working. Any ideas why (or how we might otherwise resolve this)?

Those links should be fixed in the final accepted version. Some automatically generated links are not active in these proofs (all author generated links should work though).

**Comment by SwathiSheshadri** [comment]
@cMadan and @Kevin-Mattheus-Moerman, thank you for your quick responses! I have checked that the other links in the document are working fine.

**Comment by arfon** [comment]
> @openjournals/joss-eics, it looks like the archive link in the compiled PDF isn't working. Any ideas why (or how we might otherwise resolve this)?

Yeah, sorry about this. That's undocumented behaviour and very confusing...

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by arfon** [comment]
@cMadan - as an editor you are able to ask Whedon to make final proofs of the PDF with `@whedon accept` and these PDFs should have working links.

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/s41593-018-0209-y is OK
- 10.1038/s41596-019-0176-0 is OK
- 10.1109/CVPR.2016.90 is OK
- 10.1109/CVPR.2009.5206848 is OK
- 10.5281/zenodo.3364758 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1202

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1202, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@SwathiSheshadri  - please fix the cases (upper vs lower) in the bib entries - use {}s to protect cases where needed.

**Comment by danielskatz** [comment]
@cMadan - Other than the case issue in the bib, is this otherwise ready to accept?

**Comment by SwathiSheshadri** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01849/joss.01849/10.21105.joss.01849.pdf)

**Comment by SwathiSheshadri** [comment]
@danielskatz, thank you for your response and input on the case issue in the .bib file. It is now updated.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/s41593-018-0209-y is OK
- 10.1038/s41596-019-0176-0 is OK
- 10.1109/CVPR.2016.90 is OK
- 10.1109/CVPR.2009.5206848 is OK
- 10.5281/zenodo.3364758 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1207

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1207, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
👋 @arfon - note ref6 has the same incomplete URL problem...

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1214581451771072514) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1208
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01849](https://doi.org/10.21105/joss.01849)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @danasolav and @sreschechtko for reviewing!
And to @cMadan for editing!
And congratulations to @SwathiSheshadri and co-authors!

**Comment by danielskatz** [comment]
👋 @arfon - can you fix the XML (ref6), and then close this?

**Comment by arfon** [comment]
Fixed.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01849/status.svg)](https://doi.org/10.21105/joss.01849)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01849">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01849/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01849/status.svg
   :target: https://doi.org/10.21105/joss.01849
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01849/status.svg)](https://doi.org/10.21105/joss.01849)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
