### ISSUE TITLE
[REVIEW]: highlightHTML: CSS Formatting of R Markdown Documents

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#185]
**Submitting author:** @lebebr01 (<a href="http://orcid.org/0000-0002-1265-8761">Brandon LeBeau</a>)
**Repository:** <a href="https://github.com/lebebr01/highlightHTML" target ="_blank">https://github.com/lebebr01/highlightHTML</a>
**Version:** v 0.1.3
**Editor:** @acabunoc
**Reviewer:** @daattali
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1146049" target="_blank">10.5281/zenodo.1146049</a>

## Status

[![status](http://joss.theoj.org/papers/4283c3d8f17a8e7e465d6ef5f56f812a/status.svg)](http://joss.theoj.org/papers/4283c3d8f17a8e7e465d6ef5f56f812a)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/4283c3d8f17a8e7e465d6ef5f56f812a"><img src="http://joss.theoj.org/papers/4283c3d8f17a8e7e465d6ef5f56f812a/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/4283c3d8f17a8e7e465d6ef5f56f812a/status.svg)](http://joss.theoj.org/papers/4283c3d8f17a8e7e465d6ef5f56f812a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/lebebr01/highlightHTML" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lebebr01/highlightHTML">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v 0.1.3)?
- [x] **Authorship:** Has the submitting author (@lebebr01) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @desilinguist it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by desilinguist** [comment]
It would be really useful if there was some example included in the repository and in the README that made it easy to try out this package. `vignette(highlightHTML)` also doesn't show me how to use this. What does the `tags` argument take in the `highlight_html()` function? The README just says that it takes a "Vector of CSS code" which is not very helpful.

It'd be really helpful if a usage example can be added so I can continue the review. Thanks!

**Comment by lebebr01** [comment]
Thanks for the comments. I agree, the README could have been better. This has been updated to reflect three things, installation is focused more on the CRAN version. Secondly, an example has been pulled from the vignette to remove the vague line about the tags argument. Third, description about installing the vignettes from the development version was added as well.

A second note, there is a vignette for this package, but these may not install directly from the development version on GitHub. You can view it directly on GitHub here: https://github.com/lebebr01/highlightHTML/tree/master/vignettes

You could also install from GitHub passing the build_vignettes argument: `devtools::install_github('lebebr01/highlightHTML', build_vignettes = TRUE)`.

**Comment by arfon** [comment]
👋 @desilinguist - does @lebebr01's last comment help here?

**Comment by lebebr01** [comment]
@arfon and @desilinguist, I wanted to check in to see if there is any additional information I can provide to help with this? Are there still issues viewing the vignette or is the README example too simple to be helpful?

**Comment by desilinguist** [comment]
Sorry, I have been swamped with other things. LGTM 👍

**Comment by arfon** [comment]
> Sorry, I have been swamped with other things. LGTM 👍

@desilinguist - thanks for getting back to us on this. There is still a substantial number of unchecked items above. Would you be able to update the checklist?

**Comment by acabunoc** [comment]
Pinging @desilinguist, have you had time to go through the checklist?

Let me know if you're too busy and I can look for another reviewer 😄

**Comment by desilinguist** [comment]
I really haven't had the time. Please accept my sincere apologies. Given
what the rest of my year looks like, it might indeed be prudent to look for
another reviewer.

**Comment by lebebr01** [comment]
Thank you for your time @desilinguist. 

Related to another reviewer, I had suggested @daattali during the pre-review stage. Perhaps he would have availability and be willing now.

**Comment by daattali** [comment]
If you are having trouble finding a reviewer, I can be a reviewer

**Comment by acabunoc** [comment]
Thanks so much @daattali! I'll go ahead and assign you as reviewed -- really appreciate your help

**Comment by acabunoc** [comment]
@whedon assign @daattali as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @daattali

**Comment by daattali** [comment]
I haven't done a review in a couple years, I forget how they work. Where are the exact instructions?

**Comment by acabunoc** [comment]
@daattali here are the reviewer guideline: http://joss.theoj.org/about#reviewer_guidelines

But mostly, it's going through the checklist at the top of this issue.

Thanks again! 🎉 🎈 🍰

**Comment by daattali** [comment]
Review submitted https://github.com/lebebr01/highlightHTML/issues/5

**Comment by lebebr01** [comment]
Thank you, appreciate the review and thoughtful comments. I'll work through these and post a response/changes in the coming weeks.

**Comment by lebebr01** [comment]
Thanks again @daattali for the review. I posted my comments on edits made here: https://github.com/lebebr01/highlightHTML/issues/5. As mentioned in that issue, most of the changes I grouped into a single commit: https://github.com/lebebr01/highlightHTML/commit/fc1cf86e2aff8a14f986bf9c7520e313611dbc78.

I'd be very interested on your thoughts on the changes. Thanks again in advance.

**Comment by arfon** [comment]
@daattali - friendly reminder to take another look at this when you get a chance.

**Comment by daattali** [comment]
Hi, yes it's on my calendar and will be done after December :)

**Comment by daattali** [comment]
After revisions, the package LGTM

I left a few more small comments for the author to fix, but they are not blocking issues, I would accept the package now

**Comment by arfon** [comment]
@lebebr01 - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by lebebr01** [comment]
Great, thanks @arfon. I created an archive of the reviewed software in Zenodo: https://doi.org/10.5281/zenodo.1146049. 

Thank you for your assistance and let me know if you need anything further from me.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1146049 as archive.

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1146049" target="_blank">10.5281/zenodo.1146049</a> is the archive.

**Comment by arfon** [comment]
@daattali - many thanks for your review here and to @acabunoc for editing this submission ✨ 

@lebebr01 - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00185 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00185/status.svg)](https://doi.org/10.21105/joss.00185)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00185/status.svg)](https://doi.org/10.21105/joss.00185)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
