### ISSUE TITLE
[PRE REVIEW]: workloopR: Analysis of work loops and other data from muscle physiology experiments in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1851]
**Submitting author:** @vbaliga (<a href="http://orcid.org/0000-0002-9367-8974">Vikram B. Baliga</a>)
**Repository:** <a href="https://github.com/ropensci/workloopR/" target ="_blank">https://github.com/ropensci/workloopR/</a>
**Version:** v1.1.1
**Editor:** @danielskatz
**Reviewers:** @danielskatz

**Author instructions**

Thanks for submitting your paper to JOSS @vbaliga. **Currently, there isn't an JOSS editor assigned** to your paper.

@vbaliga if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01851/joss.01851/10.21105.joss.01851.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
Note: this package has been reviewed by rOpenSci: https://github.com/ropensci/software-review/issues/326

**Comment by vbaliga** [comment]
Hi @Kevin-Mattheus-Moerman - thank you for your help. I can confirm that this package has been reviewed by rOpenSci: https://github.com/ropensci/software-review/issues/326, @lmullen was the editor

I have just taken a look a the proof that whedon provided in https://github.com/openjournals/joss-reviews/issues/1851#issuecomment-548467135 . I am generally happy with how things look, but there is one mistake that I would like to fix: I neglected to list our sources of financial support in our Acknowledgments. 

I'd like to append the following information to the Acknowledgments: This work was funded by the U.S. Air Force Office of Scientific Research (under grant no. FA9550-16-1-0182, titled "Avian-inspired multifunctional morphing vehicles" monitored by B. L. Lee) and also by the Natural Sciences and Engineering Research Council of Canada (NSERC, RGPIN-2016-05381).

Do you have advice on the most efficient way to proceed? Should I update `paper.md`  in https://github.com/ropensci/workloopR  and create a new release to trigger Zenodo? Or is there another preferred way? Thanks!

**Comment by danielskatz** [comment]
Please go ahead and make the paper fix in the .md file.  If you want to change the version, that's fine - If you want to make a new archive of the software, that's fine too.

**Comment by vbaliga** [comment]
Hi @danielskatz - thank you for your advice. I went ahead and made the fix to the paper and [bumped the version](https://github.com/ropensci/workloopR/releases/tag/v1.1.1) to 1.1.1 . Our Zenodo archive ([https://doi.org/10.5281/zenodo.3523384](https://doi.org/10.5281/zenodo.3523384)) has also been updated, following the new version. 

I think our JOSS submission is now ready. Please let me know if there is any further action I should take. Thanks again

**Comment by vbaliga** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01851/joss.01851/10.21105.joss.01851.pdf)

**Comment by vbaliga** [comment]
> [ 👉 Check article proof 📄 👈 ](https://github.com/openjournals/joss-papers/blob/joss.01851/joss.01851/10.21105.joss.01851.pdf)

The proof generated here looks good to me

**Comment by danielskatz** [comment]
@whedon set v1.1.1 as version

**Comment by whedon** [comment]
OK. v1.1.1 is the version.

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3523384 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3523384" target="_blank">10.5281/zenodo.3523384</a> is the archive.

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @danielskatz

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1856. Feel free to close this issue now!
