### ISSUE TITLE
[PRE REVIEW]: hammurabi X: a C++ package for simulating Galactic emissions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1852]
**Submitting author:** @gioacchinowang (<a href="http://orcid.org/0000-0002-7384-7152">Jiaxin Wang</a>)
**Repository:** <a href="https://bitbucket.org/hammurabicode/hamx" target ="_blank">https://bitbucket.org/hammurabicode/hamx</a>
**Version:** v.2.3.0
**Editor:** @dfm
**Reviewers:** @zonca, @pqrs6

**Author instructions**

Thanks for submitting your paper to JOSS @gioacchinowang. **Currently, there isn't an JOSS editor assigned** to your paper.

@gioacchinowang if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1852 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev does the paper need to be moved to a `paper` folder?

**Comment by Kevin-Mattheus-Moerman** [comment]
@xuanxu @dfm @mbobra can one of you edit this submission? 

The paper does not render yet but is here: 
https://bitbucket.org/hammurabicode/hamx/src/master/joss/paper.md

**Comment by dfm** [comment]
@Kevin-Mattheus-Moerman: sure! I'm happy to take this.

@gioacchinowang: please take a look at [this list of potential reviewers](https://bit.ly/joss-reviewers) and let me know if there's anyone who you think would be an especially good fit.

**Comment by dfm** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by gioacchinowang** [comment]
@dfm Thanks for being my editor! 

I checked the potential reviewer list, 
in my opinion, 
reviewers with "C++/Python" as preferred and "astrophysics" fit my submission, 
so for example: 

adam-m-jcbs, 
ziotom78,  
williamjameshandley, 
andrewfowlie, 
harpolea, 
danehkar

Many thanks!

**Comment by dfm** [comment]
:wave: @zonca: Any chance you're available to review this submission?

**Comment by dfm** [comment]
:wave: @manodeep: Any chance you're available to review this submission?

**Comment by zonca** [comment]
@dfm yes, please, the project is really interesting and links directly to my work on foregrounds simulations for CMB.

**Comment by dfm** [comment]
@zonca Excellent - thanks!

**Comment by dfm** [comment]
@whedon assign @zonca as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @zonca

**Comment by dfm** [comment]
We still need a second reviewer, so @manodeep, let me know if you can. If not, I'll ask around some more!

**Comment by dfm** [comment]
:wave: @adam-m-jcbs: Any chance you're available to review this submission? I know that it is outside of your research area, but your input on the computational aspects would be much appreciated!

**Comment by dfm** [comment]
:wave: @mgckind: Any chance you're available to review this submission?

**Comment by mgckind** [comment]
@dfm , Thanks for the consideration, unfortunately, I'm a little tight in time between travels and I haven't even started a [pending JOSS review](https://github.com/openjournals/joss-reviews/issues/1881) so I'm going to pass on this one. Cheers

**Comment by dfm** [comment]
@mgckind: No worries. Thanks for the response!

@gioacchinowang: I see that there is [an ArXiv posting](https://arxiv.org/abs/1907.00207) describing this software that has been submitted to the AAS journals. Is this JOSS submission meant to be considered in parallel via [the JOSS/AAS collaboration](https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing)?

**Comment by gioacchinowang** [comment]
> @mgckind: No worries. Thanks for the response!
> 
> @gioacchinowang: I see that there is [an ArXiv posting](https://arxiv.org/abs/1907.00207) describing this software that has been submitted to the AAS journals. Is this JOSS submission meant to be considered in parallel via [the JOSS/AAS collaboration](https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing)?

@dfm 
Yes, it is. 
And we have received the first round reviewing report from ApJS, in which the editor suggested us to get the package reviewed by JOSS first before sending back the revised draft.

**Comment by dfm** [comment]
@gioacchinowang: ok - thanks!

@zonca: Please let me know if you're still willing to review this submission as a joint submission to AAS. Thanks!

**Comment by zonca** [comment]
Yes sure, thanks!

**Comment by dfm** [comment]
:wave: @Pqrs6: Any chance you're available to review this submission? It is a joint submission to [JOSS and AAS Journals](https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing), but this review will only focus on the software component.

**Comment by dfm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1852 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1852/joss/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon.rb:115:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by dfm** [comment]
@gioacchinowang: It looks like there are some syntax errors in your paper header (the indentation is important!). Can you take a stab at fixing that? You can use [this site](https://whedon.theoj.org/) to test the compiler.

**Comment by arfon** [comment]
/ cc @crawfordsm

**Comment by arfon** [comment]
@dfm - Once we have both of the reviewers identified for this submission please make them aware of the collaboration with AAS publishing, and that as part of this collaboration, AAS publishing makes a small donation to the running costs of JOSS. 

Some related links:

- Blog post describing the collaboration: https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing
- Summary of JOSS financial model: https://joss.theoj.org/about#costs

**Comment by pqrs6** [comment]
@dfm

Yes, I can review this, can do it in the next couple of days.

**Comment by dfm** [comment]
Awesome - thanks @pqrs6!

**Comment by dfm** [comment]
@whedon add @pqrs6 as reviewer

**Comment by whedon** [comment]
OK, @pqrs6 is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1889. Feel free to close this issue now!

**Comment by dfm** [comment]
@zonca, @pqrs6, and @gioacchinowang: The main review page will now be at #1889. Please head over there when you're ready to get started. Thanks all!
