### ISSUE TITLE
[PRE REVIEW]: ytree: A Python package for analyzing merger trees

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1853]
**Submitting author:** @brittonsmith (<a href="http://orcid.org/0000-0002-6804-630X">Britton Smith</a>)
**Repository:** <a href="https://github.com/ytree-project/ytree" target ="_blank">https://github.com/ytree-project/ytree</a>
**Version:** v2.2
**Editor:** @xuanxu
**Reviewers:** @mgckind, @aureliocarnero

**Author instructions**

Thanks for submitting your paper to JOSS @brittonsmith. **Currently, there isn't an JOSS editor assigned** to your paper.

@brittonsmith if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1853 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1853/paper/paper.md): could not find expected ':' while scanning a simple key at line 27 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon.rb:115:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@brittonsmith Your paper has compilation issues. Please study our guidelines and see if you can trouble shoot these issues. 
https://joss.readthedocs.io/en/latest/submitting.html#checking-that-your-paper-compiles

You can use this link to test the compilation of your paper: https://whedon.theoj.org/

**Comment by brittonsmith** [comment]
@Kevin-Mattheus-Moerman, thanks for the note. I think the problem is that the paper is in a subdirectory of the repo linked above. The paper can be found [here](https://github.com/ytree-project/ytree/tree/master/paper). I thought that was the url I gave in the submission form. In any case, if I use that url in the compilation tester, it tells me that paper compilation is complete, although I get a "Not Found" message when I click to download the preview. Can you tell me what action I should take now?

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev do you know what is going on here?

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1853 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1853/paper/paper.md): could not find expected ':' while scanning a simple key at line 27 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon.rb:115:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @brittonsmith - It looks the the line after the metadata containing ```---``` is missing - please add this line to the paper.md and issue ```@whedon generate pdf``` as a new comment here to try again

**Comment by brittonsmith** [comment]
Oh, thanks for catching that, @danielskatz!

**Comment by brittonsmith** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01853/joss.01853/10.21105.joss.01853.pdf)

**Comment by brittonsmith** [comment]
Ok, I think we're back on track. Thanks everyone for their help.

**Comment by danielskatz** [comment]
👋 @dfm or @xuanxu, would one of you be willing to edit this submission?

**Comment by dfm** [comment]
@danielskatz: I'd like to finish my first two before taking on another. Let me know if you can't get it sorted.

**Comment by xuanxu** [comment]
@danielskatz yes, I can take this

**Comment by xuanxu** [comment]
@whedon set @xuanxu as editor

**Comment by xuanxu** [comment]
@whedon assign @xuanxu as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by xuanxu** [comment]
:wave: @mgckind: Any chance you're available to review this submission?

**Comment by xuanxu** [comment]
:wave: @ceb8: would you be willing to review this paper? I think your knowledge of astronomy and Python makes you a great fit for this submission.

**Comment by xuanxu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1088/0067-0049/192/1/9 is OK
- 10.5281/zenodo.1174374 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.21105/joss.00809 is OK
- 10.1088/0004-637X/763/1/18 is OK
- 10.3847/1538-4357/aabe8f is OK
- 10.3847/1538-4357/ab378f is OK
- 10.1093/mnras/sty2103 is OK
- 10.1093/mnras/stz2507 is OK

MISSING DOIs

- https://doi.org/10.1002/1097-024x(200009)30:11<1203::aid-spe338>3.3.co;2-e may be missing for title: An open graph visualization system and its applications to software engineering

INVALID DOIs

- None
```

**Comment by mgckind** [comment]
>  @mgckind: Any chance you're available to review this submission?

Hi, I'm traveling this week but I might be able to review it next week if that's okay?

**Comment by xuanxu** [comment]
@mgckind it is totally OK, thanks! 
I'll assign you now and wait to have the second reviewer ready before starting the review issue.

**Comment by xuanxu** [comment]
@whedon add @mgckind as reviewer

**Comment by whedon** [comment]
OK, @mgckind is now a reviewer

**Comment by xuanxu** [comment]
:wave: @cmbiwer would you be willing to review this paper? I think your knowledge of astronomy and Python makes you a great fit for this submission.

**Comment by xuanxu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1088/0067-0049/192/1/9 is OK
- 10.5281/zenodo.1174374 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.21105/joss.00809 is OK
- 10.1002/1097-024X(200009)30:11<1203::AID-SPE338>3.0.CO;2-N is OK
- 10.1088/0004-637X/763/1/18 is OK
- 10.3847/1538-4357/aabe8f is OK
- 10.3847/1538-4357/ab378f is OK
- 10.1093/mnras/sty2103 is OK
- 10.1093/mnras/stz2507 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by brittonsmith** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01853/joss.01853/10.21105.joss.01853.pdf)

**Comment by xuanxu** [comment]
@whedon add @aureliocarnero as reviewer

**Comment by whedon** [comment]
OK, @aureliocarnero is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1881. Feel free to close this issue now!

**Comment by xuanxu** [comment]
@aureliocarnero, @mgckind please head over to #1881 where the review will take place.
