### ISSUE TITLE
[PRE REVIEW]: lightr: import spectral data and metadata in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1854]
**Submitting author:** @bisaloo (<a href="http://orcid.org/0000-0002-4094-1476">Hugo Gruson</a>)
**Repository:** <a href="https://www.github.com/ropensci/lightr" target ="_blank">https://www.github.com/ropensci/lightr</a>
**Version:** v0.1
**Editor:** @danielskatz
**Reviewers:** @danielskatz

**Author instructions**

Thanks for submitting your paper to JOSS @bisaloo. **Currently, there isn't an JOSS editor assigned** to your paper.

@bisaloo if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01854/joss.01854/10.21105.joss.01854.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
Note: This package has been peer-reviewed by rOpenSci (v. 0.1): https://github.com/ropensci/software-review/issues/267

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @danielskatz

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1857. Feel free to close this issue now!
