### ISSUE TITLE
[PRE REVIEW]: DynaGUI package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1855]
**Submitting author:** @benjaminbolling (<a href="http://orcid.org/0000-0002-6650-5365">Benjamin Edward Bolling</a>)
**Repository:** <a href="https://github.com/benjaminbolling/DynaGUI" target ="_blank">https://github.com/benjaminbolling/DynaGUI</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @benjaminbolling. **Currently, there isn't an JOSS editor assigned** to your paper.

@benjaminbolling if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1855 with the following error: 

 Error reading bibliography ./paper.bib (line 7, column 16):
unexpected "("
expecting letter, digit, white space, "#", "," or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by Kevin-Mattheus-Moerman** [comment]
@benjaminbolling please fix your paper compilation issues (https://joss.readthedocs.io/en/latest/submitting.html#checking-that-your-paper-compiles). 

Also, after briefly reviewing this submission it, despite being a useful package, may run the risk of falling under the "Minor ‘utility’ packages" category which JOSS does not accept. See our requirements here:  
https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements

To convince us otherwise please elaborate (in comments here and in your paper) on the research applications of this work and on the impacts it may have to scientific research.

**Comment by benjaminbolling** [comment]
Dear Kevin,

the software is used at MAX IV Laboratory by multiple groups, including the accelerator division for diagnostics purposes, the Operations Group during beam commissioning and operations, and also by non-scientific technical groups.

Purposes include the possibility of monitoring and analyzing any type of data as the advance tool, the 'DynaGUI NV’, has the possibility of separating waveforms into scalars. This way, e.g. the different modes of a stored beam in storage ring or other ring accelerators can be monitored. It can also be used to track the evolution of the beam profile over time. These are merely two examples of this fresh yet already well-used package at the MAX IV Laboratory. If you do not want to publish it despite me failing to understand which requirement it would not fulfill, I will withdraw and publish it in another scientific journal. Let me know of this ASAP.

Kind regards,
Benjamin Bolling

———————————————
M. Sc. Benjamin Bolling
+46 (0) 702714413
benjaminbolling@icloud.com
———————————————

**Comment by danielskatz** [comment]
@benjaminbolling - it is clear that this software is useful and is being used. The question for JOSS is whether it is being used in research. One additional question here is who you expect would cite this package/submission?

**Comment by danielskatz** [comment]
Also, I think https://github.com/benjaminbolling/DynaGUI/pull/1 should fix the problem compiling.  Please merge this and then add ```@whedon generate pdf``` as a new comment in this issue to retry.  Feel free to iterate if there are additional problems

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01855/joss.01855/10.21105.joss.01855.pdf)

**Comment by danielskatz** [comment]
It looks like the references are not cited in the .md file, so while the paper compiles, there are no references found to be needed to be included in the paper
