### ISSUE TITLE
[REVIEW]: workloopR: Analysis of work loops and other data from muscle physiology experiments in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1856]
**Submitting author:** @vbaliga (<a href="http://orcid.org/0000-0002-9367-8974">Vikram B. Baliga</a>)
**Repository:** <a href="https://github.com/ropensci/workloopR/" target ="_blank">https://github.com/ropensci/workloopR/</a>
**Version:** v1.1.1
**Editor:** @danielskatz
**Reviewer:** @danielskatz
**Archive:** <a href="https://doi.org/10.5281/zenodo.3523384" target="_blank">10.5281/zenodo.3523384</a>

## Status

[![status](https://joss.theoj.org/papers/f0eca1d99dde4e02b414e65271cc24ca/status.svg)](https://joss.theoj.org/papers/f0eca1d99dde4e02b414e65271cc24ca)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f0eca1d99dde4e02b414e65271cc24ca"><img src="https://joss.theoj.org/papers/f0eca1d99dde4e02b414e65271cc24ca/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f0eca1d99dde4e02b414e65271cc24ca/status.svg)](https://joss.theoj.org/papers/f0eca1d99dde4e02b414e65271cc24ca)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ropensci/workloopR/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@danielskatz, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ropensci/workloopR/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@vbaliga) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @danielskatz it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01856/joss.01856/10.21105.joss.01856.pdf)

**Comment by danielskatz** [comment]
Note: this package has been reviewed by rOpenSci: https://github.com/ropensci/software-review/issues/326

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3523384 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3523384" target="_blank">10.5281/zenodo.3523384</a> is the archive.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1242/jeb.062752 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1069

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1069, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon set v1.1.1 as version

**Comment by whedon** [comment]
OK. v1.1.1 is the version.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1242/jeb.062752 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1070

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1070, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
👋 @vbaliga - in the paper, can you please add commas after "e.g."s  so that they look like, e.g., this.)
Also, please fix the cases in the first reference - the first word doesn't need to all CAPS...

**Comment by vbaliga** [comment]
Hi @danielskatz - thanks for catching these. I pushed a new commit (https://github.com/ropensci/workloopR/commit/0fc4be098671cfd0fb2d3ab7f72480309cbc767e) that takes care of both the comma issue and the CAPS issue. I did not create a new release, so the one I made yesterday ([v1.1.1](https://github.com/ropensci/workloopR/releases/tag/v1.1.1)) is still the latest one in our Zenodo archive (https://doi.org/10.5281/zenodo.3523384), too. Please let me know if there's anything more I should do & thanks again for all your help

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1242/jeb.062752 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1075

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1075, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@vbaliga - one more small change is needed - the first reference title should have a "-" in the middle: "How muscles function - the work loop technique"

**Comment by vbaliga** [comment]
@danielskatz - OK no problem. I just pushed a commit (https://github.com/ropensci/workloopR/commit/632352453351bc86991242aa9cf79195341c2ba1) that replaced the dash. I think that should take care of the issue.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1242/jeb.062752 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1076

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1076, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01856/joss.01856/10.21105.joss.01856.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1242/jeb.062752 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1077

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1077, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by danielskatz** [comment]
👋 @vbaliga - thanks for doing the extra work to get this in JOSS!

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1190281821319258112) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1078
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01856](https://doi.org/10.21105/joss.01856)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01856/status.svg)](https://doi.org/10.21105/joss.01856)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01856">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01856/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01856/status.svg
   :target: https://doi.org/10.21105/joss.01856
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01856/status.svg)](https://doi.org/10.21105/joss.01856)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by vbaliga** [comment]
Hi @danielskatz,
Thank you sincerely for all your help! @shreeramsenthi and I both appreciate your patience in getting us through the extra steps and we are very happy to now be published in JOSS.
Best regards,
Vikram Baliga
