### ISSUE TITLE
[REVIEW]: lightr: import spectral data and metadata in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1857]
**Submitting author:** @bisaloo (<a href="http://orcid.org/0000-0002-4094-1476">Hugo Gruson</a>)
**Repository:** <a href="https://www.github.com/ropensci/lightr" target ="_blank">https://www.github.com/ropensci/lightr</a>
**Version:** v0.1
**Editor:** @danielskatz
**Reviewer:** @danielskatz
**Archive:** <a href="https://doi.org/10.5281/zenodo.3525016" target="_blank">10.5281/zenodo.3525016</a>

## Status

[![status](https://joss.theoj.org/papers/7f76d78642d3dc72ea9d8c2597ef0e27/status.svg)](https://joss.theoj.org/papers/7f76d78642d3dc72ea9d8c2597ef0e27)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7f76d78642d3dc72ea9d8c2597ef0e27"><img src="https://joss.theoj.org/papers/7f76d78642d3dc72ea9d8c2597ef0e27/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7f76d78642d3dc72ea9d8c2597ef0e27/status.svg)](https://joss.theoj.org/papers/7f76d78642d3dc72ea9d8c2597ef0e27)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://www.github.com/ropensci/lightr" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@danielskatz, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://www.github.com/ropensci/lightr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@bisaloo) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @danielskatz it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by danielskatz** [comment]
Note: This package has been peer-reviewed by rOpenSci (v. 0.1): https://github.com/ropensci/software-review/issues/267

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01857/joss.01857/10.21105.joss.01857.pdf)

**Comment by danielskatz** [comment]
@Bisaloo - Can you please merge https://github.com/ropensci/lightr/pull/8

Also, the text in the paper that says
> It is for example planned to become a dependency to the vision model package `pavo`.

was not possible for me to fully parse so that I could suggest a change.  What is the subject of this sentence? Can you suggest a rephrasing of this sentence?

**Comment by Bisaloo** [comment]
> `lightr` can serve as a basis for colour analysis R packages to deal with the
file import step (future versions of `pavo` for example will include `lightr` as a dependency). Most packages can indeed currently only read a limited variety of file formats.
Here is an example of a workflow where `lightr` is used to import the spectral data, which is then analysed with `pavo`:
> 
> ```
> library(lightr)
> specs <- lr_get_spec(where = "yourfolder", ext = "ProcSpec")
>
> library(pavo)
> plot(specs, col = spec2rgb(specs))
> ```

Does that make more sense?

**Comment by danielskatz** [comment]
yes.

Can you change 
> It is for example planned to become a dependency to the vision model package pavo.

to 
> Future versions of pavo, for example, will include lightr as a dependency.

**Comment by Bisaloo** [comment]
done in https://github.com/ropensci/lightr/commit/1a1abcc6326b35b3da531f4454d7e13ef19faee9

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by danielskatz** [comment]
@Bisaloo - can you please archive the software in a repository, e.g., Zenodo, figshare, and let me know the DOI of the deposit?

**Comment by Bisaloo** [comment]
Sorry for the delay. For some reason, I couldn't use GitHub integration feature on the rOpenSci repo so I mirrored it on my own account.

The DOI is 10.5281/zenodo.3525016

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3525016 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3525016" target="_blank">10.5281/zenodo.3525016</a> is the archive.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.visres.2008.06.018 is OK
- 10.1086/303160 is OK
- 10.1086/285711 is OK
- 10.1111/2041-210X.12069 is OK
- 10.1111/evo.12551 is OK
- 10.1073/pnas.0501891102 is OK
- 10.1111/2041-210X.13174 is OK
- 10.1093/biostatistics/kxp014 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1071

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1071, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1190265519468941312) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1072
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01857](https://doi.org/10.21105/joss.01857)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks @Bisaloo for submitting this to JOSS as well - it's all done now!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01857/status.svg)](https://doi.org/10.21105/joss.01857)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01857">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01857/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01857/status.svg
   :target: https://doi.org/10.21105/joss.01857
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01857/status.svg)](https://doi.org/10.21105/joss.01857)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by Bisaloo** [comment]
@danielskatz, sorry, I just realized (a couple of seconds too late) that the ORCID for Thomas White is wrong. Is there a way to update it?

The correct ORCID is 0000-0002-3976-1734

**Comment by danielskatz** [comment]
@bisaloo - please change the .md file to fix this, then let us know it is done
@arfon - can you then regenerate the PDF and metadata

**Comment by Bisaloo** [comment]
I already did it in https://github.com/ropensci/lightr/commit/e0e25a657357e64ce045afc45cc541e2ae3893ab.

Thanks!

**Comment by danielskatz** [comment]
@arfon, can you regenerate the PDF and metadata and replace the old versions in the various places?

**Comment by arfon** [comment]
> @arfon, can you regenerate the PDF and metadata and replace the old versions in the various places?

That sounds be updated now.

**Comment by danielskatz** [comment]
thanks!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01857/status.svg)](https://doi.org/10.21105/joss.01857)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01857">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01857/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01857/status.svg
   :target: https://doi.org/10.21105/joss.01857
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01857/status.svg)](https://doi.org/10.21105/joss.01857)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by Bisaloo** [comment]
Thanks a bunch for reviewing @danielskatz and to you both for fixing my mistakes!
