### ISSUE TITLE
[PRE REVIEW]: The DynaGUI package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1858]
**Submitting author:** @benjaminbolling (<a href="http://orcid.org/0000-0002-6650-5365">Benjamin Edward Bolling</a>)
**Repository:** <a href="https://github.com/benjaminbolling/DynaGUI" target ="_blank">https://github.com/benjaminbolling/DynaGUI</a>
**Version:** v1.0.0
**Editor:** @majensen
**Reviewers:** @Chilipp, @pythonpanda2

**Author instructions**

Thanks for submitting your paper to JOSS @benjaminbolling. **Currently, there isn't an JOSS editor assigned** to your paper.

@benjaminbolling if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01858/joss.01858/10.21105.joss.01858.pdf)

**Comment by danielskatz** [comment]
👋 @benjaminbolling - You also submitted https://github.com/openjournals/joss-reviews/issues/1855 - can you explain why there are 2 submissions?

**Comment by benjaminbolling** [comment]
Hi, 

About the 2 versions - I uploaded one and got errors due to not having properly filled out affiliations. So I withdrew the first version (I thought), fixed the issue and re-uploaded.

/Benjamin

**Comment by danielskatz** [comment]
ok, the other issue is still open but I will close it, and we can proceed here.

**Comment by danielskatz** [comment]
It looks like the references are not cited in the .md file, so while the paper compiles, there are no references found to be needed to be included in the paper.

**Comment by danielskatz** [comment]
It is clear that this software is useful and is being used. The question for JOSS is whether it is being used in research. One additional question here is who you expect would cite this package/submission?

**Comment by kyleniemeyer** [comment]
Hi @benjaminbolling, just wanted to follow up—can you respond to @danielskatz's last question?

**Comment by benjaminbolling** [comment]
Dear all, 

first of all - I am sorry for taking an awful lot of time to respond but I have began working at a new position and was full with work to do. 

I have now cited references in the .md file and slightly edited the text to do so.

The ones I would expect to cite this package or submission would be people working in control rooms at particle accelerators (perhaps other research or industrial facilities as well), including control room operators and physicists (such as accelerator physicists doing experiments with the accelerator itself and beamline scientists doing experiments on their side). The strength of this package is that it is open and dynamical. I intend to keep updating the package and will soon integrate the EPICS control system as well (after taking a course in EPICS programming in December).

Kind regards

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01858/joss.01858/10.21105.joss.01858.pdf)

**Comment by labarba** [comment]
@benjaminbolling — I am the Associate Editor in Chief on rotation this week. I've looked at your paper and your explanation above, and I ask for your patience, because this submission is unusual for JOSS and may be difficult to put through review.

It sounds like this is more of an infrastructure tool, used in conjunction with large-scale physics equipment. Even if this is clearly within the scope of scientific workflows, it's not the kind of research software that JOSS commonly publishes. For that reason, we don't have an editor in this topic, and we may have trouble identifying reviewers.

Please help us by looking over the reviewer list, and telling us if you think you identify any potential reviewers. Also, give us some clues about how a reviewer might go about checking the functionality of the software, without access to the instrumentation it is meant to work with.

**Comment by benjaminbolling** [comment]
I see, I will look through the reviewer list. The functionality of the software can be tested by selecting the so-called "Randomizer" control system, which I made for my own diagnostics/trials purposes when working from home and demonstration purposes as it only generates (not completely) random numerical values.

**Comment by benjaminbolling** [comment]
Dear all,

I wonder which reviewers have experience with Python and PyQt?

**Comment by majensen** [comment]
@whedon assign majensen as editor

**Comment by whedon** [comment]
OK, the editor is majensen

**Comment by majensen** [comment]
@benjaminbolling thanks for your submission. If you have thoughts about possible reviewers, please let me know in the thread. (They don't have to be on Github)

**Comment by majensen** [comment]
@andrewfowlie - would you be willing to review this paper for [JOSS](https://joss.theoj.org)? I appreciated your consideration!

**Comment by majensen** [comment]
@Chilipp, @alexpghayes - would either of you be able to review this paper for [JOSS](https://joss.theoj.org)? Please let me know on this thread -- thanks in advance!

**Comment by alexpghayes** [comment]
I don't think I have the expertise necessary to review this package.

**Comment by majensen** [comment]
@alexpghayes - no problem, thanks for the quick response

**Comment by andrewfowlie** [comment]
In general I'm very willing to review submissions to joss, but it's not my area of expertise either, so I cannot review it. I don't think I know anyone suitable so cannot offer an alternative either.

**Comment by Chilipp** [comment]
Thanks for asking @majensen! Unfortunately I am completely packed with work for December and beginning of January, so I won't be able to do a review until the 20th of January (approximately). But if this is okay for you, I am happy to review the software.

**Comment by majensen** [comment]
Thanks @andrewfowlie and @Chilipp - @Chilipp I get it! Are you ok if I add you as reviewer "in reserve", ie if I can find someone who is able to review sooner I let you off the hook?

**Comment by Chilipp** [comment]
Yes, sure @majensen. That's fine with me

**Comment by benjaminbolling** [comment]
Thank you for the replies and for the effort you put in to find a reviewer, and it is great that you have found someone who can review it. :)

**Comment by majensen** [comment]
@benjaminbolling no problem -- are you ok with the review pending till late Jan?

**Comment by majensen** [comment]
@whedon assign @Chilipp as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @Chilipp

**Comment by benjaminbolling** [comment]
I am fine with the review pending until January.

**Comment by majensen** [comment]
Hey @pythonpanda2 - might you be able to review this one?

**Comment by pythonpanda2** [comment]
@majensen 

This might be  out of my area of expertise.

**Comment by majensen** [comment]
@pythonpanda2  - much appreciated. My intuition (correct me if I'm wrong @benjaminbolling ) is this work addresses a need for a UI in a highly specialized field -- which makes it cool IMO and suitable for the journal-- and it's really the UI functionality and the packaging that would take up the bulk of the review. The package has a "dummy backend" (Randomizer - see [comment above](https://github.com/openjournals/joss-reviews/issues/1858#issuecomment-555366639)), which I think will really aid the review, as @benjaminbolling points out.

@benjaminbolling if you can scare up a colleague with knowledge of the backend instruments who would be willing to comment in the review, that would be great, but it's not a show stopper AFAIC at this stage.

**Comment by majensen** [comment]
(@benjaminbolling -- I see you asked a question about reviewers with Qt experience. I have some passing familiarity with it; if we need some hardcore expertise, I'm confident we can find it.)

**Comment by majensen** [comment]
@whedon add @pythonpanda2 as reviewer

**Comment by whedon** [comment]
OK, @pythonpanda2 is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1942. Feel free to close this issue now!

**Comment by majensen** [comment]
All - our trusty bot has begun the review issue at #1942 ; please join the conversation there.
