### ISSUE TITLE
[PRE REVIEW]: NeuroDiffEq: A Python package for solving differential equations with neural networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1859]
**Submitting author:** @feiyu-chen96 (<a href="http://orcid.org/0000-0002-0476-9998">Feiyu Chen</a>)
**Repository:** <a href="https://github.com/odegym/neurodiffeq" target ="_blank">https://github.com/odegym/neurodiffeq</a>
**Version:** 1.0.0
**Editor:** @drvinceknight
**Reviewers:** @dawbarton, @marcharper

**Author instructions**

Thanks for submitting your paper to JOSS @feiyu-chen96. **Currently, there isn't an JOSS editor assigned** to your paper.

@feiyu-chen96 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1859 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01859/joss.01859/10.21105.joss.01859.pdf)

**Comment by danielskatz** [comment]
👋 @feiyu-chen96 - this paper may be a bit too long - see https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain
Please consider shortening it by moving some of the content to the software documentation.

**Comment by danielskatz** [comment]
Also, I note that some of the citations to references are missing spaces before them.  And most of the references are missing DOIs

**Comment by danielskatz** [comment]
👋 @drvinceknight - would you be willing to edit this submission?

**Comment by drvinceknight** [comment]
Yup, sounds like an interesting piece of software.

**Comment by drvinceknight** [comment]
@whedon assign @drvinceknight as editor

**Comment by whedon** [comment]
OK, the editor is @drvinceknight

**Comment by feiyu-chen96** [comment]
Hi @drvinceknight  Can I ask if there is a page limit? I'm thinking of keeping only the Summary section and move the rest to the documentation.

**Comment by drvinceknight** [comment]
@feiyu-chen96 there are is no specific page limit but in general papers are short (around 2 or 3 pages long). There is some documentation here about what to include in the paper as well as links to accepted papers: https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

**Comment by feiyu-chen96** [comment]
@whedon  generate pdf

**Comment by feiyu-chen96** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01859/joss.01859/10.21105.joss.01859.pdf)

**Comment by feiyu-chen96** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01859/joss.01859/10.21105.joss.01859.pdf)

**Comment by feiyu-chen96** [comment]
@drvinceknight I just shorten the paper and added DOI and space for citations. Could you check the updated version?

**Comment by drvinceknight** [comment]
Thanks @feiyu-chen96, I think this looks more like a JOSS paper now. I will start looking to assign reviewers. On that note do you have any you might suggest?

**Comment by feiyu-chen96** [comment]
@drvinceknight I looked through the list and no one particular stood out. I suppose anyone who works with Python and differential equations would be suitable. Thanks!

**Comment by drvinceknight** [comment]
@arghdos, @ysimillides, @Jgoldfar would you be able to able to review this paper for JOSS? There is information about what that involves here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html and I'm happy to answer any questions you may have.

**Comment by jgoldfar** [comment]
I will have time to review more effectively next January; please keep me in mind at that time!

**Comment by drvinceknight** [comment]
@lheagy @dawbarton mancellin would you be able to review this paper for JOSS? Your specified areas of interest include differential equations which this is a tool for so hopefully you'll find it interesting. It implements solving differential equations using neural networks.

If you haven't reviewed for JOSS before, there is information about what that involves here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html and I'm super happy to answer any questions you may have.

**Comment by dawbarton** [comment]
Yes, I can do a review. It'll be about 2 weeks before I can get to it though.

**Comment by drvinceknight** [comment]
No problem, thanks @dawbarton :+1:

**Comment by drvinceknight** [comment]
@whedon assign @dawbarton as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dawbarton

**Comment by drvinceknight** [comment]
@marcharper this is the paper I mentioned on email, would you be interested in reviewing it?

If you haven't reviewed for JOSS before, there is information about what that involves here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html and I'm super happy to answer any questions you may have.

**Comment by marcharper** [comment]
Yes, I can review. It may be a couple of weeks before I can do so, but I should be able to complete a review by ~EoY.

**Comment by drvinceknight** [comment]
Thanks @marcharper that's great.

**Comment by drvinceknight** [comment]
@whedon add @marcharper as reviewer

**Comment by whedon** [comment]
OK, @marcharper is now a reviewer

**Comment by drvinceknight** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1931. Feel free to close this issue now!

**Comment by drvinceknight** [comment]
#1931 is where the review will take place, let me know if there's anything I can assist with. Thank you again @marcharper and @dawbarton for your time and effort.
