### ISSUE TITLE
[PRE REVIEW]: MSMExplorer: Data Visualizations for Biomolecular Dynamics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#186]
**Submitting author:** @cxhernandez (<a href="http://orcid.org/0000-0002-8146-5904">Carlos Xavier Hernández</a>)
**Repository:** <a href="https://github.com/msmexplorer/msmexplorer" target ="_blank">https://github.com/msmexplorer/msmexplorer</a>
**Version:** v1.0.0
**Editor:** @arokem
**Reviewer:** @anotherjoshsmith

**What this issue is for**

Thanks for submitting your paper to JOSS @cxhernandez. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @arokem - would you be willing to edit this submission for JOSS?

**Comment by danielskatz** [comment]
If @arokem doesn't want it, I would be happy to take it.

**Comment by arokem** [comment]
Actually, I'd be happy to edit this! And I have a potential reviewer in mind...

@anotherjoshsmith, would you like to review this paper for JOSS (see: http://joss.theoj.org/about#reviewer_guidelines)?

**Comment by arfon** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by anotherjoshsmith** [comment]
Sounds like an exciting tool. @arokem I'd be happy to review.

**Comment by arokem** [comment]
@whedon assign @anotherjoshsmith as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @anotherjoshsmith

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/188. Feel free to close this issue now!

**Comment by arfon** [comment]
@arokem @anotherjoshsmith please head over to #188 to actually carry out the review.
