### ISSUE TITLE
[PRE REVIEW]: cdcam: Cambridge Digital Communications Assessment Model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1860]
**Submitting author:** @tomalrussell (<a href="http://orcid.org/0000-0002-0081-400X">Tom Russell</a>)
**Repository:** <a href="https://github.com/nismod/cdcam" target ="_blank">https://github.com/nismod/cdcam</a>
**Version:** v1.0.0
**Editor:** @melissawm
**Reviewers:** @nmstreethran, @potterzot

**Author instructions**

Thanks for submitting your paper to JOSS @tomalrussell. **Currently, there isn't an JOSS editor assigned** to your paper.

@tomalrussell if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01860/joss.01860/10.21105.joss.01860.pdf)

**Comment by danielskatz** [comment]
@melissawm - would you be willing to edit this submission?

**Comment by melissawm** [comment]
Sure, I can do it.

**Comment by danielskatz** [comment]
Thanks - the next step is for me to assign you, but note that you could also do this yourself :)

**Comment by danielskatz** [comment]
@whedon assign @melissawm as editor

**Comment by whedon** [comment]
OK, the editor is @melissawm

**Comment by melissawm** [comment]
@whedon assign @melissawm as editor

**Comment by whedon** [comment]
OK, the editor is @melissawm

**Comment by tomalrussell** [comment]
Hi all - thanks for the speedy first steps.

Mentioning @edwardoughton to pull them into this issue for reference.

Out of curiosity - 

@whedon commands

**Comment by danielskatz** [comment]
You have to do that (```@whedon commands```) in a new comment, by itself in the comment

**Comment by melissawm** [comment]
@aaronyd, would you be willing to review this software paper for JOSS? Thank you!

**Comment by melissawm** [comment]
@rickecon, would you be willing to review this software paper for JOSS? Thank you!

**Comment by melissawm** [comment]
Hello @tomalrussell , do you have suggestions for reviewers for your paper?

**Comment by tomalrussell** [comment]
Just looking through the JOSS reviewers list - perhaps @potterzot or @nmstreethran would be interested and available?

**Comment by nmstreethran** [comment]
Hello @tomalrussell, I would be happy to review your paper.

**Comment by potterzot** [comment]
@tomalrussell I would also be happy to review your paper, thanks!

**Comment by tomalrussell** [comment]
Thanks both! I think it's over to @melissawm :)

**Comment by melissawm** [comment]
Thank you both for responding! 

I'll move this over to the review issue then.

**Comment by melissawm** [comment]
@whedon assign @nmstreethran as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nmstreethran

**Comment by melissawm** [comment]
@whedon add @potterzot as reviewer

**Comment by whedon** [comment]
OK, @potterzot is now a reviewer

**Comment by melissawm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1911. Feel free to close this issue now!
