### ISSUE TITLE
[PRE REVIEW]: univariateML: An R package for maximum likelihood estimation of univariate densities

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1861]
**Submitting author:** @JonasMoss (<a href="http://orcid.org/0000-0002-6876-6964">Jonas Moss</a>)
**Repository:** <a href="https://github.com/JonasMoss/univariateML" target ="_blank">https://github.com/JonasMoss/univariateML</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewers:** @MaaniBeigy, @vbaliga

**Author instructions**

Thanks for submitting your paper to JOSS @JonasMoss. **Currently, there isn't an JOSS editor assigned** to your paper.

@JonasMoss if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01861/joss.01861/10.21105.joss.01861.pdf)

**Comment by danielskatz** [comment]
:wave: @karthik - would you be willing to edit this submission?

**Comment by karthik** [comment]
Sorry, I don't have bandwidth to handle new submissions at this time. 😢

**Comment by arfon** [comment]
:wave: @danielskatz - I can take this.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @JonasMoss - thanks for your submission to JOSS. Could you take a look at [this list of people](https://bit.ly/joss-reviewers) who have volunteered to review for JOSS and see if there are any good candidates?

**Comment by JonasMoss** [comment]
Hi @arfon! I would like to nominate @vbaliga and @MaaniBeigy!

**Comment by arfon** [comment]
@vbaliga and @MaaniBeigy - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by MaaniBeigy** [comment]
Yes, I am interested.

**Comment by arfon** [comment]
@whedon add @MaaniBeigy as reviewer

**Comment by whedon** [comment]
OK, @MaaniBeigy is now a reviewer

**Comment by arfon** [comment]
> Yes, I am interested.

Excellent, thanks @MaaniBeigy - I won't start the review until I've found a second review so for now, please just sit tight.

**Comment by vbaliga** [comment]
Hi @arfon and @JonasMoss - I am willing but I should mention that the next week or so is looking pretty busy. I don't see info in the JOSS guidelines about how long a window reviewers are given to return feedback. Would completing my review closer to mid- or end-November be OK? If you'd like to process this in a more timely manner, I won't be offended if you'd rather ask someone else.

**Comment by arfon** [comment]
@vbaliga mid-end of November would be great. I'll add you as a review now...

**Comment by arfon** [comment]
@whedon add @vbaliga as reviewer

**Comment by whedon** [comment]
OK, @vbaliga is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1863. Feel free to close this issue now!

**Comment by arfon** [comment]
@MaaniBeigy, @vbaliga, @JonasMoss - see you over in #1863 for the actual review.
