### ISSUE TITLE
[REVIEW]: Miet: an R package for region of interest analysis from magnetic reasonance images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1862]
**Submitting author:** @benoit-combes (<a href="http://orcid.org/0000-0003-4161-7093">Benoit Combès</a>)
**Repository:** <a href="https://gitlab.inria.fr/miet/miet" target ="_blank">https://gitlab.inria.fr/miet/miet</a>
**Version:** v0.2
**Editor:** @arokem
**Reviewer:** @janfreyberg, @neuroimaginador
**Archive:** <a href="https://doi.org/10.5281/zenodo.3626693" target="_blank">10.5281/zenodo.3626693</a>

## Status

[![status](https://joss.theoj.org/papers/812bd13a18e338ef53c6760c32e6216c/status.svg)](https://joss.theoj.org/papers/812bd13a18e338ef53c6760c32e6216c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/812bd13a18e338ef53c6760c32e6216c"><img src="https://joss.theoj.org/papers/812bd13a18e338ef53c6760c32e6216c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/812bd13a18e338ef53c6760c32e6216c/status.svg)](https://joss.theoj.org/papers/812bd13a18e338ef53c6760c32e6216c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://gitlab.inria.fr/miet/miet" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@janfreyberg & @neuroimaginador, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.inria.fr/miet/miet">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@benoit-combes) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.inria.fr/miet/miet">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@benoit-combes) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @janfreyberg, @neuroimaginador it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@arokem can you check progress here?

**Comment by arokem** [comment]
@janfreyberg : I see that you've checked off a couple of items. Any progress on the other items?

@neuroimaginador : have you had a chance to take a look?

**Comment by janfreyberg** [comment]
Hi @arokem - apologies for the delay! I've been away with work.

I've ticked the bits I was able to verify and will raise a few issues on their repo now.

**Comment by benoit-combes** [comment]
@janfreyberg @neuroimaginador. Thanks for accepted to review my work and for your first inputs. If I can do anything that may help you in the reviewing process, please let me know.

**Comment by benoit-combes** [comment]
@janfreyberg @neuroimaginador. Dear reviewers, I just realized that a directory was missing from the miet repository. This lack simply causes the function documentation not to be available using the base package installation procedure. I corrected this lack by adding the missing directory so that the doc is not available using the regular "?" command. I hope this lack did not disturb too much your work. If I can do anything that may help you in the reviewing process, please let me know.

**Comment by janfreyberg** [comment]
Thanks @benoit-combes - I've left a few comments about the documentation. I think aside from a fix / answer to the issues on your gitlab issue, I didn't feel able to tick off "state of the field" - would you be able to add this to the paper, even if it's just "Currently you have to read array data manually and program all the table creations yourself" or something along those lines.

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by benoit-combes** [comment]
@janfreyberg. Thanks for all these valuable points. I tried to address them with my last pushes. Concerning the point you raised in your comment, I added to the joss paper (end of section 1):

"Such an analysis needs to iterate over all MR volumes to read them and to
extract the relevant statistics. To the best of our knowledge, there is no
dedicated framework to ease such tasks, which may result in lengthy technical
analysis codes. Miet (acronym of medical imaging extraction tools) is an R
package attempting to fill that gap. More specifically, miet is designed to
specify and extract tibbles (which is an improved data.frame structure
@Tibble:2019) ready for data analysis from a specified folder hierarchy and a
set of extraction formulas."

I commented my fixes for each of the other points in the issues you raised on gitlab. 

I hope everythink is correct to you, if for any reason it is not please let me know. 

Thanks again for your inputs.

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by janfreyberg** [comment]
Great, thanks. This addresses all my concerns.

**Comment by benoit-combes** [comment]
Dear @arokem, may I ask you whether you get supplemental information about @neuroimaginador availability to review the work ? Thanks in advance.

**Comment by arokem** [comment]
Sorry about the delay here. Let me try to track this reviewer done, as they have not responded here.

**Comment by neuroimaginador** [comment]
Sorry about the delay, @arokem  and @benoit-combes , I'm now reviewing the paper and the package. Just opened an issue regarding a potential enhancement by using a "testthat" folder structure as described in http://r-pkgs.had.co.nz/tests.html, which is a standard and completely automated way of testing, and required by CRAN submissions.

**Comment by neuroimaginador** [comment]
Thank you, @benoit-combes for addressing my issues, I'm more than satisfied with this package, since it may be very useful to get people from neuroimaging into R. I have already closed all my issues. Thanks.

**Comment by benoit-combes** [comment]
@neuroimaginador. Thanks for this relevant suggestion. I modified the testing strategy following your suggestion. I hope everythink is now ok to you, if for any reason it is not the case, please let me know.

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by benoit-combes** [comment]
Dear @arokem, I read again the paper and fixed a few grammar/spelling mistakes and ambiguous wordings. If I can do anything that may help you in the editing process, please let me know.

**Comment by arokem** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1148/radiographics.14.2.8190954 may be missing for title: Magnetization transfer: theory and clinical applications in neuroradiology.

INVALID DOIs

- None
```

**Comment by arokem** [comment]
In addition to adding the missing DOI for this reference, I have added some proposed edits in a patch attached to https://gitlab.inria.fr/miet/miet/issues/9

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by benoit-combes** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1148/radiographics.14.2.8190954 may be missing for title: Magnetization transfer: theory and clinical applications in neuroradiology.

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by benoit-combes** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1148/radiographics.14.2.8190954 may be missing for title: Magnetization transfer: theory and clinical applications in neuroradiology.

INVALID DOIs

- None
```

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by benoit-combes** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- https://pubs.rsna.org/doi/10.1148/radiographics.14.2.8190954 is INVALID because of 'https://doi.org/' prefix
```

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by benoit-combes** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1148/radiographics.14.2.8190954 is INVALID because of 'https://doi.org/' prefix
```

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by benoit-combes** [comment]
@whedon check reference

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by benoit-combes** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1148/radiographics.14.2.8190954 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by benoit-combes** [comment]
Dear @arokem. 

Thanks for your responsiveness and for these nice suggestions, I added all of them, expect the one consisting in capitalizing "miet" as "Miet". In the last version, I used "Miet" to start a new sentence (and title), but it seems to me that this is actually not the conventional practice and that this may have motivated your suggestion. In the revised version I proposed to use "miet" everywhere ;  I looked at standard R package e.g. dplyr and they seem to follow this rule. Do you feel confortable with this choice ?

I also added the doi as suggested.Thanks,
B.

**Comment by arokem** [comment]
Yes - that sounds fine to me! With these changes, I believe that your submissions is ready for final review by the editors in chief. Before we proceed to this step, could you please do the following:

- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g. figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

We can then move forward with accepting the submission.

**Comment by benoit-combes** [comment]
Thanks for these detailed steps. So here is :
* is the tagged release of miet : https://gitlab.inria.fr/miet/miet/-/tags/v0.2
* the associated Zenodo archival deposit: https://doi.org/10.5281/zenodo.3626693

If I am correct, this fills the 4 steps detailed above, if it is not the case, please let me know.

Moreover, the paper title has changed from "**M**iet: an R package for region of interest analysis from magnetic reasonance images" to "**m**iet: an R package for region of interest analysis from magnetic reasonance images", maybe there is some metadata related to my submission to change ?

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.3626693 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3626693" target="_blank">10.5281/zenodo.3626693</a> is the archive.

**Comment by arokem** [comment]
@openjournals/joss-eics : I believe this is ready for your final review.

In particular, not submitter's question [above](https://github.com/openjournals/joss-reviews/issues/1862#issuecomment-578053546): 

> [...], the paper title has changed from "Miet: an R package for region of interest analysis from magnetic reasonance images" to "miet: an R package for region of interest analysis from magnetic reasonance images", maybe there is some metadata related to my submission to change ?

Does it?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by arfon** [comment]
@arokem @benoit-combes - the PDF has the correct title so I think this should be fine (i.e. no additional changes are necessary).

**Comment by labarba** [comment]
@whedon set v0.2 as version

**Comment by whedon** [comment]
OK. v0.2 is the version.

**Comment by labarba** [comment]
@benoit-combes — Your last reference is missing its DOI. I found it is [10.1093/scan/nsm006](https://doi.org/10.1093/scan/nsm006).

Would you consider formatting the software title with code font? It looks a bit odd to see the word miet in the text with normal font, so I'm suggesting using `miet`. What do you think?

In a couple of places, you have a reference inside a parenthetical, resulting in two sequential brackets, like this "))" — if you care to tweak a bit, that could be avoided. (Just a small style thing.)

And you have a "colmun" instead of "column" in there. Have a look!

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by benoit-combes** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1148/radiographics.14.2.8190954 is OK
- 10.1093/scan/nsm006 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by benoit-combes** [comment]
Dear @labarba,

thanks for your inputs. I generated a new article proof where:

* I added the mission DOI. 
*  I changed the title according to your suggestion ; I fully agree your feeling about the original verion.
* I rephrased the references to avoid the "))" sequences.
* I corrected the "colmun" typo.

If I can do anything that may help you in the editing process, please let me know.

**Comment by labarba** [comment]
Oops. Now you've left citations appearing in the sentences without any brackets at all. Have a look at the [Citation Syntax](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax) guidelines we like to apply. When the citation is part of the sentence, it appears as: Author (year). If the citation is not part of the sentence, then it appears in parenthesis. E.g. “We take inspiration from Smith et al. (2006) to do blah “ /  "The code implements Theory 1 (Jones 2012) and Theory 2 (Roberts 2014) to obtain … “ 

My original comment was for instances where you had a citation inside a parenthetical comment in the text. You can sometimes replace the parentheses by em-dashes. Or you can make some other adjustment.

Sorry that my suggestion led you astray. 

Could you change to code-font for "miet" *inside* the text? For example, at the start of the section with heading "A short example."

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01862/joss.01862/10.21105.joss.01862.pdf)

**Comment by benoit-combes** [comment]
Thanks @labarba. It seems, that for any reason, I indeed missed the correct syntax for citation. Sorry for that. I hope that the newly generated version now follows the standard.

Moreover, as suggested I "codify" each instance of miet in the text. 

If I can do anything that may help you in the editing process, please let me know.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1148/radiographics.14.2.8190954 is OK
- 10.1093/scan/nsm006 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1252

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1252, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1221830340563685376) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1253
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01862](https://doi.org/10.21105/joss.01862)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @benoit-combes, your JOSS paper is published! 🚀 

Huge thanks to our editor: @arokem, and the reviewers: @janfreyberg, @neuroimaginador — your contributions to JOSS are invaluable 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01862/status.svg)](https://doi.org/10.21105/joss.01862)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01862">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01862/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01862/status.svg
   :target: https://doi.org/10.21105/joss.01862
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01862/status.svg)](https://doi.org/10.21105/joss.01862)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by benoit-combes** [comment]
@whedon generate pdf

**Comment by labarba** [comment]
Please explain the situation here, and point to the correction you want made. The paper is already published so any corrections need to be made _by hand_.

Ping @openjournals/dev

**Comment by benoit-combes** [comment]
Dear @labarba,
I changed the "paper.md" in the gitlab repository. Is it possible to regenerate the final proof ?
Thanks for your consideration.
B.

**Comment by benoit-combes** [comment]
Dear @labarba,
I would like to remove the age and sex colmuns in the data. These data are not needed for the paper/analysis and should be avoided in the paper. If I can do anything to help you in the process please let me know.
Thanks in advance for your patience and consideration,
B.

**Comment by benoit-combes** [comment]
Dear @labarba,

I added more information to my last message. Do you think it is sufficient to apply the correction ? If not please, let me know.

Thanks in advance for your consideration,
B.

**Comment by labarba** [comment]
The EiC (@arfon) can help you with a post-publication correction. This is a manual process.

**Comment by arfon** [comment]
This is now updated. It may take a few hours to show up differently on the JOSS site due to caching.

**Comment by benoit-combes** [comment]
Dear Joss Editor @labarba @arfon,

thanks a lot for having considered my request quickly and gently. I am now very happy of the paper and greatly appreciated my experience as an author.

B.
