### ISSUE TITLE
[REVIEW]: Economiccomplexity: Methods Used in the Economic Complexity Literature

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1866]
**Submitting author:** @pachamaltese (<a href="http://orcid.org/0000-0003-1017-7574">Mauricio Vargas</a>)
**Repository:** <a href="https://github.com/pachamaltese/economiccomplexity" target ="_blank">https://github.com/pachamaltese/economiccomplexity</a>
**Version:** 0.2.1
**Editor:** @oliviaguest
**Reviewers:** @JohnCoene, @mpadge
**Archive:** <a href="https://doi.org/10.5281/zenodo.3671843" target="_blank">10.5281/zenodo.3671843</a>

## Status

[![status](https://joss.theoj.org/papers/8668c7ef700bd3f88fd1930fa9092326/status.svg)](https://joss.theoj.org/papers/8668c7ef700bd3f88fd1930fa9092326)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8668c7ef700bd3f88fd1930fa9092326"><img src="https://joss.theoj.org/papers/8668c7ef700bd3f88fd1930fa9092326/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8668c7ef700bd3f88fd1930fa9092326/status.svg)](https://joss.theoj.org/papers/8668c7ef700bd3f88fd1930fa9092326)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pachamaltese/economiccomplexity" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mpadge & @JohnCoene, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @oliviaguest know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pachamaltese/economiccomplexity">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@pachamaltese) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [NA] **State of the field:** Do the authors describe how this software compares to other commonly-used packages? -- there seems to be no other comparable software
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)? - the writing could perhaps do with one final, minor edit
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pachamaltese/economiccomplexity">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@pachamaltese) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @rickecon, @JohnCoene it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01866/joss.01866/10.21105.joss.01866.pdf)

**Comment by oliviaguest** [comment]
👋 @rickecon, @JohnCoene this is where the reviewing itself happens. Also feel free if you have specific code-related issues to open them in the code repo itself. Thank you again! 😊

**Comment by oliviaguest** [comment]
@rickecon, @JohnCoene — when do you think you will have time to check this?

**Comment by JohnCoene** [comment]
@oliviaguest I have already started and submitted an [issue on the repository](https://github.com/pachamaltese/economiccomplexity/issues/8) itself, will finish review by end of week.

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by pachamaltese** [comment]
yes, I'm improving the documentation after those initial comments

**Comment by oliviaguest** [comment]
@pachamaltese excellent!

@rickecon what's a realistic ETA here? :smile:

**Comment by pachamaltese** [comment]
Hi
I pushed changes to the documentation as John asked.

**Comment by oliviaguest** [comment]
@pachamaltese perfect, thanks. Hopefully @rickecon can give us a realistic time-frame for his feedback too. I'll drop him an email now.

**Comment by JohnCoene** [comment]
Hi @oliviaguest apologies for the delay, I've been in touch with @pachamaltese but I've been a bit ill these past few days. I will find the time to finish the review this week.

**Comment by oliviaguest** [comment]
@JohnCoene thank you and most importantly: get well soon! :smiley_cat:

**Comment by pachamaltese** [comment]
Hi
Just to inform that I rewrote all functions toward easier use and speed

**Comment by oliviaguest** [comment]
@JohnCoene let us know when you check this out.

@pachamaltese thank you for the update!

**Comment by oliviaguest** [comment]
@whedon remove @rickecon  as reviewer

**Comment by whedon** [comment]
OK, @rickecon  is no longer a reviewer

**Comment by oliviaguest** [comment]
I have been struggling for a while (4 months an counting) to find reviewers for this, @pachamaltese. Is there any way you could help me out? I have emailed every person suggested so far. So please feel free to reach out to people yourself — perhaps they will be more responsive?

**Comment by pachamaltese** [comment]
Sure! I'll ask more people

**Comment by oliviaguest** [comment]
@pachamaltese any luck?

**Comment by pachamaltese** [comment]
@oliviaguest I'm just back from RStudio Conf. Let me ask on that Slack :)

**Comment by oliviaguest** [comment]
Oh, welcome back @pachamaltese and fantastic! :100:

**Comment by pachamaltese** [comment]
@oliviaguest hi, maybe @ppssphysics and @mpadge

**Comment by oliviaguest** [comment]
@pachamaltese amazing!

@ppssphysics and/or @juanrocha: would you be interested in reviewing this?

**Comment by pachamaltese** [comment]
Dr. @oliviaguest I just spoke to Dr. @mpadge and he would like to review
this R package. Great news!

**Comment by oliviaguest** [comment]
@whedon add @mpadge as reviewer

**Comment by whedon** [comment]
OK, @mpadge is now a reviewer

**Comment by oliviaguest** [comment]
👋 Hi @mpadge! Please scroll up and take a look at the section: 
> Review checklist for @mpadge

Thank you for coming on board and let us know how long you think this review will take you to complete. 😄

**Comment by mpadge** [comment]
Thanks @oliviaguest, it'll be a pleasure to review this exciting looking package. I'll try to get it done this week (<= 7 Feb 2020); if not I'll commit myself now to ensuring it's done by end of the week after (<= 14 Feb 2020). I trust that's okay

**Comment by oliviaguest** [comment]
Fantastic! I'll set a reminder in 10 days then @mpadge. :relaxed:

**Comment by oliviaguest** [comment]
@whedon remind @mpadge in 10 days

**Comment by whedon** [comment]
Reminder set for @mpadge in 10 days

**Comment by mpadge** [comment]
Thanks @whedon

**Comment by mpadge** [comment]
... I just wanted to see if whedon responded to expressions of gratitude, but clearly not. Clear case for a PR there ...

**Comment by oliviaguest** [comment]
I do! :laughing:

**Comment by whedon** [comment]
:wave: @mpadge, please update us on how your review is going.

**Comment by mpadge** [comment]
just done. All good to go, except for one (very) minor comment i made regarding the `paper.md`, which could perhaps be improved prior to official publication by one final edit.

**Comment by oliviaguest** [comment]
@JohnCoene is the missing tick in your review being addressed?

@mpadge thanks, great!

@pachamaltese are you clear on what edits needs to be made to satisfy the reviewers so far?

**Comment by JohnCoene** [comment]
@oliviaguest A wee tiny thing with the paper, an opened an issue [#12](https://github.com/pachamaltese/economiccomplexity/issues/12). When this is addressed it's all good on my end.

**Comment by pachamaltese** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01866/joss.01866/10.21105.joss.01866.pdf)

**Comment by pachamaltese** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01866/joss.01866/10.21105.joss.01866.pdf)

**Comment by pachamaltese** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01866/joss.01866/10.21105.joss.01866.pdf)

**Comment by pachamaltese** [comment]
> [ point_right Check article proof page_facing_up point_left ](https://github.com/openjournals/joss-papers/blob/joss.01866/joss.01866/10.21105.joss.01866.pdf)

@JohnCoene this closed #12

**Comment by JohnCoene** [comment]
All good one my side! @oliviaguest @pachamaltese

**Comment by oliviaguest** [comment]
@JohnCoene wonderful! @mpadge does this address your concerns too?

**Comment by oliviaguest** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3386/w11905 is OK
- 10.1109/MCSE.2009.19 is OK
- 10.1126/science.1144581 is OK
- 10.1073/pnas.0900943106 is OK
- 10.1126/science.1213847 is OK
- 10.7551/mitpress/9647.001.0001 is OK
- 10.1371/journal.pone.0113470 is OK
- 10.1140/epjb/e2015-60298-7 is OK
- 10.1016/j.worlddev.2016.12.020 is OK

MISSING DOIs

- https://doi.org/10.1038/srep00723 may be missing for title: A new metrics for countries’ fitness and products’ complexity
- https://doi.org/10.1038/srep08182 may be missing for title: Ranking species in mutualistic networks

INVALID DOIs

- None
```

**Comment by oliviaguest** [comment]
@pachamaltese please check those missing DOIs. 😅

**Comment by pachamaltese** [comment]
@oliviaguest thanks lot, Dr. I also added a proof reading comment by a native speaker (Dr. @cantabile)

@whedon generate pdf

**Comment by danielskatz** [comment]
Commands to whedon need to be at the start of a new comment, as follows

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01866/joss.01866/10.21105.joss.01866.pdf)

**Comment by pachamaltese** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01866/joss.01866/10.21105.joss.01866.pdf)

**Comment by pachamaltese** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01866/joss.01866/10.21105.joss.01866.pdf)

**Comment by pachamaltese** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3386/w11905 is OK
- 10.1109/MCSE.2009.19 is OK
- 10.1126/science.1144581 is OK
- 10.1073/pnas.0900943106 is OK
- 10.1126/science.1213847 is OK
- 10.1038/srep00723 is OK
- 10.7551/mitpress/9647.001.0001 is OK
- 10.1371/journal.pone.0113470 is OK
- 10.1140/epjb/e2015-60298-7 is OK
- 10.1038/srep08182 is OK
- 10.1016/j.worlddev.2016.12.020 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by oliviaguest** [comment]
@mpadge if you are happy to tick the last checkbox, we're good to go.

**Comment by mpadge** [comment]
box checked and all wholeheartedly approved from my side

**Comment by pachamaltese** [comment]
> box checked and all wholeheartedly approved from my side

Dr. Padgham
I asked a native speaker to read the text and make some parts be more "fluid". 
Thanks a lot for the useful suggestions.

**Comment by oliviaguest** [comment]
@pachamaltese can you deposit the code to a DOI provider like figshare or zotero, please? Post back the DOI when you are done. 😄

**Comment by pachamaltese** [comment]
Sure! Let me search for it

**Comment by oliviaguest** [comment]
@pachamaltese  Sorry zenodo! Here are the links, use whatever works best for you: 
* https://figshare.com/
* https://zenodo.org/

I'm sure others exist too! 😅

**Comment by pachamaltese** [comment]
> @pachamaltese Sorry zenodo! Here are the links, use whatever works best for you:
> 
> * https://figshare.com/
> * https://zenodo.org/
> 
> I'm sure others exist too! 😅

sure! now it makes more sense, I was creating an entry in zotero

**Comment by pachamaltese** [comment]
Dear Dr. @oliviaguest 
I got 10.5281/zenodo.3671843 after registration for the software.
Best,

**Comment by oliviaguest** [comment]
@whedon set 10.5281/zenodo.3671843 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3671843" target="_blank">10.5281/zenodo.3671843</a> is the archive.

**Comment by oliviaguest** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3386/w11905 is OK
- 10.1109/MCSE.2009.19 is OK
- 10.1126/science.1144581 is OK
- 10.1073/pnas.0900943106 is OK
- 10.1126/science.1213847 is OK
- 10.1038/srep00723 is OK
- 10.7551/mitpress/9647.001.0001 is OK
- 10.1371/journal.pone.0113470 is OK
- 10.1140/epjb/e2015-60298-7 is OK
- 10.1038/srep08182 is OK
- 10.1016/j.worlddev.2016.12.020 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1313

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1313, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by oliviaguest** [comment]
Thank you! @pachamaltese can you check the final proof please? 🎉

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01866/joss.01866/10.21105.joss.01866.pdf)

**Comment by pachamaltese** [comment]
> Thank you! @pachamaltese can you check the final proof please? 🎉

Dear Dr. @oliviaguest 
I read ok in my opinion. The only thing I dislike is a reference that created a new page for just 3 lines. Besides it, I'm ok with the result.

**Comment by oliviaguest** [comment]
@pachamaltese Hmm... some of your cites are (Name (YEAR)) and others are (Name, YEAR), do you want to fix those too? Either way: make any edits you like and I'll then tag the EiCs and we can get it published. 😄

**Comment by pachamaltese** [comment]
thanks! yes, I can change that as well

**Comment by pachamaltese** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01866/joss.01866/10.21105.joss.01866.pdf)

**Comment by pachamaltese** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01866/joss.01866/10.21105.joss.01866.pdf)

**Comment by pachamaltese** [comment]
Dear Dr. @oliviaguest 

I changed the citations () and I re-added a paragraph that I had removed before.

I'm also tagging @JohnCoene and @mpadge on your behalf.

Best,

**Comment by oliviaguest** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3386/w11905 is OK
- 10.1109/MCSE.2009.19 is OK
- 10.1126/science.1144581 is OK
- 10.1073/pnas.0900943106 is OK
- 10.1126/science.1213847 is OK
- 10.1038/srep00723 is OK
- 10.7551/mitpress/9647.001.0001 is OK
- 10.1371/journal.pone.0113470 is OK
- 10.1140/epjb/e2015-60298-7 is OK
- 10.1038/srep08182 is OK
- 10.1016/j.worlddev.2016.12.020 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1316

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1316, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by oliviaguest** [comment]
@pachamaltese are you happy with the final proof?

**Comment by pachamaltese** [comment]
Yes. What do the reviewers have to say?

**Comment by oliviaguest** [comment]
It doesn't matter. If you like @pachamaltese, we are good to do. :tada:

**Comment by oliviaguest** [comment]
@openjournals/joss-eics please accept this manuscript. :smiley_cat:

**Comment by pachamaltese** [comment]
Thanks a lot!!

**Comment by pachamaltese** [comment]
@oliviaguest
It looks ok imo and I'm waiting for the final public version

**Comment by pachamaltese** [comment]
> It doesn't matter. If you like it @pachamaltese, we are good to do. 🎉

Dear Dr. @oliviaguest. Do I have to complete additional steps?

**Comment by oliviaguest** [comment]
@pachamaltese no, we just wait for a @openjournals/joss-eics for the final step. Thank you.

**Comment by kyleniemeyer** [comment]
Hi @pachamaltese, I did some minor copy-editing in this PR: https://github.com/pachamaltese/economiccomplexity/pull/14 

Could you merge this and let me know when you have?

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01866/joss.01866/10.21105.joss.01866.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3386/w11905 is OK
- 10.1109/MCSE.2009.19 is OK
- 10.1126/science.1144581 is OK
- 10.1073/pnas.0900943106 is OK
- 10.1126/science.1213847 is OK
- 10.1038/srep00723 is OK
- 10.7551/mitpress/9647.001.0001 is OK
- 10.1371/journal.pone.0113470 is OK
- 10.1140/epjb/e2015-60298-7 is OK
- 10.1038/srep08182 is OK
- 10.1016/j.worlddev.2016.12.020 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1326

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1326, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1230231293834809349) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1327
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01866](https://doi.org/10.21105/joss.01866)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @pachamaltese on your article's publication in JOSS!

Many thanks to @JohnCoene and @mpadge for reviewing this, and @oliviaguest for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01866/status.svg)](https://doi.org/10.21105/joss.01866)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01866">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01866/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01866/status.svg
   :target: https://doi.org/10.21105/joss.01866
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01866/status.svg)](https://doi.org/10.21105/joss.01866)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by JohnCoene** [comment]
Congrats Mauricio! 🥳 Thanks to everyone, particularly @oliviaguest for her patience throughout this lengthy review.

**Comment by oliviaguest** [comment]
@JohnCoene, @mpadge, and @pachamaltese: thank you all and especially congratulations to @pachamaltese!  🎉 👏

**Comment by pachamaltese** [comment]
> @JohnCoene, @mpadge, and @pachamaltese: thank you all and especially congratulations to @pachamaltese! 🎉 👏

thank you @oliviaguest 
reproducibility is a really important subject, and I hope I made it clear with this particular piece of software

**Comment by mpadge** [comment]
Congrats @pachamaltese - a fabulous piece of work!
