### ISSUE TITLE
[PRE REVIEW]: EarthPy: A Python package that makes it easier to explore and plot raster and vector data using open source Python tools

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1869]
**Submitting author:** @lwasser (<a href="http://orcid.org/0000-0002-8177-6550">Leah Wasser</a>)
**Repository:** <a href="https://github.com/earthlab/earthpy" target ="_blank">https://github.com/earthlab/earthpy</a>
**Version:** 0.7.6
**Editor:** @arfon
**Reviewers:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @lwasser. The JOSS editor @arfon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@lwasser if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@arfon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1869 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1869 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01869/joss.01869/10.21105.joss.01869.pdf)

**Comment by arfon** [comment]
@lwasser - excellent to see the first pyOpenSci submission come through!

A couple of quick things:

- Can you link here to the review on the pyOpenSci-side of things?
- It looks like the references aren't compiling properly. From a quick inspection, it looks like the citation keys you're using in your `paper.md` aren't matching the ones in the `paper.bib`. For example in your paper you're using `kelsey_jordahl_2019_3483425:2019` but in the bibtex it's `kelsey_jordahl_2019_3483425`.

Once you've fixed those, you can ask Whedon to recompile your paper with `@whedon generate pdf`

**Comment by arfon** [comment]
Looks like the pyOpenSci review happened in https://github.com/pyOpenSci/software-review/issues/3

**Comment by lwasser** [comment]
ok @arfon let me first fix the paper / citation issues. My apologies for being slow to link the pyopensci review!! but thank you for finding it. [this link that you found](https://github.com/pyOpenSci/software-review/issues/3) is the correct one.

As far as reviewers @HaoZeke said he would be willing to review here. he did the pyopensci review. @jsta could also be a good fit for this review!!

**Comment by lwasser** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01869/joss.01869/10.21105.joss.01869.pdf)

**Comment by lwasser** [comment]
ok @arfon the citations look better now. i copied the rasterio citation and it's unusual. i had submitted a pr that was accepted to fix it but it looks like the year  is rendering as n.d. because the date in the citation is 2013-pre . Would you like for me to adjust that citation in some way? I can also submit another PR to rasterio if that is preferred. i think sean wanted the citation to represent that hte tool was started in 2013 and is still being maintained in the date. they (mapbox) do not use zenodo to track doi's for their tool.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01869/joss.01869/10.21105.joss.01869.pdf)

**Comment by arfon** [comment]
@lwasser - could you make sure you've cited all of the software that you mention in your article. For example, Matplotlib seems to be missing a citation here: https://matplotlib.org/3.1.1/citing.html

**Comment by lwasser** [comment]
hi @arfon ! of course. let me go back and make a few more edits. i'll ping you again when that is complete.
leah

**Comment by jsta** [comment]
This looks a great paper but unfortunately my reviewing queue is full right now. Best of luck!

**Comment by lwasser** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01869/joss.01869/10.21105.joss.01869.pdf)

**Comment by lwasser** [comment]
@whedon generate pdf 
pretty please!

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01869/joss.01869/10.21105.joss.01869.pdf)

**Comment by lwasser** [comment]
hi @arfon !
I added matplotlib and pysal to the citations! I can't seem to find citation info for [georasters](https://github.com/ozak/georasters). This package was just included as an example of other packages that allow for the use of raster data. How would you like for me to proceed with citing that package? 

The pdf seemed to generate well that citation aside. 

Also it looks like Joe is overtasked with reviews right now. should i mention other people? or how do you proceed with the review itself to get reviewers on board? thank you!!

**Comment by HaoZeke** [comment]
As mentioned by @lwasser, I would like to confirm that I would be happy to take this on when required, which might be relevant as I also reviewed it for the [initial pyopensci review](https://github.com/pyOpenSci/software-review/issues/3). @arfon

**Comment by arfon** [comment]
> Also it looks like Joe is overtasked with reviews right now. should i mention other people? or how do you proceed with the review itself to get reviewers on board? thank you!!

@lwasser - just to clarify, we won't do a second review here. As the pyOpenSci review is compatible with the JOSS review we simply fast-track the paper through here.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01869/joss.01869/10.21105.joss.01869.pdf)

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1886. Feel free to close this issue now!

**Comment by lwasser** [comment]
i see @arfon thank you for the clarification!! please let me know what you need from me!!

**Comment by arfon** [comment]
> i see @arfon thank you for the clarification!! please let me know what you need from me!!

Please see my comment over in https://github.com/openjournals/joss-reviews/issues/1886#issuecomment-552691390 .
