### ISSUE TITLE
[PRE REVIEW]: spatial-efd: A spatial-aware implementation of elliptical Fourier analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#187]
**Submitting author:** @sgrieve (<a href="http://orcid.org/0000-0003-1893-7363">Stuart Grieve</a>)
**Repository:** <a href="https://github.com/sgrieve/spatial_efd" target ="_blank">https://github.com/sgrieve/spatial_efd</a>
**Version:** v1.0.3
**Editor:** @cmadan
**Reviewer:** @jsta

**What this issue is for**

Thanks for submitting your paper to JOSS @sgrieve. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by sgrieve** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by cMadan** [comment]
@whedon assign @cmadan as editor

**Comment by whedon** [comment]
OK, the editor is @cmadan

**Comment by cMadan** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by cMadan** [comment]
@tacaswell, @decvalts, @Mankoff, @sealhuang, @jsta - would any of you be interested/available to be a reviewer for this submission? Thanks!

**Comment by jsta** [comment]
I would be interested in reviewing. This technique looks fascinating and very useful!

**Comment by cMadan** [comment]
@jsta - much appreciated, I'll assign you as the reviewer and start the review process :)

**Comment by cMadan** [comment]
@whedon assign @jsta as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jsta

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by cMadan** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/189. Feel free to close this issue now!
