### ISSUE TITLE
[PRE REVIEW]: FLAM: Fast Linear Algebra in MATLAB

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1871]
**Submitting author:** @klho (<a href="http://orcid.org/0000-0001-5450-4966">Kenneth L. Ho</a>)
**Repository:** <a href="https://github.com/klho/FLAM" target ="_blank">https://github.com/klho/FLAM</a>
**Version:** v1.1.0 (will update on completion)
**Editor:** @melissawm
**Reviewers:** @sivaramambikasaran, @pitsianis

**Author instructions**

Thanks for submitting your paper to JOSS @klho. **Currently, there isn't an JOSS editor assigned** to your paper.

@klho if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1871 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1871 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by klho** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by klho** [comment]
Here are some suggestions for potential reviewers: @sivaramambikasaran, @pitsianis, @zgimbutas.

**Comment by kyleniemeyer** [comment]
Hi @melissawm, I realize I just asked you about another submission, but this one also looks like a good fit. Can you edit this as well?

**Comment by melissawm** [comment]
Sure, this is right for me :)

**Comment by melissawm** [comment]
@whedon assign @melissawm as editor

**Comment by whedon** [comment]
OK, the editor is @melissawm

**Comment by melissawm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01871/joss.01871/10.21105.joss.01871.pdf)

**Comment by melissawm** [comment]
@sivaramambikasaran, would you be willing to review this software paper for JOSS? Thank you!

**Comment by melissawm** [comment]
@pitsianis would you be available to review this software paper for JOSS? Thank you

**Comment by pitsianis** [comment]
I will be happy to. But I won't be able to start looking at it untill the weekend after next. Would that be acceptable?

**Comment by sivaramambikasaran** [comment]
> @sivaramambikasaran, would you be willing to review this software paper for JOSS? Thank you!

@melissawm Sure would ❤ to. The only thing is I can only start next week since we now have the end sof the semester craze going on.

**Comment by melissawm** [comment]
If @klho is ok with this time frame, I don't see a problem! Please let me know and I can start the review issue.

**Comment by klho** [comment]
No problem on my end -- thanks!

**Comment by melissawm** [comment]
Great! I'll open the review issue and will be around if you have any questions. You can start the review whenever you're ready. Thanks!

**Comment by melissawm** [comment]
@whedon assign @sivaramambikasaran as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sivaramambikasaran

**Comment by melissawm** [comment]
@whedon add @pitsianis as reviewer

**Comment by whedon** [comment]
OK, @pitsianis is now a reviewer

**Comment by melissawm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1906. Feel free to close this issue now!
