### ISSUE TITLE
[PRE REVIEW]: MNE-BIDS: Organizing neurophysiological data into the BIDS format and facilitating their analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1872]
**Submitting author:** @sappelhoff (<a href="http://orcid.org/0000-0001-8002-0877">Stefan Appelhoff</a>)
**Repository:** <a href="https://github.com/mne-tools/mne-bids" target ="_blank">https://github.com/mne-tools/mne-bids</a>
**Version:** v0.3
**Editor:** @arokem
**Reviewers:** jdkent, @TomDonoghue

**Author instructions**

Thanks for submitting your paper to JOSS @sappelhoff. **Currently, there isn't an JOSS editor assigned** to your paper.

@sappelhoff if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kyleniemeyer** [comment]
Hi @arokem, the authors suggested you to edit this submission—can you take it?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01872/joss.01872/10.21105.joss.01872.pdf)

**Comment by arokem** [comment]
Yeah. I can take this one on.

**Comment by arokem** [comment]
@whedon assign arokem as editor

**Comment by whedon** [comment]
OK, the editor is arokem

**Comment by arokem** [comment]
👋 @tyarkoni: Would you be willing to review this paper for JOSS? (assuming no [COI](https://github.com/openjournals/joss/blob/master/COI.md)? )

**Comment by arokem** [comment]
👋 @jdkent : Would you be willing to review this paper for JOSS (assuming no [COI](https://github.com/openjournals/joss/blob/master/COI.md)? )?

**Comment by tyarkoni** [comment]
I definitely have a COI—sorry!

**Comment by arokem** [comment]
👋 @ftadel :  would you be willing to review this paper for [the Journal of Open Source Software](https://joss.theoj.org/)? The review process is explained [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)

**Comment by jdkent** [comment]
I would be happy to! 

pending...
I'm on the same [nipype zenodo record](https://zenodo.org/record/3476537#.XcZIjd-YU8o) as Alexandre Gramfort, but we did not directly collaborate. Also I depend on some [MNE code in NiBetaSeries](https://github.com/HBClab/NiBetaSeries/blob/a756e85cab21e5e94cb37ebb6ecea3c698330e0c/src/nibetaseries/interfaces/nilearn.py#L43). 

I do not believe these minor perceived conflicts should impact my ability to be an impartial reviewer, but I will leave it to @arokem to decide whether the conflict(s) should be waived.

**Comment by arokem** [comment]
Thanks! The nipype zenodo record seems fine to me. And depending on MNE seems to make you an appropriate reviewer here. I'll add you, but stand by until I find a second reviewer, before I kick off the review process.

**Comment by arokem** [comment]
@whedon add jdkent as reviewer

**Comment by whedon** [comment]
OK, jdkent is now a reviewer

**Comment by ftadel** [comment]
I'd be very interested in reviewing this article, but I'll be traveling for a while and I can't guarantee I'd work on it immediately (probably by the end of November, and for sure before mid-December).
If you're not in a rush, you can count me in.

**Comment by arokem** [comment]
👋 @ixjlyons : would you be willing to review this submission to JOSS?

**Comment by arokem** [comment]
👋 @TomDonoghue : would you be willing to review this submission for JOSS?

**Comment by TomDonoghue** [comment]
@arokem - Yes, I'd be happy to review this submission!

I am an MNE user, and a fan of the BIDS project, but not directly involved in either, so I think I should be clear for COIs. This seems very relevant to the kind of word I do, and I'd be happy to review it.

**Comment by arokem** [comment]
@joss add @TomDonoghue as reviewer

**Comment by arokem** [comment]
@whedon add @TomDonoghue as reviewer

**Comment by whedon** [comment]
OK, @TomDonoghue is now a reviewer

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1896. Feel free to close this issue now!

**Comment by arokem** [comment]
Thanks @TomDonoghue and @jdkent ! Please head over to #1896 for your reviewer check lists. Feel free to post issues on the software repository, linking to the review issue. Feel free to tag me into any issues where you'd like me to weigh in. I'll close this pre-review issue now.
