### ISSUE TITLE
[PRE REVIEW]: ScenTrees.jl: A Julia Library For Generating Scenario Trees and Scenario Lattices for Multistage Stochastic Optimization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1873]
**Submitting author:** @kirui93 (<a href="http://orcid.org/0000-0002-3679-4442">Kipngeno </a>)
**Repository:** <a href="https://github.com/kirui93/ScenTrees.jl" target ="_blank">https://github.com/kirui93/ScenTrees.jl</a>
**Version:** v0.1.2
**Editor:** @melissawm
**Reviewers:** @juliohm, @matbesancon

**Author instructions**

Thanks for submitting your paper to JOSS @kirui93. **Currently, there isn't an JOSS editor assigned** to your paper.

@kirui93 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01873/joss.01873/10.21105.joss.01873.pdf)

**Comment by kyleniemeyer** [comment]
Hi @melissawm, can you edit this submission for us?

**Comment by melissawm** [comment]
I can, @kyleniemeyer!

**Comment by melissawm** [comment]
@whedon assign @melissawm as editor

**Comment by whedon** [comment]
OK, the editor is @melissawm

**Comment by melissawm** [comment]
Hello, @kirui93! There are some details on the paper:
- For the reference Høyland, K., & Wallace, S. W. (2001), there is a typo on the name of the journal (Management Science). Also, the DOI for this paper seems to be mistyped: I believe the correct number is 10.1287/mnsc.47.2.295.9834. Can you check this, please?
- For the reference Kovacevic, R. M., & Pichler, A. (2015) you should include a volume number (in this case, 235).
- For the reference Pflug, G. C., & Pichler, A. (2016), there is an extra subtitle that is not listed in the published version of the paper (here https://epubs.siam.org/doi/10.1137/15M1043376). Can you please check this?
- Finally, for some references there are Volume and Issue listed, and other not. Could you make sure that the references are standardized? Ideally, all references should have an issue number if applicable.

Thank you!

**Comment by kirui93** [comment]
Hello, @melissawm ,
Thank you so much for the corrections. 
I think it was a typo for most of them but I have corrected them.

Many thanks.

**Comment by kirui93** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1873 with the following error: 

 Error reading bibliography ./paper.bib (line 104, column 1):
unexpected "%"
expecting space, letter, digit, white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by kirui93** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01873/joss.01873/10.21105.joss.01873.pdf)

**Comment by kirui93** [comment]
Hello @melissawm ,
I think all is good now regarding the issues you had stated above.
Thank you once again.

**Comment by kirui93** [comment]
Hello @melissawm,
Is there anything that I am supposed to do next concerning this review?
Thank you.

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by melissawm** [comment]
Hello, @kirui93 , the corrections are OK except for the volume number on the reference Kovacevic, R. M., & Pichler, A. (2015). I'll now start the process of finding reviewers.

**Comment by melissawm** [comment]
@ChrisRackauckas would you be willing to review this paper for JOSS? Thank you!

**Comment by melissawm** [comment]
@jarvist would you be willing to review this software paper for JOSS? Thank you!

**Comment by jarvist** [comment]
> @jarvist would you be willing to review this software paper for JOSS? Thank you!

It's well outside my area of expertise, but I am happy to review as a naive user. 
I have quite a few academic commitments at the moment, so it may take a while to fit this review in.

**Comment by ChrisRackauckas** [comment]
I'll pass on this for now, but if it's still looking for reviewers in February let me know. It is outside of my expertise though.

**Comment by melissawm** [comment]
Thank you for responding, @ChrisRackauckas ! I'll try to ask someone else then.

@jarvist if you prefer we can contact someone else, just let me know.

@kirui93 do you have suggestions for reviewers?

**Comment by kirui93** [comment]
Hello @melissawm ,
Thank you for this opportunity to suggest the reviewers.
In terms of area of expertise, I would suggest @juliohm, @taqtiqa-mark , @dpsanders and @matbesancon from this [list of potential reviewers](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822)

Thank you.

**Comment by juliohm** [comment]
Thank you guys for pinging my name. I'd happy to review the article over the week. Very interesting package 💯 .

**Comment by matbesancon** [comment]
Hi, I'm available and happy to review this paper

**Comment by melissawm** [comment]
Great, thank you both for responding! I'll add you as reviewers and start the review issue.

**Comment by melissawm** [comment]
@whedon assign @juliohm as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @juliohm

**Comment by melissawm** [comment]
@whedon add @matbesancon as reviewer

**Comment by whedon** [comment]
OK, @matbesancon is now a reviewer

**Comment by melissawm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1912. Feel free to close this issue now!
