### ISSUE TITLE
[PRE REVIEW]: ampscan: A lightweight Python package for shape analysis of prosthetics and orthotics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1875]
**Submitting author:** @JoshuaSteer (<a href="http://orcid.org/0000-0002-6288-1347">Joshua Steer</a>)
**Repository:** <a href="https://github.com/abel-research/ampscan" target ="_blank">https://github.com/abel-research/ampscan</a>
**Version:** v0.3.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @danasolav

**Author instructions**

Thanks for submitting your paper to JOSS @JoshuaSteer. **Currently, there isn't an JOSS editor assigned** to your paper.

@JoshuaSteer if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1875 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1875 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-74bc29a6a731/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
Hi @Kevin-Mattheus-Moerman, I hesitate to ask you to edit this one due to your current load, but it looks right up your alley...

**Comment by kyleniemeyer** [comment]
@openjournals/dev any ideas why the paper isn't compiling? I can't tell from the error message.

**Comment by JoshuaSteer** [comment]
It compiles for me without any problems using the preview service if that helps debugging

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01875/joss.01875/10.21105.joss.01875.pdf)

**Comment by kyleniemeyer** [comment]
@JoshuaSteer not sure why it didn't work the first time, but looks fine now!

**Comment by Kevin-Mattheus-Moerman** [comment]
@kyleniemeyer I can take this one

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@danasolav would you or one of your colleagues like to review this work?

**Comment by Kevin-Mattheus-Moerman** [comment]
@JoshuaSteer thanks for your submission. I'll be looking for reviewers. Let me know if you had any recommended reviewers in mind. Thanks.

**Comment by JoshuaSteer** [comment]
@Kevin-Mattheus-Moerman Thanks for picking this up, and great suggestion of Dana (also who I would have suggested). I'll have a look around for potential reviewers, possibly the team behind the polygon mesh processing library (https://github.com/pmp-library/pmp-library)?

**Comment by danasolav** [comment]
I'm happy to review this submission, but I will be able to do it only at the end of the month (in about 2 weeks or so). Is that ok?

**Comment by alexd103** [comment]
Thanks for handling this for us @Kevin-Mattheus-Moerman!
Tom Saey from MOBILAB at Thomas More in Belgium might be interested and has domain-relevant experience - again if we can find him on here. https://www.linkedin.com/in/tom-saey-61167232/?originalSubdomain=be

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @danasolav as reviewer

**Comment by whedon** [comment]
OK, @danasolav is now a reviewer

**Comment by danielskatz** [comment]
👋 @Kevin-Mattheus-Moerman - it looks like this submission needs another reviewer?

**Comment by Kevin-Mattheus-Moerman** [comment]
@danielskatz thanks for the reminder

**Comment by Kevin-Mattheus-Moerman** [comment]
@gkontoudis @cmavrogiannis @liarokapis would you be interested in reviewing this submission for [JOSS](https://joss.theoj.org) on prosthetic socket design?

**Comment by danasolav** [comment]
Is it open for review already, or only after finding additional reviewers?

**Comment by Kevin-Mattheus-Moerman** [comment]
@danasolav I'm still looking for an additional reviewer. If you would like to start earlier I can open up the review issue if you like.

**Comment by Kevin-Mattheus-Moerman** [comment]
@gkontoudis @cmavrogiannis @liarokapis would you be interested in reviewing this submission for JOSS on prosthetic socket design? christmas_tree

**Comment by Kevin-Mattheus-Moerman** [comment]
I'll be the 2nd reviewer here to avoid further delay. I'll now trigger the review process.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2060.
