### ISSUE TITLE
[PRE REVIEW]: Plonk: Smoothed particle hydrodynamics analysis and visualization with Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1876]
**Submitting author:** @dmentipl (<a href="http://orcid.org/0000-0002-5526-8798">Daniel Mentiplay</a>)
**Repository:** <a href="https://github.com/dmentipl/plonk" target ="_blank">https://github.com/dmentipl/plonk</a>
**Version:** v0.2.0
**Editor:** @dfm
**Reviewers:** @zingale, @matthewturk

**Author instructions**

Thanks for submitting your paper to JOSS @dmentipl. **Currently, there isn't an JOSS editor assigned** to your paper.

@dmentipl if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kyleniemeyer** [comment]
Hi @dfm, can you edit this submission?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01876/joss.01876/10.21105.joss.01876.pdf)

**Comment by dfm** [comment]
@kyleniemeyer: Sure - I can take it!

**Comment by dfm** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by dfm** [comment]
@dmentipl: please take a look at [this list](https://bitly.com/joss-reviewers) of potential reviewers and let me know if there's anyone who you think would be especially well suited. Thanks!

**Comment by dmentipl** [comment]
Hi @dfm, thanks for agreeing to review my submission!

I had a look at the list, and no one in particular stood out. I suppose anyone with Python and astrophysics/astronomy expertise would be suitable.

**Comment by dfm** [comment]
:wave: @zingale: Any chance you're available to review this submission?

**Comment by dfm** [comment]
:wave: @matthewturk: Any chance you're available to review this submission?

**Comment by zingale** [comment]
I can review

**Comment by matthewturk** [comment]
I can review

**Comment by dfm** [comment]
@zingale @matthewturk: many thanks!

**Comment by dfm** [comment]
@whedon assign @zingale as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @zingale

**Comment by dfm** [comment]
@whedon add @matthewturk as reviewer

**Comment by whedon** [comment]
OK, @matthewturk is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1884. Feel free to close this issue now!

**Comment by dfm** [comment]
@dmentipl @matthewturk @zingale: Let's head over to #1884 to get started with the review. Thanks again!
