### ISSUE TITLE
[PRE REVIEW]: rnassqs: An R package to access agricultural data via the USDA National Agricultural Statistical Service (USDA-NASS) 'Quick Stats' API

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1877]
**Submitting author:** @potterzot (<a href="http://orcid.org/0000-0002-3410-3732">Nicholas A Potter</a>)
**Repository:** <a href="https://github.com/ropensci/rnassqs" target ="_blank">https://github.com/ropensci/rnassqs</a>
**Version:** v0.6.1
**Editor:** @kyleniemeyer
**Reviewers:** @kyleniemeyer

**Author instructions**

Thanks for submitting your paper to JOSS @potterzot. **Currently, there isn't an JOSS editor assigned** to your paper.

@potterzot if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1877 with the following error: 

 Could not find bibliography file: paper.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by kyleniemeyer** [comment]
Hi @potterzot, it looks like you are missing a `paper.bib` file in the repo—do you have any references?

**Comment by potterzot** [comment]
@kyleniemeyer ack, sorry! I removed it because when cleaning up the paper for submission I ended up without any references. I thought I had retested the compile but apparently not. I've added an empty paper.bib so that it compiles correctly.

**Comment by potterzot** [comment]
For reference, I'm submitting as part of the rOpenSci review, which I believe I am supposed to post here: https://github.com/ropensci/software-review/issues/298.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01877/joss.01877/10.21105.joss.01877.pdf)

**Comment by kyleniemeyer** [comment]
@potterzot thanks!

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
@whedon add @kyleniemeyer as reviewer

**Comment by whedon** [comment]
OK, @kyleniemeyer is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1880. Feel free to close this issue now!
