### ISSUE TITLE
[PRE REVIEW]: SHARPy: A dynamic aeroelastic simulation toolbox for very flexible aircraft and wind turbines

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1878]
**Submitting author:** @fonsocarre (<a href="http://orcid.org/0000-0002-8133-9481">Alfonso del Carre</a>)
**Repository:** <a href="https://github.com/ImperialCollegeLondon/sharpy" target ="_blank">https://github.com/ImperialCollegeLondon/sharpy</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewers:** @petebachant, @rafmudaf

**Author instructions**

Thanks for submitting your paper to JOSS @fonsocarre. **Currently, there isn't an JOSS editor assigned** to your paper.

@fonsocarre if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kyleniemeyer** [comment]
Hi @labarba, could you take this submission on? Looks to be right up your alley!

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01878/joss.01878/10.21105.joss.01878.pdf)

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
👋  @mtezzele — I see that you have published [three papers](https://joss.theoj.org/papers/by/Marco%20Tezzele) with JOSS. Good job! 
And you also already [reviewed](https://joss.theoj.org/papers/reviewed_by/@mtezzele) one paper. Thank you 🙏 

Could you contribute one more review for us? The submission is:
*SHARPy: A dynamic aeroelastic simulation toolbox for very flexible aircraft and wind turbines*
https://github.com/ImperialCollegeLondon/sharpy

**Comment by labarba** [comment]
👋  @petebachant — Do you think you could contribute a review for JOSS on this submission? You haven't reviewed for us before, but I think you will like it. The whole process is done in the open, on a GitHub issue. Have a look at our [Reviewer Guide](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).
The submission is:
_SHARPy: A dynamic aeroelastic simulation toolbox for very flexible aircraft and wind turbines_
https://github.com/ImperialCollegeLondon/sharpy

**Comment by petebachant** [comment]
@labarba I believe I did review something for you folks at one point--maybe in a different journal but similar process. Anyway, I'm up for reviewing this!

**Comment by fonsocarre** [comment]
@labarba @petebachant thank you! I’m looking forward to receiving your feedback. Let me know if there is anything I can do to make this as easy as possible for everyone.

**Comment by fonsocarre** [comment]
@ngoiz @ArturoMS13 @rafapalacios For you to keep an eye on this.

**Comment by labarba** [comment]
@whedon assign @petebachant as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @petebachant

**Comment by labarba** [comment]
Thank you, Pete! 
Stay tuned, everybody, until we assign a second reviewer

**Comment by mtezzele** [comment]
Dear @labarba, sorry but next weeks are not a good period for me, I have to decline this one.  I'm really sorry, the package seems very cool. I hope to give you a hand in the future.

**Comment by labarba** [comment]
👋 @rafmudaf — I found that you are a contributor of [OpenFAST](https://github.com/OpenFAST/openfast) at NREL. Would you be interested in contributing a review for [The Journal of Open Source Software](https://joss.theoj.org)? Reviews are done in the open, in a GitHub repo, and they focus on the quality of software for research uses. Have a look at our [Reviewer Guide](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

The submission I'm hoping you'd like to review is:
_SHARPy: A dynamic aeroelastic simulation toolbox for very flexible aircraft and wind turbines_
https://github.com/ImperialCollegeLondon/sharpy
https://github.com/openjournals/joss-reviews/issues/1878

**Comment by rafmudaf** [comment]
Hello @labarba - I'm happy to provide a review! The next few days are pretty packed, but I should be able to get started soon. Whats your time frame for me to complete it?

**Comment by labarba** [comment]
Terrific, @rafmudaf, thank you! We generally request reviewers to plan for a two-week (ideal) turn-around, but it's of course a soft deadline, and we appreciate that our volunteers have busy lives and do their best. 

I'm going to assign you know and start the review (which will open a new GitHub issue).

**Comment by labarba** [comment]
@whedon add @rafmudaf as reviewer

**Comment by whedon** [comment]
OK, @rafmudaf is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1885. Feel free to close this issue now!
