### ISSUE TITLE
[PRE REVIEW]: PyCHAM: CHemistry with Aerosol Microphysics in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1879]
**Submitting author:** @simonom (<a href="http://orcid.org/0000-0001-7197-0651">Simon O&#39;Meara</a>)
**Repository:** <a href="https://github.com/simonom/PyCHAM" target ="_blank">https://github.com/simonom/PyCHAM</a>
**Version:** 0.0.5
**Editor:** @jedbrown
**Reviewers:** dhhagan, andreas-h

**Author instructions**

Thanks for submitting your paper to JOSS @simonom. **Currently, there isn't an JOSS editor assigned** to your paper.

@simonom if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01879/joss.01879/10.21105.joss.01879.pdf)

**Comment by kyleniemeyer** [comment]
Hi @simonom, thanks for your interest in JOSS. Normally at this stage I would assign an editor, who would then find reviewers in this pre-review issue.

However, I noticed some major issues with your submission that need to be addressed (which any reviewers would likely get stuck on):
- Your software needs an open-source license, from this [list](https://opensource.org/licenses)
- You've created a Python package, but it isn't set up like a package that can be installed in the standard ways. This isn't too much work, but it goes a long way towards making your software usable by others. There are multiple guides out there on doing this: https://docs.python-guide.org/shipping/packaging/

**Comment by simonom** [comment]
Many thanks @kyleniemeyer ,

These issues you raised (inclusion of license and availability on PyPi) have now been addressed.

Regards,
Simon O'Meara

**Comment by labarba** [comment]
@simonom — please check in your paper the unresolved references (shown in the PDF as ???).

**Comment by labarba** [comment]
👋  @dvalters, @highendcompute — you both review the PyBox paper for JOSS last year. Would you be willing to review a follow-on submission?
**PyCHAM: CHemistry with Aerosol Microphysics in Python**
https://github.com/simonom/PyCHAM

**Comment by labarba** [comment]
@jedbrown — Could you handle this submission as editor? (Lindsey is stepping down from the board to focus on her job search and we're low on geosciences editors now!)

**Comment by jedbrown** [comment]
@simonom Welcome! Could you please check your paper for **???** references, and also consider more explicitly laying out the problems that are solved (e.g., can you write the structural form of the differential equations?) and related work (even if not written in Python)? Also, I would really encourage you to add continuous integration (e.g., Travis-CI or Azure DevOps) to run and report on your test suite, and to use formatting in your README (lots of commands and path literals don't use `verbatim`).

**Comment by jedbrown** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by simonom** [comment]
And now the improved description of ode equations and related work has been included in the paper.  In addition, the README has been formatted @jedbrown.

**Comment by simonom** [comment]
Finally, continuous integration using Travis-CI has been implemented, thanks @jedbrown .

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01879/joss.01879/10.21105.joss.01879.pdf)

**Comment by jedbrown** [comment]
@josephhardinee @dhhagan @andreas-h :wave: Would you be available and interested in reviewing this submission for JOSS?

**Comment by andreas-h** [comment]
Yes can do that if it is acceptable that it will take me until the end of the year to properly do it.

**Comment by dhhagan** [comment]
Yup - I could fit this in next week sometime if that's alright.

**Comment by jedbrown** [comment]
@whedon add dhhagan as reviewer

**Comment by whedon** [comment]
OK, dhhagan is now a reviewer

**Comment by jedbrown** [comment]
@whedon add andreas-h as reviewer

**Comment by whedon** [comment]
OK, andreas-h is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1918. Feel free to close this issue now!
