### ISSUE TITLE
[REVIEW]: MSMExplorer: Data Visualizations for Biomolecular Dynamics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#188]
**Submitting author:** @cxhernandez (<a href="http://orcid.org/0000-0002-8146-5904">Carlos Xavier Hernández</a>)
**Repository:** <a href="https://github.com/msmexplorer/msmexplorer" target ="_blank">https://github.com/msmexplorer/msmexplorer</a>
**Version:** v1.0.0
**Editor:** @arokem
**Reviewer:** @anotherjoshsmith
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.439774" target="_blank">10.5281/zenodo.439774</a>

## Status

[![status](http://joss.theoj.org/papers/f9485c45a7bfc5cfce6edd8919a07739/status.svg)](http://joss.theoj.org/papers/f9485c45a7bfc5cfce6edd8919a07739)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f9485c45a7bfc5cfce6edd8919a07739"><img src="http://joss.theoj.org/papers/f9485c45a7bfc5cfce6edd8919a07739/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f9485c45a7bfc5cfce6edd8919a07739/status.svg)](http://joss.theoj.org/papers/f9485c45a7bfc5cfce6edd8919a07739)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/msmexplorer/msmexplorer" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/msmexplorer/msmexplorer">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@cxhernandez) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @anotherjoshsmith it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arokem** [comment]
@arfon : why does this say "Does the release version given match the GitHub release (v1.0.0)?"? 

The current release version on Github is 0.3. Where does the `1.0.0` come from?

**Comment by cxhernandez** [comment]
@arokem: That's my fault. My intention was to hold off on making a v1.0.0 release until the review is done. In my previous experience with JOSS, the reviewer at the time requested additional functionality to package, and it required us to cut a new release anyways.

**Comment by arokem** [comment]
Gotcha - thanks! That means that @anotherjoshsmith should go through everything else, wait until everything else is in order, and then wait for you to cut a v1.0.0 before checking that box. Is that your intention?

**Comment by cxhernandez** [comment]
Yeah, that would be great!

**Comment by cxhernandez** [comment]
> I think you have put together a very useful research tool. I've even started testing it with data sets of my own!

That's great to hear! Thanks!

I've made a [PR](https://github.com/msmexplorer/msmexplorer/pull/79) that addresses each task item. Let me know what you think!

**Comment by anotherjoshsmith** [comment]
All [review issues](https://github.com/msmexplorer/msmexplorer/issues/77#issuecomment-291564733) have been resolved. 

@arokem: I suggest _"MSMExplorer: Data Visualizations for Biomolecular Dynamics"_ by @cxhernandez et al. be accepted by JOSS.

**Comment by arokem** [comment]
Thank you @anotherjoshsmith! 

@cxhernandez : could you please create a Zenodo archive with the 1.0.0 version? Once you do that, I can set that as the archive, and move ahead to accept and close this issue.

**Comment by cxhernandez** [comment]
@arokem: The archive for v1.0.0 can be found [here](https://doi.org/10.5281/zenodo.439774).

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.439774 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.439774" target="_blank">10.5281/zenodo.439774</a> is the archive.

**Comment by arokem** [comment]
@arfon : I believe this one is ready to go! Anything else I need to do to get this one into this page: http://joss.theoj.org/papers/popular?

**Comment by arfon** [comment]
> @arfon : I believe this one is ready to go! Anything else I need to do to get this one into this page: http://joss.theoj.org/papers/popular?

@arokem - I still have to do the last few bits. Planning on giving @whedon those super-powers sometime soon.

@arokem many thanks for editing this and @anotherjoshsmith for your review ✨ 

@cxhernandez - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00188 :zap: 🚀 💥
