### ISSUE TITLE
[PRE REVIEW]: Audiometry: A Model-View-ViewModel (MVVM) Application Framework for Hearing Impairment Diagnosis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1883]
**Submitting author:** @drwaseemsheikh (<a href="http://orcid.org/0000-0002-4647-4565">Waseem Sheikh</a>)
**Repository:** <a href="https://github.com/drwaseemsheikh/audiometry.git" target ="_blank">https://github.com/drwaseemsheikh/audiometry.git</a>
**Version:** 1.0.0
**Editor:** @akeshavan
**Reviewers:** @ati-ozgur, @dvberkel

**Author instructions**

Thanks for submitting your paper to JOSS @drwaseemsheikh. **Currently, there isn't an JOSS editor assigned** to your paper.

@drwaseemsheikh if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1883 with the following error: 

 Error reading bibliography ./paper.bib (line 9, column 6):
unexpected "{"
expecting letter, digit, white space or "="
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by kyleniemeyer** [comment]
Hello @drwaseemsheikh, thanks for your interest in JOSS.

Before we get started, I took a quick look at your article and software, and while it looks very useful, I can't tell from either how it satisfies one of our requirements to be in scope:
> The software should have an **obvious** research application.

Can you clarify this? Thanks!

**Comment by drwaseemsheikh** [comment]
Thank you for your feedback.

I would like to clarify this based on the scope statement of the journal reproduced below:
“JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or the execution of research experiments; extracts knowledge from large data sets; offers a mathematical library, or similar.”

First, I would like to make the case that “Audiometry solves a complex problem in the domain of medicine, in particular, ear-related pathologies”. It generates important metrics including speech perception scores, hearing impairment scores, hearing disability scores, speech recognition threshold, speech discrimination score, and speech discrimination intensity, from the raw hearing test data. These scores help in better diagnosis of a particular kind of hearing loss.

Audiometry also generates complex visualization plots including pure-tone audiogram, speech audiogram, tympanogram, and calorigram based on the raw hearing test data, which are essential for an otolaryngologist to diagnose various ear-related pathologies. The shapes and relative positioning of these curves help in the diagnosis of various ear-related pathologies.

Secondly, I would like to make the case that Audiometry “supports the functioning of research instruments or the execution of research experiments; extracts knowledge from large data sets”.
Audiometry provides a comprehensive hearing test data management and diagnosis system to support the functioning and execution of various hearing test-related hardware. An otolaryngologist uses a wide variety of specialized equipment to gather hearing test data. However, there is no unified and centralized open-source software which provides an ability to store this vast array of hearing test data in one application. By having this data in one application, allows the otolaryngologist to more accurately and swiftly diagnose a hearing loss.

The knowledge extraction parts come through the generation of important hearing loss metrics including speech perception scores, hearing impairment scores, hearing disability scores, speech recognition threshold, speech discrimination score, and speech discrimination intensity and the generation of complex visualization plots including pure-tone audiogram, speech audiogram, tympanogram, and calorigram.

**Comment by labarba** [comment]
@drwaseemsheikh — Thank you for your clarifications. You have made the case for the software's use in clinical settings. Can you describe its use in *research* situations?

**Comment by drwaseemsheikh** [comment]
Thank you for giving us a chance to explain some of the research applications of Audiometry.

Following are some of the research questions that can be investigated by the use of Audiometry. The coauthor, who is an otolaryngologist, is using the software in some of the following research studies:

1.	Audiometry can be used to compare the sensitivity (true-positive rate) and specificity (true-negative rate) of various hearing test equipment and methods. For example, questions like how reliable is a pure-tone audiometry test performed by a smartphone or a tablet when compared with a benchmark calibrated audiometer can be easily answered by using the proposed software.

2.	The software can be used to determine the correlation between certain lifestyle and/or work conditions and the types of hearing loss. For example, the coauthor is using the software to record hearing test data from air force servicemen who are subject to very loud noise. Using the software important correlations can be determined for example, what kind of hearing loss is common among air force servicemen. In addition, the coauthor is also investigating certain patterns and correlations among the demographics of young children in remote areas in underdeveloped countries and the type of hearing loss.

3.	The software can be used to measure the efficacy of a certain treatment, intervention, or equipment on the progression of a hearing loss.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1883 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/lib/whedon.rb:114:in `editor': undefined method `[]' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/lib/whedon/compilers.rb:113:in `pdf_from_markdown'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/lib/whedon/compilers.rb:13:in `generate_pdf'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/bin/whedon:56:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@openjournals/dev -- we're experiencing some compilation issues. Help?

**Comment by labarba** [comment]
@akeshavan 👋  Welcome to JOSS, Anisha! Could you handle this submission as editor? 
**Audiometry: A Model-View-ViewModel (MVVM) Application Framework for Hearing Impairment Diagnosis**

**Comment by drwaseemsheikh** [comment]
Hi @akeshavan,
Sorry for the compilation issues. Could you please tell me what do I need to do to fix these errors? It's not clear from the error log. Thanks!

**Comment by labarba** [comment]
Please stay put. I believe it is a problem on the JOSS side.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01883/joss.01883/10.21105.joss.01883.pdf)

**Comment by akeshavan** [comment]
:wave: @colbrydi @ati-ozgur and @innat : would you be willing to review this paper for JOSS?

**Comment by arfon** [comment]
@whedon assign @akeshavan as editor

**Comment by whedon** [comment]
OK, the editor is @akeshavan

**Comment by akeshavan** [comment]
@whedon assign @ati-ozgur as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ati-ozgur

**Comment by akeshavan** [comment]
👋 @xirdneh and @dvberkel - would you be willing to review this paper for JOSS?

**Comment by waseemsheikh** [comment]
Hi,
I was just checking the status of my paper. It's been a while and it's still not being assigned to a reviewer. Thank you for providing me an update on its status.

**Comment by dvberkel** [comment]
@akeshavan sorry, I missed your original request to be a reviewer.

I am willing and able to review this paper.

@waseemsheikh sorry, for the long delay. Things will kick into gear soon

**Comment by waseemsheikh** [comment]
Thank you very much!

**Comment by akeshavan** [comment]
@whedon add @dvberkel as reviewer

**Comment by whedon** [comment]
OK, @dvberkel is now a reviewer

**Comment by akeshavan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2016. Feel free to close this issue now!
