### ISSUE TITLE
[REVIEW]: Plonk: Smoothed particle hydrodynamics analysis and visualization with Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1884]
**Submitting author:** @dmentipl (<a href="http://orcid.org/0000-0002-5526-8798">Daniel Mentiplay</a>)
**Repository:** <a href="https://github.com/dmentipl/plonk" target ="_blank">https://github.com/dmentipl/plonk</a>
**Version:** 0.2.1
**Editor:** @dfm
**Reviewer:** @zingale, @matthewturk
**Archive:** <a href="https://doi.org/10.5281/zenodo.3554568" target="_blank">10.5281/zenodo.3554568</a>

## Status

[![status](https://joss.theoj.org/papers/e785dbbbc29d77211041264315d7d3c6/status.svg)](https://joss.theoj.org/papers/e785dbbbc29d77211041264315d7d3c6)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e785dbbbc29d77211041264315d7d3c6"><img src="https://joss.theoj.org/papers/e785dbbbc29d77211041264315d7d3c6/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e785dbbbc29d77211041264315d7d3c6/status.svg)](https://joss.theoj.org/papers/e785dbbbc29d77211041264315d7d3c6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dmentipl/plonk" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@zingale & @matthewturk, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @dfm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dmentipl/plonk">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@dmentipl) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dmentipl/plonk">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@dmentipl) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @zingale, @matthewturk it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01884/joss.01884/10.21105.joss.01884.pdf)

**Comment by zingale** [comment]
https://github.com/dmentipl/plonk/issues/2

**Comment by dmentipl** [comment]
Hi @zingale and @matthewturk. I've added to the documentation and provided a test data set at https://anaconda.org/dmentipl/plonk_example_data/.

**Comment by zingale** [comment]
My main comment was address and I was able to follow the analysis to do the example analysis and visualization.  I am happy to accept.

**Comment by matthewturk** [comment]
Same!

**Comment by dfm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01884/joss.01884/10.21105.joss.01884.pdf)

**Comment by dfm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1051/0004-6361/201322068 is OK
- 10.5281/zenodo.21703 is OK
- 10.1093/mnras/181.3.375 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1086/112164 is OK
- 10.5281/zenodo.2392268 is OK
- 10.1109/MCSE.2007.58 is OK
- 10.1071/AS07022 is OK
- 10.1016/j.jcp.2010.12.011 is OK
- 10.1017/pasa.2018.25 is OK
- 10.1088/0067-0049/192/1/9 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by dfm** [comment]
@dmentipl: Looking good! Can you make the following small changes:

- Update the scikit-image reference to the preferred citation as described here: https://scikit-image.org/
- Update the scipy and numpy references as requested here: https://www.scipy.org/citing.html
- Add the DOI for the Jupyter reference: [10.3233/978-1-61499-649-1-87](http://ebooks.iospress.nl/publication/42900)
- Add a capitalization guard to the title of {{Python and HDF5}}
- ASCL references don't render well in TeX so please add `howpublished = {Astrophysics Source Code Library}` to the entry to make it clearer
- In paragraph 3, "...a set of particles with mass" should be something like "...a set of massive particles".
- At the bottom of page 1, the sentence starting with "Tasks such as:..." is not complete. It could be combined with the previous sentence or expanded into a full sentence of its own right.
- On page 2, the sentence about yt should include more information to draw comparisons with Plonk. For example, my understanding is that yt was originally designed for grid codes with SPH support added more recently. If that's true, perhaps that sentence could include a comment about that.
- The last sentence of the main body could use more detail. Would users of Phantom SPH find Plonk useful because that's what it was originally designed to visualize? If so, that would be useful to include.

**Comment by dmentipl** [comment]
Hi @dfm, I've made all changes requested. See this [commit](https://github.com/dmentipl/plonk/commit/9b7a943e9fcd4bfc506ca5be726a4ba14b7fdb6c).

Hopefully the changes I've made to the last paragraph in the main body cover the last two points above.

@matthewturk I hope my changes convey the state of yt with regards to the demeshening.

**Comment by dfm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01884/joss.01884/10.21105.joss.01884.pdf)

**Comment by dfm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1051/0004-6361/201322068 is OK
- 10.5281/zenodo.21703 is OK
- 10.1093/mnras/181.3.375 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.3233/978-1-61499-649-1-87 is OK
- 10.1086/112164 is OK
- 10.5281/zenodo.2392268 is OK
- 10.1071/AS07022 is OK
- 10.1016/j.jcp.2010.12.011 is OK
- 10.1017/pasa.2018.25 is OK
- 10.1088/0067-0049/192/1/9 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.7717/peerj.453 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by dfm** [comment]
@dmentipl: Looks good to me! Can you update generate a new Zenodo archive with a title and author list that match the manuscript? Once you do that, report the new DOI here.

**Comment by dmentipl** [comment]
@dfm: The Zenodo archive DOI is 10.5281/zenodo.3554568

Also, I updated the Plonk version to v0.2.1.

The Zenodo archive automatically generated from the GitHub release included Matthew as an author, as he contributed a pull request adding a reference to yt in the manuscript. However, I removed him from the Zenodo archive author list. I hope that's appropriate?

**Comment by matthewturk** [comment]
Hi!  For what it's worth, I definitely think it's appropriate for me not to
be an author.

**Comment by dfm** [comment]
@dmentipl: That's right! Thanks this looks good.

**Comment by dfm** [comment]
@whedon set 10.5281/zenodo.3554568 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3554568" target="_blank">10.5281/zenodo.3554568</a> is the archive.

**Comment by dfm** [comment]
@whedon set 0.2.1 as version

**Comment by whedon** [comment]
OK. 0.2.1 is the version.

**Comment by dfm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01884/joss.01884/10.21105.joss.01884.pdf)

**Comment by dfm** [comment]
This looks good to go for me! Pinging @openjournals/joss-eics for final processing.

**Comment by dmentipl** [comment]
@dfm The proof looks good to me. Let me know if there's anything left to do.

**Comment by Kevin-Mattheus-Moerman** [comment]
I checked the paper and Zenodo archive as well and all looks good.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1051/0004-6361/201322068 is OK
- 10.5281/zenodo.21703 is OK
- 10.1093/mnras/181.3.375 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.3233/978-1-61499-649-1-87 is OK
- 10.1086/112164 is OK
- 10.5281/zenodo.2392268 is OK
- 10.1071/AS07022 is OK
- 10.1016/j.jcp.2010.12.011 is OK
- 10.1017/pasa.2018.25 is OK
- 10.1088/0067-0049/192/1/9 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.7717/peerj.453 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1136

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1136, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1201250357243981824) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1137
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01884](https://doi.org/10.21105/joss.01884)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by dfm** [comment]
@dmentipl: congrats - your paper is now published! 🎉

@zingale, @matthewturk: thanks 💯 for your constructive reviews!

**Comment by dmentipl** [comment]
Thank you @dfm for editing, and thank you @zingale and @matthewturk for reviewing!

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev this DOI is not resolving yet, can you check?

**Comment by danielskatz** [comment]
The DOI resolves for me, and the paper looks fine.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01884/status.svg)](https://doi.org/10.21105/joss.01884)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01884">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01884/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01884/status.svg
   :target: https://doi.org/10.21105/joss.01884
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01884/status.svg)](https://doi.org/10.21105/joss.01884)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
