### ISSUE TITLE
[REVIEW]: SHARPy: A dynamic aeroelastic simulation toolbox for very flexible aircraft and wind turbines

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1885]
**Submitting author:** @fonsocarre (<a href="http://orcid.org/0000-0002-8133-9481">Alfonso del Carre</a>)
**Repository:** <a href="https://github.com/ImperialCollegeLondon/sharpy" target ="_blank">https://github.com/ImperialCollegeLondon/sharpy</a>
**Version:** v1.1.0-2
**Editor:** @labarba
**Reviewer:** @petebachant, @rafmudaf
**Archive:** <a href="https://doi.org/10.5281/zenodo.3572512" target="_blank">10.5281/zenodo.3572512</a>

## Status

[![status](https://joss.theoj.org/papers/f7ccd562160f1a54f64a81e90f5d9af9/status.svg)](https://joss.theoj.org/papers/f7ccd562160f1a54f64a81e90f5d9af9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f7ccd562160f1a54f64a81e90f5d9af9"><img src="https://joss.theoj.org/papers/f7ccd562160f1a54f64a81e90f5d9af9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f7ccd562160f1a54f64a81e90f5d9af9/status.svg)](https://joss.theoj.org/papers/f7ccd562160f1a54f64a81e90f5d9af9)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ImperialCollegeLondon/sharpy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@petebachant & @rafmudaf, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @labarba know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ImperialCollegeLondon/sharpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@fonsocarre) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ImperialCollegeLondon/sharpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@fonsocarre) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @petebachant, @rafmudaf it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01885/joss.01885/10.21105.joss.01885.pdf)

**Comment by labarba** [comment]
👋  @petebachant, @rafmudaf — Thank you for agreeing to review for JOSS! This is where the action happens: work your way through the review checklist, feel free to ask questions or post comments here, and also open issues in the submission repository as needed (mentioning this issue, for a cross-link). Godspeed!

**Comment by petebachant** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01885/joss.01885/10.21105.joss.01885.pdf)

**Comment by petebachant** [comment]
I noticed a small error in one of the sample cases, but was able to confirm the functionality of the software with a different one. This submission is acceptable to me.

**Comment by rafmudaf** [comment]
After the latest updates to the build system, I was able to compile on macOS exactly as documented. I also was able to run the example cases and confirm the functionality. Very good work!

**Comment by labarba** [comment]
@petebachant, @rafmudaf —I see that both of you have checked off all the items in the review checklist. Do we have a recommendation to publish, from each of you?

**Comment by rafmudaf** [comment]
Yes, I recommend publishing.

**Comment by petebachant** [comment]
I also recommend publishing.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01885/joss.01885/10.21105.joss.01885.pdf)

**Comment by labarba** [comment]
@fonsocarre — small typo: ¶4 "These longer and much slender…" >> These longer and more slender... 

Also, please use consistent capitalization for your references: normal cap for article titles, camel case for journal or conference title. The first two references need proper capitalization of the conference (scitech forum >> SciTech Forum), and the 7th reference needs the article title in normal cap.

Once you make these small changes, please go ahead and make a new tagged release of your software, and report the version number here, then archive your software repository in Zenodo (or similar) and please report the DOI here.

**Comment by ngoiz** [comment]
Thanks @labarba, @petebachant and @rafmudaf for the review and suggestions!

We will update the JOSS submission with the above, release and share the DOI.

Thanks!

**Comment by fonsocarre** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1885 with the following error: 

 [WARNING] Could not convert image '/tmp/tex2pdf.-10d38b739308f138/686c07f142856d364b54fcb193b3058840e96c03.shtml': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : 
  
  
  
  
  
  
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA Invalid bit depth (104)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.-10d38b739308f1
38/686c07f142856d364b54fcb193b3058840e96c03.shtml (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.421 ...f142856d364b54fcb193b3058840e96c03.shtml}

Looks like we failed to compile the PDF

**Comment by fonsocarre** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01885/joss.01885/10.21105.joss.01885.pdf)

**Comment by ngoiz** [comment]
Hi all,

We have now released SHARPy v1.1 which includes all the comments from the review process. It is archived in Zenodo https://zenodo.org/record/3572512 with DOI: 10.5281/zenodo.3572512

That is the version specific DOI. The concept DOI is 10.5281/zenodo.3531965

Thanks again for your reviews and suggestions!

**Comment by fonsocarre** [comment]
I just wanted to thank you all for the constructive suggestions and the positive tone of the review process. SHARPy now is much easier to use than when we submitted. If there's some aero-related software and you need a reviewer, give me a shout, I'll be happy to contribute.

**Comment by petebachant** [comment]
Happy to do it, and thank you for releasing your work as open source!

**Comment by rafmudaf** [comment]
Likewise, I'm happy to be a part of the process. Keep up the good work!

**Comment by labarba** [comment]
@whedon set v1.1.0-2 as version

**Comment by whedon** [comment]
OK. v1.1.0-2 is the version.

**Comment by labarba** [comment]
@fonsocarre — I'm going to ask you to edit the metadata of the Zenodo deposit (no need to get new version or new DOI) so the title and author list match the JOSS paper.

**Comment by fonsocarre** [comment]
@labarba Done. It looks like it is not instantaneous, but it should show up soon.

**Comment by labarba** [comment]
Something didn't quite work ... can you double check?

**Comment by fonsocarre** [comment]
100% my fault. I _saved_, but didn't _publish_.

**Comment by labarba** [comment]
We generally ask for the _title_ of the Zenodo archive to match the title of the JOSS paper, but you didn't make that change. Do you have any strong reasons?

**Comment by fonsocarre** [comment]
I do not. It has been modified now.

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.3572512 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3572512" target="_blank">10.5281/zenodo.3572512</a> is the archive.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.2514/2.2738 is OK
- 10.2514/6.2013-1634 is OK
- 10.1017/s0001924000010952 is OK
- 10.2514/6.2011-1226 is OK
- 10.2514/6.1999-1394 is OK
- 10.2514/1.j051392 is OK
- 10.2514/1.c032464 is OK
- 10.2514/1.j050496 is OK
- 10.2514/6.2013-4745 is OK
- 10.1016/j.paerosci.2012.06.001 is OK
- 10.2514/1.j050513 is OK
- 10.2514/6.2018-1202 is OK
- 10.2514/1.j051697 is OK
- 10.2514/6.2002-1719 is OK
- 10.2514/6.2006-1638 is OK
- 10.2514/1.J052316 is OK
- 10.1016/j.ijsolstr.2011.04.012 is OK
- 10.2514/1.C032477 is OK
- 10.2514/1.47317 is OK
- 10.2514/1.27606 is OK
- 10.2514/1.g000715 is OK
- 10.2514/6.2019-2038 is OK
- 10.2514/1.J051543 is OK
- 10.2514/1.J052136 is OK
- 10.2514/6.2007-6703 is OK
- 10.1002/qj.49709841707 is OK
- https://doi.org/10.1016/j.paerosci.2018.03.006 is OK
- 10.2514/1.J058153 is OK

MISSING DOIs

- https://doi.org/10.2514/1.c032222 may be missing for title: Reduced-Order Modeling of Unsteady Aerodynamics Across Multiple Mach Regimes
- https://doi.org/10.2514/mscitech19 may be missing for title: AIAA SciTech 2019 Forum
- https://doi.org/10.2307/2003941 may be missing for title: A class of methods for solving nonlinear simultaneous equations

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1173

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1173, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1205594559473958918) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1174
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01885](https://doi.org/10.21105/joss.01885)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @fonsocarre, your JOSS paper is published! 🚀 

Huge thanks to @petebachant, @rafmudaf for reviewing this submission 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01885/status.svg)](https://doi.org/10.21105/joss.01885)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01885">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01885/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01885/status.svg
   :target: https://doi.org/10.21105/joss.01885
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01885/status.svg)](https://doi.org/10.21105/joss.01885)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
