### ISSUE TITLE
[PRE REVIEW]: Hypothesis: A new approach to property-based testing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1888]
**Submitting author:** @DRMacIver (<a href="http://orcid.org/0000-0002-8635-3223">David MacIver</a>)
**Repository:** <a href="https://github.com/HypothesisWorks/hypothesis/" target ="_blank">https://github.com/HypothesisWorks/hypothesis/</a>
**Version:** 4.44.2
**Editor:** @danielskatz
**Reviewers:** @luizirber, @djmitche

**Author instructions**

Thanks for submitting your paper to JOSS @DRMacIver. **Currently, there isn't an JOSS editor assigned** to your paper.

@DRMacIver if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01888/joss.01888/10.21105.joss.01888.pdf)

**Comment by labarba** [comment]
👋 @danielskatz — This submission falls in the general area of software engineering, and I think you could handle it as editor? 
*Hypothesis: A new approach to property-based testing*
https://github.com/HypothesisWorks/hypothesis/

**Comment by luizirber** [comment]
I was going to volunteer as a reviewer, but I skimmed the paper and it cites hypothesis-bio as an example (and I'm involved in the development). Is it a conflict of interest?
 https://github.com/HypothesisWorks/hypothesis/blob/master/paper.md

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@luizirber - no, you are a stakeholder in some sense, which is good - I'll add you as a reviewer and try to find a second next.

**Comment by danielskatz** [comment]
@whedon assign @luizirber as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @luizirber

**Comment by danielskatz** [comment]
👋 @DRMacIver - Can you suggest some additional reviewers? From [this list](https://bit.ly/joss-reviewers) perhaps?

**Comment by DRMacIver** [comment]
Sure!

Based solely on the process of looking for "testing" in the topics and "Python" in the primary language and excluding @Zac-HD because he's one of the authors, the following seem to be the valid choices of reviewers from that spreadsheet: @ctb @djmitche @camillescott 

I don't believe I know any of them personally, and based on looking at their github profiles it doesn't look like any of them currently use Hypothesis, so I don't have any criteria I'd use to narrow it down further than that and I guess any of those three who are interested would be good choices.

**Comment by ctb** [comment]
someone else in my lab (@luizirber) I believe has experience. pinging him now.

**Comment by ctb** [comment]
Oh. He's already assigned.  Well, @camillescott and @luizirber and I are all in the same lab so ...maybe we should only pick one? :)

**Comment by danielskatz** [comment]
👋 @djmitche - would you be willing to review this for JOSS?

**Comment by Zac-HD** [comment]
👋 everyone!  Super excited to go from JOSS admirer to JOSS author 😁 

The issue tags seem a little weird - we do have all those languages in the repo, but Hypothesis is a pure-Python library.  For later stages, we've been archiving Hypothesis at [10.5281/zenodo.1412597](https://doi.org/10.5281/zenodo.1412597)

**Comment by danielskatz** [comment]
The archive isn't needed until later, and there may be changes that needed to be made and put in a new release/archive...

**Comment by Zac-HD** [comment]
No worries, [we automated the release process](https://hypothesis.works/articles/continuous-releases/) years ago, so that's as easy as  "approve and merge a PR".

**Comment by djmitche** [comment]
> wave @djmitche - would you be willing to review this for JOSS?

I would.  I'm a very casual user of hypothesis, so I'm excited to see it in JOSS.

**Comment by danielskatz** [comment]
Thanks very much - I'll add you and we can start the review process

**Comment by danielskatz** [comment]
@whedon add @djmitche as reviewer

**Comment by whedon** [comment]
OK, @djmitche is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1891. Feel free to close this issue now!
