### ISSUE TITLE
[PRE REVIEW]: mlr3: A modern object-oriented machine learning framework in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1893]
**Submitting author:** @mllg (<a href="http://orcid.org/0000-0001-9754-0393">Michel Lang</a>)
**Repository:** <a href="https://github.com/mlr-org/mlr3" target ="_blank">https://github.com/mlr-org/mlr3</a>
**Version:** v0.1.4
**Editor:** @terrytangyuan
**Reviewers:** @nhejazi , @osorensen

**Author instructions**

Thanks for submitting your paper to JOSS @mllg. **Currently, there isn't an JOSS editor assigned** to your paper.

@mllg if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1893 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1893 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/lib/whedon.rb:114:in `editor': undefined method `[]' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/lib/whedon/compilers.rb:113:in `pdf_from_markdown'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/lib/whedon/compilers.rb:13:in `generate_pdf'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/bin/whedon:56:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.18637/jss.v028.i05 is OK
- 10.5281/zenodo.3541506 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@openjournals/dev -- help with compilation error here?

**Comment by labarba** [comment]
@terrytangyuan 👋  — The author suggested you as handling editor. Can you take it?

**Comment by terrytangyuan** [comment]
@whedon assign @terrytangyuan as editor

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1893 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01893/joss.01893/10.21105.joss.01893.pdf)

**Comment by mllg** [comment]
Note: We extended the funding part in section "Acknowledgments", fixed a typo, and added a DOI for the Weka reference.

**Comment by terrytangyuan** [comment]
@mllg Thanks for the update. If you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Comment by mllg** [comment]
After skimming through the list filtering for R as primary programming language and machine learning as topic, these seem to be potential reviewers (in no particular order):

@robohyun66 
@osorensen
@expectopatronum 
@nhejazi

**Comment by terrytangyuan** [comment]
👋 Hi @robohyun66 @osorensen @expectopatronum @nhejazi, if you would like to review this submission, please let us know here and we need at least two reviewers!

**Comment by nhejazi** [comment]
Looks quite interesting! Happy to provide a review if helpful.

**Comment by mllg** [comment]
I took the opportunity to make one last minor change to the article. I'm wondering if I can also trigger the bot to re-create the article proof?

@whedon generate pdf from branch joss

**Comment by terrytangyuan** [comment]
@mllg There will be plenty of opportunities to make changes through the process so don’t worry about generating the pdf for now. You should push your changes to main branch though.

**Comment by osorensen** [comment]
Yes, happy to review.

**Comment by terrytangyuan** [comment]
@whedon assign @osorensen as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @osorensen

**Comment by terrytangyuan** [comment]
@whedon assign @nhejazi  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @nhejazi

**Comment by terrytangyuan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1903. Feel free to close this issue now!

**Comment by terrytangyuan** [comment]
@whedon add @osorensen as reviewer

**Comment by whedon** [comment]
OK, @osorensen is now a reviewer

**Comment by mllg** [comment]
I've moved the paper to the master branch.

**Comment by terrytangyuan** [comment]
Thanks everyone for the quick responses. Please head over to #1903 for the review!
