### ISSUE TITLE
[PRE REVIEW]: Dryft: A Python and MATLAB package to correct drifting ground reaction force signals during treadmill running

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1894]
**Submitting author:** @alcantarar (<a href="http://orcid.org/0000-0002-8539-711X">Ryan Alcantara</a>)
**Repository:** <a href="https://github.com/alcantarar/dryft" target ="_blank">https://github.com/alcantarar/dryft</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @agricolab, @DARSakthi, @mwptrsn

**Author instructions**

Thanks for submitting your paper to JOSS @alcantarar. **Currently, there isn't an JOSS editor assigned** to your paper.

@alcantarar if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1894 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/lib/whedon.rb:114:in `editor': undefined method `[]' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/lib/whedon/compilers.rb:113:in `pdf_from_markdown'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/lib/whedon/compilers.rb:13:in `generate_pdf'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/bin/whedon:56:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/j.medengphy.2006.04.002 may be missing for title: Testing of a tri-instrumented-treadmill unit for kinetic analysis of locomotion tasks in static and dynamic loading conditions
- https://doi.org/10.1016/j.medengphy.2015.03.018 may be missing for title: A comprehensive protocol to test instrumented treadmills

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1894 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/lib/whedon.rb:114:in `editor': undefined method `[]' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/lib/whedon/compilers.rb:113:in `pdf_from_markdown'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/lib/whedon/compilers.rb:13:in `generate_pdf'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/bin/whedon:56:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd1f92b00da7/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by alcantarar** [comment]
:wave: @labarba , I tested the whedon paper preview and it compiled, do you have info on what this error is? I've also added DOIs for the references in the latest commit.

**Comment by labarba** [comment]
@openjournals/dev -- we're experiencing some compilation issues. Help?

**Comment by labarba** [comment]
@Kevin-Mattheus-Moerman -- Could you handle this submission as editor?
**Dryft: A Python and MATLAB package to correct drifting ground reaction force signals during treadmill running**
https://github.com/alcantarar/dryft

**Comment by alcantarar** [comment]
Looking through the latest additions to the joss_reviewers google sheet, I'd like to recommend the following folks who have matlab/python experience: 
- ulvgard
- agricolab
- DARSakthi
- mwptrsn

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01894/joss.01894/10.21105.joss.01894.pdf)

**Comment by arfon** [comment]
> @openjournals/dev -- we're experiencing some compilation issues. Help?

I accidentally broke Whedon last night. Fixed now.

**Comment by agricolab** [comment]
Would be interested and available for review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @agricolab as reviewer

**Comment by whedon** [comment]
OK, @agricolab is now a reviewer

**Comment by DARSakthi** [comment]
I also would be willing to review the paper

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @DARSakthi as reviewer

**Comment by whedon** [comment]
OK, @DARSakthi is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@danasolav would somebody from the Biomechatronics group like to review this you think?

**Comment by Kevin-Mattheus-Moerman** [comment]
@moorepants are you interested in reviewing this one?

**Comment by mwptrsn** [comment]
I’m happy to review if another is needed.

**Comment by DARSakthi** [comment]
@Kevin-Mattheus-Moerman I believe you are responsible for initiating the actual review using Whedon, as per https://joss.readthedocs.io/en/latest/whedon.html#starting-the-review 
Are we waiting for other reviewers?

**Comment by Kevin-Mattheus-Moerman** [comment]
@DARSakthi yes. However I'm hoping to attract a(nother) reviewer with biomechanics/force plate experience

**Comment by Kevin-Mattheus-Moerman** [comment]
@modenaxe @demotu @jimmyDunne @anmuller @Ipuch @cpontonn would you be interested in reviewing this work for JOSS?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @mwptrsn as reviewer

**Comment by whedon** [comment]
OK, @mwptrsn is now a reviewer

**Comment by modenaxe** [comment]
Hi @Kevin-Mattheus-Moerman I will have to pass this one, I am afraid.

**Comment by cpontonn** [comment]
Hi @Kevin-Mattheus-Moerman I'm sorry but I am under water now and too busy  doing this review in a correct manner. Next time !

**Comment by ulvgard** [comment]
What is the deadline for submitting a review?

**Comment by Kevin-Mattheus-Moerman** [comment]
@ulvgard there is no fixed deadline but we like to suggest 2 weeks.

**Comment by jimmyDunne** [comment]
I won't be able to review, busy time of year. Thanks, @Kevin-Mattheus-Moerman .

**Comment by alcantarar** [comment]
@Kevin-Mattheus-Moerman how many reviewers would you like in total? Unfortunately, I don't know many running biomechanists that are on GitHub. :disappointed:

**Comment by SjoerdBruijn** [comment]
Sorry, I cannot, way too busy now. See my message on twitter to you for alternative reviewers. :)

**Comment by Kevin-Mattheus-Moerman** [comment]
@alcantarar I tend to aim for 3 reviewers but here I was hoping to add a gait biomechanics person too. I think I can start the review though as we have a good set of reviewers now, and to avoid delays. If I do find a gait biomechanics person I'll add them at a later stage.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1910. Feel free to close this issue now!
