### ISSUE TITLE
@whedon commands

### ISSUE THREAD

**Issue by CostRagno** [openjournals/joss-reviews#1898]
STOP STOP STOP STOP STOP
STOP STOP STOP STOP STOP
👇 ================================== 👇

Issues in this repository are automatically generated by the journal submission system. DO NOT FILE ISSUES HERE.

If you have a question about JOSS then please open an issue on the main JOSS repository: https://github.com/openjournals/joss

☝ ================================== ☝

THANKS FOR NOT OPENING AN ISSUE HERE

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1898 with the following error: 

 Can't find any papers to compile :-(
