### ISSUE TITLE
[PRE REVIEW]: c14bazAAR: An R package for downloading and preparing C14 dates from different source databases

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1899]
**Submitting author:** @nevrome (<a href="http://orcid.org/0000-0003-3448-5715">Clemens Schmid</a>)
**Repository:** <a href="https://github.com/ropensci/c14bazAAR" target ="_blank">https://github.com/ropensci/c14bazAAR</a>
**Version:** 1.1.0
**Editor:** @arfon
**Reviewers:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @nevrome. **Currently, there isn't an JOSS editor assigned** to your paper.

@nevrome if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1899 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1899 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e13363a737a/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e13363a737a/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e13363a737a/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@nevrome  — please provide the software repository (GitHub, GitLab, Bitbucked) here and I will update the metadata of this Pre-Review.

**Comment by labarba** [comment]
OK, I have found it. You provided the archive DOI (https://doi.org/10.17605/OSF.IO/3DS6A) pointing to your OSF project, but we needed the URL of the GitHub repo: https://github.com/ropensci/c14bazAAR

Has this submission gone through the rOpenSci review?

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.4324/9781315421216 is OK
- 10.2307/2799190 is OK
- 10.14324/000.ds.1575442 is OK
- 10.1111/j.1467-9876.2008.00623.x is OK
- 10.32614/RJ-2018-009 is OK
- 10.7910/DVN/NJLNRJ is OK
- 10.1177/1059712319860842 is OK
- 10.12766/jna.2012.65 is OK
- 10.4312/dp.36.2 is OK
- 10.1016/j.jas.2011.08.008 is OK
- 10.1371/journal.pbio.0030410 is OK
- 10.1371/journal.pone.0087854 is OK
- 10.1371/journal.pone.0113672 is OK
- 10.2458/azu_js_rc.55.16385 is OK
- \\url{10.1073/pnas.1715336115} is OK
- 10.5281/zenodo.61113 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by nevrome** [comment]
@labarba Thank you for working with this submission! 

It did indeed go through the ROpenSci review: https://github.com/ropensci/software-review/issues/333

There I was [specifically asked](https://github.com/ropensci/software-review/issues/333#issuecomment-531599658) to submit with the archive DOI:

> Submit to JOSS using the Zenodo DOI. They will tag it for expedited review.

Maybe they should update their template?

**Comment by labarba** [comment]
@arfon Can you clarify this issue about submissions coming from rOpenSci?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01899/joss.01899/10.21105.joss.01899.pdf)

**Comment by arfon** [comment]
> @arfon Can you clarify this issue about submissions coming from rOpenSci?

This is incorrect. We can use the Zenodo DOI for the submission once we're ready to accept, but we need authors to submit to JOSS using the standard repository address (https://github.com/ropensci/c14bazAAR).

I've asked for guidance on how to fix this in https://github.com/ropensci/software-review/issues/333#issuecomment-554874000

**Comment by nevrome** [comment]
@labarba What's the procedure to apply some small changes to the proof? Resubmission?

**Comment by arfon** [comment]
@nevrome - please just make the changes to your `paper.md` and ask Whedon to recompile here with `@whedon generate pdf`

**Comment by nevrome** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01899/joss.01899/10.21105.joss.01899.pdf)

**Comment by nevrome** [comment]
@labarba The text is fine now. What are the next steps?

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1914. Feel free to close this issue now!
