### ISSUE TITLE
[REVIEW]: plotrr: Functions for making visual exploratory data analysis with nested data easier. Edit

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#190]
**Submitting author:** @cdcrabtree (<a href="http://orcid.org/0000-0001-5144-8671">Charles Crabtree</a>)
**Repository:** <a href="https://github.com/cdcrabtree/plotrr" target ="_blank">https://github.com/cdcrabtree/plotrr</a>
**Version:** v0.2.0
**Editor:** @pjotrp
**Reviewer:** @kbroman
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.344900" target="_blank">10.5281/zenodo.344900</a>

## Status

[![status](http://joss.theoj.org/papers/4f707062d9621de3b7009a2ad62cc8cc/status.svg)](http://joss.theoj.org/papers/4f707062d9621de3b7009a2ad62cc8cc)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/4f707062d9621de3b7009a2ad62cc8cc"><img src="http://joss.theoj.org/papers/4f707062d9621de3b7009a2ad62cc8cc/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/4f707062d9621de3b7009a2ad62cc8cc/status.svg)](http://joss.theoj.org/papers/4f707062d9621de3b7009a2ad62cc8cc)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/cdcrabtree/plotrr" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cdcrabtree/plotrr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.2.0)?
- [x] **Authorship:** Has the submitting author (@cdcrabtree) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @kbroman it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by pjotrp** [comment]
@whedon assign @kbroman as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kbroman

**Comment by kbroman** [comment]
I sent @cdcrabtree a pull request with several small changes, plus added a couple of issues with a few other minor suggestions.

Removing `\dontrun{}` from the examples would make it so `R CMD check` would give at least the simplest tests, of whether the functions can run without giving an error.

It would be great if the authors could add a formal [vignette](http://kbroman.org/pkg_primer/pages/vignettes.html) to give a bit more detail on the use of the functions, and maybe some discussion of interpretation. But the ReadMe file and the examples in the function documentation are probably sufficient.

The [CRAN](https://cran.r-project.org) requirement on providing license information within an R package is a bit odd, in that the `LICENSE` file just says year and copyright holder and doesn't mention the license. It might be good to add another `License.md` file that is more explicit about the MIT license, and then add that to `.Rbuildignore` so that it doesn't get included in the package file sent to CRAN.

**Comment by cdcrabtree** [comment]
@kbroman Thanks for the helpful suggestions and changes. We've just finished going through and incorporating your pull request, addressing the issues, and addressing your comments here. We've updated the version number of the software to reflect these changes and creates a NEWS file that enumerates them. Specific to your comments here, we've removed all instances of `dontrun{}`, added a vignette that focuses on the core functions and explains a bit more the intuition behind why researchers might want to use them, and created a `License.md` file. Finally, we've added a note to the README that acknowledges your help with this package.

One thing that I wanted to add here is that our references do not have DOIs, unfortunately. Several are books, which were not assigned a DOI. The article should have one, but the publisher hasn't assigned one yet.

Please let us know if there are any other issues that we can address.

Thanks again for the very helpful comments.

**Comment by kbroman** [comment]
Looks great, @cdcrabtree!

**Comment by cdcrabtree** [comment]
Thanks, @kbroman! Is there anything else that we need to do at this point?

**Comment by arfon** [comment]
@cdcrabtree - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by cdcrabtree** [comment]
@arfon Here is the Zenodo DOI: 10.5281/zenodo.344900. We plan on making future updates to this package. Is there a way of updating the DOI as we move forward? Or is it always pegged to the reviewed software release? Thanks!

**Comment by pjotrp** [comment]
It is pegged. One advantage is that you can submit a new paper on a future release.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.344900 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.344900" target="_blank">10.5281/zenodo.344900</a> is the archive.

**Comment by arfon** [comment]
@cdcrabtree - could you move the references you currently have in the `paper.md` file into a `paper.bib` file and cite them directly please? (You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html))

**Comment by sagetrey** [comment]
Unsubscribe

**Comment by cdcrabtree** [comment]
@arfon We've now done that.

**Comment by arfon** [comment]
Thanks for your review @kbroman and editing this submission @pjotrp ✨ 
@cdcrabtree your paper is now accepted into JOSS and your paper DOI is http://dx.doi.org/10.21105/joss.00190 ⚡️ 🚀 💥

**Comment by cdcrabtree** [comment]
Thanks @arfon, @pjotrp, and @kbroman for a great submission experience.

@arfon, if I can help by reviewing something in the future, please let me know. Thanks.

**Comment by arfon** [comment]
> @arfon, if I can help by reviewing something in the future, please let me know. Thanks.

Thanks @cdcrabtree. Please could you add yourself to this file? That way we'll know to call on you sometime in the future: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv
