### ISSUE TITLE
[PRE REVIEW]: OrNet - a Python Toolkit to Model the Diffuse Structure of Organelles as Social Networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1902]
**Submitting author:** @Marcdh3 (<a href="http://orcid.org/0000-0002-9380-3181">Marcus Hill</a>)
**Repository:** <a href="https://github.com/quinngroup/ornet-JOSS" target ="_blank">https://github.com/quinngroup/ornet-JOSS</a>
**Version:** v0.1
**Editor:** @akeshavan
**Reviewers:** @serine, @vc1492a

**Author instructions**

Thanks for submitting your paper to JOSS @Marcdh3. **Currently, there isn't an JOSS editor assigned** to your paper.

@Marcdh3 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1101/522763 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01902/joss.01902/10.21105.joss.01902.pdf)

**Comment by kthyng** [comment]
Hi @marcdh3! Can you look through this list and suggest some appropriate reviewers for your submission? It helps to have about 5 suggestions if possible.

Please fix the citations in your paper; you can find more details here: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by kthyng** [comment]
Hi @akeshavan and welcome onboard! Would you be interested in editing this?

**Comment by Marcdh3** [comment]
Hi @kthyng! Thank you for the quick response. Here are my reviewer suggestions:

- serine 
- sonal-raj
- vc1492a
- camillescott
- nidhog

Also, I will be working on the citations now, and I'll update you once they are fixed.

**Comment by Marcdh3** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01902/joss.01902/10.21105.joss.01902.pdf)

**Comment by Marcdh3** [comment]
@kthyng I believe we fixed the citations. Please let us know if there is anything else needing to be fixed.

**Comment by kthyng** [comment]
@whedon add @akeshavan as editor

**Comment by kthyng** [comment]
(@akeshavan approved by email)

**Comment by akeshavan** [comment]
:wave: @camillescott and @nidhog: would you be willing to review this paper for JOSS?

**Comment by kthyng** [comment]
@whedon add @akeshavan as editor

**Comment by kthyng** [comment]
@arfon is @akeshavan properly in the system? Can't seem to add her as editor here.

**Comment by arfon** [comment]
@whedon assign @akeshavan as editor

**Comment by whedon** [comment]
OK, the editor is @akeshavan

**Comment by arfon** [comment]
> @whedon add @akeshavan as editor

@kthyng it's `assign` not `add` for the editor. Sorry for any confusion caused.

**Comment by kthyng** [comment]
@arfon Oh my goodness. Sorry about that! I almost always copy and paste the whedon commands to be sure they're correct but apparently these times I was sure I was correct! :) Thanks for helping.

**Comment by arfon** [comment]
> @arfon Oh my goodness. Sorry about that! I almost always copy and paste the whedon commands to be sure they're correct but apparently these times I was sure I was correct! :) Thanks for helping.

😁no worries!

**Comment by akeshavan** [comment]
👋 @serine, @sonal-raj, and @vc1492a -- would you be willing to review this paper for JOSS?

**Comment by serine** [comment]
This looks interesting. I should be able to take a look at it next week, if I can get a hold of raw/example data. Image analysis isn't my field so I wouldn't know where to source the data from. 

One super minor thing, but it feels rather weird to call the repository (repo) `ornet-JOSS`. I'm assuming **JOSS** suffix in the name referres to the fact that the tool will be submitted to JOSS for review? If this is the case I think it would be much better to drop **JOSS** from the repo name, while this is still early days for the repo. 

Usually repo's name hints / describes what the content of the repo is and I'd say for a lot of the source code the repo name usually the name of the tool/library. JOSS `paper.md` is a very small part of the repo.

Just think about establishing a name for your tool and advertising it to other people.

Cheers

**Comment by akeshavan** [comment]
@whedon assign @serine as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @serine

**Comment by vc1492a** [comment]
@akeshavan thanks for reaching out about the opportunity to review this work. I'll be taking a long vacation in about a week's time and will not be returning until close to the end of January. If that's all right with you and the authors, I'm happy to review this work. However I'll be largely unavailable during that time due to travel. 

The work is interesting although it's not typically a field I'm involved in, so my contributions for review in regards to it's utility in the field will be very limited. I can however review for code organization, completeness, documentation suitability, etc. In line with @serine, I'd need to get a hold of some example data in order to review this work effectively - ideally more than one sample in which to test. 

Hope this helps!

**Comment by akeshavan** [comment]
Thanks @vc1492a ! It's holiday season, so I understand that we all will be taking time off. 

@Marcdh3 could you upload some raw/example data so that the reviewers can take a look?

**Comment by akeshavan** [comment]
@whedon add @vc1492a as reviewer

**Comment by whedon** [comment]
OK, @vc1492a is now a reviewer

**Comment by Marcdh3** [comment]
I've uploaded some videos that we've been using in the "samples" directory. Inside of that directory are three sub-directories labeled "control", "llo", and "mdivi". Each sub-directory contains a video (.mov) and an initial segmentation mask (.vtk). The sub-directories correspond to video data of HeLa cells that were either in the control group, exposed to pre-forming toxin listeri-olysin O (LLO), or exposed to mitochondria division inhibitor-1 (mdivi-1). These videos should do a good job illustrating the morphology changes of mitochondria under different conditions.

**Comment by akeshavan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1983. Feel free to close this issue now!
