### ISSUE TITLE
[PRE REVIEW]: alignparse: A Python package for parsing complex features from high-throughput long-read sequencing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1905]
**Submitting author:** @jbloom (<a href="http://orcid.org/0000-0003-1267-3408">Jesse Bloom</a>)
**Repository:** <a href="https://github.com/jbloomlab/alignparse" target ="_blank">https://github.com/jbloomlab/alignparse</a>
**Version:** 0.1.0
**Editor:** @will-rowe
**Reviewers:** @bede, @afrubin

**Author instructions**

Thanks for submitting your paper to JOSS @jbloom. **Currently, there isn't an JOSS editor assigned** to your paper.

@jbloom if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.gpb.2015.08.002 is OK
- 10.1186/s12864-018-4611-3 is OK
- 10.1186/1471-2105-13-238 is OK
- 10.1093/bioinformatics/bty191 is OK
- 10.1128/JVI.00500-19 is OK
- 10.1038/s41588-018-0122-z is OK
- 10.1038/nmeth.3027 is OK
- 10.1038/nmeth.1416 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
:wave: @will-rowe - the submitting authors suggested you as the handling editor - would you be willing to take this one?

**Comment by whedon** [comment]
PDF failed to compile for issue #1905 with the following error: 

 Error producing PDF.
! TeX capacity exceeded, sorry [input stack size=5000].
\reserved@a ->\def \reserved@a 
                               *{\ttl@assign@i {\@tempskipb }}\reserved@a 
l.406 ...arse works}}\label{how-alignparse-works}}

Looks like we failed to compile the PDF

**Comment by khdusenbury** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01905/joss.01905/10.21105.joss.01905.pdf)

**Comment by will-rowe** [comment]
Sounds cool - I'd be happy to.

**Comment by will-rowe** [comment]
@whedon assign @will-rowe as editor

**Comment by whedon** [comment]
OK, the editor is @will-rowe

**Comment by will-rowe** [comment]
Hey @bede - would you be willing to review this?

**Comment by bede** [comment]
@will-rowe Yes, happy to review.

**Comment by will-rowe** [comment]
awesome - thanks @bede

**Comment by will-rowe** [comment]
@whedon assign @bede as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @bede

**Comment by bede** [comment]
@will-rowe I await you hitting the `start review` button : )

**Comment by will-rowe** [comment]
ha - give me a bit longer, just chasing up a second reviewer

**Comment by jbloom** [comment]
@will-rowe: Thanks so much for getting this started quickly. If you still want us to suggest additional reviewers, here are a few possibilities *not* on the JOSS list:
- [Martin Kircher](https://www.bihealth.org/en/research/research-groups/martin-kircher/)
- [Ben Murrell](https://ki.se/en/mtc/benjamin-murrell-research-project)

And a suggestion from the JOSS list is `afrubin`.

**Comment by will-rowe** [comment]
Thanks @jbloom. The other reviewer I was thinking can't manage this at the moment, so let's try some of your suggestions!

**Comment by will-rowe** [comment]
Hi @afrubin - would be able to review this submission?

**Comment by afrubin** [comment]
@will-rowe Sorry for the late reply to this. I'm happy to review if you still need someone.

**Comment by will-rowe** [comment]
Great - thank you @afrubin!

**Comment by will-rowe** [comment]
@whedon add @afrubin as reviewer

**Comment by whedon** [comment]
OK, @afrubin is now a reviewer

**Comment by will-rowe** [comment]
Let's move this into review!

**Comment by will-rowe** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1915. Feel free to close this issue now!
