### ISSUE TITLE
[PRE REVIEW]: CaPS: Casimir Effect in the Plane-Sphere Geometry

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1907]
**Submitting author:** @michael-hartmann (<a href="http://orcid.org/0000-0002-9245-8582">Michael Hartmann</a>)
**Repository:** <a href="https://github.com/michael-hartmann/caps/" target ="_blank">https://github.com/michael-hartmann/caps/</a>
**Version:** 0.5
**Editor:** @danielskatz
**Reviewers:** @eschnett, @jwuttke

**Author instructions**

Thanks for submitting your paper to JOSS @michael-hartmann. **Currently, there isn't an JOSS editor assigned** to your paper.

@michael-hartmann if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1093/acprof:oso/9780199238743.001.0001 is OK
- 10.1103/PhysRevLett.109.160403 is OK
- 10.1088/1367-2630/8/10/243 is OK
- 10.1103/PhysRevLett.99.170403 is OK
- 10.1007/s10915-013-9714-z is OK
- 10.21105/joss.01167 is OK
- 10.1103/PhysRevE.91.033203 is OK
- 10.1103/PhysRevE.92.042125 is OK
- 10.1103/PhysRevLett.119.043901 is OK
- 10.1088/1402-4896/aae34e is OK
- 10.1103/PhysRevLett.96.080403 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01907/joss.01907/10.21105.joss.01907.pdf)

**Comment by kthyng** [comment]
Hi @michael-hartmann and thanks for your submission. Please add to your paper to [include](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain):

> A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.

and possibly also

> A clear Statement of Need that illustrates the research purpose of the software

which is hard to discern from this outside perspective currently. We want to see a clear research use stated clearly.

**Comment by danielskatz** [comment]
I'm going to mark this as paused for now - @michael-hartmann, please let us know when you have addressed the previous points.

**Comment by michael-hartmann** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01907/joss.01907/10.21105.joss.01907.pdf)

**Comment by michael-hartmann** [comment]
@kthyng, @danielskatz 

Thank you for your suggestions.

We have addressed the previous points by (i) extending the introduction for a non-specific audience, and (ii) adding references to experiments that have used data generated with our software.

We hope that the review can now continue. :-)

**Comment by michael-hartmann** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.crhy.2011.05.004 is OK
- 10.1103/PhysRevLett.87.211801 is OK
- 10.1103/PhysRevB.63.033402 is OK
- 10.1093/acprof:oso/9780199238743.001.0001 is OK
- 10.1016/j.crhy.2012.04.008 is OK
- 10.1103/PhysRevLett.109.160403 is OK
- 10.1088/1367-2630/8/10/243 is OK
- 10.1103/PhysRevLett.99.170403 is OK
- 10.1007/s10915-013-9714-z is OK
- 10.21105/joss.01167 is OK
- 10.1103/PhysRevE.91.033203 is OK
- 10.1103/PhysRevE.92.042125 is OK
- 10.1103/PhysRevLett.119.043901 is OK
- 10.1088/1402-4896/aae34e is OK
- 10.1103/PhysRevLett.96.080403 is OK
- 10.1103/PhysRevB.100.081406 is OK
- 10.1103/PhysRevA.100.052511 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
Sorry for the delay in getting back to this - our rotating associate editor-in-chief system showed some flaws over the holidays

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@michael-hartmann - do you have any suggestions for potential reviewers? If so, please mention them here in this thread, without @-tagging them. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission. Please take a look and see if you see any potentially-applicable reviewers.

**Comment by michael-hartmann** [comment]
@danielskatz Thank you for your reply.

I had a look at the list of JOSS reviewers and think jochym and jwuttke are good candidates. Both have a background in theoretical physics, experience in scattering (might be helpful), and listed C among their programming languages.

**Comment by danielskatz** [comment]
👋 @jochym and @jwuffke - Would either (or ideally) both of you be willing to review this for JOSS?

**Comment by danielskatz** [comment]
👋 @jwuttke - Would you be willing to review this for JOSS?

**Comment by danielskatz** [comment]
👋 @eschnett & @stevenrbrandt - would either of you be willing to review this, or have suggestions for others who might?

**Comment by jwuttke** [comment]
What are reviewers supposed to do?

**Comment by danielskatz** [comment]
Sorry, I thought you were familiar with JOSS - see https://joss.readthedocs.io/en/latest/reviewer_guidelines.html for general info about the reviewing process, and https://joss.readthedocs.io/en/latest/review_criteria.html for the specific review criteria.  In brief, a JOSS review is of the short paper and the software repository, and it is open and collaborative, seeking to improve the paper and software to the point where they can be accepted.

**Comment by eschnett** [comment]
@danielskatz I accept.

**Comment by danielskatz** [comment]
@jwuttke - are you willing to be a reviewer for this?

**Comment by danielskatz** [comment]
@whedon assign @eschnett as reviewer

**Comment by whedon** [comment]
OK, @eschnett is now a reviewer

**Comment by danielskatz** [comment]
Thanks @eschnett - we'll start the review once we get another reviewer assigned

**Comment by jwuttke** [comment]
> @jwuttke - are you willing to be a reviewer for this?

ok, I'll give it a try

**Comment by jwuttke** [comment]
will we get some more instructions, or shall we just start, following the guidelines linked above?

**Comment by danielskatz** [comment]
I'll add you, then create an issue for the review, which will have instructions

**Comment by danielskatz** [comment]
@whedon add @jwuttke as reviewer

**Comment by whedon** [comment]
OK, @jwuttke is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2011. Feel free to close this issue now!
