### ISSUE TITLE
[PRE REVIEW]: profileR: An R package for profile analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1908]
**Submitting author:** @cddesja (<a href="http://orcid.org/0000-0002-8234-9665">Christopher Desjardins</a>)
**Repository:** <a href="https://github.com/cddesja/profileR" target ="_blank">https://github.com/cddesja/profileR</a>
**Version:** 0.3-5
**Editor:** @marcosvital
**Reviewers:** @wjakethompson, @jrosen48, @markhwhiteii 

**Author instructions**

Thanks for submitting your paper to JOSS @cddesja. **Currently, there isn't an JOSS editor assigned** to your paper.

@cddesja if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1037//1082-989X.7.4.468 is OK

MISSING DOIs

- https://doi.org/10.1080/00273170903187665 may be missing for title: Factor Analytic Modeling of Within Person Variation in Score Profiles
- https://doi.org/10.1201/b20498 may be missing for title: Handbook of educational measurement and psychometrics using R

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01908/joss.01908/10.21105.joss.01908.pdf)

**Comment by kthyng** [comment]
Hi @cddesja and thanks for your submission! Our system hasn't found an open source license and that is a requirement for being part of JOSS. Do you want to add one?

**Comment by kthyng** [comment]
Hi @marcosvital! What do you think about this being your first JOSS submission as editor?

**Comment by cddesja** [comment]
Hi,

Sorry, yes. The software is GPL v3. Where should I add this?

**Comment by cddesja** [comment]
@rmhogervorst, @russellpierce, @lebebr01, @wjakethompson,@markhwhiteii, @bradweiner, @jrosen48, and @amarkos could all be suitable reviewers.

**Comment by markhwhiteii** [comment]
I'm not an expert in this type of statistical analysis, but it seems related enough to work I've done that I could review. This would be my first time reviewing—is there a guide on the typical type of review process?

**Comment by cddesja** [comment]
Adding @okanbulut as he's the co-author so he can follow the review.

**Comment by jrosen48** [comment]
Hi, I'd be happy to review this. I have experience with this type of analysis (and developing [software](https://github.com/data-edu/tidyLPA) for it) and think/hope I'd be able to contribute.

**Comment by kthyng** [comment]
> Hi, Sorry, yes. The software is GPL v3. Where should I add this?

@cddesja See details about the license here: https://joss.readthedocs.io/en/latest/review_criteria.html#software-license

**Comment by kthyng** [comment]
@marcosvital confirmed by email

**Comment by kthyng** [comment]
@whedon assign @marcosvital as editor

**Comment by whedon** [comment]
OK, the editor is @marcosvital

**Comment by wjakethompson** [comment]
I would also be happy to review. I haven't worked with these models specifically, but I've done some work on closely related models, also in R.

**Comment by marcosvital** [comment]
Hi, @cddesja , I'm Marcos, and I'll be the editor of your submission.

Since we already have three reviewers, we are almost ready to move from pre-review to review, so please confirm if everything is okay with the article proof and we'll move on.

@wjakethompson , @jrosen48 and @markhwhiteii , thank you all for accepting review this submission. You will all get the detailed reviewing instructions when we move to the next phase, and please fell free to call me anytime if you have any questions.

**Comment by marcosvital** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01908/joss.01908/10.21105.joss.01908.pdf)

**Comment by marcosvital** [comment]
@whedon add @wjakethompson as reviewer

**Comment by whedon** [comment]
OK, @wjakethompson is now a reviewer

**Comment by marcosvital** [comment]
@whedon add @jrosen48 as reviewer

**Comment by whedon** [comment]
OK, @jrosen48 is now a reviewer

**Comment by marcosvital** [comment]
@whedon add @markhwhiteii  as reviewer

**Comment by whedon** [comment]
OK, @markhwhiteii  is now a reviewer

**Comment by cddesja** [comment]
Here's a couple strange things in the PDF.

- It looks like the paragraph below the first Figure no longer says Figure
1.
- Right before the second Figure it should say (see Figure 2).

**Comment by marcosvital** [comment]
Hi, @cddesja , and sorry for the delayed reply. 

The problem with the figure captions is probably easy to solve: you should try to insert the figure in a single separated line in the md file, with the caption inside brackets.

Take a look at this example: https://raw.githubusercontent.com/pyvista/pyvista/master/joss/paper.md

That will generate this: https://github.com/pyvista/pyvista/blob/master/joss/paper.md

**Comment by marcosvital** [comment]
Reviewers, as soon as the proof gets ready, we are ready to begin with the reviewing process. Please take a look at the guidelines if it's your first time reviewing for JOSS:
 
https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by cddesja** [comment]
@marcosvital <https://github.com/marcosvital>, the figures should now be
fixed and the proof should be ready.

**Comment by marcosvital** [comment]
Great, let's check it out!

**Comment by marcosvital** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01908/joss.01908/10.21105.joss.01908.pdf)

**Comment by marcosvital** [comment]
@cddesja , I think that everything is fine with the proof now. Please take a look, and we can jump to review as soon as you say we are ready.

**Comment by cddesja** [comment]
Can you recompile it? I updated the text for Figure 2 and forgot to push it
to GitHub and itshould be current there now.

**Comment by marcosvital** [comment]
Yep, no problem.

**Comment by marcosvital** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01908/joss.01908/10.21105.joss.01908.pdf)

**Comment by marcosvital** [comment]
@cddesja , new version is ready for you to check.

**Comment by cddesja** [comment]
@marcosvital, looks good to me.

**Comment by marcosvital** [comment]
Great, I'll start the review. this issue will be closed, and we will begin to communicate at the new issue that will be created by Whedon.

**Comment by marcosvital** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1941. Feel free to close this issue now!
