### ISSUE TITLE
[PRE REVIEW]: EduCortex: browser-based 3D brain visualization of fMRI meta-analysis maps

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1909]
**Submitting author:** @PaulScotti (<a href="http://orcid.org/0000-0003-4912-8809">Paul Scotti</a>)
**Repository:** <a href="github.com/PaulScotti/educortex" target ="_blank">github.com/PaulScotti/educortex</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @PaulScotti. **Currently, there isn't an JOSS editor assigned** to your paper.

@PaulScotti if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1909 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
Hi @PaulScotti! This looks like a neat project. It does look geared toward education. Would the [Journal of Open Source Education](https://jose.theoj.org/about) potentially be a better fit?

**Comment by PaulScotti** [comment]
> Hi @PaulScotti! This looks like a neat project. It does look geared toward education. Would the [Journal of Open Source Education](https://jose.theoj.org/about) potentially be a better fit?

Thanks Kristen, I was not aware of JOSE! Reading into it, I agree that JOSE looks to be a better fit compared with JOSS. I'll look into submitting to JOSE. Can you cancel this submission?
