### ISSUE TITLE
[REVIEW]: Dryft: A Python and MATLAB package to correct drifting ground reaction force signals during treadmill running

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1910]
**Submitting author:** @alcantarar (<a href="http://orcid.org/0000-0002-8539-711X">Ryan Alcantara</a>)
**Repository:** <a href="https://github.com/alcantarar/dryft" target ="_blank">https://github.com/alcantarar/dryft</a>
**Version:** v1.1.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @agricolab, @DARSakthi, @mwptrsn
**Archive:** <a href="https://doi.org/10.5281/zenodo.3561026" target="_blank">10.5281/zenodo.3561026</a>

## Status

[![status](https://joss.theoj.org/papers/3b4b58ee398e8a0c11a2558d30aea88c/status.svg)](https://joss.theoj.org/papers/3b4b58ee398e8a0c11a2558d30aea88c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3b4b58ee398e8a0c11a2558d30aea88c"><img src="https://joss.theoj.org/papers/3b4b58ee398e8a0c11a2558d30aea88c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3b4b58ee398e8a0c11a2558d30aea88c/status.svg)](https://joss.theoj.org/papers/3b4b58ee398e8a0c11a2558d30aea88c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/alcantarar/dryft" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@agricolab & @DARSakthi & @mwptrsn, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/alcantarar/dryft">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@alcantarar) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/alcantarar/dryft">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@alcantarar) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/alcantarar/dryft">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@alcantarar) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @agricolab, @DARSakthi, @mwptrsn it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1152/jappl.1998.85.2.764 is OK
- 10.7717/peerj.3298 is OK
- 10.1016/j.medengphy.2006.04.002 is OK
- 10.1016/j.medengphy.2015.03.018 is OK
- 10.1249/MSS.0b013e3181677530 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01910/joss.01910/10.21105.joss.01910.pdf)

**Comment by agricolab** [comment]
Authors submitted a well-written manuscript for a well-documented toolbox on drift correction for oscillations generated by ground reaction force measurements. There are only four aspects that imho require action, the rest of my comments can be considered mere recommendations. These aspects are

- [ ] [discuss performance claims](#pf)
- [ ] [add tests](#at)
- [ ] [pin panda dependency](#pd)
- [ ] [revive dead link](#dl)

## Matlab

### Author might consider to add more documentation on installation for Matlab

Currently, the author redirects to the general Matlab documentatio for adding packages, but sth.along
```
git clone https://github.com/alcantarar/dryft.git
cd dryft
echo "addpath(\"$(pwd)\"); savepath(); exit;" > import_dryft.m
matlab -r 'run("import_dryft.m")'
```
might be helpful nonetheless, altough i am aware it'd probably would not to be refined for different platforms. If installation is done in this permanent fashion, using namespaces is  sensible, see next comment. An alternative is omitting the `savepath(); exit;` and make the user run `import_dryft.m` everytime they want to use dryft.

### Author might consider to use namespaces for Matlab

This can be achieved by putting all functions into a folder e.g. `~/MATLAB/+dryft`, which allows after `addpath("~/MATLAB")` to call matlab functions using dot.notation, e.g. `dryft.detrend`. See also https://de.mathworks.com/help/matlab/matlab_oop/scoping-classes-with-packages.html#brf3g8k This is a recommendation, only because namespaces are barely used in the Matlab ecosystem. It is good software practice, nonetheless.

## Python

### Author should pin the panda dependency as `pandas >= 0.24` <a name="pd"></a>

The package uses pandas Datafram.to_numpy which was [introduced in 0.24.0](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_numpy.html)

### Author might consider to split installation recommendations into "classical" and "with environment"

I appreciate that an environment.yaml was supported, but am uncertain why the author suggests a conda environment as recommended installation. Are there any dependencies that require conda? Otherwise, conda would become a hidden dependency, yet would actually not be required at all. All requirements install fine from pip, and the environment can be set-up with virtualenv or similar, too. I would argue, it should be left to the user how they want to set up their environment, if at all.

### Author might consider to compact snippets and add instructions for downloading repo

Everyone benefits from compact and complete copy-pastable bash snippets, and i recommend sth along

```{bash}
git clone https://github.com/alcantarar/dryft.git
cd dryft
conda env create -f environment.yml
conda activate dryft-env
python setup.py install
```

## General

### Author should discuss performance <a name="pf"></a>

Author seems to suggest his approach is superior to other methods, as

> dryft does not assume a constant drift for a given step, instead spline interpolating between aerial phases. The dryft package differs from currently available signal correction methods, which can only account for linear drift or a constant offset.

While i would agree with the author that spline interpolation is theoretically better, author might want to add some numbers to this claim.

### Author should revive dead link <a name="dl"></a>

The link in https://github.com/alcantarar/dryft/tree/master/documentation/API_Documention_by_pdoc3 to the Pdoc3 page is apparently dead

### Author should provide automated tests <a name="at"></a>

This reviewer failed to find any automated tests or instructions for manual testing for Matlab or Python.

### Author is thanked for having created sufficient documentation

pdoc3 builds the html well
the docstrings are well written and concise, and sufficient contain examples

### Author might want to streamline example and add tests

Author includes an example "of how to use the software" in the readme. Author might consider to move the sample.py and the data within the package. For python, e.g. into the folder `dryft/example`. This would allow a snippet along the lines of `python -m dryft.example.sample` to run the example, and could also constitute a basic smoke test. The datafile can be found e.g using

```
from pathlib import Path
# Read in data from force plate
GRF = pd.read_csv(Path(__file__).parent /
                  'custom_drift_S001runT25.csv', header=None)
```

### Author might want to use full names in acknowledgments

The authors acknowledges various people by acronym only. Unless this is to maintain anonymity, it counters the goal of acknowledging someone, and author might want to use full names.

**Comment by alcantarar** [comment]
Thank you @agricolab for your review!

@DARSakthi  and @mwptrsn, commit https://github.com/alcantarar/dryft/commit/4e56b8693a86b371b335bc3d674d8d4fce3f3314 is the latest and greatest.

**Comment by alcantarar** [comment]
@mwptrsn "Automated Tests" is unchecked in your review checklist; did you have any issues with the testing suite?

**Comment by mwptrsn** [comment]
> @mwptrsn "Automated Tests" is unchecked in your review checklist; did you have any issues with the testing suite?

I may have missed that/unchecked it by accident. I was able to get the package up and running with no issues.

**Comment by mwptrsn** [comment]
The author describes a software package for removing drift in ground force measurements caused by environmental or other factors. The software is well-documented, with both examples and API documentation for both the Python and MATLAB code. The use of a Jupyter Notebook to highlight the use was appreciated. The Python code was easier to set up and get running, but that’s due to the nature of the two environments vs. the software.

I have no issues preventing me from recommending the software and associated paper for publication  in its current state - the previous review was thorough and the concerns have been addressed. However, there are two things that I think could improve the software in the future:

1. The plot of original vs. corrected used in the notebook could be encapsulated in a function. This strikes me as a common analysis that would be performed
2. While an automated smoke test is provided, since the author used synthetic drift in the data used for this experiment, a basic functional test could be created to potentially avoid regressions if the algorithm is changed in the future

**Comment by DARSakthi** [comment]
The author presents a novel method for correcting non-linear error in measurements of ground reaction force, and an accompanying software package. The author submits a well written paper reporting necessity, novelty, function, and applicability. I echo the previous reviewers responses, especially in regards to test cases, which I think would be received well if maintained in this repository. Based on the previous edits made and the current state of the paper/repository I am glad to recommend this paper for publication. 

For possible future updates, I would recommend including methods to make large data analysis more efficient, beyond Matlab’s automatic parallelism/batch procedures, if the norm for the field involves large data sets or lots of data at once. An additional ReadMe elaborating on the maths behind Spline Interpolation and data subtraction as applied here may be appreciated by some non-specialists.

**Comment by alcantarar** [comment]
@mwptrsn and @DARSakthi thanks for the review and suggestions. 

@mwptrsn could you elaborate on your second point in an [issue](https://github.com/alcantarar/dryft/issues)?

**Comment by alcantarar** [comment]
@Kevin-Mattheus-Moerman 
Tagged release v1.1.0 of reviewed software: https://github.com/alcantarar/dryft/releases/tag/v1.1.0
Archived v1.1.0 in Zenodo:  https://zenodo.org/record/3561026
Zenodo DOI: 10.5281/zenodo.3561026

**Comment by Kevin-Mattheus-Moerman** [comment]
@agricolab, @DARSakthi, @mwptrsn thanks for your review work here! It seems all boxes have been ticked and you have each "given your blessing".

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01910/joss.01910/10.21105.joss.01910.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set v1.1.0 as version

**Comment by whedon** [comment]
OK. v1.1.0 is the version.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 10.5281/zenodo.3561026 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3561026" target="_blank">10.5281/zenodo.3561026</a> is the archive.

**Comment by Kevin-Mattheus-Moerman** [comment]
@alcantarar I have checked the Zenodo archive and its meta-data, and have reread the paper. All looks good so i will now proceed to recommend acceptance in JOSS. I suggest you take this moment to double-check your paper yourself too prior to final acceptance.

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/jose-eics I recommend that this work is accepted

**Comment by alcantarar** [comment]
I'll do a double check later today and let you know!

**Comment by danielskatz** [comment]
Thanks @alcantarar 
@Kevin-Mattheus-Moerman - if you want to do the processing yourself, that's fine.  Otherwise, it will be tomorrow morning until I can.

**Comment by alcantarar** [comment]
>I'll do a double check later today and let you know!

Actually, I don't think I'll be able to do a double check today. I will let you know when I give it the thumbs up! Thanks!

**Comment by alcantarar** [comment]
@Kevin-Mattheus-Moerman all good on my end, thanks!

**Comment by alcantarar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01910/joss.01910/10.21105.joss.01910.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1152/jappl.1998.85.2.764 is OK
- 10.7717/peerj.3298 is OK
- 10.1016/j.medengphy.2006.04.002 is OK
- 10.1016/j.medengphy.2015.03.018 is OK
- 10.1249/MSS.0b013e3181677530 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1162

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1162, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1202977037838962689) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1163
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01910](https://doi.org/10.21105/joss.01910)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by Kevin-Mattheus-Moerman** [comment]
Congratulations @alcantarar! And thank you @agricolab, @DARSakthi, @mwptrsn for reviewing this work!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01910/status.svg)](https://doi.org/10.21105/joss.01910)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01910">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01910/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01910/status.svg
   :target: https://doi.org/10.21105/joss.01910
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01910/status.svg)](https://doi.org/10.21105/joss.01910)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
