### ISSUE TITLE
[REVIEW]: cdcam: Cambridge Digital Communications Assessment Model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1911]
**Submitting author:** @tomalrussell (<a href="http://orcid.org/0000-0002-0081-400X">Tom Russell</a>)
**Repository:** <a href="https://github.com/nismod/cdcam" target ="_blank">https://github.com/nismod/cdcam</a>
**Version:** v1.0.2
**Editor:** @melissawm
**Reviewer:** @nmstreethran, @potterzot
**Archive:** <a href="https://doi.org/10.5281/zenodo.3583132" target="_blank">10.5281/zenodo.3583132</a>

## Status

[![status](https://joss.theoj.org/papers/c7d770ea25ec5c3da60bc2463c305a90/status.svg)](https://joss.theoj.org/papers/c7d770ea25ec5c3da60bc2463c305a90)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c7d770ea25ec5c3da60bc2463c305a90"><img src="https://joss.theoj.org/papers/c7d770ea25ec5c3da60bc2463c305a90/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c7d770ea25ec5c3da60bc2463c305a90/status.svg)](https://joss.theoj.org/papers/c7d770ea25ec5c3da60bc2463c305a90)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/nismod/cdcam" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@nmstreethran & @potterzot, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @melissawm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nismod/cdcam">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@tomalrussell) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nismod/cdcam">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@tomalrussell) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @nmstreethran, @potterzot it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1016/j.techfore.2018.03.016 is OK
- https://doi.org/10.1016/j.telpol.2017.07.009 is OK
- https://doi.org/10.1016/j.tele.2019.01.003 is OK
- https://doi.org/10.1109/ACCESS.2019.2949460 is OK
- https://doi.org/10.5334/jors.265 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01911/joss.01911/10.21105.joss.01911.pdf)

**Comment by potterzot** [comment]
I filed a detailed review as an [issue on the cdcam repository](https://github.com/nismod/cdcam/issues/14) and have updated my checklist. Overall the library is very nicely put together. I suggest a couple of minor revisions having to do with providing non-conda installation instructions, a clear real-world example and providing information on contributing, seeking additional help, and filing issues that could be added to the README. Code executes and tests all pass.

**Comment by nmstreethran** [comment]
I've completed my review and left my comments in

**Comment by nmstreethran** [comment]
My apologies for accidentally closing the issue. I've completed my review and left my comments in https://github.com/nismod/cdcam/issues/15.

**Comment by melissawm** [comment]
Thank you, @nmstreethran and @potterzot ! When you are satisfied with the revision by @tomalrussell please let me know.

**Comment by tomalrussell** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01911/joss.01911/10.21105.joss.01911.pdf)

**Comment by nmstreethran** [comment]
Hi @melissawm, I've updated my review checklist and am happy with the revisions by @tomalrussell. I think this submission is ready for publication. :)

**Comment by melissawm** [comment]
Thank you, @nmstreethran !

**Comment by potterzot** [comment]
@melissawm, I think this submission is ready for publication, thanks!

**Comment by melissawm** [comment]
Hi @potterzot, thanks! Can you please check the remaining items on your checklist?

I'll check the last details as soon as possible. Thank you all!

**Comment by potterzot** [comment]
@melissawm right, sorry. All set!

**Comment by melissawm** [comment]
@tomalrussell if you haven't already, can you create an archive (on Zenodo, figshare, or other) and post the archive DOI here? Thanks!

**Comment by tomalrussell** [comment]
@melissawm sure - it's on [Zenodo](https://zenodo.org/record/3583132), DOI 10.5281/zenodo.3583132

**Comment by melissawm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01911/joss.01911/10.21105.joss.01911.pdf)

**Comment by melissawm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.techfore.2018.03.016 is OK
- 10.1016/j.telpol.2017.07.009 is OK
- 10.1016/j.tele.2019.01.003 is OK
- 10.1109/ACCESS.2019.2949460 is OK
- 10.5334/jors.265 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by melissawm** [comment]
@whedon set 10.5281/zenodo.3583132 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3583132" target="_blank">10.5281/zenodo.3583132</a> is the archive.

**Comment by melissawm** [comment]
@openjournals/joss-eics looks like this is ready :)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set v1.0.2 as version

**Comment by whedon** [comment]
OK. v1.0.2 is the version.

**Comment by Kevin-Mattheus-Moerman** [comment]
@tomalrussell I'm the AEiC handling the processing for this submission. Below are some remaining minor points to work on. Let me know when you've processed these. 

- [ ] Please ensure the [archive](https://zenodo.org/record/3583132#.XjFGZeGnxKg) meta data matches that for the paper i.e. the paper title and the author name(s) should be the same
- [ ]  Can you confirm that the version tag v1.0.2 is the most accurate for this paper/review/archive? 
- [ ] I've proofread the paper and it reads well. This paper is about to be accepted for publication in JOSS. Please double check the paper yourself at this point as well.

**Comment by tomalrussell** [comment]
Thanks @Kevin-Mattheus-Moerman - I think this is all okay:
- [x] archive and paper are both Oughton and Russell
- [x] v1.0.2 is the most accurate version tag
- [x] I've read through the paper again

**Comment by Kevin-Mattheus-Moerman** [comment]
@tomalrussell The title of the archive is still different, can you make it match the paper title? Thanks

**Comment by tomalrussell** [comment]
@Kevin-Mattheus-Moerman I've now edited the archive metadata, title is now "cdcam: Cambridge Digital Communications Assessment Model".

**Comment by Kevin-Mattheus-Moerman** [comment]
@tomalrussell 
> @Kevin-Mattheus-Moerman I've now edited the archive metadata, title is now "cdcam: Cambridge Digital Communications Assessment Model".

Great. This looks good now

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.techfore.2018.03.016 is OK
- 10.1016/j.telpol.2017.07.009 is OK
- 10.1016/j.tele.2019.01.003 is OK
- 10.1109/ACCESS.2019.2949460 is OK
- 10.5334/jors.265 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1254

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1254, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1222527488825446400) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1255
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01911](https://doi.org/10.21105/joss.01911)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01911/status.svg)](https://doi.org/10.21105/joss.01911)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01911">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01911/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01911/status.svg
   :target: https://doi.org/10.21105/joss.01911
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01911/status.svg)](https://doi.org/10.21105/joss.01911)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
