### ISSUE TITLE
[PRE REVIEW]: SAILS: Spectral Analysis In Linear Systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1913]
**Submitting author:** @ajquinn (<a href="http://orcid.org/0000-0003-2267-9897">Andrew Quinn</a>)
**Repository:** <a href="https://vcs.ynic.york.ac.uk/analysis/sails" target ="_blank">https://vcs.ynic.york.ac.uk/analysis/sails</a>
**Version:** v0.1.1
**Editor:** @mjsottile
**Reviewers:** @szorowi1, @mnarayan

**Author instructions**

Thanks for submitting your paper to JOSS @ajquinn. **Currently, there isn't an JOSS editor assigned** to your paper.

@ajquinn if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1913 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/382043.382304 is OK
- 10.1093/biomet/37.3-4.409 is OK
- 10.1007/s004229900137 is OK
- 10.1101/gr.092759.109 is OK
- 10.3389/fnhum.2014.00448 is OK
- 10.1007/bf00198091 is OK
- 10.1007/pl00007990 is OK

MISSING DOIs

- https://doi.org/10.1007/3-540-27752-8 may be missing for title: New Introduction to Multiple Time Series Analysis

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01913/joss.01913/10.21105.joss.01913.pdf)

**Comment by kthyng** [comment]
Hi @mjsottile! Would you edit this submission?

**Comment by mjsottile** [comment]
Sure - I can do that.

**Comment by AJQuinn** [comment]
Hello, thanks for your time with our submission.

Here are some suggestions for reviewers based on the list above. These are people with listed experience in either time-series analysis or M/EEG (or both) who might be appropriate reviewers. This was from a quick skim through the list, I'm sure there are others.

mnarayan, agricolab, szorowi1, lukassnoek, breznak, ejolly

Please let me know if there is anything else I can do.

Cheers,
Andrew

**Comment by kthyng** [comment]
@whedon assign @mjsottile as editor

**Comment by whedon** [comment]
OK, the editor is @mjsottile

**Comment by mjsottile** [comment]
Thanks for the reviewer suggestions @ajquinn.

@mnarayan, @agricolab, @szorowi1, @lukassnoek, @breznak, @ejolly : you have been identified as potential reviewers for this JOSS submission.  Please let me know if you are interested in reviewing this submission and I will add you so we can start the review process.

**Comment by lukassnoek** [comment]
I don't think I have the domain knowledge (spectral analysis) to evaluate this project, but it looks quite nice!

**Comment by ejolly** [comment]
Unfortunately, I don't think I have sufficient expertise for being a reviewer for this submission. I'll also be unavailable due to travel to ensure a timely review. 

The submission looks really interesting though!

**Comment by szorowi1** [comment]
Hi there,

Apologies for the delay. Would be more than happy to review. This would be my first review for JoSS. Beyond the [review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html), anything else I should be aware of?

Thanks!
-Sam

**Comment by mjsottile** [comment]
@szorowi1 Thanks for agreeing to review.  The review checklist and JOSS documentation should cover everything.  Feel free to reach out if you have any questions during the process.

**Comment by mjsottile** [comment]
@whedon assign @szorowi1 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @szorowi1

**Comment by mjsottile** [comment]
Checking again: would @mnarayan, @agricolab, or @breznak be interested in reviewing this submission?  If not I'll look through the potential reviewer spreadsheet to find other potential reviewers.  

@ajquinn : if you have any other suggested reviewers feel free to let me know so I can check with them.

**Comment by agricolab** [comment]
It looks like a already well-documented package, but it is also relatively extensive. I can do a review, but am already busy till mid january. Best guess is i can finish the review latest till end January. If that's ok, i'm in.

**Comment by mnarayan** [comment]
I can do the review.

**Comment by mjsottile** [comment]
Thanks @mnarayan for agreeing to do the review.  It looks like we have the two necessary reviewers, so I'm going to start the formal review process.  Please feel free to reach out during the review process if you need any assistance.

**Comment by mjsottile** [comment]
@whedon add @mnarayan as reviewer

**Comment by whedon** [comment]
OK, @mnarayan is now a reviewer

**Comment by mjsottile** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1982. Feel free to close this issue now!
