### ISSUE TITLE
[REVIEW]: c14bazAAR: An R package for downloading and preparing C14 dates from different source databases

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1914]
**Submitting author:** @nevrome (<a href="http://orcid.org/0000-0003-3448-5715">Clemens Schmid</a>)
**Repository:** <a href="https://github.com/ropensci/c14bazAAR" target ="_blank">https://github.com/ropensci/c14bazAAR</a>
**Version:** 1.1.0
**Editor:** @arfon
**Reviewer:** @arfon
**Archive:** <a href="https://doi.org/10.17605/OSF.IO/3DS6A" target="_blank">10.17605/OSF.IO/3DS6A</a>

## Status

[![status](https://joss.theoj.org/papers/9e0af57210198f0b767953c4d4762954/status.svg)](https://joss.theoj.org/papers/9e0af57210198f0b767953c4d4762954)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/9e0af57210198f0b767953c4d4762954"><img src="https://joss.theoj.org/papers/9e0af57210198f0b767953c4d4762954/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/9e0af57210198f0b767953c4d4762954/status.svg)](https://joss.theoj.org/papers/9e0af57210198f0b767953c4d4762954)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://doi.org/10.17605/OSF.IO/3DS6A" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@arfon, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://doi.org/10.17605/OSF.IO/3DS6A">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@nevrome) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1914 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1914 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.4324/9781315421216 is OK
- 10.2307/2799190 is OK
- 10.14324/000.ds.1575442 is OK
- 10.1111/j.1467-9876.2008.00623.x is OK
- 10.32614/RJ-2018-009 is OK
- 10.7910/DVN/NJLNRJ is OK
- 10.1177/1059712319860842 is OK
- 10.12766/jna.2012.65 is OK
- 10.4312/dp.36.2 is OK
- 10.1016/j.jas.2011.08.008 is OK
- 10.1371/journal.pbio.0030410 is OK
- 10.1371/journal.pone.0087854 is OK
- 10.1371/journal.pone.0113672 is OK
- 10.2458/azu_js_rc.55.16385 is OK
- 10.1073/pnas.1715336115 is OK
- 10.5281/zenodo.61113 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
Accepting because of https://github.com/ropensci/software-review/issues/333

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
@whedon set 10.17605/OSF.IO/3DS6A as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.17605/OSF.IO/3DS6A" target="_blank">10.17605/OSF.IO/3DS6A</a> is the archive.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01914/joss.01914/10.21105.joss.01914.pdf)

**Comment by arfon** [comment]
@nevrome - could you update the archive record to have the same authors as the paper please?

**Comment by nevrome** [comment]
What's the archive record? OSF contributors?

**Comment by arfon** [comment]
> What's the archive record? OSF contributors?

Yes, sorry for not being more clear.

**Comment by nevrome** [comment]
@MartinHinz Could you please create an OSF account or tell me your handle if you already have one? I was able to find @dirkseidensticker (https://osf.io/7rmq4).

**Comment by MartinHinz** [comment]
@nevrome: my account is 

https://osf.io/k8yjx

Is that all you need?

**Comment by nevrome** [comment]
@MartinHinz Thank you!

@arfon Done.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.4324/9781315421216 is OK
- 10.2307/2799190 is OK
- 10.14324/000.ds.1575442 is OK
- 10.1111/j.1467-9876.2008.00623.x is OK
- 10.32614/RJ-2018-009 is OK
- 10.7910/DVN/NJLNRJ is OK
- 10.1177/1059712319860842 is OK
- 10.12766/jna.2012.65 is OK
- 10.4312/dp.36.2 is OK
- 10.1016/j.jas.2011.08.008 is OK
- 10.1371/journal.pbio.0030410 is OK
- 10.1371/journal.pone.0087854 is OK
- 10.1371/journal.pone.0113672 is OK
- 10.2458/azu_js_rc.55.16385 is OK
- 10.1073/pnas.1715336115 is OK
- 10.5281/zenodo.61113 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1127

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1127, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1198910437687005185) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1128
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01914](https://doi.org/10.21105/joss.01914)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@nevrome - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01914/status.svg)](https://doi.org/10.21105/joss.01914)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01914">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01914/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01914/status.svg
   :target: https://doi.org/10.21105/joss.01914
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01914/status.svg)](https://doi.org/10.21105/joss.01914)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
