### ISSUE TITLE
[REVIEW]: alignparse: A Python package for parsing complex features from high-throughput long-read sequencing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1915]
**Submitting author:** @jbloom (<a href="http://orcid.org/0000-0003-1267-3408">Jesse Bloom</a>)
**Repository:** <a href="https://github.com/jbloomlab/alignparse" target ="_blank">https://github.com/jbloomlab/alignparse</a>
**Version:** 0.1.1
**Editor:** @will-rowe
**Reviewer:** @bede, @afrubin
**Archive:** <a href="https://doi.org/10.5281/zenodo.3569587" target="_blank">10.5281/zenodo.3569587</a>

## Status

[![status](https://joss.theoj.org/papers/6b80644a328294f86cd62310eb16dbe5/status.svg)](https://joss.theoj.org/papers/6b80644a328294f86cd62310eb16dbe5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6b80644a328294f86cd62310eb16dbe5"><img src="https://joss.theoj.org/papers/6b80644a328294f86cd62310eb16dbe5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6b80644a328294f86cd62310eb16dbe5/status.svg)](https://joss.theoj.org/papers/6b80644a328294f86cd62310eb16dbe5)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jbloomlab/alignparse" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@bede & @afrubin, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @will-rowe know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jbloomlab/alignparse">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jbloom) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jbloomlab/alignparse">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jbloom) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @bede, @afrubin it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.gpb.2015.08.002 is OK
- 10.1186/s12864-018-4611-3 is OK
- 10.1186/1471-2105-13-238 is OK
- 10.1093/bioinformatics/bty191 is OK
- 10.1128/JVI.00500-19 is OK
- 10.1038/s41588-018-0122-z is OK
- 10.1038/nmeth.3027 is OK
- 10.1038/nmeth.1416 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01915/joss.01915/10.21105.joss.01915.pdf)

**Comment by afrubin** [comment]
@jbloom @khdusenbury This is a really nice tool that I could see using for my own work. The manuscript is well written and I found the notebook-style documentation to be quite clear.

I've submitted a PR with some minor suggested edits to the text (https://github.com/jbloomlab/alignparse/pull/57) and opened four issues. Support for new input file formats requested in https://github.com/jbloomlab/alignparse/issues/53 should be considered optional and not required for acceptance.

**Comment by will-rowe** [comment]
Brilliant - thanks for your prompt and thorough review @afrubin!

**Comment by afrubin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01915/joss.01915/10.21105.joss.01915.pdf)

**Comment by bede** [comment]
A very well crafted tool and accompanying paper. All the bases have been well covered, and multiple use cases have been elegantly demonstrated through rich notebooks with lovely visualisations. The paper is clear and well written. I see that you have recently added contribution guidelines. @afrubin has already covered some other points.

I did encounter a minor installation issue that was easily worked around and have opened a corresponding issue https://github.com/jbloomlab/alignparse/issues/58. Actioning this is not required for acceptance. However, providing this conda installation option would also offer a route for users to simultaneously install a pinned and tested version of minimap2.

**Comment by will-rowe** [comment]
Thank you @afrubin and @bede for your thorough and speedy reviews! Apologies for my slowness in getting back to this - I had to take some carer leave this week.

I think this is a lovely piece of work and we're close to acceptance. @jbloom - could you let us know if you intend to make any changes in light of the reviewer comments. I agree that support for new file formats or conda installation is not required for acceptance.

**Comment by khdusenbury** [comment]
My apologies for being slow at getting the reviewer comments, but thank you all for the reviews and being so fast with getting to this!

I've started working on the issues @afrubin and @bede raised and hope to have their changes incorporated soon.

**Comment by khdusenbury** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01915/joss.01915/10.21105.joss.01915.pdf)

**Comment by khdusenbury** [comment]
@will-rowe I think the manuscript and repo now incorporate @bede and @afrubin's reviews. Please let us know if there are additional changes you would like us to make. Thank you!

**Comment by afrubin** [comment]
@will-rowe I've looked over the changes and updated manuscript and I'm happy to recommend that we move towards acceptance.

**Comment by will-rowe** [comment]
Thanks @khdusenbury for your work in addressing the reviews - and thank you @afrubin for checking this so quickly.

I think this looks great and I'm happy to move this on for publication.

**Comment by will-rowe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01915/joss.01915/10.21105.joss.01915.pdf)

**Comment by will-rowe** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1093/nar/gkz956 is OK
- 10.1016/j.gpb.2015.08.002 is OK
- 10.1186/s12864-018-4611-3 is OK
- 10.1186/1471-2105-13-238 is OK
- 10.1093/bioinformatics/bty191 is OK
- 10.1128/JVI.00500-19 is OK
- 10.1038/s41588-018-0122-z is OK
- 10.1038/nmeth.3027 is OK
- 10.1038/nmeth.1416 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by will-rowe** [comment]
Okay - paper looks good to me. If you're happy @khdusenbury, can you please make a tagged release and archive. Then can you let me know the version number and archive DOI

**Comment by bede** [comment]
The minor points I raised before have been addressed, and the tool now installs with a single command. Everything looks great from here.

**Comment by khdusenbury** [comment]
@will-rowe Took me a bit to figure out Zenodo, but I think we have it archived properly. We archived version 0.1.1. and the DOI is 10.5281/zenodo.3569587. This is my first time working with Zenodo, so please let me know if there's anything I need to fix!

**Comment by will-rowe** [comment]
@whedon set 10.5281/zenodo.3569587 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3569587" target="_blank">10.5281/zenodo.3569587</a> is the archive.

**Comment by will-rowe** [comment]
@whedon set 0.1.1 as version

**Comment by whedon** [comment]
OK. 0.1.1 is the version.

**Comment by will-rowe** [comment]
Thanks @khdusenbury  - looks good

**Comment by will-rowe** [comment]
Hey @openjournals/joss-eics - this is good to go. Thanks everyone

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01915/joss.01915/10.21105.joss.01915.pdf)

**Comment by kyleniemeyer** [comment]
Hi @jbloom, I'm the Associate Editor-in-Chief on duty this week, so I'm going to do the final checks on your submission and then publish.

First off, can you edit the Zenodo entry metadata so that the title and authors match the submission? You can edit those without affecting the DOI.

**Comment by khdusenbury** [comment]
@kyleniemeyer I think I successfully updated the author and title information in the latest PR. Thanks for handling the submission and please let me know if there are other changes to make.

**Comment by kyleniemeyer** [comment]
@khdusenbury did you make the change at Zenodo? At https://doi.org/10.5281/zenodo.3569587 they look unchanged.

**Comment by khdusenbury** [comment]
Whoops, I had just made the change in the repo. I think the changes should be on Zenodo now (and the repo `.zenodo.json` metadata file has been updated to match Zenodo).

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1093/nar/gkz956 is OK
- 10.1016/j.gpb.2015.08.002 is OK
- 10.1186/s12864-018-4611-3 is OK
- 10.1186/1471-2105-13-238 is OK
- 10.1093/bioinformatics/bty191 is OK
- 10.1128/JVI.00500-19 is OK
- 10.1038/s41588-018-0122-z is OK
- 10.1038/nmeth.3027 is OK
- 10.1038/nmeth.1416 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1171

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1171, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1204905309665464320) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1172
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01915](https://doi.org/10.21105/joss.01915)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @jbloom and @khdusenbury on your article's publication in JOSS!

Many thanks to @bede and @afrubin for reviewing, and @will-rowe for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01915/status.svg)](https://doi.org/10.21105/joss.01915)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01915">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01915/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01915/status.svg
   :target: https://doi.org/10.21105/joss.01915
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01915/status.svg)](https://doi.org/10.21105/joss.01915)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
