### ISSUE TITLE
[PRE REVIEW]: Cocktail Shaker: An open source drug expansion and enumeration library for peptides

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1916]
**Submitting author:** @Sulstice (<a href="http://orcid.org/0000-0002-1342-9258">Suliman Sharif</a>)
**Repository:** <a href="https://github.com/Sulstice/cocktail-shaker" target ="_blank">https://github.com/Sulstice/cocktail-shaker</a>
**Version:** v1.1.0
**Editor:** @csoneson
**Reviewers:** @floux, @olivertomic

**Author instructions**

Thanks for submitting your paper to JOSS @Sulstice. **Currently, there isn't an JOSS editor assigned** to your paper.

@Sulstice if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1916 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon.rb:145:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@Sulstice your paper seems to be missing some fields (e.g. affiliations). 

Have a look here: 
https://joss.readthedocs.io/en/latest/submitting.html#checking-that-your-paper-compiles

You can test compile your paper here: 
https://whedon.theoj.org/

**Comment by Sulstice** [comment]
Hi @Kevin-Mattheus-Moerman I just updated the affiliations to "No affiliations" since I currently have none. Does that suffice or is there another protocol I should follow?

**Comment by arfon** [comment]
@Sulstice - you can add an affiliation of 'None' but this need to be in the `affiliations` block as described in the example paper: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by Kevin-Mattheus-Moerman** [comment]
@brainstorm @csoneson @will-rowe @majensen @mgymrek could one of you edit this submission? thanks

**Comment by majensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01916/joss.01916/10.21105.joss.01916.pdf)

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
Hi @Sulstice - could you check Figure 1 in your paper? It doesn't seem to show up.

**Comment by arfon** [comment]
@Sulstice - you'll need to link to the image URL like this rather than the relative path you're currently using:

```
https://raw.githubusercontent.com/Sulstice/cocktail-shaker/master/images/figure_1.png
```

**Comment by Sulstice** [comment]
@csoneson @arfon Made the change!

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01916/joss.01916/10.21105.joss.01916.pdf)

**Comment by arfon** [comment]
@Sulstice - Could you move the references you currently have in the `paper.md` file into a `paper.bib` file and cite them directly please? (You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html))

**Comment by Sulstice** [comment]
@arfon Done!

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01916/joss.01916/10.21105.joss.01916.pdf)

**Comment by csoneson** [comment]
Thanks @Sulstice. I will take care of your submission, and start by finding suitable reviewers. If you have suggestions (e.g., from the list linked in the first post above), please let me know.

**Comment by Sulstice** [comment]
@csoneson I looked through the list 

Username: mskwark, road2stat, semacu seem most reasonable since they are in the peptide/cheminformatics space.

**Comment by Sulstice** [comment]
Should I be doing a release of the software so y'all can pip install it? Or should I wait pending on whether you approve or not?

**Comment by csoneson** [comment]
@Sulstice - yes, I think that would be nice.

**Comment by csoneson** [comment]
@whedon add @floux as reviewer

**Comment by whedon** [comment]
OK, @floux is now a reviewer

**Comment by csoneson** [comment]
@mskwark, @semacu - would one of you be willing to review this submission for JOSS?

**Comment by Sulstice** [comment]
@csoneson I released the cocktail shaker v1.1.0 and it is labeled as a "pre-release" for now pending the JOSS approval. 

You should be able to easily install with this command `pip install cocktail-shaker==1.1.0`

**Comment by csoneson** [comment]
Ping @mskwark, @semacu

> @mskwark, @semacu - would one of you be willing to review this submission for JOSS?

**Comment by csoneson** [comment]
@olivertomic, @road2stat - would one of you be willing to review this submission for JOSS?

**Comment by olivertomic** [comment]
@csoneson , I will be unavailable until mid-february. Would that be too late?

**Comment by nanxstats** [comment]
Thanks @csoneson for the invitation but I'm a bit busy with a personal project right now and in the next few months. My apologies. Maybe next time...

**Comment by csoneson** [comment]
Thanks @olivertomic - I'm hoping to start the review soon, so I will reach out to a couple of more potential reviewers, but I may come back to you :)

**Comment by csoneson** [comment]
@diegoenry, @matthiaslein - would one of you be willing to review this submission for JOSS?

**Comment by csoneson** [comment]
@fdroessler, @keipertk - would one of you be interested in reviewing this submission for JOSS?

**Comment by csoneson** [comment]
:wave: @Sulstice - I suspect we may have more luck finding available reviewers after the holidays and the often hectic end of semester time. If you would be ok with a slight delay, and @olivertomic is still available from mid-February, that is one option. Otherwise I suggest we continue looking for reviewers in early January, after the holidays. 

@floux - thanks for your patience! I'll start the actual review issue as soon as we have one more reviewer.

**Comment by Sulstice** [comment]
@csoneson No worries! I'm not in a rush to get it published. Please let me know if there is anything I can do to help as well.

**Comment by csoneson** [comment]
👋 @olivertomic - Happy New Year! Would you still be interested and available in mid-February to review this submission for JOSS? 

> Cocktail Shaker: An open source drug expansion and enumeration library for peptides

**Comment by olivertomic** [comment]
@csoneson - Happy New Year to you too! Sure, I would be still interested to do it from the proposed time.

**Comment by csoneson** [comment]
@olivertomic - brilliant, thanks! Then I'll add you as a reviewer and start the review issue. I'll also ask our bot whedon to send an automated reminder in mid-February.

**Comment by csoneson** [comment]
@whedon add @olivertomic as reviewer

**Comment by whedon** [comment]
OK, @olivertomic is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1992. Feel free to close this issue now!
