### ISSUE TITLE
[REVIEW]: PyCHAM: CHemistry with Aerosol Microphysics in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1918]
**Submitting author:** @simonom (<a href="http://orcid.org/0000-0001-7197-0651">Simon O&#39;Meara</a>)
**Repository:** <a href="https://github.com/simonom/PyCHAM" target ="_blank">https://github.com/simonom/PyCHAM</a>
**Version:** v0.2.4
**Editor:** @jedbrown
**Reviewers:** @dhhagan, @samjsilva91
**Archive:** <a href="https://doi.org/10.5281/zenodo.3752677" target="_blank">10.5281/zenodo.3752677</a>

## Status

[![status](https://joss.theoj.org/papers/6c0140bf991f3110477dc9cf67775f18/status.svg)](https://joss.theoj.org/papers/6c0140bf991f3110477dc9cf67775f18)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6c0140bf991f3110477dc9cf67775f18"><img src="https://joss.theoj.org/papers/6c0140bf991f3110477dc9cf67775f18/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6c0140bf991f3110477dc9cf67775f18/status.svg)](https://joss.theoj.org/papers/6c0140bf991f3110477dc9cf67775f18)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/simonom/PyCHAM" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dhhagan & @samjsilva91, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @jedbrown know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/simonom/PyCHAM">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@simonom) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/simonom/PyCHAM">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@simonom) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dhhagan, @andreas-h it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1142/10216 is OK
- 10.3390/atmos10070401 is OK
- 10.1016/j.atmosenv.2005.05.049 is OK
- 10.1080/02786820802389251 is OK
- 10.5194/acp-14-7953-2014 is OK
- 10.1080/02786826.2018.1427209 is OK
- 10.1038/s41467-019-12338-8 is OK
- 10.1016/j.scitotenv.2019.07.218 is OK
- 10.5194/acp-18-13031-2018 is OK
- 10.21105/joss.00755 is OK
- http://dx.doi.org/10.1016/j.matcom.2015.04.007 is OK
- 10.5194/acp-15-4197-2015 is OK
- 10.1038/nature13032 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01918/joss.01918/10.21105.joss.01918.pdf)

**Comment by jedbrown** [comment]
@dhhagan @andreas-h :wave: Welcome and thanks for agreeing to review! The comments from @whedon above outline the review process, which takes place in this thread (possibly with issues filed in the [PyCHAM repository](https://github.com/simonom/PyCHAM)). I'll be watching this thread if you have any questions.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `https://github.com/openjournals/joss-reviews/issues/1918` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@jedbrown) if you have any questions/concerns.

**Comment by dhhagan** [comment]
Hi @simonom - do you know if the newer versions of SUNDIALS will work? The current version is 5.0, but some of the dependencies list only v2.x - there are also dependency issues associated with python version as well that could possibly cause issues?

**Comment by simonom** [comment]
It's a good question @dhhagan.  I'm looking into this now, whilst updating the installation instructions as you recommended.

**Comment by simonom** [comment]
Dear @dhhagan and @andreas-h,
Are you satisfied with the provided responses to issues?

**Comment by simonom** [comment]
Hi @dhhagan and @andreas-h, will you be able to complete the review?

**Comment by andreas-h** [comment]
Yes but I won't be able to do it within the next ten days.

**Comment by simonom** [comment]
Thank you, appreciate the update.

**Comment by danielskatz** [comment]
👋 @jedbrown - can you update us on where we are and what actions we are waiting for?

**Comment by simonom** [comment]
I would like to more forward with this review; @andreas-h, please let us know if you are unable to review so we can progress.

**Comment by jedbrown** [comment]
@dhhagan I see there are a few remaining check boxes in your review. Could you please let us know if you have further concerns.

@andreas-h Please let us know what you'll need to complete your review. Thanks.

**Comment by andreas-h** [comment]
hi guys,
i'm sorry but my life is a bit chaotic at the moment.  i fear that i won't be able to complete the review, contrary to what i promised and what i'd like.
i hope you can find someone else quickly.
my apologies for the delay.

**Comment by jedbrown** [comment]
@andreas-h Thanks for trying. We'll find an alternative.

**Comment by dhhagan** [comment]
Hey @jedbrown Sorry about this - I was trying to find some guidelines for python projects and any/all requirements for JOSS but couldn't seem to find any. Currently, this project likely only works if installed via conda and not via pip due to some extremely challenging/frustrating installation requirements/steps for the required dependencies. Is a conda-only installation acceptable? Are there any more detailed guidelines that are language-specific from JOSS?

**Comment by jedbrown** [comment]
@dhhagan The important thing is that the installation instructions work. IMO, this should include some way for a potential contributor to install. JOSS doesn't currently have a "minimum standards" for Python packaging, but it should strive to follow community best practices. The vast majority of Python packages in JOSS will have a working pip install. If there are really good reasons why it is not tractable here and reviewers agree, I wouldn't block acceptance, but there should be something about how a contributor would install. Bad installs tax the community so authors should make an effort to clean up their installs to the extent feasible.

**Comment by jedbrown** [comment]
@whedon add samjsilva91 as reviewer

**Comment by whedon** [comment]
OK, samjsilva91 is now a reviewer

**Comment by jedbrown** [comment]
@samjsilva91 :wave: Welcome and thanks for agreeing to review! The comments from @whedon above outline the review process, which takes place in this thread (possibly with issues filed in the [PyCHAM repository](https://github.com/simonom/PyCHAM)). I'll be watching this thread if you have any questions.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `https://github.com/openjournals/joss-reviews/issues/1918` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@jedbrown) if you have any questions/concerns.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by samjsilva91** [comment]
Hello,

I apologize for the delay on getting to this review. COVID-19 here in Washington has been a bit hectic!
As I am going through the review process, I can’t actually get the checklist options to work. As in, when I click a check box, it doesn’t actually register a check.
Is there an issue on my end somewhere?

Best,
Sam

**Comment by jedbrown** [comment]
@whedon re-invite @samjsilva91 as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@samjsilva91 please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by jedbrown** [comment]
@samjsilva91 You should be able to click after accepting that invitation. :point_up_2:

**Comment by samjsilva91** [comment]
Yep, it works!

Thanks,
Sam

**Comment by samjsilva91** [comment]
Hi, to update you: I'm waiting to hear back on issues related to installation before wrapping up the review.

**Comment by samjsilva91** [comment]
In my opinion, the basic requirements for each of the check boxes has been met for this software, particularly considering the extensive work done prior to my involvement by @dhhagan 

The code installs and runs on my machine, and modifications made to the chemical mechanism lead to results broadly consistent with expected behavior.

**Comment by simonom** [comment]
There is also one point from our internal review, which is changing the wording inside the JOSS paper from 'environmental chamber' to 'aerosol chamber'.  The aerosol chamber is a subset of the environmental chamber.  PyCHAM is designed for aerosol chamber, and whilst it could be employed for any chamber experiment, we do not want to misled readers about its capabilities.  This has been updated in the paper.md file on the master branch of the Github repository.

Finally, the version number with the above modifications is now V0.2.4, whereas the number in the original submission was V0.0.5, so this should be updated in any publication.

Thanks for your reviews @dhhagan and @samjsilva91 .

**Comment by jedbrown** [comment]
@whedon set v0.2.4 as version

**Comment by whedon** [comment]
OK. v0.2.4 is the version.

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01918/joss.01918/10.21105.joss.01918.pdf)

**Comment by simonom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01918/joss.01918/10.21105.joss.01918.pdf)

**Comment by simonom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01918/joss.01918/10.21105.joss.01918.pdf)

**Comment by simonom** [comment]
Thanks @jedbrown , article looks okay to me.

**Comment by simonom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01918/joss.01918/10.21105.joss.01918.pdf)

**Comment by simonom** [comment]
Thanks Jed, have included the improvements you suggested (Sundials citation, non-abbreviated journal titles and moving EUROCHAMP reference to acknowledgements).

**Comment by arfon** [comment]
@dhhagan - how are you getting on with your review? I see there's still a fair number of unchecked boxes for the review?

**Comment by dhhagan** [comment]
Sorry about that @arfon - been a bit insane lately at work. Just finalized everything and it looks good.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01918/joss.01918/10.21105.joss.01918.pdf)

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1142/10216 is OK
- 10.3390/atmos10070401 is OK
- 10.1016/j.atmosenv.2005.05.049 is OK
- 10.1080/02786820802389251 is OK
- 10.5194/acp-14-7953-2014 is OK
- 10.1080/02786826.2018.1427209 is OK
- 10.1038/s41467-019-12338-8 is OK
- 10.1016/j.scitotenv.2019.07.218 is OK
- 10.5194/acp-18-13031-2018 is OK
- 10.21105/joss.00755 is OK
- 10.1016/j.matcom.2015.04.007 is OK
- 10.5194/acp-15-4197-2015 is OK
- 10.1038/nature13032 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@simonom - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by simonom** [comment]
Thanks @arfon I have archived the relevant version of the software here: 10.5281/zenodo.3752677

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3752677 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3752677" target="_blank">10.5281/zenodo.3752677</a> is the archive.

**Comment by arfon** [comment]
@whedon  accept

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1142/10216 is OK
- 10.3390/atmos10070401 is OK
- 10.1016/j.atmosenv.2005.05.049 is OK
- 10.1080/02786820802389251 is OK
- 10.5194/acp-14-7953-2014 is OK
- 10.1080/02786826.2018.1427209 is OK
- 10.1038/s41467-019-12338-8 is OK
- 10.1016/j.scitotenv.2019.07.218 is OK
- 10.5194/acp-18-13031-2018 is OK
- 10.21105/joss.00755 is OK
- 10.1016/j.matcom.2015.04.007 is OK
- 10.5194/acp-15-4197-2015 is OK
- 10.1038/nature13032 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1422

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1422, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1250393575751286784) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1423
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01918](https://doi.org/10.21105/joss.01918)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@dhhagan, @samjsilva91 - many thanks for your reviews here and to @jedbrown for editing this submission ✨ 

@simonom - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01918/status.svg)](https://doi.org/10.21105/joss.01918)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01918">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01918/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01918/status.svg
   :target: https://doi.org/10.21105/joss.01918
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01918/status.svg)](https://doi.org/10.21105/joss.01918)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
