### ISSUE TITLE
[PRE REVIEW]: MatD3: A Database and Online Presentation Package for Research Data Supporting Materials Discovery, Design, and Dissemination

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1919]
**Submitting author:** @raullaasner (<a href="http://orcid.org/0000-0002-9714-1189">Raul Laasner</a>)
**Repository:** <a href="https://github.com/HybriD3-database/MatD3" target ="_blank">https://github.com/HybriD3-database/MatD3</a>
**Version:** 1.0.0
**Editor:** @majensen
**Reviewers:** @dgasmith, @mkhorton

**Author instructions**

Thanks for submitting your paper to JOSS @raullaasner. **Currently, there isn't an JOSS editor assigned** to your paper.

@raullaasner if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1919 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/author.rb:68:in `block in build_affiliation_string': Problem with affiliations for Xiaochen Du, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/author.rb:67:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/author.rb:67:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon.rb:201:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon.rb:201:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon.rb:198:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon.rb:198:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon.rb:91:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1038/sdata.2019.2 may be missing for title: Qresp, a tool for curating, discovering and
 exploring reproducible scientific papers
- https://doi.org/10.1063/1.4812323 may be missing for title: Commentary: The Materials Project: A materials
 genome approach to accelerating materials
 innovation
- https://doi.org/10.1007/s11837-016-2001-3 may be missing for title: The Materials Data Facility: Data services to
 advance materials science research
- https://doi.org/10.1016/j.commatsci.2012.02.005 may be missing for title: AFLOW: An automatic framework for high-throughput
 materials discovery
- https://doi.org/10.1007/s11837-013-0755-4 may be missing for title: Materials Design and Discovery with High-Throughput
 Density Functional Theory: The Open Quantum
 Materials Database (OQMD)

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you see what is wrong here? The affiliation index does use quotes.

**Comment by Kevin-Mattheus-Moerman** [comment]
@raullaasner while trouble shooting this you can try compiling your paper here too: https://whedon.theoj.org/
If it is compiling you can run `@whedon generate pdf` here

**Comment by xuanxu** [comment]
@Kevin-Mattheus-Moerman, @raullaasner: There was an error with the indexing of the affiliations, [this PR](https://github.com/HybriD3-database/MatD3/pull/2) should fix the compiling error.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @xuanxu !

**Comment by Kevin-Mattheus-Moerman** [comment]
@raullaasner can you check the above fix by @xuanxu ?

**Comment by raullaasner** [comment]
@Kevin-Mattheus-Moerman Yes, sorry for the delay. This is fixed now.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01919/joss.01919/10.21105.joss.01919.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@raullaasner can you also work on those missing DOI's? You can run `@whedon check references` and `@whedon generate pdf` here too to check things.

**Comment by Kevin-Mattheus-Moerman** [comment]
@trallard @csoneson @majensen @akeshavan could one of you edit this submission? Thanks!

**Comment by majensen** [comment]
@whedon assign @majensen as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by raullaasner** [comment]
@Kevin-Mattheus-Moerman I added DOIs to the paper references except for the SpringerMaterials citation, which is only a web link. It seems there is no better way to cite it at this point.

**Comment by raullaasner** [comment]
Regarding the proof, would it possible have "3" as a superscript in MatD<sup>3</sup>? In the paper, I had written `MatD<sup>3</sup>` everywhere but this formatting seems not to be present in the proof.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01919/joss.01919/10.21105.joss.01919.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev do you know how to use superscript in the text as the author requests? 

> Regarding the proof, would it possible have "3" as a superscript in MatD3? In the paper, I had written `MatD<sup>3</sup>` everywhere but this formatting seems not to be present in the proof.

**Comment by Kevin-Mattheus-Moerman** [comment]
@raullaasner the editor handling this from here on is @majensen

**Comment by majensen** [comment]
@raullaasner thanks for the submission. If you have thoughts about possible reviewers, please let me know in the thread.

**Comment by majensen** [comment]
Hey @pythonpanda2, would you be willing to review this submission for [JOSS](https://joss.theoj.org)? Please let us know in this thread. Thanks for the consideration!

**Comment by pythonpanda2** [comment]
Hey @majensen , 

Thanks for reaching out to me . I will be happy to do the review.

**Comment by majensen** [comment]
@whedon assign @pythonpanda2 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @pythonpanda2

**Comment by arfon** [comment]
> Regarding the proof, would it possible have "3" as a superscript in MatD3? In the paper, I had written MatD<sup>3</sup> everywhere but this formatting seems not to be present in the proof.

@raullaasner you can do `MatD^3^` which should work.

**Comment by raullaasner** [comment]
@arfon Thanks! I made the change and can confirm that it produces the desired output.

**Comment by majensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01919/joss.01919/10.21105.joss.01919.pdf)

**Comment by majensen** [comment]
Dear @computron - would you be willing to review the [paper](https://github.com/openjournals/joss-papers/blob/joss.01919/joss.01919/10.21105.joss.01919.pdf) in this issue for [Journal of Open Source Software](https://theoj.joss.org)? If you have any questions, please feel free to [email me](mailto:maj.fortinbras@gmail.com) . Thanks for your consideration! --@majensen

**Comment by pythonpanda2** [comment]
@majensen 

I was reviewing the  JOSS Conflict of Interest (COI) Policy.  I regret to inform you that my current employment at ANL and an ongoing collaboration with submitter research group might lead to COI.  


I would like to nominate @aykol for review.

**Comment by majensen** [comment]
Thanks for your diligence on that issue @pythonpanda2 -- @aykol are you willing to review this submission?

**Comment by pythonpanda2** [comment]
@majensen  I would also nominate @dga_smith

**Comment by majensen** [comment]
Hi @dgasmith - would you be willing to review this submission to [JOSS](https://joss.theoj.org)?

**Comment by dgasmith** [comment]
@majensen Yes, happy to review the submission.

**Comment by majensen** [comment]
@whedon assign @dgasmith as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dgasmith

**Comment by computron** [comment]
Hey @majensen , sorry but I am unable to perform this review

**Comment by dgasmith** [comment]
@computron /wave!

I could also suggest @mkhorton.

**Comment by mkhorton** [comment]
I'd be happy to take a look at this, I can't make a strong commitment on time however.

**Comment by majensen** [comment]
Thanks for your response @computron -
@mkhorton - thx - what would be a workable timeline for you?

**Comment by mkhorton** [comment]
Hopefully within the next two weeks but it's difficult to guarantee with
the holidays.

**Comment by majensen** [comment]
@mkhorton understood. I will start the review, but @raullaasner I expect we all will be off and on until 1 Jan - does this sound ok?

**Comment by majensen** [comment]
@whedon add @mkhorton as reviewer

**Comment by whedon** [comment]
OK, @mkhorton is now a reviewer

**Comment by majensen** [comment]
Applying the tacit approval principle, I will start this review. Thanks all.

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1945. Feel free to close this issue now!

**Comment by aykol** [comment]
Sorry for the delayed response. I'm glad new reviewers were find, as I wasn't going to be able to review it.

**Comment by majensen** [comment]
Thanks for following up @aykol !
