### ISSUE TITLE
[PRE REVIEW]: whampy: Python Package to Interact with, Visualize, and Analyze the Wisconsin H-Alpha Mapper - Sky Survey

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1920]
**Submitting author:** @Deech08 (<a href="http://orcid.org/0000-0002-7955-7359">Dhanesh Krishnarao</a>)
**Repository:** <a href="https://github.com/Deech08/whampy" target ="_blank">https://github.com/Deech08/whampy</a>
**Version:** v0.1.0a5
**Editor:** @xuanxu
**Reviewers:** @Gabriel-p, @HeloiseS

**Author instructions**

Thanks for submitting your paper to JOSS @Deech08. **Currently, there isn't an JOSS editor assigned** to your paper.

@Deech08 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.3847/0004-637X/823/2/77 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.1086/378850 is OK
- 10.3847/1538-4357/aa63e6 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01920/joss.01920/10.21105.joss.01920.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@Deech08 thanks for your submission. It looks like you have a BSD license but it is stowed away in a folder along with several other files. I recommend that you create a plain text LICENSE file in your main repository folder. This way GitHub will pick up on the license and render a license badge at the top. Also whedon (our journal system bot) and our reviewers will find it easier to find the license.

**Comment by Kevin-Mattheus-Moerman** [comment]
@xuanxu @mbobra @dfm @leouieda could one of you edit this submission?

**Comment by xuanxu** [comment]
@Kevin-Mattheus-Moerman I can edit this

**Comment by xuanxu** [comment]
@whedon assign @xuanxu as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by Deech08** [comment]
Thanks for agreeing to edit this @xuanxu - I just pushed an update to my whampy repo with the LICENSE.rst file in the main folder.

**Comment by xuanxu** [comment]
:wave: @Gabriel-p would you be willing to review this submission for JOSS? I think your knowledge of Python and Astronomy makes you a good fit for this submission.

**Comment by xuanxu** [comment]
:wave: @ngoldbaum would you be willing to review this submission for JOSS? I think your knowledge of Python and Astrophysics makes you a good fit for this submission.

**Comment by Gabriel-p** [comment]
@xuanxu I'll check it out as soon as I have a few minutes.

**Comment by xuanxu** [comment]
:wave: @HeloiseS would you be willing to review this submission for JOSS? I think your knowledge of Python and Astrophysics makes you a good fit for this submission.

**Comment by Gabriel-p** [comment]
@xuanxu should there be a check list here for the reviewer?

**Comment by HeloiseS** [comment]
Hello

I'm happy to help. By when does this need doing?

Cheers,
Heloise

**Comment by xuanxu** [comment]
@Gabriel-p this is the pre-review. Once I have the two reviewers I’ll start the review in a new issue with a checklist for each of the reviewers. Stay tuned!

**Comment by xuanxu** [comment]
@HeloiseS in the next two/three weeks if possible. Is that ok for you?

**Comment by HeloiseS** [comment]
Yeah should be fine :)

**Comment by xuanxu** [comment]
@whedon add @Gabriel-p as reviewer

**Comment by whedon** [comment]
OK, @Gabriel-p is now a reviewer

**Comment by xuanxu** [comment]
@whedon add @HeloiseS as reviewer

**Comment by whedon** [comment]
OK, @HeloiseS is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1940. Feel free to close this issue now!

**Comment by xuanxu** [comment]
@Gabriel-p @HeloiseS please head over to #1940 where the review will take place.
