### ISSUE TITLE
[PRE REVIEW]: Pyglmnet: Python implementation of elastic-net regularized generalized linear models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1921]
**Submitting author:** @jasmainak (<a href="http://orcid.org/0000-0002-3199-9027">Mainak Jas</a>)
**Repository:** <a href="https://github.com/glm-tools/pyglmnet/" target ="_blank">https://github.com/glm-tools/pyglmnet/</a>
**Version:** v1.1
**Editor:** @arokem
**Reviewers:** professoralkmin, ryEllison

**Author instructions**

Thanks for submitting your paper to JOSS @jasmainak. **Currently, there isn't an JOSS editor assigned** to your paper.

@jasmainak if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1371/journal.pone.0196527 may be missing for title: Active learning of cortical connectivity from two-photon imaging data
- https://doi.org/10.1162/neco_a_01150 may be missing for title: Decoding of neural data using cohomological feature extraction
- https://doi.org/10.1101/609826 may be missing for title: Probing and predicting ganglion cell responses to smooth electrical stimulation in healthy and blind mouse retina
- https://doi.org/10.1101/111450 may be missing for title: Modern machine learning outperforms GLMs at predicting spikes

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01921/joss.01921/10.21105.joss.01921.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@jasmainak thanks for your submission. Can you check those missing DOI's? :point_up:

**Comment by Kevin-Mattheus-Moerman** [comment]
@arokem @akeshavan @mbobra can one of you edit this submission? Thanks

**Comment by jasmainak** [comment]
Thanks to @geektoni, the missing DOIs should be fixed now!

**Comment by arokem** [comment]
Sure. I can take this one.

**Comment by arokem** [comment]
@whedon assign arokem as editor

**Comment by whedon** [comment]
OK, the editor is arokem

**Comment by arokem** [comment]
👋 ryEllison : would you be willing to review this paper for JOSS?

**Comment by arokem** [comment]
👋 @b-freitas : would you be willing to review this article for JOSS?

**Comment by arokem** [comment]
👋 @ryEllison : would you be willing to review this  article for JOSS?

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01921/joss.01921/10.21105.joss.01921.pdf)

**Comment by arokem** [comment]
:wave: @nmoran : would you be willing to review this  paper for JOSS?

**Comment by arokem** [comment]
:wave: @zoomelectrico: would you be willing to review this paper for JOSS?

**Comment by arokem** [comment]
👋 @prateekiiest: would you be willing to review this paper for JOSS?

**Comment by arokem** [comment]
👋 @professoralkmin: would you be willing to review this paper for JOSS?

**Comment by ryEllison** [comment]
Yes.

R

**Comment by professoralkmin** [comment]
Yes

Em seg, 16 de dez de 2019 10:31 AM, ryEllison <notifications@github.com>
escreveu:

**Comment by arokem** [comment]
@whedon assign professoralkmin as reviewer

**Comment by whedon** [comment]
OK, the reviewer is professoralkmin

**Comment by arokem** [comment]
@whedon add ryEllison as reviewer

**Comment by whedon** [comment]
OK, ryEllison is now a reviewer

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1959. Feel free to close this issue now!

**Comment by arokem** [comment]
@ryEllison @professoralkmin : thank you both for taking this on! I've started the review over on #1959, so head over there for your checklists. Please let me know if you have any questions. Feel free to post issues on the software repository related to this review, and feel free to tag me into issues if any questions come up.
