### ISSUE TITLE
[PRE REVIEW]: WulffPack: A Python package for Wulff constructions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1922]
**Submitting author:** @magnusrahm (<a href="http://orcid.org/0000-0002-6777-0371">Magnus Rahm</a>)
**Repository:** <a href="https://gitlab.com/materials-modeling/wulffpack" target ="_blank">https://gitlab.com/materials-modeling/wulffpack</a>
**Version:** 1.0
**Editor:** @drvinceknight
**Reviewers:** @EduPH, @mzszym, @corybrunson

**Author instructions**

Thanks for submitting your paper to JOSS @magnusrahm. **Currently, there isn't an JOSS editor assigned** to your paper.

@magnusrahm if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1922 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you help resolve this error :point_up:

**Comment by Kevin-Mattheus-Moerman** [comment]
@magnusrahm where is your `paper.md` file located?

**Comment by magnusrahm** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by magnusrahm** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01922/joss.01922/10.21105.joss.01922.pdf)

**Comment by magnusrahm** [comment]
@Kevin-Mattheus-Moerman The paper is currently in a a custom branch (joss-paper). Sorry for the confusion!

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1524/zkri.1901.34.1.449 is OK
- 10.1016/0022-0248(83)90184-7 is OK
- https://doi.org/10.1016/0001-6160(67)90206-4 is OK
- https://doi.org/10.1016/j.commatsci.2012.10.028 is OK
- 10.1007/s10853-012-6739-x is OK
- 10.1016/S0927-0256(97)00167-5 is OK
- 10.1145/235815.235821 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1088/1361-648X/aa680e is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@kbarnhart @brainstorm @meg-simula @drvinceknight could one of you edit this submission?

**Comment by kbarnhart** [comment]
I’m on holiday until December 7, so I’d prefer not to.

**Comment by drvinceknight** [comment]
I'm happy to pick it up :+1:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @drvinceknight as editor

**Comment by whedon** [comment]
OK, the editor is @drvinceknight

**Comment by drvinceknight** [comment]
@corybrunson I realise that this is a python package and not R but your knowledge of geometry could be nonetheless helpful here in reviewing. Would you be able to take a look at the paper and let me know if you might be able to review?

**Comment by drvinceknight** [comment]
@EduPH would you consider reviewing this paper on a topic called "Wulff Constructions", I'm not 100 familiar but I believe your familiarity with algebraic topology could be relevant here. Let me know your thoughts.

**Comment by drvinceknight** [comment]
@mzszym is this paper on a modelling technique of nanoparticles something you could review? 

EDIT: If you have not reviewed for JOSS before there is documentation here https://joss.readthedocs.io/en/latest/reviewer_guidelines.html and I'd be very happy to assist in any way I can.

**Comment by drvinceknight** [comment]
@jarvist would you be able to review this paper on nanoparticles?

If you have not reviewed for JOSS before there is documentation here https://joss.readthedocs.io/en/latest/reviewer_guidelines.html and I'd be very happy to assist in any way I can.

**Comment by corybrunson** [comment]
@drvinceknight thank you for the invitation! The package does look interesting. I can't commit the time this or next week, but if reviewers are still sought then i can check back next weekend.

**Comment by mzszym** [comment]
@drvinceknight : I think I could review it as well. The code looks OK and also I im in the domain (solid state physicist) by training. If I do it, what is the expected dead-line to report?

**Comment by EduPH** [comment]
@drvinceknight Hi! If I am still needed I can :)

**Comment by drvinceknight** [comment]
Thank you all, if it's ok I'd appreciate all of your reviews on this one (I think the various disciplines and specialities will complement each other and help arrive at a great paper).

In terms of deadline, @mzszym I understand how busy anyone is so anything over the next month or so would be great but if that's not going to be possible that's ok just let me know.

**Comment by drvinceknight** [comment]
@whedon set @EduPH as reviewer

**Comment by drvinceknight** [comment]
@whedon assign @EduPH as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @EduPH

**Comment by drvinceknight** [comment]
@whedon add @mzszym as reviewer

**Comment by whedon** [comment]
OK, @mzszym is now a reviewer

**Comment by drvinceknight** [comment]
@whedon add @corybrunson as reviewer

**Comment by whedon** [comment]
OK, @corybrunson is now a reviewer

**Comment by drvinceknight** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1944. Feel free to close this issue now!

**Comment by drvinceknight** [comment]
The review will take place on #1944, there is a checklist there for each of the reviewers. If there's anything at all that I can assist with please let me know.
