### ISSUE TITLE
[PRE REVIEW]: Annotation Sniffer: A tool to Extract Code Annotations Metrics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1923]
**Submitting author:** @phillima (<a href="http://orcid.org/0000-0002-8358-4405">Phyllipe Lima</a>)
**Repository:** <a href="https://github.com/phillima/asniffer/" target ="_blank">https://github.com/phillima/asniffer/</a>
**Version:** v2.0.0
**Editor:** @gkthiruvathukal
**Reviewers:** @arcuri82, @danieledipompeo

**Author instructions**

Thanks for submitting your paper to JOSS @phillima. **Currently, there isn't an JOSS editor assigned** to your paper.

@phillima if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1016/j.jss.2017.11.024 is OK
- 10.1007/3-540-39538-5 is OK
- 10.1145/1943226.1943230 is OK
- https://doi.org/10.1016/j.jss.2012.12.024 is OK
- 10.1145/1943226.1943230 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01923/joss.01923/10.21105.joss.01923.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@gkthiruvathukal @mjsottile @VivianePons @drvinceknight can one of you edit this one?

**Comment by gkthiruvathukal** [comment]
@Kevin-Mattheus-Moerman Yes, please assign to me!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by phillima** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01923/joss.01923/10.21105.joss.01923.pdf)

**Comment by phillima** [comment]
Checking the list for potential reviewers, perhaps @xirdneh and @arcuri82 ?

**Comment by gkthiruvathukal** [comment]
Thanks, @phillima. I'll get to work on this submission in the next couple of days. It is a busy week at the university, but I will get on it as soon as possible.

**Comment by gkthiruvathukal** [comment]
Hi @xirdneh, @arcuri82, and @BasTesterink, are any two of you willing to contribute a review for this JOSS submission?

**Comment by arcuri82** [comment]
Hi, yes, I can be a reviewer

**Comment by phillima** [comment]
Thank you @gkthiruvathukal for accepting the role of editor of this paper, and thank you @arcuri82 for accepting the reviewer role. @gkthiruvathukal , I checked the list again and ran into these name for potential reviewers: @chrisma @danieledipompeo @sambitdash @fhg @mado89 .

**Comment by gkthiruvathukal** [comment]
@whedon assign @arcuri82 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arcuri82

**Comment by gkthiruvathukal** [comment]
@chrisma @danieledipompeo @sambitdash @FHG @mado89, are any of you willing to contribute a review or this JOSS submission? I need one more reviewer. Thanks!

**Comment by danieledipompeo** [comment]
Hi, I can revise the paper. Let me know the deadline.

**Comment by gkthiruvathukal** [comment]
Hi @danieledipompeo, you meant _review_, right? It is the holidays, so we understand you may need time. I'd like to aim for reviews to be complete sometime in January.

**Comment by danieledipompeo** [comment]
> Hi @danieledipompeo, you meant _review_, right? It is the holidays, so we understand you may need time. I'd like to aim for reviews to be complete sometime in January.

Yes, I can be a reviewer :). The deadline is fine with me.

**Comment by gkthiruvathukal** [comment]
@whedon add @danieledipompeo as reviewer

**Comment by whedon** [comment]
OK, @danieledipompeo is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1960. Feel free to close this issue now!

**Comment by chrisma** [comment]
Hi @gkthiruvathukal , thanks for considering me as a reviewer for this paper. This would be my first time reviewing for JOSS, so maybe being an additional, third reviewer would be a good start. Is this possible?
Thanks!

**Comment by gkthiruvathukal** [comment]
@chrisma I'd like to go with 2 for now. Should we get to a point where we truly need a third, please mention me when doing review feedback. I will be happy to help answer any questions! I want to get review started now as I am about to go on break.  Thanks for saying yes. (I hope I can interpret your response as a yes!)

**Comment by gkthiruvathukal** [comment]
@chrisma My bad, I already had 2 reviewers. Can I reach out to you for something else in the future?

**Comment by gkthiruvathukal** [comment]
/ooo December 18, 2019 until January 5, 2020

**Comment by chrisma** [comment]
> Can I reach out to you for something else in the future?

@gkthiruvathukal Of course! I'd be happy to review.
