### ISSUE TITLE
[PRE REVIEW]: OpenTripPlanner for R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1924]
**Submitting author:** @mem48 (<a href="http://orcid.org/0000-0002-9488-9183">Malcolm Morgan</a>)
**Repository:** <a href="https://github.com/ropensci/opentripplanner" target ="_blank">https://github.com/ropensci/opentripplanner</a>
**Version:** v0.2.0
**Editor:** @danielskatz
**Reviewers:** @danielskatz

**Author instructions**

Thanks for submitting your paper to JOSS @mem48. **Currently, there isn't an JOSS editor assigned** to your paper.

@mem48 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.trpro.2018.09.027 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-642-15775-2_25 may be missing for title: Fast Routing in Very Large Public Transportation Networks Using Transfer Patterns

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01924/joss.01924/10.21105.joss.01924.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@mem48 can you check that missing DOI :point_up:

**Comment by Kevin-Mattheus-Moerman** [comment]
@csoneson @danielskatz @kbarnhart could one of you edit this submission? Thanks.

**Comment by csoneson** [comment]
Looks like this submission was [reviewed and accepted by rOpenSci](https://github.com/ropensci/software-review/issues/295).

**Comment by mem48** [comment]
Hi @csoneson yes your right This package has been reviewed by rOpenSci: https://github.com/ropensci/software-review/issues/295, @ropensci/editors

@Kevin-Mattheus-Moerman I've just updated the .bib file with the missing DOI

**Comment by danielskatz** [comment]
I'll go ahead and move this through the expedited process this morning.

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @danielskatz

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1926. Feel free to close this issue now!
