### ISSUE TITLE
[PRE REVIEW]: Analyzing D-Wave Quantum Macro Assembler Security

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1925]
**Submitting author:** @5998 (<a href="http://orcid.org/0000-0003-0884-3566">Hesham H.Alsaadi</a>)
**Repository:** <a href="https://github.com/5998/Quantum-Security/" target ="_blank">https://github.com/5998/Quantum-Security/</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @5998. **Currently, there isn't an JOSS editor assigned** to your paper.

@5998 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01925/joss.01925/10.21105.joss.01925.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2669594 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-030-14070-0_19 may be missing for title: Analyzing D-Wave Quantum Macro Assembler Security
- https://doi.org/10.1016/j.measurement.2019.107139 may be missing for title: A Deep Learning Based Static Taint Analysis Approach for IoT Software Vulnerability Location
- https://doi.org/10.1109/bigcomp.2016.7425809 may be missing for title: Improving vulnerability prediction accuracy with secure coding standard violation measures
- https://doi.org/10.1109/spw.2018.00033 may be missing for title: Forensic analysis of ransomware families using static and dynamic analysis
- https://doi.org/10.1109/ntms.2018.8328710 may be missing for title: Penetration and Security of OpenSSH Remote Secure Shell Service on Raspberry Pi 2

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @5998 - This submission appears out of scope for JOSS.

It appears to be a notebook to accompany a full paper, making some visualizations in the paper more reproducible, rather than reusable, contributable, citeable open source software.

Given this, the authors are encouraged to deposit the notebook and associated metadata on Figshare (or a similar archival repository) and get a DOI. You then can cite the DOI of the notebook in the paper (if not already published), as a form of supplementary material that is not surrendered to the journal, but owned by the authors.

**Comment by danielskatz** [comment]
I have marked it as rejected.

**Comment by danielskatz** [comment]
If you want to submit a future version to JOSS, you would need to do so with open source software (usually in the form of a library) that others can use, cite, and contribute to.  A notebook could be a good tutorial for such software.
