### ISSUE TITLE
[PRE REVIEW]: rgsp: An R Package for Quality Control Charts under Repetitive Group Sampling Plan based on Cpk

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1927]
**Submitting author:** @myaseen208 (<a href="http://orcid.org/0000-0002-5923-1714">Muhammad Yaseen</a>)
**Repository:** <a href="https://github.com/myaseen208/rgsp_article" target ="_blank">https://github.com/myaseen208/rgsp_article</a>
**Version:** 0.2.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @myaseen208. **Currently, there isn't an JOSS editor assigned** to your paper.

@myaseen208 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1080/02664760500446010 may be missing for title: Repetitive group sampling procedure for variables inspection
- https://doi.org/10.1080/00401706.1965.10490222 may be missing for title: Design and evaluation of a repetitive group sampling plan
- https://doi.org/10.1109/access.2016.2620241 may be missing for title: Capability indices for non-normal distribution using Gini’s mean difference as measure of variability
- https://doi.org/10.1016/j.omega.2005.01.018 may be missing for title: An effective decision making method for product acceptance
- https://doi.org/10.1016/j.ejor.2006.11.032 may be missing for title: A variables sampling plan based on Cpmk for product acceptance determination

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01927/joss.01927/10.21105.joss.01927.pdf)

**Comment by danielskatz** [comment]
👋 @myaseen208 - I don't see any software to be reviewed in the repository you indicated.  Where is the software?  You've also submitted .pdf and .log files for paper, which don't need to be in the repository.

**Comment by myaseen208** [comment]
@danielskatz - software is here [https://github.com/myaseen208/rgsp](url). Should I keep both software and paper in the same repository.

**Comment by danielskatz** [comment]
Yes - you should probably withdraw this submission, and add the paper (.md and .bib files only) to the repo that contains the software, then make a new submission with the repo that will then contain both the software and the paper.

In addition, I see some issues when I look at the source repo: https://github.com/myaseen208/rgsp

* There is no LICENSE file
* The README doesn't contain enough context about the software, such as what kinds of research it is used in
* The code looks fairly small - there is some chance this will be considered a minor utility, out of scope for JOSS

Overall, please review the submission instructions in https://joss.readthedocs.io/en/latest/submitting.html carefully before making a new submission

**Comment by myaseen208** [comment]
@danielskatz - Thanks for your guidance. Followed the instructions and needful done.
