### ISSUE TITLE
[PRE REVIEW]: Pooch: A friend to fetch your data files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1928]
**Submitting author:** @leouieda (<a href="http://orcid.org/0000-0001-6123-9515">Uieda, L</a>)
**Repository:** <a href="https://github.com/fatiando/pooch" target ="_blank">https://github.com/fatiando/pooch</a>
**Version:** v0.7.0
**Editor:** @danielskatz
**Reviewers:** @hmaarrfk, @martindurant

**Author instructions**

Thanks for submitting your paper to JOSS @leouieda. **Currently, there isn't an JOSS editor assigned** to your paper.

@leouieda if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.7717/peerj.453 is OK
- 10.5065/D6WW7G29 is OK
- 10.21105/joss.00957 is OK
- 10.5281/ZENODO.3086002 is OK
- 10.5281/ZENODO.3542092 is OK
- 10.5281/ZENODO.1450596 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01928/joss.01928/10.21105.joss.01928.pdf)

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@leouieda - can you suggest some reviewers for this submission?

**Comment by leouieda** [comment]
Hi @danielskatz thank you for editing the submission. From the list of reviewers, here are a few that might be interested: @krother @dghoshal-lbl @mih Others that come to mind are the main developers of Intake, which has some similar functionality to Pooch: @martindurant and @jsignell. There is also @hmaarrfk who is implementing Pooch as the download manager for scikit-image.

**Comment by danielskatz** [comment]
👋 @krother & @martindurant - would you be willing to review this submission for JOSS?  (See https://joss.readthedocs.io/en/latest/reviewer_guidelines.html for what reviewing for JOSS)

**Comment by martindurant** [comment]
The authors of Pooch ought to know about Intake ( https://github.com/fatiando/rockhound/issues/43 ), and indeed the ability of Pooch to be hooked into other systems is an important point. Will try to find time for a proper review, but don't want to commit.

**Comment by danielskatz** [comment]
👋 @jsignell - would you be willing to review this submission for JOSS? (See https://joss.readthedocs.io/en/latest/reviewer_guidelines.html for what reviewing for JOSS)

**Comment by danielskatz** [comment]
👋 @hmaarrfk - would you be willing to review this submission for JOSS?  (See https://joss.readthedocs.io/en/latest/reviewer_guidelines.html for what reviewing for JOSS)

**Comment by danielskatz** [comment]
👋 @dghoshal-lbl - would you be willing to review this submission for JOSS?  (See https://joss.readthedocs.io/en/latest/reviewer_guidelines.html for what reviewing for JOSS)

**Comment by hmaarrfk** [comment]
Is there a version that can be downloaded with double spacing so we may write our notes on it?

**Comment by danielskatz** [comment]
No, sorry

Note that the [paper](https://github.com/openjournals/joss-papers/blob/joss.01928/joss.01928/10.21105.joss.01928.pdf) is fairly short, and the review is of both the paper and software, using a checklist for the [reviewer criteria](https://joss.readthedocs.io/en/latest/review_criteria.html)

JOSS reviewers generally write note either here as comments, or in the source repository as issues, or potentially pull requests on the .md file in the source repository

**Comment by hmaarrfk** [comment]
got it, i typically go through my notes on paper and organize them again a second time, just being visual, it sometimes helps to be able to scribble things down.

**Comment by danielskatz** [comment]
Are you willing to review this?

**Comment by hmaarrfk** [comment]
yes.

**Comment by danielskatz** [comment]
thank you - I'll assign you in our system, but the review itself won't start until we get a second reviewer, and it will take place in a new "review" issue, not this "pre-review" issue

**Comment by danielskatz** [comment]
@whedon assign @hmaarrfk as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @hmaarrfk

**Comment by danielskatz** [comment]
👋 @martindurant - can I ask you again if you would be willing to be a reviewer?

**Comment by martindurant** [comment]
Alright, I'll have a little look

**Comment by danielskatz** [comment]
Thanks - I'll add you and we can start the review

**Comment by danielskatz** [comment]
@whedon add @martindurant as reviewer

**Comment by whedon** [comment]
OK, @martindurant is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1943. Feel free to close this issue now!

**Comment by danielskatz** [comment]
We'll move over to #1934 now...
