### ISSUE TITLE
[PRE REVIEW]: ROSS - Rotordynamic Open Source Software

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1929]
**Submitting author:** @raphaeltimbo (<a href="http://orcid.org/0000-0001-7689-5486">Raphael Silva</a>)
**Repository:** <a href="https://github.com/ross-rotordynamics/ross" target ="_blank">https://github.com/ross-rotordynamics/ross</a>
**Version:** v0.2.0
**Editor:** @meg-simula
**Reviewers:** @srmnitc, @nnadeau

**Author instructions**

Thanks for submitting your paper to JOSS @raphaeltimbo. **Currently, there isn't an JOSS editor assigned** to your paper.

@raphaeltimbo if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation
- https://doi.org/10.1007/978-3-662-09786-1 may be missing for title: Rotordynamik

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01929/joss.01929/10.21105.joss.01929.pdf)

**Comment by danielskatz** [comment]
👋 @raphaeltimbo - note that whedon found 2 DOIs that should be added to your paper. Also, please check the references to make sure the cases (upper vs lower) are correct, and add {}s in the .bib file where needed to protect cases. Once you have made changes, enter a new comment in this issue with ```@whedon generate pdf``` to regenerate the pdf to make sure it looks right.

**Comment by danielskatz** [comment]
I also see a number of spelling mistakes in the paper - please check this as well and make needed fixes.  e.g. softares, comercial, ...

**Comment by danielskatz** [comment]
👋 @meg-simula - would you be willing to edit this submission?

**Comment by meg-simula** [comment]
Yes, absolutely.

**Comment by raphaeltimbo** [comment]
@danielskatz, thanks for the comments!
I have changed the paper here ross-rotordynamics/ross#398 to fix the issues.

**Comment by raphaeltimbo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01929/joss.01929/10.21105.joss.01929.pdf)

**Comment by raphaeltimbo** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1017/CBO9780511780509 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1002/9780470903704 is OK
- 10.1002/9783527651894 is OK
- 10.1007/978-3-662-09786-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon assign @meg-simula as editor

**Comment by whedon** [comment]
OK, the editor is @meg-simula

**Comment by danielskatz** [comment]
👋 @meg-simula - it looks like this is waiting for you to find/assign reviewers...

**Comment by raphaeltimbo** [comment]
If you need suggestions, I have filtered the joss-reviewers list for python and mechanical engineering:
- kyleniemeyer	
- moorepants	
- trallard	
- nnadeau
- ctdegroot
- srmnitc

**Comment by meg-simula** [comment]
Hi @raphaeltimbo, thank you very much for this submission and the suggested reviewers - my apologies for the delay in editorial handling. Before we proceed, could I ask you to briefly elaborate on the (potential) use of ROSS as *research* software?

**Comment by raphaeltimbo** [comment]
Hi @meg-simula! 
I have some examples where we can use models that ROSS generates in research:
- Evaluate the impact that components such as bearings and seals have on the rotor. Particularly, we have some studies on how the uncertainties on the dynamic coefficients for these components can impact the rotor dynamic;
- Generate data to test learning algorithms that should diagnose machine failure. We can, for example, use ROSS to generate a rotor with some problem such as an unbalance or misalignment, and then use the output data from this model to test the learning algorithm and see how good it is in diagnosing the problem;
- We also have an interest in model updating. Here we could use vibrations measurements from a rotor to update a model generated by ROSS. 

Let me know if we need to update the paper and also if you need more clarification.

Thanks!

**Comment by meg-simula** [comment]
Ok, thanks @raphaeltimbo for clarifying. I'll proceed by finding a pair or reviewers, starting with your suggestions.

**Comment by meg-simula** [comment]
@moorepants, @trallard, @nnadeau, @ctdegroot, @srmnitc: Would either of you be willing and available to review this submission for JOSS?

**Comment by srmnitc** [comment]
@meg-simula I could review this submission for JOSS. However, I will be away for couple of days, but I will be able to start the review next week.

**Comment by meg-simula** [comment]
@srmnitc That would be great, thanks! I'll assign you.

**Comment by meg-simula** [comment]
@whedon assign @srmnitc as reviewer

**Comment by whedon** [comment]
OK, @srmnitc is now a reviewer

**Comment by ctdegroot** [comment]
Unfortunately I am not available at this time due to upcoming travel.

**Comment by danielskatz** [comment]
👋 @meg-simula - it seems like another reviewer is needed to move this into the review stage?

**Comment by trallard** [comment]
Hi @meg-simula and thanks for the patience. I am afraid that I do not have the bandwidth to do this at the moment

**Comment by meg-simula** [comment]
Thanks for your response @trallard! My apologies @raphaeltimbo for the delay in finding reviewers for this submission (still in progress!), and thanks for the patience @srmnitc.

**Comment by nnadeau** [comment]
@meg-simula i'm available for reviewing :)

**Comment by meg-simula** [comment]
Fantastic, thanks @nnadeau. I'll get the review issue started then.

**Comment by meg-simula** [comment]
@whedon add @nnadeau as reviewer

**Comment by whedon** [comment]
OK, @nnadeau is now a reviewer

**Comment by meg-simula** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2120.
