### ISSUE TITLE
[REVIEW]: NeuroDiffEq: A Python package for solving differential equations with neural networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1931]
**Submitting author:** @feiyu-chen96 (<a href="http://orcid.org/0000-0002-0476-9998">Feiyu Chen</a>)
**Repository:** <a href="https://github.com/odegym/neurodiffeq" target ="_blank">https://github.com/odegym/neurodiffeq</a>
**Version:** 1.0.0
**Editor:** @drvinceknight
**Reviewer:** @dawbarton, @marcharper
**Archive:** <a href="https://doi.org/10.5281/zenodo.3676028" target="_blank">10.5281/zenodo.3676028</a>

## Status

[![status](https://joss.theoj.org/papers/b7cd3f461c331636a8170563cfb7cbda/status.svg)](https://joss.theoj.org/papers/b7cd3f461c331636a8170563cfb7cbda)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b7cd3f461c331636a8170563cfb7cbda"><img src="https://joss.theoj.org/papers/b7cd3f461c331636a8170563cfb7cbda/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b7cd3f461c331636a8170563cfb7cbda/status.svg)](https://joss.theoj.org/papers/b7cd3f461c331636a8170563cfb7cbda)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/odegym/neurodiffeq" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dawbarton & @marcharper, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @drvinceknight know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/odegym/neurodiffeq">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@feiyu-chen96) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/odegym/neurodiffeq">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@feiyu-chen96) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dawbarton, @marcharper it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1063/1.4992752 is OK
- 10.1016/0893-6080(89)90020-8 is OK
- 10.1109/72.712178 is OK
- 10.1109/TNN.2009.2020735 is OK
- 10.1145/3093338.3104151 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01931/joss.01931/10.21105.joss.01931.pdf)

**Comment by drvinceknight** [comment]
I will be checking GitHub in a limited capacity over the next couple of weeks.

**Comment by marcharper** [comment]
I am declaring a potential conflict (IMO very minor)  -- this library uses torch/pytorch, my current employer creates a competing package (tensorflow) which I have not contributed to.

Authors: Feiyu Chen appears to have written the vast majority of the code along with another contributor, David Sondak. The two other authors do not appear to have contributed to the code AFAICT and are collaborators with the other authors. A very recent contributor (Johnny-Wish) is not listed as an author.

Installation: OK, but
- the given installation command does not install the requirements
- I additionally needed to run `pip install torch` to be able to import the package in a python interpreter
- I further needed to install jupyter, matplotlib, scipy in the venv to run examples

Examples: The examples run fine on a decent laptop.

Running tests: Tests are present but there are no instructions on how to run tests (at least not in a clearly visible place)
- Additional packages needed for running tests: `pip install pandas pytest seaborn`
- Tests can then be run with `/.../env/bin/pytest neurodiffpy`
- The tests open a lot of images and redraw them repeatedly; recommend closing them before moving on to subsequent tests / only displaying once

Contribution documentation is present but minimal. As noted there is a new recent contributor so seemingly the documentation is sufficient.

Citations and references look fine. It may be worth citing some of the more recent work on using neural networks to solve differential equations, if they are relevant. I defer to the authors choices.

**Comment by drvinceknight** [comment]
Hi @dawbarton apologies for the nag but any idea when you might be able to complete your review?

**Comment by dawbarton** [comment]
Thanks for the nag; I'll get onto it asap (maybe today but definitely by the end of the week).

**Comment by dawbarton** [comment]
Overall, the paper reads well and covers the material well. I agree with the comments of the other reviewer. It would be good to mention the dependence on torch - I installed the respository directly rather than via conda (since I don't have conda installed) and so also needed to install torch separately. (Easy enough via pip, but still needs doing.)

The examples run well on my laptop, though I wouldn't necessarily describe them as real-world examples. (I'd be curious to see it applied to a truly real-world example where there are significant nonlinearities.)

The justification for this package in the paper is perfectly reasonable, though the justification in the docs is far less accurate. The line "While these methods are effective and adequate, their solutions are discrete." is not entirely correct; there are many numerical methods for solving DEs that produce a continuous output.

The methods section of the paper is very broad-brush in that it doesn't go into any detail about the formulation of the problem and only shows a very high-level interpretation of the differential equation. There are many other questions I'm interested in, such as how is the derivative operator discretized, though I appreciate that this is a software paper rather than a paper on the methods and so I can understand why it isn't included.

All the checkboxes are OK. From my perpective, other than mentioning about torch in the installation section it's good to go.

**Comment by feiyu-chen96** [comment]
Thank you @marcharper and @dawbarton for your time and reviews!

## Review 1 (@marcharper)

1. on the authors: There are 3 new contributors to the package since the initial submission. They've be added to the authors (Shuheng @Johnny-Wish, Devansh @devanshkv, and Marco @marco-digio).
2. on installation and testing: Thanks! The installation section is now updated to include commands to install dependencies. Since those are still extra steps required from the user that could have been done by us, we will publish the package on PyPI in the future. The testing command is now included as well.

## Review 2 (@dawbarton)

1. on installation: Thanks! For the virtual environment, we've added `venv` as an alternative to `conda`. It comes with Python standard library so the user won't need to install extra packages. The requirements.txt now includes torch as well.
1. on real-world examples: Yes we agree that the examples included in the test and documentation are more or less toy problems. We are working on some more real-world problems at present. There's an ongoing project solving equations in general relativity. I'll also include some fluid problems in documents as my thesis progresses.
3. on documentation: Thanks! The motivation section in the documentation and README is indeed not accurate. It is now updated. For the methods section, we have added more explanation on how the software is implemented.

**Comment by drvinceknight** [comment]
Thank you for your time @dawbarton and @marcharper if you could confirm you're happy with the modifications described that would be great.

**Comment by dawbarton** [comment]
All looks good to me.

**Comment by marcharper** [comment]
Confirmed

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01931/joss.01931/10.21105.joss.01931.pdf)

**Comment by drvinceknight** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1063/1.4992752 is OK
- 10.1016/0893-6080(89)90020-8 is OK
- 10.1109/72.712178 is OK
- 10.1109/TNN.2009.2020735 is OK
- 10.1145/3093338.3104151 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by drvinceknight** [comment]
I have re read the manuscript and checked the references and everything looks good to me.

Could you make a Zenodo archive, and report the DOI here and could you also confirm the version number please.

When you make the archive could you check that it has the correct metadata (title and author list), to ensure that it matches the paper.

**Comment by feiyu-chen96** [comment]
Thanks for checking the manuscript again! The Zenodo archive's DOI is 10.5281/zenodo.3674095, version 1.0.0.

**Comment by drvinceknight** [comment]
@whedon set 10.5281/zenodo.3674095 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3674095" target="_blank">10.5281/zenodo.3674095</a> is the archive.

**Comment by drvinceknight** [comment]
@openjournals/joss-eics this paper should be ready for publication now :+1:

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01931/joss.01931/10.21105.joss.01931.pdf)

**Comment by kyleniemeyer** [comment]
Hi @feiyu-chen96, it looks like your Zenodo archive at https://doi.org/0.5281/zenodo.3674095 only contains the articlePDF. This is supposed to be an archive of the entire software repository, not the article—we handle archiving of that.

Can you please do that and provide the new DOI here?

**Comment by drvinceknight** [comment]
Apologies for missing that @kyleniemeyer.

**Comment by feiyu-chen96** [comment]
@kyleniemeyer @drvinceknight Sorry that I misunderstood what should be put in the archive. The new DOI is 10.5281/zenodo.3676028

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.3676028 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3676028" target="_blank">10.5281/zenodo.3676028</a> is the archive.

**Comment by kyleniemeyer** [comment]
@feiyu-chen96 no worries, thanks for your quick action

**Comment by kyleniemeyer** [comment]
Hi @feiyu-chen96, regarding the article, I have just two minor corrections:
- in the first paragraph, you should combine the references to Seefeldt and Smith, like this: `[@author1:2001; @author2:2001]`, which will make them look like "(Author1 et al., 2001; Author2 et al., 2002)"
- in the second paragraph, insert "and" after "(2) good interpolation properties, "

**Comment by feiyu-chen96** [comment]
@kyleniemeyer Thanks! I've updated the paper.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01931/joss.01931/10.21105.joss.01931.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1328

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1328, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1230232982281183232) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1329
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01931](https://doi.org/10.21105/joss.01931)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @feiyu-chen96 on your article's publication in JOSS! 

Many thanks to @dawbarton and @marcharper for reviewing this, and  @drvinceknight for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01931/status.svg)](https://doi.org/10.21105/joss.01931)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01931">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01931/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01931/status.svg
   :target: https://doi.org/10.21105/joss.01931
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01931/status.svg)](https://doi.org/10.21105/joss.01931)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
