### ISSUE TITLE
[PRE REVIEW]: rgsp: An R Package for Quality Control Charts under Repetitive Group Sampling Plan based on Cpk

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1932]
**Submitting author:** @myaseen208 (<a href="http://orcid.org/0000-0002-5923-1714">Muhammad Yaseen</a>)
**Repository:** <a href="https://github.com/myaseen208/rgsp" target ="_blank">https://github.com/myaseen208/rgsp</a>
**Version:** 0.2.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @myaseen208. **Currently, there isn't an JOSS editor assigned** to your paper.

@myaseen208 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1932 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1932 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@arfon - sometimes @whedon is ok with paper.Rmd (see the previous version of this submission in https://github.com/openjournals/joss-reviews/issues/1927 and https://github.com/myaseen208/rgsp_article), but here it's not.  Do you know why not?

**Comment by myaseen208** [comment]
@whedon  Added apa.csl which was missing.

**Comment by myaseen208** [comment]
@danielskatz  Added apa.csl which was missing.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1932 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@myaseen208 - @whedon should only need the .md and .bib files...

**Comment by arfon** [comment]
> @arfon - sometimes @whedon is ok with paper.Rmd (see the previous version of this submission in #1927 and https://github.com/myaseen208/rgsp_article), but here it's not. Do you know why not?

Whedon is never OK with a `paper.Rmd` file. In #1927, there was also a `paper.md` file which Whedon was using to compile the paper.

In this submission, the author needs to rename the `paper.Rmd` to `paper.md`

**Comment by myaseen208** [comment]
@arfon @danielskatz : Added `paper.md`.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01932/joss.01932/10.21105.joss.01932.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1080/02664760500446010 may be missing for title: Repetitive group sampling procedure for variables inspection
- https://doi.org/10.1080/00401706.1965.10490222 may be missing for title: Design and evaluation of a repetitive group sampling plan
- https://doi.org/10.1109/access.2016.2620241 may be missing for title: Capability indices for non-normal distribution using Gini’s mean difference as measure of variability
- https://doi.org/10.1016/j.omega.2005.01.018 may be missing for title: An effective decision making method for product acceptance
- https://doi.org/10.1016/j.ejor.2006.11.032 may be missing for title: A variables sampling plan based on Cpmk for product acceptance determination

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
Hi @myaseen208 - I've consulted with the JOSS editorial team and we've concluded that this submission is not in scope for JOSS as it falls into our 'minor utility' category.

Thanks again for your interest in JOSS.
