### ISSUE TITLE
[PRE REVIEW]: GroundwaterDupuitPercolator: A Landlab component for groundwater flow

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1933]
**Submitting author:** @davidlitwin (<a href="http://orcid.org/0000-0002-8097-4029">David Litwin</a>)
**Repository:** <a href="https://github.com/landlab/landlab" target ="_blank">https://github.com/landlab/landlab</a>
**Version:** v.1.11
**Editor:** @kthyng
**Reviewers:** @dvalters, @nicgaspar

**Author instructions**

Thanks for submitting your paper to JOSS @davidlitwin. The JOSS editor @kthyng, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@davidlitwin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kthyng it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@kthyng) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1933 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
👋 @kthyng - again, sorry to have assigned this to you accidentally...

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1029/WR006i005p01296 is OK
- 10.1016/S0167-5648(09)70009-7 is OK
- 10.1029/2002WR001728 is OK
- 10.1016/j.advwatres.2017.09.008 is OK
- 10.1002/esp.1369 is OK
- 10.1016/j.jhydrol.2003.12.043 is OK
- 10.1002/2014WR015809 is OK
- 10.1002/2013WR013918 is OK
- 10.1029/WR007i005p01256 is OK
- 10.1126/science.aaf7891 is OK
- 10.1016/j.jhydrol.2008.11.002 is OK
- 10.1029/92WR00802 is OK
- 10.5194/esurf-5-21-2017 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @kthyng - would you be willing to edit this submission?

**Comment by kthyng** [comment]
Yep I can do it!

**Comment by kthyng** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01933/joss.01933/10.21105.joss.01933.pdf)

**Comment by kthyng** [comment]
Hi @DavidLitwin! Can you please look through the list of volunteer reviewers and suggest about 5 who you think would be good fits? You can also recommend others that you know of even if they are not on the list.

https://bit.ly/joss-reviewers

**Comment by DavidLitwin** [comment]
Hi @kthyng, I would recommend @nathanlyons, @nicgaspar, @dvalters, @rreinecke, and @margauxmouchene.

**Comment by dvalters** [comment]
I'm happy to review this

**Comment by kthyng** [comment]
Thanks @dvalters!

@nicgaspar (or others who have been mentioned): are you interested in reviewing this submission for JOSS? We ask for reviews within about 3 weeks if possible and you can learn more about review guidelines here: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by kthyng** [comment]
@whedon assign @dvalters as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dvalters

**Comment by nicgaspar** [comment]
Hi! I can do this, but I'm kind of drowning right now. Realistic for me would be a Jan 1 deadline.

**Comment by kthyng** [comment]
@nicgaspar If you're willing, that would be ok from my end. I will proceed with you as the second reviewer.

**Comment by kthyng** [comment]
@whedon add @nicgaspar as reviewer

**Comment by whedon** [comment]
OK, @nicgaspar is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1935. Feel free to close this issue now!

**Comment by kthyng** [comment]
@dvalters and @nicgaspar the review itself will take place in the review issue. I'll check back in in a week or two to see how it's going. Thanks!

**Comment by rreinecke** [comment]
@kthyng Is that a new review process? Just woke up to 15 emails without then even the chance to respond. I would have been interested to review as well - but if this is the new way Joss is assigning reviewers ... Could you explain this new process? Till a week ago the handling editor used to choose the reviewers - and only when they declined somebody else was asked (again by the editor not the person who's work is reviewed).

**Comment by kthyng** [comment]
@rreinecke No, not new. The submitting author listed possible reviewers, as is always requested in the first comment in a pre-review issue and I as the handling editor additionally requested this list. The submitter author mentioned them specifically through github so people were aware of the suggestion before I subsequently wrote to them, and one volunteered from that list of mentions. I then specifically asked one person from the list of suggestions, and I typically start by asking possible reviewers who have not reviewed for us yet, or who have done so less than other possibilities, so as to avoid reviewer burnout. I prefer to specifically ask a smaller number of people rather than a bunch at once since then in that case it can fall in the cracks for awhile. We do not give a particular time frame for people to accept or decline the review.

**Comment by rreinecke** [comment]
> @rreinecke No, not new. The submitting author listed possible reviewers, as is always requested in the first comment in a pre-review issue and I as the handling editor additionally requested this list. The submitter author mentioned them specifically through github so people were aware of the suggestion before I subsequently wrote to them, and one volunteered from that list of mentions. I then specifically asked one person from the list of suggestions, and I typically start by asking possible reviewers who have not reviewed for us yet, or who have done so less than other possibilities, so as to avoid reviewer burnout. I prefer to specifically ask a smaller number of people rather than a bunch at once since then in that case it can fall in the cracks for awhile. We do not give a particular time frame for people to accept or decline the review.

@kthyng Thank you for your thorough explanation. However, you have to be aware that this way I'm getting unnecessary spam for a review I'm not even involved in. If I'm not going to review, or to be more precise given the chance to accept or decline that review, I don't want to be mentioned at all. Or am I missing something here?

**Comment by kthyng** [comment]
@rreinecke We don't have control over whether people are mentioned by submitters in reviews the way we are doing things, but we are always open to feedback on our process. Do you have any specific suggestions for improvements?

**Comment by rreinecke** [comment]
> @rreinecke We don't have control over whether people are mentioned by submitters in reviews the way we are doing things, but we are always open to feedback on our process. Do you have any specific suggestions for improvements?

@kthyng of course you do. At least a little bit: 1) Only ask for 2 suggestions for possible reviewers and only ask for more if they decline or do not answer in a given time frame. Or 2) as many of the other editors are doing it just recommend two reviewers yourself. Yes everything will be slowed down a little bit but you at least reduce the possibility to get mail on submissions one is not even concerned with. Also with the approach you have chosen the reviewer assignment doesn't look like the process you described but more like a first come first serve approach - that can't be what you want to get high quality reviews. You have to understand my frustration to be notified on something that does not even give me the possibility to react but just fills up my inbox @danielskatz @kthyng .

**Comment by kthyng** [comment]
Thank you @rreinecke I will share this with the editorial board.

**Comment by danielskatz** [comment]
@rreinecke - one thing we should make clear in our documentation and instructions from editor is for the author to suggest reviewers without the @ so that there are no notifications that start at this point.  I'll open an issue and also work on a PR to try to address this.

**Comment by rreinecke** [comment]
Thank you for hearing my concerns @kthyng and @danielskatz ! Keep up the great work for this unique journal!

**Comment by dvalters** [comment]
@rreinecke - you are welcome to review in my place if you are interested in the submission. I've done a fair few reviews this year for JOSS and would be happy to pass the opportunity on to someone else.

**Comment by rreinecke** [comment]
@dvalters No worries. Same for me. I'd just wanted to point that out. I'm pretty swamped. But of course if somebody is not able to it at all I'm happy to step in.
