### ISSUE TITLE
[PRE REVIEW]: Enhanced software and platform for the Town Energy Balance (TEB) model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1934]
**Submitting author:** @dmey (<a href="http://orcid.org/0000-0002-7071-7547">D. Meyer</a>)
**Repository:** <a href="https://github.com/teb-model/teb" target ="_blank">https://github.com/teb-model/teb</a>
**Version:** 4.0.0
**Editor:** @mjsottile
**Reviewers:** @rasmussn, @ethan-nelson

**Author instructions**

Thanks for submitting your paper to JOSS @dmey. **Currently, there isn't an JOSS editor assigned** to your paper.

@dmey if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1934 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1934 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1934 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/author.rb:56:in `build_affiliation_string': undefined method `split' for [1, 2]:Array (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon.rb:201:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon.rb:201:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon.rb:198:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon.rb:198:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon.rb:91:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-df8b50fe58b8/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by dmey** [comment]
@danielskatz I think this may be due to the 2 affiliations (see https://github.com/teb-model/teb/blame/joss-paper/paper/paper.md#L15).

**Comment by danielskatz** [comment]
👋 @dmey - the multiple affiliations line needs to be of the form
affiliation: "1, 2"
with quote marks, not square brackets

Once you've made this change, you can enter a new comment in this thread with ```@whedon generate pdf from branch joss-paper``` to try again.  Feel free to iterate until things look right.

**Comment by dmey** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1934 with the following error: 

 Error reading bibliography ./paper.bib (line 323, column 1):
unexpected "@"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by dmey** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01934/joss.01934/10.21105.joss.01934.pdf)

**Comment by dmey** [comment]
@danielskatz many thanks -- still a few issues with the typesetting -- will try to fix this momentarily.

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1023/A:1002463829265 is OK
- 10.5194/gmd-5-1377-2012 is OK
- 10.5194/gmd-11-1929-2018 is OK
- 10.1002/joc.3415 is OK
- 10.5194/gmd-5-433-2012 is OK
- 10.5194/gmd-10-2801-2017 is OK
- 10.1175/WAF-D-11-00064.1 is OK
- 10.3389/fenvs.2014.00014 is OK
- 10.21105/joss.01137 is OK
- 10.5065/1dfh-6p97 is OK
- 10.1016/j.aeaoa.2019.100042 is OK
- 10.1007/s00703-008-0320-9 is OK
- 10.21105/joss.01468 is OK
- 10.1007/BF01025401 is OK
- 10.1175/2009MWR2750.1 is OK
- 10.1007/s10546-009-9414-2 is OK
- 10.1175/1520-0493(1998)126<1373:TOCMGE>2.0.CO;2 is OK
- 10.1023/A:1016509614936 is OK
- 10.1007/s10546-006-9091-3 is OK
- 10.1175/2009JAMC2153.1 is OK
- 10.5281/zenodo.3562310 is OK

MISSING DOIs

- https://doi.org/10.1175/1520-0450(2004)043<0312:mtsebo>2.0.co;2 may be missing for title: Modeling the Surface Energy Balance of the Core of an Old Mediterranean City: Marseille
- https://doi.org/10.1007/s007030070003 may be missing for title: The Advanced Regional Prediction System (ARPS) – A Multi-Scale Nonhydrostatic Atmospheric Simulation and Prediction Model. Part I: Model Dynamics and Verification
- https://doi.org/10.1007/s00585-997-0090-6 may be missing for title: The Meso-NH Atmospheric Simulation System. Part I: Adiabatic Formulation and Control Simulations
- https://doi.org/10.1175/1520-0450(2002)041<1011:eotteb>2.0.co;2 may be missing for title: Evaluation of the Town Energy Balance (TEB) Scheme with Direct Measurements from Dry Districts in Two Cities

INVALID DOIs

- None
```

**Comment by dmey** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01934/joss.01934/10.21105.joss.01934.pdf)

**Comment by dmey** [comment]
@danielskatz I have fixed the references but there is still an issue with the typesetting of footnotes. It looks like table footnotes are made part of the table itself and not of the page footer.  Have you experienced a similar issue before?

**Comment by danielskatz** [comment]
@arfon - Any thoughts?

**Comment by arfon** [comment]
> @arfon - Any thoughts?

No idea sorry. I think this is probably pushing the limit of the Markdown/Pandoc template sorry. I'd recommend trying to find a different way to accomplish this.

**Comment by dmey** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01934/joss.01934/10.21105.joss.01934.pdf)

**Comment by dmey** [comment]
> No idea sorry. I think this is probably pushing the limit of the Markdown/Pandoc template sorry. I'd recommend trying to find a different way to accomplish this.

@arfon  @danielskatz  Thanks and not problems -- I removed the footnote and used a start (*) instead this with clarification in the caption. LGTM now but please let me know for any issues.

**Comment by danielskatz** [comment]
👋 @mjsottile - would you be willing to edit this submission? It's a bit out of your area, but the .F90 part makes you a potentially good option.

**Comment by mjsottile** [comment]
I can, but can't start the process until next week: end of semester + travel = no time for the next 7 days or so.

**Comment by danielskatz** [comment]
That's fine - thanks.

**Comment by danielskatz** [comment]
@whedon assign @mjsottile as editor

**Comment by whedon** [comment]
OK, the editor is @mjsottile

**Comment by dmey** [comment]
@mjsottile and @danielskatz many thanks for this -- In the meantime, I would like to suggest a few names [from the JOSS list of reviewers](https://bit.ly/joss-reviewers) that may be suitable for the review:

```
https://github.com/dvalters
https://github.com/bjarketol
https://github.com/tomchor
https://github.com/kramea
https://github.com/martinfleis
https://github.com/robertodr
https://github.com/nmstreethran
https://github.com/johnrobertlawson
https://github.com/brynpickering
```

**Comment by mjsottile** [comment]
👋 @dvalters @bjarketol @tomchor @kramea @martinfleis @robertodr @nmstreethran @johnrobertlawson @brynpickering - Would you be interested in reviewing this JOSS submission?

**Comment by martinfleis** [comment]
@mjsottile I am sorry, I know very little about the topic and I am not able to review FORTRAN at all.

**Comment by tomchor** [comment]
@mjsottile Unfortunately I don't have enough expertise or time to review this paper at this moment. So I'll have to decline.

Thank you.

**Comment by robertodr** [comment]
@mjsottile apologies, but I cannot review this paper. This is not my field of expertise at all.

**Comment by kramea** [comment]
Sorry, I'll have to decline as well. I don't have any FORTRAN experience.

**Comment by nmstreethran** [comment]
Hi @mjsottile, I'm unfamiliar with Fortran, so I'm afraid I can't review this submission. My apologies.

**Comment by dmey** [comment]
@mjsottile would you have any suggestion re possible reviewers for this or should I try to see if I can find more. I think that given that there's a bit of Python, CMake, Fortran reviewers may be scarce.

**Comment by mjsottile** [comment]
@dmey I found one reviewer that I contacted outside of github.  If you have any suggestions for others so we find the second reviewer, I’d be open to more ideas.  Otherwise I’ll keep looking myself.  There is likely going to be little progress right now due to people being offline for the holidays.

**Comment by dmey** [comment]
@mjsottile great thanks and no problems -- I will look for more and will let you know after Christmas.

**Comment by dmey** [comment]
@mjsottile I have added some more suggestions for Reviewers below.

```
https://github.com/zbeekman
https://github.com/ethan-nelson
https://github.com/kellykochanski
https://github.com/eviatarbach
https://github.com/Chilipp
https://github.com/ashwinvis
https://github.com/mdelorme
https://github.com/katyhuff
https://github.com/edoddridge
https://github.com/ctdegroot
https://github.com/usethedata
https://github.com/rbeucher
```

**Comment by mjsottile** [comment]
:wave: @zbeekman @ethan-nelson @mdelorme @edoddridge Would any of you be interested in reviewing this submission for JOSS?

**Comment by mdelorme** [comment]
Hi, @mjsottile, I'm sorry I cannot review this paper. This really not my area of knowledge.

**Comment by zbeekman** [comment]
I'd love to, but I'm drowning in work until the end of Feb. (Big contract coming to a close and there's a lot left to get in order.)

**Comment by ethan-nelson** [comment]
Hi @mjsottile sure, happy to review

**Comment by mjsottile** [comment]
Excellent.  I have two reviewers now, so I'll initiate the review process.

**Comment by mjsottile** [comment]
@whedon assign @rasmussn as reviewer

**Comment by whedon** [comment]
OK, @rasmussn is now a reviewer

**Comment by mjsottile** [comment]
@whedon add @ethan-nelson as reviewer

**Comment by whedon** [comment]
OK, @ethan-nelson is now a reviewer

**Comment by mjsottile** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2008. Feel free to close this issue now!
