### ISSUE TITLE
[REVIEW]: GroundwaterDupuitPercolator: A Landlab component for groundwater flow

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1935]
**Submitting author:** @davidlitwin (<a href="http://orcid.org/0000-0002-8097-4029">David Litwin</a>)
**Repository:** <a href="https://github.com/landlab/landlab" target ="_blank">https://github.com/landlab/landlab</a>
**Version:** v2.0.0b5
**Editor:** @kthyng
**Reviewers:** @dvalters, @rreinecke
**Archive:** <a href="https://doi.org/10.5281/zenodo.3660698" target="_blank">10.5281/zenodo.3660698</a>

## Status

[![status](https://joss.theoj.org/papers/6936ca6851c622de48b2c5f6cf45a7bd/status.svg)](https://joss.theoj.org/papers/6936ca6851c622de48b2c5f6cf45a7bd)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6936ca6851c622de48b2c5f6cf45a7bd"><img src="https://joss.theoj.org/papers/6936ca6851c622de48b2c5f6cf45a7bd/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6936ca6851c622de48b2c5f6cf45a7bd/status.svg)](https://joss.theoj.org/papers/6936ca6851c622de48b2c5f6cf45a7bd)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/landlab/landlab" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dvalters & @rreinecke, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/landlab/landlab">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@davidlitwin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/landlab/landlab">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@davidlitwin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dvalters, @nicgaspar it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1029/WR006i005p01296 is OK
- 10.1016/S0167-5648(09)70009-7 is OK
- 10.1029/2002WR001728 is OK
- 10.1016/j.advwatres.2017.09.008 is OK
- 10.1002/esp.1369 is OK
- 10.1016/j.jhydrol.2003.12.043 is OK
- 10.1002/2014WR015809 is OK
- 10.1002/2013WR013918 is OK
- 10.1029/WR007i005p01256 is OK
- 10.1126/science.aaf7891 is OK
- 10.1016/j.jhydrol.2008.11.002 is OK
- 10.1029/92WR00802 is OK
- 10.5194/esurf-5-21-2017 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01935/joss.01935/10.21105.joss.01935.pdf)

**Comment by kthyng** [comment]
Just a quick note to reviewers @dvalters, @nicgaspar that this is where the review is to take place. Thanks!

**Comment by kthyng** [comment]
Happy New Year @dvalters and @nicgaspar! Here is a friendly reminder for your review, maybe in a few days after you have celebrated the new year coming in. Thanks!

**Comment by nicgaspar** [comment]
Hi @kthyng! I'm behind as always. I just realized that I have a COI. I am still willing to go ahead with the review if you think it is OK. But I actively collaborate with Katy Barnhart and Greg Tucker, both of whom are co-authors. As in we are working on papers together now, and have published together in the last year.

I feel I can be unbiased, but I should let you know. Sorry this took so long.

**Comment by kthyng** [comment]
@nicgaspar Hm I think that is too close. I will search for a new reviewer. Thank you for pointing this out.

**Comment by kthyng** [comment]
Hi @rreinecke! You were interested in this JOSS submission before — any chance you still are and are available to review it? It turns out we had a conflict of interest with another reviewer.

**Comment by kthyng** [comment]
@dvalters What is your timeline for working on this review? Thanks.

**Comment by rreinecke** [comment]
@kthyng Sure.

**Comment by kthyng** [comment]
@rreinecke Awesome! Thanks. I will add you on.

**Comment by kthyng** [comment]
@whedon add @rreinecke as reviewer

**Comment by whedon** [comment]
OK, @rreinecke is now a reviewer

**Comment by kthyng** [comment]
@whedon remove @nicgaspar as reviewer

**Comment by kthyng** [comment]
I think that @nicgaspar should now be removed as a reviewer and replaced by @rreinecke, but please let me know if anything is in error. @rreinecke I think you'll just need to accept the invitation to review to have permission to edit the checklist. Thanks.

**Comment by rreinecke** [comment]
@DavidLitwin before continuing with my review could you please provide me detailed information on where to find the new groundwater module? It appears that you have submitted the landlab main repository to this JOSS review - Is there a reason it is not in a separate repository and used as submodule? 
Also the contribution of submitting author @DavidLitwin is not clear. From the number of total commits in the landlab project I cannot derive a major contribution.

**Comment by dvalters** [comment]
@kthyng Hello again, - yes, sorry I am on it this week! Thanks for the reminder :)

**Comment by DavidLitwin** [comment]
Hi @rreinecke and @dvalters, you can find the groundwater module in the components folder, [here](https://github.com/landlab/landlab/tree/master/landlab/components/groundwater). I think this is how this has been handled for all landlab components - they become part of the main repository so that they are readily available for anyone who uses landlab. Details on that are probably more a question for @kbarnhart. 

As for contributions. The groundwater model was started by Greg Tucker. I did most of the core work from there. I adapted it for sloping aquifer base, incorporated the functions necessary to allow for seepage to the surface, wrote the adaptive timestep solver, wrote setters and getters and methods to calculate fluxes, wrote all current documentation and the tutorial. @kbarnhart has since made several commits so that the component is compatible with landlab 2.0. Does that help?

**Comment by kbarnhart** [comment]
@rreinecke I'll add a few other comments regarding this submission and contributions. Hopefully this clarifies things, but if not, please let me know and I'll try and address additional questions. 

This contribution specifically focuses on the GroundwaterDupuitPercolator component within the Landlab package, rather than the Landlab package itself. Because JOSS is set up for the submission to provide a repository (e.g., https://github.com/landlab/landlab), this means that the repository of record is github/landlab/landlab, but the scope of the contribution is the the component (https://github.com/landlab/landlab/tree/master/landlab/components/groundwater), the associated documentation, and examples. At present there is no way in the JOSS workflow to formally indicate that this submission focuses on only the GroundwaterDupuitPercolator component. 

The first time someone considered submitting a component from Landlab to JOSS (it was me, [link to issue discussing this](https://github.com/openjournals/joss/issues/443)) there was a discussion about whether it would make the most sense to put it in a separate repository and then have Landlab consider it as a submodule. We decided that this was not the best approach because it would make maintenance of the component and the package more difficult. Additionally, keeping the component within the Landlab package means that a separate submodule doesn't need to re-implement all of the documentation-building, code testing, and CI specification package documents, but can take advantage of the setup that the landlab package already has. 

While @DavidLitwin has made relatively few commits to the Landlab package, he is almost entirely responsible for this component, its documentation, and examples. My description of coauthor contributions would be as follows:

- @gregtucker started the component's development
- @gregtucker and Ciaran provided most of the theoretical guidance to @DavidLitwin 
- @gregtucker and I provided operational and numerical guidance to @DavidLitwin 
- @DavidLitwin did almost all of the coding, and created the documentation and examples.

**Comment by DavidLitwin** [comment]
Thank you for clarifying @kbarnhart. I agree with the coauthor contributions as you have described them.

**Comment by rreinecke** [comment]
Thank you @kbarnhart and @DavidLitwin for clarifying the authorship.

Concerning the submodule I strongly disagree but that is something you need to decide and will not be part of this review. Nevertheless, I already have a problem in verifying the functionality of the software as I cannot find according unit tests (and how to run them). If they are somewhere else in the project please add a detailed description to your repository e.g. a list of submodules etc.. Please also explain there where to find which software component. I'm aware that there is another official Landlab page but as my time, and the time of the other reviewer and of course potential future users, is limited please consider to extend your readme. Also install instructions are missing together with a list of dependencies. Furthermore, did you implement a simple example model which demonstrates the capabilities of the new package? If so where? And where do I find the according documentation?

Please revise your repository in a way that I'm able to answer all of these questions on my own and let me know when it is implemented. Please do not describe these things in this thread. They should be self explanatory for every new user.

**Comment by dvalters** [comment]
> Furthermore, did you implement a simple example model which demonstrates the capabilities of the new package? 
There is a binder demo of the new component here (linked to in the component readme) which I'm using to explore the model.

https://mybinder.org/v2/gh/landlab/landlab/release?filepath=notebooks/tutorials/groundwater/groundwater_flow.ipynb

**Comment by rreinecke** [comment]
> > Furthermore, did you implement a simple example model which demonstrates the capabilities of the new package?
> 
> There is a binder demo of the new component here (linked to in the component readme) which I'm using to explore the model.
> 
> https://mybinder.org/v2/gh/landlab/landlab/release?filepath=notebooks/tutorials/groundwater/groundwater_flow.ipynb

Thank you! This is great!
Still my comments about the project README remain.

Please also adress landlab/landlab#1106 and landlab/landlab#1105

**Comment by rreinecke** [comment]
@dvalters I've added a question concerning the used equations here: landlab/landlab#1107

Just to have it on record and be transparent (this is not a review request only a general suggestion and note, I don't think it is a conflict of interest): @dvalters I have developed a Modflow clone that allows to efficiently calculate 3d Darcy flow. Maybe that is of interest as an alternative to your use of Depuit. Just for consideration after the review for future work. 

Nonetheless I think you should openly discuss the limitations of your approach so that users are applying it correctly.

**Comment by kbarnhart** [comment]
@rreinecke I will open an issue in the landlab repository associated with your [prior comment](https://github.com/openjournals/joss-reviews/issues/1935#issuecomment-574524938) and address it with a PR. Once that PR is live I will ask you to comment on whether I have addressed the issues you raised.

**Comment by rreinecke** [comment]
@DavidLitwin @kthyng I'm done.

Cheers

@DavidLitwin Just to let you know landlab did not pass all tests for me: "199 failed, 2665 passed, 61 skipped, 24 warnings, 19 error in 106.32 seconds" but the groundwater component tests worked as expected so I don't see a reason why dragging this review further along.

**Comment by kbarnhart** [comment]
@rreinecke could you make an issue in Landlab and paste int the output of the failing tests? I'm surprised that they are failing, and want to make sure that this is addressed. Thanks for your review!

**Comment by rreinecke** [comment]
@kbarnhart Sorry I'm super swamped right now. It might also only be a problem connected to my manual setup without anaconda. If I find the time I will open an issue in landlab. But I don't think this is blocking the completion of this review from my side.

**Comment by DavidLitwin** [comment]
Hi @kthyng, it appears that all the boxes have been checked by the reviewers. Is there anything more that we need to do at this point? Thanks!

**Comment by dvalters** [comment]
Yep, sorry forgot to say after checking the boxes - all good from my side as far as a I can see!

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01935/joss.01935/10.21105.joss.01935.pdf)

**Comment by kthyng** [comment]
@DavidLitwin Just read through your paper and have one small typo in the paper [#1144](https://github.com/landlab/landlab/pull/1144) and a few in the bib file [#1145](https://github.com/landlab/landlab/pull/1145). See what you think.

After that, let me know: what is the appropriate version number to use?

Also, can you set up an archive of your code at, for example, Zenodo, and report back here with the doi?

**Comment by DavidLitwin** [comment]
@kthyng thank you for the typo corrections. 

@kbarnhart I want to make sure the version and doi are handled correctly.. If we do it similarly to the JOSS paper for `lithology`, the landlab release where the component was introduced is referenced, along with the current landlab release and associated DOI. The component first appears in v.1.10 I believe, and current release is v2.0.0b5. @kbarnhart can you confirm this?

**Comment by DavidLitwin** [comment]
Just fixed one other typo in landlab/landlab#1146.

**Comment by kbarnhart** [comment]
@DavidLitwin you are correct. the typo you just fixed isn't in v2.0.0b5, but I'm not sure if that is important. if it is, we can make a new release.

**Comment by DavidLitwin** [comment]
@kbarnhart I think that should be fine, right? @kthyng zenodo seems to be having some trouble right now, but the DOI is 10.5281/zenodo.154179.

**Comment by kbarnhart** [comment]
@DavidLitwin I don't think that is the correct DOI. 

That looks like the DOI for v1.0.1.

**Comment by DavidLitwin** [comment]
@kbarnhart do you have the correct one? That's the one that appears in the readme for landlab on github, and I can't find anything past 1.5.4 with a DOI on zenodo.

**Comment by kbarnhart** [comment]
@DavidLitwin I would manually make a Zenodo archive rather than use the auto-created Zenodo archive that sometimes get made when a new tag is created. 

I also say this because I know in the [JOSS docs](https://joss.readthedocs.io/en/latest/editing.html#after-reviewers-recommend-acceptance) there is a statement that the title and authors of the zenodo archive should match. The docs say:

> Check the archive deposit has the correct metadata (title and author list), and request the author edit it if it doesn’t match the paper.

So I think you'll need to download a .zip of the current version of Landlab and archive it with the name and authors of this contribution. I'll let @kthyng chime in if she thinks this is not correct.

**Comment by kthyng** [comment]
@kbarnhart Yes this sounds correct to me. I haven't gone through the process myself but we do want the relevant version of the code archived at something like Zenodo, and we want the authors/title to match the paper exactly. Having the whole Landlab in the archive does make sense, given this is a submodule.

**Comment by DavidLitwin** [comment]
@kthyng and @kbarnhart I have created an archive of the latest landlab release (2.0.0b5) here: 

 http://doi.org/10.5281/zenodo.3660698

Please let me know if there are any issues with this and I will try to resolve them.

**Comment by kthyng** [comment]
@whedon set v2.0.0b5 as version

**Comment by whedon** [comment]
OK. v2.0.0b5 is the version.

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.3660698 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3660698" target="_blank">10.5281/zenodo.3660698</a> is the archive.

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1029/WR006i005p01296 is OK
- 10.1016/S0167-5648(09)70009-7 is OK
- 10.1029/2002WR001728 is OK
- 10.1016/j.advwatres.2017.09.008 is OK
- 10.1002/esp.1369 is OK
- 10.1016/j.jhydrol.2003.12.043 is OK
- 10.1002/2014WR015809 is OK
- 10.1002/2013WR013918 is OK
- 10.1029/WR007i005p01256 is OK
- 10.1126/science.aaf7891 is OK
- 10.1016/j.jhydrol.2008.11.002 is OK
- 10.1029/92WR00802 is OK
- 10.5194/esurf-5-21-2017 is OK
- 10.1002/hyp.8319 is OK
- 10.1029/2008WR007536 is OK
- 10.1029/2006WR005752 is OK
- 10.1016/j.advwatres.2005.08.006 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1290

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1290, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1226877967483228161) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1291
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01935](https://doi.org/10.21105/joss.01935)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Congratulations to @DavidLitwin on your new publication! Thanks to reviewers @dvalters and @rreinecke for your time and expertise.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01935/status.svg)](https://doi.org/10.21105/joss.01935)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01935">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01935/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01935/status.svg
   :target: https://doi.org/10.21105/joss.01935
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01935/status.svg)](https://doi.org/10.21105/joss.01935)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
