### ISSUE TITLE
[PRE REVIEW]: EspressoDB: A scientific database for managing high-performance computing workflows

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1936]
**Submitting author:** @ckoerber (<a href="http://orcid.org/0000-0002-9271-8022">Christopher Körber</a>)
**Repository:** <a href="https://github.com/callat-qcd/espressodb" target ="_blank">https://github.com/callat-qcd/espressodb</a>
**Version:** v1.0.0
**Editor:** @gkthiruvathukal
**Reviewers:** @remram44, @ixjlyons

**Author instructions**

Thanks for submitting your paper to JOSS @ckoerber. **Currently, there isn't an JOSS editor assigned** to your paper.

@ckoerber if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1109/sc.2018.00054 is OK
- 10.1109/SC.2018.00060 is OK
- 10.1038/s41586-018-0161-8 is OK
- 10.1103/PhysRevLett.121.172501 is OK
- 10.1051/epjconf/201817509007 is OK
- 10.1103/PhysRevD.82.094502 is OK

MISSING DOIs

- https://doi.org/10.1109/sc.2018.00058 may be missing for title: Simulating the weak death of the neutron in a femtoscale universe with near-Exascale computing

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01936/joss.01936/10.21105.joss.01936.pdf)

**Comment by danielskatz** [comment]
👋 @gkthiruvathukal - would you be willing to edit this submission?

**Comment by gkthiruvathukal** [comment]
@danielskatz Yes!

**Comment by danielskatz** [comment]
@whedon assign @gkthiruvathukal as editor

George, note that you can also do this yourself once you've agree :)

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by ckoerber** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by ckoerber** [comment]
Hello @gkthiruvathukal,

I have skimmed through the above list of potential referees and found a few candidates which might be fitting for this review:

@ixjlyons
@sarats
@sjvrijn
@krother
@remram44
@adammichaelwood
@pgadige 

Best regards,

Christopher

**Comment by gkthiruvathukal** [comment]
Hi, @ixjlyons, @sarats, @sjvrijn, @krother, @remram44, @adammichaelwood, @pgadige, are any 2 of you willing to contribute a review for this JOSS submission?

**Comment by sjvrijn** [comment]
@gkthiruvathukal Sorry, not this time.

**Comment by gkthiruvathukal** [comment]
Thanks, @sjvrijn. Appreciate the quick response. I hope others will say _yes_. Happy holidays!

**Comment by remram44** [comment]
@gkthiruvathukal I'm able and willing!

**Comment by ckoerber** [comment]
@remram44 Thank you for agreeing to referee our paper. We look forward to your comments and insights.

**Comment by gkthiruvathukal** [comment]
Hi, @ixjlyons, @sarats, @krother, @adammichaelwood, @pgadige, are any of you willing to contribute a review for this JOSS submission? I need one other reviewer. Thanks!

**Comment by gkthiruvathukal** [comment]
@whedon assign @remram44 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @remram44

**Comment by gkthiruvathukal** [comment]
Hi, @ixjlyons and @sarats, are either of you willing to contribute a review for this JOSS submission? I need one other reviewer. Thanks!

**Comment by ixjlyons** [comment]
Apologies for the delay. I'm able to review.

**Comment by ckoerber** [comment]
Happy New Year!

Thank you for agreeing to referee our paper, @ixjlyons.

@gkthiruvathukal, please let us know if you need any additional information from us.

**Comment by gkthiruvathukal** [comment]
@whedon add @ixjlyons as reviewer

**Comment by whedon** [comment]
OK, @ixjlyons is now a reviewer

**Comment by gkthiruvathukal** [comment]
Hi @ckoerber, no additional info needed. We have two reviewers now, so I can get the review process started.

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2007. Feel free to close this issue now!

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._
