### ISSUE TITLE
[PRE REVIEW]: ggalluvial: Layered Grammar for Alluvial Plots

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1937]
**Submitting author:** @corybrunson (<a href="http://orcid.org/0000-0003-3126-9494">Jason Cory Brunson</a>)
**Repository:** <a href="https://github.com/corybrunson/ggalluvial" target ="_blank">https://github.com/corybrunson/ggalluvial</a>
**Version:** v0.11.1
**Editor:** @akeshavan
**Reviewers:** @clauswilke, @njtierney

**Author instructions**

Thanks for submitting your paper to JOSS @corybrunson. The JOSS editor @akeshavan, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@corybrunson if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @akeshavan it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@akeshavan) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01937/joss.01937/10.21105.joss.01937.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/978-4-431-68057-4_3 is OK
- 10.1080/01621459.1990.10474926 is OK
- 10.1198/106186002317375631 is OK
- 10.1109/INFVIS.2005.1532152 is OK
- 10.1007/3-540-28084-7_4 is OK
- 10.1109/TVCG.2006.76 is OK
- 10.1111/j.1530-9290.2008.00004.x is OK
- 10.1198/jcgs.2009.07098 is OK
- 10.1371/journal.pone.0008694 is OK
- 10.1109/TVCG.2011.227 is OK
- 10.1007/978-3-642-21551-3_13 is OK
- 10.1068/a45488 is OK
- 10.1109/TVCG.2013.140 is OK
- 10.18637/jss.v059.i10 is OK
- 10.1038/srep06773 is OK
- 10.1007/978-0-387-98141-3 is OK
- 10.1177/0308518X17745067 is OK
- 10.1016/j.anaerobe.2018.05.017 is OK
- 10.21105/joss.01686 is OK
- 10.31234/OSF.IO/MKQN4 is OK
- 10.1002/ejhf.1547 is OK
- 10.1111/gec3.12441 is OK
- 10.1523/jneurosci.1451-18.2019 is OK
- 10.3389/fimmu.2019.00660 is OK
- 10.1097/CCM.0000000000003469 is OK
- 10.1016/j.marpol.2019.103676 is OK
- 10.1016/j.eiar.2019.01.003 is OK
- 10.1016/j.fcr.2019.03.023 is OK

MISSING DOIs

- https://doi.org/10.1007/0-387-28695-0 may be missing for title: The Grammar of Graphics

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @akeshavan - sorry, I assigned this to you while starting the process without checking with you first. Are you willing to edit this submission?

**Comment by danielskatz** [comment]
👋 @corybrunson - this submission needs a license - please add a plain text LICENSE file with the OSI-approved license that you are using for the software (which I think is GPL-3).

**Comment by danielskatz** [comment]
Also, please check to see if the missing DOI whedon suggests is correct, and if so, add it to the .bib file. (Whedon suggestions are just suggestions, and sometimes they are wrong.)

**Comment by corybrunson** [comment]
@danielskatz thank you! I've added the missing DOI. To be sure, is it good practice to simply put the standard GPLv3 license text (file name `LICENSE`) in the root directory, assuming i don't intend any deviations from that standard?

**Comment by corybrunson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01937/joss.01937/10.21105.joss.01937.pdf)

**Comment by danielskatz** [comment]
> To be sure, is it good practice to simply put the standard GPLv3 license text (file name LICENSE) in the root directory, assuming i don't intend any deviations from that standard?

Yes, and if there are any deviations, you have changed the license to a non-OSI-approved one, which would mean that JOSS would not consider the submission.

**Comment by corybrunson** [comment]
> Yes, and if there are any deviations, you have changed the license to a non-OSI-approved one, which would mean that JOSS would not consider the submission.

Right, thank you for pointing that out. In a moment i'll push the Markdown GPLv3 obtained from [here](https://www.gnu.org/licenses/gpl-3.0.en.html), renamed `LICENSE.md`.

**Comment by danielskatz** [comment]
not LICENSE.md but LICENSE

**Comment by corybrunson** [comment]
> not LICENSE.md but LICENSE

Thank you, this has been changed (using the plain text version of GPLv3).

**Comment by corybrunson** [comment]
From the list of potential reviewers, @kellieotto, @njtierney, and @clauswilke seem to have very relevant expertise and interests.

**Comment by njtierney** [comment]
Happy to provide a review, when would you like it completed? The end of the year is looming and I'm not sure if I could get it completed before December 20, but can try.

**Comment by danielskatz** [comment]
👋 @akeshavan - sorry, I assigned this to you while starting the process without checking with you first. Are you willing to edit this submission? (we already have one potential reviewer who has agreed...)

**Comment by akeshavan** [comment]
hi @danielskatz , sorry I only just saw this! happy to review.

@njtierney no worries, I know everyone is busy during the holidays! Can we plan for sometime in January?

**Comment by akeshavan** [comment]
👋 @kellieotto and @clauswilke -- I know you are busy with holidays now, but would you be interested in reviewing this submission in January?

**Comment by clauswilke** [comment]
I can do a review. Please send a reminder in early Jan. if I haven't done it by then.

**Comment by njtierney** [comment]
Hello! Sorry I haven't managed this yet, I am aiming for the end of Jan, if that is alright?

**Comment by corybrunson** [comment]
Thank you all!

@akeshavan is there anything i need to do before the review begins? (I have made some slight edits to the paper.)

@whedon generate pdf

**Comment by corybrunson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01937/joss.01937/10.21105.joss.01937.pdf)

**Comment by danielskatz** [comment]
Hi @corybrunson - whedon commands have to be the start of a comment, like the following

**Comment by danielskatz** [comment]
ah, you also figured this out - never mind...

**Comment by akeshavan** [comment]
@whedon assign @clauswilke as reviewer

**Comment by whedon** [comment]
OK, @clauswilke is now a reviewer

**Comment by akeshavan** [comment]
@whedon add @njtierney as reviewer

**Comment by whedon** [comment]
OK, @njtierney is now a reviewer

**Comment by akeshavan** [comment]
hi @corybrunson , @njtierney and @clauswilke -- now that holidays are over, I'm moving this to the review stage. Thanks for your patience!

**Comment by akeshavan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2017. Feel free to close this issue now!
