### ISSUE TITLE
[PRE REVIEW]: threshmodelsPackage: A Python package for a Peak-Over-Threshold modeling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1938]
**Submitting author:** @iagolemos1 (<a href="http://orcid.org/0000-0002-5829-7711">Iago Lemos</a>)
**Repository:** <a href="https://github.com/iagolemos1/threshmodelsPackage" target ="_blank">https://github.com/iagolemos1/threshmodelsPackage</a>
**Version:** v0.0.1
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @iagolemos1. **Currently, there isn't an JOSS editor assigned** to your paper.

@iagolemos1 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/978-1-4471-3675-0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01938/joss.01938/10.21105.joss.01938.pdf)

**Comment by danielskatz** [comment]
👋 @iagolemos1 - please see https://github.com/iagolemos1/threshmodelsPackage/pull/1 for grammar, spelling, etc. fixes

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01938/joss.01938/10.21105.joss.01938.pdf)

**Comment by iagolemos1** [comment]
Hello there, 
I would like to suggest some individuals to review my work. Following a list of usernames:

nicoguaro
krother
betatim
djmitche
kellieotto
jmbr
aokad
paragkulkarni11
sarats

**Comment by iagolemos1** [comment]
> 👋 @iagolemos1 - please see [iagolemos1/threshmodelsPackage#1](https://github.com/iagolemos1/threshmodelsPackage/pull/1) for grammar, spelling, etc. fixes

Everything's ok, Daniel, thanks!

**Comment by iagolemos1** [comment]
Hello there,
I would like to suggest some individuals for the review:
betatim
djmitche
kellieotto
soodoku
molgor
jmbr
kczimm
tupi
mnarayan
tianxzhu
acolum
GalenStocking
dhhagan
acolum
barryrowlingson
stensy
terrytangyuan
ziotom78
rasbt
benjaminrose
zhampel
nespinoza
stulacy
dirmeier
williamjameshandley
adavidzh
andrewfowlie
sjsrey
andremrsantos
snastase
malmaud
lindemann09
Nazeeefa
JonathanReardon
ejolly
tleonardi
bahung
dsurujon
danehkar
dhuppenkothen
tleonardi
olivertomic
matloff
tonigi, giorginolab
mskwark
gakhov
ali-ramadhan
SuperKam91
tuchandra
Stat-Cook
EtienneCmb
alanfairless
agisga
Pqrs6
Jpata
smsharma
Fipanther
fhorrobin
szorowi1
timothydmorton
cultpenguin
kose-y

**Comment by iagolemos1** [comment]
Hello there,
I would like to suggett some reviwers usernames:

betatim
djmitche
kellieotto
jmbr
GalenStocking
terrytangyuan
adavidzh
andremrsantos
malmaud
ali-ramadhan
Stat-Cook
agisga
Pqrs6
kose-y

**Comment by danielskatz** [comment]
Thanks - the JOSS editors are currently discussing if this is in scope, and will get back to you in the next couple of days

**Comment by danielskatz** [comment]
👋 @iagolemos1 - I've discussed this submission with the the JOSS editorial board, and we have determined that it is not suitable for JOSS at this time, as we state in our docs:

>Minor ‘utility’ packages, including ‘thin’ API clients, are not acceptable.

Based on this, I'm rejecting this submission

However, we also noted your comment in the README:

>A GPD package is being created for complementing this one. The main idea is to provide a complete model package of the Generalized Pareto Distribution in the future.

and would be happy to consider a more substantial software package in the future, though this is no guarantee

**Comment by iagolemos1** [comment]
Ok, thank you. I am going to work on a complete package and hope to be
accepeted.

Em dom, 8 de dez de 2019 10:12, Daniel S. Katz <notifications@github.com>
escreveu:
