### ISSUE TITLE
[PRE REVIEW]: WordTokenizers.jl: Basic tools for tokenizing natural language in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1939]
**Submitting author:** @oxinabox (<a href="http://orcid.org/0000-0003-1386-1646">Lyndon White</a>)
**Repository:** <a href="https://github.com/JuliaText/WordTokenizers.jl/" target ="_blank">https://github.com/JuliaText/WordTokenizers.jl/</a>
**Version:**  v0.5.3
**Editor:** @will-rowe
**Reviewers:** @leios, @ninjin

**Author instructions**

Thanks for submitting your paper to JOSS @oxinabox. **Currently, there isn't an JOSS editor assigned** to your paper.

@oxinabox if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1137/141000671 may be missing for title: Julia: A Fresh Approach to Numerical Computing
- https://doi.org/10.1609/aaai.v33i01.33016843 may be missing for title: Spell Once, Summon Anywhere: A Two-Level Open-Vocabulary Language Model

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01939/joss.01939/10.21105.joss.01939.pdf)

**Comment by danielskatz** [comment]
👋 @oxinabox  - thanks for your submission!

As you can see above, @whedon thinks some of your bib entries might be missing DOIs (but @whedon is also sometimes wrong)

Please check

There also seem to be some other things in the generated pdf that could be fixed, such as double (())s around some citations, missing spaces before some citations, and some extra "s in one reference

After you make changes, enter a new comment here with ```@whedon generate pdf``` to check the result

**Comment by danielskatz** [comment]
👋 @will-rowe - would you be willing to edit this submission?

**Comment by will-rowe** [comment]
This looks cool - happy to.

**Comment by will-rowe** [comment]
@whedon assign @will-rowe as editor

**Comment by whedon** [comment]
OK, the editor is @will-rowe

**Comment by will-rowe** [comment]
Hi @vchuravy and @ahwillia - would you both be willing to review this submission?

**Comment by oxinabox** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01939/joss.01939/10.21105.joss.01939.pdf)

**Comment by will-rowe** [comment]
Hi @ChrisRackauckas and @leios - would you please be able to review this submission for us?

**Comment by leios** [comment]
Hey @will-rowe I can do it next week, if that works for everyone

**Comment by will-rowe** [comment]
Perfect - thanks a lot @leios. Next week is great. Once we've got a second reviewer, I can move this submission into review.

**Comment by ChrisRackauckas** [comment]
Hi, I will not be able to.

**Comment by will-rowe** [comment]
No worries @ChrisRackauckas - thanks for letting me know quickly

**Comment by will-rowe** [comment]
Hi @ninjin - would you please be able to review this submission for us?

**Comment by will-rowe** [comment]
Hi @ionlights - would you please be able to review this submission?

**Comment by oxinabox** [comment]
@ninjin would be an awesome reviewer (being a NLP researcher and a Julia dev).
But I know is incredibly busy right now.

**Comment by ninjin** [comment]
I can do it, as long as I get two weeks to do so. That way I can clear the pre-Christmas hell first.

**Comment by will-rowe** [comment]
That's perfect - thanks @ninjin.

We're ready to move this over to review then. As it's Christmas etc., there's no rush on the reviews until the New Year as I know we're all busy this time of year.

**Comment by will-rowe** [comment]
@whedon assign @leios as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @leios

**Comment by will-rowe** [comment]
@whedon add @ninjin as reviewer

**Comment by whedon** [comment]
OK, @ninjin is now a reviewer

**Comment by will-rowe** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1956. Feel free to close this issue now!
