### ISSUE TITLE
[REVIEW]: whampy: Python Package to Interact with, Visualize, and Analyze the Wisconsin H-Alpha Mapper - Sky Survey

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1940]
**Submitting author:** @Deech08 (<a href="http://orcid.org/0000-0002-7955-7359">Dhanesh Krishnarao</a>)
**Repository:** <a href="https://github.com/Deech08/whampy" target ="_blank">https://github.com/Deech08/whampy</a>
**Version:** v1.0.1
**Editor:** @xuanxu
**Reviewer:** @Gabriel-p, @HeloiseS
**Archive:** <a href="https://doi.org/10.5281/zenodo.3591960" target="_blank">10.5281/zenodo.3591960</a>

## Status

[![status](https://joss.theoj.org/papers/feff21adb360b094e238e67e1051a81e/status.svg)](https://joss.theoj.org/papers/feff21adb360b094e238e67e1051a81e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/feff21adb360b094e238e67e1051a81e"><img src="https://joss.theoj.org/papers/feff21adb360b094e238e67e1051a81e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/feff21adb360b094e238e67e1051a81e/status.svg)](https://joss.theoj.org/papers/feff21adb360b094e238e67e1051a81e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Deech08/whampy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Gabriel-p & @HeloiseS, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @xuanxu know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Deech08/whampy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Deech08) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Deech08/whampy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Deech08) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Gabriel-p, @HeloiseS it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.3847/0004-637X/823/2/77 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.1086/378850 is OK
- 10.3847/1538-4357/aa63e6 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01940/joss.01940/10.21105.joss.01940.pdf)

**Comment by xuanxu** [comment]
@Deech08, @Gabriel-p, @HeloiseS : this is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention #1940 so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@xuanxu) if you have any questions/concerns.

**Comment by HeloiseS** [comment]
I got a quick question: do we expect there to be an explicit list of dependencies even if the package is pip installable?

**Comment by xuanxu** [comment]
@HeloiseS: to have an explicit list of requierements is not a mandatory or stopper condition to pass a JOSS review. But if you thinks it's a standard/good practice or you feel it is something a user would expect to find, it is totally ok to suggest the author to add that list to the readme (or add a requirements.txt file or whatever other solution you have in mind).

**Comment by HeloiseS** [comment]
Okay I have another question, this time about paper structure. 

The author ticks pretty much all the boxes but everything is under only one section. 
Is this an acceptable format for JOSS or would it be reasonable to ask for seperate sections to split the general summary from the specifics, or would that be redundant?

Sorry this is my first time reviewing for JOSS :smile:

**Comment by xuanxu** [comment]
@HeloiseS only one section is acceptable, yes, JOSS papers are usually quite short ([some](https://joss.theoj.org/papers/10.21105/joss.01896) [examples](https://joss.theoj.org/papers/10.21105/joss.01881)). But in any case if you think that section is too long or it would be clearer with different sections, asking for a split is also ok. So I guess the answer is "both options are acceptable". :smiley:

**Comment by HeloiseS** [comment]
Hello all!

I think I'm pretty happy with the paper and the code as it stands now. Unless major changes come from @Gabriel-p 's review that would require me to review the paper or code again, it's all good for me!

If there is anything else I need to do, or I forgot something, let me know @xuanxu :smiley: 

Merry Christmas to y'all :christmas_tree:

**Comment by xuanxu** [comment]
Great! thanks @HeloiseS!

@Gabriel-p: any update on your review?

**Comment by Gabriel-p** [comment]
Other than a very minor issue with the docs (just opened an issue at the code's repo), it looks good to me!

**Comment by Deech08** [comment]
Thanks @HeloiseS and @Gabriel-p for all the help and feedback, and @xuanxu for coordinating the review process! I've made a few final changes to fix to the minor documentation issues and all issues on the code repo are closed. I do want to change the package version to v1.0.0 when all review is complete to go along with the paper release so I'm wondering when the best time to do that is?

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01940/joss.01940/10.21105.joss.01940.pdf)

**Comment by xuanxu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.3847/0004-637X/823/2/77 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1086/378850 is OK
- 10.3847/1538-4357/aa63e6 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by xuanxu** [comment]
Thanks @HeloiseS and @Gabriel-p for the reviews!

**Comment by xuanxu** [comment]
OK @Deech08, everything looks good, here are the next steps:

- Please release a new tagged version from the current master so it includes all the changes made during the review process
- Then archive that latest release in Zenodo
- Check the Zenodo deposit has the correct metadata: title and author name should match the paper; you may also add your ORCID.

Once you do that please report here the version number and archive DOI

**Comment by Deech08** [comment]
Thanks again for your help!
I did notice one small issue in the paper - the additional astropy citation (2018) wasn't displaying properly, but is now fixed. 

The final release version is v1.0.1 (on pypi and Github). 
It is on Zenodo at the following:
https://doi.org/10.5281/zenodo.3591960

**Comment by xuanxu** [comment]
Great, @Deech08, thanks!

**Comment by xuanxu** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by xuanxu** [comment]
@whedon set 10.5281/zenodo.3591960 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3591960" target="_blank">10.5281/zenodo.3591960</a> is the archive.

**Comment by xuanxu** [comment]
Everything is ready 🎉
@openjournals/joss-eics sending it your way for final acceptance! 🚀

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.3847/0004-637X/823/2/77 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1086/378850 is OK
- 10.3847/1538-4357/aa63e6 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1200

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1200, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1209446602303299584) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1201
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01940](https://doi.org/10.21105/joss.01940)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@Gabriel-p, @HeloiseS - many thanks for your reviews and to @xuanxu for editing this submission ✨ 

@Deech08 - your paper is now accepted into JOSS :zap::rocket::boom:⛄️

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01940/status.svg)](https://doi.org/10.21105/joss.01940)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01940">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01940/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01940/status.svg
   :target: https://doi.org/10.21105/joss.01940
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01940/status.svg)](https://doi.org/10.21105/joss.01940)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
