### ISSUE TITLE
[REVIEW]: WulffPack: A Python package for Wulff constructions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1944]
**Submitting author:** @magnusrahm (<a href="http://orcid.org/0000-0002-6777-0371">Magnus Rahm</a>)
**Repository:** <a href="https://gitlab.com/materials-modeling/wulffpack" target ="_blank">https://gitlab.com/materials-modeling/wulffpack</a>
**Version:** v1.1
**Editor:** @drvinceknight
**Reviewer:** @EduPH, @mzszym, @corybrunson
**Archive:** <a href="https://doi.org/10.5281/zenodo.3600252" target="_blank">10.5281/zenodo.3600252</a>

## Status

[![status](https://joss.theoj.org/papers/f0887de96e6adf8e7ee3c0989b4003ed/status.svg)](https://joss.theoj.org/papers/f0887de96e6adf8e7ee3c0989b4003ed)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f0887de96e6adf8e7ee3c0989b4003ed"><img src="https://joss.theoj.org/papers/f0887de96e6adf8e7ee3c0989b4003ed/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f0887de96e6adf8e7ee3c0989b4003ed/status.svg)](https://joss.theoj.org/papers/f0887de96e6adf8e7ee3c0989b4003ed)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://gitlab.com/materials-modeling/wulffpack" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@EduPH & @mzszym & @corybrunson, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @drvinceknight know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/materials-modeling/wulffpack">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@magnusrahm) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/materials-modeling/wulffpack">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@magnusrahm) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/materials-modeling/wulffpack">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@magnusrahm) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @EduPH, @mzszym, @corybrunson it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1944 with the following error: 

 Can't find any papers to compile :-(

**Comment by drvinceknight** [comment]
@whedon generate pdf from branch joss-pape

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-pape. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1944 with the following error: 

 error: pathspec 'joss-pape' did not match any file(s) known to git.
Can't find any papers to compile :-(

**Comment by drvinceknight** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1524/zkri.1901.34.1.449 is OK
- 10.1016/0022-0248(83)90184-7 is OK
- https://doi.org/10.1016/0001-6160(67)90206-4 is OK
- https://doi.org/10.1016/j.commatsci.2012.10.028 is OK
- 10.1007/s10853-012-6739-x is OK
- 10.1016/S0927-0256(97)00167-5 is OK
- 10.1145/235815.235821 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1088/1361-648X/aa680e is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01944/joss.01944/10.21105.joss.01944.pdf)

**Comment by mzszym** [comment]
I believe that I am done with the review. I think it is a very good small module with a well defined function and a rather complete description. It is well implemented and I found no important issues. I could run the examples without problems. Constructed nanoparticles seem to be according to my expectations. The only thing I missed was the description how "this software compares to other commonly-used packages?", which I understand as a comparison with other packages offering the same or similar functionality.

**Comment by magnusrahm** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01944/joss.01944/10.21105.joss.01944.pdf)

**Comment by magnusrahm** [comment]
Thank you, @mzszym! The comparison to other packages was indeed very short. It is updated (and the missing reference has been fixed) in the latest version of the paper, like so:

> The regular Wulff construction has been implemented in
several software packages, including a submodule of the Python package pymatgen (Ong et
al., 2013), a no longer maintained C++ package (Roosen, McCormack, & Carter, 1998),
and a Wolfram Mathematica implementation with a graphical user interace (Zucker, Chatain,
Dahmen, Hagège, & Carter, 2012). While the latter code has support for Winterbottom
constructions, we have found no publicly available software that implements the icosahedral
and decahedral Wulff construction. The aforementioned codes also seem to lack the ability to
transform the created shapes into an atomistic representation, a feature of critical importance
if the Wulff construction is to be used for atomistic simulations.

**Comment by mzszym** [comment]
@magnusrahm Well done. I am confident that the package fulfills all requirements.

**Comment by drvinceknight** [comment]
I will be checking GitHub in a limited capacity over the next couple of weeks.

**Comment by corybrunson** [comment]
@drvinceknight and @magnusrahm thank you for your patience. I'm beginning my review now.

**Comment by corybrunson** [comment]
@magnusrahm thank you for the elegant software and thorough documentation behind this submission. In most respects i think it quite meets the needs of JOSS, and the few issues i've raised should be quick to resolve. I had no problems along the way other than those raised in the issues. The concepts are quite new to me, but i hope that i've grasped them well enough to give useful feedback. I'll be quick to respond to any questions about it, and i'll check off the remaining items as the issues are addressed.

**Comment by EduPH** [comment]
I agree with the other two reviewers. The package fulfils all the requirements.

**Comment by drvinceknight** [comment]
(Me closing the issue was a miss click)

Thank you very much for your work reviewing @EduPH, @mzszym, @corybrunson!

I'll be looking through this later today with any final minor editorial requests :+1:

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1944 with the following error: 

 Can't find any papers to compile :-(

**Comment by drvinceknight** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01944/joss.01944/10.21105.joss.01944.pdf)

**Comment by drvinceknight** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1524/zkri.1901.34.1.449 is OK
- 10.1016/0022-0248(83)90184-7 is OK
- 10.1016/0001-6160(67)90206-4 is OK
- 10.1016/j.commatsci.2012.10.028 is OK
- 10.1007/s10853-012-6739-x is OK
- 10.1016/S0927-0256(97)00167-5 is OK
- 10.1145/235815.235821 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1088/1361-648X/aa680e is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by drvinceknight** [comment]
@magnusrahm everything looks good to me, would you be able to make a Zenodo archive, and report the DOI in the review thread (here).

Could you make sure the Zenodo deposit has the correct metadata (title and author list should match the paper).

**Comment by magnusrahm** [comment]
@drvinceknight I have uploaded a Zenodo archive (10.5281/zenodo.3600252, https://doi.org/10.5281/zenodo.3600252). I have also merged the joss-paper branch into the master branch and deleted the former. Some very minor additions were made to the paper (https://gitlab.com/materials-modeling/wulffpack/commit/82b4e1771798733a6022ff292982bc17ea7b6310).

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01944/joss.01944/10.21105.joss.01944.pdf)

**Comment by drvinceknight** [comment]
@whedon set 10.5281/zenodo.3600252 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3600252" target="_blank">10.5281/zenodo.3600252</a> is the archive.

**Comment by drvinceknight** [comment]
@openjournals/joss-eics this paper is ready to be accepted :+1:

**Comment by danielskatz** [comment]
@magnusrahm  - it looks like this is now version 1.1 - correct?

**Comment by magnusrahm** [comment]
Yes, that's correct.

**Comment by danielskatz** [comment]
@whedon set v1.1 as version

**Comment by whedon** [comment]
OK. v1.1 is the version.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1088/0953-8984/28/5/053001 is OK
- 10.1524/zkri.1901.34.1.449 is OK
- 10.1016/0022-0248(83)90184-7 is OK
- 10.1016/0001-6160(67)90206-4 is OK
- 10.1016/j.commatsci.2012.10.028 is OK
- 10.1007/s10853-012-6739-x is OK
- 10.1016/S0927-0256(97)00167-5 is OK
- 10.1145/235815.235821 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1088/1361-648X/aa680e is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1205

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1205, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1214579352266035211) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1206
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01944](https://doi.org/10.21105/joss.01944)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @EduPH, @mzszym, @corybrunson for reviewing!
And @drvinceknight for editing!
And congratulations to @magnusrahm and co-authors!

**Comment by danielskatz** [comment]
I'm now waiting for the DOI to resolve, after which I will close this issue

**Comment by magnusrahm** [comment]
Thank you! 😃

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01944/status.svg)](https://doi.org/10.21105/joss.01944)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01944">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01944/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01944/status.svg
   :target: https://doi.org/10.21105/joss.01944
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01944/status.svg)](https://doi.org/10.21105/joss.01944)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
