### ISSUE TITLE
[REVIEW]: MatD3: A Database and Online Presentation Package for Research Data Supporting Materials Discovery, Design, and Dissemination

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1945]
**Submitting author:** @raullaasner (<a href="http://orcid.org/0000-0002-9714-1189">Raul Laasner</a>)
**Repository:** <a href="https://github.com/HybriD3-database/MatD3" target ="_blank">https://github.com/HybriD3-database/MatD3</a>
**Version:** v1
**Editor:** @majensen
**Reviewer:** @dgasmith, @mkhorton
**Archive:** <a href="https://doi.org/10.5281/zenodo.3609195" target="_blank">10.5281/zenodo.3609195</a>

## Status

[![status](https://joss.theoj.org/papers/016ab915d6c732c07f1a84b050524f6d/status.svg)](https://joss.theoj.org/papers/016ab915d6c732c07f1a84b050524f6d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/016ab915d6c732c07f1a84b050524f6d"><img src="https://joss.theoj.org/papers/016ab915d6c732c07f1a84b050524f6d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/016ab915d6c732c07f1a84b050524f6d/status.svg)](https://joss.theoj.org/papers/016ab915d6c732c07f1a84b050524f6d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/HybriD3-database/MatD3" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dgasmith & @mkhorton, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @majensen know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/HybriD3-database/MatD3">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@raullaasner) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/HybriD3-database/MatD3">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@raullaasner) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dgasmith, @mkhorton it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1038/sdata.2019.2 is OK
- 10.1063/1.4812323 is OK
- 10.1007/s11837-016-2001-3 is OK
- 10.1016/j.commatsci.2012.02.005 is OK
- 10.1007/s11837-013-0755-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01945/joss.01945/10.21105.joss.01945.pdf)

**Comment by mkhorton** [comment]
@raullaasner what's the easiest way to import some example data for testing?

**Comment by raullaasner** [comment]
@mkhorton The easiest way is to login on the website as the superuser (or create a regular user and use that) and click on the "Add Data" button. This presents you with a lot fields describing the data set, but only a few are mandatory. Click on "Submit" at the bottom to see which ones are mandatory and fill those in with some made up data.

Other than that, there is no import feature, i.e., the data needs to be manually inserted. If such a feature is necessary, I could implemented it in a day or two.

**Comment by mkhorton** [comment]
Ok, that should be sufficient, thank you. I just need it to test functionality :-) Reading the docs made it sound like it needed to be connected to a Qresp backend.

**Comment by dgasmith** [comment]
My requested changes have been integrated! I believe I have completed the review process.

**Comment by majensen** [comment]
Excellent @dgasmith - @mkhorton - how is your review coming along? Your checklist is almost complete.
Thanks all

**Comment by mkhorton** [comment]
I've also completed my review on this code and it's ready to go. Overall, this is a nice example of using the Django framework to create an interactive web app for exploring a materials database.

**Comment by majensen** [comment]
Thanks very much all! I will proceed with some editorial checks -- @raullaasner these may lead to some minor PRs from me.

**Comment by majensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01945/joss.01945/10.21105.joss.01945.pdf)

**Comment by majensen** [comment]
@raullaasner the proof looks good. Can you please create an archive of the software repository using [Zenodo](https://zenodo.org) or similar? [This comment](https://github.com/openjournals/joss-reviews/issues/1839#issuecomment-560048729) gives a quick overview for creating one on Zenodo. 

When you have done that, please report the archive DOI back to us here -- thanks!

**Comment by majensen** [comment]
👋 @raullaasner  - this paper is nearing acceptance; can you please review the [previous comment](https://github.com/openjournals/joss-reviews/issues/1945#issuecomment-573376626) and provide a software archive? thanks

**Comment by raullaasner** [comment]
@majensen Here is the Zenodo DOI: 10.5281/zenodo.3609195.

**Comment by majensen** [comment]
@whedon set 10.5281/zenodo.3609195 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3609195" target="_blank">10.5281/zenodo.3609195</a> is the archive.

**Comment by majensen** [comment]
@whedon set v1 as version

**Comment by whedon** [comment]
OK. v1 is the version.

**Comment by majensen** [comment]
Hello @openjournals/joss-eics - the reviewers have recommended acceptance of #1945. @raullaasner has provided the archive, which checks out for title and authors, and whedon has done his duty. Thanks!

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/sdata.2019.2 is OK
- 10.1063/1.4812323 is OK
- 10.1007/s11837-016-2001-3 is OK
- 10.1016/j.commatsci.2012.02.005 is OK
- 10.1007/s11837-013-0755-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Looks good to me!

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/sdata.2019.2 is OK
- 10.1063/1.4812323 is OK
- 10.1007/s11837-016-2001-3 is OK
- 10.1016/j.commatsci.2012.02.005 is OK
- 10.1007/s11837-013-0755-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1229

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1229, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1217864724706209797) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1230
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01945](https://doi.org/10.21105/joss.01945)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @raullaasner on your article's publication in JOSS!

Thanks to @dgasmith and @mkhorton for reviewing this, and @majensen for editing.

**Comment by majensen** [comment]
Thanks @dgasmith and @mkhorton , and congrats @raullaasner !

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01945/status.svg)](https://doi.org/10.21105/joss.01945)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01945">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01945/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01945/status.svg
   :target: https://doi.org/10.21105/joss.01945
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01945/status.svg)](https://doi.org/10.21105/joss.01945)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by kyleniemeyer** [comment]
Hey @majensen, just FYI I was leaving the issue open until the PDF builds/resolves on the article page—you can generally leave that to the handling AEiC

**Comment by majensen** [comment]
Oops thanks @kyleniemeyer will do!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01945/status.svg)](https://doi.org/10.21105/joss.01945)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01945">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01945/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01945/status.svg
   :target: https://doi.org/10.21105/joss.01945
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01945/status.svg)](https://doi.org/10.21105/joss.01945)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by raullaasner** [comment]
Thank you all for the acceptance!
