### ISSUE TITLE
[PRE REVIEW]: CoreBreakout: Subsurface Core Images to Depth-Registered Datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1946]
**Submitting author:** @rgmyr (<a href="http://orcid.org/0000-0003-2344-554X">Ross Meyer</a>)
**Repository:** <a href="https://github.com/rgmyr/corebreakout" target ="_blank">https://github.com/rgmyr/corebreakout</a>
**Version:** v0.2
**Editor:** @kbarnhart
**Reviewers:** @brendonhall, @JesperDramsch, @jessepisel

**Author instructions**

Thanks for submitting your paper to JOSS @rgmyr. **Currently, there isn't an JOSS editor assigned** to your paper.

@rgmyr if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1946 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1946 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd7dadefdab3/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd7dadefdab3/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd7dadefdab3/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
@kbarnhart could you edit this submission?

**Comment by kyleniemeyer** [comment]
@openjournals/dev any ideas why the paper won't compile? The error message is not too helpful for me.

**Comment by danielskatz** [comment]
could be a problem with a file - is the bib file correctly named and does it exist?  or any images?

**Comment by kyleniemeyer** [comment]
The bib file looks ok, but there is an image in the article: `![Figure 1](JOSS_figure_workflow.png)`

I do see a `JOSS_figure_workflow.png` in the repo, in the same location as the `paper.md`, so I'm not sure why that would cause an error.

**Comment by arfon** [comment]
A couple of issues here: 

- Whedon is likely timing out here as the repository is _very_ large (2.3GB!) even though there's only ~104MB of files present in the repository.
- Also, the bibtex has errors that I've fixed in https://github.com/rgmyr/corebreakout/pull/3

Finally, here's a copy of the paper I compiled locally: [10.21105.joss.01946.pdf](https://github.com/openjournals/joss-reviews/files/3958474/10.21105.joss.01946.pdf)

**Comment by kyleniemeyer** [comment]
@arfon  @rgmyr wow! That is a huge repository... is the large size due to files that were removed but are in the history?

If you know the files, you can remove them from the history using this: https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository#purging-a-file-from-your-repositorys-history

This is likely going to continue to be an issue, not only for whedon but for others looking to clone the repo, and so worth addressing.

**Comment by rgmyr** [comment]
Sounds good, thanks for the help guys. I wasn't sure what the problem was with paper compilation -- it seemed to be working via the preview service for awhile, and then it just stopped being able to compile all of the sudden.

I've merged @arfon's PR, and will look through the history to see where that extra size is coming from... I'm not sure of the top of my head, but I wouldn't be surprised if there were a few model files or data folders hiding in there accidentally.

**Comment by rgmyr** [comment]
I was having a hard time tracking down and removing the offending files/folders individually, so I tried a couple of things: 
- Created a new `--orphan` branch, set that as `master`, and removed some old temporary branches that aren't relevant anymore. (Following [this stackoverflow answer](https://stackoverflow.com/questions/9683279/make-the-current-commit-the-only-initial-commit-in-a-git-repository/13102849#13102849).)
- That didn't seem to actually change the size much, if at all, so I also tried cleaning things up [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/).

I ended up having to be pretty aggressive with the latter. I think a lot of files were deleted from the history, but I made a local backup incase I need to restore for some reason, and I don't foresee it being a big problem for code management going forward.

In any case, the repo size is now 182MB, and the paper compiles pretty quickly on the preview service.

**Comment by rgmyr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01946/joss.01946/10.21105.joss.01946.pdf)

**Comment by rgmyr** [comment]
Just made a couple of small fixes (multiple reference separator, figure text)...

@whedon generate pdf

**Comment by rgmyr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01946/joss.01946/10.21105.joss.01946.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/s11263-007-0090-8 is OK
- 10.6084/m9.figshare.8023835.v2 is OK
- 10.1002/2016JF003903 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kbarnhart** [comment]
@kyleniemeyer I can also handle this one.

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by kyleniemeyer** [comment]
@kbarnhart thanks!

**Comment by ThomasMGeo** [comment]
Maybe @brendonhall or @kwinkunks would be interested in reviewing?

**Comment by brendonhall** [comment]
@ThomasMGeo I'm happy to talk a look.  Are there instructions for reviewing?

**Comment by rgmyr** [comment]
Hi @brendonhall, here's the [Reviewer Guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). Once a [Review] issue is opened, each reviewer gets a [review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html) to work through (check out some of the review issues in this repo for examples).

**Comment by kbarnhart** [comment]
@rgmyr thank you for the recommendations. I'm now fully back online after a week at AGU. 

@brendonhall thank you for agreeing to review this publication. In my next comment, I'll formally add you. 

:wave: @kwinkunks would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue that I use to coordinate reviewers. Once there are sufficient reviewers (usually 2-3), I will open a new issue where the review will take place. 

If you are not able, please let me know if you have recommendations for other reviewers.

**Comment by kbarnhart** [comment]
@whedon assign @brendonhall as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @brendonhall

**Comment by ThomasMGeo** [comment]
Jesper Dramsch @ JesperDramsch might also be a decent reviewer

**Comment by kbarnhart** [comment]
:wave: @JesperDramsch would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue that I use to coordinate reviewers. Once there are sufficient reviewers (usually 2-3), I will open a new issue where the review will take place. 

If you are not able, please let me know if you have recommendations for other reviewers.

**Comment by ThomasMGeo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01946/joss.01946/10.21105.joss.01946.pdf)

**Comment by ThomasMGeo** [comment]
Jesse Pisel @jessepisel just reached out to me! Thanks Jesse!

**Comment by JesperDramsch** [comment]
This seems awesome. I'd love to take a look and review this.

I'll probably be best on the python and ml bits and ok on the core.

**Comment by ThomasMGeo** [comment]
Luckily it's way more the python/ML bits, and just being able to say rock vs no rock! Thanks @JesperDramsch

**Comment by ThomasMGeo** [comment]
Dr. Chris Yeomans (@swgeoscience) also reached out to be a reviewer.

**Comment by kbarnhart** [comment]
Thanks for being willing to review @JesperDramsch 

Thanks also @ThomasMGeo for your assistance in finding appropriate reviewers. 

:wave: @swgeoscience @jessepisel can you confirm on this thread that would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue that I use to coordinate reviewers. Once there are sufficient reviewers (usually 2-3, it looks like this submission may have 4), I will open a new issue where the review will take place.

**Comment by kbarnhart** [comment]
@whedon add @JesperDramsch as reviewer

**Comment by whedon** [comment]
OK, @JesperDramsch is now a reviewer

**Comment by jessepisel** [comment]
I am willing to review this submission. Excited to check it out.

**Comment by kbarnhart** [comment]
@whedon add @jessepisel as reviewer

**Comment by whedon** [comment]
OK, @jessepisel is now a reviewer

**Comment by kbarnhart** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1969. Feel free to close this issue now!

**Comment by kbarnhart** [comment]
Thanks all for your enthusiasm for finding reviewers and recommending reviewers. I've started the formal review over at #1969. @swgeoscience, if you are really excited to also be a reviewer, let me know and I can add you over on that issue. 

For those of you who are interested in being listed on our [list of potential reviewers](https://bit.ly/joss-reviewers) for future submissions, please consider filling out the 1-minute form at [this link](https://joss.theoj.org/reviewer-signup.html). This helps editors and authors find appropriate reviewers.

**Comment by swgeoscience** [comment]
Hi Katy,

 

Apologies, I’ve just found this email – combination of being on leave and not having my github linked to the right account!

 

If you still require a review from me I am happy to complete it. 

 

Again, apologies!

 

Best wishes,
Chris

**Comment by kbarnhart** [comment]
@swgeoscience no worries. I think that we are good with three reviewers. If you are interested in generally being considered as a JOSS reviewer 🎉,  please consider filling out the 1-minute form at [this link](https://joss.theoj.org/reviewer-signup.html).
