### ISSUE TITLE
[PRE REVIEW]: scikit-hubness: Hubness Reduction and Approximate Neighbor Search

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1947]
**Submitting author:** @VarIr (<a href="http://orcid.org/0000-0003-2216-4295">Roman Feldbauer</a>)
**Repository:** <a href="https://github.com/VarIr/scikit-hubness/" target ="_blank">https://github.com/VarIr/scikit-hubness/</a>
**Version:** v0.21.1
**Editor:** @terrytangyuan
**Reviewers:** @ryEllison, @aozorahime

**Author instructions**

Thanks for submitting your paper to JOSS @VarIr. **Currently, there isn't an JOSS editor assigned** to your paper.

@VarIr if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1109/TKDE.2013.25 is OK
- 10.1016/j.knosys.2015.06.010 is OK

MISSING DOIs

- https://doi.org/10.1109/icdmw.2013.101 may be missing for title: Can Shared Nearest Neighbors Reduce Hubness in High-Dimensional Spaces?
- https://doi.org/10.1080/09298215.2017.1354891 may be missing for title: Mutual proximity graphs for improved reachability in music recommendation
- https://doi.org/10.1007/s10115-018-1205-y may be missing for title: A comprehensive empirical comparison of hubness reduction in high-dimensional spaces
- https://doi.org/10.1109/icbk.2018.00055 may be missing for title: Fast Approximate Hubness Reduction for Large High-Dimensional Data
- https://doi.org/10.1109/tpami.2018.2889473 may be missing for title: Efficient and robust approximate nearest neighbor search using Hierarchical Navigable Small World graphs
- https://doi.org/10.1109/ijcnn.2015.7280303 may be missing for title: The unbalancing effect of hubs on K-medoids clustering in high-dimensional spaces

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01947/joss.01947/10.21105.joss.01947.pdf)

**Comment by kyleniemeyer** [comment]
@terrytangyuan could you edit this submission?

**Comment by terrytangyuan** [comment]
@whedon assign @terrytangyuan as editor

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by terrytangyuan** [comment]
👋 @VarIr if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Comment by VarIr** [comment]
@terrytangyuan Thanks for editing my submission! I have no particular preference for any reviewers. The following people from the list could be good fits: axel-loewe, road2stat, dirmeier, faroit, JesseLivezey, ryEllison, b-freitas, iskandr, osolari, dvanic, innat, aozorahime, snikumbh, gavinmdouglas

**Comment by terrytangyuan** [comment]
👋 @axel-loewe, @nan2stat, @dirmeier, @faroit, @JesseLivezey, @ryEllison, @b-freitas, @iskandr, @osolari, @dvanic, @innat, @aozorahime, @snikumbh, @gavinmdouglas Hi! If you'd like to review for this submission, please let us know here!

**Comment by ryEllison** [comment]
I’d love to review this article. 

Ryan

**Comment by aozorahime** [comment]
I'd love to help you

**Comment by terrytangyuan** [comment]
@whedon assign @ryEllison as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ryEllison

**Comment by terrytangyuan** [comment]
@whedon add @aozorahime as reviewer

**Comment by whedon** [comment]
OK, @aozorahime is now a reviewer

**Comment by terrytangyuan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1957. Feel free to close this issue now!

**Comment by terrytangyuan** [comment]
Thanks! @ryEllison, @aozorahime I'll see you in #1957. Look forward to your review!
