### ISSUE TITLE
[PRE REVIEW]: shapr: An R-package for explaining machine learning models with dependence-aware Shapley values 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1948]
**Submitting author:** @martinju (<a href="http://orcid.org/0000-0003-3908-5155">Martin Jullum</a>)
**Repository:** <a href="https://github.com/NorskRegnesentral/shapr" target ="_blank">https://github.com/NorskRegnesentral/shapr</a>
**Version:** v0.1.0
**Editor:** @terrytangyuan
**Reviewers:** @frycast, @expectopatronum

**Author instructions**

Thanks for submitting your paper to JOSS @martinju. **Currently, there isn't an JOSS editor assigned** to your paper.

@martinju if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01948/joss.01948/10.21105.joss.01948.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.18637/jss.v040.i08 is OK

MISSING DOIs

- https://doi.org/10.1007/s10115-013-0679-x may be missing for title: Explaining prediction models and individual predictions with feature contributions
- https://doi.org/10.1111/1467-9868.00125 may be missing for title: Smoothing parameter selection in nonparametric regression using an improved Akaike information criterion
- https://doi.org/10.1214/aoms/1177728190 may be missing for title: Remarks on Some Nonparametric Estimates of a Density Function

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@terrytangyuan sorry for the double ask, but this one looks well-suited for you to edit as well. Do you have bandwidth to edit another submission?

**Comment by terrytangyuan** [comment]
@whedon assign @terrytangyuan as editor

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by terrytangyuan** [comment]
:wave @martinju if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Comment by martinju** [comment]
Thank you for opening this review. 
I suggest the following reviewers: 
expectopatronum, hiendn, ja-thomas, kdpeterson51, road2stat​

**Comment by terrytangyuan** [comment]
👋 @expectopatronum, @hiendn, @ja-thomas, @kdpeterson51, @nanxstats if you would like to review for this submission, please let us know here!

**Comment by ja-thomas** [comment]
My colleague @christophM could do the review, he works as a researcher in interpretable machine learning.

**Comment by christophM** [comment]
It seems like a good match. Let me know if I can help you review this paper.

**Comment by hiendn** [comment]
I think that @frycast would be perfect as a reviewer for this paper. He is currently working on a Shapley values project of his own!

**Comment by terrytangyuan** [comment]
@whedon add @christophM as reviewer

**Comment by whedon** [comment]
OK, @christophM is now a reviewer

**Comment by terrytangyuan** [comment]
Thanks @hiendn. @frycast Would you like to review this submission? If anyone else wants to get involved, please confirm here as well.

**Comment by terrytangyuan** [comment]
@whedon remove @christophM as reviewer

**Comment by whedon** [comment]
OK, @christophM is no longer a reviewer

**Comment by terrytangyuan** [comment]
@ja-thomas There's potential conflict of interest according to @christophM so I am removing him for now. @ja-thomas Would you like to review this instead?

**Comment by martinju** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01948/joss.01948/10.21105.joss.01948.pdf)

**Comment by martinju** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/s10115-013-0679-x is OK
- 10.1111/1467-9868.00125 is OK
- 10.1214/aoms/1177728190 is OK
- 10.18637/jss.v040.i08 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by martinju** [comment]
DOI's should be fine now.
@terrytangyuan  do you need more help to find potential reviewers?

**Comment by frycast** [comment]
Hi @terrytangyuan and @martinju . I'm more than happy to review this.

**Comment by martinju** [comment]
@terrytangyuan If possible I would really appreciate getting the review rolling soon. Please let me know if there is anything I can do to speed up the process. For instance, do you need help to find more potential reviewers?

**Comment by terrytangyuan** [comment]
@whedon assign @frycast as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @frycast

**Comment by terrytangyuan** [comment]
We just need another reviewer now

**Comment by martinju** [comment]
> @ja-thomas There's potential conflict of interest according to @christophM so I am removing him for now. @ja-thomas Would you like to review this instead?

@ja-thomas ?

**Comment by martinju** [comment]
@terrytangyuan 
Since ja-thomas does not seem to answer I am suggesting a new list of potential reviewers:

expectopatronum, agisga, schalkdaniel, robohyun66, road2stat, ajank

**Comment by terrytangyuan** [comment]
@martinju Thanks. @robohyun66 @ajank @agisga Would any of you be willing to review for this submission?

**Comment by martinju** [comment]
Apparently no response from any of those either. 
Here are a couple of more suggestions: 
bahung, ati-ozgur, asntech, alessandroBombelli, Aguang, tianxzhu, dirmeier, zaxtax

**Comment by expectopatronum** [comment]
I am sorry for the very late response. I would be willing to do a review starting in February, before that I have deadlines.

**Comment by terrytangyuan** [comment]
@whedon add @expectopatronum as reviewer

**Comment by whedon** [comment]
OK, @expectopatronum is now a reviewer

**Comment by terrytangyuan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2027. Feel free to close this issue now!

**Comment by terrytangyuan** [comment]
Thanks everyone! Please head over to #2027 for the review!
