### ISSUE TITLE
[PRE REVIEW]: SampleDB: A sample and measurement metadata database

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1949]
**Submitting author:** @FlorianRhiem (<a href="http://orcid.org/0000-0001-6461-9433">Florian Rhiem</a>)
**Repository:** <a href="https://github.com/sciapp/sampledb" target ="_blank">https://github.com/sciapp/sampledb</a>
**Version:** v0.8.1
**Editor:** @trallard
**Reviewers:** @eteq, @dvanic

**Author instructions**

Thanks for submitting your paper to JOSS @FlorianRhiem. **Currently, there isn't an JOSS editor assigned** to your paper.

@FlorianRhiem if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01949/joss.01949/10.21105.joss.01949.pdf)

**Comment by kyleniemeyer** [comment]
Hi @trallard, could you edit this one for us?

**Comment by trallard** [comment]
Sure send this my way!

**Comment by kyleniemeyer** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by trallard** [comment]
Hi @FlorianRhiem 👋  I will be serving as the editor for this submission. 
The first thing we have to do is find 2 or more reviewers for this. 

Do you already have some folks in mind? if not you can check our list of reviewers available here 👉🏼 <https://bit.ly/joss-reviewers>

**Comment by FlorianRhiem** [comment]
Hello @trallard, I just went through the list and perhaps eteq, usethedata and/or jsta would be willing to review this?

**Comment by trallard** [comment]
Ok let's ping the reviewers now :sparkles: 

@eteq Erik, would you be able and willing to review this submission?
@usethedata Bruce, would you be able and willing to review this submission?
@jsta Joseph, would you be able and willing to review this submission?

Some important information:
- Our reviewer guidelines can be found here <https://joss.readthedocs.io/en/latest/review_criteria.html>
- **Title**:  SampleDB: A sample and measurement metadata database
- **GitHub repository**: https://github.com/sciapp/sampledb
-  **Submitting author**: @FlorianRhiem Florian Rhiem

We are looking at finding two reviewers to move this submission forward.

**Comment by eteq** [comment]
I can do this review, although it might take some time due to the holidays and related travel/vacation

**Comment by FlorianRhiem** [comment]
@eteq Thank you, that would be great! :)

@trallard It's been two weeks, should we wait for a reply from @usethedata or @jsta due to the holidays, or should I look for other reviewer candidates from the google doc?

**Comment by jsta** [comment]
@trallard I cannot take on a reviewing task at this time. Best of luck!

**Comment by FlorianRhiem** [comment]
@trallard Perhaps celliern, dvanic, remram44, fabianomenegidio and/or atrisovic could do the review?

**Comment by FlorianRhiem** [comment]
@trallard May I ping them with an updated version of your comment, will you ping them, or how do we continue? I'm feeling somewhat lost regarding the process at the moment.

**Comment by trallard** [comment]
@celliern, @dvanic, @remram44 @fabioanomenegidio, @astrisovic I am the editor for this submission and we are looking for at least 2 reviewers. Would you be able/willing to review this submission?

Some important information:

Our reviewer guidelines can be found here <https://joss.readthedocs.io/en/latest/review_criteria.html>

- Title: SampleDB: A sample and measurement metadata database
- GitHub repository: <https://github.com/sciapp/sampledb>
- Submitting author: @FlorianRhiem Florian Rhiem

**Comment by trallard** [comment]
@whedon assign @eteq as reviewer

**Comment by whedon** [comment]
OK, @eteq is now a reviewer

**Comment by dvanic** [comment]
Yes, I'm happy to review this submission.

**Comment by trallard** [comment]
Thanks @dvanic!

**Comment by trallard** [comment]
@whedon add @dvanic as reviewer

**Comment by whedon** [comment]
OK, @dvanic is now a reviewer

**Comment by arfon** [comment]
@trallard - this looks like it's ready to move to review unless I'm missing something?

**Comment by trallard** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2107.
