### ISSUE TITLE
[PRE REVIEW]: Museo ToolBox : a python library for remote sensing including a new way to handle rasters.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1950]
**Submitting author:** @nkarasiak (<a href="http://orcid.org/0000-0002-1558-0816">Nicolas Karasiak</a>)
**Repository:** <a href="https://github.com/nkarasiak/MuseoToolBox" target ="_blank">https://github.com/nkarasiak/MuseoToolBox</a>
**Version:** v0.12
**Editor:** @kbarnhart
**Reviewers:** @cmillion, @mollenburger

**Author instructions**

Thanks for submitting your paper to JOSS @nkarasiak. **Currently, there isn't an JOSS editor assigned** to your paper.

@nkarasiak if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.3390/rs11212512 is OK
- 10.1111/ecog.02881 is OK
- 10.1016/j.rse.2014.02.015 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01950/joss.01950/10.21105.joss.01950.pdf)

**Comment by kyleniemeyer** [comment]
Hi @kbarnhart, sorry for two requests today, but could you edit this one as well? With the focus on remote observations I thought it might be in your wheelhouse.

**Comment by nkarasiak** [comment]
@whedon set v0.12 as version

Hi, just to inform you that to respect semantic versioning I changed how I named my version. So the current version to review is now v0.12.
Kind regards,
Nicolas.

**Comment by whedon** [comment]
I'm sorry @nkarasiak, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by kbarnhart** [comment]
@kyleniemeyer I can handle this one.

**Comment by kbarnhart** [comment]
@whedon set @kbarnhart as editor

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by kyleniemeyer** [comment]
@whedon set v0.12 as version

**Comment by whedon** [comment]
OK. v0.12 is the version.

**Comment by nkarasiak** [comment]
Hello,
Here is a list of the three potential reviewers I identified : 

- MES1605 (satellite images and and classification)
- cmillion (image processing & python)
- OopsAllErrors (remote sensing & image processing)

Kind regards,
Nicolas Karasiak.

**Comment by kbarnhart** [comment]
Thanks for the recommendations @nkarasiak 

:wave: @cmillion, @OopsAllErrors, would either of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue that I use to coordinate reviewers. Once there are sufficient reviewers (usually 2-3), I will open a new issue where the review will take place. 

If you are not able, please let me know if you have recommendations for other reviewers.

**Comment by cmillion** [comment]
Yes.

**Comment by kbarnhart** [comment]
@whedon assign @cmillion as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @cmillion

**Comment by cmillion** [comment]
I recommend @mollenburger as an additional reviewer.

**Comment by kbarnhart** [comment]
Thanks for the recommendation @cmillion 

:wave: @mollenburger would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue that I use to coordinate reviewers. Once there are sufficient reviewers (usually 2-3), I will open a new issue where the review will take place. 

If you are not able, please let me know if you have recommendations for other reviewers.

**Comment by mollenburger** [comment]
@kbarnhart  sure, I can review this

**Comment by kbarnhart** [comment]
@whedon add @mollenburger as reviewer

**Comment by whedon** [comment]
OK, @mollenburger is now a reviewer

**Comment by kbarnhart** [comment]
:wave: @OopsAllErrors, would you be willing to review this? If not, might you have any recommendations?

**Comment by kbarnhart** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1978. Feel free to close this issue now!

**Comment by kbarnhart** [comment]
I'm going to transition this submission from pre-review to review with two reviewers. 

Thanks all for your enthusiasm for finding and recommending reviewers. I've started the formal review over at #1978. 

For those of you who are not yet listed on our [list of potential reviewers](https://bit.ly/joss-reviewers) for future submissions, please consider filling out the 1-minute form at [this link](https://joss.theoj.org/reviewer-signup.html). This helps editors and authors find appropriate reviewers.
