### ISSUE TITLE
[PRE REVIEW]: Pubmed Parser: A Python Parser for PubMed Open-Access XML Subset and MEDLINE XML Dataset XML Dataset

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1951]
**Submitting author:** @titipata (<a href="http://orcid.org/0000-0002-2124-2979">Titipat Achakulvisut</a>)
**Repository:** <a href="https://github.com/titipata/pubmed_parser" target ="_blank">https://github.com/titipata/pubmed_parser</a>
**Version:** v0.2.1
**Editor:** @majensen
**Reviewers:** @timClicks, @tleonardi

**Author instructions**

Thanks for submitting your paper to JOSS @titipata. **Currently, there isn't an JOSS editor assigned** to your paper.

@titipata if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01951/joss.01951/10.21105.joss.01951.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.7287/peerj.preprints.27479v2 may be missing for title: ProPheno 1.0: An Online Dataset for Accelerating the Complete Characterization of the Human Protein-phenotype Landscape in Biomedical Literature
- https://doi.org/10.18653/v1/w18-2307 may be missing for title: Sub-word information in pre-trained biomedical word representations: evaluation and hyper-parameter optimization
- https://doi.org/10.1371/journal.pone.0198030 may be missing for title: Data-driven analysis of biomedical literature suggests broad-spectrum benefits of culinary herbs and spices
- https://doi.org/10.1109/hpcc/smartcity/dss.2019.00217 may be missing for title: Parallel Computing for Large-Scale Author Name Disambiguation in MEDLINE

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @titipata, it looks like your article is missing DOIs for a number of the references; could you add those? Please review all the references (including their formatting), in case others are missing DOIs as well.

**Comment by kyleniemeyer** [comment]
Hi @majensen, could you edit this one for us?

**Comment by titipata** [comment]
Hi @kyleniemeyer, definitely, thank you! I added the missing DOIs and will check the other references.

**Comment by titipata** [comment]
@kyleniemeyer here is my list other potential reviewers if majensen is not available: Gweissman, stensy, timClicks, cbrueffer, ethanwhite, and skummerf

**Comment by majensen** [comment]
@whedon assign @majensen as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by titipata** [comment]
Thanks a lot @majensen and @kyleniemeyer! Let me know if you need any help providing an extra list of suggested reviewers!

**Comment by majensen** [comment]
@titipata sorry for wait, want to get on this tonight.

**Comment by titipata** [comment]
No worry @majensen! Thanks in advance!

**Comment by majensen** [comment]
Hello @timClicks -- would you be willing to review this artice (#1951) for [JOSS](https://joss.theoj.org)? Thanks for your consideration! --@majensen

**Comment by majensen** [comment]
Hey @tleonardi, would you have time to review this article (#1951) for [JOSS](https://joss.theoj.org)? Prego! --@majensen

**Comment by timClicks** [comment]
Happy to @majensen.

**Comment by majensen** [comment]
@timClicks very much appreciated -- thanks!

**Comment by majensen** [comment]
@whedon assign @timClicks as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @timClicks

**Comment by titipata** [comment]
Thanks, @majensen and @timClicks for reviewing!

**Comment by tleonardi** [comment]
Hi @majensen would love too this paper, but I already have too many commitments before the end of the year. If needed I'd be happy to review it in early January.

**Comment by titipata** [comment]
@majensen @tleonardi I am happy to wait until early January! I am in no rush during the holiday period.

**Comment by majensen** [comment]
@tleonardi thanks very much -- @titipata is ok with that and so am I. Very much appreciated!

**Comment by majensen** [comment]
@whedon add @tleonardi as reviewer

**Comment by whedon** [comment]
OK, @tleonardi is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1979. Feel free to close this issue now!

**Comment by majensen** [comment]
@titipata @timClicks @tleonardi we'll begin reviewing over at #1979. Thanks again all and Happy Holidays!
