### ISSUE TITLE
[PRE REVIEW]: DAFSA: a Python library for Deterministic Acyclic FiniteState Automata

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1953]
**Submitting author:** @tresoldi (<a href="http://orcid.org/0000-0002-2863-1467">Tiago Tresoldi</a>)
**Repository:** <a href="https://github.com/tresoldi/dafsa" target ="_blank">https://github.com/tresoldi/dafsa</a>
**Version:** v0.5.1
**Editor:** @gkthiruvathukal
**Reviewers:** @geoffbacon, @desilinguist

**Author instructions**

Thanks for submitting your paper to JOSS @tresoldi. **Currently, there isn't an JOSS editor assigned** to your paper.

@tresoldi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kyleniemeyer** [comment]
Hi @gkthiruvathukal, can you edit this one?

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/0304-3975(85)90157-4 may be missing for title: The smallest automation recognizing the subwords of a text
- https://doi.org/10.1002/spe.402 may be missing for title: How to squeeze a lexicon
- https://doi.org/10.1002/spe.4380230103 may be missing for title: Applications of finite automata representing large vocabularies

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01953/joss.01953/10.21105.joss.01953.pdf)

**Comment by kyleniemeyer** [comment]
Hi @tresoldi, could you review the references in your article and add DOIs for those missing?

**Comment by gkthiruvathukal** [comment]
@kyleniemeyer Yes. I will assign myself, if I can!

**Comment by gkthiruvathukal** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by tresoldi** [comment]
Thank you, everyone!

I've pushed a `paper.bib` with the DOIs (commit https://github.com/tresoldi/dafsa/commit/1e3b555f00c90809d172fa45a5bdf34adf680163) and the preview is working ([here](https://res.cloudinary.com/hju22ue2k/image/upload/v1576182013/hdshcpv6jw19uz8so5fl.pdf)).

@whedon generate pdf

**Comment by tresoldi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01953/joss.01953/10.21105.joss.01953.pdf)

**Comment by gkthiruvathukal** [comment]
@tresoldi Can you take a look at the list of reviewers (see above by scrolling up to top of this issue thread) and mention any prospective reviewers for your submission?

**Comment by tresoldi** [comment]
@gkthiruvathukal sorry, I assumed it was not a mandatory step, but one for suggestions. From the list, I'd guess (mentioning with the @) desilinguist, jkahn, ionlights, mbod, and/or geoffbacon would be the ones most in line. SimonGreenhill would be a great reviewer, but we know each other and work in the same department.

**Comment by gkthiruvathukal** [comment]
@desilinguist, @jkahn, @ionlights, @mbod, @geoffbacon, are any 2 of you willing to contribute a review for this JOSS submission?

**Comment by gkthiruvathukal** [comment]
@whedon help

**Comment by gkthiruvathukal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by gkthiruvathukal** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/0304-3975(85)90157-4 is OK
- 10.1002/spe.402 is OK
- 10.1002/spe.4380230103 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by gkthiruvathukal** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01953/joss.01953/10.21105.joss.01953.pdf)

**Comment by desilinguist** [comment]
I am happy to review but I won’t be able to do this until the middle of January.

**Comment by geoffbacon** [comment]
> @desilinguist, @jkahn, @ionlights, @mbod, @geoffbacon, are any 2 of you willing to contribute a review for this JOSS submission?

@gkthiruvathukal I'd be happy to review!

**Comment by gkthiruvathukal** [comment]
Happy holidays, @geoffbacon and @desilinguist. Thanks for your willingness to serve as reviewers. I will get the review started now but will work with your schedules. I know many are on holiday break/travel, so January is fine for getting the actual work started.

**Comment by gkthiruvathukal** [comment]
@whedon assign @geoffbacon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @geoffbacon

**Comment by gkthiruvathukal** [comment]
@whedon add @desilinguist as reviewer

**Comment by whedon** [comment]
OK, @desilinguist is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1986. Feel free to close this issue now!
