### ISSUE TITLE
[PRE REVIEW]: LFSpy: A Python Implementation of Local Feature Selection for Data Classification with scikit-learn Compatibility

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1954]
**Submitting author:** @kiretd (<a href="http://orcid.org/0000-0003-4849-732X">Kiret Dhindsa</a>)
**Repository:** <a href="https://github.com/McMasterRS/LFSpy" target ="_blank">https://github.com/McMasterRS/LFSpy</a>
**Version:** 1.0.0
**Editor:** @dfm
**Reviewers:** @effigies, @mnarayan

**Author instructions**

Thanks for submitting your paper to JOSS @kiretd. **Currently, there isn't an JOSS editor assigned** to your paper.

@kiretd if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1109/tnnls.2017.2676101 may be missing for title: Logistic localized modeling of the sample space for feature selection and classification
- https://doi.org/10.1109/jbhi.2018.2877738 may be missing for title: A Machine Learning Framework for Automatic and Continuous MMN Detection with Preliminary Results for Coma Outcome Prediction

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01954/joss.01954/10.21105.joss.01954.pdf)

**Comment by kyleniemeyer** [comment]
Hi @kiretd, could you review the references and add the missing DOIs? (Including other references that whedon may have missed)

**Comment by kyleniemeyer** [comment]
Hi @dfm, could you edit this submission for us?

**Comment by dfm** [comment]
@kyleniemeyer sure!

**Comment by dfm** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by dfm** [comment]
@kiretd: as well as fixing the DOIs, please take a look at [this list of potential reviewers](https://bit.ly/joss-reviewers) and let me know if you see anyone who would be an especially good fit (don't @ them!). I'll start pinging reviewers in the next few days one way or another. Thanks!

**Comment by kiretd** [comment]
Hi @dfm and @kyleniemeyer, thanks for such a quick turnaround!
I've added the DOIs for all references. 
Going through the list of reviewers, here are some candidates that look like a really good fit to me:
desilinguist, rougier, sealhuang, krother, ahurriyetoglu, nirum, arokem, effigies, oesteban, jsgalan, tupi, mnarayan, tianxzhu, GalenStocking, ryEllison

**Comment by dfm** [comment]
:wave: Hey @mnarayan! Any chance you're available and willing to review this JOSS submission? Thanks!

**Comment by dfm** [comment]
:wave: Hey @effigies! Any chance you're available and willing to review this JOSS submission? Thanks!

**Comment by effigies** [comment]
Sure.

**Comment by mnarayan** [comment]
Sure

**Comment by dfm** [comment]
@whedon assign @effigies as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @effigies

**Comment by dfm** [comment]
@whedon add @mnarayan as reviewer

**Comment by whedon** [comment]
OK, @mnarayan is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1958. Feel free to close this issue now!

**Comment by dfm** [comment]
@effigies, @mnarayan: thanks! Please head over to #1958 to find the main review.
