### ISSUE TITLE
[PRE REVIEW]: Soss: Code Generation for Probabilistic Programming in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1955]
**Submitting author:** @cscherrer (<a href="http://orcid.org/0000-0002-1490-0304">Chad Scherrer</a>)
**Repository:** <a href="https://github.com/cscherrer/Soss.jl" target ="_blank">https://github.com/cscherrer/Soss.jl</a>
**Version:** v0.9.0
**Editor:** @melissawm
**Reviewers:** @kose-y, @malmaud

**Author instructions**

Thanks for submitting your paper to JOSS @cscherrer. **Currently, there isn't an JOSS editor assigned** to your paper.

@cscherrer if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1145/3314221.3314642 is OK
- 10.5281/zenodo.3541506 is OK
- 10.7717/peerj-cs.103 is OK
- 10.21105/joss.01143 is OK
- 10.5281/zenodo.2647458 is OK
- 10.1137/141000671 is OK
- 10.7717/peerj-cs.103 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01955/joss.01955/10.21105.joss.01955.pdf)

**Comment by kyleniemeyer** [comment]
Hi @melissawm, could you edit this submission?

**Comment by cscherrer** [comment]
Hi @kyleniemeyer , I just saw the "if you have any suggestions for potential reviewers...". both Matt Sottile and Dan Foreman-Mackey are familiar with this work (though neither are directly involved, so no conflict of interest). Outside existing JOSS reviewers, any contributor to [Turing.jl](https://github.com/TuringLang/Turing.jl) or [Gen](https://github.com/probcomp/Gen) could be a good fit.

**Comment by melissawm** [comment]
Hello @kyleniemeyer, yes I can. I'll assign myself

**Comment by melissawm** [comment]
@whedon assign @melissawm as editor

**Comment by whedon** [comment]
OK, the editor is @melissawm

**Comment by melissawm** [comment]
Hello @cscherrer , I'll be working as the editor, the reviewers are not yet assigned 😊

**Comment by cscherrer** [comment]
Great, thank you @melissawm !

**Comment by melissawm** [comment]
@cscherrer sorry for taking so long to respond, the holidays were a busy period for me. I know you indicated some names above, but I can't find them in the list of past JOSS reviewers. I'll try some people from our reviewers list first, if that's ok.

**Comment by melissawm** [comment]
@malmaud Hello, would you be willing/available to review this software paper for JOSS?

**Comment by melissawm** [comment]
@kose-y Hello, would you be willing/available to review this software paper for JOSS?

**Comment by kose-y** [comment]
Yes, I would like to review this paper.

**Comment by melissawm** [comment]
@whedon assign @kose-y as reviewer

**Comment by whedon** [comment]
OK, @kose-y is now a reviewer

**Comment by malmaud** [comment]
Yes, I can review.

**Comment by melissawm** [comment]
@whedon add @malmaud as reviewer

**Comment by whedon** [comment]
OK, @malmaud is now a reviewer

**Comment by melissawm** [comment]
Thank you both! I will now close this pre-review issue and you'll be redirected to a REVIEW issue where you'll be provided with a checklist for the review.

**Comment by melissawm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2062.
