### ISSUE TITLE
[REVIEW]: Pyglmnet: Python implementation of elastic-net regularized generalized linear models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1959]
**Submitting author:** @jasmainak (<a href="http://orcid.org/0000-0002-3199-9027">Mainak Jas</a>)
**Repository:** <a href="https://github.com/glm-tools/pyglmnet/" target ="_blank">https://github.com/glm-tools/pyglmnet/</a>
**Version:** 1.1.1
**Editor:** @arokem
**Reviewer:** @professoralkmin, @ryEllison
**Archive:** <a href="https://doi.org/10.5281/zenodo.3686564" target="_blank">10.5281/zenodo.3686564</a>

## Status

[![status](https://joss.theoj.org/papers/ab35613e0440e60465a6f71f36e1627d/status.svg)](https://joss.theoj.org/papers/ab35613e0440e60465a6f71f36e1627d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ab35613e0440e60465a6f71f36e1627d"><img src="https://joss.theoj.org/papers/ab35613e0440e60465a6f71f36e1627d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ab35613e0440e60465a6f71f36e1627d/status.svg)](https://joss.theoj.org/papers/ab35613e0440e60465a6f71f36e1627d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/glm-tools/pyglmnet/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@professoralkmin & @ryEllison, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/glm-tools/pyglmnet/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jasmainak) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/glm-tools/pyglmnet/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jasmainak) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @professoralkmin, @ryEllison it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1371/journal.pone.0196527 is OK
- 10.1162/neco_a_01150 is OK
- 10.1101/609826 is OK
- 10.1101/111450 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01959/joss.01959/10.21105.joss.01959.pdf)

**Comment by arokem** [comment]
Hi @professoralkmin and @ryEllison : have you had a chance to take a look?

**Comment by professoralkmin** [comment]
Hello @arokem. Yes, I read and tested everything. Now, I already finished and ticked all according to my work experience and academic technology life. Thanks. :)

**Comment by ryEllison** [comment]
I'm happy to see this paper published as is. I believe it's well written with adequate documentation and clearly expands on incomplete GLM packages in the machine learning domain.

I would like to point out that the example code in your README file does GLM estimation but doesn't give the person trying to install and use your package any sort of result. Nothing is printed to the terminal. No visualizations are created. Although, the objects holding this information are there and someone could certainly run a script with this code in it interactively using the `-i` flag and 'back-of-the-envelope' spit out some results - or I suppose, more prudently (haha), alter the code to output what you'd like to see - this shouldn't be the responsibility of the end-user, in my opinion, when trying to look at your documentation. 

Otherwise, great work! Congrats!

**Comment by arokem** [comment]
Sorry about the slowness here: @professoralkmin : I see that the several boxes are still not ticked in your section. Do you still have concerns with these requirements?

**Comment by professoralkmin** [comment]
@arokem I believe that it is necessary 1) to explain better about the example usage to be more clear how to use correctly the application and 2) to review of some sentences to be improve the quality of writing.

**Comment by arokem** [comment]
Hi @jasmainak: have you had a chance to address these comments? In particular, I tend to agree with @professoralkmin's comment that more detail is needed in the example usage. These include brief introductions that provide context, but there is not enough detail to understand the various steps taken and to understand the outputs. I'd suggest adding these details.

**Comment by jasmainak** [comment]
hi @arokem sorry I was waiting for you to pitch in, we'll address these comments at the earliest and update you here. Thanks a lot for the reviews and feedback @professoralkmin and @ryEllison !

**Comment by jasmainak** [comment]
Hi @arokem following the comments of @professoralkmin and @ryEllison, we have made the following improvements:

- reorganized the paper into sections to highlight the main contributions of the software. 
- added an example in the paper that shows how Pyglmnet can be used on the community crime dataset.
- updated the example in the README document to provide console output and visualizations to assist the first time user.

We believe these should address the main concerns raised by the reviewers. Thanks again for helping us improving the software and the paper

**Comment by professoralkmin** [comment]
Hello @jasmainak. I already read the new version of article. I believe that is very good now. Congrats! :)

**Comment by arokem** [comment]
@whedon  check references

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by arokem** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1371/journal.pone.0196527 is OK
- 10.1162/neco_a_01150 is OK
- 10.1101/609826 is OK
- 10.1101/111450 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01959/joss.01959/10.21105.joss.01959.pdf)

**Comment by arokem** [comment]
@jasmainak : one small question/suggestion. The paper emphasizes compatibility with scikit learn. Are the estimators implemented in the package tested with sklearn's `check_estimator` (see: https://scikit-learn.org/stable/developers/develop.html#rolling-your-own-estimator)? That would guarantee compatibility with other sklearn features. I couldn't find that in the software tests.

**Comment by jasmainak** [comment]
They weren't but now we added this test thanks to @titipata in https://github.com/glm-tools/pyglmnet/pull/364. We were indirectly testing this in many ways but I agree `check_estimator` is the best way to guarantee compatibility. Thanks a lot for the suggestion!

**Comment by arokem** [comment]
Awesome! I think that the paper is ready for a final review by the EICs. Before we go ahead, could you please: 

- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g. figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by jasmainak** [comment]
@arokem here you go!

- the version tag of the [archived release on github](https://github.com/glm-tools/pyglmnet/releases/tag/1.1.1) is 1.1.1
- doi of the archived version on zenodo is: 10.5281/zenodo.3686564
- the author list and title of the deposit matches the author list and title on the paper

**Comment by titipata** [comment]
@arokem just to poke here to see if this is ready for the final review by the EICs. Thank you so much!

**Comment by arokem** [comment]
Whoops. Thanks for poking! Too many GitHub notifications 😅

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.3686564 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3686564" target="_blank">10.5281/zenodo.3686564</a> is the archive.

**Comment by arokem** [comment]
@whedon set 1.1.1 as version

**Comment by whedon** [comment]
OK. 1.1.1 is the version.

**Comment by arokem** [comment]
@openjournals/joss-eics : I believe that this is ready for your review

**Comment by titipata** [comment]
@arokem no problem and thank you so much again!

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1371/journal.pone.0196527 is OK
- 10.1162/neco_a_01150 is OK
- 10.1101/609826 is OK
- 10.1101/111450 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published

. Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1345

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1345, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1234263060954669057) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1346
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01959](https://doi.org/10.21105/joss.01959)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @jasmainak, your JOSS paper is published! 🚀 

Big thanks to our editor: @arokem, and the reviewers: @professoralkmin, @ryEllison — we couldn't do this without you 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01959/status.svg)](https://doi.org/10.21105/joss.01959)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01959">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01959/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01959/status.svg
   :target: https://doi.org/10.21105/joss.01959
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01959/status.svg)](https://doi.org/10.21105/joss.01959)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by jasmainak** [comment]
Thanks a lot @labarba @arokem and the reviewers @professoralkmin and @ryEllison !
