### ISSUE TITLE
[PRE REVIEW]: AskCI Server: Collaborative and version controlled documentation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1961]
**Submitting author:** @vsoch (<a href="http://orcid.org/0000-0002-4387-3819">Vanessa Sochat</a>)
**Repository:** <a href="https://github.com/vsoch/askci" target ="_blank">https://github.com/vsoch/askci</a>
**Version:** 0.0.1
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @vsoch. **Currently, there isn't an JOSS editor assigned** to your paper.

@vsoch if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1007/978-1-4842-3936-0_6 may be missing for title: Docker Compose

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01961/joss.01961/10.21105.joss.01961.pdf)

**Comment by vsoch** [comment]
Based on language familiarity (Python) and specialty, I will suggest @atrisovic, @fabianomenegidio, and @dvanic.

**Comment by vsoch** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01961/joss.01961/10.21105.joss.01961.pdf)

**Comment by kyleniemeyer** [comment]
Hi @vsoch, thanks for your (continued!) interest in JOSS—unfortunately, the editorial board found that this submission falls outside our scope of research software, though it does look useful in general.

**Comment by vsoch** [comment]
Can the board share their rationale? Documentation is central to absolutely everything - in the same way that containers are a "meta" topic but not research in and of themselves (and I've done a lot of work for containers on JoSS) this is software that is really important for the community to work together to document software, technology, etc. As a research software engineer that makes these meta tools for researchers - this is exactly research software, and JoSS has historically been the only place that is interested because I'm not answering a research question, but empowering researchers. It seems like the criteria are that the software must be for a specific research domain, which seems off. If you've published simple [user interfaces](https://joss.theoj.org/papers/10.21105/joss.01411) to tools, a [PDF renderer](https://joss.theoj.org/papers/10.21105/joss.01453), or [something to render docs for machine learning models](https://joss.theoj.org/papers/10.21105/joss.01444), or a [literature parsing API](https://joss.theoj.org/papers/10.21105/joss.01674) this is really no different, the knowledge just comes from people, and it's the whole package - web interface, GitHub integration, and APIs :/

**Comment by kyleniemeyer** [comment]
@vsoch thanks for your input. One of our rules of thumb about software being in scope is whether someone might cite it, and if so who. Can you give any thoughts on that?

**Comment by vsoch** [comment]
Sure thing! In that it's a knowledge base for however the implementer desires it (and comes with an API) there are several examples I can think of:

 - a researcher uses the API to parse the provided knowledge, and does an analysis with it (e.g., an AskCI Server branded as a software metadata repository getting updates from the software repositories could say something about software development in the domain).
 - a researcher / rse deploys an AskCI server to serve as a knowledge database for others, and creates a supporting tool to (also use the API) to update content and derive some kind of interesting metrics.
 - The AskCI Server is used for some educational purpose, and the different articles become classes / semesters or topics. An interested researcher looks at change in the course content over time.
 - The AskCI Server is used to describe machine learning models. Someone does a text analysis to compare similarity of models, or parses references to create a citation graph.

In that it serves as a programmatic way to organize and then access information, and is linked with GitHub, it's really optimized for helping researchers. I'm not great at asking interested questions (hence why I'm not a researcher) but even I can think of the general examples above.

**Comment by kyleniemeyer** [comment]
Hi @vsoch, thanks for your patience for our response. I brought your response back to the editorial board for some more discussion, and then I was on break. Unfortunately, the consensus is still that this submission falls outside our scope of research software (using our definition). We don't question that it looks useful for researchers, but fundamentally it doesn't appear to be a tool that would be directly used for scholarly research and likely to be cited as part of the research process.
