### ISSUE TITLE
[PRE REVIEW]: LiberTEM: Software platform for scalable multidimensional data processing in transmission electron microscopy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1962]
**Submitting author:** @uellue (<a href="http://orcid.org/0000-0001-6635-9567">Dieter Weber</a>)
**Repository:** <a href="https://github.com/LiberTEM/LiberTEM" target ="_blank">https://github.com/LiberTEM/LiberTEM</a>
**Version:** v0.3.0
**Editor:** @majensen
**Reviewers:** @alvarolopez, @mamcdona77

**Author instructions**

Thanks for submitting your paper to JOSS @uellue. **Currently, there isn't an JOSS editor assigned** to your paper.

@uellue if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.2450624 is OK
- 10.1145/1327452.1327492 is OK
- 10.1109/nuicone.2012.6493198 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1145/2934664 is OK
- 10.25080/majora-7b98e3ed-013 is OK
- 10.5281/ZENODO.3396791 is OK
- 10.5281/ZENODO.2649351 is OK
- 10.5281/ZENODO.1477847 is OK
- 10.1017/s1431927619000497 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1142/11389 is INVALID
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01962/joss.01962/10.21105.joss.01962.pdf)

**Comment by uellue** [comment]
> INVALID DOIs
> 
> - 10.1142/11389 is INVALID

Hi, the invalid DOI is of a book that is in print and I am referring to a chapter that I co-authored: https://www.worldscientific.com/worldscibooks/10.1142/11389

How should we deal with this? The publication date of the book was pushed recently from Jan 2020 to March 2020, by the way.

**Comment by uellue** [comment]
Potential reviewers, selected from the list by programming language and interests:

* leonardojaneis
* glatard
* alvarolopez
* dghoshal-lbl
* stsievert
* sonal-raj

  | 7 von 14
-- | --

**Comment by uellue** [comment]
> [ point_right Check article proof page_facing_up point_left ](https://github.com/openjournals/joss-papers/blob/joss.01962/joss.01962/10.21105.joss.01962.pdf)

The proof looks good!

**Comment by labarba** [comment]
> Hi, the invalid DOI is of a book that is in print and I am referring to a chapter that I co-authored: https://www.worldscientific.com/worldscibooks/10.1142/11389
> How should we deal with this? The publication date of the book was pushed recently from Jan 2020 to March 2020, by the way.

Our bot's suggestions on DOIs are best-effort. Do what you think is best!

**Comment by labarba** [comment]
... one more thing: is there any chance you could deposit your chapter on a pre-print server?

**Comment by labarba** [comment]
👋  @majensen — could you handle this submission as editor? I cannot identify any editor in the general domain of this software, but it is aimed at processing large-scale binary data sets, which I think is in scope for you?

**Comment by labarba** [comment]
@uellue : in the paper, you have several points where you say that something is in the docs, and embed a long URL to the position in the docs. This looks rather ugly, and it's unnecessary. Can you clean that up a bit? You can have just one link to the docs, and so shorten that section of the text quite a bit by just describing briefly: "here are our docs, and they contain this, that, and more."

**Comment by uellue** [comment]
> ... one more thing: is there any chance you could deposit your chapter on a pre-print server?

That's a good point! I'll contact the publisher if they would be fine with that.

**Comment by uellue** [comment]
> @uellue : (...) You can have just one link to the docs, and so shorten that section of the text quite a bit by just describing briefly: "here are our docs, and they contain this, that, and more."

Will do, thx for the feedback! :-)

**Comment by uellue** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01962/joss.01962/10.21105.joss.01962.pdf)

**Comment by uellue** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by majensen** [comment]
@whedon assign @majensen as reviewer

**Comment by majensen** [comment]
@whedon assign @majensen as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by majensen** [comment]
Hello @dghoshal-lbl - would you be willing to review [this submission](https://github.com/openjournals/joss-papers/blob/joss.01962/joss.01962/10.21105.joss.01962.pdf) to [JOSS](https://joss.theoj.org)? Thanks for your consideration! --@majensen

**Comment by majensen** [comment]
Hey @cr458 - would you be able to review [this submission](https://github.com/openjournals/joss-papers/blob/joss.01962/joss.01962/10.21105.joss.01962.pdf) to [JOSS](https://joss.theoj.org)? Thanks for considering! --@majensen

**Comment by majensen** [comment]
@uellue - just a heads-up, I won't be working too much until the new year, but I haven't forgotten your submission! Should see more action here then-- thanks for your patience! --@majensen

**Comment by majensen** [comment]
@alvarolopez - feliz año nuevo! Would you be willing to review [this paper](#1962) for [JOSS](https://joss.theoj.org)? Information on reviewing can be found [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). 
Thanks for your consideration! --@majensen

**Comment by alvarolopez** [comment]
@majensen sure, count on me.

Cheers.

**Comment by majensen** [comment]
@whedon assign @alvarolopez as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @alvarolopez

**Comment by uellue** [comment]
> @uellue - just a heads-up, I won't be working too much until the new year, but I haven't forgotten your submission! Should see more action here then-- thanks for your patience! --@majensen

@majensen No worries, I was on vacation myself and already expected that most people are on holidays. Happy new year! :-)

**Comment by uellue** [comment]
> > ... one more thing: is there any chance you could deposit your chapter on a pre-print server?
> 
> That's a good point! I'll contact the publisher if they would be fine with that.

Unfortunately, the wouldn't be happy about it.

**Comment by majensen** [comment]
Thanks to @mamcdona77 for agreeing to review! He is a TEM and imaging processing expert at NCI.

**Comment by majensen** [comment]
@whedon add @mamcdona77 as reviewer

**Comment by whedon** [comment]
OK, @mamcdona77 is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2006. Feel free to close this issue now!

**Comment by majensen** [comment]
All please join the review at #2006 -- closing the pre-review issue out now.
