### ISSUE TITLE
[PRE REVIEW]: MTEX2Gmsh: a tool for generating 2D meshes from EBSD data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1963]
**Submitting author:** @DorianDepriester (<a href="http://orcid.org/0000-0002-2881-8942">Dorian Depriester</a>)
**Repository:** <a href="https://github.com/DorianDepriester/mtex2Gmsh" target ="_blank">https://github.com/DorianDepriester/mtex2Gmsh</a>
**Version:** v1.0
**Editor:** @meg-simula
**Reviewers:** streeve, @ralfHielscher

**Author instructions**

Thanks for submitting your paper to JOSS @DorianDepriester. **Currently, there isn't an JOSS editor assigned** to your paper.

@DorianDepriester if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @Kevin-Mattheus-Moerman - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1088/0965-0393/24/5/055014 is OK
- 10.1016/j.actamat.2016.02.001 is OK
- 10.1016/0956-7151(94)90452-9 is OK
- 10.1364/AO.41.006815 is OK
- 10.1016/j.actamat.2016.10.030 is OK
- 10.1002/nme.2579 is OK
- 10.1016/j.ultramic.2011.08.002 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01963/joss.01963/10.21105.joss.01963.pdf)

**Comment by DorianDepriester** [comment]
Dear all,
As potential reviewers, I suggest:

- streeve
- IgorBaratta
- ralfHielscher (not in the list of JOSS' reviewers)
- lheagy
- WalBytes

Regards.

**Comment by DorianDepriester** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by labarba** [comment]
👋 @meg-simula — Could you handle this submission as editor?
The author suggested @Kevin-Mattheus-Moerman, but he is handling 5 papers right now.
Check out the [article proof.](https://github.com/openjournals/joss-papers/blob/joss.01963/joss.01963/10.21105.joss.01963.pdf)

**Comment by meg-simula** [comment]
I would be happy to, but I am out of office until Mon Jan 6 2020. If it can
wait until then, feel free to assign me.

**Comment by labarba** [comment]
Thanks, @meg-simula ! Yes, all editor assignments this week are carrying this caveat 😁

**Comment by labarba** [comment]
@whedon assign @meg-simula as editor

**Comment by whedon** [comment]
OK, the editor is @meg-simula

**Comment by Kevin-Mattheus-Moerman** [comment]
The reviewers/authors from these submissions might be interested in reviewing:
https://github.com/openjournals/joss-reviews/issues/1173 
https://github.com/openjournals/joss-reviews/issues/1636
https://github.com/openjournals/joss-reviews/issues/1370
https://github.com/openjournals/joss-reviews/issues/1450

**Comment by meg-simula** [comment]
Hi @DorianDepriester, thank you for the submission! This looks nicely in scope for JOSS. 

@lheagy @streeve @ralfHielscher Would you be willing and available to review this submission?

**Comment by streeve** [comment]
Yes, I'm happy to - this will be my first JOSS review :)

**Comment by meg-simula** [comment]
Fantastic @streeve, thanks!

**Comment by meg-simula** [comment]
@whedon assign streeve as reviewer

**Comment by whedon** [comment]
OK, streeve is now a reviewer

**Comment by ralfHielscher** [comment]
Hi Marie,

I also agree to review. What are the next steps?

Ralf.

********************************************************************
Ralf Hielscher                   Tel: +371-531-38556
Fakultät für Mathematik               +371-531-22200 (Sekr.)
Technische Universität Chemnitz  Fax: +371-531-22109
Reichenhainer Str. 39            E-mail:
ralf.hielscher@mathematik.tu-chemnitz.de
D-09126 Chemnitz                 http://www.tu-chemnitz.de/~rahi
********************************************************************

**Comment by danielskatz** [comment]
👋 @meg-simula - it looks like you have another reviewer ready to go, and can start the review

**Comment by meg-simula** [comment]
Fantastic, thanks @ralfHielscher, I'll assign you and get the review started.

**Comment by meg-simula** [comment]
whedon add @ralfHielscher as reviewer

**Comment by meg-simula** [comment]
@whedon add @ralfHielscher as reviewer

**Comment by whedon** [comment]
OK, @ralfHielscher is now a reviewer

**Comment by meg-simula** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2094.
