### ISSUE TITLE
[PRE REVIEW]: Discovering new packages and their connections with packexplorer

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1964]
**Submitting author:** @arielolafsalgado (<a href="http://orcid.org/0000-0001-7701-5372">Ariel Salgado</a>)
**Repository:** <a href="https://github.com/arielolafsalgado/packexplorer" target ="_blank">https://github.com/arielolafsalgado/packexplorer</a>
**Version:** 0.0.0.9000
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @arielolafsalgado. **Currently, there isn't an JOSS editor assigned** to your paper.

@arielolafsalgado if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.17713/ajs.v41i1.188 may be missing for title: Are there too many R packages?

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01964/joss.01964/10.21105.joss.01964.pdf)

**Comment by arielolafsalgado** [comment]
vbaliga
terrytangyuan
strengejacke
Stat-Cook
shivam11
sctyner
monicagerber
milesmcbain
Medewitt
MatthewSmith430
masalmon
markziemann
kellieotto

**Comment by arielolafsalgado** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by labarba** [comment]
Hello, @arielolafsalgado — After a pre-review of your submission, and an assessment by the editorial board at large (offline), we find that it does not meet our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). In particular, while the software seems useful, it falls under the 'Minor utility' category, and we therefore decided not to put it through review. 

Thank you for considering JOSS as a venue for your software, and I hope you'll submit other software with research application in the future.
