### ISSUE TITLE
[PRE REVIEW]: Oceananigans.jl: Fast and friendly geophysical fluid dynamics on GPUs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1965]
**Submitting author:** @ali-ramadhan (<a href="http://orcid.org/0000-0003-1102-1520">Ali Ramadhan</a>)
**Repository:** <a href="https://github.com/climate-machine/Oceananigans.jl" target ="_blank">https://github.com/climate-machine/Oceananigans.jl</a>
**Version:** v0.18.0
**Editor:** @kthyng
**Reviewers:** @funsim, @ysimillides

**Author instructions**

Thanks for submitting your paper to JOSS @ali-ramadhan. **Currently, there isn't an JOSS editor assigned** to your paper.

@ali-ramadhan if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @kthyng - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
PDF failed to compile for issue #1965 with the following error: 

 Can't find any papers to compile :-(

**Comment by ali-ramadhan** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by ali-ramadhan** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01965/joss.01965/10.21105.joss.01965.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1029/96JC02775 is OK
- 10/f9wkpj is OK
- 10.1109/TPDS.2018.2872064 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.5670/oceanog.2016.66 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@kthyng — We're hoping you can handle this submission. I will follow up with an email now.

**Comment by labarba** [comment]
@ali-ramadhan — As you can expect, a lot of our editors and reviewers are on holiday these days. I hereby request your patience, as the closest editor to the domain of your submission is unavailable until January 7th.

**Comment by ali-ramadhan** [comment]
Hi @labarba thank you for checking in!

Of course that's totally expected. Just wanted to submit this before the holidays. Resuming in January sounds good!

**Comment by kthyng** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
I'm happy to be editor, though I would appreciate waiting on this until January as already mentioned. It'll be hard to get reviewers now too. I'll set a reminder

**Comment by kthyng** [comment]
@whedon remind @kthyng in 18 days

**Comment by whedon** [comment]
Sorry, I can't set reminders on PRE-REVIEW issues.

**Comment by kthyng** [comment]
Oh yeah, I think this is an active issue. Ok well I will just be back in a few weeks. Happy holidays!!

**Comment by ali-ramadhan** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01965/joss.01965/10.21105.joss.01965.pdf)

**Comment by ali-ramadhan** [comment]
@kthyng Thank you for agreeing to review our submission as editor!

It seems that our submission was already assigned a DOI (`10.21105/joss.01965`) so I was curious whether it would be safe to use the following citation in another manuscript that wishes to cite this JOSS submission, or if you would refrain from any citations during the review process.

```
@article{OceananigansJOSS,
  title     = {Oceananigans.jl: {Fast} and friendly geophysical fluid dynamics on GPUs},
  author    = {Ali Ramadhan and Gregory LeClaire Wagner and Chris Hill and Jean-Michel Campin and Valentin Churavy and Tim Besard and Andre Souza and Alan Edelman and John Marshall and Raffaele Ferrari},
  journal   = {The Journal of Open Source Software},
  publisher = {The Open Journal},
  volume    = {4},
  number    = {44},
  pages     = {1965},
  year      = {2020},
  doi       = {10.21105/joss.01965},
  url       = {https://doi.org/10.21105/joss.01965},
  note      = {Under review.}
}
```

**Comment by kthyng** [comment]
@openjournals/joss-eics Is it ok to start using the joss-assigned DOI for an incoming submission while it is under review? (pre-review currently actually)

**Comment by kthyng** [comment]
@funsim and @rsignell-usgs Are you interested and willing to review this submission to the Journal for Open Source Software? We ask for reviews within about 3 weeks, and you can learn more about the review process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by danielskatz** [comment]
> Is it ok to start using the joss-assigned DOI for an incoming submission while it is under review? (pre-review currently actually)

It's not really up to us. Using it is possible, but it won't resolve until the submission is accepted, so it will look odd to anyone trying it. I personally would instead call this an "under review" submission and not use the URL until it is accepted.

**Comment by ali-ramadhan** [comment]
Thank you for the clarification @danielskatz, we'll do that.

**Comment by kthyng** [comment]
Note that I have pinged possible reviewers by email.

**Comment by kthyng** [comment]
@funsim has agreed to review!

**Comment by kthyng** [comment]
@whedon assign @funsim as reviewer

**Comment by whedon** [comment]
OK, @funsim is now a reviewer

**Comment by kthyng** [comment]
@ysimillides Are you willing to review this JOSS submission? I would hope that you review it with your expertise in Julia and numerical methods. I would hope for the review within about 3 weeks.

**Comment by ysimillides** [comment]
Hello,

Yes that should be perfectly fine.

**Comment by kthyng** [comment]
Excellent!

**Comment by kthyng** [comment]
@whedon add @ysimillides as reviewer

**Comment by whedon** [comment]
OK, @ysimillides is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2018. Feel free to close this issue now!

**Comment by kthyng** [comment]
@funsim and @ysimillides Head over to the review issue [#2018](https://github.com/openjournals/joss-reviews/issues/2018) for the actual review process. Let me know if you have any questions!
