### ISSUE TITLE
[PRE REVIEW]: MFDFA: Multifractal Detrended Fluctuation Analysis in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1966]
**Submitting author:** @LRydin (<a href="http://orcid.org/0000-0001-5513-0580">Leonardo Rydin Gorjão</a>)
**Repository:** <a href="https://github.com/LRydin/MFDFA" target ="_blank">https://github.com/LRydin/MFDFA</a>
**Version:** 0.2
**Editor:** @dfm
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @LRydin. **Currently, there isn't an JOSS editor assigned** to your paper.

@LRydin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/S0378-4371(02)01383-3 is OK
- 10.3389/fphys.2012.00141 is OK
- 10.1103/PhysRevE.49.1685 is OK
- 10.1103/PhysRevE.64.011114 is OK
- 10.1103/PhysRevA.44.2730 is OK
- 10.1088/1742-5468/2006/02/p02003 is OK
- 10.1007/s00382-019-04965-0 is OK
- 10.1038/20924 is OK
- 10.2478/s11534-009-0058-0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01966/joss.01966/10.21105.joss.01966.pdf)

**Comment by labarba** [comment]
👋 @dfm — I believe this submission is one you could handle as editor? Have look please. We understand of course that these days will be slow and you might be on holiday. Let us know, and we can assign you for handling this after the New Year.

**Comment by dfm** [comment]
@labarba: sounds good. I'm happy to edit this in the new year!

**Comment by labarba** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by dfm** [comment]
@LRydin: After a pre-review of your submission, and an assessment by the editorial board at large, we find that it does not meet [our submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). In particular, while the software seems useful, it falls under the 'Minor utility' category, and we therefore decided not to put it through review.

Thank you for considering JOSS as a venue for your software, and I hope you'll submit other software with research application in the future.

**Comment by LRydin** [comment]
Dear @dfm. Thank you for the reply. Althought this might seem uncommon, I hope you can take the following under consideration:
Althought the python package might seem "thin", the applicability of MFDFA is extensive. I refer here mainly to the work of Espen Ihlen, [Introduction to multifractal detrended fluctuation analysis in Matlab](https://doi.org/10.3389/fphys.2012.00141), which has gained a lot of attention over these last 7 years (over 400 citations). This paper explains extensively the use of DFA and MFDFA. The introduction to MFDFA is briliant, but the matlab code is not flexible.
Secondly I point out that this method is not a minor utility. Take for example the recent publication [A simple decomposition of European temperature variability capturing the variance from days to a decade](https://doi.org/10.1007/s00382-019-04965-0), which is entirelly based on applying MFDFA to temperature data. This to point out that MFDFA is not a minor utility, but a extensive method with applications in various fields. There are entire publications (see paper) based solely on DFA analysis of data, such as Earth-quake time distributions, heart-rate variability...

It is not my intension in this paper to present an introduction (the paper by Espen Ihlhen and the original paper by Kandelhardt do so), but to write an efficient python code, accessible across fields of study. Please take this into consideration when evaluating this package as a "minor utility".

I hope you can take this into consideration in re-evaluating my submission. I am submitting this package to JOSS to obtain a thorought analysis of the code itself, which admittedly could see some improvement.

Best regards,
Leonardo Rydin

**Comment by dfm** [comment]
@LRydin: The editorial board has reconsidered and we stand by our initial assessment. The classification of "minor utility" is not a statement about whether or not a piece of software is useful. Instead, we're assessing on the scope of the library (in this case, a single method of <50 lines of code, based on an existing implementation in MATLAB) and whether or not that justifies a JOSS publication.

Speaking for myself, I do believe that this software seems useful and I recommend asking that users cite the Zenodo DOI so that you can track its usage. You could also contribute the method as a pull request to an existing library ([statsmodels](https://github.com/statsmodels/statsmodels), for example) to receive a code review and broaden the accessibility of this work.

Thanks again for considering JOSS!
