### ISSUE TITLE
[PRE REVIEW]: genius: analysis ready song lyric retrieval

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1967]
**Submitting author:** @josiahparry (<a href="http://orcid.org/0000-0001-9910-865X">Josiah Parry</a>)
**Repository:** <a href="https://github.com/josiahparry/genius" target ="_blank">https://github.com/josiahparry/genius</a>
**Version:** 2.2.1
**Editor:** @danielskatz
**Reviewers:** @bmcfee, @heraldoborges

**Author instructions**

Thanks for submitting your paper to JOSS @josiahparry. **Currently, there isn't an JOSS editor assigned** to your paper.

@josiahparry if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1007/978-3-642-11674-2_15 is OK

MISSING DOIs

- https://doi.org/10.1080/02699931.2019.1700482 may be missing for title: Development of emotion recognition in popular music and vocal bursts
- https://doi.org/10.1525/jpms.2018.300411 may be missing for title: Quantitative Sentiment Analysis of Lyrics in Popular Music
- https://doi.org/10.21105/joss.00037 may be missing for title: tidytext: Text Mining and Analysis Using Tidy Data Principles in R.
- https://doi.org/10.18637/jss.v059.i10 may be missing for title: Tidy data

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01967/joss.01967/10.21105.joss.01967.pdf)

**Comment by JosiahParry** [comment]
I'll get to adding the missing DOIs.

Potential Reviewers:
@alexhanna: R user + NLP
@Faroit: is a pyton user but seems to do work in MIR

**Comment by JosiahParry** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01967/joss.01967/10.21105.joss.01967.pdf)

**Comment by alexhanna** [comment]
Hi! I don't have the bandwidth for this right now. Looks like a cool project, though.

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@JosiahParry - due to the holidays, this will likely take a little time to get reviewers assigned. Do you have additional suggestions for reviewers, perhaps based on people who have written other software in this field, with GitHub handles (but please don't tag them with @'s, since we don't want to add lots of people to the notifications of this thread) or email addresses or even just names?

**Comment by faroit** [comment]
@danielskatz @JosiahParry I could do it but I am no expert on R software and also I work mainly with audio whereas this contribution is more focussed on text metadata if I'm not mistaken.

**Comment by danielskatz** [comment]
Thanks @faroit - let me see if I can find some reviewers with closer expertise

**Comment by faroit** [comment]
Maybe consider @bmcfee he's also a python head but has significantly more experience with core MIR

**Comment by danielskatz** [comment]
👋 @bmcfee - would you be interested in reviewing this submission for JOSS?

**Comment by bmcfee** [comment]
Sure @danielskatz , thanks for the invitation!  I'm not too much of an R user, so it might not be a bad idea to get an R person to chime in as well.

**Comment by danielskatz** [comment]
Thanks - I'll add you to the system and continue to look for another reviewer before we start the review

**Comment by danielskatz** [comment]
@whedon add @bmcfee as reviewer

**Comment by whedon** [comment]
OK, @bmcfee is now a reviewer

**Comment by JosiahParry** [comment]
Thank you @danielskatz for figuring this all out! And thank you @bmcfee for being willing to review it :) It is very much appreciated.

**Comment by danielskatz** [comment]
Now after the holidays, I've tweeted about finding another reviewer - https://twitter.com/danielskatz/status/1214185648279572481

**Comment by faroit** [comment]
One more suggestions: I know @heraldoborges who is an active R user and a researcher in Machine Learning/Information Retrieval.

**Comment by danielskatz** [comment]
👋 @heraldoborges - would you be willing to review this for JOSS?  (If you haven't reviewed for JOSS before, please see our [intro to reviewing](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) and [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html))

**Comment by heraldoborges** [comment]
Yes.

Em seg, 6 de jan de 2020 3:25 PM, Daniel S. Katz <notifications@github.com>
escreveu:

**Comment by danielskatz** [comment]
@whedon add @heraldoborges as reviewer

**Comment by whedon** [comment]
OK, @heraldoborges is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1995. Feel free to close this issue now!
