### ISSUE TITLE
[PRE REVIEW]: Carculator: prospective environmental and economic life cycle assessment of vehicles

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1968]
**Submitting author:** @romainsacchi (<a href="http://orcid.org/0000-0003-1440-0905">Romain Sacchi</a>)
**Repository:** <a href="https://github.com/romainsacchi/carculator/" target ="_blank">https://github.com/romainsacchi/carculator/</a>
**Version:** 0.0.5
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @romainsacchi. **Currently, there isn't an JOSS editor assigned** to your paper.

@romainsacchi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1136/bmj.332.7550.1107 is OK
- 10.2788/318544 is OK
- 10.1016/j.apenergy.2015.01.019 is OK
- 10.2147/eect.s60408 is OK
- 10.1021/acs.est.8b00261 is OK
- 10.21105/joss.00236 is OK

MISSING DOIs

- https://doi.org/10.1007/s11367-016-1087-8 may be missing for title: The ecoinvent database version 3 (part I): overview and methodology.

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01968/joss.01968/10.21105.joss.01968.pdf)

**Comment by romainsacchi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01968/joss.01968/10.21105.joss.01968.pdf)

**Comment by romainsacchi** [comment]
konstantinstadler may be a potential reviewer for this paper.

**Comment by romainsacchi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1968 with the following error: 

 Error reading bibliography ./paper.bib (line 99, column 5):
unexpected "{"
expecting letter, digit, white space or "="
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by romainsacchi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01968/joss.01968/10.21105.joss.01968.pdf)

**Comment by arfon** [comment]
:wave: @romainsacchi, my apologies it has taken so very long to respond to this submission. Your paper was lost in the handover between editors over the holiday season and in conducting a review of our backlog this morning I noticed there hadn't been any activity on your paper.

I noticed that you have now marked the paper as 'withdrawn' on the JOSS site. Is this what you would like to happen at this stage? If not I can go ahead and assign a handling editor and we can start looking for reviewers.

Again, my sincere apologies for the delay thus far.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._
