### ISSUE TITLE
[PRE REVIEW]: `learningCurve`: An implementation of Crawford's and Wright's learning curve production functions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#197]
**Submitting author:** @bradleyboehmke (<a href="http://orcid.org/0000-0002-3611-8516">Bradley Boehmke</a>)
**Repository:** <a href="https://github.com/Auburngrads/learningCurve" target ="_blank">https://github.com/Auburngrads/learningCurve</a>
**Version:** v1.1.1
**Editor:** @arfon
**Reviewer:** @TJBihl

**What this issue is for**

Thanks for submitting your paper to JOSS @bradleyboehmke. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by bradleyboehmke** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by bradleyboehmke** [comment]
@arfon , not sure if you'll be the editor on this submission but I know last time you had asked for potential reviewers that were familiar with the mathematical/statistical area that our R package focused on.  For this submission, [Trevor Bihl](https://github.com/TJBihl) (trevor.bihl@gmail.com) would be a good candidate for review.

**Comment by arfon** [comment]
:wave: @TJBihl - would you be willing to review this submission for JOSS? You can read more about what that involves here: http://joss.theoj.org/about#reviewer_guidelines

**Comment by TJBihl** [comment]
Yes, I am up for reviewing it.

**Comment by arfon** [comment]
> Yes, I am up for reviewing it.

Wonderful, thanks!

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @TJBihl as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @TJBihl

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/202. Feel free to close this issue now!

**Comment by arfon** [comment]
@TJBihl - please carry out the review over in #202.
