### ISSUE TITLE
[REVIEW]: MOAFS: A Massive Online Analysis library for featureselection in data streams

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1970]
**Submitting author:** @mbdemoraes (<a href="http://orcid.org/0000-0002-9485-0334">Matheus Bernardelli de Moraes</a>)
**Repository:** <a href="https://github.com/mbdemoraes/moafs" target ="_blank">https://github.com/mbdemoraes/moafs</a>
**Version:** v1.1.0
**Editor:** @VivianePons
**Reviewers:** @sptennak, @DARSakthi
**Archive:** <a href="https://doi.org/10.6084/m9.figshare.11663307.v2" target="_blank">10.6084/m9.figshare.11663307.v2</a>

## Status

[![status](https://joss.theoj.org/papers/dabb12f9ea8865a8a9f320c3b6f20f99/status.svg)](https://joss.theoj.org/papers/dabb12f9ea8865a8a9f320c3b6f20f99)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/dabb12f9ea8865a8a9f320c3b6f20f99"><img src="https://joss.theoj.org/papers/dabb12f9ea8865a8a9f320c3b6f20f99/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/dabb12f9ea8865a8a9f320c3b6f20f99/status.svg)](https://joss.theoj.org/papers/dabb12f9ea8865a8a9f320c3b6f20f99)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mbdemoraes/moafs" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sptennak, @DARSakthi, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @VivianePons know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mbdemoraes/moafs">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mbdemoraes) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mbdemoraes/moafs">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mbdemoraes) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @sptennak it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.neucom.2017.01.078 is OK
- 10.1007/978-1-4612-4380-9_2 is OK
- 10.1145/1150402.1150466 is OK
- 10.1109/TKDE.2013.32 is OK
- 10.1023/A:1022643204877 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01970/joss.01970/10.21105.joss.01970.pdf)

**Comment by arfon** [comment]
@VivianePons - I just posted [a tweet](https://twitter.com/JOSS_TheOJ/status/1207837236454215682) on the JOSS account to see if we can find a second reviewer for this. I think we should have a second reviewer if at all possible.

**Comment by labarba** [comment]
Hi all — I'm the EiC on rotation this week. 
@sptennak — please go ahead with your review and post any questions here.
@VivianePons — we moved to a model of requiring two reviews a while back. Let us know if you need help adding a second reviewer here (it requires manually adding their checklist, after running `@wheddon add @user as reviewer`.

**Comment by DARSakthi** [comment]
If you are still looking to grab a second reviewer I would be interested in looking at this paper

**Comment by labarba** [comment]
Thank you for the offer, Dalton! I see you have already reviewed for us. I'll go ahead ad add you, and start the review.

**Comment by labarba** [comment]
@whedon add @DARSakthi as reviewer

**Comment by whedon** [comment]
OK, @DARSakthi is now a reviewer

**Comment by sptennak** [comment]
I started reviewing the paper.  At this point, I could locate the repository, install the software and run the GUI. The software installed and GUI loads as specified in the documentation. Good work from the authors!  However, I see some room for improvements there. I greatly appreciate if the author can provide some details on using the software to allow me testing the functionality.

I also suggest authors to 
[1] add some illustrations/text content to the paper describing the concepts and design of the software in very high level. That will help the reader to better understand the software.
[2] provide some instructions (or link) in the documentation on how to install MOA. The link appear on README.md in github, but not in the documentation. 
[3] provide some sample output/results for the examples mentioned in the documentation. 
[4] provide details on components to GUI and how a user can navigate through GUI using different examples.
[5] provide sample arffFile to test the example in the documentation.

Thanks

**Comment by mbdemoraes** [comment]
@sptennak thank you very much for your suggestions! I'm going to provide the details. I’ll let you know as soon as I've finished.

**Comment by VivianePons** [comment]
Thank you @DARSakthi for accepting the review and @sptennak for your suggestions! I am happy to see things are moving on.
I have been kept busy by the holiday season and hadn't had time to check in in the past two weeks. Thank you @labarba for adding the second reviewer and letting me know about the policy, this makes perfect sense.

**Comment by mbdemoraes** [comment]
@sptennak I added all your suggestions. Can you please verify it? Concerning how to test the software, I included a section in both readme and documentation about it. As you'll see, it is rather simple, just download a dataset in arff format which you want to experiment, run MOA with MOAFS and set the parameters accordingly to what you desire. Then run it. I think it will be easier now that I've included examples using GUI for each method.  Please verify if it is clear and easy to understand now. If not, let me know.

@VivianePons just a question: I've made changes in the paper, so I think it needs to be generated again. It's me, you or the reviewers who run the "whedon generate pdf" command?

Thank you!

**Comment by VivianePons** [comment]
We can both do it

**Comment by VivianePons** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01970/joss.01970/10.21105.joss.01970.pdf)

**Comment by sptennak** [comment]
Thanks @mbdemoraes . I will soon review the new materials you added.

**Comment by DARSakthi** [comment]
The authors have presented a package which makes the analysis of high throughput data more accurate, while also making handling this analysis easier. 

Some minor comments on the paper:
     - I suggest you switch the content in Section: Summary with Section: Statement of Need and make necessary changes for flow and comprehension. The reason I recommend this is because what has been written in each section fulfils the requirement of the other section. In Summary you have told us: what is the challenge the software provides a solution to. In Statement of Need you summarise for us how the software works.
     - You should say somewhere telling us explicitly what MOAFS stands for. 
     - There should be a line or two somewhere telling us in concise, explicit terms what MOAFS adds to MOA. Currently the section in which you summarise the package has a long explanation, but it is missing a simple, one line statement about what exactly it does. Preferably it will be placed at the beginning or end of the paragraph. A good item to use would be an abridged version of the abstract contained in moafs/README.md
     - It would be wise to clarify the exact role of Naive Bayes here, or else avoid talking about it at all. Statement of Need makes it seem like Naive Bayes classifier suggests a feature selection algorithm to use. As I understand it, MOAFS is a sandbox for the user to test out the best FS algorithm and Naive Bayes comes later.  You should emphasise this.
     - While you are editing this content I suggest you make edits to the language in the current summary section. There, language and sentence structure could use some revision.

The package itself is well done and functions as described. The extensions are well integrated, showing a good understanding of MOA's original backed, and the code performs efficiently.
     - In documentation (see: https://moafs.readthedocs.io/en/latest/install.html#running-gui) I would recommend making clear that the scripts needs to refer to the full path for sizeof.jar. Here's an example: "[...rest of script...] full_path_to_folder\lib\sizeofag-1.0.4.jar"
     - Alternatively, specify that this must take place from the lib directory.
The above is not strictly necessary, but a suggestion for user clarity.

I recommend eventually bringing the package up to date with MOA 2019 versions, but this can be a living repository so to speak, with that goal coming later. When this happens be sure to update the paper and docs.

I have not tried it on an independent data set but I do not see that as necessary. If I have been unclear on anything or you seek further suggestions please respond. Well done -- I look forward to seeing the final iteration of the paper.

**Comment by mbdemoraes** [comment]
@DARSakthi thank you for your valuable suggestions! I will review these aspects and notify you when I'm done.

**Comment by mbdemoraes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01970/joss.01970/10.21105.joss.01970.pdf)

**Comment by mbdemoraes** [comment]
@DARSakthi  Your suggestions were applied to both paper and documentation. Here is the list of modifications:

- Switched contents from Summary and Statement of Need sections;
- Included a sentence explaining what MOAFS stands for;
- Included a concise, one-line statement about MOAFS purpose in the first paragraph (Summary);
- Changed the "Library design" paragraph to explain better that feature selection is optional and the classification may occur without it;
- Revised paper language and sentence structure;
- On documentation, specified that scripts may be executed from the lib folder or using the full path.

Concerning the update to the 2019 version, you are right, I intend to make a living repository and upgrade it later.

Please, confirm if the adjustments meet your suggestions!

**Comment by DARSakthi** [comment]
This looks great guys. Well done and congratulations. I'm ready to approve
it on my end
Dalton Sakthivadivel
Biomedical Engineering
Stony Brook University

**Comment by sptennak** [comment]
Thanks for accommodating the reviewer suggestions and improving the documentation. I have completed the review checklist and ready to approve.

**Comment by VivianePons** [comment]
Perfect, so I understand we have a go from both reviewers! Let's move forward then to the final steps of accepting the paper :) :)

**Comment by VivianePons** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.neucom.2017.01.078 is OK
- 10.1007/978-1-4612-4380-9_2 is OK
- 10.1145/1150402.1150466 is OK
- 10.1109/TKDE.2013.32 is OK
- 10.1023/A:1022643204877 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by VivianePons** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01970/joss.01970/10.21105.joss.01970.pdf)

**Comment by VivianePons** [comment]
Hi @mbdemoraes can you please check the paper one last time and see if everything is alright? Especially, see if you want to do something about @DARSakthi latest minor comment.

Once done, could you make an archive (on Zenodo, figshare or what you want) of the current repo and send me the DOI. Thank you!

**Comment by mbdemoraes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01970/joss.01970/10.21105.joss.01970.pdf)

**Comment by VivianePons** [comment]
@whedon set https://doi.org/10.6084/m9.figshare.11663307.v1 as doi

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by VivianePons** [comment]
@whedon set https://doi.org/10.6084/m9.figshare.11663307.v1 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.6084/m9.figshare.11663307.v1" target="_blank">10.6084/m9.figshare.11663307.v1</a> is the archive.

**Comment by VivianePons** [comment]
This paper is ready to be accepted! Thank you @sptennak and @DARSakthi for your reviews :)

Now I let @openjournals/joss-eics do the final steps

**Comment by labarba** [comment]
@whedon set v1.1.0 as version

**Comment by whedon** [comment]
OK. v1.1.0 is the version.

**Comment by labarba** [comment]
@mbdemoraes 👋 — I've updated the version according to what I see on the repo. Please confirm that is what you wanted. Also, please update the metadata of your Figshare deposit so that the title of the archive matches the JOSS paper, and the list of authors also matches. (It would be nice if you added a description, too.)

**Comment by mbdemoraes** [comment]
@labarba Thank you for updating the version, it is correct now. 

I also updated the title and description of our Figshare deposit. Concerning the list of authors, it does already matches, doesn't it? The only difference is that Figshare uses an abbreviated form. I had to use André Gradvohl's ORCID to find him at Figshare, and since he registered his name in an abbreviated form, Fighsare used that abbreviation. If this is a problem, please inform me, because I will have to update the paper.

**Comment by labarba** [comment]
@whedon set 10.6084/m9.figshare.11663307.v2 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.6084/m9.figshare.11663307.v2" target="_blank">10.6084/m9.figshare.11663307.v2</a> is the archive.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.neucom.2017.01.078 is OK
- 10.1007/978-1-4612-4380-9_2 is OK
- 10.1145/1150402.1150466 is OK
- 10.1109/TKDE.2013.32 is OK
- 10.1023/A:1022643204877 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1243

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1243, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1220140914330537986) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1244
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01970](https://doi.org/10.21105/joss.01970)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @mbdemoraes, your JOSS paper is published! 🚀 

Huge thanks to our editor: @VivianePons, and the reviewers: @sptennak, @DARSakthi — we couldn't do this without you 🙏

**Comment by mbdemoraes** [comment]
@labarba thank you very much!!

I would like to thank you @VivianePons , @sptennak and @DARSakthi for all the support. You were amazing!

**Comment by VivianePons** [comment]
Congratulation @mbdemoraes ! Thank you @sptennak and @DARSakthi for the great reviews. And thank you @labarba for the support on this submission

**Comment by DARSakthi** [comment]
Congratulations @mbdemoraes!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01970/status.svg)](https://doi.org/10.21105/joss.01970)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01970">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01970/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01970/status.svg
   :target: https://doi.org/10.21105/joss.01970
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01970/status.svg)](https://doi.org/10.21105/joss.01970)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
