### ISSUE TITLE
[PRE REVIEW]: DNAtools: Tools for Analysing Forensic Genetic DNA Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1971]
**Submitting author:** @mikldk (<a href="http://orcid.org/0000-0002-0234-0266">Mikkel Meyer Andersen</a>)
**Repository:** <a href="https://github.com/mikldk/DNAtools" target ="_blank">https://github.com/mikldk/DNAtools</a>
**Version:** 0.2-1
**Editor:** @csoneson
**Reviewers:** @standage, @tomsing1

**Author instructions**

Thanks for submitting your paper to JOSS @mikldk. **Currently, there isn't an JOSS editor assigned** to your paper.

@mikldk if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/9780470867693 is OK
- 10.1016/C2009-0-01945-X is OK
- https://doi.org/10.1016/j.fsigen.2011.08.001 is OK
- https://doi.org/10.1016/j.fsigss.2013.10.142 is OK
- 10.1214/07-AOAS128 is OK

MISSING DOIs

- https://doi.org/10.1520/jfs2003039 may be missing for title: Matching and partially-matching DNA profiles

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01971/joss.01971/10.21105.joss.01971.pdf)

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01971/joss.01971/10.21105.joss.01971.pdf)

**Comment by mikldk** [comment]
Editor suggestion: @mgymrek 
Reviewer suggestions: @standage @tomsing1

**Comment by standage** [comment]
I'd be happy to be a reviewer on this.

**Comment by labarba** [comment]
> Editor suggestion: `@mgymrek`

Please note that `@mgymrek` has stepped down from the editorial board. I'm the associated EiC on rotation this week, and am looking for another handling editor.

**Comment by labarba** [comment]
👋 @csoneson — Could you handle this submission as editor?
Have look please. We understand of course that these days will be slow and you might be on holiday. Let us know, and we can assign you for handling this after the New Year.

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
:wave: @mikldk - I will handle your submission. Thanks for the reviewer suggestions.

@standage - thanks for your willingness to review! Once we have one more reviewer I'll start the review issue.

**Comment by csoneson** [comment]
@tomsing1 - would you be interested in reviewing this submission for JOSS?

**Comment by tomsing1** [comment]
I'd be happy to be a reviewer as well.

**Comment by csoneson** [comment]
Brilliant, thanks @tomsing1!

**Comment by csoneson** [comment]
@whedon assign @standage as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @standage

**Comment by csoneson** [comment]
@whedon add @tomsing1 as reviewer

**Comment by whedon** [comment]
OK, @tomsing1 is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1981. Feel free to close this issue now!
