### ISSUE TITLE
[PRE REVIEW]: NEEP: null empirically estimated p-values for high-throughput molecular survival analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1972]
**Submitting author:** @scwest (<a href="http://orcid.org/0000-0002-1394-1999">Sean West</a>)
**Repository:** <a href="https://github.com/thecodingdoc/neep/" target ="_blank">https://github.com/thecodingdoc/neep/</a>
**Version:** v1
**Editor:** @majensen
**Reviewers:** @wrathematics, @SiminaB, @rhagenson

**Author instructions**

Thanks for submitting your paper to JOSS @scwest. **Currently, there isn't an JOSS editor assigned** to your paper.

@scwest if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- https://doi.org/10.1371/journal.pcbi.1007469 is OK

MISSING DOIs

- https://doi.org/10.1371/journal.pone.0140072 may be missing for title: Robust selection algorithm (RSA) for multi-omic biomarker discovery; integration with functional network analysis to identify miRNA regulated pathways in multiple cancers
- https://doi.org/10.2307/2532740 may be missing for title: Maximally selected rank statistics

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01972/joss.01972/10.21105.joss.01972.pdf)

**Comment by arfon** [comment]
:wave: @will-rowe - the submitting author suggested you as the handling editor.

**Comment by labarba** [comment]
@will-rowe Hi! Have look at this one submission for editing. We understand of course that these days will be slow and you might be on holiday. Let us know, and we can assign you for handling this after the New Year.

**Comment by will-rowe** [comment]
Hi both. This is not my area but I am happy to take it on in the new year.

**Comment by labarba** [comment]
👋 @majensen — I realize you're handling four submissions now, which is more than the majority of editors have assigned, but I believe this particular submission would be a good fit for you. Can you have a look and tell me if you can take it?
We understand of course that these days will be slow and you might be on holiday. Let us know, and we can assign you for handling this after the New Year.

**Comment by majensen** [comment]
@labarba it is interesting and I can do this if you want to assign me after the holidays- thanks

**Comment by labarba** [comment]
Thanks, @majensen! I will assign you now (so the submission comes out of our "without an editor" weekly email), and you can come back to it when you're ready. Everyone is taking a break now, which is good! 🎄

**Comment by labarba** [comment]
@whedon assign @majensen as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by majensen** [comment]
@gsaksena - would you be willing to review this software submission (#1972) for [JOSS](https://joss.theoj.org)? Details on the review process are [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). Really appreciate your consideration! --@majensen

**Comment by majensen** [comment]
Hey @wrathematics, @adavidzh - would either of you be willing to review this submission (#1972) for [JOSS](https://joss.theoj.org]? Thanks for your consideration! --@majensen

**Comment by wrathematics** [comment]
Sure, happy to.

**Comment by majensen** [comment]
@whedon assign @wrathematics as reviewer

**Comment by whedon** [comment]
OK, @wrathematics is now a reviewer

**Comment by adavidzh** [comment]
> Hey @wrathematics, @adavidzh - would either of you be willing to review this submission (#1972) for [JOSS]([https://joss.theoj.org]](https://joss.theoj.org%5D)? Thanks for your consideration! --@majensen

Thank you for considering me but at this time I am afraid I cannot take on this assignment; while I think I understand the mechanism used this is a topic and an area I am not quite that familiar with.

**Comment by majensen** [comment]
@adavidzh thanks for considering and your quick response

**Comment by majensen** [comment]
Hello @tgerke - would you be able to review this submission (#1972) for [JOSS](https://joss.theoj.org)? Much obliged for your consideration! --@majensen

**Comment by majensen** [comment]
Hey @jeremiahsavage - would you be able to review this submission (#1972) for [JOSS](https://joss.theoj.org)? Let me know if you have any questions about the process-Much obliged for your consideration! --@majensen

**Comment by jeremiahsavage** [comment]
> Hey @jeremiahsavage - would you be able to review this submission (#1972) for [JOSS](https://joss.theoj.org)? Let me know if you have any questions about the process-Much obliged for your consideration! --@majensen

Hi @majensen , Thanks for thinking of me on this. It looks like interesting an interesting method, but this is out of my expertise.

**Comment by majensen** [comment]
@SiminaB - Would you be available to review this submission (#1972) for [JOSS](https://joss.theoj.org)? Let me know if you have questions about the process. I really appreciate your consideration! --@majensen

**Comment by majensen** [comment]
@scwest - having some trouble getting traction on this work. Can you provide recommendations for reviewers? I can (prob will) review myself, but want to get your input please.

**Comment by scwest** [comment]
@majensen
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_majensen&d=DwMFaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=u6KSyX1ix4-0aQ2-Xzd9a_xhs3muWm7qOpqtGf4LIc8&m=iDPuoPQZE2mHeNc65ocLmSMVb-R7ul0g1j8b7uZ9Hs8&s=Gt106W2CglZorw9L6_YUI_0o6jm9tqN4aCma__hpQ04&e=>
- I understand the difficulty. I can recommend @rhagenson
<https://github.com/RHagenson>. I'll have to review other JOSS editors
online and get back to you.

**Comment by rhagenson** [comment]
@majensen, I am happy to review this.

@scwest, the list of potential reviewers is found [here](https://bit.ly/joss-reviewers) if more reviewers are necessary.

**Comment by SiminaB** [comment]
Hi! So sorry, I just saw this! I can try to review it but will need some time (like 2-3 weeks). I also haven't done a JOSS review before now so will need to familiarize myself.

**Comment by majensen** [comment]
@SiminaB that would be great! I would be happy to help, and I think the [docs](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) are very good.

**Comment by majensen** [comment]
@rhagenson  thanks very much! I believe we have a quorum.

**Comment by majensen** [comment]
@whedon add @SiminaB as reviewer

**Comment by whedon** [comment]
OK, @SiminaB is now a reviewer

**Comment by majensen** [comment]
@whedon add @rhagenson as reviewer

**Comment by whedon** [comment]
OK, @rhagenson is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2044.

**Comment by majensen** [comment]
All, thanks so much for agreeing to review. Please join the review issue at #2044.
