### ISSUE TITLE
[PRE REVIEW]: ReferenceSeeker: rapid determination of appropriate reference genomes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1973]
**Submitting author:** @oschwengers (<a href="http://orcid.org/0000-0003-4216-2721">Oliver Schwengers</a>)
**Repository:** <a href="https://github.com/oschwengers/referenceseeker" target ="_blank">https://github.com/oschwengers/referenceseeker</a>
**Version:** v1.4
**Editor:** @will-rowe
**Reviewers:** @standage, @luizirber

**Author instructions**

Thanks for submitting your paper to JOSS @oschwengers. **Currently, there isn't an JOSS editor assigned** to your paper.

@oschwengers if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1186/1471-2105-14-60 is OK
- 10.1038/nbt.3820 is OK
- 10.1371/journal.pcbi.1005944 is OK
- 10.1007/s10482-017-0844-4 is OK
- 10.1099/ijs.0.64483-0 is OK
- 10.1093/nar/gkx1068 is OK
- 10.1186/s13059-016-0997-x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01973/joss.01973/10.21105.joss.01973.pdf)

**Comment by labarba** [comment]
Please note that `@mgymrek` has stepped down from the editorial board. I'm the associated EiC on rotation this week, and am looking for another handling editor.

**Comment by labarba** [comment]
👋 @lpantano — Could you handle this submission as editor?
Have look please. We understand of course that these days will be slow and you might be on holiday. Let us know, and we can assign you for handling this after the New Year.

**Comment by will-rowe** [comment]
@labarba - I was just looking at this tool the other day. I'd be happy to take this on as editor in the new year if @lpantano is busy

**Comment by lpantano** [comment]
it seems super interesting but I am ok if @will-rowe can take it bc i’ll be away for two weeks! i will follow the thread!

**Comment by labarba** [comment]
Thanks for the offer, @will-rowe — I'll assign this to you, and look for someone else for https://github.com/openjournals/joss-reviews/issues/1972

**Comment by labarba** [comment]
@whedon assign @will-rowe as editor

**Comment by whedon** [comment]
OK, the editor is @will-rowe

**Comment by will-rowe** [comment]
Hi @standage and @luizirber - would you please be able to review this submission?

**Comment by standage** [comment]
I'd be happy to. Note: I have another JOSS review in progress, so it may be a couple weeks before I can get to this.

**Comment by will-rowe** [comment]
Thanks @standage!

**Comment by luizirber** [comment]
> Hi @standage and @luizirber - would you please be able to review this submission?

Sure!

**Comment by will-rowe** [comment]
Great! Let's kick off the review process then.

**Comment by will-rowe** [comment]
@whedon assign @standage as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @standage

**Comment by will-rowe** [comment]
@whedon add @luizirber as reviewer

**Comment by whedon** [comment]
OK, @luizirber is now a reviewer

**Comment by will-rowe** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1994. Feel free to close this issue now!
