### ISSUE TITLE
[PRE REVIEW]: relped: Build Relatedness Pedigrees

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1974]
**Submitting author:** @RHagenson (<a href="http://orcid.org/0000-0001-9750-1925">Ryan Hagenson</a>)
**Repository:** <a href="https://github.com/rhagenson/relped" target ="_blank">https://github.com/rhagenson/relped</a>
**Version:** v1.0.0
**Editor:** @marcosvital
**Reviewers:** @djmitche, @rabdill

**Author instructions**

Thanks for submitting your paper to JOSS @RHagenson. **Currently, there isn't an JOSS editor assigned** to your paper.

@RHagenson if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1111/j.1471-8286.2006.01256.x is OK
- 10.1016/j.ajhg.2016.05.020 is OK
- 10.2307/2409206 is OK
- 10.1093/bioinformatics/bts460 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01974/joss.01974/10.21105.joss.01974.pdf)

**Comment by arfon** [comment]
:wave: @marcosvital - the submitting author suggested you as the handling editor. Do you think you can handle this one?

**Comment by rhagenson** [comment]
I noticed I placed parentheses around citations which then resulted in double parentheses on the proof. I will submit a fix for that in just a minute and regenerate the pdf.

**Comment by rhagenson** [comment]
@arfon Quick question related to the formatting flubs I am currently fixing. Is there a way to run whedon locally to check formatting before submission? I did not see a way to do this, but that certainly does not mean they do not exist somewhere.

**Comment by arfon** [comment]
@rhagenson - you can debug your paper with Whedon here: http://whedon.theoj.org

**Comment by rhagenson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01974/joss.01974/10.21105.joss.01974.pdf)

**Comment by rhagenson** [comment]
To bring my coauthor in on the review process: @ThatLionLady

**Comment by labarba** [comment]
@marcosvital — We're hoping you can take this through the JOSS process. Have look please. We understand of course that these days will be slow and you might be on holiday. Let us know, and we can assign you for handling this after the New Year.

**Comment by danielskatz** [comment]
👋 @marcosvital - just a post-holiday reminder of this request to edit...

**Comment by marcosvital** [comment]
Hey, everyone, sorry about the (very) late reply. Yes, I can handle this submission!

**Comment by danielskatz** [comment]
thanks - note that you can do the same thing I'm now going to do

**Comment by danielskatz** [comment]
@whedon assign @marcosvital as editor

**Comment by whedon** [comment]
OK, the editor is @marcosvital

**Comment by rhagenson** [comment]
@marcosvital, is there anything you need from me to begin review?

**Comment by marcosvital** [comment]
Hi, @rhagenson , sorry about the delayed reply, I was still organizing myself after some weeks out of office.

If everything seems to be ok with the article proof, we can move on to assigning reviewers for you submission. We usually ask the authors for suggestions, so let me know if you have anyone in mind that could do this.

You can also check this [list of people](https://bit.ly/joss-reviewers) that have agreed to review for JOSS, and see  and may be suitable for this submission.

And let me know if you need any help finding reviewers if you don't have anyone in mind.

**Comment by rhagenson** [comment]
@marcosvital, looking at the list of reviewers, the folks I found via a search for Go and visualization experience are:

@ djmitche
@ terrytangyuan 
@ rabdill

Spaces after the @ to let you make the decision who to reach out to and in what order.

**Comment by rhagenson** [comment]
@marcosvital, I have listed above three potential reviewers found among the list of volunteers. I will leave it up to you to reach out to them as, acting in my role as the author, I feel it is outside my power to offer the review. Is there anything else you need from me?

**Comment by marcosvital** [comment]
Hi, @rhagenson . thanks for pointing potential reviewers for your submission, we can move on and ask them to review.

Dear @djmitche, @terrytangyuan and @rabdill :
Would you be willing to review this submission for JOSS?
We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is still a pre-review, once there are enough reviewers, we will move on to a new issue where the review will take place.

If you are not able, please let us know if you have recommendations for other reviewers.

**Comment by rabdill** [comment]
I'd be happy to.

**Comment by djmitche** [comment]
I had a look through the repo and I'm comfortable reviewing this.

**Comment by marcosvital** [comment]
Thank you @rabdill and @djmitche! I'll wait a few more to see if @terrytangyuan can also join us, but we will move soon to review, ok? This will happen in a new issue, and if yo haven't reviewed for JOSS before, you can take a look [at this guide](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

**Comment by terrytangyuan** [comment]
I am now an editor of JOSS so likely won't have time to participate in reviews. Thanks for checking though. BTW, @arfon could you remove me from the reviewers spreadsheet?

**Comment by arfon** [comment]
> I am now an editor of JOSS so likely won't have time to participate in reviews. Thanks for checking though. BTW, @arfon could you remove me from the reviewers spreadsheet?

Done!

**Comment by rhagenson** [comment]
@whedon generate pdf

Humans: I fixed a formatting error where an en dash did not have a space after it.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01974/joss.01974/10.21105.joss.01974.pdf)

**Comment by rhagenson** [comment]
@marcosvital now that there are two potential reviewers, can this be moved forward?

**Comment by marcosvital** [comment]
Hi, @rhagenson , yes, we can move on to review!

**Comment by marcosvital** [comment]
@whedon add @rabdill as reviewer

**Comment by whedon** [comment]
OK, @rabdill is now a reviewer

**Comment by marcosvital** [comment]
@whedon add @djmitche as reviewer

**Comment by marcosvital** [comment]
@whedon assign @djmitche as reviewer

**Comment by whedon** [comment]
OK, @djmitche is now a reviewer

**Comment by marcosvital** [comment]
@whedon add @rabdill as reviewer

**Comment by whedon** [comment]
OK, @rabdill is now a reviewer

**Comment by marcosvital** [comment]
OK, we are ready to go. This issue will be closed soon, and we will all move to a new one, dedicated to review.

**Comment by marcosvital** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2124.
