### ISSUE TITLE
[PRE REVIEW]: partition: A fast and flexible framework for data reduction in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1975]
**Submitting author:** @malcolmbarrett (<a href="http://orcid.org/0000-0003-0299-5825">Malcolm Barrett</a>)
**Repository:** <a href="https://github.com/USCbiostats/partition" target ="_blank">https://github.com/USCbiostats/partition</a>
**Version:** 0.1.1
**Editor:** @csoneson
**Reviewers:** @lmweber, @clauswilke

**Author instructions**

Thanks for submitting your paper to JOSS @malcolmbarrett. **Currently, there isn't an JOSS editor assigned** to your paper.

@malcolmbarrett if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btz661 is OK
- 10.1038/nrg.2018.4 is OK
- https://doi.org/10.1016/j.coisb.2017.10.003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01975/joss.01975/10.21105.joss.01975.pdf)

**Comment by labarba** [comment]
👋 @csoneson — Could you handle this submission as editor?
Have look please. We understand of course that these days will be slow and you might be on holiday. Let us know, and we can assign you for handling this after the New Year.

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
:wave: @malcolmbarrett - I will handle your submission. Things may be a bit slow over the holidays, but if you have suggestions for reviewers, let me know (please just mention their GitHub username, without the '@', to avoid tagging unnecessarily many people in the issue).

**Comment by csoneson** [comment]
@whedon assign @lmweber as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @lmweber

**Comment by malcolmbarrett** [comment]
Thanks all, and happy new year! If another reviewer is needed, I took a look at the list and here are some folks who might be good fits: dcassol, clauswilke, rcannood. Otherwise, people interested in dimension reduction, performant computing, bioinformatics, or generally working with genetic data may be interested.

**Comment by csoneson** [comment]
@malcolmbarrett Happy New Year! Thanks, those are good reviewer suggestions. I would like to have at least two reviewers looking at the submission.

**Comment by csoneson** [comment]
👋 @dcassol, @clauswilke, @rcannood - would one of you be interested in reviewing this submission for JOSS? 

> partition: A fast and flexible framework for data reduction in R

**Comment by clauswilke** [comment]
Sure.

**Comment by csoneson** [comment]
@clauswilke - Brilliant, thanks!

**Comment by csoneson** [comment]
@whedon add @clauswilke as reviewer

**Comment by whedon** [comment]
OK, @clauswilke is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1991. Feel free to close this issue now!

**Comment by rcannood** [comment]
Sure! :)

**Comment by rcannood** [comment]
Oh. Seems I replied to this issue a little too late! No matter :)

**Comment by csoneson** [comment]
Thanks @rcannood! Yes, I think we are set for this one, but I hope we can come back to you for another review in the future :)

**Comment by dcassol** [comment]
Of course! :)
