### ISSUE TITLE
[PRE REVIEW]: Recan: Python tool for detection of recombination events in viral genomes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1976]
**Submitting author:** @babinyurii (<a href="http://orcid.org/0000-0002-7524-5921">Yuriy Babin</a>)
**Repository:** <a href="https://github.com/babinyurii/recan" target ="_blank">https://github.com/babinyurii/recan</a>
**Version:** v0.1
**Editor:** @will-rowe
**Reviewers:** @lamhm, @betteridiot

**Author instructions**

Thanks for submitting your paper to JOSS @babinyurii. **Currently, there isn't an JOSS editor assigned** to your paper.

@babinyurii if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/j.meegid.2014.12.022 is OK
- 10.1093/bioinformatics/bth500 is OK
- 10.1093/ve/vev003 is OK
- 10.1089/08892220050075309 is OK
- 10.1002/hep.26744 is OK
- 10.1007/s007050050651 is OK
- 10.1371/journal.pone.0207480 is OK
- 10.1093/bioinformatics/btm404 is OK
- 10.1093/nar/gkf436 is OK
- 10.1093/bioinformatics/bts091 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1976 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd7dadefdab3/lib/whedon.rb:145:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd7dadefdab3/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd7dadefdab3/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd7dadefdab3/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd7dadefdab3/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-cd7dadefdab3/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by babinyurii** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1976 with the following error: 

 pandoc-citeproc: reference Martin2015a not found
pandoc-citeproc: reference Smith2014a not found
pandoc-citeproc: reference Jiang1999a not found
pandoc: /pictures/hiv_rec_kal153.png: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by babinyurii** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1976 with the following error: 

 pandoc: /pictures/hiv_rec_kal153.png: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by babinyurii** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1976 with the following error: 

 pandoc: /pictures/hiv_rec_kal153.png: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by babinyurii** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1976 with the following error: 

 pandoc: /paper_plots/hiv_rec_kal153.png: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by babinyurii** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01976/joss.01976/10.21105.joss.01976.pdf)

**Comment by babinyurii** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01976/joss.01976/10.21105.joss.01976.pdf)

**Comment by babinyurii** [comment]
@whedon  commands

**Comment by babinyurii** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by labarba** [comment]
@will-rowe — Could you handle this submission as editor?
Have look please. We understand of course that these days will be slow and you might be on holiday. I also realize that I have asked you to take another submission... we have received half a dozen submissions in various flavors of bioinformatics, and our all editors in this topic have been asked!

**Comment by will-rowe** [comment]
Hey @labarba - this sounds nice. I will gladly edit but am about to go on AL over Christmas. I will find reviewers in the new year.

**Comment by will-rowe** [comment]
@whedon assign @will-rowe as editor

**Comment by whedon** [comment]
OK, the editor is @will-rowe

**Comment by will-rowe** [comment]
Hey @RHagenson and @joaorodrigues - would you be please able to review this for us?

**Comment by JoaoRodrigues** [comment]
Hi @will-rowe 

Thanks for the invitation but I am not sure I have the right expertise to review this paper adequately, particuarly in terms of relevance to the field and appropriate methodology. If you're fine with me reviewing only the software component, I will be more than happy to contribute.

Cheers

**Comment by will-rowe** [comment]
No worries @JoaoRodrigues - thank you for your reply. I'll try and find someone else on this occasion. Thanks again.

**Comment by will-rowe** [comment]
Hey @flashton2003 - would you be willing to review this paper for JOSS?

**Comment by rhagenson** [comment]
@will-rowe I seem to be in the same boat as João in that I lack the necessary expertise to review the paper adequately. I do not work with viral genomes, nor know the solution space of similar tools to judge this tool's merit within appropriate context; therefore, I must politely decline the request to review.

**Comment by will-rowe** [comment]
No worries @rhagenson

**Comment by will-rowe** [comment]
Hi @nhejazi - would you please be able to review this?

**Comment by flashton2003** [comment]
Hi @will-rowe, I’m not really qualified for this but my deskmate @lamhm would be great for this.

**Comment by will-rowe** [comment]
Hey @flashton2003 - I was hoping you might know someone if you couldn't do it. Thanks very much for the tip off.

Hi @lamhm - it would be fantastic if you could review this submission for us. Please do let me know if you can or if you need any information on how the review process works at JOSS.

**Comment by will-rowe** [comment]
Hi @natir - would you be willing to review this for us please?

**Comment by lamhm** [comment]
Hi @will-rowe,

Sorry, I did not notice that I had a message on Github. I am happy to help. But I do not familiar with this style of review. Do you have a guideline that I can follow?

**Comment by will-rowe** [comment]
Fantastic - thank you very much @lamhm!

Reviewer criteria and checklist for completing a review can be found [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). Once I have confirmed a second reviewer, we will start the review process officially - this is when we create a new GitHub issue where we can keep track of the reviews etc. This new issue will be where you complete the reviewer checklist and where we interact (in terms of asking for revisions, confirming acceptance. If you have any revisions/edits for the author, it's best to make those as new issues on the repository of the software being reviewed, then reference the issue in the review issue if needed.

Hope this makes sense to you, let me know if you have any queries and I'll let you know when we're moving this into review (but you can start your review now if you like and complete the checklist in due course).

**Comment by natir** [comment]
Hi @will-rowe sorry, I don't think I'm the right person to review this paper.

**Comment by will-rowe** [comment]
No worries @natir - thanks for the quick response

**Comment by will-rowe** [comment]
Hi @betteridiot - would you be able to review this paper for JOSS?

**Comment by betteridiot** [comment]
Sure. I am happy to help.

**Comment by will-rowe** [comment]
Brill - thanks @betteridiot! Let's start the review process.

**Comment by will-rowe** [comment]
@whedon assign @lamhm as reviewer

**Comment by whedon** [comment]
OK, @lamhm is now a reviewer

**Comment by will-rowe** [comment]
@whedon add @betteridiot as reviewer

**Comment by whedon** [comment]
OK, @betteridiot is now a reviewer

**Comment by will-rowe** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2014. Feel free to close this issue now!
