### ISSUE TITLE
[PRE REVIEW]: Hoki: Making BPASS accessible through Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1977]
**Submitting author:** @heloises (<a href="http://orcid.org/0000-0002-0504-4323">H. F. Stevance</a>)
**Repository:** <a href="https://github.com/HeloiseS/hoki" target ="_blank">https://github.com/HeloiseS/hoki</a>
**Version:** v1.3.2b0
**Editor:** @arfon
**Reviewers:** @ygrange, @KshitijAggarwal

**Author instructions**

Thanks for submitting your paper to JOSS @heloises. **Currently, there isn't an JOSS editor assigned** to your paper.

@heloises if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1977 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1017/pasa.2017.51 is OK
- 10.1126/science.1223344 is OK
- 10.1088/0067-0049/190/1/1 is OK
- 10.1111/j.1365-2966.2007.12738.x is OK
- 10.1093/mnras/stt1612 is OK
- 10.1093/mnras/stw1772 is OK
- 10.1103/PhysRevLett.119.161101 is OK
- 10.1093/mnras/sty1353 is OK
- 10.1111/j.1365-2966.2009.15514.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01977/joss.01977/10.21105.joss.01977.pdf)

**Comment by arfon** [comment]
:wave: @HeloiseS, thanks for your submission to JOSS! Does this accompany a paper in a AAS journal?

Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission? Please don't @-mention them here (i.e. refer to them as `arfon` rather than @arfon). 

Also, feel free to suggest reviewers that you're aware of from the wider community who you think might be able to give this a good review.

**Comment by HeloiseS** [comment]
Hello @arfon!

I had a look at the list and it looks like `KshitijAggarwal`, `ygrange` or `zhampel` would do be well suited for review :)

Thanks!

**Comment by HeloiseS** [comment]
Oh and sorry I forgot to say that, no it doesn't accompany an AAs publication - this is stand alone. Cheers :+1:

**Comment by arfon** [comment]
@KshitijAggarwal and @ygrange - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by ygrange** [comment]
Not this year, but surely happy to have a look at it when back in
January �

--
Y. Grange

> Op 22 dec. 2019 om 22:39 heeft Arfon Smith <notifications@github.com>
het volgende geschreven:
> 
> ﻿
> @KshitijAggarwal and @ygrange - would you be willing to review this
submission for JOSS? We carry out our checklist-driven reviews here in
GitHub issues and follow these guidelines:
https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by arfon** [comment]
> Not this year, but surely happy to have a look at it when back in January.

👍 fantastic, thanks! This is a very slow time of year for lots of people so no big rush here... I'll go ahead and add you as a reviewer now but won't set up the actual review until there's a second reviewer.

**Comment by arfon** [comment]
@whedon add @ygrange as reviewer

**Comment by whedon** [comment]
OK, @ygrange is now a reviewer

**Comment by ygrange** [comment]
> > Not this year, but surely happy to have a look at it when back in January.
> 
> 👍 fantastic, thanks! This is a very slow time of year for lots of people so no big rush here... I'll go ahead and add you as a reviewer now but won't set up the actual review until there's a second reviewer.

Perfect! I should've mentioned that I prefer being part of multiple reviewers anyhow. 

Happy holidays y'all!

**Comment by KshitijAggarwal** [comment]
@arfon, sorry for the late reply, I was traveling this week. 
Yes, I can review this submission.

**Comment by arfon** [comment]
@whedon add @KshitijAggarwal as reviewer

**Comment by whedon** [comment]
OK, @KshitijAggarwal is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1987. Feel free to close this issue now!

**Comment by arfon** [comment]
@ygrange, @KshitijAggarwal - many thanks for agreeing to review this. I've gone ahead and opened the main review issue over in #1987 but I realize this is a busy time of year with holidays etc. Please don't feel under any pressure to work on this during the holiday season!
