### ISSUE TITLE
[REVIEW]: Pubmed Parser: A Python Parser for PubMed Open-Access XML Subset and MEDLINE XML Dataset XML Dataset

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1979]
**Submitting author:** @titipata (<a href="http://orcid.org/0000-0002-2124-2979">Titipat Achakulvisut</a>)
**Repository:** <a href="https://github.com/titipata/pubmed_parser" target ="_blank">https://github.com/titipata/pubmed_parser</a>
**Version:** v0.2.3
**Editor:** @majensen
**Reviewer:** @timClicks, @tleonardi
**Archive:** <a href="https://doi.org/10.5281/zenodo.3660006" target="_blank">10.5281/zenodo.3660006</a>

## Status

[![status](https://joss.theoj.org/papers/207c45f0d1fc3b190cbeff2b2c27d128/status.svg)](https://joss.theoj.org/papers/207c45f0d1fc3b190cbeff2b2c27d128)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/207c45f0d1fc3b190cbeff2b2c27d128"><img src="https://joss.theoj.org/papers/207c45f0d1fc3b190cbeff2b2c27d128/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/207c45f0d1fc3b190cbeff2b2c27d128/status.svg)](https://joss.theoj.org/papers/207c45f0d1fc3b190cbeff2b2c27d128)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/titipata/pubmed_parser" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@timClicks & @tleonardi, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @majensen know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/titipata/pubmed_parser">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@titipata) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/titipata/pubmed_parser">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@titipata) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @timClicks, @tleonardi it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1186/s12859-019-2958-3 is OK
- 10.7287/peerj.preprints.27479v2 is OK
- 10.18653/v1/w18-2307 is OK
- 10.3233/shti190172 is OK
- 10.1371/journal.pone.0198030 is OK
- 10.1109/hpcc/smartcity/dss.2019.00217 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01979/joss.01979/10.21105.joss.01979.pdf)

**Comment by majensen** [comment]
Happy New Year @timClicks, @tleonardi - just a gentle reminder to please begin your review of #1979.
Thanks

**Comment by titipata** [comment]
Hi all,

Just a quick update here. I updated the repository according to @tleonardi comments. I also created a test folder and sphinx documentation on the repository which I will be updating in this coming week. We hope to make the documentation better in the coming week!

**Comment by majensen** [comment]
@timClicks, how is it going with your review?

**Comment by tleonardi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01979/joss.01979/10.21105.joss.01979.pdf)

**Comment by tleonardi** [comment]
Hi @titipata,                                                                                                                                                                                                                                                                               
I'm happy with all the changes you've made, great job writing and automating the tests! 
I only have a few concerns left, mostly regarding the README and documentation.
                                                                                                                                                        
I think it would be important, at the beginning of the README, to describe what kind of information is contained in the XML files and what can be obtained with pubmed_parser.
You could also add an index with links to the various sections of the README (Installation, Documentation, Examples, Citation, etc...).
Regarding the documentation, I think many functions lack a high level explanation of what they do: what do the input XMLs contain? What's contained in the results returned?
Lastly, I've just opened an [issue](https://github.com/titipata/pubmed_parser/issues/82) indicating some missing bits in the API docs.
All the rest is looking good!

**Comment by titipata** [comment]
@tleonardi Thank you so much for the details comments! I'll update the API documentation according to your comment by the end of this week. I will also edit the README so that it contains information about the XML files. I'll tag you once it's done.

**Comment by majensen** [comment]
@timClicks are you still able to review this work (#1979)? Thanks for any update.

**Comment by timClicks** [comment]
Really sorry about letting this slip. I will have a review within 12h.

**Comment by timClicks** [comment]
@titipata Thank you for taking the time to publish this package as open source software. I've reviewed it and the paper, and have nothing further to add above @tleonardi's comments. 

@majensen I have reviewed the submission and recommend accepting it for publication.

**Comment by majensen** [comment]
@timClicks very much appreciated. I will start my due diligence -- @titipata you may see some minor PRs come your way. Hope to accomplish over next couple of days.

**Comment by titipata** [comment]
Thank you so much @tleonardi  @timClicks @majensen for all your efforts and great reviews! We really appreciate it! Looking forward to the PRs.

**Comment by majensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01979/joss.01979/10.21105.joss.01979.pdf)

**Comment by majensen** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1186/s12859-019-2958-3 is OK
- 10.7287/peerj.preprints.27479v2 is OK
- 10.18653/v1/w18-2307 is OK
- 10.3233/shti190172 is OK
- 10.1371/journal.pone.0198030 is OK
- 10.1109/hpcc/smartcity/dss.2019.00217 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by majensen** [comment]
Hi @titipata - I've created a PR for you to consider: https://github.com/titipata/pubmed_parser/pull/84

Also, in the code example in the text, would you consider changing
`data/medline16n0902.xml.gz`
to
`data/pubmed20n0014.xml.gz`
since the latter file is actually present in the `data` directory of the repo? Then a user can simply run the sample code after cloning and installing.

thanks

**Comment by majensen** [comment]
Hi @tleonardi - I notice one box is left unchecked on your review (_Functionality documentation_). Do you still have issues here? Thanks for having a look.

**Comment by tleonardi** [comment]
Hi @majensen,
I just hadn't checked the last changes that @titipata introduced after my last comments. I have checked now and the API docs look good! I haven't seen changes in the README, but my suggestions where mostly minor details. No need to hold the publication because of this.
Overall, `pubmed_parser` is a solid software that's going to be of great help to the scientific community (as shown by the number of publications that already use it). I am happy to recommend it for publication in JOSS.

**Comment by majensen** [comment]
@tleonardi thanks very much!

**Comment by majensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01979/joss.01979/10.21105.joss.01979.pdf)

**Comment by majensen** [comment]
@titipata we are on the home stretch. Can you now create a persistent archive of the repository at a service such as [Zenodo](https://zenodo.org)? For Zenodo there is a mini tutorial at [this comment](https://github.com/openjournals/joss-reviews/issues/1839#issuecomment-560048729).
Thanks!

**Comment by titipata** [comment]
Hi @majensen, thank you so much. I updated DOI for the repository and updated it in `README` accordingly. The new DOI should be `10.5281/zenodo.3648715` for the Pubmed Parser 0.2.2

**Comment by majensen** [comment]
Thanks @titipata  - JOSS requires the author list in the paper to be the same as the author list in the archive. I think it's great to give credit to your contributors, but I think GitHub handles that pretty well, so I would suggest updating the archive metadata author list to include just the 3 on your initial submission.

**Comment by titipata** [comment]
@majensen thank you so much! I updated the metadata author list to 3, the same as in the submission in Pubmed Parser 0.2.2.

**Comment by danielskatz** [comment]
The other option would be to add the others to the paper as well.  We just want these to be consistent.

**Comment by titipata** [comment]
@danielskatz thanks! We have discussed and decided to include 3 main contributors in our paper. I edited Zenodo accordingly. This should be consistent with the JOSS submission :) Let me know if there is any concern regarding our decision!

**Comment by majensen** [comment]
@titipata great!

**Comment by majensen** [comment]
@whedon set 10.5281/zenodo.3648715 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3648715" target="_blank">10.5281/zenodo.3648715</a> is the archive.

**Comment by majensen** [comment]
@whedon set 0.2.2 as version

**Comment by whedon** [comment]
OK. 0.2.2 is the version.

**Comment by majensen** [comment]
@openjournals/joss-eics, the reviewers and I recommend this work for publication; please review. Thanks!

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01979/joss.01979/10.21105.joss.01979.pdf)

**Comment by kthyng** [comment]
@titipata Your paper looked good but your references had typos. I fixed them in a PR. See if you want to merge the changes: [#86](https://github.com/titipata/pubmed_parser/pull/86)

**Comment by titipata** [comment]
@kthyng Thank you so much for the fix. I merged the PR!

**Comment by titipata** [comment]
@majensen @kthyng Do I need to create a new archive release and DOI for the repository?

**Comment by majensen** [comment]
@titipata I believe you can update the archive with a new version and keep the DOI- just report back the new version here. Thanks!

**Comment by titipata** [comment]
@majensen I somehow updated to `v0.2.3` instead and the associated DOI should be 10.5281/zenodo.3660006 instead. Sorry for the confusion but this should be the final version!

**Comment by kthyng** [comment]
@whedon add 10.5281/zenodo.3660006 as archive

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.3660006 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3660006" target="_blank">10.5281/zenodo.3660006</a> is the archive.

**Comment by kthyng** [comment]
@whedon set v0.2.3 as version

**Comment by whedon** [comment]
OK. v0.2.3 is the version.

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1186/s12859-019-2958-3 is OK
- 10.7287/peerj.preprints.27479v2 is OK
- 10.18653/v1/w18-2307 is OK
- 10.3233/shti190172 is OK
- 10.1371/journal.pone.0198030 is OK
- 10.1109/hpcc/smartcity/dss.2019.00217 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1282

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1282, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1226242714787885061) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1283
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01979](https://doi.org/10.21105/joss.01979)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Congratulations to  @titipata on your new publication! Thanks to @majensen for editing, and to @timClicks and @tleonardi for your time and expertise reviewing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01979/status.svg)](https://doi.org/10.21105/joss.01979)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01979">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01979/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01979/status.svg
   :target: https://doi.org/10.21105/joss.01979
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01979/status.svg)](https://doi.org/10.21105/joss.01979)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by titipata** [comment]
Thanks @kthyng! And thank you so much @majensen, @tleonardi, @tleonardi for editing our submission.

tag @daniel-acuna @koerding here!
