### ISSUE TITLE
[PRE REVIEW]: NCBImeta: efficient and comprehensive metadata retrieval from NCBI databases

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1980]
**Submitting author:** @ktmeaton (<a href="http://orcid.org/0000-0001-6862-7756">Katherine Eaton</a>)
**Repository:** <a href="https://github.com/ktmeaton/NCBImeta" target ="_blank">https://github.com/ktmeaton/NCBImeta</a>
**Version:** v0.6.1
**Editor:** @lpantano
**Reviewers:** @coughls, @druvus

**Author instructions**

Thanks for submitting your paper to JOSS @ktmeaton. **Currently, there isn't an JOSS editor assigned** to your paper.

@ktmeaton if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1186/1471-2105-14-19 is OK
- 10.1093/bioinformatics/btx334 is OK
- 10.1186/s12859-016-1231-2 is OK
- 10.12688/f1000research.18676.1 is OK
- 10.7554/eLife.07335 is OK
- 10.1371/journal.pone.0077910 is OK
- 10.1057/biosoc.2015.22 is OK
- 10.1093/bioinformatics/btp163 is OK
- 10.1111/2049-632X.12107 is OK
- 10.1093/jac/dks261 is OK
- 10.1128/mBio.01721-14 is OK

MISSING DOIs

- https://doi.org/10.1007/springerreference_36064 may be missing for title: NCBI

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01980/joss.01980/10.21105.joss.01980.pdf)

**Comment by labarba** [comment]
👋 @lpantano — I know you said you'd be on holiday for two weeks ... but so is most everyone on the JOSS board! This submission looks like a good fit for you to take through review. Can you take it, in the understanding it will take a little while to get started?

**Comment by lpantano** [comment]
yes, this is a good fit!

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by ktmeaton** [comment]
Thank you for considering this paper! From the spreadsheet of current JOSS reviewers, here are some suggestions based on topic (Bioinformatics/Genomics) and language (Python):
- Luiz Irber (luizirber)
- Louis J Taylor (louiejtaylor)
- Hadrien Gourlé (HadrienG)
- Joep de Ligt (jdeligt)
- Simone Coughlan (coughls)
- Rachel Schwartz (rachelss)
- Marek Borowiec (marekborowiec)
- C. Titus Brown  (ctb)

**Comment by lpantano** [comment]
@druvus, @coughls, would you like to review this at the beginning of the next year?

**Comment by coughls** [comment]
Yes I can review this!

**Comment by druvus** [comment]
yes I can review it too.

**Comment by lpantano** [comment]
@whedon assign @coughls as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @coughls

**Comment by lpantano** [comment]
@whedon add @druvus as reviewer

**Comment by whedon** [comment]
OK, @druvus is now a reviewer

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1990. Feel free to close this issue now!
