### ISSUE TITLE
[REVIEW]: DNAtools: Tools for Analysing Forensic Genetic DNA Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1981]
**Submitting author:** @mikldk (<a href="http://orcid.org/0000-0002-0234-0266">Mikkel Meyer Andersen</a>)
**Repository:** <a href="https://github.com/mikldk/DNAtools" target ="_blank">https://github.com/mikldk/DNAtools</a>
**Version:** 0.2-1
**Editor:** @csoneson
**Reviewer:** @standage, @tomsing1
**Archive:** <a href="https://doi.org/10.5281/zenodo.3609584" target="_blank">10.5281/zenodo.3609584</a>

## Status

[![status](https://joss.theoj.org/papers/d5f3304471b19273d64bc6438bd618d1/status.svg)](https://joss.theoj.org/papers/d5f3304471b19273d64bc6438bd618d1)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d5f3304471b19273d64bc6438bd618d1"><img src="https://joss.theoj.org/papers/d5f3304471b19273d64bc6438bd618d1/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d5f3304471b19273d64bc6438bd618d1/status.svg)](https://joss.theoj.org/papers/d5f3304471b19273d64bc6438bd618d1)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mikldk/DNAtools" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@standage & @tomsing1, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mikldk/DNAtools">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mikldk) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mikldk/DNAtools">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mikldk) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @standage, @tomsing1 it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1002/9780470867693 is OK
- 10.1016/C2009-0-01945-X is OK
- 10.1016/j.fsigen.2011.08.001 is OK
- 10.1016/j.fsigss.2013.10.142 is OK
- 10.1520/jfs2003039 is OK
- 10.1214/07-AOAS128 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01981/joss.01981/10.21105.joss.01981.pdf)

**Comment by csoneson** [comment]
:wave: @standage, @tomsing1 - this is where the review happens. Please check the instructions above and don't hesitate to ping me if you have any questions!

**Comment by tomsing1** [comment]
I have completed my review and checked all but one box below:

> ## Review checklist for @tomsing1
> ### Conflict of interest
> * [x]  I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.
> 
> ### Code of Conduct
> * [x]  I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).
> 
> ### General checks
> * [x]  **Repository:** Is the source code for this software available at the [repository url](https://github.com/mikldk/DNAtools)?
> * [x]  **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
> * [x]  **Contribution and authorship:** Has the submitting author (@mikldk) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
> 
> ### Functionality
> * [x]  **Installation:** Does installation proceed as outlined in the documentation?
> * [x]  **Functionality:** Have the functional claims of the software been confirmed?
> * [x]  **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)
> 
> ### Documentation
> * [x]  **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
> * [x]  **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
> * [x]  **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
> * [x]  **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
  - :rocket: The package vignettes are extensive and carefully written.
> * [x]  **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
> * [x]  **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
> 
> ### Software paper
> * [x]  **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
> * [x]  **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
> * [ ]  **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
  - :warning: No mention is made of other software performing a similar task. Perhaps the authors can
    comment on the absence of (and hence need for) the package's functionality in the text?
> * [x]  **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
  - I found a few typos and filed them as [an issue in the package's repo](https://github.com/mikldk/DNAtools/issues/1#issue-545514822)
> * [x]  **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?
  - I found a reference that was misrendered due to a typo and included it [in the issue in the package's repo](https://github.com/mikldk/DNAtools/issues/1#issue-545514822)

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #1981 with the following error: 

 Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.355 {[} \Pr

Looks like we failed to compile the PDF

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #1981 with the following error: 

 Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.377 (\$7.54\times

Looks like we failed to compile the PDF

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01981/joss.01981/10.21105.joss.01981.pdf)

**Comment by mikldk** [comment]
@tomsing1 Thanks. We have addressed you points, thanks! Also see [the issue in the repo](https://github.com/mikldk/DNAtools/issues/1). 

Regarding 

> No mention is made of other software performing a similar task. Perhaps the authors can
comment on the absence of (and hence need for) the package's functionality in the text?

We have added this phrase:

> To our knowledge, `DNAtools` is the only software that can perform such computations.

**Comment by tomsing1** [comment]
I have completed my review and checked all boxes!

> ## Review checklist for @tomsing1
> ### Conflict of interest
> * [x]  I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.
> 
> ### Code of Conduct
> * [x]  I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).
> 
> ### General checks
> * [x]  **Repository:** Is the source code for this software available at the [repository url](https://github.com/mikldk/DNAtools)?
> * [x]  **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
> * [x]  **Contribution and authorship:** Has the submitting author (@mikldk) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
> 
> ### Functionality
> * [x]  **Installation:** Does installation proceed as outlined in the documentation?
> * [x]  **Functionality:** Have the functional claims of the software been confirmed?
> * [x]  **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)
> 
> ### Documentation
> * [x]  **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
> * [x]  **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
> * [x]  **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
> * [x]  **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
> * [x]  **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
> * [x]  **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
> 
> ### Software paper
> * [x]  **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
> * [x]  **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
> * [x]  **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
> * [x]  **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
> * [x]  **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by standage** [comment]
I am currently working on my review and should have it completed shortly!

**Comment by mikldk** [comment]
> I am currently working on my review and should have it completed shortly!

Sounds great. Let us know if you have any questions or anything else we can do.

**Comment by standage** [comment]
The authors describe DNAtools, an R package that implements methods for analysis of short tandem repeat (STR) profiles obtained from forensic DNA traces. DNAtools advertises two primary capabilities. The first focuses on estimating the complexity of DNA mixtures (the number of contributors) by examination of the total number of observed alleles present in a sample. The second focuses on empirical derivation of match probabilities between pairs of entries in a forensic DNA database, including adjustments for multiple testing. As is customary for R packages, these capabilities are demonstrated in a handful of vignettes prepared using a representative data set.

I have added several comments below for the authors' consideration, but in any case I endorse this submission for publication in JOSS.


## Installation

The standard installation instructions should be sufficient for the majority of users. I am likely a bit of a special case, in that the computers I use for data analysis are airgapped and cannot connect to the internet. As a consequence, `devtools::install_gitub("mikldk/DNAtools")` was not an option for me. However, it's not unreasonable to expect that scientists in some forensics labs may also have an airgapped setup for security reasons. So providing install instructions for this use case is potentially useful.

I'm only an occasional R user and I don't write R packages, so figuring this out took some time and effort. It may be trivial for an R developer to do, or there may even be a better way. But with a bit of research and trial-and-error I was able to install DNAtools successfully using the following procedure.

- download DNAtools as a .tar.gz archive from GitHub, transfer to computer using removable media
- install `devtools` and DNAtools pre-requisites (multicool, Rcpp, RcppParallel, RcppProgress, Rsolnp)
- install DNAtools in R using `devtools::install_local`

I'd recommend including some guidelines for offline installation in the instructions.

Related issue: https://github.com/mikldk/DNAtools/issues/3


## Minor grammatical errors

- JOSS paper
    - "forensic scientists toolbox" should be punctuated "forensic scientist's toolbox"
    - "effificy of new multiplexes" should be spelled "efficacy of new multiplexes"
    - "The analysis of mixed DNA traces *have* proven" should be "The analysis of mixed DNA traces *has* proven"
    - "there *exists* near matches" should be "there *exist* near matches"
- dna_vignette
    - "the number of distint alleles present" should be spelled "the number of distinct alleles present"


## Suggested revisions

In the second paragraph of the JOSS paper, the random match probability (RMP) is used before it is defined. I'd suggest revising the second sentence of that paragraph for clarity (possible example below), and then switching the order of the 2nd and 3rd sentences so that the RMP is defined before it is discussed.

> *The number of STR markers assayed by contemporary forensic kits commonly result in RMPs in the order of 10<sup>-20</sup>, a level of confidence considered insufficiently conclusive by some.*

In general I think the DNAtools documentation is good. But the purpose of the software is buried in the GitHub repo's main README. I'd suggest highlighting the "Getting started" section more prominently. Related issue: https://github.com/mikldk/DNAtools/issues/2.

**Comment by standage** [comment]
I have not looked at the comments in @tomsing1's review, nor the author responses. It's possible some of the issues I raise have already been addressed. Please feel free to point this out if it's the case.

Unresolved points.

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by standage** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01981/joss.01981/10.21105.joss.01981.pdf)

**Comment by standage** [comment]
Looks like the references render correctly in the latest proof.

**Comment by standage** [comment]
Latest proof now also indicates the absence of other tools for comparison.

**Comment by mikldk** [comment]
I believe that "Installation" was addressed by https://github.com/mikldk/DNAtools/issues/3. 

The "Minor grammatical errors" was addressed by https://github.com/mikldk/DNAtools/commit/252d94d5ac97e90b7be31d94175e5e4a1f865e1e. 

I am not sure if "Suggested revisions" is still present for the latest proof?

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01981/joss.01981/10.21105.joss.01981.pdf)

**Comment by standage** [comment]
Yep. I think I misunderstood the sentence for which I was suggesting revisions. The latest proof defines the RMP before discussing it, and is much clearer than the original submission. 👍

**Comment by standage** [comment]
It looks like all the errors/typos I pointed out have been addressed. However, a new one was introduced: "surpriseing" should be spelled "surprising."

Sorry for the bikeshedding! :-)

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01981/joss.01981/10.21105.joss.01981.pdf)

**Comment by standage** [comment]
LGTM!

@csoneson, my review is complete and I have checked all boxes.

**Comment by mikldk** [comment]
> It looks like all the errors/typos I pointed out have been addressed. However, a new one was introduced: "surpriseing" should be spelled "surprising."
> 
> Sorry for the bikeshedding! :-)

Thanks! Embarrassing. That's not bikeshedding! Thanks. Now fixed in https://github.com/mikldk/DNAtools/commit/00824acb90611e9041510ef3e902bc6e7b00624b.

**Comment by mikldk** [comment]
@tomsing1 @standage Thank you both very much for taking the time for reviewing and improving our software!

**Comment by mikldk** [comment]
DOI: <https://doi.org/10.5281/zenodo.3608229>: <https://zenodo.org/record/3608229>

**Comment by csoneson** [comment]
👋 @mikldk - I have gone through the paper and submitted a PR with a couple of minor fixes. Could you check and merge that, and generate a new proof? 

Also, could you please edit the Zenodo archive so that the title and authors exactly match those of the paper.

**Comment by csoneson** [comment]
@tomsing1, @standage - thanks a lot for your reviews!

**Comment by mikldk** [comment]
@csoneson Thanks! PR now merged and README/site rebuild: https://github.com/mikldk/DNAtools/commit/d25fc87e7760f6fe7ed65b853618a76b1f966b31 .

I generated new release at GitHub and Zenodo. DOI for new release: DOI: [10.5281/zenodo.3609584](https://doi.org/10.5281/zenodo.3609584) / <https://zenodo.org/record/3609584>.

I hope everything is okay, or else let me know! Thanks for all the help and the contribution.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01981/joss.01981/10.21105.joss.01981.pdf)

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1002/9780470867693 is OK
- 10.1016/C2009-0-01945-X is OK
- 10.1016/j.fsigen.2011.08.001 is OK
- 10.1016/j.fsigss.2013.10.142 is OK
- 10.1520/jfs2003039 is OK
- 10.1214/07-AOAS128 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@whedon set 10.5281/zenodo.3609584 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3609584" target="_blank">10.5281/zenodo.3609584</a> is the archive.

**Comment by csoneson** [comment]
@whedon set 0.2-1 as version

**Comment by whedon** [comment]
OK. 0.2-1 is the version.

**Comment by csoneson** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1002/9780470867693 is OK
- 10.1016/C2009-0-01945-X is OK
- 10.1016/j.fsigen.2011.08.001 is OK
- 10.1016/j.fsigss.2013.10.142 is OK
- 10.1520/jfs2003039 is OK
- 10.1214/07-AOAS128 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1226

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1226, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by csoneson** [comment]
@openjournals/joss-eics - this paper is ready to be accepted. Over to you!

**Comment by kyleniemeyer** [comment]
Looks good to me.

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1217887294327283719) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1233
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01981](https://doi.org/10.21105/joss.01981)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @mikldk on your article's publication in JOSS!

Many thanks to @standage and @tomsing1 for reviewing this, and @csoneson for editing.

**Comment by mikldk** [comment]
@standage @tomsing1 @csoneson @kyleniemeyer: Many thanks to you all for your help and work!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01981/status.svg)](https://doi.org/10.21105/joss.01981)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01981">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01981/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01981/status.svg
   :target: https://doi.org/10.21105/joss.01981
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01981/status.svg)](https://doi.org/10.21105/joss.01981)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
