### ISSUE TITLE
[PRE REVIEW]:  BamWithoutBai: fast retrieval of alignments from remote BAM without BAI index

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1984]
**Submitting author:** @lindenb (<a href="http://orcid.org/0000-0003-0148-9787">Pierre Lindenbaum</a>)
**Repository:** <a href="https://github.com/lindenb/jvarkit" target ="_blank">https://github.com/lindenb/jvarkit</a>
**Version:** 20191222
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @lindenb. **Currently, there isn't an JOSS editor assigned** to your paper.

@lindenb if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btp352 is OK
- 10.6084/m9.figshare.1425030.v1 is OK
- 10.1093/nar/gkx1081 is OK
- 10.1093/bioinformatics/bts054 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01984/joss.01984/10.21105.joss.01984.pdf)

**Comment by arfon** [comment]
:wave: @lindenb - thanks for your submission to JOSS. Before I look for an editor to handle this submission, could you please clarify a little what software is associated with this submission? The paper seems to be referencing a specific tool (`BamWithoutBai`) that forms part of a larger set of packages (https://github.com/lindenb/jvarkit).

Would it be correct to say that this submission is associated with this source code?:
https://github.com/lindenb/jvarkit/blob/master/src/main/java/com/github/lindenb/jvarkit/tools/nobai/BamWithoutBai.java

**Comment by lindenb** [comment]
@arfon thanks for the message. yes you're right ! The main code is here;

https://github.com/lindenb/jvarkit/blob/master/src/main/java/com/github/lindenb/jvarkit/tools/nobai/BamWithoutBai.java

and the test:

https://github.com/lindenb/jvarkit/blob/master/src/test/java/com/github/lindenb/jvarkit/tools/nobai/BamWithoutBaiTest.java


As stated in the paper.md , the main documentation for this software is here: http://lindenb.github.io/jvarkit/BamWithoutBai.html

**Comment by arfon** [comment]
Hi @lindenb. Thanks again for your submission to JOSS. Unfortunately after discussing this with the editorial team we have determined this is out of scope for JOSS due to its ['minor utility'](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) nature.

**Comment by lindenb** [comment]
@tomwhite FYI
