### ISSUE TITLE
[PRE REVIEW]: A Framework to Quality Control Oceanographic Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1985]
**Submitting author:** @castelao (<a href="http://orcid.org/0000-0002-6765-0708">Guilherme Castelao</a>)
**Repository:** <a href="https://github.com/castelao/CoTeDe" target ="_blank">https://github.com/castelao/CoTeDe</a>
**Version:** 0.21.0
**Editor:** @kthyng
**Reviewers:** @jessicaaustin, @evanleeturner

**Author instructions**

Thanks for submitting your paper to JOSS @castelao. **Currently, there isn't an JOSS editor assigned** to your paper.

@castelao if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1985 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@castelao our bot `@whedon` cannot find the paper.md file. Where is it located?

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev the paper is here, on a different branch: https://github.com/castelao/CoTeDe/tree/joss/joss
What is the process for handling this again? Thanks

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01985/joss.01985/10.21105.joss.01985.pdf)

**Comment by castelao** [comment]
Thanks @Kevin-Mattheus-Moerman . I can merge the joss branch into the master if that helps.

A suggestion of reviewers: efiring and koldunovn

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

-  http://dx.doi.org/10.13155/33951 is OK
- 10.1016/j.mio.2014.09.001 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by castelao** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by castelao** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01985/joss.01985/10.21105.joss.01985.pdf)

**Comment by castelao** [comment]
Hi @Kevin-Mattheus-Moerman  and @danielskatz , do I need to do anything else or just wait? Thanks!

**Comment by danielskatz** [comment]
@castelao - the action is now for @Kevin-Mattheus-Moerman to find reviewers - you don't need to do anything more at this point

**Comment by castelao** [comment]
Great, thanks!

**Comment by danielskatz** [comment]
no, sorry, my mistake - we first need an editor - @Kevin-Mattheus-Moerman started handling this as the rotating associate editor-in-chief, not as the editor

**Comment by danielskatz** [comment]
👋 @kthyng - would you be willing to edit this submission?

**Comment by kthyng** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
@koldunovn and @efiring You've been suggested as a potential reviewer for this submission to the Journal for Open Source Software, which is largely code-review based for software with scientific applications. Are you interested in reviewing this submission? We ask for reviews within about 3 weeks if possible, and you can find more information about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by kthyng** [comment]
@castelao I see that your package is self-described as "old" and doesn't use more modern packages like pandas and xarray. As a potential user of your package but also a pythonista who is trying to stay modern in my code, can you justify this more to me and others? If there is a small amount of work that could make your package at least able to tie into these other packages, that would be hugely useful to the community using your package. A number of other packages have been updating over time to be able to, for example, recognize and use data when it is input as a pandas dataframe or xarray dataarray/dataset.

**Comment by castelao** [comment]
@kthyng, thanks for raising this point. I see CoTeDe as an old package but not outdated. Yes, I also use and appreciate pandas and xarray, so I intend to provide a direct connection to them, but that will be an optional resource, so I do not force more dependencies than required. A few groups and packages already use CoTeDe, and I do not want to impose more dependencies than necessary. For instance, to Quality Control WOD on its binary files, QC a PostgreSQL database or QC directly cnv (CTD) files (https://github.com/castelao/seabird/blob/master/docs/notebooks/QualityControl.ipynb), there is no need for more.

Note that at some point, I changed my standard from .attributes to .attrs to match xarray so that CoTeDe could read directly from a dataset (xarray object). I still need to make a few adjustments to be fully transparent, but I think it is better to keep the CoTeDe data model simple so that a dictionary of np.array or an xr.dataset would both work.

**Comment by koldunovn** [comment]
@kthyng Thank you for the nomination, but I am afraid I can't do it fast due to the huge amount of work and family commitments I have at the moment. Moreover, observations are not really my thing anymore, I am in the modeling business for over 15 years now, and the set of problems is quite different. I suggest to contact @ocefpaf @ledm @zklaus . They have experience in both python and oceanography.

**Comment by kthyng** [comment]
@castelao Thank you for your response. Another possibility would be to check to see if pandas or xarray are installed and then extend possible behavior, or something similar. This happens in cartopy for example, which uses different algorithms if shapely is installed. I agree that simple is good, but it is also good to keep modernizing instead of being held back by old code that users have. Something to keep in mind, anyway.

**Comment by kthyng** [comment]
Thanks for letting me know @koldunovn! 

Hi @ocefpaf @ledm @zklaus! You've all been suggested as possible reviewers for this submission to the Journal for Open Source Software, which is largely code-review based for software with scientific applications. Are you interested in reviewing this submission? We ask for reviews within about 3 weeks if possible, and you can find more information about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

In total, we need two reviewers. Thanks.

**Comment by efiring** [comment]
@kthyng I'm sorry, but I won't be able to help with this.  If you need additional suggestions for reviewers, I suspect @ocefpaf might have good ones.

**Comment by castelao** [comment]
More suggestions for reviewers: ggalibert, gmaze, and paulfvliz.

**Comment by ocefpaf** [comment]
@efiring and @koldunovn thanks for thinking of me.

@kthyng I'm sorry to refuse but I cannot review this in a timely fashion. I just had knee surgery and I'm in bed for 4 weeks following a slow recovery relaying on crutch. The few hours I get in front of the laptop will be for the day job.

**Comment by kthyng** [comment]
@efiring and @ocefpaf Thanks for letting me know! And @ocefpaf I hope your recovery goes well.

**Comment by kthyng** [comment]
@seagrinch and @paulfvliz JOSS is the Journal for Open Source Software, which involves largely code-review based for software with research applications. Are you interested in reviewing this submission? We ask for reviews within about 3 weeks if possible, and you can find more information about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

I'm looking for experience with Python and quality controlling oceanographic data.

In total, we need two reviewers. Thanks.

**Comment by zklaus** [comment]
@kthyng, thanks for the invite, but while I have some python experience, I don't feel qualified on the ocean data quality aspect, so I have to decline.

**Comment by kthyng** [comment]
@zklaus Thanks for your reply.

**Comment by seagrinch** [comment]
@kthyng Like many of us, I'm a bit overloaded in prep for Ocean Sciences, but I can try to take a look. I am intrigued by this repo and curious to see how easy it is to utilize.

**Comment by kthyng** [comment]
@castelao It is true that many of the potential reviewers will be prepping for Ocean Sciences. One option is to push the review back to start at the end of February. What is your preference?

**Comment by castelao** [comment]
@seagrinch , I do appreciate your time. Thank you very much.

@kthyng , I have an invited poster on OS that is related to this package. My preference is to at least try to make it on schedule, but I understand that it requires a lot from you all. Thank you.

**Comment by kthyng** [comment]
@castelao Let's try then.

@seagrinch If you don't think you'll have time, it's probably best to not review. If we end up needing to push back anyway, though, I would probably reach out again in that case.

@gmaze JOSS is the Journal for Open Source Software, which involves largely code-review based for software with research applications. Are you interested in reviewing this submission? We ask for reviews within about 3 weeks if possible, and you can find more information about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

I'm looking for experience with Python and quality controlling oceanographic data.

In total, we need two reviewers. Thanks.

**Comment by gmaze** [comment]
Hi @karthik 
Yes I'd like to review this paper, 
But like many I'll be very busy to the end of February because of the Ocean Sciences meeting (and many other commitments)
So I can't guarantee to finish the review within 3 weeks.
g

**Comment by castelao** [comment]
@gmaze, thanks!

**Comment by kthyng** [comment]
Hi @gmaze, that is certainly a trend right now! 

@callumrollo I see you are on the JOSS reviewer list with an expertise in Marine Technology. Do you work with oceanographic data? This submission to JOSS is about quality control of ocean data so I'm looking for reviewers with this background plus Python expertise. I'm hoping to move through reviews in the next 3 weeks if possible. Any interest?

**Comment by kthyng** [comment]
@castelao I'm willing to keep recruiting reviewers to try to review your submission before Ocean Sciences, but I could use more suggestions. I'd really like to include people with data experience in particular. If you have suggestions, please list them without @-mentioning them here.

@gmaze Just to be clear, I am going to see if I can find reviewers who can work on this sooner, but if not I would like to be able to call on you! Thanks.

**Comment by ocefpaf** [comment]
@kthyng I spoke with Jessica Austin (@jessicaaustin), from Axiom DataScience, and she is willing to review it. Jessica a lot of experience with scientific Software development applied to oceanography and is the lead developer for the IOOS QA/QC QARTOD implementation.

**Comment by kthyng** [comment]
Awesome, thanks @ocefpaf! 

@jessicaaustin JOSS is the Journal for Open Source Software, which involves largely code-review based for software with research applications. Are you interested in reviewing this submission? We ask for reviews within about 3 weeks if possible, and you can find more information about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

I'm looking for experience with Python and quality controlling oceanographic data.

In total, we need two reviewers. Thanks.

**Comment by jessicaaustin** [comment]
@kthyng Yes, I am happy to review this submission

**Comment by kthyng** [comment]
@evanleeturner JOSS is the Journal for Open Source Software, which involves largely code-review based for software with research applications. Are you interested in reviewing this submission? We ask for reviews within about 3 weeks if possible, and you can find more information about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html
I'm looking for one more reviewer! Thanks for your consideration.

**Comment by kthyng** [comment]
Thanks @jessicaaustin! I've also had confirmation by email from @evanleeturner so let's start this review!

**Comment by kthyng** [comment]
@whedon assign @jessicaaustin as reviewer

**Comment by whedon** [comment]
OK, @jessicaaustin is now a reviewer

**Comment by kthyng** [comment]
@whedon add @evanleeturner as reviewer

**Comment by whedon** [comment]
OK, @evanleeturner is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2063.

**Comment by kthyng** [comment]
@jessicaaustin and @evanleeturner Please to go [#2063](https://github.com/openjournals/joss-reviews/issues/2063) for the actual review. You'll find a reviewer checklist for each of you and some instructions. Please open new issues in the software repo and link back to the review issue for items that arise, and let me know if you have any questions!

**Comment by evanleeturner** [comment]
Thanks for the invite.  This is a whole _new experience_ to do a review in github, so bear with me pls!  Looking forward to taking a look at the work.  -evan

**Comment by castelao** [comment]
@jessicaaustin and @evanleeturner, thank you for accepting to review my submission.

@kthyng, I do appreciate your effort and time to keep this review moving forward considering this pre-OSM busy times. Thanks!

@gmaze and @seagrinch, I would be very much interested in hearing any comments or questions that you might have. Please feel free to contact me by opening an issue in the [CoTeDe repository](https://github.com/castelao/CoTeDe) or directly by email. Thanks!

**Comment by callumrollo** [comment]
Hi @kthyng  sorry for missing this, I was at sea for 6 weeks with no internet. Just the kind of thing I would be happy to review in future though. @castelao I'll have a proper dig into the code once I'm caught up on post cruise admin. Looks like an awesome tool!
