### ISSUE TITLE
[REVIEW]: pylustrator: code generation for reproducible figures for publication

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1989]
**Submitting author:** @rgerum (<a href="http://orcid.org/0000-0001-5893-2650">Richard Gerum</a>)
**Repository:** <a href="https://github.com/rgerum/pylustrator" target ="_blank">https://github.com/rgerum/pylustrator</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewer:** @story645, @tacaswell
**Archive:** <a href="https://doi.org/10.5281/zenodo.3952417" target="_blank">10.5281/zenodo.3952417</a>

## Status

[![status](https://joss.theoj.org/papers/3309a22c5481ba2f4d464e5a19872d4c/status.svg)](https://joss.theoj.org/papers/3309a22c5481ba2f4d464e5a19872d4c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3309a22c5481ba2f4d464e5a19872d4c"><img src="https://joss.theoj.org/papers/3309a22c5481ba2f4d464e5a19872d4c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3309a22c5481ba2f4d464e5a19872d4c/status.svg)](https://joss.theoj.org/papers/3309a22c5481ba2f4d464e5a19872d4c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/rgerum/pylustrator" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@story645 & @tacaswell, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @labarba know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rgerum/pylustrator">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@rgerum) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rgerum/pylustrator">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@rgerum) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @story645, @tacaswell it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1109/MCSE.2007.55 is OK
- 10.1038/533452A is OK
- 10.5281/zenodo.883859 is OK
- 10.5860/crl.79.1.2 is OK
- 10.1038/nature.2016.20504 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01989/joss.01989/10.21105.joss.01989.pdf)

**Comment by labarba** [comment]
👋  @story645, @tacaswell — Thank you for agreeing to review for JOSS! This is where the action happens: work your way through the review checklist, feel free to ask questions or post comments here, and also open issues in the submission repository as needed. Godspeed!

**Comment by labarba** [comment]
Hi folks! @story645, @tacaswell — How is your review going? I don't see items ticked off on your checklists. Do you have any questions for us?

**Comment by tacaswell** [comment]
Sorry, I got behind on everything.  Will be done by Monday.

**Comment by tacaswell** [comment]
First, this is a super cool project, I am very impressed with the functionality.

 - Created https://github.com/rgerum/pylustrator/issues/17 to track missing community guide lines
 - This software is primarily a GUI interface to editing Matplotlib figures (which is pretty awesome!) and the intended usage is through the UI, not as a library.  There is not documentation on the API (because there is not one) nor automated tests.   Poking through the code there is a lack of docstrings on a majority of the functions.  While I don't think that it is worth doing a full GUI mock test, I think it would be reasonable to test some of the functionality (such as ensuring the the monkey patching works as expected, that the file patching works as expected for a manually generated change set etc).
 - This sort of user-action-recording functionality exist in several other visualization / image analysis packages (paraview/vtk/and friends, avizo, dragonfly, etc).  I know of no other tool that provides this functionality on top of Matplotlib, however I think that the novelty claim in the conclusions of the paper are too strong.

**Comment by labarba** [comment]
👋 @story645 — It looks like you haven't gotten a start in reviewing this software? We have progress with the second reviewer (Thomas), so I encourage you to come have look now, while the authors may start their revisions.

**Comment by labarba** [comment]
Pinged @story645 via [tweet](https://twitter.com/LorenaABarba/status/1234274680158244864?s=20)

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arfon** [comment]
:wave: @story645, @tacaswell, just a friendly check-in to see how things are going with your reviews?

**Comment by rgerum** [comment]
Dear Editors and Reviewers,
As already quite some time passed since the first review arrived, I now take the liberty to already respond to the first reviewer before the second review is there.

@tacaswell, Thank you very much for the positivity assessment of the package.

>   Created rgerum/pylustrator#17 to track missing community guide lines
- I added a guilde line paragraph to the readme.md file

>  This software is primarily a GUI interface to editing Matplotlib figures (which is pretty awesome!) and the intended usage is through the UI, not as a library. There is not documentation on the API (because there is not one) nor automated tests.
- I added a section to the documentation to document the functions of the package.

> Poking through the code there is a lack of docstrings on a majority of the functions.
- I added small docstrings to the functions and added type hints to improve readability of the code

> While I don't think that it is worth doing a full GUI mock test, I think it would be reasonable to test some of the functionality (such as ensuring the the monkey patching works as expected, that the file patching works as expected for a manually generated change set etc).
- I added an automatic test that test the basic functions of the package: monkey patching and code generation.

> This sort of user-action-recording functionality exist in several other visualization / image analysis packages (paraview/vtk/and friends, avizo, dragonfly, etc). I know of no other tool that provides this functionality on top of Matplotlib, however I think that the novelty claim in the conclusions of the paper are too strong.
- I removed the strong novenlty claim from the paper and referenced paraview, avizo and dragonfly.

Thank you for your comments that helped to improve the software.

**Comment by arfon** [comment]
👋 @story645, @tacaswell - today we [reopened JOSS](https://blog.joss.theoj.org/2020/05/reopening-joss) for new submissions and are checking in on our existing reviews. Do you think you might be able to wrap up your reviews in the next 2-3 weeks?

**Comment by story645** [comment]
Hi, 
I'm so sorry I've totally beyond dropped the ball on this (I hope I've made it up a drop by seriously recommending Pylustrator to just about everyone who's looking for something like it). I hope to get my review done sometime in the next week or so.

**Comment by labarba** [comment]
Thank you, @story645, we really appreciate your contribution, especially on these troubled times!

@tacaswell — you have a few unchecked items in your review checklist. Can you update us on the status of your review? Many thanks 🙏

**Comment by tacaswell** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01989/joss.01989/10.21105.joss.01989.pdf)

**Comment by tacaswell** [comment]
I approve for publication.

**Comment by story645** [comment]
Hi, incredibly sorry my review took so long. Mostly fine, some slight concerns:
1. the documentation homepage is missing a list of major dependencies - I'm not sure if this fits w/ joss guidelines or not
2. the paper needs copy editing (typos, some very clunky constructions) - not sure if this happens before or after the "approve for publication" step
3.  the paragraph starting with `pylustrator tracks all these changes to translate` would be clearer if either the language in it directly matched the figure (for example the figure also had an element labeled `command object`, `target object` etc) or if there was a set of smaller figure walking through these steps.

**Comment by rgerum** [comment]
Thank you for the review.

1. I added a list of dependencies to the documentation page. https://pylustrator.readthedocs.io/en/latest/#installation

2. I did some copy editing of the text.

3. I rewrote this paragraph and I hope it should be more clear now.

You can see the changes to the text here: https://github.com/rgerum/pylustrator/commit/d7cc5d798212c79a54901ad19a71a39a8efbac76

@whedon generate pdf

**Comment by rgerum** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01989/joss.01989/10.21105.joss.01989.pdf)

**Comment by story645** [comment]
thanks @rgerum for your incredible patience, I think the paper is much clearer now. Two more suggestion and then I think it's ready for publication 
missing word: "from this dependency a  object? is generated"
& I think 
"when a file with automatically generated code is loaded, pylustrator splits all the ..." might be a drop clearer if you refer back to figure 1 here to explain what this means.

**Comment by rgerum** [comment]
Thanks for the additional feedback to improve the paper. I changed these two formulations now. I hope that everything is clear now.

**Comment by rgerum** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01989/joss.01989/10.21105.joss.01989.pdf)

**Comment by story645** [comment]
Awesome! I approve for publication.

**Comment by rgerum** [comment]
@labarba it seems the review is now complete, since last week. I would be happy to see the paper published soon.

**Comment by labarba** [comment]
Thanks for the ping, @rgerum — email notification overload on my side.

**Comment by labarba** [comment]
@story645 — we're missing the check on "quality of writing." did you find issues there?

**Comment by labarba** [comment]
@rgerum — I see the last tag release on the repo is v0.14.0 from Feb., so I think you will need a new tagged release with all changes to day. Please report the version number here.

**Comment by rgerum** [comment]
ah ok, yes, good idea. I

**Comment by labarba** [comment]
I'm reading the paper now, and have minor edits to suggest, which I could enter easily as a PR on the markdown. Before I proceed: I recommend swapping the term "evaluation" for "analysis" in the Background section.

**Comment by rgerum** [comment]
Thanks for the suggestion, I changed "evaluation" for "analysis".

**Comment by labarba** [comment]
@whedon set v1.0.0 as version

**Comment by whedon** [comment]
OK. v1.0.0 is the version.

**Comment by rgerum** [comment]
I have added the pull request. Luckily Github has a nice diff display for markdown now! I found an additional typo which I corrected. Thank you for improving the paper text.

**Comment by labarba** [comment]
@story645 — I've checked the last item for you, as I edited the writing myself now.

@rgerum — please now make an archive of your software repository on Zenodo, edit the Zenodo metadata so the title and author list matches the JOSS paper, and report the archive DOI here.

**Comment by rgerum** [comment]
@labarba I created an archived version on Zenodo:
http://doi.org/10.5281/zenodo.3952417

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.3952417 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3952417" target="_blank">10.5281/zenodo.3952417</a> is the archive.

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/MCSE.2007.55 is OK
- 10.1038/533452A is OK
- 10.5281/zenodo.883859 is OK
- 10.5860/crl.79.1.2 is OK
- 10.1038/nature.2016.20504 is OK

MISSING DOIs

- https://doi.org/10.1016/b978-012387582-2/50038-1 may be missing for title: Paraview: An end-user tool for large data visualization

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1582

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1582, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01989/joss.01989/10.21105.joss.01989.pdf)

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1285307745739182080) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1583
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01989](https://doi.org/10.21105/joss.01989)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @rgerum, your JOSS paper is published! 🚀 

Huge thanks to our reviewers: @story645, @tacaswell — we couldn't do this without you 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01989/status.svg)](https://doi.org/10.21105/joss.01989)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01989">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01989/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01989/status.svg
   :target: https://doi.org/10.21105/joss.01989
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01989/status.svg)](https://doi.org/10.21105/joss.01989)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
