### ISSUE TITLE
[PRE REVIEW]: Weave.jl: Scientific Reports Using Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#199]
**Submitting author:** @mpastell (<a href="http://orcid.org/0000-0002-5810-4801">Matti Pastell</a>)
**Repository:** <a href="https://github.com/mpastell/weave.jl" target ="_blank">https://github.com/mpastell/weave.jl</a>
**Version:** v0.4.0
**Editor:** @arfon
**Reviewer:** @vchuravy

**What this issue is for**

Thanks for submitting your paper to JOSS @mpastell. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: @vchuravy - would you be willing to review this submission for JOSS?

**Comment by vchuravy** [comment]
Will do.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @vchuravy as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @vchuravy

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/204. Feel free to close this issue now!

**Comment by arfon** [comment]
> Will do.

👍 many thanks @vchuravy. Please head over to #204 to actually carry out the review.
