### ISSUE TITLE
[REVIEW]: NCBImeta: efficient and comprehensive metadata retrieval from NCBI databases

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1990]
**Submitting author:** @ktmeaton (<a href="http://orcid.org/0000-0001-6862-7756">Katherine Eaton</a>)
**Repository:** <a href="https://github.com/ktmeaton/NCBImeta" target ="_blank">https://github.com/ktmeaton/NCBImeta</a>
**Version:** v0.6.3
**Editor:** @lpantano
**Reviewer:** @coughls, @druvus
**Archive:** <a href="https://doi.org/10.5281/zenodo.3627329" target="_blank">10.5281/zenodo.3627329</a>

## Status

[![status](https://joss.theoj.org/papers/72376aa12ddf832465c92490b2074e7b/status.svg)](https://joss.theoj.org/papers/72376aa12ddf832465c92490b2074e7b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/72376aa12ddf832465c92490b2074e7b"><img src="https://joss.theoj.org/papers/72376aa12ddf832465c92490b2074e7b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/72376aa12ddf832465c92490b2074e7b/status.svg)](https://joss.theoj.org/papers/72376aa12ddf832465c92490b2074e7b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ktmeaton/NCBImeta" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@coughls & @druvus, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ktmeaton/NCBImeta">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ktmeaton) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ktmeaton/NCBImeta">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ktmeaton) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @coughls, @druvus it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1186/1471-2105-14-19 is OK
- 10.1093/bioinformatics/btx334 is OK
- 10.1186/s12859-016-1231-2 is OK
- 10.12688/f1000research.18676.1 is OK
- 10.7554/eLife.07335 is OK
- 10.1371/journal.pone.0077910 is OK
- 10.1057/biosoc.2015.22 is OK
- 10.1093/bioinformatics/btp163 is OK
- 10.1111/2049-632X.12107 is OK
- 10.1093/jac/dks261 is OK
- 10.1128/mBio.01721-14 is OK

MISSING DOIs

- https://doi.org/10.1007/springerreference_36064 may be missing for title: NCBI

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01990/joss.01990/10.21105.joss.01990.pdf)

**Comment by ktmeaton** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01990/joss.01990/10.21105.joss.01990.pdf)

**Comment by ktmeaton** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1186/1471-2105-14-19 is OK
- 10.1093/bioinformatics/btx334 is OK
- 10.1186/s12859-016-1231-2 is OK
- 10.12688/f1000research.18676.1 is OK
- 10.7554/eLife.07335 is OK
- 10.1371/journal.pone.0077910 is OK
- 10.1057/biosoc.2015.22 is OK
- 10.1093/bioinformatics/btp163 is OK
- 10.1111/2049-632X.12107 is OK
- 10.1093/jac/dks261 is OK
- 10.1128/mBio.01721-14 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by ktmeaton** [comment]
I removed the redundant website reference NCBI (n.d.) which was flagged as MISSING DOIs. The information contained in Table 1 comes from Entrez Help (2016) which is a more substantial source.

**Comment by ktmeaton** [comment]
I’ve updated the repositories Issues and Pull Requests, thank you @druvus for creating the bioconda recipe! Apologies for the delay, I just needed some time to research and experiment with how conda integration will work for long-term support.

**Comment by druvus** [comment]
@lpantano @ktmeaton I am happy with improved version of the software. Everything looks good to me.

**Comment by lpantano** [comment]
@coughls, you have almost checked everything, but I am not sure the things are left needs to be addressed by the authors or not, could you update on that, please? Thanks a lot!

**Comment by coughls** [comment]
@lpantano @ktmeaton I am finished my review now and did not find anything that needed to be addressed so I am happy with it. Thanks.

**Comment by lpantano** [comment]
@openjournals/joss-eics, this is almost there, but can somebody double-check the size of the paper will be good and not too long. One I did in the past was too long and we needed to update the archive and the version at the very last step. Trying to avoid that. Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@lpantano thanks for your comment. I think the paper looks fine. It is slightly long but it look likes it needs the length to treat the components asked for and there are no sections/paragraphs (as far as I could tell from having a glance at the paper) that should be removed (e.g. if they would double documentation content). 
You said "almost there", are there further developments we are waiting for? Let me know if this is ready to be processed for publication. Thanks.

**Comment by lpantano** [comment]
Thanks @Kevin-Mattheus-Moerman, I just need to make sure to have the archive and the version correct. 

@ktmeaton, could you create a Zenodo archive of your repo for the current version and give me the doi? Please make sure the title and authors match the paper exactly. And that will be all if nothing happens. :)

**Comment by ktmeaton** [comment]
Thank you for checking on the length requirements of the paper!

I've updated the most recent Zenodo archive to make sure the title, authors, and ORCID match the paper. The final repo version after review is 0.6.3 and the DOI is 10.5281/zenodo.3627329

**Comment by lpantano** [comment]
@whedon set v0.6.3 as version

**Comment by whedon** [comment]
OK. v0.6.3 is the version.

**Comment by lpantano** [comment]
@whedon set 10.5281/zenodo.3627329 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3627329" target="_blank">10.5281/zenodo.3627329</a> is the archive.

**Comment by lpantano** [comment]
@openjournals/joss-eics, we have all set up on our side now, I think :) Let us know.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01990/joss.01990/10.21105.joss.01990.pdf)

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1186/1471-2105-14-19 is OK
- 10.1093/bioinformatics/btx334 is OK
- 10.1186/s12859-016-1231-2 is OK
- 10.12688/f1000research.18676.1 is OK
- 10.7554/eLife.07335 is OK
- 10.1371/journal.pone.0077910 is OK
- 10.1057/biosoc.2015.22 is OK
- 10.1093/bioinformatics/btp163 is OK
- 10.1111/2049-632X.12107 is OK
- 10.1093/jac/dks261 is OK
- 10.1128/mBio.01721-14 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1263

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1263, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1224457695291375617) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1264
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01990](https://doi.org/10.21105/joss.01990)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Congratulations to @ktmeaton on your new paper! Thanks very much to @lpantano for editing and to reviewers @coughls and @druvus — we appreciate your time and expertise.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01990/status.svg)](https://doi.org/10.21105/joss.01990)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01990">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01990/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01990/status.svg
   :target: https://doi.org/10.21105/joss.01990
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01990/status.svg)](https://doi.org/10.21105/joss.01990)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by kthyng** [comment]
Oops I shouldn't have closed that before the doi rectifies. I will check back for that.

**Comment by arfon** [comment]
Looks like the DOI is resolving now @kthyng

**Comment by ktmeaton** [comment]
Thank you so much @lpantano for editing this submission and @coughls and @druvus for your reviews. I greatly appreciate your time and effort!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01990/status.svg)](https://doi.org/10.21105/joss.01990)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01990">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01990/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01990/status.svg
   :target: https://doi.org/10.21105/joss.01990
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01990/status.svg)](https://doi.org/10.21105/joss.01990)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
