### ISSUE TITLE
[REVIEW]: Cocktail Shaker: An open source drug expansion and enumeration library for peptides

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1992]
**Submitting author:** @Sulstice (<a href="http://orcid.org/0000-0002-1342-9258">Suliman Sharif</a>)
**Repository:** <a href="https://github.com/Sulstice/cocktail-shaker" target ="_blank">https://github.com/Sulstice/cocktail-shaker</a>
**Version:** 1.1.8
**Editor:** @csoneson
**Reviewers:** @olivertomic, @richardjgowers
**Archive:** <a href="https://doi.org/10.5281/zenodo.3981540" target="_blank">10.5281/zenodo.3981540</a>

## Status

[![status](https://joss.theoj.org/papers/c2e1d3c408a5729d832b34ac680d6305/status.svg)](https://joss.theoj.org/papers/c2e1d3c408a5729d832b34ac680d6305)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c2e1d3c408a5729d832b34ac680d6305"><img src="https://joss.theoj.org/papers/c2e1d3c408a5729d832b34ac680d6305/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c2e1d3c408a5729d832b34ac680d6305/status.svg)](https://joss.theoj.org/papers/c2e1d3c408a5729d832b34ac680d6305)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Sulstice/cocktail-shaker" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@floux & @olivertomic, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Sulstice/cocktail-shaker">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Sulstice) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Sulstice/cocktail-shaker">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Sulstice) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Sulstice/cocktail-shaker">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Sulstice) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @floux, @olivertomic it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1111/cbdd.12055 is OK
- 10.4155/tde.13.104 is OK
- 10.1093/nargab/lqz004 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01992/joss.01992/10.21105.joss.01992.pdf)

**Comment by csoneson** [comment]
👋@floux, @olivertomic - thanks for accepting to review this submission. This is where the review happens! Please see the instructions in the first post above, and don't hesitate to ping me if you have questions. 

@Sulstice - please have a look at the reviewer checklists above. If you notice something missing from your submission, you can add it already now to simplify the review process.

**Comment by csoneson** [comment]
@whedon remind @olivertomic in 6 weeks

**Comment by whedon** [comment]
Reminder set for @olivertomic in 6 weeks

**Comment by csoneson** [comment]
👋@floux - just checking in on your review. Do you have an estimate of when you think you'll be able to provide some feedback for @Sulstice? Of course, don't hesitate to ping me if you have questions.

**Comment by csoneson** [comment]
I have sent three follow-up emails to @floux but not received any reply. At this point, I will therefore start looking for a replacement reviewer for this submission.

**Comment by csoneson** [comment]
👋 @greglandrum - would you be interested in reviewing this submission for the Journal of Open Source Software (JOSS)? 

> Cocktail Shaker: An open source drug expansion and enumeration library for peptides

Cocktail Shaker is a python package for exploring, expanding, and synthesizing chemical peptide data, operating within the RDKit platform. 

Software: https://github.com/Sulstice/cocktail-shaker
Short accompanying paper: https://github.com/openjournals/joss-papers/blob/joss.01992/joss.01992/10.21105.joss.01992.pdf

JOSS reviews are performed openly on GitHub and are based on a checklist that can be found here: https://joss.readthedocs.io/en/latest/review_checklist.html
Additional information about reviewing for JOSS is available via https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by greglandrum** [comment]
@csoneson - Sure; I can give this a try.

**Comment by csoneson** [comment]
@greglandrum - brilliant, thank you! I will add you as a reviewer and add a checklist for you in the first post above (there are also some additional instructions). Don't hesitate to ping me if you have any questions.

**Comment by csoneson** [comment]
@whedon add @greglandrum as reviewer

**Comment by whedon** [comment]
OK, @greglandrum is now a reviewer

**Comment by greglandrum** [comment]
@csoneson - just to confirm: should I directly complete the checklist above or make a copy in a comment?

**Comment by csoneson** [comment]
@greglandrum Please directly fill the checklist in the first post above so that we have a summary in one place. 
You can then comment on individual items/aspects in separate comments (or open issues in the software repository and just mention them here).

**Comment by whedon** [comment]
:wave: @olivertomic, please update us on how your review is going.

**Comment by olivertomic** [comment]
I must admit that I am not sure any longer whether I am supposed to review the manuscript or not. 4 days ago whedon assigned me and then unassigned me and I interpreted this as being out. Or is it the other way around?

**Comment by danielskatz** [comment]
Yes, you should - the action @whedon took was, in the process of adding a reviewer, to unassign you than to reassign you.

**Comment by olivertomic** [comment]
OK, thanks for the update. I plan to start reviewing within a weeks time.

**Comment by csoneson** [comment]
> OK, thanks for the update. I plan to start reviewing within a weeks time.

@olivertomic - did you have a chance to start your review of this submission?

**Comment by olivertomic** [comment]
@csoneson - starting today.

**Comment by Sulstice** [comment]
@csoneson I updated per some of the requests from @greglandrum so there should be updates to some of the initial README and installation instructions. Please let me know if it isn't clear. For making the package a conda installable it will take some time (as I figure out how).

**Comment by csoneson** [comment]
@olivertomic - any update on your review?
> @csoneson - starting today.

**Comment by csoneson** [comment]
@olivertomic - please update us on the status of your review.

**Comment by olivertomic** [comment]
@csoneson In progress. Please see the checked boxes above.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arfon** [comment]
:wave: @floux, @olivertomic, @greglandrum, just a friendly check-in to see how things are going with your reviews?

**Comment by Sulstice** [comment]
@arfon I have a blocker on oliver temporarily with a dependency issue on the package that we discovered last week. I need to apply a fix ASAP to the package. Sorry about the delay (had a lot of craziness happening with corona for work)

**Comment by olivertomic** [comment]
@arfon I am in touch with @Sulstice regarding examples of how to run the software. Work in progress. :-)

**Comment by arfon** [comment]
👍 thanks for the updates @Sulstice and @olivertomic.

**Comment by arfon** [comment]
:wave: @Sulstice and @olivertomic - today we [reopened JOSS](https://blog.joss.theoj.org/2020/05/reopening-joss) for new submissions and are checking in on our existing reviews. Do you think you might be able to wrap up this dicsussion in the next 2-3 weeks?

**Comment by Sulstice** [comment]
Yes! I am making a little more interactive examples of how to use Cocktail Shaker per as @olivertomic suggestions (i.e juptyer notebooks or a gitpod) I am aiming for this saturday may 23rd (free time) to wrap that up. 

I believe I tackled nearly all the issues attached with the repo filed from both greg and oliver and should be good to go unless I missed something (please let me know!).

**Comment by Sulstice** [comment]
I added jupyter notebook examples for each of the apis with some more documentation into how it works with examples. I also added a litle ascii cinema in the README file for a quick visibility so someone can see if they would like to pip install it prior. 

If there is anything else let me know!

**Comment by csoneson** [comment]
Just checking in here - @Sulstice, do I interpret your message above correctly in that you have addressed the issues raised by the reviewers and are ready for a re-review?

**Comment by Sulstice** [comment]
Yep I am ready for a re-review!

**Comment by csoneson** [comment]
Great - @olivertomic, @greglandrum, could you please have a look at the updated submission and let us know what you think? Thanks!

**Comment by olivertomic** [comment]
I am happy to approve the paper for publication. @Sulstice , and @csoneson . Just a minor change would be requried in paper.md itself. 

The text says: ´Cocktail Shaker´ consists of **four** major class objects available to the user: PeptideMolecule, CocktailShaker, and FileWriter.´

However, only three are mentioned.

@Sulstice , thank you for the collaboration and implementation of suggestions.

**Comment by Sulstice** [comment]
Yes you are definitely right, kind of an artifact of time of submission and me updating the modules. I will fix that later today!

**Comment by olivertomic** [comment]
Excellent @Sulstice ! I am happy to recommend publication of the paper.

**Comment by csoneson** [comment]
@greglandrum - could you give us an update on the status of your review? Thanks!

**Comment by csoneson** [comment]
Ping @greglandrum 
> @greglandrum - could you give us an update on the status of your review? Thanks!

**Comment by csoneson** [comment]
👋 @Sulstice - in order to move this review process forward, I have decided to invite a fourth reviewer, who has agreed to take a first look shortly (thanks @richardjgowers!)

**Comment by csoneson** [comment]
@whedon add @richardjgowers as reviewer

**Comment by whedon** [comment]
OK, @richardjgowers is now a reviewer

**Comment by csoneson** [comment]
@whedon remove @floux as reviewer

**Comment by whedon** [comment]
OK, @floux is no longer a reviewer

**Comment by Sulstice** [comment]
@richardjgowers Let me know if there is anything I need to do!

**Comment by richardjgowers** [comment]
@Sulstice the comment before about mentioning 4 classes but then listing 3 of them is still valid.

**Comment by Sulstice** [comment]
@richardjgowers Sorry! I don't know what happened to that fix I had (maybe forgot to commit). I resolved your issue as well - passed tests and released a 1.1.6 release. Let me know if there is anything else!

**Comment by csoneson** [comment]
@whedon remove @greglandrum as reviewer

**Comment by whedon** [comment]
OK, @greglandrum is no longer a reviewer

**Comment by richardjgowers** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01992/joss.01992/10.21105.joss.01992.pdf)

**Comment by richardjgowers** [comment]
@Sulstice minor point, RDKit is written in C++ not C.  The paper references 3D generation using webchem, I can't find any references to this in the documentation?

**Comment by Sulstice** [comment]
@richardjgowers Good point, I'll fix immediately.

Huh, I actually didn't mention how the FileWriter module works. It's another cirpy (https://github.com/mcs07/CIRpy) under the hood (but more robust) hitting the NIH cactus resolver. I'm going to add that to the docs for how the FileWriter works - does that suffice?

**Comment by Sulstice** [comment]
I added it in the docs a little bit here: https://cocktail-shaker.readthedocs.io/en/latest/guide/file_handling.html#the-filewriter-module

**Comment by csoneson** [comment]
@richardjgowers - did you have a chance to look over @Sulstice's fixes? Thanks!

**Comment by richardjgowers** [comment]
@Sulstice the [mol2 parser](https://github.com/Sulstice/cocktail-shaker/blob/master/cocktail_shaker/file_handler.py#L290) seems like it might not work as advertised in the docs.  Similarly [there's two method here](https://github.com/Sulstice/cocktail-shaker/blob/master/cocktail_shaker/peptide_builder.py#L161) that look like they're yet to be implemented.  If they're not done yet put up a `NotImplementedError` or just remove them.

**Comment by Sulstice** [comment]
Hey @richardjgowers Thanks for finding those ->

**Comment by csoneson** [comment]
@richardjgowers - do you have any additional comments for @Sulstice? Thanks!

**Comment by csoneson** [comment]
ping @richardjgowers 
> @richardjgowers - do you have any additional comments for @Sulstice? Thanks!

**Comment by richardjgowers** [comment]
@csoneson yes I'm happy now, thanks for your patience!

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.01992/joss.01992/10.21105.joss.01992.pdf)

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1111/cbdd.12055 is OK
- 10.4155/tde.13.104 is OK
- 10.1093/nargab/lqz004 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
👋 @Sulstice - I have made a pull request to your repository with a few small fixes to the paper and the bib file. Could you please check that they look ok, that I didn't misinterpret anything, and merge it. Please also clarify this sentence in the introduction, I'm not quite sure how to interpret it: 

>  With increasing interest eludes to increasing high throughput screening of peptides computationally.

**Comment by Sulstice** [comment]
@csoneson All merged in!

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.01992/joss.01992/10.21105.joss.01992.pdf)

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1111/cbdd.12055 is OK
- 10.4155/tde.13.104 is OK
- 10.1093/nargab/lqz004 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@Sulstice - the paper looks good! Here are the next steps:

- [ ] Create a tagged release of the software, and report back the version tag here
- [ ] Archive the release in Zenodo
- [ ] Check that the Zenodo archive has the same title and author list as the paper. 
- [ ] Report back the Zenodo DOI here

**Comment by Sulstice** [comment]
@csoneson 

 Version: 1.1.8 
 DOI: 10.5281/zenodo.3981540

**Comment by csoneson** [comment]
Thanks. Could you please fix the metadata of the Zenodo archive so that it has the same title and author list as the JOSS paper. 
Also, the paper says that "it will now be released with version 1.1.0", while the current version is 1.1.8 - I would suggest changing the formulation in the paper to avoid confusion.

**Comment by Sulstice** [comment]
Alright, should be done! does that all work out?

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.01992/joss.01992/10.21105.joss.01992.pdf)

**Comment by csoneson** [comment]
@whedon set 10.5281/zenodo.3981540 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3981540" target="_blank">10.5281/zenodo.3981540</a> is the archive.

**Comment by csoneson** [comment]
@whedon set 1.1.8 as version

**Comment by whedon** [comment]
OK. 1.1.8 is the version.

**Comment by csoneson** [comment]
Looks good!

**Comment by csoneson** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1111/cbdd.12055 is OK
- 10.4155/tde.13.104 is OK
- 10.1093/nargab/lqz004 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1640

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1640, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
Hi @Sulstice, I'm doing some final review steps—can you add more info to the RDKit citation? It looks like you can add either a DOI for the most recent version (https://zenodo.org/record/3981263), or for all versions (10.5281/zenodo.591637)

**Comment by Sulstice** [comment]
@kyleniemeyer Done :) I added the DOI for all versions and in the docs a `RDKit 2019.09.1+` -> ran tests on latest RDKit 2020 release and passing.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.01992/joss.01992/10.21105.joss.01992.pdf)

**Comment by kyleniemeyer** [comment]
@Sulstice thanks! looks good

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1295413280555651073) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1646
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01992](https://doi.org/10.21105/joss.01992)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @Sulstice on your article's publication in JOSS!

Many thanks to @olivertomic and @richardjgowers for reviewing this, and @csoneson for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01992/status.svg)](https://doi.org/10.21105/joss.01992)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01992">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01992/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01992/status.svg
   :target: https://doi.org/10.21105/joss.01992
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01992/status.svg)](https://doi.org/10.21105/joss.01992)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by Sulstice** [comment]
Thank you guys! @csoneson you really helped make this process pretty simple!
