### ISSUE TITLE
[PRE REVIEW]: CMasher: Scientific colormaps for making accessible, informative and 'cmashing' plots

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1993]
**Submitting author:** @1313e (<a href="http://orcid.org/0000-0002-1559-9832">Ellert van der Velden</a>)
**Repository:** <a href="https://github.com/1313e/CMasher" target ="_blank">https://github.com/1313e/CMasher</a>
**Version:** v1.2.0
**Editor:** @mbobra
**Reviewers:** @tacaswell, @wafels

**Author instructions**

Thanks for submitting your paper to JOSS @1313e. **Currently, there isn't an JOSS editor assigned** to your paper.

@1313e if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.3847/1538-4365/ab1f7d is OK
- 10.21105/joss.01229 is OK
- 10.21105/joss.01399 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.5281/zenodo.3378106 is OK
- 10.5281/zenodo.1214904 is OK
- 10.1371/journal.pone.0199239 is OK
- 10.1063/1.4822401 is OK
- 10.1109/VISUAL.2002.1183788 is OK
- 10.1109/TVCG.2017.2744359 is OK
- 10.1080/15230406.2016.1140074 is OK
- 10.1364/JOSAA.29.000313 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01993/joss.01993/10.21105.joss.01993.pdf)

**Comment by tacaswell** [comment]
I will review this once it has an editor.

**Comment by danielskatz** [comment]
👋 @mbobra - would you be willing to edit this submission for JOSS? (Note that one reviewer has already volunteered)

**Comment by mbobra** [comment]
@whedon assign @mbobra as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by 1313e** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1993 with the following error: 

 Error producing PDF.
! LaTeX Error: Environment cslreferences undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.458 \begin{cslreferences}

Looks like we failed to compile the PDF

**Comment by 1313e** [comment]
Oh, I guess I cannot use references in figure captions.

**Comment by 1313e** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1993 with the following error: 

 Error producing PDF.
! LaTeX Error: Environment cslreferences undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.458 \begin{cslreferences}

Looks like we failed to compile the PDF

**Comment by 1313e** [comment]
Guess that is not the issue.
@mbobra Any ideas?

**Comment by danielskatz** [comment]
👋 @arfon - can you see the problem here?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01993/joss.01993/10.21105.joss.01993.pdf)

**Comment by arfon** [comment]
> 👋 @arfon - can you see the problem here?

Sorry, this was an unintended side effect of upgrading Pandoc last night. It's now fixed.

**Comment by mbobra** [comment]
@whedon assign @tacaswell as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @tacaswell

**Comment by mbobra** [comment]
@whedon add @wafels as reviewer

**Comment by whedon** [comment]
OK, @wafels is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2004. Feel free to close this issue now!
