### ISSUE TITLE
[PRE REVIEW]: vfi: Classification by Voting Feature Intervals 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1996]
**Submitting author:** @chkoar (<a href="http://orcid.org/0000-0002-5021-1442">Christos K. Aridas</a>)
**Repository:** <a href="https://github.com/chkoar/vfi" target ="_blank">https://github.com/chkoar/vfi</a>
**Version:** 0.0.1
**Editor:** @mbobra
**Reviewers:** @jakryd, @dflemin3

**Author instructions**

Thanks for submitting your paper to JOSS @chkoar. The JOSS editor @mbobra, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@chkoar if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mbobra it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.07 s (294.3 files/s, 15714.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
reStructuredText                 5             76             59            281
Python                           9            102            118            260
Markdown                         1              5              0             39
TeX                              1              2              0             34
YAML                             2              4              0             33
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            20            201            185            682
-------------------------------------------------------------------------------
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01996/joss.01996/10.21105.joss.01996.pdf)

**Comment by danielskatz** [comment]
👋 @mbobra - sorry again, I started this as assigned to you without checking first.  Are you able to edit it?  If not, I will find someone else.

**Comment by mbobra** [comment]
I am happy to edit, @danielskatz!

**Comment by mbobra** [comment]
@whedon assign @jakryd as reviewer

**Comment by whedon** [comment]
OK, @jakryd is now a reviewer

**Comment by mbobra** [comment]
@whedon add @dflemin3 as reviewer

**Comment by whedon** [comment]
OK, @dflemin3 is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2005. Feel free to close this issue now!
