### ISSUE TITLE
[PRE REVIEW]: FGTpartitioner: A rapid method for parsimonious delimitation of ancestry breakpoints in large genome-wide SNP datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1997]
**Submitting author:** @tkchafin (<a href="http://orcid.org/0000-0001-8687-5905">Tyler Chafin</a>)
**Repository:** <a href="https://github.com/tkchafin/FGTpartitioner" target ="_blank">https://github.com/tkchafin/FGTpartitioner</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @tkchafin. **Currently, there isn't an JOSS editor assigned** to your paper.

@tkchafin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (291.9 files/s, 40867.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           2             77            145            370
Markdown                         3             85              0            309
Cython                           1             16             18            120
TeX                              1              0              0            104
Bourne Shell                     2              2              0             14
-------------------------------------------------------------------------------
SUM:                             9            180            163            917
-------------------------------------------------------------------------------
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1534/genetics.109.103010 is OK
- 10.1038/s41559-018-0611-6 is OK
- 10.1186/1479-7364-7-1 is OK
- 10.1126/sciadv.1501714 is OK
- 10.1145/1854776.1854788 is OK
- 10.1093/bioinformatics/btr330 is OK
- 10.3390/genes9030123 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01997/joss.01997/10.21105.joss.01997.pdf)

**Comment by danielskatz** [comment]
👋 @tkchafin - The "Do What The Fuck You Want To Public License" is not an OSI-approved license, so I am going to reject this from JOSS

If you want to change the license to an OSI-approved one, please feel free to resubmit at that time.  If not, I hope you will be able to find another suitable publication venue.

(and sorry for delay in processing this, due to the holidays)

**Comment by tkchafin** [comment]
Oops- sorry about that... Changed to GPL3 and resubmitted. Thanks for the opportunity to correct this. 😅
