### ISSUE TITLE
[PRE REVIEW]: pyGOURGS - global optimization of n-ary tree representable problems using uniform random global search

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1998]
**Submitting author:** @pySRURGS (<a href="http://orcid.org/0000-0002-3050-8943">Sohrab Towfighi</a>)
**Repository:** <a href="https://github.com/pySRURGS/pyGOURGS" target ="_blank">https://github.com/pySRURGS/pyGOURGS</a>
**Version:** 0.1
**Editor:** @arokem
**Reviewers:** @iljah, @nicoguaro

**Author instructions**

Thanks for submitting your paper to JOSS @pySRURGS. **Currently, there isn't an JOSS editor assigned** to your paper.

@pySRURGS if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (251.9 files/s, 60095.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             1            256              0           2817
Python                           9            207            447            832
SVG                              4              2              2            194
Markdown                         2             32              0            106
TeX                              1              5              0             65
Mako                             2              1              0             28
YAML                             1              0              1             12
Bourne Shell                     1              0              0              2
-------------------------------------------------------------------------------
SUM:                            21            503            450           4056
-------------------------------------------------------------------------------
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1998 with the following error: 

 ORCID looks to be the wrong length
/app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon.rb:153:in `block in check_orcids': Problem with ORCID (https://orcid.org/0000-0002-3050-8943) for Sohrab Towfighi (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon.rb:151:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon.rb:151:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon.rb:88:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1186/s13040-018-0164-x is OK
- 10.1287/moor.6.1.19 is OK

MISSING DOIs

- https://doi.org/10.21105/joss.01675 may be missing for title: pySRURGS-a python package for symbolic regression by uniform random global search

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @arokem - would you be willing to edit this submission?

**Comment by pySRURGS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01998/joss.01998/10.21105.joss.01998.pdf)

**Comment by danielskatz** [comment]
👋 @arokem - a second ping...

**Comment by arokem** [comment]
Yes. I can take this one.

**Comment by arokem** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by pySRURGS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #1998 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1998/papers/JOSS/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arokem** [comment]
Hmm. Looks like I broke things in my PR (https://github.com/pySRURGS/pyGOURGS/pull/1). But it wasn't working before either (the title was mis-rendered and the bibliography wasn't rendering)

**Comment by pySRURGS** [comment]
I'll figure this out by end of today. Please leave to me.

**Comment by pySRURGS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01998/joss.01998/10.21105.joss.01998.pdf)

**Comment by pySRURGS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01998/joss.01998/10.21105.joss.01998.pdf)

**Comment by pySRURGS** [comment]
@whedon generate pdf

**Comment by arokem** [comment]
👍 In the meanwhile, could you please recommend potential reviewers for this article? There is a list of potential reviewers [here](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing), but feel free to suggest other people as well. Please _do not_ tag these people into this issue for now, but provide their GitHub user-name (_without_ the `@` sign)

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01998/joss.01998/10.21105.joss.01998.pdf)

**Comment by pySRURGS** [comment]
Consider hausen and trallard

**Comment by pySRURGS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01998/joss.01998/10.21105.joss.01998.pdf)

**Comment by arokem** [comment]
Unfortunately, these proposed reviewers are both currently reviewing other submissions. Let me see if I can find some other appropriate reviewers in our pool.

**Comment by arokem** [comment]
👋 @andim: would you be willing to review this paper for JOSS?

**Comment by arokem** [comment]
👋 @rowanc1 : would you be willing to review this paper for JOSS?

**Comment by pySRURGS** [comment]
@arokem Can you try different reviewers?

**Comment by arokem** [comment]
@fernandoandreotti : would you be willing to review this paper for JOSS?

**Comment by arokem** [comment]
👋 @sarats :  Would you be willing to review this paper for JOSS?

**Comment by arokem** [comment]
I apologize for how long this has taken. Let me try finding alternative reviewers.

**Comment by arokem** [comment]
@nicoguaro : would you be willing to review this article for JOSS?

**Comment by arokem** [comment]
@iljah : would you be willing to review this article for JOSS?

**Comment by iljah** [comment]
@arokem I can review

**Comment by nicoguaro** [comment]
@arokem, I could give it a try but I think that I might not provide much feedback in the technical parts of the package.

**Comment by arokem** [comment]
@whedon assign @iljah as reviewer

**Comment by whedon** [comment]
OK, @iljah is now a reviewer

**Comment by arokem** [comment]
@whedon add @nicoguaro as reviewer

**Comment by whedon** [comment]
OK, @nicoguaro is now a reviewer

**Comment by arokem** [comment]
Thanks @iljah and @nicoguaro for taking this on! I will start the review with you two. If we find that we need another reviewer for the technical parts of the work, I will add another one at that point.

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2074.
