### ISSUE TITLE
[PRE REVIEW]: thresholdmodeling: A Python package for modeling excesses over a threshold using the Peak-Over-Threshold Method and the Generalized Pareto Distribution

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1999]
**Submitting author:** @iagolemos1 (<a href="http://orcid.org/0000-0002-5829-7711">Iago Lemos</a>)
**Repository:** <a href="https://github.com/iagolemos1/thresholdmodeling" target ="_blank">https://github.com/iagolemos1/thresholdmodeling</a>
**Version:** v0.0.1
**Editor:** @drvinceknight
**Reviewers:** @bahung, @kellieotto

**Author instructions**

Thanks for submitting your paper to JOSS @iagolemos1. **Currently, there isn't an JOSS editor assigned** to your paper.

@iagolemos1 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (204.4 files/s, 21598.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5             92             67            438
Markdown                         3             73              0            161
TeX                              1             10              0            110
-------------------------------------------------------------------------------
SUM:                             9            175             67            709
-------------------------------------------------------------------------------
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-1-4471-3675-0 is OK
- 10.1016/S0309-1708(02)00056-8 is OK
- 10.1017/CBO9780511529443 is OK
- 10.6028/jres.099.028 is OK
- 10.5194/os-2016-47 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01999/joss.01999/10.21105.joss.01999.pdf)

**Comment by danielskatz** [comment]
👋 @drvinceknight - are you willing to edit this JOSS submission?

**Comment by drvinceknight** [comment]
Yup happy to :+1:

**Comment by drvinceknight** [comment]
@whedon assign @drvinceknight  as editor

**Comment by whedon** [comment]
OK, the editor is @drvinceknight

**Comment by drvinceknight** [comment]
@iagolemos1 some initial comments after a brief scan through the [pdf](https://github.com/openjournals/joss-papers/blob/joss.01999/joss.01999/10.21105.joss.01999.pdf):

- The `url = ` does not fit on the page
- The paper is a bit on the long side for a joss submission, but this is mainly taken up by graphics. Would these be better suited in documentation with a single minimal example in the paper perhaps (at the moment your documentation in the README is sparse)? The installation instructions do not need to be in the paper either. You can see a list of the criteria for review here: https://openjournals.readthedocs.io/en/latest/review_criteria.html and published papers here: https://joss.theoj.org

Regarding reviewers do you have any suggestions?

**Comment by iagolemos1** [comment]
Ok, Dr. Vince. I am going to make the changes. The README leads to the package documentation. Hence, I think it will be better to put the graphics in the README and just some of them in the paper for a little example. I am going to take the installation instructions out too. 
For reviewers, I don't have any suggestions.

**Comment by iagolemos1** [comment]
Would you have any suggestions of what grpahics I should leave in the paper?

**Comment by iagolemos1** [comment]
The edited paper is in the repository.

**Comment by iagolemos1** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01999/joss.01999/10.21105.joss.01999.pdf)

**Comment by iagolemos1** [comment]
@drvinceknight 
The [README](https://github.com/iagolemos1/thresholdmodeling/blob/master/README.md) was updated.

**Comment by iagolemos1** [comment]
Sorry @drvinceknight, I didn't see the list of possible reviewers. Sending some usernames:

kellieotto
molgor
jmbr
GalenStocking
bahung
matloff
mskwark
tuchandra
kose-y
dirmeier
adavidzh
alanfairless

**Comment by iagolemos1** [comment]
Answers in  https://github.com/openjournals/joss-reviews/issues/1999.

Em ter., 7 de jan. de 2020 às 13:39, whedon <notifications@github.com>
escreveu:

**Comment by drvinceknight** [comment]
Thanks @iagolemos1 :+1:

**Comment by drvinceknight** [comment]
@kellieotto @galenstocking @bahung would you be able to review this paper on a piece of software for extreme value analysis? There is information about what that involves here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html and I'm happy to answer any questions you may have.

**Comment by iagolemos1** [comment]
You are welcome @drvinceknight  :)

**Comment by iagolemos1** [comment]
@drvinceknight I just need to wait now while you find some reviewers?

**Comment by iagolemos1** [comment]
@drvinceknight I just need to wait now while it is found some interested reviewers?

**Comment by bahung** [comment]
Hi @drvinceknight,
I would be happy to help,
Just let me know when I should start and return the review.

Best,
Hung

**Comment by iagolemos1** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by iagolemos1** [comment]
I did some minimal changes in the citations on the paper. 
@whedon generate pdf

**Comment by iagolemos1** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01999/joss.01999/10.21105.joss.01999.pdf)

**Comment by iagolemos1** [comment]
@drvinceknight is there something I should do or just wait for now long?

**Comment by drvinceknight** [comment]
@whedon assign @bahung as reviewer

**Comment by whedon** [comment]
OK, @bahung is now a reviewer

**Comment by drvinceknight** [comment]
> Just let me know when I should start and return the review.

Thanks @bahung, once we have another reviewer, an issue will be opened where the review will take place so no need for action just yet.

**Comment by drvinceknight** [comment]
> @drvinceknight is there something I should do or just wait for now long?

Nothing to do just yet, I will wait to give the other people I ping'd a chance to respond and if they do not I will continue to search for reviewers.

**Comment by iagolemos1** [comment]
@drvinceknight Great. Thanks!

**Comment by kellieotto** [comment]
@drvinceknight @iagolemos1 I can review this

**Comment by iagolemos1** [comment]
@kellieotto thank you.

**Comment by drvinceknight** [comment]
@whedon add @kellieotto as reviewer

**Comment by whedon** [comment]
OK, @kellieotto is now a reviewer

**Comment by drvinceknight** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2013. Feel free to close this issue now!

**Comment by drvinceknight** [comment]
@kellieotto and @bahung thank you very much for accepting to review this. The review will take place on #2013 where you will see instructions but if I can answer any questions please let me know.
