### ISSUE TITLE
[PRE REVIEW]: Virtual Bumblebees

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#200]
**Submitting author:** @howardjp (<a href="http://orcid.org/0000-0003-4530-1547">James P. Howard, II</a>)
**Repository:** <a href="https://github.com/howardjp/bumblebees" target ="_blank">https://github.com/howardjp/bumblebees</a>
**Version:** 1.1
**Editor:** @arfon
**Reviewer:** @pjotrp

**What this issue is for**

Thanks for submitting your paper to JOSS howardjp. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
Hi @howardjp. It's not entirely clear what this submission is? Could you tell me a little more about the research application of this work?

**Comment by howardjp** [comment]
That's a good question, @arfon.  The environment is an implementation of a specific cellular automata ruleset.  This is [artifical life](https://en.wikipedia.org/wiki/Artificial_life).  In particular, it is a variant of the Langton Ant (see, e.g., [Gajardo, Moreira, and Goles, 2002](http://www.sciencedirect.com/science/article/pii/S0166218X00003346)).  In addition, one could implement the Langton Ant within Virtual Bumblebees through careful construction of a starting grid.

Here's a copy of the [presentation I gave at MathFest 2015](https://1drv.ms/p/s!AoC3AjtvhtrEhi94FPzEv-ZTXBZ7).  Be warned, it is 160M due to embedded videos.

**Comment by howardjp** [comment]
@arfon I wanted to jump in and see if this had completely stalled or if I could help rekickstart it somehow?

**Comment by arfon** [comment]
> @arfon I wanted to jump in and see if this had completely stalled or if I could help rekickstart it somehow?

Apologies for dropping the ball @howardjp. I'm struggling to figure out who might be a suitable editor for this submission.

@openjournals/joss-editors - anyone willing to volunteer to edit this submission?

**Comment by howardjp** [comment]
It's all good and we've all been there.  Just wanted to see if I could give it a nudge.  Totally unrelated, @arfon, but I spoke with one of your colleagues at NerdNite Baltimore last week.  It's a small world.

**Comment by pjotrp** [comment]
It is a nifty visualisation. I.e., pretty cool. I do, however, think that this submission is going to stretch our scientific application rule. @howardjp unlike the papers you refer to you don't give an explanation of what you actually have implemented and how it differs from the ant? I think that would be incredibly helpful. Your code is short and concise, but not exactly explanatory.

Also can you run through the list of checkboxes of another submission, such as https://github.com/openjournals/joss-reviews/issues/248 and see if we can actually tick the boxes.

Finally, do consider that your your scientific credibility is attached to your submission and may be visible for eternity ;)

**Comment by howardjp** [comment]
@pjotrp I think a lot of the checkboxes can be ticked with better documentation, so I will work on that and ping you again in a few days.  

As for scientific credibility, in a field that only progresses when someone has made a mistake, it is important not to take oneself too seriously ;)

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by pjotrp** [comment]
@whedon asssign @pjotrp as editor

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by howardjp** [comment]
@pjotrp Okay, I added a [README.md file to the develop branch](https://github.com/howardjp/bumblebees/blob/develop/README.md).  This adds a lot of context and explanation for

1. Why I created this,
2. How to use it, and 
3. How it works.

Of questions on this checklist, this will resolve almost all of them.  Some really don't apply (API documentation, though I do describe the internals, which can be helpful to someone wanting to make changes).  So with this in mind, please take another look and I can take another stab at getting it up to snuff.

Thanks! James

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by pjotrp** [comment]
Great. I started looking for a reviewer.

**Comment by pjotrp** [comment]
@howardjp do you have a mailing list you belong to for people with similar interests? I could put a call for review there.

**Comment by howardjp** [comment]
Hi, sorry for my own delay.  The final week of class is dense, to say the least.  As it is, not really.  My education is in public policy.  I literally wrote Bumblebees as a one-off while sitting at my son's chess tournament, as I described in a [blog post](https://jameshoward.us/2015/03/14/introducing-my-bumblebees/), based on something I was messing with 20-odd years ago.  I just wanted someone else to find it and do something interesting with it. :)

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @pjotrp as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @pjotrp

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/256. Feel free to close this issue now!
