### ISSUE TITLE
[PRE REVIEW]: mhealthtools: A Modular R Package for Extracting Features from Mobile and Wearable Sensor Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2000]
**Submitting author:** @philerooski (<a href="http://orcid.org/0000-0002-6967-2185">Phillip Snyder</a>)
**Repository:** <a href="https://github.com/Sage-Bionetworks/mhealthtools" target ="_blank">https://github.com/Sage-Bionetworks/mhealthtools</a>
**Version:** 0.2.0
**Editor:** @trallard
**Reviewers:** @Ebedthan, @AKuederle

**Author instructions**

Thanks for submitting your paper to JOSS @philerooski. **Currently, there isn't an JOSS editor assigned** to your paper.

@philerooski if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.16 s (195.9 files/s, 34438.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               22            250           1428           2072
HTML                             1             88              5            408
Rmd                              4            218            481            305
TeX                              1             14              0            158
Markdown                         2             48              0            128
YAML                             1              1              1             18
Dockerfile                       1              1              0              2
-------------------------------------------------------------------------------
SUM:                            32            620           1915           3091
-------------------------------------------------------------------------------
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/s41746-019-0090-4 is OK
- 10.21105/joss.01778 is OK
- 10.18637/jss.v059.i10 is OK
- 10.1038/s41746-019-0078-0 is OK
- 10.1038/s41746-019-0084-2 is OK
- 10.1146/annurev-bioeng-062117-121036 is OK
- 10.1145/3341162.3346277 is OK
- 10.5281/zenodo.3563546 is OK

MISSING DOIs

- https://doi.org/10.1038/s41746-019-0178-x may be missing for title: Detecting the impact of subject characteristics on machine learning-based diagnostic applications
- https://doi.org/10.1145/3267305.3267612 may be missing for title: Remote Assessment, in Real-World Setting, of Tremor Severity in Parkinson’s Disease Patients Using Smartphone Inertial Sensors

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02000/joss.02000/10.21105.joss.02000.pdf)

**Comment by danielskatz** [comment]
👋 @trallard - would you be willing to edit this submission for JOSS?

**Comment by danielskatz** [comment]
👋 @trallard - a 2nd ping...

**Comment by trallard** [comment]
Hey @danielskatz  sure, assign this to me!

**Comment by danielskatz** [comment]
Thanks @trallard - you can do it yourself by doing what I do in the next command :)

**Comment by danielskatz** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by trallard** [comment]
@philerooski let's start by finding some reviewers. Have you got someone in mind already? if not you can check the list of registered reviewers :<https://bit.ly/joss-reviewers> and suggest some
(⚠️ please make sure to not use the @ when adding their names to this issue)

**Comment by philerooski** [comment]
@trallard There is a paper similar to this that has been published in JOSS (https://joss.theoj.org/papers/10.21105/joss.01778) that was reviewed by Abhishektha Boppana (`abhishektha`), although this reviewer is not familiar with R. Arne Küderle (`AKuederle`) is familiar with the conceptual aspects of this paper (IMUs, motion/gait analysis), but they do not list R as a programming language that they are familiar with, either. There are many reviewers familiar with both R and bioinformatics: `Ebedthan`, `kanekalla`, `dcassol`, ...

**Comment by trallard** [comment]
Hi, all I am the editor for this submission and we are looking for at least 2 reviewers to move forward. 

@abhishektha Abhishek,  are you willing and able to review this submission?
@AKuederle Arne, are you willing and able to review this submission?
@Ebedthan Anicet, are you willing and able to review this submission?
@kanekalla Kishore, are you willing and able to review this submission?

**Comment by Ebedthan** [comment]
Yes I'll do.

Send me details please.
Regards.

**Comment by AKuederle** [comment]
Yes, I would be willing to, but because of my limited R knowledge, I might not be able to comment on aspects of code quality and correctness (?). If this is not an issue, I would be happy to perform the review.

**Comment by arfon** [comment]
:wave: @trallard - it looks like @Ebedthan and @AKuederle are happy to review here so once they're assigned, the main review thread can be started.

**Comment by trallard** [comment]
Apologies for the delay my OOO extended and forgot to update. Moving this forward now

**Comment by trallard** [comment]
@whedon assign @Ebedthan as reviewer

**Comment by whedon** [comment]
OK, @Ebedthan is now a reviewer

**Comment by trallard** [comment]
@whedon add @AKuederle as reviewer

**Comment by whedon** [comment]
OK, @AKuederle is now a reviewer

**Comment by trallard** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2106.
