### ISSUE TITLE
[PRE REVIEW]: EvoMaster: A Search-Based System Test Generation Tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2001]
**Submitting author:** @arcuri82 (<a href="http://orcid.org/0000-0003-0799-2930">Andrea Arcuri</a>)
**Repository:** <a href="https://github.com/EMResearch/EvoMaster" target ="_blank">https://github.com/EMResearch/EvoMaster</a>
**Version:** v1.0.0
**Editor:** @gkthiruvathukal
**Reviewers:** @mado89, @jaynanavati

**Author instructions**

Thanks for submitting your paper to JOSS @arcuri82. **Currently, there isn't an JOSS editor assigned** to your paper.

@arcuri82 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1109/icst.2018.00046 may be missing for title: EvoMaster: Evolutionary Multi-context Automated System Test Generation
- https://doi.org/10.1007/978-3-319-66299-2_1 may be missing for title: Many Independent Objective (MIO) Algorithm for Test Suite Generation
- https://doi.org/10.1109/qrs.2017.11 may be missing for title: RESTful API Automated Test Case Generation
- https://doi.org/10.1145/3321707.3321815 may be missing for title: Resource-based test case generation for RESTful web services
- https://doi.org/10.1145/3321707.3321732 may be missing for title: SQL data generation to enhance Search-Based System Testing

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=3.53 s (299.8 files/s, 43053.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                            27              0              0          56714
Kotlin                         455          10873           6106          34479
Java                           508           8276           3678          24565
Maven                           20            269            146           2146
Markdown                        13            356              0           1043
SQL                             23            230              0           1027
R                                2            152             24            359
ANTLR Grammar                    4            193            189            356
Python                           1            155            112            286
TeX                              1              9              0             66
YAML                             3             28             14             60
XML                              1              8              3             20
-------------------------------------------------------------------------------
SUM:                          1058          20549          10272         121121
-------------------------------------------------------------------------------
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02001/joss.02001/10.21105.joss.02001.pdf)

**Comment by danielskatz** [comment]
👋 @gkthiruvathukal  - would you be willing to edit this JOSS submission?

**Comment by arcuri82** [comment]
Hi. Looking at the review list starting from bottom, some possibilities could be:
mado89, bzz, chrisma and neurons

**Comment by danielskatz** [comment]
👋 @gkthiruvathukal - a 2nd ping...

**Comment by gkthiruvathukal** [comment]
So sorry, @danielskatz. I'm definitely willing to edit this submission. Will assign myself now and get it started.

**Comment by gkthiruvathukal** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
@mado89, are you willing to contribute a review or this submission?

**Comment by gkthiruvathukal** [comment]
@bzz, are you willing to contribute a review for this submission? (I need two reviewers.)

**Comment by mado89** [comment]
I could be a reviewer. However:
* I'd need some time. I don't think I can give this software a thorough review in just two weeks. By looking at it I think I can manage to do it until the end of February
* I'd possibly need more instructions on how to use the software. By looking at it I was not able to get a grasp how to use it (but I did not spend too much time on it)

So its up to you @gkthiruvathukal as editor and and @arcuri82

**Comment by gkthiruvathukal** [comment]
@mado89 Our reviewers are volunteers. We will work with your schedule. Is it ok if I assign you now? I would like to get this review started as soon as possible.

**Comment by gkthiruvathukal** [comment]
@chrisma, are you willing to contribute a review or this submission? I need a second reviewer for this submission.

**Comment by gkthiruvathukal** [comment]
@arcuri82 Will you be able to assist with making sure the instructions on how to use the software are 100% clear. This will help @mado89.

**Comment by arcuri82** [comment]
Hi,
 yes, I can provide any further documentation that is needed. But, there is already quite a bit of documentation (including a demo video of using the tool). To improve it, I will need some more info on which parts in the documentation are unclear, and know where @mado89 got stuck with the instructions

**Comment by chrisma** [comment]
> @chrisma, are you willing to contribute a review or this submission? I need a second reviewer for this submission.

Hi, thanks for considering me as a reviewer. Unfortunately, Test Generation is not my main field of expertise and I currently don't have the time resources to look into this in depth. As such, I have to decline the invitation to review. I think others would be better suited. Thanks!

**Comment by mado89** [comment]
@arcuri82 sorry for not getting back to you until now. I see that the official review process has not started yet. Currently, I am under a lot of stress but I hope that starting from next week things will ease a little bit. Then I will start giving your software a thorough investigation and let you know where I need help. 
@gkthiruvathukal whats the current status on the review process?

**Comment by gkthiruvathukal** [comment]
@mado89 Sorry for the delay. I have been working on a manuscript and finally finished drafting the last chapter. I'm getting this started right away.

**Comment by gkthiruvathukal** [comment]
@whedon assign @mado89 as reviewer

**Comment by whedon** [comment]
OK, @mado89 is now a reviewer

**Comment by gkthiruvathukal** [comment]
@neurons or @bzz Are you willing to contribute a review for this JOSS submission? I really need a second reviewer so we can start review.

**Comment by danielskatz** [comment]
👋 @gkthiruvathukal - any progress on finding another reviewer? Maybe you need to ask more potential people

**Comment by gkthiruvathukal** [comment]
@danielskatz Sorry, I hit a bit of a wall the past two weeks with faculty hiring in our department. I'll get on this shortly.  I will go through the list of reviewers and see if I can find another person to help.

**Comment by gkthiruvathukal** [comment]
@markgalassi. I was looking through our list of reviewers and saw that you have software engineering as an area of interest. Would you be willing to be the second reviewer for this JOSS submission? I need two reviewers (@mado89 has already agreed) in order to proceed.

**Comment by gkthiruvathukal** [comment]
@xirdneh I was looking through our list of reviewers and saw that you have software engineering as an area of interest. Would you be willing to be the second reviewer for this JOSS submission? I need two reviewers (@mado89 has already agreed) in order to proceed.

**Comment by gkthiruvathukal** [comment]
@jaynanavati Are you willing to contribute a review for this JOSS submission?

**Comment by jaynanavati** [comment]
Dear Sir,

I am willing to review the submission mentioned in the subject.

Thank you.

*Dr. Jay Nanavati*

**Comment by gkthiruvathukal** [comment]
Thanks, @jaynanavati. I will add you and we can get the review process started.

**Comment by gkthiruvathukal** [comment]
@whedon add @jaynanavati as reviewer

**Comment by whedon** [comment]
OK, @jaynanavati is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2153.
