### ISSUE TITLE
[PRE REVIEW]: FGTpartitioner: A rapid method for parsimonious delimitation of ancestry breakpoints in large genome-wide SNP datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2002]
**Submitting author:** @tkchafin (<a href="http://orcid.org/0000-0001-8687-5905">Tyler Chafin</a>)
**Repository:** <a href="https://github.com/tkchafin/FGTpartitioner" target ="_blank">https://github.com/tkchafin/FGTpartitioner</a>
**Version:** v1.0.0
**Editor:** @lpantano
**Reviewers:** @dangeles, @YichaoOU

**Author instructions**

Thanks for submitting your paper to JOSS @tkchafin. The JOSS editor @lpantano, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@tkchafin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lpantano it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (298.2 files/s, 41753.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           2             77            145            370
Markdown                         3             85              0            309
Cython                           1             16             18            120
TeX                              1              0              0            104
Bourne Shell                     2              2              0             14
-------------------------------------------------------------------------------
SUM:                             9            180            163            917
-------------------------------------------------------------------------------
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1534/genetics.109.103010 is OK
- 10.1038/s41559-018-0611-6 is OK
- 10.1186/1479-7364-7-1 is OK
- 10.1126/sciadv.1501714 is OK
- 10.1145/1854776.1854788 is OK
- 10.1093/bioinformatics/btr330 is OK
- 10.3390/genes9030123 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02002/joss.02002/10.21105.joss.02002.pdf)

**Comment by danielskatz** [comment]
👋 @lpantano - I apologize for assigning this to you (by submitter request) without asking you first.  Are you willing to edit it?

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.05 s (178.1 files/s, 24935.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           2             77            145            370
Markdown                         3             85              0            309
Cython                           1             16             18            120
TeX                              1              0              0            104
Bourne Shell                     2              2              0             14
-------------------------------------------------------------------------------
SUM:                             9            180            163            917
-------------------------------------------------------------------------------


Statistical information for the repository '2002' was gathered on 2020/01/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Tyler Chafin                    27           973            474           92.76
Tyler K. Chafin                  3           103             10            7.24

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Tyler Chafin                592           60.8          2.0               15.88
```

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
@whedon assign @dangeles as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dangeles

**Comment by lpantano** [comment]
@aedin do you think you would like to review this tool?

**Comment by lpantano** [comment]
Hey, @chapmanb do you think you can review this one? or knows somebody who could do it?

**Comment by lpantano** [comment]
@krother would you be interested on review this paper?

**Comment by krother** [comment]
sorry I am 10 years away from that area.

**Comment by lpantano** [comment]
Thanks @krother, @tkchafin do you have any recommendation for a reviewer?

**Comment by tkchafin** [comment]
@txje or @YichaoOU have both written similar applications, and might be interested in reviewing?

**Comment by YichaoOU** [comment]
@tkchafin Thanks for the invitation. How should I start?

**Comment by lpantano** [comment]
@whedon add @YichaoOU as reviewer

**Comment by whedon** [comment]
OK, @YichaoOU is now a reviewer

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2030. Feel free to close this issue now!

**Comment by lpantano** [comment]
thanks @dangeles and @YichaoOU to accept to review this paper. You can use the issue #2030 to start your review.
