### ISSUE TITLE
[REVIEW]: The MFrontGenericInterfaceSupport project

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2003]
**Submitting author:** @thelfer (<a href="http://orcid.org/0000-0003-2460-5816">Thomas Helfer</a>)
**Repository:** <a href="https://github.com/thelfer/MFrontGenericInterfaceSupport" target ="_blank">https://github.com/thelfer/MFrontGenericInterfaceSupport</a>
**Version:** v1.0.1
**Editor:** @arfon
**Reviewer:** @srmnitc, @IgorBaratta
**Archive:** <a href="https://doi.org/10.5281/zenodo.3762856" target="_blank">10.5281/zenodo.3762856</a>

## Status

[![status](https://joss.theoj.org/papers/6731b53e780cb0696ac285bf66d04ade/status.svg)](https://joss.theoj.org/papers/6731b53e780cb0696ac285bf66d04ade)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6731b53e780cb0696ac285bf66d04ade"><img src="https://joss.theoj.org/papers/6731b53e780cb0696ac285bf66d04ade/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6731b53e780cb0696ac285bf66d04ade/status.svg)](https://joss.theoj.org/papers/6731b53e780cb0696ac285bf66d04ade)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/thelfer/MFrontGenericInterfaceSupport" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@srmnitc & @IgorBaratta, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/thelfer/MFrontGenericInterfaceSupport">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@thelfer) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/thelfer/MFrontGenericInterfaceSupport">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@thelfer) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @srmnitc, @IgorBaratta it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.compstruc.2016.11.010 is OK
- 10.1007/s13137-019-0126-6 is OK
- 10.1016/j.ijsolstr.2018.12.019 is OK
- 10.1002/nme.1770 is OK
- 10.1007/s11242-019-01310-1 is OK
- 10.13140/RG.2.2.35501.54247 is OK
- 10.11588/ans.2015.100.20553 is OK
- 10.1007/978-3-642-23099-8 is OK
- 10.13140/RG.2.2.22079.76968 is OK
- 10.1016/j.camwa.2015.06.027 is OK
- 10.1007/s12665-012-1546-x is OK

MISSING DOIs

- https://doi.org/10.1137/141000671 may be missing for title: Julia: A fresh approach to numerical computing
- https://doi.org/10.23998/rm.76193 may be missing for title: JuliaFEM beam element implementation
- https://doi.org/10.23998/rm.76259 may be missing for title: Pipe route optimization to avoid undesired vibration by using JuliaFEM
- https://doi.org/10.23998/rm.75103 may be missing for title: Introduction to JuliaFEM an open-source FEM solver
- https://doi.org/10.23998/rm.65040 may be missing for title: Natural Frequency Calculations with JuliaFEM
- https://doi.org/10.1002/nme.3353 may be missing for title: Lower-dimensional interface elements with local enrichment: application to coupled hydro-mechanical problems in discretely fractured porous media
- https://doi.org/10.2166/hydro.2004.0017 may be missing for title: A process-oriented approach to computing multi-field problems in porous media
- https://doi.org/10.23998/rm.64224 may be missing for title: JuliaFEM: open source solver for both industrial and academia usage
- https://doi.org/10.23998/rm.64224 may be missing for title: JuliaFEM - open source solver for both industrial and academia usage
- https://doi.org/10.23998/rm.69026 may be missing for title: Implementing model reduction to the JuliaFEM platform

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02003/joss.02003/10.21105.joss.02003.pdf)

**Comment by arfon** [comment]
@srmnitc, @IgorBaratta - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by srmnitc** [comment]
@arfon  @thelfer I have completed a first round of review. Thanks @thelfer for the repository and documentation. The documentation, especially the associated webpage documents various examples and usage quite well. My issue was with initial setup. I have raised four issues at the repository - https://github.com/thelfer/MFrontGenericInterfaceSupport/issues/17, https://github.com/thelfer/MFrontGenericInterfaceSupport/issues/18, https://github.com/thelfer/MFrontGenericInterfaceSupport/issues/19, and https://github.com/thelfer/MFrontGenericInterfaceSupport/issues/20.  For me, it was hard to see how to set up or install the software and use it. Once the issues are fixed, I can move on to check the functionality. 

There are also few things for which I have not opened an issue. This has to do with the JOSS paper-  

- The JOSS paper has some typos which need to fixed.  
- The first page of the paper has numerous short paragraphs, which in my opinion affects the readability.
- Another point is about citations. Statements in the paper such as `This is error-prone and may lead to spurious or even worse inexact results` and `While this causes memory fragmentation,
this is the most frequent choice`, would be reinforced with suitable citations.
- Finally, there are multiple examples provided. This is one for the editor @arfon. These examples could be moved to a documentation in order to keep the JOSS paper short and concise.

**Comment by arfon** [comment]
> Finally, there are multiple examples provided. This is one for the editor @arfon. These examples could be moved to a documentation in order to keep the JOSS paper short and concise.

Thanks @srmnitc for your feedback here. To respond directly to ☝️this comment - I think this is probably OK as-is. We generally try to avoid lengthy discussions of e.g. the API structure (something that should be in docs) but some examples such as these are reasonable I think.

**Comment by IgorBaratta** [comment]
I started the review by trying the _experimental_ Julia binding, and the installation of the package was straightforward. However, for the C++ library itself, I couldn't find any documentation of the installation process.  So at this point, I could not honestly evaluate the **Functionality**. 

Concerning the **Documentation**, some items are missing or not easily accessible:
- Community guidelines 
- Automated tests - Are the tests automated or are there any manual steps to run them?
- Installation instructions

Some examples are given in https://thelfer.github.io/mgis/web/bindings-cxx.html , and it seems to be a good start for using the software, but I miss a standalone example I could just run and modify. Or, are there any present in the test folder? Nevertheless, I couldn't find any documented.

**Comment by thelfer** [comment]
@IgorBaratta, @srmnitc Sorry for not responding earlier. Thank you for this first round of review and those very constructive feed-backs.

I just uploaded a new version of the `INSTAL-cmake.md` file which now fully describes the installation process. Let me know if this file is self-explanatory (it requires some knowledge of `cmake` tough).

**Comment by thelfer** [comment]
> * Automated tests - Are the tests automated or are there any manual steps to run them?

To run the tests, you must type `make check` in the `build` directory. Tests are only available if the `TFEL/MFront` package is available. As explained in the paper, without `TFEL/MFront`, the package is barely useless. Yet, technically, `TFEL/MFront` is *not* a dependency of `MGIS`.

**Comment by thelfer** [comment]
> However, for the C++ library itself, I couldn't find any documentation of the installation process.

The `C++` library is *always* built. The `Julia` bindings just wraps the `C++` methods using the `CxxWrap` package.

**Comment by thelfer** [comment]
> * Community guidelines

@IgorBaratta  Are those required ?

**Comment by thelfer** [comment]
> Some examples are given in https://thelfer.github.io/mgis/web/bindings-cxx.html , and it seems to be a good start for using the software

@IgorBaratta  Indeed, this document is the main entry point for the `C++` library. The `MGIS` library is indeed quite small so it provides a convenient introduction/overview.

Interested users then have a look at the `tests` directory where examples are provided.

 I do appreciate your feed-backs on the documentation.

**Comment by thelfer** [comment]
> I started the review by trying the _experimental_ Julia binding,

@IgorBaratta At this stage, the `Julia` bindings are rather beta stage.

**Comment by srmnitc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02003/joss.02003/10.21105.joss.02003.pdf)

**Comment by srmnitc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02003/joss.02003/10.21105.joss.02003.pdf)

**Comment by srmnitc** [comment]
@arfon @thelfer Sorry for the slight delay in review, I just came back from a planned vacation. I will finish the review in the next couple of days. Thanks for the patience.

**Comment by thelfer** [comment]
@arfon @IgorBaratta T. Nagel, one of the co-author, just propose to update the `OpenGeoSys` part with a more meaningful example. Would you mind if we do this change ? (https://github.com/thelfer/MFrontGenericInterfaceSupport/pull/26)

**Comment by arfon** [comment]
I'm OK with this if @srmnitc and @IgorBaratta are.

**Comment by IgorBaratta** [comment]
> I'm OK with this if @srmnitc and @IgorBaratta are.

I'm ok with that too.

**Comment by IgorBaratta** [comment]
> > * Community guidelines
> 
> @IgorBaratta Are those required ?

I think so, it's on the review checklist, and it's one of the boxes I still have to check.

**Comment by srmnitc** [comment]
> I'm OK with this if @srmnitc and @IgorBaratta are.

I am also fine with this

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by srmnitc** [comment]
@arfon @thelfer I am mostly done with my review. I still have issues with the paper, for which I have raised  new issue. Once this is fixed, I will git it one more go. Hope everybody is staying safe and healthy!

**Comment by thelfer** [comment]
@srmnitc Thanks for you feed-backs. I'll try to fix them ASAP.

**Comment by thelfer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02003/joss.02003/10.21105.joss.02003.pdf)

**Comment by thelfer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02003/joss.02003/10.21105.joss.02003.pdf)

**Comment by thelfer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02003/joss.02003/10.21105.joss.02003.pdf)

**Comment by thelfer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02003/joss.02003/10.21105.joss.02003.pdf)

**Comment by thelfer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02003/joss.02003/10.21105.joss.02003.pdf)

**Comment by thelfer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02003/joss.02003/10.21105.joss.02003.pdf)

**Comment by thelfer** [comment]
Hi @arfon, @srmnitc @IgorBaratta
I hope everyone is fine.
I just closed this issue:  https://github.com/thelfer/MFrontGenericInterfaceSupport/issues/35
Here there anything I can do to help the review process ?
Regards,
Thomas

**Comment by srmnitc** [comment]
With the last review, I am happy with the overall status of the paper. The main part where I struggled was instructions to set up and use the code, but now the documentation is much better. Also, for the specialist audience, it might be easier. I still think the paper could be improved a bit more in terms of sentence construction and language, but it is in overall good shape. With that said, I have completed my review and recommend the paper for publication @arfon . Thanks @thelfer for the modifications and feedback. I will still post some issues for the general improvement of the code, but they do not block the publication of the paper. Thanks and hope everybody is healthy and in good spirits!

**Comment by thelfer** [comment]
@srmnitc Thank you for this kind review. Do not hesitate to make comments on the code, they will be greatly appreciated.

**Comment by arfon** [comment]
👋 @IgorBaratta - how are you getting along with your review?

**Comment by thelfer** [comment]
@whedon generate pdf

Just fixed a typo in the acknowledgements.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02003/joss.02003/10.21105.joss.02003.pdf)

**Comment by IgorBaratta** [comment]
>  @IgorBaratta - how are you getting along with your review?

Hi, Sorry for the delay.
I am going over the review checklist again, considering the latest changes.
I should be able to check all points by Friday.

**Comment by arfon** [comment]
> I am going over the review checklist again, considering the latest changes.

:+1: thanks for the update!

**Comment by IgorBaratta** [comment]
I finished my review. All boxes are now checked.
I was able to test it with the FEniCS and JuliaFEM libraries.
Also, the documentation is much better now. 

S now, I recommend it for publication.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
PDF failed to compile for issue #2003 with the following error: 

 sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.02003.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/0045-7949(94)00339-5 is OK
- 10.1016/j.compstruc.2016.11.010 is OK
- 10.1007/s13137-019-0126-6 is OK
- 10.1016/j.ijsolstr.2018.12.019 is OK
- 10.1002/nme.1770 is OK
- 10.1007/s11242-019-01310-1 is OK
- 10.13140/RG.2.2.35501.54247 is OK
- 10.11588/ans.2015.100.20553 is OK
- 10.1007/978-3-642-23099-8 is OK
- 10.13140/RG.2.2.22079.76968 is OK
- 10.1016/j.camwa.2015.06.027 is OK
- 10.1007/s12665-012-1546-x is OK

MISSING DOIs

- https://doi.org/10.1137/141000671 may be missing for title: Julia: A fresh approach to numerical computing
- https://doi.org/10.23998/rm.76193 may be missing for title: JuliaFEM beam element implementation
- https://doi.org/10.23998/rm.76259 may be missing for title: Pipe route optimization to avoid undesired vibration by using JuliaFEM
- https://doi.org/10.23998/rm.75103 may be missing for title: Introduction to JuliaFEM an open-source FEM solver
- https://doi.org/10.23998/rm.65040 may be missing for title: Natural Frequency Calculations with JuliaFEM
- https://doi.org/10.1002/nme.3353 may be missing for title: Lower-dimensional interface elements with local enrichment: application to coupled hydro-mechanical problems in discretely fractured porous media
- https://doi.org/10.2166/hydro.2004.0017 may be missing for title: A process-oriented approach to computing multi-field problems in porous media
- https://doi.org/10.23998/rm.64224 may be missing for title: JuliaFEM: open source solver for both industrial and academia usage
- https://doi.org/10.23998/rm.64224 may be missing for title: JuliaFEM - open source solver for both industrial and academia usage
- https://doi.org/10.23998/rm.69026 may be missing for title: Implementing model reduction to the JuliaFEM platform

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02003/joss.02003/10.21105.joss.02003.pdf)

**Comment by arfon** [comment]
@thelfer - I made a bunch of small changes to the paper in https://github.com/thelfer/MFrontGenericInterfaceSupport/pull/40 which are mostly designed to fix citation formatting.

Could you also review the suggested DOIs from Whedon [above](https://github.com/openjournals/joss-reviews/issues/2003#issuecomment-617948170) and update your BibTeX file where appropriate?

Finally, could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by thelfer** [comment]
@arfon I just merged those feed-backs. I'll try to do what you ask as soon as possible.

**Comment by thelfer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/0045-7949(94)00339-5 is OK
- 10.1137/141000671 is OK
- 10.23998/rm.76193 is OK
- 10.23998/rm.76259 is OK
- 10.23998/rm.75103 is OK
- 10.23998/rm.65040 is OK
- 10.1016/j.compstruc.2016.11.010 is OK
- 10.1007/s13137-019-0126-6 is OK
- 10.1016/j.ijsolstr.2018.12.019 is OK
- 10.1002/nme.3353 is OK
- 10.2166/hydro.2004.0017 is OK
- 10.1002/nme.1770 is OK
- 10.1007/s11242-019-01310-1 is OK
- 10.13140/RG.2.2.35501.54247 is OK
- 10.11588/ans.2015.100.20553 is OK
- 10.1007/978-3-642-23099-8 is OK
- 10.13140/RG.2.2.22079.76968 is OK
- 10.1016/j.camwa.2015.06.027 is OK
- 10.1007/s12665-012-1546-x is OK
- 10.23998/rm.64224 is OK
- 10.23998/rm.64224 is OK
- 10.23998/rm.69026 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by thelfer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02003/joss.02003/10.21105.joss.02003.pdf)

**Comment by thelfer** [comment]
@arfon Done: https://zenodo.org/record/3762856#.XqEO7nUzaV4

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3762856 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3762856" target="_blank">10.5281/zenodo.3762856</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/0045-7949(94)00339-5 is OK
- 10.1137/141000671 is OK
- 10.23998/rm.76193 is OK
- 10.23998/rm.76259 is OK
- 10.23998/rm.75103 is OK
- 10.23998/rm.65040 is OK
- 10.1016/j.compstruc.2016.11.010 is OK
- 10.1007/s13137-019-0126-6 is OK
- 10.1016/j.ijsolstr.2018.12.019 is OK
- 10.1002/nme.3353 is OK
- 10.2166/hydro.2004.0017 is OK
- 10.1002/nme.1770 is OK
- 10.1007/s11242-019-01310-1 is OK
- 10.13140/RG.2.2.35501.54247 is OK
- 10.11588/ans.2015.100.20553 is OK
- 10.1007/978-3-642-23099-8 is OK
- 10.13140/RG.2.2.22079.76968 is OK
- 10.1016/j.camwa.2015.06.027 is OK
- 10.1007/s12665-012-1546-x is OK
- 10.23998/rm.64224 is OK
- 10.23998/rm.64224 is OK
- 10.23998/rm.69026 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1428

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1428, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1253299955583930368) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1429
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02003](https://doi.org/10.21105/joss.02003)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@srmnitc, @IgorBaratta - many thanks for your reviews here ✨ 

@thelfer - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02003/status.svg)](https://doi.org/10.21105/joss.02003)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02003">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02003/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02003/status.svg
   :target: https://doi.org/10.21105/joss.02003
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02003/status.svg)](https://doi.org/10.21105/joss.02003)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
