### ISSUE TITLE
[REVIEW]: CMasher: Scientific colormaps for making accessible, informative and 'cmashing' plots

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2004]
**Submitting author:** @1313e (<a href="http://orcid.org/0000-0002-1559-9832">Ellert van der Velden</a>)
**Repository:** <a href="https://github.com/1313e/CMasher" target ="_blank">https://github.com/1313e/CMasher</a>
**Version:** v1.2.2
**Editor:** @mbobra
**Reviewer:** @tacaswell, @wafels
**Archive:** <a href="https://doi.org/10.5281/zenodo.3637633" target="_blank">10.5281/zenodo.3637633</a>

## Status

[![status](https://joss.theoj.org/papers/16f291edc5c4fb61e31e6eef45bb558a/status.svg)](https://joss.theoj.org/papers/16f291edc5c4fb61e31e6eef45bb558a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/16f291edc5c4fb61e31e6eef45bb558a"><img src="https://joss.theoj.org/papers/16f291edc5c4fb61e31e6eef45bb558a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/16f291edc5c4fb61e31e6eef45bb558a/status.svg)](https://joss.theoj.org/papers/16f291edc5c4fb61e31e6eef45bb558a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/1313e/CMasher" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@tacaswell & @wafels, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mbobra know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/1313e/CMasher">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@1313e) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/1313e/CMasher">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@1313e) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @tacaswell, @wafels it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3847/1538-4365/ab1f7d is OK
- 10.21105/joss.01229 is OK
- 10.21105/joss.01399 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.5281/zenodo.3378106 is OK
- 10.5281/zenodo.1214904 is OK
- 10.1371/journal.pone.0199239 is OK
- 10.1063/1.4822401 is OK
- 10.1109/VISUAL.2002.1183788 is OK
- 10.1109/TVCG.2017.2744359 is OK
- 10.1080/15230406.2016.1140074 is OK
- 10.1364/JOSAA.29.000313 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02004/joss.02004/10.21105.joss.02004.pdf)

**Comment by mbobra** [comment]
@tacaswell @wafels Thank you for agreeing to review this submission! Whedon generated a checklist and linked a reviewer guide above -- please let me know if you have any questions or comments.

**Comment by 1313e** [comment]
@mbobra Can you remind me, after the review process has finished, to do something about the placement of Figure 2 in the paper?
I will probably remember it, but just to be sure.

**Comment by 1313e** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02004/joss.02004/10.21105.joss.02004.pdf)

**Comment by 1313e** [comment]
Any updates?

**Comment by mbobra** [comment]
@tacaswell, @wafels Let me know if you have any questions!

**Comment by mbobra** [comment]
@tacaswell, @wafels Let me know if you still have time to review -- if you're too busy, no worries at all and I can find other reviewers.

**Comment by 1313e** [comment]
@mbobra I don't think this is going anywhere anytime soon?
Sadly, the one person I could come up with as a reviewer already is one for this paper, so that doesn't really work.

**Comment by mbobra** [comment]
@openjournals/joss-eics Can you help us with this?

**Comment by kthyng** [comment]
@mbobra just pinged @tacaswell by other means. Have you tried email for @wafels?

**Comment by tacaswell** [comment]
I approve this paper :+1:

**Comment by tacaswell** [comment]
As a side note, @1313e proposed some of these color maps for inclusion in Matplotlib and we suggested a stand-alone package.  I think that this has ended up in a vastly better state than if the color maps had been added to core.  There is great value in an curated set of color maps that are nicely name spaced and more opinionated than we can be on core.

**Comment by mbobra** [comment]
Thank you, @tacaswell!!!

**Comment by mbobra** [comment]
@1313e An update for you: I pinged wafels via e-mail and he's working on it!

**Comment by 1313e** [comment]
> As a side note, @1313e proposed some of these color maps for inclusion in Matplotlib and we suggested a stand-alone package. I think that this has ended up in a vastly better state than if the color maps had been added to core. There is great value in an curated set of color maps that are nicely name spaced and more opinionated than we can be on core.

Yeah, after you proposed to me to make my own package, I had several others telling me to do the same thing, and that is why *CMasher* exists.

**Comment by wafels** [comment]
I approve this paper and look forward to seeing the colormaps used in the scientific community.

**Comment by 1313e** [comment]
@mbobra I have just fixed the placement of Figure 2 in the paper.
Shall I make a GitHub release for v1.2.2, which automatically makes a Zenodo archive, and post the DOI here?

**Comment by mbobra** [comment]
> @mbobra I have just fixed the placement of Figure 2 in the paper.
> Shall I make a GitHub release for v1.2.2, which automatically makes a Zenodo archive, and post the DOI here?

Yes please!

**Comment by 1313e** [comment]
@mbobra 10.5281/zenodo.3637633

**Comment by mbobra** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02004/joss.02004/10.21105.joss.02004.pdf)

**Comment by 1313e** [comment]
Also, the version is v1.2.2 now.
Not sure if that needs to be changed.

**Comment by mbobra** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3847/1538-4365/ab1f7d is OK
- 10.21105/joss.01229 is OK
- 10.21105/joss.01399 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.5281/zenodo.3378106 is OK
- 10.5281/zenodo.1214904 is OK
- 10.1371/journal.pone.0199239 is OK
- 10.1063/1.4822401 is OK
- 10.1109/VISUAL.2002.1183788 is OK
- 10.1109/TVCG.2017.2744359 is OK
- 10.1080/15230406.2016.1140074 is OK
- 10.1364/JOSAA.29.000313 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mbobra** [comment]
@whedon set 10.5281/zenodo.3637633 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3637633" target="_blank">10.5281/zenodo.3637633</a> is the archive.

**Comment by mbobra** [comment]
@whedon set v1.2.2 as version

**Comment by whedon** [comment]
OK. v1.2.2 is the version.

**Comment by mbobra** [comment]
@openjournals/joss-eics This paper is ready for final processing!

**Comment by kthyng** [comment]
Hi @1313e! I am taking over from here. Can you update the metadata in your zenodo archive to match your paper title and authors?

**Comment by kthyng** [comment]
@1313e Please take a look at references Sharpe et al, Smith et al 2018, and Smith et al 2019. For each of these either the spacing is odd or the author list seems incomplete. Please verify the best way to reference the Smith packages.

**Comment by 1313e** [comment]
> @1313e Please take a look at references Sharpe et al, Smith et al 2018, and Smith et al 2019. For each of these either the spacing is odd or the author list seems incomplete. Please verify the best way to reference the Smith packages.

Could you elaborate on what is wrong with those references? 
Because, I cannot see anything weird or wrong with any of the references I'm using. 



> Hi @1313e! I am taking over from here. Can you update the metadata in your zenodo archive to match your paper title and authors?

Of course. Forgot that automated Zenodo archiving will obviously not set those things.

**Comment by kyleniemeyer** [comment]
@1313e if it helps, it's possible to add a `.zenodo.json` file to a repository which will specify these metadata, though I can't find an official guide on how to do this/what to include... here is an example though: https://github.com/cboettig/nonparametric-bayes/blob/master/.zenodo.json

**Comment by 1313e** [comment]
> @1313e if it helps, it's possible to add a `.zenodo.json` file to a repository which will specify these metadata, though I can't find an official guide on how to do this/what to include... here is an example though: https://github.com/cboettig/nonparametric-bayes/blob/master/.zenodo.json

@kyleniemeyer I was actually wondering if such a thing existed. I will have a look.

**Comment by kthyng** [comment]
@1313e Ok, I edited the Sharpe entry directly then. My changes are in PR [#4](https://github.com/1313e/CMasher/pull/4) and you can merge them if you agree. I looked up the details for Nathaniel's papers and they look accurate.

**Comment by kthyng** [comment]
By the way, since you're interested in colormaps, you might be interested in my paper on them! 
http://tos.org/oceanography/assets/docs/29-3_thyng.pdf

**Comment by 1313e** [comment]
> @1313e Ok, I edited the Sharpe entry directly then. My changes are in PR [#4](https://github.com/1313e/CMasher/pull/4) and you can merge them if you agree. I looked up the details for Nathaniel's papers and they look accurate.

Oooh, those spacings.
Kinda weird that they are there, as they don't appear in my bibtex database.


> By the way, since you're interested in colormaps, you might be interested in my paper on them!
> http://tos.org/oceanography/assets/docs/29-3_thyng.pdf

I actually know that paper already and somehow completely forgot to add a citation to `cmocean` in the paper.
Want me to add a citation to that paper?

**Comment by kthyng** [comment]
> Want me to add a citation to that paper?

I'm not reviewing your paper — I just thought you'd be interested in work in the same area.

I'll proceed with the final steps

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02004/joss.02004/10.21105.joss.02004.pdf)

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3847/1538-4365/ab1f7d is OK
- 10.21105/joss.01229 is OK
- 10.21105/joss.01399 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.5281/zenodo.3378106 is OK
- 10.5281/zenodo.1214904 is OK
- 10.1371/journal.pone.0199239 is OK
- 10.1063/1.4822401 is OK
- 10.1109/VISUAL.2002.1183788 is OK
- 10.1109/TVCG.2017.2744359 is OK
- 10.1080/15230406.2016.1140074 is OK
- 10.1364/JOSAA.29.000313 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1277

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1277, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1225459954410192897) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1278
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02004](https://doi.org/10.21105/joss.02004)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Congratulations to @1313e on your new publication! Thanks to editor @mbobra and reviewers @tacaswell and @wafels — we rely on your time and expertise.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02004/status.svg)](https://doi.org/10.21105/joss.02004)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02004">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02004/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02004/status.svg
   :target: https://doi.org/10.21105/joss.02004
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02004/status.svg)](https://doi.org/10.21105/joss.02004)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by 1313e** [comment]
@kthyng I am not entirely sure why, but when I go to the paper [here](https://joss.theoj.org/papers/10.21105/joss.02004), the citation information and the BibTeX entry are kinda messed up (wrong year, volume and issue).
I initially thought that this is maybe caused by the paper just being published, but the other just-published papers do not seem to have that problem.
Any ideas what this is?

**Comment by arfon** [comment]
> Any ideas what this is?

I'm not entirely sure @1313e. I've fixed this manually for now and will investigate.

**Comment by mbobra** [comment]
It also looks like [the tweet](https://twitter.com/JOSS_TheOJ/status/1225459954410192897) has the wrong citation information.

**Comment by arfon** [comment]
> It also looks like the tweet has the wrong citation information.

Still? The information probably took a little while to update on Twitter's side but looks good to me now. Can you check again @mbobra?

**Comment by mbobra** [comment]
I am just clicking on the link above that says "Tweet for this paper". It still says "1(1), 200..." which cannot be right 😟

**Comment by 1313e** [comment]
> I am just clicking on the link above that says "Tweet for this paper". It still says "1(1), 200..." which cannot be right . Edit: I am clicking from my laptop (the link may look different on mobile).

The tweet does not contain any citation info?

**Comment by mbobra** [comment]
This is what I am seeing: 
![citation](https://user-images.githubusercontent.com/8431057/74289812-dfd8c000-4ce4-11ea-91c9-e3968b591344.jpg)

**Comment by 1313e** [comment]
Oh, that. That will never get fixed as those previews only get generated once.

**Comment by mbobra** [comment]
Ohhhh, I did not know that 😳 Thanks for letting me know!

**Comment by arfon** [comment]
Yeah, I think this is cached. The only thing we can do here is delete the original tweet an resend it from the JOSS account (which I'm more than happy to).

Lemme know what you'd like us to do @1313e.

**Comment by 1313e** [comment]
As I doubt anyone will use citation information from a preview, don't bother.

**Comment by 1313e** [comment]
@arfon Do you, by any chance, know how long it usually takes for ADS to index new JOSS papers?
I was looking at ADS, and it seems that it indexes new JOSS papers that it flags as 'astronomy-related' incredibly quickly, whereas other JOSS papers take quite some time.
(All JOSS papers published this year that are indexed by ADS, which is 5 in total, are flagged as 'astronomy-related', which I doubt is a coincidence.)

**Comment by arfon** [comment]
I don't sorry. Last time I checked it was every couple of months.

**Comment by mbobra** [comment]
@1313e If you want to speed up the process, you can ask ADS to index your paper [using this form](http://adsabs.harvard.edu/adsfeedback/submit_abstract.php) and they will likely approve it right away.
