### ISSUE TITLE
[REVIEW]: vfi: Classification by Voting Feature Intervals 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2005]
**Submitting author:** @chkoar (<a href="http://orcid.org/0000-0002-5021-1442">Christos K. Aridas</a>)
**Repository:** <a href="https://github.com/chkoar/vfi" target ="_blank">https://github.com/chkoar/vfi</a>
**Version:** 0.0.1
**Editor:** @mbobra
**Reviewer:** @jakryd, @dflemin3
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/e62d4675044e138e648b93e418dd6e32/status.svg)](https://joss.theoj.org/papers/e62d4675044e138e648b93e418dd6e32)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e62d4675044e138e648b93e418dd6e32"><img src="https://joss.theoj.org/papers/e62d4675044e138e648b93e418dd6e32/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e62d4675044e138e648b93e418dd6e32/status.svg)](https://joss.theoj.org/papers/e62d4675044e138e648b93e418dd6e32)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/chkoar/vfi" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jakryd & @dflemin3, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mbobra know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/chkoar/vfi">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@chkoar) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/chkoar/vfi">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@chkoar) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jakryd, @dflemin3 it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02005/joss.02005/10.21105.joss.02005.pdf)

**Comment by mbobra** [comment]
@jakryd @dflemin3 Thank you for agreeing to review this submission! Whedon generated a checklist and linked a reviewer guide above -- please feel free to ask me any questions you may have throughout this process.

**Comment by arfon** [comment]
Hi all, my sincere apologies for not catching this sooner but I'm afraid we're going to have to reject this submission. While it looks to be a useful little package, this falls into our ['minor utility'](https://joss.readthedocs.io/en/latest/submitting.html) category.

@chkoar @mbobra - apologies for not catching this at the `pre-review` stage of the process when editorial decisions in JOSS like this are meant to be made.

@jakryd @dflemin3 - thank you for agreeing to review this submission. From the looks of things it appears that you've not started your reviews yet so hopefully we've not wasted too much of your time.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by mbobra** [comment]
@arfon No worries, I understand. @danielskatz asked me to edit this submission and I was happy to do so.

I do want to point out that @jakryd @dflemin3 were both excited about reviewing for JOSS and @dflemin3 even went through the trouble of reading the JOSS Editorial Guide to prep for this review. So I hope we can be a little better about identifying minor submissions before we solicit reviewers. I do understand that mix-ups happen sometimes.

A big thank you to @jakryd @dflemin3 for volunteering so readily on top of your already busy workload ☀️

**Comment by danielskatz** [comment]
Sorry - I think the new stats that we get when start a pre-review will help in seeing submissions that need more inspection

**Comment by chkoar** [comment]
> While it looks to be a useful little package, this falls into our 'minor utility' category.

Dear @arfon, @mbobra  and @danielskatz,

I respectively disagree that the package is a "minor utility" and I would incline you to reconsider. Currently, it contains a real world classifier and even at this stage it can be used in research works. My main motivation, in order to identify if the package at this stage could be considered as minor utility and make the submission, were utilities like [this](https://joss.theoj.org/papers/10.21105/joss.01593) and [this](https://joss.theoj.org/papers/10.21105/joss.00124) that have been accepted for publication in JOSS. At the time of publication, the former had one public function while the latter had two public functions.

Best,
Chris

**Comment by arfon** [comment]
Dear @chkoar, firstly I want to apologize again for how this submission was handled. This submission was flagged for rejection early on by a handling editor but got lost in a transition between editors over the holiday season.

To address your concern about this submission being treated differently to those of a similar size/scope: the JOSS editorial team has recently carried out a significant review of our scope as a journal (i.e. what submissions are considered in/out of scope) and your paper and software was an example of us applying these criteria. Should these other two submissions be submitted today we would reject them too.

**Comment by chkoar** [comment]
Dear @arfon, 

Hopefully, this will be my last reply.

> the JOSS editorial team has recently carried out a significant review of our scope as a journal

As a feedback, you should state how they differ with the past? As I said previously my motivation for submission were past accepted papers and JOSS' [about](https://joss.theoj.org/about) page.

> To address your concern about this submission being treated differently to those of a similar size/scope

Please, don't get me wrong. The whole thing is not about my rejection. But, it seems strange (apart from your change of scope) that an open journal like this has inconsistent decisions about submissions.  

For example:
You accept [this](https://joss.theoj.org/papers/10.21105/joss.00124) (which was a clear example of minor utility in my honest opinion), later, as handling editor, you promote [this](https://github.com/openjournals/joss-reviews/issues/804) submission from pre-review stage to [review](https://github.com/openjournals/joss-reviews/issues/928) and you reject it as minor utility. Then again you accept [this](https://joss.theoj.org/papers/10.21105/joss.01593) submission but you reject [this](https://github.com/openjournals/joss-reviews/issues/1966) one for the same reasons you accepted the previous ones.

In [this](https://joss.theoj.org/about) page of the JOSS site you state

```
JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or the execution of research experiments; extracts knowledge from large data sets; offers a mathematical library; or similar.

JOSS submissions must:
    Be open source (i.e., have an OSD-compliant license).
    Have an obvious research application.
    Be feature-complete (no half-baked solutions) and be designed for maintainable extension (not one-off modifications).
    Not be minor 'utility' packages, such as 'thin' API clients.
```
In contrast to the other rejected submissions that I mentioned, I believe that my submission was fulfilling the definition of research software and all the above submission musts.

In my honest opinion, since a submission has passed by the hands of an Associate Editor-in-Chief and an Editor and the reviewers were found, the submission should go for a review round. In my eyes their role was nullified. At the end of the day the EiC decides.

Best,
Chris
