### ISSUE TITLE
[REVIEW]: LiberTEM: Software platform for scalable multidimensional data processing in transmission electron microscopy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2006]
**Submitting author:** @uellue (<a href="http://orcid.org/0000-0001-6635-9567">Dieter Weber</a>)
**Repository:** <a href="https://github.com/LiberTEM/LiberTEM" target ="_blank">https://github.com/LiberTEM/LiberTEM</a>
**Version:** 0.5.0
**Editor:** @majensen
**Reviewers:** @alvarolopez, @fedorov
**Archive:** <a href="https://doi.org/10.5281/zenodo.3763313" target="_blank">10.5281/zenodo.3763313</a>

## Status

[![status](https://joss.theoj.org/papers/bab08517a6d948a24c29d86caa0bcdda/status.svg)](https://joss.theoj.org/papers/bab08517a6d948a24c29d86caa0bcdda)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/bab08517a6d948a24c29d86caa0bcdda"><img src="https://joss.theoj.org/papers/bab08517a6d948a24c29d86caa0bcdda/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/bab08517a6d948a24c29d86caa0bcdda/status.svg)](https://joss.theoj.org/papers/bab08517a6d948a24c29d86caa0bcdda)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/LiberTEM/LiberTEM" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@alvarolopez & @fedorov, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @majensen know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/LiberTEM/LiberTEM">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@uellue) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/LiberTEM/LiberTEM">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@uellue) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @alvarolopez, @mamcdona77 it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.2450624 is OK
- 10.1145/1327452.1327492 is OK
- 10.1109/nuicone.2012.6493198 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1145/2934664 is OK
- 10.25080/majora-7b98e3ed-013 is OK
- 10.5281/ZENODO.3396791 is OK
- 10.5281/ZENODO.2649351 is OK
- 10.1017/s1431927619000497 is OK
- 10.5281/ZENODO.3572855 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1142/11389 is INVALID
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02006/joss.02006/10.21105.joss.02006.pdf)

**Comment by alvarolopez** [comment]
@majensen I am done, the paper is ok to go in its current form.

**Comment by majensen** [comment]
@alvarolopez - very much appreciated!
@mamcdona77 - how are things progressing?

**Comment by mamcdona77** [comment]
Will update early next week 

Michael 
Michael A McDonald, MD, PhD

**Comment by uellue** [comment]
@whedon generate pdf

**Comment by uellue** [comment]
Would it be OK to include a small wording improvement in the first sentence?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02006/joss.02006/10.21105.joss.02006.pdf)

**Comment by majensen** [comment]
@uellue of course!

**Comment by majensen** [comment]
@mamcdona77 - How is it coming along? Can I help in any way? Thanks

**Comment by majensen** [comment]
@whedon add @fedorov as reviewer

**Comment by whedon** [comment]
OK, @fedorov is now a reviewer

**Comment by majensen** [comment]
Thanks @federov for agreeing to review this work. I've added a checklist for you in the header message.

**Comment by majensen** [comment]
Thanks @fedorov for agreeing to review this work.

**Comment by fedorov** [comment]
@uellue very nice work! I submitted just one issue, and also have few clarification questions below, before I check off the remaining items in the checklist (am not sure if I should submit issues about those):
* I could not find (or missed) pointers to publicly available sample datasets that software users could easily access - would you be able to add some pointers to the documentation?
* there are statements claiming functionality and performance advantages over alternatives, but it is not clear if those were confirmed anywhere. Do you have any additional citations comparing performance with other packages? I am aware of the [performance section of the documentation](https://libertem.github.io/LiberTEM/performance.html), but the paper mentions few other packages, and the performance section does not include comparison with those. Since there are statements claiming superiority in the paper, it would be good to back them with evidence.
* I think it would be helpful to the user if the documentation contained a section listing similar packages (something along the lines that you already have in the submitted paper PDF). Would it make sense to add that section to the documentation?

**Comment by uellue** [comment]
Hi @fedorov, thank you for the feedback! Good points, we'll work on it.

**Comment by majensen** [comment]
@whedon remove @mamcdona77 as reviewer

**Comment by whedon** [comment]
OK, @mamcdona77 is no longer a reviewer

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by uellue** [comment]
Hi @fedorov @majensen FYI, I have been working on a deeper comparison between Dask and LiberTEM both in programming model and benchmarking. That's still WIP. Two things can already be said: First, Dask has improved impressively since I last looked, and second, the comparison has already helped us to identify opportunities for improvement: https://github.com/LiberTEM/LiberTEM/issues/554#issuecomment-601668112

In that sense, many thanks! More details to follow when the comparison is done. :-)

**Comment by fedorov** [comment]
@uellue thank you for your note. It is very encouraging to see that review made a difference for you, and will ultimately benefit the user of your library!

**Comment by majensen** [comment]
@uellue - how's it going?

**Comment by uellue** [comment]
@majensen Work is progressing, I hope to have an update in a week or two!

**Comment by majensen** [comment]
@uellue - hope you are staying healthy! How are things coming along?

**Comment by uellue** [comment]
@majensen Progress! It just turned into a bigger update, closing some long-standing TODO items in the process: https://github.com/LiberTEM/LiberTEM/pull/706

**Comment by majensen** [comment]
@uellue @fedorov (and @alvarolopez ) - checking in. I see Andrey has only the three Functionality items to check off before completion. I know Dieter has been working through a number of improvements. My thought is, if the functionality as it stands (in medias res) is acceptable to Andrey, maybe we can go forward with completion of the review and towards a recommendation for publication. Dieter, you would be free and encouraged to continue development, but with the publication in your pocket. 
If the editorial powers have an issue with this plan, they will manifest themselves. What do you guys think?
Mark

**Comment by uellue** [comment]
@majensen @fedorov the installation instructions have been fixed, as far as I am aware. We now have some information on reference datasets, too.

The performance bottleneck that we found when addressing the performance tests is mostly fixed. In detail, sparse matrix products with memory-mapped partitions led to large intermediate result buffers that didn't fit the L3 cache. That severely hurt performance of the scipy.sparse library that we use. The same underlying cause applies to a number of other operations. The fix in the back-end is merged LiberTEM/LiberTEM#706, it just has to be used properly in the front-end part of the code, and we have to benchmark it properly. Solving it involved taking on a long-standing item for restructuring the I/O back-end, that's why it took so long.

About related packages, we have it relatively hidden in our acknowledgments more as a hat tip towards other projects, but we could also move it to a more visible location like README.rst if you think it would be a valuable resource for users.

In that sense, I could still work on proper benchmarks, but we can also remove performance claims and wrap up the paper before. :-)

**Comment by fedorov** [comment]
> About related packages, we have it relatively hidden in our acknowledgments

What I referred to in my comments were not related packages, but packages similar in functionality. I recall you mention several of those in your paper, but I did not find them in the documentation. I believe it would be helpful for a user who searches for tools implementing certain functionality to understand better how your package is unique relative to other similar packages (if such exist).

> In that sense, I could still work on proper benchmarks, but we can also remove performance claims and wrap up the paper before. :-)

👍

**Comment by majensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02006/joss.02006/10.21105.joss.02006.pdf)

**Comment by majensen** [comment]
Thanks guys. Since the associate editor-in-chief will look askance at unchecked items, let me propose that when @fedorov is satisfied with @uellue 's updates to paper, software, or both, that @fedorov can check the remaining two boxes and ping me here. 
At that point, I will do a proofing once-over which may result in a minor pull request for wording or reference resolution, then will we call in the EiC.

**Comment by fedorov** [comment]
@majensen done!

**Comment by majensen** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.2450624 is OK
- 10.1145/1327452.1327492 is OK
- 10.1109/nuicone.2012.6493198 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1145/2934664 is OK
- 10.25080/majora-7b98e3ed-013 is OK
- 10.5281/ZENODO.3396791 is OK
- 10.5281/ZENODO.2649351 is OK
- 10.1017/s1431927619000497 is OK
- 10.5281/ZENODO.3572855 is OK
- 10.1142/9789811204579_0005 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by majensen** [comment]
@uellue - The proof looks good to me, just two items for you to review:

in paper.md line 140:
* "an adapted programming model" - Do you mean "adaptive" here?

in paper.bib line 5
* "Development of ..." - I note the title at the archive 10.5281/zenodo.2450624 is "Evolution of..."

If you would rectify these to your liking, what we need next is the DOI to an archive containing the repo. The slight issue between the current Zenodo archive and the paper an sich is the author list. JOSS prefers that the author list on the archive match that on the paper. Would this be difficult to adjust?

**Comment by uellue** [comment]
Hi @majensen and @fedorov,

Thx for the feedback!

I just opened a pull request in our repository to update the paper. The performance claims in comparison to other projects are removed, since benchmarking would still take some time to implement properly. The LiberTEM reference is updated to 0.5.0. I've asked the co-creators that have since started contributing to LiberTEM if they would like to join as co-authors.

Two co-creators of LiberTEM, Colin Ophus and Jay van Schyndel, had previously declined to be co-authors since the made only small contributions that they felt didn't warrant co-authorship on the paper. Peter Simon and Jaeweon Shin hadn't replied to an invitation to be co-author.

As next steps, I'll wait for response from the new co-authors, update the paper's author list accordingly, merge, and then we can build a new draft here.

**Comment by fedorov** [comment]
> Two co-creators of LiberTEM, Colin Ophus and Jay van Schyndel, had previously declined to be co-authors since the made only small contributions that they felt didn't warrant co-authorship on the paper. 

It's yours and their call, but IMHO if they made contribution to the code described in the paper, this most definitely justifies their co-authorship on the paper.

**Comment by uellue** [comment]
@fedorov yes, I agree that their co-authorship would be justified. We had a discussion about that some time ago and the result was [our authorship policy](https://libertem.github.io/LiberTEM/authorship.html) where everybody who contributed to the repository is invited to be co-author.

**Comment by fedorov** [comment]
It is remarkable how organized your community is. Once you mentioned it, it is obvious that Authorship policy is a must to have, but I am sure I could find quite a few of established projects that don't have one.

**Comment by uellue** [comment]
Well, we added one when we needed one! :-D The main discussion was actually in the PR for the first draft of this paper: https://github.com/LiberTEM/LiberTEM/pull/460

Main points were that the decision can't be arbitrary, but based on rules, and that we have to remain able to act and fulfill all requirements for authorship of a paper (consent and approval of a draft by all co-authors) even if we have a lot of co-authors in LiberTEM.

**Comment by uellue** [comment]
@whedon generate PDF

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02006/joss.02006/10.21105.joss.02006.pdf)

**Comment by uellue** [comment]
Ok, this should be it! :-) Just had a last look at the proof and it looks good.

**Comment by majensen** [comment]
Great @uellue - can you provide the doi for your archive here- then I will twiddle various knobs and then summon the editors in chief--

**Comment by uellue** [comment]
> Great @uellue - can you provide the doi for your archive here- then I will twiddle various knobs and then summon the editors in chief--

@majensen sounds good! This is the DOI for LiberTEM 0.5.0: https://doi.org/10.5281/zenodo.3763313

**Comment by uellue** [comment]
@majensen Wait, I noticed something, forgot a co-author!

**Comment by uellue** [comment]
@whedon generate PDF

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02006/joss.02006/10.21105.joss.02006.pdf)

**Comment by uellue** [comment]
Ok, looks good now.

**Comment by majensen** [comment]
@uellue I see the following people not in the paper author list, but listed in the archive

Dey, Shankhadeep;		     
 Levin, Barnaby D.A.;		     
 Ophus, Colin;			     
 Peter, Simon;			     
 Schyndel van, Jay;
 Shin, Jaeweon;
 Sunku, Sai;

If these folks are not willing to be on the paper, let me know here. I can understand why they would remain on the archive, so I will want to have an EIC weigh in on the protocol in this situation.

**Comment by uellue** [comment]
@majensen In the archive we have everybody who contributed a commit or who contributed to LiberTEM in other ways that establish co-authorship of the software. One would have to actively opt out of being listed there since contributing commits to a software automatically establishes co-authorship. Furthermore, being a co-author of the software doesn't mean endorsement or responsibility for the entire content.

However, to be co-author of a paper means responsibility and endorsement for the entire manuscript. That's why we require co-authors to actively opt in per our authorship policy. Some people didn't respond, and some responded that they didn't want to be on the paper. All people with extensive contributions to LiberTEM are also co-authors of the paper.

**Comment by majensen** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.2450624 is OK
- 10.1145/1327452.1327492 is OK
- 10.1109/nuicone.2012.6493198 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1145/2934664 is OK
- 10.25080/majora-7b98e3ed-013 is OK
- 10.5281/ZENODO.3396791 is OK
- 10.5281/ZENODO.2649351 is OK
- 10.1017/s1431927619000497 is OK
- 10.5281/ZENODO.3763313 is OK
- 10.1142/9789811204579_0005 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by majensen** [comment]
@whedon set 10.5281/zenodo.3763313 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3763313" target="_blank">10.5281/zenodo.3763313</a> is the archive.

**Comment by majensen** [comment]
@whedon set 0.5.0 as version

**Comment by whedon** [comment]
OK. 0.5.0 is the version.

**Comment by majensen** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1484

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1484, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by majensen** [comment]
@openjournals/joss-eics - Please note that LiberTEM is a significant and ongoing project that has its own policies for author and contributor credit. It also has its own Zenodo archive location, for which 0.5.0 is the latest version and incorporates the comments of the reviewers here. 

The author list on this paper is a subset of the author list on the archive, because of the nature of the project's community guidelines. (See [@uellue comment](https://github.com/openjournals/joss-reviews/issues/2006#issuecomment-641097965) and prior.) I hope that there can be a variance allowed in the JOSS policy of requiring the author lists to be the same on both the paper and the archive in this instance. Thanks -- @majensen

**Comment by uellue** [comment]
@majensen The final proof looks good, I just verified the text, links and Orcids.

**Comment by labarba** [comment]
I can see in the comments above the rationale for the different author lists in the Zenodo archive and the JOSS paper. But is there any reason why the Zenodo archive title cannot be made to match the JOSS paper archive?

**Comment by majensen** [comment]
Well, the archives for the project LiberTEM have a [history of consistent naming](https://zenodo.org/search?page=1&size=20&q=conceptrecid:%221477847%22&sort=-version&all_versions=True). If I were to give a reason as an advocate for the author, I would say that the JOSS paper is a unique event in its history as a project, associated with the latest version of LiberTEM. Independently of this event, there is an established LiberTEM developer community and user base which has come to expect a certain convention in the naming of the software package that they contribute to and depend on. IMO, JOSS is fortunate in having the opportunity to publish this mature work under its masthead, and the journal might reasonably grant flexibility in this situation.

**Comment by uellue** [comment]
@labarba Is this a requirement that there's a 1:1 match with the Zenodo title? It seems that I overlooked it.

The title of the Zenodo deposition is the default one if GitHub integration for releases is activated. We can also call the paper `LiberTEM/LiberTEM: 0.5.0` if you prefer. A more descriptive title would just be more appealing, I figured.

As @majensen wrote, we already have quite a number of releases on Zenodo and it would seem a bit odd to rename it just to match a paper title about it.

**Comment by labarba** [comment]
We have a (soft) policy of asking authors to manually edit the metadata of the Zenodo deposit after the release has done its thing, so the titles and author list matches the paper. Of course we don't want you to change the title of the _paper_ to match the repo name. Look, I'm not insisting. That's what we regularly do. If you have your reasons, do as you wish.

**Comment by uellue** [comment]
@labarba Thank you for the clarification! If possible, I'd like to leave it as it is.  Since both paper title and archive contain the unique name "LiberTEM", I think that readers will understand that the two are referring to each other even if the titles don't match 100%. :-)

**Comment by majensen** [comment]
@labarba Sounds like we are ready to pull the trigger

**Comment by danielskatz** [comment]
@majensen - when a submission is ready to be accepted, please tag @openjournals/joss-eics to be sure you get the on-duty AEiC, which changes week to week...

**Comment by majensen** [comment]
@openjournals/joss-eics This work is recommended for publication.

**Comment by danielskatz** [comment]
👋 @uellue - if you can merge https://github.com/LiberTEM/LiberTEM/pull/823, we can finalize the publication

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.2450624 is OK
- 10.1145/1327452.1327492 is OK
- 10.1109/nuicone.2012.6493198 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1145/2934664 is OK
- 10.25080/majora-7b98e3ed-013 is OK
- 10.5281/ZENODO.3396791 is OK
- 10.5281/ZENODO.2649351 is OK
- 10.1017/s1431927619000497 is OK
- 10.5281/ZENODO.3763313 is OK
- 10.1142/9789811204579_0005 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1507

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1507, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
👋 @uellue  - sorry, I missed one - can you also merge https://github.com/LiberTEM/LiberTEM/pull/824

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1274424941748813824) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1508
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02006](https://doi.org/10.21105/joss.02006)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by sk1p** [comment]
@danielskatz Thank you! :partying_face: :tada:

**Comment by danielskatz** [comment]
Thanks to @alvarolopez & @fedorov for reviewing!
And @majensen for editing!

And congratulations to @uellue (Dieter Weber) and co-authors!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02006/status.svg)](https://doi.org/10.21105/joss.02006)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02006">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02006/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02006/status.svg
   :target: https://doi.org/10.21105/joss.02006
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02006/status.svg)](https://doi.org/10.21105/joss.02006)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by uellue** [comment]
Thank you @danielskatz @alvarolopez @fedorov @majensen for reviewing and managing the submission!

@sk1p @kruzaeva @woozey @anandbaburajan @twentyse7en @jan-car @irahulcse @sayandip18 @magnunor Knut @rafaldb Many thanks and congratulations!

**Comment by uellue** [comment]
As a general remark, open writing and open review in combination with GitHub worked really well IMO, and the whole process was a refreshing, pleasant and productive experience. I'll be sure to recommend JOSS for papers like this. 👍
