### ISSUE TITLE
[PRE REVIEW]: ExTemp: A computational and image-processing suite for extracting temporal barcodes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2009]
**Submitting author:** @shalinshah1993 (<a href="http://orcid.org/0000-0002-1406-3577">Shalin Shah</a>)
**Repository:** <a href="https://github.com/shalinshah1993/temporalDNAbarcodes" target ="_blank">https://github.com/shalinshah1993/temporalDNAbarcodes</a>
**Version:** 1.0
**Editor:** @csoneson
**Reviewers:** @lbugnon, @SirSharpest, @RealPolitiX

**Author instructions**

Thanks for submitting your paper to JOSS @shalinshah1993. **Currently, there isn't an JOSS editor assigned** to your paper.

@shalinshah1993 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1021/acssynbio.9b00010 may be missing for title: Improved optical multiplexing with temporal DNA barcodes
- https://doi.org/10.1007/978-3-030-00030-1_5 may be missing for title: Temporal DNA barcodes: A time-based approach for single-molecule imaging
- https://doi.org/10.1021/acs.nanolett.9b00590 may be missing for title: Programming temporal DNA barcodes for single-molecule fingerprinting
- https://doi.org/10.1364/oe.22.015982 may be missing for title: Localization events-based sample drift correction for localization microscopy with redundant cross-correlation algorithm

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02009/joss.02009/10.21105.joss.02009.pdf)

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (449.8 files/s, 50934.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                          40            370           1159           1560
reStructuredText                 1            249              0           1424
Markdown                         5            119              0            287
HTML                             1             38            115             74
TeX                              1              3              0             38
-------------------------------------------------------------------------------
SUM:                            48            779           1274           3383
-------------------------------------------------------------------------------


Statistical information for the repository '2009' was gathered on 2020/01/11.
No commited files with the specified extensions were found.
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@shalinshah1993 I will be looking for an editor to help with this submission. In the mean time can you check the above DOI's which appear to be missing? You can update the pdf here yourself by running `@whedon generate pdf`.

**Comment by Kevin-Mattheus-Moerman** [comment]
@will-rowe @csoneson would one of you be able to edit this one?

**Comment by shalinshah1993** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02009/joss.02009/10.21105.joss.02009.pdf)

**Comment by csoneson** [comment]
This is a bit out of my expertise, so if @will-rowe feels more comfortable taking it that would be great. Otherwise I'll give it a go.

**Comment by will-rowe** [comment]
Likewise - this is not something I am familiar with. I'm equally happy to take it on if needs be though.

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋 @shalinshah1993 - I'll handle your submission. I'll start by looking for suitable reviewers (thanks for the suggestions above).

**Comment by shalinshah1993** [comment]
Thank you for accepting the request! While not on that list, I used to be an active contributor to an open-source organization called SBML (https://github.com/nrnb) in the past and also know a few folks who are great software engineers and researchers, if they are interested in reviewing. https://github.com/draeger-lab https://github.com/niko-rodrigue

**Comment by csoneson** [comment]
👋 @sirsharpest, @caldarolamartin, @lbugnon, @RealPolitiX - would you be interested in reviewing this submission for JOSS? 

> ExTemp: A computational and image-processing suite for extracting temporal barcodes

**Comment by lbugnon** [comment]
@csoneson I'm in! please send reviewer instructions just in case.

**Comment by csoneson** [comment]
@lbugnon Great, thanks! Reviewer instructions are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html 
Once we have at least two reviewers I will open the actual review issue, where the review will take place (you will have your reviewer checklist there).

**Comment by SirSharpest** [comment]
Yes, I'd be glad to review!

**Comment by csoneson** [comment]
@SirSharpest, @RealPolitiX - brilliant! I'll assign the three of you and start the review issue.

**Comment by csoneson** [comment]
@whedon assign @lbugnon as reviewer

**Comment by whedon** [comment]
OK, @lbugnon is now a reviewer

**Comment by csoneson** [comment]
@whedon add @SirSharpest as reviewer

**Comment by whedon** [comment]
OK, @SirSharpest is now a reviewer

**Comment by csoneson** [comment]
@whedon add @RealPolitiX as reviewer

**Comment by whedon** [comment]
OK, @RealPolitiX is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2026. Feel free to close this issue now!
