### ISSUE TITLE
[PRE REVIEW]: Text-Fabric: Text representation for text with stand-off annotations and linguistic features

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#201]
**Submitting author:** @dirkroorda (<a href="http://orcid.org/0000-0002-2680-8724">Dirk Roorda</a>)
**Repository:** <a href="https://github.com/ETCBC/text-fabric" target ="_blank">https://github.com/ETCBC/text-fabric</a>
**Version:** v2.3.6
**Editor:** @acabunoc
**Reviewer:** @47rooks

**What this issue is for**

Thanks for submitting your paper to JOSS @dirkroorda. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: @acabunoc - would you be willing to edit this submission for JOSS?

**Comment by dirkroorda** [comment]
Yes.

**Comment by acabunoc** [comment]
@arfon I'm on it!

**Comment by acabunoc** [comment]
@whedon assign @acabunoc as editor

**Comment by whedon** [comment]
OK, the editor is @acabunoc

**Comment by acabunoc** [comment]
Hey @dirkroorda, I'll reach out to some potential reviews soon, but do you have anyone in mind? I like to try to find a couple people to review.

**Comment by dirkroorda** [comment]
maybe Daniel Semler. He is a user, and we communicate a lot. Maybe not independent enough. That will hold for most people I have in mind.

**Comment by arfon** [comment]
Friendly reminder on this @acabunoc :smile:

**Comment by acabunoc** [comment]
@dirkroorda is Daniel Semler on GitHub? can't seem to find him -- thanks for the recommendation!

**Comment by acabunoc** [comment]
Hi @jkahn @richardlitt @hausen @desilinguist 👋 ! Would any of you be up for reviewing this? You all seems to have python experience along with either lingustics or graphs.

Review guidelines can be found here: http://joss.theoj.org/about#reviewer_guidelines

**Comment by desilinguist** [comment]
Unfortunately, I'm completely swamped for the next month or so. Apologies.

**Comment by jkahn** [comment]
Interested, but like Nitin somewhat swamped at the moment. Perhaps a little
less swamped than Nitin.

Ping me again if you haven't found anyone by... the end of April?

--Jeremy

**Comment by RichardLitt** [comment]
I am also swamped. Founded a company last week and traveling internationally this and the next week. 

Taking a quick look now, I am confused; I don't see a PDF. Is the `paper.md` the only submission, here?

**Comment by arfon** [comment]
> Taking a quick look now, I am confused; I don't see a PDF. Is the paper.md the only submission, here?

@RichardLitt - we generally compile the PDF after review these days.

**Comment by dirkroorda** [comment]
This is Daniel Semler on github https://github.com/47rooks

**Comment by arfon** [comment]
@47rooks - would you be willing to review this submission for JOSS?

**Comment by 47rooks** [comment]
Hey arfon, I can take a look. I don't see a paper to look at here but then this would be my first review so I need to find my way around. If you can point me to the text I can take a look. 
Thx
D

**Comment by arfon** [comment]
@whedon assign @47rooks as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @47rooks

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/294. Feel free to close this issue now!

**Comment by arfon** [comment]
@47rooks - please head over to #294 for the actual review.
