### ISSUE TITLE
[REVIEW]: CaPS: Casimir Effect in the Plane-Sphere Geometry

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2011]
**Submitting author:** @michael-hartmann (<a href="http://orcid.org/0000-0002-9245-8582">Michael Hartmann</a>)
**Repository:** <a href="https://github.com/michael-hartmann/caps/" target ="_blank">https://github.com/michael-hartmann/caps/</a>
**Version:** 0.5
**Editor:** @danielskatz
**Reviewer:** @eschnett, @jwuttke
**Archive:** <a href="https://doi.org/10.5281/zenodo.3627969" target="_blank">10.5281/zenodo.3627969</a>

## Status

[![status](https://joss.theoj.org/papers/62338dfc973364495fd30be48361f678/status.svg)](https://joss.theoj.org/papers/62338dfc973364495fd30be48361f678)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/62338dfc973364495fd30be48361f678"><img src="https://joss.theoj.org/papers/62338dfc973364495fd30be48361f678/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/62338dfc973364495fd30be48361f678/status.svg)](https://joss.theoj.org/papers/62338dfc973364495fd30be48361f678)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/michael-hartmann/caps/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@eschnett & @jwuttke, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/michael-hartmann/caps/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@michael-hartmann) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/michael-hartmann/caps/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@michael-hartmann) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @eschnett, @jwuttke it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.crhy.2011.05.004 is OK
- 10.1103/PhysRevLett.87.211801 is OK
- 10.1103/PhysRevB.63.033402 is OK
- 10.1093/acprof:oso/9780199238743.001.0001 is OK
- 10.1016/j.crhy.2012.04.008 is OK
- 10.1103/PhysRevLett.109.160403 is OK
- 10.1088/1367-2630/8/10/243 is OK
- 10.1103/PhysRevLett.99.170403 is OK
- 10.1007/s10915-013-9714-z is OK
- 10.21105/joss.01167 is OK
- 10.1103/PhysRevE.91.033203 is OK
- 10.1103/PhysRevE.92.042125 is OK
- 10.1103/PhysRevLett.119.043901 is OK
- 10.1088/1402-4896/aae34e is OK
- 10.1103/PhysRevLett.96.080403 is OK
- 10.1103/PhysRevB.100.081406 is OK
- 10.1103/PhysRevA.100.052511 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02011/joss.02011/10.21105.joss.02011.pdf)

**Comment by danielskatz** [comment]
HI @eschnett & @jwuttke - thanks for agreeing to review this submission!

Your job is to review the [paper](https://github.com/openjournals/joss-papers/blob/joss.02011/joss.02011/10.21105.joss.02011.pdf) and the repository according to the criteria in your review list in the first comment in this issue, and check things off as you find them satisfactory. If you see things that you think need to be changed, open an issue in the source repository (and add a note about this review issue to link them to here), or if they are small, just state them here in this issue.

Please also read the first 2 comments in this issue carefully.

Let me know if you have any questions.

**Comment by jwuttke** [comment]
I submitted 7 issues. Otherwise I am very satisfied with project & paper, and I recommend acceptance in JOSS.

**Comment by danielskatz** [comment]
Thanks!

Can you put the URL of this issue (https://github.com/openjournals/joss-reviews/issues/2011) in the issues you opened?  This helps us view them from here, where we can see if they are open or closed, for example

**Comment by danielskatz** [comment]
👋 @michael-hartmann - it's your choice at this if you want to work on the issues opened by @jwuttke or wait for @eschnett to finish his review and see if there are more issues raised.

**Comment by jwuttke** [comment]
@michael-hartmann - My issues are suggestions, not imperatives. I hope you will find some of them useful, but you are free to disagree.

**Comment by michael-hartmann** [comment]
@danielskatz I am working on the issues right now.

@jwuttke Thank you for your suggestions. I agree with your issues and I will fix them as soon as possible. :-)

**Comment by eschnett** [comment]
@michael-hartmann You might want to refer to a particular version number (release) of the software in the paper. The current release is 0.4.2, while the master branch is 0.5.

**Comment by michael-hartmann** [comment]
@eschnett My plan is actually make the 0.5 release as soon as all the changes from the review are implemented.

**Comment by eschnett** [comment]
@michael-hartmann If you do, consider referencing this version in the paper. Also consider getting a DOI for that version (e.g. from Zenodo); I don't know whether JOSS recommends this anyway.

**Comment by eschnett** [comment]
@michael-hartmann Do you describe the state of the art for numerical Casimir calculations in your paper? Are there other, similar packages available? What are their limitations?

**Comment by danielskatz** [comment]
@eschnett  - part of the JOSS acceptance process is declaring a specific version (often new at that time), so don't worry about this too much at this point

**Comment by michael-hartmann** [comment]
The first paragraph on the second page of the [proof](https://github.com/openjournals/joss-papers/blob/joss.02011/joss.02011/10.21105.joss.02011.pdf) describes the numerical problems that render the evaluation of the Casimir free energy difficult when the sphere radius is much larger than the separation between sphere and plate. (This case is experimentally the most interesting case.). The second paragraph on the second page describes how we solve these numerical issues.

I am not aware of any other available package to compute the Casimir free energy for this configuration. Also, nobody in the Casimir community has published exact numerical data for experimentally relevant parameters (there are lot of papers that use approximations, though.). Therefore, I think our approach is the state-of-the-art.

@eschnett Does this answer your question?

**Comment by eschnett** [comment]
@michael-hartmann Do you want to add a note corresponding to your second paragraph above to the paper? This knowledge will tell others that your work is unique, instead of you not ignoring the competition.

**Comment by michael-hartmann** [comment]
@eschnett Thank you for your suggestion. I will add a note. Hopefully, I have some time to work on it on the weekend. :)

**Comment by eschnett** [comment]
@michael-hartmann The last item on my to-do list is a description of the state of the field. Can you let me know when/whether you have added this?

**Comment by michael-hartmann** [comment]
@eschnett Sorry for the delay, I have not forgotten this point. The week tended out to be busier than expected. I will add the remark either on the weekend. :-)

**Comment by michael-hartmann** [comment]
@jwuttke: Are you fine with the solution proposed for https://github.com/michael-hartmann/caps/issues/150?

**Comment by michael-hartmann** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02011/joss.02011/10.21105.joss.02011.pdf)

**Comment by michael-hartmann** [comment]
@eschnett: We have added an additional paragraph mentioning two other packages that are able to compute the Casimir free energy and briefly describing the different focus. It is the second to last paragraph befor the acknowldgements starting with "Other packages that allow...".

**Comment by eschnett** [comment]
@danielskatz I recommend to accept the manuscript.

**Comment by danielskatz** [comment]
@jwuttke - how does this now look to you?

**Comment by jwuttke** [comment]
looks good

**Comment by danielskatz** [comment]
👋 @michael-hartmann - At this point could you:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g. figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission, which will include a careful proofreading.

**Comment by gertingold** [comment]
@eschnett, @jwuttke: Thank you very much for the effort you have put into the review and for the constructive criticism.

**Comment by michael-hartmann** [comment]
A big thank you to @eschnett and @jwuttke for taking time to review and your good suggestions. Also thank you @danielskatz for your work and time.

The necessary information:
 * The git tag is [v0.5](https://github.com/michael-hartmann/caps/releases/tag/v0.5).
 * zenodo DOI: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3627969.svg)](https://doi.org/10.5281/zenodo.3627969)

**Comment by danielskatz** [comment]
@whedon set 0.5 as version

**Comment by whedon** [comment]
OK. 0.5 is the version.

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3627969 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3627969" target="_blank">10.5281/zenodo.3627969</a> is the archive.

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.crhy.2011.05.004 is OK
- 10.1103/PhysRevLett.87.211801 is OK
- 10.1103/PhysRevB.63.033402 is OK
- 10.1093/acprof:oso/9780199238743.001.0001 is OK
- 10.1016/j.crhy.2012.04.008 is OK
- 10.1103/PhysRevLett.109.160403 is OK
- 10.1088/1367-2630/8/10/243 is OK
- 10.1103/PhysRevLett.99.170403 is OK
- 10.1007/s10915-013-9714-z is OK
- 10.21105/joss.01167 is OK
- 10.1103/PhysRevE.91.033203 is OK
- 10.1103/PhysRevE.92.042125 is OK
- 10.1103/PhysRevLett.119.043901 is OK
- 10.1088/1402-4896/aae34e is OK
- 10.1103/PhysRevLett.96.080403 is OK
- 10.1103/PhysRevB.100.081406 is OK
- 10.1103/PhysRevA.100.052511 is OK
- 10.1109/TAP.2015.2438393 is OK
- 10.1016/j.cpc.2009.11.008 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@michael-hartmann  Please merge https://github.com/michael-hartmann/caps/pull/163  Also, please check the cases of titles and journals in the references, using {}s to protect cases in the .bib file.  For example, in Buks, "casimer" in the title should probably be "Casimer". There's at least one other title with the same issue, and might be other titles that also need fixing.

**Comment by michael-hartmann** [comment]
Thank you for the info, I will check the titles right now.

**Comment by michael-hartmann** [comment]
I just realized that the journal names are inconsistent: some are abbreviated, others not. I guess all journal names should be abbreviated?

**Comment by danielskatz** [comment]
we don't have a fixed style for this, so you can choose the style you want, but please be consistent

**Comment by danielskatz** [comment]
let me know when you are ready for the next steps in the process

**Comment by michael-hartmann** [comment]
Okay, then let's go for all journal names abbreviated.

@gertingold Can you have a look at the PR https://github.com/michael-hartmann/caps/pull/165 and merge it if it's okay?

**Comment by gertingold** [comment]
Is there an established style for citing JOSS? Should it be "JOSS" or would "J. Open Source Softw." also be ok?

**Comment by gertingold** [comment]
@danielskatz, we have just merged a commit consistently abbreviating all journal titles. The only open question concerns the abbreviation of JOSS (see my previous commit). If "J. Open Source Softw." is fine, all journal titles should now be consistent. If JOSS is preferred, we will make one more change.

**Comment by danielskatz** [comment]
I think that’s fine

**Comment by gertingold** [comment]
We just moved to unabbreviated titles to prevent this issue... In any case, journal titles are now consistent.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02011/joss.02011/10.21105.joss.02011.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.crhy.2011.05.004 is OK
- 10.1103/PhysRevLett.87.211801 is OK
- 10.1103/PhysRevB.63.033402 is OK
- 10.1093/acprof:oso/9780199238743.001.0001 is OK
- 10.1016/j.crhy.2012.04.008 is OK
- 10.1103/PhysRevLett.109.160403 is OK
- 10.1088/1367-2630/8/10/243 is OK
- 10.1103/PhysRevLett.99.170403 is OK
- 10.1007/s10915-013-9714-z is OK
- 10.21105/joss.01167 is OK
- 10.1103/PhysRevE.91.033203 is OK
- 10.1103/PhysRevE.92.042125 is OK
- 10.1103/PhysRevLett.119.043901 is OK
- 10.1088/1402-4896/aae34e is OK
- 10.1103/PhysRevLett.96.080403 is OK
- 10.1103/PhysRevB.100.081406 is OK
- 10.1103/PhysRevA.100.052511 is OK
- 10.1109/TAP.2015.2438393 is OK
- 10.1016/j.cpc.2009.11.008 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1250

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1250, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1221575831442673670) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1251
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02011](https://doi.org/10.21105/joss.02011)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @eschnett & @jwuttke for reviewing!
Congratulations to @michael-hartmann & @gertingold!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02011/status.svg)](https://doi.org/10.21105/joss.02011)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02011">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02011/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02011/status.svg
   :target: https://doi.org/10.21105/joss.02011
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02011/status.svg)](https://doi.org/10.21105/joss.02011)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
