### ISSUE TITLE
[PRE REVIEW]: MAGPA: A R package for multivariate analysis of genotype–phenotype association and visualization of 3D image

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2012]
**Submitting author:** @changebio (<a href="http://orcid.org/0000-0003-1055-2602">Yin Huang</a>)
**Repository:** <a href="https://github.com/changebio/MAGPA" target ="_blank">https://github.com/changebio/MAGPA</a>
**Version:** V1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @changebio. **Currently, there isn't an JOSS editor assigned** to your paper.

@changebio if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.14 s (94.3 files/s, 10243.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                9             66            347            412
HTML                             1             60              5            232
TeX                              1              6              0             81
Markdown                         1             25              0             52
Rmd                              1             35             60             31
-------------------------------------------------------------------------------
SUM:                            13            192            412            808
-------------------------------------------------------------------------------


Statistical information for the repository '2012' was gathered on 2020/01/13.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btl268 is OK
- 10.1007/978-3-319-67020-1_2 is OK
- 10.1086/519795 is OK
- 10.1177/1536867x0900900207 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02012/joss.02012/10.21105.joss.02012.pdf)

**Comment by danielskatz** [comment]
👋 @changebio - After discussions in the editorial board, we have decided that this submission is not currently reviewable by JOSS. This is not to say that it is not valuable. Two options you might consider are
1. Publishing it to Zenodo or a similar archival repository, and asking users to cite the DOI provided by that repository
1. Resubmitting it to JOSS with additional work, such as some addition of QC, metrics, or any other mathematical, optimization, visualization function that actually shows the research here, an improved paper that mentions and compares with other packages that could also be used for similar things, and adding an OSI-approved license to the repository.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
