### ISSUE TITLE
[REVIEW]: Recan: Python tool for detection of recombination events in viral genomes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2014]
**Submitting author:** @babinyurii (<a href="http://orcid.org/0000-0002-7524-5921">Yuriy Babin</a>)
**Repository:** <a href="https://github.com/babinyurii/recan" target ="_blank">https://github.com/babinyurii/recan</a>
**Version:** 0.1.3
**Editor:** @will-rowe
**Reviewer:** @lamhm, @betteridiot
**Archive:** <a href="https://doi.org/10.5281/zenodo.3820660" target="_blank">10.5281/zenodo.3820660</a>

## Status

[![status](https://joss.theoj.org/papers/1cd9f277d8481ce504971491acc367e0/status.svg)](https://joss.theoj.org/papers/1cd9f277d8481ce504971491acc367e0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/1cd9f277d8481ce504971491acc367e0"><img src="https://joss.theoj.org/papers/1cd9f277d8481ce504971491acc367e0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/1cd9f277d8481ce504971491acc367e0/status.svg)](https://joss.theoj.org/papers/1cd9f277d8481ce504971491acc367e0)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/babinyurii/recan" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@lamhm & @betteridiot, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @will-rowe know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/babinyurii/recan">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@babinyurii) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/babinyurii/recan">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@babinyurii) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lamhm, @betteridiot it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.meegid.2014.12.022 is OK
- 10.1093/bioinformatics/bth500 is OK
- 10.1093/ve/vev003 is OK
- 10.1089/08892220050075309 is OK
- 10.1002/hep.26744 is OK
- 10.1007/s007050050651 is OK
- 10.1371/journal.pone.0207480 is OK
- 10.1093/bioinformatics/btm404 is OK
- 10.1093/nar/gkf436 is OK
- 10.1093/bioinformatics/bts091 is OK

MISSING DOIs

- https://doi.org/10.1128/jvi.73.1.152-160.1999 may be missing for title: Full-length human immunodeficiency virus type 1 genomes from subtype C-infected seroconverters in India, with evidence of intersubtype recombination.

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02014/joss.02014/10.21105.joss.02014.pdf)

**Comment by will-rowe** [comment]
Hi @betteridiot and @lamhm - just checking in with you to see how the reviews are going and if you need anything.

**Comment by betteridiot** [comment]
Thank you @will-rowe for pinging us. I am still actively reviewing the paper, but I do have a question regarding the review process. Regarding the "Quality of writing" stage; are we expected to give revisions or specific notes or just request them to have an editor review it for them?

**Comment by will-rowe** [comment]
Thanks @betteridiot. If you can give some specific points, that would be great - if not a general comment would also be useful. Now that you've flagged it in your review, I'll assess it after the author has had chance to respond to reviewer comments.

**Comment by betteridiot** [comment]
@will-rowe, @babinyurii these are my reviewer comments for the review of `recan` as the package stands right now.

**Comment by lamhm** [comment]
I have only four minor issues with this publication: `Performance`, `Example usage`, `Community guidelines`, and `Quality of writing`. Most of these have been pointed out by @betteridiot.

I have checked off the `Automated tests` section in my checklist because I do not have any experience with the topic (I do not do formal development in Python).

**Comment by will-rowe** [comment]
Brilliant - thank you very much @betteridiot and @lamhm ! These are thorough reviews and I'm sure these issues can be addressed by @babinyurii

@babinyurii - please can you take a look at these issues and respond to them. Let me know if you need any assistance.

**Comment by danielskatz** [comment]
👋 @babinyurii - note that we are waiting for your response

**Comment by will-rowe** [comment]
Pinging @babinyurri again - please let us know if you are able to respond to these reviewer comments.

**Comment by babinyurii** [comment]
Hello, @will-rowe! Now I've added answeres to the reviewers' comments.

**Comment by will-rowe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02014/joss.02014/10.21105.joss.02014.pdf)

**Comment by will-rowe** [comment]
great - thanks @babinyurii

Could you please respond to [this reviewer issue](https://github.com/babinyurii/recan/issues/12).

You also suggested two options in response to [this issue](https://github.com/babinyurii/recan/issues/10). Can you please let us know which you would like to proceed with? I.E. renaming the paper and adjusting the scope, or the addition of a function for detection of recombination breakpoints

**Comment by babinyurii** [comment]
Hello, @will-rowe!
I'm sorry for overlooking @lamhm 's comment.
Now I've added the answers to the comments you mentioned.

**Comment by will-rowe** [comment]
Great - thanks @babinyurii

I think we're getting close here. Can I now ask @betteridiot and @lamhm to review the author responses to the issues raised and check they are satisfied? From my point of view, I am happy now that @babinyurii has adjusted the scope of the paper to focus on the analysis, rather than detection, of recombination events.

**Comment by babinyurii** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02014/joss.02014/10.21105.joss.02014.pdf)

**Comment by will-rowe** [comment]
Pinging @betteridiot and @lamhm - could I ask you to take another look at this submission and see if you are happy that your comments have been addressed to your satisfaction?

**Comment by betteridiot** [comment]
Sorry. I might be able to get to it later this week. I am out of town at a conference. Kind of spotty internet at best. 

Marcus D. Sherman
RISE & RMF Fellow
PhD Candidate
Mills Lab
Dept. of Comp. Medicine & Bioinformatics
University of Michigan
https://twitter.com/better_idiot 
https://github.com/betteridiot

**Comment by lamhm** [comment]
Hi @babinyurii and @will-rowe,

Apologies for my delayed response. I think `recan` has fulfilled most of the criteria in the review checklist. I only have two comments left to be resolved. They are in the `Example usage` and the `Quality of writing` issues.

**Comment by will-rowe** [comment]
Many thanks indeed @lamhm

@babinyurii - can you please respond to the additional comments left by @lamhm in the issues mentioned above. In terms of Quality of writing - if you can address the specific point regarding the summary, that would be great. I'm happy to go through the paper afterwards and help with the grammar etc.

**Comment by will-rowe** [comment]
Hi @babinyurii - just pinging you a reminder. Cheers, Will

**Comment by babinyurii** [comment]
Hi @will-rowe, now I've added answers to  @lamhm 's comments. It would be great, if you could go through the manuscript just to look at the articles. I would really appreciate it.

**Comment by will-rowe** [comment]
That's great @babinyurii. When @betteridiot signs off on his review, I will go through and help edit the paper.

Pinging @betteridiot - I know it's hectic times at the moment and I understand if this has dropped off your radar. Please let us know if you'll be able to check your comments have been addressed. If you can't manage it in the next week or two, I'll make the decision based on what you have provided so far.

Cheers,

Will

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by betteridiot** [comment]
I apologize for the long delay in responding. The author has addressed most of my notes and looks to be actively working on the "quality of writing". With that, I believe the paper is ready to move forward.

**Comment by arfon** [comment]
:wave: @will-rowe - this looks like it's pretty close to be ready to accept.

**Comment by will-rowe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02014/joss.02014/10.21105.joss.02014.pdf)

**Comment by will-rowe** [comment]
Sorry for the delay @babinyurii (and @arfon) - I've been super busy with COVID stuff and my editorial responsibilities have unfortunately been neglected. My apologies.

The paper is looking great - thank you for you work in addressing all the reviewer comments and for improving the writing quality.

I have just submitted a small pull request to your repo that makes a few grammatically changes. https://github.com/babinyurii/recan/pull/15 - let me know if you agree with these. Once you are happy, I think we can move to acceptance here.

**Comment by arfon** [comment]
> Sorry for the delay @babinyurii (and @arfon) - I've been super busy with COVID stuff and my editorial responsibilities have unfortunately been neglected. My apologies.

No need to apologize @will-rowe. I totally understand, I spent this morning bumping a whole bunch of review threads just to see how things were going and this one looked very close to being ready.

**Comment by will-rowe** [comment]
Hi @babinyurii - just pinging you to see if you have had chance to take a final look at your paper. There is no rush to respond - I just wanted to check in as we are nearly there!

**Comment by babinyurii** [comment]
Hi @will-rowe! Thank you for reminding me. I'm sorry for overlooking your merge in a hurry. I've already put the changes you proposed into the paper.

**Comment by will-rowe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02014/joss.02014/10.21105.joss.02014.pdf)

**Comment by will-rowe** [comment]
Thanks @babinyurii - this all looks great to me. I think we can accept this now - thanks to everyone for their hard work.

@babinyurii - please issue a new tagged release and archive it on Zenodo. Then post back here with the new version number and the DOI.

**Comment by babinyurii** [comment]
Thanks @will-rowe 
new version is: 0.1.3
doi is: 10.5281/zenodo.3820660

https://zenodo.org/record/3820660#.XrmVDcRR3IU

**Comment by will-rowe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02014/joss.02014/10.21105.joss.02014.pdf)

**Comment by will-rowe** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.meegid.2014.12.022 is OK
- 10.1093/bioinformatics/bth500 is OK
- 10.1093/ve/vev003 is OK
- 10.1089/08892220050075309 is OK
- 10.1002/hep.26744 is OK
- 10.1007/s007050050651 is OK
- 10.1371/journal.pone.0207480 is OK
- 10.1093/bioinformatics/btm404 is OK
- 10.1093/nar/gkf436 is OK
- 10.1093/bioinformatics/bts091 is OK

MISSING DOIs

- https://doi.org/10.1128/jvi.73.1.152-160.1999 may be missing for title: Full-length human immunodeficiency virus type 1 genomes from subtype C-infected seroconverters in India, with evidence of intersubtype recombination.

INVALID DOIs

- None
```

**Comment by will-rowe** [comment]
@whedon set 10.5281/zenodo.3820660 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3820660" target="_blank">10.5281/zenodo.3820660</a> is the archive.

**Comment by will-rowe** [comment]
@whedon set 0.1.3 as version

**Comment by whedon** [comment]
OK. 0.1.3 is the version.

**Comment by will-rowe** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.meegid.2014.12.022 is OK
- 10.1093/bioinformatics/bth500 is OK
- 10.1093/ve/vev003 is OK
- 10.1089/08892220050075309 is OK
- 10.1002/hep.26744 is OK
- 10.1007/s007050050651 is OK
- 10.1371/journal.pone.0207480 is OK
- 10.1093/bioinformatics/btm404 is OK
- 10.1093/nar/gkf436 is OK
- 10.1093/bioinformatics/bts091 is OK

MISSING DOIs

- https://doi.org/10.1128/jvi.73.1.152-160.1999 may be missing for title: Full-length human immunodeficiency virus type 1 genomes from subtype C-infected seroconverters in India, with evidence of intersubtype recombination.

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1446

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1446, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1260163193281921024) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1447
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02014](https://doi.org/10.21105/joss.02014)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@lamhm, @betteridiot - many thanks for your reviews here and to @will-rowe for editing this submission ✨ 

@babinyurii - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02014/status.svg)](https://doi.org/10.21105/joss.02014)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02014">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02014/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02014/status.svg
   :target: https://doi.org/10.21105/joss.02014
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02014/status.svg)](https://doi.org/10.21105/joss.02014)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
