### ISSUE TITLE
issues running example program Karate

### ISSUE THREAD

**Issue by Laya1363** [openjournals/joss-reviews#2015]
I want to apply GEM methods in my graph data. and just started to download required packages ans run example program to learn  more. but while running encountered different warnings and errors. one of the is this error:

Using TensorFlow backend.
Traceback (most recent call last):
  File "C:/Laya/MasterThesis/programming/test1.py", line 22, in <module>
    G = graph_util.loadGraphFromEdgeListTxt(edge_f, directed=isDirected)
  File "C:\Users\Z0040MDA\AppData\Roaming\Python\Python36\site-packages\gem-1.0.0-py3.6.egg\gem\utils\graph_util.py", line 159, in loadGraphFromEdgeListTxt
    G.add_edge(int(edge[0]), int(edge[1]), weight=w)
IndexError: list index out of range 

can you please help me to solve the problem ?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2015 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@Laya1363 - please do not open issues on this repository. If you are reviewing a JOSS submission, please open issues on that repository directly.
