### ISSUE TITLE
[REVIEW]: Audiometry: A Model-View-ViewModel (MVVM) Application Framework for Hearing Impairment Diagnosis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2016]
**Submitting author:** @drwaseemsheikh (<a href="http://orcid.org/0000-0002-4647-4565">Waseem Sheikh</a>)
**Repository:** <a href="https://github.com/drwaseemsheikh/audiometry.git" target ="_blank">https://github.com/drwaseemsheikh/audiometry.git</a>
**Version:** 1.0.0
**Editor:** @arfon
**Reviewers:** @dvberkel, @martinmodrak
**Archive:** <a href="https://doi.org/10.5281/zenodo.3924784" target="_blank">10.5281/zenodo.3924784</a>

## Status

[![status](https://joss.theoj.org/papers/7be6057cc4b575a4917a15e8d0017dbe/status.svg)](https://joss.theoj.org/papers/7be6057cc4b575a4917a15e8d0017dbe)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7be6057cc4b575a4917a15e8d0017dbe"><img src="https://joss.theoj.org/papers/7be6057cc4b575a4917a15e8d0017dbe/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7be6057cc4b575a4917a15e8d0017dbe/status.svg)](https://joss.theoj.org/papers/7be6057cc4b575a4917a15e8d0017dbe)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/drwaseemsheikh/audiometry.git" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ati-ozgur & @dvberkel, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @akeshavan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/drwaseemsheikh/audiometry.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@drwaseemsheikh) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/drwaseemsheikh/audiometry.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@drwaseemsheikh) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ati-ozgur, @dvberkel it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/IEMBS.2009.5334072 is OK
- 10.1109/MEMEA.2007.4285154 is OK

MISSING DOIs

- https://doi.org/10.1055/b-006-161125 may be missing for title: Essentials of Audiology
- https://doi.org/10.1097/00003446-198608000-00010 may be missing for title: Handbook of clinical audiology
- https://doi.org/10.1109/itoec.2017.8122338 may be missing for title: Smartphone-based self hearing diagnosis using hearing aids
- https://doi.org/10.1109/tbcas.2018.2878341 may be missing for title: Smartphone-Based Hearing Self-Assessment System Using Hearing Aids with Fast Audiometry Method
- https://doi.org/10.1089/tmj.2014.0171 may be missing for title: A browser-server-based tele-audiology system that supports multiple hearing test modalities
- https://doi.org/10.1177/0194599813501461 may be missing for title: Automated audiometry using apple iOS-based application technology
- https://doi.org/10.1089/tmj.2009.0013 may be missing for title: Web-based hearing screening test
- https://doi.org/10.1089/153056203772744707 may be missing for title: Internet-based tele-audiometry system for the assessment of hearing: a pilot study
- https://doi.org/10.1016/0169-2607(95)01712-7 may be missing for title: VISAUDIO: a Windows software application for Bekesy audiogram analysis and hearing research
- https://doi.org/10.1177/1357633x18800856 may be missing for title: Tablet-based tele-audiometry: Automated hearing screening for schoolchildren
- https://doi.org/10.1089/tmj.2016.0253 may be missing for title: Tablet-based hearing screening test
- https://doi.org/10.1044/2018_aja-17-0070 may be missing for title: Accuracy of Smartphone Self-Hearing Test Applications Across Frequencies and Earphone Styles in Adults
- https://doi.org/10.1007/s00405-015-3533-9 may be missing for title: Smartphone-based audiometric test for screening hearing loss in the elderly
- https://doi.org/10.5152/iao.2016.1421 may be missing for title: Smartphone based audiometric test for confirming the level of hearing; is it useable in underserved areas
- https://doi.org/10.1159/000349913 may be missing for title: Smartphone-based hearing test as an aid in the initial evaluation of unilateral sudden sensorineural hearing loss
- https://doi.org/10.1111/j.1365-2214.2010.01079.x may be missing for title: Hearing screening for school children: comparison of low-cost, computer-based and conventional audiometry

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02016/joss.02016/10.21105.joss.02016.pdf)

**Comment by dvberkel** [comment]
@akeshavan I have completed my review

**Comment by drwaseemsheikh** [comment]
Thank you @dvberkel for completing the review.

@akeshavan, I haven't heard from the second reviewer for over a month now. Perhaps he missed the email. Could you please remind him to start the review. I will appreciate it. Thanks!

**Comment by akeshavan** [comment]
hi @ati-ozgur ! Have you had a chance to take a look at this review?

**Comment by drwaseemsheikh** [comment]
Hi @akeshavan,
We haven't heard from the second reviewer for over a month. If the second reviewer is not going to review it, could you please assign a different reviewer? Thanks.

**Comment by akeshavan** [comment]
👋 hi @martinmodrak and @nmullins -- would you be interested in reviewing this paper for JOSS?

**Comment by martinmodrak** [comment]
@akeshavan, yes I can look into it, although I've never worked with WPF, so my review will be limited, as I can't really help wit the GUI code (which might be substantial part of the app)

**Comment by akeshavan** [comment]
thanks @martinmodrak! Let @drwaseemsheikh know if you have trouble evaluating anything on the checklist (e.g. installation, functionality), since this is useful feedback!

**Comment by akeshavan** [comment]
@whedon add @martinmodrak as reviewer

**Comment by whedon** [comment]
OK, @martinmodrak is now a reviewer

**Comment by martinmodrak** [comment]
So I completed a first round of review. I think developing open source software for medical practitioners is a worthwhile endeavour and can be especially valuable for those operating in less developed countries.  The software had some major problems on my computer (e.g. https://github.com/drwaseemsheikh/audiometry/issues/7) , but I believe those are likely very simple bugs that can be easily resolved. I like how the tabs for diagnosis update immediately and they look pretty neat.

There are many small ways the software could be improved to facilitate faster daily use by a practitioner, but I understand if the authors don't have resources to completely polish the interface.

The biggest issue is however that I couldn't find the research-related functionality which is alluded to in the paper anywhere (https://github.com/drwaseemsheikh/audiometry/issues/12), I hope this is just me not looking in the right places. I will resume my review when I hear back from @drwaseemsheikh on this issue.

**Comment by drwaseemsheikh** [comment]
I have addressed all your comments. I would like to reiterate again that as a reviewer your job is to make sure that the software meets the above checkmarks or requirements for the review and not that it is perfect. A lot of changes you asked me to do are small from a user's perspective but would require months of development time from my end which I don't have. I would urge you as a reveiwer to keep into consideration such constraints.

The software has already been downloaded hundreds of times by various users and has received very favorable feedback (See SourceForge). It helps the patients and healthcare providers in underdeveloped countries to better manage and analyze hearing test data thus making the process of hearing impairment diagnosis easier and accurate. Such things also need to be kept in consideration when you are criticizing minor changes.

**Comment by akeshavan** [comment]
@drwaseemsheikh, I understand the challenges of developing and maintaining open source software, and that it can be difficult to incorporate reviewers' suggestions when you are limited on time and are working on this software for free. Every author on JOSS experiences this. 

But JOSS has standards for the open source software papers that we publish. We are very grateful that our reviewers voluntarily take the time to install our author's software, read their documentation, and ensure functionality and performance, among other things. A reviewer's suggestions, however major or minor, _are not meant to antagonize the author_ -- they are simply suggestions to improve the accessibility and function of the author's software, so that it can reach the broader scientific community.

It is your job as a JOSS author to decide whether to incorporate a reviewer's suggestions or not, keeping in mind the JOSS criteria for publishing. If a reviewer is confused about something, you may want to consider updating your documentation. It is your choice on whether to incorporate any major or minor changes suggested by the reviewer, but I do ask that you respond politely to the reviewer who has volunteered their time to evaluate your software for JOSS.

**Comment by martinmodrak** [comment]
@drwaseemsheikh First, I admit that some of the phrasing I used in the issues could be read as combative and I apologize for that. I totally agree with @akeshavan that you don't have to incorporate the feedback I gave into your software. I however do disagree that is my job just to "make sure that the software meets the above checkmarks or requirements", the JOSS review guidelines state that "A key goal of JOSS is to raise the quality of research software generally" and this is the place I am coming from. You may disagree about specific suggestions I made and I am open to have my mind changed about most of them or let @akeshavan as the editor decide that the software can be accepted without resolving them. All of my suggestions were meant to improve the software and I tried to suggest only things I believe would be easy to do (though I might be wrong).

I agree that if there already is a substantial user community, that is a strong plus. If the software does not have GitHub as its primary home but is instead mainly hosted on SourceForge and has a community there, than linking to the SourceForge page in README.md and the paper would IMHO be very sensible.

I will react in more detail at the individual issues.

**Comment by danielskatz** [comment]
👋 @akeshavan - can you update us all on the status of this review?

**Comment by martinmodrak** [comment]
From my side there are two major issues that block further progress: 
- Save/load doesn't work on my computer: https://github.com/drwaseemsheikh/audiometry/issues/7 
- The connection to research is unclear https://github.com/drwaseemsheikh/audiometry/issues/12 (this might be actually resolved just by clarifying what the software intends to do and what it does not).

On both I am waiting for reaction from @drwaseemsheikh.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arfon** [comment]
:wave:  @drwaseemsheikh, how are you getting on responding to the reviewer feedback?

**Comment by drwaseemsheikh** [comment]
Hello, I should have the required changes submitted in a couple of days and will notify as soon as I am done.

**Comment by drwaseemsheikh** [comment]
I have fixed the following bugs which include the most important issues that were raised during the review process. I have committed my code changes and updated the installer binary file. You can test and verify that these issues have been fixed by installing the installer file under the install folder.

Fixed the following bugs:
1. If the symptoms or diagnosis list was empty, the application was not opening the record from the database. It was, however, saving it.
2. I moved the Account textbox to the top and added a tooltip to notify the user that this is a required field.
3. The application was not saving a patient record without any test data.
4. Oxyplot was throwing a null dereference exception when only one value was entered in a textbox for Speech or Impedance audiometry.

As per the changes that you want with respect to the research applications, why don't you tell me how would you like the wording? I will be happy to change the wording in the paper.

**Comment by waseemasheikh** [comment]
Hello,

I submitted my bug fixes for all the major issues two weeks back. Could you please let me know the timeline for review and publishing as the paper has been under review for a very long time. Thanks.

**Comment by arfon** [comment]
Hi @waseemasheikh / @drwaseemsheikh - it's not clear if you have addressed the feedback in drwaseemsheikh/audiometry#7 or drwaseemsheikh/audiometry#12. Could you please comment on that?

> Could you please let me know the timeline for review and publishing as the paper has been under review for a very long time. 

As I noted in [my comment](https://github.com/openjournals/joss-reviews/issues/2016#issuecomment-598981503) in mid-March, JOSS is working on a best-efforts basis right now. The effects of the pandemic on the availability of our reviewers and editors to contribute time to reviews is hard to gauge. Your patience is appreciated.

**Comment by drwaseemsheikh** [comment]
Hi.

Regarding Issue #7 (where a patient's record was not being saved when only the patient tab was filled in): This bug has been fixed in my last commit.

Regarding Issue #12 (research applications): The co-author of this paper (Dr. Nadeem) is a board-certified ENT specialist and he is using this software in his research in the following specific contexts.

1. The software can be used to compare the sensitivity (true-positive rate) and specificity (true-negative rate) of various hearing test equipment and methods. For example, questions like how reliable is a pure-tone audiometry test performed by a smartphone or a tablet when compared to a benchmark calibrated audiometer can be easily answered by using this software.

How: Record the audiometry data from the two different tests, generated the audiogram plots for the two different sets of data, and compare them to look for differences in thresholds.

2. The software can be used to determine important correlations between lifestyle, work conditions, and demographics; and the types of hearing loss.

How: The co-author used this software in collecting hearing test data for airmen who were exposed to loud noise. Their audiograms were generated and the ENT specialist was able to see certain trends in their audiograms which predicted a certain kind of hearing loss.

3. The software can be used to measure the efficacy of a certain treatment, intervention, or equipment on the progression of a hearing loss.

How: Record the hearing test data of a patient during multiple stages of an intervention. Compare the audiograms and observe the trends.

**Comment by arfon** [comment]
Thanks for the update @drwaseemsheikh. Regarding the usage in research, are there any papers/publications that could be cited?

**Comment by martinmodrak** [comment]
Sorry for the delay. I've just installed an updated version (it is a bit hard to verify that this is the latest version, as the version in the Audiometry.exe metadata has not changed and is still 1.0.0, but the file date is April 20th, so I guess this is correct).

Issue #7 persists, I am still unable to save patients and their data.

As for the scientific use: I think saying that the fact that you can record and retrieve medical information and then compare it without any help from the program stretches the definition of "obvious research application" way beyond what I understand by those words (a text editor allows you to do this as well). Since this is my first time reviewing, I however don't have a strong sense on how strongly this is usually interpreted and will delegate the decision on this to @arfon.

**Comment by drwaseemsheikh** [comment]
I am unable to replicate issue # 7 bug. I have tested it on my end and that issue has been fixed. I am able to save and restore patient data without any data. Since we are at an impasse now, I would ask the editor or another reviewer to test the functionality of the code and provide detailed steps so that I can replicate that issue. Just saying that the issue persists doesn't help me as I can't replicate it. To the best of my understanding and testing, that issue has been fixed.

**Comment by drwaseemsheikh** [comment]
Here is the proof with the screeshots that bug#7 has been fixed. Steps to follow:
1. Install the latest application.
2. Enter data in the Patient tab, leaving all other tabs blank.
3. Save the patient data by clicking on Save.
4. Click on the Search menu option and set the start date in the Search window to the previous day or any time before the data was recorded. Click Search.
5. This shows the patient record that was just saved. Opening this record shows the exact data filled in the form as was saved. See pictures for the proof.

My guess is (since the reviewer has not provided detailed steps) that he is not setting the Start date/time field in the Search window to before the date/time of the test taken and therefore he doesn't see that record. But that's an error on his part and not on the software.
![fig1](https://user-images.githubusercontent.com/56233110/82842794-24552980-9e98-11ea-8642-e83ebe97a680.png)
![fig2](https://user-images.githubusercontent.com/56233110/82842795-24edc000-9e98-11ea-9a89-334bd548a397.png)
![fig3](https://user-images.githubusercontent.com/56233110/82842796-24edc000-9e98-11ea-9f9d-583b64396c32.png)
![fig4](https://user-images.githubusercontent.com/56233110/82842797-24edc000-9e98-11ea-8a9d-428bb04be6cb.png)
![fig5](https://user-images.githubusercontent.com/56233110/82842798-25865680-9e98-11ea-96ff-894e4bce978e.png)

**Comment by drwaseemsheikh** [comment]
I, therefore, request the editor to please expedite the publishing of this paper as I have already waited too long and to the best of my knowledge and testing all issues have been resolved. Thank you!

**Comment by danielskatz** [comment]
👋 @arfon - can I assign you as the editor of this submission for now?

**Comment by arfon** [comment]
I'm happy to take this over from here.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by arfon** [comment]
> Thanks for the update @drwaseemsheikh. Regarding the usage in research, are there any papers/publications that could be cited?

@drwaseemsheikh - could you please respond to this question I posed a little while back?

**Comment by martinmodrak** [comment]
@drwaseemsheikh I just verified one more time the problem https://github.com/drwaseemsheikh/audiometry/issues/7 persists on my work PC. I will also try another machine with a different system. However, the fact that software behaves differently on different computers is unfortunately to be expected and it is generally considered good practice to test on multiple computers and resolve problems that appear. I don't think it is my role to debug this issue in depth - I tried some obvious steps (e.g. running the software as admin) but those didn't help. But as I said in the issue, I am happy to provide any information that you think might be related (e.g. logs from your application) or run some test application/modified version that provides extensive info that would help you debug. If you prefer, we can possibly also arrange a call with screen sharing. I really have no intention to shoot the application down and I want to help to make the app better. If it doesn't work on my system, it likely fails on systems of many other potential users, but most users don't report bugs and instead just stop using the software.

**Comment by arfon** [comment]
> @drwaseemsheikh I just verified one more time the problem drwaseemsheikh/audiometry#7 persists on my work PC. I will also try another machine with a different system. However, the fact that software behaves differently on different computers is unfortunately to be expected and it is generally considered good practice to test on multiple computers and resolve problems that appear.

@martinmodrak - thanks. I think that would be very helpful. I agree with the spirit of your comment here and think it would be good to, if at all possible, resolve this issue before closing out this review.

**Comment by martinmodrak** [comment]
Looking at the progress of the individual issues I filed, it is clear I was unable to build a collaborative relationship with the author.  I have no aim to gatekeep the publication of the software, but I am also unable to verify some of the basic functionality and can't find meaningful way forward. This is a lose-lose situation and I therefore ask @arfon to remove me from reviewing this submission.

**Comment by arfon** [comment]
Thank you @martinmodrak for all of your hard work thus far. I'm sorry things have reached this point but I understand why you would like to be removed at this stage.

@drwaseemsheikh - while I look for a new reviewer, could you please address my comment from a couple of weeks ago about [published research](https://github.com/openjournals/joss-reviews/issues/2016#issuecomment-627436937) that you might be able to cite here?

**Comment by arfon** [comment]
@drwaseemsheikh - I've just tried installing this software on a Windows 10 Pro VM on Azure and confirmed that I can complete the [steps described by the author](https://github.com/openjournals/joss-reviews/issues/2016#issuecomment-633714396) to save a record.

As such, I believe we can move forward with accepting this submission.

@martinmodrak - given all of the hard work you've put into this review, I'd rather leave you listed as a reviewer here if that is acceptable to you? (That way you'll be listed as a reviewer on the final paper). Please let me know if this is not OK.

@drwaseemsheikh - if there are any published papers/articles that have made use of this software, please cite them. Otherwise:

At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by martinmodrak** [comment]
OK. I agree to be listed as a reviewer. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@drwaseemsheikh :point_up: did you see @arfon's instructions on next steps? Let us know if you have questions.

**Comment by waseemasheikh** [comment]
You have the wrong email address. My name is Waseem but I have no idea what this is about, and I’m unable to unsubscribe from github.

**Comment by Kevin-Mattheus-Moerman** [comment]
Apologies @waseemasheikh it seems @arfon tagged you by accident since your name is close to the author's name.

**Comment by drwaseemsheikh** [comment]
Here are the updates from my end:

1. There are no published papers/articles that have made use of this software at this point.

2. The software release is the latest and has all the bug fixes and changes from past reviews.

3. I have archived the software in Zenodo and following is the DOI of the archive

DOI: 10.5281/zenodo.3924784

The title of the archive is the same as the JOSS paper title and the authors of the archive are the same as the JOSS paper authors.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3924784 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3924784" target="_blank">10.5281/zenodo.3924784</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1525

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1525, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/IEMBS.2009.5334072 is OK
- 10.1109/MEMEA.2007.4285154 is OK

MISSING DOIs

- https://doi.org/10.1055/b-006-161125 may be missing for title: Essentials of Audiology
- https://doi.org/10.1097/00003446-198608000-00010 may be missing for title: Handbook of clinical audiology
- https://doi.org/10.1109/itoec.2017.8122338 may be missing for title: Smartphone-based self hearing diagnosis using hearing aids
- https://doi.org/10.1109/tbcas.2018.2878341 may be missing for title: Smartphone-Based Hearing Self-Assessment System Using Hearing Aids with Fast Audiometry Method
- https://doi.org/10.1089/tmj.2014.0171 may be missing for title: A browser-server-based tele-audiology system that supports multiple hearing test modalities
- https://doi.org/10.1177/0194599813501461 may be missing for title: Automated audiometry using apple iOS-based application technology
- https://doi.org/10.1089/tmj.2009.0013 may be missing for title: Web-based hearing screening test
- https://doi.org/10.1089/153056203772744707 may be missing for title: Internet-based tele-audiometry system for the assessment of hearing: a pilot study
- https://doi.org/10.1016/0169-2607(95)01712-7 may be missing for title: VISAUDIO: a Windows software application for Bekesy audiogram analysis and hearing research
- https://doi.org/10.1177/1357633x18800856 may be missing for title: Tablet-based tele-audiometry: Automated hearing screening for schoolchildren
- https://doi.org/10.1089/tmj.2016.0253 may be missing for title: Tablet-based hearing screening test
- https://doi.org/10.1044/2018_aja-17-0070 may be missing for title: Accuracy of Smartphone Self-Hearing Test Applications Across Frequencies and Earphone Styles in Adults
- https://doi.org/10.1007/s00405-015-3533-9 may be missing for title: Smartphone-based audiometric test for screening hearing loss in the elderly
- https://doi.org/10.5152/iao.2016.1421 may be missing for title: Smartphone based audiometric test for confirming the level of hearing; is it useable in underserved areas
- https://doi.org/10.1159/000349913 may be missing for title: Smartphone-based hearing test as an aid in the initial evaluation of unilateral sudden sensorineural hearing loss
- https://doi.org/10.1111/j.1365-2214.2010.01079.x may be missing for title: Hearing screening for school children: comparison of low-cost, computer-based and conventional audiometry

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@drwaseemsheikh - could you review this list of DOIs ☝️ for your references and for the ones that look correct, please add them to your BibTeX file? For example if `https://doi.org/10.1055/b-006-161125 may be missing for title: Essentials of Audiology` is correct for this title, then add `doi=10.1055/b-006-161125` to the BibTeX entry for that paper.

@openjournals/joss-eics - apologies - I forgot to check the references here before running the proof-generation stage. This submission isn't quite ready for processing.

**Comment by drwaseemsheikh** [comment]
I have updated my BibTex file with the missing DOIs.

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1055/b-006-161125 is OK
- 10.1097/00003446-198608000-00010 is OK
- 10.1109/itoec.2017.8122338 is OK
- 10.1109/tbcas.2018.2878341 is OK
- 10.1109/IEMBS.2009.5334072 is OK
- 10.1109/MEMEA.2007.4285154 is OK
- 10.1089/tmj.2014.0171 is OK
- 10.1177/0194599813501461 is OK
- 10.1089/tmj.2009.0013 is OK
- 10.1089/153056203772744707 is OK
- 10.1016/0169-2607(95)01712-7 is OK
- 10.1177/1357633x18800856 is OK
- 10.1089/tmj.2016.0253 is OK
- 10.1044/2018_aja-17-0070 is OK
- 10.1007/s00405-015-3533-9 is OK
- 10.5152/iao.2016.1421 is OK
- 10.1159/000349913 is OK
- 10.1111/j.1365-2214.2010.01079.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02016/joss.02016/10.21105.joss.02016.pdf)

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1531

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1531, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1055/b-006-161125 is OK
- 10.1097/00003446-198608000-00010 is OK
- 10.1109/itoec.2017.8122338 is OK
- 10.1109/tbcas.2018.2878341 is OK
- 10.1109/IEMBS.2009.5334072 is OK
- 10.1109/MEMEA.2007.4285154 is OK
- 10.1089/tmj.2014.0171 is OK
- 10.1177/0194599813501461 is OK
- 10.1089/tmj.2009.0013 is OK
- 10.1089/153056203772744707 is OK
- 10.1016/0169-2607(95)01712-7 is OK
- 10.1177/1357633x18800856 is OK
- 10.1089/tmj.2016.0253 is OK
- 10.1044/2018_aja-17-0070 is OK
- 10.1007/s00405-015-3533-9 is OK
- 10.5152/iao.2016.1421 is OK
- 10.1159/000349913 is OK
- 10.1111/j.1365-2214.2010.01079.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1278378032508669953) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1533
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02016](https://doi.org/10.21105/joss.02016)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@dvberkel, @martinmodrak - many thanks for your reviews here ✨ 

@drwaseemsheikh - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02016/status.svg)](https://doi.org/10.21105/joss.02016)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02016">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02016/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02016/status.svg
   :target: https://doi.org/10.21105/joss.02016
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02016/status.svg)](https://doi.org/10.21105/joss.02016)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
