### ISSUE TITLE
[PRE REVIEW]: Akmedoids R package for generating directionally-homogeneous clusters of longitudinal data sets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2019]
**Submitting author:** @MAnalytics (<a href="http://orcid.org/0000-0002-9006-4934">Monsuru Adepeju</a>)
**Repository:** <a href="https://github.com/MAnalytics/akmedoids" target ="_blank">https://github.com/MAnalytics/akmedoids</a>
**Version:** v0.1.5
**Editor:** @karthik
**Reviewers:** @karthik, @njtierney 

**Author instructions**

Thanks for submitting your paper to JOSS @MAnalytics. **Currently, there isn't an JOSS editor assigned** to your paper.

@MAnalytics if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (612.0 files/s, 75513.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               11            197            388            697
TeX                              2             27              0            201
Rmd                              1            197            245            163
Markdown                         4             30              0             76
-------------------------------------------------------------------------------
SUM:                            18            451            633           1137
-------------------------------------------------------------------------------


Statistical information for the repository '2019' was gathered on 2020/01/17.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1007/s00180-009-0178-4 may be missing for title: KmL: k-means for longitudinal data
- https://doi.org/10.1007/s10940-014-9228-3 may be missing for title: Crime and place: a longitudinal examination of street segment patterns in Vancouver, BC
- https://doi.org/10.1111/j.1745-9125.2004.tb00541.x may be missing for title: Communities, street guns and homicide trajectories in Chicago, 1980-1995: merging methods for examining homicide trends across space and time
- https://doi.org/10.1007/s10940-016-9301-1 may be missing for title: The trajectories of crime at places: understanding the patterns of disaggregated crime types
- https://doi.org/10.4324/9781315089256-19 may be missing for title: Trajectories of Crime at Places: A Longitudinal Study of Street Segments in the City of Seattle
- https://doi.org/10.1093/bjc/azx022 may be missing for title: Local variance in the crime drop: A longitudinal study of neighbourhoods in greater Glasgow, Scotland
- https://doi.org/10.1016/0167-9473(92)90042-e may be missing for title: A classification EM algorithm for clustering and two stochastic versions
- https://doi.org/10.1080/03610917408548446 may be missing for title: A dendrite method for cluster analysis
- https://doi.org/10.1016/0377-0427(87)90125-7 may be missing for title: Silhouettes: A graphical aid to the interpretation and validation of cluster analysis

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02019/joss.02019/10.21105.joss.02019.pdf)

**Comment by kyleniemeyer** [comment]
Hey @karthik, I know you've been out, but if you're back could you edit this?

**Comment by MAnalytics** [comment]
Missing DOIs now included!
Thanks you.

**Comment by MAnalytics** [comment]
Dear Sir,

Below are my suggestions (based on this list of people<https://bit.ly/joss-reviewers>) for potential reviewers of our article:


1.       rcannood

2.       sjsrey

3.       seabbs

4.       Maczokni


I hope to hear from you soon.

Monsuru.

**Comment by MAnalytics** [comment]
Dear @kyleniemeyer, I forgot to tag you in the above email.
Best,
Monsuru.

**Comment by karthik** [comment]
👋 @MAnalytics I'l be the editor handling your submission. A quick look shows that you have no unit tests at all. Can you please add sufficient tests to cover all functionality of your package?

**Comment by MAnalytics** [comment]
@karthik Thank you very much for accepting to handle my submission. I will add the tests asap to cover all functionality, and get back to you.
Regards, Monsuru.

**Comment by labarba** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by karthik** [comment]
Thanks @MAnalytics 
I'm looking for reviewers now. Other things you might want to do in the meantime:

- Add some installation instructions to your README
- omit "Date" in DESCRIPTION. It is not required and it
    gets invalid quite often. A build date will be added to the package
    when you perform `R CMD build` on it.
- add a "URL" field to DESCRIPTION. It helps users find
    information about your package online. If your package does not
    have a homepage, add an URL to GitHub, or the CRAN package package
    page.
- add a "BugReports" field to DESCRIPTION, and point it to
    a bug tracker. Many online code hosting services provide bug
    trackers for free, https://github.com, https://gitlab.com, etc.


For the last two, see [example here](https://github.com/karthik/holepunch/blob/master/DESCRIPTION#L17-L18)

**Comment by karthik** [comment]
A couple more comments:

- avoid long code lines, it is bad for readability. Also,
    many people prefer editor windows that are about 80 characters
    wide. Try make your lines shorter than 80 characters

Use the Rstudio code formatting option under edit to break long lines of code.

Also 

- avoid 1:length(...), 1:nrow(...), 1:ncol(...),
    1:NROW(...) and 1:NCOL(...) expressions. They are error prone and
    result 1:0 if the expression on the right hand side is zero. Use
    seq_len() or seq_along() instead.

These appear mostly in `clust.R`.

**Comment by MAnalytics** [comment]
@karthik thanks for the comments. I will attend to these now, and keep you posted on the progress.

**Comment by karthik** [comment]
@njtierney Any chance you are able to review this submission?

**Comment by MAnalytics** [comment]
@karthik all comments addressed!
Thank you very much.

**Comment by karthik** [comment]
Thanks @MAnalytics I'm still seeking reviewers and will update this thread soon. Stay tuned.

**Comment by MAnalytics** [comment]
@karthik Thank you very much. I hope to hear from you soon.

**Comment by karthik** [comment]
@njtierney Would you be able to review this paper?

**Comment by karthik** [comment]
@mitchelloharawild 👋 
Would you be able to serve as the second reviewer for this submission? 🙏

**Comment by karthik** [comment]
@whedon add @@njtierney as reviewer

**Comment by whedon** [comment]
OK, @@njtierney is now a reviewer

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by MAnalytics** [comment]
Dear @karthik, 
cc @njtierney,
Please, could you send a reminder to reviewers to help  commence work on this submission?
Thank you as I anticipate your kind response,
Monsuru.

**Comment by arfon** [comment]
@MAnalytics - just to be clear, this submission is not yet out for review. The handling editor (@karthik) is likely still looking for a second reviewer.

**Comment by MAnalytics** [comment]
@arfon Ok. Thank you very much for your response.

**Comment by karthik** [comment]
Yes, Arfon is correct. I am still trying to locate a second reviewer. Right now very few people are accepting new review requests so it is challenging. As soon as I have reviewer #2, I will start the review.

**Comment by arfon** [comment]
:wave: @karthik - any luck identifying a second reviewer here?

**Comment by karthik** [comment]
👋 @earowang! Would you be able to serve as a second reviewer on this submission? :pray:

**Comment by MAnalytics** [comment]
@karthik<https://github.com/karthik>?  @arfon I greatly appreciate the efforts.



________________________________

**Comment by karthik** [comment]
eero is unable to review. Continuing looking.

**Comment by MAnalytics** [comment]
?Thanks for the efforts. I really hope you get someone very soon.


________________________________

**Comment by arfon** [comment]
@karthik - you may have made us of this already but this GitHub topic might help identify you some good reviewer candidates: https://github.com/topics/longitudinal-data

**Comment by karthik** [comment]
👋 @rpsychologist Would you be able to serve as the second reviewer for this submission? If yes I can provide instructions on how to review for JOSS.

**Comment by karthik** [comment]
Also pinged `@graemeleehickey`

**Comment by karthik** [comment]
Sent reminders today. If I don't get a second reviewer I'll just do it myself.

**Comment by MAnalytics** [comment]
@karthik That will be great! Thank you very much.

**Comment by MAnalytics** [comment]
Dear @karthik 
Regarding the reminders you sent, did they get back to you? If no, when would you commence the review as suggested. 
Thank you as I anticipate your kind response.

**Comment by karthik** [comment]
@whedon assign @karthik as reviewer

**Comment by whedon** [comment]
OK, @karthik is now a reviewer

**Comment by karthik** [comment]
@whedon add @njtierney  as reviewer

**Comment by whedon** [comment]
OK, @njtierney  is now a reviewer

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2379.
