### ISSUE TITLE
[PRE REVIEW]: refsplitr: author name disambiguation, author georeferencing, and mapping of coauthorship networks with 'Web of Science' data.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2021]
**Submitting author:** @embruna (<a href="http://orcid.org/0000-0003-3381-8477">Emilio M. Bruna</a>)
**Repository:** <a href="https://github.com/ropensci/refsplitr" target ="_blank">https://github.com/ropensci/refsplitr</a>
**Version:** v1.0.0
**Editor:** @kyleniemeyer
**Reviewers:** @kyleniemeyer

**Author instructions**

Thanks for submitting your paper to JOSS @embruna. **Currently, there isn't an JOSS editor assigned** to your paper.

@embruna if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.joi.2017.08.007 is OK
- 10.1126/science.aao0185 is OK
- 10.1038/504211a is OK
- 10.1371/journal.pone.0109195 is OK
- 10.1002/aris.2009.1440430113 is OK
- 10.1002/asi.22695 is OK
- 10.1101/262881 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.07 s (612.1 files/s, 71161.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               28            341            695           2022
XML                              1              0              2            441
JSON                             1              0              0            277
Markdown                         4             54              0            161
TeX                              2             12              0            134
Rmd                              2            283            366             75
YAML                             4             16              4             64
SVG                              1              0              0             52
-------------------------------------------------------------------------------
SUM:                            43            706           1067           3226
-------------------------------------------------------------------------------


Statistical information for the repository '2021' was gathered on 2020/01/17.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02021/joss.02021/10.21105.joss.02021.pdf)

**Comment by kyleniemeyer** [comment]
Hi @embruna, thanks for your submission to JOSS. To confirm, this has already been reviewed by rOpenSci? If so, can you share the review thread here?

**Comment by kyleniemeyer** [comment]
One issue: your repository is missing a LICENSE file, corresponding to a valid open-source software license

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by embruna** [comment]
This package has been reviewed by rOpenSci: [https://github.com/ropensci/software-review/issues/256](https://github.com/ropensci/software-review/issues/256), @maelle

**Comment by embruna** [comment]
> One issue: your repository is missing a LICENSE file, corresponding to a valid open-source software license

Thanks @kyleniemeyer.  The Description notes it's licensed under GPL-3, but I'll add a corresponding file right away.

**Comment by kyleniemeyer** [comment]
@embruna thanks, please do and let me know when you have

**Comment by embruna** [comment]
@kyleniemeyer It's now there, along with an edit in the DESCRIPTION pointing to it (`License: GPL-3 + file LICENSE`).

**Comment by kyleniemeyer** [comment]
@whedon add @kyleniemeyer as reviewer

**Comment by whedon** [comment]
OK, @kyleniemeyer is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2028. Feel free to close this issue now!
