### ISSUE TITLE
[PRE REVIEW]: scTree: An R package to generate antibody-compatible classifiers from single-cell sequencing data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2022]
**Submitting author:** @jspaezp (<a href="http://orcid.org/0000-0002-0065-1474">J. Sebastian Paez</a>)
**Repository:** <a href="https://github.com/jspaezp/sctree" target ="_blank">https://github.com/jspaezp/sctree</a>
**Version:** 0.0.5
**Editor:** @will-rowe
**Reviewers:** @mschubert, @jenzopr

**Author instructions**

Thanks for submitting your paper to JOSS @jspaezp. **Currently, there isn't an JOSS editor assigned** to your paper.

@jspaezp if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.18 s (538.9 files/s, 103344.0 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
HTML                             47           2033            501           8848
R                                16            387           1160           2123
Markdown                          2            121              0            600
Rmd                              16            381            414            570
CSS                               2             73             35            296
TeX                               1              5              0            278
JavaScript                        2             41             16            141
Bourne Again Shell                4             32              5            103
YAML                              4              5              1             37
SVG                               1              0              1             11
--------------------------------------------------------------------------------
SUM:                             95           3078           2133          13007
--------------------------------------------------------------------------------


Statistical information for the repository '2022' was gathered on 2020/01/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
J Sebastian Paez                 1           198              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
J Sebastian Paez            198          100.0          0.0                8.08
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s11634-016-0276-4 is OK
- 10.1093/bioinformatics/btq134 is OK
- 10.18637/jss.v077.i01 is OK
- 10.1101/335000 is OK
- 10.1038/s41467-018-03405-7 is OK
- 10.1016/j.cell.2018.05.061 is OK
- 10.1038/nbt.3519 is OK
- 10.1101/gr.209601.116 is OK
- 10.1186/s13059-014-0550-8 is OK
- 10.1093/bioinformatics/btp616 is OK
- 10.1038/nbt.4096 is OK
- 10.1038/nbt.2859 is OK
- 10.1038/ncomms14049 is OK
- 10.1093/bioinformatics/bts635 is OK
- 10.1002/cyto.a.22096 is OK
- 10.1002/0471142735.im22f08s69 is OK
- 10.1038/s41592-019-0535-3 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1038/nmeth.4197.Salmon is INVALID
```

**Comment by kyleniemeyer** [comment]
Hi @will-rowe, can you edit this submission for us?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02022/joss.02022/10.21105.joss.02022.pdf)

**Comment by kyleniemeyer** [comment]
@jspaezp FYI, it looks like your article has an invalid DOI for one of the referenes

**Comment by natallah** [comment]
Hello Kyle! Which DOI is invalid?

**Comment by natallah** [comment]
Patro, R., Duggal, G., Love, M. et al. Salmon provides fast and bias-aware quantification of transcript expression. Nat Methods 14, 417–419 (2017) doi:10.1038/nmeth.4197

The above is the issue.  Sebastian is aware and will comment soon

**Comment by kyleniemeyer** [comment]
@natallah  the DOI 10.1038/nmeth.4197.Salmon does not resolve (try https://doi.org/10.1038/nmeth.4197.Salmon), it leads to an error

**Comment by natallah** [comment]
Oh I see.  The correct DOI is https://doi.org/10.1038/nmeth.4197
(try https://doi.org/10.1038/nmeth.4197).  We will fix this!

**Comment by jspaezp** [comment]
Thanks @kyleniemeyer and @natallah, I commited and pushed the modified DOI.

**Comment by will-rowe** [comment]
Hi @kyleniemeyer. Sorry for the delay - I had to take a few days unexpected leave! Not my area but sounds interesting and I'm happy to edit for this submission.

**Comment by will-rowe** [comment]
@whedon assign @will-rowe as editor

**Comment by whedon** [comment]
OK, the editor is @will-rowe

**Comment by will-rowe** [comment]
Hi @jspaezp - sorry for the delay here. Do you have any reviewer suggestions? If not, I will consult our JOSS list to see if I can identify some suitable people.

**Comment by natallah** [comment]
I would say perhaps Mark Jensen, Charlotte Soneson, and you would be whom I would suggest

**Comment by natallah** [comment]
Marcos Vital and Lorena Pantano would be too other great options for reviewers

**Comment by kyleniemeyer** [comment]
@natallah thanks for the suggestions, but those are from our editor list—could you look at the [reviewer list][(https://bit.ly/joss-reviewers) instead?

**Comment by natallah** [comment]
Oh sorry about that:  skummerf, afrubin,dpolychr,mschubert,adamhsparks would all be good

**Comment by will-rowe** [comment]
Hi @afrubin and  @mschubert - would you please be able to review this submission for JOSS?

**Comment by mschubert** [comment]
I'd be happy to!

Side note @will-rowe: is there a way to update my topics on the reviewer list? (there's many more reviewers than when I put them it, so they should be more detailed now)

**Comment by will-rowe** [comment]
Thanks @mschubert! I don't seem to have edit rights on the JOSS reviewers doc - pinging @arfon to see if he can let us know how to update reviewer topics

**Comment by will-rowe** [comment]
Hi @skummerf - would you be able to review this submission for us?

**Comment by arfon** [comment]
> Side note @will-rowe: is there a way to update my topics on the reviewer list? (there's many more reviewers than when I put them in, so they should be more detailed now)

@mschubert - could you email me directly on arfon.smith@gmail.com to request these changes?

**Comment by will-rowe** [comment]
Hi @dpolychr - would you be willing to review this submission for us?

**Comment by will-rowe** [comment]
Hi @jenzopr - would you be able to review this submission for us?

**Comment by jenzopr** [comment]
Hi @will-rowe - I'm happy to do that!

**Comment by will-rowe** [comment]
Brilliant - thank you @jenzopr !

**Comment by will-rowe** [comment]
Sorry for the delay @jspaezp - we now have 2 reviewers and can start the review process. I'll kick things off now; this will result in a new thread being opened where we can track the reviews etc.

**Comment by will-rowe** [comment]
@whedon assign @mschubert as reviewer

**Comment by whedon** [comment]
OK, @mschubert is now a reviewer

**Comment by will-rowe** [comment]
@whedon add @jenzopr as reviewer

**Comment by whedon** [comment]
OK, @jenzopr is now a reviewer

**Comment by will-rowe** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2061.
