### ISSUE TITLE
[PRE REVIEW]: BGGM: Bayesian Gaussian Graphical Models in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2023]
**Submitting author:** @donaldRwilliams (<a href="http://orcid.org/0000-0001-6735-8785">Donald Williams </a>)
**Repository:** <a href="https://github.com/donaldRwilliams/BGGM" target ="_blank">https://github.com/donaldRwilliams/BGGM</a>
**Version:** 1.0.0
**Editor:** @akeshavan
**Reviewers:** @jayrobwilliams, @paulgovan

**Author instructions**

Thanks for submitting your paper to JOSS @donaldRwilliams. **Currently, there isn't an JOSS editor assigned** to your paper.

@donaldRwilliams if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2023 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (520.7 files/s, 126031.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               36           1388           2467           4182
HTML                             2             66              4            888
Markdown                         2            219              0            726
XML                              1              0              2            441
TeX                              2             32              0            356
Rmd                              5            181            537            130
-------------------------------------------------------------------------------
SUM:                            48           1886           3010           6723
-------------------------------------------------------------------------------


Statistical information for the repository '2023' was gathered on 2020/01/17.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by kyleniemeyer** [comment]
Hi @akeshavan, could you edit this for us?

**Comment by donaldRwilliams** [comment]
Hi:
Here are two potential reviewers.
(1) Paul-Christian Bürkner
(2) Tristan Mahr

I also noted there was an error compiling the pdf. I used the `rticles` R package to make the JOSS submission, which provided a nice template for this journal. However, there are a whole bunch of additional files in the folder "joss_paper" other than paper.md. Perhaps this caused the error ?

thanks !

**Comment by akeshavan** [comment]
hi! Happy to edit, but I’m on vacation now and will be back on Monday!

**Comment by kyleniemeyer** [comment]
@whedon assign @akeshavan as editor

**Comment by whedon** [comment]
OK, the editor is @akeshavan

**Comment by kyleniemeyer** [comment]
@akeshavan no problem, thanks!

**Comment by akeshavan** [comment]
hi :wave: @tjmahr, @mdogucu and @jkarreth -- would you be willing to review this paper for JOSS?

**Comment by jkarreth** [comment]
My apologies, but I'm overloaded with other tasks for the next few weeks and don't have the bandwidth to review this right now. Might @jayrobwilliams be available and interested?

**Comment by mdogucu** [comment]
I am sorry but I am also unable to review.

**Comment by jayrobwilliams** [comment]
Happy to review, but won't be able to get to this until after 2/7. If that timeline works, go ahead and assign me.

**Comment by akeshavan** [comment]
Thanks @jayrobwilliams!

**Comment by akeshavan** [comment]
@whedon assign @jayrobwilliams as reviewer

**Comment by whedon** [comment]
OK, @jayrobwilliams is now a reviewer

**Comment by akeshavan** [comment]
👋 hi @malmaud -- would you be interested in reviewing this paper for JOSS?

**Comment by malmaud** [comment]
This seems like a great project, but unfortunately I can't commit right now. Sorry!

**Comment by akeshavan** [comment]
👋 @volkerschmid and @paulgovan -- would you be interested to review this paper for JOSS?

**Comment by paulgovan** [comment]
Sure...sounds interesting. Happy to help.

**Comment by volkerschmid** [comment]
Sorry, I currently do not have time to review this.

**Comment by akeshavan** [comment]
@whedon add @paulgovan as reviewer

**Comment by whedon** [comment]
OK, @paulgovan is now a reviewer

**Comment by akeshavan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2111.

**Comment by akeshavan** [comment]
thanks @paulgovan and @jayrobwilliams ! I'm closing this pre-review issue, so head on over to #2111 to start the review
