### ISSUE TITLE
[REVIEW]: ExTemp: A computational and image-processing suite for extracting temporal barcodes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2026]
**Submitting author:** @shalinshah1993 (<a href="http://orcid.org/0000-0002-1406-3577">Shalin Shah</a>)
**Repository:** <a href="https://github.com/shalinshah1993/temporalDNAbarcodes" target ="_blank">https://github.com/shalinshah1993/temporalDNAbarcodes</a>
**Version:** 1.0.0
**Editor:** @csoneson
**Reviewer:** @lbugnon, @SirSharpest, @RealPolitiX
**Archive:** <a href="https://doi.org/10.5281/zenodo.3660411" target="_blank">10.5281/zenodo.3660411</a>

## Status

[![status](https://joss.theoj.org/papers/73c6bcf3245062f7e20242c3cb68fe82/status.svg)](https://joss.theoj.org/papers/73c6bcf3245062f7e20242c3cb68fe82)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/73c6bcf3245062f7e20242c3cb68fe82"><img src="https://joss.theoj.org/papers/73c6bcf3245062f7e20242c3cb68fe82/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/73c6bcf3245062f7e20242c3cb68fe82/status.svg)](https://joss.theoj.org/papers/73c6bcf3245062f7e20242c3cb68fe82)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/shalinshah1993/temporalDNAbarcodes" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@lbugnon & @SirSharpest & @RealPolitiX, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/shalinshah1993/temporalDNAbarcodes">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@shalinshah1993) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/shalinshah1993/temporalDNAbarcodes">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@shalinshah1993) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/shalinshah1993/temporalDNAbarcodes">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@shalinshah1993) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lbugnon, @SirSharpest, @RealPolitiX it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1021/acssynbio.9b00010 is OK
- 10.1007/978-3-030-00030-1_5 is OK
- 10.1021/acs.nanolett.9b00590 is OK
- 10.1364/OE.22.015982 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02026/joss.02026/10.21105.joss.02026.pdf)

**Comment by csoneson** [comment]
@lbugnon, @SirSharpest, @RealPolitiX - this is where the review happens! Please check the reviewer instructions in the issue above, and don't hesitate to ping me if you have questions.

**Comment by csoneson** [comment]
👋 @lbugnon, @SirSharpest, @RealPolitiX - I just wanted to check in on your reviews. Do you have an update on when you think you would be able to provide some comments for @shalinshah1993 (I see that @SirSharpest has opened an issue in the repo)?

**Comment by SirSharpest** [comment]
> 👋 @lbugnon, @SirSharpest, @RealPolitiX - I just wanted to check in on your reviews. Do you have an update on when you think you would be able to provide some comments for @shalinshah1993 (I see that @SirSharpest has opened an issue in the repo)?

Yes, I'll have my review finished before Monday, I think that all my issues are addressed and just need to verify before I can sign off.

**Comment by lbugnon** [comment]
All my issues have been addressed, I think it is a good work and ready to publish

**Comment by SirSharpest** [comment]
I'm happy to sign off on also.

**Comment by csoneson** [comment]
Thanks @lbugnon , @SirSharpest for your reviews. 

@lbugnon - there are still some unchecked items in your checklist above. Could you confirm that these issues have been addressed, and if so, check the boxes? 

@RealPolitiX - could you provide an update on your review status?

**Comment by shalinshah1993** [comment]
Dear @csoneson,  just following up if we have any progress here?

**Comment by csoneson** [comment]
@shalinshah1993 I'd like to hear from @RealPolitiX as well. I have reached out for an update via email.

**Comment by RealPolitiX** [comment]
Nice work, ready for publication

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02026/joss.02026/10.21105.joss.02026.pdf)

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1021/acssynbio.9b00010 is OK
- 10.1007/978-3-030-00030-1_5 is OK
- 10.1021/acs.nanolett.9b00590 is OK
- 10.1364/OE.22.015982 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
👋 @shalinshah1993 - I have gone through your manuscript and sent a few suggestions in a PR. Could you please check, merge and generate a new proof here with `@whedon generate pdf`? 

Next, please:
- [ ] check that the version information is consistently reported and report the version back here
- [ ] create a tagged release
- [ ] generate a zenodo archive
- [ ] make sure that the title and authors of the zenodo archive are identical to those of the paper (you can also add the ORCID of the authors there)
- [ ] report back here with the DOI of the zenodo archive

Finally, I would suggest to add also the JOSS paper to your README, and make it clear to users which of the papers to cite in which situation.

**Comment by shalinshah1993** [comment]
Dear @csoneson you said you sent a few suggestions in PR. I'm sorry where did you send it? 

- I created a release v1.0.0 https://github.com/shalinshah1993/temporalDNAbarcodes/releases/ 
- I have also enabled zendo integration for the repo. DOI: 10.5281/zenodo.3660411
- I have edited the README of the repo to make it more clear which papers to cite.

**Comment by csoneson** [comment]
Oops, sorry, forgot to press send...should be there now.

**Comment by csoneson** [comment]
For the Zenodo archive, please make sure that the title and author list are identical to those of the paper

**Comment by shalinshah1993** [comment]
Oh great, I accepted your PR. Thank you for those edits. 

I think the authors' names and paper names should match now. 
https://zenodo.org/record/3660411#.XkARhxNKjVo

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02026/joss.02026/10.21105.joss.02026.pdf)

**Comment by csoneson** [comment]
@whedon set 10.5281/zenodo.3660411 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3660411" target="_blank">10.5281/zenodo.3660411</a> is the archive.

**Comment by csoneson** [comment]
@whedon set 1.0.0 as version

**Comment by whedon** [comment]
OK. 1.0.0 is the version.

**Comment by csoneson** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1021/acssynbio.9b00010 is OK
- 10.1007/978-3-030-00030-1_5 is OK
- 10.1021/acs.nanolett.9b00590 is OK
- 10.1364/OE.22.015982 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1285

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1285, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by csoneson** [comment]
@openjournals/joss-eics - I believe this paper is ready to be accepted!

**Comment by csoneson** [comment]
@shalinshah1993 - I think this all looks good. I've handed it over to the EiCs for the final check and acceptance.

**Comment by shalinshah1993** [comment]
Thank you very much @csoneson for all your help and edits. Also, thank you @SirSharpest @lbugnon @RealPolitiX for your comments and feedback.

I think overall the `Extemp` package and GitHub repo look a lot more professional and clean. I'm happy that I submitted it to JOSS for peer-review.

**Comment by kthyng** [comment]
Everything looks great! You all made my job very easy!

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1226554452640923648) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1286
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02026](https://doi.org/10.21105/joss.02026)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Congratulations to @shalinshah1993 on your new publication! Thanks to @csoneson for editing and to @lbugnon, @SirSharpest, and @RealPolitiX for reviewing — we relied on your time and expertise!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02026/status.svg)](https://doi.org/10.21105/joss.02026)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02026">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02026/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02026/status.svg
   :target: https://doi.org/10.21105/joss.02026
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02026/status.svg)](https://doi.org/10.21105/joss.02026)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
