### ISSUE TITLE
[REVIEW]: shapr: An R-package for explaining machine learning models with dependence-aware Shapley values 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2027]
**Submitting author:** @martinju (<a href="http://orcid.org/0000-0003-3908-5155">Martin Jullum</a>)
**Repository:** <a href="https://github.com/NorskRegnesentral/shapr" target ="_blank">https://github.com/NorskRegnesentral/shapr</a>
**Version:** v0.1.1
**Editor:** @terrytangyuan
**Reviewer:** @frycast, @expectopatronum
**Archive:** <a href="https://doi.org/10.5281/zenodo.3641831" target="_blank">10.5281/zenodo.3641831</a>

## Status

[![status](https://joss.theoj.org/papers/f3ea13b8d2ea46c28ad740fd900831c7/status.svg)](https://joss.theoj.org/papers/f3ea13b8d2ea46c28ad740fd900831c7)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f3ea13b8d2ea46c28ad740fd900831c7"><img src="https://joss.theoj.org/papers/f3ea13b8d2ea46c28ad740fd900831c7/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f3ea13b8d2ea46c28ad740fd900831c7/status.svg)](https://joss.theoj.org/papers/f3ea13b8d2ea46c28ad740fd900831c7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/NorskRegnesentral/shapr" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@frycast & @expectopatronum, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @terrytangyuan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/NorskRegnesentral/shapr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@martinju) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/NorskRegnesentral/shapr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@martinju) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @frycast, @expectopatronum it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s10115-013-0679-x is OK
- 10.1111/1467-9868.00125 is OK
- 10.1214/aoms/1177728190 is OK
- 10.18637/jss.v040.i08 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02027/joss.02027/10.21105.joss.02027.pdf)

**Comment by terrytangyuan** [comment]
Note that @expectopatronum will not be able to review until Feb.

**Comment by frycast** [comment]
This package looks great. The vignette is especially detailed and useful.

I have two comments/questions:
NorskRegnesentral/shapr/pull/172 - A small typo here.
NorskRegnesentral/shapr/pull/171 - You may need to add the full MIT license here.

Thank you @martinju for making this package!

**Comment by nikolase90** [comment]
@frycast I've opened two issues based on your review. 

- [ ] https://github.com/NorskRegnesentral/shapr/issues/173
- [ ] https://github.com/NorskRegnesentral/shapr/issues/175

**Comment by frycast** [comment]
> 
> 
> @frycast I've opened two issues based on your review.
> 
>     * [ ]  [NorskRegnesentral/shapr#173](https://github.com/NorskRegnesentral/shapr/issues/173)
> 
>     * [ ]  [NorskRegnesentral/shapr#175](https://github.com/NorskRegnesentral/shapr/issues/175)

Thanks @nikolase90 for resolving both of those issues, and thanks for writing this great package along with @martinju .

I've opened one more small issue:

NorskRegnesentral/shapr#176

**Comment by nikolase90** [comment]
Hi @frycast; https://github.com/NorskRegnesentral/shapr/pull/174 and https://github.com/NorskRegnesentral/shapr/pull/177 are now merged into master. Let us know if you have any further comments, and thanks for the nice comment about the package!

**Comment by frycast** [comment]
> 
> 
> Hi @frycast; [NorskRegnesentral/shapr#174](https://github.com/NorskRegnesentral/shapr/pull/174) and [NorskRegnesentral/shapr#177](https://github.com/NorskRegnesentral/shapr/pull/177) are now merged into master. Let us know if you have any further comments, and thanks for the nice comment about the package!

Thank you @nikolase90 . I've ticked off my review checklist, and now we wait to hear from @expectopatronum .

**Comment by martinju** [comment]
> > Hi @frycast; [NorskRegnesentral/shapr#174](https://github.com/NorskRegnesentral/shapr/pull/174) and [NorskRegnesentral/shapr#177](https://github.com/NorskRegnesentral/shapr/pull/177) are now merged into master. Let us know if you have any further comments, and thanks for the nice comment about the package!
> 
> Thank you @nikolase90 . I've ticked off my review checklist, and now we wait to hear from @expectopatronum .

Thanks for finishing the helpful review, @frycast .
I've now closed the license issue/PR.

**Comment by terrytangyuan** [comment]
Hi @expectopatronum, would you be able to start the review soon?

**Comment by expectopatronum** [comment]
> Hi @expectopatronum, would you be able to start the review soon?

@terrytangyuan Yes, I am working on it!

**Comment by expectopatronum** [comment]
Hi @martinju,
there are some minor remarks regarding the references:
* Lundberg, S. (2019): I am not sure if this is correct/necessary. On their Github page they state which references should be used, this one doesn't seem to be there. (in case this actually should be there, I think SHAP should be capitalized)
* Maybe this also needs to be cited (very recent): https://raw.githubusercontent.com/slundberg/shap/master/docs/references/tree_explainer.bib
* Pedersen & Benesty: Title should be "lime: Local Interpretable Model-Agnostic Explanations"

Furthermore, capitalization of the titles and conference names is not consistent (some are capitalized, others are all lower case).

**Comment by martinju** [comment]
Hi @expectopatronum 

Thank you for raising these issues. 

I've opened an issue for these at https://github.com/NorskRegnesentral/shapr/pull/178 (let's do any further discussion on there) and an associated PR at https://github.com/NorskRegnesentral/shapr/pull/179

The pdf for the PR-version of the paper https://github.com/NorskRegnesentral/shapr/blob/references/inst/joss_paper/paper.pdf

Please let me know if you find this satisfactory.

**Comment by expectopatronum** [comment]
Regarding community guidelines: Could you add a hint where questions should be put? (most likely as a Github issue?)

**Comment by expectopatronum** [comment]
Regarding your vignette (part 1 - to be continued tomorrow):
* Just a minor remark (since it is not an issue with your package but with devtools): If you want user to be able to use `vignette(shapr)`, they need to install the package using `devtools::install_github("NorskRegnesentral/shapr", build_vignettes = TRUE)`, because apparently [devtools does not build vignettes automatically](https://stackoverflow.com/a/33617870/1117932).
* Building the vignette failed because of missing requirment `caret`, you might need to add it to your requirements? Same will happen for `xgboost` (I had to install it in order to run your example from the README), and `gbm`. 
* For opening the vignette the user first has to figure out it's name, naming it 'shapr' would make that easier. Or mention in the description that one has to call `vignette("understanding_shapr")`.

**Comment by nikolase90** [comment]
Hi @expectopatronum! 

We'll add a remark that if you want to actually want to build the vignette and README you'll have to slightly modify the installment procedure. 

By doing
```
devtools::install_github("NorskRegnesentral/shapr", dependencies = TRUE)
```
you'll also install packages listed under `Suggets` in `DESCRIPTION ` (where `xgboost` and `caret` is listed). By doing this we avoid the users to download all the different packages.  The default value is `dependencies = NA`, which only installs the packages listed under `Imports`,  `Imports` and `LinkingTo`.

**Comment by terrytangyuan** [comment]
@nikolase90 I just realized that there are many optional dependencies in DESCRIPTION. Are there any dependent packages that are worth being cited?

**Comment by nikolase90** [comment]
@terrytangyuan Most of the packages listed under `Suggests` are not necessary to cite. Though we could add a citation for `RcppArmadillo` (since that is part of the core of our package). In addition to this we could also site the packages of the models we support natively.

**Comment by terrytangyuan** [comment]
@nikolase90 Sounds good.

**Comment by expectopatronum** [comment]
Vignette (part 2):

* The citations look "weird", I tried to figure out whether I build the vignette wrong or it needs changing. 
![image](https://user-images.githubusercontent.com/2265475/73718117-e4690b80-471b-11ea-9a2a-d66779a635e5.png)
If it looks ok for you, then ignore this comment :) (maybe you know how I can compile it correctly)

* Content:
> and that we want to explain the predictions for new sets of features.

shouldn't this be:

> and that we want to explain the predictions for new sets of examples. ?

* Formatting of the following formula (again, if I built the vignette incorrectly, never mind)
![image](https://user-images.githubusercontent.com/2265475/73718323-740eba00-471c-11ea-958b-250240cd06f1.png)

* Formatting again and it probably should say KernSHAP instead of KerSHAP

![image](https://user-images.githubusercontent.com/2265475/73718365-9bfe1d80-471c-11ea-881f-59a85dd37390.png)

Besides those remarks the vignette is really great and helpful!

After https://github.com/NorskRegnesentral/shapr/issues/178, https://github.com/NorskRegnesentral/shapr/issues/180 and https://github.com/NorskRegnesentral/shapr/issues/181 are resolved I am good to go!

**Comment by martinju** [comment]
Thanks for the vignette comments @expectopatronum 
We will improve the vignette installation instructions and look into the potential typo.
Btw, we also have a html version of the vignette at our pckdown site: https://norskregnesentral.github.io/shapr/articles/understanding_shapr.html 

To actually build the vignette with `install_github` you also need the argument `build_vignette = T`

There have been some changes in devtools/remotes regarding defaults that are relevant if you want to build the vignette, but for versions newer than 2.1.0 and older than 2.0.0 (see https://github.com/r-lib/remotes/issues/353), you should install the package with

`devtools::install_github("NorskRegnesentral/shapr",dependencies = T,build_vignettes = T)`

if you want to install the package (and build the vignette at installation)
To display the vignette, then simply run
`vignette("understanding_shapr",package="shapr")`
Does this solve your formatting problem?

**Comment by nikolase90** [comment]
@terrytangyuan https://github.com/NorskRegnesentral/shapr/commit/5901393952249b3544736e1e3496d41b5cc35c55 and https://github.com/NorskRegnesentral/shapr/commit/13f1d460d3d00dcfb62742597875f8890f71b8eb adds citations for additional packages.

**Comment by martinju** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02027/joss.02027/10.21105.joss.02027.pdf)

**Comment by martinju** [comment]
@expectopatronum 

We now consider NorskRegnesentral/shapr#178, NorskRegnesentral/shapr#180, and NorskRegnesentral/shapr#181 resolved in master.

Please let us know whether or not you find it satisfactory.

**Comment by nikolase90** [comment]
> Regarding your vignette (part 1 - to be continued tomorrow):
> 
> * Just a minor remark (since it is not an issue with your package but with devtools): If you want user to be able to use `vignette(shapr)`, they need to install the package using `devtools::install_github("NorskRegnesentral/shapr", build_vignettes = TRUE)`, because apparently [devtools does not build vignettes automatically](https://stackoverflow.com/a/33617870/1117932).
> * Building the vignette failed because of missing requirment `caret`, you might need to add it to your requirements? Same will happen for `xgboost` (I had to install it in order to run your example from the README), and `gbm`.
> * For opening the vignette the user first has to figure out it's name, naming it 'shapr' would make that easier. Or mention in the description that one has to call `vignette("understanding_shapr")`.

@expectopatronum This issue was fixed with https://github.com/NorskRegnesentral/shapr/commit/8cb58f81892d6a8c7fc6462d9796fa618cb0d98a.

**Comment by expectopatronum** [comment]
Everything looks fine, except maybe the documentation of `none`, I commented [here](https://github.com/NorskRegnesentral/shapr/issues/180#issuecomment-582251441)

**Comment by nikolase90** [comment]
@expectopatronum Your last comment should be fixed with https://github.com/NorskRegnesentral/shapr/pull/191.

**Comment by expectopatronum** [comment]
Perfect! From my point of view the paper is good to go.

**Comment by terrytangyuan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s10115-013-0679-x is OK
- 10.1111/1467-9868.00125 is OK
- 10.1214/aoms/1177728190 is OK
- 10.18637/jss.v040.i08 is OK
- 10.18637/jss.v077.i01 is OK

MISSING DOIs

- https://doi.org/10.1038/s42256-019-0138-9 may be missing for title: From local explanations to global understanding with explainable AI for trees
- https://doi.org/10.1016/j.csda.2013.02.005 may be missing for title: RcppArmadillo: Accelerating R with high-performance C++ linear algebra

INVALID DOIs

- None
```

**Comment by terrytangyuan** [comment]
@martinju Could you address the above missing DOIs?

**Comment by martinju** [comment]
Will fix!

**Comment by martinju** [comment]
@terrytangyuan This is now resolved in https://github.com/NorskRegnesentral/shapr/pull/192

**Comment by martinju** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s10115-013-0679-x is OK
- 10.1111/1467-9868.00125 is OK
- 10.1214/aoms/1177728190 is OK
- 10.18637/jss.v040.i08 is OK
- 10.18637/jss.v077.i01 is OK

MISSING DOIs

- https://doi.org/10.1038/s42256-019-0138-9 may be missing for title: From local explanations to global understanding with explainable AI for trees
- https://doi.org/10.1016/j.csda.2013.02.005 may be missing for title: RcppArmadillo: Accelerating R with high-performance C++ linear algebra

INVALID DOIs

- None
```

**Comment by martinju** [comment]
@whedon check references

**Comment by nikolase90** [comment]
@martinju Do you need to generate the file again?

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s10115-013-0679-x is OK
- 10.1111/1467-9868.00125 is OK
- 10.1214/aoms/1177728190 is OK
- 10.18637/jss.v040.i08 is OK
- 10.18637/jss.v077.i01 is OK

MISSING DOIs

- https://doi.org/10.1038/s42256-019-0138-9 may be missing for title: From local explanations to global understanding with explainable AI for trees
- https://doi.org/10.1016/j.csda.2013.02.005 may be missing for title: RcppArmadillo: Accelerating R with high-performance C++ linear algebra

INVALID DOIs

- None
```

**Comment by terrytangyuan** [comment]
@whedon generate pdf

**Comment by martinju** [comment]
> @martinju Do you need to generate the file again?

Ah, of course (I think)

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02027/joss.02027/10.21105.joss.02027.pdf)

**Comment by terrytangyuan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s10115-013-0679-x is OK
- 10.1111/1467-9868.00125 is OK
- 10.1214/aoms/1177728190 is OK
- 10.18637/jss.v040.i08 is OK
- 10.1038/s42256-019-0138-9 is OK
- 10.1016/j.csda.2013.02.005 is OK
- 10.18637/jss.v077.i01 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by terrytangyuan** [comment]
At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:
* The title of the archive is the same as the JOSS paper title
* That the authors of the archive are the same as the JOSS paper authors
I can then move forward with accepting the submission.

**Comment by nikolase90** [comment]
@terrytangyuan New release made with https://github.com/NorskRegnesentral/shapr/pull/194. See also https://github.com/NorskRegnesentral/shapr/releases/tag/v0.1.1.

**Comment by terrytangyuan** [comment]
@whedon set v0.1.1 as version

**Comment by whedon** [comment]
OK. v0.1.1 is the version.

**Comment by terrytangyuan** [comment]
Thanks. Now we just need a DOI of the archive.

**Comment by nikolase90** [comment]
DOI: 10.5281/zenodo.3641831

**Comment by terrytangyuan** [comment]
@whedon set 10.5281/zenodo.3641831 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3641831" target="_blank">10.5281/zenodo.3641831</a> is the archive.

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s10115-013-0679-x is OK
- 10.1111/1467-9868.00125 is OK
- 10.1214/aoms/1177728190 is OK
- 10.18637/jss.v040.i08 is OK
- 10.1038/s42256-019-0138-9 is OK
- 10.1016/j.csda.2013.02.005 is OK
- 10.18637/jss.v077.i01 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1271

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1271, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by terrytangyuan** [comment]
@openjournals/joss-eics The paper looks good now. Could you take it from here?

**Comment by kthyng** [comment]
Ok things are looking good!

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1225108947092287495) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1272
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02027](https://doi.org/10.21105/joss.02027)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
The DOI resolution is looking weird so let's wait before closing this up.

**Comment by kthyng** [comment]
@openjournals/dev This DOI link doesn't look like it usually does while it is resolving. Any ideas? Just wait longer?

**Comment by arfon** [comment]
This issue is being caused by `formatted_doi: XX.XXXXX/joss.XXXXX` being set in the `paper.md`. This shouldn't be in the template and a fix was applied in `rticles` in https://github.com/rstudio/rticles/pull/272

I've reprocessed this submission manually and the updated PDF should be resolving soon on the JOSS website.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02027/status.svg)](https://doi.org/10.21105/joss.02027)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02027">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02027/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02027/status.svg
   :target: https://doi.org/10.21105/joss.02027
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02027/status.svg)](https://doi.org/10.21105/joss.02027)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by martinju** [comment]
I would like to express my gratitude to the editor @terrytangyuan and the two reviewers @frycast  and @expectopatronum for a thorough, yet rapid, review process that led to an improved the paper, the package, and the descriptions in the README in our GitHub repo.

Thank you!

**Comment by kthyng** [comment]
Congrats to @martinju on your new publication! Thanks for your time and expertise to @terrytangyuan as editor and @frycast and @expectopatronum for reviewing.
