### ISSUE TITLE
[REVIEW]: WEPPCLIFF: A command-line tool to process climate inputs for soil loss models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2029]
**Submitting author:** @ryanpmcg (<a href="http://orcid.org/0000-0003-0464-9774">Ryan McGehee</a>)
**Repository:** <a href="https://github.com/ryanpmcg/WEPPCLIFF" target ="_blank">https://github.com/ryanpmcg/WEPPCLIFF</a>
**Version:** 1.4
**Editor:** @arfon
**Reviewers:** @kbarnhart, @marianadobre, @baharmon
**Archive:** <a href="https://doi.org/10.5281/zenodo.3820633" target="_blank">10.5281/zenodo.3820633</a>

## Status

[![status](https://joss.theoj.org/papers/d35b4045a0b26b2baedcc2dc26360038/status.svg)](https://joss.theoj.org/papers/d35b4045a0b26b2baedcc2dc26360038)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d35b4045a0b26b2baedcc2dc26360038"><img src="https://joss.theoj.org/papers/d35b4045a0b26b2baedcc2dc26360038/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d35b4045a0b26b2baedcc2dc26360038/status.svg)](https://joss.theoj.org/papers/d35b4045a0b26b2baedcc2dc26360038)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ryanpmcg/WEPPCLIFF" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kbarnhart, @marianadobre, @baharmon please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ryanpmcg/WEPPCLIFF">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ryanpmcg) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ryanpmcg/WEPPCLIFF">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ryanpmcg) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ryanpmcg/WEPPCLIFF">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ryanpmcg) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @frengers, @stoor001, @khaors it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.2489/jswc.74.4.334 may be missing for title: Updated climate database and impacts on WEPP model predictions
- https://doi.org/10.13031/2013.27921 may be missing for title: Erosivity index values for northern Mississippi
- https://doi.org/10.2489/jswc.73.4.363 may be missing for title: Benchmarking reliable erosion indices from quarter-hour station data for climate studies in the Southeastern United States

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02029/joss.02029/10.21105.joss.02029.pdf)

**Comment by kbarnhart** [comment]
:wave: ryanpmcg, @frengers, @stoor001, @khaors this is the review thread for the paper. All of our communications will happen here from now on.

All reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#2029` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@kbarnhart) if you have any questions/concerns.

**Comment by danielskatz** [comment]
👋 @kbarnhart - It doesn't seem like anything has happened here in 3 1/2 weeks...  Can you provide a status update on this review?

**Comment by kbarnhart** [comment]
Thanks for the reminder @danielskatz. 

@frengers, @stoor001, @khaors could you provide an estimate for when you expect to complete your reviews? We are nearing the end of the 2-4 week window in which we typically try and complete JOSS reviews. 

Please let me know if you have any questions or concerns.

**Comment by kbarnhart** [comment]
:wave: @frengers, @stoor001, @khaors a friendly reminder to complete your review and/or post and update here. If you have any questions or concerns about the review process, please let me know. 

Thanks again for contributing to a JOSS review.

**Comment by frengers** [comment]
I’m going to try to have this done by the end of the week.

Best,

Francis

**Comment by kbarnhart** [comment]
@frengers thanks for the update. 

@stoor001 and @khaors could you provide an update regarding when you anticipate finishing your reviews.

**Comment by kbarnhart** [comment]
:wave: @frengers @stoor001 @khaors a friendly reminder to complete your review and/or post an update here on when we might expect a review. 

Thanks again for participating in the JOSS review process.

**Comment by ryanpmcg** [comment]
@kbarnhart do you have emails or other contact methods for @khaors and @stoor001? I noticed that neither of those reviewers have had any commit activity on GitHub recently. They may not be getting these messages at all.

**Comment by kbarnhart** [comment]
@ryanpmcg thank you for the thought. I have already reached out to both of them via email.

**Comment by kbarnhart** [comment]
@whedon re-invite @frengers as reviewer

**Comment by whedon** [comment]
The reviewer already has a pending invite.

@frengers please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by kbarnhart** [comment]
@frengers you mentioned to me earlier today that you were having issues checking the check boxes (this is a problem we are having in general at JOSS right now, sorry). 

I believe that you should be able to fix this by clicking the above link. Please let me know if you continue to have checkbox editing issues.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by frengers** [comment]
HI everyone.  I attempted to review WEPPCLIFF, but I wasn't able to run the auto test.sh.  I tried to run the Autotest.sh and it failed because I didn't have the "backports" package installed in R.  However, after I installed the package, I got the same error message and Autotest.sh once again failed.

**Comment by ryanpmcg** [comment]
@frengers did you run the tutorial successfully first? The autotest.sh script assumes you have done that first. I will revise the language to make this more clear.

**Comment by ryanpmcg** [comment]
Adding to my previous comment, I could make installation redundant (i.e. dependencies would be installed in both the autotest scripts and the autotutorial scripts). Right now they are checked in both, but only the tutorial installs them.

**Comment by kbarnhart** [comment]
@frengers would you create an issue in the main repository and provide the specific error message you got. I think that a dedicated issue thread would be better to discuss this on rather than this thread. Then @ryanpmcg can respond directly on that thread. 

@ryanpmcg I would recommend that installation is separate from running tutorials. I'd also recommend putting installation instructions in the Readme so they are easy to find. If I understand correctly this would just mean putting instructions to navigate to the main directory and execute:
```
Rscript --vanilla WEPPCLIFF.R --args -fr t
```

**Comment by kbarnhart** [comment]
@ryanpmcg I also wanted to follow up with an editorial handling update. At this point I'm going to assume that we won't hear from  @stoor001 or @khaors and am going to remove them. I will change from serving as the editor to being the second reviewer (JOSS only requires 2 reviews) and @arfon has agreed to be the handling editor. 

Let me know if you have any questions.

**Comment by kbarnhart** [comment]
@whedon passing @kbarnhart as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kbarnhart** [comment]
@whedon remove @stoor001 as reviewer

**Comment by whedon** [comment]
OK, @stoor001 is no longer a reviewer

**Comment by kbarnhart** [comment]
@whedon remove @khaors as reviewer

**Comment by whedon** [comment]
OK, @khaors is no longer a reviewer

**Comment by kbarnhart** [comment]
@whedon add @kbarnhart as reviewer

**Comment by whedon** [comment]
OK, @kbarnhart is now a reviewer

**Comment by kbarnhart** [comment]
@whedon assign @arfon as editor

**Comment by arfon** [comment]
> @whedon assign @arfon as editor

👍 thanks @katyhuff!

**Comment by ryanpmcg** [comment]
Those were all great comments @kbarnhart I will be addressing them all soon. Looking forward to your comments @frengers.

**Comment by kbarnhart** [comment]
@ryanpmcg a very quick update on my end. I am almost finished opening issues associated with my review. I may have zero, one, or two more as I revisit the code/checklist. While I may not be able to actually check off all my checklist boxes in the next few days, I'll open any remaining issues I need to by the middle of this week.

**Comment by arfon** [comment]
:wave: @frengers - I just wanted to check in an see how you're getting on with your review? (I also sent you an email a few minutes ago too.)

**Comment by kbarnhart** [comment]
@ryanpmcg and @arfon I've now opened all the issues I plan to open associated with this review. I expect to be able to complete my review checklist once these issues are resolved. I'll continue to correspond with @ryanpmcg on those issue threads.

**Comment by arfon** [comment]
👍ok thanks for the updated @kbarnhart.

**Comment by ryanpmcg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02029/joss.02029/10.21105.joss.02029.pdf)

**Comment by kbarnhart** [comment]
@whedon remove @frengers as reviewer

**Comment by whedon** [comment]
OK, @frengers is no longer a reviewer

**Comment by arfon** [comment]
@whedon add @marianadobre as reviewer

**Comment by whedon** [comment]
OK, @marianadobre is now a reviewer

**Comment by arfon** [comment]
@marianadobre - many thanks for agreeing to review this submission! Please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Also, you'll need to accept this invite to be able to  update the checklist as you go: https://github.com/openjournals/joss-reviews/invitations

Any questions/concerns please let me know.

**Comment by arfon** [comment]
@whedon add @baharmon as reviewer

**Comment by whedon** [comment]
OK, @baharmon is now a reviewer

**Comment by arfon** [comment]
@baharmon  - many thanks for agreeing to review this submission! Please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Also, you'll need to accept this invite to be able to update the checklist as you go: https://github.com/openjournals/joss-reviews/invitations

Any questions/concerns please let me know.

**Comment by baharmon** [comment]
I made several suggestions in the following issues in the WEPPCLIFF repo:
ryanpmcg/WEPPCLIFF#13
ryanpmcg/WEPPCLIFF#12
ryanpmcg/WEPPCLIFF#2

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02029/joss.02029/10.21105.joss.02029.pdf)

**Comment by ryanpmcg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02029/joss.02029/10.21105.joss.02029.pdf)

**Comment by arfon** [comment]
Just a quick update from me - I emailed @marianadobre this morning to see if they were able to complete this review soon. If not, I propose that we accept this submission with the two complete reviews we already have.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.18637/jss.v045.i03 may be missing for title: mice: Multivariate Imputation by Chained Equations in R
- https://doi.org/10.2489/jswc.74.4.334 may be missing for title: Updated climate database and impacts on WEPP model predictions
- https://doi.org/10.13031/2013.27921 may be missing for title: Erosivity index values for northern Mississippi
- https://doi.org/10.2489/jswc.73.4.363 may be missing for title: Benchmarking reliable erosion indices from quarter-hour station data for climate studies in the Southeastern United States

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@ryanpmcg - could you take a look at the list of suggested DOIs for your references and add them to your BibTeX as entries like this `doi = {10.18637/jss.v045.i03}` if they are correct?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02029/joss.02029/10.21105.joss.02029.pdf)

**Comment by arfon** [comment]
@ryanpmcg - Once you've addressed the DOI question above, could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by ryanpmcg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02029/joss.02029/10.21105.joss.02029.pdf)

**Comment by ryanpmcg** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18637/jss.v045.i03 is OK
- 10.2489/jswc.74.4.334 is OK
- 10.13031/2013.27921 is OK
- 10.2489/jswc.73.4.363 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by ryanpmcg** [comment]
@arfon I have created the archive on Zenodo and updated the DOIs. Here is the doi for Zenodo:
10.5281/zenodo.3820633

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3820633 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3820633" target="_blank">10.5281/zenodo.3820633</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18637/jss.v045.i03 is OK
- 10.2489/jswc.74.4.334 is OK
- 10.13031/2013.27921 is OK
- 10.2489/jswc.73.4.363 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1444

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1444, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1259921073123946496) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1445
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02029](https://doi.org/10.21105/joss.02029)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@kbarnhart, @marianadobre, @baharmon - many thanks for your reviews here ✨ 

@ryanpmcg - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02029/status.svg)](https://doi.org/10.21105/joss.02029)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02029">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02029/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02029/status.svg
   :target: https://doi.org/10.21105/joss.02029
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02029/status.svg)](https://doi.org/10.21105/joss.02029)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
