### ISSUE TITLE
[PRE REVIEW]: Text detection in screen images with a Convolutional Neural Network

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#203]
**Submitting author:** @domoritz (<a href="http://orcid.org/0000-0002-3110-1053">ROBYN DOMINIK MORITZ</a>)
**Repository:** <a href="https://github.com/domoritz/label_generator" target ="_blank">https://github.com/domoritz/label_generator</a>
**Version:** v1.1
**Editor:** @jakevdp
**Reviewer:** @ekolve

**What this issue is for**

Thanks for submitting your paper to JOSS @domoritz. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @arokem @jakevdp @danielskatz - would one of you be willing to edit this submission for JOSS?

**Comment by jakevdp** [comment]
@whedon commands

**Comment by jakevdp** [comment]
@whedon assign @jakevdp as editor

**Comment by whedon** [comment]
OK, the editor is @jakevdp

**Comment by jakevdp** [comment]
@whedon assign @ekolve as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ekolve

**Comment by jakevdp** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by jakevdp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/235. Feel free to close this issue now!
