### ISSUE TITLE
[REVIEW]: FGTpartitioner: A rapid method for parsimonious delimitation of ancestry breakpoints in large genome-wide SNP datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2030]
**Submitting author:** @tkchafin (<a href="http://orcid.org/0000-0001-8687-5905">Tyler Chafin</a>)
**Repository:** <a href="https://github.com/tkchafin/FGTpartitioner" target ="_blank">https://github.com/tkchafin/FGTpartitioner</a>
**Version:** v1.0.1
**Editor:** @lpantano
**Reviewer:** @dangeles, @YichaoOU
**Archive:** <a href="https://doi.org/10.5281/zenodo.3635843" target="_blank">10.5281/zenodo.3635843</a>

## Status

[![status](https://joss.theoj.org/papers/ea336b5f861c87d5a0321bc85f000985/status.svg)](https://joss.theoj.org/papers/ea336b5f861c87d5a0321bc85f000985)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ea336b5f861c87d5a0321bc85f000985"><img src="https://joss.theoj.org/papers/ea336b5f861c87d5a0321bc85f000985/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ea336b5f861c87d5a0321bc85f000985/status.svg)](https://joss.theoj.org/papers/ea336b5f861c87d5a0321bc85f000985)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/tkchafin/FGTpartitioner" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dangeles & @YichaoOU, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/tkchafin/FGTpartitioner">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@tkchafin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/tkchafin/FGTpartitioner">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@tkchafin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dangeles, @YichaoOU it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1534/genetics.109.103010 is OK
- 10.1038/s41559-018-0611-6 is OK
- 10.1186/1479-7364-7-1 is OK
- 10.1126/sciadv.1501714 is OK
- 10.1145/1854776.1854788 is OK
- 10.1093/bioinformatics/btr330 is OK
- 10.3390/genes9030123 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02030/joss.02030/10.21105.joss.02030.pdf)

**Comment by YichaoOU** [comment]
The documentation and manuscript are well written. Installation and test cases are easy to follow. 

In my case, `./FGTpartitioner.py -h` does not work, but `python FGTpartitioner.py -h` works.

The GitHub repo provides examples but the documentation didn't specifically provide test commands such as, `python FGTpartitioner.py -v examples/example_1.vcf.gz`

Minor comments:

1.  What is the time complexity for your algorithm? Remember in the Wang 2010 paper, they claimed to have O(mn) and O(nm^2) in their proposed DP algorithms. It is OK that you don't write a formal algorithmic complexity analysis, but I think it is better to show the complexity of your algorithm.

2. Did you use any publicly available data to verify your method? 

Thanks,
Yichao

**Comment by dangeles** [comment]
This is a neat algorithm that addresses an important problem for non-canonical model organism genomics. The README and paper are well-written, and in general the code is well-documented and nicely written.

Doc-strings are missing from all defined function in `FGTpartitioner.py`. It would improve the code significantly to add short doc-strings explaining the input, output and purpose of each function.

Two example datasets are provided, but to the best of my ability, it appears they give identical results, and no guidance is given to the user as to why two examples are provided. The `example_noHet` is included without a `.tbi` file (probably a good teaching moment). On the other hand, additional files are provided within the examples folder that could probably be ignored or documented somewhere. 

Best,
David

**Comment by lpantano** [comment]
Hey @tkchafin, do you think you could address the few comments of the editors?

**Comment by tkchafin** [comment]
@lpantano 
- Added information to the README with further benchmarking information including publicly-available data (accession numbers for NCBI SRA) which was used for comparison/ validation against some other published methods. 
- Fixed the path issue causing the "-h" issue both reviewers noted
- Added an Examples section to README given explicit commands to verify functionality 
- Added a README file to examples/ directory stating what each file is, and standardized the file naming in that directory
- Added docstrings throughout
Most recent commit (https://github.com/tkchafin/FGTpartitioner/commit/aa8fe7c35ed0887cfd7621175a919e907f60053d) is up to date on all of these changes

**Comment by lpantano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02030/joss.02030/10.21105.joss.02030.pdf)

**Comment by lpantano** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1534/genetics.109.103010 is OK
- 10.1038/s41559-018-0611-6 is OK
- 10.1186/1479-7364-7-1 is OK
- 10.1126/sciadv.1501714 is OK
- 10.1145/1854776.1854788 is OK
- 10.1093/bioinformatics/btr330 is OK
- 10.3390/genes9030123 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lpantano** [comment]
@tkchafin, thank you! Then, last two steps: 1) is the version still v1.0.0, 2) can you create a zenodo DOI link where the title and the author match exactly the paper information and give it to us? 
Thanks!

**Comment by tkchafin** [comment]
@lpantano 
- Version: 1.0.1
- DOI: 10.5281/zenodo.3635843

**Comment by lpantano** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by lpantano** [comment]
@whedon set  10.5281/zenodo.3635843 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3635843" target="_blank">10.5281/zenodo.3635843</a> is the archive.

**Comment by lpantano** [comment]
@openjournals/joss-eics, we are ready here

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2030 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2030 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:73:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1534/genetics.109.103010 is OK
- 10.1038/s41559-018-0611-6 is OK
- 10.1186/1479-7364-7-1 is OK
- 10.1126/sciadv.1501714 is OK
- 10.1145/1854776.1854788 is OK
- 10.1093/bioinformatics/btr330 is OK
- 10.3390/genes9030123 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02030/joss.02030/10.21105.joss.02030.pdf)

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2030 with the following error: 

 sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.02030.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1534/genetics.109.103010 is OK
- 10.1038/s41559-018-0611-6 is OK
- 10.1186/1479-7364-7-1 is OK
- 10.1126/sciadv.1501714 is OK
- 10.1145/1854776.1854788 is OK
- 10.1093/bioinformatics/btr330 is OK
- 10.3390/genes9030123 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@openjournals/dev I'm not able to figure out what is going wrong with the paper here. Could you help?

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2030 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2030 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:73:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1534/genetics.109.103010 is OK
- 10.1038/s41559-018-0611-6 is OK
- 10.1186/1479-7364-7-1 is OK
- 10.1126/sciadv.1501714 is OK
- 10.1145/1854776.1854788 is OK
- 10.1093/bioinformatics/btr330 is OK
- 10.3390/genes9030123 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1534/genetics.109.103010 is OK
- 10.1038/s41559-018-0611-6 is OK
- 10.1186/1479-7364-7-1 is OK
- 10.1126/sciadv.1501714 is OK
- 10.1145/1854776.1854788 is OK
- 10.1093/bioinformatics/btr330 is OK
- 10.3390/genes9030123 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1273

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1273, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
> @openjournals/dev I'm not able to figure out what is going wrong with the paper here. Could you help?

Apologies, I accidentally introduced a regression last night. This should be fixed now.

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1225452557138571264) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1276
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02030](https://doi.org/10.21105/joss.02030)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
Ok it looks like everything is in order!

Congratulations to @tkchafin on your new publication! Thanks very much for your time and expertise to editor @lpantano and reviewers @dangeles and @YichaoOU!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02030/status.svg)](https://doi.org/10.21105/joss.02030)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02030">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02030/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02030/status.svg
   :target: https://doi.org/10.21105/joss.02030
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02030/status.svg)](https://doi.org/10.21105/joss.02030)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
