### ISSUE TITLE
[PRE REVIEW]: MF2: A Collection of Multi-Fidelity Benchmark Functions in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2031]
**Submitting author:** @sjvrijn (<a href="http://orcid.org/0000-0001-6159-041X">Sander van Rijn</a>)
**Repository:** <a href="https://github.com/sjvrijn/mf2" target ="_blank">https://github.com/sjvrijn/mf2</a>
**Version:** 2019.11.3
**Editor:** @melissawm
**Reviewers:** @petroniocandido

**Author instructions**

Thanks for submitting your paper to JOSS @sjvrijn. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @melissawm.

@sjvrijn if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.16 s (334.7 files/s, 17993.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          27            545            626            838
reStructuredText                20            122             98            259
Markdown                         2             40              0            167
TeX                              1              4              0            133
YAML                             3              6             11             35
make                             1              4              6              9
-------------------------------------------------------------------------------
SUM:                            54            721            741           1441
-------------------------------------------------------------------------------


Statistical information for the repository '2031' was gathered on 2020/01/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
S.J. van Rijn                   83          5997           4332           91.33
Sander van Rijn                 19           756            224            8.67

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
S.J. van Rijn              1552           25.9          3.2                8.38
Sander van Rijn             457           60.4          1.5               35.67
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s00158-014-1213-9 is OK
- 10.1007/s00158-014-1209-5 is OK
- 10.5281/zenodo.2594848 is OK
- 10.1098/rspa.2007.1900 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02031/joss.02031/10.21105.joss.02031.pdf)

**Comment by kyleniemeyer** [comment]
Hi @melissawm, this looks to fit in your area of expertise very well—do you have the bandwidth to handle another submission?

**Comment by sjvrijn** [comment]
I would suggest some of the following reviewers:

- petroniocandido
- benjamin-lee
- torressa
- jmadera
- zbeekman
- lucashn
- tupi
- sarats

**Comment by melissawm** [comment]
Thank you, @kyleniemeyer , I can take this one. 

@sjvrijn I'll be contacting potential reviewers shortly, thanks for the suggestions.

**Comment by melissawm** [comment]
@whedon assign @melissawm as editor

**Comment by whedon** [comment]
OK, the editor is @melissawm

**Comment by sjvrijn** [comment]
@melissawm Have you had any time to look at the reviewers yet?

**Comment by melissawm** [comment]
@petroniocandido Hello, would you be willing/available to review this software paper for JOSS? Thank you!

**Comment by melissawm** [comment]
@benjamin-lee Hello, would you be willing/available to review this software paper for JOSS? Thank you!

**Comment by petroniocandido** [comment]
@melissawm Yes, sure! It is my first review for FOSS,  is chefe a manual of good practices?

**Comment by melissawm** [comment]
@petroniocandido you can check the general reviewer guidelines [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html), and if you have any questions, please let me know.

Once I've assigned you as reviewer, this issue is going to be closed and a review issue will be opened with a checklist for each of the reviewers.

**Comment by melissawm** [comment]
@whedon add @petroniocandido as reviewer

**Comment by whedon** [comment]
OK, @petroniocandido is now a reviewer

**Comment by melissawm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2049.
