### ISSUE TITLE
[PRE REVIEW]: stRat stat: a R-based software for the digitization of stratigraphic sections and assembly of large-stratigraphic datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2032]
**Submitting author:** @ActiveMargins (<a href="http://orcid.org/0000-0002-2345-2865">Daniel Coutts</a>)
**Repository:** <a href="https://github.com/ActiveMargins/stRatstat" target ="_blank">https://github.com/ActiveMargins/stRatstat</a>
**Version:** v1.0
**Editor:** @kthyng
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @ActiveMargins. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kthyng.

@ActiveMargins if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

**Comment by whedon** [comment]
PDF failed to compile for issue #2032 with the following error: 

 Error reading bibliography ./paper.bib (line 5, column 10):
unexpected "\8220"
expecting space, letter, digit, "\"", "{", letter or digit, white space, "," or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by kyleniemeyer** [comment]
Hi @kthyng, do you have the bandwidth to edit this one?

**Comment by kthyng** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
Hi @activemargins! I'm doing a little investigating on my end and will be back to check in shortly. Thanks!

**Comment by ActiveMargins** [comment]
Hi @kthyng I would like to withdraw this submission. I'm sorry to waste your time. Some issues regarding this software and collaborators on another project has come up.

Sorry again. I know that editors are pretty maxed these days. 

All the best,
Danny.

**Comment by kthyng** [comment]
@ActiveMargins No worries, I will withdraw the submission.
