### ISSUE TITLE
[PRE REVIEW]: FASMA 2.0: A Python package for stellar parameters and chemical abundances

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2033]
**Submitting author:** @MariaTsantaki (<a href="http://orcid.org/0000-0002-0552-2313">Maria Tsantaki</a>)
**Repository:** <a href="https://github.com/MariaTsantaki/FASMA-synthesis" target ="_blank">https://github.com/MariaTsantaki/FASMA-synthesis</a>
**Version:** v2.0
**Editor:** @xuanxu
**Reviewers:** @warrickball, @ipelupessy
**Managing EiC:** Arfon Smith

**Author instructions**

Thanks for submitting your paper to JOSS @mtsantaki. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arfon.

@MariaTsantaki if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1051/0004-6361:200809724 is OK
- 10.1093/mnras/stx2564 is OK
- 10.1051/0004-6361/201527120 is OK
- 10.1137/0111030 is OK
- 10.1088/0031-8949/90/5/054005 is OK

MISSING DOIs

- https://doi.org/10.1086/152828 may be missing for title: Carbon and Nitrogen Abundances in Metal-Poor Stars.

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.41 s (283.8 files/s, 51072.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Fortran 77                      97           2223           1838          10520
Python                          12            589           1889           2837
R                                1             53              0            460
TeX                              2             53             18            297
Markdown                         2             39              0            113
YAML                             1              0              0            100
make                             1              1              0             16
Bourne Shell                     1              1              0              6
-------------------------------------------------------------------------------
SUM:                           117           2959           3745          14349
-------------------------------------------------------------------------------


Statistical information for the repository '2033' was gathered on 2020/01/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel T. Andreasen              5          7705           6488           47.93
DanielAndreasen                 19           453            543            3.36
Maria Tsantaki                   4             1            338            1.14
MariaTsantaki                   55          9304           4779           47.56

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Daniel T. Andreasen        1235           16.0          2.3                0.08
MariaTsantaki              4080           43.9         30.0               20.83
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02033/joss.02033/10.21105.joss.02033.pdf)

**Comment by labarba** [comment]
👋 @xuanxu — Could you handle this submission as editor? Thanks!

**Comment by DanielAndreasen** [comment]
Dear @xuanxu (or if another is going to be editor on this submission). First of all, thank you for your great work you do here.
In regard to the code, I would like to point out that MOOG (in `FASMA/MOOG`) is an external software. We have included it here (as similar software to FASMA has done too) for convenience of the end user.
Therefor I do not think that part requires much attention/review. Rather the python pipeline that is 
FASMA. I'm saying this since MOOG is quite comlicated and will take a long time to go through and understand.

Do you agree @MariaTsantaki?

**Comment by xuanxu** [comment]
@whedon assign @xuanxu as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by xuanxu** [comment]
@DanielAndreasen: about redistributing MOOG with FASMA: you are releasing FASMA under MIT so to avoid license conflicts I'd recommend to add MOOG's license file inside the `FASMA/MOOG` directory (I don't know what their license is) and mention somewhere you are just redistributing it without modifications.

**Comment by xuanxu** [comment]
@MariaTsantaki whedon suggest [this](https://ui.adsabs.harvard.edu/abs/1974ApJ...189..493S/abstract) as the article referenced by your `Carbon and Nitrogen Abundances in Metal-Poor Stars` entry in the paper.bib file. Is that it? Author and title are the same but publication year is different.

**Comment by MariaTsantaki** [comment]
> Dear @xuanxu (or if another is going to be editor on this submission). First of all, thank you for your great work you do here.
> In regard to the code, I would like to point out that MOOG (in `FASMA/MOOG`) is an external software. We have included it here (as similar software to FASMA has done too) for convenience of the end user.
> Therefor I do not think that part requires much attention/review. Rather the python pipeline that is
> FASMA. I'm saying this since MOOG is quite comlicated and will take a long time to go through and understand.
> 
> Do you agree @MariaTsantaki?

Yes Daniel. This is true. MOOG is an external code used as a black box here. The goal of FASMA is to use the output of MOOG and fit the data by the minimization process.

**Comment by MariaTsantaki** [comment]
> @MariaTsantaki whedon suggest [this](https://ui.adsabs.harvard.edu/abs/1974ApJ...189..493S/abstract) as the article referenced by your `Carbon and Nitrogen Abundances in Metal-Poor Stars` entry in the paper.bib file. Is that it? Author and title are the same but publication year is different.

Thanks! I was referring to the PhD thesis where the code was first presented but maybe the format of that reference is not valid for JOSS. I can change it to the reviewed journal reference.

**Comment by MariaTsantaki** [comment]
Latest commit [here](https://github.com/MariaTsantaki/FASMA-synthesis/commit/68b9267aa53a1e7023f84f59a4dad76f815cfe3b).

**Comment by MariaTsantaki** [comment]
I think that the labels set by @whedon can be misleading. I think we should stick to python instead of Fortran, R, DIGITAL Command Language.

**Comment by xuanxu** [comment]
:wave: @ipelupessy: would you be willing to review this paper? I think your knowledge of astronomy and Python makes you a great fit for this submission.

**Comment by xuanxu** [comment]
:wave: @warrickball would you be willing to review this paper? I think your expertise on stellar physics makes you a great fit for this submission.

**Comment by warrickball** [comment]
Hi @xuanxu, I'm happy to review this paper. Let me know how to proceed.

It isn't clear to me how the bundling of an external program happens in JOSS. FASMA appears to be a wrapper for the Fortran 77 code MOOG, presumably to make it easier to use. Though the [license file for MOOG in the repo](https://github.com/MariaTsantaki/FASMA-synthesis/blob/68b9267aa53a1e7023f84f59a4dad76f815cfe3b/FASMA/MOOG/license.txt) says "MOOG has public permission and free of charge", the [link](https://www.as.utexas.edu/~chris/moog.html) doesn't have an obvious (to me, anyway) license file or statement.

I assume this is a common problem that we might not solve now. Is there any precedent for this situation in JOSS (i.e. are there packages in JOSS that are wrappers to external codes)? Perhaps the repo should *not* bundle MOOG but rather give instructions on how to download and install it?

**Comment by ipelupessy** [comment]
@xuanxu: yes, though please let me know what you expect from me!

**Comment by xuanxu** [comment]
> I'm happy to review this paper. Let me know how to proceed.

Great, thanks @warrickball! Once I have the second reviewer confirmed I'll start a new issue where the actual review will take place. 

 > Though the [license file for MOOG in the repo](https://github.com/MariaTsantaki/FASMA-synthesis/blob/68b9267aa53a1e7023f84f59a4dad76f815cfe3b/FASMA/MOOG/license.txt) says "MOOG has public permission and free of charge", the [link](https://www.as.utexas.edu/~chris/moog.html) doesn't have an obvious (to me, anyway) license file or statement.
> 

You are right, this should be clarified during the review to make sure MOOG allows redistribution of the software.

> I assume this is a common problem that we might not solve now. Is there any precedent for this situation in JOSS (i.e. are there packages in JOSS that are wrappers to external codes)? 

Wrappers are common but in general the external codes are not included. 

>Perhaps the repo should _not_ bundle MOOG but rather give instructions on how to download and install it?

Yes, if redistribution is not allowed, this is the easiest solution.

**Comment by xuanxu** [comment]
@ipelupessy Great, thanks!

**Comment by xuanxu** [comment]
@ipelupessy @warrickball  I'm going to assign both of you as reviewers now and then start the review issue. There you'll find instructions and a checklist for each one of you.

**Comment by xuanxu** [comment]
@whedon add @warrickball as reviewer

**Comment by whedon** [comment]
OK, @warrickball is now a reviewer

**Comment by xuanxu** [comment]
@whedon add @ipelupessy as reviewer

**Comment by whedon** [comment]
OK, @ipelupessy is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2048.

**Comment by xuanxu** [comment]
@ipelupessy, @warrickball please head over to #2048 where the review will take place.
