### ISSUE TITLE
[PRE REVIEW]: Install and run programs, outside of R, inside of R 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2035]
**Submitting author:** @dombennett (<a href="http://orcid.org/0000-0003-2722-1359">Dominic Bennett</a>)
**Repository:** <a href="https://github.com/ropensci/outsider" target ="_blank">https://github.com/ropensci/outsider</a>
**Version:** v0.1.1
**Editor:** @arfon
**Reviewers:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @dombennett. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arfon.

@dombennett if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (794.1 files/s, 59096.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               30             57            360            995
Markdown                         7            158              0            443
JSON                             1              0              0            250
TeX                              1             20              0            176
YAML                             4             23             25            103
Rmd                              5            166            736             60
-------------------------------------------------------------------------------
SUM:                            48            424           1121           2027
-------------------------------------------------------------------------------


Statistical information for the repository '2035' was gathered on 2020/01/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Dom Bennett                      3             7             16            4.89
Dominic Bennett                  7           228            219           95.11

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2035 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/2035/paper/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
👋  @arfon — This package has been reviewed by rOpenSci: https://github.com/ropensci/software-review/issues/282, @ropensci/editors

**Comment by arfon** [comment]
@DomBennett - could you please merge this change to your paper to allow it to compile: https://github.com/ropensci/outsider/pull/15

Also, Pandoc gives me the following errors about your references when compiling:

```
pandoc-citeproc: reference docker_desktop not found
pandoc-citeproc: reference docker_toolbox not found
pandoc-citeproc: reference supersmart not found
```

**Comment by DomBennett** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02035/joss.02035/10.21105.joss.02035.pdf)

**Comment by DomBennett** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02035/joss.02035/10.21105.joss.02035.pdf)

**Comment by DomBennett** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02035/joss.02035/10.21105.joss.02035.pdf)

**Comment by DomBennett** [comment]
👋 @arfon 

Thanks for handling the submission! I've merged your changes and made a few changes of my own. I think it looks good now.

Let me know if there's anything else I should do.

**Comment by arfon** [comment]
@whedon add @arfon as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon add @arfon as reviewer

**Comment by whedon** [comment]
OK, @arfon is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2038. Feel free to close this issue now!

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1111/2041-210X.12263 is OK
- 10.1371/journal.pone.0089543 is OK
- 10.1093/bioinformatics/btl446 is OK
- 10.1371/journal.pcbi.1006650 is OK
- 10.1016/S0022-2836(05)80360-2 is OK
- 10.5281/zenodo.3615177 is OK
- 10.5281/zenodo.3615056 is OK
- 10.5281/zenodo.3615074 is OK
- 10.5281/zenodo.3614982 is OK
- 10.1093/nar/gki198 is OK

MISSING DOIs

- https://doi.org/10.1002/wics.1212 may be missing for title: The Comprehensive R Archive Network
- https://doi.org/10.21105/joss.02038 may be missing for title: outsider: Install and run programs, outside of R, inside of R
- https://doi.org/10.1007/978-1-4842-3936-0_2 may be missing for title: Docker

INVALID DOIs

- None
```
