### ISSUE TITLE
[PRE REVIEW]: osfr: An R Interface to the Open Science Framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2036]
**Submitting author:** @aaronwolen (<a href="http://orcid.org/0000-0003-2542-2202">Aaron R Wolen</a>)
**Repository:** <a href="https://github.com/ropensci/osfr" target ="_blank">https://github.com/ropensci/osfr</a>
**Version:** v0.2.7
**Editor:** @kthyng
**Reviewers:** @kthyng

**Author instructions**

Thanks for submitting your paper to JOSS @aaronwolen. **Currently, there isn't an JOSS editor assigned** to your paper.

@aaronwolen if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (772.0 files/s, 55134.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               60            636           1248           2323
Markdown                         6            118              0            375
YAML                             4             27              3            110
TeX                              1              8              0             83
Rmd                              3            112            191             51
-------------------------------------------------------------------------------
SUM:                            74            901           1442           2942
-------------------------------------------------------------------------------


Statistical information for the repository '2036' was gathered on 2020/01/22.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1371/journal.pcbi.1003285 is OK
- 10.1002/cpet.32 is OK
- 10.1371/journal.pcbi.1005510 is OK

MISSING DOIs

- https://doi.org/10.1186/1751-0473-8-7 may be missing for title: Git can facilitate greater reproducibility and increased transparency in science

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02036/joss.02036/10.21105.joss.02036.pdf)

**Comment by labarba** [comment]
👋 @trallard — Could you handle this JOSS submission as editor? Let us know! Thx.

**Comment by aaronwolen** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by aaronwolen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02036/joss.02036/10.21105.joss.02036.pdf)

**Comment by aaronwolen** [comment]
Thanks, @whedon. You rock.

This package has been reviewed by rOpenSci: https://github.com/ropensci/software-review/issues/279, @ropensci/editors

**Comment by trallard** [comment]
Sure assign this to me! I'll be happy to edit

**Comment by labarba** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by aaronwolen** [comment]
A few potential reviewers from the list that might be a good fit:
* benmarwick
* milesmcbain
* clauswilke

**Comment by trallard** [comment]
Hi all I am the editor for this submission, we are looking for at least 2 reviewers.

@benmarwick, Ben are you willing and able to review this submission?
@milesmcbain, Miles are you willing and able to review this submission?
@clauswilke, Claus are you willing and able to review this submission?

**Comment by clauswilke** [comment]
Sorry, no, I'm super busy the next few weeks and can't take this on at this time.

**Comment by maelle** [comment]
This package has been reviewed by rOpenSci over at https://github.com/ropensci/software-review/issues/279 so doesn't need any review? @trallard

**Comment by kthyng** [comment]
> This package has been reviewed by rOpenSci over at [ropensci/software-review#279](https://github.com/ropensci/software-review/issues/279) so doesn't need any review? @trallard

Hi @maelle! Ah, we must have missed that sorry. Just to verify: this submission has already been reviewed and accepted by rOpenSci?

**Comment by maelle** [comment]
Yes, it has been reviewed and accepted by rOpenSci indeed.

**Comment by kthyng** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
@whedon assign @kthyng as reviewer

**Comment by whedon** [comment]
OK, @kthyng is now a reviewer

**Comment by kthyng** [comment]
Another link to the [rOpenSci](https://github.com/ropensci/software-review/issues/279) review.

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2071.

**Comment by MilesMcBain** [comment]
Hi @trallard, Sorry I'm not familiar with this osf.io framework and do not have the bandwidth to immerse myself in it for a review at the moment.

There are some active R/rOpensci community members I know of in the communities listed here: https://osf.io/be7yt/wiki/home/ I am sure you could find someone suitable without much digging, e.g.: https://morn.netlify.com/about/

**Comment by kthyng** [comment]
@MilesMcBain and @benmarwick sorry for the confusion — this has already been reviewed through rOpenSci so no reviewers needed here. Thanks!
