### ISSUE TITLE
[PRE REVIEW]: RADWave: Python code for ocean surface wave analysis by satellite radar altimeter

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2039]
**Submitting author:** @CourtneySmith32 (<a href="http://orcid.org/0000-0002-9556-6626">Courtney Smith</a>)
**Repository:** <a href="https://github.com/pyReef-model/RADWave" target ="_blank">https://github.com/pyReef-model/RADWave</a>
**Version:** 0.02
**Editor:** @sjpfenninger
**Reviewers:** @bradyrx, @scivision

**Author instructions**

Thanks for submitting your paper to JOSS @CourtneySmith32. **Currently, there isn't an JOSS editor assigned** to your paper.

@CourtneySmith32 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.58 s (48.5 files/s, 333230.5 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                            7            304            436            809
Bourne Shell                      4             62             51            218
Jupyter Notebook                  4              0         189368            149
reStructuredText                  6            201            210            124
Markdown                          2             64              0            105
Dockerfile                        1             29             21             40
TeX                               1              3              0             18
make                              1              4              8              9
Bourne Again Shell                2              6              3              6
--------------------------------------------------------------------------------
SUM:                             28            673         190097           1478
--------------------------------------------------------------------------------


Statistical information for the repository '2039' was gathered on 2020/01/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Tristan                          5          1552              3          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Tristan                    1549           99.8          0.0               12.07
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/J.RSE.2018.06.006 is OK
- 10.1038/s41597-019-0083-9 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02039/joss.02039/10.21105.joss.02039.pdf)

**Comment by labarba** [comment]
👋  @sjpfenninger — Could you handle this JOSS submission as editor?
(The subject area fits more closely with @kthyng, but she is editing 4 submissions right now.) 
Have a look, and let me know.

**Comment by sjpfenninger** [comment]
@labarba Can do.

**Comment by labarba** [comment]
@whedon assign @sjpfenninger as editor

**Comment by whedon** [comment]
OK, the editor is @sjpfenninger

**Comment by sjpfenninger** [comment]
@whedon add @bradyrx as reviewer

**Comment by whedon** [comment]
OK, @bradyrx is now a reviewer

**Comment by sjpfenninger** [comment]
@whedon add @scivision as reviewer

**Comment by whedon** [comment]
OK, @scivision is now a reviewer

**Comment by sjpfenninger** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2083.

**Comment by sjpfenninger** [comment]
@bradyrx and @scivision, thanks for agreeing to review! Head over to the review issue #2083 for the review process. Let me know if you have any questions!

**Comment by scivision** [comment]
@whendon start review

**Comment by scivision** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @scivision, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by kthyng** [comment]
Hi @scivision, the review is happening at: https://github.com/openjournals/joss-reviews/issues/2083
