### ISSUE TITLE
[REVIEW]: Weave.jl: Scientific Reports Using Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#204]
**Submitting author:** @mpastell (<a href="http://orcid.org/0000-0002-5810-4801">Matti Pastell</a>)
**Repository:** <a href="https://github.com/mpastell/weave.jl" target ="_blank">https://github.com/mpastell/weave.jl</a>
**Version:** v0.4.1
**Editor:** @arfon
**Reviewer:** @vchuravy
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.398871" target="_blank">10.5281/zenodo.398871</a>

## Status

[![status](http://joss.theoj.org/papers/bf6de6f2bf94f31924fdcfa48b92434e/status.svg)](http://joss.theoj.org/papers/bf6de6f2bf94f31924fdcfa48b92434e)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/bf6de6f2bf94f31924fdcfa48b92434e"><img src="http://joss.theoj.org/papers/bf6de6f2bf94f31924fdcfa48b92434e/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/bf6de6f2bf94f31924fdcfa48b92434e/status.svg)](http://joss.theoj.org/papers/bf6de6f2bf94f31924fdcfa48b92434e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mpastell/weave.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mpastell/weave.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.4.0)?
- [x] **Authorship:** Has the submitting author (@mpastell) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @vchuravy it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by vchuravy** [comment]
@arfon How would I update the version number of the package for submission? I am nearly done with my review, but I think a point or minor release would be good to give a smooth user experience.

**Comment by vchuravy** [comment]
Also didn't we used to generate a preview of the PDF?

**Comment by arfon** [comment]
> @arfon How would I update the version number of the package for submission? I am nearly done with my review, but I think a point or minor release would be good to give a smooth user experience.

@vchuravy - I can do this. What's the new release number?

> Also didn't we used to generate a preview of the PDF?

Yeah, I usually do this at the end of the review during processing now. We plan to automate this in the future.

**Comment by vchuravy** [comment]
The new version is v0.4.1.

**Comment by arfon** [comment]
@vchuravy - here's the compiled paper PDF for your review [10.21105.joss.00204.pdf](https://github.com/openjournals/joss-reviews/files/844291/10.21105.joss.00204.pdf)

**Comment by vchuravy** [comment]
Nice! @mpastell updated one citation and I think we are good to go here :+1:

**Comment by vchuravy** [comment]
@arfon anything else left to do?

**Comment by arfon** [comment]
@vchuravy - if this is all good then it's over to myself and @mpastell to wrap this up.

@mpastell - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by mpastell** [comment]
@vchuravy Many thanks for the review!

@arfon The software is archived in Zenodo: 10.5281/zenodo.398871

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.398871 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.398871" target="_blank">10.5281/zenodo.398871</a> is the archive.

**Comment by arfon** [comment]
@vchuravy many thanks for your rapid review here ✨ 

@mpastell - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00204 ⚡️ 🚀 💥
