### ISSUE TITLE
[PRE REVIEW]: hypr: An R package for hypothesis-driven contrast coding

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2041]
**Submitting author:** @mmrabe (<a href="http://orcid.org/0000-0002-2556-5644">Maximilian Rabe</a>)
**Repository:** <a href="https://github.com/mmrabe/hypr" target ="_blank">https://github.com/mmrabe/hypr</a>
**Version:** v0.1.6
**Editor:** @marcosvital
**Reviewers:** @tomfaulkenberry , @JonathanReardon

**Author instructions**

Thanks for submitting your paper to JOSS @mmrabe. **Currently, there isn't an JOSS editor assigned** to your paper.

@mmrabe if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (408.1 files/s, 70192.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                2             67            356            620
Markdown                         4            113              0            330
Rmd                              5            154            314             94
TeX                              1              1              0             15
-------------------------------------------------------------------------------
SUM:                            12            335            670           1059
-------------------------------------------------------------------------------


Statistical information for the repository '2041' was gathered on 2020/01/26.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.jml.2019.104038 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02041/joss.02041/10.21105.joss.02041.pdf)

**Comment by labarba** [comment]
👋 @marcosvital — Could you handle this JOSS submission as editor? Let me know!

**Comment by marcosvital** [comment]
Hi, @labarba !

Yes, I'll be happy to handle this submission.

**Comment by marcosvital** [comment]
@whedon assign @marcosvital as editor

**Comment by whedon** [comment]
OK, the editor is @marcosvital

**Comment by marcosvital** [comment]
Hi, @mmrabe, I'm Marcos Vital, and I'll be the editor of your submission.

Did you had the chance to check the article proof generated above? If everything seems to be ok with it, we can move on to assigning reviewers for you submission. We usually ask the authors for suggestions, so let me know if you have anyone in mind that could do this.

You can also check [this list of people](https://bit.ly/joss-reviewers) that have agreed to review for JOSS, and see if any of them may be suitable to review this submission.

And let me know if you need any help finding reviewers if you don't have anyone in mind.

**Comment by mmrabe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02041/joss.02041/10.21105.joss.02041.pdf)

**Comment by mmrabe** [comment]
Hi @marcosvital,

Thanks a lot for handling this submission. The paper proof looked fine except for two minor issues in the bibliography, which I just fixed.

I have browsed the list of potential reviewers and would like to suggest the following (in no particular order):

- tomfaulkenberry
- MikeLydeamore
- njtierney
- rmhogervorst
- JonathanReardon
- lindemann09
- janfreyberg

Best regards,
Max

**Comment by marcosvital** [comment]
Hi, @mmrabe! Thank you for pointing potential reviewers. I'll start contacting them, and we will move to review phase soon.

Dear @tomfaulkenberry, @MikeLydeamore and @njtierney

Would you be willing to review this submission for JOSS?
If you are still new to this, we carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is still a pre-review, and once there are enough reviewers, we will move on to a new issue where the review will take place.

**Comment by tomfaulkenberry** [comment]
sure, I'd love to review.  Feel free to assign it to me.

Tom

**Comment by marcosvital** [comment]
Thank you, @tomfaulkenberry! I'll wait for us to have one or two more reviewers, and we will move on to the reviewing phase.

@mmrabe , since I didn't hear from two of the potential reviewers, I'll try to reach a few more, and we will hopefully be able to start the reviewing process.

**Comment by marcosvital** [comment]
Dear @rmhogervorst and @JonathanReardon

Would you be willing to review this submission for JOSS?
If you are still new to this, we carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is still a pre-review, and once there are enough reviewers, we will move on to a new issue where the review will take place.

**Comment by JonathanReardon** [comment]
Hi, yes happy to review this! please sign me up for this one

Jon

**Comment by marcosvital** [comment]
Thank you, @JonathanReardon!
I'll soon start the reviewing process with you and @tomfaulkenberry. 

@mmrabe , this topic will be closed soon, by the time the new one is created for review. I will still try to contact one additional reviewer, but it's ok to move one with just two.

**Comment by marcosvital** [comment]
@whedon assign @tomfaulkenberry  as reviewer

**Comment by whedon** [comment]
OK, @tomfaulkenberry  is now a reviewer

**Comment by marcosvital** [comment]
@whedon add @JonathanReardon as reviewer

**Comment by whedon** [comment]
OK, @JonathanReardon is now a reviewer

**Comment by marcosvital** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2134.
