### ISSUE TITLE
[REVIEW]: SeisModels.jl: A Julia package for models of the Earth's interior

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2043]
**Submitting author:** @anowacki (<a href="http://orcid.org/0000-0001-7669-7383">Andy Nowacki</a>)
**Repository:** <a href="https://github.com/anowacki/SeisModels.jl" target ="_blank">https://github.com/anowacki/SeisModels.jl</a>
**Version:** v1.1.0
**Editor:** @kbarnhart
**Reviewers:** @daniellivingston, @joa-quim
**Archive:** <a href="https://doi.org/10.6084/m9.figshare.11993313" target="_blank">10.6084/m9.figshare.11993313</a>

## Status

[![status](https://joss.theoj.org/papers/c2155dd354c1a0a6097003ce2b2b11fe/status.svg)](https://joss.theoj.org/papers/c2155dd354c1a0a6097003ce2b2b11fe)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c2155dd354c1a0a6097003ce2b2b11fe"><img src="https://joss.theoj.org/papers/c2155dd354c1a0a6097003ce2b2b11fe/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c2155dd354c1a0a6097003ce2b2b11fe/status.svg)](https://joss.theoj.org/papers/c2155dd354c1a0a6097003ce2b2b11fe)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/anowacki/SeisModels.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@daniellivingston, @fhorrobin, & @joa-quim please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kbarnhart know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/anowacki/SeisModels.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@anowacki) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/anowacki/SeisModels.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@anowacki) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/anowacki/SeisModels.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@anowacki) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @daniellivingston, @fhorrobin it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1111/j.1365-246X.1995.tb03540.x is OK
- 10.1111/j.1365-246X.1991.tb06724.x is OK
- 10.1016/0031-9201(81)90046-7 is OK
- 10.1126/science.1199375 is OK
- 10.1785/gssrl.70.2.154 is OK
- 10.1785/gssrl.81.3.530 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02043/joss.02043/10.21105.joss.02043.pdf)

**Comment by kbarnhart** [comment]
:wave: @anowacki, @daniellivingston, @fhorrobin this is the review thread for the paper. All of our communications will happen here from now on.

All reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `https://github.com/openjournals/joss-reviews/issues/2043` so that a link is created to this thread. This helps create a record of the changes in the repository associated with this review. It also helps me keep track of open/closed issues that remain. 

Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@kbarnhart) if you have any questions/concerns.

**Comment by daniellivingston** [comment]
@anowacki Great package. Does what it claims and does it very well and very elegantly. A minor nitpick and probably a personal taste issue; feel free to ignore.

You write that "[d]ocumentation is available at a dedicated website" without explicitly spelling out the URL. I understand the URL is relatively long (https://anowacki.github.io/SeisModels.jl/stable/), and that embedded hyperlinks mean that spelling out the full address is redundant, but I would still like to see the full path in the document. However, this is a minor thing and perhaps up to personal taste, so I will approve this paper regardless. Just something to think about.

**Comment by daniellivingston** [comment]
Also, in the documentation (https://anowacki.github.io/SeisModels.jl/stable/#How-to-install-1), one finds this:

> ### How to install
> SeisModels.jl can be added to your Julia environment like so:
> 
> ```
> julia> import Pkg; pkg"add https://github.com/anowacki/SeisModels.jl"
> ```

This should be changed to match your repo README:

> SeisModels.jl can be added to your Julia install like so:
> 
> ```
> julia> import Pkg; Pkg.add("SeisModels")
> ```

**Comment by daniellivingston** [comment]
One of the review guidelines states:

>  Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Insofar as I can tell, discussions of third-party contributions are limited to this line in your README:

> Currently, only three kinds of one-dimensional models are supported, but all model parameterisations and models are acceptable for inclusion. Contributions are welcome.

You may want to add a CONTRIBUTION.md document to the repo root, or just a small paragraph in the README expanding on your contribution process. You can find an over-the-top example of this here: https://reactjs.org/docs/how-to-contribute.html

**Comment by anowacki** [comment]
I have set up a branch [joss-review](https://github.com/anowacki/SeisModels.jl/tree/joss-review) in which I propose to make the changes before merging them in finally.

@daniellivingston—thank you very much for these helpful suggestions.

### Docs website URL
> You write that "[d]ocumentation is available at a dedicated website" without explicitly spelling out the URL. […]  I would still like to see the full path in the document.

I'm very happy to go along with this and I have updated the manuscript accordingly.

### Contribution guidelines
> You may want to add a CONTRIBUTION.md document to the repo root, or just a small paragraph in the README expanding on your contribution process.

Thank you for helping me realise this—I had not quite understood the guidelines here, but do now on re-reading them.

I have added a CONTRIBUTING.md file (this filename seems much more common, at least on GirHub and Gitlab repos) to the repo root which hopefully explains things in appropriate detail.

### Docs installation instructions
> This should be changed to match your repo README:

Thank you for spotting this.  I did update the docs a little while ago (in [3c9826ac](https://github.com/anowacki/SeisModels.jl/commit/3c9826acc03a38ec86e1a4a932031db7f135e7ed)), but it transpires that the docs stopped building after an [earlier commit](https://github.com/anowacki/SeisModels.jl/commit/dbb5530e523eb890226c5e221a41b4fe135397fb).  I can see that a number of new functions are in fact missing.  I will have to investigate this further to work out what has happened.

**Comment by anowacki** [comment]
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02043/joss.02043/10.21105.joss.02043.pdf)

**Comment by anowacki** [comment]
> ### Docs installation instructions
>> This should be changed to match your repo README:
>
> Thank you for spotting this. I did update the docs a little while ago (in 3c9826ac), but it transpires that the docs stopped building after an earlier commit. I can see that a number of new functions are in fact missing. I will have to investigate this further to work out what has happened.

Docs are now [back up](https://anowacki.github.io/SeisModels.jl/dev/).  (The issue was [with Travis configuration](https://github.com/anowacki/SeisModels.jl/commit/f788c51a60c00000e422b2d53bc58925085cd744).)

**Comment by kbarnhart** [comment]
Thanks to @daniellivingston for completing your review and for @anowacki for addressing the raised issues. 🎉  

@fhorrobin and @joa-quim please work to complete your reviews in the next week or so (or provide a time estimate here). 

Thanks all for participating in the JOSS review process.

**Comment by joa-quim** [comment]
Hi @kbarnhart, any particular action that I take in order to be able to start checking my boxes? Tried but apparently I have no permission to do so.

**Comment by kbarnhart** [comment]
@whedon add @joa-quim  as reviewer

**Comment by whedon** [comment]
OK, @joa-quim  is now a reviewer

**Comment by kbarnhart** [comment]
@joa-quim try now.

**Comment by joa-quim** [comment]
Sorry, not yet. To be clear, I should be able to check the boxes at the beginning of this page, right?

**Comment by kbarnhart** [comment]
Yup. You should be able to check the checkboxes under "Review checklist for @joa-quim". I'm not entirely certain how to fix this, so I'm tagging @arfon who should be able to provide guidance.

**Comment by joa-quim** [comment]
Thanks. And I'll complete the review this week (I've already installed the package and run some examples).

**Comment by kbarnhart** [comment]
@joa-quim I wanted to check in and see if you were able to check the boxes or if they are still not editable for you.

**Comment by joa-quim** [comment]
Nope, still blocked to me. And what about you @fhorrobin, can you check them?

**Comment by kbarnhart** [comment]
@arfon can you see anything about this issue that explains why @joa-quim can't check the boxes? I used whedon to assign him and he is now listed under assigned people. Thanks!

**Comment by daniellivingston** [comment]
@joa-quim If you want, you can make a comment with the above checklist and mark off what you've done. Since I have editing permissions on that comment, I can edit the check boxes as a proxy for you.

**Comment by joa-quim** [comment]
Ok, I'll try to do that tomorrow afternoon/night.

**Comment by arfon** [comment]
@joa-quim - you need to accept the invite to the repository here: https://github.com/openjournals/joss-reviews/invitations  to be able to edit the check boxes (it should be at the top of the page). When you click the 'accept', please make sure you're logged in with your @joa-quim account.

**Comment by joa-quim** [comment]
Hmm, something strange is still on. When I try to accept the invitation I get a 
```Ooops 500. Looks like something went wrong!```
 error from Github.

Anyway, my comment on this paper is that it is elegantly written and does what it describes,

I would only suggest that the installing instructions be changed to the shorter (and working)

```
]add SeisModels
```
instead of the longer version on the Github page
```
import Pkg; Pkg.add("SeisModels")
```
or the even longer in the documentation
```
import Pkg; pkg"add https://github.com/anowacki/SeisModels.jl"
```


Given that I'm still not able to check the boxes above, I reproduced the check boxes list bellow with the corresponding checks. Hope this is good enough as a workaround.


# --------------------


- Conflict of interest

- [x] I confirm that I have read the JOSS conflict of interest (COI) policy and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

- Code of Conduct

- [x] I confirm that I read and will adhere to the JOSS code of conduct.

- General checks

- [x] **Repository:** Is the source code for this software available at the repository url?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?
- [x] **Contribution and authorship:** Has the submitting author (@anowacki) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

- Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

- Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?

- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

- Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?

**Comment by kbarnhart** [comment]
Thanks for your review @joa-quim! Sorry about the issues with check box permissions. I think your workaround is just fine. 

I'll let @anowacki consider/address the small change you recommend in the main repository. 

@fhorrobin would it be possible to get an update on when you expect to complete your review?

**Comment by anowacki** [comment]
Thanks, @joa-quim for the comments!

> I would only suggest that the installing instructions be changed to the shorter (and working)
>     ```]add SeisModels```
> instead of the longer version on the Github page
>     ```import Pkg; Pkg.add("SeisModels")```

My motivation for the latter command is that new Julia users can simply copy and paste the full command into a fresh REPL session without needing to worry about `pkg` mode, but I'd be happy to change this is you feel it is definitely less friendly.

> or the even longer in the documentation
>     ```import Pkg; pkg"add https://github.com/anowacki/SeisModels.jl"```

When the package wasn't registered, this was needed, but no longer as I'm sure you realise.  This part of the docs is a leftover from before [I realised the docs weren't updating](https://github.com/openjournals/joss-reviews/issues/2043#issuecomment-585993988) and the [latest docs](https://anowacki.github.io/SeisModels.jl/dev/) do not add using the GirHub URL.

**Comment by joa-quim** [comment]
@anowacki This was just my opinion on what looks more friendly to new users. More experimented users should know that already. But notice that one can do a copy past of ``]add SeisModels`` string into a fresh REPL and it works fine. I mean, the REPL passes automatically into the *pkg* mode.

**Comment by anowacki** [comment]
> But notice that one can do a copy past of `]add SeisModels` string into a fresh REPL and it works fine. I mean, the REPL passes automatically into the _pkg_ mode.

This doesn't actually work for me.

**Comment by joa-quim** [comment]
!! I'm on Windows and I was assuming that it would work in other OSs as well.
Anyway, this is minor point. Do as you feel is better.

**Comment by anowacki** [comment]
Thanks for you suggestion, @joa-quim—just for the avoidance of doubt in the review process, I'm stating that I have decided to keep the docs as they are in this regard.

**Comment by kbarnhart** [comment]
@anowacki Thanks for noting your response @joa-quim's comment here for posterity. 

@fhorrobin would it be possible to get an update on when you expect to complete your review?

@joa-quim and @daniellivingston thank you for completing your reviews. 

A quick additional note. I accidentally turned on the JOSS out of office responder and have not figured out how to turn it off... So if you @ me, you will see an auto response that says I'm away until March 20th. This is not true, I'm not away... 😄

**Comment by kbarnhart** [comment]
Thanks to @daniellivingston and @joa-quim for completing your reviews. 

@fhorrobin a friendly reminder to provide an update on when you expect to complete your review?  If I don't hear back in the next day or two, I will likely decide to move forward with the review process (as JOSS only requires two reviews).

**Comment by kbarnhart** [comment]
I'm going to move this review forward.

Now that the two reviews have been completed, @daniellivingston and @joa-quim could you please reply and confirm your review recommendation. 

At that point @anowacki could you please point me towards the current version of the paper (it is currently on a branch I think). I will provide some final, likely minor, editorial comments on the paper.

Once those are merged into the main repository branch, we will move to the final stages of the JOSS process (double checking reference DOIs, final paper compilation, setting archive, and version). @anowacki I'll ping you for what I need when we get there. 

@fhorrobin thanks for being willing to undertake a review. It seems like things didn't work out with your schedule, no worries. I hope you'll consider being part of a JOSS review in the future. I'm going to remove you from this review now. Feel free to follow up with me here or via email if you'd like.

**Comment by kbarnhart** [comment]
@whedon remove @fhorrobin as reviewer

**Comment by whedon** [comment]
OK, @fhorrobin is no longer a reviewer

**Comment by joa-quim** [comment]
Hi,
Yes, I confirm my recommendation for accepting this paper.

**Comment by kbarnhart** [comment]
@daniellivingston can I ping you to confirm your recommendation for this publication.

**Comment by daniellivingston** [comment]
@kbarnhart Yes, I confirm my recommendation for accepting this publication.

**Comment by kbarnhart** [comment]
Thanks @daniellivingston

**Comment by kbarnhart** [comment]
@whedon generate pdf from branch joss-review

@anowacki is this the most up to date version of the publication? I may have a couple of minor editorial comments on the paper---just want to make sure I'm looking at the right thing.

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-review
. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2043 with the following error: 

 error: pathspec 'joss-review
' did not match any file(s) known to git.
error: pathspec 'joss-review
' did not match any file(s) known to git.
pandoc-citeproc: reference joa-quim not found
Error producing PDF.
! TeX capacity exceeded, sorry [input stack size=5000].
\reserved@a ->\def \reserved@a 
                               *{\let \@xs@assign \@xs@expand@and@detokenize...
l.330 }

Looks like we failed to compile the PDF

**Comment by kbarnhart** [comment]
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2043 with the following error: 

 pandoc-citeproc: reference joa-quim not found
Error producing PDF.
! TeX capacity exceeded, sorry [input stack size=5000].
\reserved@a ->\def \reserved@a 
                               *{\let \@xs@assign \@xs@expand@and@detokenize...
l.330 }

Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02043/joss.02043/10.21105.joss.02043.pdf)

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by anowacki** [comment]
> @anowacki is this the most up to date version of the publication? I may have a couple of minor editorial comments on the paper---just want to make sure I'm looking at the right thing.

Hi @kbarnhart—yes, this version is the current one, so please do let me know of any comments you have, the current situation permitting of course.

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by kbarnhart** [comment]
@whedon check references

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02043/joss.02043/10.21105.joss.02043.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1111/j.1365-246X.1995.tb03540.x is OK
- 10.1111/j.1365-246X.1991.tb06724.x is OK
- 10.1016/0031-9201(81)90046-7 is OK
- 10.1126/science.1199375 is OK
- 10.1785/gssrl.70.2.154 is OK
- 10.1785/gssrl.81.3.530 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kbarnhart** [comment]
@anowacki I only have a couple of comments. They are meant to improve readability and accessibility for a non-specialist audience.

- [ ] In paragraph 2: Define abbreviations: I think this only means writing out PREM as Preliminary Reference Earth Model. If you are aware of better written out names of the other Earth models, I'd recommend using them, but I suspect they will stay as AK135 and iasp91. I think P-wave and S-wave can stay as is. 

- [ ] In paragraph 4: "appropriate formats" is rather unspecific. Could you revise to state which formats are supported.  

Once these changes are in the paper, please do the following:

- [ ] Make a tagged release of your software
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g. figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata (title and author list exactly the same as on the JOSS paper). 
- [ ] Comment here with:
    - The version tag of the archived version
    - the DOI of the archived version

I with then move forward with accepting the submission (I will do some final metadata updating and then pass the submission on to the managing editor in chief who will handle final acceptance and publication).

**Comment by anowacki** [comment]
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02043/joss.02043/10.21105.joss.02043.pdf)

**Comment by anowacki** [comment]
@kbarnhart I have archived v1.1.0 of SeisModels.jl at Figshare with doi 10.6084/m9.figshare.11993313.

**Comment by kbarnhart** [comment]
@whedon set 10.6084/m9.figshare.11993313 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.6084/m9.figshare.11993313" target="_blank">10.6084/m9.figshare.11993313</a> is the archive.

**Comment by kbarnhart** [comment]
@whedon set v1.1.0 as version

**Comment by whedon** [comment]
OK. v1.1.0 is the version.

**Comment by kbarnhart** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1111/j.1365-246X.1995.tb03540.x is OK
- 10.1111/j.1365-246X.1991.tb06724.x is OK
- 10.1016/0031-9201(81)90046-7 is OK
- 10.1126/science.1199375 is OK
- 10.1785/gssrl.70.2.154 is OK
- 10.1785/gssrl.81.3.530 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published

. Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1371

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1371, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kbarnhart** [comment]
Nice work @anowacki! Thanks to @daniellivingston and @joa-quim for your reviews. 

I've now recommended that this be accepted and handed it off to the JOSS Editors in Chief who handle final processing.

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1239920238424199169) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1372
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02043](https://doi.org/10.21105/joss.02043)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by anowacki** [comment]
Thanks once again, @kbarnhart, @daniellivingston and @joa-quim.  The process has been a great pleasure.

**Comment by arfon** [comment]
@daniellivingston, @joa-quim - many thanks for your reviews and to @kbarnhart for editing this submission ✨ 

@anowacki - your paper is now published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02043/status.svg)](https://doi.org/10.21105/joss.02043)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02043">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02043/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02043/status.svg
   :target: https://doi.org/10.21105/joss.02043
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02043/status.svg)](https://doi.org/10.21105/joss.02043)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
