### ISSUE TITLE
[REVIEW]: NEEP: null empirically estimated p-values for high-throughput molecular survival analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2044]
**Submitting author:** @scwest (<a href="http://orcid.org/0000-0002-1394-1999">Sean West</a>)
**Repository:** <a href="https://github.com/thecodingdoc/neep/" target ="_blank">https://github.com/thecodingdoc/neep/</a>
**Version:** 1
**Editor:** @majensen
**Reviewers:** @SiminaB, @majensen
**Archive:** <a href="https://doi.org/10.5281/zenodo.3996816" target="_blank">10.5281/zenodo.3996816</a>

## Status

[![status](https://joss.theoj.org/papers/e665412c4fecaa72ad20a9533315efd9/status.svg)](https://joss.theoj.org/papers/e665412c4fecaa72ad20a9533315efd9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e665412c4fecaa72ad20a9533315efd9"><img src="https://joss.theoj.org/papers/e665412c4fecaa72ad20a9533315efd9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e665412c4fecaa72ad20a9533315efd9/status.svg)](https://joss.theoj.org/papers/e665412c4fecaa72ad20a9533315efd9)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/thecodingdoc/neep/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@majensen & @SiminaB, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @majensen know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/thecodingdoc/neep/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@scwest) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/thecodingdoc/neep/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@scwest) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @wrathematics, @SiminaB, @rhagenson it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1371/journal.pone.0140072 may be missing for title: Robust selection algorithm (RSA) for multi-omic biomarker discovery; integration with functional network analysis to identify miRNA regulated pathways in multiple cancers
- https://doi.org/10.2307/2532740 may be missing for title: Maximally selected rank statistics

INVALID DOIs

- https://doi.org/10.1371/journal.pcbi.1007469 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02044/joss.02044/10.21105.joss.02044.pdf)

**Comment by rhagenson** [comment]
@majensen, after reading the conflict of interest statement and reviewing the authors of this paper I have notable conflict of interest as the last author on this paper (Dario Ghersi) is my MS thesis advisor from three years ago -- which I did not notice prior to accepting the offer to review. If you will allow me, I still would like to read the work and offer my help to its authors in the form of opening issues/PRs for necessary fixes prior to acceptance, however I do not believe my opinion can be impartially applied toward the final decision to accept/reject this work.

**Comment by majensen** [comment]
Thanks @rhagenson - I appreciate your raising this issue. I myself would definitely find it very helpful if you are willing to assist and even comment in the review. Since we have 2 other reviewers, JOSS guidelines are met. Onward!

**Comment by rhagenson** [comment]
@majensen, thank you for your understanding. To ensure I, as a commenter, am not stalling the review process I will try to get the bulk of the work done in the next few days.

Not sure if I have proper permissions to run this whedon command, but we will find out!

@whedon remove @rhagenson as reviewer

**Comment by majensen** [comment]
@whedon remove @rhagenson as reviewer

**Comment by whedon** [comment]
OK, @rhagenson is no longer a reviewer

**Comment by rhagenson** [comment]
@scwest, I opened an issue with all the edits I see as necessary, in addition to suggested edits that I think improve quality-of-life for either yourself as maintainer or others as users.

**Comment by scwest** [comment]
I have updated the repository with the edit suggestions from @rhagenson. The Makefile and unused variable suggestions from @wrathematics have also been added.

**Comment by majensen** [comment]
@SiminaB - how are things progressing? Let me know if I can help.

**Comment by majensen** [comment]
I've heard elsewhere from Simina; she has been delayed but will turn attention to the review soon.

**Comment by SiminaB** [comment]
Apologies for the delay! My initial review is at https://github.com/thecodingdoc/neep/issues/5. I think the paper needs some additional clarifications and details. I also made some suggestions for the README file and some other aspects.

**Comment by majensen** [comment]
Thanks @SiminaB!

**Comment by majensen** [comment]
@scwest how is it coming regarding thecodingdoc/neep#5?

@wrathematics -- how is your review coming along? 
thanks

**Comment by majensen** [comment]
@scwest can you provide an update on progress? Thank you.

**Comment by majensen** [comment]
I've reached out to @scwest via an alternate channel for an update.

**Comment by majensen** [comment]
All - I've heard from @scwest, he has been swamped. We should hear from him within about 2 weeks. Thanks!

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by majensen** [comment]
@scwest - how's it going?

**Comment by scwest** [comment]
Hi Mark,

As you might be experiencing yourself, the additional responsibilities
offered by the current COVID-19 pandemic are immediate and pressing.
Specifically as a biomedical researcher, we have lots to do. I should have
reached out earlier, but is it ok if we put this review on hold. Thank you
for your work, I'll be returning to this ASAP. But that looks like it may
be farther out than anticipated.

Sean

**Comment by majensen** [comment]
@scwest no problem at all -- I will add the "Paused" tag. Thanks a lot for the response!

**Comment by majensen** [comment]
@whedon remind @majensen in 2 weeks

**Comment by whedon** [comment]
Reminder set for @majensen in 2 weeks

**Comment by arfon** [comment]
@majensen looks like Whedon didn't remind you here either.

**Comment by majensen** [comment]
Hi @scwest , checking in with you to see how are things?

**Comment by scwest** [comment]
I'm ready to unpause this. I'll submit a response to the previous review
within a couple of days.

Sean

**Comment by scwest** [comment]
Hi Mark,

I've submitted a full response to the review #3 (Issue #5). Thank you for
your patience!

Sean

**Comment by SiminaB** [comment]
Thank you! Hope to take a look at it soon!

**Comment by majensen** [comment]
Hi @SiminaB - just checking in on whether you've had opportunity to take a look at the latest version.
@wrathematics -- are you still able to provide a review? 
I really appreciate the efforts of you both.

**Comment by SiminaB** [comment]
Alright, I just added my re-review at https://github.com/thecodingdoc/neep/issues/5. I think there are still just a few outstanding issues, but it's much improved!

**Comment by majensen** [comment]
@wrathematics - please let me know if you are unable to review at this time. No harm done if so. thanks --@majensen

**Comment by majensen** [comment]
I believe @wrathematics is no longer participating.
I will take on the review @scwest so we can finally move this along-- this is unusual, but not unheard-of. If you have any qualms about this @scwest, just let me know.

**Comment by majensen** [comment]
@whedon add @majensen as reviewer

**Comment by whedon** [comment]
OK, @majensen is now a reviewer

**Comment by majensen** [comment]
@whedon remove @wrathematics as reviewer

**Comment by whedon** [comment]
OK, @wrathematics is no longer a reviewer

**Comment by scwest** [comment]
I have posted an updated response for the new comments made by  @SiminaB
<https://github.com/SiminaB>. They are posted in thecodingdoc/neep#5
<https://github.com/thecodingdoc/neep/issues/5>.

Sean

**Comment by majensen** [comment]
@whedon remind @majensen in 5 days

**Comment by whedon** [comment]
Reminder set for @majensen in 5 days

**Comment by whedon** [comment]
:wave: @majensen, please update us on how your review is going.

**Comment by majensen** [comment]
@scwest - re Installation. Need to remove the object files (.o) and the executable (neep) from the repo. Two things: (1) if they are present, then `make` thinks the software is built and doesn't do anything, and (2) they're architecture-dependent and will be useless to many users anyway. Also, please link out to https://www.openmp.org/resources/openmp-compilers-tools/ when mentioning OpenMP as a requirement. I think it would be better to explicitly say "you need a C compiler that complies with OpenMP." Otherwise, it sounds like a library one requires. I will probably help with a PR for your Makefile.

**Comment by majensen** [comment]
@scwest - re https://github.com/openjournals/joss-reviews/issues/2044#issuecomment-657073238, I will fork the repo and make a PR with some suggested changes.

**Comment by SiminaB** [comment]
I haven't had the chance to look at this again, but hope to really soon! Had some internet problems for much of the week.

**Comment by SiminaB** [comment]
Alright, just looked over it again - Looks good! All the boxes are now checked for my review.

**Comment by majensen** [comment]
Hi @scwest - I believe we are in the home stretch. Please review the PR at thecodingdoc/neep#6. I will be looking over the paper itself. thanks!

**Comment by majensen** [comment]
@scwest - I am proposing https://github.com/thecodingdoc/neep/pull/7 with some editorial changes. 
If you merge both https://github.com/thecodingdoc/neep/pull/6 and https://github.com/thecodingdoc/neep/pull/7, my review will be complete and we can move ahead towards recommendation for acceptance. 
thanks

**Comment by majensen** [comment]
@scwest Can you ping here? Thanks.

**Comment by scwest** [comment]
Yes! Sorry. Expect an update this week.

**Comment by scwest** [comment]
Thank you Mark for those changes! You really made my life super easy here. I've tested the current master to ensure that it is working and installs correctly on my end. I have generated a new release.

**Comment by majensen** [comment]
Hey @scwest - I felt that (1) this work has been in the hopper a long time, (2) if I am a reviewer I should do something, and (3) it was fun and not onerous. I have checked off the remaining items and so both @SiminaB and I now recommend acceptance. 

To move forward, can you create a public archive of the latest version of the master branch in a service such as [Zenodo](https://zenodo.org)? Here is a [simple tutorial](https://github.com/openjournals/joss-reviews/issues/1839#issuecomment-560048729) from a previous review.

Once you have done this, can you report back here:
* the new archive's DOI
* the new archive's version number

thanks!

**Comment by scwest** [comment]
Thanks @majensen - I will do so over this weekend and report back.

**Comment by scwest** [comment]
Here are the requested numbers:

10.5281/zenodo.3996816
Version 1

Thanks for the tutorial!

**Comment by majensen** [comment]
@whedon set 10.5281/zenodo.3996816 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3996816" target="_blank">10.5281/zenodo.3996816</a> is the archive.

**Comment by majensen** [comment]
@whedon set version as 1

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by majensen** [comment]
@whedon set 1 as version

**Comment by whedon** [comment]
OK. 1 is the version.

**Comment by majensen** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1371/journal.pone.0140072 may be missing for title: Robust selection algorithm (RSA) for multi-omic biomarker discovery; integration with functional network analysis to identify miRNA regulated pathways in multiple cancers
- https://doi.org/10.2307/2532740 may be missing for title: Maximally selected rank statistics
- https://doi.org/10.1111/j.2517-6161.1995.tb02031.x may be missing for title: Controlling the false discovery rate: a practical and powerful approach to multiple testing

INVALID DOIs

- https://doi.org/10.1371/journal.pcbi.1007469 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1675

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1675, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by majensen** [comment]
@scwest - can you look at https://github.com/openjournals/joss-reviews/issues/2044#issuecomment-680887845 and add those refs? Re: the invalid DOI, I believe you want to reference just the "10.1371/..." portion in the bib file, and whedon adds the prefix. Thanks!

**Comment by scwest** [comment]
I have added the updated DOIs to the paper.bib file. I then prepared a new release with the changes.

**Comment by majensen** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1371/journal.pcbi.1007469 is OK
- 10.1371/journal.pone.0140072 is OK
- 10.2307/2532740 is OK
- 10.1111/j.2517-6161.1995.tb02031.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by majensen** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1371/journal.pcbi.1007469 is OK
- 10.1371/journal.pone.0140072 is OK
- 10.2307/2532740 is OK
- 10.1111/j.2517-6161.1995.tb02031.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1678

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1678, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by majensen** [comment]
@openjournals/joss-eics this paper is, in fact, ready. Thanks.

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1300317436802105345) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1682
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02044](https://doi.org/10.21105/joss.02044)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@SiminaB, @majensen - may thanks for your reviews here and to @majensen for editing too ✨ 

@scwest - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02044/status.svg)](https://doi.org/10.21105/joss.02044)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02044">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02044/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02044/status.svg
   :target: https://doi.org/10.21105/joss.02044
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02044/status.svg)](https://doi.org/10.21105/joss.02044)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by scwest** [comment]
Thanks, Mark! I appreciate all the effort and hard work that came from the
reviewers, but especially you!

Sean

**Comment by majensen** [comment]
@scwest by all means! It a nice idea made very functional, and I'm glad we could bring it in for a landing.
