### ISSUE TITLE
Request to regenerate final proof

### ISSUE THREAD

**Issue by benoit-combes** [openjournals/joss-reviews#2045]
Dear @labarba,
I changed the "paper.md" in the gitlab repository. Is it possible to regenerate the final proof ?
Thanks for your consideration.
B.

_Originally posted by @benoit-combes in https://github.com/openjournals/joss-reviews/issues/1862#issuecomment-579278220_

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2045 with the following error: 

 Can't find any papers to compile :-(
