### ISSUE TITLE
[PRE REVIEW]: `continuum_mechanics`: A Python package for Continuum Mechanics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2047]
**Submitting author:** @nicoguaro (<a href="http://orcid.org/0000-0002-9435-1914">Nicolas Guarin-Zapata</a>)
**Repository:** <a href="https://github.com/nicoguaro/continuum_mechanics" target ="_blank">https://github.com/nicoguaro/continuum_mechanics</a>
**Version:** v0.2.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @nicoguaro. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@nicoguaro if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (357.8 files/s, 195955.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           8            245            669            587
reStructuredText                16            565            568            361
Jupyter Notebook                 5              0          17174            174
Markdown                         2             66              0            130
make                             2             24              6             78
TeX                              1             11              0             65
YAML                             2              0              0             29
DOS Batch                        1              8              1             27
INI                              1              5              3             18
-------------------------------------------------------------------------------
SUM:                            38            924          18421           1469
-------------------------------------------------------------------------------


Statistical information for the repository '2047' was gathered on 2020/01/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Nicolas Guarin-Zapat            27          1875            374          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Nicolas Guarin-Zapat       1501           80.1          5.6               11.66
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2047 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/2047/paper/paper.md): found character that cannot start any token while scanning for the next token at line 2 column 8 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you help diagnose this error? It looks like it refers to the use of the ` symbol in this line of YAML text: 

```yaml
---
title: `continuum_mechanics`: A Python package for Continuum Mechanics
```

@nicoguaro can you remove the ` symbols in the title YAML field and call `@whedon generate pdf` here once you are done?

**Comment by xuanxu** [comment]
The title string is yaml-invalid. [This PR](https://github.com/nicoguaro/continuum_mechanics/pull/100) should fix it.

**Comment by nicoguaro** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02047/joss.02047/10.21105.joss.02047.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.7717/peerj-cs.103 is OK

MISSING DOIs

- https://doi.org/10.1016/j.wavemoti.2019.102406 may be missing for title: Finite element modeling of micropolar-based phononic crystals
- https://doi.org/10.1016/j.compstruc.2019.106175 may be missing for title: Method of manufactured solutions code verification of elastostatic solid mechanics problems in a commercial finite element solver
- https://doi.org/10.2172/759450 may be missing for title: Code verification by the method of manufactured solutions

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@nicoguaro Can you check those missing DOI's :point_up: and regenerate the pdf when you are ready?

**Comment by nicoguaro** [comment]
@Kevin-Mattheus-Moerman, ``muhaochen`` is a potential reviewer.

**Comment by nicoguaro** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02047/joss.02047/10.21105.joss.02047.pdf)

**Comment by nicoguaro** [comment]
I forgot to push the commit before regenerating the pdf ...

@whedon generate pdf

**Comment by nicoguaro** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02047/joss.02047/10.21105.joss.02047.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.7717/peerj-cs.103 is OK
- 10.1016/C2009-0-30629-7 is OK
- 10.1016/j.wavemoti.2019.102406 is OK
- 10.1007/978-3-7091-2720-9 is OK
- 10.1016/j.ijsolstr.2011.05.002 is OK
- 10.1016/j.compstruc.2019.106175 is OK
- 10.1115/1.1436090 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@nicoguaro this software certainly seems useful to me but for JOSS a clear research application and functionality beyond that of a minor utility package is required (see our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements)). Would you be able to elaborate on why you feel this work, which appears to be a type of interface to SymPy, classifies as “research software”?

**Comment by nicoguaro** [comment]
> @nicoguaro this software certainly seems useful to me but for JOSS a clear research application and functionality beyond that of a minor utility package is required (see our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements)). Would you be able to elaborate on why you feel this work, which appears to be a type of interface to SymPy, classifies as “research software”?

My first take on this question would be that it has been useful to my research on generalized continua (micropolar and couple-stress), this point is mentioned in the paper and also a recently published article is cited. We are also working on a paper related to couple-stress elasticity where it has been proved useful as well.

A second point, that I also mention in the paper is the need for this type of packages for verification. For example, to automate the creation of solutions using the "Method of Manufactured Solutions" or contrasting Finite Element results with Ritz-Galerkin (or any other weighted-residuals method). These tasks can be automated using a package like `continuum_mechanics`.

A third point that I would mention is the use of similar packages in some books in the field, e.g.

- Constantinescu, A., & Korsunsky, A. (2007). Elasticity with Mathematica®: An Introduction to Continuum Mechanics and Linear Elasticity. Cambridge University Press.

- J.R. (2010). Elasticity. 3rd edition, Springer.

Regarding the software being an "interface to SymPy", I think I could say the same about pretty much any other software that I have authored in the past. For example, [SolidsPy](https://github.com/AppliedMechanics-EAFIT/SolidsPy) is "just" an interface to NumPy, SciPy, and Matplotlib.

I thought that I was aware of the scope of the journal since I have been a reviewer from the very beginning, but it seems that this is not the case. What would you suggest me to do regarding the submission then?

**Comment by jedbrown** [comment]
What would you think of adding an MMS module to this package, wherein a user passes in an analytic displacement field and this package can return the body force for a couple material models, with optional export to C/Fortran (as provided by SymPy). I think this software would be a lot more compelling and exciting with that infrastructure, and would have an obvious venue for contributors to get involved.

**Comment by nicoguaro** [comment]
> What would you think of adding an MMS module to this package, wherein a user passes in an analytic displacement field and this package can return the body force for a couple material models, with optional export to C/Fortran (as provided by SymPy). I think this software would be a lot more compelling and exciting with that infrastructure, and would have an obvious venue for contributors to get involved.

@jedbrown, that sounds like a nice idea. I was planning to add analytic solutions for elasticity, and still plan to, but I think that I could give priority to your suggestion.

**Comment by Kevin-Mattheus-Moerman** [comment]
@nicoguaro great that you will work on these suggestions. If you do not mind I will pause this submission and will resume once you are ready with those developments. You can ping me here when you are ready.

**Comment by danielskatz** [comment]
👋 @nicoguaro - can you provide an estimate of when you think we might be ready to start the review?

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by Kevin-Mattheus-Moerman** [comment]
@nicoguaro how are you getting on? Let me know when you are ready to resume this submission.

**Comment by nicoguaro** [comment]
@Kevin-Mattheus-Moerman, this is in my TODO list. But dealing with online lectures have left little free time.

**Comment by Kevin-Mattheus-Moerman** [comment]
@nicoguaro just checking in. How are you getting on? Let me know when you have those developments done and want us to resume. I hope your lecturing went well and that you enjoyed your summer.

**Comment by arfon** [comment]
@whedon withdraw 

:wave: all, this submission has now been open for nearly nine months without any progress. At this point I'm going to withdraw this submission on behalf of the author. If @nicoguaro has time to make the suggested changes, we can always revisit this in the form of a resubmission to JOSS.

**Comment by whedon** [comment]
Paper withdrawn.
