### ISSUE TITLE
[REVIEW]: hdbscan: A high performance implementation of HDBSCAN* clustering. 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#205]
**Submitting author:** @lmcinnes (<a href="http://orcid.org/0000-0003-2143-6834">Leland McInnes</a>)
**Repository:** <a href="https://github.com/scikit-learn-contrib/hdbscan" target ="_blank">https://github.com/scikit-learn-contrib/hdbscan</a>
**Version:** v0.8.8
**Editor:** @danielskatz
**Reviewer:** @zhaozhang
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.401403" target="_blank">10.5281/zenodo.401403</a>

## Status

[![status](http://joss.theoj.org/papers/b5c5dd4b7491890b711c06225dcc9649/status.svg)](http://joss.theoj.org/papers/b5c5dd4b7491890b711c06225dcc9649)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/b5c5dd4b7491890b711c06225dcc9649"><img src="http://joss.theoj.org/papers/b5c5dd4b7491890b711c06225dcc9649/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/b5c5dd4b7491890b711c06225dcc9649/status.svg)](http://joss.theoj.org/papers/b5c5dd4b7491890b711c06225dcc9649)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/scikit-learn-contrib/hdbscan" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/scikit-learn-contrib/hdbscan">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.8.8)?
- [x] **Authorship:** Has the submitting author (@lmcinnes) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @zhaozhang it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by danielskatz** [comment]
Hi @lmcinnes

Please fix the formatting of the paper part of your submission. See https://github.com/mpastell/Weave.jl/blob/master/paper/paper.md for an example of another current submission that has a properly formatted paper. By this, I refer to two things:

1. the metadata: your line 12 needs one more space at the start.
2. references to items in the bibliography. Only items that are referenced in the text will be shown in the bibliography when the paper is compiled, and you currently don't refer to any of them.

Thanks.

**Comment by lmcinnes** [comment]
Hi @dskatz

Thanks for taking on the review! I'm honoured to have such esteemed
reviewers for this.

I have fixed the metadata as requested. Sorry for the oversight. I believe
I have provided references, hopefully in the correct format (based off the
example).

Thanks,

Leland McInnes.

**Comment by danielskatz** [comment]
Thanks - there were also a couple more things I saw, so I put in a pull request.

**Comment by lmcinnes** [comment]
Thank you! Merged.

**Comment by zhaozhang** [comment]
Hi @lmcinnes,

I have found the following points during installation:
  1. hdbscan depends on scipy also, it was not documented in the instruction manual.
  2. it works with both Python2 and Python3, please document this.
  3. The code examples in README.md are not self-contained, please replace "data" with some example dataset.

Please also include community guidelines:
  1. Contribute to the software.
  2. Report issues or problems with the software.
  3. Seek support.

Please add DOI for the references in paper.bib.

Best,
Zhao

**Comment by lmcinnes** [comment]
Hi @zhaozhang 

Thanks for taking the time to look through everything. I've attempted to remedy each of these points. My only issue is that there does not appear to be a DOI for "Rates of convergence for the cluster tree" from NIPS 2010 (NIPS proceedings seem to forego DOIs for reasons that are not clear to me). Any recommendations on that front would be appreciated.

**Comment by danielskatz** [comment]
If there's no DOI for a reference, then you don't need to supply one :)

JOSS just wants to be sure that where there is a DOI, it's used.

**Comment by danielskatz** [comment]
Hi @zhaozhang 

If the authors have addressed your points, please update the checkboxes and let me know here that you think is ready to be accepted.

If not, please continue to work with the authors on what you think is needed.

**Comment by zhaozhang** [comment]
Hi @danielskatz 

Yes, I have update the checkboxes. I think it is ready to be accepted.

**Comment by danielskatz** [comment]
@arfon, over to you for the next steps.

@zhaozhang, thanks for the quick work in suggesting changes

@lmcinnes, thanks for your quick work in responding to the suggestions.

**Comment by lmcinnes** [comment]
Thanks @zhaozhang and @danielskatz for steering me through this so well.

**Comment by arfon** [comment]
@lmcinnes - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by lmcinnes** [comment]
I believe I managed to make this work: http://doi.org/10.5281/zenodo.401403

Thanks for all the help.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.401403 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.401403" target="_blank">10.5281/zenodo.401403</a> is the archive.

**Comment by arfon** [comment]
@zhaozhang many thanks for the review here and @danielskatz for editing this paper ✨ 

@lmcinnes - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00205 ⚡️ 🚀 💥
