### ISSUE TITLE
[REVIEW]: SpiceyPy: a Pythonic Wrapper for the SPICE Toolkit

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2050]
**Submitting author:** @andrewannex (<a href="http://orcid.org/0000-0002-0253-2313">Andrew Annex</a>)
**Repository:** <a href="https://github.com/AndrewAnnex/SpiceyPy" target ="_blank">https://github.com/AndrewAnnex/SpiceyPy</a>
**Version:** v3.0.2
**Editor:** @mbobra
**Reviewer:** @hayesla, @jessie-dotson
**Archive:** <a href="https://doi.org/10.5281/zenodo.3676146" target="_blank">10.5281/zenodo.3676146</a>

## Status

[![status](https://joss.theoj.org/papers/98136d30bea9982ad160d251e2039fee/status.svg)](https://joss.theoj.org/papers/98136d30bea9982ad160d251e2039fee)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/98136d30bea9982ad160d251e2039fee"><img src="https://joss.theoj.org/papers/98136d30bea9982ad160d251e2039fee/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/98136d30bea9982ad160d251e2039fee/status.svg)](https://joss.theoj.org/papers/98136d30bea9982ad160d251e2039fee)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/AndrewAnnex/SpiceyPy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@hayesla & @jessie-dotson, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mbobra know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/AndrewAnnex/SpiceyPy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@andrewannex) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/AndrewAnnex/SpiceyPy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@andrewannex) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @hayesla, @jessie-dotson it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3847/1538-3881/aac2e1 is OK
- 10.1016/j.pss.2017.02.013 is OK
- 10.5281/zenodo.1009079 is OK
- 10.1029/2018ja025877 is OK
- 10.2514/1.a34329 is OK
- 10.1002/2015gl067436 is OK
- 10.18419/opus-10454 is OK
- 10.1051/0004-6361/201834415 is OK
- 10.1093/mnras/stx1871 is OK
- 10.1117/12.2240648 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02050/joss.02050/10.21105.joss.02050.pdf)

**Comment by mbobra** [comment]
@hayesla @jessie-dotson Thank you for agreeing to review this submission! Whedon generated a checklist and linked a reviewer guide above. Please feel free to ask me (or the submitting author, or each other) if you have any questions :)

**Comment by mbobra** [comment]
@AndrewAnnex Your paper is officially in review!

**Comment by AndrewAnnex** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02050/joss.02050/10.21105.joss.02050.pdf)

**Comment by jessie-dotson** [comment]
My review is complete.  Recommend accepting as is.  

I identified a couple of modest changes that would make the documentation more beginner friendly and filed those as issues in the SpiceyPy repository (#350 and #351).  These are not blockers in anyway, just suggestions to the author.

(An aside to JOSS editors...  I did confirm some functionality, but the package includes so many useful functions, it wasn't feasible for me to confirm them all.  As to whether or not the functionality I did confirm was "core functionality" would depend on why you like spice...  )

**Comment by hayesla** [comment]
I've also completed my review, and I recommend accepting in its current form. 

This is a really great package, and while it was quite a learning curve for me as I have never dealt with SPICE before, the SpiceyPy lessons were extremely helpful! 

If I was to suggest things for the future (not in relation to this review) is to perhaps add more simple examples like the Cassini Position Example, and have the functionality to download the example as a `.py` file so users can play around with it.

Also some helper functions about which kernels are required would be such a plus (however I imagine this is a lot of work) but it would certainly make it more user friendly for people not familiar with SPICE. 

And one final absolutely minor comment, on the instillation [page](https://spiceypy.readthedocs.io/en/master/installation.html#how-to-install-from-source-for-bleeding-edge-updates) it should be `git clone https://github.com/AndrewAnnex/SpiceyPy.git`

**Comment by AndrewAnnex** [comment]
@hayesla @jessie-dotson 
Thank you both for reviewing SpiceyPy! 🎉  As you may have seen I have already started incorporating your feedback into the docs and as issues to be addressed. The kernel management and suggestion idea from @hayesla is a goal that other SPICE users and the NAIF IIRC have been looking into, but it is a substantial project unto itself. 

Thanks again, and for your suggested improvements! -Andrew

**Comment by mbobra** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02050/joss.02050/10.21105.joss.02050.pdf)

**Comment by mbobra** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3847/1538-3881/aac2e1 is OK
- 10.1016/j.pss.2017.02.013 is OK
- 10.5281/zenodo.1009079 is OK
- 10.1029/2018ja025877 is OK
- 10.2514/1.a34329 is OK
- 10.1002/2015gl067436 is OK
- 10.18419/opus-10454 is OK
- 10.1051/0004-6361/201834415 is OK
- 10.1093/mnras/stx1871 is OK
- 10.1117/12.2240648 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mbobra** [comment]
@hayesla @jessie-dotson Thank you so much for your review! We really appreciate your time and effort 😄

**Comment by mbobra** [comment]
@AndrewAnnex We're almost there! Do you mind fixing the following:

* Can you please make your affiliations consistent? Some affiliations includes city, country, and postal code, and others simply include the name of the institute.
* The first reference needs a space between 150 and the following parenthesis.
* Can you please make a new Zenodo release after fixing these issues and make sure the title and author list of the Zenodo release matches that of the JOSS paper?

**Comment by AndrewAnnex** [comment]
@mbobra so the 2nd issue regarding the first reference and the parentheses appears to be the default style for rendering the volume and number in the bib entry (e.g. "volume(number)"), and can be seen in the other reference entries. But I also double checked the reference and google scholar seems to set the number to 2018, so I have that change made in a local branch. 

I will look into making the affiliations consistent, most likely I will remove the additional location information. FYI Author Ben Pearson is not affiliated with an institution (I have their affiliation listed as "General Public" at the moment). If instead I should locate all the additional information for each author please let me know. 

For the zenodo release, is it sufficient to update that information by-hand in the zenodo release via the zenodo website, or should I include a .zenodo.json file in the repo? Note that the new zenodo release will result in version 3.0.2 (v3.0.2) of spiceypy.

**Comment by AndrewAnnex** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02050/joss.02050/10.21105.joss.02050.pdf)

**Comment by AndrewAnnex** [comment]
@mbobra I think the first two issues are now fixed, I have started looking into the zenodo release but the question about the json file still stands, but I will check back in tomorrow

**Comment by AndrewAnnex** [comment]
@mbobra I just noticed that we may have to add an author to the author list. Currently the author list includes every contributor (large and small) to the repo who responded prior to the submission to JOSS for review, which was all of the contributors. During the pre-review period but after the software report which listed code contributions, two commits were merged into the master branch, see https://github.com/AndrewAnnex/SpiceyPy/commit/fde56cd41935b15e3e3735db03cc9c0311711d73 and https://github.com/AndrewAnnex/SpiceyPy/commit/c2ed0c05aaa65a373bee8a1f430c70027a8adea5.

At the time I must have concluded that this author did not meet the deadline for inclusion as an author but since a new release is needed it would be more consistent to include them with my permissive policy on authorship. What do you advise in this situation?

**Comment by AndrewAnnex** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by AndrewAnnex** [comment]
@whedon generate pdf from branch fix_for_joss_zenodo

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch fix_for_joss_zenodo. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2050 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/lib/whedon/author.rb:68:in `block in build_affiliation_string': Problem with affiliations for Johan von Forstner, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/lib/whedon/author.rb:67:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/lib/whedon/author.rb:67:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/lib/whedon.rb:201:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/lib/whedon.rb:201:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/lib/whedon.rb:198:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/lib/whedon.rb:198:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/lib/whedon.rb:91:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by AndrewAnnex** [comment]
@whedon generate pdf from branch fix_for_joss_zenodo

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch fix_for_joss_zenodo. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02050/joss.02050/10.21105.joss.02050.pdf)

**Comment by AndrewAnnex** [comment]
@mbobra I've received permission from the new author so I have went ahead and added their information and the above proof includes their information. If everything looks good I'll merge that change into the master branch and cut a new release 🚀

**Comment by AndrewAnnex** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02050/joss.02050/10.21105.joss.02050.pdf)

**Comment by AndrewAnnex** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02050/joss.02050/10.21105.joss.02050.pdf)

**Comment by mbobra** [comment]
Thanks for all this! Here are my answers:

* It is okay to have no affiliation. We recommend using 'None' instead of general public, so please change it to 'None.'
* All the other affiliations look good 😄
* It is sufficient to update the Zenodo deposit information by hand, so please go ahead and merge this branch into master (after making the affiliation change), cut a new release, deposit in Zenodo, edit any necessary metadata by hand, and then link the Zenodo DOI in your `README.rst file`.

**Comment by AndrewAnnex** [comment]
@mbobra okay great I think we are almost ready then, but annoyingly I just noticed that all of my affiliations end with periods. Should I remove them?

**Comment by mbobra** [comment]
> @mbobra okay great I think we are almost ready then, but annoyingly I just noticed that all of my affiliations end with periods. Should I remove them?

Hmm...I just looked at the most recent JOSS publications (https://joss.theoj.org/papers/published) and it looks like none of the affiliations end with periods. So, yes. Sorry :( We're almost there!!!

**Comment by AndrewAnnex** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02050/joss.02050/10.21105.joss.02050.pdf)

**Comment by AndrewAnnex** [comment]
@mbobra turns out the .zenodo.json file was a bad idea and broke the release hence the delay. But in any case I fixed it!

the Zenodo DOI for SpiceyPy 3.0.2 is 10.5281/zenodo.3676146, note that the version is now v3.0.2. 


:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit:

**Comment by mbobra** [comment]
@whedon set 10.5281/zenodo.3676146 as archive

**Comment by mbobra** [comment]
@whedon set v3.0.2 as version

**Comment by whedon** [comment]
OK. v3.0.2 is the version.

**Comment by mbobra** [comment]
@openjournals/joss-eics This paper is ready for final processing 🎉

**Comment by kyleniemeyer** [comment]
Hi @AndrewAnnex, I submitted two small PRs that did some copy-editing:
https://github.com/AndrewAnnex/SpiceyPy/pull/356 and https://github.com/AndrewAnnex/SpiceyPy/pull/357

**Comment by AndrewAnnex** [comment]
@kyleniemeyer okay I will look to merge those, will that require a new release?

**Comment by AndrewAnnex** [comment]
@kyleniemeyer those changes are merged

@whedon generate pdf

**Comment by AndrewAnnex** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02050/joss.02050/10.21105.joss.02050.pdf)

**Comment by kyleniemeyer** [comment]
No, we can proceed since the software hasn't changed

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3847/1538-3881/aac2e1 is OK
- 10.1016/j.pss.2017.02.013 is OK
- 10.5281/zenodo.1009079 is OK
- 10.1029/2018ja025877 is OK
- 10.2514/1.a34329 is OK
- 10.1002/2015gl067436 is OK
- 10.18419/opus-10454 is OK
- 10.1051/0004-6361/201834415 is OK
- 10.1093/mnras/stx1871 is OK
- 10.1117/12.2240648 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1331

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1331, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1230714471502401536) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1332
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02050](https://doi.org/10.21105/joss.02050)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @AndrewAnnex on your article's publication in JOSS!

Many thanks to @hayesla and @jessie-dotson for reviewing this, and @mbobra for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02050/status.svg)](https://doi.org/10.21105/joss.02050)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02050">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02050/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02050/status.svg
   :target: https://doi.org/10.21105/joss.02050
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02050/status.svg)](https://doi.org/10.21105/joss.02050)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by AndrewAnnex** [comment]
Thank you @kyleniemeyer @mbobra @jessie-dotson @hayesla !
