### ISSUE TITLE
[PRE REVIEW]: PyEscape

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2051]
**Submitting author:** @sirsharpest (<a href="http://orcid.org/0000-0002-4572-5828">Nathan Hughes</a>)
**Repository:** <a href="https://github.com/SirSharpest/NarrowEscapeSimulator" target ="_blank">https://github.com/SirSharpest/NarrowEscapeSimulator</a>
**Version:** 1.0
**Editor:** @drvinceknight
**Reviewers:** @pdebuyl, @markgalassi

**Author instructions**

Thanks for submitting your paper to JOSS @sirsharpest. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @drvinceknight.

@sirsharpest if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (124.4 files/s, 65925.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              2            338              0           4788
Python                           7             43              3            166
Markdown                         2             20              0             44
Jupyter Notebook                 1              0            927             31
-------------------------------------------------------------------------------
SUM:                            12            401            930           5029
-------------------------------------------------------------------------------


Statistical information for the repository '2051' was gathered on 2020/02/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Nathan Hughes                    4           251             39          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Nathan Hughes               212           84.5          0.0                0.94
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #2051 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/2051/paper.md): mapping values are not allowed in this context at line 2 column 16 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@SirSharpest I think your paper is not compiling because you used a ` symbol in the YAML code at the top for the title. Can you replace:
```YAML
title: PyEscape: A narrow escape problem simulator package for python'
```
with
```YAML
title: PyEscape: A narrow escape problem simulator package for python
```
Once you made the change you can call `@whedon generate pdf` here to reattempt the creation of the the pdf.

**Comment by Kevin-Mattheus-Moerman** [comment]
@drvinceknight, @dfm, @majensen can one of you edit this submission? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev am I right to say it is the ` symbol? Or are those allowed in YAML?

**Comment by SirSharpest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2051 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/2051/paper.md): mapping values are not allowed in this context at line 2 column 16 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by SirSharpest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02051/joss.02051/10.21105.joss.02051.pdf)

**Comment by xuanxu** [comment]
> openjournals/dev am I right to say it is the ` symbol? Or are those allowed in YAML?

The error is that the parser considers `PyEscape:` a YAML key, out of place, so it errors. 
To keep the title, quoting the whole string will make it:
```YAML
title: "PyEscape: A narrow escape problem simulator package for python"
```

**Comment by SirSharpest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02051/joss.02051/10.21105.joss.02051.pdf)

**Comment by SirSharpest** [comment]
All good now, sorry for the issues!

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1080/07388551.2016.1271767 is OK
- 10.1016/j.sbspro.2013.12.893 is OK
- 10.1016/S0022-2836(05)80360-2 is OK
- 10.1186/gb-2010-11-10-r106 is OK
- 10.1007/978-3-7091-1254-0_14 is OK
- 10.1016/S0006-3495(00)76647-1 is OK
- 10.1038/nrg3095 is OK
- 10.1111/tpj.12114 is OK
- 10.3389/fpls.2017.00051 is OK
- 10.1111/j.1365-3040.2007.01727.x is OK
- 10.1016/j.tplants.2018.08.006 is OK
- 10.1016/j.molp.2019.02.004 is OK
- 10.1007/BF00197025 is OK
- 10.1049/iet-cvi.2016.0127 is OK
- 10.1016/j.devcel.2013.06.010 is OK
- 10.1016/S0006-3495(93)81179-2 is OK
- 10.1016/0022-5193(78)90288-6 is OK
- 10.1002/0471142727.mb1811s66 is OK
- 10.1007/s00114-012-0988-z is OK
- 10.1093/bioinformatics/btu170 is OK
- 10.1101/423905 is OK
- 10.1038/nbt.3519 is OK
- 10.1016/j.fcr.2006.11.008 is OK
- 10.1111/pbi.13017 is OK
- 10.1104/pp.19.00460 is OK
- 10.3389/fpls.2015.00170 is OK
- 10.1126/science.aar4142 is OK
- 10.1105/tpc.15.00956 is OK
- 10.1371/journal.pone.0196219 is OK
- 10.1016/j.cell.2008.06.030 is OK
- 10.1038/ncomms8658 is OK
- 10.1134/S0965545X14050034 is OK
- 10.1016/j.crvi.2010.12.013 is OK
- 10.4161/psb.4.6.8359 is OK
- 10.1111/tpj.13415 is OK
- 10.1111/nph.14857 is OK
- 10.1111/nph.14857 is OK
- 10.7554/eLife.14770 is OK
- 10.1093/jxb/erm042 is OK
- 10.1098/rsif.2008.0014 is OK
- 10.1038/cdd.2011.37 is OK
- 10.1186/s13059-016-0881-8 is OK
- 10.1126/science.1203877 is OK
- 10.1146/annurev-phyto-080614-120114 is OK
- 10.1104/pp.125.4.1802 is OK
- 10.1111/j.1365-3040.2007.01676.x is OK
- 10.1111/pce.12983 is OK
- 10.1371/journal.pone.0156362 is OK
- 10.3389/fpls.2016.00987 is OK
- 10.1016/j.devcel.2019.02.022 is OK
- 10.1016/j.tplants.2010.05.002 is OK
- 10.1016/j.cell.2006.12.006 is OK
- 10.1111/tpj.12342 is OK
- 10.1007/s00122-017-2925-1 is OK
- 10.1186/1746-4811-7-44 is OK
- 10.1093/aob/mcu120 is OK
- 10.1105/tpc.104.021725 is OK
- 10.1093/bioinformatics/btw354 is OK
- 10.1073/pnas.1203458110 is OK
- 10.1534/genetics.112.146316 is OK
- 10.1002/andp.18551700105 is OK
- 10.1111/pce.13164 is OK
- 10.1126/science.283.5409.1911 is OK
- 10.1093/jxb/53.366.39 is OK
- 10.1093/aob/mcm048 is OK
- 10.1016/j.tplants.2011.09.005 is OK
- 10.2147/OTT.S98910 is OK
- 10.1016/j.pbi.2014.11.002 is OK
- 10.1105/tpc.110.074153 is OK
- 10.1016/j.tplants.2014.06.013 is OK
- 10.1101/720086 is OK
- 10.1016/j.biocel.2009.09.016 is OK
- 10.1146/annurev.phyto.43.040204.135923 is OK
- 10.1093/jxb/err182 is OK
- 10.7326/0003-4819-130-12-199906150-00008 is OK
- 10.1007/BF00202335 is OK
- 10.1104/pp.106.900207 is OK
- 10.2307/1938927 is OK
- 10.1016/S1364-8152(98)00033-4 is OK
- 10.1186/s13007-019-0394-z is OK
- 10.1371/journal.pcbi.1006015 is OK
- 10.1038/212635a0 is OK
- 10.1016/j.envexpbot.2009.08.005 is OK
- 10.1016/j.plantsci.2016.12.006 is OK
- 10.1038/nrm3790 is OK
- 10.1016/j.tplants.2008.03.005 is OK
- 10.1093/aob/mcm110 is OK
- 10.21105/joss.00097 is OK
- 10.3389/fpls.2015.00171 is OK
- 10.1105/tpc.16.00958 is OK
- 10.1007/s10955-004-5712-8 is OK
- 10.1016/j.tplants.2015.07.008 is OK
- 10.1111/tpj.14312 is OK
- 10.1186/s13007-017-0229-8 is OK
- 10.1186/s13007-015-0072-8 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1016/j.cels.2018.12.009 is OK
- 10.12703/P7-25 is OK
- 10.1093/jxb/erv387 is OK
- 10.2307/3802789 is OK
- 10.1126/science.1251358 is OK
- 10.1038/nature05286 is OK
- 10.1073/pnas.0508882103 is OK
- 10.1007/1-4020-4496-8_123 is OK
- 10.1073/pnas.0401221101 is OK
- 10.1038/nmeth.3317 is OK
- 10.3390/plants6010012 is OK
- 10.1093/pcp/pcy249 is OK
- 10.1007/s10265-013-0547-5 is OK
- 10.1145/258533.258653 is OK
- 10.1038/s41598-018-28948-z is OK
- 10.1007/BF01290774 is OK
- 10.1093/bioinformatics/btq310 is OK
- 10.1093/jxb/erm155 is OK
- 10.1037/a0029177 is OK
- 10.1039/DC9786600199 is OK
- 10.1038/nrmicro.2017.33 is OK
- 10.1111/nph.12439 is OK
- 10.1016/j.tplants.2011.01.004 is OK
- 10.1016/j.pbi.2015.06.019 is OK
- 10.1105/tpc.111.087742 is OK
- 10.1007/s10722-013-9957-4 is OK
- 10.1105/tpc.15.00471 is OK
- 10.1155/2013/387023 is OK
- 10.1128/JVI.02346-08 is OK
- 10.1111/j.1365-2818.2011.03584.x is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.1016/j.pbi.2016.05.008 is OK
- 10.1111/gcb.13212 is OK
- 10.1038/s41477-018-0288-5 is OK
- 10.1016/j.pbi.2017.04.005 is OK
- 10.1186/s13059-014-0550-8 is OK
- 10.4161/rna.19965 is OK
- 10.1038/nrm1470 is OK
- 10.1093/aob/mcr308 is OK
- 10.1094/MPMI-07-10-0149 is OK
- 10.1094/MPMI-07-10-0149 is OK
- 10.1104/pp.18.00107 is OK
- 10.1111/nph.15130 is OK
- 10.1104/pp.107.1.7 is OK
- 10.1037/1082-989X.1.2.130 is OK
- 10.1111/tpj.13047 is OK
- 10.1098/rstb.2018.0307 is OK
- 10.1007/s00122-014-2322-y is OK
- 10.1371/journal.pbio.2002050 is OK
- 10.1111/tpj.14498 is OK
- 10.1073/pnas.1202040109 is OK
- 10.1109/TNB.2018.2882223 is OK
- 10.4161/psb.27931 is OK
- 10.3389/fpls.2012.00030 is OK
- 10.1016/S0092-8674(00)80412-2 is OK
- 10.1111/tpj.13755 is OK
- 10.1186/s13007-015-0060-z is OK
- 10.1371/journal.pone.0051822 is OK
- 10.1016/j.tplants.2004.08.009 is OK
- 10.1073/pnas.0705147104 is OK
- 10.1073/pnas.1911758116 is OK
- 10.1016/j.pbi.2017.11.001 is OK
- 10.1007/s11033-011-1185-4 is OK
- 10.1007/s11033-011-1185-4 is OK
- 10.1007/s00122-017-2880-x is OK
- 10.1186/s13007-017-0173-7 is OK
- 10.4161/psb.25345 is OK
- 10.1016/j.jplph.2006.10.011 is OK
- 10.1038/nplants.2017.82 is OK
- 10.5897/AJMR11.784 is OK
- 10.1038/nbt1209-1135 is OK
- 10.1266/ggs.87.299 is OK
- 10.1109/MCSE.2007.58 is OK
- 10.1146/annurev.arplant.51.1.323 is OK
- 10.1016/j.tplants.2017.01.004 is OK
- 10.1080/13518040701205365 is OK
- 10.1093/jxb/ers392 is OK
- 10.1104/pp.19.00130 is OK
- 10.1007/s11032-011-9608-4 is OK
- 10.1145/321356.321357 is OK
- 10.1038/nature02734 is OK
- 10.1002/ardp.201300287 is OK
- 10.5772/53203 is OK
- 10.1007/978-94-007-6401-9_13 is OK
- 10.1111/mpp.12210 is OK
- 10.1371/journal.pone.0088419 is OK
- 10.3389/fpls.2017.00318 is OK
- 10.1007/BF01280708 is OK
- 10.3389/fpls.2015.00619 is OK
- 10.1094/MPMI-07-12-0187-R is OK
- 10.1016/j.plantsci.2018.07.001 is OK
- 10.1016/j.plantsci.2018.07.001 is OK
- 10.1615/AtoZ.s.stokes-einstein_equation is OK
- 10.1073/pnas.1914096116 is OK
- 10.1007/978-3-642-41787-0_9 is OK
- 10.1186/gb-2010-11-3-r25 is OK
- 10.1105/tpc.109.069922 is OK
- 10.1111/pbi.12245 is OK
- 10.1111/j.1365-2745.2010.01752.x is OK
- 10.1017/CBO9781107415324.004 is OK
- 10.1007/s41060-017-0086-6 is OK
- 10.1007/s41060-017-0086-6 is OK
- 10.5281/ZENODO.225783 is OK
- 10.1186/s13007-015-0098-y is OK
- 10.3389/fpls.2016.00745 is OK
- 10.1104/pp.110.168187 is OK
- 10.1186/s12870-018-1515-y is OK
- 10.1073/pnas.72.8.3111 is OK
- 10.1242/jcs.209346 is OK
- 10.1126/science.aaq0892 is OK
- 10.1111/tpj.14485 is OK
- 10.1261/rna.053959.115 is OK
- 10.1073/pnas.0706599104 is OK
- 10.1186/s13007-019-0401-4 is OK
- 10.1016/j.jcs.2014.01.006 is OK
- 10.1016/S1369-5266(03)00058-X is OK
- 10.1093/jxb/erp058 is OK
- 10.1007/s12571-013-0263-y is OK
- 10.1016/j.jconrel.2009.09.019 is OK
- 10.1016/j.plantsci.2018.01.001 is OK
- 10.1093/pcp/pcs113 is OK
- 10.1104/pp.113.229179 is OK
- 10.1016/j.pbi.2015.12.002 is OK
- 10.1371/journal.pone.0075295 is OK
- 10.1093/jxb/ert245 is OK
- 10.1016/j.tplants.2015.11.002 is OK
- 10.1371/journal.pone.0140484 is OK
- 10.1093/biostatistics/kxw041 is OK
- 10.1111/tpj.13741 is OK
- 10.1016/S1360-1385(02)00004-3 is OK
- 10.7554/eLife.01355.001 is OK
- 10.1038/nplants.2015.25 is OK
- 10.1105/tpc.110.082602 is OK
- 10.1146/annurev-arplant-043015-111840 is OK
- 10.1126/science.aat7744 is OK
- 10.1093/aob/mcs031 is OK
- 10.1186/s13007-017-0162-x is OK
- 10.1098/rstb.1952.0012 is OK
- 10.1016/j.tibtech.2014.11.006 is OK
- 10.1016/j.tplants.2010.05.005 is OK
- 10.1016/j.devcel.2011.10.006 is OK
- 10.1101/507319 is OK
- 10.1146/annurev.phyto.050908.135202 is OK
- 10.1371/journal.pone.0143196 is OK
- 10.1093/aob/mcm180 is OK
- 10.1118/1.2836950 is OK
- 10.1105/tpc.113.110676 is OK
- 10.3389/fpls.2015.00724 is OK
- 10.4161/psb.21663 is OK
- 10.1093/nar/gkq808 is OK
- 10.1007/s00122-007-0681-3 is OK
- 10.1016/S1369-5266(00)00082-0 is OK
- 10.1016/j.jas.2003.07.003 is OK
- 10.1105/tpc.112.102046 is OK
- 10.1111/j.1467-9574.2012.00530.x is OK
- 10.1016/j.pbi.2013.07.002 is OK
- 10.1016/j.pbi.2012.09.010 is OK
- 10.1093/jxb/erv378 is OK
- 10.1073/pnas.1202919109 is OK
- 10.1111/nph.14599 is OK
- 10.1038/s41477-019-0429-5 is OK
- 10.13523/j.cb.20140505 is OK
- 10.1007/s00709-010-0247-0 is OK
- 10.1104/pp.110.161547 is OK
- 10.1016/j.it.2014.05.004 is OK
- 10.1016/j.it.2014.05.004 is OK
- 10.1021/j150474a012 is OK

MISSING DOIs

- https://doi.org/10.1353/abr.2017.0007 may be missing for title: Academia.Edu
- https://doi.org/10.1007/s11538-019-00685-y may be missing for title: Mathematical Modelling of Auxin Transport in Plant Tissues: Flux Meets Signalling and Growth
- https://doi.org/10.24097/wolfram.06940.data may be missing for title: The Valley of Fear
- https://doi.org/10.1371/journal.pgen.1005373 may be missing for title: Large-Scale Phenomics Identifies Primary and Fine-Tuning Roles for CRKs in Responses Related to Oxidative Stress
- https://doi.org/10.1104/pp.90.3.1143 may be missing for title: Symplastic Transport of Carboxyfluorescein in Staminal Hairs of Setcreasea Purpurea Is Diffusive and Includes Loss to the Vacuole 1
- https://doi.org/10.1109/iccv.2017.244 may be missing for title: Unpaired Image-To-Image Translation Using Cycle-Consistent Adversarial Networks

INVALID DOIs

- 10.1016/j.bbamem.2015.02.010.Cationic is INVALID
```

**Comment by arfon** [comment]
@SirSharpest - could you please truncate your bibtex file to only include the entries that this paper actually cites?

**Comment by SirSharpest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02051/joss.02051/10.21105.joss.02051.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @drvinceknight as editor

**Comment by whedon** [comment]
@drvinceknight has been invited to edit this submission.

**Comment by drvinceknight** [comment]
@whedon assign @drvinceknight as editor

**Comment by whedon** [comment]
OK, the editor is @drvinceknight

**Comment by drvinceknight** [comment]
@SirSharpest looking at [this list of possible reviewers](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing) could you suggest any as a good fit?

**Comment by SirSharpest** [comment]
possibly markgalassi, pdebuyl ?

**Comment by drvinceknight** [comment]
@markgalassi and @pdebuyl would you be able to review this software paper for JOSS? It's a package for a particle type of Brownian particle simulation which I believe is within both of your expertise. If you've not done it before, reviewing for JOSS is slightly different to a traditional journal, you can find information about the process here https://joss.readthedocs.io/en/latest/reviewer_guidelines.html and I'd be delighted to answer any questions you may have.

**Comment by pdebuyl** [comment]
Hi @drvinceknight 

I will review the paper. I already worked for JOSS for the paper on the rowan quaternion library.

**Comment by markgalassi** [comment]
Dear @drvinceknight I will be happy to review the paper.  I started another one once but got badly ill for a protracted period, but that was long ago so I am ready.

**Comment by drvinceknight** [comment]
@whedon assign @pdebuyl as reviewer

**Comment by whedon** [comment]
OK, @pdebuyl is now a reviewer

**Comment by drvinceknight** [comment]
@whedon add @markgalassi as reviewer

**Comment by whedon** [comment]
OK, @markgalassi is now a reviewer

**Comment by drvinceknight** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2072.

**Comment by drvinceknight** [comment]
Thank you both for agreeing to review :+1: 

The review takes place on #2072 and there are instructions there. If I can assist with anything please let me know.
