### ISSUE TITLE
[PRE REVIEW]: The pdb2sql Python Package: Parsing, Manipulation and Analysis of PDB Files Using SQL Queries

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2052]
**Submitting author:** @NicoRenaud (<a href="http://orcid.org/0000-0001-9589-2694">Nicolas Renaud</a>)
**Repository:** <a href="https://github.com/DeepRank/pdb2sql" target ="_blank">https://github.com/DeepRank/pdb2sql</a>
**Version:** 0.2.2
**Editor:** @lpantano
**Reviewers:** @i-mtz, @JoaoRodrigues

**Author instructions**

Thanks for submitting your paper to JOSS @NicoRenaud. **Currently, there isn't an JOSS editor assigned** to your paper.

@NicoRenaud if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (407.1 files/s, 62723.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          17            798           1176           2380
reStructuredText                12            232            271            240
Markdown                         2             52              0            151
YAML                             2             17              9             43
make                             1              4              7              9
JSON                             1              0              0              3
-------------------------------------------------------------------------------
SUM:                            35           1103           1463           2826
-------------------------------------------------------------------------------


Statistical information for the repository '2052' was gathered on 2020/02/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Cunliang Geng                  100         15479          13662           82.58
NicoRenaud                      11           433            619            2.98
Nicolas Renaud                  26          3915           1181           14.44

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Cunliang Geng              2664           17.2          1.1               15.32
Nicolas Renaud             1690           43.2         14.9               18.46
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btp163 is OK
- 10.1093/bioinformatics/btg299 is OK
- 10.1002/(SICI)1096-987X(20000130)21:2<79::AID-JCC1>3.0.CO;2-B is OK
-  10.25080/Majora-629e541a-00e  is OK
- 10.1093/bioinformatics/btz496 is OK
- 10.1371/journal.pcbi.1006791 is OK
- 10.1371/journal.pone.0161879 is OK
- 10.1093/nar/gky949 is OK
- 10.1101/483305 is OK
- 10.1002/prot.10393 is OK

MISSING DOIs

- https://doi.org/10.1093/bioinformatics/btr168 may be missing for title: ProDy : Protein Dynamics Inferred from Theory and Experiments

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02052/joss.02052/10.21105.joss.02052.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@VivianePons, @lpantano, @will-rowe, @majensen would one of you be able to edit this submission?

**Comment by Kevin-Mattheus-Moerman** [comment]
@NicoRenaud can you check the potentially missing DOI :point_up:, thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @lpantano as editor

**Comment by whedon** [comment]
@lpantano has been invited to edit this submission.

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by NicoRenaud** [comment]
Dear editor, I’m not sure if I should answer that email as it is my first submission to JOSS. But I’ve fixed the missing DOI and all the DOIs should be in order now. ThanksBest wishesNico  From: Kevin Mattheus MoermanSent: Saturday, 1 February 2020 23:15To: openjournals/joss-reviewsCc: Nicolas Renaud; MentionSubject: Re: [openjournals/joss-reviews] [PRE REVIEW]: The pdb2sql Python Package: Parsing, Manipulation and Analysis of PDB Files Using SQL Queries (#2052) @NicoRenaud can you check the potentially missing DOI ☝️, thanks—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lpantano** [comment]
@whedon assign @i-mtz as reviewer

**Comment by whedon** [comment]
OK, @i-mtz is now a reviewer

**Comment by lpantano** [comment]
@NicoRenaud, do you recommend any review for this? I will start the review process and add it afterwards. Thanks!

**Comment by lpantano** [comment]
@HadrienG, would you be interested on reviewing this?

**Comment by NicoRenaud** [comment]
Dear Lorena, Joao Rodriguez (https://github.com/JoaoRodrigues) would be a good reviewer. He has written pdb_tools which is similar to pdb2sql Best,Nico  From: Lorena PantanoSent: Wednesday, 5 February 2020 23:36To: openjournals/joss-reviewsCc: Nicolas Renaud; MentionSubject: Re: [openjournals/joss-reviews] [PRE REVIEW]: The pdb2sql Python Package: Parsing, Manipulation and Analysis of PDB Files Using SQL Queries (#2052) @NicoRenaud, do you recommend any review for this? I will start the review process and add it afterwards. Thanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lpantano** [comment]
Hi @JoaoRodrigues would you like to review this tool?

**Comment by JoaoRodrigues** [comment]
Hi @lpantano, would be happy to!

**Comment by lpantano** [comment]
@whedon add @JoaoRodrigues as reviewer

**Comment by whedon** [comment]
OK, @JoaoRodrigues is now a reviewer

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2077.
