### ISSUE TITLE
[PRE REVIEW]: Latexify.jl, translating mathematical Julia objects to renderable equations and tables.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2053]
**Submitting author:** @korsbo (<a href="http://orcid.org/0000-0001-9811-3190">Niklas Korsbo</a>)
**Repository:** <a href="https://github.com/korsbo/Latexify.jl" target ="_blank">https://github.com/korsbo/Latexify.jl</a>
**Version:** v0.12.3
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @korsbo. **Currently, there isn't an JOSS editor assigned** to your paper.

@korsbo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (797.7 files/s, 79872.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           41            496            155           4621
Markdown                        18            260              0            839
YAML                             4              9              3             86
TOML                             2              5              0             34
-------------------------------------------------------------------------------
SUM:                            65            770            158           5580
-------------------------------------------------------------------------------


Statistical information for the repository '2053' was gathered on 2020/02/01.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2053 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@korsbo thanks for your submission. Our bot `@whedon` has failed to find your paper.md file. Where is it located? Can you place it in an appropriate spot for our system (see https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements)

I've had a glance at your repository. This submission certainly seems to be a very useful piece of work e.g. for me I can think of uses for the development of teaching and documentation materials. One of the JOSS submission criteria is that the "_The software should have an **obvious** research application._", can you clearly summarize the research applications for this software for us? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@korsbo :point_up:

**Comment by korsbo** [comment]
Hi @Kevin-Mattheus-Moerman,
Thanks for the work that you do in processing my submission and sorry about the delay! 

I'll make sure that the document can be generated. It's currently under `docs/paper/paper.md` in a branch, joss2. I'll fiddle around until `@whedon` manages to get it right. 

The paper has a short paragraph aimed to justify why the package should be considered to have a research application. 

> The package aims to support the scientific work-flow through facilitating
inspection, automation and representation. Simple inspection of the equations
that a computational model is ultimately simulating may increase
comprehensibility and improve troubleshooting.  It, furthermore, allows for
de-mystification of computational models generated using DSLs.  The
programmatic formatting of equations and tables enables their automatic
inclusion into generated documents, documentation, reports or posts (possibly
in combination with tools such as Weave.jl). Such programmatic
translation can also help to ensure an accurate correspondence between what
software does and what reports or articles claim that they do.  It is also just
rather convenient.

I could expand on this and I know that Latexify.jl is already used at several stages of the scientific process. It is used in the iterative process of generating and testing models, where the inspection of the mathematics behind a model is useful. It is used to automate parts of software documentation (indeed all tables and equations in Latexify.jl's own documentation are generated with the package). It is used to write tutorials and blog posts ([example](https://tutorials.juliadiffeq.org/html/models/04-diffeqbio_II_networkproperties.html)). lt is used by other packages to allow users of their software to inspect the mathematics behind objects and thus facilitate understanding. And finally, it is used in the generation of scientific papers. 

Latexify.jl allows for an automated and almost instant mapping from mathematical objects to legible and neatly formatted equations, tables, etc. This is not only very convenient but it also helps with ensuring correctness along all these stages of scientific inquiry.

**Comment by korsbo** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by korsbo** [comment]
@whedon generate pdf from branch joss2

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss2
. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2053 with the following error: 

 error: pathspec 'joss2
' did not match any file(s) known to git.
Can't find any papers to compile :-(

**Comment by korsbo** [comment]
@whedon generate pdf from branch joss2

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss2
. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2053 with the following error: 

 error: pathspec 'joss2
' did not match any file(s) known to git.
Can't find any papers to compile :-(

**Comment by korsbo** [comment]
@whedon generate pdf from branch joss2/paper/

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss2/paper/. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2053 with the following error: 

 error: pathspec 'joss2/paper/' did not match any file(s) known to git.
Can't find any papers to compile :-(

**Comment by korsbo** [comment]
@whedon generate pdf from branch joss2/paper/paper.md

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss2/paper/paper.md
. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2053 with the following error: 

 error: pathspec 'joss2/paper/paper.md
' did not match any file(s) known to git.
Can't find any papers to compile :-(

**Comment by korsbo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02053/joss.02053/10.21105.joss.02053.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- doi:10.21105/joss.00204 is OK
- 10.5334/jors.151 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by korsbo** [comment]
I had a look through the list of reviewers and made a list of potential reviewers. I ordered the list roughly by relevance, most relevant first.

ChrisRackauckas
matbesancon
dpsanders
Datseris
avik-pal
dawbarton
kavir1698
malmaud
jingpengw
juliohm

**Comment by korsbo** [comment]
I should disclose that I have collaborated with ChrisRackauckas on DiffEqBiological.jl. I'm uncertain whether that would constitute a conflict of interest. He is, however, the one on the list who I think would know Latexify the best.

**Comment by Kevin-Mattheus-Moerman** [comment]
@korsbo after having reviewed your submission, the code functionality, the paper, and your additional comments here on research applications, the board has decided that this work is unfortunately not within scope for JOSS. In particular, although this is clearly well put together and very useful package, the research application is not substantial enough at present. 
We thank you again for your submission and hope you will consider JOSS for future work (or amended versions of this work) which do have a clear and significant research application.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
