### ISSUE TITLE
[PRE REVIEW]: Annotating text with ontologies using jabberwocky’s catch

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2054]
**Submitting author:** @sap218 (<a href="http://orcid.org/0000-0002-6169-0135">Samantha Pendleton</a>)
**Repository:** <a href="https://github.com/sap218/jabberwocky" target ="_blank">https://github.com/sap218/jabberwocky</a>
**Version:** v0.1.0.2
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @sap218. **Currently, there isn't an JOSS editor assigned** to your paper.

@sap218 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (175.3 files/s, 18726.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           2             68             43            317
Markdown                         3             39              0             97
TeX                              1              6              0             71
-------------------------------------------------------------------------------
SUM:                             6            113             43            485
-------------------------------------------------------------------------------


Statistical information for the repository '2054' was gathered on 2020/02/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Samantha Pendleton               3           432              4          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Samantha Pendleton          428           99.1          0.0                9.35
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1093/database/bau033 may be missing for title: tagtog: interactive and text-mining-assisted annotation of gene mentions in PLOS full-text articles
- https://doi.org/10.3115/v1/p14-5010 may be missing for title: The Stanford CoreNLP natural language processing toolkit
- https://doi.org/10.1093/nar/gkr972 may be missing for title: Disease Ontology: a backbone for disease semantic integration
- https://doi.org/10.1016/j.ajhg.2008.09.017 may be missing for title: The Human Phenotype Ontology: a tool for annotating and analyzing human hereditary disease
- https://doi.org/10.1093/bib/bbv011 may be missing for title: The role of ontologies in biological and biomedical research: a functional perspective

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02054/joss.02054/10.21105.joss.02054.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@sap218 thank you for your submission. After reviewing your repository and the software functionality the JOSS editorial board has determined that although this work appears to be useful, it is at present not acceptable for publication in JOSS. In particular it is classified as a "minor utility" package (see our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements)).  
If the functionality of this project is significantly expanded it may warrant a re-submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
