### ISSUE TITLE
[PRE REVIEW]: scPCA: A toolbox for sparse contrastive principal component analysis in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2055]
**Submitting author:** @PhilBoileau (<a href="http://orcid.org/0000-0002-4850-2507">Philippe Boileau</a>)
**Repository:** <a href="https://github.com/PhilBoileau/scPCA" target ="_blank">https://github.com/PhilBoileau/scPCA</a>
**Version:** v1.1.6
**Editor:** @csoneson
**Reviewers:** @fabian-s, @LTLA

**Author instructions**

Thanks for submitting your paper to JOSS @PhilBoileau. **Currently, there isn't an JOSS editor assigned** to your paper.

@PhilBoileau if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.05 s (606.2 files/s, 65358.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               19            131            678           1295
Rmd                              2            127            316            254
Markdown                         5             81              0            234
TeX                              2             15              0            145
YAML                             3             28              4            113
make                             1              9              0             20
-------------------------------------------------------------------------------
SUM:                            32            391            998           2061
-------------------------------------------------------------------------------


Statistical information for the repository '2055' was gathered on 2020/02/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Nima Hejazi                      3           205            205          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1198/jasa.2009.0121 is OK
- 10.1198/106186006X113430 is OK
- 10.1038/s41467-018-04608-8 is OK
- 10.1101/836650 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02055/joss.02055/10.21105.joss.02055.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@lpantano, @csoneson, @will-rowe, would one you be able to edit this submission?

**Comment by csoneson** [comment]
I can take this one

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋 @PhilBoileau - I will handle your submission. While I look for suitable reviewers, could you add DOIs to the references that are currently missing them, and look into case protection to get the right capitalization of the references (e.g., r, bioconductor, some of the journal names)? To generate a new pdf proof, just type `@whedon generate pdf` in this issue.

**Comment by csoneson** [comment]
👋 @LTLA, @fabian-s, @gabrielodom - would you be interested in reviewing this submission for the Journal of Open Source Software (JOSS)? 

`scPCA: A toolbox for sparse contrastive principal component analysis in R`
Software: https://github.com/PhilBoileau/scPCA
Paper: https://github.com/openjournals/joss-papers/blob/joss.02055/joss.02055/10.21105.joss.02055.pdf

The guidelines for JOSS reviews are available at https://joss.readthedocs.io/en/latest/reviewer_guidelines.html, and the review criteria are listed at https://joss.readthedocs.io/en/latest/review_criteria.html. 

Thanks!

**Comment by fabian-s** [comment]
I would.

**Comment by PhilBoileau** [comment]
Thank you, @csoneson! I have added the doi's, and fixed the issues with journal name/article title capitalization.

**Comment by PhilBoileau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02055/joss.02055/10.21105.joss.02055.pdf)

**Comment by PhilBoileau** [comment]
Please ignore the proof above!

**Comment by PhilBoileau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02055/joss.02055/10.21105.joss.02055.pdf)

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18129/B9.bioc.SingleCellExperiment is OK
- 10.1198/jasa.2009.0121 is OK
- 10.1198/106186006X113430 is OK
- 10.1038/s41467-018-04608-8 is OK
- 10.1101/836650 is OK
- 10.1186/gb-2004-5-10-r80 is OK
- 10.1038/nmeth.3252 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@whedon assign @fabian-s as reviewer

**Comment by whedon** [comment]
OK, @fabian-s is now a reviewer

**Comment by csoneson** [comment]
@whedon add @LTLA a reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by csoneson** [comment]
@whedon add @LTLA as reviewer

**Comment by whedon** [comment]
OK, @LTLA is now a reviewer

**Comment by csoneson** [comment]
Ok @PhilBoileau , we have our two reviewers. Thanks @fabian-s and @LTLA for accepting! I'll open the review issue where the actual review will take place.

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2079.
