### ISSUE TITLE
[PRE REVIEW]: Using drones to quantify the length of marine animals

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2056]
**Submitting author:** @egemose (<a href="http://orcid.org/0000-0002-6765-8216">Henrik Dyrberg Egemose</a>)
**Repository:** <a href="https://github.com/egemose/DroneVideoMeasure" target ="_blank">https://github.com/egemose/DroneVideoMeasure</a>
**Version:** v1.0.0
**Editor:** @kthyng
**Reviewers:** @abhishekbajpayee, @jizecn

**Author instructions**

Thanks for submitting your paper to JOSS @egemose. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kthyng.

@egemose if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.49 s (115.4 files/s, 76884.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       5           4476          10317          19136
Python                          15            212             65           1506
HTML                            28             66             20           1388
CSS                              2             60             31            356
Bourne Shell                     1             15              0            133
Markdown                         2             34              0            112
YAML                             2              1              0             24
TeX                              1              1              0             13
Dockerfile                       1              5              0             11
-------------------------------------------------------------------------------
SUM:                            57           4870          10433          22679
-------------------------------------------------------------------------------


Statistical information for the repository '2056' was gathered on 2020/02/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Henrik Dyrberg Egemo            35        112063          76351          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Henrik Dyrberg Egemo      35712           31.9          0.4               29.41
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02056/joss.02056/10.21105.joss.02056.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@egemose thanks for your submission. I recommend adding the software name in the paper title e.g. 
`DroneVideoMeasure: Using drones to quantify the length of marine animals`

**Comment by Kevin-Mattheus-Moerman** [comment]
@kthyng the authors suggested you as editor. Would you be able to edit this submission? You can likely also invite the authors/reviewers from this submission: https://github.com/openjournals/joss-reviews/issues/1825 to review this work. 
If you cannot take this I can take it myself.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @kthyng as editor

**Comment by whedon** [comment]
@kthyng has been invited to edit this submission.

**Comment by kthyng** [comment]
Yes I can edit this

**Comment by kthyng** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
Hi @egemose! I have a few questions to get started. First, is there any documentation? I didn't see any on a quick scan through your repository.

**Comment by egemose** [comment]
Hi @kthyng This is a new submission of https://github.com/openjournals/joss-reviews/issues/1654 where most of the software have been rewritten to work in docker and a browser, to ease the installation and use.

**Comment by egemose** [comment]
@kthyng I can see that I forgot to redo the manual of the old repository with the documentation. I will quickly add it.

**Comment by egemose** [comment]
@kthyng There is now documentation in the "manual" directory.

**Comment by egemose** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2056 with the following error: 

 Error reading bibliography ./paper.bib (line 40, column 1):
unexpected "t"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02056/joss.02056/10.21105.joss.02056.pdf)

**Comment by kthyng** [comment]
@egemose Ok I understand now.

I also now see that there are two Henriks working on this software! That was confusing at first.

Ok I will try to recruit our original reviewers.

**Comment by kthyng** [comment]
Hi @abhishekbajpayee and @jizecn! You were reviewers on a previous [submission](https://github.com/openjournals/joss-reviews/issues/1654) to JOSS which was paused for some code improvements. It has been resubmitted in this PRE-REVIEW issue. Are you able and willing to review it at this point?

**Comment by abhishekbajpayee** [comment]
Yes I can review.

**Comment by jizecn** [comment]
> Hi @abhishekbajpayee and @jizecn! You were reviewers on a previous [submission](https://github.com/openjournals/joss-reviews/issues/1654) to JOSS which was paused for some code improvements. It has been resubmitted in this PRE-REVIEW issue. Are you able and willing to review it at this point?

Yes, I will review too.

**Comment by kthyng** [comment]
Excellent! Thanks to both of you once again.

**Comment by kthyng** [comment]
@whedon assign @abhishekbajpayee as reviewer

**Comment by whedon** [comment]
OK, @abhishekbajpayee is now a reviewer

**Comment by kthyng** [comment]
@whedon add @jizecn as reviewer

**Comment by whedon** [comment]
OK, @jizecn is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2097.
