### ISSUE TITLE
[PRE REVIEW]: COLNA: A Python Package to Analyze Complex, Linear Networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2057]
**Submitting author:** @pstrk (<a href="http://orcid.org/0000-0002-7389-5592">Pascal Stark</a>)
**Repository:** <a href="https://github.com/IBM/complex-linear-network-analyzer" target ="_blank">https://github.com/IBM/complex-linear-network-analyzer</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewers:** @brandondube, @DiegoJRR

**Author instructions**

Thanks for submitting your paper to JOSS @pstrk. **Currently, there isn't an JOSS editor assigned** to your paper.

@pstrk if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.55 s (141.7 files/s, 85266.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                             17              1            100          21653
JavaScript                      11           2200           2239           8326
HTML                            14           1658             11           5150
Python                          19            627           1185           1437
CSS                              4            164             34            642
reStructuredText                 5            320            455            358
Markdown                         5             77              0            196
TeX                              1              1              0             68
DOS Batch                        1              9              1             28
YAML                             1              0              2              2
-------------------------------------------------------------------------------
SUM:                            78           5057           4027          37860
-------------------------------------------------------------------------------


Statistical information for the repository '2057' was gathered on 2020/02/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Lorenz K. Muller                 1            38             28            0.15
Pascal Stark                    24         29447          13443           99.85

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Lorenz K. Muller             26           68.4          0.0                7.69
Pascal Stark              15988           54.3          0.0               18.53
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-3-642-10503-6 is OK
- 10.1364/JOSAB.29.000896 is OK
- 10.1002/lpor.201100017 is OK
- 10.1038/ncomms4541 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02057/joss.02057/10.21105.joss.02057.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@danielskatz, @drvinceknight, @VivianePons, @mjsottile, could one of you edit this submission?

**Comment by arfon** [comment]
@whedon invite @arfon as editor

**Comment by whedon** [comment]
@arfon has been invited to edit this submission.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@pstrk - many thanks for your submission to JOSS. Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by pstrk** [comment]
Thank you for your message. Just looking at the list we think the following reviewers could be a good fit aquilesC, brandondube, IgorBaratta, DiegoJRR

**Comment by arfon** [comment]
@aquilesC @DiegoJRR @brandondube - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by aquilesC** [comment]
Dear @arfon , even though I would like to help, I do not have available time to do it in a timely manner. I strongly advise you to go for another reviewer. If you can't find any, ping me again and we can see what is possible.

**Comment by diversemix** [comment]
How does this work fit into to other's work in this field? 

For example `pyunicorn`  [Unified functional network and nonlinear time series analysis for complex systems science: The pyunicorn package](https://aip.scitation.org/doi/10.1063/1.4934554)

**Comment by pstrk** [comment]
> How does this work fit into to other's work in this field?
> 
> For example `pyunicorn` [Unified functional network and nonlinear time series analysis for complex systems science: The pyunicorn package](https://aip.scitation.org/doi/10.1063/1.4934554)

I was not familiar with pyunicorn before and did just quickly through the paper. I think there is some confusion about the term "complex network".  According to e.g. wikipedia complex networks are graphs with non-trivial topological features.  In our case however we model networks where the edges have complex valued weights (i.e. phase and amplitude) and are delayed (meaning it takes a number of timesteps until a signal propagtes through the edge). Our software package is focused on returning all paths through the network, leading from a set of "input nodes" to a set of "output nodes", which are both defined by the user. If there are recurrent paths (i.e. loops) in the network, our software will return the paths until the amplitude decays below a user provided threshold (loops must have gain < 1, otherwise the analysis will not converge).  We do not provide any network statistics/graph measures.

Pyunicorn, iGraph etc. are very general packages to model complex networks resp. graphs (not sure if they do support complex valued edges though), while our package is focused on a very specific type of network/graph (complex valued and delayed edges, linear nodes) and is focused on modelling the signal propagation through these kind of networks. Additionally we provide a framework that supports the use of symbolic numbers for all edge properties, that can then be set to a target value using a feed dictionary, when analyzing the network or when calculating output signals.

**Comment by brandondube** [comment]
@arfon I can review -- anything I need to tell whedon?

**Comment by arfon** [comment]
@whedon add @brandondube as reviewer

**Comment by whedon** [comment]
OK, @brandondube is now a reviewer

**Comment by arfon** [comment]
> @arfon I can review -- anything I need to tell whedon?

:zap: thanks @brandondube! I'd like to find a second reviewer before I open up the actual review issue with the checklist to work through.

**Comment by DiegoJRR** [comment]
@arfon  I can also review 👍 (Although its my first time)

**Comment by arfon** [comment]
@whedon add @DiegoJRR as reviewer

**Comment by whedon** [comment]
OK, @DiegoJRR is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2073.

**Comment by arfon** [comment]
@brandondube, @DiegoJRR - please head over to #2073 where the actual review will take place.
