### ISSUE TITLE
[PRE REVIEW]: covtobed: a simple and fast tool to extract coverage tracks from BAM files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2058]
**Submitting author:** @telatin (<a href="http://orcid.org/0000-0001-7619-281X">Andrea Telatin</a>)
**Repository:** <a href="https://github.com/telatin/covtobed/" target ="_blank">https://github.com/telatin/covtobed/</a>
**Version:** v1.0.0
**Editor:** @will-rowe
**Reviewers:** @jdeligt, @brentp

**Author instructions**

Thanks for submitting your paper to JOSS @telatin. **Currently, there isn't an JOSS editor assigned** to your paper.

@telatin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (321.8 files/s, 43989.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                              2             92             44            683
C/C++ Header                     2             87            184            369
Markdown                         4             51              0            145
TeX                              1              5              0            117
Bourne Shell                     3             17             12             70
YAML                             1              0              0             22
Dockerfile                       1              2              0             14
-------------------------------------------------------------------------------
SUM:                            14            254            240           1420
-------------------------------------------------------------------------------


Statistical information for the repository '2058' was gathered on 2020/02/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andrea Telatin                  14          1533             70           95.36
gbirolo                          4            37             41            4.64

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andrea Telatin             1435           93.6          0.0               13.66
gbirolo                      24           64.9          0.0               29.17
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btq033 is OK
- 10.1093/bioinformatics/btx699 is OK
- 10.1038/nrg3642 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.1093/bioinformatics/btr174 is OK
- 10.1016/j.hrthm.2018.11.015 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02058/joss.02058/10.21105.joss.02058.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@csoneson, @will-rowe, @majensen, @lpantano could one of you edit this submission? Also can you judge if this work is significant enough to pass our "minor-utility" check?

**Comment by Kevin-Mattheus-Moerman** [comment]
@telatin thanks for your submission. I recommend that you reformulate your readme to be a bit more suitable to somebody from outside of this domain (like myself). It contains 2 undefined acronyms for instance. Perhaps create a lay-persons summary at the top so it is clear what this software is for to new comers. 
Furthermore if this work is reviewed at a later stage our reviewers will demand clear contributing guidelines. I have not found these from quickly looking through the readme. Perhaps you can consider adding clear contributing guidelines at this point while we determine the suitability of this software for JOSS. Thanks.

**Comment by will-rowe** [comment]
Good morning. I've been looking at this submission this morning and I'm afraid we may class this as a minor-utility. Whilst I think this is a useful tool and one which I would use to save myself bedtools + awk scripting, I don't think there is enough functionality here to pass our submission requirements.

I'd appreciate it if either @lpantano, @majensen or @csoneson could take a quick look and confirm this.

Best,

Will

**Comment by lpantano** [comment]
It seems a nice tool, if it is actually super fast compare to others like bedtools or mosdepth, it could be a good improvement. Otherwise, I could agree is minor.

**Comment by telatin** [comment]
Thanks @will-rowe and @lpantano  for your first feedback!

We were aware of this possible limitation, yet we were also thinking that "covtobed" fits into a broad set of common tasks, and different bioinformatics applications this specificity was somehow desirable. So we focused on supporting streaming and speed to have a reliable brick for multiple pipelines.

**Comment by will-rowe** [comment]
Hi @telatin. Thanks for your reply. I've been playing with covtobed again this morning - it is a good utility and is very nicely packaged and documented.

Of course you and @lpantano are right in that the speed makes this appealing. I was testing against bedtools (`bedtools genomecov -ibam a.bam -bg`), which gives the same output to `covtobed a.bam`. covtobed was roughly twice as fast (note: there were some output inconsistencies but that seems to be due to just using defaults for both programs) and allows streaming (which bedtools doesn't for genomecov at the moment).

Maybe if you could add some benchmarking to your paper and that would satisfy our concerns that this is a minor utility?

I have an alternative (and somewhat cheeky suggestion). Adding some functionality to generate a coverage plot from the bed file would make this an indispensable tool to many bioinformaticians. Something along the lines of the image in your README would be fantastic. This is of course only a suggestion and I'd be happy to put this paper into review with only the benchmarking data added

**Comment by telatin** [comment]
@will-rowe I really appreciate the time you dedicated to this tool!

To be fair, both suggestions are valuable, and I'll be glad to try addressing one or both. 
This will probably take some time, is it better to close this issue and resubmit mentioning the issue later or is it possible to keep the issue open in the meantime?

**Comment by will-rowe** [comment]
You're welcome @telatin.

Let's keep this issue as it's easiest to keep track of the conversation history. I'm happy to assign myself as editor and you can ping this thread when you'd like me to take another look and we can take it from there?

**Comment by will-rowe** [comment]
@whedon assign @will-rowe as editor

**Comment by whedon** [comment]
OK, the editor is @will-rowe

**Comment by kthyng** [comment]
@will-rowe and @telatin Sounds great what you've planned. I will go ahead and add the "paused" label for now to indicate your decision. When ready to go again, it is easy to remove.

**Comment by telatin** [comment]
Hello!
We tested our tool comparing its speed with *bedtools* and *mosdepth*. With either small genomes or large genomes  having a small targets (*e. g.* Human gene panels), *covtobed* outperforms both tools (up to 60X faster). In whole exome sequencing *covtobed* is 3-5X slower than *mosdepth* but 2-4X faster than *bedtools*.

We believe that this combined with peculiar features (covtobed is available for mac, allows to split the coverage by strand and works in pipes) makes the tool a useful addition in the bioinformatician's toolshed. 

Hope you agree :)

**Comment by will-rowe** [comment]
Hi @telatin. Many thanks for the update. I think this sounds great and I'd be happy to put it out to review. Let me find some reviewers

**Comment by will-rowe** [comment]
@whedon assign @will-rowe as editor

**Comment by whedon** [comment]
OK, the editor is @will-rowe

**Comment by will-rowe** [comment]
Hi @brentp. Would you be interested in reviewing this submission for JOSS?

**Comment by will-rowe** [comment]
Hi @jdeligt - would you also be interested in reviewing this submission?

**Comment by jdeligt** [comment]
Sure, happy to help

**Comment by brentp** [comment]
yes

**Comment by will-rowe** [comment]
Brilliant. Thanks everyone. I'll start the review now and you'll shortly receive links to the new review issue - let me know if any of you need further instruction on the JOSS review process.

**Comment by will-rowe** [comment]
@whedon assign @jdeligt as reviewer

**Comment by whedon** [comment]
OK, @jdeligt is now a reviewer

**Comment by will-rowe** [comment]
@whedon add @brentp as reviewer

**Comment by whedon** [comment]
OK, @brentp is now a reviewer

**Comment by will-rowe** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2119.
