### ISSUE TITLE
[PRE REVIEW]: fleck: Fast approximate light curves for starspot rotational modulation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2059]
**Submitting author:** @bmorris3 (<a href="http://orcid.org/0000-0003-2528-3409">Brett Morris</a>)
**Repository:** <a href="https://github.com/bmorris3/fleck" target ="_blank">https://github.com/bmorris3/fleck</a>
**Version:** v0.1
**Editor:** @dfm
**Reviewers:** @nespinoza, @rodluger

**Author instructions**

Thanks for submitting your paper to JOSS @bmorris3. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dfm.

@bmorris3 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (440.2 files/s, 54713.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          13            451            852           1111
reStructuredText                16            337            186            904
DOS Batch                        1             21              1            150
make                             1             22              5            106
TeX                              1              4              0            104
YAML                             3             31             59             64
Markdown                         1             12              0             54
-------------------------------------------------------------------------------
SUM:                            36            878           1103           2493
-------------------------------------------------------------------------------


Statistical information for the repository '2059' was gathered on 2020/02/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Brett Morris                    23          2695            281          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Brett Morris               2414           89.6          3.3               20.71
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/mnras/sty568 is OK
- 10.1093/mnras/stz199 is OK
- 10.3847/1538-3881/aabc4f is OK

MISSING DOIs

- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02059/joss.02059/10.21105.joss.02059.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@dfm, @xuanxu, can one of you edit this submission?

**Comment by dfm** [comment]
Sure! I'm happy to edit. I'm mostly offline for the next few days, but I'll start the process before the end of the week. 

@bmorris3: take a look at [this list of potential reviewers](https://bit.ly/joss-reviewers) and let me know if you think anyone would be an especially good fit (but please don't @ them!).

**Comment by dfm** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by bmorris3** [comment]
Thanks @dfm! Some potential reviewers include Cadair, nespinoza, ngoldbaum, dhuppenkothen.

**Comment by dfm** [comment]
:wave: @nespinoza, would be you available and willing to review this submission to JOSS? Thanks!

**Comment by dfm** [comment]
:wave: @rodluger, would be you available and willing to review this submission to JOSS? Thanks!

**Comment by nespinoza** [comment]
Hey @dfm  --- sure can do!

**Comment by dfm** [comment]
@whedon assign @nespinoza as reviewer

**Comment by whedon** [comment]
OK, @nespinoza is now a reviewer

**Comment by dfm** [comment]
Thanks @nespinoza!

**Comment by bmorris3** [comment]
Hey @dfm, is there anything I need to do to link this paper to my AAS Journals submission?

**Comment by dfm** [comment]
@bmorris3: Thanks for letting us know. We will perform this review independently of AAS, so you should keep us posted on the status of that review. We will wait until both reviews are finished to publish the paper because the two will be linked at the end. Let me know if you have any questions!

**Comment by dfm** [comment]
@rodluger: any chance you're available to review this submission? (It sounded like you could via email, but I wanted to confirm)

**Comment by rodluger** [comment]
Yes, happy to do it. Can you point me to reviewer instructions?

**Comment by dfm** [comment]
@rodluger: Thanks!

Here are the instructions: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

You'll see more in the review thread...

**Comment by dfm** [comment]
@whedon add @rodluger as reviewer

**Comment by whedon** [comment]
OK, @rodluger is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2103.

**Comment by dfm** [comment]
@bmorris3, @rodluger, @nespinoza: The review is now started over in https://github.com/openjournals/joss-reviews/issues/2103. Let's head that way. Let me know if you have any questions!
