### ISSUE TITLE
[PRE REVIEW]: Varistran: Anscombe's variance stabilizing transformation for RNA-seq gene expression data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#206]
**Submitting author:** @pfh (<a href="http://orcid.org/0000-0002-3980-268X">Paul Harrison</a>)
**Repository:** <a href="https://github.com/MonashBioinformaticsPlatform/varistran" target ="_blank">https://github.com/MonashBioinformaticsPlatform/varistran</a>
**Version:** v1.0.1
**Editor:** @brainstorm
**Reviewer:** @roryk

**What this issue is for**

Thanks for submitting your paper to JOSS @pfh. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: @noamross would this submission be suitable for rOpenSci?

**Comment by noamross** [comment]
No, as this is primarily a statistical method implementation, it's out of scope for us.

**Comment by arfon** [comment]
> No, as this is primarily a statistical method implementation, it's out of scope for us.

OK thanks for confirming.

**Comment by arfon** [comment]
👋 @brainstorm - would you be willing to edit this submission for JOSS?

**Comment by brainstorm** [comment]
I've been having a look at it for a couple of days but I'm in ;)

@whedon review

**Comment by arfon** [comment]
@whedon assign @brainstorm as editor

**Comment by whedon** [comment]
OK, the editor is @brainstorm

**Comment by arfon** [comment]
> I've been having a look at it for a couple of days but I'm in ;)

@brainstorm 👍 thanks. Next step would be to find a reviewer for this.

**Comment by brainstorm** [comment]
Perhaps @roryk would be interested?

**Comment by roryk** [comment]
This looks great, would definitely be doing for reviewing it. @mikelove would be another good pick but he might be super busy.

**Comment by mikelove** [comment]
I can review if needed

**Comment by arfon** [comment]
@brainstorm - I'll let you drive @whedon but you need the following two commands to start the process:

```
@whedon assign @roryk as reviewer
@whedon start review magic-word=bananas
```
☝️ these need to be issued as separate commands. @whedon will then open a new review issue for @roryk to work through.

**Comment by brainstorm** [comment]
@whedon assign @roryk as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @roryk

**Comment by brainstorm** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/257. Feel free to close this issue now!
