### ISSUE TITLE
[REVIEW]: scTree: An R package to generate antibody-compatible classifiers from single-cell sequencing data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2061]
**Submitting author:** @jspaezp (<a href="http://orcid.org/0000-0002-0065-1474">J. Sebastian Paez</a>)
**Repository:** <a href="https://github.com/jspaezp/sctree" target ="_blank">https://github.com/jspaezp/sctree</a>
**Version:** 0.0.5
**Editor:** @will-rowe
**Reviewer:** @mschubert, @jenzopr
**Archive:** <a href="https://doi.org/10.5281/zenodo.3766467" target="_blank">10.5281/zenodo.3766467</a>

## Status

[![status](https://joss.theoj.org/papers/4316d75e1e458003f7acfee08fd3922b/status.svg)](https://joss.theoj.org/papers/4316d75e1e458003f7acfee08fd3922b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4316d75e1e458003f7acfee08fd3922b"><img src="https://joss.theoj.org/papers/4316d75e1e458003f7acfee08fd3922b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4316d75e1e458003f7acfee08fd3922b/status.svg)](https://joss.theoj.org/papers/4316d75e1e458003f7acfee08fd3922b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jspaezp/sctree" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mschubert & @jenzopr, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @will-rowe know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jspaezp/sctree">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jspaezp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jspaezp/sctree">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jspaezp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mschubert, @jenzopr it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s11634-016-0276-4 is OK
- 10.1093/bioinformatics/btq134 is OK
- 10.18637/jss.v077.i01 is OK
- 10.1101/335000 is OK
- 10.1038/nmeth.4197 is OK
- 10.1038/s41467-018-03405-7 is OK
- 10.1016/j.cell.2018.05.061 is OK
- 10.1038/nbt.3519 is OK
- 10.1101/gr.209601.116 is OK
- 10.1186/s13059-014-0550-8 is OK
- 10.1093/bioinformatics/btp616 is OK
- 10.1038/nbt.4096 is OK
- 10.1038/nbt.2859 is OK
- 10.1038/ncomms14049 is OK
- 10.1093/bioinformatics/bts635 is OK
- 10.1002/cyto.a.22096 is OK
- 10.1002/0471142735.im22f08s69 is OK
- 10.1038/s41592-019-0535-3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02061/joss.02061/10.21105.joss.02061.pdf)

**Comment by will-rowe** [comment]
Hi @jspaezp - I'm just checking in here. Looks as though you've got some good comments from @mschubert and @jenzopr. Are you happy to continue addressing these and then to ping this thread once you'd like us to take another look?

**Comment by jspaezp** [comment]
Hello @will-rowe, sorry for the late reply, had not seen the activity on this thread! Yes indeed I am interesting and have been working on the changes, I will let you know as soon as I believe we have addressed everything that was mentioned.

@natallah

**Comment by jenzopr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02061/joss.02061/10.21105.joss.02061.pdf)

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by natallah** [comment]
@jenzopr   @jspaezp 
The proof overall looks really good!  One thing we  need to figure out is why Figure 3 in the paper.md is showing up labeled as Figure 1 in the pdf.  We definitely do not want to have two figure 1s!

**Comment by jspaezp** [comment]
@natallah 
Oddly enough, when previewing the paper using the `Whedon paper preview service`, the figure is correctly labelled.

here is the link to the current preview ...
https://whedon.theoj.org/preview?id=8b96fc6483534375133ccd09

**Comment by jenzopr** [comment]
I can confirm that. The link sent by @jspaezp does not lead to the paper immediately, but if you use the service with the scTree repo URL as input, the figure labels are correct.

**Comment by jenzopr** [comment]
I accidentally hit the Close and Comment button 🙈 Sorry for that!

**Comment by arfon** [comment]
@natallah - Pandoc knows how to number figures already so this change should fix your numbering issue: https://github.com/jspaezp/sctree/pull/13

**Comment by jspaezp** [comment]
hello @arfon,

I have accepted the figure label changes to master and updated all the active branches, Thanks for the PR. I also checked and they seem to render correctly using pandoc locally (`pandoc paper.md --filter pandoc-citeproc --bibliography bibliography.bib -o paper_$(echo $(date +%H%M)_$(date +%d%m%Y)).pdf`) .

Kindest wishes,
Sebastian

@natallah

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02061/joss.02061/10.21105.joss.02061.pdf)

**Comment by jenzopr** [comment]
Lgtm! :tada:

**Comment by jspaezp** [comment]
I just pushed a commit that fixes a couple of minor typos and grammar details in the paper :D 

https://github.com/jspaezp/sctree/commit/7112e2e5872fb241b3781024e3d33135379156b0
I feel like it should be good to go :D 
@natallah

**Comment by jspaezp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02061/joss.02061/10.21105.joss.02061.pdf)

**Comment by natallah** [comment]
@jspaezp  This looks great!

**Comment by mschubert** [comment]
I apologize for the delay in updating my checklist, I was not feeling well the last 10 days (not sure if this virus or another).

Great work on this in the meantime @jspaezp! This all looks good to me now. I particularly like the more concise "mission statement" of the package.

<hr>

Here are some very minor, last discretionary changes that I do not consider acceptance blockers:
* Does JOSS have an opinion about snapshotting cited web pages to keep links accessible?
* Seurat tutorial (4th ref from bottom) does not provide a link
* There is a number of `R CMD check` warnings on Travis that could be fixed

**Comment by jspaezp** [comment]
hello @mschubert I have modified the links in the bibliography.bib file and (hypothetically) fixed the key that made the link not show up in the references section.

regarding the check fixes ... for the most part its issues with the naming of arguments and patterns for s3 methods, which after trying would break A LOT of the checks and examples in the documentation, so I believe it should be done on changing to a major version. We would definitely add it to the milestones for v2.0. In addition the example data (another warn in the package check, due to the size) could be fixed by generating a data package independently and having it as a required dependency for automated testing but the warn would still appear in that one and make reasonably harder to set up the travis automated testing.

@whedon generate pdf 
@natallah

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
@jspaezp commands to @whedon need to be either at the start of a message or standalone ☝️

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02061/joss.02061/10.21105.joss.02061.pdf)

**Comment by natallah** [comment]
It looks good to me!

**Comment by arfon** [comment]
@jspaezp - I'm not sure if you want to do anything about this margin issue on this 👇figure/example?

<img width="725" alt="Screen Shot 2020-04-13 at 11 14 54 AM" src="https://user-images.githubusercontent.com/4483/79132271-06b08280-7d78-11ea-8ef9-5ffdb834f836.png">

**Comment by jspaezp** [comment]
Hello @arfon ,

I was discussing with @natallah on what the best way to handle it would be.
On one hand I want it to be faithful to actual code output, but it going over the margins is not really useful information.
I am not familiar with latex, (alternative 1) is there a way to make the font on code chunks smaller for it to fit ?
We could also (alternative 2) just crop the content to fit the margins of the page and would resemble well enough the output of a terminal.

Highly appreciating your feedback on what would be the best approach,
Sebastian

**Comment by arfon** [comment]
I think the second approach (cropping content) is probably the best one.

**Comment by jspaezp** [comment]
Hello @arfon,

I cropped it in commit jspaezp/sctree@ac02e43abb49f9f8bf228b900e9f4178fa076273

@natallah

**Comment by jspaezp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02061/joss.02061/10.21105.joss.02061.pdf)

**Comment by natallah** [comment]
@arfon @jspaezp the proof looks good to me and I have no changes to suggest.

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s11634-016-0276-4 is OK
- 10.1093/bioinformatics/btq134 is OK
- 10.18637/jss.v077.i01 is OK
- 10.1016/j.cll.2007.05.001 is OK
- 10.1186/s13059-014-0550-8 is OK
- 10.1093/bioinformatics/btp616 is OK
- 10.1038/nbt.4096 is OK
- 10.1038/nbt.2859 is OK
- 10.1038/ncomms14049 is OK
- 10.1002/cyto.a.22096 is OK
- 10.1002/0471142735.im22f08s69 is OK
- 10.1038/s41592-019-0535-3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@jspaezp - I made a couple of tiny formatting improvements in https://github.com/jspaezp/sctree/pull/14.

At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by jspaezp** [comment]
I think it is done, I used Zenodo for the upload,

@arfon and @natallah 

https://doi.org/10.5281/zenodo.3766467

Let me know if further actions are required.
Kindest wishes and appreciating your help,
Sebastian

**Comment by arfon** [comment]
@jenzopr - could you merge https://github.com/jspaezp/sctree/pull/14 please?

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3766467 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3766467" target="_blank">10.5281/zenodo.3766467</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s11634-016-0276-4 is OK
- 10.1093/bioinformatics/btq134 is OK
- 10.18637/jss.v077.i01 is OK
- 10.1016/j.cll.2007.05.001 is OK
- 10.1186/s13059-014-0550-8 is OK
- 10.1093/bioinformatics/btp616 is OK
- 10.1038/nbt.4096 is OK
- 10.1038/nbt.2859 is OK
- 10.1038/ncomms14049 is OK
- 10.1002/cyto.a.22096 is OK
- 10.1002/0471142735.im22f08s69 is OK
- 10.1038/s41592-019-0535-3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1432

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1432, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1254389664695320576) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1433
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02061](https://doi.org/10.21105/joss.02061)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@mschubert, @jenzopr - many thanks for your reviews here and to @will-rowe for editing this submission ✨ 

@jspaezp - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02061/status.svg)](https://doi.org/10.21105/joss.02061)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02061">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02061/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02061/status.svg
   :target: https://doi.org/10.21105/joss.02061
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02061/status.svg)](https://doi.org/10.21105/joss.02061)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by jenzopr** [comment]
Congrats!!

**Comment by natallah** [comment]
Thank you for all your comments and suggestions!  You all have made it a better package and submission! @will-rowe @jspaezp @jenzopr @arfon
