### ISSUE TITLE
[REVIEW]: Soss: Code Generation for Probabilistic Programming in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2062]
**Submitting author:** @cscherrer (<a href="http://orcid.org/0000-0002-1490-0304">Chad Scherrer</a>)
**Repository:** <a href="https://github.com/cscherrer/Soss.jl" target ="_blank">https://github.com/cscherrer/Soss.jl</a>
**Version:** v0.9.0
**Editor:** @melissawm
**Reviewer:** @kose-y, @malmaud
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/703afc01ce7a4f97f3947dc7b5255610/status.svg)](https://joss.theoj.org/papers/703afc01ce7a4f97f3947dc7b5255610)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/703afc01ce7a4f97f3947dc7b5255610"><img src="https://joss.theoj.org/papers/703afc01ce7a4f97f3947dc7b5255610/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/703afc01ce7a4f97f3947dc7b5255610/status.svg)](https://joss.theoj.org/papers/703afc01ce7a4f97f3947dc7b5255610)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/cscherrer/Soss.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kose-y & @malmaud, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @melissawm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cscherrer/Soss.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@cscherrer) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cscherrer/Soss.jl">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@cscherrer) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kose-y, @malmaud it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1145/3314221.3314642 is OK
- 10.5281/zenodo.3541506 is OK
- 10.7717/peerj-cs.103 is OK
- 10.21105/joss.01143 is OK
- 10.5281/zenodo.2647458 is OK
- 10.1137/141000671 is OK
- 10.7717/peerj-cs.103 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02062/joss.02062/10.21105.joss.02062.pdf)

**Comment by kose-y** [comment]
Hi @cscherrer, the link to the document on the badge on your repository does not seem to work.

https://cscherrer.github.io/Soss.jl/stable
https://cscherrer.github.io/Soss.jl/dev

Is there another way to view the web version of documentation?

**Comment by kose-y** [comment]
SymPy is listed twice in the references of the paper.

**Comment by cscherrer** [comment]
Thanks @kose-y !

Documentation is currently limited to the README. I do have some slides and a PROBPROG submission I could point to, but generated docs aren't yet set up.

Thanks for catching the SymPy double-citation, I'll get that fixed. Feel free to add issues directly in the repo if you like, or I can add them as we go :)

**Comment by kose-y** [comment]
I have checked and read documentations, your outside slides, and PROBPROG submission. I think this is a fantastic package resolving the "three-language problem" often arising from Bayesian inference (Although I'm not a Bayesian, I have used JAGS in a course before, and have seen how TensorFlow Probability and PyMC3 works.). However, the review process of JOSS is checklist-driven, and I have to comment based on the checklist above. 

- On a statement of need: I think the "three-language problem" claim deserves to be included in the software paper as well as `README.md`. 
- Functionality documentation: current information given on `README.md` is weak. For example, I could not figure out what `codegen` means from `README.md` alone. I think including the description from the PROBPROG submission would help.
- Automated tests: All I could find was a test checking if `README.md` is successfully generated from `README.jmd`. I think it should check if each functionality works correctly.
- Community guidelines: It is required in the documentation.

**Comment by danielskatz** [comment]
👋 @cscherrer - it seems like this review is waiting for your response to @kose-y's comments above.

**Comment by cscherrer** [comment]
Thanks for bumping this @danielskatz !

Hi @kose-y, thank you for your helpful comments; I'm sorry to not have responded sooner. This project is my first experience with both Julia's documentation and test system, so the software engineering side of this is taking me some time. The [docs|dev](https://cscherrer.github.io/Soss.jl/dev) button now works, but there's nothing really there yet. I should have some time to populate this somewhat this weekend.

I agree there also need to be more tests; this will be an ongoing effort.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arfon** [comment]
:wave: @malmaud, just a friendly check-in to see how things are going with your review?

**Comment by malmaud** [comment]
I had paused since it sounds like we're waiting for @cscherrer to add some tests and docs.

**Comment by arfon** [comment]
> I had paused since it sounds like we're waiting for @cscherrer to add some tests and docs.

👍got it. Thanks.

**Comment by cscherrer** [comment]
Thanks for checking in @arfon, I'll ping the reviewers when the tests and docs are ready for review

**Comment by arfon** [comment]
:wave: @cscherrer - have you managed to make any progress since April? JOSS is now reopen for submissions so we're actively trying to wrap up existing reviews.

:wave: @malmaud - do you think you might be able to start work on your review sometime in the next few weeks?

**Comment by malmaud** [comment]
My understanding was to pause until @cscherrer indicated he's ready for a review. I'm still on-board with that plan and will be available to review.

**Comment by arfon** [comment]
> I'm still on-board with that plan and will be available to review.

Got it. Thanks!

**Comment by cscherrer** [comment]
Thanks @arfon and @malmaud . We've been digging into the Julia documentation system, and now have a good start on documentation (previously it had been just the README). I'm hoping to have this ready to move forward within a few weeks. We can keep this paused until then. Please let me know if we need a hard deadline or this delay causes some problem for you; I could instead cancel and re-apply when we're ready if that is somehow better for you.

**Comment by arfon** [comment]
:wave: @cscherrer - just checking in to see how things are going here?

**Comment by arfon** [comment]
@cscherrer - do you think you will have the time to restart working on this submission within the next few weeks or so? If not, in order to respect the reviewers' time and availability committment, I will propose to close (reject) this submission, and invite a resubmission at a later point in time.

**Comment by cscherrer** [comment]
Thanks @arfon . I think resubmission would be fine. We have some changes to our SymPy approach that we should update anyway. This was my first JOSS submission with the current system; next time I'll work through the checklist before hitting submit. Thanks to everyone here for your time.

**Comment by arfon** [comment]
OK thanks @cscherrer.  I'll go ahead and reject now but please do feel free to resubmit again in the future.

@kose-y - many thanks for your efforts on the review here. I'm sorry this paper didn't make it through the review process.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
