### ISSUE TITLE
[PRE REVIEW]: `psi-collect`: A Python module for post-storm image collection and cataloging

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2064]
**Submitting author:** @ebgoldstein (<a href="http://orcid.org/0000-0001-9358-1016">Evan B Goldstein</a>)
**Repository:** <a href="https://github.com/UNCG-DAISY/psi-collect" target ="_blank">https://github.com/UNCG-DAISY/psi-collect</a>
**Version:** v0.6
**Editor:** @kbarnhart
**Reviewers:** @katmratliff, @conlin-matt, @chrisleaman

**Author instructions**

Thanks for submitting your paper to JOSS @ebgoldstein. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kbarnhart.

@ebgoldstein if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2064 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.14 s (387.4 files/s, 30452.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          21            574            388           1237
Markdown                        11            169              0            502
HTML                             2             65             25            404
GLSL                             2              0              0            176
YAML                             5             21             40            127
Sass                             1             24              0             98
CSS                              1             22              0             94
TeX                              1             11              0             90
INI                              2             10              0             72
XML                              7              0              0             70
JSON                             1              0              0             25
TOML                             1             17             43             19
-------------------------------------------------------------------------------
SUM:                            55            913            496           2914
-------------------------------------------------------------------------------


Statistical information for the repository '2064' was gathered on 2020/02/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Evan B. Goldstein                1             0            118            4.77
Matmorcat                        7          2336             19           95.23

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Matmorcat                  2199           94.1          0.0               13.32
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.6084/m9.figshare.11604192.v1 is OK
- 10.1002/2016GL071213 is OK
- 10.1002/2015JF003634 is OK
- 10.1109/TGRS.2013.2277092 is OK
- 10.1145/2556420.2556790 is OK
- 10.1142/9789814689977_0250 is OK
- 10.1109/OCEANS.2018.8604932 is OK
- 10.1142/9789811204487_0124 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by ebgoldstein** [comment]
Possible reviewers: Katherine Ratliff, Chris Leaman, Dylan Anderson,  Matt Conlin, Josh Simmons

**Comment by kthyng** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by ebgoldstein** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02064/joss.02064/10.21105.joss.02064.pdf)

**Comment by kbarnhart** [comment]
@ebgoldstein thanks for recommending reviewers. I will work on getting two or three reviewers for this submission. Once I've gotten a few reviewers, we will close this issue and start the review on a new dedicated review issue. 

A couple of comments from me.

1. I would recommend adding a bit more motivation to the paper.md. Based on our conversation at AGU I know that there many qualities of this package that make collection and cataloging of images _way easier_, probably more appropriately described as _actually possible_. This doesn't come through clearly in the paper. I would recommend expanding the statement of need and/or adding a section that focuses on challenges to accessing this dataset that sets up the statement of need. 

2. Reference `Madore2018` needs and `@` in front.

**Comment by ebgoldstein** [comment]
i corrected the madore ref, and will work on adding more motivation.
@whedon generate pdf

**Comment by kbarnhart** [comment]
:wave: @katmratliff @chrisleaman @anderdyl @conlin-matt and @simmonsja would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue that I use to coordinate reviewers. Once there are sufficient reviewers (usually 2-3), I will open a new issue where the review will take place.

If you are not able, please let me know if you have recommendations for other reviewers. Please recommend without mentioning a handle (e.g., you would refer to me as @ kbarnhart instead of @kbarnhart). This way we attempt to reduce the number of people who are subscribed to this thread.

**Comment by katmratliff** [comment]
@kbarnhart I am willing to review.

**Comment by conlin-matt** [comment]
Hi @kbarnhart- I'm happy to review as well.

**Comment by chrisleaman** [comment]
@kbarnhart I’m happy to review 👍

**Comment by simmonsja** [comment]
Hi @kbarnhart I would be very happy to review too!

**Comment by kbarnhart** [comment]
thanks @katmratliff @conlin-matt @chrisleaman and @simmonsja for your rapid and enthusiastic interest! I think three reviewers is sufficient, and am going to select based on response order. 

I'll now assign @katmratliff @conlin-matt @chrisleaman as reviewers, and then transition this submission from the PRE-REVIEW stage to the REVIEW stage on another issue.

**Comment by kbarnhart** [comment]
@whedon assign @katmratliff as reviewer

**Comment by kbarnhart** [comment]
@whedon add @conlin-matt as reviewer

**Comment by whedon** [comment]
OK, @conlin-matt is now a reviewer

**Comment by kbarnhart** [comment]
@whedon add @chrisleaman as reviewer

**Comment by whedon** [comment]
OK, @chrisleaman is now a reviewer

**Comment by kbarnhart** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2075.
