### ISSUE TITLE
[PRE REVIEW]: Expectations.jl: Quick and Accurate Expectation Operators in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2065]
**Submitting author:** @arnavs (<a href="http://orcid.org/0000-0003-0074-7908">Arnav Sood</a>)
**Repository:** <a href="https://github.com/QuantEcon/Expectations.jl" target ="_blank">https://github.com/QuantEcon/Expectations.jl</a>
**Version:** v1.2.0
**Editor:** @VivianePons
**Reviewers:** @odow, @pkofod

**Author instructions**

Thanks for submitting your paper to JOSS @arnavs. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @melissawm.

@arnavs if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.02 s (1050.8 files/s, 53013.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                            7             84             73            367
Markdown                         4             71              0            160
TOML                             3             26              1             89
YAML                             4             14              8             73
TeX                              1              2              0             40
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            20            197             82            730
-------------------------------------------------------------------------------


Statistical information for the repository '2065' was gathered on 2020/02/03.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.2647458 is OK

MISSING DOIs

- https://doi.org/10.2307/1879403 may be missing for title: Economics of Information and Job Search
- https://doi.org/10.1093/imanum/drv002 may be missing for title: Fast computation of Gauss quadrature nodes and weights on the whole real line

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02065/joss.02065/10.21105.joss.02065.pdf)

**Comment by arnavs** [comment]
This references pkofod's code (Patrick Kofod Mogensen), so he would be a great reviewer. juliohm, metbesancon, and odow also look related.

**Comment by arnavs** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.2307/1879403 is OK
- 10.1093/imanum/drv002 is OK
- 10.5281/zenodo.2647458 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@VivianePons Can you take a look at this submission? I'd ask you to be the editor if we take it on.

@arnavs Thank you for your submission! The editorial board at JOSS is currently working on improved guidelines for in-scope submissions. We haven't finished, but we plan to start using some metrics to help guide if a submission passes some minimum bars to be considered a "large enough" contribution to be considered for JOSS, of course a question at any journal. Your submission is a bit on the low end for lines of code. This is not disqualifying, but it does mean that it would help if you were to give some extra motivation and understanding for the editors here who are not necessarily experts in your domain as to why your submission is a large enough contribution for its own publication. Thanks.

**Comment by arnavs** [comment]
Thanks @kthyng, will make sure to give that extra emphasis in the paper.

**Comment by VivianePons** [comment]
No problem!

**Comment by kthyng** [comment]
@arnavs Yes this would be excellent to add to the paper, but also please provide the information here when you have it in case there is some discussion to be had.

**Comment by kthyng** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by arnavs** [comment]
@kthyng Sure. So the crux is that many statistical problems require taking an expectation of some random variable. This comes up all the time in various domains (economics, chemistry, physics, etc.) 

Julia has really great support for distribution objects. But given one of those distribution objects (say, `d = Normal()`), there's really no easy way (besides drawing a large sample and averaging) to answer questions like "what is the expected value of `sin(x)` where `x` is drawn from `d`?)

What we do in this package is create operators `E = expectation(d)`, where you can go `E(x -> sin(x))`, etc. The operators themselves are computed with Gaussian quadrature (specialized for various distributions, like `Exponential`, `Erlang`, `Beta`, etc.) We referred to @pkofod's `DistQuads.jl` library for the underlying calls to the quadrature library. 

These operators are more efficient, reusable, notationally clear, and highly accurate. Instead of taking a sample of `10^6` to compute an expectation, you can just multiply two vectors of size 32. 

Hope this helps.

**Comment by VivianePons** [comment]
@kthyng From what I understand, the code, even if not big, is quite meaningful and implements some needed mathematics. I believe we can consider it for submission and move forward. Of course, the final decision will depend on the reviewers comments. Do you agree?

**Comment by kthyng** [comment]
@VivianePons Sounds good, please take over from here.

**Comment by VivianePons** [comment]
@arnavs In your message, you mention "community input". Could you tell me more about current usage of your package? (And maybe add it to the paper if it's relevant)

**Comment by arnavs** [comment]
@VivianePons We had a recent request from a user for the `Erlang` distribution, so I added that in. The package is used in the [QuantEcon lecture notes](julia.quantecon.org), and was also used as a dependency for a package `AdaptiveGaussianProcesses.jl` (although I think it may not be used in the latest version.)

Will add this to the paper. thanks for the suggestion.

**Comment by VivianePons** [comment]
Hi @pkofod you were suggested as a potential reviewer for this submission into JOSS (The Journal of Open Source Software), would you be interested in carrying it out? 

JOSS is a free, open-source, community driven and developer-friendly online journal
(no publisher is seeking to raise revenue from the volunteer labor of researchers!).

The review process at JOSS is unique: it is open and author-reviewer-editor conversations
are encouraged.

JOSS reviews involve downloading and installing the software, and inspecting the repository
and submitted paper for key elements. See https://joss.readthedocs.io/en/latest/review_criteria.html

Editors and reviewers post comments on the Review issue, and authors respond to the comments and improve their submission until acceptance (or withdrawal, if they feel unable to
satisfy the review).

Thank you for your consideration!

**Comment by arnavs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02065/joss.02065/10.21105.joss.02065.pdf)

**Comment by VivianePons** [comment]
@whedon assign @odow as reviewer

**Comment by whedon** [comment]
OK, @odow is now a reviewer

**Comment by arnavs** [comment]
@whedon assign @pkofod as reviewer 

(@VivianePons --- I checked with him on Slack and he was amenable.)

**Comment by whedon** [comment]
I'm sorry @arnavs, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by VivianePons** [comment]
@whedon add @pkofod as reviewer

**Comment by whedon** [comment]
OK, @pkofod is now a reviewer

**Comment by VivianePons** [comment]
> (@VivianePons --- I checked with him on Slack and he was amenable.)

Perfect!

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2090.

**Comment by arnavs** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```
