### ISSUE TITLE
[REVIEW]: SpeciesEvolver: A Landlab component to evolve life in simulated landscapes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2066]
**Submitting author:** @nathanlyons (<a href="http://orcid.org/0000-0001-6965-3374">Nathan Lyons</a>)
**Repository:** <a href="https://github.com/landlab/landlab" target ="_blank">https://github.com/landlab/landlab</a>
**Version:** v2.0.0b6
**Editor:** @kyleniemeyer
**Reviewer:** @ebgoldstein, @fclubb
**Archive:** <a href="https://doi.org/10.5281/zenodo.3672119" target="_blank">10.5281/zenodo.3672119</a>

## Status

[![status](https://joss.theoj.org/papers/446f3d17d642682b234ffed2b53198f6/status.svg)](https://joss.theoj.org/papers/446f3d17d642682b234ffed2b53198f6)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/446f3d17d642682b234ffed2b53198f6"><img src="https://joss.theoj.org/papers/446f3d17d642682b234ffed2b53198f6/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/446f3d17d642682b234ffed2b53198f6/status.svg)](https://joss.theoj.org/papers/446f3d17d642682b234ffed2b53198f6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/landlab/landlab" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ebgoldstein & @fclubb, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kyleniemeyer know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/landlab/landlab">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@nathanlyons) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/landlab/landlab">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@nathanlyons) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ebgoldstein, @fclubb it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by kyleniemeyer** [comment]
👋 @nathanlyons @ebgoldstein @fclubb the actual review will take place in here

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02066/joss.02066/10.21105.joss.02066.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1029/WR006i005p01296 is OK
- 10.1016/S0167-5648(09)70009-7 is OK
- 10.1029/2002WR001728 is OK
- 10.1016/j.advwatres.2017.09.008 is OK
- 10.1002/esp.1369 is OK
- 10.1016/j.jhydrol.2003.12.043 is OK
- 10.1002/2014WR015809 is OK
- 10.1002/2013WR013918 is OK
- 10.1029/WR007i005p01256 is OK
- 10.1126/science.aaf7891 is OK
- 10.1016/j.jhydrol.2008.11.002 is OK
- 10.1029/92WR00802 is OK
- 10.5194/esurf-5-21-2017 is OK
- 10.1002/hyp.8319 is OK
- 10.1029/2008WR007536 is OK
- 10.1029/2006WR005752 is OK
- 10.1016/j.advwatres.2005.08.006 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by nathanlyons** [comment]
@kyleniemeyer @ebgoldstein @fclubb Thank you in advance for your time.

**The Landlab branch under this review is `nathanlyons_species_evolver_joss_review`.** This branch will be merged with the Landlab development branch, `master` then `release` following this review. The separate joss review branch is necessary because multiple Landlab modules are under JOSS review.

**Comment by nathanlyons** [comment]
@whedon generate pdf from branch nathanlyons_species_evolver_joss_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch nathanlyons_species_evolver_joss_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02066/joss.02066/10.21105.joss.02066.pdf)

**Comment by nathanlyons** [comment]
Please see the article proof describing SpeciesEvolver directly above this comment. The first proof, describing a groundwater component, is not a part of this review.

**Comment by kyleniemeyer** [comment]
Thanks @nathanlyons, I forgot about the paper being on a branch—I've deleted the incorrect PDF.

**Comment by fclubb** [comment]
Hi @nathanlyons, I have updated my checklist and made a couple of very minor suggestions in a Landlab issue: https://github.com/landlab/landlab/issues/1147

**Comment by nathanlyons** [comment]
@fclubb I have responded to your comments at https://github.com/landlab/landlab/issues/1147. Code changes were pushed to the [branch under review](https://github.com/landlab/landlab/tree/nathanlyons_species_evolver_joss_review). I will ask the robot to create an updated version of the paper reflecting your comments.

**Comment by nathanlyons** [comment]
@whedon generate pdf from branch nathanlyons_species_evolver_joss_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch nathanlyons_species_evolver_joss_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02066/joss.02066/10.21105.joss.02066.pdf)

**Comment by ebgoldstein** [comment]
👋  @nathanlyons 

I have now worked through the Species Evolver [tutorial notebook](https://github.com/landlab/landlab/tree/master/notebooks/tutorials/species_evolution) (via a Google Colab).  The install and model worked without a hiccup — i think this component extends the capabilities of the model in exciting ways, and will allow many interesting questions to be addressed using Landlab.

The paper was clear, and I understood both the SON and the summary of the component. 

@kyleniemeyer, at this time I have made no issues in the Landlab repository, and i have no suggested edits to the ms. 

very cool work @nathanlyons et al.

**Comment by fclubb** [comment]
I'm also happy with everything, excellent job @nathanlyons !

**Comment by kyleniemeyer** [comment]
Thanks @ebgoldstein  and @fclubb! Next I will do a quick review of the article.

Actually, @ebgoldstein, could you fill out the remaining review checklist items (in the functionality section)?

**Comment by ebgoldstein** [comment]
done.

**Comment by nathanlyons** [comment]
@ebgoldstein Thank you also for the review. Good to know it works in Google Colab. I suppose no reason it should not.

**Comment by nathanlyons** [comment]
@kyleniemeyer FYI for your review, I noticed minor changes needed in the paper, namely an incorrect year on a reference, acknowledging all reviewers, and rewording "taxa evolution" to "biological evolution" because taxa was not defined yet in the Introduction. Here is the [commit](https://github.com/landlab/landlab/commit/b84a8214ed4a99ed2c9cca2c048052ac5eddb153) with these changes, along with an additional word change in [here](https://github.com/landlab/landlab/commit/c2e815be02b7bf0a762ad5a32570ece4abfdf13b). I will generate an updated pdf.

In the meantime and given this repo is a branch, I foresee that this is the next course of action for me, at least given this recent precedent: https://github.com/openjournals/joss-reviews/issues/1935
- I merge my Landlab review branch with Landlab master (first I have requested groundwater's now published paper to no longer be named 'paper.md' so as to not conflict with mine.
- A new landlab version is released, maybe this will be v2.0.0b6, I will let you know.
- I set up an archive at zenodo and provide this doi to you.

@kyleniemeyer Please let me know if this is off.

**Comment by nathanlyons** [comment]
@whedon generate pdf from branch nathanlyons_species_evolver_joss_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch nathanlyons_species_evolver_joss_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02066/joss.02066/10.21105.joss.02066.pdf)

**Comment by kyleniemeyer** [comment]
@nathanlyons yes, that seems a good course of action. However, before you merge your branch into the Landlab master, please wait until i can review your article—that way any changes are contained in the branch

**Comment by nathanlyons** [comment]
@kyleniemeyer Will do.

**Comment by kyleniemeyer** [comment]
@nathanlyons just a minor comment: please consistently put commas after instances of "i.e." and "e.g." (for example, `(i.e. allopatry)` -> `(i.e., allopatry)`)

**Comment by nathanlyons** [comment]
@kyleniemeyer All `i.e.` and `e.g.` instances are now followed by commas. I will now work on the aforementioned workflow.

**Comment by kyleniemeyer** [comment]
@nathanlyons thanks- let me know when your branch has been merged, and report back with a DOI associated with a Zenodo archive

**Comment by nathanlyons** [comment]
@kyleniemeyer 

The software under review is no longer on a branch, and is now on `master` of the Landlab repo.

Please update the version of the software under review. It should now be `v2.0.0b6`.

The Zenodo archive DOI is `10.5281/zenodo.3672119`.

**Comment by kyleniemeyer** [comment]
@whedon set v2.0.0b6 as version

**Comment by whedon** [comment]
OK. v2.0.0b6 is the version.

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.3672119 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3672119" target="_blank">10.5281/zenodo.3672119</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch master

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch master. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02066/joss.02066/10.21105.joss.02066.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1029/WR006i005p01296 is OK
- 10.1016/S0167-5648(09)70009-7 is OK
- 10.1029/2002WR001728 is OK
- 10.1016/j.advwatres.2017.09.008 is OK
- 10.1002/esp.1369 is OK
- 10.1016/j.jhydrol.2003.12.043 is OK
- 10.1002/2014WR015809 is OK
- 10.1002/2013WR013918 is OK
- 10.1029/WR007i005p01256 is OK
- 10.1126/science.aaf7891 is OK
- 10.1016/j.jhydrol.2008.11.002 is OK
- 10.1029/92WR00802 is OK
- 10.5194/esurf-5-21-2017 is OK
- 10.1002/hyp.8319 is OK
- 10.1029/2008WR007536 is OK
- 10.1029/2006WR005752 is OK
- 10.1016/j.advwatres.2005.08.006 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1314

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1314, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1229563218022064129) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1315
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02066](https://doi.org/10.21105/joss.02066)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @nathanlyons on your article's publication in JOSS!

Many thanks to @ebgoldstein and @fclubb for reviewing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02066/status.svg)](https://doi.org/10.21105/joss.02066)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02066">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02066/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02066/status.svg
   :target: https://doi.org/10.21105/joss.02066
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02066/status.svg)](https://doi.org/10.21105/joss.02066)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
