### ISSUE TITLE
[PRE REVIEW]: fqfa: A pure Python package for genomic sequence files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2067]
**Submitting author:** @afrubin (<a href="http://orcid.org/0000-0003-1474-605X">Alan F. Rubin</a>)
**Repository:** <a href="https://github.com/CountESS-Project/fqfa/" target ="_blank">https://github.com/CountESS-Project/fqfa/</a>
**Version:** v0.0.2
**Editor:** @lpantano
**Reviewers:** @natir, @FlorianThibord

**Author instructions**

Thanks for submitting your paper to JOSS @afrubin. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @will-rowe.

@afrubin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.7287/peerj.preprints.970v1 is OK
- 10.1093/bioinformatics/btp163 is OK
- 10.1093/nar/gkp1137 is OK
- 10.1073/pnas.85.8.2444 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02067/joss.02067/10.21105.joss.02067.pdf)

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (329.7 files/s, 28156.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          21            450            703           1088
Markdown                         3             36              0            110
TeX                              1              7              0             96
reStructuredText                 5             77            169             90
DOS Batch                        1              8              1             26
YAML                             1              0              0             20
make                             1              4              7              9
CSS                              1              0              0              3
-------------------------------------------------------------------------------
SUM:                            34            582            880           1442
-------------------------------------------------------------------------------


Statistical information for the repository '2067' was gathered on 2020/02/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alan Rubin                      96          3244           1003          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alan Rubin                 2241           69.1          1.3                8.66
```

**Comment by kthyng** [comment]
Hi @will-rowe, @lpantano, and @majensen! Could one of you take over to handle this submission?

@afrubin As a non-expert in your field, I read through your paper but am a bit unsure of the package motivation. It says this is slower than other readers, but easier to understand. Do people usually use this type of package as a black box or look at the code?

**Comment by afrubin** [comment]
> @afrubin As a non-expert in your field, I read through your paper but am a bit unsure of the package motivation. It says this is slower than other readers, but easier to understand. Do people usually use this type of package as a black box or look at the code?

@kthyng Happy to expand on this! 

Bioinformatics and computational biology are expanding rapidly and ever more people from biology backgrounds (often with no programming experience) are learning to do their own analyses. I think there's value in having code that's easier to understand by newcomers and students, and I know from experience that many of them like to try to read the code as part of their learning. Also, the efficiency of reading these files is typically not a major contributor to program runtime.

The package is written in pure Python (despite compiled extensions being faster) because many of these new users aren't running a Unix-based OS and don't have a standard development environment, compilers, etc. installed, which has been a source of problems when requiring some common Python bioinformatics dependencies.

**Comment by kthyng** [comment]
@afrubin Ok that seems reasonable. I will wait to hear back from one of our editors in this area to see if they can take it on.

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
@natir, @simonvh, @FlorianThibord would you like to review this tool?

**Comment by natir** [comment]
@lpantano I can review this tool.

**Comment by FlorianThibord** [comment]
@lpantano Yes, I can review the tool

**Comment by simonvh** [comment]
I think two would suffice? In case it is needed, I would be happy to help out.

**Comment by lpantano** [comment]
@whedon assign @natir as reviewer

**Comment by whedon** [comment]
OK, @natir is now a reviewer

**Comment by lpantano** [comment]
@whedon add @FlorianThibord as reviewer

**Comment by whedon** [comment]
OK, @FlorianThibord is now a reviewer

**Comment by lpantano** [comment]
Thanks all for the super quick reply, I will let @simonvh free this time :)

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2076.
