### ISSUE TITLE
[PRE REVIEW]: SyntenyViz

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2068]
**Submitting author:** @robqiao (<a href="http://orcid.org/0000-0003-4569-6921">Robert QIAO</a>)
**Repository:** <a href="https://github.com/DPP4ResearchGroup/SyntenyViz" target ="_blank">https://github.com/DPP4ResearchGroup/SyntenyViz</a>
**Version:** v0.0.0.9000
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @robqiao. **Currently, there isn't an JOSS editor assigned** to your paper.

@robqiao if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2068 with the following error: 

 Error reading bibliography ./paper.bib (line 2, column 1):
unexpected "}"
expecting space
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (787.4 files/s, 20145.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               21             48            324            224
Markdown                         2              4              0             32
Bourne Shell                     3             13             24             30
YAML                             1              0              0             22
Rmd                              1              2             12              5
TeX                              1              0              0              2
-------------------------------------------------------------------------------
SUM:                            29             67            360            315
-------------------------------------------------------------------------------


Statistical information for the repository '2068' was gathered on 2020/02/04.
No commited files with the specified extensions were found.
```

**Comment by kthyng** [comment]
Hi @robqiao! Thank you for your submission. Your submission is looking a bit unfinished currently because it lacks much of a readme, the vignette is empty, the paper looks like it wasn't finished, it's missing documentation, and therefore we at the editorial board as unsure how your package works and the type of input/output produced, and how to test it.

I suggest that you withdraw your submission, improve it, and resubmit in the future.

In case you want to do that, note that we are working to improve our guidelines for what counts as a "large enough" contribution to warrant a JOSS submission, but your current number of lines of code would raise a red flag for potentially being too small. Being a small package is not disqualifying, but it would require some extra explanation as to why it should still be enough to warrant a publication.

**Comment by danielskatz** [comment]
👋 @robqiao - as mentioned by @kthyng, I'm going to reject this as incomplete at this time. Normally, we would welcome a later submission of a more complete version, but given the small amount of code in your submission and the potential that it would be considered minor or a wrapper, you might want to first make a pre-submission inquiry, using https://github.com/openjournals/joss/issues/new?title=Pre-submission%20enquiry

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by robqiao** [comment]
Thx for your comments @danielskatz @kthyng 
I forgot to merge the branch, now released. 
plus what's the size deemed reasonable? do we have a whedon function to check? Many Thanks

**Comment by danielskatz** [comment]
Can we discuss this in a pre-submission inquiry, using https://github.com/openjournals/joss/issues/new?title=Pre-submission%20enquiry
rather than a closed pre-review issue...

**Comment by robqiao** [comment]
@kthyng is this looking any better? 

      68 text files.
      62 unique files.
      31 files ignored.

github.com/AlDanial/cloc v 1.84  T=0.28 s (129.9 files/s, 4776.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                      24             73            382            282
Markdown                         2             24              0               135
TeX                                    1              6              0                  83
Bourne Shell                     5             25             33                79
Rmd                                   1             32            107               54
YAML                                 2              2              2                 35
HTML                                 2              0              0                  6
-------------------------------------------------------------------------------
SUM:                            37            162            524            674
-------------------------------------------------------------------------------

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/431916a is OK
- 10.1038/nature03025 is OK
- 10.1371/journal.pcbi.0020015 is OK
- 10.1093/nar/gks1172 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/B978-0-12-809633-8.20236-7 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/S0091-679X(04)77025-9 is INVALID because of 'https://doi.org/' prefix
```

**Comment by manifestoso** [comment]
@whedon commands

**Comment by manifestoso** [comment]
@editorialbot commands

**Comment by manifestoso** [comment]
@editorialbot check repository

**Comment by manifestoso** [comment]
@editorialbot check references

**Comment by manifestoso** [comment]
@editorialbot generate pdf

**Comment by manifestoso** [comment]
@editorialbot generate preprint
