### ISSUE TITLE
[REVIEW]: pyGOURGS - global optimization of n-ary tree representable problems using uniform random global search

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2074]
**Submitting author:** @pySRURGS (<a href="http://orcid.org/0000-0002-3050-8943">Sohrab Towfighi</a>)
**Repository:** <a href="https://github.com/pySRURGS/pyGOURGS" target ="_blank">https://github.com/pySRURGS/pyGOURGS</a>
**Version:** 0.1
**Editor:** @arokem
**Reviewer:** @iljah, @nicoguaro
**Archive:** <a href="https://doi.org/10.5281/zenodo.3710475" target="_blank">10.5281/zenodo.3710475</a>

## Status

[![status](https://joss.theoj.org/papers/17180193c5f25d3cc1edb460bc1335aa/status.svg)](https://joss.theoj.org/papers/17180193c5f25d3cc1edb460bc1335aa)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/17180193c5f25d3cc1edb460bc1335aa"><img src="https://joss.theoj.org/papers/17180193c5f25d3cc1edb460bc1335aa/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/17180193c5f25d3cc1edb460bc1335aa/status.svg)](https://joss.theoj.org/papers/17180193c5f25d3cc1edb460bc1335aa)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pySRURGS/pyGOURGS" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@iljah & @nicoguaro, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arokem know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pySRURGS/pyGOURGS">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@pySRURGS) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pySRURGS/pyGOURGS">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@pySRURGS) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @iljah, @nicoguaro it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1186/s13040-018-0164-x is OK
- 10.1287/moor.6.1.19 is OK

MISSING DOIs

- https://doi.org/10.1016/0012-365x(71)90023-9 may be missing for title: Enumerating Trees
- https://doi.org/10.21105/joss.01675 may be missing for title: pySRURGS-a python package for symbolic regression by uniform random global search

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02074/joss.02074/10.21105.joss.02074.pdf)

**Comment by nicoguaro** [comment]
I have installed the software as described. Nevertheless, I couldn't find an example of use in the documentation.

**Comment by pySRURGS** [comment]
@nicoguaro , I will amend documentation to reflect suggested changes once I am back from interviews. There is an examples folder with script ant.py

**Comment by nicoguaro** [comment]
I tried running the example with

    $ python ant.py 

with output

```bash
Traceback (most recent call last):
  File "ant.py", line 118, in <module>
    output_db = args[0]
IndexError: list index out of range
```

with

$ python ant.py output

I get

```bash
Traceback (most recent call last):
  File "ant.py", line 119, in <module>
    n_iters = int(args[1])
IndexError: list index out of range
```

and, finally, with

    $ python ant.py output 10

I didn't have any error message

**Comment by pySRURGS** [comment]
The results would then be saved to the file called "output" without any extension.

**Comment by pySRURGS** [comment]
There would have been 10 candidate solutions considered in that run.

**Comment by nicoguaro** [comment]
Yes, that's what I understood by looking at the source code. But those things should be explained in the documentation.

**Comment by iljah** [comment]
@pySRURGS please specify which university of medicine you are affiliated with.

**Comment by iljah** [comment]
@pySRURGS it would be helpful if you'd mention how this relates to e.g. https://www.gnu.org/software/gsl/doc/html/multimin.html. Does this solve a more general problem or is this more efficient than GSL or..?

**Comment by iljah** [comment]
As @nicoguaro mentioned, @pySRURGS  please add at least one simple example to documentation. Also it would be helpful for example programs to print usage instructions when used incorrectly, etc.

**Comment by pySRURGS** [comment]
University of Toronto. 
It solves a different class of problems. It is more akin to traditional machine learning than it is to numerical optimization/function minimization. Thanks for the feedback and I will address these issues in coming days.

**Comment by pySRURGS** [comment]
@iljah @nicoguaro 
I have made the corrections you suggested. Please review the readme as it has been edited. Please review the ant.py example file as it has been greatly altered. It now has an interface that you can use from command line and this is discussed in the readme.

**Comment by nicoguaro** [comment]
I guess that the line

    $ winpty python ant.py -h

is for Windows (?).

I ran 

    $ python ant.py

and obtained

```bash
Traceback (most recent call last):
  File "ant.py", line 101, in <module>
    pset = pg.PrimitiveSet()
AttributeError: module 'pyGOURGS' has no attribute 'PrimitiveSet'
```

**Comment by pySRURGS** [comment]
@nicoguaro 
Yes winpty is for windows and has no effect on my code's function.
That is odd, and your error message is not that helpful. If the script is in the current directory and you are running it from terminal then I am not sure the cause of the error. I don't want to come across dismissive but did you `git pull` before running?

**Comment by pySRURGS** [comment]
Oh nevermind i accidentally removed a line, let me fix.

**Comment by pySRURGS** [comment]
It is working fine on my end. If you are unable to run the code after git pulling and doing some sanity checks I can run on Linux later.

**Comment by pySRURGS** [comment]
@nicoguaro I ran a fresh install of the software on linux and ran 
`python ant.py` and did not encounter the issue.
please check that you ran the script from within the /examples/ directory, as I import the pyGOURGS package using a relative path.

**Comment by pySRURGS** [comment]
I added commentary to the readme about running ant.py when in the /examples directory because of the relative path import of pyGOURGS

**Comment by nicoguaro** [comment]
> @nicoguaro I ran a fresh install of the software on linux and ran
> `python ant.py` and did not encounter the issue.
> please check that you ran the script from within the /examples/ directory, as I import the pyGOURGS package using a relative path.

I tried with a fresh install and it worked.

**Comment by iljah** [comment]
@pySRURGS thanks for making the changes, to me this looks good to go.

**Comment by pySRURGS** [comment]
@nicoguaro  I have added multiprocessing support to ant.py
You may need to run 
```
pip install -r requirements.txt --user
```
while in the main directory in order to install new requirements.

**Comment by pySRURGS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02074/joss.02074/10.21105.joss.02074.pdf)

**Comment by pySRURGS** [comment]
@nicoguaro are there any changes you would like to see made? Can I assist your review in any way?

**Comment by nicoguaro** [comment]
@pySRURGS, sorry I had some busy days. I will come back to the review this week.

**Comment by nicoguaro** [comment]
@arokem I have completed my review and I would suggest publication. I do have a suggestion to the documentation, though:

> Add tutorials/examples to it. Currently it only provides an API documentation without explanations. I would suggest to start with the ant example and expand it with explanations.

@pySRURGS, I also have some comments regarding the paper. You can find an annotated PDF [here](https://www.dropbox.com/s/flshpkopb3brckv/10.21105.joss.02074.pdf?dl=0).

**Comment by sohrabtowfighi** [comment]
> @arokem I have completed my review and I would suggest publication. I do have a suggestion to the documentation, though:
> 
> > Add tutorials/examples to it. Currently it only provides an API documentation without explanations. I would suggest to start with the ant example and expand it with explanations.

Could you help me by clarifying this? The API documentation is provided with comments for just about every function and class. The artificial ant example is explored in detail in the readme.md and a basic example run is shown. Do you think I should add more examples on how to use the bash interface?

**Comment by nicoguaro** [comment]
Yes, I think so.

The API documentation and examples/tutorials serve to different types of users. For newcomers to your software, the API documentation will be less useful than step-by-step explanations. The opposite happens for competent users.

**Comment by sohrabtowfighi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02074/joss.02074/10.21105.joss.02074.pdf)

**Comment by sohrabtowfighi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02074/joss.02074/10.21105.joss.02074.pdf)

**Comment by sohrabtowfighi** [comment]
Ok @nicoguaro I think it is ready for re-review. I have incorporated most your edits into the paper. I also added several examples and subheaders in the description of the artificial ant example in the readme.md

**Comment by nicoguaro** [comment]
@sohrabtowfighi, I already suggested the publication. I think that we are waiting for @arokem.

**Comment by pySRURGS** [comment]
@nicoguaro please check off all the tick boxes

**Comment by arokem** [comment]
@nicoguaro : I see that "example usage" is still unchecked.  Just making sure: is this ready for publication from your point of view?

**Comment by arokem** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/4235.585893 is OK
- 10.1186/s13040-018-0164-x is OK
- 10.1287/moor.6.1.19 is OK
- 10.21105/joss.01675 is OK

MISSING DOIs

- https://doi.org/10.1016/0012-365x(71)90023-9 may be missing for title: Enumerating Trees

INVALID DOIs

- None
```

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by arokem** [comment]
In the meanwhile, @pySRURGS : could you please fix the missing DOI?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02074/joss.02074/10.21105.joss.02074.pdf)

**Comment by pySRURGS** [comment]
@arokem no doi available for that reference

**Comment by arokem** [comment]
I see now. The DOI suggested by whedon is incorrect (points to another resource). I think that you can leave this as is. 

In the meanwhile, while we are waiting for @nicoguaro's final approval, could you please go ahead and proceed with the following steps: 

- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g. figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

Once we have these items, and @nicoguaro's confirmation, we can move ahead with the acceptance of the paper.

**Comment by nicoguaro** [comment]
> @nicoguaro : I see that "example usage" is still unchecked. Just making sure: is this ready for publication from your point of view?

Yes, it is checked now.

**Comment by pySRURGS** [comment]
https://github.com/pySRURGS/pyGOURGS/releases/tag/0.1
http://doi.org/10.5281/zenodo.3710475

**Comment by pySRURGS** [comment]
All done

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.3710475 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3710475" target="_blank">10.5281/zenodo.3710475</a> is the archive.

**Comment by arokem** [comment]
@whedon set 0.1 as version

**Comment by whedon** [comment]
OK. 0.1 is the version.

**Comment by arokem** [comment]
@openjournals/joss-eics : this is ready for your review, when you get around to it. 

@pySRURGS : please bear with us, as we do our best here.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/4235.585893 is OK
- 10.1186/s13040-018-0164-x is OK
- 10.1287/moor.6.1.19 is OK
- 10.21105/joss.01675 is OK

MISSING DOIs

- https://doi.org/10.1016/0012-365x(71)90023-9 may be missing for title: Enumerating Trees

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1381

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1381, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
👋 @pySRURGS - please merge https://github.com/pySRURGS/pyGOURGS/pull/2 and https://github.com/pySRURGS/pyGOURGS/pull/3 or let me know what you disagree with. These are changes based on proof-reading the final draft paper.

**Comment by pySRURGS** [comment]
@danielskatz , I have merged all suggested changes.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/4235.585893 is OK
- 10.1186/s13040-018-0164-x is OK
- 10.1287/moor.6.1.19 is OK
- 10.21105/joss.01675 is OK

MISSING DOIs

- https://doi.org/10.1016/0012-365x(71)90023-9 may be missing for title: Enumerating Trees

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1384

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1384, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1240960807137169412) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1385
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02074](https://doi.org/10.21105/joss.02074)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @iljah & @nicoguaro for reviewing, and to @arokem for editing!

And congratulations to @pySRURGS!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02074/status.svg)](https://doi.org/10.21105/joss.02074)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02074">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02074/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02074/status.svg
   :target: https://doi.org/10.21105/joss.02074
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02074/status.svg)](https://doi.org/10.21105/joss.02074)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
