### ISSUE TITLE
[REVIEW]: `psi-collect`: A Python module for post-storm image collection and cataloging

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2075]
**Submitting author:** @ebgoldstein (<a href="http://orcid.org/0000-0001-9358-1016">Evan B Goldstein</a>)
**Repository:** <a href="https://github.com/UNCG-DAISY/psi-collect" target ="_blank">https://github.com/UNCG-DAISY/psi-collect</a>
**Version:** v1.0.4
**Editor:** @kbarnhart
**Reviewer:** @katmratliff, @conlin-matt, @chrisleaman
**Archive:** <a href="https://doi.org/10.5281/zenodo.3687347" target="_blank">10.5281/zenodo.3687347</a>

## Status

[![status](https://joss.theoj.org/papers/890cc9edd3ec2aafeba9616e8c5f7813/status.svg)](https://joss.theoj.org/papers/890cc9edd3ec2aafeba9616e8c5f7813)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/890cc9edd3ec2aafeba9616e8c5f7813"><img src="https://joss.theoj.org/papers/890cc9edd3ec2aafeba9616e8c5f7813/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/890cc9edd3ec2aafeba9616e8c5f7813/status.svg)](https://joss.theoj.org/papers/890cc9edd3ec2aafeba9616e8c5f7813)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/UNCG-DAISY/psi-collect" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@katmratliff & @conlin-matt & @chrisleaman, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kbarnhart know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/UNCG-DAISY/psi-collect">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ebgoldstein) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/UNCG-DAISY/psi-collect">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ebgoldstein) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a
target="_blank" href="https://github.com/UNCG-DAISY/psi-collect">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with
the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ebgoldstein) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties
wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @katmratliff, @conlin-matt, @chrisleaman it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2075 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.6084/m9.figshare.11604192.v1 is OK
- 10.1002/2016GL071213 is OK
- 10.1002/2015JF003634 is OK
- 10.1109/TGRS.2013.2277092 is OK
- 10.1145/2556420.2556790 is OK
- 10.1142/9789814689977_0250 is OK
- 10.1109/OCEANS.2018.8604932 is OK
- 10.1142/9789811204487_0124 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02075/joss.02075/10.21105.joss.02075.pdf)

**Comment by kbarnhart** [comment]
@arfon something funny is happening with whedon and PDF generating. Here and in the PRE-REVIEW (#2064) the automated attempt to compile the paper.md failed, but when I asked whedon to do it, ti succeeded.

**Comment by kbarnhart** [comment]
:wave: @ebgoldstein, @katmratliff, @conlin-matt, and @chrisleaman this is the review thread for the paper. All of our communications will happen here from now on.

All reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention openjournals/joss-reviews#2075 so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@kbarnhart) if you have any questions/concerns.

**Comment by arfon** [comment]
> @arfon something funny is happening with whedon and PDF generating. Here and in the PRE-REVIEW (#2064) the automated attempt to compile the paper.md failed, but when I asked whedon to do it, ti succeeded.

I think the issue here is that the repository is pretty large (> 400Mb) which means that Whedon is sometimes timing out. I'm not sure that there's much we can do about this sorry, unless the authors are able to [reduce the size of the repository](https://www.google.com/search?q=reducing+git+repository+size&oq=reducing+git+repo&aqs=chrome.0.0j69i57j0l4.4260j1j7&sourceid=chrome&ie=UTF-8).

**Comment by chrisleaman** [comment]
Hi @kbarnhart and `psi-collect` team, 

Just letting you know I've finished my review. Overall, I thought it was a nifty tool to manage a lot of unwieldy but important data. I've been finding aerial imagery is so important and can give a lot of context to pre- and post-storm LIDAR surveys especially for assigning storm impacts. 

For a bit of feedback on the code, what I liked:
1. The extensive use of type hinting for variables! There were a couple of times I was playing round with the code and it caught a couple of my errors.
2. The fact it's available as a CLI script. Users will find it easy to just call `pstorm` from the CLI, rather than having to implement the package in their own script.
3. Great that tests are included, makes it really easy to see if changes to code affect anything.

These are some suggestions for future improvements, if you're looking for ideas. Some of these I'm sure you're already aware of:

1. Using the `click` package can help tidy up some of the path wrangling that's being done in the `pstorm.py` file. Otherwise perhaps look at the argparse `add_subparsers` command. I'm not sure that using `exec()` to call the script is the best idea. 
2. Try reducing the size data in the tests folder. Do you really need to include the full resolution images to test on? Or is it possible to use a reduced size image or even mock them out completely. This might improve compatibility with build systems (which can have issues if the repo is too big) and might just generally be easier to work with.
3. I think a lot of the Path manipulation can be done with the `pathlib` library that was introduced in Python 3.4. This might help clean up the code, rather than using `os.path`.

List of pull requests and issues I submitted:

- https://github.com/UNCG-DAISY/psi-collect/issues/73
- https://github.com/UNCG-DAISY/psi-collect/issues/74
- https://github.com/UNCG-DAISY/psi-collect/pull/75
- https://github.com/UNCG-DAISY/psi-collect/pull/68
- https://github.com/UNCG-DAISY/psi-collect/pull/83
- https://github.com/UNCG-DAISY/psi-collect/pull/84

**Comment by kbarnhart** [comment]
Thanks for the update and for completing your review @chrisleaman!

**Comment by conlin-matt** [comment]
Hi @kbarnhart et al.,

I have finished my review as well. Agreeing with @chrisleaman here that this is a neat tool to help deal with a whole-lot of difficult-to-manage data. I especially find the ability to automatically extract geographic info from the photos to be a hugely useful and important feature. It's relatively easy to use, and, with a few tweaks to the documentation (outlined in my submitted Issues above), is well documented and transparent in its capabilities. The paper is clear as well. With @chrisleaman's tweaks to the code, I don't see anything that glaringly needs improvement in terms of efficiency. 

Once the relatively minor improvements to the cataloging routine are made (see above), I think all will look good. 

Thanks to the authors for creating this tool- I've definitely added it to my toolbox!

**Comment by katmratliff** [comment]
Hi @kbarnhart and others,

I have also finished my review. I agree with @chrisleaman and @conlin-matt that is a very useful package for streamlining the downloading, extracting, and processing of NOAA imagery, which will undoubtedly be of interest to many academic, engineering, and government entities. The paper states the use cases for the software, and the documentation is informative.  I did have trouble extracting .zip archive files on my machine, but I suspect this is an issue with my EPA machine and/or network, particularly if the other reviewers didn't have trouble doing this on windows machines (I think I saw @chrisleaman was also running windows?). I opened the following issues and a PR as part of my review:

- https://github.com/UNCG-DAISY/psi-collect/issues/103
- https://github.com/UNCG-DAISY/psi-collect/issues/102
- https://github.com/UNCG-DAISY/psi-collect/issues/99
- https://github.com/UNCG-DAISY/psi-collect/pull/104

Thanks to the `psi-collect` team for their hard work!

**Comment by ebgoldstein** [comment]
Thanks @chrisleaman, @conlin-matt, @katmratliff, and @kbarnhart for all of your the suggestions, PRs, issues, bug identifications, and comments. The docs and the paper now reflect the changes requested by reviewers. I think we (read: @Matmorcat) have squashed some nice bugs. 

@chrisleaman 's suggestions for future enhancements have been added as issues, and we hope to integrate these with future iterations of the tool.

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02075/joss.02075/10.21105.joss.02075.pdf)

**Comment by kbarnhart** [comment]
Thanks to reviewers @chrisleaman, @conlin-matt, @katmratliff for prompt and thoughtful reviews and to authors @ebgoldstein (and @Matmorcat) for addressing issues. I agree with the decision to archive @chrisleaman's recommendations for future enhancements and outstanding issues. I see that those are the only remaining open issues.  

At this stage, I ask that all reviewers confirm their recommendation to accept this publication. 

After reviewers have confirmed, I will do a final copy edit of the manuscript.

**Comment by chrisleaman** [comment]
@kbarnhart, confirming my recommendation to accept this publication 👍

**Comment by katmratliff** [comment]
@kbarnhart also confirming my recommendation to accept for publication

**Comment by conlin-matt** [comment]
@kbarnhart I confirm my recommendation for publication as well.

**Comment by ebgoldstein** [comment]
I just added a thx to reviewers and editor in the acknowledgments

**Comment by ebgoldstein** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02075/joss.02075/10.21105.joss.02075.pdf)

**Comment by kbarnhart** [comment]
@ebgoldstein can you:

* Issue a new tagged release reflecting the latest changes to the software. 
* Respond here with that version number.
* Create a zenodo (or similar) archive. Make sure that it has the same title and author list as the paper.
* Post the DOI of that archive here.

**Comment by Matmorcat** [comment]
@kbarnhart I've created an updated release tagged [v1.0.4](https://github.com/UNCG-DAISY/psi-collect/releases/tag/v1.0.4). I'll leave @ebgoldstein to create the archive! 😄

**Comment by kbarnhart** [comment]
Sounds good. FYI, this ooo is not correct.

**Comment by kbarnhart** [comment]
Thanks @Matmorcat ! Can you try tagging me? I deleted the comments in which I incorrectly marked myself as OOO, not sure if that works to cancel...

**Comment by Matmorcat** [comment]
Sure @kbarnhart 
If that doesn't work just set an arbitrary date that is closer I guess.

**Comment by kbarnhart** [comment]
@Matmorcat looks like deleting the post doesn't work. 

I had tried your approach of re-posting with a shorter date range, and that didn't work... Thanks for the thought though!

**Comment by Matmorcat** [comment]
I think it's because you have to spell out the full month for both parameters!

**Comment by kbarnhart** [comment]
OK. I'll retry here.

/ooo February 22 until February 22

**Comment by ebgoldstein** [comment]
code DOI (via Zenodo): 10.5281/zenodo.3687347

**Comment by kbarnhart** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.6084/m9.figshare.11604192.v1 is OK
- 10.1002/2016GL071213 is OK
- 10.1002/2015JF003634 is OK
- 10.1109/TGRS.2013.2277092 is OK
- 10.1145/2556420.2556790 is OK
- 10.1142/9789814689977_0250 is OK
- 10.1109/OCEANS.2018.8604932 is OK
- 10.1142/9789811204487_0124 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02075/joss.02075/10.21105.joss.02075.pdf)

**Comment by kbarnhart** [comment]
@whedon set 10.5281/zenodo.3687347 as archive.

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3687347" target="_blank">10.5281/zenodo.3687347</a> is the archive.

**Comment by kbarnhart** [comment]
@whedon set v1.0.4 as version

**Comment by whedon** [comment]
OK. v1.0.4 is the version.

**Comment by kbarnhart** [comment]
@openjournals/joss-eics this is now ready for final processing.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.6084/m9.figshare.11604192.v1 is OK
- 10.1002/2016GL071213 is OK
- 10.1002/2015JF003634 is OK
- 10.1109/TGRS.2013.2277092 is OK
- 10.1145/2556420.2556790 is OK
- 10.1142/9789814689977_0250 is OK
- 10.1109/OCEANS.2018.8604932 is OK
- 10.1142/9789811204487_0124 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published

. Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1347

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1347, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1234266615312736262) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1348
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02075](https://doi.org/10.21105/joss.02075)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @ebgoldstein, your JOSS paper is published! 🚀 

Big thanks to our editor: @kbarnhart, and reviewers: @katmratliff, @conlin-matt, @chrisleaman — we couldn't do this without you 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02075/status.svg)](https://doi.org/10.21105/joss.02075)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02075">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02075/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02075/status.svg
   :target: https://doi.org/10.21105/joss.02075
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02075/status.svg)](https://doi.org/10.21105/joss.02075)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
