### ISSUE TITLE
[REVIEW]: The pdb2sql Python Package: Parsing, Manipulation and Analysis of PDB Files Using SQL Queries

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2077]
**Submitting author:** @NicoRenaud (<a href="http://orcid.org/0000-0001-9589-2694">Nicolas Renaud</a>)
**Repository:** <a href="https://github.com/DeepRank/pdb2sql" target ="_blank">https://github.com/DeepRank/pdb2sql</a>
**Version:** 0.4.0
**Editor:** @lpantano
**Reviewers:** @i-mtz, @JoaoRodrigues, @joaomcteixeira
**Archive:** <a href="https://doi.org/10.5281/zenodo.3860329" target="_blank">10.5281/zenodo.3860329</a>

## Status

[![status](https://joss.theoj.org/papers/6430fd2833ca0a70f1da4b8d8cbcbb2e/status.svg)](https://joss.theoj.org/papers/6430fd2833ca0a70f1da4b8d8cbcbb2e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6430fd2833ca0a70f1da4b8d8cbcbb2e"><img src="https://joss.theoj.org/papers/6430fd2833ca0a70f1da4b8d8cbcbb2e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6430fd2833ca0a70f1da4b8d8cbcbb2e/status.svg)](https://joss.theoj.org/papers/6430fd2833ca0a70f1da4b8d8cbcbb2e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/DeepRank/pdb2sql" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@i-mtz & @JoaoRodrigues & @joaomcteixeira, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/DeepRank/pdb2sql">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@NicoRenaud) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/DeepRank/pdb2sql">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@NicoRenaud) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/DeepRank/pdb2sql">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@NicoRenaud) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @i-mtz, @JoaoRodrigues it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2077 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2077 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btp163 is OK
- 10.1093/bioinformatics/btg299 is OK
- 10.1002/(SICI)1096-987X(20000130)21:2<79::AID-JCC1>3.0.CO;2-B is OK
-  10.25080/Majora-629e541a-00e  is OK
- 10.1093/bioinformatics/btz496 is OK
- 10.1093/bioinformatics/btr168 is OK
- 10.1371/journal.pcbi.1006791 is OK
- 10.1371/journal.pone.0161879 is OK
- 10.1093/nar/gky949 is OK
- 10.1101/483305 is OK
- 10.1002/prot.10393 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02077/joss.02077/10.21105.joss.02077.pdf)

**Comment by lpantano** [comment]
@JoaoRodrigues , @i-mtz, any update in the revision of this paper? thanks!

**Comment by JoaoRodrigues** [comment]
Hi @lpantano , sorry for the late reply but I was traveling+sick and away from my laptop for quite some time. Apologies to the authors for the delay.

**Comment by JoaoRodrigues** [comment]
Hey @NicoRenaud

The tool looks good but there are a few rough edges I'd polish before publishing it. I left a few issues on your repo that should be easy to fix. Here are a few more minor questions/issues I found when going over the paper and the code:

- [ ] There is a consistent typo on the word 'structure' all over the documentation :) `sed -e 's/strcture/structure/g'` should fix it!
- [ ] As a user, I would expect I could use the interface module on a PDB I already parsed, e.g. `pdb = pdb2sql('myfile.pdb'); pdbint = interface(pdb)`. Right now I need to load it twice and this is a bit counter-intuitive. Maybe this is a simple fix?
- [ ] I'd keep to one convention when naming variables and attributes. You use a lot of `get_X` methods, for example, but then there are attributes named `nModels`, `chainID`, `altLoc`. You should stick to one, e.g., `n_models`, `chain_id`, `altloc` for simplicity.
- [ ] For convenience, you could add a fetch method to download files from the RCSB PDB directly. Makes it easier for new users to try the tool without having to find a PDB of their own first.
- [ ] The paper states that pdb2sql tries to abstract SQL language for the end-user, and it generally does a pretty good job! However, having methods like `db.close()` and such in the documentation (and exposed in the public API) sort of defeats the purpose. I would make these private and, my preference here, would make them happen behind the scenes so that the end user never has to worry about db connections, cursors, etc.
- [ ] On the topic of dependencies, I see that sqlalchemy is not necessary for the tool to run, but it provides a better OO interface. Maybe making it a runtime dependency then? Or explain the difference between the two interfaces and why you'd want (or not) to use sqlalchemy.

Overall, the tool does what it says it does and it's pretty quick too. As I said before, just some rough edges that need polishing! Good job @NicoRenaud and @CunliangGeng !

**Comment by NicoRenaud** [comment]
Dear @JoaoRodrigues, thanks for reviewing our code and for your comments and suggestions. We've addressed them all, merged the changes in the master and updated the paper accordingly. As a quick summary : 
- [x] we fixed the consistent typos on the documentation, thanks for spotting that
- [x] You can directly use `pdbint=interface('myfile.pdb')` or if needed first create an sql db and pass it to the interface : `pdb = pdb2sql('myfile.pdb)` pdbint =interface(pdb)`
- [x] The fetch function is a very good idea that is now implemented !
- [x] Indeed exposing the `.close()` method is not ideal. This is now fully done behind the scene as you suggested. (Note that we always use in memory db)
- [x] we realized that we never use sqlalchemy and that we do not want to maintain code that is never used. Therefore we have decided to entirely remove sqlalchemy support form pdb2sql. We kept it in a separate branch in case there is a demand for it. We have updated the documentation and the paper accordingly.
Thanks again for all your comments !

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by lpantano** [comment]
Hey @i-mtz, I hope all is good. Do you have an update for this tool?

@JoaoRodrigues, were all your comments resolved?

Thanks

**Comment by JoaoRodrigues** [comment]
Hi @lpantano , I haven't had time to go over the changes in detail yet, but the message from @NicoRenaud seems to address most of my comments. I am a bit swamped today, but this is on my to-do list for this week. Is that OK? Sorry for the delay in reviewing

**Comment by lpantano** [comment]
All good, thank you!

**Comment by arfon** [comment]
:wave: @i-mtz, @JoaoRodrigues, just a friendly check-in to see how things are going with your reviews?

**Comment by JoaoRodrigues** [comment]
Hi @arfon @NicoRenaud @CunliangGeng , this completely fell off my radar, I'm terribly sorry. Will reply as soon as possible!

**Comment by JoaoRodrigues** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02077/joss.02077/10.21105.joss.02077.pdf)

**Comment by JoaoRodrigues** [comment]
Hi @NicoRenaud @CunliangGeng

Thank you for addressing my points! I'd only add somewhere in the documentation page a mention to the `fetch` function. It's good for me! Approved!! Great work!

**Comment by lpantano** [comment]
Sorry, I need to get a new reviewer since one of them couldn't make it under the current COVID-19 situation. @NicoRenaud , if you have a reviewer in mind, let me know. I will try to find another as soon as possible.

**Comment by JoaoRodrigues** [comment]
Not to overstep my boundaries as a reviewer, but if I can suggest people: @joaomcteixeira or @jgreener64. Both very skilled structural bioinformaticians and very active on Github.

**Comment by lpantano** [comment]
Thank you @JoaoRodrigues,  @joaomcteixeira or @jgreener64 are you interested on this tool and participate as reviewers? Thanks!

**Comment by joaomcteixeira** [comment]
@JoaoRodrigues @lpantano I am glad to help with this review process, it is a tool related to my background and research interests. I declare no conflict of interests.

**Comment by lpantano** [comment]
Thank you, @joaomcteixeira. I will add you tomorrow!

**Comment by CunliangGeng** [comment]
> Thank you for addressing my points! I'd only add somewhere in the documentation page a mention to the `fetch` function. It's good for me! Approved!! Great work!
@JoaoRodrigues Thanks for the comment. The `fetch` has been mentioned in the docs but the docs build failed. Now it is fixed https://pdb2sql.readthedocs.io.

**Comment by lpantano** [comment]
@whedon add @joaomcteixeira as reviewer

**Comment by whedon** [comment]
OK, @joaomcteixeira is now a reviewer

**Comment by lpantano** [comment]
@joaomcteixeira, I updated the top message so you have a checklist as the other reviewers to go through. Thanks!

**Comment by joaomcteixeira** [comment]
Thank you, I will do it during the course of today/tomorrow.

**Comment by joaomcteixeira** [comment]
Dear @lpantano and @NicoRenaud 

I have the article and the details of the project proposed. The package presented is relevant to our community and can help facilitate several implementations on a daily basis. Also, it has a good basis to allow the implementation of additional functionalities. Congratulations to the authors for this package!

In the continuation of the review process, I have raised 4 issues in the `pdb2sql` repository which refer to code implementations and which I found relevant to address before publication. Also, I list here additional minor concerns that I consider should be addressed also before acceptance.

- [ ] provide documentation at the module level: `import pdb2sql; help(pdb2sql)` . Though the documentation website states that the user should `from pdb2sql import pdb2sql`, the `pdb2sql` library level is the first place where a user at a Python prompt will look for help.  I was expecting here a general overview of how to use the library along with external references for more detailed explanations.
- [ ] bind one of the general printing actions in python to the `.pprint()` method, also provide a general `repr` message instead of the memory coordinates:
```python
In [117]: pdb_db                                                                                                                                  
Out[117]: <pdb2sql.pdb2sqlcore.pdb2sql at 0x7f3164223890>

In [118]: print(pdb_db)                                                                                                                           
<pdb2sql.pdb2sqlcore.pdb2sql object at 0x7f3164223890>
```
- [ ] I found no place in the documentation that addresses the fact that `HETATM` are ignored.  It would be valuable to have explicit clarification on the decisions to which information is parsed out from the original PDB.
- [ ] I encourage the authors to write the complete kwargs options in `pdb2sql.get` function.
- [ ] documentation of `pdb2sql.exportpdb` is insuficient.
- [ ] what is the meaning of the `.commit()` method?

Have another comment for the authors, though this should be a concern that hinders publication, the authors might want to consider it for future implementations.

I found a bit anti-Pythonic that none of the methods of the `pdb2sql` core class return an instance of the same class. The return value is always a list, and this hinders functionalities like the following:

```python
pdb_db.get('*', resSeq=['1']).pprint()
```

Also, `pprint()` does not accept column `kwargs`. So, I wonder whether `pdb_db`'s `get` methods should return an instance of the same class containing just the subselection of the data.

I look forward to the reply of the authors to the issues raised.

**Comment by joaomcteixeira** [comment]
I see the authors have addressed my issues. I would like them to address the questions I raised in my previous post so I can finalize my review. @lpantano @NicoRenaud 
Kind Regards,

**Comment by NicoRenaud** [comment]
@joaomcteixeira Thanks for your review and your comments ! We have addressed your last comment about returning a class instance and implemented that in the `__call__` method of the `pdb2sql` class.
It is now possible to do the following:

```python
import pdb2sql
db = pdb2sql('1AK4.pdb')
db_chainA = db(chainID='A')
```
`db_chainA` is there a `pdb2sql` instance as you suggested. Thanks for this comment, it is very valuable to have such method.

**Comment by joaomcteixeira** [comment]
Dear @NicoRenaud 

Thanks for all the new additions and corrections to the `pdb2sql` package. I can appreciate you addressed all of my issues, and this indeed improved the quality of your package. Also, I appreciate much that you considered the creation of new instances. Thanks!

I just found a [minor issue regarding the tests](https://github.com/DeepRank/pdb2sql/issues/47), that I would like you to address before my recommendation to acceptance.

@lpantano 
The authors have addressed all my suggestions. I have raised a final issue (https://github.com/DeepRank/pdb2sql/issues/47) for the authors to address. After the authors have addressed that issue I fully recommend `pdb2sql` to publication in JOSS.

Best Wishes and Congratulations!

**Comment by arfon** [comment]
:wave: @NicoRenaud - when do you think you might be able to address @joaomcteixeira's feedback? JOSS [is now open again](https://blog.joss.theoj.org/2020/05/reopening-joss) for submissions and we're actively trying to wrap up existing reviews.

**Comment by NicoRenaud** [comment]
@arfon we updated the instruction to manually run the test as pointed out by @joaomcteixeira. We could also follow his suggestion to change the exec path but I don't really have the time to do that at the moment. So from our side we are done I think

**Comment by NicoRenaud** [comment]
@arfon just to let you know that @joaomcteixeira has implemented his own suggestions for the test so we are officially done with the review on our side ! Thanks again @joaomcteixeira  !!

**Comment by lpantano** [comment]
Perfect! @NicoRenaud can you confirm the latest version is 0.2.2? if that is right, can you work on a zenodo archive of this version and having the title and authors matching what is shown in the paper? Thanks!

**Comment by lpantano** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btp163 is OK
- 10.1093/bioinformatics/btg299 is OK
- 10.1002/(SICI)1096-987X(20000130)21:2<79::AID-JCC1>3.0.CO;2-B is OK
-  10.25080/Majora-629e541a-00e  is OK
- 10.1093/bioinformatics/btz496 is OK
- 10.1093/bioinformatics/btr168 is OK
- 10.1371/journal.pcbi.1006791 is OK
- 10.1371/journal.pone.0161879 is OK
- 10.1093/nar/gky949 is OK
- 10.1101/483305 is OK
- 10.1002/prot.10393 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lpantano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02077/joss.02077/10.21105.joss.02077.pdf)

**Comment by CunliangGeng** [comment]
> Perfect! @NicoRenaud can you confirm the latest version is 0.2.2? if that is right, can you work on a zenodo archive of this version and having the title and authors matching what is shown in the paper? Thanks!
Thanks @lpantano, the version now is 0.4.0, and zenodo archive has been updated with your suggestions, see https://doi.org/10.5281/zenodo.3860329.

**Comment by lpantano** [comment]
@whedon set version as 0.4.0

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by lpantano** [comment]
@whedon set 0.4.0 as version

**Comment by whedon** [comment]
OK. 0.4.0 is the version.

**Comment by lpantano** [comment]
@whedon set 10.5281/zenodo.3860329 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3860329" target="_blank">10.5281/zenodo.3860329</a> is the archive.

**Comment by lpantano** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btp163 is OK
- 10.1093/bioinformatics/btg299 is OK
- 10.1002/(SICI)1096-987X(20000130)21:2<79::AID-JCC1>3.0.CO;2-B is OK
-  10.25080/Majora-629e541a-00e  is OK
- 10.1093/bioinformatics/btz496 is OK
- 10.1093/bioinformatics/btr168 is OK
- 10.1371/journal.pcbi.1006791 is OK
- 10.1371/journal.pone.0161879 is OK
- 10.1093/nar/gky949 is OK
- 10.1101/483305 is OK
- 10.1002/prot.10393 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1460

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1460, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
👋 @NicoRenaud - please merge the minor changes in https://github.com/DeepRank/pdb2sql/pull/54 or let me know what you disagree with in it

**Comment by CunliangGeng** [comment]
@danielskatz Many thanks for the changes, it's merged.

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1265982623756713984) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1461
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02077](https://doi.org/10.21105/joss.02077)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @i-mtz, @JoaoRodrigues, @joaomcteixeira for  reviewing, and to @lpantano for editing!

And congratulations to @NicoRenaud and co-author!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02077/status.svg)](https://doi.org/10.21105/joss.02077)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02077">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02077/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02077/status.svg
   :target: https://doi.org/10.21105/joss.02077
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02077/status.svg)](https://doi.org/10.21105/joss.02077)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
