### ISSUE TITLE
[PRE REVIEW]: LATTE: Lightcurve Analysis Tool for Transiting Exoplanets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2078]
**Submitting author:** @noraeisner (<a href="http://orcid.org/0000-0002-9138-9028">N. L. Eisner</a>)
**Repository:** <a href="https://github.com/noraeisner/LATTE" target ="_blank">https://github.com/noraeisner/LATTE</a>
**Version:** v0.0.12
**Editor:** @xuanxu
**Reviewers:** @christinahedges, @aureliocarnero
**Managing EiC:** Arfon Smith

**Author instructions**

Thanks for submitting your paper to JOSS @noraeisner. **Currently, there isn't an JOSS editor assigned** to your paper.

@noraeisner if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2078 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=2.18 s (30.7 files/s, 49828.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Bourne Shell                     1              0             18          85302
Python                          38           2678           3299           6742
Fortran 90                      12            595            694           2243
Jupyter Notebook                 8              0           4016           1962
TeX                              3             28             18            508
Markdown                         4            257              0            295
make                             1              7              8             29
-------------------------------------------------------------------------------
SUM:                            67           3565           8053          97081
-------------------------------------------------------------------------------


Statistical information for the repository '2078' was gathered on 2020/02/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
noraeisner                      54       1504293        1491574          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
noraeisner                12719            0.8          0.6               16.16
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02078/joss.02078/10.21105.joss.02078.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1117/1.JATIS.1.1.014003 is OK
- 10.3847/1538-3881/aa9be0 is OK
- 10.1111/j.1365-2966.2011.19932.x is OK
- 10.1111/j.1365-2966.2004.07657.x is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1117/12.2233418 is OK
- 10.1086/667698 is OK
- 10.1093/mnras/sty2472 is OK
- 10.1051/0004-6361/201833051 is OK

MISSING DOIs

- https://doi.org/10.1093/mnras/staa138 may be missing for title: Planet Hunters TESS I: TOI 813, a subgiant hosting a transiting Saturn-sized planet on an 84-day orbit

INVALID DOIs

- None
```

**Comment by arfon** [comment]
:wave: @noraeisner. Thanks for your submission to JOSS! 

Can you tell me if this paper has an accompanying paper with AAS journals?

**Comment by noraeisner** [comment]
Hi Arfon! No, this paper doesn't have an accompanying AAS paper.

**Comment by danielskatz** [comment]
👋 @xuanxu - can you edit this submission?

**Comment by xuanxu** [comment]
@whedon assign @xuanxu as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by xuanxu** [comment]
@christinahedges: would you be willing to review this paper? I think your knowledge of astronomy and Python makes you a great fit for this submission.

**Comment by xuanxu** [comment]
@aureliocarnero: would you be willing to review this paper? I think your knowledge of Astrophysics and Python makes you a great fit for this submission.

**Comment by christinahedges** [comment]
Hey @xuanxu I could review this paper, but I believe the authors are visiting my group soon to collaborate. Would that make me conflicted? If not, happy to review!

**Comment by aureliocarnero** [comment]
sure! Im happy to review it

**Comment by xuanxu** [comment]
@christinahedges Thanks! If you don't have previous/recent association with the author and you think you can make an impartial scientific evaluation I don't think there's conflict, or if there is it's minor and can be waived.

**Comment by xuanxu** [comment]
Thanks @aureliocarnero & @christinahedges! I'll start the review issue now.

**Comment by xuanxu** [comment]
@whedon add @christinahedges as reviewer

**Comment by whedon** [comment]
OK, @christinahedges is now a reviewer

**Comment by xuanxu** [comment]
@whedon add @aureliocarnero as reviewer

**Comment by whedon** [comment]
OK, @aureliocarnero is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2101.

**Comment by xuanxu** [comment]
@christinahedges, @aureliocarnero: please head over to #2101 where the review will take place.
