### ISSUE TITLE
[REVIEW]: scPCA: A toolbox for sparse contrastive principal component analysis in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2079]
**Submitting author:** @PhilBoileau (<a href="http://orcid.org/0000-0002-4850-2507">Philippe Boileau</a>)
**Repository:** <a href="https://github.com/PhilBoileau/scPCA" target ="_blank">https://github.com/PhilBoileau/scPCA</a>
**Version:** v1.1.10
**Editor:** @csoneson
**Reviewer:** @fabian-s, @LTLA
**Archive:** <a href="https://doi.org/10.5281/zenodo.3686201" target="_blank">10.5281/zenodo.3686201</a>

## Status

[![status](https://joss.theoj.org/papers/7f0f1271ede7aba120d71c9b5a14c865/status.svg)](https://joss.theoj.org/papers/7f0f1271ede7aba120d71c9b5a14c865)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7f0f1271ede7aba120d71c9b5a14c865"><img src="https://joss.theoj.org/papers/7f0f1271ede7aba120d71c9b5a14c865/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7f0f1271ede7aba120d71c9b5a14c865/status.svg)](https://joss.theoj.org/papers/7f0f1271ede7aba120d71c9b5a14c865)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/PhilBoileau/scPCA" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@fabian-s & @LTLA, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/PhilBoileau/scPCA">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@PhilBoileau) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/PhilBoileau/scPCA">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@PhilBoileau) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @fabian-s, @LTLA it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18129/B9.bioc.SingleCellExperiment is OK
- 10.1198/jasa.2009.0121 is OK
- 10.1198/106186006X113430 is OK
- 10.1038/s41467-018-04608-8 is OK
- 10.1101/836650 is OK
- 10.1186/gb-2004-5-10-r80 is OK
- 10.1038/nmeth.3252 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02079/joss.02079/10.21105.joss.02079.pdf)

**Comment by csoneson** [comment]
👋 @fabian-s, @LTLA - this is where the review takes place. Your checklists, together with additional instructions, are available in the first post above. Don't hesitate to ping me if you have questions. 

@PhilBoileau - please also have a look at the reviewer checklist and make sure that nothing is missing from your repository (if so, you can fix it already now to simplify the review process)

**Comment by PhilBoileau** [comment]
@csoneson - Thank you for organizing the review process! I reviewed the checklist, the `scPCA` package satisfies all the requirements.

@fabian-s, @LTLA - Thank you for volunteering to review our package. We're looking forward to receiving your feedback.

**Comment by fabian-s** [comment]
This seems fine -- one minor nitpick at PhilBoileau/scPCA/issues/36 regarding a potentially missing comparison to existing alternative approaches, but that is debatable...

**Comment by PhilBoileau** [comment]
Thanks, @fabian-s. I've added a line that briefly details the results of our comparisons to existing methods.

**Comment by PhilBoileau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02079/joss.02079/10.21105.joss.02079.pdf)

**Comment by fabian-s** [comment]
seems fine to me now.

**Comment by PhilBoileau** [comment]
I made slight edits to the newly added sentence, should read a little better now.

**Comment by PhilBoileau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02079/joss.02079/10.21105.joss.02079.pdf)

**Comment by csoneson** [comment]
👋 @LTLA, just wanted to check in on your review and when you think you might have some comments for @PhilBoileau. Thanks!

**Comment by LTLA** [comment]
Oops. Forgot about this. Alright, I'll hold up my end of the deal. Expect comments tomorrow evening.

**Comment by LTLA** [comment]
Looks good in general. Various comments:

- PhilBoileau/scPCA#38
- PhilBoileau/scPCA#39
- PhilBoileau/scPCA#40
- PhilBoileau/scPCA#41
- PhilBoileau/scPCA#42

**Comment by PhilBoileau** [comment]
Thank you for your thorough review, @LTLA! I've addressed most of your comments in a recent PR: [PhilBoileau/scPCA/pull/43](https://github.com/PhilBoileau/scPCA/pull/43). I've also responded to [PhilBoileau/scPCA#40](https://github.com/PhilBoileau/scPCA/issues/40). I hope that you find the changes satisfactory!

**Comment by LTLA** [comment]
Looks good to me.

**Comment by csoneson** [comment]
@fabian-s , @LTLA - thanks a lot for your careful reviews!

> Looks good to me.

@LTLA - does this mean that the outstanding box in your checklist above could also be checked, or are there other remaining issues?

**Comment by LTLA** [comment]
Done.

**Comment by PhilBoileau** [comment]
Thank you @fabian-s and @LTLA for your helpful comments and suggestions! They are much appreciated. And thank you for organizing the reviews, @csoneson!

**Comment by csoneson** [comment]
Great!
@PhilBoileau - I'll look over the submission and get back to you with the next steps shortly.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02079/joss.02079/10.21105.joss.02079.pdf)

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18129/B9.bioc.SingleCellExperiment is OK
- 10.1198/jasa.2009.0121 is OK
- 10.1198/106186006X113430 is OK
- 10.1038/s41467-018-04608-8 is OK
- 10.1101/836650 is OK
- 10.1186/gb-2004-5-10-r80 is OK
- 10.1038/nmeth.3252 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@PhilBoileau - this looks all good! Next steps:

- [ ] Make a tagged release of the package, and post the version tag of the release here
- [ ] Create a Zenodo archive. Make sure that the Zenodo record has the same title and author list as the paper (you can also add ORCiDs)
- [ ] Post the doi of the Zenodo record here

I would also recommend clarifying to users (e.g. in your README) the relationship between this paper and the bioRxiv preprint, e.g. to make it easier to know when to cite which paper.

**Comment by PhilBoileau** [comment]
Thanks, @csoneson! Here you go:

- The release version tag is [v1.1.10](https://github.com/PhilBoileau/scPCA/releases/tag/v1.1.10)
- The Zenodo doi is [10.5281/zenodo.3686201](https://doi.org/10.5281/zenodo.3686201))

I've also added a *Citation* section in the README indicating how to cite the package. I'll update it to include the JOSS reference once published.

**Comment by csoneson** [comment]
@whedon set 10.5281/zenodo.3686201 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3686201" target="_blank">10.5281/zenodo.3686201</a> is the archive.

**Comment by csoneson** [comment]
@whedon set v1.1.10 as version

**Comment by whedon** [comment]
OK. v1.1.10 is the version.

**Comment by csoneson** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18129/B9.bioc.SingleCellExperiment is OK
- 10.1198/jasa.2009.0121 is OK
- 10.1198/106186006X113430 is OK
- 10.1038/s41467-018-04608-8 is OK
- 10.1101/836650 is OK
- 10.1186/gb-2004-5-10-r80 is OK
- 10.1038/nmeth.3252 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1336

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1336, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by csoneson** [comment]
@openjournals/joss-eics - this paper is ready to be accepted!

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1232103611339038726) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1337
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02079](https://doi.org/10.21105/joss.02079)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @PhilBoileau, your JOSS paper is published! 🚀 

Big thanks to our editor: @csoneson, and the reviewers: @fabian-s, @LTLA — your contribution to JOSS is appreciated 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02079/status.svg)](https://doi.org/10.21105/joss.02079)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02079">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02079/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02079/status.svg
   :target: https://doi.org/10.21105/joss.02079
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02079/status.svg)](https://doi.org/10.21105/joss.02079)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
