### ISSUE TITLE
[REVIEW]: VCC: A framework for building containerized reproducible cluster software environments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#208]
**Submitting author:** @joshiggins (<a href="http://orcid.org/0000-0003-1551-5552">Joshua Higgins</a>)
**Repository:** <a href="https://github.com/hpchud/vccjs" target ="_blank">https://github.com/hpchud/vccjs</a>
**Version:** v1.0
**Editor:** @pjotrp
**Reviewer:** @brainstorm
**Archive:** <a href="http://dx.doi.org/10.6084/m9.figshare.4763857" target="_blank">10.6084/m9.figshare.4763857</a>

## Status

[![status](http://joss.theoj.org/papers/8348377e25b3ce70596888fd643d5e82/status.svg)](http://joss.theoj.org/papers/8348377e25b3ce70596888fd643d5e82)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/8348377e25b3ce70596888fd643d5e82"><img src="http://joss.theoj.org/papers/8348377e25b3ce70596888fd643d5e82/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/8348377e25b3ce70596888fd643d5e82/status.svg)](http://joss.theoj.org/papers/8348377e25b3ce70596888fd643d5e82)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/hpchud/vccjs" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/hpchud/vccjs">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@joshiggins) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @brainstorm it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by brainstorm** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by brainstorm** [comment]
@joshiggins

1) The LICENSE seems a bit barebones to me... is it public domain? A clearer definition or reference would be great.

2) The update process fails on me due to hardcoded `/usr/bin` paths in the auto-update process. I would recommend to change the documentation and the `vcc` script so that it refers to `$HOME/bin` which has much higher chances to have suitable permissions rather than `/usr` and `/usr/local`:

```
$ vcc update
Updating VCC tool...

/usr/bin/vcc-new: Permission denied
There was a problem updating the script. Check proxy settings.
```

I'll continue reviewing, just wanted you to know early and as I go...

**Comment by brainstorm** [comment]
There are no performance claims to be confirmed in the `paper.md` file, or am I missing some benchmarks I have not seen? 

Other than the points outlined above, all the rest looks great, good job @joshiggins!

**Comment by pjotrp** [comment]
Thanks @brainstorm for the fast turnaround. @joshiggins can you address the point? We also need to tick the OSI box for JOSS before acceptance.

**Comment by pjotrp** [comment]
On a personal note, it may be worth looking into Nix and Guix for true reproducibly installs (and they play well inside containers). Bruno has a nice [writeup](https://medium.com/@bmpvieira/a-truly-reproducible-scientific-paper-5059b282ee9a#.c7wny4wx6).

**Comment by joshiggins** [comment]
@brainstorm @pjotrp the MIT license text is copied from https://opensource.org/licenses/MIT as far as I know is the real deal?!

The claim that containers can be more performant than VMs is based on the reference _Felter, 2014_ (in `paper.bib`) but I wasnt sure how to indicate this in the markdown.

Thanks for checking everything! The `vcc` script - it will now try and update itself in whatever directory it's currently in, so will deal with `$HOME/bin` or `/usr/bin`, wherever, and give more helpful messages if this isn't possible. 

I've bumped the release to `v1.1` for the update functionality (the released version of the script updates from a tag, not from `master`), hope this won't mess up the submission.....

p.s. the linked article was a good read! I will try those out for sure.

**Comment by pjotrp** [comment]
MIT license is OSI approved. @arfon I believe we can accept this paper using the latest release.

**Comment by brainstorm** [comment]
Indeed, all remaining boxes checked ;)

**Comment by arfon** [comment]
@joshiggins - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by joshiggins** [comment]
@arfon here is the DOI of the archive on figshare https://doi.org/10.6084/m9.figshare.4763857 cheers!

**Comment by arfon** [comment]
@whedon set 10.6084/m9.figshare.4763857 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.6084/m9.figshare.4763857" target="_blank">10.6084/m9.figshare.4763857</a> is the archive.

**Comment by arfon** [comment]
Hi @joshiggins - minor issue here - you actually need to cite the items in your `paper.bib` file for Pandoc to include them in the compiled paper PDF. You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html).

**Comment by joshiggins** [comment]
@arfon sorry about that, I missed the [@...] syntax in the example, but it is clear having looked again :laughing:
I just updated the `paper.md`.

**Comment by arfon** [comment]
@brainstorm many thanks for the review here and to @pjotrp for editing this one ✨ 

@joshiggins - your paper is now accepted into JOSS and your paper DOI is http://dx.doi.org/10.21105/joss.00208 ⚡️ 🚀 💥
