### ISSUE TITLE
[PRE REVIEW]: Tamaas: a library for elastic-plastic contact of periodic rough surfaces

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2080]
**Submitting author:** @prs513rosewood (<a href="http://orcid.org/0000-0002-4138-1052">Lucas Frérot</a>)
**Repository:** <a href="https://c4science.ch/source/tamaas/" target ="_blank">https://c4science.ch/source/tamaas/</a>
**Version:** 2.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @likask, @agshvarts, @srmnitc, @chennachaos
**Managing EiC:** Kevin M. Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @prs513rosewood. **Currently, there isn't an JOSS editor assigned** to your paper.

@prs513rosewood if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2080 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2080 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-9847f98e9ec6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.cma.2019.04.006 is OK
- 10.1016/j.jmps.2018.02.015 is OK
- 10.1016/0890-6955(92)90064-N is OK
- 10.1063/1.1699786 is OK
- 10.1088/0953-8984/17/1/R01 is OK
- 10.1016/S0043-1648(99)00113-1 is OK
- 10.1029/2012GL054143 is OK
- 10.1007/s00466-017-1392-5 is OK
- 10.1016/j.ijengsci.2019.02.003 is OK
- 10.1007/s00466-018-1556-y is OK
- 10.1016/j.finel.2015.02.003 is OK
- 10.1115/1.2833523 is OK
- 10.1016/S0307-904X(79)80030-X is OK
- 10.1016/j.triboint.2017.04.023 is OK
- 10.1007/s11249-014-0395-z is OK
- 10.1016/j.ijsolstr.2014.09.019 is OK
- 10.1016/j.jmps.2017.07.016 is OK

MISSING DOIs

- https://doi.org/10.1103/physreve.86.035601 may be missing for title: Contact between Representative Rough Surfaces

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.45 s (535.5 files/s, 65453.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             84           2029           3085           7361
C/C++ Header                    95           1492           3857           6080
Python                          47            906           1253           2473
reStructuredText                 5            173             52            279
Markdown                         2             57              0            172
SVG                              1              1              1             80
Dockerfile                       1              4              2             23
YAML                             3              5             11             20
make                             1              8              4             20
JSON                             1              0              0              6
Bourne Shell                     1              1              0              2
-------------------------------------------------------------------------------
SUM:                           241           4676           8265          16516
-------------------------------------------------------------------------------


Statistical information for the repository '2080' was gathered on 2020/02/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Guillaume Anciaux               35         13370           1251           11.44
Lucas Frérot                   582         57128          46064           80.75
Son Pham-Ba                     49          3890           1521            4.23
Valentine                       17          3450            550            3.13
Valentine Rey                    1           553             14            0.44

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Guillaume Anciaux          2418           18.1         12.5               33.50
Lucas Frérot              22340           39.1         20.1               29.10
Son Pham-Ba                1588           40.8         18.7               24.24
Valentine                  1864           54.0         40.8               22.85
Valentine Rey               142           25.7         44.9               38.03
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you advise on what is going wrong with paper compilation?

**Comment by arfon** [comment]
I think this a regression I recently introduced. Trying to fix now. In the meantime, simply asking Whedon to generate the proof should work fine.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02080/joss.02080/10.21105.joss.02080.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@prs513rosewood thanks for this submission. For works to be considered for JOSS the software repositories need to be fully public and allow for anybody to post issues and submit PR's to the software. This functionality does not seem to be enabled on your repository as far as I can see: https://c4science.ch/source/tamaas/. 
Please enable this functionality now for this submission to be considered in JOSS. In particular our criteria state _"the software associated with your submission must"_:
- [ ] Be stored in a repository that can be cloned without registration.
- [ ] Be stored in a repository that is browsable online without registration.
- [ ] Have an issue tracker that is readable without registration.
- [ ] Permit individuals to create issues/file tickets against your repository.

**Comment by prs513rosewood** [comment]
Thanks for the feedback.

The issue tracker is not directly visible from the repository page, but is accessible from the project page (link on the left navigation bar): https://c4science.ch/project/view/2036/
There's also a link to submit bugs/issues to the tracker. As for PRs, the Phabricator procedure is described in [this guide](https://secure.phabricator.com/book/phabricator/article/arcanist/), but perhaps should I add the necessary steps in the README file?

**Comment by Kevin-Mattheus-Moerman** [comment]
@prs513rosewood thanks for those comments. So I take it posting issues is possible then. In relation to that "Phabricator procedure",  is that the process for users to create a pull request? 

Yes, can you describe (and link to) both the issue tracker and the PR approach in the README?

**Comment by prs513rosewood** [comment]
[Phabricator](https://www.phacility.com/phabricator/) is the code hosting software that c4science (the site where Tamaas is hosted) uses. I have added the procedures to post an issue and send a pull request to the README.

**Comment by Kevin-Mattheus-Moerman** [comment]
@chennachaos @likask @srmnitc @tjhei @sriharisundar @rudraa @MRezaYaghoobi @dbeurle @diogocecilio would you be interested in reviewing this submission on "elastic-plastic contact" for [JOSS](https://joss.theoj.org/)? The [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) focuses on the [software](https://c4science.ch/source/tamaas/) this [short paper](https://github.com/openjournals/joss-papers/blob/joss.02080/joss.02080/10.21105.joss.02080.pdf). 
This is a pre-review issue, once sufficient reviewers have been recruited I'll open a review issue where the review will take place.

**Comment by Kevin-Mattheus-Moerman** [comment]
@chennachaos thanks for you review efforts for other submissions as well! Let me know if I'm inviting you too often :smile:

**Comment by srmnitc** [comment]
@Kevin-Mattheus-Moerman I think I can review this submission.

**Comment by likask** [comment]
Hello @Kevin-Mattheus-Moerman, My co-developer and colleague, @agshvarts, working on a similar problem in FEM. He knows authors papers, and physical problem well. He is keen to make a review. I will help him with review as well since we are interested in generating rough surfaces and the problem itself.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @likask as reviewer

**Comment by whedon** [comment]
OK, @likask is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @agshvarts as reviewer

**Comment by whedon** [comment]
OK, @agshvarts is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @srmnitc as reviewer

**Comment by whedon** [comment]
OK, @srmnitc is now a reviewer

**Comment by chennachaos** [comment]
Hi @Kevin-Mattheus-Moerman,
Appreciate the opportunity as well as your concern. Happy to provide a review for this library also. Do it count me in if you need more reviews. But please note that I will only be able to work on this after finishing the one on FSI.

**Comment by agshvarts** [comment]
Hi @Kevin-Mattheus-Moerman, thank you for assigning me, I am eager to get hands-on with this code and review it. However, to avoid possible issues I need to state the following. There are a couple of published conference proceedings (2017, 2019) where I appear as a co-author with two of the authors of this submission (G. Anciaux, J.-F. Molinari).  These proceedings were communicated by my former thesis supervisor (V. Yastrebov, Mines ParisTech) who combined and presented at conferences results from two projects: my PhD and his separate collaboration with G. Anciaux and J.-F. Molinari.  However, these were two unrelated projects both in terms of funding and published articles, i.e. I personally have never worked together with the authors of this submission. I believe that I can make an impartial assessment of this work, and I hope that the potential COI could be waived.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @chennachaos as reviewer

**Comment by whedon** [comment]
OK, @chennachaos is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@agshvarts thanks for sharing that information. I would consider that a minor COI. However given that there are 3 other impartial reviewers I feel we can proceed, and it does sound like you will be able to provide valuable feedback.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2121.
