### ISSUE TITLE
[PRE REVIEW]: turtleFSI: A Robust and Monolithic FEniCS-based Fluid-Structure Interaction Solver

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2081]
**Submitting author:** @albansouche (<a href="http://orcid.org/0000-0001-7547-7979">Alban Souche</a>)
**Repository:** <a href="https://github.com/KVSlab/turtleFSI.git" target ="_blank">https://github.com/KVSlab/turtleFSI.git</a>
**Version:** v1.3
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @nathanquinlan, @chennachaos, @JaroslavHron
**Managing EiC:** Kevin M. Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @albansouche. **Currently, there isn't an JOSS editor assigned** to your paper.

@albansouche if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (336.8 files/s, 29269.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          24            497            532           1251
reStructuredText                 6            116             58            282
Markdown                         3             76              0            222
TeX                              1              6              0             76
DOS Batch                        1              8              1             27
YAML                             1             11              6             26
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                            37            718            603           1894
-------------------------------------------------------------------------------


Statistical information for the repository '2081' was gathered on 2020/02/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Aslak Bergersen                 47          4199           4411           72.01
albansouche                     27          2919            427           27.99

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Aslak Bergersen            1666           39.7          6.8               17.23
albansouche                 614           21.0          6.1               21.82
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/j.compstruc.2011.02.019 may be missing for title: Fluid-structure interactions using different mesh motion techniques.

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02081/joss.02081/10.21105.joss.02081.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@albansouche thanks for your submission! I'll be handling this submission. We'll first review the work for scope and if we deem it suitable for JOSS I'll work to find reviewers. 
In the meantime, you could troubleshoot that missing DOI listed above. You can run `@whedon generate pdf` to update the proof here yourself.

**Comment by Kevin-Mattheus-Moerman** [comment]
A colleague at NUIG @nathanquinlan (https://orcid.org/0000-0002-5720-5811) has agreed to help review this work

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @nathanquinlan as reviewer

**Comment by whedon** [comment]
OK, @nathanquinlan is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@albansouche let me know if you'd like to recommend any reviewers at this point

**Comment by Kevin-Mattheus-Moerman** [comment]
@chrisrichardson @garth-wells @chennachaos @weymouth @BenjaminRueth @JaroslavHron 
Would you be interested in reviewing this work for [JOSS](joss.theoj.org/): **turtleFSI: A Robust and Monolithic FEniCS-based Fluid-Structure Interaction Solver**? The review focuses on [the software](https://github.com/KVSlab/turtleFSI.git) and [this short paper](https://github.com/openjournals/joss-papers/blob/joss.02081/joss.02081/10.21105.joss.02081.pdf)
Let me know if you have any questions.

**Comment by albansouche** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02081/joss.02081/10.21105.joss.02081.pdf)

**Comment by albansouche** [comment]
@Kevin-Mattheus-Moerman Thank you for handling our submission. I have added the DOIs of the references in the new proof.

**Comment by chennachaos** [comment]
Hi @Kevin-Mattheus-Moerman. Thanks for the opportunity.
This looks very interesting! Count me in as a reviewer.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @chennachaos as reviewer

**Comment by whedon** [comment]
OK, @chennachaos is now a reviewer

**Comment by JaroslavHron** [comment]
Hi @Kevin-Mattheus-Moerman, I will be happy to review this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @JaroslavHron as reviewer

**Comment by whedon** [comment]
OK, @JaroslavHron is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2089.
