### ISSUE TITLE
[PRE REVIEW]: SARAS: A general-purpose PDE solver for fluid dynamics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2084]
**Submitting author:** @roshansamuel (<a href="http://orcid.org/0000-0002-1280-9881">Roshan Samuel</a>)
**Repository:** <a href="https://github.com/roshansamuel/saras" target ="_blank">https://github.com/roshansamuel/saras</a>
**Version:** v1.0
**Editor:** @kyleniemeyer
**Reviewers:** @harpolea, @dlagrava
**Managing EiC:** Kristen Thyng

**Author instructions**

Thanks for submitting your paper to JOSS @roshansamuel. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kyleniemeyer.

@roshansamuel if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.28 s (418.7 files/s, 56975.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                           340           1447           1877          46862
C++                             48           1711           4874           5987
JavaScript                      89             80             66           1621
CSS                              3            277             44           1376
C/C++ Header                    22            544           1515           1011
Python                          11            270            558            659
Markdown                         2             84              0            283
XML                              1              5              7            182
TeX                              1             16              0            167
CMake                           13             48            547            146
YAML                             2             52            149            108
Bourne Shell                     3             22            147             59
-------------------------------------------------------------------------------
SUM:                           535           4556           9784          58461
-------------------------------------------------------------------------------


Statistical information for the repository '2084' was gathered on 2020/02/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Roshan Samuel                    8         22601           3656          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Roshan Samuel             18945           83.8          0.0               36.97
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1007/3-540-49372-7_24 may be missing for title: Arrays in Blitz++

INVALID DOIs

- https://doi.org/10.1017/S0305004100023197 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1063/1.1761178 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.jpdc.2017.10.014 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1098/rspa.1937.0036 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1063/1.1761178 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1137/1.9780898719505 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/0021-9991(82)90058-4 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/0017-9310(72)90054-3 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1098/rspa.1991.0076 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1007/BF01448839 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1007/978-3-642-84108-8 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1007/978-3-642-56026-2 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1088/1742-6596/899/2/022017 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1007/s12043-013-0594-4 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1017/9781316810019 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02084/joss.02084/10.21105.joss.02084.pdf)

**Comment by kthyng** [comment]
@whedon invite @kyleniemeyer as editor

**Comment by whedon** [comment]
@kyleniemeyer has been invited to edit this submission.

**Comment by kthyng** [comment]
@kyleniemeyer You were suggested — can you take this one on?

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
Hi @roshansamuel, any suggestions for reviewers from our list (mentioned at the top) would be appreciated; otherwise, I will look for some shortly.

Also, could you edit your article to remove the leading `https://doi.org/` from the DOI entries for each reference?

**Comment by roshansamuel** [comment]
Hi, @kyleniemeyer , the leading ``https://doi.org/`` have been removed from all the DOI entries. The missing DOI has been added as well.

From the list of reviewers, harpolea, mancellin, and dlagrava seem to have good overlap with the target audience of the solver. Hence I would like to suggest them as potential reviewers.

**Comment by roshansamuel** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1017/S0305004100023197 is OK
- 10.1063/1.1761178 is OK
- 10.1016/j.jpdc.2017.10.014 is OK
- 10.1098/rspa.1937.0036 is OK
- 10.1063/1.1761178 is OK
- 10.1137/1.9780898719505 is OK
- 10.1016/0021-9991(82)90058-4 is OK
- 10.1016/0017-9310(72)90054-3 is OK
- 10.1098/rspa.1991.0076 is OK
- 10.1007/BF01448839 is OK
- 10.1007/978-3-642-84108-8 is OK
- 10.1007/978-3-642-56026-2 is OK
- 10.1007/3-540-49372-7_24 is OK
- 10.1088/1742-6596/899/2/022017 is OK
- 10.1007/s12043-013-0594-4 is OK
- 10.1017/9781316810019 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hello @harpolea, would you be interested in reviewing this submission?

**Comment by kyleniemeyer** [comment]
Hi @dlagrava, are you interested and available to review this?

**Comment by harpolea** [comment]
Hi @kyleniemeyer, I'd be happy to review this!

**Comment by dlagrava** [comment]
Hi @kyleniemeyer, I will be happy to perform the review as well. Cheers.

**Comment by kyleniemeyer** [comment]
@harpolea @dlagrava Thanks to both of you! I'll assign you and initiate the review shortly.

**Comment by kyleniemeyer** [comment]
@whedon add @harpolea as reviewer

**Comment by whedon** [comment]
OK, @harpolea is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon add @dlagrava as reviewer

**Comment by whedon** [comment]
OK, @dlagrava is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2095.
