### ISSUE TITLE
[PRE REVIEW]: mimosa: A Modern Graphical User Interface for 2-level Mixed Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2085]
**Submitting author:** @johannes-titz (<a href="http://orcid.org/0000-0002-1102-5719">Johannes Titz</a>)
**Repository:** <a href="https://github.com/johannes-titz/mimosa" target ="_blank">https://github.com/johannes-titz/mimosa</a>
**Version:** v0.2.0
**Editor:** @cMadan
**Reviewers:** @strengejacke, @aj2duncan
**Managing EiC:** Kristen Thyng

**Author instructions**

Thanks for submitting your paper to JOSS @johannes-titz. **Currently, there isn't an JOSS editor assigned** to your paper.

@johannes-titz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.07 s (574.1 files/s, 61495.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                            17             86              0           1244
Markdown                         4            191              0            791
XML                              1              0             14            761
R                               15             56            276            604
TeX                              1             10              0            138
Rmd                              1             40             63              8
YAML                             1              0              0              3
-------------------------------------------------------------------------------
SUM:                            40            383            353           3549
-------------------------------------------------------------------------------


Statistical information for the repository '2085' was gathered on 2020/02/07.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18637/jss.v067.i01 is OK
- 10.1080/0305498930190401 is OK
- 10.5281/zenodo.1308157 is OK
- 10.1016/0883-0355(89)90027-X is OK
- 10.1198/tas.2011.11077 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02085/joss.02085/10.21105.joss.02085.pdf)

**Comment by kthyng** [comment]
@whedon invite @cMadan as editor

**Comment by whedon** [comment]
@cMadan has been invited to edit this submission.

**Comment by kthyng** [comment]
@cMadan Could you evaluate this submission as editor?

**Comment by danielskatz** [comment]
👋 @cMadan - just a quick ping at the start of a new week and a new AEiC on duty...

**Comment by cMadan** [comment]
@kthyng @danielskatz, I'm happy to serve as editor here!

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@johannes-titz, it looks like things are in order! Can you look through the list of JOSS reviewers (linked in the first comment in this issue) and suggest some who may be suitable? Thanks!

**Comment by johannes-titz** [comment]
@cMadan Thank you! I would like to suggest Daniel Lüdecke (github: strengejacke). He is an expert in mixed models and R. Otherwise, adibender and fabian-s might be suitable reviewers as they list mixed models in their domain. aj2duncan is another potential reviewer as he is familiar with shiny. 

By the way, the reviewers document has some duplicates. They should be easy to identify and remove, which would make the file a bit cleaner. It might also be worth to sort the file by some columns (by default), e.g. programming language--active reviews--review count. This would make the selection of reviewers a bit easier. (Just a suggestion.)

**Comment by cMadan** [comment]
@johannes-titz, thanks for the suggestions--both for reviewers and on our process. We are working to revamp how the reviewer list works to make it a bit more dynamic (e.g., active reviews, total count) and that's in progress. :)

**Comment by cMadan** [comment]
@strengejacke @fabian-s, would you be available and interested in reviewing this submission?

**Comment by strengejacke** [comment]
I'd be happy to review the submission!

**Comment by fabian-s** [comment]
nope, sorry. I got deadlines coming up :face_with_head_bandage:

**Comment by cMadan** [comment]
@strengejacke, thanks for agreeing to be a reviewer! We'll start the review after I've found a second reviewer.

@fabian-s, no problem, thanks for considering and the prompt response!

**Comment by cMadan** [comment]
@whedon add @strengejacke as reviewer

**Comment by whedon** [comment]
OK, @strengejacke is now a reviewer

**Comment by cMadan** [comment]
@adibender @aj2duncan, would you be available and interested in reviewing this submission?

**Comment by aj2duncan** [comment]
I'm happy to review this.

**Comment by cMadan** [comment]
@aj2duncan, that's great, thank you!

@johannes-titz @strengejacke, I will go ahead and start the review now.

**Comment by cMadan** [comment]
@whedon add @aj2duncan as reviewer

**Comment by whedon** [comment]
OK, @aj2duncan is now a reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2116.
