### ISSUE TITLE
[PRE REVIEW]: psychTestR: An R package for designing and conducting behavioural psychological experiments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2087]
**Submitting author:** @pmcharrison (<a href="http://orcid.org/0000-0002-9851-9462">Peter Harrison</a>)
**Repository:** <a href="https://github.com/pmcharrison/psychTestR" target ="_blank">https://github.com/pmcharrison/psychTestR</a>
**Version:** v2.19.0
**Editor:** @oliviaguest
**Reviewers:** @Cognitive-Modeller, @DivyaSeernani
**Managing EiC:** Kristen Thyng

**Author instructions**

Thanks for submitting your paper to JOSS @pmcharrison. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @oliviaguest.

@pmcharrison if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (985.9 files/s, 101123.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               62            461           1577           3700
XML                              1              0             12            686
Markdown                         5             92              0            310
YAML                             2              2              1            163
Rmd                             14            512           2128            138
TeX                              1             10              0             88
JavaScript                      12              3              5             61
-------------------------------------------------------------------------------
SUM:                            97           1080           3723           5146
-------------------------------------------------------------------------------


Statistical information for the repository '2087' was gathered on 2020/02/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Peter Harrison                   3            21              1            0.20
Peter M C Harrison              18          5384           5335           99.80

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Peter Harrison               69          328.6         14.6                7.25
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3758/s13428-018-01193-y is OK
- 10.3758/s13428-014-0458-y is OK
- 10.1111/bmsp.12057 is OK
- 10.1038/s41598-017-03586-z is OK
- 10.1038/s41598-018-30318-8 is OK
- 10.3758/s13428-019-01225-1 is OK
- 10.31234/osf.io/8gvhz is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02087/joss.02087/10.21105.joss.02087.pdf)

**Comment by kthyng** [comment]
@whedon invite @oliviaguest as editor

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by kthyng** [comment]
@oliviaguest you were suggested as editor!

**Comment by oliviaguest** [comment]
@whedon assign @oliviaguest  as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by oliviaguest** [comment]
Hi @pmcharrison, if you have anybody in mind that you think is especially suitable please let me know. I have already sent off some invitations but I value your input too, of course — and thank you for submitting to JOSS. 😺

**Comment by oliviaguest** [comment]
@whedon add @Cognitive-Modeller as reviewer

**Comment by whedon** [comment]
OK, @Cognitive-Modeller is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @DivyaSeernani as reviewer

**Comment by whedon** [comment]
OK, @DivyaSeernani is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2088.

**Comment by oliviaguest** [comment]
:wave: @Cognitive-Modeller @DivyaSeernani — thank you both for accepting to review this! Please go to #2088 to start the process. :smile_cat:

**Comment by pmcharrison** [comment]
> Hi @pmcharrison, if you have anybody in mind that you think is especially suitable please let me know. I have already sent off some invitations but I value your input too, of course — and thank you for submitting to JOSS.

Hi @oliviaguest, thanks very much for finding reviewers so quickly! I was not sure who to suggest myself, but thank you for offering the opportunity.
