### ISSUE TITLE
[REVIEW]: Ramble: Higher-Order Functions for Parsing in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#209]
**Submitting author:** @chappers (<a href="http://orcid.org/0000-0002-2089-3796">Chapman Siu</a>)
**Repository:** <a href="https://github.com/chappers/Ramble" target ="_blank">https://github.com/chappers/Ramble</a>
**Version:** v0.1.1
**Editor:** @arfon
**Reviewer:** @pjotrp
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.438282" target="_blank">10.5281/zenodo.438282</a>

## Status

[![status](http://joss.theoj.org/papers/1b33a8141e698aa4cf038b3c5c9bbfd8/status.svg)](http://joss.theoj.org/papers/1b33a8141e698aa4cf038b3c5c9bbfd8)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/1b33a8141e698aa4cf038b3c5c9bbfd8"><img src="http://joss.theoj.org/papers/1b33a8141e698aa4cf038b3c5c9bbfd8/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/1b33a8141e698aa4cf038b3c5c9bbfd8/status.svg)](http://joss.theoj.org/papers/1b33a8141e698aa4cf038b3c5c9bbfd8)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/chappers/Ramble/tree/master/joss-paper" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/chappers/Ramble/tree/master/joss-paper">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.1)?
- [x] **Authorship:** Has the submitting author (@chappers) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @pjotrp it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by pjotrp** [comment]
Dear @chappers,

I finally have time to work on this review. I started, but there are two issues. First the license file does not contain an OSI approved license. This is obligatory for JOSS, so please add one. Then the paper you refer to is hosted on Slideshare https://www.slideshare.net/chapm0nsiu/ramble-introduction. I can not download it without having to register. Please make it freely available, perhaps as part of your repository. 

Ping me when this is done. I will continue after.

Pj.

**Comment by pjotrp** [comment]
@chappers Also the unit tests point to a standard R test. Can you do better than that? Kinda meaningless to add a test icon to the website if it is not a real test. Correct me if I am wrong.

**Comment by chappers** [comment]
@pjotrp Updated the license with license.md (artifact of the R build process) and added the pdf to `/docs`. 

What do you mean if its not a real test? Do you expect tests with sample data or something similar?

**Comment by pjotrp** [comment]
Thanks! Regarding the test I would expect it to build the package and run it as a minimum. Even better to have a real data test in it though. Many packaging systems depend on these tests to make sure integration works (including those of CRAN).

**Comment by pjotrp** [comment]
The current LICENSE file is a bit confusing. How about renaming LICENSE.md to LICENSE? Alternatively add that it is an MIT or expat license to the current LICENSE file.

**Comment by pjotrp** [comment]
If possible can you add to the README some guidelines on what people need to do to contact you? I.e., community guidelines.

**Comment by pjotrp** [comment]
I think this is a nice piece of work and can be quite useful to scientists needing to parse data. @chappers  to popularize this work I would add more examples of real use cases, especially for statistics or bioinformatics (who should be using proper parsers more often). Double them as tests for your test scripts too. Though you can do that later.

Before submission I recommend changing the name of the LICENSE file (also that allows github to show the license) and adding some community guidelines. Optionally you can improve paper.md a bit by referencing your PDF (now on github). If you feel energetic I would add a few use cases to paper.md too - just so as to make the reader aware of possibilities. When happy with your final version create a DOI for your source repository and ping @arfon for inclusion into JOSS.

Good job @chappers and sorry it took so long. The largest gap in time was after I asked you for potential reviewers and forgot to follow up when I got no response. Github issues do that do you: no message, no reminder. Next time I'll monitor more closely.

**Comment by chappers** [comment]
Hi @pjotrp thanks for spending time on this! I have updated the LICENSE file so now it shows up correctly. I have also added the contributing guide. 

@arfon The software is in Zenodo: 10.5281/zenodo.438282

**Comment by pjotrp** [comment]
@arfon I believe this paper is good to be published in JOSS.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.438282 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.438282" target="_blank">10.5281/zenodo.438282</a> is the archive.

**Comment by arfon** [comment]
@chappers - the title of this paper appears to be ['Eclipse Golo'](https://github.com/chappers/Ramble/blob/master/joss-paper/paper.md) - is that correct?

**Comment by chappers** [comment]
@arfon good spot...changed it to a more sensible title :)

**Comment by arfon** [comment]
@pjotrp many thanks for reviewing here ✨ 

@chappers - your paper is now accepted into JOSS and your paper DOI is http://dx.doi.org/10.21105/joss.00209 ⚡️ 🚀 💥
