### ISSUE TITLE
[REVIEW]: Expectations.jl: Quick and Accurate Expectation Operators in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2090]
**Submitting author:** @arnavs (<a href="http://orcid.org/0000-0003-0074-7908">Arnav Sood</a>)
**Repository:** <a href="https://github.com/QuantEcon/Expectations.jl" target ="_blank">https://github.com/QuantEcon/Expectations.jl</a>
**Version:** v1.2.0
**Editor:** @VivianePons
**Reviewers:** @odow, @oxinabox
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/f7659b88b54130ce9347aea25677a0fe/status.svg)](https://joss.theoj.org/papers/f7659b88b54130ce9347aea25677a0fe)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f7659b88b54130ce9347aea25677a0fe"><img src="https://joss.theoj.org/papers/f7659b88b54130ce9347aea25677a0fe/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f7659b88b54130ce9347aea25677a0fe/status.svg)](https://joss.theoj.org/papers/f7659b88b54130ce9347aea25677a0fe)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/QuantEcon/Expectations.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@odow & @oxinabox, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @VivianePons know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/QuantEcon/Expectations.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@arnavs) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/QuantEcon/Expectations.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@arnavs) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @odow, @pkofod it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.2307/1879403 is OK
- 10.1093/imanum/drv002 is OK
- 10.5281/zenodo.2647458 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02090/joss.02090/10.21105.joss.02090.pdf)

**Comment by odow** [comment]
Only one point with the paper: you should reference `FastGaussQuadrature.jl`.

The real go/no-go question is the extent to which the library is substantive enough. I note that this was [brought up in pre-review](https://github.com/openjournals/joss-reviews/issues/2065#issuecomment-582000457):

> The editorial board at JOSS is currently working on improved guidelines for in-scope submissions. We haven't finished, but we plan to start using some metrics to help guide if a submission passes some minimum bars to be considered a "large enough" contribution to be considered for JOSS, of course a question at any journal. Your submission is a bit on the low end for lines of code. This is not disqualifying, but it does mean that it would help if you were to give some extra motivation and understanding for the editors here who are not necessarily experts in your domain as to why your submission is a large enough contribution for its own publication. 

I would tend to agree.

`Expectations.jl` is on the low-side with respect to lines of code, and the real difficulty is handled by the `FastGaussQuadrature.jl` package. In addition, `FastGaussQuadrature.jl` doesn't meet the JOSS standards: CI appears to be down, limited documentation, etc.

I'll defer to an editor on the decision though; it does seem shame to place barriers in front of people trying to get credit for their open-source work.

If the `FastGaussQuadrature.jl` package was tidied up, it would be a suitable JOSS paper, and then you could say "oh, and there is a package called Expectations.jl that uses FastGaussQuadrature.jl to do cool things."

**Comment by arnavs** [comment]
@odow Can you elaborate on CI? Last I checked (this morning), everything is passing on Travis and AppVeyor. 

Documentation is a bit thin, but the basic functionality seems pretty straightforward. Would be happy to elaborate if you have any suggestions.

We cite FastGaussQuadrature in the paper. Will search around for a formal thing to refer to.

**Comment by odow** [comment]
Oh, it's just the badges on the README:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/8177701/74272449-3f7a9f80-4cd4-11ea-83b2-c64fb8753a34.png">

**Comment by arnavs** [comment]
Ah @odow gotcha, I thought you meant our CI (expectations.jl)

**Comment by arnavs** [comment]
@odow I asked the FGQ guys, and the paper I cite (Townsend, Olver, Trogdon) is what they recommend citing. I think that + the inline reference to FGQ should do it.

**Comment by arnavs** [comment]
@VivianePons Haven't heard much from @pkofod lately, so I think we can assign this review to someone else. Sorry about that.

**Comment by arnavs** [comment]
@whedon generate statistics

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by oxinabox** [comment]
I can do the review

**Comment by oxinabox** [comment]
I can do the review @VivianePons

**Comment by VivianePons** [comment]
Thank you @oxinabox I'm updating the issue accordingly

**Comment by VivianePons** [comment]
@whedon add @oxinabox as reviewer

**Comment by whedon** [comment]
OK, @oxinabox is now a reviewer

**Comment by oxinabox** [comment]
I have not yet properly begun the review, and am yet to more than skim the paper and code.

I notice that a few lines are almost character for character identical to DistQuads.jl
The DistQuads package is mentioned in Acknowledgements.
However, given relative size and scope of the overlap, it seems as though it may be more appropriate to have the author of DistQuads.jl as a coauthor to the paper.
e.g.:
https://github.com/QuantEcon/Expectations.jl/blob/0a24f4b53ed2bc4fc6119a0a2b69c550a571dab3/src/iterable.jl#L175
and
https://github.com/pkofod/DistQuads.jl/blob/553a1a7dcf6fd679aae7f7bd7c19f0b511040edd/src/DistQuads.jl#L46
and several other lines from that file.

**Comment by arnavs** [comment]
@oxinabox I ran the acknowledgment text by Patrick (and this is kinda why I wanted him to be a reviewer.) But that's a good point. I'll ask him if he's interested in coauthorship. Will let you know what he says.

**Comment by arnavs** [comment]
@pkofod is willing to be a coauthor. Will add him to the paper. Thanks for the suggestion.

**Comment by arnavs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02090/joss.02090/10.21105.joss.02090.pdf)

**Comment by arnavs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02090/joss.02090/10.21105.joss.02090.pdf)

**Comment by oxinabox** [comment]
Below follows my, admittedly fairly limited, evaluation of performance.

```julia
julia> using Distributions, Expectations, BenchmarkTools

julia> const y = Normal(20, 0.01)
Normal{Float64}(μ=20.0, σ=0.01)

julia> foo(x) = x^2 - 0.5x
foo (generic function with 1 method)

julia> @btime mean(foo, rand($y, 1000))
  9.807 μs (1 allocation: 7.94 KiB)
390.0042603170717

julia> @btime mean(foo, rand($y, 1_000_000))
  10.538 ms (2 allocations: 7.63 MiB)
389.9998149984719

julia> @btime expectation(foo, $y)
  20.196 μs (254 allocations: 31.38 KiB)
390.0000999999998
```

Seems it is much faster than working with a large number of samples, but similarly accurate.

Seems good

**Comment by oxinabox** [comment]
>State of the field: Do the authors describe how this software compares to other commonly-used packages?

It would be nice to see reference to other software.
I am sure they must have tools for something similar in R or Python.

---

It would also be nice to see some examples in the documentation of how it's generic fallback can be used with other distribution types.
E.g. with [TransformedDistributions from Bijectors.jl](https://github.com/TuringLang/Bijectors.jl).

More broadly, and related to this, it would be good to contextualize how this fits into the world of PPLs.

**Comment by arnavs** [comment]
@oxinabox Thanks for finishing the review. And good idea. Will add some references to other langs and types. 

There's also the classic `Measurements.jl` add-on that works super well. 

```
julia> d = Normal(1. ± 0.5, 0.25 ± 0.25);

julia> E = expectation(d);

julia> E(x -> x^2 * sin(x))
0.9 ± 1.1
```

**Comment by arnavs** [comment]
@oxinabox Incorporated your feedback; the TransformedDistribution support is looking a bit more annoying than I imagined (partly bc of some missing methods, partly because I need to read the math.) So I filed an issue, noted what our generic fallback supports, and will work on extending that.

**Comment by arnavs** [comment]
OK @VivianePons I have received and incorporated reviewer feedback.

**Comment by arnavs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02090/joss.02090/10.21105.joss.02090.pdf)

**Comment by arnavs** [comment]
@whedon generate pdf 

(unicode support fix)

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02090/joss.02090/10.21105.joss.02090.pdf)

**Comment by VivianePons** [comment]
Hi @arnavs thank you for incorporating all the feedbacks. I am still feeling some hesitations from the reviewers. I would like to have their opinions now that many things have changed, especially a new author! 

Dear @odow and @oxinabox thank you very much for the work you have provided. I see that @arnavs has implemented some of your suggestions. How do you feel about the new version of the software / paper, especially the clarification on references and the addition of a new author? would you say that this piece is a "significant contribution" to the existent state of scientific open source software on this topic?

**Comment by oxinabox** [comment]
Without the addition of the new author, I would have said this fails the requirements for "Contribution and authorship".

I think this probably marks the low-end of _" "significant contribution" to the existent state of scientific open source software on this topic?"_.
Calculated expectations is important for many things, and this makes it faster and easier.

**Comment by odow** [comment]
One typo: `s/elswhere/elsewhere`.

Agree with @oxinabox. Low-end of significant contribution, but still useful. 

This is really an editorial decision on where the bar should be set with respect to papers accepted.

If the decision is to have a generous acceptance policy in order to give people credit for their open-source work (Which we appreciate, @arnavs!), accept. 
If JOSS wants to move toward a more stringent policy that selectively rewards more significant contributions, reject.

**Comment by VivianePons** [comment]
Thank you both for your valuable inputs and the work. I will discuss it with other editors and let you know what we decide. In any case, @arnavs this is valuable work and I appreciate your reactivity in responding to the different requests.

**Comment by arnavs** [comment]
Good catch on typo @odow. Fixed. 

And thanks @VivianePons. Just a note that it would be great to re-check the statistics if possible. I don't know if we are over the threshold, but we have been adding features here and there (new distributions, mixed distributions, etc.)

**Comment by VivianePons** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by VivianePons** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (661.3 files/s, 34001.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                            9             94             83            429
Markdown                         4            107              0            238
YAML                             6             16              8             95
TOML                             3             27              1             91
TeX                              1              2              0             42
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            24            246             92            896
-------------------------------------------------------------------------------


Statistical information for the repository '2090' was gathered on 2020/03/09.
No commited files with the specified extensions were found.
```

**Comment by arnavs** [comment]
@VivianePons Any news about this? (No worries if you all are still discussing.)

**Comment by VivianePons** [comment]
Dear @arnavs thank you very much for your patience.

We have had a thorough discussion with the editorial team. I am sorry but we believe that the reviewer comments confirm our initial concern that the submission is a bit too small to be considered for publication (the quantity of code is an indicator here but not a barrier in itself) . We are right now improving our processes and guidelines to help authors better understand the expectations of the journal and improve the handling of submission like yours which are on the edge: https://github.com/openjournals/joss/issues/709

Nevertheless, we value the high quality work that you have done and which was noted by the reviewers and the editorial team. If, in the future, you add  significant features to your software, we would suggest that you resubmit to be again considered for publication.  

I understand that this decision might come as disappointing but I hope this won't discourage any further work of yours. I have very much appreciated your responsiveness dealing with the editors and reviewers comments. 

I wish you the best and long life to Expectations.jl and hopefully a publication in JOSS when it has grown a bit.

**Comment by arnavs** [comment]
OK, sorry to hear that but thanks for the thorough response and hard work. Will definitely resubmit when the library grows.

**Comment by danielskatz** [comment]
As on-duty Associate Editor in Chief, I'm going mark this as withdrawn, to take it out of the review system and database

**Comment by danielskatz** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
