### ISSUE TITLE
[PRE REVIEW]: CarrierCapture.jl: Anharmonic Carrier Capture

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2091]
**Submitting author:** @frssp (<a href="http://orcid.org/0000-0001-5072-6801">Sunghyun Kim</a>)
**Repository:** <a href="https://github.com/WMD-group/CarrierCapture.jl" target ="_blank">https://github.com/WMD-group/CarrierCapture.jl</a>
**Version:** v0.1
**Editor:** @danielskatz
**Reviewers:** @utf, @taylor-a-barnes
**Managing EiC:** Daniel S. Katz

**Author instructions**

Thanks for submitting your paper to JOSS @frssp. **Currently, there isn't an JOSS editor assigned** to your paper.

@frssp if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (441.2 files/s, 54128.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           16            284            112           1112
Markdown                         9            197              0            584
Python                           4             92             50            236
Jupyter Notebook                 4              0           1818            224
YAML                             5             15             29            179
TeX                              1              7              0             63
TOML                             2              1              0             27
-------------------------------------------------------------------------------
SUM:                            41            596           2009           2425
-------------------------------------------------------------------------------


Statistical information for the repository '2091' was gathered on 2020/02/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Sunghyun Kim                     4           101            234           35.19
frssp                            3           563             54           64.81

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Sungyun Kim                 378          100.0          9.6                8.20
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1088/0034-4885/44/12/001 may be missing for title: Non-radiative transitions in semiconductors
- https://doi.org/10.1103/physrevb.90.075202 may be missing for title: First-principles theory of nonradiative carrier capture via multiphonon emission
- https://doi.org/10.1103/physrevb.100.041202 may be missing for title: Anharmonic lattice relaxation during nonradiative carrier capture

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02091/joss.02091/10.21105.joss.02091.pdf)

**Comment by danielskatz** [comment]
👋 @frssp - there seem to be some DOIs missing in your bib file - please add any that are correct (noting that whedon's reference check summary sometimes makes mistakes)

**Comment by frssp** [comment]
Updated. 
@whedon generate pdf

**Comment by frssp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2091 with the following error: 

 Error reading bibliography ./paper.bib (line 14, column 3):
unexpected "d"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by frssp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02091/joss.02091/10.21105.joss.02091.pdf)

**Comment by danielskatz** [comment]
Thanks - one of the DOIs has a leading "https:/doi.org/" that should be removed

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by frssp** [comment]
I suggest JMSkelton and utf for potential reviewers because they are experts in computational chemistry.

**Comment by frssp** [comment]
DOI fixed; @whedon generate pdf

**Comment by danielskatz** [comment]
```@whedon generate pdf``` has to be the start (or entirety) of a comment

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02091/joss.02091/10.21105.joss.02091.pdf)

**Comment by danielskatz** [comment]
👋 @JMSkelton & @utf - would either or both of you be willing to review this submission?

**Comment by utf** [comment]
I’d be happy to review this.

**Comment by danielskatz** [comment]
👋 @godotalgorithm & @taylor-a-barnes - would either or both of you be willing to review this submission to JOSS?  JOSS reviews are of the software and short paper, and are checklist-driven, with the goal of improving the software to the point where it can be accepted - see https://joss.readthedocs.io/en/latest/reviewer_guidelines.html for more info

**Comment by danielskatz** [comment]
Thanks @utf - I'll assign you, but we won't start until we get at least one more reviewer.

**Comment by danielskatz** [comment]
@whedon assign @utf as reviewer

**Comment by whedon** [comment]
OK, @utf is now a reviewer

**Comment by taylor-a-barnes** [comment]
@danielskatz I would be happy to review this submission.

**Comment by danielskatz** [comment]
Thanks @taylor-a-barnes - I'll add you, and we'll start the review process in a new thread - hang on...

**Comment by danielskatz** [comment]
@whedon add @taylor-a-barnes as reviewer

**Comment by whedon** [comment]
OK, @taylor-a-barnes is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2102.
