### ISSUE TITLE
[PRE REVIEW]: Visions: An Open-Source Library for Semantic Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2092]
**Submitting author:** @sbrugman (<a href="http://orcid.org/0000-0001-9866-7767">Simon Brugman</a>)
**Repository:** <a href="https://github.com/dylan-profiler/visions" target ="_blank">https://github.com/dylan-profiler/visions</a>
**Version:** v0.2.2
**Editor:** @mjsottile
**Reviewers:** @1313e, @fccoelho
**Managing EiC:** Daniel S. Katz

**Author instructions**

Thanks for submitting your paper to JOSS @sbrugman. **Currently, there isn't an JOSS editor assigned** to your paper.

@sbrugman if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.72 s (575.2 files/s, 104488.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                           150          17129            149          27139
JavaScript                      11           2200           2239           8326
SVG                             21              0            604           5149
Python                         109           1455           1479           4298
reStructuredText               102           1075            997            933
CSS                              4            164             34            642
Markdown                         3             39              0            122
TeX                              1              7              0            103
DOS Batch                        2             19              1             87
make                             2             17             35             87
INI                              3             12              0             35
YAML                             2              3              4             16
Jupyter Notebook                 1              0            404             15
Bourne Shell                     1              0              0              3
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                           413          22120           5946          46956
-------------------------------------------------------------------------------


Statistical information for the repository '2092' was gathered on 2020/02/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ian Eaves                      114         43047          17741           35.24
Simon Brugman                   11          1898           1292            1.85
sbrugman                        38          2011           1950            2.30
simon_graphkite                256         49462          55114           60.62

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ian Eaves                  1384            3.2          4.3                7.01
Simon Brugman              1004           52.9          2.7                7.07
simon_graphkite           17609           35.6          4.1               15.57
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.3545747 is OK

MISSING DOIs

- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2092 with the following error: 

 Error producing PDF.
! Unable to load picture or PDF file '/tmp/tex2pdf.-62463a8dc5eb813c/403e2020ef
d7c89668a95a5c8d4cbfb2c5ed0399.png'.
<to be read again> 
                   }
l.415 ...2020efd7c89668a95a5c8d4cbfb2c5ed0399.png}

Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
👋 @openjournals/dev - Can whedon compile papers with figures that are remote?  If so, any idea what the problem is here?

**Comment by sbrugman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02092/joss.02092/10.21105.joss.02092.pdf)

**Comment by sbrugman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/MCSE.2011.37 is OK
- 10.5281/zenodo.3545747 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by sbrugman** [comment]
@danielskatz The figure pointed to the branch we used for development. Moreover, the numpy reference was missing it's DOI. I've fixed both issues.

**Comment by danielskatz** [comment]
the labels aren't very well-generated - sorry - I'll change them manually

**Comment by danielskatz** [comment]
You also might want to take the time to fix case issues in the references - use {}s as needed to protect case, such as {P}ython.

**Comment by danielskatz** [comment]
@whedon invite mjsottile as editor

**Comment by whedon** [comment]
@mjsottile has been invited to edit this submission.

**Comment by sbrugman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02092/joss.02092/10.21105.joss.02092.pdf)

**Comment by mjsottile** [comment]
Sure @danielskatz , I can take this submission.

**Comment by arfon** [comment]
@sbrugman - please change links to images to make them full URLs, e.g. change `![Visions' Standard Typeset](images/typeset_standard.png)` to `https://raw.githubusercontent.com/dylan-profiler/visions/master/paper/images/typeset_standard.png`

Also, please cite your BibTeX entries using the rMarkdown syntax. You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)

**Comment by danielskatz** [comment]
Thanks @mjsottile - the command that I'm going to issue to whedon next is also one you can issue, once you've agreed to edit a submission

**Comment by danielskatz** [comment]
@whedon assign @mjsottile as editor

**Comment by whedon** [comment]
OK, the editor is @mjsottile

**Comment by mjsottile** [comment]
:wave: @sbrugman If you have any suggestions for reviewers please let me know.  Otherwise I'll dig through the list of available reviewers to find some candidates.

**Comment by sbrugman** [comment]
@casperdcl @alexpghayes @1313e @bzz @amcasari would you be interested to review this submission?

**Comment by sbrugman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02092/joss.02092/10.21105.joss.02092.pdf)

**Comment by 1313e** [comment]
@sbrugman @mjsottile Sure, I would like to be a reviewer for this.

**Comment by alexpghayes** [comment]
Looks very interesting but I don't have the background to review this!

**Comment by casperdcl** [comment]
Same, I could review but don't specialise in this field.

**Comment by mjsottile** [comment]
@whedon assign @sbrugman as reviewer

**Comment by whedon** [comment]
OK, @sbrugman is now a reviewer

**Comment by mjsottile** [comment]
@whedon remove @sbrugman as reviewer

**Comment by whedon** [comment]
OK, @sbrugman is no longer a reviewer

**Comment by mjsottile** [comment]
@whedon assign @1313e as reviewer

**Comment by whedon** [comment]
OK, @1313e is now a reviewer

**Comment by mjsottile** [comment]
:wave: @gabrielspadon @dirmeier @dvysardana @GregaVrbancic Hello!  Would you be interested in reviewing this recent JOSS submission?  Based on the topic and your expertise as listed in our potential reviewer list I believe you may be a good match.

**Comment by sbrugman** [comment]
@mstimberg @macrocosme @pandaconstantin @rchg @fccoelho Hello! Would you be interested in reviewing this submission? 

@mjsottile People might be put off by thinking they are not familiar enough with the topic, as the title does not include downstream applications. How `visions` relates to e.g. machine learning, data compression is described here: https://dylan-profiler.github.io/visions/visions/applications/applications.html. Moreover, a background in functional programming could also provide a good intuition of the contribution of this work.

**Comment by 1313e** [comment]
@sbrugman I think you might be right.
I thought the same when I just read the title, but I first read parts of the documentation and the paper before deciding if I could review this.

**Comment by fccoelho** [comment]
I'd be happy to review it. The library looks quite interesting

**Comment by mstimberg** [comment]
Not sure how many reviewers you are looking for, but I'd be happy to review it. But also happy to leave it to those who volunteered earlier.

**Comment by macrocosme** [comment]
Unless there is a need for many reviewer,  I'm happy to skip this one. However, it does look interesting.

**Comment by mjsottile** [comment]
Thanks @fccoelho for agreeing to review.  I will keep @mstimberg and @macrocosme in mind in case I need to find an additional reviewer during the process.

**Comment by mjsottile** [comment]
@whedon add @fccoelho as reviewer

**Comment by whedon** [comment]
OK, @fccoelho is now a reviewer

**Comment by mjsottile** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2145.
