### ISSUE TITLE
[PRE REVIEW]: Pippin: A pipeline for supernova cosmology

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2096]
**Submitting author:** @samreay (<a href="http://orcid.org/0000-0003-2071-9349">Samuel Hinton</a>)
**Repository:** <a href="https://github.com/Samreay/Pippin" target ="_blank">https://github.com/Samreay/Pippin</a>
**Version:** 0.1.1
**Editor:** @arfon
**Reviewers:** @kboone, @temuller
**Managing EiC:** Arfon Smith

**Author instructions**

Thanks for submitting your paper to JOSS samreay. **Currently, there isn't an JOSS editor assigned** to your paper.

samreay if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.20 s (588.1 files/s, 61207.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          35           1225            824           5913
YAML                            60            393             77           2526
Markdown                         2            170              0            545
INI                             19             61              0            362
TeX                              1             10              0            172
Bourne Shell                     1              0              0              3
-------------------------------------------------------------------------------
SUM:                           118           1859            901           9521
-------------------------------------------------------------------------------


Statistical information for the repository '2096' was gathered on 2020/02/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Samuel Hinton                 1120         13282           5718           94.64
samreay                         94           740            337            5.36

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Samuel Hinton              7962           59.9          5.2                5.31
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/MCSE.2007.55 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1086/605984 is OK
- 10.1103/PhysRevD.66.103511 is OK
- 10.21105/joss.00045 is OK
- 10.3847/2041-8213/ab04fa is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02096/joss.02096/10.21105.joss.02096.pdf)

**Comment by arfon** [comment]
:wave: @Samreay - thanks for your submission to JOSS. Does this paper accompany a submission to a AAS journal?

**Comment by danielskatz** [comment]
@whedon invite @arfon as editor

**Comment by whedon** [comment]
@arfon has been invited to edit this submission.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by Samreay** [comment]
Hi @arfon - not this time, JOSS only. The primary results from using Pippin will be published in about a years time for the DES 5YR analysis cosmology results. The initial plan was to wait until then to publish Pippin as a companion paper, but its had enough uptake in the community we realised we shouldn't wait.

**Comment by arfon** [comment]
@temuller @kbarbary - would you be willing to review this submission for JOSS? 

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by temuller** [comment]
Hi,

I would be happy to do it, but I would like to have more details. For example, on what coding language is the submission? How much time do I have to review?

The more details, the better.

Regards
Tomás


_____________________________________________

Tomás E. Müller Bravo,
School of Physics and Astronomy,
University of Southampton,
Southampton, SO17 1BJ, UK
________________________________

**Comment by arfon** [comment]
Thanks for your interest @temuller. The software appears to be mostly written in Python 3.7 (https://github.com/Samreay/Pippin).

> How much time do I have to review?

Ideally we'd like to have the review complete in 2-3 weeks. The review is checklist-driven and happens on GitHub. We have pretty detailed guidelines [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.htmll) for reviewers.

**Comment by kbarbary** [comment]
Hey Arfon! Thanks for the invite. Unfortunately  I won't have the time to give this a thorough review. (I'm now a couple years removed from SN cosmology work.)

**Comment by arfon** [comment]
> Hey Arfon! Thanks for the invite. Unfortunately I won't have the time to give this a thorough review. (I'm now a couple years removed from SN cosmology work.)

No worries. Thanks for getting back to me.

**Comment by arfon** [comment]
:wave: @grburgess - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by arfon** [comment]
:wave: @daniel-muthukrishna - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by arfon** [comment]
@Samreay - I'm struggling a little to identify a second reviewer for this submission. Are there any individuals you think might be able to review this?

**Comment by Samreay** [comment]
@kboone springs to mind. @JoeZuntz would have the experience as well I believe. I can also try and ping Dan.

**Comment by arfon** [comment]
:wave: @kboone @jradavenport @joezuntz - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by joezuntz** [comment]
Sorry, I'm slightly overloaded ATM.

**Comment by kboone** [comment]
Sure, I'd be happy to do this review.

In the interest of transparency, @Samreay and I worked at the same institution for a few months around three years ago. We did not work directly together on any projects, and I don't think that this is a COI that would make me unable to make an impartial evaluation.

**Comment by danielskatz** [comment]
This is a COI according to [JOSS policies](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy) but it's long enough ago and minor enough that it can be waived

**Comment by arfon** [comment]
@whedon add @kboone as reviewer

**Comment by whedon** [comment]
OK, @kboone is now a reviewer

**Comment by arfon** [comment]
> In the interest of transparency, @Samreay and I worked at the same institution for a few months around three years ago. We did not work directly together on any projects, and I don't think that this is a COI that would make me unable to make an impartial evaluation.

:zap: thanks @kboone!

**Comment by arfon** [comment]
@whedon add @temuller as reviewer

**Comment by whedon** [comment]
OK, @temuller is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2122.

**Comment by arfon** [comment]
@kboone, @temuller - many thanks for agreeing to review this submission. See you over in #2122 where the actual review will take place.
