### ISSUE TITLE
[REVIEW]: Using drones to quantify the length of marine animals

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2097]
**Submitting author:** @egemose (<a href="http://orcid.org/0000-0002-6765-8216">Henrik Dyrberg Egemose</a>)
**Repository:** <a href="https://github.com/egemose/DroneVideoMeasure" target ="_blank">https://github.com/egemose/DroneVideoMeasure</a>
**Version:** v1.0.0
**Editor:** @kthyng
**Reviewer:** @abhishekbajpayee, @jizecn
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/261f0d3d7db18c71a836dad19a2b809c/status.svg)](https://joss.theoj.org/papers/261f0d3d7db18c71a836dad19a2b809c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/261f0d3d7db18c71a836dad19a2b809c"><img src="https://joss.theoj.org/papers/261f0d3d7db18c71a836dad19a2b809c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/261f0d3d7db18c71a836dad19a2b809c/status.svg)](https://joss.theoj.org/papers/261f0d3d7db18c71a836dad19a2b809c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/egemose/DroneVideoMeasure" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@abhishekbajpayee & @jizecn, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/egemose/DroneVideoMeasure">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@egemose) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/egemose/DroneVideoMeasure">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@egemose) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @abhishekbajpayee, @jizecn it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3389/fmars.2017.00366 is OK
- 10.1111/mms.12527 is OK
- 10.21105/joss.01825 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02097/joss.02097/10.21105.joss.02097.pdf)

**Comment by kthyng** [comment]
Hi @abhishekbajpayee and @jizecn! When do you think you'll be able to work on your reviews?

**Comment by danielskatz** [comment]
👋 @abhishekbajpayee and @jizecn - repeating @kthyng's comment: When do you think you'll be able to work on your reviews?

**Comment by kthyng** [comment]
Just pinged both by email.

**Comment by abhishekbajpayee** [comment]
@kthyng apologies for the delay.

I installed things and launched the application using provided instructions. Using calibration video in the sample dataset, I was able to calibrate. I did notice a few things that might be worth addressing here:
1) The UI to pick a calibration video file only shows mp4 video files but the sample file is an mov file. Dragging and dropping worked for me but seeing only mp4 in the file selection UI was a bit confusing.
2) It might be useful to either show progress or logs or some sort while calibration is going on. User has no idea how long to wait.
3) Ideally there should be some way to handle incorrect calibration videos i.e. videos that do not contain a checkerboard. Initially when I just saw the mp4 files in the file selector, I picked the demo.mp4 files instead but seems like things froze. So I had to restart everything.

Once beyond calibration, I was able to create a project and upload a video. Comments for this step:
1) Here I wasn't sure which video or videos in the sample data correspond to which csv log file.
2) Not knowing the correspondence, I tried all combinations but got stuck after the upload. So the upload completed but then going to the video gallery didn't show any videos. Not sure how to proceed from here.

@egemose can you advise on how I should proceed with testing after calibration?

**Comment by jizecn** [comment]
Hi, I also tried the software following the instructions provided. 

Docker to facilitate the installation and testing works fine for me. However, I need to use "sudo" to start the software. Maybe it is only for me, but might be worth mentioning in the document (ps. I use Linux Ubuntu 16.04). 

A few comments/suggestions: 
1. The calibration process looks similar to the annotation part. I by mistake uploaded a wrong video for calibration, and that took ages without notifying any error. 
2. Similarly, when creating a project, I also uploaded a wrong file for the log file (which I initially thought it was for the video). However, the system did not report any error either until at a later stage. It might be useful to use tooltips providing instructions about at least file types expected to be uploaded and the content of the file. 
3. The UI buttons: can we change the appearance to make it look clearer when toggled? The three buttons for changing colours, line width, and removing annotations are useful, but not very intuitive in my opinion. Can we provide some tooltips too when the mouse pointer hovers around the buttons for these buttons? 

As mentioned by the other reviewer (@abhishekbajpayee ), it is not clear how to identify corresponding log and video files. I was only able to do it following the demo video. It is worth providing a simple tool (e.g. a python / bash script) that can rename two paired files after downloading from the drone to the same one (as a pre-processing stage), so that user only needs to upload two files once. 

Overall, I can confirm the software works as described (overall good documentation), except the user interface can be improved for better usability. I hope it helps. Thanks.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by kthyng** [comment]
@egemose I know you might not be spending time on work right now, but for when you are, it looks like the reviewers have given some input and are ready to hear back from you.

**Comment by egemose** [comment]
@kthyng, @abhishekbajpayee and @jizecn Given the current situation I am unable to allocate time for this and it does not look like I will have time the next couple of months. So I would like to put a pause on this until I again Have time.

**Comment by kthyng** [comment]
@egemose Totally get it. I'll add the pause label. Just ping here when you're able to work on this again.

**Comment by arfon** [comment]
@egemose - do you think you will have the time to restart working on this submission within the next few weeks or so? If not, in order to respect the reviewers' time and availability committment, I will propose to close (reject) this submission, and invite a resubmission at a later point in time.

**Comment by egemose** [comment]
@arfon You may close this submission. I will do a resubmission when I find the time at a later point.

**Comment by arfon** [comment]
> @arfon You may close this submission. I will do a resubmission when I find the time at a later point.

OK, thanks for the update @egemose.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by arfon** [comment]
@abhishekbajpayee, @jizecn, @kthyng  - thanks for your efforts here, sorry it didn't work out this time.
