### ISSUE TITLE
[PRE REVIEW]: Chemiscope: interactive structure-property explorer for materials and molecules

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2098]
**Submitting author:** @luthaf (<a href="http://orcid.org/0000-0003-4824-6512">Guillaume Fraux</a>)
**Repository:** <a href="https://github.com/cosmo-epfl/chemiscope" target ="_blank">https://github.com/cosmo-epfl/chemiscope</a>
**Version:** v0.1.0
**Editor:** @cMadan
**Reviewers:** @kblin, @mkhorton
**Managing EiC:** Daniel S. Katz

**Author instructions**

Thanks for submitting your paper to JOSS @luthaf. **Currently, there isn't an JOSS editor assigned** to your paper.

@luthaf if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1073/pnas.1108486108 is OK
- 10.1103/physrevb.87.184115 is OK
- 10.1088/1367-2630/15/9/095003 is OK
- 10.1186/s13321-014-0041-7 is OK
- 10.1093/bioinformatics/btx760 is OK
- 10.1093/bioinformatics/btt270 is OK
- 10.1038/s41467-018-06972-x is OK
- 10.5281/zenodo.3541831 is OK
- 10.1039/c6cp00415f is OK
- 10.1186/s13321-017-0192-4 is OK
- 10.1039/c7sc04665k is OK
- 10.1016/j.commatsci.2019.02.040 is OK
- 10.1063/1.5090481 is OK
- 10.1103/physrevlett.98.146401 is OK
- 10.1021/ci300415d is OK
- 10.1038/sdata.2014.22 is OK
- 10.1103/physrevlett.104.136403 is OK
- 10.1162/089976698300017467 is OK
- 10.1002/anie.200603675 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02098/joss.02098/10.21105.joss.02098.pdf)

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=3.55 s (361.4 files/s, 138230.0 lines/s)
----------------------------------------------------------------------------------------
Language                              files          blank        comment           code
----------------------------------------------------------------------------------------
JavaScript                             1230           5930           2231         463471
JSON                                      3              0              0          11541
TypeScript                               23            497            890           3183
Velocity Template Language                6             55             57            808
HTML                                      6             68             11            588
CSS                                       3             71              4            335
TeX                                       1             21              0            252
Python                                    3             72             77            199
reStructuredText                          3             93            172            166
Markdown                                  2             28              0            137
YAML                                      1              5              3             39
DOS Batch                                 1              8              1             27
make                                      1              6              8             15
SVG                                       1              0              0              1
----------------------------------------------------------------------------------------
SUM:                                   1284           6854           3454         480762
----------------------------------------------------------------------------------------


Statistical information for the repository '2098' was gathered on 2020/02/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Guillaume Fraux                 19        982951         655117          100.00
Luthaf                           5            67             10            0.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Guillaume Fraux          473010           48.1          0.0                0.49
Luthaf                       63           94.0          0.1                4.76
```

**Comment by danielskatz** [comment]
@whedon invite @cMadan as editor

I know this is a bit out of scope for you, but we don't really have a chemistry editor at this point, so I hope you can take it

**Comment by whedon** [comment]
@cMadan has been invited to edit this submission.

**Comment by cMadan** [comment]
@danielskatz I can oversee the review process, but I don't think I'd be able to help find reviewers, so hopefully that part doesn't end up being too much of a problem

**Comment by danielskatz** [comment]
thanks - I can help, though it's not my field either, so let me know if you get stuck

**Comment by danielskatz** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@Luthaf, it looks like things are in order! Can you look through the list of JOSS reviewers (linked in the first comment in this issue) and suggest some who may be suitable? Thanks!

**Comment by Luthaf** [comment]
After looking through the list, I think mnf2014, nmoran, jochym, trallard, and utf have experience in related fields.

Additionally, b-freitas, kblin, leonardojaneis and zoomelectrico have experience with the web platform/javascript; which is the implementation language of chemiscope.

**Comment by cMadan** [comment]
@utf @mskwark @kblin, would you be available and interested in reviewing this submission?

**Comment by kblin** [comment]
I won't be able to comment on the chemistry much, but I'm happy to look at the software side of things.

**Comment by cMadan** [comment]
@kblin, that would be great, thank you! My plan is to get at least one reviewer with chemistry expertise to cover that side of things.

**Comment by cMadan** [comment]
@whedon add @kblin as reviewer

**Comment by whedon** [comment]
OK, @kblin is now a reviewer

**Comment by utf** [comment]
I'm already reviewing another paper for JOSS currently, but @mkhorton might be available.

**Comment by cMadan** [comment]
@utf, no problem, thanks for the suggestion!

@mkhorton, would you be available and interested in reviewing this submission? (I notice you thumbs-up'd the comment, but thought I should ask properly before just assigning you.)

**Comment by mkhorton** [comment]
Yes, fine with me, thanks for asking @cMadan !

**Comment by cMadan** [comment]
@mkhorton, great, thank you!

@Luthaf @kblin, I will go ahead and start the review now!

**Comment by cMadan** [comment]
@whedon add @mkhorton as reviewer

**Comment by whedon** [comment]
OK, @mkhorton is now a reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2117.
