### ISSUE TITLE
[PRE REVIEW]: CloudnetPy: A Python package for processing cloud remote sensing data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2099]
**Submitting author:** @tukiains (<a href="http://orcid.org/0000-0002-0651-4622">Simo Tukiainen</a>)
**Repository:** <a href="https://github.com/actris-cloudnet/cloudnetpy" target ="_blank">https://github.com/actris-cloudnet/cloudnetpy</a>
**Version:** v1.0.7
**Editor:** @jedbrown
**Reviewers:** josephhardinee
**Managing EiC:** Daniel S. Katz

**Author instructions**

Thanks for submitting your paper to JOSS @tukiains. **Currently, there isn't an JOSS editor assigned** to your paper.

@tukiains if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.21 s (489.8 files/s, 62272.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          85           2299           1804           8001
Markdown                         5             53              0            197
reStructuredText                 6            205            199            188
INI                              3             17              0            160
TeX                              1              4              0             59
YAML                             2              0              0             16
make                             1              4              6              9
HTML                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                           104           2582           2009           8631
-------------------------------------------------------------------------------


Statistical information for the repository '2099' was gathered on 2020/02/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Simo Tukiainen                   6         25200          13096          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Simo Tukiainen            12104           48.0          0.0                5.25
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1175/BAMS-88-6-883 is OK
- 10.1175/JAM2340.1 is OK
- 10.1175/JAM-2181.1 is OK
- 10.5194/acp-19-1985-2019 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02099/joss.02099/10.21105.joss.02099.pdf)

**Comment by danielskatz** [comment]
@whedon invite @jedbrown as editor

**Comment by whedon** [comment]
@jedbrown has been invited to edit this submission.

**Comment by tukiains** [comment]
Potential reviewers (from the list) could be scivision, usethedata and josephhardinee. They all have experience in remote sensing / radars and Python.

**Comment by danielskatz** [comment]
@whedon invite @jedbrown as editor

**Comment by whedon** [comment]
@jedbrown has been invited to edit this submission.

**Comment by jedbrown** [comment]
@whedon assign jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is jedbrown

**Comment by jedbrown** [comment]
@scivision @josephhardinee :wave: Would you be available to review this submission for JOSS?

**Comment by josephhardinee** [comment]
Sure

**Comment by jedbrown** [comment]
@whedon add josephhardinee as reviewer

**Comment by whedon** [comment]
OK, josephhardinee is now a reviewer

**Comment by josephhardinee** [comment]
Normally this triggers a new repository to be created right? I hadn't been notified and just want to make sure no one is waiting on me.

**Comment by jedbrown** [comment]
@josephhardinee Yep, I'm still working to confirm a second reviewer, but will start the review issue for you now.

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2123.

**Comment by josephhardinee** [comment]
@jedbrown  I can suggest @ekschuman as another reviewer as well if you would like. I checked and he is available.
