### ISSUE TITLE
Submission: pyuca: a Python implementation of the Unicode Collation Algorithm

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#21]
**Submitting author:** @jtauber (<a href="http://orcid.org/0000-0001-6534-8866">James Tauber</a>)
**Repository:** <a href="https://github.com/jtauber/pyuca" target ="_blank">https://github.com/jtauber/pyuca</a>
**Version:** v1.1.2
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.51550" target ="_blank">10.5281/zenodo.51622</a>

## Status

[![status](http://joss.theoj.org/papers/28430167d67c58585f014e503baf6f08/status.svg)](http://joss.theoj.org/papers/28430167d67c58585f014e503baf6f08)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/28430167d67c58585f014e503baf6f08"><img src="http://joss.theoj.org/papers/28430167d67c58585f014e503baf6f08/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/28430167d67c58585f014e503baf6f08/status.svg)](http://joss.theoj.org/papers/28430167d67c58585f014e503baf6f08)
```

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jtauber/pyuca">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.1.1)?
- [x] **Archive:** Does the <a target="_blank" href="http://dx.doi.org/10.5281/zenodo.51550">software archive</a> resolve?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have the performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Compiled paper PDF: [10.21105.joss.00021.pdf](https://github.com/openjournals/joss-reviews/files/268914/10.21105.joss.00021.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by luizirber** [comment]
:hand: I am reviewing this

**Comment by luizirber** [comment]
- There are no performance claims, so should I will just check the box?
- Although `test.py` have examples, the `usage` in the README could include an example `words` list (like `["cafe", "caff", "café"]` from [this test](https://github.com/jtauber/pyuca/blob/e048ae43ccc89d33e3d31777701c0e4bdabe8d47/test.py#L17))
- The author affiliation is missing in paper.md
- There are no community guidelines (Add a CONTRIBUTING file?)

Just some minor corrections, looks very good otherwise! @jtauber @arfon

**Comment by jtauber** [comment]
I'll add the `["cafe", "caff", "café"]` example to README and add a CONTRIBUTING file.

As to affiliation, I normally leave it blank as my scholarly work is independent (on academia.edu I'm under independent.academia.edu). I *could* put my company but it's not really relevant to this work.

**Comment by jtauber** [comment]
@luizirber @arfon 

I've updated the `README.md` and added a `CONTRIBUTING.md`.

One question (besides the outstanding affiliation question): do I need to re-release and mint a new DOI to include these changes?

**Comment by luizirber** [comment]
@jtauber I left a [comment](https://github.com/jtauber/pyuca/commit/67728992e1de1d9370804da8f005a1b8c82b25a1#commitcomment-17517151) in the commit, I'll let @arfon answer about the affiliation and re-relase and new DOI questions.

**Comment by arfon** [comment]
> One question (besides the outstanding affiliation question): do I need to re-release and mint a new DOI to include these changes?

Ideally yes please!

**Comment by jtauber** [comment]
@luizirber I've addressed your comment. Thank you!
@arfon no problem doing another release. Did you want me to do anything about affiliation first?

**Comment by arfon** [comment]
> @arfon no problem doing another release. Did you want me to do anything about affiliation first?

Leaving it blank is fine.

**Comment by jtauber** [comment]
Okay, I'll re-release and mint another DOI.

**Comment by jtauber** [comment]
@luizirber @arfon re-released with new DOI: 10.5281/zenodo.51622

**Comment by jtauber** [comment]
Note the version has changed to 1.1.2 too.

**Comment by arfon** [comment]
👍 thanks for the review @luizirber.

**Comment by arfon** [comment]
@jtauber http://dx.doi.org/10.21105/joss.00021 🎉

**Comment by jtauber** [comment]
Thanks @luizirber and @arfon.  🎉
