### ISSUE TITLE
[PRE REVIEW]: Ensight4Matlab: read, process, and write data in EnSight Gold format from C++ or MATLAB

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#210]
**Submitting author:** schmeisser (<a href="http://orcid.org/0000-0002-4400-9635">Andre Schmeißer</a>)
**Repository:** <a href="https://github.com/ITWM-TVFS/Ensight4Matlab" target ="_blank">https://github.com/ITWM-TVFS/Ensight4Matlab</a>
**Version:** v1.0
**Editor:** @cmadan
**Reviewer:** @Kevin-Mattheus-Moerman

**What this issue is for**

Thanks for submitting your paper to JOSS schmeisser. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by Kevin-Mattheus-Moerman** [comment]
@cMadan / @labarba / @kyleniemeyer would one of you be willing to act as editor for this? I'd like to review this submission but will focus on the MATLAB and 3D mesh visualization side of this project. We will also have to find additional reviewers with more CFD and C++ experience. Can you help suggest such reviewers?

**Comment by cMadan** [comment]
@Kevin-Mattheus-Moerman - I can act as editor and am happy to help with recruiting an additional reviewer. Do you think we should 'start' the review now, or recruit the additional reviewer first?

**Comment by cMadan** [comment]
@whedon assign @cmadan as editor

**Comment by whedon** [comment]
OK, the editor is @cmadan

**Comment by cMadan** [comment]
@whedon assign @Kevin-Mattheus-Moerman as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
We can formally start the review now and I can get started.

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by cMadan** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/217. Feel free to close this issue now!
