### ISSUE TITLE
[PRE REVIEW]: MaterialNet: A web-based graph explorer for materials science data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2100]
**Submitting author:** @waxlamp (<a href="http://orcid.org/0000-0003-3898-4626">Roni Choudhury</a>)
**Repository:** <a href="https://github.com/ToyotaResearchInstitute/materialnet" target ="_blank">https://github.com/ToyotaResearchInstitute/materialnet</a>
**Version:** 1.0.0
**Editor:** @danielskatz
**Reviewers:** @Luthaf, @rcannood
**Managing EiC:** Daniel S. Katz

**Author instructions**

Thanks for submitting your paper to JOSS @waxlamp. **Currently, there isn't an JOSS editor assigned** to your paper.

@waxlamp if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.13 s (838.1 files/s, 79592.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      70           1063            658           6372
Python                           8            168             29            360
JSON                             4              0              0            216
Markdown                         3             58              0            211
TeX                              1             12              0            147
GLSL                             7              7              0             85
Pug                              2             19              0             76
YAML                             2              6              0             64
Jupyter Notebook                 2              0            344             57
CSS                              3              7              0             44
HTML                             1              3             20             17
Bourne Shell                     2              4              0             13
SVG                              1              0              0              7
-------------------------------------------------------------------------------
SUM:                           106           1347           1051           7669
-------------------------------------------------------------------------------


Statistical information for the repository '2100' was gathered on 2020/02/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alessandro Genova               36          5175           2195           32.64
Roni Choudhury                 188          5098           1569           29.52
Samuel Gratzl                  150          5227           3318           37.84

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alessandro Genova          3090           59.7         11.7               17.06
Chris Harris                  1          100.0         -2.1                0.00
Roni Choudhury             2551           50.0          6.9                2.47
Samuel Gratzl              3225           61.7          2.0                3.04
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/npjcompumats.2015.10 is OK
- 10.1063/1.4812323 is OK
- 10.1016/j.commatsci.2012.02.002 is OK
- 10.1038/s41467-019-10030-5 is OK
- 10.1016/j.matt.2019.10.024 is OK
- 10.1021/cm503507h is OK
- 10.1109/TVCG.2013.173 is OK
- 10.1103/PhysRevB.96.024104 is OK
- 10.1021/acs.jcim.9b00470 is OK
- 10.1038/s41586-019-1335-8 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02100/joss.02100/10.21105.joss.02100.pdf)

**Comment by danielskatz** [comment]
👋 @waxlamp - we need an open source license in the repository.

Also, while I can see how this software is useful, can you explain how it is used in research? What problems does it help solve?

**Comment by waxlamp** [comment]
>  @waxlamp - we need an open source license in the repository.
> 

Hi @danielskatz, thank you for the fast response to our submission!

I've added a LICENSE file--Apache 2.0.

> Also, while I can see how this software is useful, can you explain how it is used in research? What problems does it help solve?

Here's a response from co-author Joseph Montoya:

*In the past five years, materials databases have become very popular because they enable their users to do rapid prototyping by searching near globally for figures of merit for their target application.  However, both scientists and engineers have little in the way of visualization of aggregates from these databases, i.e. intuitive layouts that help understand which materials are related and how they are related.  The need for a tool that does this is particularly crucial in materials science because properties like phase stability and crystal structure similarity are themselves functions of a material dataset, rather than of individual materials.*

*Materialnet provides for this by enabling a simple layout of a given network of materials.  The examples in the current implementation are for the aforementioned cases (i. e. Visualization of the “complete” phase diagram of the OQMD and similarity metrics from crystal structure), but the tool may be applied to any case in which a materials network can be constructed.*

*The most obvious extensions of this that we envision are users with their own database of formation energies which may differ from the OQMD.  Similarly, any vector representing material properties can be used to construct a similarity network, a user might want to understand how the network of materials with similar optical properties differs from that of materials with similar mechanical properties.*

**Comment by danielskatz** [comment]
Ok, thanks

**Comment by danielskatz** [comment]
You might want to add some of this to your paper and to your readme.

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @dgasmith - would you be willing to review this for JOSS?

**Comment by danielskatz** [comment]
👋 @waxlamp - if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by dgasmith** [comment]
@danielskatz My JS foo likely isn't sufficient to review the code base itself and I am busy for the next ~two weeks. Happy to serve as a backup however with the above caveats.

**Comment by danielskatz** [comment]
@dgasmith - do you have suggestions for other potential reviewers?  I might also want to use you as the second reviewer, but I'll hold off on that for now...

**Comment by waxlamp** [comment]
>  @waxlamp - if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

luthaf, rcannood, ati-ozgur, and sptennak all seem like good matches for our project. There's a mix of network science, materials science, and JavaScript expertise amongst them (though not concentrated in any one person).

**Comment by waxlamp** [comment]
> You might want to add some of this to your paper and to your readme.

Thanks for this suggestion. I have folded some of that language into both the README and our paper text's introduction.

**Comment by danielskatz** [comment]
👋 @luthaf, @rcannood, @ati-ozgur, @sptennak - would one or two of you be willing to review this submission to JOSS?

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02100/joss.02100/10.21105.joss.02100.pdf)

**Comment by Luthaf** [comment]
I'll be happy to!

**Comment by danielskatz** [comment]
Thanks. I’ll assign you now but we won’t start the review until we get another reviewer

**Comment by danielskatz** [comment]
@whedon assign @Luthaf as reviewer

**Comment by whedon** [comment]
OK, @Luthaf is now a reviewer

**Comment by rcannood** [comment]
Count me in! :+1:

**Comment by danielskatz** [comment]
@whedon add @rcannood as reviewer

**Comment by whedon** [comment]
OK, @rcannood is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2105.
