### ISSUE TITLE
[REVIEW]: CarrierCapture.jl: Anharmonic Carrier Capture

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2102]
**Submitting author:** @frssp (<a href="http://orcid.org/0000-0001-5072-6801">Sunghyun Kim</a>)
**Repository:** <a href="https://github.com/WMD-group/CarrierCapture.jl" target ="_blank">https://github.com/WMD-group/CarrierCapture.jl</a>
**Version:** v0.3
**Editor:** @danielskatz
**Reviewer:** @utf, @taylor-a-barnes
**Archive:** <a href="https://doi.org/10.5281/zenodo.3707592" target="_blank">10.5281/zenodo.3707592</a>

## Status

[![status](https://joss.theoj.org/papers/389d1f1765402a27d13830b691bf13d8/status.svg)](https://joss.theoj.org/papers/389d1f1765402a27d13830b691bf13d8)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/389d1f1765402a27d13830b691bf13d8"><img src="https://joss.theoj.org/papers/389d1f1765402a27d13830b691bf13d8/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/389d1f1765402a27d13830b691bf13d8/status.svg)](https://joss.theoj.org/papers/389d1f1765402a27d13830b691bf13d8)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/WMD-group/CarrierCapture.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@utf & @taylor-a-barnes, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/WMD-group/CarrierCapture.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@frssp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/WMD-group/CarrierCapture.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@frssp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @utf, @taylor-a-barnes it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/s41578-018-0026-7 is OK
- 10.1103/RevModPhys.86.253 is OK
- 10.1088/0034-4885/44/12/001 is OK
- 10.1103/PhysRevB.90.075202 is OK
- 10.1039/C8TA10130B is OK
- 10.1103/PhysRevB.100.041202 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02102/joss.02102/10.21105.joss.02102.pdf)

**Comment by danielskatz** [comment]
👋 @utf & @taylor-a-barnes - again, thanks very much for agreeing to this review.  Please read the comments above carefully, particularly in terms of accepting the invitation to be able to use the checkboxes, and in terms of not getting unwanted JOSS notifications.

**Comment by danielskatz** [comment]
Your job now is to examine the paper and the software, and to check off the items on your list that you can, and to explain what blocks you from checking off other items, either here if they are brief, or in new issues in the source repo if they are more complex.  (If you do open issues in the source repo, please mention this review issue in those issues so that we can see them here as well.)

We expect that the review will be done in a couple of weeks, at most, to happen, or at least it will get to a list of blocking items in that timeframe.

**Comment by taylor-a-barnes** [comment]
This is a very nice submission with a well-defined scope and general adherence to best practices.  I have just a couple of comments regarding the documentation, which are provided in the above issues.  Otherwise, I recommend that this paper be accepted.

**Comment by danielskatz** [comment]
Thanks @taylor-a-barnes! I note you didn't check the Functionality documentation checkbox, and that you opened 2 issues in the source repo that are now closed.  Did those changes resolve the overall issue for you, so that you can check off this final checkbox?  If not, what else do you think is needed?

**Comment by danielskatz** [comment]
👋 @utf - I also want to check in with you and see how your review is going...

**Comment by taylor-a-barnes** [comment]
The sentence at the end of the "Usage" section of the documentation is currently as follows:

> the detailed description provided in the [Usage section](https://wmd-group.github.io/CarrierCapture.jl/dev/usage.html).

This should be corrected for grammatical issues:

> A more detailed description is provided in the [Usage section](https://wmd-group.github.io/CarrierCapture.jl/dev/usage.html).

More importantly, the link is broken.  Once that is fixed, I can check the final checkbox.

**Comment by frssp** [comment]
The typo and the broken link are fixed.

**Comment by danielskatz** [comment]
👋 @utf - How is your review going?

**Comment by danielskatz** [comment]
FYI - I just emailed @utf to check on their status

**Comment by danielskatz** [comment]
I have an email from @utf that they will submit their reivew on Monday

**Comment by utf** [comment]
This is a fantastic package and will be of use to many researchers studying first-principles defects. The paper is well written and very clear. The package itself is well structured and the API is clean. The module level documentation is also excellent. Overall, I strongly recommend this paper be accepted.

I have a number of minor concerns which I've raised as pull requests and issues.

**Comment by danielskatz** [comment]
Thanks @utf - over to @frssp again now

**Comment by utf** [comment]
Everything has now been resolved except merging my PR here: WMD-group/CarrierCapture.jl#5

**Comment by frssp** [comment]
Merged.

**Comment by danielskatz** [comment]
👋 @frssp - At this point could you:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g. figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by frssp** [comment]
- [x] v0.3 is released
- [x] the release v0.3 is archived in Zenodo.
- [x] The Zenodo archive checked.
- [x] The DOI of the archived version is 10.5281/zenodo.3707592

**Comment by danielskatz** [comment]
@whedon set v0.3 as version

**Comment by whedon** [comment]
OK. v0.3 is the version.

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3707592 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3707592" target="_blank">10.5281/zenodo.3707592</a> is the archive.

**Comment by danielskatz** [comment]
@frssp - please fix the zenodo metadata so that the authors match the authors on the paper (order and real names)

**Comment by frssp** [comment]
The Zenodo metadata are updated.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02102/joss.02102/10.21105.joss.02102.pdf)

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/s41578-018-0026-7 is OK
- 10.1103/RevModPhys.86.253 is OK
- 10.1088/0034-4885/44/12/001 is OK
- 10.1103/PhysRevB.90.075202 is OK
- 10.1039/C8TA10130B is OK
- 10.1103/PhysRevB.100.041202 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@frssp - if you can merge https://github.com/WMD-group/CarrierCapture.jl/pull/10, we will be ready for final acceptance

**Comment by frssp** [comment]
Merged! Thanks @danielskatz

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/s41578-018-0026-7 is OK
- 10.1103/RevModPhys.86.253 is OK
- 10.1088/0034-4885/44/12/001 is OK
- 10.1103/PhysRevB.90.075202 is OK
- 10.1039/C8TA10130B is OK
- 10.1103/PhysRevB.100.041202 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published

. Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1367

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1367, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by frssp** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
I'm sorry @frssp, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1238089944570216448) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1368
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02102](https://doi.org/10.21105/joss.02102)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @utf & @taylor-a-barnes for reviewing!

**Comment by danielskatz** [comment]
Congratulations to @frssp and co-authors!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02102/status.svg)](https://doi.org/10.21105/joss.02102)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02102">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02102/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02102/status.svg
   :target: https://doi.org/10.21105/joss.02102
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02102/status.svg)](https://doi.org/10.21105/joss.02102)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by frssp** [comment]
Thanks, @danielskatz, and reviews @utf and @taylor-a-barnes.
Of course, thanks @whedon.
