### ISSUE TITLE
[REVIEW]: fleck: Fast approximate light curves for starspot rotational modulation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2103]
**Submitting author:** @bmorris3 (<a href="http://orcid.org/0000-0003-2528-3409">Brett Morris</a>)
**Repository:** <a href="https://github.com/bmorris3/fleck" target ="_blank">https://github.com/bmorris3/fleck</a>
**Version:** v1.0
**Editor:** @dfm
**Reviewer:** @nespinoza, @rodluger
**Archive:** <a href="https://doi.org/10.5281/zenodo.3700053" target="_blank">10.5281/zenodo.3700053</a>

## Status

[![status](https://joss.theoj.org/papers/dd737faef3d36ef40b428df69cc237c6/status.svg)](https://joss.theoj.org/papers/dd737faef3d36ef40b428df69cc237c6)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/dd737faef3d36ef40b428df69cc237c6"><img src="https://joss.theoj.org/papers/dd737faef3d36ef40b428df69cc237c6/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/dd737faef3d36ef40b428df69cc237c6/status.svg)](https://joss.theoj.org/papers/dd737faef3d36ef40b428df69cc237c6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bmorris3/fleck" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@nespinoza & @rodluger, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @dfm know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bmorris3/fleck">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@bmorris3) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bmorris3/fleck">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@bmorris3) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @nespinoza, @rodluger it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/mnras/sty568 is OK
- 10.1093/mnras/stz199 is OK
- 10.3847/1538-3881/aabc4f is OK

MISSING DOIs

- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02103/joss.02103/10.21105.joss.02103.pdf)

**Comment by dfm** [comment]
@rodluger, @nespinoza: Just a quick reminder that this has been submitted in collaboration with AAS. AAS makes a small donation to JOSS to support this process. For more information check out the following links and let me know if you have any issue with this:

- Blog post describing the collaboration: https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing
- Summary of JOSS financial model: https://joss.theoj.org/about#costs

**Comment by nespinoza** [comment]
Hi @bmorris3,

 First of all, thanks for this fantastic piece of software!

 I want to start my review by suggesting you mention in the documentation that this is a Python3-only package. I do know that this is now *the* Python standard, but it doesn't hurt to be nice to possible users --- especially given most OS older than ~last year come with Python 2.7 by default.

 In terms of the *functionality* of the code:

- I tried following the tutorial, but couldn't make the last plot of the "Getting started" tutorial (https://fleck.readthedocs.io/en/latest/fleck/gettingstarted.html). Just before the `plt.show()` call, when trying to make the `star.plot(` call, I get a: `'Star' object has no attribute 'plot'`. Perhaps this is a new function in the `Star` class that is on the Github but not in the pip-installable version of the code (which is how I installed `fleck`)?

 In terms of the *documentation* of the code:

- There is no explicit statement of need in the documentation. This is somewhat in the paper, but there is no introduction in the Read The Docs page for users that don't know what `fleck` is, what it does and what problems it is designed to do. I suggest creating an introductory page on the Read the Docs stating this.

- I think the community guidelines are not detailed enough, at least according to the checks we as reviewers have to do (see above). The Github repo does say that you "(...) love contributions", but it doesn't state explicitly how to submit contributions, if they must have, e.g., automated tests, etc. A simple sencence stating what you would want from contributions will suffice (e.g., "feel free to submit a pull request"). The same applies to any issues (I imagine you expect to use the Github issue tracker --- this should be stated) and support (e.g., should users reach out to you via e-mail? Github?).

 In terms of the *software paper*:

- I'm missing comparisons to other codes for rotational modulation and star-spotted transits such as e.g., `starry` (https://github.com/rodluger/starry), `spotrod` (https://github.com/bencebeky/spotrod) or `ellc` (https://github.com/pmaxted/ellc --- https://arxiv.org/pdf/1603.08484.pdf). Why is `fleck` needed in light of those existing algorithms? What is the advantage of using `fleck`?

- The paper mentions that the rapid computation of light curves allows to measure spot distributions with Approximate Bayesian Computation (ABC). Is there a reason why ABC is mentioned and not other bayesian optimization/posterior sampling methods? To be honest, that sentence makes me a little nervous because as a reviewer, I cannot know given the current state of the documentation if that statement is true or not. I suggest to either modify it to account for these concerns, remove it or add an optimization example in the documentation that uses either ABC or any other posterior sampling scheme out there.

**Comment by bmorris3** [comment]
Thanks so much for the initial review, @nespinoza! I really appreciated your close eye. 

RE Functionality: 
* I _should_ have done a pip release prior to submitting the paper, sorry I did not! I just pushed a newer version to PyPI which you should be able to grab with `pip install --upgrade fleck`. I also intend to do another release and increment to v0.1 once the JOSS submission is accepted.

RE Documentation: 
* You're right, I wrote most of the documentation while I was writing the code, that is to say, before I knew _exactly_ what I was going to do with it. I've updated the main landing page to reflect the text of the JOSS submission.
* I've added the required [statement about community contributions](https://github.com/bmorris3/fleck#contributing)

RE Software: 
* The primary use case for fleck is *ensemble* generation of thousands of light curves for use with ABC methods. As far as I know, the packages you mentioned are good for modeling individual stellar systems, whereas fleck is optimized for vectorized, ensemble analysis. I think I describe this in the paper, but perhaps I could describe it better? Suggestions welcome!

* This is a great point – I was definitely letting the AAS Journals submission do the talking about the Bayesian methods and I failed to internally document how to use fleck for ABC. I've added docs examples with Bayesian techniques: one on [MCMC](https://fleck.readthedocs.io/en/latest/fleck/bayes/mcmc.html) and one on [ABC](https://fleck.readthedocs.io/en/latest/fleck/bayes/abc.html).

**Comment by nespinoza** [comment]
Hi @bmorris3 --- thanks for the quick reply to the inquiries; I tested all the examples you added and all look great! I've checked the appropriate reviewer marks above, and all is almost ready to go on my side.

Regarding my comment on the paper, I think I understand that the methods and primary applications are different (i.e., you used this in the AAS submission to analyze _a sample_ of young stars, whereas the codes I mentioned above are used to model individual systems). However, in the documentation, you _do_ analyze individual stars (and spotted transits), and I believe this functionality and the caveats on that should be acknowledged in the paper or, at the very least, in the documentation itself. You could add something on the lines of "(...) while `fleck` is not intended to model individual stellar systems, it is able to do this reasonably well. However, other methods exist out there for this particular application such as X, Y, Z that might be better suited for those particular science cases".

**Comment by bmorris3** [comment]
Thanks for the reminder, sorry I didn't address that right away. I've updated the [text of the paper](https://github.com/bmorris3/fleck/blob/master/docs/paper.md#summary) to read: 

> While fleck is intended to model ensembles of light curves, we also include some examples of fitting light curves of individual spotted stars. Other methods exist which are more efficient for modeling individual systems, such as starry [Luger:2019] and spotrod [Beky:2014], and we encourage users to explore whether those packages might be ideal for modeling individual systems.

**Comment by nespinoza** [comment]
Thanks @bmorris3 for considering all the comments I made on this! @dfm, I think I have covered all the angles on my side of the review at least. On my side, I'm happy to recommend accepting `fleck` for publication pending the AAS submission status.

**Comment by dfm** [comment]
@rodluger: Any updates on this? I see that you've made some progress on the checklist, but can you let us know when you think you'll have it finished and if you have any questions that are holding it up? Thanks!

**Comment by rodluger** [comment]
Hi, sorry for the delay. I'll have this done by tomorrow. In the meantime, I raised three issues ([here](https://github.com/bmorris3/fleck/issues/1), [here](https://github.com/bmorris3/fleck/issues/2), and [here](https://github.com/bmorris3/fleck/issues/3)). I believe the first one is a bug in the plotting routine, the second is a user interface suggestion, and the third is a limitation of the model that has already been addressed & closed. @bmorris3, can you take a look at the remaining two issues when you get a chance? I'll have final comments in the next 24 hours.

**Comment by rodluger** [comment]
@dfm, is there a way to re-generate the article proof after Brett's recent changes?

**Comment by dfm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02103/joss.02103/10.21105.joss.02103.pdf)

**Comment by rodluger** [comment]
@bmorris3: I'm done checking everything off. Awesome work! @nespinoza touched on most of the things I would have commented on. I have no further comments other than the two outstanding issues.

**Comment by dfm** [comment]
@rodluger: Thanks!

@bmorris3: Can you report back here when:

1. You have address the final issues that @rodluger raised, and
2. You have the DOI of the accepted AAS paper. For reference, the DOI of this paper (when it is published) will be 10.21105.joss.02103. I believe that the AAS folks will want that.

**Comment by bmorris3** [comment]
@rodluger – thanks again!
@dfm – All of @rodluger's issues have been addressed.

**Comment by rodluger** [comment]
I confirm!

**Comment by dfm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/mnras/sty568 is OK
- 10.1093/mnras/stz199 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.3847/1538-3881/aae8e5 is OK
- 10.1093/mnras/stu1061 is OK

MISSING DOIs

- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation

INVALID DOIs

- None
```

**Comment by dfm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02103/joss.02103/10.21105.joss.02103.pdf)

**Comment by dfm** [comment]
Last thing (I think) for now: can you update the BibTeX entry for Numpy to include the DOI (https://doi.org/10.1109/mcse.2011.37)?

Then I'll pause this review until you have the DOI from the AAS journals.

**Comment by bmorris3** [comment]
Ok, I think I've [done it](https://github.com/bmorris3/fleck/blob/master/docs/paper.bib#L108) correctly.

**Comment by dfm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02103/joss.02103/10.21105.joss.02103.pdf)

**Comment by dfm** [comment]
@bmorris3: I submitted one more pull request with a BibTeX fix. After merging that, we should be good to go. I'll pause this review until the AAS paper has a DOI (when it is published). When that happens:

1. Update the `paper.md` file with the AAS journal name and DOI,
2. Create a new versioned release in the archive (make sure that the title and author list match the JOSS submission), and
3. Report back here with the new Zenodo (or similar) DOI and version number.

**Comment by arfon** [comment]
@dfm @bmorris3 - I just heard from AAS that their DOI will be `10.3847/1538-4357/ab79a0`.

**Comment by dfm** [comment]
Thanks @arfon! 

@bmorris3: You'll still need to go through the steps I listed above. When you do, let us know - thanks!

**Comment by bmorris3** [comment]
@dfm – `paper.md` has been updated, Zenodo DOI minted (https://doi.org/10.5281/zenodo.3700053) and [version number 1.0](https://github.com/bmorris3/fleck/releases/tag/v1.0) released.

**Comment by dfm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02103/joss.02103/10.21105.joss.02103.pdf)

**Comment by dfm** [comment]
@whedon set 10.5281/zenodo.3700053 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3700053" target="_blank">10.5281/zenodo.3700053</a> is the archive.

**Comment by dfm** [comment]
@whedon set v1.0 as version

**Comment by whedon** [comment]
OK. v1.0 is the version.

**Comment by dfm** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/mnras/sty568 is OK
- 10.1093/mnras/stz199 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1109/MCSE.2011.37 is OK
- 10.3847/1538-3881/aae8e5 is OK
- 10.1093/mnras/stu1061 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published

. Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1357

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1357, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by dfm** [comment]
@bmorris3: You should also take a look at the final proofs to make sure that it all looks good to you. Let us know if you see any issues!

**Comment by bmorris3** [comment]
Looks good to me! Thanks @dfm!

**Comment by Kevin-Mattheus-Moerman** [comment]
Please check the following: 
- [ ] Please make sure the Zenodo meta data such as the title and the author list match the JOSS paper. You can just edit this information on Zenodo. Currently both the title and the author set are different. 

- [ ] The statement concerning "...in about 10 seconds on a 2.5 GHz Intel Core i7 processor." is a bit vague. If you want to cite something like this I suggest you add more detail. There are various CPU's with a 2.5 GHz base frequency with varying degrees of performance. For instance the [i7-2860QM](https://ark.intel.com/content/www/us/en/ark/products/53476/intel-core-i7-2860qm-processor-8m-cache-up-to-3-60-ghz.html) has 4 cores, 8 threads and a 8Mb Cache, while the [i7-6500U](https://ark.intel.com/content/www/us/en/ark/products/88194/intel-core-i7-6500u-processor-4m-cache-up-to-3-10-ghz.html) only has 2 cores, 4 threads, and a 4Mb Cache. Also, computational time could highly depend on the system RAM. So perhaps say something like: 
"...in about 10 seconds on a regular personal computer (64-bit [Insert OS here], Intel Core i7 XXXXXX CPU, [insert memory amount] Gb RAM)." (I was assuming you are referring to performance on a standard desktop/laptop but change as you see fit).

**Comment by bmorris3** [comment]
Hi @Kevin-Mattheus-Moerman – sorry about the mismatch, do I create and edit a `.zenodo.json` file to edit the repo's metadata in the existing release?

**Comment by bmorris3** [comment]
Hi @Kevin-Mattheus-Moerman, I've edited the `paper.md` file according to your recommendations and fixed the zenodo metadata. Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02103/joss.02103/10.21105.joss.02103.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@bmorris3 thanks the Zenodo archive looks good. About the CPU specification. It still only mentions the base frequency. Can you add either the CPU id (I'm guessing you have the [i7-4870HQ](https://ark.intel.com/content/www/us/en/ark/products/83504/intel-core-i7-4870hq-processor-6m-cache-up-to-3-70-ghz.html), but check which one you have) or quote the number of cores, number of threads, and the cache size?

**Comment by bmorris3** [comment]
Sorry for my lack of precision, I had to dig a bit to verify the processor specs. [Done!](https://github.com/bmorris3/fleck/blob/master/docs/paper.md)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02103/joss.02103/10.21105.joss.02103.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1236981978999795713) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1360
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02103](https://doi.org/10.21105/joss.02103)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02103/status.svg)](https://doi.org/10.21105/joss.02103)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02103">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02103/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02103/status.svg
   :target: https://doi.org/10.21105/joss.02103
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02103/status.svg)](https://doi.org/10.21105/joss.02103)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by dfm** [comment]
@nespinoza, @rodluger: Thanks for your thoughtful and constructive reviews!

@bmorris3: Congrats on your new paper!
