### ISSUE TITLE
[REVIEW]: PySINDy: A Python package for the sparse identification of nonlinear dynamical systems from data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2104]
**Submitting author:** @briandesilva (<a href="http://orcid.org/0000-0003-0944-900X">Brian de Silva</a>)
**Repository:** <a href="https://github.com/dynamicslab/pysindy" target ="_blank">https://github.com/dynamicslab/pysindy</a>
**Version:** v0.12.0
**Editor:** @terrytangyuan
**Reviewer:** @sixpearls, @dawbarton
**Archive:** <a href="https://doi.org/10.5281/zenodo.3832319" target="_blank">10.5281/zenodo.3832319</a>

## Status

[![status](https://joss.theoj.org/papers/82d080bbe10ac3ab4bc03fa75f07d644/status.svg)](https://joss.theoj.org/papers/82d080bbe10ac3ab4bc03fa75f07d644)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/82d080bbe10ac3ab4bc03fa75f07d644"><img src="https://joss.theoj.org/papers/82d080bbe10ac3ab4bc03fa75f07d644/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/82d080bbe10ac3ab4bc03fa75f07d644/status.svg)](https://joss.theoj.org/papers/82d080bbe10ac3ab4bc03fa75f07d644)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dynamicslab/pysindy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sixpearls & @dawbarton, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @terrytangyuan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dynamicslab/pysindy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@briandesilva) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dynamicslab/pysindy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@briandesilva) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @sixpearls, @dawbarton it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1073/pnas.1517384113 is OK
- 10.1109/access.2018.2886528 is OK
- 10.1126/science.1165893 is OK
- 10.1103/physrevmaterials.2.083802 is OK
- 10.1111/j.2517-6161.1996.tb02080.x is OK
- 10.5281/zenodo.1173754 is OK
- 10.1364/oe.24.030433 is OK
- 10.1063/1.5066099 is OK
- 10.1063/1.4977057 is OK
- 10.1016/j.ymssp.2018.08.033 is OK
- 10.1126/sciadv.1602614 is OK
- 10.1098/rspa.2016.0446 is OK
- 10.1137/16m1086637 is OK
- 10.1137/18m116798x is OK
- 10.1017/jfm.2017.823 is OK
- 10.1063/1.5018409 is OK
- 10.1016/j.ifacol.2016.10.249 is OK
- 10.1103/physreve.96.023302 is OK
- 10.1016/j.jcp.2018.10.045 is OK
- 10.1098/rspa.2018.0335 is OK
- 10.1016/j.jcp.2019.07.049 is OK
- 10.1103/physreve.101.010203 is OK
- 10.1115/1.4043148 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02104/joss.02104/10.21105.joss.02104.pdf)

**Comment by sixpearls** [comment]
Hi @briandesilva et al, this is a very nice library! I checked most of the items in the list, but I did have a few comments, particularly on the unchecked items, below. 

## Authorship
I am not sure I see the SOFTWARE contribution of the last three authors, although it seems that based on the references these authors may have contributed to the theoretical development. In the past, I believe the JOSS policy was relatively strict about the software contribution of each author. Is that still the case? Could you please advise @terrytangyuan?

# Documentation:

## Statement of need

The documentation itself does not provide any statement of need or description of the mathematical formulation. I understand that the references that describe the problem are open-access, however in my experience there was a significant cognitive burden to understand the purpose of the library. These are my recommendations:
- [ ] At the very least, please provide a prose reference to the papers in the readme (as currently done in the top of the `sindy_paper.ipynb` example notebook).
- [ ] It would be nice to embed the example notebooks in the docs -- this would reduce the cognitive burden for understanding the purpose of the library prior to installation and (I believe sphinx does this automatically:) make it easier to download the notebook so users can play with them.
- [ ] It would be nice if a brief overview of the mathematics was included in at least one of the example notebooks; one particular benefit of using notebooks for examples is that it is easy to interweave the mathematical concepts with the code that implements it and that is essentially absent. For example, walking through some of the [supplemental examples](https://www.pnas.org/content/pnas/suppl/2016/03/23/1517384113.DCSupplemental/pnas.1517384113.sapp.pdf) or really the majority of the [unified framework paper](https://arxiv.org/pdf/1906.10612.pdf) including the equations and software implementation would be really nice. This could especially improve the API documentation for tuning the basis function family, optimizer, and other parameters, which is currently a bit difficult to parse through.
- [ ] It would greatly improve the experience for the reader to include at least some mathematical discussion and example code in the readme and setup.py `long_description` so that the benefits of the previous two suggests can be obtained for users without leaving github or PyPI.

## Tests

I have checked it off because there does seem to be a thorough set of tests that cover the API, but it would improve the library to include regression tests that verify performance. For example, tests comparing the optimizers should show LASSO producing a larger number of terms than SR3 or STLSQ produces.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by briandesilva** [comment]
Thanks, Arfon, for the update. At the moment we **do not** need to put a pause on our involvement in the review process.

**Comment by sixpearls** [comment]
Hi @briandesilva, I will be happy to do a follow up review when you are ready. I will need guidance on the authorship question.

@arfon could you advise on my authorship question?

> I am not sure I see the SOFTWARE contribution of the last three authors, although it seems that based on the references these authors may have contributed to the theoretical development. In the past, I believe the JOSS policy was relatively strict about the software contribution of each author. Is that still the case?

**Comment by arfon** [comment]
@sixpearls - we generally try and steer clear of making authorship decisions. That said, we definitely do *not* require that all authors have to have contributed code/commits to the software as it's clearly possible for people to be important members of a project/collaboration without actually authoring the git commits.

**Comment by sixpearls** [comment]
Thanks, @arfon. I must have been mis-remembering the policy. I'll check it off.

**Comment by briandesilva** [comment]
> * [ ]  It would greatly improve the experience for the reader to include at least some mathematical discussion and example code in the readme and setup.py `long_description` so that the benefits of the previous two suggests can be obtained for users without leaving github or PyPI.

@sixpearls, do you have any suggestions about how to render math in the README.rst file? I have drafted a simple mathematical description and some accompanying text for the README, but I have so far been unable to get any of the math to be rendered on GitHub.

After some poking around other repositories, the only solution I have been able to find is to export the rendered equations as images, then embed the images in the README (something like what [this repository](https://github.com/artivis/manif) does. This would work for users viewing the README on GitHub, but I'm not sure whether it would work for those viewing the package on PyPI.

Any recommendations you can provide on how to proceed would be greatly appreciated.

**Comment by sixpearls** [comment]
@briandesilva I can't find a better example, but I was imagining just a simple [ASCII formulation like this one](https://github.com/cvxgrp/dccp#dccp-rules). You could alternatively describe the mathematical concepts "in" Python or pseudocode. 

That said, Your update to the ["original paper" notebook](https://pysindy.readthedocs.io/en/latest/examples/2_original_paper.html#main-ideas) is exactly what I had in mind. Since your API is fairly semantic, I think a brief prose description with a well commented example and a link to the "main idea" section of this notebook (or breaking it out onto its own page) would be sufficient for the readme and PyPi long description.

**Comment by sixpearls** [comment]
I believe the PyPI long description can render images, but you would need to find a host to serve the graphic to PyPI and I'm not sure if GitHub does that. So, rather than using plots in the PyPI long description, you could do something like show the output of numpy's `isclose` function to verify the fit.

**Comment by briandesilva** [comment]
@sixpearls, I've added some information on the mathematics behind SINDy and a short example to the README (and the PyPI description). I also took your advice and moved the introduction to SINDY to its own notebook. Please take a look when you get a chance.

**Comment by sixpearls** [comment]
Hi @briandesilva, this looks great. I will check off the item from my review and recommend that this can be published. This is a great library, congratulations!

**Comment by arfon** [comment]
:wave: @dawbarton - how are you getting on with your review?

**Comment by dawbarton** [comment]
Apologies for the delay, life has been a bit manic (and I also missed the ping somehow). I have been through the package, documentation, and paper - it looks good overall. 

A few comments:

When I run the example in the README, I don't get the specified output. It's close but not quite the same; see below.

```
In [3]: model.print()                                                       
x' = -0.008 1 + -2.005 x + 0.002 y + 0.012 x y
y' = 1.000 y
```

Syntax highlighting in the docs is a little off - seems to get confused by ' characters.

Docs are relatively clear but slightly odd in places. For example, in the pysindy.feature_library package, the first class mentions things like `n_input_features\_`, and `n_output_features\_` but I can't see how these relate to the class (they don't appear to be parameters to the constructor or fields in the class - they are not valid identifiers). More of these terms ending with `\_` appear in the pysindy.optimizers package documentation.

The extensive examples are very nice. If only all packages had so many!

Overall, this is a great package. Thanks for putting it together.

**Comment by briandesilva** [comment]
Thanks for your feedback!
- I will have to look into the README example. This looks like a bug -- those small magnitude terms should be getting ruled out.
- @Ohjeah, do you know of any fixes for the syntax highlighting issue? It looks like it's only rendering incorrectly on the sphinx site. We could change the way we write the math (e.g. write something like dX/dt), but for the example where we show the output of `model.print()`, we would have to change the call to something like `model.print(lhs=['dx/dt', 'dy/dt'])'. This makes the example look a little more complex than I would like.
- Let me provide some context for why we included the `n_input_features_` and `n_output_features_` attributes. When building our feature library objects we looked to scikit-learn's [PolynomialFeatures](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html) class, which has these attributes itself. They aren't known until the `fit` function is called because they depend on the shape of the input data, so they are automatically set then. Again, we are essentially just copying the structure of `PolynomialFeatures`. In any case, it looks like class attributes are not being rendered like I'd expect on the documentation site. They should be presented in a list under the heading "Attributes", but that's not how they're currently displayed. Sphinx is also adding extra backslashes before trailing underscores for these attributes. I will look into it.

**Comment by Ohjeah** [comment]
Equation formatting in the readme is fixed now. The code-blocks were automatically interpreted as python and hence the funny looking syntax highlighting.

**Comment by briandesilva** [comment]
@dawbarton, we have updated the package and documentation to address each of your comments. When you get a chance could you please take another look to make sure everything meets your standards?

**Comment by dawbarton** [comment]
I haven't checked whether you've fixed the regression with the readme example but everything else looks good to me. 👍

**Comment by briandesilva** [comment]
Great! Is there anything else we need to do to move things forward?

**Comment by arfon** [comment]
> Great! Is there anything else we need to do to move things forward?

Sorry for the delay here @briandesilva - the handling editor (@terrytangyuan) has limited availability to edit right now but I can help moving this forward.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02104/joss.02104/10.21105.joss.02104.pdf)

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1073/pnas.1517384113 is OK
- 10.1109/access.2018.2886528 is OK
- 10.1126/science.1165893 is OK
- 10.1103/physrevmaterials.2.083802 is OK
- 10.1111/j.2517-6161.1996.tb02080.x is OK
- 10.5281/zenodo.1173754 is OK
- 10.1364/oe.24.030433 is OK
- 10.1063/1.5066099 is OK
- 10.1063/1.4977057 is OK
- 10.1016/j.ymssp.2018.08.033 is OK
- 10.1126/sciadv.1602614 is OK
- 10.1098/rspa.2016.0446 is OK
- 10.1137/16m1086637 is OK
- 10.1137/18m116798x is OK
- 10.1017/jfm.2017.823 is OK
- 10.1063/1.5018409 is OK
- 10.1016/j.ifacol.2016.10.249 is OK
- 10.1103/physreve.96.023302 is OK
- 10.1016/j.jcp.2018.10.045 is OK
- 10.1098/rspa.2018.0335 is OK
- 10.1016/j.jcp.2019.07.049 is OK
- 10.1103/physreve.101.010203 is OK
- 10.1115/1.4043148 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@briandesilva - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by terrytangyuan** [comment]
@arfon Thanks. Please take it from here since it will be ready for handing over to you anyways soon for final acceptance and deposit.

**Comment by briandesilva** [comment]
@arfon - I have made a new release including all the changes prompted by this review. Here is the Zenodo DOI for PySINDy: [![DOI](https://zenodo.org/badge/186055899.svg)](https://zenodo.org/badge/latestdoi/186055899)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3832319 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3832319" target="_blank">10.5281/zenodo.3832319</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1073/pnas.1517384113 is OK
- 10.1109/access.2018.2886528 is OK
- 10.1126/science.1165893 is OK
- 10.1103/physrevmaterials.2.083802 is OK
- 10.1111/j.2517-6161.1996.tb02080.x is OK
- 10.5281/zenodo.1173754 is OK
- 10.1364/oe.24.030433 is OK
- 10.1063/1.5066099 is OK
- 10.1063/1.4977057 is OK
- 10.1016/j.ymssp.2018.08.033 is OK
- 10.1126/sciadv.1602614 is OK
- 10.1098/rspa.2016.0446 is OK
- 10.1137/16m1086637 is OK
- 10.1137/18m116798x is OK
- 10.1017/jfm.2017.823 is OK
- 10.1063/1.5018409 is OK
- 10.1016/j.ifacol.2016.10.249 is OK
- 10.1103/physreve.96.023302 is OK
- 10.1016/j.jcp.2018.10.045 is OK
- 10.1098/rspa.2018.0335 is OK
- 10.1016/j.jcp.2019.07.049 is OK
- 10.1103/physreve.101.010203 is OK
- 10.1115/1.4043148 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1450

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1450, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1262477033113817089) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1451
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02104](https://doi.org/10.21105/joss.02104)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@sixpearls, @dawbarton - many thanks for your reviews here and to @terrytangyuan for editing this submission ✨ 

@briandesilva - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02104/status.svg)](https://doi.org/10.21105/joss.02104)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02104">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02104/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02104/status.svg
   :target: https://doi.org/10.21105/joss.02104
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02104/status.svg)](https://doi.org/10.21105/joss.02104)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
