### ISSUE TITLE
[REVIEW]: MaterialNet: A web-based graph explorer for materials science data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2105]
**Submitting author:** @waxlamp (<a href="http://orcid.org/0000-0003-3898-4626">Roni Choudhury</a>)
**Repository:** <a href="https://github.com/ToyotaResearchInstitute/materialnet" target ="_blank">https://github.com/ToyotaResearchInstitute/materialnet</a>
**Version:** v1.0.0
**Editor:** @danielskatz
**Reviewer:** @Luthaf, @rcannood
**Archive:** <a href="https://doi.org/10.5281/zenodo.3701759" target="_blank">10.5281/zenodo.3701759</a>

## Status

[![status](https://joss.theoj.org/papers/7e663b9196c523b88d2de24fb20ecdac/status.svg)](https://joss.theoj.org/papers/7e663b9196c523b88d2de24fb20ecdac)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7e663b9196c523b88d2de24fb20ecdac"><img src="https://joss.theoj.org/papers/7e663b9196c523b88d2de24fb20ecdac/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7e663b9196c523b88d2de24fb20ecdac/status.svg)](https://joss.theoj.org/papers/7e663b9196c523b88d2de24fb20ecdac)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ToyotaResearchInstitute/materialnet" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Luthaf & @rcannood, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ToyotaResearchInstitute/materialnet">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@waxlamp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ToyotaResearchInstitute/materialnet">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@waxlamp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Luthaf, @rcannood it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/npjcompumats.2015.10 is OK
- 10.1063/1.4812323 is OK
- 10.1016/j.commatsci.2012.02.002 is OK
- 10.1038/s41467-019-10030-5 is OK
- 10.1016/j.matt.2019.10.024 is OK
- 10.1021/cm503507h is OK
- 10.1109/TVCG.2013.173 is OK
- 10.1103/PhysRevB.96.024104 is OK
- 10.1021/acs.jcim.9b00470 is OK
- 10.1038/s41586-019-1335-8 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02105/joss.02105/10.21105.joss.02105.pdf)

**Comment by danielskatz** [comment]
👋 @Luthaf & @rcannood - thanks for agreeing to review - here's where the action happens.

Please read the comments above carefully, particularly in terms of accepting the invitation to be able to use the checkboxes, and in terms of not getting unwanted JOSS notifications.

Your job now is to examine the paper and the software, and to check off the items on your list that you can, and to explain what blocks you from checking off other items, either here if they are brief, or in new issues in the source repo if they are more complex. (If you do open issues in the source repo, please mention this review issue in those issues so that we can see them here as well.)

We expect that the review will be done in a couple of weeks, at most, or at least it will get to a list of blocking items in that timeframe.

**Comment by Luthaf** [comment]
@danielskatz, are they JOSS guideline for documentation concerning SaaS/Online tools? Is user documentation/developer reference/separate installation information something that is required?

**Comment by danielskatz** [comment]
> are they JOSS guideline for documentation concerning SaaS/Online tools? Is user documentation/developer reference/separate installation information something that is required?

JOSS doesn't really provide detailed guidance here. You should probably consider this from the point of view of a user who wants to use the SaaS as well as a developer who wants to understand and potentially contribute to the underlying software.

**Comment by waxlamp** [comment]
> > are they JOSS guideline for documentation concerning SaaS/Online tools? Is user documentation/developer reference/separate installation information something that is required?
> 
> JOSS doesn't really provide detailed guidance here. You should probably consider this from the point of view of a user who wants to use the SaaS as well as a developer who wants to understand and potentially contribute to the underlying software.

Thanks for this insight. Creating detailed developer documentation is currently out of scope for our project, but of course I can see how it would enrich our open source offering here.

**Comment by danielskatz** [comment]
I think that's a reasonable answer, as long as the community guidelines match - expectations for community contributions will depend on developer documentation to some extent.

**Comment by waxlamp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02105/joss.02105/10.21105.joss.02105.pdf)

**Comment by rcannood** [comment]
Would be nice if @whedon could also generate a diff :) 

[Here](https://github.com/ToyotaResearchInstitute/materialnet/compare/470318edf5b9234c1dab672061aa1c11da8b8145...master#diff-16d3fe279379b2a19e836e62ab840c12) are the changes w.r.t. the original proof.

**Comment by rcannood** [comment]
@danielskatz I believe @Luthaf and I have ticked all the checkboxes :)

**Comment by danielskatz** [comment]
great, thanks very much to both of you

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
PDF failed to compile for issue #2105 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2105 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/npjcompumats.2015.10 is OK
- 10.1063/1.4812323 is OK
- 10.1016/j.commatsci.2012.02.002 is OK
- 10.1038/s41467-019-10030-5 is OK
- 10.1016/j.matt.2019.10.024 is OK
- 10.1021/cm503507h is OK
- 10.1109/TVCG.2013.173 is OK
- 10.1103/PhysRevB.96.024104 is OK
- 10.1021/acs.jcim.9b00470 is OK
- 10.1038/s41586-019-1335-8 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02105/joss.02105/10.21105.joss.02105.pdf)

**Comment by danielskatz** [comment]
👋 @waxlamp - please check the references, particular the cases (upper vs lower) for title and journal names. Add {}s in the .bib file to protect cases through compilation, and then use ```@whedon generate pdf``` to generate a new PDF.  The immediate thing I see is that voronoi should be Voronoi, but please check for anything else as well.

**Comment by danielskatz** [comment]
I've also created https://github.com/ToyotaResearchInstitute/materialnet/pull/175 with a few more changes in the paper, and a question about wording.

**Comment by waxlamp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02105/joss.02105/10.21105.joss.02105.pdf)

**Comment by danielskatz** [comment]
Thanks - looks good.  At this point could you:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g. figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by waxlamp** [comment]
Here's the requested information:
- tagged release version: v1.0.0 (https://github.com/ToyotaResearchInstitute/materialnet/releases/tag/v1.0.0)
- Zenodo DOI: http://doi.org/10.5281/zenodo.3701759

Please let me know if these look ok.

**Comment by danielskatz** [comment]
@whedon set v1.0.0 as version

**Comment by whedon** [comment]
OK. v1.0.0 is the version.

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3701759 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3701759" target="_blank">10.5281/zenodo.3701759</a> is the archive.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published

. Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1364

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1364, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1237099083942318080) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1365
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02105](https://doi.org/10.21105/joss.02105)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @Luthaf and @rcannood for reviewing, and congratulations to @waxlamp and coauthors!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02105/status.svg)](https://doi.org/10.21105/joss.02105)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02105">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02105/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02105/status.svg
   :target: https://doi.org/10.21105/joss.02105
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02105/status.svg)](https://doi.org/10.21105/joss.02105)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by waxlamp** [comment]
> Thanks to @Luthaf and @rcannood for reviewing, and congratulations to @waxlamp and coauthors!

Thank you, reviewers! And thank you @danielskatz for your support during this very first JOSS paper submission experience for me!
