### ISSUE TITLE
[REVIEW]: SampleDB: A sample and measurement metadata database

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2107]
**Submitting author:** @FlorianRhiem (<a href="http://orcid.org/0000-0001-6461-9433">Florian Rhiem</a>)
**Repository:** <a href="https://github.com/sciapp/sampledb" target ="_blank">https://github.com/sciapp/sampledb</a>
**Version:** 0.17.0
**Editor:** @arfon
**Reviewer:** @stuartcampbell, @dvanic
**Archive:** <a href="https://doi.org/10.5281/zenodo.4529206" target="_blank">10.5281/zenodo.4529206</a>

## Status

[![status](https://joss.theoj.org/papers/3769b983ef954e66bf7e3e7d064e7c7e/status.svg)](https://joss.theoj.org/papers/3769b983ef954e66bf7e3e7d064e7c7e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3769b983ef954e66bf7e3e7d064e7c7e"><img src="https://joss.theoj.org/papers/3769b983ef954e66bf7e3e7d064e7c7e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3769b983ef954e66bf7e3e7d064e7c7e/status.svg)](https://joss.theoj.org/papers/3769b983ef954e66bf7e3e7d064e7c7e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/sciapp/sampledb" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@stuartcampbell & @dvanic, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @trallard know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sciapp/sampledb">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@FlorianRhiem) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sciapp/sampledb">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@FlorianRhiem) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @eteq, @dvanic it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02107/joss.02107/10.21105.joss.02107.pdf)

**Comment by danielskatz** [comment]
👋 @eteq, @dvanic - It doesn't look like there's been any progress on this review in about 3 1/2 weeks - Can everyone please check in and provide an estimate of when your reviews might be started/finished?

**Comment by FlorianRhiem** [comment]
@trallard SampleDB v0.9.0 has been released yesterday. I've updated the [`paper.json`](https://github.com/sciapp/sampledb/blob/develop/docs/publications/joss/paper.json). Could you please run `@whedon set v0.9.0 as version` to update the version here?

**Comment by trallard** [comment]
@whedon set v0.9.0 as version

**Comment by whedon** [comment]
OK. v0.9.0 is the version.

**Comment by trallard** [comment]
@eteq and @dvanic any chance you could check in an give any updates re
 your review?

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arfon** [comment]
:wave: @eteq & @dvanic, just a friendly check-in to see how things are going with your reviews?

**Comment by FlorianRhiem** [comment]
@trallard I have just released SampleDB v0.10.0. Could you please run `@whedon set v0.10.0 as version` so that it is updated here? Thank you!

**Comment by arfon** [comment]
@whedon set v0.10.0 as version

**Comment by whedon** [comment]
OK. v0.10.0 is the version.

**Comment by arfon** [comment]
👋 @eteq & @dvanic - today we [reopened JOSS](https://blog.joss.theoj.org/2020/05/reopening-joss) for new submissions and are checking in on our existing reviews. Do you think you might be able to wrap up your reviews in the next 2-3 weeks?

**Comment by trallard** [comment]
Hi folks just checking in on the status as per Arfon's message. 
Any updates on the reviews @eteq @dvanic

**Comment by dvanic** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by dvanic** [comment]
@whedon I need a new invitation: 
![image](https://user-images.githubusercontent.com/3272378/84238511-8079a800-ab3e-11ea-8681-997976925253.png)

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by dvanic** [comment]
@whedon generate pdf

**Comment by dvanic** [comment]
@whedon check references

**Comment by dvanic** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.34 s (345.2 files/s, 64768.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         223           6529           3385          30001
JavaScript                      76           2128           2083          17229
CSS                             16             58             74          10764
HTML                            96            204             12           5965
SVG                              2              0              0           2959
JSON                            31              0              0           2604
reStructuredText                11            678           1092            391
YAML                             1              8             11            112
Markdown                         3             38              0            101
TeX                              1              0              0             28
Dockerfile                       1              9              7             20
-------------------------------------------------------------------------------
SUM:                           461           9652           6664          70174
-------------------------------------------------------------------------------


Statistical information for the repository '2107' was gathered on 2020/06/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel Kaiser                    1            84             12            0.10
Dorothea Henkel                 56          5257           2195            7.54
Florian Rhiem                  360         74066          16361           91.49
peters@iff242                    5           720            141            0.87

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Daniel Kaiser                72           85.7         20.0                0.00
Dorothea Henkel            2187           41.6         37.2                9.37
Florian Rhiem             58985           79.6         27.9                6.16
peters@iff242               185           25.7         20.8                0.00
```

**Comment by dvanic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02107/joss.02107/10.21105.joss.02107.pdf)

**Comment by dvanic** [comment]
# Review checklist for @dvanic
## Conflict of interest

- [x] I confirm that I have read the JOSS conflict of interest (COI) policy and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

## Code of Conduct
- [x] I confirm that I read and will adhere to the JOSS code of conduct.

## General checks

- [x] Repository: Is the source code for this software available at the repository url?
- [x] License: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?

- [x] Contribution and authorship: Has the submitting author (@FlorianRhiem) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

## Functionality

- [x] Installation: Does installation proceed as outlined in the documentation?
- [ ] Functionality: Have the functional claims of the software been confirmed?

     - Note: not yet. There are challenges with documentation around setting up new users, groups and projects. 

 - [x] Performance: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

## Documentation

- [x] A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

- [x] Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

- [ ] Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

This is the area I struggled with the most: I could not identify clear documentation on how to set up a completely new instance of sampleDB at a new institution, add users, groups, projects, metadata, samples, instruments etc, and then how to proceed to a tracked lifecycle of samples and visualisations in Jupyter. 

Please note I followed the "Getting Started" instructions in the GitHub repository, and while I could try to read the output options for all of the possible commands in `docker exec sampledb env/bin/python -m sampledb help` it's not clear what the optimal/recommended order of setup is. To enable wide adoption of this tool a case study of setting up a basic database is vital (because I genuinely think this is a very useful software, that really could be adopted beyond the institution in which it was developed!).

- [x] Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

API documentation is available. Due to not being able to set up or access a dummy database I was unable to test it.

- [x] Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

- [ ] Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

It is not clear how users are meant to seek support: also via GitHub issues?



## Software paper

- [x] Summary: Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?

Yes, although the database could be of use beyond physics (for ex. in the life sciences, especially biology), and I'm not sure the provided description would enable life science users to see this.

- [x] A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

Yes.

- [ ] State of the field: Do the authors describe how this software compares to other commonly-used packages?

No. No mention of other packages is made.

- [x] Quality of writing: Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?

- [ ] References: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper citation syntax?

No scientific publications are cited - only references to software tools that underpin the database, and a metapaper around research data management. 

## Footnote

I'd like to personally apologize to @FlorianRhiem for the amount of time it's taken me to review this. While I'm fortunate enough to be in Australia, where COVID has not raged as widely as in many other parts of the world, our workload this semester has been horrific due to the move to online teaching/training (as well as the challenges of childcare and life). @FlorianRhiem I am SO sorry for how long this review has taken! And while I have made some suggestions, I think this is a very useful piece of software, and one we can potentially adapt to some of the work we do with researchers at the Sydney Informatics Hub/University of Sydney.

**Comment by FlorianRhiem** [comment]
Thank you for the review, Darya. I'm glad to hear that you think SampleDB could be useful for more researchers and I will try to fix these issues until the end of next week.

I think the most difficult points will be the documentation for more than the minimal setup and for the JupyterHub integration. For both there are dependencies to likely existing IT infrastructure (where should backups be stored, which volumes are mounted by the JupyterHub notebook servers, etc.), but I will try to keep the information as independent of these details as possible. Currently the online documentation is only updated for the tagged releases, so if that's alright with you, I will post drafts for these texts in the GitHub issues you opened, so that you can let me know whether something is missing or too vague.

**Comment by FlorianRhiem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02107/joss.02107/10.21105.joss.02107.pdf)

**Comment by FlorianRhiem** [comment]
I have created an Administrator Guide with a new [Getting Started](https://scientific-it-systems.iffgit.fz-juelich.de/SampleDB/administrator_guide/getting_started.html) guide, which walks readers through the first steps. I hope this solves the functionality and documentation issues for setting up SampleDB. If information on a particular step is still missing or too vague, please let me know!

I have added a Support section to the README and also recommend opening GitHub issues at the end of the Getting Started guide.

I have updated the paper to include a paragraph in which I discuss what I see as the largest difference between SampleDB and other applications with similar goals, in particular JuliaBase and BikaLIMS / Senaite, and which advantages and disadvantages result from this. In terms of goals, JuliaBase is the closest to SampleDB, but BikaLIMS / Senaite include sample management as a core feature as well and I think it's worth mentioning them as their approach of having pre-defined calculations might be something worth exploring in the future, for use cases where a data analysis in a Jupyter notebook might not be necessary.

I have also added a reference to [The FAIR Guiding Principles for scientific data management and stewardship](https://www.nature.com/articles/sdata201618) and updated the text to include more than just making the data accessible, as the motivation and reasoning behind the FAIR principles as presented in the paper match the motivation behind SampleDB as well.

I hope I have addressed the issues with SampleDB and the paper, either here or in the GitHub Issues of the project. Please let me know what I can improve and thank you again for taking the time to review the paper, particular given the current situation.

---

@trallard I've released SampleDB 0.11.0, could you please updated the version with whedon? Thank you!

**Comment by trallard** [comment]
@whedon set version as 0.11.0

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by trallard** [comment]
@whedon set 0.11.0 as version

**Comment by whedon** [comment]
OK. 0.11.0 is the version.

**Comment by trallard** [comment]
@FlorianRhiem thanks for the ping I have updated the version but will have to rectify as the review moves forward.

--
@eteq, @dvanic how are your reviews coming along? Do you need any support from my side?

**Comment by trallard** [comment]
@eteq, @dvanic gentle ping again. Are there any blockers for your reviews, would it be possible to move them forward?

**Comment by FlorianRhiem** [comment]
SampleDB 0.14 was released yesterday.

Is there any way I can help you with the review?

**Comment by arfon** [comment]
:wave: @trallard - it might be a good idea to try contacting our reviewers via email at this point? Many of our reviewers struggle with GitHub notifications and I'm wondering if this review has got lost in the noise :-/

**Comment by dvanic** [comment]
@arfon / @trallard  - I have reviewed this and think the issued I identified have been resolved with the new documentation.

**Comment by arfon** [comment]
@trallard - I think we're going to need to find a second reviewer for this submission as it doesn't look like @eteq is going to be able to assist here.

**Comment by arfon** [comment]
:wave: @celliern @dvanic @schnorr, would any of you be willing to provide a second review for this submission to JOSS?

The title of the submission is _"SampleDB: A sample and measurement metadata database"_, which describes a [Python package](https://github.com/sciapp/sampledb) for managing experiments. Quoting from the SampleDB website: 

> SampleDB is a web-based sample and measurement metadata database developed at PGI and JCNS. Scientists can use SampleDB to store and retrieve information on samples, measurements and simulations, analyze them using Jupyter notebooks, track sample locations and responsibilities and view sample lifecycles. As a tool for reproducible and sustainable science, it facilitates long-term storage of research data with clear benefits to scientists, interfaces with dedicated JupyterHub instances and can be integrated in instrument systems to automate data entry. A schema system allows users to store and search even complex types of metadata, and the powerful permission system ensures that information stays secure while simplifying collaboration with external users.

Our request here would be that you review the [software](https://github.com/sciapp/sampledb) and [short paper](https://github.com/openjournals/joss-papers/blob/joss.02107/joss.02107/10.21105.joss.02107.pdf), following the JOSS [checklist-driven review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

Many thanks!

**Comment by arfon** [comment]
> @arfon / @trallard - I have reviewed this and think the issued I identified have been resolved with the new documentation.

Thanks for your review here @dvanic. Could I ask you to check of any remaining items in your checklist at the top of the issue (assuming these criteria have now been met)?

**Comment by arfon** [comment]
👋 @DanNixon @stuartcampbell @cmbiwer, would any of you be willing to provide a second review for this submission to JOSS?

The title of the submission is _"SampleDB: A sample and measurement metadata database"_, which describes a [Python package](https://github.com/sciapp/sampledb) for managing experiments. Quoting from the SampleDB website: 

> SampleDB is a web-based sample and measurement metadata database developed at PGI and JCNS. Scientists can use SampleDB to store and retrieve information on samples, measurements and simulations, analyze them using Jupyter notebooks, track sample locations and responsibilities and view sample lifecycles. As a tool for reproducible and sustainable science, it facilitates long-term storage of research data with clear benefits to scientists, interfaces with dedicated JupyterHub instances and can be integrated in instrument systems to automate data entry. A schema system allows users to store and search even complex types of metadata, and the powerful permission system ensures that information stays secure while simplifying collaboration with external users.

Our request here would be that you review the [software](https://github.com/sciapp/sampledb) and [short paper](https://github.com/openjournals/joss-papers/blob/joss.02107/joss.02107/10.21105.joss.02107.pdf), following the JOSS [checklist-driven review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

Many thanks!

**Comment by stuartcampbell** [comment]
Yes I'd be happy to help.

**Comment by arfon** [comment]
@whedon re-invite @stuartcampbell as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@stuartcampbell please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by arfon** [comment]
> Yes I'd be happy to help.

Great! Many thanks! Please accept the invite in the post above to start. I've added a review checklist for you above too.

**Comment by stuartcampbell** [comment]
@arfon I think I am done with my review.  I have created a couple of issues over on the SampleDB Github site, but I don't think that they need to hold up this paper.  They are more comments and nice to haves.

**Comment by arfon** [comment]
@stuartcampbell - many thanks! 

@FlorianRhiem – At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by FlorianRhiem** [comment]
@arfon Thank you, I have created a new release (version 0.17.0), updated the paper.json accordingly and updated the auto-generated Zenodo entry to have the correct title and author: https://doi.org/10.5281/zenodo.4529206

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4529206 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4529206" target="_blank">10.5281/zenodo.4529206</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2082

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2082, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/sdata.2016.18 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@FlorianRhiem - please give the paper proof linked to in https://github.com/openjournals/joss-papers/pull/2082 a final proof read (I will do the same).

**Comment by FlorianRhiem** [comment]
The proof looks good to me. 👍 The top whedon post here still has version 0.11.0, but I didn't find that version referenced in either the paper or the crossref XML, so I guess that's fine and just for reviewing?

**Comment by arfon** [comment]
@whedon set 0.17.0 as version

**Comment by whedon** [comment]
OK. 0.17.0 is the version.

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1359623269704486912) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2083
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02107](https://doi.org/10.21105/joss.02107)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@stuartcampbell, @dvanic - many thanks for your reviews here! JOSS relies upon the volunteer efforts of folks like yourselves and we simply wouldn't be able to do this without you ✨ 

@FlorianRhiem - your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02107/status.svg)](https://doi.org/10.21105/joss.02107)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02107">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02107/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02107/status.svg
   :target: https://doi.org/10.21105/joss.02107
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02107/status.svg)](https://doi.org/10.21105/joss.02107)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by eteq** [comment]
While know this is like a year after the fact, it came up in a search for my recently and I just want to publicly apologies for ghosting y'all here.  This was definitely a victim of COVID/childcare/inability to keep up with committments in 2020, but I apologize all the same.
