### ISSUE TITLE
[PRE REVIEW]: Maelstrom: A Python package for identifying companions to pulsating stars from their light travel time variations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2108]
**Submitting author:** @danhey (<a href="http://orcid.org/0000-0003-3244-5357">Daniel Hey</a>)
**Repository:** <a href="https://github.com/danhey/maelstrom" target ="_blank">https://github.com/danhey/maelstrom</a>
**Version:** v0.2
**Editor:** @mbobra
**Reviewers:** @hpparvi, @DingXuefeng
**Managing EiC:** Kyle Niemeyer

**Author instructions**

Thanks for submitting your paper to JOSS @danhey. **Currently, there isn't an JOSS editor assigned** to your paper.

@danhey if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2108 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2108 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/nature24153 is OK
- 10.1093/mnras/stv884 is OK
- 10.1016/0370-2693(87)91197-X is OK
- 10/gdk3dm is OK
- 10.5281/zenodo.3359880 is OK
- 10.1093/mnras/stw1622 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon invite @mbobra as editor

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
@openjournals/dev any ideas why the paper won't compile? I see there is a figure, but can't decipher the error message.

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02108/joss.02108/10.21105.joss.02108.pdf)

**Comment by xuanxu** [comment]
@kyleniemeyer It looks like there was a problem finding the paper file in the initial import

**Comment by arfon** [comment]
:wave: @danhey - does this paper accompany a publication in a AAS journal?

**Comment by mbobra** [comment]
@whedon assign @mbobra as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by danhey** [comment]
>  @danhey - does this paper accompany a publication in a AAS journal?

Yes! The paper is currently in review. I submitted under the dual-review system, so the editors are aware of the JOSS review

**Comment by arfon** [comment]
@mbobra - I've just added some docs on how to handle these papers that are being jointly published with AAS: https://joss.readthedocs.io/en/latest/editing.html#handling-of-papers-published-together-with-aas-publishing

/ cc @crawfordsm

**Comment by mbobra** [comment]
@whedon assign @hpparvi as reviewer

**Comment by whedon** [comment]
OK, @hpparvi is now a reviewer

**Comment by mbobra** [comment]
Thanks for agreeing to review, @hpparvi! I'm still working on securing a second referee, so I'll start the review after I do that.

**Comment by DingXuefeng** [comment]
I can review

**Comment by mbobra** [comment]
@whedon add @DingXuefeng as reviewer

**Comment by whedon** [comment]
OK, @DingXuefeng is now a reviewer

**Comment by mbobra** [comment]
@DingXuefeng @hpparvi

This JOSS submission/paper is a joint publication with AAS Journals, i.e. this JOSS paper will be published together with another paper in one of the AAS journals. As part of this collaboration, AAS publishing makes a small donation to the running costs of JOSS. 

If this is unacceptable to you, please let me know and I can look for alternative reviewers.

Some related links:

- Blog post describing the collaboration: https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing
- Summary of JOSS financial model: https://joss.theoj.org/about#costs

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2125.
