### ISSUE TITLE
[PRE REVIEW]: TESPy: Thermal Engineering Systems in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2109]
**Submitting author:** @fwitte (<a href="http://orcid.org/0000-0003-4019-0390">Francesco Witte</a>)
**Repository:** <a href="https://github.com/oemof/tespy" target ="_blank">https://github.com/oemof/tespy</a>
**Version:** 0.2.2
**Editor:** @kyleniemeyer
**Reviewers:** @arosen93, @corentin-dev
**Managing EiC:** Kyle Niemeyer

**Author instructions**

Thanks for submitting your paper to JOSS @fwitte. **Currently, there isn't an JOSS editor assigned** to your paper.

@fwitte if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.50 s (247.3 files/s, 93867.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                             33             11             99          17337
Python                          39           4700           8964          10339
reStructuredText                44           1130           1302           2186
JSON                             2              0              0            245
Markdown                         2             34              0            132
TeX                              1             11              0            120
YAML                             2             10             14             55
-------------------------------------------------------------------------------
SUM:                           123           5896          10379          30414
-------------------------------------------------------------------------------


Statistical information for the repository '2109' was gathered on 2020/02/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Francesco Witte               1057        104076          86652           88.32
MarBrandt                        1            20             18            0.02
Markus Brandt                   26         12514          10870           10.83
Paul-Jonas                       2           217             33            0.12
Shuang Chen                      4            56             10            0.03
TimHoener                       11           488            645            0.52
jfreissmann                      1            31             31            0.03
maltefritz                      11           128            137            0.12
nilsstolze                       1            10              2            0.01
uwe                              1             0              1            0.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Francesco Witte           17233           16.6          5.5               10.11
MarBrandt                  5737        28685.0          3.1               11.36
Markus Brandt               916            7.3          3.5               11.14
TimHoener                     9            1.8          8.8                0.00
maltefritz                  108           84.4          2.7                0.93
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1021/ie4033999 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1016/j.applthermaleng.2019.114750 is OK
- 10.1007/978-3-662-49568-1 is OK
- 10.1016/j.esr.2018.07.001 is OK
- 10.5281/ZENODO.591265 is OK
- 10.1007/978-3-7091-1182-6 is OK
- 10.1144/petgeo2016-050 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1038/s41592-019-0686-2 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02109/joss.02109/10.21105.joss.02109.pdf)

**Comment by kyleniemeyer** [comment]
@whedon invite @katyhuff as editor

**Comment by whedon** [comment]
@katyhuff has been invited to edit this submission.

**Comment by fwitte** [comment]
@whedon generate pdf

**Comment by fwitte** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02109/joss.02109/10.21105.joss.02109.pdf)

**Comment by fwitte** [comment]
I checked the list of reviewers, these may be interested:

- arosen93
- corentin-dev
- JaroslavHron
- jgoldfar
- pdebuyl
- maybe yourself, @kyleniemeyer?

Best regards
Francesco

**Comment by kyleniemeyer** [comment]
@katyhuff you can disregard that edit request, I can take this one

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by fwitte** [comment]
Hi @kyleniemeyer,
is it possible to update the software version submitted to v0.2.2? I would like to publish v0.2.2 within the next days as some bugs in the code and the documentation have been fixed in the meantime. Thank you very much!
Best regards

**Comment by kyleniemeyer** [comment]
Hey @fwitte, sure thing. Feel free to update the code and then ping me here. "Fortunately" I'm behind on asking folks to review...

**Comment by fwitte** [comment]
Great, I updated to version 0.2.2 :). Have a nice weekend!

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arfon** [comment]
:wave: @kyleniemeyer - how are things going here? Are you ready to start looking for reviewers for this submission?

**Comment by arosen93** [comment]
Hi @kyleniemeyer. I'd be happy to review this work.

**Comment by kyleniemeyer** [comment]
@whedon add @arosen93 as reviewer

**Comment by whedon** [comment]
OK, @arosen93 is now a reviewer

**Comment by kyleniemeyer** [comment]
Thanks @arosen93! I need to find at least one additional reviewer, and then I'll formally start the review.

**Comment by corentin-dev** [comment]
Dear Kyle,
I accept to review this submission.
Best regards,
Corentin

Le 13 avr. 2020 à 18:45, à 18:45, Kyle Niemeyer <notifications@github.com> a écrit:

**Comment by fwitte** [comment]
Looking forward to your review, @corentin-dev and @arosen93.
@kyleniemeyer, can you update the version number to 0.2.2? I plan to publish 0.3.0 shortly, so maybe even to 0.3.0 if it is ready within the next days?
Best regards
Francesco

**Comment by kyleniemeyer** [comment]
@whedon set version as 0.2.2

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kyleniemeyer** [comment]
@whedon set 0.2.2 as version

**Comment by whedon** [comment]
OK. 0.2.2 is the version.

**Comment by kyleniemeyer** [comment]
@whedon add @corentin-dev as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kyleniemeyer** [comment]
@whedon add @corentin-dev as reviewer

**Comment by whedon** [comment]
OK, @corentin-dev is now a reviewer

**Comment by fwitte** [comment]
Hi guys,
I just wanted to let you know, how I plan my workflow for the review process:

- For any issues/proposals/... regarding the software, I will open a PR over at https://github.com/oemof/tespy and merge the changes into the dev branch.
- The documentation of the dev branch automatically updates and can be found at https://tespy.readthedocs.io/en/dev/index.html. I also append a short overview of the changes applied in every PR (https://tespy.readthedocs.io/en/dev/whats_new.html).
- If the review is successful, I will then merge the dev branch into the master branch and publish the version 0.3.0.

If you have any objections or suggestions, just let me know :). Thank you and stay healthy!
Best regards
Francesco

**Comment by arosen93** [comment]
Great! Thanks for the info. I've got a busy week but will be starting my review this weekend. You'll likely see some activity from me then.

Cheers! 
Andrew

**Comment by fwitte** [comment]
Great, do not worry, I did/do not want to rush you.

Btw.: If you are testing code etc. you may want to install the dev version instead of the PyPi version (which is version 0.2.2) as the dev version already has some commits since 0.2.2 and breaks with the 0.2.x API. Just in case you do not know (you'll probably know :)), here is the workflow I usually go with:

0. If you have TESPy already installed remove it: `pip uninstall tespy`.
1. Clone the github repo using ssh `git@github.com:oemof/tespy.git` or using `https://github.com/oemof/tespy.git`
2. In a console activate your environment, navigate to the github clone and install manually `pip install -e ./`
3. If changes to dev are beeing made, you installation automatically updates if you go to your github folder and pull from origin `git pull origin dev`

Have a nice week, cheers!
Francesco

**Comment by arosen93** [comment]
@kyleniemeyer -- will the review be opened soon for TESPy?

**Comment by kyleniemeyer** [comment]
@arosen93 yes, thanks for the reminder—I was just waiting to see if any of the other folks I had pinged responded.

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2178.
