### ISSUE TITLE
[PRE REVIEW]: SaffronTree: Fast, reference-free pseudo-phylogenomic trees from reads or contigs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#211]
**Submitting author:** @andrewjpage (<a href="http://orcid.org/0000-0001-6919-6062">Andrew Page</a>)
**Repository:** <a href="https://github.com/sanger-pathogens/saffrontree" target ="_blank">https://github.com/sanger-pathogens/saffrontree</a>
**Version:** v0.1.2
**Editor:** @biorelated
**Reviewer:** @brainstorm

**What this issue is for**

Thanks for submitting your paper to JOSS @andrewjpage. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @biorelated @brainstorm - would you be willing to edit this submission for JOSS?

**Comment by brainstorm** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by brainstorm** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by brainstorm** [comment]
@whedon start review magic-word=bananas

**Comment by arfon** [comment]
:wave: @brainstorm - you need to assign a review and an editor first. If you're willing to edit this then do:

```
@whedon assign @brainstorm as editor
```

**Comment by brainstorm** [comment]
@whedon assign @brainstorm as editor

**Comment by whedon** [comment]
OK, the editor is @brainstorm

**Comment by arfon** [comment]
...then do the same for a reviewer:

```
@whedon assign @reviewername as reviewer
```

**Comment by brainstorm** [comment]
@whedon assign @brainstorm as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @brainstorm

**Comment by arfon** [comment]
...also, we shouldn't have the reviewer and editor be the same person so if you would like to review this one then we'll need to find another editor 😁

**Comment by biorelated** [comment]
I am  happy to edit this

**Comment by biorelated** [comment]
@whedon assign @biorelated as editor

**Comment by whedon** [comment]
OK, the editor is @biorelated

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/243. Feel free to close this issue now!
