### ISSUE TITLE
[PRE REVIEW]: Autorank: A Python package for automated ranking of classifiers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2110]
**Submitting author:** @sherbold (<a href="http://orcid.org/0000-0001-9765-2803">Steffen Herbold</a>)
**Repository:** <a href="https://github.com/sherbold/autorank" target ="_blank">https://github.com/sherbold/autorank</a>
**Version:** 1.0.0
**Editor:** @arfon
**Reviewers:** @JonathanReardon, @ejhigson
**Managing EiC:** Kyle Niemeyer

**Author instructions**

Thanks for submitting your paper to JOSS @sherbold. **Currently, there isn't an JOSS editor assigned** to your paper.

@sherbold if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (274.7 files/s, 45420.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           7            182            190           1168
Markdown                         2             57              0            265
YAML                             2              7             20             72
TeX                              1              1              0             22
-------------------------------------------------------------------------------
SUM:                            12            247            210           1527
-------------------------------------------------------------------------------


Statistical information for the repository '2110' was gathered on 2020/02/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
sherbold                        40          2887           1347          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
sherbold                   1540           53.3          0.9                4.16
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02110/joss.02110/10.21105.joss.02110.pdf)

**Comment by kyleniemeyer** [comment]
@whedon invite @lorenanicole as editor

**Comment by whedon** [comment]
@lorenanicole has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
Hi @lorenanicole, I think this may be your first editorial request—feel free to reach out with any questions!

**Comment by lorenanicole** [comment]
Greetings @kyleniemeyer ! I am traveling tomorrow to arrive early to be onsite for work next week! In terms of time expectations, I presume starting to work on this next weekish is agreeable?

**Comment by kyleniemeyer** [comment]
@lorenanicole sure thing, a few days delay isn't an issue (especially over the weekend)

**Comment by kyleniemeyer** [comment]
@whedon assign @lorenanicole as editor

**Comment by whedon** [comment]
OK, the editor is @lorenanicole

**Comment by danielskatz** [comment]
👋 @lorenanicole - how are you doing on this?

**Comment by lorenanicole** [comment]
Hi folks! I apologize, some Python Software Foundation commitments are sending me scrambling due to covid19. Should be freed up this weekend!

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by sherbold** [comment]
Thanks for the info. I would be happy with any progress, but understand waiting as well. My own workload is also quite heavily impacted already.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
> Thanks for the info. I would be happy with any progress, but understand waiting as well. My own workload is also quite heavily impacted already.

@sherbold - I'm going to take over the handling of this submission for now. 
When you have a chance, could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

Thanks!

**Comment by sherbold** [comment]
Thanks for taking over. I just went from the top and looked for reviewers that have statistics + something related to ML or data analysis as domain, Python as preferred language and no active reviews. Here are eight candidates, but I only went half-way through the list and could look for if they do not have time.  

- betatim
- tupi
- tianxzhu
- dirmeier
- adavidzh
- JonathanReardon
- ejolly
- bahung
- mskwark

**Comment by arfon** [comment]
@JonathanReardon @bahung @ejolly - 
would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The package we would ask you to review is [_Autorank: A Python package for automated ranking of classifiers_](https://github.com/sherbold/autorank) and there is a [short associated paper](https://github.com/openjournals/joss-papers/blob/joss.02110/joss.02110/10.21105.joss.02110.pdf) to read too.

**Comment by ejhigson** [comment]
@sherbold @arfon - I would be happy to review this submission for you if you would like?

**Comment by JonathanReardon** [comment]
Yes I would be happy to review this submission, thanks

**Comment by JonathanReardon** [comment]
@arfon @sherbold Yes I would be happy to review this submission, thanks

**Comment by arfon** [comment]
Thanks @ejhigson and @JonathanReardon!

**Comment by arfon** [comment]
@whedon add @JonathanReardon as reviewer

**Comment by whedon** [comment]
OK, @JonathanReardon is now a reviewer

**Comment by arfon** [comment]
@whedon add @ejhigson as reviewer

**Comment by whedon** [comment]
OK, @ejhigson is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2173.

**Comment by arfon** [comment]
@JonathanReardon, @ejhigson - thanks for agreeing to review this submission - see you over in #2173 where the actual review will take place.
