### ISSUE TITLE
[REVIEW]: BGGM: Bayesian Gaussian Graphical Models in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2111]
**Submitting author:** @donaldRwilliams (<a href="http://orcid.org/0000-0001-6735-8785">Donald Williams </a>)
**Repository:** <a href="https://github.com/donaldRwilliams/BGGM" target ="_blank">https://github.com/donaldRwilliams/BGGM</a>
**Version:** 1.0.0
**Editor:** @akeshavan
**Reviewer:** @jayrobwilliams, @paulgovan
**Archive:** <a href="https://doi.org/10.5281/zenodo.3954503" target="_blank">10.5281/zenodo.3954503</a>

## Status

[![status](https://joss.theoj.org/papers/4ecb84c5b3b2a2b5da46be4e0700502f/status.svg)](https://joss.theoj.org/papers/4ecb84c5b3b2a2b5da46be4e0700502f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4ecb84c5b3b2a2b5da46be4e0700502f"><img src="https://joss.theoj.org/papers/4ecb84c5b3b2a2b5da46be4e0700502f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4ecb84c5b3b2a2b5da46be4e0700502f/status.svg)](https://joss.theoj.org/papers/4ecb84c5b3b2a2b5da46be4e0700502f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/donaldRwilliams/BGGM" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jayrobwilliams & @paulgovan, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @akeshavan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/donaldRwilliams/BGGM">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@donaldRwilliams) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/donaldRwilliams/BGGM">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@donaldRwilliams) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jayrobwilliams, @paulgovan it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2111 with the following error: 

 Can't find any papers to compile :-(

**Comment by akeshavan** [comment]
hi @donaldRwilliams -- could you take a look at your repo and put the paper.md file in the root of your repository, so that we can generate a PDF automatically ?

**Comment by donaldRwilliams** [comment]
Hi:
Apologies on the delay. I added the paper.md file to the root of the repository.

**Comment by paulgovan** [comment]
There are several issues with this submission. Please reference the links above.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by jayrobwilliams** [comment]
I've completed my initial review. I largely agree with @paulgovan, but have noted a couple of other issues on the package repo. I'm also going to attempt to compile the paper as it's currently missing.

**Comment by jayrobwilliams** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02111/joss.02111/10.21105.joss.02111.pdf)

**Comment by arfon** [comment]
:wave: @donaldRwilliams, just a friendly check-in to see how things are going with your responses to the review feedback here?

**Comment by donaldRwilliams** [comment]
@arfon Hi. thank you for this check in. We are currently working on updating the documentation per the reviewers suggestions to include actual examples of hypotheses one can test.

**Comment by donaldRwilliams** [comment]
@arfon @jayrobwilliams @paulgovan 

I wanted to check in once more. We had received reviews for one of the methods that is implemented in the package (generally favorable) and we just finished that up. We also decided to follow the suggestions of @paulgovan to (1) make the paper more of a high level summary; and (2) also include real world examples (this was also suggested in the review).

Anyhow, we expect to have this completed by the end of next week.

Thanks !

**Comment by arfon** [comment]
:wave: @donaldRwilliams - just a friendly check in to see if you've managed to make these updates yet. JOSS is now reopen for submissions so we're actively trying to wrap up existing reviews.

**Comment by donaldRwilliams** [comment]
Hi:
Sounds good. Just now finished making the rather large changes to the documentation, README, etc. Will have the paper updated by end of the week

**Comment by donaldRwilliams** [comment]
@arfon 
We updated the paper. Note the package has undergone extensive changes, including rewriting all the algorithms in `c++`, adding support for binary, ordinal, and mixed data, linked to Travis, etc.

As for the reviewer comments, we extensively rewrote the documentation to include many examples, added to Travis, and most notably shortened the paper to be a "high-level" overview.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02111/joss.02111/10.21105.joss.02111.pdf)

**Comment by arfon** [comment]
:+1: thanks for the update @donaldRwilliams!

@jayrobwilliams, @paulgovan - when you're ready, it sounds like this submission is ready for you both to take another look.

**Comment by jayrobwilliams** [comment]
@arfon doing so now

**Comment by donaldRwilliams** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02111/joss.02111/10.21105.joss.02111.pdf)

**Comment by donaldRwilliams** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02111/joss.02111/10.21105.joss.02111.pdf)

**Comment by arfon** [comment]
@donaldRwilliams - did you latest updates address many of the comments opened by the reviewers (e.g. https://github.com/donaldRwilliams/BGGM/issues/3, https://github.com/donaldRwilliams/BGGM/issues/4, https://github.com/donaldRwilliams/BGGM/issues/6)? If so, perhaps you could leave comments on those issues (and close them if appropriate) to help us all understand what changes have been made?

**Comment by donaldRwilliams** [comment]
@arfon I think I have indeed made all the changes, besides the "statement of need". I am working on that now..

**Comment by donaldRwilliams** [comment]
@arfon I left comments on those issues and also closed them (I think this was fine, but can always re open if needed).

**Comment by jayrobwilliams** [comment]
@arfon @akeshavan I have completed my review and recommend this paper for publication.

**Comment by arfon** [comment]
:+1: thanks @jayrobwilliams! @paulgovan - when do you think you might be able to come and take another look at this?

**Comment by arfon** [comment]
Just a quick note that I emailed @paulgovan just now to see when they might be able to complete their review.

**Comment by paulgovan** [comment]
Sorry for the delay. I see several issues related to the paper that are still open. My thought is that these should be closed before moving forward with publication. @arfon @akeshavan do you agree?

**Comment by arfon** [comment]
> Sorry for the delay. I see several issues related to the paper that are still open. My thought is that these should be closed before moving forward with publication. @arfon @akeshavan do you agree?

Yes, I agree, although it looks like almost all of them have been addressed and that @donaldRwilliams might just need to close those issues. The one I see that is still unresolved is https://github.com/donaldRwilliams/BGGM/issues/10 - could you confirm what is happening there @donaldRwilliams?

**Comment by donaldRwilliams** [comment]
@arfon I closed this issue, as it was addressed sometime ago.

**Comment by arfon** [comment]
@donaldRwilliams - to help our reviewers (and me), could you state on the issues that are still open as part of this review what actions you have taken and (if appropriate) close them. The issues I still see open here are: https://github.com/donaldRwilliams/BGGM/issues/3 https://github.com/donaldRwilliams/BGGM/issues/7 https://github.com/donaldRwilliams/BGGM/issues/8

Thanks!

**Comment by donaldRwilliams** [comment]
@arfon I went through and noted the changes. I think we followed the advice in the reviewers in all cases, and we noted the changes accordingly in the issue. They are all now closed as well.

**Comment by arfon** [comment]
> @arfon I went through and noted the changes. I think we followed the advice in the reviewers in all cases, and we noted the changes accordingly in the issue. They are all now closed as well.

Excellent, thanks @donaldRwilliams 

@paulgovan - could ask you to take one more quick look at this (and update your checklist accordingly) now that the author has resolved all of the outstanding issues? 🙏

**Comment by paulgovan** [comment]
@arfon, @akeshavan, sure thing. I've reviewed the paper again and also recommend moving forward with publication. These are great improvements.

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3758/s13423-016-1221-4 is OK
- 10.1177/0013164416669201 is OK
- 10.31234/OSF.IO/X8DPR is OK
- 10.31234/osf.io/ypxd8 is OK
- 10.1080/00031305.2018.1549100 is OK
- 10.1214/17-BA1092 is OK

MISSING DOIs

- https://doi.org/10.1016/j.csda.2007.09.008 may be missing for title: Bayesian model determination for multivariate ordinal and binary data
- https://doi.org/10.1037/abn0000446 may be missing for title: What do centrality measures measure in psychological networks?
- https://doi.org/10.31234/osf.io/pg4mf may be missing for title: Problems with centrality measures in psychopathology symptom networks: Why network psychometrics cannot escape psychometric theory
- https://doi.org/10.1214/009053606000000821 may be missing for title: Can one estimate the conditional distribution of post-model-selection estimators?
- https://doi.org/10.31234/osf.io/yt386 may be missing for title: Comparing Gaussian graphical models with the posterior predictive distribution and Bayesian model selection.
- https://doi.org/10.1214/07-aoas107 may be missing for title: Extending the rank likelihood for semiparametric copula estimation
- https://doi.org/10.31219/osf.io/ksfyr may be missing for title: The Bayesian New Statistics: Hypothesis testing, estimation, meta-analysis, and power analysis from a Bayesian perspective
- https://doi.org/10.1037/met0000201 may be missing for title: A tutorial on testing hypotheses using the Bayes factor.
- https://doi.org/10.1080/10618600.2012.679239 may be missing for title: Efficient Bayesian inference for multivariate probit models with sparse inverse correlation matrices
- https://doi.org/10.1080/01621459.1993.10476321 may be missing for title: Bayesian analysis of binary and polychotomous response data
- https://doi.org/10.1007/bf00162520 may be missing for title: Accelerating Monte Carlo Markov chain convergence for cumulative-link generalized linear models
- https://doi.org/10.1191/1471082x04st063oa may be missing for title: MCMC model determination for discrete graphical models
- https://doi.org/10.1080/01621459.1988.10478640 may be missing for title: Evaluating logistic models for large contingency tables
- https://doi.org/10.21236/ada241408 may be missing for title: Model selection and accounting for model uncertainty in graphical models using Occam’s window
- https://doi.org/10.1198/004017008000000064 may be missing for title: Bayesian inference for multivariate ordinal data using parameter expansion
- https://doi.org/10.21105/joss.00026 may be missing for title: Armadillo: a template-based C++ library for linear algebra
- https://doi.org/10.31234/osf.io/p69m7 may be missing for title: A network analysis of DSM-5 posttraumatic stress disorder symptoms and correlates in US military veterans
- https://doi.org/10.1214/aos/1176346785 may be missing for title: Bayesianly justifiable and relevant frequency calculations for the applied statistician
- https://doi.org/10.31234/osf.io/zw7pf may be missing for title: On Formalizing Theoretical Expectations: Bayesian Testing of Central Structures in Psychological Networks
- https://doi.org/10.3758/s13428-017-0910-x may be missing for title: How well do network models predict observations? On the importance of predictability in network models
- https://doi.org/10.1080/00273171.2019.1614898 may be missing for title: Bridge centrality: A network approach to understanding comorbidity
- https://doi.org/10.1214/13-ejs854 may be missing for title: Two simple examples for understanding posterior p-values whose distributions are far from uniform
- https://doi.org/10.1109/vetecs.2005.1543265 may be missing for title: Correlation matrix distance, a meaningful measure for evaluation of non-stationary MIMO channels
- https://doi.org/10.18637/jss.v048.i04 may be missing for title: qgraph: Network visualizations of relationships in psychometric data
- https://doi.org/10.18637/jss.v089.i03 may be missing for title: BDgraph: An R package for Bayesian structure learning in graphical models
- https://doi.org/10.3389/fpsyg.2019.01050 may be missing for title: Using a Gaussian graphical model to explore relationships between items and variables in environmental psychology research
- https://doi.org/10.1080/00273171.2020.1716673 may be missing for title: Use of Composites in Analysis of Individual Time Series: Implications for Person-Specific Dynamic Parameters
- https://doi.org/10.31234/osf.io/4kfjp may be missing for title: Bayesian Multivariate Mixed-Effects Location Scale Modeling of Longitudinal Relations among Affective Traits, States, and Physical Activity
- https://doi.org/10.1063/1.4870402 may be missing for title: A Gaussian graphical model approach to climate networks
- https://doi.org/10.1186/1752-0509-3-55 may be missing for title: A graphical model approach for inferring large-scale networks integrating gene expression and genetic polymorphism
- https://doi.org/10.1007/s41109-020-0251-z may be missing for title: Partial correlation financial networks
- https://doi.org/10.1093/biostatistics/kxt005 may be missing for title: Sparse time series chain graphical models for reconstructing genetic networks

INVALID DOIs

- 10.1.1.142.9951 is INVALID
```

**Comment by arfon** [comment]
@donaldRwilliams - could you take a look at the DOIs suggested by Whedon above and add them to your BibTeX file if they are correct.

**Comment by donaldRwilliams** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3758/s13423-016-1221-4 is OK
- 10.1177/0013164416669201 is OK
- 10.31234/OSF.IO/X8DPR is OK
- 10.31234/osf.io/ypxd8 is OK
- 10.1080/00031305.2018.1549100 is OK
- 10.1016/j.csda.2007.09.008 is OK
- 10.1037/abn0000446 is OK
- 10.1080/00273171.2019.1640103 is OK
- 10.1214/009053606000000821 is OK
- 10.1037/met0000254 is OK
- 10.1214/17-BA1092 is OK
- 10.1214/07-AOAS107 is OK
- 10.3758/s13423-016-1221-4 is OK
- 10.1037/met0000201 is OK
- 10.1080/10618600.2012.679239 is OK
- 10.1080/01621459.1993.10476321 is OK
- 10.1007/bf00162520 is OK
- 10.1191/1471082x04st063oa is OK
- 10.1080/01621459.1988.10478640 is OK
- 10.21236/ada241408 is OK
- 10.1198/004017008000000064 is OK
- 10.21105/joss.00026 is OK
- 10.31234/osf.io/p69m7 is OK
- 10.1214/aos/1176346785 is OK
- 10.31234/osf.io/zw7pf is OK
- 10.3758/s13428-017-0910-x is OK
- 10.1214/13-ejs854 is OK
- 10.1109/vetecs.2005.1543265 is OK
- 10.18637/jss.v048.i04 is OK
- 10.18637/jss.v089.i03 is OK
- fpsyg.2019.01050 is OK
- 10.1080/00273171.2020.1716673 is OK
- 10.31234/osf.io/4kfjp is OK
- 10.1063/1.4870402 is OK
- 10.1186/1752-0509-3-55 is OK
- 10.1007/s41109-020-0251-z is OK
- 10.1093/biostatistics/kxt005 is OK

MISSING DOIs

- None

INVALID DOIs

- 0.1080/00273171.2019.1614898 is INVALID
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3758/s13423-016-1221-4 is OK
- 10.1177/0013164416669201 is OK
- 10.31234/OSF.IO/X8DPR is OK
- 10.31234/osf.io/ypxd8 is OK
- 10.1080/00031305.2018.1549100 is OK
- 10.1016/j.csda.2007.09.008 is OK
- 10.1037/abn0000446 is OK
- 10.1080/00273171.2019.1640103 is OK
- 10.1214/009053606000000821 is OK
- 10.1037/met0000254 is OK
- 10.1214/17-BA1092 is OK
- 10.1214/07-AOAS107 is OK
- 10.3758/s13423-016-1221-4 is OK
- 10.1037/met0000201 is OK
- 10.1080/10618600.2012.679239 is OK
- 10.1080/01621459.1993.10476321 is OK
- 10.1007/bf00162520 is OK
- 10.1191/1471082x04st063oa is OK
- 10.1080/01621459.1988.10478640 is OK
- 10.21236/ada241408 is OK
- 10.1198/004017008000000064 is OK
- 10.21105/joss.00026 is OK
- 10.31234/osf.io/p69m7 is OK
- 10.1214/aos/1176346785 is OK
- 10.31234/osf.io/zw7pf is OK
- 10.3758/s13428-017-0910-x is OK
- 10.1080/00273171.2019.1614898 is OK
- 10.1214/13-ejs854 is OK
- 10.1109/vetecs.2005.1543265 is OK
- 10.18637/jss.v048.i04 is OK
- 10.18637/jss.v089.i03 is OK
- fpsyg.2019.01050 is OK
- 10.1080/00273171.2020.1716673 is OK
- 10.31234/osf.io/4kfjp is OK
- 10.1063/1.4870402 is OK
- 10.1186/1752-0509-3-55 is OK
- 10.1007/s41109-020-0251-z is OK
- 10.1093/biostatistics/kxt005 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by donaldRwilliams** [comment]
@arfon I updated the .bib file. Quite nice that the dois were all provided. Thanks !

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02111/joss.02111/10.21105.joss.02111.pdf)

**Comment by arfon** [comment]
donaldRwilliams - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by donaldRwilliams** [comment]
@arfon I uploaded the new release of the software. 

Here is the doi:
10.5281/zenodo.3954503

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3954503 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3954503" target="_blank">10.5281/zenodo.3954503</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3758/s13423-016-1221-4 is OK
- 10.1177/0013164416669201 is OK
- 10.31234/OSF.IO/X8DPR is OK
- 10.31234/osf.io/ypxd8 is OK
- 10.1080/00031305.2018.1549100 is OK
- 10.1016/j.csda.2007.09.008 is OK
- 10.1037/abn0000446 is OK
- 10.1080/00273171.2019.1640103 is OK
- 10.1214/009053606000000821 is OK
- 10.1037/met0000254 is OK
- 10.1214/17-BA1092 is OK
- 10.1214/07-AOAS107 is OK
- 10.3758/s13423-016-1221-4 is OK
- 10.1037/met0000201 is OK
- 10.1080/10618600.2012.679239 is OK
- 10.1080/01621459.1993.10476321 is OK
- 10.1007/bf00162520 is OK
- 10.1191/1471082x04st063oa is OK
- 10.1080/01621459.1988.10478640 is OK
- 10.21236/ada241408 is OK
- 10.1198/004017008000000064 is OK
- 10.21105/joss.00026 is OK
- 10.31234/osf.io/p69m7 is OK
- 10.1214/aos/1176346785 is OK
- 10.31234/osf.io/zw7pf is OK
- 10.3758/s13428-017-0910-x is OK
- 10.1080/00273171.2019.1614898 is OK
- 10.1214/13-ejs854 is OK
- 10.1109/vetecs.2005.1543265 is OK
- 10.18637/jss.v048.i04 is OK
- 10.18637/jss.v089.i03 is OK
- fpsyg.2019.01050 is OK
- 10.1080/00273171.2020.1716673 is OK
- 10.31234/osf.io/4kfjp is OK
- 10.1063/1.4870402 is OK
- 10.1186/1752-0509-3-55 is OK
- 10.1007/s41109-020-0251-z is OK
- 10.1093/biostatistics/kxt005 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1584

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1584, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1285593905178828800) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1585
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02111](https://doi.org/10.21105/joss.02111)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@jayrobwilliams, @paulgovan - many thank for your reviews here and to @akeshavan for editing this submission ✨ 

@donaldRwilliams - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02111/status.svg)](https://doi.org/10.21105/joss.02111)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02111">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02111/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02111/status.svg
   :target: https://doi.org/10.21105/joss.02111
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02111/status.svg)](https://doi.org/10.21105/joss.02111)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
