### ISSUE TITLE
[PRE REVIEW]: cgmquantify: A Python package for comprehensive analysis of interstitial glucose and glycemic variability from continuous glucose monitor data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2112]
**Submitting author:** @brinnaebent (<a href="http://orcid.org/0000-0002-7039-0177">Brinnae Bent</a>)
**Repository:** <a href="https://github.com/brinnaebent/cgmquantify" target ="_blank">https://github.com/brinnaebent/cgmquantify</a>
**Version:** v0.3
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**Author instructions**

Thanks for submitting your paper to JOSS @brinnaebent. **Currently, there isn't an JOSS editor assigned** to your paper.

@brinnaebent if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02112/joss.02112/10.21105.joss.02112.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/s0084-3741(09)79371-0 may be missing for title: Continuous Glucose Monitoring and Intensive Treatment of Type 1 Diabetes
- https://doi.org/10.1016/j.amjms.2018.09.010 may be missing for title: Glycemic Variability: How to Measure and Its Clinical Implication for  Type 2 Diabetes
- https://doi.org/10.1038/nrendo.2017.3 may be missing for title: Metrics for glycaemic control — from HbA1c to continuous glucose monitoring
- https://doi.org/10.1089/dia.2010.0247 may be missing for title: Normal reference range for mean tissue glucose and glycemic variability  derived from continuous glucose monitoring for subjects without diabetes in different ethnic groups
- https://doi.org/10.1371/journal.pone.0216851 may be missing for title: cgmanalysis: An R package for descriptive analysis of continuous glucose monitor data.
- https://doi.org/10.1093/bioinformatics/bty144 may be missing for title: CGManalyzer: An R package for analyzing continuous glucose monitoring studies
- https://doi.org/10.3414/me17-03-0001 may be missing for title: Single Subject (N-of-1) Research Design, Data Processing, and Personal Science
- https://doi.org/10.1089/dia.2011.0099 may be missing for title: Translating glucose variability metrics into the clinic via continuous glucose monitoring:  A graphical user interface for diabetes evaluation (CGM-GUIDE©)
- https://doi.org/10.1055/s-2007-979906 may be missing for title: ’J’-index. A new proposition of the assessment of current glucose control in diabetic patients
- https://doi.org/10.1177/1932296819826111 may be missing for title: Glycemic Variability: Risk Factors, Assessment, and Control

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi  @brinnaebent, thanks for your interest in JOSS. Before we get started, could you clarify: in terms of source code, I just see `__init__.py`, which has around 240 lines of code. Are there any other files that I am missing?

**Comment by brinnaebent** [comment]
@kyleniemeyer That is the source code, yes. The setup.py file is the only other file you may need to reference (formatted for PyPI). Thank you!

**Comment by brinnaebent** [comment]
Recommended reviewers (from list):
dvanic
jeremyklein
esadr

**Comment by labarba** [comment]
After a pre-review of your submission, and an assessment by the editorial board at large, we find that it does not meet our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). In particular, while the software seems useful, it falls under the 'Minor utility' category, and we therefore decided not to put it through review. 

Our eligibility criterion is: 

> “The software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better”

Thank you for considering JOSS as a venue for your software, and I hope you'll submit other software with research application in the future.

**Comment by labarba** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by brinnaebent** [comment]
Good afternoon @labarba . Thank you for your comments. Can you elaborate on this being in the 'minor utility' category? Diabetes and prediabetes affect 1/3 of the US population, there are over 700k diabetes publications indexed in PubMed, and yet there is not a standard package with metrics summarizing glucose and glucose variability in the most utilized programming language, Python. The metrics provided in this package include clinically validated metrics across multiple studies in addition to novel metrics that give a more complete picture of glucose health. Could you provide more information into why this is considered 'minor utility'? Thank you very much.
