### ISSUE TITLE
[PRE REVIEW]: BiRank: Fast and Flexible Ranking on Bipartite Networks with R and Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2113]
**Submitting author:** @yangkcatiu (<a href="http://orcid.org/0000-0003-4627-9273">Kai-Cheng Yang</a>)
**Repository:** <a href="https://github.com/BrianAronson/birankr" target ="_blank">https://github.com/BrianAronson/birankr</a>
**Version:** v0.1.1
**Editor:** @drvinceknight
**Reviewers:** @gvegayon, @nikoleta-v3
**Managing EiC:** Kyle Niemeyer

**Author instructions**

Thanks for submitting your paper to JOSS @yangkcatiu. **Currently, there isn't an JOSS editor assigned** to your paper.

@yangkcatiu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (296.6 files/s, 25295.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               19             76            345            729
Markdown                         9            162              0            473
Python                           3             83            128            274
TeX                              1             11              0            128
Jupyter Notebook                 1              0            423             21
Rmd                              1             12             25             10
-------------------------------------------------------------------------------
SUM:                            34            344            921           1635
-------------------------------------------------------------------------------


Statistical information for the repository '2113' was gathered on 2020/02/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Kaicheng Yang                    1            56              1            9.68
yangkc                          25           481             51           90.32

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Kaicheng(Kevin) Yang        485          100.0          0.2                8.66
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/TKDE.2016.2611584 is OK
- 10.1103/PhysRevE.76.046115 is OK
- 10.1145/324133.324140 is OK
- 10.1371/journal.pone.0112022 is OK
- 10.1145/1557019.1557051 is OK
- 10.1109/WI-IAT.2011.60 is OK
- 10.1145/1291233.1291378 is OK
- 10.1103/PhysRevE.78.016108 is OK
- 10.1038/nmeth.2728 is OK

MISSING DOIs

- https://doi.org/10.1177/000312240406900204 may be missing for title: The structure of a social science collaboration network: Disciplinary cohesion from 1963 to 1999

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02113/joss.02113/10.21105.joss.02113.pdf)

**Comment by kyleniemeyer** [comment]
@whedon invite @drvinceknight as editor

**Comment by whedon** [comment]
@drvinceknight has been invited to edit this submission.

**Comment by yangkcatiu** [comment]
Suggestions for potential reviewers:

ati-ozgur
rodogi
sara-02
szhorvat
MatthewSmith430
gvegayon
camillescott
Nick-gauthier

**Comment by yangkcatiu** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by yangkcatiu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/TKDE.2016.2611584 is OK
- 10.1103/PhysRevE.76.046115 is OK
- 10.1145/324133.324140 is OK
- 10.1371/journal.pone.0112022 is OK
- 10.1145/1557019.1557051 is OK
- 10.1109/WI-IAT.2011.60 is OK
- 10.1145/1291233.1291378 is OK
- 10.1103/PhysRevE.78.016108 is OK
- 10.1038/nmeth.2728 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by drvinceknight** [comment]
@whedon assign @drvinceknight as editor

**Comment by whedon** [comment]
OK, the editor is @drvinceknight

**Comment by drvinceknight** [comment]
@ati-ozgur @camillescott @Nick-gauthier would you be able to review this software paper for JOSS? It's an interesting piece of graph theory work that is implemented in two languages both R and Python. 

If you have not reviewed for JOSS before, you can find information about the process here https://openjournals.readthedocs.io/en/latest/reviewer_guidelines.html and I'd be happy to answer any questions you may have.

**Comment by nick-gauthier** [comment]
Sorry, I won't have time this month to give this a thorough review.

**Comment by drvinceknight** [comment]
I understand, thank you for getting back to me @nick-gauthier :+1:

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arfon** [comment]
:wave: @drvinceknight, just a friendly check-in to see if you think you might be able to start looking for reviewers sometime soon?

**Comment by yangkcatiu** [comment]
👋 @drvinceknight @arfon We hope everything is alright! We understand this is a hard time for everyone and everything moves slower. It's just that we are preparing a project update for the funding agency and we hope to push this paper forward a little bit before the deadline.

**Comment by arfon** [comment]
:wave: @rodogi @szhorvat @gvegayon - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by szhorvat** [comment]
@arfon I'm still behind with a review for JOSS, which turned out to be more work than expected, so I cannot formally commit this time. It looks interesting though, so if time permits, I might post a few comments in the review thread.

**Comment by arfon** [comment]
No worries @szhorvat - thanks for the quick response (and apologies for not checking first to see if you were already actively reviewing for us).

**Comment by szhorvat** [comment]
> and apologies for not checking first to see if you were already actively reviewing for us

I think it's okay to ask. We can always refuse, and as I said, it does look interesting.

**Comment by gvegayon** [comment]
Hi @arfon, I am a bit busy, but this is very interesting work. I'll be happy to review it.

**Comment by arfon** [comment]
:wave: @nick-gauthier - I realize you [declined to review](https://github.com/openjournals/joss-reviews/issues/2113#issuecomment-592161797) this submission a couple of months ago - any chance you might have some availability now? I totally understand if this is not the case :-)

**Comment by rodogi** [comment]
Hey @arfon! Thanks for the consideration,  but unfortunately I will be too busy this month to handle the review.

**Comment by drvinceknight** [comment]
Hi @arfon and @yangkcatiu I'm really sorry it's taking me a long time: struggling with child care / work so joss has suffered I'm afraid. My students are submitting a big piece of work on Friday so until then I'm really swamped but I **will** have time to give this submission the attention it deserves from next week. Sincere apologies.

**Comment by yangkcatiu** [comment]
@drvinceknight no need to apologize, we totally understand the situation and really appreciate it!

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02113/joss.02113/10.21105.joss.02113.pdf)

**Comment by drvinceknight** [comment]
> Hi @arfon, I am a bit busy, but this is very interesting work. I'll be happy to review it.

Hi @gvegayon hopefully you're still happy to review this work :)

**Comment by drvinceknight** [comment]
@whedon assign @gvegayon as reviewer

**Comment by whedon** [comment]
OK, @gvegayon is now a reviewer

**Comment by drvinceknight** [comment]
@camillescott would you be able to review this paper for JOSS? Your indicated research interests include graph theory so I think you will hopefully find it interesting.

**Comment by drvinceknight** [comment]
@ati-ozgur would you be able to review this paper for JOSS? You also indicated algorithms and network science as your interests so I hope you'd find the paper of interest :)

**Comment by arfon** [comment]
:wave: @elplatt - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by drvinceknight** [comment]
@whedon add @nikoleta-v3 as reviewer

**Comment by whedon** [comment]
OK, @nikoleta-v3 is now a reviewer

**Comment by drvinceknight** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2315.

**Comment by drvinceknight** [comment]
@nikoleta-v3 and @gvegayon thank you very much for agreeing to review this work. The review takes place on #2315, if you have any questions or if I can assist in any way let me know :+1:
