### ISSUE TITLE
[PRE REVIEW]: OpenOA: An Open-Source Codebase For Operational Analysis of Wind Farms

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2114]
**Submitting author:** @jordanperr (<a href="http://orcid.org/0000-0003-1571-1887">Jordan Perr-Sauer</a>)
**Repository:** <a href="https://github.com/NREL/OpenOA" target ="_blank">https://github.com/NREL/OpenOA</a>
**Version:** v1
**Editor:** @sjpfenninger
**Reviewers:** @gschivley
**Managing EiC:** Kyle Niemeyer

**Author instructions**

Thanks for submitting your paper to JOSS @jordanperr. **Currently, there isn't an JOSS editor assigned** to your paper.

@jordanperr if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.67 s (95.8 files/s, 17194.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          41           1439           1917           3055
Markdown                         4             96              0            330
Jupyter Notebook                 6              0           3724            195
reStructuredText                 7             99             83            189
JSON                             2             28              0            153
TeX                              1             12              0             91
DOS Batch                        1              8              1             27
YAML                             1              5              0             16
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                            64           1691           5731           4066
-------------------------------------------------------------------------------


Statistical information for the repository '2114' was gathered on 2020/02/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Caleb                            1             2              1            0.03
Jordan Perr-Sauer               37           867            689           14.69
Lee, Joseph                      4           249            133            3.61
Mike Optis                      32          1953           1011           27.98
Nathan Agarwal                   5            60             58            1.11
Optis                           14           312            143            4.30
Perr-Sauer, Jordan               1          4105              0           38.75
Sebastian Pfaffel                1            46              0            0.43
moptis                           1           249              2            2.37
nateagarwal                      2           627             38            6.28
sebastianpfaffel                 5            33             15            0.45

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jordan Perr-Sauer           676           78.0          8.2                6.21
Lee, Joseph                 225           90.4          9.8               25.33
Mike Optis                  973           49.8          4.6               15.83
Nathan Agarwal               27           45.0          2.8                0.00
Optis                       183           58.7          9.3               15.85
Perr-Sauer, Jordan         3669           89.4          0.0               13.95
nateagarwal                 626           99.8          0.2               13.26
sebastianpfaffel             32           97.0          2.9                6.25
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1088/1742-6596/1037/5/052021 is OK

MISSING DOIs

- https://doi.org/10.1088/1742-6596/1037/6/062009 may be missing for title: Understanding Biases in Pre-Construction Estimates

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon invite @sjpfenninger as editor

**Comment by whedon** [comment]
@sjpfenninger has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
Hey @sjpfenninger, this looks right up your alley!

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02114/joss.02114/10.21105.joss.02114.pdf)

**Comment by jordanperr** [comment]
Hi @kyleniemeyer and @sjpfenninger,

It looks like most of the Whedon checks were passed. Would it be preferable to swap out the URL for the DOI in reference "Understanding Biases in Pre-Construction Estimate"? It would be no trouble for me to do. I'll monitor this thread for any further questions or changes.

Thank you, and I look forward to your review.

**Comment by sjpfenninger** [comment]
@kyleniemeyer yes, happy to edit this

**Comment by sjpfenninger** [comment]
@whedon assign @sjpfenninger as editor

**Comment by whedon** [comment]
OK, the editor is @sjpfenninger

**Comment by sjpfenninger** [comment]
@jordanperr Yes the DOI would be preferred, thanks!

**Comment by jordanperr** [comment]
@sjpfenninger Where is the best place to push this update? Is there a pull request branch somewhere we can iterate in? I don't want to iterate on these changes in our master branch. Thanks.

**Comment by kyleniemeyer** [comment]
@jordanperr we can generate the PDF from a branch using this command:

`@whedon generate pdf from branch custom-branch-name`

**Comment by jordanperr** [comment]
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02114/joss.02114/10.21105.joss.02114.pdf)

**Comment by jordanperr** [comment]
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02114/joss.02114/10.21105.joss.02114.pdf)

**Comment by jordanperr** [comment]
@kyleniemeyer DOI has been added

**Comment by sjpfenninger** [comment]
@jordanperr thanks - meanwhile I've been working offline by email to contact potential reviewers, so hopefully we can start the review soon!

**Comment by jordanperr** [comment]
@sjpfenninger Sounds good. Let me know if there's anything I can do.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by jordanperr** [comment]
@sjpfenninger Hi Stefan, I hope all is well with you during these trying times. I'd like to know what kind of progress we should expect on this article over the next couple of weeks. I will be here to answer any questions or provide revisions. Thank you, and stay safe.

**Comment by sjpfenninger** [comment]
@jordanperr Thanks for asking. I am working offline to find reviewers. You are welcome to suggest reviewers here if you have any suitable ones in mind!

**Comment by sjpfenninger** [comment]
@whedon assign @coroa as reviewer

**Comment by whedon** [comment]
OK, @coroa is now a reviewer

**Comment by sjpfenninger** [comment]
@whedon assign @gschivley as reviewer

**Comment by whedon** [comment]
OK, @gschivley is now a reviewer

**Comment by sjpfenninger** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2171.

**Comment by sjpfenninger** [comment]
@coroa @gschivley thanks for agreeing to review, and we understand that things are likely to take longer given the current circumstances. Let's head over to #2171 for the actual review!
