### ISSUE TITLE
[PRE REVIEW]: niacin: A Python package for text data enrichment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2115]
**Submitting author:** @deniederhut (<a href="http://orcid.org/0000-0002-9995-4378">Dillon Niederhut</a>)
**Repository:** <a href="https://github.com/deniederhut/niacin" target ="_blank">https://github.com/deniederhut/niacin</a>
**Version:** 0.2.0
**Editor:** @oliviaguest
**Reviewers:** @BayesforDays, @sara-02
**Managing EiC:** Kyle Niemeyer

**Author instructions**

Thanks for submitting your paper to JOSS @deniederhut. **Currently, there isn't an JOSS editor assigned** to your paper.

@deniederhut if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.18653/v1/d19-1670 may be missing for title: EDA: Easy Data Augmentation Techniques for Boosting Performance on Text Classification Tasks
- https://doi.org/10.3390/info11020108 may be missing for title: fastai: A Layered API for Deep Learning
- https://doi.org/10.3115/v1/d14-1162 may be missing for title: GloVe: Global Vectors for Word Representation

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02115/joss.02115/10.21105.joss.02115.pdf)

**Comment by kyleniemeyer** [comment]
@whedon invite @oliviaguest as editor

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
Hi @oliviaguest, can you handle this one?

**Comment by oliviaguest** [comment]
@kyleniemeyer I can indeed! 

@deniederhut can you suggest some reviewers please? 😄

**Comment by oliviaguest** [comment]
Also @deniederhut is this a library for dealing with linguistic data or data in general? Sorry I am skimming and it looks like specifically for corpora of text but I am struggling to see it explicitly stated in the docs https://niacin.readthedocs.io/en/latest/? I might be missing something though, either way, please feel free (if you think it's useful) to link me to the right place so I can read more.

**Comment by kyleniemeyer** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by deniederhut** [comment]
😅 the intention was to also include algorithms for image data and timeseries, but I haven't had a chance to write any of that. Right now it is just text augmentation.

As for reviewers, I might suggest the following:
- rlskoeser
- adammichaelwood
- sara-02
- mbod

**Comment by oliviaguest** [comment]
> 😅 the intention was to also include algorithms for image data and timeseries, but I haven't had a chance to write any of that. Right now it is just text augmentation.

Thanks for clarifying. Can you make some edits to make this current state and plan clear, please?

**Comment by oliviaguest** [comment]
@deniederhut ☝️

**Comment by deniederhut** [comment]
Hey! I modified the titles of both the paper and the README last week per your request - you can see the [changes here](https://github.com/deniederhut/niacin/commit/5b5595a069d5233985e8e842353fcf3ca4af8561). 

The body of the paper already stated this focus explicitly:

> Here, we introduce niacin, a python library for performing a large set of commonly-used text transformations

Were there further changes you would like to see?

**Comment by oliviaguest** [comment]
Thank you! No changes for now — this is perfect. 😊

**Comment by oliviaguest** [comment]
@whedon add reviewer @BayesForDays

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by oliviaguest** [comment]
@whedon add @BayesforDays as reviewer

**Comment by whedon** [comment]
OK, @BayesforDays is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @sara-02 as reviewer

**Comment by whedon** [comment]
OK, @sara-02 is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2136.

**Comment by oliviaguest** [comment]
✨ @deniederhut, @sara-02, and @BayesForDays: Please go to https://github.com/openjournals/joss-reviews/issues/2136 where the review will actually take place! 😊
