### ISSUE TITLE
[REVIEW]: Chemiscope: interactive structure-property explorer for materials and molecules

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2117]
**Submitting author:** @luthaf (<a href="http://orcid.org/0000-0003-4824-6512">Guillaume Fraux</a>)
**Repository:** <a href="https://github.com/cosmo-epfl/chemiscope" target ="_blank">https://github.com/cosmo-epfl/chemiscope</a>
**Version:** 0.2.0
**Editor:** @cMadan
**Reviewer:** @kblin, @mkhorton
**Archive:** <a href="https://doi.org/10.5281/zenodo.3909400" target="_blank">10.5281/zenodo.3909400</a>

## Status

[![status](https://joss.theoj.org/papers/fd6f554ee0fbc5ae622a0b3853ff6306/status.svg)](https://joss.theoj.org/papers/fd6f554ee0fbc5ae622a0b3853ff6306)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fd6f554ee0fbc5ae622a0b3853ff6306"><img src="https://joss.theoj.org/papers/fd6f554ee0fbc5ae622a0b3853ff6306/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fd6f554ee0fbc5ae622a0b3853ff6306/status.svg)](https://joss.theoj.org/papers/fd6f554ee0fbc5ae622a0b3853ff6306)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/cosmo-epfl/chemiscope" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kblin & @mkhorton, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @cMadan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cosmo-epfl/chemiscope">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@luthaf) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cosmo-epfl/chemiscope">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@luthaf) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kblin, @mkhorton it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1073/pnas.1108486108 is OK
- 10.1103/physrevb.87.184115 is OK
- 10.1088/1367-2630/15/9/095003 is OK
- 10.1186/s13321-014-0041-7 is OK
- 10.1093/bioinformatics/btx760 is OK
- 10.1093/bioinformatics/btt270 is OK
- 10.1038/s41467-018-06972-x is OK
- 10.5281/zenodo.3541831 is OK
- 10.1039/c6cp00415f is OK
- 10.1186/s13321-017-0192-4 is OK
- 10.1039/c7sc04665k is OK
- 10.1016/j.commatsci.2019.02.040 is OK
- 10.1063/1.5090481 is OK
- 10.1103/physrevlett.98.146401 is OK
- 10.1021/ci300415d is OK
- 10.1038/sdata.2014.22 is OK
- 10.1103/physrevlett.104.136403 is OK
- 10.1162/089976698300017467 is OK
- 10.1002/anie.200603675 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02117/joss.02117/10.21105.joss.02117.pdf)

**Comment by mkhorton** [comment]
Hi @Luthaf, I'm trying the interactive version on chemiscope.org and the Jmol viewer doesn't seem to be showing anything, looks like it should be an easy fix:

<img width="1133" alt="Screen Shot 2020-02-24 at 1 29 32 PM" src="https://user-images.githubusercontent.com/2976580/75192778-cb93ba80-5709-11ea-90cd-a0cc5dcdeca2.png">

**Comment by Luthaf** [comment]
Thanks for the report @mkhorton, it should be fixed now. If not, feel free to open more issues on chemiscope repo!

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arfon** [comment]
:wave: @kblin & @mkhorton - just a friendly check-in to see how things are going with your reviews?

**Comment by Luthaf** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02117/joss.02117/10.21105.joss.02117.pdf)

**Comment by mkhorton** [comment]
Hi @arfon, I can't seem to check-off items on the review?

**Comment by arfon** [comment]
@whedon  re-invite @mkhorton as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon re-invite @mkhorton as reviewer

**Comment by whedon** [comment]
The reviewer already has a pending invite.

@mkhorton please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by arfon** [comment]
@mkhorton it looks like you need to accept the invitation to the repo? ☝️

**Comment by mkhorton** [comment]
@arfon ah, thanks -- I thought I'd accepted for a previous review. I found the link but it says invite has expired.

**Comment by arfon** [comment]
@whedon re-invite @mkhorton as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@mkhorton please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by arfon** [comment]
> @arfon ah, thanks -- I thought I'd accepted for a previous review. I found the link but it says invite has expired.

OK, could you try again now? Sorry about the disruption, it seems like GitHub expires repository invitations these days after a certain period.

**Comment by mkhorton** [comment]
Great, got it now. Thanks :)

**Comment by mkhorton** [comment]
Hi @Luthaf, first my sincere apologies in the delay in making significant progress on this review. The code looks excellent, very well structured, and fills a clear need (indeed, we work on similar problems ourselves, and it's been a common source of frustration that all these nice global similarity measures exist, but are pretty inaccessible to the average user).

I have two queries:

1. Are there any automated tests? I couldn't find any.

2. Could you improve the paragraph for people looking to contribute and/or where to find support, just a minor point.

**Comment by Luthaf** [comment]
> Are there any automated tests? I couldn't find any.

No, unfortunately, I could not find a nice way to do automated tests for web user interfaces. If you know of a good framework for this, I am interested. I'd like to add such tests at some point.

In the mean time, I have been using the example files (which you can get locally with `npm run  download-example-input`) to test the behaviour of the code on varied examples.

> Could you improve the paragraph for people looking to contribute and/or where to find support, just a minor point.

Sure!

**Comment by mkhorton** [comment]
>  If you know of a good framework for this, I am interested. I'd like to add such tests at some point.

Yes, there are many test frameworks available. It is a bit of a pain to write tests for web apps, but it's worth it. Even minimal tests that just check your server loads and displays a graph and molecule can be valuable if, for example, something like a dependency being updated breaks your app.

Some frameworks include [Jest](https://jestjs.io) for testing components, browser testing like [Selenium](https://www.selenium.dev) or visual diffing like [Percy](https://percy.io) (commercial).

Automated testing is part of the requirements for JOSS paper acceptance.

**Comment by Luthaf** [comment]
> Yes, there are many test frameworks available. It is a bit of a pain to write tests for web apps, but it's worth it. Even minimal tests that just check your server loads and displays a graph and molecule can be valuable if, for example, something like a dependency being updated breaks your app.
>
> Some frameworks include Jest for testing components, browser testing like Selenium or visual diffing like Percy (commercial).

Percy sounds interesting, but I would rather use something free and open source, even if the setup is a bit more complex. However I disagree that minimal tests are useful: when updating dependencies I will be manually checking that basics still work. IMO, more interesting tests would be workflow/user story tests (when I click on this element, this other element changes, and this modal opens); do you know a framework for that?

> Automated testing is part of the requirements for JOSS paper acceptance.

From JOSS [documentation](https://joss.readthedocs.io/en/latest/review_criteria.html#tests)

> Tests
>
>Authors are strongly encouraged to include an automated test suite covering the core functionality of their software.
>
>    Good: An automated test suite hooked up to an external service such as Travis-CI or similar
>    OK: Documented manual steps that can be followed to objectively check the expected functionality of the software (e.g., a sample input file to assert behavior)
>    Bad (not acceptable): No way for you the reviewer to objectively assess whether the software works

I hoped that chemiscope would fell in the OK category here, even if it is not in the Good one.

**Comment by mkhorton** [comment]
> I hoped that chemiscope would fell in the OK category here, even if it is not in the Good one.

Yes, I agree, on the OK criteria I can check it off.

In my role as a reviewer though, I do want to echo the JOSS guidelines and strongly encourage tests. Tests in JavaScript are definitely possible, and there are open source solutions ([Jest](https://jestjs.io) is fully open source). From my own past experience, writing web apps is a lot more brittle than other kinds of apps precisely because they tend to have very deep dependency trees and lots of small packages.

> when updating dependencies I will be manually checking that basics still work.

The intent here is for other contributors to the project too, and help them, help them know when they break things and how to add new features that don't conflict with requirements for the project. Tests help communicate your intent for what you want the code to do.

Your call though -- I agree that this meets the minimal requirements, so I won't hold up the review over it :)

**Comment by Luthaf** [comment]
I am already convinced by the usefulness of testing in general, and its availability in JavaScript projects (I used mocha/chai + karma + Travis running on node + 3 browsers in [another project of mine](https://github.com/chemfiles/chemfiles.js) to get >95% line coverage).

My pain point here is that this project does not tend itself to unit tests, and would require setting up more integrated, end-to-end testing. And I would like to have tests that are useful, and don't require changing them every time I tweak the placement of an element. So graphical diff would be interesting to have -- if I can find an open source version of it -- but not the end of the story. 

Anyway, I'll spend some more time looking for frameworks for such end-to-end testing!

**Comment by mkhorton** [comment]
Ok, that sounds reasonable. And I'm sure that you know the requirements of your project better than I do, so I did not mean to lecture on this point.

> And I would like to have tests that are useful, and don't require changing them every time I tweak the placement of an element. 

Hear you on this!

**Comment by Luthaf** [comment]
Hello @kblin 👋 , do you think you will have time to review this submission in the near future? We are submitting other papers using chemiscope, and we would like to be able to cite the JOSS paper in these. 

@cMadan, is there a way for us to get a "pre-reserved" DOI that will resolve to the chemiscope JOSS paper once it is accepted?

**Comment by arfon** [comment]
@Luthaf @cMadan the DOI for this paper will be: `10.21105/joss.02117`

**Comment by Luthaf** [comment]
Thanks a lot!

**Comment by mkhorton** [comment]
My review is complete, thanks everyone.

**Comment by kblin** [comment]
Hi, my apologies.
The paper is on my todo list for this week.

Cheers,
Kai

--
Kai Blin                                           kblin@biosustain.dtu.dk
Researcher / Scientific Software Engineer
DTU Biosustain                                     http://www.biosustain.dtu.dk/
Building 220, room 327
DK - 2800 Kgs. Lyngby
Denmark
mobile: +45 93511306                               twitter: @kaiblin

________________________________________

**Comment by kblin** [comment]
Sorry again for all the delays. I've just gotten started with the review. I take the latest version of the manuscript is the PDF from April 14?

**Comment by kblin** [comment]
I've found two minor issues during the review:
* When installing into a folder that that's not on the same filesystem as `/tmp`, downloading the example data fails. I've filed a bug: https://github.com/cosmo-epfl/chemiscope/issues/47
* Manuscript page 2, 2nd paragraph. Citation for Bartók, 2010 isn't resolved properly

**Comment by Luthaf** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02117/joss.02117/10.21105.joss.02117.pdf)

**Comment by kblin** [comment]
Both issues are fixed now, thanks.
@cMadan, I think all reviews are in now. Again my apologies for the delay.

**Comment by Luthaf** [comment]
We have fixed a few typos in the paper, so please @whedon generate pdf

**Comment by Luthaf** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02117/joss.02117/10.21105.joss.02117.pdf)

**Comment by Luthaf** [comment]
@cMadan, what is the next step here? I've seen we have to provide a zenodo DOI for a fixed release, is there anything else to do on our side?

**Comment by kthyng** [comment]
I can help out here as the rotating Associate Editor in Chief this week. @cMadan is able to partially work currently but not necessarily consistently.

It looks like the reviews are finished! Can I verify that the issue listed above is meant to be left open?

**Comment by Luthaf** [comment]
Do you mean https://github.com/cosmo-epfl/chemiscope/issues/21? I think so, the goal is to introduce automated testing to the code, in addition to current manual checking. It is not totally trivial to do, since the project is mostly a graphical interface, which is hard to unit test. 

We discussed this with @mkhorton starting https://github.com/openjournals/joss-reviews/issues/2117#issuecomment-625103628, and I think both reviewer agreed that automated tests are not required as part of the review.

**Comment by mkhorton** [comment]
Yes, I definitely would have liked to see automated tests, but our reading of the JOSS guidelines was that this was _not_ required to fulfill the requirements of the review (though of course encouraged!).

**Comment by kthyng** [comment]
That is correct that automated testing is not required, and I read above that *a* means of verifying correct behavior has been included. Thank you @mkhorton!

**Comment by kthyng** [comment]
@Luthaf I made some small changes to your paper in [this PR](https://github.com/cosmo-epfl/chemiscope/pull/54), please consider and merge if you agree with them. I looked through your references too and they look reasonably capitalized, etc, but please verify too.

**Comment by kthyng** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1073/pnas.1108486108 is OK
- 10.1103/physrevb.87.184115 is OK
- 10.1088/1367-2630/15/9/095003 is OK
- 10.1186/s13321-014-0041-7 is OK
- 10.1093/bioinformatics/btx760 is OK
- 10.1093/bioinformatics/btt270 is OK
- 10.1038/s41467-018-06972-x is OK
- 10.5281/zenodo.3541831 is OK
- 10.1039/c6cp00415f is OK
- 10.1186/s13321-017-0192-4 is OK
- 10.1039/c7sc04665k is OK
- 10.1016/j.commatsci.2019.02.040 is OK
- 10.1063/1.5090481 is OK
- 10.1103/physrevlett.98.146401 is OK
- 10.1021/ci300415d is OK
- 10.1038/sdata.2014.22 is OK
- 10.1103/physrevlett.104.136403 is OK
- 10.1162/089976698300017467 is OK
- 10.1002/anie.200603675 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@Luthaf after the paper is finalized, please verify the current version of the code. Also, go to a place like Zenodo and create an archive of your code and report back here with the doi. Be sure that the metadata for the Zenodo archive exactly matches that of your JOSS paper (title and authors) — you may need to update it there. This is a request but not mandatory.

**Comment by Luthaf** [comment]
We just set up zenodo, and released version 0.2.0 this morning, corresponding to the latest master (minus your PR): https://zenodo.org/record/3909400

The title should match already match, the authors also include two more people, one who helped correct a typo, and @rosecers. @rosecers made some significant contributions to the code since the paper was submited, so we'll discuss co-authorship on the paper. I'll have to correct the zenodo author list anyway, I'll try to do this tomorrow.

**Comment by cMadan** [comment]
@kblin @mkhorton, thanks for reviewing this submission!

@kthyng, thank you for providing some guidance to the authors between my check-ins here.

**Comment by cMadan** [comment]
@whedon set 0.2.0 as version

**Comment by whedon** [comment]
OK. 0.2.0 is the version.

**Comment by cMadan** [comment]
@whedon set 10.5281/zenodo.3909400 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3909400" target="_blank">10.5281/zenodo.3909400</a> is the archive.

**Comment by cMadan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02117/joss.02117/10.21105.joss.02117.pdf)

**Comment by cMadan** [comment]
@Luthaf, I think we're about all set to accept here. However, for now I'll wait until you discuss co-authorship with @rosecers and provide an update here.

**Comment by Luthaf** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02117/joss.02117/10.21105.joss.02117.pdf)

**Comment by Luthaf** [comment]
@cMadan, after discussion I've added @rosecers as co-author of the paper, and added the corresponding funding body to the acknowledgements, so this should be done from our side!

**Comment by cMadan** [comment]
@Luthaf, great, everything looks good to me! I'll flag this submission for acceptance and then an Editor-in-Chief will do a final once-over. Congratulations!

**Comment by cMadan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1073/pnas.1108486108 is OK
- 10.1103/physrevb.87.184115 is OK
- 10.1088/1367-2630/15/9/095003 is OK
- 10.1186/s13321-014-0041-7 is OK
- 10.1093/bioinformatics/btx760 is OK
- 10.1093/bioinformatics/btt270 is OK
- 10.1038/s41467-018-06972-x is OK
- 10.5281/zenodo.3541831 is OK
- 10.1039/c6cp00415f is OK
- 10.1186/s13321-017-0192-4 is OK
- 10.1039/c7sc04665k is OK
- 10.1016/j.commatsci.2019.02.040 is OK
- 10.1063/1.5090481 is OK
- 10.1103/physrevlett.98.146401 is OK
- 10.1021/ci300415d is OK
- 10.1038/sdata.2014.22 is OK
- 10.1103/physrevlett.104.136403 is OK
- 10.1162/089976698300017467 is OK
- 10.1002/anie.200603675 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1524

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1524, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Luthaf** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02117/joss.02117/10.21105.joss.02117.pdf)

**Comment by Luthaf** [comment]
We've made some tiny phrasing changes & improved the use of descriptor vs representation: https://github.com/cosmo-epfl/chemiscope/commit/8c11a56929c4793a845931939c7e60bfde740493

**Comment by danielskatz** [comment]
As AEiC on duty this week, I'll read this in the next few hours and either proceed with acceptance or provide feedback.

**Comment by danielskatz** [comment]
Please see https://github.com/cosmo-epfl/chemiscope/pull/55

Also, is "Additional" in the first paragraph needed?
And the caption of figure 2 seems to end abruptly.

**Comment by Luthaf** [comment]
Thanks for the feedback, I hope I addressed your comments in https://github.com/cosmo-epfl/chemiscope/pull/55/commits/a9828421d8832537a3ff4992f2a7de5cb3ef8fd2

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1073/pnas.1108486108 is OK
- 10.1103/physrevb.87.184115 is OK
- 10.1088/1367-2630/15/9/095003 is OK
- 10.1186/s13321-014-0041-7 is OK
- 10.1093/bioinformatics/btx760 is OK
- 10.1093/bioinformatics/btt270 is OK
- 10.1038/s41467-018-06972-x is OK
- 10.5281/zenodo.3541831 is OK
- 10.1039/c6cp00415f is OK
- 10.1186/s13321-017-0192-4 is OK
- 10.1039/c7sc04665k is OK
- 10.1016/j.commatsci.2019.02.040 is OK
- 10.1063/1.5090481 is OK
- 10.1103/physrevlett.98.146401 is OK
- 10.1021/ci300415d is OK
- 10.1038/sdata.2014.22 is OK
- 10.1103/physrevlett.104.136403 is OK
- 10.1162/089976698300017467 is OK
- 10.1002/anie.200603675 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1528

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1528, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@Luthaf - please change the metadata (title and authors) in the zenodo archive to match the paper

**Comment by Luthaf** [comment]
@danielskatz should be good now, let me know if something is missing

**Comment by danielskatz** [comment]
It seems like you added a subtitle rather than changing the title?

**Comment by Luthaf** [comment]
Sorry, it is better now?

**Comment by danielskatz** [comment]
looks good - thanks

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1278369448492138505) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1530
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02117](https://doi.org/10.21105/joss.02117)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @kblin & @mkhorton for reviewing!
And @cMadan for editing!

Congratulations to @Luthaf (Guillaume Fraux) and co-authors!

**Comment by danielskatz** [comment]
@arfon - this doesn't seem to have had the normal final message added with the badge link etc...

**Comment by Luthaf** [comment]
Thanks everyone involved here, the discussions have been very interesting!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02117/status.svg)](https://doi.org/10.21105/joss.02117)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02117">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02117/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02117/status.svg
   :target: https://doi.org/10.21105/joss.02117
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02117/status.svg)](https://doi.org/10.21105/joss.02117)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by arfon** [comment]
> @arfon - this doesn't seem to have had the normal final message added with the badge link etc...

Seems like there's some inconsistency with GitHub webhooks being sent out today.
