### ISSUE TITLE
[PRE REVIEW]: PorousFlow: a multiphysics simulation code for coupled problems in porous media

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2118]
**Submitting author:** @WilkAndy (<a href="http://orcid.org/0000-0001-6472-9560">Andy Wilkins</a>)
**Repository:** <a href="https://github.com/idaholab/moose" target ="_blank">https://github.com/idaholab/moose</a>
**Version:** v1.0.0
**Editor:** @jedbrown
**Reviewers:** @jbrezmorf, @rpodgorney
**Managing EiC:** Kevin M. Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @WilkAndy. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jedbrown.

@WilkAndy if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2118 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@jedbrown you were suggested as editor here but I can take this one too if you like.

**Comment by WilkAndy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by WilkAndy** [comment]
@whedon generate pdf from branch next

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch next. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2118 with the following error: 

 sh: 1: cd: can't cd to tmp/2118
/app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2118 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by WilkAndy** [comment]
Yea, @Kevin-Mattheus-Moerman , i only suggested @jedbrown as editor since he's probably peripherally aware of the code, since the MOOSE team liaises with the PETSc people.

Gosh, the list of possible referees has over 1000 people.  It's the evening here now, so i'll get to this tomorrow.

**Comment by jedbrown** [comment]
@Kevin-Mattheus-Moerman Fine for me either way. I'm happy to take it.

**Comment by WilkAndy** [comment]
Here are some suggestions for reviewers:

1. Cody Permann (permcody) or David Andrs (andrsd) who are MOOSE developers, so can check that we've written fairly about the MOOSE framework

2. Rob Podgorney (rpodgorney) or Philipp Schaedle (philippschaedle) or Heather Sheldon (hsheldon) who are all PorousFlow users, so can check we've included the relevant information

3. Olaf Kolditz (OlafKolditz) who is one of the authors of OpenGeoSys, which has similar functionality to PorousFlow, so could be considered a "competitor".

**Comment by WilkAndy** [comment]
Why doesn't the paper compile?  It's clearly in the repository:

https://github.com/idaholab/moose/blob/next/modules/porous_flow/paper.md

and @whedon can compile it from my own repo:

https://github.com/WilkAndy/PorousFlowDescription

I submitted an issue at  openjournals/whedon#63  just in case it's not my fault.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by Kevin-Mattheus-Moerman** [comment]
@jedbrown 
> @Kevin-Mattheus-Moerman Fine for me either way. I'm happy to take it.

Okay great.

**Comment by WilkAndy** [comment]
@Kevin-Mattheus-Moerman , is it possible to change the Repo of this to

https://github.com/WilkAndy/PorousFlowDescription

?  The code is NOT at that location, only the paper.md, paper.bib, LICENSE and README.md that points to the code's location. 

We've read the whedon Ruby script and think the first stage is to clone the Repo, which is failing.  This is because https://github.com/idaholab/moose/tree/master/modules/porous_flow isn't directly clonable, only https://github.com/idaholab/moose/ is itself.   There are about 20 physics modules of MOOSE - PorousFlow is only one of them - and we feel it's likely the authors of some other physics modules (eg, solid mechanics) will want to write JOSS papers too, so we don't want to have https://github.com/idaholab/moose/ as our repo.

**Comment by jedbrown** [comment]
We could change it, but standard practice is to put it in the parent repository and rename or delete the paper source after publication. There have been a few Landlab examples of this pattern: https://github.com/openjournals/joss-reviews/issues?utf8=%E2%9C%93&q=is%3Aissue+landlab

**Comment by WilkAndy** [comment]
Aha, i get it, thanks @jedbrown .    I will organise a separate branch of MOOSE to be created.

**Comment by WilkAndy** [comment]
@jedbrown , the MOOSE team have created a new branch.  Could you please change the repository address to

https://github.com/idaholab/moose/

with branch
```
joss_porous_flow
```

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arfon** [comment]
@whedon generate pdf from branch joss_porous_flow

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_porous_flow. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @permcody @hsheldon @rpodgorney @OlafKolditz - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02118/joss.02118/10.21105.joss.02118.pdf)

**Comment by WilkAndy** [comment]
I check the article proof - it looks good, thank you.

**Comment by hsheldon** [comment]
@arfon I think I'm a bit too close to this manuscript to review. Already done an internal review on it.

**Comment by jedbrown** [comment]
@dflanderka @jbrezmorf @Paulie14 @janhybs Would any of you from the Flow123 project be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by rpodgorney** [comment]
I can provide a review.

Robert Podgorney, PhD, PG
Lead, Geothermal and Fossil Energy
Energy and Environment Division
Idaho National Laboratory

Office: 208-526-1524<tel:208-526-1524>
Cell: 208-520-9361<tel:208-520-9361>
email: robert.podgorney@inl.gov<mailto:robert.podgorney@inl.gov>

-sent from my mobile device, please excuse any typos or autocorrect errors

Statement of Confidentiality
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.


On Apr 14, 2020, at 15:20, Jed Brown <notifications@github.com> wrote:

﻿

@dflanderka<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdflanderka&data=02%7C01%7Crobert.podgorney%40inl.gov%7C5b6f668baafc4d4a146c08d7e0b999be%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637224960070962809&sdata=th%2BD0nzovKqjSvq0wWrq%2BrXIPE32aVbfLS8PmuJrv9Y%3D&reserved=0> @jbrezmorf<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjbrezmorf&data=02%7C01%7Crobert.podgorney%40inl.gov%7C5b6f668baafc4d4a146c08d7e0b999be%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637224960070972768&sdata=9QF4M95n%2FSWNV5uFNVRBmkEIEHIAzWFh5rzY20krATE%3D&reserved=0> @Paulie14<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPaulie14&data=02%7C01%7Crobert.podgorney%40inl.gov%7C5b6f668baafc4d4a146c08d7e0b999be%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637224960070972768&sdata=XYd1JpIkca1IMOlcMKPusngLH8r9XiYVzcPy972ocuE%3D&reserved=0> @janhybs<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjanhybs&data=02%7C01%7Crobert.podgorney%40inl.gov%7C5b6f668baafc4d4a146c08d7e0b999be%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637224960070982725&sdata=00o0zB1t3x9BoDpZ%2BAwYraT1q8eLw7NdtI%2BiFrg57mU%3D&reserved=0> Would any of you from the Flow123 project be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjoss.readthedocs.io%2Fen%2Flatest%2Freviewer_guidelines.html&data=02%7C01%7Crobert.podgorney%40inl.gov%7C5b6f668baafc4d4a146c08d7e0b999be%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C637224960070982725&sdata=eXuRCyFxjfu4s54gJ%2Bq4b9m%2Bi8Vw8Mz0KNt%2F69CX6yw%3D&reserved=0>

**Comment by jbrezmorf** [comment]
I can make a review during the first week of May.

Jan Březina, Technical University of Liberec
jan _dot_ brezina _at_ tul _dot_ cz

**Comment by jedbrown** [comment]
@whedon add @jbrezmorf as reviewer

**Comment by whedon** [comment]
OK, @jbrezmorf is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @rpodgorney as reviewer

**Comment by whedon** [comment]
OK, @rpodgorney is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2176.
