### ISSUE TITLE
[REVIEW]: covtobed: a simple and fast tool to extract coverage tracks from BAM files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2119]
**Submitting author:** @telatin (<a href="http://orcid.org/0000-0001-7619-281X">Andrea Telatin</a>)
**Repository:** <a href="https://github.com/telatin/covtobed/" target ="_blank">https://github.com/telatin/covtobed/</a>
**Version:** v1.1.0
**Editor:** @will-rowe
**Reviewer:** @jdeligt, @brentp
**Archive:** <a href="https://doi.org/10.5281/zenodo.3695204" target="_blank">10.5281/zenodo.3695204</a>

## Status

[![status](https://joss.theoj.org/papers/0ed74df9f40a58a852bf3fff512acd2b/status.svg)](https://joss.theoj.org/papers/0ed74df9f40a58a852bf3fff512acd2b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/0ed74df9f40a58a852bf3fff512acd2b"><img src="https://joss.theoj.org/papers/0ed74df9f40a58a852bf3fff512acd2b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/0ed74df9f40a58a852bf3fff512acd2b/status.svg)](https://joss.theoj.org/papers/0ed74df9f40a58a852bf3fff512acd2b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/telatin/covtobed/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jdeligt & @brentp, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @will-rowe know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/telatin/covtobed/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@telatin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/telatin/covtobed/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@telatin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jdeligt, @brentp it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btq033 is OK
- 10.1093/bioinformatics/btx699 is OK
- 10.1038/nrg3642 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.1093/bioinformatics/btr174 is OK
- 10.1016/j.hrthm.2018.11.015 is OK
- 10.5281/zenodo.3643386 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02119/joss.02119/10.21105.joss.02119.pdf)

**Comment by brentp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02119/joss.02119/10.21105.joss.02119.pdf)

**Comment by jdeligt** [comment]
Hi @telatin, 

Overall looking good, please consider the integrity and performance check marks in;
https://github.com/telatin/covtobed/issues/6

And please update example usage as specified in; 
https://github.com/telatin/covtobed/issues/5

Best regards,
Joep

**Comment by brentp** [comment]
LGTM

**Comment by telatin** [comment]
Dear @brentp and @jdeligt,
thank you very much for your quick and thorough review, we really feel that your input allowed us to improve the package quality.

Summarizing:
* paper updated clarifying some sentences
* automated tests have been expanded
* the wiki documentation has been expanded, specifically including information on the coverage calculation and stressing the peculiar usage of "covtobed" (physical-coverage, strand-specific analysis, streaming)
* the benchmark section has been expanded to include a test with a whole human genome and its description extended
* released 1.0.1 with support for coverage > 2**16, initially naively excluded

See: https://github.com/telatin/covtobed/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Ajoss+ for the issues opened in the repo

**Comment by jdeligt** [comment]
Hi @telatin , 

Thank you for the quick responses and the additions made to the repo.
I added one last comment to issue#5 but this is a nice to have but should not hold up publication. 
The clarifactions will help users better determine what the software does and is a nice intro into some of the vageries of coverage depth calculations. 

@will-rowe, looks like @brentp is happy with it as well so I think we'll hand it back to you.

**Comment by will-rowe** [comment]
Perfect - thanks for your speedy and excellent reviews @jdeligt and @brentp!

This is looking really nice @telatin  - I'll just give it a finally read through

**Comment by will-rowe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02119/joss.02119/10.21105.joss.02119.pdf)

**Comment by will-rowe** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btq033 is OK
- 10.1093/bioinformatics/btx699 is OK
- 10.1038/nrg3642 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.1093/bioinformatics/btr174 is OK
- 10.1016/j.hrthm.2018.11.015 is OK
- 10.5281/zenodo.3643386 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by will-rowe** [comment]
Okay I think we can move toward acceptance here!

@telatin - I need you to tag a new release and archive it. Then can you get back to me with the version number and the archive DOI.

**Comment by telatin** [comment]
Thanks to you all for your great work!

* **Archived release**
https://github.com/telatin/covtobed/releases/tag/v1.1.0

* **Zeonodo**
Birolo, Giovanni, & Telatin, Andrea. (2020, March 3). covtobed 1.1 - a simple and fast tool to convert the coverage track from a BAM file into a BED file (Version 1.1.0). Zenodo. http://doi.org/10.5281/zenodo.3695204

**Comment by will-rowe** [comment]
@whedon set 10.5281/zenodo.3695204 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3695204" target="_blank">10.5281/zenodo.3695204</a> is the archive.

**Comment by will-rowe** [comment]
@whedon set v1.1.0 as version

**Comment by whedon** [comment]
OK. v1.1.0 is the version.

**Comment by will-rowe** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btq033 is OK
- 10.1093/bioinformatics/btx699 is OK
- 10.1038/nrg3642 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.1093/bioinformatics/btr174 is OK
- 10.1016/j.hrthm.2018.11.015 is OK
- 10.5281/zenodo.3643386 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published

. Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1351

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1351, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
I've read the paper and it looks good

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1235979491152928768) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1356
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02119](https://doi.org/10.21105/joss.02119)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by will-rowe** [comment]
Pinging @openjournals/jose-eics - I think this can be closed now?

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02119/status.svg)](https://doi.org/10.21105/joss.02119)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02119">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02119/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02119/status.svg
   :target: https://doi.org/10.21105/joss.02119
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02119/status.svg)](https://doi.org/10.21105/joss.02119)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by arfon** [comment]
> Pinging @openjournals/jose-eics - I think this can be closed now?

Just a heads up @will-rowe that you mentioned the wrong EiC group here :-)
