### ISSUE TITLE
[PRE REVIEW]: Pynamical: Model and visualize discrete nonlinear dynamical systems, chaos, and fractals

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#212]
**Submitting author:** @gboeing (<a href="http://orcid.org/0000-0003-1851-6411">Geoff Boeing</a>)
**Repository:** <a href="https://github.com/gboeing/pynamical" target ="_blank">https://github.com/gboeing/pynamical</a>
**Version:** v0.1.1
**Editor:** Pending
**Reviewer:** Pending

**What this issue is for**

Thanks for submitting your paper to JOSS @gboeing. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by labarba** [comment]
Thank for your submission, @gboeing. That certainly looks cool, and it seems like a neat package for teaching Nonlinear Dynamics. But can you clarify whether the software has a research application? The examples shown are textbook systems—they look great, though! (And I do not find a statement of need.)

**Comment by gboeing** [comment]
@labarba thanks so much for the quick feedback. I've updated the paper per your suggestions, to clarify its research applications and state the need/gap it fills.

**Comment by gboeing** [comment]
@labarba please let me know if there's anything else you need from me to begin the review

**Comment by labarba** [comment]
As far as I can see, this package is not a research tool. It may be useful for teaching a beginner course in dynamical systems at the undergraduate level. Even there, the author has pretty much given all the examples of interest. Historically, these systems played a role in calling people’s attention to dynamical systems, but there are no applications in the modern literature where one-dimentional discrete systems have research significance. This type of model is simply not used in present-day research. Can the tool compute two- or three-dimensional discrete-time systems? Is it limited to autonomous, or can it do non-autonomous systems? If so, provide examples. The author does not make the case that the tool can be applied to contemporary applications that use dynamical modeling.

**Comment by arfon** [comment]
👋 @gboeing - do you have any thoughts based on @labarba's comment?

**Comment by gboeing** [comment]
Hi @arfon, I will defer to the editors' judgment on topics of publishability.

**Comment by labarba** [comment]
@gboeing We are launching a new journal which you might consider moving your submission to (submissions will open in a few weeks):
https://github.com/openjournals/jose

**Comment by gboeing** [comment]
@labarba thanks. I'll keep my eye on it for when submissions open.

**Comment by kyleniemeyer** [comment]
I agree this looks like a great candidate for JOSE, as it seems like a tool more useful to explain/explore dynamical systems from an educational perspective rather than being a reusable research tool—unless there are research use cases we are missing.

@gboeing If you agree, would you be ok with withdrawing this submission for now, and resubmitting to JOSE as soon as we open that up? (or leave this open until then, but we can tag as "paused" or "withdrawn")

**Comment by gboeing** [comment]
@kyleniemeyer sure we can withdraw this here then. When is JOSE estimated to open up?

**Comment by labarba** [comment]
We hope JOSE can start receiving submissions in maybe about a month or so ... currently, we're stuck on the need to make some changes to the submission web form, but we don't have a Ruby programmer who can contribute that right now.

**Comment by gboeing** [comment]
Hi @labarba just checking back on this. Is there an update on when JOSE will start receiving submissions?

**Comment by labarba** [comment]
We're getting increasing number of enquiries about the launch of JOSE!
As you can see in this [issue](https://github.com/openjournals/joss/issues/329#issuecomment-336757238), we are close to having the infrastructure changes in JOSS to be re-usable for JOSE. (A couple more weeks?)

**Comment by arfon** [comment]
Closing this as this submission isn't being considered for JOSS but feel free to keep checking back on JOSE updates @gboeing :-)
