### ISSUE TITLE
[REVIEW]: Pippin: A pipeline for supernova cosmology

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2122]
**Submitting author:** @samreay (<a href="http://orcid.org/0000-0003-2071-9349">Samuel Hinton</a>)
**Repository:** <a href="https://github.com/Samreay/Pippin" target ="_blank">https://github.com/Samreay/Pippin</a>
**Version:** 0.1.1
**Editor:** @arfon
**Reviewer:** @kboone, @temuller
**Archive:** <a href="https://doi.org/10.5281/zenodo.3716116" target="_blank">10.5281/zenodo.3716116</a>

## Status

[![status](https://joss.theoj.org/papers/956143a352df07f181555e7d167ff20f/status.svg)](https://joss.theoj.org/papers/956143a352df07f181555e7d167ff20f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/956143a352df07f181555e7d167ff20f"><img src="https://joss.theoj.org/papers/956143a352df07f181555e7d167ff20f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/956143a352df07f181555e7d167ff20f/status.svg)](https://joss.theoj.org/papers/956143a352df07f181555e7d167ff20f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Samreay/Pippin" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kboone & @temuller, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Samreay/Pippin">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (samreay) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Samreay/Pippin">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (samreay) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kboone, @temuller it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/MCSE.2007.55 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1086/605984 is OK
- 10.1103/PhysRevD.66.103511 is OK
- 10.21105/joss.00045 is OK
- 10.3847/2041-8213/ab04fa is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02122/joss.02122/10.21105.joss.02122.pdf)

**Comment by arfon** [comment]
@kboone, @temuller - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html and if possible I'd appreciate it if you could complete your review in the next 2-3 weeks.

Any questions/concerns please let me know!

**Comment by temuller** [comment]
See my review attached.
[JOSS_Review_2122.pdf](https://github.com/openjournals/joss-reviews/files/4312102/JOSS_Review_2122.pdf)

**Comment by Samreay** [comment]
Hey Tomás! I've added a link to the SNANA report and made the purpose statement clearer in the main readme. As to reporting issues or seeking support, I've updated the contribution section to make it clear that it applies to seeking support and raising issues.

As to the functionality, this is definitely a hassle - because Pippin is a pipeline that stitches other software together, running it necessarily requires having those pieces installed (which is a big hassle for SNANA if you dont have a midway account). Even the data prep stages uses new code in SNANA to determine better starting conditions for the eventual light curve fitting of data. 

I'd be happy to record a video showing the usage in action if that would help, just let me know.

**Comment by temuller** [comment]
Hi Sam, thanks for the prompt reply.

I know installing SNANA can be a hassle (I have installed it myself!), but as it is a core package used by Pippin, you should be able to provide a straight forward example (assuming the user has SNANA already installed). If you think recording a video can show the usage properly, there is no problem with that, but I am not sure if it is actually simpler that way.

**Comment by Samreay** [comment]
Ah, thanks for the catch on the hyperlink I broke! And ah, if you have a working SNANA install, I am hoping that this config file would run without hassle for you: https://github.com/Samreay/Pippin/blob/master/configs/examples/example_sim.yml

If there are issues I'll record the video - Im conscious about not taking too much of your time installing deps and smacking paths around given how much work you've done already. Thanks for the comments so far too, appreciate it!

**Comment by temuller** [comment]
Pippin is complaining about the "group" keyword for SNANA in the cfg.yml file. It doesn't seem to find it anywhere. Is it meant to work with midway?

**Comment by Samreay** [comment]
Ah, yes, it's trying to set the group ownership over newly created files to Rick Kessler's group by default (the one we use in DES) so that other members of the collaboration can use it. You should be able to set the group to your own name or whatever group you are part of

**Comment by temuller** [comment]
It doesn't find any group if I run it locally on my machine

**Comment by Samreay** [comment]
As in it can't find the property itself? Throw me the stack if you can,
I'll get it fixed up asap

**Comment by temuller** [comment]
Here is the output 
[pippin_output.txt](https://github.com/openjournals/joss-reviews/files/4312986/pippin_output.txt)

**Comment by Samreay** [comment]
Ah, so yeah we need to find you a valid group - you can list groups in linux using `groups $USER`. The second error is then because Pippin needs python3.7+ as per the doco alas - text is a new kwarg. Let me make a quick video showing it in action so you dont have to dick around.

**Comment by Samreay** [comment]
Heres a link to executing the sim example and showing the output log results of our preliminary 5yr DES analysis, let me know if youd like other examples: https://youtu.be/pCaPvzFCZ-Y

**Comment by temuller** [comment]
Thanks for the video Sam. I was able to correct the errors I had, but I encountered a new one (it has to do with subprocess.check_output). However, I think that after solving this one, the example should run fine. See below.

[pippin_output2.txt](https://github.com/openjournals/joss-reviews/files/4315325/pippin_output2.txt)

**Comment by Samreay** [comment]
Ah yes, so Pippin is supposed to be run on an HPC, as it submits and checks
on the status of jobs. To do that it executes squeue, which seems to be
having an issue - are you on an HPC?

**Comment by temuller** [comment]
Ah, I see! I am not! I will see if I can do that tomorrow. I will just give it a try and see how that goes, but I guess I am quite happy with the changes. I will double-check everything tomorrow so I can finish the review. Thanks a lot!

**Comment by temuller** [comment]
Hi again Sam. I am finally happy with the changes you made. I would like you to add the description/example video to the documentation so users have access to it, but that is last thing I will ask you to do. Thanks!

**Comment by Samreay** [comment]
Awesome, thanks for finally getting it working! I've added a link to the video in the description :)

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by kboone** [comment]
I have attached my review. I have a couple of minor suggestions that should be fixed before accepting this paper for publication.

[JOSS Review #2122.pdf](https://github.com/openjournals/joss-reviews/files/4346420/JOSS.Review.2122.pdf)

**Comment by Samreay** [comment]
Hey Kyle! I've made the requested changes to improve the documentation and pushed them out. You can verify the changes here: https://github.com/Samreay/Pippin/commit/7e4c108d086e00c79d436ddc37dd92dc824f0062

Cheers!

**Comment by kboone** [comment]
The changes look good, and they address my concerns. I recommend this paper for acceptance.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02122/joss.02122/10.21105.joss.02122.pdf)

**Comment by arfon** [comment]
@Samreay - a few comments on your paper:

Do you want the title to be only 'Pippin'? _Pippin: A pipeline for supernova cosmology_ seems more descriptive?

>  For the DES-3YR analysis (Abbott et al., 2019), we implemented a basic bash pipeline
to reduce manual labour. For the DES-5YR analysis, which greatly increases complexity, I
implement this pipeline to increase researcher productivity.

This ☝️ paragraph reads a little weirdly. You're using 'we' and then 'I' in the same sentence. Perhaps this could be rephrased as:

>  For the DES-3YR analysis (Abbott et al., 2019), we implemented a basic bash pipeline
to reduce manual labour. For the DES-5YR analysis, which greatly increases complexity, Pippin was developed as the pipeline to increase researcher productivity.

Should 'SALT2 supernova model' have a citation?

Last sentence change Github to GitHub. Also, consider linking the phrase 'development page' to to https://github.com/Samreay/Pippin/issues .

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/MCSE.2007.55 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1086/605984 is OK
- 10.1103/PhysRevD.66.103511 is OK
- 10.21105/joss.00045 is OK
- 10.3847/2041-8213/ab04fa is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Samreay** [comment]
Hi @arfon, I've made the I/we consistent change in the latest commit. The SALT2 paper reference is still in draft and yet to be submitted. Github -> GitHub, and a link to the developer doco has been added.

**Comment by Samreay** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02122/joss.02122/10.21105.joss.02122.pdf)

**Comment by arfon** [comment]
@Samreay - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by Samreay** [comment]
Done and done! :)

https://zenodo.org/record/3716116

**Comment by arfon** [comment]
@Samreay - last time I'll ask I promise (as the title of the Zenodo release is _Pippin: A pipeline for supernova cosmology_. You definitely want the title of the JOSS paper to only be _Pippin_?

**Comment by Samreay** [comment]
Oh I thought the title was the full "Pippin: A pipeline for supernova cosmology", as it is in this review. Definitely the full name makes more sense haha

**Comment by arfon** [comment]
Glad I checked :-) https://github.com/Samreay/Pippin/pull/3 fixes this.

**Comment by Samreay** [comment]
Ah right, the paper.md, of course! Thanks for the fix! :)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3716116 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3716116" target="_blank">10.5281/zenodo.3716116</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/MCSE.2007.55 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1086/605984 is OK
- 10.1103/PhysRevD.66.103511 is OK
- 10.21105/joss.00045 is OK
- 10.3847/2041-8213/ab04fa is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1379

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1379, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1240612065666088961) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1380
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02122](https://doi.org/10.21105/joss.02122)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@kboone, @temuller - many thanks for your reviews here ✨ 

@Samreay - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02122/status.svg)](https://doi.org/10.21105/joss.02122)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02122">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02122/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02122/status.svg
   :target: https://doi.org/10.21105/joss.02122
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02122/status.svg)](https://doi.org/10.21105/joss.02122)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
