### ISSUE TITLE
[REVIEW]: CloudnetPy: A Python package for processing cloud remote sensing data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2123]
**Submitting author:** @tukiains (<a href="http://orcid.org/0000-0002-0651-4622">Simo Tukiainen</a>)
**Repository:** <a href="https://github.com/actris-cloudnet/cloudnetpy" target ="_blank">https://github.com/actris-cloudnet/cloudnetpy</a>
**Version:** v1.2.4
**Editor:** @jedbrown
**Reviewers:** @josephhardinee, @ekschuman
**Archive:** <a href="https://doi.org/10.5281/zenodo.4011843" target="_blank">10.5281/zenodo.4011843</a>

## Status

[![status](https://joss.theoj.org/papers/959971f196f617dddc0e7d8333ff22b7/status.svg)](https://joss.theoj.org/papers/959971f196f617dddc0e7d8333ff22b7)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/959971f196f617dddc0e7d8333ff22b7"><img src="https://joss.theoj.org/papers/959971f196f617dddc0e7d8333ff22b7/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/959971f196f617dddc0e7d8333ff22b7/status.svg)](https://joss.theoj.org/papers/959971f196f617dddc0e7d8333ff22b7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/actris-cloudnet/cloudnetpy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@josephhardinee, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @jedbrown know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/actris-cloudnet/cloudnetpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@tukiains) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/actris-cloudnet/cloudnetpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@tukiains) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @josephhardinee it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1175/BAMS-88-6-883 is OK
- 10.1175/JAM2340.1 is OK
- 10.1175/JAM-2181.1 is OK
- 10.5194/acp-19-1985-2019 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02123/joss.02123/10.21105.joss.02123.pdf)

**Comment by jedbrown** [comment]
@josephhardinee :wave: Welcome and thanks for agreeing to review! The comments from @whedon above outline the review process, which takes place in this thread (possibly with issues filed in the CloudnetPy repository). I'll be watching this thread if you have any questions.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `https://github.com/openjournals/joss-reviews/issues/2123` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@jedbrown) if you have any questions/concerns.

**Comment by josephhardinee** [comment]
@commands whedon

**Comment by josephhardinee** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by josephhardinee** [comment]
@jedbrown I appear to be unable to click on the checkboxes. The invite to collaborate link also says expired.

**Comment by arfon** [comment]
@josephhardinee - could you try the invite now again? https://github.com/openjournals/joss-reviews/invitations

**Comment by josephhardinee** [comment]
Thanks it works now.

**Comment by jedbrown** [comment]
@whedon add @ekschuman as reviewer

**Comment by whedon** [comment]
OK, @ekschuman is now a reviewer

**Comment by jedbrown** [comment]
@ekschuman :wave: Welcome to JOSS and thanks for agreeing to review! (I understand you are available and willing, per Joseph.  Please let me know here or by email if that is not accurate or you need any accommodation.)

The comments from @whedon above outline the review process, which takes place in this thread (possibly with issues filed in the CloudnetPy repository). I'll be watching this thread if you have any questions.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `https://github.com/openjournals/joss-reviews/issues/2123` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@jedbrown) if you have any questions/concerns.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arfon** [comment]
:wave: @josephhardinee, @ekschuman - just a friendly check-in to see how things are going with your reviews?

**Comment by arfon** [comment]
👋 @josephhardinee, @ekschuman - today we [reopened JOSS](https://blog.joss.theoj.org/2020/05/reopening-joss) for new submissions and are checking in on our existing reviews. Do you think you might be able to wrap up your reviews in the next 2-3 weeks?

**Comment by kthyng** [comment]
I've emailed @josephhardinee to check in but can't find an email address for @ekschuman. Next check-in by an AEiC, I think we should remove reviewers and find new if we haven't heard from either.

**Comment by kthyng** [comment]
6 days later I haven't heard back from @josephhardinee.

@jedbrown I suggest removing the reviewers and finding new ones, unless you can find a way to get ahold of them!

**Comment by josephhardinee** [comment]
I apologize, I was out at the end of last week and this kinda slipped off my radar with things going on. I'll get right back on this as I still have some notes from when I first  started on it. I'll also ping Eddie as I think he was out on vacation last week .

**Comment by jedbrown** [comment]
Many thanks @josephhardinee!

**Comment by kthyng** [comment]
Thanks @josephhardinee! Sounds great!

**Comment by josephhardinee** [comment]
The authors have addressed all issues I've raised so this is good to go on my end.

**Comment by ekschuman** [comment]
They have also addressed everything I have raised, so it is good on my end as well.

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by jedbrown** [comment]
@whedon check references

**Comment by whedon** [comment]
PDF failed to compile for issue #2123 with the following error: 

 sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.02123.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1175/BAMS-88-6-883 is OK
- 10.1175/JAM2340.1 is OK
- 10.1175/JAM-2181.1 is OK
- 10.5194/acp-19-1985-2019 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jedbrown** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02123/joss.02123/10.21105.joss.02123.pdf)

**Comment by tukiains** [comment]
The proof looks good to me.

**Comment by jedbrown** [comment]
Reads well to me. In order to proceed with acceptance, could you please:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

**Comment by jedbrown** [comment]
And should the version be v1.0.7 or one of the later releases (v1.2.4 looks to be the most recent)?

**Comment by tukiains** [comment]
Yes, the correct version is the latest (v1.2.4). This tagged release is archived in Zenodo with the correct metadata. 

The DOI of the archived version is [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4011843.svg)](https://doi.org/10.5281/zenodo.4011843)

**Comment by jedbrown** [comment]
@whedon set v1.2.4 as version

**Comment by whedon** [comment]
OK. v1.2.4 is the version.

**Comment by jedbrown** [comment]
@whedon set 10.5281/zenodo.4011843 as DOI

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by jedbrown** [comment]
@whedon set 10.5281/zenodo.4011843 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4011843" target="_blank">10.5281/zenodo.4011843</a> is the archive.

**Comment by jedbrown** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1175/BAMS-88-6-883 is OK
- 10.1175/JAM2340.1 is OK
- 10.1175/JAM-2181.1 is OK
- 10.5194/acp-19-1985-2019 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1705

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1705, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by kthyng** [comment]
Congrats on your new publication to @tukiains! Thanks to editor @jedbrown and to reviewers @josephhardinee and @ekschuman. This process couldn't occur without your time and expertise.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02123/status.svg)](https://doi.org/10.21105/joss.02123)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02123">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02123/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02123/status.svg
   :target: https://doi.org/10.21105/joss.02123
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02123/status.svg)](https://doi.org/10.21105/joss.02123)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by tukiains** [comment]
Thank you @jedbrown and @kthyng for editing and publishing the paper, and big thanks @josephhardinee and @ekschuman for reviewing!
