### ISSUE TITLE
[REVIEW]: Maelstrom: A Python package for identifying companions to pulsating stars from their light travel time variations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2125]
**Submitting author:** @danhey (<a href="http://orcid.org/0000-0003-3244-5357">Daniel Hey</a>)
**Repository:** <a href="https://github.com/danhey/maelstrom" target ="_blank">https://github.com/danhey/maelstrom</a>
**Version:** v0.3
**Editor:** @mbobra
**Reviewers:** @hpparvi, @mbobra
**Archive:** <a href="https://doi.org/10.5281/zenodo.3937862" target="_blank">10.5281/zenodo.3937862</a>

## Status

[![status](https://joss.theoj.org/papers/44657d050c3c99237d4c546e245f1c21/status.svg)](https://joss.theoj.org/papers/44657d050c3c99237d4c546e245f1c21)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/44657d050c3c99237d4c546e245f1c21"><img src="https://joss.theoj.org/papers/44657d050c3c99237d4c546e245f1c21/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/44657d050c3c99237d4c546e245f1c21/status.svg)](https://joss.theoj.org/papers/44657d050c3c99237d4c546e245f1c21)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/danhey/maelstrom" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@hpparvi & @DingXuefeng, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mbobra know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/danhey/maelstrom">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@danhey) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/danhey/maelstrom">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@danhey) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @hpparvi, @DingXuefeng it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/nature24153 is OK
- 10.1093/mnras/stv884 is OK
- 10.1016/0370-2693(87)91197-X is OK
- 10/gdk3dm is OK
- 10.5281/zenodo.3359880 is OK
- 10.1093/mnras/stw1622 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02125/joss.02125/10.21105.joss.02125.pdf)

**Comment by mbobra** [comment]
@hpparvi, @DingXuefeng Thank you for agreeing to review this submission! We really appreciate your time. Whedon generated a checklist and linked a reviewer guide above. Please let me know if you have any questions or comments, and please feel free to have an open dialogue with the submitting author and each other ☀️

**Comment by arfon** [comment]
:wave: @mbobra - the accompanying AAS paper is accepted (not yet published) and the DOI is `10.3847/1538-3881/ab7d38`. When you get a chance @danhey, please add this information to your `paper.md` YAML header as [described in our docs](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain):

```
# Optional fields if submitting to a AAS journal too, see this blog post:
# https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing
aas-doi: 10.3847/xxxxx <- update this with the DOI from AAS once you know it.
aas-journal: Astrophysical Journal <- The name of the AAS journal.
```

**Comment by danhey** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02125/joss.02125/10.21105.joss.02125.pdf)

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arfon** [comment]
:wave:  @hpparvi, @DingXuefeng - just a friendly check-in to see how things are going with your reviews?

**Comment by danhey** [comment]
Hi all, just a heads up that the paper has now been published -- https://doi.org/10.3847/1538-3881/ab7d38

**Comment by arfon** [comment]
Thanks for the heads-up @danhey / cc @crawfordsm

**Comment by arfon** [comment]
👋 @hpparvi, @DingXuefeng - today we [reopened JOSS](https://blog.joss.theoj.org/2020/05/reopening-joss) for new submissions and are checking in on our existing reviews. Do you think you might be able to wrap up your reviews in the next 2-3 weeks?

**Comment by hpparvi** [comment]
My apologies for the extremely long delay. I'll aim to finish my review by Friday.

**Comment by hpparvi** [comment]
Dear all,

I find the code clear and well-documented. Installation works without issues, the tutorials in the user guide are clear (some could do with a bit cleaning up, but nothing major), and the real-life use-case notebooks reproducing the analyses reported in the associated AJ paper are also very useful.

The only two minor issues I can find with this submission is the lack of community guidelines (e.g. how to contribute to the code.) and docstring formatting. Community guidelines are required by the JOSS policy but should be a very quick thing to fix. 

The second issue is that some of the docstrings use Google style while others use Numpy style. Combining both styles in a single file may confuse Sphinx, and some of the API documentation has problems with formatting (such as the documentation of the main Maelstrom class). However, this is mainly cosmetics (the docs are understandable) and not an acceptance-blocker.

So, I believe the code will be useful to the astrophysics community, and I recommend accepting the submission after the community guidelines (at least a "contributing" document) are added.

**Comment by mbobra** [comment]
@hpparvi Thank you so much for your review! Do you mind opening an issue on the submitting author's repo about contributing guidelines? Also, should the authors address any issues with functionality (I noticed those two boxes are also unchecked)?

**Comment by hpparvi** [comment]
@mbobra Done! I left the functionality checkbox unchecked because I still wanted to test things for a moment. This will need to wait till tomorrow, but I expect to be able to check this box too by the time the community guidelines have been added.

**Comment by hpparvi** [comment]
@danhey has added the contribution document to the repository and I'm now happy to recommend accepting his contribution.

**Comment by mbobra** [comment]
@DingXuefeng Please let me know if you need any help with this review! I'm happy to help.

**Comment by mbobra** [comment]
@danhey I know this has been a long process -- thanks for hanging in there. I've contacted @DingXuefeng via e-mail.

**Comment by danhey** [comment]
No problem, I understand everyone's busy so I appreciate the review :)

**Comment by mbobra** [comment]
@danhey I cannot reach @DingXuefeng, so I will review. I'll work on this today and can hopefully finish by tomorrow.

**Comment by mbobra** [comment]
@whedon remove @DingXuefeng as reviewer

**Comment by whedon** [comment]
OK, @DingXuefeng is no longer a reviewer

**Comment by mbobra** [comment]
@whedon add @mbobra as reviewer

**Comment by whedon** [comment]
OK, @mbobra is now a reviewer

**Comment by mbobra** [comment]
@danhey Great work!!! ☀️ I enjoyed playing with the code today and learning about phase modulation. I (referee hat) recommend accepting this submission. Can you fix the authorship issue in Zenodo? Then I (editor hat) will move forward with the acceptance process.

**Comment by danhey** [comment]
Great, thanks for the review @mbobra! I've updated the Zenodo listing with all the paper authors.

**Comment by mbobra** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02125/joss.02125/10.21105.joss.02125.pdf)

**Comment by mbobra** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/nature24153 is OK
- 10.1093/mnras/stv884 is OK
- 10.1016/0370-2693(87)91197-X is OK
- 10/gdk3dm is OK
- 10.5281/zenodo.3359880 is OK
- 10.1093/mnras/stw1622 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mbobra** [comment]
@danhey Thank you, we're almost there! I have a couple more small requests:
*  Could you please cut a new release and deposit it in Zenodo? (I see the most recent one is from February 16, which doesn't include the `CONTRIBUTING.md` file). And then re-update the author list?
* Also do you mind changing the DOI for the Murphy+2018 reference from the short link to https://doi.org/10.1093/mnras/stx3049?

**Comment by danhey** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02125/joss.02125/10.21105.joss.02125.pdf)

**Comment by danhey** [comment]
Hi @mbobra, I've updated the DOI! I'm happy to make a new release for Zenodo but the AAS paper points to the v0.2 Zenodo release, which I don't think can be changed now.

**Comment by mbobra** [comment]
@danhey Thank you! hmmm, interesting. I am not sure what to do here. 

@openjournals/joss-eics, submitting author @danhey submitted a joint publication with The Astronomical Journal. The AAS publication cites Zenodo release v0.2 of the author's package, `Maelstrom`. The AAS review process is over, and the paper has been accepted (and cannot be changed). However, the JOSS review is ongoing. JOSS referees requested changes to `Maelstrom` that the submitting author implemented. Cutting a new release with these changes would result in v0.3, thereby causing a mismatch with The Astronomical Journal paper. How do you recommend we proceed?

**Comment by danielskatz** [comment]
I will defer to @arfon specifically in this case

**Comment by arfon** [comment]
> Cutting a new release with these changes would result in v0.3, thereby causing a mismatch with The Astronomical Journal paper. How do you recommend we proceed?

I think this mismatch is not ideal but is better than not having a new release with the changes from this review. So please create a `v0.3` release and post the DOI here.

/ cc @crawfordsm from the AAS-side of things.

**Comment by crawfordsm** [comment]
Unfortunately, as this paper was already published, I don't think there is much we can change on our side at this time.

**Comment by mbobra** [comment]
@danhey Can you please create a new release and add a sentence (or a footnote) to the JOSS paper about this mismatch?

**Comment by mbobra** [comment]
@danhey Let me know if want any help with this, I'm happy to get your paper published as soon as possible :)

**Comment by danhey** [comment]
Hi all, apologies for my delay! I've cut a new release and it's now on Zenodo: https://zenodo.org/record/3937862

**Comment by mbobra** [comment]
@whedon set 10.5281/zenodo.3937862 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3937862" target="_blank">10.5281/zenodo.3937862</a> is the archive.

**Comment by mbobra** [comment]
@whedon set v0.3 as version

**Comment by whedon** [comment]
OK. v0.3 is the version.

**Comment by mbobra** [comment]
@openjournals/joss-eics this paper is ready for final processing! 🎉🎉🎉

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/nature24153 is OK
- 10.1093/mnras/stv884 is OK
- 10.1016/0370-2693(87)91197-X is OK
- 10.5281/zenodo.3359880 is OK
- 10.1093/mnras/stw1622 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1093/mnras/stx3049 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1557

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1557, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1281399864589516801) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1558
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02125](https://doi.org/10.21105/joss.02125)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@hpparvi, @mbobra - many thanks for your reviews here and to @mbobra for editing too ✨ 

@danhey - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02125/status.svg)](https://doi.org/10.21105/joss.02125)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02125">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02125/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02125/status.svg
   :target: https://doi.org/10.21105/joss.02125
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02125/status.svg)](https://doi.org/10.21105/joss.02125)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
