### ISSUE TITLE
[PRE REVIEW]: Omorfi: Open morphology of Finnish

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2126]
**Submitting author:** @flammie (<a href="http://orcid.org/0000-0003-1207-5395">Tommi Pirinen</a>)
**Repository:** <a href="https://github.com/flammie/omorfi/" target ="_blank">https://github.com/flammie/omorfi/</a>
**Version:** 2020-05-11
**Editor:** @hugoledoux
**Reviewers:** @desilinguist
**Managing EiC:** Lorena A Barba

**Author instructions**

Thanks for submitting your paper to JOSS @flammie. **Currently, there isn't an JOSS editor assigned** to your paper.

@flammie if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02126/joss.02126/10.21105.joss.02126.pdf)

**Comment by labarba** [comment]
👋 @lorenanicole — This submission is in computational linguistics and natural language processing, and I think you are our only expert in these areas. Can you take it as handling editor? Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @lorenanicole as editor

**Comment by whedon** [comment]
@lorenanicole has been invited to edit this submission.

**Comment by danielskatz** [comment]
👋 @lorenanicole - just a reminder/ping...

**Comment by lorenanicole** [comment]
Hi folks! I apologize, some Python Software Foundation commitments are sending me scrambling due to covid19. Should be freed up this weekend!

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arfon** [comment]
:wave: @hugoledoux - I realize this isn't close to your fields/disciplines but given the pause in submissions for JOSS right now, this is the only paper currently without an editor assigned. 

Are you OK for me to go ahead and assign this to you?

**Comment by hugoledoux** [comment]
ok sure

**Comment by arfon** [comment]
@whedon assign @hugoledoux as editor

**Comment by whedon** [comment]
OK, the editor is @hugoledoux

**Comment by arfon** [comment]
👍 thanks @hugoledoux. Over to you and @flammie to identify some potential reviewers together.

**Comment by hugoledoux** [comment]
Hello @flammie , I'm the editor of your paper, and this is my first (!), so apologies if things don't go as fast as you'd normally expect.

Since, as you saw above, the best editor if unavailable, I'd appreciate if you could give any suggestions for potential reviewers (please please mention them in this thread (without tagging them with an @)).

**Comment by flammie** [comment]
no worries, we're all busy with random things at the moment. If we can recruit freely I'd probably suggest from the reviewer pool of nlp oss workshop: https://nlposs.github.io/2020/index.html#programme-committee. I personally only know alvations (Liling Tan) who is organising but he may be quite busy.

**Comment by arfon** [comment]
:wave: @hugoledoux - did you manage to take a look at that list of suggested reviewers?

**Comment by hugoledoux** [comment]
@desilinguist happy to wait till beginning June for your review, I'll add you, thanks

**Comment by hugoledoux** [comment]
@arfon I contacted 2 potential reviewers, one just accepted (see above), waiting for the other one. If no answer by next week I'll try others

**Comment by hugoledoux** [comment]
@whedon assign @desilinguist as reviewer

**Comment by whedon** [comment]
OK, @desilinguist is now a reviewer

**Comment by hugoledoux** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2184.
