### ISSUE TITLE
[PRE REVIEW]: OpenDrop: Open-source software for pendant drop tensiometry & contact angle measurements

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2128]
**Submitting author:** @jdber1 (<a href="http://orcid.org/0000-0002-0961-7782">Joe Berry</a>)
**Repository:** <a href="https://github.com/jdber1/opendrop" target ="_blank">https://github.com/jdber1/opendrop</a>
**Version:** v3
**Editor:** @kyleniemeyer
**Reviewers:** @cryos, @rajeshrinet
**Managing EiC:** Lorena A Barba

**Author instructions**

Thanks for submitting your paper to JOSS @jdber1. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kyleniemeyer.

@jdber1 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1103/physrevlett.100.024501 may be missing for title: Decompressing emulsion droplets favors coalescence
- https://doi.org/10.1103/revmodphys.69.865 may be missing for title: Nonlinear dynamics and breakup of free-surface flows
- https://doi.org/10.1163/156856192x00629 may be missing for title: Contact angle, wetting, and adhesion: a critical review
- https://doi.org/10.1016/j.jcis.2016.10.040 may be missing for title: Mapping coalescence of micron-sized drops and bubbles
- https://doi.org/10.1016/j.biosystemseng.2012.02.005 may be missing for title: Experimental method for the assessment of agricultural spray retention based on high-speed imaging of drop impact on a synthetic superhydrophobic surface
- https://doi.org/10.1039/c6sm00047a may be missing for title: Electrokinetics of isolated electrified drops
- https://doi.org/10.1039/c7ra05538b may be missing for title: A comparative analysis of antibacterial properties and in flammatory responses for the KR-12 peptide on titanium and PEGylated titanium surfaces
- https://doi.org/10.1038/srep21048 may be missing for title: Durable, superoleophobic polymer – nanoparticle composite surfaces with re-entrant geometry via solvent-induced phase transformation
- https://doi.org/10.1021/acsami.7b03094 may be missing for title: Decreasing the Wettability of Cellulose Nanocrystal Surfaces Using Wrinkle-Based Alignment
- https://doi.org/10.1021/la102566c may be missing for title: Contact angles of liquid drops on super hydrophobic surfaces: understanding the role of flattening of drops by gravity

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02128/joss.02128/10.21105.joss.02128.pdf)

**Comment by labarba** [comment]
@openjournals/dev Can you check why our bot didn't run `cloc` on starting this pre-review? And also why it's flagging all those missing DOIs when the paper only has two citations.

**Comment by labarba** [comment]
👋 @kyleniemeyer — The authors suggested you as handling editor for this submission. The software facilitates acquisition, analysis and fitting of pendant drop profiles to obtain surface and interfacial tension. Can you take it?

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.42 s (557.5 files/s, 60586.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         220           4971           6376          13118
TeX                              1             18              0            162
reStructuredText                 8            145            146            131
Markdown                         1             15              0             78
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           232           5161           6530          13524
-------------------------------------------------------------------------------


Statistical information for the repository '2128' was gathered on 2020/03/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Eugene Huang                     9           484            257            0.57
eugenevorld                    532         70882          52473           94.46
eugenhu                          5            32             26            0.04
jberry                           3          6347             83            4.92
jdber1                           1             2              2            0.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Eugene Huang                  2            0.4         25.6                0.00
eugenevorld               18850           26.6          8.4                3.03
eugenhu                      31           96.9          1.2                0.00
jdber1                     6023       301150.0         -0.0               99.97
```

**Comment by arfon** [comment]
> @openjournals/dev Can you check why our bot didn't run cloc on starting this pre-review? 

Not sure why that didn't work the first time.

> And also why it's flagging all those missing DOIs when the paper only has two citations.

The DOI checker just parses whatever is in the `paper.bib` file. This BibTeX file looks to have a whole bunch of entries that aren't being cited in the paper?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @kyleniemeyer as editor

**Comment by whedon** [comment]
@kyleniemeyer has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
whoops, somehow I missed @labarba's original invitation. I can take this, though anything experimental is a bit outside my wheelhouse...

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
Hi @jdber1, thanks for your interest in JOSS.

My first question is on how easy/hard it will be for others to review this software—will reviewers be limited to those with access to certain experimental equipment? If so, then I'll really need your help to find folks who can review.

**Comment by jdber1** [comment]
Hi @kyleniemeyer, it would probably be better for the reviewers to have an experimental setup, but it is not necessary. I can give you a list of people who I know have used OpenDrop v1 for their research. Do they need to be active on github to review? That might be a bit harder.

There are also test images for interfacial tension in tests/samples/images, and I can add test images for contact angle too, for those without experimental apparatus.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by kyleniemeyer** [comment]
Hi @jdber1, sorry for the delay and thanks for the info.

I think adding some test images, and setting up associated tests, is a great idea. I also welcome suggestions for reviewers! They don't have to be active on GitHub to be asked to review, though completing a review does require a GitHub account. I'm happy to reach out to folks via email. Feel free to give names here, or email me if you prefer.

**Comment by jdber1** [comment]
No problems at all @kyleniemeyer. Potential reviewers include:

Stuart Prescott -  [llimeht](https://github.com/llimeht)
Trent Parker - [tmpchem](https://github.com/tmpchem)
Marcus Hanwell- [cryos](https://github.com/cryos)
Palli Thordarson - contact details [here](http://www.chemistry.unsw.edu.au/research/research-groups/thordarson-group)
Jan Vermant - contact details [here](https://mavt.ethz.ch/the-department/people/person-detail.MjAzNTI5.TGlzdC8xMzc1LC02OTM2MTkzMA==.html)

I will also get some test images so that the reviewers can use the software without experimental apparatus.

**Comment by arfon** [comment]
:wave: @kyleniemeyer - just a friendly reminder to try and organize some reviewers here.

**Comment by kyleniemeyer** [comment]
Hi @llimeht @tmpchem and @cryos, would any of you be interested in reviewing this submission for JOSS?

I'm not sure if you've all reviewed for JOSS before (or recently), but we carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The package we would ask you to review is ["OpenDrop: Open-source software for pendant drop tensiometry & contact angle measurements"](https://github.com/jdber1/opendrop) and there is a [short associated paper](https://github.com/openjournals/joss-papers/blob/joss.02128/joss.02128/10.21105.joss.02128.pdf) to read too.

Thanks!

**Comment by jdber1** [comment]
Hi @kyleniemeyer, any progress on finding reviewers?
Happy to suggest alternatives if necessary.

**Comment by kyleniemeyer** [comment]
@jdber1 I still have two more to reach out to, will try and get back to you.

**Comment by cryos** [comment]
Apologies, I missed this the first time. I should be able to get to this on the weekend. Sorry about the delayed response, got behind on some of my mail folders.

**Comment by kyleniemeyer** [comment]
@cryos Thanks! I'll add you as a reviewer.

**Comment by kyleniemeyer** [comment]
@whedon add @cryos as reviewer

**Comment by whedon** [comment]
OK, @cryos is now a reviewer

**Comment by llimeht** [comment]
I love (and use) this software but would have to decline to review it due to a conflict of interest. Thanks for thinking of me though.

**Comment by kyleniemeyer** [comment]
Hi @jdber1, do you have any other reviewer recommendations?

**Comment by jdber1** [comment]
HI @kyleniemeyer, you could try Pat Spicer (details[ here](http://nonequilibrium.com/)).

**Comment by kyleniemeyer** [comment]
Sorry @jdber1, still working on this. I have not gotten any responses to my emailed requests to review.

**Comment by kthyng** [comment]
@kyleniemeyer Just a ping here to keep moving this along!

**Comment by kyleniemeyer** [comment]
Hi @jdber1, sorry for letting this slide. Part of the problem is none of the folks I emailed to review ever responded... additional suggestions would be welcome, but I will also seek out another from the JOSS reviewer pool (we need two reviewers).

**Comment by kyleniemeyer** [comment]
Hi @rajeshrinet and @abhishekbajpayee, would either of you be interested (and available) to review this submission? Thanks!

**Comment by rajeshrinet** [comment]
Hi @kyleniemeyer, yes, I would be happy to review this submission.

**Comment by kyleniemeyer** [comment]
@whedon add @rajeshrinet as reviewer

Thanks so much @rajeshrinet!

**Comment by whedon** [comment]
OK, @rajeshrinet is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2604.

**Comment by kyleniemeyer** [comment]
OK, after a long delay, @jdber1 , @cryos , and @rajeshrinet , I have now started the actual review issue in #2604. See you over there!
