### ISSUE TITLE
[PRE REVIEW]: LTRpred: de novo annotation of intact retrotransposons

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2129]
**Submitting author:** @HajkD (<a href="http://orcid.org/0000-0002-1567-306X">Hajk-Georg Drost</a>)
**Repository:** <a href="https://github.com/HajkD/LTRpred" target ="_blank">https://github.com/HajkD/LTRpred</a>
**Version:** v1.1.0
**Editor:** @lpantano
**Reviewers:** @dcassol
**Managing EiC:** Lorena A Barba

**Author instructions**

Thanks for submitting your paper to JOSS @HajkD. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @karthik.

@HajkD if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02129/joss.02129/10.21105.joss.02129.pdf)

**Comment by labarba** [comment]
👋  @karthik — The authors suggested you as editor for this submission. According to the README: "LTRpred will take any genome assembly file in fasta format as input and will generate a detailed annotation of functional and potentially mobile LTR retrotransposons." It's an R package. Can you handle it?

**Comment by HajkD** [comment]
Dear @labarba 

Thank you so much for arranging the editorial assignment.

After going through the [reviewer list](https://bit.ly/joss-reviewers), I think the following reviewers could be very suitable: rachelss and dcassol .

I very much look forward to receiving some feedback.

Many thanks!

**Comment by arfon** [comment]
@whedon invite @karthik as editor

**Comment by whedon** [comment]
@karthik has been invited to edit this submission.

**Comment by karthik** [comment]
I'm unable to take this on. Is there another editor who can handle this?

**Comment by HajkD** [comment]
Dear @karthik 
Many thanks for your prompt reply.

Dear @arfon and @labarba 
Would it be possible to assign a different editor? There is no preference from my side
since all of them are very much suitable.

Thank you very much!

**Comment by arfon** [comment]
@Kevin-Mattheus-Moerman is the EiC on rotation this week so will be handling this.

**Comment by Kevin-Mattheus-Moerman** [comment]
@lpantano @will-rowe @csoneson can one of you edit this submission?

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
@dcassol, would you like to review this tool about LTRpred: de novo annotation of intact retrotransposons?

**Comment by lpantano** [comment]
@oushujun, would you like to review this tool about de novo annotation of intact retrotransposons?

**Comment by dcassol** [comment]
Sure!

**Comment by lpantano** [comment]
@whedon assign @dcassol as reviewer

**Comment by whedon** [comment]
OK, @dcassol is now a reviewer

**Comment by oushujun** [comment]
@ipantano Hello I don't know what this is for but seems interesting. Unfortunately I don't have open times until Mar. 25.

**Comment by lpantano** [comment]
Thanks @oushujun, do you know somebody who could be a reviewer for this tool? JOSS makes its reviewing process through github, and it is a very nice experience in general.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by lpantano** [comment]
@whedon invite @MatthewHaas as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by lpantano** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by lpantano** [comment]
Hi  @MatthewHaas, this tool may be interesting to you. Would you like to review this tool for Journal of Open Source Software? Cheers

**Comment by arfon** [comment]
> `@whedon invite @MatthewHaas as reviewer`

@lpantano - I'm afraid Whedon doesn't know how to do this yet for reviewers.

**Comment by lpantano** [comment]
@oushujun, since we didn't find any additional reviewer available, would you like to do it since we reached the date you may be free for this? Thanks!

**Comment by oushujun** [comment]
Sorry, it seems not likely before April, lots of things being piled up
during my travel.

Shujun

**Comment by lpantano** [comment]
Hi @rachelss, would you like to review this tool?

**Comment by lpantano** [comment]
Hi @HajkD, I will start the review meanwhile looking for the second reviewer. Thanks!

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2170.

**Comment by HajkD** [comment]
Hi @lpantano 

Thank you very much for arranging everything and for taking over the role of the second reviewer for now! I very much appreciate it!

**Comment by rachelss** [comment]
Sorry I just saw this notification by email. Looks from the other issue that you found a second reviewer.
