### ISSUE TITLE
[PRE REVIEW]: OSMnx: A Python package to work with graph-theoretic OpenStreetMap street networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#213]
**Submitting author:** gboeing (<a href="http://orcid.org/0000-0003-1851-6411">Geoff Boeing</a>)
**Repository:** <a href="https://github.com/gboeing/osmnx/" target ="_blank">https://github.com/gboeing/osmnx/</a>
**Version:** v0.4
**Editor:** @arokem
**Reviewer:** @rdottle

**What this issue is for**

Thanks for submitting your paper to JOSS gboeing. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arokem** [comment]
:hand: I'd like to edit this

**Comment by arokem** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by arokem** [comment]
@rdottle : would you like to review this software paper for JOSS?

**Comment by rdottle** [comment]
@arokem I would love to review, looks really interesting. What's the timeline, and how should I format comments/review output? Thanks!

**Comment by arokem** [comment]
Awesome! Thank you.

Take a look at the guidelines for reviewers here: http://joss.theoj.org/about#reviewer_guidelines

I will start the review on another issue, where there will be a check-list for you to go through, to make sure that the software meets all the requirements for publication. If there are items on the checklist that are not currently met by the software, post an issue on the software project's Github repo. When everything is place, give me the 👍  on the review issue.

As for timeline -- if you can review this within 2 weeks or so, that would be great. Let me know if you think it will take much longer than that.

**Comment by arokem** [comment]
@whedon assign @rdottle as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rdottle

**Comment by arokem** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/215. Feel free to close this issue now!

**Comment by arokem** [comment]
OK - @rdottle - head on over to #215 for the review! Thanks again!
