### ISSUE TITLE
[PRE REVIEW]: Matching: A Python library for solving matching games

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2130]
**Submitting author:** @daffidwilde (<a href="http://orcid.org/0000-0002-3788-7691">Henry Wilde</a>)
**Repository:** <a href="https://github.com/daffidwilde/matching" target ="_blank">https://github.com/daffidwilde/matching</a>
**Version:** v1.2.1
**Editor:** @VivianePons
**Reviewers:** @igarizio, @mbdemoraes
**Managing EiC:** Lorena A Barba

**Author instructions**

Thanks for submitting your paper to JOSS @daffidwilde. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @VivianePons.

@daffidwilde if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.23 s (545.1 files/s, 72398.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                             17              0              0           6975
Python                          43           1218            842           2667
reStructuredText                34            344            222            719
TeX                             18            157             50            655
Jupyter Notebook                 8              0           2285            388
Markdown                         1             21              0            110
YAML                             4              8              0             53
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                           126           1752           3405          11577
-------------------------------------------------------------------------------


Statistical information for the repository '2130' was gathered on 2020/03/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Henry Wilde                     44          7463           2667          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Henry Wilde                4727           63.3          8.5               10.70
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.jda.2006.03.006 is OK
- 10.1257/aer.p20171112 is OK
- 10.1109/MSP.2016.2598848 is OK
- 10.1007/s10479-017-2710-1 is OK
- 10.1016/0196-6774(85)90033-1 is OK
- 10.2307/2312726 is OK
- 10.12688/f1000research.11407.1 is OK
- 10.5281/zenodo.3691470 is OK
- 10.1006/game.1995.1006 is OK
- 10.1086/261272 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02130/joss.02130/10.21105.joss.02130.pdf)

**Comment by labarba** [comment]
👋  @VivianePons — The authors suggested you as handling editor for this submission. It's a package for solving matching games: games with two sets of players, where each player in one set has a ranked preference list of those in the other, and the objective is to find some mapping between the two sets such that no pair of players are unhappy.

Could you handle it?

**Comment by VivianePons** [comment]
@whedon assign @VivianePons as reviewer

**Comment by VivianePons** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by VivianePons** [comment]
Sure!

**Comment by daffidwilde** [comment]
👋  Hello all

> if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @).

Looking at the list of reviewers provided, my suggestions are:

- `igarizio`
- `VarIr`
- `fil`
- `amcasari`

I hope this helps!

**Comment by VivianePons** [comment]
@whedon assign igarizio as reviewer

**Comment by whedon** [comment]
OK, igarizio is now a reviewer

**Comment by VivianePons** [comment]
@wheon assign @igarizio as reviewer

**Comment by VivianePons** [comment]
@whedon assign @igarizio as reviewer

**Comment by whedon** [comment]
OK, @igarizio is now a reviewer

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by mbdemoraes** [comment]
@VivianePons Hi! I don't know if you already have a second reviewer, but if not, I would like to volunteer to review this one, if possible.

**Comment by VivianePons** [comment]
@whedon add @mbdemoraes as reviewer

**Comment by whedon** [comment]
OK, @mbdemoraes is now a reviewer

**Comment by VivianePons** [comment]
Thanks a lot, that's perfect! I am launching the review: with the special conditions these days, we are in no hurry. Please start review when / if it's convenient for you, no pressure at all

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2169.
