### ISSUE TITLE
[PRE REVIEW]: City2BA: Tools for creating synthetic bundle adjustment problems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2131]
**Submitting author:** @tkonolige (<a href="http://orcid.org/0000-0002-5052-6479">Tristan Konolige</a>)
**Repository:** <a href="https://github.com/tkonolige/city2ba" target ="_blank">https://github.com/tkonolige/city2ba</a>
**Version:** v1.1.0
**Editor:** @poulson
**Reviewers:** @adi3, @breezykermo
**Managing EiC:** Lorena A Barba

**Author instructions**

Thanks for submitting your paper to JOSS @tkonolige. **Currently, there isn't an JOSS editor assigned** to your paper.

@tkonolige if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.05 s (278.9 files/s, 58303.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Rust                             8            298            375           2241
Markdown                         2             18              0             82
TOML                             1              2              0             34
TeX                              1              1              0             31
YAML                             1              2              0             26
JSON                             1              0              0             23
Dockerfile                       1              0              0              3
-------------------------------------------------------------------------------
SUM:                            15            321            375           2440
-------------------------------------------------------------------------------


Statistical information for the repository '2131' was gathered on 2020/03/01.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1007/978-3-319-10578-9_5 may be missing for title: Robust global translations with 1DSFM
- https://doi.org/10.1109/iccv.2013.122 may be missing for title: Street view motion-from-structure-from-motion

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02131/joss.02131/10.21105.joss.02131.pdf)

**Comment by labarba** [comment]
👋  @poulson — This submission falls in the general field of computer vision, where we don't have any topic editors. It runs a global nonlinear optimization to minimize the error between the projected location of 3D points in each camera and the actual observed location of the point in the camera frames. Could you handle it as editor?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @poulson as editor

**Comment by whedon** [comment]
@poulson has been invited to edit this submission.

**Comment by danielskatz** [comment]
👋 @poulson - just a reminder/ping...

**Comment by poulson** [comment]
@whedon set @poulson as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by poulson** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by poulson** [comment]
@whedon assign @poulson as editor

**Comment by whedon** [comment]
OK, the editor is @poulson

**Comment by poulson** [comment]
Hi Sameer :wave: (@sandwichmaker) -- would you mind serving as one of the reviewers for this paper? It cites some of your work and it seems you would have some useful feedback for them.

**Comment by poulson** [comment]
Hi @fiveop :wave: -- given your preferred language of Rust, would you feel comfortable serving as one of the reviewers of this paper on a Rust software package for generating datasets for bundle adjustment problems?

**Comment by poulson** [comment]
Hi @fhorrobin :wave: -- given that you mentioned Rust as one of your preferred languages, and your stated interest in statistical modeling, would you be interested and able to serve as one of the reviewers for this submission on a Rust package for generating datasets for bundle adjustment problems?

**Comment by sandwichmaker** [comment]
@poulson is there a pdf here somewhere? if its rust code, I have no rust knowledge.

**Comment by tkonolige** [comment]
@sandwichmaker The pdf is here: https://github.com/openjournals/joss-papers/blob/joss.02131/joss.02131/10.21105.joss.02131.pdf

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arfon** [comment]
:wave: @poulson - just a friendly reminder that we still need to identify some reviewers for this submission.

**Comment by arfon** [comment]
:wave: @poulson - do you think you could work on identifying some reviewers for this submission soon?

**Comment by poulson** [comment]
Hi Fergus (@fhorrobin) :wave: -- given that you have listed Rust as one of your preferred programming language, as well as expertise in statistical methods and solid body dynamics, you appear to be one of the most qualified reviewers in our list. I'm fully aware that now is a very unstable time, and you could likely be overwhelmed, but please let me know if you would have the time to review this submission, as it has been on hold for a few months.

Hi Sameer (@sandwichmaker) :wave: -- given the PDF and, if we get a Rust specialist as a reviewer, would you feel comfortable reviewing the mathematics and methodology of this submission?

**Comment by poulson** [comment]
Hi Conrad (@conradsnicta) :wave: -- You've expressed interest in reviewing JOSS submissions and have listed both computer vision as one of your specialties. While the submission is in Rust, would you feel comfortable helping to review this submission?

**Comment by poulson** [comment]
Hi Valentin (@vchuravy) :wave: -- Like Conrad, you have maked computer vision as one of your specialties and listed a primary language that is different from this submision's (Julia vs. Rust). Would you feel comfortable helping to review this submission on bundle adjustment in Rust?

**Comment by poulson** [comment]
Hi Abhishek (@abhishekbajpayee) :wave: -- You have mentioned computer vision as one of your specialties and have listed both Python and C++ as preferred programming languages. Would you feel comfortable reviewing this submission on bundle adjustment problems in Rust?

**Comment by poulson** [comment]
Hi Tristan (@tkonolige) :wave: -- As you can see, we are having issues with reviewer and editor capacity for obvious reasons. Are there any reviewers that you would recommend as being capable, impartial, and responsive for this submission?

**Comment by conradsnicta** [comment]
@poulson Apologies for the late response. Been very busy.  Based on the contents of the paper draft, I currently don't have sufficient knowledge in the applicable areas (SfM and SLAM).

**Comment by tkonolige** [comment]
@poulson I'm new to the joss community, so I don't know anyone who make a good reviewer.

**Comment by vchuravy** [comment]
@poulson Since both BA and Rust are outside of my expertise I don't think I would make a good reviewer.

**Comment by poulson** [comment]
Hi Mathieu :wave:  (@matbesancon) -- I hate to repeatedly request you as a reviewer, but, as you can see, we've been having issues finding reviewers who are comfortable with both Rust and reviewing a bundle adjustment project. You list both Rust and a combination of optimization and statistics in your expertise and are one of the better first. Would you happen to be interested and able to help review this submission?

**Comment by poulson** [comment]
Hi Lachlan :wave: (@breezykermo) -- Given your listed expertise in Rust and computer graphics, you appear to be one of the few potential reviewers who fits the bill for this Rust Bundle Adjustment submission. Would you be interested and able to help review this submission?

**Comment by breezykermo** [comment]
Hi @poulson; although I do not have any expertise in BA, I would be happy to help review if you think it would be useful. What exactly would a review require from me? I have not reviewed or contributed through JOSS yet. :)

**Comment by kthyng** [comment]
Hi @breezykermo! I am the rotating associate editor in chief this week so I can help with your question. JOSS reviews are done as a github issue (which will be opened separately from this pre-review issue). They are checklist-driven, and you can get more information on the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. We basically want reviewers to use the software as a new user from installation, going through docs, and verifying it works as it says it should. Issues and comments that come up should be documented as issues on the software repository and linked to the review issue by mentioning it inline. 

Let me know if you have any other questions!

**Comment by kthyng** [comment]
> @poulson I'm new to the joss community, so I don't know anyone who make a good reviewer.

@tkonolige as you can see, @poulson is having a hard time finding reviewers for your submission. I wouldn't say that any familiarity with the JOSS community is needed to suggest reviewers, just like it isn't for a traditional academic paper. We provide a list of possible reviewers you can [peruse](https://bit.ly/joss-reviewers) to see if anyone seems like a fit (if so, please list them here without using "@" so they aren't directly pinged). Or, perhaps you know people in your scientific community and network and can provide contact information for them, or ask them for potential reviewers.

**Comment by poulson** [comment]
Hi Lachlan (@breezykermo). Yes, what Kristen (@kthyng) said. Please let us know if you feel qualified to provide constructive feedback on the software and domain of this paper.

**Comment by adi3** [comment]
@poulson I work in robotics, and have experience with SLAM and bundle adjustments. I'd be happy to take this on. Let me know! I do not have hands-on experience in Rust, but can review the code against common best practices for software and documentation.

**Comment by breezykermo** [comment]
Sorry I haven't got around to this! Happy to hand to @adi3

**Comment by adi3** [comment]
@breezykermo since JOSS papers require 2 reviewers, I would suggest we both do it. I have reviewed for JOSS in the past and can guide you through the review process, although I think the documentation is already quite helpful with this.
@kthyng @poulson your call :)

**Comment by kthyng** [comment]
@breezykermo and @adi3 yes we do want to have two reviewers. Since @poulson is the handling editor, he'll need to decide, but thank you for your willingness to review in the meantime!

**Comment by arfon** [comment]
I agree it may be good to have @adi3 and @breezykermo take on the review here together. 

I just pinged @poulson to see if he can come and make a decision here about how to proceed.

**Comment by adi3** [comment]
@arfon it's more than a year since this submission has been in pre-review. Shall we perhaps get on with it?

**Comment by arfon** [comment]
@whedon add @adi3 as reviewer

**Comment by whedon** [comment]
OK, @adi3 is now a reviewer

**Comment by arfon** [comment]
@whedon add @breezykermo as reviewer

**Comment by whedon** [comment]
OK, @breezykermo is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3125.

**Comment by arfon** [comment]
@poulson - I've gone ahead and started this review with @adi3 & @breezykermo as the reviewers.
