### ISSUE TITLE
[PRE REVIEW]: pygen-structures: A Python package to generate 3D molecular structures for simulations using the CHARMM forcefield

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2132]
**Submitting author:** @thesketh (<a href="http://orcid.org/0000-0002-0502-9596">Travis Paul Hesketh</a>)
**Repository:** <a href="https://github.com/thesketh/pygen-structures" target ="_blank">https://github.com/thesketh/pygen-structures</a>
**Version:** v0.2.2
**Editor:** @richardjgowers
**Reviewers:** @dotsdl, @rmeli, @amandadumi
**Managing EiC:** Lorena A Barba

**Author instructions**

Thanks for submitting your paper to JOSS @thesketh. **Currently, there isn't an JOSS editor assigned** to your paper.

@thesketh if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.34 s (141.8 files/s, 58134.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       9           2200           2234           8325
Python                          16            335            613           2078
HTML                             7            338              0           1432
CSS                              4            312             49           1186
Markdown                         3             68              0            235
TeX                              1              9              0             80
reStructuredText                 4             33             48             37
DOS Batch                        1              8              1             26
YAML                             2              3              0             14
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            48           3310           2952          13422
-------------------------------------------------------------------------------


Statistical information for the repository '2132' was gathered on 2020/03/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Travis Hesketh                   7         17802           2017          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Travis Hesketh            15785           88.7          0.0               15.41
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1017/S0033583500003966 is OK
- 10.1002/jcc.23354 is OK
- 10.1021/acs.jcim.5b00654 is OK

MISSING DOIs

- https://doi.org/10.1016/0263-7855(96)00018-5 may be missing for title: VMD - Visual Molecular Dynamics

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02132/joss.02132/10.21105.joss.02132.pdf)

**Comment by labarba** [comment]
👋  @jedbrown — Could you handle this submission as editor? We don't have a topic editor in computational chemistry, but you know many folks in this area and could identify reviewers. Thanks!

**Comment by thesketh** [comment]
From a quick glance at the list of reviewers, RMeli and amandadumi seem to potentially be good reviewers as both have experience in computational chemistry. The DOI suggested for the VMD article seems correct, I'll make sure that I update it!

**Comment by jedbrown** [comment]
@whedon assign jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is jedbrown

**Comment by jedbrown** [comment]
@thesketh What is the status of `rdkit`? It fails for me. 
```
$ pip install rdkit
ERROR: Could not find a version that satisfies the requirement rdkit (from versions: none)
ERROR: No matching distribution found for rdkit
```
The `pygen_structures` wheel installs, but fails to import due to missing `rdkit`, which seems to be [very old](https://pypi.org/project/rdkit/#history).

**Comment by thesketh** [comment]
Unfortunately RDKit has to be installed using Conda because of their installation process. This is an issue with distributing code via different package managers I suppose - sorry about the lack of documentation to that effect, I'll make sure to add it to the README. The conda `environment.yml` in the project root is used by ReadTheDocs to build the documentation, so should be enough to build a minimal environment.

**Comment by thesketh** [comment]
I've updated README.md to reflect this information

**Comment by jedbrown** [comment]
Okay, I see there is a [thread](https://github.com/rdkit/rdkit/issues/1812) and [pull request](https://github.com/rdkit/rdkit/pull/2690) to make rdkit pip-installable.

I'm getting errors in running the tests, which appear to be due to this:

**Comment by thesketh** [comment]
For reasons unknown to me, when using Python 3.6 conda was not installing the latest version of the RDKit. I've updated the requirements and .travis.yml, so the builds for 3.6 are now passing. 

I was unable to fix a dependency problem with Python 3.8, so I've removed it from the supported versions. I'll reevaluate it when the next RDKit version is released.

**Comment by jedbrown** [comment]
@whedon assign @richardjgowers as editor

**Comment by whedon** [comment]
OK, the editor is @richardjgowers

**Comment by jedbrown** [comment]
Welcome our new editor, @richardjgowers, who has agreed to edit this submission. I'll continue to watch this issue (and the review thread once created) and will be able to help answer questions.

**Comment by richardjgowers** [comment]
@rmeli any chance you can look at this?

**Comment by richardjgowers** [comment]
@amandadumi would you be interested in reviewing this?

**Comment by richardjgowers** [comment]
@dotsdl are you interested in this?

**Comment by dotsdl** [comment]
@richardjgowers I am interested. I can allocate time to review later this week.

**Comment by RMeli** [comment]
@richardjgowers I can have a look by the end of the week or this weekend.

**Comment by amandadumi** [comment]
@richardjgowers I am interested. I will also have a look by this weekend.

**Comment by richardjgowers** [comment]
@whedon add @dotsdl as reviewer

**Comment by whedon** [comment]
OK, @dotsdl is now a reviewer

**Comment by richardjgowers** [comment]
@whedon add @rmeli as reviewer

**Comment by whedon** [comment]
OK, @rmeli is now a reviewer

**Comment by richardjgowers** [comment]
@whedon add @amandadumi as reviewer

**Comment by whedon** [comment]
OK, @amandadumi is now a reviewer

**Comment by richardjgowers** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2157.

**Comment by RMeli** [comment]
@arfon I noticed my name appears three times in the list of reviews. Would it be possible to remove the first two entries (entry 1127 is the most up-to-date)? Thanks.

**Comment by arfon** [comment]
> @arfon I noticed my name appears three times in the list of reviews. Would it be possible to remove the first two entries (entry 1127 is the most up-to-date)? Thanks.

Not sure I follow sorry?

**Comment by RMeli** [comment]
Sorry, I wasn't clear. My name (GitHub ID) appears three times in the [this list of people [that] have already agreed to review for JOSS](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822). I was wondering if the first two spurious entries could be removed.

**Comment by arfon** [comment]
> Sorry, I wasn't clear. My name (GitHub ID) appears three times in the this list of people [that] have already agreed to review for JOSS. I was wondering if the first two spurious entries could be removed to avoid confusion.

Done.
