### ISSUE TITLE
[PRE REVIEW]: VlaPy: A Python package for Eulerian Vlasov-Poisson-Fokker-Planck Simulations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2133]
**Submitting author:** @joglekara (<a href="http://orcid.org/0000-0003-3599-5629">Archis Joglekar</a>)
**Repository:** <a href="https://github.com/joglekara/VlaPy" target ="_blank">https://github.com/joglekara/VlaPy</a>
**Version:** v1.0
**Editor:** @dpsanders
**Reviewers:** @TomGoffrey, @StanczakDominik
**Managing EiC:** Lorena A Barba

**Author instructions**

Thanks for submitting your paper to JOSS @joglekara. **Currently, there isn't an JOSS editor assigned** to your paper.

@joglekara if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1103/PhysRevE.96.043208 is OK
- 10.1088/1361-6587/aab978 is OK
- 10.1103/PhysRev.112.1456 is OK
- 10.1016/0021-9991(73)90131-9 is OK
- 10.1088/0741-3335/41/3A/001 is OK
- 10.1016/S0010-4655(02)00451-4 is OK
- 10.5281/zenodo.1238132 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02133/joss.02133/10.21105.joss.02133.pdf)

**Comment by labarba** [comment]
👋 @katyhuff — Could you handle this submission as editor? It is a pure-Python solver for the Vlasov-Poisson-Fokker-Planck based on finite-difference and pseudo-spectral methods. Thanks!

**Comment by joglekara** [comment]
👋 all!

I am honored and excited to contribute.

Here are some potential reviewers I found from the Google Sheet:
TomGoffrey
StanczakDominik
ali-ramadhan

**Comment by Kevin-Mattheus-Moerman** [comment]
@katyhuff :point_up: are you able to help edit this submission?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @katyhuff as editor

**Comment by whedon** [comment]
@katyhuff has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@dpsanders would this be a nice first submisson to handle (@arfon) ?

**Comment by dpsanders** [comment]
Yes sure, would be happy to.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @dpsanders as editor

**Comment by whedon** [comment]
OK, the editor is @dpsanders

**Comment by dpsanders** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by dpsanders** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02133/joss.02133/10.21105.joss.02133.pdf)

**Comment by dpsanders** [comment]
👋 Hello @joglekara. Thanks for your submission to JOSS.

Looking over the repo, I notice that there is no (narrative) documentation. Could you please add documentation on the system being solved (as in the paper) and on how to use your implementation (API) before we proceed to review?  

I didn't quite understand the relation between this submission and PlasmaPy.

There's also a missing reference at the end of page 3 in the paper.

Thanks!

**Comment by dpsanders** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (468.4 files/s, 41532.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          15            291            224            655
Markdown                         2             69              0            129
TeX                              1              7              0            113
Jupyter Notebook                 1              0            233             82
YAML                             1              8             12             37
INI                              1              0              0              2
-------------------------------------------------------------------------------
SUM:                            21            375            469           1018
-------------------------------------------------------------------------------


Statistical information for the repository '2133' was gathered on 2020/03/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Archis Joglekar                 11          1893            754           97.75
archis                           4            46             15            2.25

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Archis Joglekar            1126           59.5          0.1                8.17
archis                       44           95.7          0.1                0.00
```

**Comment by dpsanders** [comment]
Also, there is only 1 contributor to the repo. Could you please comment about the fact that the paper has 2 authors?

**Comment by arfon** [comment]
@dpsanders @joglekara - I made a couple of minor readability improvements in https://github.com/joglekara/VlaPy/pull/6

**Comment by joglekara** [comment]
Hi @dpsanders , thanks for your comments. @arfon , thanks for the improvements.

Re: Docs and API: 
The API instructions are provided through a jupyter-notebook but we understand that it should be more obvious. We will add some more documentation about the equations being solved along with instructions on how to use the API. 

Re: PlasmaPy
This was partially motivated by the explicit mention by the PlasmaPy community of the need for this type of simulation code. There is no greater relationship than that at the present time. We intend to reach out to the PlasmaPy community to collect their feedback as this submission matures.

Re: Missing Reference
Good catch. This has been addressed in an on-going PR.

Re: 2nd Author
Matthew has helped provide high level guidance for the software and has helped write the manuscript.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by joglekara** [comment]
Hi @dpsanders , hope you are well at this time.

I've added documentation via ReadTheDocs as well as a quickstart guide to the README.md in the repo.

Looking forward to your feedback.

**Comment by dpsanders** [comment]
Hi @joglekara, 

I'm well thanks; I hope you are too.

Sorry for the delay in getting to this.
The documentation looks very nice, thanks for doing that. That will definitely make the package more appealing and usable.

I'll start looking for referees.

**Comment by dpsanders** [comment]
👋 Hi @StanczakDominik, @TomGoffrey and @CFGrote

I hope you are all doing OK in these difficult times.

If you have any spare bandwidth, would you be able to review this JOSS submission? Thanks!

**Comment by TomGoffrey** [comment]
I'd be happy to.

**Comment by dpsanders** [comment]
Great, thanks @TomGoffrey!

**Comment by whedon** [comment]
OK, @TomGoffrey is now a reviewer

**Comment by TomGoffrey** [comment]
@whedon  generate pdf

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by TomGoffrey** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by TomGoffrey** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02133/joss.02133/10.21105.joss.02133.pdf)

**Comment by StanczakDominik** [comment]
> 👋 Hi @StanczakDominik, @TomGoffrey and @CFGrote
> 
> I hope you are all doing OK in these difficult times.
> 
> If you have any spare bandwidth, would you be able to review this JOSS submission? Thanks!
> 

Wow, sure! It is my first time reviewing (hyped!) and I'd like to make sure I do a good job of it; what are the time frames like? Is it fine if I take a few days to really dig into it?

**Comment by dpsanders** [comment]
@StanczakDominik Great! Yes of course, please do.

**Comment by StanczakDominik** [comment]
Going through the comments section I see mentions of PlasmaPy. As a on-off maintainer of that package, which I'd describe as "still very smol" - that's a surprise, to be sure, but a welcome one. I don't know if that makes for any sort of conflict of interest, though? I'd be happy to do my best to review this package on a completely stand alone basis.

**Comment by dpsanders** [comment]
I don't see that as a conflict of interest, no. On the contrary @joglekara seems to be interested in having contact with that community.

**Comment by StanczakDominik** [comment]
Awesome, I'll get to it, then :)

**Comment by joglekara** [comment]
@dpsanders : No problem about the delay at all. The times have not been kind to most this year so thanks a bunch for taking time to get this started.

@StanczakDominik : Appreciate your enthusiasm! @dpsanders is right in that I'm interested in further connecting with PlasmaPy. I think it'd be great to be able to put that package on firm ground. 

Also, @TomGoffrey, @StanczakDominik , nice to e-meet you 👋

**Comment by StanczakDominik** [comment]
@whedon add @StanczakDominik as reviewer

**Comment by whedon** [comment]
I'm sorry @StanczakDominik, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by StanczakDominik** [comment]
Right, @dpsanders, may I ask you to run that command? :smiley:

**Comment by dpsanders** [comment]
Ah, sorry, of course

**Comment by dpsanders** [comment]
@whedon add @StanczakDominik as reviewer

**Comment by whedon** [comment]
OK, @StanczakDominik is now a reviewer

**Comment by StanczakDominik** [comment]
Thanks, both of you! #EqualityForBots

**Comment by arfon** [comment]
@dpsanders - this looks like it's ready to move to review unless I'm missing something?

**Comment by StanczakDominik** [comment]
I've started submitting issues in the main repo's tracker as part of that review. It's sort of ongoing, though I don't know the procedures here yet.

**Comment by dpsanders** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2182.

**Comment by dpsanders** [comment]
Sorry for the delay in getting to this. Thanks @arfon, I had been waiting to see if we could get another reviewer.
