### ISSUE TITLE
[REVIEW]: hypr: An R package for hypothesis-driven contrast coding

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2134]
**Submitting author:** @mmrabe (<a href="http://orcid.org/0000-0002-2556-5644">Maximilian Rabe</a>)
**Repository:** <a href="https://github.com/mmrabe/hypr" target ="_blank">https://github.com/mmrabe/hypr</a>
**Version:** v0.1.7
**Editor:** @marcosvital
**Reviewer:** @tomfaulkenberry, @JonathanReardon
**Archive:** <a href="https://doi.org/10.5281/zenodo.3765843" target="_blank">10.5281/zenodo.3765843</a>

## Status

[![status](https://joss.theoj.org/papers/866129b28b619712fa28bbc10bef37c6/status.svg)](https://joss.theoj.org/papers/866129b28b619712fa28bbc10bef37c6)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/866129b28b619712fa28bbc10bef37c6"><img src="https://joss.theoj.org/papers/866129b28b619712fa28bbc10bef37c6/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/866129b28b619712fa28bbc10bef37c6/status.svg)](https://joss.theoj.org/papers/866129b28b619712fa28bbc10bef37c6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mmrabe/hypr" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@tomfaulkenberry  & @JonathanReardon, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @marcosvital know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mmrabe/hypr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mmrabe) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mmrabe/hypr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mmrabe) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @tomfaulkenberry , @JonathanReardon it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.jml.2019.104038 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02134/joss.02134/10.21105.joss.02134.pdf)

**Comment by marcosvital** [comment]
Dear @tomfaulkenberry and @JonathanReardon, thank you very much for accepting review this submission for JOSS.

Please check the instructions and checklists above, and let me know if you need any assistance. You can also tag @mmrabe  if you need to ask specific questions about the submission.

**Comment by JonathanReardon** [comment]
Hello, I can't seem to access the checklist at all (unable to tick any boxes), could you look into this for me? apologies if it's a fault my end.

**Comment by marcosvital** [comment]
Hi, @JonathanReardon, no need to apologize!

In order to be able to tick the boxes, you need to accept the invite as a collaborator on the joss-reviews repository - GitHub should have sent you an invite. This is easily missed depending on how you handle notifications from GitHub, so I'll send you another one.

@whedon re-invite @JonathanReardon as reviewer

Let me know if this works, ok?

**Comment by JonathanReardon** [comment]
Thanks @marcosvital, I see the invite at the top (I missed that before), though I think it has now expired.

"Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account"

Could you reset that perhaps? I didn't get any email with an invite, I just noticed the invite at the top of this page.

**Comment by marcosvital** [comment]
Yes, I can try to reset it, the command I gave Whedon should have done the trick, but I think it didn't work. I'll try again:

**Comment by marcosvital** [comment]
@whedon re-invite @JonathanReardon as reviewer

**Comment by whedon** [comment]
Sorry, I couldn't re-invite @jonathanreardon.

**Comment by marcosvital** [comment]
Didn't work... I'll ask for help with the editor team and will come back here soon, ok?

**Comment by danielskatz** [comment]
👋 @openjournals/dev - another case where this doesn't seem to work

**Comment by danielskatz** [comment]
And @marcosvital - FYI, any command to @whedon has to be the start of a comment, not later in the comment (but this isn't the main problem here)

**Comment by marcosvital** [comment]
> 
> 
> And @marcosvital - FYI, any command to @whedon has to be the start of a comment, not later in the comment (but this isn't the main problem here)

Thanks, @danielskatz! I imagined that after my first attempt, as Whedon didn't respond anything.

**Comment by JonathanReardon** [comment]
All good now, I got the invite! Thank you @marcosvital and @danielskatz

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by tomfaulkenberry** [comment]
I have (finally) completed my review of this paper/package.  It is a very nice package, and will be immediately useful as a tool for psychologists who want to translate the (sometimes unfamiliar) R method of specifying contrasts to the way that we are usually taught to specify contrasts.

I left two boxes unchecked in my review above: (1) there is no license in the Github repo, and (2) there is no statement of how people can contribute.  These should be easy to fix.  

Functionally, the package installed easily (even on my half-broken installation of R), and the functions did exactly what they were supposed to.

Overall, nice package, and good paper.

Tom

**Comment by JonathanReardon** [comment]
I too have now finished the review, apologies for the delay, and thank you to all for being understanding. This was a very simple tool to install and use, it worked exactly as intended and behaved exactly as described. No issues at all.

If you could include a license and a brief statement as to how others can contribute to the project, that would be great. I (and @tomfaulkenberry) could then tick off the remaining 2 boxes.

Nice paper and useful tool that I am sure many psychologists would be interested in using. 

Thanks all,
Jonathan

**Comment by mmrabe** [comment]
@tomfaulkenberry and @JonathanReardon, thank you both very much for taking the time to review the package and paper and of course for your wonderful feedback! @marcosvital, I hope it’s okay that I went ahead and made the changes to the repository.

I added a “Community guidelines” paragraph to the end of the [README](https://github.com/mmrabe/hypr/blob/master/README.md) file and a [LICENSE](https://github.com/mmrabe/hypr/blob/master/LICENSE) file (GPL-3) to the root directory. Some of these details can also be found in the [DESCRIPTION](https://github.com/mmrabe/hypr/blob/master/DESCRIPTION) meta file.

This was a great experience so far and I really enjoyed the interaction. I’m looking forward to hearing from you again.

Thanks a lot and stay safe!
Max

**Comment by tomfaulkenberry** [comment]
Great..thanks @mmrabe!  I have finished the checkmarks on my part, and I'm perfectly happy with the final result.

**Comment by JonathanReardon** [comment]
Thank you @mmrabe, and congrats on the project! Just ticked off the final two boxes, cheers all.

**Comment by marcosvital** [comment]
Hi, @mmrabe! Sorry about the delayed reply. Since all the reviewers are satisfied, we can carry on.

@JonathanReardon and @tomfaulkenberry , thank you very much for the time and effort put into this review!

@mmrabe, I'll trigger a DOI checking, so we can see if there are any corrections to be done on the references, ok?

**Comment by marcosvital** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.jml.2019.104038 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by marcosvital** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02134/joss.02134/10.21105.joss.02134.pdf)

**Comment by marcosvital** [comment]
@mmrabe, everything is ok with cited DOIs.

I generated a new proof, so you can take a carefull (maybe final?) look at the manuscript. I'll read it myself too, and will let you know if I find any issues, ok?

**Comment by mmrabe** [comment]
@marcosvital, thank you very much! Sorry for the late response. My coauthors and I have had another look at the manuscript and have found no further issues.

**Comment by marcosvital** [comment]
Hi, @mmrabe! Sorry about the late reply. Let's move on, everything looks fine with the manuscript.

As one of our last steps, if you already didn't do this, you will need to archive the last release of the package (on Zenodo, figshare, or other of your choice). After that, post the version number and archive DOI here, and we can continue.

**Comment by mmrabe** [comment]
Hi @marcosvital! Thanks! I just archived the package using Zenodo. The current version number is v0.1.7 (was v0.1.6 upon submission) and the Zenodo DOI is: 10.5281/zenodo.3765843

**Comment by marcosvital** [comment]
@whedon set 10.5281/zenodo.3765843 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3765843" target="_blank">10.5281/zenodo.3765843</a> is the archive.

**Comment by marcosvital** [comment]
@whedon set v0.1.7 as version

**Comment by whedon** [comment]
OK. v0.1.7 is the version.

**Comment by marcosvital** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.jml.2019.104038 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1434

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1434, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
Thanks - I'll take this from here

**Comment by danielskatz** [comment]
👋 @mmrabe - please update the metadata in the Zenodo archive, specifically the title, to match the JOSS paper

**Comment by mmrabe** [comment]
Thanks for pointing that out, @danielskatz. I have now updated the title in Zenodo.

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1254769396632993792) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1435
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02134](https://doi.org/10.21105/joss.02134)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
We're now waiting for the DOI to work - everything else seems ok

**Comment by danielskatz** [comment]
Thanks to @tomfaulkenberry & @JonathanReardon for reviewing, and @marcosvital for editing!

And congratulations to @mmrabe (Maximilian Rabe) and co-authors!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02134/status.svg)](https://doi.org/10.21105/joss.02134)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02134">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02134/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02134/status.svg
   :target: https://doi.org/10.21105/joss.02134
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02134/status.svg)](https://doi.org/10.21105/joss.02134)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
