### ISSUE TITLE
[REVIEW]: audiomate: A Python package for working with audio datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2135]
**Submitting author:** @ynop (<a href="http://orcid.org/0000-0003-0207-5711">Matthias Büchi</a>)
**Repository:** <a href="https://github.com/ynop/audiomate" target ="_blank">https://github.com/ynop/audiomate</a>
**Version:** v6.0.0
**Editor:** @terrytangyuan
**Reviewer:** @mulhod, @faroit 
**Archive:** <a href="https://doi.org/10.5281/zenodo.3970567" target="_blank">10.5281/zenodo.3970567</a>

## Status

[![status](https://joss.theoj.org/papers/b3b6733b4649ded21f99c68ba7e091d5/status.svg)](https://joss.theoj.org/papers/b3b6733b4649ded21f99c68ba7e091d5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b3b6733b4649ded21f99c68ba7e091d5"><img src="https://joss.theoj.org/papers/b3b6733b4649ded21f99c68ba7e091d5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b3b6733b4649ded21f99c68ba7e091d5/status.svg)](https://joss.theoj.org/papers/b3b6733b4649ded21f99c68ba7e091d5)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ynop/audiomate" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mulhod  & @faroit , please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @terrytangyuan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ynop/audiomate">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ynop) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ynop/audiomate">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ynop) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [X] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [X] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mulhod , @faroit  it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1109/icassp.2015.7178964 may be missing for title: Librispeech: An ASR corpus based on public domain audio books

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02135/joss.02135/10.21105.joss.02135.pdf)

**Comment by mulhod** [comment]
Created issue about sox dependency: https://github.com/ynop/audiomate/issues/101

**Comment by mulhod** [comment]
Created issue about python 3.8 issues: https://github.com/ynop/audiomate/issues/102

**Comment by mulhod** [comment]
Create issue about benchmark test failure: https://github.com/ynop/audiomate/issues/109

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by faroit** [comment]
Sorry for the delay. Things are a bit rough over here in 🇫🇷 . I will hopefully able to provide a review by next week.

**Comment by faroit** [comment]
I am now back on the review. Thanks for your patience

**Comment by faroit** [comment]
`audiomate` is a python based package that addresses the extraction, transformation and loading of audio datasets.
It comes with a large list of available datasets and many of them can be automatically downloaded from within python. The package is very well done and is excellently documented. It offers great value for the scientific audio community.

## Concerns
I added a few concerns in the issues opened by me. Most of them are minor can quickly be addressed or have already been addressed by the authors. 

However, I have two main concerns that I would ask the authors to address before this paper gets accepted:

## Related software tools

The paper does not mention related software packages. In such section other tool would be listed and compared to `audiomate`.  Key differences would be highlighted as well as unique features  that emphasise the contributions in `audiomate`. Here are a few packages that are related:

### Audio related software
* https://github.com/juliagusak/dataloaders
* https://github.com/mir-dataset-loaders/mirdata
* https://github.com/mcfletch/audiodatasets
* https://pytorch.org/audio/datasets.html
* https://github.com/mpariente/asteroid

### Non-Audio related software
* https://pytorch.org/docs/stable/torchvision/datasets.html
* https://github.com/tensorflow/datasets

## Reproducibility

In [issue 126](https://github.com/ynop/audiomate/issues/126) I brought up reproducibility issued with audiomate. Compared to other software packages such as [mirdata](https://github.com/mir-dataset-loaders/mirdata) or [torchvision.datasets](https://pytorch.org/docs/stable/torchvision/datasets.html), `audiomate` does not come with mechanisms to allow users to reproduce dataset downloads. Often there are two ways to foster this:

* __verification__: making sure that a downloaded dataset matches a reference file. This is usually verified through the use of checksums/hashes in other packages.
* __versioning__: making sure that a downloaded dataset is the same when being downloaded at later times. This is usually archived by referring to specific tags (e.g. on github repos) or unique identifiers (e.g. DOIs on zenodo). 

Both features are not covered by `audiomate` and I would highly suggest to incorporate at least __versioning__ into the software. E.g. this could easily be implemented by the authors by changing links from `master` branches of repos to specific commits/tags.

## Recommendation

For this paper being accepted in JOSS, I would suggest make these changes regarding a related work section in the paper and versioning the dataset downloads. However, I am happy to discuss this issues here with authors and other reviewers and I leave the final decision for @terrytangyuan

**Comment by arfon** [comment]
Thanks @faroit! @ynop - please let us know when you've had a chance to make changes in response to @faroit's review.

**Comment by ynop** [comment]
Hi @faroit, thanks for your review. 

Regarding reproducibility I completely agree with you, that versioning and verification would be cool. But this is a lot of work and I am not sure if we can do that in the near future. The only change that is possible with reasonable effort is using fixed commits for git-based datasets. The problem with that is that you have to update audiomate, every time a new version is released (and know that there is a new version). Furthermore, a user can fix the version of such datasets on her/his own by passing the specific url to the downloader.

Regarding related software, I will add a section in the paper.

**Comment by faroit** [comment]
> The only change that is possible with reasonable effort is using fixed commits for git-based datasets. 
> The problem with that is that you have to update audiomate, every time a new version is released (and know that there is a new version). 

I think there is no way around this. Given how less frequent datasets are actually updated the workload is quite small, also I would say that reproducibility is more important for researchers than having the most recent version of the a dataset these . Then, this would currently only affect 3 datasets in audiomate, so this change would be rather quick, I guess.

> Furthermore, a user can fix the version of such datasets on her/his own by passing the specific url to the downloader.

Maybe have a look at [torch.hub](https://pytorch.org/docs/stable/hub.html#torch.hub.load) to implement a similar repo/tag scheme?

**Comment by ynop** [comment]
Another thought: What happens If we update the version in audiomate. The user either has to keep working with the old audiomate version (and fix it) or use a custom download URL afterwards. I am not sure if it is a good approach to have the dataset versions depend on the software version, since this is not really transparent to the user.

**Comment by faroit** [comment]
@ynop 

> what happens If we update the version in audiomate. The user either has to keep working with the old audiomate version (and fix it) or use a custom download URL afterwards. I am not sure if it is a good approach to have the dataset versions depend on the software version, since this is not really transparent to the user.

I did a bit of research and I found that most libraries actually do not support a good way to version the dataset. In many cases, the dataset is just verified with a checksum, so when a dataset is changed, the checksum fails. 

A detailed solution is proposed by the [tensorflow tfds team](https://github.com/tensorflow/datasets/blob/master/docs/datasets_versioning.md). Basically they followed your idea to implement versions for each dataset. Now I agree that this is significant amount of work, so I agree to take this out of the JOSS review.

**Comment by arfon** [comment]
> Now I agree that this is significant amount of work, so I agree to take this out of the JOSS review.

Thanks @faroit. Could you check on @ynop's most recent updates to see if you're able to check off the last few checkboxes for your review?

**Comment by faroit** [comment]
@arfon as far as I can see, there has not been any changes made to the paper.

**Comment by aahlenst** [comment]
Sorry, it's stuck on my desk. Swamped with work. Should get better next week.

**Comment by ynop** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02135/joss.02135/10.21105.joss.02135.pdf)

**Comment by ynop** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02135/joss.02135/10.21105.joss.02135.pdf)

**Comment by ynop** [comment]
@faroit We added a section about related work.

**Comment by faroit** [comment]
> @faroit We added a section about related work.

Great. I made three comments on the changes: 

* https://github.com/ynop/audiomate/commit/31203e4817be1626f3266aa5eab3cc6bcf811bd8#r40297165
* https://github.com/ynop/audiomate/commit/31203e4817be1626f3266aa5eab3cc6bcf811bd8#r40297291
* https://github.com/ynop/audiomate/commit/31203e4817be1626f3266aa5eab3cc6bcf811bd8#commitcomment-40297261

can you address these?

**Comment by ynop** [comment]
@whedon generate pdf
@faroit We reference numpy in the second example now.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02135/joss.02135/10.21105.joss.02135.pdf)

**Comment by faroit** [comment]
> @faroit We reference numpy in the second example now.

Looks good

**Comment by faroit** [comment]
@arfon all checked from my side. 👍

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1109/icassp.2015.7178964 may be missing for title: Librispeech: An ASR corpus based on public domain audio books
- https://doi.org/10.1016/b978-0-08-099388-1.00019-4 may be missing for title: Audio Datasets

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@ynop - could you take a look at the suggested DOIs above from Whedon? If they're correct, then please add them to your BibTeX file with entries like this: `doi=10.1109/icassp.2015.7178964`

**Comment by ynop** [comment]
@whedon generate pdf
@whedon check references

**Comment by whedon** [comment]
PDF failed to compile for issue #2135 with the following error: 

 Error reading bibliography ./paper.bib (line 29, column 11):
unexpected "."
expecting letter, digit, white space, "#", "," or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by ynop** [comment]
@whedon generate pdf
@whedon check references

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02135/joss.02135/10.21105.joss.02135.pdf)

**Comment by ynop** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/icassp.2015.7178964 is OK

MISSING DOIs

- https://doi.org/10.1016/b978-0-08-099388-1.00019-4 may be missing for title: Audio Datasets

INVALID DOIs

- None
```

**Comment by ynop** [comment]
@arfon I added a missing one, the other one is a wrong.

**Comment by danielskatz** [comment]
as you've probably learned, whedon only see one command at a time, and only if it's the first thing in a comment

**Comment by terrytangyuan** [comment]
@whedon check references

**Comment by terrytangyuan** [comment]
@arfon It doesn't work on this review as well.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/icassp.2015.7178964 is OK

MISSING DOIs

- https://doi.org/10.1016/b978-0-08-099388-1.00019-4 may be missing for title: Audio Datasets

INVALID DOIs

- None
```

**Comment by terrytangyuan** [comment]
That missing DOI seems a false positive.

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by terrytangyuan** [comment]
@ynop At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:
- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors
I can then move forward with accepting the submission.

**Comment by ynop** [comment]
@terrytangyuan New version is `v6.0.0` and DOI is `10.5281/zenodo.3970567`

**Comment by terrytangyuan** [comment]
@whedon set v6.0.0 as version

**Comment by whedon** [comment]
OK. v6.0.0 is the version.

**Comment by terrytangyuan** [comment]
@whedon set 10.5281/zenodo.3970567 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3970567" target="_blank">10.5281/zenodo.3970567</a> is the archive.

**Comment by terrytangyuan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/icassp.2015.7178964 is OK

MISSING DOIs

- https://doi.org/10.1016/b978-0-08-099388-1.00019-4 may be missing for title: Audio Datasets

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1609

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1609, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by terrytangyuan** [comment]
@openjournals/joss-eics This paper looks good to me now. Handing over to you now!

**Comment by danielskatz** [comment]
@openjournals/dev - note that in the XML there are a bunch of badly formed URLs in unstructured citations.  This is a bug we've had for a while.
1. What should we do in this case?
2. Can we fix the bug?

**Comment by danielskatz** [comment]
@ynop - please merge https://github.com/ynop/audiomate/pull/133

**Comment by ynop** [comment]
@danielskatz Done.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/icassp.2015.7178964 is OK

MISSING DOIs

- https://doi.org/10.1016/b978-0-08-099388-1.00019-4 may be missing for title: Audio Datasets

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1626

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1626, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1290818540426203136) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1627
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02135](https://doi.org/10.21105/joss.02135)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @mulhod and @faroit reviewing, and @terrytangyuan for editing!

Congratulations to @ynop (Matthias Büchi) and co-author!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02135/status.svg)](https://doi.org/10.21105/joss.02135)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02135">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02135/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02135/status.svg
   :target: https://doi.org/10.21105/joss.02135
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02135/status.svg)](https://doi.org/10.21105/joss.02135)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
