### ISSUE TITLE
[PRE REVIEW]: py-pde: A Python package for solving partial differential equations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2138]
**Submitting author:** @david-zwicker (<a href="http://orcid.org/0000-0002-3909-3334">David Zwicker</a>)
**Repository:** <a href="https://github.com/zwicker-group/py-pde" target ="_blank">https://github.com/zwicker-group/py-pde</a>
**Version:** v0.2
**Editor:** @xuanxu
**Reviewers:** @celliern, @@mstimberg
**Managing EiC:** Kevin M. Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @david-zwicker. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @drvinceknight.

@david-zwicker if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.47 s (311.6 files/s, 57396.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         120           5500           6847          11469
Markdown                         3             38              0            274
reStructuredText                 6             82             25            248
TeX                              1             21              0            139
Bourne Shell                     7             27             11             92
YAML                             4             15              2             82
Jupyter Notebook                 3              0           2076             62
INI                              2             13              0             34
make                             1              4              6              9
-------------------------------------------------------------------------------
SUM:                           147           5700           8967          12409
-------------------------------------------------------------------------------


Statistical information for the repository '2138' was gathered on 2020/03/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
David Zwicker                   35         24112            296          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
David Zwicker             23816           98.8          0.0               11.06
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1145/2833157.2833162 is OK
- 10.21105/joss.01356 is OK
- 10.11588/ans.2015.100.20553 is OK
- 10.1109/MCSE.2009.52 is OK
- 10.1007/s10444-019-09666-0 is OK
- 10.5194/gmd-12-1165-2019 is OK
- 10.1109/MCSE.2007.53 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.7717/peerj-cs.103 is OK
- 10.21105/joss.01277 is OK

MISSING DOIs

- https://doi.org/10.1137/110856976 may be missing for title: PyClaw: Accessible, Extensible, Scalable Tools for Wave Propagation Problems

INVALID DOIs

- https://doi.org/10.1038/s41592-019-0686-2 is INVALID because of 'https://doi.org/' prefix
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@drvinceknight @xuanxu is one of you able to edit this submission?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02138/joss.02138/10.21105.joss.02138.pdf)

**Comment by xuanxu** [comment]
@Kevin-Mattheus-Moerman I can take this

**Comment by xuanxu** [comment]
@whedon assign @xuanxu as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by xuanxu** [comment]
👋 @mstimberg: would you be willing to review this paper? I think your knowledge of math and Python makes you a great fit for this submission.

**Comment by xuanxu** [comment]
👋 @rljacobson would you be willing to review this paper? I think your expertise on mathematics makes you a great fit for this submission.

**Comment by mstimberg** [comment]
@xuanxu yes, I'd be happy to review the paper.

**Comment by xuanxu** [comment]
@mstimberg great, thanks! Once I have the second reviewer I'll start a new issue where the actual review will take place. Stay tuned!

**Comment by rljacobson** [comment]
@xuanxu I am unable to at this time. Sorry!

**Comment by celliern** [comment]
@xuanxu Hello! If you need it, I would be happy to review this work. I have been recently published in JOSS for a similar software ([here](https://joss.theoj.org/papers/10.21105/joss.01356)) and have some skill in Python and PDE modeling. Do not feel obliged to, if you find a more relevant reviewer or if you find both works being to close to each other.

**Comment by xuanxu** [comment]
@celliern Great, thanks! I'll assign you now and start the review issue

**Comment by xuanxu** [comment]
@whedon add @celliern as reviewer

**Comment by whedon** [comment]
OK, @celliern is now a reviewer

**Comment by xuanxu** [comment]
@whedon add @@mstimberg as reviewer

**Comment by whedon** [comment]
OK, @@mstimberg is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2158.

**Comment by xuanxu** [comment]
@mstimberg @celliern please head over to #2158 where the review will take place.
