### ISSUE TITLE
[PRE REVIEW]: Surprise: A Python library for recommender systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2139]
**Submitting author:** @NicolasHug (<a href="http://orcid.org/0000-0003-1360-704X">Nicolas Hug</a>)
**Repository:** <a href="https://github.com/NicolasHug/Surprise" target ="_blank">https://github.com/NicolasHug/Surprise</a>
**Version:** v1.1.0
**Editor:** @terrytangyuan
**Reviewers:** @sara-02, @ejhigson
**Managing EiC:** Kevin M. Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @NicolasHug. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @terrytangyuan.

@NicolasHug if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2139 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2139 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you see what is preventing paper compilation here?

**Comment by Kevin-Mattheus-Moerman** [comment]
@terrytangyuan @arokem can one of you edit this submission?

**Comment by terrytangyuan** [comment]
@whedon assign @terrytangyuan as editor

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by terrytangyuan** [comment]
@NicolasHug if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Comment by NicolasHug** [comment]
Hi @terrytangyuan ,

From the list, sara-02, mhetrerajat, and mamrehn seem to have experience with recommender systems and Python.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2139 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2139 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
The issue here is that this is not a URL that Git can clone: https://github.com/NicolasHug/Surprise/tree/joss_paper . I've updated the URL here and in the long run we will have Whedon check for this but for now you need to do this 👇

**Comment by arfon** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02139/joss.02139/10.21105.joss.02139.pdf)

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by sara-02** [comment]
> wave @sara-02 @mhetrerajat @mamrehn if you would like to review for this submission, please let us know here! We need at least two reviewers.

I just saw the notification. Is this still open for review? 
I would love to help, but it might take me until mid-april to finish the review :slightly_frowning_face:

**Comment by arfon** [comment]
> I just saw the notification. Is this still open for review?

@sara-02 - yes, we're still processing submissions, albeit at a slower pace. I'll defer to the handling editor (@terrytangyuan) here but I think we'd likely still want you to review and mid-April sounds pretty reasonable to me :-)

**Comment by terrytangyuan** [comment]
@whedon assign @sara-02 as reviewer

**Comment by whedon** [comment]
OK, @sara-02 is now a reviewer

**Comment by terrytangyuan** [comment]
@sara-02 Yes, mid-April is fine. Just assigned you as reviewer. 

@arfon Do we still need at least two reviewers at this time?

**Comment by arfon** [comment]
> @arfon Do we still need at least two reviewers at this time?

I would prefer so yes but this might be worth raising with the other JOSS editors on the mailing list?

**Comment by danielskatz** [comment]
> Do we still need at least two reviewers at this time?

yes

**Comment by terrytangyuan** [comment]
@NicolasHug @mhetrerajat @mamrehn Please let us know if you are willing to review for this submission. Thanks.

**Comment by ejhigson** [comment]
@terrytangyuan @NicolasHug @arfon I would be happy to review this submission if you would like?

**Comment by arfon** [comment]
Thanks @ejhigson - that would be great! I'm not sure of @terrytangyuan's availability so I'll go ahead and set up the review issue now.

**Comment by arfon** [comment]
@whedon add @ejhigson as reviewer

**Comment by whedon** [comment]
OK, @ejhigson is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2174.

**Comment by arfon** [comment]
@sara-02, @ejhigson, @NicolasHug - see you all over in #2174 where the actual review will take place.

**Comment by terrytangyuan** [comment]
@arfon yes, thank you!

**Comment by arfon** [comment]
> @arfon yes, thank you!

👋 hi @terrytangyuan - sorry for jumping in so quickly there!
