### ISSUE TITLE
[PRE REVIEW]: Jabberwocky: an ontology-aware toolkit for manipulating text

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2140]
**Submitting author:** @sap218 (<a href="http://orcid.org/0000-0002-6169-0135">Samantha Pendleton</a>)
**Repository:** <a href="https://github.com/sap218/jabberwocky" target ="_blank">https://github.com/sap218/jabberwocky</a>
**Version:** v0.5.0.1
**Editor:** @majensen
**Reviewers:** @wdduncan, @balhoff
**Managing EiC:** Kevin M. Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @sap218. **Currently, there isn't an JOSS editor assigned** to your paper.

@sap218 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (226.7 files/s, 40348.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            183            129            757
Markdown                         3             51              0            166
TeX                              1             11              0            127
-------------------------------------------------------------------------------
SUM:                             8            245            129           1050
-------------------------------------------------------------------------------


Statistical information for the repository '2140' was gathered on 2020/03/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Samantha Pendleton              15          1135             66          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Samantha Pendleton         1069           94.2          0.2               11.23
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1093/database/bau033 may be missing for title: tagtog: interactive and text-mining-assisted annotation of gene mentions in PLOS full-text articles
- https://doi.org/10.3115/v1/p14-5010 may be missing for title: The Stanford CoreNLP natural language processing toolkit
- https://doi.org/10.1093/nar/gkr972 may be missing for title: Disease Ontology: a backbone for disease semantic integration
- https://doi.org/10.1016/j.ajhg.2008.09.017 may be missing for title: The Human Phenotype Ontology: a tool for annotating and analyzing human hereditary disease
- https://doi.org/10.1093/bib/bbv011 may be missing for title: The role of ontologies in biological and biomedical research: a functional perspective

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02140/joss.02140/10.21105.joss.02140.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@sap218 thanks for submitting this work. Can appears to be a re-submission of this work which was previously rejected by JOSS: https://github.com/openjournals/joss-reviews/issues/2054. Can you tell us in detail how the functionality of project has been significantly expanded with respect to the previously submitted version?

**Comment by sap218** [comment]
@Kevin-Mattheus-Moerman Thanks! 

Previously I submitted Jabberwocky with a single command, which allowed users to retrieve key elements from a text corpus using an ontology’s terms. Jabberwocky is the first tool to use an ontology directly. However, I understand the feedback that Jabberwocky was a minor-utility package and so I significantly expanded to include more functionality that demonstrates its utility in developing and maintaining ontologies, as well as querying text. This updated version of Jabberwocky includes two new subcommands, which together combine to make a workflow for users. Jabberwocky can now perform a tf-idf analysis on textual data to select key terms, and annotate those key terms in the ontology. Users can iteratively use these commands to identify and incrementally add new synonyms to expand their ontology.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by danielskatz** [comment]
@whedon invite @majensen as editor

**Comment by whedon** [comment]
@majensen has been invited to edit this submission.

**Comment by majensen** [comment]
@whedon assign @majensen as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by majensen** [comment]
@wdduncan -- would you be willing to review [this software]() for [JOSS](https://joss.theoj.org)? Information about reviewing is [available here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). Please let me know here or via other channels - thanks for considering! --@majensen

**Comment by wdduncan** [comment]
@majensen 
Yes, I would. You can also reach me at wdduncan@gmail.com.

**Comment by wdduncan** [comment]
@majensen 
 Chris Mungall might be interested too.

**Comment by majensen** [comment]
@wdduncan great thought- will give it a shot

**Comment by majensen** [comment]
@whedon assign @wdduncan as reviewer

**Comment by whedon** [comment]
OK, @wdduncan is now a reviewer

**Comment by majensen** [comment]
@cmungall - would you have time and inclination to review [this software]() for [JOSS](https://joss.theoj.org)? Reviewing information is [available here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). Let me know here or at maj.fortinbras@gmail.com if you have any questions. Thanks for considering! --@majensen

**Comment by wdduncan** [comment]
Other people you might consider:

Jim Balhoff - balhoff 
James Overton - jamesaoverton 
Alan Ruttenberg - alanruttenberg

**Comment by majensen** [comment]
@balhoff - would you have time and inclination to review [this software]() for [JOSS](https://joss.theoj.org)? Reviewing information is [available here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). Let me know here or at maj.fortinbras@gmail.com if you have any questions. Thanks for considering! --@majensen

**Comment by majensen** [comment]
To all - JOSS is operating under a [very relaxed schedule](https://github.com/openjournals/joss-reviews/issues/2161#issuecomment-598980193) during these days of COVID-19. @sap218, @wdduncan , please just drop a note here if you need to pause the review process to attend to more pressing matters.

**Comment by balhoff** [comment]
@majensen I can review. I like the idea of a relaxed schedule—I may not be able to begin this week.

**Comment by wdduncan** [comment]
@majensen 
Thanks! I should be able to start next week.

**Comment by sap218** [comment]
Hi all ( @majensen @balhoff @wdduncan ), thank you for taking the time, please do work at your own pace - let me know if you need anything from my end :-)

**Comment by majensen** [comment]
@whedon add @balhoff as reviewer

**Comment by whedon** [comment]
OK, @balhoff is now a reviewer

**Comment by majensen** [comment]
Ok everyone - we're are dialed in for a review. I will create that now- this issue will close and we'll continue the discussion in the new one.
Stay safe at home!

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2168.

**Comment by majensen** [comment]
Review @ #2168
