### ISSUE TITLE
[PRE REVIEW]: DetecTree: Tree detection from aerial imagery in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2143]
**Submitting author:** @martibosch (<a href="http://orcid.org/0000-0001-8735-9144">Martí Bosch</a>)
**Repository:** <a href="https://github.com/martibosch/detectree" target ="_blank">https://github.com/martibosch/detectree</a>
**Version:** v0.3.0
**Editor:** @kthyng
**Reviewers:** @JeffWalton-PSC , @rmsare
**Managing EiC:** Kevin M. Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @martibosch. **Currently, there isn't an JOSS editor assigned** to your paper.

@martibosch if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.22 s (139.4 files/s, 13978.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          13            380            754           1449
TeX                              2             10              0            111
Markdown                         4             56              0             96
YAML                             2              7              4             43
reStructuredText                 7             19             31             21
make                             1              4              6             10
Lisp                             1              1              0              6
-------------------------------------------------------------------------------
SUM:                            30            477            795           1736
-------------------------------------------------------------------------------


Statistical information for the repository '2143' was gathered on 2020/03/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Martí Bosch                     11          2659             76          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Martí Bosch                2583           97.1          0.2               14.32
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2143 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon.rb:200:in `block in parse_authors': Author (Martí Bosch) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon.rb:198:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon.rb:198:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon.rb:91:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1007/3-540-59119-2_166 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1023/A:1011139631724 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1109/TPAMI.2004.60 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1145/1653771.1653792 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.5555/1953048.2078195 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1109/MCSE.2011.37 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.7717/peerj.453 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.25080/Majora-7b98e3ed-013 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.25080/Majora-4af1f417-011 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1038/s41592-019-0686-2 is INVALID because of 'https://doi.org/' prefix
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you help compile this paper?

**Comment by martibosch** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2143 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon.rb:200:in `block in parse_authors': Author (Martí Bosch) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon.rb:198:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon.rb:198:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon.rb:91:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@terrytangyuan @arokem @kthyng could one of you edit this submission? 

Some potential reviewer overlap may exists with: 
https://github.com/openjournals/joss-reviews/issues/2056
https://github.com/openjournals/joss-reviews/issues/1825

**Comment by martibosch** [comment]
the affiliation is copied from [my other JOSS paper source](https://github.com/martibosch/swisslandstats-geopy/blob/master/paper/paper.md), in which I am also the sole author. I do not know what might be wrong.

**Comment by arfon** [comment]
> the affiliation is copied from my other JOSS paper source, in which I am also the sole author. I do not know what might be wrong.

Yes, but this isn't compliant with our updated format. Please follow the example [in our docs](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) and break the `affiliations` into their own YAML key.

**Comment by martibosch** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02143/joss.02143/10.21105.joss.02143.pdf)

**Comment by martibosch** [comment]
Hello @arfon I am sorry about that and I thank you for your help. I have amended the paper md source and the PDF is compiled correcly now :smile:

**Comment by martibosch** [comment]
Hello @Kevin-Mattheus-Moerman , should I tag more potential editors, or should we wait for the tagged ones to answer?

**Comment by kthyng** [comment]
Hi! I can take this one.

**Comment by kthyng** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
@martibosch It looks like your documentation could be improved. I went to your readthedocs but it doesn't include the more useful documentation from your readme or from the example repo you mention.

**Comment by kthyng** [comment]
@martibosch Could you look through the reviewer list (https://bit.ly/joss-reviewers) and give suggestions of who might be relevant reviewers for your software? Please don't use "@" to mention them so that they do not get emailed about this, just list their github username. You can also provide information for reviewers who are not on the list if you have other suggestions.

**Comment by martibosch** [comment]
First of all thank you for editing my submission :smile: 

> @martibosch It looks like your documentation could be improved. I went to your readthedocs but it doesn't include the more useful documentation from your readme or from the example repo you mention.

I understand that you mean that I should include the documentation for the technical methods described in the `background.ipynb` notebook of the example repository (e.g., the classes and methods to build the features and image descriptors)? The reason that I had not included them in the readthedocs site is because end users are not supposed to use this methods directly but through the arguments of the `TrainingSelector`, `Classifier` and `ClassifierTrainer` classes and their methods - which are documented. However it is indeed a good idea to document the other background methods as well, e.g., to help potential contributors. I will get to it tomorrow :+1:

**Comment by kthyng** [comment]
/ooo March 7, 2020 to March 15, 2020

**Comment by martibosch** [comment]
some well suited potential reviewers that I could find are: rmsare scivision stsievert thomakra juliohm JeffWalton-PSC

**Comment by martibosch** [comment]
I have added [an "Advanced Topics"](https://detectree.readthedocs.io/en/latest/advanced_topics.html) page in the documentation, which I hope addresses (or at least partly addresses) the comment of @kthyng :smiley:

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by kthyng** [comment]
> I understand that you mean that I should include the documentation for the technical methods described in the `background.ipynb` notebook of the example repository (e.g., the classes and methods to build the features and image descriptors)? The reason that I had not included them in the readthedocs site is because end users are not supposed to use this methods directly but through the arguments of the `TrainingSelector`, `Classifier` and `ClassifierTrainer` classes and their methods - which are documented. However it is indeed a good idea to document the other background methods as well, e.g., to help potential contributors. I will get to it tomorrow 👍

I mean — I am trying to learn about the package you wrote, like I have been as an editor, and I want to go somewhere to learn about it more. Normally readthedocs functions this way, but yours (previously) was strictly description of the functions. Where do you imagine a new user starting with your code? The readme seems like a good start, but also seems too short.

Anyway, this will surely come up in review too, but I figured you could start working on it :)

**Comment by kthyng** [comment]
@JeffWalton-PSC and @thomakra  Are you interested and willing to review this JOSS submission? Normally I would ask for the reviews within about 3 weeks, but many things are unusual right now, so timing is flexible too. Let me know what you think. Thanks.

**Comment by kthyng** [comment]
here is more information about reviewing: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by JeffWalton-PSC** [comment]
Kristen,
Yes, I’m interested.  I will look through the documentation link you sent.

Thanks,

Jeff

**Comment by thomakra** [comment]
Hi Kristen,

Unfortunately I do not have the capacity at this time, although the project
seems interesting.

-Thomas-

**Comment by kthyng** [comment]
Thanks @JeffWalton-PSC! I'll add you as a reviewer and continue to search for a second reviewer.

**Comment by kthyng** [comment]
@whedon assign @JeffWalton-PSC  as reviewer

**Comment by whedon** [comment]
OK, @JeffWalton-PSC  is now a reviewer

**Comment by kthyng** [comment]
@juliohm Do you have the availability and interest to review this JOSS submission? We understand people are quite busy in these unusual times and reviews may take extra time right now, that is ok. Thanks for your consideration.

**Comment by juliohm** [comment]
Thank you @kthyng for pinging. I wish I could review the paper, but I am very busy at the moment with some deadlines. Hope you can find another reviewer.

**Comment by kthyng** [comment]
@rmsare Might you be able to review this submission to JOSS? Thanks for your consideration.

**Comment by rmsare** [comment]
@kthyng, thanks for the request - this submission looks really interesting. I expect I could complete a review by 3 May (unfortunately I have a late April deadline). Would this be timely enough for this review?

**Comment by kthyng** [comment]
@rmsare Yes, that would be great. We are grateful for any time people can dedicate to JOSS right now in these unusual times. I will add you as the second reviewer and we can move ahead to start the review.

**Comment by kthyng** [comment]
@whedon add @rmsare as reviewer

**Comment by whedon** [comment]
OK, @rmsare is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2172.

**Comment by kthyng** [comment]
@JeffWalton-PSC and @rmsare please head over to [#2172](https://github.com/openjournals/joss-reviews/issues/2172) for the actual review.
