### ISSUE TITLE
[PRE REVIEW]: MASTR-Quant: An Open-Source Web-based Software Tool for the Quantitive Analysis of Mass Spectrometry-based Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2144]
**Submitting author:** @MetabolomicsAustralia-Bioinformatics (<a href="http://orcid.org/0000-0003-3980-7496">Vinod Narayana</a>)
**Repository:** <a href="https://github.com/MetabolomicsAustralia-Bioinformatics/metabio" target ="_blank">https://github.com/MetabolomicsAustralia-Bioinformatics/metabio</a>
**Version:** 1.0
**Editor:** @csoneson
**Reviewers:** @lgatto, @bovee
**Managing EiC:** Kevin M. Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @MetabolomicsAustralia-Bioinformatics. **Currently, there isn't an JOSS editor assigned** to your paper.

@MetabolomicsAustralia-Bioinformatics if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1038/nrg3575 may be missing for title: Systems genetics approaches to understand complex traits

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02144/joss.02144/10.21105.joss.02144.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=34.10 s (126.4 files/s, 56961.0 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
JSON                            352            118              0         552238
Python                         2491         155080         199581         548569
PO File                        1109          71710           9717         216767
JavaScript                       97          20453          29412          85504
CSS                              47           2503            644          15088
HTML                             94           2139            228          14902
C/C++ Header                     26            936           1338           5865
reStructuredText                 29           1680            501           3978
SQL                               3              0              0           1103
C                                 3            102             92           1091
Fortran 90                       15             69             35            252
SVG                              25              0              0            129
Markdown                          3             35              0            114
TeX                               4              1             16             55
Fish Shell                        1             16             13             47
XML                               5              1              1             44
INI                               2              5              0             27
YAML                              1              0              0             18
C Shell                           1             12              7             17
Fortran 77                        2              1              1             14
Bourne Again Shell                1              1              0              9
--------------------------------------------------------------------------------
SUM:                           4311         254862         241586        1445831
--------------------------------------------------------------------------------

**Comment by Kevin-Mattheus-Moerman** [comment]
@lpantano @will-rowe @csoneson @lorenanicole could on of you edit this submission?

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=36.05 s (119.5 files/s, 53873.2 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
JSON                            352            118              0         552238
Python                         2491         155080         199581         548569
PO File                        1109          71710           9717         216767
JavaScript                       97          20453          29412          85504
CSS                              47           2503            644          15088
HTML                             94           2139            228          14902
C/C++ Header                     26            936           1338           5865
reStructuredText                 29           1680            501           3978
SQL                               3              0              0           1103
C                                 3            102             92           1091
Fortran 90                       15             69             35            252
SVG                              25              0              0            129
Markdown                          3             35              0            114
TeX                               4              1             16             55
Fish Shell                        1             16             13             47
XML                               5              1              1             44
INI                               2              5              0             27
C Shell                           1             12              7             17
Fortran 77                        2              1              1             14
Bourne Again Shell                1              1              0              9
--------------------------------------------------------------------------------
SUM:                           4310         254862         241586        1445813
--------------------------------------------------------------------------------


Statistical information for the repository '2144' was gathered on 2020/03/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
MetabolomicsAustrali             5            60         109381            8.84
shushu-leng                     27       1128299            677           91.16

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
MetabolomicsAustrali         57           95.0          1.0                8.77
shushu-leng             1075686           95.3         10.8               11.49
```

**Comment by csoneson** [comment]
> @lpantano @will-rowe @csoneson @lorenanicole could on of you edit this submission?

I can take this one

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋 @MetabolomicsAustralia-Bioinformatics - I'll handle your submission, and start by looking for suitable reviewers. 

Looking at your submission, I noticed that your paper is a bit too short for JOSS standards (see https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). Could you add a bit more context?

**Comment by csoneson** [comment]
👋 @bovee, @lgatto, @jorainer - would (two of) you be willing to review this submission for the Journal of Open Source Software (JOSS)? 

 > MASTR-Quant: An Open-Source Web-based Software Tool for the Quantitive Analysis of Mass Spectrometry-based Data

software: https://github.com/MetabolomicsAustralia-Bioinformatics/metabio
accompanying paper: https://github.com/openjournals/joss-papers/blob/joss.02144/joss.02144/10.21105.joss.02144.pdf

instructions on reviewing for JOSS: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by csoneson** [comment]
ping @bovee, @lgatto, @jorainer

> 👋 @bovee, @lgatto, @jorainer - would (two of) you be willing to review this submission for the Journal of Open Source Software (JOSS)?
> 
> > MASTR-Quant: An Open-Source Web-based Software Tool for the Quantitive Analysis of Mass Spectrometry-based Data
> 
> software: https://github.com/MetabolomicsAustralia-Bioinformatics/metabio
> accompanying paper: https://github.com/openjournals/joss-papers/blob/joss.02144/joss.02144/10.21105.joss.02144.pdf
> 
> instructions on reviewing for JOSS: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by lgatto** [comment]
Here are my comments regarding this submission:
- The submission contains a repository (but see below) and a valid OSI approved license.
- I find the manuscript to be extremely short. In particular, I miss some citation/comparison with existing alternatives in general, and a description of this software compares to other commonly-used packages in this research area.
- There are no references.
- The documentation on the README page only contains installation instructions (which I have not tested). There is no information about the underlying implementations or core functionality. In particular, it seems the user is let to decide what regression type and parameters are best suited based on visual inspection of the fit, being also allowed to manually define outliers. More rigorous approaches such (standardised) residuals, leverage and/or Cook's distance might be applicable. 
- The application is available at `mastr-quant.bio21.unimelb.edu.au`, which contains some basic documentation of how to use the web interface. I tried it twice but the application froze and became unresponsive. The web application contains test data for user to try the interface out, but there is no description of these test data.
- I managed to download result files, which seem to contain various forms of the data (raw, normalised, ...), at time poorly formatted (multiple table per sheet) and I could find any documentation describing the output file or how to use the results for downstream analyses.
- It is confusion that the repo to be reviewed is itself a for of `uncle-leng/metabio`. There are only two contributors to either of the fork or original repository. It would be useful to document the contributions of the 9 authors.

I confirm that I have read the JOSS conflict of interest policy and that I have no COIs with reviewing this work.

**Comment by csoneson** [comment]
Thanks @lgatto (that was super fast 😃)! 
Once one more reviewer confirms their interest, I will close this issue and open the actual review issue that contains the checklist for each reviewer. I will then transfer your comments above over there so that we have everything in one place.

**Comment by jorainer** [comment]
Dear @csoneson - I'm quite busy at present with other reviews - so I would only want to accept to review yet another one when it's absolutely necessary. Would be happy if another reviewer would accept to review...

**Comment by csoneson** [comment]
@jorainer - no problem! If you happen to have a suggestion for someone that I might reach out to, that would be awesome :)

**Comment by jorainer** [comment]
@sgibb eventually - but I'm not sure if he's available.

**Comment by csoneson** [comment]
@sgibb - would you be interested in reviewing this submission for the Journal of Open Source Software? 

> MASTR-Quant: An Open-Source Web-based Software Tool for the Quantitive Analysis of Mass Spectrometry-based Data

software: https://github.com/MetabolomicsAustralia-Bioinformatics/metabio
accompanying paper: https://github.com/openjournals/joss-papers/blob/joss.02144/joss.02144/10.21105.joss.02144.pdf

instructions on reviewing for JOSS: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by sgibb** [comment]
@csoneson I am sorry but I am currently not able to review anything.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by bovee** [comment]
@csoneson Sorry about the delay! I'm a little stretched right now, but happy to review.

**Comment by csoneson** [comment]
@bovee - brilliant, thanks so much! I'll add you too as a reviewer and open the actual review issue.

**Comment by csoneson** [comment]
@whedon assign @lgatto as reviewer

**Comment by whedon** [comment]
OK, @lgatto is now a reviewer

**Comment by csoneson** [comment]
@whedon add @bovee as reviewer

**Comment by whedon** [comment]
OK, @bovee is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2163.

**Comment by MetabolomicsAustralia-Bioinformatics** [comment]
Hi all,

Thanks for your time and effort in reviewing so far. Only about manuscript submission:

1. We actually have a larger, 2 page, manuscript written, as a pdf. I’ve restructured (in particular, cut down) this larger paper to the approximate size and formatting as recommended here: https://joss.theoj.org/papers/10.21105/joss.00388, where it looked like only a summary was needed. Should I be submitting the full manuscript instead?
2. As for lack of references: I’ve actually included references in paper.bib (https://github.com/MetabolomicsAustralia-Bioinformatics/metabio/blob/master/paper/paper.bib), as per the submission instructions.  Unfortunately, this won’t actually compile. In fact, the Whedon paper preview service provided won’t compile its own example either to contain References (the gala paper). An attempt as of a few minutes ago has received a 404 error.

Just to address the manuscript issues, any advice to get around these technical issues would be greatly appreciated.

Many thanks and regards,
Don Teng
Bioinformatician
Metabolomics Australia
University of Melbourne, Parkville, Melbourne, Victoria
