### ISSUE TITLE
[REVIEW]: Visions: An Open-Source Library for Semantic Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2145]
**Submitting author:** @sbrugman (<a href="http://orcid.org/0000-0001-9866-7767">Simon Brugman</a>)
**Repository:** <a href="https://github.com/dylan-profiler/visions" target ="_blank">https://github.com/dylan-profiler/visions</a>
**Version:** v0.3.0
**Editor:** @mjsottile
**Reviewer:** @1313e, @fccoelho
**Archive:** <a href="https://doi.org/10.5281/zenodo.3748758" target="_blank">10.5281/zenodo.3748758</a>

## Status

[![status](https://joss.theoj.org/papers/dcc0ecdd4db6e53fb305097d0297d33e/status.svg)](https://joss.theoj.org/papers/dcc0ecdd4db6e53fb305097d0297d33e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/dcc0ecdd4db6e53fb305097d0297d33e"><img src="https://joss.theoj.org/papers/dcc0ecdd4db6e53fb305097d0297d33e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/dcc0ecdd4db6e53fb305097d0297d33e/status.svg)](https://joss.theoj.org/papers/dcc0ecdd4db6e53fb305097d0297d33e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dylan-profiler/visions" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@1313e & @fccoelho, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mjsottile know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dylan-profiler/visions">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@sbrugman) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dylan-profiler/visions">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@sbrugman) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @1313e, @fccoelho it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/MCSE.2011.37 is OK
- 10.5281/zenodo.3545747 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02145/joss.02145/10.21105.joss.02145.pdf)

**Comment by 1313e** [comment]
I am currently reviewing this, and I am going to assume that I should review v0.2.3, as that version has the bugfix for the `attr.s` decorator.
Can this be confirmed and if so, updated above? @sbrugman @mjsottile

**Comment by mjsottile** [comment]
@1313e I would review the version with the bug fix.  When the process is finished, the version number for the submission will be set to whatever version is archived - which I assume will reflect the bug fix you mention, as well as any other bugs and changes that arise during the review process.

**Comment by fccoelho** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02145/joss.02145/10.21105.joss.02145.pdf)

**Comment by fccoelho** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by fccoelho** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02145/joss.02145/10.21105.joss.02145.pdf)

**Comment by sbrugman** [comment]
@whedon set v0.3.0 as version

**Comment by whedon** [comment]
I'm sorry @sbrugman, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by sbrugman** [comment]
@mjsottile Could you set the version to v0.3.0, please.

**Comment by mjsottile** [comment]
Sure - no problem.

**Comment by mjsottile** [comment]
@whedon set v0.3.0 as version

**Comment by whedon** [comment]
OK. v0.3.0 is the version.

**Comment by 1313e** [comment]
Once the issues raised in dylan-profiler/visions#22, dylan-profiler/visions#30, dylan-profiler/visions#31 and dylan-profiler/visions#32 are resolved, I am happy for this paper to be accepted.

**Comment by sbrugman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02145/joss.02145/10.21105.joss.02145.pdf)

**Comment by 1313e** [comment]
Alright, I am happy for this paper to be accepted now.
Great work @sbrugman (and @ieaves) in solving the issues this quickly. :)

**Comment by mjsottile** [comment]
:wave: @fccoelho It looks like your checklist is complete as well.  Do you agree with @1313e regarding acceptance?  If so, I'll do my pass through the submission and move on to next steps.

**Comment by fccoelho** [comment]
@mjsottile , I am done and recommend the paper for publication.

**Comment by mjsottile** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/MCSE.2011.37 is OK
- 10.5281/zenodo.3545747 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mjsottile** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02145/joss.02145/10.21105.joss.02145.pdf)

**Comment by mjsottile** [comment]
The only thing I found when reviewing the paper and repository was that the first word of Figure 1's caption should be capitalized.  

Given that everyone seems to agree that the paper is good to go forward, the next steps for @sbrugman are:

- Submit a version of the software to an archive (e.g., figshare or zenodo) and post the DOI for the archive in this thread.  

- Please verify that the version number (0.3.0) matches that of the archived code, and if not, let me know so I can update the version here.  

- Finally, make sure that the metadata for the archive (e.g., title, authors) matches the paper.

Once all of these steps are done, I'll pass the paper on up the line to the EIC team for finalizing the process.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by sbrugman** [comment]
We went through the remaining steps. 
- The software version has increased.  For the publication is v0.4.1. 
- For the archive, the Zenodo DOI is http://doi.org/10.5281/zenodo.3748758.

@1313e and @fccoelho Many thanks for your constructive reviews!

@mjsottile Thanks for editing this one :)

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02145/joss.02145/10.21105.joss.02145.pdf)

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.3644238 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.5281/zenodo.3545747 is OK

MISSING DOIs

- https://doi.org/10.25080/majora-92bf1922-00a may be missing for title: Data Structures for Statistical Computing in Python

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3748758 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3748758" target="_blank">10.5281/zenodo.3748758</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1414

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1414, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.3644238 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.5281/zenodo.3545747 is OK

MISSING DOIs

- https://doi.org/10.25080/majora-92bf1922-00a may be missing for title: Data Structures for Statistical Computing in Python

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@sbrugman - a couple of quick changes please for us to proceed from here. Could you please add `10.25080/majora-92bf1922-00a` to the `doi` field of your BibTeX entry for that paper Whedon is suggesting (it looks to be a correct DOI suggestion).

Also, the fact that you have a `*` after your author names is causing issues with our production pipeline. Could you explain what you're trying to accomplish here and perhaps I can make an alternative suggestion?

**Comment by sbrugman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

-  10.25080/Majora-92bf1922-00a  is OK
- 10.5281/zenodo.3644238 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.5281/zenodo.3545747 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by sbrugman** [comment]
> Also, the fact that you have a * after your author names is causing issues with our production pipeline. Could you explain what you're trying to accomplish here and perhaps I can make an alternative suggestion?

The * is intended to indicate equal contribution.

**Comment by arfon** [comment]
@sbrugman -  could you merge this PR (https://github.com/dylan-profiler/visions/pull/48) or make a similar change?

**Comment by ieaves** [comment]
@arfon - Merged, thank you.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02145/joss.02145/10.21105.joss.02145.pdf)

**Comment by arfon** [comment]
Can you check the new pdf proof looks ok (for denoting equal authorship?)

**Comment by sbrugman** [comment]
@afron Looks good, thank you.

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1249671099006300165) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1415
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02145](https://doi.org/10.21105/joss.02145)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@1313e, @fccoelho - many thanks for your reviews here and to @mjsottile for editing this submission ✨ 

@sbrugman - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02145/status.svg)](https://doi.org/10.21105/joss.02145)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02145">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02145/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02145/status.svg
   :target: https://doi.org/10.21105/joss.02145
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02145/status.svg)](https://doi.org/10.21105/joss.02145)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
