### ISSUE TITLE
[PRE REVIEW]: Sensie: Probing the sensitivity of neural networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2146]
**Submitting author:** @coljac (<a href="http://orcid.org/0000-0003-4239-4055">Colin Jacobs</a>)
**Repository:** <a href="https://github.com/coljac/sensie" target ="_blank">https://github.com/coljac/sensie</a>
**Version:** 0.1.0
**Editor:** @gkthiruvathukal
**Reviewers:** @ejhigson
**Managing EiC:** Kevin M. Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @coljac. **Currently, there isn't an JOSS editor assigned** to your paper.

@coljac if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.39 s (61.5 files/s, 8796.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5            204            269            450
Jupyter Notebook                 3              0           1633            236
TeX                              1             17              0            181
Markdown                         3             84              0            156
SVG                              7              0              0            120
reStructuredText                 3             22             11             27
make                             1              4              6              9
INI                              1              0              0              2
-------------------------------------------------------------------------------
SUM:                            24            331           1919           1181
-------------------------------------------------------------------------------


Statistical information for the repository '2146' was gathered on 2020/03/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Colin Jacobs                     1           178              0           16.08
coljac                           5           837             92           83.92

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Colin Jacobs                923          518.5          0.1               18.74
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.dsp.2017.10.011 is OK
- 10.1109/ICIP.2016.7532763 is OK
- 10.1371/journal.pone.0130140 is OK
- 10.1002/widm.1349 is OK
- 10.3847/1538-4365/ab26b6 is OK
- 10.1093/mnras/stz272 is OK
- 10.1093/mnras/stx1492 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-319-44781-0_8 may be missing for title: Layer-Wise Relevance Propagation for Neural Networks with Local Renormalization Layers
- https://doi.org/10.1109/iccv.2017.74 may be missing for title: Grad-CAM: Visual Explanations From Deep Networks via Gradient-Based Localization

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02146/joss.02146/10.21105.joss.02146.pdf)

**Comment by coljac** [comment]
From the list, AvianaGlobal and MohmedSoudy (among others) would seem to have relevant expertise.

**Comment by Kevin-Mattheus-Moerman** [comment]
@gkthiruvathukal can you handle this as editor?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
@Kevin-Mattheus-Moerman Thanks. I will take care of this over the weekend. Thanks to everyone for your patience until I can get to it.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by arfon** [comment]
:wave: @gkthiruvathukal - just a friendly reminder that we're waiting on you to find some reviewers for this submission.

**Comment by gkthiruvathukal** [comment]
@arfon It looks like I will be able to resume semi-normal operations later this week. I will definitely get on it. Thanks to everyone for waiting!

**Comment by ejhigson** [comment]
@gkthiruvathukal @arfon I would be happy to review this submission if you would like me to? (I have a lot of experience with neural networks and Python)

**Comment by arfon** [comment]
Thanks @ejhigson, that would be great! I'll go ahead and start the review with just yourself as the reviewer and ask that @gkthiruvathukal looks for a second reviewer when he has time.

**Comment by arfon** [comment]
@whedon add @ejhigson as reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2180.

**Comment by arfon** [comment]
@ejhigson - please head over the #2180 where the actual review will take place.
