### ISSUE TITLE
[PRE REVIEW]: MDBED: A R package for simulating the Moran-Downton bivariate exponential   distribution

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2147]
**Submitting author:** @https://github.com/lfduquey (<a href="http://orcid.org/0000-0002-0367-8496">Luis F. Duque</a>)
**Repository:** <a href="https://github.com/lfduquey/Paper-JOSS-MDBED" target ="_blank">https://github.com/lfduquey/Paper-JOSS-MDBED</a>
**Version:** 1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @https://github.com/lfduquey. **Currently, there isn't an JOSS editor assigned** to your paper.

@https://github.com/lfduquey if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (37.0 files/s, 6240.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              1              0              2            441
TeX                              1              0              0             94
Markdown                         1             12              0             38
Rmd                              1             17             43             27
-------------------------------------------------------------------------------
SUM:                             4             29             45            600
-------------------------------------------------------------------------------


Statistical information for the repository '2147' was gathered on 2020/03/06.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1111/j.2517-6161.1970.tb00852.x is OK
- 10.1007/BF01543085 is OK
- 10.18637/jss.v021.i04 is OK
- 10.1007/b101765 is OK
- 10.1029/WR021i005p00755 is OK

MISSING DOIs

- https://doi.org/10.1201/9780203710319 may be missing for title: Simulation Methodology for Statisticians, Operations Analysts, and Engineers (1988)

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02147/joss.02147/10.21105.joss.02147.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev the used have created a separate repository for the JOSS paper. It looks like the actual software is here: https://github.com/lfduquey/MDBED. 
Is this acceptable or do we need to change the repository?

**Comment by arfon** [comment]
> @openjournals/dev the used have created a separate repository for the JOSS paper. It looks like the actual software is here: https://github.com/lfduquey/MDBED.

We'd strongly prefer the paper to be in the same repo as the software but it's not compulsory.

**Comment by danielskatz** [comment]
👋 @lfduquey - Can you move your paper into your software repo, then resubmit the software repo (also use your github handle when you submit, not the URL to your github account)?

**Comment by lfduquey** [comment]
@danielskatz ok. I will repeat the submission process by following your suggestions.

**Comment by danielskatz** [comment]
Thanks - I'll mark this as withdrawn and expect the replacement

**Comment by danielskatz** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
