### ISSUE TITLE
[PRE REVIEW]: Spleeter: a fast and state-of-the art music source separation tool with pre-trained models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2148]
**Submitting author:** @romi1502 (<a href="http://orcid.org/0000-0001-8158-5562">Romain Hennequin</a>)
**Repository:** <a href="https://github.com/deezer/spleeter" target ="_blank">https://github.com/deezer/spleeter</a>
**Version:** v1.4.9
**Editor:** @terrytangyuan
**Reviewers:** @bmcfee , @faroit 
**Managing EiC:** Kevin M. Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @romi1502. **Currently, there isn't an JOSS editor assigned** to your paper.

@romi1502 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.18 s (279.0 files/s, 24565.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          30            504            897           1887
JSON                             9              0              0            275
YAML                             2              0             21            258
Markdown                         7             74              0            189
TeX                              1             15              1            135
make                             1              7              6             20
Jupyter Notebook                 1              0            192             10
-------------------------------------------------------------------------------
SUM:                            51            600           1117           2774
-------------------------------------------------------------------------------


Statistical information for the repository '2148' was gathered on 2020/03/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Félix Voituret                  44          1096           1067           39.66
Romain                           1          3242              0           59.44
Romain Hennequin                 1             4              2            0.11
Yusuke Goto                      1            10              1            0.20
fvoituret                        1             1              1            0.04
johnwmillr                       1             3              3            0.11
mmoussallam                      1             7              4            0.20
romi1502                         2             2              2            0.07
valrus                           1             6              3            0.17

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Félix Voituret              492           44.9          2.5               10.37
Romain Hennequin              4          100.0          1.2                0.00
Yusuke Goto                  10          100.0          0.9                0.00
johnwmillr                    3          100.0          2.1                0.00
mmoussallam                   7          100.0          0.0                0.00
romi1502                   2766       138300.0          0.0               14.61
valrus                        6          100.0          0.5                0.00
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/ICASSP.2019.8683555 is OK
- 10.5281/zenodo.3269749 is OK
- 10.1109/TSA.2005.858005 is OK
- 10.5281/zenodo.1117372 is OK
- 10.21105/joss.01667 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-319-93764-9_28 may be missing for title: The 2018 Signal Separation Evaluation Campaign

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02148/joss.02148/10.21105.joss.02148.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @arokem as editor

**Comment by whedon** [comment]
@arokem has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@terrytangyuan @arokem could one of you edit this submission? Perhaps there is some reviewer overlap with: https://github.com/openjournals/joss-reviews/issues/1667

**Comment by terrytangyuan** [comment]
@whedon set @terrytangyuan as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by terrytangyuan** [comment]
@whedon assign @terrytangyuan as editor

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by terrytangyuan** [comment]
Happy to edit this one. @romi1502 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Comment by romi1502** [comment]
Hey @terrytangyuan.
Thank you for managing the review.
An obvious choice for the paper review would be faroit as he is the main author of an open source package which also deals with Source Separation (Open Unmix) though it may be considered as a conflict of interest. Otherwise, I don't know other people in the list. Anyone with experience in Python and audio/music processing should be skilled to review it.

**Comment by terrytangyuan** [comment]
👋 @bmcfee, @hagenw @faroit if you would like to review for this submission, please let us know here! We need at least two reviewers.

**Comment by faroit** [comment]
@terrytangyuan @romi1502 Great to see more audio papers here. I don't see a conflict of interest and can ensure that I would review the paper accordingly. But I let the editors decide....

**Comment by bmcfee** [comment]
Sure, count me in.

**Comment by terrytangyuan** [comment]
@whedon assign @bmcfee  as reviewer

**Comment by whedon** [comment]
OK, @bmcfee  is now a reviewer

**Comment by terrytangyuan** [comment]
@whedon add @faroit  as reviewer

**Comment by whedon** [comment]
OK, @faroit  is now a reviewer

**Comment by terrytangyuan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2154.

**Comment by terrytangyuan** [comment]
Thanks! Look forward to your reviews in #2154.
