### ISSUE TITLE
[PRE REVIEW]: Utopia: A Comprehensive and Collaborative Modeling Framework for Complex and Evolving Systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2149]
**Submitting author:** @peanutfun (<a href="http://orcid.org/0000-0002-4667-3652">Lukas Riedel</a>)
**Repository:** <a href="https://ts-gitlab.iup.uni-heidelberg.de/utopia/utopia" target ="_blank">https://ts-gitlab.iup.uni-heidelberg.de/utopia/utopia</a>
**Version:** latest
**Editor:** @arfon
**Reviewers:** @platipodium, @Shibabrat
**Managing EiC:** Kevin M. Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @peanutfun. **Currently, there isn't an JOSS editor assigned** to your paper.

@peanutfun if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2149 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02149/joss.02149/10.21105.joss.02149.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev this paper is on a separate branch so we created the pdf by running `@whedon generate pdf from branch joss-paper`. Will we need to keep using this command throughout the review process or are there any other steps we need to take?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.06 s (458.9 files/s, 74328.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                    78           4158           9832          15074
C++                             65           2454           1696           8984
Python                         104           3866           5629           8640
YAML                           145           1407           1453           4644
reStructuredText                44           2410           2428           3012
Markdown                        14            402              0            957
CMake                           35            222            426            856
-------------------------------------------------------------------------------
SUM:                           485          14919          21464          42167
-------------------------------------------------------------------------------


Statistical information for the repository '2149' was gathered on 2020/03/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Benjamin Herdeanu              407         20796          11883           10.43
Christian Kobrow                 1            30             30            0.02
Daniel Lake                     21          2925           1375            1.37
Fabian Krautgasser              17           532            125            0.21
Fritz Furz                       1             1              1            0.00
H_Leusmann                      52           786            311            0.35
Harald Mack                    267         53150          32928           27.47
Jeremias Traub                  21          1452            863            0.74
Josephine Westermann           119          3176           2126            1.69
Julian                          74          3680           3066            2.15
Julian 530U3C Ubuntu             7           465            167            0.20
Julian Weninger                 37          6212           2269            2.71
Lorenzo Biasi                    1           595              6            0.19
Lukas Riedel                   248         43585          42089           27.35
Lukas Siebert                   37          1327            548            0.60
Narek Baghumian                 12          1715           1169            0.92
Peter Manshausen                 2           100              2            0.03
Rechenknecht                     2            97            107            0.07
Sebastian Stezura                1            88             88            0.06
Simeon Scheib                    2           680              7            0.22
Unai Fischer Abaigar            34          1183            374            0.50
Yunus Sevinchan                815         47043          22776           22.28
jweninger                       20           801            485            0.41
root                             1            74             17            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Benjamin Herdeanu          8334           40.1          8.4               28.34
Christian Kobrow             30          100.0          0.0                0.00
Daniel Lake                 693           23.7         13.5               27.42
Fabian Krautgasser           64           12.0         23.4               14.06
H_Leusmann                  103           13.1         23.2               15.53
Harald Mack               15417           29.0         10.0               24.80
Jeremias Traub             1034           71.2          3.0               28.43
Josephine Westermann        280            8.8         19.2               21.07
Julian                      267            7.3         15.8               18.35
Julian 530U3C Ubuntu          2            0.4         14.5               50.00
Julian Weninger            4737           76.3          8.1               21.47
Lorenzo Biasi               140           23.5         12.4               21.43
Lukas Riedel               2426            5.6         12.6               24.36
Lukas Siebert                24            1.8         21.9               29.17
Narek Baghumian             162            9.4         11.5               37.04
Peter Manshausen              1            1.0         10.8                0.00
Sebastian Stezura            79           89.8          3.0              100.00
Simeon Scheib               121           17.8         11.4               18.18
Unai Fischer Abaigar        209           17.7         16.5               25.36
Yunus Sevinchan           25450           54.1         13.3               25.02
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@gkthiruvathukal @mbobra @mjsottile @poulson can one of you edit this submission?

**Comment by arfon** [comment]
> Will we need to keep using this command throughout the review process or are there any other steps we need to take?

Yes, this is something we'll need to keep doing through the review process.

**Comment by gkthiruvathukal** [comment]
@Kevin-Mattheus-Moerman I'm facing a bit of mid-semester congestion, so I hope one of the others you mentioned can edit this submission. I should be in a better position to take on new assignments in a week or so.

**Comment by mjsottile** [comment]
@Kevin-Mattheus-Moerman I’m saturated with work at the moment, so I can’t take on another paper right now.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@Kevin-Mattheus-Moerman - I can take this one.

**Comment by arfon** [comment]
@peanutfun - many thanks for your submission to JOSS. 

Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by peanutfun** [comment]
Hi @arfon, thank you in advance. We've been looking forward to this!

As potential reviewers I would like to suggest @eteq, @platipodium, @szhorvat, @dglmoore, @shibabrat, and @sgrieve.

> this paper is on a separate branch so we created the pdf by running @whedon generate pdf from branch joss-paper

It would be great if we could keep compiling the paper from the `joss-paper` branch in our repository until the review is finished. This way, we can update the document quickly and only merge it into our `master` branch once the publication is accepted.

**Comment by arfon** [comment]
:wave: @dglmoore @platipodium - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by platipodium** [comment]
Dear @arfon, thanks for inviting me to review this paper.  I am also grounded at home, but I will be able to do the review.  I did find information on review criteria, checklist and guidelines https://joss.readthedocs.io/en/latest/reviewer_guidelines.html , but I did not find information on how to technically do the review through github.  Any hints for me?

**Comment by arfon** [comment]
Thanks for the response @platipodium. Yes, once I've identified reviewers for this submission I'll be setting up another issue on GitHub with a checklist for you to work through (see [this one as an example](https://github.com/openjournals/joss-reviews/issues/2073)).

As it might take a while to find a second reviewer I'll go ahead and do this now.

**Comment by arfon** [comment]
@whedon add @platipodium as reviewer

**Comment by whedon** [comment]
OK, @platipodium is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2165.

**Comment by arfon** [comment]
@platipodium - see you over in #2165!

**Comment by arfon** [comment]
:wave: @Shibabrat @szhorvat - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by szhorvat** [comment]
@arfon It is not entirely clear to me what this tool actually does, and who would want to use it, and therefore to judge at a glance if I have the expertise to review it. This could actually be considered as the first piece of feedback to the authors.

Can you give me a couple of days to take a more careful look before I commit? I would give my final response about whether I can do it by Thursday evening European time.

**Comment by arfon** [comment]
Understood, thanks @szhorvat. I don't know if you managed to take a look at the paper yet ([this comment](https://github.com/openjournals/joss-reviews/issues/2149#issuecomment-596178906)) - this may help?

**Comment by szhorvat** [comment]
I am sorry, I forgot to look at the paper. I am still relatively new to JOSS, having done only half a review so far.

It looks like an interesting tool. I can do the review. It might take a bit longer than usual because of the situation.

I would still recommend listing [some example models that can be implemented](https://hermes.iup.uni-heidelberg.de/utopia_doc/latest/html/models/ContDisease.html) in the paper's introduction. It connects to something readers are familiar with. The comparison with NetLogo was helpful.

**Comment by platipodium** [comment]
@szhorvat  I have the same issue with first glance at the manuscript and code and help pages.  Purpose and added value are not easy to grasp.  It is a complex framework with lots of flexibility and they do provide examples.   I agree with @arfon that we should make this a first recommendation to @peanutfun in our review.

**Comment by Shibabrat** [comment]
@arfon yes I'm happy to review this submission. Some of the applications are outside my domain expertise so I'll rely on other reviewers to open issues in the repo about that. 

> 👋 @Shibabrat @szhorvat - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

thanks

**Comment by arfon** [comment]
Excellent, thanks @Shibabrat. See you over in #2165 for the actual review.

**Comment by szhorvat** [comment]
@arfon Do you still want me to do it then? As I mentioned, I skimmed the paper and I am willing to do it.

**Comment by arfon** [comment]
> @arfon Do you still want me to do it then? As I mentioned, I skimmed the paper and I am willing to do it.

Yes please! I'll add you as a reviewer now.

**Comment by dglmoore** [comment]
@arfon The last week has been crazy. I'm up to reviewing if there's still a need?

**Comment by arfon** [comment]
@dglmoore - yes please! I'll add you as a reviewer over in #2165 right now.

**Comment by arfon** [comment]
Oh, actually, scrub that. I forgot we already had two reviewers. If you're particularly motivated to review this @dglmoore you're more than welcome to but we already have the necessary number of reviewers here.

Let me know what you'd like to do :-)

**Comment by dglmoore** [comment]
@arfon No worries. Keep me in mind for the next one.
