### ISSUE TITLE
[PRE REVIEW]: AcPgChecker: A tool for Plagiarism Detection in Students’ Assignments and Reports

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2150]
**Submitting author:** @dipongkor (<a href="http://orcid.org/0000-0001-8253-429X">Atish Kumar Dipongkor</a>)
**Repository:** <a href="https://github.com/dipongkor/PlagiarismChecker" target ="_blank">https://github.com/dipongkor/PlagiarismChecker</a>
**Version:** V1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**Author instructions**

Thanks for submitting your paper to JOSS @dipongkor. **Currently, there isn't an JOSS editor assigned** to your paper.

@dipongkor if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=3.68 s (23.7 files/s, 37509.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                             59           2154            549         133050
Markdown                         4            119              0            611
C#                              16            116            123            462
MSBuild script                   5              0              0            415
XAML                             2             17              0            248
TeX                              1              2              0             24
-------------------------------------------------------------------------------
SUM:                            87           2408            672         134810
-------------------------------------------------------------------------------


Statistical information for the repository '2150' was gathered on 2020/03/08.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.25103/jestr.094.23 may be missing for title: Study on Extrinsic Text Plagiarism Detection Techniques and Tools.

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02150/joss.02150/10.21105.joss.02150.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@dipongkor thanks for your submission. 

As our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) state:
- The software should have an **obvious** research application.

- The software should be feature-complete (no half-baked solutions) and designed for maintainable extension (not one-off modifications). Minor ‘utility’ packages, including ‘thin’ API clients, and **single-function** packages are not acceptable.

At 16 C# files (462 lines of code), this submission appears rather minor. The functionality appears limited to only plagiarism checking through a Windows desktop GUI. Furthermore the software does not seem to have a clear research application. Can you elaborate on the actual scientific research applications of AcPgChecker?

**Comment by dipongkor** [comment]
Suggested Reviewers: -
@CBenghi, @Fusionet24, @xirdneh, @zedtaha

**Comment by dipongkor** [comment]
> **Submitting author:** @dipongkor ([Atish Kumar Dipongkor](http://orcid.org/0000-0001-8253-429X))
> **Repository:** https://github.com/dipongkor/PlagiarismChecker
> **Version:** V1.0
> **Editor:** Pending
> **Reviewer:** Pending
> **Managing EiC:** Kevin M. Moerman
> 
> **Author instructions**
> 
> Thanks for submitting your paper to JOSS @dipongkor. **Currently, there isn't an JOSS editor assigned** to your paper.
> 
> @dipongkor if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).
> 
> **Editor instructions**
> 
> The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:
> 
> ```
> @whedon commands
> ```

zedtaha

**Comment by dipongkor** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by dipongkor** [comment]
@Kevin-Mattheus-Moerman Thanks for your comments. Please find the statement of the need and research application. I have added **Statement of the Need** section in the paper.  

> Most of the plagiarism detection tools available for text plagiarism detection are not freely
> available. However, freely available plagiarism checkers (e.g. Small Seo, PlagScan, and Plagiarisma) impose some text limits. Moreover, none of the existing tools aim is to serve busy
> academics who want to make sure that the reports or assignments they are marking is as
> plagiarism free as possible. The software throws light on the immense research potential in
> this field for developing efficient intelligent detection systems so as to curb unethical acts in
> students’ assignments as well as in examination papers. Furthermore, the software can be
> used as a base tool for detecting plagiarism in different languages.

**Comment by dipongkor** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02150/joss.02150/10.21105.joss.02150.pdf)

**Comment by CBenghi** [comment]
Hello @dipongkor,

since you tagged me in the thread I'm feeling it's appropriate to chip in.

My view is that your update is far from addressing the concerns expressed by @Kevin-Mattheus-Moerman 

> Most of the plagiarism detection tools available for text plagiarism detection are not freely
> available. However, freely available plagiarism checkers (e.g. Small Seo, PlagScan, and Plagiarisma) > impose some text limits. Moreover, none of the existing tools aim is to serve busy
> academics who want to make sure that the reports or assignments they are marking is as
> plagiarism free as possible. 

As stated, this looks more like a commercial problem that educators face than a research issue.

> The software throws light on the immense research potential in this field 

What is the research field exactly?
Can you provide examples of publications or research projects that might benefit from the tool?
While we all appreciate enthusiastic approaches, I'd also invite you to use a more constrained language, words such as ```Immense```, should perhaps be used more sparingly in academic and research environments.

> for developing efficient intelligent detection systems so as to curb unethical acts in
> students’ assignments as well as in examination papers.  Furthermore, the software can be
> used as a base tool for detecting plagiarism in different languages.

Again, this seems to be a clear application domain, but not one that has obvious research outcomes.

Finally, and perhaps most significantly, you have not clearly addressed the concerns around the significance of the software (i.e. the one related to half-baked solutions).
Have you evaluated how the features provided compare with the feature lists of the checkers that are available on the market (e.g. turnitin, PlagScan and similar)

Would you please revise carefully the guidance found at https://joss.readthedocs.io/en/latest/submitting.html, before updating the submission again?

Best regards,
Claudio

**Comment by danielskatz** [comment]
@dipongkor - we've decided to reject this submission as out of scope for JOSS because of its focus on students, not research, as well as the potential reviewer comments.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
