### ISSUE TITLE
[PRE REVIEW]: Pydiogment: A Python package for audio augmentation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2151]
**Submitting author:** @SuperKogito (<a href="http://orcid.org/0000-0002-5610-9086">Ayoub Malek</a>)
**Repository:** <a href="https://github.com/SuperKogito/pydiogment" target ="_blank">https://github.com/SuperKogito/pydiogment</a>
**Version:** v0.1.0
**Editor:** @mbobra
**Reviewers:** @bmcfee, @justinsalamon
**Managing EiC:** Daniel S. Katz

**Author instructions**

Thanks for submitting your paper to JOSS @SuperKogito. **Currently, there isn't an JOSS editor assigned** to your paper.

@SuperKogito if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/s41592-019-0686-2 is OK
- 10.21437/interspeech.2019-2680 is OK
- 10.5281/zenodo.3607820 is OK
- 10.1016/j.specom.2005.10.004 is OK
- 10.1109/IAdCC.2013.6514336 is OK
- 10.1016/j.procs.2015.10.020 is OK
- 10.1109/ICACDOT.2016.7877753 is OK
- 10.1109/TENCON.2008.4766487 is OK
- 10.1201/9781315219707 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02151/joss.02151/10.21105.joss.02151.pdf)

**Comment by danielskatz** [comment]
I've suggested a bunch of small changes in https://github.com/SuperKogito/pydiogment/pull/6, and pointed out one phrase that I don't understand

**Comment by SuperKogito** [comment]
Suggestions for potential reviewers: desilinguist, rougier, krother, sealhuang, ahurriyetoglu, or jkahn.

**Comment by mbobra** [comment]
@whedon assign @mbobra as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by faroit** [comment]
@mbobra I would also like to bring up @justinsalamon the author of [scaper](https://github.com/justinsalamon/scaper) and @bmcfee the author of [muda](https://github.com/bmcfee/muda) which are both software packages with a very similar use case. I think it would be important to include one of them as reviewers to reduce the overlap between these packages.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by mbobra** [comment]
@whedon assign @bmcfee as reviewer

**Comment by whedon** [comment]
OK, @bmcfee is now a reviewer

**Comment by mbobra** [comment]
@whedon add @justinsalamon as reviewer

**Comment by whedon** [comment]
OK, @justinsalamon is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2167.
