### ISSUE TITLE
[PRE REVIEW]: MDBED: An R package for simulating the Moran-Downton bivariate exponential   distribution

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2155]
**Submitting author:** @lfduquey (<a href="http://orcid.org/0000-0002-0367-8496">Luis F. Duque</a>)
**Repository:** <a href="https://github.com/lfduquey/MDBED" target ="_blank">https://github.com/lfduquey/MDBED</a>
**Version:** 1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**Author instructions**

Thanks for submitting your paper to JOSS @lfduquey. **Currently, there isn't an JOSS editor assigned** to your paper.

@lfduquey if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2155 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
👋 @openjournals/dev - can you fix the submitting author please?  (it's a URL rather than a github handle)

**Comment by danielskatz** [comment]
@lfduquey - can you try again?

The repository should be https://github.com/lfduquey/MDBED

**Comment by lfduquey** [comment]
@danielskatz I have submitted the paper again.

**Comment by lfduquey** [comment]
@danielskatz  I am sorry, it is my first time I submit a paper in this journal, and I have made several mistakes. The system asks me this information when submitting the paper:
•	Title: MDBED: An R package…
•	Repository address: https://github.com/lfduquey/MDBED
•	Software version: 1.0.0
•	Suggested editor: 
In the last discussion, you suggested to me to include my GitHub handle, so I do not understand where I should put it. Please, can you tell me what I am doing wrong?

**Comment by arfon** [comment]
@lfduquey @danielskatz - I've fixed up the metadata on this submission. Let's stick with this one rather than using the resubmission.

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (277.9 files/s, 22283.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              1              0              2            441
R                               12            185            404            293
Markdown                         3             50              0            128
TeX                              2              0              0            118
YAML                             3             21              8             60
Rmd                              2             27             70             37
-------------------------------------------------------------------------------
SUM:                            23            283            484           1077
-------------------------------------------------------------------------------


Statistical information for the repository '2155' was gathered on 2020/03/10.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02155/joss.02155/10.21105.joss.02155.pdf)

**Comment by lfduquey** [comment]
Thank you @arfon.

**Comment by danielskatz** [comment]
@lfduquey - you need to have an OSI-approved license in your repository.  See the first bullet in https://joss.readthedocs.io/en/latest/submitting.html#typical-paper-submission-flow

**Comment by danielskatz** [comment]
Additionally, I because of the small amount of code here, this could be viewed as out of the scope of JOSS.  Specifically, https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements includes 
> The software should be feature-complete (no half-baked solutions) and designed for maintainable extension (not one-off modifications). Minor ‘utility’ packages, including ‘thin’ API clients, and single-function packages are not acceptable.

Can you explain why you think this does not apply to your submission?

**Comment by lfduquey** [comment]
Dear @danielskatz, the MDBED has been accepted in CRAN, and it is made up of seven functions.  It describes the bivariate exponential distribution (BED) entirely, to the best of my knowledge, there is not a statistical free software that does it. The BED has been used in many areas such as reliability, queueing systems, or hydrology; this package can be, therefore, considered as an excellent research tool for these areas. Based on this explanation, I think the MDBED R package cannot be viewed either as Minor ‘utility’ package or as a single-function package, and it is within the scope of JOSS.  

Regards.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by danielskatz** [comment]
@lfduquey - The JOSS editors have decided that this remains out of scope for JOSS review.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by lfduquey** [comment]
@danielskatz Thank you for letting me know.
