### ISSUE TITLE
[PRE REVIEW]: ldaPrototype: A method in R to get a Prototype of multiple Latent Dirichlet Allocations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2156]
**Submitting author:** @JonasRieger (<a href="http://orcid.org/0000-0002-0007-4478">Jonas Rieger</a>)
**Repository:** <a href="https://github.com/JonasRieger/ldaPrototype" target ="_blank">https://github.com/JonasRieger/ldaPrototype</a>
**Version:** v0.1.1
**Editor:** @karthik
**Reviewers:** @tommyjones
**Managing EiC:** Daniel S. Katz

**Author instructions**

Thanks for submitting your paper to JOSS @JonasRieger. **Currently, there isn't an JOSS editor assigned** to your paper.

@JonasRieger if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.05 s (658.1 files/s, 65405.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               29            309           1125           1683
Markdown                         3             30              0            110
TeX                              1              9              0            105
YAML                             1              2              0              6
-------------------------------------------------------------------------------
SUM:                            34            350           1125           1904
-------------------------------------------------------------------------------


Statistical information for the repository '2156' was gathered on 2020/03/10.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.3591068 is OK
- 10.21105/joss.00135 is OK
- 10.18637/jss.v040.i13 is OK
- 10.1073/pnas.0307752101 is OK
- 10.1162/jmlr.2003.3.4-5.993 is OK
- 10.1145/2133806.2133826 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02156/joss.02156/10.21105.joss.02156.pdf)

**Comment by danielskatz** [comment]
👋 @JonasRieger - thanks for your submission.  I will now find an editor for it.  While I do so, can you:

1. fix the cases in the references, using {}s to protect cases, along with any other proofreading of the paper. When you have made changes, you can add a new comment here with ```@whedon generate pdf``` to see the built pdf.  One example is "tools for r" which should be "tools for R"

1. Suggest potential reviewers - please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by danielskatz** [comment]
@whedon invite @mbobra as editor

I know this is a second current invitation, but I promise no more this week :)

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by mbobra** [comment]
@danielskatz I don't know R at all, and I don't think that's fair to the submitting author, so I'll decline this one. I accepted the other invitation.

**Comment by danielskatz** [comment]
👋 @karthik - can you take this one?

**Comment by JonasRieger** [comment]
> 
> 
> 👋 @JonasRieger - thanks for your submission. I will now find an editor for it. While I do so, can you:
> 
>     1. fix the cases in the references, using {}s to protect cases, along with any other proofreading of the paper. When you have made changes, you can add a new comment here with `@whedon generate pdf` to see the built pdf.  One example is "tools for r" which should be "tools for R"
> 
>     2. Suggest potential reviewers - please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

1. done
`@whedon generate pdf`
2. kbenoit would definitely fit as reviewer, cmaimone could also fit according to the given list. Maybe bagheria or lmullen could also fit.

**Comment by JonasRieger** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02156/joss.02156/10.21105.joss.02156.pdf)

**Comment by karthik** [comment]
Sure

**Comment by karthik** [comment]
@@whedon assign @karthik as editor

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by karthik** [comment]
Pinged `@cpsievert` to review over email

**Comment by karthik** [comment]
@JonasRieger Do you have any reviewer suggestions that do not result in a conflict of interest? If so please suggest names.

**Comment by JonasRieger** [comment]
> 
> 
> @JonasRieger Do you have any reviewer suggestions that do not result in a conflict of interest? If so please suggest names.

kbenoit, cmaimone, bagheria, lmullen

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by karthik** [comment]
@whedon assign @tommyjones as reviewer

**Comment by whedon** [comment]
OK, @tommyjones is now a reviewer

**Comment by TommyJones** [comment]
All, I am reviewing this weekend. If I do or do not complete it this weekend, I will update the channel. Thank you for your patience!

**Comment by arfon** [comment]
@karthik should we go ahead and set up the review issue for @TommyJones?

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2181.

**Comment by arfon** [comment]
@TommyJones - please head over to #2181 where the actual review will take place. @karthik - this paper still needs a second reviewer when you get a chance.

**Comment by karthik** [comment]
@arfon sorry I missed this (was out quite sick). Yes glad Tommy posted the review. I was still waiting on reviewer 2 but am happy to proceed with this review.

**Comment by karthik** [comment]
In fact I hadn't started the review yet since I did not have reviewer 2 in place yet.

**Comment by arfon** [comment]
Hope you're feeling better soon @karthik - I moved this forward as I wasn't sure what your availability was. When you have the bandwidth, we'll still need to find a second reviewer here.

**Comment by karthik** [comment]
👋 @bstewart 
Would you be able to serve as a second reviewer on this submission?

**Comment by bstewart** [comment]
Sure- I will likely be a bit slower and if someone could direct me to the guidelines/expectations I'd be grateful.  But happy to help out.
