### ISSUE TITLE
[PRE REVIEW]: MPA: a novel cross-language API for time series analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2159]
**Submitting author:** @vanbenschoten (<a href="http://orcid.org/0000-0002-7944-6237">Andrew Van Benschoten</a>)
**Repository:** <a href="https://github.com/matrix-profile-foundation/joss_paper" target ="_blank">https://github.com/matrix-profile-foundation/joss_paper</a>
**Version:** Misc (multiple repos)
**Editor:** @arfon
**Reviewers:** @coljac, @krystophny
**Managing EiC:** Daniel S. Katz

**Author instructions**

Thanks for submitting your paper to JOSS @vanbenschoten. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arfon.

@vanbenschoten if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/ICDM.2016.0179 is OK
- 10.1109/ICDM.2016.0085 is OK
- 10.1109/ICDM.2017.21 is OK
- 10.1109/ICDM.2018.00099 is OK
- 10.1109/ICDM.2018.00119 is OK
- 10.1109/ICBK.2018.00058 is OK
- 10.1109/ICBK.2019.00031 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02159/joss.02159/10.21105.joss.02159.pdf)

**Comment by danielskatz** [comment]
👋 @vanbenschoten - Where is the software that you want to have reviewed as this submission?

**Comment by vanbenschoten** [comment]
@danielskatz there are three individual repos that comprise the software described in our paper. The manuscript is in matrix-profile-foundation/joss_paper, and the actual codebases are:

1. matrix-profile-foundation/tsmp
2. matrix-profile-foundation/go-matrixprofile
3. matrix-profile-foundation/matrixprofile

I connected with @arfon last week about how to handle this situation, and he advised me that submitting the manuscript in a separate repo was the recommended approach.

Let me know if there are any further questions!

**Comment by danielskatz** [comment]
👋 @arfon, do you want to handle this as editor? (you were suggested by the authors)

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @vanbenschoten - thanks for your could your submission to JOSS. Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by vanbenschoten** [comment]
@arfon here's a list of some folks who I think would be good reviewers:

wrathematics
suyashkumar
vc1492a
robohyun66
marksantcroos
galenstocking
ionlights
jkahn

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by vanbenschoten** [comment]
@arfon thanks for the notification! We're in a good spot to continue the article's review (but we understand that things might be crazy on your end, so no rush :) )

**Comment by arfon** [comment]
@suyashkumar, @robohyun66, @galenstocking, @ionlights - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by vanbenschoten** [comment]
Hi @arfon! Wanted to circle back regarding our review. I realize folks are super busy right now, so would it be help if I added a few more suggested reviewers? Thanks!

**Comment by arfon** [comment]
Sure thing, that would be helpful. Thanks @vanbenschoten.

**Comment by vanbenschoten** [comment]
Apologies for the delay! Below are 5 other potential reviewers:

bliiir
yzhao062
Sirjla
krystophny
coljac

**Comment by arfon** [comment]
@bliiir @yzhao062 @Sirjla @krystophny @coljac - - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

This review would need you to inspect code in a [small number of repositories](https://github.com/openjournals/joss-reviews/issues/2159#issuecomment-597276663):

- https://github.com/matrix-profile-foundation/tsmp
- https://github.com/matrix-profile-foundation/go-matrixprofile
- https://github.com/matrix-profile-foundation/matrixprofile

...and the paper explaining how they relate is available [here](https://github.com/openjournals/joss-papers/blob/joss.02159/joss.02159/10.21105.joss.02159.pdf).

**Comment by vanbenschoten** [comment]
Hi Arfon,
   Any update on the publication front? We're getting to the point where we
need to DOI to continue other lines of work. Thanks!

-Andrew

**Comment by arfon** [comment]
> Any update on the publication front? 

I'm afraid not sorry - it looks like we're really struggling to get any traction here with potential reviewers. This could be due to people struggling to keep up with life/their day jobs during the pandemic, or lack of interest/availability to review. Let me try another couple of folks here...

**Comment by arfon** [comment]
@wrathematics @jkahn - would you be willing to review this submission for JOSS? As past JOSS reviewers, you'll hopefully recall we carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

This review would be of the MPA project which aims to help researchers with analyzing time series data. The code is in a [small number of repositories](https://github.com/openjournals/joss-reviews/issues/2159#issuecomment-597276663):

- https://github.com/matrix-profile-foundation/tsmp
- https://github.com/matrix-profile-foundation/go-matrixprofile
- https://github.com/matrix-profile-foundation/matrixprofile

...and the paper explaining how they relate is available [here](https://github.com/openjournals/joss-papers/blob/joss.02159/joss.02159/10.21105.joss.02159.pdf).

**Comment by coljac** [comment]
I'll be take this one on if the editors would like. I didn't pipe up before as I'm not an R user, but I'll figure that part of it out.

**Comment by vanbenschoten** [comment]
@coljac thanks so much! We really appreciate it!

**Comment by jkahn** [comment]
Not a good one for me; R is far enough out of my wheelhouse to make it
difficult for me to compare to existing work.

**Comment by arfon** [comment]
> Not a good one for me; R is far enough out of my wheelhouse to make it
> difficult for me to compare to existing work.

Got it, thanks for responding @jkahn 

> I'll be willing take this one on if the editors would like. I didn't pipe up before as I'm not an R user, but I'll figure that part of it out.

@coljac - many thanks! I'll add you as a reviewer now but won't start the actual review process until we have identified a second reviewer.

**Comment by arfon** [comment]
@whedon add @coljac as reviewer

**Comment by whedon** [comment]
OK, @coljac is now a reviewer

**Comment by vanbenschoten** [comment]
@arfon I can find some more potential reviewers if that'd be helpful.

**Comment by arfon** [comment]
> @arfon I can find some more potential reviewers if that'd be helpful.

Yes please @vanbenschoten.

**Comment by vanbenschoten** [comment]
ryEllison
mattbesancon
nidhog
osolari
zaxtax
mirca

**Comment by krystophny** [comment]
@vanbenschoten @arfon sorry, your mail slipped my inbox beginning of April. Do you still need reviewers? If yes, I'd be happy to do it! Best, Chris

**Comment by arfon** [comment]
@krystophny - yes please!

**Comment by arfon** [comment]
@whedon add @krystophny as reviewer

**Comment by whedon** [comment]
OK, @krystophny is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2179.

**Comment by arfon** [comment]
@coljac, @krystophny - thanks so much for agreeing to review this! See you and @vanbenschoten over in #2179 for the actual review.

**Comment by suyashkumar** [comment]
@arfon apologies for missing the review request. I've had my hands full recently, but I'll be available for around 1 review a month of capacity starting around end of May! 

Hope everyone is staying safe and healthy!
