### ISSUE TITLE
[REVIEW]: Fitting a Gamma-Gompertz survival model to capture-recapture data collected on free-ranging animal populations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#216]
**Submitting author:** @oliviergimenez (<a href="http://orcid.org/0000-0001-7001-5142">Olivier Gimenez</a>)
**Repository:** <a href="https://github.com/oliviergimenez/GammaGompertzCR" target ="_blank">https://github.com/oliviergimenez/GammaGompertzCR</a>
**Version:** v1.0.0
**Editor:** @karthik
**Reviewer:** @bbolker
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1154931" target="_blank">10.5281/zenodo.1154931</a>

## Status

[![status](http://joss.theoj.org/papers/c93e42d092f6ed4f66e3951c89136690/status.svg)](http://joss.theoj.org/papers/c93e42d092f6ed4f66e3951c89136690)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/c93e42d092f6ed4f66e3951c89136690"><img src="http://joss.theoj.org/papers/c93e42d092f6ed4f66e3951c89136690/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/c93e42d092f6ed4f66e3951c89136690/status.svg)](http://joss.theoj.org/papers/c93e42d092f6ed4f66e3951c89136690)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/oliviergimenez/GammaGompertzCR" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/oliviergimenez/GammaGompertzCR">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (oliviergimenez) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @bbolker it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @bbolker - how are you getting on with your review?

**Comment by bbolker** [comment]
it had slipped but am working on it and think I should be able to get it done shortly.  How granular would you like the issues in the target-repo issue list to be?  (One long issue with lots of bullet points?  One issue per item above? Somewhere in between?)

**Comment by karthik** [comment]
> (One long issue with lots of bullet points? One issue per item above? Somewhere in between?)

We'll leave that up to you. Somewhere in between would be best. A few issues grouped by theme would allow the authors to break that down further but also make it easy for you to reference here.

**Comment by bbolker** [comment]
I'm not sure if this is how I'm supposed to do it, but these issues constitute my "review"

- https://github.com/oliviergimenez/GammaGompertzCR/issues/2
- https://github.com/oliviergimenez/GammaGompertzCR/issues/3
- https://github.com/oliviergimenez/GammaGompertzCR/issues/4
- https://github.com/oliviergimenez/GammaGompertzCR/issues/5 (not necessarily blocking)
- https://github.com/oliviergimenez/GammaGompertzCR/issues/6 (non-blocking)

**Comment by karthik** [comment]
@bbolker 
🙏 a ton!

We don't have a set review style and we leave it up to the reviewers. 

@oliviergimenez Can you please address the issues raised by Dr. Bolker in those individual threads and present us with a summary here once you are done. That way @bbolker can check that he is satisfied with the changes and recommend an acceptance.

**Comment by karthik** [comment]
@bbolker PS: I'm sure you must have seen this GitHub trick, but if you mention `openjournals/joss-reviews/#216` anywhere is an issue on the author's repo, it automatically lists them here with you having to manually link them in the body of your review. That trick also works across repos. Syntax is just `user/repo/#issue_number`

**Comment by oliviergimenez** [comment]
Thanks a lot @bbolker. My co-author and I will address the issues you raised the best we can. I'm going to be busy over the next two weeks though, is the end of May working for you @karthik ? Cheers, Olivier.

**Comment by karthik** [comment]
@oliviergimenez Totally fine. Please update this thread when you have completed revisions, tagging me and Ben.

**Comment by oliviergimenez** [comment]
Dear @bbolker and @karthik,
First, apologies for taking so long to get back to you. The second semester of 2017 has been hectic. At last we had the chance to go through @bbolker's review over the Christmas break. @bbolker, our answers to your comments are attached. We have also submitted a new version of the package.
Thanks a lot for your time in reviewing our work.
Olivier & Gilbert

[bolker_review_with_answers.pdf](https://github.com/openjournals/joss-reviews/files/1612177/bolker_review_with_answers.pdf)

**Comment by bbolker** [comment]
These responses seem fine to me. I will go through and close the issues.

**Comment by bbolker** [comment]
I've left a couple of specific comments on the issues list. Everything else was fine.

**Comment by karthik** [comment]
Thanks @bbolker. Let me know when you are ok with signing off. 🙏

**Comment by oliviergimenez** [comment]
Dear @bbolker, cc @karthik, 
Thanks for closing all issues, your help has been very valuable.
Olivier & Gilbert

**Comment by oliviergimenez** [comment]
Hi @karthik,
Is there anything we can do now that Ben has closed all issues?
Cheers,
Olivier & Gilbert.

**Comment by karthik** [comment]
Hi @oliviergimenez
Congrats on getting your paper accepted! 🎉
At this point I would like you to archive your software in Zenodo and post the DOI here. Then I'll be able to set the archive and complete the final steps.

**Comment by oliviergimenez** [comment]
Hi @karthik,
That's great news! 🍾 ✨ 
I have just archived the software, the DOI is 10.5281/zenodo.1154931
Cheers,
Olivier

**Comment by karthik** [comment]
@whedon set 10.5281/zenodo.1154931 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1154931" target="_blank">10.5281/zenodo.1154931</a> is the archive.

**Comment by karthik** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by karthik** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00216/joss.00216/10.21105.joss.00216.pdf
```

**Comment by arfon** [comment]
@bbolker - many thanks for your review here and to @karthik for editing this one ✨ 

@oliviergimenez - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00216 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00216/status.svg)](https://doi.org/10.21105/joss.00216)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00216/status.svg)](https://doi.org/10.21105/joss.00216)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html

**Comment by oliviergimenez** [comment]
This is awesome, thank you all @whedon @bbolker @karthik.
