### ISSUE TITLE
[PRE REVIEW]: DALEXtra: Cross language model comparison 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2162]
**Submitting author:** @maksymiuks (<a href="http://orcid.org/0000-0002-3120-1601">Szymon Maksymiuk</a>)
**Repository:** <a href="https://github.com/ModelOriented/DALEXtra" target ="_blank">https://github.com/ModelOriented/DALEXtra</a>
**Version:** 0.2.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**Author instructions**

Thanks for submitting your paper to JOSS @maksymiuks. **Currently, there isn't an JOSS editor assigned** to your paper.

@maksymiuks if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.24 s (404.7 files/s, 103508.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            39           2323            510           9295
CSS                              4            983             62           6082
R                               34            411           1584           2123
Markdown                         3             83              0            357
JavaScript                       3             41             19            147
Rmd                              6            111            151            118
YAML                             5             12              0            118
SVG                              2              0              2             21
-------------------------------------------------------------------------------
SUM:                            96           3964           2328          18261
-------------------------------------------------------------------------------


Statistical information for the repository '2162' was gathered on 2020/03/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
maksymiuks                       2           217             10          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
maksymiuks                  207           95.4          0.0                9.18
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #2162 with the following error: 

 Can't find any papers to compile :-(

**Comment by maksymiuks** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02162/joss.02162/10.21105.joss.02162.pdf)

**Comment by danielskatz** [comment]
@maksymiuks - this paper appears incomplete: there are some sections without content.

**Comment by danielskatz** [comment]
Due to that, and to the very recent hiatus in JOSS receiving submissions, I'm going to push this back for now, and ask you to resubmit once we are accepting submissions again.  We welcome a resubmission of a complete paper in the future, once we are accepting submissions.

**Comment by danielskatz** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
