### ISSUE TITLE
[REVIEW]: MASTR-Quant: An Open-Source Web-based Software Tool for the Quantitive Analysis of Mass Spectrometry-based Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2163]
**Submitting author:** @MetabolomicsAustralia-Bioinformatics (<a href="http://orcid.org/0000-0003-3980-7496">Vinod Narayana</a>)
**Repository:** <a href="https://github.com/MetabolomicsAustralia-Bioinformatics/metabio" target ="_blank">https://github.com/MetabolomicsAustralia-Bioinformatics/metabio</a>
**Version:** 1.0
**Editor:** @csoneson
**Reviewer:** @lgatto, @bovee
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/f04578d60a5b2819d9894ee39dff909d/status.svg)](https://joss.theoj.org/papers/f04578d60a5b2819d9894ee39dff909d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f04578d60a5b2819d9894ee39dff909d"><img src="https://joss.theoj.org/papers/f04578d60a5b2819d9894ee39dff909d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f04578d60a5b2819d9894ee39dff909d/status.svg)](https://joss.theoj.org/papers/f04578d60a5b2819d9894ee39dff909d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/MetabolomicsAustralia-Bioinformatics/metabio" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@lgatto & @bovee, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MetabolomicsAustralia-Bioinformatics/metabio">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@MetabolomicsAustralia-Bioinformatics) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MetabolomicsAustralia-Bioinformatics/metabio">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@MetabolomicsAustralia-Bioinformatics) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lgatto, @bovee it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1038/nrg3575 may be missing for title: Systems genetics approaches to understand complex traits

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02163/joss.02163/10.21105.joss.02163.pdf)

**Comment by csoneson** [comment]
@lgatto, @bovee - thanks for accepting to review this submission! This is where the actual review takes place - your checklists are in the first post above, together with some more instructions. Just ping me if you have any questions. 

@lgatto - I'll paste your comments from the PRE-REVIEW issue below.

@MetabolomicsAustralia-Bioinformatics - please have a look at these comments. As I also mentioned in the PRE-REVIEW issue, the paper is currently a bit short for JOSS standards, and needs a bit more context.

And of course, as Arfon already commented in the PRE-REVIEW issue, due to the COVID-19 pandemic JOSS currently handles existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

**Comment by csoneson** [comment]
Comments from @lgatto, transferred from the PRE-REVIEW issue:

Here are my comments regarding this submission:

* The submission contains a repository (but see below) and a valid OSI approved license.
* I find the manuscript to be extremely short. In particular, I miss some citation/comparison with existing alternatives in general, and a description of this software compares to other commonly-used packages in this research area.
* There are no references.
* The documentation on the README page only contains installation instructions (which I have not tested). There is no information about the underlying implementations or core functionality. In particular, it seems the user is let to decide what regression type and parameters are best suited based on visual inspection of the fit, being also allowed to manually define outliers. More rigorous approaches such (standardised) residuals, leverage and/or Cook's distance might be applicable.
* The application is available at mastr-quant.bio21.unimelb.edu.au, which contains some basic documentation of how to use the web interface. I tried it twice but the application froze and became unresponsive. The web application contains test data for user to try the interface out, but there is no description of these test data.
* I managed to download result files, which seem to contain various forms of the data (raw, normalised, ...), at time poorly formatted (multiple table per sheet) and I could find any documentation describing the output file or how to use the results for downstream analyses.
* It is confusion that the repo to be reviewed is itself a fork of uncle-leng/metabio. There are only two contributors to either of the fork or original repository. It would be useful to document the contributions of the 9 authors.

I confirm that I have read the JOSS conflict of interest policy and that I have no COIs with reviewing this work.

**Comment by bovee** [comment]
I've done a preliminary review of the software and have some suggestions for improvement, but it appears GitHub issues are disabled on the repo (and there's no other documentation about how to make suggestions) so I'm unable to proceed.

**Comment by MetabolomicsAustralia-Bioinformatics** [comment]
Hi Roderick,

Thanks for your input. I’ve just enabled GitHub issues on the repo (a bit surprised it’s not enabled by default!)

Regards,

don

**Comment by csoneson** [comment]
> Hi all,
> Thanks for your time and effort in reviewing so far. Only about manuscript submission:
> 1. We actually have a larger, 2 page, manuscript written, as a pdf. I’ve restructured (in particular, cut down) this larger paper to the approximate size and formatting as recommended here: https://joss.theoj.org/papers/10.21105/joss.00388, where it looked like only a summary was needed. Should I be submitting the full manuscript instead?
> 2. As for lack of references: I’ve actually included references in paper.bib (https://github.com/MetabolomicsAustralia-Bioinformatics/metabio/blob/master/paper/paper.bib), as per the submission instructions.  Unfortunately, this won’t actually compile. In fact, the Whedon paper preview service provided won’t compile its own example either to contain References (the gala paper). An attempt as of a few minutes ago has received a 404 error.

> Just to address the manuscript issues, any advice to get around these technical issues would be greatly appreciated.

Hi @MetabolomicsAustralia-Bioinformatics (please post any further comments in this issue, the pre-review issue is closed). 
A typical JOSS paper is around 250-1000 words (your summary is currently ~170). However, it is not just a matter of the length in itself. I think your introduction needs to be expanded a bit to be understandable by a diverse, non-specialist audience and to provide the necessary context. As mentioned, we'd also like to have a brief discussion/comparison to other software addressing related needs. Please check https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain for more information. 

Could you provide more details about the compilation issues? What is going wrong? I am able to compile the paper on the preview service just now. However, you should cite the references in the paper to make them show up in the bibliography.

**Comment by MetabolomicsAustralia-Bioinformatics** [comment]
Hi @csoneson: thanks for your prompt reply. 

1. I'll be uploading our manuscript in the required format. Thanks!

2. I've just tried the paper preview service; pasting [this link](https://github.com/adrn/gala/tree/master/paper) into the "Paper repository address". It seems to compile fine, but clicking the "click here to download preview" link leads to a "Not Found" page.

**Comment by csoneson** [comment]
@MetabolomicsAustralia-Bioinformatics - the JOSS paper preview works fine for me if I just put the link to the repository (not the paper/ folder): https://github.com/adrn/gala

**Comment by arfon** [comment]
Yes, the form expects just the repository address. Whedon can find the paper within the repository.

**Comment by MetabolomicsAustralia-Bioinformatics** [comment]
Hi all,

Thanks for your input so far.

I’ve compiled and pushed the long-form paper.pdf to the repo, but it still lacks references, though paper.md and paper.bib are both in the same /paper dir in the repo.

I’m sensing that this is a silly syntax error on my part, but I can’t tell what I’m missing?

Many thanks and regards,
Don

**Comment by csoneson** [comment]
You need to use markdown syntax for the citations in `paper.md`. Like this (from the example paper):

```
# Citations

Citations to entries in paper.bib should be in
[rMarkdown](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)
format.

If you want to cite a software repository URL (e.g. something on GitHub without a preferred
citation) then you can do it with the example BibTeX entry below for @fidgit.

For a quick reference, the following citation commands can be used:
- `@author:2001`  ->  "Author et al. (2001)"
- `[@author:2001]` -> "(Author et al., 2001)"
- `[@author1:2001; @author2:2001]` -> "(Author1 et al., 2001; Author2 et al., 2002)"
```

**Comment by arfon** [comment]
:wave: @lgatto, @bovee  - just a friendly check-in to see how things are going with your reviews?

**Comment by lgatto** [comment]
I haven't been made aware that there was a revision to check.

**Comment by csoneson** [comment]
@lgatto - I don't think there is. 
@MetabolomicsAustralia-Bioinformatics - would you mind updating us on whether you had the chance to look at the reviewers' comments (and whether you were able to compile the paper with the above modifications)? Thanks!

**Comment by MetabolomicsAustralia-Bioinformatics** [comment]
Hi all, thanks for the reminder.

There’s been a full paper uploaded to the repo; I just haven’t provided any updates since I’m in the process of addressing reviewer comments re. better documentation, that I’ve done so far with sphinx (link in README).

However, the new, longer version still doesn’t compile with a complete references section. Is there some syntax error I’m missing? The .md and .bib files I used are in the repo.

Thanks,
don

**Comment by csoneson** [comment]
Thanks for the update @MetabolomicsAustralia-Bioinformatics. Did you try this:

> You need to use markdown syntax for the citations in `paper.md`. Like this (from the example paper):
> 
> ```
> # Citations
> 
> Citations to entries in paper.bib should be in
> [rMarkdown](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)
> format.
> 
> If you want to cite a software repository URL (e.g. something on GitHub without a preferred
> citation) then you can do it with the example BibTeX entry below for @fidgit.
> 
> For a quick reference, the following citation commands can be used:
> - `@author:2001`  ->  "Author et al. (2001)"
> - `[@author:2001]` -> "(Author et al., 2001)"
> - `[@author1:2001; @author2:2001]` -> "(Author1 et al., 2001; Author2 et al., 2002)"
> ```

**Comment by bovee** [comment]
Apologies for the delay; I made issues on the repo of things that I'd like to see before I can accept (in addition to the other changes in documentation and the paper requested), but forgot to link out here:

 - [ ] https://github.com/MetabolomicsAustralia-Bioinformatics/metabio/issues/1
 - [ ] https://github.com/MetabolomicsAustralia-Bioinformatics/metabio/issues/3
 - [ ] https://github.com/MetabolomicsAustralia-Bioinformatics/metabio/issues/4
 - [ ] https://github.com/MetabolomicsAustralia-Bioinformatics/metabio/issues/5

**Comment by MetabolomicsAustralia-Bioinformatics** [comment]
Hi Roderick,

Many thanks for your input. I’ll be getting onto these.

Regards,
Don

**Comment by arfon** [comment]
:wave: @MetabolomicsAustralia-Bioinformatics - how are you getting on responding to the review feedback thus far?

**Comment by csoneson** [comment]
@MetabolomicsAustralia-Bioinformatics - could you update us on the status of this submission? Thanks!

**Comment by MetabolomicsAustralia-Bioinformatics** [comment]
Hi all,

Apologies for the radio silence. I’ve been swamped so far as the only bioinformatician/ML analyst in my organisation.

I am working on a testing suite with Django’s built-in suite on a local build. I understand that we would preferably get to a point of automated testing. I’ve done my best to address the other points raised far re.:documentation, explanations for a non-technical audience.

Thanks and regards,
Don

**Comment by csoneson** [comment]
👋  @MetabolomicsAustralia-Bioinformatics - just checking in to clarify where we are here. Do I interpret the message above correctly in that you plan to add the test suite as well before the reviewers should take a second look at the submission?

**Comment by csoneson** [comment]
ping @MetabolomicsAustralia-Bioinformatics

> 👋 @MetabolomicsAustralia-Bioinformatics - just checking in to clarify where we are here. Do I interpret the message above correctly in that you plan to add the test suite as well before the reviewers should take a second look at the submission?

**Comment by MetabolomicsAustralia-Bioinformatics** [comment]
Many apologies, I thought I’d replied to this, but turns out that my email client (Spark) didn’t send out the reply!

Yes, please wait while a test-suite is written out. Apologies as well for any inconvenience.

Regards,
Don

**Comment by csoneson** [comment]
👋 @MetabolomicsAustralia-Bioinformatics - just checking in. Do you have an expected timeline for when you think your changes might be ready for the reviewers to take another look?

**Comment by csoneson** [comment]
ping @MetabolomicsAustralia-Bioinformatics 

> 👋 @MetabolomicsAustralia-Bioinformatics - just checking in. Do you have an expected timeline for when you think your changes might be ready for the reviewers to take another look?

**Comment by csoneson** [comment]
After offline interaction with the author, I will pause this submission for now.

**Comment by csoneson** [comment]
@MetabolomicsAustralia-Bioinformatics - do you think you will have the time to restart working on this submission within the next month or so? If not, in order to respect the reviewers' time and availability committment, I will propose to close (reject) this submission, and invite a resubmission at a later point in time.

**Comment by MetabolomicsAustralia-Bioinformatics** [comment]
Hi Charlotte,

Yup, I think it’s best to close this submission for the time being. You may receive a resubmission from this email address as and when this gets back up and running.

Many thanks and regards,

don

**Comment by csoneson** [comment]
Thanks @MetabolomicsAustralia-Bioinformatics - we will close this submission then. 
@lgatto, @bovee - thank you so much for your comments and contributions!

**Comment by csoneson** [comment]
@openjournals/joss-eics - we have agreed to close this submission. Could you help with that?

**Comment by kyleniemeyer** [comment]
@csoneson ok, I will withdraw this one.

**Comment by kyleniemeyer** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
