### ISSUE TITLE
[REVIEW]: BayesMFSurv: An R Package to Estimate Bayesian Split-Population Survival Models With (and Without) Misclassified Failure Events

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2164]
**Submitting author:** @Nicolas-Schmidt (<a href="http://orcid.org/0000-0001-5083-5792">Nicolás Schmidt</a>)
**Repository:** <a href="https://github.com/Nicolas-Schmidt/BayesMFSurv" target ="_blank">https://github.com/Nicolas-Schmidt/BayesMFSurv</a>
**Version:** v0.2.0
**Editor:** @marcosvital
**Reviewer:** @alletsee, @andybega
**Archive:** <a href="https://doi.org/10.5281/zenodo.3746286" target="_blank">10.5281/zenodo.3746286</a>

## Status

[![status](https://joss.theoj.org/papers/74b9f9b2449e9f9a2312c5606d7f4751/status.svg)](https://joss.theoj.org/papers/74b9f9b2449e9f9a2312c5606d7f4751)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/74b9f9b2449e9f9a2312c5606d7f4751"><img src="https://joss.theoj.org/papers/74b9f9b2449e9f9a2312c5606d7f4751/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/74b9f9b2449e9f9a2312c5606d7f4751/status.svg)](https://joss.theoj.org/papers/74b9f9b2449e9f9a2312c5606d7f4751)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Nicolas-Schmidt/BayesMFSurv" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@alletsee & @andybega, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @marcosvital know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Nicolas-Schmidt/BayesMFSurv">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Nicolas-Schmidt) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Nicolas-Schmidt/BayesMFSurv">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Nicolas-Schmidt) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @alletsee, @andybega it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/sj.bjc.6601118 is OK
- 10.32614/RJ-2017-056 is OK
- 10.1002/sim.687 is OK
- 10.1214/aos/1056562461 is OK
- 10.1111/j.1468-2478.2007.00469.x is OK
- 10.1213/ANE.0000000000003653 is OK
- 10.1111/j.1468-2478.2012.00719.x is OK
- 10.1017/pan.2019.6 is OK
- 10.1080/00401706.1998.10485509 is OK
- 10.1111/0020-8833.00137 is OK

MISSING DOIs

- https://doi.org/10.18637/jss.v092.i09 may be missing for title: spBayesSurv: Fitting Bayesian Spatial Survival Models Using R

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02164/joss.02164/10.21105.joss.02164.pdf)

**Comment by marcosvital** [comment]
Dear @alletsee and @andybega, thank you very much for accepting review this submission for JOSS.
Even if you are not starting the review right now, please accept the invite, as it has an expiration date (there is a link under **Reviewer instructions & questions** and you should also get an email notification). Furthermore, please check the instructions and checklists above, and let me know if you need any assistance. 

You can also tag @Nicolas-Schmidt and @Sergio-Bejar  if you need to ask specific questions about the submission.

**Comment by alletsee** [comment]
Dear @Nicolas-Schmidt and @Sergio-Bejar,

Thanks for submitting the software and this paper - and congratulations for publishing the academic paper in PA!

I'm currently reviewing the package and have a few minor questions:
- Tests: I couldn't see any automated testing integrated in the paper, but this is part of the JOSS checklist. Did I overlook something? Or can we maybe use something as a surrogate for this? (@marcosvital : would replicating the coefficients from the main example be acceptable for this point?)
- Community Guidelines: I understand that this is meant as an addition to an academic paper, so I wouldn't expect a massive developer community starting to extend the software. However, I think it might be good if you would add a note how users can report issues/problems or seek support (e.g. by recommending to open an issue on Github). Is this something that you might consider adding?
- Documentation, #1: In "Buhaugetal_2009_JCR.Rd", you refer to a "Gates et al. (2006)" paper for which I cannot find a proper citation. Could you please add this? (Note that you can add a "Reference" section to Rd files, which might be a convenient and user-friendly way.)
- Documentation, #2: Super-tiny detail, but I just spotted this and it's super-quick to fix. In "RBS.Rd", there is a missing white space for "Bernhard,Michael," in the source.

I hope that the questions/suggestions above are helpful for you and not much of a burden.
(As a quick status update: I still have to read the software paper and test the code to confirm functionality.)

Best regards,
Max

**Comment by Nicolas-Schmidt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02164/joss.02164/10.21105.joss.02164.pdf)

**Comment by Nicolas-Schmidt** [comment]
Dear @alletsee:
 
Thanks for your comments and questions.  They all are very helpful.  Below please find our response to your comments/queries.
 
1)   This is a good point.  We did not integrate any automatic testing into the paper due to space limitations.   But the README file of our package provides readers with examples that allow users to verify the functionality of the software.   We hope this is acceptable, and will be more than happy to add a sentence in the paper explaining where users can find such examples.
2)   We addressed this point by opening an issue on Github where users can report issues/problems or seek support. This can be found in the “DESCRIPTION” file on Github. 
3)   Thanks for raising this issue.  We indeed omitted the DOI of the Gates et al (2006) paper in our original submission.
4)   We fixed the issue related to the missing white space for “Bernhard, Michael,” in the source. 
5)    Further, the automatic compilation detected a missing DOI.  This has also been corrected as we added the aforementioned DOI.

Thanks again for your time and effort reviewing our submission!

**Comment by andybega** [comment]
Hi @Nicolas-Schmidt and @Sergio-Bejar,

I've opened a couple of issues in your repo; below are the ones I think are needed for the review/checklist. The others are suggestions that I think would make the package better, but I don't think it's needed for the review. 

- Duplicate Authors fields in DESCRIPTION https://github.com/Nicolas-Schmidt/BayesMFSurv/issues/2
- Missing `data()` call in README example https://github.com/Nicolas-Schmidt/BayesMFSurv/issues/3
- The package version referenced in the paper is 0.2.0. The version on CRAN is 0.1.0. Are you planning to submit 0.2.0 to CRAN before this review is over? Ok with me if not, but then I would ask you to fix two minor issues related to documentation and R check in https://github.com/Nicolas-Schmidt/BayesMFSurv/issues/1

One minor thing, for the paper, I think it would be helpful in the first paragraph to have 2 or so examples where mis-classified failures might be a problem. E.g. the civil war example from the PA paper (we don't really know that well how many people die in remote conflicts, so some civil wars might be coded as ended when they are not), and then maybe one other non-poli-sci example? Or I guess the democracy one in a pickle. 

### Testing

I guess ideally you'd have some combination of `testthat` unit tests and some kind of CI like travis. Since the package is pretty small and you have examples in the docs for the main functions that would show up in R check if they broke, maybe just having CI would meet this? 

When I cloned the repo and built the package from source, I found a missing dependency and some documentation that had to be updated (including changes to NAMESPACE). That would help you catch issues like this. 

(see e.g. `?usethis::use_travis(ext = "com")` for setup)

**Comment by alletsee** [comment]
Hi @Nicolas-Schmidt and @Sergio-Bejar,

I saw that you have included @andybega's suggestion of providing examples where misclassified failures are problematic; I second his suggestion and think that your edit addresses this well. (I think you have not yet generated a new article proof.)

Apart from this, I have only a few minor edit suggestions for the paper that are mainly about form:

- You introduce the "Misclassified Failure (MF)" abbreviation multiple times; introducing it once should be sufficient.
-  There are a few instances with in-text citation where the full citation appears in parentheses while the author names should be part of the main sentence: "As described below, (Bagozzi et al., 2019) develop a Bayesian parametric" in the second paragraph of the summary and "using a slice-sampling algorithm described in (Bagozzi et al., 2019)." in the first paragraph of the "BayesMFSurv R Package" chapter. It would be great if you could use proper in-text citation in those examples ([see here](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax).
- In the last paragraph of the "Motivation, Description, Applications" chapter, there is a citation in the middle of the sentence that looks like a formatting error: "our BayesMFSurv R package incorporates various functions listed below that fit (Bagozzi et al., 2019) parametric Misclassified Failure (MF) survival model via Bayesian MCMC methods." Did you maybe mean to have this at the end of the sentence
- There were sometimes minor inconsistencies in the capitalization of the journal names in the bibliography, for instance "International Studies Quarterly" vs. "British journal of cancer".

(As a quick update, I would still need to review the package functionality.)

**Comment by Sergio-Bejar** [comment]
Hi @andybega and @alletsee,

We have addressed all the points raised by you in your previous messages.   I already responded in detail to all the issues raised by @andybega in our Github repo (please see those responses here: [https://github.com/Nicolas-Schmidt/BayesMFSurv/issues](url).  Below, I respond to the points raised in this page.   

@andybega:

- We addressed points 1 and 2 as suggested by you.  
[https://github.com/Nicolas-Schmidt/BayesMFSurv/issues/2](url)
[https://github.com/Nicolas-Schmidt/BayesMFSurv/issues/3](url)

- We also responded to issue #1 raised by you. We believe that our response addresses the issues related with (i) documentation and (ii) R CMD checks that you found [https://github.com/Nicolas-Schmidt/BayesMFSurv/issues/1](url).   We believe that the issues you found prompted your comment related to using travis CI (see: **Testing**).  If this is not the case, please let us know. We will be happy to incorporate travis CI into the package.  

- Version 0.2.0 of our package is ready to be submitted to CRAN R, we wanted to first hear comments/suggestions from our reviewers in order to improve the package.  We plan to submit version 0.2.0 to CRAN R as soon as this review is over.  

- Following your suggestion, the revised version of our manuscript now includes three examples that illustrate when mis-classified failures might be a problem -see paragraph 2-.  Further, we also explain how such mis-classification may affect the results one obtains when using standard survival models. 

@alletsee:  

- We carefully edited the manuscript to address all your comments.  Specifically, we tried hard to avoid being redundant when mentioning the name of the model.  We also edited the citations in the the sections of the paper, and the bib file containing the references -i.e. being consistent with the capitalization of journal names, and adding the correct reference for Zhou et al (2020).   

Thanks again for all your comments and suggestions!

**Comment by Sergio-Bejar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02164/joss.02164/10.21105.joss.02164.pdf)

**Comment by andybega** [comment]
Hi @Nicolas-Schmidt and @Sergio-Bejar,

thanks for addressing the points raised. Two items I would like to keep open:

- Re the [1st issue, R check error](https://github.com/Nicolas-Schmidt/BayesMFSurv/issues/1) (summarizing for the benefit of others): using `devtools::document()` on the package leads R check to throw an error because RcppArmadillo (and Rcpp::sourceEval) are added to the NAMESPACE but RcppArmadillo is not in the DESCRIPTION. Thus you have been using `devtools::documents(roclets = 'rd')`, i.e. not using roxygen2 to generate the NAMESPACE. If I understand correctly, those two imports are not needed, and thus the preferable solution is to remove the directives in `mfsurv.R` that tell roxygen2 to import them. 
- Re testing: this was more about the **Automated tests** item in our review checklists. The idea is to make it easier to catch issues like that early. Like I said, I don't think you need full blown unit testing with `testthat`, but since it shouldn't be that much work to add Travis or some other CI, could you please go ahead and do it?

**Comment by Sergio-Bejar** [comment]
Hi @andybega, 

You are absolutely right!   We somehow missed those points, and we apologize for that.  

We have (i) removed the directives in `mfsurv.R` that tell roxygen2 to import them, and (ii) added Travis as suggested by you.

**Comment by andybega** [comment]
Hi, thanks. All good from my side. Thank you guys for addressing the issues, and thank you for implementing these models and making your software publicly available!

@marcosvital, my review is complete.

**Comment by Sergio-Bejar** [comment]
Hi @andybega !

Thanks again for your excellent and thorough comments.   We are happy to hear that you liked how we addressed your comments!  

Regards,
Sergio

**Comment by marcosvital** [comment]
Thank you very much for your detailed review, @andybega!

@alletsee , do you think that all the issues raised by you were addressed? Let us know if there is something else to be worked on.

**Comment by alletsee** [comment]
Hi all.

Thanks for taking the comments into account. I now found the time to re-read the article and run basic checks on functionality. From my perspective, all aspects mentioned above have been addressed thoroughly.

@Nicolas-Schmidt @Sergio-Bejar : Thank you for the effort of making this publicly available.

@marcosvital : my review is also complete.

**Comment by marcosvital** [comment]
Thank you very much for the effort put in reviewing, @alletsee.

@Nicolas-Schmidt and @Sergio-Bejar , we are almost there! Let's proceed with a reference checking.

**Comment by marcosvital** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1111/0020-8833.00174 is OK
- 10.1038/sj.bjc.6601118 is OK
- 10.32614/RJ-2017-056 is OK
- 10.1002/sim.687 is OK
- 10.1214/aos/1056562461 is OK
- 10.1111/j.1468-2478.2007.00469.x is OK
- 10.1213/ANE.0000000000003653 is OK
- 10.1111/j.1468-2478.2012.00719.x is OK
- 10.1017/pan.2019.6 is OK
- 10.1080/00401706.1998.10485509 is OK
- 10.18637/jss.v092.i09 is OK
- 10.1111/0020-8833.00137 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by marcosvital** [comment]
Good, all DOIs are ok!

@Nicolas-Schmidt and @Sergio-Bejar , I'll generate a (possibly) final proof. Please check if everything is ok with it. I'll read it myself too, and will let you know if I find something that should be fixed.

**Comment by marcosvital** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02164/joss.02164/10.21105.joss.02164.pdf)

**Comment by Sergio-Bejar** [comment]
@alletsee, thank you very much for the time and effort you put into the review process.  All your comments were excellent and they made our paper and package better.  

@marcosvital , we will take a good look into the article poof.    Thanks for generating it.  We will be in touch soon!

**Comment by Sergio-Bejar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02164/joss.02164/10.21105.joss.02164.pdf)

**Comment by Sergio-Bejar** [comment]
@marcosvital , I made a couple of minor changes in the paper (nothing major, please see proof generated above).  Please let me know if there's anything you'd like to change/add.   

Thanks!

**Comment by marcosvital** [comment]
Hello again, @Sergio-Bejar and @Nicolas-Schmidt, and sorry about the delay.

Everything looks fine for me, so we can move on to acceptance!

As one of our last steps, if you already didn't do this, you will need to archive the last release of the package (on Zenodo, figshare, or other of your choice). After that, post the version number and archive DOI here, and we can continue.

**Comment by Nicolas-Schmidt** [comment]
Hi @marcosvital , thanks for everything!
The package version is v0.2.0.
DOI is https://zenodo.org/badge/latestdoi/226979997

**Comment by marcosvital** [comment]
Hi, @Nicolas-Schmidt, sorry about the (yet another) late reply...

Let's move on, we are almost finished.

**Comment by marcosvital** [comment]
@whedon set 10.5281/zenodo.3746286 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3746286" target="_blank">10.5281/zenodo.3746286</a> is the archive.

**Comment by marcosvital** [comment]
@whedon set v0.2.0 as version

**Comment by whedon** [comment]
OK. v0.2.0 is the version.

**Comment by marcosvital** [comment]
Now I will recommend acceptance, and the Editors in Chief will be tagged.

**Comment by marcosvital** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1111/0020-8833.00174 is OK
- 10.1038/sj.bjc.6601118 is OK
- 10.32614/RJ-2017-056 is OK
- 10.1002/sim.687 is OK
- 10.1214/aos/1056562461 is OK
- 10.1111/j.1468-2478.2007.00469.x is OK
- 10.1213/ANE.0000000000003653 is OK
- 10.1111/j.1468-2478.2012.00719.x is OK
- 10.1017/pan.2019.6 is OK
- 10.1080/00401706.1998.10485509 is OK
- 10.18637/jss.v092.i09 is OK
- 10.1111/0020-8833.00137 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1430

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1430, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
I'll take this from here

**Comment by danielskatz** [comment]
@Nicolas-Schmidt - please merge https://github.com/Nicolas-Schmidt/BayesMFSurv/pull/6

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1111/0020-8833.00174 is OK
- 10.1038/sj.bjc.6601118 is OK
- 10.32614/RJ-2017-056 is OK
- 10.1002/sim.687 is OK
- 10.1214/aos/1056562461 is OK
- 10.1111/j.1468-2478.2007.00469.x is OK
- 10.1213/ANE.0000000000003653 is OK
- 10.1111/j.1468-2478.2012.00719.x is OK
- 10.1017/pan.2019.6 is OK
- 10.1080/00401706.1998.10485509 is OK
- 10.18637/jss.v092.i09 is OK
- 10.1111/0020-8833.00137 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02164/joss.02164/10.21105.joss.02164.pdf)

**Comment by danielskatz** [comment]
👋 @arfon - note that the previous accepted didn't see to complete, but I'm going to try a real accept anyhow...

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1253771361325064193) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1431
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02164](https://doi.org/10.21105/joss.02164)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @alletsee & @andybega for reviewing, and @marcosvital for editing!

Congratulations to @Nicolas-Schmidt and co-authors!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02164/status.svg)](https://doi.org/10.21105/joss.02164)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02164">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02164/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02164/status.svg
   :target: https://doi.org/10.21105/joss.02164
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02164/status.svg)](https://doi.org/10.21105/joss.02164)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
