### ISSUE TITLE
[REVIEW]: Pydiogment: A Python package for audio augmentation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2167]
**Submitting author:** @SuperKogito (<a href="http://orcid.org/0000-0002-5610-9086">Ayoub Malek</a>)
**Repository:** <a href="https://github.com/SuperKogito/pydiogment" target ="_blank">https://github.com/SuperKogito/pydiogment</a>
**Version:** v0.1.0
**Editor:** @mbobra
**Reviewer:** @bmcfee, @justinsalamon
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/d5430f38bce0b020c2715e118b3034e5/status.svg)](https://joss.theoj.org/papers/d5430f38bce0b020c2715e118b3034e5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d5430f38bce0b020c2715e118b3034e5"><img src="https://joss.theoj.org/papers/d5430f38bce0b020c2715e118b3034e5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d5430f38bce0b020c2715e118b3034e5/status.svg)](https://joss.theoj.org/papers/d5430f38bce0b020c2715e118b3034e5)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/SuperKogito/pydiogment" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@bmcfee & @justinsalamon, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mbobra know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SuperKogito/pydiogment">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@SuperKogito) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SuperKogito/pydiogment">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@SuperKogito) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @bmcfee, @justinsalamon it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/s41592-019-0686-2 is OK
- 10.21437/interspeech.2019-2680 is OK
- 10.5281/zenodo.3607820 is OK
- 10.1016/j.specom.2005.10.004 is OK
- 10.1109/IAdCC.2013.6514336 is OK
- 10.1016/j.procs.2015.10.020 is OK
- 10.1109/ICACDOT.2016.7877753 is OK
- 10.1109/TENCON.2008.4766487 is OK
- 10.1201/9781315219707 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02167/joss.02167/10.21105.joss.02167.pdf)

**Comment by mbobra** [comment]
@bmcfee @justinsalamon Thank you for agreeing to review this submission! Whedon generated a checklist and linked a reviewer guide above -- please let me know if you have any questions or comments. Feel free to message each other and the submitting author. And I know it is a difficult time to get work done; JOSS' position at the moment is that there is no pressure on reviewers or editors for the next 30 days. So feel free to take your time :)

**Comment by arfon** [comment]
@bmcfee, @justinsalamon - today we [reopened JOSS](https://blog.joss.theoj.org/2020/05/reopening-joss) for new submissions and are checking in on our existing reviews. Do you think you might be able to wrap up your reviews in the next 2-3 weeks?

**Comment by bmcfee** [comment]
@arfon absolutely, it's on my list for the end of this week, now that the semester's over.  Thanks for your patience!

**Comment by justinsalamon** [comment]
Yes, I'm OOO this week but will get it once I'm back, thanks!

**Comment by justinsalamon** [comment]
@arfon @SuperKogito @bmcfee @mbobra 

I've started my review (apologies for the delay), but pretty quickly hit some functionality issues.

Here are the issues I've created so far on the target repo:
* Missing installation instructions: https://github.com/SuperKogito/pydiogment/issues/9
* Missing docs on audio formats: https://github.com/SuperKogito/pydiogment/issues/10
* fade issue: https://github.com/SuperKogito/pydiogment/issues/12
* gain issue: https://github.com/SuperKogito/pydiogment/issues/13

Given the last two issues with functionality, should I continue with the review, or wait until they are addressed before continuing? I suspect this issue might impact other parts of the software and would like to avoid duplicating review work if at all possible. Thanks!

**Comment by mbobra** [comment]
@justinsalamon I'm sorry for my late response. If the functionality issues impact other parts of the software, let's wait for the submitting author to address them. 

@SuperKogito Do you need any help addressing the functionality issues raised by @justinsalamon? Or do you have any questions? Please let me know!

**Comment by SuperKogito** [comment]
@arfon @mbobra  @justinsalamon  @bmcfee,  thank you all for your assistance and reviews :heart:
@justinsalamon  @bmcfee raised quite a few interesting points, that will surely improve the library. 
@mbobra I think I can handle most of the required changes. The ones that concern me the most are the functionality issues raised by @justinsalamon. I am not sure yet about the complexity of those, although it is great to know that you got my back. So hopefully this weekend, I will find out if I can handle them and if I need assistance, I will be coming to you; at least for some advice. 
@HMMalek, I think we got a lot to do this weekend :smile:

**Comment by mbobra** [comment]
@SuperKogito I am going to pause this review. Pausing a review doesn't indicate anything negative -- it just tells the Editorial Board not to get worried that this review is taking longer than usual. Once you're done modifying the package, let me know here on this thread and I'll un-pause the submission.

**Comment by arfon** [comment]
@SuperKogito - do you think you will have the time to restart working on this submission within the next few weeks or so? If not, in order to respect the reviewers' time and availability committment, I will propose to close (reject) this submission, and invite a resubmission at a later point in time.

**Comment by SuperKogito** [comment]
This is very fair of you, I apologize for the long inactivity. I discussed this with the other contributor and we really like to try to close this -at the latest- by the end of November. We already implemented some of the requested changes, but didn't mention it in the issues yet. So my request is to give us a couple of more weeks as we work on the code and hopefully by November, this will be done & ready either for rejection or acceptance. However, if you think that a resubmission at a later point is a better option at this stage, then I will trust your decision.

**Comment by SuperKogito** [comment]
Unfortunately, we didn't manage to implement the requested changes at this point in time. Therefore, I think this should be closed as @arfon suggested and maybe we attempt a resubmission at a later point in time. I would like to thank this community, the editor @mbobra, the reviewers @bmcfee, @justinsalamon for their help, patience and the learning opportunity they provided us during this submission procedure. Maybe this one wasn't fruitful but hopefully the next ones will be. Thank you for your time and energy. Stay safe, stay healthy <3

**Comment by mbobra** [comment]
No worries @SuperKogito and thank you for submitting to JOSS! We look forward to your new submission. 

@openjournals/joss-eics Can we close (reject) this submission? The authors would like to continue working on it and re-submit at a later date.

**Comment by arfon** [comment]
@whedon reject

@bmcfee, @justinsalamon, @mbobra - thanks for all of your efforts here. Sorry it didn't work out @SuperKogito but as @mbobra said, we'd welcome a resubmission in the future here.

**Comment by whedon** [comment]
Paper rejected.
