### ISSUE TITLE
[REVIEW]: LTRpred: de novo annotation of intact retrotransposons

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2170]
**Submitting author:** @HajkD (<a href="http://orcid.org/0000-0002-1567-306X">Hajk-Georg Drost</a>)
**Repository:** <a href="https://github.com/HajkD/LTRpred" target ="_blank">https://github.com/HajkD/LTRpred</a>
**Version:** v1.1.0
**Editor:** @lpantano
**Reviewers:** @dcassol, @mdozmorov
**Archive:** <a href="https://doi.org/10.5281/zenodo.3895754" target="_blank">10.5281/zenodo.3895754</a>

## Status

[![status](https://joss.theoj.org/papers/eeb2359d2459d3ae448cafac3ae33211/status.svg)](https://joss.theoj.org/papers/eeb2359d2459d3ae448cafac3ae33211)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/eeb2359d2459d3ae448cafac3ae33211"><img src="https://joss.theoj.org/papers/eeb2359d2459d3ae448cafac3ae33211/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/eeb2359d2459d3ae448cafac3ae33211/status.svg)](https://joss.theoj.org/papers/eeb2359d2459d3ae448cafac3ae33211)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/HajkD/LTRpred" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dcassol, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/HajkD/LTRpred">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@HajkD) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/HajkD/LTRpred">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@HajkD) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dcassol it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02170/joss.02170/10.21105.joss.02170.pdf)

**Comment by lpantano** [comment]
@whedon add @mdozmorov as reviewer

**Comment by whedon** [comment]
OK, @mdozmorov is now a reviewer

**Comment by arfon** [comment]
:wave: @dcassol, @mdozmorov - just a friendly check-in to see how things are going with your reviews?

**Comment by mdozmorov** [comment]
The package has installation problems, the issues have been opened https://github.com/HajkD/LTRpred/issues/14, https://github.com/HajkD/LTRpred/issues/13. The review will continue when the package will be possible to test

**Comment by HajkD** [comment]
Dear all,

with the most recent `Dockerfile` on GitHub it is now possible to run all examples shown in the manuscript. As well as playing with all `LTRpred` functions.

https://github.com/HajkD/LTRpred/blob/master/Dockerfile

This Dockerfile can be used to create a `ltrpred` Docker container as follows:

```sh
# assuming the Dockerfile is in the current working directory
docker build -t ltrpred .
# running ltrpred container
docker run --rm -ti ltrpred
# open R
:/app# R
```
Now in the R prompt:
```r
# all tools are installed and the example LTRpred::LTRpred(...) run etc can be used
LTRpred::LTRpred(genome.file = system.file("Hsapiens_ChrY.fa", package = "LTRpred"))
```

What is missing and I would like to add is the ability to copy a local genome `fasta` file to the running `ltrpred` docker image. In addition, I think it could be nice and useful for users to be able to communicate with the `ltrpred` docker image via `RStudio`. For this purpose, I am implementing an interface between the `ltrpred` docker image and `RStudio`.

The core functionality of `LTRpred`, however, can now be used.

I hope this helps to make it easier to interact with this package.

I will try to have the final interfaces (ltrpred docker/RStudio and local file copy to ltrpred docker)
running in the next few days.

Many thanks!

**Comment by HajkD** [comment]
P.S. I will also push the final docker image to `Docker Hub` so that users can easily retrieve `LTRpred`.

**Comment by HajkD** [comment]
Dear all,

Please accept my apologies for being silent for a while, but I wanted to make sure that this time I can deliver a complete and interactive `ltrpred` container toolkit rather than a `Dockerfile` prototype. 

As a result, I developed two types of `ltrpred` containers which are available at `Docker Hub`:

1) Running the `LTRpred` pipeline through the `R command line prompt`: https://hub.docker.com/repository/docker/drostlab/ltrpred/.
2) Running the `LTRpred` pipeline through an RStudio Server interface: https://hub.docker.com/repository/docker/drostlab/ltrpred_rstudio.

I now documented in detail how to install, interact, and run both types of docker images here:
https://hajkd.github.io/LTRpred/articles/Introduction.html#ltrpred-docker-container

A minimal example to get you started right away is the following:

```bash
# retrieve docker image from dockerhub
docker pull drostlab/ltrpred
# run ltrpred container
docker run --rm -ti drostlab/ltrpred
# start R prompt within ltrpred container
~:/app# R
```

Within the ltrpred container R prompt run the `ltrpred` example:

```r
LTRpred::LTRpred(genome.file = system.file("Hsapiens_ChrY.fa", package = "LTRpred"))
```

The RStudio variant can be found here:
https://hajkd.github.io/LTRpred/articles/Introduction.html#download-ltrpred_rstudio-container-for-use-with-rstudio-server

It took me a while to find the best way to allow users to run `ltrpred` through a `RStudio Server` interface, but I think the solution presented here should make it as easy as possible to use the `ltrpred` pipeline with `RStudio`.

I would like to express my gratitude for this brilliant suggestion and I am sure that future users will appreciate having access to a pipeline environment where all tool dependencies are preinstalled. 

I am very well aware that the `ltrpred` pipeline depends on a large number of other tools, but 
the new functionality and analyses that can be performed thanks to the integration of all these tools are very useful for `transposable element` research and the type of annotation and analysis output generated by `ltrpred` was urgently needed.

I now very much look forward to hearing your feedback regarding the pipeline and further ways to improve it.

Your help and efforts are very much appreciated!

Many thanks,

Hajk

**Comment by mdozmorov** [comment]
The software LTRpred software for annotation of retrotransposons within genomic sequences is fully functional. The author should be applauded for the amount of effort to make the software accessible to users. Besides the original purpose, the GitHub repository contains good examples of complex Docker files that automate the installation of dependencies and enable the use of the software both in the command line and via the RStudio interface. The documentation is up-to-date. The manuscript accurately describes the functionality of LTRpred. @whedon accept

**Comment by lpantano** [comment]
@dcassol , how is your reviewing coming? Could you give us some update?

**Comment by dcassol** [comment]
@lpantano Yes, by the end of the week I can give you feedback. Thanks!

**Comment by lpantano** [comment]
@dcassol, just asking for an update on this, thanks.

**Comment by dcassol** [comment]
I made small comments here: HajkD/LTRpred#17
@lpantano How can I make comments on the article? Find a typo.

**Comment by lpantano** [comment]
you can open an issue there as well since the source of the paper is in their repo: https://github.com/HajkD/LTRpred/blob/master/paper.md

**Comment by dcassol** [comment]
LTRpred pipeline focuses on the annotation of retrotransposons and retrieving structurally intact elements within any sequence of genomes. The software fulfills all the required checkboxes for the review. In particular, I am impressed with the availability of the Docker container for the package which makes the installation and running process much more easer, special for users with less programming skills. The author also provides the possibility of deploying the software both in the command line and via the RStudio interface. Also, the paper is well written and the code is clear, easy to use, and properly documented.

**Comment by lpantano** [comment]
Hi  @HajkD, let me know when the issues are addressed and closed so I can move forward with the acceptance :)

**Comment by HajkD** [comment]
Dear Lorena,

Thank you so much for handling the editorial process of the `LTRpred` manuscript despite the ongoing Covid19 pandemic. I very much appreciate your efforts to keep the review process as smoothly as possible.

I now addressed all remaining suggestions raised by Dani and would wait for her approval and closure of the last issue.

Dear  Mikhail and Dani,

I am truly grateful for all your excellent suggestions and for catching all shortcomings of the `LTRpred` functionality.

I am convinced that your efforts have vastly increased the accessibility of `LTRpred` to a much wider life science audience and it taught me to always go the extra mile from now on and build a container for all my tools.

I hope that the review process didn't disrupt your daily adjustments to the Covid19 pandemic too much and I will always be grateful to all of you for your continued service to the academic cycle.

With the warmest wishes,
Hajk

**Comment by HajkD** [comment]
Dear Lorena,

all issues all closed now.

Thank you very much for arranging the next steps of the submission process.

Best wishes,
Hajk

**Comment by lpantano** [comment]
@whedon check references

**Comment by lpantano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2170 with the following error:

**Comment by lpantano** [comment]
perfect! meanwhile we solve this technical issues, @HajkD can you confirm the current version of your tool?

**Comment by HajkD** [comment]
Brilliant! Thank you very much!

I can confirm that the current version of `LTRpred` is `v1.1.0`.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02170/joss.02170/10.21105.joss.02170.pdf)

**Comment by HajkD** [comment]
Dear @arfon 

Thank you for generating the article proof. I can confirm that the text and formatting are correct and as they are supposed to be. Just a very quick question: Would it be possible to rotate __Figure 1__? Is there a way I can control the figure rotation in the Markdown file? I was trying a few LateX tricks, but they didn't work. This isn't absolutely necessary, but would make the manuscript as flawless as possible.

Your help with this is truly appreciated!

Many thanks,
Hajk

**Comment by arfon** [comment]
Hrmm, I'm not sure sorry @HajkD. I don't think it's possible to rotate with Markdown/Pandoc. Perhaps it has something to do with the figure being a PDF? Could you try converting it to a PNG and see if that preserves the correct rotation?

BTW, you can experiment with paper compilation either here (which creates some notification noise for all parties) or using our preview service at http://whedon.theoj.org

**Comment by HajkD** [comment]
Brilliant! Thank you very much! I will try this option and will come back to all of you soon.

**Comment by HajkD** [comment]
Dear @arfon 

The trick worked like a charm!

Thank you so much for your help with this!

I added the PNG figure change to the Markdown file. The manuscript is perfect now.

Many thanks,
Hajk

**Comment by lpantano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02170/joss.02170/10.21105.joss.02170.pdf)

**Comment by lpantano** [comment]
@whedon check references

**Comment by lpantano** [comment]
@HajkD, can you make a Zenodo archive and send me the link. The title and the authors should match the paper information. I think you can sync Zenodo with the releases and it will create one archive link for each release. Thanks!

**Comment by HajkD** [comment]
Dear @lpantano 

I just created a LTRpred release for the GitHub repo and created a Zenodo archive.

The corresponding link is as follows:

https://doi.org/10.5281/zenodo.3895754

Thank you very much for arranging the next steps!

With very best wishes,
Hajk

**Comment by lpantano** [comment]
thank you. But I think we need an archive without tar the content. It should look like this: https://zenodo.org/record/3755304

**Comment by HajkD** [comment]
Dear Lorena,

Thank you very much for making me aware of this. 

In my last JOSS paper I also submitted a `*.tar.gz` file, since this is the source format for R packages:

https://zenodo.org/record/1286221#.XunyeZ4zahc

Would it be possible to check wether there is a way to use `*.tar.gz` files in JOSS, because the Zenodo policy states:

`Note: File addition, removal or modification are not allowed after an upload has been published. This is because a Digital Object Identifier (DOI) is registered with  DataCite for each upload.`

Thank you very much for your help with this and I apologise if I have caused any additional work.

With very best wishes,
Hajk

**Comment by lpantano** [comment]
@whedon set 10.5281/zenodo.3895754 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3895754" target="_blank">10.5281/zenodo.3895754</a> is the archive.

**Comment by lpantano** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2170 with the following error: 

 E, [2020-06-18 16:35:28#1452] ERROR -- : Failed to parse BibTeX on value "," (COMMA) [#<BibTeX::Bibliography data=[16]>, "@", #<BibTeX::Entry >, {:title=>["Transposon age and non-CG methylation"], :author=>["Wang, Zhengming and Baulcombe, David"], :abstract=>["Silencing of transposable elements (TEs) is established by small RNA-directed DNA methylation (RdDM). Maintenance of silencing is then based on a combination of RdDM and RNA-independent mechanisms involving DNA methyltransferase MET1 and chromodomain DNA methyltransferases (CMTs). Involvement of RdDM, according to this model should decrease with TE age but here we show a different pattern in tomato and Arabidopsis. In these species the CMTs silence long terminal repeat (LTR) transposons in the distal chromatin that are younger than those affected by RdDM. To account for these findings we propose that, after establishment of primary RdDM as in the original model, there is an RNA-independent maintenance phase involving CMTs followed by secondary RdDM. This progression of epigenetic silencing in the gene-rich distal chromatin is likely to influence the transcriptome either in cis or in trans depending on whether the mechanisms are RNA-dependent or -independent."], :journal=>["Nature Communications"], :volume=>["In press."]}, ",", "number", "="]
bibtex.y:138:in `on_error': Failed to parse BibTeX on value "," (COMMA) [#<BibTeX::Bibliography data=[16]>, "@", #<BibTeX::Entry >, {:title=>["Transposon age and non-CG methylation"], :author=>["Wang, Zhengming and Baulcombe, David"], :abstract=>["Silencing of transposable elements (TEs) is established by small RNA-directed DNA methylation (RdDM). Maintenance of silencing is then based on a combination of RdDM and RNA-independent mechanisms involving DNA methyltransferase MET1 and chromodomain DNA methyltransferases (CMTs). Involvement of RdDM, according to this model should decrease with TE age but here we show a different pattern in tomato and Arabidopsis. In these species the CMTs silence long terminal repeat (LTR) transposons in the distal chromatin that are younger than those affected by RdDM. To account for these findings we propose that, after establishment of primary RdDM as in the original model, there is an RNA-independent maintenance phase involving CMTs followed by secondary RdDM. This progression of epigenetic silencing in the gene-rich distal chromatin is likely to influence the transcriptome either in cis or in trans depending on whether the mechanisms are RNA-dependent or -independent."], :journal=>["Nature Communications"], :volume=>["In press."]}, ",", "number", "="] (BibTeX::ParseError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/racc/parser.rb:259:in `_racc_do_parse_c'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/racc/parser.rb:259:in `do_parse'
	from bibtex.y:111:in `parse'
	from /app/vendor/bundle/ruby/2.4.0/gems/bibtex-ruby-5.1.4/lib/bibtex/bibliography.rb:67:in `parse'
	from /app/vendor/bundle/ruby/2.4.0/gems/bibtex-ruby-5.1.4/lib/bibtex/bibliography.rb:50:in `open'
	from /app/vendor/bundle/ruby/2.4.0/gems/bibtex-ruby-5.1.4/lib/bibtex/utilities.rb:25:in `open'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon/bibtex_parser.rb:36:in `generate_citations'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon/compilers.rb:245:in `crossref_from_markdown'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon/compilers.rb:21:in `generate_crossref'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon/processor.rb:95:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/bin/whedon:79:in `compile'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by lpantano** [comment]
Only thing to double-check whether the archive is valid being an tar file by the board of editors.

**Comment by lpantano** [comment]
oh oh @HajkD, did you change something? it rendered well a couple of days before. Let us know if you don't know how to fix this.

**Comment by arfon** [comment]
@HajkD - this PR should fix the issue with your paper: https://github.com/HajkD/LTRpred/pull/19

**Comment by HajkD** [comment]
@arfon - brilliant! Thanks so much! I just merged your pull request.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1093/nar/gkv1272 may be missing for title: The Dfam database of repetitive DNA families
- https://doi.org/10.1093/nar/gkr367 may be missing for title: HMMER web server: interactive sequence similarity searching
- https://doi.org/10.1093/bioinformatics/btq461 may be missing for title: Search and clustering orders of magnitude faster than BLAST
- https://doi.org/10.1109/tcbb.2013.68 may be missing for title: GenomeTools: a comprehensive software library for efficient processing of structured genome annotations
- https://doi.org/10.1093/nar/gkp759 may be missing for title: Fine-grained annotation and classification of de novo predicted LTR retrotransposons
- https://doi.org/10.1186/1471-2105-9-18 may be missing for title: LTRharvest, an efficient and flexible software for de novo detection of LTR retrotransposons
- https://doi.org/10.1371/journal.pcbi.1003118 may be missing for title: Software for computing and annotating genomic ranges
- https://doi.org/10.1038/nrg.2016.139 may be missing for title: Regulatory activities of transposable elements: from conflicts to benefits
- https://doi.org/10.1101/517508 may be missing for title: Environmental and epigenetic regulation of Rider retrotransposons in tomato
- https://doi.org/10.1093/gbe/evz255 may be missing for title: Becoming a Selfish Clan: Recombination Associated to Reverse-Transcription in LTR Retrotransposons
- https://doi.org/10.1038/s41477-018-0320-9 may be missing for title: Sensitive detection of pre-integration intermediates of long terminal repeat retrotransposons in crop plants
- https://doi.org/10.1093/bioinformatics/btw821 may be missing for title: Biomartr: genomic data retrieval with R
- https://doi.org/10.1038/s41467-020-14995-6 may be missing for title: Transposon age and non-CG methylation
- https://doi.org/10.1186/gb-2012-13-8-r77 may be missing for title: ggbio: an R package for extending the grammar of graphics for genomic data
- https://doi.org/10.1038/s41467-017-01374-x may be missing for title: High-frequency recombination between members of an LTR retrotransposon family during transposition bursts

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1497

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1497, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@HajkD - looks like most of your references need a `doi` field added. Can you check the suggestions from Whedon above and if they are correct add them?

Also, just as a heads-up, these should be formatted without the `https://doi.org/` bit, i.e. the BibTeX field should look like:   

```
doi=10.1038/s41467-017-01374-x
```

**Comment by HajkD** [comment]
Dear @arfon 

I now added `doi` fields to all references in the `bib` file and tested all the doi links. They are all correct and after checking with http://whedon.theoj.org it seems like the manuscript is in excellent shape.

Thank you very much for catching these issues!

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/nar/gkv1272 is OK
- 10.1093/nar/gkr367 is OK
- 10.7717/peerj.2584 is OK
- 10.1093/bioinformatics/btq461 is OK
- 10.1109/tcbb.2013.68 is OK
- 10.1093/nar/gkp759 is OK
- 10.1186/1471-2105-9-18 is OK
- 10.1007/978-3-319-24277-4 is OK
- 10.1371/journal.pcbi.1003118 is OK
- 10.21105/joss.01686 is OK
- 10.1038/nrg.2016.139 is OK
- 10.1371/journal.pgen.1008370 is OK
- 10.1093/gbe/evz255 is OK
- 10.1038/s41477-018-0320-9 is OK
- 10.1093/bioinformatics/btw821 is OK
- 10.1038/s41467-020-14995-6 is OK
- 10.1186/gb-2012-13-8-r77 is OK
- 10.1038/s41467-017-01374-x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1498

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1498, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1273863918033788928) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1499
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02170](https://doi.org/10.21105/joss.02170)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02170/status.svg)](https://doi.org/10.21105/joss.02170)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02170">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02170/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02170/status.svg
   :target: https://doi.org/10.21105/joss.02170
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02170/status.svg)](https://doi.org/10.21105/joss.02170)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by HajkD** [comment]
Dear all, 

Thank you very much for all your efforts. As always it has been a pleasure submitting software to JOSS. Please keep up the excellent work and I very much look forward to collaborating with you on future projects.

With very best wishes,
Hajk
