### ISSUE TITLE
[REVIEW]: TESPy: Thermal Engineering Systems in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2178]
**Submitting author:** @fwitte (<a href="http://orcid.org/0000-0003-4019-0390">Francesco Witte</a>)
**Repository:** <a href="https://github.com/oemof/tespy" target ="_blank">https://github.com/oemof/tespy</a>
**Version:** v0.2.1
**Editor:** @kyleniemeyer
**Reviewer:** @arosen93, @corentin-dev
**Archive:** <a href="https://doi.org/10.5281/zenodo.3837555" target="_blank">10.5281/zenodo.3837555</a>

## Status

[![status](https://joss.theoj.org/papers/590b0b4767606bce4d0ebe397d4b7a4f/status.svg)](https://joss.theoj.org/papers/590b0b4767606bce4d0ebe397d4b7a4f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/590b0b4767606bce4d0ebe397d4b7a4f"><img src="https://joss.theoj.org/papers/590b0b4767606bce4d0ebe397d4b7a4f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/590b0b4767606bce4d0ebe397d4b7a4f/status.svg)](https://joss.theoj.org/papers/590b0b4767606bce4d0ebe397d4b7a4f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/oemof/tespy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@arosen93 & @corentin-dev, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kyleniemeyer know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/oemof/tespy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@fwitte) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/oemof/tespy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@fwitte) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arosen93, @corentin-dev it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1021/ie4033999 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1016/j.applthermaleng.2019.114750 is OK
- 10.1007/978-3-662-49568-1 is OK
- 10.1016/j.esr.2018.07.001 is OK
- 10.5281/ZENODO.591265 is OK
- 10.1007/978-3-7091-1182-6 is OK
- 10.1144/petgeo2016-050 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02178/joss.02178/10.21105.joss.02178.pdf)

**Comment by kyleniemeyer** [comment]
👋 @fwitte @arosen93  @corentin-dev the actual review will take place in here. Thanks!

**Comment by kyleniemeyer** [comment]
@arosen93 linking your comments here: https://github.com/oemof/tespy/issues/180

**Comment by fwitte** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by fwitte** [comment]
@whedon generate pdf from branch feature/joss_paper_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature/joss_paper_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02178/joss.02178/10.21105.joss.02178.pdf)

**Comment by fwitte** [comment]
@whedon generate pdf from branch feature/joss_paper_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature/joss_paper_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02178/joss.02178/10.21105.joss.02178.pdf)

**Comment by arosen93** [comment]
@fwitte: I can confirm that, in my view, TESPy fulfills all the required checkboxes for the review. In particular, I am very impressed with the extensive documentation and examples provided with the code. I also think the manuscript is greatly improved, now that it more clearly specifies the variables used and takes a more general approach with regards to the equations. I can confirm that the code works as-advertised, and the modular nature of the package is self-evident. I still would like to test out the code for a few more days (and will provide any minor remaining comments then -- probably just clarifications) but will certainly complete the review by the 2-week suggested deadline.

As for right now, I think there is one easy improvement that can be made. One of the checkbox items states "Documentation: Are there automated tests or manual steps described so that the functionality of the software can be verified?" It is clear there is actually quite extensive automated tests, for which I applaud the developers. Still, I think it would be helpful to link to the tests being carried out (and briefly describe where the expected results are) at the corresponding [docs page](https://tespy.readthedocs.io/en/master/developing_tespy.html#tests). Nothing more than a sentence or two is really needed. Also, very minor, but when you say "If you have further questions regarding the tests, do not bother to contact us", it makes it sound like you should _not_ be contacted if there are questions. The phrase that makes more sense here is "do not hesitate to contact us." I also left a few minor comments on the docs [here](https://github.com/oemof/tespy/issues/185).

**Comment by fwitte** [comment]
@arosen93: Thank you very much for your comments, take your time and have fun :).

> Very minor comment. When you say "If you have further questions regarding the tests, do not bother to contact us", it makes it sound like you should _not_ be contacted if there are questions. The phrase that makes more sense here is "do not hesitate to contact us."

Haha, I like this one. When there is too much work on the desk, you must find your priorities... Thank you very much for the hint! I addressed this over at https://github.com/oemof/tespy/pull/181 (https://tespy--181.org.readthedocs.build/en/181/developing_tespy.html#tests).

>  I also left a few minor comments on the docs [here](https://github.com/oemof/tespy/issues/185).

Addressed these comments as well.

Have a nice week!

**Comment by arosen93** [comment]
@fwitte, @kyleniemeyer -- my review is completed. The code is well-documented with an extensive set of (working) examples, there are robust unit-tests, and there is a clear need for such a program in the community. I am happy to recommend TESPy for publication in JOSS.

**Comment by kyleniemeyer** [comment]
Thanks @arosen93!

**Comment by kyleniemeyer** [comment]
Hi @corentin-dev, just wanted to check in on the status of your review—no rush though, we understand that things are not normal right now.

**Comment by corentin-dev** [comment]
Hi, at the moment I got no time to work on it. My review is scheduled to 
start this week.

Best regards,

Corentin

**Comment by fwitte** [comment]
@whedon generate pdf from branch feature/joss_paper_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature/joss_paper_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02178/joss.02178/10.21105.joss.02178.pdf)

**Comment by fwitte** [comment]
@whedon generate pdf from branch feature/joss_paper_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature/joss_paper_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02178/joss.02178/10.21105.joss.02178.pdf)

**Comment by fwitte** [comment]
Hi @corentin-dev,
looking forward to your review. Just to let you know: I am keeping track of the changes made within the review process on this PR: https://github.com/oemof/tespy/pull/181. You might want to have a look at the corresponding documentation (https://tespy--181.org.readthedocs.build/en/181/) instead of the documentation on the master branch (https://tespy.readthedocs.io) as some typos etc. have already been fixed.
Have a nice week, best regards
Francesco

**Comment by corentin-dev** [comment]
Sorry, but my invitation to joss-review has been revoked (I took too much time to accept I guess). Can you renew it please ?
```
 Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account. 
```

**Comment by arfon** [comment]
@whedon re-invite @corentin-dev as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@corentin-dev please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by arfon** [comment]
@corentin-dev - can you try again now?

**Comment by corentin-dev** [comment]
` You now have push access to the openjournals/joss-reviews repository. `
Perfect ! Thank you @arfon

**Comment by corentin-dev** [comment]
**Scientific paper**

The scientific paper is clear but short. It clearly states the motivations, the architecture and the main equations solved. It does not state any major contribution to the field and mainly aims at providing an up to date open source package written in python and using state-of-the-art procedures.

The paper could list component models, fluid models, connections, etc... It does not need to detail everything, but pointing to the right papers / documentation would be nice. The documentation already covers a lot of those details, and it should not take too long to have the paper updated.

Typo : pre- in page 1
Consider using Re with curved `\mathrm{Re}` for Reynolds number even if it is purely author's choice.

**Documentation, usability**

The package is very well documented. It is easy to use. Many examples, tutorials are available and cover many aspects of the software.

The source code respects current standard developpement in python.

**Global opinion**

The sofware is suitable to be published in JOSS. The paper can be improved, but overall everything is in the documentation which is extensive and provides lots of well written tutorials and examples.

**Comment by kyleniemeyer** [comment]
Thanks @corentin-dev!

@fwitte, can you respond to these comments? There are a few specific requests/suggestions.

**Comment by fwitte** [comment]
Hi,
thank you for the review. I'll address your comments until tomorrow and will prepare the release thereafter. Some quick questions/remarks:

> The paper could list component models, fluid models, connections, etc... It does not need to detail everything, but pointing to the right papers / documentation would be nice. The documentation already covers a lot of those details, and it should not take too long to have the paper updated.

I wanted to stay within the 1000 word limit. As adding more formulas of the components available (e.g. parababolic trough and solar collector energy balances, stodolas cone law applied for turbines, compressor maps, ...) would add a lot of content to the paper, is a link with a short description, where the respective formulas are located in the documentation sufficient?

> Typo : pre- in page 1

Is it "pre and postprocessing" in english?

> Consider using Re with curved `\mathrm{Re}` for Reynolds number even if it is purely author's choice.

Is that not the opposite of curved? See https://latex.wikia.org/wiki/Mathrm_(LaTeX_symbol).

**Comment by corentin-dev** [comment]
> Hi,
> thank you for the review. I'll address your comments until tomorrow and will prepare the release thereafter. Some quick questions/remarks:
> 
> > The paper could list component models, fluid models, connections, etc... It does not need to detail everything, but pointing to the right papers / documentation would be nice. The documentation already covers a lot of those details, and it should not take too long to have the paper updated.
> 
> I wanted to stay within the 1000 word limit. As adding more formulas of the components available (e.g. parababolic trough and solar collector energy balances, Stodola's cone law applied for turbines, compressor maps, ...) would add a lot of content to the paper, is a link with a short description, where the respective formulas are located in the documentation sufficient?

Yes perfect ! 

> 
> > Typo : pre- in page 1
> 
> Is it "pre and postprocessing" in english?
> 

Yes

> > Consider using Re with curved `\mathrm{Re}` for Reynolds number even if it is purely author's choice.
> 
> Is that not the opposite of curved? See https://latex.wikia.org/wiki/Mathrm_(LaTeX_symbol).

I meant as the opposite of mathsf, but not as curvy as mathcal though.

Sorry, I'm writting from mobile...

**Comment by fwitte** [comment]
@corentin-dev, thank you for your fast reply. I updated the manuscript and hope it suits your remarks well.

There is only one issue, that I am not sure of: What about the syllabification of "initialisation"? Is it correct or do I need to apply something manually here?

@whedon generate pdf from branch feature/joss_paper_review

**Comment by fwitte** [comment]
@whedon generate pdf from branch feature/joss_paper_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature/joss_paper_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02178/joss.02178/10.21105.joss.02178.pdf)

**Comment by kyleniemeyer** [comment]
Hi @fwitte, I have a few editorial comments on the paper:

- [ ] For a few citations (such as Witte 2020 in the Summery and Casella & Leva 2003 in the Motivation paragraph, I think you want to change the citations from the `[@author:year]` format to the `@author:year` format, which will make the citation look like "Author et al. (year)".
- [ ] In the second paragraph of Motivation, the first sentence could be improved a bit; perhaps something like "Here we propose a new solution for simulating thermal processes, since ThermoPower is not currently maintained and also limited to one field of thermal engineering." Then, in the second sentence, the "is very promising" at the end seems out of place, and I think should just be removed.
- [ ] In the second paragraph of Method, you have nested parentheses with the citations; perhaps just bring the "based on standard literature..." to the main level of the sentence.
- [ ] Just after that, "component specific" needs a hyphen, I think.
- [ ] Just after _that_, I don't think you mean that CoolProp is "implemented", but rather that it is used. Perhaps the sentence could be edited to something like "For calculating fluid properties, TESPy uses CoolProp (Bell ...), which supports a wide range of pure and incompressible fluids."
- [ ] Just above equation 5, a sentence starts with "E.g."; this is a bit awkward, and perhaps could just be "For example, for an adiabatic ..."
- [ ] The number "7" appears right after "pressure ratio pr" just before equation 6. I think this sentence should be something like "A simpler approach is to specify the pressure ratio pr:" (no need to write the equation number when the equation appears next)

**Comment by fwitte** [comment]
Thank you for your comments and suggestions @kyleniemeyer, I have addressed all of them over here https://github.com/oemof/tespy/pull/181.

**Comment by fwitte** [comment]
@whedon generate pdf from branch feature/joss_paper_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature/joss_paper_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02178/joss.02178/10.21105.joss.02178.pdf)

**Comment by fwitte** [comment]
@whedon generate pdf from branch feature/joss_paper_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature/joss_paper_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02178/joss.02178/10.21105.joss.02178.pdf)

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1021/ie4033999 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1016/j.applthermaleng.2019.114750 is OK
- 10.1007/978-3-662-49568-1 is OK
- 10.1016/j.esr.2018.07.001 is OK
- 10.5281/ZENODO.591265 is OK
- 10.1007/978-3-7091-1182-6 is OK
- 10.1144/petgeo2016-050 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@fwitte almost done! The references are just missing a few details here and there:

- add volume and pages to the Chen et al. 2019 reference
- I think the year for the Herning and Zipperer reference should be 1936, not 2015
- For the IEA technology roadmap, please provide a URL or other information
- The Virtanen 2020 citation (for SciPy) is missing some info (volume, page numbers)

When you've addressed these, we are ready to accept! Please merge the JOSS review branch into master, archive the repo (e.g., with Zenodo), and let me know the DOI.

**Comment by fwitte** [comment]
@kyleniemeyer, great! I will do so tomorrow morning. Just one question: Is it possible to add the bibtex entry and the doi of the JOSS paper to the online documentation prior to the release? If so, I would not need to make a second release after the paper is published (as I usually only commit to master in case I release a new version).
Cheers

**Comment by kyleniemeyer** [comment]
@fwitte sure, the DOI will be what shows up in the paper draft, though it does not yet resolve.

**Comment by fwitte** [comment]
>* add volume and pages to the Chen et al. 2019 reference

I have looked this up, there is no pages information available. Only an article number (114750): https://www.sciencedirect.com/journal/applied-thermal-engineering/vol/167/suppl/C.

>* I think the year for the Herning and Zipperer reference should be 1936, not 2015

Adjusted, thank you!
 
>* For the IEA technology roadmap, please provide a URL or other information

Done.

>* The Virtanen 2020 citation (for SciPy) is missing some info (volume, page numbers)

Also added the missing info.
 
> When you've addressed these, we are ready to accept! Please merge the JOSS review branch into master, archive the repo (e.g., with Zenodo), and let me know the DOI.

I will prepare the release and let you know, when it is done.

**Comment by fwitte** [comment]
@whedon generate pdf from branch feature/joss_paper_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature/joss_paper_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02178/joss.02178/10.21105.joss.02178.pdf)

**Comment by fwitte** [comment]
@whedon generate pdf from branch feature/joss_paper_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature/joss_paper_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02178/joss.02178/10.21105.joss.02178.pdf)

**Comment by fwitte** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1021/ie4033999 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1016/j.applthermaleng.2019.114750 is OK
- 10.1007/978-3-662-49568-1 is OK
- 10.1016/j.esr.2018.07.001 is OK
- 10.5281/zenodo.591265 is OK
- 10.1007/978-3-7091-1182-6 is OK
- 10.1144/petgeo2016-050 is OK

MISSING DOIs

- https://doi.org/10.29172/928700ef130543aeab15117d0a461239 may be missing for title: ThermoPower

INVALID DOIs

- None
```

**Comment by fwitte** [comment]
Hi @kyleniemeyer,
version has been published, archive to be found here: https://zenodo.org/record/3837555.
Thank to all of you for your efforts and support :tada: :beers:!
Best
Francesco

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.3837555 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3837555" target="_blank">10.5281/zenodo.3837555</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1021/ie4033999 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1016/j.applthermaleng.2019.114750 is OK
- 10.1007/978-3-662-49568-1 is OK
- 10.1016/j.esr.2018.07.001 is OK
- 10.5281/zenodo.591265 is OK
- 10.1007/978-3-7091-1182-6 is OK
- 10.1144/petgeo2016-050 is OK

MISSING DOIs

- https://doi.org/10.29172/928700ef130543aeab15117d0a461239 may be missing for title: ThermoPower

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1458

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1458, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1263554170914832385) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1459
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02178](https://doi.org/10.21105/joss.02178)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @fwitte on your article's publication in JOSS!

Many thanks to @arosen93 and @corentin-dev for reviewing this submission.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02178/status.svg)](https://doi.org/10.21105/joss.02178)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02178">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02178/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02178/status.svg
   :target: https://doi.org/10.21105/joss.02178
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02178/status.svg)](https://doi.org/10.21105/joss.02178)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
