### ISSUE TITLE
[REVIEW]: MPA: a novel cross-language API for time series analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2179]
**Submitting author:** @vanbenschoten (<a href="http://orcid.org/0000-0002-7944-6237">Andrew Van Benschoten</a>)
**Repository:** <a href="https://github.com/matrix-profile-foundation/joss_paper" target ="_blank">https://github.com/matrix-profile-foundation/joss_paper</a>
**Version:** Misc (multiple repos)
**Editor:** @arfon
**Reviewer:** @coljac, @krystophny
**Archive:** <a href="https://doi.org/10.5281/zenodo.3789780" target="_blank">10.5281/zenodo.3789780</a>

## Status

[![status](https://joss.theoj.org/papers/8430d3833cf8e0007e557aee5a25cfe2/status.svg)](https://joss.theoj.org/papers/8430d3833cf8e0007e557aee5a25cfe2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8430d3833cf8e0007e557aee5a25cfe2"><img src="https://joss.theoj.org/papers/8430d3833cf8e0007e557aee5a25cfe2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8430d3833cf8e0007e557aee5a25cfe2/status.svg)](https://joss.theoj.org/papers/8430d3833cf8e0007e557aee5a25cfe2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/matrix-profile-foundation/joss_paper" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@coljac & @krystophny, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/matrix-profile-foundation/joss_paper">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@vanbenschoten) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/matrix-profile-foundation/joss_paper">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@vanbenschoten) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @coljac, @krystophny it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/ICDM.2016.0179 is OK
- 10.1109/ICDM.2016.0085 is OK
- 10.1109/ICDM.2017.21 is OK
- 10.1109/ICDM.2018.00099 is OK
- 10.1109/ICDM.2018.00119 is OK
- 10.1109/ICBK.2018.00058 is OK
- 10.1109/ICBK.2019.00031 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02179/joss.02179/10.21105.joss.02179.pdf)

**Comment by arfon** [comment]
@coljac, @krystophny - thanks again for agreeing to review this submission! Please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Unlike some JOSS submissions, the code for this review is in a [small number of repositories](https://github.com/openjournals/joss-reviews/issues/2159#issuecomment-597276663):

- https://github.com/matrix-profile-foundation/tsmp
- https://github.com/matrix-profile-foundation/go-matrixprofile
- https://github.com/matrix-profile-foundation/matrixprofile

Any questions/concerns please let me know.

**Comment by krystophny** [comment]
### General checks 

1) The source code of all three mentioned repositories is available. Please check that this information (links to the URLs) appears also in the final publication https://github.com/matrix-profile-foundation/joss_paper/issues/1
2) The codes are under the Apache License, which is OSI compliant and LICENSE files exist
3) All authors appear to have contributed significantly, the list is alphabetical https://github.com/matrix-profile-foundation/joss_paper/issues/2

**Comment by coljac** [comment]
Hi @vanbenschoten:

Congratulations of developing Matrix profile and the associated software packages. A lot of work has gone into making the algorithms as accessible and usable as possible. This package certainly clears the bar for significance and quality.

I have reviewed the python and golang implementations of matrix profile. The python package is fully-fledged and well documented, with many accessible examples and quality API documentation. The performance was good even with large data sets that I tested. I was able to successfully run all tests.

The golang implementation is much less fleshed out. While a few examples were provided, it lacks proper API documentation. On its own, I'm not sure that go-matrixprofile would clear the bar for this reason. However, the golang implementation is provided alongside two other repositories where the capabilities of the algorithm are more clearly explained. I will discuss this with my co-reviewer, @krystophny; if the R version is similarly well fleshed out to the python version, this may not be a barrier to acceptance.

Regarding the paper, there isn't much discussion of other approaches to the analysis of time series data. The paper would be improved if you named a few other approaches, with references, in the first paragraph (where you have cited Yeh+ 2016). 

*Minor issues:*
- The link to example code in the go-matrixprofile README.md is broken
- Python matrix profile: the Linux/Mac instructions to install from source/run tests:
    - the `git clone git@github.com:...` gives a permission error; maybe use https:// URL?
    - The `pip install -e .` fails unless it's run after the `pip install -r requirements.txt` for me.

**Comment by vanbenschoten** [comment]
@coljac Thank you for the kind words, and the time you've put into reviewing! We'll look into the issues you've raised and work on edits. Keep us posted!

-Andrew

**Comment by vanbenschoten** [comment]
@coljac @krystophny 

We've updated the paper intro per @coljac 's comments, as well as resolved the matrixprofile install and Golang README issues.

**Comment by coljac** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02179/joss.02179/10.21105.joss.02179.pdf)

**Comment by coljac** [comment]
@vanbenschoten This resolves my issues with the paper.

Once @krystophny has had a chance to look at the R module, we'll get back to you again.

**Comment by krystophny** [comment]
@vanbenschoten I could now test installation and basic functionality of your packages in Python, R and Go. There was one issue with the Python version that downgraded my SciPy from 1.4.1 to some 1.3 version. It would be great if you could fix that before publication, or at least prioritize this issue, as it will destroy other dependencies (e.g. tensorflow 2.2).

Otherwise I'm happy with usability and documentation and think the software is very useful. The reference documentation for the R version API is also very detailed and available on CRAN too, so this should be fine @coljac . The paper is well written and explains the basics of what's going on in a concise way. 

The last remaining issue are references. JOSS explicitly asks for referencing related codes in the paper. I saw this on the github READMEs only though, and even that one was missing e.g. this code: https://github.com/TDAmeritrade/stumpy that I found when quickly googling for matrix profile in Python. Please give some information where your code stands, what distinguishes it from the others, and also reference the most important alternatives.

**Comment by vanbenschoten** [comment]
@krystophny sounds good! I'll add a paragraph or two detailing the history and current landscape of matrix profile implementations.

**Comment by coljac** [comment]
@vanbenschoten @krystophny Unless I missed something, I'm not sure about the scipy versioning issue being a problem here. It's standard these days to run any software like this in its own environment to manage these sorts of versioning clashes. Perhaps the docs should reference this, but from where I sit this is understood implicitly.

**Comment by vanbenschoten** [comment]
We've gone ahead and resolved the scipy version issue in a minor code
release we're pushing tomorrow, so I think we'll be good on this front.

**Comment by vanbenschoten** [comment]
@krystophny @coljac @arfon I've updated the paper to per @krystophny 's feedback.

**Comment by coljac** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02179/joss.02179/10.21105.joss.02179.pdf)

**Comment by coljac** [comment]
Based on the changes and @krystophny's comments, at this point I'm happy to recommend accept. (Well done @vanbenschoten and team!)

**Comment by krystophny** [comment]
@vanbenschoten very nice work indeed! With the changes made I can propose to accept the paper. 

PS: In the proofs I saw a space is missing after "UCR". Is "pan-Matrix Profile" really written in that way?

**Comment by krystophny** [comment]
@arfon our reviews are finished, is there anything else to do from our side? Otherwise we agree to support publication of the article!

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02179/joss.02179/10.21105.joss.02179.pdf)

**Comment by arfon** [comment]
Thanks @krystophny and @coljac!

@vanbenschoten - I think this is ready to move forward to the accept/publish stage. 

At this point could you make new releases of these software packages review here that includes the changes that have resulted from this review. Then, please make an archive of the software packages together in a deposit with Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by vanbenschoten** [comment]
@arfon Done! The DOI is 10.5281/zenodo.3789780.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3789780 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3789780" target="_blank">10.5281/zenodo.3789780</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/ICDM.2016.0179 is OK
- 10.1109/ICDM.2016.0085 is OK
- 10.1109/ICDM.2017.21 is OK
- 10.1109/ICDM.2018.00099 is OK
- 10.1109/ICDM.2018.00119 is OK
- 10.1109/ICBK.2018.00058 is OK
- 10.1109/ICBK.2019.00031 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1440

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1440, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1257851763912314884) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1441
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02179](https://doi.org/10.21105/joss.02179)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@coljac, @krystophny - many thanks for your reviews here :sparkles:

@vanbenschoten - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02179/status.svg)](https://doi.org/10.21105/joss.02179)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02179">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02179/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02179/status.svg
   :target: https://doi.org/10.21105/joss.02179
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02179/status.svg)](https://doi.org/10.21105/joss.02179)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by vanbenschoten** [comment]
Thanks so much everyone for all of the help!
