### ISSUE TITLE
[REVIEW]: Sensie: Probing the sensitivity of neural networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2180]
**Submitting author:** @coljac (<a href="http://orcid.org/0000-0003-4239-4055">Colin Jacobs</a>)
**Repository:** <a href="https://github.com/coljac/sensie" target ="_blank">https://github.com/coljac/sensie</a>
**Version:** v1.0.0
**Editor:** @gkthiruvathukal
**Reviewers:** @ejhigson, @omshinde
**Archive:** <a href="https://doi.org/10.5281/zenodo.3894083" target="_blank">10.5281/zenodo.3894083</a>

## Status

[![status](https://joss.theoj.org/papers/cabd37234d4a4d19b9d047907bc81ebe/status.svg)](https://joss.theoj.org/papers/cabd37234d4a4d19b9d047907bc81ebe)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/cabd37234d4a4d19b9d047907bc81ebe"><img src="https://joss.theoj.org/papers/cabd37234d4a4d19b9d047907bc81ebe/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/cabd37234d4a4d19b9d047907bc81ebe/status.svg)](https://joss.theoj.org/papers/cabd37234d4a4d19b9d047907bc81ebe)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/coljac/sensie" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ejhigson, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @gkthiruvathukal know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/coljac/sensie">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@coljac) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/coljac/sensie">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@coljac) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.dsp.2017.10.011 is OK
- 10.1109/ICIP.2016.7532763 is OK
- 10.1371/journal.pone.0130140 is OK
- 10.1002/widm.1349 is OK
- 10.3847/1538-4365/ab26b6 is OK
- 10.1093/mnras/stz272 is OK
- 10.1093/mnras/stx1492 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-319-44781-0_8 may be missing for title: Layer-Wise Relevance Propagation for Neural Networks with Local Renormalization Layers
- https://doi.org/10.1109/iccv.2017.74 may be missing for title: Grad-CAM: Visual Explanations From Deep Networks via Gradient-Based Localization

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02180/joss.02180/10.21105.joss.02180.pdf)

**Comment by arfon** [comment]
@ejhigson - thanks again for agreeing to review this submission for JOSS.

Please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let myself or @gkthiruvathukal know.

**Comment by arfon** [comment]
:wave: @nilesh-patil @sssomani @chekoduadarsh @omshinde - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The package being reviewed here is [Sensie](https://github.com/coljac/sensie), a Python package for probing the sensitivity of neural networks.

**Comment by omshinde** [comment]
Hi @arfon ! Thanks for consideration. Yes, I would be interested to review this submission for JOSS. This would be my maiden review for JOSS and I foresee a great learning expereince ahead. Please let  me know of the further steps. Thanks!

**Comment by arfon** [comment]
Sounds good to me, thanks @omshinde. @gkthiruvathukal - do you want to take it from here? (You can do `@whedon add @omshinde as reviewer`) but then you'll have to edit the top of the issue to add a checklist for them.

**Comment by ejhigson** [comment]
Hi @coljac - congratulations on a really neat piece of software. I definitely see the usefulness of this package!

I took an initial look over it and have a few suggestions:

1. For the installation, I suggest adding your requirements to ``setup.py`` using the ``install_requires`` property so they are installed automatically (in addition to having them in the requirements.txt). You also may want to list your package on PyPI so users can install it with pip without doing a git clone.

2. Forgive me if I have missed them but I can't see any instructions for how to run your automated tests in the docs? When I try with ``nosetests`` I get some errors but maybe I am doing something wrong?

3. I would suggest adding a bit more detail to your community guidelines at https://sensie.readthedocs.io/en/latest/index.html. The review criteria is "Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support". Some of this is covered in your "Contact" section but maybe you can add more.

4. In the paper, you survey the literature on testing DNN sensitivity but you don't mention if there are any other software packages for doing this similar to ``sense``. Please could you add this? If the answer is no then its worth saying so explicitly.

5. One of the references in the paper, "Layer-Wise Relevance Propagation for Neural Networks with Local Renormalization Layers", is missing a DOI.

**Comment by coljac** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02180/joss.02180/10.21105.joss.02180.pdf)

**Comment by coljac** [comment]
Hi @ejhigson,

Thanks for taking the time to review Sensie, it's much appreciated. I have responded to your initial feedback as follows:

>    For the installation, I suggest adding your requirements to setup.py using the install_requires property so they are installed automatically (in addition to having them in the requirements.txt). You also may want to list your package on PyPI so users can install it with pip without doing a git clone.

Thanks for this suggestion. I have updated setup.py accordingly, and adjusted the documentation to make the installation procedure clearer.

>    Forgive me if I have missed them but I can't see any instructions for how to run your automated tests in the docs? When I try with nosetests I get some errors but maybe I am doing something wrong?

`pip install pytest` and then `pytest test` from the repo root should run the tests successfully.

I have also indicated this in the documentation:

"Optionally, install `pytest` with `pip install pytest`, then run the tests with `pytest test` from the repository root."

>    I would suggest adding a bit more detail to your community guidelines at https://sensie.readthedocs.io/en/latest/index.html. The review criteria is "Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support". Some of this is covered in your "Contact" section but maybe you can add more.

I have updated the documentation to read as follows on readthedocs and GitHub:

"Issues, Questions and Contributions
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Any problems or questions? Email colin@coljac.net, or open an issue on GitHub at https://github.com/coljac/sensie.

Contributions are welcome and encouraged. Fork the GitHub repository to your own machine, make some changes, and push your work back up to the fork and open a pull request so that I can review the changes."

>    In the paper, you survey the literature on testing DNN sensitivity but you don't mention if there are any other software packages for doing this similar to sense. Please could you add this? If the answer is no then its worth saying so explicitly.

I'm not aware of anything that does what Sensie does precisely. I added the following to the paper:

"Several quality software packages exist to probe ANN internals, such as ``Innvestigate`, ``tf-explain``, and ``keras-vis``. These packages are geared towards traditional image-based applications, and cannot explore relationships between the neural network performance and arbitrary properties of the examples presented to the network. ``Sensie`` is designed to fill that gap."

>    One of the references in the paper, "Layer-Wise Relevance Propagation for Neural Networks with Local Renormalization Layers", is missing a DOI.

Fixed.

**Comment by coljac** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2180 with the following error: 

 Error reading bibliography ./paper.bib (line 63, column 3):
unexpected "f"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by coljac** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02180/joss.02180/10.21105.joss.02180.pdf)

**Comment by ejhigson** [comment]
Hi @coljac - thank you very much for these changes!

The install and tests work perfectly for me, and the community guidelines additions look good

> "Several quality software packages exist to probe ANN internals, such as `Innvestigate`, `tf-explain`, and `keras-vis`. These packages are geared towards traditional image-based applications, and cannot explore relationships between the neural network performance and arbitrary properties of the examples presented to the network. `Sensie` is designed to fill that gap."

Thank you for adding this to the paper - I think it is very useful background information.

Rereading the paper I spotted a couple of minor typos: you are missing a comma after ``Innvestigate`` and in the caption of Figure 1 I think "ann" should be "an". Aside from this I think the paper looks great and is very well written and clear. I particularly like the examples in the paper.

Regarding documentation: this looks mostly complete but there are a few methods missing documentation as can be seen at https://sensie.readthedocs.io/en/latest/sensie.html and in the source code. Please could you check it over and fill in the missing methods' documentation?

**Comment by ejhigson** [comment]
Also, looking at the examples on the jupyter notebooks, I think "MNIST example" is missing an
``import numpy as np``
statement in the first cell? With this addition it runs perfectly for me. "CIFAR10 example" also works perfectly for me. However "VGG example" seems to need some files from your local drive at ``/home/coljac/Downloads/imagenet/gorillas``(?) Is this example notebook meant to be runnable by other people?

**Comment by gkthiruvathukal** [comment]
@arfon Just letting you know, with this comment, that I am resuming editorial activities and will see this and other submissions through the process. It's good to see @ejhigson has been offering good feedback for @coljac, who is working to address the issues.

**Comment by arfon** [comment]
> @arfon Just letting you know, with this comment, that I am resuming editorial activities and will see this and other submissions through the process. 

👍thanks @gkthiruvathukal! One quick reminder (and possibly stating the obvious here) - we still need a second reviewer for this one.

**Comment by gkthiruvathukal** [comment]
@arfon Is it easy to add a reviewer after review has started? I seem to recall that wasn't easy to do in the past. I'll try to find a second. Let's hope more people are becoming available as some of the COVID-19 measures begin to lift.

**Comment by coljac** [comment]
Hi @ejhigson,

Thanks again for the follow up comments - and the bug/typo finding. 

- I added the missing numpy import in the notebook example.
- I fixed the typos indicated.

Regarding the VGG example, for copyright reasons I didn't check in/make available the collection of gorilla pictures I used for this example, and so I've left that as an exercise for the reader (though they can of course see how things work from the state of the notebook checked in). I've added a note to this effect to the top. Let me know if you think this is an acceptable solution; otherwise, I can hunt down some images (in a different class) whose copyright I can vouch for.

As for the documentation, I ensured there are docstrings for all the methods and they show up on readthedocs; I also put in docstrings for all the underscore-methods for those accessing the source. That should all be in order now.

Thanks again for the comments and the attention to detail.

**Comment by ejhigson** [comment]
@coljac thank you very much for your latest changes - they all look good to me! I think the VGG example now works well with the note at the top you just added telling people they can use their own images instead.

I am satisfied that you have met all the JOSS criteria - the paper is well written and the performance all seems as expected. Congratulations on a very neat software package and a nice paper!

**Comment by arfon** [comment]
> @arfon Is it easy to add a reviewer after review has started? I seem to recall that wasn't easy to do in the past. I'll try to find a second. Let's hope more people are becoming available as some of the COVID-19 measures begin to lift.

You can do `@whedon add xxx as reviewer` here which will update the assignments but unfortunately you'll need to manually create a checklist for the second reviewer by editing the issue body at the top of this thread.

**Comment by coljac** [comment]
@ejhigson Thanks for the nice comments and the work as reviewer, it's much appreciated!

**Comment by omshinde** [comment]
Hi @arfon and @gkthiruvathukal , sorry for the long communication gap from my side. I couldn't start the review as I did not receive any reviewer invitation as mentioned above. Also, I am not sure whether I would require permissions to edit the review checklist or I can make the checklist in a comment. Please let me know if I should still review the work and make the checklist here itself in the comment. 

Thanks.
Thanks to @coljac and @ejhigson for the contributions. :)

**Comment by coljac** [comment]
Sorry to chime in here; I noticed @omshinde was willing to review but was waiting for confirmation. Does anything further need to be done @gkthiruvathukal?

**Comment by gkthiruvathukal** [comment]
Hi @omshinde, thanks for your folllow up. I, too, have been a bit unavailable because of COVID-19 and am now getting back into a routine. I will add you as a reviewer now.

**Comment by gkthiruvathukal** [comment]
@whedon add @omshinde as reviewer

**Comment by whedon** [comment]
OK, @omshinde is now a reviewer

**Comment by gkthiruvathukal** [comment]
@omshinde I think it worked! Let me know if everything is working so you can begin review. Thank you so much for being willing to help JOSS (and me!)

**Comment by arfon** [comment]
@gkthiruvathukal - you'll need to edit the issue body at the top of this list to add a reviewer checklist for @omshinde. Whedon doesn't know how to do this yet sorry.

Any problems, just let me know and I can help out.

**Comment by omshinde** [comment]
Thank you @gkthiruvathukal , @arfon (and whedon =D). 
@gkthiruvathukal Yes, everything is working at my end except the reviewer checklist mentioned by @arfon and I have accepted the reviewer invitation too. I will start reviewing the work at my end following the reviewer's checklist present in one of the above comments, till my checklist is being prepared. Thanks again!

**Comment by gkthiruvathukal** [comment]
@omshinde Just checking in on how things are coming along with your review. Let me know if you have any questions.

**Comment by omshinde** [comment]
Hi @gkthiruvathukal . Thank you! Sure. Yes, I have started review steps locally but I think we need to have a review checklist as mentioned by @arfon in the first comment of this issue so that I can mark the status of completed steps. Oh, it seems I can edit it. I will update it manually. Thanks again for the reminder.

**Comment by omshinde** [comment]
Hi @coljac!
cc: @gkthiruvathukal , @arfon

System settings while reviewing:
1. Installation - Local Machine, Google Colab
2. Running example notebooks - Google Colab 

Thank you for the great software, I foresee Sensie as a great framework for sensitivity analysis of a machine learning/deep learning model. Please find my detailed thoughts below regarding the points mentioned in the review checklist:

1. Installation: Does installation proceed as outlined in the documentation?
 - The installation works perfectly for `python` version `>=3.5.4` but not for a version `<3.5.4`. I feel a note about this could be added in the installation instructions. Implicitly, this is happening because of the dependency arising from the usage of `pymc3` and hence, installing `Sensie` for a `python` version `<3.5.4` generates following output - ```ERROR: Package 'pymc3' requires a different Python: 3.5.2 not in '>=3.5.4'```. This would be helpful while creating the virtual environment specifying a python version `>=3.5.4`.

2. Documentation: 
2.1 Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- The examples worked like charm. I had to add `import matplotlib.pyplot as plt` before plotting the histogram in the CIFAR10 example notebook.

2.2 Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?
- The [Sensie Documentation](https://sensie.readthedocs.io/en/latest/) does not mentions anything about the automated tests. Though, information about `tests` is present in the [installation](https://github.com/coljac/sensie#installation) section of the project repository README but not in the documentation. Please verify if I missed anything.

3. Software paper
3.1 The paper is very well drafted and includes relevant information for using the software package. I could only see a difference in the title mentioned in the paper and the title mentioned in the documentation. 
Paper Title - Sensie: Probing the sensitivity of neural networks
Documentation Title - Sensie: Simple neural network sensitivity

Although, I don't feel any reasons not to use both the titles but I am bringing this to the author's interest if they missed it by any chance. 

3.2 The [Discussion and conclusion](https://github.com/coljac/sensie/blob/master/paper/paper.md#discussion-and-conclusion) section in the paper refers to Figure 1 but the images are not annotated with figure title. 
Citing the content from the paper - "Figure 1 shows two examples; on the left, an output plot from Sensie showing the sensitivity of a trained model to rotation of the input images". 
I think it would be a good idea to add figure title below the images to avoid any confusion.

4. Other
-  I found all the examples for models trained using `keras` framework. The documentation also mentions that with user supplied predictor function any framework should be usable. If the authors find it useful, they can explore using [ONNX](https://github.com/onnx/onnx) format for the model object and use the [onnx-converters](https://github.com/onnx/tutorials#converting-to-onnx-format) for using model objects from multiple frameworks. Well, these are my thoughts which I see as potential add-ons for future versions of `Sensie` on authors discretion.

- There are some spelling errors and typos in the repository. Please find them below:
1. [Calculation of the **signficance** of the effect](https://github.com/coljac/sensie#calculation-of-the-signficance-of-the-effect) -> [Calculation of the **significance** of the effect](https://github.com/coljac/sensie#calculation-of-the-signficance-of-the-effect)

2. [Installation](https://github.com/coljac/sensie#installation)
Which will **isntall** Sensie -> Which will **install** Sensie

My remarks:
Reproducibility in machine learning research is an important pursuit in the current research setting. Be it a scenario for deploying an ML/DL model on the production or for using the model for research on a different dataset, sensitivity analysis of the pre-trained model plays a significant role in understanding the variation of evaluation metrics with the data and model parameters. `Sensie` provides a great utility in performing the sensitivity of a machine learning model and quantifying changes in the performance of the model with respect to a parameter. I wish to congratulate the authors for their efforts and for providing a neat software package to the scientific community. Thanks! 
Kind regards,
Rajat

**Comment by coljac** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02180/joss.02180/10.21105.joss.02180.pdf)

**Comment by coljac** [comment]
Hi @omshinde,

Thanks for the remarks and careful attention to the project.

I have addressed your comments as follows:

1. Python version

I altered the README and docs to indicate python 3.6 and above is required (there are f-strings in the Sensie code).

2. Documentation

- I added the matplotlib import to the example notebook.
- I added the reference to pytest and how to run the tests to the documentation.

3. Paper

Thanks for comments about the title - I settled on " Sensie: Probing the sensitivity of neural networks".

Regarding Figure 1 in the paper, you wrote "the images are not annotated with figure title". However, there is a *caption* ("Figure 1: Left: ....") immediately below the image. Do you mean that it would be better to alter the images themselves to add the name of the figure? That's a little non-standard, so I'm not clear on that.

I re-generated the PDF (see immediately above this comment); is it possible you were looking at the markdown in the repository? The github previewer doesn't render the captions properly, but they show up in the PDF.

I fixed the typos. Thanks for spotting those.

Thanks again for reviewing the code.

-Colin

**Comment by omshinde** [comment]
Hi @coljac!

Thank you for addressing the comments. 

> Regarding Figure 1 in the paper, you wrote "the images are not annotated with figure title". However, there is a caption ("Figure 1: Left: ....") immediately below the image. Do you mean that it would be better to alter the images themselves to add the name of the figure? That's a little non-standard, so I'm not clear on that.
> 
> I re-generated the PDF (see immediately above this comment); is it possible you were looking at the markdown in the repository? The github previewer doesn't render the captions properly, but they show up in the PDF.

Oh, I missed out on this. Thanks for pointing it out and sorry for the inconvenience. Yes, the generated PDF looks perfect with the image properly captioned in the paper. Please keep it as it is.

I am completely satisfied with the `Sensie` software package and paper with regards to the JOSS review-checklist. Thanks again for your contribution and congratulations!

-Rajat

**Comment by coljac** [comment]
@gkthiruvathukal - just checking on the next step here from my end. Since both reviewers signed off, should I create an archive of the repository and get a DOI or is that premature?

**Comment by gkthiruvathukal** [comment]
Hi @coljac, thanks for your patience! We are ready to move to the next steps. Can you please do the following?

- [ ] Make a tagged release of your software, and list the version tag of the archived version here. 
- [ ] Archive the reviewed software in Zenodo 
- [ ] Check the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] List the Zenodo DOI of the archived version here.

Let me know when all are done!

**Comment by coljac** [comment]
Hi @gkthiruvathukal,

[Done!](https://zenodo.org/record/3894083) Here's the DOI: `10.5281/zenodo.3894083`

Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@gkthiruvathukal let me know if this submission is ready for processing

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 10.5281/zenodo.3894083 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3894083" target="_blank">10.5281/zenodo.3894083</a> is the archive.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set v1.0.0 as version

**Comment by whedon** [comment]
OK. v1.0.0 is the version.

**Comment by Kevin-Mattheus-Moerman** [comment]
@gkthiruvathukal I've assigned the archive DOI and also update the version label (pumped to v1.0.0). I also check the DOI metadata which seems okay. If you are happy to tick your boxes :point_up: and proceed, let me know. Thanks.

**Comment by gkthiruvathukal** [comment]
@Kevin-Mattheus-Moerman Thanks for your help here! This submission is definitely ready to go. Thanks, @coljac for completing all final steps.

Thanks to @omshinde and @ejhigson for your work as reviewers.

**Comment by omshinde** [comment]
@gkthiruvathukal 
Most Welcome! Indeed, it was a great pleasure. Thanks for giving this opportunity.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02180/joss.02180/10.21105.joss.02180.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.dsp.2017.10.011 is OK
- 10.1109/ICIP.2016.7532763 is OK
- 10.1371/journal.pone.0130140 is OK
- 10.1007/978-3-319-44781-0_8 is OK
- 10.1002/widm.1349 is OK
- 10.3847/1538-4365/ab26b6 is OK
- 10.1093/mnras/stz272 is OK
- 10.1093/mnras/stx1492 is OK

MISSING DOIs

- https://doi.org/10.1109/iccv.2017.74 may be missing for title: Grad-CAM: Visual Explanations From Deep Networks via Gradient-Based Localization

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@coljac some editorial comments on the paper: 

- [ ] Check/fix double occurrence of `directly` in: `Some well-known methods for visualising and interpreting the outputs of DNNs include directly inspecting the learned features of a model directly`
- [ ] Please define the acronym ANN (or should it be DNN?)
- [ ] If the software you cite in footnotes has papers to cite please do add them. 
- [ ] The paper is about to be processed for acceptance in JOSS. Please proofread the paper yourself again. In particular check the author names, affiliations, and acknowledgement section. 

Once you've made these changes please call `@whedon generate pdf` to update the paper (use `@whedon check references` if you add new citations).

**Comment by coljac** [comment]
@Kevin-Mattheus-Moerman 

Done and done. Thanks for catching a couple of issues.

**Comment by coljac** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02180/joss.02180/10.21105.joss.02180.pdf)

**Comment by coljac** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.dsp.2017.10.011 is OK
- 10.1109/ICIP.2016.7532763 is OK
- 10.1371/journal.pone.0130140 is OK
- 10.1007/978-3-319-44781-0_8 is OK
- 10.1002/widm.1349 is OK
- 10.3847/1538-4365/ab26b6 is OK
- 10.1093/mnras/stz272 is OK
- 10.1093/mnras/stx1492 is OK

MISSING DOIs

- https://doi.org/10.1109/iccv.2017.74 may be missing for title: Grad-CAM: Visual Explanations From Deep Networks via Gradient-Based Localization

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@coljac great I ticked all those boxes. Can you check that last potentially missing DOI? Is it this paper: https://ieeexplore.ieee.org/document/8237336 ?

**Comment by coljac** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02180/joss.02180/10.21105.joss.02180.pdf)

**Comment by coljac** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.dsp.2017.10.011 is OK
- 10.1109/ICIP.2016.7532763 is OK
- 10.1371/journal.pone.0130140 is OK
- 10.1007/978-3-319-44781-0_8 is OK
- 10.1002/widm.1349 is OK
- 10.3847/1538-4365/ab26b6 is OK
- 10.1093/mnras/stz272 is OK
- 10.1093/mnras/stx1492 is OK
- 10.1109/ICCV.2017.74 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by coljac** [comment]
@Kevin-Mattheus-Moerman I fixed the erroneous DOI before realising I removed the reference from the body of the paper. I've updated accordingly.

**Comment by coljac** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02180/joss.02180/10.21105.joss.02180.pdf)

**Comment by coljac** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.dsp.2017.10.011 is OK
- 10.1109/ICIP.2016.7532763 is OK
- 10.1371/journal.pone.0130140 is OK
- 10.1007/978-3-319-44781-0_8 is OK
- 10.1002/widm.1349 is OK
- 10.3847/1538-4365/ab26b6 is OK
- 10.1093/mnras/stz272 is OK
- 10.1093/mnras/stx1492 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.dsp.2017.10.011 is OK
- 10.1109/ICIP.2016.7532763 is OK
- 10.1371/journal.pone.0130140 is OK
- 10.1007/978-3-319-44781-0_8 is OK
- 10.1002/widm.1349 is OK
- 10.3847/1538-4365/ab26b6 is OK
- 10.1093/mnras/stz272 is OK
- 10.1093/mnras/stx1492 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1500

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1500, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1273930452617900034) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1501
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02180](https://doi.org/10.21105/joss.02180)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02180/status.svg)](https://doi.org/10.21105/joss.02180)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02180">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02180/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02180/status.svg
   :target: https://doi.org/10.21105/joss.02180
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02180/status.svg)](https://doi.org/10.21105/joss.02180)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
