### ISSUE TITLE
[REVIEW]: Scripts for Easier Use of Spice (SEUS): A Perl script package for simulating and creating batches of circuit netlists for Monte Carlo simulations when using Ngspice or Ngspice-based simulators

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2183]
**Submitting author:** @miketuri (<a href="http://orcid.org/0000-0002-9171-5305">Michael Turi</a>)
**Repository:** <a href="https://bitbucket.org/miketuri/perl-spice-sim-seus/" target ="_blank">https://bitbucket.org/miketuri/perl-spice-sim-seus/</a>
**Version:** v1.1.4
**Editor:** @VivianePons
**Reviewer:** @mzszym, @victorvalgenti
**Archive:** <a href="https://doi.org/10.5281/zenodo.4017949" target="_blank">10.5281/zenodo.4017949</a>

## Status

[![status](https://joss.theoj.org/papers/12f72f4fa20275a0b5d4da0cc0903de9/status.svg)](https://joss.theoj.org/papers/12f72f4fa20275a0b5d4da0cc0903de9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/12f72f4fa20275a0b5d4da0cc0903de9"><img src="https://joss.theoj.org/papers/12f72f4fa20275a0b5d4da0cc0903de9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/12f72f4fa20275a0b5d4da0cc0903de9/status.svg)](https://joss.theoj.org/papers/12f72f4fa20275a0b5d4da0cc0903de9)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://bitbucket.org/miketuri/perl-spice-sim-seus/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mzszym & @victorvalgenti, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @VivianePons know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/miketuri/perl-spice-sim-seus/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@miketuri) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/miketuri/perl-spice-sim-seus/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@miketuri) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mzszym, @victorvalgenti it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.sse.2003.12.030 is OK
- 10.1109/CCWC.2017.7868469 is OK
- 10.1109/TCSII.2019.2922921 is OK
- 10.1016/j.vlsi.2016.12.003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02183/joss.02183/10.21105.joss.02183.pdf)

**Comment by VivianePons** [comment]
Dear @mzszym and @victorvalgenti Are you still willing to review this submission? Do you think you will have time soon?

Best

Viviane

**Comment by victorvalgenti** [comment]
Sorry, Many distractions recently. I should have it done by next week.

Vic v.

**Comment by mzszym** [comment]
I am sorry for the delay, I have just started the review.

**Comment by mzszym** [comment]
I would like to ask the author to fix the following before continuing the review:

- Improve description of the installation: specify example version numbers of ngspice and PERL known to work with this package; provide an example sequence of shell commands for a typical installation

- Provide at least one complete example/testcase (complete input files, expected output files, complete list of shell commands to execute). It should be possible to execute the testcase either automatically or manually to verify that the package works as expected

- Provide community guidelines in the documentation (in the repository), with clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support. 

I think they are not specified directly enough in the repository. I apologize if I missed something, however, I did not find that information where I expected.

**Comment by victorvalgenti** [comment]
@VivianePons I have finally found the time and energy to begin a review. However, I must disclose my conflicts of Interest and also, I seem to have a technical difficulty.
COI:
Mike Turi and I attended WSU at the same time (in different labs). We have been friends and remain in occasional contact (conversations once or twice a year). I worked with Mike on a small project in the summer of 2014 (I believe -- maybe 2015). Said project has nothing to do with SPICE--It was some testing to see how well we could dump data from a 10GB network interface onto SSD and Hard-Disk drives (goal to be able to dump maximum traffic directly to the drives. No paper was produced. In any case, I have not worked with Mike on any other projects. That is the sum of my conflict of Interest. Let me know if this is significant enough to disqualify me.

Technical issue. I don't seem to be able to update the review checklist. Yes, I am logged in. I am not sure if I accepted the invitation in time, though I think I have.

**Comment by VivianePons** [comment]
Hi @victorvalgenti thank you for starting the review

About the conflict of interest, it seems ok to me, I will check with other editors.

About the technical issue, what happen exactly when you try to edit the checklist? Have you tried editing the issue description directly?

**Comment by victorvalgenti** [comment]
@VivianePons I don't seem to have the ability to edit the issue description at all. The menu on the issue description does not provide an edit option. Is there something I am missing?

My basic review is as below. Overall, I agree with @mzszym review.
Software License:
  Present. I would have considered a BSD or MIT license instead, but the GNU license suffices.
  
Scholarly Effort:
 Roughly 3500 lines of well commented code which is a decent-sized project, especially for 1 Author.
 Commits have been compressed into a small number.
 Demonstrates efforts over a decade.
 Software used in authors papers--Not sure outside of that.
 Usefullness: Given that in this type of research-ware that many tools lag well behind regular development this tool is likely useful to a select few working in similar research. As such, there is value for projects such as this--especially to young grad students searching for a tool to help them move forward with their own research (rather than re-inventing the wheel). However, we must note that without sufficient advertisement of this tool (either through paper citations or getting on board with SPICE) most researchers who might use this are likely to end up using ngSPICE solely or find their own solution.
 Overall: The project demonstrates sufficient Scholarly Effort.

Documentation:
   Statement of need: The statement of need is buried in the introduction. It might be better to have a separate statement with more details about the motivation. Exactly what problem is this software solving? Currently, we are told this is a wrapper to ngspice to provide better control, but I have no idea what the benefit of that extra control is.
   Installation Instructions: The installation instructions assume quite a lot of knowledge about Perl. Further, it is based in 'nix and does not account for potential Windows users. If the software is tied to these platforms there should probably be some discussion of those assumptions. Also, a setup script could probably do most of the work. Could probably even use CMake and just have the user use that to build for local use.
   Example Usage: I don't see good documentation of example usage.
   API Documentation: The API is well commented within the code. It might be better to use some sort of automatic documentation like Doxygen or Perldoc and then having a script at install create HTML documentation for user reference.
   Community Guidelines: There are no community guidelines for submission that I can see.
   Tests: There are no tests. Optimally, there should exist a unit test framework to prove functionality and to ensure that updates do not break functionality.
   Overall: Needs Improvement.

Authorship: Author has definitely made a substantial contribution to the project.

Novelty: The development is novel for the solving problems to deal with these particular software packages. So, in that vein, it is derivative but still of value as often dealing with the software packages is more difficult than the desired research.

Software Paper: The software paper provides all of the requirements and does so quite well. Much of this information is missing from the README.

Extra:
**Universal entry**: For a project like this I think it would be nicer to have a single entry-point into the program (i.e. a dispatch script like seus.pl). The user can then designate the desired functions using command line options (example seus.pl -run_spice rather than using run_spice.pl directly). Perl supports getopt and getopt::Long so it is fairly easy to implement. The benefit of this approach is the author may discuss the individual functions rather than the script names. Further, some of the scripts are likely run under-the-hood so to speak so a user might never need to execute them. Such an approach makes the package more cohesive and makes it a little more accessible to users.

**Repository Architecture**: For a project like this I expect the source code to exist in a src directory, Informational documents and install scripts at the top level, and perhaps a docs repository to contain generated help documentation. While throwing everything into a single directory works, it does make it more difficult for users to determine what is important and what is not.

**Unit Tests**: An automated testing set would be really nice. There are quite a few good test frameworks available.

**Full Examples**: A couple of full examples would be nice. They could be in a separate folder and include any data and explanation necessary to get them to run.

**Comment by VivianePons** [comment]
About the potential conflict of interest, thank you very much @victorvalgenti for bringing this possible conflict to our knowledge. I checked with other editors and this can be waved as long as you feel that you can review while staying objective, which seems to be the case.

About the technical difficulties, I am going to ask other editors if they know where this comes from. @arfon seen anything like this before?

**Comment by VivianePons** [comment]
Thank you very much both @victorvalgenti and @mzszym for these reviews. From what I read, this is not ready yet to be published at JOSS. Some issues might be fixed rather quickly like improving the paper and some instructions. Some might take longer: better documentation, implementing some tests, platform dependency. Nevertheless, I can read from @victorvalgenti 's review that there is some research potential in this software and this is a valuable contribution, just not ready for JOSS quality standard as of yet.

I would say the follow up depends on  @miketuri : if you believe that you can make the improvements asked by the reviewers in a reasonable time frame, we can leave this issue open and let you improve the software. If you find that this is going to take longer or if you have other priorities right now, we can close the submission now and let you resubmit when you feel ready to do so.

I any case, I would like to thank you for your submission and your work and encourage you to implement the suggested improvements as they would help your software to be accessible and useful to a larger part of the scientific community.

**Comment by arfon** [comment]
@whedon re-invite @victorvalgenti as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@victorvalgenti please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by arfon** [comment]
@victorvalgenti - can you try clicking the link above? I believe the invites only last for ~7 days.

**Comment by miketuri** [comment]
Thank you @victorvalgenti and @mzszym for your reviews, and thank you @VivianePons for overseeing this and for your comments.  I have examined the review comments and agree that these will improve the software package.  I plan to complete updates on the paper, documentation, installation, tests, and example usage within one to two weeks.  Please let me know if you have any questions about this or this timeline.  Thank you again.

**Comment by VivianePons** [comment]
Just to let you know, I am taking some time off until August 24, I will still be checking my emails and keep an eye on my current assigned submissions. I might just take a bit more time than usual to answer.

**Comment by miketuri** [comment]
Hello @VivianePons , @mzszym , and @victorvalgenti , I have just added a new version (currently 1.1.2) to the repository to address the comments from the previous review and add documentation (generate html files, allow use of 'man' pages, and allow use of 'perldoc'), add tests and examples, add an installation procedure (details are in the README), and improve the paper.  Please let me know if you have any questions about this, or any recommended changes or issues with the package.  Thank you again for working with this during this time.

**Comment by victorvalgenti** [comment]
I have reviewed some of the new code and confirmed that the instructions allow the source to be installed and built and the tests run and pass. I am continuing to examine the documents, however I have one request.

I am glad to see the examples directory, but I would really appreciate some text for running the examples along with enough context to get a feel for what is occurring. Without it, it is really difficult to get a feel for the working. If this text exists already, please point me to it. I think a README or similar walk through for using the scripts is needed and can be contained in the examples directory. As it is, I'm a little lost.

**Comment by miketuri** [comment]
Thank you for taking a look at this again @victorvalgenti.  I have just added a new version (currently 1.1.3) to the repository to add a README/walk-through for the files in the examples/ directory.  I have also added a few more files to the examples/ directory to allow users to test running the scripts on the netlists there.  If you (or @mzszym and @VivianePons) have any more questions or recommendations for this, please let me know.  Thank you.

**Comment by victorvalgenti** [comment]
@VivianePons @mzszym @miketuri I have reviewed the latest changes.

1. Installation instructions and scripts added. The dependencies from CPAN were substantial and require some familiarity with Perl, but are workable.
2. There are now a set of tests and they pass given that the correct modules are installed.
3. The script API is built and documented and populated in the docs/ directory.
4. The examples now contain better explanation and usage examples. The examples work. They could use a little more explanation of the outputs but are sufficient for me.
5. The repository now uses a more organized structure with docs in docs, examples in examples, etc.
6. The script now allows for universal entry using seus.pl.

Thus, my major issues have been addressed.

@miketuri Am I to assume that the community guidelines for this project are: do as you will no warranty, no guarantee, and no help?

Beyond that question, I am fine with this submission.

**Comment by VivianePons** [comment]
I see things are progressing! Thank you @miketuri for the work and @victorvalgenti for the review. 

@mzszym do you think you'll have time to review the new version anytime soon?

**Comment by mzszym** [comment]
@VivianePons I will have a look at it later this week, hopefully it will be possible to finish the interview from my side.

**Comment by miketuri** [comment]
Thank you @VivianePons, @mzszym, and @victorvalgenti for reviewing and overseeing my submission during this time.

And thank you @victorvalgenti for the review; for your question, yes, there is no warranty or guarantee with this software, however, I can be emailed if there are questions, and bugs or feature requests can be submitted via the repository's issues tracker.  I noticed that I included this support information at the end of each of the perldocs, but I did not place this on either readme.  I can copy this information to the end of each readme to make this easier to find.

**Comment by mzszym** [comment]
@VivianePons @miketuri I apologize for additional days of delay. I am done with the review, I believe it is a good piece of software. It certainly does what it should, and is of value for people in electronics community.

On side of small comments:
- It would be great to add community guidelines directly to the README; currently I find it in paper.md which I believe is not the place where people will look in the first place
- I had some issues with unit tests on my computer. I believe this is only a technical problem, I still could run examples. I do not think it should block the paper.

**Comment by miketuri** [comment]
@mzszym Thank you for your review.  @victorvalgenti also indicated that it should be easier to find the community guidelines.  To address this I have added a new version to the repository (version 1.1.4) to add support/contribution info, author contact info, and copyright/warranty info to the main README, as well as the README in the examples/ directory.  I also made some minor changes to batchexec_seus.pl to improve compatibility on non-Unix/Linux systems.

@mzszym, @victorvalgenti, and @VivianePons Thank you again for reviewing this during this time.  Please let me know if need anything else.  @mzszym, if you wish, you can report unit test issues via the [issues tracker](https://bitbucket.org/miketuri/perl-spice-sim-seus/issues) or via my email.

**Comment by VivianePons** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.sse.2003.12.030 is OK
- 10.1109/CCWC.2017.7868469 is OK
- 10.1109/TCSII.2019.2922921 is OK
- 10.1016/j.vlsi.2016.12.003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by VivianePons** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02183/joss.02183/10.21105.joss.02183.pdf)

**Comment by VivianePons** [comment]
Thank you very much @miketuri for the work and @mzszym and @victorvalgenti for the helpful reviews! I am very happy about the course this submission took, the review process has clearly improved the quality of the paper and we are now heading towards acceptance!

I am only missing one checkbox from @victorvalgenti : can you look at the latest changes made by @miketuri regarding community guidelines?

**Comment by victorvalgenti** [comment]
@VivianePons I have checked the final checkbox.

**Comment by VivianePons** [comment]
Perfect!

@miketuri could you make an archive (on Zenodo, figshare, or other) and send it to me? Please use the same title as for the JOSS paper.

**Comment by miketuri** [comment]
Hello @VivianePons, I have just made an archive on Zenodo; it can be found at https://doi.org/10.5281/zenodo.4017949
Let me know if you need to make any changes or need anything else.  Thank you!

**Comment by VivianePons** [comment]
@whedon set v1.1.4 as version

**Comment by whedon** [comment]
OK. v1.1.4 is the version.

**Comment by VivianePons** [comment]
@whedon set 10.5281/zenodo.4017949 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4017949" target="_blank">10.5281/zenodo.4017949</a> is the archive.

**Comment by VivianePons** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.sse.2003.12.030 is OK
- 10.1109/CCWC.2017.7868469 is OK
- 10.1109/TCSII.2019.2922921 is OK
- 10.1016/j.vlsi.2016.12.003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1719

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1719, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@VivianePons - just to check, you've proofread this and it's ready to go in your opinion?

**Comment by VivianePons** [comment]
Yes!

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1303321861443457024) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1720
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02183](https://doi.org/10.21105/joss.02183)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @mzszym & @victorvalgenti for reviewing, and @VivianePons for editing!

Congratulations to @miketuri (Michael Turi)!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02183/status.svg)](https://doi.org/10.21105/joss.02183)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02183">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02183/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02183/status.svg
   :target: https://doi.org/10.21105/joss.02183
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02183/status.svg)](https://doi.org/10.21105/joss.02183)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
