### ISSUE TITLE
[REVIEW]: Omorfi: Open morphology of Finnish

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2184]
**Submitting author:** @flammie (<a href="http://orcid.org/0000-0003-1207-5395">Tommi Pirinen</a>)
**Repository:** <a href="https://github.com/flammie/omorfi/" target ="_blank">https://github.com/flammie/omorfi/</a>
**Version:** 2020-05-11
**Editor:** @hugoledoux
**Reviewers:** @desilinguist, @alvations
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/110b650c2900d538291af954f2b74219/status.svg)](https://joss.theoj.org/papers/110b650c2900d538291af954f2b74219)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/110b650c2900d538291af954f2b74219"><img src="https://joss.theoj.org/papers/110b650c2900d538291af954f2b74219/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/110b650c2900d538291af954f2b74219/status.svg)](https://joss.theoj.org/papers/110b650c2900d538291af954f2b74219)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/flammie/omorfi/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@desilinguist, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @hugoledoux know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/flammie/omorfi/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@flammie) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/flammie/omorfi/">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@flammie) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @desilinguist it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02184/joss.02184/10.21105.joss.02184.pdf)

**Comment by hugoledoux** [comment]
@whedon add @alvations as reviewer

**Comment by whedon** [comment]
OK, @alvations is now a reviewer

**Comment by arfon** [comment]
:wave: @hugoledoux - you'll need to edit the issue at the top of this thread to add a checklist for @alvations (Whedon doesn't know how to do this mid-review just yet).

Let me know if you need my help doing this.

**Comment by hugoledoux** [comment]
oh, I should have RTFD. Actually I did, just spotted the command in red, and moved on.

It's fixed now.

**Comment by alvations** [comment]
Okay, it's a little overwhelming but definitely not tonight but I'll work on the review over the coming week nights. 

A few questions on the JOSS review, should the comments on the review come here in this issue or should it go directly to https://github.com/flammie/omorfi/issues/new so that the problems in the review are corrected? 

Also, regarding the high-level summary (the read-able paper), how do I get access to it for the review of that too?

**Comment by hugoledoux** [comment]
yes it is at first.

You should indeed create issues in the original repo, and link to them here.

The idea is simply to verify/check that all the items in the checklist above (watch out, there's one for you and one for the other reviewer) are okay.

The PDF is available a few comments above here, or [here](https://github.com/openjournals/joss-papers/blob/joss.02184/joss.02184/10.21105.joss.02184.pdf)

**Comment by alvations** [comment]
Thanks @hugoledoux for the clarifications! 

Commenting out the partial reviews first, will undo the comments at the end.

**Comment by hugoledoux** [comment]
👋 @alvation & @desilinguist I was wondering if you need any help/instructions at this point or if I can help?

**Comment by desilinguist** [comment]
Sorry for the delay. I just started the review but I can't proceed because I am finding the installation quite confusing. It's not clear to me what instructions should be followed.

**Comment by hugoledoux** [comment]
@flammie could you help clarify here?

**Comment by flammie** [comment]
Yeah, there's no pip package or similar yet, but I can look into making one in near future. The minimum installation is to get dependencies which are packaged and you probably need to run autoreconf and configure to have helper scripts use right program paths. The language models can then be downloaded from latest release instead of compiling anew. The readme improvements are tracked in an issue in the repo, I'll try to clarify the instructions.

**Comment by hugoledoux** [comment]
@flammie - I'm going to mark this review as paused for now as it sounds like there's a non-trivial amount of work for you to complete before the reviewers can get started. Please let me know when you're ready to continue and I will then remove the paused label.

**Comment by flammie** [comment]
I’ve pushed new release today with pip support and some fixes to the documentation hopefully...

**Comment by hugoledoux** [comment]
@desilinguist @alvations can it give it another try?

**Comment by desilinguist** [comment]
Sure, I’ll take a look when I can.

________________________________

**Comment by alvations** [comment]
Sorry for the non-response for the past few months, has been a whirlwind of things happening. Will look at it in the reviewing few weeks.

**Comment by hugoledoux** [comment]
👋 @alvations and @desilinguist, do you think you could give it another try soon? I'd like to not let that review stall too much.

**Comment by arfon** [comment]
:wave: @alvations and @desilinguist – just checking in here. Do you think you could take another look at this submission soon and the updates @flammie has made to improve the installation process?

**Comment by desilinguist** [comment]
Apologies for the delay. I will try to take a look this week.

**Comment by desilinguist** [comment]
Sorry for the delay on this. I took a look at the updated instructions and while they are certainly better than before, I still think the bar to entry is rather high and this shouldn't really be the case in 2021. I can think of two ways to make this much easier for folks who just want to try out the package:

- Build a conda package. Since conda provides the `c-compiler` and `cxx-compiler` packages, it should be fairly easy to build a self-contained package that installs all the dependencies needed.

- Provide a docker image with all of the dependencies and the package that folks can download and easily try out all the great things it does. 

I understand that this submission has been held up for a long time so please consider these only recommendations and not requirements. As far as I am concerned, this submission can now go forward and is ready to be published. 

Good work @flammie!

**Comment by flammie** [comment]
Thanks for the feedback, I tried both conda-builder and docker a bit, [a basic Dockerfile](https://github.com/flammie/omorfi/commit/b8c072b3f5e8b4c9b805b153ecc97dbeaa674f7d) was easy to create, but for conda support, one required dependency hfst would need packaging before.

**Comment by hugoledoux** [comment]
👋 @alvations , could you let us know whether you are planning to finish this review? If not then it's fine, but knowing would help us move forward

**Comment by hugoledoux** [comment]
I would agree with this 👍
