### ISSUE TITLE
[PRE REVIEW]: spam: Software for Practical Analysis of Materials

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2186]
**Submitting author:** @edwardando (<a href="http://orcid.org/0000-0001-5509-5287">Edward Andò</a>)
**Repository:** <a href="https://gricad-gitlab.univ-grenoble-alpes.fr/ttk/spam/" target ="_blank">https://gricad-gitlab.univ-grenoble-alpes.fr/ttk/spam/</a>
**Version:** 0.5.1.4
**Editor:** @usethedata
**Reviewers:** @Shuang-Plum, @jwbuurlage
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @edwardando. **Currently, there isn't an JOSS editor assigned** to your paper.

@edwardando if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2186 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/2186/docs/paper/paper.md): could not find expected ':' while scanning a simple key at line 17 column 5 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=2.66 s (83.5 files/s, 100885.8 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
SVG                              14             14             18         190613
C++                              36           2603           6952          20158
Python                          103           5146           9465          14413
C                                 3            709           1954           5859
reStructuredText                 27           1129            949           1682
TeX                               4            140             71            950
HTML                              3            149             15            850
Markdown                          3            197              0            668
C/C++ Header                     15            384           1808            635
Cython                            3             40             82            198
Pascal                            2              0             97            113
make                              5             10             19             52
YAML                              1              5              0             44
Bourne Again Shell                2              6              3             27
Bourne Shell                      1              4              8             20
--------------------------------------------------------------------------------
SUM:                            222          10536          21441         236282
--------------------------------------------------------------------------------


Statistical information for the repository '2186' was gathered on 2020/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alejandro Ortega Lab             3           425            315            0.28
Christos Papazoglou              7           578             37            0.23
Cyrille-B Couture                2            11              6            0.01
EXT Papazoglou Chris             1           121             35            0.06
Edward                           5            62             55            0.04
Edward Ando                      9           667            598            0.47
Edward Andò                    498         92588          45047           51.66
Elin Törnquist                   1            15             14            0.01
Emmanuel Roubin                220         45491          35887           30.55
Estefan Garcia                   3           184             32            0.08
Gustavo Adolfo Pinzo            16          1827           1386            1.21
Gustavo Pinzon                   1            89             79            0.06
Ilija Vego                       1           203              0            0.08
Max Wiebicke                    19          1159             56            0.46
Olga Stamati                    91          4162           2308            2.43
Olumide                          6           246             12            0.10
Olumide Okubadejo                1          1537            913            0.92
Robert Caulk                     3           150             57            0.08
Ryan Hurley                      3           324              4            0.12
Tom Arnaud                      16          2934            381            1.24
Yue SUN                          5           350            142            0.18
remche                          50          2157          17163            7.25
roubin                           2          5582            645            2.34
yue.sun                          2           370              0            0.14

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alejandro Ortega Lab        419           98.6          2.8               64.92
Christos Papazoglou         122           21.1         11.9                9.02
Edward Ando                  71           10.6         34.1               16.90
Edward Andò               47509           51.3         24.3               25.95
Elin Törnquist                6           40.0          8.4                0.00
Emmanuel Roubin           13359           29.4         18.6               18.60
Estefan Garcia               12            6.5          7.3                0.00
Gustavo Adolfo Pinzo       1021           55.9          1.7               13.22
Gustavo Pinzon               86           96.6          2.4               36.05
Ilija Vego                   67           33.0          0.7               14.93
Max Wiebicke                971           83.8         22.8               14.52
Olga Stamati               1339           32.2         15.8               13.97
Olumide Okubadejo           216           14.1         25.3               13.43
Robert Caulk                127           84.7          6.5                4.72
Ryan Hurley                 184           56.8         18.9               13.59
Tom Arnaud                  425           14.5         11.8               18.59
Yue SUN                     210           60.0         22.8               10.95
remche                      518           24.0         30.8               46.33
roubin                      178            3.2         33.9               14.04
yue.sun                      49           13.2         30.9               20.41
```

**Comment by arfon** [comment]
@edwardando - thanks for your submission to JOSS. It looks like there's an issue with the metadata of your paper. One obvious issue is the missing ORCID keys. i.e. change this:

```
authors:
  - name: Olga Stamati
    affiliation: 1
  - name: Edward Andò
    0000-0001-5509-5287
```

to this:

```
authors:
  - name: Olga Stamati
    affiliation: 1
  - name: Edward Andò
    orcid: 0000-0001-5509-5287
```

There may be other issues though that I didn't spot. You can test if your paper compiles properly here: http://whedon.theoj.org

**Comment by arfon** [comment]
@usethedata this looks like it could be a good fit - I'm going to go ahead and assign it to you. Please let me know if this isn't OK.

**Comment by arfon** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by edwardando** [comment]
Thanks: I don't see the problem with orcid, perhaps it's been fixed.

Just a piece of info - we mentioned @Kevin-Mattheus-Moerman as a suggested editor in the submission process.

**Comment by arfon** [comment]
@whedon generate pdf from branch spamPaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch spamPaper. Reticulating splines etc...
```

**Comment by arfon** [comment]
> Thanks: The orcid problem is in the main branch, we've been working on the paper in a branch called `spamPaper`, although if it's easier we can merge this into master.

Thanks @edwardando - this is probably OK for now but before publishing/accepting the submission it would be good for the paper to be in `master`.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02186/joss.02186/10.21105.joss.02186.pdf)

**Comment by edwardando** [comment]
Happy with the proof.

OK, we'll merge if and when the paper is accepted.

**Comment by edwardando** [comment]
If more than one editor is needed, here are some relevant choices from `list[1000:-1]`:

- SebastianoF
- dbrizard
- crstnbr
- hanayik
- Shuang-Plum
- iagolemos1
- luthaf
- jwbuurlage

**Comment by edwardando** [comment]
We made a tiny change.

@whedon generate pdf from branch spamPaper

**Comment by edwardando** [comment]
@whedon generate pdf from branch spamPaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch spamPaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02186/joss.02186/10.21105.joss.02186.pdf)

**Comment by usethedata** [comment]
@edwardando Thanks for the list of suggested reviewers.  I have reached out to a couple via email to see if they are willing.

**Comment by edwardando** [comment]
Perfect, let me know if and when I should look higher up the list.

**Comment by usethedata** [comment]
One decline, no response on other request.  Resent request and will send out a new request for the slot that was declined.

**Comment by usethedata** [comment]
@whedon add @Shuang-Plum as reviewer

**Comment by whedon** [comment]
OK, @Shuang-Plum is now a reviewer

**Comment by edwardando** [comment]
So now a new issue will be created with the review?

**Comment by usethedata** [comment]
@whedon add @jwbuurlage as reviewer

**Comment by whedon** [comment]
OK, @jwbuurlage is now a reviewer

**Comment by usethedata** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2286.
