### ISSUE TITLE
[PRE REVIEW]: DVRlib: A C++ library for geometric mesh improvement using Directional Vertex Relaxation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2187]
**Submitting author:** @rram84 (<a href="http://orcid.org/0000-0001-7403-7728">Ramsharan Rangarajan</a>)
**Repository:** <a href="https://bitbucket.org/rram/dvrlib/src/joss/" target ="_blank">https://bitbucket.org/rram/dvrlib/src/joss/</a>
**Version:** v1.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @hugoledoux, @jhale, @jonwong12
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @rram84. **Currently, there isn't an JOSS editor assigned** to your paper.

@rram84 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.21 s (359.8 files/s, 68675.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                    50           1646           3985           5337
C++                             16            369            838           1273
Markdown                         2             32              0            200
CMake                            4             47             40            199
TeX                              1             14              1            114
make                             1              2              0             26
-------------------------------------------------------------------------------
SUM:                            74           2110           4864           7149
-------------------------------------------------------------------------------


Statistical information for the repository '2187' was gathered on 2020/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ramsharan Rangarajan           187         43676          30130          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ramsharan Rangarajan      13448           30.8          7.7               35.88
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1137/16m1089101 may be missing for title: Provably robust directional vertex relaxation for geometric mesh optimization
- https://doi.org/10.1007/s10589-017-9903-z may be missing for title: On the resolution of certain discrete univariate max–min problems
- https://doi.org/10.1145/2629697 may be missing for title: TetGen, a Delaunay-based quality tetrahedral mesh generator
- https://doi.org/10.1002/nme.2579 may be missing for title: Gmsh: A 3-D finite element mesh generator with built-in pre-and post-processing facilities
- https://doi.org/10.1007/bfb0014497 may be missing for title: Triangle: Engineering a 2D quality mesh generator and Delaunay triangulator
- https://doi.org/10.1137/s0036144503429121 may be missing for title: A simple mesh generator in MATLAB
- https://doi.org/10.1016/s0045-7949(02)00002-0 may be missing for title: A three-dimensional torsional spring analogy method for unstructured dynamic meshes
- https://doi.org/10.1002/nme.5960 may be missing for title: A shape optimization approach for simulating contact of elastic membranes with rigid obstacles
- https://doi.org/10.1002/nme.5949 may be missing for title: An algorithm for triangulating smooth three-dimensional domains immersed in universal meshes

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02187/joss.02187/10.21105.joss.02187.pdf)

**Comment by arfon** [comment]
@Kevin-Mattheus-Moerman - this looks very much up your street. Is this something you'd be able to take on? If not, we can look for another editor or waitlist it until you have more availability.

**Comment by arfon** [comment]
@whedon invite @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
@Kevin-Mattheus-Moerman has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @hugoledoux as reviewer

**Comment by whedon** [comment]
OK, @hugoledoux is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@avaxman @fwilliams @alecjacobson @keenancrane @sgsellan @nicoguaro @ranahanocka would you be interested in reviewing this work for [JOSS (the Journal of Open Source Software)](https://joss.theoj.org)? 

Submission: _DVRlib: A C++ library for geometric mesh improvement using Directional Vertex Relaxation_

The review process focuses on the software:
https://bitbucket.org/rram/dvrlib/src/joss/
and this short paper:
https://github.com/openjournals/joss-papers/blob/joss.02187/joss.02187/10.21105.joss.02187.pdf

If you are interested you can let me know here so I can add you as a reviewer. Once I have sufficient reviewers I'll trigger a dedicated review issue where the review takes place.

**Comment by rram84** [comment]
Please let me know if there is anything I can/need to do at this stage.

**Comment by hugoledoux** [comment]
planning to do this later this week

**Comment by Kevin-Mattheus-Moerman** [comment]
@rram84 I'd like to find an additional reviewer. Can you recommend any reviewers that I've missed? Thanks.

**Comment by rram84** [comment]
@Kevin-Mattheus-Moerman
I would like to recommend jonwong12
Dr Jonathan Wong at Lawrence Livermore National Labs: 
(https://www.linkedin.com/in/jonathan-wong-2ab79729/)

I will send a few more suggestions asap.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jonwong12 @avaxman @fwilliams @alecjacobson @keenancrane @sgsellan @nicoguaro @ranahanocka would you be interested in reviewing this work for [JOSS (the Journal of Open Source Software)](https://joss.theoj.org)? 

Submission: _DVRlib: A C++ library for geometric mesh improvement using Directional Vertex Relaxation_

The review process focuses on the software:
https://bitbucket.org/rram/dvrlib/src/joss/
and this short paper:
https://github.com/openjournals/joss-papers/blob/joss.02187/joss.02187/10.21105.joss.02187.pdf

If you are interested you can let me know here so I can add you as a reviewer. Once I have sufficient reviewers I'll trigger a dedicated review issue where the review takes place.

**Comment by rram84** [comment]
@Kevin-Mattheus-Moerman
Suggested reviewer: popersson
Prof Per-Olof Persson, UC Berkeley 
http://persson.berkeley.edu/  
https://popersson.github.io/distmesh/

**Comment by pearsonkyle** [comment]
Thank you for the consideration but unfortunately, I can not review it at this time.

**Comment by popersson** [comment]
Sorry, too much behind on everything else.

Per

**Comment by fwilliams** [comment]
I'm really sorry but I won't be able to do this. I'm very busy with other projects at the moment.

**Comment by rram84** [comment]
@Kevin-Mattheus-Moerman
Suggested reviewers:

jhale
Dr Jack Hale, Research Scientist, University of Luxembourg 
https://jackhale.co.uk/

aaortizb
Prof Alejandro Ortiz-Bernardin, Associate Professor, Universidad de Chile
https://camlab.cl/members/alejandro/

**Comment by Kevin-Mattheus-Moerman** [comment]
@jhale @aaortizb @jonwong12 @keenancrane @sgsellan @ranahanocka would you be interested in reviewing this work for [JOSS (the Journal of Open Source Software)](https://joss.theoj.org)? 

Submission: _DVRlib: A C++ library for geometric mesh improvement using Directional Vertex Relaxation_

The review process focuses on the software:
https://bitbucket.org/rram/dvrlib/src/joss/
and this short paper:
https://github.com/openjournals/joss-papers/blob/joss.02187/joss.02187/10.21105.joss.02187.pdf

If you are interested you can let me know here so I can add you as a reviewer. Once I have sufficient reviewers I'll trigger a dedicated review issue where the review takes place.

**Comment by jhale** [comment]
Yes I can review the paper.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @jhale as reviewer

**Comment by whedon** [comment]
OK, @jhale is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@perlr would you be interested in reviewing this work for JOSS? would you be interested in reviewing this work for [JOSS (the Journal of Open Source Software)](https://joss.theoj.org)? 

Submission: _DVRlib: A C++ library for geometric mesh improvement using Directional Vertex Relaxation_

The review process focuses on the software:
https://bitbucket.org/rram/dvrlib/src/joss/
and this short paper:
https://github.com/openjournals/joss-papers/blob/joss.02187/joss.02187/10.21105.joss.02187.pdf

If you are interested you can let me know here so I can add you as a reviewer. Once I have sufficient reviewers I'll trigger a dedicated review issue where the review takes place.

**Comment by jonwong12** [comment]
Sorry about the late reply. I can also review the paper if it would be useful.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @jonwong12 as reviewer

**Comment by whedon** [comment]
OK, @jonwong12 is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2372.
