### ISSUE TITLE
[PRE REVIEW]: qMRLab: Quantitative MRI Analysis, under one umbrella

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2188]
**Submitting author:** @agahkarakuzu (<a href="http://orcid.org/0000-0001-7283-271X">Agah Karakuzu</a>)
**Repository:** <a href="https://github.com/qMRLab/qMRLab" target ="_blank">https://github.com/qMRLab/qMRLab</a>
**Version:** v2.4.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @grlee77, @mfroeling, @62442katieb
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @agahkarakuzu. **Currently, there isn't an JOSS editor assigned** to your paper.

@agahkarakuzu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2188 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2188 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.21105/joss.00656 may be missing for title: QUIT: QUantitative imaging tools
- https://doi.org/10.1016/b978-012372560-8/50002-4 may be missing for title: Statistical parametric mapping
- https://doi.org/10.1101/343079 may be missing for title: Let’s talk about cardiac T1 mapping
- https://doi.org/10.1016/j.softx.2019.100369 may be missing for title: Total Mapping Toolbox (TOMATO): An open source library for cardiac magnetic resonance parametric mapping
- https://doi.org/10.4135/9781412950657.n33 may be missing for title: The cathedral and the bazaar

INVALID DOIs

- None
```

**Comment by arfon** [comment]
Whedon is struggling with compiling the paper here as the repository is very large (~500Mb) - it might be a good idea to look at reducing this @agahkarakuzu. For now, I have compiled the paper locally: [10.21105.joss.02188.pdf](https://github.com/openjournals/joss-reviews/files/4662829/10.21105.joss.02188.pdf)

👋 @cMadan - would you be able to take this paper? Ariel would be the ideal editor but he's unable to edit for JOSS right now.

**Comment by agahkarakuzu** [comment]
Hi @arfon, thank you for the quick response and the feedback!

The repo had some large files in the past, hence the large size with deep clone depth. Right now the documentation files are stored in this repo, moving them elsewhere would free some considerable space, but the same issue would still persist with clone.  Do you have a suggestion how we might approach this? 

We discussed with the team about removing the large files from the history, but it looked like a tricky operation, so we did not act on it.

**Comment by mathieuboudreau** [comment]
@arfon (Hi, one of @agahkarakuzu 's coauthors here) Does Whedon clone the entire repo's git history, or just the master branch and/or a single commit of it?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2188 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
> @arfon (Hi, one of @agahkarakuzu 's coauthors here) Does Whedon clone the entire repo's git history, or just the master branch and/or a single commit of it?

It does a full clone. I could investigate how to do a shallow clone.

**Comment by arfon** [comment]
I've done a little digging here and it turns out we need the full history for calculating things like the repository statistics.

> We discussed with the team about removing the large files from the history, but it looked like a tricky operation, so we did not act on it.

This is the only thing that will truly fix this issue but it's not essential for the JOSS review as I can compile the paper locally and update the thread with the PDF as we go.

That said, I would encourage you to address this issue as all of your future users will have to clone a very large repository which isn't a great user experience.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon I can take this one if @cMadan can't

**Comment by arfon** [comment]
Thanks @Kevin-Mattheus-Moerman. Feel free to grab this now if you feel able to handle it.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@mfroeling, @oliverchampion, @grlee77, @JoshKarpel, @rljacobson, @angielaird, @Lestropie would you be interested in reviewing: _qMRLab: Quantitative MRI Analysis, under one umbrella_, for [JOSS (the Journal of Open Source Software)](joss.theoj.org/). 
The review takes place on GitHub and focuses on [the software](https://github.com/qMRLab/qMRLab) and this short paper: 
https://github.com/openjournals/joss-reviews/files/4662829/10.21105.joss.02188.pdf

If you agree to review this work you can let me know here and I'll add you as a reviewer. Once I have sufficient reviewers I'll open a dedicated review issues. 

Thanks!

**Comment by grlee77** [comment]
Yes, I can review this

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @grlee77 as reviewer

**Comment by whedon** [comment]
OK, @grlee77 is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@mfroeling, @oliverchampion, @JoshKarpel, @rljacobson, @Lestropie, @mriedel56 @62442katieb would you be interested in reviewing: _qMRLab: Quantitative MRI Analysis, under one umbrella_, for [JOSS (the Journal of Open Source Software)](joss.theoj.org/). 
The review takes place on GitHub and focuses on [the software](https://github.com/qMRLab/qMRLab) and this short paper: 
https://github.com/openjournals/joss-reviews/files/4662829/10.21105.joss.02188.pdf

If you agree to review this work you can let me know here and I'll add you as a reviewer. Once I have sufficient reviewers I'll open a dedicated review issues. 

Thanks!

**Comment by JoshKarpel** [comment]
I am not familiar with either QMRI or MATLAB, so I think I should pass. Thanks for the offer!

**Comment by rljacobson** [comment]
@Kevin-Mattheus-Moerman Unfortunately, I am unavailable.

**Comment by mriedel56** [comment]
Hi @Kevin-Mattheus-Moerman, I dont think I’m knowledgeable enough about qMRI to provide a sufficient review; but happy to be considered for other submissions.

**Comment by Lestropie** [comment]
While I would like to do so and familiarise myself with JOSS prior to hopefully submitting my own work there in the future, I unfortunately cannot commit to a thorough review right now due to other obligations. But thank you for the offer.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mfroeling agreed to review in an email, thanks Martijn

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @mfroeling as reviewer

**Comment by whedon** [comment]
OK, @mfroeling is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@Lestropie @mriedel56 @rljacobson understood, and thanks for your reply

**Comment by Kevin-Mattheus-Moerman** [comment]
@62442katieb @exmakhina @cMadan @@WIAS-BERLIN @JPolzehl would you be interested in reviewing: _qMRLab: Quantitative MRI Analysis, under one umbrella_, for JOSS (the Journal of Open Source Software).

The review takes place on GitHub and focuses on the software and this short paper:
https://github.com/openjournals/joss-reviews/files/4662829/10.21105.joss.02188.pdf

If you agree to review this work you can let me know here and I'll add you as a reviewer. Once I have sufficient reviewers I'll open a dedicated review issue.

Thanks!

**Comment by 62442katieb** [comment]
Hi @Kevin-Mattheus-Moerman, I'd be happy to review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @62442katieb as reviewer

**Comment by whedon** [comment]
OK, @62442katieb is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2343.
