### ISSUE TITLE
[PRE REVIEW]: uravu: Making Bayesian modelling easy(er)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2189]
**Submitting author:** @arm61 (<a href="http://orcid.org/0000-0003-3381-5911">Andrew McCluskey</a>)
**Repository:** <a href="https://github.com/arm61/uravu" target ="_blank">https://github.com/arm61/uravu</a>
**Version:** v0.0.7
**Editor:** @dfm
**Reviewers:** @ejhigson, @joshspeagle
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @arm61. **Currently, there isn't an JOSS editor assigned** to your paper.

@arm61 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.29 s (171.8 files/s, 14977.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          16            357            595            907
Markdown                         8             66              0            213
Jupyter Notebook                 6              0           1516            196
reStructuredText                11             46             75             67
TeX                              1              4              0             63
SVG                              1              0              1             31
YAML                             2              5             12             30
DOS Batch                        1              8              1             26
JSON                             1              0              0             21
make                             1              4              7              9
CSS                              1              2              0              9
-------------------------------------------------------------------------------
SUM:                            49            492           2207           1572
-------------------------------------------------------------------------------


Statistical information for the repository '2189' was gathered on 2020/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andrew McCluskey               112          5172           3313          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andrew McCluskey           1859           35.9          1.5               16.41
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/s41592-019-0686-2 is OK
- 10.1093/mnras/staa278 is OK
- 10.21105/joss.01864 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.21105/joss.00024 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02189/joss.02189/10.21105.joss.02189.pdf)

**Comment by arfon** [comment]
:wave: @dfm - the submitting author suggested you as the handling editor and this looks like it could be a good fit. I'll go ahead and assign this to you now - please let me know if this is a problem.

**Comment by arfon** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by arm61** [comment]
Potential reviewers:
- @ejhigson 
- @andyfaff
- @GregoryAshton
- @joshspeagle (not on the review list but their `dynesty` package is used by `uravu`)  

I am sure that @dfm knows plenty of others that would be suitable too though!

**Comment by ejhigson** [comment]
@arm61 @dfm @arfon I am happy to review this submission!

**Comment by dfm** [comment]
I'm happy to edit this and I'll start looking into recruiting reviewers shortly.

@ejhigson: Thanks for responding! I'll confirm shortly.

**Comment by dfm** [comment]
@ejhigson: You're on! I'll add you as a reviewer and add another as soon as I have confirmation. Thanks!

**Comment by dfm** [comment]
@whedon assign @ejhigson as reviewer

**Comment by whedon** [comment]
OK, @ejhigson is now a reviewer

**Comment by dfm** [comment]
Good news: @joshspeagle has also agreed to be a reviewer. Thanks Josh!

**Comment by dfm** [comment]
@whedon add @joshspeagle as reviewer

**Comment by whedon** [comment]
OK, @joshspeagle is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2214.

**Comment by dfm** [comment]
@arm61, @ejhigson, @joshspeagle: The main review thread is now at: https://github.com/openjournals/joss-reviews/issues/2214

We can head over there to start the review. Thanks all!
