### ISSUE TITLE
[PRE REVIEW]: filltex: Automatic queries to ADS and INSPIRE databases to fill LaTex bibliography

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#219]
**Submitting author:** @dgerosa (<a href="http://orcid.org/0000-0002-0933-3579">Davide Gerosa</a>)
**Repository:** <a href="https://github.com/dgerosa/filltex" target ="_blank">https://github.com/dgerosa/filltex</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** @lnielsen

**What this issue is for**

Thanks for submitting your paper to JOSS @dgerosa. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: @lnielsen - would you be willing to review this submission for JOSS?

**Comment by arfon** [comment]
@whedon assign @lnielsen as reviewer

**Comment by arfon** [comment]
@whedon assign @lnielsen as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @lnielsen

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/222. Feel free to close this issue now!

**Comment by arfon** [comment]
@lnielsen - please head over the #222 to complete the review.

Many thanks in advance! ✨
