### ISSUE TITLE
[PRE REVIEW]: GridTest: testing and metrics collection for Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2192]
**Submitting author:** @vsoch (<a href="http://orcid.org/0000-0002-4387-3819">Vanessa Sochat</a>)
**Repository:** <a href="https://github.com/vsoch/gridtest" target ="_blank">https://github.com/vsoch/gridtest</a>
**Version:** 0.0.14
**Editor:** @usethedata
**Reviewers:** @cbrueffer, @khinsen
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @vsoch. **Currently, there isn't an JOSS editor assigned** to your paper.

@vsoch if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.96 s (216.7 files/s, 50680.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            45           4950             44           9134
JavaScript                      14           2237           2256           8541
Markdown                        45           1469              0           6321
Python                          47           1116           1376           3074
SVG                              7              0              0           2691
JSON                             6              0              0           1750
CSS                              6            317            288           1699
YAML                            26             64             35            635
make                             1             30              5            190
reStructuredText                 7             79            132             90
Bourne Shell                     3             15             11             64
TeX                              1              2              0             22
-------------------------------------------------------------------------------
SUM:                           208          10279           4147          34211
-------------------------------------------------------------------------------


Statistical information for the repository '2192' was gathered on 2020/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Vanessasaurus                    6          1489            379            8.67
vsoch                           52         18888            794           91.33

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vanessasaurus              1269           85.2          0.1               12.61
vsoch                     17935           95.0          0.5               17.12
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02192/joss.02192/10.21105.joss.02192.pdf)

**Comment by arfon** [comment]
:wave: @usethedata - this looks like it could be a good fit for you. I'll go ahead and assign this to you now - please let me know if this is a problem.

**Comment by arfon** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by vsoch** [comment]
Thank you @whedon, @arfon, and @usethedata! Since this is a Python-based tool that is generally usable across domains, I'll suggest reviewers that are keen on Python. I'll also try to choose reviewers that aren't currently reviewing, and haven't reviewed recently to help balance the work.

 - khinsen
 - ahurriyetoglu
 - Adrianzo
 - jochym
 - cbrueffer

Let me know if you want others, or otherwise different.

**Comment by usethedata** [comment]
@vsoch -- Thank you.

@khninsen and @cbrueffer -- Would you be willing to review this paper for the Journal of Open Source Software?  I realize this would be a first review and I'm happy to help walk through that process.  When I have at least one (and preferably the needed two) reviewers, I will open up a review issue that will have a checklist for each reviewer and some additional instructions.  My email is in my GitHub profile if you'd like to discuss off-line.

**Comment by vsoch** [comment]
@khinsen see above!

**Comment by cbrueffer** [comment]
Hi everyone,

looks interesting; happy to review, but I won't have time to work on this for the next ~two weeks. If that's alright, please sign me up.

**Comment by usethedata** [comment]
@cbrueffer When do you think you would be able to work on this?

**Comment by cbrueffer** [comment]
I can commit to it from about June 13.

**Comment by vsoch** [comment]
That's definitely okay with me!

**Comment by usethedata** [comment]
@whedon set @cbrueffer as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by usethedata** [comment]
@wehedon assign @cbrueffer as reviewer

**Comment by usethedata** [comment]
@whedon assign @cbrueffer as reviewer

**Comment by whedon** [comment]
OK, @cbrueffer is now a reviewer

**Comment by usethedata** [comment]
@khinsen 👋   Pinging on this issue.  Are you able to review this paper for JOSS?

**Comment by khinsen** [comment]
@usethedata Yes, I can review this submission. Sorry for not reacting earlier, but GitHub notified me only today of being mentioned in this thread.

**Comment by usethedata** [comment]
@whedon add @khinsen as reviewer

**Comment by whedon** [comment]
OK, @khinsen is now a reviewer

**Comment by usethedata** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2284.
