### ISSUE TITLE
[PRE REVIEW]: Hypothesize: Robust Statistics for Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2193]
**Submitting author:** @Alcampopiano (<a href="http://orcid.org/0000-0002-3280-4447">Allan Campopiano</a>)
**Repository:** <a href="https://github.com/Alcampopiano/hypothesize" target ="_blank">https://github.com/Alcampopiano/hypothesize</a>
**Version:** v1.0.0
**Editor:** @csoneson
**Reviewers:** @martinagvilas, @arbennett
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Alcampopiano. **Currently, there isn't an JOSS editor assigned** to your paper.

@Alcampopiano if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

-  10.25080/Majora-92bf1922-00a  is OK

MISSING DOIs

- https://doi.org/10.1037/0003-066x.53.3.300 may be missing for title: How many discoveries have been lost by ignoring modern statistical methods?
- https://doi.org/10.1016/c2010-0-67044-1 may be missing for title: Introduction to robust estimation and hypothesis testing

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02193/joss.02193/10.21105.joss.02193.pdf)

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.28 s (172.3 files/s, 30676.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          11           1362           1293           3446
Markdown                         9            933              0           1509
YAML                             2              9              4             69
TeX                              1              5              0             46
CSS                              1              3              0             19
Jupyter Notebook                25              0             25              0
-------------------------------------------------------------------------------
SUM:                            49           2312           1322           5089
-------------------------------------------------------------------------------


Statistical information for the repository '2193' was gathered on 2020/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Allan Campopiano                11          2024            153           23.55
alcampopiano                    57          5649           1419           76.45

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Allan Campopiano           1749           86.4          2.0                2.69
alcampopiano               4352           77.0          0.8                3.81
```

**Comment by Alcampopiano** [comment]
Thank you very much for providing a the list of potential reviewers. Starting from the bottom of that list, I have chosen the following reviewers based on their fields and programming language(s):

kirstensgithub
martinagvilas
alanfairless

I can continue to suggest more if needed.

**Comment by Alcampopiano** [comment]
@whedon check references

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

-  10.1037/0003-066X.53.3.300  is OK
-  10.1016/c2010-0-67044-1  is OK
-  10.25080/Majora-92bf1922-00a  is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
:wave: @csoneson - could you edit this one for us? I'll go ahead and assign this to you now - please let me know if this is a problem.

**Comment by arfon** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02193/joss.02193/10.21105.joss.02193.pdf)

**Comment by csoneson** [comment]
👋@Alcampopiano - I will handle your submission and start by inviting reviewers. 
Going through your paper, I think it would be useful to include a brief comparison of `Hypothesize` to other (potential) Python packages implementing similar functionality. Could you add a statement about that?

**Comment by csoneson** [comment]
👋 @arbennett, @kirstensgithub, @martinagvilas - would you be interested in reviewing this submission for JOSS? 

> Hypothesize: Robust Statistics for Python

software: https://github.com/Alcampopiano/hypothesize
accompanying paper: https://github.com/openjournals/joss-papers/blob/joss.02193/joss.02193/10.21105.joss.02193.pdf

**Comment by Alcampopiano** [comment]
> I think it would be useful to include a brief comparison of `Hypothesize` to other (potential) Python packages implementing similar functionality. Could you add a statement about that?

@csoneson Absolutely. I will add a statement to that effect.

**Comment by martinagvilas** [comment]
@csoneson @Alcampopiano I would be glad to review this submission

**Comment by arbennett** [comment]
@csoneson @Alcampopiano - Sure, I'd be happy to review this!

**Comment by Alcampopiano** [comment]
Hello @csoneson,

As you have requested, I have added the following statements (and related references) regarding other useful Python libraries that offer methods for robust statistics:

> While other statistical libraries in Python provide useful options 
for robust model fitting [@seabold2010statsmodels] and visualizations [@ho2019moving], 
Hypothesize focuses on providing a larger selection of robust methods 
for comparing groups and measuring associations, especially those that are 
analogous to traditional NHST approaches.

@whedon generate pdf

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
@Alcampopiano - commands to Whedon need to be in standalone comments ☝️

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02193/joss.02193/10.21105.joss.02193.pdf)

**Comment by csoneson** [comment]
@martinagvilas, @arbennett - brilliant, thank you for your quick replies. Since we now have two reviewers I'm going to start the actual review issue, where you will find your checklists and more details on the process.

**Comment by csoneson** [comment]
@whedon assign @martinagvilas as reviewer

**Comment by whedon** [comment]
OK, @martinagvilas is now a reviewer

**Comment by csoneson** [comment]
@whedon add @arbennett as reviewer

**Comment by whedon** [comment]
OK, @arbennett is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2241.
