### ISSUE TITLE
[PRE REVIEW]: datafold: data-driven models for point clouds and time series on manifolds

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2194]
**Submitting author:** @eldan101 (<a href="http://orcid.org/0000-0002-4012-5014">Daniel Lehmberg</a>)
**Repository:** <a href="https://gitlab.com/datafold-dev/datafold/" target ="_blank">https://gitlab.com/datafold-dev/datafold/</a>
**Version:** v1.0.0
**Editor:** @dfm
**Reviewers:** @jsgalan, @mtezzele
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @eldan101. **Currently, there isn't an JOSS editor assigned** to your paper.

@eldan101 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.33 s (246.0 files/s, 74848.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          54           4655           5029          10842
Jupyter Notebook                 9              0           1990            860
TeX                              2             43              0            614
reStructuredText                 7            143            106            394
YAML                             2             11              1             76
Markdown                         2             31              0             61
DOS Batch                        1              8              1             26
TOML                             1              0              0             15
Bourne Shell                     1              5              7             12
make                             1              4              7              9
INI                              1              0              0              3
SVG                              1              0              0              1
-------------------------------------------------------------------------------
SUM:                            82           4900           7141          12913
-------------------------------------------------------------------------------


Statistical information for the repository '2194' was gathered on 2020/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel Lehmberg                211         62657          34152           99.82
Felix Dietrich                   5           154             18            0.18

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Daniel Lehmberg           20407           32.6          1.9                8.87
Felix Dietrich              119           77.3          0.5                2.52
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.expthermflusci.2017.06.011 is OK
- 10.1016/j.acha.2017.09.001 is OK
- 10.1137/18M1188227 is OK
- 10.3934/jcd.2014.1.391 is OK
- 10.1007/s00332-015-9258-5 is OK
- 10.1137/1.9781611972825.17 is OK
- 10.1016/j.acha.2005.07.005 is OK
- 10.1016/j.acha.2006.04.006 is OK
- 10.1162/0899766041732396 is OK
- 10.1017/S0022112010001217 is OK
- 10.1162/089976603321780317 is OK
- 10.1073/pnas.1031596100 is OK
- 10.1073/pnas.1517384113 is OK
- 10.3390/pr2010112 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02194/joss.02194/10.21105.joss.02194.pdf)

**Comment by kthyng** [comment]
Hi @dfm! What do you think about editing this submission?

**Comment by dfm** [comment]
@kthyng: I'd be happy to edit this submission!

**Comment by dfm** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by dfm** [comment]
@elDan101: Can you take a look at [this list](https://bit.ly/joss-reviewers) and let me know if you see anyone who would be a particularly good fit as a reviewer. I'll start looking for reviewers soon!

**Comment by elDan101** [comment]
Hello @dfm, 
Thank you for starting the review process. Based on similar projects reviewed in JOSS I can suggest

@jkmacc-LANL (PyDMD) and @sixpearls (PySINDy) 

as reviewers. I also had a look at the list, and

@EduPH @jsgalan @ixjlyons 

may also be a good match. Thanks again.

**Comment by jsgalan** [comment]
Hi guys, I am available to review. 

Let me know your decision.

Best

**Comment by mtezzele** [comment]
Hi! I am available too for the review. Let me know.

**Comment by dfm** [comment]
@jsgalan, @mtezzele: Thanks for your responses! I'll add you both as reviewers and we'll get the review started.

**Comment by dfm** [comment]
@whedon assign @jsgalan as reviewer

**Comment by whedon** [comment]
OK, @jsgalan is now a reviewer

**Comment by dfm** [comment]
@whedon add @mtezzele as reviewer

**Comment by whedon** [comment]
OK, @mtezzele is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2283.

**Comment by dfm** [comment]
@mtezzele, @jsgalan, @elDan101: let's head over to #2283 to start the review. Thanks all!
