### ISSUE TITLE
[PRE REVIEW]: DORiE: A discontinuous Galerkin solver for soil water flow and passive solute transport based on DUNE

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2195]
**Submitting author:** @peanutfun (<a href="http://orcid.org/0000-0002-4667-3652">Lukas Riedel</a>)
**Repository:** <a href="https://ts-gitlab.iup.uni-heidelberg.de/dorie/dorie" target ="_blank">https://ts-gitlab.iup.uni-heidelberg.de/dorie/dorie</a>
**Version:** v2.0
**Editor:** @meg-simula
**Reviewers:** @gassmoeller, @pratikvn
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @peanutfun. **Currently, there isn't an JOSS editor assigned** to your paper.

@peanutfun if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2195 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.46 s (599.1 files/s, 82286.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                    96           3132           6419          12302
C++                             23            705            436           3392
Python                          51            612            653           1949
reStructuredText                22            813            714           1616
XML                              5            148             16           1014
Markdown                        17            359              0           1009
CMake                           37            178            363            806
YAML                            19             71             34            675
GLSL                             4              0            143            139
CSS                              1             12              0             62
-------------------------------------------------------------------------------
SUM:                           275           6030           8778          22964
-------------------------------------------------------------------------------


Statistical information for the repository '2195' was gathered on 2020/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Dion Häfner                     44         21870          10746           17.28
Lukas Riedel                   446         33015          29191           32.96
Santiago                       122          7213           8655            8.41
Santiago Ospina                257         39854          27048           35.45
Santiago Ospina De L             8           258            304            0.30
Santiago Ospina De L            71          5378           5199            5.60

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Dion Häfner                3503           16.0         20.9               16.27
Lukas Riedel              11796           35.7         14.9               20.63
Santiago                   1156           16.0         15.8               15.22
Santiago Ospina           11141           28.0         15.7               16.85
Santiago Ospina De L       1985           36.9         13.4               26.50
```

**Comment by kthyng** [comment]
Hi @peanutfun! Do you have a JOSS paper somewhere in your repo, or maybe another repo? Our bot can't find it.

**Comment by kthyng** [comment]
Hi @meg-simula! Would you be able to edit this submission?

**Comment by meg-simula** [comment]
Yes, can do. (But public holiday here until Monday, will follow up then.)

**Comment by danielskatz** [comment]
@whedon assign @meg-simula as editor

**Comment by whedon** [comment]
OK, the editor is @meg-simula

**Comment by peanutfun** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02195/joss.02195/10.21105.joss.02195.pdf)

**Comment by peanutfun** [comment]
Hello everybody and thanks for having us! The paper is located in the [`joss-paper`](https://ts-gitlab.iup.uni-heidelberg.de/dorie/dorie/-/merge_requests/198) branch of the repository in order to quickly update it during the review process. I just had it compiled from there.

**Comment by peanutfun** [comment]
As potential reviewers and I would like to suggest [`rreinecke`](https://github.com/rreinecke), [`mikaem`](https://github.com/mikaem), [`gassmoeller`](https://github.com/gassmoeller), [`dvalters`](https://github.com/dvalters), and [`pratikvn`](https://github.com/pratikvn)

**Comment by meg-simula** [comment]
Thank you for the submission @peanutfun, I look forward to taking a closer look at DORiE. List of potential reviewers also much appreciated. 

Before we move this along, please note that the JOSS guidelines stipulate a paper length of 250-1000 words:

https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

As far as I can tell, the current DORiE paper is substantially longer than this. Could you please revise? Perhaps some of the text could enter in the DORiE documentation?

**Comment by peanutfun** [comment]
Hi @meg-simula! 👋 You are correct. Excluding formulae, the current manuscript comprises some 3000 words, with ca. 1300 words in the longest section "Discontinuous Galerkin Discretization".

To the best of our knowledge, applying the described discretization method to the physical problem and providing the software implementing it is a novelty. We therefore included the mentioned section in the paper, as potential readers might have a strong interest not only in the software, but also the numerical methods. Currently, the documentation is hosted online but in general, users will have to build it locally after a lengthy installation process which might be a major hurdle to some (see [README.md#manual-installation](https://ts-gitlab.iup.uni-heidelberg.de/dorie/dorie#manual-installation)). Additionally, the paper will potentially receive a more thorough review than the documentation. We thus would still prefer keeping this section in the paper. However, we could declare it an "Appendix" section of the paper and move it to its end, if that is possible.

Apart from this section, I see few opportunities for shortening the paper substantially:

- Dropping "Summary" would leave readers without overview of the software and the paper.
- Removing "Physics of Simulated Processes" might leave non-specialists wondering what the software actually computes.
- "Research and Use Cases" demonstrates that the software is operational and has been applied successfully.
- Each of the "Showcases" demonstrates a major feature of the software.

What do you think? Would exceeding the word limit be acceptable in our case?

**Comment by meg-simula** [comment]
I completely understand your reasoning @peanutfun. If the discretization is novel, I would suggest that you consider submitting a manuscript describing those bits (and perhaps other material) to a suitable venue. JOSS papers are only expected to contain a limited set of metadata (see example below), a Statement of Need, Summary, Acknowledgements, and References sections. You can look at an example accepted paper at the aforementioned link.

**Comment by peanutfun** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02195/joss.02195/10.21105.joss.02195.pdf)

**Comment by peanutfun** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02195/joss.02195/10.21105.joss.02195.pdf)

**Comment by peanutfun** [comment]
Fair enough, @meg-simula! We were hoping to put all this information on the software in one publication, but I understand that the numerics exceed the scope of a JOSS paper.

We drastically pruned the originally submitted paper to a word count of 1090, including the figure captions (see the latest version compiled by @whedon). The paper now contains a summary, a background section giving the statement of need, a feature overview, a section on past research, a shortened showcase section and acknowledgements.

Also, sorry for the noise in this thread! I had @whedon compile the latest version and immediately noticed a typo 🙈

**Comment by meg-simula** [comment]
Great, thanks @peanutfun. This looks very much ready for review. I'll reach out to reviewers and get back to you.

**Comment by meg-simula** [comment]
@rreinecke, @mikaem, @gassmoeller, @dvalters, @pratikvn @: Would you like to review this submission for JOSS? Feel free to take a look at our reviewer guidelines here: 

https://joss.readthedocs.io/en/latest/reviewer_guidelines.html .

**Comment by gassmoeller** [comment]
@meg-simula I am happy to review this paper. Review should happen within the next few weeks.

**Comment by pratikvn** [comment]
@meg-simula , I am happy to review this paper.

**Comment by meg-simula** [comment]
@pratikvn @gassmoeller Excellent! I'll start the review issue. Let's move the discussion over there.

**Comment by meg-simula** [comment]
@whedon assign @reviewer as reviewer

**Comment by whedon** [comment]
OK, @reviewer is now a reviewer

**Comment by meg-simula** [comment]
@whedon assign @gassmoeller as reviewer

**Comment by whedon** [comment]
OK, @gassmoeller is now a reviewer

**Comment by meg-simula** [comment]
@whedon add @pratikvn as reviewer

**Comment by whedon** [comment]
OK, @pratikvn is now a reviewer

**Comment by meg-simula** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2313.
