### ISSUE TITLE
[PRE REVIEW]: PySWMM: The Python Interface to Stormwater Management Model (SWMM)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2196]
**Submitting author:** @katmratliff (<a href="http://orcid.org/0000-0003-1410-2756">Katherine Ratliff</a>)
**Repository:** <a href="https://github.com/OpenWaterAnalytics/pyswmm" target ="_blank">https://github.com/OpenWaterAnalytics/pyswmm</a>
**Version:** v0.6.1
**Editor:** @kbarnhart
**Reviewers:** @nickrsan, @jrkasprzyk, @dickinsonre
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @katmratliff. **Currently, there isn't an JOSS editor assigned** to your paper.

@katmratliff if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.25 s (304.3 files/s, 56539.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          35           1890           4571           4437
C                                3            290            331            881
reStructuredText                27            264            286            402
Markdown                         5            174              0            276
C/C++ Header                     2             48             50            160
TeX                              1             11              0            101
YAML                             3             15             26             65
Bourne Shell                     1              3              6             22
-------------------------------------------------------------------------------
SUM:                            77           2695           5270           6344
-------------------------------------------------------------------------------


Statistical information for the repository '2196' was gathered on 2020/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Abhi                             1            85              0            0.24
Abhiram                          1            68             33            0.28
Bryant E. McDonnell            195         12751           6184           53.04
Bryant McDonnell                 4           505            217            2.02
Christian Urich                  1             1              1            0.01
Damon McDougall                  5            13             13            0.07
Gonzalo Pena-Castell            28          4660           1833           18.19
James Westover                   2           173              4            0.50
Jenn Wu                         53           887            851            4.87
Jiada                            1             2              2            0.01
Katherine Ratliff               32           825            344            3.27
Michael Tryby                    2           244            246            1.37
Stephen Roberts                  8            49             13            0.17
jennwuu                         10          4000           1698           15.96

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Abhi                         84           98.8         28.7               20.24
Bryant E. McDonnell        5911           46.4         32.2               13.01
Christian Urich               1          100.0         16.9                0.00
Damon McDougall               4           30.8         18.3                0.00
Gonzalo Pena-Castell       3508           75.3         36.4               19.13
Jenn Wu                     437           49.3          7.6               10.07
Jiada                         2          100.0         20.1                0.00
Katherine Ratliff           668           81.0         13.7                8.23
Michael Tryby                 1            0.4         69.6                0.00
Stephen Roberts              39           79.6         33.3               12.82
jennwuu                    2003           50.1         16.9               12.73
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3390/w8060259 is OK
- 10.1016/j.proeng.2014.11.503 is OK
- 10.1016/j.envsoft.2016.05.009 is OK

MISSING DOIs

- https://doi.org/10.1061/9780784482360.006 may be missing for title: Exploring the Potential for Simulating System-Level Controlled Smart Stormwater System
- https://doi.org/10.1061/jswbay.0000817 may be missing for title: Storm Water Management Model: Performance Review and Gap Analysis
- https://doi.org/10.1080/1573062x.2019.1611889 may be missing for title: swmmr - an R package to interface SWMM

INVALID DOIs

- https://doi.org/10.1016/j.envsoft.2018.12.004 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02196/joss.02196/10.21105.joss.02196.pdf)

**Comment by kthyng** [comment]
Hi @kbarnhart! Are you able to edit this submission?

**Comment by kbarnhart** [comment]
@kthyng I can edit this.

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by katmratliff** [comment]
Recommended reviewers:
Delcan Valters (dvalters)
Kel Markert (KMarkert)
Andrew Bennett (arbennett)

**Comment by kbarnhart** [comment]
:wave: @KMarkert @arbennet @dleutnant @ZhenduoZhu, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html 

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. 

The submission is about the [pySWMM](https://github.com/OpenWaterAnalytics/pyswmm) package which provides a Python interface to the Stormwater Management Model (SWMM). I'm reaching out to you based on your experience with python, surface water, and/or SWMM. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart"). 

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?highlight=conflict%20of%20interest#joss-conflict-of-interest-policy) before the review process starts. 

If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by kbarnhart** [comment]
👋 @KMarkert @arbennet @dleutnant @ZhenduoZhu a quick ping to see if you would be interested in reviewing this submission for JOSS.

**Comment by katmratliff** [comment]
Some additional reviewer suggestions if needed are (no @'s) jrkasprzyk, julianneq, and nickrsan. They all have experience working with water systems and python.

**Comment by katmratliff** [comment]
Also recommending @ dickinsonre

**Comment by kbarnhart** [comment]
👋 @jrkasprzyk @julianneq @nickrsan @dickinsonre, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. 

The submission is about the [pySWMM](https://github.com/OpenWaterAnalytics/pyswmm) package which provides a Python interface to the Stormwater Management Model (SWMM). I'm reaching out to you based on your experience with python, surface water, and/or SWMM. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart"). 

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?highlight=conflict%20of%20interest#joss-conflict-of-interest-policy) before the review process starts. 

If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by nickrsan** [comment]
Sure, I'd be happy to - I'd been meaning to volunteer to review for JOSS, but don't think I ever submitted the form, so very timely. My expertise isn't in stormwater - I do work in water systems as katmratliff mentioned though. From the review checklist, it seems like that's not a major issue though?

**Comment by jrkasprzyk** [comment]
I’d be happy to, too!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dickinsonre** [comment]
I also would be happy to be a reviewer for the PySWMM article.

**Comment by julianneq** [comment]
@kbarnhart I recommend @jsadler2 as a reviewer, as I think his expertise is more relevant than mine (see https://www.sciencedirect.com/science/article/pii/S1364815218312325)

**Comment by dleutnant** [comment]
If there are still reviewers required, I'd be happy to review the article. However, I wouldn't be surprised or disappointed if the expertise already involved is sufficient.

**Comment by kbarnhart** [comment]
@nickrsan @jrkasprzyk @dickinsonre thanks for your willingness to review. I'll move forward with assigning you as reviewers and moving this submission from pre-review to review. 

@julianneq, thanks for your response and your recommendation. 

@dleutnant, thanks for your willingness to review.

**Comment by kbarnhart** [comment]
@whedon add @nickrsan as reviewer

**Comment by whedon** [comment]
OK, @nickrsan is now a reviewer

**Comment by kbarnhart** [comment]
@whedon add @jrkasprzyk as reviewer

**Comment by whedon** [comment]
OK, @jrkasprzyk is now a reviewer

**Comment by kbarnhart** [comment]
@whedon add @dickinsonre as reviewer

**Comment by whedon** [comment]
OK, @dickinsonre is now a reviewer

**Comment by kbarnhart** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2292.
