### ISSUE TITLE
[PRE REVIEW]: cmstatr: An R Package for Statistical Analysis of Composite Material Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2198]
**Submitting author:** @kloppen (<a href="http://orcid.org/0000-0002-1908-5214">Stefan Kloppenborg</a>)
**Repository:** <a href="https://github.com/ComtekAdvancedStructures/cmstatr" target ="_blank">https://github.com/ComtekAdvancedStructures/cmstatr</a>
**Version:** 0.5.2
**Editor:** @usethedata
**Reviewers:** @myousefi2016, @JonasMoss
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kloppen. **Currently, there isn't an JOSS editor assigned** to your paper.

@kloppen if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.15 s (340.6 files/s, 83070.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               31            757           1823           5511
SVG                              4              1              1           2023
Markdown                         4             78              0            360
XML                              1              0             10            343
Rmd                              5            202            669            302
YAML                             4             35              6            172
TeX                              1              1              0            100
JSON                             1              0              0             45
-------------------------------------------------------------------------------
SUM:                            51           1074           2509           8856
-------------------------------------------------------------------------------


Statistical information for the repository '2198' was gathered on 2020/05/21.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.2307/2682297 is OK
- 10.1080/01621459.1987.10478517 is OK
- 10.1080/03610919408813222 is OK
- 10.1198/004017002188618428 is OK
- 10.21105/joss.01686 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02198/joss.02198/10.21105.joss.02198.pdf)

**Comment by kthyng** [comment]
Hi @usethedata! Are you able to edit this submission?

**Comment by usethedata** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by kloppen** [comment]
@usethedata Thanks for volunteering to be the editor for this submission!

I did a cursory search of the reviewers list for people with R as a preferred language and who have listed domains that are somehow related to `cmstatr` and came up with a few names. 
- trallard
- myousefi2016
- njtierney
- JonasMoss

This list is certainly not exhaustive. You must have a fairly good idea of which reviewers would be good for reviewing this submission. I'm sure that whichever people you ask will be excellent choices.

I'm looking forward to the review process and receiving some feedback on the software and documentation.

**Comment by usethedata** [comment]
@kloppen Thank you for the suggestions.  I have reached out via email to a couple of potential reviewers.

**Comment by usethedata** [comment]
@whedon assign @myousefi2016 as reviewer

**Comment by whedon** [comment]
OK, @myousefi2016 is now a reviewer

**Comment by danielskatz** [comment]
@usethedata - you may need to use ```@whedon add ... as reviewer```

**Comment by usethedata** [comment]
@whedon add @JonasMoss as reviewer

**Comment by whedon** [comment]
OK, @JonasMoss is now a reviewer

**Comment by usethedata** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2265.
