### ISSUE TITLE
[REVIEW]: GRUPO: Gauging Research University Publication Output

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#22]
**Submitting author:** @vpnagraj (<a href="http://orcid.org/0000-0003-0060-566X">VP Nagraj</a>)
**Repository:** <a href="https://github.com/vpnagraj/grupo" target ="_blank">https://github.com/vpnagraj/grupo</a>
**Version:** v1.0.0
**Archive:** <a href="http://dx.doi.org/10.6084/m9.figshare.3383653.v1" target ="_blank">https://dx.doi.org/10.6084/m9.figshare.3383653.v1</a>
**Editor:** @arfon 
**Reviewer:** @aespinosa 
## Status

[![status](http://joss.theoj.org/papers/3f833ae46924e1e79582c3715eb38496/status.svg)](http://joss.theoj.org/papers/3f833ae46924e1e79582c3715eb38496)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/3f833ae46924e1e79582c3715eb38496"><img src="http://joss.theoj.org/papers/3f833ae46924e1e79582c3715eb38496/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/3f833ae46924e1e79582c3715eb38496/status.svg)](http://joss.theoj.org/papers/3f833ae46924e1e79582c3715eb38496)
```
### General checks
- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/vpnagraj/grupo">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Archive:** Does the <a target="_blank" href="http://dx.doi.org/10.6084/m9.figshare.3383653.v1">software archive</a> resolve?
### Functionality
- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** Have the performance claims of the software been confirmed?
### Documentation
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
### Software paper

Compiled paper PDF: [10.21105.joss.00022.pdf](https://github.com/openjournals/joss-reviews/files/269280/10.21105.joss.00022.pdf)
- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by aespinosa** [comment]
hi @arfon I'll review this entry.

**Comment by janschulz** [comment]
I've had a short look at the software: it is a one page shiny app where you can chose two US universities and a timerange and the app displays the number of papers in PUBMED.

Regarding `Have the functional claims of the software been confirmed?`: IMO yes, but there is IMO a lot more things to build around the idea of analysing such data than simply choosing a date range and showing a bar plot (e.g. numbers over years).

There are no tests.

**Comment by aespinosa** [comment]
# General Checks

* version - there is no github release or git tag for v1.0.0

# Documetation

* example usage - there's no documented example usage. a screenshot on how to use would be nice
* automated tests - there are none. maybe take a look at Selenium to do basic verification of certain gui elments
* community guidelines - there is no CONTRIBUTING.md file or equivalent

# Software paper

* statement of need - The summary should focus more on the motivation with building the software rather that how it works.

# Reviewer conclusion

I agree with @janschulz that more work to do more work of analyzing the data and have  greater justification on its contribution before being accepted.

**Comment by arfon** [comment]
OK thanks for the input @aespinosa & @janschulz.

@vpnagraj - is sounds like there are a few major things to address before we can move forward with this submission.

**Comment by vpnagraj** [comment]
@arfon @aespinosa @janschulz 

Thank you all for taking the time to review the submission. 

I will take a step back and try to address the issues around functionality / research applications for this software. 

Is there currently a process in place for re-submitting? How long will the paper remain under review?

Thanks again for the feedback.

**Comment by arfon** [comment]
> I will take a step back and try to address the issues around functionality / research applications for this software.

Excellent.

> Is there currently a process in place for re-submitting? How long will the paper remain under review?

We're happy to leave this pending until you've made your improvements to the package. Please comment on this thread when you're ready for a re-review.

**Comment by arfon** [comment]
@vpnagraj - have you had a chance to take a look at making improvements to this submission? Also, if you're not interested in pursuing this submission to JOSS any longer we can withdraw your submission,.

**Comment by vpnagraj** [comment]
@arfon i appreciate the follow up ... i don't have a timeline for the proposed edits, so i think it's best to withdraw the submission

thank you again for the comments and review on this project

**Comment by arfon** [comment]
👍 ok thanks @vpnagraj - I'll go ahead and withdraw the submission on your behalf. Thanks for you interest in JOSS :-)
