### ISSUE TITLE
[PRE REVIEW]: PupillometryR: An R package for preparing and analysing pupillometry data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2200]
**Submitting author:** @samhforbes (<a href="http://orcid.org/0000-0003-1022-4676">Samuel Forbes</a>)
**Repository:** <a href="https://github.com/samhforbes/PupillometryR" target ="_blank">https://github.com/samhforbes/PupillometryR</a>
**Version:** 0.0.2
**Editor:** @oliviaguest
**Reviewers:** @paulinepalma, @Athanasiamo
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @samhforbes. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @oliviaguest.

@samhforbes if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=4.62 s (14.1 files/s, 23859.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                             50              0              0         106758
R                               11            228            683            832
HTML                             1             97              3            682
Markdown                         2            171              0            607
TeX                              1             16              0            171
-------------------------------------------------------------------------------
SUM:                            65            512            686         109050
-------------------------------------------------------------------------------


Statistical information for the repository '2200' was gathered on 2020/05/21.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.12688/wellcomeopenres.15191.1 is OK
- 10.3758/s13428-017-1007-2 is OK
- 10.3758/s13428-018-01190-1 is OK
- 10.31234/osf.io/gvcxb is OK
- 10.1007/978-1-4757-7107-7 is OK
- 10.1111/j.1467-7687.2008.00805.x is OK
- 10.3758/s13428-011-0109-5 is OK
- 10.1177/2331216519832483 is OK
- 10.3758/s13423-018-1432-y is OK
- 10.1177/2331216518800869 is OK
- 10.1126/science.143.3611.1190 is OK
- 10.1037/h0026952 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02200/joss.02200/10.21105.joss.02200.pdf)

**Comment by kthyng** [comment]
Hi @oliviaguest! You were the suggested handling editor for this submission. I'm hoping to get some extra eyes on this submission being in scope given that the number of lines of code shown above is a bit low for a typical submission (being below 1000 for the number of lines of R code).

Given all this, are you able to edit this submission? Thanks!

**Comment by oliviaguest** [comment]
I sure can — lemme know when to move to find reviewers.

**Comment by danielskatz** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by danielskatz** [comment]
> lemme know when to move to find reviewers

Go for it!

**Comment by oliviaguest** [comment]
@whedon add @paulinepalma as reviewer

**Comment by whedon** [comment]
OK, @paulinepalma is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @Athanasiamo as reviewer

**Comment by whedon** [comment]
OK, @Athanasiamo is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2285.

**Comment by oliviaguest** [comment]
Hi all @paulinepalma, @Athanasiamo and @samhforbes — head on over to #2285 to start the review proper. 😊
