### ISSUE TITLE
[PRE REVIEW]: Automated Sleep Stage Scoring Using k-Nearest Neighbors Classifier

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2201]
**Submitting author:** @teamPSG (<a href="http://orcid.org/0000-0001-6360-0714">Tamas Kiss</a>)
**Repository:** <a href="https://github.com/teamPSG/kNN_Sleep_Scorer_kNNSS" target ="_blank">https://github.com/teamPSG/kNN_Sleep_Scorer_kNNSS</a>
**Version:** v1.0.0
**Editor:** @oliviaguest
**Reviewers:** @Emma-k-ward, @sbuergers
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @teamPSG. **Currently, there isn't an JOSS editor assigned** to your paper.

@teamPSG if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2201 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.97 s (17.3 files/s, 4634.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              2              2              2           5151
MATLAB                          25            190           1343           1902
Markdown                         6             75              0            269
TeX                              1             15              0            163
-------------------------------------------------------------------------------
SUM:                            34            282           1345           7485
-------------------------------------------------------------------------------


Statistical information for the repository '2201' was gathered on 2020/05/21.
No commited files with the specified extensions were found.
```

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02201/joss.02201/10.21105.joss.02201.pdf)

**Comment by kthyng** [comment]
Hi again @oliviaguest! Are you able to edit this submission too?

**Comment by oliviaguest** [comment]
Sure thing. 😊

**Comment by arfon** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by teamPSG** [comment]
Hi @oliviaguest! Some help for reviewers: I suggest Bernát Kocsis (bernat_kocsis@hms.harvard.edu, https://sleep.med.harvard.edu/people/faculty/154/Bernat+Kocsis+MD+PhD) and Péter Barthó (peter.bartho@gmail.com, http://www.ttk.hu/en/phonebook/peter-bartho). From your list maybe sappelhoff, TomDonoghue, and ixjlyons. Hope this help. Best, Tamás Kiss (teamPSG)

**Comment by oliviaguest** [comment]
Hi @teamPSG — thank you, this is very useful. I have sent a few emails off, once I get replies (or enough times passes) I'll decide if I should ask any of these people too. Much appreciated. 😊

**Comment by oliviaguest** [comment]
@whedon add @Emma-k-ward as reviewer

**Comment by whedon** [comment]
OK, @Emma-k-ward is now a reviewer

**Comment by oliviaguest** [comment]
@teamPSG I have tried your suggestions and sadly none of them have replied. I'm struggling a bit and have contacted over 10 people. If you have any more suggestions that would definitely help hurry this along.

**Comment by teamPSG** [comment]
Hi @oliviaguest! Previously (like 5+ years ago) I was working with Brian Harvey (brian.harvey@biogen.com) and Liam Scott (liamscott26.2@gmail.com) and we did automated sleep scoring together so they have the expertise to review this software. However, previously we published together so we are not entirely independent. I asked coauthors too, will be back with more names if I receive suggestions. Thanks for contacting me!

**Comment by teamPSG** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02201/joss.02201/10.21105.joss.02201.pdf)

**Comment by teamPSG** [comment]
@oliviaguest I have received suggestions for potential reviewers from one of my coauthors. I hope one of them will take on the review. Please try these contacts: Jack Allocca, Ph.D., Univ Melbourne <giancarlo.allocca@gmail.com>; Giovanna Zoccoli, M.D., Ph.D., Univ Bologna <giovanna.zoccoli@unibo.it>; Richard Stephenson, Ph.D., Univ Toronto <richard.stephenson@utoronto.ca>; Steven Fox, Merck <steven_fox@merck.com>; Zeke Barger, Ph.D. <Zeke@berkeley.edu>. Hope this helps. Best, Tamás

**Comment by teamPSG** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02201/joss.02201/10.21105.joss.02201.pdf)

**Comment by oliviaguest** [comment]
@teamPSG I have emailed a few and will wait for now and then (if required) try more next week. Thank you! 👍

**Comment by oliviaguest** [comment]
@whedon add @sbuergers as reviewer

**Comment by whedon** [comment]
OK, @sbuergers is now a reviewer

**Comment by oliviaguest** [comment]
👋 Hi, @sbuergers and thank you for agreeing to review this. Just sit tight and I will let you all know when we're going to start the review. If you have any questions before then — please let me know. ☺️

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2377.

**Comment by oliviaguest** [comment]
👋  @Emma-k-ward and @sbuergers please head on over to #2377 for the review itself. 😄
