### ISSUE TITLE
[PRE REVIEW]: dfba: Software for efficient simulation of dynamic flux-balance analysis models in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2202]
**Submitting author:** @davidtourigny (<a href="http://orcid.org/0000-0002-3987-8078">David Tourigny</a>)
**Repository:** <a href="https://gitlab.com/davidtourigny/dynamic-fba" target ="_blank">https://gitlab.com/davidtourigny/dynamic-fba</a>
**Version:** v0.1.6
**Editor:** @marcosvital
**Reviewers:** @jdbrunner, @pstjohn, @synchon
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @davidtourigny. **Currently, there isn't an JOSS editor assigned** to your paper.

@davidtourigny if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1038/nbt1094-994 may be missing for title: Metabolic flux balancing: basic concepts, scientific and practical use
- https://doi.org/10.1016/s0006-3495(02)73903-9 may be missing for title: Dynamic flux balance analysis of diauxic growth in Escherichia coli
- https://doi.org/10.1007/s00211-015-0760-3 may be missing for title: Efficient solution of ordinary differential equations with a parametric lexicographic linear program embedded
- https://doi.org/10.1186/s12859-014-0409-8 may be missing for title: DFBAlab: a fast and reliable MATLAB code for dynamic flux balance analysis
- https://doi.org/10.1101/700112 may be missing for title: Community standards to facilitate development and address challenges in metabolic modeling
- https://doi.org/10.1186/1752-0509-7-74 may be missing for title: COBRApy: COnstraints-Based Reconstruction and Analysis for Python
- https://doi.org/10.21105/joss.00139 may be missing for title: Optlang: An algebraic modeling language for mathematical optimization

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=2.30 s (36.0 files/s, 176569.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          29            920           1982           2401
C++                              9            190            348           1090
Markdown                        10            161              0            733
reStructuredText                10            193            140            348
C/C++ Header                     4             59            106            297
Jupyter Notebook                 3              0         396655            168
CMake                            3             33             15            144
make                             3             24             63            129
INI                              1             14              0            106
TeX                              1             13              0            104
Bourne Shell                     4             37             72             48
YAML                             2              4              1             35
DOS Batch                        1              8              1             26
TOML                             1              1              0             13
HTML                             1              0              0              7
Dockerfile                       1              7             14              6
-------------------------------------------------------------------------------
SUM:                            83           1664         399397           5655
-------------------------------------------------------------------------------


Statistical information for the repository '2202' was gathered on 2020/05/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Midnighter                      21          3265            847            0.69
Moritz E. Beber                 17        278060         277320           93.85
carrascomj                      54          3683           2259            1.00
davidtourigny                   73         14869          11461            4.45

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Midnighter                 2798           85.7          6.7               15.80
Moritz E. Beber             656            0.2          7.4               31.86
carrascomj                  940           25.5          1.8               32.77
davidtourigny              2999           20.2          6.9               17.41
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02202/joss.02202/10.21105.joss.02202.pdf)

**Comment by arfon** [comment]
:wave: @marcosvital - would you be able to edit this submission for JOSS?

**Comment by arfon** [comment]
@whedon invite @marcosvital as editor

**Comment by whedon** [comment]
@marcosvital has been invited to edit this submission.

**Comment by marcosvital** [comment]
Yes, I can handle this, @arfon.

**Comment by marcosvital** [comment]
@whedon assign @marcosvital as editor

**Comment by whedon** [comment]
OK, the editor is @marcosvital

**Comment by marcosvital** [comment]
Hi, @davidtourigny, I will be the editor of your submission.

I'll generate a first version of your manuscript proof, so you can start by checking if everything seems to be ok with it (it will be the version used for revision). If you make any changes, you can use the same whedon command I will use below to create a new proof (or just let me know and I'll do it).

At the same time, we can start assigning reviewers for you submission. We usually ask the authors for suggestions, so let me know if you have anyone in mind that could do this - you can paste the github profile of anyone you think that could do it.
You can also check [this list of people](https://bit.ly/joss-reviewers) that have agreed to review for JOSS, and see if any of them may be suitable to review this submission.

**Comment by marcosvital** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02202/joss.02202/10.21105.joss.02202.pdf)

**Comment by marcosvital** [comment]
David, please feel free to tag any of the other authors here on this issue if you want to, ok?

**Comment by davidtourigny** [comment]
Thanks for taking this on @marcosvital and for initial handling @arfon !

The proof looks fine, but perhaps we should still add some DOIs to the citations.

Co-authors are @Midnighter and @carrascomj

**Comment by davidtourigny** [comment]
For review, contributors to the project https://github.com/opencobra/cobrapy would be most suitable. Including but not limited to:

cdiener 

pstjohn

synchon

matthiaskoenig

**Comment by davidtourigny** [comment]
Please be aware that some of these suggested reviewers have had previously corresponded with us about this project (but not directly contributed). I highlight in case of conflict of interest issues.

**Comment by davidtourigny** [comment]
Authors of a related project https://github.com/jdbrunner/surfin_fba would also serve as very appropriate reviewers for this paper: jdbrunner at https://github.com/jdbrunner

**Comment by marcosvital** [comment]
Thank you for the sugestions, @davidtourigny, I'll start to contact some of them. In the meantime, please do add the DOIs when they are available.

**Comment by marcosvital** [comment]
Dear @jdbrunner, @cdiener and @pstjohn 

Would you be willing to review this submission for JOSS?
We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is still a pre-review, once there are enough reviewers, we will move on to a new issue where the review will take place.

Since @davidtourigny warned us that some of you might have corresponded with the authors about this project, I would also ask for you to check [JOSS policy on conflict of interest](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy) in advance. But corresponding without actual collaboration does not violate it.

Finally, if you are not able to review, please let us know if you have recommendations for other reviewers.

**Comment by jdbrunner** [comment]
Hello,

Yes, am I willing to review this paper.

Thank you,
James Brunner

**Comment by davidtourigny** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02202/joss.02202/10.21105.joss.02202.pdf)

**Comment by marcosvital** [comment]
Thank you very much, @jdbrunner. As soon as we have one or two more reviewers, we will move on and start the reviewing process.

@davidtourigny , if you don't mind, I would like to wait a few more days to see if we get some response from @cdiener and @pstjohn, given that many of us are not able to answer quickly during the pandemic.

**Comment by marcosvital** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1038/nbt1094-994 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1038/nbt.1614 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/s0006-3495(02)73903-9 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1007/s00211-015-0760-3 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1186/s12859-014-0409-8 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1101/700112 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1145/1089014.1089020 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1186/1752-0509-7-74 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.21105/joss.00139 is INVALID because of 'https://doi.org/' prefix
```

**Comment by marcosvital** [comment]
Hi, @davidtourigny , as you can see above, the DOIs should be inserted without the 'https://doi.org/'. Just omit that, and they should be recognized correctly.

**Comment by davidtourigny** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/nbt1094-994 is OK
- 10.1038/nbt.1614 is OK
- 10.1007/s00211-015-0760-3 is OK
- 10.1186/s12859-014-0409-8 is OK
- 10.1101/700112 is OK
- 10.1145/1089014.1089020 is OK
- 10.1186/1752-0509-7-74 is OK
- 10.21105/joss.00139 is OK

MISSING DOIs

- None

INVALID DOIs

- s0006-3495(02)73903-9 is INVALID
```

**Comment by davidtourigny** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/nbt1094-994 is OK
- 10.1038/nbt.1614 is OK
- 10.1016/S0006-3495(02)73903-9 is OK
- 10.1007/s00211-015-0760-3 is OK
- 10.1186/s12859-014-0409-8 is OK
- 10.1101/700112 is OK
- 10.1145/1089014.1089020 is OK
- 10.1186/1752-0509-7-74 is OK
- 10.21105/joss.00139 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by davidtourigny** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02202/joss.02202/10.21105.joss.02202.pdf)

**Comment by pstjohn** [comment]
I'm willing to be a reviewer as well. Thanks!

**Comment by marcosvital** [comment]
Thank you very much @pstjohn, we will let you know when we start the reviewing process.

**Comment by marcosvital** [comment]
Dear synchon

Would you be willing to review this submission for JOSS?
We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is still a pre-review, once there are enough reviewers, we will move on to a new issue where the review will take place. Right now we have two confirmed reviewers, so if you accept we'll move on and start the reviewing process.

Since @davidtourigny warned us that some of the suggested reviewers might have corresponded with the authors about this project, I would also ask for you to take a look at JOSS policy on conflict of interest in advance. But corresponding without actual collaboration does not violate it.

Finally, if you are not able to review, please let us know if you have recommendations for other reviewers.

**Comment by marcosvital** [comment]
Dear @synchon

Would you be willing to review this submission for JOSS?
We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is still a pre-review, once there are enough reviewers, we will move on to a new issue where the review will take place. Right now we have two confirmed reviewers, so if you accept we'll move on and start the reviewing process.

Since @davidtourigny warned us that some of the suggested reviewers might have corresponded with the authors about this project, I would also ask for you to take a look at JOSS policy on conflict of interest in advance. But corresponding without actual collaboration does not violate it.

Finally, if you are not able to review, please let us know if you have recommendations for other reviewers.

**Comment by synchon** [comment]
@marcosvital Yeah sure, I'll be happy to review the submission.

**Comment by marcosvital** [comment]
Thank you @synchon!

We now have three reviewers, so we can move on and start the reviewing process. A new issue will be created for this soon.

**Comment by marcosvital** [comment]
@whedon assign @jdbrunner as reviewer

**Comment by whedon** [comment]
OK, @jdbrunner is now a reviewer

**Comment by marcosvital** [comment]
@whedon add @pstjohn as reviewer

**Comment by whedon** [comment]
OK, @pstjohn is now a reviewer

**Comment by marcosvital** [comment]
@whedon add @synchon as reviewer

**Comment by whedon** [comment]
OK, @synchon is now a reviewer

**Comment by marcosvital** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2342.
