### ISSUE TITLE
[PRE REVIEW]: TBFMM: A C++ generic and parallel fast multipole method library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2203]
**Submitting author:** @berenger-eu (<a href="http://orcid.org/0000-0003-0281-9709">Bérenger Bramas</a>)
**Repository:** <a href="https://gitlab.inria.fr/bramas/tbfmm" target ="_blank">https://gitlab.inria.fr/bramas/tbfmm</a>
**Version:** v1.0
**Editor:** @poulson
**Reviewers:** @pitsianis, @Himscipy, @sarats
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @berenger-eu. **Currently, there isn't an JOSS editor assigned** to your paper.

@berenger-eu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.7717/peerj-cs.183 is OK
- 10.1002/cpe.3723 is OK
- 10.1137/130915662 is OK
- 10.1063/1.472369 is OK
- 10.1063/1.468354 is OK
- 10.1063/1.2194548 is OK

MISSING DOIs

- https://doi.org/10.1109/aps.1994.407723 may be missing for title: The fast multipole method for periodic structures
- https://doi.org/10.1109/tpds.2017.2697857 may be missing for title: Bridging the Gap Between OpenMP and Task-Based Runtime Systems for the Fast Multipole Method
- https://doi.org/10.1155/2017/5482468 may be missing for title: Inastemp: A Novel Intrinsics-as-Template Library for Portable SIMD-Vectorization
- https://doi.org/10.4208/cicp.020215.150515sw may be missing for title: PVFMM: A parallel kernel independent FMM for particle and volume potentials
- https://doi.org/10.1016/j.enganabound.2012.07.004 may be missing for title: Fast multipole method applied to Symmetric Galerkin boundary element method for 3D elasticity and fracture problems

INVALID DOIs

- https://doi.org/10.1016/0021-9991(87)90140-9 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.cam.2003.12.011 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02203/joss.02203/10.21105.joss.02203.pdf)

**Comment by arfon** [comment]
:wave: @poulson - would you be able to take on this submission for us?

**Comment by arfon** [comment]
@whedon invite @poulson as editor

**Comment by whedon** [comment]
@poulson has been invited to edit this submission.

**Comment by poulson** [comment]
Hi @arfon -- I should be able to edit this in a couple days if that's ok. I am swamped with volunteering to review a batch of thirty papers for a journalist at the moment.

**Comment by arfon** [comment]
> Hi @arfon -- I should be able to edit this in a couple days if that's ok. I am swamped with volunteering to review a batch of thirty papers for a journalist at the moment.

👍 thanks @poulson. I'll go ahead and assign you now so it's tracked for the EiCs but please pick this up in your own time.

**Comment by arfon** [comment]
@whedon assign @poulson as editor

**Comment by whedon** [comment]
OK, the editor is @poulson

**Comment by berenger-eu** [comment]
As potential reviewers:
- Laura Morgenstern (https://www.fz-juelich.de/SharedDocs/Personen/IAS/JSC/EN/staff/morgenstern_l.html?nn=362224)
- Bartosz Kohnke (https://www.mpibpc.mpg.de/grubmueller/staff/29430)
- Yoshimichi ANDOH (yandoh@chembio.nagoya-u.ac.jp https://scholar.google.com/citations?user=QWQIm4gAAAAJ&hl=en)
- Eike Mueller (https://people.bath.ac.uk/em459/)
- Louis Lagardere (louis.lagardere@upmc.fr)
- Florent Lopez (http://www.numerical.rl.ac.uk/people/f_lopez/)
- Mawussi Zounon (https://mawussi.github.io/)

From the list:
- pratikvn
- Himscipy
- mdelorme
- colbrydi
- davidbeckingsale
- gassmoeller
- casperdcl
- gweodoo
- sarats

**Comment by poulson** [comment]
Thank you, @berenger-eu -- I looked through the profiles in the first set of your suggested potential reviewer list, and it seems Yoshimichi ANDOH would be the most appropriate, as they list interests in Fast Multipole Methods and C++. Eike Mueller also looks relevant given their interest in elliptic partial differential equations and numerical methods.

I have been unable to find a GitHub profile for Yoshimichi despite their name appearing in a few GitHub projects -- do you know if they have one? If not, I can reach out by email.

I believe that Kenneth Ho (@klho) of FLAM [https://github.com/klho/FLAM] would also make a great reviewer. Ken :wave: -- it's been a while, and I hope you are keeping safe right now. Would you happen to have time to help review this submisssion?

**Comment by poulson** [comment]
Along those lines, Nikos (@pitsianis) was/is a reviewer for said fast-multipole like fast linear algebra method implementation. Nikos, would you be willing to help review this submission?

**Comment by pitsianis** [comment]
Certainly. After Thursday though.

**Comment by poulson** [comment]
Thank you, Nikos (@pitsianis)! I will add you now with the understanding that it will be several days before you can circle back.

**Comment by poulson** [comment]
@whedon add @pitsianis as reviewer

**Comment by whedon** [comment]
OK, @pitsianis is now a reviewer

**Comment by klho** [comment]
This looks great -- and thanks for thinking of me! -- but I just am not going to be able to put in the proper time to do this justice. Sorry.

**Comment by berenger-eu** [comment]
@poulson , sorry I was not connected for last 2 weeks (new baby at home). I do not have Yoshimichi Github login. I can ask for it, simply let me know if you need anything from my side. Thanks a lot.

**Comment by poulson** [comment]
Thank you for reaching out to Yoshimichi, @berenger-eu -- that would be very helpful. I will look for other reviewers in the mean time.

**Comment by poulson** [comment]
Hi Himanshu (@Himscipy) :wave: -- Bergenger Bramas has recommended you as a reviewer for this submission on a C++ library for parallel fast multipole methods. Would you be interested in serving as a reviewer?

**Comment by poulson** [comment]
Hi Sarat (@sarats) :wave: -- Berenger Bramas suggested you would be one of the ideal reviewers for this submission on parallel fast multipole methods (written in C++).

Would you happen to have the time to serve as one of the reviewers?

**Comment by Himscipy** [comment]
@poulson thank you for thinking about me..  I will be happy to take the role of reviewer for the submission. Let me know what the planned timelines for the feedback and review to complete. Thank you.

**Comment by poulson** [comment]
@whedon add @Himscipy as reviewer

**Comment by whedon** [comment]
OK, @Himscipy is now a reviewer

**Comment by poulson** [comment]
Thank you for being willing to help review this submission, Himanshu (@Himscipy)!

Ideally we could get your initial review feedback within the next two weeks.

Please feel free to also review the guide for reviewing for JOSS here:
https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by poulson** [comment]
Thank you, @berenger-eu -- I followed up with one of the invited potential reviewers by email and hope to hear back soon. If not, I will dig back through the potential reviewer list to find more possibilities.

**Comment by sarats** [comment]
@poulson Yes, I can review. The Github notification got buried in rest of the noise.

**Comment by poulson** [comment]
@whedon add @sarats as reviewer

**Comment by whedon** [comment]
OK, @sarats is now a reviewer

**Comment by poulson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2444.
