### ISSUE TITLE
[PRE REVIEW]: Analysing 24-hour behaviour sequence data with an Rshiny application

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2204]
**Submitting author:** @jcolomb (<a href="http://orcid.org/0000-0002-3127-5520">Colomb, J.</a>)
**Repository:** <a href="https://github.com/jcolomb/HCS_analysis" target ="_blank">https://github.com/jcolomb/HCS_analysis</a>
**Version:** v0.1.3
**Editor:** @danielskatz
**Reviewers:** @mikerspencer, @aj2duncan
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jcolomb. **Currently, there isn't an JOSS editor assigned** to your paper.

@jcolomb if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2204 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.30 s (64.8 files/s, 16664.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSS                              1              0             14           6844
R                               65           1659           1494           4487
SVG                              1              1              1           3708
HTML                             6            279             18           1426
TeX                              4             31              4            673
Rmd                              3            259            183            243
Markdown                         4            115              0            163
-------------------------------------------------------------------------------
SUM:                            84           2344           1714          17544
-------------------------------------------------------------------------------

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02204/joss.02204/10.21105.joss.02204.pdf)

**Comment by arfon** [comment]
👋 @danielskatz - would you be willing to edit this for JOSS?

**Comment by arfon** [comment]
@whedon invite @danielskatz as editor

**Comment by whedon** [comment]
@danielskatz has been invited to edit this submission.

**Comment by danielskatz** [comment]
@whedon assign me as editor

@arfon - I don't think this will work, but it should

**Comment by danielskatz** [comment]
not even an error...

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @j_colomb - thanks for your submission to JOSS. Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by arfon** [comment]
> @whedon assign me as editor

> @arfon - I don't think this will work, but it should

Agreed. It should!

**Comment by jcolomb** [comment]
looking for R, machine learning, statistics, (and not epidemiology) none found for Rshiny.
(PS would be cool to have a possibility to filter that list, maybe directly from the result of whedon software report ?).

nhejazi
jayrobwilliams
ati-ozgur
rcannood

**Comment by danielskatz** [comment]
We have a bunch of ideas for potential changes in progress to make this process better, and hope to start implementing them soon

**Comment by danielskatz** [comment]
👋 @nhejazi - Would you be willing to review this submission?

**Comment by danielskatz** [comment]
👋 @jayrobwilliams - Would you be willing to review this submission?

**Comment by danielskatz** [comment]
👋 @ati-ozgur - Would you be willing to review this submission?

**Comment by danielskatz** [comment]
👋 @rcannood - Would you be willing to review this submission?

**Comment by jayrobwilliams** [comment]
@danielskatz unfortunately I don't have time to review this submission at the moment.

**Comment by danielskatz** [comment]
👋 @nhejazi, @ati-ozgur, @rcannood - Would you be willing to review this JOSS submission?

**Comment by danielskatz** [comment]
👋 @jcolomb - Can I ask if you might have additional thoughts on potential reviewers?

**Comment by danielskatz** [comment]
👋 @amoeba, @brylie, @DominiqueMakowski, @mikerspencer, @aj2duncan - would one or two of you be willing to review this JOSS submission?

**Comment by DominiqueMakowski** [comment]
Hi @danielskatz, thanks for the invite, unfortunately, I feel like this is really outside my domain. Sorry, and good luck!

**Comment by mikerspencer** [comment]
Yes, I can review this. It's my first piece for this journal, so I may need a little hand-holding.

**Comment by aj2duncan** [comment]
@danielskatz  I'm happy to review this too.

**Comment by danielskatz** [comment]
Thanks to @mikerspencer and @aj2duncan  - we will go ahead with a review in a few minutes (and in a new thread after more commands to whedon).  Mike, please feel free to ask questions as needed, but I hope the fact that the process is checklist-driven will make this reasonably clear and easy.

**Comment by danielskatz** [comment]
@whedon assign @mikerspencer as reviewer

**Comment by whedon** [comment]
OK, @mikerspencer is now a reviewer

**Comment by danielskatz** [comment]
@whedon add @aj2duncan as reviewer

**Comment by whedon** [comment]
OK, @aj2duncan is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2282.
