### ISSUE TITLE
[PRE REVIEW]: mmaqshiny v1.0: R-Shiny package to explore air quality mobile monitoring data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2205]
**Submitting author:** @adithirgis (<a href="http://orcid.org/0000-0002-1764-1379">Adithi Upadhya</a>)
**Repository:** <a href="https://github.com/meenakshi-kushwaha/mmaqshiny" target ="_blank">https://github.com/meenakshi-kushwaha/mmaqshiny</a>
**Version:** v.1.0.0
**Editor:** @arfon
**Reviewers:** @ibarraespinosa, @nistara
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @adithirugis. **Currently, there isn't an JOSS editor assigned** to your paper.

@adithirugis if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.atmosenv.2011.05.028 is OK
- 10.1021/es8021039 is OK
- 10.1016/j.atmosenv.2004.03.007 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=5.01 s (4.8 files/s, 138043.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                            13            312              0         689522
R                                5             84             33           1432
Markdown                         5            128              0            201
TeX                              1              1              0             33
-------------------------------------------------------------------------------
SUM:                            24            525             33         691188
-------------------------------------------------------------------------------


Statistical information for the repository '2205' was gathered on 2020/05/22.
No commited files with the specified extensions were found.
```

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @adithirgis - thanks for your submission to JOSS. Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by adithirgis** [comment]
Hello Arfon,
Thank you!
Here are my suggestions:
- masalmon
- garretrc

Please let me know if I need to suggest more reviewers.


Warm regards and stay safe
Adithi R. Upadhya

**Comment by arfon** [comment]
:wave: @masalmon & @garretrc - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by maelle** [comment]
Sorry, no, I wouldn't have time.

**Comment by arfon** [comment]
> Sorry, no, I wouldn't have time.

OK, no worries. @adithirgis - please suggest a few more potential reviewers if you can.

**Comment by adithirgis** [comment]
Hello!

Here are some more suggestions:
- cdcrabtree
-edonnachie
- mikerspencer
- nistara
- aj2duncan
-ibarraespinosa
- briatte
- cimentadaj
- jhollist



Thank you and stay safe
Warm Regards
Adithi R. Upadhya
ILK Labs

**Comment by arfon** [comment]
:wave: @cimentadaj, @edonnachie, @ibarraespinosa - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by garretrc** [comment]
Sorry, bad time for me right now. Still willing to do reviews in a couple
of months!

**Comment by ibarraespinosa** [comment]
Hello guys, I can do it but I will start by n a couple of daya. Thanks for the invitation

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by arfon** [comment]
@whedon add @ibarraespinosa as reviewer

**Comment by whedon** [comment]
OK, @ibarraespinosa is now a reviewer

**Comment by arfon** [comment]
Thanks for agreeing to review @ibarraespinosa. The review process won't actually start until we've identified a second reviewer, so please sit tight for now!

**Comment by arfon** [comment]
:wave: @aj2duncan @nistara @mikerspencer - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by cimentadaj** [comment]
Thanks for reaching out! I'm afraid I won't have time but feel free to me ping me after June. Thanks!

**Comment by edonnachie** [comment]
Thank you for the opportunity to review this package. At first sight, this is a very interesting project. Unfortunately though, I'm unable to take this on at present. Feel free to contact me for any future review.

**Comment by nistara** [comment]
Thank you for giving me this opportunity. I can review the package, but like @ibarraespinosa I'll need a few more days before I can begin.

**Comment by arfon** [comment]
@whedon add @nistara as reviewer

**Comment by whedon** [comment]
OK, @nistara is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2250.

**Comment by arfon** [comment]
@ibarraespinosa, @nistara - many thanks for agreeing to review this submission - I've noted that it will be a little time before you're both able to start work on this. See you over in #2250 where the actual review will take place.

**Comment by mikerspencer** [comment]
Hi all, apologies for the late response (a dislocated finger has slowed me down).

If you need an extra reviewer I'm happy to be involved.

**Comment by aj2duncan** [comment]
Apologies for my tardiness too, it looks like an interesting submission. Seems like @mikerspencer has you covered for an extra reviewer but if anything changes let me know. Thanks.
