### ISSUE TITLE
[PRE REVIEW]: BrkRaw: A comprehensive tool for accessing raw Bruker Biospin MRI data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2206]
**Submitting author:** @dvm-shlee (<a href="http://orcid.org/0000-0001-5292-0747">Sung-Ho Lee</a>)
**Repository:** <a href="https://github.com/brkraw/bruker" target ="_blank">https://github.com/brkraw/bruker</a>
**Version:** 0.3.3
**Editor:** @richardjgowers
**Reviewers:** @mih, @mwegrzyn, @PeerHerholz
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @dvm-shlee. **Currently, there isn't an JOSS editor assigned** to your paper.

@dvm-shlee if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2206 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.17 s (126.0 files/s, 59349.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          17            508            325           3355
Markdown                         2             30              0            169
TeX                              1              7              0            149
Jupyter Notebook                 1              0           5245            106
-------------------------------------------------------------------------------
SUM:                            21            545           5570           3779
-------------------------------------------------------------------------------


Statistical information for the repository '2206' was gathered on 2020/05/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
SungHo Lee                      50          2384            717           44.72
dvm-shlee                       38          3177            656           55.28

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
SungHo Lee                 4188          175.7          1.7                5.52
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.00354 is OK
- 10.3389/fninf.2013.00045 is OK
- 10.1038/sdata.2016.44 is OK
- 10.5281/zenodo.3745545 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02206/joss.02206/10.21105.joss.02206.pdf)

**Comment by arfon** [comment]
👋 @richardjgowers - would you be able to edit this for JOSS? I realize it's not really in your field but our MRI specialist is completely unavailable to edit currently.

**Comment by arfon** [comment]
@whedon invite @richardjgowers as editor

**Comment by whedon** [comment]
@richardjgowers has been invited to edit this submission.

**Comment by dvm-shlee** [comment]
@arfon Thank you for suggesting the editor! I would like to ask for reviewing this paper to following reviewers, @mih, @mwegrzyn, @peerherholz. Thank you! Please let me know if you have any questions or comments regarding this software. Thanks!

**Comment by richardjgowers** [comment]
@arfon ok sure.  The three suggested reviewers look ok to me too @mih @mwegrzyn @PeerHerholz would you be available to review this paper?

**Comment by richardjgowers** [comment]
@whedon assign @richardjgowers as editor

**Comment by whedon** [comment]
OK, the editor is @richardjgowers

**Comment by mih** [comment]
@richardjgowers I can do that. Thx!

**Comment by mwegrzyn** [comment]
Dear @richardjgowers,

thank you for your message. I would be glad to review the submission.

Best regards,
Martin Wegrzyn

**Comment by PeerHerholz** [comment]
Ahoi hoi folks (@mwegrzyn, @mih and @richardjgowers),

sure thing, happy to review the submission.

Best, Peer

**Comment by richardjgowers** [comment]
@Whedon set @mih as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by richardjgowers** [comment]
@whedon add @mih as reviewer

**Comment by whedon** [comment]
OK, @mih is now a reviewer

**Comment by richardjgowers** [comment]
@Whedon add @mwegrzyn as reviewer

**Comment by whedon** [comment]
OK, @mwegrzyn is now a reviewer

**Comment by richardjgowers** [comment]
@whedon Add @PeerHerholz as reviewer

**Comment by whedon** [comment]
OK, @PeerHerholz is now a reviewer

**Comment by richardjgowers** [comment]
@whedon Start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2277.
