### ISSUE TITLE
[PRE REVIEW]: dantro: a Python package for handling, transforming, and visualizing hierarchically structured data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2207]
**Submitting author:** @blsqr (<a href="http://orcid.org/0000-0003-3858-0904">Yunus Sevinchan</a>)
**Repository:** <a href="https://ts-gitlab.iup.uni-heidelberg.de/utopia/dantro" target ="_blank">https://ts-gitlab.iup.uni-heidelberg.de/utopia/dantro</a>
**Version:** v0.13
**Editor:** @lorenanicole
**Reviewers:** @Chilipp, @mdpiper
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @blsqr. **Currently, there isn't an JOSS editor assigned** to your paper.

@blsqr if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by arfon** [comment]
@whedon generate pdf from branch add-joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch add-joss-paper. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @lorenanicole - would you be willing to edit this for JOSS?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02207/joss.02207/10.21105.joss.02207.pdf)

**Comment by arfon** [comment]
@whedon invite @lorenanicole as editor

**Comment by whedon** [comment]
@lorenanicole has been invited to edit this submission.

**Comment by blsqr** [comment]
Hey everyone 👋 @herdeanu, @jeremiastraub and I are looking forward to the review! :)

Our suggestions for potential reviewers are [`mdpiper`](https://github.com/mdpiper) and [`Chillip`](https://github.com/Chilipp).

**Comment by lorenanicole** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @lorenanicole

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.73 s (194.2 files/s, 46226.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          81           5326           8373          11739
YAML                            20            498            386           2640
reStructuredText                24           1111           1284           1205
Markdown                        14            281              0            677
INI                              1              4              0             19
make                             1              5              8             12
-------------------------------------------------------------------------------
SUM:                           141           7225          10051          16292
-------------------------------------------------------------------------------


Statistical information for the repository '2207' was gathered on 2020/05/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Benjamin Herdeanu               57          2728           1027            5.43
Daniel Lake                      3           476             62            0.78
Jeremias Traub                  16          3338           1248            6.63
Julian Weninger                  4           752            130            1.28
Unai Fischer                     1           195             10            0.30
Yunus Sevinchan                522         39864          19305           85.58

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Benjamin Herdeanu          1136           41.6         14.2               20.33
Daniel Lake                 311           65.3         13.8               19.61
Jeremias Traub             1812           54.3          5.1               15.89
Julian Weninger             415           55.2         13.7               17.35
Unai Fischer                 34           17.4         13.8               29.41
Yunus Sevinchan           21730           54.5         12.3               19.72
```

**Comment by blsqr** [comment]
Thanks, @lorenanicole, for editing our submission! :)

Just checking: Is there some further information you would like us to provide or something else we can do to move to the review process?

**Comment by lorenanicole** [comment]
Thanks for the checkin @blsqr! We'll be moving to confirming your reviewers!

@mdpiper, @CHILLIP - would you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by lorenanicole** [comment]
@blsqr great! Making the edit in line above.

**Comment by Chilipp** [comment]
Hey @lorenanicole, yes, I'd be happy to review this submission!

**Comment by mdpiper** [comment]
@lorenanicole Count me in!

**Comment by blsqr** [comment]
@whedon generate pdf from branch add-joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch add-joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02207/joss.02207/10.21105.joss.02207.pdf)

**Comment by lorenanicole** [comment]
> Hey @lorenanicole, yes, I'd be happy to review this submission!

Great! I'll get you going then!

**Comment by lorenanicole** [comment]
> @lorenanicole Count me in!

Fantastic! @mdpiper let me get you setup!

**Comment by lorenanicole** [comment]
@whedon add @Chilipp as reviewer.

**Comment by whedon** [comment]
OK, @Chilipp is now a reviewer

**Comment by lorenanicole** [comment]
@whedon add @mdpiper as reviewer.

**Comment by whedon** [comment]
OK, @mdpiper is now a reviewer

**Comment by lorenanicole** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2316.

**Comment by lorenanicole** [comment]
> OK, I've started the review over in #2316.

Ok team (@Chilipp @mdpiper  @blsqr) - moving over to #2316 for the actual review!
