### ISSUE TITLE
[PRE REVIEW]: StoSpa2: A C++ software package for stochastic simulations of spatially extended systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2208]
**Submitting author:** @BartoszBartmanski (<a href="http://orcid.org/0000-0002-0495-9150">Bartosz Bartmanski</a>)
**Repository:** <a href="https://github.com/BartoszBartmanski/StoSpa2" target ="_blank">https://github.com/BartoszBartmanski/StoSpa2</a>
**Version:** v2.0.27
**Editor:** @pdebuyl
**Reviewers:** @CFGrote
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @BartoszBartmanski. **Currently, there isn't an JOSS editor assigned** to your paper.

@BartoszBartmanski if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.18 s (247.2 files/s, 119026.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                     8           3287           1366          13960
Markdown                         3             96             10            431
Python                          10            105             72            349
C++                              7             95             26            276
Jupyter Notebook                 1              0            648            259
YAML                             2             38             13            172
TeX                              1              7              0            101
reStructuredText                 3             73             21            101
CMake                            7             32             19             75
Bourne Shell                     2              7              4             26
TOML                             1              0              0              2
-------------------------------------------------------------------------------
SUM:                            45           3740           2179          15752
-------------------------------------------------------------------------------


Statistical information for the repository '2208' was gathered on 2020/05/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
bartosz.bartmanski              41         20987            641          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
bartosz.bartmanski        20346           96.9          0.3                8.75
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1371/journal.pcbi.1004923 is OK
- 10.1063/1.4975167 is OK
- 10.1371/journal.pcbi.1005387 is OK
- 10.1007/s40571-015-0082-3 is OK
- 10.1063/1.4816377 is OK

MISSING DOIs

- https://doi.org/10.1137/070705039 may be missing for title: The reaction-diffusion master equation as an asymptotic approximation of diffusion to a small target

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02208/joss.02208/10.21105.joss.02208.pdf)

**Comment by arfon** [comment]
@whedon invite @drvinceknight as editor

**Comment by whedon** [comment]
@drvinceknight has been invited to edit this submission.

**Comment by danielskatz** [comment]
👋 @drvinceknight - note that this is waiting for your response.

**Comment by danielskatz** [comment]
@whedon invite @drvinceknight as editor

**Comment by whedon** [comment]
@drvinceknight has been invited to edit this submission.

**Comment by pdebuyl** [comment]
If there is no reply from @drvinceknight I can handle this paper.

**Comment by arfon** [comment]
> If there is no reply from @drvinceknight I can handle this paper.

@pdebuyl - feel free to grab this. @drvinceknight has limited availability right now. You can ask Whedon to assign you with `@whedon assign me as editor`

**Comment by pdebuyl** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @pdebuyl

**Comment by pdebuyl** [comment]
@mbkumar could you review the JOSS article StoSpa2 ?

**Comment by pdebuyl** [comment]
@arosen93 could you review the JOSS article StoSpa2 ?

**Comment by pdebuyl** [comment]
@arosen93 thank you for the quick reply :-)

**Comment by pdebuyl** [comment]
@CFGrote could you review the JOSS article StoSpa2 ?

**Comment by pdebuyl** [comment]
@whedon assign @CFGrote as reviewer

**Comment by pdebuyl** [comment]
Thank you @CFGrote , the review will start in another github issue once there are two reviewers.

**Comment by mbkumar** [comment]
Yes. Could you please send me a formal invite for the review?

**Comment by pdebuyl** [comment]
@mbkumar by email? If so, can you give me an email address?

**Comment by mbkumar** [comment]
mbkumar@gmail.com

**Comment by drvinceknight** [comment]
> 👋 @drvinceknight - note that this is waiting for your response.

Apologies, just got to this but I see it's in hand.

**Comment by mbkumar** [comment]
Yes. I can review as 3rd reviewer.

**Comment by pdebuyl** [comment]
Thank you @mbkumar

**Comment by pdebuyl** [comment]
@whedon start review
