### ISSUE TITLE
[PRE REVIEW]: DriveML: An R Package for Driverless Machine Learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2209]
**Submitting author:** @sayanddude (<a href="http://orcid.org/0000-0002-6477-0376">Sayan Putatunda</a>)
**Repository:** <a href="https://github.com/daya6489/DriveML" target ="_blank">https://github.com/daya6489/DriveML</a>
**Version:** v0.1
**Editor:** @dfm
**Reviewers:** @mirca, @pat-s
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @sayanddude. **Currently, there isn't an JOSS editor assigned** to your paper.

@sayanddude if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (420.9 files/s, 79737.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             1            286              2           2551
R                               24            174            554           1460
Rmd                              3            276            400            300
TeX                              1             32              4            254
Markdown                         5             85              0            161
CSS                              1             16              8             67
-------------------------------------------------------------------------------
SUM:                            35            869            968           4793
-------------------------------------------------------------------------------


Statistical information for the repository '2209' was gathered on 2020/05/22.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18637/jss.v077.i01 is OK
- 10.1016/j.orp.2016.09.002 is OK
- 10.18637/jss.v045.i03 is OK
- 10.1145/2347736.2347755 is OK
- doi:10.1088/1742-6596/1207/1/012015 is OK
- 10.1007/978-0-387-21706-2 is OK

MISSING DOIs

- https://doi.org/10.18637/jss.v033.i01 may be missing for title: Regularization Paths for Generalized Linear Models via Coordinate Descent

INVALID DOIs

- https://doi.org/10.21105/joss.01509 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1007/978-981-13-1208-3_1 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02209/joss.02209/10.21105.joss.02209.pdf)

**Comment by arfon** [comment]
:wave: @dfm - would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by sayanddude** [comment]
Hi, updated the paper.bib file in the github repo and re-generating the pdf to resolve the issue of "Invalid DOIs"

**Comment by sayanddude** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02209/joss.02209/10.21105.joss.02209.pdf)

**Comment by sayanddude** [comment]
Hi, please find below my suggestions for potential reviewers:
nhejazi
jsta
robohyun66
road2stat

**Comment by dfm** [comment]
@arfon: I'm happy to edit!

@sayanddude: Thanks for the suggestions. I'll start reaching out to folks shortly.

**Comment by dfm** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by dfm** [comment]
@whedon assign @mirca as reviewer

**Comment by whedon** [comment]
OK, @mirca is now a reviewer

**Comment by dfm** [comment]
@whedon add @pat-s as reviewer

**Comment by whedon** [comment]
OK, @pat-s is now a reviewer

**Comment by dfm** [comment]
Thanks to @pat-s and @mirca for agreeing to review this submission! I'll start the main review now (whedon will create a new issue for that) and we'll head over there for the rest of the process. Thanks again!

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2278.

**Comment by dfm** [comment]
@sayanddude, @mirca, @pat-s: Please head over to #2278 for the review.
