### ISSUE TITLE
[PRE REVIEW]: policytree: Policy learning via doubly robust empirical welfare maximization over trees

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2210]
**Submitting author:** @erikcs (<a href="http://orcid.org/0000-0001-6093-1390">Erik Sverdrup</a>)
**Repository:** <a href="https://github.com/grf-labs/policytree" target ="_blank">https://github.com/grf-labs/policytree</a>
**Version:** v0.9.2
**Editor:** @arfon
**Reviewers:** @nhejazi, @jjharden
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @erikcs. **Currently, there isn't an JOSS editor assigned** to your paper.

@erikcs if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (503.3 files/s, 38405.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               20            165            391            870
C++                              3             37            161            284
Markdown                         5             56              0            147
C/C++ Header                     1             28             20             85
Rmd                              1             38             44             59
YAML                             2              5              0             52
-------------------------------------------------------------------------------
SUM:                            32            329            616           1497
-------------------------------------------------------------------------------


Statistical information for the repository '2210' was gathered on 2020/05/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ayush Kanodia                    2            30             31            7.97
Erik Sverdrup                   11           660             44           92.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ayush Kanodia                28           93.3          0.0               10.71
Erik Sverdrup               587           88.9          0.1               31.86
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2210 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch oss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch oss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02210/joss.02210/10.21105.joss.02210.pdf)

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @erikcs - thanks for your submission to JOSS.

Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by erikcs** [comment]
Thank you, it seems _AvianaGlobal_, _jjharden_, _nhejazi_  (causal inference) and _bblum9_ (statistics and C++) are good candidates.

**Comment by arfon** [comment]
:wave: @bblum9, @nhejazi, @jjharden, @AvianaGlobal - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by nhejazi** [comment]
Sure! Looks very interesting, would be happy to help out by (co-)reviewing

**Comment by arfon** [comment]
@whedon add @nhejazi as reviewer

**Comment by whedon** [comment]
OK, @nhejazi is now a reviewer

**Comment by arfon** [comment]
Great, thanks @nhejazi. The review won't actually start until we've identified a second reviewer so please sit tight for now.

**Comment by jjharden** [comment]
I can review this paper. 

Jeff

**Comment by arfon** [comment]
@whedon add @jjharden as reviewer

**Comment by whedon** [comment]
OK, @jjharden is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2232.

**Comment by arfon** [comment]
@nhejazi, @jjharden - thanks so much for agreeing to review this submission. See you over in #2232 where the actual review will take place.
