### ISSUE TITLE
[PRE REVIEW]: seg1d: A Python package for Automated segmentation of one-dimensional (1D) data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2211]
**Submitting author:** @cadop (<a href="http://orcid.org/0000-0003-3662-7203">Mathew Schwartz</a>)
**Repository:** <a href="https://github.com/cadop/seg1d" target ="_blank">https://github.com/cadop/seg1d</a>
**Version:** 0.1.0
**Editor:** @trallard
**Reviewers:** @AKuederle, @ejhigson
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @cadop. **Currently, there isn't an JOSS editor assigned** to your paper.

@cadop if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.31 s (581.8 files/s, 130673.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSS                              9            353            181           9975
JavaScript                      10           2206           2246           8380
HTML                            40            885              0           6043
LESS                            48            838            961           4524
Python                          36            786           1595           1047
reStructuredText                34            165            140            175
TeX                              1              1              0            137
Markdown                         2             63              0             93
DOS Batch                        1              8              1             26
make                             1             16              9             25
-------------------------------------------------------------------------------
SUM:                           182           5321           5133          30425
-------------------------------------------------------------------------------


Statistical information for the repository '2211' was gathered on 2020/05/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
cadop                           42         36840          20514          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
cadop                     16326           44.3          0.1               16.62
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02211/joss.02211/10.21105.joss.02211.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1137/1.9781611972757.50 may be missing for title: Three myths about dynamic time warping data mining
- https://doi.org/10.1145/2448196.2448199 may be missing for title: Efficient motion retrieval in large motion databases
- https://doi.org/10.1145/2822013.2822039 may be missing for title: Segmenting motion capture data using a qualitative analysis
- https://doi.org/10.1109/tnsre.2013.2291907 may be missing for title: Segmentation and classification of gait cycles
- https://doi.org/10.3390/s16010066 may be missing for title: Gait partitioning methods: A systematic review
- https://doi.org/10.23919/eusipco.2017.8081163 may be missing for title: A robust algorithm for gait cycle segmentation
- https://doi.org/10.1109/tnsre.2019.2907483 may be missing for title: Segmentation of Exercise Repetitions Enabling Real-Time Patient Analysis and Feedback Using a Single Exemplar
- https://doi.org/10.1145/956750.956777 may be missing for title: Indexing multi-dimensional time-series with support for multiple distance measures
- https://doi.org/10.1016/b978-012088469-8.50069-3 may be missing for title: Indexing large human-motion databases
- https://doi.org/10.1145/1081870.1081966 may be missing for title: Fast window correlations over uncooperative time series
- https://doi.org/10.1109/tnsre.2013.2260561 may be missing for title: Accelerometry-based gait analysis and its application to Parkinson’s disease assessment—part 1: detection of stride event
- https://doi.org/10.1109/hic.2016.7797709 may be missing for title: Comparison of kinematic and dynamic sensor modalities and derived features for human motion segmentation
- https://doi.org/10.1371/journal.pone.0211466 may be missing for title: Automatic real-time gait event detection in children using deep neural networks

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
Hi @trallard! Are you able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @trallard  as editor

**Comment by whedon** [comment]
@trallard has been invited to edit this submission.

**Comment by cadop** [comment]
Hello,

From the excel file, I found the following list of people that I think fit as reviewers (I noticed trallard is also invited already, so it seems like a great fit!).

```
trallard
alcantarar
akuederle
cpontonn
abhishektha
lbugnon
ixjlyons
jackbrookes
ejolly
bradyrx
```

**Comment by ejhigson** [comment]
@trallard @cadop @kthyng I would also be happy to review this submission - it is a good fit for my current research interests.

**Comment by trallard** [comment]
@whedon  add @ejhigson as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon add @ejhigson as reviewer

**Comment by arfon** [comment]
Seems like Whedon is having some issues...

**Comment by arfon** [comment]
Ahhh. @trallard - looks like you need to assign yourself first (this is a bug).

**Comment by arfon** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by trallard** [comment]
@whedon add @ejhigson as reviewer

**Comment by whedon** [comment]
OK, @ejhigson is now a reviewer

**Comment by trallard** [comment]
Dear potential reviewers,

On behalf of the JOSS team I would like to ask if any of you's be able to review this JOSS submission:

**Title**:  seg1d: A Python package for Automated segmentation of one-dimensional (1D) data
**Repo**: https://github.com/cadop/seg1d
**Submitting author**: @cadop

@ixjlyons Kenneth, will you be willing to and are able to review this submission?
@alcantarar Ryan, will you be willing to and are able to review this submission?
@akuederle Arne,  will you be willing to and are able to review this submission?
@ lbugnon Leandro,   will you be willing to and are able to review this submission?

We are currently looking for at least one more reviewer to proceed.

**Comment by AKuederle** [comment]
I would be willing to review

**Comment by cadop** [comment]
@trallard  is there anything I should do next?

**Comment by alcantarar** [comment]
Sorry @trallard , I can't commit to reviewing this submission.

**Comment by cadop** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02211/joss.02211/10.21105.joss.02211.pdf)

**Comment by cadop** [comment]
@kthyng Is there a problem with my submission, or any updates on what the next steps are?

**Comment by kthyng** [comment]
Hi @cadop! Your editor is @trallard, so generally you'll want to contact her.

BUT, looking above, I see that you have gotten two reviewers to volunteer, so I'll move this process along.

**Comment by kthyng** [comment]
@whedon add @AKuederle as reviewer

**Comment by whedon** [comment]
OK, @AKuederle is now a reviewer

**Comment by kthyng** [comment]
@whedon remove @ejhigson as reviewer

**Comment by whedon** [comment]
OK, @ejhigson is no longer a reviewer

**Comment by kthyng** [comment]
@whedon add @ejhigson as reviewer

**Comment by whedon** [comment]
OK, @ejhigson is now a reviewer

**Comment by kthyng** [comment]
Ok excellent, now we have exactly two reviewers who are also distinct.

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2404.

**Comment by kthyng** [comment]
@ejhigson and @AKuederle — the review itself now occurs over in #2404 , so please head on over there to start up your review! We're asking for reviews within 6 weeks due to the global pandemic.

**Comment by cadop** [comment]
Thank you @kthyng !
