### ISSUE TITLE
[PRE REVIEW]: Exact sinogram: an analytical approachto the Radon transform of phantoms

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2212]
**Submitting author:** @francescat93 (<a href="http://orcid.org/0000-0002-2544-0913">FRANCESCA TEDESCHI</a>)
**Repository:** <a href="https://github.com/francescat93/Exact_sinogram" target ="_blank">https://github.com/francescat93/Exact_sinogram</a>
**Version:** v0.1.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @francescat93. **Currently, there isn't an JOSS editor assigned** to your paper.

@francescat93 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (171.1 files/s, 36303.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         3             79              0            411
Python                           4            112            195            340
Jupyter Notebook                 2              0            681            165
TeX                              1             16              0            123
-------------------------------------------------------------------------------
SUM:                            10            207            876           1039
-------------------------------------------------------------------------------


Statistical information for the repository '2212' was gathered on 2020/05/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
francescat93                     2           693             62           37.17
martagatto                       1            47             47            4.63
pog87                            3           599            583           58.20

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
francescat93                588           84.8          0.0               12.24
martagatto                   43           91.5          1.1                9.30
pog87                        16            2.7          1.2                0.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2212 with the following error: 

 [WARNING] Could not fetch resource 'JOSSimages/phantom_rectangles.png': replacing image with description
[WARNING] Could not fetch resource 'JOSSimages/analytical_sinograms_rectangles.png': replacing image with description
Error producing PDF.
! Undefined control sequence.
l.443 ...llowing form \[f_{\epsilon}(x,y)\coloneqq

Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.7717/peerj.453 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1063/1.1729798 is OK

MISSING DOIs

- https://doi.org/10.1109/tmi.1986.4307775 may be missing for title: On the determination of functions from their integral values along certain manifolds
- https://doi.org/10.1109/tns.1974.6499235 may be missing for title: The Fourier reconstruction of a head section

INVALID DOIs

- https://doi.org/10.1038/s41592-019-0686-2 is INVALID because of 'https://doi.org/' prefix
```

**Comment by kthyng** [comment]
Hi @francescat93! Thank you for your submission. I have some questions that are based on our [submission requirements and what your paper should contain](https://joss.readthedocs.io/en/latest/submitting.html). 

1. Typically acceptable submissions have at least 1000 lines of code, though this is not always the case. However, given that this submission has less than 1000 lines of code, we would like more information before proceeding. Thinking of the following submission requirement in particular, can you explain why this submission doesn't fit into this category?
> Minor ‘utility’ packages, including ‘thin’ API clients, and single-function packages are not acceptable.
2. Can you explain a statement of need for the work? This should be the first part of your paper.

We have a lot of submissions that have come in since we re-opened, and given the questions I have, I'm going to mark this as paused for now. (This is internal bookkeeping for us)

**Comment by arfon** [comment]
@francescat93  - many thanks for your submission to JOSS. After consulting with the JOSS editorial team, we have deemed that this submission is out of scope and does not meet our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). Specifically, while this package looks useful, it fails into out 'minor utility' category.

Thanks again for your interest in JOSS.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
