### ISSUE TITLE
[PRE REVIEW]: Ginkgo: A high performance numerical linear algebra library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2213]
**Submitting author:** @pratikvn (<a href="http://orcid.org/0000-0002-7961-1159">Pratik Nayak</a>)
**Repository:** <a href="https://github.com/ginkgo-project/ginkgo" target ="_blank">https://github.com/ginkgo-project/ginkgo</a>
**Version:** v1.1.1
**Editor:** @mjsottile
**Reviewers:** @sivaramambikasaran, @adam-m-jcbs, @zeroset
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pratikvn. **Currently, there isn't an JOSS editor assigned** to your paper.

@pratikvn if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2213 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.97 s (742.2 files/s, 145059.3 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
C++                             337          17437          12356          55170
C/C++ Header                    154           6370          12492          16489
CUDA                             54           2057           1961           5628
CMake                           110            293            350           2406
Bourne Shell                     30            239            235           1730
Pascal                           10            242            690           1257
YAML                              5             62             53           1090
Markdown                         10            210              0            940
Perl                              4             76            139            320
XML                               1              5              7            190
Python                            1             23             28             79
CSS                               1              7             19             59
Bourne Again Shell                2              0              0              7
diff                              1              2              6              5
--------------------------------------------------------------------------------
SUM:                            720          27023          28336          85370
--------------------------------------------------------------------------------


Statistical information for the repository '2213' was gathered on 2020/05/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
=                                1             6              6            0.00
Eoli-an                         38          3562            985            1.09
Fritz Goebel                   101          3236            790            0.97
Goran Flegar                   352         50824          23533           17.91
Hartwig Anzt                   100         15867           7662            5.67
Pratik Nayak                   219         37548          20065           13.87
Pratik Nayakpratik.n             2           220            118            0.08
Terry Cojean                   301         49542          29278           18.98
Thomas Grützmacher             207         45911          36774           19.91
Tobias Ribizel                 145         13807           4478            4.40
Yuhsiang M. Tsai               111         18985           7998            6.50
Yuhsiang Tsai                   70          8118           1236            2.25
fritzgoebel                      6            35             18            0.01
keldu                            2             2              2            0.00
keldu.magnus                    18          1679            932            0.63
tcojean                          6           129             80            0.05
yanjen                         124         17765           8932            6.43
yhmtsai                         59          3587           1565            1.24

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
=                             6          100.0         19.7               33.33
Eoli-an                    2476           69.5          4.6               16.68
Fritz Goebel               2380           73.5         10.9                8.36
Goran Flegar              21172           41.7         23.4               20.44
Hartwig Anzt               7784           49.1         21.0                6.89
Pratik Nayak              13027           34.7         11.4               28.86
Terry Cojean              31520           63.6         12.6               33.90
Thomas Grützmacher         8341           18.2         10.3               19.30
Tobias Ribizel            11753           85.1          2.7               21.61
fritzgoebel                  34           97.1          0.3               50.00
keldu                         2          100.0         11.9              100.00
keldu.magnus                606           36.1         12.8               37.13
yanjen                     3564           20.1         22.6               12.18
yhmtsai                   17779          495.7         10.1               14.64
```

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2213 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
Hi @pratikvn! Thanks for your submission. Do you have a JOSS paper somewhere? Our bot can't find it.

**Comment by danielskatz** [comment]
@whedon generate pdf from custom-branch joss-paper

**Comment by kthyng** [comment]
@mjsottile - Are you willing to edit this submission?

**Comment by whedon** [comment]
PDF failed to compile for issue #2213 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
@whedon invite @mjsottile as editor

**Comment by whedon** [comment]
@mjsottile has been invited to edit this submission.

**Comment by pratikvn** [comment]
Yes, you can find the [paper here](https://github.com/ginkgo-project/ginkgo/tree/joss-paper/doc/joss)

**Comment by danielskatz** [comment]
@arfon - the JOSS paper is in doc/joss in branch joss-paper - How do we compile it?

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02213/joss.02213/10.21105.joss.02213.pdf)

**Comment by pratikvn** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02213/joss.02213/10.21105.joss.02213.pdf)

**Comment by mjsottile** [comment]
:+1: @kthyng - I can take this submission.

**Comment by mjsottile** [comment]
@whedon assign @mjsottile as editor

**Comment by whedon** [comment]
OK, the editor is @mjsottile

**Comment by mjsottile** [comment]
:wave: @pratikvn - before I reach out to potential reviewers, I wanted to check to see if you had any people in mind that I should try first?

**Comment by pratikvn** [comment]
Hello @mjsottile . Thank you for editing this submission. Looking at the spreadsheet, I feel that sivaramambikasaran, zeroset or adam-m-jcbs might be suitable.

**Comment by mjsottile** [comment]
:wave: Hi @sivaramambikasaran, @zeroset and @adam-m-jcbs - you were suggested by the author of this submission to JOSS as potential reviewers. Would you be interested in providing a review? If you haven't reviewed for JOSS before, you can see the review criteria here : https://joss.readthedocs.io/en/latest/review_criteria.html

Please let me know if you are interested and I can add you as a reviewer to the submission.

**Comment by sivaramambikasaran** [comment]
> 👋 Hi @sivaramambikasaran, @zeroset and @adam-m-jcbs - you were suggested by the author of this submission to JOSS as potential reviewers. Would you be interested in providing a review? If you haven't reviewed for JOSS before, you can see the review criteria here : https://joss.readthedocs.io/en/latest/review_criteria.html
> 
> Please let me know if you are interested and I can add you as a reviewer to the submission.

Sure. Can review.

**Comment by adam-m-jcbs** [comment]
I am also available to review.

**Comment by zeroset** [comment]
I am happy to review.

**Comment by mjsottile** [comment]
Excellent - thanks all for the fast response.  I'll initiate the review now.

**Comment by mjsottile** [comment]
@whedon assign @sivaramambikasaran as reviewer

**Comment by whedon** [comment]
OK, @sivaramambikasaran is now a reviewer

**Comment by mjsottile** [comment]
@whedon add @adam-m-jcbs as reviewer

**Comment by whedon** [comment]
OK, @adam-m-jcbs is now a reviewer

**Comment by mjsottile** [comment]
@whedon add @zeroset as reviewer

**Comment by whedon** [comment]
OK, @zeroset is now a reviewer

**Comment by mjsottile** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2260.
