### ISSUE TITLE
[REVIEW]: uravu: Making Bayesian modelling easy(er)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2214]
**Submitting author:** @arm61 (<a href="http://orcid.org/0000-0003-3381-5911">Andrew McCluskey</a>)
**Repository:** <a href="https://github.com/arm61/uravu" target ="_blank">https://github.com/arm61/uravu</a>
**Version:** v1.0.0
**Editor:** @dfm
**Reviewer:** @ejhigson, @joshspeagle
**Archive:** <a href="https://doi.org/10.5281/zenodo.3876888" target="_blank">10.5281/zenodo.3876888</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e9047e48bf024589e0765f955b3e4c76/status.svg)](https://joss.theoj.org/papers/e9047e48bf024589e0765f955b3e4c76)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e9047e48bf024589e0765f955b3e4c76"><img src="https://joss.theoj.org/papers/e9047e48bf024589e0765f955b3e4c76/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e9047e48bf024589e0765f955b3e4c76/status.svg)](https://joss.theoj.org/papers/e9047e48bf024589e0765f955b3e4c76)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/arm61/uravu" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ejhigson & @joshspeagle, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @dfm know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/arm61/uravu">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@arm61) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/arm61/uravu">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@arm61) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ejhigson, @joshspeagle it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/s41592-019-0686-2 is OK
- 10.1093/mnras/staa278 is OK
- 10.21105/joss.01864 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.21105/joss.00024 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02214/joss.02214/10.21105.joss.02214.pdf)

**Comment by dfm** [comment]
@ejhigson, @joshspeagle: Thanks again for agreeing to review this submission. You should have access to the checklists above so please take a look when you get a chance. We generally ask that you complete your reviews in about 2 weeks, but we understand that life might not allow that these days so please just let me know if you need much longer or if there's anything I can do to help. The reviewer docs are linked above and that should explain most of the workflow, but I'm here to answer any questions as they come up. Thanks again!

**Comment by arm61** [comment]
Absolute dream team of editor/reviewers here 🤟🏻. 

Thanks all for you time and I can’t wait to hear your thoughts! Excited to make `uravu` the best code it can be.

**Comment by ejhigson** [comment]
Hi @arm61 - this is a really neat piece of software, nice work!

I have a few minor questions about the installation process. Your documentation says:
```
pip install -r requirements.txt
python setup.py build
python setup.py install 
pytest
```
Is there a reason that the separate ```python setup.py build``` step is needed? You could also consider putting the requirements into the ```install_requires``` property in ``setup.py`` to eliminate the first step too. It might be nice to list ``uravu`` on PyPI so it can be easily installed with pip, but this is optional.

I initially got a bunch of the following errors running tests
```
E           AttributeError: module 'scipy.misc' has no attribute 'logsumexp'
```
which turned out to be due to me having an older version of ```dynesty``` (0.9.2) which used an old ```scipy``` function which is no longer included in the latest version of ```scipy```. They were fixed when I upgraded ```dynesty``` (to 1.0.1). I think it would be useful to put a set of minimum versions in your requirements (e.g. dynesty>=1.0.1 or whatever the appropriate version is).

**Comment by ejhigson** [comment]
A minor fix in the documentation - I think the hyperlink to the contributing guidelines in README.md is broken?

**Comment by ejhigson** [comment]
@arm61 please could you explain the contributions of the second author of the paper Tim Snow? I see that on the github repo you seem to be the only person to have contributed code(?)

**Comment by arm61** [comment]
Nice catch @ejhigson, I have now added `dynasty>=1.0.1` to the `requirements.txt` and to the `install_requires` and `setup_requires` of the `setup.py`, this is currently in [PR #5](https://github.com/arm61/uravu/pull/5) and which is now pulled. 

The difference between the readthedocs and `README.md` on Github is that the former is meant to be the general purpose installation while the later is for those interested in a "development" build (I [will mention this](https://github.com/arm61/uravu/issues/6) in the installation guidance for improved clarity). This is also the reason why `pytest`, `matplotlib` and `seaborn` are in the `requirements.txt` and not the `setup.py` (as these modules are only **required** for testing of the [`plotting.py` module](https://github.com/arm61/uravu/blob/421d04ad6a3ee04634adb3bbfd67f081a668c493/uravu/plotting.py#L18) and not really needed for just using the code). 

The logic of the `python setup.py build` is just that when I am doing development work I like to [segment things as much as possible](https://docs.python.org/2/install/#splitting-the-job-up).

I have made [an issue](https://github.com/arm61/uravu/issues/7) for the broken hyperlink in the README.md so will get that sorted ASAP. 

Finally, Tim Snow is my supervisor at Diamond Light Source, while he did not contribute to the code base itself, his contributions in terms of discussion when developing the code and writing the paper were invaluable.

**Comment by ejhigson** [comment]
That's great, thank you very much @arm61! As I understand it Tim Snow's non-code contributions meet the authorship criteria (https://joss.readthedocs.io/en/latest/submitting.html#authorship) so that's all good - thank you for explaining.

Looking at the paper: I think there is a typo in the first sentence: "interface data analysis" -> "interface for data analysis"? Also do you know of any other similar pieces of software that act as data analysis interfaces like ``uravu``? I think it is worth mentioning any alternatives or explicitly stating that there are no other such packages to your knowledge.

**Comment by arm61** [comment]
Thanks for catching that typo @ejhigson (it must have slipped through that particular gap in my brain!). I have resolved this and included a brief discussion of the uniqueness of `uravu` in [PR #11](https://github.com/arm61/uravu/pull/11). 

As is clear from the addition I believe that `uravu` is the only package that offers Bayesian data modelling in such a simple interface. However, I am more than happy to be proved wrong if yourself, @joshspeagle, or @dfm know of any!

**Comment by arm61** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02214/joss.02214/10.21105.joss.02214.pdf)

**Comment by arm61** [comment]
Oops, looks like I missed an `@` symbol from a citation there. Lets try again!

**Comment by arm61** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02214/joss.02214/10.21105.joss.02214.pdf)

**Comment by arm61** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02214/joss.02214/10.21105.joss.02214.pdf)

**Comment by ejhigson** [comment]
Hi @arm61 - thank you very much for your responses!

I had a look over the code and API documentation and most things seemed to be nicely documented, but there are some functions where some of the arguments are missing documentation e.g. ``uravu.sampling.nested_sampling``. Please could you check over this and filling in the gaps? I also just saw a very minor typo in the paper where you are missing a space "matplotlib(Hunter".

I ran all of the getting started and tutorial jupyter notebooks which are nicely written - these all ran perfectly for me.

One other suggestion - I think it may be worth mentioning _dynamic_ nested sampling in the documentation and paper, since ``dynesty`` is nominally a dynamic nested sampling software package and I see you use dynamic nested sampling via the ``dynesty.DynamicNestedSampling`` sampler in ``uravu.sampling.nested_sampling``.

**Comment by arm61** [comment]
Hey @ejhigson, thanks for the additional comments! The benefit of having someone independent look though the code is really necessary for finding things like missing argument docs!

I have improved the docstrings in https://github.com/arm61/uravu/commit/0c143daec8d749994abd8c9adfe5af5261776714. Hopefully I have got them all covered now!

The missing space is dealt with in https://github.com/arm61/uravu/commit/93ccdf5882dbd9b9c149a9f48bf089287cb0b091.

And finally, I totally agree that mentioning `uravu`'s ability to use `dynasty`'s dynamic nested sampling is important. 
- I have added a mention in the paper (and some fresh references) 
- I have mentioned dynamic nested sampling in the nested sampling tutorial
- and I have improved the docstrings for `Relationship.nested_sampling()` and `sampling.nested_sampling()` to mention dynamic nested sampling 

These changes are all in https://github.com/arm61/uravu/commit/b4b2ea51550d6321f7e3df25875cb62f28724943 and https://github.com/arm61/uravu/commit/c8c8b0fd31646ed2e1d8371b20f6fc9ad6bd1e78

Please let me know if you catch anything else, and thanks for the kind words about the tutorial notebooks 😄.

**Comment by arm61** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02214/joss.02214/10.21105.joss.02214.pdf)

**Comment by ejhigson** [comment]
Hi @arm61 - thank you very much for these changes, they all look great to me!

I am satisfied that you have met all the reviewer criteria. Congratulations on a nice paper and an awesome software package!

**Comment by arm61** [comment]
Thanks @ejhigson! Great comments and very constructive 🙂

**Comment by joshspeagle** [comment]
Hi Andrew,

Sorry for the delay in getting to this compared with @ejhigson. I've gone through the paper, code, tutorials, and docs and only have a few small comments on the docs, none of which are a barrier to publication (as indicated by the reviewer checklist above). These are:

- In the docs and tutorials, it would be nice to include a little more description of what's going on under the hood when you call various functions since the user interface is purposely designed to ease many of these subtleties. For instance, `straight_line` and `diff_evo` seem self-explanatory to me personally, but it would be good to highlight those and other options for users whose first interaction with the code (and possibly Bayesian statistics) will be running through the tutorials in `uravu`. You do this in some places in later tutorials but not as much earlier, so it'd be good to homogenize a bit.

- I really love how easy the code makes using user-defined functions!!! However, I don't see a particular tutorial on how those might need to be structured. I could imagine users having questions like: Do they require non-array arguments? Do they allow for additional arguments/keywords to be passed through `uravu`? Can they return an additional `blob`, or does it have to be just the output model? etc. etc. that would be easy to address in some way in the docs.

- Might be good to mention in the docs that `variable_medians` stands in for the modes when running `max_likelihood` but are actually the medians when using MCMC or NS. It might be worth adding a separate summary variable like `variable_map` since sometimes users might want both the median and the mode.

- During the NS tutorial, you have a comparison with the line "We can see that the highest order terms are quite small for the larger degree of polynomial." I don't actually see a direct comparison, however, but only the plot for the single-parameter fit. Did you mean to overplot the four models?

- It might be worth commenting that some of the outputs are piped through `emcee` or `dynesty`, and directing users there to get more information.

The most recent version of the paper is clear and meets all the standards for publishing in JOSS. The code is well-documented and easy to use. Great work on making an excellent package!

**Comment by arm61** [comment]
Hi Josh!

Thanks for the great review and the detailed notes on the docs. Appreciated massively! I have opened them all as issues 😄 

@dfm if you are happy, can we hold off until I get back to 0 issues (probably tomorrow) before moving forward? I would like to have the best possible `1.0.0` build to go along with the paper.

**Comment by dfm** [comment]
@ejhigson, @joshspeagle: Also a big thanks from me for your reviews!!

@arm61: That sounds good. I also want to proofread the paper and do a bit of sanity checking before you tag your release for the publication so hold off on that for now, but let me know when you're satisfied with your responses to these suggestions.

**Comment by arm61** [comment]
Hey @dfm,

Thats me ticked off all of the points @joshspeagle rised. On his second bullet point, unfortunately `uravu` currently only supports **very** simple function definitions (no array args and only simplistic returns). However, I am happy with this functionality for a `1.0.0` build, and will work on adding this additional (quite complex) functionality in the future. 

Please let me know when you are happy with everything and I will mint a `1.0.0` release. 

Thanks again to @ejhigson and @joshspeagle for making the review process of JOSS a pleasure!

**Comment by dfm** [comment]
@whedon check references

**Comment by dfm** [comment]
@arm61: Everything is looking good to me! Can you now bump the version number and generate a new Zenodo release? **The title and author list of the Zenodo release must match the JOSS paper.** You can edit the metadata on the Zenodo page after making the release. Then please report the version number and Zenodo DOI back to this thread. Thanks!

**Comment by arm61** [comment]
Version number: `1.0.0`

I will get the DOI as soon as possible [but zenodo.org is down just now](https://downforeveryoneorjustme.com/zenodo.org) 😱 .

**Comment by arm61** [comment]
Zenodo is back!: `10.5281/zenodo.3876821`

**Comment by dfm** [comment]
I think there's a little typo in the title of your archive :)

**Comment by arm61** [comment]
Too excited!

That's the old release deleted. Version number is still `1.0.0`, doi is now `10.5281/zenodo.3876888`

**Comment by dfm** [comment]
@whedon set v1.0.0 as version

**Comment by whedon** [comment]
OK. v1.0.0 is the version.

**Comment by dfm** [comment]
@whedon set 10.5281/zenodo.3876888 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3876888" target="_blank">10.5281/zenodo.3876888</a> is the archive.

**Comment by dfm** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by dfm** [comment]
@arm61: The Editors-in-chief will take a look and do the final processing. Please take a look at the final proofs and give us a heads up if anything looks wrong to you, but I think we should be in good shape.

@ejhigson, @joshspeagle: Thanks again for your excellent, thorough, and constructive reviews!

**Comment by arm61** [comment]
Thanks again all! Great work and really pleased with how `uravu` has turned out! 

@dfm @joshspeagle @ejhigson

**Comment by kyleniemeyer** [comment]
Hi @arm61, just a few quick edits on the paper:

- I think the semi-colon in the first sentence is not the right punctuation, instead a comma seems more appropriate
- in the first sentence after the bullets, "uravu also add the" should be "uravu also adds the"
- in the Statement of Need paragraph, "to the best of the author's knowledge" should either be "to the best of our knowledge" or "to the best of the authors' knowledge"
- in the emcee citation, please force capitalization of Python and MCMC by surrounding them with curly brackets, e.g., `{Python}`, `{MCMC}`
- same for Python and PyMC3 in the Salvatier 2016 citation

Please let me know when you've made those changes, and I'll get the article published!

**Comment by arm61** [comment]
Hey @kyleniemeyer, 

Thanks for the expert proof reading! Those changes are now in master (https://github.com/arm61/uravu/commit/14ad67ebb099c0e57b7d52ad1fdc7449a0b7b5ee). 

Do I need to generate a new zenodo DOI with these changes?

**Comment by arm61** [comment]
Also if anyone wants an `uravu` sticker, let me know and I will post you some (my email is easy enough to find) 🤘

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02214/joss.02214/10.21105.joss.02214.pdf)

**Comment by kyleniemeyer** [comment]
@arm61 looks good! And no, if the software has not changed, the prior Zenodo archive is fine, since JOSS archives the paper itself.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/s41592-019-0686-2 is OK
- 10.1007/s11222-018-9844-0 is OK
- 10.1063/1.1835238 is OK
- 10.7717/peerj-cs.55 is OK
- 10.1093/mnras/staa278 is OK
- 10.21105/joss.01864 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.21105/joss.00024 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1466

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1466, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1269005318685700103) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1467
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02214](https://doi.org/10.21105/joss.02214)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @arm61 on your article's publication in JOSS!

Many thanks to @ejhigson and @joshspeagle for reviewing this submission, and to @dfm for editing it.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02214/status.svg)](https://doi.org/10.21105/joss.02214)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02214">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02214/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02214/status.svg
   :target: https://doi.org/10.21105/joss.02214
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02214/status.svg)](https://doi.org/10.21105/joss.02214)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by xyluo25** [comment]
Hi @arm61, I hope you’re doing well and enjoying a productive week. I recently submitted the pyufunc paper to JOSS (just yesterday), and I was delighted to see that JOSS recommended you as an ideal reviewer given your expertise. I know how busy schedules can be, so I would be incredibly grateful if you could kindly consider reviewing the manuscript. Your insights and feedback would mean a great deal to me and help ensure pyufunc meets the highest standards.

Please let me know if you have any questions or need additional information. Thank you so much for your time and consideration. I truly appreciate it.
