### ISSUE TITLE
[PRE REVIEW]: PythoFragam: A Python-based Optimization Tool for DNA Fragment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2215]
**Submitting author:** @uzmakhann (<a href="http://orcid.org/0000-0002-3441-7889">uzma khan</a>)
**Repository:** <a href="https://github.com/uzmakhann/A-package-for-optimizing-the-DNA-fragment-assembly" target ="_blank">https://github.com/uzmakhann/A-package-for-optimizing-the-DNA-fragment-assembly</a>
**Version:** Python 3.4+
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @uzmakhann. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @will-rowe.

@uzmakhann if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (423.0 files/s, 28603.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          12            152            176            501
Markdown                         1             20              0             30
-------------------------------------------------------------------------------
SUM:                            13            172            176            531
-------------------------------------------------------------------------------


Statistical information for the repository '2215' was gathered on 2020/05/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Uzma khan                        1           829              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Uzma khan                   829          100.0          0.0               18.46
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #2215 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
Hi @uzmakhann, thanks for your submission! I have a few questions to get started:

1. I don't see a paper accompanying your submission. Please see our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html).
1. We need to have a valid open source license.
1. A typical acceptable submission will have at least 1000 lines of code, but this isn't always the case. Can you make the case for why your submission is [not a](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements):
> Minor ‘utility’ packages, including ‘thin’ API clients, and single-function packages are not acceptable.

**Comment by kthyng** [comment]
We have a lot of submissions that have come in since we re-opened, and given the questions I have, I'm going to mark this as paused for now. (This is internal bookkeeping for us)

**Comment by richardjgowers** [comment]
@uzmakhann I think this project would benefit (and be easier to review) from getting a more typical python package structure, something like this: https://docs.python-guide.org/writing/structure/#structure-of-the-repository

**Comment by arfon** [comment]
@uzmakhann - many thanks for your submission to JOSS. After consulting with the JOSS editorial team, we have deemed that this submission is out of scope and does not meet our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). Specifically, while this package looks useful, it fails into out 'minor utility' category.

Thanks again for your interest in JOSS.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
