### ISSUE TITLE
[PRE REVIEW]: Easy SimAuto (ESA): A Python Package that Simplifies Interacting with PowerWorld Simulator

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2216]
**Submitting author:** @blthayer (<a href="http://orcid.org/0000-0002-6517-1295">Brandon Thayer</a>)
**Repository:** <a href="https://github.com/mzy2240/ESA" target ="_blank">https://github.com/mzy2240/ESA</a>
**Version:** v1.0.2
**Editor:** @danielskatz
**Reviewers:** @robinroche, @tonyelhabr
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @blthayer. **Currently, there isn't an JOSS editor assigned** to your paper.

@blthayer if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.19 s (428.5 files/s, 131548.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       9           2201           2234           8335
HTML                            12            498              0           3869
Python                           9            744           1702           1655
CSS                              4            312             49           1186
reStructuredText                41            483            520            961
Markdown                         3             36              0            238
TeX                              2              8              0             87
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            82           4294           4513          16366
-------------------------------------------------------------------------------


Statistical information for the repository '2216' was gathered on 2020/05/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Brandon Thayer                 118         33082          30086           66.58
CIR Overbye Group                1             4              4            0.01
SmartJingJing123                15           260             59            0.34
mzy2240                         73         16130          15197           33.02
yiji21                           1             7             17            0.03
zeyumao2                         2            20             10            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Brandon Thayer            16196           49.0          1.6               18.72
CIR Overbye Group             2           50.0          2.9                0.00
SmartJingJing123             33           12.7          1.4                9.09
mzy2240                     640            4.0          1.6               16.25
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/DEXA.2012.9 is OK
- 10.1109/TPEC48276.2020.9042493 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02216/joss.02216/10.21105.joss.02216.pdf)

**Comment by arfon** [comment]
:wave: @danielskatz - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @blthayer - thanks for your submission to JOSS. Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

Also, be aware that this might be difficult.  I don't know anything about "PowerWorld Simulator Automation Server (SimAuto)", but if this is something reviewers need to know, need to have, or even just need to install, this will limit the number of people who may be able or willing to review.

**Comment by blthayer** [comment]
@danielskatz - Thank you for volunteering to be our editor!

I've reviewed the list of potential reviewers, and you're right, there don't seem to be too many in the power systems domain. I did find `robinroche` who listed Python as a language of choice, and Power Systems as a domain area.

Myself and my coauthors planned to reach out into our research community to find individuals who have a PowerWorld license and might be interested in reviewing after we made it to this stage. We have reviewed the [ethics guidelines](https://joss.theoj.org/about#ethics) and the [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy) and will ensure our suggested reviewers meet the guidelines/policies.

I'll kick off our search, and report back as soon as possible with potential reviewers.

**Comment by danielskatz** [comment]
sounds good

**Comment by danielskatz** [comment]
👋 @robinroche - Would you be able to review this submission for JOSS?  Given the Covid-19 situation, we are being very flexible on reviewing times

**Comment by robinroche** [comment]
Hi all, yes, having already worked with SimAuto and PowerWorld, I am interested in reviewing this submission.

**Comment by danielskatz** [comment]
Thanks very much.  I'll add you as into the system a reviewer, but we won't actually start until we find another reviewer as well.

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by danielskatz** [comment]
@whedon assign @robinroche as reviewer

**Comment by whedon** [comment]
OK, @robinroche is now a reviewer

**Comment by blthayer** [comment]
@robinroche - thank you very much for your willingness to review! We appreciate it! I'm hoping I'll be able to find another reviewer soon in order to get the process moving.

Just to confirm - do you have access to PowerWorld and SimAuto at this time? Unfortunately, we (the creators of ESA) aren't able to provide licenses to reviewers.

**Comment by robinroche** [comment]
@blthayer - I have access to PWS 17 with SimAuto

**Comment by blthayer** [comment]
@robinroche - thank you for being so responsive. We have primarily done our work/testing with versions 20 and 21, though I know PowerWorld is very dedicated to maintaining backward compatibility in SimAuto.

This is an area we should upgrade ESA's documentation - we have not extensively tested with older versions of PWS/SimAuto. 

I suspect if we run into issues, it'll be related to the `.pwb` cases in our repository being saved in the version 20 or 21 format. I believe that we can use a newer version (e.g. version 21) to save files in the version 17 format, so please let us know if we need to do that.

I'm still waiting on some reviewer leads, but I'm hoping we can get this moving this week. In the meantime, I'll try to find some time this week to install version 17 and do some preliminary tests to preempt PWS version issues.

Thanks again!

**Comment by danielskatz** [comment]
👋 @blthayer - Any progress on suggesting other reviewers?

**Comment by blthayer** [comment]
@danielskatz - thank you for following up.

Progress has been slower than I hoped, but it's possible that `tonyelhabr` may be willing to review. I'll continue emailing folks this week to try to get more possible reviewers.

@robinroche - good news: I was able to get a hold of a PWS 17 copy. ESA required only very minor touch-ups, and we now fully support PWS 17.

Thank you both for your patience as I continue to keep emailing potential reviewers.

**Comment by danielskatz** [comment]
👋 @tonyelhabr - would you be willing to review this submission for JOSS?  We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

In this particular case, you would also need access to PowerWorld and SimAuto.

**Comment by tonyelhabr** [comment]
Yes, I can review the submission.

**Comment by danielskatz** [comment]
Thanks! - just to confirm, you do have access to the required software?

**Comment by tonyelhabr** [comment]
Yes.

**Comment by danielskatz** [comment]
Thanks - I'll add you and start the review then

**Comment by danielskatz** [comment]
@whedon add @tonyelhabr as reviewer

**Comment by whedon** [comment]
OK, @tonyelhabr is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2289.

**Comment by danielskatz** [comment]
👋 @robinroche, @tonyelhabr - we'll continue in #2289
