### ISSUE TITLE
[PRE REVIEW]: BluVision Macro - a software for automated powdery mildew and rust disease quantification on detached leaves.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2217]
**Submitting author:** @snowformatics (<a href="http://orcid.org/0000-0003-0536-835X">Stefanie Lueck</a>)
**Repository:** <a href="https://github.com/snowformatics/macrobot" target ="_blank">https://github.com/snowformatics/macrobot</a>
**Version:** 0.4.6
**Editor:** @mjsottile
**Reviewers:** @SirSharpest, @phckopper, @jizecn
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @snowformatics. **Currently, there isn't an JOSS editor assigned** to your paper.

@snowformatics if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (447.6 files/s, 24694.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          12            251            319            587
reStructuredText                10            117             76            150
TeX                              1             18              0            147
Markdown                         2             38              0             93
XML                              6              0              0             50
HTML                             1             10              0             29
DOS Batch                        1              8              1             26
TOML                             1              4              0             18
make                             1              4              7              9
YAML                             1              6              9              9
-------------------------------------------------------------------------------
SUM:                            36            456            412           1118
-------------------------------------------------------------------------------


Statistical information for the repository '2217' was gathered on 2020/05/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
luecks@gmail.com                40         14438          13281          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
luecks@gmail.com           1157            8.0          0.2               17.20
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1101/2020.03.16.993451 is OK
- 10.7717/peerj.453 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1186/s13059-014-0518-8 is OK
- 10.1080/07060660509507230 is OK
- 10.1038/sj.bjp.0703793 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.neuroscience.2009.01.027 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02217/joss.02217/10.21105.joss.02217.pdf)

**Comment by arfon** [comment]
:wave: @mjsottile - I realize this isn't really in your wheelhouse but any chance you could edit this for us?

**Comment by arfon** [comment]
@whedon invite @mjsottile as editor

**Comment by whedon** [comment]
@mjsottile has been invited to edit this submission.

**Comment by snowformatics** [comment]
Dear all,

I would like to suggest **sirsharpest** as reviewer because he has experience in plant science, phenotyping and computer vision.

Best regards
Stefanie

**Comment by snowformatics** [comment]
> Failed to discover a valid open source license.

I copied the license file in the main directory, hope that's the right place.

**Comment by snowformatics** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1101/2020.03.16.993451 is OK
- 10.7717/peerj.453 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1016/j.neuroscience.2009.01.027 is OK
- 10.1186/s13059-014-0518-8 is OK
- 10.1080/07060660509507230 is OK
- 10.1038/sj.bjp.0703793 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mjsottile** [comment]
:+1: @arfon Sure!  Actually, this is in my area - image processing is one of my research areas and I've worked on problems similar to the one that this submission focuses on.

**Comment by mjsottile** [comment]
@whedon assign @mjsottile as editor

**Comment by whedon** [comment]
OK, the editor is @mjsottile

**Comment by arfon** [comment]
> 👍 @arfon Sure! Actually, this is in my area - image processing is one of my research areas and I've worked on problems similar to the one that this submission focuses on.

Perfect, even better!

**Comment by mjsottile** [comment]
:wave: Hi @sirsharpest, @phckopper and @jizecn - you were suggested by the author of this submission to JOSS as potential reviewers.  Would you be interested in providing a review?   If you haven't reviewed for JOSS before, you can see the review criteria here : https://joss.readthedocs.io/en/latest/review_criteria.html

Please let me know if you are interested and I can add you as a reviewer to the submission.

**Comment by SirSharpest** [comment]
Sure. I'll be happy to review.

**Comment by snowformatics** [comment]
> Sure. I'll be happy to review.

Thanks!

**Comment by phckopper** [comment]
I'll be happy to review it too!

**Comment by jizecn** [comment]
>  Hi @SirSharpest, @phckopper and @jizecn - you were suggested by the author of this submission to JOSS as potential reviewers. Would you be interested in providing a review? If you haven't reviewed for JOSS before, you can see the review criteria here : https://joss.readthedocs.io/en/latest/review_criteria.html
> 
> Please let me know if you are interested and I can add you as a reviewer to the submission.

Sorry for the late response. Yes, I am happy to review too.

**Comment by mjsottile** [comment]
Excellent!  Thanks for the quick responses to the review request.  I'll add everyone and initiate the review process right away.

**Comment by mjsottile** [comment]
@whedon assign @SirSharpest as reviewer

**Comment by whedon** [comment]
OK, @SirSharpest is now a reviewer

**Comment by mjsottile** [comment]
@whedon add @phckopper as reviewer

**Comment by whedon** [comment]
OK, @phckopper is now a reviewer

**Comment by mjsottile** [comment]
@whedon add @jizecn as reviewer

**Comment by whedon** [comment]
OK, @jizecn is now a reviewer

**Comment by mjsottile** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2259.
