### ISSUE TITLE
[PRE REVIEW]: Drug Informatics Studio: An Ontology-based Integrative Research Environment for Clinical Informatics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2218]
**Submitting author:** @jing-su (<a href="http://orcid.org/0000-0003-4917-6173">Jing Su</a>)
**Repository:** <a href="https://github.com/Su-informatics-lab/DIStudio" target ="_blank">https://github.com/Su-informatics-lab/DIStudio</a>
**Version:** v0.1.0
**Editor:** @richardjgowers
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jing-su. **Currently, there isn't an JOSS editor assigned** to your paper.

@jing-su if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (867.6 files/s, 61808.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               20            293            173            812
Markdown                         2             48              0            147
Rmd                              2             49            138             74
TeX                              1              5              0             42
-------------------------------------------------------------------------------
SUM:                            25            395            311           1075
-------------------------------------------------------------------------------


Statistical information for the repository '2218' was gathered on 2020/05/22.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.jalz.2018.06.610 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02218/joss.02218/10.21105.joss.02218.pdf)

**Comment by arfon** [comment]
:wave: @richardjgowers - I realize this isn't really in your wheelhouse but any chance you could edit this for us?

**Comment by arfon** [comment]
@whedon invite @richardjgowers as editor

**Comment by whedon** [comment]
@richardjgowers has been invited to edit this submission.

**Comment by danielskatz** [comment]
@whedon invite @richardjgowers as editor

**Comment by whedon** [comment]
@richardjgowers has been invited to edit this submission.

**Comment by danielskatz** [comment]
👋 @richardjgowers - note that this is waiting for your response.

**Comment by richardjgowers** [comment]
@whedon assign @richardjgowers as editor

**Comment by whedon** [comment]
OK, the editor is @richardjgowers

**Comment by richardjgowers** [comment]
@uth-tuan any chance you would be able to review this?

**Comment by richardjgowers** [comment]
@dombennett would you be available to review this?

**Comment by kthyng** [comment]
@richardjgowers Can you take a look at this submission? It is stale here at the pre-review stage, but should we also query scope? I'm not so familiar with R packages though...

**Comment by arfon** [comment]
@whedon query scope

@kthyng @richardjgowers given the scope and size of this submission I think we should ask the editorial team to review.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
@jing-su After a pre-review of your submission, and an assessment by the editorial board at large, we find that this submission does not quite meet our [submission requirements](http://joss.theoj.org/about#submission_requirements). In particular, while the software seems very useful, it falls under the 'Minor utility/Thin wrapper' category, and we therefore decided not to put it through review. 

Thank you for considering JOSS as a venue for your software, and I hope you'll submit other software with research application in the future. We would also consider this package again in the future if it has significantly expanded in scope.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
