### ISSUE TITLE
[PRE REVIEW]: impedance.py: A Python package for electrochemical impedance analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2219]
**Submitting author:** @mdmurbach (<a href="http://orcid.org/0000-0002-6583-5995">Matthew D. Murbach</a>)
**Repository:** <a href="https://github.com/ECSHackWeek/impedance.py" target ="_blank">https://github.com/ECSHackWeek/impedance.py</a>
**Version:** v1.0.0
**Editor:** @mbobra
**Reviewers:** @ma-sadeghi, @EricaEgg
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mdmurbach. **Currently, there isn't an JOSS editor assigned** to your paper.

@mdmurbach if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.12 s (356.1 files/s, 64324.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          17            723            895           1953
Markdown                         8            102              0            282
TeX                              1             17              0            266
Jupyter Notebook                 6              0           2873            225
reStructuredText                 8            108             84            156
DOS Batch                        1              8              1             27
YAML                             1              6              2             19
make                             1              4              7             10
-------------------------------------------------------------------------------
SUM:                            43            968           3862           2938
-------------------------------------------------------------------------------


Statistical information for the repository '2219' was gathered on 2020/05/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
BGerwe                           8           245             21            0.58
Brian Gerwe                     23          1374            930            4.99
Dave Beck                        2          1444           1444            6.26
Jason Bonezzi                    4         13579          13380           58.39
Kenny Huynh                      3            26              1            0.06
Lok-kun Tsui                    28           768             95            1.87
Matt Murbach                   114          6006           4721           23.23
Neal Dawson-Elli                22          1267            670            4.20
Rowin                            2            23              4            0.06
khuynh                           5             8             10            0.04
nobkat                           1            24              4            0.06
pangq2                           2           118              6            0.27

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Brian Gerwe                 894           65.1          2.3                7.27
Jason Bonezzi               186            1.4         23.7               52.69
Lok-kun Tsui                337           43.9          4.9                4.75
Matt Murbach               1562           26.0         10.7                7.04
Neal Dawson-Elli            530           41.8          4.6                8.11
khuynh                       27          337.5          0.3                7.41
pangq2                       35           29.7         23.7               11.43
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/0013-4686(93)85083-B is OK
- 10.1149/2.0711811jes is OK
- 10.21105/joss.01057 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1007/s40964-018-0054-2 is OK
- 10.1016/j.electacta.2014.01.034 is OK
- 10.1149/2.1021802jes is OK
- 10.1149/2.1051908jes is OK
- 10.1016/S0167-2738(02)00185-6 is OK
- 10.1016/0013-4686(95)00440-8 is OK
- 10.1016/S0378-7753(99)00351-1 is OK
- 10.1016/j.electacta.2005.02.148 is OK
- 10.1149/1.1836485 is OK
- 10.1016/S0013-4686(98)00138-8 is OK
- 10.1114/1.1366675 is OK

MISSING DOIs

- None

INVALID DOIs

- http://www.scipy.org/ is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02219/joss.02219/10.21105.joss.02219.pdf)

**Comment by arfon** [comment]
:wave: @mdmurbach. Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by mdmurbach** [comment]
👋 @arfon Thanks for all your work!

I know we're still waiting on an editor, but I've looked through the list above and listed a few reviewers for now 😄 I'll also plan on fixing the DOI issue flagged above. Please let me know if there is anything else I can be of help with. Hope you're staying healthy; have a good weekend! 🚀 

#### Potential reviewers
- `EricaEgg` <-- we've worked in the same lab together, but not on this software
- `amandadumi`
- `shivupa`
- `untzag`

**Comment by mdmurbach** [comment]
Fixed the scipy reference issue above 🎉 

@whedon generate pdf

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/0013-4686(93)85083-B is OK
- 10.1149/2.0711811jes is OK
- 10.21105/joss.01057 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1007/s40964-018-0054-2 is OK
- 10.1016/j.electacta.2014.01.034 is OK
- 10.1149/2.1021802jes is OK
- 10.1149/2.1051908jes is OK
- 10.1016/S0167-2738(02)00185-6 is OK
- 10.1016/0013-4686(95)00440-8 is OK
- 10.1016/S0378-7753(99)00351-1 is OK
- 10.1016/j.electacta.2005.02.148 is OK
- 10.1149/1.1836485 is OK
- 10.1016/S0013-4686(98)00138-8 is OK
- 10.1114/1.1366675 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1038/s41592-019-0686-2 is INVALID because of 'https://doi.org/' prefix
```

**Comment by arfon** [comment]
@mdmurbach - DOIs should be listed as e.g. `10.1038/s41592-019-0686-2` in the BibTeX please.

**Comment by mdmurbach** [comment]
👍 thanks! Just pushed a fix

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/0013-4686(93)85083-B is OK
- 10.1149/2.0711811jes is OK
- 10.21105/joss.01057 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1007/s40964-018-0054-2 is OK
- 10.1016/j.electacta.2014.01.034 is OK
- 10.1149/2.1021802jes is OK
- 10.1149/2.1051908jes is OK
- 10.1016/S0167-2738(02)00185-6 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1016/0013-4686(95)00440-8 is OK
- 10.1016/S0378-7753(99)00351-1 is OK
- 10.1016/j.electacta.2005.02.148 is OK
- 10.1149/1.1836485 is OK
- 10.1016/S0013-4686(98)00138-8 is OK
- 10.1114/1.1366675 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02219/joss.02219/10.21105.joss.02219.pdf)

**Comment by danielskatz** [comment]
👋 @mbobra - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @mbobra as editor

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by danielskatz** [comment]
@whedon invite @mobra as editor

**Comment by danielskatz** [comment]
👋 - I think this is still waiting for you. (But I also feel like perhaps we discussed this in email, so let me know if I'm wrong and there's a decision that didn't get recorded here.)

**Comment by kyleniemeyer** [comment]
@whedon invite @mbobra as editor

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by mbobra** [comment]
@whedon assign @mbobra as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by mbobra** [comment]
Thanks for your submission, @mdmurbach! Please give me a few days to find some reviewers.

**Comment by mdmurbach** [comment]
Awesome, thanks @mbobra! 😄

**Comment by mbobra** [comment]
@whedon assign @ma-sadeghi as reviewer

**Comment by whedon** [comment]
OK, @ma-sadeghi is now a reviewer

**Comment by mbobra** [comment]
@whedon add @EricaEgg as reviewer

**Comment by whedon** [comment]
OK, @EricaEgg is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2349.
