### ISSUE TITLE
[REVIEW]: filltex: Automatic queries to ADS and INSPIRE databases to fill LaTex bibliography

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#222]
**Submitting author:** @dgerosa (<a href="http://orcid.org/0000-0002-0933-3579">Davide Gerosa</a>)
**Repository:** <a href="https://github.com/dgerosa/filltex" target ="_blank">https://github.com/dgerosa/filltex</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** @lnielsen
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.570875" target="_blank">10.5281/zenodo.570875</a>

## Status

[![status](http://joss.theoj.org/papers/4f08218cfae0de6b41a5739ea03d91d2/status.svg)](http://joss.theoj.org/papers/4f08218cfae0de6b41a5739ea03d91d2)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/4f08218cfae0de6b41a5739ea03d91d2"><img src="http://joss.theoj.org/papers/4f08218cfae0de6b41a5739ea03d91d2/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/4f08218cfae0de6b41a5739ea03d91d2/status.svg)](http://joss.theoj.org/papers/4f08218cfae0de6b41a5739ea03d91d2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dgerosa/filltex" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dgerosa/filltex">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@dgerosa) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @lnielsen it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by lnielsen** [comment]
I've had an initial review of the repository. I like that it's a small simple script to automate the fetching the citations automatically from ADS/INSPIRE. I think it's definitely something that can save researchers time when writing so that's much appreciated.

I think the following issues should be resolved before the paper can be accepted:

- [ ] dgerosa/filltex#1
- [ ] dgerosa/filltex#2
- [ ] dgerosa/filltex#4
- [ ] dgerosa/filltex#5
- [ ] dgerosa/filltex#8

These optional issues will help improve the quality of the software but are not necessary in order to accept the paper:

- [ ] dgerosa/filltex#3
- [ ] dgerosa/filltex#6

**Comment by arfon** [comment]
⚡️ many thanks @lnielsen!

**Comment by dgerosa** [comment]
Hello,

Michele @vallis and I addressed your comments. Please let us know if you find our modifications acceptable. Should I close the issues? 

Best,
Davide

**Comment by arfon** [comment]
> Michele (@vallis) and I addressed your comments. Please let us know if you find our modifications acceptable. Should I close the issues?

@lnielsen - I think we should be good to accept here? Could you confirm?

**Comment by lnielsen** [comment]
Yep, ok from my side. Sorry for the delay - was on extended vacation over easter :-)

**Comment by arfon** [comment]
> Yep, ok from my side. Sorry for the delay - was on extended vacation over easter :-)

👍 thanks for confirming @lnielsen 

@dgerosa @vallis - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by dgerosa** [comment]
Hello,

here is the badge for the new release (v1.1):
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.570875.svg)](https://doi.org/10.5281/zenodo.570875)

Best,
Davide

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.570875 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.570875" target="_blank">10.5281/zenodo.570875</a> is the archive.

**Comment by arfon** [comment]
@dgerosa - apologies for being late to suggest this but could you move the references/links you currently have in the `paper.md` file into a `paper.bib` file and cite them directly please? (You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html))

**Comment by dgerosa** [comment]
Hello,

I don't have references. I moved the links into a .bib file, now in the JOSS directory.

Davide

**Comment by arfon** [comment]
Thanks @dgerosa. That's not quite it: you now need to cite these items in the `paper.bib` file (e.g. `@TexShop` - https://github.com/dgerosa/filltex/blob/master/JOSS/paper.bib#L25)

**Comment by dgerosa** [comment]
It should be fixed now. Please let me know.

**Comment by arfon** [comment]
@lnielsen - many thanks for the review here ✨ 

@dgerosa - your submission is now accepted into JOSS and your paper DOI is http://dx.doi.org/10.21105/joss.00222 :zap: 🚀 💥

**Comment by dgerosa** [comment]
Great! Thanks
