### ISSUE TITLE
[PRE REVIEW]: arcos (R) and arcospy (Python): twin software packages to access the DEA ARCOS database from 2006 to 2014

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2223]
**Submitting author:** @jeffcsauer (<a href="http://orcid.org/0000-0002-8581-6919">Jeffery Sauer</a>)
**Repository:** <a href="https://github.com/jeffcsauer/arcos_arcospy_information" target ="_blank">https://github.com/jeffcsauer/arcos_arcospy_information</a>
**Version:** arcos (1.1); arcospy (1.1.0)
**Editor:** @bmcfee
**Reviewers:** @jaeyk, @edonnachie
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jeffcsauer. **Currently, there isn't an JOSS editor assigned** to your paper.

@jeffcsauer if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.02 s (243.6 files/s, 11451.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         3             52              0             94
TeX                              1              4              0             38
-------------------------------------------------------------------------------
SUM:                             4             56              0            132
-------------------------------------------------------------------------------


Statistical information for the repository '2223' was gathered on 2020/05/22.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- doi:10.1016/j.drugpo.2019.03.024 is OK
- doi:10.1016/j.jpainsymman.2004.01.003 is OK
- doi:10.1001/jama.283.13.1710 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02223/joss.02223/10.21105.joss.02223.pdf)

**Comment by arfon** [comment]
:wave: @jeffcsauer - could you link the related software repositories here please?

**Comment by arfon** [comment]
:wave: @lorenanicole - would you be willing to edit this submission for JOSS?

**Comment by arfon** [comment]
@whedon invite @lorenanicole as editor

**Comment by whedon** [comment]
@lorenanicole has been invited to edit this submission.

**Comment by jeffcsauer** [comment]
Sure, no problem! Thanks for assigning and inviting an editor. 

[Link to `arcos` (r) repository](https://github.com/wpinvestigative/arcos)

[Link to `arcospy` (python) repository](https://github.com/jeffcsauer/arcospy)

Both links are also present in the article under the Availability section.

**Comment by danielskatz** [comment]
👋 @lorenanicole - just a reminder here that you have been invited to edit this submission as well (and no more are coming to you in the immediate future)

**Comment by arfon** [comment]
:wave: @jeffcsauer - @lorenanicole is a new editor and is already handling two JOSS submissions and so won't be able to take this one on. I'm going to mark this as `waitlisted` for now due to the large volume of submissions that have been received by JOSS in the last week but expect we'll be able to identify a handling editor relatively soon.

Thanks in advance for your patience!

**Comment by jeffcsauer** [comment]
Sounds good! Thank you for the follow-up.

**Comment by kyleniemeyer** [comment]
Hey @bmcfee, could you take this one on as your first editing assignment?

**Comment by kyleniemeyer** [comment]
@whedon invite @bmcfee as editor

**Comment by whedon** [comment]
@bmcfee has been invited to edit this submission.

**Comment by bmcfee** [comment]
@whedon assign @bmcfee as editor

**Comment by whedon** [comment]
I'm sorry @bmcfee, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by arfon** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@Kevin-Mattheus-Moerman
@KristinaRiemer
@VivianePons
@akeshavan
@arfon
@arokem
@bmcfee
@cMadan
@csoneson
@danielskatz
@dfm
@dhhagan
@diehlpk
@dpsanders
@drvinceknight
@gkthiruvathukal
@harpolea
@hugoledoux
@jedbrown
@jgostick
@karthik
@katyhuff
@kbarnhart
@kthyng
@kyleniemeyer
@labarba
@leouieda
@lorenanicole
@lpantano
@majensen
@marcosvital
@mbobra
@meg-simula
@melissawm
@mikldk
@mjsottile
@oliviaguest
@pdebuyl
@pibion
@poulson
@richardjgowers
@sjpfenninger
@terrytangyuan
@trallard
@usethedata
@will-rowe
@xuanxu
```

**Comment by arfon** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@Kevin-Mattheus-Moerman
@KristinaRiemer
@VivianePons
@akeshavan
@arfon
@arokem
@bmcfee
@cMadan
@csoneson
@danielskatz
@dfm
@dhhagan
@diehlpk
@dpsanders
@drvinceknight
@gkthiruvathukal
@harpolea
@hugoledoux
@jedbrown
@jgostick
@karthik
@katyhuff
@kbarnhart
@kthyng
@kyleniemeyer
@labarba
@leouieda
@lorenanicole
@lpantano
@majensen
@marcosvital
@mbobra
@meg-simula
@melissawm
@mikldk
@mjsottile
@oliviaguest
@pdebuyl
@pibion
@poulson
@richardjgowers
@sjpfenninger
@terrytangyuan
@trallard
@usethedata
@will-rowe
@xuanxu
```

**Comment by arfon** [comment]
@bmcfee try again now...

**Comment by bmcfee** [comment]
@whedon assign @bmcfee as editor

**Comment by whedon** [comment]
OK, the editor is @bmcfee

**Comment by bmcfee** [comment]
Thanks @arfon !

**Comment by bmcfee** [comment]
@jeffcsauer :wave: Things look generally good so far, so I'll get to finding some reviewers over the next few days.

In the meantime, I've noticed that the [`LICENSE`](https://github.com/wpinvestigative/arcos/blob/master/LICENSE) file in one of the repos doesn't quite line up with the [license listed in the submission repository](https://github.com/jeffcsauer/arcos_arcospy_information/blob/master/LICENSE).  These should be made complete and consistent to satisfy the submission requirements.

**Comment by bmcfee** [comment]
@mariacuellar @mkearney This looks like it could be up your respective alleys -- are you interested/available to review?

**Comment by jeffcsauer** [comment]
@bmcfee thanks for catching that! Reaching out to co-authors to clarify this and will update ASAP.

**Comment by jeffcsauer** [comment]
@bmcfee spoke with co-author and updated LICENSE file in [arcos_arcospy_information](https://github.com/jeffcsauer/arcos_arcospy_information/blob/master/LICENSE) and [arcospy](https://github.com/jeffcsauer/arcospy) to follow the lead of arcos. All LICENSE files across the software repositories and JOSS paper repo page are now consistent.

**Comment by bmcfee** [comment]
Thanks @jeffcsauer, however it now appears that these packages are not using a standard OSS license?  The README says "MIT", but the full text of the license should be included in the repository/ies (as per [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html)).

**Comment by jeffcsauer** [comment]
@bmcfee thanks for pointing this out! I spoke again with the co-author and confirmed the MIT + file LICENSE is the appropriate template. I updated the [arcos_arcospy_information ](https://github.com/jeffcsauer/arcos_arcospy_information/blob/master/LICENSE) LICENSE file to avoid confusion. Could you confirm this is now conforms to submission guidelines?

**Comment by bmcfee** [comment]
Just a heads up on this, since it's been a couple of weeks.  I'm still working on finding reviewers, but your patience is appreciated!

**Comment by jeffcsauer** [comment]
No worries, thanks for the update! Totally understand.

**Comment by bmcfee** [comment]
@whedon add @jaeyk as reviewer

**Comment by whedon** [comment]
OK, @jaeyk is now a reviewer

**Comment by bmcfee** [comment]
@whedon add @edonnachie as reviewer

**Comment by whedon** [comment]
OK, @edonnachie is now a reviewer

**Comment by bmcfee** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2450.
