### ISSUE TITLE
[PRE REVIEW]: TEfits: Nonlinear regression for time-evolving indices

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2226]
**Submitting author:** @akcochrane (<a href="http://orcid.org/0000-0001-6691-9149">Aaron Cochrane</a>)
**Repository:** <a href="https://github.com/akcochrane/TEfits" target ="_blank">https://github.com/akcochrane/TEfits</a>
**Version:** v0.77.01
**Editor:** @cMadan
**Reviewers:** @ejhigson, @paul-buerkner
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @akcochrane. **Currently, there isn't an JOSS editor assigned** to your paper.

@akcochrane if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (623.6 files/s, 55244.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               47            559           1269           2405
Markdown                         2             52              0            195
TeX                              1              3              0             52
Rmd                              2             79            107             50
YAML                             1              2              0              6
INI                              1              1              0              4
-------------------------------------------------------------------------------
SUM:                            54            696           1376           2712
-------------------------------------------------------------------------------


Statistical information for the repository '2226' was gathered on 2020/05/22.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18637/jss.v067.i01 is OK
- 10.18637/jss.v080.i01 is OK
- 10.1167/17.11.3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02226/joss.02226/10.21105.joss.02226.pdf)

**Comment by arfon** [comment]
:wave: @akcochrane - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by ejhigson** [comment]
@akcochrane @arfon I would be happy to review this software once the review process begins if that would be helpful.

**Comment by kyleniemeyer** [comment]
Hey @cMadan, do you have the bandwidth to edit this one right now?

**Comment by kyleniemeyer** [comment]
@whedon invite @cMadan as editor

**Comment by whedon** [comment]
@cMadan has been invited to edit this submission.

**Comment by cMadan** [comment]
@kyleniemeyer, sure I can take this one on.

@ejhigson, thanks for volunteering to review!

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@whedon add @ejhigson as reviewer

**Comment by whedon** [comment]
OK, @ejhigson is now a reviewer

**Comment by cMadan** [comment]
@akcochrane, I'll do some pre-review checks over the next few days and let you know if I have any suggestions before the review process starts.

**Comment by akcochrane** [comment]
Thanks. Looking forward to the review process!

**Comment by cMadan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02226/joss.02226/10.21105.joss.02226.pdf)

**Comment by cMadan** [comment]
@akcochrane, sorry for the delay, it looks like you need to add some `{` and `}` around terms in your bib to fix the capitalisation in the references but otherwise things look good. 

Do you have any additional suggestions for reviewers (see the initial comment in this issue for some guidance) ?

**Comment by akcochrane** [comment]
@cMadan Thanks for pointing those out, I've made some minor changes to the paper that include the capitalization of references. 
Regarding reviewers, I don't have any particularly well-informed suggestions. Given the information available in the initial comment, it seems that **samhforbes**, **ssriv**, or **Darthpathos** may have relevant overlapping interest and expertise.

**Comment by cMadan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02226/joss.02226/10.21105.joss.02226.pdf)

**Comment by cMadan** [comment]
@samhforbes @ssriv @Darthpathos, would you be available and interested in reviewing this submission? Thanks for your consideration!

**Comment by cMadan** [comment]
@DominiqueMakowski @johannes-titz @paul-buerkner, would you be available and interested in reviewing this submission? Thanks for your consideration!

**Comment by paul-buerkner** [comment]
I should be able to review this submission.

**Comment by johannes-titz** [comment]
@cMadan Sorry, I have some important deadlines coming up, so I cannot do it.

**Comment by cMadan** [comment]
@paul-buerkner, that would be great thank you!

@johannes-titz, thanks for letting me know!

@akcochrane @ejhigson @paul-buerkner, as we now have two reviewers, I will go ahead and start the actual review process. Do let me know if you have any questions as things progress!

**Comment by cMadan** [comment]
@whedon add @paul-buerkner as reviewer

**Comment by whedon** [comment]
OK, @paul-buerkner is now a reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2535.
