### ISSUE TITLE
[PRE REVIEW]: FIPS: An R Package for Biomathematical Modelling of Human Fatigue Related Impairment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2227]
**Submitting author:** @humanfactors (<a href="http://orcid.org/0000-0003-4143-7308">Michael David Wilson</a>)
**Repository:** <a href="https://github.com/humanfactors/FIPS" target ="_blank">https://github.com/humanfactors/FIPS</a>
**Version:** 0.1.0
**Editor:** @oliviaguest
**Reviewers:** @craddm, @anibalsolon
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @humanfactors. **Currently, there isn't an JOSS editor assigned** to your paper.

@humanfactors if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02227/joss.02227/10.21105.joss.02227.pdf)

**Comment by arfon** [comment]
:wave: @humanfactors - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by humanfactors** [comment]
Thank you for message @arfon, all delays are very much understood during these tough times. Quick question, are we able to start using the assigned DOI in the article proof as of now, or should we continue referencing the DOI assigned from PsyArXiv preprint?

Note, @lukestrickland and @ballardtj the article proof processed above.

## Suggested Reviewers

I've identified three potential reviewers (see below) from the list of volunteer reviewers based on expertise in both R and Cognitive Modelling/Psychology. Unfortunately, I don't know of other suitable reviewers, though am happy to expand suggestions from list as required.

- craddm
- wjakethompson
- mmrabe

Thanks for your assistance!

**Comment by arfon** [comment]
> Thank you for message @arfon, all delays are very much understood during these tough times. Quick question, are we able to start using the assigned DOI in the article proof as of now, or should we continue referencing the DOI assigned from PsyArXiv preprint?

Please don't use the DOI from the proof - it's not the final DOI.

**Comment by kyleniemeyer** [comment]
Hi @oliviaguest, do you have the bandwidth to edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @oliviaguest as editor

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by oliviaguest** [comment]
Sure! I am having a lot of trouble finding reviewers for other submissions (been sending about 5 🙀  times as many emails and getting back almost all rejections) — but very happy to take this on given the system is able to understand these inevitable delays. 😊

**Comment by kyleniemeyer** [comment]
@oliviaguest thanks! and yes, absolutely. Personally basically everything I'm doing is delayed somehow (evidence: you getting this request on a Friday, rather than earlier in the week...)

**Comment by oliviaguest** [comment]
Cool! 🌼

**Comment by labarba** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by oliviaguest** [comment]
Hi @humanfactors, if you can post some suggestions for reviewers that would be very useful — thanks! ☺️

**Comment by oliviaguest** [comment]
Sorry, @humanfactors (deleted previous as I forgot you had some suggestions) but I just realised you suggested some from the list, which I think I have tried (will double check). In general, I've been having no luck. Do you think you might know anybody outside the JOSS list?

**Comment by humanfactors** [comment]
Hi @oliviaguest, thanks for efforts reaching out to potential reviewers. I might have some ideas, the issue of course is finding individuals with overlapping subject matter familiarity/expertise as well as R expertise. I assume we need both?

Depending on flexibility with expertise areas, I might have some more suggestions. In any case, I'll conduct a broader search for suggestions. 

Cheers.

**Comment by oliviaguest** [comment]
@whedon add @craddm as reviewer

**Comment by whedon** [comment]
OK, @craddm is now a reviewer

**Comment by oliviaguest** [comment]
@humanfactors thank you so much — I will reach out to more people too but excited (and grateful!) to say @craddm is happy to be part of this. 🥳

**Comment by oliviaguest** [comment]
@whedon add @anibalsolon as reviewer

**Comment by whedon** [comment]
OK, @anibalsolon is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2340.

**Comment by oliviaguest** [comment]
Hi all! 👋 @humanfactors, @craddm, @anibalsolon — please head on to the review issue: #2340!
