### ISSUE TITLE
[PRE REVIEW]: rgee: An R package for interacting with Google Earth Engine

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2228]
**Submitting author:** @csaybar (<a href="http://orcid.org/0000-0003-2745-9535">Cesar Luis Aybar Camacho</a>)
**Repository:** <a href="https://github.com/r-spatial/rgee" target ="_blank">https://github.com/r-spatial/rgee</a>
**Version:** v.0.5.0
**Editor:** @hugoledoux
**Reviewers:** @appelmar, @gena
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @csaybar. **Currently, there isn't an JOSS editor assigned** to your paper.

@csaybar if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by arfon** [comment]
:wave: @csaybar - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by whedon** [comment]
PDF failed to compile for issue #2228 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2228 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
@whedon check repository

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02228/joss.02228/10.21105.joss.02228.pdf)

**Comment by csaybar** [comment]
Hi @arfon, thanks for considering **rgee** for reviewing. I would like to suggest as potential reviewers to: **mikejohnson51 GISerDaishaoqing  kauedesousa jsta  jhollist nuest**

**Comment by danielskatz** [comment]
👋 @hugoledoux - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @hugoledoux as editor

**Comment by whedon** [comment]
@hugoledoux has been invited to edit this submission.

**Comment by hugoledoux** [comment]
ok sure

**Comment by danielskatz** [comment]
Thanks - I'm going to make the assignment now, but you can also do this yourself next time.

**Comment by danielskatz** [comment]
@whedon assign @hugoledoux as editor

**Comment by whedon** [comment]
OK, the editor is @hugoledoux

**Comment by hugoledoux** [comment]
👋 @jhollist would you be interested in reviewing this submission for JOSS?
    
  > rgee: An R package for interacting with Google Earth Engine

software: https://github.com/r-spatial/rgee

**Comment by hugoledoux** [comment]
thank you @appelmar & @gena for accepting to review this submission.

Since there are 2 of you, I'll start the review process, it's in another issue, it will be shown below.

I know for both of you it's the first review, so I'll help you in the process, and don't hesitate to ask for my help by tagging me.

**Comment by hugoledoux** [comment]
@whedon add @appelmar as reviewer

**Comment by whedon** [comment]
OK, @appelmar is now a reviewer

**Comment by hugoledoux** [comment]
@whedon add @gena as reviewer

**Comment by whedon** [comment]
OK, @gena is now a reviewer

**Comment by hugoledoux** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2272.

**Comment by jhollist** [comment]
@hugoledoux It looks like you are all set on reviewers for this?  If so, great!  If you do need an additional one, just let me know.
