### ISSUE TITLE
[PRE REVIEW]: OSeMOSYS-CR: Costa Rica’s Energy System Optimization Model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2229]
**Submitting author:** @guidogz (<a href="http://orcid.org/0000-0002-0256-1640">Guido Godínez-Zamora</a>)
**Repository:** <a href="https://github.com/EPERLab/OSeMOSYS-CR" target ="_blank">https://github.com/EPERLab/OSeMOSYS-CR</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @guidogz. **Currently, there isn't an JOSS editor assigned** to your paper.

@guidogz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02229/joss.02229/10.21105.joss.02229.pdf)

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.34 s (184.5 files/s, 87515.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      13           2395           2247          11477
HTML                            13           1852             13           2983
SVG                              1              0              0           2671
reStructuredText                19            782            992           1535
Python                           3             78            274           1003
CSS                              5            148             37            577
TeX                              2             27              0            144
Markdown                         3             27              0             72
DOS Batch                        1              8              1             27
YAML                             1              5              2             13
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                            62           5326           3572          20512
-------------------------------------------------------------------------------


Statistical information for the repository '2229' was gathered on 2020/05/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
guidogz                         13         17485             14           99.74
jamangulop                      18            24             21            0.26

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
guidogz                   17467           99.9          1.8               14.44
jamangulop                    7           29.2          1.0                0.00
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by arfon** [comment]
:wave: @guidogz - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by kyleniemeyer** [comment]
Hi @guidogz, we'll be working to get this to an editor to handle. However, I noticed that your repository is missing an open-source license, which is one of the requirements for submitting software to JOSS. Can you please add an open-source license to your software?

**Comment by kyleniemeyer** [comment]
Hi @sjpfenninger, do you have the bandwidth to edit this?

**Comment by kyleniemeyer** [comment]
@whedon invite @sjpfenninger as editor

**Comment by whedon** [comment]
@sjpfenninger has been invited to edit this submission.

**Comment by guidogz** [comment]
> Hi @guidogz, we'll be working to get this to an editor to handle. However, I noticed that your repository is missing an open-source license, which is one of the requirements for submitting software to JOSS. Can you please add an open-source license to your software?

**Comment by guidogz** [comment]
The license is ready, thanks!

**Comment by labarba** [comment]
@guidogz -- After a pre-review of your submission, and an assessment by the editorial board at large, we find that it does not meet our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). In particular, it was found to be out-of-scope as not research software, and we therefore decided not to put it through review. 

The assessment by our editors is:

>  the submission appears to consist primarily of data (i.e. model assumptions and input data for a study on Costa Rica). I think this stretches beyond what we want to consider as software, and should be submitted to a disciplinary journal where reviewers can really focus on the research question(s) this was built to answer, and on the data and assumptions.

**Comment by labarba** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
