### ISSUE TITLE
[PRE REVIEW]: cbcbeat: an adjoint-enabled framework for computational cardiac electrophysiology

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#223]
**Submitting author:** @meg-simula (<a href="http://orcid.org/0000-0002-6872-3710">Marie Rognes</a>)
**Repository:** <a href="https://bitbucket.org/meg/cbcbeat" target ="_blank">https://bitbucket.org/meg/cbcbeat</a>
**Version:** v1.0
**Editor:** @labarba
**Reviewer:** @jessdtate

**Author instructions**

Thanks for submitting your paper to JOSS @meg-simula. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@meg-simula if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
> Editor: @labarba 

@labarba - this was a suggestion from the submitting author. Please shout it you don't think this is a good fit.

**Comment by labarba** [comment]
@whedon assign @jessdtate as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jessdtate

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by labarba** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/224. Feel free to close this issue now!
