### ISSUE TITLE
[PRE REVIEW]: dcgp: Differentiable Cartesian Genetic Programming made easy.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2230]
**Submitting author:** @darioizzo (<a href="http://orcid.org/0000-0002-9846-8423">Dario Izzo</a>)
**Repository:** <a href="https://github.com/darioizzo/dcgp" target ="_blank">https://github.com/darioizzo/dcgp</a>
**Version:** v1.5.1
**Editor:** @VivianePons
**Reviewers:** @Ohjeah, @shah314
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @darioizzo. **Currently, there isn't an JOSS editor assigned** to your paper.

@darioizzo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.01 s (326.9 files/s, 19720.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         2             21              0             95
TeX                              1              6              0             59
-------------------------------------------------------------------------------
SUM:                             3             27              0            154
-------------------------------------------------------------------------------


Statistical information for the repository '2230' was gathered on 2020/05/22.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.3702783 is OK
- 10.5281/zenodo.3820769 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-319-55696-3_3 may be missing for title: Differentiable genetic programming
- https://doi.org/10.1007/s10710-010-9112-3 may be missing for title: Human-competitive results produced by genetic programming
- https://doi.org/10.1007/978-3-642-17310-3_2 may be missing for title: Cartesian genetic programming
- https://doi.org/10.1145/3319619.3322003 may be missing for title: Neural network architecture search with differentiable cartesian genetic programming for regression

INVALID DOIs

- None
```

**Comment by arfon** [comment]
:wave: @darioizzo - thanks for your submission to JOSS. Do you think you could move this paper into the same repository as the software?

As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02230/joss.02230/10.21105.joss.02230.pdf)

**Comment by darioizzo** [comment]
@arfon I would rather keep the repositories for the code and this paper separate. The reasons are that the code will evolve and change, while the paper, if published should stay unmodified. I also do not like having too many files in the root folder of the code repository (but thats a matter of taste).

**Comment by darioizzo** [comment]
Going through the reviewer list, I noticed the entry ``Ohjeah`` that seems to me as a good fit for this paper, thus I am daring suggesting him.

**Comment by arfon** [comment]
> I could make a branch with the paper only if thats better?

Yes, a branch would be better than what we have currently here. Also, the paper can be anywhere in the repository (i.e. nested in a folder) so doesn't need to be in the repository root.

**Comment by darioizzo** [comment]
@arfon I have moved all files to a branch in the repository https://github.com/darioizzo/dcgp/tree/joss-paper-v1.5.1

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper-v1.5.1

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-v1.5.1. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02230/joss.02230/10.21105.joss.02230.pdf)

**Comment by darioizzo** [comment]
proof looks ok to me.

**Comment by danielskatz** [comment]
👋 @VivianePons - would you be able to edit this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon invite @VivianePons as editor

**Comment by whedon** [comment]
@VivianePons has been invited to edit this submission.

**Comment by VivianePons** [comment]
Sure

**Comment by VivianePons** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by VivianePons** [comment]
@whedon assign @Ohjeah as reviewer

**Comment by whedon** [comment]
OK, @Ohjeah is now a reviewer

**Comment by VivianePons** [comment]
@whedon add @shah314 as reviewer

**Comment by whedon** [comment]
OK, @shah314 is now a reviewer

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2290.
