### ISSUE TITLE
[REVIEW]: policytree: Policy learning via doubly robust empirical welfare maximization over trees

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2232]
**Submitting author:** @erikcs (<a href="http://orcid.org/0000-0001-6093-1390">Erik Sverdrup</a>)
**Repository:** <a href="https://github.com/grf-labs/policytree" target ="_blank">https://github.com/grf-labs/policytree</a>
**Version:** v0.9.2
**Editor:** @arfon
**Reviewer:** @nhejazi, @jjharden
**Archive:** <a href="https://doi.org/10.5281/zenodo.3903433" target="_blank">10.5281/zenodo.3903433</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/7147cbf65fc0b407cf21a80eca107fb4/status.svg)](https://joss.theoj.org/papers/7147cbf65fc0b407cf21a80eca107fb4)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7147cbf65fc0b407cf21a80eca107fb4"><img src="https://joss.theoj.org/papers/7147cbf65fc0b407cf21a80eca107fb4/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7147cbf65fc0b407cf21a80eca107fb4/status.svg)](https://joss.theoj.org/papers/7147cbf65fc0b407cf21a80eca107fb4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/grf-labs/policytree" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@nhejazi & @jjharden, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/grf-labs/policytree">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@erikcs) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/grf-labs/policytree">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@erikcs) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @nhejazi, @jjharden it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2232 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch oss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch oss-paper. Reticulating splines etc...
```

**Comment by arfon** [comment]
@nhejazi, @jjharden - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02232/joss.02232/10.21105.joss.02232.pdf)

**Comment by arfon** [comment]
:wave: @nhejazi, @jjharden - just checking in to see how you're getting along here?

**Comment by jjharden** [comment]
My invitation expired. Is it possible to resend it? Thanks.

**Comment by danielskatz** [comment]
@whedon re-invite @jjharden

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by danielskatz** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by danielskatz** [comment]
@whedon re-invite @jjharden as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@jjharden please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by jjharden** [comment]
I have completed a review of this paper and software. Overall, I believe it represents a useful contribution. Here are my comments for revision.

1. The documentation is somewhat sparse. I left a few items unchecked above which I think could be improved (statement of need, example, functionality). Also, there is a dependency on the DiagrammeR package that tripped up my initial run of the simulated data example from the paper.

2. I think the paper itself could better address "high-level functionality and [the] purpose of the software for a diverse, non-specialist audience." 

I congratulate the authors on their contribution. Please let me know if you have further questions.

**Comment by erikcs** [comment]
Thank you @jjharden. 

1. Do you have suggestions for what you would see documented? Currently the introduction is in the online vignette: https://grf-labs.github.io/policytree/articles/policytree.html, with the rest being method docstrings.

    Not including the DiagrammeR is intentional to keep dependencies to a minimum. It is an optional add-on for the user who wishes to plot, you should have gotten an informative error message? ([this one](https://github.com/grf-labs/policytree/blob/master/R/policy_tree-plot.R#L89), it is done the same way in [grf](https://github.com/grf-labs/grf))

**Comment by erikcs** [comment]
Also, @nhejazi please let us know if there are similar packages in the tlverse we should cite that we may have missed.

**Comment by jjharden** [comment]
Sorry, my comments about documentation referred to the help files in R (e.g., by typing ?double_robust_scores). The online vignette looks complete.

Yes, that is the error message I got and I agree it was informative. I understand and appreciate wanting to minimize dependencies. It might be worth considering a footnote about the need for DiagrammeR in the paper. My sense is that most users would expect that code to run error-free. But it is a minor issue either way.

**Comment by nhejazi** [comment]
I just had some time to go through the package and paper throughout yesterday
and today. I agree with @jjharden that the package seems to provide an good and
very useful contribution. For a few major comments about the package, I opened
up issues https://github.com/grf-labs/policytree/issues/30 and
https://github.com/grf-labs/policytree/issues/31. Once these are addressed, I'll
be able to check off the few remaining items on the checklist above. Some minor
comments on the package and paper are included below.

Minor comments on the package (these need not be addressed for acceptance):
* The package documentation generally looks good, though there are minor aspects
  of it that could be improved, such as adding short running examples for
  exported functions/methods (e.g., `double_robust_scores.causal_forest` and
  `conditional_means.causal_forest`).
* It would be nice to add a citations section both to the `README` and as a
  plain text file in the `inst` directory (e.g.,
  https://github.com/nhejazi/medshift/blob/master/inst/CITATION), so that
  citations can be generated from R via `citation(policytree)`.
* The `README.md` is generally well written. It includes appropriate R examples
  and references, both good things. Since the file includes example code (and
  the output of this code), I would recommend converting the `README.md` file
  to an R Markdown file `README.Rmd` that can be used to auto-generate the
  `README.md`. This will be useful to ensure that the example code remains up
  to date as the package evolves over time. For example, consider
  https://github.com/nhejazi/medshift/blob/master/README.Rmd

Minor comments on the paper:
* The first sentence of the second paragraph should read: "There has recently
  been a considerable amount __[of]__ work..." (missing preposition added).
* The R language is mentioned but not cited. For this purpose, I generally use
  a BibTeX entry like the following https://scholar.googleusercontent.com/scholar.bib?q=info:vROS1kQC7b8J:scholar.google.com/&output=citation&scisdr=CgXI3MF1EK2KvDjnRqI:AAGBfm0AAAAAXtriXqLBfUBBIBiwusVRnSFBi3CX4VsU&scisig=AAGBfm0AAAAAXtriXmJOD9c7swu-rkbMdWU5sgDW3caO&scisf=4&ct=citation&cd=-1&hl=en
  (but update the years). Feel free to use another appropriate entry too.
* A good overview of methods for learning optimal rules is provided. It could
  be improved by including other recent doubly robust and data adaptive
  developments in similar vein, e.g., https://pubmed.ncbi.nlm.nih.gov/27227726/
  an https://pubmed.ncbi.nlm.nih.gov/26236571/
* Since you asked @erikcs, an R package implementing the above approaches is
  available https://github.com/tlverse/tmle3mopttx, documented in long-form at
  https://tlverse.org/tlverse-handbook/optimal-individualized-treatment-regimes.html

**Comment by erikcs** [comment]
Thank you @nhejazi, I have opened three PRs in https://github.com/grf-labs/policytree/pulls.

The paper has also been updated with more references. 

@whedon generate pdf from branch oss-paper

**Comment by arfon** [comment]
@whedon generate pdf from branch oss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch oss-paper. Reticulating splines etc...
```

**Comment by arfon** [comment]
☝️ @erikcs - commands to Whedon have to be standalone in their own comment (or at the very start of a comment).

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02232/joss.02232/10.21105.joss.02232.pdf)

**Comment by erikcs** [comment]
> ☝️ @erikcs - commands to Whedon have to be standalone in their own comment (or at the very start of a comment).

Got it, thanks.

**Comment by erikcs** [comment]
@jjharden I added a note under Figure 1 that `DiagrammeR` is needed for tree plots.

**Comment by erikcs** [comment]
@whedon generate pdf from branch oss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch oss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02232/joss.02232/10.21105.joss.02232.pdf)

**Comment by erikcs** [comment]
Just checking in and summarizing the changes so far:

1. Paper: under Figure 1 we add a note that DiagrammeR is needed for tree plots (we do not include it as a dependency since it has a ton of dependencies). 

2. Paper: we fix the typo pointed out

3. Paper: we add add two articles pointed out by @nhejazi to the citation list, cite the use of R, and cite another useful package from the tlverse. 

4. Code: we update the dosctring for `double_robust_scores` and `conditional_means` with one more example (https://github.com/grf-labs/policytree/pull/34)

5. Code: We add a more informative package description on the GitHub landing page (https://github.com/grf-labs/policytree/pull/32)

6. Code: We clarify the community guidelines by adding a separate DEVELOPING.md (this reuses some info from our parent package, grf), and add more descriptive links to issues and the online documentation (https://github.com/grf-labs/policytree/pull/33).

**Comment by jjharden** [comment]
The paper looks ready to go to me. I have no more suggested changes.

**Comment by nhejazi** [comment]
Looks good to me as well! Thanks for making these changes, @erikcs.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2232 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch oss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch oss-paper. Reticulating splines etc...
```

**Comment by arfon** [comment]
@whedon check references from branch oss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch oss-paper
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2232 with the following error: 

 pandoc: 10.21105.joss.02232.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18637/jss.v061.i01 is OK

MISSING DOIs

- https://doi.org/10.1920/wp.cem.2017.2417 may be missing for title: Who should be treated? empirical welfare maximization methods for treatment choice
- https://doi.org/10.2307/146183 may be missing for title: The benefits and costs of JTPA Title II-A programs: Key findings from the National Job Training Partnership Act study
- https://doi.org/10.1920/wp.cem.2003.0303 may be missing for title: Statistical treatment rules for heterogeneous populations
- https://doi.org/10.1515/ijb-2015-0052 may be missing for title: Super-learning of an optimal dynamic treatment rule

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon generate pdf from branch oss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch oss-paper
. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2232 with the following error: 

 error: pathspec 'oss-paper
' did not match any file(s) known to git.
Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch oss-paper

Thanks @nhejazi and @jjharden.

@erikcs - could you check those potentially missing DOIs for the references and also give the paper one final read to check everything looks OK?

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch oss-paper
. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2232 with the following error: 

 error: pathspec 'oss-paper
' did not match any file(s) known to git.
Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch oss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch oss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02232/joss.02232/10.21105.joss.02232.pdf)

**Comment by arfon** [comment]
@whedon accept from branch oss-paper

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by erikcs** [comment]
@whedon check references from branch oss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch oss-paper
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3982/ECTA13288 is OK
- 10.2307/146183 is OK
- 10.18637/jss.v061.i01 is OK
- 10.1111/j.1468-0262.2004.00530.x is OK
- 10.1515/ijb-2015-0052 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by erikcs** [comment]
Thank you for the review @jjharden and @nhejazi!

**Comment by erikcs** [comment]
> @whedon generate pdf from branch oss-paper
> 
> Thanks @nhejazi and @jjharden.
> 
> @erikcs - could you check those potentially missing DOIs for the references and also give the paper one final read to check everything looks OK?

Thank you @arfon, I have updated the .bib file with DOIs from the publisher's page for the listed items.

**Comment by arfon** [comment]
@erikcs - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by erikcs** [comment]
@arfon A version 1.0 version of the [package](https://github.com/grf-labs/policytree/pull/35) with the enhancements arising from this review (and some earlier fixes) is published on [CRAN](https://cran.r-project.org/web/packages/policytree/index.html) now. 

The Zenodo archive is here: https://zenodo.org/record/3903401

**Comment by arfon** [comment]
@erikcs - thanks for this. One small request, please use a Zenodo-issued DOI for your deposit with them. You've currently got the _JOSS_ DOI listed as the DOI but this won't work:

<img width="373" alt="Screen_Shot_2020-06-22_at_10_16_48_AM" src="https://user-images.githubusercontent.com/4483/85298089-a4f44f00-b471-11ea-9f24-de92f8a01a39.png">

**Comment by erikcs** [comment]
@arfon Here is a new Zenodo archive with their generated DOI: https://zenodo.org/record/3903433 (I have asked them to delete the first submission).

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3903433 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3903433" target="_blank">10.5281/zenodo.3903433</a> is the archive.

**Comment by arfon** [comment]
@whedon accept from branch oss-paper

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3982/ECTA13288 is OK
- 10.2307/146183 is OK
- 10.18637/jss.v061.i01 is OK
- 10.1111/j.1468-0262.2004.00530.x is OK
- 10.1515/ijb-2015-0052 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1511

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1511, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch oss-paper 
```

**Comment by arfon** [comment]
@whedon accept deposit=true from branch oss-paper

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1275085593433735170) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1512
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02232](https://doi.org/10.21105/joss.02232)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@nhejazi, @jjharden - many thanks for your reviews here ✨ 

@erikcs - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02232/status.svg)](https://doi.org/10.21105/joss.02232)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02232">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02232/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02232/status.svg
   :target: https://doi.org/10.21105/joss.02232
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02232/status.svg)](https://doi.org/10.21105/joss.02232)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by erikcs** [comment]
Thank you @arfon for your editorial work, and thank you @jjharden and @nhejazi for improving the package.
