### ISSUE TITLE
[PRE REVIEW]: Methods and Algorithms for Correlation Analysis in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2233]
**Submitting author:** @DominiqueMakowski (<a href="http://orcid.org/0000-0001-5375-9967">Dominique Makowski</a>)
**Repository:** <a href="https://github.com/easystats/correlation" target ="_blank">https://github.com/easystats/correlation</a>
**Version:** v0.2.1
**Editor:** @mikldk
**Reviewers:** @markhwhiteii, @mmrabe
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @DominiqueMakowski. **Currently, there isn't an JOSS editor assigned** to your paper.

@DominiqueMakowski if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.21 s (386.2 files/s, 59066.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            26           1319            317           4979
R                               38            620            520           1524
XML                              1              0             42           1484
Markdown                         3            121              0            427
CSS                              3             79             51            298
JavaScript                       3             41             18            151
Rmd                              3            144            173            122
YAML                             4             27             10            121
TeX                              1              8              0             86
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            83           2359           1132           9203
-------------------------------------------------------------------------------


Statistical information for the repository '2233' was gathered on 2020/05/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel                           1            12              0            5.36
Dominique Makowski               2           205              7           94.64

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Daniel                       12          100.0          0.0               16.67
DominiqueMakowski           198          100.0          0.1                8.08
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.01412 is OK
- 10.21105/joss.01541 is OK
- 10.21105/joss.01686 is OK

MISSING DOIs

- https://doi.org/10.3758/s13428-016-0702-8 may be missing for title: Confidence intervals for correlations when data are not normal
- https://doi.org/10.1093/biomet/48.1-2.29 may be missing for title: Tests for rank correlation coefficients. I

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02233/joss.02233/10.21105.joss.02233.pdf)

**Comment by arfon** [comment]
:wave: @DominiqueMakowski - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by DominiqueMakowski** [comment]
Thanks! We totally understand the 'reduced service' given the situation. Stay safe!

Here are some suggestions for potential reviewers: @gprochilo, @stephenturner, @JosueMA, @taiyun, @kassambara, @AEBilgrau, @cimentadaj, @vsimko, @Nathaniel-Haines 👌

**Comment by cimentadaj** [comment]
Thanks for recommending @DominiqueMakowski. I'm afraid I won't have time to review stuff until the end of June. Feel free to ping me then. Thanks!

**Comment by DominiqueMakowski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02233/joss.02233/10.21105.joss.02233.pdf)

**Comment by markhwhiteii** [comment]
Hi all,

Glad to help review here, but this would be my first time doing a review for JOSS. Is there a specific way this journal does peer-review? What is the typical procedure?

**Comment by arfon** [comment]
:wave: @mikldk - this looks like it might be a reasonable first submission for you. I'll go ahead and add you.

**Comment by arfon** [comment]
@whedon assign @mikldk as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by arfon** [comment]
> Hi all,

> Glad to help review here, but this would be my first time doing a review for JOSS. Is there a specific way this journal does peer-review? What is the typical procedure?

:wave: @markhwhiteii - thanks for being willing to edit this. We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html .

Before the review will start though, the editor (@mikldk) will need to find a second reviewer for this submission.

**Comment by mmrabe** [comment]
👋 Thanks for suggesting me, @DominiqueMakowski. Just in case that @mikldk would consider me as a reviewer, I would be more than happy to review this paper 👀 but unfortunately won’t be available before 29-06-2020.

**Comment by mikldk** [comment]
@whedon assign @markhwhiteii as reviewer

**Comment by whedon** [comment]
OK, @markhwhiteii is now a reviewer

**Comment by mikldk** [comment]
@whedon add @mmrabe as reviewer

**Comment by whedon** [comment]
OK, @mmrabe is now a reviewer

**Comment by mikldk** [comment]
@markhwhiteii, @mmrabe: Thank you very much for agreeing to review. I will init the review issue now.

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2306.
