### ISSUE TITLE
[PRE REVIEW]: WDPM: the Wetland DEM Ponding Model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2234]
**Submitting author:** @KevinShook (<a href="http://orcid.org/0000-0003-0363-9929">Kevin Shook</a>)
**Repository:** <a href="https://github.com/CentreForHydrology/WDPM" target ="_blank">https://github.com/CentreForHydrology/WDPM</a>
**Version:** v1.0.0
**Editor:** @kbarnhart
**Reviewers:** @r-barnes, @awickert, @KCallaghan
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @KevinShook. **Currently, there isn't an JOSS editor assigned** to your paper.

@KevinShook if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.13 s (60.7 files/s, 42276.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                                2            296            208           3294
Python                           1             82            251           1028
OpenCL                           1             23              6            156
TeX                              1             10              0             96
Markdown                         2             32              0             63
JSON                             1              0              0             23
-------------------------------------------------------------------------------
SUM:                             8            443            465           4660
-------------------------------------------------------------------------------


Statistical information for the repository '2234' was gathered on 2020/05/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Kevin Shook                      1          5159              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Kevin Shook                5159          100.0          0.0                9.01
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1002/hyp.8381 is OK
- 10.1002/hyp.9867 is OK
- 10.1016/j.jhydrol.2014.12.014 is OK
- 10.1016/S0022-1694(03)00175-6 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1002/hyp is INVALID
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02234/joss.02234/10.21105.joss.02234.pdf)

**Comment by arfon** [comment]
:wave: @KevinShook - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by KevinShook** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by KevinShook** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02234/joss.02234/10.21105.joss.02234.pdf)

**Comment by KevinShook** [comment]
@whedon generate proof

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by KevinShook** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02234/joss.02234/10.21105.joss.02234.pdf)

**Comment by KevinShook** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1002/hyp.6787 is OK
- 10.1002/hyp.8381 is OK
- 10.1002/hyp.9867 is OK
- 10.1016/j.jhydrol.2014.12.014 is OK
- 10.1016/S0022-1694(03)00175-6 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by KevinShook** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (97.4 files/s, 67783.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                                2            296            208           3294
Python                           1             82            251           1028
OpenCL                           1             23              6            156
TeX                              1             10              0             96
Markdown                         2             32              0             63
JSON                             1              0              0             23
-------------------------------------------------------------------------------
SUM:                             8            443            465           4660
-------------------------------------------------------------------------------


Statistical information for the repository '2234' was gathered on 2020/05/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Kevin Shook                      1          5159              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Kevin Shook                5159          100.0          0.0                9.01
```

**Comment by KevinShook** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02234/joss.02234/10.21105.joss.02234.pdf)

**Comment by KevinShook** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02234/joss.02234/10.21105.joss.02234.pdf)

**Comment by kbarnhart** [comment]
@openjournals/joss-eics I can handle this one.

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by kbarnhart** [comment]
@KevinShook thanks for submitting this to JOSS. If you have any recommendations for reviewers, please post them here (separate @ from handle name, e.g., you would refer to me as @ kbarnhart). Consider the sheet with potential reviewers [linked above](https://bit.ly/joss-reviewers), but don't feel limited to it. It is OK if potential reviewers are not yet on GitHub. I have some initial thoughts for suitable reviewers but am also interested in your input.

**Comment by KevinShook** [comment]
@kbarnhart thanks very much for getting in touch.
I'm afraid that I can't think of anyone who would be good as a reviewer, as everyone I know is either a hydrologist, or a computer scientist (or someone I work with!). Few people straddle both disciplines.
Looking at the list of reviewers, I see that there are about 12 who are comfortable with hydrology, of whom 4 (mlep, dvalters, arbennett, sgrieve) mention C as a preferred or other language. Although the GUI of WDPM was written in Python, it is not necessary to execute the program, so is probably less important.
I see that dvalters is familiar with C, Python and parallel processing, which is very important to this program, so would seem to be a good selection.
I see that there are another 13 parallel processing people, but none of them mention OpenCl.
Did you have some other reviewers in mind as well?

**Comment by kbarnhart** [comment]
👋 @r-barnes @dvalters @laijingtao @awickert, @KCallaghan, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart").

If you are interested in reviewing, I would recommend looking over the journal's conflict of interest policy before the review process starts.

If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by r-barnes** [comment]
Happy to review.

-R

**Comment by awickert** [comment]
I can as well. I might be a bit slow on the uptake for the next few weeks.

**Comment by KCallaghan** [comment]
Sure, this looks interesting.

**Comment by kbarnhart** [comment]
Thanks @r-barnes , @awickert, and @KCallaghan ! 

I'll now add you as reviewers and start the review thread.

**Comment by kbarnhart** [comment]
@whedon assign @r-barnes as reviewer

**Comment by whedon** [comment]
OK, @r-barnes is now a reviewer

**Comment by kbarnhart** [comment]
@whedon add @awickert as reviewer

**Comment by whedon** [comment]
OK, @awickert is now a reviewer

**Comment by whedon** [comment]
OK, @KCallaghan is now a reviewer

**Comment by kbarnhart** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2276.

**Comment by KevinShook** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2234 with the following error: 

 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (a61e06cd2a4edf93b9d570d2/paper/paper.md): found a tab character that violate intendation while scanning a plain scalar at line 18 column 18 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by KevinShook** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02234/joss.02234/10.21105.joss.02234.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02234/joss.02234/10.21105.joss.02234.pdf) :page_facing_up: :point_left:

**Comment by KevinShook** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02234/joss.02234/10.21105.joss.02234.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02234/joss.02234/10.21105.joss.02234.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @KevinShook! You can test out your paper compilation, see here: https://joss.readthedocs.io/en/latest/submitting.html#checking-that-your-paper-compiles

**Comment by KevinShook** [comment]
Thanks - wasn't sure where to be running the whedon commands

**Comment by kthyng** [comment]
You can always just run the generate pdf command in the review issue too.
