### ISSUE TITLE
[PRE REVIEW]: AutoFunc: A Python package for automating and verifying functional modeling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2235]
**Submitting author:** @AlexMikes (<a href="http://orcid.org/0000-0002-7873-5758">Alex Mikes</a>)
**Repository:** <a href="https://github.com/AlexMikes/AutoFunc" target ="_blank">https://github.com/AlexMikes/AutoFunc</a>
**Version:** v0.2.1
**Editor:** @gkthiruvathukal
**Reviewers:** @cmccomb, @e-dub
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @AlexMikes. **Currently, there isn't an JOSS editor assigned** to your paper.

@AlexMikes if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (575.0 files/s, 52936.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          26            765            701           1291
Markdown                         3             48              0            122
TeX                              1              9              0             74
YAML                             2              2              0             19
XML                              1              0              0              7
-------------------------------------------------------------------------------
SUM:                            33            824            701           1513
-------------------------------------------------------------------------------


Statistical information for the repository '2235' was gathered on 2020/05/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
AlexMikes                       67          7561           4804          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
AlexMikes                  2757           36.5          3.1               18.06
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1115/1.1625400 is OK
- 10.1115/1.1289637 is OK
- 10.5281/zenodo.3694300 is OK

MISSING DOIs

- https://doi.org/10.1007/s00163-001-0008-3 may be missing for title: A functional basis for engineering design: Reconciling and evolving previous efforts

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02235/joss.02235/10.21105.joss.02235.pdf)

**Comment by arfon** [comment]
:wave: @AlexMikes - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by AlexMikes** [comment]
> @AlexMikes if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @).

Kyle Niemeyer

**Comment by danielskatz** [comment]
I'm fairly sure Kyle has a conflict with reviewing this - can you suggest other reviewers?

**Comment by danielskatz** [comment]
👋 @gkthiruvathukal - Are you able to edit this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon invite @gkthiruvathukal as editor

**Comment by whedon** [comment]
@gkthiruvathukal has been invited to edit this submission.

**Comment by gkthiruvathukal** [comment]
@danielskatz Yes, I will do it.

**Comment by gkthiruvathukal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by gkthiruvathukal** [comment]
@danielskatz Just to clarify the workflow, when I am invited, if I agree, do I just assign myself as the editor, if I want to accept the invitation?

**Comment by danielskatz** [comment]
yes, exactly - you do ```@whedon assign @gkthiruvathukal as editor```

**Comment by gkthiruvathukal** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
@AlexMikes, can you please take a look at https://bit.ly/joss-reviewers and suggest potential reviewers? Please don't use the @ symbol to mention them. I'll mention those who I want to invite to participate in the review and will throw in others as needed. Thanks!

**Comment by AlexMikes** [comment]
> @AlexMikes, can you please take a look at https://bit.ly/joss-reviewers and suggest potential reviewers? Please don't use the @ symbol to mention them. I'll mention those who I want to invite to participate in the review and will throw in others as needed. Thanks!

I have identified two. Usernames `cmccomb` and `e-dub`. Let me know if I should find more. Thanks.

**Comment by gkthiruvathukal** [comment]
Thanks, @AlexMikes, especially for your patience as I get the review going.

**Comment by gkthiruvathukal** [comment]
@whedon invite @cmscomb as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by gkthiruvathukal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by gkthiruvathukal** [comment]
@cmccomb and @e-dub, Would you be willing to contribute a review for this JOSS submission?

**Comment by cmccomb** [comment]
Sure, count me in @gkthiruvathukal!

**Comment by e-dub** [comment]
> @cmccomb and @e-dub, Would you be willing to contribute a review for this JOSS submission?

I am in!

**Comment by gkthiruvathukal** [comment]
@whedon assign @cmccomb as reviewer

**Comment by whedon** [comment]
OK, @cmccomb is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon add @e-dub as reviewer

**Comment by whedon** [comment]
OK, @e-dub is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2362.
