### ISSUE TITLE
[PRE REVIEW]: ObsPlus: A Pandas Centric ObsPy Expansion Pack

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2236]
**Submitting author:** @d-chambers (<a href="http://orcid.org/0000-0003-3656-6607">Derrick Chambers</a>)
**Repository:** <a href="https://github.com/niosh-mining/obsplus" target ="_blank">https://github.com/niosh-mining/obsplus</a>
**Version:** v0.1.0
**Editor:** @leouieda
**Reviewers:** @seisman, @ThomasLecocq
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @d-chambers. **Currently, there isn't an JOSS editor assigned** to your paper.

@d-chambers if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1088/1749-4699/8/1/014003 may be missing for title: ObsPy: A bridge for seismology into the scientific Python ecosystem

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.12 s (161.9 files/s, 133123.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                             26              0              0         110459
Python                         110           4606           8325          16698
SVG                              3              3              3           1993
JSON                             4              0              0           1651
Jupyter Notebook                21              0           3365            567
YAML                             8             65             50            313
DOS Batch                        1             29              1            212
make                             1             28              6            143
Markdown                         3             49              0             97
reStructuredText                 3             49             47             34
TeX                              1              2              0             16
-------------------------------------------------------------------------------
SUM:                           181           4831          11797         132183
-------------------------------------------------------------------------------


Statistical information for the repository '2236' was gathered on 2020/05/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Calum Chamberlain                4           497            130            1.04
Derrick                         82         23297          14147           62.29
Derrick Chambers                10         15514             13           25.83
Shawn                            7          1176            511            2.81
Shawn Boltz                     12          2423            852            5.45
derrick                          8            98             51            0.25
isti_ew                          1             9              9            0.03
sboltz                           7          1235             92            2.21
sjohnson5                        1            54              4            0.10

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Calum Chamberlain           347           69.8          9.9               14.99
Derrick                   16690           71.6          5.0               16.02
Shawn                      1773          150.8         11.0               12.30
derrick                   10798        11018.4         18.2               16.48
sjohnson5                    21           38.9         16.5               19.05
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02236/joss.02236/10.21105.joss.02236.pdf)

**Comment by arfon** [comment]
:wave: @leouieda - I realize you're busy until early June but this looks like a good fit for you when you're available again. As such, I'll go ahead and assign this to you. Any concerns, just let me know.

**Comment by arfon** [comment]
@whedon assign @leouieda as editor

**Comment by whedon** [comment]
OK, the editor is @leouieda

**Comment by arfon** [comment]
:wave: @d-chambers - the handling editor is going to be busy for the next couple of weeks but should be able to pick this up then. Your patience is appreciated!

**Comment by d-chambers** [comment]
Ok great, thanks @arfon and @leouieda

**Comment by leouieda** [comment]
Hi @arfon I'm happy to edit this paper :+1:

@d-chambers I'll be a bit more free next week and will start looking over the paper then. Thank you for your patience :slightly_smiling_face:

**Comment by leouieda** [comment]
@d-chambers apologies for the delay in getting this started. I've been going over the paper and code and have a few comments. These are mostly issues you could start working on in the mean time which are very likely to be raised during review:

* Add a citation to pandas in the paper
* Link to the contributing guide on the README
* Add instructions for running your tests (reviewers will likely want to do this)
* I found example usage in the [Introduction](https://niosh-mining.github.io/obsplus/versions/latest/notebooks/intro.html) page but that took a bit of digging since it wasn't clear from the heading and link texts that these were examples, not API reference documentation.

I'll start inviting reviewers but this will give you a bit of a head start.

**Comment by leouieda** [comment]
:wave: @megies @anowacki @seisman would you be willing to review this submission for [JOSS](https://joss.theoj.org/)? Reviews are done entirely through GitHub (issues and pull requests). These are the reviewer guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue in which I will assign reviewers. Once there are sufficient reviewers (usually 2-3), I will open a new issue where the review will take place. If you agree to review, you will be notified when the review process if formally started.

If you are not able to review at this time, please let me know if you have recommendations for other reviewers. **Please recommend without mentioning a handle to avoid notifying the person** (e.g., you would refer to me as leouieda instead of @leouieda). This way we attempt to reduce the number of people who are subscribed to this thread.

**Comment by seisman** [comment]
@leouieda I'm willing to review it. Please assign it to me.

**Comment by leouieda** [comment]
Thank you @seisman 👍🏽

**Comment by leouieda** [comment]
@whedon assign @seisman as reviewer

**Comment by whedon** [comment]
OK, @seisman is now a reviewer

**Comment by megies** [comment]
@leouieda I'm actually not using pandas a lot, so maybe there could be better options. Maybe @thomaslecocq? But if no other people come forward I can be a backup.

**Comment by leouieda** [comment]
Thanks, @megies. I'll keep let you know if no one else is available.

**Comment by leouieda** [comment]
@ThomasLecocq would be willing to review this submission for JOSS?

**Comment by anowacki** [comment]
@leouieda Apologies, I'm afraid I don't think I would be useful here, so I would be grateful if you were able to find another reviewer.

(I should update the list of things on the reviewers spreadsheet to reflect the fact that I don't  really use Python any more, have never used Pandas, and so can't give much in the way of a helpful review.)

**Comment by d-chambers** [comment]
@leouieda 
Thanks for the pre-review comments. I believe I have addressed the concerns you raised.

**Comment by leouieda** [comment]
@d-chambers thank you for implementing the changes. I'll search for a second reviewer a little longer still. Unfortunately, I'll be out of office until September but will resume as soon as I get back. I appreciate your patience these past months.

@anowacki thank you for the quick response 👍

**Comment by leouieda** [comment]
👋🏽 Hi @lheagy would you be interested in reviewing this submission? I know it's a bit outside your field but I would appreciate your perspective on this.

**Comment by ThomasLecocq** [comment]
Heyyyyyyyyyyyyyyy seems I was ping'ed here 👍 
I can do it !

**Comment by lheagy** [comment]
Hi @leouieda, thanks for thinking of me -- this looks like an interesting project! I am pretty loaded at the moment unfortunately, so I don't have the bandwidth to take this on. I wonder if, given the focus on the #subsurface channel of Swung on interoperability between software packages / data representations (xarray, pandas, etc), if there would be someone there who would be interested?

**Comment by leouieda** [comment]
Thanks @ThomasLecocq! I’ll assign you to the review as well.

@lheagy thank you for the suggestion! I’ll ask there and see if I can get a third reviewer from outside seismology to comment on the integration. If not, then I’ll proceed with two reviewers.

**Comment by leouieda** [comment]
I haven't able to get a third reviewer so we'll move forward with @seisman and @ThomasLecocq as reviewers. 

@d-chambers apologies for the delay with this submission.

**Comment by leouieda** [comment]
@whedon add @ThomasLecocq as reviewer

**Comment by whedon** [comment]
OK, @ThomasLecocq is now a reviewer

**Comment by leouieda** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02236/joss.02236/10.21105.joss.02236.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02236/joss.02236/10.21105.joss.02236.pdf) :page_facing_up: :point_left:

**Comment by leouieda** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2696.
