### ISSUE TITLE
[PRE REVIEW]: spiR, An R package to access social progress data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2237]
**Submitting author:** @warint (<a href="http://orcid.org/0000-0002-5921-3428">Thierry Warin</a>)
**Repository:** <a href="https://github.com/warint/spiR" target ="_blank">https://github.com/warint/spiR</a>
**Version:** v0.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @warint. **Currently, there isn't an JOSS editor assigned** to your paper.

@warint if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2237 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2237 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02237/joss.02237/10.21105.joss.02237.pdf)

**Comment by arfon** [comment]
:wave: @warint - Thanks for your submission to JOSS. From a quick inspection of the repository, it looks like there's little/no software actually present. Could you clarify where the software is located?

Additionally, as described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by warint** [comment]
Please find the R package here: https://github.com/warint/spiR

Thanks,

Th.

**Comment by arfon** [comment]
Thanks @warint. It's better for JOSS if the paper is in the same repository as the software, perhaps under the vignettes. Is this something you'd be willing to do?

**Comment by warint** [comment]
Oh, yes, sure, sorry.

I just put the joss article in vignettes > joss on https://github.com/warint/spiR

Do I need to do anything else?

Sorry about that again,

Thanks a ton for your help,

Th.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02237/joss.02237/10.21105.joss.02237.pdf)

**Comment by arfon** [comment]
> Do I need to do anything else?

Perfect, thanks! Now we'll just need to wait a little while until we've worked through the backlog of submissions.

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (472.8 files/s, 99955.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            19            864            227           2764
XML                              1              0             42           1505
TeX                              2            101              0           1303
CSS                              3             99             48            428
Markdown                         5             87              0            271
JavaScript                       3             64             32            256
R                                1             46            144             77
Rmd                              2             85             88             49
YAML                             4             19              8             48
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            41           1365            590           6712
-------------------------------------------------------------------------------


Statistical information for the repository '2237' was gathered on 2020/06/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Martin Paquette                  1           198              0           54.70
Thierry Warin                    1           159              5           45.30

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Martin Paquette             193           97.5          0.0                8.29
Thierry Warin               159          100.0          0.0               10.06
```

**Comment by arfon** [comment]
:wave: @warint - thanks for your submission to JOSS. After discussing this with the JOSS editorial team, we have concluded that this submission is out of scope due to its _minor utility_ nature (https://joss.readthedocs.io/en/latest/submitting.html).

Thanks again for your interest in JOSS.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
