### ISSUE TITLE
[PRE REVIEW]: Flint: a simulator for biological and physiological models in ordinary and stochastic differential equations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2238]
**Submitting author:** @tabe (<a href="http://orcid.org/0000-0002-7074-4561">Takeshi Abe</a>)
**Repository:** <a href="https://github.com/flintproject/Flint" target ="_blank">https://github.com/flintproject/Flint</a>
**Version:** v2.3.0
**Editor:** @majensen
**Reviewers:** @funasoul, @mstimberg
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @tabe. **Currently, there isn't an JOSS editor assigned** to your paper.

@tabe if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2238 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2238 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3389/fphys.2015.00251 is OK
- 10.1016/j.pbiomolbio.2004.01.004 is OK
- 10.1093/bioinformatics/btg015 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
:wave: @tabe - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02238/joss.02238/10.21105.joss.02238.pdf)

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.69 s (530.5 files/s, 112731.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                   491          16060          22236          88052
C++                            243           4844            707          39194
XML                             16              1              0           5828
Bourne Shell                     2            101            386           2971
m4                               5            259             56           2055
Scheme                          39            126             42           1786
make                            49            414             10           1725
CMake                           24             95             11            991
C                                9            123             18            873
TeX                              5            111              7            567
Protocol Buffers                 6            168             10            447
diff                             6             45            165            395
Markdown                         2             18              0             84
YAML                             2             17              1             51
-------------------------------------------------------------------------------
SUM:                           899          22382          23649         145019
-------------------------------------------------------------------------------


Statistical information for the repository '2238' was gathered on 2020/05/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Takeshi Abe                   1094        467536         239623          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Takeshi Abe              172107           36.8         43.3               13.79
```

**Comment by kyleniemeyer** [comment]
Hi @majensen, do you have the bandwidth to take this one?

**Comment by kyleniemeyer** [comment]
@whedon invite @majensen as editor

**Comment by whedon** [comment]
@majensen has been invited to edit this submission.

**Comment by majensen** [comment]
@whedon assign @majensen as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by majensen** [comment]
@tabe this looks like a very interesting and useful application. Can you suggest a few people who would be qualified to review this work? It would be very helpful.

**Comment by tabe** [comment]
@majensen Is there a list of JOSS's possible reviewers?  If any, I could tell some relevant ones in it.

**Comment by majensen** [comment]
Definitely @tabe - have a look at [this google sheet](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78)

**Comment by tabe** [comment]
@majensen Thanks a lot.  dawbarton, PrashantVaidyanathan, and mstimberg look relevant among those who declare C++ expertise.

**Comment by tabe** [comment]
@majensen I have a question, is it possible to recommend some scholars who has their GitHub accounts but are not included in the above list as reviewers?  For example, researchers in the SBML,  CellML, or physiome community will be a good fit.

**Comment by majensen** [comment]
That would be very welcome @tabe , JOSS is always looking for new reviewers.

**Comment by tabe** [comment]
@majensen I recommend Dr Akira Funahashi @funasoul from the SBML team would be one of the best reviewer candidates.

**Comment by majensen** [comment]
Hello @funasol -- would you be willing to review this work for [JOSS](https://joss.theoj.org)? I would welcome your assistance on this work on  [Flint](https://github.com/flintproject/Flint) by @tabe. 
The review process is fully open and outlined [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). Thanks for your consideration!  --@majensen

**Comment by funasoul** [comment]
Hi @majensen 
Thank you for the invitation. I would be happy to accept a peer review.

**Comment by majensen** [comment]
@whedon assign @funasoul as reviewer

**Comment by whedon** [comment]
OK, @funasoul is now a reviewer

**Comment by majensen** [comment]
Hello @mstimberg - Would you be willing to review this work by @tabe on [Flint](https://github.com/flintproject/Flint) - a DE modeling package in C++ - for [JOSS](https://joss.theoj.org)? I would really appreciate your expertise here. Thanks for considering -
-- @majensen

**Comment by mstimberg** [comment]
Hi @majensen, looks very interesting, would be happy to review it!

**Comment by majensen** [comment]
@whedon add @mstimberg as reviewer

**Comment by whedon** [comment]
OK, @mstimberg is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2331.

**Comment by majensen** [comment]
@tabe @funasoul @mstimberg looking forward to the review over at issue #2331 - thanks for your time and contribution!
