### ISSUE TITLE
[PRE REVIEW]: xrdfit: A Python package for fitting synchrotron X-ray diffraction spectra

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2240]
**Submitting author:** @merrygoat (<a href="http://orcid.org/0000-0002-5430-6924">Peter Crowther</a>)
**Repository:** <a href="https://github.com/LightForm-group/xrdfit" target ="_blank">https://github.com/LightForm-group/xrdfit</a>
**Version:** v1.0.0
**Editor:** @jgostick
**Reviewers:** @KedoKudo
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @merrygoat. **Currently, there isn't an JOSS editor assigned** to your paper.

@merrygoat if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (225.9 files/s, 44609.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5            166            364            607
SVG                              2              2              2            481
Jupyter Notebook                 4              0           1787            343
TeX                              1             14              1            143
Markdown                         4             47              0             93
reStructuredText                 3             32             24             30
YAML                             1              2              1              7
HTML                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            21            263           2179           1705
-------------------------------------------------------------------------------


Statistical information for the repository '2240' was gathered on 2020/05/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Christopher Daniel               3           771             19            6.90
Peter Crowther                 134          5520           5135           93.10

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Christopher Daniel            8            1.0          0.0               12.50
Peter Crowther             1129           20.5          3.5               16.30
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/ZENODO.11813 is OK
- 10.1016/j.msea.2008.05.017 is OK
- 10.3390/met5042252 is OK
- 10.1016/j.msea.2016.01.059 is OK
- 10.1016/j.actamat.2017.04.028 is OK
- 10.1107/s1600576717004708 is OK
- 10.1107/s1600576715004306 is OK
- 10.1107/s1600577515002283 is OK
- 10.1107/s1600576715010390 is OK
- 10.1080/08957959608201408 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
:wave: @merrygoat - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02240/joss.02240/10.21105.joss.02240.pdf)

**Comment by kyleniemeyer** [comment]
Hi @jgostick, would this be a bit closer to your area of expertise to edit?

**Comment by kyleniemeyer** [comment]
@whedon invite @jgostick as editor

**Comment by whedon** [comment]
@jgostick has been invited to edit this submission.

**Comment by jgostick** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by jgostick** [comment]
@whedon assign @jgostick as editor

**Comment by whedon** [comment]
OK, the editor is @jgostick

**Comment by kyleniemeyer** [comment]
Thanks @jgostick!

**Comment by jgostick** [comment]
@whedon invite @KedoKudo as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by arfon** [comment]
> @whedon invite @KedoKudo as reviewer

@jgostick - Whedon doesn't know how to invite reviewers like this yet sorry. If you want to invite @KedoKudo as a reviewer you can either do that in an email (e.g. [like this](https://joss.readthedocs.io/en/latest/editing.html#sample-email-to-potential-reviewers)) or just by mentioning them here.

**Comment by jgostick** [comment]
This email template is what I needed.  Will send asap.  It'd be sweet if Whedon could send this though!

**Comment by jgostick** [comment]
@whedon assign @KedoKudo as reviewer

**Comment by whedon** [comment]
OK, @KedoKudo is now a reviewer

**Comment by jgostick** [comment]
Hi @KedoKudo, do you need any help getting going on your review?  I'm still looking for a second reviewer to add, but you can get started.

**Comment by arfon** [comment]
> Hi @KedoKudo, do you need any help getting going on your review? I'm still looking for a second reviewer to add, but you can get started.

@jgostick - if you'd like to start the review with one reviewer (which is fine as long is there is a second one later), you should probably move this forward to the review stage where @KedoKudo will have a checklist and guidelines to work through. You can do this with `@whedon start review`

**Comment by jgostick** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2381.
