### ISSUE TITLE
[REVIEW]: Hypothesize: Robust Statistics for Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2241]
**Submitting author:** @Alcampopiano (<a href="http://orcid.org/0000-0002-3280-4447">Allan Campopiano</a>)
**Repository:** <a href="https://github.com/Alcampopiano/hypothesize" target ="_blank">https://github.com/Alcampopiano/hypothesize</a>
**Version:** v1.1.0
**Editor:** @csoneson
**Reviewer:** @martinagvilas, @arbennett
**Archive:** <a href="https://doi.org/10.5281/zenodo.3900100" target="_blank">10.5281/zenodo.3900100</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/caf4095b3cdcc3adbb0252c995d59926/status.svg)](https://joss.theoj.org/papers/caf4095b3cdcc3adbb0252c995d59926)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/caf4095b3cdcc3adbb0252c995d59926"><img src="https://joss.theoj.org/papers/caf4095b3cdcc3adbb0252c995d59926/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/caf4095b3cdcc3adbb0252c995d59926/status.svg)](https://joss.theoj.org/papers/caf4095b3cdcc3adbb0252c995d59926)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Alcampopiano/hypothesize" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@martinagvilas & @arbennett, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [X] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [X] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [X] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Alcampopiano/hypothesize">repository url</a>?
- [X] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [X] **Contribution and authorship:** Has the submitting author (@Alcampopiano) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [X] **Installation:** Does installation proceed as outlined in the documentation?
- [X] **Functionality:** Have the functional claims of the software been confirmed?
- [X] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [X] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [X] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [X] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [X] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [X] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [X] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [X] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [X] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [X] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [X] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [X] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Alcampopiano/hypothesize">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Alcampopiano) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @martinagvilas, @arbennett it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

-  10.1037/0003-066X.53.3.300  is OK
-  10.1016/c2010-0-67044-1  is OK
-  10.1038/s41592-019-0470-3  is OK
-  10.25080/Majora-92bf1922-00a  is OK

MISSING DOIs

- https://doi.org/10.25080/majora-92bf1922-011 may be missing for title: statsmodels: Econometric and statistical modeling with python

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02241/joss.02241/10.21105.joss.02241.pdf)

**Comment by csoneson** [comment]
👋  @martinagvilas, @arbennett - thanks for accepting to review this submission! This is the review issue. Please have a look at the instructions above, and don't hesitate to ping me if anything is unclear or if you have questions.

**Comment by Alcampopiano** [comment]
The missing DOI suggested above has been verified and added.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02241/joss.02241/10.21105.joss.02241.pdf)

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

-  10.1037/0003-066X.53.3.300  is OK
-  10.1016/c2010-0-67044-1  is OK
-  10.25080/majora-92bf1922-011  is OK
-  10.1038/s41592-019-0470-3  is OK
-  10.25080/Majora-92bf1922-00a  is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by martinagvilas** [comment]
Thanks @Alcampopiano! 

@csoneson all my issues have been addressed, so I recommend the acceptance of Hypothesize.

**Comment by csoneson** [comment]
Thank you @martinagvilas!

**Comment by csoneson** [comment]
@arbennett - could you give a quick update on the status of your review? Of course, don't hesitate to ask if you have any questions. Thanks!

**Comment by arbennett** [comment]
@csoneson - apologies for slowness, I have not yet started the review because of current events, but should be able to do so within the next week or so.

**Comment by Alcampopiano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02241/joss.02241/10.21105.joss.02241.pdf)

**Comment by arbennett** [comment]
Hypothesize is a well designed library with a clear and well defined scope as well as functionality that does not appear to exist in other Python packages. I think this is a good contribution and a good fit to be published in JOSS after some minor modifications.

I really enjoyed how clean the documentation and structure of the code is. I had almost no trouble installing and getting started with hypothesize. The only functional issue that I had was three minor points on testing. I have opened issues [here](https://github.com/Alcampopiano/hypothesize/issues/7) and [here](https://github.com/Alcampopiano/hypothesize/issues/8) describing these issues.

Additionally, I think that some of the text in the paper could be elaborated on and expanded to make it clearer why user should use hypothesize over some of the other referenced packages, and a bit more information about what is actually implemented in hypothesize. Most of this _is_ found in the documentation, but I think it would also be useful to include in the paper itself. I have opened an issue [here](https://github.com/Alcampopiano/hypothesize/issues/9) specifically describing my suggestions.

**Comment by csoneson** [comment]
Thank you @arbennett!

**Comment by Alcampopiano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02241/joss.02241/10.21105.joss.02241.pdf)

**Comment by Alcampopiano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02241/joss.02241/10.21105.joss.02241.pdf)

**Comment by csoneson** [comment]
@Alcampopiano - I see that you have closed the issues raised by @arbennett above, and there was a confirmation from @arbennett in at least one of them. Could you both please confirm if you consider these issues to be satisfactorily addressed and we should go ahead with accepting the submission, or if there are still open issues? Thanks!

**Comment by arbennett** [comment]
@Alcampopiano thanks for the quick responses!

@csoneson in my view this is ready to be accepted!

**Comment by Alcampopiano** [comment]
@csoneson I believe that the reviewers and myself have addressed all of the issues at this point.

**Comment by csoneson** [comment]
Great, thanks to all of you! I will have a quick look through the paper and get back to you shortly with the next steps.

**Comment by Alcampopiano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02241/joss.02241/10.21105.joss.02241.pdf)

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

-  10.1037/0003-066X.53.3.300  is OK
-  10.1016/c2010-0-67044-1  is OK
-  10.25080/majora-92bf1922-011  is OK
-  10.1038/s41592-019-0470-3  is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.21105/joss.01026 is OK

MISSING DOIs

- https://doi.org/10.1093/biomet/77.3.663 may be missing for title: A sequentially rejective test procedure based on a modified Bonferroni inequality
- https://doi.org/10.1093/biomet/75.4.800 may be missing for title: A sharper Bonferroni procedure for multiple tests of significance
- https://doi.org/10.1111/j.2517-6161.1995.tb02031.x may be missing for title: Controlling the false discovery rate: a practical and powerful approach to multiple testing

INVALID DOIs

- None
```

**Comment by Alcampopiano** [comment]
Hello @csoneson,

Are you able to check the references again when you have a chance (I don't believe I can ask Whedon to do that)? I have attempted to fix the missing DOIs.

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

-  10.1037/0003-066X.53.3.300  is OK
-  10.1016/c2010-0-67044-1  is OK
-  10.25080/majora-92bf1922-011  is OK
-  10.1038/s41592-019-0470-3  is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.21105/joss.01026 is OK
- 10.1093/biomet/77.3.663 is OK
- 10.1093/biomet/75.4.800 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1111/j.2517-6161.1995.tb02031.x is INVALID because of 'https://doi.org/' prefix
```

**Comment by Alcampopiano** [comment]
@csoneson Thank you. I could not get the last one to resolve in an online DOI checker, so I added the full URL. That is invalid, which makes sense. 

Okay, I've added the DOI as Whedon has suggested and I hope that will work.

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

-  10.1037/0003-066X.53.3.300  is OK
-  10.1016/c2010-0-67044-1  is OK
-  10.25080/majora-92bf1922-011  is OK
-  10.1038/s41592-019-0470-3  is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.21105/joss.01026 is OK
- 10.1093/biomet/77.3.663 is OK
- 10.1093/biomet/75.4.800 is OK
- doi.org/10.1111/j.2517-6161.1995.tb02031.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02241/joss.02241/10.21105.joss.02241.pdf)

**Comment by csoneson** [comment]
@Alcampopiano - Could you make the following small fixes to the references:
* the DOI for Benjamini & Hochberg (1995) should not contain `doi.org/`
* Benjamini & Hochberg (1995) is missing an "i" in Benjamini
* There seem to be spaces in the DOIs for Ho et al (2019), McKinney (2010), Seabold & Perktold (2010), Wilcox (1998) and Wilcox (2013)
* Hochberg (1988) and Rom (1990) need case protection in the title to keep the capital B in Bonferroni
* For consistency, please write out the full journal name also for Benjamini & Hochberg (1995) and check the capitalization of journal names. 
Note that if you click on the article proof above and then download the pdf, you can check that the DOI links work by clicking on them directly in the bibliography.

**Comment by Alcampopiano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02241/joss.02241/10.21105.joss.02241.pdf)

**Comment by Alcampopiano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02241/joss.02241/10.21105.joss.02241.pdf)

**Comment by Alcampopiano** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02241/joss.02241/10.21105.joss.02241.pdf)

**Comment by Alcampopiano** [comment]
@csoneson Thank you for pointing out the various things to fix and check in the reference section.

I believe I have addressed each of the points listed above (and I have verified that each DOI is valid by clicking on them in the proof).

**Comment by csoneson** [comment]
@Alcampopiano - great, thanks for making those edits! I found one more detail - in "Bradley & Tibshirani (1993)", Bradley Efron's first name and surname have been swapped - it should be "Efron & Tibshirani (1993)". Could you fix that too?

The next steps: 
- [ ] Make a tagged release of the software and list the version tag of the archived version here.
- [ ] Archive the software in Zenodo.
- [ ] Check the metadata of the Zenodo archive - it should have exactly the same title and authors as the paper. You can also add authors' ORCiD there if you want.
- [ ] Report the DOI of the Zenodo archive here

**Comment by Alcampopiano** [comment]
Hello @csoneson,

Thank you very much for your incredibly careful eye on the paper. I have fixed the citation so that the name appears correctly. 

In addition:

- I have made a tagged release: `v1.1.0`
- I have archived that release in Zenodo
- The title and authors in the paper match Zenodo's corresponding metatdata exactly
- Zenodo DOI: http://doi.org/10.5281/zenodo.3900100

Please let me know if you need anything else.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02241/joss.02241/10.21105.joss.02241.pdf)

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1037/0003-066X.53.3.300 is OK
- 10.1016/c2010-0-67044-1 is OK
- 10.25080/majora-92bf1922-011 is OK
- 10.1038/s41592-019-0470-3 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.21105/joss.01026 is OK
- 10.1093/biomet/77.3.663 is OK
- 10.1093/biomet/75.4.800 is OK
- 10.1111/j.2517-6161.1995.tb02031.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@whedon set 10.5281/zenodo.3900100 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3900100" target="_blank">10.5281/zenodo.3900100</a> is the archive.

**Comment by csoneson** [comment]
@whedon set v1.1.0 as version

**Comment by whedon** [comment]
OK. v1.1.0 is the version.

**Comment by csoneson** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1037/0003-066X.53.3.300 is OK
- 10.1016/c2010-0-67044-1 is OK
- 10.25080/majora-92bf1922-011 is OK
- 10.1038/s41592-019-0470-3 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.21105/joss.01026 is OK
- 10.1093/biomet/77.3.663 is OK
- 10.1093/biomet/75.4.800 is OK
- 10.1111/j.2517-6161.1995.tb02031.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1496

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1496, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by csoneson** [comment]
@Alcampopiano - thanks for making these changes. The Associate Editor-in-Chief on duty this week will take over from here!

**Comment by Alcampopiano** [comment]
@csoneson I really appreciate all of your hard work in general and on this paper. Take care.

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1274075670138826752) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1505
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02241](https://doi.org/10.21105/joss.02241)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@martinagvilas, @arbennett - many thanks for your reviews here and to @csoneson for editing this submission ✨ 

@Alcampopiano - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02241/status.svg)](https://doi.org/10.21105/joss.02241)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02241">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02241/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02241/status.svg
   :target: https://doi.org/10.21105/joss.02241
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02241/status.svg)](https://doi.org/10.21105/joss.02241)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by Alcampopiano** [comment]
@martinagvilas @arbennett @csoneson @arfon 

Publishing in JOSS was an incredibly positive experience for me. My sincerest thanks to you all. I really appreciate all of your hard work. I made sure to acknowledged Whedon in the paper too :).
