### ISSUE TITLE
[PRE REVIEW]: ExoTiC-ISM: A Python package for marginalised exoplanet transit parameters across a grid of systematic instrument models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2242]
**Submitting author:** @ivalaginja (<a href="http://orcid.org/0000-0003-1783-5023">Iva Laginja</a>)
**Repository:** <a href="https://github.com/hrwakeford/ExoTiC-ISM" target ="_blank">https://github.com/hrwakeford/ExoTiC-ISM</a>
**Version:** v1.1.0
**Editor:** @xuanxu
**Reviewers:** @hayesla, @mattpitkin
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ivalaginja. **Currently, there isn't an JOSS editor assigned** to your paper.

@ivalaginja if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by arfon** [comment]
:wave: @ivalaginja - thanks for your submission to JOSS. Does this paper accompany a paper in a AAS journal?

**Comment by whedon** [comment]
PDF failed to compile for issue #2242 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2242 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2242 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02242/joss.02242/10.21105.joss.02242.pdf)

**Comment by arfon** [comment]
:wave: @xuanxu - would you be able to edit this submission for JOSS?

**Comment by arfon** [comment]
@ivalaginja @xuanxu - just a heads up that this repository is very large (lots of data files) so Whedon may struggle to work properly here and may need some manual work on my side.

**Comment by ivalaginja** [comment]
@arfon thanks! No, this paper does not accompany a paper in any AAS journal. We tried to reduce the repository size by cleaning out the history before submission, but with limited success. If there is anything that can be done from our side concerning that issue, please let me know.

**Comment by arfon** [comment]
OK, thanks for letting me know. Next step here is for @xuanxu to pick this up (assuming he's able to).

**Comment by xuanxu** [comment]
:wave: I can take this

**Comment by xuanxu** [comment]
@whedon assign @xuanxu as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by xuanxu** [comment]
:wave: @hayesla & @nespinoza - would you be willing to review this submission for JOSS?  
I think your knowledge of Python and astrophysics/exoplanets makes both of you a great fit for this submission.

**Comment by ivalaginja** [comment]
I had to update the author affiliations so I will regenerate the PDF

**Comment by ivalaginja** [comment]
@whedon generate pdf

**Comment by ivalaginja** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2242 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/compilers.rb:158:in `initialize': No such file or directory @ rb_sysopen - tmp/2242/paper/markdown-metadata.yaml (Errno::ENOENT)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/compilers.rb:158:in `open'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/compilers.rb:158:in `pdf_from_markdown'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/compilers.rb:13:in `generate_pdf'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:56:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by ivalaginja** [comment]
@arfon you mentioned these sort of errors can happen since the repository is so large. Mind giving us a hand?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02242/joss.02242/10.21105.joss.02242.pdf)

**Comment by arfon** [comment]
Looks like Whedon got there eventually :-)

**Comment by nespinoza** [comment]
Hi everyone! Sadly, can't right now as my schedule is quite full for the next month or so :(.

**Comment by hayesla** [comment]
> 👋 @hayesla & @nespinoza - would you be willing to review this submission for JOSS?
> I think your knowledge of Python and astrophysics/exoplanets makes both of you a great fit for this submission.

@xuanxu  yes I'm happy to review this 👍

**Comment by xuanxu** [comment]
@nespinoza: No problem!

@hayesla: Great, thanks! Once I have the second reviewer I'll start a new issue where the actual review will take place. Stay tuned!

**Comment by xuanxu** [comment]
:wave: @HeloiseS - would you be willing to review this submission for JOSS?
Your expertise with Python and astrophysics would come in handy.

**Comment by xuanxu** [comment]
:wave: @mattpitkin - would you be willing to review this submission for JOSS?

**Comment by mattpitkin** [comment]
@xuanxu Yes, I can review this.

**Comment by xuanxu** [comment]
@mattpitkin Great, thanks! 
I'll assign you now and start the review issue.

**Comment by xuanxu** [comment]
@whedon add @hayesla as reviewer

**Comment by whedon** [comment]
OK, @hayesla is now a reviewer

**Comment by xuanxu** [comment]
@whedon add @mattpitkin as reviewer

**Comment by whedon** [comment]
OK, @mattpitkin is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2281.

**Comment by xuanxu** [comment]
@hayesla & @mattpitkin: please head over to #2281 where the review will take place.
