### ISSUE TITLE
[PRE REVIEW]: geemap: A Python package for interactive mapping with Google Earth Engine

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2244]
**Submitting author:** @giswqs (<a href="http://orcid.org/0000-0001-5437-4073">Qiusheng Wu</a>)
**Repository:** <a href="https://github.com/giswqs/geemap" target ="_blank">https://github.com/giswqs/geemap</a>
**Version:** v0.7.0
**Editor:** @hugoledoux
**Reviewers:** @fbiljecki, @steflhermitte
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @giswqs. **Currently, there isn't an JOSS editor assigned** to your paper.

@giswqs if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.43 s (258.2 files/s, 61794.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          19           1951           1848           6716
Jupyter Notebook                57              0          10631           3007
reStructuredText                13            366            250            386
JSON                             3              0              0            234
Markdown                         4             73              0            145
TeX                              1              8              0            142
HTML                             2             19              0            135
make                             2             24              6             75
JavaScript                       5             29             65             72
YAML                             2              4             19             69
DOS Batch                        1              8              1             27
INI                              1              4              0             16
-------------------------------------------------------------------------------
SUM:                           110           2486          12820          11024
-------------------------------------------------------------------------------


Statistical information for the repository '2244' was gathered on 2020/05/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Cesar Luis Aybar Cam             1             7              0            0.04
Digdgeo                          1             5              3            0.05
Oliver                           4           303             67            2.11
Qiusheng Wu                    115         13891           3251           97.80

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Cesar Luis Aybar Cam          7          100.0          0.5                0.00
Digdgeo                       2           40.0          1.4                0.00
Oliver                      236           77.9          0.6               15.25
Qiusheng Wu               10640           76.6          1.2                9.80
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.rse.2017.06.031 is OK
- 10.1126/science.1244693 is OK
- 10.3390/rs9121315 is OK
- 10.3390/rs10050691 is OK
- 10.1038/s41893-020-0521-x is OK
- 10.1038/nature20584 is OK
- 10.1016/j.rse.2019.04.015 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02244/joss.02244/10.21105.joss.02244.pdf)

**Comment by arfon** [comment]
@giswqs - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by giswqs** [comment]
Potential reviewers with expertise in Google Earth Engine, remote sensing, and GIS: 
- kmarkert
- Scivision
- Zac-HD
- usethedata
- agisga
- nagellette

**Comment by kyleniemeyer** [comment]
Hi @hugoledoux, do you have the bandwidth to take this submission on?

**Comment by kyleniemeyer** [comment]
@whedon invite @hugoledoux as editor

**Comment by whedon** [comment]
@hugoledoux has been invited to edit this submission.

**Comment by hugoledoux** [comment]
@whedon assign @hugoledoux as editor

**Comment by whedon** [comment]
OK, the editor is @hugoledoux

**Comment by hugoledoux** [comment]
@whedon assign @fbiljecki as reviewer

**Comment by whedon** [comment]
OK, @fbiljecki is now a reviewer

**Comment by hugoledoux** [comment]
@whedon add @steflhermitte as reviewer

**Comment by whedon** [comment]
OK, @steflhermitte is now a reviewer

**Comment by hugoledoux** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2305.
