### ISSUE TITLE
[PRE REVIEW]: Open Source Optical Coherence Tomography Software

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2245]
**Submitting author:** @spectralcode (<a href="http://orcid.org/0000-0002-4494-6127">Miroslav Zabic</a>)
**Repository:** <a href="https://github.com/spectralcode/OCTproZ" target ="_blank">https://github.com/spectralcode/OCTproZ</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewers:** @phtomlins, @jdavidli
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @spectralcode. **Currently, there isn't an JOSS editor assigned** to your paper.

@spectralcode if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.50 s (182.4 files/s, 102992.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             36           5385          11190          19692
C/C++ Header                    37           1747           2569           5836
Qt                               4              0              0           2772
CUDA                             1            156            109            941
ProGuard                         4            104             65            412
GLSL                             4             84            112            264
Markdown                         5            116              0            240
TeX                              1             15              0            152
-------------------------------------------------------------------------------
SUM:                            92           7607          14045          30309
-------------------------------------------------------------------------------


Statistical information for the repository '2245' was gathered on 2020/05/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
spectralcode                    11         46904            485          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
spectralcode              46419           99.0          0.0               35.40
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1364/boe.3.003067 may be missing for title: Spectral domain optical coherence tomography of multi-MHz A-scan rates at 1310 nm range and real-time 4D-display up to 41 volumes/second
- https://doi.org/10.1364/oe.18.011772 may be missing for title: Real-time 4D signal processing and visualization using graphics processing unit on a regular nonlinear-k Fourier-domain OCT system
- https://doi.org/10.1109/fccm.2011.27 may be missing for title: Scalable, high performance Fourier domain optical coherence tomography: Why FPGAs and not GPGPUs
- https://doi.org/10.1364/oe.15.007634 may be missing for title: Improved lateral resolution in optical coherence tomography by digital focusing using two-dimensional numerical diffraction method
- https://doi.org/10.1364/boe.8.004887 may be missing for title: Improving lateral resolution and image quality of optical coherence tomography by the multi-frame superresolution technique for 3D tissue imaging
- https://doi.org/10.1117/12.911297 may be missing for title: Digital refocusing in optical coherence tomography
- https://doi.org/10.1117/1.jbo.18.2.026002 may be missing for title: Graphics processing unit accelerated optical coherence tomography processing at megahertz axial scan rate and high resolution video rate volumetric rendering
- https://doi.org/10.1007/978-3-319-06419-2_6 may be missing for title: Spectral/Fourier domain optical coherence tomography
- https://doi.org/10.1364/oe.18.024395 may be missing for title: Reference spectrum extraction and fixed-pattern noise removal in optical coherence tomography
- https://doi.org/10.1364/boe.5.002963 may be missing for title: High definition live 3D-OCT in vivo: design and evaluation of a 4D OCT engine with 1 GVoxel/s

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02245/joss.02245/10.21105.joss.02245.pdf)

**Comment by arfon** [comment]
@spectralcode - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1364/boe.3.003067 is OK
- 10.1364/oe.18.011772 is OK
- 10.1117/1.3548153 is OK
- 10.1117/1.JBO.17.10.100502 is OK
- 10.1109/fccm.2011.27 is OK
- 10.1364/OPEX.12.002404 is OK
- 10.1364/OPEX.12.002435 is OK
- 10.1364/oe.15.007634 is OK
- 10.1364/BOE.8.004887 is OK
- 10.1117/12.911297 is OK
- 10.1364/OE.11.000782 is OK
- 10.1117/1.JBO.18.2.026002 is OK
- 10.1364/OL.24.001221 is OK
- 10.1007/978-3-540-77550-8_5 is OK
- 10.1364/OE.18.024395 is OK
- 10.1364/BOE.5.002963 is OK
- 10.1371/journal.pone.0213144 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @spectralcode - thanks for your submission to JOSS. I'll be your editor for this submission. A couple of items I could do with your help with: 

- Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?
- The paper as currently written is rather long compared to our guidelines of 250--1000 words: https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain . Please could you look at moving some of the content to documentation?

**Comment by spectralcode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02245/joss.02245/10.21105.joss.02245.pdf)

**Comment by spectralcode** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1364/boe.3.003067 is OK
- 10.1364/oe.18.011772 is OK
- 10.1117/1.3548153 is OK
- 10.1117/1.JBO.17.10.100502 is OK
- 10.1109/fccm.2011.27 is OK
- 10.1117/1.JBO.18.2.026002 is OK
- 10.1364/OE.18.024395 is OK
- 10.1364/BOE.5.002963 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by spectralcode** [comment]
@arfon thank you for your comment regarding the paper length. I have shortened the paper drastically. Please let me know if you still have any concerns.

Here are some potential reviewers from the list:
- mlxd
- mstimberg
- adam-m-jcbs
- RainierBarrett

A very suitable reviewer who is not on the list would be datenwolf. However, I don't know if he is willing to review.

**Comment by arfon** [comment]
:wave: @datenwolf @mstimberg @RainierBarrett - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by mstimberg** [comment]
:wave: @arfon. I could review from the technical side, but I have only minimal domain knowledge and don't know other software used in this area. I also have a number of reviews lined up, so this is more of an "ok, if you don't find anyone else" rather than an enthusiastic yes :wink:  (the software itself looks pretty impressive though!)

**Comment by datenwolf** [comment]
I'm okay to review it. However I must stress that any review must clearly indicate my financial interest in Optores. Other than that, I can do it.

**Comment by arfon** [comment]
> I'm okay to review it. However I must stress that any review must clearly indicate my financial interest in Optores. Other than that, I can do it.

OK, thanks for letting me know @datenwolf. I'd rather not avoid this conflict it at all possible.

**Comment by arfon** [comment]
:wave: @mlxd - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by mlxd** [comment]
Hi @arfon as much as I would like to help, due to current restrictions here I won't have access to capable hardware to evaluate this for another 3 months or so. Apologies, but I will need to pass for now.

If no progress is made by then please feel free to get back to me.

**Comment by arfon** [comment]
:wave: @adam-m-jcbs - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by RainierBarrett** [comment]
Hi @arfon, I'm afraid I'm gearing up to defend my PhD thesis in the next couple months, so I don't think I'll have time to dedicate to a review for the time being.

**Comment by arfon** [comment]
NP, thanks for letting us know @RainierBarrett. Also good luck!

**Comment by arfon** [comment]
@whedon invite @jgostick as editor

:wave: @jgostick - would you be willing to edit this submission? I feel like you might have better luck finding reviewers?

**Comment by whedon** [comment]
@jgostick has been invited to edit this submission.

**Comment by jgostick** [comment]
I'm not able to run or compile any of this code, and despite the tomography keyword it's quite different from what I work on, so I don't know anyone that could review.  Sorry.

**Comment by arfon** [comment]
> I'm not able to run or compile any of this code, and despite the tomography keyword it's quite different from what I work on, so I don't know anyone that could review. Sorry.

OK thanks for letting me know.

**Comment by arfon** [comment]
:wave: @marksgraham -  would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by marksgraham** [comment]
Hi. I've taken a look and am not able to compile the code. Perhaps if @spectralcode  can assist me I'd be able to review.

**Comment by spectralcode** [comment]
Hi @marksgraham I can assist you to compile the code and then I will update the compiling instructions to help future users with similar troubles.

Can you provide some more information? Do you use the QtCreator and do you have installed cuda?
Are there any error messages from the compiler?

**Comment by marksgraham** [comment]
I have installed QTCreator and I have all the CUDA drivers. OCTProZ_DevKit seems to build fine. virtualoctsystem gives three errors when I attempt to build, all related to `ceil`. Here is an example of one of them:

```
/home/mark/Downloads/OCTproZ-master/octproz_virtual_oct_system/src/virtualoctsystem.cpp:60: error: ‘ceil’ was not declared in this scope
  size_t bufferSize = currParams.width*currParams.height*currParams.depth*ceil((double)this->currParams.bitDepth / 8.0);
                                                                          ^~~~
````

**Comment by spectralcode** [comment]
@marksgraham thank you for taking the time to try to compile this somewhat large project. I'm sure we can get it to work together.

I've updated virtualoctsystem.h (just added the line "#include "math.h"").
Could you please retry it with the new virtualoctsystem.h and let me know if it works?

If this does not work another possibility is to replace "ceil" by "std::ceil", but as this problem does not occur with Ubuntu 16.04 I will first have to install Ubuntu 18.04 and test it.

**Comment by marksgraham** [comment]
@spectralcode I can now compile virtualoctsystem. It isn't clear to me how I actually get it to run now.. when I press run I'm told `You need to set an executable in the custom run configuration.`

**Comment by spectralcode** [comment]
@marksgraham ok, thats great!
The virtual OCT system is an OCTproZ plugin and it cannot be executed on its own. It needs to be loaded from OCTproZ. Have a look at the quick start guide in the user manual: https://spectralcode.github.io/OCTproZ/index.html 

Try compiling OCTproZ and then run it to load the virtual OCT system. 
(Hint: before running OCTproZ with the "play" button in Qt Creator right click on the OCTproZ project and click on the first option. It should be something like "set as active project")

**Comment by marksgraham** [comment]
@spectralcode 
When I now try to compile OCTproZ I get a CUDA error:
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
I had  thought I had the relevant drivers because nvidia-smi works on my system with the following output:
``` NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1   ```

Does this mean I also need to install the nvidia-cuda-toolkit to get this working on my system?

**Comment by spectralcode** [comment]
@marksgraham yes, exactly.

**Comment by marksgraham** [comment]
I have nvcc installed at `/usr/bin/nvcc` but QTcreator is still looking for it in `/usr/local/cuda/bin/nvcc`. It isn't  clear to me how I can configure the build to point it to the right place - any ideas?

**Comment by arfon** [comment]
@datenwolf - could you say a little more about your financial interests in Optores here? It's not clear what _Optores_ is, and how it's related to this software.

**Comment by spectralcode** [comment]
@marksgraham I am not sure, but it could be that you need to do the "post-installation actions" which are listed in the [official cuda installation guide for Linux](https://docs.nvidia.com/cuda/cuda-installation-guide-linux).

I am going to set up Ubuntu 18.04 and the Qt + Cuda development environment to see if I run in to the same issue.

**Comment by spectralcode** [comment]
I've tested it with Ubuntu 18.04 and everything worked just fine. Unfortunately (?) I did not had the same problem as you did with nvcc that can't be found. 
For installation of cuda I followed the official cuda installation guide for Linux. If you have also used this guide, then probably something went wrong during the post-installation actions as those include the setup of the PATH variable. 
Do you think this can be the case?

But I've found some other minor issues in the .pro files that are now fixed.

**Comment by marksgraham** [comment]
Hi @spectralcode @arfon 

I've delved deeper and concluded that for me to get this working I would need to do a fresh install of all my CUDA drivers. Experience had taught me that messing with CUDA drivers can cause various problems and should only be done when absolutely necessary. I'm reluctant to do so in order to complete this review, especially as I'm doing a lot of GPU-heavy work right now that would be interrupted if I were to interfere with my setup. So I'm going to have to say sorry, and pass on this.

**Comment by spectralcode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02245/joss.02245/10.21105.joss.02245.pdf)

**Comment by arfon** [comment]
@spectralcode - sorry it's proving so tough to find reviewers here. Any chance you could suggest some additional possible candidates here?

**Comment by spectralcode** [comment]
@arfon - I still hope that @datenwolf will reply.

Here are some other possible candidates:
- Marcin Sylwestrzak (http://lab.fizyka.umk.pl/team/ )
- Pete Tomlins (https://www.qmul.ac.uk/dentistry/people/profiles/drpetetomlins.html )
- Christian Viehland (http://biophotonics.pratt.duke.edu/content/viehland ) or one of the Phd students (e. g. David Li http://biophotonics.pratt.duke.edu/content/li )
- GitHub user PhillyVanilly9119 (I talked with him about the Software and he starred the Project on GitHub, so I don't know if this disqualifies him as reviewer.)

**Comment by arfon** [comment]
Many thanks @spectralcode. I've emailed Marcin, Pete, and Christian to see if they can help out.

**Comment by arfon** [comment]
Just a quick update from me: I heard back from Pete who was positive about reviewing this package. I asked him to post here so we have his GitHub handle.

**Comment by arfon** [comment]
I also just asked for potential reviewers on Twitter: https://twitter.com/arfon/status/1285536296828653569

**Comment by spectralcode** [comment]
Thank you for the update and for your effort! I've sent a link to your tweet to octnews.org.

**Comment by arfon** [comment]
:wave: @PhillyVanilly9119 - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by PhillyVanilly9119** [comment]
Hey guys!
First of all, thank you guys for considering me as a possible reviewer (@arfon ). However, I think I might be too biased, since my research is on a very related topic (as @spectralcode mentioned). I like to think I'm not but in the interest of fact based reviewing, I agree that someone else would proably be a more suitable candidate.
I think guys from Jo Izatt group, like Christian Viehland or his PhD students working on intra-surgical OCT would be a great fit!
@spectralcode : I think they are very active in reviewing papers in OSA jourals, so I think you can directly contact them and you dint have to wait for the tweet to appear on octnews.org.

Good luck with your search!
Cheers

**Comment by arfon** [comment]
> @spectralcode : I think they are very active in reviewing papers in OSA jourals, so I think you can directly contact them and you don't have to wait for the tweet to appear on octnews.org.

:zap: thanks @PhillyVanilly9119! If you are willing to contact them that would be great! Feel free to copy me (arfon.smith@gmail.com) on the email thread.

**Comment by spectralcode** [comment]
@PhillyVanilly9119 : thanks! 
Regarding octnews: A link to Arfon's tweet already was on [octnews](http://www.octnews.org/articles/9866790/the-journal-of-open-source-software-is-looking-for/) but it doesn't seem to have helped much.

@arfon : I think you have already contacted Christian Viehland (see [your post](https://github.com/openjournals/joss-reviews/issues/2245#issuecomment-658701574) ) but probably not David Li. So I just contacted David Li via mail.

**Comment by arfon** [comment]
@whedon add @phtomlins as reviewer

**Comment by whedon** [comment]
OK, @phtomlins is now a reviewer

**Comment by arfon** [comment]
:wave: @dntrinca @DanNixon @brandondube - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by arfon** [comment]
@phtomlins - while we're waiting to find a second reviewer, feel free to familiarize yourself with the JOSS reviewer guidelines https://joss.readthedocs.io/en/latest/reviewer_guidelines.html . Once we have a second reviewer, I'll go ahead and set up the actual review.

**Comment by arfon** [comment]
@whedon add @jdavidli as reviewer

**Comment by whedon** [comment]
OK, @jdavidli is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2580.

**Comment by arfon** [comment]
@phtomlins, @jdavidli - thanks for agreeing to review this submission. See you over in #2580 where the actual review will take place.

**Comment by brandondube** [comment]
👋 @arfon @spectralcode I can perform this review.  I do not think it constitutes COI, but I am an alumni ('18) of a group that does research on OCT, e.g. [a recent publication](https://www.osapublishing.org/oe/abstract.cfm?uri=oe-28-14-19937&origin=search).  I never worked in any depth on any of the OCT stuff.

**Comment by arfon** [comment]
Great, thanks @brandondube. I'd love to have you as a third reviewer. I'll go ahead and add you to #2580 now.
