### ISSUE TITLE
[PRE REVIEW]: TTLocVis: A Twitter Topic Location Visualization Package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2246]
**Submitting author:** @xillig (<a href="http://orcid.org/0000-0003-2346-2841">Gillian Kant</a>)
**Repository:** <a href="https://github.com/xillig/TTLocVis" target ="_blank">https://github.com/xillig/TTLocVis</a>
**Version:** v0.1.0
**Editor:** @trallard
**Reviewers:** @sara-02 , @linuxscout, @aozorahime
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @xillig. **Currently, there isn't an JOSS editor assigned** to your paper.

@xillig if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (135.0 files/s, 31258.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           3            210            640            885
JSON                             3              0              0            676
Markdown                         6            151              0            634
TeX                              1              8              4             26
YAML                             1              0              0              7
-------------------------------------------------------------------------------
SUM:                            14            369            644           2228
-------------------------------------------------------------------------------


Statistical information for the repository '2246' was gathered on 2020/05/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ben                              1             1              0            0.00
ChrisW09                         2            81              0            0.25
Gillian                         36         15985          15475           96.25
xillig                           1          1143              0            3.50

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Gillian                    1090            6.8          0.6               49.08
xillig                      645           56.4          0.0               16.28
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1145/2484028.2484166 may be missing for title: Improving LDA Topic Models for Microblogs via Tweet Pooling and Automatic Labeling

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02246/joss.02246/10.21105.joss.02246.pdf)

**Comment by arfon** [comment]
:wave: @xillig - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by sara-02** [comment]
Hello, @arfon and @xillig I would like to review this package as I have recently started working on Twitter data visualization myself.
Do let me know when we move this up from the waitlisted phase :)

**Comment by xillig** [comment]
Hi @arfon and @sara-02. That sounds good to me.  :smile:

**Comment by kyleniemeyer** [comment]
Hi @trallard, do you have the bandwidth to take this one one?

**Comment by kyleniemeyer** [comment]
@whedon invite @trallard as editor

**Comment by whedon** [comment]
@trallard has been invited to edit this submission.

**Comment by trallard** [comment]
Hi I can take this submission

**Comment by trallard** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by trallard** [comment]
Hi, thanks for your patience during these busy times. We still need another reviewer to move this submission forward.

@xillig do you have any suggestions? Otherwise, please check our list of available reviewers <https://bit.ly/joss-reviewers> and list a couple of names here (without pinging them with @)

**Comment by trallard** [comment]
@whedon add @sara-02  as reviewer

**Comment by whedon** [comment]
OK, @sara-02  is now a reviewer

**Comment by sara-02** [comment]
Hey @trallard Do we wait for the others to be added or I can start the review process?

**Comment by trallard** [comment]
Hey @sara-02 we do need at least 2 reviewers to move forward. 

@xillig any chance you have had time to look at the list of potential reviewers?

**Comment by xillig** [comment]
hey @trallard, I think @ahurriyetoglu would be a good fit regarding the topic.

**Comment by trallard** [comment]
Hi @ahurriyetoglu on behalf of the JOSS editorial team I would like to invite you to review this submission. 

Would you be able and willing to take it?

**Comment by xillig** [comment]
Hi @trallard, shall I come up with more reviewer suggestions to move forward?

**Comment by trallard** [comment]
That would be great @xillig  since we have not had any response

**Comment by xillig** [comment]
Hi @trallard,

In the following you find a list of selected potential reviewers. Would it be possible to contact the first three in the list to speed up the process a little bit? 

@alexhanna
@sbrugman
@vc1492a

@jkahn
@deniederhut
@linuxscout
@ionlights
@aozorahime

Thank you!

**Comment by xillig** [comment]
Hi @sara-02, 

Thanks again for offering to review our paper. We appreciate your interest a lot. As you know, we are still urgently trying to find a second reviewer. Do you perhaps have any additional suggestions?

**Comment by sbrugman** [comment]
@xillig Sorry, won't be able to review at this time. Hope you will find a second reviewer soon.

**Comment by linuxscout** [comment]
Hi @xillig , I can do it

**Comment by aozorahime** [comment]
@xillig I am late for this :smile:

**Comment by linuxscout** [comment]
> @xillig I am late for this smile

@aozorahime  you can do it.

**Comment by trallard** [comment]
@whedon add @linuxscout as reviewer

**Comment by whedon** [comment]
OK, @linuxscout is now a reviewer

**Comment by trallard** [comment]
Great we have 2 reviewers now, depending on @aozorahime response we can add them and move forward or move forward with our 2 reviewers straight away

**Comment by aozorahime** [comment]
If the slot still available, I can do that @trallard

**Comment by trallard** [comment]
Awesome thanks!

**Comment by trallard** [comment]
@whedon add @aozorahime as reviewer

**Comment by whedon** [comment]
OK, @aozorahime is now a reviewer

**Comment by trallard** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2507.

**Comment by xillig** [comment]
Perfect, thank you everyone for your support! :)

**Comment by vc1492a** [comment]
Sorry I missed it! Was 2AM local time about 5 hours ago 😄  best of luck with the review!
