### ISSUE TITLE
[PRE REVIEW]: CollatriX: A GUI to collate MorphoMetriX outputs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2247]
**Submitting author:** @cbirdferrer (<a href="http://orcid.org/0000-0001-7763-7761">Clara Bird</a>)
**Repository:** <a href="https://github.com/cbirdferrer/collatrix" target ="_blank">https://github.com/cbirdferrer/collatrix</a>
**Version:** v1.0.5
**Editor:** @KristinaRiemer
**Reviewers:** @evaristor, @katmratliff
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @cbirdferrer. **Currently, there isn't an JOSS editor assigned** to your paper.

@cbirdferrer if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.01825 is OK
- 10.1002/ecs2.1468 is OK
- 10.3389/fmars.2017.00366 is OK
- 10.3354/meps12522 is OK
- 10.1111/mms.12527 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@cbirdferrer - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02247/joss.02247/10.21105.joss.02247.pdf)

**Comment by kyleniemeyer** [comment]
Hi @KristinaRiemer, can you take this submission on as your first editorial assignment?

**Comment by kyleniemeyer** [comment]
@whedon invite @KristinaRiemer as editor

**Comment by whedon** [comment]
@KristinaRiemer has been invited to edit this submission.

**Comment by KristinaRiemer** [comment]
@kyleniemeyer I can take this on. Can I assign myself as editor, or is that something you have to do?

**Comment by danielskatz** [comment]
You can assign yourself, either by
```@whedon assign @KristinaRiemer as editor```
or
```@whedon assign me as editor```

After you do this, remove the waitlisted label.

**Comment by KristinaRiemer** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @KristinaRiemer

**Comment by KristinaRiemer** [comment]
@evaristor @rabernat @katmratliff @NatalieThurlby would any of you be able and willing to review this submission? Here are [the reviewing guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) for reference.

**Comment by evaristor** [comment]
@KristinaRiemer I can review this submission.

**Comment by katmratliff** [comment]
@KristinaRiemer I am also happy to review.

**Comment by KristinaRiemer** [comment]
Great, thanks so much @evaristor and @katmratliff!

**Comment by KristinaRiemer** [comment]
@whedon assign @evaristor as reviewer

**Comment by whedon** [comment]
OK, @evaristor is now a reviewer

**Comment by KristinaRiemer** [comment]
@whedon add @katmratliff as reviewer

**Comment by whedon** [comment]
OK, @katmratliff is now a reviewer

**Comment by KristinaRiemer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2328.
