### ISSUE TITLE
[PRE REVIEW]: Excimontec v1.0: An Open-Source Software Tool for Kinetic Monte Carlo Simulations of Organic Electronic Devices

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2248]
**Submitting author:** @MikeHeiber (<a href="http://orcid.org/0000-0002-1567-5663">Michael Heiber</a>)
**Repository:** <a href="https://github.com/MikeHeiber/Excimontec" target ="_blank">https://github.com/MikeHeiber/Excimontec</a>
**Version:** v1.0.0
**Editor:** @pdebuyl
**Reviewers:** @mdavezac
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @MikeHeiber. **Currently, there isn't an JOSS editor assigned** to your paper.

@MikeHeiber if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.92 s (437.1 files/s, 99268.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                             19           2236              5          36176
HTML                           227           1801           1628          32321
C++                              6            158            664           5572
JavaScript                     125            164            245           3838
CSS                              4            359             80           1743
TeX                              3            196              4            910
XML                              6              0              0            766
C/C++ Header                     4            308            553            657
Markdown                         5            138              0            628
make                             1             18              7             50
YAML                             1              5              5             35
Bourne Shell                     1              5             12             11
-------------------------------------------------------------------------------
SUM:                           402           5388           3203          82707
-------------------------------------------------------------------------------


Statistical information for the repository '2248' was gathered on 2020/05/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Joshua S Brown                   1             2              2            0.01
JoshuaSBrown                     1            16              0            0.03
Michael C. Heiber               87         27717          18085           90.94
MikeHeiber                      12          3752            792            9.02

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
JoshuaSBrown                  6           37.5         22.0                0.00
Michael C. Heiber         12206           44.0         22.5               12.25
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1002/pssb.201350339 is OK
- 10.1088/1361-6633/80/2/026502 is OK
- 10.21105/joss.01072 is OK
- 10.1016/B978-0-08-102284-9.00010-3 is OK
- 10.21105/joss.01168 is OK
- 10.1002/aelm.201800821 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02248/joss.02248/10.21105.joss.02248.pdf)

**Comment by arfon** [comment]
Copying an excerpt of the author submission comment for future editors which includes potential reviewers:

> I'd like to suggest several expert reviewers that may not already be current JOSS reviewers: Prof. Geoff Hutchison, University of Pittsburgh, `@ghutchis` on GitHub. Dr. Christoph Junghans, Los Alamos National Lab,`@junghans` on GitHub Prof. Bjoern Baumeier, Eindhoven University of Technology, `@baumeier` on GitHub

**Comment by arfon** [comment]
:wave: @MikeHeiber - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by kyleniemeyer** [comment]
Hi @pdebuyl, can you take this submission on as your first editorial assignment?

**Comment by kyleniemeyer** [comment]
@whedon invite @pdebuyl as editor

**Comment by whedon** [comment]
@pdebuyl has been invited to edit this submission.

**Comment by pdebuyl** [comment]
@kyleniemeyer yes [note that I self-assigned already for another submission :-) ]

**Comment by pdebuyl** [comment]
@elena-pascal , @dalonsoa are you willing to review this paper for JOSS ?

**Comment by dalonsoa** [comment]
Hi @pdebuyl , I'm afraid I'm packed with other stuff at the moment. Sorry, maybe next time.

**Comment by pdebuyl** [comment]
@dalonsoa thank you for the quick reply!

**Comment by arfon** [comment]
@whedon assign @pdebuyl as editor

**Comment by whedon** [comment]
OK, the editor is @pdebuyl

**Comment by pdebuyl** [comment]
@mdavezac would you review the article "Excimontec v1.0: An Open-Source Software Tool for Kinetic Monte Carlo Simulations of Organic Electronic Devices" for the Journal of Open Source Software?

**Comment by mdavezac** [comment]
@pdebuyl, I'll will be a bit slow in reviewing because of other commitments. If that's okay, then I'm happy to take it on.

**Comment by elena-pascal** [comment]
@pdebuyl sorry my C++ is not good enough to review this.

**Comment by pdebuyl** [comment]
@whedon assign @liangtianumich as reviewer

**Comment by whedon** [comment]
OK, @liangtianumich is now a reviewer

**Comment by pdebuyl** [comment]
@whedon assign @mdavezac as reviewer

**Comment by whedon** [comment]
OK, @mdavezac is now a reviewer

**Comment by pdebuyl** [comment]
@mdavezac thank you, we are still recovering from our pause so this should be ok

**Comment by pdebuyl** [comment]
@elena-pascal thank you for the quick reply!

**Comment by pdebuyl** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2307.

**Comment by arfon** [comment]
> @whedon assign @mdavezac as reviewer

Heads up @pdebuyl, `assign` clobbers existing reviewer assignments which means you actually only have a single reviewer assigned now on #2307. 

If you do `@whedon add @liangtianumich as reviewer` in #2307, you will then have to edit the issue at the top of #2307 to manually add a checklist for @ liangtianumich to work through.

**Comment by pdebuyl** [comment]
Thanks @arfon it is fixed.
