### ISSUE TITLE
[PRE REVIEW]: mlr3shiny: A graphical user interface for easy machine learning in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2249]
**Submitting author:** @lamate (<a href="http://orcid.org/0000-0001-9560-2669">Laurens  Tetzlaff</a>)
**Repository:** <a href="https://github.com/LamaTe/mlr3shiny" target ="_blank">https://github.com/LamaTe/mlr3shiny</a>
**Version:** 0.1.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @lamate. **Currently, there isn't an JOSS editor assigned** to your paper.

@lamate if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (546.5 files/s, 63713.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               22            219            171           2342
JSON                             5             44              0            828
Markdown                         4             31              0            102
TeX                              1             11              0             77
YAML                             1              2              3             17
-------------------------------------------------------------------------------
SUM:                            33            307            174           3366
-------------------------------------------------------------------------------


Statistical information for the repository '2249' was gathered on 2020/05/24.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.01903 is OK
- 10.1007/978-3-642-10745-0_83 is OK
- 10.32614/RJ-2009-016 is OK
- 10.18637/jss.v077.i01 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02249/joss.02249/10.21105.joss.02249.pdf)

**Comment by arfon** [comment]
:wave: @LamaTe - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by labarba** [comment]
@LamaTe — After a pre-review of your submission, and an assessment by the editorial board at large, we find that it does not meet our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). In particular, while the software seems useful, it fails in this criterion: “The software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better”

In our assessment of your submission, it provides a GUI to an existing machine learning framework, and the core functionality is in the mlr3 package.

Thank you for considering JOSS as a venue for your software, and I hope you'll submit other software with research application in the future.

**Comment by labarba** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
