### ISSUE TITLE
[PRE REVIEW]: getCRUCLdata: Use and Explore CRU CL v. 2.0 Climatology Elements in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#225]
**Submitting author:** @adamhsparks (<a href="http://orcid.org/0000-0002-0061-8359">Adam H. Sparks</a>)
**Repository:** <a href="https://github.com/ropensci/getCRUCLdata" target ="_blank">https://github.com/ropensci/getCRUCLdata</a>
**Version:** 0.1.5
**Editor:** @arfon
**Reviewer:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @adamhsparks. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@adamhsparks if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@noamross is this good to auto-accept into JOSS?

**Comment by noamross** [comment]
**getCRUCLdata** has been accepted to rOpenSci.  Reviews can be found here: https://github.com/ropensci/onboarding/issues/96

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/230. Feel free to close this issue now!
