### ISSUE TITLE
[PRE REVIEW]: heddlr: Functional Programming Concepts for R Markdown Document Generation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2251]
**Submitting author:** @mikemahoney218 (<a href="http://orcid.org/0000-0003-2402-304X">Michael Mahoney</a>)
**Repository:** <a href="https://github.com/mikemahoney218/heddlr" target ="_blank">https://github.com/mikemahoney218/heddlr</a>
**Version:** v0.6.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mikemahoney218. **Currently, there isn't an JOSS editor assigned** to your paper.

@mikemahoney218 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.32 s (277.3 files/s, 68759.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              2              1              2           7564
HTML                            29           1869            355           7522
R                               24             51            377            908
CSS                              3             99             48            428
Rmd                              9            306            714            283
Markdown                         8             59              0            266
JavaScript                       3             64             32            256
JSON                             1              0              0            248
YAML                             6             41              8            214
XML                              1              0              0             48
TeX                              1              4              0             41
Bourne Shell                     1              2              0             11
-------------------------------------------------------------------------------
SUM:                            88           2496           1536          17789
-------------------------------------------------------------------------------


Statistical information for the repository '2251' was gathered on 2020/05/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Michael Mahoney                  1           159              5           45.30
Mike Mahoney                     1           198              0           54.70

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Mike Mahoney                352          177.8          0.0                9.09
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/comjnl/27.2.97 is OK

MISSING DOIs

- https://doi.org/10.1145/1463822.1463824 may be missing for title: An experiment in non-procedural programming
- https://doi.org/10.1201/9781315373461-1 may be missing for title: knitr: A Comprehensive Tool for Reproducible Research in R

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02251/joss.02251/10.21105.joss.02251.pdf)

**Comment by danielskatz** [comment]
Note for the future - @csoneson was suggested as the editor

**Comment by danielskatz** [comment]
👋 @mikemahoney218 - Can you help me understand how this is research software?  Specifically, how does this software meet the requirement stated in the JOSS submitting documentation "The software should have an obvious research application"?

**Comment by mikemahoney218** [comment]
:wave: This software helps researchers ensure reproducibility by reducing the amount of repetition necessary in producing R Markdown documents with repeated analysis sections, such as when a similar suite of analyses are performed across multiple distinct study groups. I have previously used it (in research that I unfortunately don't have permission to share publicly) on projects focusing on qualitatively comparing separate populations.

I had viewed this as being a comparable research purpose to [other articles previously published in JOSS](https://joss.theoj.org/papers/10.21105/joss.00185), though I agree that the applications are somewhat less tailored than the average JOSS publication. I fully understand if the guidance for what constitutes a research application has shifted with time!

**Comment by danielskatz** [comment]
Hi @mikemahoney218 - we've had a short discussion among some of the JOSS editors, and while there were some really nice words about this software, and interest in trying it, we don't believe it fits the current JOSS expectations of a research application, so I'm going to reject it from JOSS.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by mikemahoney218** [comment]
Sounds good to me! Thank you for the speedy response.
