### ISSUE TITLE
[PRE REVIEW]: CancerSim: A python3 package for stochastic cancer simulation in 2D

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2252]
**Submitting author:** @CFGrote (<a href="http://orcid.org/0000-0002-2579-5546">Carsten Fortmann-Grote</a>)
**Repository:** <a href="https://github.com/mpievolbio-scicomp/cancer_sim" target ="_blank">https://github.com/mpievolbio-scicomp/cancer_sim</a>
**Version:** v1.0.0
**Editor:** @pdebuyl
**Reviewers:** @jenzopr, @blakeaw
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @CFGrote. **Currently, there isn't an JOSS editor assigned** to your paper.

@CFGrote if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/s41576-019-0114-6 is OK
- 10.1038/ng.3489 is OK
- 10.1038/nrc4029 is OK
- 10.1186/s12885-019-5597-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02252/joss.02252/10.21105.joss.02252.pdf)

**Comment by danielskatz** [comment]
👋 @CFGrote - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.12 s (177.7 files/s, 25153.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           7            437            387            994
Markdown                         2            122              0            365
XML                              1              0              4            170
YAML                             3             11              0             85
TeX                              1              6              1             47
JSON                             1              0              0             42
Jupyter Notebook                 1              0            210             25
Bourne Shell                     2              5              0             12
reStructuredText                 2              9             12              9
make                             1              4              6              9
-------------------------------------------------------------------------------
SUM:                            21            594            620           1758
-------------------------------------------------------------------------------


Statistical information for the repository '2252' was gathered on 2020/06/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Carsten Fortmann-Gro            62          3274           2160           82.46
Luka Opasic                     11           931            225           17.54

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Carsten Fortmann-Gro       1658           50.6          8.3               16.16
Luka Opasic                 161           17.3          4.5               15.53
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by CFGrote** [comment]
MIT License added to master

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.07 s (307.3 files/s, 43489.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           7            437            387            994
Markdown                         2            122              0            365
XML                              1              0              4            170
YAML                             3             11              0             85
TeX                              1              6              1             47
JSON                             1              0              0             42
Jupyter Notebook                 1              0            210             25
Bourne Shell                     2              5              0             12
make                             1              4              6              9
reStructuredText                 2              9             12              9
-------------------------------------------------------------------------------
SUM:                            21            594            620           1758
-------------------------------------------------------------------------------


Statistical information for the repository '2252' was gathered on 2020/06/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Carsten Fortmann-Gro            62          3274           2160           82.46
Luka Opasic                     11           931            225           17.54

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Carsten Fortmann-Gro       1658           50.6          8.3               16.16
Luka Opasic                 161           17.3          4.5               15.53
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@meg-simula @pdebuyl could one of you handle this submission? Also I recommend MathCancer (Paul Macklin, https://github.com/MathCancer) as a potential reviewer

**Comment by pdebuyl** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by pdebuyl** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @pdebuyl

**Comment by pdebuyl** [comment]
@jenzopr , @hannahbrucemacdonald , @blakeaw could you review the manuscript "CancerSim: A python3 package for stochastic cancer simulation in 2D" for the Journal of Open Source Software? (two reviewers needed).

**Comment by jenzopr** [comment]
Thanks @pdebuyl ! Unfortunately, I won't have enough resources in the next weeks. However, its a very interesting topic and at any other point in time I would have agreed to review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jenzopr thanks for your reply here. FYI we can be extra flexible during these challenging times. If you can review but need more than the usual 2 week window we can likely accommodate. If given this you'd be interested please reconsider. Thanks either way.

**Comment by blakeaw** [comment]
Hi @pdebuyl, sure, I can review it.

**Comment by pdebuyl** [comment]
Thank you @blakeaw !

**Comment by pdebuyl** [comment]
@jenzopr thank you for the quick reply. As @Kevin-Mattheus-Moerman writes, we indeed accept longer delays currently.

**Comment by pdebuyl** [comment]
@mabraham would you review the article "CancerSim: A python3 package for stochastic cancer simulation in 2D" for the Journal of Open Source Software?

**Comment by pdebuyl** [comment]
@CFGrote while we are waiting for the confirmation of a second reviewer, I have a comment already. The paper includes a full example for the parameter file. JOSS articles are intended to remain concise and this content is best left in the dedicated documentation.

**Comment by pdebuyl** [comment]
@dirmeier would you review the article "CancerSim: A python3 package for stochastic cancer simulation in 2D" for the Journal of Open Source Software?

**Comment by jenzopr** [comment]
Hi @pdebuyl, I can do the review if you still need me, as my schedule got a bit lighter 👍

**Comment by pdebuyl** [comment]
@jenzopr thank you for the proposal! I was indeed having difficulty finding another reviewer.

**Comment by pdebuyl** [comment]
@whedon assign @blakeaw as reviewer

**Comment by whedon** [comment]
OK, @blakeaw is now a reviewer

**Comment by pdebuyl** [comment]
@whedon assign @jenzopr as reviewer

**Comment by whedon** [comment]
OK, @jenzopr is now a reviewer

**Comment by pdebuyl** [comment]
@whedon add @blakeaw as reviewer

**Comment by whedon** [comment]
OK, @blakeaw is now a reviewer

**Comment by pdebuyl** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2436.
