### ISSUE TITLE
[PRE REVIEW]: ExoNoodle: A Python package spectral time-series of transiting exoplanets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2253]
**Submitting author:** @mmartin-lagarde (<a href="http://orcid.org/0000-0003-0523-7683">Marine Martin-Lagarde</a>)
**Repository:** <a href="https://gitlab.com/mmartin-lagarde/exonoodle-exoplanets" target ="_blank">https://gitlab.com/mmartin-lagarde/exonoodle-exoplanets</a>
**Version:** v0.12.3
**Editor:** @arfon
**Reviewers:** @hpparvi, @kevin218
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mmartin-lagarde. **Currently, there isn't an JOSS editor assigned** to your paper.

@mmartin-lagarde if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2253 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2253 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @mmartin-lagarde - I think there are some problems with your paper.md.  Please remove the blank lines in the header.

Also, please remove the comments in the AAAS lines so that they read:
aas-doi: 10.3847/xxxxx
aas-journal: The Astronomical Journal

Then try regenerating the PDF by putting in a new comment here with ```@whedon generate pdf```

**Comment by danielskatz** [comment]
Also, I assume this really is associated with a AAS paper?

**Comment by danielskatz** [comment]
👋 @openjournals/dev  - this submission isn't associated with a GitHub user.  I'm unsure how to fix this.

**Comment by arfon** [comment]
> 👋 @openjournals/dev - this submission isn't associated with a GitHub user. I'm unsure how to fix this.

I've just emailed the author (and copied you).

**Comment by arfon** [comment]
Looks like @mmartin-lagarde is valid here now on GitHub too.

**Comment by danielskatz** [comment]
👋 @mmartin-lagarde - please see the comments above and reply to them when you can

**Comment by mmartin-lagarde** [comment]
@danielskatz Yes exactly, it is associated with a AJ paper that is currently under review, therefore I don't have any DOI yet. Should I remove it for now ?

**Comment by danielskatz** [comment]
It's probably fine to leave it, but without the comments. This could be part of the problem with compiling, along with the blank lines

**Comment by mmartin-lagarde** [comment]
The new version with no black line and no comments is on the repository now.

**Comment by mmartin-lagarde** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02253/joss.02253/10.21105.joss.02253.pdf)

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@danielskatz - I'll take this one ✋

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02253/joss.02253/10.21105.joss.02253.pdf)

**Comment by arfon** [comment]
:wave: @hover2pi & @hpparvi - would you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by hpparvi** [comment]
Hi! I'll be happy to review the submission.

**Comment by arfon** [comment]
> Hi! I'll be happy to review the submission.

:zap: thanks @hpparvi. I'll add you to the review now but won't move this forward to the main review issue until we've identified a second reviewer.

**Comment by arfon** [comment]
@whedon add @hpparvi as reviewer

**Comment by whedon** [comment]
OK, @hpparvi is now a reviewer

**Comment by arfon** [comment]
:wave: @hrwakeford @kevin218 - would either of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by kevin218** [comment]
What's the turnaround time for this?

**Comment by arfon** [comment]
> @arfon What's the turnaround time for this?

Ideally within 4-6 weeks?

**Comment by kevin218** [comment]
Ok, I can handle that

**Comment by arfon** [comment]
> Ok, I can handle that

Excellent, thanks @kevin218! I'll go ahead and set up the review for you and @hpparvi now.

**Comment by arfon** [comment]
@whedon add @kevin218 as reviewer

**Comment by whedon** [comment]
OK, @kevin218 is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2287.

**Comment by arfon** [comment]
@hpparvi, @kevin218, @mmartin-lagarde - see you all over in ##2287 where the actual review will take place.
