### ISSUE TITLE
[PRE REVIEW]: MorphoPy: A python package for feature extraction of neural morphologies.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2254]
**Submitting author:** @visdoom (<a href="http://orcid.org/0000-0001-9532-788X">Sophie Laturnus</a>)
**Repository:** <a href="https://github.com/berenslab/MorphoPy" target ="_blank">https://github.com/berenslab/MorphoPy</a>
**Version:** v0.6
**Editor:** @oliviaguest
**Reviewers:** @Emptymalei, @mstimberg
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @visdoom. **Currently, there isn't an JOSS editor assigned** to your paper.

@visdoom if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (235.8 files/s, 61479.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          10            519            807           1714
HTML                            10             85              0            753
Jupyter Notebook                 3              0           2036            361
Markdown                         2            114              0            294
TeX                              1              8              0             87
-------------------------------------------------------------------------------
SUM:                            26            726           2843           3209
-------------------------------------------------------------------------------


Statistical information for the repository '2254' was gathered on 2020/05/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Sophie Laturnus                108          2756           1575           18.97
Thassilo Vogt                   10           190            266            2.00
Visdoom                         12           174             27            0.88
avdaranyi                       39          3882           3344           31.65
huangziwei                       4            32             13            0.20
ziweih                          74          6360           4211           46.30

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Sophie Laturnus             892           32.4          0.8                7.40
Thassilo Vogt                67           35.3          1.7                2.99
Visdoom                     116           66.7          3.4               13.79
avdaranyi                  1965           50.6          5.8               14.96
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2254 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/2254/paper/paper.md): did not find expected '-' indicator while parsing a block collection at line 9 column 5 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @Visdoom - you will need to remove the blank lines from the header of paper.md.  You also should change date to a date, following the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography)

Once you've made these changes, please add a new comment here starting with ```@whedon generate pdf``` to see if the compilation works.  Iterate as needed.

(Also, Reference at the end should be References)

**Comment by arfon** [comment]
@danielskatz @Visdoom - this PR should fix that build: https://github.com/berenslab/MorphoPy/pull/103 (it's got whitespace-alignment issues too)

**Comment by Visdoom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2254 with the following error: 

 Error producing PDF.
! TeX capacity exceeded, sorry [input stack size=5000].
\reserved@a ->\def \reserved@a 
                               *{\@hspacer }\reserved@a 
l.562 ...{0pt}https://github.com/BlueBrain/NeuroM}

Looks like we failed to compile the PDF

**Comment by Visdoom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02254/joss.02254/10.21105.joss.02254.pdf)

**Comment by Visdoom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02254/joss.02254/10.21105.joss.02254.pdf)

**Comment by Visdoom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02254/joss.02254/10.21105.joss.02254.pdf)

**Comment by Visdoom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02254/joss.02254/10.21105.joss.02254.pdf)

**Comment by Visdoom** [comment]
@whedon generate pdf

**Comment by danielskatz** [comment]
👋 @Visdoom - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS last week, we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

(In the meantime, feel free to continue making fixes to the paper, adding missing DOIs, etc.)

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02254/joss.02254/10.21105.joss.02254.pdf)

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1007/s12021-010-9093-7 may be missing for title: The TREES toolbox—probing the basis of axonal and dendritic branching
- https://doi.org/10.1371/journal.pone.0182184 may be missing for title: Metrics for comparing neuronal tree shapes based on persistent homology
- https://doi.org/10.1007/s12021-017-9341-1 may be missing for title: A topological representation of branching neuronal morphologies
- https://doi.org/10.1038/s41467-019-12058-z may be missing for title: Layer 4 of mouse neocortex differs in cell types and circuit organization between sensory areas
- https://doi.org/10.1101/2020.02.03.929158 may be missing for title: Phenotypic variation within and across transcriptomic cell types in mouse motor cortex
- https://doi.org/10.1038/nprot.2008.51 may be missing for title: L-Measure: a web-accessible tool for the analysis, comparison and search of digital reconstructions of neuronal morphologies
- https://doi.org/10.1016/j.cell.2007.01.040 may be missing for title: Comprehensive maps of Drosophila higher olfactory centers: spatially segregated fruit and pheromone representation

INVALID DOIs

- None
```

**Comment by Visdoom** [comment]
Potential reviewers:
Jkanche
A3sha2
Mstimberg
Emptymalei
anibalsolon

**Comment by Visdoom** [comment]
> 👋 @Visdoom - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.
> 
> Since reopening JOSS last week, we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.
> 
> Thanks in advance for your patience!
> 
> (In the meantime, feel free to continue making fixes to the paper, adding missing DOIs, etc.)

Great, thank you!

**Comment by Visdoom** [comment]
@whedon generate pdf

**Comment by Visdoom** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by Visdoom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02254/joss.02254/10.21105.joss.02254.pdf)

**Comment by kyleniemeyer** [comment]
Hi @oliviaguest, do you have bandwidth to take on one more?

**Comment by kyleniemeyer** [comment]
@whedon invite @oliviaguest as editor

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by oliviaguest** [comment]
Sure — with the same proviso as before! 😊

**Comment by oliviaguest** [comment]
Hi 👋  @Visdoom — could you give me some names for reviewers, please, as this is quite far outside my areas of expertise and so I'd appreciate help to find some people. 😁

**Comment by kyleniemeyer** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by Visdoom** [comment]
Hi @oliviaguest :wave: ,

**Comment by oliviaguest** [comment]
@whedon add @Emptymalei as reviewer

**Comment by whedon** [comment]
OK, @Emptymalei is now a reviewer

**Comment by oliviaguest** [comment]
Fantastic news we have @Emptymalei as one of the reviewers. Thank you so much @Emptymalei. Please just sit tight until we find a 2nd person — so: nothing to do just yet. ☺️

**Comment by oliviaguest** [comment]
@whedon add @mstimberg as reviewer

**Comment by whedon** [comment]
OK, @mstimberg is now a reviewer

**Comment by oliviaguest** [comment]
I spoke too soon! We are all set to get ready to review! 🎉

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2339.

**Comment by oliviaguest** [comment]
Please all (@Visdoom, @emptymalei, @mstimberg) move to #2339 to get this party started. 😄
