### ISSUE TITLE
[PRE REVIEW]: itmlogic: Longley Rice Irregular Terrain Model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2255]
**Submitting author:** @edwardoughton (<a href="http://orcid.org/0000-0002-2766-008X">Edward J. Oughton</a>)
**Repository:** <a href="https://github.com/edwardoughton/itmlogic" target ="_blank">https://github.com/edwardoughton/itmlogic</a>
**Version:** v1
**Editor:** @danielskatz
**Reviewers:** @gorlapraveen, @garrettj403
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @edwardoughton. **Currently, there isn't an JOSS editor assigned** to your paper.

@edwardoughton if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2255 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
Note that @hugoledoux was suggested as the editor

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.39 s (162.7 files/s, 15635.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          47            883            731           3455
Markdown                         3             84              0            172
reStructuredText                 4            103            129            155
MATLAB                           1             26             40             70
TeX                              1              0              0             52
YAML                             2              8              3             33
DOS Batch                        1              8              1             26
CSS                              1              2              2             25
XML                              1              0              0             20
make                             1              4              7              9
INI                              1              4              0              4
-------------------------------------------------------------------------------
SUM:                            63           1122            913           4021
-------------------------------------------------------------------------------


Statistical information for the repository '2255' was gathered on 2020/05/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Tom Russell                     12           570            518            6.44
ej550                           76         10515           5298           93.56

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Tom Russell                 259           45.4          0.8               14.67
edwardoughton              4810          100.0          3.8                5.80
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.tele.2019.01.003 is OK
- 10.1109/ACCESS.2019.2949460 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by danielskatz** [comment]
👋 @edwardoughton - Please suggest some potential reviewers (without tagging them with an @).

[This list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

Or if you have other suggestions for potential reviewers, then please mention them here.

**Comment by edwardoughton** [comment]
Potential reviewer: @mychele (Michele Polese)

**Comment by danielskatz** [comment]
Thanks - given that we will need to find 2 reviewers, more suggestions would also be welcome (please note the comment above "(without tagging them with an @)" as well)

**Comment by danielskatz** [comment]
👋 @mychele - Would you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by edwardoughton** [comment]
Thanks for the guidance Daniel.

Potential reviewer - alirazaanis - creator of the community cellular planner repo.

**Comment by danielskatz** [comment]
👋 @alirazaanis - Would you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by edwardoughton** [comment]
Potential reviewer: gorlapraveen (previous JOSS reviewer - knows radio/electrical engineering etc. - uses python)

**Comment by edwardoughton** [comment]
Potetial reviewer: garrettj403 (previous JOSS reviewer - knows radio/electrical engineering etc. - uses python)

**Comment by edwardoughton** [comment]
Potential reviewer: peterl3233 (RF engineer who also codes)

**Comment by danielskatz** [comment]
👋 @gorlapraveen - Would you be willing to review this submission for JOSS?

**Comment by gorlapraveen** [comment]
> wave @gorlapraveen - Would you be willing to review this submission for JOSS?

@danielskatz I wish to review!

**Comment by danielskatz** [comment]
Thanks @gorlapraveen - I'll add you into the system, but we won't start the review until we find at least one more reviewer as well.

**Comment by danielskatz** [comment]
@whedon assign @gorlapraveen as reviewer

**Comment by whedon** [comment]
OK, @gorlapraveen is now a reviewer

**Comment by danielskatz** [comment]
👋 @garrettj403 - Would you be willing to review this submission for JOSS?

**Comment by garrettj403** [comment]
Hi @danielskatz, I can to review this project. :+1:

**Comment by danielskatz** [comment]
@whedon add @garrettj403 as reviewer

**Comment by whedon** [comment]
OK, @garrettj403 is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2266.
