### ISSUE TITLE
[PRE REVIEW]: OMG: A Scalable and Flexible Simulation and Testing Environment Toolbox for Intelligent Microgrid Control

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2256]
**Submitting author:** @stheid (<a href="http://orcid.org/0000-0002-9461-7372">Stefan Heid</a>)
**Repository:** <a href="https://github.com/upb-lea/openmodelica-microgrid-gym" target ="_blank">https://github.com/upb-lea/openmodelica-microgrid-gym</a>
**Version:** v0.2.0
**Editor:** @dhhagan
**Reviewers:** @katyhuff, @gonsie
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @stheid. **Currently, there isn't an JOSS editor assigned** to your paper.

@stheid if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (738.2 files/s, 46954.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          34            629           1006           1467
reStructuredText                33            347            203            678
make                             2             24              7             74
YAML                             1              7              0             39
DOS Batch                        1              8              1             26
-------------------------------------------------------------------------------
SUM:                            71           1015           1217           2284
-------------------------------------------------------------------------------


Statistical information for the repository '2256' was gathered on 2020/05/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel Weber                    88          2088           1631           12.38
Stefan Heid                    136         11200          10905           73.59
hbode                           11          2743            837           11.92
walli                            9           387            246            2.11

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Daniel Weber                650           31.1          1.0               17.38
Oliver Wallscheid            94          100.0          0.8               53.19
Stefan Heid                1924           17.2          1.3               10.40
hbode                       434           15.8          0.5               39.86
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2256 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
👋 @stheid - where is the paper.md and .bib file for this submission?

**Comment by stheid** [comment]
Oh, i assume the issue is caused that the paper is currently not yet on the master branch. The preview worked fine. I am a bit worried to make an ad-hoc merge. Please give me until the end of this work-week to properly finalize our development branch and merge to master.

**Comment by stheid** [comment]
@danielskatz i assume it is fine now. the whedon.theoj preview produces a paper if i omit specifying the branch (meaning master branch)

**Comment by stheid** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02256/joss.02256/10.21105.joss.02256.pdf)

**Comment by stheid** [comment]
![image](https://user-images.githubusercontent.com/2736207/83120700-aaa88000-a0d1-11ea-8566-077a97f2152d.png)

And is there a way to fix the missing whitespace typo? I assume everything will be automatic from here on so the typo would also be on you website if this review comes to an sucessfull end.

**Comment by stheid** [comment]
@whedon set v0.2.0 as version

**Comment by whedon** [comment]
I'm sorry @stheid, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by danielskatz** [comment]
I fixed the whitespace issue

**Comment by danielskatz** [comment]
@whedon set v0.2.0 as version

**Comment by whedon** [comment]
OK. v0.2.0 is the version.

**Comment by danielskatz** [comment]
I don't know that the version matters at this point - we will set it at the end of the view process in case further changes are needed

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.5334/jors.188 may be missing for title: PyPSA: Python for Power System Analysis
- https://doi.org/10.1109/tpwrs.2018.2829021 may be missing for title: Pandapower: An Open-Source Python Tool for Convenient Modeling, Analysis, and Optimization of Electric Power Systems
- https://doi.org/10.1109/tie.2012.2194969 may be missing for title: Advanced Control Architectures for Intelligent Microgrids, Part I: Decentralized and Hierarchical Control
- https://doi.org/10.1109/tie.2012.2196889 may be missing for title: Advanced Control Architectures for Intelligent Microgrids, Part II: Power Quality, Energy Storage, and AC/DC Microgrids

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @stheid - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS last week, we've had > 60 papers submitted and as such, now that yours is complete, it has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

(Also, I see some possibly missing DOIs in the references - feel free to make change to the bib or md files, and enter ```@whedon generate pdf``` as a new comment here to check the results)

**Comment by labarba** [comment]
👋 @sjpfenninger — Could you have a look at this submission and let us know if you can handle it as editor?
Title: OMG: A Scalable and Flexible Simulation and Testing Environment Toolbox for Intelligent Microgrid Control
[ Article proof](https://github.com/openjournals/joss-papers/blob/joss.02256/joss.02256/10.21105.joss.02256.pdf)

**Comment by labarba** [comment]
@whedon invite @sjpfenninger as editor

**Comment by whedon** [comment]
@sjpfenninger has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@sjpfenninger can you handle this submission?

**Comment by Kevin-Mattheus-Moerman** [comment]
@sjpfenninger @KristinaRiemer @usethedata could one of you edit this submission? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@sjpfenninger @KristinaRiemer @usethedata could one of you edit this submission? Thanks

**Comment by dhhagan** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @dhhagan

**Comment by dhhagan** [comment]
Hey @stheid - did you have any recommendations for reviewers (list [here](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822))? If not, I will assign a couple. Thanks!

**Comment by dhhagan** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by stheid** [comment]
> Hey @stheid - did you have any recommendations for reviewers (list [here](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822))? If not, I will assign a couple. Thanks!

ahm, i have no specific preference. i guess someone with the background to electrical engeneering; control; or reinforcement learning would be good

**Comment by dhhagan** [comment]
@garrettj403 and @katyhuff do you have the bandwidth to review this manuscript?

**Comment by garrettj403** [comment]
Hi @dhhagan, unfortunately I don't have any time right now. Looks like an interesting project!

**Comment by katyhuff** [comment]
I can review it this weekend, but not sooner (and maybe not later). If that works, @dhhagan , please count me in.

**Comment by dhhagan** [comment]
@katyhuff thank you! Sounds great. @whedon assign @katyhuff as reviewer

**Comment by danielskatz** [comment]
@dhhagan - whedon commands need to be the first thing in a comment

**Comment by dhhagan** [comment]
@danielskatz Thanks for the info!

**Comment by dhhagan** [comment]
@whedon assign @katyhuff as reviewer

**Comment by whedon** [comment]
OK, @katyhuff is now a reviewer

**Comment by dhhagan** [comment]
@kczimm @IgorBaratta @pdebuyl are one of you available and interested in completing this review?

**Comment by pdebuyl** [comment]
@dhhagan I prefer to skip this one as I am not familiar with the topic.

**Comment by kczimm** [comment]
@dhhagan sorry, I’m unavailable at this time.

**Comment by dhhagan** [comment]
@garrettj403 - Do you have the availability to review this manuscript?

**Comment by garrettj403** [comment]
Hi @dhhagan, unfortunately I don't have any time right now. Looks like an interesting project!

**Comment by dhhagan** [comment]
@jsgalan @gonsie @CameronDevice - are one you able to review this manuscript?

**Comment by gonsie** [comment]
This is a bit outside my area, but I can do it if none of the others are available.

**Comment by dhhagan** [comment]
@whedon add @gonsie as reviewer. Thanks @gonsie

**Comment by whedon** [comment]
OK, @gonsie is now a reviewer

**Comment by dhhagan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2435.
