### ISSUE TITLE
[PRE REVIEW]: CRBHits: Conditional Reciprocal Best Hits in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2257]
**Submitting author:** @kullrich (<a href="http://orcid.org/0000-0003-4308-9626">Kristian Ullrich</a>)
**Repository:** <a href="https://gitlab.gwdg.de/mpievolbio-it/joss_crbhits" target ="_blank">https://gitlab.gwdg.de/mpievolbio-it/joss_crbhits</a>
**Version:** v0.0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kullrich. **Currently, there isn't an JOSS editor assigned** to your paper.

@kullrich if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.01 s (156.0 files/s, 20207.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              1             13              0            120
Markdown                         1             25              0            101
-------------------------------------------------------------------------------
SUM:                             2             38              0            221
-------------------------------------------------------------------------------


Statistical information for the repository '2257' was gathered on 2020/05/26.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02257/joss.02257/10.21105.joss.02257.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.21105/joss.00142 may be missing for title: shmlast: an improved implementation of conditional reciprocal best hits with LAST and Python
- https://doi.org/10.1101/gr.113985.110 may be missing for title: Adaptive seeds tame genomic sequence comparison
- https://doi.org/10.1186/s13059-015-0721-2 may be missing for title: OrthoFinder: solving fundamental biases in whole genome comparisons dramatically improves orthogroup inference accuracy
- https://doi.org/10.1093/protein/12.2.85 may be missing for title: Twilight zone of protein sequence alignments
- https://doi.org/10.1007/978-3-540-35306-5_10 may be missing for title: SeqinR 1.0-2: a contributed package to the R project for statistical computing devoted to biological sequences retrieval and analysis
- https://doi.org/10.1016/s1672-0229(10)60008-3 may be missing for title: KaKs_Calculator 2.0: a toolkit incorporating gamma-series methods and sliding window strategies
- https://doi.org/10.1093/oxfordjournals.molbev.a026236 may be missing for title: Estimating synonymous and nonsynonymous substitution rates under realistic evolutionary models
- https://doi.org/10.1093/nar/gkr853 may be missing for title: PomBase: a comprehensive online resource for fission yeast

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @kullrich - this repository seems to include your paper but not the software. JOSS submissions are normally a software repository that also includes a paper.  Additionally, the software needs to be a public version control system, and from the paper, it appears that your software is in https://mpievolbio-it.pages.gwdg.de/ which may not be public?

Finally, and as a minor point, you should add DOIs to the papers in your references for the papers that have DOIs. The reference check above provides some suggestions, but it is not always completely accurate.

**Comment by kullrich** [comment]
The software repo is here:

https://gitlab.gwdg.de/mpievolbio-it/crbhits <https://gitlab.gwdg.de/mpievolbio-it/crbhits>

I now included the paper.md, paper.bib and figure1.png at the root and added them to .Rbuildignore

Should I do a new submission or can the repo source be changed?

Best regards

Kristian Ullrich
--
Kristian Ullrich, Ph.D.
Scientific IT group
Department of Evolutionary Genetics
Max Planck Institute for Evolutionary Biology
August Thienemann Str. 2
24306 Plön
Germany
+49 4522 763 313
ullrich@evolbio.mpg.de

--
CONFIDENTIALITY NOTICE:
The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.

**Comment by danielskatz** [comment]
If you don't mind making a new submission, it might be slightly easier.  I will mark this one as withdrawn

**Comment by danielskatz** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.

**Comment by kullrich** [comment]
OK, thanks
--
Kristian Ullrich, Ph.D.
Scientific IT group
Department of Evolutionary Genetics
Max Planck Institute for Evolutionary Biology
August Thienemann Str. 2
24306 Plön
Germany
+49 4522 763 313
ullrich@evolbio.mpg.de

--
CONFIDENTIALITY NOTICE:
The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.

**Comment by kullrich** [comment]
Paper was re-submitted but until now the @whedon seems not to have reported any feedback. Might there be an issue because the same title was used for the new submission?

**Comment by danielskatz** [comment]
I see it in the queue, but the next step is manual, and I haven't gotten to it yet.  Last time you were just fortunate that I was working on this at about the same time as you submitted, so you got a very fast manual (not automated) response.

**Comment by kullrich** [comment]
OK, I understand.

Thank you for the quick response and the nice help about this first issue.

Best regards

Kristian
--
Kristian Ullrich, Ph.D.
Scientific IT group
Department of Evolutionary Genetics
Max Planck Institute for Evolutionary Biology
August Thienemann Str. 2
24306 Plön
Germany
+49 4522 763 313
ullrich@evolbio.mpg.de

--
CONFIDENTIALITY NOTICE:
The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.
