### ISSUE TITLE
[PRE REVIEW]: nails: Network Analysis Interface for Literature Studies

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#226]
**Submitting author:** @jsalminen (<a href="http://orcid.org/0000-0003-0688-2211">Juho Salminen</a>)
**Repository:** <a href="https://github.com/aknutas/nails" target ="_blank">https://github.com/aknutas/nails</a>
**Version:** 1.0.0
**Editor:** @karthik
**Reviewer:** @janschulz

**Author instructions**

Thanks for submitting your paper to JOSS @jsalminen. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jsalminen if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @karthik - the submitting author suggested you as an editor.

**Comment by aknutas** [comment]
Hi, I'm Antti Knutas, the second author. The whedon robot asked to propose reviewers. The software is related to bibliometrics, network analysis and data visualization in R. Because of this I would propose @janschulz and @cdcrabtree as reviewers. We performed the submission process together with @jsalminen and I think he would agree.

**Comment by jsalminen** [comment]
That's correct, @aknutas, I agree :)

**Comment by janschulz** [comment]
I can do the review, if it is still open :-)

**Comment by karthik** [comment]
Great, thanks @janschulz! Assigning you.

**Comment by karthik** [comment]
@whedon assign @janschulz as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @janschulz

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by karthik** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/233. Feel free to close this issue now!
