### ISSUE TITLE
[REVIEW]: Ginkgo: A high performance numerical linear algebra library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2260]
**Submitting author:** @pratikvn (<a href="http://orcid.org/0000-0002-7961-1159">Pratik Nayak</a>)
**Repository:** <a href="https://github.com/ginkgo-project/ginkgo" target ="_blank">https://github.com/ginkgo-project/ginkgo</a>
**Version:** v1.3.0
**Editor:** @mjsottile
**Reviewers:** @adam-m-jcbs, @zeroset
**Archive:** <a href="https://doi.org/10.5281/zenodo.4003613" target="_blank">10.5281/zenodo.4003613</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/087426312405a4c0bffaf67d3802bc59/status.svg)](https://joss.theoj.org/papers/087426312405a4c0bffaf67d3802bc59)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/087426312405a4c0bffaf67d3802bc59"><img src="https://joss.theoj.org/papers/087426312405a4c0bffaf67d3802bc59/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/087426312405a4c0bffaf67d3802bc59/status.svg)](https://joss.theoj.org/papers/087426312405a4c0bffaf67d3802bc59)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ginkgo-project/ginkgo" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sivaramambikasaran & @adam-m-jcbs & @zeroset, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mjsottile know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ginkgo-project/ginkgo">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@pratikvn) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ginkgo-project/ginkgo">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@pratikvn) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @sivaramambikasaran, @adam-m-jcbs, @zeroset it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2260 with the following error: 

 Can't find any papers to compile :-(

**Comment by mjsottile** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02260/joss.02260/10.21105.joss.02260.pdf)

**Comment by mjsottile** [comment]
@whedon check references

**Comment by pratikvn** [comment]
Hello Editors and Reviewers, Thank you for taking your time to review this submission. 

To make this process easier for all of us,

* Please feel free to use this issue to discuss the library and its features: https://github.com/ginkgo-project/ginkgo/issues/478

* Please feel free to submit feedback on the paper itself on this PR: https://github.com/ginkgo-project/ginkgo/pull/479

**Comment by adam-m-jcbs** [comment]
As per JOSS guidelines, I will create new issues for the purposes of review.  However, I will be careful to link back to the gingko project's two issues for tracking this review.  Thanks for providing these, @pratikvn !

**Comment by mjsottile** [comment]
:wave: @sivaramambikasaran, @adam-m-jcbs, @zeroset - I just wanted to check in and see if you were making progress on the review.  Let me know if you need any assistance while you proceed.

**Comment by pratikvn** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1145/3149704.3149767 is OK
- 10.1145/3380930 is OK
- 10.1002/cpe.4460 is OK
- 10.1145/3324989.3325719 is OK
- 10.1515/jnma-2019-0064 is OK

MISSING DOIs

- https://doi.org/10.1109/ipdps.2019.00033 may be missing for title: ParILUT - A Parallel Threshold ILU for GPUs
- https://doi.org/10.1007/978-3-030-50743-5_16 may be missing for title: Sparse Linear Algebra on AMD and NVIDIA GPUs – The Race is on
- https://doi.org/10.1007/978-3-642-11261-4_11 may be missing for title: Collecting Performance Data with PAPI-C

INVALID DOIs

- None
```

**Comment by pratikvn** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02260/joss.02260/10.21105.joss.02260.pdf)

**Comment by pratikvn** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1145/3149704.3149767 is OK
- 10.1145/3380930 is OK
- 10.1109/IPDPS.2019.00033 is OK
- 10.1007/978-3-030-50743-5_16 is OK
- 10.1002/cpe.4460 is OK
- 10.1145/3324989.3325719 is OK
- 10.1515/jnma-2019-0064 is OK
- 10.1007/978-3-642-11261-4_11 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mjsottile** [comment]
👋 @sivaramambikasaran, @adam-m-jcbs, @zeroset - I haven't seen much activity recently on the reviews and wanted to check in on progress.  Please be sure to check off the reviewer checklists at the top of this issue so I can tell when reviews have been completed and if any outstanding things remain.

**Comment by pratikvn** [comment]
@mjsottile , We just released [Ginkgo version 1.2.0](https://github.com/ginkgo-project/ginkgo/releases/tag/v1.2.0) yesterday, Can I update the version number in the comment that whedon created from 1.1.1 to 1.2.0 ?

**Comment by mjsottile** [comment]
@whedon set v1.2.0 as version

**Comment by whedon** [comment]
OK. v1.2.0 is the version.

**Comment by mjsottile** [comment]
Hi @sivaramambikasaran and @adam-m-jcbs - please let me know if you are unable to complete the reviews so I can identify other reviewer candidates.  If you are able to complete the reviews, it would be useful if you could do so within the next 7-14 days.

**Comment by pratikvn** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02260/joss.02260/10.21105.joss.02260.pdf)

**Comment by mjsottile** [comment]
@whedon remove @sivaramambikasaran as reviewer

**Comment by whedon** [comment]
OK, @sivaramambikasaran is no longer a reviewer

**Comment by mjsottile** [comment]
Confirmed by email that one reviewer has decided they cannot perform review.  Waiting to hear back from other alternative reviewers that have been contacted by email to replace them.  No word from @adam-m-jcbs and don’t have email to contact outside github.  If I successfully find an additional reviewer who will complete their review, we should be good since we have one complete review already.

**Comment by adam-m-jcbs** [comment]
I apologize for my unprofessional absence. My family and I got hit by some COVID-related crises and this review got lost in the chaos.

I apologise for not getting in touch sooner.

I can offer two resolutions:

1: withdraw to allow the process to continue, or

2: address all remaining review criteria by the end of this week.

I will start locally on 2, but let me know if 1 is preferred.

**Comment by mjsottile** [comment]
No problem @adam-m-jcbs - I understand that right now things are a bit chaotic and it's easy to lose track of less critical things like this.  I'd definitely be happy with you completing your review.  No need to withdraw from the process if you believe that you can complete the review.

**Comment by adam-m-jcbs** [comment]
Quick update here (more can be seen in the issues above): func review only has a discrepency in example output to resolve.

doc review is complete.

paper review needs some more accessible context in intro, but otherwise strongly satisfies JOSS criteria.

**Comment by adam-m-jcbs** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02260/joss.02260/10.21105.joss.02260.pdf)

**Comment by adam-m-jcbs** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1145/3149704.3149767 is OK
- 10.1145/3380930 is OK
- 10.1109/IPDPS.2019.00033 is OK
- 10.1007/978-3-030-50743-5_16 is OK
- 10.1002/cpe.4460 is OK
- 10.1145/3324989.3325719 is OK
- 10.1515/jnma-2019-0064 is OK
- 10.1007/978-3-642-11261-4_11 is OK

MISSING DOIs

- https://doi.org/10.1016/j.camwa.2020.06.009 may be missing for title: MFEM: a modular finite element methods library

INVALID DOIs

- None
```

**Comment by adam-m-jcbs** [comment]
fyi, @pratikvn , see missing DOI above.

**Comment by pratikvn** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02260/joss.02260/10.21105.joss.02260.pdf)

**Comment by pratikvn** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1145/3149704.3149767 is OK
- 10.1145/3380930 is OK
- 10.1109/IPDPS.2019.00033 is OK
- 10.1007/978-3-030-50743-5_16 is OK
- 10.1002/cpe.4460 is OK
- 10.1145/3324989.3325719 is OK
- 10.1515/jnma-2019-0064 is OK
- 10.1007/978-3-642-11261-4_11 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.camwa.2020.06.009 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.parco.2017.10.003 is INVALID because of 'https://doi.org/' prefix
```

**Comment by pratikvn** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1145/3149704.3149767 is OK
- 10.1145/3380930 is OK
- 10.1109/IPDPS.2019.00033 is OK
- 10.1007/978-3-030-50743-5_16 is OK
- 10.1002/cpe.4460 is OK
- 10.1145/3324989.3325719 is OK
- 10.1515/jnma-2019-0064 is OK
- 10.1016/j.camwa.2020.06.009 is OK
- 10.1007/978-3-642-11261-4_11 is OK
- 10.1016/j.parco.2017.10.003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by pratikvn** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02260/joss.02260/10.21105.joss.02260.pdf)

**Comment by mjsottile** [comment]
Looks like good progress is being made on the review over in the issues within the Ginkgo repository.  I've been periodically clicking through them to see the progress on the review.  

To make sure things go fast once those are all completed, make sure to post a message in this issue thread to indicate that the review is complete.

In the meantime, @zeroset - I am going to assume based on your checklist that you are satisfied with the submission and have no issues that require addressing as part of your review?  When I perform my final review of the paper I'll keep an eye out for the one unchecked box you have related to the writing of the paper itself.

**Comment by adam-m-jcbs** [comment]
Hi all :wave: !

I want to confirm that through the resolution of these issues (and those linked therein):
https://github.com/ginkgo-project/ginkgo/issues/618
https://github.com/ginkgo-project/ginkgo/issues/597

The `ginkgo` developers have satisfied all criteria for JOSS publication and I recommend acceptance of the submission.

Speaking personally, I want to thank the developers and JOSS for your patience and accommodating the unforeseen delays on my end, in-part due to the impacts of COVID and its fallout.

I apologize for any inconvenience caused, and am very thankful that the developers have been so friendly, helpful, and responsive to my review.

**Comment by mjsottile** [comment]
Thanks for the review @adam-m-jcbs - no problem on the delays.  These days things are a bit unpredictable.

I have a deadline that I need to meet by tomorrow, so once that's cleared I'll finalize the review process.

**Comment by mjsottile** [comment]
@pratikvn I‘ve looked the reviews over and we’re mostly done.  The only remaining request that I have is that you update your bibliography entries for some software packages.  For example, the Eigen package authors provide a BiBTeX entry for citing their work (http://eigen.tuxfamily.org/index.php?title=BibTeX).  PetSc as well (https://www.mcs.anl.gov/petsc/documentation/referencing.html).  SuiteSparse has a “to cite this package” note on their web page (http://faculty.cse.tamu.edu/davis/suitesparse.html).  Trilinos too (https://trilinos.github.io/cite.html).

Please go through the set of software packages currently cited as github links and use the citations that the package authors ask people to use.  I didn’t search for all of them, but only list the four above as examples.  You should search to see if citations exist for the other packages and if you can’t find any, links to the repositories will be fine.

**Comment by pratikvn** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by pratikvn** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02260/joss.02260/10.21105.joss.02260.pdf)

**Comment by pratikvn** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by pratikvn** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2260 with the following error: 

 error: pathspec 'joss-paper' did not match any file(s) known to git.
Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1145/3149704.3149767 is OK
- 10.1145/3380930 is OK
- 10.1109/IPDPS.2019.00033 is OK
- 10.1007/978-3-030-50743-5_16 is OK
- 10.1002/cpe.4460 is OK
- 10.1145/3324989.3325719 is OK
- 10.1515/jnma-2019-0064 is OK
- 10.1016/j.camwa.2020.06.009 is OK
- 10.1007/978-3-642-11261-4_11 is OK
- 10.1016/j.parco.2017.10.003 is OK
- 10.14529/jsfi170104 is OK
- 10.1145/1391989.1391995 is OK
- 10.1145/992200.992206 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by pratikvn** [comment]
@mjsottile , thank you for pointing that out. I have added the proper citations for the references. I could not find any citation guides for `gflags`, `gtest` and `sonarcloud` and hence I left the github repository links in for them. For Trilinos, I had to adapt a bit as their citation format does not seem to work well atleast for the markdown setup here.

**Comment by pratikvn** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02260/joss.02260/10.21105.joss.02260.pdf)

**Comment by pratikvn** [comment]
I believe the doi of this submission is already set (10.21105/joss.02260) . Do I put that in while creating a new upload on Zenodo ?

**Comment by pratikvn** [comment]
@mjsottile , please give us a few more days to merge some of the related pull requests and create a tag for upload on Zenodo. I will ping you here as soon as I have the Zenodo DOI for you.

**Comment by pratikvn** [comment]
@whedon check references

**Comment by pratikvn** [comment]
@whedon generate pdf

**Comment by pratikvn** [comment]
@mjsottile , Here is the Zenodo record: https://zenodo.org/record/4003613 and the DOI for the archive is: 

10.5281/zenodo.4003613

Please also update the version of the library to 1.3.0. 

Thanks!

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02260/joss.02260/10.21105.joss.02260.pdf)

**Comment by mjsottile** [comment]
Great!  I will issue the final commands and then hand the paper off to the acting EIC for final processing.

**Comment by mjsottile** [comment]
@whedon set v1.3.0 as version

**Comment by whedon** [comment]
OK. v1.3.0 is the version.

**Comment by mjsottile** [comment]
@whedon set 10.5281/zenodo.4003613 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4003613" target="_blank">10.5281/zenodo.4003613</a> is the archive.

**Comment by mjsottile** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1679

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1679, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1300319786040205314) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1684
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02260](https://doi.org/10.21105/joss.02260)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@adam-m-jcbs, @zeroset - many thanks for your reviews here and to @mjsottile for editing this submission ✨ 

@pratikvn - your paper is now accepted into JOSS... [AND IT'S OUR 1000TH PAPER](https://blog.joss.theoj.org/2020/08/1000-papers-published-in-joss) :zap::rocket::boom:🥳!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02260/status.svg)](https://doi.org/10.21105/joss.02260)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02260">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02260/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02260/status.svg
   :target: https://doi.org/10.21105/joss.02260
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02260/status.svg)](https://doi.org/10.21105/joss.02260)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
