### ISSUE TITLE
[PRE REVIEW]: gobbli: A uniform interface to deep learning for text in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2261]
**Submitting author:** @jasonnance (<a href="http://orcid.org/0000-0003-4127-3198">Jason Nance</a>)
**Repository:** <a href="https://github.com/RTIInternational/gobbli" target ="_blank">https://github.com/RTIInternational/gobbli</a>
**Version:** v0.2.0
**Editor:** @bmcfee
**Reviewers:** @w4ngatang, @thomwolf
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jasonnance. **Currently, there isn't an JOSS editor assigned** to your paper.

@jasonnance if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2261 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.95 s (341.1 files/s, 44903.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         119           3878           3977          16420
Markdown                        99            967              0          13766
YAML                             8             38             38            833
Jupyter Notebook                 1              0            481            750
reStructuredText                 7            236             80            371
SVG                              2              0              2            213
Bourne Shell                    13             44             26            213
Dockerfile                      11             34             16            120
JSON                            60              0              0             71
DOS Batch                        1              8              1             26
TOML                             1              0              0             21
make                             1              4              7              9
INI                              1              1              0              7
-------------------------------------------------------------------------------
SUM:                           324           5210           4628          32820
-------------------------------------------------------------------------------


Statistical information for the repository '2261' was gathered on 2020/05/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jason Nance                    149         26203           1932           99.99
Peter B                          1             4              0            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jason Nance               24271           92.6          1.0                9.25
Peter B                       4          100.0          6.9                0.00
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02261/joss.02261/10.21105.joss.02261.pdf)

**Comment by danielskatz** [comment]
@whedon check references

**Comment by danielskatz** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1007/978-1-4614-3223-4_6 may be missing for title: A survey of text classification algorithms
- https://doi.org/10.18653/v1/d16-1264 may be missing for title: Squad: 100,000+ questions for machine comprehension of text
- https://doi.org/10.18653/v1/p19-1441 may be missing for title: Multi-task deep neural networks for natural language understanding
- https://doi.org/10.18653/v1/d19-1670 may be missing for title: Eda: Easy data augmentation techniques for boosting performance on text classification tasks
- https://doi.org/10.18653/v1/n18-1101 may be missing for title: A Broad-Coverage Challenge Corpus for Sentence Understanding through Inference
- https://doi.org/10.18653/v1/d15-1075 may be missing for title: A large annotated corpus for learning natural language inference
- https://doi.org/10.18653/v1/n18-2072 may be missing for title: Contextual augmentation: Data augmentation by words with paradigmatic relations

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @jasonnance - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS last week, we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

(Also, I see some small issues in the paper, such as cases in some of the bib entries and missing DOIs - feel free to make change to the bib or md files, and enter ```@whedon generate pdf from branch joss-paper``` as a new comment here to check the results)

**Comment by jasonnance** [comment]
Thanks, Daniel!  We understand JOSS has a large backlog and are in no hurry.  I've tried to clean up the bib entries a bit.

@whedon generate pdf from branch joss-paper

**Comment by jasonnance** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02261/joss.02261/10.21105.joss.02261.pdf)

**Comment by jasonnance** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-1-4614-3223-4_6 is OK
- 10.18653/v1/d16-1264 is OK
- 10.18653/v1/p19-1441 is OK
- 10.18653/v1/d19-1670 is OK
- 10.18653/v1/n18-1101 is OK
- 10.18653/v1/d15-1075 is OK
- 10.18653/v1/n18-2072 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
👋 @bmcfee -- Could you have a look at this submission and let us know if you can handle it as editor?
Title — gobbli: A uniform interface to deep learning for text in Python
[ Article proof](https://github.com/openjournals/joss-papers/blob/joss.02261/joss.02261/10.21105.joss.02261.pdf)

**Comment by labarba** [comment]
@whedon invite @bmcfee as editor

**Comment by whedon** [comment]
@bmcfee has been invited to edit this submission.

**Comment by bmcfee** [comment]
@whedon assign @bmcfee as editor

**Comment by whedon** [comment]
OK, the editor is @bmcfee

**Comment by bmcfee** [comment]
:wave: @jasonnance The repo, license, and scope appear to be in order.  I'll get cracking on finding some reviewers for this submission.  Do you have any suggestions for potential reviewers?

**Comment by jasonnance** [comment]
Thanks, @bmcfee!  I don't have any suggestions for reviewers.

**Comment by bmcfee** [comment]
@whedon add @w4ngatang as reviewer

**Comment by whedon** [comment]
OK, @w4ngatang is now a reviewer

**Comment by bmcfee** [comment]
@whedon add @thomwolf as reviewer

**Comment by whedon** [comment]
OK, @thomwolf is now a reviewer

**Comment by bmcfee** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2395.
