### ISSUE TITLE
[PRE REVIEW]: TorchGAN: A Flexible Framework for GAN Training and Evaluation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2262]
**Submitting author:** @avik-pal (<a href="http://orcid.org/0000-0002-3938-7375">Avik Pal</a>)
**Repository:** <a href="https://github.com/torchgan/torchgan/" target ="_blank">https://github.com/torchgan/torchgan/</a>
**Version:** v0.0.4
**Editor:** @terrytangyuan
**Reviewers:** @Paul92, @urbanophile
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @avik-pal. **Currently, there isn't an JOSS editor assigned** to your paper.

@avik-pal if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.25 s (331.4 files/s, 43589.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          48            949           1941           3790
Jupyter Notebook                 5              0           2056            993
reStructuredText                14            227            215            317
YAML                             9             34             11            242
Markdown                         3             46              0            132
DOS Batch                        1              8              1             27
TOML                             1              0              0             16
CSS                              1              2              2             11
make                             1              4              5             10
TeX                              1              0              0              8
-------------------------------------------------------------------------------
SUM:                            84           1270           4231           5546
-------------------------------------------------------------------------------


Statistical information for the repository '2262' was gathered on 2020/05/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Aniket Das                      23          2608            549           20.86
Aniket1998                       3             4              4            0.05
Avik Pal                        55          8242           3633           78.47
Naman Biyani                     1            50             35            0.56
Weili Shi                        1             2              2            0.03
jess                             1             0              4            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Aniket Das                 1213           46.5         18.8                4.62
Aniket1998                    1           25.0         17.1                0.00
Avik Pal                   5432           65.9         15.3                5.56
Naman Biyani                 34           68.0         10.6                0.00
Weili Shi                     1           50.0         12.6                0.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2262 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch ap/joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch ap/joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2262 with the following error: 

 error: pathspec 'ap/joss-paper' did not match any file(s) known to git.
Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch ap/joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch ap/joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02262/joss.02262/10.21105.joss.02262.pdf)

**Comment by danielskatz** [comment]
👋 @avik-pal - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS last week, we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

(Also, I see at least some small issues in the paper, one of the references (Krizhevesk) seems incomplete, and some things need to kept in upper case (ieee -> IEEE) - feel free to make change to the bib or md files, and enter ```@whedon generate pdf from branch ap/joss_paper``` as a new comment here to check the results)

**Comment by avik-pal** [comment]
@whedon generate pdf from branch ap/joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch ap/joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02262/joss.02262/10.21105.joss.02262.pdf)

**Comment by labarba** [comment]
👋  @terrytangyuan -- Could you have a look at this submission and let us know if you can handle it as editor?
Title — TorchGAN: A Flexible Framework for GAN Training and Evaluation
[Article proof](https://github.com/openjournals/joss-papers/blob/joss.02262/joss.02262/10.21105.joss.02262.pdf)

**Comment by labarba** [comment]
@whedon invite @terrytangyuan as editor

**Comment by whedon** [comment]
@terrytangyuan has been invited to edit this submission.

**Comment by terrytangyuan** [comment]
@whedon assign @terrytangyuan as editor

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by terrytangyuan** [comment]
Hi @avik-pal, if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Comment by avik-pal** [comment]
Hi @terrytangyuan, after going through the list, here is a list of potential reviewers:
1.  `urbanophile`
2. `lee-seon-woo`
3. `Paul92`

**Comment by terrytangyuan** [comment]
@urbanophile @lee-seon-woo @Paul92 If you would like to review for this submission, please let us know here! We need at least two reviewers.

**Comment by Paul92** [comment]
@terrytangyuan Sure, happy to do it.

**Comment by terrytangyuan** [comment]
@whedon assign @Paul92 as reviewer

**Comment by whedon** [comment]
OK, @Paul92 is now a reviewer

**Comment by terrytangyuan** [comment]
@nilesh-patil @paragkulkarni11 @sssomani Would you be interested in reviewing this submission?

**Comment by urbanophile** [comment]
Hi I'm sorry, I need to check my github notifications more frequently but I am happy to review this.

**Comment by terrytangyuan** [comment]
@whedon add @urbanophile as reviewer

**Comment by whedon** [comment]
OK, @urbanophile is now a reviewer

**Comment by terrytangyuan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2606.

**Comment by terrytangyuan** [comment]
Thanks! Please head over to the new issue for review!
