### ISSUE TITLE
[PRE REVIEW]: Frackit: a framework for stochastic fracture network generation and analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2263]
**Submitting author:** @dglaeser (<a href="http://orcid.org/0000-0001-9646-881X">Dennis Gläser</a>)
**Repository:** <a href="https://git.iws.uni-stuttgart.de/tools/frackit" target ="_blank">https://git.iws.uni-stuttgart.de/tools/frackit</a>
**Version:** v1.1
**Editor:** @diehlpk
**Reviewers:** @ilyasst
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @dglaeser. **Currently, there isn't an JOSS editor assigned** to your paper.

@dglaeser if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18419/opus-289 is OK
- 10.1016/j.cageo.2017.02.002 is OK
- 10.1016/j.advwatres.2011.03.007 is OK
- doi.org/10.1016/j.advwatres.2017.10.031 is OK
- 10.1002/nme.2579 is OK
- 10.1016/j.advwatres.2017.10.036 is OK
- 10.1016/j.jcp.2014.12.047 is OK
- 10.1016/j.jcp.2017.07.041 is OK
- 10.1016/j.cageo.2019.06.014 is OK
- 10.1016/j.jcp.2017.12.003 is OK
- 10.1016/j.applthermaleng.2011.01.038 is OK
- 10.1016/j.rser.2014.04.068 is OK

MISSING DOIs

- https://doi.org/10.1016/j.cageo.2015.04.012 may be missing for title: Fracture-based modeling of complex flow and CO2 migration in three-dimensional fractured rocks
- https://doi.org/10.1016/j.jhydrol.2015.08.065 may be missing for title: Finite element generation of arbitrary 3-D fracture networks for flow analysis in complicated discrete fracture networks
- https://doi.org/10.5194/hess-2018-397-rc2 may be missing for title: Stochastic modeling of flow and conservative transport in three-dimensional discrete fracture networks
- https://doi.org/10.1007/s13137-019-0116-8 may be missing for title: A hybrid-dimensional discrete fracture model for non-isothermal two-phase flow in fractured porous media
- https://doi.org/10.1002/nme.6238 may be missing for title: Finite volume discretization for poroelastic media with fractures modeled by contact mechanics
- https://doi.org/10.1007/s13137-019-0117-7 may be missing for title: A stabilized Lagrange multiplier finite-element method for flow in porous media with fractures
- https://doi.org/10.1007/s10596-018-9778-9 may be missing for title: Unified approach to discretization of flow in fractured porous media
- https://doi.org/10.1007/s12665-014-3211-z may be missing for title: Numerical simulation and evaluation of groundwater resources in a fractured chalk aquifer: a case study in Zinder well field, Niger
- https://doi.org/10.1016/j.fuel.2011.08.037 may be missing for title: Comparative evaluation of immiscible, near miscible and miscible CO2 huff-n-puff to enhance oil recovery from a single matrix–fracture system (experimental and simulation studies)

INVALID DOIs

- https://doi.org/10.1016/j.petrol.2019.106350 is INVALID because of 'https://doi.org/' prefix
```

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.30 s (846.9 files/s, 88377.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                   126           2259           6298           8329
C++                             51            829            629           3792
Markdown                         6            363              0           1552
CMake                           53             92            103            608
Python                          12            191            232            559
TeX                              1             33              0            258
GLSL                             2              7              3             56
-------------------------------------------------------------------------------
SUM:                           251           3774           7265          15154
-------------------------------------------------------------------------------


Statistical information for the repository '2263' was gathered on 2020/05/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Dennis.Glaeser                 481         33742          10624          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Dennis.Glaeser            23118           68.5          1.7               30.70
```

**Comment by danielskatz** [comment]
👋 @openjournals/dev - generating the PDF seems to be failing - can you check what's going wrong?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02263/joss.02263/10.21105.joss.02263.pdf)

**Comment by arfon** [comment]
> 👋 @openjournals/dev - generating the PDF seems to be failing - can you check what's going wrong?

I think Whedon might be struggling a little here due to the large size of the (very nice) images in this paper.

**Comment by danielskatz** [comment]
yes, this is also causing a lot of slowness when I try to display the paper in github.

**Comment by danielskatz** [comment]
👋 @dglaeser - if you can reduce the size of the images without losing content, please do.  If not, that's ok.

**Comment by danielskatz** [comment]
Also note a bunch of references may be missing DOIs.  As you make changes to the .md, .bib, etc. please enter ```@whedon generate pdf``` as a new command here to check the results

**Comment by danielskatz** [comment]
👋 @dglaeser - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS last week, we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by dglaeser** [comment]
Thanks a lot for your quick responses! I fixed the missing and failing dois and downsampled some of the images

**Comment by dglaeser** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02263/joss.02263/10.21105.joss.02263.pdf)

**Comment by dglaeser** [comment]
@wheddon commands

**Comment by dglaeser** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by dglaeser** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18419/opus-289 is OK
- doi.org/10.1016/j.cageo.2015.04.012 is OK
- doi.org/10.1016/j.jhydrol.2015.08.065 is OK
- 10.5194/hess-23-19-2019 is OK
- 10.1016/j.cageo.2017.02.002 is OK
- 10.1016/j.advwatres.2011.03.007 is OK
- doi.org/10.1016/j.advwatres.2017.10.031 is OK
- doi.org/10.1007/s13137-019-0116-8 is OK
- 10.1002/nme.2579 is OK
- 10.1002/nme.6238 is OK
- 10.1016/j.advwatres.2017.10.036 is OK
- doi.org/10.1016/j.petrol.2019.106350 is OK
- 10.1016/j.jcp.2014.12.047 is OK
- 10.1016/j.jcp.2017.07.041 is OK
- doi.org/10.1007/s13137-019-0117-7 is OK
- 10.1016/j.cageo.2019.06.014 is OK
- doi.org/10.1007/s10596-018-9778-9 is OK
- 10.1016/j.jcp.2017.12.003 is OK
- doi.org/10.1007/s12665-014-3211-z is OK
- doi.org/10.1016/j.fuel.2011.08.037 is OK
- 10.1016/j.applthermaleng.2011.01.038 is OK
- 10.1016/j.rser.2014.04.068 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by diehlpk** [comment]
@danielskatz I would be interested to handle this paper, since it is related to much current research.

**Comment by danielskatz** [comment]
Thanks @diehlpk - you can claim it and start work by ```@whedon assign me as editor``` as a new comment here

**Comment by danielskatz** [comment]
You should also remove the waitlisted label

**Comment by diehlpk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @diehlpk

**Comment by diehlpk** [comment]
Hi, @dglaeser, I'll be serving as the editor for this submission.

**Comment by diehlpk** [comment]
@whedon assign @johntfoster as reviewer

**Comment by diehlpk** [comment]
@whedon assign @ilyasst as reviewer

**Comment by whedon** [comment]
OK, @ilyasst is now a reviewer

**Comment by diehlpk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02263/joss.02263/10.21105.joss.02263.pdf)

**Comment by diehlpk** [comment]
Hi, @dglaeser, if you do not want to do more changes to the paper or the repo, I will start the review process. Just let me know when I am good to go.

**Comment by dglaeser** [comment]
hi, @diehlpk, thanks for being the editor of this! From my side we can start the review process. Thanks a lot to all of you!

**Comment by diehlpk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2291.

**Comment by arfon** [comment]
:wave: @diehlpk - just a heads up that `assign` clobbers existing reviewer assignments so [this command](https://github.com/openjournals/joss-reviews/issues/2263#issuecomment-639101867) actually removed @johntfoster as a reviewer. If this wasn't what you wanted to do then you'll need to edit the issue body at the top of #2291 to add a checklist for both reviewers (this isn't something that Whedon can do yet).

**Comment by danielskatz** [comment]
For multiple reviewers, we usually whedon assign the first then whedon add the second.

**Comment by diehlpk** [comment]
@danielskatz and @arfon Thanks for explanation. I will do it correctly the next time.

**Comment by diehlpk** [comment]
@whedon add @johntfoster as reviewer

**Comment by whedon** [comment]
OK, @johntfoster is now a reviewer
