### ISSUE TITLE
[REVIEW]: itmlogic: Longley Rice Irregular Terrain Model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2266]
**Submitting author:** @edwardoughton (<a href="http://orcid.org/0000-0002-2766-008X">Edward J. Oughton</a>)
**Repository:** <a href="https://github.com/edwardoughton/itmlogic" target ="_blank">https://github.com/edwardoughton/itmlogic</a>
**Version:** v1.1
**Editor:** @danielskatz
**Reviewer:** @gorlapraveen, @garrettj403
**Archive:** <a href="https://doi.org/10.5281/zenodo.3931350" target="_blank">10.5281/zenodo.3931350</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e170845c6121712db6a71a1095a617e4/status.svg)](https://joss.theoj.org/papers/e170845c6121712db6a71a1095a617e4)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e170845c6121712db6a71a1095a617e4"><img src="https://joss.theoj.org/papers/e170845c6121712db6a71a1095a617e4/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e170845c6121712db6a71a1095a617e4/status.svg)](https://joss.theoj.org/papers/e170845c6121712db6a71a1095a617e4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/edwardoughton/itmlogic" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@gorlapraveen & @garrettj403, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/edwardoughton/itmlogic">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@edwardoughton) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/edwardoughton/itmlogic">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@edwardoughton) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @gorlapraveen, @garrettj403 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.tele.2019.01.003 is OK
- 10.1109/ACCESS.2019.2949460 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02266/joss.02266/10.21105.joss.02266.pdf)

**Comment by danielskatz** [comment]
👋 @gorlapraveen & @garrettj403 - thanks for agreeing to review this submission. Please be sure to read the comments above, and let me know if you have any questions.  Basically, your job is to check the article proof and repository and check items off your checklist above.

If you see small problems that need to be discussed, feel free to discuss them here.  But if you can, create a new issue in the <a href="https://github.com/edwardoughton/itmlogic" target="_blank">target repository</a> and linking to this review thread in that issue to create corresponding breadcrumb trail here.

I look forward to seeing how this review goes

**Comment by garrettj403** [comment]
Hello @edwardoughton, 

I have a couple comments on your paper:
- You wrote "... access to disparate user base ...". Do you mean "dispersed user base"?
- I think that "Longley-Rice" should be hyphenated.
- You should check the capitalization of the titles in your references. E.g., "The its irregular terrain model..." should be changed to "The ITS Irregular Terrain Model...".
- The final reference is wonky. You have the Institute for Telecommunication Sciences listed as the author.

Overall, the paper was very well-written. The software was also easy to install on my computer and I hope to finish reviewing the code in the next couple days.  Note: I had the same issue as @gorlapraveen  that he raised in [issue #34](https://github.com/edwardoughton/itmlogic/issues/34) (missing ``rasterstats`` package).

**Comment by danielskatz** [comment]
Thanks @garrettj403  - if you and @gorlapraveen can add a link to this issue (https://github.com/openjournals/joss-reviews/issues/2266) in any issues you open in the source repo, the will be flagged here and anyone looking at this issue will be able to tell if they are open or closed as well.

**Comment by edwardoughton** [comment]
Thank you for the review feedback @garrettj403 and @gorlapraveen, we're working to turn these corrections around.

**Comment by edwardoughton** [comment]
> Hello @edwardoughton,
> 
> I have a couple comments on your paper:
> 
> * You wrote "... access to disparate user base ...". Do you mean "dispersed user base"?
> * I think that "Longley-Rice" should be hyphenated.
> * You should check the capitalization of the titles in your references. E.g., "The its irregular terrain model..." should be changed to "The ITS Irregular Terrain Model...".
> * The final reference is wonky. You have the Institute for Telecommunication Sciences listed as the author.
> 
> Overall, the paper was very well-written. The software was also easy to install on my computer and I hope to finish reviewing the code in the next couple days. Note: I had the same issue as @gorlapraveen that he raised in [issue #34](https://github.com/edwardoughton/itmlogic/issues/34) (missing `rasterstats` package).

@garrettj403 I've now made most of those changes. I'm not sure the reference is wonky for the last entry in the bib as this is a citation of the website that releases the code. I think ITS seems like the right author, as it's their website, but I'm happy to be convinced otherwise.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02266/joss.02266/10.21105.joss.02266.pdf)

**Comment by danielskatz** [comment]
the bib problem is in formatting - please merge https://github.com/edwardoughton/itmlogic/pull/39 to fix it (and some other bib problems)

**Comment by danielskatz** [comment]
then you can put in a new comment here with ```@whedon generate pdf``` to regenerate the pdf.

**Comment by gorlapraveen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02266/joss.02266/10.21105.joss.02266.pdf)

**Comment by danielskatz** [comment]
@gorlapraveen - we need changes in the repo before it's useful to regenerate the pdf.

**Comment by edwardoughton** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02266/joss.02266/10.21105.joss.02266.pdf)

**Comment by edwardoughton** [comment]
@gorlapraveen @garrettj403 @danielskatz I think that fixed the bibliography ordering plus capitalizations. Please let me know if there is anything else.

**Comment by danielskatz** [comment]
I'm not sure why you made changes manually rather than just merging the PR.  You missed the {}s around MHz and GHz.  Otherwise, it looks ok to me.

**Comment by edwardoughton** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02266/joss.02266/10.21105.joss.02266.pdf)

**Comment by edwardoughton** [comment]
> I'm not sure why you made changes manually rather than just merging the PR. You missed the {}s around MHz and GHz. Otherwise, it looks ok to me.

Apologies Daniel, I missed the PR! Thanks for that. I hope this is resolved now.

**Comment by danielskatz** [comment]
no problem

**Comment by garrettj403** [comment]
Hi @edwardoughton 

I like that you provided two examples in the ``scripts/`` directory, but I think that they need a bit more explanation. For example, ``scripts/area.py`` doesn't have any inline comments past line 107, which makes it difficult to follow along. I raised this issue in [#43](https://github.com/edwardoughton/itmlogic/issues/43).

The testing looks good (I think), but again it's very difficult to follow along without any comments. For example, I'm looking at the test for ``lrprop`` (``test_lrprop.py``). Where does ``setup_expected_prop_to_test_lrprop`` come from? Were these results generated by the previous FORTRAN/C++/MATLAB code? I think that you should have a short docstring in each file to describe the general idea behind the test. I raised this issue in [#44](https://github.com/edwardoughton/itmlogic/issues/44).


Outside the scope of the JOSS review, I have a few general comments about the package:
   - The variable names are very short, usually only 2 or 3 letters. Python is somewhat self-documenting, but that doesn't really work when you have short variable names. For example, you use ``gme`` to represent the Earth's effective curvature, but normally in Python you would call this variable something like ``earth_eff_curv``. I assume that this is because you adopted the variable names from the old C++ code.
   - There are almost no inline comments, and since the variable names aren't obvious, it makes it very difficult to understand what's going on. I would suggest adding references. For example:
      ```python
      # Calculate attenuation
      # Eqn. 6.3 in The ITS Irregular Terrain Model, the Algorithm - G. Hufford
      ```
   - The package is flat (no sub-directories) and each function is in its own separate module. To make it easier to navigate, you may want to consider grouping similar functions into modules and similar modules into sub-packages. Again, I assume that this is because you adopted the structure of some old MATLAB code.

Overall, the package looks very useful. I think if you add a couple more comments to the ``scripts/`` and ``tests/`` directories, it will help new users to understand how package works and ensure that the package is maintainable. I'll be ready to sign off once issue [#43](https://github.com/edwardoughton/itmlogic/issues/43) and issue [#44](https://github.com/edwardoughton/itmlogic/issues/44) are addressed. Also, it looks like the build is failing right now, so that should be taken care of.

**Comment by danielskatz** [comment]
👋 @edwardoughton - This is just to make sure you've seen the comments and are working on responding to them...

**Comment by edwardoughton** [comment]
> 👋 @edwardoughton - This is just to make sure you've seen the comments and are working on responding to them...

Most of this is now complete @danielskatz, I'm just waiting for the authorship team to agree all the changes, and then I'll integrate the branch for @garrettj403 to review. I'm hoping this will be done by tomorrow.

**Comment by edwardoughton** [comment]
@danielskatz @garrettj403 

We've now completed our corrections and look forward to your response. 

Best wishes, 

Ed et al.

**Comment by danielskatz** [comment]
👋 @gorlapraveen & @garrettj403 - can you take a look at the changes, and see what else (if anything) you think needs to be done?

**Comment by garrettj403** [comment]
Hi @edwardoughton, the changes look great! The additional comments will definitely help new users get started with your code. 

@danielskatz, I'm ready to recommend publication. ``itmlogic`` was easy to install on my computer and all of the unit tests run smoothly without any errors. The package also has detailed documentation, which is hosted online. Overall, it looks like a very useful package with clear applications.

Great job!

**Comment by danielskatz** [comment]
thanks @garrettj403!

I now look forward to hearing from @gorlapraveen

**Comment by gorlapraveen** [comment]
Hi @edwardoughton, the functionality and the use of algorithms is technically quite satisfying. However,  I would also suggest you to document where User inputs can be given. Such as where to change the operating frequencies for different modes.  This would be my final comment and we can proceed for publication.

**Comment by edwardoughton** [comment]
@gorlapraveen I've now adapted the example running scripts and the documentation to reflect the main user defined parameters. This includes having a dict which contains the main parameters which the user can concisely state before calling the ``itmfunction``. Hopefully this makes things clearer. 

I also separated out the example scripts which use either 1 DEM tile or 2 DEM tiles, to overcome the issue of working across large areas which some users will need to deal with. The documentation also now reflects these changes. 

Thanks for the review feedback, Ed

**Comment by gorlapraveen** [comment]
@edwardoughton Thanks for the changes. Looks great!
@danielskatz I also recommend for publishing.

**Comment by edwardoughton** [comment]
Fantastic, thanks for the review @gorlapraveen.

**Comment by danielskatz** [comment]
thanks @gorlapraveen!

**Comment by danielskatz** [comment]
@edwardoughton  - at this point, please:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g. figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission, which will include me proofreading the paper and the references.

**Comment by edwardoughton** [comment]
> @edwardoughton - at this point, please:
> 
> * [x]  Make a tagged release of your software, and list the version tag of the archived version here.
> * [x]  Archive the reviewed software in Zenodo or a similar service (e.g. figshare, an institutional repository)
> * [x]  Check the archival deposit (e.g., in Zenodo) has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
> * [ ]  Please list the DOI of the archived version here.
> 
> I can then move forward with accepting the submission, which will include me proofreading the paper and the references.

Thanks @danielskatz, I should now have completed those tasks. Please let me know if I missed anything.  

DOI: 10.5281/zenodo.3931350

Zonodo link: https://zenodo.org/record/3931350#.XwLumihKh9M

**Comment by danielskatz** [comment]
@whedon set v1.1 as version

**Comment by whedon** [comment]
OK. v1.1 is the version.

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3931350 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3931350" target="_blank">10.5281/zenodo.3931350</a> is the archive.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02266/joss.02266/10.21105.joss.02266.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.tele.2019.01.003 is OK
- 10.1109/ACCESS.2019.2949460 is OK
- 10.1108/DPRG-02-2018-0004 is OK
- 10.1016/j.telpol.2017.07.009 is OK
- 10.1016/j.compenvurbsys.2020.101515 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1548

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1548, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1280109325328023553) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1549
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02266](https://doi.org/10.21105/joss.02266)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @gorlapraveen & @garrettj403 for reviewing! 

Congratulations to @edwardoughton (Edward J. Oughton) and co-authors!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02266/status.svg)](https://doi.org/10.21105/joss.02266)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02266">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02266/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02266/status.svg
   :target: https://doi.org/10.21105/joss.02266
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02266/status.svg)](https://doi.org/10.21105/joss.02266)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
