### ISSUE TITLE
[PRE REVIEW]: HOOMD-TF: GPU-Accelerated, Online Machine Learning in the HOOMD-blue Molecular Dynamics Engine

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2267]
**Submitting author:** @RainierBarrett (<a href="http://orcid.org/0000-0002-5728-9074">Rainier Barrett</a>)
**Repository:** <a href="https://github.com/ur-whitelab/hoomd-tf/" target ="_blank">https://github.com/ur-whitelab/hoomd-tf/</a>
**Version:** v0.6
**Editor:** @richardjgowers
**Reviewers:** @malramsay64, @rmeli
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @RainierBarrett. **Currently, there isn't an JOSS editor assigned** to your paper.

@RainierBarrett if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2267 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02267/joss.02267/10.21105.joss.02267.pdf)

**Comment by danielskatz** [comment]
@whedon check references from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper-branch
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1126/sciadv.1603015 is OK
- 10.1039/C6SC05720A is OK
- 10.1021/acscentsci.8b00913 is OK
- 10.1103/PhysRevLett.108.058301 is OK
- 10.1002/qua.24836 is OK
- 10.1002/adfm.201501919 is OK
- 10.1021/ct300857j is OK
- 10.1016/j.commatsci.2019.109363 is OK
-  10.25080/Majora-629e541a-00e  is OK
- 10.1002/jcc.21787 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @RainierBarrett - can you add a little more context about why you would use this software in the README?  The paper seems to have this context, but the README doesn't.

**Comment by danielskatz** [comment]
👋 @RainierBarrett - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS last week, we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.26 s (279.6 files/s, 47518.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          16            424           1066           2826
C++                              7            115            118            727
reStructuredText                17            371            467            526
C/C++ Header                     5            134            173            492
Jupyter Notebook                 8              0           2952            445
CSS                              1             91             11            405
CMake                            7            101             77            347
CUDA                             6             79             71            283
Dockerfile                       1             12              4             35
HTML                             1              6              0             14
make                             1              4              7              9
Markdown                         1              4              0              5
YAML                             2              1              2              4
-------------------------------------------------------------------------------
SUM:                            73           1342           4948           6118
-------------------------------------------------------------------------------


Statistical information for the repository '2267' was gathered on 2020/05/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andrew White                   247         12473          10408           56.47
DILNOZA AMIRKULOVA               5           325            209            1.32
Dilnoza Amirkulova               2           771            539            3.23
HETA ANILKUMAR GANDH             1            16             11            0.07
Heta Gandhi                     14           493            111            1.49
MAGHESREE CHAKRABORT             2            14              7            0.05
Maghesree Chakrabort             4          4379           4381           21.62
Rainier Barrett                 11          2514           1516            9.95
RainierBarrett                  20          1063            745            4.46
Sara Ali                         1             5              2            0.02
Ziyue Yang                       2            96             65            0.40
geemi725                         7           299             13            0.77
hgandhi2411                      3            37             29            0.16

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andrew White               3146           25.2         15.2               10.39
Dilnoza Amirkulova          416           54.0         12.0                5.29
Heta Gandhi                 359           72.8          4.3               14.21
MAGHESREE CHAKRABORT         10           71.4         14.5                0.00
Maghesree Chakrabort        160            3.7         11.1                0.62
Rainier Barrett             867           34.5          7.7               44.06
RainierBarrett              747           70.3         11.0               29.59
Sara Ali                      1           20.0          2.6                0.00
Ziyue Yang                   90           93.8          2.4                1.11
geemi725                    279           93.3          0.1                7.53
```

**Comment by richardjgowers** [comment]
@danielskatz I could be editor on this one

**Comment by arfon** [comment]
@richardjgowers great! Please go ahead and assign yourself.

**Comment by danielskatz** [comment]
I'll go ahead and do this, this time, but as @arfon said, you can also just do this yourself, exactly as follows

**Comment by danielskatz** [comment]
@whedon assign @richardjgowers as editor

**Comment by whedon** [comment]
OK, the editor is @richardjgowers

**Comment by richardjgowers** [comment]
@keipertk @malramsay64 @pszi1ard would you be available to review this?

**Comment by RainierBarrett** [comment]
Hi guys, thanks for the quick turn around. I added a brief blurb in the README about the main benefits of HOOMD-TF. Let me know what you think.

**Comment by malramsay64** [comment]
@richardjgowers I am currently available to review.

**Comment by richardjgowers** [comment]
@whedon add @malramsay64 as reviewer

**Comment by whedon** [comment]
OK, @malramsay64 is now a reviewer

**Comment by richardjgowers** [comment]
@rmeli would you be interested in reviewing this?

**Comment by RMeli** [comment]
@richardjgowers Looks interesting, count me in.

**Comment by richardjgowers** [comment]
@whedon add @rmeli as a reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by richardjgowers** [comment]
@whedon add @rmeli as reviewer

**Comment by whedon** [comment]
OK, @rmeli is now a reviewer

**Comment by arfon** [comment]
:wave: @richardjgowers - this looks like it's ready to move forward to review?

**Comment by richardjgowers** [comment]
Yeah I was waiting to see if one of the earlier invitees with GPU knowledge
wanted to step in but we can proceed with the current reviewers.

**Comment by richardjgowers** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2367.
