### ISSUE TITLE
[PRE REVIEW]: COVID-19 Data Hub

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2268]
**Submitting author:** ArdiaD (<a href="http://orcid.org/0000-0003-2823-782X">David Ardia</a>)
**Repository:** <a href="https://github.com/covid19datahub/JOSS" target ="_blank">https://github.com/covid19datahub/JOSS</a>
**Version:** 2.0.5
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS ArdiaD. **Currently, there isn't an JOSS editor assigned** to your paper.

ArdiaD if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.07 s (70.7 files/s, 9063.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              1              0              2            441
Markdown                         2             25              0             54
TeX                              1              4              0             37
Rmd                              1             23             54              1
-------------------------------------------------------------------------------
SUM:                             5             52             56            533
-------------------------------------------------------------------------------


Statistical information for the repository '2268' was gathered on 2020/05/28.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/s1473-3099(20)30120-1 may be missing for title: An interactive web-based dashboard to track COVID-19 in real time

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02268/joss.02268/10.21105.joss.02268.pdf)

**Comment by danielskatz** [comment]
👋  @ArdiaD - I'm going to mark this as withdrawn, but please resubmit, with

- an @ as part of your username
- the paper in the software repository, and the software repository as the submission

This submission doesn't have any software in it, which can be easily fixed.

**Comment by danielskatz** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.

**Comment by ArdiaD** [comment]
Hi @danielskatz will resubmit now. Not sure about your comment "resubmit with an @ as part of your username"; should I mention this in the "Message to editors". Thanks

**Comment by danielskatz** [comment]
in the top line of the first comment in this issue, based on the data you submitted, I see
Submitting author: ArdiaD (David Ardia)
this should be
Submitting author: @ArdiaD (David Ardia)
But as I look at the submission form, I don't see how that this is something you control, so maybe don't worry about it

**Comment by ArdiaD** [comment]
I see; this might be because I am logging in via ORCID instead of GitHub. Thanks for your help. Will resubmit now and select you are Editor. Thx again

**Comment by danielskatz** [comment]
no, you don't need to select me as editor - I'm just the Associate Editor-in-Chief on duty this week...

**Comment by ArdiaD** [comment]
I see; resubmitted without specific Editor. Thanks
