### ISSUE TITLE
[PRE REVIEW]: pypillometry: A Python package for pupillometric analyses

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2269]
**Submitting author:** @ihrke (<a href="http://orcid.org/0000-0003-0205-7353">Matthias Mittner</a>)
**Repository:** <a href="https://github.com/ihrke/pypillometry" target ="_blank">https://github.com/ihrke/pypillometry</a>
**Version:** v1.0.0
**Editor:** @oliviaguest
**Reviewers:** @samhforbes, @szorowi1
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ihrke. **Currently, there isn't an JOSS editor assigned** to your paper.

@ihrke if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.88 s (76.4 files/s, 35171.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            21            462              0           8648
JavaScript                       9           2201           2234           8331
Python                          14            597           1361           1683
CSS                              3            210             42            837
Jupyter Notebook                 8              0           3237            441
reStructuredText                 7            145            127            115
TeX                              1              9              0             97
Markdown                         2             15              0             32
make                             1              4              7              9
YAML                             1              0              2              7
-------------------------------------------------------------------------------
SUM:                            67           3643           7010          20200
-------------------------------------------------------------------------------


Statistical information for the repository '2269' was gathered on 2020/05/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Matthias Mittner                62         17207            800          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Matthias Mittner          16407           95.4          5.7               15.68
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3758/s13428-020-01374-8 is OK

MISSING DOIs

- https://doi.org/10.5334/joc.18 may be missing for title: Pupillometry: Psychology, physiology, and function
- https://doi.org/10.1126/science.132.3423.349 may be missing for title: Pupil size as related to interest value of visual stimuli
- https://doi.org/10.1146/annurev.neuro.28.061604.135709 may be missing for title: An integrative theory of locus coeruleus-norepinephrine function: adaptive gain and optimal performance
- https://doi.org/10.3758/cabn.10.2.252 may be missing for title: Pupil diameter tracks changes in control state predicted by the adaptive gain theory of locus coeruleus function

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02269/joss.02269/10.21105.joss.02269.pdf)

**Comment by danielskatz** [comment]
👋 @ihrke - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS last week, we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

(In the meantime, feel free to make fixes to the paper, such as adding missing DOIs, etc. - add ```@whedon generate pdf``` as a new comment in this thread to build the pdf)

**Comment by ihrke** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2269 with the following error: 

 Error reading bibliography ./paper.bib (line 9, column 3):
unexpected "p"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by ihrke** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02269/joss.02269/10.21105.joss.02269.pdf)

**Comment by ihrke** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3758/s13428-020-01374-8 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.5334/joc.18 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1126/science.132.3423.349 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1146/annurev.neuro.28.061604.135709 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.3758/cabn.10.2.252 is INVALID because of 'https://doi.org/' prefix
```

**Comment by ihrke** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5334/joc.18 is OK
- 10.1126/science.132.3423.349 is OK
- 10.3758/s13428-020-01374-8 is OK
- 10.1146/annurev.neuro.28.061604.135709 is OK
- 10.3758/cabn.10.2.252 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by ihrke** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02269/joss.02269/10.21105.joss.02269.pdf)

**Comment by labarba** [comment]
👋  @oliviaguest — Could you have a look at this submission and let us know if you can handle it as editor? I realize you are handling four other submissions, but perhaps you can accept this on a 'best effort' basis (we have more than 30 submissions in the backlog).

Title — pypillometry: A Python package for pupillometric analyses
[ Article proof](https://github.com/openjournals/joss-papers/blob/joss.02269/joss.02269/10.21105.joss.02269.pdf)

**Comment by labarba** [comment]
@whedon invite @oliviaguest as editor

**Comment by oliviaguest** [comment]
Oh, wow — very similar to: https://joss.theoj.org/papers/65fdd6bc59eb558543282e93140eb31e but in Python! Fun!

**Comment by oliviaguest** [comment]
I'm down. 👍

**Comment by labarba** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by danielskatz** [comment]
👋 @oliviaguest - just as a reminder, you can make it easier for the AEiC: if you are willing to edit a submission, issue ```@whedon assign me as editor```, and remove the waitlisted label if there is one.

**Comment by oliviaguest** [comment]
Aha, I did not know this, @danielskatz. Ta!

**Comment by oliviaguest** [comment]
@whedon add @samhforbes as reviewer

**Comment by whedon** [comment]
OK, @samhforbes is now a reviewer

**Comment by ihrke** [comment]
Thanks @oliviaguest for handling the submission! Surprised and glad to see @samhforbes 's PupillometryR - looks like there are finally some good tools emerging for pupillometry! Looking forward to the review process!

**Comment by oliviaguest** [comment]
@ihrke do you have any ideas for reviewers? I have a few in mind but people are (understandably) very busy these days — so the more names to try the merrier!

**Comment by ihrke** [comment]
Ignace Hooge perhaps? He is an expert in eyetracking/pupillometry but I don't know how good his Python is: https://www.uu.nl/staff/ihooge/Contact

**Comment by oliviaguest** [comment]
Really down on our luck here with many relevant people being busy, @ihrke — of course I will keep trying and any new names you think of... please pop them in this thread so I can try them. ☺️

**Comment by ihrke** [comment]
I looked at the list of JOSS reviewers and found the following people that I think competent to review this submission (in - very rough - order of perceived goodness-of-fit based on their description): 

szorowi1
sappelhoff
marcoapintoo
agricolab
lukassnoek
jsheunis
faroit
SebastianoF

let me know if you need more names...

**Comment by oliviaguest** [comment]
@whedon add @szorowi1 as reviewer

**Comment by whedon** [comment]
OK, @szorowi1 is now a reviewer

**Comment by oliviaguest** [comment]
Wow, two Sams! I should probably change my name to Sam as should @whedon and @ihrke to avoid confusion. Anyway, fantastic to have all these Sams on board — thank you all!

Let's get the review started!

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2348.

**Comment by oliviaguest** [comment]
Head on over to #2348 to start the process. 😸
