### ISSUE TITLE
[PRE REVIEW]: libqcpp: A C++14 sequence quality control library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#227]
**Submitting author:** @kdmurray91 (<a href="http://orcid.org/0000-0002-2466-1917">Kevin Murray</a>)
**Repository:** <a href="https://github.com/kdmurray91/libqcpp" target ="_blank">https://github.com/kdmurray91/libqcpp</a>
**Version:** 0.4.0
**Editor:** @arfon
**Reviewer:** @luizirber

**Author instructions**

Thanks for submitting your paper to JOSS @kdmurray91. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@kdmurray91 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @tracykteal it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @tracykteal - the submitting author suggested you would be a good editor for this submission. Let me know if this is an issue :-)

**Comment by kdmurray91** [comment]
Hi all, @ctb & @luizirber could be possible reviewers :smile:

**Comment by luizirber** [comment]
yes, I can review it

**Comment by arfon** [comment]
@whedon assign @luizirber as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @luizirber

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon start-review magic-word=bananas

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/232. Feel free to close this issue now!

**Comment by arfon** [comment]
@luizirber please head over to #232 to carry out the review.

**Comment by kdmurray91** [comment]
Thanks very much @luizirber!
