### ISSUE TITLE
[PRE REVIEW]: GPP, the Generic Preprocessor

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2270]
**Submitting author:** @Logological (<a href="http://orcid.org/0000-0002-0749-1100">Tristan Miller</a>)
**Repository:** <a href="https://github.com/logological/gpp.git" target ="_blank">https://github.com/logological/gpp.git</a>
**Version:** 2.26
**Editor:** @gkthiruvathukal
**Reviewers:** @Smattr, @drj11
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Logological. **Currently, there isn't an JOSS editor assigned** to your paper.

@Logological if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-3-642-37521-7_5 is OK
- 10.1109/WCRE.2001.957833 is OK
- 10.1145/363717.363746 is OK
- 10.1016/0066-4138(69)90001-9 is OK
- 10.1109/TSE.2002.1158288 is OK
- 10.1145/2211616.2211617 is OK
- 10.1093/comjnl/28.1.29 is OK
- 10.1007/978-1-4842-5149-2_10 is OK
- 10.1145/367177.367223 is OK
- 10.1145/987316.987320 is OK
- 10.1145/800197.806048 is OK
- 10.1109/IPCC.1992.673146 is OK
- 10.1093/comjnl/8.3.225 is OK

MISSING DOIs

- https://doi.org/10.1093/comjnl/23.3.194 may be missing for title: Structured Programming in COBOL—The Current Options

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02270/joss.02270/10.21105.joss.02270.pdf)

**Comment by danielskatz** [comment]
Note: @gkthiruvathukal was suggested as the editor

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.14 s (66.0 files/s, 38329.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                                1            236            137           2861
Pascal                           1             21             59           1377
TeX                              1             31              0            297
Markdown                         2             34              0             96
m4                               1              8              0             21
make                             3              9             27             16
-------------------------------------------------------------------------------
SUM:                             9            339            223           4668
-------------------------------------------------------------------------------


Statistical information for the repository '2270' was gathered on 2020/05/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Tristan Miller                  39          7164           3930           99.98
gavanderhoorn                    1             1              1            0.02

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Tristan Miller             3233           45.1         41.0                7.55
gavanderhoorn                 1          100.0         44.6                0.00
```

**Comment by danielskatz** [comment]
👋 @logological - thanks for your submission.  A few checks are needed now, then we'll likely move this to a waiting list due to the very large number of submissions we've had this week.  More info to follow...

**Comment by logological** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02270/joss.02270/10.21105.joss.02270.pdf)

**Comment by logological** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-3-642-37521-7_5 is OK
- 10.1109/WCRE.2001.957833 is OK
- 10.1145/363717.363746 is OK
- 10.1016/0066-4138(69)90001-9 is OK
- 10.1109/TSE.2002.1158288 is OK
- 10.1145/2211616.2211617 is OK
- 10.1093/comjnl/28.1.29 is OK
- 10.1007/978-1-4842-5149-2_10 is OK
- 10.1145/367177.367223 is OK
- 10.1145/987316.987320 is OK
- 10.1145/800197.806048 is OK
- 10.1109/IPCC.1992.673146 is OK
- 10.1093/comjnl/8.3.225 is OK
- 10.1093/comjnl/23.3.194 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by logological** [comment]
@danielskatz Thanks!  Looking forward to the process, whenever it may begin…

**Comment by gkthiruvathukal** [comment]
Hi, @logological, I'll be serving as the editor for this submission. About to assign myself. I will be asking you to suggest potential reviewers from our list (see the top of this the thread).

**Comment by gkthiruvathukal** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by logological** [comment]
Hello, @gkthiruvathukal.  The following reviewers seem to be qualified: bzz, kokan, rljacobson, smattr.  Let me know if you need more suggestions than this.

**Comment by gkthiruvathukal** [comment]
@bzz and @kokan, would you be willing to serve as reviewers for this JOSS submission?

**Comment by gkthiruvathukal** [comment]
@rljacobson and smattr, would you be willing to serve as reviewers for this JOSS submission?

**Comment by gkthiruvathukal** [comment]
@smattr, oops, I forgot the mention symbol...  would you be willing to serve as reviewers for this JOSS submission?

**Comment by Smattr** [comment]
Yes, certainly. I'm not qualified to review the Pascal, but I can review the C. I've had a lot of experience with CPP and M4, so I should also be able to review the usability/functionality too.

**Comment by logological** [comment]
@Smattr, don't be misled by whedon's automated analysis, which is full of false positives. The software described in the paper is written entirely in C.  There's no Pascal, no C++, and no M4 (except insofar as that's what the Autotools configuration files are processed with, though you won't need to touch those if you build from the portable source packages).

**Comment by gkthiruvathukal** [comment]
@Smattr, @logological is right. We do see these false positives in the language analysis now and then.

@Smattr I'm going to assign you as a reviewer. I still need to get one more, so it may be a little while before we get started with the review.

**Comment by whedon** [comment]
OK, @Smattr is now a reviewer

**Comment by logological** [comment]
@gkthiruvathukal: So far only one of the four nominated reviewers has responded. Here are some further nominations, in case you need them: drj11, davidbeckingsale, smiths

**Comment by gkthiruvathukal** [comment]
@logological Thanks. I will try one of them now!

**Comment by gkthiruvathukal** [comment]
@davidbeckingsale, would you be willing to serve as reviewers for this JOSS submission?

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale, would you be willing to serve as reviewers for this JOSS submission?

I don't have the bandwidth for this right now, so will decline. Thanks for considering me.

**Comment by Smattr** [comment]
Just to confirm: I'm not meant to start my review until you've found a second reviewer, right?

**Comment by gkthiruvathukal** [comment]
@Smattr That's correct. You are certainly welcome to start looking things over until the review thread is formally opened. Going to try to get the second reviewer assigned. Thanks!

**Comment by gkthiruvathukal** [comment]
@smiths or @drj11, are either of you willing to contribute a review for this JOSS submission?

**Comment by drj11** [comment]
in principle yes I can review this JOSS submission. It would be my first review for JOSS. Are there guidelines for reviewers?

**Comment by gkthiruvathukal** [comment]
@drj11 Thanks for responding. As a matter of fact, we do have guidelines at https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?

I hope I can interpret your response as a "yes". I'll be happy to help with any questions during the process.

**Comment by drj11** [comment]
@gkthiruvathukal Yes you can interpret my response as a "yes". :)

**Comment by gkthiruvathukal** [comment]
Thanks, @drj11!

I will start the review now....

**Comment by gkthiruvathukal** [comment]
@whedon add @drj11 as reviewer

**Comment by whedon** [comment]
OK, @drj11 is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2400.

**Comment by smiths** [comment]
Looks like I missed my chance.  I'll be quicker to say yes on the next request.  :smile:

**Comment by gkthiruvathukal** [comment]
@smiths I will definitely call upon you soon. Thank you for responding!
