### ISSUE TITLE
[PRE REVIEW]: COVID-19 Data Hub

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2271]
**Submitting author:** @ArdiaD (<a href="http://orcid.org/0000-0003-2823-782X">David Ardia</a>)
**Repository:** <a href="https://github.com/covid19datahub/COVID19/" target ="_blank">https://github.com/covid19datahub/COVID19/</a>
**Version:** 2.0.7
**Editor:** @will-rowe
**Reviewers:** @linuxscout, @mbod
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS ArdiaD. **Currently, there isn't an JOSS editor assigned** to your paper.

ArdiaD if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.37 s (729.3 files/s, 49996.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Rmd                            204           3663           5088           5438
R                               54            727            697           1518
Markdown                         6             77              0            548
XML                              1              0              2            441
YAML                             2             18              1            113
TeX                              1              4              0             37
-------------------------------------------------------------------------------
SUM:                           268           4489           5788           8095
-------------------------------------------------------------------------------


Statistical information for the repository '2271' was gathered on 2020/05/28.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/s1473-3099(20)30120-1 may be missing for title: An interactive web-based dashboard to track COVID-19 in real time

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02271/joss.02271/10.21105.joss.02271.pdf)

**Comment by danielskatz** [comment]
from the author
> We point toward the R package for the Data Hub, but are actually asking for the review of the full data hub. The distinction is clear in the paper I believe.

**Comment by danielskatz** [comment]
👋 @ArdiaD - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS last week, we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

(In the meantime, feel free to make any needed fixes to the paper, such as adding the possibly missing DOI, etc. - add ```@whedon generate pdf``` as a new comment in this thread to build the pdf)

**Comment by mbod** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by mbod** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by mbod** [comment]
@ArdiaD would be happy to review

**Comment by danielskatz** [comment]
I'm confused by this, since @ArdiaD is the author

**Comment by ArdiaD** [comment]
indeed I am a co-author ;)

**Comment by mbod** [comment]
if looking for reviewers still I would be happy to review

**Comment by ArdiaD** [comment]
@danielskatz I am happy if @mbod reviews the data hub

**Comment by danielskatz** [comment]
Thanks @mbod for volunteering. As you can see, this submission is currently waitlisted, so there's not even an editor assigned yet, who will pick reviewers.  We'll keep your offer here for the editor to potentially accept once the submission moves off the waitlist.

**Comment by kyleniemeyer** [comment]
Hi @will-rowe, do you have the bandwidth to take this submission on?

**Comment by kyleniemeyer** [comment]
@whedon invite @will-rowe as editor

**Comment by whedon** [comment]
@will-rowe has been invited to edit this submission.

**Comment by will-rowe** [comment]
Hi @kyleniemeyer. I'd be happy to make time for this - it looks great!

**Comment by will-rowe** [comment]
@whedon assign @will-rowe as editor

**Comment by whedon** [comment]
OK, the editor is @will-rowe

**Comment by will-rowe** [comment]
Hi @mbod - are you still happy to review?

**Comment by will-rowe** [comment]
Hi @HadrienG - would you be interested in reviewing this JOSS submission?

**Comment by will-rowe** [comment]
Hi @mbod - just pinging you again to see if you can review. If no reply, I'll find some additional reviewers

**Comment by will-rowe** [comment]
Hi @linuxscout and @MDebasish - are either of you able to review this submission to JOSS please?

**Comment by linuxscout** [comment]
Ok.

**Comment by will-rowe** [comment]
Great - thanks very much @linuxscout. We're still waiting on one more reviewer before I start the review process. I'll ping you again when we're ready.

**Comment by will-rowe** [comment]
@whedon assign @linuxscout as reviewer

**Comment by whedon** [comment]
OK, @linuxscout is now a reviewer

**Comment by linuxscout** [comment]
Salam,
Where can I find the paper and the check list to do?
Thanks

**Comment by ArdiaD** [comment]
thx @linuxscout for reviewing the paper and the data hub. The paper is here: https://github.com/covid19datahub/COVID19/tree/master/inst/joss => PDF

**Comment by ArdiaD** [comment]
The checklist (at least the steps) are reported here: https://joss.readthedocs.io/en/latest/review_checklist.html#
I guess you'll have access to a real "check box" page with all these points mentioned. Am I correct @will-rowe ?

**Comment by will-rowe** [comment]
Hi @linuxscout and @ArdiaD. Thanks for posting the docs - they are correct. There will be a full checklist for you to fill in when we start the review - you will get tagged in a new thread.

Sorry this has taken a while to get started @ArdiaD, hopefully I will have another reviewer soon. I'll give it another couple of days and then I'll do the review if we can't find anyone.

**Comment by will-rowe** [comment]
Hi @leomrtns - I don't suppose you could review this submission for us?

**Comment by mbod** [comment]
Yes am happy to review

**Comment by ArdiaD** [comment]
thx @will-rowe. I think we have now @linuxscout and @mbod which are willing to start the review

**Comment by will-rowe** [comment]
Great - thanks @mbod. Let's start the review process. I'll assign @mbod and @linuxscout - then the review will be tracked in a new thread and this one will close.

**Comment by will-rowe** [comment]
@whedon add @mbod as reviewer

**Comment by whedon** [comment]
OK, @mbod is now a reviewer

**Comment by will-rowe** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2376.

**Comment by leomrtns** [comment]
@will-rowe I guess you sorted it out? in any case if you need me, just let me know. cheers

**Comment by will-rowe** [comment]
I did - thanks @leomrtns!
