### ISSUE TITLE
[REVIEW]: rgee: An R package for interacting with Google Earth Engine

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2272]
**Submitting author:** @csaybar (<a href="http://orcid.org/0000-0003-2745-9535">Cesar Luis Aybar Camacho</a>)
**Repository:** <a href="https://github.com/r-spatial/rgee" target ="_blank">https://github.com/r-spatial/rgee</a>
**Version:** v1.0.0
**Editor:** @hugoledoux
**Reviewers:** @appelmar, @gena, @jhollist
**Archive:** <a href="https://doi.org/10.5281/zenodo.3947571" target="_blank">10.5281/zenodo.3947571</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/aea42ddddd79df480a858bc1e51857fc/status.svg)](https://joss.theoj.org/papers/aea42ddddd79df480a858bc1e51857fc)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/aea42ddddd79df480a858bc1e51857fc"><img src="https://joss.theoj.org/papers/aea42ddddd79df480a858bc1e51857fc/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/aea42ddddd79df480a858bc1e51857fc/status.svg)](https://joss.theoj.org/papers/aea42ddddd79df480a858bc1e51857fc)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/r-spatial/rgee" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@appelmar & @gena, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @hugoledoux know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/r-spatial/rgee">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@csaybar) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/r-spatial/rgee">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@csaybar) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/r-spatial/rgee">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@csaybar) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @appelmar, @gena it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/j.rse.2017.06.031 may be missing for title: Google Earth Engine: Planetary-scale geospatial analysis for everyone
- https://doi.org/10.1038/sdata.2017.191 may be missing for title: TerraClimate, a high-resolution global dataset of monthly climate and climatic water balance from 1958–2015

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02272/joss.02272/10.21105.joss.02272.pdf)

**Comment by hugoledoux** [comment]
@whedon add @jhollist as reviewer

**Comment by whedon** [comment]
OK, @jhollist is now a reviewer

**Comment by csaybar** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by csaybar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02272/joss.02272/10.21105.joss.02272.pdf)

**Comment by hugoledoux** [comment]
👋 @appelmar @gena @jhollist I was wondering if you need any help/instructions at this point or if I can help?

**Comment by jhollist** [comment]
@hugoledoux  thanks for the reminder on this.  I am all set, just need to clone myself!  Hoping to work on the review this week.

**Comment by gena** [comment]
Same here. I will write a review over the weekend or beginning of the next week.

**Comment by appelmar** [comment]
Same here, too. I'll finish the review next week at the latest.

**Comment by hugoledoux** [comment]
@whedon add @gena as reviewer

**Comment by whedon** [comment]
OK, @gena is now a reviewer

**Comment by jhollist** [comment]
@csaybar Really nice job!  I have posted a new issue on your repo (https://github.com/r-spatial/rgee/issues/68) with some more detailed review comments.  Any questions, let me know.

**Comment by csaybar** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS
. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02272/joss.02272/10.21105.joss.02272.pdf)

**Comment by jhollist** [comment]
@hugoledoux and @csaybar  I have completed the checklist and the edits (https://github.com/r-spatial/rgee/pull/69) made in response to my review (https://github.com/r-spatial/rgee/issues/68) all look great.  Again, really nice job on this package.

**Comment by csaybar** [comment]
Thank @jhollist for your comments and suggestions :). They were addressed here r-spatial/rgee#69

**Comment by appelmar** [comment]
Great work @csaybar. Please find my detailed review with some minor comments in a separate issue in your repo (see  r-spatial/rgee#70). Let me know if you have questions.

**Comment by appelmar** [comment]
@hugoledoux I can't fill out the checklist in this issue, did I miss something?

**Comment by danielskatz** [comment]
> I can't fill out the checklist in this issue, did I miss something?

As stated at the top:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

If these don't solve the problem, ping again

**Comment by appelmar** [comment]
Thanks @danielskatz. I am logged in but I might have missed to accept the invitation when this issue was started, now getting _"Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account."_. Could you invite me again? Sorry for the inconvenience.

**Comment by danielskatz** [comment]
@whedon re-invite @appelmar as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@appelmar please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by gena** [comment]
I've added my review https://github.com/r-spatial/rgee/issues/72, it's short, not a lot to add to other reviews.

**Comment by csaybar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02272/joss.02272/10.21105.joss.02272.pdf)

**Comment by csaybar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02272/joss.02272/10.21105.joss.02272.pdf)

**Comment by hugoledoux** [comment]
@csaybar has https://github.com/r-spatial/rgee/issues/72 been completely solved? It seems yes but you left it open. It seems all reviewers are happy now, and if this issue is closed then we can move towards acceptance and the final steps.

**Comment by csaybar** [comment]
Hi @hugoledoux sorry for the last reply. We are waiting for the response of @appelmar (r-spatial/rgee#70)!.

**Comment by appelmar** [comment]
No need to wait, all good from my side!

**Comment by csaybar** [comment]
@appelmar @gena @hugoledoux  Thank you very much for your time and support in reviewing rgee.

**Comment by hugoledoux** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.rse.2017.06.031 is OK
- 10.1002/wics.147 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by hugoledoux** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02272/joss.02272/10.21105.joss.02272.pdf)

**Comment by hugoledoux** [comment]
@csaybar there's a glitch with your PDF, see this:

![CleanShot 2020-07-15 at 08 03 01@2x](https://user-images.githubusercontent.com/1546518/87509593-2bb3da80-c672-11ea-91aa-8de832a7f860.png)

Something goes wrong with a function name with "$ and it doesn't escape, I think you should modify at l.45 
```
("$getInfo")
```
=> 
```
`($getInfo)`
```

**Comment by hugoledoux** [comment]
also, shouldn't the reference to mapview be the package/website? I tried to find the paper, but couldn't in 2min, while the website is complete, informative, etc. If you want to stick to the paper at EGU, please provide a DOI

**Comment by hugoledoux** [comment]
@csaybar the 3 reviewers recommend acceptance, and I'm happy to say that we're reaching the end of the review!

At this point could you:

- [ ] Fix the 2 issues I pointed above
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g. figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.

Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by csaybar** [comment]
Dear @hugoledoux thanks for the fast response. I've made the requested changes.
- I changed ("$getInfo") by ("\$getInfo") the problem will be fixed now. With respect to the citation to mapview we now refer to the R package manual instead of the publication in EGU.
- rgee [v.0.5.0](https://github.com/r-spatial/rgee/releases/tag/v.0.5.0).
- rgee is archived in zenodo [here](https://zenodo.org/record/3946739).

**Comment by csaybar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02272/joss.02272/10.21105.joss.02272.pdf)

**Comment by hugoledoux** [comment]
@csaybar I am confused, you have a v1.0.0 release, but also you made one for v.0.5.0? Your releases have 2 options for one repository? This is new to me, and rather confusing... Can you shed some light on why that is?

**Comment by csaybar** [comment]
Hi Hugo, after submitting rgee version 0.5.0 to JOSS I was making some additional changes that were reflected in new versions of rgee. Version 1.0.0 has all the changes made to pass the issues pointed out by the reviewers. However, I was not sure which version should be used if version 0.5.0 or 1.0.0. Sorry if this is a bit confusing.

**Comment by hugoledoux** [comment]
ah right, then if you released v1.0.0 based on all reviews than it should be v.1.0.0 for JOSS, this is a nice outcome too.

Could you make a new Zenodo release (pointing to v1.0.0) and list the DOI here please?

**Comment by csaybar** [comment]
@hugoledoux  I've made the requested changes.

- Archived rgee v.1.0.0 in Zenodo [here](https://zenodo.org/record/3945409).
- rgee v.1.0.0 Zenodo citation: Cesar Aybar, Qiusheng Wu, Lesly Bautista, Roy Yali, & Antony Barja. (2020, July 14). rgee: An R package for interacting with Google Earth Engine (Version v.1.0.0). Zenodo. http://doi.org/10.5281/zenodo.3945409

**Comment by hugoledoux** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02272/joss.02272/10.21105.joss.02272.pdf)

**Comment by hugoledoux** [comment]
two small things: 

1. https://github.com/r-spatial/rgee/pull/74 

2. there is something strange with your zenodo, if I go to the v1.0.0 I get that warning, which redirects me to v0.5.0, not sure why... could you look into this?

![CleanShot 2020-07-16 at 08 34 27@2x](https://user-images.githubusercontent.com/1546518/87635449-5cae1100-c73f-11ea-89a8-6acc7069b3b1.png)

**Comment by csaybar** [comment]
@hugoledoux Sorry for the inconvenience, but I had to create a new archived in Zenodo to solve the issue.

- New archived rgee v.1.0.0 in Zenodo [here](https://zenodo.org/record/3947571).
- rgee v.1.0.0 Zenodo citation: Cesar Aybar, Qiusheng Wu, Lesly Bautista, Roy Yali, & Antony Barja. (2020, July 16). rgee: An R package for interacting with Google Earth Engine (Version v.1.0.0). Zenodo. http://doi.org/10.5281/zenodo.3947571
- Thanks for the PR, I added it to the master branch.

**Comment by hugoledoux** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02272/joss.02272/10.21105.joss.02272.pdf)

**Comment by hugoledoux** [comment]
@whedon set 10.5281/zenodo.3947571 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3947571" target="_blank">10.5281/zenodo.3947571</a> is the archive.

**Comment by hugoledoux** [comment]
@whedon set v1.0.0 as version

**Comment by whedon** [comment]
OK. v1.0.0 is the version.

**Comment by hugoledoux** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.rse.2017.06.031 is OK
- 10.1002/wics.147 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by hugoledoux** [comment]
Congratulations @csaybar  your submission is now accepted! Your paper will be handled and published in the near future.

Thanks to @gena , @jhollist and @appelmar  for the reviews and feedback!

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1578

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1578, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1283684448316329986) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1580
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02272](https://doi.org/10.21105/joss.02272)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @csaybar, your JOSS paper is published! 🚀 

Huge thanks to our editor: @hugoledoux, and reviewers: @appelmar, @gena, @jhollist 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02272/status.svg)](https://doi.org/10.21105/joss.02272)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02272">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02272/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02272/status.svg
   :target: https://doi.org/10.21105/joss.02272
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02272/status.svg)](https://doi.org/10.21105/joss.02272)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
