### ISSUE TITLE
[PRE REVIEW]: memr: An R package for medical free-text records embedding and visualization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2273]
**Submitting author:** @adamgdobrakowski (<a href="http://orcid.org/0000-0001-6460-3079">Adam Dobrakowski</a>)
**Repository:** <a href="https://github.com/MI2DataLab/memr" target ="_blank">https://github.com/MI2DataLab/memr</a>
**Version:** v0.1.0
**Editor:** @karthik
**Reviewers:** @cmaimone,  @timchurches
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @adamgdobrakowski. **Currently, there isn't an JOSS editor assigned** to your paper.

@adamgdobrakowski if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.3115/v1/d14-1162 may be missing for title: Glove: Global vectors for word representation

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02273/joss.02273/10.21105.joss.02273.pdf)

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.12 s (409.8 files/s, 76494.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            26           1310            313           4388
R                               11            117            586            919
Markdown                         3             95              0            372
CSS                              2             73             35            296
JavaScript                       2             41             16            141
Rmd                              1             41            103             47
TeX                              1              5              0             45
SVG                              1              0              1             11
YAML                             1              1              0              4
-------------------------------------------------------------------------------
SUM:                            48           1683           1054           6223
-------------------------------------------------------------------------------


Statistical information for the repository '2273' was gathered on 2020/05/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adam Gabriel Dobrako             1           198              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adam Gabriel Dobrako        198          100.0          0.0                8.08
```

**Comment by danielskatz** [comment]
👋 @adamgdobrakowski - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS last week, we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

(In the meantime, feel free to make any needed fixes to the paper, such as adding the possibly missing DOI, etc. - add ```@whedon generate pdf``` as a new comment in this thread to build the pdf)

**Comment by adamgdobrakowski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02273/joss.02273/10.21105.joss.02273.pdf)

**Comment by labarba** [comment]
👋 @karthik — Could you have a look at this submission and let us know if you can handle it as editor? Perhaps you can accept this on a 'best effort' basis (we have more than 30 submissions in the backlog).

Title: _memr: An R package for medical free-text records embedding and visualization_

**Comment by labarba** [comment]
@whedon invite @karthik ad editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by labarba** [comment]
@whedon invite @karthik as editor

**Comment by whedon** [comment]
@karthik has been invited to edit this submission.

**Comment by karthik** [comment]
@@whedon assign @karthik as editor

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by karthik** [comment]
:wave: @adamgdobrakowski
I'll take a look at the submission early next week and start looking for reviewers. In the meantime if you have any suggestions for independent reviewers, please feel to suggest names (and Github handles).

**Comment by adamgdobrakowski** [comment]
@karthik Thank you. Based on the list of reviewers I think these reviewers have an appropriate area of interest: dormezil, cmaimone, bagheria

**Comment by karthik** [comment]
Thank you. I have reached out to `dormezil` and `cmaimone` and will follow up once I hear a response.

**Comment by karthik** [comment]
@whedon add @cmaimone as reviewer

**Comment by whedon** [comment]
OK, @cmaimone is now a reviewer

**Comment by cmaimone** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @cmaimone, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by cmaimone** [comment]
@karthik can you start a review issue for this?

**Comment by karthik** [comment]
Apologies @cmaimone. I'm just waiting on the second reviewer. As soon as that person is assigned I'll start.

**Comment by karthik** [comment]
👋 @DASpringate Any chance you can serve as second reviewer for this submission?

**Comment by karthik** [comment]
👋  @timchurches Would you be able to serve as second reviewer for this submission?

**Comment by timchurches** [comment]
Yes, happy to review it.

----
t

**Comment by karthik** [comment]
@whedon add  @timchurches as reviewer

**Comment by whedon** [comment]
OK,  @timchurches is now a reviewer

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2482.

**Comment by karthik** [comment]
@cmaimone  Sorry for the delay. You can start your review here now: https://github.com/openjournals/joss-reviews/issues/2482
