### ISSUE TITLE
[PRE REVIEW]: ALVA: An adaptive MATLAB package for layered viscoelastic elastic analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2274]
**Submitting author:** @asmusskar (<a href="http://orcid.org/0000-0003-3176-791X">Asmus Skar</a>)
**Repository:** <a href="https://github.com/asmusskar/ALVA" target ="_blank">https://github.com/asmusskar/ALVA</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @AnaWaldila, @CBenghi
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @asmusskar. **Currently, there isn't an JOSS editor assigned** to your paper.

@asmusskar if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (274.8 files/s, 38467.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                          24            470           1339           1766
TeX                              1             10              0            112
Markdown                         2             15              0             68
-------------------------------------------------------------------------------
SUM:                            27            495           1339           1946
-------------------------------------------------------------------------------


Statistical information for the repository '2274' was gathered on 2020/05/29.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1080/10298436.2018.1483502 is OK
- 10.1080/14680629.2010.9690274 is OK
- 10.1080/14680629.2012.757558 is OK
- 10.3141/2037-06 is OK
- 10.3850/978-981-11-0449-7-132-cd is OK
- 10.1080/14680629.2020.1741429 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02274/joss.02274/10.21105.joss.02274.pdf)

**Comment by danielskatz** [comment]
👋 @asmusskar - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS last week, we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by Kevin-Mattheus-Moerman** [comment]
@danielskatz I can take this one

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@ShiyongYu-cloud thanks for offering to help. Would you be able to update your GitHub profile with some professional information, e.g. a link to your professional profile, or an ORCID profile? This is not a requirement but if you do not mind it would be good to know who we recruit as reviewers. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@asmusskar I'm currently looking for reviewers for your submission. If you can recommend any please let me know.

**Comment by asmusskar** [comment]
Hi!

I can recommend Emin Kutay (https://www.egr.msu.edu/people/profile/kutay)
and Sigurdur Erlingsson (
https://www.vti.se/sv/medarbetare/profil/sigurdur_erlingsson/), which to my
knowledge are both top international domain knowledge and Matlab experts. I
can also recommend Morten Herfelt Andersen (mah@optumce.com) a software
developer at OPTUM computational engineering with Matlab skills that kills
;-)

Asmus

**Comment by Kevin-Mattheus-Moerman** [comment]
@asmusskar thanks for those. Do you know if they have GitHub handles already?

**Comment by Kevin-Mattheus-Moerman** [comment]
@fyangneil @hmhtb would you be interested in reviewing this submission for [JOSS (The Journal of Open Source Software)](https://joss.theoj.org): 
_ALVA: An adaptive MATLAB package for layered viscoelastic elastic analysis_

The review takes place on GitHub and focuses on this short paper: 
https://github.com/openjournals/joss-papers/blob/joss.02274/joss.02274/10.21105.joss.02274.pdf
and the software:
https://github.com/asmusskar/ALVA

You can tell me if you are interested by replying here. Once I have sufficient reviewers I'll open a dedicated review issue. 

If you are unavailable but can recommend alternative reviewers that would be great. Thank you!

**Comment by Kevin-Mattheus-Moerman** [comment]
@ShiyongYu-cloud :wave: thanks for offering to help. Would you be able to update your GitHub profile with some professional information, e.g. a link to your professional profile, or an ORCID profile? This is not a requirement but if you do not mind it would be good to know who we recruit as reviewers. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@fyangneil @hmhtb would you be interested in reviewing this submission for JOSS (The Journal of Open Source Software):
ALVA: An adaptive MATLAB package for layered viscoelastic elastic analysis

The review takes place on GitHub and focuses on this short paper:
https://github.com/openjournals/joss-papers/blob/joss.02274/joss.02274/10.21105.joss.02274.pdf
and the software:
https://github.com/asmusskar/ALVA

You can tell me if you are interested by replying here. Once I have sufficient reviewers I'll open a dedicated review issue.

If you are unavailable but can recommend alternative reviewers that would be great. Thank you!

**Comment by Kevin-Mattheus-Moerman** [comment]
> @asmusskar thanks for those. I've emailed them. Do you know if they have GitHub handles already?

@asmusskar :wave: do you have github handles for your suggested reviewers? I was not able to find them.

**Comment by Kevin-Mattheus-Moerman** [comment]
@CBenghi @mdelcambre @satish-annigeri @abhiramm7 @anawaldila would you be interested in reviewing this civil engineering related submission for JOSS (The Journal of Open Source Software):
ALVA: An adaptive MATLAB package for layered viscoelastic elastic analysis

The review takes place on GitHub and focuses on this short paper:
https://github.com/openjournals/joss-papers/blob/joss.02274/joss.02274/10.21105.joss.02274.pdf
and the software:
https://github.com/asmusskar/ALVA

You can tell me if you are interested by replying here. Once I have sufficient reviewers I'll open a dedicated review issue.

If you are unavailable but can recommend alternative reviewers that would be great. Thank you!

**Comment by AnaWaldila** [comment]
Yes, I would like to review this paper,
Kind regard,


----------------------------------------------------------------------------------------------------

Ana Waldila de Queiroz Ramiro Reis

Doutoranda em Engenharia Civil - Estrutura (UERJ)

Engenheira Civil

Tel: (21) 9 7945 - 6510

E-mail: anawaldila@hotmail.com

________________________________
De: Kevin Mattheus Moerman <notifications@github.com>
Enviado: sábado, 25 de julho de 2020 15:30
Para: openjournals/joss-reviews <joss-reviews@noreply.github.com>
Cc: Ana Waldila <anawaldila@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [openjournals/joss-reviews] [PRE REVIEW]: ALVA: An adaptive MATLAB package for layered viscoelastic elastic analysis (#2274)


@CBenghi<https://github.com/CBenghi> @mdelcambre<https://github.com/mdelcambre> @satish-annigeri<https://github.com/satish-annigeri> @abhiramm7<https://github.com/abhiramm7> @AnaWaldila<https://github.com/AnaWaldila> would you be interested in reviewing this civil engineering related submission for JOSS (The Journal of Open Source Software):
ALVA: An adaptive MATLAB package for layered viscoelastic elastic analysis

The review takes place on GitHub and focuses on this short paper:
https://github.com/openjournals/joss-papers/blob/joss.02274/joss.02274/10.21105.joss.02274.pdf
and the software:
https://github.com/asmusskar/ALVA

You can tell me if you are interested by replying here. Once I have sufficient reviewers I'll open a dedicated review issue.

If you are unavailable but can recommend alternative reviewers that would be great. Thank you!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @AnaWaldila as reviewer

**Comment by CBenghi** [comment]
Hello,
I don't have a MATLAB environment readily available.
But if you can't find another reviewer I'll be able to set one up once back
from leave in mid August.
Ping me again then, if needed.

Sorry for the inconvenience.

Claudio

Il Dom 26 Lug 2020, 01:36 Kevin Mattheus Moerman <notifications@github.com>
ha scritto:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @AnaWaldila as reviewer

**Comment by whedon** [comment]
OK, @AnaWaldila is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@CBenghi thanks that would be great. I'll add you for now so we can get started and I'll remind you mid-August. If you have difficulties installing/setting up MATLAB let me know. 

@asmusskar can you comment on how compatible this work is with Octave? Does it run in Octave or not really? Are special MATLAB toolboxes required?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @CBenghi as reviewer

**Comment by whedon** [comment]
OK, @CBenghi is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@ShiyongYu-cloud thanks again for offering to help review this work. I'd be happy to add you as reviewer but it would be good it you could share a professional profile (e.g. university link, ORCID, LinkedIn), or add one to your GitHub profile, so your expertise and background are visible to us.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mdelcambre @satish-annigeri @abhiramm7 would you be interested in reviewing this civil engineering related submission for JOSS (The Journal of Open Source Software):
ALVA: An adaptive MATLAB package for layered viscoelastic elastic analysis

The review takes place on GitHub and focuses on this short paper:
https://github.com/openjournals/joss-papers/blob/joss.02274/joss.02274/10.21105.joss.02274.pdf
and the software:
https://github.com/asmusskar/ALVA

You can tell me if you are interested by replying here. Once I have sufficient reviewers I'll open a dedicated review issue.

If you are unavailable but can recommend alternative reviewers that would be great. Thank you!

**Comment by asmusskar** [comment]
Hi. 

The package should be fully compatible with Octave. At least this is what I have heard from other users.

Asmus

Sendt fra min iPhone

**Comment by Kevin-Mattheus-Moerman** [comment]
I'll start the review process now to avoid further delay.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2548.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mdelcambre @satish-annigeri @abhiramm7  please consider my reviewer invitation :point_up:. If you are able to help that would be great and I can add you as a reviewer over at #2548
