### ISSUE TITLE
[PRE REVIEW]: multDM: An R package for multivariate version of the Diebold-Mariano test

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2279]
**Submitting author:** @kdrachal (<a href="http://orcid.org/0000-0001-5297-6695">Krzysztof Drachal</a>)
**Repository:** <a href="https://github.com/kdrachal/multDM" target ="_blank">https://github.com/kdrachal/multDM</a>
**Version:** 1.1.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kdrachal. **Currently, there isn't an JOSS editor assigned** to your paper.

@kdrachal if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.21 s (28.5 files/s, 2949.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                4             57             94            300
TeX                              1             12              0             88
Markdown                         1              9              0             61
-------------------------------------------------------------------------------
SUM:                             6             78             94            449
-------------------------------------------------------------------------------


Statistical information for the repository '2279' was gathered on 2020/05/31.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by danielskatz** [comment]
Note: @mbobra was suggested as the editor

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/j.ijforecast.2015.03.008 may be missing for title: A note on the Mean Absolute Scaled Error
- https://doi.org/10.3386/t0169 may be missing for title: Comparing predictive accuracy
- https://doi.org/10.1016/j.jeconom.2012.01.014 may be missing for title: Statistical tests for multiple forecast comparison
- https://doi.org/10.2139/ssrn.2692118 may be missing for title: The model confidence set package for R
- https://doi.org/10.2307/2287575 may be missing for title: Modeling multiple times series with applications
- https://doi.org/10.1016/j.ijforecast.2006.03.001 may be missing for title: Another look at measures of forecast accuracy

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02279/joss.02279/10.21105.joss.02279.pdf)

**Comment by danielskatz** [comment]
👋 @kdrachal - thanks for your submission - we'll get back to you with the next step shortly

**Comment by danielskatz** [comment]
Hi @kdrachal. Many thanks for your submission to JOSS. Unfortunately, after consulting with the JOSS editorial board, we have decided that this submission is out of scope for JOSS due to its limited scope.  We encourage you to potentially add more methods and build a larger package, or to consider if this method can be added to an existing package.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
