### ISSUE TITLE
[PRE REVIEW]: Brightway: An open source framework for life cycle assessment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#228]
**Submitting author:** @cmutel (<a href="http://orcid.org/0000-0002-7898-9862">Chris Mutel</a>)
**Repository:** <a href="https://bitbucket.org/cmutel/brightway2" target ="_blank">https://bitbucket.org/cmutel/brightway2</a>
**Version:** 2.0.2
**Editor:** @katyhuff
**Reviewer:** @amoeba

**Author instructions**

Thanks for submitting your paper to JOSS @cmutel. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@cmutel if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by cmutel** [comment]
@sgrieve @jsta @katyhuff @amoeba Based on your provided descriptions, you seem to be reasonable candidates as editors. Would any of you have time for this submission?

**Comment by sgrieve** [comment]
@cmutel I'm afraid I don't know enough about Life Cycle Assessment to be a suitable editor for this paper.

**Comment by katyhuff** [comment]
I am willing and able to be the editor for this.
@jsta @amoeba,would either of you be willing and able to be a reviewer? (or
vice versa, I could review if you would prefer to edit)

On Tue, Apr 11, 2017, 6:17 AM Stuart Grieve <notifications@github.com>
wrote:

@cmutel <https://github.com/cmutel> I'm afraid I don't know enough about
Life Cycle Assessment to be a suitable editor for this paper.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjournals/joss-reviews/issues/228#issuecomment-293214562>,
or mute the thread

**Comment by cmutel** [comment]
@katyhuff The easiest way to get started is to follow the [introduction notebook](http://nbviewer.jupyter.org/urls/bitbucket.org/cmutel/brightway2/raw/default/notebooks/Getting%20Started%20with%20Brightway2.ipynb), as this downloads a real database.

Also note that, while the badges for test coverage give "unknown", they are linked to the CI, and you can see test coverage reports if you click on them.

**Comment by amoeba** [comment]
I am also unfamiliar with LCA but after a quick look it I think I might be able to make sense of it. I can at least get started on the review and address many of the reviewer checklist items. I'll do this over that over the weekend. Sound good?

**Comment by katyhuff** [comment]
Thanks @amoeba .

**Comment by katyhuff** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by katyhuff** [comment]
@whedon assign @amoeba as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @amoeba

**Comment by katyhuff** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/236. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Ok, @amoeba , head over to #236 for the review! Thanks!!
