### ISSUE TITLE
[PRE REVIEW]: The Basic Model Interface 2.0: A standard interface for coupling numerical models in the geosciences

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2280]
**Submitting author:** @mdpiper (<a href="http://orcid.org/0000-0001-6418-277X">MARK PIPER</a>)
**Repository:** <a href="https://github.com/csdms/bmi" target ="_blank">https://github.com/csdms/bmi</a>
**Version:** v2.0
**Editor:** @diehlpk
**Reviewers:** @yangbai90, @teuben
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mdpiper. **Currently, there isn't an JOSS editor assigned** to your paper.

@mdpiper if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.21 s (139.5 files/s, 15882.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
reStructuredText                23            723            562           1152
DOS Batch                        1             34              2            227
make                             1             30              6            156
Python                           2             86            187            122
HTML                             2              1              0             14
-------------------------------------------------------------------------------
SUM:                            29            874            757           1671
-------------------------------------------------------------------------------


Statistical information for the repository '2280' was gathered on 2020/05/31.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
(no author)                      1          1054              0            6.21
Mark Piper                       4           115            739            5.04
Mike Taves                       1            23             12            0.21
huttone                         21          1296            682           11.66
mcflugen                        53          6189           6849           76.88

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Mark Piper                  113           98.3          1.7                6.19
mcflugen                    282            4.6         36.9               62.77
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2280 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch mdpiper/paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch mdpiper/paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02280/joss.02280/10.21105.joss.02280.pdf)

**Comment by danielskatz** [comment]
👋 @mdpiper - thanks for your submission  - we'll get back to you with a next step shortly

**Comment by danielskatz** [comment]
Note to editors: this was discussed in https://github.com/openjournals/joss/issues/690 before submission

**Comment by danielskatz** [comment]
👋 @mdpiper - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS about a little more than a week ago, we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months. We also are beginning to bring in new editors to move this process along.

Thanks in advance for your patience!

**Comment by kyleniemeyer** [comment]
Hey @jedbrown, just wanted to see if you were interested / had the bandwidth to edit this, since you participated in the pre-submission discussion.

**Comment by kyleniemeyer** [comment]
@whedon invite @jedbrown as editor

**Comment by whedon** [comment]
@jedbrown has been invited to edit this submission.

**Comment by jedbrown** [comment]
@kyleniemeyer Interested, but as mentioned in email, conflicted according to our policy (same institution).

**Comment by kyleniemeyer** [comment]
@jedbrown oh, sorry. I missed that. So, I think we have faced this sort of conflict before, and I'm not as concerned about this for an editor, as long as the reviewers do not have similar conflicts. @joss-eics do you agree?

**Comment by danielskatz** [comment]
Unless there are no other editors who can take this, I would prefer to avoid the conflict

**Comment by diehlpk** [comment]
I can take this, since I have experience in coupling methods for computational fracture mechanics.

**Comment by kyleniemeyer** [comment]
Thanks @diehlpk!

**Comment by kyleniemeyer** [comment]
@whedon assign @diehlpk as editor

**Comment by whedon** [comment]
OK, the editor is @diehlpk

**Comment by diehlpk** [comment]
@whedon generate pdf from branch mdpiper/paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch mdpiper/paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02280/joss.02280/10.21105.joss.02280.pdf)

**Comment by diehlpk** [comment]
Hi @mdpiper, I am the editor for this submission. I briefly read the paper and have following remarks:

1. There are no references in the Reference section
2. All Bib Tex entries are not resolved

Please have look into these issues.

**Comment by mdpiper** [comment]
@diehlpk Sorry about that--it's now fixed.

**Comment by diehlpk** [comment]
@whedon generate pdf from branch mdpiper/paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch mdpiper/paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02280/joss.02280/10.21105.joss.02280.pdf)

**Comment by diehlpk** [comment]
@mdpiper thanks for the corrections. Could you recommend some potential reviewers?

**Comment by mdpiper** [comment]
@diehlpk I'd like to suggest @Teuben and @yangbai90 as reviewers; both are familiar with C, C++, Fortran, and Python.

**Comment by teuben** [comment]
funny you say.   If I do accept (i might, although this is not my field, and this would be my first online review), I ran into this article today, which it now on my reading shelf:

https://abompard.wordpress.com/2020/06/07/reviews-are-hard/

**Comment by teuben** [comment]
@mdpiper when i read the abstract, the amuse project in astropysics came to mind. have you heard of this before?   https://ascl.net/1107.007 has a reference. Comining legacy (and new) codes via a python hub.

**Comment by diehlpk** [comment]
Hi Peter (@teuben), would you be interested to serve as a reviewer?

**Comment by mdpiper** [comment]
@teuben I hadn't seen AMUSE before, but from the examples, it looks similar to what we in the earth surface processes community are doing with [pymt](https://pymt.readthedocs.io/en/latest/). Neat! Thanks for the reference!

**Comment by teuben** [comment]
and there is another group (in amsterdam?) that has cloned amuse for their field (hydrology?). i remember looking at their link, but they are not as active as amuse it (which still is very active).

**Comment by diehlpk** [comment]
Hi @yangbai90, would you be interested to review this paper?

**Comment by yangbai90** [comment]
Hi @diehlpk , I would like to be the reviewer for this paper.

**Comment by teuben** [comment]
@diehlp do you need one or two reviewers

**Comment by diehlpk** [comment]
@teuben I need at least two. So I would appreciate if you can become the second reviewer.

**Comment by diehlpk** [comment]
@yangbai90 Thanks, I will add you soon.

**Comment by diehlpk** [comment]
@whedon assign @yangbai90 as reviewer

**Comment by whedon** [comment]
OK, @yangbai90 is now a reviewer

**Comment by teuben** [comment]
@diehlpk  sure go ahead, this will be a nice challenge, new field, new method, what could go wrong

**Comment by diehlpk** [comment]
@whedon add @teuben as reviewer

**Comment by whedon** [comment]
OK, @teuben is now a reviewer

**Comment by diehlpk** [comment]
@teuben Thanks for volunteering.

**Comment by diehlpk** [comment]
@mdpiper If you have provided us with the latest version. I will start the review soon.

**Comment by mdpiper** [comment]
@diehlpk Yes, this is the latest version--thanks!

**Comment by diehlpk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2317.
