### ISSUE TITLE
[PRE REVIEW]: dms-view: Interactive visualization tool for deep mutational scanning data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2288]
**Submitting author:** @skhilton (<a href="http://orcid.org/0000-0001-9278-3644">Sarah K. Hilton</a>)
**Repository:** <a href="https://github.com/dms-view/dms-view.github.io" target ="_blank">https://github.com/dms-view/dms-view.github.io</a>
**Version:** v1.0.0
**Editor:** @csoneson
**Reviewers:** @afrubin, @andrefaure, @thorvere
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @skhilton. **Currently, there isn't an JOSS editor assigned** to your paper.

@skhilton if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.02 s (189.0 files/s, 36149.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              2             21             16            597
Markdown                         2             27              0            104
-------------------------------------------------------------------------------
SUM:                             4             48             16            701
-------------------------------------------------------------------------------


Statistical information for the repository '2288' was gathered on 2020/06/03.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/j.celrep.2015.06.005 may be missing for title: Identification of hemagglutinin residues responsible for H3N2 antigenic drift during the 2014–2015 influenza season
- https://doi.org/10.1038/nmeth.3027 may be missing for title: Deep mutational scanning: a new style of protein science.
- https://doi.org/10.1186/s13073-019-0698-7 may be missing for title: Recommendations for the collection and use of multiplexed functional data for clinical variant interpretation
- https://doi.org/10.1186/s12859-015-0590-4 may be missing for title: Software for the analysis and visualization of deep mutational scanning data

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02288/joss.02288/10.21105.joss.02288.pdf)

**Comment by kyleniemeyer** [comment]
👋 Hi @skhilton! Thanks for your submission to JOSS. As described in [our blog post announcing the reopening of JOSS](https://blog.joss.theoj.org/2020/05/reopening-joss), we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS about a little more than a week ago, we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months. We also are beginning to bring in new editors to move this process along.

Thanks in advance for your patience!

**Comment by skhilton** [comment]
Hi @kyleniemeyer. Thanks so much for the update on the timeline. 

As far as potential reviewers, we would like to to suggest Alan Rubin who has extensive experience with the datasets our tool visualizes.

**Comment by labarba** [comment]
👋  @skhilton -- you've provided a link to a repository that contains _just the paper_. We expect a repository containing _the code_, with the paper contained within. Can you re-arrange things?

**Comment by skhilton** [comment]
👋 @labarba: I've re-arranged our repos. Now the code and the paper are both in the repo https://github.com/dms-view/dms-view.github.io. Is there another place I should update the repo url or will this comment suffice? Thanks!

**Comment by labarba** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.52 s (226.6 files/s, 74405.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      85           4210           6786          24244
HTML                             6            189              0           1453
Markdown                        16            261              0            817
CSS                              2             56              4            280
JSON                             5              0              0            253
TeX                              1              9              0             97
Python                           1             15             15             46
YAML                             2              0              0             13
-------------------------------------------------------------------------------
SUM:                           118           4740           6805          27203
-------------------------------------------------------------------------------


Statistical information for the repository '2288' was gathered on 2020/06/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alli Black                       1           132              0            0.01
Jesse Bloom                      1             6              1            0.00
John Huddleston                101        533181         534316           47.35
Khrystyna Dilai                 17          3982         529057           23.64
Sarah Hilton                    78         70265           8080            3.47
kdilai                           9        529111            243           23.48
skhilton                       117         40160           6110            2.05

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
John Huddleston              32            0.0          1.2               25.00
skhilton                  68238          169.9          2.7               21.41
```

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02288/joss.02288/10.21105.joss.02288.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@lpantano @will-rowe @csoneson could one of you handle this submission?

**Comment by csoneson** [comment]
@Kevin-Mattheus-Moerman - I can handle this one.

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/j.celrep.2015.06.005 may be missing for title: Identification of hemagglutinin residues responsible for H3N2 antigenic drift during the 2014–2015 influenza season
- https://doi.org/10.1038/nmeth.3027 may be missing for title: Deep mutational scanning: a new style of protein science.
- https://doi.org/10.1186/s13073-019-0698-7 may be missing for title: Recommendations for the collection and use of multiplexed functional data for clinical variant interpretation
- https://doi.org/10.1186/s12859-015-0590-4 may be missing for title: Software for the analysis and visualization of deep mutational scanning data

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
👋 @skhilton - I will handle your submission, and start by engaging some reviewers! In the meantime, could you please add DOIs to your references?

**Comment by csoneson** [comment]
👋  @afrubin, @andrefaure - would you be interested in reviewing this submission for the Journal of Open Source Software (JOSS)? 

> dms-view: Interactive visualization tool for deep mutational scanning data

Software repository: https://github.com/dms-view/dms-view.github.io
Accompanying paper: https://github.com/openjournals/joss-papers/blob/joss.02288/joss.02288/10.21105.joss.02288.pdf

JOSS reviewer guidelines and more information about the process: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by afrubin** [comment]
@csoneson I am happy to review this manuscript.

**Comment by andrefaure** [comment]
@csoneson I am also happy to review the manuscript.

**Comment by csoneson** [comment]
@afrubin, @andrefaure - brilliant, thanks so much! I'll formally add you as reviewers and open the review issue.

**Comment by csoneson** [comment]
@whedon add @afrubin as reviewer

**Comment by whedon** [comment]
OK, @afrubin is now a reviewer

**Comment by csoneson** [comment]
@whedon add @andrefaure as reviewer

**Comment by whedon** [comment]
OK, @andrefaure is now a reviewer

**Comment by csoneson** [comment]
@whedon add @ thorvere as reviewer

**Comment by whedon** [comment]
OK, @ thorvere is now a reviewer

**Comment by csoneson** [comment]
@whedon remove @ thorvere as reviewer

**Comment by whedon** [comment]
OK, @ thorvere is no longer a reviewer

**Comment by csoneson** [comment]
@whedon add @thorvere as reviewer

**Comment by whedon** [comment]
OK, @thorvere is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2353.
