### ISSUE TITLE
[REVIEW]: dcgp: Differentiable Cartesian Genetic Programming made easy.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2290]
**Submitting author:** @darioizzo (<a href="http://orcid.org/0000-0002-9846-8423">Dario Izzo</a>)
**Repository:** <a href="https://github.com/darioizzo/dcgp" target ="_blank">https://github.com/darioizzo/dcgp</a>
**Version:** 1.5
**Editor:** @VivianePons
**Reviewer:** @Ohjeah, @shah314
**Archive:** <a href="https://doi.org/10.5281/zenodo.3802555" target="_blank">10.5281/zenodo.3802555</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/a7c9c9b52cb43c915c263adfbd3a7458/status.svg)](https://joss.theoj.org/papers/a7c9c9b52cb43c915c263adfbd3a7458)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a7c9c9b52cb43c915c263adfbd3a7458"><img src="https://joss.theoj.org/papers/a7c9c9b52cb43c915c263adfbd3a7458/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a7c9c9b52cb43c915c263adfbd3a7458/status.svg)](https://joss.theoj.org/papers/a7c9c9b52cb43c915c263adfbd3a7458)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/darioizzo/dcgp" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Ohjeah & @shah314, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @VivianePons know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/darioizzo/dcgp">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@darioizzo) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/darioizzo/dcgp">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@darioizzo) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Ohjeah, @shah314 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2290 with the following error: 

 Can't find any papers to compile :-(

**Comment by VivianePons** [comment]
@whedon generate pdf from branch joss-paper-v1.5.1

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-v1.5.1. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02290/joss.02290/10.21105.joss.02290.pdf)

**Comment by VivianePons** [comment]
For info, the paper is in a branch here: https://github.com/darioizzo/dcgp/tree/joss-paper-v1.5.1

**Comment by shah314** [comment]
For the authors:

Can you add the missing DOIs to the paper?

Can you add a brief description of audi to the paper (just to make the paper complete and readable), since audi looks like a codebase on Zenodo.

Do you do any form of crossover between A and B? Like replacing a random subtree of A with a random subtree of B? I could not find anything in the paper.

Any results, or comparison with benchmarks or do you think it is not necessary? For instance, you could compare the results with linear or quadratic regression?

**Comment by Ohjeah** [comment]
#### Software paper

- The introduction is a little bit steep for non-experts. As an outsider I would not be able to understand it (e.g. 1. sentence: What is a fitness?). Could you please add a paragraph for non-experts?
- I am missing the statement of need as well as the state of the field. I think you can repurpose parts of the "Comparison to the CGP-Library" paragraph from the README.

**Comment by darioizzo** [comment]
@shah314 

DOIs are added.

We extended a bit on audi, adding a sentence: "The library `audi` makes computations in this algebra rather straight-forward by defining all the basic arithmetics rules for the new type `audi::gdual<T>` which, essentially, represents a multivariate Taylor polynomial and thus contains all the derivatives of the considered expansion."

We commented explicitly upon the absence of crossover in the current version.

We think a comparison between symbolic regression and quadratic/linear regression would be out of scope, maybe a comparison to other existing codes for symbolic regression would be possbile, but its a bit of a pandora box as most are commercial and the non commercial ones are anyway hardly comparable.

**Comment by darioizzo** [comment]
@Ohjeah 

* We explained at length the concpet of fitness
* We added a last paragraph in the intro to address your point.

**Comment by Ohjeah** [comment]
- Could you add the statement of need to the online documentation as well?
- Please expand the installtion guide:
  - What versions of the thirdparty dependencies are required?
  - Did you look into an automated package management solution for the c++ version?
  - Why is the PyPI version deprecated? If it's not coming back, please remove the outdated batch from the README.
  - Please add documentation how to execute the tests (I think it's done while installing, you should make the test command explicit).

**Comment by darioizzo** [comment]
@Ohjeah 

 * We added the statement in the background section of the web pages
 * Installation guide expanded:
     * all version required of third parties are added
     * guide on readme is now the same as that in the online docs
     * the exact version of the code available in PyPi (it may come back in the future, but we need to find the resources to maintain also those pip packages)
     * no C++ package manager
* Documentation on how tests can be run is added in the installation pages. (for the conda packages those tests are run alreay by conda when creating the packages, but local installation may indeed need to be tested too)

**Comment by shah314** [comment]
@whedon generate pdf from branch joss-paper-v1.5.1

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-v1.5.1. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02290/joss.02290/10.21105.joss.02290.pdf)

**Comment by shah314** [comment]
I have been struggling with installing the packages. I was able to install all dependencies (including audi), but the dcgp code is unable to find audi. To install audi from source, I installed all dependencies (including obake), but it is unable to find obake.

Is it possible to write a shell script with the steps needed to install everything? You may be aware of conda command line options that might also speed up the installation. Thank you.

**Comment by darioizzo** [comment]
I cannot reproduce your issue. @shah314 can you post the exact conda command you are issuing? From the environment creation. The following for example:

```
conda create -n dcgpy python=3.7 dcgp-python
```

also maybe we can move this in the dcgp GitHub issues?

**Comment by shah314** [comment]
I was missing the environment creation. I am now able to install the package and run the python tests. Continued on the git issues page. Thanks.

**Comment by darioizzo** [comment]
@Ohjeah @shah314 I realize community guidelines are not very visible at the moment, should I add a specific section in the readme file in the github repository?

**Comment by Ohjeah** [comment]
Yes you should mention (or link) them in the readme file. Maybe you can have a look into [issue templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) as well.

**Comment by shah314** [comment]
@whedon generate pdf from branch joss-paper-v1.5.1

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-v1.5.1. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02290/joss.02290/10.21105.joss.02290.pdf)

**Comment by shah314** [comment]
@darioizzo There should be a CONTRIBUTING.md and a CODE_OF_CONDUCT.md files present in the repository.

The CODE_OF_CONDUCT can be adapted from [this page](https://www.contributor-covenant.org/version/1/4/code-of-conduct/). 

CONTRIBUTING.md could be anything that you want contributors to know before they contribute to the code or submit issues. [Here](https://github.com/shah314/gamultiknapsack/blob/master/CONTRIBUTING.md) is an example.

**Comment by Ohjeah** [comment]
I have two remaining points which I would like to see addressed:

- [ ] I'd like to see a more in depth installation guide for the c++ part on how to install the thirdparty requirements. I had to dig into the issues (https://github.com/darioizzo/dcgp/issues/73) and install an undocumented requirement. Maybe the authors could also provide a convenience script to setup a working environment (on macos it's basically a brew + conda install).
- [ ] Similarly the python dependencies should be listed in a standard format (e.g. requirements.txt, environtment.yml, Pipfile or similar). Optional dependencies, as well as dependencies for examples and documentation need to be listed as well. As a user, I'd want to make sure that thirdparty dependencies of dgcpy are compatible before using it in a project.

**Comment by shah314** [comment]
@VivianePons @darioizzo @Ohjeah 

The code implements differentiable cartesian genetic programming in which the code can learn using symbolic regression. The implementation provides several kernels with the ability to write custom kernels. I tried to fit a few functions from data and it was able to find good approximations.

Another application is the code's ability to learn neural networks and the library provides several activation functions like sigmoid, tanh and ReLu. The python examples provide python notebooks which can be experimented with. In addition to SGD, the library can evolve a neural network's topology using mutation. Comparing this work with [2] might yield some fundamental results.

The work is based on the authors' 2017 paper [1] which has interesting results. The examples in the repository compare the work with a commonly used ANN framework keras and find good results.

Because of several dependencies and interfaces in C++ and python, the initial installation was a minor struggle, but the authors responded to questions fast and resolved the issues.

The only two minor issues I found (in symbolic regression runs) were that, one, the differences between multiple runs were significant. And two, for X and Y of length 10,000, the run was a little slow. Both of these are expected as this is a randomized search procedure with a fixed number of generations.

After reviewing the installation, dependencies and trying out examples, I strongly recommend the work for acceptance to JOSS.

[1] Izzo, Dario, Francesco Biscani, and Alessio Mereta. "Differentiable genetic programming." European Conference on Genetic Programming. Springer, Cham, 2017.
[2] Gaier, Adam, and David Ha. "Weight agnostic neural networks." Advances in Neural Information Processing Systems. 2019.

**Comment by darioizzo** [comment]
@Ohjeah Sorry for the inactivity. I have implemented your requested changes in the documentation: http://darioizzo.github.io/dcgp/installation.html

I added the exact commands, assuming a conda user toset up correctly all dependencies.

**Comment by Ohjeah** [comment]
@darioizzo Thanks! Have you looked into [environment files](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually).

I am only missing the Community guidelines. A good example would be using Github issue templates and a paragraph in the Readme similar to this project: https://github.com/BartoszBartmanski/StoSpa2

**Comment by darioizzo** [comment]
@Ohjeah Thanks for your suggestions, I have added issue templates in github and community guidelines in the readme.

**Comment by Ohjeah** [comment]
@darioizzo Thanks.

@VivianePons I can now recommend the submission for acceptance as well.

**Comment by VivianePons** [comment]
Thank you @shah314 and @Ohjeah for your time and useful comments. I will proceed to next step towards acceptance :)

@whedon generate pdf

**Comment by VivianePons** [comment]
@whedon generate pdf from branch joss-paper-v1.5.1

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-v1.5.1. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02290/joss.02290/10.21105.joss.02290.pdf)

**Comment by VivianePons** [comment]
@whedon check references from branch joss-paper-v1.5.1

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper-v1.5.1
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-3-319-55696-3_3 is OK
- 10.1007/s10710-010-9112-3 is OK
- 10.1007/978-3-642-17310-3_2 is OK
- 10.5281/zenodo.3702783 is OK
- 10.1145/3319619.3322003 is OK
- 10.1007/s10710-014-9233-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by VivianePons** [comment]
Thanks again to @shah314 and @Ohjeah for all the usefull feedback providing the review and to @darioizzo for the work.

@darioizzo could you make an archive (on Zenodo, figshare, or other) of the repo and put it here? Please make sure that the metadata (authors and title) correspond to the paper.

**Comment by darioizzo** [comment]
@VivianePons we have this zenodo record already: https://zenodo.org/record/3802555#.Xw8ETygzaUk, it is linked to all new releases ...

**Comment by VivianePons** [comment]
Hi Dario, I need the title on the zenodo to be the same as the paper. Thanks

**Comment by darioizzo** [comment]
@VivianePons  done.

**Comment by VivianePons** [comment]
Perfect!

**Comment by VivianePons** [comment]
@whedon set 10.5281/zenodo.3802555 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3802555" target="_blank">10.5281/zenodo.3802555</a> is the archive.

**Comment by VivianePons** [comment]
@whedon set 1.5 as version

**Comment by whedon** [comment]
OK. 1.5 is the version.

**Comment by VivianePons** [comment]
Congratulations! I can now accept the paper. This is a very nice work and I am happy to see it published at JOSS. Thank you very much @darioizzo for submitting it and thanks to @shah314 and @Ohjeah for the reviews and feedbacks

**Comment by VivianePons** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2290 with the following error: 

 Can't find any papers to compile :-(

**Comment by VivianePons** [comment]
@whedon accept from branch joss-paper-v1.5.1

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-3-319-55696-3_3 is OK
- 10.1007/s10710-010-9112-3 is OK
- 10.1007/978-3-642-17310-3_2 is OK
- 10.5281/zenodo.3702783 is OK
- 10.1145/3319619.3322003 is OK
- 10.1007/s10710-014-9233-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1575

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1575, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss-paper-v1.5.1 
```

**Comment by labarba** [comment]
@darioizzo -- version tag 1.5 in the repo is from May 6. Please confirm: there have been no changes since due to this review? (if yes, you could up the patch number in a new tag)

**Comment by darioizzo** [comment]
@labarba 1.5 is the last released code and is what the paper refers to. There have been minor changes in the repo since we are developing 1.5.1, but it is not ready for a release yet, that is planned in 6-12 months.

**Comment by labarba** [comment]
wait... but we're publishing from a branch that has `v1.5.1` in the _name_...

**Comment by darioizzo** [comment]
@labarba The branch was created as per request during the review process (orignally I had put the paper into an entirely different repo), I gave it the name 1.5.1 back then as I took it from the development code (in retrospective I should have used 1.5). 

There is not any difference (only code overhauls) in features between 1.5 and 1.5.1. But it is true that 1.5.1 is under development and unreleased.

**Comment by darioizzo** [comment]
I can clone into a new branch with the 1.5 name ,if you want, and delete the old branch?

**Comment by labarba** [comment]
No, that's fine. I just wanted to confirm that we have the correct metadata.

**Comment by labarba** [comment]
@whedon accept deposit=true from branch joss-paper-v1.5.1

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1283677158506987521) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1579
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02290](https://doi.org/10.21105/joss.02290)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by labarba** [comment]
Congratulation, @darioizzo, your JOSS paper is published! 🚀 

Huge thanks to our editor: @VivianePons, and the reviewer: @Ohjeah, @shah314 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02290/status.svg)](https://doi.org/10.21105/joss.02290)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02290">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02290/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02290/status.svg
   :target: https://doi.org/10.21105/joss.02290
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02290/status.svg)](https://doi.org/10.21105/joss.02290)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by labarba** [comment]
Congratulation, @darioizzo, your JOSS paper is published! 🚀 

Huge thanks to our editor: @VivianePons, and the reviewer: @Ohjeah, @shah314 🙏

**Comment by darioizzo** [comment]
Thanks to everybody @Ohjeah @shah314 @VivianePons and @labarba, it has been a great process and I only have positive feedback on how things were handled!
