### ISSUE TITLE
[REVIEW]: PySWMM: The Python Interface to Stormwater Management Model (SWMM)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2292]
**Submitting author:** @katmratliff (<a href="http://orcid.org/0000-0003-1410-2756">Katherine Ratliff</a>)
**Repository:** <a href="https://github.com/OpenWaterAnalytics/pyswmm" target ="_blank">https://github.com/OpenWaterAnalytics/pyswmm</a>
**Version:** v0.6.2
**Editor:** @kbarnhart
**Reviewers:** @nickrsan, @jrkasprzyk
**Archive:** <a href="https://doi.org/10.5281/zenodo.3972214" target="_blank">10.5281/zenodo.3972214</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/671bd4b25df92ed466c8e9b8d76ae9df/status.svg)](https://joss.theoj.org/papers/671bd4b25df92ed466c8e9b8d76ae9df)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/671bd4b25df92ed466c8e9b8d76ae9df"><img src="https://joss.theoj.org/papers/671bd4b25df92ed466c8e9b8d76ae9df/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/671bd4b25df92ed466c8e9b8d76ae9df/status.svg)](https://joss.theoj.org/papers/671bd4b25df92ed466c8e9b8d76ae9df)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/OpenWaterAnalytics/pyswmm" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@nickrsan & @jrkasprzyk & @dickinsonre, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kbarnhart know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/OpenWaterAnalytics/pyswmm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@katmratliff) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/OpenWaterAnalytics/pyswmm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@katmratliff) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @nickrsan, @jrkasprzyk, @dickinsonre it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3390/w8060259 is OK
- 10.1016/j.proeng.2014.11.503 is OK
- 10.1016/j.envsoft.2016.05.009 is OK

MISSING DOIs

- https://doi.org/10.1061/9780784482360.006 may be missing for title: Exploring the Potential for Simulating System-Level Controlled Smart Stormwater System
- https://doi.org/10.1061/jswbay.0000817 may be missing for title: Storm Water Management Model: Performance Review and Gap Analysis
- https://doi.org/10.1080/1573062x.2019.1611889 may be missing for title: swmmr - an R package to interface SWMM

INVALID DOIs

- https://doi.org/10.1016/j.envsoft.2018.12.004 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02292/joss.02292/10.21105.joss.02292.pdf)

**Comment by kbarnhart** [comment]
@katmratliff @nickrsan, @jrkasprzyk, @dickinsonre

I wanted to check in and see how things were going with this review, and to answer any questions if you have them. As mentioned above, JOSS is presently requesting reviewers complete their reviews in six weeks (a bit more than three weeks from now).

**Comment by nickrsan** [comment]
Thanks for checking in with us - the review is going well so far - I'll try to have mine finished soon so it doesn't linger! Installed just fine, but I need to do the rest of the testing with it.

**Comment by nickrsan** [comment]
So, quick note on my status - just ran the test suite and it passed fine on my computer (Python 3.7.7, Win 10). I still have a bit more to do to verify the functional claims, but seems good so far.

One question I have for @kbarnhart - I'm wondering if, in addition to the objective/checklist process for acceptance, if JOSS reviews include general feedback from reviewers. Should we be considering comments of things we think are well done and any suggestions or clarifying questions we have (such as about spots in the documentation), or if they don't affect acceptance, then we should generally not include it here, and any comments should instead be on the target repo? To be clear, I haven't encountered anything significant, but just wanted to confirm - I don't want the authors to miss out on a constructive conversation if I should be attempting to provide that as a reviewer, and alternatively, don't want to be chiming in with anything that's not appropriate here if I should just be following the checklist. It seems like the latter, but I wanted to make sure. Thanks!

**Comment by katmratliff** [comment]
@nickrsan if you have any suggestions/feedback about PySWMM or our documentation beyond the scope of this JOSS review, please feel free to open up issues/PRs in the repo! We are always happy to receive that sort of thing, however big or small, and are always looking to improve! :) thank you for taking the time to review!

**Comment by kbarnhart** [comment]
@nickrsan Thanks for a great question. The kind of feedback you are describing is incredibly valuable and I would encourage you to make those comments. 

I would recommend that you make issues in the main source repository about these sort of comments and link them to this issue. If you could make a quick note here for me that indicates which issues don't impact acceptance, that would also be very helpful. 

Thanks for contributing to the JOSS review process! 👍

**Comment by nickrsan** [comment]
Review complete - looks great to me and seems like a very valuable tool and contribution - I think the paper clearly states what capabilities the software provides that weren't previously available, and the software performs as expected on my computer.  Overall, it seems like it's in great shape.

@katmratliff I especially liked that the documentation had a tutorial section with multiple sets of code - as a reviewer, it helped me when I got to the phase of verifying the software does what the paper says, but it was also just nice for me, as someone who isn't a stormwater modeler, to see how the package would be used in practice. I'm not sure if it'd be in scope for the package's audience, but it would have been handy if the input files were available for each section (similar to how the `Examples` section approached the input file download) - I pulled ones that seemed appropriate from the project's tests folder though. Even without the files though, it worked well as a demonstration of capabilities. If it seems like something you'd want to include, I can make an issue or a pull request, but since I wasn't sure it'd apply, I thought I'd start by mentioning it here.

Another thing I appreciated is that the code not only had tests, but also references in the README to the current build statuses so I could see it in CI/CD. It really seems like the team is striving for high code quality between that and the submission guidelines.

**Comment by katmratliff** [comment]
@nickrsan I like your idea about including downloadable input files in the tutorial section. Feel free to open up an issue - you can also label it `type:docs` and assign me.

**Comment by kbarnhart** [comment]
Thanks @nickrsan for completing your review, making issues in the repository, and providing a summary here. 

@jrkasprzyk, @dickinsonre a friendly reminder to complete your review and/or provide a quick update here on when you anticipate being able to complete it. 

Thanks to all for contributing to the JOSS review process.

**Comment by jrkasprzyk** [comment]
Hi @kbarnhart I am coming into the process a little late! I cannot fill out the checklist, although I am logged into my account. Perhaps I need another invitation?

**Comment by jrkasprzyk** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by jrkasprzyk** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by kbarnhart** [comment]
@whedon re-invite @jrkasprzyk as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@jrkasprzyk please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by kbarnhart** [comment]
@jrkasprzyk if you click the link above and accept the invitation (which expires after some point) then you should be able to edit the checklist. Let me know if it still doesn't address the check/uncheck issue.

**Comment by jrkasprzyk** [comment]
Looks like the checkboxes work now, thanks!

**Comment by kbarnhart** [comment]
@dickinsonre a friendly reminder to complete your review and/or provide a quick update here on when you anticipate being able to complete it.

**Comment by kbarnhart** [comment]
@jrkasprzyk and @dickinsonre a friendly reminder to complete your review and/or provide a quick update here on when you anticipate being able to complete it. Thanks!

**Comment by jrkasprzyk** [comment]
My review is complete! I second the comment from @nickrsan about the example files listed. As a person with less GitHub experience, I got a little confused in the Usage statement because it refers to 'model.inp' in the initial example, and I am not sure if it is obvious what that model file is, or the fact that it would need to be in the working directory. It sounds like @nickrsan made an issue about finding the sample files in the documentation, so that is good.

**Comment by kbarnhart** [comment]
@jrkasprzyk thanks for completing your review! Glad to hear that changes made in response to @nickrsan 's comments helped with your review. 

@dickinsonre could you please provide an update on when you might complete your review. 

A note on proceedure: JOSS only requires two reviews, so if I don't hear from @dickinsonre in the next day or two, I will likely remove them as a reviewer and move this submission forward.

Thanks again to all for your participation in this JOSS review.

**Comment by katmratliff** [comment]
@jrkasprzyk thank you for your review and feedback! @kbarnhart let me know if we should go ahead and make a tagged release.

**Comment by kbarnhart** [comment]
@katmratliff not quite yet. I still need to do a final copy-edit on the paper. You should get that from me later today.

**Comment by katmratliff** [comment]
ok thanks @kbarnhart!

**Comment by kbarnhart** [comment]
@whedon remove @dickinsonre as reviewer

**Comment by whedon** [comment]
OK, @dickinsonre is no longer a reviewer

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by kbarnhart** [comment]
@whedon check references

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02292/joss.02292/10.21105.joss.02292.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3390/w8060259 is OK
- 10.1016/j.proeng.2014.11.503 is OK
- 10.1016/j.envsoft.2016.05.009 is OK
- 10.1061/9780784482360.006 is OK
- 10.1016/j.envsoft.2019.07.009 is OK
- 10.1061/JSWBAY.0000817 is OK
- 10.1016/j.envsoft.2018.12.004 is OK
- 10.1080/1573062X.2019.1611889 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kbarnhart** [comment]
@katmratliff - we are now at the final stage of the JOSS process. PySWMM is a fantastic contribution to surface water modeling and I am excited to see it published in JOSS. 

Attached is a PDF with some inline comments. [10.21105.joss.02292_barnhart_edits.pdf](https://github.com/openjournals/joss-reviews/files/5019179/10.21105.joss.02292_barnhart_edits.pdf) Edits/comments pertain to copyediting, reference formatting, acronym definition, and clarity. They are pretty minimal. Once you have addressed them (just link the PR to this thread), then go ahead and do the following steps:

- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

Once those steps are done, ping me here and I'll do my final steps and label this with "recommend accept" which flags the JOSS handling editor in chief who will mange the final publication steps. The EIC may request minor additional changes. Know also that there is a current effort to better standardize author affiliations in JOSS papers (openjournals/joss/issues/783). While nothing has been finalized, the EIC may request that affiliations be expanded (e.g., to include the country). (tagging @openjournals/joss-eics to see if they have any guidance at this point regarding affiliations that the authors of this contribution might address at the same time that they address my copyedits).

As always, let me know if you have any questions/concerns.

**Comment by katmratliff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02292/joss.02292/10.21105.joss.02292.pdf)

**Comment by katmratliff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02292/joss.02292/10.21105.joss.02292.pdf)

**Comment by katmratliff** [comment]
PySWMM [v0.6.1](https://github.com/OpenWaterAnalytics/pyswmm/releases/tag/v0.6.1) has now been released

**Comment by katmratliff** [comment]
The reviewed version has now been archived at [10.5281/zenodo.3972126](https://zenodo.org/record/3972126)

**Comment by katmratliff** [comment]
@kbarnhart a new release has been made of the reviewed code and it has been archived at Zenodo. I think we are good to go!

**Comment by katmratliff** [comment]
PySWMM [v0.6.2](https://github.com/OpenWaterAnalytics/pyswmm/releases/tag/v0.6.2) has now been released

**Comment by katmratliff** [comment]
The reviewed software has now been archived on Zenodo: [10.5281/zenodo.3972214](https://zenodo.org/record/3972214)

**Comment by katmratliff** [comment]
@kbarnhart a new release has been made and the reviewed software has been archived. I think we are good to go!

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02292/joss.02292/10.21105.joss.02292.pdf)

**Comment by kbarnhart** [comment]
@whedon set 10.5281/zenodo.3972214 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3972214" target="_blank">10.5281/zenodo.3972214</a> is the archive.

**Comment by kbarnhart** [comment]
@whedon set v0.6.2 as version

**Comment by whedon** [comment]
OK. v0.6.2 is the version.

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02292/joss.02292/10.21105.joss.02292.pdf)

**Comment by kbarnhart** [comment]
@whedon accept

@katmratliff thanks for making those changes and completing these last few steps. I've now marked this as ready for final processing by the handling Editor in Chief. 

@nickrsan @jrkasprzyk thank you for your reviews.

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3390/w8060259 is OK
- 10.1016/j.proeng.2014.11.503 is OK
- 10.1016/j.envsoft.2016.05.009 is OK
- 10.1061/9780784482360.006 is OK
- 10.1016/j.envsoft.2019.07.009 is OK
- 10.1061/JSWBAY.0000817 is OK
- 10.1016/j.envsoft.2018.12.004 is OK
- 10.1080/1573062X.2019.1611889 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1624

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1624, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1290794527997952001) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1625
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02292](https://doi.org/10.21105/joss.02292)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by katmratliff** [comment]
@kbarnhart thank you!!!!

**Comment by danielskatz** [comment]
Thanks to @nickrsan and @jrkasprzyk for reviewing and @kbarnhart for editing!

Congratulations to @katmratliff (Katherine Ratliff) and co-authors!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02292/status.svg)](https://doi.org/10.21105/joss.02292)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02292">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02292/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02292/status.svg
   :target: https://doi.org/10.21105/joss.02292
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02292/status.svg)](https://doi.org/10.21105/joss.02292)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
