### ISSUE TITLE
[PRE REVIEW]: tidyfst: Tidy Verbs for Fast Data Manipulation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2294]
**Submitting author:** @hope-data-science (<a href="http://orcid.org/0000-0002-4151-3764">Tian-Yuan Huang</a>)
**Repository:** <a href="https://github.com/hope-data-science/tidyfst" target ="_blank">https://github.com/hope-data-science/tidyfst</a>
**Version:** v0.9.7
**Editor:** @mikldk
**Reviewers:** @tomsing1, @rcannood
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @hope-data-science. **Currently, there isn't an JOSS editor assigned** to your paper.

@hope-data-science if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2294 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2294 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
👋 @hope-data-science - Thanks for your submission to JOSS. As described in our blog post announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by kyleniemeyer** [comment]
@hope-data-science it looks like the URL for the software repo does not load. Can you provide the correct URL?

**Comment by arfon** [comment]
> @hope-data-science it looks like the URL for the software repo does not load. Can you provide the correct URL?

I updated this.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2294 with the following error: 

 pandoc-citeproc: Cannot decode byte '\xff': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@hope-data-science - looks like there's some kind of encoding issue with your files here. Could you make sure you can get your paper to compile with this service while we're waiting to assign an editor: http://whedon.theoj.org

**Comment by hope-data-science** [comment]
@arfon Thank you for the prompt feedback. I've try to compile this link (<https://github.com/hope-data-science/tidyfst/tree/master/docs/JOSS>) and successed, but when I click and try to download the preview, it failed. Am I supposed to change anything in the submission system or make adjustment on the files in the Github repo? 

A Word version is also available here: <https://github.com/hope-data-science/tidyfst/blob/master/docs/tidyfst_JOSS.docx>. If there's any more questions, let me know.

Thanks.

**Comment by hope-data-science** [comment]
Below are the messages from the system:
![image](https://user-images.githubusercontent.com/32947502/83988571-3a71e800-a976-11ea-80b1-35c431fe2058.png)
![image](https://user-images.githubusercontent.com/32947502/83988606-51183f00-a976-11ea-811e-7cbfa9676bc4.png)

**Comment by dvanic** [comment]
I just came across this issue, and would love to be a reviewer for this (when it's ready for review/the formal process has kicked off).

**Comment by hope-data-science** [comment]
Thank you for the feedback. I have no idea how to advance the process at the current state.
Best.

BTW: A copy of the manuscript in MS WORD could be found at <https://github.com/hope-data-science/tidyfst/blob/master/docs/tidyfst_JOSS.docx>. I tried to compile files at <https://github.com/hope-data-science/tidyfst/tree/master/docs/JOSS> but failed to the PDF. Any hints?

**Comment by dvanic** [comment]
@hope-data-science You have an encoding issue. One possibility is that the "ç" character you have in your markdown is causing pandoc to flip - perhaps replace it with a c for now to test?

If not that one, I'd look at other things like quotes, symbols (@#brackets etc) that could be breaking pandoc.

**Comment by hope-data-science** [comment]
@dvanic Thanks, I've made this change in the manuscript. Hope it could help later.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2294 with the following error: 

 Error reading bibliography ./paper.bib (line 64, column 3):
unexpected "C"
expecting space or ","
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by labarba** [comment]
@hope-data-science — you can't have spaces in labels of bibles entries; please fix:
https://github.com/hope-data-science/tidyfst/blob/dc57addcb3629a57c33e874544809acdc869089d/docs/JOSS/paper.bib#L64

**Comment by hope-data-science** [comment]
@dvanic Thanks, I've fixed that now. Let me have a try.

**Comment by hope-data-science** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02294/joss.02294/10.21105.joss.02294.pdf)

**Comment by hope-data-science** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02294/joss.02294/10.21105.joss.02294.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @lorenanicole as editor

**Comment by whedon** [comment]
@lorenanicole has been invited to edit this submission.

**Comment by hope-data-science** [comment]
TODO list: 
1. Miss the citation of the package fst, add it in next correction.
2. Cite "R Core Team" correctly.

**Comment by mikldk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by lorenanicole** [comment]
Thanks @Kevin-Mattheus-Moerman for that! I already have 2 papers assigned to me so glad we settled on @mikldk as editor.

**Comment by mikldk** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.48 s (311.4 files/s, 62203.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            74           3675            957          17746
R                               54            638           2003           1739
Rmd                              8            276            561            705
CSS                              3             99             48            428
Markdown                         4             82              0            269
JavaScript                       3             64             32            256
TeX                              1             59              0             96
YAML                             1              1              0             13
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                           149           4894           3602          21263
-------------------------------------------------------------------------------


Statistical information for the repository '2294' was gathered on 2020/06/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Hope                             2           357              5          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Hope                        352           98.6          0.0                9.09
```

**Comment by mikldk** [comment]
@hope-data-science : Do you have any suggestions for reviewers?

**Comment by hope-data-science** [comment]
@mikldk Perhaps someone from this list: <https://github.com/hope-data-science/tidyfst/stargazers>. I think they might have the first-hand experience of using this package and make comments on it to make it better.

**Comment by hope-data-science** [comment]
Also, I recommend this folk (https://github.com/Atrebas). He has written a great post (from which I benefited from) on the related topic at <https://atrebas.github.io/post/2019-03-03-datatable-dplyr/>. I think he might be interested and give great suggestions.

**Comment by mikldk** [comment]
@tomsing1, @kellieotto: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by tomsing1** [comment]
@mikldk I am happy to review.

**Comment by mikldk** [comment]
@rcannood: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by rcannood** [comment]
@mikldk Sure!

**Comment by mikldk** [comment]
@whedon add @tomsing1 as reviewer

**Comment by mikldk** [comment]
@whedon add @rcannood as reviewer

**Comment by whedon** [comment]
OK, @rcannood is now a reviewer

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2388.

**Comment by hope-data-science** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02294/joss.02294/10.21105.joss.02294.pdf)
