### ISSUE TITLE
[PRE REVIEW]: kiwiPy: Robust, high-volume, messaging for big-data and computational science workflows

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2295]
**Submitting author:** @muhrin (<a href="http://orcid.org/0000-0001-6902-1289">Martin Uhrin</a>)
**Repository:** <a href="https://github.com/aiidateam/kiwipy" target ="_blank">https://github.com/aiidateam/kiwipy</a>
**Version:** v0.6.0
**Editor:** @danielskatz
**Reviewers:** @dghoshal-lbl, @uellue
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @muhrin. **Currently, there isn't an JOSS editor assigned** to your paper.

@muhrin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.14 s (391.0 files/s, 41959.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          34            866            653           2385
Jupyter Notebook                 4              0            737            178
TeX                              1             13              0            172
SVG                              1             19              8            149
reStructuredText                 6            120            119            100
YAML                             3             16              5             75
Markdown                         1             18              0             45
Bourne Shell                     1             24              4             30
DOS Batch                        1              8              1             26
make                             1              4              6              9
INI                              1              0              0              5
-------------------------------------------------------------------------------
SUM:                            54           1088           1533           3174
-------------------------------------------------------------------------------


Statistical information for the repository '2295' was gathered on 2020/06/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jason Eu                         1           226            177            2.25
Jason.Eu                         1             2              7            0.05
Martin Uhrin                   130         10609           6787           97.02
Sebastiaan Huber                19            81             40            0.67
cclauss                          1             1              1            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jason.Eu                    135         6750.0         12.7               49.63
Martin Uhrin               3734           35.2          8.4               10.28
Sebastiaan Huber             35           43.2         15.6                2.86
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1063/1.4812323 is OK
- 10.1007/s11837-013-0755-4 is OK
- 10.1016/j.commatsci.2012.02.005 is OK
- 10.1088/2515-7639/ab13bb is OK
- 10.1109/MCSE.2012.16 is OK
- 10.1002/cpe.3505 is OK
- 10.1016/j.commatsci.2015.09.013 is OK
- 10.21105/joss.01844 is OK
- 10.21105/joss.01844 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02295/joss.02295/10.21105.joss.02295.pdf)

**Comment by kyleniemeyer** [comment]
👋 @muhrin - Thanks for your submission to JOSS. As described in our blog post announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by muhrin** [comment]
Thanks @kyleniemeyer, no worries regarding the backlog - we're looking forward to your review.  I mention my coauthor, @sphuber, to bring him into the conversation.

**Comment by Kevin-Mattheus-Moerman** [comment]
@poulson @harpolea @dpsanders could one of you handle this submission? Thanks

**Comment by danielskatz** [comment]
I'll take this one

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @muhrin - if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).  I will also think about potential reviewers...

**Comment by danielskatz** [comment]
Also, the repository you entered when submitting (as shown at the top of the issue is https://github.com/aiidateam/kiwipy.git - I'm going to change this to https://github.com/aiidateam/kiwipy unless you object...)

**Comment by muhrin** [comment]
Thanks Daniel.  No objection re: repo change, this was a mistake.

I'll have a look at the list tomorrow and get back with some suitable candidates.

**Comment by muhrin** [comment]
Here are some usernames that came up that I feel could be suitable reviewers:

colbrydi
cmbiwer
uellue
alvarolopez
dghoshal-lbl

My main criteria were looking for reviewers with python as a preferred language, then some experience of big-data/HPC/workflows (which is the main application for kiwiPy) followed by those who had HPC/cloud/distributed systems expertise.

**Comment by danielskatz** [comment]
👋 @dghoshal-lbl - would you be willing to review this submission for JOSS?

**Comment by danielskatz** [comment]
👋 @uellue - would you be willing to review this submission for JOSS?

**Comment by danielskatz** [comment]
👋 @cmbiwer - would you be willing to review this submission for JOSS?

**Comment by dghoshal-lbl** [comment]
@danielskatz sure. I can review this submission.

**Comment by danielskatz** [comment]
Thanks @dghoshal-lbl - I'll assign you, but the review won't start until we get one more reviewer as well.

**Comment by danielskatz** [comment]
@whedon assign @dghoshal-lbl as reviewer

**Comment by whedon** [comment]
OK, @dghoshal-lbl is now a reviewer

**Comment by uellue** [comment]
> 👋 @uellue - would you be willing to review this submission for JOSS?

Yes, sure! :-)

**Comment by danielskatz** [comment]
Thank - I'll add you and we can get started

**Comment by danielskatz** [comment]
@whedon add @uellue as reviewer

**Comment by whedon** [comment]
OK, @uellue is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2351.
