### ISSUE TITLE
[PRE REVIEW]: PyMMS: Implementation of a non-numeric spacetime model with the Minkovsky metric

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2296]
**Submitting author:** @vgurianov (<a href="http://orcid.org/0000-0003-2667-4241">Vasyliy Gurianov</a>)
**Repository:** <a href="https://github.com/vgurianov/srt" target ="_blank">https://github.com/vgurianov/srt</a>
**Version:** v1.0.9
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @vgurianov. **Currently, there isn't an JOSS editor assigned** to your paper.

@vgurianov if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (359.4 files/s, 61102.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          12            808            629           2373
Markdown                        16            415              0           1559
HTML                             2              9              3             66
YAML                             4              2              2             41
TeX                              1              4              0             40
-------------------------------------------------------------------------------
SUM:                            35           1238            634           4079
-------------------------------------------------------------------------------


Statistical information for the repository '2296' was gathered on 2020/06/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Vasyliy I. Gurianov             53          8693           4883          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vasyliy I. Gurianov        3810           43.8          1.3               13.65
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02296/joss.02296/10.21105.joss.02296.pdf)

**Comment by kyleniemeyer** [comment]
👋 @vgurianov - Thanks for your submission to JOSS. As described in our blog post announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by vgurianov** [comment]
Some suggestions for potential reviewers.

This article will be of interest to those involved in simulate modeling and agent-based programming.
From the proposed list, this  is true for:
1.fdroessler (Molecular Dynamics Simulation, Computational Chemistry, Agent Based Models)
2.kavir1698 (Agent-based modeling, Computational biology, Bioinformatics)
And also, perhaps:
DARSakthi (Modeling, simulations, AI and ML, data analysis)
and
No (Computer codes in Physics)

**Comment by vgurianov** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02296/joss.02296/10.21105.joss.02296.pdf)

**Comment by arfon** [comment]
Closing this as a duplicate of https://github.com/openjournals/joss-reviews/issues/2346

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
