### ISSUE TITLE
[PRE REVIEW]: Implicit measures with reproducible results: The implicitMeasures package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2297]
**Submitting author:** @OttaviaE (<a href="http://orcid.org/0000-0001-8552-568X">Ottavia M. Epifania</a>)
**Repository:** <a href="https://github.com/OttaviaE/implicitMeasures" target ="_blank">https://github.com/OttaviaE/implicitMeasures</a>
**Version:** v0.1.3
**Editor:** @oliviaguest
**Reviewers:** @eirini-zormpa, @wjakethompson, @jflournoy
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @OttaviaE. **Currently, there isn't an JOSS editor assigned** to your paper.

@OttaviaE if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2297 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2297 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
@openjournals/dev any ideas why whedon can't find the paper here? Could it have anything to do with the 
```yaml
output: 
  html_document:
       keep_md: true
```
in the paper header?

**Comment by kyleniemeyer** [comment]
👋 @OttaviaE - Thanks for your submission to JOSS. As described in our blog post announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by OttaviaE** [comment]
@kyleniemeyer Okay thank you! Should I still indicate any preference for an editor?

**Comment by kyleniemeyer** [comment]
Hi @OttaviaE, sure, you may suggest someone, but who we ultimately ask/assign to edit also depends on editor availability and preference

**Comment by OttaviaE** [comment]
@kyleniemeyer I don't think I have any preference, so I'll let you decide! Thanks again

**Comment by oliviaguest** [comment]
Happy to take this on, if OK?

**Comment by OttaviaE** [comment]
Hey @oliviaguest that would be great, thank you!

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2297 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2297 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by oliviaguest** [comment]
I have no idea what is wrong with building the PDF? I assume this is a bug? @kyleniemeyer and @openjournals/dev are aware so I'll leave it for now, unless you have ideas, @OttaviaE?

But anyway while we wait, can you fix the Travis build badge, please here: https://github.com/OttaviaE/implicitMeasures/blob/master/README.md?

**Comment by oliviaguest** [comment]
PS: See: https://github.com/OttaviaE/implicitMeasures/pull/1

**Comment by oliviaguest** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by danielskatz** [comment]
The repository was incorrectly specified as https://github.com/OttaviaE/implicitMeasures/tree/master/inst rather than https://github.com/OttaviaE/implicitMeasures

I've changed it in this issue - but I'm not sure if it needs to be changed in database as well. cc @openjournals/dev

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02297/joss.02297/10.21105.joss.02297.pdf)

**Comment by danielskatz** [comment]
looks like that fixed it.

Also, @oliviaguest, I removed the waitlisted label, which you should do when you grab a submission of the list to edit in the future.

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1037/0022-3514.85.2.197 is OK
- 10.1080/19312458.2015.1096330 is OK
- 10.1037/1089-2699.6.1.101 is OK
- 10.1037/0022-3514.74.6.1464 is OK
- 10.1037/0022-3514.91.1.16 is OK
- 10.1177/0146167216684131 is OK
- 10.21105/joss.01764 is OK
- 10.4473/TPM27.2.4 is OK
- 10.31124/advance.11914416.v1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (734.0 files/s, 88363.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               20            120            855           1771
Markdown                         5             95              0            236
TeX                              2              4              0            186
Rmd                              5            196            340            166
YAML                             1              1              1              2
-------------------------------------------------------------------------------
SUM:                            33            416           1196           2361
-------------------------------------------------------------------------------


Statistical information for the repository '2297' was gathered on 2020/06/15.
No commited files with the specified extensions were found.
```

**Comment by oliviaguest** [comment]
@danielskatz great, didn't know that! Thank you so much for all the help as usual! 😊

**Comment by OttaviaE** [comment]
> PS: See: [OttaviaE/implicitMeasures#1](https://github.com/OttaviaE/implicitMeasures/pull/1)

Hey @oliviaguest I think I solved the Travis issue, glad to see that also the pdf generation went well, thanks @danielskatz

**Comment by oliviaguest** [comment]
@OttaviaE fabulous! 🌼

**Comment by oliviaguest** [comment]
@OttaviaE I have sent off some invitations but it would be great if you have some ideas too. So far no luck, but I of course will keep trying. Any names you have will be highly useful in finding a good set of skilled reviewers since IATs are quite tricky to evaluate, I think? Anyway, either way: names would be much appreciated. 😊

**Comment by OttaviaE** [comment]
Hey @oliviaguest thank you for your work! Yeah I know the struggle, I had problems finding reviewers also when I submitted a paper for a shiny app always related to the IAT... Anyways, I think I found some names, should I mention directly them here? 
Thanks again =)

**Comment by oliviaguest** [comment]
@OttaviaE Yes please! ✨

**Comment by OttaviaE** [comment]
Hey @mikerspencer and @mmrabe, @oliviaguest  and I were wondering whether you wanted to review my R package for computing implicit measures scores and its related paper....? Thanks!

**Comment by oliviaguest** [comment]
Ah, sorry. I should have said not to tag them (see top):

> @OttaviaE if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, this list of people have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

I apologise — my fault for not being clear and not reminding you. No worries though. I am sure they are understanding and aware of how to unsubscribe. Sorry.

If you have any other names that are not on that list, also feel free to mention them. I think it might be good to find IAT experts who might be less (explicitly) expert in R per se. Since such people might be your users too, right?

**Comment by danielskatz** [comment]
Just to make it clear - Choosing, inviting, and assigning reviewers is part of the job of the editor, though it's typical that she asks the author for suggestions, which may or may not be used. The authors can suggest potential reviewers, but should not ask them to review.

**Comment by oliviaguest** [comment]
My fault @danielskatz because I didn't realise/think of the ambiguity between tag and mention — I was hoping just for emails/[user]names.

**Comment by OttaviaE** [comment]
Sorry @danielskatz and @oliviaguest, this is my bad cause I forgot what was written on the first thread regarding the mentioning/tag of the reviewers. I apologise for that.

**Comment by oliviaguest** [comment]
Do not worry! It's a non-issue, totally an innocent mistake.

**Comment by OttaviaE** [comment]
@oliviaguest I was thinking maybe we can ask again to one of the reviewer that reviewed my Shiny app... worst case sceanario he can mention someone pretty familiar with the IAT & R. Sorry again

**Comment by oliviaguest** [comment]
> Hey @mikerspencer and @mmrabe, @oliviaguest and I were wondering whether you wanted to review my R package for computing implicit measures scores and its related paper....? Thanks!

FWIW if either or both of them want to review this, I think that's a good idea BTW. So I am happy to hear from them if they do check this thread. Otherwise, I will email them soon — I have already sent quite a few emails today for this, so maybe people will get back to us.

> @oliviaguest I was thinking maybe we can ask again to one of the reviewer that reviewed my Shiny app... worst case sceanario he can mention someone pretty familiar with the IAT & R. Sorry again

Drop their details here (ideally their website?) please! Good idea!

**Comment by OttaviaE** [comment]
@oliviaguest okay just to clear the air and prevent me from doing any other silly mistakes... can I just write it down his e-mail adrees here? he is in the list of the JOSS reviewers

**Comment by oliviaguest** [comment]
@OttaviaE you can write anything except actually @-tagging, get me? See this as "safe" example: https://github.com/openjournals/joss-reviews/issues/2269#issuecomment-644718399

**Comment by OttaviaE** [comment]
@oliviaguest got you, thanks. tomfaulkenberry and benmarwick were the reviewers for my shiny app, they looked pretty familiar with both R and the IAT. Maybe they are available or they can suggest someone.

**Comment by oliviaguest** [comment]
@whedon add @eirini-zormpa as reviewer

**Comment by whedon** [comment]
OK, @eirini-zormpa is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @wjakethompson as reviewer

**Comment by whedon** [comment]
OK, @wjakethompson is now a reviewer

**Comment by mikerspencer** [comment]
Thanks for the invite. I'm reviewing another submission at the moment, which is all I've time for. Best of luck.

**Comment by oliviaguest** [comment]
@whedon add @jflournoy as reviewer

**Comment by whedon** [comment]
OK, @jflournoy is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2394.

**Comment by oliviaguest** [comment]
👋  @eirini-zormpa, @wjakethompson, @jflournoy: please go to #2394 to get the review started! 🥳
