### ISSUE TITLE
Submission: Scowl: a Scala DSL for programming with the OWL API

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#23]
**Submitting author:** @balhoff (<a href="http://orcid.org/0000-0002-8688-6599">James P. Balhoff</a>)
**Repository:** <a href="https://github.com/phenoscape/scowl" target ="_blank">https://github.com/phenoscape/scowl</a>
**Version:** v1.1
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.51556" target ="_blank">http://dx.doi.org/10.5281/zenodo.51556</a>

## Status

[![status](http://joss.theoj.org/papers/1b9d09aab8754997884a04c081cfc019/status.svg)](http://joss.theoj.org/papers/1b9d09aab8754997884a04c081cfc019)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/1b9d09aab8754997884a04c081cfc019"><img src="http://joss.theoj.org/papers/1b9d09aab8754997884a04c081cfc019/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/1b9d09aab8754997884a04c081cfc019/status.svg)](http://joss.theoj.org/papers/1b9d09aab8754997884a04c081cfc019)
```

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/phenoscape/scowl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.1)?
- [x] **Archive:** Does the <a target="_blank" href="http://dx.doi.org/10.5281/zenodo.51556">software archive</a> resolve?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have the performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Compiled paper PDF: [10.21105.joss.00023.pdf](https://github.com/openjournals/joss-reviews/files/269284/10.21105.joss.00023.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by xuanxu** [comment]
:hand: I am reviewing this

**Comment by xuanxu** [comment]
Review finished, every point is checked but one:

### Community guidelines
There is no mention on how to contribute, report bugs or get support. 

Please add a 'How to contribute' section to the README with at least a brief statement encouraging posible contributors to help pointing them to open a new github issue. Add also information on how to report a problem (opening an issue should be OK) and seek support (ideas: mailing list, contact email, github issue with a specific tag). 
Even better would be to include a CONTRIBUTING.md file with detailed instructions. 

### Recommendation:
I recommend publication after some minor revisions: contributing guidelines should be added to the documentation.

**Comment by arfon** [comment]
Thanks for the review @xuanxu! @balhoff - could you take a look at the reviewer's responses and see what you think?

**Comment by balhoff** [comment]
Thanks @xuanxu! I updated the [README](https://github.com/phenoscape/scowl#question-or-problem) and added [CONTRIBUTING.md](https://github.com/phenoscape/scowl/blob/master/CONTRIBUTING.md). Please let me know what you think.

I also updated [paper.bib](https://github.com/phenoscape/scowl/blob/master/paper.bib), hoping to eliminate duplicate URLs in the reference output.

**Comment by xuanxu** [comment]
Thanks @balhoff! It looks good to me. 
All points checked, this is publication-ready @arfon.

**Comment by arfon** [comment]
Thanks for the review @xuanxu! 

@balhoff http://dx.doi.org/10.21105/joss.00023 🎉 🚀 :boom:

**Comment by balhoff** [comment]
Great! @arfon would it be possible to regenerate the PDF at this point? I had made some tweaks to the references file hoping to remove duplicated URLs from the output.

**Comment by arfon** [comment]
@balhoff - I regenerated it when I generate the DOI: https://github.com/openjournals/joss-papers/blob/master/joss.00023/10.21105.joss.00023.pdf

Does ☝️ look good? If not, we can update it.

**Comment by balhoff** [comment]
@arfon I just updated paper.bib to remove the `howpublished` field. The website citations were showing the URL twice. Hopefully this will fix it. Can you regenerate? Thanks!

**Comment by arfon** [comment]
Is this better? https://github.com/openjournals/joss-papers/blob/master/joss.00023/10.21105.joss.00023.pdf

**Comment by balhoff** [comment]
Yes, thanks!
